In [ ]:
from pathlib import Path
import shutil
import zipfile
import os

inputs = Path("/kaggle/input")
destination = Path("/kaggle/working/BTP")

matches = list(inputs.rglob("run_public252.py"))

if matches:
    source = matches[0].parent
    shutil.copytree(source, destination, dirs_exist_ok=True)
else:
    archives = list(inputs.rglob("*.zip"))
    code_found = False

    for archive in archives:
        with zipfile.ZipFile(archive) as z:
            if "BTP/run_public252.py" in z.namelist():
                # Extract only our code archive.
                target = Path("/kaggle/working").resolve()
                for name in z.namelist():
                    if not (target / name).resolve().is_relative_to(target):
                        raise ValueError("Unsafe archive path")
                z.extractall(target)
                code_found = True
                break

    if not code_found:
        print("Attached input folders:", list(inputs.iterdir()))
        print("ZIP files found:", archives)
        raise RuntimeError(
            "BTP code is not attached. Add the dataset containing BTP-code.zip."
        )

assert (destination / "run_public252.py").is_file()
os.chdir(destination)
print("Code ready:", os.getcwd())

In [ ]:
import importlib
from pathlib import Path

for name in [
    "torch", "torchvision", "numpy", "pandas",
    "scipy", "skimage", "PIL", "einops", "torchmetrics", "tqdm"
]:
    try:
        module = importlib.import_module(name)
        print(f"{name}: OK ({getattr(module, '__version__', 'unknown')})")
    except Exception as error:
        print(f"{name}: FAILED — {error}")

import torch
print("\nCUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:", round(
        torch.cuda.get_device_properties(0).total_memory / 1024**3, 1
    ), "GB")

roots = [
    p.parent
    for p in Path("/kaggle/input").rglob("train_data.csv")
    if (p.parent / "visible_28").is_dir()
    and (p.parent / "labels").is_dir()
]

print("\nPrepared dataset folders:", roots)

In [ ]:
from pathlib import Path
import subprocess
import sys

DATA_ROOT = Path("/kaggle/input/datasets/arnavnigamd/btp-data/public252")

def run(script, *args):
    subprocess.run(
        [sys.executable, script, *map(str, args)],
        cwd="/kaggle/working/BTP",
        check=True,
    )

run("verify_evaluation.py")
run("run_public252.py", "--root", DATA_ROOT)
run("verify_portability.py", "--root", DATA_ROOT)
run("verify_public252_pipeline.py", "--root", DATA_ROOT)

In [ ]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
import subprocess
import sys
from datetime import datetime

DATA_ROOT = "/kaggle/input/datasets/arnavnigamd/btp-data/public252"
OUT = "/kaggle/working/gpu_smoke_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "gpu_smoke.py",
        "--root", DATA_ROOT,
        "--out", OUT,
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

In [ ]:
import subprocess
import sys
from datetime import datetime

OUT = "/kaggle/working/fixed_crop_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "diagnostic_public252.py",
        "--root", "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--out", OUT,
        "--transpose-image",
        "--steps", "200",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Diagnostic results:", OUT)

In [ ]:
from IPython.display import display, Image

display(Image(
    filename="/kaggle/working/fixed_crop_20260917_144904/predictions.png"
))

In [ ]:
import subprocess
import sys
from datetime import datetime

OUT = "/kaggle/working/fixed_crop_1000_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "diagnostic_public252.py",
        "--root", "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--out", OUT,
        "--transpose-image",
        "--steps", "1000",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Results:", OUT)

In [ ]:
from pathlib import Path
from IPython.display import display, Image
import json

run_dir = Path("/kaggle/working/fixed_crop_1000_20260917_145850")

metrics = json.loads((run_dir / "metrics.json").read_text())
print("Final step:", metrics[-1]["step"])
print("Final mIoU:", metrics[-1]["foreground_miou_present"])

display(Image(filename=str(run_dir / "predictions.png")))

In [ ]:
from pathlib import Path
import shutil
from IPython.display import FileLink, display

run_dir = Path("/kaggle/working/fixed_crop_1000_20260917_145850")
assert run_dir.is_dir(), "Run folder not found"

archive = shutil.make_archive(
    "/kaggle/working/fixed_crop_1000_backup",
    "zip",
    root_dir=run_dir.parent,
    base_dir=run_dir.name,
)

display(FileLink(archive))

##version 2

In [ ]:
from pathlib import Path
import shutil, zipfile, os

inputs = Path('/kaggle/input')
working = Path('/kaggle/working')

def safe_extract(archive, target):
    target.mkdir(parents=True, exist_ok=False)
    with zipfile.ZipFile(archive) as z:
        for name in z.namelist():
            if not (target / name).resolve().is_relative_to(target.resolve()):
                raise ValueError('Unsafe ZIP member')
        z.extractall(target)

code = list(inputs.rglob('compare_diagnostic_lr.py'))
if not code:
    for archive in inputs.rglob('*.zip'):
        with zipfile.ZipFile(archive) as z:
            is_code = 'BTP/compare_diagnostic_lr.py' in z.namelist()
        if is_code:
            target = working / 'lr_code_unpacked'
            safe_extract(archive, target)
            code.extend(target.rglob('compare_diagnostic_lr.py'))
assert len(code) == 1, f'Expected one updated code input: {code}'
shutil.copytree(code[0].parent, working/'BTP', dirs_exist_ok=True)
os.chdir(working/'BTP')

run_name = 'fixed_crop_1000_20260917_145850'
runs = [p.parent for p in inputs.rglob('diagnostic_checkpoint.pt')
        if p.parent.name == run_name]
if not runs:
    for archive in inputs.rglob('*.zip'):
        with zipfile.ZipFile(archive) as z:
            is_run = f'{run_name}/diagnostic_checkpoint.pt' in z.namelist()
        if is_run:
            target = working / 'reference_unpacked'
            safe_extract(archive, target)
            runs.append(target/run_name)
assert len(runs) == 1, f'Expected one saved 1,000-step run: {runs}'
REFERENCE_RUN = runs[0]
DATA_ROOT = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert (DATA_ROOT/'train_data.csv').is_file()
print('Code ready; reference:', REFERENCE_RUN)

In [ ]:
import subprocess
import sys
import torch
from pathlib import Path
from datetime import datetime

assert torch.cuda.is_available(), "Enable GPU T4 ×2 first"

DATA_ROOT = Path("/kaggle/input/datasets/arnavnigamd/btp-data/public252")
REFERENCE_RUN = Path(
    "/kaggle/input/datasets/arnavnigamd/checkpoint1/"
    "fixed_crop_1000_20260917_145850"
)
OUT = Path(
    "/kaggle/working/lr_comparison_"
    + datetime.now().strftime("%Y%m%d_%H%M%S")
)

subprocess.run(
    [sys.executable, "verify_diagnostic_comparison.py"],
    cwd="/kaggle/working/BTP",
    check=True,
)

subprocess.run(
    [
        sys.executable, "compare_diagnostic_lr.py",
        "--root", str(DATA_ROOT),
        "--from-run", str(REFERENCE_RUN),
        "--out", str(OUT),
        "--steps", "500",
        "--eval-every", "10",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Results:", OUT)
print((OUT / "comparison_summary.json").read_text())

In [ ]:
import subprocess
import sys
from datetime import datetime

checkpoint = (
    "/kaggle/working/lr_comparison_20260917_160952/"
    "control_4e-4/diagnostic_checkpoint.pt"
)

subprocess.run(
    [
        sys.executable, "test.py",
        "--data_root",
        "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--transpose_image",
        "--eval_split", "val",
        "--limit", "1",
        "--pretrained_model_path", checkpoint,
        "--outf", "/kaggle/working/evaluations",
        "--name", "full_frame_smoke_" + datetime.now().strftime("%H%M%S"),
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

In [ ]:
from pathlib import Path
from IPython.display import display, Image

comparison = Path("/kaggle/working/lr_comparison_20260917_160952")

for arm in ["control_4e-4", "low_4e-5"]:
    path = comparison / arm / "best_predictions.png"
    print(arm)
    if path.is_file():
        display(Image(filename=str(path)))
    else:
        print("Restore the saved comparison folder and update its path.")

In [ ]:
from pathlib import Path

for root in [Path("/kaggle/input"), Path("/kaggle/working")]:
    print(f"\nSearching {root}")
    for pattern in ["best_predictions.png", "comparison_summary.json", "*.zip"]:
        for path in root.rglob(pattern):
            print(path)

In [ ]:
from pathlib import Path
import shutil
import zipfile

inputs = Path("/kaggle/input")
target = Path("/kaggle/working/BTP")

# Find an already-extracted copy of the updated code.
sources = [
    p.parent for p in inputs.rglob("run_public252.py")
    if "--stop-after-epoch" in p.read_text()
]

if sources:
    shutil.copytree(sources[0], target, dirs_exist_ok=True)
else:
    candidates = []
    for archive in inputs.rglob("*.zip"):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            name = "BTP/run_public252.py"
            if name in z.namelist():
                if b"--stop-after-epoch" in z.read(name):
                    candidates.append(archive)

    if not candidates:
        raise FileNotFoundError(
            "Attach BTP-code-pilot.zip through Add Input, then rerun this cell."
        )

    with zipfile.ZipFile(candidates[0]) as z:
        destination = Path("/kaggle/working").resolve()
        for member in z.infolist():
            resolved = (destination / member.filename).resolve()
            if not resolved.is_relative_to(destination):
                raise ValueError("Unsafe archive path")
        z.extractall(destination)

assert (target / "run_public252.py").is_file()
assert "--stop-after-epoch" in (target / "run_public252.py").read_text()
print("Updated pilot code ready:", target)

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_pilot_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '3', '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-3 model folder.
import zipfile
expected = 'baseline_pilot_20260917_190720'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-3 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_to_epoch10_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '10', '--resume', str(REFERENCE), '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-10 model folder.
import zipfile
expected = 'baseline_to_epoch10_20260917_195856'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-10 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_to_epoch50_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '50', '--resume', str(REFERENCE), '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
import json
for path in sorted((RUN / 'result').glob('*_training.json')):
    print(json.dumps(json.loads(path.read_text()), indent=2))
print('Download the complete archive, then share these metrics and the per-class segmentation CSVs.')

In [ ]:
from pathlib import Path
import shutil
import zipfile

inputs = Path("/kaggle/input")
destination = Path("/kaggle/working").resolve()
code = destination / "BTP"

sources = [
    p.parent for p in inputs.rglob("run_public252.py")
    if "--stop-after-epoch" in p.read_text()
]

if sources:
    shutil.copytree(sources[0], code, dirs_exist_ok=True)
else:
    found = False
    for archive in inputs.rglob("*.zip"):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            entry = "BTP/run_public252.py"
            if entry not in z.namelist():
                continue
            if b"--stop-after-epoch" not in z.read(entry):
                continue
            for member in z.infolist():
                if not (destination / member.filename).resolve().is_relative_to(destination):
                    raise ValueError("Unsafe archive path")
            z.extractall(destination)
            found = True
            break

    assert found, "Attach BTP-code-pilot.zip through Add Input, then rerun."

assert (code / "test.py").is_file()
print("Code ready:", code)

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-50 model folder.
import zipfile
expected = 'baseline_to_epoch50_20260917_204827'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-50 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import shutil
OUT = Path('/kaggle/working') / ('checkpoint_audit_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
OUT.mkdir()
try:
    for name, weights in [('best_iou_a', 'best_iou.pth'), ('best_iou_b', 'best_iou.pth'), ('last_epoch50', 'last.pt')]:
        subprocess.run([sys.executable, '-u', 'test.py', '--data_root', str(DATA),
            '--transpose_image', '--eval_split', 'val', '--pretrained_model_path', str(REFERENCE.with_name(weights)),
            '--outf', str(OUT), '--name', name], cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
    display(FileLink(archive))
    print('Download this evaluation archive for comparison:', archive)

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-paired')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
if not CODE.exists():
    sources = list(INPUTS.rglob('paired_full_training.py'))
    if len(sources) == 1:
        shutil.copytree(sources[0].parent, CODE)
    else:
        found = []
        for archive in INPUTS.rglob('*.zip'):
            if zipfile.is_zipfile(archive):
                with zipfile.ZipFile(archive) as z:
                    if 'BTP/paired_full_training.py' in z.namelist(): found.append(archive)
        assert len(found) == 1, 'Attach exactly one BTP-code-paired-full.zip input.'
        staging = Path('/kaggle/working/paired_code_extract')
        staging.mkdir(exist_ok=False)
        with zipfile.ZipFile(found[0]) as z: safe_extract(z, staging)
        shutil.copytree(staging / 'BTP', CODE)
assert (CODE / 'paired_full_training.py').is_file()
expected = 'baseline_to_epoch50_20260917_204827'
refs = list(INPUTS.rglob(expected + '/model/last.pt'))
if not refs:
    for archive in INPUTS.rglob('*.zip'):
        if not zipfile.is_zipfile(archive): continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' in z.namelist():
                dest = Path('/kaggle/working/paired_reference')
                safe_extract(z, dest)
                refs = [dest / expected / 'model/last.pt']
                break
assert len(refs) == 1, 'Attach the complete epoch50 run ZIP or extracted folder.'
REFERENCE = refs[0].parent.parent
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
import torch
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Code:', CODE, 'Reference:', REFERENCE, 'GPU:', torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'verify_paired_full_training.py'], cwd=CODE, check=True)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
OUT = Path('/kaggle/working') / ('paired_full_lr_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
try:
    subprocess.run([sys.executable, '-u', 'paired_full_training.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{OUT.name}/{arm}/model/{name}' for arm in ['control','quarter_lr']
                for name in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{OUT.name}/{arm}/model/{name}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download the complete ZIP before closing the session. Check logs for successful epoch60 completion in BOTH arms.')

In [ ]:
import json
summary = json.loads((OUT / 'comparison_summary.json').read_text())
for arm, result in summary['arms'].items():
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))
assert set(summary['arms']) == {'control', 'quarter_lr'}, 'Comparison is incomplete.'

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-paired')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
if not CODE.exists():
    sources = list(INPUTS.rglob('paired_full_training.py'))
    if len(sources) == 1:
        shutil.copytree(sources[0].parent, CODE)
    else:
        found = []
        for archive in INPUTS.rglob('*.zip'):
            if zipfile.is_zipfile(archive):
                with zipfile.ZipFile(archive) as z:
                    if 'BTP/paired_full_training.py' in z.namelist(): found.append(archive)
        assert len(found) == 1, 'Attach exactly one BTP-code-paired-full.zip input.'
        staging = Path('/kaggle/working/paired_code_extract')
        staging.mkdir(exist_ok=False)
        with zipfile.ZipFile(found[0]) as z: safe_extract(z, staging)
        shutil.copytree(staging / 'BTP', CODE)
assert (CODE / 'paired_full_training.py').is_file()
import json, hashlib, math
import torch
expected = 'paired_full_lr_20260918_065140'
relative = expected + '/quarter_lr/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach paired_full_lr_20260918_065140.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 60
expected_config = dict(learning_rate=0.0001, max_epoch=500, batch_size=1,
                       workers=0, seed=3407, transpose_image=True,
                       method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Unexpected checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 60
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Resuming quarter-rate checkpoint:', CHECKPOINT)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Saved best metrics:', state['best'])
del state
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU before training.'
print('GPU:', torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above; the next cell resumes the quarter schedule, not the printed default schedule.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'quarter_lr_to_epoch100_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
shutil.copy2(CODE / 'public252-v1.json', OUT / 'dataset_protocol.json')
provenance = {
    'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
    'source_epoch': 60, 'stop_after_epoch': 100, 'arm': 'quarter_lr',
    'note': 'Restore saved Adam/scaler/RNG and quarter-scaled500-epoch scheduler without rescaling again.',
    'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
                      for f in ['train.py', 'opt.py', 'training_state.py', 'dataset.py']}
}
(OUT / 'continuation.json').write_text(json.dumps(provenance, indent=2))
command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
    '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
    '--learning_rate', '0.0001', '--max_epoch', '500', '--stop_after_epoch', '100',
    '--resume', str(CHECKPOINT), '--outf', str(OUT.parent) + '/', '--name', NAME]
try:
    subprocess.run(command, cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{NAME}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
                   if f'{NAME}/model/{f}' not in z.namelist()]
    print('Archive:', archive, 'Missing checkpoint files:', missing)
    if (OUT / 'model/last.pt').is_file():
        saved = torch.load(OUT / 'model/last.pt', map_location='cpu', weights_only=True)
        print('Saved epoch:', saved['epoch'], 'Best metrics:', saved['best'])
        del saved
    display(FileLink(archive))
    print('Download the complete archive before stopping the session. Check saved epoch is100; a partial run also creates an archive.')

In [ ]:
records = [json.loads(p.read_text()) for p in sorted((OUT / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(61,101)), 'Training did not finish all40 epochs.'
print('Final epoch:', json.dumps(records[-1], indent=2))
print('Best mIoU among new epochs:', max(records, key=lambda r: r['val_foreground_miou_all22']))
print('AMP skips in new epochs:', sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import os
import shutil
import zipfile
from IPython.display import display, FileLink

working = Path("/kaggle/working")
runs = [
    p for p in working.glob("quarter_lr_to_epoch100_*")
    if p.is_dir() and (p / "model/last.pt").is_file()
]
assert runs, "No saved run found. Keep this session open and share the output."

run = max(runs, key=lambda p: (p / "model/last.pt").stat().st_mtime)
archive = run.with_suffix(".zip")

# Recreate the archive from the saved run.
shutil.make_archive(
    str(run), "zip", root_dir=run.parent, base_dir=run.name
)

with zipfile.ZipFile(archive) as z:
    assert z.testzip() is None, "Archive integrity check failed"

print("ZIP:", archive)
print(f"Size: {archive.stat().st_size / 1024**2:.1f} MiB")

os.chdir(working)
display(FileLink(archive.name))

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-weak-audit')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = "parser.add_argument('--save_segmentation'"
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'test.py'):
    sources = [p.parent for p in INPUTS.rglob('test.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/test.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-weak-audit.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'test.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
CHECKPOINT = CHECKPOINT.with_name('best_iou.pth')
assert '--save_segmentation' in (CODE / 'test.py').read_text(), 'Attach the updated BTP-code-weak-audit.zip.'
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Evaluating saved best segmentation checkpoint:', CHECKPOINT)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'weak_class_audit_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
try:
    subprocess.run([sys.executable, '-u', 'test.py', '--data_root', str(DATA),
        '--transpose_image', '--eval_split', 'val', '--save_segmentation',
        '--pretrained_model_path', str(CHECKPOINT), '--outf', str(OUT), '--name', 'best_epoch96'], cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    import os
    os.chdir('/kaggle/working')
    print('Download:', archive)
    display(FileLink(Path(archive).name))

In [ ]:
import numpy as np
import sys
sys.path.insert(0,str(CODE))
from dataset import get_class_names
folder = OUT / 'best_epoch96/evaluation_val'
meta = json.loads((folder / 'evaluation.json').read_text())
assert meta['status']=='completed' and meta['scene_count']==25
hist = np.load(folder / 'confusion_matrix.npy')
classes = get_class_names()
for k in [9,12,17,22]:
    total = hist[k].sum()
    print(classes[k], 'ground-truth pixels:', int(total))
    print([(classes[j], round(100*hist[k,j]/total,2)) for j in np.argsort(hist[k])[::-1][:5]])
print('Share the downloaded ZIP; it contains all25 previews and per-scene confusion matrices, without reconstructed HSI cubes.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-training-diagnostic')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Training-only inference diagnostic; fixed class-rich crops'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'diagnose_training_classes.py'):
    sources = [p.parent for p in INPUTS.rglob('diagnose_training_classes.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/diagnose_training_classes.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-training-diagnostic.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'diagnose_training_classes.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
CHECKPOINT = CHECKPOINT.with_name('best_iou.pth')
assert (CODE / 'diagnose_training_classes.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Evaluating saved best segmentation checkpoint:', CHECKPOINT)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'training_class_diagnostic_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'diagnose_training_classes.py', '--root', str(DATA),
        '--checkpoint', str(CHECKPOINT), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z: assert z.testzip() is None
        import os
        os.chdir('/kaggle/working')
        print('Download:', archive)
        display(FileLink(Path(archive).name))

In [ ]:
record = json.loads((OUT / 'diagnostic.json').read_text())
assert record.get('status') == 'completed', 'Diagnostic did not finish.'
for row in json.loads((OUT / 'summary.json').read_text()):
    print(row['class_id'],row['scene'],row['mode'],
          'IoU:',round(100*row['target_iou'],2),'recall:',round(100*row['target_recall'],2))
print('These are selected TRAINING-scene diagnostics, not validation or test scores.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-loss-pair')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Matched epoch101-110 segmentation-loss experiment'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'paired_loss_weight.py'):
    sources = [p.parent for p in INPUTS.rglob('paired_loss_weight.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/paired_loss_weight.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-loss-pair.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'paired_loss_weight.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'paired_loss_weight.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Epoch100 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_loss_pair.py'],cwd=CODE,check=True)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'paired_loss_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'paired_loss_weight.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{NAME}/{arm}/model/{file}' for arm in ['control_seg1e-4','higher_seg1e-3']
                for file in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{NAME}/{arm}/model/{file}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        import os
        os.chdir('/kaggle/working')
        display(FileLink(Path(archive).name))
        print('Download before ending the session. Confirm BOTH arms reached epoch110.')

In [ ]:
summary = json.loads((OUT / 'comparison_summary.json').read_text())
assert set(summary['arms']) == {'control_seg1e-4','higher_seg1e-3'}, 'Incomplete comparison'
for arm, result in summary['arms'].items():
    assert result['final']['epoch'] == 110
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))

/////////////////////////////////////////

In [2]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Epoch100 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)

Epoch100 reference: /kaggle/input/datasets/arnavnigamd/checkpoint6/quarter_lr_to_epoch100_20260918_094320
PASS:22-class support, aligned crops/flips, deterministic replay, no RNG consumed by index building, baseline crop branch unchanged.

CompletedProcess(args=['/usr/bin/python3', 'verify_balanced_sampling.py'], returncode=0)

In [3]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'balanced_sampling_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_sampling_experiment.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{NAME}/balanced50/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{NAME}/balanced50/model/{f}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        import os
        os.chdir('/kaggle/working')
        display(FileLink(Path(archive).name))
        print('Download the complete ZIP before ending the session.')

{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/balanced_sampling_20260922_131859/', name='balanced50', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/working/balanced_sampling_20260922_131859/initial_state/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=110, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-22 13:20:36,259 - INFO: Resuming after epoch 100

Epoch 101/500 | Batch 10/202 | Rec 0.001275 | Seg 0.507494 | Elapsed 0.6m | ETA 11.3m
Epoch 101/500 | Batch 20/202 | Rec 0.001360 | Seg 0.556372 | Elapsed 0.9m | ETA 8.1m
Epoch 101/500 | Batch 30/202 | Rec 0.001405 | Seg 0.565463 | Elapsed 1.2m | ETA 7.0m
Epoch 101/500 | Batch 40/202 | Rec 0.001388 | Seg 0.565884 | Elapsed 1.5m | ETA 6.1m
Epoch 101/500 | Batch 50/202 | Rec 0.001413 | Seg 0.540606 | Elapsed 1.8m | ETA 5.5m
Epoch 101/500 | Batch 60/202 | Rec 0.001386 | Seg 0.524814 | Elapsed 2.1m | ETA 5.0m
Epoch 101/500 | Batch 70/202 | Rec 0.001385 | Seg 0.525357 | Elapsed 2.4m | ETA 4.5m
Epoch 101/500 | Batch 80/202 | Rec 0.001353 | Seg 0.512432 | Elapsed 2.7m | ETA 4.1m
Epoch 101/500 | Batch 90/202 | Rec 0.001356 | Seg 0.516476 | Elapsed 3.0m | ETA 3.7m
Epoch 101/500 | Batch 100/202 | Rec 0.001357 | Seg 0.524314 | Elapsed 3.3m | ETA 3.3m
Epoch 101/500 | Batch 110/202 | Rec 0.001344 | Seg 0.511227 | Elapsed 3.5m | ETA 3.0m
Epoch 101/500 | Batch 120/202 | Rec 0.001341 | Seg 0.511161 | Elapsed 3.8m | ETA 2.6m
Epoch 101/500 | Batch 130/202 | Rec 0.001331 | Seg 0.512516 | Elapsed 4.1m | ETA 2.3m
Epoch 101/500 | Batch 140/202 | Rec 0.001331 | Seg 0.521914 | Elapsed 4.3m | ETA 1.9m
Epoch 101/500 | Batch 150/202 | Rec 0.001352 | Seg 0.524308 | Elapsed 4.6m | ETA 1.6m
Epoch 101/500 | Batch 160/202 | Rec 0.001343 | Seg 0.527401 | Elapsed 4.9m | ETA 1.3m
Epoch 101/500 | Batch 170/202 | Rec 0.001334 | Seg 0.522595 | Elapsed 5.2m | ETA 1.0m
Epoch 101/500 | Batch 180/202 | Rec 0.001339 | Seg 0.523896 | Elapsed 5.4m | ETA 0.7m
Epoch 101/500 | Batch 190/202 | Rec 0.001345 | Seg 0.524276 | Elapsed 5.6m | ETA 0.4m
Epoch 101/500 | Batch 200/202 | Rec 0.001335 | Seg 0.523960 | Elapsed 5.9m | ETA 0.1m
Epoch 101/500 | Batch 202/202 | Rec 0.001335 | Seg 0.523789 | Elapsed 6.0m | ETA 0.0m

2026-09-22 13:26:33,289 - INFO: Rec loss: 0.0013349367131877893
2026-09-22 13:26:33,289 - INFO: Seg loss: 0.5237891542734486
2026-09-22 13:26:33,290 - INFO: λ_rec: 1
2026-09-22 13:26:33,290 - INFO: λ_seg: 0.0001
2026-09-22 13:28:08,785 - INFO: -------------------Epoch: 101------------------------
2026-09-22 13:28:08,796 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.252942  0.964178  0.000307
2026-09-22 13:28:08,803 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993502  0.996691  0.995265  0.998221  0.993785
real potato   0.105330  0.190569  1.000000  0.105330  0.998929
fake potato   0.665899  0.799399  1.000000  0.665899  0.999757
real apple    0.516501  0.681124  0.700988  0.662450  0.997861
fake apple    0.612850  0.759911  0.928118  0.643388  0.998465
real orange   0.438536  0.609655  0.972363  0.444071  0.999251
fake orange   0.686505  0.814066  0.715445  0.944356  0.998765
real grape    0.409119  0.580625  0.511878  0.670832  0.997977
fake grape    0.689007  0.815823  0.748288  0.896877  0.998503
real lemon    0.151559  0.263176  0.329750  0.219034  0.998559
fake lemon    0.806245  0.892681  0.945628  0.845438  0.999570
real avocado  0.703881  0.826159  0.885468  0.774384  0.999697
fake avocado  0.387246  0.558250  0.842905  0.417368  0.999210
real pepper   0.646152  0.784996  0.808948  0.762515  0.998473
fake pepper   0.525984  0.689324  0.936175  0.545548  0.998828
real plant    0.829603  0.906817  0.946622  0.870317  0.998212
fake plant    0.542575  0.703419  0.570900  0.916219  0.999385
real banana   0.104361  0.188980  0.909251  0.105460  0.997966
fake banana   0.383635  0.554488  0.414730  0.836513  0.997528
real onion    0.633061  0.775257  0.923436  0.668130  0.999650
fake onion    0.878839  0.935463  1.000000  0.878839  0.999924
real unknown  0.344268  0.512162  0.350439  0.951336  0.999710
fake unknown  0.078733  0.145933  0.101855  0.257515  0.997461
total         0.527539  0.651520  0.762541  0.655654  0.998585
total(-bg)    0.506359  0.635831  0.751963  0.640083  0.998804
2026-09-22 13:28:09,332 - INFO: Epoch accounting: {'epoch': 101, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11285780, 47961, 61892, 107975, 141075, 62533, 54530, 150119, 254578, 62447, 47426, 25680, 21287, 267911, 133708, 127452, 24405, 85147, 71791, 69339, 65015, 7422, 62799], 'crops_with_class': [202, 30, 26, 29, 43, 19, 21, 35, 41, 29, 21, 11, 7, 62, 35, 23, 30, 26, 29, 32, 26, 9, 25], 'targeted_crops_by_class': [0, 3, 7, 5, 4, 0, 4, 7, 5, 4, 5, 1, 3, 4, 10, 3, 6, 9, 5, 3, 5, 6, 7], 'sampled_scene_counts': [0, 0, 1, 2, 0, 0, 1, 0, 3, 1, 0, 1, 0, 2, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 1, 2, 1, 2, 1, 0, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 1, 3, 1, 1, 1, 1, 2, 1, 0, 2, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 3, 1, 1, 2, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 2, 0, 1, 0, 1, 4, 0, 0, 3, 2, 4, 0, 0, 1, 1, 0, 1, 1, 2, 1, 1, 1, 8, 1, 1, 1, 3, 3, 5, 1, 1, 3, 2, 1, 1, 2, 0, 1, 3, 1, 1, 3, 1, 1, 1, 1, 1, 4, 1, 0, 1, 1, 0, 2, 0, 3, 2, 0, 1, 0, 1], 'learning_rate': 9.047472259445046e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0013349367131877893, 'train_segmentation_loss': 0.5237891542734486, 'val_foreground_miou_all22': 0.50635863158517, 'val_psnr_ref1': 35.25294219970703, 'elapsed_seconds': 453.06403708457947, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 102/500 | Batch 10/202 | Rec 0.001235 | Seg 0.551678 | Elapsed 0.3m | ETA 5.1m
Epoch 102/500 | Batch 20/202 | Rec 0.001345 | Seg 0.564867 | Elapsed 0.6m | ETA 5.0m
Epoch 102/500 | Batch 30/202 | Rec 0.001298 | Seg 0.531825 | Elapsed 0.8m | ETA 4.8m
Epoch 102/500 | Batch 40/202 | Rec 0.001228 | Seg 0.502288 | Elapsed 1.1m | ETA 4.3m
Epoch 102/500 | Batch 50/202 | Rec 0.001273 | Seg 0.545591 | Elapsed 1.3m | ETA 3.8m
Epoch 102/500 | Batch 60/202 | Rec 0.001311 | Seg 0.564979 | Elapsed 1.5m | ETA 3.6m
Epoch 102/500 | Batch 70/202 | Rec 0.001265 | Seg 0.544184 | Elapsed 1.7m | ETA 3.3m
Epoch 102/500 | Batch 80/202 | Rec 0.001231 | Seg 0.532543 | Elapsed 2.0m | ETA 3.0m
Epoch 102/500 | Batch 90/202 | Rec 0.001263 | Seg 0.522218 | Elapsed 2.2m | ETA 2.7m
Epoch 102/500 | Batch 100/202 | Rec 0.001244 | Seg 0.512182 | Elapsed 2.4m | ETA 2.5m
Epoch 102/500 | Batch 110/202 | Rec 0.001221 | Seg 0.502601 | Elapsed 2.7m | ETA 2.2m
Epoch 102/500 | Batch 120/202 | Rec 0.001215 | Seg 0.493515 | Elapsed 2.9m | ETA 2.0m
Epoch 102/500 | Batch 130/202 | Rec 0.001214 | Seg 0.494153 | Elapsed 3.2m | ETA 1.8m
Epoch 102/500 | Batch 140/202 | Rec 0.001208 | Seg 0.495843 | Elapsed 3.4m | ETA 1.5m
Epoch 102/500 | Batch 150/202 | Rec 0.001217 | Seg 0.493408 | Elapsed 3.7m | ETA 1.3m
Epoch 102/500 | Batch 160/202 | Rec 0.001215 | Seg 0.491909 | Elapsed 3.9m | ETA 1.0m
Epoch 102/500 | Batch 170/202 | Rec 0.001230 | Seg 0.501919 | Elapsed 4.1m | ETA 0.8m
Epoch 102/500 | Batch 180/202 | Rec 0.001226 | Seg 0.498675 | Elapsed 4.4m | ETA 0.5m
Epoch 102/500 | Batch 190/202 | Rec 0.001214 | Seg 0.494825 | Elapsed 4.6m | ETA 0.3m
Epoch 102/500 | Batch 200/202 | Rec 0.001214 | Seg 0.495298 | Elapsed 4.8m | ETA 0.0m
Epoch 102/500 | Batch 202/202 | Rec 0.001223 | Seg 0.494650 | Elapsed 4.9m | ETA 0.0m

2026-09-22 13:33:02,382 - INFO: Rec loss: 0.0012234958330466698
2026-09-22 13:33:02,382 - INFO: Seg loss: 0.4946498637004654
2026-09-22 13:33:02,382 - INFO: λ_rec: 1
2026-09-22 13:33:02,382 - INFO: λ_seg: 0.0001
2026-09-22 13:34:25,845 - INFO: -------------------Epoch: 102------------------------
2026-09-22 13:34:25,851 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.979935  0.966522  0.000266
2026-09-22 13:34:25,859 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993385  0.996631  0.995001  0.998368  0.993671
real potato   0.854716  0.921618  0.976731  0.872481  0.999823
fake potato   0.955855  0.977379  0.989063  0.966066  0.999967
real apple    0.354713  0.523632  0.952954  0.361035  0.997734
fake apple    0.549067  0.708852  0.845521  0.610289  0.998108
real orange   0.397869  0.569210  1.000000  0.397869  0.999207
fake orange   0.724219  0.840005  0.753384  0.949259  0.998965
real grape    0.200418  0.333867  0.468338  0.259446  0.997839
fake grape    0.730996  0.844546  0.819696  0.871056  0.998814
real lemon    0.128995  0.228468  0.336704  0.172942  0.998628
fake lemon    0.789013  0.882015  0.922181  0.845294  0.999522
real avocado  0.595562  0.746476  0.977665  0.603777  0.999619
fake avocado  0.362721  0.532309  0.997547  0.363045  0.999237
real pepper   0.722773  0.839031  0.826946  0.851577  0.998805
fake pepper   0.723644  0.839618  0.772749  0.919275  0.999163
real plant    0.781607  0.877368  0.852057  0.904335  0.997473
fake plant    0.531764  0.694268  0.573590  0.879409  0.999384
real banana   0.104074  0.188507  0.851145  0.106003  0.997950
fake banana   0.401768  0.573184  0.449224  0.791805  0.997831
real onion    0.801064  0.889496  0.843788  0.940551  0.999789
fake onion    0.922038  0.959388  0.978622  0.940992  0.999950
real unknown  0.407496  0.578995  0.411765  0.975191  0.999773
fake unknown  0.041512  0.079675  0.054855  0.145781  0.997164
total         0.568490  0.679328  0.767371  0.683732  0.998627
total(-bg)    0.549177  0.664905  0.757024  0.669431  0.998852
2026-09-22 13:34:26,839 - INFO: Epoch accounting: {'epoch': 102, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11392418, 31890, 42677, 125195, 172632, 102840, 72738, 136268, 193421, 67753, 52704, 54845, 41686, 205748, 99178, 124389, 24269, 51713, 68635, 65034, 67260, 7539, 37440], 'crops_with_class': [202, 21, 20, 38, 46, 31, 27, 30, 38, 29, 22, 16, 13, 51, 26, 18, 20, 17, 23, 25, 30, 11, 15], 'targeted_crops_by_class': [0, 4, 4, 3, 6, 8, 6, 10, 4, 6, 3, 5, 4, 6, 6, 5, 0, 5, 1, 7, 3, 6, 4], 'sampled_scene_counts': [0, 1, 0, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 1, 2, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 3, 2, 0, 2, 0, 0, 2, 1, 0, 0, 2, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 3, 0, 0, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 1, 1, 1, 0, 2, 0, 0, 1, 3, 0, 1, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 2, 3, 1, 0, 0, 0, 2, 2, 1, 4, 1, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 3, 5, 2, 0, 0, 2, 0, 3, 0, 1, 2, 2, 2, 2, 1, 1, 1, 0, 6, 0, 3, 2, 0, 1, 2, 1, 0, 0, 1, 1, 0, 2, 0, 1, 0, 0, 1, 1, 0, 1, 1, 5, 0, 0, 2, 2, 0, 1, 0, 0, 1, 2, 4, 2, 3, 4, 1], 'learning_rate': 9.028973079984215e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0012234958330466698, 'train_segmentation_loss': 0.4946498637004654, 'val_foreground_miou_all22': 0.5491765642760209, 'val_psnr_ref1': 35.97993469238281, 'elapsed_seconds': 377.4956703186035, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 103/500 | Batch 10/202 | Rec 0.001620 | Seg 0.614047 | Elapsed 0.2m | ETA 4.5m
Epoch 103/500 | Batch 20/202 | Rec 0.001481 | Seg 0.555654 | Elapsed 0.5m | ETA 4.2m
Epoch 103/500 | Batch 30/202 | Rec 0.001413 | Seg 0.560413 | Elapsed 0.7m | ETA 3.9m
Epoch 103/500 | Batch 40/202 | Rec 0.001386 | Seg 0.546645 | Elapsed 0.9m | ETA 3.7m
Epoch 103/500 | Batch 50/202 | Rec 0.001346 | Seg 0.547240 | Elapsed 1.1m | ETA 3.4m
Epoch 103/500 | Batch 60/202 | Rec 0.001322 | Seg 0.545222 | Elapsed 1.3m | ETA 3.2m
Epoch 103/500 | Batch 70/202 | Rec 0.001334 | Seg 0.530235 | Elapsed 1.6m | ETA 3.0m
Epoch 103/500 | Batch 80/202 | Rec 0.001363 | Seg 0.530658 | Elapsed 1.8m | ETA 2.8m
Epoch 103/500 | Batch 90/202 | Rec 0.001364 | Seg 0.525526 | Elapsed 2.0m | ETA 2.5m
Epoch 103/500 | Batch 100/202 | Rec 0.001366 | Seg 0.521631 | Elapsed 2.2m | ETA 2.3m
Epoch 103/500 | Batch 110/202 | Rec 0.001336 | Seg 0.518741 | Elapsed 2.5m | ETA 2.1m
Epoch 103/500 | Batch 120/202 | Rec 0.001320 | Seg 0.518171 | Elapsed 2.7m | ETA 1.8m
Epoch 103/500 | Batch 130/202 | Rec 0.001305 | Seg 0.512773 | Elapsed 2.9m | ETA 1.6m
Epoch 103/500 | Batch 140/202 | Rec 0.001332 | Seg 0.521764 | Elapsed 3.2m | ETA 1.4m
Epoch 103/500 | Batch 150/202 | Rec 0.001320 | Seg 0.522430 | Elapsed 3.4m | ETA 1.2m
Epoch 103/500 | Batch 160/202 | Rec 0.001326 | Seg 0.528796 | Elapsed 3.6m | ETA 0.9m
Epoch 103/500 | Batch 170/202 | Rec 0.001325 | Seg 0.525655 | Elapsed 3.8m | ETA 0.7m
Epoch 103/500 | Batch 180/202 | Rec 0.001322 | Seg 0.524267 | Elapsed 4.0m | ETA 0.5m
Epoch 103/500 | Batch 190/202 | Rec 0.001328 | Seg 0.526086 | Elapsed 4.2m | ETA 0.3m
Epoch 103/500 | Batch 200/202 | Rec 0.001328 | Seg 0.527904 | Elapsed 4.5m | ETA 0.0m
Epoch 103/500 | Batch 202/202 | Rec 0.001325 | Seg 0.526049 | Elapsed 4.5m | ETA 0.0m

2026-09-22 13:38:58,099 - INFO: Rec loss: 0.0013246516945499853
2026-09-22 13:38:58,099 - INFO: Seg loss: 0.5260487513450702
2026-09-22 13:38:58,099 - INFO: λ_rec: 1
2026-09-22 13:38:58,099 - INFO: λ_seg: 0.0001
2026-09-22 13:40:21,600 - INFO: -------------------Epoch: 103------------------------
2026-09-22 13:40:21,604 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.039629  0.966057  0.000259
2026-09-22 13:40:21,612 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993622  0.996751  0.994603  0.999008  0.993895
real potato   0.648655  0.786842  0.991854  0.652130  0.999577
fake potato   0.864358  0.927195  0.908871  0.946376  0.999892
real apple    0.411637  0.583159  0.793860  0.460902  0.997727
fake apple    0.518100  0.682518  0.972565  0.525784  0.998154
real orange   0.436313  0.607504  1.000000  0.436313  0.999257
fake orange   0.664335  0.798270  0.684891  0.956774  0.998616
real grape    0.431456  0.602772  0.641720  0.568370  0.998436
fake grape    0.766522  0.867782  0.924012  0.818092  0.999078
real lemon    0.015229  0.029984  0.154031  0.016619  0.998737
fake lemon    0.712956  0.832379  0.990252  0.717995  0.999388
real avocado  0.391233  0.562386  0.999580  0.391297  0.999434
fake avocado  0.066565  0.124809  1.000000  0.066565  0.998883
real pepper   0.623844  0.768305  0.760029  0.776865  0.998287
fake pepper   0.680108  0.809551  0.966679  0.696434  0.999219
real plant    0.818762  0.900301  0.898525  0.902185  0.998002
fake plant    0.538185  0.699720  0.554869  0.947086  0.999353
real banana   0.139582  0.244946  0.899612  0.141790  0.998036
fake banana   0.345708  0.513750  0.379760  0.794044  0.997235
real onion    0.811518  0.895904  0.876555  0.916230  0.999808
fake onion    0.917802  0.957089  0.969486  0.945103  0.999947
real unknown  0.261812  0.414943  0.264923  0.957061  0.999568
fake unknown  0.085556  0.157593  0.099603  0.377581  0.996600
total         0.527994  0.641933  0.770708  0.652635  0.998571
total(-bg)    0.506829  0.625805  0.760531  0.636891  0.998783
2026-09-22 13:40:22,489 - INFO: Epoch accounting: {'epoch': 103, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11311140, 59085, 62187, 112253, 104277, 81081, 77342, 130984, 149323, 68694, 72369, 33230, 34677, 224842, 144462, 159284, 31459, 115411, 82372, 75729, 57002, 10852, 40217], 'crops_with_class': [202, 31, 27, 27, 27, 29, 27, 26, 34, 34, 26, 10, 12, 56, 42, 20, 25, 36, 32, 35, 27, 13, 16], 'targeted_crops_by_class': [0, 8, 7, 4, 1, 6, 5, 6, 4, 6, 8, 2, 4, 3, 9, 1, 8, 8, 2, 3, 4, 5, 0], 'sampled_scene_counts': [1, 0, 5, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 3, 0, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 0, 1, 2, 0, 3, 2, 0, 1, 1, 1, 1, 2, 0, 2, 1, 0, 0, 0, 2, 2, 4, 2, 0, 1, 0, 1, 4, 1, 0, 3, 1, 2, 2, 2, 2, 1, 1, 1, 0, 1, 2, 2, 3, 4, 0, 0, 1, 4, 2, 2, 1, 2, 2, 1, 1, 1, 3, 1, 0, 1, 2, 1, 1, 1, 0, 3, 1, 1, 2, 1, 1, 1, 4, 2, 2, 1], 'learning_rate': 9.010315337043492e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0013246516945499853, 'train_segmentation_loss': 0.5260487513450702, 'val_foreground_miou_all22': 0.5068288798088318, 'val_psnr_ref1': 36.03962860107422, 'elapsed_seconds': 355.6400029659271, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 104/500 | Batch 10/202 | Rec 0.001376 | Seg 0.583516 | Elapsed 0.2m | ETA 4.4m
Epoch 104/500 | Batch 20/202 | Rec 0.001194 | Seg 0.525501 | Elapsed 0.4m | ETA 4.1m
Epoch 104/500 | Batch 30/202 | Rec 0.001239 | Seg 0.544603 | Elapsed 0.7m | ETA 3.8m
Epoch 104/500 | Batch 40/202 | Rec 0.001294 | Seg 0.581161 | Elapsed 0.9m | ETA 3.5m
Epoch 104/500 | Batch 50/202 | Rec 0.001376 | Seg 0.575242 | Elapsed 1.1m | ETA 3.3m
Epoch 104/500 | Batch 60/202 | Rec 0.001329 | Seg 0.573417 | Elapsed 1.3m | ETA 3.1m
Epoch 104/500 | Batch 70/202 | Rec 0.001327 | Seg 0.542520 | Elapsed 1.5m | ETA 2.9m
Epoch 104/500 | Batch 80/202 | Rec 0.001316 | Seg 0.539643 | Elapsed 1.8m | ETA 2.7m
Epoch 104/500 | Batch 90/202 | Rec 0.001332 | Seg 0.540821 | Elapsed 2.0m | ETA 2.5m
Epoch 104/500 | Batch 100/202 | Rec 0.001332 | Seg 0.536372 | Elapsed 2.2m | ETA 2.2m
Epoch 104/500 | Batch 110/202 | Rec 0.001348 | Seg 0.540496 | Elapsed 2.4m | ETA 2.0m
Epoch 104/500 | Batch 120/202 | Rec 0.001339 | Seg 0.539117 | Elapsed 2.6m | ETA 1.8m
Epoch 104/500 | Batch 130/202 | Rec 0.001308 | Seg 0.527552 | Elapsed 2.9m | ETA 1.6m
Epoch 104/500 | Batch 140/202 | Rec 0.001296 | Seg 0.521651 | Elapsed 3.1m | ETA 1.4m
Epoch 104/500 | Batch 150/202 | Rec 0.001285 | Seg 0.518307 | Elapsed 3.3m | ETA 1.1m
Epoch 104/500 | Batch 160/202 | Rec 0.001288 | Seg 0.524395 | Elapsed 3.5m | ETA 0.9m
Epoch 104/500 | Batch 170/202 | Rec 0.001277 | Seg 0.522966 | Elapsed 3.7m | ETA 0.7m
Epoch 104/500 | Batch 180/202 | Rec 0.001275 | Seg 0.521896 | Elapsed 3.9m | ETA 0.5m
Epoch 104/500 | Batch 190/202 | Rec 0.001267 | Seg 0.518611 | Elapsed 4.2m | ETA 0.3m
Epoch 104/500 | Batch 200/202 | Rec 0.001262 | Seg 0.516088 | Elapsed 4.4m | ETA 0.0m
Epoch 104/500 | Batch 202/202 | Rec 0.001268 | Seg 0.514944 | Elapsed 4.4m | ETA 0.0m

2026-09-22 13:44:47,286 - INFO: Rec loss: 0.001267718602032954
2026-09-22 13:44:47,286 - INFO: Seg loss: 0.5149435246049767
2026-09-22 13:44:47,286 - INFO: λ_rec: 1
2026-09-22 13:44:47,286 - INFO: λ_seg: 0.0001
2026-09-22 13:46:10,414 - INFO: -------------------Epoch: 104------------------------
2026-09-22 13:46:10,419 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.432825  0.964855  0.000298
2026-09-22 13:46:10,426 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994387  0.997136  0.996100  0.998274  0.994636
real potato   0.283584  0.441828  0.998205  0.283729  0.999142
fake potato   0.633012  0.775222  1.000000  0.633012  0.999733
real apple    0.572907  0.728419  0.690219  0.771207  0.998017
fake apple    0.732739  0.845708  0.819578  0.873666  0.998797
real orange   0.421955  0.593444  1.000000  0.421955  0.999238
fake orange   0.664492  0.798384  0.682943  0.960932  0.998611
real grape    0.174455  0.297049  0.704017  0.188263  0.998140
fake grape    0.758429  0.862571  0.797055  0.939941  0.998893
real lemon    0.064163  0.120553  0.252588  0.079200  0.998642
fake lemon    0.815804  0.898510  0.982288  0.827984  0.999604
real avocado  0.760576  0.863958  0.887888  0.841379  0.999754
fake avocado  0.644093  0.783474  0.850298  0.726473  0.999520
real pepper   0.688555  0.815505  0.810997  0.820165  0.998643
fake pepper   0.508366  0.674017  0.987885  0.511555  0.998821
real plant    0.786648  0.880536  0.853541  0.909400  0.997533
fake plant    0.377028  0.547547  0.496491  0.610429  0.999197
real banana   0.033356  0.064552  0.953488  0.033410  0.997824
fake banana   0.315999  0.480200  0.342479  0.803417  0.996801
real onion    0.641832  0.781799  0.819090  0.747847  0.999623
fake onion    0.812324  0.896395  0.963056  0.838452  0.999878
real unknown  0.656539  0.792615  0.680822  0.948473  0.999921
fake unknown  0.160231  0.276156  0.242028  0.321623  0.998580
total         0.543542  0.661547  0.774394  0.656121  0.998676
total(-bg)    0.523049  0.646293  0.764316  0.640569  0.998860
2026-09-22 13:46:11,063 - INFO: Epoch accounting: {'epoch': 104, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11308675, 49660, 66575, 149022, 180795, 79877, 65807, 121948, 199253, 63426, 54392, 37440, 37425, 203032, 88943, 132321, 24218, 87769, 84718, 92215, 60060, 14187, 36514], 'crops_with_class': [202, 32, 32, 41, 45, 30, 26, 23, 36, 31, 22, 12, 13, 51, 28, 18, 24, 24, 35, 40, 26, 14, 18], 'targeted_crops_by_class': [0, 4, 6, 5, 7, 6, 4, 3, 4, 5, 2, 1, 5, 4, 5, 3, 8, 5, 8, 6, 4, 7, 3], 'sampled_scene_counts': [2, 1, 2, 0, 1, 2, 1, 1, 2, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 2, 2, 1, 1, 0, 0, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1, 1, 0, 3, 1, 1, 2, 1, 0, 1, 0, 1, 3, 1, 2, 0, 3, 2, 1, 1, 0, 2, 2, 0, 0, 0, 2, 1, 2, 1, 2, 3, 3, 2, 1, 0, 3, 0, 1, 1, 2, 1, 1, 2, 1, 2, 2, 5, 1, 0, 1, 0, 3, 2, 2, 1, 1, 0, 2, 0, 1, 2, 1, 2, 0, 2, 2, 1, 1, 1, 3, 3, 1, 4, 1, 2, 1, 1, 1, 2, 0, 0, 0, 1, 2, 3, 0, 3], 'learning_rate': 8.991499767198617e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.001267718602032954, 'train_segmentation_loss': 0.5149435246049767, 'val_foreground_miou_all22': 0.5230494156061396, 'val_psnr_ref1': 35.43282470703125, 'elapsed_seconds': 348.56573462486267, 'peak_cuda_allocated_gib': 7.509555816650391}

Epoch 105/500 | Batch 10/202 | Rec 0.001182 | Seg 0.531165 | Elapsed 0.2m | ETA 4.2m
Epoch 105/500 | Batch 20/202 | Rec 0.001464 | Seg 0.532797 | Elapsed 0.4m | ETA 3.9m
Epoch 105/500 | Batch 30/202 | Rec 0.001312 | Seg 0.457351 | Elapsed 0.6m | ETA 3.7m
Epoch 105/500 | Batch 40/202 | Rec 0.001356 | Seg 0.471936 | Elapsed 0.9m | ETA 3.5m
Epoch 105/500 | Batch 50/202 | Rec 0.001313 | Seg 0.473633 | Elapsed 1.1m | ETA 3.3m
Epoch 105/500 | Batch 60/202 | Rec 0.001337 | Seg 0.503464 | Elapsed 1.3m | ETA 3.0m
Epoch 105/500 | Batch 70/202 | Rec 0.001297 | Seg 0.497318 | Elapsed 1.5m | ETA 2.8m
Epoch 105/500 | Batch 80/202 | Rec 0.001296 | Seg 0.512418 | Elapsed 1.7m | ETA 2.6m
Epoch 105/500 | Batch 90/202 | Rec 0.001279 | Seg 0.518186 | Elapsed 1.9m | ETA 2.4m
Epoch 105/500 | Batch 100/202 | Rec 0.001274 | Seg 0.513233 | Elapsed 2.1m | ETA 2.2m
Epoch 105/500 | Batch 110/202 | Rec 0.001277 | Seg 0.510613 | Elapsed 2.4m | ETA 2.0m
Epoch 105/500 | Batch 120/202 | Rec 0.001319 | Seg 0.517038 | Elapsed 2.6m | ETA 1.8m
Epoch 105/500 | Batch 130/202 | Rec 0.001341 | Seg 0.524672 | Elapsed 2.8m | ETA 1.5m
Epoch 105/500 | Batch 140/202 | Rec 0.001330 | Seg 0.516059 | Elapsed 3.0m | ETA 1.3m
Epoch 105/500 | Batch 150/202 | Rec 0.001361 | Seg 0.522087 | Elapsed 3.2m | ETA 1.1m
Epoch 105/500 | Batch 160/202 | Rec 0.001358 | Seg 0.518255 | Elapsed 3.4m | ETA 0.9m
Epoch 105/500 | Batch 170/202 | Rec 0.001346 | Seg 0.516791 | Elapsed 3.7m | ETA 0.7m
Epoch 105/500 | Batch 180/202 | Rec 0.001345 | Seg 0.526692 | Elapsed 3.9m | ETA 0.5m
Epoch 105/500 | Batch 190/202 | Rec 0.001341 | Seg 0.523863 | Elapsed 4.1m | ETA 0.3m
Epoch 105/500 | Batch 200/202 | Rec 0.001336 | Seg 0.522724 | Elapsed 4.3m | ETA 0.0m
Epoch 105/500 | Batch 202/202 | Rec 0.001330 | Seg 0.521078 | Elapsed 4.4m | ETA 0.0m

2026-09-22 13:50:32,807 - INFO: Rec loss: 0.0013304470885847003
2026-09-22 13:50:32,807 - INFO: Seg loss: 0.521077938193437
2026-09-22 13:50:32,808 - INFO: λ_rec: 1
2026-09-22 13:50:32,808 - INFO: λ_seg: 0.0001
2026-09-22 13:51:56,653 - INFO: -------------------Epoch: 105------------------------
2026-09-22 13:51:56,658 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.189148  0.964083  0.000312
2026-09-22 13:51:56,666 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994549  0.997217  0.996489  0.998046  0.994792
real potato   0.789513  0.882328  0.985525  0.798776  0.999745
fake potato   0.951285  0.974984  0.980716  0.969418  0.999964
real apple    0.706669  0.828077  0.903450  0.764396  0.998905
fake apple    0.599778  0.749778  0.874475  0.656280  0.998347
real orange   0.508169  0.673843  0.961778  0.518643  0.999339
fake orange   0.779962  0.876331  0.797483  0.972604  0.999214
real grape    0.613929  0.760738  0.851684  0.687422  0.999097
fake grape    0.827072  0.905303  0.888646  0.922699  0.999286
real lemon    0.042441  0.081392  0.185083  0.052194  0.998616
fake lemon    0.716982  0.835117  0.998595  0.717706  0.999401
real avocado  0.601626  0.751222  0.984043  0.607553  0.999626
fake avocado  0.126714  0.224906  0.905575  0.128411  0.998941
real pepper   0.709443  0.829979  0.828013  0.832054  0.998754
fake pepper   0.663647  0.797772  0.784684  0.811408  0.999020
real plant    0.833892  0.909373  0.873518  0.948407  0.998110
fake plant    0.547726  0.707734  0.568554  0.937308  0.999384
real banana   0.219163  0.359498  0.888146  0.225384  0.998196
fake banana   0.372683  0.542956  0.401029  0.840577  0.997397
real onion    0.754107  0.859769  0.788177  0.945786  0.999721
fake onion    0.807188  0.893259  0.818566  0.983071  0.999852
real unknown  0.334433  0.501197  0.338225  0.967557  0.999692
fake unknown  0.063646  0.119630  0.089366  0.181094  0.997755
total         0.589766  0.698365  0.769210  0.715948  0.998833
total(-bg)    0.571367  0.684781  0.758879  0.703125  0.999016
2026-09-22 13:51:57,472 - INFO: Epoch accounting: {'epoch': 105, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11280248, 56030, 69164, 99391, 130553, 105890, 70251, 149235, 145283, 68302, 73707, 55244, 31553, 241468, 141618, 142802, 27076, 96719, 61308, 90040, 58960, 8693, 34737], 'crops_with_class': [202, 33, 32, 24, 32, 33, 26, 23, 33, 26, 31, 18, 12, 57, 37, 18, 19, 28, 30, 42, 27, 11, 17], 'targeted_crops_by_class': [0, 6, 4, 3, 6, 4, 4, 7, 2, 3, 4, 8, 2, 7, 6, 3, 4, 4, 3, 9, 5, 3, 3], 'sampled_scene_counts': [1, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 3, 1, 0, 0, 0, 1, 1, 2, 0, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 3, 3, 1, 0, 3, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 2, 0, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 4, 0, 0, 1, 3, 1, 1, 0, 2, 2, 1, 3, 1, 1, 2, 3, 1, 0, 2, 2, 0, 0, 1, 2, 0, 3, 2, 0, 1, 0, 0, 1, 0, 2, 0, 1, 2, 0, 2, 1, 2, 2, 1, 1, 0, 3, 2, 1, 1, 0, 1, 1, 3, 1, 1, 2, 2, 1, 1, 2, 0, 0, 2, 2, 2, 1, 0, 1, 2, 1, 3, 3, 2, 1, 2, 1, 0, 1, 3, 3, 2, 4], 'learning_rate': 8.972527113256072e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0013304470885847003, 'train_segmentation_loss': 0.521077938193437, 'val_foreground_miou_all22': 0.5713668003773757, 'val_psnr_ref1': 35.18914794921875, 'elapsed_seconds': 346.4003071784973, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 106/500 | Batch 10/202 | Rec 0.001225 | Seg 0.498611 | Elapsed 0.2m | ETA 4.0m
Epoch 106/500 | Batch 20/202 | Rec 0.001206 | Seg 0.477416 | Elapsed 0.4m | ETA 3.9m
Epoch 106/500 | Batch 30/202 | Rec 0.001155 | Seg 0.444880 | Elapsed 0.6m | ETA 3.7m
Epoch 106/500 | Batch 40/202 | Rec 0.001146 | Seg 0.473487 | Elapsed 0.9m | ETA 3.5m
Epoch 106/500 | Batch 50/202 | Rec 0.001175 | Seg 0.487268 | Elapsed 1.1m | ETA 3.2m
Epoch 106/500 | Batch 60/202 | Rec 0.001200 | Seg 0.488332 | Elapsed 1.3m | ETA 3.0m
Epoch 106/500 | Batch 70/202 | Rec 0.001208 | Seg 0.479074 | Elapsed 1.5m | ETA 2.8m
Epoch 106/500 | Batch 80/202 | Rec 0.001201 | Seg 0.479654 | Elapsed 1.7m | ETA 2.6m
Epoch 106/500 | Batch 90/202 | Rec 0.001197 | Seg 0.484986 | Elapsed 1.9m | ETA 2.4m
Epoch 106/500 | Batch 100/202 | Rec 0.001212 | Seg 0.492200 | Elapsed 2.2m | ETA 2.2m
Epoch 106/500 | Batch 110/202 | Rec 0.001198 | Seg 0.492252 | Elapsed 2.4m | ETA 2.0m
Epoch 106/500 | Batch 120/202 | Rec 0.001201 | Seg 0.489110 | Elapsed 2.6m | ETA 1.8m
Epoch 106/500 | Batch 130/202 | Rec 0.001220 | Seg 0.508873 | Elapsed 2.8m | ETA 1.5m
Epoch 106/500 | Batch 140/202 | Rec 0.001218 | Seg 0.510557 | Elapsed 3.0m | ETA 1.3m
Epoch 106/500 | Batch 150/202 | Rec 0.001202 | Seg 0.504565 | Elapsed 3.2m | ETA 1.1m
Epoch 106/500 | Batch 160/202 | Rec 0.001197 | Seg 0.505932 | Elapsed 3.4m | ETA 0.9m
Epoch 106/500 | Batch 170/202 | Rec 0.001205 | Seg 0.509912 | Elapsed 3.7m | ETA 0.7m
Epoch 106/500 | Batch 180/202 | Rec 0.001206 | Seg 0.513376 | Elapsed 3.9m | ETA 0.5m
Epoch 106/500 | Batch 190/202 | Rec 0.001231 | Seg 0.524542 | Elapsed 4.1m | ETA 0.3m
Epoch 106/500 | Batch 200/202 | Rec 0.001237 | Seg 0.524502 | Elapsed 4.3m | ETA 0.0m
Epoch 106/500 | Batch 202/202 | Rec 0.001238 | Seg 0.523745 | Elapsed 4.3m | ETA 0.0m

2026-09-22 13:56:17,186 - INFO: Rec loss: 0.001237642449484723
2026-09-22 13:56:17,187 - INFO: Seg loss: 0.5237448147617945
2026-09-22 13:56:17,187 - INFO: λ_rec: 1
2026-09-22 13:56:17,187 - INFO: λ_seg: 0.0001
2026-09-22 13:57:40,449 - INFO: -------------------Epoch: 106------------------------
2026-09-22 13:57:40,453 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.212138  0.962476  0.000325
2026-09-22 13:57:40,461 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994443  0.997164  0.995775  0.998657  0.994687
real potato   0.486794  0.654779  0.981902  0.491201  0.999380
fake potato   0.938962  0.968470  0.970353  0.966695  0.999954
real apple    0.660277  0.795332  0.797095  0.793675  0.998591
fake apple    0.609916  0.757651  0.949476  0.630375  0.998478
real orange   0.312605  0.476274  0.910726  0.322487  0.999066
fake orange   0.645018  0.784160  0.654402  0.978254  0.998459
real grape    0.070804  0.132224  0.585198  0.074545  0.997957
fake grape    0.757806  0.862168  0.817610  0.911975  0.998922
real lemon    0.370249  0.540362  0.551249  0.529992  0.998941
fake lemon    0.775075  0.873238  0.993288  0.779156  0.999522
real avocado  0.870376  0.930647  0.967736  0.896388  0.999876
fake avocado  0.229568  0.373381  0.948491  0.232466  0.999066
real pepper   0.680148  0.809579  0.824257  0.795511  0.998632
fake pepper   0.658768  0.794236  0.871473  0.729659  0.999099
real plant    0.745112  0.853892  0.823188  0.887082  0.996965
fake plant    0.515380  0.680151  0.549292  0.893021  0.999332
real banana   0.180666  0.306011  0.845941  0.186812  0.998096
fake banana   0.440532  0.611578  0.479696  0.843646  0.998029
real onion    0.619657  0.765121  0.816632  0.719811  0.999601
fake onion    0.935399  0.966571  0.992610  0.941959  0.999959
real unknown  0.598113  0.748476  0.636972  0.907443  0.999902
fake unknown  0.165145  0.283433  0.203254  0.468309  0.998005
total         0.576557  0.694126  0.789853  0.694744  0.998718
total(-bg)    0.557562  0.680352  0.780493  0.680930  0.998901
2026-09-22 13:57:41,057 - INFO: Epoch accounting: {'epoch': 106, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11236691, 48967, 57692, 174500, 149971, 86671, 65557, 148071, 186571, 74937, 53127, 38391, 32785, 223229, 90741, 179462, 22298, 93249, 70137, 95096, 55295, 7657, 47177], 'crops_with_class': [202, 32, 24, 44, 38, 28, 22, 31, 38, 34, 22, 13, 13, 55, 26, 21, 21, 28, 28, 39, 27, 9, 21], 'targeted_crops_by_class': [0, 5, 5, 3, 3, 6, 3, 4, 3, 5, 8, 3, 4, 6, 3, 6, 4, 5, 6, 4, 5, 4, 3], 'sampled_scene_counts': [1, 1, 0, 1, 1, 0, 1, 2, 1, 3, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 2, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 2, 1, 1, 3, 1, 2, 1, 1, 1, 2, 2, 0, 3, 1, 1, 2, 1, 0, 4, 0, 2, 1, 2, 0, 1, 2, 3, 3, 1, 2, 3, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 4, 1, 3, 1, 4, 0, 1, 2, 4, 3, 0, 1, 2, 2, 2, 1, 0, 2, 2, 1, 0, 3, 0, 2, 1, 1, 1, 1, 3, 1, 1, 0, 0, 1, 0, 2, 2, 1, 2, 1, 2, 1], 'learning_rate': 8.95339812422375e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001237642449484723, 'train_segmentation_loss': 0.5237448147617945, 'val_foreground_miou_all22': 0.5575622960038031, 'val_psnr_ref1': 35.21213806152344, 'elapsed_seconds': 343.57535767555237, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 107/500 | Batch 10/202 | Rec 0.001480 | Seg 0.611233 | Elapsed 0.2m | ETA 4.1m
Epoch 107/500 | Batch 20/202 | Rec 0.001493 | Seg 0.565459 | Elapsed 0.4m | ETA 3.9m
Epoch 107/500 | Batch 30/202 | Rec 0.001494 | Seg 0.606739 | Elapsed 0.6m | ETA 3.7m
Epoch 107/500 | Batch 40/202 | Rec 0.001363 | Seg 0.566172 | Elapsed 0.9m | ETA 3.5m
Epoch 107/500 | Batch 50/202 | Rec 0.001305 | Seg 0.537087 | Elapsed 1.1m | ETA 3.3m
Epoch 107/500 | Batch 60/202 | Rec 0.001313 | Seg 0.516807 | Elapsed 1.3m | ETA 3.0m
Epoch 107/500 | Batch 70/202 | Rec 0.001297 | Seg 0.504834 | Elapsed 1.5m | ETA 2.8m
Epoch 107/500 | Batch 80/202 | Rec 0.001310 | Seg 0.512213 | Elapsed 1.7m | ETA 2.6m
Epoch 107/500 | Batch 90/202 | Rec 0.001315 | Seg 0.531522 | Elapsed 1.9m | ETA 2.4m
Epoch 107/500 | Batch 100/202 | Rec 0.001296 | Seg 0.525939 | Elapsed 2.1m | ETA 2.2m
Epoch 107/500 | Batch 110/202 | Rec 0.001293 | Seg 0.520875 | Elapsed 2.3m | ETA 1.9m
Epoch 107/500 | Batch 120/202 | Rec 0.001298 | Seg 0.527856 | Elapsed 2.5m | ETA 1.7m
Epoch 107/500 | Batch 130/202 | Rec 0.001298 | Seg 0.532984 | Elapsed 2.7m | ETA 1.5m
Epoch 107/500 | Batch 140/202 | Rec 0.001290 | Seg 0.530735 | Elapsed 3.0m | ETA 1.3m
Epoch 107/500 | Batch 150/202 | Rec 0.001290 | Seg 0.530015 | Elapsed 3.2m | ETA 1.1m
Epoch 107/500 | Batch 160/202 | Rec 0.001284 | Seg 0.522077 | Elapsed 3.4m | ETA 0.9m
Epoch 107/500 | Batch 170/202 | Rec 0.001296 | Seg 0.520951 | Elapsed 3.6m | ETA 0.7m
Epoch 107/500 | Batch 180/202 | Rec 0.001300 | Seg 0.525336 | Elapsed 3.8m | ETA 0.5m
Epoch 107/500 | Batch 190/202 | Rec 0.001305 | Seg 0.527250 | Elapsed 4.0m | ETA 0.3m
Epoch 107/500 | Batch 200/202 | Rec 0.001296 | Seg 0.525087 | Elapsed 4.3m | ETA 0.0m
Epoch 107/500 | Batch 202/202 | Rec 0.001294 | Seg 0.524203 | Elapsed 4.3m | ETA 0.0m

2026-09-22 14:02:00,002 - INFO: Rec loss: 0.001293538063637783
2026-09-22 14:02:00,002 - INFO: Seg loss: 0.5242027146833959
2026-09-22 14:02:00,002 - INFO: λ_rec: 1
2026-09-22 14:02:00,002 - INFO: λ_seg: 0.0001
2026-09-22 14:03:23,357 - INFO: -------------------Epoch: 107------------------------
2026-09-22 14:03:23,362 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.462185  0.965849  0.000301
2026-09-22 14:03:23,369 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994160  0.997021  0.995866  0.998279  0.994417
real potato   0.510183  0.675613  0.996519  0.511094  0.999413
fake potato   0.897280  0.945810  0.998603  0.898408  0.999925
real apple    0.558931  0.717020  0.783982  0.660681  0.998201
fake apple    0.714585  0.833488  0.926457  0.757557  0.998858
real orange   0.379111  0.549750  1.000000  0.379111  0.999182
fake orange   0.733703  0.846351  0.757688  0.958640  0.999004
real grape    0.385022  0.555930  0.633147  0.495578  0.998347
fake grape    0.736765  0.848384  0.822509  0.876047  0.998842
real lemon    0.200116  0.333447  0.439304  0.268761  0.998737
fake lemon    0.808125  0.893832  0.985656  0.817743  0.999589
real avocado  0.884609  0.938722  0.966441  0.912644  0.999889
fake avocado  0.533427  0.695686  0.993843  0.535195  0.999440
real pepper   0.677365  0.807604  0.822626  0.793217  0.998618
fake pepper   0.786924  0.880709  0.970851  0.805966  0.999480
real plant    0.804207  0.891430  0.847102  0.940765  0.997709
fake plant    0.594306  0.745488  0.622814  0.928489  0.999496
real banana   0.063324  0.119093  0.816221  0.064240  0.997865
fake banana   0.409337  0.580847  0.451411  0.814532  0.997838
real onion    0.770984  0.870634  0.840698  0.902888  0.999758
fake onion    0.923893  0.960391  0.972953  0.948247  0.999951
real unknown  0.388974  0.560047  0.393798  0.969466  0.999756
fake unknown  0.199762  0.332956  0.262564  0.455089  0.998464
total         0.606743  0.720881  0.795698  0.725767  0.998816
total(-bg)    0.589133  0.708329  0.786599  0.713380  0.999016
2026-09-22 14:03:24,152 - INFO: Epoch accounting: {'epoch': 107, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11229255, 46846, 53578, 122397, 149442, 71078, 63849, 147680, 148330, 78352, 62908, 46451, 51842, 261993, 131126, 172079, 22790, 89664, 91933, 90220, 47365, 12602, 46492], 'crops_with_class': [202, 28, 27, 30, 38, 26, 22, 28, 32, 33, 25, 18, 18, 63, 32, 25, 22, 25, 34, 34, 25, 13, 21], 'targeted_crops_by_class': [0, 6, 3, 6, 6, 1, 9, 12, 2, 3, 6, 7, 8, 6, 2, 5, 1, 4, 6, 5, 5, 5, 2], 'sampled_scene_counts': [1, 0, 2, 1, 1, 1, 1, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 2, 3, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1, 2, 1, 2, 2, 1, 3, 2, 1, 2, 1, 2, 1, 1, 2, 0, 1, 0, 0, 2, 2, 2, 2, 1, 3, 2, 0, 2, 3, 1, 1, 1, 4, 3, 2, 1, 3, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 0, 2, 1, 3, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1, 0, 4, 0, 3, 2, 0, 2, 1, 0, 1, 1, 2, 1, 2], 'learning_rate': 8.934113555281382e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001293538063637783, 'train_segmentation_loss': 0.5242027146833959, 'val_foreground_miou_all22': 0.5891333535565889, 'val_psnr_ref1': 35.46218475341797, 'elapsed_seconds': 343.084778547287, 'peak_cuda_allocated_gib': 7.511142730712891}

Epoch 108/500 | Batch 10/202 | Rec 0.001225 | Seg 0.480870 | Elapsed 0.2m | ETA 4.1m
Epoch 108/500 | Batch 20/202 | Rec 0.001374 | Seg 0.547488 | Elapsed 0.4m | ETA 3.9m
Epoch 108/500 | Batch 30/202 | Rec 0.001323 | Seg 0.558102 | Elapsed 0.6m | ETA 3.7m
Epoch 108/500 | Batch 40/202 | Rec 0.001393 | Seg 0.544931 | Elapsed 0.8m | ETA 3.4m
Epoch 108/500 | Batch 50/202 | Rec 0.001358 | Seg 0.533091 | Elapsed 1.1m | ETA 3.2m
Epoch 108/500 | Batch 60/202 | Rec 0.001331 | Seg 0.524602 | Elapsed 1.3m | ETA 3.0m
Epoch 108/500 | Batch 70/202 | Rec 0.001334 | Seg 0.536430 | Elapsed 1.5m | ETA 2.8m
Epoch 108/500 | Batch 80/202 | Rec 0.001298 | Seg 0.536380 | Elapsed 1.7m | ETA 2.6m
Epoch 108/500 | Batch 90/202 | Rec 0.001291 | Seg 0.539201 | Elapsed 1.9m | ETA 2.4m
Epoch 108/500 | Batch 100/202 | Rec 0.001291 | Seg 0.540593 | Elapsed 2.1m | ETA 2.2m
Epoch 108/500 | Batch 110/202 | Rec 0.001271 | Seg 0.529785 | Elapsed 2.3m | ETA 1.9m
Epoch 108/500 | Batch 120/202 | Rec 0.001256 | Seg 0.516045 | Elapsed 2.5m | ETA 1.7m
Epoch 108/500 | Batch 130/202 | Rec 0.001261 | Seg 0.522158 | Elapsed 2.8m | ETA 1.5m
Epoch 108/500 | Batch 140/202 | Rec 0.001240 | Seg 0.511900 | Elapsed 3.0m | ETA 1.3m
Epoch 108/500 | Batch 150/202 | Rec 0.001229 | Seg 0.507149 | Elapsed 3.2m | ETA 1.1m
Epoch 108/500 | Batch 160/202 | Rec 0.001223 | Seg 0.505871 | Elapsed 3.4m | ETA 0.9m
Epoch 108/500 | Batch 170/202 | Rec 0.001218 | Seg 0.501678 | Elapsed 3.6m | ETA 0.7m
Epoch 108/500 | Batch 180/202 | Rec 0.001215 | Seg 0.501611 | Elapsed 3.8m | ETA 0.5m
Epoch 108/500 | Batch 190/202 | Rec 0.001205 | Seg 0.498772 | Elapsed 4.0m | ETA 0.3m
Epoch 108/500 | Batch 200/202 | Rec 0.001210 | Seg 0.500860 | Elapsed 4.2m | ETA 0.0m
Epoch 108/500 | Batch 202/202 | Rec 0.001211 | Seg 0.502294 | Elapsed 4.3m | ETA 0.0m

2026-09-22 14:07:40,846 - INFO: Rec loss: 0.001211182776801657
2026-09-22 14:07:40,847 - INFO: Seg loss: 0.5022943063390137
2026-09-22 14:07:40,847 - INFO: λ_rec: 1
2026-09-22 14:07:40,847 - INFO: λ_seg: 0.0001
2026-09-22 14:09:04,015 - INFO: -------------------Epoch: 108------------------------
2026-09-22 14:09:04,019 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  35.991049  0.966797  0.00026
2026-09-22 14:09:04,028 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994498  0.997192  0.995367  0.999124  0.994738
real potato   0.476609  0.645502  0.999198  0.476792  0.999373
fake potato   0.937693  0.967795  0.984192  0.952032  0.999954
real apple    0.683387  0.811869  0.832481  0.792349  0.998734
fake apple    0.601759  0.751324  0.906764  0.641448  0.998397
real orange   0.340048  0.507477  0.951895  0.345994  0.999115
fake orange   0.583595  0.737004  0.589988  0.981772  0.997995
real grape    0.424551  0.596003  0.843704  0.460791  0.998696
fake grape    0.743195  0.852632  0.831348  0.875139  0.998881
real lemon    0.316071  0.480276  0.434810  0.536484  0.998636
fake lemon    0.812020  0.896210  0.942191  0.854598  0.999581
real avocado  0.868132  0.929362  0.937960  0.921018  0.999870
fake avocado  0.543649  0.704323  0.985777  0.547947  0.999450
real pepper   0.702475  0.825190  0.837377  0.813449  0.998740
fake pepper   0.575238  0.730302  0.891266  0.618654  0.998911
real plant    0.805602  0.892286  0.888397  0.896311  0.997837
fake plant    0.711932  0.831680  0.783330  0.886503  0.999715
real banana   0.062910  0.118355  0.548568  0.066345  0.997779
fake banana   0.485762  0.653841  0.555221  0.795206  0.998451
real onion    0.728873  0.843127  0.847348  0.839047  0.999718
fake onion    0.837574  0.911559  0.871772  0.955260  0.999883
real unknown  0.818926  0.900400  0.946372  0.858779  0.999970
fake unknown  0.117806  0.210732  0.185145  0.244658  0.998456
total         0.616187  0.730193  0.808281  0.711291  0.998821
total(-bg)    0.598991  0.718057  0.799778  0.698208  0.999006
2026-09-22 14:09:04,815 - INFO: Epoch accounting: {'epoch': 108, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11261178, 32738, 50084, 149758, 146842, 93425, 97367, 156639, 258789, 105743, 78031, 42619, 34820, 209650, 68439, 166746, 33828, 57089, 65797, 51198, 43349, 7418, 26725], 'crops_with_class': [202, 23, 24, 39, 37, 29, 35, 35, 44, 41, 34, 15, 11, 47, 21, 24, 26, 19, 26, 27, 22, 8, 16], 'targeted_crops_by_class': [0, 3, 5, 5, 3, 10, 6, 4, 9, 3, 10, 7, 8, 3, 1, 6, 11, 1, 5, 5, 4, 4, 2], 'sampled_scene_counts': [1, 1, 0, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 2, 0, 1, 1, 2, 0, 3, 0, 1, 0, 2, 0, 1, 0, 3, 1, 1, 3, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 1, 1, 0, 1, 0, 0, 1, 0, 2, 1, 2, 2, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 2, 3, 1, 0, 0, 0, 6, 1, 2, 1, 2, 3, 0, 5, 3, 1, 3, 0, 2, 1, 1, 2, 2, 2, 2, 4, 1, 1, 3, 2, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 2, 1, 1, 1, 0, 2, 0, 1, 1, 0, 0, 2, 2, 0, 1, 2, 1, 0, 1, 1, 1, 3, 1, 2, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 0, 2, 3, 2, 2], 'learning_rate': 8.914674167750728e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001211182776801657, 'train_segmentation_loss': 0.5022943063390137, 'val_foreground_miou_all22': 0.5989913541239169, 'val_psnr_ref1': 35.99104873657227, 'elapsed_seconds': 340.65429186820984, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 109/500 | Batch 10/202 | Rec 0.001541 | Seg 0.579098 | Elapsed 0.2m | ETA 4.1m
Epoch 109/500 | Batch 20/202 | Rec 0.001382 | Seg 0.585600 | Elapsed 0.4m | ETA 3.8m
Epoch 109/500 | Batch 30/202 | Rec 0.001291 | Seg 0.550906 | Elapsed 0.6m | ETA 3.6m
Epoch 109/500 | Batch 40/202 | Rec 0.001294 | Seg 0.556363 | Elapsed 0.8m | ETA 3.4m
Epoch 109/500 | Batch 50/202 | Rec 0.001338 | Seg 0.575572 | Elapsed 1.0m | ETA 3.2m
Epoch 109/500 | Batch 60/202 | Rec 0.001332 | Seg 0.574340 | Elapsed 1.3m | ETA 3.0m
Epoch 109/500 | Batch 70/202 | Rec 0.001281 | Seg 0.557337 | Elapsed 1.5m | ETA 2.8m
Epoch 109/500 | Batch 80/202 | Rec 0.001253 | Seg 0.546200 | Elapsed 1.7m | ETA 2.6m
Epoch 109/500 | Batch 90/202 | Rec 0.001242 | Seg 0.544373 | Elapsed 1.9m | ETA 2.4m
Epoch 109/500 | Batch 100/202 | Rec 0.001245 | Seg 0.553338 | Elapsed 2.1m | ETA 2.2m
Epoch 109/500 | Batch 110/202 | Rec 0.001250 | Seg 0.559649 | Elapsed 2.3m | ETA 2.0m
Epoch 109/500 | Batch 120/202 | Rec 0.001256 | Seg 0.554621 | Elapsed 2.6m | ETA 1.8m
Epoch 109/500 | Batch 130/202 | Rec 0.001263 | Seg 0.550276 | Elapsed 2.8m | ETA 1.5m
Epoch 109/500 | Batch 140/202 | Rec 0.001259 | Seg 0.551746 | Elapsed 3.0m | ETA 1.3m
Epoch 109/500 | Batch 150/202 | Rec 0.001255 | Seg 0.544700 | Elapsed 3.2m | ETA 1.1m
Epoch 109/500 | Batch 160/202 | Rec 0.001245 | Seg 0.538974 | Elapsed 3.4m | ETA 0.9m
Epoch 109/500 | Batch 170/202 | Rec 0.001247 | Seg 0.535782 | Elapsed 3.7m | ETA 0.7m
Epoch 109/500 | Batch 180/202 | Rec 0.001246 | Seg 0.533023 | Elapsed 3.9m | ETA 0.5m
Epoch 109/500 | Batch 190/202 | Rec 0.001242 | Seg 0.529301 | Elapsed 4.1m | ETA 0.3m
Epoch 109/500 | Batch 200/202 | Rec 0.001248 | Seg 0.527535 | Elapsed 4.3m | ETA 0.0m
Epoch 109/500 | Batch 202/202 | Rec 0.001249 | Seg 0.528805 | Elapsed 4.3m | ETA 0.0m

2026-09-22 14:13:25,150 - INFO: Rec loss: 0.0012486421929310436
2026-09-22 14:13:25,150 - INFO: Seg loss: 0.5288054587522356
2026-09-22 14:13:25,150 - INFO: λ_rec: 1
2026-09-22 14:13:25,150 - INFO: λ_seg: 0.0001
2026-09-22 14:14:48,820 - INFO: -------------------Epoch: 109------------------------
2026-09-22 14:14:48,824 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.951673  0.966069  0.000264
2026-09-22 14:14:48,832 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993570  0.996725  0.994448  0.999113  0.993845
real potato   0.690637  0.816965  0.994693  0.693191  0.999628
fake potato   0.879934  0.936083  0.990645  0.887306  0.999912
real apple    0.666285  0.799676  0.898560  0.720478  0.998755
fake apple    0.707669  0.828763  0.911236  0.760063  0.998815
real orange   0.291093  0.450889  0.970903  0.293654  0.999058
fake orange   0.659260  0.794594  0.681966  0.951924  0.998591
real grape    0.357484  0.526640  0.718308  0.415771  0.998440
fake grape    0.653728  0.790562  0.756358  0.828115  0.998377
real lemon    0.229657  0.373483  0.481171  0.305245  0.998797
fake lemon    0.760943  0.864196  0.991228  0.766102  0.999491
real avocado  0.803097  0.890748  0.990949  0.809031  0.999816
fake avocado  0.137524  0.241769  0.747521  0.144223  0.998918
real pepper   0.694811  0.819878  0.892919  0.757968  0.998782
fake pepper   0.695550  0.820392  0.868430  0.777479  0.999189
real plant    0.774440  0.872834  0.886853  0.859348  0.997496
fake plant    0.572219  0.727865  0.614968  0.891679  0.999469
real banana   0.240512  0.387731  0.970356  0.242293  0.998281
fake banana   0.487460  0.655378  0.544189  0.823822  0.998407
real onion    0.785076  0.879550  0.830681  0.934639  0.999769
fake onion    0.874026  0.932729  0.916453  0.949698  0.999914
real unknown  0.729569  0.843593  0.767187  0.937023  0.999944
fake unknown  0.110416  0.198829  0.145710  0.313111  0.997874
total         0.599781  0.715212  0.807206  0.698316  0.998764
total(-bg)    0.581881  0.702416  0.798695  0.684644  0.998987
2026-09-22 14:14:49,421 - INFO: Epoch accounting: {'epoch': 109, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11164581, 41630, 50027, 139913, 209286, 88007, 90709, 173592, 204663, 68880, 62085, 55902, 44398, 200993, 99028, 196241, 28566, 81152, 53338, 91716, 41340, 9619, 42606], 'crops_with_class': [202, 25, 22, 35, 48, 23, 32, 31, 38, 34, 27, 21, 14, 49, 27, 23, 24, 21, 18, 30, 16, 9, 18], 'targeted_crops_by_class': [0, 2, 6, 6, 8, 6, 3, 3, 3, 7, 6, 5, 5, 2, 3, 7, 5, 6, 0, 2, 4, 3, 6], 'sampled_scene_counts': [1, 2, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 0, 1, 2, 1, 0, 1, 2, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1, 2, 0, 0, 3, 2, 1, 2, 2, 4, 1, 2, 1, 1, 3, 0, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 4, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 0, 1, 3, 1, 3, 0, 2, 0, 3, 1, 0, 1, 3, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 3, 1, 2, 1, 1, 1, 2, 1], 'learning_rate': 8.895080729065526e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0012486421929310436, 'train_segmentation_loss': 0.5288054587522356, 'val_foreground_miou_all22': 0.5818813295319496, 'val_psnr_ref1': 35.95167327880859, 'elapsed_seconds': 344.59644508361816, 'peak_cuda_allocated_gib': 7.510318756103516}

Epoch 110/500 | Batch 10/202 | Rec 0.001352 | Seg 0.521458 | Elapsed 0.2m | ETA 4.2m
Epoch 110/500 | Batch 20/202 | Rec 0.001427 | Seg 0.584784 | Elapsed 0.4m | ETA 3.9m
Epoch 110/500 | Batch 30/202 | Rec 0.001404 | Seg 0.567217 | Elapsed 0.6m | ETA 3.6m
Epoch 110/500 | Batch 40/202 | Rec 0.001390 | Seg 0.578567 | Elapsed 0.8m | ETA 3.4m
Epoch 110/500 | Batch 50/202 | Rec 0.001315 | Seg 0.553821 | Elapsed 1.0m | ETA 3.2m
Epoch 110/500 | Batch 60/202 | Rec 0.001292 | Seg 0.546239 | Elapsed 1.3m | ETA 3.0m
Epoch 110/500 | Batch 70/202 | Rec 0.001289 | Seg 0.539931 | Elapsed 1.5m | ETA 2.8m
Epoch 110/500 | Batch 80/202 | Rec 0.001285 | Seg 0.553617 | Elapsed 1.7m | ETA 2.6m
Epoch 110/500 | Batch 90/202 | Rec 0.001260 | Seg 0.546180 | Elapsed 1.9m | ETA 2.4m
Epoch 110/500 | Batch 100/202 | Rec 0.001249 | Seg 0.543041 | Elapsed 2.1m | ETA 2.2m
Epoch 110/500 | Batch 110/202 | Rec 0.001250 | Seg 0.535556 | Elapsed 2.3m | ETA 2.0m
Epoch 110/500 | Batch 120/202 | Rec 0.001270 | Seg 0.532647 | Elapsed 2.5m | ETA 1.7m
Epoch 110/500 | Batch 130/202 | Rec 0.001277 | Seg 0.531279 | Elapsed 2.8m | ETA 1.5m
Epoch 110/500 | Batch 140/202 | Rec 0.001250 | Seg 0.521365 | Elapsed 3.0m | ETA 1.3m
Epoch 110/500 | Batch 150/202 | Rec 0.001222 | Seg 0.505717 | Elapsed 3.2m | ETA 1.1m
Epoch 110/500 | Batch 160/202 | Rec 0.001228 | Seg 0.505133 | Elapsed 3.4m | ETA 0.9m
Epoch 110/500 | Batch 170/202 | Rec 0.001225 | Seg 0.506113 | Elapsed 3.6m | ETA 0.7m
Epoch 110/500 | Batch 180/202 | Rec 0.001223 | Seg 0.501113 | Elapsed 3.8m | ETA 0.5m
Epoch 110/500 | Batch 190/202 | Rec 0.001224 | Seg 0.503997 | Elapsed 4.0m | ETA 0.3m
Epoch 110/500 | Batch 200/202 | Rec 0.001221 | Seg 0.500610 | Elapsed 4.2m | ETA 0.0m
Epoch 110/500 | Batch 202/202 | Rec 0.001223 | Seg 0.500844 | Elapsed 4.3m | ETA 0.0m

2026-09-22 14:19:06,576 - INFO: Rec loss: 0.0012228662105758978
2026-09-22 14:19:06,576 - INFO: Seg loss: 0.5008443528694091
2026-09-22 14:19:06,576 - INFO: λ_rec: 1
2026-09-22 14:19:06,576 - INFO: λ_seg: 0.0001
2026-09-22 14:20:29,791 - INFO: -------------------Epoch: 110------------------------
2026-09-22 14:20:29,795 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.904402  0.966554  0.000267
2026-09-22 14:20:29,803 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993720  0.996800  0.994467  0.999245  0.993988
real potato   0.840948  0.913553  0.879335  0.950650  0.999785
fake potato   0.805014  0.891926  0.826600  0.968580  0.999829
real apple    0.420580  0.592083  0.999580  0.420655  0.998001
fake apple    0.584091  0.737398  0.914463  0.617847  0.998339
real orange   0.482770  0.651129  0.977062  0.488305  0.999311
fake orange   0.643732  0.783208  0.672087  0.938493  0.998513
real grape    0.476364  0.645271  0.697732  0.600234  0.998622
fake grape    0.753414  0.859319  0.976987  0.767026  0.999071
real lemon    0.200615  0.334151  0.694103  0.220073  0.998969
fake lemon    0.791559  0.883604  0.996109  0.794014  0.999558
real avocado  0.566995  0.723626  1.000000  0.566995  0.999598
fake avocado  0.157101  0.271518  0.960496  0.158123  0.998985
real pepper   0.682207  0.811036  0.780477  0.844193  0.998562
fake pepper   0.597159  0.747729  0.963838  0.610844  0.999018
real plant    0.790063  0.882671  0.895161  0.870622  0.997686
fake plant    0.696467  0.821030  0.742330  0.918520  0.999681
real banana   0.384377  0.555264  0.887910  0.403979  0.998546
fake banana   0.444324  0.615222  0.493486  0.816855  0.998121
real onion    0.825340  0.904264  0.869755  0.941733  0.999820
fake onion    0.931602  0.964540  0.984635  0.945345  0.999956
real unknown  0.457421  0.627667  0.482794  0.896946  0.999830
fake unknown  0.101087  0.183579  0.117534  0.419413  0.996857
total         0.592476  0.712895  0.817693  0.702552  0.998724
total(-bg)    0.574238  0.699990  0.809658  0.689066  0.998939

Stopped after epoch 110; scheduler horizon remains 500

2026-09-22 14:20:30,383 - INFO: Epoch accounting: {'epoch': 110, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11283738, 47234, 56394, 121521, 115842, 65434, 76179, 157908, 181629, 79783, 66854, 53978, 37032, 219828, 150434, 117357, 28897, 98212, 80393, 89564, 52202, 8709, 49150], 'crops_with_class': [202, 26, 23, 31, 31, 21, 26, 26, 36, 31, 28, 19, 17, 62, 34, 17, 27, 25, 37, 40, 24, 9, 21], 'targeted_crops_by_class': [0, 7, 2, 2, 3, 4, 8, 5, 3, 9, 2, 6, 5, 11, 6, 2, 8, 10, 4, 7, 2, 5, 3], 'sampled_scene_counts': [2, 0, 1, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 2, 2, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 2, 1, 2, 1, 1, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 3, 0, 0, 1, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 3, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 2, 1, 0, 0, 1, 2, 1, 4, 1, 4, 1, 2, 1, 1, 1, 1, 2, 2, 1, 3, 1, 3, 0, 0, 1, 1, 0, 1, 2, 1, 3, 1, 2, 1, 1, 2, 4, 2, 3, 0, 3, 4, 0, 2, 3, 2, 3, 2, 1, 1, 1, 1, 2, 5, 1, 1, 1, 0, 1, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 2, 2, 2, 1, 1], 'learning_rate': 8.875334012741181e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0012228662105758978, 'train_segmentation_loss': 0.5008443528694091, 'val_foreground_miou_all22': 0.5742377754103709, 'val_psnr_ref1': 35.90440246582031, 'elapsed_seconds': 340.95255732536316, 'peak_cuda_allocated_gib': 7.510044097900391}

{
  "historical_control": {
    "final": {
      "epoch": 110,
      "scheduler_horizon": 500,
      "lambda_rec": 1,
      "lambda_seg": 0.0001,
      "learning_rate": 8.875334012741181e-05,
      "attempted_updates": 202,
      "optimizer_updates": 202,
      "amp_skipped_updates": 0,
      "train_reconstruction_loss": 0.0011724064606103567,
      "train_segmentation_loss": 0.44373450572095297,
      "val_foreground_miou_all22": 0.5061350281587473,
      "val_psnr_ref1": 35.944615783691404,
      "elapsed_seconds": 347.6273500919342,
      "peak_cuda_allocated_gib": 7.511264801025391
    },
    "best_logged_continuation_miou": 0.5769871229537121,
    "mean_last5_miou": 0.53186823965506,
    "std_last5_miou": 0.03449801483812449,
    "actual_updates": 2019,
    "amp_skips": 1
  },
  "balanced50": {
    "final": {
      "epoch": 110,
      "scheduler_horizon": 500,
      "lambda_rec": 1,
      "lambda_seg": 0.0001,
      "sampling_policy": "balanced50_v1",
      "class_pixels_seen": [
        11283738,
        47234,
        56394,
        121521,
        115842,
        65434,
        76179,
        157908,
        181629,
        79783,
        66854,
        53978,
        37032,
        219828,
        150434,
        117357,
        28897,
        98212,
        80393,
        89564,
        52202,
        8709,
        49150
      ],
      "crops_with_class": [
        202,
        26,
        23,
        31,
        31,
        21,
        26,
        26,
        36,
        31,
        28,
        19,
        17,
        62,
        34,
        17,
        27,
        25,
        37,
        40,
        24,
        9,
        21
      ],
      "targeted_crops_by_class": [
        0,
        7,
        2,
        2,
        3,
        4,
        8,
        5,
        3,
        9,
        2,
        6,
        5,
        11,
        6,
        2,
        8,
        10,
        4,
        7,
        2,
        5,
        3
      ],
      "sampled_scene_counts": [
        2,
        0,
        1,
        0,
        2,
        1,
        1,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        1,
        0,
        1,
        1,
        1,
        1,
        0,
        0,
        0,
        1,
        1,
        0,
        0,
        2,
        1,
        1,
        1,
        0,
        2,
        2,
        0,
        0,
        1,
        1,
        0,
        1,
        1,
        0,
        1,
        1,
        0,
        0,
        2,
        1,
        2,
        1,
        1,
        2,
        1,
        1,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        3,
        0,
        0,
        1,
        1,
        1,
        0,
        1,
        2,
        0,
        0,
        0,
        0,
        1,
        0,
        0,
        1,
        1,
        1,
        2,
        0,
        0,
        3,
        1,
        1,
        2,
        0,
        1,
        0,
        1,
        0,
        0,
        0,
        2,
        0,
        0,
        1,
        1,
        0,
        0,
        1,
        0,
        1,
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        1,
        0,
        1,
        2,
        1,
        0,
        0,
        1,
        2,
        1,
        4,
        1,
        4,
        1,
        2,
        1,
        1,
        1,
        1,
        2,
        2,
        1,
        3,
        1,
        3,
        0,
        0,
        1,
        1,
        0,
        1,
        2,
        1,
        3,
        1,
        2,
        1,
        1,
        2,
        4,
        2,
        3,
        0,
        3,
        4,
        0,
        2,
        3,
        2,
        3,
        2,
        1,
        1,
        1,
        1,
        2,
        5,
        1,
        1,
        1,
        0,
        1,
        3,
        1,
        2,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        0,
        1,
        1,
        0,
        0,
        0,
        2,
        2,
        2,
        2,
        1,
        1
      ],
      "learning_rate": 8.875334012741181e-05,
      "attempted_updates": 202,
      "optimizer_updates": 202,
      "amp_skipped_updates": 0,
      "train_reconstruction_loss": 0.0012228662105758978,
      "train_segmentation_loss": 0.5008443528694091,
      "val_foreground_miou_all22": 0.5742377754103709,
      "val_psnr_ref1": 35.90440246582031,
      "elapsed_seconds": 340.95255732536316,
      "peak_cuda_allocated_gib": 7.510044097900391
    },
    "best_logged_continuation_miou": 0.5989913541239169,
    "mean_last5_miou": 0.5803612217253259,
    "std_last5_miou": 0.014025907932290832,
    "actual_updates": 2019,
    "amp_skips": 1
  }
}
Archive: /kaggle/working/balanced_sampling_20260922_131859.zip Missing checkpoint files: []

/kaggle/working/balanced_sampling_20260922_131859.zip

Download the complete ZIP before ending the session.

In [4]:
summary = json.loads((OUT / 'comparison_summary.json').read_text())
assert summary['arms']['balanced50']['final']['epoch']==110
for arm, result in summary['arms'].items():
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))
print('Historical control is reused from the completed loss experiment; only balanced50 was newly trained.')

historical_control {
  "final": {
    "epoch": 110,
    "scheduler_horizon": 500,
    "lambda_rec": 1,
    "lambda_seg": 0.0001,
    "learning_rate": 8.875334012741181e-05,
    "attempted_updates": 202,
    "optimizer_updates": 202,
    "amp_skipped_updates": 0,
    "train_reconstruction_loss": 0.0011724064606103567,
    "train_segmentation_loss": 0.44373450572095297,
    "val_foreground_miou_all22": 0.5061350281587473,
    "val_psnr_ref1": 35.944615783691404,
    "elapsed_seconds": 347.6273500919342,
    "peak_cuda_allocated_gib": 7.511264801025391
  },
  "best_logged_continuation_miou": 0.5769871229537121,
  "mean_last5_miou": 0.53186823965506,
  "std_last5_miou": 0.03449801483812449,
  "actual_updates": 2019,
  "amp_skips": 1
}
balanced50 {
  "final": {
    "epoch": 110,
    "scheduler_horizon": 500,
    "lambda_rec": 1,
    "lambda_seg": 0.0001,
    "sampling_policy": "balanced50_v1",
    "class_pixels_seen": [
      11283738,
      47234,
      56394,
      121521,
      115842,
      65434,
      76179,
      157908,
      181629,
      79783,
      66854,
      53978,
      37032,
      219828,
      150434,
      117357,
      28897,
      98212,
      80393,
      89564,
      52202,
      8709,
      49150
    ],
    "crops_with_class": [
      202,
      26,
      23,
      31,
      31,
      21,
      26,
      26,
      36,
      31,
      28,
      19,
      17,
      62,
      34,
      17,
      27,
      25,
      37,
      40,
      24,
      9,
      21
    ],
    "targeted_crops_by_class": [
      0,
      7,
      2,
      2,
      3,
      4,
      8,
      5,
      3,
      9,
      2,
      6,
      5,
      11,
      6,
      2,
      8,
      10,
      4,
      7,
      2,
      5,
      3
    ],
    "sampled_scene_counts": [
      2,
      0,
      1,
      0,
      2,
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      2,
      1,
      1,
      1,
      0,
      2,
      2,
      0,
      0,
      1,
      1,
      0,
      1,
      1,
      0,
      1,
      1,
      0,
      0,
      2,
      1,
      2,
      1,
      1,
      2,
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      3,
      0,
      0,
      1,
      1,
      1,
      0,
      1,
      2,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      1,
      1,
      1,
      2,
      0,
      0,
      3,
      1,
      1,
      2,
      0,
      1,
      0,
      1,
      0,
      0,
      0,
      2,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      1,
      0,
      1,
      0,
      1,
      2,
      1,
      0,
      0,
      1,
      2,
      1,
      4,
      1,
      4,
      1,
      2,
      1,
      1,
      1,
      1,
      2,
      2,
      1,
      3,
      1,
      3,
      0,
      0,
      1,
      1,
      0,
      1,
      2,
      1,
      3,
      1,
      2,
      1,
      1,
      2,
      4,
      2,
      3,
      0,
      3,
      4,
      0,
      2,
      3,
      2,
      3,
      2,
      1,
      1,
      1,
      1,
      2,
      5,
      1,
      1,
      1,
      0,
      1,
      3,
      1,
      2,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      0,
      0,
      0,
      2,
      2,
      2,
      2,
      1,
      1
    ],
    "learning_rate": 8.875334012741181e-05,
    "attempted_updates": 202,
    "optimizer_updates": 202,
    "amp_skipped_updates": 0,
    "train_reconstruction_loss": 0.0012228662105758978,
    "train_segmentation_loss": 0.5008443528694091,
    "val_foreground_miou_all22": 0.5742377754103709,
    "val_psnr_ref1": 35.90440246582031,
    "elapsed_seconds": 340.95255732536316,
    "peak_cuda_allocated_gib": 7.510044097900391
  },
  "best_logged_continuation_miou": 0.5989913541239169,
  "mean_last5_miou": 0.5803612217253259,
  "std_last5_miou": 0.014025907932290832,
  "actual_updates": 2019,
  "amp_skips": 1
}
Historical control is reused from the completed loss experiment; only balanced50 was newly trained.

In [1]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_sampling_20260922_131859'
relative = expected + '/balanced50/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_sampling_20260922_131859.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch110 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 110
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 110
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')

Balanced epoch110 reference: /kaggle/input/datasets/arnavnigamd/checkpoint7/balanced_sampling_20260922_131859/balanced50
PASS:22-class support, aligned crops/flips, deterministic replay, no RNG consumed by index building, baseline crop branch unchanged.
Saved next-epoch LR: 8.855434798344244e-05
Preserved best metrics: {'iou': 0.5989913541239169, 'psnr': 36.03962860107422}
{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.

In [2]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'balanced_to_epoch130_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
shutil.copy2(CODE / 'public252-v1.json', OUT / 'dataset_protocol.json')
manifest = {
    'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
    'source_epoch': 110, 'stop_after_epoch': 130, 'sampling_policy': 'balanced50_v1',
    'note': 'Exact full-state continuation settings: lambda_seg1e-4; saved quarter-rate cosine schedule restored without additional scaling.',
    'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
        for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
}
(OUT / 'continuation.json').write_text(json.dumps(manifest, indent=2))
command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
    '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
    '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
    '--max_epoch', '500', '--stop_after_epoch', '130', '--resume', str(CHECKPOINT),
    '--outf', str(OUT.parent) + '/', '--name', NAME]
try:
    subprocess.run(command, cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{NAME}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{NAME}/model/{f}' not in z.namelist()]
    print('Archive:', archive, 'Missing checkpoint files:', missing)
    if (OUT / 'model/last.pt').is_file():
        saved = torch.load(OUT / 'model/last.pt', map_location='cpu', weights_only=True)
        print('Saved epoch:', saved['epoch'], 'Best metrics:', saved['best'])
        del saved
    import os
    os.chdir('/kaggle/working')
    display(FileLink(Path(archive).name))
    print('Download the complete ZIP before ending the session. A partial run can also produce an archive.')

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced_to_epoch130_20260922_143402', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/input/datasets/arnavnigamd/checkpoint7/balanced_sampling_20260922_131859/balanced50/model/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=130, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-22 14:34:50,344 - INFO: Resuming after epoch 110

Epoch 111/500 | Batch 10/202 | Rec 0.001794 | Seg 0.626496 | Elapsed 0.5m | ETA 10.1m
Epoch 111/500 | Batch 20/202 | Rec 0.001451 | Seg 0.557312 | Elapsed 0.8m | ETA 7.4m
Epoch 111/500 | Batch 30/202 | Rec 0.001381 | Seg 0.549214 | Elapsed 1.1m | ETA 6.2m
Epoch 111/500 | Batch 40/202 | Rec 0.001329 | Seg 0.557169 | Elapsed 1.4m | ETA 5.6m
Epoch 111/500 | Batch 50/202 | Rec 0.001300 | Seg 0.538946 | Elapsed 1.7m | ETA 5.1m
Epoch 111/500 | Batch 60/202 | Rec 0.001256 | Seg 0.518119 | Elapsed 2.0m | ETA 4.7m
Epoch 111/500 | Batch 70/202 | Rec 0.001237 | Seg 0.513168 | Elapsed 2.2m | ETA 4.2m
Epoch 111/500 | Batch 80/202 | Rec 0.001246 | Seg 0.508317 | Elapsed 2.5m | ETA 3.8m
Epoch 111/500 | Batch 90/202 | Rec 0.001228 | Seg 0.505219 | Elapsed 2.8m | ETA 3.4m
Epoch 111/500 | Batch 100/202 | Rec 0.001229 | Seg 0.495805 | Elapsed 3.0m | ETA 3.1m
Epoch 111/500 | Batch 110/202 | Rec 0.001216 | Seg 0.492942 | Elapsed 3.3m | ETA 2.8m
Epoch 111/500 | Batch 120/202 | Rec 0.001218 | Seg 0.493302 | Elapsed 3.6m | ETA 2.5m
Epoch 111/500 | Batch 130/202 | Rec 0.001212 | Seg 0.498886 | Elapsed 3.9m | ETA 2.2m
Epoch 111/500 | Batch 140/202 | Rec 0.001200 | Seg 0.492490 | Elapsed 4.2m | ETA 1.9m
Epoch 111/500 | Batch 150/202 | Rec 0.001186 | Seg 0.490184 | Elapsed 4.5m | ETA 1.6m
Epoch 111/500 | Batch 160/202 | Rec 0.001203 | Seg 0.485746 | Elapsed 4.8m | ETA 1.3m
Epoch 111/500 | Batch 170/202 | Rec 0.001219 | Seg 0.489601 | Elapsed 5.1m | ETA 1.0m
Epoch 111/500 | Batch 180/202 | Rec 0.001220 | Seg 0.486523 | Elapsed 5.4m | ETA 0.7m
Epoch 111/500 | Batch 190/202 | Rec 0.001222 | Seg 0.490079 | Elapsed 5.6m | ETA 0.4m
Epoch 111/500 | Batch 200/202 | Rec 0.001220 | Seg 0.487245 | Elapsed 5.9m | ETA 0.1m
Epoch 111/500 | Batch 202/202 | Rec 0.001220 | Seg 0.486636 | Elapsed 6.0m | ETA 0.0m

2026-09-22 14:40:49,229 - INFO: Rec loss: 0.001220329428070898
2026-09-22 14:40:49,229 - INFO: Seg loss: 0.4866358845098184
2026-09-22 14:40:49,229 - INFO: λ_rec: 1
2026-09-22 14:40:49,229 - INFO: λ_seg: 0.0001
2026-09-22 14:42:23,325 - INFO: -------------------Epoch: 111------------------------
2026-09-22 14:42:23,335 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  36.25307  0.966338  0.000254
2026-09-22 14:42:23,342 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993391  0.996635  0.994127  0.999255  0.993671
real potato   0.848485  0.917983  0.901228  0.935476  0.999800
fake potato   0.916292  0.956268  0.973114  0.940092  0.999937
real apple    0.450417  0.621043  0.953056  0.460637  0.998061
fake apple    0.581177  0.735071  0.865011  0.639145  0.998261
real orange   0.463798  0.633648  0.997512  0.464335  0.999293
fake orange   0.598724  0.748954  0.620342  0.944995  0.998187
real grape    0.175467  0.298500  0.360496  0.254769  0.997500
fake grape    0.735117  0.847290  0.903603  0.797674  0.998937
real lemon    0.187463  0.315691  0.445180  0.244612  0.998754
fake lemon    0.752187  0.858519  0.837517  0.880707  0.999386
real avocado  0.754844  0.860249  1.000000  0.754844  0.999772
fake avocado  0.426313  0.597741  0.999402  0.426422  0.999313
real pepper   0.528019  0.691068  0.883392  0.567579  0.998144
fake pepper   0.427508  0.598907  0.602213  0.595737  0.998098
real plant    0.712051  0.831761  0.819593  0.844398  0.996584
fake plant    0.691483  0.817556  0.755859  0.890337  0.999684
real banana   0.246208  0.395099  0.971535  0.247997  0.998294
fake banana   0.365569  0.535361  0.449501  0.661911  0.997887
real onion    0.798023  0.887617  0.903023  0.872826  0.999800
fake onion    0.892597  0.943201  0.969372  0.918501  0.999930
real unknown  0.473416  0.642562  0.537572  0.798664  0.999858
fake unknown  0.053099  0.100801  0.072269  0.166787  0.997494
total         0.568333  0.688327  0.774562  0.665552  0.998550
total(-bg)    0.549012  0.674313  0.764581  0.650384  0.998772
2026-09-22 14:42:23,980 - INFO: Epoch accounting: {'epoch': 111, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11269854, 56878, 52880, 160308, 117499, 88783, 82803, 104564, 139480, 68456, 67786, 28595, 38830, 266429, 181440, 136633, 22043, 62668, 86987, 69511, 66086, 9034, 60725], 'crops_with_class': [202, 35, 26, 43, 31, 26, 28, 21, 25, 34, 31, 12, 17, 64, 48, 20, 20, 20, 38, 35, 27, 11, 25], 'targeted_crops_by_class': [0, 7, 3, 1, 5, 1, 4, 6, 4, 9, 4, 2, 5, 5, 9, 4, 2, 4, 7, 8, 3, 4, 6], 'sampled_scene_counts': [2, 0, 4, 0, 0, 2, 3, 0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 1, 2, 1, 2, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1, 4, 1, 1, 0, 1, 0, 2, 0, 3, 0, 1, 1, 1, 1, 1, 2, 2, 2, 0, 2, 1, 1, 3, 0, 2, 2, 2, 1, 2, 0, 1, 2, 1, 1, 1, 1, 4, 1, 2, 5, 1, 2, 2, 1, 5, 0, 1, 0, 3, 3, 1, 2, 0, 2, 1, 2, 2, 1, 0, 2, 1, 3, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 2, 2, 1, 4, 0, 1], 'learning_rate': 8.855434798344244e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001220329428070898, 'train_segmentation_loss': 0.4866358845098184, 'val_foreground_miou_all22': 0.5490117371017248, 'val_psnr_ref1': 36.253070220947265, 'elapsed_seconds': 453.62858986854553, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 112/500 | Batch 10/202 | Rec 0.001244 | Seg 0.571040 | Elapsed 0.2m | ETA 4.3m
Epoch 112/500 | Batch 20/202 | Rec 0.001314 | Seg 0.551418 | Elapsed 0.5m | ETA 4.2m
Epoch 112/500 | Batch 30/202 | Rec 0.001372 | Seg 0.571568 | Elapsed 0.7m | ETA 4.0m
Epoch 112/500 | Batch 40/202 | Rec 0.001352 | Seg 0.556314 | Elapsed 0.9m | ETA 3.7m
Epoch 112/500 | Batch 50/202 | Rec 0.001320 | Seg 0.548005 | Elapsed 1.2m | ETA 3.6m
Epoch 112/500 | Batch 60/202 | Rec 0.001311 | Seg 0.542744 | Elapsed 1.5m | ETA 3.4m
Epoch 112/500 | Batch 70/202 | Rec 0.001305 | Seg 0.540150 | Elapsed 1.7m | ETA 3.3m
Epoch 112/500 | Batch 80/202 | Rec 0.001288 | Seg 0.537747 | Elapsed 2.0m | ETA 3.0m
Epoch 112/500 | Batch 90/202 | Rec 0.001282 | Seg 0.534023 | Elapsed 2.2m | ETA 2.8m
Epoch 112/500 | Batch 100/202 | Rec 0.001268 | Seg 0.529206 | Elapsed 2.5m | ETA 2.5m
Epoch 112/500 | Batch 110/202 | Rec 0.001293 | Seg 0.541504 | Elapsed 2.7m | ETA 2.3m
Epoch 112/500 | Batch 120/202 | Rec 0.001316 | Seg 0.536299 | Elapsed 2.9m | ETA 2.0m
Epoch 112/500 | Batch 130/202 | Rec 0.001316 | Seg 0.545383 | Elapsed 3.1m | ETA 1.7m
Epoch 112/500 | Batch 140/202 | Rec 0.001301 | Seg 0.539046 | Elapsed 3.4m | ETA 1.5m
Epoch 112/500 | Batch 150/202 | Rec 0.001288 | Seg 0.532887 | Elapsed 3.6m | ETA 1.3m
Epoch 112/500 | Batch 160/202 | Rec 0.001284 | Seg 0.533779 | Elapsed 3.9m | ETA 1.0m
Epoch 112/500 | Batch 170/202 | Rec 0.001275 | Seg 0.536697 | Elapsed 4.1m | ETA 0.8m
Epoch 112/500 | Batch 180/202 | Rec 0.001269 | Seg 0.528041 | Elapsed 4.3m | ETA 0.5m
Epoch 112/500 | Batch 190/202 | Rec 0.001276 | Seg 0.527603 | Elapsed 4.5m | ETA 0.3m
Epoch 112/500 | Batch 200/202 | Rec 0.001265 | Seg 0.520317 | Elapsed 4.8m | ETA 0.0m
Epoch 112/500 | Batch 202/202 | Rec 0.001269 | Seg 0.519456 | Elapsed 4.8m | ETA 0.0m

2026-09-22 14:47:12,655 - INFO: Rec loss: 0.0012694064742138627
2026-09-22 14:47:12,655 - INFO: Seg loss: 0.5194561290416387
2026-09-22 14:47:12,655 - INFO: λ_rec: 1
2026-09-22 14:47:12,655 - INFO: λ_seg: 0.0001
2026-09-22 14:48:28,889 - INFO: -------------------Epoch: 112------------------------
2026-09-22 14:48:28,893 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  35.791402  0.96619  0.000273
2026-09-22 14:48:28,902 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994324  0.997104  0.995285  0.999031  0.994571
real potato   0.555121  0.713880  0.982786  0.560571  0.999462
fake potato   0.794179  0.885235  0.999473  0.794512  0.999850
real apple    0.487655  0.655553  0.775523  0.567802  0.997942
fake apple    0.617283  0.763310  0.955241  0.635669  0.998512
real orange   0.495203  0.662344  0.996511  0.496063  0.999334
fake orange   0.666932  0.800142  0.697563  0.938226  0.998659
real grape    0.444369  0.615262  0.572165  0.665497  0.998263
fake grape    0.754534  0.860046  0.842276  0.878687  0.998943
real lemon    0.197367  0.329623  0.472829  0.253051  0.998791
fake lemon    0.800769  0.889314  0.983908  0.811396  0.999573
real avocado  0.752211  0.858535  0.896231  0.823974  0.999748
fake avocado  0.368505  0.538510  0.909366  0.382555  0.999216
real pepper   0.733466  0.846192  0.806109  0.890581  0.998816
fake pepper   0.590783  0.742710  0.979354  0.598233  0.999012
real plant    0.835737  0.910469  0.940491  0.882399  0.998265
fake plant    0.725281  0.840719  0.778322  0.914110  0.999724
real banana   0.336354  0.503351  0.928428  0.345308  0.998469
fake banana   0.451330  0.621907  0.504042  0.811878  0.998184
real onion    0.650038  0.787857  0.867289  0.721838  0.999649
fake onion    0.888540  0.940931  0.997292  0.890689  0.999930
real unknown  0.628232  0.771624  0.701248  0.857824  0.999919
fake unknown  0.127968  0.226861  0.152255  0.445129  0.997444
total         0.604182  0.728760  0.814521  0.702827  0.998795
total(-bg)    0.586448  0.716563  0.806305  0.689363  0.998987
2026-09-22 14:48:29,438 - INFO: Epoch accounting: {'epoch': 112, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11210046, 45523, 46919, 98843, 151404, 94912, 82314, 166924, 167743, 62018, 58494, 35344, 49159, 227227, 166836, 157183, 27965, 66106, 84264, 97657, 59323, 13308, 68760], 'crops_with_class': [202, 30, 24, 30, 40, 26, 29, 31, 33, 30, 26, 15, 18, 64, 39, 22, 26, 26, 35, 39, 29, 15, 27], 'targeted_crops_by_class': [0, 4, 5, 2, 9, 4, 5, 7, 3, 5, 1, 4, 6, 5, 7, 7, 10, 2, 8, 6, 4, 6, 3], 'sampled_scene_counts': [0, 1, 1, 1, 1, 2, 1, 0, 1, 3, 1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 3, 1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 1, 3, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 1, 0, 2, 3, 2, 1, 2, 1, 3, 1, 1, 0, 2, 2, 3, 1, 1, 2, 1, 5, 0, 0, 1, 2, 2, 1, 1, 1, 2, 1, 3, 2, 1, 4, 3, 2, 2, 3, 1, 1, 1, 0, 3, 3, 1, 1, 0, 0, 5, 1, 1, 1, 2, 4, 1, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 2, 2, 2, 3], 'learning_rate': 8.835383871461628e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0012694064742138627, 'train_segmentation_loss': 0.5194561290416387, 'val_foreground_miou_all22': 0.5864480055651223, 'val_psnr_ref1': 35.79140228271484, 'elapsed_seconds': 365.4504191875458, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 113/500 | Batch 10/202 | Rec 0.001209 | Seg 0.482914 | Elapsed 0.2m | ETA 4.3m
Epoch 113/500 | Batch 20/202 | Rec 0.001195 | Seg 0.456280 | Elapsed 0.5m | ETA 4.3m
Epoch 113/500 | Batch 30/202 | Rec 0.001085 | Seg 0.433377 | Elapsed 0.7m | ETA 4.0m
Epoch 113/500 | Batch 40/202 | Rec 0.001124 | Seg 0.449764 | Elapsed 0.9m | ETA 3.7m
Epoch 113/500 | Batch 50/202 | Rec 0.001135 | Seg 0.464885 | Elapsed 1.1m | ETA 3.5m
Epoch 113/500 | Batch 60/202 | Rec 0.001178 | Seg 0.495339 | Elapsed 1.4m | ETA 3.2m
Epoch 113/500 | Batch 70/202 | Rec 0.001171 | Seg 0.479799 | Elapsed 1.6m | ETA 3.0m
Epoch 113/500 | Batch 80/202 | Rec 0.001153 | Seg 0.472802 | Elapsed 1.8m | ETA 2.8m
Epoch 113/500 | Batch 90/202 | Rec 0.001173 | Seg 0.490622 | Elapsed 2.0m | ETA 2.5m
Epoch 113/500 | Batch 100/202 | Rec 0.001173 | Seg 0.491120 | Elapsed 2.2m | ETA 2.3m
Epoch 113/500 | Batch 110/202 | Rec 0.001152 | Seg 0.484333 | Elapsed 2.5m | ETA 2.1m
Epoch 113/500 | Batch 120/202 | Rec 0.001175 | Seg 0.483773 | Elapsed 2.7m | ETA 1.9m
Epoch 113/500 | Batch 130/202 | Rec 0.001166 | Seg 0.475046 | Elapsed 2.9m | ETA 1.6m
Epoch 113/500 | Batch 140/202 | Rec 0.001181 | Seg 0.484804 | Elapsed 3.2m | ETA 1.4m
Epoch 113/500 | Batch 150/202 | Rec 0.001189 | Seg 0.488937 | Elapsed 3.4m | ETA 1.2m
Epoch 113/500 | Batch 160/202 | Rec 0.001191 | Seg 0.487389 | Elapsed 3.6m | ETA 1.0m
Epoch 113/500 | Batch 170/202 | Rec 0.001187 | Seg 0.489225 | Elapsed 3.8m | ETA 0.7m
Epoch 113/500 | Batch 180/202 | Rec 0.001194 | Seg 0.493371 | Elapsed 4.1m | ETA 0.5m
Epoch 113/500 | Batch 190/202 | Rec 0.001198 | Seg 0.494328 | Elapsed 4.3m | ETA 0.3m
Epoch 113/500 | Batch 200/202 | Rec 0.001194 | Seg 0.496193 | Elapsed 4.5m | ETA 0.0m
Epoch 113/500 | Batch 202/202 | Rec 0.001195 | Seg 0.496429 | Elapsed 4.6m | ETA 0.0m

2026-09-22 14:53:03,201 - INFO: Rec loss: 0.001195163643973105
2026-09-22 14:53:03,201 - INFO: Seg loss: 0.49642915949963107
2026-09-22 14:53:03,201 - INFO: λ_rec: 1
2026-09-22 14:53:03,201 - INFO: λ_seg: 0.0001
2026-09-22 14:54:19,346 - INFO: -------------------Epoch: 113------------------------
2026-09-22 14:54:19,350 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.207605  0.967296  0.000249
2026-09-22 14:54:19,357 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994030  0.996956  0.995162  0.998856  0.994289
real potato   0.803985  0.891294  0.979090  0.818031  0.999761
fake potato   0.894982  0.944531  0.922693  0.967532  0.999917
real apple    0.724366  0.840104  0.962320  0.745511  0.999021
fake apple    0.624710  0.768963  0.957202  0.642661  0.998542
real orange   0.515220  0.680013  0.888806  0.550718  0.999317
fake orange   0.739516  0.850205  0.756862  0.969939  0.999022
real grape    0.176207  0.299583  0.641026  0.195498  0.998092
fake grape    0.781578  0.877350  0.900126  0.855793  0.999115
real lemon    0.301596  0.463375  0.429633  0.502986  0.998631
fake lemon    0.807329  0.893345  0.981354  0.819906  0.999586
real avocado  0.625307  0.769416  0.995051  0.627258  0.999651
fake avocado  0.133231  0.235115  0.991469  0.133384  0.998962
real pepper   0.736245  0.848039  0.866336  0.830594  0.998912
fake pepper   0.710091  0.830422  0.912850  0.761731  0.999259
real plant    0.754336  0.859917  0.831486  0.890469  0.997099
fake plant    0.502392  0.668743  0.523345  0.926189  0.999270
real banana   0.268782  0.423649  0.903548  0.276721  0.998308
fake banana   0.584417  0.737656  0.706763  0.771483  0.998991
real onion    0.745678  0.854264  0.788264  0.932444  0.999713
fake onion    0.836538  0.910945  0.877803  0.946796  0.999883
real unknown  0.343003  0.510761  0.348112  0.958969  0.999706
fake unknown  0.131289  0.232067  0.155777  0.455089  0.997463
total         0.597166  0.712466  0.796308  0.720807  0.998805
total(-bg)    0.579127  0.699534  0.787269  0.708168  0.999010
2026-09-22 14:54:19,943 - INFO: Epoch accounting: {'epoch': 113, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11217652, 57081, 82942, 122646, 146050, 66277, 51321, 132182, 162003, 64144, 58219, 34983, 23882, 267904, 134020, 142325, 27256, 121313, 91744, 97535, 70229, 8764, 57800], 'crops_with_class': [202, 31, 33, 31, 39, 25, 20, 30, 32, 28, 26, 11, 10, 63, 38, 21, 23, 31, 38, 45, 33, 13, 24], 'targeted_crops_by_class': [0, 6, 4, 3, 7, 5, 3, 5, 2, 5, 5, 4, 3, 2, 5, 7, 3, 10, 5, 8, 10, 9, 6], 'sampled_scene_counts': [0, 1, 1, 0, 0, 0, 1, 1, 1, 3, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 0, 2, 0, 2, 0, 2, 1, 1, 0, 3, 2, 5, 4, 0, 2, 0, 3, 1, 1, 0, 2, 1, 0, 2, 0, 1, 2, 0, 3, 6, 1, 3, 1, 5, 1, 3, 1, 2, 1, 1, 3, 2, 2, 2, 1, 1, 0, 2, 3, 1, 1, 0, 1, 3, 1, 4, 0, 4, 4, 1, 1, 0, 2, 1, 3, 1, 2, 1], 'learning_rate': 8.815182023669592e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001195163643973105, 'train_segmentation_loss': 0.49642915949963107, 'val_foreground_miou_all22': 0.5791272460010758, 'val_psnr_ref1': 36.20760498046875, 'elapsed_seconds': 350.4977068901062, 'peak_cuda_allocated_gib': 7.510044097900391}

Epoch 114/500 | Batch 10/202 | Rec 0.001444 | Seg 0.472517 | Elapsed 0.2m | ETA 4.4m
Epoch 114/500 | Batch 20/202 | Rec 0.001320 | Seg 0.491650 | Elapsed 0.4m | ETA 4.1m
Epoch 114/500 | Batch 30/202 | Rec 0.001211 | Seg 0.479733 | Elapsed 0.7m | ETA 3.8m
Epoch 114/500 | Batch 40/202 | Rec 0.001185 | Seg 0.471578 | Elapsed 0.9m | ETA 3.6m
Epoch 114/500 | Batch 50/202 | Rec 0.001206 | Seg 0.493618 | Elapsed 1.1m | ETA 3.3m
Epoch 114/500 | Batch 60/202 | Rec 0.001194 | Seg 0.485837 | Elapsed 1.3m | ETA 3.1m
Epoch 114/500 | Batch 70/202 | Rec 0.001154 | Seg 0.468109 | Elapsed 1.5m | ETA 2.9m
Epoch 114/500 | Batch 80/202 | Rec 0.001151 | Seg 0.487571 | Elapsed 1.7m | ETA 2.7m
Epoch 114/500 | Batch 90/202 | Rec 0.001118 | Seg 0.465584 | Elapsed 2.0m | ETA 2.4m
Epoch 114/500 | Batch 100/202 | Rec 0.001125 | Seg 0.469114 | Elapsed 2.2m | ETA 2.2m
Epoch 114/500 | Batch 110/202 | Rec 0.001131 | Seg 0.472498 | Elapsed 2.4m | ETA 2.0m
Epoch 114/500 | Batch 120/202 | Rec 0.001118 | Seg 0.462863 | Elapsed 2.6m | ETA 1.8m
Epoch 114/500 | Batch 130/202 | Rec 0.001123 | Seg 0.463827 | Elapsed 2.8m | ETA 1.6m
Epoch 114/500 | Batch 140/202 | Rec 0.001126 | Seg 0.464345 | Elapsed 3.0m | ETA 1.4m
Epoch 114/500 | Batch 150/202 | Rec 0.001134 | Seg 0.463351 | Elapsed 3.3m | ETA 1.1m
Epoch 114/500 | Batch 160/202 | Rec 0.001135 | Seg 0.458948 | Elapsed 3.5m | ETA 0.9m
Epoch 114/500 | Batch 170/202 | Rec 0.001127 | Seg 0.453041 | Elapsed 3.7m | ETA 0.7m
Epoch 114/500 | Batch 180/202 | Rec 0.001104 | Seg 0.446058 | Elapsed 3.9m | ETA 0.5m
Epoch 114/500 | Batch 190/202 | Rec 0.001104 | Seg 0.443485 | Elapsed 4.1m | ETA 0.3m
Epoch 114/500 | Batch 200/202 | Rec 0.001105 | Seg 0.440226 | Elapsed 4.4m | ETA 0.0m
Epoch 114/500 | Batch 202/202 | Rec 0.001109 | Seg 0.440990 | Elapsed 4.4m | ETA 0.0m

2026-09-22 14:58:45,891 - INFO: Rec loss: 0.0011087284814727742
2026-09-22 14:58:45,891 - INFO: Seg loss: 0.4409896785227379
2026-09-22 14:58:45,891 - INFO: λ_rec: 1
2026-09-22 14:58:45,891 - INFO: λ_seg: 0.0001
2026-09-22 15:00:01,927 - INFO: -------------------Epoch: 114------------------------
2026-09-22 15:00:01,931 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.347289  0.966743  0.000243
2026-09-22 15:00:01,938 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994231  0.997057  0.994945  0.999279  0.994480
real potato   0.204030  0.338883  1.000000  0.204030  0.999048
fake potato   0.490997  0.658571  0.999148  0.491202  0.999629
real apple    0.602126  0.751609  0.711593  0.796506  0.998184
fake apple    0.728980  0.843199  0.903125  0.790818  0.998890
real orange   0.464860  0.634639  0.999751  0.464914  0.999295
fake orange   0.643381  0.782949  0.653120  0.977348  0.998449
real grape    0.566617  0.723315  0.883662  0.612293  0.999022
fake grape    0.771786  0.871146  0.872204  0.870189  0.999048
real lemon    0.191919  0.321984  0.334078  0.310828  0.998462
fake lemon    0.820528  0.901368  0.931186  0.873494  0.999596
real avocado  0.668684  0.801401  0.804567  0.798358  0.999632
fake avocado  0.224667  0.366869  0.812773  0.236929  0.999022
real pepper   0.712204  0.831865  0.855901  0.809236  0.998804
fake pepper   0.371016  0.541188  0.993841  0.371871  0.998497
real plant    0.793822  0.885012  0.927393  0.846427  0.997801
fake plant    0.709119  0.829757  0.797665  0.864647  0.999718
real banana   0.060421  0.113946  0.995526  0.060437  0.997888
fake banana   0.431952  0.603259  0.483936  0.800846  0.998063
real onion    0.648216  0.786517  0.800245  0.773349  0.999621
fake onion    0.906910  0.951133  0.980488  0.923579  0.999940
real unknown  0.544225  0.704805  0.570585  0.921756  0.999877
fake unknown  0.103941  0.188270  0.126550  0.367802  0.997328
total         0.550201  0.670815  0.801403  0.659397  0.998708
total(-bg)    0.530018  0.655986  0.792606  0.643948  0.998901
2026-09-22 15:00:02,642 - INFO: Epoch accounting: {'epoch': 114, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11418184, 44421, 39575, 174742, 146987, 93144, 95155, 103218, 175166, 55319, 26864, 57443, 34834, 193655, 116528, 143543, 24168, 56216, 78096, 64787, 37851, 9814, 48562], 'crops_with_class': [202, 24, 19, 45, 38, 27, 30, 24, 31, 26, 15, 19, 14, 48, 28, 20, 17, 18, 33, 26, 20, 11, 20], 'targeted_crops_by_class': [0, 6, 1, 11, 1, 3, 11, 5, 4, 3, 0, 7, 3, 3, 4, 5, 6, 2, 5, 4, 2, 6, 3], 'sampled_scene_counts': [1, 1, 1, 1, 1, 2, 2, 1, 3, 2, 0, 1, 2, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 3, 0, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1, 3, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 2, 3, 1, 1, 0, 1, 0, 2, 1, 1, 3, 0, 3, 0, 3, 3, 1, 0, 3, 0, 1, 2, 4, 3, 2, 1, 1, 1, 1, 3, 2, 1, 2, 2, 1, 3, 3, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 2, 0, 1, 1, 2, 2, 2, 1, 2, 2, 2, 3, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 3, 1], 'learning_rate': 8.794830052502497e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0011087284814727742, 'train_segmentation_loss': 0.4409896785227379, 'val_foreground_miou_all22': 0.5300183258627421, 'val_psnr_ref1': 36.34728897094727, 'elapsed_seconds': 342.69056940078735, 'peak_cuda_allocated_gib': 7.509685516357422}

Epoch 115/500 | Batch 10/202 | Rec 0.001543 | Seg 0.497618 | Elapsed 0.2m | ETA 4.4m
Epoch 115/500 | Batch 20/202 | Rec 0.001352 | Seg 0.501122 | Elapsed 0.4m | ETA 4.0m
Epoch 115/500 | Batch 30/202 | Rec 0.001297 | Seg 0.531545 | Elapsed 0.7m | ETA 3.7m
Epoch 115/500 | Batch 40/202 | Rec 0.001248 | Seg 0.510239 | Elapsed 0.9m | ETA 3.5m
Epoch 115/500 | Batch 50/202 | Rec 0.001227 | Seg 0.521366 | Elapsed 1.1m | ETA 3.3m
Epoch 115/500 | Batch 60/202 | Rec 0.001231 | Seg 0.516221 | Elapsed 1.3m | ETA 3.1m
Epoch 115/500 | Batch 70/202 | Rec 0.001228 | Seg 0.508368 | Elapsed 1.5m | ETA 2.9m
Epoch 115/500 | Batch 80/202 | Rec 0.001240 | Seg 0.519702 | Elapsed 1.7m | ETA 2.7m
Epoch 115/500 | Batch 90/202 | Rec 0.001244 | Seg 0.512882 | Elapsed 2.0m | ETA 2.4m
Epoch 115/500 | Batch 100/202 | Rec 0.001276 | Seg 0.521000 | Elapsed 2.2m | ETA 2.2m
Epoch 115/500 | Batch 110/202 | Rec 0.001255 | Seg 0.511457 | Elapsed 2.4m | ETA 2.0m
Epoch 115/500 | Batch 120/202 | Rec 0.001254 | Seg 0.511797 | Elapsed 2.6m | ETA 1.8m
Epoch 115/500 | Batch 130/202 | Rec 0.001288 | Seg 0.516900 | Elapsed 2.8m | ETA 1.6m
Epoch 115/500 | Batch 140/202 | Rec 0.001265 | Seg 0.503541 | Elapsed 3.0m | ETA 1.3m
Epoch 115/500 | Batch 150/202 | Rec 0.001246 | Seg 0.496942 | Elapsed 3.3m | ETA 1.1m
Epoch 115/500 | Batch 160/202 | Rec 0.001242 | Seg 0.488125 | Elapsed 3.5m | ETA 0.9m
Epoch 115/500 | Batch 170/202 | Rec 0.001238 | Seg 0.491049 | Elapsed 3.7m | ETA 0.7m
Epoch 115/500 | Batch 180/202 | Rec 0.001241 | Seg 0.498829 | Elapsed 3.9m | ETA 0.5m
Epoch 115/500 | Batch 190/202 | Rec 0.001243 | Seg 0.498071 | Elapsed 4.1m | ETA 0.3m
Epoch 115/500 | Batch 200/202 | Rec 0.001234 | Seg 0.499383 | Elapsed 4.3m | ETA 0.0m
Epoch 115/500 | Batch 202/202 | Rec 0.001235 | Seg 0.500646 | Elapsed 4.4m | ETA 0.0m

2026-09-22 15:04:26,197 - INFO: Rec loss: 0.0012345153921673368
2026-09-22 15:04:26,198 - INFO: Seg loss: 0.5006458014987483
2026-09-22 15:04:26,198 - INFO: λ_rec: 1
2026-09-22 15:04:26,198 - INFO: λ_seg: 0.0001
2026-09-22 15:05:42,548 - INFO: -------------------Epoch: 115------------------------
2026-09-22 15:05:42,553 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.850458  0.966446  0.000267
2026-09-22 15:05:42,560 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993873  0.996877  0.994537  0.999329  0.994135
real potato   0.365723  0.535535  1.000000  0.365723  0.999241
fake potato   0.771339  0.870861  0.998375  0.772308  0.999833
real apple    0.566808  0.723470  0.824055  0.644847  0.998300
fake apple    0.716570  0.834836  0.878960  0.795021  0.998813
real orange   0.428671  0.600055  1.000000  0.428671  0.999247
fake orange   0.766177  0.867561  0.788124  0.964929  0.999157
real grape    0.148460  0.258507  0.679950  0.159614  0.998089
fake grape    0.669195  0.801768  0.772581  0.833354  0.998476
real lemon    0.117590  0.210386  0.215295  0.205791  0.998185
fake lemon    0.798884  0.888150  0.933757  0.846881  0.999549
real avocado  0.798416  0.887861  0.957281  0.827915  0.999806
fake avocado  0.107965  0.194863  0.662232  0.114257  0.998870
real pepper   0.743176  0.852619  0.867617  0.838228  0.998940
fake pepper   0.687723  0.814922  0.908733  0.738749  0.999200
real plant    0.741242  0.851345  0.859488  0.843453  0.997055
fake plant    0.684841  0.812894  0.793645  0.833206  0.999695
real banana   0.008094  0.016040  0.077013  0.008964  0.997532
fake banana   0.390065  0.561171  0.450371  0.744443  0.997859
real onion    0.680385  0.809747  0.833542  0.787367  0.999666
fake onion    0.877931  0.934948  0.999450  0.878355  0.999923
real unknown  0.770567  0.870368  0.948256  0.804389  0.999962
fake unknown  0.111608  0.200768  0.131455  0.425027  0.997149
total         0.562839  0.669372  0.764118  0.646123  0.998638
total(-bg)    0.543247  0.654485  0.753645  0.630068  0.998843
2026-09-22 15:05:43,098 - INFO: Epoch accounting: {'epoch': 115, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11191641, 68806, 63185, 142140, 174738, 47642, 81883, 157525, 202102, 67377, 46351, 48406, 40464, 200185, 150397, 126903, 28336, 106632, 82217, 90760, 71126, 10665, 38791], 'crops_with_class': [202, 40, 31, 34, 41, 18, 28, 31, 35, 28, 23, 14, 16, 52, 40, 17, 23, 33, 32, 36, 30, 12, 16], 'targeted_crops_by_class': [0, 8, 7, 4, 4, 3, 7, 3, 5, 4, 4, 4, 5, 4, 1, 2, 4, 5, 6, 8, 5, 4, 1], 'sampled_scene_counts': [1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 3, 0, 0, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 2, 5, 1, 4, 1, 1, 1, 0, 0, 2, 1, 0, 1, 2, 3, 2, 0, 1, 1, 2, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 5, 2, 2, 1, 1, 2, 1, 5, 0, 2, 2, 2, 1, 1, 3, 3, 0, 0, 1, 2, 2, 1, 3, 1, 1, 0, 2, 0, 1, 3, 1, 1, 2, 1, 1, 0, 0, 1, 1, 4, 2, 4, 1], 'learning_rate': 8.774328761421314e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0012345153921673368, 'train_segmentation_loss': 0.5006458014987483, 'val_foreground_miou_all22': 0.5432468791348052, 'val_psnr_ref1': 35.850457916259764, 'elapsed_seconds': 340.4480366706848, 'peak_cuda_allocated_gib': 7.508365631103516}

Epoch 116/500 | Batch 10/202 | Rec 0.001155 | Seg 0.475872 | Elapsed 0.2m | ETA 4.2m
Epoch 116/500 | Batch 20/202 | Rec 0.001122 | Seg 0.422177 | Elapsed 0.4m | ETA 3.9m
Epoch 116/500 | Batch 30/202 | Rec 0.001144 | Seg 0.421529 | Elapsed 0.7m | ETA 3.7m
Epoch 116/500 | Batch 40/202 | Rec 0.001164 | Seg 0.447655 | Elapsed 0.9m | ETA 3.5m
Epoch 116/500 | Batch 50/202 | Rec 0.001196 | Seg 0.463111 | Elapsed 1.1m | ETA 3.3m
Epoch 116/500 | Batch 60/202 | Rec 0.001231 | Seg 0.470525 | Elapsed 1.3m | ETA 3.1m
Epoch 116/500 | Batch 70/202 | Rec 0.001262 | Seg 0.464849 | Elapsed 1.5m | ETA 2.9m
Epoch 116/500 | Batch 80/202 | Rec 0.001289 | Seg 0.483393 | Elapsed 1.7m | ETA 2.6m
Epoch 116/500 | Batch 90/202 | Rec 0.001293 | Seg 0.485359 | Elapsed 1.9m | ETA 2.4m
Epoch 116/500 | Batch 100/202 | Rec 0.001306 | Seg 0.485474 | Elapsed 2.2m | ETA 2.2m
Epoch 116/500 | Batch 110/202 | Rec 0.001318 | Seg 0.492229 | Elapsed 2.4m | ETA 2.0m
Epoch 116/500 | Batch 120/202 | Rec 0.001314 | Seg 0.486895 | Elapsed 2.6m | ETA 1.8m
Epoch 116/500 | Batch 130/202 | Rec 0.001311 | Seg 0.490412 | Elapsed 2.8m | ETA 1.6m
Epoch 116/500 | Batch 140/202 | Rec 0.001310 | Seg 0.494337 | Elapsed 3.0m | ETA 1.3m
Epoch 116/500 | Batch 150/202 | Rec 0.001333 | Seg 0.497196 | Elapsed 3.2m | ETA 1.1m
Epoch 116/500 | Batch 160/202 | Rec 0.001322 | Seg 0.495412 | Elapsed 3.5m | ETA 0.9m
Epoch 116/500 | Batch 170/202 | Rec 0.001308 | Seg 0.492954 | Elapsed 3.7m | ETA 0.7m
Epoch 116/500 | Batch 180/202 | Rec 0.001286 | Seg 0.485853 | Elapsed 3.9m | ETA 0.5m
Epoch 116/500 | Batch 190/202 | Rec 0.001284 | Seg 0.488395 | Elapsed 4.1m | ETA 0.3m
Epoch 116/500 | Batch 200/202 | Rec 0.001275 | Seg 0.487043 | Elapsed 4.3m | ETA 0.0m
Epoch 116/500 | Batch 202/202 | Rec 0.001274 | Seg 0.486445 | Elapsed 4.4m | ETA 0.0m

2026-09-22 15:10:05,886 - INFO: Rec loss: 0.0012737996935311907
2026-09-22 15:10:05,886 - INFO: Seg loss: 0.48644520117357226
2026-09-22 15:10:05,886 - INFO: λ_rec: 1
2026-09-22 15:10:05,886 - INFO: λ_seg: 0.0001
2026-09-22 15:11:22,338 - INFO: -------------------Epoch: 116------------------------
2026-09-22 15:11:22,342 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.378119  0.966463  0.000239
2026-09-22 15:11:22,350 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994103  0.996993  0.994871  0.999224  0.994357
real potato   0.240882  0.388212  1.000000  0.240882  0.999092
fake potato   0.474654  0.643706  1.000000  0.474654  0.999617
real apple    0.584938  0.738071  0.741149  0.735117  0.998200
fake apple    0.789954  0.882603  0.914471  0.852974  0.999144
real orange   0.332353  0.498857  0.934202  0.340320  0.999099
fake orange   0.642819  0.782532  0.656179  0.969300  0.998458
real grape    0.056984  0.107798  0.347809  0.063802  0.997796
fake grape    0.698777  0.822633  0.782329  0.867426  0.998617
real lemon    0.232825  0.377660  0.398960  0.358608  0.998611
fake lemon    0.824812  0.903947  0.960185  0.854021  0.999616
real avocado  0.675746  0.806453  0.914982  0.721018  0.999678
fake avocado  0.120910  0.215706  0.600816  0.131472  0.998856
real pepper   0.728085  0.842600  0.891376  0.798974  0.998909
fake pepper   0.529779  0.692576  0.990709  0.532424  0.998874
real plant    0.730108  0.843953  0.839790  0.848258  0.996864
fake plant    0.672097  0.803847  0.753014  0.862155  0.999665
real banana   0.013865  0.027342  0.300142  0.014328  0.997710
fake banana   0.393679  0.564904  0.429689  0.824486  0.997664
real onion    0.630371  0.773235  0.830393  0.723526  0.999617
fake onion    0.931900  0.964700  0.998448  0.933253  0.999957
real unknown  0.670659  0.802818  0.756757  0.854962  0.999933
fake unknown  0.121321  0.216350  0.146819  0.411264  0.997490
total         0.525723  0.639022  0.747091  0.626628  0.998601
total(-bg)    0.504433  0.622750  0.735828  0.609692  0.998794
2026-09-22 15:11:23,052 - INFO: Epoch accounting: {'epoch': 116, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11226237, 45755, 63542, 124431, 155050, 81073, 60024, 124572, 233469, 68730, 65649, 41786, 39664, 228362, 148903, 166112, 25443, 74522, 70551, 67686, 55219, 12747, 58745], 'crops_with_class': [202, 28, 27, 31, 39, 25, 21, 26, 38, 35, 27, 15, 13, 57, 40, 21, 22, 22, 27, 29, 24, 15, 25], 'targeted_crops_by_class': [0, 2, 2, 4, 2, 3, 3, 5, 2, 4, 6, 8, 4, 6, 7, 2, 4, 7, 2, 3, 2, 6, 6], 'sampled_scene_counts': [2, 0, 3, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 2, 1, 0, 2, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 1, 2, 0, 1, 2, 0, 1, 1, 1, 0, 2, 1, 0, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 3, 0, 1, 2, 2, 1, 1, 4, 1, 1, 2, 0, 1, 3, 0, 1, 3, 1, 1, 0, 1, 2, 2, 2, 0, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 1, 4, 4, 1, 2, 4, 1, 3, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 1, 3, 1, 0, 2, 1, 2, 3, 0, 0, 0, 1, 1, 2, 1, 1, 2], 'learning_rate': 8.753678959781913e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0012737996935311907, 'train_segmentation_loss': 0.48644520117357226, 'val_foreground_miou_all22': 0.5044326685093519, 'val_psnr_ref1': 36.37811859130859, 'elapsed_seconds': 339.9471535682678, 'peak_cuda_allocated_gib': 7.513614654541016}

Epoch 117/500 | Batch 10/202 | Rec 0.001197 | Seg 0.544026 | Elapsed 0.2m | ETA 4.3m
Epoch 117/500 | Batch 20/202 | Rec 0.001290 | Seg 0.474015 | Elapsed 0.4m | ETA 4.0m
Epoch 117/500 | Batch 30/202 | Rec 0.001261 | Seg 0.456372 | Elapsed 0.7m | ETA 3.8m
Epoch 117/500 | Batch 40/202 | Rec 0.001207 | Seg 0.434868 | Elapsed 0.9m | ETA 3.6m
Epoch 117/500 | Batch 50/202 | Rec 0.001217 | Seg 0.435127 | Elapsed 1.1m | ETA 3.3m
Epoch 117/500 | Batch 60/202 | Rec 0.001195 | Seg 0.449471 | Elapsed 1.3m | ETA 3.1m
Epoch 117/500 | Batch 70/202 | Rec 0.001223 | Seg 0.466727 | Elapsed 1.5m | ETA 2.9m
Epoch 117/500 | Batch 80/202 | Rec 0.001236 | Seg 0.469592 | Elapsed 1.7m | ETA 2.6m
Epoch 117/500 | Batch 90/202 | Rec 0.001237 | Seg 0.479604 | Elapsed 1.9m | ETA 2.4m
Epoch 117/500 | Batch 100/202 | Rec 0.001248 | Seg 0.490428 | Elapsed 2.1m | ETA 2.2m
Epoch 117/500 | Batch 110/202 | Rec 0.001241 | Seg 0.488285 | Elapsed 2.4m | ETA 2.0m
Epoch 117/500 | Batch 120/202 | Rec 0.001218 | Seg 0.482071 | Elapsed 2.6m | ETA 1.8m
Epoch 117/500 | Batch 130/202 | Rec 0.001229 | Seg 0.478673 | Elapsed 2.8m | ETA 1.6m
Epoch 117/500 | Batch 140/202 | Rec 0.001219 | Seg 0.477086 | Elapsed 3.0m | ETA 1.3m
Epoch 117/500 | Batch 150/202 | Rec 0.001228 | Seg 0.484584 | Elapsed 3.2m | ETA 1.1m
Epoch 117/500 | Batch 160/202 | Rec 0.001224 | Seg 0.486820 | Elapsed 3.4m | ETA 0.9m
Epoch 117/500 | Batch 170/202 | Rec 0.001248 | Seg 0.496874 | Elapsed 3.7m | ETA 0.7m
Epoch 117/500 | Batch 180/202 | Rec 0.001238 | Seg 0.492980 | Elapsed 3.9m | ETA 0.5m
Epoch 117/500 | Batch 190/202 | Rec 0.001254 | Seg 0.496146 | Elapsed 4.1m | ETA 0.3m
Epoch 117/500 | Batch 200/202 | Rec 0.001241 | Seg 0.490033 | Elapsed 4.3m | ETA 0.0m
Epoch 117/500 | Batch 202/202 | Rec 0.001235 | Seg 0.489251 | Elapsed 4.3m | ETA 0.0m

2026-09-22 15:15:43,409 - INFO: Rec loss: 0.001235367584740743
2026-09-22 15:15:43,409 - INFO: Seg loss: 0.4892508366910538
2026-09-22 15:15:43,409 - INFO: λ_rec: 1
2026-09-22 15:15:43,409 - INFO: λ_seg: 0.0001
2026-09-22 15:16:59,837 - INFO: -------------------Epoch: 117------------------------
2026-09-22 15:16:59,841 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.238519  0.966604  0.000245
2026-09-22 15:16:59,848 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994495  0.997190  0.995789  0.998695  0.994737
real potato   0.706459  0.827934  0.998739  0.707090  0.999648
fake potato   0.940352  0.969209  0.999110  0.941139  0.999957
real apple    0.514966  0.679790  0.838917  0.571473  0.998143
fake apple    0.677626  0.807789  0.871306  0.752991  0.998647
real orange   0.603578  0.752742  0.974250  0.613363  0.999469
fake orange   0.676915  0.807285  0.703588  0.946967  0.998706
real grape    0.364126  0.533813  0.704396  0.429803  0.998433
fake grape    0.752509  0.858729  0.803893  0.921709  0.998879
real lemon    0.056957  0.107728  0.129461  0.092314  0.998204
fake lemon    0.804898  0.891854  0.939851  0.848612  0.999565
real avocado  0.753273  0.859226  0.794561  0.935468  0.999715
fake avocado  0.403266  0.574712  0.964543  0.409334  0.999275
real pepper   0.691181  0.817344  0.802970  0.832346  0.998640
fake pepper   0.551255  0.710675  0.964968  0.562512  0.998909
real plant    0.800706  0.889275  0.896802  0.881972  0.997804
fake plant    0.684211  0.812451  0.729268  0.917178  0.999663
real banana   0.068219  0.127710  0.880208  0.068858  0.997887
fake banana   0.411243  0.582764  0.446594  0.838587  0.997791
real onion    0.687168  0.814531  0.821649  0.807634  0.999668
fake onion    0.920830  0.958734  0.997907  0.922612  0.999950
real unknown  0.628045  0.771484  0.669474  0.910305  0.999914
fake unknown  0.102715  0.186255  0.129019  0.335024  0.997534
total         0.599782  0.710401  0.785098  0.706347  0.998745
total(-bg)    0.581841  0.697365  0.775522  0.693059  0.998927
2026-09-22 15:17:00,375 - INFO: Epoch accounting: {'epoch': 117, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11246566, 50329, 73506, 89562, 130095, 68338, 81316, 155859, 181414, 96347, 69192, 58268, 35044, 195079, 126944, 227625, 30665, 65210, 56778, 86054, 56749, 9550, 47782], 'crops_with_class': [202, 30, 33, 25, 39, 22, 31, 30, 38, 41, 29, 21, 15, 53, 34, 28, 26, 20, 26, 38, 25, 10, 23], 'targeted_crops_by_class': [0, 4, 5, 5, 10, 3, 5, 3, 3, 6, 5, 4, 6, 5, 3, 8, 7, 6, 4, 4, 3, 3, 5], 'sampled_scene_counts': [1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 3, 2, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 2, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 2, 2, 1, 1, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 0, 1, 2, 3, 0, 2, 0, 3, 0, 2, 0, 2, 0, 3, 1, 3, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 1, 1, 4, 2, 3, 3, 1, 1, 1, 1, 1, 1, 1, 3, 4, 2, 3, 2, 2, 1, 1, 5, 2, 2, 2, 1, 1, 0, 0, 2, 1, 0, 1, 0, 3, 2, 0, 4, 1, 0, 2, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 1, 3, 1, 1], 'learning_rate': 8.732881462803105e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001235367584740743, 'train_segmentation_loss': 0.4892508366910538, 'val_foreground_miou_all22': 0.5818407489319545, 'val_psnr_ref1': 36.23851913452148, 'elapsed_seconds': 337.3151788711548, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 118/500 | Batch 10/202 | Rec 0.001510 | Seg 0.587125 | Elapsed 0.2m | ETA 4.2m
Epoch 118/500 | Batch 20/202 | Rec 0.001298 | Seg 0.554919 | Elapsed 0.4m | ETA 3.9m
Epoch 118/500 | Batch 30/202 | Rec 0.001214 | Seg 0.504007 | Elapsed 0.6m | ETA 3.7m
Epoch 118/500 | Batch 40/202 | Rec 0.001156 | Seg 0.476782 | Elapsed 0.9m | ETA 3.5m
Epoch 118/500 | Batch 50/202 | Rec 0.001169 | Seg 0.492393 | Elapsed 1.1m | ETA 3.3m
Epoch 118/500 | Batch 60/202 | Rec 0.001183 | Seg 0.487560 | Elapsed 1.3m | ETA 3.1m
Epoch 118/500 | Batch 70/202 | Rec 0.001199 | Seg 0.486079 | Elapsed 1.5m | ETA 2.9m
Epoch 118/500 | Batch 80/202 | Rec 0.001175 | Seg 0.477507 | Elapsed 1.7m | ETA 2.7m
Epoch 118/500 | Batch 90/202 | Rec 0.001200 | Seg 0.480075 | Elapsed 2.0m | ETA 2.4m
Epoch 118/500 | Batch 100/202 | Rec 0.001187 | Seg 0.473968 | Elapsed 2.2m | ETA 2.2m
Epoch 118/500 | Batch 110/202 | Rec 0.001204 | Seg 0.471990 | Elapsed 2.4m | ETA 2.0m
Epoch 118/500 | Batch 120/202 | Rec 0.001211 | Seg 0.479259 | Elapsed 2.6m | ETA 1.8m
Epoch 118/500 | Batch 130/202 | Rec 0.001202 | Seg 0.476488 | Elapsed 2.8m | ETA 1.6m
Epoch 118/500 | Batch 140/202 | Rec 0.001214 | Seg 0.477335 | Elapsed 3.0m | ETA 1.3m
Epoch 118/500 | Batch 150/202 | Rec 0.001212 | Seg 0.473467 | Elapsed 3.3m | ETA 1.1m
Epoch 118/500 | Batch 160/202 | Rec 0.001207 | Seg 0.471108 | Elapsed 3.5m | ETA 0.9m
Epoch 118/500 | Batch 170/202 | Rec 0.001204 | Seg 0.477382 | Elapsed 3.7m | ETA 0.7m
Epoch 118/500 | Batch 180/202 | Rec 0.001199 | Seg 0.472760 | Elapsed 3.9m | ETA 0.5m
Epoch 118/500 | Batch 190/202 | Rec 0.001217 | Seg 0.478234 | Elapsed 4.1m | ETA 0.3m
Epoch 118/500 | Batch 200/202 | Rec 0.001219 | Seg 0.478868 | Elapsed 4.3m | ETA 0.0m
Epoch 118/500 | Batch 202/202 | Rec 0.001232 | Seg 0.480087 | Elapsed 4.4m | ETA 0.0m

2026-09-22 15:21:22,122 - INFO: Rec loss: 0.001231587258522574
2026-09-22 15:21:22,122 - INFO: Seg loss: 0.4800867380039527
2026-09-22 15:21:22,122 - INFO: λ_rec: 1
2026-09-22 15:21:22,123 - INFO: λ_seg: 0.0001
2026-09-22 15:22:38,719 - INFO: -------------------Epoch: 118------------------------
2026-09-22 15:22:38,724 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.058226  0.966141  0.000257
2026-09-22 15:22:38,731 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994490  0.997187  0.995707  0.998772  0.994732
real potato   0.615871  0.762230  0.988020  0.620505  0.999537
fake potato   0.876751  0.934279  0.966212  0.904483  0.999907
real apple    0.666876  0.800101  0.854587  0.752234  0.998704
fake apple    0.555831  0.714465  0.906971  0.589436  0.998222
real orange   0.478919  0.647617  0.994960  0.480083  0.999312
fake orange   0.690704  0.817012  0.708807  0.964343  0.998764
real grape    0.697827  0.821974  0.884761  0.767595  0.999306
fake grape    0.762878  0.865442  0.906105  0.828363  0.999048
real lemon    0.188706  0.317452  0.420231  0.255129  0.998711
fake lemon    0.795520  0.886067  0.998283  0.796610  0.999567
real avocado  0.783627  0.878640  0.867991  0.889655  0.999772
fake avocado  0.242881  0.390803  0.970172  0.244708  0.999087
real pepper   0.717362  0.835373  0.830141  0.840773  0.998788
fake pepper   0.662383  0.796859  0.950102  0.686256  0.999166
real plant    0.859577  0.924437  0.917234  0.931856  0.998477
fake plant    0.691285  0.817418  0.737434  0.916986  0.999674
real banana   0.181279  0.306891  0.908757  0.184639  0.998126
fake banana   0.448341  0.619063  0.496248  0.822827  0.998138
real onion    0.752971  0.859030  0.831962  0.888026  0.999737
fake onion    0.860721  0.925098  0.903806  0.947521  0.999903
real unknown  0.678522  0.808426  0.715968  0.928435  0.999930
fake unknown  0.160593  0.276708  0.179337  0.605759  0.997332
total         0.624518  0.739242  0.823209  0.732391  0.998867
total(-bg)    0.607701  0.727517  0.815368  0.720283  0.999055
2026-09-22 15:22:39,469 - INFO: Epoch accounting: {'epoch': 118, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11269256, 49007, 65111, 94801, 124140, 93590, 82724, 155968, 169248, 67971, 63813, 43522, 45324, 217501, 137050, 164085, 27211, 90064, 82981, 83912, 44107, 11291, 55595], 'crops_with_class': [202, 31, 26, 34, 32, 27, 26, 32, 28, 34, 24, 15, 17, 56, 36, 23, 26, 25, 34, 33, 21, 13, 22], 'targeted_crops_by_class': [0, 2, 4, 3, 5, 4, 7, 2, 6, 3, 5, 5, 5, 5, 3, 3, 6, 5, 3, 10, 4, 6, 9], 'sampled_scene_counts': [3, 1, 1, 1, 0, 3, 0, 1, 1, 3, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 1, 1, 2, 3, 2, 0, 2, 2, 1, 1, 1, 1, 1, 2, 3, 2, 1, 1, 2, 1, 2, 1, 3, 2, 4, 3, 2, 0, 3, 1, 2, 1, 2, 1, 2, 1, 0, 2, 0, 1, 1, 3, 2, 2, 0, 0, 3, 1, 1, 2, 1, 3, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 0], 'learning_rate': 8.711937091534459e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001231587258522574, 'train_segmentation_loss': 0.4800867380039527, 'val_foreground_miou_all22': 0.6077011777293602, 'val_psnr_ref1': 36.05822647094727, 'elapsed_seconds': 339.085825920105, 'peak_cuda_allocated_gib': 7.512149810791016}

Epoch 119/500 | Batch 10/202 | Rec 0.001296 | Seg 0.438192 | Elapsed 0.2m | ETA 4.2m
Epoch 119/500 | Batch 20/202 | Rec 0.001312 | Seg 0.485293 | Elapsed 0.4m | ETA 3.9m
Epoch 119/500 | Batch 30/202 | Rec 0.001359 | Seg 0.526619 | Elapsed 0.6m | ETA 3.7m
Epoch 119/500 | Batch 40/202 | Rec 0.001286 | Seg 0.510049 | Elapsed 0.9m | ETA 3.5m
Epoch 119/500 | Batch 50/202 | Rec 0.001263 | Seg 0.501080 | Elapsed 1.1m | ETA 3.3m
Epoch 119/500 | Batch 60/202 | Rec 0.001240 | Seg 0.495628 | Elapsed 1.3m | ETA 3.1m
Epoch 119/500 | Batch 70/202 | Rec 0.001245 | Seg 0.501962 | Elapsed 1.5m | ETA 2.9m
Epoch 119/500 | Batch 80/202 | Rec 0.001233 | Seg 0.494679 | Elapsed 1.7m | ETA 2.6m
Epoch 119/500 | Batch 90/202 | Rec 0.001271 | Seg 0.520318 | Elapsed 1.9m | ETA 2.4m
Epoch 119/500 | Batch 100/202 | Rec 0.001267 | Seg 0.522580 | Elapsed 2.1m | ETA 2.2m
Epoch 119/500 | Batch 110/202 | Rec 0.001248 | Seg 0.520281 | Elapsed 2.4m | ETA 2.0m
Epoch 119/500 | Batch 120/202 | Rec 0.001241 | Seg 0.513071 | Elapsed 2.6m | ETA 1.8m
Epoch 119/500 | Batch 130/202 | Rec 0.001225 | Seg 0.507898 | Elapsed 2.8m | ETA 1.5m
Epoch 119/500 | Batch 140/202 | Rec 0.001250 | Seg 0.506074 | Elapsed 3.0m | ETA 1.3m
Epoch 119/500 | Batch 150/202 | Rec 0.001252 | Seg 0.508569 | Elapsed 3.2m | ETA 1.1m
Epoch 119/500 | Batch 160/202 | Rec 0.001235 | Seg 0.505063 | Elapsed 3.4m | ETA 0.9m
Epoch 119/500 | Batch 170/202 | Rec 0.001225 | Seg 0.499780 | Elapsed 3.7m | ETA 0.7m
Epoch 119/500 | Batch 180/202 | Rec 0.001207 | Seg 0.494088 | Elapsed 3.9m | ETA 0.5m
Epoch 119/500 | Batch 190/202 | Rec 0.001211 | Seg 0.493346 | Elapsed 4.1m | ETA 0.3m
Epoch 119/500 | Batch 200/202 | Rec 0.001222 | Seg 0.496842 | Elapsed 4.3m | ETA 0.0m
Epoch 119/500 | Batch 202/202 | Rec 0.001228 | Seg 0.500955 | Elapsed 4.4m | ETA 0.0m

2026-09-22 15:27:00,607 - INFO: Rec loss: 0.0012278630008337797
2026-09-22 15:27:00,607 - INFO: Seg loss: 0.5009553795034932
2026-09-22 15:27:00,607 - INFO: λ_rec: 1
2026-09-22 15:27:00,607 - INFO: λ_seg: 0.0001
2026-09-22 15:28:16,825 - INFO: -------------------Epoch: 119------------------------
2026-09-22 15:28:16,830 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.316353  0.965968  0.000243
2026-09-22 15:28:16,837 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994338  0.997111  0.995418  0.998910  0.994585
real potato   0.506431  0.672314  0.997242  0.507141  0.999409
fake potato   0.920336  0.958466  0.976320  0.941349  0.999941
real apple    0.742005  0.851848  0.882900  0.822999  0.999013
fake apple    0.599216  0.749340  0.951993  0.617887  0.998440
real orange   0.235334  0.380973  0.935265  0.239231  0.998976
fake orange   0.695874  0.820618  0.720701  0.952830  0.998808
real grape    0.431319  0.602644  0.952321  0.440839  0.998786
fake grape    0.771843  0.871182  0.851062  0.892381  0.999024
real lemon    0.027508  0.053507  0.114663  0.034926  0.998549
fake lemon    0.818207  0.899966  0.971737  0.838154  0.999606
real avocado  0.795954  0.886336  0.972729  0.814121  0.999806
fake avocado  0.147226  0.256641  0.942557  0.148559  0.998970
real pepper   0.718101  0.835874  0.821108  0.851285  0.998778
fake pepper   0.743001  0.852504  0.930622  0.786569  0.999352
real plant    0.811695  0.896012  0.866331  0.927905  0.997847
fake plant    0.598145  0.748501  0.652329  0.878067  0.999530
real banana   0.142617  0.249600  0.635808  0.155304  0.997902
fake banana   0.348954  0.517326  0.382758  0.798026  0.997261
real onion    0.749232  0.856591  0.812169  0.906266  0.999726
fake onion    0.754488  0.860016  0.788900  0.945345  0.999806
real unknown  0.874881  0.933216  0.992473  0.880725  0.999980
fake unknown  0.109071  0.196645  0.147571  0.294821  0.997971
total         0.588512  0.693358  0.795434  0.681463  0.998785
total(-bg)    0.570065  0.679551  0.786344  0.667033  0.998976
2026-09-22 15:28:17,373 - INFO: Epoch accounting: {'epoch': 119, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11136344, 56669, 57963, 155775, 152489, 76902, 93031, 127078, 256491, 75990, 62718, 48936, 28991, 240021, 125600, 165718, 28695, 89201, 75719, 69209, 65406, 14609, 34717], 'crops_with_class': [202, 31, 23, 39, 45, 23, 30, 29, 44, 27, 29, 15, 12, 62, 35, 20, 26, 27, 28, 35, 30, 15, 18], 'targeted_crops_by_class': [0, 5, 7, 8, 9, 1, 3, 4, 5, 2, 5, 5, 5, 7, 3, 3, 4, 5, 2, 4, 7, 5, 5], 'sampled_scene_counts': [1, 1, 0, 1, 2, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 0, 2, 0, 0, 0, 2, 1, 0, 0, 1, 0, 1, 1, 1, 0, 2, 1, 0, 0, 2, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 1, 2, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 1, 2, 2, 1, 2, 5, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 3, 1, 1, 2, 2, 1, 1, 2, 1, 1, 0, 1, 3, 1, 3, 1, 2, 0, 1, 1, 1, 0, 2, 2, 0, 0, 1, 3, 4, 3, 1, 1, 1, 2, 2, 0, 0, 2, 2, 2, 0, 2, 2, 0, 4, 0, 2, 1, 1, 1, 4, 1, 2, 2, 1, 2, 2, 0, 1, 1, 2, 1, 0, 1, 2, 0, 2, 0, 4, 1], 'learning_rate': 8.690846672823889e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0012278630008337797, 'train_segmentation_loss': 0.5009553795034932, 'val_foreground_miou_all22': 0.5700654246416349, 'val_psnr_ref1': 36.31635330200195, 'elapsed_seconds': 337.89721751213074, 'peak_cuda_allocated_gib': 7.507846832275391}

Epoch 120/500 | Batch 10/202 | Rec 0.001278 | Seg 0.488584 | Elapsed 0.2m | ETA 4.1m
Epoch 120/500 | Batch 20/202 | Rec 0.001108 | Seg 0.459898 | Elapsed 0.4m | ETA 3.9m
Epoch 120/500 | Batch 30/202 | Rec 0.001163 | Seg 0.476383 | Elapsed 0.6m | ETA 3.7m
Epoch 120/500 | Batch 40/202 | Rec 0.001130 | Seg 0.468949 | Elapsed 0.9m | ETA 3.5m
Epoch 120/500 | Batch 50/202 | Rec 0.001108 | Seg 0.464423 | Elapsed 1.1m | ETA 3.3m
Epoch 120/500 | Batch 60/202 | Rec 0.001103 | Seg 0.458584 | Elapsed 1.3m | ETA 3.0m
Epoch 120/500 | Batch 70/202 | Rec 0.001082 | Seg 0.444883 | Elapsed 1.5m | ETA 2.8m
Epoch 120/500 | Batch 80/202 | Rec 0.001109 | Seg 0.454094 | Elapsed 1.7m | ETA 2.6m
Epoch 120/500 | Batch 90/202 | Rec 0.001079 | Seg 0.444200 | Elapsed 1.9m | ETA 2.4m
Epoch 120/500 | Batch 100/202 | Rec 0.001069 | Seg 0.446615 | Elapsed 2.2m | ETA 2.2m
Epoch 120/500 | Batch 110/202 | Rec 0.001059 | Seg 0.441575 | Elapsed 2.4m | ETA 2.0m
Epoch 120/500 | Batch 120/202 | Rec 0.001058 | Seg 0.447732 | Elapsed 2.6m | ETA 1.8m
Epoch 120/500 | Batch 130/202 | Rec 0.001073 | Seg 0.447846 | Elapsed 2.8m | ETA 1.6m
Epoch 120/500 | Batch 140/202 | Rec 0.001074 | Seg 0.446130 | Elapsed 3.0m | ETA 1.3m
Epoch 120/500 | Batch 150/202 | Rec 0.001101 | Seg 0.452016 | Elapsed 3.3m | ETA 1.1m
Epoch 120/500 | Batch 160/202 | Rec 0.001108 | Seg 0.454088 | Elapsed 3.5m | ETA 0.9m
Epoch 120/500 | Batch 170/202 | Rec 0.001113 | Seg 0.453774 | Elapsed 3.7m | ETA 0.7m
Epoch 120/500 | Batch 180/202 | Rec 0.001104 | Seg 0.447708 | Elapsed 3.9m | ETA 0.5m
Epoch 120/500 | Batch 190/202 | Rec 0.001126 | Seg 0.451079 | Elapsed 4.1m | ETA 0.3m
Epoch 120/500 | Batch 200/202 | Rec 0.001130 | Seg 0.448259 | Elapsed 4.4m | ETA 0.0m
Epoch 120/500 | Batch 202/202 | Rec 0.001127 | Seg 0.447957 | Elapsed 4.4m | ETA 0.0m

2026-09-22 15:32:41,283 - INFO: Rec loss: 0.0011273715594647415
2026-09-22 15:32:41,283 - INFO: Seg loss: 0.44795749460042705
2026-09-22 15:32:41,283 - INFO: λ_rec: 1
2026-09-22 15:32:41,284 - INFO: λ_seg: 0.0001
2026-09-22 15:33:57,521 - INFO: -------------------Epoch: 120------------------------
2026-09-22 15:33:57,525 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  36.169746  0.965478  0.00025
2026-09-22 15:33:57,532 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994750  0.997318  0.995964  0.998776  0.994982
real potato   0.838278  0.911975  0.978521  0.853991  0.999803
fake potato   0.894869  0.944468  0.999766  0.895057  0.999923
real apple    0.727119  0.841952  0.891183  0.797965  0.998967
fake apple    0.670350  0.802597  0.970919  0.684085  0.998730
real orange   0.444706  0.615589  0.853448  0.481473  0.999208
fake orange   0.729395  0.843477  0.751751  0.960825  0.998979
real grape    0.654272  0.790959  0.824663  0.759994  0.999162
fake grape    0.831588  0.908002  0.963913  0.858310  0.999357
real lemon    0.489279  0.657019  0.604294  0.719943  0.999117
fake lemon    0.806723  0.892974  0.984615  0.817021  0.999586
real avocado  0.723433  0.839476  0.902550  0.784729  0.999721
fake avocado  0.040151  0.077193  0.755924  0.040678  0.998836
real pepper   0.739385  0.850118  0.841875  0.858627  0.998893
fake pepper   0.756511  0.861329  0.921126  0.808911  0.999379
real plant    0.843673  0.915159  0.918648  0.911795  0.998310
fake plant    0.506332  0.672225  0.522358  0.942868  0.999268
real banana   0.376622  0.547127  0.948877  0.384422  0.998570
fake banana   0.602765  0.752107  0.707560  0.802754  0.999027
real onion    0.657337  0.793195  0.818541  0.769465  0.999638
fake onion    0.911034  0.953396  0.948540  0.958404  0.999941
real unknown  0.360015  0.529387  0.368500  0.939885  0.999733
fake unknown  0.177077  0.300835  0.209771  0.531873  0.997917
total         0.642420  0.752082  0.812318  0.763559  0.999002
total(-bg)    0.626405  0.740935  0.803970  0.752867  0.999185
2026-09-22 15:33:58,260 - INFO: Epoch accounting: {'epoch': 120, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11329265, 44664, 36711, 115450, 119867, 69779, 72941, 129078, 201914, 74579, 59773, 36994, 29617, 242341, 128282, 155135, 25309, 84502, 79634, 82066, 59529, 10493, 50349], 'crops_with_class': [202, 27, 19, 29, 30, 24, 23, 26, 33, 31, 27, 11, 12, 62, 38, 23, 22, 25, 34, 39, 25, 11, 22], 'targeted_crops_by_class': [0, 2, 2, 4, 3, 1, 7, 3, 2, 6, 3, 1, 5, 5, 7, 6, 4, 6, 4, 8, 5, 3, 3], 'sampled_scene_counts': [1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 2, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 1, 0, 1, 0, 2, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 1, 2, 2, 1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 1, 1, 4, 2, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 3, 0, 1, 1, 5, 1, 3, 0, 2, 1, 1, 0, 0, 2, 2, 2, 3, 3, 1, 1, 2, 1, 4, 1, 1, 0, 2, 3, 1, 5, 1, 1, 1, 1, 3, 2, 0, 0, 2, 2, 0, 0, 1, 2, 2, 2, 1, 1, 0, 0, 1, 1, 1, 2, 3, 1, 1], 'learning_rate': 8.669611039285016e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0011273715594647415, 'train_segmentation_loss': 0.44795749460042705, 'val_foreground_miou_all22': 0.6264051148932249, 'val_psnr_ref1': 36.16974639892578, 'elapsed_seconds': 340.8788459300995, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 121/500 | Batch 10/202 | Rec 0.001237 | Seg 0.493949 | Elapsed 0.2m | ETA 4.2m
Epoch 121/500 | Batch 20/202 | Rec 0.001144 | Seg 0.495564 | Elapsed 0.4m | ETA 4.0m
Epoch 121/500 | Batch 30/202 | Rec 0.001124 | Seg 0.499818 | Elapsed 0.6m | ETA 3.7m
Epoch 121/500 | Batch 40/202 | Rec 0.001095 | Seg 0.470370 | Elapsed 0.9m | ETA 3.5m
Epoch 121/500 | Batch 50/202 | Rec 0.001234 | Seg 0.506446 | Elapsed 1.1m | ETA 3.3m
Epoch 121/500 | Batch 60/202 | Rec 0.001275 | Seg 0.517897 | Elapsed 1.3m | ETA 3.0m
Epoch 121/500 | Batch 70/202 | Rec 0.001248 | Seg 0.514646 | Elapsed 1.5m | ETA 2.8m
Epoch 121/500 | Batch 80/202 | Rec 0.001256 | Seg 0.528693 | Elapsed 1.7m | ETA 2.6m
Epoch 121/500 | Batch 90/202 | Rec 0.001220 | Seg 0.523086 | Elapsed 1.9m | ETA 2.4m
Epoch 121/500 | Batch 100/202 | Rec 0.001201 | Seg 0.512421 | Elapsed 2.1m | ETA 2.2m
Epoch 121/500 | Batch 110/202 | Rec 0.001196 | Seg 0.505720 | Elapsed 2.4m | ETA 2.0m
Epoch 121/500 | Batch 120/202 | Rec 0.001209 | Seg 0.505548 | Elapsed 2.6m | ETA 1.8m
Epoch 121/500 | Batch 130/202 | Rec 0.001203 | Seg 0.502271 | Elapsed 2.8m | ETA 1.5m
Epoch 121/500 | Batch 140/202 | Rec 0.001208 | Seg 0.504445 | Elapsed 3.0m | ETA 1.3m
Epoch 121/500 | Batch 150/202 | Rec 0.001201 | Seg 0.497881 | Elapsed 3.2m | ETA 1.1m
Epoch 121/500 | Batch 160/202 | Rec 0.001196 | Seg 0.493698 | Elapsed 3.4m | ETA 0.9m
Epoch 121/500 | Batch 170/202 | Rec 0.001207 | Seg 0.501723 | Elapsed 3.7m | ETA 0.7m
Epoch 121/500 | Batch 180/202 | Rec 0.001188 | Seg 0.492877 | Elapsed 3.9m | ETA 0.5m
Epoch 121/500 | Batch 190/202 | Rec 0.001188 | Seg 0.493168 | Elapsed 4.1m | ETA 0.3m
Epoch 121/500 | Batch 200/202 | Rec 0.001186 | Seg 0.490525 | Elapsed 4.3m | ETA 0.0m
Epoch 121/500 | Batch 202/202 | Rec 0.001188 | Seg 0.495282 | Elapsed 4.3m | ETA 0.0m

2026-09-22 15:38:19,078 - INFO: Rec loss: 0.0011878398756812428
2026-09-22 15:38:19,078 - INFO: Seg loss: 0.49528170198128363
2026-09-22 15:38:19,078 - INFO: λ_rec: 1
2026-09-22 15:38:19,078 - INFO: λ_seg: 0.0001
2026-09-22 15:39:35,868 - INFO: -------------------Epoch: 121------------------------
2026-09-22 15:39:35,872 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.285604  0.967523  0.000244
2026-09-22 15:39:35,880 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994573  0.997229  0.996411  0.998149  0.994815
real potato   0.356034  0.525071  0.995020  0.356669  0.999228
fake potato   0.918187  0.957299  0.977516  0.937997  0.999939
real apple    0.650721  0.788358  0.800483  0.776692  0.998562
fake apple    0.611360  0.758765  0.972759  0.622009  0.998507
real orange   0.361414  0.530895  0.807710  0.395438  0.999079
fake orange   0.730102  0.843949  0.750487  0.964130  0.998980
real grape    0.353968  0.522819  0.879993  0.371921  0.998583
fake grape    0.769161  0.869471  0.864416  0.874685  0.999029
real lemon    0.056417  0.106770  0.216495  0.070891  0.998607
fake lemon    0.836631  0.911000  0.988688  0.844717  0.999651
real avocado  0.708744  0.829500  0.918962  0.755993  0.999711
fake avocado  0.354376  0.523266  0.962432  0.359347  0.999217
real pepper   0.729949  0.843847  0.815817  0.873978  0.998817
fake pepper   0.735357  0.847450  0.978463  0.747455  0.999359
real plant    0.813661  0.897208  0.853705  0.945494  0.997834
fake plant    0.619807  0.765237  0.653158  0.923888  0.999549
real banana   0.043055  0.082540  0.496257  0.045022  0.997751
fake banana   0.313875  0.477744  0.338754  0.810385  0.996741
real onion    0.686744  0.814234  0.756264  0.881946  0.999637
fake onion    0.757664  0.862076  0.793054  0.944377  0.999809
real unknown  0.698499  0.822441  0.710125  0.977099  0.999933
fake unknown  0.134685  0.237358  0.158340  0.474104  0.997433
total         0.575434  0.687588  0.768927  0.693582  0.998729
total(-bg)    0.556382  0.673514  0.758586  0.679738  0.998907
2026-09-22 15:39:36,467 - INFO: Epoch accounting: {'epoch': 121, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11139956, 42347, 50763, 118088, 183931, 89315, 77994, 186529, 242999, 65100, 82877, 43502, 38021, 204368, 97083, 216008, 21940, 91475, 78657, 62523, 44086, 12545, 48165], 'crops_with_class': [202, 25, 26, 35, 44, 28, 29, 29, 47, 29, 35, 13, 13, 52, 29, 24, 22, 27, 29, 30, 18, 12, 22], 'targeted_crops_by_class': [0, 1, 2, 4, 5, 4, 8, 5, 8, 2, 6, 8, 0, 4, 4, 5, 6, 6, 5, 6, 5, 10, 3], 'sampled_scene_counts': [1, 0, 0, 0, 2, 2, 3, 0, 1, 3, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 3, 1, 0, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 3, 2, 0, 3, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 4, 0, 2, 2, 1, 1, 2, 1, 2, 3, 4, 1, 1, 2, 3, 0, 1, 2, 1, 0, 2, 0, 0, 4, 0, 2, 2, 2, 0, 2, 1, 0, 0, 1, 3, 3, 1, 0, 1, 2, 4, 4, 2, 2, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 1, 3, 3, 2, 1, 1, 1, 1, 2, 5, 3, 1, 1, 1, 1, 1, 1, 5, 0, 0, 1, 1, 0, 2, 0, 0, 1, 0], 'learning_rate': 8.648231029264287e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0011878398756812428, 'train_segmentation_loss': 0.49528170198128363, 'val_foreground_miou_all22': 0.5563823150673027, 'val_psnr_ref1': 36.285603790283204, 'elapsed_seconds': 338.197954416275, 'peak_cuda_allocated_gib': 7.510044097900391}

Epoch 122/500 | Batch 10/202 | Rec 0.001100 | Seg 0.512961 | Elapsed 0.2m | ETA 4.2m
Epoch 122/500 | Batch 20/202 | Rec 0.001056 | Seg 0.453543 | Elapsed 0.4m | ETA 3.9m
Epoch 122/500 | Batch 30/202 | Rec 0.001056 | Seg 0.441223 | Elapsed 0.7m | ETA 3.7m
Epoch 122/500 | Batch 40/202 | Rec 0.001119 | Seg 0.445302 | Elapsed 0.9m | ETA 3.5m
Epoch 122/500 | Batch 50/202 | Rec 0.001136 | Seg 0.457858 | Elapsed 1.1m | ETA 3.3m
Epoch 122/500 | Batch 60/202 | Rec 0.001097 | Seg 0.450334 | Elapsed 1.3m | ETA 3.1m
Epoch 122/500 | Batch 70/202 | Rec 0.001119 | Seg 0.448867 | Elapsed 1.5m | ETA 2.8m
Epoch 122/500 | Batch 80/202 | Rec 0.001124 | Seg 0.457678 | Elapsed 1.7m | ETA 2.6m
Epoch 122/500 | Batch 90/202 | Rec 0.001145 | Seg 0.473243 | Elapsed 1.9m | ETA 2.4m
Epoch 122/500 | Batch 100/202 | Rec 0.001145 | Seg 0.475074 | Elapsed 2.2m | ETA 2.2m
Epoch 122/500 | Batch 110/202 | Rec 0.001136 | Seg 0.468684 | Elapsed 2.4m | ETA 2.0m
Epoch 122/500 | Batch 120/202 | Rec 0.001141 | Seg 0.468366 | Elapsed 2.6m | ETA 1.8m
Epoch 122/500 | Batch 130/202 | Rec 0.001137 | Seg 0.467435 | Elapsed 2.8m | ETA 1.5m
Epoch 122/500 | Batch 140/202 | Rec 0.001148 | Seg 0.469722 | Elapsed 3.0m | ETA 1.3m
Epoch 122/500 | Batch 150/202 | Rec 0.001133 | Seg 0.458162 | Elapsed 3.2m | ETA 1.1m
Epoch 122/500 | Batch 160/202 | Rec 0.001139 | Seg 0.460145 | Elapsed 3.4m | ETA 0.9m
Epoch 122/500 | Batch 170/202 | Rec 0.001178 | Seg 0.462303 | Elapsed 3.6m | ETA 0.7m
Epoch 122/500 | Batch 180/202 | Rec 0.001175 | Seg 0.460307 | Elapsed 3.9m | ETA 0.5m
Epoch 122/500 | Batch 190/202 | Rec 0.001167 | Seg 0.458385 | Elapsed 4.1m | ETA 0.3m
Epoch 122/500 | Batch 200/202 | Rec 0.001156 | Seg 0.459195 | Elapsed 4.3m | ETA 0.0m
Epoch 122/500 | Batch 202/202 | Rec 0.001157 | Seg 0.456901 | Elapsed 4.3m | ETA 0.0m

2026-09-22 15:43:57,220 - INFO: Rec loss: 0.001157462842979164
2026-09-22 15:43:57,221 - INFO: Seg loss: 0.45690119723872386
2026-09-22 15:43:57,221 - INFO: λ_rec: 1
2026-09-22 15:43:57,221 - INFO: λ_seg: 0.0001
2026-09-22 15:45:13,468 - INFO: -------------------Epoch: 122------------------------
2026-09-22 15:45:13,472 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.125105  0.968209  0.000253
2026-09-22 15:45:13,479 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994523  0.997204  0.995370  0.999145  0.994761
real potato   0.305878  0.468427  0.999583  0.305917  0.999169
fake potato   0.546292  0.706538  1.000000  0.546292  0.999669
real apple    0.582441  0.736080  0.693294  0.784609  0.998059
fake apple    0.706202  0.827757  0.956160  0.729833  0.998854
real orange   0.439416  0.610502  0.895456  0.463177  0.999221
fake orange   0.642673  0.782424  0.662019  0.956508  0.998477
real grape    0.323647  0.488979  0.732216  0.367098  0.998398
fake grape    0.773785  0.872417  0.892315  0.853483  0.999077
real lemon    0.329596  0.495735  0.428693  0.587769  0.998595
fake lemon    0.794425  0.885387  0.943027  0.834475  0.999543
real avocado  0.824543  0.903785  0.911917  0.895895  0.999823
fake avocado  0.402071  0.573497  0.976388  0.406019  0.999277
real pepper   0.733210  0.846022  0.866495  0.826589  0.998900
fake pepper   0.542060  0.702988  0.991722  0.544523  0.998904
real plant    0.764093  0.866223  0.841234  0.892848  0.997243
fake plant    0.778841  0.875623  0.930343  0.827071  0.999813
real banana   0.272440  0.428182  0.964992  0.275160  0.998349
fake banana   0.602198  0.751665  0.720158  0.786165  0.999045
real onion    0.461268  0.631278  0.776244  0.532005  0.999439
fake onion    0.950084  0.974353  0.996964  0.952842  0.999968
real unknown  0.572609  0.728180  0.600247  0.925572  0.999890
fake unknown  0.182309  0.308355  0.210680  0.575154  0.997826
total         0.588026  0.715722  0.825457  0.689920  0.998796
total(-bg)    0.569549  0.702927  0.817734  0.675864  0.998979
2026-09-22 15:45:14,022 - INFO: Epoch accounting: {'epoch': 122, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11305658, 65931, 67809, 111652, 127514, 79569, 57234, 162452, 182474, 59506, 37279, 48186, 35206, 227632, 88566, 148275, 23356, 116117, 74870, 92441, 58853, 12833, 54859], 'crops_with_class': [202, 39, 35, 32, 32, 23, 21, 33, 33, 26, 17, 18, 13, 56, 28, 22, 23, 33, 32, 39, 29, 13, 26], 'targeted_crops_by_class': [0, 4, 7, 5, 3, 2, 3, 6, 7, 2, 4, 5, 5, 8, 4, 5, 5, 6, 4, 3, 2, 9, 4], 'sampled_scene_counts': [1, 1, 2, 1, 2, 1, 1, 0, 3, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 2, 2, 1, 1, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 2, 1, 0, 0, 0, 1, 1, 2, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 2, 0, 3, 0, 3, 0, 0, 0, 0, 0, 1, 0, 2, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 1, 3, 2, 1, 3, 0, 1, 3, 2, 2, 1, 1, 2, 3, 3, 2, 3, 3, 2, 2, 1, 3, 1, 0, 2, 3, 2, 1, 1, 3, 2, 1, 2, 2, 1, 2, 1, 0, 2, 2, 3, 3, 1, 1, 2, 1, 2, 3, 1, 1, 0, 1, 1, 1, 2, 1, 0, 2], 'learning_rate': 8.626707486807892e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001157462842979164, 'train_segmentation_loss': 0.45690119723872386, 'val_foreground_miou_all22': 0.5695491106327877, 'val_psnr_ref1': 36.125105438232424, 'elapsed_seconds': 337.547078371048, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 123/500 | Batch 10/202 | Rec 0.001050 | Seg 0.438161 | Elapsed 0.2m | ETA 4.3m
Epoch 123/500 | Batch 20/202 | Rec 0.001051 | Seg 0.459521 | Elapsed 0.4m | ETA 3.9m
Epoch 123/500 | Batch 30/202 | Rec 0.001065 | Seg 0.457936 | Elapsed 0.6m | ETA 3.7m
Epoch 123/500 | Batch 40/202 | Rec 0.001058 | Seg 0.450494 | Elapsed 0.9m | ETA 3.5m
Epoch 123/500 | Batch 50/202 | Rec 0.001049 | Seg 0.451026 | Elapsed 1.1m | ETA 3.3m
Epoch 123/500 | Batch 60/202 | Rec 0.001053 | Seg 0.459171 | Elapsed 1.3m | ETA 3.1m
Epoch 123/500 | Batch 70/202 | Rec 0.001060 | Seg 0.450492 | Elapsed 1.5m | ETA 2.8m
Epoch 123/500 | Batch 80/202 | Rec 0.001057 | Seg 0.443397 | Elapsed 1.7m | ETA 2.6m
Epoch 123/500 | Batch 90/202 | Rec 0.001108 | Seg 0.452894 | Elapsed 1.9m | ETA 2.4m
Epoch 123/500 | Batch 100/202 | Rec 0.001111 | Seg 0.455047 | Elapsed 2.2m | ETA 2.2m
Epoch 123/500 | Batch 110/202 | Rec 0.001127 | Seg 0.449839 | Elapsed 2.4m | ETA 2.0m
Epoch 123/500 | Batch 120/202 | Rec 0.001152 | Seg 0.453909 | Elapsed 2.6m | ETA 1.8m
Epoch 123/500 | Batch 130/202 | Rec 0.001138 | Seg 0.449720 | Elapsed 2.8m | ETA 1.6m
Epoch 123/500 | Batch 140/202 | Rec 0.001122 | Seg 0.449572 | Elapsed 3.0m | ETA 1.3m
Epoch 123/500 | Batch 150/202 | Rec 0.001120 | Seg 0.445673 | Elapsed 3.3m | ETA 1.1m
Epoch 123/500 | Batch 160/202 | Rec 0.001137 | Seg 0.446339 | Elapsed 3.5m | ETA 0.9m
Epoch 123/500 | Batch 170/202 | Rec 0.001129 | Seg 0.449261 | Elapsed 3.7m | ETA 0.7m
Epoch 123/500 | Batch 180/202 | Rec 0.001125 | Seg 0.447320 | Elapsed 3.9m | ETA 0.5m
Epoch 123/500 | Batch 190/202 | Rec 0.001132 | Seg 0.453140 | Elapsed 4.1m | ETA 0.3m
Epoch 123/500 | Batch 200/202 | Rec 0.001128 | Seg 0.447506 | Elapsed 4.3m | ETA 0.0m
Epoch 123/500 | Batch 202/202 | Rec 0.001127 | Seg 0.448606 | Elapsed 4.4m | ETA 0.0m

2026-09-22 15:49:35,619 - INFO: Rec loss: 0.001127060773778974
2026-09-22 15:49:35,619 - INFO: Seg loss: 0.4486063402330521
2026-09-22 15:49:35,619 - INFO: λ_rec: 1
2026-09-22 15:49:35,619 - INFO: λ_seg: 0.0001
2026-09-22 15:50:52,161 - INFO: -------------------Epoch: 123------------------------
2026-09-22 15:50:52,166 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.521324  0.967415  0.000231
2026-09-22 15:50:52,173 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994624  0.997255  0.995699  0.998916  0.994860
real potato   0.885768  0.939374  0.981520  0.900791  0.999861
fake potato   0.930797  0.964108  0.964765  0.963553  0.999948
real apple    0.689361  0.816071  0.952606  0.713843  0.998890
fake apple    0.571800  0.727527  0.981007  0.578201  0.998365
real orange   0.464594  0.634389  0.958782  0.474062  0.999280
fake orange   0.655111  0.791573  0.673063  0.960878  0.998552
real grape    0.664618  0.798473  0.798903  0.798144  0.999159
fake grape    0.832112  0.908314  0.954306  0.866642  0.999353
real lemon    0.303964  0.466165  0.498228  0.438068  0.998821
fake lemon    0.771895  0.871215  0.994999  0.774901  0.999516
real avocado  0.820412  0.901297  0.880997  0.922660  0.999812
fake avocado  0.384086  0.554963  1.000000  0.384086  0.999263
real pepper   0.767018  0.868100  0.874339  0.862047  0.999042
fake pepper   0.697208  0.821546  0.987508  0.703412  0.999272
real plant    0.846545  0.916846  0.932584  0.901727  0.998365
fake plant    0.772206  0.871413  0.841729  0.903374  0.999788
real banana   0.414963  0.586493  0.948702  0.424487  0.998655
fake banana   0.480301  0.648876  0.532211  0.831204  0.998345
real onion    0.749137  0.856529  0.778069  0.952711  0.999712
fake onion    0.878301  0.935158  0.907045  0.965175  0.999916
real unknown  0.351124  0.519711  0.357143  0.954198  0.999718
fake unknown  0.146532  0.255567  0.179693  0.442593  0.997828
total         0.655325  0.767433  0.824952  0.770247  0.998970
total(-bg)    0.639902  0.756987  0.817191  0.759853  0.999157
2026-09-22 15:50:53,069 - INFO: Epoch accounting: {'epoch': 123, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11319290, 42262, 54103, 116242, 132487, 79351, 80837, 60370, 186681, 71944, 42487, 69010, 58678, 268064, 149249, 117181, 25913, 104439, 74355, 72519, 51004, 11231, 50575], 'crops_with_class': [202, 27, 25, 32, 40, 26, 28, 17, 31, 30, 21, 20, 24, 62, 37, 20, 24, 28, 32, 34, 25, 17, 22], 'targeted_crops_by_class': [0, 3, 3, 3, 5, 1, 4, 2, 3, 4, 4, 5, 6, 8, 5, 5, 7, 7, 1, 8, 3, 6, 8], 'sampled_scene_counts': [0, 1, 4, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2, 1, 0, 0, 1, 2, 0, 1, 1, 0, 3, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 3, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1, 2, 1, 2, 1, 0, 2, 2, 1, 2, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 4, 1, 2, 1, 3, 1, 0, 0, 1, 2, 1, 0, 0, 1, 0, 2, 1, 2, 2, 3, 2, 1, 2, 6, 1, 0, 2, 2, 2, 3, 0, 1, 1, 0, 1, 2, 5, 2, 2, 2, 2, 1, 1, 0, 3, 2, 2, 0, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 0, 2, 3, 1, 1, 2, 1, 3, 0, 2, 3, 1, 0, 2, 1, 2, 1, 4, 2, 1, 2], 'learning_rate': 8.605041261628431e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001127060773778974, 'train_segmentation_loss': 0.4486063402330521, 'val_foreground_miou_all22': 0.6399022656441243, 'val_psnr_ref1': 36.52132400512696, 'elapsed_seconds': 339.0381443500519, 'peak_cuda_allocated_gib': 7.5045623779296875}

Epoch 124/500 | Batch 10/202 | Rec 0.001398 | Seg 0.527966 | Elapsed 0.2m | ETA 4.3m
Epoch 124/500 | Batch 20/202 | Rec 0.001156 | Seg 0.448759 | Elapsed 0.4m | ETA 4.0m
Epoch 124/500 | Batch 30/202 | Rec 0.001116 | Seg 0.412321 | Elapsed 0.7m | ETA 3.8m
Epoch 124/500 | Batch 40/202 | Rec 0.001031 | Seg 0.383504 | Elapsed 0.9m | ETA 3.6m
Epoch 124/500 | Batch 50/202 | Rec 0.001095 | Seg 0.416538 | Elapsed 1.1m | ETA 3.3m
Epoch 124/500 | Batch 60/202 | Rec 0.001133 | Seg 0.442222 | Elapsed 1.3m | ETA 3.1m
Epoch 124/500 | Batch 70/202 | Rec 0.001116 | Seg 0.435923 | Elapsed 1.5m | ETA 2.9m
Epoch 124/500 | Batch 80/202 | Rec 0.001096 | Seg 0.430252 | Elapsed 1.7m | ETA 2.7m
Epoch 124/500 | Batch 90/202 | Rec 0.001099 | Seg 0.439492 | Elapsed 2.0m | ETA 2.4m
Epoch 124/500 | Batch 100/202 | Rec 0.001105 | Seg 0.438966 | Elapsed 2.2m | ETA 2.2m
Epoch 124/500 | Batch 110/202 | Rec 0.001092 | Seg 0.437429 | Elapsed 2.4m | ETA 2.0m
Epoch 124/500 | Batch 120/202 | Rec 0.001106 | Seg 0.447330 | Elapsed 2.6m | ETA 1.8m
Epoch 124/500 | Batch 130/202 | Rec 0.001104 | Seg 0.450695 | Elapsed 2.8m | ETA 1.6m
Epoch 124/500 | Batch 140/202 | Rec 0.001114 | Seg 0.446892 | Elapsed 3.0m | ETA 1.3m
Epoch 124/500 | Batch 150/202 | Rec 0.001099 | Seg 0.441519 | Elapsed 3.2m | ETA 1.1m
Epoch 124/500 | Batch 160/202 | Rec 0.001105 | Seg 0.445414 | Elapsed 3.5m | ETA 0.9m
Epoch 124/500 | Batch 170/202 | Rec 0.001103 | Seg 0.452861 | Elapsed 3.7m | ETA 0.7m
Epoch 124/500 | Batch 180/202 | Rec 0.001091 | Seg 0.449717 | Elapsed 3.9m | ETA 0.5m
Epoch 124/500 | Batch 190/202 | Rec 0.001098 | Seg 0.456949 | Elapsed 4.1m | ETA 0.3m
Epoch 124/500 | Batch 200/202 | Rec 0.001103 | Seg 0.457354 | Elapsed 4.3m | ETA 0.0m
Epoch 124/500 | Batch 202/202 | Rec 0.001101 | Seg 0.456988 | Elapsed 4.4m | ETA 0.0m

2026-09-22 15:55:15,355 - INFO: Rec loss: 0.0011011181111933923
2026-09-22 15:55:15,355 - INFO: Seg loss: 0.4569878514745448
2026-09-22 15:55:15,355 - INFO: λ_rec: 1
2026-09-22 15:55:15,355 - INFO: λ_seg: 0.0001
2026-09-22 15:56:31,844 - INFO: -------------------Epoch: 124------------------------
2026-09-22 15:56:31,848 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.972657  0.966138  0.000261
2026-09-22 15:56:31,855 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994259  0.997071  0.995291  0.998958  0.994509
real potato   0.879326  0.935739  0.985197  0.891099  0.999854
fake potato   0.878261  0.935135  0.939535  0.930876  0.999906
real apple    0.385222  0.556148  0.976884  0.388766  0.997859
fake apple    0.660145  0.795236  0.872191  0.730844  0.998579
real orange   0.474873  0.643907  1.000000  0.474873  0.999308
fake orange   0.757948  0.862261  0.780571  0.963170  0.999119
real grape    0.567275  0.723850  0.771828  0.681576  0.998914
fake grape    0.789794  0.882503  0.911368  0.855505  0.999158
real lemon    0.055072  0.104351  0.154080  0.078941  0.998408
fake lemon    0.753010  0.859056  0.999426  0.753336  0.999477
real avocado  0.492658  0.660063  0.966139  0.501314  0.999520
fake avocado  0.287823  0.446957  0.992541  0.288447  0.999146
real pepper   0.637680  0.778710  0.719351  0.848865  0.998236
fake pepper   0.806406  0.892780  0.945016  0.846105  0.999516
real plant    0.816620  0.899004  0.948307  0.854665  0.998080
fake plant    0.623498  0.768044  0.651744  0.935008  0.999551
real banana   0.231580  0.376036  0.866879  0.240120  0.998210
fake banana   0.396427  0.567729  0.431404  0.830209  0.997675
real onion    0.826597  0.905017  0.882277  0.929066  0.999824
fake onion    0.904110  0.949590  0.941736  0.957678  0.999936
real unknown  0.717430  0.835419  0.902547  0.777672  0.999951
fake unknown  0.085554  0.157590  0.099908  0.373234  0.996639
total         0.609633  0.718791  0.814531  0.701318  0.998755
total(-bg)    0.592150  0.706142  0.806315  0.687789  0.998948
2026-09-22 15:56:32,423 - INFO: Epoch accounting: {'epoch': 124, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11263671, 25663, 29550, 86850, 197586, 123754, 87777, 168400, 137857, 86956, 65031, 35092, 32630, 218838, 137050, 203504, 20293, 71740, 42273, 77499, 49516, 14466, 62276], 'crops_with_class': [202, 18, 15, 24, 47, 33, 29, 31, 28, 36, 27, 11, 15, 54, 32, 26, 20, 19, 21, 33, 20, 17, 27], 'targeted_crops_by_class': [0, 1, 4, 2, 7, 6, 10, 1, 6, 3, 5, 1, 3, 7, 3, 4, 3, 6, 1, 3, 5, 7, 6], 'sampled_scene_counts': [1, 1, 2, 0, 1, 2, 2, 1, 4, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 2, 0, 2, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 1, 0, 1, 1, 3, 1, 1, 1, 0, 0, 1, 4, 0, 3, 1, 0, 0, 0, 0, 2, 1, 1, 1, 2, 2, 5, 1, 3, 0, 1, 0, 0, 1, 1, 1, 1, 4, 0, 0, 0, 2, 3, 1, 0, 2, 1, 1, 0, 2, 0, 6, 3, 3, 2, 1, 1, 2, 1, 1, 1, 0, 2, 1, 1, 0, 2, 1, 1, 1, 0, 2, 1, 0, 0, 0, 1, 3, 0, 0, 1, 1, 0, 1, 3, 2, 1, 0, 1, 3, 0, 2, 2, 0], 'learning_rate': 8.583233209071379e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0011011181111933923, 'train_segmentation_loss': 0.4569878514745448, 'val_foreground_miou_all22': 0.5921503258996936, 'val_psnr_ref1': 35.97265655517578, 'elapsed_seconds': 339.3459165096283, 'peak_cuda_allocated_gib': 7.506137847900391}

Epoch 125/500 | Batch 10/202 | Rec 0.001073 | Seg 0.384550 | Elapsed 0.2m | ETA 4.3m
Epoch 125/500 | Batch 20/202 | Rec 0.001150 | Seg 0.441146 | Elapsed 0.4m | ETA 4.0m
Epoch 125/500 | Batch 30/202 | Rec 0.001254 | Seg 0.487448 | Elapsed 0.7m | ETA 3.8m
Epoch 125/500 | Batch 40/202 | Rec 0.001233 | Seg 0.492221 | Elapsed 0.9m | ETA 3.5m
Epoch 125/500 | Batch 50/202 | Rec 0.001159 | Seg 0.468579 | Elapsed 1.1m | ETA 3.3m
Epoch 125/500 | Batch 60/202 | Rec 0.001097 | Seg 0.456776 | Elapsed 1.3m | ETA 3.1m
Epoch 125/500 | Batch 70/202 | Rec 0.001099 | Seg 0.473203 | Elapsed 1.5m | ETA 2.8m
Epoch 125/500 | Batch 80/202 | Rec 0.001115 | Seg 0.488158 | Elapsed 1.7m | ETA 2.6m
Epoch 125/500 | Batch 90/202 | Rec 0.001121 | Seg 0.491080 | Elapsed 1.9m | ETA 2.4m
Epoch 125/500 | Batch 100/202 | Rec 0.001147 | Seg 0.490376 | Elapsed 2.1m | ETA 2.2m
Epoch 125/500 | Batch 110/202 | Rec 0.001157 | Seg 0.497916 | Elapsed 2.4m | ETA 2.0m
Epoch 125/500 | Batch 120/202 | Rec 0.001169 | Seg 0.501443 | Elapsed 2.6m | ETA 1.8m
Epoch 125/500 | Batch 130/202 | Rec 0.001157 | Seg 0.491516 | Elapsed 2.8m | ETA 1.6m
Epoch 125/500 | Batch 140/202 | Rec 0.001169 | Seg 0.484156 | Elapsed 3.0m | ETA 1.3m
Epoch 125/500 | Batch 150/202 | Rec 0.001169 | Seg 0.475182 | Elapsed 3.2m | ETA 1.1m
Epoch 125/500 | Batch 160/202 | Rec 0.001169 | Seg 0.473105 | Elapsed 3.5m | ETA 0.9m
Epoch 125/500 | Batch 170/202 | Rec 0.001141 | Seg 0.460225 | Elapsed 3.7m | ETA 0.7m
Epoch 125/500 | Batch 180/202 | Rec 0.001137 | Seg 0.459811 | Elapsed 3.9m | ETA 0.5m
Epoch 125/500 | Batch 190/202 | Rec 0.001141 | Seg 0.463523 | Elapsed 4.1m | ETA 0.3m
Epoch 125/500 | Batch 200/202 | Rec 0.001150 | Seg 0.470932 | Elapsed 4.3m | ETA 0.0m
Epoch 125/500 | Batch 202/202 | Rec 0.001148 | Seg 0.469468 | Elapsed 4.3m | ETA 0.0m

2026-09-22 16:00:53,219 - INFO: Rec loss: 0.001147668533076735
2026-09-22 16:00:53,219 - INFO: Seg loss: 0.46946757910127684
2026-09-22 16:00:53,219 - INFO: λ_rec: 1
2026-09-22 16:00:53,219 - INFO: λ_seg: 0.0001
2026-09-22 16:02:09,350 - INFO: -------------------Epoch: 125------------------------
2026-09-22 16:02:09,354 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.573602  0.967349  0.000229
2026-09-22 16:02:09,361 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994740  0.997313  0.995652  0.999080  0.994971
real potato   0.492927  0.660306  0.998709  0.493242  0.999393
fake potato   0.943633  0.970949  0.967165  0.974864  0.999958
real apple    0.723818  0.839735  0.850840  0.829014  0.998909
fake apple    0.604425  0.753400  0.951248  0.623747  0.998459
real orange   0.444970  0.615843  0.899844  0.468157  0.999230
fake orange   0.573589  0.728974  0.577428  0.988541  0.997896
real grape    0.264433  0.418228  0.895848  0.272820  0.998416
fake grape    0.798288  0.887781  0.902960  0.873201  0.999184
real lemon    0.092117  0.168649  0.238547  0.130486  0.998489
fake lemon    0.822700  0.902677  0.996689  0.824955  0.999624
real avocado  0.800708  0.889276  0.927286  0.854351  0.999802
fake avocado  0.375743  0.546200  0.978590  0.378857  0.999247
real pepper   0.687184  0.814543  0.850075  0.781954  0.998698
fake pepper   0.526575  0.689829  0.833318  0.588567  0.998739
real plant    0.759941  0.863549  0.850115  0.877517  0.997227
fake plant    0.636121  0.777546  0.779318  0.775882  0.999647
real banana   0.107432  0.193988  0.490228  0.120943  0.997742
fake banana   0.344648  0.512579  0.373493  0.816938  0.997142
real onion    0.647324  0.785860  0.795844  0.776220  0.999618
fake onion    0.742831  0.852393  0.755892  0.977267  0.999787
real unknown  0.742947  0.852468  0.806122  0.904580  0.999950
fake unknown  0.137683  0.241994  0.192608  0.325607  0.998282
total         0.576729  0.694090  0.778601  0.680730  0.998713
total(-bg)    0.557729  0.680307  0.768735  0.666259  0.998883
2026-09-22 16:02:10,079 - INFO: Epoch accounting: {'epoch': 125, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11251580, 51389, 72253, 118053, 117201, 71829, 57184, 107581, 209210, 90392, 93648, 52134, 58736, 219730, 159225, 129253, 27230, 101962, 55289, 65133, 55500, 13784, 59976], 'crops_with_class': [202, 34, 32, 27, 29, 19, 21, 23, 38, 42, 38, 18, 21, 56, 39, 18, 30, 27, 22, 32, 23, 15, 27], 'targeted_crops_by_class': [0, 6, 4, 3, 4, 0, 3, 5, 1, 10, 8, 5, 6, 8, 6, 5, 1, 4, 5, 6, 6, 4, 4], 'sampled_scene_counts': [2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0, 1, 2, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1, 0, 2, 1, 2, 3, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 2, 2, 0, 0, 0, 0, 1, 3, 2, 3, 1, 5, 2, 0, 2, 2, 3, 1, 2, 1, 2, 0, 0, 1, 1, 2, 0, 1, 0, 0, 1, 3, 2, 0, 1, 3, 3, 0, 1, 5, 2, 4, 3, 3, 4, 0, 2, 1, 4, 0, 1, 2, 1, 1, 2, 2, 1, 1, 0, 2, 0, 2, 1, 1, 2, 0, 1, 2, 2, 1, 0, 4, 3, 0, 1, 0, 0, 2, 0, 0, 1, 2], 'learning_rate': 8.561284190081308e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001147668533076735, 'train_segmentation_loss': 0.46946757910127684, 'val_foreground_miou_all22': 0.5577289674197261, 'val_psnr_ref1': 36.573602447509764, 'elapsed_seconds': 337.6485629081726, 'peak_cuda_allocated_gib': 7.507877349853516}

Epoch 126/500 | Batch 10/202 | Rec 0.001120 | Seg 0.435336 | Elapsed 0.2m | ETA 4.2m
Epoch 126/500 | Batch 20/202 | Rec 0.001316 | Seg 0.464195 | Elapsed 0.4m | ETA 4.0m
Epoch 126/500 | Batch 30/202 | Rec 0.001271 | Seg 0.476176 | Elapsed 0.7m | ETA 3.8m
Epoch 126/500 | Batch 40/202 | Rec 0.001228 | Seg 0.469841 | Elapsed 0.9m | ETA 3.5m
Epoch 126/500 | Batch 50/202 | Rec 0.001171 | Seg 0.453459 | Elapsed 1.1m | ETA 3.3m
Epoch 126/500 | Batch 60/202 | Rec 0.001174 | Seg 0.468587 | Elapsed 1.3m | ETA 3.1m
Epoch 126/500 | Batch 70/202 | Rec 0.001157 | Seg 0.474023 | Elapsed 1.5m | ETA 2.9m
Epoch 126/500 | Batch 80/202 | Rec 0.001196 | Seg 0.473289 | Elapsed 1.7m | ETA 2.6m
Epoch 126/500 | Batch 90/202 | Rec 0.001159 | Seg 0.455460 | Elapsed 2.0m | ETA 2.4m
Epoch 126/500 | Batch 100/202 | Rec 0.001153 | Seg 0.458229 | Elapsed 2.2m | ETA 2.2m
Epoch 126/500 | Batch 110/202 | Rec 0.001124 | Seg 0.450298 | Elapsed 2.4m | ETA 2.0m
Epoch 126/500 | Batch 120/202 | Rec 0.001110 | Seg 0.443397 | Elapsed 2.6m | ETA 1.8m
Epoch 126/500 | Batch 130/202 | Rec 0.001122 | Seg 0.445091 | Elapsed 2.8m | ETA 1.6m
Epoch 126/500 | Batch 140/202 | Rec 0.001118 | Seg 0.440019 | Elapsed 3.0m | ETA 1.3m
Epoch 126/500 | Batch 150/202 | Rec 0.001118 | Seg 0.438450 | Elapsed 3.3m | ETA 1.1m
Epoch 126/500 | Batch 160/202 | Rec 0.001108 | Seg 0.440285 | Elapsed 3.5m | ETA 0.9m
Epoch 126/500 | Batch 170/202 | Rec 0.001124 | Seg 0.441011 | Elapsed 3.7m | ETA 0.7m
Epoch 126/500 | Batch 180/202 | Rec 0.001117 | Seg 0.437222 | Elapsed 3.9m | ETA 0.5m
Epoch 126/500 | Batch 190/202 | Rec 0.001115 | Seg 0.444303 | Elapsed 4.1m | ETA 0.3m
Epoch 126/500 | Batch 200/202 | Rec 0.001103 | Seg 0.443076 | Elapsed 4.3m | ETA 0.0m
Epoch 126/500 | Batch 202/202 | Rec 0.001106 | Seg 0.442687 | Elapsed 4.4m | ETA 0.0m

2026-09-22 16:06:32,369 - INFO: Rec loss: 0.0011063218825625826
2026-09-22 16:06:32,369 - INFO: Seg loss: 0.44268677110719207
2026-09-22 16:06:32,369 - INFO: λ_rec: 1
2026-09-22 16:06:32,369 - INFO: λ_seg: 0.0001
2026-09-22 16:07:48,872 - INFO: -------------------Epoch: 126------------------------
2026-09-22 16:07:48,876 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.853405  0.968033  0.000216
2026-09-22 16:07:48,883 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994862  0.997374  0.996123  0.998730  0.995090
real potato   0.175976  0.299259  1.000000  0.175976  0.999014
fake potato   0.545227  0.705646  0.995044  0.546711  0.999668
real apple    0.599530  0.749583  0.733150  0.766873  0.998233
fake apple    0.694502  0.819663  0.892922  0.757598  0.998742
real orange   0.322796  0.488014  0.988693  0.323993  0.999104
fake orange   0.583075  0.736589  0.592318  0.973937  0.998006
real grape    0.209443  0.346317  0.945259  0.212015  0.998329
fake grape    0.762897  0.865454  0.812937  0.925339  0.998936
real lemon    0.180134  0.305231  0.408487  0.243703  0.998696
fake lemon    0.849091  0.918338  0.969389  0.872485  0.999672
real avocado  0.681939  0.810846  0.822962  0.799179  0.999654
fake avocado  0.318334  0.482892  0.832657  0.340092  0.999129
real pepper   0.690994  0.817214  0.866505  0.773319  0.998735
fake pepper   0.467105  0.636727  0.973397  0.473145  0.998713
real plant    0.778079  0.875141  0.850321  0.901559  0.997428
fake plant    0.788500  0.881695  0.864994  0.899156  0.999808
real banana   0.085542  0.157586  0.876891  0.086582  0.997920
fake banana   0.359640  0.528977  0.398913  0.785086  0.997428
real onion    0.675405  0.806209  0.782851  0.831110  0.999639
fake onion    0.951243  0.974962  0.997974  0.953083  0.999969
real unknown  0.662100  0.796655  0.676667  0.968511  0.999921
fake unknown  0.133677  0.235794  0.153644  0.507063  0.997231
total         0.543917  0.662442  0.801395  0.657184  0.998655
total(-bg)    0.523420  0.647218  0.792544  0.641660  0.998817
2026-09-22 16:07:49,580 - INFO: Epoch accounting: {'epoch': 126, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11292186, 38086, 48202, 149192, 166638, 79003, 61328, 144688, 245663, 56144, 60025, 40795, 29350, 231939, 114832, 91585, 26214, 98492, 66608, 76834, 45481, 17032, 57955], 'crops_with_class': [202, 24, 22, 37, 39, 25, 23, 32, 44, 27, 21, 13, 12, 61, 31, 19, 24, 26, 32, 34, 20, 19, 27], 'targeted_crops_by_class': [0, 2, 1, 8, 8, 2, 6, 3, 3, 1, 4, 5, 3, 6, 2, 3, 5, 9, 2, 5, 1, 7, 9], 'sampled_scene_counts': [0, 1, 0, 1, 2, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 0, 2, 0, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 3, 1, 0, 2, 2, 2, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2, 0, 0, 2, 2, 1, 2, 1, 1, 3, 1, 1, 0, 2, 1, 0, 2, 1, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 5, 1, 1, 2, 0, 2, 1, 1, 2, 2, 2, 0, 0, 4, 5, 2, 1, 2, 1, 1, 1, 1, 3, 3, 1, 2, 1, 1, 3, 2, 1, 1, 2, 2, 2, 0, 1, 1, 1, 0, 1, 0, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 0], 'learning_rate': 8.539195071167902e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0011063218825625826, 'train_segmentation_loss': 0.44268677110719207, 'val_foreground_miou_all22': 0.5234195779820077, 'val_psnr_ref1': 36.85340530395508, 'elapsed_seconds': 339.49261474609375, 'peak_cuda_allocated_gib': 7.510044097900391}

Epoch 127/500 | Batch 10/202 | Rec 0.001131 | Seg 0.411380 | Elapsed 0.2m | ETA 4.1m
Epoch 127/500 | Batch 20/202 | Rec 0.001110 | Seg 0.431286 | Elapsed 0.4m | ETA 3.9m
Epoch 127/500 | Batch 30/202 | Rec 0.001160 | Seg 0.455086 | Elapsed 0.6m | ETA 3.7m
Epoch 127/500 | Batch 40/202 | Rec 0.001081 | Seg 0.427380 | Elapsed 0.9m | ETA 3.5m
Epoch 127/500 | Batch 50/202 | Rec 0.001078 | Seg 0.436537 | Elapsed 1.1m | ETA 3.3m
Epoch 127/500 | Batch 60/202 | Rec 0.001066 | Seg 0.433318 | Elapsed 1.3m | ETA 3.1m
Epoch 127/500 | Batch 70/202 | Rec 0.001062 | Seg 0.426840 | Elapsed 1.5m | ETA 2.9m
Epoch 127/500 | Batch 80/202 | Rec 0.001037 | Seg 0.419266 | Elapsed 1.7m | ETA 2.7m
Epoch 127/500 | Batch 90/202 | Rec 0.001046 | Seg 0.425967 | Elapsed 2.0m | ETA 2.4m
Epoch 127/500 | Batch 100/202 | Rec 0.001065 | Seg 0.431789 | Elapsed 2.2m | ETA 2.2m
Epoch 127/500 | Batch 110/202 | Rec 0.001077 | Seg 0.445971 | Elapsed 2.4m | ETA 2.0m
Epoch 127/500 | Batch 120/202 | Rec 0.001096 | Seg 0.449167 | Elapsed 2.6m | ETA 1.8m
Epoch 127/500 | Batch 130/202 | Rec 0.001103 | Seg 0.452801 | Elapsed 2.8m | ETA 1.6m
Epoch 127/500 | Batch 140/202 | Rec 0.001092 | Seg 0.449367 | Elapsed 3.0m | ETA 1.3m
Epoch 127/500 | Batch 150/202 | Rec 0.001099 | Seg 0.446853 | Elapsed 3.2m | ETA 1.1m
Epoch 127/500 | Batch 160/202 | Rec 0.001096 | Seg 0.441212 | Elapsed 3.5m | ETA 0.9m
Epoch 127/500 | Batch 170/202 | Rec 0.001113 | Seg 0.445109 | Elapsed 3.7m | ETA 0.7m
Epoch 127/500 | Batch 180/202 | Rec 0.001108 | Seg 0.443502 | Elapsed 3.9m | ETA 0.5m
Epoch 127/500 | Batch 190/202 | Rec 0.001121 | Seg 0.450005 | Elapsed 4.1m | ETA 0.3m
Epoch 127/500 | Batch 200/202 | Rec 0.001119 | Seg 0.447381 | Elapsed 4.3m | ETA 0.0m
Epoch 127/500 | Batch 202/202 | Rec 0.001120 | Seg 0.447047 | Elapsed 4.4m | ETA 0.0m

2026-09-22 16:12:11,146 - INFO: Rec loss: 0.0011196509790307113
2026-09-22 16:12:11,146 - INFO: Seg loss: 0.44704679702178085
2026-09-22 16:12:11,146 - INFO: λ_rec: 1
2026-09-22 16:12:11,146 - INFO: λ_seg: 0.0001
2026-09-22 16:13:27,318 - INFO: -------------------Epoch: 127------------------------
2026-09-22 16:13:27,322 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.266374  0.965464  0.000244
2026-09-22 16:13:27,329 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994414  0.997149  0.995555  0.998849  0.994659
real potato   0.705224  0.827085  0.995514  0.707473  0.999646
fake potato   0.946232  0.972323  0.990654  0.954755  0.999960
real apple    0.547523  0.707565  0.951993  0.563069  0.998395
fake apple    0.672059  0.803821  0.896391  0.728661  0.998658
real orange   0.490355  0.657993  0.995077  0.491547  0.999327
fake orange   0.690095  0.816586  0.705572  0.969193  0.998754
real grape    0.541901  0.702850  0.695655  0.710297  0.998746
fake grape    0.753817  0.859580  0.815942  0.908262  0.998903
real lemon    0.229742  0.373594  0.449826  0.319527  0.998741
fake lemon    0.813216  0.896938  0.998938  0.813920  0.999604
real avocado  0.838185  0.911920  0.936343  0.888834  0.999841
fake avocado  0.253634  0.404606  1.000000  0.253634  0.999107
real pepper   0.704109  0.826316  0.845878  0.807734  0.998758
fake pepper   0.652527  0.789684  0.985634  0.658793  0.999164
real plant    0.843359  0.914974  0.920734  0.909385  0.998311
fake plant    0.650703  0.788346  0.678705  0.940376  0.999598
real banana   0.346088  0.514171  0.831462  0.372199  0.998420
fake banana   0.515646  0.680382  0.577359  0.828301  0.998569
real onion    0.758498  0.862616  0.862302  0.863030  0.999752
fake onion    0.941318  0.969722  0.994158  0.946554  0.999963
real unknown  0.598562  0.748828  0.616667  0.953244  0.999898
fake unknown  0.148642  0.258772  0.180259  0.458711  0.997786
total         0.636341  0.751558  0.822636  0.741146  0.998894
total(-bg)    0.620065  0.740394  0.814776  0.729432  0.999086
2026-09-22 16:13:27,871 - INFO: Epoch accounting: {'epoch': 127, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11252983, 52705, 67299, 145261, 134015, 70525, 78178, 121543, 219667, 68897, 34516, 42806, 55130, 233917, 104860, 153148, 19865, 104258, 63560, 92978, 69506, 11100, 41555], 'crops_with_class': [202, 31, 32, 37, 36, 23, 28, 29, 36, 28, 17, 14, 19, 56, 29, 19, 19, 28, 27, 38, 32, 13, 19], 'targeted_crops_by_class': [0, 5, 2, 8, 5, 2, 1, 4, 6, 7, 1, 6, 4, 6, 9, 2, 2, 6, 3, 2, 8, 6, 7], 'sampled_scene_counts': [1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 0, 2, 2, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 2, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 2, 1, 0, 2, 2, 2, 1, 3, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 2, 1, 0, 2, 1, 2, 3, 1, 2, 1, 1, 1, 0, 2, 2, 2, 2, 1, 0, 3, 1, 1, 1, 1, 1, 3, 1, 2, 5, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 2, 1, 3, 3, 2, 0, 1, 3, 3, 0, 1, 1, 0, 0, 1, 0, 3, 2, 2, 4, 1, 1, 1, 5, 1, 1, 2, 0, 2, 0, 2, 0, 4, 1, 3, 3, 1, 0, 1, 1, 1, 1, 3, 1, 0], 'learning_rate': 8.516966724371758e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0011196509790307113, 'train_segmentation_loss': 0.44704679702178085, 'val_foreground_miou_all22': 0.6200652627214263, 'val_psnr_ref1': 36.266373748779294, 'elapsed_seconds': 338.28225231170654, 'peak_cuda_allocated_gib': 7.503337860107422}

Epoch 128/500 | Batch 10/202 | Rec 0.001038 | Seg 0.449607 | Elapsed 0.2m | ETA 4.1m
Epoch 128/500 | Batch 20/202 | Rec 0.001135 | Seg 0.466817 | Elapsed 0.4m | ETA 3.9m
Epoch 128/500 | Batch 30/202 | Rec 0.001052 | Seg 0.431241 | Elapsed 0.6m | ETA 3.7m
Epoch 128/500 | Batch 40/202 | Rec 0.001000 | Seg 0.424925 | Elapsed 0.9m | ETA 3.5m
Epoch 128/500 | Batch 50/202 | Rec 0.001024 | Seg 0.443222 | Elapsed 1.1m | ETA 3.3m
Epoch 128/500 | Batch 60/202 | Rec 0.001063 | Seg 0.449034 | Elapsed 1.3m | ETA 3.0m
Epoch 128/500 | Batch 70/202 | Rec 0.001058 | Seg 0.446102 | Elapsed 1.5m | ETA 2.8m
Epoch 128/500 | Batch 80/202 | Rec 0.001065 | Seg 0.451530 | Elapsed 1.7m | ETA 2.6m
Epoch 128/500 | Batch 90/202 | Rec 0.001059 | Seg 0.450161 | Elapsed 1.9m | ETA 2.4m
Epoch 128/500 | Batch 100/202 | Rec 0.001060 | Seg 0.456507 | Elapsed 2.2m | ETA 2.2m
Epoch 128/500 | Batch 110/202 | Rec 0.001090 | Seg 0.452665 | Elapsed 2.4m | ETA 2.0m
Epoch 128/500 | Batch 120/202 | Rec 0.001096 | Seg 0.452730 | Elapsed 2.6m | ETA 1.8m
Epoch 128/500 | Batch 130/202 | Rec 0.001096 | Seg 0.449432 | Elapsed 2.8m | ETA 1.6m
Epoch 128/500 | Batch 140/202 | Rec 0.001124 | Seg 0.457276 | Elapsed 3.0m | ETA 1.3m
Epoch 128/500 | Batch 150/202 | Rec 0.001125 | Seg 0.454664 | Elapsed 3.2m | ETA 1.1m
Epoch 128/500 | Batch 160/202 | Rec 0.001129 | Seg 0.451093 | Elapsed 3.5m | ETA 0.9m
Epoch 128/500 | Batch 170/202 | Rec 0.001128 | Seg 0.454315 | Elapsed 3.7m | ETA 0.7m
Epoch 128/500 | Batch 180/202 | Rec 0.001125 | Seg 0.451313 | Elapsed 3.9m | ETA 0.5m
Epoch 128/500 | Batch 190/202 | Rec 0.001118 | Seg 0.449390 | Elapsed 4.1m | ETA 0.3m
Epoch 128/500 | Batch 200/202 | Rec 0.001113 | Seg 0.444398 | Elapsed 4.3m | ETA 0.0m
Epoch 128/500 | Batch 202/202 | Rec 0.001122 | Seg 0.447112 | Elapsed 4.3m | ETA 0.0m

2026-09-22 16:17:48,850 - INFO: Rec loss: 0.0011223994401781496
2026-09-22 16:17:48,850 - INFO: Seg loss: 0.44711222138145185
2026-09-22 16:17:48,850 - INFO: λ_rec: 1
2026-09-22 16:17:48,851 - INFO: λ_seg: 0.0001
2026-09-22 16:19:04,998 - INFO: -------------------Epoch: 128------------------------
2026-09-22 16:19:05,002 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.482157  0.967862  0.000242
2026-09-22 16:19:05,010 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995077  0.997483  0.996236  0.998833  0.995296
real potato   0.583016  0.736542  0.994794  0.584800  0.999500
fake potato   0.939898  0.968968  0.968410  0.969627  0.999955
real apple    0.647276  0.785824  0.764883  0.808050  0.998481
fake apple    0.582831  0.736394  0.979796  0.589921  0.998406
real orange   0.428301  0.599689  0.823030  0.471746  0.999170
fake orange   0.626122  0.770033  0.633753  0.981132  0.998323
real grape    0.517540  0.682030  0.836572  0.575751  0.998879
fake grape    0.859381  0.924323  0.947075  0.902735  0.999454
real lemon    0.383739  0.554592  0.485297  0.647105  0.998779
fake lemon    0.835032  0.910051  0.948463  0.874721  0.999634
real avocado  0.836041  0.910650  0.908764  0.912644  0.999834
fake avocado  0.750858  0.857654  0.995786  0.753252  0.999701
real pepper   0.701302  0.824380  0.813238  0.835934  0.998698
fake pepper   0.531798  0.694299  0.968385  0.541195  0.998864
real plant    0.805499  0.892223  0.897026  0.887570  0.997856
fake plant    0.816039  0.898652  0.908023  0.889571  0.999840
real banana   0.399660  0.571039  0.915107  0.415048  0.998599
fake banana   0.571162  0.727008  0.628392  0.862475  0.998809
real onion    0.555841  0.714473  0.840878  0.621179  0.999552
fake onion    0.945613  0.971996  0.999489  0.946070  0.999966
real unknown  0.601621  0.751218  0.604773  0.991412  0.999895
fake unknown  0.173539  0.295710  0.216352  0.467222  0.998125
total         0.655965  0.772836  0.829327  0.762087  0.998940
total(-bg)    0.640550  0.762625  0.821740  0.751325  0.999105
2026-09-22 16:19:05,760 - INFO: Epoch accounting: {'epoch': 128, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11248564, 42119, 46905, 180828, 101654, 122503, 64093, 144896, 177646, 94857, 87581, 34064, 30298, 218058, 124078, 147716, 23497, 89992, 69148, 64550, 50413, 16379, 58433], 'crops_with_class': [202, 29, 23, 40, 30, 35, 24, 32, 31, 40, 39, 13, 12, 59, 33, 24, 24, 26, 31, 34, 21, 17, 25], 'targeted_crops_by_class': [0, 3, 2, 6, 7, 8, 3, 3, 4, 6, 8, 2, 3, 3, 4, 7, 4, 6, 4, 3, 2, 9, 4], 'sampled_scene_counts': [1, 1, 2, 0, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 0, 1, 0, 2, 1, 0, 0, 1, 1, 1, 0, 3, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 2, 2, 0, 2, 0, 0, 0, 0, 2, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2, 1, 1, 3, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1, 3, 3, 3, 0, 2, 1, 1, 0, 1, 1, 0, 2, 2, 2, 1, 1, 0, 1, 1, 1, 4, 1, 0, 3, 1, 0, 0, 4, 1, 1, 1, 3, 8, 3, 3, 2, 1, 1, 1, 1, 3, 1, 0, 2, 2, 1, 3, 1, 2, 0, 0, 1, 1, 0, 1, 1, 2, 1, 1, 2, 2, 1, 3, 2, 1, 0, 0, 0, 0, 1, 4, 1, 1, 1], 'learning_rate': 8.494600027229942e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0011223994401781496, 'train_segmentation_loss': 0.44711222138145185, 'val_foreground_miou_all22': 0.6405504134118066, 'val_psnr_ref1': 36.48215728759766, 'elapsed_seconds': 337.8815338611603, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 129/500 | Batch 10/202 | Rec 0.001072 | Seg 0.350369 | Elapsed 0.2m | ETA 4.1m
Epoch 129/500 | Batch 20/202 | Rec 0.001092 | Seg 0.378100 | Elapsed 0.4m | ETA 4.0m
Epoch 129/500 | Batch 30/202 | Rec 0.001099 | Seg 0.415198 | Elapsed 0.7m | ETA 3.8m
Epoch 129/500 | Batch 40/202 | Rec 0.001095 | Seg 0.418509 | Elapsed 0.9m | ETA 3.5m
Epoch 129/500 | Batch 50/202 | Rec 0.001039 | Seg 0.393382 | Elapsed 1.1m | ETA 3.3m
Epoch 129/500 | Batch 60/202 | Rec 0.001090 | Seg 0.414329 | Elapsed 1.3m | ETA 3.1m
Epoch 129/500 | Batch 70/202 | Rec 0.001110 | Seg 0.428307 | Elapsed 1.5m | ETA 2.9m
Epoch 129/500 | Batch 80/202 | Rec 0.001091 | Seg 0.430963 | Elapsed 1.7m | ETA 2.6m
Epoch 129/500 | Batch 90/202 | Rec 0.001079 | Seg 0.423165 | Elapsed 2.0m | ETA 2.4m
Epoch 129/500 | Batch 100/202 | Rec 0.001064 | Seg 0.417316 | Elapsed 2.2m | ETA 2.2m
Epoch 129/500 | Batch 110/202 | Rec 0.001050 | Seg 0.417386 | Elapsed 2.4m | ETA 2.0m
Epoch 129/500 | Batch 120/202 | Rec 0.001050 | Seg 0.423074 | Elapsed 2.6m | ETA 1.8m
Epoch 129/500 | Batch 130/202 | Rec 0.001051 | Seg 0.422086 | Elapsed 2.8m | ETA 1.6m
Epoch 129/500 | Batch 140/202 | Rec 0.001058 | Seg 0.425113 | Elapsed 3.0m | ETA 1.3m
Epoch 129/500 | Batch 150/202 | Rec 0.001061 | Seg 0.430439 | Elapsed 3.2m | ETA 1.1m
Epoch 129/500 | Batch 160/202 | Rec 0.001077 | Seg 0.435206 | Elapsed 3.5m | ETA 0.9m
Epoch 129/500 | Batch 170/202 | Rec 0.001082 | Seg 0.435778 | Elapsed 3.7m | ETA 0.7m
Epoch 129/500 | Batch 180/202 | Rec 0.001080 | Seg 0.435860 | Elapsed 3.9m | ETA 0.5m
Epoch 129/500 | Batch 190/202 | Rec 0.001088 | Seg 0.441855 | Elapsed 4.1m | ETA 0.3m
Epoch 129/500 | Batch 200/202 | Rec 0.001084 | Seg 0.440164 | Elapsed 4.3m | ETA 0.0m
Epoch 129/500 | Batch 202/202 | Rec 0.001083 | Seg 0.438422 | Elapsed 4.4m | ETA 0.0m

2026-09-22 16:23:28,315 - INFO: Rec loss: 0.001082503655233817
2026-09-22 16:23:28,315 - INFO: Seg loss: 0.43842212099692607
2026-09-22 16:23:28,315 - INFO: λ_rec: 1
2026-09-22 16:23:28,315 - INFO: λ_seg: 0.0001
2026-09-22 16:24:44,941 - INFO: -------------------Epoch: 129------------------------
2026-09-22 16:24:44,945 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.036741  0.968728  0.000207
2026-09-22 16:24:44,953 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995518  0.997704  0.997123  0.998386  0.995721
real potato   0.166114  0.284878  0.998467  0.166157  0.999002
fake potato   0.370471  0.540608  0.999435  0.370549  0.999541
real apple    0.622745  0.767471  0.679031  0.882530  0.998156
fake apple    0.697804  0.821959  0.961411  0.717911  0.998826
real orange   0.516837  0.681421  0.949710  0.531380  0.999345
fake orange   0.746806  0.855004  0.757497  0.981452  0.999047
real grape    0.538285  0.699804  0.918845  0.565154  0.998988
fake grape    0.820295  0.901227  0.898598  0.903972  0.999267
real lemon    0.311811  0.475342  0.399206  0.587510  0.998476
fake lemon    0.833567  0.909180  0.968913  0.856473  0.999638
real avocado  0.755950  0.860965  0.841511  0.881445  0.999736
fake avocado  0.243801  0.391990  0.867249  0.253252  0.999060
real pepper   0.717909  0.835744  0.803985  0.870224  0.998749
fake pepper   0.650488  0.788189  0.994345  0.652903  0.999164
real plant    0.833118  0.908913  0.874368  0.946409  0.998104
fake plant    0.833059  0.908878  0.948520  0.872508  0.999861
real banana   0.187226  0.315373  0.970259  0.188306  0.998163
fake banana   0.548952  0.708755  0.633972  0.803666  0.998785
real onion    0.512674  0.677790  0.820845  0.577267  0.999504
fake onion    0.938091  0.968007  0.976149  0.960097  0.999960
real unknown  0.631995  0.774458  0.635474  0.991412  0.999908
fake unknown  0.179976  0.305017  0.191610  0.747736  0.997129
total         0.593630  0.712116  0.829849  0.708987  0.998875
total(-bg)    0.575362  0.699135  0.822246  0.695832  0.999019
2026-09-22 16:24:45,722 - INFO: Epoch accounting: {'epoch': 129, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11284273, 48747, 59074, 109283, 184546, 79486, 65956, 153679, 208787, 107993, 90639, 29411, 30767, 201533, 112985, 136811, 25983, 74703, 64781, 60729, 31958, 14137, 62011], 'crops_with_class': [202, 26, 25, 31, 43, 26, 23, 33, 34, 44, 39, 11, 12, 50, 28, 19, 24, 21, 28, 30, 19, 16, 25], 'targeted_crops_by_class': [0, 3, 6, 4, 7, 6, 5, 4, 3, 9, 2, 3, 4, 5, 6, 1, 4, 2, 3, 2, 6, 8, 6], 'sampled_scene_counts': [0, 1, 2, 1, 0, 0, 1, 2, 0, 2, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 2, 1, 3, 0, 0, 1, 2, 0, 1, 0, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 3, 2, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 2, 0, 2, 1, 1, 3, 1, 1, 2, 0, 1, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 3, 0, 1, 1, 2, 2, 2, 0, 2, 5, 3, 1, 1, 1, 5, 1, 5, 4, 1, 1, 0, 1, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 2, 1, 0, 2, 4, 1, 1, 2, 2, 1, 1, 0, 3, 0, 1, 2, 2, 2], 'learning_rate': 8.472095862741362e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001082503655233817, 'train_segmentation_loss': 0.43842212099692607, 'val_foreground_miou_all22': 0.5753624679931021, 'val_psnr_ref1': 37.036741485595705, 'elapsed_seconds': 339.95433831214905, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 130/500 | Batch 10/202 | Rec 0.001070 | Seg 0.442459 | Elapsed 0.2m | ETA 4.2m
Epoch 130/500 | Batch 20/202 | Rec 0.001094 | Seg 0.419245 | Elapsed 0.4m | ETA 4.0m
Epoch 130/500 | Batch 30/202 | Rec 0.001090 | Seg 0.436388 | Elapsed 0.6m | ETA 3.7m
Epoch 130/500 | Batch 40/202 | Rec 0.001099 | Seg 0.425258 | Elapsed 0.9m | ETA 3.6m
Epoch 130/500 | Batch 50/202 | Rec 0.001175 | Seg 0.450199 | Elapsed 1.1m | ETA 3.3m
Epoch 130/500 | Batch 60/202 | Rec 0.001162 | Seg 0.445230 | Elapsed 1.3m | ETA 3.1m
Epoch 130/500 | Batch 70/202 | Rec 0.001124 | Seg 0.438889 | Elapsed 1.5m | ETA 2.9m
Epoch 130/500 | Batch 80/202 | Rec 0.001107 | Seg 0.440037 | Elapsed 1.7m | ETA 2.6m
Epoch 130/500 | Batch 90/202 | Rec 0.001100 | Seg 0.452251 | Elapsed 1.9m | ETA 2.4m
Epoch 130/500 | Batch 100/202 | Rec 0.001135 | Seg 0.459386 | Elapsed 2.2m | ETA 2.2m
Epoch 130/500 | Batch 110/202 | Rec 0.001124 | Seg 0.456621 | Elapsed 2.4m | ETA 2.0m
Epoch 130/500 | Batch 120/202 | Rec 0.001098 | Seg 0.446433 | Elapsed 2.6m | ETA 1.8m
Epoch 130/500 | Batch 130/202 | Rec 0.001077 | Seg 0.441996 | Elapsed 2.8m | ETA 1.6m
Epoch 130/500 | Batch 140/202 | Rec 0.001079 | Seg 0.443125 | Elapsed 3.0m | ETA 1.3m
Epoch 130/500 | Batch 150/202 | Rec 0.001077 | Seg 0.438120 | Elapsed 3.2m | ETA 1.1m
Epoch 130/500 | Batch 160/202 | Rec 0.001081 | Seg 0.441197 | Elapsed 3.4m | ETA 0.9m
Epoch 130/500 | Batch 170/202 | Rec 0.001088 | Seg 0.444812 | Elapsed 3.7m | ETA 0.7m
Epoch 130/500 | Batch 180/202 | Rec 0.001086 | Seg 0.442924 | Elapsed 3.9m | ETA 0.5m
Epoch 130/500 | Batch 190/202 | Rec 0.001063 | Seg 0.433635 | Elapsed 4.1m | ETA 0.3m
Epoch 130/500 | Batch 200/202 | Rec 0.001057 | Seg 0.428331 | Elapsed 4.3m | ETA 0.0m
Epoch 130/500 | Batch 202/202 | Rec 0.001058 | Seg 0.429290 | Elapsed 4.3m | ETA 0.0m

2026-09-22 16:29:06,288 - INFO: Rec loss: 0.0010577139816659567
2026-09-22 16:29:06,289 - INFO: Seg loss: 0.4292896730769979
2026-09-22 16:29:06,289 - INFO: λ_rec: 1
2026-09-22 16:29:06,289 - INFO: λ_seg: 0.0001
2026-09-22 16:30:22,175 - INFO: -------------------Epoch: 130------------------------
2026-09-22 16:30:22,180 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.643479  0.967475  0.000225
2026-09-22 16:30:22,187 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994424  0.997154  0.995689  0.998724  0.994668
real potato   0.508479  0.674116  0.999749  0.508544  0.999412
fake potato   0.368069  0.538046  0.997165  0.368454  0.999539
real apple    0.611204  0.758643  0.794779  0.725741  0.998407
fake apple    0.737740  0.849030  0.963857  0.758729  0.998982
real orange   0.443377  0.614318  1.000000  0.443377  0.999267
fake orange   0.725010  0.840537  0.742362  0.968767  0.998948
real grape    0.070095  0.130983  0.485701  0.075714  0.997903
fake grape    0.710870  0.830954  0.801072  0.863259  0.998701
real lemon    0.085792  0.157980  0.219428  0.123474  0.998454
fake lemon    0.803040  0.890713  0.998567  0.803967  0.999583
real avocado  0.698345  0.822335  0.996959  0.699836  0.999719
fake avocado  0.203675  0.338387  0.743401  0.219077  0.998975
real pepper   0.701608  0.824592  0.970306  0.717003  0.998885
fake pepper   0.752700  0.858854  0.961237  0.776263  0.999392
real plant    0.751775  0.858251  0.792914  0.935441  0.996911
fake plant    0.783981  0.878862  0.834051  0.928873  0.999796
real banana   0.200965  0.334644  0.939812  0.203585  0.998181
fake banana   0.446127  0.616949  0.494135  0.821168  0.998125
real onion    0.629205  0.772358  0.805092  0.742273  0.999605
fake onion    0.868987  0.929852  0.999444  0.869407  0.999917
real unknown  0.546644  0.706830  0.575105  0.916985  0.999878
fake unknown  0.115510  0.207067  0.127793  0.545817  0.996478
total         0.554679  0.670933  0.792983  0.652803  0.998684
total(-bg)    0.534691  0.656105  0.783769  0.637080  0.998866
2026-09-22 16:30:22,763 - INFO: Epoch accounting: {'epoch': 130, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11332284, 44907, 51844, 118995, 159667, 47928, 76633, 105072, 190097, 68144, 51061, 34386, 37978, 239798, 140342, 128882, 15302, 117152, 65418, 77027, 64471, 11344, 59540], 'crops_with_class': [202, 28, 23, 33, 37, 21, 27, 20, 35, 28, 24, 11, 16, 58, 37, 18, 17, 30, 27, 32, 28, 15, 24], 'targeted_crops_by_class': [0, 6, 3, 1, 5, 5, 5, 2, 7, 4, 4, 5, 5, 5, 5, 3, 1, 7, 4, 6, 8, 6, 7], 'sampled_scene_counts': [1, 0, 1, 0, 0, 2, 2, 0, 2, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 2, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0, 1, 2, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 0, 0, 3, 1, 0, 0, 2, 1, 0, 1, 2, 0, 4, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 2, 2, 1, 4, 4, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 0, 0, 6, 1, 1, 3, 1, 1, 2, 1, 1, 2, 2, 3, 2, 1, 1, 3, 6, 1, 0, 0, 1, 2, 0, 2, 2, 1, 1, 3, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 3, 2, 1, 1], 'learning_rate': 8.449455119331898e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010577139816659567, 'train_segmentation_loss': 0.4292896730769979, 'val_foreground_miou_all22': 0.534690742863078, 'val_psnr_ref1': 36.64347900390625, 'elapsed_seconds': 337.032648563385, 'peak_cuda_allocated_gib': 7.504184722900391}

Stopped after epoch 130; scheduler horizon remains 500
Archive: /kaggle/working/balanced_to_epoch130_20260922_143402.zip Missing checkpoint files: []
Saved epoch: 130 Best metrics: {'iou': 0.6405504134118066, 'psnr': 37.036741485595705}

/kaggle/working/balanced_to_epoch130_20260922_143402.zip

Download the complete ZIP before ending the session. A partial run can also produce an archive.

In [3]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((OUT / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(111,131)), 'Not all20 epochs completed.'
print('Final:', json.dumps(records[-1], indent=2))
for start in [111,121]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] < start+10]
    print(f'Epochs{start}-{start+9}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('New optimizer updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

Final: {
  "epoch": 130,
  "scheduler_horizon": 500,
  "lambda_rec": 1,
  "lambda_seg": 0.0001,
  "sampling_policy": "balanced50_v1",
  "class_pixels_seen": [
    11332284,
    44907,
    51844,
    118995,
    159667,
    47928,
    76633,
    105072,
    190097,
    68144,
    51061,
    34386,
    37978,
    239798,
    140342,
    128882,
    15302,
    117152,
    65418,
    77027,
    64471,
    11344,
    59540
  ],
  "crops_with_class": [
    202,
    28,
    23,
    33,
    37,
    21,
    27,
    20,
    35,
    28,
    24,
    11,
    16,
    58,
    37,
    18,
    17,
    30,
    27,
    32,
    28,
    15,
    24
  ],
  "targeted_crops_by_class": [
    0,
    6,
    3,
    1,
    5,
    5,
    5,
    2,
    7,
    4,
    4,
    5,
    5,
    5,
    5,
    3,
    1,
    7,
    4,
    6,
    8,
    6,
    7
  ],
  "sampled_scene_counts": [
    1,
    0,
    1,
    0,
    0,
    2,
    2,
    0,
    2,
    0,
    1,
    0,
    1,
    1,
    0,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    2,
    1,
    1,
    1,
    0,
    1,
    2,
    1,
    2,
    1,
    1,
    1,
    0,
    1,
    0,
    1,
    1,
    0,
    1,
    0,
    0,
    1,
    0,
    0,
    1,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    1,
    0,
    0,
    1,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    1,
    1,
    2,
    0,
    1,
    1,
    0,
    0,
    1,
    2,
    1,
    2,
    1,
    1,
    1,
    0,
    0,
    0,
    1,
    1,
    1,
    0,
    1,
    1,
    0,
    1,
    1,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    0,
    1,
    2,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    3,
    1,
    0,
    0,
    2,
    1,
    0,
    1,
    2,
    0,
    4,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    2,
    1,
    2,
    2,
    1,
    4,
    4,
    2,
    1,
    1,
    2,
    2,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    6,
    1,
    1,
    3,
    1,
    1,
    2,
    1,
    1,
    2,
    2,
    3,
    2,
    1,
    1,
    3,
    6,
    1,
    0,
    0,
    1,
    2,
    0,
    2,
    2,
    1,
    1,
    3,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    3,
    2,
    1,
    1
  ],
  "learning_rate": 8.449455119331898e-05,
  "attempted_updates": 202,
  "optimizer_updates": 202,
  "amp_skipped_updates": 0,
  "train_reconstruction_loss": 0.0010577139816659567,
  "train_segmentation_loss": 0.4292896730769979,
  "val_foreground_miou_all22": 0.534690742863078,
  "val_psnr_ref1": 36.64347900390625,
  "elapsed_seconds": 337.032648563385,
  "peak_cuda_allocated_gib": 7.504184722900391
}
Epochs111-120: mean mIoU=56.78%, std=3.48 points
Epochs121-130: mean mIoU=58.10%, std=3.93 points
New optimizer updates: 4039
New AMP skips: 1

In [1]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_to_epoch130_20260922_143402'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced130')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_to_epoch130_20260922_143402.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch130 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 130
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 130
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch130 run.')

Balanced epoch130 reference: /kaggle/input/datasets/arnavnigamd/checkpoint8/balanced_to_epoch130_20260922_143402
PASS:22-class support, aligned crops/flips, deterministic replay, no RNG consumed by index building, baseline crop branch unchanged.
Saved next-epoch LR: 8.426678690819333e-05
Preserved best metrics: {'iou': 0.6405504134118066, 'psnr': 37.036741485595705}
{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.
Training source hashes match the epoch130 run.

In [3]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT_RUN' not in globals():
    CONT_RUN = Path('/kaggle/working') / ('balanced_to_epoch200_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 130, 'target_epoch': 200, 'backup_epochs': [150,175,200],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Three subprocess blocks with epoch-boundary RNG restoration.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT_RUN.parent / (CONT_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT_RUN.parent, base_dir=CONT_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target in [150,175,200]
    last = CONT_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT_RUN.parent) + '/', '--name', CONT_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Block completed. Download the backup, then run the next block when ready.')
print('Continuation folder:', CONT_RUN)

Continuation folder: /kaggle/working/balanced_to_epoch200_20260922_164019

In [4]:
continue_to(150)

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced_to_epoch200_20260922_164019', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/input/datasets/arnavnigamd/checkpoint8/balanced_to_epoch130_20260922_143402/model/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=150, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-22 16:41:34,913 - INFO: Resuming after epoch 130

Epoch 131/500 | Batch 10/202 | Rec 0.001109 | Seg 0.509199 | Elapsed 0.6m | ETA 10.7m
Epoch 131/500 | Batch 20/202 | Rec 0.001166 | Seg 0.423172 | Elapsed 0.9m | ETA 7.9m
Epoch 131/500 | Batch 30/202 | Rec 0.001164 | Seg 0.438559 | Elapsed 1.2m | ETA 6.7m
Epoch 131/500 | Batch 40/202 | Rec 0.001212 | Seg 0.471956 | Elapsed 1.5m | ETA 5.9m
Epoch 131/500 | Batch 50/202 | Rec 0.001129 | Seg 0.448930 | Elapsed 1.7m | ETA 5.3m
Epoch 131/500 | Batch 60/202 | Rec 0.001124 | Seg 0.439263 | Elapsed 2.0m | ETA 4.8m
Epoch 131/500 | Batch 70/202 | Rec 0.001118 | Seg 0.436814 | Elapsed 2.3m | ETA 4.3m
Epoch 131/500 | Batch 80/202 | Rec 0.001120 | Seg 0.434457 | Elapsed 2.5m | ETA 3.9m
Epoch 131/500 | Batch 90/202 | Rec 0.001127 | Seg 0.446905 | Elapsed 2.8m | ETA 3.5m
Epoch 131/500 | Batch 100/202 | Rec 0.001124 | Seg 0.447013 | Elapsed 3.0m | ETA 3.1m
Epoch 131/500 | Batch 110/202 | Rec 0.001110 | Seg 0.449910 | Elapsed 3.3m | ETA 2.8m
Epoch 131/500 | Batch 120/202 | Rec 0.001109 | Seg 0.445754 | Elapsed 3.6m | ETA 2.5m
Epoch 131/500 | Batch 130/202 | Rec 0.001107 | Seg 0.443296 | Elapsed 3.9m | ETA 2.2m
Epoch 131/500 | Batch 140/202 | Rec 0.001106 | Seg 0.439905 | Elapsed 4.2m | ETA 1.9m
Epoch 131/500 | Batch 150/202 | Rec 0.001101 | Seg 0.441970 | Elapsed 4.4m | ETA 1.5m
Epoch 131/500 | Batch 160/202 | Rec 0.001094 | Seg 0.439416 | Elapsed 4.7m | ETA 1.2m
Epoch 131/500 | Batch 170/202 | Rec 0.001075 | Seg 0.433245 | Elapsed 4.9m | ETA 0.9m
Epoch 131/500 | Batch 180/202 | Rec 0.001077 | Seg 0.435805 | Elapsed 5.2m | ETA 0.6m
Epoch 131/500 | Batch 190/202 | Rec 0.001082 | Seg 0.434543 | Elapsed 5.4m | ETA 0.3m
Epoch 131/500 | Batch 200/202 | Rec 0.001094 | Seg 0.441272 | Elapsed 5.7m | ETA 0.1m
Epoch 131/500 | Batch 202/202 | Rec 0.001089 | Seg 0.440006 | Elapsed 5.7m | ETA 0.0m

2026-09-22 16:47:17,478 - INFO: Rec loss: 0.001089372483253857
2026-09-22 16:47:17,478 - INFO: Seg loss: 0.44000647364571543
2026-09-22 16:47:17,478 - INFO: λ_rec: 1
2026-09-22 16:47:17,478 - INFO: λ_seg: 0.0001
2026-09-22 16:48:51,809 - INFO: -------------------Epoch: 131------------------------
2026-09-22 16:48:51,819 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.347699  0.965914  0.000239
2026-09-22 16:48:51,826 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994533  0.997209  0.995795  0.998727  0.994773
real potato   0.918482  0.957459  0.980746  0.935348  0.999901
fake potato   0.940496  0.969285  0.968626  0.970046  0.999955
real apple    0.590851  0.742764  0.993995  0.592968  0.998583
fake apple    0.650398  0.788122  0.890206  0.707121  0.998565
real orange   0.471659  0.640946  0.989367  0.474062  0.999300
fake orange   0.731873  0.845132  0.742229  0.981292  0.998971
real grape    0.420687  0.592182  0.757169  0.486297  0.998602
fake grape    0.827628  0.905636  0.917040  0.894609  0.999311
real lemon    0.303540  0.465666  0.445657  0.487666  0.998685
fake lemon    0.816764  0.899092  0.984802  0.827191  0.999607
real avocado  0.805915  0.892478  0.928647  0.859113  0.999808
fake avocado  0.367093  0.537002  0.984030  0.369294  0.999238
real pepper   0.740183  0.850646  0.886412  0.817746  0.998950
fake pepper   0.886321  0.939685  0.976200  0.905896  0.999723
real plant    0.792904  0.884442  0.880533  0.888485  0.997679
fake plant    0.646247  0.785067  0.672780  0.942485  0.999589
real banana   0.289127  0.448526  0.969321  0.291797  0.998388
fake banana   0.519504  0.683733  0.579405  0.834025  0.998581
real onion    0.825509  0.904365  0.867649  0.944435  0.999820
fake onion    0.934959  0.966337  0.988122  0.945586  0.999958
real unknown  0.419621  0.591131  0.424875  0.971374  0.999785
fake unknown  0.129359  0.229046  0.153798  0.448750  0.997455
total         0.653202  0.761563  0.825105  0.764100  0.998923
total(-bg)    0.637687  0.750852  0.817346  0.753436  0.999112
2026-09-22 16:48:52,299 - INFO: Epoch accounting: {'epoch': 131, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11296636, 70607, 67043, 86679, 116661, 53192, 76216, 85752, 196042, 51945, 58158, 48620, 43809, 237882, 125254, 181569, 17826, 90258, 102478, 127820, 59470, 14466, 29889], 'crops_with_class': [202, 42, 29, 20, 29, 19, 25, 17, 35, 28, 26, 16, 17, 55, 33, 22, 20, 34, 37, 50, 32, 14, 17], 'targeted_crops_by_class': [0, 8, 6, 3, 7, 6, 5, 3, 6, 4, 2, 5, 3, 5, 3, 6, 3, 8, 1, 7, 3, 7, 4], 'sampled_scene_counts': [0, 0, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 1, 0, 1, 1, 1, 2, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0, 1, 3, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 2, 1, 0, 0, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 0, 0, 2, 1, 3, 0, 0, 2, 2, 0, 1, 1, 1, 0, 1, 3, 2, 2, 1, 0, 2, 1, 1, 2, 2, 0, 4, 6, 0, 1, 0, 4, 1, 3, 0, 0, 2, 2, 2, 1, 3, 2, 1, 0, 3, 0, 3, 2, 2, 5, 2, 0, 2, 3, 0, 1, 2, 2, 1, 3, 3, 1, 2, 1, 0, 2, 1, 2, 0, 2, 4, 0, 1, 3], 'learning_rate': 8.426678690819333e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001089372483253857, 'train_segmentation_loss': 0.44000647364571543, 'val_foreground_miou_all22': 0.637687250917586, 'val_psnr_ref1': 36.3476985168457, 'elapsed_seconds': 437.37768387794495, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 132/500 | Batch 10/202 | Rec 0.001049 | Seg 0.383189 | Elapsed 0.2m | ETA 4.6m
Epoch 132/500 | Batch 20/202 | Rec 0.001048 | Seg 0.386483 | Elapsed 0.5m | ETA 4.1m
Epoch 132/500 | Batch 30/202 | Rec 0.001064 | Seg 0.392055 | Elapsed 0.7m | ETA 4.1m
Epoch 132/500 | Batch 40/202 | Rec 0.001061 | Seg 0.416291 | Elapsed 0.9m | ETA 3.8m
Epoch 132/500 | Batch 50/202 | Rec 0.001018 | Seg 0.397263 | Elapsed 1.2m | ETA 3.6m
Epoch 132/500 | Batch 60/202 | Rec 0.000986 | Seg 0.395420 | Elapsed 1.4m | ETA 3.4m
Epoch 132/500 | Batch 70/202 | Rec 0.000968 | Seg 0.388186 | Elapsed 1.6m | ETA 3.1m
Epoch 132/500 | Batch 80/202 | Rec 0.000979 | Seg 0.391776 | Elapsed 1.9m | ETA 2.9m
Epoch 132/500 | Batch 90/202 | Rec 0.000979 | Seg 0.385436 | Elapsed 2.1m | ETA 2.6m
Epoch 132/500 | Batch 100/202 | Rec 0.000978 | Seg 0.386657 | Elapsed 2.3m | ETA 2.4m
Epoch 132/500 | Batch 110/202 | Rec 0.001004 | Seg 0.400278 | Elapsed 2.5m | ETA 2.1m
Epoch 132/500 | Batch 120/202 | Rec 0.000999 | Seg 0.397870 | Elapsed 2.8m | ETA 1.9m
Epoch 132/500 | Batch 130/202 | Rec 0.001004 | Seg 0.401718 | Elapsed 3.1m | ETA 1.7m
Epoch 132/500 | Batch 140/202 | Rec 0.001001 | Seg 0.398550 | Elapsed 3.3m | ETA 1.5m
Epoch 132/500 | Batch 150/202 | Rec 0.001003 | Seg 0.401106 | Elapsed 3.5m | ETA 1.2m
Epoch 132/500 | Batch 160/202 | Rec 0.001012 | Seg 0.409842 | Elapsed 3.7m | ETA 1.0m
Epoch 132/500 | Batch 170/202 | Rec 0.001015 | Seg 0.413666 | Elapsed 3.9m | ETA 0.7m
Epoch 132/500 | Batch 180/202 | Rec 0.001051 | Seg 0.421611 | Elapsed 4.2m | ETA 0.5m
Epoch 132/500 | Batch 190/202 | Rec 0.001063 | Seg 0.427777 | Elapsed 4.4m | ETA 0.3m
Epoch 132/500 | Batch 200/202 | Rec 0.001073 | Seg 0.427295 | Elapsed 4.6m | ETA 0.0m
Epoch 132/500 | Batch 202/202 | Rec 0.001069 | Seg 0.426740 | Elapsed 4.7m | ETA 0.0m

2026-09-22 16:53:32,396 - INFO: Rec loss: 0.0010692425067006324
2026-09-22 16:53:32,396 - INFO: Seg loss: 0.42674017199637865
2026-09-22 16:53:32,396 - INFO: λ_rec: 1
2026-09-22 16:53:32,396 - INFO: λ_seg: 0.0001
2026-09-22 16:54:47,174 - INFO: -------------------Epoch: 132------------------------
2026-09-22 16:54:47,178 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.142633  0.967231  0.000256
2026-09-22 16:54:47,185 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994644  0.997265  0.995547  0.999089  0.994878
real potato   0.796757  0.886834  0.947788  0.833333  0.999746
fake potato   0.861501  0.925548  0.900218  0.952451  0.999888
real apple    0.669889  0.802266  0.841993  0.766210  0.998697
fake apple    0.307224  0.470004  0.993608  0.307832  0.997379
real orange   0.240065  0.387149  0.978863  0.241315  0.998993
fake orange   0.661685  0.796354  0.673307  0.974576  0.998573
real grape    0.472775  0.641971  0.791537  0.540013  0.998743
fake grape    0.818843  0.900350  0.970221  0.839954  0.999313
real lemon    0.348139  0.516426  0.669770  0.420280  0.999075
fake lemon    0.780066  0.876397  0.998065  0.781248  0.999534
real avocado  0.621679  0.766663  0.997894  0.622496  0.999648
fake avocado  0.504774  0.670852  0.996732  0.505611  0.999406
real pepper   0.734913  0.847154  0.836676  0.858001  0.998868
fake pepper   0.796971  0.886966  0.891548  0.882530  0.999464
real plant    0.795727  0.886195  0.892435  0.880141  0.997740
fake plant    0.819898  0.900987  0.878943  0.924271  0.999838
real banana   0.451706  0.622266  0.926777  0.468423  0.998722
fake banana   0.494429  0.661649  0.546151  0.839250  0.998421
real onion    0.811736  0.896037  0.883725  0.908799  0.999810
fake onion    0.880762  0.936551  0.913353  0.961064  0.999918
real unknown  0.559848  0.717777  0.565695  0.981870  0.999877
fake unknown  0.112894  0.202850  0.128502  0.481710  0.996811
total         0.632040  0.747674  0.835624  0.737846  0.998841
total(-bg)    0.615558  0.736329  0.828355  0.725972  0.999021
2026-09-22 16:54:47,755 - INFO: Epoch accounting: {'epoch': 132, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11331392, 56464, 61374, 121605, 140419, 77235, 63299, 172431, 181583, 64873, 51582, 41525, 35168, 211813, 104352, 124746, 33648, 91172, 78302, 77106, 47468, 13172, 57543], 'crops_with_class': [202, 30, 29, 32, 31, 23, 25, 35, 35, 30, 24, 16, 13, 52, 28, 23, 30, 26, 31, 38, 23, 15, 28], 'targeted_crops_by_class': [0, 4, 5, 3, 6, 5, 6, 6, 3, 4, 5, 2, 3, 4, 4, 6, 5, 6, 3, 4, 4, 4, 6], 'sampled_scene_counts': [2, 1, 1, 1, 0, 2, 0, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 3, 0, 1, 0, 2, 2, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 0, 1, 0, 3, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 2, 1, 0, 0, 0, 1, 1, 2, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 2, 3, 1, 1, 2, 2, 2, 1, 0, 2, 1, 1, 2, 2, 2, 3, 1, 1, 1, 3, 0, 1, 1, 1, 5, 5, 1, 1, 1, 0, 2, 0, 1, 2, 2, 2, 1, 1, 1, 1, 3, 2, 1, 2, 1, 1, 1, 0, 2, 1, 1, 1, 2, 1, 3, 2, 2, 3, 1, 0, 2, 0, 0, 0, 3, 1], 'learning_rate': 8.403767476378064e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010692425067006324, 'train_segmentation_loss': 0.42674017199637865, 'val_foreground_miou_all22': 0.6155582092455216, 'val_psnr_ref1': 36.142633209228514, 'elapsed_seconds': 355.44791412353516, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 133/500 | Batch 10/202 | Rec 0.001058 | Seg 0.390213 | Elapsed 0.2m | ETA 4.0m
Epoch 133/500 | Batch 20/202 | Rec 0.001030 | Seg 0.413201 | Elapsed 0.4m | ETA 3.8m
Epoch 133/500 | Batch 30/202 | Rec 0.001032 | Seg 0.381591 | Elapsed 0.6m | ETA 3.7m
Epoch 133/500 | Batch 40/202 | Rec 0.000997 | Seg 0.389709 | Elapsed 0.9m | ETA 3.4m
Epoch 133/500 | Batch 50/202 | Rec 0.001013 | Seg 0.390426 | Elapsed 1.1m | ETA 3.2m
Epoch 133/500 | Batch 60/202 | Rec 0.001037 | Seg 0.404752 | Elapsed 1.3m | ETA 3.0m
Epoch 133/500 | Batch 70/202 | Rec 0.001064 | Seg 0.408850 | Elapsed 1.5m | ETA 2.8m
Epoch 133/500 | Batch 80/202 | Rec 0.001072 | Seg 0.418897 | Elapsed 1.7m | ETA 2.6m
Epoch 133/500 | Batch 90/202 | Rec 0.001067 | Seg 0.415013 | Elapsed 1.9m | ETA 2.4m
Epoch 133/500 | Batch 100/202 | Rec 0.001058 | Seg 0.421820 | Elapsed 2.1m | ETA 2.2m
Epoch 133/500 | Batch 110/202 | Rec 0.001036 | Seg 0.413634 | Elapsed 2.3m | ETA 2.0m
Epoch 133/500 | Batch 120/202 | Rec 0.001044 | Seg 0.409279 | Elapsed 2.6m | ETA 1.7m
Epoch 133/500 | Batch 130/202 | Rec 0.001059 | Seg 0.418237 | Elapsed 2.8m | ETA 1.5m
Epoch 133/500 | Batch 140/202 | Rec 0.001070 | Seg 0.418586 | Elapsed 3.0m | ETA 1.3m
Epoch 133/500 | Batch 150/202 | Rec 0.001083 | Seg 0.424614 | Elapsed 3.2m | ETA 1.1m
Epoch 133/500 | Batch 160/202 | Rec 0.001074 | Seg 0.421771 | Elapsed 3.4m | ETA 0.9m
Epoch 133/500 | Batch 170/202 | Rec 0.001069 | Seg 0.422351 | Elapsed 3.6m | ETA 0.7m
Epoch 133/500 | Batch 180/202 | Rec 0.001065 | Seg 0.422894 | Elapsed 3.8m | ETA 0.5m
Epoch 133/500 | Batch 190/202 | Rec 0.001065 | Seg 0.425909 | Elapsed 4.0m | ETA 0.3m
Epoch 133/500 | Batch 200/202 | Rec 0.001067 | Seg 0.421992 | Elapsed 4.3m | ETA 0.0m
Epoch 133/500 | Batch 202/202 | Rec 0.001068 | Seg 0.424252 | Elapsed 4.3m | ETA 0.0m

2026-09-22 16:59:05,381 - INFO: Rec loss: 0.0010679584040622328
2026-09-22 16:59:05,381 - INFO: Seg loss: 0.4242519235404411
2026-09-22 16:59:05,382 - INFO: λ_rec: 1
2026-09-22 16:59:05,382 - INFO: λ_seg: 0.0001
2026-09-22 17:00:20,284 - INFO: -------------------Epoch: 133------------------------
2026-09-22 17:00:20,288 - INFO:
Validation stats:
       PSNR     SSIM      MSE
0  35.63385  0.96571  0.00028
2026-09-22 17:00:20,295 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995271  0.997580  0.996780  0.998481  0.995483
real potato   0.330868  0.497184  0.999615  0.330910  0.999199
fake potato   0.466957  0.636589  0.977026  0.472141  0.999607
real apple    0.614910  0.761491  0.731795  0.793808  0.998285
fake apple    0.604049  0.753107  0.959465  0.619867  0.998466
real orange   0.370135  0.540250  0.992875  0.371121  0.999168
fake orange   0.704379  0.826503  0.718812  0.972284  0.998832
real grape    0.497170  0.664098  0.805776  0.564862  0.998807
fake grape    0.786201  0.880255  0.858330  0.903436  0.999091
real lemon    0.150247  0.261193  0.251078  0.272267  0.998190
fake lemon    0.821385  0.901885  0.982160  0.833826  0.999616
real avocado  0.741557  0.851552  0.798591  0.912151  0.999705
fake avocado  0.135727  0.238990  0.877122  0.138358  0.998946
real pepper   0.680788  0.810032  0.794877  0.825880  0.998584
fake pepper   0.690321  0.816745  0.994215  0.693105  0.999259
real plant    0.840523  0.913302  0.902584  0.924381  0.998246
fake plant    0.733074  0.845931  0.770223  0.938267  0.999728
real banana   0.176439  0.299928  0.977154  0.177170  0.998142
fake banana   0.505585  0.671564  0.580872  0.795952  0.998568
real onion    0.676517  0.807001  0.817898  0.796487  0.999656
fake onion    0.914759  0.955432  0.963829  0.947279  0.999944
real unknown  0.736451  0.848176  0.768397  0.946565  0.999946
fake unknown  0.153175  0.265630  0.160124  0.779247  0.996370
total         0.579413  0.697583  0.812156  0.695993  0.998776
total(-bg)    0.560510  0.683947  0.803764  0.682244  0.998925
2026-09-22 17:00:20,823 - INFO: Epoch accounting: {'epoch': 133, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11312554, 52574, 61468, 137026, 152795, 127483, 98625, 155903, 157943, 78168, 66998, 46953, 31819, 191850, 111705, 125700, 25203, 69517, 59666, 69618, 54311, 3223, 47170], 'crops_with_class': [202, 30, 25, 37, 39, 34, 32, 27, 34, 35, 26, 16, 11, 53, 32, 20, 22, 21, 24, 31, 27, 4, 18], 'targeted_crops_by_class': [0, 5, 3, 4, 6, 6, 6, 5, 9, 1, 6, 5, 3, 9, 4, 2, 6, 3, 3, 4, 5, 1, 8], 'sampled_scene_counts': [2, 1, 3, 0, 0, 2, 0, 1, 1, 2, 1, 0, 0, 2, 2, 1, 0, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 0, 2, 1, 0, 0, 0, 1, 0, 2, 1, 2, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 2, 1, 0, 3, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 3, 2, 1, 1, 1, 2, 1, 3, 2, 1, 1, 2, 1, 1, 0, 2, 1, 0, 3, 2, 4, 0, 1, 2, 4, 2, 0, 2, 2, 1, 2, 3, 0, 0, 1, 3, 0, 2, 1, 1, 2, 3, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 1, 2, 2, 1, 1], 'learning_rate': 8.380722380503607e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010679584040622328, 'train_segmentation_loss': 0.4242519235404411, 'val_foreground_miou_all22': 0.5605098921438716, 'val_psnr_ref1': 35.63385040283203, 'elapsed_seconds': 333.0606777667999, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 134/500 | Batch 10/202 | Rec 0.001127 | Seg 0.420455 | Elapsed 0.2m | ETA 4.1m
Epoch 134/500 | Batch 20/202 | Rec 0.001196 | Seg 0.390036 | Elapsed 0.4m | ETA 3.9m
Epoch 134/500 | Batch 30/202 | Rec 0.001100 | Seg 0.356364 | Elapsed 0.6m | ETA 3.7m
Epoch 134/500 | Batch 40/202 | Rec 0.001082 | Seg 0.356509 | Elapsed 0.8m | ETA 3.4m
Epoch 134/500 | Batch 50/202 | Rec 0.001108 | Seg 0.382910 | Elapsed 1.0m | ETA 3.2m
Epoch 134/500 | Batch 60/202 | Rec 0.001164 | Seg 0.402027 | Elapsed 1.3m | ETA 3.0m
Epoch 134/500 | Batch 70/202 | Rec 0.001211 | Seg 0.423946 | Elapsed 1.5m | ETA 2.8m
Epoch 134/500 | Batch 80/202 | Rec 0.001186 | Seg 0.423297 | Elapsed 1.7m | ETA 2.6m
Epoch 134/500 | Batch 90/202 | Rec 0.001172 | Seg 0.427221 | Elapsed 1.9m | ETA 2.4m
Epoch 134/500 | Batch 100/202 | Rec 0.001160 | Seg 0.422536 | Elapsed 2.1m | ETA 2.2m
Epoch 134/500 | Batch 110/202 | Rec 0.001141 | Seg 0.425014 | Elapsed 2.3m | ETA 1.9m
Epoch 134/500 | Batch 120/202 | Rec 0.001128 | Seg 0.418763 | Elapsed 2.5m | ETA 1.7m
Epoch 134/500 | Batch 130/202 | Rec 0.001113 | Seg 0.416572 | Elapsed 2.7m | ETA 1.5m
Epoch 134/500 | Batch 140/202 | Rec 0.001085 | Seg 0.409555 | Elapsed 2.9m | ETA 1.3m
Epoch 134/500 | Batch 150/202 | Rec 0.001087 | Seg 0.406999 | Elapsed 3.1m | ETA 1.1m
Epoch 134/500 | Batch 160/202 | Rec 0.001081 | Seg 0.401797 | Elapsed 3.3m | ETA 0.9m
Epoch 134/500 | Batch 170/202 | Rec 0.001089 | Seg 0.409978 | Elapsed 3.5m | ETA 0.7m
Epoch 134/500 | Batch 180/202 | Rec 0.001074 | Seg 0.404255 | Elapsed 3.8m | ETA 0.5m
Epoch 134/500 | Batch 190/202 | Rec 0.001075 | Seg 0.408314 | Elapsed 4.0m | ETA 0.3m
Epoch 134/500 | Batch 200/202 | Rec 0.001074 | Seg 0.411963 | Elapsed 4.2m | ETA 0.0m
Epoch 134/500 | Batch 202/202 | Rec 0.001077 | Seg 0.413428 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:04:33,877 - INFO: Rec loss: 0.0010770043753845948
2026-09-22 17:04:33,877 - INFO: Seg loss: 0.4134282153653036
2026-09-22 17:04:33,877 - INFO: λ_rec: 1
2026-09-22 17:04:33,877 - INFO: λ_seg: 0.0001
2026-09-22 17:05:48,279 - INFO: -------------------Epoch: 134------------------------
2026-09-22 17:05:48,283 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.822685  0.966891  0.000215
2026-09-22 17:05:48,289 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994190  0.997036  0.995038  0.999144  0.994441
real potato   0.694971  0.819991  0.997624  0.696123  0.999634
fake potato   0.595754  0.746627  0.989627  0.599497  0.999704
real apple    0.689406  0.816103  0.910204  0.739717  0.998850
fake apple    0.637743  0.778759  0.969535  0.650784  0.998604
real orange   0.466918  0.636553  0.972626  0.473136  0.999288
fake orange   0.770347  0.870228  0.788731  0.970632  0.999172
real grape    0.469859  0.639278  0.842924  0.514946  0.998787
fake grape    0.710648  0.830803  0.892553  0.777132  0.998829
real lemon    0.009384  0.018554  0.035505  0.012594  0.998437
fake lemon    0.815510  0.898332  0.962039  0.842625  0.999597
real avocado  0.652877  0.789939  0.820223  0.761905  0.999624
fake avocado  0.368694  0.538711  0.918562  0.381153  0.999219
real pepper   0.707042  0.828332  0.818845  0.838144  0.998730
fake pepper   0.811857  0.896111  0.954957  0.844184  0.999534
real plant    0.827862  0.905775  0.903031  0.908637  0.998110
fake plant    0.766403  0.867706  0.845426  0.891296  0.999784
real banana   0.121429  0.216538  0.823318  0.124677  0.997973
fake banana   0.402786  0.574219  0.458732  0.767585  0.997906
real onion    0.772316  0.871483  0.849920  0.894275  0.999762
fake onion    0.903738  0.949385  0.963867  0.935429  0.999937
real unknown  0.683819  0.812175  0.701876  0.963740  0.999929
fake unknown  0.159789  0.275515  0.173940  0.662622  0.997064
total         0.610145  0.720789  0.808222  0.706521  0.998822
total(-bg)    0.592689  0.708233  0.799730  0.693220  0.999022
2026-09-22 17:05:48,822 - INFO: Epoch accounting: {'epoch': 134, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11367760, 57471, 57227, 113038, 159865, 97909, 71993, 134925, 183228, 57401, 41555, 30968, 34705, 198007, 132037, 127465, 26738, 103578, 69656, 80176, 42937, 4258, 45375], 'crops_with_class': [202, 31, 24, 29, 38, 28, 27, 25, 31, 28, 21, 13, 12, 56, 32, 21, 25, 30, 28, 34, 24, 6, 20], 'targeted_crops_by_class': [0, 8, 4, 2, 9, 6, 5, 6, 8, 0, 7, 2, 4, 3, 6, 6, 7, 5, 4, 4, 2, 2, 6], 'sampled_scene_counts': [1, 0, 2, 1, 2, 2, 0, 0, 1, 3, 2, 1, 1, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 1, 0, 1, 1, 2, 2, 0, 1, 0, 0, 0, 0, 0, 1, 3, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1, 1, 0, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 3, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 1, 2, 0, 1, 0, 1, 1, 2, 0, 0, 2, 2, 1, 2, 1, 2, 0, 0, 1, 1, 2, 1, 1, 2, 1, 0, 1, 1, 2, 1, 4, 1, 1, 1, 1, 3, 1, 1, 2, 1, 3, 2, 2, 3, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 2, 2, 0, 2, 1, 2, 1, 1, 3, 0, 2, 0, 0, 0, 1, 1, 2, 4, 1, 2, 1, 1, 3, 0, 0, 2, 2, 2, 1, 1, 2, 0, 1, 0, 4, 1], 'learning_rate': 8.35754431297689e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010770043753845948, 'train_segmentation_loss': 0.4134282153653036, 'val_foreground_miou_all22': 0.5926886592703279, 'val_psnr_ref1': 36.822685394287106, 'elapsed_seconds': 327.99085235595703, 'peak_cuda_allocated_gib': 7.509555816650391}

Epoch 135/500 | Batch 10/202 | Rec 0.001195 | Seg 0.439688 | Elapsed 0.2m | ETA 4.0m
Epoch 135/500 | Batch 20/202 | Rec 0.001173 | Seg 0.441606 | Elapsed 0.4m | ETA 3.8m
Epoch 135/500 | Batch 30/202 | Rec 0.001182 | Seg 0.447375 | Elapsed 0.6m | ETA 3.6m
Epoch 135/500 | Batch 40/202 | Rec 0.001240 | Seg 0.457449 | Elapsed 0.8m | ETA 3.4m
Epoch 135/500 | Batch 50/202 | Rec 0.001253 | Seg 0.451620 | Elapsed 1.0m | ETA 3.2m
Epoch 135/500 | Batch 60/202 | Rec 0.001210 | Seg 0.465397 | Elapsed 1.3m | ETA 3.0m
Epoch 135/500 | Batch 70/202 | Rec 0.001204 | Seg 0.473281 | Elapsed 1.4m | ETA 2.7m
Epoch 135/500 | Batch 80/202 | Rec 0.001173 | Seg 0.462007 | Elapsed 1.7m | ETA 2.5m
Epoch 135/500 | Batch 90/202 | Rec 0.001183 | Seg 0.466712 | Elapsed 1.9m | ETA 2.3m
Epoch 135/500 | Batch 100/202 | Rec 0.001175 | Seg 0.463745 | Elapsed 2.1m | ETA 2.1m
Epoch 135/500 | Batch 110/202 | Rec 0.001156 | Seg 0.456350 | Elapsed 2.3m | ETA 1.9m
Epoch 135/500 | Batch 120/202 | Rec 0.001145 | Seg 0.456788 | Elapsed 2.5m | ETA 1.7m
Epoch 135/500 | Batch 130/202 | Rec 0.001136 | Seg 0.452471 | Elapsed 2.7m | ETA 1.5m
Epoch 135/500 | Batch 140/202 | Rec 0.001147 | Seg 0.450504 | Elapsed 2.9m | ETA 1.3m
Epoch 135/500 | Batch 150/202 | Rec 0.001135 | Seg 0.445901 | Elapsed 3.1m | ETA 1.1m
Epoch 135/500 | Batch 160/202 | Rec 0.001122 | Seg 0.444120 | Elapsed 3.3m | ETA 0.9m
Epoch 135/500 | Batch 170/202 | Rec 0.001118 | Seg 0.443386 | Elapsed 3.5m | ETA 0.7m
Epoch 135/500 | Batch 180/202 | Rec 0.001131 | Seg 0.442033 | Elapsed 3.7m | ETA 0.5m
Epoch 135/500 | Batch 190/202 | Rec 0.001138 | Seg 0.443199 | Elapsed 3.9m | ETA 0.2m
Epoch 135/500 | Batch 200/202 | Rec 0.001126 | Seg 0.438938 | Elapsed 4.2m | ETA 0.0m
Epoch 135/500 | Batch 202/202 | Rec 0.001122 | Seg 0.437571 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:10:00,800 - INFO: Rec loss: 0.0011221477779154066
2026-09-22 17:10:00,801 - INFO: Seg loss: 0.43757136782059575
2026-09-22 17:10:00,801 - INFO: λ_rec: 1
2026-09-22 17:10:00,801 - INFO: λ_seg: 0.0001
2026-09-22 17:11:15,106 - INFO: -------------------Epoch: 135------------------------
2026-09-22 17:11:15,110 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.487342  0.965204  0.000233
2026-09-22 17:11:15,117 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995095  0.997491  0.996472  0.998613  0.995314
real potato   0.705358  0.827177  0.997301  0.706707  0.999647
fake potato   0.825548  0.904389  0.984229  0.836615  0.999871
real apple    0.666721  0.799990  0.894170  0.723839  0.998752
fake apple    0.600194  0.750103  0.888569  0.649046  0.998368
real orange   0.554085  0.713023  0.974318  0.562297  0.999404
fake orange   0.793619  0.884886  0.825754  0.953257  0.999290
real grape    0.160180  0.276102  0.812277  0.166338  0.998179
fake grape    0.756312  0.861200  0.851544  0.871179  0.998962
real lemon    0.028344  0.055100  0.186937  0.032329  0.998698
fake lemon    0.782994  0.878242  0.988276  0.790335  0.999537
real avocado  0.890746  0.942166  0.939295  0.945156  0.999892
fake avocado  0.777976  0.875076  0.999345  0.778373  0.999734
real pepper   0.777635  0.874860  0.891462  0.858960  0.999102
fake pepper   0.801358  0.889677  0.829286  0.959670  0.999433
real plant    0.774340  0.872770  0.829225  0.921253  0.997315
fake plant    0.778054  0.875125  0.850552  0.901265  0.999795
real banana   0.304572  0.466890  0.854716  0.321201  0.998352
fake banana   0.358236  0.527460  0.377112  0.877405  0.997108
real onion    0.761309  0.864431  0.828355  0.903901  0.999744
fake onion    0.931422  0.964443  0.987335  0.942684  0.999956
real unknown  0.713200  0.832545  0.721174  0.984733  0.999937
fake unknown  0.156091  0.269989  0.200919  0.411626  0.998125
total         0.647539  0.747962  0.813418  0.743338  0.998892
total(-bg)    0.631741  0.736620  0.805098  0.731735  0.999055
2026-09-22 17:11:15,665 - INFO: Epoch accounting: {'epoch': 135, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11252248, 48680, 48937, 125453, 154075, 75221, 91004, 173547, 182810, 75053, 49248, 16369, 18525, 221034, 177258, 141840, 18543, 97103, 86250, 88994, 49955, 10503, 35622], 'crops_with_class': [202, 27, 26, 36, 40, 24, 28, 31, 34, 31, 24, 8, 8, 61, 41, 24, 20, 31, 33, 37, 24, 12, 16], 'targeted_crops_by_class': [0, 10, 3, 2, 8, 5, 7, 5, 5, 2, 4, 3, 4, 8, 4, 6, 4, 7, 3, 3, 6, 5, 0], 'sampled_scene_counts': [1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 1, 0, 1, 1, 3, 0, 3, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 1, 2, 3, 1, 2, 0, 1, 3, 2, 0, 0, 2, 2, 1, 0, 1, 3, 3, 0, 1, 1, 2, 0, 0, 1, 1, 1, 1, 3, 1, 0, 2, 0, 4, 2, 2, 3, 2, 4, 3, 2, 1, 1, 1, 0, 2, 3, 4, 3, 3, 1, 1, 1, 1, 3, 3, 2, 2, 0, 1, 0, 2, 1, 2, 1, 1, 1, 2, 0, 2, 1, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1], 'learning_rate': 8.334234188828327e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0011221477779154066, 'train_segmentation_loss': 0.43757136782059575, 'val_foreground_miou_all22': 0.6317405624371424, 'val_psnr_ref1': 36.48734237670899, 'elapsed_seconds': 326.8362355232239, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 136/500 | Batch 10/202 | Rec 0.000995 | Seg 0.463153 | Elapsed 0.2m | ETA 4.0m
Epoch 136/500 | Batch 20/202 | Rec 0.001126 | Seg 0.473820 | Elapsed 0.4m | ETA 3.7m
Epoch 136/500 | Batch 30/202 | Rec 0.001149 | Seg 0.463249 | Elapsed 0.6m | ETA 3.5m
Epoch 136/500 | Batch 40/202 | Rec 0.001091 | Seg 0.450685 | Elapsed 0.8m | ETA 3.3m
Epoch 136/500 | Batch 50/202 | Rec 0.001059 | Seg 0.441846 | Elapsed 1.0m | ETA 3.1m
Epoch 136/500 | Batch 60/202 | Rec 0.001070 | Seg 0.441123 | Elapsed 1.2m | ETA 2.9m
Epoch 136/500 | Batch 70/202 | Rec 0.001045 | Seg 0.422695 | Elapsed 1.4m | ETA 2.7m
Epoch 136/500 | Batch 80/202 | Rec 0.001035 | Seg 0.411774 | Elapsed 1.7m | ETA 2.5m
Epoch 136/500 | Batch 90/202 | Rec 0.001064 | Seg 0.423721 | Elapsed 1.9m | ETA 2.3m
Epoch 136/500 | Batch 100/202 | Rec 0.001058 | Seg 0.429205 | Elapsed 2.1m | ETA 2.1m
Epoch 136/500 | Batch 110/202 | Rec 0.001063 | Seg 0.430959 | Elapsed 2.3m | ETA 1.9m
Epoch 136/500 | Batch 120/202 | Rec 0.001059 | Seg 0.428519 | Elapsed 2.5m | ETA 1.7m
Epoch 136/500 | Batch 130/202 | Rec 0.001060 | Seg 0.430326 | Elapsed 2.7m | ETA 1.5m
Epoch 136/500 | Batch 140/202 | Rec 0.001053 | Seg 0.429438 | Elapsed 2.9m | ETA 1.3m
Epoch 136/500 | Batch 150/202 | Rec 0.001059 | Seg 0.433294 | Elapsed 3.1m | ETA 1.1m
Epoch 136/500 | Batch 160/202 | Rec 0.001063 | Seg 0.436603 | Elapsed 3.3m | ETA 0.9m
Epoch 136/500 | Batch 170/202 | Rec 0.001058 | Seg 0.430229 | Elapsed 3.5m | ETA 0.7m
Epoch 136/500 | Batch 180/202 | Rec 0.001075 | Seg 0.434344 | Elapsed 3.8m | ETA 0.5m
Epoch 136/500 | Batch 190/202 | Rec 0.001069 | Seg 0.432054 | Elapsed 4.0m | ETA 0.2m
Epoch 136/500 | Batch 200/202 | Rec 0.001073 | Seg 0.431290 | Elapsed 4.2m | ETA 0.0m
Epoch 136/500 | Batch 202/202 | Rec 0.001073 | Seg 0.432452 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:15:28,142 - INFO: Rec loss: 0.001072866859728249
2026-09-22 17:15:28,143 - INFO: Seg loss: 0.4324521655862284
2026-09-22 17:15:28,143 - INFO: λ_rec: 1
2026-09-22 17:15:28,143 - INFO: λ_seg: 0.0001
2026-09-22 17:16:42,452 - INFO: -------------------Epoch: 136------------------------
2026-09-22 17:16:42,455 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.766128  0.968675  0.000217
2026-09-22 17:16:42,461 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994776  0.997331  0.995746  0.999021  0.995005
real potato   0.868569  0.929612  0.998536  0.869676  0.999843
fake potato   0.940454  0.969263  0.993621  0.946167  0.999956
real apple    0.821546  0.901982  0.932028  0.873905  0.999345
fake apple    0.586738  0.739505  0.971021  0.597195  0.998412
real orange   0.485471  0.653582  0.983481  0.489463  0.999316
fake orange   0.764363  0.866397  0.786559  0.964396  0.999149
real grape    0.697046  0.821433  0.948608  0.724403  0.999343
fake grape    0.847547  0.917434  0.936316  0.899394  0.999402
real lemon    0.317329  0.481726  0.515465  0.452220  0.998857
fake lemon    0.818700  0.900264  0.970883  0.839308  0.999607
real avocado  0.744163  0.853268  0.843329  0.863547  0.999724
fake avocado  0.253379  0.404282  1.000000  0.253379  0.999107
real pepper   0.721622  0.838255  0.824229  0.852870  0.998797
fake pepper   0.802307  0.890261  0.980968  0.814993  0.999521
real plant    0.834635  0.909815  0.937563  0.883756  0.998249
fake plant    0.822904  0.902799  0.932747  0.874808  0.999850
real banana   0.377787  0.548355  0.935923  0.387817  0.998565
fake banana   0.460055  0.630140  0.528869  0.779529  0.998317
real onion    0.786250  0.880286  0.828810  0.938693  0.999769
fake onion    0.915132  0.955635  0.962246  0.949214  0.999944
real unknown  0.691238  0.817385  0.718208  0.948473  0.999932
fake unknown  0.148316  0.258284  0.169373  0.544006  0.997368
total         0.682623  0.785535  0.856284  0.771575  0.999016
total(-bg)    0.668434  0.775907  0.849945  0.761237  0.999199
2026-09-22 17:16:43,190 - INFO: Epoch accounting: {'epoch': 136, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11251313, 59393, 56831, 131326, 135498, 97710, 69223, 129031, 204294, 68729, 54013, 33909, 47020, 203267, 138076, 124456, 21991, 113025, 96390, 81563, 54882, 11725, 54607], 'crops_with_class': [202, 35, 28, 37, 33, 27, 23, 27, 32, 35, 24, 12, 17, 51, 36, 20, 20, 33, 37, 37, 27, 14, 21], 'targeted_crops_by_class': [0, 4, 6, 7, 4, 6, 6, 3, 3, 3, 3, 5, 6, 2, 4, 2, 5, 4, 8, 5, 6, 4, 3], 'sampled_scene_counts': [2, 1, 1, 2, 0, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 3, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 2, 0, 1, 1, 0, 0, 2, 0, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 2, 1, 0, 2, 2, 2, 0, 1, 0, 3, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 2, 4, 2, 3, 0, 1, 1, 1, 0, 2, 2, 1, 2, 1, 3, 5, 1, 3, 1, 0, 0, 3, 0, 3, 1, 1, 1, 2, 2, 3, 2, 1, 1, 1, 1, 1, 1, 0, 2, 3, 3, 1, 2, 1, 2, 1, 2, 2, 0, 0, 1, 1, 1, 2, 1, 2, 4], 'learning_rate': 8.31079292830171e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001072866859728249, 'train_segmentation_loss': 0.4324521655862284, 'val_foreground_miou_all22': 0.6684340613281045, 'val_psnr_ref1': 36.766128387451175, 'elapsed_seconds': 327.51683497428894, 'peak_cuda_allocated_gib': 7.512271881103516}

Epoch 137/500 | Batch 10/202 | Rec 0.001071 | Seg 0.464710 | Elapsed 0.2m | ETA 4.0m
Epoch 137/500 | Batch 20/202 | Rec 0.001239 | Seg 0.452514 | Elapsed 0.4m | ETA 3.8m
Epoch 137/500 | Batch 30/202 | Rec 0.001305 | Seg 0.493165 | Elapsed 0.6m | ETA 3.6m
Epoch 137/500 | Batch 40/202 | Rec 0.001328 | Seg 0.504298 | Elapsed 0.8m | ETA 3.4m
Epoch 137/500 | Batch 50/202 | Rec 0.001327 | Seg 0.508438 | Elapsed 1.0m | ETA 3.2m
Epoch 137/500 | Batch 60/202 | Rec 0.001326 | Seg 0.521270 | Elapsed 1.2m | ETA 3.0m
Epoch 137/500 | Batch 70/202 | Rec 0.001291 | Seg 0.507671 | Elapsed 1.5m | ETA 2.8m
Epoch 137/500 | Batch 80/202 | Rec 0.001309 | Seg 0.509695 | Elapsed 1.7m | ETA 2.5m
Epoch 137/500 | Batch 90/202 | Rec 0.001324 | Seg 0.505798 | Elapsed 1.9m | ETA 2.3m
Epoch 137/500 | Batch 100/202 | Rec 0.001303 | Seg 0.497607 | Elapsed 2.1m | ETA 2.1m
Epoch 137/500 | Batch 110/202 | Rec 0.001283 | Seg 0.489922 | Elapsed 2.3m | ETA 1.9m
Epoch 137/500 | Batch 120/202 | Rec 0.001252 | Seg 0.477571 | Elapsed 2.5m | ETA 1.7m
Epoch 137/500 | Batch 130/202 | Rec 0.001230 | Seg 0.471553 | Elapsed 2.7m | ETA 1.5m
Epoch 137/500 | Batch 140/202 | Rec 0.001214 | Seg 0.469227 | Elapsed 2.9m | ETA 1.3m
Epoch 137/500 | Batch 150/202 | Rec 0.001202 | Seg 0.467474 | Elapsed 3.1m | ETA 1.1m
Epoch 137/500 | Batch 160/202 | Rec 0.001195 | Seg 0.458756 | Elapsed 3.3m | ETA 0.9m
Epoch 137/500 | Batch 170/202 | Rec 0.001186 | Seg 0.459897 | Elapsed 3.5m | ETA 0.7m
Epoch 137/500 | Batch 180/202 | Rec 0.001168 | Seg 0.453398 | Elapsed 3.7m | ETA 0.5m
Epoch 137/500 | Batch 190/202 | Rec 0.001171 | Seg 0.459307 | Elapsed 3.9m | ETA 0.2m
Epoch 137/500 | Batch 200/202 | Rec 0.001171 | Seg 0.458842 | Elapsed 4.2m | ETA 0.0m
Epoch 137/500 | Batch 202/202 | Rec 0.001173 | Seg 0.462000 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:20:55,181 - INFO: Rec loss: 0.0011731128608588922
2026-09-22 17:20:55,181 - INFO: Seg loss: 0.4620001963754692
2026-09-22 17:20:55,181 - INFO: λ_rec: 1
2026-09-22 17:20:55,181 - INFO: λ_seg: 0.0001
2026-09-22 17:22:09,251 - INFO: -------------------Epoch: 137------------------------
2026-09-22 17:22:09,255 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.206237  0.967481  0.000249
2026-09-22 17:22:09,262 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994902  0.997395  0.996109  0.998783  0.995128
real potato   0.799044  0.888249  0.983734  0.809742  0.999756
fake potato   0.909274  0.952432  0.960392  0.944700  0.999931
real apple    0.695650  0.820462  0.908023  0.748386  0.998870
fake apple    0.583446  0.736885  0.969793  0.594245  0.998398
real orange   0.517273  0.681801  0.989427  0.520148  0.999360
fake orange   0.786468  0.880423  0.806374  0.969566  0.999246
real grape    0.693934  0.819267  0.854704  0.786743  0.999276
fake grape    0.844253  0.915500  0.927863  0.903560  0.999383
real lemon    0.425117  0.596557  0.552568  0.648273  0.998970
fake lemon    0.803157  0.890785  0.982856  0.814569  0.999578
real avocado  0.821057  0.901687  0.895675  0.907882  0.999816
fake avocado  0.311026  0.474441  0.998772  0.311145  0.999175
real pepper   0.748517  0.856123  0.854643  0.857709  0.998946
fake pepper   0.865732  0.927985  0.947987  0.908905  0.999664
real plant    0.839529  0.912715  0.923453  0.902322  0.998275
fake plant    0.686772  0.814254  0.748473  0.892830  0.999676
real banana   0.485032  0.653183  0.943561  0.499525  0.998808
fake banana   0.611156  0.758605  0.705354  0.820670  0.999039
real onion    0.746784  0.854989  0.867141  0.843270  0.999742
fake onion    0.772886  0.871846  0.796045  0.963724  0.999821
real unknown  0.629032  0.772229  0.660122  0.930343  0.999912
fake unknown  0.119655  0.213698  0.141483  0.436798  0.997292
total         0.682161  0.790935  0.844111  0.783210  0.999046
total(-bg)    0.667945  0.781551  0.837202  0.773412  0.999224
2026-09-22 17:22:09,779 - INFO: Epoch accounting: {'epoch': 137, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11116435, 53104, 67523, 163969, 119784, 82245, 73335, 133327, 224224, 88627, 76758, 34638, 26562, 243869, 151914, 204084, 15560, 97120, 96105, 59409, 52687, 9321, 47672], 'crops_with_class': [202, 32, 33, 39, 32, 27, 27, 25, 43, 37, 32, 11, 11, 60, 34, 24, 16, 28, 34, 32, 25, 11, 18], 'targeted_crops_by_class': [0, 5, 2, 6, 2, 3, 4, 2, 8, 5, 3, 2, 5, 3, 6, 8, 5, 6, 4, 1, 5, 5, 5], 'sampled_scene_counts': [1, 1, 1, 2, 1, 1, 1, 0, 1, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 2, 3, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 1, 2, 2, 3, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 1, 2, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 2, 2, 2, 2, 1, 3, 3, 0, 1, 1, 1, 1, 0, 0, 2, 2, 1, 1, 2, 1, 0, 5, 1, 1, 0, 3, 1, 3, 2, 0, 0, 1, 1, 3, 2, 4, 2, 0, 2, 3, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 0, 2, 1, 3, 5, 1, 1, 1, 1, 3, 2, 1, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0], 'learning_rate': 8.287221456817867e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0011731128608588922, 'train_segmentation_loss': 0.4620001963754692, 'val_foreground_miou_all22': 0.6679452029941454, 'val_psnr_ref1': 36.20623748779297, 'elapsed_seconds': 326.58086133003235, 'peak_cuda_allocated_gib': 7.512271881103516}

Epoch 138/500 | Batch 10/202 | Rec 0.001064 | Seg 0.376946 | Elapsed 0.2m | ETA 4.0m
Epoch 138/500 | Batch 20/202 | Rec 0.000967 | Seg 0.355140 | Elapsed 0.4m | ETA 3.8m
Epoch 138/500 | Batch 30/202 | Rec 0.001093 | Seg 0.399333 | Elapsed 0.6m | ETA 3.6m
Epoch 138/500 | Batch 40/202 | Rec 0.001134 | Seg 0.396079 | Elapsed 0.8m | ETA 3.4m
Epoch 138/500 | Batch 50/202 | Rec 0.001106 | Seg 0.403957 | Elapsed 1.0m | ETA 3.2m
Epoch 138/500 | Batch 60/202 | Rec 0.001118 | Seg 0.423894 | Elapsed 1.3m | ETA 3.0m
Epoch 138/500 | Batch 70/202 | Rec 0.001064 | Seg 0.408051 | Elapsed 1.5m | ETA 2.8m
Epoch 138/500 | Batch 80/202 | Rec 0.001070 | Seg 0.412175 | Elapsed 1.7m | ETA 2.6m
Epoch 138/500 | Batch 90/202 | Rec 0.001065 | Seg 0.403412 | Elapsed 1.9m | ETA 2.4m
Epoch 138/500 | Batch 100/202 | Rec 0.001096 | Seg 0.415367 | Elapsed 2.1m | ETA 2.1m
Epoch 138/500 | Batch 110/202 | Rec 0.001077 | Seg 0.416958 | Elapsed 2.3m | ETA 1.9m
Epoch 138/500 | Batch 120/202 | Rec 0.001082 | Seg 0.411046 | Elapsed 2.5m | ETA 1.7m
Epoch 138/500 | Batch 130/202 | Rec 0.001088 | Seg 0.413501 | Elapsed 2.7m | ETA 1.5m
Epoch 138/500 | Batch 140/202 | Rec 0.001088 | Seg 0.415393 | Elapsed 2.9m | ETA 1.3m
Epoch 138/500 | Batch 150/202 | Rec 0.001091 | Seg 0.410518 | Elapsed 3.1m | ETA 1.1m
Epoch 138/500 | Batch 160/202 | Rec 0.001084 | Seg 0.412375 | Elapsed 3.4m | ETA 0.9m
Epoch 138/500 | Batch 170/202 | Rec 0.001081 | Seg 0.410294 | Elapsed 3.6m | ETA 0.7m
Epoch 138/500 | Batch 180/202 | Rec 0.001071 | Seg 0.406329 | Elapsed 3.8m | ETA 0.5m
Epoch 138/500 | Batch 190/202 | Rec 0.001068 | Seg 0.405404 | Elapsed 4.0m | ETA 0.3m
Epoch 138/500 | Batch 200/202 | Rec 0.001063 | Seg 0.402312 | Elapsed 4.2m | ETA 0.0m
Epoch 138/500 | Batch 202/202 | Rec 0.001064 | Seg 0.403629 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:26:23,721 - INFO: Rec loss: 0.0010635970515662362
2026-09-22 17:26:23,721 - INFO: Seg loss: 0.4036288124573703
2026-09-22 17:26:23,721 - INFO: λ_rec: 1
2026-09-22 17:26:23,721 - INFO: λ_seg: 0.0001
2026-09-22 17:27:37,788 - INFO: -------------------Epoch: 138------------------------
2026-09-22 17:27:37,792 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.322537  0.967532  0.000241
2026-09-22 17:27:37,799 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994505  0.997195  0.995472  0.999025  0.994745
real potato   0.885225  0.939069  0.977251  0.903851  0.999860
fake potato   0.943231  0.970737  0.992343  0.950147  0.999958
real apple    0.524551  0.688093  0.985247  0.528704  0.998347
fake apple    0.669073  0.801681  0.911812  0.715365  0.998664
real orange   0.526170  0.689484  1.000000  0.526170  0.999376
fake orange   0.778702  0.875535  0.809847  0.952937  0.999225
real grape    0.416307  0.587830  0.779038  0.472046  0.998618
fake grape    0.715152  0.833872  0.821313  0.846925  0.998752
real lemon    0.123108  0.219186  0.366849  0.156323  0.998691
fake lemon    0.787512  0.881077  0.999634  0.787739  0.999550
real avocado  0.819985  0.901040  0.913168  0.889327  0.999819
fake avocado  0.248505  0.398052  0.991371  0.249044  0.999099
real pepper   0.724140  0.839952  0.834913  0.845153  0.998822
fake pepper   0.851355  0.919660  0.992511  0.856859  0.999643
real plant    0.818482  0.900132  0.901601  0.898767  0.998006
fake plant    0.781407  0.877242  0.860860  0.894363  0.999801
real banana   0.453728  0.624183  0.958644  0.462787  0.998748
fake banana   0.479353  0.648010  0.533133  0.826145  0.998349
real onion    0.760342  0.863807  0.805551  0.931262  0.999735
fake onion    0.924899  0.960935  0.978446  0.944135  0.999952
real unknown  0.688854  0.815715  0.784832  0.849237  0.999939
fake unknown  0.162894  0.280120  0.177574  0.663347  0.997128
total         0.655543  0.761418  0.842235  0.745637  0.998906
total(-bg)    0.640135  0.750701  0.835270  0.734120  0.999095
2026-09-22 17:27:38,312 - INFO: Epoch accounting: {'epoch': 138, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11333342, 36823, 50658, 136027, 156769, 88646, 56428, 134860, 206653, 68304, 51137, 43665, 36936, 211765, 122095, 135297, 22053, 63654, 56259, 105676, 62047, 7148, 52030], 'crops_with_class': [202, 20, 25, 31, 38, 29, 17, 24, 39, 30, 24, 14, 14, 58, 29, 20, 20, 21, 28, 40, 28, 9, 22], 'targeted_crops_by_class': [0, 2, 2, 5, 3, 4, 4, 3, 4, 6, 4, 3, 6, 4, 9, 4, 2, 1, 5, 6, 4, 2, 5], 'sampled_scene_counts': [2, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 2, 1, 1, 0, 2, 2, 0, 2, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 2, 1, 0, 0, 2, 1, 0, 3, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 2, 1, 1, 0, 1, 2, 1, 2, 3, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 3, 3, 1, 0, 1, 0, 1, 0, 1, 0, 3, 2, 2, 0, 2, 1, 1, 0, 1, 1, 2, 1, 0, 1, 0, 1, 3, 1, 1, 2, 3, 2, 1, 2, 1, 1, 1, 0, 2, 3, 2, 1, 2, 0, 3, 0, 1, 1, 3, 3, 2, 0, 2, 1, 0, 2, 1, 1, 1, 2, 3, 0, 0, 0, 2, 1, 0, 1, 1, 0, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 2], 'learning_rate': 8.26352070493813e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010635970515662362, 'train_segmentation_loss': 0.4036288124573703, 'val_foreground_miou_all22': 0.6401353183641697, 'val_psnr_ref1': 36.32253677368164, 'elapsed_seconds': 328.52501821517944, 'peak_cuda_allocated_gib': 7.511783599853516}

Epoch 139/500 | Batch 10/202 | Rec 0.001016 | Seg 0.352708 | Elapsed 0.2m | ETA 4.1m
Epoch 139/500 | Batch 20/202 | Rec 0.000989 | Seg 0.387780 | Elapsed 0.4m | ETA 3.9m
Epoch 139/500 | Batch 30/202 | Rec 0.000920 | Seg 0.370787 | Elapsed 0.6m | ETA 3.7m
Epoch 139/500 | Batch 40/202 | Rec 0.000949 | Seg 0.377031 | Elapsed 0.9m | ETA 3.5m
Epoch 139/500 | Batch 50/202 | Rec 0.000957 | Seg 0.385541 | Elapsed 1.1m | ETA 3.2m
Epoch 139/500 | Batch 60/202 | Rec 0.000947 | Seg 0.376072 | Elapsed 1.3m | ETA 3.0m
Epoch 139/500 | Batch 70/202 | Rec 0.000999 | Seg 0.403605 | Elapsed 1.5m | ETA 2.8m
Epoch 139/500 | Batch 80/202 | Rec 0.001030 | Seg 0.427964 | Elapsed 1.7m | ETA 2.6m
Epoch 139/500 | Batch 90/202 | Rec 0.001050 | Seg 0.430544 | Elapsed 1.9m | ETA 2.4m
Epoch 139/500 | Batch 100/202 | Rec 0.001067 | Seg 0.427772 | Elapsed 2.1m | ETA 2.1m
Epoch 139/500 | Batch 110/202 | Rec 0.001048 | Seg 0.418795 | Elapsed 2.3m | ETA 1.9m
Epoch 139/500 | Batch 120/202 | Rec 0.001032 | Seg 0.416244 | Elapsed 2.5m | ETA 1.7m
Epoch 139/500 | Batch 130/202 | Rec 0.001033 | Seg 0.421807 | Elapsed 2.7m | ETA 1.5m
Epoch 139/500 | Batch 140/202 | Rec 0.001032 | Seg 0.420021 | Elapsed 2.9m | ETA 1.3m
Epoch 139/500 | Batch 150/202 | Rec 0.001018 | Seg 0.418631 | Elapsed 3.1m | ETA 1.1m
Epoch 139/500 | Batch 160/202 | Rec 0.001015 | Seg 0.413400 | Elapsed 3.4m | ETA 0.9m
Epoch 139/500 | Batch 170/202 | Rec 0.001004 | Seg 0.407526 | Elapsed 3.6m | ETA 0.7m
Epoch 139/500 | Batch 180/202 | Rec 0.001013 | Seg 0.403549 | Elapsed 3.8m | ETA 0.5m
Epoch 139/500 | Batch 190/202 | Rec 0.001023 | Seg 0.409525 | Elapsed 4.0m | ETA 0.3m
Epoch 139/500 | Batch 200/202 | Rec 0.001027 | Seg 0.407783 | Elapsed 4.2m | ETA 0.0m
Epoch 139/500 | Batch 202/202 | Rec 0.001027 | Seg 0.408659 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:31:51,618 - INFO: Rec loss: 0.001027443711899479
2026-09-22 17:31:51,618 - INFO: Seg loss: 0.40865934422553174
2026-09-22 17:31:51,618 - INFO: λ_rec: 1
2026-09-22 17:31:51,618 - INFO: λ_seg: 0.0001
2026-09-22 17:33:05,806 - INFO: -------------------Epoch: 139------------------------
2026-09-22 17:33:05,810 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.794007  0.967607  0.000217
2026-09-22 17:33:05,816 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995038  0.997463  0.996199  0.998829  0.995258
real potato   0.897577  0.945974  0.933573  0.958812  0.999869
fake potato   0.935418  0.966582  0.968461  0.964809  0.999951
real apple    0.667623  0.800640  0.996640  0.669129  0.998851
fake apple    0.752216  0.858538  0.936962  0.792313  0.999015
real orange   0.483927  0.652180  0.982747  0.488073  0.999314
fake orange   0.754946  0.860315  0.770346  0.974203  0.999095
real grape    0.595508  0.746432  0.878189  0.649127  0.999079
fake grape    0.817532  0.899557  0.951255  0.853277  0.999296
real lemon    0.297914  0.459016  0.510324  0.417164  0.998845
fake lemon    0.813765  0.897272  0.993952  0.817815  0.999604
real avocado  0.811997  0.896195  0.840230  0.960263  0.999793
fake avocado  0.448738  0.619445  1.000000  0.448738  0.999340
real pepper   0.803842  0.891205  0.910452  0.872852  0.999221
fake pepper   0.883361  0.938019  0.926187  0.950259  0.999701
real plant    0.835977  0.910612  0.901861  0.919636  0.998195
fake plant    0.812500  0.896502  0.903446  0.889762  0.999837
real banana   0.421775  0.593265  0.966570  0.428018  0.998681
fake banana   0.528933  0.691850  0.593091  0.830209  0.998640
real onion    0.794399  0.885371  0.837602  0.939031  0.999780
fake onion    0.834523  0.909749  0.863725  0.961064  0.999880
real unknown  0.620063  0.765432  0.643880  0.943702  0.999908
fake unknown  0.199113  0.332060  0.231762  0.585657  0.998015
total         0.695943  0.800594  0.849454  0.796206  0.999094
total(-bg)    0.682347  0.791646  0.842784  0.786996  0.999269
2026-09-22 17:33:06,484 - INFO: Epoch accounting: {'epoch': 139, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11304144, 57143, 61987, 126686, 148441, 86052, 61375, 173576, 195455, 84390, 67829, 60348, 46802, 224585, 101211, 107016, 29688, 57284, 52583, 82356, 62441, 5973, 40907], 'crops_with_class': [202, 31, 27, 36, 39, 23, 23, 35, 37, 33, 26, 20, 18, 51, 30, 16, 25, 16, 28, 38, 26, 7, 19], 'targeted_crops_by_class': [0, 3, 2, 2, 4, 5, 2, 6, 4, 4, 4, 7, 5, 3, 2, 3, 3, 4, 2, 11, 6, 4, 6], 'sampled_scene_counts': [1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 3, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 3, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 0, 0, 1, 0, 1, 2, 2, 0, 2, 2, 1, 3, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 2, 3, 2, 2, 1, 3, 0, 1, 2, 1, 0, 3, 2, 5, 1, 1, 0, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 3, 1, 3, 0, 2, 1, 2, 1, 0, 0, 1, 2, 0, 0, 2, 0, 3, 1, 1, 0, 3, 1, 2, 2, 1, 4, 1, 0, 1, 3, 1, 1, 1, 0, 2, 3, 1, 1, 1, 0, 1, 1, 0, 2, 2, 3], 'learning_rate': 8.239691608327601e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.001027443711899479, 'train_segmentation_loss': 0.40865934422553174, 'val_foreground_miou_all22': 0.6823474929513432, 'val_psnr_ref1': 36.79400741577148, 'elapsed_seconds': 328.1652545928955, 'peak_cuda_allocated_gib': 7.509288787841797}

Epoch 140/500 | Batch 10/202 | Rec 0.000895 | Seg 0.273833 | Elapsed 0.2m | ETA 4.0m
Epoch 140/500 | Batch 20/202 | Rec 0.001019 | Seg 0.364982 | Elapsed 0.4m | ETA 3.7m
Epoch 140/500 | Batch 30/202 | Rec 0.000977 | Seg 0.375661 | Elapsed 0.6m | ETA 3.6m
Epoch 140/500 | Batch 40/202 | Rec 0.000980 | Seg 0.396547 | Elapsed 0.8m | ETA 3.4m
Epoch 140/500 | Batch 50/202 | Rec 0.001025 | Seg 0.409986 | Elapsed 1.0m | ETA 3.2m
Epoch 140/500 | Batch 60/202 | Rec 0.001024 | Seg 0.408359 | Elapsed 1.2m | ETA 2.9m
Epoch 140/500 | Batch 70/202 | Rec 0.001053 | Seg 0.427115 | Elapsed 1.5m | ETA 2.7m
Epoch 140/500 | Batch 80/202 | Rec 0.001044 | Seg 0.428121 | Elapsed 1.7m | ETA 2.5m
Epoch 140/500 | Batch 90/202 | Rec 0.001024 | Seg 0.410113 | Elapsed 1.9m | ETA 2.3m
Epoch 140/500 | Batch 100/202 | Rec 0.001025 | Seg 0.414500 | Elapsed 2.1m | ETA 2.1m
Epoch 140/500 | Batch 110/202 | Rec 0.001017 | Seg 0.397271 | Elapsed 2.3m | ETA 1.9m
Epoch 140/500 | Batch 120/202 | Rec 0.001045 | Seg 0.411267 | Elapsed 2.5m | ETA 1.7m
Epoch 140/500 | Batch 130/202 | Rec 0.001048 | Seg 0.410104 | Elapsed 2.7m | ETA 1.5m
Epoch 140/500 | Batch 140/202 | Rec 0.001075 | Seg 0.409305 | Elapsed 2.9m | ETA 1.3m
Epoch 140/500 | Batch 150/202 | Rec 0.001065 | Seg 0.411167 | Elapsed 3.1m | ETA 1.1m
Epoch 140/500 | Batch 160/202 | Rec 0.001057 | Seg 0.408907 | Elapsed 3.3m | ETA 0.9m
Epoch 140/500 | Batch 170/202 | Rec 0.001060 | Seg 0.415602 | Elapsed 3.5m | ETA 0.7m
Epoch 140/500 | Batch 180/202 | Rec 0.001059 | Seg 0.412918 | Elapsed 3.7m | ETA 0.5m
Epoch 140/500 | Batch 190/202 | Rec 0.001058 | Seg 0.413304 | Elapsed 3.9m | ETA 0.2m
Epoch 140/500 | Batch 200/202 | Rec 0.001053 | Seg 0.408959 | Elapsed 4.1m | ETA 0.0m
Epoch 140/500 | Batch 202/202 | Rec 0.001054 | Seg 0.408038 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:37:17,600 - INFO: Rec loss: 0.0010539376668777262
2026-09-22 17:37:17,600 - INFO: Seg loss: 0.4080384130598885
2026-09-22 17:37:17,600 - INFO: λ_rec: 1
2026-09-22 17:37:17,600 - INFO: λ_seg: 0.0001
2026-09-22 17:38:31,186 - INFO: -------------------Epoch: 140------------------------
2026-09-22 17:38:31,190 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.672416  0.968585  0.000222
2026-09-22 17:38:31,198 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994742  0.997314  0.995724  0.999009  0.994973
real potato   0.749016  0.856451  0.994103  0.752359  0.999698
fake potato   0.952391  0.975565  0.992203  0.959573  0.999965
real apple    0.653938  0.790716  0.905023  0.702123  0.998718
fake apple    0.742762  0.852347  0.958790  0.767257  0.998997
real orange   0.728380  0.842798  0.933080  0.768527  0.999622
fake orange   0.839001  0.912403  0.865176  0.965196  0.999470
real grape    0.589421  0.741630  0.672069  0.827377  0.998797
fake grape    0.713481  0.832736  0.948837  0.742029  0.998898
real lemon    0.365466  0.535249  0.493535  0.584783  0.998807
fake lemon    0.815554  0.898358  0.957256  0.846376  0.999595
real avocado  0.818664  0.900242  0.889049  0.911823  0.999812
fake avocado  0.534105  0.696263  0.976081  0.541188  0.999435
real pepper   0.757476  0.861955  0.848507  0.875939  0.998974
fake pepper   0.866591  0.928478  0.988082  0.875744  0.999679
real plant    0.843886  0.915285  0.960947  0.873856  0.998383
fake plant    0.795413  0.886000  0.850865  0.924271  0.999811
real banana   0.331502  0.497899  0.960598  0.336072  0.998477
fake banana   0.567964  0.724411  0.634032  0.844973  0.998818
real onion    0.838939  0.912366  0.906484  0.918426  0.999841
fake onion    0.950459  0.974550  0.999238  0.951149  0.999969
real unknown  0.364407  0.534122  0.366477  0.984733  0.999725
fake unknown  0.187579  0.315858  0.228210  0.513039  0.998128
total         0.695702  0.799261  0.840190  0.802862  0.999069
total(-bg)    0.682109  0.790258  0.833120  0.793946  0.999255
2026-09-22 17:38:31,708 - INFO: Epoch accounting: {'epoch': 140, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11276589, 60435, 51560, 119065, 153111, 68725, 74673, 142419, 214115, 74091, 59165, 32492, 50992, 233312, 142065, 116727, 16404, 77203, 64783, 91132, 64035, 11601, 43578], 'crops_with_class': [202, 32, 25, 29, 38, 21, 23, 28, 38, 31, 27, 11, 17, 59, 29, 14, 19, 22, 31, 37, 27, 11, 21], 'targeted_crops_by_class': [0, 5, 3, 3, 4, 4, 6, 3, 8, 5, 3, 1, 4, 7, 10, 3, 1, 6, 4, 5, 6, 7, 6], 'sampled_scene_counts': [0, 1, 2, 1, 2, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 3, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 3, 1, 1, 0, 0, 1, 2, 2, 0, 1, 1, 3, 2, 2, 2, 1, 1, 0, 2, 3, 2, 1, 0, 2, 0, 1, 1, 2, 0, 0, 1, 0, 1, 2, 1, 1, 3, 0, 4, 1, 5, 1, 2, 1, 0, 0, 0, 0, 1, 2, 0, 4, 2, 0, 1, 2, 0, 1, 1, 1, 1, 1, 2, 2, 3, 2, 1, 3, 1, 3, 1, 1, 2, 0, 1, 1, 1, 1, 5, 2, 1], 'learning_rate': 8.215735107718212e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010539376668777262, 'train_segmentation_loss': 0.4080384130598885, 'val_foreground_miou_all22': 0.6821088513639735, 'val_psnr_ref1': 36.672416076660156, 'elapsed_seconds': 325.2165558338165, 'peak_cuda_allocated_gib': 7.511539459228516}

Epoch 141/500 | Batch 10/202 | Rec 0.001191 | Seg 0.449661 | Elapsed 0.2m | ETA 4.0m
Epoch 141/500 | Batch 20/202 | Rec 0.001102 | Seg 0.415316 | Elapsed 0.4m | ETA 3.8m
Epoch 141/500 | Batch 30/202 | Rec 0.001166 | Seg 0.431244 | Elapsed 0.6m | ETA 3.6m
Epoch 141/500 | Batch 40/202 | Rec 0.001066 | Seg 0.387987 | Elapsed 0.8m | ETA 3.4m
Epoch 141/500 | Batch 50/202 | Rec 0.001105 | Seg 0.403094 | Elapsed 1.0m | ETA 3.2m
Epoch 141/500 | Batch 60/202 | Rec 0.001091 | Seg 0.431140 | Elapsed 1.2m | ETA 3.0m
Epoch 141/500 | Batch 70/202 | Rec 0.001095 | Seg 0.428685 | Elapsed 1.4m | ETA 2.7m
Epoch 141/500 | Batch 80/202 | Rec 0.001055 | Seg 0.418290 | Elapsed 1.7m | ETA 2.5m
Epoch 141/500 | Batch 90/202 | Rec 0.001034 | Seg 0.409286 | Elapsed 1.9m | ETA 2.3m
Epoch 141/500 | Batch 100/202 | Rec 0.001019 | Seg 0.409149 | Elapsed 2.1m | ETA 2.1m
Epoch 141/500 | Batch 110/202 | Rec 0.001044 | Seg 0.410120 | Elapsed 2.3m | ETA 1.9m
Epoch 141/500 | Batch 120/202 | Rec 0.001028 | Seg 0.411395 | Elapsed 2.5m | ETA 1.7m
Epoch 141/500 | Batch 130/202 | Rec 0.001031 | Seg 0.413694 | Elapsed 2.7m | ETA 1.5m
Epoch 141/500 | Batch 140/202 | Rec 0.001020 | Seg 0.406523 | Elapsed 2.9m | ETA 1.3m
Epoch 141/500 | Batch 150/202 | Rec 0.001008 | Seg 0.402830 | Elapsed 3.1m | ETA 1.1m
Epoch 141/500 | Batch 160/202 | Rec 0.001004 | Seg 0.398553 | Elapsed 3.3m | ETA 0.9m
Epoch 141/500 | Batch 170/202 | Rec 0.001002 | Seg 0.398202 | Elapsed 3.5m | ETA 0.7m
Epoch 141/500 | Batch 180/202 | Rec 0.001005 | Seg 0.403289 | Elapsed 3.7m | ETA 0.5m
Epoch 141/500 | Batch 190/202 | Rec 0.001005 | Seg 0.405806 | Elapsed 4.0m | ETA 0.2m
Epoch 141/500 | Batch 200/202 | Rec 0.001015 | Seg 0.410958 | Elapsed 4.2m | ETA 0.0m
Epoch 141/500 | Batch 202/202 | Rec 0.001013 | Seg 0.410253 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:42:43,922 - INFO: Rec loss: 0.0010134500323444383
2026-09-22 17:42:43,923 - INFO: Seg loss: 0.4102525204641394
2026-09-22 17:42:43,923 - INFO: λ_rec: 1
2026-09-22 17:42:43,923 - INFO: λ_seg: 0.0001
2026-09-22 17:43:57,565 - INFO: -------------------Epoch: 141------------------------
2026-09-22 17:43:57,569 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.273965  0.968198  0.000246
2026-09-22 17:43:57,575 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995172  0.997530  0.996242  0.998922  0.995387
real potato   0.193803  0.324655  0.999342  0.193828  0.999035
fake potato   0.093213  0.170515  1.000000  0.093213  0.999339
real apple    0.571589  0.727352  0.732359  0.722512  0.998132
fake apple    0.796197  0.886486  0.903944  0.869787  0.999159
real orange   0.348706  0.517058  0.980912  0.351088  0.999136
fake orange   0.706331  0.827846  0.715746  0.981718  0.998831
real grape    0.262658  0.416005  0.894381  0.271066  0.998411
fake grape    0.696838  0.821288  0.763825  0.888215  0.998571
real lemon    0.147698  0.257331  0.247366  0.268242  0.998181
fake lemon    0.817882  0.899769  0.924065  0.876812  0.999587
real avocado  0.684771  0.812846  0.710236  0.950246  0.999594
fake avocado  0.381394  0.552146  0.987837  0.383193  0.999256
real pepper   0.759335  0.863157  0.905621  0.824587  0.999044
fake pepper   0.666792  0.800042  0.971993  0.679854  0.999190
real plant    0.811546  0.895920  0.880415  0.912085  0.997881
fake plant    0.757107  0.861716  0.911834  0.816909  0.999791
real banana   0.020433  0.040035  0.286878  0.021527  0.997681
fake banana   0.399130  0.570494  0.448413  0.784091  0.997829
real onion    0.544968  0.705426  0.819767  0.619152  0.999533
fake onion    0.840730  0.913425  0.873373  0.957436  0.999886
real unknown  0.765812  0.867327  0.880157  0.854962  0.999958
fake unknown  0.118081  0.211185  0.137492  0.455451  0.997134
total         0.538269  0.649546  0.781400  0.642387  0.998719
total(-bg)    0.517501  0.633728  0.771634  0.626181  0.998871
2026-09-22 17:43:58,132 - INFO: Epoch accounting: {'epoch': 141, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11375648, 45293, 55931, 143229, 150492, 76194, 69735, 109068, 134137, 68092, 53170, 33663, 51110, 216943, 154100, 134033, 18429, 85822, 62747, 80342, 50797, 15798, 53499], 'crops_with_class': [202, 25, 26, 39, 33, 27, 26, 21, 31, 30, 22, 13, 19, 54, 35, 19, 19, 23, 26, 35, 26, 15, 23], 'targeted_crops_by_class': [0, 5, 5, 4, 7, 6, 1, 3, 2, 4, 4, 3, 9, 9, 3, 3, 6, 6, 3, 2, 4, 6, 6], 'sampled_scene_counts': [1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 0, 2, 2, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 1, 0, 0, 2, 2, 1, 0, 1, 0, 2, 1, 0, 1, 2, 0, 0, 0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 0, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 1, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 0, 1, 1, 2, 0, 1, 2, 2, 1, 0, 2, 1, 1, 4, 0, 2, 1, 2, 3, 4, 2, 4, 0, 1, 0, 2, 1, 1, 4, 2, 1, 2, 1, 2, 0, 2, 3, 1, 0, 1, 1, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 1, 2, 1, 1, 2, 2, 0, 0, 2, 2, 2], 'learning_rate': 8.191652148871586e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010134500323444383, 'train_segmentation_loss': 0.4102525204641394, 'val_foreground_miou_all22': 0.5175006938063444, 'val_psnr_ref1': 36.273965454101564, 'elapsed_seconds': 326.4156174659729, 'peak_cuda_allocated_gib': 7.517520904541016}

Epoch 142/500 | Batch 10/202 | Rec 0.001051 | Seg 0.427923 | Elapsed 0.2m | ETA 3.9m
Epoch 142/500 | Batch 20/202 | Rec 0.000964 | Seg 0.390091 | Elapsed 0.4m | ETA 3.8m
Epoch 142/500 | Batch 30/202 | Rec 0.000958 | Seg 0.390486 | Elapsed 0.6m | ETA 3.6m
Epoch 142/500 | Batch 40/202 | Rec 0.000952 | Seg 0.370353 | Elapsed 0.8m | ETA 3.4m
Epoch 142/500 | Batch 50/202 | Rec 0.000968 | Seg 0.374165 | Elapsed 1.0m | ETA 3.1m
Epoch 142/500 | Batch 60/202 | Rec 0.000959 | Seg 0.377391 | Elapsed 1.2m | ETA 2.9m
Epoch 142/500 | Batch 70/202 | Rec 0.000937 | Seg 0.376464 | Elapsed 1.4m | ETA 2.7m
Epoch 142/500 | Batch 80/202 | Rec 0.000983 | Seg 0.389093 | Elapsed 1.6m | ETA 2.5m
Epoch 142/500 | Batch 90/202 | Rec 0.000978 | Seg 0.386178 | Elapsed 1.9m | ETA 2.3m
Epoch 142/500 | Batch 100/202 | Rec 0.000961 | Seg 0.381171 | Elapsed 2.1m | ETA 2.1m
Epoch 142/500 | Batch 110/202 | Rec 0.000971 | Seg 0.389539 | Elapsed 2.3m | ETA 1.9m
Epoch 142/500 | Batch 120/202 | Rec 0.000966 | Seg 0.386929 | Elapsed 2.5m | ETA 1.7m
Epoch 142/500 | Batch 130/202 | Rec 0.000975 | Seg 0.395889 | Elapsed 2.7m | ETA 1.5m
Epoch 142/500 | Batch 140/202 | Rec 0.000971 | Seg 0.399719 | Elapsed 2.9m | ETA 1.3m
Epoch 142/500 | Batch 150/202 | Rec 0.000978 | Seg 0.403539 | Elapsed 3.1m | ETA 1.1m
Epoch 142/500 | Batch 160/202 | Rec 0.000979 | Seg 0.404420 | Elapsed 3.3m | ETA 0.9m
Epoch 142/500 | Batch 170/202 | Rec 0.001007 | Seg 0.422139 | Elapsed 3.5m | ETA 0.7m
Epoch 142/500 | Batch 180/202 | Rec 0.000997 | Seg 0.418977 | Elapsed 3.7m | ETA 0.5m
Epoch 142/500 | Batch 190/202 | Rec 0.001020 | Seg 0.417565 | Elapsed 3.9m | ETA 0.2m
Epoch 142/500 | Batch 200/202 | Rec 0.001028 | Seg 0.422217 | Elapsed 4.1m | ETA 0.0m
Epoch 142/500 | Batch 202/202 | Rec 0.001032 | Seg 0.422621 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:48:08,947 - INFO: Rec loss: 0.0010318082053759503
2026-09-22 17:48:08,947 - INFO: Seg loss: 0.4226207514062966
2026-09-22 17:48:08,947 - INFO: λ_rec: 1
2026-09-22 17:48:08,948 - INFO: λ_seg: 0.0001
2026-09-22 17:49:22,736 - INFO: -------------------Epoch: 142------------------------
2026-09-22 17:49:22,740 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.863145  0.965638  0.000267
2026-09-22 17:49:22,747 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994706  0.997296  0.995771  0.998927  0.994939
real potato   0.442815  0.613779  0.999712  0.442872  0.999333
fake potato   0.561011  0.718733  0.980804  0.567239  0.999677
real apple    0.686271  0.813901  0.803960  0.824193  0.998700
fake apple    0.669918  0.802288  0.967104  0.685540  0.998725
real orange   0.435775  0.606981  0.967089  0.442334  0.999245
fake orange   0.767221  0.868230  0.780499  0.978307  0.999150
real grape    0.686092  0.813776  0.934015  0.721041  0.999311
fake grape    0.777645  0.874866  0.865851  0.884173  0.999065
real lemon    0.099421  0.180811  0.207174  0.160478  0.998292
fake lemon    0.811105  0.895652  0.975282  0.828128  0.999592
real avocado  0.737743  0.849032  0.783532  0.926601  0.999694
fake avocado  0.262306  0.415565  1.000000  0.262306  0.999117
real pepper   0.701766  0.824700  0.842908  0.807359  0.998745
fake pepper   0.747153  0.855231  0.932910  0.789578  0.999363
real plant    0.839032  0.912422  0.921500  0.903618  0.998266
fake plant    0.609957  0.757681  0.749906  0.765721  0.999610
real banana   0.074163  0.138071  0.855375  0.075105  0.997893
fake banana   0.400649  0.572045  0.442663  0.808477  0.997775
real onion    0.646449  0.785214  0.814781  0.757811  0.999626
fake onion    0.821362  0.901871  0.855192  0.954051  0.999869
real unknown  0.715385  0.834032  0.728114  0.976145  0.999938
fake unknown  0.132577  0.234078  0.154155  0.486418  0.997318
total         0.592197  0.707228  0.806882  0.697670  0.998837
total(-bg)    0.573901  0.694044  0.798297  0.683977  0.999014
2026-09-22 17:49:23,288 - INFO: Epoch accounting: {'epoch': 142, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11196774, 47378, 57810, 99286, 152873, 113722, 92360, 148502, 226789, 49611, 34385, 64575, 48318, 228664, 116184, 204364, 34049, 63198, 73975, 83197, 63329, 9640, 29289], 'crops_with_class': [202, 29, 28, 28, 39, 29, 31, 28, 45, 23, 14, 22, 17, 58, 30, 21, 20, 24, 27, 34, 27, 12, 17], 'targeted_crops_by_class': [0, 7, 5, 2, 5, 4, 10, 5, 7, 2, 1, 7, 4, 6, 5, 5, 5, 6, 2, 3, 6, 6, 3], 'sampled_scene_counts': [0, 0, 1, 1, 0, 3, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 2, 3, 2, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 1, 0, 2, 1, 2, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 2, 1, 1, 2, 1, 0, 3, 1, 0, 1, 2, 1, 0, 3, 3, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 2, 1, 0, 1, 0, 1, 0, 2, 1, 0, 6, 1, 3, 2, 1, 2, 0, 0, 2, 4, 3, 1, 2, 1, 1, 2, 2, 1, 0, 0, 3, 3, 1, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 3, 3, 3, 1, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 2, 0, 2, 3, 2, 1, 0, 1, 3, 0, 2, 1, 4, 1, 4, 1, 1, 2, 2, 1, 1, 1, 1, 1, 0, 2, 3, 1, 0, 0], 'learning_rate': 8.167443682541706e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010318082053759503, 'train_segmentation_loss': 0.4226207514062966, 'val_foreground_miou_all22': 0.5739006751164079, 'val_psnr_ref1': 35.86314483642578, 'elapsed_seconds': 325.14804577827454, 'peak_cuda_allocated_gib': 7.510440826416016}

Epoch 143/500 | Batch 10/202 | Rec 0.001288 | Seg 0.443002 | Elapsed 0.2m | ETA 4.0m
Epoch 143/500 | Batch 20/202 | Rec 0.001047 | Seg 0.393468 | Elapsed 0.4m | ETA 3.8m
Epoch 143/500 | Batch 30/202 | Rec 0.001006 | Seg 0.378850 | Elapsed 0.6m | ETA 3.6m
Epoch 143/500 | Batch 40/202 | Rec 0.001060 | Seg 0.409115 | Elapsed 0.8m | ETA 3.4m
Epoch 143/500 | Batch 50/202 | Rec 0.001141 | Seg 0.446624 | Elapsed 1.1m | ETA 3.2m
Epoch 143/500 | Batch 60/202 | Rec 0.001096 | Seg 0.439156 | Elapsed 1.3m | ETA 3.0m
Epoch 143/500 | Batch 70/202 | Rec 0.001092 | Seg 0.430622 | Elapsed 1.5m | ETA 2.8m
Epoch 143/500 | Batch 80/202 | Rec 0.001104 | Seg 0.430813 | Elapsed 1.7m | ETA 2.6m
Epoch 143/500 | Batch 90/202 | Rec 0.001122 | Seg 0.431695 | Elapsed 1.9m | ETA 2.3m
Epoch 143/500 | Batch 100/202 | Rec 0.001094 | Seg 0.425590 | Elapsed 2.1m | ETA 2.1m
Epoch 143/500 | Batch 110/202 | Rec 0.001078 | Seg 0.418712 | Elapsed 2.3m | ETA 1.9m
Epoch 143/500 | Batch 120/202 | Rec 0.001083 | Seg 0.414254 | Elapsed 2.5m | ETA 1.7m
Epoch 143/500 | Batch 130/202 | Rec 0.001074 | Seg 0.411992 | Elapsed 2.7m | ETA 1.5m
Epoch 143/500 | Batch 140/202 | Rec 0.001086 | Seg 0.415197 | Elapsed 2.9m | ETA 1.3m
Epoch 143/500 | Batch 150/202 | Rec 0.001078 | Seg 0.409593 | Elapsed 3.1m | ETA 1.1m
Epoch 143/500 | Batch 160/202 | Rec 0.001079 | Seg 0.411596 | Elapsed 3.3m | ETA 0.9m
Epoch 143/500 | Batch 170/202 | Rec 0.001072 | Seg 0.403712 | Elapsed 3.6m | ETA 0.7m
Epoch 143/500 | Batch 180/202 | Rec 0.001066 | Seg 0.403400 | Elapsed 3.8m | ETA 0.5m
Epoch 143/500 | Batch 190/202 | Rec 0.001066 | Seg 0.406838 | Elapsed 4.0m | ETA 0.3m
Epoch 143/500 | Batch 200/202 | Rec 0.001082 | Seg 0.406814 | Elapsed 4.2m | ETA 0.0m
Epoch 143/500 | Batch 202/202 | Rec 0.001081 | Seg 0.406582 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:53:37,181 - INFO: Rec loss: 0.0010810477714144192
2026-09-22 17:53:37,181 - INFO: Seg loss: 0.40658203409154814
2026-09-22 17:53:37,181 - INFO: λ_rec: 1
2026-09-22 17:53:37,181 - INFO: λ_seg: 0.0001
2026-09-22 17:54:51,078 - INFO: -------------------Epoch: 143------------------------
2026-09-22 17:54:51,082 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  36.02033  0.967347  0.000264
2026-09-22 17:54:51,089 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994169  0.997026  0.995285  0.998874  0.994423
real potato   0.629954  0.772924  0.993987  0.632364  0.999556
fake potato   0.680790  0.810035  0.974102  0.693339  0.999763
real apple    0.659085  0.794467  0.876273  0.726714  0.998703
fake apple    0.598224  0.748563  0.955858  0.615220  0.998440
real orange   0.498902  0.665645  0.996537  0.499768  0.999339
fake orange   0.774269  0.872725  0.803425  0.955229  0.999203
real grape    0.558311  0.716511  0.918419  0.587444  0.999030
fake grape    0.786296  0.880315  0.840307  0.924432  0.999071
real lemon    0.119981  0.214210  0.311309  0.163334  0.998592
fake lemon    0.784575  0.879235  0.953392  0.815867  0.999526
real avocado  0.849193  0.918397  0.949352  0.889491  0.999853
fake avocado  0.114391  0.205279  0.981441  0.114639  0.998938
real pepper   0.756749  0.861484  0.837012  0.887535  0.998956
fake pepper   0.838356  0.912021  0.925072  0.899430  0.999587
real plant    0.788814  0.881891  0.937219  0.832820  0.997770
fake plant    0.683170  0.811716  0.762595  0.867715  0.999680
real banana   0.388277  0.559320  0.814358  0.425981  0.998492
fake banana   0.426748  0.598166  0.454812  0.873673  0.997841
real onion    0.787005  0.880759  0.851379  0.912346  0.999777
fake onion    0.909028  0.952296  0.950168  0.954534  0.999940
real unknown  0.858726  0.923944  0.963730  0.887404  0.999977
fake unknown  0.100101  0.181949  0.120049  0.375951  0.997152
total         0.634135  0.740821  0.833308  0.718874  0.998852
total(-bg)    0.617770  0.729175  0.825945  0.706147  0.999054
2026-09-22 17:54:51,624 - INFO: Epoch accounting: {'epoch': 143, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11350080, 45772, 44940, 112805, 105922, 77872, 82056, 172843, 220611, 50979, 58102, 43924, 33356, 186244, 121333, 157051, 36174, 68157, 61888, 94896, 54410, 12498, 46359], 'crops_with_class': [202, 25, 19, 33, 30, 26, 29, 33, 36, 29, 27, 14, 13, 47, 28, 21, 26, 21, 26, 40, 25, 12, 20], 'targeted_crops_by_class': [0, 2, 4, 2, 3, 4, 3, 6, 3, 2, 5, 5, 3, 2, 4, 5, 6, 4, 2, 8, 4, 3, 5], 'sampled_scene_counts': [2, 1, 1, 1, 0, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 3, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 2, 2, 1, 0, 1, 0, 1, 0, 3, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 2, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 1, 2, 0, 2, 3, 4, 1, 2, 0, 4, 0, 1, 0, 1, 2, 2, 2, 1, 1, 3, 2, 2, 1, 0, 1, 0, 2, 1, 3, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 4, 2, 1, 1, 1, 1, 1], 'learning_rate': 8.143110664437366e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0010810477714144192, 'train_segmentation_loss': 0.40658203409154814, 'val_foreground_miou_all22': 0.6177701162738023, 'val_psnr_ref1': 36.02032974243164, 'elapsed_seconds': 328.32926988601685, 'peak_cuda_allocated_gib': 7.506381988525391}

Epoch 144/500 | Batch 10/202 | Rec 0.001057 | Seg 0.433391 | Elapsed 0.2m | ETA 4.0m
Epoch 144/500 | Batch 20/202 | Rec 0.000984 | Seg 0.400257 | Elapsed 0.4m | ETA 3.8m
Epoch 144/500 | Batch 30/202 | Rec 0.000942 | Seg 0.368490 | Elapsed 0.6m | ETA 3.6m
Epoch 144/500 | Batch 40/202 | Rec 0.000985 | Seg 0.397140 | Elapsed 0.8m | ETA 3.4m
Epoch 144/500 | Batch 50/202 | Rec 0.000998 | Seg 0.398159 | Elapsed 1.0m | ETA 3.1m
Epoch 144/500 | Batch 60/202 | Rec 0.000953 | Seg 0.377466 | Elapsed 1.3m | ETA 3.0m
Epoch 144/500 | Batch 70/202 | Rec 0.000947 | Seg 0.377396 | Elapsed 1.5m | ETA 2.7m
Epoch 144/500 | Batch 80/202 | Rec 0.000952 | Seg 0.383851 | Elapsed 1.7m | ETA 2.5m
Epoch 144/500 | Batch 90/202 | Rec 0.000940 | Seg 0.378228 | Elapsed 1.9m | ETA 2.3m
Epoch 144/500 | Batch 100/202 | Rec 0.000958 | Seg 0.385119 | Elapsed 2.1m | ETA 2.1m
Epoch 144/500 | Batch 110/202 | Rec 0.000954 | Seg 0.382916 | Elapsed 2.3m | ETA 1.9m
Epoch 144/500 | Batch 120/202 | Rec 0.000953 | Seg 0.383427 | Elapsed 2.5m | ETA 1.7m
Epoch 144/500 | Batch 130/202 | Rec 0.000950 | Seg 0.384945 | Elapsed 2.7m | ETA 1.5m
Epoch 144/500 | Batch 140/202 | Rec 0.000946 | Seg 0.384636 | Elapsed 2.9m | ETA 1.3m
Epoch 144/500 | Batch 150/202 | Rec 0.000953 | Seg 0.388412 | Elapsed 3.1m | ETA 1.1m
Epoch 144/500 | Batch 160/202 | Rec 0.000965 | Seg 0.390919 | Elapsed 3.3m | ETA 0.9m
Epoch 144/500 | Batch 170/202 | Rec 0.000964 | Seg 0.389296 | Elapsed 3.6m | ETA 0.7m
Epoch 144/500 | Batch 180/202 | Rec 0.000958 | Seg 0.388225 | Elapsed 3.8m | ETA 0.5m
Epoch 144/500 | Batch 190/202 | Rec 0.000967 | Seg 0.391151 | Elapsed 4.0m | ETA 0.3m
Epoch 144/500 | Batch 200/202 | Rec 0.000970 | Seg 0.394678 | Elapsed 4.2m | ETA 0.0m
Epoch 144/500 | Batch 202/202 | Rec 0.000969 | Seg 0.394737 | Elapsed 4.2m | ETA 0.0m

2026-09-22 17:59:05,900 - INFO: Rec loss: 0.0009692786948693142
2026-09-22 17:59:05,901 - INFO: Seg loss: 0.39473698974245847
2026-09-22 17:59:05,901 - INFO: λ_rec: 1
2026-09-22 17:59:05,901 - INFO: λ_seg: 0.0001
2026-09-22 18:00:19,904 - INFO: -------------------Epoch: 144------------------------
2026-09-22 18:00:19,908 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.452255  0.969014  0.000236
2026-09-22 18:00:19,915 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994842  0.997364  0.995988  0.998844  0.995070
real potato   0.706623  0.828046  0.995523  0.708875  0.999648
fake potato   0.783622  0.878637  0.980893  0.795769  0.999840
real apple    0.658662  0.794160  0.897692  0.712119  0.998727
fake apple    0.686048  0.813745  0.970819  0.700493  0.998790
real orange   0.478296  0.647046  0.972590  0.484831  0.999303
fake orange   0.748536  0.856137  0.767952  0.967328  0.999070
real grape    0.490033  0.657701  0.881493  0.524593  0.998860
fake grape    0.798320  0.887801  0.878213  0.897702  0.999161
real lemon    0.164463  0.282423  0.371847  0.227733  0.998640
fake lemon    0.812885  0.896737  0.992215  0.818103  0.999602
real avocado  0.800891  0.889389  0.865465  0.914778  0.999789
fake avocado  0.140226  0.245940  0.972687  0.140780  0.998967
real pepper   0.747008  0.855136  0.864368  0.846196  0.998952
fake pepper   0.890823  0.942210  0.987442  0.901031  0.999737
real plant    0.811028  0.895605  0.901966  0.889431  0.997927
fake plant    0.761133  0.864318  0.809404  0.927339  0.999768
real banana   0.398361  0.569712  0.936898  0.409344  0.998611
fake banana   0.487359  0.655287  0.535515  0.844227  0.998366
real onion    0.796785  0.886851  0.841340  0.937679  0.999784
fake onion    0.929514  0.963420  0.973580  0.953567  0.999954
real unknown  0.599634  0.749666  0.623970  0.938931  0.999900
fake unknown  0.162968  0.280229  0.177264  0.668961  0.997105
total         0.645568  0.753807  0.834571  0.748202  0.998938
total(-bg)    0.629692  0.742736  0.827233  0.736810  0.999114
2026-09-22 18:00:20,420 - INFO: Epoch accounting: {'epoch': 144, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11344791, 57946, 55923, 157070, 133615, 85254, 59714, 184358, 172989, 67446, 63838, 53186, 40043, 194683, 75861, 157801, 27884, 85882, 66200, 68778, 47583, 7877, 29550], 'crops_with_class': [202, 36, 25, 38, 29, 22, 20, 35, 31, 31, 26, 18, 17, 53, 22, 22, 23, 23, 31, 35, 20, 9, 13], 'targeted_crops_by_class': [0, 4, 2, 4, 8, 1, 5, 4, 5, 2, 4, 9, 6, 3, 2, 4, 1, 6, 6, 2, 3, 4, 1], 'sampled_scene_counts': [0, 0, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 3, 0, 1, 1, 2, 0, 1, 1, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 3, 1, 2, 2, 1, 1, 2, 1, 0, 0, 2, 1, 3, 0, 1, 1, 1, 1, 1, 1, 0, 1, 3, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 3, 1, 1, 1, 1, 3, 1, 1, 2, 3, 1, 1, 1, 2, 1, 0, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 0, 0, 2, 2, 1, 1, 0, 1, 1, 0, 3, 0, 2, 1, 1, 4, 1, 2, 1, 2, 1, 2, 1, 1, 0, 1, 1, 4, 1, 3, 0, 1, 1, 0, 1, 1, 1, 0, 1, 2, 0, 1, 1, 4, 2, 2, 1, 3, 1, 0, 1, 1, 1, 1, 1, 1, 2], 'learning_rate': 8.118654055184458e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009692786948693142, 'train_segmentation_loss': 0.39473698974245847, 'val_foreground_miou_all22': 0.6296917542024562, 'val_psnr_ref1': 36.45225524902344, 'elapsed_seconds': 328.78833174705505, 'peak_cuda_allocated_gib': 7.5111846923828125}

Epoch 145/500 | Batch 10/202 | Rec 0.000812 | Seg 0.358441 | Elapsed 0.2m | ETA 4.1m
Epoch 145/500 | Batch 20/202 | Rec 0.000928 | Seg 0.428578 | Elapsed 0.4m | ETA 3.8m
Epoch 145/500 | Batch 30/202 | Rec 0.000985 | Seg 0.413136 | Elapsed 0.6m | ETA 3.6m
Epoch 145/500 | Batch 40/202 | Rec 0.000970 | Seg 0.392112 | Elapsed 0.8m | ETA 3.4m
Epoch 145/500 | Batch 50/202 | Rec 0.001009 | Seg 0.382020 | Elapsed 1.1m | ETA 3.2m
Epoch 145/500 | Batch 60/202 | Rec 0.001028 | Seg 0.400648 | Elapsed 1.3m | ETA 3.0m
Epoch 145/500 | Batch 70/202 | Rec 0.001046 | Seg 0.410005 | Elapsed 1.5m | ETA 2.8m
Epoch 145/500 | Batch 80/202 | Rec 0.001027 | Seg 0.407704 | Elapsed 1.7m | ETA 2.6m
Epoch 145/500 | Batch 90/202 | Rec 0.001032 | Seg 0.407887 | Elapsed 1.9m | ETA 2.3m
Epoch 145/500 | Batch 100/202 | Rec 0.001045 | Seg 0.415126 | Elapsed 2.1m | ETA 2.1m
Epoch 145/500 | Batch 110/202 | Rec 0.001045 | Seg 0.417787 | Elapsed 2.3m | ETA 1.9m
Epoch 145/500 | Batch 120/202 | Rec 0.001031 | Seg 0.407702 | Elapsed 2.5m | ETA 1.7m
Epoch 145/500 | Batch 130/202 | Rec 0.001010 | Seg 0.402381 | Elapsed 2.7m | ETA 1.5m
Epoch 145/500 | Batch 140/202 | Rec 0.001005 | Seg 0.402874 | Elapsed 2.9m | ETA 1.3m
Epoch 145/500 | Batch 150/202 | Rec 0.000993 | Seg 0.396446 | Elapsed 3.1m | ETA 1.1m
Epoch 145/500 | Batch 160/202 | Rec 0.000993 | Seg 0.401261 | Elapsed 3.3m | ETA 0.9m
Epoch 145/500 | Batch 170/202 | Rec 0.001005 | Seg 0.403007 | Elapsed 3.5m | ETA 0.7m
Epoch 145/500 | Batch 180/202 | Rec 0.001004 | Seg 0.403698 | Elapsed 3.7m | ETA 0.5m
Epoch 145/500 | Batch 190/202 | Rec 0.000997 | Seg 0.398151 | Elapsed 4.0m | ETA 0.2m
Epoch 145/500 | Batch 200/202 | Rec 0.001008 | Seg 0.401375 | Elapsed 4.2m | ETA 0.0m
Epoch 145/500 | Batch 202/202 | Rec 0.001005 | Seg 0.399545 | Elapsed 4.2m | ETA 0.0m

2026-09-22 18:04:32,813 - INFO: Rec loss: 0.0010046449099150993
2026-09-22 18:04:32,813 - INFO: Seg loss: 0.3995450922094359
2026-09-22 18:04:32,813 - INFO: λ_rec: 1
2026-09-22 18:04:32,813 - INFO: λ_seg: 0.0001
2026-09-22 18:05:46,969 - INFO: -------------------Epoch: 145------------------------
2026-09-22 18:05:46,973 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.107803  0.968243  0.000202
2026-09-22 18:05:46,981 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994897  0.997392  0.995964  0.998925  0.995123
real potato   0.891863  0.942791  0.926085  0.960214  0.999861
fake potato   0.939078  0.968532  0.955936  0.981567  0.999954
real apple    0.687660  0.814879  0.993889  0.690579  0.998918
fake apple    0.621106  0.766227  0.973592  0.631749  0.998545
real orange   0.540667  0.701815  0.975675  0.548055  0.999386
fake orange   0.790347  0.882848  0.813494  0.965249  0.999267
real grape    0.527397  0.690534  0.826610  0.592999  0.998891
fake grape    0.846076  0.916571  0.906797  0.926659  0.999376
real lemon    0.429551  0.600910  0.658066  0.552973  0.999137
fake lemon    0.802990  0.890682  0.995722  0.805770  0.999582
real avocado  0.610837  0.758363  1.000000  0.610837  0.999638
fake avocado  0.280151  0.437646  0.859918  0.293548  0.999097
real pepper   0.781809  0.877495  0.839087  0.919698  0.999061
fake pepper   0.913564  0.954780  0.951612  0.958069  0.999784
real plant    0.810306  0.895165  0.909315  0.881544  0.997936
fake plant    0.739809  0.850399  0.779250  0.935966  0.999738
real banana   0.517921  0.682362  0.919140  0.542646  0.998865
fake banana   0.597167  0.747734  0.681140  0.828882  0.998971
real onion    0.823487  0.903150  0.856127  0.955751  0.999815
fake onion    0.882172  0.937348  0.906483  0.970496  0.999918
real unknown  0.343049  0.510812  0.345829  0.977099  0.999701
fake unknown  0.157315  0.271825  0.182154  0.535675  0.997582
total         0.675183  0.782620  0.837038  0.785433  0.999050
total(-bg)    0.660651  0.772858  0.829815  0.775728  0.999228
2026-09-22 18:05:47,714 - INFO: Epoch accounting: {'epoch': 145, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11359652, 53788, 65179, 100495, 102585, 74973, 74998, 120440, 200384, 55348, 71766, 32154, 29237, 235209, 130538, 121578, 20341, 108889, 69564, 86271, 71348, 13903, 39632], 'crops_with_class': [202, 35, 33, 29, 30, 25, 26, 25, 37, 28, 28, 12, 11, 53, 35, 20, 21, 33, 28, 40, 31, 15, 21], 'targeted_crops_by_class': [0, 4, 1, 4, 4, 4, 5, 5, 1, 4, 7, 3, 3, 4, 4, 6, 7, 5, 5, 7, 8, 3, 4], 'sampled_scene_counts': [0, 1, 2, 1, 1, 1, 2, 0, 0, 2, 1, 1, 0, 1, 3, 1, 0, 1, 1, 0, 1, 1, 1, 4, 0, 0, 0, 0, 1, 1, 2, 2, 1, 1, 1, 2, 2, 1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 2, 3, 1, 1, 1, 0, 1, 1, 2, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 2, 2, 1, 0, 1, 1, 0, 2, 0, 2, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 2, 0, 1, 3, 2, 1, 1, 3, 3, 0, 1, 2, 1, 0, 0, 1, 3, 3, 5, 0, 1, 2, 1, 3, 1, 3, 2, 2, 0, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 3, 0, 2, 2, 1, 0, 2, 2, 0, 2, 3, 0, 1, 0, 3, 1, 3, 1, 2, 1], 'learning_rate': 8.09407482028804e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010046449099150993, 'train_segmentation_loss': 0.3995450922094359, 'val_foreground_miou_all22': 0.6606509459228358, 'val_psnr_ref1': 37.10780334472656, 'elapsed_seconds': 327.2849497795105, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 146/500 | Batch 10/202 | Rec 0.001135 | Seg 0.424806 | Elapsed 0.2m | ETA 4.0m
Epoch 146/500 | Batch 20/202 | Rec 0.000965 | Seg 0.365075 | Elapsed 0.4m | ETA 3.8m
Epoch 146/500 | Batch 30/202 | Rec 0.001071 | Seg 0.356629 | Elapsed 0.6m | ETA 3.6m
Epoch 146/500 | Batch 40/202 | Rec 0.001040 | Seg 0.357108 | Elapsed 0.8m | ETA 3.4m
Epoch 146/500 | Batch 50/202 | Rec 0.001040 | Seg 0.365468 | Elapsed 1.0m | ETA 3.2m
Epoch 146/500 | Batch 60/202 | Rec 0.001058 | Seg 0.384554 | Elapsed 1.3m | ETA 3.0m
Epoch 146/500 | Batch 70/202 | Rec 0.001058 | Seg 0.395009 | Elapsed 1.5m | ETA 2.7m
Epoch 146/500 | Batch 80/202 | Rec 0.001056 | Seg 0.398854 | Elapsed 1.7m | ETA 2.5m
Epoch 146/500 | Batch 90/202 | Rec 0.001045 | Seg 0.397495 | Elapsed 1.9m | ETA 2.3m
Epoch 146/500 | Batch 100/202 | Rec 0.001056 | Seg 0.399556 | Elapsed 2.1m | ETA 2.1m
Epoch 146/500 | Batch 110/202 | Rec 0.001035 | Seg 0.393285 | Elapsed 2.3m | ETA 1.9m
Epoch 146/500 | Batch 120/202 | Rec 0.001067 | Seg 0.395693 | Elapsed 2.5m | ETA 1.7m
Epoch 146/500 | Batch 130/202 | Rec 0.001066 | Seg 0.403126 | Elapsed 2.7m | ETA 1.5m
Epoch 146/500 | Batch 140/202 | Rec 0.001059 | Seg 0.409296 | Elapsed 2.9m | ETA 1.3m
Epoch 146/500 | Batch 150/202 | Rec 0.001058 | Seg 0.414286 | Elapsed 3.1m | ETA 1.1m
Epoch 146/500 | Batch 160/202 | Rec 0.001071 | Seg 0.417694 | Elapsed 3.3m | ETA 0.9m
Epoch 146/500 | Batch 170/202 | Rec 0.001055 | Seg 0.411840 | Elapsed 3.5m | ETA 0.7m
Epoch 146/500 | Batch 180/202 | Rec 0.001057 | Seg 0.413200 | Elapsed 3.7m | ETA 0.5m
Epoch 146/500 | Batch 190/202 | Rec 0.001064 | Seg 0.415428 | Elapsed 3.9m | ETA 0.2m
Epoch 146/500 | Batch 200/202 | Rec 0.001061 | Seg 0.413989 | Elapsed 4.1m | ETA 0.0m
Epoch 146/500 | Batch 202/202 | Rec 0.001060 | Seg 0.414281 | Elapsed 4.2m | ETA 0.0m

2026-09-22 18:09:58,037 - INFO: Rec loss: 0.0010603101016944366
2026-09-22 18:09:58,037 - INFO: Seg loss: 0.41428141594670786
2026-09-22 18:09:58,037 - INFO: λ_rec: 1
2026-09-22 18:09:58,037 - INFO: λ_seg: 0.0001
2026-09-22 18:11:12,269 - INFO: -------------------Epoch: 146------------------------
2026-09-22 18:11:12,273 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.127207  0.968748  0.000202
2026-09-22 18:11:12,280 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994672  0.997279  0.995461  0.999204  0.994905
real potato   0.916625  0.956449  0.969852  0.943509  0.999897
fake potato   0.933483  0.965547  0.972990  0.958316  0.999950
real apple    0.661094  0.795926  0.973154  0.673375  0.998809
fake apple    0.632304  0.774690  0.981828  0.639791  0.998595
real orange   0.497343  0.664256  0.995376  0.498495  0.999336
fake orange   0.768068  0.868772  0.788808  0.966901  0.999164
real grape    0.593447  0.744810  0.809626  0.689688  0.999014
fake grape    0.819121  0.900518  0.915636  0.885988  0.999276
real lemon    0.463716  0.633565  0.591032  0.682810  0.999072
fake lemon    0.815028  0.898039  0.999823  0.815146  0.999609
real avocado  0.792877  0.884425  0.895490  0.873727  0.999788
fake avocado  0.125473  0.222949  0.925512  0.126753  0.998943
real pepper   0.770075  0.870054  0.879485  0.860921  0.999060
fake pepper   0.835977  0.910612  0.999159  0.836566  0.999609
real plant    0.808280  0.893927  0.935143  0.856282  0.997968
fake plant    0.761811  0.864755  0.837979  0.893405  0.999778
real banana   0.512108  0.677298  0.943044  0.528453  0.998869
fake banana   0.675038  0.805947  0.798356  0.813786  0.999279
real onion    0.731169  0.844662  0.759887  0.950853  0.999684
fake onion    0.930798  0.964109  0.975495  0.953083  0.999955
real unknown  0.646897  0.785545  0.700000  0.895038  0.999922
fake unknown  0.171911  0.293354  0.183700  0.728178  0.997045
total         0.689449  0.792065  0.862036  0.785664  0.999023
total(-bg)    0.675575  0.782737  0.855972  0.775957  0.999210
2026-09-22 18:11:12,967 - INFO: Epoch accounting: {'epoch': 146, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11218204, 51301, 62806, 106348, 166449, 87160, 92343, 132843, 248333, 83238, 71161, 26597, 38111, 210606, 156633, 111548, 19719, 73287, 69414, 101817, 57378, 13436, 39540], 'crops_with_class': [202, 33, 29, 29, 39, 25, 31, 25, 45, 38, 31, 11, 14, 51, 35, 14, 23, 24, 25, 41, 30, 14, 21], 'targeted_crops_by_class': [0, 7, 4, 8, 5, 6, 3, 3, 10, 5, 4, 4, 5, 7, 5, 0, 6, 2, 3, 5, 7, 7, 4], 'sampled_scene_counts': [1, 2, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1, 1, 0, 3, 0, 3, 1, 0, 2, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 2, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 2, 0, 1, 0, 1, 0, 1, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2, 2, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 3, 1, 3, 2, 0, 1, 0, 0, 1, 2, 0, 4, 4, 3, 3, 1, 3, 0, 1, 1, 0, 1, 1, 1, 0, 0, 3, 0, 0, 1, 1, 3, 1, 3, 0, 2, 1, 0, 3, 3, 0, 7, 1, 1, 1, 5, 0, 1, 0, 1, 2, 0, 1, 1, 1, 2, 1, 2, 0, 2, 4, 1, 3, 1, 3, 2, 2, 2, 2, 0, 0, 3, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1], 'learning_rate': 8.069373930094218e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010603101016944366, 'train_segmentation_loss': 0.41428141594670786, 'val_foreground_miou_all22': 0.675574800828615, 'val_psnr_ref1': 37.127206573486326, 'elapsed_seconds': 325.245667219162, 'peak_cuda_allocated_gib': 7.509342193603516}

Epoch 147/500 | Batch 10/202 | Rec 0.001174 | Seg 0.475385 | Elapsed 0.2m | ETA 3.8m
Epoch 147/500 | Batch 20/202 | Rec 0.001185 | Seg 0.524442 | Elapsed 0.4m | ETA 3.7m
Epoch 147/500 | Batch 30/202 | Rec 0.001203 | Seg 0.489641 | Elapsed 0.6m | ETA 3.5m
Epoch 147/500 | Batch 40/202 | Rec 0.001163 | Seg 0.471239 | Elapsed 0.8m | ETA 3.3m
Epoch 147/500 | Batch 50/202 | Rec 0.001118 | Seg 0.446981 | Elapsed 1.0m | ETA 3.1m
Epoch 147/500 | Batch 60/202 | Rec 0.001091 | Seg 0.439108 | Elapsed 1.2m | ETA 2.9m
Epoch 147/500 | Batch 70/202 | Rec 0.001067 | Seg 0.438228 | Elapsed 1.4m | ETA 2.7m
Epoch 147/500 | Batch 80/202 | Rec 0.001032 | Seg 0.426284 | Elapsed 1.6m | ETA 2.5m
Epoch 147/500 | Batch 90/202 | Rec 0.001007 | Seg 0.418327 | Elapsed 1.9m | ETA 2.3m
Epoch 147/500 | Batch 100/202 | Rec 0.001015 | Seg 0.426694 | Elapsed 2.1m | ETA 2.1m
Epoch 147/500 | Batch 110/202 | Rec 0.001005 | Seg 0.421101 | Elapsed 2.3m | ETA 1.9m
Epoch 147/500 | Batch 120/202 | Rec 0.000996 | Seg 0.419080 | Elapsed 2.5m | ETA 1.7m
Epoch 147/500 | Batch 130/202 | Rec 0.000989 | Seg 0.415272 | Elapsed 2.7m | ETA 1.5m
Epoch 147/500 | Batch 140/202 | Rec 0.000999 | Seg 0.426056 | Elapsed 2.9m | ETA 1.3m
Epoch 147/500 | Batch 150/202 | Rec 0.001003 | Seg 0.423017 | Elapsed 3.1m | ETA 1.1m
Epoch 147/500 | Batch 160/202 | Rec 0.001012 | Seg 0.423454 | Elapsed 3.3m | ETA 0.9m
Epoch 147/500 | Batch 170/202 | Rec 0.001010 | Seg 0.421121 | Elapsed 3.5m | ETA 0.7m
Epoch 147/500 | Batch 180/202 | Rec 0.001017 | Seg 0.419679 | Elapsed 3.7m | ETA 0.5m
Epoch 147/500 | Batch 190/202 | Rec 0.001025 | Seg 0.421869 | Elapsed 3.9m | ETA 0.2m
Epoch 147/500 | Batch 200/202 | Rec 0.001017 | Seg 0.420425 | Elapsed 4.1m | ETA 0.0m
Epoch 147/500 | Batch 202/202 | Rec 0.001012 | Seg 0.417932 | Elapsed 4.2m | ETA 0.0m

2026-09-22 18:15:24,039 - INFO: Rec loss: 0.0010115195708038137
2026-09-22 18:15:24,039 - INFO: Seg loss: 0.41793163762529295
2026-09-22 18:15:24,039 - INFO: λ_rec: 1
2026-09-22 18:15:24,039 - INFO: λ_seg: 0.0001
2026-09-22 18:16:37,992 - INFO: -------------------Epoch: 147------------------------
2026-09-22 18:16:37,996 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.164066  0.969785  0.000201
2026-09-22 18:16:38,004 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994991  0.997439  0.996271  0.998710  0.995214
real potato   0.863665  0.926796  0.969503  0.887784  0.999832
fake potato   0.633286  0.775426  0.951569  0.654378  0.999724
real apple    0.708484  0.829322  0.949726  0.736090  0.998955
fake apple    0.686107  0.813787  0.961397  0.705545  0.998781
real orange   0.743314  0.852711  0.999844  0.743400  0.999662
fake orange   0.871149  0.931088  0.896140  0.968980  0.999590
real grape    0.662817  0.797172  0.801759  0.792736  0.999158
fake grape    0.811016  0.895598  0.896647  0.894650  0.999229
real lemon    0.454132  0.624560  0.572092  0.687743  0.999028
fake lemon    0.826502  0.904961  0.994301  0.830436  0.999631
real avocado  0.759608  0.863333  0.797440  0.941215  0.999723
fake avocado  0.348113  0.516407  0.989527  0.349401  0.999217
real pepper   0.768978  0.869354  0.937000  0.810904  0.999109
fake pepper   0.860121  0.924751  0.995278  0.863645  0.999665
real plant    0.843244  0.914907  0.934958  0.895793  0.998334
fake plant    0.797591  0.887350  0.862206  0.914110  0.999815
real banana   0.470165  0.639564  0.960544  0.479424  0.998786
fake banana   0.652221  0.789459  0.740749  0.845139  0.999171
real onion    0.724218  0.840004  0.752911  0.950008  0.999673
fake onion    0.927408  0.962287  0.990026  0.936155  0.999954
real unknown  0.546587  0.706784  0.558384  0.962786  0.999872
fake unknown  0.201859  0.335878  0.212139  0.806411  0.997313
total         0.702416  0.808649  0.857409  0.811106  0.999106
total(-bg)    0.689118  0.800068  0.851097  0.802579  0.999283
2026-09-22 18:16:38,857 - INFO: Epoch accounting: {'epoch': 147, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11256596, 44492, 73370, 117263, 135955, 104020, 111379, 131663, 217795, 90326, 88354, 43380, 37644, 98663, 131346, 144609, 25164, 122682, 74221, 70733, 48637, 14619, 55361], 'crops_with_class': [202, 28, 33, 33, 31, 28, 34, 28, 36, 38, 33, 15, 17, 31, 34, 17, 23, 30, 26, 34, 25, 14, 26], 'targeted_crops_by_class': [0, 6, 4, 3, 5, 7, 11, 3, 8, 5, 9, 3, 8, 2, 4, 1, 6, 4, 3, 3, 4, 7, 4], 'sampled_scene_counts': [1, 2, 0, 1, 0, 3, 0, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 3, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 2, 2, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 3, 0, 1, 2, 1, 1, 2, 4, 2, 0, 0, 0, 1, 2, 3, 3, 2, 1, 1, 3, 2, 0, 2, 2, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 2, 4, 1, 5, 3, 3, 1, 1, 3, 0, 4, 0, 1, 0, 1, 3, 2, 1, 2, 3, 0, 1, 1, 2, 0, 3, 3, 1, 2, 2, 0, 0, 0, 2, 2, 1, 0, 0, 1, 2, 1, 0, 2, 1], 'learning_rate': 8.044552359751842e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010115195708038137, 'train_segmentation_loss': 0.41793163762529295, 'val_foreground_miou_all22': 0.6891175014127712, 'val_psnr_ref1': 37.16406616210938, 'elapsed_seconds': 325.882732629776, 'peak_cuda_allocated_gib': 7.514682769775391}

Epoch 148/500 | Batch 10/202 | Rec 0.000817 | Seg 0.365966 | Elapsed 0.2m | ETA 4.1m
Epoch 148/500 | Batch 20/202 | Rec 0.000991 | Seg 0.437715 | Elapsed 0.4m | ETA 3.8m
Epoch 148/500 | Batch 30/202 | Rec 0.001057 | Seg 0.414175 | Elapsed 0.6m | ETA 3.6m
Epoch 148/500 | Batch 40/202 | Rec 0.001055 | Seg 0.403982 | Elapsed 0.8m | ETA 3.4m
Epoch 148/500 | Batch 50/202 | Rec 0.001054 | Seg 0.413106 | Elapsed 1.0m | ETA 3.2m
Epoch 148/500 | Batch 60/202 | Rec 0.001039 | Seg 0.410007 | Elapsed 1.3m | ETA 3.0m
Epoch 148/500 | Batch 70/202 | Rec 0.001057 | Seg 0.416184 | Elapsed 1.5m | ETA 2.7m
Epoch 148/500 | Batch 80/202 | Rec 0.001036 | Seg 0.410040 | Elapsed 1.7m | ETA 2.5m
Epoch 148/500 | Batch 90/202 | Rec 0.001060 | Seg 0.413049 | Elapsed 1.9m | ETA 2.3m
Epoch 148/500 | Batch 100/202 | Rec 0.001069 | Seg 0.413902 | Elapsed 2.1m | ETA 2.1m
Epoch 148/500 | Batch 110/202 | Rec 0.001073 | Seg 0.417521 | Elapsed 2.3m | ETA 1.9m
Epoch 148/500 | Batch 120/202 | Rec 0.001085 | Seg 0.426485 | Elapsed 2.5m | ETA 1.7m
Epoch 148/500 | Batch 130/202 | Rec 0.001065 | Seg 0.419134 | Elapsed 2.7m | ETA 1.5m
Epoch 148/500 | Batch 140/202 | Rec 0.001056 | Seg 0.414401 | Elapsed 2.9m | ETA 1.3m
Epoch 148/500 | Batch 150/202 | Rec 0.001056 | Seg 0.414366 | Elapsed 3.1m | ETA 1.1m
Epoch 148/500 | Batch 160/202 | Rec 0.001049 | Seg 0.415443 | Elapsed 3.3m | ETA 0.9m
Epoch 148/500 | Batch 170/202 | Rec 0.001046 | Seg 0.417669 | Elapsed 3.6m | ETA 0.7m
Epoch 148/500 | Batch 180/202 | Rec 0.001030 | Seg 0.410902 | Elapsed 3.8m | ETA 0.5m
Epoch 148/500 | Batch 190/202 | Rec 0.001019 | Seg 0.410313 | Elapsed 4.0m | ETA 0.3m
Epoch 148/500 | Batch 200/202 | Rec 0.001012 | Seg 0.407413 | Elapsed 4.2m | ETA 0.0m
Epoch 148/500 | Batch 202/202 | Rec 0.001010 | Seg 0.406880 | Elapsed 4.2m | ETA 0.0m

2026-09-22 18:20:52,385 - INFO: Rec loss: 0.0010098631774411897
2026-09-22 18:20:52,385 - INFO: Seg loss: 0.40687977408271025
2026-09-22 18:20:52,385 - INFO: λ_rec: 1
2026-09-22 18:20:52,385 - INFO: λ_seg: 0.0001
2026-09-22 18:22:06,457 - INFO: -------------------Epoch: 148------------------------
2026-09-22 18:22:06,461 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.190786  0.969267  0.000199
2026-09-22 18:22:06,468 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994683  0.997284  0.995710  0.998964  0.994916
real potato   0.540541  0.701709  0.999529  0.540678  0.999450
fake potato   0.311927  0.475488  0.985507  0.313364  0.999496
real apple    0.638867  0.779595  0.844053  0.724370  0.998587
fake apple    0.756324  0.861209  0.981442  0.767297  0.999067
real orange   0.760562  0.863950  0.992340  0.765053  0.999683
fake orange   0.871377  0.931218  0.891958  0.974203  0.999588
real grape    0.413345  0.584872  0.848098  0.446393  0.998677
fake grape    0.690603  0.816941  0.732001  0.924308  0.998468
real lemon    0.297445  0.458460  0.381589  0.574266  0.998406
fake lemon    0.827877  0.905785  0.997226  0.829787  0.999635
real avocado  0.725417  0.840810  0.768739  0.927915  0.999674
fake avocado  0.279299  0.436608  0.963027  0.282326  0.999128
real pepper   0.735427  0.847496  0.877630  0.819456  0.998922
fake pepper   0.825548  0.904389  0.997837  0.827028  0.999583
real plant    0.801015  0.889465  0.927364  0.854634  0.997876
fake plant    0.803932  0.891261  0.922288  0.862347  0.999833
real banana   0.170808  0.291748  0.802077  0.178324  0.998055
fake banana   0.579071  0.733383  0.694062  0.777538  0.998960
real onion    0.720514  0.837508  0.751341  0.946124  0.999668
fake onion    0.940280  0.969171  0.999743  0.940508  0.999962
real unknown  0.552859  0.712006  0.559803  0.978053  0.999874
fake unknown  0.193771  0.324604  0.204310  0.789750  0.997231
total         0.627456  0.741520  0.831203  0.740986  0.998902
total(-bg)    0.610764  0.729894  0.823726  0.729260  0.999083
2026-09-22 18:22:07,204 - INFO: Epoch accounting: {'epoch': 148, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11313919, 64067, 48565, 120554, 116972, 89773, 51844, 137707, 219080, 64699, 77761, 51098, 23224, 218523, 120626, 144292, 19005, 95059, 62369, 74311, 57081, 11946, 55797], 'crops_with_class': [202, 34, 26, 29, 29, 32, 23, 32, 33, 32, 30, 16, 9, 60, 34, 22, 20, 28, 28, 35, 25, 15, 23], 'targeted_crops_by_class': [0, 3, 2, 2, 4, 3, 3, 5, 7, 5, 3, 3, 2, 6, 4, 6, 6, 8, 8, 4, 5, 3, 4], 'sampled_scene_counts': [1, 0, 3, 0, 1, 2, 0, 1, 2, 3, 0, 0, 1, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 2, 0, 0, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 3, 1, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1, 0, 0, 1, 0, 1, 1, 4, 1, 0, 1, 2, 0, 0, 2, 1, 2, 1, 0, 1, 3, 2, 2, 2, 1, 0, 1, 0, 2, 1, 3, 2, 1, 1, 1, 2, 1, 1, 3, 1, 3, 1, 1, 0, 1, 5, 1, 3, 2, 0, 3, 2, 0, 3, 3, 1, 3, 4, 0, 0, 0, 0, 0, 1, 3, 0, 0, 2, 1, 3, 2, 1, 1, 1, 0, 2, 2, 2, 1, 0, 2, 0, 1, 2, 1, 1, 4], 'learning_rate': 8.019611089174007e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010098631774411897, 'train_segmentation_loss': 0.40687977408271025, 'val_foreground_miou_all22': 0.6107639664980735, 'val_psnr_ref1': 37.19078598022461, 'elapsed_seconds': 328.33904910087585, 'peak_cuda_allocated_gib': 7.512729644775391}

Epoch 149/500 | Batch 10/202 | Rec 0.001310 | Seg 0.563174 | Elapsed 0.2m | ETA 4.0m
Epoch 149/500 | Batch 20/202 | Rec 0.001130 | Seg 0.454558 | Elapsed 0.4m | ETA 3.8m
Epoch 149/500 | Batch 30/202 | Rec 0.001111 | Seg 0.419408 | Elapsed 0.6m | ETA 3.6m
Epoch 149/500 | Batch 40/202 | Rec 0.001007 | Seg 0.398428 | Elapsed 0.8m | ETA 3.4m
Epoch 149/500 | Batch 50/202 | Rec 0.000965 | Seg 0.388429 | Elapsed 1.0m | ETA 3.2m
Epoch 149/500 | Batch 60/202 | Rec 0.000967 | Seg 0.377987 | Elapsed 1.2m | ETA 2.9m
Epoch 149/500 | Batch 70/202 | Rec 0.000970 | Seg 0.385098 | Elapsed 1.5m | ETA 2.7m
Epoch 149/500 | Batch 80/202 | Rec 0.001010 | Seg 0.395082 | Elapsed 1.7m | ETA 2.5m
Epoch 149/500 | Batch 90/202 | Rec 0.001006 | Seg 0.395513 | Elapsed 1.9m | ETA 2.3m
Epoch 149/500 | Batch 100/202 | Rec 0.001000 | Seg 0.392782 | Elapsed 2.1m | ETA 2.1m
Epoch 149/500 | Batch 110/202 | Rec 0.000988 | Seg 0.392776 | Elapsed 2.3m | ETA 1.9m
Epoch 149/500 | Batch 120/202 | Rec 0.001000 | Seg 0.395555 | Elapsed 2.5m | ETA 1.7m
Epoch 149/500 | Batch 130/202 | Rec 0.000994 | Seg 0.392329 | Elapsed 2.7m | ETA 1.5m
Epoch 149/500 | Batch 140/202 | Rec 0.000991 | Seg 0.393364 | Elapsed 2.9m | ETA 1.3m
Epoch 149/500 | Batch 150/202 | Rec 0.000987 | Seg 0.396237 | Elapsed 3.1m | ETA 1.1m
Epoch 149/500 | Batch 160/202 | Rec 0.000980 | Seg 0.394213 | Elapsed 3.3m | ETA 0.9m
Epoch 149/500 | Batch 170/202 | Rec 0.000975 | Seg 0.391931 | Elapsed 3.5m | ETA 0.7m
Epoch 149/500 | Batch 180/202 | Rec 0.000975 | Seg 0.392513 | Elapsed 3.7m | ETA 0.5m
Epoch 149/500 | Batch 190/202 | Rec 0.000977 | Seg 0.393374 | Elapsed 3.9m | ETA 0.2m
Epoch 149/500 | Batch 200/202 | Rec 0.000985 | Seg 0.396710 | Elapsed 4.1m | ETA 0.0m
Epoch 149/500 | Batch 202/202 | Rec 0.000985 | Seg 0.397157 | Elapsed 4.2m | ETA 0.0m

2026-09-22 18:26:18,804 - INFO: Rec loss: 0.0009847939870836638
2026-09-22 18:26:18,804 - INFO: Seg loss: 0.39715686079004026
2026-09-22 18:26:18,804 - INFO: λ_rec: 1
2026-09-22 18:26:18,804 - INFO: λ_seg: 0.0001
2026-09-22 18:27:32,713 - INFO: -------------------Epoch: 149------------------------
2026-09-22 18:27:32,717 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.040082  0.968514  0.000205
2026-09-22 18:27:32,724 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994518  0.997202  0.995406  0.999104  0.994758
real potato   0.903366  0.949180  0.943667  0.954858  0.999878
fake potato   0.910489  0.953098  0.951754  0.954545  0.999932
real apple    0.703714  0.826045  0.997684  0.704865  0.998976
fake apple    0.693600  0.819035  0.979363  0.703888  0.998826
real orange   0.449150  0.619837  0.998200  0.449514  0.999274
fake orange   0.744427  0.853443  0.758654  0.975429  0.999041
real grape    0.591334  0.743144  0.848303  0.661258  0.999046
fake grape    0.810808  0.895471  0.938917  0.855958  0.999261
real lemon    0.213499  0.351826  0.442629  0.292002  0.998736
fake lemon    0.797578  0.887342  0.999368  0.797981  0.999572
real avocado  0.746327  0.854690  0.992187  0.750739  0.999763
fake avocado  0.044123  0.084508  0.885496  0.044376  0.998850
real pepper   0.807644  0.893538  0.873169  0.914984  0.999203
fake pepper   0.880889  0.936623  0.987857  0.890532  0.999713
real plant    0.807188  0.893258  0.934208  0.855840  0.997955
fake plant    0.696586  0.821113  0.749762  0.907592  0.999685
real banana   0.473764  0.642885  0.930640  0.491104  0.998774
fake banana   0.532590  0.694971  0.596963  0.831619  0.998657
real onion    0.807186  0.893257  0.841140  0.952373  0.999794
fake onion    0.944950  0.971646  0.989226  0.954776  0.999965
real unknown  0.586585  0.739383  0.619048  0.917939  0.999897
fake unknown  0.190515  0.320022  0.202953  0.756610  0.997291
total         0.666558  0.767022  0.845939  0.765995  0.998993
total(-bg)    0.651651  0.756560  0.839145  0.755399  0.999186
2026-09-22 18:27:33,274 - INFO: Epoch accounting: {'epoch': 149, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11331094, 48599, 53990, 125198, 138642, 93410, 77745, 102353, 226577, 73386, 52101, 39078, 30812, 220589, 131246, 107376, 22620, 81488, 102188, 89447, 48351, 9834, 32148], 'crops_with_class': [202, 25, 22, 34, 38, 24, 26, 24, 39, 26, 24, 15, 12, 49, 36, 16, 18, 25, 34, 32, 25, 11, 16], 'targeted_crops_by_class': [0, 3, 5, 5, 5, 6, 5, 3, 4, 6, 2, 5, 3, 7, 5, 5, 5, 7, 9, 3, 5, 5, 2], 'sampled_scene_counts': [1, 1, 1, 0, 2, 1, 0, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1, 3, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 3, 1, 0, 0, 1, 1, 1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, 1, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 3, 2, 3, 1, 2, 1, 1, 1, 2, 2, 3, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 2, 2, 2, 0, 0, 2, 2, 2, 1, 1, 1, 0, 1, 0, 2, 2, 0, 0, 2, 1, 2, 2, 3, 3, 2, 1, 1, 0, 2, 3, 0, 0, 3, 1, 2, 2, 1, 0, 0, 2, 0, 1, 0, 1, 0, 2, 6, 2], 'learning_rate': 7.994551102999372e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009847939870836638, 'train_segmentation_loss': 0.39715686079004026, 'val_foreground_miou_all22': 0.6516505416369763, 'val_psnr_ref1': 37.040082397460935, 'elapsed_seconds': 326.0622091293335, 'peak_cuda_allocated_gib': 7.506870269775391}

Epoch 150/500 | Batch 10/202 | Rec 0.001221 | Seg 0.502571 | Elapsed 0.2m | ETA 3.9m
Epoch 150/500 | Batch 20/202 | Rec 0.001064 | Seg 0.412322 | Elapsed 0.4m | ETA 3.7m
Epoch 150/500 | Batch 30/202 | Rec 0.001022 | Seg 0.379584 | Elapsed 0.6m | ETA 3.5m
Epoch 150/500 | Batch 40/202 | Rec 0.000936 | Seg 0.360003 | Elapsed 0.8m | ETA 3.3m
Epoch 150/500 | Batch 50/202 | Rec 0.000925 | Seg 0.350023 | Elapsed 1.0m | ETA 3.1m
Epoch 150/500 | Batch 60/202 | Rec 0.000943 | Seg 0.366660 | Elapsed 1.2m | ETA 2.9m
Epoch 150/500 | Batch 70/202 | Rec 0.000962 | Seg 0.368551 | Elapsed 1.4m | ETA 2.7m
Epoch 150/500 | Batch 80/202 | Rec 0.000964 | Seg 0.370354 | Elapsed 1.6m | ETA 2.5m
Epoch 150/500 | Batch 90/202 | Rec 0.000957 | Seg 0.377569 | Elapsed 1.8m | ETA 2.3m
Epoch 150/500 | Batch 100/202 | Rec 0.000946 | Seg 0.374066 | Elapsed 2.0m | ETA 2.1m
Epoch 150/500 | Batch 110/202 | Rec 0.000946 | Seg 0.371946 | Elapsed 2.2m | ETA 1.9m
Epoch 150/500 | Batch 120/202 | Rec 0.000942 | Seg 0.373238 | Elapsed 2.5m | ETA 1.7m
Epoch 150/500 | Batch 130/202 | Rec 0.000963 | Seg 0.383620 | Elapsed 2.7m | ETA 1.5m
Epoch 150/500 | Batch 140/202 | Rec 0.000969 | Seg 0.384680 | Elapsed 2.9m | ETA 1.3m
Epoch 150/500 | Batch 150/202 | Rec 0.000974 | Seg 0.390333 | Elapsed 3.1m | ETA 1.1m
Epoch 150/500 | Batch 160/202 | Rec 0.000974 | Seg 0.388238 | Elapsed 3.3m | ETA 0.9m
Epoch 150/500 | Batch 170/202 | Rec 0.000963 | Seg 0.386434 | Elapsed 3.5m | ETA 0.7m
Epoch 150/500 | Batch 180/202 | Rec 0.000966 | Seg 0.385170 | Elapsed 3.7m | ETA 0.5m
Epoch 150/500 | Batch 190/202 | Rec 0.000967 | Seg 0.387697 | Elapsed 3.9m | ETA 0.2m
Epoch 150/500 | Batch 200/202 | Rec 0.000983 | Seg 0.395282 | Elapsed 4.1m | ETA 0.0m
Epoch 150/500 | Batch 202/202 | Rec 0.000981 | Seg 0.394252 | Elapsed 4.2m | ETA 0.0m

2026-09-22 18:31:42,359 - INFO: Rec loss: 0.0009810408045817858
2026-09-22 18:31:42,359 - INFO: Seg loss: 0.39425176437390913
2026-09-22 18:31:42,359 - INFO: λ_rec: 1
2026-09-22 18:31:42,359 - INFO: λ_seg: 0.0001
2026-09-22 18:32:57,288 - INFO: -------------------Epoch: 150------------------------
2026-09-22 18:32:57,292 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  36.975839  0.96711  0.000208
2026-09-22 18:32:57,299 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994545  0.997215  0.995333  0.999205  0.994783
real potato   0.658639  0.794144  0.998841  0.659143  0.999591
fake potato   0.947830  0.973166  0.996053  0.951403  0.999962
real apple    0.689379  0.816084  0.877890  0.762494  0.998815
fake apple    0.704501  0.826587  0.935058  0.740745  0.998827
real orange   0.799608  0.888598  0.993984  0.803497  0.999735
fake orange   0.817311  0.899423  0.843188  0.963810  0.999383
real grape    0.238088  0.384573  0.898310  0.244683  0.998365
fake grape    0.720923  0.837783  0.795308  0.885163  0.998732
real lemon    0.258509  0.410769  0.454631  0.374708  0.998737
fake lemon    0.809233  0.894510  0.979737  0.823008  0.999590
real avocado  0.793699  0.884936  0.840071  0.934975  0.999774
fake avocado  0.543229  0.703970  1.000000  0.543229  0.999453
real pepper   0.810050  0.895008  0.916951  0.874187  0.999250
fake pepper   0.817328  0.899433  0.981970  0.829780  0.999558
real plant    0.755850  0.860900  0.882210  0.840691  0.997284
fake plant    0.800876  0.889380  0.903321  0.875959  0.999827
real banana   0.134276  0.236739  0.941454  0.135407  0.998038
fake banana   0.421615  0.593104  0.462276  0.827389  0.997912
real onion    0.740216  0.850668  0.779685  0.935991  0.999703
fake onion    0.948547  0.973544  0.984425  0.962999  0.999967
real unknown  0.674290  0.805414  0.711257  0.928435  0.999928
fake unknown  0.207384  0.343485  0.242826  0.586925  0.998110
total         0.664606  0.767801  0.844121  0.760166  0.998927
total(-bg)    0.649608  0.757374  0.837247  0.749301  0.999116
2026-09-22 18:32:57,827 - INFO: Epoch accounting: {'epoch': 150, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11315081, 57408, 59509, 142096, 138082, 82221, 60492, 162487, 198886, 73447, 64371, 29399, 34674, 206921, 114346, 143576, 29027, 61453, 74457, 80474, 45454, 11158, 53253], 'crops_with_class': [202, 29, 27, 35, 36, 24, 22, 30, 34, 32, 26, 12, 13, 53, 31, 23, 27, 20, 31, 35, 20, 14, 22], 'targeted_crops_by_class': [0, 12, 5, 8, 2, 6, 6, 3, 4, 9, 6, 7, 7, 5, 5, 5, 6, 4, 3, 7, 0, 5, 8], 'sampled_scene_counts': [1, 0, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 1, 3, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 2, 2, 0, 1, 0, 3, 0, 0, 1, 2, 2, 1, 0, 1, 1, 1, 2, 0, 4, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 2, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1, 1, 3, 1, 2, 2, 1, 2, 1, 3, 0, 0, 0, 2, 0, 0, 1, 1, 2, 1, 1, 0, 0, 2, 0, 4, 1, 3, 0, 2, 0, 2, 3, 3, 5, 0, 1, 2, 2, 4, 2, 0, 2, 1, 1, 1, 2, 1, 0, 0, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 4, 0, 0, 0, 4, 0, 1, 1, 3, 1, 0, 0, 1, 3, 1, 2, 2, 1, 0], 'learning_rate': 7.969373390553279e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009810408045817858, 'train_segmentation_loss': 0.39425176437390913, 'val_foreground_miou_all22': 0.649608339285044, 'val_psnr_ref1': 36.975839385986326, 'elapsed_seconds': 324.54529786109924, 'peak_cuda_allocated_gib': 7.513248443603516}

Stopped after epoch 150; scheduler horizon remains 500
Saved epoch: 150 | block target: 150 | Missing checkpoint files: []
Download: /kaggle/working/balanced_to_epoch200_20260922_164019_epoch150.zip

/kaggle/working/balanced_to_epoch200_20260922_164019_epoch150.zip

Block completed. Download the backup, then run the next block when ready.

In [1]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_to_epoch200_20260922_164019'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced150')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_to_epoch200_20260922_164019_epoch150.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch150 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 150
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 150
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch150 run.')

Balanced epoch150 reference: /kaggle/input/datasets/arnavnigamd/checkpoint9/balanced_to_epoch200_20260922_164019
PASS:22-class support, aligned crops/flips, deterministic replay, no RNG consumed by index building, baseline crop branch unchanged.
Saved next-epoch LR: 7.944078945808706e-05
Preserved best metrics: {'iou': 0.6891175014127712, 'psnr': 37.19078598022461}
{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.
Training source hashes match the epoch150 run.

In [3]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT150_RUN' not in globals():
    CONT150_RUN = Path('/kaggle/working') / ('balanced150_to_epoch200_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT150_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT150_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 150, 'target_epoch': 200, 'backup_epochs': [200],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Single subprocess continuation from150 through200.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT150_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT150_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT150_RUN.parent / (CONT150_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT150_RUN.parent, base_dir=CONT150_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT150_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT150_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target == 200
    last = CONT150_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT150_RUN.parent) + '/', '--name', CONT150_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT150_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT150_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Epoch200 completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT150_RUN)

Continuation folder: /kaggle/working/balanced150_to_epoch200_20260923_102523

In [4]:
continue_to(200)

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced150_to_epoch200_20260923_102523', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/input/datasets/arnavnigamd/checkpoint9/balanced_to_epoch200_20260922_164019/model/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=200, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-23 10:28:53,814 - INFO: Resuming after epoch 150

Epoch 151/500 | Batch 10/202 | Rec 0.000921 | Seg 0.437346 | Elapsed 0.7m | ETA 12.7m
Epoch 151/500 | Batch 20/202 | Rec 0.000945 | Seg 0.423789 | Elapsed 1.0m | ETA 9.3m
Epoch 151/500 | Batch 30/202 | Rec 0.000980 | Seg 0.449903 | Elapsed 1.4m | ETA 8.0m
Epoch 151/500 | Batch 40/202 | Rec 0.001055 | Seg 0.435764 | Elapsed 1.8m | ETA 7.1m
Epoch 151/500 | Batch 50/202 | Rec 0.001035 | Seg 0.421722 | Elapsed 2.1m | ETA 6.4m
Epoch 151/500 | Batch 60/202 | Rec 0.001009 | Seg 0.412267 | Elapsed 2.4m | ETA 5.7m
Epoch 151/500 | Batch 70/202 | Rec 0.000979 | Seg 0.398594 | Elapsed 2.8m | ETA 5.2m
Epoch 151/500 | Batch 80/202 | Rec 0.000969 | Seg 0.396855 | Elapsed 3.1m | ETA 4.7m
Epoch 151/500 | Batch 90/202 | Rec 0.000942 | Seg 0.385254 | Elapsed 3.4m | ETA 4.2m
Epoch 151/500 | Batch 100/202 | Rec 0.000962 | Seg 0.393703 | Elapsed 3.7m | ETA 3.8m
Epoch 151/500 | Batch 110/202 | Rec 0.000963 | Seg 0.398102 | Elapsed 4.0m | ETA 3.3m
Epoch 151/500 | Batch 120/202 | Rec 0.000966 | Seg 0.398859 | Elapsed 4.3m | ETA 2.9m
Epoch 151/500 | Batch 130/202 | Rec 0.000966 | Seg 0.393507 | Elapsed 4.5m | ETA 2.5m
Epoch 151/500 | Batch 140/202 | Rec 0.000956 | Seg 0.391731 | Elapsed 4.8m | ETA 2.1m
Epoch 151/500 | Batch 150/202 | Rec 0.000966 | Seg 0.394934 | Elapsed 5.1m | ETA 1.8m
Epoch 151/500 | Batch 160/202 | Rec 0.000966 | Seg 0.392330 | Elapsed 5.5m | ETA 1.4m
Epoch 151/500 | Batch 170/202 | Rec 0.000959 | Seg 0.387188 | Elapsed 5.8m | ETA 1.1m
Epoch 151/500 | Batch 180/202 | Rec 0.000964 | Seg 0.387443 | Elapsed 6.2m | ETA 0.8m
Epoch 151/500 | Batch 190/202 | Rec 0.000960 | Seg 0.384042 | Elapsed 6.5m | ETA 0.4m
Epoch 151/500 | Batch 200/202 | Rec 0.000955 | Seg 0.379426 | Elapsed 6.8m | ETA 0.1m
Epoch 151/500 | Batch 202/202 | Rec 0.000952 | Seg 0.378354 | Elapsed 6.9m | ETA 0.0m

2026-09-23 10:35:49,727 - INFO: Rec loss: 0.0009524681362482525
2026-09-23 10:35:49,727 - INFO: Seg loss: 0.37835352698175034
2026-09-23 10:35:49,727 - INFO: λ_rec: 1
2026-09-23 10:35:49,727 - INFO: λ_seg: 0.0001
2026-09-23 10:37:40,796 - INFO: -------------------Epoch: 151------------------------
2026-09-23 10:37:40,804 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.191496  0.968868  0.000199
2026-09-23 10:37:40,812 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994015  0.996949  0.994820  0.999187  0.994273
real potato   0.238715  0.385392  1.000000  0.238715  0.999089
fake potato   0.302136  0.464026  0.998616  0.302262  0.999491
real apple    0.529176  0.692056  0.682581  0.701902  0.997845
fake apple    0.772205  0.871413  0.947029  0.807064  0.999101
real orange   0.407712  0.579214  1.000000  0.407712  0.999220
fake orange   0.754185  0.859820  0.775200  0.965302  0.999099
real grape    0.361553  0.531041  0.668812  0.440400  0.998376
fake grape    0.713257  0.832583  0.827561  0.837768  0.998754
real lemon    0.145179  0.253498  0.267184  0.241236  0.998331
fake lemon    0.823392  0.903093  0.980241  0.837288  0.999620
real avocado  0.814975  0.898006  0.868764  0.929392  0.999804
fake avocado  0.174061  0.296485  0.952282  0.175593  0.999003
real pepper   0.771950  0.871250  0.928379  0.820833  0.999113
fake pepper   0.754232  0.859851  0.978126  0.767172  0.999404
real plant    0.759385  0.863189  0.851935  0.874847  0.997227
fake plant    0.797412  0.887239  0.888654  0.885928  0.999821
real banana   0.247746  0.397078  0.992667  0.248200  0.998307
fake banana   0.548416  0.708307  0.653176  0.773723  0.998828
real onion    0.561916  0.719473  0.857109  0.619997  0.999563
fake onion    0.905314  0.950254  0.998668  0.906409  0.999940
real unknown  0.734187  0.846672  0.776892  0.930343  0.999946
fake unknown  0.149617  0.260256  0.167748  0.580587  0.997220
total         0.576554  0.692485  0.828541  0.664864  0.998755
total(-bg)    0.557578  0.678645  0.820983  0.649667  0.998959
2026-09-23 10:37:41,449 - INFO: Epoch accounting: {'epoch': 151, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11411629, 36616, 40015, 99430, 75677, 87222, 85166, 176497, 179257, 84262, 47148, 41329, 39772, 199563, 118552, 164558, 25821, 66540, 66630, 74106, 49723, 10038, 58721], 'crops_with_class': [202, 24, 24, 27, 27, 25, 31, 32, 30, 36, 26, 16, 16, 49, 31, 24, 27, 20, 30, 30, 23, 10, 23], 'targeted_crops_by_class': [0, 5, 2, 3, 1, 6, 4, 6, 4, 4, 3, 3, 9, 4, 3, 7, 4, 2, 6, 3, 2, 5, 7], 'sampled_scene_counts': [0, 1, 1, 0, 1, 1, 1, 0, 0, 3, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 2, 0, 0, 1, 1, 0, 1, 3, 1, 0, 4, 1, 1, 1, 3, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 2, 1, 1, 1, 2, 0, 0, 1, 3, 0, 3, 0, 1, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 3, 0, 1, 1, 3, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 2, 1, 2, 1, 3, 2, 1, 2, 0, 0, 1, 1, 1, 3, 1, 2, 1, 1, 0, 2, 1, 2, 3, 2, 4, 3, 0, 2, 1, 1, 1, 1, 1, 1, 1, 0, 3, 2, 0, 2, 1, 4, 2, 0, 1, 1, 0, 0, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1], 'learning_rate': 7.944078945808706e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009524681362482525, 'train_segmentation_loss': 0.37835352698175034, 'val_foreground_miou_all22': 0.557578218502377, 'val_psnr_ref1': 37.1914958190918, 'elapsed_seconds': 527.6274104118347, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 152/500 | Batch 10/202 | Rec 0.000892 | Seg 0.316285 | Elapsed 0.2m | ETA 4.5m
Epoch 152/500 | Batch 20/202 | Rec 0.001130 | Seg 0.366233 | Elapsed 0.5m | ETA 4.5m
Epoch 152/500 | Batch 30/202 | Rec 0.001048 | Seg 0.378407 | Elapsed 0.7m | ETA 4.2m
Epoch 152/500 | Batch 40/202 | Rec 0.001009 | Seg 0.374382 | Elapsed 1.0m | ETA 4.0m
Epoch 152/500 | Batch 50/202 | Rec 0.000999 | Seg 0.376779 | Elapsed 1.2m | ETA 3.7m
Epoch 152/500 | Batch 60/202 | Rec 0.001006 | Seg 0.388832 | Elapsed 1.4m | ETA 3.4m
Epoch 152/500 | Batch 70/202 | Rec 0.001043 | Seg 0.412052 | Elapsed 1.7m | ETA 3.2m
Epoch 152/500 | Batch 80/202 | Rec 0.001025 | Seg 0.411621 | Elapsed 1.9m | ETA 2.9m
Epoch 152/500 | Batch 90/202 | Rec 0.000994 | Seg 0.405598 | Elapsed 2.1m | ETA 2.7m
Epoch 152/500 | Batch 100/202 | Rec 0.001000 | Seg 0.400962 | Elapsed 2.4m | ETA 2.5m
Epoch 152/500 | Batch 110/202 | Rec 0.001030 | Seg 0.399407 | Elapsed 2.7m | ETA 2.3m
Epoch 152/500 | Batch 120/202 | Rec 0.001017 | Seg 0.396892 | Elapsed 3.0m | ETA 2.0m
Epoch 152/500 | Batch 130/202 | Rec 0.001030 | Seg 0.396542 | Elapsed 3.2m | ETA 1.8m
Epoch 152/500 | Batch 140/202 | Rec 0.001018 | Seg 0.398527 | Elapsed 3.4m | ETA 1.5m
Epoch 152/500 | Batch 150/202 | Rec 0.001014 | Seg 0.396113 | Elapsed 3.7m | ETA 1.3m
Epoch 152/500 | Batch 160/202 | Rec 0.000990 | Seg 0.389414 | Elapsed 3.9m | ETA 1.0m
Epoch 152/500 | Batch 170/202 | Rec 0.000999 | Seg 0.394554 | Elapsed 4.1m | ETA 0.8m
Epoch 152/500 | Batch 180/202 | Rec 0.000990 | Seg 0.392150 | Elapsed 4.3m | ETA 0.5m
Epoch 152/500 | Batch 190/202 | Rec 0.000988 | Seg 0.389305 | Elapsed 4.6m | ETA 0.3m
Epoch 152/500 | Batch 200/202 | Rec 0.000980 | Seg 0.386694 | Elapsed 4.8m | ETA 0.0m
Epoch 152/500 | Batch 202/202 | Rec 0.000978 | Seg 0.385335 | Elapsed 4.9m | ETA 0.0m

2026-09-23 10:42:33,515 - INFO: Rec loss: 0.0009781381353478889
2026-09-23 10:42:33,516 - INFO: Seg loss: 0.38533516512206284
2026-09-23 10:42:33,516 - INFO: λ_rec: 1
2026-09-23 10:42:33,516 - INFO: λ_seg: 0.0001
2026-09-23 10:43:50,231 - INFO: -------------------Epoch: 152------------------------
2026-09-23 10:43:50,235 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  36.742052  0.968431  0.00022
2026-09-23 10:43:50,241 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994774  0.997330  0.995928  0.998837  0.995005
real potato   0.828328  0.906055  0.997548  0.830018  0.999794
fake potato   0.960215  0.979654  0.988903  0.970674  0.999971
real apple    0.684785  0.812856  0.936343  0.718222  0.998859
fake apple    0.664300  0.798245  0.957645  0.684408  0.998694
real orange   0.500689  0.667234  0.985078  0.504516  0.999337
fake orange   0.766055  0.867483  0.780004  0.977188  0.999146
real grape    0.410497  0.582013  0.741654  0.478989  0.998564
fake grape    0.817157  0.899329  0.898953  0.899806  0.999255
real lemon    0.368849  0.538869  0.496823  0.588808  0.998816
fake lemon    0.812348  0.896410  0.953943  0.845510  0.999587
real avocado  0.810666  0.895384  0.871233  0.921018  0.999800
fake avocado  0.489427  0.657157  0.997922  0.489926  0.999388
real pepper   0.753349  0.859276  0.895742  0.825755  0.999011
fake pepper   0.903962  0.949509  0.977561  0.923116  0.999766
real plant    0.797944  0.887569  0.874389  0.901254  0.997717
fake plant    0.776053  0.873858  0.875505  0.872316  0.999800
real banana   0.316879  0.481220  0.958663  0.321269  0.998444
fake banana   0.498662  0.665427  0.575888  0.788072  0.998542
real onion    0.768616  0.869123  0.831867  0.909981  0.999753
fake onion    0.954195  0.976511  0.996726  0.957195  0.999971
real unknown  0.237547  0.383868  0.239630  0.964695  0.999505
fake unknown  0.212727  0.350780  0.258563  0.545455  0.998299
total         0.666436  0.773703  0.829848  0.779001  0.999001
total(-bg)    0.651511  0.763538  0.822299  0.769009  0.999183
2026-09-23 10:43:50,753 - INFO: Epoch accounting: {'epoch': 152, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11316960, 35282, 58073, 96679, 168642, 80430, 52445, 149369, 218513, 66255, 56604, 45121, 34218, 238901, 132449, 105610, 20424, 88727, 64843, 81999, 63149, 9794, 53785], 'crops_with_class': [202, 26, 24, 26, 38, 26, 22, 28, 43, 29, 24, 16, 14, 60, 32, 20, 21, 26, 31, 36, 31, 15, 23], 'targeted_crops_by_class': [0, 5, 3, 4, 6, 2, 4, 6, 2, 4, 4, 6, 4, 4, 7, 3, 5, 6, 3, 3, 4, 7, 6], 'sampled_scene_counts': [1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 2, 1, 1, 0, 0, 2, 2, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 2, 1, 0, 1, 0, 3, 0, 0, 2, 0, 1, 1, 2, 1, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 1, 0, 2, 1, 1, 1, 1, 4, 1, 1, 1, 2, 2, 1, 2, 1, 3, 1, 1, 3, 1, 4, 4, 1, 1, 1, 1, 0, 2, 1, 3, 1, 0, 1, 2, 3, 3, 2, 0, 2, 1, 0, 1, 1, 1, 1, 2, 1, 0, 2, 2, 0, 0, 0, 0, 3, 2, 1, 2, 0, 5, 2, 0, 2, 0, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 2, 4, 0], 'learning_rate': 7.91866876734702e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009781381353478889, 'train_segmentation_loss': 0.38533516512206284, 'val_foreground_miou_all22': 0.6515114429175605, 'val_psnr_ref1': 36.74205230712891, 'elapsed_seconds': 369.2967538833618, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 153/500 | Batch 10/202 | Rec 0.000996 | Seg 0.374575 | Elapsed 0.2m | ETA 4.8m
Epoch 153/500 | Batch 20/202 | Rec 0.000850 | Seg 0.330941 | Elapsed 0.5m | ETA 4.4m
Epoch 153/500 | Batch 30/202 | Rec 0.000868 | Seg 0.336795 | Elapsed 0.7m | ETA 4.1m
Epoch 153/500 | Batch 40/202 | Rec 0.000873 | Seg 0.349126 | Elapsed 1.0m | ETA 3.9m
Epoch 153/500 | Batch 50/202 | Rec 0.000869 | Seg 0.357214 | Elapsed 1.2m | ETA 3.6m
Epoch 153/500 | Batch 60/202 | Rec 0.000893 | Seg 0.369697 | Elapsed 1.4m | ETA 3.3m
Epoch 153/500 | Batch 70/202 | Rec 0.000908 | Seg 0.365084 | Elapsed 1.6m | ETA 3.0m
Epoch 153/500 | Batch 80/202 | Rec 0.000901 | Seg 0.363669 | Elapsed 1.8m | ETA 2.8m
Epoch 153/500 | Batch 90/202 | Rec 0.000948 | Seg 0.372198 | Elapsed 2.0m | ETA 2.5m
Epoch 153/500 | Batch 100/202 | Rec 0.000984 | Seg 0.378664 | Elapsed 2.3m | ETA 2.3m
Epoch 153/500 | Batch 110/202 | Rec 0.000968 | Seg 0.379444 | Elapsed 2.5m | ETA 2.1m
Epoch 153/500 | Batch 120/202 | Rec 0.000978 | Seg 0.381344 | Elapsed 2.7m | ETA 1.9m
Epoch 153/500 | Batch 130/202 | Rec 0.000965 | Seg 0.377415 | Elapsed 2.9m | ETA 1.6m
Epoch 153/500 | Batch 140/202 | Rec 0.000959 | Seg 0.375511 | Elapsed 3.2m | ETA 1.4m
Epoch 153/500 | Batch 150/202 | Rec 0.000976 | Seg 0.386462 | Elapsed 3.4m | ETA 1.2m
Epoch 153/500 | Batch 160/202 | Rec 0.000974 | Seg 0.391925 | Elapsed 3.6m | ETA 1.0m
Epoch 153/500 | Batch 170/202 | Rec 0.000967 | Seg 0.389156 | Elapsed 3.9m | ETA 0.7m
Epoch 153/500 | Batch 180/202 | Rec 0.000971 | Seg 0.392451 | Elapsed 4.1m | ETA 0.5m
Epoch 153/500 | Batch 190/202 | Rec 0.000973 | Seg 0.391752 | Elapsed 4.3m | ETA 0.3m
Epoch 153/500 | Batch 200/202 | Rec 0.000983 | Seg 0.391692 | Elapsed 4.6m | ETA 0.0m
Epoch 153/500 | Batch 202/202 | Rec 0.000980 | Seg 0.390589 | Elapsed 4.6m | ETA 0.0m

2026-09-23 10:48:29,706 - INFO: Rec loss: 0.000979809344361195
2026-09-23 10:48:29,706 - INFO: Seg loss: 0.39058929187531516
2026-09-23 10:48:29,706 - INFO: λ_rec: 1
2026-09-23 10:48:29,706 - INFO: λ_seg: 0.0001
2026-09-23 10:49:46,652 - INFO: -------------------Epoch: 153------------------------
2026-09-23 10:49:46,657 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  35.932819  0.966545  0.000263
2026-09-23 10:49:46,664 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994553  0.997219  0.995622  0.998921  0.994791
real potato   0.259977  0.412637  0.999510  0.260010  0.999114
fake potato   0.119058  0.212762  0.962900  0.119606  0.999355
real apple    0.590142  0.742201  0.746921  0.737638  0.998233
fake apple    0.769734  0.869837  0.968097  0.789767  0.999108
real orange   0.603520  0.752697  1.000000  0.603520  0.999478
fake orange   0.807075  0.893189  0.823937  0.975269  0.999333
real grape    0.370368  0.540494  0.838506  0.398816  0.998584
fake grape    0.751531  0.858092  0.819037  0.901167  0.998898
real lemon    0.162204  0.279082  0.251352  0.313815  0.998095
fake lemon    0.826694  0.905076  0.996446  0.829138  0.999632
real avocado  0.739142  0.849958  0.816929  0.885878  0.999709
fake avocado  0.049692  0.094668  0.786852  0.050370  0.998847
real pepper   0.761168  0.864340  0.928986  0.808193  0.999072
fake pepper   0.793809  0.885005  0.998793  0.794571  0.999508
real plant    0.777996  0.875088  0.885924  0.864611  0.997532
fake plant    0.802218  0.890207  0.879514  0.901265  0.999823
real banana   0.132694  0.234275  0.874451  0.135271  0.998013
fake banana   0.493062  0.660422  0.565998  0.792800  0.998501
real onion    0.734949  0.847178  0.849169  0.845296  0.999725
fake onion    0.712008  0.831732  0.998644  0.712696  0.999818
real unknown  0.675951  0.806599  0.701198  0.949427  0.999927
fake unknown  0.146592  0.255673  0.153197  0.772727  0.996210
total         0.568441  0.676453  0.819217  0.671338  0.998752
total(-bg)    0.549072  0.661873  0.811198  0.656448  0.998933
2026-09-23 10:49:47,256 - INFO: Epoch accounting: {'epoch': 153, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11295618, 43979, 56741, 107527, 171459, 75244, 65911, 147825, 232888, 73867, 54994, 52419, 46026, 237645, 151288, 81823, 23453, 75539, 59301, 62967, 45916, 12361, 63481], 'crops_with_class': [202, 25, 26, 32, 47, 22, 25, 30, 36, 30, 27, 19, 18, 56, 33, 12, 23, 24, 24, 25, 21, 15, 25], 'targeted_crops_by_class': [0, 4, 7, 0, 6, 7, 9, 3, 5, 3, 4, 5, 6, 4, 3, 4, 3, 7, 1, 2, 2, 3, 6], 'sampled_scene_counts': [1, 2, 0, 0, 0, 2, 0, 1, 3, 3, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 1, 2, 1, 1, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 2, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 3, 0, 3, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 2, 0, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 1, 2, 1, 1, 2, 0, 2, 1, 2, 2, 0, 3, 0, 1, 1, 1, 2, 1, 2, 1, 1, 2, 0, 1, 0, 1, 3, 1, 0, 1, 0, 3, 1, 1, 1, 4, 1, 0, 2, 3, 2, 3, 2, 5, 1, 2, 2, 0, 1, 2, 0, 2, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 2, 2, 1, 2, 2, 1, 3, 0, 0, 0, 1, 1, 1, 3, 1, 1, 1], 'learning_rate': 7.893143858318555e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000979809344361195, 'train_segmentation_loss': 0.39058929187531516, 'val_foreground_miou_all22': 0.5490718740820697, 'val_psnr_ref1': 35.9328190612793, 'elapsed_seconds': 356.4957649707794, 'peak_cuda_allocated_gib': 7.510044097900391}

Epoch 154/500 | Batch 10/202 | Rec 0.000986 | Seg 0.419388 | Elapsed 0.2m | ETA 4.0m
Epoch 154/500 | Batch 20/202 | Rec 0.000969 | Seg 0.410680 | Elapsed 0.4m | ETA 3.9m
Epoch 154/500 | Batch 30/202 | Rec 0.000965 | Seg 0.413090 | Elapsed 0.7m | ETA 3.7m
Epoch 154/500 | Batch 40/202 | Rec 0.000945 | Seg 0.403029 | Elapsed 0.9m | ETA 3.5m
Epoch 154/500 | Batch 50/202 | Rec 0.000957 | Seg 0.411991 | Elapsed 1.1m | ETA 3.4m
Epoch 154/500 | Batch 60/202 | Rec 0.001017 | Seg 0.430151 | Elapsed 1.3m | ETA 3.1m
Epoch 154/500 | Batch 70/202 | Rec 0.001035 | Seg 0.418459 | Elapsed 1.6m | ETA 3.0m
Epoch 154/500 | Batch 80/202 | Rec 0.001076 | Seg 0.423041 | Elapsed 1.8m | ETA 2.7m
Epoch 154/500 | Batch 90/202 | Rec 0.001047 | Seg 0.408373 | Elapsed 2.0m | ETA 2.5m
Epoch 154/500 | Batch 100/202 | Rec 0.001037 | Seg 0.409463 | Elapsed 2.2m | ETA 2.3m
Epoch 154/500 | Batch 110/202 | Rec 0.001030 | Seg 0.407757 | Elapsed 2.5m | ETA 2.1m
Epoch 154/500 | Batch 120/202 | Rec 0.001034 | Seg 0.419261 | Elapsed 2.7m | ETA 1.8m
Epoch 154/500 | Batch 130/202 | Rec 0.001024 | Seg 0.411706 | Elapsed 2.9m | ETA 1.6m
Epoch 154/500 | Batch 140/202 | Rec 0.001019 | Seg 0.410387 | Elapsed 3.1m | ETA 1.4m
Epoch 154/500 | Batch 150/202 | Rec 0.001024 | Seg 0.409713 | Elapsed 3.3m | ETA 1.1m
Epoch 154/500 | Batch 160/202 | Rec 0.001022 | Seg 0.407529 | Elapsed 3.5m | ETA 0.9m
Epoch 154/500 | Batch 170/202 | Rec 0.001024 | Seg 0.408741 | Elapsed 3.7m | ETA 0.7m
Epoch 154/500 | Batch 180/202 | Rec 0.001018 | Seg 0.404250 | Elapsed 4.0m | ETA 0.5m
Epoch 154/500 | Batch 190/202 | Rec 0.001012 | Seg 0.402363 | Elapsed 4.2m | ETA 0.3m
Epoch 154/500 | Batch 200/202 | Rec 0.001009 | Seg 0.400839 | Elapsed 4.4m | ETA 0.0m
Epoch 154/500 | Batch 202/202 | Rec 0.001010 | Seg 0.400590 | Elapsed 4.5m | ETA 0.0m

2026-09-23 10:54:14,428 - INFO: Rec loss: 0.0010104773728647222
2026-09-23 10:54:14,428 - INFO: Seg loss: 0.4005899107692265
2026-09-23 10:54:14,428 - INFO: λ_rec: 1
2026-09-23 10:54:14,428 - INFO: λ_seg: 0.0001
2026-09-23 10:55:31,653 - INFO: -------------------Epoch: 154------------------------
2026-09-23 10:55:31,657 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.908321  0.968373  0.000212
2026-09-23 10:55:31,664 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994963  0.997425  0.996126  0.998828  0.995186
real potato   0.433197  0.604477  0.999412  0.433308  0.999322
fake potato   0.638316  0.779186  0.992545  0.641391  0.999735
real apple    0.710927  0.830993  0.805159  0.858647  0.998795
fake apple    0.642239  0.782102  0.946924  0.666222  0.998599
real orange   0.487639  0.655544  0.985821  0.491084  0.999320
fake orange   0.741371  0.851430  0.754142  0.977668  0.999024
real grape    0.307152  0.469918  0.913291  0.316378  0.998510
fake grape    0.780635  0.876755  0.874646  0.878975  0.999086
real lemon    0.423023  0.594493  0.512154  0.708517  0.998864
fake lemon    0.829178  0.906563  0.981999  0.841976  0.999633
real avocado  0.825917  0.904610  0.875672  0.935632  0.999817
fake avocado  0.396286  0.567587  0.976954  0.400025  0.999271
real pepper   0.780404  0.876610  0.869289  0.884157  0.999090
fake pepper   0.811040  0.895612  0.993294  0.815505  0.999547
real plant    0.778611  0.875477  0.862509  0.888943  0.997472
fake plant    0.788799  0.881882  0.846194  0.920821  0.999804
real banana   0.388878  0.559947  0.931574  0.400312  0.998586
fake banana   0.643658  0.783152  0.731276  0.843066  0.999141
real onion    0.731378  0.844801  0.839080  0.850701  0.999718
fake onion    0.956259  0.977591  0.999242  0.956953  0.999972
real unknown  0.927589  0.962385  0.959242  0.965649  0.999988
fake unknown  0.198081  0.330628  0.216171  0.703006  0.997602
total         0.661545  0.774312  0.863596  0.755555  0.998960
total(-bg)    0.646390  0.764170  0.857572  0.744497  0.999132
2026-09-23 10:55:32,197 - INFO: Epoch accounting: {'epoch': 154, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11258144, 56194, 67736, 113300, 118777, 86913, 64587, 132343, 179650, 86363, 56676, 45869, 41443, 229575, 145002, 171733, 28495, 86935, 71870, 78091, 56680, 13037, 48859], 'crops_with_class': [202, 30, 29, 33, 36, 25, 25, 24, 35, 42, 28, 16, 17, 59, 39, 18, 24, 25, 37, 35, 25, 14, 20], 'targeted_crops_by_class': [0, 4, 5, 7, 3, 7, 4, 3, 5, 6, 5, 4, 4, 5, 7, 3, 5, 7, 5, 5, 4, 7, 5], 'sampled_scene_counts': [0, 1, 3, 1, 1, 0, 0, 1, 0, 3, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 3, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 3, 0, 1, 1, 0, 2, 0, 0, 1, 0, 0, 3, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 2, 1, 1, 2, 3, 0, 2, 1, 1, 1, 1, 1, 1, 0, 3, 1, 3, 1, 0, 3, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 3, 1, 5, 1, 1, 0, 4, 2, 2, 1, 2, 1, 1, 1, 0, 2, 2, 0, 2, 1, 2, 2, 2, 1, 1, 1, 3, 1, 1, 4, 1, 2, 0, 0, 1, 1, 3, 1, 1, 2, 1, 0, 2, 2, 1, 0, 2, 4, 1], 'learning_rate': 7.867505226403017e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0010104773728647222, 'train_segmentation_loss': 0.4005899107692265, 'val_foreground_miou_all22': 0.6463899426591729, 'val_psnr_ref1': 36.90832122802735, 'elapsed_seconds': 344.9328455924988, 'peak_cuda_allocated_gib': 7.509685516357422}

Epoch 155/500 | Batch 10/202 | Rec 0.000820 | Seg 0.324573 | Elapsed 0.2m | ETA 4.8m
Epoch 155/500 | Batch 20/202 | Rec 0.000890 | Seg 0.322085 | Elapsed 0.5m | ETA 4.2m
Epoch 155/500 | Batch 30/202 | Rec 0.000865 | Seg 0.327230 | Elapsed 0.7m | ETA 3.9m
Epoch 155/500 | Batch 40/202 | Rec 0.000899 | Seg 0.341002 | Elapsed 0.9m | ETA 3.7m
Epoch 155/500 | Batch 50/202 | Rec 0.000927 | Seg 0.374469 | Elapsed 1.1m | ETA 3.5m
Epoch 155/500 | Batch 60/202 | Rec 0.000931 | Seg 0.378070 | Elapsed 1.4m | ETA 3.3m
Epoch 155/500 | Batch 70/202 | Rec 0.000926 | Seg 0.390400 | Elapsed 1.6m | ETA 3.0m
Epoch 155/500 | Batch 80/202 | Rec 0.000961 | Seg 0.387046 | Elapsed 1.8m | ETA 2.8m
Epoch 155/500 | Batch 90/202 | Rec 0.000959 | Seg 0.382475 | Elapsed 2.0m | ETA 2.5m
Epoch 155/500 | Batch 100/202 | Rec 0.000972 | Seg 0.384814 | Elapsed 2.3m | ETA 2.3m
Epoch 155/500 | Batch 110/202 | Rec 0.000939 | Seg 0.375229 | Elapsed 2.5m | ETA 2.1m
Epoch 155/500 | Batch 120/202 | Rec 0.000958 | Seg 0.373361 | Elapsed 2.7m | ETA 1.8m
Epoch 155/500 | Batch 130/202 | Rec 0.000977 | Seg 0.377996 | Elapsed 2.9m | ETA 1.6m
Epoch 155/500 | Batch 140/202 | Rec 0.000990 | Seg 0.373662 | Elapsed 3.1m | ETA 1.4m
Epoch 155/500 | Batch 150/202 | Rec 0.000980 | Seg 0.373862 | Elapsed 3.3m | ETA 1.2m
Epoch 155/500 | Batch 160/202 | Rec 0.000983 | Seg 0.377648 | Elapsed 3.6m | ETA 0.9m
Epoch 155/500 | Batch 170/202 | Rec 0.000974 | Seg 0.374846 | Elapsed 3.8m | ETA 0.7m
Epoch 155/500 | Batch 180/202 | Rec 0.000974 | Seg 0.376178 | Elapsed 4.0m | ETA 0.5m
Epoch 155/500 | Batch 190/202 | Rec 0.000966 | Seg 0.376440 | Elapsed 4.2m | ETA 0.3m
Epoch 155/500 | Batch 200/202 | Rec 0.000970 | Seg 0.377576 | Elapsed 4.4m | ETA 0.0m
Epoch 155/500 | Batch 202/202 | Rec 0.000968 | Seg 0.376700 | Elapsed 4.4m | ETA 0.0m

2026-09-23 10:59:59,070 - INFO: Rec loss: 0.0009682900582078272
2026-09-23 10:59:59,070 - INFO: Seg loss: 0.3766996552153389
2026-09-23 10:59:59,070 - INFO: λ_rec: 1
2026-09-23 10:59:59,070 - INFO: λ_seg: 0.0001
2026-09-23 11:01:16,054 - INFO: -------------------Epoch: 155------------------------
2026-09-23 11:01:16,059 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  37.15015  0.968959  0.000201
2026-09-23 11:01:16,067 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994781  0.997334  0.995780  0.998992  0.995010
real potato   0.497386  0.664295  0.999744  0.497450  0.999398
fake potato   0.629339  0.772460  0.978792  0.638039  0.999726
real apple    0.658820  0.794274  0.836317  0.756347  0.998649
fake apple    0.631459  0.774055  0.934289  0.660807  0.998544
real orange   0.563338  0.720640  0.996728  0.564382  0.999424
fake orange   0.713253  0.832581  0.724803  0.978147  0.998874
real grape    0.262367  0.415641  0.956808  0.265512  0.998441
fake grape    0.737839  0.849095  0.837114  0.861527  0.998868
real lemon    0.417986  0.589500  0.509505  0.699429  0.998855
fake lemon    0.830734  0.907492  0.995864  0.833610  0.999641
real avocado  0.794013  0.885131  0.853722  0.919048  0.999778
fake avocado  0.041571  0.079816  1.000000  0.041571  0.998853
real pepper   0.839837  0.912897  0.961508  0.869056  0.999394
fake pepper   0.769182  0.869485  0.985801  0.777799  0.999444
real plant    0.786359  0.880354  0.868360  0.892787  0.997574
fake plant    0.645406  0.784445  0.756362  0.814801  0.999644
real banana   0.313937  0.477818  0.919876  0.322762  0.998415
fake banana   0.605043  0.753877  0.693379  0.826062  0.999008
real onion    0.692097  0.817985  0.785481  0.853403  0.999657
fake onion    0.949120  0.973846  0.982525  0.965417  0.999967
real unknown  0.883530  0.938114  0.950098  0.926527  0.999980
fake unknown  0.165995  0.284696  0.175953  0.745744  0.996843
total         0.627104  0.738080  0.856470  0.726488  0.998869
total(-bg)    0.610391  0.726295  0.850138  0.714101  0.999044
2026-09-23 11:01:16,633 - INFO: Epoch accounting: {'epoch': 155, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11359960, 60081, 70432, 95928, 146239, 114571, 86064, 117188, 233499, 73760, 72438, 31806, 13268, 222994, 94311, 142370, 23001, 75489, 45920, 76230, 35535, 5252, 41936], 'crops_with_class': [202, 33, 31, 31, 34, 31, 28, 26, 42, 33, 30, 10, 5, 52, 24, 20, 21, 19, 23, 30, 17, 8, 20], 'targeted_crops_by_class': [0, 3, 5, 3, 2, 6, 5, 7, 7, 3, 6, 5, 3, 5, 3, 5, 4, 5, 3, 6, 2, 3, 7], 'sampled_scene_counts': [1, 1, 1, 0, 1, 1, 2, 1, 2, 1, 0, 0, 0, 0, 3, 1, 2, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 2, 1, 1, 0, 3, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 3, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 0, 1, 3, 0, 5, 1, 1, 1, 4, 3, 0, 1, 0, 0, 1, 1, 0, 0, 2, 2, 3, 1, 1, 1, 1, 0, 3, 0, 2, 3, 1, 1, 0, 1, 0, 3, 1, 0, 3, 3, 2, 1, 3, 1, 1, 1, 1, 1, 0, 1, 2, 0, 0, 2, 2, 0, 1, 2, 4, 2, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 1, 0, 2, 0, 0, 2], 'learning_rate': 7.841753883769693e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009682900582078272, 'train_segmentation_loss': 0.3766996552153389, 'val_foreground_miou_all22': 0.6103914328098319, 'val_psnr_ref1': 37.15015045166015, 'elapsed_seconds': 344.4282433986664, 'peak_cuda_allocated_gib': 7.508365631103516}

Epoch 156/500 | Batch 10/202 | Rec 0.000855 | Seg 0.334320 | Elapsed 0.2m | ETA 4.2m
Epoch 156/500 | Batch 20/202 | Rec 0.001089 | Seg 0.400448 | Elapsed 0.4m | ETA 4.0m
Epoch 156/500 | Batch 30/202 | Rec 0.001037 | Seg 0.390252 | Elapsed 0.7m | ETA 3.8m
Epoch 156/500 | Batch 40/202 | Rec 0.001061 | Seg 0.386020 | Elapsed 0.9m | ETA 3.5m
Epoch 156/500 | Batch 50/202 | Rec 0.001084 | Seg 0.412072 | Elapsed 1.1m | ETA 3.3m
Epoch 156/500 | Batch 60/202 | Rec 0.001034 | Seg 0.388129 | Elapsed 1.3m | ETA 3.1m
Epoch 156/500 | Batch 70/202 | Rec 0.001023 | Seg 0.394439 | Elapsed 1.5m | ETA 2.9m
Epoch 156/500 | Batch 80/202 | Rec 0.001057 | Seg 0.414339 | Elapsed 1.7m | ETA 2.7m
Epoch 156/500 | Batch 90/202 | Rec 0.001043 | Seg 0.417908 | Elapsed 2.0m | ETA 2.4m
Epoch 156/500 | Batch 100/202 | Rec 0.001059 | Seg 0.411016 | Elapsed 2.2m | ETA 2.2m
Epoch 156/500 | Batch 110/202 | Rec 0.001075 | Seg 0.414465 | Elapsed 2.4m | ETA 2.0m
Epoch 156/500 | Batch 120/202 | Rec 0.001096 | Seg 0.420386 | Elapsed 2.6m | ETA 1.8m
Epoch 156/500 | Batch 130/202 | Rec 0.001112 | Seg 0.417939 | Elapsed 2.8m | ETA 1.6m
Epoch 156/500 | Batch 140/202 | Rec 0.001106 | Seg 0.420659 | Elapsed 3.0m | ETA 1.3m
Epoch 156/500 | Batch 150/202 | Rec 0.001112 | Seg 0.421304 | Elapsed 3.2m | ETA 1.1m
Epoch 156/500 | Batch 160/202 | Rec 0.001094 | Seg 0.417066 | Elapsed 3.5m | ETA 0.9m
Epoch 156/500 | Batch 170/202 | Rec 0.001100 | Seg 0.424451 | Elapsed 3.7m | ETA 0.7m
Epoch 156/500 | Batch 180/202 | Rec 0.001099 | Seg 0.426415 | Elapsed 3.9m | ETA 0.5m
Epoch 156/500 | Batch 190/202 | Rec 0.001078 | Seg 0.417033 | Elapsed 4.1m | ETA 0.3m
Epoch 156/500 | Batch 200/202 | Rec 0.001067 | Seg 0.416947 | Elapsed 4.3m | ETA 0.0m
Epoch 156/500 | Batch 202/202 | Rec 0.001068 | Seg 0.415555 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:05:39,198 - INFO: Rec loss: 0.0010681023439715184
2026-09-23 11:05:39,198 - INFO: Seg loss: 0.4155549001096204
2026-09-23 11:05:39,198 - INFO: λ_rec: 1
2026-09-23 11:05:39,198 - INFO: λ_seg: 0.0001
2026-09-23 11:06:56,346 - INFO: -------------------Epoch: 156------------------------
2026-09-23 11:06:56,350 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.013388  0.968428  0.000207
2026-09-23 11:06:56,357 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993565  0.996722  0.994321  0.999235  0.993839
real potato   0.489543  0.657263  1.000000  0.489543  0.999389
fake potato   0.261746  0.414862  0.972201  0.263720  0.999458
real apple    0.497594  0.664476  0.802554  0.567006  0.998025
fake apple    0.722714  0.838992  0.905482  0.781684  0.998868
real orange   0.242937  0.390876  1.000000  0.242937  0.999002
fake orange   0.676200  0.806776  0.694342  0.962797  0.998680
real grape    0.336686  0.503717  0.740814  0.381641  0.998430
fake grape    0.806648  0.892928  0.890086  0.895887  0.999206
real lemon    0.363814  0.533475  0.493865  0.580109  0.998808
fake lemon    0.819472  0.900731  0.999034  0.820123  0.999618
real avocado  0.830354  0.907265  0.914581  0.900164  0.999829
fake avocado  0.112089  0.201564  1.000000  0.112089  0.998938
real pepper   0.728452  0.842846  0.919964  0.777741  0.998940
fake pepper   0.838863  0.912322  0.946658  0.880481  0.999597
real plant    0.725108  0.840602  0.848696  0.832759  0.996842
fake plant    0.720427  0.837448  0.846184  0.828988  0.999744
real banana   0.232989  0.377895  1.000000  0.232989  0.998277
fake banana   0.575145  0.730226  0.674731  0.795786  0.998919
real onion    0.799284  0.888397  0.872254  0.905252  0.999795
fake onion    0.913200  0.954581  0.993721  0.918501  0.999945
real unknown  0.810160  0.895076  0.924720  0.867366  0.999967
fake unknown  0.140824  0.246848  0.155045  0.605578  0.996887
total         0.592948  0.705908  0.851707  0.680103  0.998739
total(-bg)    0.574739  0.692689  0.845224  0.665597  0.998962
2026-09-23 11:06:56,945 - INFO: Epoch accounting: {'epoch': 156, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11204460, 53591, 70426, 113904, 136510, 102500, 87330, 149096, 201817, 99359, 88589, 29920, 31403, 181279, 138073, 173603, 25746, 87833, 79275, 83801, 53059, 7744, 38954], 'crops_with_class': [202, 33, 29, 36, 36, 31, 29, 32, 40, 46, 33, 12, 14, 53, 34, 21, 25, 24, 27, 37, 25, 8, 19], 'targeted_crops_by_class': [0, 6, 4, 6, 4, 6, 3, 6, 4, 8, 6, 3, 5, 5, 6, 6, 4, 4, 3, 5, 7, 4, 1], 'sampled_scene_counts': [2, 1, 2, 1, 2, 1, 0, 0, 1, 3, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 2, 0, 2, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 3, 2, 1, 1, 0, 1, 4, 2, 0, 1, 2, 3, 4, 1, 3, 0, 1, 1, 1, 2, 1, 0, 1, 3, 1, 1, 3, 0, 2, 2, 1, 3, 0, 1, 3, 2, 2, 2, 1, 3, 1, 2, 4, 3, 5, 1, 1, 0, 1, 0, 1, 0, 3, 3, 2, 1, 3, 2, 1, 1, 0, 1, 2, 0, 1, 1, 5, 1, 1, 2, 1, 1, 1, 0, 0, 2, 2, 1, 0, 2, 1], 'learning_rate': 7.815890847037496e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010681023439715184, 'train_segmentation_loss': 0.4155549001096204, 'val_foreground_miou_all22': 0.5747386371111465, 'val_psnr_ref1': 37.01338760375977, 'elapsed_seconds': 340.3040976524353, 'peak_cuda_allocated_gib': 7.515201568603516}

Epoch 157/500 | Batch 10/202 | Rec 0.001085 | Seg 0.488646 | Elapsed 0.2m | ETA 4.2m
Epoch 157/500 | Batch 20/202 | Rec 0.001076 | Seg 0.451514 | Elapsed 0.4m | ETA 3.9m
Epoch 157/500 | Batch 30/202 | Rec 0.000974 | Seg 0.440446 | Elapsed 0.6m | ETA 3.7m
Epoch 157/500 | Batch 40/202 | Rec 0.000977 | Seg 0.425864 | Elapsed 0.9m | ETA 3.5m
Epoch 157/500 | Batch 50/202 | Rec 0.000933 | Seg 0.398550 | Elapsed 1.1m | ETA 3.2m
Epoch 157/500 | Batch 60/202 | Rec 0.000992 | Seg 0.405101 | Elapsed 1.3m | ETA 3.0m
Epoch 157/500 | Batch 70/202 | Rec 0.000945 | Seg 0.386544 | Elapsed 1.5m | ETA 2.8m
Epoch 157/500 | Batch 80/202 | Rec 0.000941 | Seg 0.392822 | Elapsed 1.7m | ETA 2.6m
Epoch 157/500 | Batch 90/202 | Rec 0.000934 | Seg 0.394621 | Elapsed 1.9m | ETA 2.4m
Epoch 157/500 | Batch 100/202 | Rec 0.000943 | Seg 0.408060 | Elapsed 2.1m | ETA 2.2m
Epoch 157/500 | Batch 110/202 | Rec 0.000950 | Seg 0.405353 | Elapsed 2.4m | ETA 2.0m
Epoch 157/500 | Batch 120/202 | Rec 0.000944 | Seg 0.404256 | Elapsed 2.6m | ETA 1.8m
Epoch 157/500 | Batch 130/202 | Rec 0.000935 | Seg 0.396540 | Elapsed 2.8m | ETA 1.5m
Epoch 157/500 | Batch 140/202 | Rec 0.000935 | Seg 0.397777 | Elapsed 3.0m | ETA 1.3m
Epoch 157/500 | Batch 150/202 | Rec 0.000972 | Seg 0.398426 | Elapsed 3.2m | ETA 1.1m
Epoch 157/500 | Batch 160/202 | Rec 0.000975 | Seg 0.395266 | Elapsed 3.4m | ETA 0.9m
Epoch 157/500 | Batch 170/202 | Rec 0.000958 | Seg 0.391066 | Elapsed 3.6m | ETA 0.7m
Epoch 157/500 | Batch 180/202 | Rec 0.000957 | Seg 0.390670 | Elapsed 3.9m | ETA 0.5m
Epoch 157/500 | Batch 190/202 | Rec 0.000955 | Seg 0.387775 | Elapsed 4.1m | ETA 0.3m
Epoch 157/500 | Batch 200/202 | Rec 0.000948 | Seg 0.387135 | Elapsed 4.3m | ETA 0.0m
Epoch 157/500 | Batch 202/202 | Rec 0.000948 | Seg 0.386564 | Elapsed 4.3m | ETA 0.0m

2026-09-23 11:11:17,058 - INFO: Rec loss: 0.0009479376590882179
2026-09-23 11:11:17,058 - INFO: Seg loss: 0.3865643992724985
2026-09-23 11:11:17,058 - INFO: λ_rec: 1
2026-09-23 11:11:17,058 - INFO: λ_seg: 0.0001
2026-09-23 11:12:33,984 - INFO: -------------------Epoch: 157------------------------
2026-09-23 11:12:33,988 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  36.86798  0.968685  0.000214
2026-09-23 11:12:33,996 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994894  0.997391  0.995882  0.999004  0.995119
real potato   0.912741  0.954330  0.973098  0.936368  0.999893
fake potato   0.939455  0.968733  0.962572  0.975073  0.999954
real apple    0.689460  0.816141  0.988119  0.695223  0.998920
fake apple    0.710421  0.830648  0.928807  0.751334  0.998844
real orange   0.501959  0.668361  0.990002  0.504516  0.999340
fake orange   0.734396  0.846812  0.759062  0.957627  0.999008
real grape    0.620271  0.765590  0.925236  0.653000  0.999165
fake grape    0.831334  0.907850  0.964509  0.857567  0.999356
real lemon    0.339916  0.507322  0.635227  0.422358  0.999036
fake lemon    0.830163  0.907152  0.981127  0.843635  0.999635
real avocado  0.862124  0.925908  0.975809  0.880952  0.999869
fake avocado  0.186560  0.314428  1.000000  0.186560  0.999027
real pepper   0.803649  0.891087  0.883806  0.898590  0.999197
fake pepper   0.886355  0.939704  0.988345  0.895717  0.999726
real plant    0.833844  0.909345  0.910291  0.908500  0.998189
fake plant    0.817356  0.899450  0.901579  0.897431  0.999840
real banana   0.503768  0.669962  0.950125  0.517452  0.998855
fake banana   0.550083  0.709698  0.623563  0.823573  0.998761
real onion    0.777351  0.874680  0.805055  0.957608  0.999752
fake onion    0.866332  0.928330  0.898056  0.960822  0.999906
real unknown  0.751520  0.858085  0.786794  0.943702  0.999950
fake unknown  0.162184  0.279066  0.183348  0.584209  0.997457
total         0.700267  0.798699  0.870018  0.784818  0.999078
total(-bg)    0.686875  0.789667  0.864297  0.775083  0.999258
2026-09-23 11:12:34,544 - INFO: Epoch accounting: {'epoch': 157, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11299898, 57902, 70720, 127933, 110007, 90090, 79790, 141851, 181977, 80757, 62260, 71317, 37581, 218116, 124364, 95932, 27629, 102927, 58816, 100144, 74730, 5172, 18359], 'crops_with_class': [202, 36, 33, 37, 28, 25, 31, 27, 36, 36, 26, 21, 14, 55, 31, 19, 20, 33, 27, 45, 35, 6, 10], 'targeted_crops_by_class': [0, 5, 4, 4, 8, 5, 6, 5, 5, 6, 6, 6, 4, 6, 6, 2, 7, 6, 3, 8, 4, 1, 1], 'sampled_scene_counts': [2, 0, 2, 0, 0, 1, 1, 0, 1, 3, 0, 0, 1, 0, 0, 2, 2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 2, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1, 3, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 1, 3, 1, 2, 1, 4, 3, 2, 1, 1, 0, 1, 2, 0, 5, 1, 2, 1, 1, 1, 1, 1, 2, 3, 1, 4, 1, 0, 2, 0, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 0, 0, 1, 3, 1, 1, 2, 1, 1, 4, 0, 0, 2, 2, 1, 0, 0, 1, 1, 2, 2, 3, 2, 2, 0, 2, 1, 1, 3, 3, 2, 0, 0, 3, 0, 2, 3, 5, 3, 2], 'learning_rate': 7.789917137234833e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009479376590882179, 'train_segmentation_loss': 0.3865643992724985, 'val_foreground_miou_all22': 0.6868746615990463, 'val_psnr_ref1': 36.867980041503905, 'elapsed_seconds': 337.5901429653168, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 158/500 | Batch 10/202 | Rec 0.001145 | Seg 0.525671 | Elapsed 0.2m | ETA 4.1m
Epoch 158/500 | Batch 20/202 | Rec 0.001059 | Seg 0.461420 | Elapsed 0.4m | ETA 3.9m
Epoch 158/500 | Batch 30/202 | Rec 0.000970 | Seg 0.406938 | Elapsed 0.6m | ETA 3.7m
Epoch 158/500 | Batch 40/202 | Rec 0.000984 | Seg 0.424734 | Elapsed 0.9m | ETA 3.5m
Epoch 158/500 | Batch 50/202 | Rec 0.000963 | Seg 0.426070 | Elapsed 1.1m | ETA 3.3m
Epoch 158/500 | Batch 60/202 | Rec 0.001076 | Seg 0.428862 | Elapsed 1.3m | ETA 3.1m
Epoch 158/500 | Batch 70/202 | Rec 0.001123 | Seg 0.442163 | Elapsed 1.5m | ETA 2.9m
Epoch 158/500 | Batch 80/202 | Rec 0.001097 | Seg 0.430316 | Elapsed 1.7m | ETA 2.6m
Epoch 158/500 | Batch 90/202 | Rec 0.001064 | Seg 0.421401 | Elapsed 2.0m | ETA 2.4m
Epoch 158/500 | Batch 100/202 | Rec 0.001057 | Seg 0.423915 | Elapsed 2.2m | ETA 2.2m
Epoch 158/500 | Batch 110/202 | Rec 0.001039 | Seg 0.414811 | Elapsed 2.4m | ETA 2.0m
Epoch 158/500 | Batch 120/202 | Rec 0.001036 | Seg 0.413617 | Elapsed 2.6m | ETA 1.8m
Epoch 158/500 | Batch 130/202 | Rec 0.001027 | Seg 0.412451 | Elapsed 2.8m | ETA 1.6m
Epoch 158/500 | Batch 140/202 | Rec 0.001024 | Seg 0.410040 | Elapsed 3.0m | ETA 1.3m
Epoch 158/500 | Batch 150/202 | Rec 0.001020 | Seg 0.408892 | Elapsed 3.2m | ETA 1.1m
Epoch 158/500 | Batch 160/202 | Rec 0.001024 | Seg 0.410865 | Elapsed 3.5m | ETA 0.9m
Epoch 158/500 | Batch 170/202 | Rec 0.001026 | Seg 0.408637 | Elapsed 3.7m | ETA 0.7m
Epoch 158/500 | Batch 180/202 | Rec 0.001037 | Seg 0.406826 | Elapsed 3.9m | ETA 0.5m
Epoch 158/500 | Batch 190/202 | Rec 0.001054 | Seg 0.403925 | Elapsed 4.1m | ETA 0.3m
Epoch 158/500 | Batch 200/202 | Rec 0.001047 | Seg 0.402975 | Elapsed 4.3m | ETA 0.0m
Epoch 158/500 | Batch 202/202 | Rec 0.001048 | Seg 0.402657 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:16:56,570 - INFO: Rec loss: 0.0010478891859333594
2026-09-23 11:16:56,570 - INFO: Seg loss: 0.40265729495942004
2026-09-23 11:16:56,570 - INFO: λ_rec: 1
2026-09-23 11:16:56,570 - INFO: λ_seg: 0.0001
2026-09-23 11:18:13,263 - INFO: -------------------Epoch: 158------------------------
2026-09-23 11:18:13,267 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.874382  0.968637  0.000214
2026-09-23 11:18:13,275 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994739  0.997313  0.995574  0.999158  0.994969
real potato   0.577256  0.731929  0.999558  0.577404  0.999494
fake potato   0.946554  0.972493  0.984546  0.960829  0.999960
real apple    0.724531  0.840214  0.857742  0.823485  0.998920
fake apple    0.703612  0.825975  0.984129  0.711688  0.998868
real orange   0.703050  0.825587  0.952330  0.728694  0.999594
fake orange   0.757441  0.861932  0.774867  0.971165  0.999110
real grape    0.580205  0.734294  0.964341  0.592926  0.999104
fake grape    0.813660  0.897208  0.926531  0.869777  0.999263
real lemon    0.335737  0.502650  0.439942  0.586341  0.998637
fake lemon    0.826955  0.905232  0.985895  0.836855  0.999630
real avocado  0.740132  0.850612  0.777461  0.939080  0.999694
fake avocado  0.635645  0.777193  0.999599  0.635807  0.999564
real pepper   0.744754  0.853657  0.883093  0.826214  0.998964
fake pepper   0.648555  0.786769  0.997738  0.649510  0.999161
real plant    0.792089  0.883934  0.894526  0.873688  0.997706
fake plant    0.783344  0.878462  0.861434  0.896281  0.999803
real banana   0.187487  0.315744  0.952495  0.189257  0.998157
fake banana   0.527008  0.690201  0.593948  0.823822  0.998640
real onion    0.740135  0.850614  0.787378  0.925013  0.999707
fake onion    0.919082  0.957785  0.957026  0.958646  0.999947
real unknown  0.421869  0.593358  0.424292  0.986641  0.999784
fake unknown  0.260316  0.413054  0.298485  0.670590  0.998394
total         0.668007  0.780270  0.838823  0.784038  0.999003
total(-bg)    0.653155  0.770404  0.831698  0.774260  0.999186
2026-09-23 11:18:13,828 - INFO: Epoch accounting: {'epoch': 158, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11219154, 46614, 59706, 104254, 157353, 79516, 75817, 113181, 162318, 51567, 39522, 46693, 49142, 223629, 169876, 225887, 22651, 85104, 95551, 99603, 65138, 7911, 38085], 'crops_with_class': [202, 29, 24, 26, 37, 23, 22, 20, 32, 24, 17, 15, 17, 53, 39, 30, 23, 29, 31, 40, 31, 11, 17], 'targeted_crops_by_class': [0, 4, 5, 1, 5, 2, 6, 2, 6, 4, 3, 4, 4, 6, 7, 6, 6, 5, 6, 5, 3, 3, 2], 'sampled_scene_counts': [4, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 2, 2, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 2, 1, 1, 0, 2, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 0, 2, 2, 2, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 3, 1, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 0, 3, 1, 1, 2, 1, 2, 3, 1, 1, 0, 0, 2, 2, 0, 1, 5, 0, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 4, 2, 1, 1, 1, 1, 1, 3, 0, 1, 3, 2, 1, 1, 0, 2, 3, 1, 3, 0, 2, 0, 1, 1, 1, 2, 0, 2, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 0, 5, 4], 'learning_rate': 7.763833779759291e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010478891859333594, 'train_segmentation_loss': 0.40265729495942004, 'val_foreground_miou_all22': 0.6531553931448318, 'val_psnr_ref1': 36.87438186645508, 'elapsed_seconds': 339.27584433555603, 'peak_cuda_allocated_gib': 7.506870269775391}

Epoch 159/500 | Batch 10/202 | Rec 0.001060 | Seg 0.428380 | Elapsed 0.2m | ETA 4.2m
Epoch 159/500 | Batch 20/202 | Rec 0.000986 | Seg 0.404378 | Elapsed 0.4m | ETA 3.9m
Epoch 159/500 | Batch 30/202 | Rec 0.000916 | Seg 0.375836 | Elapsed 0.6m | ETA 3.7m
Epoch 159/500 | Batch 40/202 | Rec 0.000934 | Seg 0.381328 | Elapsed 0.9m | ETA 3.5m
Epoch 159/500 | Batch 50/202 | Rec 0.000927 | Seg 0.381015 | Elapsed 1.1m | ETA 3.3m
Epoch 159/500 | Batch 60/202 | Rec 0.000917 | Seg 0.384700 | Elapsed 1.3m | ETA 3.0m
Epoch 159/500 | Batch 70/202 | Rec 0.000923 | Seg 0.388754 | Elapsed 1.5m | ETA 2.8m
Epoch 159/500 | Batch 80/202 | Rec 0.000936 | Seg 0.382553 | Elapsed 1.7m | ETA 2.6m
Epoch 159/500 | Batch 90/202 | Rec 0.000965 | Seg 0.382815 | Elapsed 1.9m | ETA 2.4m
Epoch 159/500 | Batch 100/202 | Rec 0.000962 | Seg 0.383960 | Elapsed 2.2m | ETA 2.2m
Epoch 159/500 | Batch 110/202 | Rec 0.000982 | Seg 0.397706 | Elapsed 2.4m | ETA 2.0m
Epoch 159/500 | Batch 120/202 | Rec 0.000986 | Seg 0.394612 | Elapsed 2.6m | ETA 1.8m
Epoch 159/500 | Batch 130/202 | Rec 0.000971 | Seg 0.393579 | Elapsed 2.8m | ETA 1.5m
Epoch 159/500 | Batch 140/202 | Rec 0.000973 | Seg 0.388373 | Elapsed 3.0m | ETA 1.3m
Epoch 159/500 | Batch 150/202 | Rec 0.000975 | Seg 0.384938 | Elapsed 3.2m | ETA 1.1m
Epoch 159/500 | Batch 160/202 | Rec 0.000978 | Seg 0.388019 | Elapsed 3.5m | ETA 0.9m
Epoch 159/500 | Batch 170/202 | Rec 0.000989 | Seg 0.388792 | Elapsed 3.7m | ETA 0.7m
Epoch 159/500 | Batch 180/202 | Rec 0.000995 | Seg 0.393067 | Elapsed 3.9m | ETA 0.5m
Epoch 159/500 | Batch 190/202 | Rec 0.000991 | Seg 0.395428 | Elapsed 4.1m | ETA 0.3m
Epoch 159/500 | Batch 200/202 | Rec 0.000976 | Seg 0.389901 | Elapsed 4.3m | ETA 0.0m
Epoch 159/500 | Batch 202/202 | Rec 0.000977 | Seg 0.389899 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:22:35,973 - INFO: Rec loss: 0.0009767414591653218
2026-09-23 11:22:35,973 - INFO: Seg loss: 0.38989944383502007
2026-09-23 11:22:35,973 - INFO: λ_rec: 1
2026-09-23 11:22:35,973 - INFO: λ_seg: 0.0001
2026-09-23 11:23:53,530 - INFO: -------------------Epoch: 159------------------------
2026-09-23 11:23:53,535 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.482078  0.968942  0.000186
2026-09-23 11:23:53,543 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.993857  0.996869  0.994441  0.999409  0.994119
real potato   0.196634  0.328617  1.000000  0.196634  0.999039
fake potato   0.022832  0.044640  0.999999  0.022832  0.999288
real apple    0.630570  0.773385  0.694550  0.872534  0.998236
fake apple    0.755395  0.860606  0.983127  0.765317  0.999064
real orange   0.458849  0.629013  0.999244  0.459009  0.999287
fake orange   0.721138  0.837929  0.748857  0.951178  0.998947
real grape    0.575930  0.730859  0.845165  0.643865  0.999010
fake grape    0.814030  0.897432  0.936472  0.861610  0.999272
real lemon    0.409718  0.581231  0.454619  0.805765  0.998636
fake lemon    0.802869  0.890608  0.987187  0.811323  0.999579
real avocado  0.800432  0.889106  0.867291  0.912151  0.999789
fake avocado  0.094364  0.172438  1.000000  0.094364  0.998916
real pepper   0.784501  0.879189  0.881803  0.876689  0.999119
fake pepper   0.706398  0.827892  0.999186  0.706805  0.999300
real plant    0.787145  0.880847  0.923117  0.842369  0.997722
fake plant    0.813095  0.896864  0.967806  0.835698  0.999847
real banana   0.238909  0.385646  0.995478  0.239169  0.998288
fake banana   0.657934  0.793631  0.985242  0.664482  0.999364
real onion    0.555836  0.714470  0.895648  0.594325  0.999571
fake onion    0.934058  0.965855  0.998709  0.935187  0.999958
real unknown  0.889943  0.941717  0.993644  0.895038  0.999982
fake unknown  0.165925  0.284592  0.178456  0.702644  0.997024
total         0.600450  0.704497  0.883915  0.682104  0.998842
total(-bg)    0.582568  0.691208  0.878891  0.667681  0.999056
2026-09-23 11:23:54,310 - INFO: Epoch accounting: {'epoch': 159, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11329115, 42348, 55698, 128718, 133340, 63646, 85094, 120143, 206337, 71736, 91455, 50430, 35743, 171721, 92133, 187526, 31922, 86985, 59930, 75844, 50062, 16144, 52202], 'crops_with_class': [202, 26, 27, 38, 34, 24, 27, 27, 39, 34, 37, 17, 20, 48, 26, 23, 28, 26, 27, 35, 21, 17, 21], 'targeted_crops_by_class': [0, 4, 0, 6, 3, 5, 4, 2, 6, 5, 5, 6, 7, 5, 1, 6, 6, 3, 5, 1, 7, 8, 2], 'sampled_scene_counts': [1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 0, 0, 0, 0, 2, 3, 1, 2, 3, 1, 0, 1, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 3, 1, 0, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 2, 0, 1, 1, 0, 2, 1, 2, 2, 1, 0, 3, 1, 0, 2, 2, 0, 1, 4, 2, 2, 2, 3, 2, 1, 0, 0, 0, 1, 0, 1, 1, 2, 2, 1, 5, 2, 5, 3, 2, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 1, 1, 4, 3, 0, 0, 2, 0, 4, 1, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1, 0, 0, 3, 0, 2, 0, 1, 0], 'learning_rate': 7.737641804337162e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009767414591653218, 'train_segmentation_loss': 0.38989944383502007, 'val_foreground_miou_all22': 0.5825683777798008, 'val_psnr_ref1': 37.48207763671875, 'elapsed_seconds': 340.4727883338928, 'peak_cuda_allocated_gib': 7.507846832275391}

Epoch 160/500 | Batch 10/202 | Rec 0.000988 | Seg 0.364983 | Elapsed 0.2m | ETA 4.1m
Epoch 160/500 | Batch 20/202 | Rec 0.000954 | Seg 0.413177 | Elapsed 0.4m | ETA 3.9m
Epoch 160/500 | Batch 30/202 | Rec 0.000921 | Seg 0.400264 | Elapsed 0.7m | ETA 3.7m
Epoch 160/500 | Batch 40/202 | Rec 0.000912 | Seg 0.390906 | Elapsed 0.9m | ETA 3.5m
Epoch 160/500 | Batch 50/202 | Rec 0.000950 | Seg 0.395151 | Elapsed 1.1m | ETA 3.3m
Epoch 160/500 | Batch 60/202 | Rec 0.000980 | Seg 0.408315 | Elapsed 1.3m | ETA 3.1m
Epoch 160/500 | Batch 70/202 | Rec 0.000974 | Seg 0.403230 | Elapsed 1.5m | ETA 2.9m
Epoch 160/500 | Batch 80/202 | Rec 0.000965 | Seg 0.399130 | Elapsed 1.7m | ETA 2.6m
Epoch 160/500 | Batch 90/202 | Rec 0.000967 | Seg 0.408285 | Elapsed 1.9m | ETA 2.4m
Epoch 160/500 | Batch 100/202 | Rec 0.000961 | Seg 0.400971 | Elapsed 2.2m | ETA 2.2m
Epoch 160/500 | Batch 110/202 | Rec 0.000963 | Seg 0.397999 | Elapsed 2.4m | ETA 2.0m
Epoch 160/500 | Batch 120/202 | Rec 0.000950 | Seg 0.389650 | Elapsed 2.6m | ETA 1.8m
Epoch 160/500 | Batch 130/202 | Rec 0.000947 | Seg 0.392573 | Elapsed 2.8m | ETA 1.6m
Epoch 160/500 | Batch 140/202 | Rec 0.000951 | Seg 0.394292 | Elapsed 3.0m | ETA 1.3m
Epoch 160/500 | Batch 150/202 | Rec 0.000954 | Seg 0.394536 | Elapsed 3.3m | ETA 1.1m
Epoch 160/500 | Batch 160/202 | Rec 0.000955 | Seg 0.393440 | Elapsed 3.5m | ETA 0.9m
Epoch 160/500 | Batch 170/202 | Rec 0.000956 | Seg 0.396279 | Elapsed 3.7m | ETA 0.7m
Epoch 160/500 | Batch 180/202 | Rec 0.000957 | Seg 0.396378 | Elapsed 3.9m | ETA 0.5m
Epoch 160/500 | Batch 190/202 | Rec 0.000943 | Seg 0.391180 | Elapsed 4.2m | ETA 0.3m
Epoch 160/500 | Batch 200/202 | Rec 0.000947 | Seg 0.388742 | Elapsed 4.4m | ETA 0.0m
Epoch 160/500 | Batch 202/202 | Rec 0.000943 | Seg 0.387854 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:28:18,965 - INFO: Rec loss: 0.0009430346603904122
2026-09-23 11:28:18,965 - INFO: Seg loss: 0.3878541665133273
2026-09-23 11:28:18,965 - INFO: λ_rec: 1
2026-09-23 11:28:18,965 - INFO: λ_seg: 0.0001
2026-09-23 11:29:36,383 - INFO: -------------------Epoch: 160------------------------
2026-09-23 11:29:36,387 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.267045  0.969842  0.000195
2026-09-23 11:29:36,395 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994899  0.997393  0.996120  0.998769  0.995125
real potato   0.524981  0.688463  0.999030  0.525249  0.999431
fake potato   0.872283  0.931736  0.986654  0.882698  0.999906
real apple    0.679730  0.809282  0.776235  0.845378  0.998626
fake apple    0.651094  0.788633  0.968518  0.665171  0.998654
real orange   0.337421  0.504545  0.945293  0.344141  0.999109
fake orange   0.721721  0.838322  0.734963  0.975642  0.998923
real grape    0.617787  0.763694  0.826679  0.709713  0.999083
fake grape    0.827125  0.905334  0.938316  0.874685  0.999324
real lemon    0.303089  0.465136  0.465428  0.464944  0.998744
fake lemon    0.830312  0.907240  0.992293  0.835701  0.999639
real avocado  0.764176  0.866276  0.934106  0.807718  0.999768
fake avocado  0.547800  0.707795  0.866187  0.598444  0.999409
real pepper   0.847662  0.917501  0.937647  0.898298  0.999409
fake pepper   0.892923  0.943383  0.950078  0.936880  0.999732
real plant    0.823684  0.903269  0.901002  0.905647  0.998061
fake plant    0.840051  0.913024  0.949865  0.879026  0.999867
real banana   0.381905  0.552681  0.939394  0.391552  0.998576
fake banana   0.514534  0.679413  0.572566  0.835435  0.998550
real onion    0.693671  0.819084  0.916580  0.740415  0.999705
fake onion    0.948625  0.973585  0.997211  0.951149  0.999967
real unknown  0.908370  0.951935  0.922182  0.983779  0.999984
fake unknown  0.203787  0.338535  0.242042  0.563202  0.998146
total         0.683810  0.789837  0.859060  0.765810  0.999032
total(-bg)    0.669669  0.780403  0.852830  0.755221  0.999210
2026-09-23 11:29:36,987 - INFO: Epoch accounting: {'epoch': 160, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11281093, 65835, 83630, 121886, 101086, 92571, 82896, 150274, 169564, 69564, 48170, 41285, 33468, 240718, 125552, 97243, 18176, 105226, 83544, 114846, 66212, 13582, 31851], 'crops_with_class': [202, 40, 38, 33, 27, 23, 29, 26, 36, 29, 19, 13, 14, 60, 38, 13, 19, 32, 31, 45, 32, 12, 17], 'targeted_crops_by_class': [0, 6, 4, 5, 0, 5, 7, 4, 9, 6, 3, 4, 2, 7, 4, 1, 1, 6, 4, 10, 5, 5, 3], 'sampled_scene_counts': [1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 3, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 3, 0, 2, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 2, 1, 0, 2, 1, 2, 2, 0, 0, 0, 1, 0, 2, 0, 3, 1, 1, 2, 1, 1, 2, 1, 1, 1, 0, 1, 1, 2, 2, 0, 1, 2, 1, 5, 0, 1, 2, 3, 3, 2, 1, 1, 0, 2, 1, 1, 2, 3, 2, 1, 1, 3, 1, 1, 1, 1, 4, 2, 1, 1, 2, 1, 2, 3, 2, 2, 0, 2, 1, 0, 2, 2, 3, 3], 'learning_rate': 7.711342244982788e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009430346603904122, 'train_segmentation_loss': 0.3878541665133273, 'val_foreground_miou_all22': 0.6696694934454029, 'val_psnr_ref1': 37.26704452514648, 'elapsed_seconds': 342.6676585674286, 'peak_cuda_allocated_gib': 7.513370513916016}

Epoch 161/500 | Batch 10/202 | Rec 0.000916 | Seg 0.415599 | Elapsed 0.2m | ETA 4.2m
Epoch 161/500 | Batch 20/202 | Rec 0.000916 | Seg 0.395402 | Elapsed 0.4m | ETA 4.0m
Epoch 161/500 | Batch 30/202 | Rec 0.000864 | Seg 0.372886 | Elapsed 0.7m | ETA 3.8m
Epoch 161/500 | Batch 40/202 | Rec 0.000968 | Seg 0.410078 | Elapsed 0.9m | ETA 3.5m
Epoch 161/500 | Batch 50/202 | Rec 0.000959 | Seg 0.397453 | Elapsed 1.1m | ETA 3.3m
Epoch 161/500 | Batch 60/202 | Rec 0.000969 | Seg 0.405935 | Elapsed 1.3m | ETA 3.1m
Epoch 161/500 | Batch 70/202 | Rec 0.001036 | Seg 0.425465 | Elapsed 1.5m | ETA 2.8m
Epoch 161/500 | Batch 80/202 | Rec 0.001029 | Seg 0.408688 | Elapsed 1.7m | ETA 2.6m
Epoch 161/500 | Batch 90/202 | Rec 0.001019 | Seg 0.405787 | Elapsed 1.9m | ETA 2.4m
Epoch 161/500 | Batch 100/202 | Rec 0.001046 | Seg 0.403596 | Elapsed 2.2m | ETA 2.2m
Epoch 161/500 | Batch 110/202 | Rec 0.001033 | Seg 0.400779 | Elapsed 2.4m | ETA 2.0m
Epoch 161/500 | Batch 120/202 | Rec 0.001043 | Seg 0.397048 | Elapsed 2.6m | ETA 1.8m
Epoch 161/500 | Batch 130/202 | Rec 0.001039 | Seg 0.393828 | Elapsed 2.8m | ETA 1.6m
Epoch 161/500 | Batch 140/202 | Rec 0.001031 | Seg 0.391631 | Elapsed 3.0m | ETA 1.3m
Epoch 161/500 | Batch 150/202 | Rec 0.001031 | Seg 0.396110 | Elapsed 3.2m | ETA 1.1m
Epoch 161/500 | Batch 160/202 | Rec 0.001028 | Seg 0.399471 | Elapsed 3.5m | ETA 0.9m
Epoch 161/500 | Batch 170/202 | Rec 0.001023 | Seg 0.402319 | Elapsed 3.7m | ETA 0.7m
Epoch 161/500 | Batch 180/202 | Rec 0.001022 | Seg 0.400011 | Elapsed 3.9m | ETA 0.5m
Epoch 161/500 | Batch 190/202 | Rec 0.001024 | Seg 0.401678 | Elapsed 4.1m | ETA 0.3m
Epoch 161/500 | Batch 200/202 | Rec 0.001024 | Seg 0.400984 | Elapsed 4.3m | ETA 0.0m
Epoch 161/500 | Batch 202/202 | Rec 0.001026 | Seg 0.401957 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:33:59,186 - INFO: Rec loss: 0.0010258470835408547
2026-09-23 11:33:59,186 - INFO: Seg loss: 0.40195671542741285
2026-09-23 11:33:59,186 - INFO: λ_rec: 1
2026-09-23 11:33:59,186 - INFO: λ_seg: 0.0001
2026-09-23 11:35:16,814 - INFO: -------------------Epoch: 161------------------------
2026-09-23 11:35:16,818 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  36.804745  0.967744  0.000215
2026-09-23 11:35:16,827 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994388  0.997136  0.995127  0.999254  0.994631
real potato   0.464618  0.634413  0.999726  0.464677  0.999359
fake potato   0.931687  0.964586  0.981361  0.948471  0.999949
real apple    0.670821  0.802934  0.787729  0.818841  0.998614
fake apple    0.687750  0.814942  0.972594  0.701342  0.998798
real orange   0.513262  0.678306  0.938792  0.531033  0.999336
fake orange   0.759273  0.863117  0.781135  0.964449  0.999125
real grape    0.638768  0.779521  0.852115  0.718410  0.999152
fake grape    0.814163  0.897513  0.946850  0.853153  0.999280
real lemon    0.190237  0.319612  0.298882  0.343547  0.998281
fake lemon    0.811280  0.895759  0.956436  0.842409  0.999585
real avocado  0.737626  0.848955  0.795409  0.910345  0.999699
fake avocado  0.699789  0.823334  0.964231  0.718439  0.999631
real pepper   0.726140  0.841296  0.822793  0.860754  0.998813
fake pepper   0.784502  0.879190  0.977219  0.799117  0.999477
real plant    0.819171  0.900548  0.933204  0.870195  0.998079
fake plant    0.817484  0.899528  0.900962  0.898198  0.999840
real banana   0.185308  0.312648  0.984178  0.185862  0.998164
fake banana   0.486747  0.654733  0.561108  0.785999  0.998475
real onion    0.688724  0.815624  0.871686  0.766425  0.999687
fake onion    0.936603  0.967214  0.988636  0.946796  0.999960
real unknown  0.877056  0.934452  0.904464  0.966603  0.999978
fake unknown  0.246774  0.395813  0.311249  0.543644  0.998602
total         0.673138  0.779181  0.848952  0.758172  0.998979
total(-bg)    0.658536  0.769274  0.842307  0.747214  0.999177
2026-09-23 11:35:17,457 - INFO: Epoch accounting: {'epoch': 161, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11213438, 63481, 58727, 138048, 122910, 54564, 58709, 109504, 287880, 67539, 56944, 49646, 25350, 253292, 115343, 136178, 22454, 90751, 82656, 122438, 65589, 10557, 32274], 'crops_with_class': [202, 33, 30, 33, 33, 20, 25, 23, 41, 29, 22, 17, 12, 58, 29, 18, 21, 28, 34, 46, 31, 9, 18], 'targeted_crops_by_class': [0, 5, 4, 9, 3, 4, 2, 4, 8, 4, 3, 4, 2, 5, 3, 2, 6, 8, 6, 7, 7, 2, 4], 'sampled_scene_counts': [1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 3, 0, 1, 0, 2, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 0, 2, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 3, 0, 0, 1, 0, 2, 1, 0, 1, 0, 1, 0, 2, 2, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 0, 2, 4, 0, 0, 0, 4, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 2, 0, 1, 1, 1, 2, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 4, 2, 1, 1, 1, 1, 2, 0, 0, 4, 2, 3, 2, 2, 2, 3, 2, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 4, 2, 2, 2, 1, 0, 2, 0, 2, 2, 1, 1, 3], 'learning_rate': 7.68493613995774e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0010258470835408547, 'train_segmentation_loss': 0.40195671542741285, 'val_foreground_miou_all22': 0.6585356812223264, 'val_psnr_ref1': 36.8047445678711, 'elapsed_seconds': 340.46186351776123, 'peak_cuda_allocated_gib': 7.510295867919922}

Epoch 162/500 | Batch 10/202 | Rec 0.000743 | Seg 0.359685 | Elapsed 0.2m | ETA 4.1m
Epoch 162/500 | Batch 20/202 | Rec 0.000837 | Seg 0.396030 | Elapsed 0.4m | ETA 3.9m
Epoch 162/500 | Batch 30/202 | Rec 0.000891 | Seg 0.400522 | Elapsed 0.6m | ETA 3.7m
Epoch 162/500 | Batch 40/202 | Rec 0.000897 | Seg 0.398391 | Elapsed 0.9m | ETA 3.5m
Epoch 162/500 | Batch 50/202 | Rec 0.000916 | Seg 0.405695 | Elapsed 1.1m | ETA 3.2m
Epoch 162/500 | Batch 60/202 | Rec 0.000943 | Seg 0.404912 | Elapsed 1.3m | ETA 3.0m
Epoch 162/500 | Batch 70/202 | Rec 0.000965 | Seg 0.408562 | Elapsed 1.5m | ETA 2.8m
Epoch 162/500 | Batch 80/202 | Rec 0.000952 | Seg 0.401110 | Elapsed 1.7m | ETA 2.6m
Epoch 162/500 | Batch 90/202 | Rec 0.000934 | Seg 0.392607 | Elapsed 1.9m | ETA 2.4m
Epoch 162/500 | Batch 100/202 | Rec 0.000929 | Seg 0.390697 | Elapsed 2.2m | ETA 2.2m
Epoch 162/500 | Batch 110/202 | Rec 0.000924 | Seg 0.386313 | Elapsed 2.4m | ETA 2.0m
Epoch 162/500 | Batch 120/202 | Rec 0.000941 | Seg 0.390889 | Elapsed 2.6m | ETA 1.8m
Epoch 162/500 | Batch 130/202 | Rec 0.000924 | Seg 0.390809 | Elapsed 2.8m | ETA 1.6m
Epoch 162/500 | Batch 140/202 | Rec 0.000937 | Seg 0.394847 | Elapsed 3.0m | ETA 1.3m
Epoch 162/500 | Batch 150/202 | Rec 0.000918 | Seg 0.389783 | Elapsed 3.2m | ETA 1.1m
Epoch 162/500 | Batch 160/202 | Rec 0.000917 | Seg 0.391120 | Elapsed 3.5m | ETA 0.9m
Epoch 162/500 | Batch 170/202 | Rec 0.000932 | Seg 0.393351 | Elapsed 3.7m | ETA 0.7m
Epoch 162/500 | Batch 180/202 | Rec 0.000932 | Seg 0.393949 | Elapsed 3.9m | ETA 0.5m
Epoch 162/500 | Batch 190/202 | Rec 0.000927 | Seg 0.391244 | Elapsed 4.1m | ETA 0.3m
Epoch 162/500 | Batch 200/202 | Rec 0.000920 | Seg 0.386256 | Elapsed 4.3m | ETA 0.0m
Epoch 162/500 | Batch 202/202 | Rec 0.000919 | Seg 0.384626 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:39:40,177 - INFO: Rec loss: 0.0009185808984790974
2026-09-23 11:39:40,177 - INFO: Seg loss: 0.3846258314529268
2026-09-23 11:39:40,177 - INFO: λ_rec: 1
2026-09-23 11:39:40,177 - INFO: λ_seg: 0.0001
2026-09-23 11:40:57,784 - INFO: -------------------Epoch: 162------------------------
2026-09-23 11:40:57,788 - INFO:
Validation stats:
        PSNR      SSIM     MSE
0  37.163112  0.969763  0.0002
2026-09-23 11:40:57,796 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994384  0.997134  0.995325  0.999050  0.994628
real potato   0.753156  0.859151  0.999831  0.753252  0.999705
fake potato   0.582658  0.736256  0.987663  0.586929  0.999694
real apple    0.591126  0.742981  0.919384  0.623441  0.998512
fake apple    0.585711  0.738689  0.976613  0.594043  0.998414
real orange   0.516095  0.680777  1.000000  0.516095  0.999362
fake orange   0.783314  0.878443  0.813129  0.955282  0.999243
real grape    0.636344  0.777713  0.711351  0.857853  0.998976
fake grape    0.796207  0.886492  0.848544  0.928103  0.999121
real lemon    0.341837  0.509457  0.466028  0.561932  0.998728
fake lemon    0.676956  0.807315  1.000000  0.676956  0.999317
real avocado  0.772285  0.871464  0.822997  0.926108  0.999746
fake avocado  0.144385  0.252314  0.989529  0.144606  0.998975
real pepper   0.743656  0.852935  0.857571  0.848448  0.998930
fake pepper   0.875352  0.933484  0.998323  0.876640  0.999702
real plant    0.823219  0.902989  0.971421  0.843651  0.998188
fake plant    0.696634  0.821146  0.743777  0.916603  0.999682
real banana   0.399464  0.570840  0.966154  0.405134  0.998631
fake banana   0.576946  0.731676  0.668680  0.807896  0.998910
real onion    0.814546  0.897746  0.868858  0.928728  0.999809
fake onion    0.943035  0.970632  0.989204  0.952842  0.999964
real unknown  0.710870  0.830954  0.747144  0.936069  0.999939
fake unknown  0.184069  0.310878  0.193209  0.795545  0.997029
total         0.649663  0.763542  0.849336  0.758052  0.998922
total(-bg)    0.633994  0.752924  0.842700  0.747098  0.999117
2026-09-23 11:40:58,386 - INFO: Epoch accounting: {'epoch': 162, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11278214, 52786, 64116, 140057, 129638, 91201, 57182, 140786, 179082, 75457, 74508, 40491, 36914, 251240, 120760, 89547, 26331, 98115, 82546, 88977, 55180, 8400, 56744], 'crops_with_class': [202, 35, 27, 38, 37, 26, 19, 26, 40, 36, 30, 12, 16, 61, 39, 18, 21, 29, 33, 40, 29, 9, 21], 'targeted_crops_by_class': [0, 8, 4, 4, 3, 5, 3, 4, 8, 8, 7, 5, 6, 3, 3, 2, 4, 7, 7, 3, 5, 2, 2], 'sampled_scene_counts': [1, 0, 2, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 2, 3, 1, 1, 0, 0, 0, 0, 0, 1, 3, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 3, 1, 0, 1, 1, 3, 0, 1, 3, 1, 0, 2, 1, 3, 1, 4, 0, 1, 0, 2, 1, 1, 2, 3, 4, 2, 1, 1, 2, 2, 2, 1, 0, 1, 1, 3, 2, 0, 0, 4, 3, 2, 1, 3, 2, 1, 2, 2, 3, 1, 1, 1, 2, 1, 1, 3, 1, 0, 1, 1, 2, 1, 2, 1, 2, 4, 1, 1, 1, 1, 0, 3, 2, 1, 0, 1, 1, 1, 4, 1, 1, 3, 1], 'learning_rate': 7.65842453172983e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009185808984790974, 'train_segmentation_loss': 0.3846258314529268, 'val_foreground_miou_all22': 0.6339938348336627, 'val_psnr_ref1': 37.16311233520508, 'elapsed_seconds': 340.9202649593353, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 163/500 | Batch 10/202 | Rec 0.000885 | Seg 0.380628 | Elapsed 0.2m | ETA 4.2m
Epoch 163/500 | Batch 20/202 | Rec 0.000960 | Seg 0.385189 | Elapsed 0.4m | ETA 4.0m
Epoch 163/500 | Batch 30/202 | Rec 0.000920 | Seg 0.371228 | Elapsed 0.7m | ETA 3.7m
Epoch 163/500 | Batch 40/202 | Rec 0.000906 | Seg 0.364431 | Elapsed 0.9m | ETA 3.5m
Epoch 163/500 | Batch 50/202 | Rec 0.000928 | Seg 0.387211 | Elapsed 1.1m | ETA 3.3m
Epoch 163/500 | Batch 60/202 | Rec 0.000919 | Seg 0.384130 | Elapsed 1.3m | ETA 3.1m
Epoch 163/500 | Batch 70/202 | Rec 0.000937 | Seg 0.389946 | Elapsed 1.5m | ETA 2.9m
Epoch 163/500 | Batch 80/202 | Rec 0.000937 | Seg 0.382153 | Elapsed 1.7m | ETA 2.6m
Epoch 163/500 | Batch 90/202 | Rec 0.000911 | Seg 0.378180 | Elapsed 1.9m | ETA 2.4m
Epoch 163/500 | Batch 100/202 | Rec 0.000908 | Seg 0.376416 | Elapsed 2.2m | ETA 2.2m
Epoch 163/500 | Batch 110/202 | Rec 0.000915 | Seg 0.383881 | Elapsed 2.4m | ETA 2.0m
Epoch 163/500 | Batch 120/202 | Rec 0.000932 | Seg 0.380940 | Elapsed 2.6m | ETA 1.8m
Epoch 163/500 | Batch 130/202 | Rec 0.000923 | Seg 0.376539 | Elapsed 2.8m | ETA 1.6m
Epoch 163/500 | Batch 140/202 | Rec 0.000936 | Seg 0.389839 | Elapsed 3.0m | ETA 1.3m
Epoch 163/500 | Batch 150/202 | Rec 0.000960 | Seg 0.391505 | Elapsed 3.3m | ETA 1.1m
Epoch 163/500 | Batch 160/202 | Rec 0.000972 | Seg 0.397958 | Elapsed 3.5m | ETA 0.9m
Epoch 163/500 | Batch 170/202 | Rec 0.000966 | Seg 0.396003 | Elapsed 3.7m | ETA 0.7m
Epoch 163/500 | Batch 180/202 | Rec 0.000961 | Seg 0.395181 | Elapsed 3.9m | ETA 0.5m
Epoch 163/500 | Batch 190/202 | Rec 0.000964 | Seg 0.398705 | Elapsed 4.1m | ETA 0.3m
Epoch 163/500 | Batch 200/202 | Rec 0.000965 | Seg 0.397229 | Elapsed 4.3m | ETA 0.0m
Epoch 163/500 | Batch 202/202 | Rec 0.000964 | Seg 0.397270 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:45:20,871 - INFO: Rec loss: 0.0009640297377862424
2026-09-23 11:45:20,871 - INFO: Seg loss: 0.3972702495532461
2026-09-23 11:45:20,871 - INFO: λ_rec: 1
2026-09-23 11:45:20,871 - INFO: λ_seg: 0.0001
2026-09-23 11:46:38,403 - INFO: -------------------Epoch: 163------------------------
2026-09-23 11:46:38,407 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.055188  0.969008  0.000205
2026-09-23 11:46:38,416 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994446  0.997165  0.995280  0.999158  0.994688
real potato   0.785678  0.879928  0.999028  0.786279  0.999743
fake potato   0.670327  0.802582  0.984180  0.677629  0.999757
real apple    0.784540  0.879213  0.930257  0.833569  0.999210
fake apple    0.742905  0.852441  0.980098  0.754284  0.999014
real orange   0.461494  0.631494  0.981210  0.465609  0.999284
fake orange   0.734170  0.846661  0.754852  0.964023  0.999001
real grape    0.403567  0.575014  0.848446  0.434919  0.998658
fake grape    0.798285  0.887779  0.955286  0.829270  0.999225
real lemon    0.110624  0.199163  0.262588  0.160478  0.998484
fake lemon    0.824575  0.903805  0.987938  0.832961  0.999625
real avocado  0.610511  0.758109  0.877049  0.667652  0.999604
fake avocado  0.153502  0.266124  0.854772  0.157613  0.998960
real pepper   0.781937  0.877576  0.965643  0.804313  0.999180
fake pepper   0.844388  0.915580  0.910443  0.920876  0.999595
real plant    0.780094  0.876414  0.856529  0.897349  0.997470
fake plant    0.769270  0.869540  0.861090  0.878259  0.999790
real banana   0.359721  0.529071  0.987748  0.361334  0.998555
fake banana   0.489069  0.656830  0.559135  0.796035  0.998470
real onion    0.752955  0.859019  0.827543  0.893092  0.999735
fake onion    0.930078  0.963723  0.979042  0.948972  0.999955
real unknown  0.922516  0.959646  0.953817  0.965649  0.999987
fake unknown  0.144303  0.252177  0.162518  0.562840  0.997188
total         0.645607  0.749524  0.846717  0.721398  0.998921
total(-bg)    0.629750  0.738268  0.839964  0.708773  0.999113
2026-09-23 11:46:39,011 - INFO: Epoch accounting: {'epoch': 163, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11229760, 60082, 65430, 101267, 143087, 80756, 101545, 118667, 214536, 63112, 63230, 46729, 48504, 233439, 108571, 180135, 26269, 99010, 83418, 69812, 44555, 8465, 47893], 'crops_with_class': [202, 32, 28, 30, 38, 27, 36, 24, 37, 35, 26, 18, 17, 57, 29, 22, 24, 28, 33, 34, 20, 11, 23], 'targeted_crops_by_class': [0, 9, 5, 3, 7, 4, 9, 1, 6, 3, 6, 4, 4, 4, 4, 5, 5, 9, 6, 4, 2, 3, 6], 'sampled_scene_counts': [0, 0, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 3, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 2, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 3, 2, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 3, 2, 0, 1, 3, 2, 1, 0, 3, 1, 3, 1, 2, 1, 2, 1, 2, 1, 1, 0, 1, 1, 0, 1, 5, 2, 2, 1, 1, 2, 3, 2, 0, 4, 0, 0, 1, 1, 0, 3, 3, 1, 4, 1, 2, 2, 1, 0, 3, 0, 1, 1, 0, 2, 0, 0, 1, 0, 2, 1, 0, 2, 4, 2, 2, 1, 2, 2, 0, 1, 3, 0, 2, 1, 0, 1, 1, 4, 1, 2, 2], 'learning_rate': 7.631808466931957e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009640297377862424, 'train_segmentation_loss': 0.3972702495532461, 'val_foreground_miou_all22': 0.6297503752679909, 'val_psnr_ref1': 37.05518829345703, 'elapsed_seconds': 340.616238117218, 'peak_cuda_allocated_gib': 7.509777069091797}

Epoch 164/500 | Batch 10/202 | Rec 0.000973 | Seg 0.417034 | Elapsed 0.2m | ETA 4.1m
Epoch 164/500 | Batch 20/202 | Rec 0.000916 | Seg 0.388817 | Elapsed 0.4m | ETA 4.0m
Epoch 164/500 | Batch 30/202 | Rec 0.000920 | Seg 0.379758 | Elapsed 0.7m | ETA 3.8m
Epoch 164/500 | Batch 40/202 | Rec 0.000884 | Seg 0.366420 | Elapsed 0.9m | ETA 3.6m
Epoch 164/500 | Batch 50/202 | Rec 0.000881 | Seg 0.353535 | Elapsed 1.1m | ETA 3.3m
Epoch 164/500 | Batch 60/202 | Rec 0.000906 | Seg 0.371992 | Elapsed 1.3m | ETA 3.1m
Epoch 164/500 | Batch 70/202 | Rec 0.000939 | Seg 0.383322 | Elapsed 1.5m | ETA 2.9m
Epoch 164/500 | Batch 80/202 | Rec 0.000928 | Seg 0.378493 | Elapsed 1.7m | ETA 2.7m
Epoch 164/500 | Batch 90/202 | Rec 0.000936 | Seg 0.380127 | Elapsed 2.0m | ETA 2.4m
Epoch 164/500 | Batch 100/202 | Rec 0.000936 | Seg 0.376959 | Elapsed 2.2m | ETA 2.2m
Epoch 164/500 | Batch 110/202 | Rec 0.000949 | Seg 0.381616 | Elapsed 2.4m | ETA 2.0m
Epoch 164/500 | Batch 120/202 | Rec 0.000971 | Seg 0.385002 | Elapsed 2.6m | ETA 1.8m
Epoch 164/500 | Batch 130/202 | Rec 0.000971 | Seg 0.391967 | Elapsed 2.8m | ETA 1.6m
Epoch 164/500 | Batch 140/202 | Rec 0.000961 | Seg 0.386463 | Elapsed 3.0m | ETA 1.3m
Epoch 164/500 | Batch 150/202 | Rec 0.000978 | Seg 0.386195 | Elapsed 3.3m | ETA 1.1m
Epoch 164/500 | Batch 160/202 | Rec 0.000992 | Seg 0.387970 | Elapsed 3.5m | ETA 0.9m
Epoch 164/500 | Batch 170/202 | Rec 0.000983 | Seg 0.385928 | Elapsed 3.7m | ETA 0.7m
Epoch 164/500 | Batch 180/202 | Rec 0.000988 | Seg 0.388423 | Elapsed 3.9m | ETA 0.5m
Epoch 164/500 | Batch 190/202 | Rec 0.000988 | Seg 0.385021 | Elapsed 4.1m | ETA 0.3m
Epoch 164/500 | Batch 200/202 | Rec 0.000996 | Seg 0.386311 | Elapsed 4.3m | ETA 0.0m
Epoch 164/500 | Batch 202/202 | Rec 0.000999 | Seg 0.387864 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:51:02,104 - INFO: Rec loss: 0.0009985952116525962
2026-09-23 11:51:02,104 - INFO: Seg loss: 0.38786436370251204
2026-09-23 11:51:02,104 - INFO: λ_rec: 1
2026-09-23 11:51:02,104 - INFO: λ_seg: 0.0001
2026-09-23 11:52:19,558 - INFO: -------------------Epoch: 164------------------------
2026-09-23 11:52:19,562 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.027413  0.968101  0.000206
2026-09-23 11:52:19,570 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994754  0.997320  0.995550  0.999197  0.994983
real potato   0.921938  0.959334  0.991563  0.929227  0.999906
fake potato   0.954228  0.976528  0.979355  0.973816  0.999966
real apple    0.739280  0.850050  0.995195  0.741928  0.999097
fake apple    0.657929  0.793627  0.906167  0.706030  0.998614
real orange   0.665703  0.799258  0.997402  0.666860  0.999559
fake orange   0.829854  0.906967  0.848216  0.974576  0.999428
real grape    0.709017  0.829687  0.882852  0.782650  0.999329
fake grape    0.865766  0.928004  0.930827  0.925298  0.999469
real lemon    0.252256  0.402833  0.484406  0.344845  0.998799
fake lemon    0.794487  0.885426  0.921266  0.852362  0.999534
real avocado  0.784086  0.878928  0.871389  0.886699  0.999773
fake avocado  0.594139  0.745357  0.991531  0.597169  0.999512
real pepper   0.797161  0.887084  0.908304  0.866928  0.999193
fake pepper   0.802207  0.890199  0.873468  0.907688  0.999467
real plant    0.831182  0.907760  0.956877  0.863528  0.998246
fake plant    0.705378  0.827190  0.754663  0.915261  0.999696
real banana   0.309681  0.472874  0.981596  0.311490  0.998440
fake banana   0.456665  0.626952  0.524920  0.778368  0.998296
real onion    0.779301  0.875913  0.819291  0.941057  0.999759
fake onion    0.886805  0.939957  0.930977  0.949214  0.999924
real unknown  0.534945  0.696976  0.543513  0.971374  0.999865
fake unknown  0.146310  0.255227  0.193821  0.373778  0.998162
total         0.696221  0.797107  0.838398  0.793885  0.999088
total(-bg)    0.682651  0.788006  0.831255  0.784552  0.999274
2026-09-23 11:52:20,154 - INFO: Epoch accounting: {'epoch': 164, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11282278, 45788, 63399, 116701, 163338, 57183, 61893, 137270, 150177, 66425, 71343, 47543, 17951, 224458, 171645, 128447, 24399, 88691, 90042, 100063, 80065, 10781, 38392], 'crops_with_class': [202, 27, 27, 35, 34, 23, 27, 29, 33, 30, 30, 17, 6, 56, 37, 23, 23, 24, 31, 41, 33, 11, 18], 'targeted_crops_by_class': [0, 4, 5, 4, 4, 0, 5, 8, 5, 9, 3, 7, 1, 3, 8, 4, 4, 5, 5, 5, 7, 8, 3], 'sampled_scene_counts': [0, 2, 3, 0, 0, 0, 2, 1, 0, 3, 0, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 2, 3, 2, 2, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1, 2, 0, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 1, 0, 3, 0, 1, 1, 2, 1, 1, 2, 2, 0, 2, 2, 0, 4, 1, 0, 0, 0, 1, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 0, 1, 1, 2, 1, 2, 1, 4, 1, 2, 1, 2, 2, 2, 0, 1, 3, 1, 0, 1, 0, 1, 0, 2, 1, 1, 3, 0, 0, 1, 2, 1, 3, 1, 2, 1, 0, 2, 4, 2, 1, 0, 4, 5, 1, 3, 2, 1], 'learning_rate': 7.605088996320782e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0009985952116525962, 'train_segmentation_loss': 0.38786436370251204, 'val_foreground_miou_all22': 0.6826508860853271, 'val_psnr_ref1': 37.027413024902344, 'elapsed_seconds': 341.13376474380493, 'peak_cuda_allocated_gib': 7.506626129150391}

Epoch 165/500 | Batch 10/202 | Rec 0.000905 | Seg 0.380920 | Elapsed 0.2m | ETA 4.2m
Epoch 165/500 | Batch 20/202 | Rec 0.000864 | Seg 0.350748 | Elapsed 0.4m | ETA 3.9m
Epoch 165/500 | Batch 30/202 | Rec 0.000857 | Seg 0.345548 | Elapsed 0.7m | ETA 3.7m
Epoch 165/500 | Batch 40/202 | Rec 0.000825 | Seg 0.330959 | Elapsed 0.9m | ETA 3.5m
Epoch 165/500 | Batch 50/202 | Rec 0.000845 | Seg 0.342188 | Elapsed 1.1m | ETA 3.3m
Epoch 165/500 | Batch 60/202 | Rec 0.000886 | Seg 0.364314 | Elapsed 1.3m | ETA 3.1m
Epoch 165/500 | Batch 70/202 | Rec 0.000881 | Seg 0.360409 | Elapsed 1.5m | ETA 2.9m
Epoch 165/500 | Batch 80/202 | Rec 0.000897 | Seg 0.368987 | Elapsed 1.7m | ETA 2.6m
Epoch 165/500 | Batch 90/202 | Rec 0.000890 | Seg 0.367570 | Elapsed 1.9m | ETA 2.4m
Epoch 165/500 | Batch 100/202 | Rec 0.000884 | Seg 0.362470 | Elapsed 2.2m | ETA 2.2m
Epoch 165/500 | Batch 110/202 | Rec 0.000874 | Seg 0.359605 | Elapsed 2.4m | ETA 2.0m
Epoch 165/500 | Batch 120/202 | Rec 0.000881 | Seg 0.367325 | Elapsed 2.6m | ETA 1.8m
Epoch 165/500 | Batch 130/202 | Rec 0.000907 | Seg 0.380321 | Elapsed 2.8m | ETA 1.6m
Epoch 165/500 | Batch 140/202 | Rec 0.000916 | Seg 0.385552 | Elapsed 3.0m | ETA 1.3m
Epoch 165/500 | Batch 150/202 | Rec 0.000913 | Seg 0.384745 | Elapsed 3.3m | ETA 1.1m
Epoch 165/500 | Batch 160/202 | Rec 0.000917 | Seg 0.386186 | Elapsed 3.5m | ETA 0.9m
Epoch 165/500 | Batch 170/202 | Rec 0.000918 | Seg 0.386718 | Elapsed 3.7m | ETA 0.7m
Epoch 165/500 | Batch 180/202 | Rec 0.000927 | Seg 0.392823 | Elapsed 3.9m | ETA 0.5m
Epoch 165/500 | Batch 190/202 | Rec 0.000913 | Seg 0.383549 | Elapsed 4.1m | ETA 0.3m
Epoch 165/500 | Batch 200/202 | Rec 0.000910 | Seg 0.379971 | Elapsed 4.4m | ETA 0.0m
Epoch 165/500 | Batch 202/202 | Rec 0.000910 | Seg 0.381136 | Elapsed 4.4m | ETA 0.0m

2026-09-23 11:56:43,900 - INFO: Rec loss: 0.0009104000439200007
2026-09-23 11:56:43,901 - INFO: Seg loss: 0.38113583369862913
2026-09-23 11:56:43,901 - INFO: λ_rec: 1
2026-09-23 11:56:43,901 - INFO: λ_seg: 0.0001
2026-09-23 11:58:01,969 - INFO: -------------------Epoch: 165------------------------
2026-09-23 11:58:01,974 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.063517  0.969307  0.000204
2026-09-23 11:58:01,982 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994981  0.997434  0.996148  0.998824  0.995203
real potato   0.774542  0.872900  0.996401  0.776715  0.999729
fake potato   0.921580  0.959140  0.946381  0.972350  0.999940
real apple    0.660059  0.795174  0.916186  0.702477  0.998752
fake apple    0.660859  0.795756  0.983293  0.668364  0.998705
real orange   0.518056  0.682480  0.999107  0.518296  0.999365
fake orange   0.779302  0.875915  0.793391  0.977721  0.999207
real grape    0.537334  0.698998  0.811872  0.613754  0.998897
fake grape    0.849818  0.918762  0.925074  0.912635  0.999403
real lemon    0.363743  0.533400  0.456341  0.641911  0.998680
fake lemon    0.796937  0.886945  0.973866  0.814353  0.999561
real avocado  0.794362  0.885348  0.877824  0.893103  0.999785
fake avocado  0.091025  0.166846  0.997207  0.091048  0.998912
real pepper   0.799253  0.888377  0.875877  0.901343  0.999172
fake pepper   0.930334  0.963860  0.987707  0.941233  0.999832
real plant    0.805428  0.892180  0.901916  0.882750  0.997867
fake plant    0.701973  0.824844  0.733971  0.941526  0.999682
real banana   0.408040  0.579542  0.932390  0.420481  0.998629
fake banana   0.668287  0.801116  0.792868  0.809638  0.999261
real onion    0.776005  0.873827  0.832340  0.919777  0.999760
fake onion    0.913075  0.954513  0.995276  0.917050  0.999945
real unknown  0.539273  0.700639  0.546474  0.976145  0.999867
fake unknown  0.168756  0.288744  0.184577  0.663166  0.997248
total         0.671870  0.775510  0.845934  0.780637  0.999017
total(-bg)    0.657184  0.765423  0.839106  0.770720  0.999191
2026-09-23 11:58:02,567 - INFO: Epoch accounting: {'epoch': 165, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11284337, 34773, 43716, 129748, 166042, 81044, 94038, 142381, 199117, 84114, 59752, 52407, 32159, 224819, 127501, 123630, 22084, 76497, 70001, 77916, 55449, 9213, 47534], 'crops_with_class': [202, 20, 21, 31, 40, 25, 31, 31, 39, 36, 28, 19, 15, 47, 33, 16, 21, 24, 26, 29, 23, 11, 22], 'targeted_crops_by_class': [0, 3, 5, 7, 4, 3, 8, 7, 2, 2, 8, 8, 4, 6, 6, 4, 4, 6, 1, 5, 2, 3, 5], 'sampled_scene_counts': [1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 2, 0, 3, 0, 2, 1, 0, 2, 1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 4, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 0, 2, 1, 1, 2, 0, 1, 1, 2, 0, 1, 1, 0, 2, 3, 1, 2, 2, 2, 2, 1, 3, 0, 1, 1, 3, 0, 1, 3, 0, 3, 0, 0, 3, 0, 1, 1, 2, 0, 1, 0, 3, 2, 2, 4, 2, 2, 3, 3, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 3, 2, 3, 1, 0, 0, 1, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0], 'learning_rate': 7.578267174735258e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009104000439200007, 'train_segmentation_loss': 0.38113583369862913, 'val_foreground_miou_all22': 0.6571836454436729, 'val_psnr_ref1': 37.063516540527345, 'elapsed_seconds': 342.40384459495544, 'peak_cuda_allocated_gib': 7.507854461669922}

Epoch 166/500 | Batch 10/202 | Rec 0.001051 | Seg 0.410556 | Elapsed 0.2m | ETA 4.2m
Epoch 166/500 | Batch 20/202 | Rec 0.001047 | Seg 0.391589 | Elapsed 0.4m | ETA 4.0m
Epoch 166/500 | Batch 30/202 | Rec 0.000993 | Seg 0.394852 | Elapsed 0.7m | ETA 3.8m
Epoch 166/500 | Batch 40/202 | Rec 0.000989 | Seg 0.400045 | Elapsed 0.9m | ETA 3.5m
Epoch 166/500 | Batch 50/202 | Rec 0.000962 | Seg 0.395173 | Elapsed 1.1m | ETA 3.3m
Epoch 166/500 | Batch 60/202 | Rec 0.000909 | Seg 0.378455 | Elapsed 1.3m | ETA 3.1m
Epoch 166/500 | Batch 70/202 | Rec 0.000898 | Seg 0.375093 | Elapsed 1.5m | ETA 2.9m
Epoch 166/500 | Batch 80/202 | Rec 0.000891 | Seg 0.371791 | Elapsed 1.7m | ETA 2.7m
Epoch 166/500 | Batch 90/202 | Rec 0.000898 | Seg 0.379560 | Elapsed 2.0m | ETA 2.4m
Epoch 166/500 | Batch 100/202 | Rec 0.000893 | Seg 0.377670 | Elapsed 2.2m | ETA 2.2m
Epoch 166/500 | Batch 110/202 | Rec 0.000893 | Seg 0.379786 | Elapsed 2.4m | ETA 2.0m
Epoch 166/500 | Batch 120/202 | Rec 0.000878 | Seg 0.368253 | Elapsed 2.6m | ETA 1.8m
Epoch 166/500 | Batch 130/202 | Rec 0.000885 | Seg 0.370349 | Elapsed 2.8m | ETA 1.6m
Epoch 166/500 | Batch 140/202 | Rec 0.000885 | Seg 0.369562 | Elapsed 3.1m | ETA 1.4m
Epoch 166/500 | Batch 150/202 | Rec 0.000890 | Seg 0.369341 | Elapsed 3.3m | ETA 1.1m
Epoch 166/500 | Batch 160/202 | Rec 0.000886 | Seg 0.366636 | Elapsed 3.5m | ETA 0.9m
Epoch 166/500 | Batch 170/202 | Rec 0.000877 | Seg 0.365397 | Elapsed 3.7m | ETA 0.7m
Epoch 166/500 | Batch 180/202 | Rec 0.000885 | Seg 0.370749 | Elapsed 4.0m | ETA 0.5m
Epoch 166/500 | Batch 190/202 | Rec 0.000881 | Seg 0.367604 | Elapsed 4.2m | ETA 0.3m
Epoch 166/500 | Batch 200/202 | Rec 0.000882 | Seg 0.371626 | Elapsed 4.4m | ETA 0.0m
Epoch 166/500 | Batch 202/202 | Rec 0.000882 | Seg 0.371333 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:02:28,574 - INFO: Rec loss: 0.0008820190562954228
2026-09-23 12:02:28,574 - INFO: Seg loss: 0.3713327980793939
2026-09-23 12:02:28,574 - INFO: λ_rec: 1
2026-09-23 12:02:28,574 - INFO: λ_seg: 0.0001
2026-09-23 12:03:45,942 - INFO: -------------------Epoch: 166------------------------
2026-09-23 12:03:45,947 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  37.248514  0.96901  0.000196
2026-09-23 12:03:45,956 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995009  0.997448  0.996218  0.998782  0.995231
real potato   0.807419  0.893400  0.995302  0.810508  0.999769
fake potato   0.958548  0.978785  0.984120  0.973607  0.999969
real apple    0.782933  0.878203  0.909233  0.849314  0.999188
fake apple    0.666188  0.799607  0.982336  0.674264  0.998724
real orange   0.527078  0.690264  0.986868  0.530801  0.999372
fake orange   0.774629  0.872954  0.793505  0.970206  0.999192
real grape    0.564961  0.721964  0.832347  0.637506  0.998975
fake grape    0.833976  0.909423  0.917335  0.901745  0.999336
real lemon    0.521194  0.685195  0.578004  0.841340  0.999092
fake lemon    0.807387  0.893381  0.957831  0.837144  0.999577
real avocado  0.802334  0.890278  0.888871  0.891790  0.999796
fake avocado  0.709021  0.829691  0.954855  0.733614  0.999640
real pepper   0.799793  0.888711  0.874914  0.903054  0.999173
fake pepper   0.855504  0.922076  0.948130  0.897510  0.999639
real plant    0.835019  0.910043  0.901024  0.919346  0.998183
fake plant    0.823498  0.903157  0.930474  0.877492  0.999850
real banana   0.434555  0.605796  0.944484  0.445946  0.998696
fake banana   0.638408  0.779253  0.793958  0.765179  0.999203
real onion    0.702664  0.825320  0.831022  0.819794  0.999687
fake onion    0.918052  0.957225  0.966478  0.948247  0.999947
real unknown  0.947663  0.973079  0.978764  0.967557  0.999991
fake unknown  0.215242  0.354193  0.265279  0.532959  0.998363
total         0.735699  0.833019  0.878754  0.814248  0.999156
total(-bg)    0.723912  0.825545  0.873415  0.805860  0.999335
2026-09-23 12:03:46,767 - INFO: Epoch accounting: {'epoch': 166, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11304968, 51009, 64471, 140788, 149691, 92879, 64006, 124982, 171285, 97766, 86735, 38408, 40863, 208771, 119174, 98192, 23261, 91707, 72345, 86596, 53068, 6719, 50588], 'crops_with_class': [202, 26, 27, 41, 36, 26, 20, 29, 36, 40, 33, 13, 16, 51, 27, 15, 22, 22, 24, 37, 24, 8, 19], 'targeted_crops_by_class': [0, 4, 4, 2, 2, 5, 4, 3, 5, 5, 5, 3, 4, 4, 7, 5, 3, 6, 3, 4, 4, 2, 6], 'sampled_scene_counts': [0, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 2, 0, 1, 1, 0, 2, 1, 1, 1, 2, 1, 0, 0, 1, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 2, 1, 2, 0, 1, 3, 1, 1, 2, 2, 1, 1, 0, 2, 3, 1, 1, 0, 2, 0, 0, 0, 2, 1, 3, 0, 6, 0, 3, 1, 1, 2, 0, 2, 2, 0, 1, 2, 1, 1, 2, 4, 1, 0, 0, 3, 1, 0, 0, 1, 0, 2, 2, 0, 3, 3, 1, 2, 1, 2, 2, 2, 2, 1, 1, 0, 1, 1, 1, 1, 3, 2, 0, 1, 2, 0, 1, 1, 2, 3], 'learning_rate': 7.551344061054971e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008820190562954228, 'train_segmentation_loss': 0.3713327980793939, 'val_foreground_miou_all22': 0.7239120805006498, 'val_psnr_ref1': 37.248513793945314, 'elapsed_seconds': 344.19176864624023, 'peak_cuda_allocated_gib': 7.512729644775391}

Epoch 167/500 | Batch 10/202 | Rec 0.001103 | Seg 0.444897 | Elapsed 0.2m | ETA 4.2m
Epoch 167/500 | Batch 20/202 | Rec 0.001044 | Seg 0.421521 | Elapsed 0.4m | ETA 4.0m
Epoch 167/500 | Batch 30/202 | Rec 0.000974 | Seg 0.413943 | Elapsed 0.7m | ETA 3.8m
Epoch 167/500 | Batch 40/202 | Rec 0.000924 | Seg 0.399681 | Elapsed 0.9m | ETA 3.6m
Epoch 167/500 | Batch 50/202 | Rec 0.000895 | Seg 0.383397 | Elapsed 1.1m | ETA 3.3m
Epoch 167/500 | Batch 60/202 | Rec 0.000875 | Seg 0.375705 | Elapsed 1.3m | ETA 3.1m
Epoch 167/500 | Batch 70/202 | Rec 0.000878 | Seg 0.381315 | Elapsed 1.5m | ETA 2.9m
Epoch 167/500 | Batch 80/202 | Rec 0.000895 | Seg 0.380933 | Elapsed 1.7m | ETA 2.7m
Epoch 167/500 | Batch 90/202 | Rec 0.000897 | Seg 0.379564 | Elapsed 2.0m | ETA 2.5m
Epoch 167/500 | Batch 100/202 | Rec 0.000897 | Seg 0.369593 | Elapsed 2.2m | ETA 2.2m
Epoch 167/500 | Batch 110/202 | Rec 0.000919 | Seg 0.370828 | Elapsed 2.4m | ETA 2.0m
Epoch 167/500 | Batch 120/202 | Rec 0.000916 | Seg 0.375564 | Elapsed 2.6m | ETA 1.8m
Epoch 167/500 | Batch 130/202 | Rec 0.000899 | Seg 0.375195 | Elapsed 2.8m | ETA 1.6m
Epoch 167/500 | Batch 140/202 | Rec 0.000902 | Seg 0.379675 | Elapsed 3.1m | ETA 1.4m
Epoch 167/500 | Batch 150/202 | Rec 0.000920 | Seg 0.381395 | Elapsed 3.3m | ETA 1.1m
Epoch 167/500 | Batch 160/202 | Rec 0.000906 | Seg 0.382001 | Elapsed 3.5m | ETA 0.9m
Epoch 167/500 | Batch 170/202 | Rec 0.000903 | Seg 0.380101 | Elapsed 3.7m | ETA 0.7m
Epoch 167/500 | Batch 180/202 | Rec 0.000901 | Seg 0.379122 | Elapsed 4.0m | ETA 0.5m
Epoch 167/500 | Batch 190/202 | Rec 0.000901 | Seg 0.378961 | Elapsed 4.2m | ETA 0.3m
Epoch 167/500 | Batch 200/202 | Rec 0.000900 | Seg 0.380136 | Elapsed 4.4m | ETA 0.0m
Epoch 167/500 | Batch 202/202 | Rec 0.000901 | Seg 0.380568 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:08:12,741 - INFO: Rec loss: 0.0009007110464441968
2026-09-23 12:08:12,741 - INFO: Seg loss: 0.38056802200061257
2026-09-23 12:08:12,741 - INFO: λ_rec: 1
2026-09-23 12:08:12,741 - INFO: λ_seg: 0.0001
2026-09-23 12:09:30,676 - INFO: -------------------Epoch: 167------------------------
2026-09-23 12:09:30,681 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  37.627187  0.970308  0.00018
2026-09-23 12:09:30,689 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994910  0.997399  0.995826  0.999076  0.995134
real potato   0.916106  0.956166  0.976092  0.937133  0.999897
fake potato   0.947076  0.972769  0.982482  0.963343  0.999961
real apple    0.740108  0.850597  0.990537  0.745378  0.999097
fake apple    0.689711  0.816317  0.978487  0.700331  0.998810
real orange   0.563636  0.720884  0.978364  0.570750  0.999418
fake orange   0.796538  0.886698  0.815720  0.971325  0.999290
real grape    0.549786  0.709451  0.866941  0.600453  0.998973
fake grape    0.835945  0.910593  0.930969  0.891185  0.999353
real lemon    0.430253  0.601596  0.559727  0.650351  0.998988
fake lemon    0.806385  0.892767  0.985371  0.816156  0.999585
real avocado  0.777066  0.874499  0.854346  0.895731  0.999761
fake avocado  0.274972  0.431302  0.925693  0.281178  0.999113
real pepper   0.797572  0.887338  0.909848  0.866010  0.999196
fake pepper   0.935428  0.966587  0.970693  0.962614  0.999842
real plant    0.813560  0.897147  0.907194  0.887418  0.997966
fake plant    0.853732  0.921045  0.916809  0.925422  0.999874
real banana   0.479188  0.647861  0.918932  0.500340  0.998778
fake banana   0.672456  0.804104  0.808673  0.799685  0.999283
real onion    0.731761  0.845057  0.761937  0.948657  0.999686
fake onion    0.940855  0.969476  0.981417  0.957920  0.999962
real unknown  0.467366  0.636970  0.472543  0.977099  0.999822
fake unknown  0.182512  0.308648  0.205098  0.623687  0.997646
total         0.704214  0.804577  0.856248  0.803098  0.999106
total(-bg)    0.691001  0.795812  0.849903  0.794189  0.999286
2026-09-23 12:09:31,485 - INFO: Epoch accounting: {'epoch': 167, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11274886, 41962, 50653, 133837, 140222, 76097, 54108, 177298, 203948, 67786, 54677, 74555, 48508, 235324, 114428, 156424, 22066, 95961, 59215, 64647, 43974, 11750, 35946], 'crops_with_class': [202, 27, 23, 36, 41, 22, 21, 31, 45, 29, 22, 23, 19, 59, 30, 22, 19, 24, 26, 31, 21, 13, 15], 'targeted_crops_by_class': [0, 4, 0, 6, 5, 3, 1, 6, 6, 2, 5, 6, 8, 2, 3, 5, 3, 6, 3, 6, 4, 5, 5], 'sampled_scene_counts': [0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 3, 1, 1, 1, 2, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 1, 3, 2, 2, 3, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 2, 1, 3, 0, 3, 1, 0, 0, 2, 0, 3, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 1, 4, 0, 1, 1, 0, 1, 1, 1, 2, 3, 0, 2, 1, 2, 2, 2, 1, 0, 0, 3, 2, 1, 1, 0, 1, 0, 2, 3, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 2, 1, 2, 2, 4, 0, 1, 0, 1, 2, 0, 1, 2, 1], 'learning_rate': 7.524320718158349e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009007110464441968, 'train_segmentation_loss': 0.38056802200061257, 'val_foreground_miou_all22': 0.691000554931067, 'val_psnr_ref1': 37.6271875, 'elapsed_seconds': 344.70886731147766, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 168/500 | Batch 10/202 | Rec 0.001101 | Seg 0.383691 | Elapsed 0.2m | ETA 4.2m
Epoch 168/500 | Batch 20/202 | Rec 0.001005 | Seg 0.372598 | Elapsed 0.4m | ETA 4.0m
Epoch 168/500 | Batch 30/202 | Rec 0.000924 | Seg 0.369817 | Elapsed 0.6m | ETA 3.7m
Epoch 168/500 | Batch 40/202 | Rec 0.000904 | Seg 0.375014 | Elapsed 0.9m | ETA 3.5m
Epoch 168/500 | Batch 50/202 | Rec 0.000904 | Seg 0.367486 | Elapsed 1.1m | ETA 3.3m
Epoch 168/500 | Batch 60/202 | Rec 0.000886 | Seg 0.355510 | Elapsed 1.3m | ETA 3.1m
Epoch 168/500 | Batch 70/202 | Rec 0.000899 | Seg 0.354027 | Elapsed 1.5m | ETA 2.9m
Epoch 168/500 | Batch 80/202 | Rec 0.000906 | Seg 0.357297 | Elapsed 1.7m | ETA 2.7m
Epoch 168/500 | Batch 90/202 | Rec 0.000905 | Seg 0.361014 | Elapsed 2.0m | ETA 2.4m
Epoch 168/500 | Batch 100/202 | Rec 0.000904 | Seg 0.359686 | Elapsed 2.2m | ETA 2.2m
Epoch 168/500 | Batch 110/202 | Rec 0.000920 | Seg 0.374092 | Elapsed 2.4m | ETA 2.0m
Epoch 168/500 | Batch 120/202 | Rec 0.000911 | Seg 0.379808 | Elapsed 2.6m | ETA 1.8m
Epoch 168/500 | Batch 130/202 | Rec 0.000915 | Seg 0.385536 | Elapsed 2.8m | ETA 1.6m
Epoch 168/500 | Batch 140/202 | Rec 0.000912 | Seg 0.382231 | Elapsed 3.0m | ETA 1.3m
Epoch 168/500 | Batch 150/202 | Rec 0.000925 | Seg 0.385245 | Elapsed 3.3m | ETA 1.1m
Epoch 168/500 | Batch 160/202 | Rec 0.000938 | Seg 0.385839 | Elapsed 3.5m | ETA 0.9m
Epoch 168/500 | Batch 170/202 | Rec 0.000931 | Seg 0.383489 | Elapsed 3.7m | ETA 0.7m
Epoch 168/500 | Batch 180/202 | Rec 0.000931 | Seg 0.383085 | Elapsed 3.9m | ETA 0.5m
Epoch 168/500 | Batch 190/202 | Rec 0.000931 | Seg 0.382604 | Elapsed 4.1m | ETA 0.3m
Epoch 168/500 | Batch 200/202 | Rec 0.000923 | Seg 0.378679 | Elapsed 4.3m | ETA 0.0m
Epoch 168/500 | Batch 202/202 | Rec 0.000929 | Seg 0.379227 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:13:54,552 - INFO: Rec loss: 0.0009290210887994894
2026-09-23 12:13:54,552 - INFO: Seg loss: 0.3792274498408384
2026-09-23 12:13:54,552 - INFO: λ_rec: 1
2026-09-23 12:13:54,552 - INFO: λ_seg: 0.0001
2026-09-23 12:15:12,281 - INFO: -------------------Epoch: 168------------------------
2026-09-23 12:15:12,287 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.051819  0.968856  0.000206
2026-09-23 12:15:12,295 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994565  0.997225  0.995558  0.998998  0.994803
real potato   0.823279  0.903025  0.850654  0.962382  0.999753
fake potato   0.931447  0.964457  0.950386  0.979053  0.999948
real apple    0.459953  0.630050  0.999904  0.459973  0.998137
fake apple    0.548816  0.708644  0.935388  0.570441  0.998229
real orange   0.763021  0.865535  0.996531  0.765053  0.999687
fake orange   0.865335  0.927757  0.895316  0.962744  0.999571
real grape    0.419908  0.591411  0.763258  0.482789  0.998607
fake grape    0.829458  0.906730  0.904158  0.909417  0.999308
real lemon    0.260962  0.413866  0.653318  0.302908  0.998992
fake lemon    0.653613  0.790479  0.999890  0.653660  0.999267
real avocado  0.837236  0.911358  0.988481  0.845484  0.999847
fake avocado  0.179684  0.304603  0.921442  0.182479  0.999003
real pepper   0.823305  0.903041  0.934974  0.873311  0.999314
fake pepper   0.935470  0.966609  0.967248  0.966071  0.999841
real plant    0.784237  0.879023  0.897146  0.861713  0.997629
fake plant    0.736078  0.847928  0.770569  0.942676  0.999731
real banana   0.525922  0.689270  0.887487  0.563493  0.998859
fake banana   0.422766  0.594242  0.463063  0.829297  0.997917
real onion    0.691231  0.817380  0.721619  0.942577  0.999620
fake onion    0.929574  0.963452  0.982893  0.944861  0.999955
real unknown  0.502238  0.668607  0.511911  0.963740  0.999847
fake unknown  0.124629  0.221604  0.137986  0.562840  0.996669
total         0.654032  0.759404  0.831704  0.761998  0.998893
total(-bg)    0.638553  0.748594  0.824256  0.751226  0.999079
2026-09-23 12:15:12,904 - INFO: Epoch accounting: {'epoch': 168, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11280582, 52769, 58376, 115557, 134945, 63494, 68980, 115353, 188156, 75412, 59024, 23639, 41307, 235775, 118331, 174191, 25465, 90995, 85956, 106570, 69043, 7911, 46441], 'crops_with_class': [202, 30, 30, 32, 31, 24, 21, 22, 35, 32, 25, 8, 17, 59, 29, 24, 25, 29, 31, 42, 33, 11, 21], 'targeted_crops_by_class': [0, 4, 4, 1, 1, 6, 3, 4, 10, 1, 4, 1, 7, 8, 5, 6, 7, 7, 7, 7, 5, 3, 5], 'sampled_scene_counts': [1, 1, 1, 1, 2, 0, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 3, 1, 1, 1, 1, 0, 2, 1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 2, 2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 2, 0, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 3, 1, 1, 0, 2, 1, 2, 2, 0, 1, 0, 3, 2, 0, 1, 2, 1, 0, 0, 2, 2, 2, 2, 1, 4, 0, 1, 1, 0, 4, 0, 0, 1, 1, 1, 0, 1, 2, 3, 3, 1, 4, 1, 1, 0, 1, 2, 0, 4, 1, 1, 1, 1, 1, 1, 3, 0, 1, 0, 1, 1, 2, 2, 3, 2, 2, 2, 1, 2, 2, 2, 3, 1, 0, 2, 3, 2, 4, 1, 1, 0], 'learning_rate': 7.497198212880703e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009290210887994894, 'train_segmentation_loss': 0.3792274498408384, 'val_foreground_miou_all22': 0.6385528190092917, 'val_psnr_ref1': 37.05181869506836, 'elapsed_seconds': 341.41099977493286, 'peak_cuda_allocated_gib': 7.510044097900391}

Epoch 169/500 | Batch 10/202 | Rec 0.000754 | Seg 0.304818 | Elapsed 0.2m | ETA 4.2m
Epoch 169/500 | Batch 20/202 | Rec 0.001002 | Seg 0.373735 | Elapsed 0.4m | ETA 3.9m
Epoch 169/500 | Batch 30/202 | Rec 0.001095 | Seg 0.419472 | Elapsed 0.6m | ETA 3.7m
Epoch 169/500 | Batch 40/202 | Rec 0.001061 | Seg 0.408980 | Elapsed 0.9m | ETA 3.5m
Epoch 169/500 | Batch 50/202 | Rec 0.001011 | Seg 0.402587 | Elapsed 1.1m | ETA 3.3m
Epoch 169/500 | Batch 60/202 | Rec 0.000975 | Seg 0.388519 | Elapsed 1.3m | ETA 3.1m
Epoch 169/500 | Batch 70/202 | Rec 0.000971 | Seg 0.399035 | Elapsed 1.5m | ETA 2.8m
Epoch 169/500 | Batch 80/202 | Rec 0.000954 | Seg 0.396577 | Elapsed 1.7m | ETA 2.6m
Epoch 169/500 | Batch 90/202 | Rec 0.000936 | Seg 0.390502 | Elapsed 1.9m | ETA 2.4m
Epoch 169/500 | Batch 100/202 | Rec 0.000917 | Seg 0.377412 | Elapsed 2.2m | ETA 2.2m
Epoch 169/500 | Batch 110/202 | Rec 0.000912 | Seg 0.374982 | Elapsed 2.4m | ETA 2.0m
Epoch 169/500 | Batch 120/202 | Rec 0.000886 | Seg 0.365652 | Elapsed 2.6m | ETA 1.8m
Epoch 169/500 | Batch 130/202 | Rec 0.000880 | Seg 0.367298 | Elapsed 2.8m | ETA 1.6m
Epoch 169/500 | Batch 140/202 | Rec 0.000894 | Seg 0.373304 | Elapsed 3.0m | ETA 1.3m
Epoch 169/500 | Batch 150/202 | Rec 0.000899 | Seg 0.376813 | Elapsed 3.2m | ETA 1.1m
Epoch 169/500 | Batch 160/202 | Rec 0.000898 | Seg 0.376660 | Elapsed 3.5m | ETA 0.9m
Epoch 169/500 | Batch 170/202 | Rec 0.000894 | Seg 0.375122 | Elapsed 3.7m | ETA 0.7m
Epoch 169/500 | Batch 180/202 | Rec 0.000897 | Seg 0.374029 | Elapsed 3.9m | ETA 0.5m
Epoch 169/500 | Batch 190/202 | Rec 0.000902 | Seg 0.376129 | Elapsed 4.1m | ETA 0.3m
Epoch 169/500 | Batch 200/202 | Rec 0.000897 | Seg 0.374594 | Elapsed 4.3m | ETA 0.0m
Epoch 169/500 | Batch 202/202 | Rec 0.000895 | Seg 0.375844 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:19:35,117 - INFO: Rec loss: 0.0008951026178656681
2026-09-23 12:19:35,117 - INFO: Seg loss: 0.3758440947916248
2026-09-23 12:19:35,117 - INFO: λ_rec: 1
2026-09-23 12:19:35,117 - INFO: λ_seg: 0.0001
2026-09-23 12:20:52,341 - INFO: -------------------Epoch: 169------------------------
2026-09-23 12:20:52,346 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.815713  0.969913  0.000173
2026-09-23 12:20:52,354 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995131  0.997510  0.996621  0.998500  0.995349
real potato   0.711548  0.831419  0.993268  0.714996  0.999653
fake potato   0.708256  0.829166  0.976441  0.720570  0.999784
real apple    0.763148  0.865616  0.906289  0.828527  0.999113
fake apple    0.575865  0.730809  0.981336  0.582242  0.998381
real orange   0.493218  0.660567  0.985304  0.496874  0.999327
fake orange   0.771761  0.871130  0.797863  0.959333  0.999188
real grape    0.780625  0.876749  0.892565  0.861580  0.999494
fake grape    0.865753  0.927997  0.905693  0.951532  0.999454
real lemon    0.442225  0.613205  0.531631  0.724487  0.998926
fake lemon    0.809278  0.894537  0.992787  0.814064  0.999594
real avocado  0.758173  0.862406  0.810514  0.921511  0.999727
fake avocado  0.075738  0.140798  0.977011  0.075874  0.998892
real pepper   0.764981  0.866793  0.888524  0.846196  0.999049
fake pepper   0.827675  0.905664  0.952792  0.863069  0.999572
real plant    0.863193  0.926524  0.949127  0.905068  0.998565
fake plant    0.704522  0.826601  0.748562  0.922929  0.999692
real banana   0.454427  0.624843  0.918005  0.473652  0.998722
fake banana   0.611758  0.759070  0.691998  0.840660  0.999019
real onion    0.707800  0.828853  0.739695  0.942577  0.999648
fake onion    0.928134  0.962678  0.973073  0.952600  0.999953
real unknown  0.743514  0.852842  0.769172  0.957061  0.999947
fake unknown  0.162951  0.280205  0.174930  0.704093  0.996953
total         0.674769  0.779825  0.850139  0.785130  0.999044
total(-bg)    0.660207  0.769931  0.843481  0.775432  0.999212
2026-09-23 12:20:53,132 - INFO: Epoch accounting: {'epoch': 169, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11301809, 54109, 61635, 145293, 112992, 73616, 70137, 155149, 183092, 48773, 60804, 33669, 32407, 228866, 132252, 156711, 25096, 99341, 72481, 85208, 48829, 13501, 42502], 'crops_with_class': [202, 29, 28, 32, 29, 22, 26, 30, 35, 26, 26, 13, 14, 55, 30, 20, 21, 24, 32, 37, 25, 13, 19], 'targeted_crops_by_class': [0, 1, 9, 8, 4, 3, 4, 6, 6, 5, 5, 5, 4, 4, 2, 4, 5, 6, 5, 6, 1, 8, 1], 'sampled_scene_counts': [0, 1, 0, 0, 2, 0, 0, 1, 0, 3, 1, 1, 0, 1, 1, 2, 1, 2, 0, 2, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 2, 0, 2, 1, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 2, 1, 0, 2, 0, 1, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 4, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 3, 1, 0, 2, 1, 2, 1, 2, 2, 1, 0, 2, 1, 2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 4, 1, 5, 1, 2, 1, 1, 1, 3, 1, 1, 2, 3, 2, 1, 0, 3, 2, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2], 'learning_rate': 7.469977615972096e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008951026178656681, 'train_segmentation_loss': 0.3758440947916248, 'val_foreground_miou_all22': 0.6602065879145307, 'val_psnr_ref1': 37.81571334838867, 'elapsed_seconds': 340.21900272369385, 'peak_cuda_allocated_gib': 7.515171051025391}

Epoch 170/500 | Batch 10/202 | Rec 0.000842 | Seg 0.349123 | Elapsed 0.2m | ETA 4.2m
Epoch 170/500 | Batch 20/202 | Rec 0.000881 | Seg 0.320607 | Elapsed 0.4m | ETA 3.9m
Epoch 170/500 | Batch 30/202 | Rec 0.000964 | Seg 0.357402 | Elapsed 0.7m | ETA 3.7m
Epoch 170/500 | Batch 40/202 | Rec 0.000968 | Seg 0.362900 | Elapsed 0.9m | ETA 3.5m
Epoch 170/500 | Batch 50/202 | Rec 0.000946 | Seg 0.370808 | Elapsed 1.1m | ETA 3.3m
Epoch 170/500 | Batch 60/202 | Rec 0.000941 | Seg 0.376481 | Elapsed 1.3m | ETA 3.1m
Epoch 170/500 | Batch 70/202 | Rec 0.000943 | Seg 0.377464 | Elapsed 1.5m | ETA 2.9m
Epoch 170/500 | Batch 80/202 | Rec 0.000947 | Seg 0.377690 | Elapsed 1.7m | ETA 2.6m
Epoch 170/500 | Batch 90/202 | Rec 0.000990 | Seg 0.396861 | Elapsed 2.0m | ETA 2.4m
Epoch 170/500 | Batch 100/202 | Rec 0.000992 | Seg 0.399082 | Elapsed 2.2m | ETA 2.2m
Epoch 170/500 | Batch 110/202 | Rec 0.000977 | Seg 0.388592 | Elapsed 2.4m | ETA 2.0m
Epoch 170/500 | Batch 120/202 | Rec 0.000972 | Seg 0.390755 | Elapsed 2.6m | ETA 1.8m
Epoch 170/500 | Batch 130/202 | Rec 0.000964 | Seg 0.389518 | Elapsed 2.8m | ETA 1.6m
Epoch 170/500 | Batch 140/202 | Rec 0.000964 | Seg 0.390622 | Elapsed 3.0m | ETA 1.3m
Epoch 170/500 | Batch 150/202 | Rec 0.000957 | Seg 0.387326 | Elapsed 3.3m | ETA 1.1m
Epoch 170/500 | Batch 160/202 | Rec 0.000970 | Seg 0.387694 | Elapsed 3.5m | ETA 0.9m
Epoch 170/500 | Batch 170/202 | Rec 0.000954 | Seg 0.383922 | Elapsed 3.7m | ETA 0.7m
Epoch 170/500 | Batch 180/202 | Rec 0.000947 | Seg 0.381568 | Elapsed 3.9m | ETA 0.5m
Epoch 170/500 | Batch 190/202 | Rec 0.000951 | Seg 0.382671 | Elapsed 4.1m | ETA 0.3m
Epoch 170/500 | Batch 200/202 | Rec 0.000950 | Seg 0.384584 | Elapsed 4.4m | ETA 0.0m
Epoch 170/500 | Batch 202/202 | Rec 0.000950 | Seg 0.384714 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:25:17,266 - INFO: Rec loss: 0.0009495063974766411
2026-09-23 12:25:17,266 - INFO: Seg loss: 0.3847137825692644
2026-09-23 12:25:17,266 - INFO: λ_rec: 1
2026-09-23 12:25:17,266 - INFO: λ_seg: 0.0001
2026-09-23 12:26:34,575 - INFO: -------------------Epoch: 170------------------------
2026-09-23 12:26:34,579 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.711595  0.969653  0.000176
2026-09-23 12:26:34,586 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994920  0.997403  0.996282  0.998627  0.995146
real potato   0.726419  0.841484  0.993920  0.729661  0.999671
fake potato   0.887284  0.940226  0.968681  0.913490  0.999915
real apple    0.665323  0.798982  0.905172  0.715170  0.998759
fake apple    0.600375  0.750245  0.947018  0.621242  0.998439
real orange   0.484532  0.652728  0.907797  0.509611  0.999286
fake orange   0.775916  0.873771  0.800009  0.962637  0.999204
real grape    0.620499  0.765764  0.937447  0.647300  0.999173
fake grape    0.842956  0.914737  0.912945  0.916636  0.999368
real lemon    0.333907  0.500595  0.497818  0.503506  0.998820
fake lemon    0.651594  0.789001  0.999889  0.651641  0.999263
real avocado  0.567810  0.724288  0.931355  0.592611  0.999581
fake avocado  0.348437  0.516760  0.874696  0.366743  0.999179
real pepper   0.768661  0.869151  0.895361  0.844527  0.999070
fake pepper   0.878159  0.935078  0.993661  0.883106  0.999708
real plant    0.825952  0.904631  0.887392  0.922657  0.998055
fake plant    0.802436  0.890341  0.910274  0.871357  0.999829
real banana   0.465721  0.635440  0.968698  0.472837  0.998781
fake banana   0.492385  0.659816  0.545874  0.834025  0.998418
real onion    0.635224  0.776878  0.653054  0.958791  0.999503
fake onion    0.911183  0.953478  0.949413  0.957678  0.999941
real unknown  0.393310  0.564528  0.397127  0.976145  0.999759
fake unknown  0.178988  0.303596  0.194528  0.691416  0.997328
total         0.645739  0.763431  0.829061  0.762670  0.998965
total(-bg)    0.629867  0.752796  0.821460  0.751945  0.999139
2026-09-23 12:26:35,153 - INFO: Epoch accounting: {'epoch': 170, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11289215, 62521, 84097, 100089, 143856, 111395, 67123, 95565, 204655, 51846, 42508, 32708, 35203, 211932, 102559, 145564, 22496, 106382, 112868, 100917, 53198, 11873, 49702], 'crops_with_class': [202, 34, 38, 27, 36, 37, 26, 21, 37, 26, 21, 10, 13, 52, 30, 20, 19, 28, 45, 44, 27, 13, 24], 'targeted_crops_by_class': [0, 2, 8, 3, 4, 8, 8, 4, 7, 5, 2, 4, 4, 3, 6, 3, 5, 6, 9, 5, 3, 3, 4], 'sampled_scene_counts': [1, 2, 5, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 3, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 2, 0, 0, 1, 1, 2, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 1, 3, 2, 1, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 2, 0, 0, 2, 1, 2, 1, 2, 0, 0, 1, 2, 2, 1, 1, 1, 0, 2, 1, 0, 3, 3, 1, 0, 3, 2, 5, 2, 2, 1, 1, 1, 0, 1, 2, 3, 0, 0, 3, 1, 1, 3, 3, 0, 1, 2, 2, 2, 2, 1, 0, 0, 0, 2, 1, 1, 3, 1, 1, 0, 3, 1, 1, 1, 3, 4, 1, 2, 2, 1, 2, 1, 4, 3, 2, 1, 1, 2, 1, 1, 1, 3, 2], 'learning_rate': 7.442660002055087e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009495063974766411, 'train_segmentation_loss': 0.3847137825692644, 'val_foreground_miou_all22': 0.6298668893103073, 'val_psnr_ref1': 37.71159454345703, 'elapsed_seconds': 342.01253938674927, 'peak_cuda_allocated_gib': 7.514438629150391}

Epoch 171/500 | Batch 10/202 | Rec 0.000686 | Seg 0.321037 | Elapsed 0.2m | ETA 4.2m
Epoch 171/500 | Batch 20/202 | Rec 0.000862 | Seg 0.389326 | Elapsed 0.4m | ETA 3.9m
Epoch 171/500 | Batch 30/202 | Rec 0.000863 | Seg 0.358598 | Elapsed 0.7m | ETA 3.7m
Epoch 171/500 | Batch 40/202 | Rec 0.000868 | Seg 0.371491 | Elapsed 0.9m | ETA 3.5m
Epoch 171/500 | Batch 50/202 | Rec 0.000832 | Seg 0.355631 | Elapsed 1.1m | ETA 3.3m
Epoch 171/500 | Batch 60/202 | Rec 0.000885 | Seg 0.374952 | Elapsed 1.3m | ETA 3.1m
Epoch 171/500 | Batch 70/202 | Rec 0.000906 | Seg 0.377733 | Elapsed 1.5m | ETA 2.9m
Epoch 171/500 | Batch 80/202 | Rec 0.000911 | Seg 0.387595 | Elapsed 1.7m | ETA 2.7m
Epoch 171/500 | Batch 90/202 | Rec 0.000888 | Seg 0.374276 | Elapsed 2.0m | ETA 2.5m
Epoch 171/500 | Batch 100/202 | Rec 0.000871 | Seg 0.368670 | Elapsed 2.2m | ETA 2.2m
Epoch 171/500 | Batch 110/202 | Rec 0.000860 | Seg 0.363355 | Elapsed 2.4m | ETA 2.0m
Epoch 171/500 | Batch 120/202 | Rec 0.000859 | Seg 0.359356 | Elapsed 2.6m | ETA 1.8m
Epoch 171/500 | Batch 130/202 | Rec 0.000857 | Seg 0.357773 | Elapsed 2.8m | ETA 1.6m
Epoch 171/500 | Batch 140/202 | Rec 0.000866 | Seg 0.361844 | Elapsed 3.1m | ETA 1.4m
Epoch 171/500 | Batch 150/202 | Rec 0.000871 | Seg 0.368524 | Elapsed 3.3m | ETA 1.1m
Epoch 171/500 | Batch 160/202 | Rec 0.000877 | Seg 0.372185 | Elapsed 3.5m | ETA 0.9m
Epoch 171/500 | Batch 170/202 | Rec 0.000886 | Seg 0.379368 | Elapsed 3.7m | ETA 0.7m
Epoch 171/500 | Batch 180/202 | Rec 0.000882 | Seg 0.379272 | Elapsed 3.9m | ETA 0.5m
Epoch 171/500 | Batch 190/202 | Rec 0.000883 | Seg 0.378437 | Elapsed 4.2m | ETA 0.3m
Epoch 171/500 | Batch 200/202 | Rec 0.000895 | Seg 0.379798 | Elapsed 4.4m | ETA 0.0m
Epoch 171/500 | Batch 202/202 | Rec 0.000891 | Seg 0.378115 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:30:59,734 - INFO: Rec loss: 0.0008911244920743076
2026-09-23 12:30:59,735 - INFO: Seg loss: 0.3781151922770066
2026-09-23 12:30:59,735 - INFO: λ_rec: 1
2026-09-23 12:30:59,735 - INFO: λ_seg: 0.0001
2026-09-23 12:32:16,417 - INFO: -------------------Epoch: 171------------------------
2026-09-23 12:32:16,421 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.549069  0.970785  0.000182
2026-09-23 12:32:16,428 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994455  0.997170  0.995286  0.999161  0.994696
real potato   0.828384  0.906088  0.984155  0.839582  0.999792
fake potato   0.876263  0.934002  0.982655  0.890029  0.999908
real apple    0.741318  0.851395  0.958848  0.765679  0.999078
fake apple    0.737614  0.848947  0.974550  0.752102  0.998990
real orange   0.493757  0.661050  0.996733  0.494558  0.999332
fake orange   0.765330  0.867017  0.805627  0.938653  0.999176
real grape    0.369497  0.539566  0.851181  0.395016  0.998593
fake grape    0.740863  0.851094  0.850251  0.852040  0.998898
real lemon    0.376096  0.546563  0.517393  0.579330  0.998871
fake lemon    0.829167  0.906557  0.988337  0.837360  0.999635
real avocado  0.818469  0.900124  0.868437  0.934319  0.999807
fake avocado  0.131072  0.231746  0.999028  0.131089  0.998960
real pepper   0.780658  0.876770  0.925437  0.833055  0.999144
fake pepper   0.909772  0.952705  0.982257  0.924973  0.999781
real plant    0.782762  0.878095  0.892662  0.864093  0.997601
fake plant    0.766384  0.867693  0.870085  0.865414  0.999790
real banana   0.386399  0.557371  0.898776  0.403979  0.998559
fake banana   0.553963  0.712919  0.632177  0.817435  0.998789
real onion    0.720026  0.837177  0.748172  0.950346  0.999666
fake onion    0.911199  0.953486  0.956670  0.950423  0.999942
real unknown  0.775397  0.873441  0.821699  0.932252  0.999957
fake unknown  0.197795  0.330229  0.217524  0.685621  0.997657
total         0.673332  0.777444  0.857302  0.766805  0.998984
total(-bg)    0.658736  0.767456  0.851030  0.756243  0.999178
2026-09-23 12:32:17,011 - INFO: Epoch accounting: {'epoch': 171, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11276238, 48169, 43934, 133121, 143419, 74268, 87937, 168962, 200964, 73378, 71631, 55321, 39819, 237648, 137454, 141055, 27263, 74539, 44914, 72217, 35199, 8562, 42260], 'crops_with_class': [202, 31, 22, 37, 34, 22, 27, 29, 37, 31, 33, 16, 16, 59, 34, 20, 29, 20, 18, 30, 14, 9, 18], 'targeted_crops_by_class': [0, 4, 3, 4, 3, 2, 6, 3, 5, 3, 5, 5, 5, 7, 2, 4, 8, 3, 2, 4, 3, 1, 5], 'sampled_scene_counts': [0, 1, 2, 1, 1, 2, 0, 1, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 0, 1, 1, 0, 1, 2, 2, 1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 1, 2, 1, 0, 1, 1, 0, 0, 1, 0, 3, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 3, 1, 2, 0, 1, 1, 2, 0, 3, 1, 3, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 1, 1, 2, 1, 2, 1, 1, 0, 1, 2, 0, 3, 1, 3, 1, 0, 3, 2, 3, 2, 2, 0, 2, 1, 0, 2, 0, 2, 3, 1, 0, 2, 2, 1, 2, 1, 0, 1, 3, 0, 1, 1, 1, 5, 1, 1, 1, 1, 2, 2, 2, 1, 1, 4, 1, 0, 1, 0, 2, 2, 2, 2, 1, 1, 1, 2, 1, 0, 0, 0, 2, 2, 0, 3, 0, 1, 2, 0, 1, 1, 1, 1, 1, 0, 2, 1, 0, 2, 1, 0], 'learning_rate': 7.415246449582297e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008911244920743076, 'train_segmentation_loss': 0.3781151922770066, 'val_foreground_miou_all22': 0.658735659064109, 'val_psnr_ref1': 37.5490690612793, 'elapsed_seconds': 341.84898257255554, 'peak_cuda_allocated_gib': 7.510265350341797}

Epoch 172/500 | Batch 10/202 | Rec 0.000858 | Seg 0.361771 | Elapsed 0.2m | ETA 4.1m
Epoch 172/500 | Batch 20/202 | Rec 0.000878 | Seg 0.363450 | Elapsed 0.4m | ETA 3.9m
Epoch 172/500 | Batch 30/202 | Rec 0.000918 | Seg 0.375052 | Elapsed 0.6m | ETA 3.7m
Epoch 172/500 | Batch 40/202 | Rec 0.000910 | Seg 0.370857 | Elapsed 0.9m | ETA 3.5m
Epoch 172/500 | Batch 50/202 | Rec 0.000936 | Seg 0.373101 | Elapsed 1.1m | ETA 3.3m
Epoch 172/500 | Batch 60/202 | Rec 0.000913 | Seg 0.365645 | Elapsed 1.3m | ETA 3.1m
Epoch 172/500 | Batch 70/202 | Rec 0.000914 | Seg 0.374878 | Elapsed 1.5m | ETA 2.8m
Epoch 172/500 | Batch 80/202 | Rec 0.000893 | Seg 0.360712 | Elapsed 1.7m | ETA 2.6m
Epoch 172/500 | Batch 90/202 | Rec 0.000890 | Seg 0.359412 | Elapsed 1.9m | ETA 2.4m
Epoch 172/500 | Batch 100/202 | Rec 0.000905 | Seg 0.364518 | Elapsed 2.2m | ETA 2.2m
Epoch 172/500 | Batch 110/202 | Rec 0.000927 | Seg 0.363172 | Elapsed 2.4m | ETA 2.0m
Epoch 172/500 | Batch 120/202 | Rec 0.000931 | Seg 0.360736 | Elapsed 2.6m | ETA 1.8m
Epoch 172/500 | Batch 130/202 | Rec 0.000918 | Seg 0.366086 | Elapsed 2.8m | ETA 1.6m
Epoch 172/500 | Batch 140/202 | Rec 0.000916 | Seg 0.378792 | Elapsed 3.0m | ETA 1.3m
Epoch 172/500 | Batch 150/202 | Rec 0.000932 | Seg 0.388701 | Elapsed 3.3m | ETA 1.1m
Epoch 172/500 | Batch 160/202 | Rec 0.000918 | Seg 0.389739 | Elapsed 3.5m | ETA 0.9m
Epoch 172/500 | Batch 170/202 | Rec 0.000934 | Seg 0.399240 | Elapsed 3.7m | ETA 0.7m
Epoch 172/500 | Batch 180/202 | Rec 0.000939 | Seg 0.397599 | Elapsed 3.9m | ETA 0.5m
Epoch 172/500 | Batch 190/202 | Rec 0.000945 | Seg 0.396752 | Elapsed 4.1m | ETA 0.3m
Epoch 172/500 | Batch 200/202 | Rec 0.000951 | Seg 0.392520 | Elapsed 4.3m | ETA 0.0m
Epoch 172/500 | Batch 202/202 | Rec 0.000957 | Seg 0.394879 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:36:39,472 - INFO: Rec loss: 0.0009565083639947513
2026-09-23 12:36:39,472 - INFO: Seg loss: 0.3948788688158487
2026-09-23 12:36:39,472 - INFO: λ_rec: 1
2026-09-23 12:36:39,473 - INFO: λ_seg: 0.0001
2026-09-23 12:37:56,114 - INFO: -------------------Epoch: 172------------------------
2026-09-23 12:37:56,118 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.342124  0.969326  0.000191
2026-09-23 12:37:56,125 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994203  0.997043  0.994859  0.999337  0.994453
real potato   0.679848  0.809368  0.986615  0.686177  0.999613
fake potato   0.892326  0.943050  0.956091  0.930457  0.999918
real apple    0.690368  0.816777  0.955561  0.713268  0.998896
fake apple    0.569662  0.725794  0.988232  0.573553  0.998364
real orange   0.531149  0.693746  1.000000  0.531149  0.999382
fake orange   0.803270  0.890854  0.820803  0.974097  0.999317
real grape    0.103857  0.188152  0.898189  0.105094  0.998107
fake grape    0.594273  0.745459  0.726760  0.765252  0.998067
real lemon    0.042737  0.081923  0.110792  0.065048  0.998288
fake lemon    0.799287  0.888399  0.985928  0.808511  0.999570
real avocado  0.795565  0.886095  0.982411  0.807061  0.999807
fake avocado  0.000000  0.000000  0.000000  0.000000  0.998803
real pepper   0.689715  0.816319  0.825277  0.807651  0.998671
fake pepper   0.870124  0.930502  0.971974  0.892516  0.999682
real plant    0.737372  0.848786  0.827219  0.871613  0.996895
fake plant    0.647764  0.786184  0.775602  0.797163  0.999655
real banana   0.196435  0.328332  0.704830  0.214043  0.998033
fake banana   0.442895  0.613850  0.516661  0.756221  0.998250
real onion    0.633909  0.775893  0.662720  0.935822  0.999512
fake onion    0.885735  0.939355  0.976017  0.905441  0.999926
real unknown  0.900858  0.947794  0.998943  0.901717  0.999984
fake unknown  0.137995  0.242491  0.150677  0.621152  0.996731
total         0.593015  0.691138  0.774616  0.680971  0.998692
total(-bg)    0.574779  0.677233  0.764605  0.666500  0.998885
2026-09-23 12:37:56,683 - INFO: Epoch accounting: {'epoch': 172, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11319116, 42045, 44570, 120191, 183897, 78800, 80053, 139228, 198298, 72746, 60748, 39840, 25695, 236552, 158698, 128115, 27289, 68752, 56263, 48057, 45283, 11724, 52312], 'crops_with_class': [202, 28, 21, 34, 41, 24, 26, 27, 39, 30, 26, 15, 11, 57, 37, 18, 26, 21, 21, 27, 22, 12, 25], 'targeted_crops_by_class': [0, 6, 2, 2, 10, 4, 2, 2, 6, 5, 4, 4, 2, 2, 7, 2, 7, 3, 4, 3, 4, 5, 7], 'sampled_scene_counts': [1, 0, 1, 2, 0, 2, 1, 2, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 3, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 2, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 1, 3, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 1, 0, 2, 1, 1, 1, 2, 0, 2, 1, 1, 1, 2, 2, 0, 1, 2, 1, 2, 2, 2, 0, 1, 1, 1, 3, 2, 1, 1, 1, 2, 2, 0, 2, 1, 0, 3, 1, 2, 0, 2, 1, 1, 2, 3, 2, 3, 2, 1, 0, 2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 1, 0, 1, 2, 0, 0, 3, 1, 0, 3, 1, 3, 3, 2, 2, 3, 0, 0, 1, 0, 1, 3, 0, 0, 2, 1], 'learning_rate': 7.387738040793838e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009565083639947513, 'train_segmentation_loss': 0.3948788688158487, 'val_foreground_miou_all22': 0.5747792902015058, 'val_psnr_ref1': 37.34212371826172, 'elapsed_seconds': 339.6631920337677, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 173/500 | Batch 10/202 | Rec 0.000925 | Seg 0.423629 | Elapsed 0.2m | ETA 4.2m
Epoch 173/500 | Batch 20/202 | Rec 0.000906 | Seg 0.384195 | Elapsed 0.4m | ETA 3.9m
Epoch 173/500 | Batch 30/202 | Rec 0.000960 | Seg 0.387473 | Elapsed 0.6m | ETA 3.7m
Epoch 173/500 | Batch 40/202 | Rec 0.000981 | Seg 0.389685 | Elapsed 0.9m | ETA 3.5m
Epoch 173/500 | Batch 50/202 | Rec 0.000991 | Seg 0.423408 | Elapsed 1.1m | ETA 3.3m
Epoch 173/500 | Batch 60/202 | Rec 0.001032 | Seg 0.423211 | Elapsed 1.3m | ETA 3.1m
Epoch 173/500 | Batch 70/202 | Rec 0.000991 | Seg 0.404267 | Elapsed 1.5m | ETA 2.9m
Epoch 173/500 | Batch 80/202 | Rec 0.001019 | Seg 0.403842 | Elapsed 1.7m | ETA 2.6m
Epoch 173/500 | Batch 90/202 | Rec 0.000998 | Seg 0.402330 | Elapsed 1.9m | ETA 2.4m
Epoch 173/500 | Batch 100/202 | Rec 0.000996 | Seg 0.407356 | Elapsed 2.2m | ETA 2.2m
Epoch 173/500 | Batch 110/202 | Rec 0.000983 | Seg 0.403844 | Elapsed 2.4m | ETA 2.0m
Epoch 173/500 | Batch 120/202 | Rec 0.000984 | Seg 0.409531 | Elapsed 2.6m | ETA 1.8m
Epoch 173/500 | Batch 130/202 | Rec 0.000969 | Seg 0.403108 | Elapsed 2.8m | ETA 1.5m
Epoch 173/500 | Batch 140/202 | Rec 0.000960 | Seg 0.398025 | Elapsed 3.0m | ETA 1.3m
Epoch 173/500 | Batch 150/202 | Rec 0.000952 | Seg 0.400094 | Elapsed 3.2m | ETA 1.1m
Epoch 173/500 | Batch 160/202 | Rec 0.000952 | Seg 0.400091 | Elapsed 3.4m | ETA 0.9m
Epoch 173/500 | Batch 170/202 | Rec 0.000949 | Seg 0.399881 | Elapsed 3.7m | ETA 0.7m
Epoch 173/500 | Batch 180/202 | Rec 0.000940 | Seg 0.395832 | Elapsed 3.9m | ETA 0.5m
Epoch 173/500 | Batch 190/202 | Rec 0.000946 | Seg 0.392120 | Elapsed 4.1m | ETA 0.3m
Epoch 173/500 | Batch 200/202 | Rec 0.000941 | Seg 0.391840 | Elapsed 4.3m | ETA 0.0m
Epoch 173/500 | Batch 202/202 | Rec 0.000938 | Seg 0.391663 | Elapsed 4.3m | ETA 0.0m

2026-09-23 12:42:17,555 - INFO: Rec loss: 0.0009382645434430238
2026-09-23 12:42:17,555 - INFO: Seg loss: 0.3916629561324521
2026-09-23 12:42:17,556 - INFO: λ_rec: 1
2026-09-23 12:42:17,556 - INFO: λ_seg: 0.0001
2026-09-23 12:43:34,121 - INFO: -------------------Epoch: 173------------------------
2026-09-23 12:43:34,125 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.284592  0.969348  0.000194
2026-09-23 12:43:34,132 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995211  0.997550  0.996415  0.998787  0.995424
real potato   0.943729  0.971000  0.988895  0.953838  0.999932
fake potato   0.877943  0.934955  0.897036  0.976330  0.999901
real apple    0.785582  0.879868  0.995310  0.788501  0.999258
fake apple    0.590040  0.742123  0.982941  0.596145  0.998436
real orange   0.805418  0.892174  0.989423  0.812413  0.999741
fake orange   0.904512  0.949812  0.928353  0.972391  0.999706
real grape    0.443626  0.614556  0.954587  0.453190  0.998813
fake grape    0.760879  0.864154  0.836700  0.893578  0.998961
real lemon    0.404783  0.576243  0.515907  0.652688  0.998872
fake lemon    0.816558  0.898967  0.993540  0.820916  0.999610
real avocado  0.791744  0.883719  0.858847  0.910181  0.999778
fake avocado  0.053696  0.101907  0.853413  0.054195  0.998857
real pepper   0.737200  0.848672  0.860493  0.837268  0.998908
fake pepper   0.889969  0.941732  0.991507  0.896806  0.999736
real plant    0.823540  0.903182  0.903136  0.903329  0.998064
fake plant    0.687736  0.814931  0.739647  0.907400  0.999672
real banana   0.425593  0.597031  0.918866  0.442211  0.998659
fake banana   0.577354  0.732004  0.646973  0.842900  0.998865
real onion    0.658819  0.794274  0.687446  0.940551  0.999560
fake onion    0.924412  0.960671  0.981823  0.940508  0.999951
real unknown  0.580045  0.734166  0.586325  0.981870  0.999886
fake unknown  0.174620  0.297288  0.188281  0.706447  0.997186
total         0.680566  0.779608  0.838951  0.794889  0.999034
total(-bg)    0.666264  0.769701  0.831793  0.785621  0.999198
2026-09-23 12:43:34,685 - INFO: Epoch accounting: {'epoch': 173, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11230452, 42393, 53161, 135759, 137287, 110971, 60322, 181486, 198275, 57737, 60999, 37988, 35857, 206555, 124009, 179811, 30254, 81753, 69605, 73720, 68158, 15359, 46361], 'crops_with_class': [202, 27, 26, 38, 37, 26, 27, 34, 32, 29, 23, 12, 16, 53, 32, 25, 27, 25, 33, 36, 29, 16, 23], 'targeted_crops_by_class': [0, 4, 6, 5, 4, 4, 5, 4, 6, 5, 3, 3, 1, 6, 3, 5, 5, 5, 5, 3, 6, 6, 5], 'sampled_scene_counts': [2, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 3, 2, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 3, 1, 1, 1, 1, 2, 1, 1, 3, 0, 3, 3, 2, 1, 1, 0, 0, 0, 5, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 4, 4, 4, 1, 0, 0, 1, 1, 1, 2, 0, 1, 0, 2, 1, 4, 1, 3, 0, 0, 3, 2, 1, 0, 2, 2, 3, 0, 1, 2, 1, 2, 1, 0, 1, 1, 1, 3, 3, 1, 1, 1, 0], 'learning_rate': 7.360135861674588e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009382645434430238, 'train_segmentation_loss': 0.3916629561324521, 'val_foreground_miou_all22': 0.6662635144840859, 'val_psnr_ref1': 37.2845915222168, 'elapsed_seconds': 337.993540763855, 'peak_cuda_allocated_gib': 7.512271881103516}

Epoch 174/500 | Batch 10/202 | Rec 0.000916 | Seg 0.339546 | Elapsed 0.2m | ETA 4.3m
Epoch 174/500 | Batch 20/202 | Rec 0.000813 | Seg 0.330237 | Elapsed 0.4m | ETA 4.0m
Epoch 174/500 | Batch 30/202 | Rec 0.000849 | Seg 0.358528 | Elapsed 0.6m | ETA 3.7m
Epoch 174/500 | Batch 40/202 | Rec 0.000862 | Seg 0.361471 | Elapsed 0.9m | ETA 3.5m
Epoch 174/500 | Batch 50/202 | Rec 0.000875 | Seg 0.357253 | Elapsed 1.1m | ETA 3.3m
Epoch 174/500 | Batch 60/202 | Rec 0.000874 | Seg 0.375053 | Elapsed 1.3m | ETA 3.1m
Epoch 174/500 | Batch 70/202 | Rec 0.000863 | Seg 0.367755 | Elapsed 1.5m | ETA 2.8m
Epoch 174/500 | Batch 80/202 | Rec 0.000877 | Seg 0.369871 | Elapsed 1.7m | ETA 2.6m
Epoch 174/500 | Batch 90/202 | Rec 0.000881 | Seg 0.372829 | Elapsed 1.9m | ETA 2.4m
Epoch 174/500 | Batch 100/202 | Rec 0.000883 | Seg 0.370401 | Elapsed 2.1m | ETA 2.2m
Epoch 174/500 | Batch 110/202 | Rec 0.000881 | Seg 0.369964 | Elapsed 2.4m | ETA 2.0m
Epoch 174/500 | Batch 120/202 | Rec 0.000871 | Seg 0.366605 | Elapsed 2.6m | ETA 1.8m
Epoch 174/500 | Batch 130/202 | Rec 0.000858 | Seg 0.365189 | Elapsed 2.8m | ETA 1.5m
Epoch 174/500 | Batch 140/202 | Rec 0.000885 | Seg 0.365874 | Elapsed 3.0m | ETA 1.3m
Epoch 174/500 | Batch 150/202 | Rec 0.000896 | Seg 0.365198 | Elapsed 3.2m | ETA 1.1m
Epoch 174/500 | Batch 160/202 | Rec 0.000899 | Seg 0.370515 | Elapsed 3.4m | ETA 0.9m
Epoch 174/500 | Batch 170/202 | Rec 0.000897 | Seg 0.373278 | Elapsed 3.6m | ETA 0.7m
Epoch 174/500 | Batch 180/202 | Rec 0.000902 | Seg 0.372649 | Elapsed 3.9m | ETA 0.5m
Epoch 174/500 | Batch 190/202 | Rec 0.000901 | Seg 0.372133 | Elapsed 4.1m | ETA 0.3m
Epoch 174/500 | Batch 200/202 | Rec 0.000899 | Seg 0.371751 | Elapsed 4.3m | ETA 0.0m
Epoch 174/500 | Batch 202/202 | Rec 0.000903 | Seg 0.373655 | Elapsed 4.3m | ETA 0.0m

2026-09-23 12:47:55,025 - INFO: Rec loss: 0.0009033620731540873
2026-09-23 12:47:55,025 - INFO: Seg loss: 0.37365543702156234
2026-09-23 12:47:55,025 - INFO: λ_rec: 1
2026-09-23 12:47:55,026 - INFO: λ_seg: 0.0001
2026-09-23 12:49:11,701 - INFO: -------------------Epoch: 174------------------------
2026-09-23 12:49:11,705 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.573864  0.969909  0.000182
2026-09-23 12:49:11,712 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995306  0.997598  0.996367  0.998931  0.995515
real potato   0.889113  0.941252  0.988084  0.898750  0.999866
fake potato   0.938821  0.968395  0.959877  0.977168  0.999954
real apple    0.787337  0.880967  0.973408  0.804644  0.999250
fake apple    0.600080  0.750015  0.982585  0.606531  0.998474
real orange   0.711822  0.831605  0.972412  0.726494  0.999612
fake orange   0.836831  0.911119  0.851603  0.979693  0.999453
real grape    0.582074  0.735789  0.967373  0.593729  0.999110
fake grape    0.817321  0.899429  0.891301  0.907808  0.999249
real lemon    0.312536  0.476183  0.547386  0.421449  0.998911
fake lemon    0.787931  0.881339  0.995010  0.791057  0.999550
real avocado  0.860191  0.924791  0.916344  0.933498  0.999859
fake avocado  0.023078  0.045110  0.994505  0.023081  0.998831
real pepper   0.794419  0.885383  0.915342  0.857417  0.999188
fake pepper   0.878930  0.935514  0.971659  0.902055  0.999704
real plant    0.813460  0.897086  0.892846  0.901468  0.997932
fake plant    0.758120  0.862372  0.810246  0.921779  0.999766
real banana   0.412720  0.584248  0.952995  0.421296  0.998653
fake banana   0.502501  0.668838  0.558707  0.833195  0.998483
real onion    0.610456  0.758068  0.622090  0.970275  0.999441
fake onion    0.826923  0.905213  0.850851  0.967110  0.999872
real unknown  0.943235  0.970739  0.991054  0.951336  0.999991
fake unknown  0.154402  0.267466  0.171477  0.607932  0.997195
total         0.688592  0.781675  0.859718  0.782465  0.999037
total(-bg)    0.674650  0.771860  0.853507  0.772626  0.999197
2026-09-23 12:49:12,261 - INFO: Epoch accounting: {'epoch': 174, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11222899, 56048, 57042, 125650, 173240, 95674, 85978, 182822, 176003, 88806, 71835, 42733, 31924, 228804, 138939, 140005, 17546, 32720, 74532, 79072, 59414, 10583, 46003], 'crops_with_class': [202, 33, 28, 33, 41, 27, 28, 31, 37, 41, 31, 14, 11, 60, 32, 20, 21, 13, 31, 36, 26, 10, 20], 'targeted_crops_by_class': [0, 3, 5, 4, 7, 6, 7, 6, 9, 2, 5, 4, 3, 9, 3, 5, 4, 1, 5, 6, 2, 4, 4], 'sampled_scene_counts': [0, 0, 3, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 3, 0, 3, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 1, 1, 2, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 0, 0, 0, 2, 1, 3, 1, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 3, 4, 1, 1, 0, 1, 0, 4, 2, 0, 1, 3, 1, 2, 3, 1, 1, 1, 1, 3, 2, 1, 0, 1, 2, 0, 2, 1, 1, 1, 3, 1, 0, 0, 3, 2, 0, 2, 1, 2, 2, 3, 2, 2, 2, 3, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 1, 2, 0, 2, 0, 1, 1, 0, 1, 0, 1, 2, 1, 2, 1, 2, 0, 2, 0, 1, 2, 3, 1, 1, 3, 2], 'learning_rate': 7.332441001911316e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009033620731540873, 'train_segmentation_loss': 0.37365543702156234, 'val_foreground_miou_all22': 0.6746500164729801, 'val_psnr_ref1': 37.573864135742184, 'elapsed_seconds': 337.566171169281, 'peak_cuda_allocated_gib': 7.509830474853516}

Epoch 175/500 | Batch 10/202 | Rec 0.001027 | Seg 0.439807 | Elapsed 0.2m | ETA 4.2m
Epoch 175/500 | Batch 20/202 | Rec 0.000967 | Seg 0.425771 | Elapsed 0.4m | ETA 4.0m
Epoch 175/500 | Batch 30/202 | Rec 0.000944 | Seg 0.414801 | Elapsed 0.7m | ETA 3.7m
Epoch 175/500 | Batch 40/202 | Rec 0.000960 | Seg 0.417542 | Elapsed 0.9m | ETA 3.5m
Epoch 175/500 | Batch 50/202 | Rec 0.000945 | Seg 0.419553 | Elapsed 1.1m | ETA 3.3m
Epoch 175/500 | Batch 60/202 | Rec 0.000958 | Seg 0.413641 | Elapsed 1.3m | ETA 3.1m
Epoch 175/500 | Batch 70/202 | Rec 0.000953 | Seg 0.416886 | Elapsed 1.5m | ETA 2.9m
Epoch 175/500 | Batch 80/202 | Rec 0.000957 | Seg 0.418986 | Elapsed 1.7m | ETA 2.6m
Epoch 175/500 | Batch 90/202 | Rec 0.000945 | Seg 0.404987 | Elapsed 1.9m | ETA 2.4m
Epoch 175/500 | Batch 100/202 | Rec 0.000924 | Seg 0.390797 | Elapsed 2.2m | ETA 2.2m
Epoch 175/500 | Batch 110/202 | Rec 0.000935 | Seg 0.393080 | Elapsed 2.4m | ETA 2.0m
Epoch 175/500 | Batch 120/202 | Rec 0.000929 | Seg 0.388893 | Elapsed 2.6m | ETA 1.8m
Epoch 175/500 | Batch 130/202 | Rec 0.000922 | Seg 0.388922 | Elapsed 2.8m | ETA 1.6m
Epoch 175/500 | Batch 140/202 | Rec 0.000913 | Seg 0.383362 | Elapsed 3.0m | ETA 1.3m
Epoch 175/500 | Batch 150/202 | Rec 0.000904 | Seg 0.378663 | Elapsed 3.2m | ETA 1.1m
Epoch 175/500 | Batch 160/202 | Rec 0.000909 | Seg 0.378736 | Elapsed 3.5m | ETA 0.9m
Epoch 175/500 | Batch 170/202 | Rec 0.000907 | Seg 0.381356 | Elapsed 3.7m | ETA 0.7m
Epoch 175/500 | Batch 180/202 | Rec 0.000906 | Seg 0.378777 | Elapsed 3.9m | ETA 0.5m
Epoch 175/500 | Batch 190/202 | Rec 0.000911 | Seg 0.383767 | Elapsed 4.1m | ETA 0.3m
Epoch 175/500 | Batch 200/202 | Rec 0.000914 | Seg 0.388924 | Elapsed 4.3m | ETA 0.0m
Epoch 175/500 | Batch 202/202 | Rec 0.000912 | Seg 0.388935 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:53:34,964 - INFO: Rec loss: 0.0009120751218697388
2026-09-23 12:53:34,964 - INFO: Seg loss: 0.38893453828474084
2026-09-23 12:53:34,964 - INFO: λ_rec: 1
2026-09-23 12:53:34,964 - INFO: λ_seg: 0.0001
2026-09-23 12:54:51,831 - INFO: -------------------Epoch: 175------------------------
2026-09-23 12:54:51,834 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.150103  0.969805  0.000201
2026-09-23 12:54:51,841 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994396  0.997140  0.995063  0.999327  0.994639
real potato   0.415275  0.586805  0.999693  0.415328  0.999300
fake potato   0.754465  0.860002  0.974284  0.769795  0.999818
real apple    0.625019  0.769195  0.797985  0.742503  0.998463
fake apple    0.580755  0.734734  0.961322  0.594649  0.998379
real orange   0.553871  0.712846  0.998956  0.554192  0.999412
fake orange   0.789908  0.882574  0.809471  0.970312  0.999261
real grape    0.323340  0.488634  0.945668  0.329460  0.998560
fake grape    0.722322  0.838727  0.815093  0.863878  0.998772
real lemon    0.229069  0.372702  0.376858  0.368735  0.998542
fake lemon    0.821662  0.902052  0.992553  0.826758  0.999620
real avocado  0.798567  0.887954  0.862314  0.915271  0.999785
fake avocado  0.080424  0.148859  0.875171  0.081357  0.998887
real pepper   0.793785  0.884989  0.917749  0.854580  0.999188
fake pepper   0.888938  0.941154  0.986047  0.900262  0.999732
real plant    0.775593  0.873566  0.898261  0.850287  0.997539
fake plant    0.623803  0.768273  0.775068  0.761695  0.999634
real banana   0.257003  0.408880  0.943313  0.261035  0.998304
fake banana   0.449508  0.620174  0.519304  0.769824  0.998266
real onion    0.731253  0.844717  0.800454  0.894275  0.999703
fake onion    0.936455  0.967135  0.987157  0.948005  0.999959
real unknown  0.910185  0.952931  0.968473  0.937977  0.999985
fake unknown  0.166341  0.285204  0.176679  0.739768  0.996876
total         0.618345  0.727359  0.842476  0.710838  0.998810
total(-bg)    0.601252  0.715096  0.835540  0.697725  0.998999
2026-09-23 12:54:52,375 - INFO: Epoch accounting: {'epoch': 175, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11180675, 50272, 51485, 145951, 133422, 81066, 82424, 124346, 268920, 62549, 54575, 46133, 34875, 259094, 125715, 112407, 29919, 100305, 75065, 84734, 71293, 11048, 51999], 'crops_with_class': [202, 29, 26, 37, 34, 26, 30, 26, 40, 29, 23, 19, 15, 64, 30, 14, 25, 29, 32, 37, 32, 12, 22], 'targeted_crops_by_class': [0, 2, 6, 1, 2, 4, 4, 3, 7, 3, 6, 5, 1, 4, 6, 2, 6, 6, 5, 2, 5, 5, 4], 'sampled_scene_counts': [1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 1, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 3, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 3, 1, 0, 1, 3, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 0, 3, 2, 3, 1, 3, 3, 1, 1, 0, 3, 1, 2, 2, 2, 1, 2, 1, 0, 2, 3, 1, 1, 2, 0, 3, 0, 2, 1, 0, 1, 2, 1, 1, 1, 3, 1, 3, 0, 4, 1, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 1, 3, 1, 3, 2, 2, 2, 1, 0, 1, 1, 2, 1, 1, 2, 2, 1, 2, 3, 4, 0, 1, 1, 0, 2, 4, 1, 1, 2], 'learning_rate': 7.304654554849664e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009120751218697388, 'train_segmentation_loss': 0.38893453828474084, 'val_foreground_miou_all22': 0.6012517689940142, 'val_psnr_ref1': 37.150103454589846, 'elapsed_seconds': 340.1053252220154, 'peak_cuda_allocated_gib': 7.508823394775391}

Epoch 176/500 | Batch 10/202 | Rec 0.000851 | Seg 0.372960 | Elapsed 0.2m | ETA 4.2m
Epoch 176/500 | Batch 20/202 | Rec 0.000791 | Seg 0.362287 | Elapsed 0.4m | ETA 4.0m
Epoch 176/500 | Batch 30/202 | Rec 0.000866 | Seg 0.375816 | Elapsed 0.6m | ETA 3.7m
Epoch 176/500 | Batch 40/202 | Rec 0.000815 | Seg 0.353803 | Elapsed 0.9m | ETA 3.5m
Epoch 176/500 | Batch 50/202 | Rec 0.000841 | Seg 0.359287 | Elapsed 1.1m | ETA 3.3m
Epoch 176/500 | Batch 60/202 | Rec 0.000872 | Seg 0.374638 | Elapsed 1.3m | ETA 3.0m
Epoch 176/500 | Batch 70/202 | Rec 0.000861 | Seg 0.361194 | Elapsed 1.5m | ETA 2.8m
Epoch 176/500 | Batch 80/202 | Rec 0.000848 | Seg 0.360701 | Elapsed 1.7m | ETA 2.6m
Epoch 176/500 | Batch 90/202 | Rec 0.000831 | Seg 0.356642 | Elapsed 1.9m | ETA 2.4m
Epoch 176/500 | Batch 100/202 | Rec 0.000867 | Seg 0.360969 | Elapsed 2.1m | ETA 2.2m
Epoch 176/500 | Batch 110/202 | Rec 0.000865 | Seg 0.367603 | Elapsed 2.4m | ETA 2.0m
Epoch 176/500 | Batch 120/202 | Rec 0.000873 | Seg 0.366524 | Elapsed 2.6m | ETA 1.8m
Epoch 176/500 | Batch 130/202 | Rec 0.000866 | Seg 0.359455 | Elapsed 2.8m | ETA 1.6m
Epoch 176/500 | Batch 140/202 | Rec 0.000869 | Seg 0.362585 | Elapsed 3.0m | ETA 1.3m
Epoch 176/500 | Batch 150/202 | Rec 0.000878 | Seg 0.368784 | Elapsed 3.2m | ETA 1.1m
Epoch 176/500 | Batch 160/202 | Rec 0.000894 | Seg 0.378413 | Elapsed 3.5m | ETA 0.9m
Epoch 176/500 | Batch 170/202 | Rec 0.000890 | Seg 0.381192 | Elapsed 3.7m | ETA 0.7m
Epoch 176/500 | Batch 180/202 | Rec 0.000885 | Seg 0.380683 | Elapsed 3.9m | ETA 0.5m
Epoch 176/500 | Batch 190/202 | Rec 0.000905 | Seg 0.381897 | Elapsed 4.1m | ETA 0.3m
Epoch 176/500 | Batch 200/202 | Rec 0.000896 | Seg 0.381182 | Elapsed 4.3m | ETA 0.0m
Epoch 176/500 | Batch 202/202 | Rec 0.000899 | Seg 0.381201 | Elapsed 4.4m | ETA 0.0m

2026-09-23 12:59:14,494 - INFO: Rec loss: 0.0008989848046088684
2026-09-23 12:59:14,495 - INFO: Seg loss: 0.3812009442302555
2026-09-23 12:59:14,495 - INFO: λ_rec: 1
2026-09-23 12:59:14,495 - INFO: λ_seg: 0.0001
2026-09-23 13:00:31,366 - INFO: -------------------Epoch: 176------------------------
2026-09-23 13:00:31,371 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.289028  0.970583  0.000194
2026-09-23 13:00:31,378 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994925  0.997406  0.995978  0.998938  0.995149
real potato   0.893130  0.943498  0.979550  0.910099  0.999870
fake potato   0.955789  0.977345  0.981212  0.973607  0.999967
real apple    0.838189  0.911923  0.972021  0.858912  0.999428
fake apple    0.562181  0.719692  0.990999  0.565066  0.998338
real orange   0.675114  0.806003  0.979463  0.684808  0.999566
fake orange   0.817072  0.899278  0.846512  0.959173  0.999385
real grape    0.632821  0.775077  0.941693  0.658627  0.999202
fake grape    0.864389  0.927212  0.953298  0.902611  0.999476
real lemon    0.532810  0.695158  0.629715  0.775902  0.999200
fake lemon    0.803772  0.891163  0.993088  0.808294  0.999583
real avocado  0.798558  0.887948  0.851651  0.927586  0.999783
fake avocado  0.611579  0.758934  1.000000  0.611579  0.999535
real pepper   0.773895  0.872488  0.875709  0.869389  0.999071
fake pepper   0.874745  0.933139  0.960306  0.907560  0.999690
real plant    0.820558  0.901386  0.906884  0.896052  0.998040
fake plant    0.859771  0.924549  0.926468  0.922738  0.999880
real banana   0.521278  0.685269  0.935605  0.540676  0.998884
fake banana   0.605642  0.754342  0.716890  0.796035  0.999046
real onion    0.681299  0.810394  0.708702  0.946293  0.999600
fake onion    0.951225  0.974953  0.993226  0.957436  0.999969
real unknown  0.879061  0.935589  0.941973  0.929389  0.999980
fake unknown  0.203637  0.338330  0.233469  0.614451  0.997975
total         0.745715  0.840047  0.883235  0.826749  0.999157
total(-bg)    0.734387  0.832894  0.878111  0.818922  0.999340
2026-09-23 13:00:32,066 - INFO: Epoch accounting: {'epoch': 176, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11214156, 38252, 48631, 171774, 119307, 84946, 68201, 170506, 192189, 77709, 67011, 57860, 32024, 222648, 130122, 191624, 23891, 87826, 85086, 55966, 42785, 8228, 47530], 'crops_with_class': [202, 27, 24, 44, 31, 27, 26, 32, 38, 35, 30, 18, 13, 57, 33, 24, 23, 24, 34, 30, 18, 9, 19], 'targeted_crops_by_class': [0, 4, 2, 3, 6, 9, 4, 5, 3, 2, 7, 9, 3, 5, 8, 4, 4, 4, 7, 4, 4, 2, 5], 'sampled_scene_counts': [1, 0, 1, 0, 1, 3, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 2, 1, 1, 0, 1, 0, 3, 0, 1, 1, 0, 1, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 3, 2, 0, 2, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 3, 1, 2, 2, 1, 3, 0, 2, 3, 1, 2, 2, 1, 0, 2, 1, 1, 2, 2, 0, 2, 1, 1, 1, 0, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 3, 1, 3, 2, 2, 2, 1, 3, 0, 1, 1, 2, 4, 2, 1, 2, 0, 2, 2, 2, 1, 2, 2, 0, 2, 0, 0, 2, 1, 1, 0, 1, 2, 3, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 3, 1], 'learning_rate': 7.276777617450981e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008989848046088684, 'train_segmentation_loss': 0.3812009442302555, 'val_foreground_miou_all22': 0.7343870394322584, 'val_psnr_ref1': 37.289027557373046, 'elapsed_seconds': 339.6830892562866, 'peak_cuda_allocated_gib': 7.508823394775391}

Epoch 177/500 | Batch 10/202 | Rec 0.000984 | Seg 0.372194 | Elapsed 0.2m | ETA 4.4m
Epoch 177/500 | Batch 20/202 | Rec 0.000893 | Seg 0.368684 | Elapsed 0.5m | ETA 4.2m
Epoch 177/500 | Batch 30/202 | Rec 0.000839 | Seg 0.354589 | Elapsed 0.7m | ETA 3.9m
Epoch 177/500 | Batch 40/202 | Rec 0.000872 | Seg 0.365947 | Elapsed 0.9m | ETA 3.6m
Epoch 177/500 | Batch 50/202 | Rec 0.000901 | Seg 0.385952 | Elapsed 1.1m | ETA 3.4m
Epoch 177/500 | Batch 60/202 | Rec 0.000857 | Seg 0.371688 | Elapsed 1.3m | ETA 3.2m
Epoch 177/500 | Batch 70/202 | Rec 0.000859 | Seg 0.378398 | Elapsed 1.6m | ETA 2.9m
Epoch 177/500 | Batch 80/202 | Rec 0.000848 | Seg 0.366434 | Elapsed 1.8m | ETA 2.7m
Epoch 177/500 | Batch 90/202 | Rec 0.000897 | Seg 0.369002 | Elapsed 2.0m | ETA 2.5m
Epoch 177/500 | Batch 100/202 | Rec 0.000899 | Seg 0.365290 | Elapsed 2.2m | ETA 2.3m
Epoch 177/500 | Batch 110/202 | Rec 0.000881 | Seg 0.358576 | Elapsed 2.4m | ETA 2.0m
Epoch 177/500 | Batch 120/202 | Rec 0.000877 | Seg 0.359716 | Elapsed 2.6m | ETA 1.8m
Epoch 177/500 | Batch 130/202 | Rec 0.000856 | Seg 0.353870 | Elapsed 2.9m | ETA 1.6m
Epoch 177/500 | Batch 140/202 | Rec 0.000869 | Seg 0.357725 | Elapsed 3.1m | ETA 1.4m
Epoch 177/500 | Batch 150/202 | Rec 0.000868 | Seg 0.359615 | Elapsed 3.3m | ETA 1.1m
Epoch 177/500 | Batch 160/202 | Rec 0.000865 | Seg 0.357157 | Elapsed 3.5m | ETA 0.9m
Epoch 177/500 | Batch 170/202 | Rec 0.000888 | Seg 0.359055 | Elapsed 3.7m | ETA 0.7m
Epoch 177/500 | Batch 180/202 | Rec 0.000895 | Seg 0.359014 | Elapsed 3.9m | ETA 0.5m
Epoch 177/500 | Batch 190/202 | Rec 0.000899 | Seg 0.360882 | Elapsed 4.1m | ETA 0.3m
Epoch 177/500 | Batch 200/202 | Rec 0.000891 | Seg 0.358197 | Elapsed 4.4m | ETA 0.0m
Epoch 177/500 | Batch 202/202 | Rec 0.000889 | Seg 0.356179 | Elapsed 4.4m | ETA 0.0m

2026-09-23 13:04:55,860 - INFO: Rec loss: 0.0008890754595113051
2026-09-23 13:04:55,860 - INFO: Seg loss: 0.3561793940861036
2026-09-23 13:04:55,860 - INFO: λ_rec: 1
2026-09-23 13:04:55,860 - INFO: λ_seg: 0.0001
2026-09-23 13:06:12,022 - INFO: -------------------Epoch: 177------------------------
2026-09-23 13:06:12,026 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.061535  0.969496  0.000204
2026-09-23 13:06:12,033 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995143  0.997516  0.996348  0.998786  0.995359
real potato   0.656449  0.792550  0.996140  0.658123  0.999588
fake potato   0.671053  0.803101  0.995662  0.673021  0.999760
real apple    0.688369  0.815375  0.874159  0.764087  0.998807
fake apple    0.793281  0.884676  0.925494  0.847397  0.999166
real orange   0.479736  0.648364  1.000000  0.479736  0.999314
fake orange   0.773743  0.872391  0.786114  0.980066  0.999180
real grape    0.451899  0.622448  0.874058  0.483374  0.998776
fake grape    0.781708  0.877431  0.868147  0.887019  0.999084
real lemon    0.263620  0.417196  0.410054  0.424695  0.998606
fake lemon    0.748775  0.856293  0.999327  0.749153  0.999468
real avocado  0.733653  0.846317  0.759192  0.956158  0.999677
fake avocado  0.705329  0.827157  0.996228  0.707218  0.999646
real pepper   0.769742  0.869842  0.895889  0.845361  0.999075
fake pepper   0.878480  0.935260  0.997173  0.880673  0.999710
real plant    0.803407  0.890938  0.879327  0.902963  0.997790
fake plant    0.869744  0.930285  0.928735  0.931940  0.999889
real banana   0.363630  0.533287  0.956438  0.369754  0.998546
fake banana   0.493727  0.661020  0.541376  0.848706  0.998399
real onion    0.709917  0.830303  0.755750  0.921297  0.999660
fake onion    0.950689  0.974671  0.999492  0.951149  0.999969
real unknown  0.856410  0.922602  0.891459  0.956107  0.999974
fake unknown  0.296573  0.457427  0.341905  0.691054  0.998619
total         0.684134  0.794193  0.855151  0.778601  0.999046
total(-bg)    0.669997  0.784952  0.848733  0.768593  0.999214
2026-09-23 13:06:12,547 - INFO: Epoch accounting: {'epoch': 177, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11361378, 61334, 56239, 110984, 168186, 82188, 69245, 100050, 171968, 77566, 48116, 49826, 45258, 221376, 110436, 144704, 28816, 82252, 74005, 71429, 49510, 12298, 41108], 'crops_with_class': [202, 32, 25, 31, 41, 23, 25, 24, 32, 33, 24, 16, 15, 51, 29, 20, 27, 25, 28, 33, 25, 12, 20], 'targeted_crops_by_class': [0, 8, 5, 7, 5, 3, 5, 2, 3, 3, 3, 0, 5, 4, 1, 8, 7, 5, 4, 2, 2, 2, 6], 'sampled_scene_counts': [1, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 1, 1, 3, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 2, 1, 2, 0, 2, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 3, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 2, 2, 2, 1, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 2, 1, 3, 2, 0, 1, 2, 2, 1, 1, 1, 0, 0, 1, 2, 2, 1, 1, 2, 1, 0, 3, 1, 3, 1, 2, 2, 3, 1, 2, 1, 1, 3, 1, 1, 1, 1, 2, 1, 0, 0, 2, 1, 4, 1, 2, 1, 0, 1, 2, 1, 0, 2, 1, 2, 1, 2, 1, 2, 1, 1, 0, 1, 2, 3, 0, 0, 3, 3, 0, 4, 2, 1, 3, 0, 1, 0, 0, 1, 1, 4, 1, 1, 2], 'learning_rate': 7.24881129024903e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008890754595113051, 'train_segmentation_loss': 0.3561793940861036, 'val_foreground_miou_all22': 0.6699969303606887, 'val_psnr_ref1': 37.06153549194336, 'elapsed_seconds': 340.4722008705139, 'peak_cuda_allocated_gib': 7.506137847900391}

Epoch 178/500 | Batch 10/202 | Rec 0.000960 | Seg 0.430994 | Elapsed 0.2m | ETA 4.1m
Epoch 178/500 | Batch 20/202 | Rec 0.001011 | Seg 0.426792 | Elapsed 0.4m | ETA 3.8m
Epoch 178/500 | Batch 30/202 | Rec 0.001009 | Seg 0.391524 | Elapsed 0.6m | ETA 3.7m
Epoch 178/500 | Batch 40/202 | Rec 0.000967 | Seg 0.390393 | Elapsed 0.9m | ETA 3.5m
Epoch 178/500 | Batch 50/202 | Rec 0.000966 | Seg 0.383119 | Elapsed 1.1m | ETA 3.2m
Epoch 178/500 | Batch 60/202 | Rec 0.000946 | Seg 0.374382 | Elapsed 1.3m | ETA 3.0m
Epoch 178/500 | Batch 70/202 | Rec 0.000935 | Seg 0.375172 | Elapsed 1.5m | ETA 2.8m
Epoch 178/500 | Batch 80/202 | Rec 0.000932 | Seg 0.371175 | Elapsed 1.7m | ETA 2.6m
Epoch 178/500 | Batch 90/202 | Rec 0.000965 | Seg 0.373121 | Elapsed 1.9m | ETA 2.4m
Epoch 178/500 | Batch 100/202 | Rec 0.000948 | Seg 0.369480 | Elapsed 2.1m | ETA 2.2m
Epoch 178/500 | Batch 110/202 | Rec 0.000936 | Seg 0.374966 | Elapsed 2.4m | ETA 2.0m
Epoch 178/500 | Batch 120/202 | Rec 0.000935 | Seg 0.378060 | Elapsed 2.6m | ETA 1.8m
Epoch 178/500 | Batch 130/202 | Rec 0.000917 | Seg 0.377117 | Elapsed 2.8m | ETA 1.6m
Epoch 178/500 | Batch 140/202 | Rec 0.000907 | Seg 0.374242 | Elapsed 3.0m | ETA 1.3m
Epoch 178/500 | Batch 150/202 | Rec 0.000923 | Seg 0.383288 | Elapsed 3.2m | ETA 1.1m
Epoch 178/500 | Batch 160/202 | Rec 0.000915 | Seg 0.381561 | Elapsed 3.5m | ETA 0.9m
Epoch 178/500 | Batch 170/202 | Rec 0.000910 | Seg 0.379661 | Elapsed 3.7m | ETA 0.7m
Epoch 178/500 | Batch 180/202 | Rec 0.000911 | Seg 0.382044 | Elapsed 3.9m | ETA 0.5m
Epoch 178/500 | Batch 190/202 | Rec 0.000920 | Seg 0.387918 | Elapsed 4.1m | ETA 0.3m
Epoch 178/500 | Batch 200/202 | Rec 0.000915 | Seg 0.384216 | Elapsed 4.3m | ETA 0.0m
Epoch 178/500 | Batch 202/202 | Rec 0.000914 | Seg 0.382833 | Elapsed 4.4m | ETA 0.0m

2026-09-23 13:10:34,058 - INFO: Rec loss: 0.000914028353699815
2026-09-23 13:10:34,058 - INFO: Seg loss: 0.38283262969833787
2026-09-23 13:10:34,058 - INFO: λ_rec: 1
2026-09-23 13:10:34,058 - INFO: λ_seg: 0.0001
2026-09-23 13:11:50,378 - INFO: -------------------Epoch: 178------------------------
2026-09-23 13:11:50,382 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.603833  0.970193  0.000182
2026-09-23 13:11:50,389 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994341  0.997113  0.995227  0.999105  0.994587
real potato   0.546915  0.707058  0.999534  0.547054  0.999458
fake potato   0.674351  0.805459  0.987530  0.680142  0.999761
real apple    0.676805  0.807206  0.849954  0.768642  0.998734
fake apple    0.800394  0.889082  0.969868  0.820805  0.999227
real orange   0.608906  0.756872  0.989714  0.612784  0.999481
fake orange   0.803435  0.890956  0.827641  0.964876  0.999324
real grape    0.440199  0.611257  0.849434  0.477454  0.998732
fake grape    0.798671  0.888018  0.856333  0.922246  0.999140
real lemon    0.349044  0.517419  0.511080  0.524020  0.998851
fake lemon    0.834720  0.909865  0.983088  0.846881  0.999645
real avocado  0.711785  0.831579  0.798338  0.867816  0.999673
fake avocado  0.408975  0.580485  0.893245  0.429992  0.999256
real pepper   0.752078  0.858448  0.936069  0.792800  0.999044
fake pepper   0.750336  0.857313  0.998978  0.750912  0.999404
real plant    0.763491  0.865836  0.883138  0.849295  0.997368
fake plant    0.865169  0.927661  0.940504  0.915261  0.999886
real banana   0.363655  0.533314  0.992972  0.364593  0.998566
fake banana   0.584923  0.738060  0.668551  0.823822  0.998925
real onion    0.694559  0.819702  0.725546  0.942071  0.999626
fake onion    0.723081  0.839239  0.997668  0.724305  0.999825
real unknown  0.476767  0.645645  0.491762  0.939885  0.999835
fake unknown  0.209686  0.346641  0.229950  0.704093  0.997764
total         0.644882  0.766271  0.842440  0.750820  0.998962
total(-bg)    0.628997  0.755778  0.835495  0.739534  0.999160
2026-09-23 13:11:50,908 - INFO: Epoch accounting: {'epoch': 178, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11207880, 53718, 62607, 136122, 124598, 92748, 79105, 160129, 202295, 86105, 58369, 39367, 43384, 227190, 138328, 141210, 20848, 82172, 55221, 105378, 51903, 13608, 55987], 'crops_with_class': [202, 30, 25, 33, 35, 26, 27, 31, 36, 38, 27, 15, 17, 53, 36, 23, 22, 29, 22, 39, 26, 14, 23], 'targeted_crops_by_class': [0, 5, 4, 3, 5, 7, 4, 5, 5, 7, 6, 4, 3, 2, 6, 3, 5, 4, 2, 10, 4, 5, 5], 'sampled_scene_counts': [2, 0, 1, 1, 0, 1, 1, 1, 0, 3, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 1, 0, 1, 0, 2, 3, 1, 1, 0, 1, 1, 2, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 0, 1, 2, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 2, 2, 2, 2, 0, 2, 1, 1, 2, 1, 0, 3, 1, 0, 0, 0, 1, 2, 1, 2, 1, 0, 2, 1, 1, 4, 2, 2, 0, 0, 2, 1, 2, 1, 4, 5, 3, 2, 1, 1, 1, 2, 0, 2, 2, 3, 2, 1, 2, 1, 3, 1, 0, 1, 0, 3, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 0, 2, 2, 2, 2, 3, 3], 'learning_rate': 7.220756677306513e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000914028353699815, 'train_segmentation_loss': 0.38283262969833787, 'val_foreground_miou_all22': 0.628997413488053, 'val_psnr_ref1': 37.60383285522461, 'elapsed_seconds': 338.35361075401306, 'peak_cuda_allocated_gib': 7.505161285400391}

Epoch 179/500 | Batch 10/202 | Rec 0.001020 | Seg 0.429085 | Elapsed 0.2m | ETA 4.1m
Epoch 179/500 | Batch 20/202 | Rec 0.000963 | Seg 0.405534 | Elapsed 0.4m | ETA 3.8m
Epoch 179/500 | Batch 30/202 | Rec 0.000924 | Seg 0.356126 | Elapsed 0.6m | ETA 3.6m
Epoch 179/500 | Batch 40/202 | Rec 0.000872 | Seg 0.341452 | Elapsed 0.8m | ETA 3.4m
Epoch 179/500 | Batch 50/202 | Rec 0.000920 | Seg 0.365539 | Elapsed 1.0m | ETA 3.2m
Epoch 179/500 | Batch 60/202 | Rec 0.000891 | Seg 0.356769 | Elapsed 1.3m | ETA 3.0m
Epoch 179/500 | Batch 70/202 | Rec 0.000884 | Seg 0.363553 | Elapsed 1.5m | ETA 2.8m
Epoch 179/500 | Batch 80/202 | Rec 0.000868 | Seg 0.363362 | Elapsed 1.7m | ETA 2.6m
Epoch 179/500 | Batch 90/202 | Rec 0.000875 | Seg 0.367813 | Elapsed 1.9m | ETA 2.4m
Epoch 179/500 | Batch 100/202 | Rec 0.000858 | Seg 0.360921 | Elapsed 2.1m | ETA 2.2m
Epoch 179/500 | Batch 110/202 | Rec 0.000835 | Seg 0.352926 | Elapsed 2.3m | ETA 2.0m
Epoch 179/500 | Batch 120/202 | Rec 0.000835 | Seg 0.349027 | Elapsed 2.6m | ETA 1.7m
Epoch 179/500 | Batch 130/202 | Rec 0.000840 | Seg 0.349592 | Elapsed 2.8m | ETA 1.5m
Epoch 179/500 | Batch 140/202 | Rec 0.000830 | Seg 0.349698 | Elapsed 3.0m | ETA 1.3m
Epoch 179/500 | Batch 150/202 | Rec 0.000832 | Seg 0.351083 | Elapsed 3.2m | ETA 1.1m
Epoch 179/500 | Batch 160/202 | Rec 0.000844 | Seg 0.354827 | Elapsed 3.4m | ETA 0.9m
Epoch 179/500 | Batch 170/202 | Rec 0.000833 | Seg 0.346213 | Elapsed 3.6m | ETA 0.7m
Epoch 179/500 | Batch 180/202 | Rec 0.000836 | Seg 0.345314 | Elapsed 3.9m | ETA 0.5m
Epoch 179/500 | Batch 190/202 | Rec 0.000838 | Seg 0.346497 | Elapsed 4.1m | ETA 0.3m
Epoch 179/500 | Batch 200/202 | Rec 0.000846 | Seg 0.348593 | Elapsed 4.3m | ETA 0.0m
Epoch 179/500 | Batch 202/202 | Rec 0.000845 | Seg 0.349300 | Elapsed 4.3m | ETA 0.0m

2026-09-23 13:16:09,952 - INFO: Rec loss: 0.000845019200166669
2026-09-23 13:16:09,952 - INFO: Seg loss: 0.34930021013363755
2026-09-23 13:16:09,952 - INFO: λ_rec: 1
2026-09-23 13:16:09,952 - INFO: λ_seg: 0.0001
2026-09-23 13:17:26,177 - INFO: -------------------Epoch: 179------------------------
2026-09-23 13:17:26,181 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.961834  0.971368  0.000168
2026-09-23 13:17:26,188 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994515  0.997200  0.995354  0.999154  0.994754
real potato   0.895017  0.944551  0.993666  0.900153  0.999874
fake potato   0.786503  0.880445  0.970722  0.805614  0.999841
real apple    0.664409  0.798324  0.982423  0.672402  0.998828
fake apple    0.720539  0.837524  0.939409  0.755658  0.998893
real orange   0.481010  0.649526  1.000000  0.481010  0.999316
fake orange   0.777199  0.874584  0.796238  0.970152  0.999204
real grape    0.608096  0.756244  0.827958  0.696046  0.999063
fake grape    0.788778  0.881868  0.882428  0.881409  0.999127
real lemon    0.114848  0.205984  0.250139  0.175149  0.998414
fake lemon    0.822334  0.902456  0.990943  0.828561  0.999621
real avocado  0.786691  0.880562  0.831703  0.935632  0.999764
fake avocado  0.487699  0.655598  0.999216  0.487886  0.999387
real pepper   0.779403  0.875978  0.934260  0.824629  0.999146
fake pepper   0.883617  0.938163  0.982553  0.897702  0.999718
real plant    0.819395  0.900684  0.923354  0.879195  0.998062
fake plant    0.843727  0.915191  0.969951  0.866373  0.999872
real banana   0.381561  0.552322  0.976912  0.385033  0.998598
fake banana   0.480637  0.649182  0.542544  0.808145  0.998394
real onion    0.735665  0.847655  0.768723  0.944773  0.999693
fake onion    0.934000  0.965824  0.984430  0.948005  0.999958
real unknown  0.698258  0.822273  0.721382  0.956107  0.999934
fake unknown  0.190755  0.320355  0.219234  0.594893  0.997874
total         0.681507  0.784891  0.847111  0.769290  0.999015
total(-bg)    0.667279  0.775241  0.840372  0.758842  0.999208
2026-09-23 13:17:26,882 - INFO: Epoch accounting: {'epoch': 179, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11372890, 53611, 68201, 118188, 114788, 74824, 77478, 131854, 176862, 87803, 66177, 40218, 45043, 196237, 97563, 99235, 25763, 93997, 61276, 109349, 80678, 5771, 40466], 'crops_with_class': [202, 35, 32, 33, 29, 22, 26, 24, 38, 37, 27, 12, 15, 51, 26, 19, 23, 30, 28, 44, 37, 6, 18], 'targeted_crops_by_class': [0, 2, 5, 3, 3, 1, 8, 2, 7, 5, 2, 5, 7, 9, 2, 5, 6, 9, 3, 10, 7, 1, 5], 'sampled_scene_counts': [1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 0, 2, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2, 3, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 2, 0, 1, 0, 1, 1, 1, 2, 3, 1, 1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 3, 0, 2, 2, 0, 3, 3, 1, 0, 1, 1, 1, 2, 1, 2, 0, 1, 1, 2, 1, 1, 1, 2, 3, 1, 0, 2, 1, 1, 0, 2, 3, 3, 2, 1, 0, 2, 0, 1, 1, 3, 2, 4, 1, 0, 1, 1, 3, 3, 0, 2, 2, 4, 1, 2, 0, 0, 2, 2, 1, 2, 1, 4, 2, 3, 1, 3, 0, 3, 3, 1, 1, 0, 0, 0, 0, 0, 3, 0, 1], 'learning_rate': 7.192614886171519e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000845019200166669, 'train_segmentation_loss': 0.34930021013363755, 'val_foreground_miou_all22': 0.6672791795547671, 'val_psnr_ref1': 37.961833801269535, 'elapsed_seconds': 335.9660153388977, 'peak_cuda_allocated_gib': 7.510807037353516}

Epoch 180/500 | Batch 10/202 | Rec 0.000892 | Seg 0.356662 | Elapsed 0.2m | ETA 4.0m
Epoch 180/500 | Batch 20/202 | Rec 0.000911 | Seg 0.352849 | Elapsed 0.4m | ETA 3.9m
Epoch 180/500 | Batch 30/202 | Rec 0.000833 | Seg 0.351569 | Elapsed 0.6m | ETA 3.7m
Epoch 180/500 | Batch 40/202 | Rec 0.000816 | Seg 0.336027 | Elapsed 0.8m | ETA 3.4m
Epoch 180/500 | Batch 50/202 | Rec 0.000803 | Seg 0.342615 | Elapsed 1.1m | ETA 3.2m
Epoch 180/500 | Batch 60/202 | Rec 0.000776 | Seg 0.326872 | Elapsed 1.3m | ETA 3.0m
Epoch 180/500 | Batch 70/202 | Rec 0.000792 | Seg 0.325274 | Elapsed 1.5m | ETA 2.8m
Epoch 180/500 | Batch 80/202 | Rec 0.000811 | Seg 0.325075 | Elapsed 1.7m | ETA 2.6m
Epoch 180/500 | Batch 90/202 | Rec 0.000834 | Seg 0.338253 | Elapsed 1.9m | ETA 2.4m
Epoch 180/500 | Batch 100/202 | Rec 0.000822 | Seg 0.331084 | Elapsed 2.1m | ETA 2.2m
Epoch 180/500 | Batch 110/202 | Rec 0.000832 | Seg 0.340577 | Elapsed 2.4m | ETA 2.0m
Epoch 180/500 | Batch 120/202 | Rec 0.000838 | Seg 0.345401 | Elapsed 2.6m | ETA 1.8m
Epoch 180/500 | Batch 130/202 | Rec 0.000837 | Seg 0.346418 | Elapsed 2.8m | ETA 1.5m
Epoch 180/500 | Batch 140/202 | Rec 0.000842 | Seg 0.348686 | Elapsed 3.0m | ETA 1.3m
Epoch 180/500 | Batch 150/202 | Rec 0.000849 | Seg 0.352361 | Elapsed 3.2m | ETA 1.1m
Epoch 180/500 | Batch 160/202 | Rec 0.000844 | Seg 0.353394 | Elapsed 3.4m | ETA 0.9m
Epoch 180/500 | Batch 170/202 | Rec 0.000842 | Seg 0.349263 | Elapsed 3.6m | ETA 0.7m
Epoch 180/500 | Batch 180/202 | Rec 0.000836 | Seg 0.350811 | Elapsed 3.9m | ETA 0.5m
Epoch 180/500 | Batch 190/202 | Rec 0.000835 | Seg 0.347687 | Elapsed 4.1m | ETA 0.3m
Epoch 180/500 | Batch 200/202 | Rec 0.000842 | Seg 0.349447 | Elapsed 4.3m | ETA 0.0m
Epoch 180/500 | Batch 202/202 | Rec 0.000845 | Seg 0.350329 | Elapsed 4.3m | ETA 0.0m

2026-09-23 13:21:47,024 - INFO: Rec loss: 0.0008447967030397284
2026-09-23 13:21:47,024 - INFO: Seg loss: 0.35032931999257294
2026-09-23 13:21:47,024 - INFO: λ_rec: 1
2026-09-23 13:21:47,024 - INFO: λ_seg: 0.0001
2026-09-23 13:23:03,213 - INFO: -------------------Epoch: 180------------------------
2026-09-23 13:23:03,217 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  37.713109  0.96994  0.000176
2026-09-23 13:23:03,224 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994493  0.997189  0.995273  0.999212  0.994732
real potato   0.865649  0.927937  0.987764  0.875032  0.999837
fake potato   0.640855  0.781076  0.986262  0.646628  0.999736
real apple    0.748961  0.856415  0.986001  0.757010  0.999125
fake apple    0.621300  0.766374  0.965547  0.635386  0.998538
real orange   0.714104  0.833161  1.000000  0.714104  0.999623
fake orange   0.845353  0.916147  0.893920  0.939612  0.999508
real grape    0.520945  0.684981  0.896161  0.554411  0.998936
fake grape    0.822358  0.902471  0.891959  0.913336  0.999270
real lemon    0.225579  0.368069  0.418416  0.328616  0.998674
fake lemon    0.827439  0.905523  0.981717  0.840389  0.999629
real avocado  0.736701  0.848342  0.885673  0.814121  0.999730
fake avocado  0.205050  0.340289  1.000000  0.205050  0.999049
real pepper   0.782638  0.878017  0.875373  0.880778  0.999105
fake pepper   0.900144  0.947398  0.979365  0.917547  0.999757
real plant    0.788639  0.881781  0.915029  0.850958  0.997719
fake plant    0.792251  0.884035  0.954646  0.823236  0.999828
real banana   0.434090  0.605342  0.876222  0.462447  0.998645
fake banana   0.521262  0.685253  0.595327  0.807316  0.998636
real onion    0.702337  0.825095  0.735999  0.938862  0.999641
fake onion    0.908100  0.951787  0.977812  0.927207  0.999941
real unknown  0.927688  0.962438  0.996932  0.930343  0.999988
fake unknown  0.167208  0.286477  0.180817  0.689605  0.997106
total         0.682311  0.784156  0.868531  0.758748  0.998989
total(-bg)    0.668121  0.774473  0.862770  0.747818  0.999183
2026-09-23 13:23:03,779 - INFO: Epoch accounting: {'epoch': 180, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11348832, 51416, 64398, 130245, 130699, 71618, 42531, 147600, 148401, 72355, 50908, 41240, 59901, 208023, 149512, 110053, 25610, 84278, 65086, 105143, 59791, 10120, 60512], 'crops_with_class': [202, 29, 31, 31, 34, 24, 15, 27, 26, 29, 20, 15, 22, 54, 34, 18, 23, 26, 32, 43, 27, 13, 22], 'targeted_crops_by_class': [0, 3, 5, 8, 6, 3, 1, 3, 3, 5, 5, 4, 5, 3, 4, 2, 5, 5, 6, 5, 8, 6, 5], 'sampled_scene_counts': [0, 3, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 2, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 2, 0, 1, 0, 0, 3, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 2, 1, 0, 2, 1, 0, 0, 3, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 2, 1, 3, 3, 1, 1, 1, 2, 0, 1, 3, 3, 1, 1, 1, 0, 0, 1, 1, 2, 2, 1, 2, 2, 0, 5, 3, 0, 3, 1, 1, 2, 1, 0, 1, 3, 2, 2, 3, 2, 0, 2, 3, 3, 0, 1, 2, 0, 1, 1, 1, 0, 1, 2, 1, 0, 4, 2, 1, 2, 0, 0, 1, 0, 2, 2, 0, 3], 'learning_rate': 7.164387027833775e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008447967030397284, 'train_segmentation_loss': 0.35032931999257294, 'val_foreground_miou_all22': 0.6681205678364648, 'val_psnr_ref1': 37.713108673095704, 'elapsed_seconds': 336.8892893791199, 'peak_cuda_allocated_gib': 7.512516021728516}

Epoch 181/500 | Batch 10/202 | Rec 0.000903 | Seg 0.438240 | Elapsed 0.2m | ETA 4.2m
Epoch 181/500 | Batch 20/202 | Rec 0.000935 | Seg 0.412102 | Elapsed 0.4m | ETA 4.0m
Epoch 181/500 | Batch 30/202 | Rec 0.000875 | Seg 0.401189 | Elapsed 0.6m | ETA 3.7m
Epoch 181/500 | Batch 40/202 | Rec 0.000898 | Seg 0.410801 | Elapsed 0.9m | ETA 3.5m
Epoch 181/500 | Batch 50/202 | Rec 0.000902 | Seg 0.415511 | Elapsed 1.1m | ETA 3.3m
Epoch 181/500 | Batch 60/202 | Rec 0.000912 | Seg 0.403228 | Elapsed 1.3m | ETA 3.0m
Epoch 181/500 | Batch 70/202 | Rec 0.000937 | Seg 0.386643 | Elapsed 1.5m | ETA 2.8m
Epoch 181/500 | Batch 80/202 | Rec 0.000941 | Seg 0.388202 | Elapsed 1.7m | ETA 2.6m
Epoch 181/500 | Batch 90/202 | Rec 0.000921 | Seg 0.381719 | Elapsed 1.9m | ETA 2.4m
Epoch 181/500 | Batch 100/202 | Rec 0.000903 | Seg 0.378861 | Elapsed 2.1m | ETA 2.2m
Epoch 181/500 | Batch 110/202 | Rec 0.000895 | Seg 0.372098 | Elapsed 2.3m | ETA 2.0m
Epoch 181/500 | Batch 120/202 | Rec 0.000904 | Seg 0.374675 | Elapsed 2.6m | ETA 1.7m
Epoch 181/500 | Batch 130/202 | Rec 0.000900 | Seg 0.379036 | Elapsed 2.8m | ETA 1.5m
Epoch 181/500 | Batch 140/202 | Rec 0.000889 | Seg 0.378144 | Elapsed 3.0m | ETA 1.3m
Epoch 181/500 | Batch 150/202 | Rec 0.000903 | Seg 0.383344 | Elapsed 3.2m | ETA 1.1m
Epoch 181/500 | Batch 160/202 | Rec 0.000898 | Seg 0.380360 | Elapsed 3.4m | ETA 0.9m
Epoch 181/500 | Batch 170/202 | Rec 0.000889 | Seg 0.379986 | Elapsed 3.6m | ETA 0.7m
Epoch 181/500 | Batch 180/202 | Rec 0.000886 | Seg 0.381789 | Elapsed 3.8m | ETA 0.5m
Epoch 181/500 | Batch 190/202 | Rec 0.000874 | Seg 0.376628 | Elapsed 4.0m | ETA 0.3m
Epoch 181/500 | Batch 200/202 | Rec 0.000871 | Seg 0.376000 | Elapsed 4.3m | ETA 0.0m
Epoch 181/500 | Batch 202/202 | Rec 0.000872 | Seg 0.375493 | Elapsed 4.3m | ETA 0.0m

2026-09-23 13:27:21,740 - INFO: Rec loss: 0.0008723575664778692
2026-09-23 13:27:21,740 - INFO: Seg loss: 0.3754926539662451
2026-09-23 13:27:21,741 - INFO: λ_rec: 1
2026-09-23 13:27:21,741 - INFO: λ_seg: 0.0001
2026-09-23 13:28:38,210 - INFO: -------------------Epoch: 181------------------------
2026-09-23 13:28:38,214 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.844171  0.971479  0.000171
2026-09-23 13:28:38,221 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994866  0.997376  0.995885  0.998973  0.995092
real potato   0.395129  0.566401  0.999677  0.395180  0.999276
fake potato   0.606793  0.755237  0.991488  0.609971  0.999712
real apple    0.627164  0.770817  0.791182  0.751570  0.998459
fake apple    0.655841  0.792107  0.993598  0.658624  0.998695
real orange   0.482766  0.651124  0.934980  0.499537  0.999295
fake orange   0.771615  0.871037  0.787119  0.975109  0.999174
real grape    0.209443  0.346315  0.891212  0.214938  0.998306
fake grape    0.751475  0.858055  0.854752  0.861486  0.998946
real lemon    0.179108  0.303753  0.321631  0.287847  0.998450
fake lemon    0.813830  0.897311  0.995866  0.816589  0.999605
real avocado  0.598552  0.748819  0.935531  0.624302  0.999611
fake avocado  0.000000  0.000000  0.000000  0.000000  0.998616
real pepper   0.831081  0.907699  0.974861  0.849282  0.999369
fake pepper   0.862689  0.926234  0.991456  0.869150  0.999670
real plant    0.754523  0.860039  0.828821  0.893809  0.997091
fake plant    0.765797  0.867317  0.822226  0.917753  0.999777
real banana   0.393182  0.564396  0.966102  0.398683  0.998617
fake banana   0.549497  0.709210  0.614580  0.838421  0.998736
real onion    0.661149  0.795965  0.695257  0.930924  0.999569
fake onion    0.927867  0.962534  0.993819  0.933253  0.999954
real unknown  0.608052  0.756212  0.615707  0.979962  0.999899
fake unknown  0.165485  0.283947  0.173278  0.786309  0.996659
total         0.591561  0.703996  0.789958  0.699638  0.998808
total(-bg)    0.573229  0.690661  0.780597  0.686032  0.998977
2026-09-23 13:28:38,747 - INFO: Epoch accounting: {'epoch': 181, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11260178, 60401, 76894, 106169, 182200, 63529, 97523, 112553, 230414, 80374, 54190, 36409, 61571, 223931, 108224, 86812, 30167, 82570, 68421, 81262, 53377, 17187, 63916], 'crops_with_class': [202, 30, 29, 34, 45, 21, 35, 24, 38, 37, 25, 11, 21, 61, 26, 16, 29, 24, 32, 37, 25, 18, 29], 'targeted_crops_by_class': [0, 4, 4, 5, 7, 3, 10, 4, 3, 5, 5, 3, 9, 5, 2, 2, 6, 6, 10, 6, 3, 4, 6], 'sampled_scene_counts': [1, 0, 1, 1, 0, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 3, 0, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 1, 1, 4, 1, 1, 1, 2, 2, 2, 2, 1, 0, 2, 2, 1, 1, 1, 4, 0, 0, 0, 2, 1, 4, 2, 2, 2, 0, 1, 0, 1, 3, 1, 2, 2, 3, 6, 1, 2, 2, 3, 4, 4, 1, 2, 0, 1, 2, 1, 1, 2, 2, 1, 2, 1, 3, 1, 1, 1, 1, 1, 1, 3, 2, 2, 1, 2, 0, 2, 2, 1, 2, 0, 1, 0, 1, 1, 3, 1, 3, 1, 0, 3], 'learning_rate': 7.136074216680792e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008723575664778692, 'train_segmentation_loss': 0.3754926539662451, 'val_foreground_miou_all22': 0.5732291490047295, 'val_psnr_ref1': 37.84417068481445, 'elapsed_seconds': 334.9589822292328, 'peak_cuda_allocated_gib': 7.510662078857422}

Epoch 182/500 | Batch 10/202 | Rec 0.000720 | Seg 0.306390 | Elapsed 0.2m | ETA 4.1m
Epoch 182/500 | Batch 20/202 | Rec 0.000765 | Seg 0.313368 | Elapsed 0.4m | ETA 3.9m
Epoch 182/500 | Batch 30/202 | Rec 0.000742 | Seg 0.312650 | Elapsed 0.6m | ETA 3.7m
Epoch 182/500 | Batch 40/202 | Rec 0.000754 | Seg 0.315101 | Elapsed 0.9m | ETA 3.5m
Epoch 182/500 | Batch 50/202 | Rec 0.000809 | Seg 0.323480 | Elapsed 1.1m | ETA 3.3m
Epoch 182/500 | Batch 60/202 | Rec 0.000808 | Seg 0.327515 | Elapsed 1.3m | ETA 3.0m
Epoch 182/500 | Batch 70/202 | Rec 0.000815 | Seg 0.332777 | Elapsed 1.5m | ETA 2.8m
Epoch 182/500 | Batch 80/202 | Rec 0.000802 | Seg 0.329691 | Elapsed 1.7m | ETA 2.6m
Epoch 182/500 | Batch 90/202 | Rec 0.000808 | Seg 0.341548 | Elapsed 1.9m | ETA 2.4m
Epoch 182/500 | Batch 100/202 | Rec 0.000814 | Seg 0.344878 | Elapsed 2.2m | ETA 2.2m
Epoch 182/500 | Batch 110/202 | Rec 0.000821 | Seg 0.346397 | Elapsed 2.4m | ETA 2.0m
Epoch 182/500 | Batch 120/202 | Rec 0.000846 | Seg 0.351356 | Elapsed 2.6m | ETA 1.8m
Epoch 182/500 | Batch 130/202 | Rec 0.000857 | Seg 0.353798 | Elapsed 2.8m | ETA 1.6m
Epoch 182/500 | Batch 140/202 | Rec 0.000859 | Seg 0.353869 | Elapsed 3.0m | ETA 1.3m
Epoch 182/500 | Batch 150/202 | Rec 0.000863 | Seg 0.351016 | Elapsed 3.2m | ETA 1.1m
Epoch 182/500 | Batch 160/202 | Rec 0.000857 | Seg 0.346812 | Elapsed 3.5m | ETA 0.9m
Epoch 182/500 | Batch 170/202 | Rec 0.000849 | Seg 0.345287 | Elapsed 3.7m | ETA 0.7m
Epoch 182/500 | Batch 180/202 | Rec 0.000850 | Seg 0.345103 | Elapsed 3.9m | ETA 0.5m
Epoch 182/500 | Batch 190/202 | Rec 0.000850 | Seg 0.345782 | Elapsed 4.1m | ETA 0.3m
Epoch 182/500 | Batch 200/202 | Rec 0.000869 | Seg 0.352708 | Elapsed 4.3m | ETA 0.0m
Epoch 182/500 | Batch 202/202 | Rec 0.000867 | Seg 0.352073 | Elapsed 4.4m | ETA 0.0m

2026-09-23 13:33:00,765 - INFO: Rec loss: 0.0008669697659696444
2026-09-23 13:33:00,765 - INFO: Seg loss: 0.35207279177732986
2026-09-23 13:33:00,765 - INFO: λ_rec: 1
2026-09-23 13:33:00,765 - INFO: λ_seg: 0.0001
2026-09-23 13:34:17,069 - INFO: -------------------Epoch: 182------------------------
2026-09-23 13:34:17,073 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.764419  0.970534  0.000175
2026-09-23 13:34:17,080 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995037  0.997462  0.996428  0.998600  0.995258
real potato   0.507839  0.673554  0.999248  0.508034  0.999411
fake potato   0.718520  0.836159  0.967520  0.736280  0.999790
real apple    0.655895  0.792144  0.834353  0.754091  0.998635
fake apple    0.704244  0.826410  0.942773  0.735693  0.998833
real orange   0.646374  0.785161  0.993443  0.649143  0.999532
fake orange   0.831561  0.907986  0.849353  0.975429  0.999434
real grape    0.407609  0.579106  0.838366  0.442374  0.998658
fake grape    0.737781  0.849057  0.783651  0.926494  0.998782
real lemon    0.321631  0.486668  0.502140  0.472215  0.998829
fake lemon    0.824482  0.903749  0.972340  0.844284  0.999620
real avocado  0.683660  0.812062  0.770250  0.858785  0.999631
fake avocado  0.321662  0.486714  0.865667  0.338562  0.999146
real pepper   0.791814  0.883763  0.900693  0.867554  0.999166
fake pepper   0.901326  0.948052  0.984892  0.913962  0.999762
real plant    0.812238  0.896342  0.900011  0.892803  0.997936
fake plant    0.733311  0.846089  0.856441  0.836081  0.999758
real banana   0.407339  0.578836  0.931736  0.419870  0.998627
fake banana   0.496449  0.663455  0.543191  0.852273  0.998410
real onion    0.718012  0.835814  0.756081  0.934471  0.999668
fake onion    0.937440  0.967660  0.990628  0.945828  0.999960
real unknown  0.750378  0.857340  0.783570  0.946565  0.999950
fake unknown  0.225342  0.367764  0.249006  0.703368  0.997963
total         0.657824  0.773102  0.835295  0.763163  0.998989
total(-bg)    0.642496  0.762904  0.827971  0.752462  0.999159
2026-09-23 13:34:17,610 - INFO: Epoch accounting: {'epoch': 182, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11383952, 32174, 57104, 106743, 166132, 64305, 78049, 151850, 165283, 58443, 60321, 51252, 40844, 195243, 106677, 136677, 25744, 73886, 74846, 77856, 57924, 17877, 55090], 'crops_with_class': [202, 22, 25, 33, 39, 21, 32, 27, 33, 26, 26, 17, 15, 53, 29, 23, 25, 22, 30, 32, 23, 19, 27], 'targeted_crops_by_class': [0, 7, 4, 6, 3, 3, 4, 3, 3, 6, 2, 4, 6, 5, 1, 2, 8, 4, 4, 3, 4, 7, 5], 'sampled_scene_counts': [0, 0, 2, 1, 0, 0, 1, 2, 3, 3, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 3, 1, 1, 3, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 3, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 2, 1, 0, 2, 2, 2, 1, 1, 0, 0, 1, 2, 0, 2, 1, 1, 1, 0, 3, 1, 1, 0, 1, 3, 4, 1, 0, 0, 2, 1, 0, 1, 1, 1, 2, 0, 2, 1, 5, 4, 4, 2, 0, 1, 1, 3, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 3, 0, 0, 2, 1, 4, 1, 1, 1, 2, 1, 1, 0, 1, 0, 2, 0, 3, 1, 0], 'learning_rate': 7.107677570453875e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0008669697659696444, 'train_segmentation_loss': 0.35207279177732986, 'val_foreground_miou_all22': 0.6424958403669686, 'val_psnr_ref1': 37.76441879272461, 'elapsed_seconds': 338.85569071769714, 'peak_cuda_allocated_gib': 7.516544342041016}

Epoch 183/500 | Batch 10/202 | Rec 0.000820 | Seg 0.360758 | Elapsed 0.2m | ETA 3.9m
Epoch 183/500 | Batch 20/202 | Rec 0.000779 | Seg 0.339320 | Elapsed 0.4m | ETA 3.8m
Epoch 183/500 | Batch 30/202 | Rec 0.000787 | Seg 0.356195 | Elapsed 0.6m | ETA 3.7m
Epoch 183/500 | Batch 40/202 | Rec 0.000753 | Seg 0.349198 | Elapsed 0.8m | ETA 3.4m
Epoch 183/500 | Batch 50/202 | Rec 0.000746 | Seg 0.339929 | Elapsed 1.1m | ETA 3.2m
Epoch 183/500 | Batch 60/202 | Rec 0.000787 | Seg 0.345929 | Elapsed 1.3m | ETA 3.0m
Epoch 183/500 | Batch 70/202 | Rec 0.000789 | Seg 0.350822 | Elapsed 1.5m | ETA 2.8m
Epoch 183/500 | Batch 80/202 | Rec 0.000792 | Seg 0.352116 | Elapsed 1.7m | ETA 2.6m
Epoch 183/500 | Batch 90/202 | Rec 0.000796 | Seg 0.358258 | Elapsed 1.9m | ETA 2.4m
Epoch 183/500 | Batch 100/202 | Rec 0.000789 | Seg 0.349753 | Elapsed 2.1m | ETA 2.2m
Epoch 183/500 | Batch 110/202 | Rec 0.000791 | Seg 0.352788 | Elapsed 2.3m | ETA 2.0m
Epoch 183/500 | Batch 120/202 | Rec 0.000776 | Seg 0.345396 | Elapsed 2.6m | ETA 1.7m
Epoch 183/500 | Batch 130/202 | Rec 0.000775 | Seg 0.343534 | Elapsed 2.8m | ETA 1.5m
Epoch 183/500 | Batch 140/202 | Rec 0.000792 | Seg 0.349082 | Elapsed 3.0m | ETA 1.3m
Epoch 183/500 | Batch 150/202 | Rec 0.000791 | Seg 0.349208 | Elapsed 3.2m | ETA 1.1m
Epoch 183/500 | Batch 160/202 | Rec 0.000787 | Seg 0.348715 | Elapsed 3.4m | ETA 0.9m
Epoch 183/500 | Batch 170/202 | Rec 0.000793 | Seg 0.356069 | Elapsed 3.6m | ETA 0.7m
Epoch 183/500 | Batch 180/202 | Rec 0.000791 | Seg 0.353727 | Elapsed 3.8m | ETA 0.5m
Epoch 183/500 | Batch 190/202 | Rec 0.000801 | Seg 0.355426 | Elapsed 4.1m | ETA 0.3m
Epoch 183/500 | Batch 200/202 | Rec 0.000802 | Seg 0.354650 | Elapsed 4.3m | ETA 0.0m
Epoch 183/500 | Batch 202/202 | Rec 0.000803 | Seg 0.353382 | Elapsed 4.3m | ETA 0.0m

2026-09-23 13:38:36,784 - INFO: Rec loss: 0.0008025551152140096
2026-09-23 13:38:36,784 - INFO: Seg loss: 0.3533820365325059
2026-09-23 13:38:36,784 - INFO: λ_rec: 1
2026-09-23 13:38:36,784 - INFO: λ_seg: 0.0001
2026-09-23 13:39:52,950 - INFO: -------------------Epoch: 183------------------------
2026-09-23 13:39:52,954 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.985648  0.971562  0.000166
2026-09-23 13:39:52,961 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995148  0.997518  0.996435  0.998704  0.995365
real potato   0.811797  0.896074  0.975962  0.828360  0.999770
fake potato   0.747290  0.855321  0.947087  0.779849  0.999808
real apple    0.661786  0.796427  0.938768  0.691641  0.998781
fake apple    0.648331  0.786604  0.988983  0.653047  0.998663
real orange   0.528814  0.691751  0.995002  0.530222  0.999377
fake orange   0.789018  0.882019  0.807982  0.971112  0.999257
real grape    0.611192  0.758634  0.868230  0.673683  0.999105
fake grape    0.834450  0.909705  0.910507  0.909005  0.999333
real lemon    0.388600  0.559650  0.548102  0.571800  0.998943
fake lemon    0.829240  0.906600  0.994745  0.832889  0.999637
real avocado  0.768717  0.869187  0.805322  0.944171  0.999736
fake avocado  0.473543  0.642684  0.999731  0.473604  0.999370
real pepper   0.807785  0.893624  0.943065  0.849199  0.999261
fake pepper   0.920947  0.958797  0.991252  0.928494  0.999810
real plant    0.829789  0.906928  0.926572  0.888196  0.998178
fake plant    0.841947  0.914143  0.913318  0.915069  0.999863
real banana   0.499002  0.665732  0.906506  0.526076  0.998813
fake banana   0.496865  0.663827  0.540138  0.861148  0.998396
real onion    0.742022  0.851859  0.782633  0.934639  0.999706
fake onion    0.947343  0.972910  0.989253  0.957195  0.999966
real unknown  0.436481  0.607665  0.442366  0.970420  0.999800
fake unknown  0.188959  0.317821  0.205413  0.702282  0.997460
total         0.686916  0.795890  0.844234  0.799600  0.999061
total(-bg)    0.672905  0.786725  0.837315  0.790550  0.999229
2026-09-23 13:39:53,659 - INFO: Epoch accounting: {'epoch': 183, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11330786, 51493, 70855, 116536, 139733, 79496, 60501, 121093, 143192, 65944, 76511, 54021, 55290, 239163, 110899, 122260, 19931, 87357, 91150, 81827, 78685, 10915, 30634], 'crops_with_class': [202, 29, 31, 32, 35, 25, 24, 25, 30, 30, 26, 18, 20, 59, 32, 23, 19, 24, 37, 38, 34, 13, 17], 'targeted_crops_by_class': [0, 2, 9, 5, 5, 6, 4, 4, 2, 4, 3, 6, 6, 6, 3, 5, 3, 4, 8, 5, 6, 5, 4], 'sampled_scene_counts': [0, 1, 0, 1, 0, 1, 1, 0, 2, 2, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 1, 2, 0, 1, 0, 1, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 2, 3, 2, 1, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 0, 2, 1, 1, 2, 1, 3, 0, 1, 0, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 0, 0, 2, 2, 1, 2, 3, 3, 2, 1, 1, 3, 3, 1, 2, 2, 3, 2, 1, 1, 0, 3, 1, 2, 2, 2, 0, 1, 1, 2, 1, 1, 1, 2, 1, 0, 0, 2, 2, 2, 0, 2, 0, 1, 3, 2, 0, 1, 2, 3, 0, 1, 0, 0, 2, 3, 4, 1, 2], 'learning_rate': 7.079198210203997e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008025551152140096, 'train_segmentation_loss': 0.3533820365325059, 'val_foreground_miou_all22': 0.6729054148903384, 'val_psnr_ref1': 37.985648498535156, 'elapsed_seconds': 336.0413134098053, 'peak_cuda_allocated_gib': 7.512271881103516}

Epoch 184/500 | Batch 10/202 | Rec 0.000781 | Seg 0.343976 | Elapsed 0.2m | ETA 4.1m
Epoch 184/500 | Batch 20/202 | Rec 0.000858 | Seg 0.372290 | Elapsed 0.4m | ETA 3.9m
Epoch 184/500 | Batch 30/202 | Rec 0.000873 | Seg 0.361215 | Elapsed 0.6m | ETA 3.7m
Epoch 184/500 | Batch 40/202 | Rec 0.000851 | Seg 0.358730 | Elapsed 0.9m | ETA 3.5m
Epoch 184/500 | Batch 50/202 | Rec 0.000859 | Seg 0.358528 | Elapsed 1.1m | ETA 3.2m
Epoch 184/500 | Batch 60/202 | Rec 0.000880 | Seg 0.368182 | Elapsed 1.3m | ETA 3.0m
Epoch 184/500 | Batch 70/202 | Rec 0.000872 | Seg 0.362272 | Elapsed 1.5m | ETA 2.8m
Epoch 184/500 | Batch 80/202 | Rec 0.000877 | Seg 0.351463 | Elapsed 1.7m | ETA 2.6m
Epoch 184/500 | Batch 90/202 | Rec 0.000894 | Seg 0.361131 | Elapsed 1.9m | ETA 2.4m
Epoch 184/500 | Batch 100/202 | Rec 0.000913 | Seg 0.370513 | Elapsed 2.1m | ETA 2.2m
Epoch 184/500 | Batch 110/202 | Rec 0.000907 | Seg 0.366682 | Elapsed 2.4m | ETA 2.0m
Epoch 184/500 | Batch 120/202 | Rec 0.000901 | Seg 0.365585 | Elapsed 2.6m | ETA 1.8m
Epoch 184/500 | Batch 130/202 | Rec 0.000906 | Seg 0.365873 | Elapsed 2.8m | ETA 1.5m
Epoch 184/500 | Batch 140/202 | Rec 0.000892 | Seg 0.358919 | Elapsed 3.0m | ETA 1.3m
Epoch 184/500 | Batch 150/202 | Rec 0.000886 | Seg 0.357874 | Elapsed 3.2m | ETA 1.1m
Epoch 184/500 | Batch 160/202 | Rec 0.000894 | Seg 0.358923 | Elapsed 3.4m | ETA 0.9m
Epoch 184/500 | Batch 170/202 | Rec 0.000891 | Seg 0.358493 | Elapsed 3.7m | ETA 0.7m
Epoch 184/500 | Batch 180/202 | Rec 0.000895 | Seg 0.356147 | Elapsed 3.9m | ETA 0.5m
Epoch 184/500 | Batch 190/202 | Rec 0.000890 | Seg 0.356138 | Elapsed 4.1m | ETA 0.3m
Epoch 184/500 | Batch 200/202 | Rec 0.000885 | Seg 0.351772 | Elapsed 4.3m | ETA 0.0m
Epoch 184/500 | Batch 202/202 | Rec 0.000885 | Seg 0.351778 | Elapsed 4.4m | ETA 0.0m

2026-09-23 13:44:14,912 - INFO: Rec loss: 0.0008853411703660973
2026-09-23 13:44:14,913 - INFO: Seg loss: 0.3517780582429749
2026-09-23 13:44:14,913 - INFO: λ_rec: 1
2026-09-23 13:44:14,913 - INFO: λ_seg: 0.0001
2026-09-23 13:45:31,722 - INFO: -------------------Epoch: 184------------------------
2026-09-23 13:45:31,727 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  36.97626  0.969367  0.000209
2026-09-23 13:45:31,734 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994793  0.997340  0.995683  0.999103  0.995022
real potato   0.584119  0.737422  0.999128  0.584417  0.999502
fake potato   0.676234  0.806801  0.979366  0.686008  0.999761
real apple    0.622862  0.767559  0.787162  0.749005  0.998435
fake apple    0.556269  0.714829  0.987742  0.560136  0.998313
real orange   0.846380  0.916749  0.971855  0.867647  0.999792
fake orange   0.909480  0.952545  0.932999  0.973031  0.999723
real grape    0.681021  0.810197  0.814949  0.805598  0.999212
fake grape    0.867454  0.928973  0.950304  0.908675  0.999486
real lemon    0.378742  0.549354  0.462350  0.676837  0.998695
fake lemon    0.832192  0.908361  0.975656  0.849838  0.999637
real avocado  0.739042  0.849892  0.767399  0.952381  0.999687
fake avocado  0.340048  0.507479  0.999625  0.340092  0.999210
real pepper   0.767943  0.868692  0.874767  0.862798  0.999046
fake pepper   0.769609  0.869758  0.980795  0.781384  0.999442
real plant    0.825760  0.904516  0.939522  0.872117  0.998159
fake plant    0.810059  0.895014  0.954003  0.842983  0.999843
real banana   0.406785  0.578277  0.965380  0.412807  0.998647
fake banana   0.697293  0.821603  0.836153  0.807648  0.999355
real onion    0.635878  0.777365  0.771277  0.783651  0.999595
fake onion    0.924560  0.960752  0.996364  0.927690  0.999952
real unknown  0.517903  0.682347  0.531699  0.952290  0.999858
fake unknown  0.164497  0.282487  0.178650  0.674937  0.997112
total         0.676040  0.786448  0.854471  0.777003  0.999021
total(-bg)    0.661551  0.776862  0.848052  0.766908  0.999203
2026-09-23 13:45:32,257 - INFO: Epoch accounting: {'epoch': 184, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11306214, 50957, 59658, 136310, 170460, 78621, 70459, 116437, 241804, 85332, 76888, 31274, 41767, 187096, 145262, 121675, 24460, 56295, 48372, 67868, 46689, 11084, 63290], 'crops_with_class': [202, 29, 23, 32, 39, 25, 24, 28, 43, 37, 30, 12, 13, 55, 38, 20, 22, 17, 23, 33, 22, 12, 26], 'targeted_crops_by_class': [0, 3, 7, 3, 2, 4, 3, 4, 11, 10, 1, 4, 4, 2, 4, 4, 5, 2, 1, 7, 4, 5, 2], 'sampled_scene_counts': [2, 0, 2, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 0, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 2, 2, 1, 0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 3, 0, 1, 2, 1, 2, 1, 1, 1, 0, 1, 1, 2, 1, 3, 3, 0, 2, 2, 2, 1, 1, 2, 3, 1, 2, 2, 0, 0, 3, 1, 0, 3, 2, 2, 2, 0, 2, 4, 4, 1, 2, 3, 0, 3, 2, 3, 2, 1, 2, 1, 1, 1, 3, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2, 1, 1, 2, 1, 2, 2, 0, 1], 'learning_rate': 7.050637260247533e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008853411703660973, 'train_segmentation_loss': 0.3517780582429749, 'val_foreground_miou_all22': 0.6615513365032584, 'val_psnr_ref1': 36.97625991821289, 'elapsed_seconds': 338.5855851173401, 'peak_cuda_allocated_gib': 7.510074615478516}

Epoch 185/500 | Batch 10/202 | Rec 0.000624 | Seg 0.249896 | Elapsed 0.2m | ETA 4.2m
Epoch 185/500 | Batch 20/202 | Rec 0.000699 | Seg 0.287077 | Elapsed 0.4m | ETA 3.9m
Epoch 185/500 | Batch 30/202 | Rec 0.000724 | Seg 0.278482 | Elapsed 0.6m | ETA 3.7m
Epoch 185/500 | Batch 40/202 | Rec 0.000760 | Seg 0.297812 | Elapsed 0.9m | ETA 3.5m
Epoch 185/500 | Batch 50/202 | Rec 0.000792 | Seg 0.314045 | Elapsed 1.1m | ETA 3.3m
Epoch 185/500 | Batch 60/202 | Rec 0.000811 | Seg 0.320986 | Elapsed 1.3m | ETA 3.1m
Epoch 185/500 | Batch 70/202 | Rec 0.000856 | Seg 0.340428 | Elapsed 1.5m | ETA 2.8m
Epoch 185/500 | Batch 80/202 | Rec 0.000881 | Seg 0.346305 | Elapsed 1.7m | ETA 2.6m
Epoch 185/500 | Batch 90/202 | Rec 0.000885 | Seg 0.351753 | Elapsed 1.9m | ETA 2.4m
Epoch 185/500 | Batch 100/202 | Rec 0.000902 | Seg 0.358708 | Elapsed 2.2m | ETA 2.2m
Epoch 185/500 | Batch 110/202 | Rec 0.000909 | Seg 0.361634 | Elapsed 2.4m | ETA 2.0m
Epoch 185/500 | Batch 120/202 | Rec 0.000887 | Seg 0.358788 | Elapsed 2.6m | ETA 1.8m
Epoch 185/500 | Batch 130/202 | Rec 0.000896 | Seg 0.360912 | Elapsed 2.8m | ETA 1.5m
Epoch 185/500 | Batch 140/202 | Rec 0.000888 | Seg 0.358127 | Elapsed 3.0m | ETA 1.3m
Epoch 185/500 | Batch 150/202 | Rec 0.000898 | Seg 0.362924 | Elapsed 3.2m | ETA 1.1m
Epoch 185/500 | Batch 160/202 | Rec 0.000903 | Seg 0.366607 | Elapsed 3.4m | ETA 0.9m
Epoch 185/500 | Batch 170/202 | Rec 0.000902 | Seg 0.371031 | Elapsed 3.6m | ETA 0.7m
Epoch 185/500 | Batch 180/202 | Rec 0.000902 | Seg 0.370994 | Elapsed 3.9m | ETA 0.5m
Epoch 185/500 | Batch 190/202 | Rec 0.000895 | Seg 0.372246 | Elapsed 4.1m | ETA 0.3m
Epoch 185/500 | Batch 200/202 | Rec 0.000897 | Seg 0.377974 | Elapsed 4.3m | ETA 0.0m
Epoch 185/500 | Batch 202/202 | Rec 0.000901 | Seg 0.377732 | Elapsed 4.3m | ETA 0.0m

2026-09-23 13:49:51,735 - INFO: Rec loss: 0.0009010474620148364
2026-09-23 13:49:51,735 - INFO: Seg loss: 0.37773215538351845
2026-09-23 13:49:51,736 - INFO: λ_rec: 1
2026-09-23 13:49:51,736 - INFO: λ_seg: 0.0001
2026-09-23 13:51:08,134 - INFO: -------------------Epoch: 185------------------------
2026-09-23 13:51:08,138 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.203755  0.970327  0.000198
2026-09-23 13:51:08,145 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994740  0.997313  0.995438  0.999296  0.994970
real potato   0.485212  0.653347  0.999475  0.485335  0.999384
fake potato   0.727200  0.842007  0.949277  0.756598  0.999793
real apple    0.709877  0.830275  0.838794  0.822026  0.998841
fake apple    0.621516  0.766538  0.927424  0.653290  0.998498
real orange   0.532940  0.695272  0.996542  0.533928  0.999383
fake orange   0.795989  0.886358  0.818362  0.966795  0.999291
real grape    0.641125  0.781275  0.947593  0.664693  0.999223
fake grape    0.780215  0.876490  0.913724  0.842264  0.999122
real lemon    0.241696  0.389250  0.370570  0.410023  0.998488
fake lemon    0.801938  0.890034  0.929840  0.853588  0.999554
real avocado  0.774338  0.872769  0.837153  0.911658  0.999753
fake avocado  0.747051  0.855164  0.993086  0.750956  0.999696
real pepper   0.792243  0.884030  0.894113  0.874270  0.999161
fake pepper   0.822193  0.902371  0.897027  0.907880  0.999532
real plant    0.828938  0.906420  0.932435  0.881911  0.998180
fake plant    0.757881  0.862217  0.926244  0.806557  0.999795
real banana   0.138719  0.243614  0.770148  0.144710  0.997981
fake banana   0.432624  0.603913  0.491067  0.784257  0.998108
real onion    0.706488  0.827952  0.821126  0.834994  0.999687
fake onion    0.911345  0.953566  0.965312  0.942201  0.999942
real unknown  0.941989  0.970078  0.964185  0.976145  0.999990
fake unknown  0.167017  0.286185  0.210648  0.446396  0.998124
total         0.667534  0.772889  0.843025  0.749990  0.998978
total(-bg)    0.652661  0.762687  0.836098  0.738658  0.999160
2026-09-23 13:51:08,679 - INFO: Epoch accounting: {'epoch': 185, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11181454, 51104, 47983, 143653, 147245, 89634, 71066, 160315, 270134, 63207, 75550, 64428, 59342, 223945, 116154, 159420, 33004, 60024, 50230, 74653, 46828, 14169, 34730], 'crops_with_class': [202, 30, 20, 40, 39, 29, 26, 32, 49, 28, 28, 20, 20, 53, 28, 21, 26, 17, 23, 31, 23, 14, 20], 'targeted_crops_by_class': [0, 3, 4, 7, 7, 4, 4, 3, 11, 3, 3, 8, 9, 3, 5, 5, 6, 2, 4, 4, 2, 3, 2], 'sampled_scene_counts': [1, 2, 0, 1, 0, 1, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 2, 1, 1, 1, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 2, 2, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 4, 1, 0, 2, 4, 2, 1, 1, 0, 2, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 3, 2, 2, 1, 1, 2, 2, 2, 2, 3, 4, 1, 0, 0, 0, 2, 1, 1, 1, 2, 3, 1, 0, 1, 2, 0, 1, 1, 1, 3, 3, 2, 0, 0, 2, 3, 4, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 4, 0, 1, 1, 2, 1, 2, 0, 2, 4, 1, 1, 0, 2, 0, 2, 0, 0, 0, 2, 3, 0, 2, 1, 3, 2, 1, 1, 0, 1], 'learning_rate': 7.021995848121885e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0009010474620148364, 'train_segmentation_loss': 0.37773215538351845, 'val_foreground_miou_all22': 0.6526605418474795, 'val_psnr_ref1': 37.20375518798828, 'elapsed_seconds': 336.4152355194092, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 186/500 | Batch 10/202 | Rec 0.000657 | Seg 0.326898 | Elapsed 0.2m | ETA 4.2m
Epoch 186/500 | Batch 20/202 | Rec 0.000940 | Seg 0.398802 | Elapsed 0.4m | ETA 3.9m
Epoch 186/500 | Batch 30/202 | Rec 0.000865 | Seg 0.357400 | Elapsed 0.6m | ETA 3.7m
Epoch 186/500 | Batch 40/202 | Rec 0.000857 | Seg 0.356958 | Elapsed 0.9m | ETA 3.5m
Epoch 186/500 | Batch 50/202 | Rec 0.000852 | Seg 0.356483 | Elapsed 1.1m | ETA 3.3m
Epoch 186/500 | Batch 60/202 | Rec 0.000836 | Seg 0.356166 | Elapsed 1.3m | ETA 3.1m
Epoch 186/500 | Batch 70/202 | Rec 0.000862 | Seg 0.357028 | Elapsed 1.5m | ETA 2.9m
Epoch 186/500 | Batch 80/202 | Rec 0.000853 | Seg 0.365625 | Elapsed 1.7m | ETA 2.7m
Epoch 186/500 | Batch 90/202 | Rec 0.000848 | Seg 0.367227 | Elapsed 1.9m | ETA 2.4m
Epoch 186/500 | Batch 100/202 | Rec 0.000846 | Seg 0.359294 | Elapsed 2.2m | ETA 2.2m
Epoch 186/500 | Batch 110/202 | Rec 0.000878 | Seg 0.364507 | Elapsed 2.4m | ETA 2.0m
Epoch 186/500 | Batch 120/202 | Rec 0.000865 | Seg 0.356851 | Elapsed 2.6m | ETA 1.8m
Epoch 186/500 | Batch 130/202 | Rec 0.000859 | Seg 0.357147 | Elapsed 2.8m | ETA 1.6m
Epoch 186/500 | Batch 140/202 | Rec 0.000856 | Seg 0.357166 | Elapsed 3.0m | ETA 1.3m
Epoch 186/500 | Batch 150/202 | Rec 0.000856 | Seg 0.357939 | Elapsed 3.2m | ETA 1.1m
Epoch 186/500 | Batch 160/202 | Rec 0.000869 | Seg 0.360517 | Elapsed 3.4m | ETA 0.9m
Epoch 186/500 | Batch 170/202 | Rec 0.000876 | Seg 0.361807 | Elapsed 3.7m | ETA 0.7m
Epoch 186/500 | Batch 180/202 | Rec 0.000869 | Seg 0.361620 | Elapsed 3.9m | ETA 0.5m
Epoch 186/500 | Batch 190/202 | Rec 0.000867 | Seg 0.359716 | Elapsed 4.1m | ETA 0.3m
Epoch 186/500 | Batch 200/202 | Rec 0.000873 | Seg 0.361645 | Elapsed 4.3m | ETA 0.0m
Epoch 186/500 | Batch 202/202 | Rec 0.000875 | Seg 0.362850 | Elapsed 4.3m | ETA 0.0m

2026-09-23 13:55:29,355 - INFO: Rec loss: 0.0008745873215813466
2026-09-23 13:55:29,355 - INFO: Seg loss: 0.3628502276052933
2026-09-23 13:55:29,355 - INFO: λ_rec: 1
2026-09-23 13:55:29,356 - INFO: λ_seg: 0.0001
2026-09-23 13:56:45,756 - INFO: -------------------Epoch: 186------------------------
2026-09-23 13:56:45,760 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  37.80159  0.970543  0.000173
2026-09-23 13:56:45,768 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995110  0.997499  0.996385  0.998716  0.995328
real potato   0.525350  0.688781  0.998064  0.525886  0.999431
fake potato   0.666804  0.800050  0.972714  0.679514  0.999753
real apple    0.711224  0.831196  0.845447  0.817514  0.998855
fake apple    0.812519  0.896514  0.950718  0.848246  0.999261
real orange   0.761287  0.864418  0.999696  0.761464  0.999685
fake orange   0.877597  0.934759  0.895997  0.977135  0.999610
real grape    0.545163  0.705591  0.889222  0.584886  0.998981
fake grape    0.785913  0.880075  0.900444  0.860702  0.999133
real lemon    0.426161  0.597584  0.556052  0.645936  0.998978
fake lemon    0.820171  0.901152  0.963623  0.846376  0.999607
real avocado  0.752385  0.858649  0.769411  0.971429  0.999703
fake avocado  0.798217  0.887738  0.998725  0.799031  0.999758
real pepper   0.796047  0.886394  0.889122  0.883781  0.999172
fake pepper   0.875996  0.933850  0.994790  0.880033  0.999703
real plant    0.836350  0.910833  0.899304  0.922764  0.998194
fake plant    0.779332  0.875933  0.846168  0.907975  0.999795
real banana   0.460764  0.630808  0.937827  0.475282  0.998750
fake banana   0.677203  0.807489  0.819291  0.796118  0.999302
real onion    0.729709  0.843687  0.757559  0.952035  0.999681
fake onion    0.946115  0.972261  0.994437  0.951149  0.999966
real unknown  0.885664  0.939316  0.918796  0.960878  0.999980
fake unknown  0.281430  0.439200  0.320007  0.700109  0.998494
total         0.728109  0.829729  0.874513  0.815085  0.999179
total(-bg)    0.715973  0.822103  0.868973  0.806738  0.999354
2026-09-23 13:56:46,318 - INFO: Epoch accounting: {'epoch': 186, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11319692, 23748, 52176, 122821, 152606, 73354, 66717, 182679, 179902, 87696, 71470, 65921, 33456, 216104, 96310, 157917, 31196, 59243, 78659, 69504, 37879, 10458, 48764], 'crops_with_class': [202, 14, 24, 31, 38, 23, 26, 33, 32, 38, 34, 22, 11, 48, 26, 22, 28, 18, 32, 27, 16, 11, 22], 'targeted_crops_by_class': [0, 1, 7, 4, 4, 6, 7, 7, 2, 7, 7, 8, 2, 6, 4, 2, 2, 4, 2, 3, 0, 3, 7], 'sampled_scene_counts': [1, 0, 1, 1, 1, 2, 0, 1, 0, 2, 1, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 1, 1, 3, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 2, 2, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 3, 1, 1, 2, 0, 0, 0, 2, 3, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 3, 1, 0, 3, 2, 2, 3, 1, 2, 1, 1, 1, 1, 1, 3, 1, 1, 0, 3, 3, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 4, 2, 5, 0, 1, 2, 0, 3, 1, 1, 3, 3, 2, 3, 0, 2, 1, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 5, 1, 2, 2, 1, 0, 1, 1, 0, 1, 1, 0, 3, 1, 1, 3, 0, 1, 0, 0, 1, 0, 0, 1, 1], 'learning_rate': 6.993275104540961e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008745873215813466, 'train_segmentation_loss': 0.3628502276052933, 'val_foreground_miou_all22': 0.7159727038131011, 'val_psnr_ref1': 37.801589813232425, 'elapsed_seconds': 337.63062930107117, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 187/500 | Batch 10/202 | Rec 0.000909 | Seg 0.371638 | Elapsed 0.2m | ETA 4.2m
Epoch 187/500 | Batch 20/202 | Rec 0.000897 | Seg 0.373784 | Elapsed 0.4m | ETA 4.0m
Epoch 187/500 | Batch 30/202 | Rec 0.000921 | Seg 0.364430 | Elapsed 0.7m | ETA 3.8m
Epoch 187/500 | Batch 40/202 | Rec 0.000891 | Seg 0.346883 | Elapsed 0.9m | ETA 3.5m
Epoch 187/500 | Batch 50/202 | Rec 0.000913 | Seg 0.363760 | Elapsed 1.1m | ETA 3.3m
Epoch 187/500 | Batch 60/202 | Rec 0.000937 | Seg 0.377068 | Elapsed 1.3m | ETA 3.1m
Epoch 187/500 | Batch 70/202 | Rec 0.000913 | Seg 0.378168 | Elapsed 1.5m | ETA 2.9m
Epoch 187/500 | Batch 80/202 | Rec 0.000908 | Seg 0.369511 | Elapsed 1.7m | ETA 2.6m
Epoch 187/500 | Batch 90/202 | Rec 0.000905 | Seg 0.369845 | Elapsed 1.9m | ETA 2.4m
Epoch 187/500 | Batch 100/202 | Rec 0.000907 | Seg 0.364156 | Elapsed 2.2m | ETA 2.2m
Epoch 187/500 | Batch 110/202 | Rec 0.000887 | Seg 0.365328 | Elapsed 2.4m | ETA 2.0m
Epoch 187/500 | Batch 120/202 | Rec 0.000875 | Seg 0.357125 | Elapsed 2.6m | ETA 1.8m
Epoch 187/500 | Batch 130/202 | Rec 0.000871 | Seg 0.360458 | Elapsed 2.8m | ETA 1.5m
Epoch 187/500 | Batch 140/202 | Rec 0.000872 | Seg 0.362609 | Elapsed 3.0m | ETA 1.3m
Epoch 187/500 | Batch 150/202 | Rec 0.000866 | Seg 0.360984 | Elapsed 3.2m | ETA 1.1m
Epoch 187/500 | Batch 160/202 | Rec 0.000863 | Seg 0.363167 | Elapsed 3.4m | ETA 0.9m
Epoch 187/500 | Batch 170/202 | Rec 0.000857 | Seg 0.359665 | Elapsed 3.6m | ETA 0.7m
Epoch 187/500 | Batch 180/202 | Rec 0.000860 | Seg 0.358863 | Elapsed 3.9m | ETA 0.5m
Epoch 187/500 | Batch 190/202 | Rec 0.000868 | Seg 0.356384 | Elapsed 4.1m | ETA 0.3m
Epoch 187/500 | Batch 200/202 | Rec 0.000868 | Seg 0.355772 | Elapsed 4.3m | ETA 0.0m
Epoch 187/500 | Batch 202/202 | Rec 0.000866 | Seg 0.355407 | Elapsed 4.3m | ETA 0.0m

2026-09-23 14:01:05,707 - INFO: Rec loss: 0.0008663774857304455
2026-09-23 14:01:05,707 - INFO: Seg loss: 0.3554067469690696
2026-09-23 14:01:05,707 - INFO: λ_rec: 1
2026-09-23 14:01:05,707 - INFO: λ_seg: 0.0001
2026-09-23 14:02:21,937 - INFO: -------------------Epoch: 187------------------------
2026-09-23 14:02:21,941 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.022851  0.971475  0.000165
2026-09-23 14:02:21,948 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995008  0.997448  0.996064  0.998935  0.995229
real potato   0.603110  0.752378  0.999155  0.603417  0.999525
fake potato   0.907949  0.951704  0.981741  0.923544  0.999932
real apple    0.700586  0.823885  0.863606  0.787749  0.998839
fake apple    0.656379  0.792499  0.985752  0.662666  0.998690
real orange   0.783117  0.878319  1.000000  0.783117  0.999714
fake orange   0.842960  0.914740  0.869300  0.965302  0.999485
real grape    0.684534  0.812679  0.913921  0.731711  0.999296
fake grape    0.849614  0.918643  0.934916  0.903024  0.999409
real lemon    0.408609  0.580110  0.511287  0.670475  0.998860
fake lemon    0.820163  0.901147  0.966243  0.844356  0.999608
real avocado  0.785461  0.879791  0.822597  0.945649  0.999760
fake avocado  0.265205  0.419195  0.999519  0.265238  0.999121
real pepper   0.802954  0.890659  0.908905  0.873227  0.999216
fake pepper   0.799545  0.888558  0.984965  0.809423  0.999516
real plant    0.839698  0.912815  0.913325  0.912405  0.998258
fake plant    0.814916  0.897971  0.943424  0.856787  0.999845
real banana   0.479353  0.648013  0.952456  0.491104  0.998801
fake banana   0.652419  0.789603  0.756806  0.825481  0.999191
real onion    0.714229  0.833245  0.763424  0.917244  0.999668
fake onion    0.932886  0.965228  0.990583  0.941233  0.999957
real unknown  0.793930  0.885079  0.829716  0.948473  0.999961
fake unknown  0.175597  0.298701  0.195821  0.629663  0.997509
total         0.709053  0.810105  0.873197  0.795227  0.999104
total(-bg)    0.696055  0.801589  0.867612  0.785968  0.999280
2026-09-23 14:02:22,610 - INFO: Epoch accounting: {'epoch': 187, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11320972, 48187, 64791, 116044, 144284, 89484, 68739, 167629, 202554, 73435, 50976, 41814, 21791, 201311, 125023, 112446, 21459, 84758, 93413, 91228, 52524, 11079, 34331], 'crops_with_class': [202, 28, 29, 30, 34, 30, 26, 30, 36, 31, 23, 16, 9, 52, 33, 20, 21, 26, 32, 36, 23, 15, 20], 'targeted_crops_by_class': [0, 2, 9, 2, 3, 7, 0, 10, 7, 6, 7, 6, 0, 6, 6, 5, 5, 1, 5, 5, 1, 8, 3], 'sampled_scene_counts': [1, 0, 1, 1, 2, 0, 0, 1, 1, 2, 1, 1, 2, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 2, 0, 1, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 3, 1, 0, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 2, 1, 2, 0, 1, 3, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 2, 2, 3, 1, 1, 1, 0, 1, 1, 2, 0, 2, 2, 2, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 6, 5, 0, 1, 0, 2, 2, 1, 1, 2, 0, 1, 1, 0, 2, 2, 2, 1, 2, 0, 1, 3, 1, 1, 1, 2, 1, 2, 4, 2, 1, 3, 2, 1, 2, 1, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 0, 3, 1, 1, 2, 1, 0, 0, 1, 3, 1], 'learning_rate': 6.96447616335054e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008663774857304455, 'train_segmentation_loss': 0.3554067469690696, 'val_foreground_miou_all22': 0.6960551292981155, 'val_psnr_ref1': 38.022851104736326, 'elapsed_seconds': 336.2840805053711, 'peak_cuda_allocated_gib': 7.509586334228516}

Epoch 188/500 | Batch 10/202 | Rec 0.000827 | Seg 0.275540 | Elapsed 0.2m | ETA 4.2m
Epoch 188/500 | Batch 20/202 | Rec 0.000798 | Seg 0.278704 | Elapsed 0.4m | ETA 3.9m
Epoch 188/500 | Batch 30/202 | Rec 0.000767 | Seg 0.298339 | Elapsed 0.6m | ETA 3.7m
Epoch 188/500 | Batch 40/202 | Rec 0.000779 | Seg 0.315688 | Elapsed 0.9m | ETA 3.5m
Epoch 188/500 | Batch 50/202 | Rec 0.000792 | Seg 0.330251 | Elapsed 1.1m | ETA 3.2m
Epoch 188/500 | Batch 60/202 | Rec 0.000770 | Seg 0.317893 | Elapsed 1.3m | ETA 3.0m
Epoch 188/500 | Batch 70/202 | Rec 0.000804 | Seg 0.325224 | Elapsed 1.5m | ETA 2.8m
Epoch 188/500 | Batch 80/202 | Rec 0.000815 | Seg 0.347059 | Elapsed 1.7m | ETA 2.6m
Epoch 188/500 | Batch 90/202 | Rec 0.000851 | Seg 0.360408 | Elapsed 1.9m | ETA 2.4m
Epoch 188/500 | Batch 100/202 | Rec 0.000848 | Seg 0.366475 | Elapsed 2.1m | ETA 2.2m
Epoch 188/500 | Batch 110/202 | Rec 0.000858 | Seg 0.377425 | Elapsed 2.3m | ETA 2.0m
Epoch 188/500 | Batch 120/202 | Rec 0.000878 | Seg 0.379212 | Elapsed 2.6m | ETA 1.7m
Epoch 188/500 | Batch 130/202 | Rec 0.000877 | Seg 0.379444 | Elapsed 2.8m | ETA 1.5m
Epoch 188/500 | Batch 140/202 | Rec 0.000878 | Seg 0.381500 | Elapsed 3.0m | ETA 1.3m
Epoch 188/500 | Batch 150/202 | Rec 0.000877 | Seg 0.384841 | Elapsed 3.2m | ETA 1.1m
Epoch 188/500 | Batch 160/202 | Rec 0.000889 | Seg 0.386254 | Elapsed 3.4m | ETA 0.9m
Epoch 188/500 | Batch 170/202 | Rec 0.000887 | Seg 0.387298 | Elapsed 3.6m | ETA 0.7m
Epoch 188/500 | Batch 180/202 | Rec 0.000891 | Seg 0.384251 | Elapsed 3.8m | ETA 0.5m
Epoch 188/500 | Batch 190/202 | Rec 0.000889 | Seg 0.384666 | Elapsed 4.0m | ETA 0.3m
Epoch 188/500 | Batch 200/202 | Rec 0.000888 | Seg 0.384094 | Elapsed 4.2m | ETA 0.0m
Epoch 188/500 | Batch 202/202 | Rec 0.000887 | Seg 0.383994 | Elapsed 4.3m | ETA 0.0m

2026-09-23 14:06:39,801 - INFO: Rec loss: 0.0008867562720828717
2026-09-23 14:06:39,802 - INFO: Seg loss: 0.38399393825173966
2026-09-23 14:06:39,802 - INFO: λ_rec: 1
2026-09-23 14:06:39,802 - INFO: λ_seg: 0.0001
2026-09-23 14:07:55,905 - INFO: -------------------Epoch: 188------------------------
2026-09-23 14:07:55,908 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.203446  0.969442  0.000198
2026-09-23 14:07:55,915 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994884  0.997385  0.995726  0.999151  0.995109
real potato   0.853408  0.920857  0.994527  0.857434  0.999824
fake potato   0.831001  0.907651  0.996743  0.833263  0.999877
real apple    0.794536  0.885456  0.944514  0.833437  0.999256
fake apple    0.708511  0.829341  0.992011  0.712577  0.998893
real orange   0.837629  0.911592  0.992636  0.842867  0.999785
fake orange   0.894045  0.944009  0.927620  0.961092  0.999674
real grape    0.685922  0.813656  0.905953  0.738508  0.999294
fake grape    0.831467  0.907929  0.921975  0.894403  0.999329
real lemon    0.655068  0.791541  0.706795  0.899507  0.999443
fake lemon    0.837368  0.911437  0.995219  0.840750  0.999655
real avocado  0.773294  0.872106  0.801376  0.956650  0.999739
fake avocado  0.471986  0.641247  0.992254  0.473731  0.999366
real pepper   0.793202  0.884627  0.911322  0.859544  0.999180
fake pepper   0.893177  0.943525  0.983543  0.906728  0.999742
real plant    0.820566  0.901391  0.945266  0.861499  0.998116
fake plant    0.766950  0.868056  0.854016  0.882669  0.999787
real banana   0.625900  0.769864  0.958612  0.643284  0.999136
fake banana   0.691440  0.817525  0.821824  0.813371  0.999332
real onion    0.737681  0.848992  0.765392  0.953217  0.999694
fake onion    0.926104  0.961584  0.991523  0.933495  0.999953
real unknown  0.882819  0.937713  0.920110  0.956107  0.999980
fake unknown  0.212149  0.349998  0.242447  0.629301  0.998031
total         0.761700  0.852934  0.893974  0.838373  0.999226
total(-bg)    0.751101  0.846368  0.889349  0.831065  0.999413
2026-09-23 14:07:56,600 - INFO: Epoch accounting: {'epoch': 188, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11239960, 47760, 59566, 144207, 138350, 96818, 50030, 137742, 187402, 73194, 47087, 35247, 50489, 226746, 124354, 112251, 21038, 118387, 116937, 102969, 52020, 10507, 45211], 'crops_with_class': [202, 31, 28, 33, 39, 28, 22, 28, 35, 30, 22, 13, 16, 54, 34, 18, 18, 38, 39, 40, 28, 16, 20], 'targeted_crops_by_class': [0, 4, 6, 7, 7, 7, 4, 5, 6, 7, 3, 4, 6, 4, 3, 5, 6, 5, 11, 5, 3, 5, 2], 'sampled_scene_counts': [0, 1, 0, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 2, 1, 1, 1, 0, 2, 1, 1, 2, 0, 0, 0, 1, 1, 1, 0, 2, 1, 0, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 4, 2, 2, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 3, 1, 2, 2, 1, 1, 1, 0, 0, 0, 1, 5, 2, 3, 2, 0, 1, 1, 2, 1, 1, 1, 1, 2, 2, 5, 2, 0, 2, 2, 1, 1, 0, 1, 1, 1, 2, 1, 1, 4, 3, 1, 1, 1, 0, 2, 3, 0, 1, 2, 0, 1, 1, 2, 2, 2, 2, 5, 0, 1, 1, 0, 1, 2, 5, 1, 1, 1, 2, 1, 1, 2, 1, 0, 0, 3, 1, 0, 2, 2, 4, 1], 'learning_rate': 6.935600161483506e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008867562720828717, 'train_segmentation_loss': 0.38399393825173966, 'val_foreground_miou_all22': 0.7511010246306207, 'val_psnr_ref1': 37.20344635009766, 'elapsed_seconds': 333.9807872772217, 'peak_cuda_allocated_gib': 7.510265350341797}

Epoch 189/500 | Batch 10/202 | Rec 0.000893 | Seg 0.318002 | Elapsed 0.2m | ETA 4.0m
Epoch 189/500 | Batch 20/202 | Rec 0.000852 | Seg 0.339447 | Elapsed 0.4m | ETA 3.8m
Epoch 189/500 | Batch 30/202 | Rec 0.000856 | Seg 0.367962 | Elapsed 0.6m | ETA 3.6m
Epoch 189/500 | Batch 40/202 | Rec 0.000814 | Seg 0.354245 | Elapsed 0.8m | ETA 3.4m
Epoch 189/500 | Batch 50/202 | Rec 0.000815 | Seg 0.343506 | Elapsed 1.1m | ETA 3.2m
Epoch 189/500 | Batch 60/202 | Rec 0.000824 | Seg 0.334027 | Elapsed 1.3m | ETA 3.0m
Epoch 189/500 | Batch 70/202 | Rec 0.000791 | Seg 0.317700 | Elapsed 1.5m | ETA 2.8m
Epoch 189/500 | Batch 80/202 | Rec 0.000799 | Seg 0.325461 | Elapsed 1.7m | ETA 2.6m
Epoch 189/500 | Batch 90/202 | Rec 0.000821 | Seg 0.342150 | Elapsed 1.9m | ETA 2.4m
Epoch 189/500 | Batch 100/202 | Rec 0.000810 | Seg 0.338360 | Elapsed 2.2m | ETA 2.2m
Epoch 189/500 | Batch 110/202 | Rec 0.000819 | Seg 0.346187 | Elapsed 2.4m | ETA 2.0m
Epoch 189/500 | Batch 120/202 | Rec 0.000817 | Seg 0.349118 | Elapsed 2.6m | ETA 1.8m
Epoch 189/500 | Batch 130/202 | Rec 0.000817 | Seg 0.349484 | Elapsed 2.8m | ETA 1.5m
Epoch 189/500 | Batch 140/202 | Rec 0.000825 | Seg 0.355036 | Elapsed 3.0m | ETA 1.3m
Epoch 189/500 | Batch 150/202 | Rec 0.000825 | Seg 0.353763 | Elapsed 3.2m | ETA 1.1m
Epoch 189/500 | Batch 160/202 | Rec 0.000822 | Seg 0.355124 | Elapsed 3.4m | ETA 0.9m
Epoch 189/500 | Batch 170/202 | Rec 0.000827 | Seg 0.363849 | Elapsed 3.6m | ETA 0.7m
Epoch 189/500 | Batch 180/202 | Rec 0.000839 | Seg 0.361594 | Elapsed 3.9m | ETA 0.5m
Epoch 189/500 | Batch 190/202 | Rec 0.000839 | Seg 0.364583 | Elapsed 4.1m | ETA 0.3m
Epoch 189/500 | Batch 200/202 | Rec 0.000839 | Seg 0.362654 | Elapsed 4.3m | ETA 0.0m
Epoch 189/500 | Batch 202/202 | Rec 0.000837 | Seg 0.361364 | Elapsed 4.3m | ETA 0.0m

2026-09-23 14:12:16,417 - INFO: Rec loss: 0.0008372323821520082
2026-09-23 14:12:16,418 - INFO: Seg loss: 0.36136441379047857
2026-09-23 14:12:16,418 - INFO: λ_rec: 1
2026-09-23 14:12:16,418 - INFO: λ_seg: 0.0001
2026-09-23 14:13:32,550 - INFO: -------------------Epoch: 189------------------------
2026-09-23 14:13:32,554 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.287575  0.970871  0.000194
2026-09-23 14:13:32,561 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995166  0.997527  0.996279  0.998879  0.995381
real potato   0.836053  0.910657  0.990558  0.842770  0.999802
fake potato   0.966887  0.983115  0.987738  0.978634  0.999976
real apple    0.669781  0.802189  0.938018  0.700796  0.998808
fake apple    0.676526  0.807008  0.892266  0.736704  0.998670
real orange   0.577384  0.732031  0.990518  0.580593  0.999440
fake orange   0.791810  0.883761  0.805419  0.979107  0.999263
real grape    0.547356  0.707425  0.889984  0.587079  0.998986
fake grape    0.827044  0.905286  0.948288  0.866106  0.999330
real lemon    0.455896  0.626227  0.522676  0.781096  0.998904
fake lemon    0.794050  0.885154  0.998460  0.795023  0.999564
real avocado  0.817486  0.899529  0.843072  0.964204  0.999800
fake avocado  0.314763  0.478777  0.999191  0.314843  0.999180
real pepper   0.797229  0.887126  0.893539  0.880903  0.999180
fake pepper   0.908721  0.952128  0.977031  0.928558  0.999778
real plant    0.809737  0.894817  0.896848  0.892894  0.997901
fake plant    0.761621  0.864632  0.808064  0.929831  0.999768
real banana   0.464180  0.634003  0.936927  0.479153  0.998757
fake banana   0.750387  0.857346  0.870893  0.844310  0.999483
real onion    0.669359  0.801887  0.685567  0.965884  0.999569
fake onion    0.943039  0.970635  0.976505  0.964933  0.999963
real unknown  0.676610  0.807068  0.700351  0.952290  0.999927
fake unknown  0.236764  0.382838  0.258719  0.736146  0.998000
total         0.708167  0.811790  0.861170  0.813075  0.999106
total(-bg)    0.695122  0.803347  0.855029  0.804630  0.999275
2026-09-23 14:13:33,074 - INFO: Epoch accounting: {'epoch': 189, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11301341, 64292, 57517, 125145, 124831, 73171, 97064, 118442, 216127, 64553, 52754, 54954, 42326, 233506, 118660, 126036, 19874, 85235, 72922, 85820, 46399, 9705, 47598], 'crops_with_class': [202, 37, 24, 35, 32, 22, 33, 23, 36, 32, 24, 17, 18, 54, 31, 16, 19, 24, 31, 40, 25, 14, 23], 'targeted_crops_by_class': [0, 6, 8, 7, 2, 4, 3, 3, 5, 5, 2, 4, 8, 2, 7, 5, 2, 4, 7, 4, 3, 2, 7], 'sampled_scene_counts': [0, 2, 2, 1, 0, 2, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 0, 2, 0, 1, 2, 0, 1, 0, 0, 1, 1, 2, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 2, 2, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 2, 3, 2, 2, 1, 2, 1, 1, 1, 3, 1, 0, 1, 1, 1, 1, 2, 2, 0, 0, 4, 1, 2, 5, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 0, 1, 1, 4, 1, 3, 2, 0, 2, 3, 0, 2, 1, 2, 1, 1, 3, 1, 3, 2, 3, 1, 1, 0, 1, 1, 0, 2, 3, 1, 0, 1, 3, 2, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 3], 'learning_rate': 6.906648238914975e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008372323821520082, 'train_segmentation_loss': 0.36136441379047857, 'val_foreground_miou_all22': 0.6951219091528554, 'val_psnr_ref1': 37.287575225830075, 'elapsed_seconds': 336.4663574695587, 'peak_cuda_allocated_gib': 7.503452301025391}

Epoch 190/500 | Batch 10/202 | Rec 0.000916 | Seg 0.312494 | Elapsed 0.2m | ETA 4.2m
Epoch 190/500 | Batch 20/202 | Rec 0.000905 | Seg 0.311963 | Elapsed 0.4m | ETA 4.0m
Epoch 190/500 | Batch 30/202 | Rec 0.000908 | Seg 0.328076 | Elapsed 0.6m | ETA 3.7m
Epoch 190/500 | Batch 40/202 | Rec 0.000863 | Seg 0.339425 | Elapsed 0.9m | ETA 3.5m
Epoch 190/500 | Batch 50/202 | Rec 0.000849 | Seg 0.337983 | Elapsed 1.1m | ETA 3.3m
Epoch 190/500 | Batch 60/202 | Rec 0.000819 | Seg 0.330475 | Elapsed 1.3m | ETA 3.0m
Epoch 190/500 | Batch 70/202 | Rec 0.000815 | Seg 0.329926 | Elapsed 1.5m | ETA 2.8m
Epoch 190/500 | Batch 80/202 | Rec 0.000812 | Seg 0.334254 | Elapsed 1.7m | ETA 2.6m
Epoch 190/500 | Batch 90/202 | Rec 0.000802 | Seg 0.332946 | Elapsed 1.9m | ETA 2.4m
Epoch 190/500 | Batch 100/202 | Rec 0.000806 | Seg 0.335705 | Elapsed 2.1m | ETA 2.2m
Epoch 190/500 | Batch 110/202 | Rec 0.000833 | Seg 0.344973 | Elapsed 2.3m | ETA 2.0m
Epoch 190/500 | Batch 120/202 | Rec 0.000819 | Seg 0.337761 | Elapsed 2.6m | ETA 1.8m
Epoch 190/500 | Batch 130/202 | Rec 0.000815 | Seg 0.337457 | Elapsed 2.8m | ETA 1.5m
Epoch 190/500 | Batch 140/202 | Rec 0.000812 | Seg 0.333560 | Elapsed 3.0m | ETA 1.3m
Epoch 190/500 | Batch 150/202 | Rec 0.000818 | Seg 0.334713 | Elapsed 3.2m | ETA 1.1m
Epoch 190/500 | Batch 160/202 | Rec 0.000812 | Seg 0.332431 | Elapsed 3.4m | ETA 0.9m
Epoch 190/500 | Batch 170/202 | Rec 0.000814 | Seg 0.336114 | Elapsed 3.6m | ETA 0.7m
Epoch 190/500 | Batch 180/202 | Rec 0.000822 | Seg 0.339241 | Elapsed 3.9m | ETA 0.5m
Epoch 190/500 | Batch 190/202 | Rec 0.000832 | Seg 0.340216 | Elapsed 4.1m | ETA 0.3m
Epoch 190/500 | Batch 200/202 | Rec 0.000835 | Seg 0.343992 | Elapsed 4.3m | ETA 0.0m
Epoch 190/500 | Batch 202/202 | Rec 0.000833 | Seg 0.343864 | Elapsed 4.3m | ETA 0.0m

2026-09-23 14:17:52,886 - INFO: Rec loss: 0.0008329382214676773
2026-09-23 14:17:52,886 - INFO: Seg loss: 0.3438641207274234
2026-09-23 14:17:52,886 - INFO: λ_rec: 1
2026-09-23 14:17:52,886 - INFO: λ_seg: 0.0001
2026-09-23 14:19:09,158 - INFO: -------------------Epoch: 190------------------------
2026-09-23 14:19:09,162 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  37.894762  0.971457  0.00017
2026-09-23 14:19:09,169 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995181  0.997535  0.996588  0.998583  0.995396
real potato   0.768079  0.868780  0.993436  0.771997  0.999721
fake potato   0.487562  0.655474  0.979184  0.492669  0.999623
real apple    0.670082  0.802405  0.925000  0.708580  0.998796
fake apple    0.596684  0.747357  0.989217  0.600590  0.998467
real orange   0.874282  0.932875  0.990376  0.881774  0.999833
fake orange   0.957484  0.978230  0.993135  0.963863  0.999877
real grape    0.564235  0.721370  0.741249  0.702624  0.998867
fake grape    0.823610  0.903224  0.884953  0.922369  0.999269
real lemon    0.379050  0.549678  0.482087  0.639444  0.998769
fake lemon    0.835449  0.910299  0.993517  0.840029  0.999650
real avocado  0.768737  0.869200  0.791875  0.963383  0.999731
fake avocado  0.573973  0.729284  0.995807  0.575363  0.999489
real pepper   0.752429  0.858677  0.871414  0.846404  0.998981
fake pepper   0.845879  0.916456  0.996840  0.848153  0.999632
real plant    0.850910  0.919400  0.926558  0.912451  0.998401
fake plant    0.722231  0.838666  0.776888  0.911235  0.999721
real banana   0.461288  0.631299  0.884794  0.490765  0.998712
fake banana   0.576181  0.731061  0.656628  0.824652  0.998884
real onion    0.786056  0.880165  0.825592  0.942577  0.999768
fake onion    0.921860  0.959292  0.990471  0.930109  0.999950
real unknown  0.731277  0.844734  0.760305  0.950382  0.999944
fake unknown  0.196651  0.328636  0.208162  0.780514  0.997313
total         0.701703  0.807569  0.854525  0.804283  0.999078
total(-bg)    0.688363  0.798934  0.848068  0.795451  0.999245
2026-09-23 14:19:09,660 - INFO: Epoch accounting: {'epoch': 190, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11372451, 37580, 48476, 109230, 141005, 106960, 73529, 124907, 207887, 60100, 60590, 48801, 44969, 196459, 121166, 120108, 23640, 78392, 61066, 83388, 51124, 8248, 58196], 'crops_with_class': [202, 26, 23, 31, 32, 35, 25, 29, 34, 30, 27, 16, 15, 53, 29, 21, 20, 21, 27, 34, 23, 11, 25], 'targeted_crops_by_class': [0, 2, 4, 2, 3, 8, 6, 3, 8, 5, 2, 4, 5, 2, 3, 3, 4, 4, 3, 8, 4, 2, 11], 'sampled_scene_counts': [1, 0, 2, 0, 1, 1, 0, 1, 2, 2, 0, 2, 0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 2, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 1, 0, 2, 2, 2, 0, 1, 1, 0, 0, 1, 2, 3, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 2, 1, 3, 2, 3, 1, 2, 0, 1, 0, 0, 2, 1, 1, 2, 0, 1, 2, 3, 2, 0, 1, 1, 1, 2, 1, 2, 2, 1, 4, 1, 0, 2, 1, 2, 1, 1, 1, 3, 4, 1, 1, 2, 1, 1, 1, 0, 0, 1, 2, 2, 1, 0, 1, 2, 0, 2, 1, 3, 1, 1, 0, 0, 4, 2, 1, 1, 0, 0, 2, 1, 2, 1, 1, 1, 0, 2, 1, 0, 4, 1], 'learning_rate': 6.87762153861727e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008329382214676773, 'train_segmentation_loss': 0.3438641207274234, 'val_foreground_miou_all22': 0.6883631548730463, 'val_psnr_ref1': 37.89476226806641, 'elapsed_seconds': 336.57842898368835, 'peak_cuda_allocated_gib': 7.512729644775391}

Epoch 191/500 | Batch 10/202 | Rec 0.000860 | Seg 0.351934 | Elapsed 0.2m | ETA 4.1m
Epoch 191/500 | Batch 20/202 | Rec 0.000872 | Seg 0.365746 | Elapsed 0.4m | ETA 3.9m
Epoch 191/500 | Batch 30/202 | Rec 0.000865 | Seg 0.386244 | Elapsed 0.6m | ETA 3.7m
Epoch 191/500 | Batch 40/202 | Rec 0.000810 | Seg 0.356386 | Elapsed 0.9m | ETA 3.4m
Epoch 191/500 | Batch 50/202 | Rec 0.000812 | Seg 0.357100 | Elapsed 1.1m | ETA 3.2m
Epoch 191/500 | Batch 60/202 | Rec 0.000779 | Seg 0.345025 | Elapsed 1.3m | ETA 3.0m
Epoch 191/500 | Batch 70/202 | Rec 0.000800 | Seg 0.363149 | Elapsed 1.5m | ETA 2.8m
Epoch 191/500 | Batch 80/202 | Rec 0.000812 | Seg 0.373603 | Elapsed 1.7m | ETA 2.6m
Epoch 191/500 | Batch 90/202 | Rec 0.000805 | Seg 0.370023 | Elapsed 1.9m | ETA 2.4m
Epoch 191/500 | Batch 100/202 | Rec 0.000828 | Seg 0.367091 | Elapsed 2.1m | ETA 2.2m
Epoch 191/500 | Batch 110/202 | Rec 0.000843 | Seg 0.368417 | Elapsed 2.4m | ETA 2.0m
Epoch 191/500 | Batch 120/202 | Rec 0.000850 | Seg 0.364550 | Elapsed 2.6m | ETA 1.8m
Epoch 191/500 | Batch 130/202 | Rec 0.000857 | Seg 0.365789 | Elapsed 2.8m | ETA 1.5m
Epoch 191/500 | Batch 140/202 | Rec 0.000863 | Seg 0.372558 | Elapsed 3.0m | ETA 1.3m
Epoch 191/500 | Batch 150/202 | Rec 0.000864 | Seg 0.371241 | Elapsed 3.2m | ETA 1.1m
Epoch 191/500 | Batch 160/202 | Rec 0.000857 | Seg 0.367478 | Elapsed 3.4m | ETA 0.9m
Epoch 191/500 | Batch 170/202 | Rec 0.000863 | Seg 0.369880 | Elapsed 3.6m | ETA 0.7m
Epoch 191/500 | Batch 180/202 | Rec 0.000858 | Seg 0.369831 | Elapsed 3.8m | ETA 0.5m
Epoch 191/500 | Batch 190/202 | Rec 0.000864 | Seg 0.373712 | Elapsed 4.1m | ETA 0.3m
Epoch 191/500 | Batch 200/202 | Rec 0.000873 | Seg 0.375403 | Elapsed 4.3m | ETA 0.0m
Epoch 191/500 | Batch 202/202 | Rec 0.000875 | Seg 0.375520 | Elapsed 4.3m | ETA 0.0m

2026-09-23 14:23:29,005 - INFO: Rec loss: 0.0008748389521468486
2026-09-23 14:23:29,005 - INFO: Seg loss: 0.3755197922634606
2026-09-23 14:23:29,005 - INFO: λ_rec: 1
2026-09-23 14:23:29,005 - INFO: λ_seg: 0.0001
2026-09-23 14:24:45,068 - INFO: -------------------Epoch: 191------------------------
2026-09-23 14:24:45,072 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.664755  0.970672  0.000178
2026-09-23 14:24:45,079 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994988  0.997438  0.995869  0.999112  0.995209
real potato   0.258065  0.410224  0.999506  0.258097  0.999112
fake potato   0.469384  0.638840  0.954602  0.480101  0.999605
real apple    0.637243  0.778384  0.773086  0.783857  0.998461
fake apple    0.737855  0.849107  0.966084  0.757477  0.998984
real orange   0.520531  0.684624  0.992523  0.522580  0.999366
fake orange   0.791449  0.883536  0.805262  0.978787  0.999262
real grape    0.564177  0.721323  0.849085  0.627055  0.998989
fake grape    0.765447  0.867093  0.855195  0.879429  0.999003
real lemon    0.242250  0.389969  0.351301  0.438328  0.998389
fake lemon    0.843898  0.915292  0.993165  0.848828  0.999668
real avocado  0.741031  0.851206  0.773557  0.946305  0.999693
fake avocado  0.441038  0.612069  0.994550  0.442107  0.999330
real pepper   0.783059  0.878282  0.914028  0.845320  0.999143
fake pepper   0.830182  0.907163  0.978090  0.845913  0.999588
real plant    0.834379  0.909663  0.930024  0.890270  0.998232
fake plant    0.698166  0.822209  0.792705  0.854103  0.999706
real banana   0.037633  0.072528  0.756065  0.038096  0.997811
fake banana   0.418817  0.590328  0.473626  0.783510  0.998000
real onion    0.714131  0.833178  0.782441  0.891066  0.999678
fake onion    0.936195  0.966996  0.968924  0.965175  0.999958
real unknown  0.779859  0.876266  0.810877  0.953244  0.999957
fake unknown  0.184929  0.312097  0.210341  0.604853  0.997754
total         0.618466  0.729035  0.822648  0.723201  0.998908
total(-bg)    0.601351  0.716835  0.814774  0.710659  0.999077
2026-09-23 14:24:45,607 - INFO: Epoch accounting: {'epoch': 191, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11210820, 57362, 72142, 166012, 115586, 85707, 77596, 146763, 239596, 61145, 80634, 19503, 16784, 222138, 83924, 184571, 22292, 73758, 83350, 96938, 80317, 9436, 31898], 'crops_with_class': [202, 32, 31, 39, 30, 29, 28, 30, 44, 27, 28, 7, 7, 57, 28, 23, 20, 21, 38, 42, 32, 12, 16], 'targeted_crops_by_class': [0, 12, 3, 7, 2, 7, 7, 2, 5, 6, 5, 2, 3, 6, 4, 6, 5, 3, 6, 7, 1, 3, 0], 'sampled_scene_counts': [1, 2, 2, 1, 0, 1, 0, 0, 1, 3, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0, 2, 0, 1, 1, 0, 1, 2, 0, 2, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 3, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 1, 0, 2, 2, 1, 2, 4, 3, 1, 3, 1, 1, 0, 0, 2, 2, 2, 0, 1, 0, 0, 1, 1, 1, 3, 1, 0, 2, 1, 1, 0, 1, 1, 2, 1, 0, 3, 1, 2, 3, 2, 0, 1, 0, 0, 1, 1, 1, 3, 2, 0, 4, 1, 0, 2, 4, 1, 0, 3, 2, 1, 1, 2, 2, 0, 1, 2, 2, 1, 0, 2, 0, 2, 1, 2, 3, 1, 1, 4, 1, 2], 'learning_rate': 6.848521206514822e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008748389521468486, 'train_segmentation_loss': 0.3755197922634606, 'val_foreground_miou_all22': 0.6013508524924434, 'val_psnr_ref1': 37.664754943847655, 'elapsed_seconds': 335.94009590148926, 'peak_cuda_allocated_gib': 7.508342742919922}

Epoch 192/500 | Batch 10/202 | Rec 0.000831 | Seg 0.342684 | Elapsed 0.2m | ETA 4.0m
Epoch 192/500 | Batch 20/202 | Rec 0.000883 | Seg 0.378116 | Elapsed 0.4m | ETA 3.8m
Epoch 192/500 | Batch 30/202 | Rec 0.000832 | Seg 0.344254 | Elapsed 0.6m | ETA 3.7m
Epoch 192/500 | Batch 40/202 | Rec 0.000834 | Seg 0.344101 | Elapsed 0.8m | ETA 3.4m
Epoch 192/500 | Batch 50/202 | Rec 0.000896 | Seg 0.341509 | Elapsed 1.1m | ETA 3.2m
Epoch 192/500 | Batch 60/202 | Rec 0.000914 | Seg 0.347321 | Elapsed 1.3m | ETA 3.0m
Epoch 192/500 | Batch 70/202 | Rec 0.000890 | Seg 0.338888 | Elapsed 1.5m | ETA 2.8m
Epoch 192/500 | Batch 80/202 | Rec 0.000894 | Seg 0.350400 | Elapsed 1.7m | ETA 2.6m
Epoch 192/500 | Batch 90/202 | Rec 0.000883 | Seg 0.342746 | Elapsed 1.9m | ETA 2.4m
Epoch 192/500 | Batch 100/202 | Rec 0.000889 | Seg 0.352124 | Elapsed 2.1m | ETA 2.2m
Epoch 192/500 | Batch 110/202 | Rec 0.000879 | Seg 0.351592 | Elapsed 2.4m | ETA 2.0m
Epoch 192/500 | Batch 120/202 | Rec 0.000901 | Seg 0.353535 | Elapsed 2.6m | ETA 1.8m
Epoch 192/500 | Batch 130/202 | Rec 0.000896 | Seg 0.356000 | Elapsed 2.8m | ETA 1.5m
Epoch 192/500 | Batch 140/202 | Rec 0.000913 | Seg 0.362923 | Elapsed 3.0m | ETA 1.3m
Epoch 192/500 | Batch 150/202 | Rec 0.000903 | Seg 0.357297 | Elapsed 3.2m | ETA 1.1m
Epoch 192/500 | Batch 160/202 | Rec 0.000913 | Seg 0.363930 | Elapsed 3.4m | ETA 0.9m
Epoch 192/500 | Batch 170/202 | Rec 0.000912 | Seg 0.365632 | Elapsed 3.7m | ETA 0.7m
Epoch 192/500 | Batch 180/202 | Rec 0.000910 | Seg 0.367625 | Elapsed 3.9m | ETA 0.5m
Epoch 192/500 | Batch 190/202 | Rec 0.000901 | Seg 0.363650 | Elapsed 4.1m | ETA 0.3m
Epoch 192/500 | Batch 200/202 | Rec 0.000903 | Seg 0.360858 | Elapsed 4.3m | ETA 0.0m
Epoch 192/500 | Batch 202/202 | Rec 0.000898 | Seg 0.359231 | Elapsed 4.3m | ETA 0.0m

2026-09-23 14:29:06,360 - INFO: Rec loss: 0.0008984844744641168
2026-09-23 14:29:06,360 - INFO: Seg loss: 0.3592306479516596
2026-09-23 14:29:06,360 - INFO: λ_rec: 1
2026-09-23 14:29:06,360 - INFO: λ_seg: 0.0001
2026-09-23 14:30:22,413 - INFO: -------------------Epoch: 192------------------------
2026-09-23 14:30:22,416 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.691706  0.970631  0.000177
2026-09-23 14:30:22,423 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995094  0.997491  0.996629  0.998455  0.995314
real potato   0.130451  0.230775  1.000000  0.130451  0.998960
fake potato   0.120217  0.214613  0.984589  0.120444  0.999358
real apple    0.580638  0.734638  0.701105  0.771650  0.998077
fake apple    0.793734  0.884958  0.981586  0.805731  0.999209
real orange   0.808151  0.893848  0.999857  0.808245  0.999747
fake orange   0.889850  0.941665  0.909651  0.976122  0.999654
real grape    0.338448  0.505689  0.795266  0.370752  0.998487
fake grape    0.747113  0.855204  0.833634  0.878027  0.998901
real lemon    0.295136  0.455718  0.329474  0.739029  0.997926
fake lemon    0.841843  0.914081  0.985167  0.852651  0.999661
real avocado  0.770722  0.870467  0.825530  0.920690  0.999745
fake avocado  0.672015  0.803790  0.964649  0.688982  0.999598
real pepper   0.796003  0.886366  0.943706  0.835683  0.999217
fake pepper   0.894791  0.944425  0.996941  0.897254  0.999749
real plant    0.801754  0.889921  0.848629  0.935547  0.997686
fake plant    0.818535  0.900164  0.874120  0.927914  0.999836
real banana   0.061399  0.115683  0.905473  0.061795  0.997877
fake banana   0.621434  0.766474  0.741643  0.793132  0.999111
real onion    0.586588  0.739384  0.774205  0.707651  0.999549
fake onion    0.916344  0.956296  0.999736  0.916566  0.999947
real unknown  0.538259  0.699782  0.546331  0.973282  0.999866
fake unknown  0.233877  0.379056  0.249118  0.792648  0.997812
total         0.619669  0.720891  0.834219  0.734900  0.998926
total(-bg)    0.602605  0.708318  0.826837  0.722920  0.999090
2026-09-23 14:30:22,916 - INFO: Epoch accounting: {'epoch': 192, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11251830, 28855, 50701, 126784, 171861, 78674, 83406, 152473, 259597, 83693, 75665, 51597, 24865, 207035, 132231, 167999, 30332, 42282, 62536, 64889, 58729, 5322, 26916], 'crops_with_class': [202, 17, 27, 35, 40, 24, 28, 26, 45, 36, 32, 18, 11, 50, 29, 27, 26, 17, 22, 30, 24, 7, 11], 'targeted_crops_by_class': [0, 1, 6, 3, 5, 3, 7, 6, 4, 3, 5, 6, 2, 5, 8, 7, 6, 4, 4, 1, 3, 4, 2], 'sampled_scene_counts': [1, 0, 2, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 1, 2, 1, 0, 0, 3, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 3, 0, 1, 1, 0, 0, 2, 2, 0, 1, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 2, 2, 1, 3, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 2, 2, 1, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 1, 2, 3, 1, 2, 1, 1, 1, 2, 5, 2, 1, 2, 1, 3, 2, 3, 2, 0, 1, 1, 3, 1, 1, 4, 1, 1, 0, 3, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 3, 2, 0, 2, 0, 1, 3, 3, 2, 1, 0, 0, 1, 1, 5, 2, 1, 1, 2, 0, 1, 1, 3, 2, 2, 0, 2, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 3, 0, 1], 'learning_rate': 6.819348391438913e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008984844744641168, 'train_segmentation_loss': 0.3592306479516596, 'val_foreground_miou_all22': 0.6026046312226039, 'val_psnr_ref1': 37.69170623779297, 'elapsed_seconds': 337.30140018463135, 'peak_cuda_allocated_gib': 7.511051177978516}

Epoch 193/500 | Batch 10/202 | Rec 0.000859 | Seg 0.356138 | Elapsed 0.2m | ETA 4.2m
Epoch 193/500 | Batch 20/202 | Rec 0.000951 | Seg 0.365789 | Elapsed 0.4m | ETA 4.0m
Epoch 193/500 | Batch 30/202 | Rec 0.000900 | Seg 0.344199 | Elapsed 0.7m | ETA 3.7m
Epoch 193/500 | Batch 40/202 | Rec 0.000922 | Seg 0.356309 | Elapsed 0.9m | ETA 3.5m
Epoch 193/500 | Batch 50/202 | Rec 0.000971 | Seg 0.374209 | Elapsed 1.1m | ETA 3.3m
Epoch 193/500 | Batch 60/202 | Rec 0.000918 | Seg 0.355783 | Elapsed 1.3m | ETA 3.1m
Epoch 193/500 | Batch 70/202 | Rec 0.000908 | Seg 0.361766 | Elapsed 1.5m | ETA 2.9m
Epoch 193/500 | Batch 80/202 | Rec 0.000896 | Seg 0.360582 | Elapsed 1.7m | ETA 2.6m
Epoch 193/500 | Batch 90/202 | Rec 0.000897 | Seg 0.370741 | Elapsed 1.9m | ETA 2.4m
Epoch 193/500 | Batch 100/202 | Rec 0.000889 | Seg 0.364993 | Elapsed 2.2m | ETA 2.2m
Epoch 193/500 | Batch 110/202 | Rec 0.000897 | Seg 0.371005 | Elapsed 2.4m | ETA 2.0m
Epoch 193/500 | Batch 120/202 | Rec 0.000890 | Seg 0.369404 | Elapsed 2.6m | ETA 1.8m
Epoch 193/500 | Batch 130/202 | Rec 0.000884 | Seg 0.367453 | Elapsed 2.8m | ETA 1.6m
Epoch 193/500 | Batch 140/202 | Rec 0.000880 | Seg 0.370721 | Elapsed 3.0m | ETA 1.3m
Epoch 193/500 | Batch 150/202 | Rec 0.000871 | Seg 0.370897 | Elapsed 3.2m | ETA 1.1m
Epoch 193/500 | Batch 160/202 | Rec 0.000870 | Seg 0.371072 | Elapsed 3.4m | ETA 0.9m
Epoch 193/500 | Batch 170/202 | Rec 0.000898 | Seg 0.374807 | Elapsed 3.6m | ETA 0.7m
Epoch 193/500 | Batch 180/202 | Rec 0.000895 | Seg 0.374468 | Elapsed 3.9m | ETA 0.5m
Epoch 193/500 | Batch 190/202 | Rec 0.000891 | Seg 0.375390 | Elapsed 4.1m | ETA 0.3m
Epoch 193/500 | Batch 200/202 | Rec 0.000886 | Seg 0.373814 | Elapsed 4.3m | ETA 0.0m
Epoch 193/500 | Batch 202/202 | Rec 0.000886 | Seg 0.373862 | Elapsed 4.3m | ETA 0.0m

2026-09-23 14:34:42,159 - INFO: Rec loss: 0.0008856732267736559
2026-09-23 14:34:42,159 - INFO: Seg loss: 0.37386230796132935
2026-09-23 14:34:42,159 - INFO: λ_rec: 1
2026-09-23 14:34:42,159 - INFO: λ_seg: 0.0001
2026-09-23 14:35:58,472 - INFO: -------------------Epoch: 193------------------------
2026-09-23 14:35:58,476 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.764218  0.970373  0.000173
2026-09-23 14:35:58,483 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995435  0.997662  0.996746  0.998680  0.995640
real potato   0.508276  0.673938  0.997003  0.509054  0.999411
fake potato   0.961372  0.980255  0.985808  0.974864  0.999971
real apple    0.688860  0.815720  0.777515  0.857983  0.998663
fake apple    0.657704  0.793464  0.993917  0.660362  0.998702
real orange   0.632637  0.774940  0.978626  0.641501  0.999509
fake orange   0.814518  0.897729  0.824321  0.985609  0.999357
real grape    0.630005  0.772960  0.850698  0.708324  0.999131
fake grape    0.855934  0.922325  0.927006  0.917791  0.999429
real lemon    0.328120  0.494062  0.479760  0.509348  0.998774
fake lemon    0.837863  0.911730  0.978106  0.853877  0.999650
real avocado  0.778859  0.875634  0.814993  0.946141  0.999750
fake avocado  0.435047  0.606275  0.983963  0.438154  0.999319
real pepper   0.811482  0.895882  0.908950  0.883280  0.999249
fake pepper   0.921354  0.959017  0.965003  0.953204  0.999806
real plant    0.844933  0.915900  0.923412  0.908607  0.998332
fake plant    0.723746  0.839687  0.775451  0.915644  0.999722
real banana   0.480927  0.649449  0.926513  0.500000  0.998787
fake banana   0.558336  0.716530  0.627705  0.834771  0.998785
real onion    0.538305  0.699818  0.730529  0.671677  0.999480
fake onion    0.946730  0.972586  0.982720  0.962757  0.999966
real unknown  0.923664  0.960267  1.000000  0.923664  0.999988
fake unknown  0.238871  0.385586  0.267894  0.687975  0.998153
total         0.700564  0.804844  0.856376  0.793186  0.999112
total(-bg)    0.687161  0.796080  0.849995  0.783845  0.999270
2026-09-23 14:35:58,986 - INFO: Epoch accounting: {'epoch': 193, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11207625, 58885, 80334, 118393, 169339, 68580, 86425, 149808, 225294, 78628, 65587, 37910, 26111, 212803, 138250, 139129, 18503, 102318, 81570, 72290, 60572, 5245, 34673], 'crops_with_class': [202, 34, 36, 37, 35, 20, 30, 29, 36, 37, 26, 14, 11, 54, 41, 19, 18, 31, 34, 35, 27, 8, 15], 'targeted_crops_by_class': [0, 7, 6, 4, 7, 2, 7, 5, 3, 3, 4, 6, 2, 7, 5, 4, 2, 11, 1, 5, 2, 3, 6], 'sampled_scene_counts': [1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 4, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 3, 0, 1, 2, 2, 1, 2, 4, 2, 2, 3, 3, 1, 0, 2, 1, 0, 3, 1, 2, 1, 1, 1, 3, 0, 1, 2, 0, 2, 1, 1, 2, 1, 1, 2, 3, 0, 3, 0, 1, 0, 0, 1, 2, 3, 0, 2, 0, 2, 0, 1, 3, 5, 2, 3, 1, 1, 2, 0, 0, 2, 2, 4, 1, 1, 4, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 2, 3, 1], 'learning_rate': 6.790104245082328e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008856732267736559, 'train_segmentation_loss': 0.37386230796132935, 'val_foreground_miou_all22': 0.6871610111844411, 'val_psnr_ref1': 37.764218444824216, 'elapsed_seconds': 336.06158661842346, 'peak_cuda_allocated_gib': 7.5048065185546875}

Epoch 194/500 | Batch 10/202 | Rec 0.000822 | Seg 0.301030 | Elapsed 0.2m | ETA 4.1m
Epoch 194/500 | Batch 20/202 | Rec 0.000887 | Seg 0.358998 | Elapsed 0.4m | ETA 3.9m
Epoch 194/500 | Batch 30/202 | Rec 0.000832 | Seg 0.348863 | Elapsed 0.6m | ETA 3.7m
Epoch 194/500 | Batch 40/202 | Rec 0.000780 | Seg 0.325928 | Elapsed 0.9m | ETA 3.5m
Epoch 194/500 | Batch 50/202 | Rec 0.000772 | Seg 0.325088 | Elapsed 1.1m | ETA 3.3m
Epoch 194/500 | Batch 60/202 | Rec 0.000787 | Seg 0.338721 | Elapsed 1.3m | ETA 3.1m
Epoch 194/500 | Batch 70/202 | Rec 0.000839 | Seg 0.347310 | Elapsed 1.5m | ETA 2.8m
Epoch 194/500 | Batch 80/202 | Rec 0.000843 | Seg 0.346189 | Elapsed 1.7m | ETA 2.6m
Epoch 194/500 | Batch 90/202 | Rec 0.000837 | Seg 0.345141 | Elapsed 1.9m | ETA 2.4m
Epoch 194/500 | Batch 100/202 | Rec 0.000834 | Seg 0.345483 | Elapsed 2.2m | ETA 2.2m
Epoch 194/500 | Batch 110/202 | Rec 0.000840 | Seg 0.349787 | Elapsed 2.4m | ETA 2.0m
Epoch 194/500 | Batch 120/202 | Rec 0.000871 | Seg 0.351067 | Elapsed 2.6m | ETA 1.8m
Epoch 194/500 | Batch 130/202 | Rec 0.000849 | Seg 0.345435 | Elapsed 2.8m | ETA 1.6m
Epoch 194/500 | Batch 140/202 | Rec 0.000852 | Seg 0.355291 | Elapsed 3.0m | ETA 1.3m
Epoch 194/500 | Batch 150/202 | Rec 0.000854 | Seg 0.350460 | Elapsed 3.2m | ETA 1.1m
Epoch 194/500 | Batch 160/202 | Rec 0.000854 | Seg 0.352189 | Elapsed 3.5m | ETA 0.9m
Epoch 194/500 | Batch 170/202 | Rec 0.000850 | Seg 0.349536 | Elapsed 3.7m | ETA 0.7m
Epoch 194/500 | Batch 180/202 | Rec 0.000850 | Seg 0.349697 | Elapsed 3.9m | ETA 0.5m
Epoch 194/500 | Batch 190/202 | Rec 0.000859 | Seg 0.357565 | Elapsed 4.1m | ETA 0.3m
Epoch 194/500 | Batch 200/202 | Rec 0.000862 | Seg 0.361201 | Elapsed 4.3m | ETA 0.0m
Epoch 194/500 | Batch 202/202 | Rec 0.000873 | Seg 0.362148 | Elapsed 4.4m | ETA 0.0m

2026-09-23 14:40:20,112 - INFO: Rec loss: 0.0008731146739556058
2026-09-23 14:40:20,112 - INFO: Seg loss: 0.362147829836548
2026-09-23 14:40:20,112 - INFO: λ_rec: 1
2026-09-23 14:40:20,112 - INFO: λ_seg: 0.0001
2026-09-23 14:41:36,421 - INFO: -------------------Epoch: 194------------------------
2026-09-23 14:41:36,425 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.707007  0.971004  0.000177
2026-09-23 14:41:36,431 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994840  0.997363  0.995707  0.999126  0.995066
real potato   0.318669  0.483282  1.000000  0.318669  0.999185
fake potato   0.604976  0.753828  0.970637  0.616255  0.999707
real apple    0.684142  0.812402  0.768073  0.862273  0.998627
fake apple    0.640937  0.781136  0.988736  0.645651  0.998634
real orange   0.770058  0.870044  0.997903  0.771306  0.999697
fake orange   0.871350  0.931203  0.897956  0.967114  0.999591
real grape    0.721947  0.838475  0.941878  0.755609  0.999392
fake grape    0.853466  0.920891  0.932586  0.909582  0.999422
real lemon    0.446135  0.616954  0.527778  0.742534  0.998917
fake lemon    0.818751  0.900295  0.998069  0.820050  0.999616
real avocado  0.786872  0.880676  0.827795  0.940887  0.999763
fake avocado  0.541954  0.702898  1.000000  0.541954  0.999452
real pepper   0.822312  0.902443  0.925814  0.880319  0.999304
fake pepper   0.809902  0.894918  0.964775  0.834582  0.999533
real plant    0.843025  0.914778  0.946675  0.885053  0.998352
fake plant    0.755008  0.860354  0.909266  0.816526  0.999789
real banana   0.338068  0.505269  0.974956  0.341029  0.998500
fake banana   0.542841  0.703641  0.635846  0.787741  0.998780
real onion    0.655310  0.791717  0.781414  0.802398  0.999619
fake onion    0.931628  0.964554  0.987833  0.942443  0.999956
real unknown  0.934160  0.965910  1.000000  0.934160  0.999989
fake unknown  0.205127  0.340388  0.223028  0.718761  0.997653
total         0.690934  0.797105  0.878118  0.775392  0.999067
total(-bg)    0.677120  0.788003  0.872774  0.765223  0.999249
2026-09-23 14:41:36,941 - INFO: Epoch accounting: {'epoch': 194, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11260537, 51623, 55248, 135713, 206962, 90083, 65289, 162451, 189749, 60037, 53560, 36853, 36473, 206730, 88226, 168596, 27164, 76222, 76107, 96842, 41749, 6227, 45831], 'crops_with_class': [202, 24, 24, 35, 48, 27, 22, 27, 37, 25, 24, 11, 14, 52, 24, 22, 25, 23, 29, 37, 20, 8, 19], 'targeted_crops_by_class': [0, 3, 3, 1, 5, 7, 5, 3, 4, 2, 1, 4, 7, 6, 3, 5, 6, 5, 3, 4, 4, 3, 4], 'sampled_scene_counts': [1, 1, 1, 0, 0, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 3, 1, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 3, 0, 3, 0, 0, 3, 0, 0, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 4, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 0, 1, 2, 3, 4, 2, 1, 1, 1, 3, 1, 0, 0, 2, 2, 1, 1, 1, 1, 1, 0, 2, 1, 3, 1, 0, 2, 2, 0, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 3, 2, 0, 1, 2, 1, 0, 0, 3, 1, 0, 2, 1, 1, 3, 1, 1, 2, 1, 1, 0, 3, 2, 1, 2, 1, 1, 0, 1, 1, 2, 1, 1], 'learning_rate': 6.760789921953895e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008731146739556058, 'train_segmentation_loss': 0.362147829836548, 'val_foreground_miou_all22': 0.6771199452259148, 'val_psnr_ref1': 37.707007293701174, 'elapsed_seconds': 337.94668912887573, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 195/500 | Batch 10/202 | Rec 0.000865 | Seg 0.426573 | Elapsed 0.2m | ETA 4.2m
Epoch 195/500 | Batch 20/202 | Rec 0.000853 | Seg 0.378385 | Elapsed 0.4m | ETA 4.0m
Epoch 195/500 | Batch 30/202 | Rec 0.000892 | Seg 0.368817 | Elapsed 0.6m | ETA 3.7m
Epoch 195/500 | Batch 40/202 | Rec 0.000914 | Seg 0.369777 | Elapsed 0.9m | ETA 3.5m
Epoch 195/500 | Batch 50/202 | Rec 0.000949 | Seg 0.378111 | Elapsed 1.1m | ETA 3.3m
Epoch 195/500 | Batch 60/202 | Rec 0.000923 | Seg 0.362515 | Elapsed 1.3m | ETA 3.0m
Epoch 195/500 | Batch 70/202 | Rec 0.000907 | Seg 0.364740 | Elapsed 1.5m | ETA 2.8m
Epoch 195/500 | Batch 80/202 | Rec 0.000882 | Seg 0.354010 | Elapsed 1.7m | ETA 2.6m
Epoch 195/500 | Batch 90/202 | Rec 0.000892 | Seg 0.367109 | Elapsed 1.9m | ETA 2.4m
Epoch 195/500 | Batch 100/202 | Rec 0.000879 | Seg 0.359872 | Elapsed 2.1m | ETA 2.2m
Epoch 195/500 | Batch 110/202 | Rec 0.000881 | Seg 0.363209 | Elapsed 2.4m | ETA 2.0m
Epoch 195/500 | Batch 120/202 | Rec 0.000885 | Seg 0.359669 | Elapsed 2.6m | ETA 1.8m
Epoch 195/500 | Batch 130/202 | Rec 0.000898 | Seg 0.360260 | Elapsed 2.8m | ETA 1.5m
Epoch 195/500 | Batch 140/202 | Rec 0.000889 | Seg 0.359076 | Elapsed 3.0m | ETA 1.3m
Epoch 195/500 | Batch 150/202 | Rec 0.000874 | Seg 0.351933 | Elapsed 3.2m | ETA 1.1m
Epoch 195/500 | Batch 160/202 | Rec 0.000864 | Seg 0.349667 | Elapsed 3.4m | ETA 0.9m
Epoch 195/500 | Batch 170/202 | Rec 0.000858 | Seg 0.349853 | Elapsed 3.7m | ETA 0.7m
Epoch 195/500 | Batch 180/202 | Rec 0.000861 | Seg 0.348884 | Elapsed 3.9m | ETA 0.5m
Epoch 195/500 | Batch 190/202 | Rec 0.000859 | Seg 0.348966 | Elapsed 4.1m | ETA 0.3m
Epoch 195/500 | Batch 200/202 | Rec 0.000861 | Seg 0.350748 | Elapsed 4.3m | ETA 0.0m
Epoch 195/500 | Batch 202/202 | Rec 0.000860 | Seg 0.350034 | Elapsed 4.3m | ETA 0.0m

2026-09-23 14:45:57,668 - INFO: Rec loss: 0.0008602855517586582
2026-09-23 14:45:57,668 - INFO: Seg loss: 0.3500342934512266
2026-09-23 14:45:57,668 - INFO: λ_rec: 1
2026-09-23 14:45:57,668 - INFO: λ_seg: 0.0001
2026-09-23 14:47:13,857 - INFO: -------------------Epoch: 195------------------------
2026-09-23 14:47:13,861 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.590279  0.971071  0.000181
2026-09-23 14:47:13,869 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995174  0.997531  0.996302  0.998864  0.995389
real potato   0.769680  0.869803  0.994423  0.773017  0.999723
fake potato   0.935987  0.966885  0.978550  0.955593  0.999952
real apple    0.741170  0.851297  0.928389  0.786112  0.999053
fake apple    0.646537  0.785281  0.970728  0.659392  0.998639
real orange   0.888953  0.941162  0.991919  0.895438  0.999853
fake orange   0.918144  0.957276  0.938550  0.976868  0.999751
real grape    0.602708  0.752063  0.879390  0.657020  0.999096
fake grape    0.851316  0.919638  0.928601  0.910943  0.999411
real lemon    0.473870  0.642980  0.537295  0.800571  0.998955
fake lemon    0.842302  0.914352  0.995415  0.845582  0.999665
real avocado  0.784157  0.878973  0.817245  0.950903  0.999757
fake avocado  0.620808  0.766001  0.999795  0.620888  0.999546
real pepper   0.840812  0.913473  0.938884  0.889496  0.999384
fake pepper   0.917734  0.957053  0.979688  0.935535  0.999800
real plant    0.829796  0.906932  0.911489  0.902520  0.998148
fake plant    0.753310  0.859251  0.836449  0.883436  0.999770
real banana   0.450595  0.621212  0.945331  0.462651  0.998732
fake banana   0.658748  0.794221  0.759304  0.832614  0.999207
real onion    0.714827  0.833653  0.739699  0.955075  0.999656
fake onion    0.955110  0.976990  0.986923  0.967352  0.999971
real unknown  0.691937  0.817874  0.713575  0.958015  0.999932
fake unknown  0.242902  0.390822  0.274221  0.680188  0.998214
total         0.744634  0.839771  0.871398  0.839047  0.999200
total(-bg)    0.733246  0.832600  0.865721  0.831782  0.999373
2026-09-23 14:47:14,368 - INFO: Epoch accounting: {'epoch': 195, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11308804, 48892, 50991, 117770, 143651, 75420, 43243, 120427, 159100, 75080, 58655, 36323, 50661, 257377, 149183, 157565, 21657, 92553, 58538, 106233, 47690, 11222, 47237], 'crops_with_class': [202, 31, 27, 32, 39, 21, 14, 21, 35, 28, 24, 12, 19, 62, 33, 20, 18, 23, 29, 41, 22, 12, 18], 'targeted_crops_by_class': [0, 5, 2, 3, 3, 6, 2, 3, 3, 3, 4, 1, 5, 5, 5, 6, 3, 4, 6, 5, 6, 5, 8], 'sampled_scene_counts': [0, 1, 0, 1, 1, 0, 2, 2, 0, 1, 0, 2, 1, 0, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 3, 0, 1, 0, 1, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 2, 0, 1, 2, 0, 0, 1, 2, 3, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 2, 2, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 3, 0, 2, 1, 3, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 3, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 0, 4, 4, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 0, 2, 4, 2, 1, 1, 1, 0, 1, 1, 0, 3, 2, 0, 3, 2, 4, 2, 2, 1, 2, 0, 4, 0, 1, 0, 1, 0, 0], 'learning_rate': 6.731406579332896e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008602855517586582, 'train_segmentation_loss': 0.3500342934512266, 'val_foreground_miou_all22': 0.7332457344619082, 'val_psnr_ref1': 37.59027938842773, 'elapsed_seconds': 337.41969656944275, 'peak_cuda_allocated_gib': 7.510684967041016}

Epoch 196/500 | Batch 10/202 | Rec 0.000765 | Seg 0.326301 | Elapsed 0.2m | ETA 4.2m
Epoch 196/500 | Batch 20/202 | Rec 0.000911 | Seg 0.341127 | Elapsed 0.4m | ETA 4.0m
Epoch 196/500 | Batch 30/202 | Rec 0.000869 | Seg 0.340470 | Elapsed 0.7m | ETA 3.8m
Epoch 196/500 | Batch 40/202 | Rec 0.000904 | Seg 0.377947 | Elapsed 0.9m | ETA 3.5m
Epoch 196/500 | Batch 50/202 | Rec 0.000877 | Seg 0.376630 | Elapsed 1.1m | ETA 3.3m
Epoch 196/500 | Batch 60/202 | Rec 0.000891 | Seg 0.376562 | Elapsed 1.3m | ETA 3.1m
Epoch 196/500 | Batch 70/202 | Rec 0.000859 | Seg 0.362420 | Elapsed 1.5m | ETA 2.8m
Epoch 196/500 | Batch 80/202 | Rec 0.000852 | Seg 0.360886 | Elapsed 1.7m | ETA 2.6m
Epoch 196/500 | Batch 90/202 | Rec 0.000836 | Seg 0.357287 | Elapsed 1.9m | ETA 2.4m
Epoch 196/500 | Batch 100/202 | Rec 0.000839 | Seg 0.364180 | Elapsed 2.1m | ETA 2.2m
Epoch 196/500 | Batch 110/202 | Rec 0.000821 | Seg 0.358131 | Elapsed 2.4m | ETA 2.0m
Epoch 196/500 | Batch 120/202 | Rec 0.000821 | Seg 0.356399 | Elapsed 2.6m | ETA 1.8m
Epoch 196/500 | Batch 130/202 | Rec 0.000810 | Seg 0.352663 | Elapsed 2.8m | ETA 1.5m
Epoch 196/500 | Batch 140/202 | Rec 0.000810 | Seg 0.355168 | Elapsed 3.0m | ETA 1.3m
Epoch 196/500 | Batch 150/202 | Rec 0.000828 | Seg 0.363154 | Elapsed 3.2m | ETA 1.1m
Epoch 196/500 | Batch 160/202 | Rec 0.000836 | Seg 0.364481 | Elapsed 3.4m | ETA 0.9m
Epoch 196/500 | Batch 170/202 | Rec 0.000843 | Seg 0.364719 | Elapsed 3.7m | ETA 0.7m
Epoch 196/500 | Batch 180/202 | Rec 0.000840 | Seg 0.364607 | Elapsed 3.9m | ETA 0.5m
Epoch 196/500 | Batch 190/202 | Rec 0.000841 | Seg 0.363954 | Elapsed 4.1m | ETA 0.3m
Epoch 196/500 | Batch 200/202 | Rec 0.000839 | Seg 0.358419 | Elapsed 4.3m | ETA 0.0m
Epoch 196/500 | Batch 202/202 | Rec 0.000838 | Seg 0.359184 | Elapsed 4.4m | ETA 0.0m

2026-09-23 14:51:35,387 - INFO: Rec loss: 0.0008383284662654254
2026-09-23 14:51:35,387 - INFO: Seg loss: 0.3591838078481136
2026-09-23 14:51:35,387 - INFO: λ_rec: 1
2026-09-23 14:51:35,387 - INFO: λ_seg: 0.0001
2026-09-23 14:52:51,660 - INFO: -------------------Epoch: 196------------------------
2026-09-23 14:52:51,664 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  37.883087  0.971375  0.00017
2026-09-23 14:52:51,671 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994885  0.997386  0.996068  0.998808  0.995111
real potato   0.940103  0.969077  0.986140  0.952691  0.999927
fake potato   0.943768  0.971020  0.968340  0.973816  0.999958
real apple    0.536417  0.698225  0.984310  0.541044  0.998387
fake apple    0.562500  0.719954  0.987048  0.566683  0.998336
real orange   0.808344  0.893966  0.962478  0.834646  0.999739
fake orange   0.898334  0.946395  0.927719  0.965942  0.999687
real grape    0.475534  0.644509  0.614026  0.678287  0.998438
fake grape    0.845079  0.915986  0.942727  0.890814  0.999396
real lemon    0.380550  0.551253  0.521036  0.585303  0.998880
fake lemon    0.819345  0.900654  0.995547  0.822358  0.999616
real avocado  0.832366  0.908465  0.898379  0.918883  0.999828
fake avocado  0.386115  0.557078  0.997368  0.386509  0.999265
real pepper   0.771107  0.870713  0.834928  0.909811  0.999012
fake pepper   0.843434  0.915018  0.986169  0.853530  0.999622
real plant    0.828485  0.906148  0.919533  0.893245  0.998150
fake plant    0.822811  0.902744  0.889033  0.916986  0.999843
real banana   0.514728  0.679585  0.938180  0.532799  0.998871
fake banana   0.630945  0.773667  0.746205  0.803334  0.999136
real onion    0.791811  0.883761  0.813993  0.966729  0.999770
fake onion    0.933110  0.965348  0.990835  0.941233  0.999957
real unknown  0.506726  0.672574  0.514676  0.970420  0.999849
fake unknown  0.196561  0.328510  0.207490  0.788664  0.997284
total         0.707089  0.807480  0.853140  0.812719  0.999046
total(-bg)    0.694008  0.798848  0.846644  0.804260  0.999225
2026-09-23 14:52:52,182 - INFO: Epoch accounting: {'epoch': 196, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11337908, 47599, 59807, 156642, 137203, 71619, 71872, 132360, 198541, 77089, 56346, 51469, 34825, 203456, 116247, 176911, 34339, 44877, 54468, 67725, 55056, 11936, 39977], 'crops_with_class': [202, 27, 23, 36, 35, 27, 26, 25, 36, 38, 30, 15, 15, 50, 29, 24, 31, 15, 21, 27, 24, 11, 19], 'targeted_crops_by_class': [0, 5, 6, 6, 7, 5, 3, 4, 3, 6, 4, 6, 4, 3, 6, 2, 6, 2, 0, 3, 2, 5, 5], 'sampled_scene_counts': [0, 1, 2, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 2, 0, 2, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 3, 2, 0, 1, 2, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 2, 0, 1, 1, 2, 2, 0, 0, 1, 1, 0, 2, 0, 2, 1, 0, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 2, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 2, 2, 1, 0, 0, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 3, 3, 2, 1, 0, 2, 0, 4, 1, 3, 1, 1, 2, 0, 0, 0, 2, 0, 1, 0, 1, 2, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 1, 1, 0, 0, 1, 2, 1, 2, 3, 3, 0, 1], 'learning_rate': 6.701955377223383e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008383284662654254, 'train_segmentation_loss': 0.3591838078481136, 'val_foreground_miou_all22': 0.6940078657346187, 'val_psnr_ref1': 37.88308700561524, 'elapsed_seconds': 337.8057174682617, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 197/500 | Batch 10/202 | Rec 0.000947 | Seg 0.362723 | Elapsed 0.2m | ETA 4.0m
Epoch 197/500 | Batch 20/202 | Rec 0.000952 | Seg 0.395979 | Elapsed 0.4m | ETA 3.9m
Epoch 197/500 | Batch 30/202 | Rec 0.000899 | Seg 0.361556 | Elapsed 0.6m | ETA 3.7m
Epoch 197/500 | Batch 40/202 | Rec 0.000888 | Seg 0.347642 | Elapsed 0.9m | ETA 3.5m
Epoch 197/500 | Batch 50/202 | Rec 0.000861 | Seg 0.341405 | Elapsed 1.1m | ETA 3.3m
Epoch 197/500 | Batch 60/202 | Rec 0.000840 | Seg 0.337118 | Elapsed 1.3m | ETA 3.1m
Epoch 197/500 | Batch 70/202 | Rec 0.000801 | Seg 0.323547 | Elapsed 1.5m | ETA 2.8m
Epoch 197/500 | Batch 80/202 | Rec 0.000795 | Seg 0.323067 | Elapsed 1.7m | ETA 2.6m
Epoch 197/500 | Batch 90/202 | Rec 0.000807 | Seg 0.336118 | Elapsed 1.9m | ETA 2.4m
Epoch 197/500 | Batch 100/202 | Rec 0.000825 | Seg 0.337847 | Elapsed 2.2m | ETA 2.2m
Epoch 197/500 | Batch 110/202 | Rec 0.000818 | Seg 0.341103 | Elapsed 2.4m | ETA 2.0m
Epoch 197/500 | Batch 120/202 | Rec 0.000831 | Seg 0.348271 | Elapsed 2.6m | ETA 1.8m
Epoch 197/500 | Batch 130/202 | Rec 0.000825 | Seg 0.346795 | Elapsed 2.8m | ETA 1.5m
Epoch 197/500 | Batch 140/202 | Rec 0.000820 | Seg 0.345199 | Elapsed 3.0m | ETA 1.3m
Epoch 197/500 | Batch 150/202 | Rec 0.000810 | Seg 0.345454 | Elapsed 3.2m | ETA 1.1m
Epoch 197/500 | Batch 160/202 | Rec 0.000817 | Seg 0.349730 | Elapsed 3.4m | ETA 0.9m
Epoch 197/500 | Batch 170/202 | Rec 0.000817 | Seg 0.348520 | Elapsed 3.7m | ETA 0.7m
Epoch 197/500 | Batch 180/202 | Rec 0.000822 | Seg 0.344968 | Elapsed 3.9m | ETA 0.5m
Epoch 197/500 | Batch 190/202 | Rec 0.000820 | Seg 0.341306 | Elapsed 4.1m | ETA 0.3m
Epoch 197/500 | Batch 200/202 | Rec 0.000823 | Seg 0.342957 | Elapsed 4.3m | ETA 0.0m
Epoch 197/500 | Batch 202/202 | Rec 0.000824 | Seg 0.344405 | Elapsed 4.4m | ETA 0.0m

2026-09-23 14:57:13,736 - INFO: Rec loss: 0.0008244843183011554
2026-09-23 14:57:13,737 - INFO: Seg loss: 0.34440488412533654
2026-09-23 14:57:13,737 - INFO: λ_rec: 1
2026-09-23 14:57:13,737 - INFO: λ_seg: 0.0001
2026-09-23 14:58:30,050 - INFO: -------------------Epoch: 197------------------------
2026-09-23 14:58:30,054 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  37.818699  0.97142  0.000173
2026-09-23 14:58:30,061 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995232  0.997560  0.996376  0.998847  0.995444
real potato   0.802662  0.890480  0.992478  0.807575  0.999762
fake potato   0.844785  0.915813  0.972687  0.865312  0.999884
real apple    0.673130  0.804586  0.888159  0.735471  0.998768
fake apple    0.576321  0.731176  0.980823  0.582889  0.998382
real orange   0.799565  0.888571  0.985199  0.809287  0.999733
fake orange   0.891663  0.942679  0.901508  0.987901  0.999656
real grape    0.593581  0.744916  0.844572  0.666374  0.999047
fake grape    0.854469  0.921474  0.950342  0.894403  0.999436
real lemon    0.400306  0.571693  0.477113  0.713191  0.998744
fake lemon    0.844500  0.915646  0.988710  0.852723  0.999668
real avocado  0.818673  0.900247  0.860048  0.944499  0.999806
fake avocado  0.131327  0.232144  0.999030  0.131344  0.998960
real pepper   0.804220  0.891438  0.904088  0.879234  0.999217
fake pepper   0.877288  0.934583  0.976627  0.896101  0.999701
real plant    0.825313  0.904248  0.912364  0.896372  0.998102
fake plant    0.776200  0.873951  0.900386  0.849118  0.999805
real banana   0.318652  0.483263  0.970113  0.321812  0.998454
fake banana   0.646677  0.785383  0.735554  0.842568  0.999153
real onion    0.627347  0.770958  0.634746  0.981760  0.999473
fake onion    0.947456  0.972969  0.982495  0.963724  0.999966
real unknown  0.765973  0.867431  0.775771  0.983779  0.999952
fake unknown  0.168209  0.287946  0.179534  0.727273  0.996970
total         0.694937  0.792572  0.861249  0.797024  0.999047
total(-bg)    0.681287  0.783254  0.855107  0.787850  0.999211
2026-09-23 14:58:30,570 - INFO: Epoch accounting: {'epoch': 197, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11352222, 49305, 59053, 126653, 136007, 82511, 61239, 187745, 166625, 82458, 58232, 45461, 23454, 214229, 104401, 131387, 28901, 64805, 60955, 100487, 52355, 7076, 42711], 'crops_with_class': [202, 26, 24, 37, 38, 28, 22, 36, 34, 35, 26, 17, 9, 54, 26, 17, 26, 19, 27, 37, 27, 8, 18], 'targeted_crops_by_class': [0, 1, 6, 3, 6, 4, 4, 5, 2, 8, 4, 4, 1, 4, 2, 4, 6, 0, 5, 7, 7, 4, 4], 'sampled_scene_counts': [1, 2, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 2, 0, 2, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 3, 0, 1, 3, 0, 3, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 2, 1, 1, 0, 2, 2, 0, 0, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 2, 1, 2, 2, 1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 2, 5, 1, 2, 1, 3, 0, 1, 1, 2, 4, 3, 1, 2, 1, 2, 1, 1, 2, 1, 3, 1, 1, 1, 2, 1, 2, 3, 1, 3, 0, 1, 0, 1, 1, 1, 0, 1, 3, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 4, 2, 1, 2, 3, 2, 2, 1, 2, 2], 'learning_rate': 6.672437478308387e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008244843183011554, 'train_segmentation_loss': 0.34440488412533654, 'val_foreground_miou_all22': 0.6812872262334337, 'val_psnr_ref1': 37.81869873046875, 'elapsed_seconds': 338.38078260421753, 'peak_cuda_allocated_gib': 7.508579254150391}

Epoch 198/500 | Batch 10/202 | Rec 0.000863 | Seg 0.365312 | Elapsed 0.2m | ETA 4.2m
Epoch 198/500 | Batch 20/202 | Rec 0.000775 | Seg 0.325856 | Elapsed 0.4m | ETA 4.0m
Epoch 198/500 | Batch 30/202 | Rec 0.000788 | Seg 0.332745 | Elapsed 0.6m | ETA 3.7m
Epoch 198/500 | Batch 40/202 | Rec 0.000793 | Seg 0.357884 | Elapsed 0.9m | ETA 3.5m
Epoch 198/500 | Batch 50/202 | Rec 0.000810 | Seg 0.355131 | Elapsed 1.1m | ETA 3.2m
Epoch 198/500 | Batch 60/202 | Rec 0.000825 | Seg 0.355010 | Elapsed 1.3m | ETA 3.0m
Epoch 198/500 | Batch 70/202 | Rec 0.000839 | Seg 0.361533 | Elapsed 1.5m | ETA 2.8m
Epoch 198/500 | Batch 80/202 | Rec 0.000819 | Seg 0.350765 | Elapsed 1.7m | ETA 2.6m
Epoch 198/500 | Batch 90/202 | Rec 0.000827 | Seg 0.346616 | Elapsed 1.9m | ETA 2.4m
Epoch 198/500 | Batch 100/202 | Rec 0.000846 | Seg 0.345346 | Elapsed 2.1m | ETA 2.2m
Epoch 198/500 | Batch 110/202 | Rec 0.000842 | Seg 0.347420 | Elapsed 2.4m | ETA 2.0m
Epoch 198/500 | Batch 120/202 | Rec 0.000847 | Seg 0.347245 | Elapsed 2.6m | ETA 1.8m
Epoch 198/500 | Batch 130/202 | Rec 0.000863 | Seg 0.352543 | Elapsed 2.8m | ETA 1.5m
Epoch 198/500 | Batch 140/202 | Rec 0.000884 | Seg 0.348069 | Elapsed 3.0m | ETA 1.3m
Epoch 198/500 | Batch 150/202 | Rec 0.000894 | Seg 0.350200 | Elapsed 3.2m | ETA 1.1m
Epoch 198/500 | Batch 160/202 | Rec 0.000890 | Seg 0.349015 | Elapsed 3.4m | ETA 0.9m
Epoch 198/500 | Batch 170/202 | Rec 0.000891 | Seg 0.353093 | Elapsed 3.7m | ETA 0.7m
Epoch 198/500 | Batch 180/202 | Rec 0.000876 | Seg 0.353281 | Elapsed 3.9m | ETA 0.5m
Epoch 198/500 | Batch 190/202 | Rec 0.000859 | Seg 0.346997 | Elapsed 4.1m | ETA 0.3m
Epoch 198/500 | Batch 200/202 | Rec 0.000863 | Seg 0.346979 | Elapsed 4.3m | ETA 0.0m
Epoch 198/500 | Batch 202/202 | Rec 0.000863 | Seg 0.346868 | Elapsed 4.4m | ETA 0.0m

2026-09-23 15:02:51,703 - INFO: Rec loss: 0.0008633089853199383
2026-09-23 15:02:51,703 - INFO: Seg loss: 0.34686777958332904
2026-09-23 15:02:51,703 - INFO: λ_rec: 1
2026-09-23 15:02:51,704 - INFO: λ_seg: 0.0001
2026-09-23 15:04:07,849 - INFO: -------------------Epoch: 198------------------------
2026-09-23 15:04:07,853 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.723315  0.971057  0.000175
2026-09-23 15:04:07,860 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994648  0.997267  0.995648  0.998992  0.994883
real potato   0.507396  0.673164  1.000000  0.507396  0.999411
fake potato   0.749006  0.856444  0.999162  0.749476  0.999817
real apple    0.615797  0.762171  0.821851  0.710659  0.998470
fake apple    0.691119  0.817302  0.965580  0.708576  0.998804
real orange   0.670830  0.802942  0.998279  0.671607  0.999566
fake orange   0.835936  0.910588  0.862598  0.964343  0.999458
real grape    0.309841  0.473053  0.690313  0.359863  0.998326
fake grape    0.828851  0.906367  0.930495  0.883554  0.999325
real lemon    0.309185  0.472284  0.392999  0.591794  0.998446
fake lemon    0.789743  0.882472  0.998361  0.790768  0.999555
real avocado  0.854785  0.921658  0.908193  0.935632  0.999852
fake avocado  0.076001  0.141253  1.000000  0.076001  0.998894
real pepper   0.839484  0.912688  0.919304  0.906266  0.999366
fake pepper   0.942526  0.970363  0.989357  0.952180  0.999862
real plant    0.780660  0.876771  0.856337  0.898310  0.997475
fake plant    0.805220  0.892052  0.903143  0.881327  0.999830
real banana   0.293798  0.454127  0.962189  0.297229  0.998395
fake banana   0.605263  0.754049  0.701951  0.814615  0.999023
real onion    0.719875  0.837075  0.759598  0.932275  0.999672
fake onion    0.921109  0.958885  0.987695  0.931802  0.999950
real unknown  0.908397  0.951950  1.000000  0.908397  0.999985
fake unknown  0.179475  0.304295  0.196921  0.669504  0.997421
total         0.662128  0.762140  0.862608  0.745242  0.998947
total(-bg)    0.647014  0.751452  0.856560  0.733708  0.999132
2026-09-23 15:04:08,362 - INFO: Epoch accounting: {'epoch': 198, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11338814, 46277, 56776, 132559, 136982, 88649, 88282, 109128, 141790, 61976, 59567, 52580, 53880, 205582, 127560, 163039, 31599, 66466, 80660, 84878, 56373, 10963, 43892], 'crops_with_class': [202, 27, 23, 34, 31, 28, 30, 21, 29, 31, 21, 18, 18, 48, 30, 23, 26, 22, 33, 34, 26, 13, 23], 'targeted_crops_by_class': [0, 3, 4, 3, 0, 4, 4, 5, 2, 3, 2, 8, 7, 6, 4, 2, 8, 7, 6, 5, 4, 4, 2], 'sampled_scene_counts': [3, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 2, 2, 0, 1, 0, 1, 2, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 0, 1, 2, 2, 1, 1, 0, 2, 1, 2, 1, 3, 1, 2, 0, 0, 1, 2, 2, 1, 0, 3, 6, 0, 3, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 0, 2, 4, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 4, 1, 0, 1, 2, 3, 2, 0, 2, 2, 0, 2, 2, 3, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 3, 2, 0], 'learning_rate': 6.64285404790402e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008633089853199383, 'train_segmentation_loss': 0.34686777958332904, 'val_foreground_miou_all22': 0.6470135264777244, 'val_psnr_ref1': 37.72331497192383, 'elapsed_seconds': 337.7838554382324, 'peak_cuda_allocated_gib': 7.5111846923828125}

Epoch 199/500 | Batch 10/202 | Rec 0.000664 | Seg 0.249594 | Elapsed 0.2m | ETA 4.1m
Epoch 199/500 | Batch 20/202 | Rec 0.000638 | Seg 0.260611 | Elapsed 0.4m | ETA 3.9m
Epoch 199/500 | Batch 30/202 | Rec 0.000650 | Seg 0.269035 | Elapsed 0.6m | ETA 3.7m
Epoch 199/500 | Batch 40/202 | Rec 0.000746 | Seg 0.315300 | Elapsed 0.9m | ETA 3.5m
Epoch 199/500 | Batch 50/202 | Rec 0.000719 | Seg 0.308390 | Elapsed 1.1m | ETA 3.2m
Epoch 199/500 | Batch 60/202 | Rec 0.000703 | Seg 0.292838 | Elapsed 1.3m | ETA 3.0m
Epoch 199/500 | Batch 70/202 | Rec 0.000730 | Seg 0.310052 | Elapsed 1.5m | ETA 2.8m
Epoch 199/500 | Batch 80/202 | Rec 0.000747 | Seg 0.311871 | Elapsed 1.7m | ETA 2.6m
Epoch 199/500 | Batch 90/202 | Rec 0.000751 | Seg 0.318903 | Elapsed 1.9m | ETA 2.4m
Epoch 199/500 | Batch 100/202 | Rec 0.000751 | Seg 0.325708 | Elapsed 2.1m | ETA 2.2m
Epoch 199/500 | Batch 110/202 | Rec 0.000758 | Seg 0.324964 | Elapsed 2.4m | ETA 2.0m
Epoch 199/500 | Batch 120/202 | Rec 0.000768 | Seg 0.326155 | Elapsed 2.6m | ETA 1.8m
Epoch 199/500 | Batch 130/202 | Rec 0.000783 | Seg 0.332959 | Elapsed 2.8m | ETA 1.5m
Epoch 199/500 | Batch 140/202 | Rec 0.000792 | Seg 0.334698 | Elapsed 3.0m | ETA 1.3m
Epoch 199/500 | Batch 150/202 | Rec 0.000784 | Seg 0.331982 | Elapsed 3.2m | ETA 1.1m
Epoch 199/500 | Batch 160/202 | Rec 0.000784 | Seg 0.331794 | Elapsed 3.4m | ETA 0.9m
Epoch 199/500 | Batch 170/202 | Rec 0.000784 | Seg 0.333705 | Elapsed 3.6m | ETA 0.7m
Epoch 199/500 | Batch 180/202 | Rec 0.000787 | Seg 0.338333 | Elapsed 3.9m | ETA 0.5m
Epoch 199/500 | Batch 190/202 | Rec 0.000795 | Seg 0.339778 | Elapsed 4.1m | ETA 0.3m
Epoch 199/500 | Batch 200/202 | Rec 0.000792 | Seg 0.337387 | Elapsed 4.3m | ETA 0.0m
Epoch 199/500 | Batch 202/202 | Rec 0.000788 | Seg 0.335721 | Elapsed 4.3m | ETA 0.0m

2026-09-23 15:08:27,219 - INFO: Rec loss: 0.0007883536159395157
2026-09-23 15:08:27,219 - INFO: Seg loss: 0.3357206893402456
2026-09-23 15:08:27,220 - INFO: λ_rec: 1
2026-09-23 15:08:27,220 - INFO: λ_seg: 0.0001
2026-09-23 15:09:43,539 - INFO: -------------------Epoch: 199------------------------
2026-09-23 15:09:43,544 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.679845  0.969779  0.000177
2026-09-23 15:09:43,550 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994640  0.997263  0.995547  0.999086  0.994875
real potato   0.186942  0.314971  1.000000  0.186942  0.999027
fake potato   0.641573  0.781608  0.997399  0.642648  0.999738
real apple    0.607931  0.756116  0.708841  0.810261  0.998197
fake apple    0.877399  0.934647  0.948003  0.921759  0.999514
real orange   0.523535  0.687216  0.869989  0.567971  0.999319
fake orange   0.649348  0.787352  0.658111  0.979906  0.998485
real grape    0.678717  0.808564  0.827771  0.790324  0.999219
fake grape    0.837000  0.911218  0.942561  0.881987  0.999365
real lemon    0.330468  0.496725  0.370477  0.753700  0.998205
fake lemon    0.849270  0.918443  0.985134  0.860296  0.999677
real avocado  0.687945  0.815078  0.721828  0.936125  0.999605
fake avocado  0.512044  0.677242  0.988739  0.515047  0.999413
real pepper   0.763281  0.865701  0.946405  0.797764  0.999095
fake pepper   0.447130  0.617911  0.997006  0.447731  0.998680
real plant    0.820925  0.901607  0.933566  0.871857  0.998098
fake plant    0.767287  0.868272  0.875170  0.861580  0.999792
real banana   0.060256  0.113653  0.987764  0.060302  0.997887
fake banana   0.649061  0.787139  0.774611  0.800182  0.999204
real onion    0.589281  0.741519  0.781373  0.705624  0.999556
fake onion    0.933076  0.965329  0.998965  0.933978  0.999958
real unknown  0.631080  0.773770  0.651239  0.953244  0.999911
fake unknown  0.270135  0.425319  0.317739  0.643245  0.998536
total         0.622101  0.736812  0.838184  0.735720  0.998928
total(-bg)    0.605167  0.724973  0.831031  0.723749  0.999113
2026-09-23 15:09:44,069 - INFO: Epoch accounting: {'epoch': 199, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11339462, 54351, 69006, 135252, 119198, 84192, 69969, 159518, 200432, 78926, 46959, 64467, 62787, 237558, 102513, 65885, 14053, 64112, 80366, 84037, 58931, 7907, 38391], 'crops_with_class': [202, 29, 32, 34, 28, 25, 27, 29, 33, 35, 24, 19, 23, 51, 28, 10, 12, 19, 33, 35, 28, 8, 17], 'targeted_crops_by_class': [0, 6, 6, 7, 2, 5, 4, 3, 8, 8, 4, 3, 11, 6, 3, 0, 3, 2, 6, 4, 6, 4, 4], 'sampled_scene_counts': [1, 0, 3, 2, 2, 0, 0, 0, 1, 3, 1, 1, 0, 1, 1, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 3, 1, 2, 1, 2, 0, 1, 3, 2, 3, 0, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 0, 1, 0, 0, 0, 3, 0, 0, 1, 0, 3, 1, 2, 1, 1, 1, 1, 0, 2, 2, 0, 2, 1, 0, 2, 2, 2, 1, 0, 3, 1, 1, 1, 3, 1, 0, 1, 0, 1, 0, 0, 2, 1, 0, 2, 3, 2, 2, 1, 2, 1, 1, 0, 0, 1, 2, 2, 0, 1, 1, 1, 0, 3, 1, 3, 1, 2, 0, 3, 0, 1, 1, 0, 1, 1, 2, 3, 0, 2, 0, 0, 3, 2, 0, 4, 2, 4], 'learning_rate': 6.61320625391345e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007883536159395157, 'train_segmentation_loss': 0.3357206893402456, 'val_foreground_miou_all22': 0.6051674496565949, 'val_psnr_ref1': 37.679844512939454, 'elapsed_seconds': 335.7000358104706, 'peak_cuda_allocated_gib': 7.510044097900391}

Epoch 200/500 | Batch 10/202 | Rec 0.001056 | Seg 0.460487 | Elapsed 0.2m | ETA 4.0m
Epoch 200/500 | Batch 20/202 | Rec 0.000912 | Seg 0.384848 | Elapsed 0.4m | ETA 3.9m
Epoch 200/500 | Batch 30/202 | Rec 0.000899 | Seg 0.365313 | Elapsed 0.6m | ETA 3.7m
Epoch 200/500 | Batch 40/202 | Rec 0.000871 | Seg 0.365619 | Elapsed 0.9m | ETA 3.5m
Epoch 200/500 | Batch 50/202 | Rec 0.000839 | Seg 0.335549 | Elapsed 1.1m | ETA 3.3m
Epoch 200/500 | Batch 60/202 | Rec 0.000836 | Seg 0.335208 | Elapsed 1.3m | ETA 3.1m
Epoch 200/500 | Batch 70/202 | Rec 0.000822 | Seg 0.334044 | Elapsed 1.5m | ETA 2.9m
Epoch 200/500 | Batch 80/202 | Rec 0.000837 | Seg 0.348505 | Elapsed 1.7m | ETA 2.6m
Epoch 200/500 | Batch 90/202 | Rec 0.000821 | Seg 0.343173 | Elapsed 1.9m | ETA 2.4m
Epoch 200/500 | Batch 100/202 | Rec 0.000796 | Seg 0.333333 | Elapsed 2.1m | ETA 2.2m
Epoch 200/500 | Batch 110/202 | Rec 0.000810 | Seg 0.340235 | Elapsed 2.4m | ETA 2.0m
Epoch 200/500 | Batch 120/202 | Rec 0.000805 | Seg 0.338594 | Elapsed 2.6m | ETA 1.8m
Epoch 200/500 | Batch 130/202 | Rec 0.000800 | Seg 0.334676 | Elapsed 2.8m | ETA 1.6m
Epoch 200/500 | Batch 140/202 | Rec 0.000811 | Seg 0.337984 | Elapsed 3.0m | ETA 1.3m
Epoch 200/500 | Batch 150/202 | Rec 0.000795 | Seg 0.333789 | Elapsed 3.2m | ETA 1.1m
Epoch 200/500 | Batch 160/202 | Rec 0.000799 | Seg 0.336429 | Elapsed 3.5m | ETA 0.9m
Epoch 200/500 | Batch 170/202 | Rec 0.000787 | Seg 0.332348 | Elapsed 3.7m | ETA 0.7m
Epoch 200/500 | Batch 180/202 | Rec 0.000781 | Seg 0.331914 | Elapsed 3.9m | ETA 0.5m
Epoch 200/500 | Batch 190/202 | Rec 0.000778 | Seg 0.333705 | Elapsed 4.1m | ETA 0.3m
Epoch 200/500 | Batch 200/202 | Rec 0.000773 | Seg 0.332757 | Elapsed 4.3m | ETA 0.0m
Epoch 200/500 | Batch 202/202 | Rec 0.000774 | Seg 0.334142 | Elapsed 4.4m | ETA 0.0m

2026-09-23 15:14:05,931 - INFO: Rec loss: 0.0007740801209923904
2026-09-23 15:14:05,931 - INFO: Seg loss: 0.33414209353746754
2026-09-23 15:14:05,931 - INFO: λ_rec: 1
2026-09-23 15:14:05,931 - INFO: λ_seg: 0.0001
2026-09-23 15:15:22,413 - INFO: -------------------Epoch: 200------------------------
2026-09-23 15:15:22,417 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.574205  0.971244  0.000181
2026-09-23 15:15:22,423 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994916  0.997402  0.996392  0.998514  0.995143
real potato   0.835661  0.910425  0.984435  0.846850  0.999801
fake potato   0.918981  0.957730  0.988411  0.928990  0.999940
real apple    0.668252  0.801091  0.921590  0.708536  0.998786
fake apple    0.599785  0.749785  0.977274  0.608269  0.998468
real orange   0.922521  0.959650  0.989064  0.932029  0.999897
fake orange   0.927116  0.962130  0.969178  0.955282  0.999785
real grape    0.604600  0.753533  0.730548  0.778119  0.998938
fake grape    0.873451  0.932402  0.946273  0.919028  0.999507
real lemon    0.564570  0.721643  0.735508  0.708387  0.999358
fake lemon    0.718032  0.835829  0.998397  0.718860  0.999403
real avocado  0.768708  0.869182  0.802586  0.947947  0.999735
fake avocado  0.531107  0.693710  0.999520  0.531242  0.999439
real pepper   0.772212  0.871417  0.872798  0.870140  0.999061
fake pepper   0.864315  0.927170  0.981825  0.878369  0.999671
real plant    0.849983  0.918859  0.901958  0.936508  0.998347
fake plant    0.786080  0.880180  0.826131  0.941909  0.999796
real banana   0.687463  0.814740  0.965312  0.704876  0.999280
fake banana   0.638065  0.778997  0.748909  0.811712  0.999153
real onion    0.639295  0.779915  0.683983  0.907279  0.999538
fake onion    0.936094  0.966942  0.989125  0.945828  0.999959
real unknown  0.640574  0.780866  0.669393  0.937023  0.999916
fake unknown  0.187785  0.316155  0.217232  0.580768  0.997883
total         0.736068  0.833902  0.865037  0.830281  0.999165
total(-bg)    0.724302  0.826470  0.859066  0.822634  0.999348
2026-09-23 15:15:22,919 - INFO: Epoch accounting: {'epoch': 200, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11423119, 34674, 40281, 142886, 149127, 75348, 52016, 176061, 225208, 51580, 33751, 55804, 43107, 169315, 72359, 160648, 32115, 65858, 58197, 61466, 60374, 13112, 41866], 'crops_with_class': [202, 21, 21, 35, 42, 23, 19, 35, 38, 24, 19, 19, 19, 43, 24, 23, 29, 18, 27, 31, 25, 15, 19], 'targeted_crops_by_class': [0, 3, 2, 5, 5, 3, 3, 6, 3, 5, 5, 8, 5, 3, 2, 6, 4, 4, 4, 5, 3, 6, 1], 'sampled_scene_counts': [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 3, 1, 1, 0, 1, 1, 2, 1, 2, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 0, 1, 2, 2, 2, 1, 4, 2, 0, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 4, 1, 0, 2, 1, 1, 1, 0, 0, 3, 1, 3, 0, 1, 2, 2, 2, 1, 2, 1, 3, 1, 4, 4, 2, 3, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 5, 0, 2, 0, 2, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 2, 0, 2, 0, 0, 4, 1, 2, 0, 0, 1, 0, 1, 0, 2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1], 'learning_rate': 6.583495266780825e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007740801209923904, 'train_segmentation_loss': 0.33414209353746754, 'val_foreground_miou_all22': 0.7243022351531792, 'val_psnr_ref1': 37.57420455932617, 'elapsed_seconds': 338.84246850013733, 'peak_cuda_allocated_gib': 7.509708404541016}

Stopped after epoch 200; scheduler horizon remains 500
Saved epoch: 200 | block target: 200 | Missing checkpoint files: []
Download: /kaggle/working/balanced150_to_epoch200_20260923_102523_epoch200.zip

/kaggle/working/balanced150_to_epoch200_20260923_102523_epoch200.zip

Epoch200 completed. Download the full backup before stopping the session.

In [5]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((CONT150_RUN / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(151,201)), 'Not all50 new epochs completed.'
for start,end in [(151,175),(176,200)]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] <= end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:', json.dumps(records[-1], indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

Epochs151-175: mean mIoU=63.85%, std=4.36 points
Epochs176-200: mean mIoU=67.09%, std=4.41 points
Final: {
  "epoch": 200,
  "scheduler_horizon": 500,
  "lambda_rec": 1,
  "lambda_seg": 0.0001,
  "sampling_policy": "balanced50_v1",
  "class_pixels_seen": [
    11423119,
    34674,
    40281,
    142886,
    149127,
    75348,
    52016,
    176061,
    225208,
    51580,
    33751,
    55804,
    43107,
    169315,
    72359,
    160648,
    32115,
    65858,
    58197,
    61466,
    60374,
    13112,
    41866
  ],
  "crops_with_class": [
    202,
    21,
    21,
    35,
    42,
    23,
    19,
    35,
    38,
    24,
    19,
    19,
    19,
    43,
    24,
    23,
    29,
    18,
    27,
    31,
    25,
    15,
    19
  ],
  "targeted_crops_by_class": [
    0,
    3,
    2,
    5,
    5,
    3,
    3,
    6,
    3,
    5,
    5,
    8,
    5,
    3,
    2,
    6,
    4,
    4,
    4,
    5,
    3,
    6,
    1
  ],
  "sampled_scene_counts": [
    0,
    1,
    0,
    1,
    0,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    1,
    1,
    3,
    1,
    1,
    0,
    1,
    1,
    2,
    1,
    2,
    1,
    0,
    0,
    0,
    1,
    1,
    0,
    0,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    1,
    2,
    2,
    0,
    2,
    2,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    2,
    0,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    2,
    1,
    0,
    1,
    2,
    2,
    2,
    1,
    4,
    2,
    0,
    0,
    1,
    0,
    1,
    2,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    2,
    1,
    1,
    0,
    1,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    4,
    1,
    0,
    2,
    1,
    1,
    1,
    0,
    0,
    3,
    1,
    3,
    0,
    1,
    2,
    2,
    2,
    1,
    2,
    1,
    3,
    1,
    4,
    4,
    2,
    3,
    2,
    2,
    2,
    2,
    1,
    1,
    2,
    2,
    2,
    1,
    5,
    0,
    2,
    0,
    2,
    1,
    1,
    1,
    1,
    2,
    1,
    0,
    0,
    1,
    1,
    2,
    0,
    2,
    0,
    0,
    4,
    1,
    2,
    0,
    0,
    1,
    0,
    1,
    0,
    2,
    1,
    1,
    2,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    2,
    1
  ],
  "learning_rate": 6.583495266780825e-05,
  "attempted_updates": 202,
  "optimizer_updates": 202,
  "amp_skipped_updates": 0,
  "train_reconstruction_loss": 0.0007740801209923904,
  "train_segmentation_loss": 0.33414209353746754,
  "val_foreground_miou_all22": 0.7243022351531792,
  "val_psnr_ref1": 37.57420455932617,
  "elapsed_seconds": 338.84246850013733,
  "peak_cuda_allocated_gib": 7.509708404541016
}
New successful updates: 10097
New AMP skips: 3

In [1]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='5ad004708dd6ce388708ad3627cf8206b184804b6202754204f7296bfc253c7b'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced150_to_epoch200_20260923_102523/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch188_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced150_to_epoch200_20260923_102523_epoch200.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch188 weights:',CHECKPOINT)

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch188 weights: /kaggle/input/datasets/arnavnigamd/checkpoint10/balanced150_to_epoch200_20260923_102523/model/best_iou.pth

In [3]:
NAME='epoch188_validation_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f')
RUN=WORK/NAME
subprocess.run([sys.executable,'test.py','--data_root',str(DATA),
    '--transpose_image','--eval_split','val','--pretrained_model_path',str(CHECKPOINT),
    '--outf',str(WORK),'--name',NAME,'--workers','0','--save_segmentation'],
    cwd=CODE,check=True)
OUT=RUN/'evaluation_val'
print('Evaluation complete:',OUT)

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

load model from /kaggle/input/datasets/arnavnigamd/checkpoint10/balanced150_to_epoch200_20260923_102523/model/best_iou.pth
Evaluated 1/25
Evaluated 2/25
Evaluated 3/25
Evaluated 4/25
Evaluated 5/25
Evaluated 6/25
Evaluated 7/25
Evaluated 8/25
Evaluated 9/25
Evaluated 10/25
Evaluated 11/25
Evaluated 12/25
Evaluated 13/25
Evaluated 14/25
Evaluated 15/25
Evaluated 16/25
Evaluated 17/25
Evaluated 18/25
Evaluated 19/25
Evaluated 20/25
Evaluated 21/25
Evaluated 22/25
Evaluated 23/25
Evaluated 24/25
Evaluated 25/25
Completed val: 25 scenes. Results: /kaggle/working/epoch188_validation_audit_20260923_152602_480885/evaluation_val
Evaluation complete: /kaggle/working/epoch188_validation_audit_20260923_152602_480885/evaluation_val

In [4]:
EXPECTED_MIOU=0.7511010246306207
EXPECTED_PSNR=37.20344635009766

import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['split']=='val' and meta['scene_count']==25
assert meta['checkpoint_sha256']==EXPECTED
assert len(set(meta['scenes']))==25
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(scene+'_confusion.npy')) for scene in meta['scenes']]
assert np.array_equal(sum(parts),cm), 'Per-scene confusion totals differ.'
assert len(list(OUT.glob('*_preview.png')))==25
assert not list(OUT.glob('*_hsi.npy'))
seg=pd.read_csv(OUT/'segmentation.csv',index_col=0)
rec=pd.read_csv(OUT/'reconstruction.csv')
miou=float(seg.loc['total(-bg)','IoU'])
psnr=float(rec.iloc[0]['PSNR'])
summary=dict(checkpoint_epoch=188,validation_scenes=25,foreground_miou=miou,
    psnr_ref1=psnr,logged_miou=EXPECTED_MIOU,logged_psnr=EXPECTED_PSNR,
    miou_difference=miou-EXPECTED_MIOU,psnr_difference=psnr-EXPECTED_PSNR,
    matches_logged_metrics=bool(abs(miou-EXPECTED_MIOU)<1e-5 and abs(psnr-EXPECTED_PSNR)<1e-3),
    scope='Independent full validation evaluation; no test performance or new training.')
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'evaluator_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in
    ['test.py','dataset.py','utils.py','public252-v1.json']},indent=2))
print(json.dumps(summary,indent=2))
display(seg)
display(rec)
# Save results even if the comparison differs, so the difference can be investigated.
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir(WORK)
print('Download this archive before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))
if not summary['matches_logged_metrics']:
    print('Metrics differ from the training record: share this ZIP before further training.')

{
  "checkpoint_epoch": 188,
  "validation_scenes": 25,
  "foreground_miou": 0.7511010246306207,
  "psnr_ref1": 37.20344635009766,
  "logged_miou": 0.7511010246306207,
  "logged_psnr": 37.20344635009766,
  "miou_difference": 0.0,
  "psnr_difference": 0.0,
  "matches_logged_metrics": true,
  "scope": "Independent full validation evaluation; no test performance or new training."
}

                   IoU        F1      Prec    recall       Acc
bg,           0.994884  0.997385  0.995726  0.999151  0.995109
real potato   0.853408  0.920857  0.994527  0.857434  0.999824
fake potato   0.831001  0.907651  0.996743  0.833263  0.999877
real apple    0.794536  0.885456  0.944514  0.833437  0.999256
fake apple    0.708511  0.829341  0.992011  0.712577  0.998893
real orange   0.837629  0.911592  0.992636  0.842867  0.999785
fake orange   0.894045  0.944009  0.927620  0.961092  0.999674
real grape    0.685922  0.813656  0.905953  0.738508  0.999294
fake grape    0.831467  0.907929  0.921975  0.894403  0.999329
real lemon    0.655068  0.791541  0.706795  0.899507  0.999443
fake lemon    0.837368  0.911437  0.995219  0.840750  0.999655
real avocado  0.773294  0.872106  0.801376  0.956650  0.999739
fake avocado  0.471986  0.641247  0.992254  0.473731  0.999366
real pepper   0.793202  0.884627  0.911322  0.859544  0.999180
fake pepper   0.893177  0.943525  0.983543  0.906728  0.999742
real plant    0.820566  0.901391  0.945266  0.861499  0.998116
fake plant    0.766950  0.868056  0.854016  0.882669  0.999787
real banana   0.625900  0.769864  0.958612  0.643284  0.999136
fake banana   0.691440  0.817525  0.821824  0.813371  0.999332
real onion    0.737681  0.848992  0.765392  0.953217  0.999694
fake onion    0.926104  0.961584  0.991523  0.933495  0.999953
real unknown  0.882819  0.937713  0.920110  0.956107  0.999980
fake unknown  0.212149  0.349998  0.242447  0.629301  0.998031
total         0.761700  0.852934  0.893974  0.838373  0.999226
total(-bg)    0.751101  0.846368  0.889349  0.831065  0.999413

        PSNR      SSIM       MSE
0  37.203446  0.969442  0.000198

Download this archive before stopping: epoch188_validation_audit_20260923_152602_480885.zip 7161904 bytes

/kaggle/working/epoch188_validation_audit_20260923_152602_480885.zip

In [1]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced150_to_epoch200_20260923_102523'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced200')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced150_to_epoch200_20260923_102523_epoch200.zip or its extracted folder.'
CHECKPOINT = refs[0]
assert hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest() == 'e0c7e178b9c90178cc08d71136d3f5316ab985159b9ab1254bf26c5cf0325e9a', 'Wrong epoch200 checkpoint.'
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch200 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 200
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 200
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch200 run.')

Balanced epoch200 reference: /kaggle/input/datasets/arnavnigamd/checkpoint10/balanced150_to_epoch200_20260923_102523
PASS:22-class support, aligned crops/flips, deterministic replay, no RNG consumed by index building, baseline crop branch unchanged.
Saved next-epoch LR: 6.553722259445043e-05
Preserved best metrics: {'iou': 0.7511010246306207, 'psnr': 38.022851104736326}
{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.
Training source hashes match the epoch200 run.

In [2]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT200_RUN' not in globals():
    CONT200_RUN = Path('/kaggle/working') / ('balanced200_to_epoch250_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT200_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT200_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 200, 'target_epoch': 250, 'backup_epochs': [250],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Single subprocess continuation from200 through250.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT200_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT200_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT200_RUN.parent / (CONT200_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT200_RUN.parent, base_dir=CONT200_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT200_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT200_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target == 250
    last = CONT200_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT200_RUN.parent) + '/', '--name', CONT200_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT200_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT200_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Epoch250 completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT200_RUN)

Continuation folder: /kaggle/working/balanced200_to_epoch250_20260923_155019

In [3]:
continue_to(250)

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced200_to_epoch250_20260923_155019', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/input/datasets/arnavnigamd/checkpoint10/balanced150_to_epoch200_20260923_102523/model/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=250, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-23 15:51:07,756 - INFO: Resuming after epoch 200

Epoch 201/500 | Batch 10/202 | Rec 0.000903 | Seg 0.339494 | Elapsed 0.7m | ETA 12.7m
Epoch 201/500 | Batch 20/202 | Rec 0.000963 | Seg 0.334189 | Elapsed 1.0m | ETA 9.3m
Epoch 201/500 | Batch 30/202 | Rec 0.000900 | Seg 0.318285 | Elapsed 1.5m | ETA 8.4m
Epoch 201/500 | Batch 40/202 | Rec 0.000894 | Seg 0.340804 | Elapsed 1.9m | ETA 7.7m
Epoch 201/500 | Batch 50/202 | Rec 0.000882 | Seg 0.337762 | Elapsed 2.3m | ETA 7.1m
Epoch 201/500 | Batch 60/202 | Rec 0.000835 | Seg 0.324124 | Elapsed 2.8m | ETA 6.5m
Epoch 201/500 | Batch 70/202 | Rec 0.000834 | Seg 0.323390 | Elapsed 3.2m | ETA 6.1m
Epoch 201/500 | Batch 80/202 | Rec 0.000822 | Seg 0.315940 | Elapsed 3.6m | ETA 5.5m
Epoch 201/500 | Batch 90/202 | Rec 0.000814 | Seg 0.313874 | Elapsed 4.1m | ETA 5.1m
Epoch 201/500 | Batch 100/202 | Rec 0.000808 | Seg 0.314649 | Elapsed 4.5m | ETA 4.6m
Epoch 201/500 | Batch 110/202 | Rec 0.000798 | Seg 0.315469 | Elapsed 5.0m | ETA 4.1m
Epoch 201/500 | Batch 120/202 | Rec 0.000808 | Seg 0.323132 | Elapsed 5.4m | ETA 3.7m
Epoch 201/500 | Batch 130/202 | Rec 0.000810 | Seg 0.330113 | Elapsed 5.7m | ETA 3.2m
Epoch 201/500 | Batch 140/202 | Rec 0.000811 | Seg 0.335330 | Elapsed 6.1m | ETA 2.7m
Epoch 201/500 | Batch 150/202 | Rec 0.000805 | Seg 0.333623 | Elapsed 6.5m | ETA 2.2m
Epoch 201/500 | Batch 160/202 | Rec 0.000811 | Seg 0.338571 | Elapsed 6.8m | ETA 1.8m
Epoch 201/500 | Batch 170/202 | Rec 0.000818 | Seg 0.341421 | Elapsed 7.2m | ETA 1.3m
Epoch 201/500 | Batch 180/202 | Rec 0.000819 | Seg 0.341016 | Elapsed 7.4m | ETA 0.9m
Epoch 201/500 | Batch 190/202 | Rec 0.000825 | Seg 0.344470 | Elapsed 7.9m | ETA 0.5m
Epoch 201/500 | Batch 200/202 | Rec 0.000820 | Seg 0.341320 | Elapsed 8.3m | ETA 0.1m
Epoch 201/500 | Batch 202/202 | Rec 0.000818 | Seg 0.340260 | Elapsed 8.4m | ETA 0.0m

2026-09-23 15:59:28,915 - INFO: Rec loss: 0.0008181227655795467
2026-09-23 15:59:28,915 - INFO: Seg loss: 0.3402599443008404
2026-09-23 15:59:28,915 - INFO: λ_rec: 1
2026-09-23 15:59:28,915 - INFO: λ_seg: 0.0001
2026-09-23 16:01:18,789 - INFO: -------------------Epoch: 201------------------------
2026-09-23 16:01:18,800 - INFO:
Validation stats:
       PSNR      SSIM      MSE
0  37.36953  0.971029  0.00019
2026-09-23 16:01:18,807 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995093  0.997490  0.996536  0.998547  0.995312
real potato   0.387656  0.558681  1.000000  0.387656  0.999267
fake potato   0.656899  0.792878  0.988121  0.662128  0.999748
real apple    0.641701  0.781701  0.779876  0.783636  0.998490
fake apple    0.618683  0.764380  0.987959  0.623383  0.998549
real orange   0.830485  0.907344  0.996674  0.832793  0.999776
fake orange   0.886143  0.939585  0.915298  0.965302  0.999645
real grape    0.611306  0.758722  0.848874  0.685961  0.999089
fake grape    0.861770  0.925704  0.949521  0.903147  0.999464
real lemon    0.422943  0.594416  0.457421  0.848741  0.998639
fake lemon    0.816903  0.899176  0.993629  0.821204  0.999611
real avocado  0.890191  0.941856  0.948095  0.935796  0.999893
fake avocado  0.220796  0.361694  0.985812  0.221500  0.999065
real pepper   0.834389  0.909669  0.872025  0.950818  0.999310
fake pepper   0.842561  0.914504  0.968779  0.866078  0.999614
real plant    0.839390  0.912633  0.906753  0.918691  0.998242
fake plant    0.859077  0.924147  0.963202  0.888229  0.999884
real banana   0.327437  0.493297  0.885508  0.341912  0.998422
fake banana   0.708324  0.829212  0.833501  0.825066  0.999375
real onion    0.707592  0.828710  0.800157  0.859483  0.999679
fake onion    0.939962  0.969002  0.992645  0.946554  0.999962
real unknown  0.894265  0.944132  0.936210  0.952290  0.999982
fake unknown  0.168226  0.287971  0.179432  0.729265  0.996962
total         0.693991  0.792909  0.877653  0.780356  0.999043
total(-bg)    0.680304  0.783610  0.872250  0.770438  0.999212
2026-09-23 16:01:19,262 - INFO: Epoch accounting: {'epoch': 201, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11370810, 40278, 56736, 113439, 131332, 62361, 63004, 115132, 159433, 90050, 80864, 32552, 52196, 238535, 124408, 141604, 23641, 100027, 57872, 83246, 46317, 7792, 46643], 'crops_with_class': [202, 25, 26, 31, 32, 18, 24, 26, 31, 36, 33, 12, 18, 57, 35, 23, 22, 28, 23, 35, 21, 8, 22], 'targeted_crops_by_class': [0, 3, 3, 4, 5, 3, 0, 3, 3, 6, 5, 5, 5, 1, 3, 3, 7, 6, 5, 4, 3, 2, 5], 'sampled_scene_counts': [1, 1, 2, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 1, 1, 0, 2, 1, 2, 1, 1, 3, 0, 3, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 1, 1, 2, 1, 2, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 1, 1, 1, 2, 1, 0, 1, 3, 1, 0, 1, 1, 2, 0, 0, 2, 2, 2, 1, 3, 0, 1, 0, 1, 1, 1, 3, 1, 0, 1, 1, 0, 1, 1, 0, 3, 1, 4, 1, 4, 1, 1, 2, 1, 2, 1, 0, 0, 1, 2, 2, 3, 1, 0, 1, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 0, 1, 2, 2, 1, 1, 1, 1, 1, 0, 4, 4, 0], 'learning_rate': 6.553722259445043e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008181227655795467, 'train_segmentation_loss': 0.3402599443008404, 'val_foreground_miou_all22': 0.6803044882904099, 'val_psnr_ref1': 37.36952957153321, 'elapsed_seconds': 611.49760222435, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 202/500 | Batch 10/202 | Rec 0.000731 | Seg 0.347174 | Elapsed 0.3m | ETA 4.9m
Epoch 202/500 | Batch 20/202 | Rec 0.000752 | Seg 0.353579 | Elapsed 0.5m | ETA 4.9m
Epoch 202/500 | Batch 30/202 | Rec 0.000790 | Seg 0.351548 | Elapsed 0.9m | ETA 5.1m
Epoch 202/500 | Batch 40/202 | Rec 0.000811 | Seg 0.346457 | Elapsed 1.1m | ETA 4.5m
Epoch 202/500 | Batch 50/202 | Rec 0.000834 | Seg 0.351609 | Elapsed 1.4m | ETA 4.3m
Epoch 202/500 | Batch 60/202 | Rec 0.000834 | Seg 0.350755 | Elapsed 1.7m | ETA 3.9m
Epoch 202/500 | Batch 70/202 | Rec 0.000812 | Seg 0.340790 | Elapsed 2.0m | ETA 3.7m
Epoch 202/500 | Batch 80/202 | Rec 0.000842 | Seg 0.339556 | Elapsed 2.3m | ETA 3.4m
Epoch 202/500 | Batch 90/202 | Rec 0.000831 | Seg 0.336097 | Elapsed 2.5m | ETA 3.1m
Epoch 202/500 | Batch 100/202 | Rec 0.000819 | Seg 0.332714 | Elapsed 2.7m | ETA 2.8m
Epoch 202/500 | Batch 110/202 | Rec 0.000811 | Seg 0.329030 | Elapsed 3.0m | ETA 2.5m
Epoch 202/500 | Batch 120/202 | Rec 0.000818 | Seg 0.330382 | Elapsed 3.2m | ETA 2.2m
Epoch 202/500 | Batch 130/202 | Rec 0.000810 | Seg 0.329204 | Elapsed 3.5m | ETA 2.0m
Epoch 202/500 | Batch 140/202 | Rec 0.000787 | Seg 0.322588 | Elapsed 3.8m | ETA 1.7m
Epoch 202/500 | Batch 150/202 | Rec 0.000785 | Seg 0.321014 | Elapsed 4.0m | ETA 1.4m
Epoch 202/500 | Batch 160/202 | Rec 0.000792 | Seg 0.323049 | Elapsed 4.3m | ETA 1.1m
Epoch 202/500 | Batch 170/202 | Rec 0.000796 | Seg 0.324406 | Elapsed 4.5m | ETA 0.9m
Epoch 202/500 | Batch 180/202 | Rec 0.000781 | Seg 0.319166 | Elapsed 4.8m | ETA 0.6m
Epoch 202/500 | Batch 190/202 | Rec 0.000789 | Seg 0.327173 | Elapsed 5.0m | ETA 0.3m
Epoch 202/500 | Batch 200/202 | Rec 0.000793 | Seg 0.331878 | Elapsed 5.2m | ETA 0.1m
Epoch 202/500 | Batch 202/202 | Rec 0.000796 | Seg 0.333927 | Elapsed 5.3m | ETA 0.0m

2026-09-23 16:06:36,858 - INFO: Rec loss: 0.0007960068483809286
2026-09-23 16:06:36,858 - INFO: Seg loss: 0.3339267494249167
2026-09-23 16:06:36,858 - INFO: λ_rec: 1
2026-09-23 16:06:36,858 - INFO: λ_seg: 0.0001
2026-09-23 16:07:57,020 - INFO: -------------------Epoch: 202------------------------
2026-09-23 16:07:57,023 - INFO:
Validation stats:
        PSNR   SSIM      MSE
0  38.142203  0.972  0.00016
2026-09-23 16:07:57,031 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995469  0.997679  0.996854  0.998607  0.995673
real potato   0.894482  0.944252  0.972436  0.917751  0.999870
fake potato   0.840008  0.912998  0.930420  0.896313  0.999876
real apple    0.647957  0.786328  0.983531  0.655064  0.998772
fake apple    0.577833  0.732392  0.986716  0.582363  0.998394
real orange   0.641307  0.781411  0.995341  0.643238  0.999526
fake orange   0.830828  0.907548  0.846701  0.977934  0.999430
real grape    0.670076  0.802401  0.916956  0.713367  0.999267
fake grape    0.851186  0.919562  0.929176  0.910242  0.999411
real lemon    0.240138  0.387228  0.445948  0.342249  0.998727
fake lemon    0.774712  0.873007  0.998607  0.775550  0.999523
real avocado  0.811775  0.896060  0.854589  0.941872  0.999797
fake avocado  0.364992  0.534751  0.999302  0.365085  0.999240
real pepper   0.799030  0.888240  0.876477  0.900425  0.999172
fake pepper   0.879501  0.935838  0.988952  0.888227  0.999710
real plant    0.862122  0.925906  0.915552  0.936600  0.998502
fake plant    0.811467  0.895873  0.854533  0.941526  0.999826
real banana   0.463581  0.633445  0.954216  0.474127  0.998767
fake banana   0.506186  0.672095  0.557971  0.845056  0.998483
real onion    0.628584  0.771891  0.642633  0.966391  0.999484
fake onion    0.885165  0.939035  0.920753  0.958162  0.999922
real unknown  0.692255  0.818096  0.710767  0.963740  0.999931
fake unknown  0.173450  0.295592  0.184319  0.746288  0.997003
total         0.688787  0.793549  0.846207  0.797399  0.999057
total(-bg)    0.674847  0.784270  0.839359  0.788253  0.999211
2026-09-23 16:07:57,740 - INFO: Epoch accounting: {'epoch': 202, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11430027, 45556, 74011, 95174, 127153, 76606, 59655, 109915, 121174, 64855, 33059, 55228, 60483, 195730, 108146, 194475, 25171, 94953, 63611, 83929, 50884, 7298, 61179], 'crops_with_class': [202, 31, 33, 30, 37, 21, 23, 22, 30, 30, 13, 18, 22, 48, 30, 28, 22, 28, 26, 38, 25, 9, 25], 'targeted_crops_by_class': [0, 5, 7, 4, 4, 3, 5, 2, 7, 9, 3, 5, 8, 3, 3, 3, 7, 1, 2, 5, 7, 4, 5], 'sampled_scene_counts': [2, 1, 1, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0, 2, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 2, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 0, 0, 1, 2, 0, 1, 1, 2, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 3, 1, 2, 0, 1, 2, 4, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 0, 0, 1, 1, 0, 0, 2, 0, 1, 2, 0, 2, 1, 1, 3, 1, 2, 1, 1, 1, 0, 2, 2, 1, 1, 2, 1, 3, 2, 4, 0, 0, 2, 2, 3, 2, 3, 1, 2, 2, 3, 2, 1, 4, 1, 4, 1, 1, 2, 2, 1, 1, 0, 0, 1, 1, 2, 1, 1, 4, 0, 1, 0, 1, 0, 2, 3, 3, 0, 1, 0, 0, 0, 0, 2, 1, 2], 'learning_rate': 6.523888407293454e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0007960068483809286, 'train_segmentation_loss': 0.3339267494249167, 'val_foreground_miou_all22': 0.67484703621271, 'val_psnr_ref1': 38.14220321655274, 'elapsed_seconds': 398.4701383113861, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 203/500 | Batch 10/202 | Rec 0.000820 | Seg 0.412941 | Elapsed 0.2m | ETA 4.1m
Epoch 203/500 | Batch 20/202 | Rec 0.000819 | Seg 0.367423 | Elapsed 0.4m | ETA 3.8m
Epoch 203/500 | Batch 30/202 | Rec 0.000822 | Seg 0.385795 | Elapsed 0.7m | ETA 3.8m
Epoch 203/500 | Batch 40/202 | Rec 0.000838 | Seg 0.403958 | Elapsed 0.9m | ETA 3.7m
Epoch 203/500 | Batch 50/202 | Rec 0.000820 | Seg 0.380375 | Elapsed 1.2m | ETA 3.5m
Epoch 203/500 | Batch 60/202 | Rec 0.000798 | Seg 0.359090 | Elapsed 1.4m | ETA 3.4m
Epoch 203/500 | Batch 70/202 | Rec 0.000776 | Seg 0.345393 | Elapsed 1.6m | ETA 3.1m
Epoch 203/500 | Batch 80/202 | Rec 0.000791 | Seg 0.354486 | Elapsed 1.9m | ETA 2.9m
Epoch 203/500 | Batch 90/202 | Rec 0.000798 | Seg 0.351222 | Elapsed 2.1m | ETA 2.7m
Epoch 203/500 | Batch 100/202 | Rec 0.000793 | Seg 0.347564 | Elapsed 2.4m | ETA 2.4m
Epoch 203/500 | Batch 110/202 | Rec 0.000780 | Seg 0.349785 | Elapsed 2.6m | ETA 2.2m
Epoch 203/500 | Batch 120/202 | Rec 0.000769 | Seg 0.344392 | Elapsed 2.8m | ETA 1.9m
Epoch 203/500 | Batch 130/202 | Rec 0.000762 | Seg 0.343885 | Elapsed 3.0m | ETA 1.7m
Epoch 203/500 | Batch 140/202 | Rec 0.000765 | Seg 0.341955 | Elapsed 3.3m | ETA 1.4m
Epoch 203/500 | Batch 150/202 | Rec 0.000771 | Seg 0.343645 | Elapsed 3.5m | ETA 1.2m
Epoch 203/500 | Batch 160/202 | Rec 0.000778 | Seg 0.345185 | Elapsed 3.7m | ETA 1.0m
Epoch 203/500 | Batch 170/202 | Rec 0.000778 | Seg 0.344181 | Elapsed 4.0m | ETA 0.7m
Epoch 203/500 | Batch 180/202 | Rec 0.000796 | Seg 0.348416 | Elapsed 4.2m | ETA 0.5m
Epoch 203/500 | Batch 190/202 | Rec 0.000805 | Seg 0.348772 | Elapsed 4.4m | ETA 0.3m
Epoch 203/500 | Batch 200/202 | Rec 0.000803 | Seg 0.346189 | Elapsed 4.6m | ETA 0.0m
Epoch 203/500 | Batch 202/202 | Rec 0.000805 | Seg 0.348424 | Elapsed 4.7m | ETA 0.0m

2026-09-23 16:12:38,095 - INFO: Rec loss: 0.0008051229373864267
2026-09-23 16:12:38,095 - INFO: Seg loss: 0.3484236751452531
2026-09-23 16:12:38,095 - INFO: λ_rec: 1
2026-09-23 16:12:38,095 - INFO: λ_seg: 0.0001
2026-09-23 16:13:58,722 - INFO: -------------------Epoch: 203------------------------
2026-09-23 16:13:58,727 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.039569  0.971905  0.000164
2026-09-23 16:13:58,733 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994862  0.997374  0.995727  0.999127  0.995088
real potato   0.463284  0.633168  0.999450  0.463402  0.999358
fake potato   0.679641  0.809221  0.961649  0.698576  0.999760
real apple    0.663520  0.797680  0.802822  0.792702  0.998613
fake apple    0.668260  0.801097  0.935218  0.700695  0.998687
real orange   0.744543  0.853519  0.996445  0.746526  0.999662
fake orange   0.871748  0.931430  0.899162  0.966208  0.999593
real grape    0.578549  0.732965  0.896177  0.620113  0.999057
fake grape    0.839441  0.912663  0.937543  0.889164  0.999371
real lemon    0.278449  0.435555  0.469003  0.406648  0.998762
fake lemon    0.830317  0.907244  0.981050  0.843851  0.999635
real avocado  0.826132  0.904739  0.887293  0.922988  0.999819
fake avocado  0.566363  0.723110  0.988069  0.570263  0.999478
real pepper   0.837879  0.911739  0.920175  0.903554  0.999361
fake pepper   0.828512  0.906165  0.989318  0.835990  0.999588
real plant    0.845078  0.915985  0.929233  0.903207  0.998344
fake plant    0.827715  0.905687  0.966717  0.851994  0.999859
real banana   0.407592  0.579092  0.982927  0.410498  0.998659
fake banana   0.522274  0.686126  0.613150  0.778948  0.998689
real onion    0.714870  0.833681  0.745835  0.945111  0.999659
fake onion    0.930506  0.963952  0.990309  0.939057  0.999956
real unknown  0.744557  0.853528  0.756637  0.979008  0.999946
fake unknown  0.196113  0.327881  0.215888  0.681637  0.997646
total         0.689574  0.796678  0.863469  0.776055  0.999069
total(-bg)    0.675697  0.787556  0.857458  0.765915  0.999250
2026-09-23 16:13:59,267 - INFO: Epoch accounting: {'epoch': 203, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11297730, 48416, 55247, 121885, 132274, 104389, 70963, 174692, 216846, 104703, 60849, 36939, 36382, 206270, 102003, 122829, 21872, 70501, 79868, 67856, 50800, 12991, 41967], 'crops_with_class': [202, 28, 29, 31, 38, 31, 27, 33, 40, 39, 28, 12, 15, 51, 33, 17, 22, 18, 30, 33, 21, 15, 18], 'targeted_crops_by_class': [0, 2, 5, 4, 6, 11, 7, 6, 5, 5, 4, 4, 5, 5, 1, 4, 5, 1, 5, 8, 4, 5, 7], 'sampled_scene_counts': [1, 1, 0, 1, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 3, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 4, 2, 3, 1, 0, 1, 2, 1, 1, 2, 1, 1, 1, 2, 3, 0, 1, 4, 0, 2, 0, 1, 0, 2, 1, 2, 3, 1, 2, 3, 1, 1, 1, 2, 0, 3, 3, 3, 1, 3, 1, 5, 1, 2, 1, 2, 0, 1, 2, 0, 0, 0, 3, 2, 1, 1, 1, 2, 1, 3, 1, 1, 2, 1, 2, 1, 3, 1, 2, 1, 2, 3, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0], 'learning_rate': 6.493994888115455e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008051229373864267, 'train_segmentation_loss': 0.3484236751452531, 'val_foreground_miou_all22': 0.675697334825571, 'val_psnr_ref1': 38.039568786621096, 'elapsed_seconds': 361.51880645751953, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 204/500 | Batch 10/202 | Rec 0.000556 | Seg 0.273663 | Elapsed 0.2m | ETA 4.1m
Epoch 204/500 | Batch 20/202 | Rec 0.000709 | Seg 0.360319 | Elapsed 0.4m | ETA 3.8m
Epoch 204/500 | Batch 30/202 | Rec 0.000718 | Seg 0.335316 | Elapsed 0.6m | ETA 3.6m
Epoch 204/500 | Batch 40/202 | Rec 0.000749 | Seg 0.341768 | Elapsed 0.8m | ETA 3.4m
Epoch 204/500 | Batch 50/202 | Rec 0.000782 | Seg 0.354671 | Elapsed 1.1m | ETA 3.2m
Epoch 204/500 | Batch 60/202 | Rec 0.000776 | Seg 0.351509 | Elapsed 1.3m | ETA 3.0m
Epoch 204/500 | Batch 70/202 | Rec 0.000780 | Seg 0.355562 | Elapsed 1.5m | ETA 2.9m
Epoch 204/500 | Batch 80/202 | Rec 0.000822 | Seg 0.360407 | Elapsed 1.7m | ETA 2.6m
Epoch 204/500 | Batch 90/202 | Rec 0.000826 | Seg 0.361136 | Elapsed 1.9m | ETA 2.4m
Epoch 204/500 | Batch 100/202 | Rec 0.000832 | Seg 0.356020 | Elapsed 2.1m | ETA 2.2m
Epoch 204/500 | Batch 110/202 | Rec 0.000831 | Seg 0.359184 | Elapsed 2.4m | ETA 2.0m
Epoch 204/500 | Batch 120/202 | Rec 0.000836 | Seg 0.352686 | Elapsed 2.6m | ETA 1.8m
Epoch 204/500 | Batch 130/202 | Rec 0.000834 | Seg 0.348815 | Elapsed 2.8m | ETA 1.5m
Epoch 204/500 | Batch 140/202 | Rec 0.000830 | Seg 0.349427 | Elapsed 3.0m | ETA 1.3m
Epoch 204/500 | Batch 150/202 | Rec 0.000835 | Seg 0.355975 | Elapsed 3.2m | ETA 1.1m
Epoch 204/500 | Batch 160/202 | Rec 0.000838 | Seg 0.356344 | Elapsed 3.4m | ETA 0.9m
Epoch 204/500 | Batch 170/202 | Rec 0.000831 | Seg 0.353019 | Elapsed 3.7m | ETA 0.7m
Epoch 204/500 | Batch 180/202 | Rec 0.000827 | Seg 0.352381 | Elapsed 3.9m | ETA 0.5m
Epoch 204/500 | Batch 190/202 | Rec 0.000826 | Seg 0.350322 | Elapsed 4.1m | ETA 0.3m
Epoch 204/500 | Batch 200/202 | Rec 0.000829 | Seg 0.351545 | Elapsed 4.3m | ETA 0.0m
Epoch 204/500 | Batch 202/202 | Rec 0.000832 | Seg 0.352810 | Elapsed 4.3m | ETA 0.0m

2026-09-23 16:18:19,094 - INFO: Rec loss: 0.0008320022702313923
2026-09-23 16:18:19,094 - INFO: Seg loss: 0.35280973298272283
2026-09-23 16:18:19,095 - INFO: λ_rec: 1
2026-09-23 16:18:19,095 - INFO: λ_seg: 0.0001
2026-09-23 16:19:38,339 - INFO: -------------------Epoch: 204------------------------
2026-09-23 16:19:38,342 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.591074  0.971381  0.000181
2026-09-23 16:19:38,349 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995018  0.997453  0.996090  0.998919  0.995238
real potato   0.891206  0.942424  0.983638  0.904616  0.999868
fake potato   0.931600  0.964539  0.953726  0.975702  0.999948
real apple    0.692632  0.818360  0.977341  0.703936  0.998922
fake apple    0.621312  0.766384  0.984960  0.627263  0.998557
real orange   0.715617  0.834190  0.991548  0.720009  0.999623
fake orange   0.852122  0.920108  0.874760  0.970526  0.999518
real grape    0.411417  0.582939  0.837187  0.447197  0.998664
fake grape    0.766185  0.867566  0.859107  0.876294  0.999011
real lemon    0.311534  0.475018  0.509900  0.444690  0.998845
fake lemon    0.786002  0.880131  0.996625  0.788100  0.999546
real avocado  0.831678  0.908055  0.953905  0.866502  0.999837
fake avocado  0.004182  0.008327  0.402439  0.004208  0.998801
real pepper   0.848279  0.917862  0.923964  0.911939  0.999403
fake pepper   0.914433  0.955255  0.971851  0.939312  0.999790
real plant    0.825780  0.904528  0.905830  0.903329  0.998094
fake plant    0.812457  0.896475  0.895240  0.897814  0.999835
real banana   0.401519  0.572935  0.936239  0.412807  0.998617
fake banana   0.462647  0.632568  0.523683  0.798772  0.998293
real onion    0.676644  0.807092  0.701258  0.950684  0.999590
fake onion    0.901524  0.948162  0.938003  0.958646  0.999934
real unknown  0.722701  0.838983  0.745185  0.959924  0.999941
fake unknown  0.169357  0.289626  0.180465  0.733430  0.996969
total         0.675906  0.770825  0.827954  0.773679  0.998993
total(-bg)    0.661401  0.760524  0.820312  0.763441  0.999164
2026-09-23 16:19:38,879 - INFO: Epoch accounting: {'epoch': 204, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11295193, 60717, 63225, 119519, 158079, 80210, 75994, 125468, 198114, 63981, 41678, 41462, 21422, 205968, 119236, 149555, 17341, 81714, 85555, 101959, 67496, 16378, 48008], 'crops_with_class': [202, 33, 28, 32, 40, 24, 26, 27, 35, 27, 21, 14, 9, 59, 32, 20, 20, 24, 38, 44, 34, 17, 24], 'targeted_crops_by_class': [0, 7, 3, 6, 6, 3, 5, 6, 4, 2, 2, 4, 2, 6, 6, 3, 4, 4, 7, 5, 5, 9, 4], 'sampled_scene_counts': [1, 1, 0, 1, 2, 0, 0, 0, 3, 1, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 0, 3, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 0, 2, 2, 1, 0, 1, 1, 3, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 1, 2, 4, 0, 2, 0, 1, 2, 0, 1, 1, 1, 0, 3, 4, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 3, 1, 0, 0, 1, 2, 1, 1, 0, 2, 5, 1, 2, 2, 2, 5, 2, 1, 1, 1, 2, 2, 1, 0, 1, 3, 1, 1, 2, 3, 1, 1, 0, 0, 2, 2, 1, 1, 1, 1, 3, 3, 3, 0, 1, 1, 2, 6, 2, 0, 1, 2, 0, 0, 0, 1, 4], 'learning_rate': 6.464042882056e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008320022702313923, 'train_segmentation_loss': 0.35280973298272283, 'val_foreground_miou_all22': 0.6614012755020392, 'val_psnr_ref1': 37.59107437133789, 'elapsed_seconds': 339.6041429042816, 'peak_cuda_allocated_gib': 7.509067535400391}

Epoch 205/500 | Batch 10/202 | Rec 0.000673 | Seg 0.281984 | Elapsed 0.2m | ETA 4.1m
Epoch 205/500 | Batch 20/202 | Rec 0.000743 | Seg 0.338552 | Elapsed 0.4m | ETA 3.8m
Epoch 205/500 | Batch 30/202 | Rec 0.000854 | Seg 0.351763 | Elapsed 0.7m | ETA 3.8m
Epoch 205/500 | Batch 40/202 | Rec 0.000822 | Seg 0.339700 | Elapsed 0.9m | ETA 3.5m
Epoch 205/500 | Batch 50/202 | Rec 0.000829 | Seg 0.351746 | Elapsed 1.1m | ETA 3.3m
Epoch 205/500 | Batch 60/202 | Rec 0.000869 | Seg 0.358182 | Elapsed 1.3m | ETA 3.1m
Epoch 205/500 | Batch 70/202 | Rec 0.000871 | Seg 0.353646 | Elapsed 1.6m | ETA 2.9m
Epoch 205/500 | Batch 80/202 | Rec 0.000876 | Seg 0.355152 | Elapsed 1.8m | ETA 2.7m
Epoch 205/500 | Batch 90/202 | Rec 0.000853 | Seg 0.352876 | Elapsed 2.0m | ETA 2.5m
Epoch 205/500 | Batch 100/202 | Rec 0.000839 | Seg 0.349485 | Elapsed 2.2m | ETA 2.3m
Epoch 205/500 | Batch 110/202 | Rec 0.000835 | Seg 0.350770 | Elapsed 2.4m | ETA 2.0m
Epoch 205/500 | Batch 120/202 | Rec 0.000818 | Seg 0.342353 | Elapsed 2.7m | ETA 1.8m
Epoch 205/500 | Batch 130/202 | Rec 0.000821 | Seg 0.337407 | Elapsed 2.9m | ETA 1.6m
Epoch 205/500 | Batch 140/202 | Rec 0.000812 | Seg 0.335176 | Elapsed 3.1m | ETA 1.4m
Epoch 205/500 | Batch 150/202 | Rec 0.000813 | Seg 0.332954 | Elapsed 3.3m | ETA 1.1m
Epoch 205/500 | Batch 160/202 | Rec 0.000833 | Seg 0.338732 | Elapsed 3.5m | ETA 0.9m
Epoch 205/500 | Batch 170/202 | Rec 0.000826 | Seg 0.337282 | Elapsed 3.7m | ETA 0.7m
Epoch 205/500 | Batch 180/202 | Rec 0.000815 | Seg 0.334341 | Elapsed 3.9m | ETA 0.5m
Epoch 205/500 | Batch 190/202 | Rec 0.000812 | Seg 0.331607 | Elapsed 4.1m | ETA 0.3m
Epoch 205/500 | Batch 200/202 | Rec 0.000806 | Seg 0.329793 | Elapsed 4.4m | ETA 0.0m
Epoch 205/500 | Batch 202/202 | Rec 0.000807 | Seg 0.330611 | Elapsed 4.4m | ETA 0.0m

2026-09-23 16:24:02,596 - INFO: Rec loss: 0.0008071573237349085
2026-09-23 16:24:02,597 - INFO: Seg loss: 0.3306108995128681
2026-09-23 16:24:02,597 - INFO: λ_rec: 1
2026-09-23 16:24:02,597 - INFO: λ_seg: 0.0001
2026-09-23 16:25:24,250 - INFO: -------------------Epoch: 205------------------------
2026-09-23 16:25:24,254 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.845963  0.971346  0.000172
2026-09-23 16:25:24,260 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995281  0.997585  0.996474  0.998798  0.995491
real potato   0.373964  0.544318  0.999659  0.374012  0.999251
fake potato   0.689798  0.816378  0.980047  0.699623  0.999771
real apple    0.635639  0.777187  0.734359  0.825431  0.998368
fake apple    0.688335  0.815352  0.964718  0.706111  0.998793
real orange   0.724221  0.840007  0.994614  0.727073  0.999635
fake orange   0.865252  0.927709  0.884268  0.975749  0.999565
real grape    0.558694  0.716827  0.881249  0.604180  0.999004
fake grape    0.854049  0.921230  0.935419  0.907561  0.999426
real lemon    0.423296  0.594763  0.495418  0.744092  0.998809
fake lemon    0.808128  0.893834  0.943723  0.849044  0.999574
real avocado  0.813858  0.897328  0.852728  0.946962  0.999799
fake avocado  0.499810  0.666453  0.988221  0.502805  0.999398
real pepper   0.804517  0.891620  0.883044  0.900467  0.999200
fake pepper   0.829991  0.907048  0.927487  0.887587  0.999567
real plant    0.818673  0.900247  0.888130  0.912802  0.997978
fake plant    0.646076  0.784940  0.707021  0.882285  0.999615
real banana   0.439204  0.610299  0.930809  0.454027  0.998697
fake banana   0.665845  0.799358  0.753561  0.851194  0.999214
real onion    0.495380  0.662498  0.729785  0.606654  0.999442
fake onion    0.956595  0.977766  0.996984  0.959371  0.999973
real unknown  0.937616  0.967754  0.974830  0.960878  0.999990
fake unknown  0.180311  0.305487  0.226640  0.468671  0.998205
total         0.682806  0.791999  0.855182  0.771538  0.999077
total(-bg)    0.668602  0.782655  0.848760  0.761208  0.999240
2026-09-23 16:25:24,810 - INFO: Epoch accounting: {'epoch': 205, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11397739, 42845, 52914, 155133, 126356, 104850, 67305, 134169, 145296, 74916, 67286, 47715, 30861, 198278, 131962, 134324, 36961, 64717, 60276, 69178, 38503, 10273, 46415], 'crops_with_class': [202, 25, 22, 40, 31, 31, 23, 32, 29, 35, 28, 19, 15, 49, 32, 21, 32, 20, 24, 27, 18, 10, 21], 'targeted_crops_by_class': [0, 3, 1, 5, 5, 5, 1, 7, 4, 4, 5, 6, 5, 4, 3, 3, 8, 4, 5, 2, 4, 3, 4], 'sampled_scene_counts': [1, 2, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 2, 2, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 0, 0, 1, 2, 0, 0, 2, 2, 0, 0, 0, 1, 0, 1, 1, 2, 1, 1, 0, 1, 1, 2, 1, 1, 1, 2, 1, 0, 1, 1, 0, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 2, 1, 3, 1, 2, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 2, 2, 3, 0, 1, 2, 0, 0, 2, 0, 0, 3, 1, 3, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 3, 2, 1, 1, 3, 1, 0, 1, 2, 3, 1, 1, 2, 3, 3, 1, 4, 2, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1, 3, 3, 0, 2, 1, 0, 0, 1, 3, 0, 1, 2, 1, 1, 1, 1, 0, 0, 2, 2, 1], 'learning_rate': 6.434033571569e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008071573237349085, 'train_segmentation_loss': 0.3306108995128681, 'val_foreground_miou_all22': 0.6686023449013385, 'val_psnr_ref1': 37.845962829589844, 'elapsed_seconds': 345.9211730957031, 'peak_cuda_allocated_gib': 7.5117950439453125}

Epoch 206/500 | Batch 10/202 | Rec 0.000672 | Seg 0.336882 | Elapsed 0.2m | ETA 4.0m
Epoch 206/500 | Batch 20/202 | Rec 0.000754 | Seg 0.347572 | Elapsed 0.4m | ETA 3.9m
Epoch 206/500 | Batch 30/202 | Rec 0.000758 | Seg 0.362735 | Elapsed 0.6m | ETA 3.6m
Epoch 206/500 | Batch 40/202 | Rec 0.000749 | Seg 0.355129 | Elapsed 0.8m | ETA 3.4m
Epoch 206/500 | Batch 50/202 | Rec 0.000777 | Seg 0.364034 | Elapsed 1.0m | ETA 3.2m
Epoch 206/500 | Batch 60/202 | Rec 0.000765 | Seg 0.349459 | Elapsed 1.3m | ETA 3.0m
Epoch 206/500 | Batch 70/202 | Rec 0.000782 | Seg 0.344887 | Elapsed 1.5m | ETA 2.8m
Epoch 206/500 | Batch 80/202 | Rec 0.000787 | Seg 0.352312 | Elapsed 1.7m | ETA 2.6m
Epoch 206/500 | Batch 90/202 | Rec 0.000818 | Seg 0.358042 | Elapsed 1.9m | ETA 2.3m
Epoch 206/500 | Batch 100/202 | Rec 0.000809 | Seg 0.352119 | Elapsed 2.1m | ETA 2.1m
Epoch 206/500 | Batch 110/202 | Rec 0.000809 | Seg 0.357601 | Elapsed 2.3m | ETA 1.9m
Epoch 206/500 | Batch 120/202 | Rec 0.000787 | Seg 0.347638 | Elapsed 2.5m | ETA 1.7m
Epoch 206/500 | Batch 130/202 | Rec 0.000773 | Seg 0.342032 | Elapsed 2.8m | ETA 1.5m
Epoch 206/500 | Batch 140/202 | Rec 0.000797 | Seg 0.358382 | Elapsed 3.0m | ETA 1.3m
Epoch 206/500 | Batch 150/202 | Rec 0.000789 | Seg 0.355635 | Elapsed 3.2m | ETA 1.1m
Epoch 206/500 | Batch 160/202 | Rec 0.000792 | Seg 0.360616 | Elapsed 3.4m | ETA 0.9m
Epoch 206/500 | Batch 170/202 | Rec 0.000796 | Seg 0.363718 | Elapsed 3.6m | ETA 0.7m
Epoch 206/500 | Batch 180/202 | Rec 0.000801 | Seg 0.361542 | Elapsed 3.8m | ETA 0.5m
Epoch 206/500 | Batch 190/202 | Rec 0.000807 | Seg 0.359844 | Elapsed 4.0m | ETA 0.3m
Epoch 206/500 | Batch 200/202 | Rec 0.000811 | Seg 0.359635 | Elapsed 4.2m | ETA 0.0m
Epoch 206/500 | Batch 202/202 | Rec 0.000811 | Seg 0.359480 | Elapsed 4.3m | ETA 0.0m

2026-09-23 16:29:41,157 - INFO: Rec loss: 0.0008105445219668339
2026-09-23 16:29:41,157 - INFO: Seg loss: 0.35948028979767666
2026-09-23 16:29:41,157 - INFO: λ_rec: 1
2026-09-23 16:29:41,158 - INFO: λ_seg: 0.0001
2026-09-23 16:31:01,689 - INFO: -------------------Epoch: 206------------------------
2026-09-23 16:31:01,693 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.731823  0.969602  0.000176
2026-09-23 16:31:01,699 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994965  0.997426  0.995998  0.998958  0.995187
real potato   0.144733  0.252846  1.000000  0.144733  0.998977
fake potato   0.557282  0.715665  0.980678  0.563469  0.999674
real apple    0.617972  0.763836  0.693746  0.849801  0.998188
fake apple    0.835072  0.910074  0.942279  0.880092  0.999344
real orange   0.755368  0.860588  0.982180  0.765864  0.999673
fake orange   0.874325  0.932899  0.902135  0.965942  0.999603
real grape    0.670925  0.803009  0.930573  0.706278  0.999277
fake grape    0.796352  0.886582  0.906123  0.867962  0.999179
real lemon    0.321242  0.486227  0.378590  0.679564  0.998313
fake lemon    0.820900  0.901592  0.968215  0.843635  0.999611
real avocado  0.716937  0.835085  0.744093  0.951560  0.999651
fake avocado  0.334302  0.501050  0.972090  0.337541  0.999196
real pepper   0.812375  0.896426  0.908791  0.884490  0.999253
fake pepper   0.749968  0.857073  0.997874  0.751168  0.999403
real plant    0.843293  0.914935  0.916779  0.913199  0.998303
fake plant    0.786263  0.880294  0.859675  0.902032  0.999805
real banana   0.148161  0.258061  0.984248  0.148513  0.998081
fake banana   0.631664  0.774207  0.804815  0.745936  0.999200
real onion    0.559557  0.717534  0.718739  0.716433  0.999491
fake onion    0.949783  0.974195  0.998224  0.951391  0.999968
real unknown  0.960952  0.980037  0.998022  0.962786  0.999994
fake unknown  0.253653  0.404623  0.280022  0.729265  0.998192
total         0.658089  0.761055  0.863647  0.750461  0.999024
total(-bg)    0.642776  0.750311  0.857631  0.739166  0.999199
2026-09-23 16:31:02,209 - INFO: Epoch accounting: {'epoch': 206, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11286682, 44170, 46914, 104793, 151011, 85403, 92127, 157294, 214418, 83563, 79160, 60362, 47898, 158162, 121963, 196064, 27668, 73613, 44846, 71060, 31197, 16082, 43822], 'crops_with_class': [202, 24, 22, 29, 32, 29, 30, 29, 35, 36, 28, 21, 18, 41, 30, 21, 26, 21, 19, 32, 15, 16, 22], 'targeted_crops_by_class': [0, 3, 3, 3, 6, 7, 5, 4, 7, 1, 6, 8, 8, 4, 5, 8, 3, 7, 5, 4, 2, 4, 1], 'sampled_scene_counts': [1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 1, 2, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 0, 2, 0, 1, 2, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 3, 0, 1, 1, 0, 1, 1, 1, 2, 1, 0, 3, 0, 1, 2, 3, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 0, 1, 2, 3, 0, 1, 1, 2, 0, 1, 2, 1, 0, 2, 2, 1, 4, 2, 2, 1, 1, 0, 1, 2, 1, 1, 5, 1, 0, 1, 2, 0, 3, 0, 1, 0, 3, 2, 1, 2, 1, 1, 5, 3, 1, 1, 3, 1, 1, 1, 0, 0, 0, 4, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 5, 2, 2, 1, 1, 0, 0, 1, 2, 0, 2], 'learning_rate': 6.403968141370651e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008105445219668339, 'train_segmentation_loss': 0.35948028979767666, 'val_foreground_miou_all22': 0.6427762854458581, 'val_psnr_ref1': 37.731823425292966, 'elapsed_seconds': 337.392117023468, 'peak_cuda_allocated_gib': 7.515178680419922}

Epoch 207/500 | Batch 10/202 | Rec 0.000815 | Seg 0.356244 | Elapsed 0.2m | ETA 4.0m
Epoch 207/500 | Batch 20/202 | Rec 0.000819 | Seg 0.309042 | Elapsed 0.4m | ETA 3.8m
Epoch 207/500 | Batch 30/202 | Rec 0.000809 | Seg 0.342229 | Elapsed 0.6m | ETA 3.5m
Epoch 207/500 | Batch 40/202 | Rec 0.000822 | Seg 0.339854 | Elapsed 0.8m | ETA 3.4m
Epoch 207/500 | Batch 50/202 | Rec 0.000806 | Seg 0.342764 | Elapsed 1.0m | ETA 3.2m
Epoch 207/500 | Batch 60/202 | Rec 0.000823 | Seg 0.349870 | Elapsed 1.2m | ETA 3.0m
Epoch 207/500 | Batch 70/202 | Rec 0.000813 | Seg 0.345710 | Elapsed 1.5m | ETA 2.8m
Epoch 207/500 | Batch 80/202 | Rec 0.000813 | Seg 0.348814 | Elapsed 1.7m | ETA 2.5m
Epoch 207/500 | Batch 90/202 | Rec 0.000824 | Seg 0.357721 | Elapsed 1.9m | ETA 2.3m
Epoch 207/500 | Batch 100/202 | Rec 0.000823 | Seg 0.358257 | Elapsed 2.1m | ETA 2.1m
Epoch 207/500 | Batch 110/202 | Rec 0.000824 | Seg 0.356668 | Elapsed 2.3m | ETA 1.9m
Epoch 207/500 | Batch 120/202 | Rec 0.000807 | Seg 0.353221 | Elapsed 2.5m | ETA 1.7m
Epoch 207/500 | Batch 130/202 | Rec 0.000811 | Seg 0.356972 | Elapsed 2.7m | ETA 1.5m
Epoch 207/500 | Batch 140/202 | Rec 0.000802 | Seg 0.348498 | Elapsed 2.9m | ETA 1.3m
Epoch 207/500 | Batch 150/202 | Rec 0.000803 | Seg 0.349806 | Elapsed 3.1m | ETA 1.1m
Epoch 207/500 | Batch 160/202 | Rec 0.000809 | Seg 0.352225 | Elapsed 3.3m | ETA 0.9m
Epoch 207/500 | Batch 170/202 | Rec 0.000810 | Seg 0.354677 | Elapsed 3.5m | ETA 0.7m
Epoch 207/500 | Batch 180/202 | Rec 0.000806 | Seg 0.353930 | Elapsed 3.7m | ETA 0.5m
Epoch 207/500 | Batch 190/202 | Rec 0.000807 | Seg 0.354672 | Elapsed 4.0m | ETA 0.2m
Epoch 207/500 | Batch 200/202 | Rec 0.000803 | Seg 0.353188 | Elapsed 4.2m | ETA 0.0m
Epoch 207/500 | Batch 202/202 | Rec 0.000801 | Seg 0.353326 | Elapsed 4.2m | ETA 0.0m

2026-09-23 16:35:14,830 - INFO: Rec loss: 0.0008006989202372232
2026-09-23 16:35:14,830 - INFO: Seg loss: 0.3533263569974368
2026-09-23 16:35:14,830 - INFO: λ_rec: 1
2026-09-23 16:35:14,830 - INFO: λ_seg: 0.0001
2026-09-23 16:36:34,613 - INFO: -------------------Epoch: 207------------------------
2026-09-23 16:36:34,617 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.674922  0.971888  0.000179
2026-09-23 16:36:34,624 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995054  0.997471  0.996029  0.999017  0.995273
real potato   0.566386  0.723130  0.998652  0.566820  0.999481
fake potato   0.802926  0.890642  0.963902  0.827817  0.999852
real apple    0.688180  0.815242  0.808712  0.821981  0.998715
fake apple    0.698177  0.822218  0.981661  0.707404  0.998845
real orange   0.700960  0.824145  0.982063  0.710051  0.999601
fake orange   0.843601  0.915117  0.872727  0.961944  0.999489
real grape    0.754943  0.860312  0.881712  0.840020  0.999431
fake grape    0.861946  0.925805  0.948550  0.904220  0.999464
real lemon    0.497516  0.664408  0.547381  0.845235  0.998997
fake lemon    0.818308  0.900027  0.957544  0.849116  0.999601
real avocado  0.765861  0.867358  0.823903  0.915764  0.999740
fake avocado  0.663636  0.797766  0.965923  0.679546  0.999588
real pepper   0.801643  0.889852  0.888478  0.891332  0.999193
fake pepper   0.781065  0.877027  0.952370  0.812816  0.999457
real plant    0.849410  0.918524  0.950632  0.888608  0.998424
fake plant    0.749350  0.856668  0.830722  0.884394  0.999765
real banana   0.486483  0.654497  0.935166  0.503463  0.998806
fake banana   0.715015  0.833780  0.843127  0.824735  0.999395
real onion    0.600660  0.750465  0.763227  0.738220  0.999557
fake onion    0.962545  0.980865  0.992572  0.969528  0.999976
real unknown  0.901978  0.948413  0.940019  0.957061  0.999983
fake unknown  0.217894  0.357778  0.260062  0.573343  0.998266
total         0.727110  0.829196  0.873267  0.811845  0.999170
total(-bg)    0.714931  0.821547  0.867687  0.803337  0.999347
2026-09-23 16:36:35,186 - INFO: Epoch accounting: {'epoch': 207, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11258098, 38849, 55467, 108087, 150361, 80397, 77673, 144149, 166866, 72745, 66569, 63340, 45336, 250450, 158008, 122244, 23271, 82213, 81377, 91778, 45111, 12059, 43824], 'crops_with_class': [202, 26, 25, 31, 33, 23, 28, 27, 35, 31, 26, 22, 17, 62, 35, 16, 21, 24, 33, 38, 26, 11, 18], 'targeted_crops_by_class': [0, 3, 7, 4, 7, 2, 6, 5, 7, 6, 4, 6, 5, 9, 9, 4, 5, 2, 5, 5, 4, 4, 1], 'sampled_scene_counts': [0, 0, 3, 0, 2, 0, 1, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 2, 0, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 2, 0, 0, 1, 0, 3, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 2, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 4, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 1, 2, 0, 1, 1, 1, 0, 0, 2, 2, 1, 2, 1, 4, 1, 2, 1, 0, 2, 1, 0, 1, 1, 2, 2, 2, 3, 2, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 1, 3, 0, 0, 1, 1, 2, 1, 1, 4, 2, 3, 3, 0, 2, 1, 2, 2, 1, 2, 0, 2, 3, 1, 3, 1, 2, 0, 0, 0, 3, 1, 0, 0, 1, 3, 1, 2, 2, 0, 3, 2, 2, 0, 1, 1, 4, 1, 0, 0, 1, 1], 'learning_rate': 6.373847778392654e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008006989202372232, 'train_segmentation_loss': 0.3533263569974368, 'val_foreground_miou_all22': 0.7149311235706229, 'val_psnr_ref1': 37.67492172241211, 'elapsed_seconds': 332.9681465625763, 'peak_cuda_allocated_gib': 7.516544342041016}

Epoch 208/500 | Batch 10/202 | Rec 0.001004 | Seg 0.348162 | Elapsed 0.2m | ETA 4.1m
Epoch 208/500 | Batch 20/202 | Rec 0.000988 | Seg 0.328682 | Elapsed 0.4m | ETA 3.9m
Epoch 208/500 | Batch 30/202 | Rec 0.001029 | Seg 0.360810 | Elapsed 0.6m | ETA 3.7m
Epoch 208/500 | Batch 40/202 | Rec 0.000960 | Seg 0.357141 | Elapsed 0.8m | ETA 3.4m
Epoch 208/500 | Batch 50/202 | Rec 0.000938 | Seg 0.359350 | Elapsed 1.1m | ETA 3.2m
Epoch 208/500 | Batch 60/202 | Rec 0.000925 | Seg 0.350787 | Elapsed 1.3m | ETA 3.0m
Epoch 208/500 | Batch 70/202 | Rec 0.000871 | Seg 0.345039 | Elapsed 1.5m | ETA 2.8m
Epoch 208/500 | Batch 80/202 | Rec 0.000864 | Seg 0.347611 | Elapsed 1.7m | ETA 2.6m
Epoch 208/500 | Batch 90/202 | Rec 0.000878 | Seg 0.357839 | Elapsed 1.9m | ETA 2.3m
Epoch 208/500 | Batch 100/202 | Rec 0.000865 | Seg 0.355175 | Elapsed 2.1m | ETA 2.1m
Epoch 208/500 | Batch 110/202 | Rec 0.000857 | Seg 0.351500 | Elapsed 2.3m | ETA 1.9m
Epoch 208/500 | Batch 120/202 | Rec 0.000858 | Seg 0.351372 | Elapsed 2.5m | ETA 1.7m
Epoch 208/500 | Batch 130/202 | Rec 0.000848 | Seg 0.354252 | Elapsed 2.7m | ETA 1.5m
Epoch 208/500 | Batch 140/202 | Rec 0.000843 | Seg 0.355345 | Elapsed 2.9m | ETA 1.3m
Epoch 208/500 | Batch 150/202 | Rec 0.000829 | Seg 0.347410 | Elapsed 3.1m | ETA 1.1m
Epoch 208/500 | Batch 160/202 | Rec 0.000817 | Seg 0.343175 | Elapsed 3.4m | ETA 0.9m
Epoch 208/500 | Batch 170/202 | Rec 0.000818 | Seg 0.347459 | Elapsed 3.6m | ETA 0.7m
Epoch 208/500 | Batch 180/202 | Rec 0.000814 | Seg 0.344873 | Elapsed 3.8m | ETA 0.5m
Epoch 208/500 | Batch 190/202 | Rec 0.000809 | Seg 0.343713 | Elapsed 4.0m | ETA 0.3m
Epoch 208/500 | Batch 200/202 | Rec 0.000811 | Seg 0.342450 | Elapsed 4.2m | ETA 0.0m
Epoch 208/500 | Batch 202/202 | Rec 0.000809 | Seg 0.342652 | Elapsed 4.3m | ETA 0.0m

2026-09-23 16:40:50,769 - INFO: Rec loss: 0.0008094477431795624
2026-09-23 16:40:50,769 - INFO: Seg loss: 0.3426515709350605
2026-09-23 16:40:50,770 - INFO: λ_rec: 1
2026-09-23 16:40:50,770 - INFO: λ_seg: 0.0001
2026-09-23 16:42:15,487 - INFO: -------------------Epoch: 208------------------------
2026-09-23 16:42:15,490 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.993066  0.971416  0.000165
2026-09-23 16:42:15,497 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995178  0.997533  0.996511  0.998658  0.995394
real potato   0.837927  0.911768  0.857801  0.973094  0.999775
fake potato   0.931634  0.964557  0.942623  0.987641  0.999947
real apple    0.571498  0.727283  0.997380  0.572357  0.998519
fake apple    0.584087  0.737396  0.962206  0.597801  0.998393
real orange   0.840233  0.913132  0.985513  0.850741  0.999787
fake orange   0.907842  0.951645  0.932352  0.971858  0.999718
real grape    0.706170  0.827734  0.843058  0.813053  0.999294
fake grape    0.871292  0.931170  0.964385  0.900260  0.999508
real lemon    0.554013  0.712960  0.817983  0.631914  0.999402
fake lemon    0.770518  0.870338  0.999906  0.770573  0.999514
real avocado  0.919127  0.957810  0.998930  0.920033  0.999925
fake avocado  0.072303  0.134843  1.000000  0.072303  0.998890
real pepper   0.850213  0.918994  0.900060  0.938845  0.999395
fake pepper   0.920867  0.958753  0.957365  0.960246  0.999803
real plant    0.859034  0.924122  0.937891  0.910849  0.998505
fake plant    0.695219  0.820162  0.747398  0.908742  0.999683
real banana   0.755209  0.860485  0.937765  0.795056  0.999421
fake banana   0.614015  0.760805  0.715350  0.812541  0.999060
real onion    0.629886  0.772872  0.642873  0.968924  0.999486
fake onion    0.943396  0.970824  0.987006  0.955260  0.999964
real unknown  0.462749  0.632667  0.473261  0.954198  0.999823
fake unknown  0.160150  0.276053  0.173776  0.671315  0.997034
total         0.715329  0.805822  0.859626  0.823316  0.999141
total(-bg)    0.702608  0.797108  0.853404  0.815346  0.999311
2026-09-23 16:42:16,021 - INFO: Epoch accounting: {'epoch': 208, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11301916, 59514, 62114, 97103, 134527, 103041, 81276, 129968, 136886, 59960, 72113, 48487, 48197, 244368, 155733, 161597, 20883, 74468, 75993, 55117, 38617, 15807, 60587], 'crops_with_class': [202, 33, 25, 24, 34, 29, 24, 27, 31, 29, 28, 17, 17, 57, 38, 25, 22, 21, 31, 27, 20, 19, 26], 'targeted_crops_by_class': [0, 3, 3, 2, 2, 2, 5, 2, 4, 3, 5, 7, 8, 3, 5, 5, 3, 10, 6, 3, 4, 6, 8], 'sampled_scene_counts': [1, 0, 2, 0, 1, 3, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 1, 3, 1, 0, 0, 0, 1, 1, 0, 2, 2, 1, 1, 1, 1, 0, 0, 1, 2, 0, 2, 1, 0, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 1, 2, 1, 0, 0, 0, 2, 3, 1, 1, 2, 2, 4, 2, 2, 2, 2, 1, 2, 1, 0, 3, 2, 2, 0, 1, 1, 2, 0, 0, 2, 1, 0, 2, 1, 5, 5, 3, 1, 2, 0, 1, 2, 1, 1, 0, 1, 0, 0, 3, 1, 0, 0, 0, 3, 1, 1, 3, 3, 2, 2, 2, 1, 1, 2, 2, 3, 2, 1, 2, 1, 0, 2, 2, 1, 1, 2, 0], 'learning_rate': 6.343673671735367e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008094477431795624, 'train_segmentation_loss': 0.3426515709350605, 'val_foreground_miou_all22': 0.7026082263872273, 'val_psnr_ref1': 37.99306640625, 'elapsed_seconds': 340.82586145401, 'peak_cuda_allocated_gib': 7.509830474853516}

Epoch 209/500 | Batch 10/202 | Rec 0.001155 | Seg 0.338572 | Elapsed 0.2m | ETA 4.1m
Epoch 209/500 | Batch 20/202 | Rec 0.000960 | Seg 0.339132 | Elapsed 0.4m | ETA 3.8m
Epoch 209/500 | Batch 30/202 | Rec 0.000862 | Seg 0.325312 | Elapsed 0.6m | ETA 3.6m
Epoch 209/500 | Batch 40/202 | Rec 0.000855 | Seg 0.345992 | Elapsed 0.8m | ETA 3.4m
Epoch 209/500 | Batch 50/202 | Rec 0.000807 | Seg 0.333122 | Elapsed 1.1m | ETA 3.2m
Epoch 209/500 | Batch 60/202 | Rec 0.000797 | Seg 0.327111 | Elapsed 1.3m | ETA 3.0m
Epoch 209/500 | Batch 70/202 | Rec 0.000854 | Seg 0.339127 | Elapsed 1.5m | ETA 2.8m
Epoch 209/500 | Batch 80/202 | Rec 0.000871 | Seg 0.352845 | Elapsed 1.7m | ETA 2.6m
Epoch 209/500 | Batch 90/202 | Rec 0.000842 | Seg 0.342609 | Elapsed 1.9m | ETA 2.4m
Epoch 209/500 | Batch 100/202 | Rec 0.000834 | Seg 0.338330 | Elapsed 2.1m | ETA 2.2m
Epoch 209/500 | Batch 110/202 | Rec 0.000834 | Seg 0.338845 | Elapsed 2.3m | ETA 1.9m
Epoch 209/500 | Batch 120/202 | Rec 0.000818 | Seg 0.331449 | Elapsed 2.5m | ETA 1.7m
Epoch 209/500 | Batch 130/202 | Rec 0.000819 | Seg 0.333647 | Elapsed 2.8m | ETA 1.5m
Epoch 209/500 | Batch 140/202 | Rec 0.000819 | Seg 0.335172 | Elapsed 3.0m | ETA 1.3m
Epoch 209/500 | Batch 150/202 | Rec 0.000812 | Seg 0.330458 | Elapsed 3.2m | ETA 1.1m
Epoch 209/500 | Batch 160/202 | Rec 0.000795 | Seg 0.322961 | Elapsed 3.4m | ETA 0.9m
Epoch 209/500 | Batch 170/202 | Rec 0.000790 | Seg 0.323506 | Elapsed 3.6m | ETA 0.7m
Epoch 209/500 | Batch 180/202 | Rec 0.000790 | Seg 0.323527 | Elapsed 3.8m | ETA 0.5m
Epoch 209/500 | Batch 190/202 | Rec 0.000797 | Seg 0.323742 | Elapsed 4.1m | ETA 0.3m
Epoch 209/500 | Batch 200/202 | Rec 0.000800 | Seg 0.326428 | Elapsed 4.3m | ETA 0.0m
Epoch 209/500 | Batch 202/202 | Rec 0.000801 | Seg 0.327586 | Elapsed 4.3m | ETA 0.0m

2026-09-23 16:46:34,648 - INFO: Rec loss: 0.0008012722585653416
2026-09-23 16:46:34,648 - INFO: Seg loss: 0.327585560371085
2026-09-23 16:46:34,648 - INFO: λ_rec: 1
2026-09-23 16:46:34,648 - INFO: λ_seg: 0.0001
2026-09-23 16:47:59,014 - INFO: -------------------Epoch: 209------------------------
2026-09-23 16:47:59,018 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.224825  0.972519  0.000157
2026-09-23 16:47:59,027 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995414  0.997652  0.996830  0.998575  0.995620
real potato   0.601858  0.751403  0.996419  0.603162  0.999523
fake potato   0.956486  0.977709  0.979403  0.976121  0.999968
real apple    0.724456  0.840164  0.868451  0.813755  0.998932
fake apple    0.770333  0.870220  0.980989  0.782008  0.999120
real orange   0.734907  0.847151  0.985710  0.742821  0.999647
fake orange   0.861003  0.925261  0.884831  0.969673  0.999552
real grape    0.534866  0.696907  0.910634  0.564496  0.998975
fake grape    0.821914  0.902203  0.904422  0.900095  0.999279
real lemon    0.355248  0.524206  0.518269  0.530382  0.998869
fake lemon    0.829615  0.906824  0.993642  0.834043  0.999638
real avocado  0.849141  0.918367  0.875428  0.965846  0.999841
fake avocado  0.629653  0.772698  0.999595  0.629814  0.999557
real pepper   0.812285  0.896371  0.868969  0.925663  0.999218
fake pepper   0.855911  0.922312  0.972800  0.876896  0.999648
real plant    0.839578  0.912744  0.892065  0.934510  0.998214
fake plant    0.853891  0.921138  0.952498  0.891871  0.999879
real banana   0.426690  0.598110  0.905299  0.446625  0.998652
fake banana   0.539880  0.701148  0.605303  0.833195  0.998694
real onion    0.678925  0.808712  0.703523  0.951022  0.999594
fake onion    0.754918  0.860297  0.770216  0.974365  0.999800
real unknown  0.944656  0.971491  1.000000  0.944656  0.999991
fake unknown  0.241266  0.388698  0.291014  0.585295  0.998449
total         0.722300  0.822252  0.863318  0.811952  0.999159
total(-bg)    0.709885  0.814279  0.857249  0.803469  0.999320
2026-09-23 16:47:59,731 - INFO: Epoch accounting: {'epoch': 209, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11412335, 62019, 60539, 142910, 156748, 57627, 71641, 123273, 161437, 66819, 60419, 49219, 34989, 213872, 95703, 161579, 32761, 50075, 60070, 77292, 38176, 10546, 38223], 'crops_with_class': [202, 31, 29, 37, 34, 19, 26, 21, 27, 34, 30, 13, 13, 49, 30, 22, 27, 17, 24, 35, 21, 12, 18], 'targeted_crops_by_class': [0, 3, 7, 5, 3, 4, 4, 3, 3, 4, 6, 2, 3, 3, 3, 4, 7, 5, 3, 9, 2, 7, 2], 'sampled_scene_counts': [2, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 2, 0, 0, 1, 0, 2, 1, 3, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 0, 1, 0, 2, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 3, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 1, 4, 0, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 1, 2, 0, 1, 2, 1, 1, 0, 1, 0, 3, 1, 3, 1, 0, 3, 1, 1, 2, 0, 3, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 2, 1, 0, 1, 1, 4, 1, 0, 0, 2, 2, 3, 1, 1, 3, 2, 1, 2, 3, 1, 1, 1, 2, 1, 3, 2, 0, 0, 0, 2, 0, 1, 2, 0, 3, 1, 1, 1, 1, 1, 1, 0, 0, 4, 0, 0, 1, 2, 1, 1, 1, 1], 'learning_rate': 6.313447012620853e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008012722585653416, 'train_segmentation_loss': 0.327585560371085, 'val_foreground_miou_all22': 0.7098854902593815, 'val_psnr_ref1': 38.22482528686523, 'elapsed_seconds': 343.70217967033386, 'peak_cuda_allocated_gib': 7.508068084716797}

Epoch 210/500 | Batch 10/202 | Rec 0.000678 | Seg 0.277587 | Elapsed 0.2m | ETA 4.2m
Epoch 210/500 | Batch 20/202 | Rec 0.000724 | Seg 0.308164 | Elapsed 0.4m | ETA 3.9m
Epoch 210/500 | Batch 30/202 | Rec 0.000721 | Seg 0.307193 | Elapsed 0.6m | ETA 3.6m
Epoch 210/500 | Batch 40/202 | Rec 0.000773 | Seg 0.312637 | Elapsed 0.8m | ETA 3.4m
Epoch 210/500 | Batch 50/202 | Rec 0.000783 | Seg 0.323295 | Elapsed 1.1m | ETA 3.2m
Epoch 210/500 | Batch 60/202 | Rec 0.000799 | Seg 0.332508 | Elapsed 1.3m | ETA 3.0m
Epoch 210/500 | Batch 70/202 | Rec 0.000809 | Seg 0.334664 | Elapsed 1.5m | ETA 2.8m
Epoch 210/500 | Batch 80/202 | Rec 0.000828 | Seg 0.327812 | Elapsed 1.7m | ETA 2.6m
Epoch 210/500 | Batch 90/202 | Rec 0.000828 | Seg 0.334371 | Elapsed 1.9m | ETA 2.4m
Epoch 210/500 | Batch 100/202 | Rec 0.000822 | Seg 0.327834 | Elapsed 2.1m | ETA 2.2m
Epoch 210/500 | Batch 110/202 | Rec 0.000820 | Seg 0.331053 | Elapsed 2.3m | ETA 1.9m
Epoch 210/500 | Batch 120/202 | Rec 0.000804 | Seg 0.328104 | Elapsed 2.5m | ETA 1.7m
Epoch 210/500 | Batch 130/202 | Rec 0.000808 | Seg 0.331088 | Elapsed 2.7m | ETA 1.5m
Epoch 210/500 | Batch 140/202 | Rec 0.000796 | Seg 0.326361 | Elapsed 3.0m | ETA 1.3m
Epoch 210/500 | Batch 150/202 | Rec 0.000803 | Seg 0.332469 | Elapsed 3.2m | ETA 1.1m
Epoch 210/500 | Batch 160/202 | Rec 0.000806 | Seg 0.332898 | Elapsed 3.4m | ETA 0.9m
Epoch 210/500 | Batch 170/202 | Rec 0.000797 | Seg 0.328685 | Elapsed 3.6m | ETA 0.7m
Epoch 210/500 | Batch 180/202 | Rec 0.000793 | Seg 0.328725 | Elapsed 3.8m | ETA 0.5m
Epoch 210/500 | Batch 190/202 | Rec 0.000789 | Seg 0.325830 | Elapsed 4.0m | ETA 0.3m
Epoch 210/500 | Batch 200/202 | Rec 0.000791 | Seg 0.325384 | Elapsed 4.2m | ETA 0.0m
Epoch 210/500 | Batch 202/202 | Rec 0.000791 | Seg 0.325810 | Elapsed 4.3m | ETA 0.0m

2026-09-23 16:52:15,476 - INFO: Rec loss: 0.0007906950896981606
2026-09-23 16:52:15,476 - INFO: Seg loss: 0.32581037428635773
2026-09-23 16:52:15,476 - INFO: λ_rec: 1
2026-09-23 16:52:15,476 - INFO: λ_seg: 0.0001
2026-09-23 16:53:37,715 - INFO: -------------------Epoch: 210------------------------
2026-09-23 16:53:37,718 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.918942  0.971887  0.000168
2026-09-23 16:53:37,724 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995125  0.997507  0.996172  0.998945  0.995341
real potato   0.492796  0.660188  0.999741  0.492859  0.999393
fake potato   0.885316  0.939120  0.975406  0.905530  0.999915
real apple    0.692039  0.817944  0.805219  0.831181  0.998724
fake apple    0.646783  0.785463  0.986677  0.652481  0.998655
real orange   0.595194  0.746187  0.988166  0.599467  0.999463
fake orange   0.812764  0.896663  0.838309  0.963863  0.999364
real grape    0.592458  0.744032  0.963079  0.606227  0.999129
fake grape    0.830925  0.907606  0.923905  0.891969  0.999329
real lemon    0.503650  0.669856  0.545084  0.868865  0.998994
fake lemon    0.841042  0.913609  0.987844  0.849838  0.999660
real avocado  0.843393  0.914994  0.897003  0.933826  0.999839
fake avocado  0.616080  0.762390  0.976503  0.625351  0.999534
real pepper   0.857578  0.923279  0.929931  0.916820  0.999443
fake pepper   0.893933  0.943946  0.959410  0.929070  0.999737
real plant    0.827359  0.905475  0.925614  0.886289  0.998150
fake plant    0.854056  0.921234  0.918126  0.924463  0.999874
real banana   0.360751  0.530183  0.932012  0.370501  0.998525
fake banana   0.624090  0.768492  0.714052  0.832034  0.999078
real onion    0.687264  0.814599  0.730661  0.920453  0.999622
fake onion    0.924415  0.960673  0.957263  0.964208  0.999950
real unknown  0.950382  0.974510  1.000000  0.950382  0.999992
fake unknown  0.223904  0.365846  0.248113  0.696487  0.997966
total         0.719622  0.820165  0.878187  0.809179  0.999116
total(-bg)    0.707099  0.812104  0.872824  0.800553  0.999288
2026-09-23 16:53:38,244 - INFO: Epoch accounting: {'epoch': 210, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11411757, 51385, 55613, 122557, 127516, 80345, 52562, 151103, 132083, 65687, 63020, 34570, 32066, 220691, 119956, 121988, 26305, 85211, 100008, 76897, 61295, 11669, 33988], 'crops_with_class': [202, 30, 30, 31, 31, 25, 22, 26, 30, 29, 21, 13, 13, 54, 35, 20, 24, 25, 37, 37, 29, 13, 15], 'targeted_crops_by_class': [0, 5, 2, 7, 8, 6, 3, 9, 6, 4, 2, 2, 4, 5, 2, 3, 3, 7, 7, 5, 7, 3, 3], 'sampled_scene_counts': [2, 2, 1, 0, 0, 0, 0, 1, 1, 3, 0, 2, 2, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 2, 0, 1, 1, 1, 0, 1, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 5, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 2, 0, 2, 2, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 2, 0, 0, 2, 1, 1, 0, 2, 2, 1, 1, 3, 0, 3, 2, 1, 2, 3, 0, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 0, 2, 2, 3, 3, 0, 0, 1, 2, 5, 1, 1, 0, 1, 0, 3, 1, 1, 1, 3, 1, 1, 2, 1, 0, 1, 1, 4, 2, 3, 1, 0, 0, 5, 1, 1, 2, 0, 0, 0, 0, 3, 0, 1, 1], 'learning_rate': 6.283168994345863e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007906950896981606, 'train_segmentation_loss': 0.32581037428635773, 'val_foreground_miou_all22': 0.7070987297079069, 'val_psnr_ref1': 37.918941802978516, 'elapsed_seconds': 338.5048065185547, 'peak_cuda_allocated_gib': 7.506870269775391}

Epoch 211/500 | Batch 10/202 | Rec 0.000696 | Seg 0.336130 | Elapsed 0.2m | ETA 4.1m
Epoch 211/500 | Batch 20/202 | Rec 0.000693 | Seg 0.324308 | Elapsed 0.4m | ETA 3.9m
Epoch 211/500 | Batch 30/202 | Rec 0.000711 | Seg 0.340380 | Elapsed 0.6m | ETA 3.7m
Epoch 211/500 | Batch 40/202 | Rec 0.000710 | Seg 0.319316 | Elapsed 0.9m | ETA 3.5m
Epoch 211/500 | Batch 50/202 | Rec 0.000709 | Seg 0.332690 | Elapsed 1.1m | ETA 3.2m
Epoch 211/500 | Batch 60/202 | Rec 0.000739 | Seg 0.344068 | Elapsed 1.3m | ETA 3.0m
Epoch 211/500 | Batch 70/202 | Rec 0.000758 | Seg 0.346471 | Elapsed 1.5m | ETA 2.8m
Epoch 211/500 | Batch 80/202 | Rec 0.000789 | Seg 0.358999 | Elapsed 1.7m | ETA 2.6m
Epoch 211/500 | Batch 90/202 | Rec 0.000768 | Seg 0.345598 | Elapsed 1.9m | ETA 2.4m
Epoch 211/500 | Batch 100/202 | Rec 0.000760 | Seg 0.336888 | Elapsed 2.1m | ETA 2.2m
Epoch 211/500 | Batch 110/202 | Rec 0.000759 | Seg 0.332692 | Elapsed 2.3m | ETA 2.0m
Epoch 211/500 | Batch 120/202 | Rec 0.000776 | Seg 0.340240 | Elapsed 2.6m | ETA 1.7m
Epoch 211/500 | Batch 130/202 | Rec 0.000772 | Seg 0.340681 | Elapsed 2.8m | ETA 1.5m
Epoch 211/500 | Batch 140/202 | Rec 0.000773 | Seg 0.342811 | Elapsed 3.0m | ETA 1.3m
Epoch 211/500 | Batch 150/202 | Rec 0.000764 | Seg 0.339301 | Elapsed 3.2m | ETA 1.1m
Epoch 211/500 | Batch 160/202 | Rec 0.000771 | Seg 0.347413 | Elapsed 3.4m | ETA 0.9m
Epoch 211/500 | Batch 170/202 | Rec 0.000775 | Seg 0.351300 | Elapsed 3.6m | ETA 0.7m
Epoch 211/500 | Batch 180/202 | Rec 0.000776 | Seg 0.351880 | Elapsed 3.8m | ETA 0.5m
Epoch 211/500 | Batch 190/202 | Rec 0.000774 | Seg 0.349125 | Elapsed 4.0m | ETA 0.3m
Epoch 211/500 | Batch 200/202 | Rec 0.000770 | Seg 0.349512 | Elapsed 4.2m | ETA 0.0m
Epoch 211/500 | Batch 202/202 | Rec 0.000769 | Seg 0.349213 | Elapsed 4.3m | ETA 0.0m

2026-09-23 16:57:55,522 - INFO: Rec loss: 0.0007687117573764811
2026-09-23 16:57:55,522 - INFO: Seg loss: 0.3492129202010018
2026-09-23 16:57:55,522 - INFO: λ_rec: 1
2026-09-23 16:57:55,522 - INFO: λ_seg: 0.0001
2026-09-23 16:59:16,245 - INFO: -------------------Epoch: 211------------------------
2026-09-23 16:59:16,249 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.251511  0.972634  0.000156
2026-09-23 16:59:16,256 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995136  0.997512  0.996471  0.998655  0.995353
real potato   0.841939  0.914138  0.988293  0.850421  0.999809
fake potato   0.902359  0.948624  0.977556  0.921449  0.999927
real apple    0.744204  0.853295  0.946982  0.776559  0.999079
fake apple    0.665005  0.798754  0.980366  0.673982  0.998718
real orange   0.827063  0.905298  0.981599  0.840088  0.999769
fake orange   0.901102  0.947929  0.921413  0.976122  0.999693
real grape    0.597407  0.747922  0.887095  0.646569  0.999090
fake grape    0.862954  0.926386  0.953902  0.900507  0.999471
real lemon    0.466755  0.636398  0.517034  0.827577  0.998889
fake lemon    0.827883  0.905788  0.993203  0.832600  0.999634
real avocado  0.731025  0.844566  0.951822  0.759113  0.999740
fake avocado  0.350651  0.519189  0.798359  0.384723  0.999147
real pepper   0.812058  0.896232  0.874935  0.918697  0.999222
fake pepper   0.842394  0.914406  0.969923  0.864989  0.999614
real plant    0.832757  0.908698  0.909470  0.908027  0.998176
fake plant    0.803948  0.891271  0.877415  0.905675  0.999824
real banana   0.447308  0.618080  0.933461  0.462040  0.998717
fake banana   0.694771  0.819850  0.812225  0.827721  0.999331
real onion    0.658128  0.793772  0.679409  0.954568  0.999552
fake onion    0.933045  0.965313  0.991837  0.940266  0.999957
real unknown  0.672495  0.804133  0.694927  0.954198  0.999926
fake unknown  0.197233  0.329446  0.214757  0.707352  0.997574
total         0.722070  0.821174  0.863150  0.818778  0.999140
total(-bg)    0.709658  0.813158  0.857090  0.810602  0.999312
2026-09-23 16:59:16,966 - INFO: Epoch accounting: {'epoch': 211, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11302352, 60775, 54662, 89309, 144045, 80305, 83180, 146842, 169993, 66937, 59482, 35495, 41349, 189849, 90243, 231929, 22005, 94577, 73449, 95672, 51070, 13155, 41597], 'crops_with_class': [202, 31, 22, 24, 31, 29, 27, 27, 30, 33, 25, 13, 14, 50, 22, 28, 20, 27, 33, 41, 29, 16, 20], 'targeted_crops_by_class': [0, 5, 3, 2, 6, 5, 6, 5, 6, 3, 2, 4, 5, 1, 5, 9, 4, 7, 4, 3, 3, 7, 5], 'sampled_scene_counts': [0, 0, 0, 0, 1, 3, 0, 0, 0, 0, 2, 2, 0, 0, 2, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 2, 1, 3, 2, 0, 0, 0, 2, 2, 2, 1, 0, 0, 2, 2, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 0, 1, 2, 0, 1, 1, 0, 2, 2, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 3, 2, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 3, 1, 0, 0, 1, 1, 1, 1, 0, 2, 2, 1, 3, 1, 2, 1, 1, 0, 2, 1, 2, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 7, 2, 1, 1, 1, 3, 0, 2, 2, 2, 0, 0, 1, 0, 1, 3, 3, 0, 0, 1, 3, 0, 1, 1, 3, 2, 1, 1, 1, 2, 2, 1, 1, 3, 0, 5, 2, 2, 1, 0, 2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 2], 'learning_rate': 6.252840812234707e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007687117573764811, 'train_segmentation_loss': 0.3492129202010018, 'val_foreground_miou_all22': 0.7096583274556099, 'val_psnr_ref1': 38.25151062011719, 'elapsed_seconds': 338.713267326355, 'peak_cuda_allocated_gib': 7.5131378173828125}

Epoch 212/500 | Batch 10/202 | Rec 0.000810 | Seg 0.321608 | Elapsed 0.2m | ETA 4.0m
Epoch 212/500 | Batch 20/202 | Rec 0.000837 | Seg 0.337647 | Elapsed 0.4m | ETA 3.8m
Epoch 212/500 | Batch 30/202 | Rec 0.000770 | Seg 0.322408 | Elapsed 0.6m | ETA 3.6m
Epoch 212/500 | Batch 40/202 | Rec 0.000753 | Seg 0.315200 | Elapsed 0.8m | ETA 3.4m
Epoch 212/500 | Batch 50/202 | Rec 0.000751 | Seg 0.316664 | Elapsed 1.1m | ETA 3.2m
Epoch 212/500 | Batch 60/202 | Rec 0.000764 | Seg 0.320166 | Elapsed 1.3m | ETA 3.0m
Epoch 212/500 | Batch 70/202 | Rec 0.000764 | Seg 0.321347 | Elapsed 1.5m | ETA 2.8m
Epoch 212/500 | Batch 80/202 | Rec 0.000770 | Seg 0.321234 | Elapsed 1.7m | ETA 2.6m
Epoch 212/500 | Batch 90/202 | Rec 0.000780 | Seg 0.329414 | Elapsed 1.9m | ETA 2.4m
Epoch 212/500 | Batch 100/202 | Rec 0.000780 | Seg 0.330506 | Elapsed 2.1m | ETA 2.2m
Epoch 212/500 | Batch 110/202 | Rec 0.000797 | Seg 0.332502 | Elapsed 2.3m | ETA 1.9m
Epoch 212/500 | Batch 120/202 | Rec 0.000798 | Seg 0.332085 | Elapsed 2.5m | ETA 1.7m
Epoch 212/500 | Batch 130/202 | Rec 0.000804 | Seg 0.328255 | Elapsed 2.7m | ETA 1.5m
Epoch 212/500 | Batch 140/202 | Rec 0.000803 | Seg 0.323915 | Elapsed 2.9m | ETA 1.3m
Epoch 212/500 | Batch 150/202 | Rec 0.000809 | Seg 0.329762 | Elapsed 3.2m | ETA 1.1m
Epoch 212/500 | Batch 160/202 | Rec 0.000807 | Seg 0.330985 | Elapsed 3.4m | ETA 0.9m
Epoch 212/500 | Batch 170/202 | Rec 0.000815 | Seg 0.337124 | Elapsed 3.6m | ETA 0.7m
Epoch 212/500 | Batch 180/202 | Rec 0.000809 | Seg 0.336624 | Elapsed 3.8m | ETA 0.5m
Epoch 212/500 | Batch 190/202 | Rec 0.000816 | Seg 0.338675 | Elapsed 4.0m | ETA 0.3m
Epoch 212/500 | Batch 200/202 | Rec 0.000820 | Seg 0.341154 | Elapsed 4.2m | ETA 0.0m
Epoch 212/500 | Batch 202/202 | Rec 0.000822 | Seg 0.343829 | Elapsed 4.3m | ETA 0.0m

2026-09-23 17:03:32,466 - INFO: Rec loss: 0.0008221802085299174
2026-09-23 17:03:32,467 - INFO: Seg loss: 0.34382870199509186
2026-09-23 17:03:32,467 - INFO: λ_rec: 1
2026-09-23 17:03:32,467 - INFO: λ_seg: 0.0001
2026-09-23 17:04:53,138 - INFO: -------------------Epoch: 212------------------------
2026-09-23 17:04:53,142 - INFO:
Validation stats:
       PSNR     SSIM       MSE
0  37.89887  0.97174  0.000168
2026-09-23 17:04:53,149 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995297  0.997593  0.996265  0.999024  0.995506
real potato   0.261668  0.414764  1.000000  0.261668  0.999117
fake potato   0.658132  0.793775  0.967480  0.673021  0.999745
real apple    0.638871  0.779598  0.754835  0.806148  0.998428
fake apple    0.654052  0.790800  0.960929  0.671920  0.998658
real orange   0.506358  0.672250  0.996814  0.507179  0.999348
fake orange   0.789898  0.882568  0.804412  0.977668  0.999256
real grape    0.545263  0.705675  0.933173  0.567419  0.999012
fake grape    0.807032  0.893163  0.868550  0.919317  0.999187
real lemon    0.274153  0.430280  0.407304  0.456115  0.998581
fake lemon    0.841168  0.913683  0.990564  0.847962  0.999661
real avocado  0.773396  0.872170  0.847560  0.898358  0.999755
fake avocado  0.324187  0.489600  0.924903  0.332951  0.999169
real pepper   0.828737  0.906299  0.944424  0.871225  0.999341
fake pepper   0.820373  0.901274  0.959722  0.849625  0.999557
real plant    0.805560  0.892261  0.898430  0.886273  0.997860
fake plant    0.822226  0.902391  0.915893  0.889379  0.999847
real banana   0.195344  0.326808  0.795222  0.205691  0.998096
fake banana   0.459822  0.629922  0.513992  0.813537  0.998242
real onion    0.636339  0.777709  0.761281  0.794967  0.999590
fake onion    0.934239  0.965951  0.984434  0.948247  0.999958
real unknown  0.945335  0.971849  0.987205  0.957061  0.999991
fake unknown  0.182771  0.309021  0.197693  0.707715  0.997334
total         0.639140  0.748670  0.843960  0.732281  0.998923
total(-bg)    0.622951  0.737355  0.837037  0.720157  0.999079
2026-09-23 17:04:53,685 - INFO: Epoch accounting: {'epoch': 212, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11295954, 50943, 56912, 125114, 154872, 77469, 63493, 144823, 165210, 63034, 55825, 53441, 35701, 204912, 145667, 168525, 31008, 75348, 81213, 65118, 63252, 8567, 51871], 'crops_with_class': [202, 28, 27, 36, 36, 22, 23, 30, 31, 31, 23, 18, 13, 51, 37, 25, 27, 23, 35, 35, 29, 9, 22], 'targeted_crops_by_class': [0, 5, 2, 6, 4, 5, 6, 8, 3, 6, 2, 4, 3, 4, 5, 4, 6, 5, 6, 5, 8, 2, 5], 'sampled_scene_counts': [2, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 2, 3, 3, 2, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 0, 2, 0, 1, 2, 0, 0, 2, 2, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 2, 2, 2, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 1, 5, 2, 1, 1, 0, 0, 0, 1, 1, 0, 2, 2, 2, 1, 1, 1, 1, 2, 2, 0, 3, 4, 1, 2, 3, 0, 1, 1, 1, 2, 2, 0, 1, 1, 0, 3, 1, 2, 0, 1, 5, 1, 3, 1, 0, 3, 1, 1, 2, 1, 2, 1, 4, 3, 2, 1, 0, 0, 0, 1, 3, 1, 1], 'learning_rate': 6.22246366359209e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0008221802085299174, 'train_segmentation_loss': 0.34382870199509186, 'val_foreground_miou_all22': 0.6229510153460442, 'val_psnr_ref1': 37.89886962890625, 'elapsed_seconds': 336.7108154296875, 'peak_cuda_allocated_gib': 7.510807037353516}

Epoch 213/500 | Batch 10/202 | Rec 0.000687 | Seg 0.309212 | Elapsed 0.2m | ETA 4.0m
Epoch 213/500 | Batch 20/202 | Rec 0.000779 | Seg 0.342997 | Elapsed 0.4m | ETA 3.8m
Epoch 213/500 | Batch 30/202 | Rec 0.000713 | Seg 0.299108 | Elapsed 0.6m | ETA 3.6m
Epoch 213/500 | Batch 40/202 | Rec 0.000744 | Seg 0.318983 | Elapsed 0.8m | ETA 3.4m
Epoch 213/500 | Batch 50/202 | Rec 0.000729 | Seg 0.321211 | Elapsed 1.0m | ETA 3.2m
Epoch 213/500 | Batch 60/202 | Rec 0.000749 | Seg 0.334131 | Elapsed 1.3m | ETA 3.0m
Epoch 213/500 | Batch 70/202 | Rec 0.000743 | Seg 0.332038 | Elapsed 1.5m | ETA 2.8m
Epoch 213/500 | Batch 80/202 | Rec 0.000769 | Seg 0.341425 | Elapsed 1.7m | ETA 2.6m
Epoch 213/500 | Batch 90/202 | Rec 0.000775 | Seg 0.344965 | Elapsed 1.9m | ETA 2.4m
Epoch 213/500 | Batch 100/202 | Rec 0.000761 | Seg 0.340619 | Elapsed 2.1m | ETA 2.1m
Epoch 213/500 | Batch 110/202 | Rec 0.000759 | Seg 0.331832 | Elapsed 2.3m | ETA 1.9m
Epoch 213/500 | Batch 120/202 | Rec 0.000747 | Seg 0.328761 | Elapsed 2.5m | ETA 1.7m
Epoch 213/500 | Batch 130/202 | Rec 0.000750 | Seg 0.328478 | Elapsed 2.7m | ETA 1.5m
Epoch 213/500 | Batch 140/202 | Rec 0.000744 | Seg 0.323835 | Elapsed 2.9m | ETA 1.3m
Epoch 213/500 | Batch 150/202 | Rec 0.000738 | Seg 0.323633 | Elapsed 3.2m | ETA 1.1m
Epoch 213/500 | Batch 160/202 | Rec 0.000744 | Seg 0.329122 | Elapsed 3.4m | ETA 0.9m
Epoch 213/500 | Batch 170/202 | Rec 0.000746 | Seg 0.331532 | Elapsed 3.6m | ETA 0.7m
Epoch 213/500 | Batch 180/202 | Rec 0.000751 | Seg 0.332599 | Elapsed 3.8m | ETA 0.5m
Epoch 213/500 | Batch 190/202 | Rec 0.000745 | Seg 0.329416 | Elapsed 4.0m | ETA 0.3m
Epoch 213/500 | Batch 200/202 | Rec 0.000751 | Seg 0.335015 | Elapsed 4.2m | ETA 0.0m
Epoch 213/500 | Batch 202/202 | Rec 0.000752 | Seg 0.335176 | Elapsed 4.2m | ETA 0.0m

2026-09-23 17:09:07,769 - INFO: Rec loss: 0.0007517183479613228
2026-09-23 17:09:07,769 - INFO: Seg loss: 0.33517592669566076
2026-09-23 17:09:07,769 - INFO: λ_rec: 1
2026-09-23 17:09:07,769 - INFO: λ_seg: 0.0001
2026-09-23 17:10:28,937 - INFO: -------------------Epoch: 213------------------------
2026-09-23 17:10:28,941 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.916237  0.970883  0.000167
2026-09-23 17:10:28,947 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994808  0.997347  0.995539  0.999262  0.995035
real potato   0.481000  0.649517  1.000000  0.481000  0.999379
fake potato   0.798507  0.887917  0.987186  0.806871  0.999852
real apple    0.715310  0.833980  0.813246  0.855904  0.998825
fake apple    0.674412  0.805503  0.987273  0.680327  0.998760
real orange   0.699075  0.822839  0.921234  0.743516  0.999578
fake orange   0.842537  0.914490  0.861097  0.975056  0.999478
real grape    0.702234  0.825024  0.922174  0.746474  0.999339
fake grape    0.832811  0.908730  0.943241  0.876748  0.999349
real lemon    0.473012  0.642189  0.581709  0.716827  0.999061
fake lemon    0.839366  0.912619  0.988066  0.847962  0.999657
real avocado  0.712446  0.832030  0.761275  0.917406  0.999656
fake avocado  0.754542  0.860052  0.977439  0.767916  0.999701
real pepper   0.795073  0.885789  0.905503  0.867012  0.999183
fake pepper   0.771468  0.870943  0.968429  0.791371  0.999441
real plant    0.813596  0.897168  0.946025  0.853201  0.998045
fake plant    0.853881  0.921132  0.947507  0.896281  0.999878
real banana   0.476175  0.645102  0.967808  0.483838  0.998804
fake banana   0.600166  0.750080  0.678663  0.838421  0.998972
real onion    0.657622  0.793403  0.746022  0.847323  0.999601
fake onion    0.923367  0.960107  0.973645  0.947037  0.999950
real unknown  0.903493  0.949250  0.960899  0.937977  0.999984
fake unknown  0.243911  0.392125  0.284836  0.629301  0.998356
total         0.719948  0.824232  0.874731  0.804653  0.999125
total(-bg)    0.707455  0.816363  0.869240  0.795808  0.999311
2026-09-23 17:10:29,461 - INFO: Epoch accounting: {'epoch': 213, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11402031, 54458, 61246, 85040, 116467, 75937, 68345, 180843, 150169, 80511, 48847, 47798, 48462, 183221, 80654, 188752, 34545, 107343, 59060, 73885, 36558, 6877, 47223], 'crops_with_class': [202, 33, 27, 26, 32, 27, 27, 34, 29, 35, 23, 16, 18, 49, 25, 22, 29, 31, 24, 27, 18, 11, 21], 'targeted_crops_by_class': [0, 4, 3, 2, 3, 3, 2, 5, 2, 4, 6, 7, 10, 4, 6, 5, 10, 7, 3, 3, 8, 5, 8], 'sampled_scene_counts': [0, 2, 0, 0, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 0, 4, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 3, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 0, 0, 1, 1, 2, 2, 2, 0, 2, 1, 4, 1, 2, 0, 0, 0, 0, 1, 1, 1, 0, 3, 1, 1, 1, 2, 1, 0, 5, 6, 2, 1, 0, 0, 5, 4, 2, 2, 1, 1, 1, 2, 1, 1, 1, 0, 1, 2, 2, 0, 3, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 0, 5, 2, 4, 2, 0, 1, 3, 0, 0, 0, 2, 0, 0, 2, 0, 0, 2, 0, 0, 1], 'learning_rate': 6.192038747655822e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007517183479613228, 'train_segmentation_loss': 0.33517592669566076, 'val_foreground_miou_all22': 0.707454699918885, 'val_psnr_ref1': 37.916236877441406, 'elapsed_seconds': 335.76798391342163, 'peak_cuda_allocated_gib': 7.509830474853516}

Epoch 214/500 | Batch 10/202 | Rec 0.000744 | Seg 0.334564 | Elapsed 0.2m | ETA 4.0m
Epoch 214/500 | Batch 20/202 | Rec 0.000700 | Seg 0.321562 | Elapsed 0.4m | ETA 3.8m
Epoch 214/500 | Batch 30/202 | Rec 0.000776 | Seg 0.373715 | Elapsed 0.6m | ETA 3.6m
Epoch 214/500 | Batch 40/202 | Rec 0.000755 | Seg 0.362386 | Elapsed 0.8m | ETA 3.4m
Epoch 214/500 | Batch 50/202 | Rec 0.000749 | Seg 0.366775 | Elapsed 1.0m | ETA 3.2m
Epoch 214/500 | Batch 60/202 | Rec 0.000753 | Seg 0.359192 | Elapsed 1.3m | ETA 3.0m
Epoch 214/500 | Batch 70/202 | Rec 0.000760 | Seg 0.367615 | Elapsed 1.5m | ETA 2.8m
Epoch 214/500 | Batch 80/202 | Rec 0.000763 | Seg 0.360876 | Elapsed 1.7m | ETA 2.5m
Epoch 214/500 | Batch 90/202 | Rec 0.000758 | Seg 0.357507 | Elapsed 1.9m | ETA 2.3m
Epoch 214/500 | Batch 100/202 | Rec 0.000759 | Seg 0.357064 | Elapsed 2.1m | ETA 2.1m
Epoch 214/500 | Batch 110/202 | Rec 0.000754 | Seg 0.353351 | Elapsed 2.3m | ETA 1.9m
Epoch 214/500 | Batch 120/202 | Rec 0.000757 | Seg 0.355069 | Elapsed 2.5m | ETA 1.7m
Epoch 214/500 | Batch 130/202 | Rec 0.000797 | Seg 0.352228 | Elapsed 2.7m | ETA 1.5m
Epoch 214/500 | Batch 140/202 | Rec 0.000789 | Seg 0.351680 | Elapsed 2.9m | ETA 1.3m
Epoch 214/500 | Batch 150/202 | Rec 0.000792 | Seg 0.353196 | Elapsed 3.1m | ETA 1.1m
Epoch 214/500 | Batch 160/202 | Rec 0.000790 | Seg 0.352414 | Elapsed 3.3m | ETA 0.9m
Epoch 214/500 | Batch 170/202 | Rec 0.000788 | Seg 0.348987 | Elapsed 3.6m | ETA 0.7m
Epoch 214/500 | Batch 180/202 | Rec 0.000797 | Seg 0.344373 | Elapsed 3.8m | ETA 0.5m
Epoch 214/500 | Batch 190/202 | Rec 0.000796 | Seg 0.344308 | Elapsed 4.0m | ETA 0.3m
Epoch 214/500 | Batch 200/202 | Rec 0.000794 | Seg 0.343660 | Elapsed 4.2m | ETA 0.0m
Epoch 214/500 | Batch 202/202 | Rec 0.000792 | Seg 0.342656 | Elapsed 4.2m | ETA 0.0m

2026-09-23 17:14:44,377 - INFO: Rec loss: 0.0007922604907272927
2026-09-23 17:14:44,377 - INFO: Seg loss: 0.3426562967055505
2026-09-23 17:14:44,377 - INFO: λ_rec: 1
2026-09-23 17:14:44,377 - INFO: λ_seg: 0.0001
2026-09-23 17:16:02,843 - INFO: -------------------Epoch: 214------------------------
2026-09-23 17:16:02,847 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.966873  0.971508  0.000166
2026-09-23 17:16:02,854 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995653  0.997772  0.996912  0.998734  0.995849
real potato   0.299413  0.460808  1.000000  0.299413  0.999162
fake potato   0.646062  0.784931  0.980238  0.654587  0.999739
real apple    0.601553  0.751162  0.723287  0.781380  0.998214
fake apple    0.603525  0.752701  0.989273  0.607501  0.998493
real orange   0.835346  0.910237  0.991673  0.841246  0.999781
fake orange   0.901488  0.948142  0.916787  0.981825  0.999693
real grape    0.703391  0.825822  0.848002  0.804867  0.999291
fake grape    0.846006  0.916530  0.926941  0.906447  0.999390
real lemon    0.385709  0.556652  0.408434  0.873929  0.998364
fake lemon    0.854903  0.921727  0.991285  0.861378  0.999691
real avocado  0.671753  0.803602  0.706080  0.932512  0.999577
fake avocado  0.475942  0.644889  0.945320  0.489416  0.999355
real pepper   0.776694  0.874264  0.915237  0.836893  0.999120
fake pepper   0.808545  0.894089  0.997008  0.810511  0.999543
real plant    0.852295  0.920208  0.926815  0.913794  0.998416
fake plant    0.845852  0.916440  0.883473  0.952071  0.999862
real banana   0.225977  0.368616  0.931462  0.229798  0.998231
fake banana   0.748046  0.855816  0.897588  0.817850  0.999493
real onion    0.584079  0.737387  0.772862  0.705117  0.999546
fake onion    0.949095  0.973833  0.997464  0.951391  0.999968
real unknown  0.668191  0.801048  0.679283  0.976145  0.999922
fake unknown  0.194942  0.326247  0.202443  0.840275  0.997076
total         0.672803  0.780127  0.853386  0.785525  0.999034
total(-bg)    0.658128  0.770234  0.846862  0.775834  0.999179
2026-09-23 17:16:03,375 - INFO: Epoch accounting: {'epoch': 214, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11319345, 40998, 55851, 113561, 125730, 75338, 63282, 132018, 185124, 84221, 48461, 48972, 43178, 224551, 146260, 123353, 28076, 73018, 81658, 90857, 47485, 9554, 77381], 'crops_with_class': [202, 22, 26, 31, 36, 21, 24, 27, 42, 32, 26, 19, 22, 57, 34, 16, 24, 19, 35, 35, 24, 11, 29], 'targeted_crops_by_class': [0, 2, 4, 1, 3, 5, 6, 2, 8, 7, 4, 4, 4, 7, 7, 2, 7, 6, 6, 4, 3, 1, 11], 'sampled_scene_counts': [0, 0, 1, 1, 2, 1, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 3, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 1, 0, 2, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 3, 0, 0, 1, 1, 1, 2, 0, 0, 1, 4, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 1, 0, 0, 1, 2, 1, 2, 2, 0, 4, 0, 1, 2, 1, 2, 3, 2, 0, 1, 0, 1, 1, 1, 0, 0, 0, 3, 2, 0, 3, 2, 2, 2, 1, 1, 5, 2, 1, 2, 4, 2, 2, 4, 1, 1, 1, 1, 2, 0, 1, 2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 1, 2, 1, 1, 1, 1, 3, 0, 2, 1, 0, 1, 2, 1, 0, 1, 2, 1], 'learning_rate': 6.16156726554949e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007922604907272927, 'train_segmentation_loss': 0.3426562967055505, 'val_foreground_miou_all22': 0.6581275699074747, 'val_psnr_ref1': 37.96687316894531, 'elapsed_seconds': 333.9056558609009, 'peak_cuda_allocated_gib': 7.514171600341797}

Epoch 215/500 | Batch 10/202 | Rec 0.000823 | Seg 0.281947 | Elapsed 0.2m | ETA 4.1m
Epoch 215/500 | Batch 20/202 | Rec 0.000759 | Seg 0.276608 | Elapsed 0.4m | ETA 3.9m
Epoch 215/500 | Batch 30/202 | Rec 0.000701 | Seg 0.276669 | Elapsed 0.6m | ETA 3.7m
Epoch 215/500 | Batch 40/202 | Rec 0.000709 | Seg 0.291177 | Elapsed 0.8m | ETA 3.4m
Epoch 215/500 | Batch 50/202 | Rec 0.000707 | Seg 0.290823 | Elapsed 1.1m | ETA 3.2m
Epoch 215/500 | Batch 60/202 | Rec 0.000701 | Seg 0.288203 | Elapsed 1.3m | ETA 3.0m
Epoch 215/500 | Batch 70/202 | Rec 0.000689 | Seg 0.281214 | Elapsed 1.5m | ETA 2.8m
Epoch 215/500 | Batch 80/202 | Rec 0.000695 | Seg 0.278907 | Elapsed 1.7m | ETA 2.6m
Epoch 215/500 | Batch 90/202 | Rec 0.000697 | Seg 0.286531 | Elapsed 1.9m | ETA 2.4m
Epoch 215/500 | Batch 100/202 | Rec 0.000701 | Seg 0.296888 | Elapsed 2.1m | ETA 2.1m
Epoch 215/500 | Batch 110/202 | Rec 0.000703 | Seg 0.301770 | Elapsed 2.3m | ETA 1.9m
Epoch 215/500 | Batch 120/202 | Rec 0.000708 | Seg 0.306812 | Elapsed 2.5m | ETA 1.7m
Epoch 215/500 | Batch 130/202 | Rec 0.000713 | Seg 0.309842 | Elapsed 2.7m | ETA 1.5m
Epoch 215/500 | Batch 140/202 | Rec 0.000728 | Seg 0.310040 | Elapsed 2.9m | ETA 1.3m
Epoch 215/500 | Batch 150/202 | Rec 0.000728 | Seg 0.313137 | Elapsed 3.2m | ETA 1.1m
Epoch 215/500 | Batch 160/202 | Rec 0.000728 | Seg 0.314800 | Elapsed 3.4m | ETA 0.9m
Epoch 215/500 | Batch 170/202 | Rec 0.000736 | Seg 0.318122 | Elapsed 3.6m | ETA 0.7m
Epoch 215/500 | Batch 180/202 | Rec 0.000739 | Seg 0.321397 | Elapsed 3.8m | ETA 0.5m
Epoch 215/500 | Batch 190/202 | Rec 0.000749 | Seg 0.326578 | Elapsed 4.0m | ETA 0.3m
Epoch 215/500 | Batch 200/202 | Rec 0.000745 | Seg 0.325934 | Elapsed 4.2m | ETA 0.0m
Epoch 215/500 | Batch 202/202 | Rec 0.000745 | Seg 0.325838 | Elapsed 4.2m | ETA 0.0m

2026-09-23 17:20:17,768 - INFO: Rec loss: 0.0007445414738336551
2026-09-23 17:20:17,768 - INFO: Seg loss: 0.32583836521400084
2026-09-23 17:20:17,768 - INFO: λ_rec: 1
2026-09-23 17:20:17,768 - INFO: λ_seg: 0.0001
2026-09-23 17:21:36,780 - INFO: -------------------Epoch: 215------------------------
2026-09-23 17:21:36,783 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.923584  0.971091  0.000168
2026-09-23 17:21:36,790 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995270  0.997580  0.996377  0.998886  0.995481
real potato   0.812064  0.896237  0.992411  0.817138  0.999774
fake potato   0.937073  0.967464  0.958856  0.976330  0.999952
real apple    0.622402  0.767211  0.932991  0.651526  0.998636
fake apple    0.646225  0.785051  0.964826  0.661817  0.998632
real orange   0.770569  0.870370  0.984935  0.779759  0.999694
fake orange   0.871492  0.931284  0.894280  0.971592  0.999590
real grape    0.677302  0.807559  0.811633  0.803625  0.999201
fake grape    0.838393  0.912043  0.934369  0.890855  0.999365
real lemon    0.383147  0.553974  0.468498  0.677746  0.998718
fake lemon    0.828479  0.906145  0.996540  0.830869  0.999636
real avocado  0.769862  0.869919  0.799065  0.954680  0.999735
fake avocado  0.466862  0.636502  0.998909  0.467100  0.999362
real pepper   0.780579  0.876720  0.865232  0.888620  0.999086
fake pepper   0.879220  0.935679  0.966501  0.906856  0.999703
real plant    0.861596  0.925603  0.936958  0.914617  0.998530
fake plant    0.797199  0.887107  0.869205  0.905867  0.999817
real banana   0.421561  0.593053  0.944370  0.432297  0.998667
fake banana   0.669379  0.801900  0.785737  0.818845  0.999256
real onion    0.677066  0.807392  0.702449  0.949333  0.999591
fake onion    0.953588  0.976193  0.988836  0.963966  0.999970
real unknown  0.625078  0.769242  0.643545  0.956107  0.999908
fake unknown  0.231270  0.375623  0.254122  0.720029  0.997983
total         0.718073  0.819559  0.856115  0.823411  0.999143
total(-bg)    0.705473  0.811467  0.849740  0.815435  0.999309
2026-09-23 17:21:37,302 - INFO: Epoch accounting: {'epoch': 215, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11385979, 31733, 58323, 96727, 157553, 89850, 84093, 162670, 215462, 71237, 58178, 68177, 46248, 188263, 108221, 89029, 24633, 60071, 68894, 68432, 50178, 11247, 43074], 'crops_with_class': [202, 21, 28, 27, 40, 25, 29, 31, 33, 29, 27, 25, 18, 44, 28, 17, 21, 20, 27, 30, 25, 11, 24], 'targeted_crops_by_class': [0, 1, 4, 3, 7, 5, 3, 6, 5, 11, 3, 7, 8, 2, 5, 6, 3, 3, 3, 5, 7, 4, 8], 'sampled_scene_counts': [0, 2, 1, 0, 1, 2, 1, 0, 2, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 3, 1, 0, 1, 3, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 2, 2, 3, 2, 1, 1, 0, 3, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, 2, 1, 2, 3, 0, 2, 1, 0, 0, 1, 1, 2, 3, 2, 0, 3, 4, 2, 1, 2, 0, 1, 2, 2, 1, 0, 2, 2, 2, 0, 0, 0, 2, 1, 0, 3, 1, 3, 3, 0, 2, 0, 2, 1, 0, 1, 1, 1, 1, 2, 1, 0, 2, 1, 1, 1, 2, 1, 1, 2, 1, 3, 0, 2, 1, 0, 1, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 3, 2], 'learning_rate': 6.131050420235033e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007445414738336551, 'train_segmentation_loss': 0.32583836521400084, 'val_foreground_miou_all22': 0.7054730883461356, 'val_psnr_ref1': 37.92358352661133, 'elapsed_seconds': 333.91847944259644, 'peak_cuda_allocated_gib': 7.514682769775391}

Epoch 216/500 | Batch 10/202 | Rec 0.000832 | Seg 0.358671 | Elapsed 0.2m | ETA 4.2m
Epoch 216/500 | Batch 20/202 | Rec 0.000934 | Seg 0.391485 | Elapsed 0.4m | ETA 3.9m
Epoch 216/500 | Batch 30/202 | Rec 0.000852 | Seg 0.355838 | Elapsed 0.6m | ETA 3.7m
Epoch 216/500 | Batch 40/202 | Rec 0.000828 | Seg 0.337195 | Elapsed 0.8m | ETA 3.4m
Epoch 216/500 | Batch 50/202 | Rec 0.000853 | Seg 0.354967 | Elapsed 1.1m | ETA 3.2m
Epoch 216/500 | Batch 60/202 | Rec 0.000853 | Seg 0.335387 | Elapsed 1.3m | ETA 3.0m
Epoch 216/500 | Batch 70/202 | Rec 0.000831 | Seg 0.330797 | Elapsed 1.5m | ETA 2.8m
Epoch 216/500 | Batch 80/202 | Rec 0.000814 | Seg 0.331039 | Elapsed 1.7m | ETA 2.6m
Epoch 216/500 | Batch 90/202 | Rec 0.000808 | Seg 0.328487 | Elapsed 1.9m | ETA 2.4m
Epoch 216/500 | Batch 100/202 | Rec 0.000790 | Seg 0.325016 | Elapsed 2.1m | ETA 2.1m
Epoch 216/500 | Batch 110/202 | Rec 0.000788 | Seg 0.322446 | Elapsed 2.3m | ETA 1.9m
Epoch 216/500 | Batch 120/202 | Rec 0.000784 | Seg 0.327236 | Elapsed 2.5m | ETA 1.7m
Epoch 216/500 | Batch 130/202 | Rec 0.000795 | Seg 0.328960 | Elapsed 2.7m | ETA 1.5m
Epoch 216/500 | Batch 140/202 | Rec 0.000802 | Seg 0.336850 | Elapsed 3.0m | ETA 1.3m
Epoch 216/500 | Batch 150/202 | Rec 0.000811 | Seg 0.341764 | Elapsed 3.2m | ETA 1.1m
Epoch 216/500 | Batch 160/202 | Rec 0.000816 | Seg 0.349994 | Elapsed 3.4m | ETA 0.9m
Epoch 216/500 | Batch 170/202 | Rec 0.000813 | Seg 0.349737 | Elapsed 3.6m | ETA 0.7m
Epoch 216/500 | Batch 180/202 | Rec 0.000803 | Seg 0.349973 | Elapsed 3.8m | ETA 0.5m
Epoch 216/500 | Batch 190/202 | Rec 0.000801 | Seg 0.359492 | Elapsed 4.0m | ETA 0.3m
Epoch 216/500 | Batch 200/202 | Rec 0.000800 | Seg 0.363101 | Elapsed 4.2m | ETA 0.0m
Epoch 216/500 | Batch 202/202 | Rec 0.000808 | Seg 0.368259 | Elapsed 4.2m | ETA 0.0m

2026-09-23 17:25:51,852 - INFO: Rec loss: 0.0008077905800062149
2026-09-23 17:25:51,852 - INFO: Seg loss: 0.36825937646819223
2026-09-23 17:25:51,852 - INFO: λ_rec: 1
2026-09-23 17:25:51,852 - INFO: λ_seg: 0.0001
2026-09-23 17:27:12,809 - INFO: -------------------Epoch: 216------------------------
2026-09-23 17:27:12,812 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.079773  0.972142  0.000162
2026-09-23 17:27:12,819 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995145  0.997517  0.996164  0.998973  0.995360
real potato   0.023846  0.046577  0.999999  0.023846  0.998832
fake potato   0.639640  0.780171  0.935304  0.669250  0.999725
real apple    0.582086  0.735797  0.740527  0.731225  0.998189
fake apple    0.749020  0.856453  0.917455  0.803144  0.998984
real orange   0.523491  0.687180  0.994082  0.525127  0.999370
fake orange   0.801484  0.889755  0.807826  0.990300  0.999298
real grape    0.252915  0.403690  0.965708  0.255207  0.998426
fake grape    0.751780  0.858254  0.805234  0.918863  0.998878
real lemon    0.191198  0.320972  0.249819  0.448974  0.997768
fake lemon    0.775373  0.873426  0.910036  0.839740  0.999485
real avocado  0.552253  0.711501  0.769025  0.662069  0.999501
fake avocado  0.471919  0.641181  0.717374  0.579699  0.999224
real pepper   0.769177  0.869481  0.913661  0.829468  0.999090
fake pepper   0.747716  0.855600  0.946454  0.780744  0.999372
real plant    0.768085  0.868783  0.843679  0.895533  0.997295
fake plant    0.693436  0.818919  0.885816  0.761503  0.999732
real banana   0.027631  0.053764  0.393518  0.028861  0.997718
fake banana   0.465462  0.635194  0.556770  0.739466  0.998438
real onion    0.628475  0.771807  0.788445  0.755953  0.999596
fake onion    0.944325  0.971316  0.983156  0.959855  0.999964
real unknown  0.852727  0.920460  0.947475  0.895038  0.999975
fake unknown  0.199258  0.332264  0.224190  0.641796  0.997827
total         0.582889  0.691307  0.795292  0.684115  0.998785
total(-bg)    0.564150  0.677388  0.786162  0.669803  0.998940
2026-09-23 17:27:13,336 - INFO: Epoch accounting: {'epoch': 216, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11252505, 30580, 40289, 115695, 206354, 89852, 83641, 129939, 281828, 65876, 78245, 48081, 39255, 247264, 116274, 100769, 30025, 68982, 60130, 52831, 49391, 15803, 34663], 'crops_with_class': [202, 19, 19, 39, 53, 26, 35, 28, 46, 31, 35, 18, 13, 60, 26, 16, 24, 22, 23, 25, 22, 14, 19], 'targeted_crops_by_class': [0, 0, 4, 4, 8, 4, 8, 5, 8, 1, 8, 5, 3, 4, 2, 2, 4, 3, 4, 2, 6, 5, 5], 'sampled_scene_counts': [0, 1, 1, 2, 1, 0, 2, 1, 3, 4, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 3, 3, 1, 4, 0, 3, 4, 1, 3, 1, 1, 2, 3, 0, 1, 2, 0, 0, 1, 0, 1, 1, 0, 2, 2, 0, 0, 0, 1, 2, 2, 3, 3, 2, 1, 8, 0, 1, 0, 1, 1, 0, 1, 0, 1, 2, 0, 1, 2, 2, 1, 2, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 3, 0, 1, 2, 1, 0, 1, 1, 1, 1, 2, 3, 1, 2], 'learning_rate': 6.1004894164652505e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0008077905800062149, 'train_segmentation_loss': 0.36825937646819223, 'val_foreground_miou_all22': 0.5641499642876794, 'val_psnr_ref1': 38.07977340698242, 'elapsed_seconds': 336.02486205101013, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 217/500 | Batch 10/202 | Rec 0.000738 | Seg 0.336990 | Elapsed 0.2m | ETA 4.1m
Epoch 217/500 | Batch 20/202 | Rec 0.000727 | Seg 0.349121 | Elapsed 0.4m | ETA 3.8m
Epoch 217/500 | Batch 30/202 | Rec 0.000747 | Seg 0.344140 | Elapsed 0.6m | ETA 3.6m
Epoch 217/500 | Batch 40/202 | Rec 0.000769 | Seg 0.364105 | Elapsed 0.8m | ETA 3.4m
Epoch 217/500 | Batch 50/202 | Rec 0.000754 | Seg 0.349139 | Elapsed 1.0m | ETA 3.2m
Epoch 217/500 | Batch 60/202 | Rec 0.000772 | Seg 0.363526 | Elapsed 1.2m | ETA 3.0m
Epoch 217/500 | Batch 70/202 | Rec 0.000771 | Seg 0.361803 | Elapsed 1.5m | ETA 2.7m
Epoch 217/500 | Batch 80/202 | Rec 0.000764 | Seg 0.367514 | Elapsed 1.7m | ETA 2.5m
Epoch 217/500 | Batch 90/202 | Rec 0.000765 | Seg 0.364056 | Elapsed 1.9m | ETA 2.3m
Epoch 217/500 | Batch 100/202 | Rec 0.000759 | Seg 0.365566 | Elapsed 2.1m | ETA 2.1m
Epoch 217/500 | Batch 110/202 | Rec 0.000754 | Seg 0.361794 | Elapsed 2.3m | ETA 1.9m
Epoch 217/500 | Batch 120/202 | Rec 0.000767 | Seg 0.371190 | Elapsed 2.5m | ETA 1.7m
Epoch 217/500 | Batch 130/202 | Rec 0.000772 | Seg 0.368095 | Elapsed 2.7m | ETA 1.5m
Epoch 217/500 | Batch 140/202 | Rec 0.000768 | Seg 0.366259 | Elapsed 2.9m | ETA 1.3m
Epoch 217/500 | Batch 150/202 | Rec 0.000757 | Seg 0.358801 | Elapsed 3.1m | ETA 1.1m
Epoch 217/500 | Batch 160/202 | Rec 0.000748 | Seg 0.352756 | Elapsed 3.3m | ETA 0.9m
Epoch 217/500 | Batch 170/202 | Rec 0.000755 | Seg 0.350053 | Elapsed 3.6m | ETA 0.7m
Epoch 217/500 | Batch 180/202 | Rec 0.000753 | Seg 0.346464 | Elapsed 3.8m | ETA 0.5m
Epoch 217/500 | Batch 190/202 | Rec 0.000767 | Seg 0.350098 | Elapsed 4.0m | ETA 0.3m
Epoch 217/500 | Batch 200/202 | Rec 0.000768 | Seg 0.348967 | Elapsed 4.2m | ETA 0.0m
Epoch 217/500 | Batch 202/202 | Rec 0.000777 | Seg 0.347973 | Elapsed 4.2m | ETA 0.0m

2026-09-23 17:31:27,118 - INFO: Rec loss: 0.0007770323483584596
2026-09-23 17:31:27,118 - INFO: Seg loss: 0.3479732778107766
2026-09-23 17:31:27,118 - INFO: λ_rec: 1
2026-09-23 17:31:27,118 - INFO: λ_seg: 0.0001
2026-09-23 17:32:47,128 - INFO: -------------------Epoch: 217------------------------
2026-09-23 17:32:47,132 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.913679  0.972445  0.000169
2026-09-23 17:32:47,139 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995074  0.997481  0.995840  0.999228  0.995291
real potato   0.542766  0.703582  0.999296  0.542974  0.999453
fake potato   0.743254  0.852671  0.968567  0.761625  0.999808
real apple    0.690796  0.817076  0.848009  0.788412  0.998783
fake apple    0.626991  0.770689  0.935603  0.655270  0.998528
real orange   0.786691  0.880563  0.980125  0.799444  0.999714
fake orange   0.871732  0.931421  0.895529  0.970419  0.999591
real grape    0.515473  0.680234  0.939359  0.533216  0.998954
fake grape    0.779325  0.875928  0.835079  0.921091  0.999035
real lemon    0.417070  0.588591  0.456642  0.827967  0.998640
fake lemon    0.798914  0.888168  0.931529  0.848756  0.999548
real avocado  0.811495  0.895890  0.858648  0.936617  0.999798
fake avocado  0.499554  0.666225  0.999745  0.499617  0.999401
real pepper   0.827584  0.905609  0.926629  0.885617  0.999325
fake pepper   0.865296  0.927734  0.996838  0.867678  0.999678
real plant    0.811253  0.895742  0.935409  0.859394  0.998000
fake plant    0.795095  0.885803  0.876949  0.894939  0.999816
real banana   0.309125  0.472224  0.937475  0.315632  0.998415
fake banana   0.673509  0.804857  0.881992  0.740212  0.999340
real onion    0.709866  0.830268  0.755012  0.922310  0.999659
fake onion    0.935174  0.966451  0.992357  0.941959  0.999959
real unknown  0.737573  0.848920  0.759217  0.962786  0.999945
fake unknown  0.195265  0.326695  0.212639  0.704998  0.997552
total         0.692995  0.800557  0.866021  0.790442  0.999054
total(-bg)    0.679264  0.791606  0.860120  0.780952  0.999225
2026-09-23 17:32:47,663 - INFO: Epoch accounting: {'epoch': 217, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11310095, 45788, 58813, 111361, 135354, 131642, 76998, 165470, 145062, 76490, 72542, 44980, 40482, 162057, 106791, 208621, 28434, 63900, 55515, 81067, 48771, 11411, 56628], 'crops_with_class': [202, 29, 26, 33, 35, 34, 25, 33, 28, 36, 30, 13, 16, 48, 25, 26, 26, 17, 27, 34, 23, 13, 26], 'targeted_crops_by_class': [0, 2, 3, 6, 3, 5, 6, 5, 2, 6, 9, 7, 4, 1, 3, 12, 4, 3, 7, 5, 1, 5, 3], 'sampled_scene_counts': [1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 4, 3, 0, 0, 0, 1, 1, 1, 2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 2, 0, 0, 1, 1, 2, 1, 3, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2, 2, 0, 1, 1, 1, 0, 4, 0, 0, 2, 1, 2, 1, 3, 1, 0, 2, 2, 1, 1, 2, 2, 2, 2, 5, 2, 1, 1, 2, 3, 2, 2, 1, 0, 0, 2, 2, 1, 1, 3, 3, 4, 1, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 1, 1, 2, 3, 2, 2, 1, 1, 1, 1, 3, 0, 0, 1, 3, 2, 0, 1, 0, 2], 'learning_rate': 6.0698854607362424e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007770323483584596, 'train_segmentation_loss': 0.3479732778107766, 'val_foreground_miou_all22': 0.6792636863599508, 'val_psnr_ref1': 37.913678588867185, 'elapsed_seconds': 334.3194913864136, 'peak_cuda_allocated_gib': 7.507389068603516}

Epoch 218/500 | Batch 10/202 | Rec 0.000868 | Seg 0.386980 | Elapsed 0.2m | ETA 4.1m
Epoch 218/500 | Batch 20/202 | Rec 0.000779 | Seg 0.355976 | Elapsed 0.4m | ETA 3.9m
Epoch 218/500 | Batch 30/202 | Rec 0.000795 | Seg 0.375207 | Elapsed 0.6m | ETA 3.6m
Epoch 218/500 | Batch 40/202 | Rec 0.000788 | Seg 0.365443 | Elapsed 0.8m | ETA 3.4m
Epoch 218/500 | Batch 50/202 | Rec 0.000774 | Seg 0.352755 | Elapsed 1.0m | ETA 3.2m
Epoch 218/500 | Batch 60/202 | Rec 0.000789 | Seg 0.357969 | Elapsed 1.3m | ETA 3.0m
Epoch 218/500 | Batch 70/202 | Rec 0.000801 | Seg 0.361606 | Elapsed 1.5m | ETA 2.8m
Epoch 218/500 | Batch 80/202 | Rec 0.000821 | Seg 0.372512 | Elapsed 1.7m | ETA 2.6m
Epoch 218/500 | Batch 90/202 | Rec 0.000814 | Seg 0.363481 | Elapsed 1.9m | ETA 2.4m
Epoch 218/500 | Batch 100/202 | Rec 0.000807 | Seg 0.360024 | Elapsed 2.1m | ETA 2.1m
Epoch 218/500 | Batch 110/202 | Rec 0.000803 | Seg 0.365717 | Elapsed 2.3m | ETA 1.9m
Epoch 218/500 | Batch 120/202 | Rec 0.000802 | Seg 0.361846 | Elapsed 2.5m | ETA 1.7m
Epoch 218/500 | Batch 130/202 | Rec 0.000784 | Seg 0.350363 | Elapsed 2.7m | ETA 1.5m
Epoch 218/500 | Batch 140/202 | Rec 0.000772 | Seg 0.344030 | Elapsed 2.9m | ETA 1.3m
Epoch 218/500 | Batch 150/202 | Rec 0.000773 | Seg 0.347686 | Elapsed 3.2m | ETA 1.1m
Epoch 218/500 | Batch 160/202 | Rec 0.000772 | Seg 0.346265 | Elapsed 3.4m | ETA 0.9m
Epoch 218/500 | Batch 170/202 | Rec 0.000777 | Seg 0.347929 | Elapsed 3.6m | ETA 0.7m
Epoch 218/500 | Batch 180/202 | Rec 0.000772 | Seg 0.346305 | Elapsed 3.8m | ETA 0.5m
Epoch 218/500 | Batch 190/202 | Rec 0.000770 | Seg 0.347080 | Elapsed 4.0m | ETA 0.3m
Epoch 218/500 | Batch 200/202 | Rec 0.000770 | Seg 0.349396 | Elapsed 4.2m | ETA 0.0m
Epoch 218/500 | Batch 202/202 | Rec 0.000770 | Seg 0.350314 | Elapsed 4.2m | ETA 0.0m

2026-09-23 17:37:02,652 - INFO: Rec loss: 0.0007702259190949971
2026-09-23 17:37:02,652 - INFO: Seg loss: 0.3503138894713161
2026-09-23 17:37:02,652 - INFO: λ_rec: 1
2026-09-23 17:37:02,653 - INFO: λ_seg: 0.0001
2026-09-23 17:38:20,514 - INFO: -------------------Epoch: 218------------------------
2026-09-23 17:38:20,519 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.990332  0.971837  0.000164
2026-09-23 17:38:20,525 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995299  0.997594  0.996259  0.999032  0.995508
real potato   0.276333  0.432976  1.000000  0.276333  0.999134
fake potato   0.638246  0.779134  0.967381  0.652283  0.999731
real apple    0.652765  0.789857  0.775905  0.804423  0.998524
fake apple    0.659711  0.794922  0.915110  0.702716  0.998631
real orange   0.594570  0.745696  0.996321  0.595878  0.999465
fake orange   0.816866  0.899154  0.830399  0.980439  0.999371
real grape    0.466743  0.636390  0.956190  0.476942  0.998862
fake grape    0.756654  0.861422  0.811343  0.918203  0.998908
real lemon    0.256304  0.407981  0.340913  0.508050  0.998268
fake lemon    0.837629  0.911591  0.952243  0.874360  0.999641
real avocado  0.772292  0.871468  0.812287  0.940066  0.999742
fake avocado  0.640996  0.781181  0.994676  0.643203  0.999569
real pepper   0.832224  0.908381  0.948808  0.871350  0.999357
fake pepper   0.787587  0.881124  0.969636  0.807503  0.999481
real plant    0.821499  0.901954  0.907097  0.896967  0.998051
fake plant    0.818520  0.900154  0.873422  0.928681  0.999836
real banana   0.167025  0.286214  0.936042  0.168953  0.998107
fake banana   0.537247  0.698924  0.635549  0.776460  0.998770
real onion    0.697696  0.821883  0.779207  0.869617  0.999660
fake onion    0.943994  0.971140  0.984833  0.957920  0.999964
real unknown  0.956075  0.977494  0.978947  0.976145  0.999993
fake unknown  0.179791  0.304747  0.201858  0.621876  0.997610
total         0.656785  0.763538  0.850627  0.749887  0.998964
total(-bg)    0.641398  0.752899  0.844008  0.738562  0.999121
2026-09-23 17:38:21,061 - INFO: Epoch accounting: {'epoch': 218, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11241417, 60912, 45324, 133357, 155117, 111879, 50661, 168292, 173949, 65504, 73706, 41362, 32681, 185478, 130728, 183983, 29915, 93161, 66495, 66694, 57917, 16353, 53387], 'crops_with_class': [202, 29, 21, 34, 38, 32, 22, 34, 33, 33, 29, 16, 13, 49, 35, 24, 24, 25, 30, 31, 26, 17, 24], 'targeted_crops_by_class': [0, 5, 5, 3, 4, 8, 6, 4, 5, 4, 4, 6, 3, 4, 3, 3, 5, 3, 3, 8, 2, 5, 7], 'sampled_scene_counts': [0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 2, 2, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 0, 2, 0, 2, 0, 2, 0, 3, 1, 0, 1, 1, 1, 3, 1, 2, 1, 3, 1, 2, 3, 2, 2, 2, 0, 0, 1, 3, 4, 0, 2, 2, 1, 1, 2, 1, 0, 3, 4, 1, 2, 1, 4, 4, 3, 0, 1, 2, 0, 2, 1, 1, 1, 2, 1, 1, 3, 1, 0, 1, 1, 3, 1, 2, 2, 1, 1, 2, 0, 2, 0, 2, 1, 0, 2, 1, 2, 2, 1, 0, 1, 2, 1, 2, 1], 'learning_rate': 6.039239761239777e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007702259190949971, 'train_segmentation_loss': 0.3503138894713161, 'val_foreground_miou_all22': 0.6413984974794436, 'val_psnr_ref1': 37.99033172607422, 'elapsed_seconds': 333.3898227214813, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 219/500 | Batch 10/202 | Rec 0.000681 | Seg 0.263909 | Elapsed 0.2m | ETA 4.0m
Epoch 219/500 | Batch 20/202 | Rec 0.000755 | Seg 0.301452 | Elapsed 0.4m | ETA 3.8m
Epoch 219/500 | Batch 30/202 | Rec 0.000779 | Seg 0.308169 | Elapsed 0.6m | ETA 3.6m
Epoch 219/500 | Batch 40/202 | Rec 0.000787 | Seg 0.314499 | Elapsed 0.8m | ETA 3.4m
Epoch 219/500 | Batch 50/202 | Rec 0.000763 | Seg 0.305532 | Elapsed 1.1m | ETA 3.2m
Epoch 219/500 | Batch 60/202 | Rec 0.000776 | Seg 0.319598 | Elapsed 1.3m | ETA 3.0m
Epoch 219/500 | Batch 70/202 | Rec 0.000807 | Seg 0.339781 | Elapsed 1.5m | ETA 2.8m
Epoch 219/500 | Batch 80/202 | Rec 0.000797 | Seg 0.333993 | Elapsed 1.7m | ETA 2.6m
Epoch 219/500 | Batch 90/202 | Rec 0.000793 | Seg 0.324734 | Elapsed 1.9m | ETA 2.4m
Epoch 219/500 | Batch 100/202 | Rec 0.000788 | Seg 0.327410 | Elapsed 2.1m | ETA 2.2m
Epoch 219/500 | Batch 110/202 | Rec 0.000793 | Seg 0.337730 | Elapsed 2.3m | ETA 1.9m
Epoch 219/500 | Batch 120/202 | Rec 0.000780 | Seg 0.333497 | Elapsed 2.5m | ETA 1.7m
Epoch 219/500 | Batch 130/202 | Rec 0.000789 | Seg 0.338093 | Elapsed 2.7m | ETA 1.5m
Epoch 219/500 | Batch 140/202 | Rec 0.000778 | Seg 0.337962 | Elapsed 3.0m | ETA 1.3m
Epoch 219/500 | Batch 150/202 | Rec 0.000782 | Seg 0.344118 | Elapsed 3.2m | ETA 1.1m
Epoch 219/500 | Batch 160/202 | Rec 0.000777 | Seg 0.341913 | Elapsed 3.4m | ETA 0.9m
Epoch 219/500 | Batch 170/202 | Rec 0.000780 | Seg 0.341572 | Elapsed 3.6m | ETA 0.7m
Epoch 219/500 | Batch 180/202 | Rec 0.000781 | Seg 0.344605 | Elapsed 3.8m | ETA 0.5m
Epoch 219/500 | Batch 190/202 | Rec 0.000778 | Seg 0.342125 | Elapsed 4.0m | ETA 0.3m
Epoch 219/500 | Batch 200/202 | Rec 0.000778 | Seg 0.341410 | Elapsed 4.2m | ETA 0.0m
Epoch 219/500 | Batch 202/202 | Rec 0.000777 | Seg 0.340084 | Elapsed 4.3m | ETA 0.0m

2026-09-23 17:42:36,137 - INFO: Rec loss: 0.0007769916364220017
2026-09-23 17:42:36,137 - INFO: Seg loss: 0.3400835970988368
2026-09-23 17:42:36,137 - INFO: λ_rec: 1
2026-09-23 17:42:36,137 - INFO: λ_seg: 0.0001
2026-09-23 17:43:55,365 - INFO: -------------------Epoch: 219------------------------
2026-09-23 17:43:55,369 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.093794  0.971602  0.000161
2026-09-23 17:43:55,377 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995346  0.997618  0.996765  0.998573  0.995555
real potato   0.751829  0.858287  0.986100  0.759883  0.999700
fake potato   0.960865  0.979992  0.982933  0.977168  0.999971
real apple    0.785286  0.879681  0.909718  0.851659  0.999197
fake apple    0.824678  0.903867  0.983507  0.836243  0.999329
real orange   0.507662  0.673396  0.913690  0.533233  0.999319
fake orange   0.751111  0.857819  0.772807  0.963970  0.999086
real grape    0.673001  0.804494  0.912258  0.719579  0.999270
fake grape    0.871564  0.931325  0.909080  0.954791  0.999480
real lemon    0.517546  0.682036  0.541568  0.921059  0.998991
fake lemon    0.837233  0.911357  0.990520  0.843996  0.999653
real avocado  0.836144  0.910711  0.872350  0.952709  0.999827
fake avocado  0.820947  0.901621  0.997526  0.822622  0.999785
real pepper   0.812526  0.896517  0.887354  0.905974  0.999235
fake pepper   0.743807  0.853035  0.973408  0.759234  0.999377
real plant    0.842902  0.914705  0.917718  0.911810  0.998300
fake plant    0.842576  0.914513  0.908764  0.920437  0.999863
real banana   0.467849  0.637417  0.921871  0.487166  0.998755
fake banana   0.758004  0.862296  0.910625  0.818928  0.999519
real onion    0.638343  0.779206  0.657944  0.955413  0.999511
fake onion    0.957589  0.978285  0.984808  0.971947  0.999973
real unknown  0.851724  0.919875  0.898182  0.942748  0.999974
fake unknown  0.342868  0.510603  0.430578  0.627309  0.998987
total         0.756148  0.850376  0.880873  0.845063  0.999246
total(-bg)    0.745275  0.843684  0.875605  0.838085  0.999414
2026-09-23 17:43:55,912 - INFO: Epoch accounting: {'epoch': 219, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11299293, 55732, 62908, 122198, 128763, 77563, 76730, 111692, 204348, 71711, 60603, 41430, 48648, 241926, 98396, 200584, 25763, 74390, 58804, 83425, 58767, 10624, 23974], 'crops_with_class': [202, 33, 29, 34, 29, 23, 24, 22, 35, 31, 25, 13, 17, 55, 28, 26, 21, 22, 28, 40, 31, 10, 13], 'targeted_crops_by_class': [0, 9, 3, 6, 5, 3, 1, 4, 6, 6, 4, 5, 7, 1, 3, 6, 7, 4, 5, 2, 7, 4, 1], 'sampled_scene_counts': [0, 0, 1, 0, 0, 1, 3, 0, 1, 2, 1, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 1, 3, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 3, 1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 2, 0, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 2, 0, 2, 2, 2, 1, 1, 0, 2, 3, 1, 1, 0, 1, 0, 4, 1, 2, 2, 1, 1, 2, 1, 0, 1, 2, 1, 2, 1, 2, 1, 0, 1, 3, 3, 1, 0, 0, 1, 0, 1, 2, 0, 0, 0, 2, 0, 2, 2, 3, 0, 0, 1, 3, 1, 3, 1, 1, 1, 1, 1, 2, 1, 4, 3, 1, 0, 1, 2, 2, 3, 2, 1, 1, 3], 'learning_rate': 6.008553527815599e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007769916364220017, 'train_segmentation_loss': 0.3400835970988368, 'val_foreground_miou_all22': 0.7452751469793746, 'val_psnr_ref1': 38.0937939453125, 'elapsed_seconds': 334.84330010414124, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 220/500 | Batch 10/202 | Rec 0.000675 | Seg 0.325815 | Elapsed 0.2m | ETA 4.1m
Epoch 220/500 | Batch 20/202 | Rec 0.000710 | Seg 0.320822 | Elapsed 0.4m | ETA 3.9m
Epoch 220/500 | Batch 30/202 | Rec 0.000709 | Seg 0.315310 | Elapsed 0.6m | ETA 3.6m
Epoch 220/500 | Batch 40/202 | Rec 0.000756 | Seg 0.330169 | Elapsed 0.8m | ETA 3.4m
Epoch 220/500 | Batch 50/202 | Rec 0.000730 | Seg 0.327396 | Elapsed 1.1m | ETA 3.2m
Epoch 220/500 | Batch 60/202 | Rec 0.000776 | Seg 0.352518 | Elapsed 1.3m | ETA 3.0m
Epoch 220/500 | Batch 70/202 | Rec 0.000764 | Seg 0.347353 | Elapsed 1.5m | ETA 2.8m
Epoch 220/500 | Batch 80/202 | Rec 0.000765 | Seg 0.343373 | Elapsed 1.7m | ETA 2.6m
Epoch 220/500 | Batch 90/202 | Rec 0.000751 | Seg 0.339291 | Elapsed 1.9m | ETA 2.4m
Epoch 220/500 | Batch 100/202 | Rec 0.000751 | Seg 0.339680 | Elapsed 2.1m | ETA 2.2m
Epoch 220/500 | Batch 110/202 | Rec 0.000749 | Seg 0.337610 | Elapsed 2.3m | ETA 2.0m
Epoch 220/500 | Batch 120/202 | Rec 0.000760 | Seg 0.335615 | Elapsed 2.5m | ETA 1.7m
Epoch 220/500 | Batch 130/202 | Rec 0.000776 | Seg 0.340878 | Elapsed 2.8m | ETA 1.5m
Epoch 220/500 | Batch 140/202 | Rec 0.000777 | Seg 0.339550 | Elapsed 3.0m | ETA 1.3m
Epoch 220/500 | Batch 150/202 | Rec 0.000780 | Seg 0.345947 | Elapsed 3.2m | ETA 1.1m
Epoch 220/500 | Batch 160/202 | Rec 0.000805 | Seg 0.347224 | Elapsed 3.4m | ETA 0.9m
Epoch 220/500 | Batch 170/202 | Rec 0.000805 | Seg 0.347415 | Elapsed 3.6m | ETA 0.7m
Epoch 220/500 | Batch 180/202 | Rec 0.000796 | Seg 0.344149 | Elapsed 3.8m | ETA 0.5m
Epoch 220/500 | Batch 190/202 | Rec 0.000791 | Seg 0.345130 | Elapsed 4.0m | ETA 0.3m
Epoch 220/500 | Batch 200/202 | Rec 0.000788 | Seg 0.345549 | Elapsed 4.2m | ETA 0.0m
Epoch 220/500 | Batch 202/202 | Rec 0.000793 | Seg 0.346857 | Elapsed 4.3m | ETA 0.0m

2026-09-23 17:48:12,295 - INFO: Rec loss: 0.0007933516135020873
2026-09-23 17:48:12,296 - INFO: Seg loss: 0.3468574425666639
2026-09-23 17:48:12,296 - INFO: λ_rec: 1
2026-09-23 17:48:12,296 - INFO: λ_seg: 0.0001
2026-09-23 17:49:37,200 - INFO: -------------------Epoch: 220------------------------
2026-09-23 17:49:37,204 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.607479  0.971312  0.000181
2026-09-23 17:49:37,213 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995390  0.997640  0.996468  0.998915  0.995596
real potato   0.615375  0.761850  0.991619  0.618592  0.999537
fake potato   0.717431  0.835421  0.964110  0.737118  0.999789
real apple    0.717675  0.835585  0.871339  0.802742  0.998911
fake apple    0.731043  0.844578  0.959492  0.754324  0.998952
real orange   0.798242  0.887753  0.998842  0.798981  0.999734
fake orange   0.882822  0.937715  0.905012  0.972977  0.999630
real grape    0.716258  0.834625  0.945688  0.746985  0.999382
fake grape    0.841476  0.913865  0.902376  0.925752  0.999355
real lemon    0.376573  0.547069  0.450956  0.695404  0.998647
fake lemon    0.829366  0.906675  0.989425  0.836783  0.999636
real avocado  0.833788  0.909311  0.868830  0.953859  0.999823
fake avocado  0.423690  0.595158  0.999699  0.423744  0.999310
real pepper   0.851156  0.919544  0.928590  0.910771  0.999417
fake pepper   0.883373  0.938026  0.987752  0.893157  0.999719
real plant    0.859102  0.924162  0.939107  0.909782  0.998508
fake plant    0.865311  0.927743  0.951441  0.905291  0.999888
real banana   0.286212  0.445011  0.956756  0.289963  0.998375
fake banana   0.635250  0.776896  0.747356  0.808975  0.999146
real onion    0.643134  0.782765  0.664506  0.952373  0.999523
fake onion    0.942344  0.970267  0.988705  0.952600  0.999963
real unknown  0.876748  0.934277  0.912648  0.957061  0.999978
fake unknown  0.225319  0.367735  0.244127  0.745201  0.997841
total         0.719438  0.817116  0.876732  0.808320  0.999159
total(-bg)    0.706895  0.808910  0.871290  0.799656  0.999321
2026-09-23 17:49:37,794 - INFO: Epoch accounting: {'epoch': 220, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11298109, 60416, 52737, 115563, 137798, 48102, 67226, 159593, 172018, 57809, 47196, 39273, 39764, 259701, 87414, 181698, 18451, 104070, 77631, 85758, 72841, 10106, 44998], 'crops_with_class': [202, 35, 27, 29, 32, 18, 22, 30, 34, 30, 22, 14, 16, 59, 28, 22, 19, 27, 30, 36, 28, 11, 20], 'targeted_crops_by_class': [0, 9, 4, 3, 2, 2, 6, 5, 4, 2, 3, 3, 5, 4, 3, 2, 6, 4, 3, 5, 4, 6, 7], 'sampled_scene_counts': [0, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 0, 0, 2, 2, 0, 2, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 1, 2, 0, 0, 1, 1, 0, 3, 0, 1, 0, 3, 2, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 0, 0, 2, 0, 1, 3, 0, 0, 2, 0, 2, 1, 1, 0, 2, 1, 1, 2, 0, 2, 2, 1, 0, 0, 1, 2, 2, 3, 1, 2, 0, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 0, 1, 2, 2, 0, 2, 2, 0, 1, 2, 2, 1, 2, 0, 1, 0, 4, 1, 2, 2, 0, 4, 2, 1, 1, 1, 1, 1, 3, 1, 4, 1, 2, 1, 1], 'learning_rate': 5.97782797190366e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007933516135020873, 'train_segmentation_loss': 0.3468574425666639, 'val_foreground_miou_all22': 0.7068949534733442, 'val_psnr_ref1': 37.607479400634766, 'elapsed_seconds': 341.8732039928436, 'peak_cuda_allocated_gib': 7.506870269775391}

Epoch 221/500 | Batch 10/202 | Rec 0.000736 | Seg 0.333549 | Elapsed 0.2m | ETA 4.0m
Epoch 221/500 | Batch 20/202 | Rec 0.000714 | Seg 0.312835 | Elapsed 0.4m | ETA 3.8m
Epoch 221/500 | Batch 30/202 | Rec 0.000755 | Seg 0.362138 | Elapsed 0.6m | ETA 3.7m
Epoch 221/500 | Batch 40/202 | Rec 0.000777 | Seg 0.370884 | Elapsed 0.9m | ETA 3.4m
Epoch 221/500 | Batch 50/202 | Rec 0.000827 | Seg 0.355961 | Elapsed 1.1m | ETA 3.2m
Epoch 221/500 | Batch 60/202 | Rec 0.000816 | Seg 0.357338 | Elapsed 1.3m | ETA 3.0m
Epoch 221/500 | Batch 70/202 | Rec 0.000798 | Seg 0.353877 | Elapsed 1.5m | ETA 2.8m
Epoch 221/500 | Batch 80/202 | Rec 0.000804 | Seg 0.349876 | Elapsed 1.7m | ETA 2.6m
Epoch 221/500 | Batch 90/202 | Rec 0.000787 | Seg 0.349731 | Elapsed 1.9m | ETA 2.4m
Epoch 221/500 | Batch 100/202 | Rec 0.000762 | Seg 0.340473 | Elapsed 2.1m | ETA 2.1m
Epoch 221/500 | Batch 110/202 | Rec 0.000778 | Seg 0.346828 | Elapsed 2.3m | ETA 1.9m
Epoch 221/500 | Batch 120/202 | Rec 0.000769 | Seg 0.341670 | Elapsed 2.5m | ETA 1.7m
Epoch 221/500 | Batch 130/202 | Rec 0.000788 | Seg 0.352156 | Elapsed 2.7m | ETA 1.5m
Epoch 221/500 | Batch 140/202 | Rec 0.000785 | Seg 0.352114 | Elapsed 2.9m | ETA 1.3m
Epoch 221/500 | Batch 150/202 | Rec 0.000792 | Seg 0.351812 | Elapsed 3.2m | ETA 1.1m
Epoch 221/500 | Batch 160/202 | Rec 0.000795 | Seg 0.349144 | Elapsed 3.4m | ETA 0.9m
Epoch 221/500 | Batch 170/202 | Rec 0.000798 | Seg 0.355296 | Elapsed 3.6m | ETA 0.7m
Epoch 221/500 | Batch 180/202 | Rec 0.000800 | Seg 0.356793 | Elapsed 3.8m | ETA 0.5m
Epoch 221/500 | Batch 190/202 | Rec 0.000794 | Seg 0.354414 | Elapsed 4.0m | ETA 0.3m
Epoch 221/500 | Batch 200/202 | Rec 0.000786 | Seg 0.349797 | Elapsed 4.2m | ETA 0.0m
Epoch 221/500 | Batch 202/202 | Rec 0.000785 | Seg 0.350576 | Elapsed 4.2m | ETA 0.0m

2026-09-23 17:53:52,276 - INFO: Rec loss: 0.0007854886203894788
2026-09-23 17:53:52,276 - INFO: Seg loss: 0.350576200291957
2026-09-23 17:53:52,276 - INFO: λ_rec: 1
2026-09-23 17:53:52,276 - INFO: λ_seg: 0.0001
2026-09-23 17:55:11,963 - INFO: -------------------Epoch: 221------------------------
2026-09-23 17:55:11,966 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  37.869485  0.971497  0.00017
2026-09-23 17:55:11,972 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995120  0.997504  0.996193  0.998918  0.995336
real potato   0.339837  0.507243  1.000000  0.339837  0.999210
fake potato   0.678867  0.808672  0.981465  0.687683  0.999763
real apple    0.610540  0.758131  0.767491  0.749093  0.998351
fake apple    0.741602  0.851583  0.984568  0.750323  0.999013
real orange   0.800092  0.888896  0.986859  0.808708  0.999734
fake orange   0.855432  0.922034  0.881193  0.966954  0.999532
real grape    0.620397  0.765686  0.916565  0.657531  0.999160
fake grape    0.862289  0.926003  0.930858  0.921297  0.999456
real lemon    0.352694  0.521423  0.412467  0.708777  0.998471
fake lemon    0.845508  0.916238  0.994010  0.849838  0.999671
real avocado  0.767978  0.868714  0.798760  0.952217  0.999733
fake avocado  0.544307  0.704875  0.999766  0.544376  0.999455
real pepper   0.815990  0.898623  0.951387  0.851493  0.999298
fake pepper   0.746725  0.854951  0.997780  0.747967  0.999395
real plant    0.822721  0.902689  0.884224  0.922047  0.998013
fake plant    0.770781  0.870505  0.861325  0.879985  0.999792
real banana   0.279567  0.436937  0.987100  0.280592  0.998375
fake banana   0.694154  0.819420  0.854839  0.786911  0.999362
real onion    0.623835  0.768298  0.680976  0.881439  0.999520
fake onion    0.895461  0.944798  0.998116  0.896977  0.999934
real unknown  0.507880  0.673589  0.520855  0.953244  0.999852
fake unknown  0.235310  0.380937  0.252231  0.778160  0.997869
total         0.669873  0.782076  0.853871  0.778886  0.999056
total(-bg)    0.655089  0.772284  0.847402  0.768884  0.999225
2026-09-23 17:55:12,478 - INFO: Epoch accounting: {'epoch': 221, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11252450, 51312, 62825, 91679, 190469, 98026, 69543, 113820, 197889, 68159, 70189, 71663, 43671, 214026, 106985, 151449, 18808, 110132, 69887, 79900, 46597, 15824, 42969], 'crops_with_class': [202, 29, 29, 32, 40, 28, 25, 22, 36, 35, 29, 25, 15, 49, 28, 24, 21, 30, 27, 34, 22, 15, 20], 'targeted_crops_by_class': [0, 4, 6, 7, 1, 2, 4, 4, 6, 4, 7, 10, 5, 3, 2, 4, 3, 6, 4, 5, 7, 6, 4], 'sampled_scene_counts': [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 2, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 3, 1, 2, 0, 2, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 3, 2, 1, 3, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 0, 3, 1, 0, 5, 3, 1, 0, 0, 1, 4, 2, 2, 4, 1, 2, 1, 3, 2, 1, 1, 0, 1, 0, 2, 3, 0, 2, 1, 1, 0, 1, 1, 2, 3, 0, 1, 2, 0, 4, 5, 1, 2, 1, 0, 4, 1, 1, 1, 2, 1, 1, 3, 1, 2, 1, 3, 1, 1, 0, 2, 0, 2, 0, 1, 1, 0, 2, 0, 1, 7, 1, 1, 0, 1, 1, 1, 2, 2, 0, 1], 'learning_rate': 5.947064306496296e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007854886203894788, 'train_segmentation_loss': 0.350576200291957, 'val_foreground_miou_all22': 0.6550893279429776, 'val_psnr_ref1': 37.86948486328125, 'elapsed_seconds': 334.67636942863464, 'peak_cuda_allocated_gib': 7.511508941650391}

Epoch 222/500 | Batch 10/202 | Rec 0.000749 | Seg 0.370157 | Elapsed 0.2m | ETA 4.0m
Epoch 222/500 | Batch 20/202 | Rec 0.000835 | Seg 0.376859 | Elapsed 0.4m | ETA 3.8m
Epoch 222/500 | Batch 30/202 | Rec 0.000828 | Seg 0.351539 | Elapsed 0.6m | ETA 3.6m
Epoch 222/500 | Batch 40/202 | Rec 0.000847 | Seg 0.371085 | Elapsed 0.8m | ETA 3.4m
Epoch 222/500 | Batch 50/202 | Rec 0.000851 | Seg 0.363328 | Elapsed 1.0m | ETA 3.2m
Epoch 222/500 | Batch 60/202 | Rec 0.000878 | Seg 0.369515 | Elapsed 1.3m | ETA 3.0m
Epoch 222/500 | Batch 70/202 | Rec 0.000883 | Seg 0.373479 | Elapsed 1.5m | ETA 2.8m
Epoch 222/500 | Batch 80/202 | Rec 0.000875 | Seg 0.375504 | Elapsed 1.7m | ETA 2.6m
Epoch 222/500 | Batch 90/202 | Rec 0.000870 | Seg 0.377607 | Elapsed 1.9m | ETA 2.3m
Epoch 222/500 | Batch 100/202 | Rec 0.000886 | Seg 0.389733 | Elapsed 2.1m | ETA 2.1m
Epoch 222/500 | Batch 110/202 | Rec 0.000879 | Seg 0.392378 | Elapsed 2.3m | ETA 1.9m
Epoch 222/500 | Batch 120/202 | Rec 0.000873 | Seg 0.385727 | Elapsed 2.5m | ETA 1.7m
Epoch 222/500 | Batch 130/202 | Rec 0.000861 | Seg 0.381002 | Elapsed 2.7m | ETA 1.5m
Epoch 222/500 | Batch 140/202 | Rec 0.000864 | Seg 0.383718 | Elapsed 2.9m | ETA 1.3m
Epoch 222/500 | Batch 150/202 | Rec 0.000857 | Seg 0.377496 | Elapsed 3.1m | ETA 1.1m
Epoch 222/500 | Batch 160/202 | Rec 0.000849 | Seg 0.371483 | Elapsed 3.3m | ETA 0.9m
Epoch 222/500 | Batch 170/202 | Rec 0.000840 | Seg 0.369541 | Elapsed 3.6m | ETA 0.7m
Epoch 222/500 | Batch 180/202 | Rec 0.000839 | Seg 0.368921 | Elapsed 3.8m | ETA 0.5m
Epoch 222/500 | Batch 190/202 | Rec 0.000837 | Seg 0.369866 | Elapsed 4.0m | ETA 0.3m
Epoch 222/500 | Batch 200/202 | Rec 0.000833 | Seg 0.366868 | Elapsed 4.2m | ETA 0.0m
Epoch 222/500 | Batch 202/202 | Rec 0.000834 | Seg 0.366101 | Elapsed 4.2m | ETA 0.0m

2026-09-23 17:59:25,855 - INFO: Rec loss: 0.0008344876496086709
2026-09-23 17:59:25,855 - INFO: Seg loss: 0.36610093828991497
2026-09-23 17:59:25,855 - INFO: λ_rec: 1
2026-09-23 17:59:25,856 - INFO: λ_seg: 0.0001
2026-09-23 18:00:49,378 - INFO: -------------------Epoch: 222------------------------
2026-09-23 18:00:49,382 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  37.988835  0.97177  0.000165
2026-09-23 18:00:49,389 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995537  0.997714  0.996625  0.998905  0.995737
real potato   0.661284  0.796064  0.984044  0.668452  0.999590
fake potato   0.914841  0.955477  0.975764  0.936112  0.999937
real apple    0.719328  0.836705  0.876465  0.800487  0.998922
fake apple    0.654104  0.790838  0.988069  0.659311  0.998684
real orange   0.740016  0.850536  0.977017  0.753126  0.999651
fake orange   0.849786  0.918744  0.860179  0.985982  0.999501
real grape    0.821663  0.902052  0.908963  0.895345  0.999594
fake grape    0.877439  0.934669  0.947839  0.921957  0.999524
real lemon    0.470295  0.639683  0.501921  0.881849  0.998833
fake lemon    0.843347  0.914967  0.992993  0.848395  0.999667
real avocado  0.787740  0.881220  0.812873  0.962233  0.999759
fake avocado  0.629734  0.772758  0.999798  0.629814  0.999557
real pepper   0.864176  0.927090  0.950329  0.905056  0.999480
fake pepper   0.875914  0.933803  0.973339  0.897446  0.999697
real plant    0.862843  0.926323  0.968214  0.887997  0.998588
fake plant    0.846209  0.916649  0.928600  0.905100  0.999869
real banana   0.413022  0.584551  0.935315  0.425166  0.998642
fake banana   0.741218  0.851329  0.859255  0.843646  0.999458
real onion    0.670559  0.802747  0.694815  0.950515  0.999578
fake onion    0.961253  0.980194  0.988684  0.971947  0.999975
real unknown  0.747204  0.855264  0.773745  0.956107  0.999948
fake unknown  0.230699  0.374869  0.251963  0.732162  0.997943
total         0.746879  0.841054  0.875948  0.844222  0.999223
total(-bg)    0.735576  0.833933  0.870463  0.837191  0.999382
2026-09-23 18:00:49,958 - INFO: Epoch accounting: {'epoch': 222, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11145222, 46094, 48129, 80900, 139401, 74255, 75229, 172761, 236826, 88244, 85826, 32939, 28357, 227975, 145063, 219284, 20746, 88082, 77267, 93841, 56746, 11634, 43451], 'crops_with_class': [202, 31, 28, 27, 35, 27, 28, 34, 44, 37, 34, 9, 13, 57, 38, 24, 20, 24, 30, 45, 26, 15, 20], 'targeted_crops_by_class': [0, 8, 5, 2, 7, 7, 4, 2, 6, 6, 8, 2, 3, 5, 5, 7, 4, 4, 6, 5, 2, 4, 7], 'sampled_scene_counts': [0, 1, 0, 1, 2, 0, 0, 0, 3, 3, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 3, 1, 0, 1, 1, 1, 3, 1, 0, 1, 0, 2, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 2, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 2, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 3, 0, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 3, 4, 4, 0, 0, 1, 1, 2, 1, 0, 1, 3, 2, 1, 2, 2, 0, 2, 0, 1, 0, 0, 2, 3, 3, 2, 1, 0, 2, 1, 0, 1, 1, 2, 2, 1, 2, 0, 2, 3, 3, 3, 0, 1, 3, 1, 3, 4, 1, 2, 1, 1, 0, 5, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 3, 2, 1, 2, 1, 1, 0, 1, 2, 5, 1, 1], 'learning_rate': 5.916263746090342e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0008344876496086709, 'train_segmentation_loss': 0.36610093828991497, 'val_foreground_miou_all22': 0.735576077004941, 'val_psnr_ref1': 37.988835144042966, 'elapsed_seconds': 337.47189927101135, 'peak_cuda_allocated_gib': 7.505535125732422}

Epoch 223/500 | Batch 10/202 | Rec 0.000829 | Seg 0.334700 | Elapsed 0.2m | ETA 4.1m
Epoch 223/500 | Batch 20/202 | Rec 0.000791 | Seg 0.305989 | Elapsed 0.4m | ETA 3.8m
Epoch 223/500 | Batch 30/202 | Rec 0.000789 | Seg 0.346402 | Elapsed 0.6m | ETA 3.6m
Epoch 223/500 | Batch 40/202 | Rec 0.000773 | Seg 0.324899 | Elapsed 0.8m | ETA 3.4m
Epoch 223/500 | Batch 50/202 | Rec 0.000797 | Seg 0.339334 | Elapsed 1.1m | ETA 3.2m
Epoch 223/500 | Batch 60/202 | Rec 0.000783 | Seg 0.326319 | Elapsed 1.3m | ETA 3.0m
Epoch 223/500 | Batch 70/202 | Rec 0.000785 | Seg 0.331798 | Elapsed 1.5m | ETA 2.8m
Epoch 223/500 | Batch 80/202 | Rec 0.000786 | Seg 0.332856 | Elapsed 1.7m | ETA 2.6m
Epoch 223/500 | Batch 90/202 | Rec 0.000809 | Seg 0.330934 | Elapsed 1.9m | ETA 2.4m
Epoch 223/500 | Batch 100/202 | Rec 0.000796 | Seg 0.328842 | Elapsed 2.1m | ETA 2.2m
Epoch 223/500 | Batch 110/202 | Rec 0.000794 | Seg 0.331782 | Elapsed 2.3m | ETA 1.9m
Epoch 223/500 | Batch 120/202 | Rec 0.000787 | Seg 0.334568 | Elapsed 2.5m | ETA 1.7m
Epoch 223/500 | Batch 130/202 | Rec 0.000782 | Seg 0.334401 | Elapsed 2.7m | ETA 1.5m
Epoch 223/500 | Batch 140/202 | Rec 0.000784 | Seg 0.338058 | Elapsed 3.0m | ETA 1.3m
Epoch 223/500 | Batch 150/202 | Rec 0.000783 | Seg 0.337237 | Elapsed 3.2m | ETA 1.1m
Epoch 223/500 | Batch 160/202 | Rec 0.000788 | Seg 0.335385 | Elapsed 3.4m | ETA 0.9m
Epoch 223/500 | Batch 170/202 | Rec 0.000781 | Seg 0.333463 | Elapsed 3.6m | ETA 0.7m
Epoch 223/500 | Batch 180/202 | Rec 0.000771 | Seg 0.331400 | Elapsed 3.8m | ETA 0.5m
Epoch 223/500 | Batch 190/202 | Rec 0.000771 | Seg 0.330491 | Elapsed 4.0m | ETA 0.3m
Epoch 223/500 | Batch 200/202 | Rec 0.000770 | Seg 0.329540 | Elapsed 4.2m | ETA 0.0m
Epoch 223/500 | Batch 202/202 | Rec 0.000770 | Seg 0.329226 | Elapsed 4.3m | ETA 0.0m

2026-09-23 18:05:07,151 - INFO: Rec loss: 0.0007703483028632432
2026-09-23 18:05:07,151 - INFO: Seg loss: 0.3292258542289238
2026-09-23 18:05:07,151 - INFO: λ_rec: 1
2026-09-23 18:05:07,151 - INFO: λ_seg: 0.0001
2026-09-23 18:06:29,524 - INFO: -------------------Epoch: 223------------------------
2026-09-23 18:06:29,528 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.216087  0.97215  0.000157
2026-09-23 18:06:29,534 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995618  0.997754  0.996874  0.998737  0.995816
real potato   0.532365  0.694782  0.998566  0.532772  0.999440
fake potato   0.831827  0.908144  0.976851  0.848555  0.999875
real apple    0.675178  0.806047  0.842077  0.773065  0.998717
fake apple    0.723319  0.839400  0.976775  0.735976  0.998937
real orange   0.667737  0.800722  0.985944  0.674155  0.999558
fake orange   0.836127  0.910701  0.842146  0.991525  0.999444
real grape    0.469907  0.639323  0.874651  0.503837  0.998813
fake grape    0.782997  0.878243  0.838510  0.922039  0.999055
real lemon    0.397469  0.568794  0.465943  0.730070  0.998699
fake lemon    0.850061  0.918905  0.992140  0.855824  0.999681
real avocado  0.778539  0.875432  0.810429  0.951888  0.999748
fake avocado  0.719024  0.836500  0.995251  0.721500  0.999663
real pepper   0.817795  0.899716  0.927733  0.873436  0.999288
fake pepper   0.907833  0.951640  0.976429  0.928174  0.999775
real plant    0.843404  0.915001  0.908664  0.921528  0.998289
fake plant    0.853469  0.920892  0.895347  0.948044  0.999870
real banana   0.387174  0.558178  0.945372  0.396034  0.998591
fake banana   0.660949  0.795819  0.780480  0.811878  0.999234
real onion    0.645172  0.784274  0.660692  0.964871  0.999521
fake onion    0.958442  0.978730  0.981517  0.976058  0.999973
real unknown  0.711806  0.831594  0.723359  0.978053  0.999937
fake unknown  0.270616  0.425919  0.300349  0.732162  0.998337
total         0.709427  0.814631  0.856352  0.816095  0.999142
total(-bg)    0.696419  0.806307  0.849965  0.807793  0.999293
2026-09-23 18:06:30,051 - INFO: Epoch accounting: {'epoch': 223, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11355332, 47061, 78735, 112387, 142403, 50580, 61619, 135105, 214411, 66671, 54233, 30303, 32739, 173551, 120137, 183693, 22457, 86004, 79347, 93580, 47125, 11417, 39382], 'crops_with_class': [202, 29, 33, 28, 32, 19, 23, 28, 37, 30, 23, 13, 11, 47, 33, 27, 25, 28, 32, 40, 28, 11, 19], 'targeted_crops_by_class': [0, 4, 3, 4, 1, 2, 3, 4, 5, 1, 6, 5, 3, 5, 6, 2, 3, 1, 7, 7, 3, 4, 4], 'sampled_scene_counts': [1, 0, 1, 0, 1, 1, 1, 0, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 0, 2, 3, 1, 1, 0, 1, 0, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 2, 3, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 3, 1, 1, 0, 1, 4, 1, 3, 2, 2, 0, 1, 1, 0, 2, 3, 1, 1, 1, 3, 1, 2, 0, 1, 1, 1, 1, 1, 2, 2, 3, 1, 1, 2, 2, 2, 1, 2, 1, 0, 0, 2, 2, 2, 0, 1, 2, 0, 3, 1, 2, 1, 1, 4, 1, 0, 0, 0, 1, 3, 2, 1, 1, 0, 1, 1, 0, 2, 1, 3, 1], 'learning_rate': 5.885427506639185e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007703483028632432, 'train_segmentation_loss': 0.3292258542289238, 'val_foreground_miou_all22': 0.696418663580594, 'val_psnr_ref1': 38.21608749389648, 'elapsed_seconds': 340.08418011665344, 'peak_cuda_allocated_gib': 7.509830474853516}

Epoch 224/500 | Batch 10/202 | Rec 0.000733 | Seg 0.315939 | Elapsed 0.2m | ETA 4.0m
Epoch 224/500 | Batch 20/202 | Rec 0.000789 | Seg 0.343813 | Elapsed 0.4m | ETA 3.8m
Epoch 224/500 | Batch 30/202 | Rec 0.000815 | Seg 0.365303 | Elapsed 0.6m | ETA 3.6m
Epoch 224/500 | Batch 40/202 | Rec 0.000807 | Seg 0.363522 | Elapsed 0.8m | ETA 3.4m
Epoch 224/500 | Batch 50/202 | Rec 0.000769 | Seg 0.333561 | Elapsed 1.0m | ETA 3.2m
Epoch 224/500 | Batch 60/202 | Rec 0.000751 | Seg 0.331416 | Elapsed 1.3m | ETA 3.0m
Epoch 224/500 | Batch 70/202 | Rec 0.000753 | Seg 0.331558 | Elapsed 1.5m | ETA 2.8m
Epoch 224/500 | Batch 80/202 | Rec 0.000762 | Seg 0.331325 | Elapsed 1.7m | ETA 2.6m
Epoch 224/500 | Batch 90/202 | Rec 0.000753 | Seg 0.331483 | Elapsed 1.9m | ETA 2.4m
Epoch 224/500 | Batch 100/202 | Rec 0.000736 | Seg 0.325941 | Elapsed 2.1m | ETA 2.2m
Epoch 224/500 | Batch 110/202 | Rec 0.000738 | Seg 0.327150 | Elapsed 2.3m | ETA 1.9m
Epoch 224/500 | Batch 120/202 | Rec 0.000731 | Seg 0.327353 | Elapsed 2.5m | ETA 1.7m
Epoch 224/500 | Batch 130/202 | Rec 0.000730 | Seg 0.330074 | Elapsed 2.8m | ETA 1.5m
Epoch 224/500 | Batch 140/202 | Rec 0.000721 | Seg 0.323997 | Elapsed 3.0m | ETA 1.3m
Epoch 224/500 | Batch 150/202 | Rec 0.000739 | Seg 0.331527 | Elapsed 3.2m | ETA 1.1m
Epoch 224/500 | Batch 160/202 | Rec 0.000733 | Seg 0.329827 | Elapsed 3.4m | ETA 0.9m
Epoch 224/500 | Batch 170/202 | Rec 0.000736 | Seg 0.327103 | Elapsed 3.6m | ETA 0.7m
Epoch 224/500 | Batch 180/202 | Rec 0.000740 | Seg 0.332443 | Elapsed 3.8m | ETA 0.5m
Epoch 224/500 | Batch 190/202 | Rec 0.000738 | Seg 0.331603 | Elapsed 4.0m | ETA 0.3m
Epoch 224/500 | Batch 200/202 | Rec 0.000739 | Seg 0.331109 | Elapsed 4.2m | ETA 0.0m
Epoch 224/500 | Batch 202/202 | Rec 0.000740 | Seg 0.332458 | Elapsed 4.3m | ETA 0.0m

2026-09-23 18:10:46,235 - INFO: Rec loss: 0.000739834118720333
2026-09-23 18:10:46,236 - INFO: Seg loss: 0.33245761771133114
2026-09-23 18:10:46,236 - INFO: λ_rec: 1
2026-09-23 18:10:46,236 - INFO: λ_seg: 0.0001
2026-09-23 18:12:03,430 - INFO: -------------------Epoch: 224------------------------
2026-09-23 18:12:03,434 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.271566  0.972261  0.000156
2026-09-23 18:12:03,441 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995135  0.997511  0.996231  0.998895  0.995351
real potato   0.204157  0.339059  1.000000  0.204157  0.999048
fake potato   0.621767  0.766730  0.980744  0.629451  0.999721
real apple    0.646646  0.785360  0.754864  0.818532  0.998457
fake apple    0.691183  0.817347  0.995186  0.693501  0.998830
real orange   0.811010  0.895594  0.993370  0.815424  0.999750
fake orange   0.885434  0.939186  0.917285  0.962264  0.999644
real grape    0.367461  0.537395  0.975399  0.370898  0.998667
fake grape    0.828986  0.906448  0.922125  0.891391  0.999320
real lemon    0.326544  0.492276  0.399579  0.641132  0.998446
fake lemon    0.814050  0.897445  0.996304  0.816516  0.999605
real avocado  0.751781  0.858255  0.819349  0.901149  0.999724
fake avocado  0.362477  0.532044  0.926266  0.373247  0.999214
real pepper   0.842606  0.914531  0.952643  0.879443  0.999399
fake pepper   0.792308  0.884071  0.997426  0.793931  0.999504
real plant    0.804704  0.891735  0.851706  0.935822  0.997728
fake plant    0.877760  0.934851  0.932316  0.937500  0.999896
real banana   0.238118  0.384613  0.976197  0.239508  0.998278
fake banana   0.608366  0.756452  0.730716  0.784174  0.999071
real onion    0.654921  0.791434  0.709673  0.894612  0.999574
fake onion    0.927398  0.962282  0.983342  0.942201  0.999953
real unknown  0.936389  0.967100  0.979452  0.955153  0.999990
fake unknown  0.205987  0.341575  0.214405  0.839913  0.997272
total         0.660660  0.764926  0.869764  0.752992  0.998976
total(-bg)    0.645457  0.754354  0.864016  0.741815  0.999141
2026-09-23 18:12:04,167 - INFO: Epoch accounting: {'epoch': 224, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11351252, 48125, 48689, 115966, 117184, 77602, 73650, 143685, 201904, 79055, 58537, 49835, 37498, 226653, 103460, 205043, 33068, 78499, 49552, 63582, 34872, 9455, 31106], 'crops_with_class': [202, 31, 23, 28, 31, 25, 29, 30, 35, 36, 24, 19, 13, 54, 23, 23, 31, 19, 20, 28, 16, 10, 16], 'targeted_crops_by_class': [0, 6, 2, 5, 4, 2, 6, 4, 5, 1, 4, 6, 6, 4, 3, 8, 6, 4, 4, 0, 3, 4, 5], 'sampled_scene_counts': [0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 3, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 2, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 1, 3, 1, 1, 1, 1, 2, 0, 1, 0, 0, 1, 1, 3, 2, 3, 1, 1, 2, 4, 4, 3, 0, 1, 2, 4, 0, 0, 0, 2, 3, 1, 1, 1, 1, 3, 2, 1, 1, 2, 0, 2, 1, 0, 3, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 2, 0, 4, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2], 'learning_rate': 5.854556805504755e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000739834118720333, 'train_segmentation_loss': 0.33245761771133114, 'val_foreground_miou_all22': 0.6454568899714632, 'val_psnr_ref1': 38.27156585693359, 'elapsed_seconds': 334.10780596733093, 'peak_cuda_allocated_gib': 7.509586334228516}

Epoch 225/500 | Batch 10/202 | Rec 0.000696 | Seg 0.285843 | Elapsed 0.2m | ETA 3.9m
Epoch 225/500 | Batch 20/202 | Rec 0.000777 | Seg 0.360968 | Elapsed 0.4m | ETA 3.7m
Epoch 225/500 | Batch 30/202 | Rec 0.000779 | Seg 0.347979 | Elapsed 0.6m | ETA 3.6m
Epoch 225/500 | Batch 40/202 | Rec 0.000763 | Seg 0.340599 | Elapsed 0.8m | ETA 3.4m
Epoch 225/500 | Batch 50/202 | Rec 0.000802 | Seg 0.345913 | Elapsed 1.0m | ETA 3.2m
Epoch 225/500 | Batch 60/202 | Rec 0.000784 | Seg 0.345804 | Elapsed 1.3m | ETA 3.0m
Epoch 225/500 | Batch 70/202 | Rec 0.000776 | Seg 0.342043 | Elapsed 1.5m | ETA 2.8m
Epoch 225/500 | Batch 80/202 | Rec 0.000756 | Seg 0.333615 | Elapsed 1.7m | ETA 2.6m
Epoch 225/500 | Batch 90/202 | Rec 0.000763 | Seg 0.337097 | Elapsed 1.9m | ETA 2.3m
Epoch 225/500 | Batch 100/202 | Rec 0.000771 | Seg 0.342840 | Elapsed 2.1m | ETA 2.1m
Epoch 225/500 | Batch 110/202 | Rec 0.000781 | Seg 0.344880 | Elapsed 2.3m | ETA 1.9m
Epoch 225/500 | Batch 120/202 | Rec 0.000769 | Seg 0.335428 | Elapsed 2.5m | ETA 1.7m
Epoch 225/500 | Batch 130/202 | Rec 0.000776 | Seg 0.337326 | Elapsed 2.7m | ETA 1.5m
Epoch 225/500 | Batch 140/202 | Rec 0.000770 | Seg 0.334370 | Elapsed 2.9m | ETA 1.3m
Epoch 225/500 | Batch 150/202 | Rec 0.000758 | Seg 0.331889 | Elapsed 3.1m | ETA 1.1m
Epoch 225/500 | Batch 160/202 | Rec 0.000756 | Seg 0.333617 | Elapsed 3.4m | ETA 0.9m
Epoch 225/500 | Batch 170/202 | Rec 0.000758 | Seg 0.333287 | Elapsed 3.6m | ETA 0.7m
Epoch 225/500 | Batch 180/202 | Rec 0.000750 | Seg 0.329229 | Elapsed 3.8m | ETA 0.5m
Epoch 225/500 | Batch 190/202 | Rec 0.000750 | Seg 0.331159 | Elapsed 4.0m | ETA 0.3m
Epoch 225/500 | Batch 200/202 | Rec 0.000759 | Seg 0.329044 | Elapsed 4.2m | ETA 0.0m
Epoch 225/500 | Batch 202/202 | Rec 0.000757 | Seg 0.328235 | Elapsed 4.2m | ETA 0.0m

2026-09-23 18:16:17,359 - INFO: Rec loss: 0.0007573423894481863
2026-09-23 18:16:17,359 - INFO: Seg loss: 0.3282345852418111
2026-09-23 18:16:17,359 - INFO: λ_rec: 1
2026-09-23 18:16:17,359 - INFO: λ_seg: 0.0001
2026-09-23 18:17:37,316 - INFO: -------------------Epoch: 225------------------------
2026-09-23 18:17:37,320 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.226786  0.97222  0.000158
2026-09-23 18:17:37,326 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995422  0.997656  0.996670  0.998744  0.995627
real potato   0.453468  0.623937  0.999438  0.453583  0.999346
fake potato   0.682805  0.811460  0.994529  0.685379  0.999768
real apple    0.720580  0.837551  0.814301  0.862273  0.998846
fake apple    0.726061  0.841244  0.990474  0.731167  0.998958
real orange   0.774977  0.873176  0.975422  0.790412  0.999698
fake orange   0.878230  0.935118  0.901881  0.971005  0.999615
real grape    0.735635  0.847634  0.905003  0.797194  0.999402
fake grape    0.881858  0.937171  0.944384  0.930165  0.999539
real lemon    0.448479  0.619196  0.478067  0.878733  0.998730
fake lemon    0.848748  0.918137  0.986899  0.858420  0.999676
real avocado  0.747425  0.855409  0.775788  0.953366  0.999701
fake avocado  0.664209  0.798179  0.995617  0.666157  0.999597
real pepper   0.805718  0.892357  0.900944  0.884031  0.999220
fake pepper   0.790809  0.883137  0.976207  0.806350  0.999492
real plant    0.855943  0.922331  0.927718  0.917104  0.998456
fake plant    0.769579  0.869738  0.806520  0.943827  0.999775
real banana   0.362908  0.532509  0.935644  0.372199  0.998532
fake banana   0.724249  0.840025  0.859237  0.821749  0.999424
real onion    0.657153  0.793062  0.705179  0.906097  0.999573
fake onion    0.943278  0.970761  0.997957  0.945103  0.999964
real unknown  0.697095  0.821467  0.716927  0.961832  0.999933
fake unknown  0.281178  0.438894  0.314185  0.727997  0.998432
total         0.715035  0.820006  0.865174  0.820126  0.999187
total(-bg)    0.702290  0.811931  0.859196  0.812007  0.999349
2026-09-23 18:17:37,835 - INFO: Epoch accounting: {'epoch': 225, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11345147, 54783, 70203, 106084, 114954, 80231, 74636, 114942, 194731, 58066, 50307, 27655, 49308, 221203, 128802, 139039, 20632, 79319, 80517, 77248, 71236, 18517, 60712], 'crops_with_class': [202, 33, 29, 26, 32, 27, 25, 25, 33, 28, 23, 10, 18, 52, 35, 18, 21, 24, 36, 36, 28, 19, 23], 'targeted_crops_by_class': [0, 7, 6, 3, 3, 6, 4, 4, 3, 3, 5, 4, 5, 4, 2, 2, 3, 6, 4, 6, 8, 6, 8], 'sampled_scene_counts': [1, 0, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 3, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 2, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 1, 1, 3, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 3, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 3, 2, 0, 1, 3, 1, 1, 0, 0, 2, 2, 3, 2, 1, 1, 2, 1, 1, 0, 0, 3, 1, 1, 1, 5, 2, 5, 2, 3, 1, 1, 1, 1, 3, 2, 1, 1, 1, 2, 1, 2, 3, 1, 1, 2, 1, 1, 1, 1, 1, 0, 2, 4, 5, 1, 0, 0, 0, 0, 1, 0, 2, 1, 2, 3, 1, 3], 'learning_rate': 5.8236528614094774e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007573423894481863, 'train_segmentation_loss': 0.3282345852418111, 'val_foreground_miou_all22': 0.7022902719357762, 'val_psnr_ref1': 38.226786041259764, 'elapsed_seconds': 333.6604416370392, 'peak_cuda_allocated_gib': 7.508335113525391}

Epoch 226/500 | Batch 10/202 | Rec 0.000701 | Seg 0.288842 | Elapsed 0.2m | ETA 3.9m
Epoch 226/500 | Batch 20/202 | Rec 0.000698 | Seg 0.277303 | Elapsed 0.4m | ETA 3.7m
Epoch 226/500 | Batch 30/202 | Rec 0.000703 | Seg 0.296226 | Elapsed 0.6m | ETA 3.6m
Epoch 226/500 | Batch 40/202 | Rec 0.000744 | Seg 0.323704 | Elapsed 0.8m | ETA 3.4m
Epoch 226/500 | Batch 50/202 | Rec 0.000746 | Seg 0.329463 | Elapsed 1.0m | ETA 3.2m
Epoch 226/500 | Batch 60/202 | Rec 0.000761 | Seg 0.338467 | Elapsed 1.3m | ETA 3.0m
Epoch 226/500 | Batch 70/202 | Rec 0.000770 | Seg 0.345083 | Elapsed 1.5m | ETA 2.8m
Epoch 226/500 | Batch 80/202 | Rec 0.000776 | Seg 0.350130 | Elapsed 1.7m | ETA 2.6m
Epoch 226/500 | Batch 90/202 | Rec 0.000777 | Seg 0.357693 | Elapsed 1.9m | ETA 2.3m
Epoch 226/500 | Batch 100/202 | Rec 0.000768 | Seg 0.352482 | Elapsed 2.1m | ETA 2.1m
Epoch 226/500 | Batch 110/202 | Rec 0.000766 | Seg 0.356172 | Elapsed 2.3m | ETA 1.9m
Epoch 226/500 | Batch 120/202 | Rec 0.000769 | Seg 0.358093 | Elapsed 2.5m | ETA 1.7m
Epoch 226/500 | Batch 130/202 | Rec 0.000767 | Seg 0.350170 | Elapsed 2.7m | ETA 1.5m
Epoch 226/500 | Batch 140/202 | Rec 0.000771 | Seg 0.347362 | Elapsed 2.9m | ETA 1.3m
Epoch 226/500 | Batch 150/202 | Rec 0.000777 | Seg 0.351605 | Elapsed 3.1m | ETA 1.1m
Epoch 226/500 | Batch 160/202 | Rec 0.000776 | Seg 0.350798 | Elapsed 3.3m | ETA 0.9m
Epoch 226/500 | Batch 170/202 | Rec 0.000770 | Seg 0.344016 | Elapsed 3.5m | ETA 0.7m
Epoch 226/500 | Batch 180/202 | Rec 0.000761 | Seg 0.340946 | Elapsed 3.8m | ETA 0.5m
Epoch 226/500 | Batch 190/202 | Rec 0.000767 | Seg 0.345907 | Elapsed 4.0m | ETA 0.3m
Epoch 226/500 | Batch 200/202 | Rec 0.000772 | Seg 0.350530 | Elapsed 4.2m | ETA 0.0m
Epoch 226/500 | Batch 202/202 | Rec 0.000775 | Seg 0.352374 | Elapsed 4.2m | ETA 0.0m

2026-09-23 18:21:51,346 - INFO: Rec loss: 0.0007748370257518623
2026-09-23 18:21:51,346 - INFO: Seg loss: 0.35237439795590864
2026-09-23 18:21:51,347 - INFO: λ_rec: 1
2026-09-23 18:21:51,347 - INFO: λ_seg: 0.0001
2026-09-23 18:23:08,766 - INFO: -------------------Epoch: 226------------------------
2026-09-23 18:23:08,769 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.909367  0.971549  0.000168
2026-09-23 18:23:08,776 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995371  0.997630  0.996252  0.999113  0.995577
real potato   0.630324  0.773202  1.000000  0.630324  0.999558
fake potato   0.857491  0.923229  0.966766  0.883536  0.999893
real apple    0.745908  0.854414  0.882278  0.828350  0.999026
fake apple    0.646467  0.785230  0.981455  0.654462  0.998649
real orange   0.512251  0.677423  0.978565  0.518064  0.999350
fake orange   0.792926  0.884456  0.806068  0.979853  0.999267
real grape    0.675503  0.806280  0.975415  0.687203  0.999311
fake grape    0.859073  0.924145  0.925073  0.923318  0.999440
real lemon    0.235154  0.380719  0.346461  0.422617  0.998385
fake lemon    0.839252  0.912552  0.966758  0.864190  0.999650
real avocado  0.789214  0.882141  0.825838  0.946798  0.999765
fake avocado  0.685579  0.813416  0.999814  0.685667  0.999624
real pepper   0.804360  0.891524  0.882894  0.900425  0.999199
fake pepper   0.811932  0.896156  0.967570  0.834646  0.999539
real plant    0.845573  0.916276  0.934749  0.898615  0.998358
fake plant    0.845497  0.916231  0.964210  0.872891  0.999873
real banana   0.316424  0.480695  0.945053  0.322355  0.998435
fake banana   0.520256  0.684383  0.592809  0.809555  0.998627
real onion    0.705299  0.827136  0.740197  0.937342  0.999646
fake onion    0.923293  0.960067  0.968504  0.951874  0.999950
real unknown  0.854825  0.921681  0.890569  0.955153  0.999974
fake unknown  0.232562  0.377324  0.260981  0.681094  0.998106
total         0.701067  0.803753  0.860795  0.790758  0.999096
total(-bg)    0.687689  0.794940  0.854638  0.781288  0.999256
2026-09-23 18:23:09,294 - INFO: Epoch accounting: {'epoch': 226, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11177943, 29652, 32285, 127272, 168980, 105644, 76629, 140450, 242620, 108703, 85517, 30527, 34160, 217643, 118848, 209733, 21581, 82084, 55489, 79527, 41365, 9131, 42489], 'crops_with_class': [202, 19, 15, 37, 42, 33, 27, 27, 47, 38, 35, 10, 14, 53, 28, 22, 22, 23, 23, 30, 20, 10, 20], 'targeted_crops_by_class': [0, 6, 0, 5, 6, 6, 4, 6, 7, 7, 4, 2, 5, 3, 4, 7, 5, 5, 1, 4, 4, 5, 5], 'sampled_scene_counts': [1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 0, 2, 0, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2, 3, 1, 1, 2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 2, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 2, 2, 0, 0, 1, 2, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 2, 1, 0, 0, 0, 1, 1, 3, 2, 3, 3, 4, 4, 2, 3, 2, 1, 0, 0, 2, 0, 2, 2, 1, 2, 3, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 3, 2, 2, 0, 1, 1, 1, 2, 2, 3, 1, 0, 3, 2, 2, 2, 2, 0, 1, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 2, 0], 'learning_rate': 5.792716894388147e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007748370257518623, 'train_segmentation_loss': 0.35237439795590864, 'val_foreground_miou_all22': 0.6876893029983081, 'val_psnr_ref1': 37.9093669128418, 'elapsed_seconds': 331.4510567188263, 'peak_cuda_allocated_gib': 7.508823394775391}

Epoch 227/500 | Batch 10/202 | Rec 0.000767 | Seg 0.309053 | Elapsed 0.2m | ETA 4.1m
Epoch 227/500 | Batch 20/202 | Rec 0.000770 | Seg 0.333338 | Elapsed 0.4m | ETA 3.9m
Epoch 227/500 | Batch 30/202 | Rec 0.000777 | Seg 0.341474 | Elapsed 0.6m | ETA 3.6m
Epoch 227/500 | Batch 40/202 | Rec 0.000816 | Seg 0.357487 | Elapsed 0.8m | ETA 3.4m
Epoch 227/500 | Batch 50/202 | Rec 0.000804 | Seg 0.363111 | Elapsed 1.1m | ETA 3.2m
Epoch 227/500 | Batch 60/202 | Rec 0.000788 | Seg 0.358790 | Elapsed 1.3m | ETA 3.0m
Epoch 227/500 | Batch 70/202 | Rec 0.000806 | Seg 0.355019 | Elapsed 1.5m | ETA 2.8m
Epoch 227/500 | Batch 80/202 | Rec 0.000809 | Seg 0.355356 | Elapsed 1.7m | ETA 2.6m
Epoch 227/500 | Batch 90/202 | Rec 0.000815 | Seg 0.353829 | Elapsed 1.9m | ETA 2.4m
Epoch 227/500 | Batch 100/202 | Rec 0.000808 | Seg 0.347905 | Elapsed 2.1m | ETA 2.1m
Epoch 227/500 | Batch 110/202 | Rec 0.000795 | Seg 0.350874 | Elapsed 2.3m | ETA 1.9m
Epoch 227/500 | Batch 120/202 | Rec 0.000791 | Seg 0.351070 | Elapsed 2.5m | ETA 1.7m
Epoch 227/500 | Batch 130/202 | Rec 0.000794 | Seg 0.352838 | Elapsed 2.7m | ETA 1.5m
Epoch 227/500 | Batch 140/202 | Rec 0.000782 | Seg 0.349309 | Elapsed 2.9m | ETA 1.3m
Epoch 227/500 | Batch 150/202 | Rec 0.000778 | Seg 0.348218 | Elapsed 3.2m | ETA 1.1m
Epoch 227/500 | Batch 160/202 | Rec 0.000770 | Seg 0.344162 | Elapsed 3.4m | ETA 0.9m
Epoch 227/500 | Batch 170/202 | Rec 0.000770 | Seg 0.343393 | Elapsed 3.6m | ETA 0.7m
Epoch 227/500 | Batch 180/202 | Rec 0.000778 | Seg 0.344955 | Elapsed 3.8m | ETA 0.5m
Epoch 227/500 | Batch 190/202 | Rec 0.000765 | Seg 0.338883 | Elapsed 4.0m | ETA 0.3m
Epoch 227/500 | Batch 200/202 | Rec 0.000760 | Seg 0.337497 | Elapsed 4.2m | ETA 0.0m
Epoch 227/500 | Batch 202/202 | Rec 0.000758 | Seg 0.337609 | Elapsed 4.3m | ETA 0.0m

2026-09-23 18:27:24,853 - INFO: Rec loss: 0.0007580227027232251
2026-09-23 18:27:24,853 - INFO: Seg loss: 0.33760912893432204
2026-09-23 18:27:24,853 - INFO: λ_rec: 1
2026-09-23 18:27:24,853 - INFO: λ_seg: 0.0001
2026-09-23 18:28:46,923 - INFO: -------------------Epoch: 227------------------------
2026-09-23 18:28:46,927 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.301103  0.972795  0.000155
2026-09-23 18:28:46,935 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995511  0.997700  0.997072  0.998429  0.995714
real potato   0.886312  0.939680  0.987086  0.896710  0.999862
fake potato   0.753709  0.859510  0.961878  0.776917  0.999815
real apple    0.792338  0.884089  0.964803  0.815922  0.999262
fake apple    0.615826  0.762196  0.990247  0.619585  0.998541
real orange   0.885573  0.939264  0.994565  0.889880  0.999848
fake orange   0.925634  0.961331  0.939915  0.983850  0.999774
real grape    0.792742  0.884341  0.963390  0.817365  0.999554
fake grape    0.881522  0.936981  0.953267  0.921338  0.999542
real lemon    0.474962  0.643985  0.533311  0.812776  0.998944
fake lemon    0.842056  0.914207  0.996173  0.844789  0.999665
real avocado  0.878687  0.935376  0.922144  0.949097  0.999878
fake avocado  0.657787  0.793525  0.999226  0.658123  0.999590
real pepper   0.852545  0.920354  0.915899  0.924954  0.999415
fake pepper   0.935085  0.966403  0.985689  0.947955  0.999843
real plant    0.863736  0.926837  0.932214  0.921619  0.998546
fake plant    0.887653  0.940433  0.932856  0.948236  0.999904
real banana   0.484638  0.652824  0.900621  0.512020  0.998777
fake banana   0.700441  0.823785  0.772955  0.881885  0.999306
real onion    0.634116  0.776049  0.650485  0.961831  0.999499
fake onion    0.955844  0.977373  0.992030  0.963241  0.999972
real unknown  0.575482  0.730501  0.586806  0.967557  0.999886
fake unknown  0.243784  0.391966  0.258975  0.806049  0.997893
total         0.761564  0.850379  0.875287  0.861745  0.999262
total(-bg)    0.750931  0.843682  0.869752  0.855532  0.999423
2026-09-23 18:28:47,619 - INFO: Epoch accounting: {'epoch': 227, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11292871, 44593, 52363, 117506, 156225, 74201, 72142, 136167, 200226, 74916, 74996, 38012, 45293, 234297, 98398, 163545, 44251, 74738, 74999, 68719, 40518, 13635, 45661], 'crops_with_class': [202, 26, 24, 36, 39, 23, 27, 26, 40, 32, 32, 13, 17, 60, 26, 28, 37, 21, 32, 30, 16, 14, 21], 'targeted_crops_by_class': [0, 1, 2, 5, 4, 4, 5, 6, 3, 4, 4, 2, 5, 7, 6, 7, 8, 5, 2, 5, 2, 7, 1], 'sampled_scene_counts': [1, 0, 2, 0, 1, 1, 0, 0, 1, 3, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 2, 0, 2, 2, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 3, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 1, 1, 4, 2, 0, 2, 2, 2, 2, 2, 3, 1, 0, 1, 1, 2, 2, 1, 1, 0, 0, 4, 2, 1, 3, 1, 1, 1, 1, 2, 2, 1, 1, 3, 1, 2, 2, 4, 1, 3, 1, 3, 2, 0, 2, 3, 1, 1, 2, 3, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 2, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 0, 1, 3, 1, 1, 1, 1, 0], 'learning_rate': 5.761750125739771e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007580227027232251, 'train_segmentation_loss': 0.33760912893432204, 'val_foreground_miou_all22': 0.7509305083750966, 'val_psnr_ref1': 38.30110260009766, 'elapsed_seconds': 338.3163847923279, 'peak_cuda_allocated_gib': 7.509342193603516}

Epoch 228/500 | Batch 10/202 | Rec 0.000871 | Seg 0.413012 | Elapsed 0.2m | ETA 4.1m
Epoch 228/500 | Batch 20/202 | Rec 0.000808 | Seg 0.400168 | Elapsed 0.4m | ETA 4.0m
Epoch 228/500 | Batch 30/202 | Rec 0.000765 | Seg 0.364292 | Elapsed 0.6m | ETA 3.7m
Epoch 228/500 | Batch 40/202 | Rec 0.000769 | Seg 0.361529 | Elapsed 0.8m | ETA 3.4m
Epoch 228/500 | Batch 50/202 | Rec 0.000757 | Seg 0.352074 | Elapsed 1.0m | ETA 3.2m
Epoch 228/500 | Batch 60/202 | Rec 0.000779 | Seg 0.369098 | Elapsed 1.3m | ETA 3.0m
Epoch 228/500 | Batch 70/202 | Rec 0.000774 | Seg 0.358899 | Elapsed 1.5m | ETA 2.8m
Epoch 228/500 | Batch 80/202 | Rec 0.000807 | Seg 0.362731 | Elapsed 1.7m | ETA 2.6m
Epoch 228/500 | Batch 90/202 | Rec 0.000795 | Seg 0.355604 | Elapsed 1.9m | ETA 2.4m
Epoch 228/500 | Batch 100/202 | Rec 0.000776 | Seg 0.343935 | Elapsed 2.1m | ETA 2.1m
Epoch 228/500 | Batch 110/202 | Rec 0.000775 | Seg 0.342276 | Elapsed 2.3m | ETA 1.9m
Epoch 228/500 | Batch 120/202 | Rec 0.000758 | Seg 0.335083 | Elapsed 2.5m | ETA 1.7m
Epoch 228/500 | Batch 130/202 | Rec 0.000765 | Seg 0.334607 | Elapsed 2.7m | ETA 1.5m
Epoch 228/500 | Batch 140/202 | Rec 0.000768 | Seg 0.334374 | Elapsed 2.9m | ETA 1.3m
Epoch 228/500 | Batch 150/202 | Rec 0.000784 | Seg 0.332726 | Elapsed 3.1m | ETA 1.1m
Epoch 228/500 | Batch 160/202 | Rec 0.000777 | Seg 0.332304 | Elapsed 3.3m | ETA 0.9m
Epoch 228/500 | Batch 170/202 | Rec 0.000769 | Seg 0.330612 | Elapsed 3.6m | ETA 0.7m
Epoch 228/500 | Batch 180/202 | Rec 0.000780 | Seg 0.330807 | Elapsed 3.8m | ETA 0.5m
Epoch 228/500 | Batch 190/202 | Rec 0.000786 | Seg 0.334650 | Elapsed 4.0m | ETA 0.3m
Epoch 228/500 | Batch 200/202 | Rec 0.000787 | Seg 0.335183 | Elapsed 4.2m | ETA 0.0m
Epoch 228/500 | Batch 202/202 | Rec 0.000787 | Seg 0.336532 | Elapsed 4.2m | ETA 0.0m

2026-09-23 18:33:01,410 - INFO: Rec loss: 0.0007870896940700489
2026-09-23 18:33:01,410 - INFO: Seg loss: 0.3365317702219628
2026-09-23 18:33:01,410 - INFO: λ_rec: 1
2026-09-23 18:33:01,410 - INFO: λ_seg: 0.0001
2026-09-23 18:34:23,378 - INFO: -------------------Epoch: 228------------------------
2026-09-23 18:34:23,382 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.920295  0.971905  0.000167
2026-09-23 18:34:23,388 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994832  0.997360  0.995568  0.999258  0.995059
real potato   0.696896  0.821329  0.996363  0.698674  0.999636
fake potato   0.848241  0.917840  0.954535  0.883955  0.999885
real apple    0.759650  0.863361  0.904363  0.826006  0.999098
fake apple    0.709928  0.830311  0.994083  0.712941  0.998900
real orange   0.566283  0.723045  0.973164  0.575266  0.999419
fake orange   0.801552  0.889796  0.818670  0.974576  0.999309
real grape    0.705299  0.827136  0.948488  0.733392  0.999360
fake grape    0.831747  0.908096  0.942974  0.875799  0.999345
real lemon    0.233534  0.378593  0.330683  0.442872  0.998292
fake lemon    0.846508  0.916825  0.995689  0.849621  0.999674
real avocado  0.805490  0.892217  0.841730  0.949261  0.999787
fake avocado  0.560867  0.718615  0.999319  0.561081  0.999474
real pepper   0.834045  0.909464  0.914229  0.904847  0.999341
fake pepper   0.800679  0.889259  0.978998  0.814673  0.999517
real plant    0.810279  0.895148  0.953435  0.843666  0.998024
fake plant    0.847406  0.917351  0.937025  0.898581  0.999871
real banana   0.303766  0.465946  0.953191  0.308366  0.998412
fake banana   0.576169  0.731051  0.652619  0.831038  0.998875
real onion    0.690476  0.816852  0.719224  0.945279  0.999617
fake onion    0.949213  0.973895  0.985396  0.962757  0.999967
real unknown  0.820132  0.901129  0.858376  0.948473  0.999967
fake unknown  0.247063  0.396194  0.265051  0.784498  0.997986
total         0.706089  0.807861  0.865790  0.796734  0.999079
total(-bg)    0.692965  0.799248  0.859891  0.787528  0.999262
2026-09-23 18:34:23,925 - INFO: Epoch accounting: {'epoch': 228, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11303403, 47499, 45527, 102264, 149867, 73479, 60116, 82441, 198337, 64972, 58482, 52766, 49144, 244707, 158673, 128768, 19349, 105972, 73708, 90707, 51216, 15192, 61683], 'crops_with_class': [202, 28, 26, 28, 44, 21, 21, 22, 36, 28, 23, 19, 20, 55, 40, 17, 19, 29, 27, 41, 25, 20, 24], 'targeted_crops_by_class': [0, 2, 4, 3, 6, 3, 2, 3, 6, 2, 6, 5, 7, 1, 5, 3, 3, 7, 6, 12, 3, 8, 12], 'sampled_scene_counts': [1, 1, 1, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 3, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 3, 1, 1, 0, 2, 0, 0, 3, 1, 1, 0, 2, 4, 1, 1, 3, 1, 4, 1, 1, 1, 5, 1, 1, 1, 6, 3, 1, 1, 3, 1, 3, 2, 0, 2, 0, 2, 2, 0, 1, 3, 1, 2, 1, 1, 0, 2, 0, 0, 1, 0, 2, 1, 1, 6, 2, 4, 0, 3, 1, 2, 2, 0, 1, 0, 3, 3, 1], 'learning_rate': 5.7307537779793535e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007870896940700489, 'train_segmentation_loss': 0.3365317702219628, 'val_foreground_miou_all22': 0.6929646901428815, 'val_psnr_ref1': 37.92029541015625, 'elapsed_seconds': 336.2982244491577, 'peak_cuda_allocated_gib': 7.506381988525391}

Epoch 229/500 | Batch 10/202 | Rec 0.000838 | Seg 0.424423 | Elapsed 0.2m | ETA 4.0m
Epoch 229/500 | Batch 20/202 | Rec 0.000762 | Seg 0.342969 | Elapsed 0.4m | ETA 3.8m
Epoch 229/500 | Batch 30/202 | Rec 0.000796 | Seg 0.357286 | Elapsed 0.6m | ETA 3.6m
Epoch 229/500 | Batch 40/202 | Rec 0.000799 | Seg 0.362534 | Elapsed 0.8m | ETA 3.4m
Epoch 229/500 | Batch 50/202 | Rec 0.000780 | Seg 0.353948 | Elapsed 1.1m | ETA 3.2m
Epoch 229/500 | Batch 60/202 | Rec 0.000822 | Seg 0.358710 | Elapsed 1.3m | ETA 3.0m
Epoch 229/500 | Batch 70/202 | Rec 0.000800 | Seg 0.343352 | Elapsed 1.5m | ETA 2.8m
Epoch 229/500 | Batch 80/202 | Rec 0.000798 | Seg 0.342109 | Elapsed 1.7m | ETA 2.6m
Epoch 229/500 | Batch 90/202 | Rec 0.000815 | Seg 0.347400 | Elapsed 1.9m | ETA 2.4m
Epoch 229/500 | Batch 100/202 | Rec 0.000810 | Seg 0.344379 | Elapsed 2.1m | ETA 2.2m
Epoch 229/500 | Batch 110/202 | Rec 0.000804 | Seg 0.343695 | Elapsed 2.3m | ETA 2.0m
Epoch 229/500 | Batch 120/202 | Rec 0.000801 | Seg 0.339461 | Elapsed 2.5m | ETA 1.7m
Epoch 229/500 | Batch 130/202 | Rec 0.000798 | Seg 0.340799 | Elapsed 2.8m | ETA 1.5m
Epoch 229/500 | Batch 140/202 | Rec 0.000801 | Seg 0.334418 | Elapsed 3.0m | ETA 1.3m
Epoch 229/500 | Batch 150/202 | Rec 0.000799 | Seg 0.338519 | Elapsed 3.2m | ETA 1.1m
Epoch 229/500 | Batch 160/202 | Rec 0.000799 | Seg 0.338769 | Elapsed 3.4m | ETA 0.9m
Epoch 229/500 | Batch 170/202 | Rec 0.000802 | Seg 0.343232 | Elapsed 3.6m | ETA 0.7m
Epoch 229/500 | Batch 180/202 | Rec 0.000800 | Seg 0.339870 | Elapsed 3.8m | ETA 0.5m
Epoch 229/500 | Batch 190/202 | Rec 0.000795 | Seg 0.337710 | Elapsed 4.0m | ETA 0.3m
Epoch 229/500 | Batch 200/202 | Rec 0.000794 | Seg 0.336296 | Elapsed 4.2m | ETA 0.0m
Epoch 229/500 | Batch 202/202 | Rec 0.000793 | Seg 0.335728 | Elapsed 4.3m | ETA 0.0m

2026-09-23 18:38:40,094 - INFO: Rec loss: 0.0007927374752056277
2026-09-23 18:38:40,094 - INFO: Seg loss: 0.3357283633091662
2026-09-23 18:38:40,094 - INFO: λ_rec: 1
2026-09-23 18:38:40,094 - INFO: λ_seg: 0.0001
2026-09-23 18:40:02,492 - INFO: -------------------Epoch: 229------------------------
2026-09-23 18:40:02,496 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.248394  0.972332  0.000157
2026-09-23 18:40:02,502 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994996  0.997442  0.996055  0.998932  0.995217
real potato   0.337662  0.504817  0.995495  0.338179  0.999206
fake potato   0.626915  0.770632  0.981842  0.634269  0.999725
real apple    0.672792  0.804344  0.794487  0.814551  0.998633
fake apple    0.737446  0.848836  0.959925  0.760871  0.998977
real orange   0.537455  0.699104  0.999785  0.537517  0.999390
fake orange   0.807291  0.893322  0.828669  0.969033  0.999338
real grape    0.699086  0.822847  0.904387  0.754878  0.999322
fake grape    0.817738  0.899681  0.908915  0.890731  0.999266
real lemon    0.311201  0.474636  0.358665  0.701636  0.998175
fake lemon    0.829017  0.906467  0.996800  0.831230  0.999637
real avocado  0.820946  0.901620  0.859161  0.948604  0.999808
fake avocado  0.365340  0.535125  1.000000  0.365340  0.999241
real pepper   0.854486  0.921484  0.956303  0.889204  0.999446
fake pepper   0.871648  0.931373  0.997151  0.873824  0.999693
real plant    0.858230  0.923657  0.932202  0.915365  0.998488
fake plant    0.820155  0.901143  0.911713  0.890913  0.999845
real banana   0.139481  0.244794  0.979553  0.139889  0.998061
fake banana   0.673269  0.804685  0.820588  0.789482  0.999295
real onion    0.721269  0.838017  0.753233  0.944435  0.999670
fake onion    0.896593  0.945428  0.991247  0.903748  0.999934
real unknown  0.838435  0.912068  0.885099  0.940840  0.999971
fake unknown  0.253708  0.404697  0.262548  0.882832  0.997812
total         0.673268  0.777662  0.872775  0.770274  0.999050
total(-bg)    0.658644  0.767672  0.867171  0.759881  0.999224
2026-09-23 18:40:03,010 - INFO: Epoch accounting: {'epoch': 229, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11273985, 55164, 67823, 134990, 125636, 62851, 74422, 150976, 254089, 104164, 79871, 35706, 24653, 186969, 121471, 148751, 25814, 78766, 47322, 83841, 45245, 4765, 50998], 'crops_with_class': [202, 34, 28, 35, 32, 19, 27, 32, 38, 41, 33, 11, 11, 46, 29, 20, 20, 20, 23, 38, 20, 6, 20], 'targeted_crops_by_class': [0, 5, 5, 5, 3, 0, 3, 5, 6, 5, 8, 4, 5, 4, 6, 5, 4, 3, 4, 4, 3, 2, 3], 'sampled_scene_counts': [1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 2, 0, 2, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 0, 1, 3, 0, 0, 1, 2, 2, 1, 0, 1, 0, 2, 1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0, 0, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 2, 0, 1, 0, 0, 1, 2, 0, 2, 3, 1, 0, 3, 3, 4, 2, 0, 2, 1, 1, 1, 1, 2, 0, 3, 2, 1, 2, 1, 1, 2, 3, 0, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 1, 3, 1, 0, 1, 2, 6, 1, 3, 1, 1, 2, 0, 3, 1, 3, 1, 0, 2, 1, 1, 0, 1, 2, 1, 0, 2, 0, 0, 1, 4, 2, 0, 0, 3, 0, 2, 0, 0, 2, 2, 2, 0, 1, 1], 'learning_rate': 5.699729074789628e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007927374752056277, 'train_segmentation_loss': 0.3357283633091662, 'val_foreground_miou_all22': 0.6586438349569366, 'val_psnr_ref1': 38.2483935546875, 'elapsed_seconds': 339.0766248703003, 'peak_cuda_allocated_gib': 7.508853912353516}

Epoch 230/500 | Batch 10/202 | Rec 0.000756 | Seg 0.304302 | Elapsed 0.2m | ETA 4.1m
Epoch 230/500 | Batch 20/202 | Rec 0.000795 | Seg 0.330989 | Elapsed 0.4m | ETA 3.8m
Epoch 230/500 | Batch 30/202 | Rec 0.000717 | Seg 0.297917 | Elapsed 0.6m | ETA 3.6m
Epoch 230/500 | Batch 40/202 | Rec 0.000743 | Seg 0.320795 | Elapsed 0.8m | ETA 3.4m
Epoch 230/500 | Batch 50/202 | Rec 0.000717 | Seg 0.314619 | Elapsed 1.1m | ETA 3.2m
Epoch 230/500 | Batch 60/202 | Rec 0.000761 | Seg 0.318079 | Elapsed 1.3m | ETA 3.0m
Epoch 230/500 | Batch 70/202 | Rec 0.000748 | Seg 0.316651 | Elapsed 1.5m | ETA 2.8m
Epoch 230/500 | Batch 80/202 | Rec 0.000743 | Seg 0.323350 | Elapsed 1.7m | ETA 2.6m
Epoch 230/500 | Batch 90/202 | Rec 0.000740 | Seg 0.315228 | Elapsed 1.9m | ETA 2.4m
Epoch 230/500 | Batch 100/202 | Rec 0.000751 | Seg 0.324502 | Elapsed 2.1m | ETA 2.2m
Epoch 230/500 | Batch 110/202 | Rec 0.000753 | Seg 0.332062 | Elapsed 2.3m | ETA 1.9m
Epoch 230/500 | Batch 120/202 | Rec 0.000759 | Seg 0.332257 | Elapsed 2.5m | ETA 1.7m
Epoch 230/500 | Batch 130/202 | Rec 0.000768 | Seg 0.340652 | Elapsed 2.7m | ETA 1.5m
Epoch 230/500 | Batch 140/202 | Rec 0.000761 | Seg 0.341109 | Elapsed 2.9m | ETA 1.3m
Epoch 230/500 | Batch 150/202 | Rec 0.000766 | Seg 0.343761 | Elapsed 3.2m | ETA 1.1m
Epoch 230/500 | Batch 160/202 | Rec 0.000759 | Seg 0.338548 | Elapsed 3.4m | ETA 0.9m
Epoch 230/500 | Batch 170/202 | Rec 0.000766 | Seg 0.343177 | Elapsed 3.6m | ETA 0.7m
Epoch 230/500 | Batch 180/202 | Rec 0.000769 | Seg 0.348235 | Elapsed 3.8m | ETA 0.5m
Epoch 230/500 | Batch 190/202 | Rec 0.000766 | Seg 0.345844 | Elapsed 4.0m | ETA 0.3m
Epoch 230/500 | Batch 200/202 | Rec 0.000765 | Seg 0.345244 | Elapsed 4.2m | ETA 0.0m
Epoch 230/500 | Batch 202/202 | Rec 0.000763 | Seg 0.344424 | Elapsed 4.3m | ETA 0.0m

2026-09-23 18:44:18,126 - INFO: Rec loss: 0.0007627793596533016
2026-09-23 18:44:18,126 - INFO: Seg loss: 0.3444242899186245
2026-09-23 18:44:18,127 - INFO: λ_rec: 1
2026-09-23 18:44:18,127 - INFO: λ_seg: 0.0001
2026-09-23 18:45:44,340 - INFO: -------------------Epoch: 230------------------------
2026-09-23 18:45:44,343 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.26726  0.972612  0.000155
2026-09-23 18:45:44,350 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994520  0.997203  0.995274  0.999240  0.994759
real potato   0.166922  0.286064  1.000000  0.166922  0.999003
fake potato   0.537453  0.699102  0.987763  0.541056  0.999661
real apple    0.686098  0.813780  0.750327  0.889076  0.998597
fake apple    0.807144  0.893231  0.934337  0.855682  0.999228
real orange   0.782961  0.878221  0.999557  0.783233  0.999714
fake orange   0.876275  0.934008  0.907838  0.961838  0.999611
real grape    0.437351  0.608508  0.981141  0.441058  0.998815
fake grape    0.694021  0.819328  0.892954  0.757002  0.998765
real lemon    0.343238  0.511014  0.401814  0.701896  0.998422
fake lemon    0.838098  0.911869  0.995139  0.841543  0.999656
real avocado  0.699448  0.823098  0.722436  0.956486  0.999618
fake avocado  0.811076  0.895634  0.997964  0.812420  0.999774
real pepper   0.845488  0.916226  0.950913  0.884073  0.999409
fake pepper   0.794846  0.885649  0.998714  0.795660  0.999510
real plant    0.812904  0.896748  0.899281  0.894328  0.997941
fake plant    0.859003  0.924105  0.966513  0.885353  0.999884
real banana   0.177844  0.301954  0.884818  0.182059  0.998109
fake banana   0.620831  0.766016  0.733693  0.801427  0.999100
real onion    0.660097  0.795201  0.748287  0.848505  0.999605
fake onion    0.948650  0.973598  0.996707  0.951632  0.999967
real unknown  0.932282  0.964904  0.971014  0.958969  0.999989
fake unknown  0.332160  0.498634  0.377383  0.734879  0.998755
total         0.680813  0.782352  0.873646  0.767145  0.999039
total(-bg)    0.666554  0.772586  0.868118  0.756595  0.999233
2026-09-23 18:45:44,870 - INFO: Epoch accounting: {'epoch': 230, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11274603, 54334, 52987, 135787, 151378, 55422, 59009, 148761, 249627, 59791, 53407, 67129, 45880, 213077, 118842, 110927, 26443, 83581, 65829, 98118, 61814, 13986, 37540], 'crops_with_class': [202, 32, 25, 41, 36, 18, 25, 28, 43, 26, 22, 24, 19, 54, 29, 15, 21, 19, 30, 35, 26, 13, 20], 'targeted_crops_by_class': [0, 5, 7, 9, 4, 2, 2, 5, 6, 3, 2, 9, 8, 6, 4, 1, 3, 1, 5, 7, 4, 5, 4], 'sampled_scene_counts': [1, 0, 3, 1, 1, 1, 0, 2, 1, 0, 1, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 1, 0, 4, 2, 2, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 3, 6, 3, 2, 1, 2, 1, 1, 1, 1, 1, 0, 0, 2, 2, 2, 2, 1, 0, 3, 2, 2, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 3, 4, 3, 0, 1, 3, 1, 2, 0, 0, 2, 1, 2, 3, 0, 4, 1, 2, 1, 2, 1, 1, 0, 2, 1, 1, 1, 3, 2, 0, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 1, 1], 'learning_rate': 5.668677240972754e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007627793596533016, 'train_segmentation_loss': 0.3444242899186245, 'val_foreground_miou_all22': 0.6665540459223713, 'val_psnr_ref1': 38.26725982666016, 'elapsed_seconds': 341.85267400741577, 'peak_cuda_allocated_gib': 7.509288787841797}

Epoch 231/500 | Batch 10/202 | Rec 0.000756 | Seg 0.353486 | Elapsed 0.2m | ETA 4.0m
Epoch 231/500 | Batch 20/202 | Rec 0.000778 | Seg 0.353514 | Elapsed 0.4m | ETA 3.8m
Epoch 231/500 | Batch 30/202 | Rec 0.000797 | Seg 0.331074 | Elapsed 0.6m | ETA 3.6m
Epoch 231/500 | Batch 40/202 | Rec 0.000814 | Seg 0.335614 | Elapsed 0.8m | ETA 3.4m
Epoch 231/500 | Batch 50/202 | Rec 0.000796 | Seg 0.334054 | Elapsed 1.1m | ETA 3.2m
Epoch 231/500 | Batch 60/202 | Rec 0.000787 | Seg 0.350638 | Elapsed 1.3m | ETA 3.0m
Epoch 231/500 | Batch 70/202 | Rec 0.000793 | Seg 0.361077 | Elapsed 1.5m | ETA 2.8m
Epoch 231/500 | Batch 80/202 | Rec 0.000793 | Seg 0.366399 | Elapsed 1.7m | ETA 2.6m
Epoch 231/500 | Batch 90/202 | Rec 0.000778 | Seg 0.356183 | Elapsed 1.9m | ETA 2.4m
Epoch 231/500 | Batch 100/202 | Rec 0.000772 | Seg 0.354357 | Elapsed 2.1m | ETA 2.1m
Epoch 231/500 | Batch 110/202 | Rec 0.000776 | Seg 0.356584 | Elapsed 2.3m | ETA 1.9m
Epoch 231/500 | Batch 120/202 | Rec 0.000768 | Seg 0.353514 | Elapsed 2.5m | ETA 1.7m
Epoch 231/500 | Batch 130/202 | Rec 0.000766 | Seg 0.350353 | Elapsed 2.7m | ETA 1.5m
Epoch 231/500 | Batch 140/202 | Rec 0.000763 | Seg 0.351866 | Elapsed 2.9m | ETA 1.3m
Epoch 231/500 | Batch 150/202 | Rec 0.000761 | Seg 0.349347 | Elapsed 3.2m | ETA 1.1m
Epoch 231/500 | Batch 160/202 | Rec 0.000776 | Seg 0.347916 | Elapsed 3.4m | ETA 0.9m
Epoch 231/500 | Batch 170/202 | Rec 0.000775 | Seg 0.350836 | Elapsed 3.6m | ETA 0.7m
Epoch 231/500 | Batch 180/202 | Rec 0.000768 | Seg 0.349994 | Elapsed 3.8m | ETA 0.5m
Epoch 231/500 | Batch 190/202 | Rec 0.000758 | Seg 0.347703 | Elapsed 4.0m | ETA 0.3m
Epoch 231/500 | Batch 200/202 | Rec 0.000754 | Seg 0.348886 | Elapsed 4.2m | ETA 0.0m
Epoch 231/500 | Batch 202/202 | Rec 0.000752 | Seg 0.347670 | Elapsed 4.2m | ETA 0.0m

2026-09-23 18:49:59,353 - INFO: Rec loss: 0.0007515940326784673
2026-09-23 18:49:59,354 - INFO: Seg loss: 0.34766971924812484
2026-09-23 18:49:59,354 - INFO: λ_rec: 1
2026-09-23 18:49:59,354 - INFO: λ_seg: 0.0001
2026-09-23 18:51:21,267 - INFO: -------------------Epoch: 231------------------------
2026-09-23 18:51:21,272 - INFO:
Validation stats:
        PSNR    SSIM       MSE
0  37.922917  0.9719  0.000168
2026-09-23 18:51:21,279 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995233  0.997561  0.996349  0.998876  0.995445
real potato   0.311400  0.474876  1.000000  0.311400  0.999176
fake potato   0.612040  0.759289  0.996596  0.613322  0.999717
real apple    0.683843  0.812191  0.783235  0.843476  0.998655
fake apple    0.778869  0.875640  0.979357  0.791869  0.999151
real orange   0.681450  0.810502  1.000000  0.681450  0.999580
fake orange   0.853735  0.921047  0.871605  0.976548  0.999521
real grape    0.624660  0.768926  0.966062  0.638676  0.999199
fake grape    0.854692  0.921604  0.946369  0.898197  0.999435
real lemon    0.359424  0.528745  0.392323  0.810828  0.998302
fake lemon    0.833897  0.909376  0.996391  0.836423  0.999648
real avocado  0.847673  0.917508  0.886186  0.951232  0.999841
fake avocado  0.729661  0.843655  1.000000  0.729661  0.999677
real pepper   0.896103  0.945155  0.978349  0.914233  0.999612
fake pepper   0.944522  0.971420  0.994701  0.949299  0.999867
real plant    0.835815  0.910515  0.898194  0.923282  0.998186
fake plant    0.899925  0.947277  0.969873  0.925805  0.999918
real banana   0.181709  0.307508  0.904809  0.185251  0.998125
fake banana   0.692573  0.818317  0.876777  0.767253  0.999373
real onion    0.633998  0.775959  0.693628  0.880594  0.999541
fake onion    0.870804  0.930891  0.998339  0.872068  0.999918
real unknown  0.915033  0.955581  0.977069  0.935114  0.999986
fake unknown  0.299611  0.461038  0.316254  0.850598  0.998325
total         0.710290  0.807156  0.887933  0.795020  0.999139
total(-bg)    0.697338  0.798501  0.883005  0.785754  0.999307
2026-09-23 18:51:21,790 - INFO: Epoch accounting: {'epoch': 231, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11218319, 69390, 47420, 80489, 209177, 110403, 93291, 137280, 191304, 92962, 54239, 53312, 37366, 196600, 128831, 123874, 19930, 95355, 87919, 76439, 55915, 7335, 51122], 'crops_with_class': [202, 33, 25, 25, 50, 29, 34, 28, 32, 41, 25, 18, 17, 53, 29, 18, 19, 23, 32, 35, 23, 9, 22], 'targeted_crops_by_class': [0, 7, 5, 3, 7, 8, 4, 3, 1, 7, 3, 5, 6, 6, 4, 4, 3, 5, 6, 6, 2, 2, 6], 'sampled_scene_counts': [1, 1, 2, 0, 1, 1, 0, 1, 3, 0, 0, 3, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 3, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 2, 1, 1, 1, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 1, 1, 3, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 3, 0, 1, 2, 2, 1, 2, 5, 4, 0, 1, 1, 0, 2, 1, 1, 0, 1, 2, 3, 3, 0, 2, 2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 2, 1, 1, 3, 5, 0, 0, 1, 1, 1, 2, 1, 0, 1, 0, 2, 0, 1, 2, 1, 3, 1, 1, 1, 5, 0, 3, 1, 1, 2, 2, 2, 0, 2, 4, 1, 1, 1, 1, 2, 2, 1, 1], 'learning_rate': 5.637599502401962e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007515940326784673, 'train_segmentation_loss': 0.34766971924812484, 'val_foreground_miou_all22': 0.6973380509830397, 'val_psnr_ref1': 37.9229167175293, 'elapsed_seconds': 336.9093225002289, 'peak_cuda_allocated_gib': 7.514957427978516}

Epoch 232/500 | Batch 10/202 | Rec 0.000869 | Seg 0.317911 | Elapsed 0.2m | ETA 4.1m
Epoch 232/500 | Batch 20/202 | Rec 0.000743 | Seg 0.287140 | Elapsed 0.4m | ETA 3.8m
Epoch 232/500 | Batch 30/202 | Rec 0.000770 | Seg 0.320393 | Elapsed 0.6m | ETA 3.6m
Epoch 232/500 | Batch 40/202 | Rec 0.000713 | Seg 0.312496 | Elapsed 0.8m | ETA 3.4m
Epoch 232/500 | Batch 50/202 | Rec 0.000743 | Seg 0.337863 | Elapsed 1.0m | ETA 3.2m
Epoch 232/500 | Batch 60/202 | Rec 0.000738 | Seg 0.340558 | Elapsed 1.3m | ETA 3.0m
Epoch 232/500 | Batch 70/202 | Rec 0.000709 | Seg 0.323736 | Elapsed 1.5m | ETA 2.8m
Epoch 232/500 | Batch 80/202 | Rec 0.000704 | Seg 0.322975 | Elapsed 1.7m | ETA 2.6m
Epoch 232/500 | Batch 90/202 | Rec 0.000716 | Seg 0.321157 | Elapsed 1.9m | ETA 2.4m
Epoch 232/500 | Batch 100/202 | Rec 0.000717 | Seg 0.328141 | Elapsed 2.1m | ETA 2.1m
Epoch 232/500 | Batch 110/202 | Rec 0.000713 | Seg 0.325049 | Elapsed 2.3m | ETA 1.9m
Epoch 232/500 | Batch 120/202 | Rec 0.000718 | Seg 0.320131 | Elapsed 2.5m | ETA 1.7m
Epoch 232/500 | Batch 130/202 | Rec 0.000738 | Seg 0.325697 | Elapsed 2.7m | ETA 1.5m
Epoch 232/500 | Batch 140/202 | Rec 0.000729 | Seg 0.323222 | Elapsed 3.0m | ETA 1.3m
Epoch 232/500 | Batch 150/202 | Rec 0.000726 | Seg 0.324444 | Elapsed 3.2m | ETA 1.1m
Epoch 232/500 | Batch 160/202 | Rec 0.000708 | Seg 0.316043 | Elapsed 3.4m | ETA 0.9m
Epoch 232/500 | Batch 170/202 | Rec 0.000720 | Seg 0.326934 | Elapsed 3.6m | ETA 0.7m
Epoch 232/500 | Batch 180/202 | Rec 0.000722 | Seg 0.325487 | Elapsed 3.8m | ETA 0.5m
Epoch 232/500 | Batch 190/202 | Rec 0.000722 | Seg 0.325182 | Elapsed 4.0m | ETA 0.3m
Epoch 232/500 | Batch 200/202 | Rec 0.000726 | Seg 0.326991 | Elapsed 4.2m | ETA 0.0m
Epoch 232/500 | Batch 202/202 | Rec 0.000723 | Seg 0.326695 | Elapsed 4.3m | ETA 0.0m

2026-09-23 18:55:37,139 - INFO: Rec loss: 0.0007231868129214364
2026-09-23 18:55:37,139 - INFO: Seg loss: 0.32669514008235223
2026-09-23 18:55:37,139 - INFO: λ_rec: 1
2026-09-23 18:55:37,139 - INFO: λ_seg: 0.0001
2026-09-23 18:56:56,400 - INFO: -------------------Epoch: 232------------------------
2026-09-23 18:56:56,403 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.195922  0.972657  0.000157
2026-09-23 18:56:56,410 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995340  0.997615  0.996331  0.999001  0.995547
real potato   0.439684  0.610764  1.000000  0.439684  0.999330
fake potato   0.726471  0.841519  0.971750  0.742145  0.999796
real apple    0.720986  0.837825  0.809559  0.868244  0.998841
fake apple    0.730001  0.843882  0.971325  0.746080  0.998958
real orange   0.515856  0.680569  0.999103  0.516095  0.999362
fake orange   0.786097  0.880190  0.805837  0.969779  0.999245
real grape    0.618810  0.764476  0.940837  0.643865  0.999172
fake grape    0.865392  0.927789  0.951174  0.905622  0.999479
real lemon    0.359462  0.528785  0.405400  0.760322  0.998408
fake lemon    0.840031  0.913012  0.981826  0.853300  0.999656
real avocado  0.748854  0.856345  0.769120  0.966010  0.999699
fake avocado  0.772820  0.871805  0.999670  0.773017  0.999728
real pepper   0.791295  0.883439  0.859130  0.909269  0.999123
fake pepper   0.849131  0.918361  0.980593  0.863645  0.999634
real plant    0.849392  0.918514  0.936222  0.901559  0.998401
fake plant    0.852078  0.920082  0.958654  0.884586  0.999878
real banana   0.210484  0.347738  0.931912  0.213772  0.998198
fake banana   0.634907  0.776639  0.738864  0.818597  0.999134
real onion    0.665188  0.798885  0.745213  0.861003  0.999608
fake onion    0.937875  0.967892  0.991379  0.945586  0.999960
real unknown  0.942344  0.970266  0.990069  0.951336  0.999991
fake unknown  0.284638  0.443098  0.321809  0.711336  0.998494
total         0.701615  0.804326  0.871990  0.793211  0.999115
total(-bg)    0.688263  0.795540  0.866338  0.783857  0.999277
2026-09-23 18:56:56,942 - INFO: Epoch accounting: {'epoch': 232, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11337686, 43912, 53832, 121150, 141335, 73401, 69685, 166839, 214460, 75649, 55579, 42317, 30458, 198256, 75871, 172154, 31358, 82765, 82126, 63446, 56922, 8336, 40735], 'crops_with_class': [202, 25, 26, 33, 36, 23, 24, 36, 35, 35, 26, 14, 12, 52, 24, 23, 27, 23, 32, 31, 24, 11, 18], 'targeted_crops_by_class': [0, 5, 3, 3, 5, 3, 7, 9, 3, 4, 3, 5, 4, 9, 4, 5, 4, 2, 2, 1, 7, 2, 4], 'sampled_scene_counts': [2, 0, 0, 1, 0, 1, 2, 0, 1, 2, 1, 0, 0, 2, 0, 1, 0, 2, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 2, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 2, 0, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 2, 2, 2, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 1, 3, 2, 0, 2, 1, 1, 0, 4, 3, 2, 1, 2, 2, 0, 0, 3, 2, 0, 1, 3, 2, 2, 2, 3, 2, 0, 2, 2, 2, 0, 3, 0, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1, 3, 2, 1, 0, 2, 2, 1, 1, 1, 1, 1, 2, 0, 1, 2, 1, 0, 1, 0, 1, 2, 0, 1], 'learning_rate': 5.6064970859731574e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007231868129214364, 'train_segmentation_loss': 0.32669514008235223, 'val_foreground_miou_all22': 0.6882634893048866, 'val_psnr_ref1': 38.19592178344727, 'elapsed_seconds': 335.14399790763855, 'peak_cuda_allocated_gib': 7.503917694091797}

Epoch 233/500 | Batch 10/202 | Rec 0.000724 | Seg 0.327299 | Elapsed 0.2m | ETA 3.9m
Epoch 233/500 | Batch 20/202 | Rec 0.000686 | Seg 0.336660 | Elapsed 0.4m | ETA 3.8m
Epoch 233/500 | Batch 30/202 | Rec 0.000750 | Seg 0.362226 | Elapsed 0.6m | ETA 3.6m
Epoch 233/500 | Batch 40/202 | Rec 0.000762 | Seg 0.351822 | Elapsed 0.8m | ETA 3.4m
Epoch 233/500 | Batch 50/202 | Rec 0.000789 | Seg 0.358024 | Elapsed 1.1m | ETA 3.2m
Epoch 233/500 | Batch 60/202 | Rec 0.000805 | Seg 0.349877 | Elapsed 1.3m | ETA 3.0m
Epoch 233/500 | Batch 70/202 | Rec 0.000811 | Seg 0.355916 | Elapsed 1.5m | ETA 2.8m
Epoch 233/500 | Batch 80/202 | Rec 0.000790 | Seg 0.341971 | Elapsed 1.7m | ETA 2.6m
Epoch 233/500 | Batch 90/202 | Rec 0.000785 | Seg 0.332487 | Elapsed 1.9m | ETA 2.4m
Epoch 233/500 | Batch 100/202 | Rec 0.000777 | Seg 0.332119 | Elapsed 2.1m | ETA 2.1m
Epoch 233/500 | Batch 110/202 | Rec 0.000767 | Seg 0.322772 | Elapsed 2.3m | ETA 1.9m
Epoch 233/500 | Batch 120/202 | Rec 0.000753 | Seg 0.315707 | Elapsed 2.5m | ETA 1.7m
Epoch 233/500 | Batch 130/202 | Rec 0.000780 | Seg 0.333431 | Elapsed 2.7m | ETA 1.5m
Epoch 233/500 | Batch 140/202 | Rec 0.000773 | Seg 0.327390 | Elapsed 2.9m | ETA 1.3m
Epoch 233/500 | Batch 150/202 | Rec 0.000771 | Seg 0.333143 | Elapsed 3.2m | ETA 1.1m
Epoch 233/500 | Batch 160/202 | Rec 0.000763 | Seg 0.330111 | Elapsed 3.4m | ETA 0.9m
Epoch 233/500 | Batch 170/202 | Rec 0.000766 | Seg 0.328321 | Elapsed 3.6m | ETA 0.7m
Epoch 233/500 | Batch 180/202 | Rec 0.000765 | Seg 0.330920 | Elapsed 3.8m | ETA 0.5m
Epoch 233/500 | Batch 190/202 | Rec 0.000764 | Seg 0.330889 | Elapsed 4.0m | ETA 0.3m
Epoch 233/500 | Batch 200/202 | Rec 0.000768 | Seg 0.331681 | Elapsed 4.2m | ETA 0.0m
Epoch 233/500 | Batch 202/202 | Rec 0.000765 | Seg 0.330276 | Elapsed 4.3m | ETA 0.0m

2026-09-23 19:01:12,211 - INFO: Rec loss: 0.0007647619682703038
2026-09-23 19:01:12,211 - INFO: Seg loss: 0.330276203885822
2026-09-23 19:01:12,212 - INFO: λ_rec: 1
2026-09-23 19:01:12,212 - INFO: λ_seg: 0.0001
2026-09-23 19:02:31,106 - INFO: -------------------Epoch: 233------------------------
2026-09-23 19:02:31,110 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.989391  0.971146  0.000165
2026-09-23 19:02:31,117 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995348  0.997619  0.996366  0.998975  0.995556
real potato   0.833567  0.909180  0.997412  0.835374  0.999800
fake potato   0.794008  0.885128  0.983116  0.804985  0.999848
real apple    0.753624  0.859455  0.944244  0.788722  0.999110
fake apple    0.701311  0.824387  0.988974  0.706838  0.998863
real orange   0.588426  0.740845  0.999214  0.588698  0.999457
fake orange   0.811383  0.895822  0.835439  0.965729  0.999357
real grape    0.651279  0.788769  0.962721  0.668128  0.999253
fake grape    0.842541  0.914493  0.965437  0.868746  0.999399
real lemon    0.449823  0.620472  0.552126  0.708258  0.998982
fake lemon    0.846296  0.916701  0.986537  0.856185  0.999671
real avocado  0.828796  0.906334  0.879635  0.934811  0.999821
fake avocado  0.677546  0.807734  0.988374  0.682989  0.999611
real pepper   0.862284  0.926000  0.959808  0.894585  0.999477
fake pepper   0.896510  0.945382  0.988271  0.906152  0.999751
real plant    0.845213  0.916064  0.910660  0.921635  0.998312
fake plant    0.888480  0.940897  0.956797  0.925613  0.999908
real banana   0.481034  0.649547  0.934711  0.497759  0.998793
fake banana   0.645572  0.784567  0.741852  0.832614  0.999159
real onion    0.643385  0.782952  0.663383  0.955244  0.999522
fake onion    0.927616  0.962399  0.987036  0.939057  0.999954
real unknown  0.617950  0.763820  0.629012  0.972328  0.999904
fake unknown  0.251910  0.402402  0.271621  0.776349  0.998057
total         0.731909  0.832216  0.874902  0.827381  0.999199
total(-bg)    0.719934  0.824698  0.869381  0.819582  0.999364
2026-09-23 19:02:31,642 - INFO: Epoch accounting: {'epoch': 233, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11318086, 46980, 59269, 132226, 130262, 98236, 97975, 184841, 188608, 65604, 75839, 39639, 34053, 172075, 111563, 120396, 29723, 92981, 57075, 83986, 60897, 11671, 26287], 'crops_with_class': [202, 31, 29, 34, 31, 31, 33, 38, 35, 33, 28, 12, 13, 46, 36, 16, 24, 27, 24, 38, 26, 14, 16], 'targeted_crops_by_class': [0, 3, 1, 2, 9, 7, 3, 9, 2, 3, 7, 4, 4, 1, 6, 1, 4, 5, 4, 7, 5, 5, 2], 'sampled_scene_counts': [1, 2, 2, 0, 1, 2, 3, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 0, 2, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 5, 1, 2, 2, 1, 3, 1, 1, 1, 0, 0, 1, 1, 2, 5, 2, 1, 1, 1, 2, 1, 0, 4, 4, 1, 0, 1, 0, 0, 0, 0, 1, 0, 3, 2, 1, 0, 1, 3, 3, 0, 3, 2, 0, 1, 1, 1, 1, 1, 0, 2, 2, 4, 0, 2, 1, 1, 2, 1, 0, 3, 0, 4, 1, 1, 0, 1, 1, 1, 3, 1, 1, 0, 1, 2, 2, 2, 3, 2, 0], 'learning_rate': 5.575371219556484e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007647619682703038, 'train_segmentation_loss': 0.330276203885822, 'val_foreground_miou_all22': 0.7199343001242915, 'val_psnr_ref1': 37.989391479492184, 'elapsed_seconds': 334.6908257007599, 'peak_cuda_allocated_gib': 7.504947662353516}

Epoch 234/500 | Batch 10/202 | Rec 0.000783 | Seg 0.318532 | Elapsed 0.2m | ETA 4.0m
Epoch 234/500 | Batch 20/202 | Rec 0.000769 | Seg 0.321368 | Elapsed 0.4m | ETA 3.8m
Epoch 234/500 | Batch 30/202 | Rec 0.000716 | Seg 0.325756 | Elapsed 0.6m | ETA 3.6m
Epoch 234/500 | Batch 40/202 | Rec 0.000786 | Seg 0.332373 | Elapsed 0.8m | ETA 3.4m
Epoch 234/500 | Batch 50/202 | Rec 0.000789 | Seg 0.335446 | Elapsed 1.0m | ETA 3.2m
Epoch 234/500 | Batch 60/202 | Rec 0.000810 | Seg 0.342783 | Elapsed 1.2m | ETA 3.0m
Epoch 234/500 | Batch 70/202 | Rec 0.000822 | Seg 0.333366 | Elapsed 1.5m | ETA 2.7m
Epoch 234/500 | Batch 80/202 | Rec 0.000801 | Seg 0.327027 | Elapsed 1.7m | ETA 2.5m
Epoch 234/500 | Batch 90/202 | Rec 0.000793 | Seg 0.328264 | Elapsed 1.9m | ETA 2.3m
Epoch 234/500 | Batch 100/202 | Rec 0.000796 | Seg 0.334440 | Elapsed 2.1m | ETA 2.1m
Epoch 234/500 | Batch 110/202 | Rec 0.000795 | Seg 0.333635 | Elapsed 2.3m | ETA 1.9m
Epoch 234/500 | Batch 120/202 | Rec 0.000792 | Seg 0.331678 | Elapsed 2.5m | ETA 1.7m
Epoch 234/500 | Batch 130/202 | Rec 0.000786 | Seg 0.327424 | Elapsed 2.7m | ETA 1.5m
Epoch 234/500 | Batch 140/202 | Rec 0.000766 | Seg 0.320600 | Elapsed 2.9m | ETA 1.3m
Epoch 234/500 | Batch 150/202 | Rec 0.000759 | Seg 0.318326 | Elapsed 3.1m | ETA 1.1m
Epoch 234/500 | Batch 160/202 | Rec 0.000764 | Seg 0.319173 | Elapsed 3.3m | ETA 0.9m
Epoch 234/500 | Batch 170/202 | Rec 0.000764 | Seg 0.318484 | Elapsed 3.5m | ETA 0.7m
Epoch 234/500 | Batch 180/202 | Rec 0.000759 | Seg 0.318461 | Elapsed 3.8m | ETA 0.5m
Epoch 234/500 | Batch 190/202 | Rec 0.000756 | Seg 0.320875 | Elapsed 4.0m | ETA 0.3m
Epoch 234/500 | Batch 200/202 | Rec 0.000759 | Seg 0.323730 | Elapsed 4.2m | ETA 0.0m
Epoch 234/500 | Batch 202/202 | Rec 0.000756 | Seg 0.323704 | Elapsed 4.2m | ETA 0.0m

2026-09-23 19:06:44,824 - INFO: Rec loss: 0.0007562104236256184
2026-09-23 19:06:44,824 - INFO: Seg loss: 0.3237038019786377
2026-09-23 19:06:44,824 - INFO: λ_rec: 1
2026-09-23 19:06:44,824 - INFO: λ_seg: 0.0001
2026-09-23 19:08:05,210 - INFO: -------------------Epoch: 234------------------------
2026-09-23 19:08:05,214 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.980144  0.972177  0.000166
2026-09-23 19:08:05,221 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995495  0.997692  0.996656  0.998831  0.995697
real potato   0.413542  0.585074  1.000000  0.413542  0.999298
fake potato   0.677426  0.807648  0.973412  0.690197  0.999761
real apple    0.702759  0.825385  0.796716  0.856303  0.998750
fake apple    0.645663  0.784636  0.975377  0.656361  0.998640
real orange   0.821581  0.902003  0.992082  0.827003  0.999763
fake orange   0.892776  0.943301  0.909838  0.979426  0.999663
real grape    0.675064  0.805967  0.970271  0.689323  0.999307
fake grape    0.844497  0.915643  0.945440  0.887761  0.999395
real lemon    0.320539  0.485422  0.375872  0.685277  0.998293
fake lemon    0.856350  0.922567  0.984459  0.868085  0.999692
real avocado  0.936287  0.967045  0.984024  0.950739  0.999940
fake avocado  0.111678  0.200899  0.997722  0.111706  0.998937
real pepper   0.878228  0.935117  0.948590  0.922117  0.999532
fake pepper   0.892981  0.943415  0.981729  0.908072  0.999741
real plant    0.843479  0.915045  0.917692  0.912512  0.998306
fake plant    0.773295  0.872106  0.877230  0.867140  0.999798
real banana   0.262483  0.415784  0.893617  0.270949  0.998289
fake banana   0.651636  0.789030  0.744700  0.839084  0.999175
real onion    0.657601  0.793387  0.747573  0.845296  0.999602
fake onion    0.932873  0.965221  0.983438  0.947763  0.999957
real unknown  0.950382  0.974510  1.000000  0.950382  0.999992
fake unknown  0.185196  0.312484  0.194365  0.796994  0.997045
total         0.692253  0.785191  0.877861  0.777168  0.999068
total(-bg)    0.678469  0.775531  0.872461  0.767092  0.999222
2026-09-23 19:08:05,764 - INFO: Epoch accounting: {'epoch': 234, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11371006, 47257, 56596, 142422, 137599, 85802, 59639, 166113, 165704, 65007, 54810, 54369, 34044, 165771, 107824, 192249, 24829, 69523, 47814, 90104, 45635, 13641, 40514], 'crops_with_class': [202, 24, 23, 36, 33, 28, 23, 30, 34, 30, 23, 17, 12, 42, 28, 25, 23, 21, 25, 35, 22, 17, 18], 'targeted_crops_by_class': [0, 7, 5, 8, 2, 6, 6, 8, 5, 3, 5, 6, 4, 3, 2, 8, 7, 4, 4, 7, 3, 6, 2], 'sampled_scene_counts': [3, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 2, 1, 1, 2, 0, 0, 2, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 0, 2, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 2, 0, 1, 2, 2, 1, 1, 1, 1, 2, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2, 0, 1, 0, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 0, 2, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 1, 2, 0, 1, 1, 2, 2, 1, 1, 1, 0, 1, 0, 3, 5, 3, 1, 0, 1, 2, 1, 1, 3, 2, 1, 1, 0, 2, 3, 3, 2, 0, 2, 1, 0, 1, 2, 2, 1, 0, 3, 2, 1, 4, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 4, 0, 0, 1, 3, 2, 1, 1, 1, 3], 'learning_rate': 5.544223131947853e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007562104236256184, 'train_segmentation_loss': 0.3237038019786377, 'val_foreground_miou_all22': 0.6784688293512915, 'val_psnr_ref1': 37.98014389038086, 'elapsed_seconds': 334.11361503601074, 'peak_cuda_allocated_gib': 7.510807037353516}

Epoch 235/500 | Batch 10/202 | Rec 0.000833 | Seg 0.337837 | Elapsed 0.2m | ETA 4.0m
Epoch 235/500 | Batch 20/202 | Rec 0.000803 | Seg 0.356169 | Elapsed 0.4m | ETA 3.9m
Epoch 235/500 | Batch 30/202 | Rec 0.000824 | Seg 0.347846 | Elapsed 0.6m | ETA 3.6m
Epoch 235/500 | Batch 40/202 | Rec 0.000848 | Seg 0.367069 | Elapsed 0.8m | ETA 3.4m
Epoch 235/500 | Batch 50/202 | Rec 0.000831 | Seg 0.353164 | Elapsed 1.1m | ETA 3.2m
Epoch 235/500 | Batch 60/202 | Rec 0.000822 | Seg 0.359796 | Elapsed 1.3m | ETA 3.0m
Epoch 235/500 | Batch 70/202 | Rec 0.000809 | Seg 0.353136 | Elapsed 1.5m | ETA 2.8m
Epoch 235/500 | Batch 80/202 | Rec 0.000797 | Seg 0.346588 | Elapsed 1.7m | ETA 2.6m
Epoch 235/500 | Batch 90/202 | Rec 0.000791 | Seg 0.344076 | Elapsed 1.9m | ETA 2.4m
Epoch 235/500 | Batch 100/202 | Rec 0.000792 | Seg 0.352529 | Elapsed 2.1m | ETA 2.2m
Epoch 235/500 | Batch 110/202 | Rec 0.000793 | Seg 0.352911 | Elapsed 2.3m | ETA 1.9m
Epoch 235/500 | Batch 120/202 | Rec 0.000768 | Seg 0.342591 | Elapsed 2.5m | ETA 1.7m
Epoch 235/500 | Batch 130/202 | Rec 0.000754 | Seg 0.337942 | Elapsed 2.7m | ETA 1.5m
Epoch 235/500 | Batch 140/202 | Rec 0.000745 | Seg 0.336706 | Elapsed 2.9m | ETA 1.3m
Epoch 235/500 | Batch 150/202 | Rec 0.000744 | Seg 0.333723 | Elapsed 3.2m | ETA 1.1m
Epoch 235/500 | Batch 160/202 | Rec 0.000732 | Seg 0.329611 | Elapsed 3.4m | ETA 0.9m
Epoch 235/500 | Batch 170/202 | Rec 0.000722 | Seg 0.327224 | Elapsed 3.6m | ETA 0.7m
Epoch 235/500 | Batch 180/202 | Rec 0.000719 | Seg 0.325904 | Elapsed 3.8m | ETA 0.5m
Epoch 235/500 | Batch 190/202 | Rec 0.000721 | Seg 0.328925 | Elapsed 4.0m | ETA 0.3m
Epoch 235/500 | Batch 200/202 | Rec 0.000729 | Seg 0.329452 | Elapsed 4.2m | ETA 0.0m
Epoch 235/500 | Batch 202/202 | Rec 0.000731 | Seg 0.330405 | Elapsed 4.2m | ETA 0.0m

2026-09-23 19:12:20,697 - INFO: Rec loss: 0.0007308442158553067
2026-09-23 19:12:20,697 - INFO: Seg loss: 0.3304052898420556
2026-09-23 19:12:20,697 - INFO: λ_rec: 1
2026-09-23 19:12:20,697 - INFO: λ_seg: 0.0001
2026-09-23 19:13:41,607 - INFO: -------------------Epoch: 235------------------------
2026-09-23 19:13:41,611 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  37.97922  0.971615  0.000167
2026-09-23 19:13:41,618 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995612  0.997751  0.996914  0.998689  0.995810
real potato   0.811258  0.895746  0.998433  0.812293  0.999774
fake potato   0.936717  0.967274  0.980009  0.954964  0.999953
real apple    0.770253  0.870168  0.933529  0.814949  0.999161
fake apple    0.615084  0.761626  0.935385  0.642378  0.998482
real orange   0.822021  0.902268  0.986132  0.831635  0.999763
fake orange   0.888856  0.941108  0.916894  0.966741  0.999654
real grape    0.692862  0.818520  0.967411  0.709420  0.999343
fake grape    0.873709  0.932549  0.919567  0.946005  0.999494
real lemon    0.513917  0.678877  0.539426  0.915736  0.998982
fake lemon    0.841037  0.913606  0.997865  0.842553  0.999663
real avocado  0.788666  0.881799  0.832871  0.936946  0.999767
fake avocado  0.730955  0.844520  0.998608  0.731701  0.999678
real pepper   0.833991  0.909432  0.911540  0.907434  0.999339
fake pepper   0.849411  0.918525  0.988421  0.857948  0.999637
real plant    0.858032  0.923542  0.928095  0.919133  0.998479
fake plant    0.873252  0.932288  0.908347  0.957630  0.999889
real banana   0.473794  0.642913  0.922101  0.493549  0.998768
fake banana   0.661309  0.796080  0.754211  0.842983  0.999206
real onion    0.713196  0.832542  0.742555  0.947475  0.999656
fake onion    0.947481  0.972982  0.982020  0.964208  0.999966
real unknown  0.924528  0.960734  0.987903  0.935114  0.999988
fake unknown  0.265030  0.418970  0.289466  0.758421  0.998228
total         0.768738  0.857123  0.887726  0.855996  0.999247
total(-bg)    0.758425  0.850730  0.882763  0.849510  0.999403
2026-09-23 19:13:42,339 - INFO: Epoch accounting: {'epoch': 235, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11270031, 35462, 42461, 132251, 136273, 115838, 88124, 152595, 189502, 81061, 72626, 43173, 62648, 248006, 130144, 138865, 29336, 50868, 68887, 53886, 34404, 8898, 52933], 'crops_with_class': [202, 21, 21, 41, 38, 34, 30, 29, 36, 35, 29, 14, 23, 60, 30, 24, 24, 15, 32, 26, 18, 11, 23], 'targeted_crops_by_class': [0, 2, 2, 7, 4, 8, 6, 3, 6, 4, 4, 5, 9, 7, 3, 3, 4, 3, 6, 2, 4, 2, 4], 'sampled_scene_counts': [0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 1, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 3, 0, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 3, 2, 2, 2, 4, 1, 0, 2, 0, 3, 2, 0, 1, 3, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 4, 1, 5, 1, 3, 2, 1, 2, 2, 0, 2, 1, 3, 1, 3, 3, 2, 2, 1, 1, 2, 2, 1, 1, 2, 0, 1, 3, 0, 0, 2, 2, 1, 1, 0, 0, 1, 0, 1, 2, 0, 1, 1, 0, 2, 2, 1, 0, 0, 0, 1, 2, 1, 1, 1, 0, 1], 'learning_rate': 5.513054052820428e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007308442158553067, 'train_segmentation_loss': 0.3304052898420556, 'val_foreground_miou_all22': 0.7584254897344173, 'val_psnr_ref1': 37.97922027587891, 'elapsed_seconds': 336.56754779815674, 'peak_cuda_allocated_gib': 7.510532379150391}

Epoch 236/500 | Batch 10/202 | Rec 0.000727 | Seg 0.338087 | Elapsed 0.2m | ETA 4.1m
Epoch 236/500 | Batch 20/202 | Rec 0.000686 | Seg 0.342448 | Elapsed 0.4m | ETA 3.8m
Epoch 236/500 | Batch 30/202 | Rec 0.000815 | Seg 0.349896 | Elapsed 0.6m | ETA 3.6m
Epoch 236/500 | Batch 40/202 | Rec 0.000801 | Seg 0.346621 | Elapsed 0.8m | ETA 3.4m
Epoch 236/500 | Batch 50/202 | Rec 0.000789 | Seg 0.334414 | Elapsed 1.1m | ETA 3.2m
Epoch 236/500 | Batch 60/202 | Rec 0.000804 | Seg 0.339819 | Elapsed 1.3m | ETA 3.0m
Epoch 236/500 | Batch 70/202 | Rec 0.000822 | Seg 0.343189 | Elapsed 1.5m | ETA 2.8m
Epoch 236/500 | Batch 80/202 | Rec 0.000809 | Seg 0.340931 | Elapsed 1.7m | ETA 2.6m
Epoch 236/500 | Batch 90/202 | Rec 0.000782 | Seg 0.331132 | Elapsed 1.9m | ETA 2.4m
Epoch 236/500 | Batch 100/202 | Rec 0.000809 | Seg 0.341186 | Elapsed 2.1m | ETA 2.1m
Epoch 236/500 | Batch 110/202 | Rec 0.000801 | Seg 0.339908 | Elapsed 2.3m | ETA 1.9m
Epoch 236/500 | Batch 120/202 | Rec 0.000798 | Seg 0.344975 | Elapsed 2.5m | ETA 1.7m
Epoch 236/500 | Batch 130/202 | Rec 0.000805 | Seg 0.343619 | Elapsed 2.7m | ETA 1.5m
Epoch 236/500 | Batch 140/202 | Rec 0.000800 | Seg 0.343184 | Elapsed 2.9m | ETA 1.3m
Epoch 236/500 | Batch 150/202 | Rec 0.000792 | Seg 0.342662 | Elapsed 3.1m | ETA 1.1m
Epoch 236/500 | Batch 160/202 | Rec 0.000789 | Seg 0.342952 | Elapsed 3.3m | ETA 0.9m
Epoch 236/500 | Batch 170/202 | Rec 0.000791 | Seg 0.340184 | Elapsed 3.6m | ETA 0.7m
Epoch 236/500 | Batch 180/202 | Rec 0.000787 | Seg 0.338381 | Elapsed 3.8m | ETA 0.5m
Epoch 236/500 | Batch 190/202 | Rec 0.000793 | Seg 0.338293 | Elapsed 4.0m | ETA 0.3m
Epoch 236/500 | Batch 200/202 | Rec 0.000790 | Seg 0.340939 | Elapsed 4.2m | ETA 0.0m
Epoch 236/500 | Batch 202/202 | Rec 0.000788 | Seg 0.339698 | Elapsed 4.2m | ETA 0.0m

2026-09-23 19:17:56,636 - INFO: Rec loss: 0.000787705754588063
2026-09-23 19:17:56,637 - INFO: Seg loss: 0.33969839562726495
2026-09-23 19:17:56,637 - INFO: λ_rec: 1
2026-09-23 19:17:56,637 - INFO: λ_seg: 0.0001
2026-09-23 19:19:16,439 - INFO: -------------------Epoch: 236------------------------
2026-09-23 19:19:16,443 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  37.941375  0.97148  0.000166
2026-09-23 19:19:16,449 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995432  0.997661  0.996518  0.998906  0.995636
real potato   0.502166  0.668545  0.998480  0.502550  0.999404
fake potato   0.746716  0.854945  0.973769  0.762044  0.999812
real apple    0.672294  0.803988  0.823480  0.785493  0.998679
fake apple    0.730317  0.844093  0.986384  0.737755  0.998971
real orange   0.531613  0.694142  0.989921  0.534507  0.999379
fake orange   0.795186  0.885860  0.807716  0.980866  0.999277
real grape    0.601919  0.751450  0.978771  0.609881  0.999158
fake grape    0.868842  0.929769  0.930587  0.929052  0.999481
real lemon    0.400815  0.572215  0.426622  0.868865  0.998474
fake lemon    0.843175  0.914866  0.995336  0.846520  0.999667
real avocado  0.791088  0.883310  0.829655  0.944499  0.999768
fake avocado  0.447322  0.618094  0.989888  0.449375  0.999336
real pepper   0.853607  0.920972  0.940944  0.901927  0.999434
fake pepper   0.869883  0.930364  0.990317  0.877345  0.999687
real plant    0.824059  0.903494  0.905677  0.901422  0.998075
fake plant    0.847681  0.917512  0.910206  0.925038  0.999868
real banana   0.206337  0.342060  0.956942  0.208271  0.998200
fake banana   0.724486  0.840184  0.853573  0.827306  0.999421
real onion    0.632841  0.775093  0.666100  0.926870  0.999514
fake onion    0.951301  0.974993  0.986630  0.963724  0.999969
real unknown  0.550654  0.710175  0.561979  0.964695  0.999874
fake unknown  0.247412  0.396644  0.261383  0.822347  0.997892
total         0.679789  0.788280  0.859169  0.794316  0.999086
total(-bg)    0.665442  0.778762  0.852925  0.785016  0.999243
2026-09-23 19:19:16,974 - INFO: Epoch accounting: {'epoch': 236, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11252210, 43847, 51198, 127617, 137402, 59244, 62377, 133707, 225292, 57698, 74853, 58731, 25654, 214002, 130366, 200473, 33690, 78454, 78277, 81400, 67383, 10216, 34181], 'crops_with_class': [202, 29, 27, 35, 32, 20, 22, 30, 37, 25, 23, 19, 12, 54, 32, 26, 30, 25, 32, 34, 28, 9, 19], 'targeted_crops_by_class': [0, 5, 2, 8, 6, 3, 3, 4, 3, 7, 0, 7, 3, 7, 4, 4, 6, 5, 8, 3, 6, 5, 5], 'sampled_scene_counts': [0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 3, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 2, 0, 1, 1, 0, 0, 0, 1, 0, 3, 0, 0, 3, 1, 0, 1, 1, 1, 0, 0, 2, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 1, 0, 2, 2, 2, 1, 1, 1, 3, 0, 1, 0, 1, 5, 3, 1, 1, 0, 1, 0, 1, 1, 4, 2, 1, 1, 2, 1, 4, 2, 1, 1, 1, 1, 1, 7, 1, 0, 0, 6, 2, 0, 1, 2, 1, 1, 0, 1, 2, 0, 0, 2, 4, 1, 1, 0, 0, 4, 1, 0, 1, 1, 3, 3, 1, 1, 3, 1, 3, 2, 1, 1, 1, 1, 0, 0, 3, 0, 1, 1], 'learning_rate': 5.481865212676084e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000787705754588063, 'train_segmentation_loss': 0.33969839562726495, 'val_foreground_miou_all22': 0.6654415626820669, 'val_psnr_ref1': 37.941374969482425, 'elapsed_seconds': 334.62640619277954, 'peak_cuda_allocated_gib': 7.5104522705078125}

Epoch 237/500 | Batch 10/202 | Rec 0.000729 | Seg 0.335248 | Elapsed 0.2m | ETA 4.1m
Epoch 237/500 | Batch 20/202 | Rec 0.000791 | Seg 0.355214 | Elapsed 0.4m | ETA 3.9m
Epoch 237/500 | Batch 30/202 | Rec 0.000794 | Seg 0.353440 | Elapsed 0.6m | ETA 3.6m
Epoch 237/500 | Batch 40/202 | Rec 0.000761 | Seg 0.338038 | Elapsed 0.8m | ETA 3.4m
Epoch 237/500 | Batch 50/202 | Rec 0.000784 | Seg 0.345027 | Elapsed 1.1m | ETA 3.2m
Epoch 237/500 | Batch 60/202 | Rec 0.000806 | Seg 0.340514 | Elapsed 1.3m | ETA 3.0m
Epoch 237/500 | Batch 70/202 | Rec 0.000768 | Seg 0.328841 | Elapsed 1.5m | ETA 2.8m
Epoch 237/500 | Batch 80/202 | Rec 0.000808 | Seg 0.340011 | Elapsed 1.7m | ETA 2.6m
Epoch 237/500 | Batch 90/202 | Rec 0.000792 | Seg 0.337106 | Elapsed 1.9m | ETA 2.4m
Epoch 237/500 | Batch 100/202 | Rec 0.000787 | Seg 0.339208 | Elapsed 2.1m | ETA 2.1m
Epoch 237/500 | Batch 110/202 | Rec 0.000775 | Seg 0.336532 | Elapsed 2.3m | ETA 1.9m
Epoch 237/500 | Batch 120/202 | Rec 0.000773 | Seg 0.334289 | Elapsed 2.5m | ETA 1.7m
Epoch 237/500 | Batch 130/202 | Rec 0.000760 | Seg 0.330871 | Elapsed 2.7m | ETA 1.5m
Epoch 237/500 | Batch 140/202 | Rec 0.000755 | Seg 0.327711 | Elapsed 2.9m | ETA 1.3m
Epoch 237/500 | Batch 150/202 | Rec 0.000767 | Seg 0.330044 | Elapsed 3.1m | ETA 1.1m
Epoch 237/500 | Batch 160/202 | Rec 0.000773 | Seg 0.336595 | Elapsed 3.4m | ETA 0.9m
Epoch 237/500 | Batch 170/202 | Rec 0.000767 | Seg 0.332194 | Elapsed 3.6m | ETA 0.7m
Epoch 237/500 | Batch 180/202 | Rec 0.000769 | Seg 0.331800 | Elapsed 3.8m | ETA 0.5m
Epoch 237/500 | Batch 190/202 | Rec 0.000767 | Seg 0.331926 | Elapsed 4.0m | ETA 0.3m
Epoch 237/500 | Batch 200/202 | Rec 0.000761 | Seg 0.329460 | Elapsed 4.2m | ETA 0.0m
Epoch 237/500 | Batch 202/202 | Rec 0.000757 | Seg 0.329208 | Elapsed 4.2m | ETA 0.0m

2026-09-23 19:23:30,669 - INFO: Rec loss: 0.0007572521957410914
2026-09-23 19:23:30,670 - INFO: Seg loss: 0.3292084963309883
2026-09-23 19:23:30,670 - INFO: λ_rec: 1
2026-09-23 19:23:30,670 - INFO: λ_seg: 0.0001
2026-09-23 19:24:52,783 - INFO: -------------------Epoch: 237------------------------
2026-09-23 19:24:52,787 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  37.841476  0.97236  0.000172
2026-09-23 19:24:52,794 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995761  0.997826  0.997324  0.998429  0.995954
real potato   0.464803  0.634585  0.992404  0.466463  0.999357
fake potato   0.794568  0.885476  0.969357  0.815040  0.999846
real apple    0.680217  0.809628  0.790019  0.830341  0.998653
fake apple    0.776736  0.874291  0.984025  0.786655  0.999146
real orange   0.863647  0.926785  0.988969  0.872047  0.999819
fake orange   0.902518  0.948711  0.915997  0.983957  0.999696
real grape    0.699885  0.823400  0.904779  0.755536  0.999324
fake grape    0.873848  0.932628  0.911979  0.954337  0.999490
real lemon    0.475504  0.644485  0.502101  0.899766  0.998834
fake lemon    0.849198  0.918401  0.991062  0.855752  0.999678
real avocado  0.753224  0.859195  0.771948  0.968801  0.999705
fake avocado  0.790017  0.882643  0.998230  0.791125  0.999748
real pepper   0.812844  0.896711  0.894361  0.899174  0.999243
fake pepper   0.796082  0.886416  0.976361  0.811728  0.999504
real plant    0.856581  0.922701  0.916078  0.929522  0.998443
fake plant    0.826416  0.904909  0.869981  0.942868  0.999842
real banana   0.411146  0.582669  0.927364  0.424827  0.998633
fake banana   0.758225  0.862439  0.882828  0.843066  0.999505
real onion    0.622869  0.767565  0.707390  0.839047  0.999541
fake onion    0.966498  0.982914  0.996521  0.969770  0.999979
real unknown  0.537662  0.699279  0.541318  0.987595  0.999864
fake unknown  0.316725  0.481037  0.353728  0.751720  0.998634
total         0.731521  0.831508  0.860179  0.842503  0.999236
total(-bg)    0.719510  0.823948  0.853945  0.835415  0.999386
2026-09-23 19:24:53,308 - INFO: Epoch accounting: {'epoch': 237, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11326308, 50847, 61316, 98204, 121212, 95878, 70565, 157132, 201938, 64223, 58886, 31120, 47113, 209462, 116798, 137983, 25882, 82699, 91539, 85780, 49339, 11319, 42729], 'crops_with_class': [202, 30, 31, 26, 33, 28, 26, 33, 38, 31, 26, 11, 17, 56, 35, 21, 24, 26, 32, 36, 23, 14, 21], 'targeted_crops_by_class': [0, 6, 3, 4, 3, 4, 3, 8, 6, 6, 5, 4, 8, 7, 7, 5, 5, 4, 5, 5, 3, 4, 2], 'sampled_scene_counts': [1, 2, 2, 0, 2, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 0, 2, 1, 2, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 4, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 1, 0, 2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 3, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 0, 0, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 3, 1, 1, 0, 3, 3, 0, 1, 1, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 3, 4, 2, 1, 0, 5, 2, 5, 2, 0, 0, 1, 2, 2, 0, 3, 1, 2, 1, 0, 1, 0, 0, 1, 2, 3, 0, 1, 1, 2, 1, 0, 1, 3, 1, 2, 1, 1, 1, 1, 0, 2, 1], 'learning_rate': 5.450657842796826e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007572521957410914, 'train_segmentation_loss': 0.3292084963309883, 'val_foreground_miou_all22': 0.7195096346206604, 'val_psnr_ref1': 37.841475830078124, 'elapsed_seconds': 336.3265368938446, 'peak_cuda_allocated_gib': 7.506870269775391}

Epoch 238/500 | Batch 10/202 | Rec 0.000698 | Seg 0.297586 | Elapsed 0.2m | ETA 4.0m
Epoch 238/500 | Batch 20/202 | Rec 0.000758 | Seg 0.294898 | Elapsed 0.4m | ETA 3.9m
Epoch 238/500 | Batch 30/202 | Rec 0.000713 | Seg 0.283627 | Elapsed 0.6m | ETA 3.6m
Epoch 238/500 | Batch 40/202 | Rec 0.000731 | Seg 0.312524 | Elapsed 0.8m | ETA 3.4m
Epoch 238/500 | Batch 50/202 | Rec 0.000758 | Seg 0.323949 | Elapsed 1.0m | ETA 3.2m
Epoch 238/500 | Batch 60/202 | Rec 0.000768 | Seg 0.329467 | Elapsed 1.3m | ETA 3.0m
Epoch 238/500 | Batch 70/202 | Rec 0.000766 | Seg 0.332548 | Elapsed 1.5m | ETA 2.8m
Epoch 238/500 | Batch 80/202 | Rec 0.000796 | Seg 0.349867 | Elapsed 1.7m | ETA 2.6m
Epoch 238/500 | Batch 90/202 | Rec 0.000782 | Seg 0.353097 | Elapsed 1.9m | ETA 2.3m
Epoch 238/500 | Batch 100/202 | Rec 0.000784 | Seg 0.355747 | Elapsed 2.1m | ETA 2.1m
Epoch 238/500 | Batch 110/202 | Rec 0.000781 | Seg 0.355978 | Elapsed 2.3m | ETA 1.9m
Epoch 238/500 | Batch 120/202 | Rec 0.000782 | Seg 0.358404 | Elapsed 2.5m | ETA 1.7m
Epoch 238/500 | Batch 130/202 | Rec 0.000774 | Seg 0.357015 | Elapsed 2.7m | ETA 1.5m
Epoch 238/500 | Batch 140/202 | Rec 0.000767 | Seg 0.356642 | Elapsed 2.9m | ETA 1.3m
Epoch 238/500 | Batch 150/202 | Rec 0.000774 | Seg 0.360128 | Elapsed 3.2m | ETA 1.1m
Epoch 238/500 | Batch 160/202 | Rec 0.000774 | Seg 0.357274 | Elapsed 3.4m | ETA 0.9m
Epoch 238/500 | Batch 170/202 | Rec 0.000767 | Seg 0.352504 | Elapsed 3.6m | ETA 0.7m
Epoch 238/500 | Batch 180/202 | Rec 0.000768 | Seg 0.352773 | Elapsed 3.8m | ETA 0.5m
Epoch 238/500 | Batch 190/202 | Rec 0.000782 | Seg 0.353751 | Elapsed 4.0m | ETA 0.3m
Epoch 238/500 | Batch 200/202 | Rec 0.000773 | Seg 0.349558 | Elapsed 4.2m | ETA 0.0m
Epoch 238/500 | Batch 202/202 | Rec 0.000771 | Seg 0.349963 | Elapsed 4.2m | ETA 0.0m

2026-09-23 19:29:07,161 - INFO: Rec loss: 0.0007711599900365328
2026-09-23 19:29:07,161 - INFO: Seg loss: 0.3499631729013849
2026-09-23 19:29:07,161 - INFO: λ_rec: 1
2026-09-23 19:29:07,161 - INFO: λ_seg: 0.0001
2026-09-23 19:30:27,897 - INFO: -------------------Epoch: 238------------------------
2026-09-23 19:30:27,900 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.816105  0.972083  0.000173
2026-09-23 19:30:27,907 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995568  0.997729  0.997054  0.998505  0.995768
real potato   0.878113  0.935052  0.984765  0.890207  0.999852
fake potato   0.954582  0.976714  0.971802  0.981776  0.999966
real apple    0.736283  0.848065  0.957906  0.760902  0.999060
fake apple    0.625724  0.769731  0.981762  0.633083  0.998570
real orange   0.938469  0.968208  0.990909  0.946619  0.999918
fake orange   0.937317  0.967594  0.947124  0.989074  0.999811
real grape    0.725849  0.841101  0.948532  0.755609  0.999404
fake grape    0.895390  0.944758  0.949810  0.939859  0.999594
real lemon    0.428685  0.600064  0.491667  0.769930  0.998794
fake lemon    0.846477  0.916807  0.985731  0.856978  0.999671
real avocado  0.872363  0.931781  0.913812  0.950575  0.999871
fake avocado  0.593754  0.745054  0.999356  0.593981  0.999514
real pepper   0.852056  0.920069  0.923951  0.916319  0.999418
fake pepper   0.931172  0.964309  0.986541  0.943153  0.999834
real plant    0.851920  0.919990  0.916309  0.923801  0.998394
fake plant    0.824398  0.903698  0.908387  0.899156  0.999848
real banana   0.421811  0.593300  0.931947  0.435217  0.998660
fake banana   0.663902  0.797956  0.786468  0.809887  0.999246
real onion    0.579811  0.733978  0.593659  0.961324  0.999371
fake onion    0.921957  0.959344  0.985962  0.934220  0.999950
real unknown  0.491434  0.658964  0.502251  0.958015  0.999841
fake unknown  0.242066  0.389743  0.257972  0.796994  0.997897
total         0.748222  0.838435  0.865812  0.854138  0.999228
total(-bg)    0.736979  0.831194  0.859847  0.847576  0.999386
2026-09-23 19:30:28,448 - INFO: Epoch accounting: {'epoch': 238, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11210159, 53925, 62966, 116559, 174435, 97497, 88139, 146539, 155714, 83270, 71463, 35631, 32526, 196833, 119664, 166379, 29079, 119756, 83038, 101617, 56538, 12551, 23994], 'crops_with_class': [202, 32, 29, 33, 35, 26, 33, 29, 30, 35, 30, 13, 12, 53, 35, 21, 25, 33, 35, 45, 30, 12, 15], 'targeted_crops_by_class': [0, 5, 6, 3, 6, 2, 6, 5, 3, 6, 9, 2, 4, 4, 2, 3, 8, 12, 3, 4, 8, 4, 2], 'sampled_scene_counts': [2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 3, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2, 0, 2, 1, 3, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 2, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 2, 3, 2, 2, 2, 1, 0, 1, 0, 1, 3, 1, 3, 3, 2, 2, 1, 2, 3, 0, 1, 1, 0, 2, 3, 0, 1, 0, 0, 2, 0, 1, 0, 0, 1, 1, 2, 0, 2, 1, 5, 2, 1, 0, 1, 1, 1, 3, 4, 1, 1, 3, 1, 2, 1, 1, 2, 1, 1, 1, 3, 1, 0, 3, 2, 1, 1, 2, 0, 5, 3, 2, 0, 1, 1, 3, 0, 2, 1, 2, 1], 'learning_rate': 5.41943317519618e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007711599900365328, 'train_segmentation_loss': 0.3499631729013849, 'val_foreground_miou_all22': 0.7369787750829058, 'val_psnr_ref1': 37.8161051940918, 'elapsed_seconds': 335.1327118873596, 'peak_cuda_allocated_gib': 7.506381988525391}

Epoch 239/500 | Batch 10/202 | Rec 0.000801 | Seg 0.344072 | Elapsed 0.2m | ETA 4.2m
Epoch 239/500 | Batch 20/202 | Rec 0.000798 | Seg 0.347015 | Elapsed 0.4m | ETA 3.8m
Epoch 239/500 | Batch 30/202 | Rec 0.000773 | Seg 0.342514 | Elapsed 0.6m | ETA 3.6m
Epoch 239/500 | Batch 40/202 | Rec 0.000755 | Seg 0.357983 | Elapsed 0.8m | ETA 3.4m
Epoch 239/500 | Batch 50/202 | Rec 0.000725 | Seg 0.349639 | Elapsed 1.1m | ETA 3.2m
Epoch 239/500 | Batch 60/202 | Rec 0.000729 | Seg 0.350790 | Elapsed 1.3m | ETA 3.0m
Epoch 239/500 | Batch 70/202 | Rec 0.000714 | Seg 0.343901 | Elapsed 1.5m | ETA 2.8m
Epoch 239/500 | Batch 80/202 | Rec 0.000714 | Seg 0.342755 | Elapsed 1.7m | ETA 2.6m
Epoch 239/500 | Batch 90/202 | Rec 0.000715 | Seg 0.340332 | Elapsed 1.9m | ETA 2.4m
Epoch 239/500 | Batch 100/202 | Rec 0.000716 | Seg 0.337689 | Elapsed 2.1m | ETA 2.2m
Epoch 239/500 | Batch 110/202 | Rec 0.000702 | Seg 0.333159 | Elapsed 2.3m | ETA 1.9m
Epoch 239/500 | Batch 120/202 | Rec 0.000701 | Seg 0.325712 | Elapsed 2.5m | ETA 1.7m
Epoch 239/500 | Batch 130/202 | Rec 0.000686 | Seg 0.317392 | Elapsed 2.7m | ETA 1.5m
Epoch 239/500 | Batch 140/202 | Rec 0.000682 | Seg 0.315626 | Elapsed 3.0m | ETA 1.3m
Epoch 239/500 | Batch 150/202 | Rec 0.000672 | Seg 0.311609 | Elapsed 3.2m | ETA 1.1m
Epoch 239/500 | Batch 160/202 | Rec 0.000692 | Seg 0.319378 | Elapsed 3.4m | ETA 0.9m
Epoch 239/500 | Batch 170/202 | Rec 0.000687 | Seg 0.315148 | Elapsed 3.6m | ETA 0.7m
Epoch 239/500 | Batch 180/202 | Rec 0.000698 | Seg 0.320868 | Elapsed 3.8m | ETA 0.5m
Epoch 239/500 | Batch 190/202 | Rec 0.000703 | Seg 0.320637 | Elapsed 4.0m | ETA 0.3m
Epoch 239/500 | Batch 200/202 | Rec 0.000715 | Seg 0.326671 | Elapsed 4.2m | ETA 0.0m
Epoch 239/500 | Batch 202/202 | Rec 0.000714 | Seg 0.325968 | Elapsed 4.3m | ETA 0.0m

2026-09-23 19:34:44,528 - INFO: Rec loss: 0.000714492286992891
2026-09-23 19:34:44,528 - INFO: Seg loss: 0.3259680413521162
2026-09-23 19:34:44,528 - INFO: λ_rec: 1
2026-09-23 19:34:44,528 - INFO: λ_seg: 0.0001
2026-09-23 19:36:03,198 - INFO: -------------------Epoch: 239------------------------
2026-09-23 19:36:03,201 - INFO:
Validation stats:
       PSNR    SSIM       MSE
0  37.74135  0.9726  0.000175
2026-09-23 19:36:03,208 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995786  0.997838  0.997193  0.998584  0.995977
real potato   0.859352  0.924307  0.882155  0.970798  0.999810
fake potato   0.955363  0.977122  0.963929  0.990783  0.999966
real apple    0.670077  0.802401  0.878307  0.738655  0.998745
fake apple    0.353645  0.522469  0.983138  0.355803  0.997545
real orange   0.820956  0.901626  0.971769  0.841014  0.999758
fake orange   0.894186  0.944087  0.904221  0.987741  0.999665
real grape    0.593950  0.745206  0.790894  0.704597  0.998994
fake grape    0.887631  0.940421  0.949546  0.931568  0.999564
real lemon    0.612852  0.759911  0.686720  0.850688  0.999368
fake lemon    0.846110  0.916591  0.994348  0.850198  0.999673
real avocado  0.946455  0.972441  0.997067  0.949097  0.999950
fake avocado  0.349071  0.517460  0.994201  0.349783  0.999220
real pepper   0.896212  0.945215  0.943185  0.947355  0.999599
fake pepper   0.912770  0.954346  0.963105  0.945842  0.999785
real plant    0.836704  0.911043  0.917921  0.904366  0.998235
fake plant    0.891969  0.942850  0.930063  0.956097  0.999908
real banana   0.663363  0.797568  0.926895  0.699986  0.999202
fake banana   0.690514  0.816878  0.780092  0.857415  0.999293
real onion    0.679009  0.808773  0.697103  0.963182  0.999589
fake onion    0.948834  0.973695  0.983473  0.964208  0.999967
real unknown  0.522032  0.685921  0.533369  0.960878  0.999859
fake unknown  0.161647  0.278276  0.173157  0.708620  0.996903
total         0.738630  0.827672  0.862689  0.844664  0.999155
total(-bg)    0.726941  0.819937  0.856575  0.837667  0.999300
2026-09-23 19:36:03,717 - INFO: Epoch accounting: {'epoch': 239, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11309877, 43266, 75200, 118078, 124695, 100516, 55950, 138127, 233919, 50559, 81198, 50134, 28712, 188094, 106318, 157679, 22053, 94415, 72331, 77875, 56686, 5825, 46765], 'crops_with_class': [202, 30, 33, 31, 32, 27, 19, 30, 35, 28, 31, 16, 11, 47, 32, 26, 20, 27, 28, 32, 24, 7, 21], 'targeted_crops_by_class': [0, 6, 7, 3, 1, 8, 2, 6, 2, 6, 6, 6, 4, 2, 1, 3, 6, 4, 2, 3, 8, 2, 2], 'sampled_scene_counts': [0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 2, 2, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 2, 4, 2, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 3, 0, 2, 1, 1, 0, 3, 0, 3, 1, 0, 2, 5, 1, 0, 0, 0, 1, 0, 1, 2, 1, 2, 1, 1, 1, 1, 3, 3, 0, 1, 4, 1, 0, 1, 1, 2, 3, 0, 1, 1, 2, 1, 2, 1, 3, 1, 3, 1, 1, 2, 0, 1, 3, 2, 0, 1, 1, 1, 2, 1, 1, 2, 2, 3, 2, 2, 2, 1, 1, 0, 1, 1, 0, 0, 2, 1, 2, 1], 'learning_rate': 5.388192442570558e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000714492286992891, 'train_segmentation_loss': 0.3259680413521162, 'val_foreground_miou_all22': 0.7269410249324795, 'val_psnr_ref1': 37.74135025024414, 'elapsed_seconds': 335.26055359840393, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 240/500 | Batch 10/202 | Rec 0.000683 | Seg 0.292780 | Elapsed 0.2m | ETA 4.0m
Epoch 240/500 | Batch 20/202 | Rec 0.000848 | Seg 0.367882 | Elapsed 0.4m | ETA 3.8m
Epoch 240/500 | Batch 30/202 | Rec 0.000793 | Seg 0.360425 | Elapsed 0.6m | ETA 3.6m
Epoch 240/500 | Batch 40/202 | Rec 0.000834 | Seg 0.351516 | Elapsed 0.8m | ETA 3.4m
Epoch 240/500 | Batch 50/202 | Rec 0.000829 | Seg 0.353506 | Elapsed 1.0m | ETA 3.2m
Epoch 240/500 | Batch 60/202 | Rec 0.000825 | Seg 0.357850 | Elapsed 1.3m | ETA 3.0m
Epoch 240/500 | Batch 70/202 | Rec 0.000808 | Seg 0.350637 | Elapsed 1.5m | ETA 2.8m
Epoch 240/500 | Batch 80/202 | Rec 0.000798 | Seg 0.354234 | Elapsed 1.7m | ETA 2.6m
Epoch 240/500 | Batch 90/202 | Rec 0.000770 | Seg 0.342176 | Elapsed 1.9m | ETA 2.4m
Epoch 240/500 | Batch 100/202 | Rec 0.000773 | Seg 0.343353 | Elapsed 2.1m | ETA 2.2m
Epoch 240/500 | Batch 110/202 | Rec 0.000775 | Seg 0.351386 | Elapsed 2.3m | ETA 1.9m
Epoch 240/500 | Batch 120/202 | Rec 0.000769 | Seg 0.347910 | Elapsed 2.5m | ETA 1.7m
Epoch 240/500 | Batch 130/202 | Rec 0.000758 | Seg 0.342293 | Elapsed 2.7m | ETA 1.5m
Epoch 240/500 | Batch 140/202 | Rec 0.000757 | Seg 0.340290 | Elapsed 3.0m | ETA 1.3m
Epoch 240/500 | Batch 150/202 | Rec 0.000759 | Seg 0.345726 | Elapsed 3.2m | ETA 1.1m
Epoch 240/500 | Batch 160/202 | Rec 0.000765 | Seg 0.347790 | Elapsed 3.4m | ETA 0.9m
Epoch 240/500 | Batch 170/202 | Rec 0.000766 | Seg 0.345500 | Elapsed 3.6m | ETA 0.7m
Epoch 240/500 | Batch 180/202 | Rec 0.000757 | Seg 0.342973 | Elapsed 3.8m | ETA 0.5m
Epoch 240/500 | Batch 190/202 | Rec 0.000754 | Seg 0.344335 | Elapsed 4.0m | ETA 0.3m
Epoch 240/500 | Batch 200/202 | Rec 0.000752 | Seg 0.344206 | Elapsed 4.2m | ETA 0.0m
Epoch 240/500 | Batch 202/202 | Rec 0.000751 | Seg 0.344122 | Elapsed 4.3m | ETA 0.0m

2026-09-23 19:40:19,059 - INFO: Rec loss: 0.000750901239551258
2026-09-23 19:40:19,060 - INFO: Seg loss: 0.34412225226106324
2026-09-23 19:40:19,060 - INFO: λ_rec: 1
2026-09-23 19:40:19,060 - INFO: λ_seg: 0.0001
2026-09-23 19:41:40,252 - INFO: -------------------Epoch: 240------------------------
2026-09-23 19:41:40,256 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.833354  0.972312  0.000172
2026-09-23 19:41:40,262 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995799  0.997845  0.997123  0.998669  0.995989
real potato   0.857287  0.923110  0.983980  0.869421  0.999827
fake potato   0.946293  0.972355  0.956258  0.989108  0.999959
real apple    0.767286  0.868271  0.943916  0.803936  0.999159
fake apple    0.774485  0.872863  0.986702  0.782654  0.999140
real orange   0.451767  0.622322  0.843973  0.492937  0.999212
fake orange   0.649412  0.787399  0.656505  0.983637  0.998480
real grape    0.738392  0.849462  0.939587  0.775195  0.999427
fake grape    0.876215  0.933974  0.950002  0.918574  0.999520
real lemon    0.345555  0.513577  0.420565  0.659569  0.998532
fake lemon    0.848129  0.917775  0.977818  0.864767  0.999672
real avocado  0.899566  0.947078  0.941291  0.953038  0.999901
fake avocado  0.373279  0.543592  0.999317  0.373374  0.999250
real pepper   0.827345  0.905466  0.896683  0.914525  0.999302
fake pepper   0.567322  0.723892  0.984692  0.572371  0.998960
real plant    0.859445  0.924360  0.939843  0.909476  0.998512
fake plant    0.797336  0.887192  0.858526  0.917945  0.999814
real banana   0.371489  0.541689  0.882922  0.390737  0.998515
fake banana   0.631291  0.773927  0.716313  0.841739  0.999096
real onion    0.619978  0.765368  0.632269  0.969600  0.999463
fake onion    0.886979  0.940055  0.908804  0.973640  0.999922
real unknown  0.708333  0.829219  0.731583  0.957061  0.999937
fake unknown  0.235107  0.380668  0.261791  0.697573  0.998088
total         0.696874  0.800933  0.843933  0.809111  0.999116
total(-bg)    0.683286  0.791982  0.836970  0.800494  0.999258
2026-09-23 19:41:40,795 - INFO: Epoch accounting: {'epoch': 240, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11234965, 66220, 60900, 131726, 145100, 71902, 115162, 127881, 168653, 71884, 48274, 44881, 28735, 211506, 140221, 140053, 12755, 95286, 98866, 103511, 86297, 5090, 28404], 'crops_with_class': [202, 40, 30, 36, 33, 23, 36, 22, 32, 32, 17, 15, 12, 53, 40, 16, 11, 29, 31, 49, 38, 6, 13], 'targeted_crops_by_class': [0, 4, 4, 4, 5, 6, 9, 1, 3, 3, 1, 3, 5, 4, 6, 2, 2, 3, 8, 10, 6, 3, 2], 'sampled_scene_counts': [0, 1, 1, 1, 1, 2, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 2, 0, 1, 2, 0, 3, 0, 0, 1, 0, 3, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 2, 0, 0, 1, 3, 1, 3, 0, 1, 4, 1, 1, 1, 2, 1, 1, 1, 3, 0, 1, 2, 0, 1, 2, 0, 2, 1, 0, 0, 3, 1, 1, 2, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 1, 2, 1, 2, 4, 3, 0, 3, 2, 0, 1, 1, 0, 3, 2, 4, 2, 0, 2, 1, 1, 1, 2, 2, 1, 3, 3, 4, 1, 1, 3, 1, 1, 0, 2, 1, 3, 1, 2, 0, 2], 'learning_rate': 5.356936878250593e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000750901239551258, 'train_segmentation_loss': 0.34412225226106324, 'val_foreground_miou_all22': 0.6832860076492312, 'val_psnr_ref1': 37.83335433959961, 'elapsed_seconds': 337.0698847770691, 'peak_cuda_allocated_gib': 7.510288238525391}

Epoch 241/500 | Batch 10/202 | Rec 0.000870 | Seg 0.346497 | Elapsed 0.2m | ETA 4.1m
Epoch 241/500 | Batch 20/202 | Rec 0.000912 | Seg 0.337403 | Elapsed 0.4m | ETA 3.9m
Epoch 241/500 | Batch 30/202 | Rec 0.000877 | Seg 0.363258 | Elapsed 0.6m | ETA 3.6m
Epoch 241/500 | Batch 40/202 | Rec 0.000840 | Seg 0.345223 | Elapsed 0.9m | ETA 3.4m
Epoch 241/500 | Batch 50/202 | Rec 0.000808 | Seg 0.337104 | Elapsed 1.1m | ETA 3.2m
Epoch 241/500 | Batch 60/202 | Rec 0.000777 | Seg 0.336803 | Elapsed 1.3m | ETA 3.0m
Epoch 241/500 | Batch 70/202 | Rec 0.000780 | Seg 0.347030 | Elapsed 1.5m | ETA 2.8m
Epoch 241/500 | Batch 80/202 | Rec 0.000752 | Seg 0.336053 | Elapsed 1.7m | ETA 2.6m
Epoch 241/500 | Batch 90/202 | Rec 0.000753 | Seg 0.341176 | Elapsed 1.9m | ETA 2.4m
Epoch 241/500 | Batch 100/202 | Rec 0.000765 | Seg 0.334423 | Elapsed 2.1m | ETA 2.2m
Epoch 241/500 | Batch 110/202 | Rec 0.000767 | Seg 0.330471 | Elapsed 2.3m | ETA 1.9m
Epoch 241/500 | Batch 120/202 | Rec 0.000790 | Seg 0.344296 | Elapsed 2.5m | ETA 1.7m
Epoch 241/500 | Batch 130/202 | Rec 0.000779 | Seg 0.337623 | Elapsed 2.7m | ETA 1.5m
Epoch 241/500 | Batch 140/202 | Rec 0.000784 | Seg 0.338778 | Elapsed 3.0m | ETA 1.3m
Epoch 241/500 | Batch 150/202 | Rec 0.000783 | Seg 0.335449 | Elapsed 3.2m | ETA 1.1m
Epoch 241/500 | Batch 160/202 | Rec 0.000775 | Seg 0.331915 | Elapsed 3.4m | ETA 0.9m
Epoch 241/500 | Batch 170/202 | Rec 0.000767 | Seg 0.328103 | Elapsed 3.6m | ETA 0.7m
Epoch 241/500 | Batch 180/202 | Rec 0.000763 | Seg 0.327720 | Elapsed 3.8m | ETA 0.5m
Epoch 241/500 | Batch 190/202 | Rec 0.000759 | Seg 0.325508 | Elapsed 4.0m | ETA 0.3m
Epoch 241/500 | Batch 200/202 | Rec 0.000757 | Seg 0.326123 | Elapsed 4.2m | ETA 0.0m
Epoch 241/500 | Batch 202/202 | Rec 0.000758 | Seg 0.326867 | Elapsed 4.3m | ETA 0.0m

2026-09-23 19:45:56,347 - INFO: Rec loss: 0.0007581970278959777
2026-09-23 19:45:56,347 - INFO: Seg loss: 0.32686694349982953
2026-09-23 19:45:56,347 - INFO: λ_rec: 1
2026-09-23 19:45:56,348 - INFO: λ_seg: 0.0001
2026-09-23 19:47:17,548 - INFO: -------------------Epoch: 241------------------------
2026-09-23 19:47:17,552 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.276879  0.972947  0.000156
2026-09-23 19:47:17,559 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994779  0.997332  0.995704  0.999066  0.995008
real potato   0.921807  0.959263  0.971866  0.947080  0.999904
fake potato   0.956218  0.977569  0.980814  0.974445  0.999967
real apple    0.730216  0.844025  0.955035  0.756214  0.999036
fake apple    0.687483  0.814754  0.983707  0.695401  0.998806
real orange   0.489514  0.657234  0.930450  0.508106  0.999302
fake orange   0.706839  0.828194  0.719536  0.975642  0.998842
real grape    0.695280  0.820204  0.861742  0.782577  0.999284
fake grape    0.856715  0.922779  0.965314  0.883925  0.999453
real lemon    0.605432  0.754180  0.739277  0.769800  0.999410
fake lemon    0.829071  0.906499  0.972881  0.848684  0.999630
real avocado  0.843166  0.914861  0.883956  0.948112  0.999836
fake avocado  0.310301  0.473597  0.999179  0.310380  0.999174
real pepper   0.828264  0.906016  0.900025  0.912189  0.999308
fake pepper   0.735501  0.847546  0.974146  0.750144  0.999357
real plant    0.822714  0.902685  0.959998  0.851919  0.998164
fake plant    0.855014  0.921791  0.954994  0.890913  0.999880
real banana   0.651643  0.789036  0.950526  0.674521  0.999190
fake banana   0.671482  0.803407  0.754092  0.859738  0.999226
real onion    0.660049  0.795168  0.681456  0.954568  0.999556
fake onion    0.918290  0.957355  0.980969  0.934946  0.999948
real unknown  0.758002  0.862295  0.806478  0.926527  0.999953
fake unknown  0.204516  0.339542  0.232903  0.626585  0.997946
total         0.727491  0.825884  0.876306  0.816586  0.999138
total(-bg)    0.715342  0.818091  0.870879  0.808292  0.999326
2026-09-23 19:47:18,062 - INFO: Epoch accounting: {'epoch': 241, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11320119, 50083, 67251, 140861, 155578, 74637, 68450, 136138, 128688, 76436, 76449, 45371, 33492, 216191, 132920, 136344, 27890, 76558, 83831, 75086, 60326, 5315, 50258], 'crops_with_class': [202, 28, 31, 38, 40, 21, 24, 24, 28, 37, 31, 15, 12, 56, 31, 17, 25, 24, 30, 32, 28, 7, 21], 'targeted_crops_by_class': [0, 4, 4, 2, 8, 6, 3, 5, 3, 5, 3, 3, 4, 7, 3, 3, 4, 5, 4, 3, 4, 2, 6], 'sampled_scene_counts': [1, 1, 2, 0, 1, 1, 0, 2, 3, 3, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 3, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 2, 0, 1, 0, 1, 1, 0, 2, 2, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1, 2, 2, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 0, 3, 0, 1, 1, 2, 1, 0, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 0, 2, 4, 1, 1, 1, 1, 0, 1, 3, 1, 2, 0, 1, 1, 0, 1, 2, 0, 1, 0, 2, 1, 2, 3, 1, 2, 0, 0, 2, 2, 0, 4, 2, 1, 1, 4, 3, 2, 2, 1, 1], 'learning_rate': 5.325667716152444e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007581970278959777, 'train_segmentation_loss': 0.32686694349982953, 'val_foreground_miou_all22': 0.7153415352643155, 'val_psnr_ref1': 38.276878662109375, 'elapsed_seconds': 337.2588815689087, 'peak_cuda_allocated_gib': 7.510532379150391}

Epoch 242/500 | Batch 10/202 | Rec 0.000729 | Seg 0.315530 | Elapsed 0.2m | ETA 4.0m
Epoch 242/500 | Batch 20/202 | Rec 0.000723 | Seg 0.349802 | Elapsed 0.4m | ETA 3.9m
Epoch 242/500 | Batch 30/202 | Rec 0.000714 | Seg 0.340761 | Elapsed 0.6m | ETA 3.7m
Epoch 242/500 | Batch 40/202 | Rec 0.000693 | Seg 0.333931 | Elapsed 0.9m | ETA 3.5m
Epoch 242/500 | Batch 50/202 | Rec 0.000671 | Seg 0.320373 | Elapsed 1.1m | ETA 3.3m
Epoch 242/500 | Batch 60/202 | Rec 0.000718 | Seg 0.324086 | Elapsed 1.3m | ETA 3.0m
Epoch 242/500 | Batch 70/202 | Rec 0.000718 | Seg 0.330591 | Elapsed 1.5m | ETA 2.8m
Epoch 242/500 | Batch 80/202 | Rec 0.000702 | Seg 0.323834 | Elapsed 1.7m | ETA 2.6m
Epoch 242/500 | Batch 90/202 | Rec 0.000712 | Seg 0.323481 | Elapsed 1.9m | ETA 2.4m
Epoch 242/500 | Batch 100/202 | Rec 0.000716 | Seg 0.320729 | Elapsed 2.1m | ETA 2.2m
Epoch 242/500 | Batch 110/202 | Rec 0.000731 | Seg 0.326595 | Elapsed 2.3m | ETA 2.0m
Epoch 242/500 | Batch 120/202 | Rec 0.000727 | Seg 0.321670 | Elapsed 2.6m | ETA 1.7m
Epoch 242/500 | Batch 130/202 | Rec 0.000732 | Seg 0.326138 | Elapsed 2.8m | ETA 1.5m
Epoch 242/500 | Batch 140/202 | Rec 0.000726 | Seg 0.324773 | Elapsed 3.0m | ETA 1.3m
Epoch 242/500 | Batch 150/202 | Rec 0.000725 | Seg 0.323950 | Elapsed 3.2m | ETA 1.1m
Epoch 242/500 | Batch 160/202 | Rec 0.000718 | Seg 0.325131 | Elapsed 3.4m | ETA 0.9m
Epoch 242/500 | Batch 170/202 | Rec 0.000714 | Seg 0.324735 | Elapsed 3.6m | ETA 0.7m
Epoch 242/500 | Batch 180/202 | Rec 0.000720 | Seg 0.325787 | Elapsed 3.8m | ETA 0.5m
Epoch 242/500 | Batch 190/202 | Rec 0.000721 | Seg 0.328113 | Elapsed 4.0m | ETA 0.3m
Epoch 242/500 | Batch 200/202 | Rec 0.000719 | Seg 0.325601 | Elapsed 4.2m | ETA 0.0m
Epoch 242/500 | Batch 202/202 | Rec 0.000720 | Seg 0.325977 | Elapsed 4.3m | ETA 0.0m

2026-09-23 19:51:34,854 - INFO: Rec loss: 0.0007202254989648948
2026-09-23 19:51:34,854 - INFO: Seg loss: 0.32597693590687055
2026-09-23 19:51:34,854 - INFO: λ_rec: 1
2026-09-23 19:51:34,854 - INFO: λ_seg: 0.0001
2026-09-23 19:52:55,509 - INFO: -------------------Epoch: 242------------------------
2026-09-23 19:52:55,513 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.218203  0.972413  0.000157
2026-09-23 19:52:55,520 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995270  0.997579  0.996158  0.999105  0.995479
real potato   0.923767  0.960323  0.962711  0.958046  0.999905
fake potato   0.961891  0.980525  0.972594  0.988689  0.999971
real apple    0.727820  0.842423  0.991852  0.732198  0.999055
fake apple    0.694717  0.819813  0.982063  0.703645  0.998833
real orange   0.703448  0.825862  0.989651  0.708661  0.999606
fake orange   0.841626  0.913953  0.867666  0.965569  0.999480
real grape    0.652895  0.789952  0.867407  0.725280  0.999195
fake grape    0.881336  0.936876  0.946690  0.927360  0.999538
real lemon    0.615133  0.761662  0.822493  0.709296  0.999478
fake lemon    0.815424  0.898280  0.995787  0.818247  0.999608
real avocado  0.886232  0.939635  0.948328  0.931199  0.999889
fake avocado  0.401301  0.572714  1.000000  0.401301  0.999284
real pepper   0.842974  0.914748  0.891613  0.939221  0.999360
fake pepper   0.925085  0.961035  0.962504  0.959670  0.999815
real plant    0.829724  0.906889  0.938647  0.877304  0.998199
fake plant    0.801567  0.889806  0.860236  0.921587  0.999818
real banana   0.725955  0.841172  0.949688  0.754991  0.999360
fake banana   0.661585  0.796280  0.770250  0.824237  0.999224
real onion    0.659704  0.794917  0.673068  0.970782  0.999548
fake onion    0.939637  0.968829  0.974089  0.963724  0.999961
real unknown  0.539088  0.700482  0.555680  0.947519  0.999870
fake unknown  0.232359  0.377054  0.269240  0.629120  0.998249
total         0.750371  0.843079  0.877757  0.841598  0.999249
total(-bg)    0.739240  0.836056  0.872375  0.834438  0.999420
2026-09-23 19:52:56,025 - INFO: Epoch accounting: {'epoch': 242, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11337344, 52561, 63999, 132643, 155778, 62789, 73402, 158085, 165808, 52934, 31889, 55412, 42647, 213251, 143244, 151136, 23300, 75727, 75061, 86898, 40819, 11737, 31808], 'crops_with_class': [202, 29, 28, 33, 33, 21, 26, 28, 36, 26, 17, 15, 16, 48, 31, 25, 22, 25, 27, 39, 23, 12, 14], 'targeted_crops_by_class': [0, 7, 8, 3, 2, 2, 4, 7, 2, 3, 2, 4, 4, 4, 2, 6, 2, 3, 7, 4, 2, 4, 1], 'sampled_scene_counts': [0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 2, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 2, 1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 0, 2, 1, 0, 2, 0, 1, 1, 1, 1, 1, 4, 2, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 1, 4, 0, 0, 1, 0, 1, 4, 1, 1, 0, 0, 1, 4, 0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 0, 0, 1, 2, 0, 0, 3, 2, 3, 2, 0, 2, 2, 0, 2, 3, 1, 1, 0, 0, 1, 1, 1, 1, 3, 0, 0, 2, 0, 2, 2, 1, 3, 1, 0, 2, 2, 2, 2, 1, 2, 1, 0, 3, 0, 2, 2, 2, 0], 'learning_rate': 5.29438619072909e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007202254989648948, 'train_segmentation_loss': 0.32597693590687055, 'val_foreground_miou_all22': 0.7392395166845694, 'val_psnr_ref1': 38.218202667236326, 'elapsed_seconds': 337.9561507701874, 'peak_cuda_allocated_gib': 7.5141143798828125}

Epoch 243/500 | Batch 10/202 | Rec 0.000909 | Seg 0.358744 | Elapsed 0.2m | ETA 4.0m
Epoch 243/500 | Batch 20/202 | Rec 0.000781 | Seg 0.337848 | Elapsed 0.4m | ETA 3.9m
Epoch 243/500 | Batch 30/202 | Rec 0.000711 | Seg 0.320929 | Elapsed 0.6m | ETA 3.6m
Epoch 243/500 | Batch 40/202 | Rec 0.000716 | Seg 0.316685 | Elapsed 0.8m | ETA 3.4m
Epoch 243/500 | Batch 50/202 | Rec 0.000717 | Seg 0.318732 | Elapsed 1.1m | ETA 3.2m
Epoch 243/500 | Batch 60/202 | Rec 0.000718 | Seg 0.310900 | Elapsed 1.3m | ETA 3.0m
Epoch 243/500 | Batch 70/202 | Rec 0.000746 | Seg 0.326316 | Elapsed 1.5m | ETA 2.8m
Epoch 243/500 | Batch 80/202 | Rec 0.000741 | Seg 0.320987 | Elapsed 1.7m | ETA 2.6m
Epoch 243/500 | Batch 90/202 | Rec 0.000751 | Seg 0.331932 | Elapsed 1.9m | ETA 2.4m
Epoch 243/500 | Batch 100/202 | Rec 0.000749 | Seg 0.330093 | Elapsed 2.1m | ETA 2.1m
Epoch 243/500 | Batch 110/202 | Rec 0.000772 | Seg 0.337539 | Elapsed 2.3m | ETA 1.9m
Epoch 243/500 | Batch 120/202 | Rec 0.000764 | Seg 0.339302 | Elapsed 2.5m | ETA 1.7m
Epoch 243/500 | Batch 130/202 | Rec 0.000757 | Seg 0.335943 | Elapsed 2.7m | ETA 1.5m
Epoch 243/500 | Batch 140/202 | Rec 0.000775 | Seg 0.346700 | Elapsed 2.9m | ETA 1.3m
Epoch 243/500 | Batch 150/202 | Rec 0.000773 | Seg 0.346690 | Elapsed 3.1m | ETA 1.1m
Epoch 243/500 | Batch 160/202 | Rec 0.000767 | Seg 0.341757 | Elapsed 3.3m | ETA 0.9m
Epoch 243/500 | Batch 170/202 | Rec 0.000757 | Seg 0.337559 | Elapsed 3.6m | ETA 0.7m
Epoch 243/500 | Batch 180/202 | Rec 0.000758 | Seg 0.336359 | Elapsed 3.8m | ETA 0.5m
Epoch 243/500 | Batch 190/202 | Rec 0.000756 | Seg 0.333647 | Elapsed 4.0m | ETA 0.3m
Epoch 243/500 | Batch 200/202 | Rec 0.000766 | Seg 0.339970 | Elapsed 4.2m | ETA 0.0m
Epoch 243/500 | Batch 202/202 | Rec 0.000763 | Seg 0.338656 | Elapsed 4.2m | ETA 0.0m

2026-09-23 19:57:09,251 - INFO: Rec loss: 0.0007632709822777686
2026-09-23 19:57:09,252 - INFO: Seg loss: 0.3386564154804933
2026-09-23 19:57:09,252 - INFO: λ_rec: 1
2026-09-23 19:57:09,252 - INFO: λ_seg: 0.0001
2026-09-23 19:58:29,984 - INFO: -------------------Epoch: 243------------------------
2026-09-23 19:58:29,989 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.274796  0.972717  0.000155
2026-09-23 19:58:29,997 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995570  0.997730  0.996818  0.998743  0.995769
real potato   0.767389  0.868338  0.991650  0.772379  0.999720
fake potato   0.948546  0.973544  0.970252  0.976959  0.999961
real apple    0.771780  0.871142  0.921718  0.825918  0.999157
fake apple    0.635464  0.777058  0.986200  0.641166  0.998611
real orange   0.726599  0.841604  0.979256  0.737957  0.999634
fake orange   0.852270  0.920194  0.875740  0.969513  0.999519
real grape    0.715214  0.833915  0.906773  0.771980  0.999358
fake grape    0.874583  0.933046  0.925430  0.940890  0.999501
real lemon    0.493552  0.660861  0.587516  0.755258  0.999089
fake lemon    0.823377  0.903085  0.994536  0.827119  0.999625
real avocado  0.778751  0.875566  0.824109  0.933990  0.999753
fake avocado  0.810612  0.895351  0.994394  0.814333  0.999772
real pepper   0.843570  0.915098  0.915855  0.914442  0.999380
fake pepper   0.817739  0.899682  0.955796  0.849882  0.999548
real plant    0.858465  0.923793  0.929319  0.918431  0.998485
fake plant    0.874404  0.932944  0.952467  0.914302  0.999895
real banana   0.547296  0.707376  0.945884  0.564987  0.998950
fake banana   0.621449  0.766486  0.693672  0.856503  0.999040
real onion    0.661725  0.796383  0.685686  0.949840  0.999561
fake onion    0.941852  0.970006  0.968652  0.971463  0.999962
real unknown  0.910018  0.952840  0.970326  0.936069  0.999985
fake unknown  0.258973  0.411361  0.298344  0.662441  0.998403
total         0.762139  0.853365  0.881322  0.848025  0.999247
total(-bg)    0.751529  0.846803  0.876072  0.841174  0.999405
2026-09-23 19:58:30,532 - INFO: Epoch accounting: {'epoch': 243, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11213023, 47054, 45134, 96545, 130045, 77298, 72698, 189735, 255612, 92701, 54818, 44576, 37097, 228273, 129313, 191007, 30851, 63742, 65644, 65142, 47016, 8628, 52320], 'crops_with_class': [202, 28, 21, 25, 39, 26, 27, 35, 41, 39, 30, 16, 13, 55, 32, 19, 25, 21, 26, 30, 21, 10, 24], 'targeted_crops_by_class': [0, 6, 2, 3, 6, 6, 6, 7, 5, 5, 3, 5, 3, 9, 5, 9, 5, 3, 5, 2, 4, 5, 8], 'sampled_scene_counts': [0, 0, 2, 0, 1, 0, 2, 0, 3, 2, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 0, 2, 2, 1, 0, 2, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 6, 3, 2, 2, 4, 0, 3, 0, 2, 1, 0, 3, 1, 2, 1, 2, 1, 1, 1, 1, 3, 0, 1, 0, 1, 2, 2, 1, 0, 1, 2, 2, 1, 2, 2, 2, 3, 0, 1, 3, 1, 1, 0, 2, 2, 2, 1, 0, 2, 1, 1, 1, 3, 1, 3, 1, 1, 2, 2, 2, 2, 0, 1, 0, 1, 1, 1, 0, 0, 2, 3, 1, 0, 0, 0, 0, 0, 1, 3, 1, 0, 2], 'learning_rate': 5.2630935369215936e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007632709822777686, 'train_segmentation_loss': 0.3386564154804933, 'val_foreground_miou_all22': 0.7515286662115332, 'val_psnr_ref1': 38.27479629516601, 'elapsed_seconds': 334.4990656375885, 'peak_cuda_allocated_gib': 7.512760162353516}

Epoch 244/500 | Batch 10/202 | Rec 0.000678 | Seg 0.289617 | Elapsed 0.2m | ETA 4.2m
Epoch 244/500 | Batch 20/202 | Rec 0.000714 | Seg 0.335473 | Elapsed 0.4m | ETA 3.9m
Epoch 244/500 | Batch 30/202 | Rec 0.000707 | Seg 0.327840 | Elapsed 0.6m | ETA 3.7m
Epoch 244/500 | Batch 40/202 | Rec 0.000718 | Seg 0.323310 | Elapsed 0.8m | ETA 3.4m
Epoch 244/500 | Batch 50/202 | Rec 0.000699 | Seg 0.318242 | Elapsed 1.1m | ETA 3.2m
Epoch 244/500 | Batch 60/202 | Rec 0.000724 | Seg 0.321168 | Elapsed 1.3m | ETA 3.0m
Epoch 244/500 | Batch 70/202 | Rec 0.000723 | Seg 0.326417 | Elapsed 1.5m | ETA 2.8m
Epoch 244/500 | Batch 80/202 | Rec 0.000734 | Seg 0.320701 | Elapsed 1.7m | ETA 2.6m
Epoch 244/500 | Batch 90/202 | Rec 0.000766 | Seg 0.328877 | Elapsed 1.9m | ETA 2.4m
Epoch 244/500 | Batch 100/202 | Rec 0.000776 | Seg 0.345160 | Elapsed 2.1m | ETA 2.1m
Epoch 244/500 | Batch 110/202 | Rec 0.000765 | Seg 0.337854 | Elapsed 2.3m | ETA 1.9m
Epoch 244/500 | Batch 120/202 | Rec 0.000748 | Seg 0.333834 | Elapsed 2.5m | ETA 1.7m
Epoch 244/500 | Batch 130/202 | Rec 0.000739 | Seg 0.330321 | Elapsed 2.7m | ETA 1.5m
Epoch 244/500 | Batch 140/202 | Rec 0.000733 | Seg 0.329450 | Elapsed 2.9m | ETA 1.3m
Epoch 244/500 | Batch 150/202 | Rec 0.000723 | Seg 0.324003 | Elapsed 3.2m | ETA 1.1m
Epoch 244/500 | Batch 160/202 | Rec 0.000721 | Seg 0.325089 | Elapsed 3.4m | ETA 0.9m
Epoch 244/500 | Batch 170/202 | Rec 0.000723 | Seg 0.326390 | Elapsed 3.6m | ETA 0.7m
Epoch 244/500 | Batch 180/202 | Rec 0.000726 | Seg 0.328921 | Elapsed 3.8m | ETA 0.5m
Epoch 244/500 | Batch 190/202 | Rec 0.000726 | Seg 0.331500 | Elapsed 4.0m | ETA 0.3m
Epoch 244/500 | Batch 200/202 | Rec 0.000724 | Seg 0.327785 | Elapsed 4.2m | ETA 0.0m
Epoch 244/500 | Batch 202/202 | Rec 0.000724 | Seg 0.328065 | Elapsed 4.2m | ETA 0.0m

2026-09-23 20:02:44,957 - INFO: Rec loss: 0.0007237583370867766
2026-09-23 20:02:44,957 - INFO: Seg loss: 0.3280650869122531
2026-09-23 20:02:44,957 - INFO: λ_rec: 1
2026-09-23 20:02:44,957 - INFO: λ_seg: 0.0001
2026-09-23 20:04:06,504 - INFO: -------------------Epoch: 244------------------------
2026-09-23 20:04:06,508 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.60312  0.973349  0.000144
2026-09-23 20:04:06,514 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995796  0.997844  0.997194  0.998595  0.995987
real potato   0.875000  0.933283  0.936569  0.930120  0.999841
fake potato   0.945297  0.971829  0.962986  0.980938  0.999959
real apple    0.735219  0.847359  0.972666  0.750730  0.999067
fake apple    0.670306  0.802567  0.990098  0.674830  0.998747
real orange   0.776211  0.873958  0.977377  0.790412  0.999700
fake orange   0.880504  0.936405  0.899705  0.976335  0.999621
real grape    0.679895  0.809399  0.850032  0.772564  0.999241
fake grape    0.891473  0.942573  0.957649  0.928062  0.999582
real lemon    0.495217  0.662353  0.583317  0.766294  0.999082
fake lemon    0.847674  0.917509  0.996114  0.850487  0.999677
real avocado  0.865453  0.927824  0.897743  0.960099  0.999861
fake avocado  0.431485  0.602807  0.999114  0.431650  0.999319
real pepper   0.863124  0.926484  0.935719  0.917529  0.999468
fake pepper   0.889433  0.941431  0.991781  0.896037  0.999734
real plant    0.860397  0.924911  0.918924  0.931078  0.998489
fake plant    0.716333  0.834675  0.751150  0.939225  0.999704
real banana   0.577479  0.732107  0.934613  0.601793  0.999011
fake banana   0.721376  0.838089  0.821002  0.856005  0.999392
real onion    0.623256  0.767861  0.637285  0.965884  0.999473
fake onion    0.948021  0.973267  0.985378  0.961548  0.999967
real unknown  0.661745  0.796397  0.690476  0.940840  0.999923
fake unknown  0.245170  0.393756  0.262209  0.790474  0.997949
total         0.747646  0.841508  0.867352  0.852675  0.999252
total(-bg)    0.736367  0.834402  0.861450  0.846042  0.999400
2026-09-23 20:04:07,202 - INFO: Epoch accounting: {'epoch': 244, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11340824, 52218, 55023, 118069, 155857, 87366, 107079, 90226, 179181, 82412, 49360, 35840, 39792, 190352, 97060, 138345, 24038, 103435, 96943, 72455, 53150, 10692, 58555], 'crops_with_class': [202, 29, 32, 35, 39, 25, 33, 20, 37, 34, 21, 16, 18, 51, 30, 22, 22, 31, 37, 37, 23, 11, 29], 'targeted_crops_by_class': [0, 9, 5, 3, 7, 4, 3, 3, 7, 4, 2, 4, 7, 2, 5, 6, 3, 4, 3, 4, 4, 4, 7], 'sampled_scene_counts': [1, 2, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 2, 3, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 2, 1, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 0, 1, 2, 2, 1, 0, 0, 2, 4, 0, 0, 1, 2, 1, 0, 2, 1, 2, 2, 1, 4, 1, 1, 1, 1, 0, 3, 1, 0, 5, 1, 1, 2, 1, 0, 0, 0, 1, 3, 0, 3, 3, 1, 3, 1, 1, 3, 2, 2, 3, 2, 1, 2, 4, 0, 2, 1, 0, 3, 1, 1, 1, 0, 0, 2, 1, 3, 1, 0, 0, 1, 4, 1, 1, 2, 1, 0, 2, 3, 4, 4, 0, 0, 2, 0, 0, 1, 2, 2], 'learning_rate': 5.231790990110343e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007237583370867766, 'train_segmentation_loss': 0.3280650869122531, 'val_foreground_miou_all22': 0.7363667320637123, 'val_psnr_ref1': 38.60311950683594, 'elapsed_seconds': 336.6628363132477, 'peak_cuda_allocated_gib': 7.506656646728516}

Epoch 245/500 | Batch 10/202 | Rec 0.000784 | Seg 0.328557 | Elapsed 0.2m | ETA 4.2m
Epoch 245/500 | Batch 20/202 | Rec 0.000781 | Seg 0.344326 | Elapsed 0.4m | ETA 3.9m
Epoch 245/500 | Batch 30/202 | Rec 0.000786 | Seg 0.350135 | Elapsed 0.6m | ETA 3.6m
Epoch 245/500 | Batch 40/202 | Rec 0.000764 | Seg 0.352495 | Elapsed 0.8m | ETA 3.4m
Epoch 245/500 | Batch 50/202 | Rec 0.000751 | Seg 0.341200 | Elapsed 1.1m | ETA 3.2m
Epoch 245/500 | Batch 60/202 | Rec 0.000738 | Seg 0.334980 | Elapsed 1.3m | ETA 3.0m
Epoch 245/500 | Batch 70/202 | Rec 0.000751 | Seg 0.343665 | Elapsed 1.5m | ETA 2.8m
Epoch 245/500 | Batch 80/202 | Rec 0.000743 | Seg 0.348836 | Elapsed 1.7m | ETA 2.6m
Epoch 245/500 | Batch 90/202 | Rec 0.000733 | Seg 0.342264 | Elapsed 1.9m | ETA 2.4m
Epoch 245/500 | Batch 100/202 | Rec 0.000736 | Seg 0.342487 | Elapsed 2.1m | ETA 2.2m
Epoch 245/500 | Batch 110/202 | Rec 0.000767 | Seg 0.350865 | Elapsed 2.3m | ETA 1.9m
Epoch 245/500 | Batch 120/202 | Rec 0.000767 | Seg 0.349390 | Elapsed 2.5m | ETA 1.7m
Epoch 245/500 | Batch 130/202 | Rec 0.000761 | Seg 0.349260 | Elapsed 2.7m | ETA 1.5m
Epoch 245/500 | Batch 140/202 | Rec 0.000755 | Seg 0.348809 | Elapsed 2.9m | ETA 1.3m
Epoch 245/500 | Batch 150/202 | Rec 0.000768 | Seg 0.347596 | Elapsed 3.2m | ETA 1.1m
Epoch 245/500 | Batch 160/202 | Rec 0.000768 | Seg 0.341594 | Elapsed 3.4m | ETA 0.9m
Epoch 245/500 | Batch 170/202 | Rec 0.000757 | Seg 0.336235 | Elapsed 3.6m | ETA 0.7m
Epoch 245/500 | Batch 180/202 | Rec 0.000754 | Seg 0.335575 | Elapsed 3.8m | ETA 0.5m
Epoch 245/500 | Batch 190/202 | Rec 0.000744 | Seg 0.333720 | Elapsed 4.0m | ETA 0.3m
Epoch 245/500 | Batch 200/202 | Rec 0.000744 | Seg 0.332382 | Elapsed 4.2m | ETA 0.0m
Epoch 245/500 | Batch 202/202 | Rec 0.000744 | Seg 0.332330 | Elapsed 4.2m | ETA 0.0m

2026-09-23 20:08:21,428 - INFO: Rec loss: 0.0007435286018218255
2026-09-23 20:08:21,428 - INFO: Seg loss: 0.3323298637745994
2026-09-23 20:08:21,428 - INFO: λ_rec: 1
2026-09-23 20:08:21,428 - INFO: λ_seg: 0.0001
2026-09-23 20:09:41,524 - INFO: -------------------Epoch: 245------------------------
2026-09-23 20:09:41,528 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.219764  0.972731  0.000157
2026-09-23 20:09:41,535 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994936  0.997412  0.995896  0.999032  0.995159
real potato   0.266191  0.420426  0.999043  0.266259  0.999122
fake potato   0.655381  0.791771  0.996505  0.656891  0.999748
real apple    0.660187  0.795267  0.760347  0.833658  0.998520
fake apple    0.903418  0.949209  0.936419  0.962456  0.999612
real orange   0.530452  0.693151  0.996310  0.531496  0.999380
fake orange   0.795438  0.886016  0.820739  0.962691  0.999291
real grape    0.604072  0.753124  0.863392  0.667909  0.999086
fake grape    0.844910  0.915886  0.903031  0.929217  0.999369
real lemon    0.403615  0.575064  0.426114  0.884316  0.998464
fake lemon    0.841484  0.913870  0.996678  0.843851  0.999664
real avocado  0.775142  0.873280  0.812376  0.944171  0.999745
fake avocado  0.690225  0.816677  0.995417  0.692425  0.999628
real pepper   0.814205  0.897538  0.892352  0.902887  0.999246
fake pepper   0.745630  0.854233  0.995486  0.748160  0.999392
real plant    0.816329  0.898828  0.925941  0.873352  0.998035
fake plant    0.871804  0.931462  0.970301  0.895706  0.999895
real banana   0.193225  0.323842  0.959211  0.194825  0.998172
fake banana   0.694782  0.819857  0.834048  0.806238  0.999348
real onion    0.656380  0.792498  0.741324  0.851376  0.999597
fake onion    0.928382  0.962811  0.996893  0.931076  0.999955
real unknown  0.894084  0.944031  1.000000  0.894084  0.999983
fake unknown  0.401105  0.572507  0.479745  0.709888  0.999107
total         0.694842  0.799076  0.882503  0.781824  0.999110
total(-bg)    0.681202  0.790061  0.877349  0.771951  0.999289
2026-09-23 20:09:42,042 - INFO: Epoch accounting: {'epoch': 245, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11270802, 47834, 56398, 146191, 133321, 56638, 76124, 144741, 176241, 71922, 66225, 41640, 47364, 235049, 115826, 166572, 34935, 83616, 69202, 87166, 68726, 7874, 33865], 'crops_with_class': [202, 30, 24, 38, 33, 18, 28, 26, 32, 34, 31, 15, 18, 56, 28, 25, 26, 25, 29, 39, 28, 9, 16], 'targeted_crops_by_class': [0, 5, 3, 3, 5, 5, 8, 1, 3, 5, 4, 5, 8, 6, 3, 7, 4, 2, 8, 5, 7, 2, 4], 'sampled_scene_counts': [1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 1, 1, 0, 1, 1, 2, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 3, 0, 1, 1, 4, 2, 1, 2, 1, 3, 1, 2, 2, 1, 1, 0, 2, 0, 1, 2, 0, 1, 2, 2, 3, 3, 1, 1, 2, 1, 1, 2, 2, 0, 2, 1, 0, 1, 2, 3, 1, 2, 2, 0, 3, 0, 2, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 2, 0, 4, 0, 2, 0, 0, 4, 1, 0, 2, 1, 1, 0, 0, 4, 1, 0, 0, 1, 1, 3, 1, 2, 1], 'learning_rate': 5.2004797860662906e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007435286018218255, 'train_segmentation_loss': 0.3323298637745994, 'val_foreground_miou_all22': 0.6812018240824147, 'val_psnr_ref1': 38.21976379394531, 'elapsed_seconds': 334.8327577114105, 'peak_cuda_allocated_gib': 7.5083770751953125}

Epoch 246/500 | Batch 10/202 | Rec 0.000739 | Seg 0.379366 | Elapsed 0.2m | ETA 4.1m
Epoch 246/500 | Batch 20/202 | Rec 0.000696 | Seg 0.329818 | Elapsed 0.4m | ETA 3.9m
Epoch 246/500 | Batch 30/202 | Rec 0.000670 | Seg 0.320259 | Elapsed 0.6m | ETA 3.7m
Epoch 246/500 | Batch 40/202 | Rec 0.000691 | Seg 0.317119 | Elapsed 0.8m | ETA 3.4m
Epoch 246/500 | Batch 50/202 | Rec 0.000744 | Seg 0.334040 | Elapsed 1.1m | ETA 3.2m
Epoch 246/500 | Batch 60/202 | Rec 0.000749 | Seg 0.336533 | Elapsed 1.3m | ETA 3.0m
Epoch 246/500 | Batch 70/202 | Rec 0.000747 | Seg 0.340349 | Elapsed 1.5m | ETA 2.8m
Epoch 246/500 | Batch 80/202 | Rec 0.000737 | Seg 0.341692 | Elapsed 1.7m | ETA 2.6m
Epoch 246/500 | Batch 90/202 | Rec 0.000744 | Seg 0.343059 | Elapsed 1.9m | ETA 2.3m
Epoch 246/500 | Batch 100/202 | Rec 0.000739 | Seg 0.344558 | Elapsed 2.1m | ETA 2.1m
Epoch 246/500 | Batch 110/202 | Rec 0.000747 | Seg 0.341601 | Elapsed 2.3m | ETA 1.9m
Epoch 246/500 | Batch 120/202 | Rec 0.000756 | Seg 0.338334 | Elapsed 2.5m | ETA 1.7m
Epoch 246/500 | Batch 130/202 | Rec 0.000745 | Seg 0.333030 | Elapsed 2.7m | ETA 1.5m
Epoch 246/500 | Batch 140/202 | Rec 0.000737 | Seg 0.329791 | Elapsed 2.9m | ETA 1.3m
Epoch 246/500 | Batch 150/202 | Rec 0.000736 | Seg 0.332826 | Elapsed 3.1m | ETA 1.1m
Epoch 246/500 | Batch 160/202 | Rec 0.000736 | Seg 0.331383 | Elapsed 3.4m | ETA 0.9m
Epoch 246/500 | Batch 170/202 | Rec 0.000723 | Seg 0.325514 | Elapsed 3.6m | ETA 0.7m
Epoch 246/500 | Batch 180/202 | Rec 0.000721 | Seg 0.325605 | Elapsed 3.8m | ETA 0.5m
Epoch 246/500 | Batch 190/202 | Rec 0.000719 | Seg 0.323752 | Elapsed 4.0m | ETA 0.3m
Epoch 246/500 | Batch 200/202 | Rec 0.000719 | Seg 0.322751 | Elapsed 4.2m | ETA 0.0m
Epoch 246/500 | Batch 202/202 | Rec 0.000717 | Seg 0.322009 | Elapsed 4.2m | ETA 0.0m

2026-09-23 20:13:56,857 - INFO: Rec loss: 0.0007166143900531547
2026-09-23 20:13:56,857 - INFO: Seg loss: 0.3220088246951599
2026-09-23 20:13:56,857 - INFO: λ_rec: 1
2026-09-23 20:13:56,857 - INFO: λ_seg: 0.0001
2026-09-23 20:15:20,378 - INFO: -------------------Epoch: 246------------------------
2026-09-23 20:15:20,381 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.279244  0.972855  0.000155
2026-09-23 20:15:20,387 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995317  0.997603  0.996718  0.998590  0.995527
real potato   0.890314  0.941925  0.912000  0.973986  0.999856
fake potato   0.947527  0.973007  0.959292  0.987222  0.999960
real apple    0.657878  0.793591  0.995198  0.659973  0.998816
fake apple    0.639939  0.780395  0.990733  0.643792  0.998632
real orange   0.773810  0.872434  0.997616  0.775243  0.999701
fake orange   0.876575  0.934179  0.899862  0.971325  0.999608
real grape    0.669050  0.801664  0.867262  0.745377  0.999230
fake grape    0.880295  0.936287  0.943653  0.929134  0.999533
real lemon    0.544442  0.704985  0.813795  0.621916  0.999388
fake lemon    0.807678  0.893559  0.998397  0.808727  0.999593
real avocado  0.939404  0.968705  0.991575  0.946962  0.999943
fake avocado  0.543797  0.704447  0.999766  0.543866  0.999454
real pepper   0.853749  0.921055  0.892239  0.951902  0.999404
fake pepper   0.907648  0.951539  0.947512  0.955701  0.999768
real plant    0.853032  0.920638  0.930742  0.910849  0.998430
fake plant    0.884608  0.938722  0.944326  0.933282  0.999903
real banana   0.762257  0.865042  0.907221  0.826701  0.999421
fake banana   0.623776  0.768253  0.700629  0.850448  0.999056
real onion    0.576200  0.731079  0.585510  0.973146  0.999353
fake onion    0.933271  0.965434  0.970437  0.960580  0.999957
real unknown  0.436994  0.608161  0.452681  0.926527  0.999809
fake unknown  0.222383  0.363811  0.254095  0.640529  0.998113
total         0.748693  0.840718  0.867446  0.849382  0.999237
total(-bg)    0.737483  0.833587  0.861570  0.842600  0.999406
2026-09-23 20:15:20,922 - INFO: Epoch accounting: {'epoch': 246, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11315368, 65376, 68320, 118215, 170401, 88974, 77886, 158574, 157762, 64032, 58752, 20184, 25730, 225578, 135757, 135158, 16723, 85562, 49596, 90885, 48440, 12678, 48321], 'crops_with_class': [202, 37, 29, 31, 38, 29, 29, 31, 32, 28, 29, 7, 11, 58, 40, 24, 18, 25, 24, 35, 23, 17, 21], 'targeted_crops_by_class': [0, 8, 5, 6, 5, 6, 7, 5, 3, 4, 2, 2, 2, 4, 2, 4, 3, 5, 1, 4, 8, 8, 3], 'sampled_scene_counts': [1, 2, 2, 1, 2, 1, 1, 0, 1, 2, 0, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 2, 2, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 3, 0, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 0, 0, 1, 3, 2, 1, 0, 0, 2, 1, 0, 4, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1, 2, 0, 0, 3, 5, 3, 3, 1, 3, 0, 1, 1, 2, 1, 1, 2, 4, 2, 3, 0, 2, 1, 0, 0, 1, 0, 6, 1, 0, 1, 0, 2, 0, 1, 0, 3, 3, 1, 1, 1, 4, 3, 1, 0, 1, 1], 'learning_rate': 5.169161160902157e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007166143900531547, 'train_segmentation_loss': 0.3220088246951599, 'val_foreground_miou_all22': 0.7374830454564134, 'val_psnr_ref1': 38.27924362182617, 'elapsed_seconds': 338.87269377708435, 'peak_cuda_allocated_gib': 7.5111541748046875}

Epoch 247/500 | Batch 10/202 | Rec 0.000848 | Seg 0.386618 | Elapsed 0.2m | ETA 3.9m
Epoch 247/500 | Batch 20/202 | Rec 0.000769 | Seg 0.353943 | Elapsed 0.4m | ETA 3.7m
Epoch 247/500 | Batch 30/202 | Rec 0.000768 | Seg 0.372925 | Elapsed 0.6m | ETA 3.6m
Epoch 247/500 | Batch 40/202 | Rec 0.000753 | Seg 0.375634 | Elapsed 0.8m | ETA 3.4m
Epoch 247/500 | Batch 50/202 | Rec 0.000739 | Seg 0.356359 | Elapsed 1.0m | ETA 3.1m
Epoch 247/500 | Batch 60/202 | Rec 0.000728 | Seg 0.364813 | Elapsed 1.2m | ETA 2.9m
Epoch 247/500 | Batch 70/202 | Rec 0.000724 | Seg 0.365265 | Elapsed 1.4m | ETA 2.7m
Epoch 247/500 | Batch 80/202 | Rec 0.000732 | Seg 0.365037 | Elapsed 1.7m | ETA 2.5m
Epoch 247/500 | Batch 90/202 | Rec 0.000727 | Seg 0.358174 | Elapsed 1.9m | ETA 2.3m
Epoch 247/500 | Batch 100/202 | Rec 0.000716 | Seg 0.351811 | Elapsed 2.1m | ETA 2.1m
Epoch 247/500 | Batch 110/202 | Rec 0.000714 | Seg 0.345080 | Elapsed 2.3m | ETA 1.9m
Epoch 247/500 | Batch 120/202 | Rec 0.000738 | Seg 0.341132 | Elapsed 2.5m | ETA 1.7m
Epoch 247/500 | Batch 130/202 | Rec 0.000734 | Seg 0.339675 | Elapsed 2.7m | ETA 1.5m
Epoch 247/500 | Batch 140/202 | Rec 0.000735 | Seg 0.341355 | Elapsed 2.9m | ETA 1.3m
Epoch 247/500 | Batch 150/202 | Rec 0.000734 | Seg 0.338361 | Elapsed 3.1m | ETA 1.1m
Epoch 247/500 | Batch 160/202 | Rec 0.000737 | Seg 0.333374 | Elapsed 3.3m | ETA 0.9m
Epoch 247/500 | Batch 170/202 | Rec 0.000739 | Seg 0.338469 | Elapsed 3.5m | ETA 0.7m
Epoch 247/500 | Batch 180/202 | Rec 0.000731 | Seg 0.335999 | Elapsed 3.8m | ETA 0.5m
Epoch 247/500 | Batch 190/202 | Rec 0.000728 | Seg 0.334176 | Elapsed 4.0m | ETA 0.3m
Epoch 247/500 | Batch 200/202 | Rec 0.000731 | Seg 0.335329 | Elapsed 4.2m | ETA 0.0m
Epoch 247/500 | Batch 202/202 | Rec 0.000731 | Seg 0.335158 | Elapsed 4.2m | ETA 0.0m

2026-09-23 20:19:34,373 - INFO: Rec loss: 0.000730867137282967
2026-09-23 20:19:34,373 - INFO: Seg loss: 0.3351584249867661
2026-09-23 20:19:34,373 - INFO: λ_rec: 1
2026-09-23 20:19:34,373 - INFO: λ_seg: 0.0001
2026-09-23 20:20:53,430 - INFO: -------------------Epoch: 247------------------------
2026-09-23 20:20:53,434 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.667038  0.971697  0.000177
2026-09-23 20:20:53,441 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995663  0.997777  0.996895  0.998760  0.995859
real potato   0.768397  0.868983  0.970283  0.786917  0.999716
fake potato   0.959221  0.979136  0.977857  0.980519  0.999970
real apple    0.701277  0.824363  0.910681  0.753074  0.998893
fake apple    0.714212  0.833234  0.978736  0.725469  0.998904
real orange   0.780183  0.876471  0.999555  0.780454  0.999710
fake orange   0.881279  0.936843  0.899745  0.977241  0.999623
real grape    0.684763  0.812840  0.902731  0.739312  0.999289
fake grape    0.890345  0.941942  0.957049  0.927402  0.999577
real lemon    0.404155  0.575607  0.479547  0.719943  0.998753
fake lemon    0.844002  0.915353  0.999402  0.844428  0.999670
real avocado  0.919222  0.957861  0.946323  0.969787  0.999921
fake avocado  0.083780  0.154592  1.000000  0.083780  0.998904
real pepper   0.816155  0.898722  0.859290  0.942057  0.999224
fake pepper   0.802599  0.890442  0.976622  0.818321  0.999520
real plant    0.865094  0.927618  0.919787  0.935685  0.998540
fake plant    0.848815  0.918176  0.909844  0.926764  0.999869
real banana   0.414320  0.585850  0.940003  0.425574  0.998648
fake banana   0.703999  0.826241  0.841313  0.811795  0.999372
real onion    0.652254  0.789484  0.670242  0.960480  0.999537
fake onion    0.936672  0.967251  0.995394  0.940750  0.999960
real unknown  0.583043  0.736563  0.598331  0.958015  0.999890
fake unknown  0.216631  0.356081  0.229889  0.789750  0.997594
total         0.715917  0.807453  0.867805  0.817229  0.999171
total(-bg)    0.703201  0.798802  0.861937  0.808978  0.999322
2026-09-23 20:20:53,948 - INFO: Epoch accounting: {'epoch': 247, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11214860, 62434, 66197, 137871, 173585, 101755, 76999, 137192, 208490, 69647, 58074, 34906, 28499, 225865, 122191, 106895, 15564, 111879, 71346, 81041, 67797, 20041, 45144], 'crops_with_class': [202, 37, 27, 40, 40, 34, 27, 24, 40, 28, 27, 10, 12, 54, 31, 13, 16, 33, 32, 40, 30, 21, 21], 'targeted_crops_by_class': [0, 9, 2, 5, 6, 4, 5, 3, 5, 6, 1, 4, 4, 5, 4, 3, 2, 10, 5, 7, 5, 10, 1], 'sampled_scene_counts': [0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 2, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 3, 1, 1, 0, 1, 1, 3, 0, 2, 0, 1, 1, 0, 3, 1, 0, 0, 3, 2, 5, 1, 1, 2, 0, 0, 1, 0, 1, 1, 0, 0, 4, 5, 1, 1, 1, 2, 1, 0, 1, 1, 2, 0, 1, 0, 3, 3, 5, 0, 1, 1, 0, 1, 2, 1, 3, 3, 3, 2, 1, 3, 3, 1, 1, 3, 1, 0, 3, 2, 1, 3, 1, 1, 2, 2, 1, 1, 2, 1, 1, 0, 1, 2, 2, 1, 1, 3, 0], 'learning_rate': 5.137836351023638e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000730867137282967, 'train_segmentation_loss': 0.3351584249867661, 'val_foreground_miou_all22': 0.7032007490317691, 'val_psnr_ref1': 37.667038421630856, 'elapsed_seconds': 333.01788783073425, 'peak_cuda_allocated_gib': 7.511173248291016}

Epoch 248/500 | Batch 10/202 | Rec 0.000942 | Seg 0.411966 | Elapsed 0.2m | ETA 4.1m
Epoch 248/500 | Batch 20/202 | Rec 0.000836 | Seg 0.398956 | Elapsed 0.4m | ETA 3.9m
Epoch 248/500 | Batch 30/202 | Rec 0.000768 | Seg 0.358753 | Elapsed 0.6m | ETA 3.7m
Epoch 248/500 | Batch 40/202 | Rec 0.000706 | Seg 0.333107 | Elapsed 0.9m | ETA 3.5m
Epoch 248/500 | Batch 50/202 | Rec 0.000700 | Seg 0.323159 | Elapsed 1.1m | ETA 3.2m
Epoch 248/500 | Batch 60/202 | Rec 0.000735 | Seg 0.324399 | Elapsed 1.3m | ETA 3.0m
Epoch 248/500 | Batch 70/202 | Rec 0.000738 | Seg 0.320990 | Elapsed 1.5m | ETA 2.8m
Epoch 248/500 | Batch 80/202 | Rec 0.000728 | Seg 0.326038 | Elapsed 1.7m | ETA 2.6m
Epoch 248/500 | Batch 90/202 | Rec 0.000727 | Seg 0.333881 | Elapsed 1.9m | ETA 2.4m
Epoch 248/500 | Batch 100/202 | Rec 0.000721 | Seg 0.327095 | Elapsed 2.1m | ETA 2.2m
Epoch 248/500 | Batch 110/202 | Rec 0.000725 | Seg 0.325887 | Elapsed 2.3m | ETA 2.0m
Epoch 248/500 | Batch 120/202 | Rec 0.000727 | Seg 0.327117 | Elapsed 2.6m | ETA 1.7m
Epoch 248/500 | Batch 130/202 | Rec 0.000731 | Seg 0.326696 | Elapsed 2.8m | ETA 1.5m
Epoch 248/500 | Batch 140/202 | Rec 0.000730 | Seg 0.326418 | Elapsed 3.0m | ETA 1.3m
Epoch 248/500 | Batch 150/202 | Rec 0.000729 | Seg 0.326690 | Elapsed 3.2m | ETA 1.1m
Epoch 248/500 | Batch 160/202 | Rec 0.000725 | Seg 0.325534 | Elapsed 3.4m | ETA 0.9m
Epoch 248/500 | Batch 170/202 | Rec 0.000717 | Seg 0.324487 | Elapsed 3.6m | ETA 0.7m
Epoch 248/500 | Batch 180/202 | Rec 0.000714 | Seg 0.323027 | Elapsed 3.8m | ETA 0.5m
Epoch 248/500 | Batch 190/202 | Rec 0.000717 | Seg 0.328127 | Elapsed 4.0m | ETA 0.3m
Epoch 248/500 | Batch 200/202 | Rec 0.000715 | Seg 0.325326 | Elapsed 4.2m | ETA 0.0m
Epoch 248/500 | Batch 202/202 | Rec 0.000715 | Seg 0.324627 | Elapsed 4.3m | ETA 0.0m

2026-09-23 20:25:10,763 - INFO: Rec loss: 0.0007145939545249474
2026-09-23 20:25:10,763 - INFO: Seg loss: 0.3246269313120606
2026-09-23 20:25:10,763 - INFO: λ_rec: 1
2026-09-23 20:25:10,763 - INFO: λ_seg: 0.0001
2026-09-23 20:26:31,091 - INFO: -------------------Epoch: 248------------------------
2026-09-23 20:26:31,095 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.537019  0.973468  0.000146
2026-09-23 20:26:31,101 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995635  0.997763  0.996932  0.998696  0.995832
real potato   0.702561  0.825251  0.999094  0.703009  0.999644
fake potato   0.846964  0.917092  0.983689  0.859028  0.999887
real apple    0.696394  0.820979  0.895885  0.757718  0.998860
fake apple    0.679997  0.809473  0.967045  0.696128  0.998763
real orange   0.768471  0.869030  0.990081  0.774433  0.999693
fake orange   0.875631  0.933642  0.899644  0.970419  0.999605
real grape    0.754883  0.860273  0.935215  0.796536  0.999460
fake grape    0.875958  0.933828  0.944295  0.923689  0.999516
real lemon    0.336503  0.503512  0.389477  0.712153  0.998350
fake lemon    0.843049  0.914792  0.993074  0.848035  0.999666
real avocado  0.799836  0.888738  0.827459  0.959934  0.999777
fake avocado  0.443651  0.614581  0.999426  0.443764  0.999334
real pepper   0.822701  0.902677  0.899011  0.906474  0.999285
fake pepper   0.882364  0.937457  0.995468  0.885923  0.999718
real plant    0.867329  0.928901  0.936322  0.921696  0.998590
fake plant    0.905371  0.950286  0.950518  0.950153  0.999921
real banana   0.316209  0.480445  0.893939  0.328535  0.998404
fake banana   0.644740  0.783953  0.748060  0.823573  0.999165
real onion    0.646786  0.785464  0.673921  0.941395  0.999536
fake onion    0.933874  0.965757  0.986384  0.946070  0.999958
real unknown  0.878414  0.935222  0.919742  0.951336  0.999979
fake unknown  0.240451  0.387647  0.252493  0.834480  0.997779
total         0.728599  0.823772  0.872921  0.823182  0.999162
total(-bg)    0.716461  0.815864  0.867284  0.815204  0.999313
2026-09-23 20:26:31,651 - INFO: Epoch accounting: {'epoch': 248, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11302560, 48629, 56440, 108352, 146974, 79045, 68062, 153968, 209683, 71485, 52148, 57448, 33007, 232072, 129830, 138915, 21761, 90401, 59496, 84214, 58806, 3641, 31335], 'crops_with_class': [202, 31, 24, 32, 36, 24, 23, 28, 36, 30, 23, 19, 12, 60, 31, 24, 19, 25, 26, 38, 25, 4, 16], 'targeted_crops_by_class': [0, 4, 4, 5, 4, 2, 5, 4, 3, 4, 4, 5, 4, 7, 4, 7, 3, 2, 2, 2, 4, 2, 2], 'sampled_scene_counts': [0, 2, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 2, 1, 2, 0, 0, 1, 0, 0, 1, 2, 1, 0, 3, 1, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 2, 2, 3, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 1, 1, 0, 0, 1, 1, 1, 0, 2, 1, 0, 2, 3, 3, 2, 0, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 0, 3, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 3, 1, 1, 3, 0, 2, 1, 1, 0, 2, 1, 2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 1, 1, 1, 3, 3, 1, 0, 0, 1, 2, 1, 1, 2, 2, 2, 0, 3, 0, 1, 2, 2, 1, 1, 1, 1, 1, 1, 3, 1, 0], 'learning_rate': 5.106506593080591e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007145939545249474, 'train_segmentation_loss': 0.3246269313120606, 'val_foreground_miou_all22': 0.7164608215582512, 'val_psnr_ref1': 38.537018585205075, 'elapsed_seconds': 337.69498109817505, 'peak_cuda_allocated_gib': 7.511272430419922}

Epoch 249/500 | Batch 10/202 | Rec 0.000818 | Seg 0.364295 | Elapsed 0.2m | ETA 4.0m
Epoch 249/500 | Batch 20/202 | Rec 0.000730 | Seg 0.349575 | Elapsed 0.4m | ETA 3.8m
Epoch 249/500 | Batch 30/202 | Rec 0.000711 | Seg 0.337391 | Elapsed 0.6m | ETA 3.6m
Epoch 249/500 | Batch 40/202 | Rec 0.000697 | Seg 0.337077 | Elapsed 0.8m | ETA 3.4m
Epoch 249/500 | Batch 50/202 | Rec 0.000667 | Seg 0.308956 | Elapsed 1.0m | ETA 3.2m
Epoch 249/500 | Batch 60/202 | Rec 0.000709 | Seg 0.322245 | Elapsed 1.3m | ETA 3.0m
Epoch 249/500 | Batch 70/202 | Rec 0.000727 | Seg 0.324058 | Elapsed 1.5m | ETA 2.8m
Epoch 249/500 | Batch 80/202 | Rec 0.000723 | Seg 0.318434 | Elapsed 1.7m | ETA 2.5m
Epoch 249/500 | Batch 90/202 | Rec 0.000737 | Seg 0.322807 | Elapsed 1.9m | ETA 2.3m
Epoch 249/500 | Batch 100/202 | Rec 0.000741 | Seg 0.328062 | Elapsed 2.1m | ETA 2.1m
Epoch 249/500 | Batch 110/202 | Rec 0.000748 | Seg 0.329215 | Elapsed 2.3m | ETA 1.9m
Epoch 249/500 | Batch 120/202 | Rec 0.000736 | Seg 0.329243 | Elapsed 2.5m | ETA 1.7m
Epoch 249/500 | Batch 130/202 | Rec 0.000743 | Seg 0.331357 | Elapsed 2.7m | ETA 1.5m
Epoch 249/500 | Batch 140/202 | Rec 0.000743 | Seg 0.336625 | Elapsed 2.9m | ETA 1.3m
Epoch 249/500 | Batch 150/202 | Rec 0.000742 | Seg 0.336148 | Elapsed 3.1m | ETA 1.1m
Epoch 249/500 | Batch 160/202 | Rec 0.000749 | Seg 0.335650 | Elapsed 3.4m | ETA 0.9m
Epoch 249/500 | Batch 170/202 | Rec 0.000766 | Seg 0.334297 | Elapsed 3.6m | ETA 0.7m
Epoch 249/500 | Batch 180/202 | Rec 0.000759 | Seg 0.333353 | Elapsed 3.8m | ETA 0.5m
Epoch 249/500 | Batch 190/202 | Rec 0.000766 | Seg 0.335966 | Elapsed 4.0m | ETA 0.3m
Epoch 249/500 | Batch 200/202 | Rec 0.000778 | Seg 0.339490 | Elapsed 4.2m | ETA 0.0m
Epoch 249/500 | Batch 202/202 | Rec 0.000781 | Seg 0.340613 | Elapsed 4.2m | ETA 0.0m

2026-09-23 20:30:45,145 - INFO: Rec loss: 0.0007808430632259374
2026-09-23 20:30:45,145 - INFO: Seg loss: 0.3406126049928146
2026-09-23 20:30:45,145 - INFO: λ_rec: 1
2026-09-23 20:30:45,145 - INFO: λ_seg: 0.0001
2026-09-23 20:32:06,473 - INFO: -------------------Epoch: 249------------------------
2026-09-23 20:32:06,477 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.192655  0.971656  0.000158
2026-09-23 20:32:06,484 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995494  0.997692  0.996607  0.998880  0.995696
real potato   0.892907  0.943374  0.994488  0.897348  0.999871
fake potato   0.856538  0.922676  0.958889  0.889191  0.999892
real apple    0.688179  0.815243  0.954219  0.711676  0.998887
fake apple    0.637704  0.778730  0.952217  0.658786  0.998587
real orange   0.758100  0.862359  0.994404  0.761348  0.999680
fake orange   0.874425  0.932956  0.896371  0.972764  0.999600
real grape    0.537153  0.698844  0.841672  0.597530  0.998925
fake grape    0.843045  0.914790  0.875566  0.957802  0.999340
real lemon    0.361177  0.530634  0.482568  0.589457  0.998775
fake lemon    0.830102  0.907115  0.999306  0.830581  0.999640
real avocado  0.842824  0.914659  0.879624  0.952709  0.999835
fake avocado  0.586818  0.739569  0.999566  0.586968  0.999505
real pepper   0.875040  0.933306  0.950994  0.916361  0.999521
fake pepper   0.914359  0.955214  0.974938  0.936368  0.999791
real plant    0.818443  0.900108  0.915935  0.884916  0.998036
fake plant    0.884084  0.938426  0.944121  0.932899  0.999903
real banana   0.496053  0.663103  0.926526  0.516366  0.998821
fake banana   0.644128  0.783500  0.731259  0.843895  0.999142
real onion    0.638049  0.778987  0.655961  0.958960  0.999509
fake onion    0.914835  0.955474  0.944904  0.966384  0.999943
real unknown  0.852941  0.920585  0.901280  0.940840  0.999974
fake unknown  0.222168  0.363526  0.241467  0.735422  0.997831
total         0.737590  0.832647  0.870125  0.827715  0.999161
total(-bg)    0.725867  0.825145  0.864376  0.819935  0.999319
2026-09-23 20:32:06,993 - INFO: Epoch accounting: {'epoch': 249, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11206121, 63411, 60555, 113923, 141574, 77232, 59559, 136133, 237385, 69966, 49614, 41536, 36313, 231227, 159950, 175057, 24852, 72830, 71109, 84076, 61841, 11617, 52391], 'crops_with_class': [202, 36, 27, 31, 41, 24, 22, 28, 39, 29, 21, 15, 14, 60, 41, 23, 21, 24, 31, 39, 28, 12, 21], 'targeted_crops_by_class': [0, 6, 4, 6, 4, 4, 2, 7, 7, 4, 2, 5, 3, 3, 9, 8, 3, 2, 8, 3, 6, 4, 5], 'sampled_scene_counts': [1, 0, 1, 1, 2, 1, 0, 0, 2, 2, 1, 0, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 2, 1, 0, 1, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 2, 1, 1, 1, 2, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 2, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 3, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 2, 1, 1, 1, 0, 4, 1, 2, 0, 2, 1, 2, 1, 1, 0, 1, 2, 1, 1, 1, 1, 1, 0, 2, 2, 3, 2, 1, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 4, 2, 1, 2, 2, 4, 0, 1, 1, 2, 1, 1, 5, 2, 1, 0, 3, 1, 1, 2, 0, 0, 2, 2, 2, 1, 1, 2, 0, 1, 2, 3, 1, 0, 2, 1, 1, 2, 0, 1, 2, 1], 'learning_rate': 5.0751731239182144e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007808430632259374, 'train_segmentation_loss': 0.3406126049928146, 'val_foreground_miou_all22': 0.7258669222725487, 'val_psnr_ref1': 38.192655334472654, 'elapsed_seconds': 335.33451628685, 'peak_cuda_allocated_gib': 7.513950347900391}

Epoch 250/500 | Batch 10/202 | Rec 0.000731 | Seg 0.303073 | Elapsed 0.2m | ETA 4.0m
Epoch 250/500 | Batch 20/202 | Rec 0.000687 | Seg 0.303090 | Elapsed 0.4m | ETA 3.8m
Epoch 250/500 | Batch 30/202 | Rec 0.000727 | Seg 0.338599 | Elapsed 0.6m | ETA 3.6m
Epoch 250/500 | Batch 40/202 | Rec 0.000713 | Seg 0.328374 | Elapsed 0.8m | ETA 3.4m
Epoch 250/500 | Batch 50/202 | Rec 0.000725 | Seg 0.329993 | Elapsed 1.1m | ETA 3.2m
Epoch 250/500 | Batch 60/202 | Rec 0.000712 | Seg 0.317434 | Elapsed 1.3m | ETA 3.0m
Epoch 250/500 | Batch 70/202 | Rec 0.000706 | Seg 0.312719 | Elapsed 1.5m | ETA 2.8m
Epoch 250/500 | Batch 80/202 | Rec 0.000708 | Seg 0.315190 | Elapsed 1.7m | ETA 2.6m
Epoch 250/500 | Batch 90/202 | Rec 0.000712 | Seg 0.322547 | Elapsed 1.9m | ETA 2.4m
Epoch 250/500 | Batch 100/202 | Rec 0.000697 | Seg 0.315439 | Elapsed 2.1m | ETA 2.1m
Epoch 250/500 | Batch 110/202 | Rec 0.000697 | Seg 0.314712 | Elapsed 2.3m | ETA 1.9m
Epoch 250/500 | Batch 120/202 | Rec 0.000682 | Seg 0.302144 | Elapsed 2.5m | ETA 1.7m
Epoch 250/500 | Batch 130/202 | Rec 0.000688 | Seg 0.306232 | Elapsed 2.7m | ETA 1.5m
Epoch 250/500 | Batch 140/202 | Rec 0.000686 | Seg 0.305454 | Elapsed 2.9m | ETA 1.3m
Epoch 250/500 | Batch 150/202 | Rec 0.000690 | Seg 0.307138 | Elapsed 3.2m | ETA 1.1m
Epoch 250/500 | Batch 160/202 | Rec 0.000694 | Seg 0.308873 | Elapsed 3.4m | ETA 0.9m
Epoch 250/500 | Batch 170/202 | Rec 0.000693 | Seg 0.308479 | Elapsed 3.6m | ETA 0.7m
Epoch 250/500 | Batch 180/202 | Rec 0.000709 | Seg 0.309831 | Elapsed 3.8m | ETA 0.5m
Epoch 250/500 | Batch 190/202 | Rec 0.000708 | Seg 0.310636 | Elapsed 4.0m | ETA 0.3m
Epoch 250/500 | Batch 200/202 | Rec 0.000708 | Seg 0.309428 | Elapsed 4.2m | ETA 0.0m
Epoch 250/500 | Batch 202/202 | Rec 0.000708 | Seg 0.309609 | Elapsed 4.3m | ETA 0.0m

2026-09-23 20:36:22,324 - INFO: Rec loss: 0.0007083780252683613
2026-09-23 20:36:22,324 - INFO: Seg loss: 0.3096086105128916
2026-09-23 20:36:22,324 - INFO: λ_rec: 1
2026-09-23 20:36:22,324 - INFO: λ_seg: 0.0001
2026-09-23 20:37:43,182 - INFO: -------------------Epoch: 250------------------------
2026-09-23 20:37:43,186 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.988927  0.972001  0.000166
2026-09-23 20:37:43,192 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995066  0.997477  0.996381  0.998675  0.995286
real potato   0.921043  0.958849  0.949606  0.968375  0.999901
fake potato   0.933863  0.965751  0.947411  0.984918  0.999949
real apple    0.669508  0.801994  0.998090  0.670367  0.998858
fake apple    0.552616  0.711805  0.962596  0.564743  0.998274
real orange   0.725315  0.840743  0.999521  0.725567  0.999638
fake orange   0.846807  0.917000  0.885148  0.951338  0.999507
real grape    0.745882  0.854397  0.883349  0.827377  0.999411
fake grape    0.885107  0.939002  0.938453  0.939653  0.999549
real lemon    0.512378  0.677530  0.770516  0.604648  0.999324
fake lemon    0.783283  0.878424  0.999908  0.783339  0.999541
real avocado  0.920643  0.958632  0.976986  0.941051  0.999925
fake avocado  0.166922  0.286064  1.000000  0.166922  0.999003
real pepper   0.867891  0.929224  0.918538  0.940264  0.999476
fake pepper   0.917475  0.956912  0.945569  0.968632  0.999792
real plant    0.843853  0.915265  0.955159  0.878661  0.998374
fake plant    0.842870  0.914686  0.917293  0.912193  0.999865
real banana   0.735784  0.847733  0.924391  0.782901  0.999368
fake banana   0.606216  0.754788  0.677186  0.852605  0.998981
real onion    0.640379  0.780722  0.653500  0.969600  0.999508
fake onion    0.943437  0.970845  0.986277  0.955985  0.999964
real unknown  0.739862  0.850434  0.788744  0.922710  0.999948
fake unknown  0.164303  0.282202  0.176174  0.709163  0.996961
total         0.737413  0.825673  0.880469  0.826943  0.999148
total(-bg)    0.725702  0.817864  0.875201  0.819137  0.999324

Stopped after epoch 250; scheduler horizon remains 500

2026-09-23 20:37:43,699 - INFO: Epoch accounting: {'epoch': 250, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11395584, 54132, 61841, 93589, 123977, 49092, 59890, 122801, 225566, 65600, 57272, 65628, 54183, 223245, 121709, 82052, 24704, 81338, 76995, 90525, 61193, 8170, 39186], 'crops_with_class': [202, 31, 29, 28, 31, 16, 24, 25, 33, 26, 25, 22, 18, 48, 34, 14, 23, 25, 32, 35, 25, 9, 16], 'targeted_crops_by_class': [0, 5, 7, 2, 4, 3, 0, 5, 4, 2, 5, 7, 6, 6, 4, 3, 6, 8, 7, 3, 4, 1, 2], 'sampled_scene_counts': [1, 1, 0, 1, 2, 0, 1, 0, 0, 3, 1, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 2, 0, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 4, 1, 1, 0, 1, 2, 0, 1, 3, 1, 2, 2, 1, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 3, 3, 0, 2, 2, 1, 0, 2, 1, 0, 0, 3, 1, 0, 1, 0, 0, 1, 1, 3, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 1, 2, 2, 1, 1, 1, 1, 3, 3, 1, 1, 0, 4, 1, 2, 1, 2, 1, 0, 1, 0, 0, 3, 2, 2, 0, 1, 0, 2, 1, 2, 2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 2, 1, 3, 1, 1, 5, 4], 'learning_rate': 5.043837180528219e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007083780252683613, 'train_segmentation_loss': 0.3096086105128916, 'val_foreground_miou_all22': 0.7257016703685952, 'val_psnr_ref1': 37.988926544189454, 'elapsed_seconds': 336.6984033584595, 'peak_cuda_allocated_gib': 7.508335113525391}

Saved epoch: 250 | block target: 250 | Missing checkpoint files: []
Download: /kaggle/working/balanced200_to_epoch250_20260923_155019_epoch250.zip

/kaggle/working/balanced200_to_epoch250_20260923_155019_epoch250.zip

Epoch250 completed. Download the full backup before stopping the session.

In [4]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((CONT200_RUN / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(201,251)), 'Not all50 new epochs completed.'
for start,end in [(201,225),(226,250)]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] <= end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:', json.dumps(records[-1], indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

Epochs201-225: mean mIoU=68.05%, std=3.84 points
Epochs226-250: mean mIoU=71.06%, std=2.85 points
Final: {
  "epoch": 250,
  "scheduler_horizon": 500,
  "lambda_rec": 1,
  "lambda_seg": 0.0001,
  "sampling_policy": "balanced50_v1",
  "class_pixels_seen": [
    11395584,
    54132,
    61841,
    93589,
    123977,
    49092,
    59890,
    122801,
    225566,
    65600,
    57272,
    65628,
    54183,
    223245,
    121709,
    82052,
    24704,
    81338,
    76995,
    90525,
    61193,
    8170,
    39186
  ],
  "crops_with_class": [
    202,
    31,
    29,
    28,
    31,
    16,
    24,
    25,
    33,
    26,
    25,
    22,
    18,
    48,
    34,
    14,
    23,
    25,
    32,
    35,
    25,
    9,
    16
  ],
  "targeted_crops_by_class": [
    0,
    5,
    7,
    2,
    4,
    3,
    0,
    5,
    4,
    2,
    5,
    7,
    6,
    6,
    4,
    3,
    6,
    8,
    7,
    3,
    4,
    1,
    2
  ],
  "sampled_scene_counts": [
    1,
    1,
    0,
    1,
    2,
    0,
    1,
    0,
    0,
    3,
    1,
    0,
    2,
    1,
    1,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    2,
    2,
    2,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    0,
    0,
    2,
    0,
    1,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    1,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    1,
    1,
    0,
    1,
    0,
    1,
    4,
    1,
    1,
    0,
    1,
    2,
    0,
    1,
    3,
    1,
    2,
    2,
    1,
    2,
    1,
    0,
    0,
    0,
    0,
    0,
    1,
    0,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    2,
    1,
    1,
    1,
    0,
    0,
    1,
    0,
    3,
    3,
    0,
    2,
    2,
    1,
    0,
    2,
    1,
    0,
    0,
    3,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    3,
    1,
    1,
    0,
    1,
    1,
    0,
    0,
    1,
    1,
    1,
    2,
    0,
    1,
    2,
    2,
    1,
    1,
    1,
    1,
    3,
    3,
    1,
    1,
    0,
    4,
    1,
    2,
    1,
    2,
    1,
    0,
    1,
    0,
    0,
    3,
    2,
    2,
    0,
    1,
    0,
    2,
    1,
    2,
    2,
    1,
    1,
    2,
    1,
    1,
    0,
    1,
    1,
    1,
    2,
    1,
    3,
    1,
    1,
    5,
    4
  ],
  "learning_rate": 5.043837180528219e-05,
  "attempted_updates": 202,
  "optimizer_updates": 202,
  "amp_skipped_updates": 0,
  "train_reconstruction_loss": 0.0007083780252683613,
  "train_segmentation_loss": 0.3096086105128916,
  "val_foreground_miou_all22": 0.7257016703685952,
  "val_psnr_ref1": 37.988926544189454,
  "elapsed_seconds": 336.6984033584595,
  "peak_cuda_allocated_gib": 7.508335113525391
}
New successful updates: 10095
New AMP skips: 5