In [ ]:
from pathlib import Path
import shutil
import zipfile
import os

inputs = Path("/kaggle/input")
destination = Path("/kaggle/working/BTP")

matches = list(inputs.rglob("run_public252.py"))

if matches:
    source = matches[0].parent
    shutil.copytree(source, destination, dirs_exist_ok=True)
else:
    archives = list(inputs.rglob("*.zip"))
    code_found = False

    for archive in archives:
        with zipfile.ZipFile(archive) as z:
            if "BTP/run_public252.py" in z.namelist():
                # Extract only our code archive.
                target = Path("/kaggle/working").resolve()
                for name in z.namelist():
                    if not (target / name).resolve().is_relative_to(target):
                        raise ValueError("Unsafe archive path")
                z.extractall(target)
                code_found = True
                break

    if not code_found:
        print("Attached input folders:", list(inputs.iterdir()))
        print("ZIP files found:", archives)
        raise RuntimeError(
            "BTP code is not attached. Add the dataset containing BTP-code.zip."
        )

assert (destination / "run_public252.py").is_file()
os.chdir(destination)
print("Code ready:", os.getcwd())

In [ ]:
import importlib
from pathlib import Path

for name in [
    "torch", "torchvision", "numpy", "pandas",
    "scipy", "skimage", "PIL", "einops", "torchmetrics", "tqdm"
]:
    try:
        module = importlib.import_module(name)
        print(f"{name}: OK ({getattr(module, '__version__', 'unknown')})")
    except Exception as error:
        print(f"{name}: FAILED — {error}")

import torch
print("\nCUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:", round(
        torch.cuda.get_device_properties(0).total_memory / 1024**3, 1
    ), "GB")

roots = [
    p.parent
    for p in Path("/kaggle/input").rglob("train_data.csv")
    if (p.parent / "visible_28").is_dir()
    and (p.parent / "labels").is_dir()
]

print("\nPrepared dataset folders:", roots)

In [ ]:
from pathlib import Path
import subprocess
import sys

DATA_ROOT = Path("/kaggle/input/datasets/arnavnigamd/btp-data/public252")

def run(script, *args):
    subprocess.run(
        [sys.executable, script, *map(str, args)],
        cwd="/kaggle/working/BTP",
        check=True,
    )

run("verify_evaluation.py")
run("run_public252.py", "--root", DATA_ROOT)
run("verify_portability.py", "--root", DATA_ROOT)
run("verify_public252_pipeline.py", "--root", DATA_ROOT)

In [ ]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
import subprocess
import sys
from datetime import datetime

DATA_ROOT = "/kaggle/input/datasets/arnavnigamd/btp-data/public252"
OUT = "/kaggle/working/gpu_smoke_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "gpu_smoke.py",
        "--root", DATA_ROOT,
        "--out", OUT,
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

In [ ]:
import subprocess
import sys
from datetime import datetime

OUT = "/kaggle/working/fixed_crop_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "diagnostic_public252.py",
        "--root", "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--out", OUT,
        "--transpose-image",
        "--steps", "200",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Diagnostic results:", OUT)

In [ ]:
from IPython.display import display, Image

display(Image(
    filename="/kaggle/working/fixed_crop_20260917_144904/predictions.png"
))

In [ ]:
import subprocess
import sys
from datetime import datetime

OUT = "/kaggle/working/fixed_crop_1000_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "diagnostic_public252.py",
        "--root", "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--out", OUT,
        "--transpose-image",
        "--steps", "1000",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Results:", OUT)

In [ ]:
from pathlib import Path
from IPython.display import display, Image
import json

run_dir = Path("/kaggle/working/fixed_crop_1000_20260917_145850")

metrics = json.loads((run_dir / "metrics.json").read_text())
print("Final step:", metrics[-1]["step"])
print("Final mIoU:", metrics[-1]["foreground_miou_present"])

display(Image(filename=str(run_dir / "predictions.png")))

In [ ]:
from pathlib import Path
import shutil
from IPython.display import FileLink, display

run_dir = Path("/kaggle/working/fixed_crop_1000_20260917_145850")
assert run_dir.is_dir(), "Run folder not found"

archive = shutil.make_archive(
    "/kaggle/working/fixed_crop_1000_backup",
    "zip",
    root_dir=run_dir.parent,
    base_dir=run_dir.name,
)

display(FileLink(archive))

##version 2

In [ ]:
from pathlib import Path
import shutil, zipfile, os

inputs = Path('/kaggle/input')
working = Path('/kaggle/working')

def safe_extract(archive, target):
    target.mkdir(parents=True, exist_ok=False)
    with zipfile.ZipFile(archive) as z:
        for name in z.namelist():
            if not (target / name).resolve().is_relative_to(target.resolve()):
                raise ValueError('Unsafe ZIP member')
        z.extractall(target)

code = list(inputs.rglob('compare_diagnostic_lr.py'))
if not code:
    for archive in inputs.rglob('*.zip'):
        with zipfile.ZipFile(archive) as z:
            is_code = 'BTP/compare_diagnostic_lr.py' in z.namelist()
        if is_code:
            target = working / 'lr_code_unpacked'
            safe_extract(archive, target)
            code.extend(target.rglob('compare_diagnostic_lr.py'))
assert len(code) == 1, f'Expected one updated code input: {code}'
shutil.copytree(code[0].parent, working/'BTP', dirs_exist_ok=True)
os.chdir(working/'BTP')

run_name = 'fixed_crop_1000_20260917_145850'
runs = [p.parent for p in inputs.rglob('diagnostic_checkpoint.pt')
        if p.parent.name == run_name]
if not runs:
    for archive in inputs.rglob('*.zip'):
        with zipfile.ZipFile(archive) as z:
            is_run = f'{run_name}/diagnostic_checkpoint.pt' in z.namelist()
        if is_run:
            target = working / 'reference_unpacked'
            safe_extract(archive, target)
            runs.append(target/run_name)
assert len(runs) == 1, f'Expected one saved 1,000-step run: {runs}'
REFERENCE_RUN = runs[0]
DATA_ROOT = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert (DATA_ROOT/'train_data.csv').is_file()
print('Code ready; reference:', REFERENCE_RUN)

In [ ]:
import subprocess
import sys
import torch
from pathlib import Path
from datetime import datetime

assert torch.cuda.is_available(), "Enable GPU T4 ×2 first"

DATA_ROOT = Path("/kaggle/input/datasets/arnavnigamd/btp-data/public252")
REFERENCE_RUN = Path(
    "/kaggle/input/datasets/arnavnigamd/checkpoint1/"
    "fixed_crop_1000_20260917_145850"
)
OUT = Path(
    "/kaggle/working/lr_comparison_"
    + datetime.now().strftime("%Y%m%d_%H%M%S")
)

subprocess.run(
    [sys.executable, "verify_diagnostic_comparison.py"],
    cwd="/kaggle/working/BTP",
    check=True,
)

subprocess.run(
    [
        sys.executable, "compare_diagnostic_lr.py",
        "--root", str(DATA_ROOT),
        "--from-run", str(REFERENCE_RUN),
        "--out", str(OUT),
        "--steps", "500",
        "--eval-every", "10",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Results:", OUT)
print((OUT / "comparison_summary.json").read_text())

In [ ]:
import subprocess
import sys
from datetime import datetime

checkpoint = (
    "/kaggle/working/lr_comparison_20260917_160952/"
    "control_4e-4/diagnostic_checkpoint.pt"
)

subprocess.run(
    [
        sys.executable, "test.py",
        "--data_root",
        "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--transpose_image",
        "--eval_split", "val",
        "--limit", "1",
        "--pretrained_model_path", checkpoint,
        "--outf", "/kaggle/working/evaluations",
        "--name", "full_frame_smoke_" + datetime.now().strftime("%H%M%S"),
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

In [ ]:
from pathlib import Path
from IPython.display import display, Image

comparison = Path("/kaggle/working/lr_comparison_20260917_160952")

for arm in ["control_4e-4", "low_4e-5"]:
    path = comparison / arm / "best_predictions.png"
    print(arm)
    if path.is_file():
        display(Image(filename=str(path)))
    else:
        print("Restore the saved comparison folder and update its path.")

In [ ]:
from pathlib import Path

for root in [Path("/kaggle/input"), Path("/kaggle/working")]:
    print(f"\nSearching {root}")
    for pattern in ["best_predictions.png", "comparison_summary.json", "*.zip"]:
        for path in root.rglob(pattern):
            print(path)

In [ ]:
from pathlib import Path
import shutil
import zipfile

inputs = Path("/kaggle/input")
target = Path("/kaggle/working/BTP")

# Find an already-extracted copy of the updated code.
sources = [
    p.parent for p in inputs.rglob("run_public252.py")
    if "--stop-after-epoch" in p.read_text()
]

if sources:
    shutil.copytree(sources[0], target, dirs_exist_ok=True)
else:
    candidates = []
    for archive in inputs.rglob("*.zip"):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            name = "BTP/run_public252.py"
            if name in z.namelist():
                if b"--stop-after-epoch" in z.read(name):
                    candidates.append(archive)

    if not candidates:
        raise FileNotFoundError(
            "Attach BTP-code-pilot.zip through Add Input, then rerun this cell."
        )

    with zipfile.ZipFile(candidates[0]) as z:
        destination = Path("/kaggle/working").resolve()
        for member in z.infolist():
            resolved = (destination / member.filename).resolve()
            if not resolved.is_relative_to(destination):
                raise ValueError("Unsafe archive path")
        z.extractall(destination)

assert (target / "run_public252.py").is_file()
assert "--stop-after-epoch" in (target / "run_public252.py").read_text()
print("Updated pilot code ready:", target)

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_pilot_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '3', '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-3 model folder.
import zipfile
expected = 'baseline_pilot_20260917_190720'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-3 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_to_epoch10_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '10', '--resume', str(REFERENCE), '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-10 model folder.
import zipfile
expected = 'baseline_to_epoch10_20260917_195856'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-10 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_to_epoch50_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '50', '--resume', str(REFERENCE), '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
import json
for path in sorted((RUN / 'result').glob('*_training.json')):
    print(json.dumps(json.loads(path.read_text()), indent=2))
print('Download the complete archive, then share these metrics and the per-class segmentation CSVs.')

In [ ]:
from pathlib import Path
import shutil
import zipfile

inputs = Path("/kaggle/input")
destination = Path("/kaggle/working").resolve()
code = destination / "BTP"

sources = [
    p.parent for p in inputs.rglob("run_public252.py")
    if "--stop-after-epoch" in p.read_text()
]

if sources:
    shutil.copytree(sources[0], code, dirs_exist_ok=True)
else:
    found = False
    for archive in inputs.rglob("*.zip"):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            entry = "BTP/run_public252.py"
            if entry not in z.namelist():
                continue
            if b"--stop-after-epoch" not in z.read(entry):
                continue
            for member in z.infolist():
                if not (destination / member.filename).resolve().is_relative_to(destination):
                    raise ValueError("Unsafe archive path")
            z.extractall(destination)
            found = True
            break

    assert found, "Attach BTP-code-pilot.zip through Add Input, then rerun."

assert (code / "test.py").is_file()
print("Code ready:", code)

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-50 model folder.
import zipfile
expected = 'baseline_to_epoch50_20260917_204827'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-50 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import shutil
OUT = Path('/kaggle/working') / ('checkpoint_audit_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
OUT.mkdir()
try:
    for name, weights in [('best_iou_a', 'best_iou.pth'), ('best_iou_b', 'best_iou.pth'), ('last_epoch50', 'last.pt')]:
        subprocess.run([sys.executable, '-u', 'test.py', '--data_root', str(DATA),
            '--transpose_image', '--eval_split', 'val', '--pretrained_model_path', str(REFERENCE.with_name(weights)),
            '--outf', str(OUT), '--name', name], cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
    display(FileLink(archive))
    print('Download this evaluation archive for comparison:', archive)

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-paired')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
if not CODE.exists():
    sources = list(INPUTS.rglob('paired_full_training.py'))
    if len(sources) == 1:
        shutil.copytree(sources[0].parent, CODE)
    else:
        found = []
        for archive in INPUTS.rglob('*.zip'):
            if zipfile.is_zipfile(archive):
                with zipfile.ZipFile(archive) as z:
                    if 'BTP/paired_full_training.py' in z.namelist(): found.append(archive)
        assert len(found) == 1, 'Attach exactly one BTP-code-paired-full.zip input.'
        staging = Path('/kaggle/working/paired_code_extract')
        staging.mkdir(exist_ok=False)
        with zipfile.ZipFile(found[0]) as z: safe_extract(z, staging)
        shutil.copytree(staging / 'BTP', CODE)
assert (CODE / 'paired_full_training.py').is_file()
expected = 'baseline_to_epoch50_20260917_204827'
refs = list(INPUTS.rglob(expected + '/model/last.pt'))
if not refs:
    for archive in INPUTS.rglob('*.zip'):
        if not zipfile.is_zipfile(archive): continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' in z.namelist():
                dest = Path('/kaggle/working/paired_reference')
                safe_extract(z, dest)
                refs = [dest / expected / 'model/last.pt']
                break
assert len(refs) == 1, 'Attach the complete epoch50 run ZIP or extracted folder.'
REFERENCE = refs[0].parent.parent
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
import torch
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Code:', CODE, 'Reference:', REFERENCE, 'GPU:', torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'verify_paired_full_training.py'], cwd=CODE, check=True)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
OUT = Path('/kaggle/working') / ('paired_full_lr_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
try:
    subprocess.run([sys.executable, '-u', 'paired_full_training.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{OUT.name}/{arm}/model/{name}' for arm in ['control','quarter_lr']
                for name in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{OUT.name}/{arm}/model/{name}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download the complete ZIP before closing the session. Check logs for successful epoch60 completion in BOTH arms.')

In [ ]:
import json
summary = json.loads((OUT / 'comparison_summary.json').read_text())
for arm, result in summary['arms'].items():
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))
assert set(summary['arms']) == {'control', 'quarter_lr'}, 'Comparison is incomplete.'

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-paired')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
if not CODE.exists():
    sources = list(INPUTS.rglob('paired_full_training.py'))
    if len(sources) == 1:
        shutil.copytree(sources[0].parent, CODE)
    else:
        found = []
        for archive in INPUTS.rglob('*.zip'):
            if zipfile.is_zipfile(archive):
                with zipfile.ZipFile(archive) as z:
                    if 'BTP/paired_full_training.py' in z.namelist(): found.append(archive)
        assert len(found) == 1, 'Attach exactly one BTP-code-paired-full.zip input.'
        staging = Path('/kaggle/working/paired_code_extract')
        staging.mkdir(exist_ok=False)
        with zipfile.ZipFile(found[0]) as z: safe_extract(z, staging)
        shutil.copytree(staging / 'BTP', CODE)
assert (CODE / 'paired_full_training.py').is_file()
import json, hashlib, math
import torch
expected = 'paired_full_lr_20260918_065140'
relative = expected + '/quarter_lr/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach paired_full_lr_20260918_065140.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 60
expected_config = dict(learning_rate=0.0001, max_epoch=500, batch_size=1,
                       workers=0, seed=3407, transpose_image=True,
                       method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Unexpected checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 60
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Resuming quarter-rate checkpoint:', CHECKPOINT)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Saved best metrics:', state['best'])
del state
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU before training.'
print('GPU:', torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above; the next cell resumes the quarter schedule, not the printed default schedule.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'quarter_lr_to_epoch100_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
shutil.copy2(CODE / 'public252-v1.json', OUT / 'dataset_protocol.json')
provenance = {
    'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
    'source_epoch': 60, 'stop_after_epoch': 100, 'arm': 'quarter_lr',
    'note': 'Restore saved Adam/scaler/RNG and quarter-scaled500-epoch scheduler without rescaling again.',
    'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
                      for f in ['train.py', 'opt.py', 'training_state.py', 'dataset.py']}
}
(OUT / 'continuation.json').write_text(json.dumps(provenance, indent=2))
command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
    '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
    '--learning_rate', '0.0001', '--max_epoch', '500', '--stop_after_epoch', '100',
    '--resume', str(CHECKPOINT), '--outf', str(OUT.parent) + '/', '--name', NAME]
try:
    subprocess.run(command, cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{NAME}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
                   if f'{NAME}/model/{f}' not in z.namelist()]
    print('Archive:', archive, 'Missing checkpoint files:', missing)
    if (OUT / 'model/last.pt').is_file():
        saved = torch.load(OUT / 'model/last.pt', map_location='cpu', weights_only=True)
        print('Saved epoch:', saved['epoch'], 'Best metrics:', saved['best'])
        del saved
    display(FileLink(archive))
    print('Download the complete archive before stopping the session. Check saved epoch is100; a partial run also creates an archive.')

In [ ]:
records = [json.loads(p.read_text()) for p in sorted((OUT / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(61,101)), 'Training did not finish all40 epochs.'
print('Final epoch:', json.dumps(records[-1], indent=2))
print('Best mIoU among new epochs:', max(records, key=lambda r: r['val_foreground_miou_all22']))
print('AMP skips in new epochs:', sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import os
import shutil
import zipfile
from IPython.display import display, FileLink

working = Path("/kaggle/working")
runs = [
    p for p in working.glob("quarter_lr_to_epoch100_*")
    if p.is_dir() and (p / "model/last.pt").is_file()
]
assert runs, "No saved run found. Keep this session open and share the output."

run = max(runs, key=lambda p: (p / "model/last.pt").stat().st_mtime)
archive = run.with_suffix(".zip")

# Recreate the archive from the saved run.
shutil.make_archive(
    str(run), "zip", root_dir=run.parent, base_dir=run.name
)

with zipfile.ZipFile(archive) as z:
    assert z.testzip() is None, "Archive integrity check failed"

print("ZIP:", archive)
print(f"Size: {archive.stat().st_size / 1024**2:.1f} MiB")

os.chdir(working)
display(FileLink(archive.name))

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-weak-audit')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = "parser.add_argument('--save_segmentation'"
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'test.py'):
    sources = [p.parent for p in INPUTS.rglob('test.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/test.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-weak-audit.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'test.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
CHECKPOINT = CHECKPOINT.with_name('best_iou.pth')
assert '--save_segmentation' in (CODE / 'test.py').read_text(), 'Attach the updated BTP-code-weak-audit.zip.'
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Evaluating saved best segmentation checkpoint:', CHECKPOINT)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'weak_class_audit_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
try:
    subprocess.run([sys.executable, '-u', 'test.py', '--data_root', str(DATA),
        '--transpose_image', '--eval_split', 'val', '--save_segmentation',
        '--pretrained_model_path', str(CHECKPOINT), '--outf', str(OUT), '--name', 'best_epoch96'], cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    import os
    os.chdir('/kaggle/working')
    print('Download:', archive)
    display(FileLink(Path(archive).name))

In [ ]:
import numpy as np
import sys
sys.path.insert(0,str(CODE))
from dataset import get_class_names
folder = OUT / 'best_epoch96/evaluation_val'
meta = json.loads((folder / 'evaluation.json').read_text())
assert meta['status']=='completed' and meta['scene_count']==25
hist = np.load(folder / 'confusion_matrix.npy')
classes = get_class_names()
for k in [9,12,17,22]:
    total = hist[k].sum()
    print(classes[k], 'ground-truth pixels:', int(total))
    print([(classes[j], round(100*hist[k,j]/total,2)) for j in np.argsort(hist[k])[::-1][:5]])
print('Share the downloaded ZIP; it contains all25 previews and per-scene confusion matrices, without reconstructed HSI cubes.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-training-diagnostic')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Training-only inference diagnostic; fixed class-rich crops'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'diagnose_training_classes.py'):
    sources = [p.parent for p in INPUTS.rglob('diagnose_training_classes.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/diagnose_training_classes.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-training-diagnostic.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'diagnose_training_classes.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
CHECKPOINT = CHECKPOINT.with_name('best_iou.pth')
assert (CODE / 'diagnose_training_classes.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Evaluating saved best segmentation checkpoint:', CHECKPOINT)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'training_class_diagnostic_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'diagnose_training_classes.py', '--root', str(DATA),
        '--checkpoint', str(CHECKPOINT), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z: assert z.testzip() is None
        import os
        os.chdir('/kaggle/working')
        print('Download:', archive)
        display(FileLink(Path(archive).name))

In [ ]:
record = json.loads((OUT / 'diagnostic.json').read_text())
assert record.get('status') == 'completed', 'Diagnostic did not finish.'
for row in json.loads((OUT / 'summary.json').read_text()):
    print(row['class_id'],row['scene'],row['mode'],
          'IoU:',round(100*row['target_iou'],2),'recall:',round(100*row['target_recall'],2))
print('These are selected TRAINING-scene diagnostics, not validation or test scores.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-loss-pair')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Matched epoch101-110 segmentation-loss experiment'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'paired_loss_weight.py'):
    sources = [p.parent for p in INPUTS.rglob('paired_loss_weight.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/paired_loss_weight.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-loss-pair.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'paired_loss_weight.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'paired_loss_weight.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Epoch100 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_loss_pair.py'],cwd=CODE,check=True)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'paired_loss_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'paired_loss_weight.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{NAME}/{arm}/model/{file}' for arm in ['control_seg1e-4','higher_seg1e-3']
                for file in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{NAME}/{arm}/model/{file}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        import os
        os.chdir('/kaggle/working')
        display(FileLink(Path(archive).name))
        print('Download before ending the session. Confirm BOTH arms reached epoch110.')

In [ ]:
summary = json.loads((OUT / 'comparison_summary.json').read_text())
assert set(summary['arms']) == {'control_seg1e-4','higher_seg1e-3'}, 'Incomplete comparison'
for arm, result in summary['arms'].items():
    assert result['final']['epoch'] == 110
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))

/////////////////////////////////////////

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Epoch100 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'balanced_sampling_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_sampling_experiment.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{NAME}/balanced50/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{NAME}/balanced50/model/{f}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        import os
        os.chdir('/kaggle/working')
        display(FileLink(Path(archive).name))
        print('Download the complete ZIP before ending the session.')

In [ ]:
summary = json.loads((OUT / 'comparison_summary.json').read_text())
assert summary['arms']['balanced50']['final']['epoch']==110
for arm, result in summary['arms'].items():
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))
print('Historical control is reused from the completed loss experiment; only balanced50 was newly trained.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_sampling_20260922_131859'
relative = expected + '/balanced50/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_sampling_20260922_131859.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch110 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 110
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 110
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'balanced_to_epoch130_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
shutil.copy2(CODE / 'public252-v1.json', OUT / 'dataset_protocol.json')
manifest = {
    'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
    'source_epoch': 110, 'stop_after_epoch': 130, 'sampling_policy': 'balanced50_v1',
    'note': 'Exact full-state continuation settings: lambda_seg1e-4; saved quarter-rate cosine schedule restored without additional scaling.',
    'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
        for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
}
(OUT / 'continuation.json').write_text(json.dumps(manifest, indent=2))
command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
    '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
    '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
    '--max_epoch', '500', '--stop_after_epoch', '130', '--resume', str(CHECKPOINT),
    '--outf', str(OUT.parent) + '/', '--name', NAME]
try:
    subprocess.run(command, cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{NAME}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{NAME}/model/{f}' not in z.namelist()]
    print('Archive:', archive, 'Missing checkpoint files:', missing)
    if (OUT / 'model/last.pt').is_file():
        saved = torch.load(OUT / 'model/last.pt', map_location='cpu', weights_only=True)
        print('Saved epoch:', saved['epoch'], 'Best metrics:', saved['best'])
        del saved
    import os
    os.chdir('/kaggle/working')
    display(FileLink(Path(archive).name))
    print('Download the complete ZIP before ending the session. A partial run can also produce an archive.')

In [ ]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((OUT / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(111,131)), 'Not all20 epochs completed.'
print('Final:', json.dumps(records[-1], indent=2))
for start in [111,121]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] < start+10]
    print(f'Epochs{start}-{start+9}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('New optimizer updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_to_epoch130_20260922_143402'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced130')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_to_epoch130_20260922_143402.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch130 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 130
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 130
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch130 run.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT_RUN' not in globals():
    CONT_RUN = Path('/kaggle/working') / ('balanced_to_epoch200_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 130, 'target_epoch': 200, 'backup_epochs': [150,175,200],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Three subprocess blocks with epoch-boundary RNG restoration.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT_RUN.parent / (CONT_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT_RUN.parent, base_dir=CONT_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target in [150,175,200]
    last = CONT_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT_RUN.parent) + '/', '--name', CONT_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Block completed. Download the backup, then run the next block when ready.')
print('Continuation folder:', CONT_RUN)

In [ ]:
continue_to(150)

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_to_epoch200_20260922_164019'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced150')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_to_epoch200_20260922_164019_epoch150.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch150 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 150
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 150
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch150 run.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT150_RUN' not in globals():
    CONT150_RUN = Path('/kaggle/working') / ('balanced150_to_epoch200_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT150_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT150_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 150, 'target_epoch': 200, 'backup_epochs': [200],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Single subprocess continuation from150 through200.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT150_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT150_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT150_RUN.parent / (CONT150_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT150_RUN.parent, base_dir=CONT150_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT150_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT150_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target == 200
    last = CONT150_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT150_RUN.parent) + '/', '--name', CONT150_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT150_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT150_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Epoch200 completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT150_RUN)

In [ ]:
continue_to(200)

In [ ]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((CONT150_RUN / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(151,201)), 'Not all50 new epochs completed.'
for start,end in [(151,175),(176,200)]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] <= end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:', json.dumps(records[-1], indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='5ad004708dd6ce388708ad3627cf8206b184804b6202754204f7296bfc253c7b'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced150_to_epoch200_20260923_102523/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch188_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced150_to_epoch200_20260923_102523_epoch200.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch188 weights:',CHECKPOINT)

In [ ]:
NAME='epoch188_validation_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f')
RUN=WORK/NAME
subprocess.run([sys.executable,'test.py','--data_root',str(DATA),
    '--transpose_image','--eval_split','val','--pretrained_model_path',str(CHECKPOINT),
    '--outf',str(WORK),'--name',NAME,'--workers','0','--save_segmentation'],
    cwd=CODE,check=True)
OUT=RUN/'evaluation_val'
print('Evaluation complete:',OUT)

In [ ]:
EXPECTED_MIOU=0.7511010246306207
EXPECTED_PSNR=37.20344635009766

import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['split']=='val' and meta['scene_count']==25
assert meta['checkpoint_sha256']==EXPECTED
assert len(set(meta['scenes']))==25
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(scene+'_confusion.npy')) for scene in meta['scenes']]
assert np.array_equal(sum(parts),cm), 'Per-scene confusion totals differ.'
assert len(list(OUT.glob('*_preview.png')))==25
assert not list(OUT.glob('*_hsi.npy'))
seg=pd.read_csv(OUT/'segmentation.csv',index_col=0)
rec=pd.read_csv(OUT/'reconstruction.csv')
miou=float(seg.loc['total(-bg)','IoU'])
psnr=float(rec.iloc[0]['PSNR'])
summary=dict(checkpoint_epoch=188,validation_scenes=25,foreground_miou=miou,
    psnr_ref1=psnr,logged_miou=EXPECTED_MIOU,logged_psnr=EXPECTED_PSNR,
    miou_difference=miou-EXPECTED_MIOU,psnr_difference=psnr-EXPECTED_PSNR,
    matches_logged_metrics=bool(abs(miou-EXPECTED_MIOU)<1e-5 and abs(psnr-EXPECTED_PSNR)<1e-3),
    scope='Independent full validation evaluation; no test performance or new training.')
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'evaluator_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in
    ['test.py','dataset.py','utils.py','public252-v1.json']},indent=2))
print(json.dumps(summary,indent=2))
display(seg)
display(rec)
# Save results even if the comparison differs, so the difference can be investigated.
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir(WORK)
print('Download this archive before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))
if not summary['matches_logged_metrics']:
    print('Metrics differ from the training record: share this ZIP before further training.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced150_to_epoch200_20260923_102523'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced200')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced150_to_epoch200_20260923_102523_epoch200.zip or its extracted folder.'
CHECKPOINT = refs[0]
assert hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest() == 'e0c7e178b9c90178cc08d71136d3f5316ab985159b9ab1254bf26c5cf0325e9a', 'Wrong epoch200 checkpoint.'
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch200 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 200
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 200
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch200 run.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT200_RUN' not in globals():
    CONT200_RUN = Path('/kaggle/working') / ('balanced200_to_epoch250_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT200_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT200_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 200, 'target_epoch': 250, 'backup_epochs': [250],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Single subprocess continuation from200 through250.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT200_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT200_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT200_RUN.parent / (CONT200_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT200_RUN.parent, base_dir=CONT200_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT200_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT200_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target == 250
    last = CONT200_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT200_RUN.parent) + '/', '--name', CONT200_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT200_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT200_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Epoch250 completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT200_RUN)

In [ ]:
continue_to(250)

In [ ]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((CONT200_RUN / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(201,251)), 'Not all50 new epochs completed.'
for start,end in [(201,225),(226,250)]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] <= end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:', json.dumps(records[-1], indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

In [1]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced200_to_epoch250_20260923_155019'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced250')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced200_to_epoch250_20260923_155019_epoch250.zip or its extracted folder.'
CHECKPOINT = refs[0]
assert hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest() == '2ae6932257f8145195e62f2152ef43c14a61cec1de4e15d8c71b4e1aff8b1253', 'Wrong epoch250 checkpoint.'
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch250 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 250
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 250
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch250 run.')

Balanced epoch250 reference: /kaggle/input/datasets/arnavnigamd/checkpoint11/balanced200_to_epoch250_20260923_155019
PASS:22-class support, aligned crops/flips, deterministic replay, no RNG consumed by index building, baseline crop branch unchanged.
Saved next-epoch LR: 5.012499999999993e-05
Preserved best metrics: {'iou': 0.7584254897344173, 'psnr': 38.60311950683594}
{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.
Training source hashes match the epoch250 run.

In [2]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT250_RUN' not in globals():
    CONT250_RUN = Path('/kaggle/working') / ('balanced250_to_epoch300_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT250_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT250_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 250, 'target_epoch': 300, 'backup_epochs': [300],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Single subprocess continuation from250 through300.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT250_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT250_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT250_RUN.parent / (CONT250_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT250_RUN.parent, base_dir=CONT250_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT250_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT250_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target == 300
    last = CONT250_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT250_RUN.parent) + '/', '--name', CONT250_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT250_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT250_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Epoch300 completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT250_RUN)

Continuation folder: /kaggle/working/balanced250_to_epoch300_20260924_074129

In [3]:
continue_to(300)

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced250_to_epoch300_20260924_074129', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/input/datasets/arnavnigamd/checkpoint11/balanced200_to_epoch250_20260923_155019/model/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=300, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-24 07:42:18,251 - INFO: Resuming after epoch 250

Epoch 251/500 | Batch 10/202 | Rec 0.000750 | Seg 0.329174 | Elapsed 0.5m | ETA 10.0m
Epoch 251/500 | Batch 20/202 | Rec 0.000667 | Seg 0.303941 | Elapsed 0.8m | ETA 7.3m
Epoch 251/500 | Batch 30/202 | Rec 0.000668 | Seg 0.296523 | Elapsed 1.1m | ETA 6.1m
Epoch 251/500 | Batch 40/202 | Rec 0.000666 | Seg 0.303320 | Elapsed 1.4m | ETA 5.5m
Epoch 251/500 | Batch 50/202 | Rec 0.000668 | Seg 0.311343 | Elapsed 1.6m | ETA 4.9m
Epoch 251/500 | Batch 60/202 | Rec 0.000684 | Seg 0.315615 | Elapsed 1.9m | ETA 4.5m
Epoch 251/500 | Batch 70/202 | Rec 0.000684 | Seg 0.320309 | Elapsed 2.2m | ETA 4.1m
Epoch 251/500 | Batch 80/202 | Rec 0.000672 | Seg 0.312660 | Elapsed 2.4m | ETA 3.7m
Epoch 251/500 | Batch 90/202 | Rec 0.000682 | Seg 0.314601 | Elapsed 2.7m | ETA 3.3m
Epoch 251/500 | Batch 100/202 | Rec 0.000680 | Seg 0.320170 | Elapsed 2.9m | ETA 3.0m
Epoch 251/500 | Batch 110/202 | Rec 0.000691 | Seg 0.323606 | Elapsed 3.1m | ETA 2.6m
Epoch 251/500 | Batch 120/202 | Rec 0.000700 | Seg 0.328968 | Elapsed 3.4m | ETA 2.3m
Epoch 251/500 | Batch 130/202 | Rec 0.000707 | Seg 0.335425 | Elapsed 3.7m | ETA 2.0m
Epoch 251/500 | Batch 140/202 | Rec 0.000704 | Seg 0.330993 | Elapsed 3.9m | ETA 1.7m
Epoch 251/500 | Batch 150/202 | Rec 0.000718 | Seg 0.334498 | Elapsed 4.1m | ETA 1.4m
Epoch 251/500 | Batch 160/202 | Rec 0.000715 | Seg 0.335579 | Elapsed 4.4m | ETA 1.1m
Epoch 251/500 | Batch 170/202 | Rec 0.000718 | Seg 0.337156 | Elapsed 4.6m | ETA 0.9m
Epoch 251/500 | Batch 180/202 | Rec 0.000715 | Seg 0.332608 | Elapsed 4.8m | ETA 0.6m
Epoch 251/500 | Batch 190/202 | Rec 0.000719 | Seg 0.339900 | Elapsed 5.1m | ETA 0.3m
Epoch 251/500 | Batch 200/202 | Rec 0.000722 | Seg 0.337479 | Elapsed 5.3m | ETA 0.1m
Epoch 251/500 | Batch 202/202 | Rec 0.000720 | Seg 0.336860 | Elapsed 5.4m | ETA 0.0m

2026-09-24 07:47:40,823 - INFO: Rec loss: 0.0007199603810071908
2026-09-24 07:47:40,823 - INFO: Seg loss: 0.33686020007670514
2026-09-24 07:47:40,823 - INFO: λ_rec: 1
2026-09-24 07:47:40,823 - INFO: λ_seg: 0.0001
2026-09-24 07:49:12,414 - INFO: -------------------Epoch: 251------------------------
2026-09-24 07:49:12,424 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  37.898774  0.972202  0.00017
2026-09-24 07:49:12,430 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.994776  0.997331  0.995616  0.999153  0.995005
real potato   0.873200  0.932259  0.999271  0.873757  0.999848
fake potato   0.932452  0.964995  0.970152  0.959992  0.999949
real apple    0.762383  0.865123  0.961649  0.786289  0.999155
fake apple    0.576336  0.731188  0.993957  0.578362  0.998395
real orange   0.806027  0.892547  0.996432  0.808360  0.999744
fake orange   0.879563  0.935873  0.907902  0.965729  0.999621
real grape    0.820607  0.901415  0.956836  0.852152  0.999611
fake grape    0.863853  0.926904  0.932977  0.921008  0.999463
real lemon    0.415003  0.586526  0.523717  0.666580  0.998896
fake lemon    0.800475  0.889133  0.997489  0.802092  0.999577
real avocado  0.896915  0.945607  0.955727  0.935796  0.999900
fake avocado  0.265345  0.419370  0.987234  0.266259  0.999118
real pepper   0.892409  0.943096  0.940330  0.945979  0.999583
fake pepper   0.901684  0.948250  0.957395  0.939376  0.999756
real plant    0.814780  0.897889  0.978672  0.829509  0.998114
fake plant    0.827081  0.905308  0.923783  0.887653  0.999852
real banana   0.540622  0.701776  0.937663  0.560777  0.998929
fake banana   0.612807  0.759876  0.686496  0.850946  0.999011
real onion    0.650772  0.788397  0.699346  0.903564  0.999562
fake onion    0.926283  0.961681  0.995856  0.929867  0.999953
real unknown  0.902672  0.948797  1.000000  0.902672  0.999984
fake unknown  0.165708  0.284270  0.182203  0.646686  0.997257
total         0.744424  0.831635  0.890465  0.817937  0.999143
total(-bg)    0.733044  0.824104  0.885686  0.809700  0.999331
2026-09-24 07:49:12,908 - INFO: Epoch accounting: {'epoch': 251, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11228706, 58137, 59368, 76419, 154861, 84210, 86638, 140892, 200935, 86124, 69935, 35335, 34018, 256256, 130280, 181962, 30421, 61224, 65136, 89688, 55627, 10404, 41696], 'crops_with_class': [202, 30, 27, 24, 37, 26, 25, 28, 45, 32, 27, 12, 13, 58, 29, 24, 25, 20, 25, 32, 24, 12, 22], 'targeted_crops_by_class': [0, 4, 6, 4, 5, 5, 7, 7, 6, 8, 4, 3, 2, 5, 4, 4, 5, 4, 7, 7, 3, 4, 6], 'sampled_scene_counts': [0, 0, 0, 0, 0, 2, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 2, 2, 2, 0, 1, 1, 1, 2, 1, 2, 1, 0, 2, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 2, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 3, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 3, 3, 0, 0, 2, 2, 0, 0, 3, 1, 3, 3, 2, 3, 1, 0, 2, 2, 2, 1, 2, 0, 3, 2, 1, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0, 2, 1, 2, 4, 1, 1, 2, 2, 4, 1, 0, 2, 2, 1, 2, 2, 1, 0, 1, 2, 2, 0, 1, 1, 1, 2, 0, 2, 2, 0, 1, 0, 1, 0, 1, 2, 1, 2, 2, 3, 1, 1, 0, 2], 'learning_rate': 5.012499999999993e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007199603810071908, 'train_segmentation_loss': 0.33686020007670514, 'val_foreground_miou_all22': 0.7330443255116227, 'val_psnr_ref1': 37.898773956298825, 'elapsed_seconds': 414.6494023799896, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 252/500 | Batch 10/202 | Rec 0.000731 | Seg 0.340342 | Elapsed 0.2m | ETA 4.2m
Epoch 252/500 | Batch 20/202 | Rec 0.000736 | Seg 0.342296 | Elapsed 0.4m | ETA 4.0m
Epoch 252/500 | Batch 30/202 | Rec 0.000723 | Seg 0.336074 | Elapsed 0.7m | ETA 3.8m
Epoch 252/500 | Batch 40/202 | Rec 0.000725 | Seg 0.348590 | Elapsed 0.9m | ETA 3.6m
Epoch 252/500 | Batch 50/202 | Rec 0.000746 | Seg 0.352943 | Elapsed 1.1m | ETA 3.4m
Epoch 252/500 | Batch 60/202 | Rec 0.000741 | Seg 0.350800 | Elapsed 1.4m | ETA 3.2m
Epoch 252/500 | Batch 70/202 | Rec 0.000739 | Seg 0.351378 | Elapsed 1.6m | ETA 3.0m
Epoch 252/500 | Batch 80/202 | Rec 0.000744 | Seg 0.350070 | Elapsed 1.8m | ETA 2.8m
Epoch 252/500 | Batch 90/202 | Rec 0.000742 | Seg 0.352520 | Elapsed 2.0m | ETA 2.5m
Epoch 252/500 | Batch 100/202 | Rec 0.000743 | Seg 0.347079 | Elapsed 2.2m | ETA 2.3m
Epoch 252/500 | Batch 110/202 | Rec 0.000727 | Seg 0.339807 | Elapsed 2.5m | ETA 2.1m
Epoch 252/500 | Batch 120/202 | Rec 0.000744 | Seg 0.341650 | Elapsed 2.7m | ETA 1.8m
Epoch 252/500 | Batch 130/202 | Rec 0.000742 | Seg 0.342128 | Elapsed 2.9m | ETA 1.6m
Epoch 252/500 | Batch 140/202 | Rec 0.000745 | Seg 0.343588 | Elapsed 3.1m | ETA 1.4m
Epoch 252/500 | Batch 150/202 | Rec 0.000738 | Seg 0.342961 | Elapsed 3.3m | ETA 1.1m
Epoch 252/500 | Batch 160/202 | Rec 0.000735 | Seg 0.340330 | Elapsed 3.5m | ETA 0.9m
Epoch 252/500 | Batch 170/202 | Rec 0.000741 | Seg 0.340567 | Elapsed 3.7m | ETA 0.7m
Epoch 252/500 | Batch 180/202 | Rec 0.000745 | Seg 0.341748 | Elapsed 4.0m | ETA 0.5m
Epoch 252/500 | Batch 190/202 | Rec 0.000737 | Seg 0.338922 | Elapsed 4.2m | ETA 0.3m
Epoch 252/500 | Batch 200/202 | Rec 0.000733 | Seg 0.335829 | Elapsed 4.4m | ETA 0.0m
Epoch 252/500 | Batch 202/202 | Rec 0.000730 | Seg 0.335235 | Elapsed 4.5m | ETA 0.0m

2026-09-24 07:53:40,414 - INFO: Rec loss: 0.0007299987100310264
2026-09-24 07:53:40,414 - INFO: Seg loss: 0.3352352032198174
2026-09-24 07:53:40,414 - INFO: λ_rec: 1
2026-09-24 07:53:40,414 - INFO: λ_seg: 0.0001
2026-09-24 07:54:54,193 - INFO: -------------------Epoch: 252------------------------
2026-09-24 07:54:54,198 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.04729  0.972431  0.000164
2026-09-24 07:54:54,204 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995596  0.997743  0.997028  0.998560  0.995795
real potato   0.910349  0.953021  0.958355  0.947845  0.999888
fake potato   0.948859  0.973708  0.972031  0.975492  0.999962
real apple    0.818033  0.899860  0.966585  0.841840  0.999354
fake apple    0.655255  0.791679  0.989515  0.659837  0.998689
real orange   0.923359  0.960103  0.988593  0.933302  0.999898
fake orange   0.925027  0.961003  0.953565  0.968660  0.999775
real grape    0.652772  0.789863  0.905603  0.700431  0.999222
fake grape    0.891771  0.942740  0.946869  0.938745  0.999579
real lemon    0.551582  0.710946  0.571993  0.939237  0.999103
fake lemon    0.777698  0.874900  0.999259  0.778146  0.999529
real avocado  0.919930  0.958245  0.963947  0.952709  0.999923
fake avocado  0.759720  0.863406  0.999497  0.760010  0.999712
real pepper   0.804912  0.891863  0.837262  0.954197  0.999154
fake pepper   0.775703  0.873636  0.977651  0.789706  0.999456
real plant    0.854456  0.921466  0.910545  0.932756  0.998411
fake plant    0.906820  0.951083  0.948865  0.953413  0.999922
real banana   0.484010  0.652254  0.902243  0.510797  0.998776
fake banana   0.709814  0.830232  0.829115  0.831453  0.999375
real onion    0.666745  0.800008  0.688949  0.953893  0.999569
fake onion    0.934788  0.966245  0.990851  0.942926  0.999958
real unknown  0.694561  0.819704  0.720695  0.950382  0.999933
fake unknown  0.260440  0.413210  0.296404  0.682180  0.998368
total         0.774878  0.860736  0.883279  0.865066  0.999276
total(-bg)    0.764846  0.854508  0.878109  0.858998  0.999434
2026-09-24 07:54:54,912 - INFO: Epoch accounting: {'epoch': 252, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11212527, 52658, 63293, 122936, 189852, 95378, 47327, 139184, 181129, 59627, 79950, 46192, 24829, 224115, 102934, 223973, 28421, 59102, 72588, 84410, 73252, 12177, 42418], 'crops_with_class': [202, 31, 31, 32, 47, 29, 18, 23, 33, 27, 25, 16, 11, 58, 33, 29, 26, 18, 28, 42, 30, 14, 21], 'targeted_crops_by_class': [0, 2, 6, 1, 9, 3, 2, 2, 8, 2, 5, 3, 4, 5, 6, 5, 5, 3, 5, 3, 8, 7, 5], 'sampled_scene_counts': [1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 0, 1, 2, 1, 2, 0, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 0, 3, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1, 2, 2, 0, 2, 0, 1, 2, 1, 0, 1, 2, 1, 3, 0, 2, 2, 3, 4, 1, 1, 1, 1, 0, 0, 0, 2, 0, 3, 4, 1, 2, 4, 5, 2, 1, 0, 1, 1, 1, 2, 1, 4, 0, 3, 0, 2, 1, 1, 0, 0, 2, 1, 3, 0, 2, 1, 1, 1, 4, 1, 0, 2, 0, 1, 2, 0, 3, 1, 0, 4, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1], 'learning_rate': 4.981162819471768e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007299987100310264, 'train_segmentation_loss': 0.3352352032198174, 'val_foreground_miou_all22': 0.7648456344172129, 'val_psnr_ref1': 38.04729049682617, 'elapsed_seconds': 341.9961621761322, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 253/500 | Batch 10/202 | Rec 0.000744 | Seg 0.342958 | Elapsed 0.2m | ETA 3.8m
Epoch 253/500 | Batch 20/202 | Rec 0.000846 | Seg 0.405390 | Elapsed 0.4m | ETA 3.6m
Epoch 253/500 | Batch 30/202 | Rec 0.000800 | Seg 0.375868 | Elapsed 0.6m | ETA 3.4m
Epoch 253/500 | Batch 40/202 | Rec 0.000748 | Seg 0.353964 | Elapsed 0.8m | ETA 3.3m
Epoch 253/500 | Batch 50/202 | Rec 0.000739 | Seg 0.342907 | Elapsed 1.0m | ETA 3.1m
Epoch 253/500 | Batch 60/202 | Rec 0.000723 | Seg 0.336485 | Elapsed 1.2m | ETA 2.9m
Epoch 253/500 | Batch 70/202 | Rec 0.000721 | Seg 0.337611 | Elapsed 1.4m | ETA 2.7m
Epoch 253/500 | Batch 80/202 | Rec 0.000724 | Seg 0.338664 | Elapsed 1.6m | ETA 2.5m
Epoch 253/500 | Batch 90/202 | Rec 0.000713 | Seg 0.335077 | Elapsed 1.8m | ETA 2.3m
Epoch 253/500 | Batch 100/202 | Rec 0.000724 | Seg 0.336357 | Elapsed 2.0m | ETA 2.1m
Epoch 253/500 | Batch 110/202 | Rec 0.000726 | Seg 0.332780 | Elapsed 2.3m | ETA 1.9m
Epoch 253/500 | Batch 120/202 | Rec 0.000728 | Seg 0.336773 | Elapsed 2.5m | ETA 1.7m
Epoch 253/500 | Batch 130/202 | Rec 0.000728 | Seg 0.334867 | Elapsed 2.7m | ETA 1.5m
Epoch 253/500 | Batch 140/202 | Rec 0.000726 | Seg 0.331403 | Elapsed 2.9m | ETA 1.3m
Epoch 253/500 | Batch 150/202 | Rec 0.000725 | Seg 0.329190 | Elapsed 3.1m | ETA 1.1m
Epoch 253/500 | Batch 160/202 | Rec 0.000741 | Seg 0.329987 | Elapsed 3.3m | ETA 0.9m
Epoch 253/500 | Batch 170/202 | Rec 0.000746 | Seg 0.333173 | Elapsed 3.5m | ETA 0.7m
Epoch 253/500 | Batch 180/202 | Rec 0.000740 | Seg 0.329822 | Elapsed 3.7m | ETA 0.5m
Epoch 253/500 | Batch 190/202 | Rec 0.000746 | Seg 0.330538 | Elapsed 3.9m | ETA 0.2m
Epoch 253/500 | Batch 200/202 | Rec 0.000737 | Seg 0.326922 | Elapsed 4.1m | ETA 0.0m
Epoch 253/500 | Batch 202/202 | Rec 0.000734 | Seg 0.325753 | Elapsed 4.2m | ETA 0.0m

2026-09-24 07:59:06,448 - INFO: Rec loss: 0.0007338985638799016
2026-09-24 07:59:06,449 - INFO: Seg loss: 0.3257526462842332
2026-09-24 07:59:06,449 - INFO: λ_rec: 1
2026-09-24 07:59:06,449 - INFO: λ_seg: 0.0001
2026-09-24 08:00:19,272 - INFO: -------------------Epoch: 253------------------------
2026-09-24 08:00:19,276 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.342337  0.972863  0.000153
2026-09-24 08:00:19,283 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995486  0.997688  0.996761  0.998718  0.995689
real potato   0.105330  0.190569  1.000000  0.105330  0.998929
fake potato   0.354388  0.523279  0.986651  0.356096  0.999527
real apple    0.635872  0.777361  0.704218  0.867581  0.998286
fake apple    0.874963  0.933262  0.922606  0.944269  0.999491
real orange   0.900116  0.947383  0.999486  0.900533  0.999868
fake orange   0.928433  0.962839  0.955113  0.970792  0.999786
real grape    0.767526  0.868425  0.964649  0.789739  0.999501
fake grape    0.864879  0.927495  0.919776  0.935445  0.999459
real lemon    0.310627  0.473970  0.341417  0.774993  0.997979
fake lemon    0.820582  0.901400  0.951591  0.856329  0.999604
real avocado  0.775779  0.873684  0.804393  0.956158  0.999743
fake avocado  0.591152  0.743003  0.999569  0.591303  0.999511
real pepper   0.822943  0.902823  0.917413  0.888787  0.999301
fake pepper   0.792758  0.884351  0.997028  0.794635  0.999505
real plant    0.861736  0.925684  0.921737  0.929766  0.998508
fake plant    0.851254  0.919601  0.909142  0.930406  0.999871
real banana   0.046144  0.088209  0.955119  0.046245  0.997852
fake banana   0.651734  0.789101  0.828965  0.752986  0.999260
real onion    0.550743  0.710246  0.701350  0.719473  0.999470
fake onion    0.909553  0.952584  1.000000  0.909553  0.999943
real unknown  0.887500  0.940347  0.932458  0.948473  0.999981
fake unknown  0.310679  0.474031  0.343142  0.766570  0.998567
total         0.678703  0.769884  0.871851  0.771051  0.999114
total(-bg)    0.664304  0.759529  0.866174  0.760703  0.999270
2026-09-24 08:00:19,848 - INFO: Epoch accounting: {'epoch': 253, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11283562, 55274, 63587, 107724, 144784, 64821, 68811, 108534, 179286, 58746, 52890, 36924, 39052, 204105, 183050, 139833, 17763, 116596, 80552, 77894, 65337, 16543, 72604], 'crops_with_class': [202, 32, 32, 26, 37, 23, 26, 22, 29, 26, 20, 12, 17, 57, 48, 23, 16, 32, 33, 37, 27, 19, 28], 'targeted_crops_by_class': [0, 3, 4, 5, 4, 3, 3, 0, 4, 7, 3, 5, 5, 2, 4, 6, 3, 8, 7, 6, 8, 10, 4], 'sampled_scene_counts': [0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 2, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 4, 0, 1, 1, 1, 0, 1, 0, 0, 3, 0, 3, 3, 1, 0, 1, 3, 0, 1, 5, 0, 1, 0, 2, 0, 0, 2, 1, 2, 1, 1, 1, 4, 7, 3, 3, 2, 1, 1, 4, 5, 1, 4, 3, 0, 1, 3, 1, 1, 0, 1, 1, 1, 2, 1, 2, 1, 0, 0, 0, 1, 3, 2, 0, 0, 3, 1, 1, 0, 0, 2, 1, 4, 3, 3, 1], 'learning_rate': 4.949826876081772e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007338985638799016, 'train_segmentation_loss': 0.3257526462842332, 'val_foreground_miou_all22': 0.6643041374209088, 'val_psnr_ref1': 38.342337188720705, 'elapsed_seconds': 324.92643213272095, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 254/500 | Batch 10/202 | Rec 0.000775 | Seg 0.342279 | Elapsed 0.2m | ETA 4.1m
Epoch 254/500 | Batch 20/202 | Rec 0.000780 | Seg 0.370150 | Elapsed 0.4m | ETA 3.8m
Epoch 254/500 | Batch 30/202 | Rec 0.000674 | Seg 0.326929 | Elapsed 0.6m | ETA 3.6m
Epoch 254/500 | Batch 40/202 | Rec 0.000665 | Seg 0.320115 | Elapsed 0.8m | ETA 3.4m
Epoch 254/500 | Batch 50/202 | Rec 0.000688 | Seg 0.332758 | Elapsed 1.0m | ETA 3.1m
Epoch 254/500 | Batch 60/202 | Rec 0.000714 | Seg 0.329396 | Elapsed 1.2m | ETA 2.9m
Epoch 254/500 | Batch 70/202 | Rec 0.000723 | Seg 0.337268 | Elapsed 1.4m | ETA 2.7m
Epoch 254/500 | Batch 80/202 | Rec 0.000719 | Seg 0.336090 | Elapsed 1.6m | ETA 2.5m
Epoch 254/500 | Batch 90/202 | Rec 0.000714 | Seg 0.330051 | Elapsed 1.8m | ETA 2.3m
Epoch 254/500 | Batch 100/202 | Rec 0.000708 | Seg 0.326566 | Elapsed 2.1m | ETA 2.1m
Epoch 254/500 | Batch 110/202 | Rec 0.000711 | Seg 0.329868 | Elapsed 2.3m | ETA 1.9m
Epoch 254/500 | Batch 120/202 | Rec 0.000708 | Seg 0.332312 | Elapsed 2.5m | ETA 1.7m
Epoch 254/500 | Batch 130/202 | Rec 0.000718 | Seg 0.332921 | Elapsed 2.7m | ETA 1.5m
Epoch 254/500 | Batch 140/202 | Rec 0.000718 | Seg 0.333976 | Elapsed 2.9m | ETA 1.3m
Epoch 254/500 | Batch 150/202 | Rec 0.000715 | Seg 0.332834 | Elapsed 3.1m | ETA 1.1m
Epoch 254/500 | Batch 160/202 | Rec 0.000707 | Seg 0.329427 | Elapsed 3.3m | ETA 0.9m
Epoch 254/500 | Batch 170/202 | Rec 0.000708 | Seg 0.327243 | Elapsed 3.5m | ETA 0.7m
Epoch 254/500 | Batch 180/202 | Rec 0.000702 | Seg 0.326068 | Elapsed 3.7m | ETA 0.4m
Epoch 254/500 | Batch 190/202 | Rec 0.000710 | Seg 0.326903 | Elapsed 3.9m | ETA 0.2m
Epoch 254/500 | Batch 200/202 | Rec 0.000706 | Seg 0.323704 | Elapsed 4.1m | ETA 0.0m
Epoch 254/500 | Batch 202/202 | Rec 0.000707 | Seg 0.323702 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:04:27,721 - INFO: Rec loss: 0.000707235356151947
2026-09-24 08:04:27,722 - INFO: Seg loss: 0.3237018913473233
2026-09-24 08:04:27,722 - INFO: λ_rec: 1
2026-09-24 08:04:27,722 - INFO: λ_seg: 0.0001
2026-09-24 08:05:42,655 - INFO: -------------------Epoch: 254------------------------
2026-09-24 08:05:42,659 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.359044  0.972757  0.000151
2026-09-24 08:05:42,666 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995682  0.997786  0.997050  0.998624  0.995877
real potato   0.898594  0.946539  0.932023  0.961617  0.999870
fake potato   0.929319  0.963315  0.941777  0.985966  0.999945
real apple    0.765263  0.866975  0.955824  0.793322  0.999160
fake apple    0.567368  0.723929  0.991080  0.570280  0.998358
real orange   0.733189  0.846009  0.978999  0.744905  0.999643
fake orange   0.858534  0.923833  0.871978  0.982358  0.999537
real grape    0.697034  0.821424  0.912353  0.747058  0.999322
fake grape    0.897648  0.946013  0.932420  0.960112  0.999595
real lemon    0.551601  0.710960  0.604400  0.863282  0.999175
fake lemon    0.839894  0.912931  0.995149  0.843347  0.999660
real avocado  0.939129  0.968559  0.985224  0.952545  0.999943
fake avocado  0.421905  0.593394  0.999698  0.421959  0.999308
real pepper   0.825259  0.904215  0.866180  0.945853  0.999267
fake pepper   0.824098  0.903518  0.961705  0.852058  0.999566
real plant    0.842747  0.914614  0.929859  0.899957  0.998320
fake plant    0.756547  0.861353  0.786110  0.952646  0.999756
real banana   0.546007  0.706297  0.904399  0.579451  0.998917
fake banana   0.707603  0.828717  0.793803  0.866954  0.999341
real onion    0.635397  0.777007  0.653315  0.958622  0.999503
fake onion    0.943665  0.970966  0.982187  0.960097  0.999964
real unknown  0.541081  0.702163  0.555186  0.955153  0.999870
fake unknown  0.213488  0.351820  0.237132  0.681637  0.997884
total         0.736133  0.832276  0.859472  0.846861  0.999208
total(-bg)    0.724335  0.824752  0.853218  0.839963  0.999359
2026-09-24 08:05:43,226 - INFO: Epoch accounting: {'epoch': 254, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11309009, 55556, 60328, 131920, 111345, 67470, 67970, 125494, 225535, 59967, 61977, 46319, 41897, 214968, 79489, 167592, 26504, 77261, 69799, 109897, 63031, 14535, 50409], 'crops_with_class': [202, 33, 25, 35, 32, 24, 28, 24, 47, 32, 26, 17, 15, 57, 23, 21, 24, 27, 28, 42, 30, 15, 22], 'targeted_crops_by_class': [0, 6, 2, 3, 6, 2, 3, 3, 9, 3, 11, 6, 6, 3, 4, 4, 5, 3, 4, 5, 6, 5, 7], 'sampled_scene_counts': [2, 1, 3, 0, 0, 1, 1, 0, 2, 2, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 3, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 2, 0, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 2, 1, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 0, 2, 6, 1, 2, 2, 2, 1, 4, 3, 2, 2, 0, 2, 0, 3, 1, 4, 2, 1, 1, 1, 0, 0, 0, 2, 3, 1, 3, 0, 1, 2, 0, 1, 0, 0, 0, 2, 1, 1, 2, 2, 1, 1, 4, 0, 1, 1, 5, 2, 1, 2, 2, 2, 1, 3, 0, 3], 'learning_rate': 4.918493406919394e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000707235356151947, 'train_segmentation_loss': 0.3237018913473233, 'val_foreground_miou_all22': 0.7243348962864229, 'val_psnr_ref1': 38.359043731689454, 'elapsed_seconds': 323.3706738948822, 'peak_cuda_allocated_gib': 7.509555816650391}

Epoch 255/500 | Batch 10/202 | Rec 0.000641 | Seg 0.315679 | Elapsed 0.2m | ETA 3.9m
Epoch 255/500 | Batch 20/202 | Rec 0.000633 | Seg 0.313678 | Elapsed 0.4m | ETA 3.8m
Epoch 255/500 | Batch 30/202 | Rec 0.000673 | Seg 0.327939 | Elapsed 0.6m | ETA 3.6m
Epoch 255/500 | Batch 40/202 | Rec 0.000658 | Seg 0.305380 | Elapsed 0.8m | ETA 3.4m
Epoch 255/500 | Batch 50/202 | Rec 0.000658 | Seg 0.306759 | Elapsed 1.0m | ETA 3.2m
Epoch 255/500 | Batch 60/202 | Rec 0.000705 | Seg 0.321228 | Elapsed 1.2m | ETA 3.0m
Epoch 255/500 | Batch 70/202 | Rec 0.000703 | Seg 0.326121 | Elapsed 1.5m | ETA 2.7m
Epoch 255/500 | Batch 80/202 | Rec 0.000708 | Seg 0.325556 | Elapsed 1.7m | ETA 2.5m
Epoch 255/500 | Batch 90/202 | Rec 0.000704 | Seg 0.323396 | Elapsed 1.9m | ETA 2.3m
Epoch 255/500 | Batch 100/202 | Rec 0.000694 | Seg 0.319074 | Elapsed 2.1m | ETA 2.1m
Epoch 255/500 | Batch 110/202 | Rec 0.000694 | Seg 0.317916 | Elapsed 2.3m | ETA 1.9m
Epoch 255/500 | Batch 120/202 | Rec 0.000685 | Seg 0.309319 | Elapsed 2.5m | ETA 1.7m
Epoch 255/500 | Batch 130/202 | Rec 0.000696 | Seg 0.311980 | Elapsed 2.7m | ETA 1.5m
Epoch 255/500 | Batch 140/202 | Rec 0.000696 | Seg 0.310578 | Elapsed 2.9m | ETA 1.3m
Epoch 255/500 | Batch 150/202 | Rec 0.000691 | Seg 0.313005 | Elapsed 3.1m | ETA 1.1m
Epoch 255/500 | Batch 160/202 | Rec 0.000691 | Seg 0.314185 | Elapsed 3.3m | ETA 0.9m
Epoch 255/500 | Batch 170/202 | Rec 0.000690 | Seg 0.314463 | Elapsed 3.5m | ETA 0.7m
Epoch 255/500 | Batch 180/202 | Rec 0.000701 | Seg 0.318172 | Elapsed 3.7m | ETA 0.5m
Epoch 255/500 | Batch 190/202 | Rec 0.000706 | Seg 0.321401 | Elapsed 3.9m | ETA 0.2m
Epoch 255/500 | Batch 200/202 | Rec 0.000711 | Seg 0.324962 | Elapsed 4.1m | ETA 0.0m
Epoch 255/500 | Batch 202/202 | Rec 0.000711 | Seg 0.324795 | Elapsed 4.2m | ETA 0.0m

2026-09-24 08:09:52,987 - INFO: Rec loss: 0.0007108837943282071
2026-09-24 08:09:52,987 - INFO: Seg loss: 0.3247949866448889
2026-09-24 08:09:52,987 - INFO: λ_rec: 1
2026-09-24 08:09:52,987 - INFO: λ_seg: 0.0001
2026-09-24 08:11:04,736 - INFO: -------------------Epoch: 255------------------------
2026-09-24 08:11:04,740 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.489607  0.973101  0.000148
2026-09-24 08:11:04,747 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995318  0.997604  0.996291  0.999020  0.995526
real potato   0.622738  0.767468  0.999182  0.623055  0.999548
fake potato   0.800858  0.889368  0.969824  0.821324  0.999851
real apple    0.723576  0.839572  0.868093  0.812959  0.998929
fake apple    0.720611  0.837573  0.949787  0.749151  0.998903
real orange   0.848863  0.918204  0.996611  0.851320  0.999800
fake orange   0.908714  0.952124  0.935593  0.969353  0.999721
real grape    0.783930  0.878830  0.954592  0.814295  0.999531
fake grape    0.864029  0.927005  0.926216  0.927897  0.999460
real lemon    0.410579  0.582095  0.474153  0.753830  0.998728
fake lemon    0.830769  0.907513  0.996121  0.833466  0.999641
real avocado  0.732382  0.845471  0.754968  0.960755  0.999674
fake avocado  0.556037  0.714638  0.999771  0.556108  0.999469
real pepper   0.823810  0.903344  0.928223  0.879860  0.999312
fake pepper   0.774416  0.872819  0.963292  0.797964  0.999446
real plant    0.859289  0.924270  0.938130  0.910910  0.998508
fake plant    0.757693  0.862095  0.860416  0.863880  0.999780
real banana   0.356434  0.525506  0.967231  0.360790  0.998536
fake banana   0.682178  0.811015  0.838350  0.785501  0.999327
real onion    0.655204  0.791641  0.677315  0.952542  0.999547
fake onion    0.917864  0.957123  0.989417  0.926965  0.999948
real unknown  0.567703  0.724201  0.575689  0.976145  0.999881
fake unknown  0.246129  0.394989  0.276590  0.690873  0.998217
total         0.714745  0.818455  0.862428  0.818172  0.999186
total(-bg)    0.701991  0.810312  0.856344  0.809952  0.999353
2026-09-24 08:11:05,284 - INFO: Epoch accounting: {'epoch': 255, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11304804, 59141, 76844, 121042, 190917, 87527, 82887, 102619, 195308, 54426, 47858, 53846, 28424, 213932, 90822, 171956, 31598, 70674, 75581, 77866, 56184, 8801, 35215], 'crops_with_class': [202, 32, 32, 31, 43, 28, 22, 25, 33, 27, 18, 19, 10, 52, 25, 26, 29, 24, 33, 34, 25, 9, 18], 'targeted_crops_by_class': [0, 6, 4, 6, 6, 2, 5, 4, 4, 4, 2, 4, 3, 5, 4, 5, 4, 3, 4, 5, 5, 2, 5], 'sampled_scene_counts': [1, 1, 1, 1, 2, 1, 1, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 2, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 2, 1, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 0, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 3, 0, 2, 1, 1, 3, 2, 0, 0, 1, 1, 1, 4, 2, 1, 1, 1, 3, 0, 1, 0, 1, 1, 1, 1, 2, 0, 1, 2, 4, 3, 0, 0, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 0, 0, 0, 1, 3, 0, 1, 2, 0, 3, 1, 1, 1, 2, 2, 2, 1, 1, 2, 1, 3, 4, 2, 1, 1, 1, 1, 1, 0, 3, 1, 2, 1, 2, 2], 'learning_rate': 4.8871636489763476e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007108837943282071, 'train_segmentation_loss': 0.3247949866448889, 'val_foreground_miou_all22': 0.7019911780134911, 'val_psnr_ref1': 38.48960723876953, 'elapsed_seconds': 322.04888701438904, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 256/500 | Batch 10/202 | Rec 0.000887 | Seg 0.334843 | Elapsed 0.2m | ETA 3.9m
Epoch 256/500 | Batch 20/202 | Rec 0.000729 | Seg 0.298182 | Elapsed 0.4m | ETA 3.7m
Epoch 256/500 | Batch 30/202 | Rec 0.000772 | Seg 0.348963 | Elapsed 0.6m | ETA 3.5m
Epoch 256/500 | Batch 40/202 | Rec 0.000833 | Seg 0.342069 | Elapsed 0.8m | ETA 3.3m
Epoch 256/500 | Batch 50/202 | Rec 0.000821 | Seg 0.350117 | Elapsed 1.0m | ETA 3.1m
Epoch 256/500 | Batch 60/202 | Rec 0.000784 | Seg 0.334191 | Elapsed 1.2m | ETA 2.9m
Epoch 256/500 | Batch 70/202 | Rec 0.000772 | Seg 0.329628 | Elapsed 1.4m | ETA 2.7m
Epoch 256/500 | Batch 80/202 | Rec 0.000752 | Seg 0.317057 | Elapsed 1.6m | ETA 2.5m
Epoch 256/500 | Batch 90/202 | Rec 0.000751 | Seg 0.320616 | Elapsed 1.8m | ETA 2.3m
Epoch 256/500 | Batch 100/202 | Rec 0.000755 | Seg 0.321493 | Elapsed 2.0m | ETA 2.1m
Epoch 256/500 | Batch 110/202 | Rec 0.000754 | Seg 0.321313 | Elapsed 2.2m | ETA 1.9m
Epoch 256/500 | Batch 120/202 | Rec 0.000753 | Seg 0.325336 | Elapsed 2.4m | ETA 1.7m
Epoch 256/500 | Batch 130/202 | Rec 0.000756 | Seg 0.332231 | Elapsed 2.6m | ETA 1.5m
Epoch 256/500 | Batch 140/202 | Rec 0.000744 | Seg 0.329504 | Elapsed 2.8m | ETA 1.3m
Epoch 256/500 | Batch 150/202 | Rec 0.000757 | Seg 0.339505 | Elapsed 3.0m | ETA 1.1m
Epoch 256/500 | Batch 160/202 | Rec 0.000757 | Seg 0.340122 | Elapsed 3.3m | ETA 0.9m
Epoch 256/500 | Batch 170/202 | Rec 0.000760 | Seg 0.339453 | Elapsed 3.5m | ETA 0.7m
Epoch 256/500 | Batch 180/202 | Rec 0.000754 | Seg 0.336385 | Elapsed 3.7m | ETA 0.4m
Epoch 256/500 | Batch 190/202 | Rec 0.000752 | Seg 0.336324 | Elapsed 3.9m | ETA 0.2m
Epoch 256/500 | Batch 200/202 | Rec 0.000755 | Seg 0.336833 | Elapsed 4.1m | ETA 0.0m
Epoch 256/500 | Batch 202/202 | Rec 0.000758 | Seg 0.336764 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:15:12,420 - INFO: Rec loss: 0.0007581942788807048
2026-09-24 08:15:12,420 - INFO: Seg loss: 0.3367639731726434
2026-09-24 08:15:12,420 - INFO: λ_rec: 1
2026-09-24 08:15:12,420 - INFO: λ_seg: 0.0001
2026-09-24 08:16:27,487 - INFO: -------------------Epoch: 256------------------------
2026-09-24 08:16:27,491 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  37.784814  0.972022  0.000173
2026-09-24 08:16:27,499 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995774  0.997832  0.997272  0.998493  0.995966
real potato   0.671278  0.803263  0.993053  0.674445  0.999605
fake potato   0.833602  0.909201  0.957378  0.865731  0.999874
real apple    0.741893  0.851774  0.880816  0.824679  0.999010
fake apple    0.631575  0.774142  0.944167  0.656078  0.998555
real orange   0.930955  0.964193  0.996909  0.933650  0.999909
fake orange   0.947314  0.972894  0.969367  0.976548  0.999845
real grape    0.739433  0.850151  0.951493  0.768399  0.999435
fake grape    0.897175  0.945751  0.934176  0.957720  0.999594
real lemon    0.430576  0.601918  0.445351  0.928460  0.998557
fake lemon    0.837784  0.911683  0.991192  0.844068  0.999654
real avocado  0.866449  0.928397  0.898097  0.960920  0.999862
fake avocado  0.715033  0.833793  0.999822  0.715124  0.999659
real pepper   0.848620  0.918062  0.899500  0.937510  0.999388
fake pepper   0.854866  0.921705  0.956872  0.889124  0.999640
real plant    0.871562  0.931324  0.928711  0.934052  0.998623
fake plant    0.838074  0.911855  0.987048  0.847393  0.999870
real banana   0.269351  0.424356  0.878465  0.279777  0.998295
fake banana   0.732614  0.845625  0.858094  0.833610  0.999440
real onion    0.677647  0.807806  0.699777  0.955413  0.999589
fake onion    0.942331  0.970259  0.988950  0.952358  0.999963
real unknown  0.709039  0.829703  0.731778  0.958015  0.999937
fake unknown  0.235217  0.380814  0.254989  0.752083  0.997940
total         0.748616  0.838543  0.875795  0.845376  0.999227
total(-bg)    0.737381  0.831303  0.870273  0.838416  0.999375
2026-09-24 08:16:28,076 - INFO: Epoch accounting: {'epoch': 256, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11230462, 47788, 61064, 114684, 121700, 67448, 66225, 135054, 153858, 107205, 67421, 44862, 14985, 263513, 126147, 209153, 20914, 98088, 91677, 93988, 72721, 4699, 24616], 'crops_with_class': [202, 26, 32, 32, 32, 24, 28, 25, 31, 42, 31, 18, 7, 64, 35, 24, 18, 29, 36, 45, 33, 4, 12], 'targeted_crops_by_class': [0, 2, 6, 6, 2, 6, 2, 1, 5, 5, 9, 4, 1, 4, 5, 7, 3, 6, 8, 10, 3, 2, 7], 'sampled_scene_counts': [2, 1, 4, 0, 1, 2, 0, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0, 1, 0, 2, 3, 0, 1, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 2, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 3, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 1, 0, 2, 1, 2, 0, 1, 1, 2, 1, 2, 1, 0, 2, 1, 2, 1, 2, 3, 1, 2, 3, 0, 2, 0, 1, 2, 0, 1, 1, 2, 1, 3, 0, 1, 0, 2, 2, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 3, 2, 2, 2, 2, 1, 1, 1, 3, 2, 1, 2, 0, 4, 2, 2, 4, 1, 1, 4, 1, 4, 1, 0, 0, 1, 3, 1, 1, 2, 0], 'learning_rate': 4.8558388390978285e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007581942788807048, 'train_segmentation_loss': 0.3367639731726434, 'val_foreground_miou_all22': 0.7373813049741096, 'val_psnr_ref1': 37.784814453125, 'elapsed_seconds': 322.78381419181824, 'peak_cuda_allocated_gib': 7.512271881103516}

Epoch 257/500 | Batch 10/202 | Rec 0.000669 | Seg 0.297935 | Elapsed 0.2m | ETA 3.9m
Epoch 257/500 | Batch 20/202 | Rec 0.000714 | Seg 0.326701 | Elapsed 0.4m | ETA 3.7m
Epoch 257/500 | Batch 30/202 | Rec 0.000742 | Seg 0.301953 | Elapsed 0.6m | ETA 3.5m
Epoch 257/500 | Batch 40/202 | Rec 0.000833 | Seg 0.315857 | Elapsed 0.8m | ETA 3.3m
Epoch 257/500 | Batch 50/202 | Rec 0.000785 | Seg 0.310679 | Elapsed 1.0m | ETA 3.1m
Epoch 257/500 | Batch 60/202 | Rec 0.000822 | Seg 0.310805 | Elapsed 1.2m | ETA 2.9m
Epoch 257/500 | Batch 70/202 | Rec 0.000809 | Seg 0.306325 | Elapsed 1.4m | ETA 2.7m
Epoch 257/500 | Batch 80/202 | Rec 0.000797 | Seg 0.298226 | Elapsed 1.6m | ETA 2.5m
Epoch 257/500 | Batch 90/202 | Rec 0.000773 | Seg 0.294536 | Elapsed 1.8m | ETA 2.3m
Epoch 257/500 | Batch 100/202 | Rec 0.000760 | Seg 0.296756 | Elapsed 2.0m | ETA 2.1m
Epoch 257/500 | Batch 110/202 | Rec 0.000753 | Seg 0.298098 | Elapsed 2.2m | ETA 1.9m
Epoch 257/500 | Batch 120/202 | Rec 0.000749 | Seg 0.298882 | Elapsed 2.5m | ETA 1.7m
Epoch 257/500 | Batch 130/202 | Rec 0.000744 | Seg 0.300998 | Elapsed 2.7m | ETA 1.5m
Epoch 257/500 | Batch 140/202 | Rec 0.000745 | Seg 0.302097 | Elapsed 2.9m | ETA 1.3m
Epoch 257/500 | Batch 150/202 | Rec 0.000744 | Seg 0.303222 | Elapsed 3.1m | ETA 1.1m
Epoch 257/500 | Batch 160/202 | Rec 0.000745 | Seg 0.305924 | Elapsed 3.3m | ETA 0.9m
Epoch 257/500 | Batch 170/202 | Rec 0.000738 | Seg 0.304921 | Elapsed 3.5m | ETA 0.7m
Epoch 257/500 | Batch 180/202 | Rec 0.000747 | Seg 0.306898 | Elapsed 3.7m | ETA 0.4m
Epoch 257/500 | Batch 190/202 | Rec 0.000749 | Seg 0.309366 | Elapsed 3.9m | ETA 0.2m
Epoch 257/500 | Batch 200/202 | Rec 0.000751 | Seg 0.312195 | Elapsed 4.1m | ETA 0.0m
Epoch 257/500 | Batch 202/202 | Rec 0.000749 | Seg 0.311510 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:20:35,810 - INFO: Rec loss: 0.0007490252353116123
2026-09-24 08:20:35,810 - INFO: Seg loss: 0.3115095564320979
2026-09-24 08:20:35,810 - INFO: λ_rec: 1
2026-09-24 08:20:35,810 - INFO: λ_seg: 0.0001
2026-09-24 08:21:49,673 - INFO: -------------------Epoch: 257------------------------
2026-09-24 08:21:49,677 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.301762  0.972426  0.000154
2026-09-24 08:21:49,684 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995415  0.997652  0.997043  0.998363  0.995623
real potato   0.922323  0.959542  0.984702  0.935731  0.999906
fake potato   0.963274  0.981244  0.979145  0.983452  0.999973
real apple    0.803962  0.891280  0.973395  0.822026  0.999308
fake apple    0.633634  0.775688  0.989284  0.638013  0.998607
real orange   0.922673  0.959731  0.985482  0.935387  0.999897
fake orange   0.937680  0.967788  0.962179  0.973564  0.999815
real grape    0.799690  0.888647  0.958559  0.828327  0.999567
fake grape    0.886605  0.939845  0.928029  0.952069  0.999550
real lemon    0.566027  0.722835  0.604061  0.899896  0.999189
fake lemon    0.835400  0.910270  0.992843  0.840462  0.999650
real avocado  0.881333  0.936874  0.931225  0.942693  0.999882
fake avocado  0.554254  0.713163  0.997707  0.554960  0.999466
real pepper   0.861482  0.925537  0.905636  0.946438  0.999443
fake pepper   0.849887  0.918803  0.944568  0.894501  0.999623
real plant    0.858938  0.924067  0.945250  0.903908  0.998515
fake plant    0.823390  0.903092  0.874215  0.934049  0.999841
real banana   0.589390  0.741606  0.844938  0.660872  0.998965
fake banana   0.628573  0.771881  0.714790  0.839001  0.999088
real onion    0.602515  0.751913  0.623554  0.946968  0.999436
fake onion    0.943222  0.970732  0.977445  0.964208  0.999963
real unknown  0.895028  0.944556  0.962376  0.927481  0.999983
fake unknown  0.225487  0.367955  0.259049  0.635096  0.998162
total         0.781747  0.863683  0.884151  0.867716  0.999280
total(-bg)    0.772035  0.857593  0.879020  0.861777  0.999447
2026-09-24 08:21:50,427 - INFO: Epoch accounting: {'epoch': 257, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11335166, 47085, 51326, 180378, 140489, 105030, 63793, 99125, 188217, 73562, 75209, 37657, 20011, 251356, 129579, 139027, 33896, 63177, 58289, 82510, 32883, 2693, 27814], 'crops_with_class': [202, 29, 22, 46, 35, 29, 22, 22, 30, 34, 30, 14, 10, 57, 29, 23, 22, 19, 24, 35, 18, 3, 13], 'targeted_crops_by_class': [0, 4, 3, 7, 3, 11, 3, 1, 4, 6, 5, 3, 4, 7, 5, 5, 4, 0, 6, 8, 4, 0, 4], 'sampled_scene_counts': [1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 2, 0, 1, 1, 1, 0, 1, 0, 2, 1, 2, 2, 2, 1, 1, 0, 1, 2, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 0, 1, 1, 0, 0, 4, 2, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 3, 1, 0, 2, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 4, 0, 1, 1, 1, 1, 2, 3, 0, 2, 1, 1, 1, 0, 1, 5, 1, 2, 2, 0, 0, 2, 2, 2, 2, 0, 0, 2, 0, 2, 3, 2, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 0, 2, 1, 3, 0, 0, 3, 1, 4, 0, 1, 1, 1, 1, 1, 0, 2, 2, 1, 1, 0, 0, 1, 0, 0, 4, 2, 0, 3, 1, 2, 0, 1, 3, 2, 1, 1, 2, 0, 1, 1, 0, 0], 'learning_rate': 4.824520213933694e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007490252353116123, 'train_segmentation_loss': 0.3115095564320979, 'val_foreground_miou_all22': 0.7720348696805952, 'val_psnr_ref1': 38.301762084960934, 'elapsed_seconds': 322.3432991504669, 'peak_cuda_allocated_gib': 7.512271881103516}

Epoch 258/500 | Batch 10/202 | Rec 0.000644 | Seg 0.276936 | Elapsed 0.2m | ETA 4.0m
Epoch 258/500 | Batch 20/202 | Rec 0.000712 | Seg 0.311977 | Elapsed 0.4m | ETA 3.7m
Epoch 258/500 | Batch 30/202 | Rec 0.000700 | Seg 0.297544 | Elapsed 0.6m | ETA 3.5m
Epoch 258/500 | Batch 40/202 | Rec 0.000692 | Seg 0.306797 | Elapsed 0.8m | ETA 3.3m
Epoch 258/500 | Batch 50/202 | Rec 0.000688 | Seg 0.299671 | Elapsed 1.0m | ETA 3.1m
Epoch 258/500 | Batch 60/202 | Rec 0.000676 | Seg 0.300165 | Elapsed 1.2m | ETA 2.9m
Epoch 258/500 | Batch 70/202 | Rec 0.000684 | Seg 0.307916 | Elapsed 1.4m | ETA 2.7m
Epoch 258/500 | Batch 80/202 | Rec 0.000671 | Seg 0.300408 | Elapsed 1.6m | ETA 2.5m
Epoch 258/500 | Batch 90/202 | Rec 0.000679 | Seg 0.304807 | Elapsed 1.8m | ETA 2.3m
Epoch 258/500 | Batch 100/202 | Rec 0.000674 | Seg 0.306348 | Elapsed 2.0m | ETA 2.1m
Epoch 258/500 | Batch 110/202 | Rec 0.000685 | Seg 0.315406 | Elapsed 2.3m | ETA 1.9m
Epoch 258/500 | Batch 120/202 | Rec 0.000676 | Seg 0.310840 | Elapsed 2.5m | ETA 1.7m
Epoch 258/500 | Batch 130/202 | Rec 0.000673 | Seg 0.310075 | Elapsed 2.7m | ETA 1.5m
Epoch 258/500 | Batch 140/202 | Rec 0.000677 | Seg 0.312949 | Elapsed 2.9m | ETA 1.3m
Epoch 258/500 | Batch 150/202 | Rec 0.000669 | Seg 0.306445 | Elapsed 3.1m | ETA 1.1m
Epoch 258/500 | Batch 160/202 | Rec 0.000667 | Seg 0.303843 | Elapsed 3.3m | ETA 0.9m
Epoch 258/500 | Batch 170/202 | Rec 0.000675 | Seg 0.306564 | Elapsed 3.5m | ETA 0.7m
Epoch 258/500 | Batch 180/202 | Rec 0.000674 | Seg 0.311428 | Elapsed 3.7m | ETA 0.5m
Epoch 258/500 | Batch 190/202 | Rec 0.000675 | Seg 0.312803 | Elapsed 3.9m | ETA 0.2m
Epoch 258/500 | Batch 200/202 | Rec 0.000671 | Seg 0.311253 | Elapsed 4.1m | ETA 0.0m
Epoch 258/500 | Batch 202/202 | Rec 0.000671 | Seg 0.310704 | Elapsed 4.2m | ETA 0.0m

2026-09-24 08:25:59,854 - INFO: Rec loss: 0.0006708075179451025
2026-09-24 08:25:59,854 - INFO: Seg loss: 0.31070408282229806
2026-09-24 08:25:59,854 - INFO: λ_rec: 1
2026-09-24 08:25:59,854 - INFO: λ_seg: 0.0001
2026-09-24 08:27:16,863 - INFO: -------------------Epoch: 258------------------------
2026-09-24 08:27:16,866 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.05956  0.972572  0.000163
2026-09-24 08:27:16,873 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995707  0.997799  0.996978  0.998721  0.995901
real potato   0.898204  0.946323  0.968875  0.924892  0.999875
fake potato   0.939227  0.968611  0.975973  0.961458  0.999955
real apple    0.797700  0.887418  0.932139  0.846882  0.999259
fake apple    0.619441  0.764959  0.988979  0.623747  0.998553
real orange   0.709348  0.829914  0.988478  0.715262  0.999614
fake orange   0.851919  0.919989  0.873080  0.972338  0.999516
real grape    0.671563  0.803466  0.911612  0.718337  0.999267
fake grape    0.893449  0.943677  0.956686  0.931114  0.999589
real lemon    0.580852  0.734811  0.618891  0.904311  0.999233
fake lemon    0.854069  0.921242  0.986096  0.864479  0.999687
real avocado  0.836744  0.911066  0.883897  0.940066  0.999830
fake avocado  0.634560  0.776381  0.976614  0.644351  0.999556
real pepper   0.860379  0.924900  0.930989  0.918989  0.999454
fake pepper   0.847071  0.917155  0.955090  0.882210  0.999620
real plant    0.842457  0.914443  0.923164  0.905983  0.998305
fake plant    0.827849  0.905768  0.857632  0.959739  0.999841
real banana   0.568913  0.725184  0.929603  0.594527  0.998988
fake banana   0.733974  0.846530  0.850800  0.842402  0.999438
real onion    0.639293  0.779913  0.708299  0.867759  0.999558
fake onion    0.940880  0.969489  0.993403  0.946796  0.999962
real unknown  0.650032  0.787854  0.663619  0.969466  0.999917
fake unknown  0.223922  0.365872  0.244572  0.726186  0.997879
total         0.757285  0.849685  0.874586  0.854783  0.999252
total(-bg)    0.746448  0.842953  0.869022  0.848240  0.999404
2026-09-24 08:27:17,404 - INFO: Epoch accounting: {'epoch': 258, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11376788, 43060, 53593, 130012, 131404, 71372, 75269, 152406, 220840, 55329, 58574, 43950, 33394, 175865, 127545, 156882, 29561, 92181, 58232, 56733, 49212, 7457, 38613], 'crops_with_class': [202, 28, 25, 34, 35, 22, 22, 27, 40, 24, 28, 16, 13, 49, 32, 24, 25, 24, 24, 28, 23, 7, 15], 'targeted_crops_by_class': [0, 5, 3, 9, 2, 2, 7, 3, 3, 2, 4, 5, 3, 4, 2, 7, 6, 4, 4, 1, 5, 3, 3], 'sampled_scene_counts': [0, 2, 0, 1, 1, 3, 2, 0, 1, 2, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 2, 1, 1, 1, 2, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 2, 1, 1, 2, 0, 0, 1, 1, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 1, 1, 2, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 1, 3, 3, 2, 3, 0, 0, 0, 1, 2, 2, 0, 1, 0, 1, 0, 2, 1, 3, 2, 2, 1, 0, 3, 2, 0, 2, 1, 0, 1, 2, 2, 0, 1, 0, 3, 0, 1, 1, 1, 1, 2, 4, 0, 1, 1, 2, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 3, 2, 1, 2, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1, 1, 1, 0, 2, 0], 'learning_rate': 4.793209009889643e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006708075179451025, 'train_segmentation_loss': 0.31070408282229806, 'val_foreground_miou_all22': 0.7464475487351433, 'val_psnr_ref1': 38.05955978393555, 'elapsed_seconds': 326.9687440395355, 'peak_cuda_allocated_gib': 7.511783599853516}

Epoch 259/500 | Batch 10/202 | Rec 0.000797 | Seg 0.305440 | Elapsed 0.2m | ETA 4.2m
Epoch 259/500 | Batch 20/202 | Rec 0.000767 | Seg 0.313324 | Elapsed 0.4m | ETA 3.8m
Epoch 259/500 | Batch 30/202 | Rec 0.000713 | Seg 0.298434 | Elapsed 0.6m | ETA 3.6m
Epoch 259/500 | Batch 40/202 | Rec 0.000709 | Seg 0.313716 | Elapsed 0.8m | ETA 3.4m
Epoch 259/500 | Batch 50/202 | Rec 0.000732 | Seg 0.334176 | Elapsed 1.0m | ETA 3.1m
Epoch 259/500 | Batch 60/202 | Rec 0.000748 | Seg 0.339226 | Elapsed 1.2m | ETA 2.9m
Epoch 259/500 | Batch 70/202 | Rec 0.000731 | Seg 0.329482 | Elapsed 1.4m | ETA 2.7m
Epoch 259/500 | Batch 80/202 | Rec 0.000730 | Seg 0.328875 | Elapsed 1.7m | ETA 2.5m
Epoch 259/500 | Batch 90/202 | Rec 0.000708 | Seg 0.329779 | Elapsed 1.9m | ETA 2.3m
Epoch 259/500 | Batch 100/202 | Rec 0.000718 | Seg 0.328398 | Elapsed 2.1m | ETA 2.1m
Epoch 259/500 | Batch 110/202 | Rec 0.000750 | Seg 0.337055 | Elapsed 2.3m | ETA 1.9m
Epoch 259/500 | Batch 120/202 | Rec 0.000754 | Seg 0.341216 | Elapsed 2.5m | ETA 1.7m
Epoch 259/500 | Batch 130/202 | Rec 0.000757 | Seg 0.343585 | Elapsed 2.7m | ETA 1.5m
Epoch 259/500 | Batch 140/202 | Rec 0.000747 | Seg 0.341243 | Elapsed 2.9m | ETA 1.3m
Epoch 259/500 | Batch 150/202 | Rec 0.000743 | Seg 0.338685 | Elapsed 3.1m | ETA 1.1m
Epoch 259/500 | Batch 160/202 | Rec 0.000737 | Seg 0.337086 | Elapsed 3.3m | ETA 0.9m
Epoch 259/500 | Batch 170/202 | Rec 0.000728 | Seg 0.332926 | Elapsed 3.5m | ETA 0.7m
Epoch 259/500 | Batch 180/202 | Rec 0.000730 | Seg 0.334900 | Elapsed 3.7m | ETA 0.4m
Epoch 259/500 | Batch 190/202 | Rec 0.000731 | Seg 0.336336 | Elapsed 3.9m | ETA 0.2m
Epoch 259/500 | Batch 200/202 | Rec 0.000727 | Seg 0.334487 | Elapsed 4.1m | ETA 0.0m
Epoch 259/500 | Batch 202/202 | Rec 0.000725 | Seg 0.333308 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:31:24,843 - INFO: Rec loss: 0.0007248039591923761
2026-09-24 08:31:24,844 - INFO: Seg loss: 0.33330777530918027
2026-09-24 08:31:24,844 - INFO: λ_rec: 1
2026-09-24 08:31:24,844 - INFO: λ_seg: 0.0001
2026-09-24 08:32:38,741 - INFO: -------------------Epoch: 259------------------------
2026-09-24 08:32:38,745 - INFO:
Validation stats:
       PSNR      SSIM      MSE
0  38.40263  0.973137  0.00015
2026-09-24 08:32:38,752 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995440  0.997665  0.996737  0.998695  0.995645
real potato   0.592937  0.744411  0.999570  0.593088  0.999513
fake potato   0.749896  0.857026  0.984774  0.758693  0.999816
real apple    0.692544  0.818297  0.874466  0.768996  0.998822
fake apple    0.742656  0.852277  0.958550  0.767297  0.998996
real orange   0.780002  0.876357  0.999259  0.780454  0.999710
fake orange   0.886363  0.939709  0.902093  0.980706  0.999640
real grape    0.672902  0.804423  0.890594  0.733538  0.999256
fake grape    0.867054  0.928744  0.904211  0.954750  0.999458
real lemon    0.384102  0.554972  0.455492  0.710205  0.998662
fake lemon    0.842369  0.914392  0.991737  0.848323  0.999664
real avocado  0.784720  0.879327  0.809077  0.963054  0.999754
fake avocado  0.568715  0.725025  0.999552  0.568860  0.999484
real pepper   0.859107  0.924165  0.962339  0.888995  0.999467
fake pepper   0.851717  0.919872  0.974097  0.871455  0.999638
real plant    0.844363  0.915565  0.912590  0.918660  0.998306
fake plant    0.865044  0.927589  0.957551  0.899540  0.999888
real banana   0.370725  0.540878  0.948264  0.378378  0.998557
fake banana   0.640527  0.780829  0.760091  0.802837  0.999171
real onion    0.641794  0.781772  0.665638  0.947137  0.999522
fake onion    0.919846  0.958200  0.991721  0.926965  0.999949
real unknown  0.750187  0.857216  0.778210  0.954198  0.999949
fake unknown  0.257717  0.409779  0.277900  0.780152  0.998107
total         0.720032  0.822108  0.869327  0.817173  0.999173
total(-bg)    0.707513  0.814128  0.863535  0.808922  0.999333
2026-09-24 08:32:39,302 - INFO: Epoch accounting: {'epoch': 259, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11236511, 64845, 66475, 119746, 206616, 81627, 75956, 112026, 196987, 83511, 44815, 33797, 32920, 216596, 112323, 151087, 19754, 105215, 80089, 88387, 56976, 9263, 42750], 'crops_with_class': [202, 35, 31, 32, 46, 22, 25, 25, 28, 38, 19, 15, 16, 58, 29, 21, 16, 27, 34, 37, 25, 10, 16], 'targeted_crops_by_class': [0, 5, 6, 8, 6, 4, 7, 4, 5, 6, 1, 3, 5, 2, 6, 4, 2, 3, 6, 6, 4, 3, 4], 'sampled_scene_counts': [1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 2, 0, 0, 0, 1, 1, 1, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 0, 0, 0, 2, 1, 2, 0, 1, 1, 3, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 4, 2, 0, 0, 1, 1, 2, 1, 3, 1, 2, 3, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 3, 2, 0, 0, 1, 1, 3, 1, 3, 2, 3, 3, 0, 2, 1, 1, 0, 1, 2, 2, 3, 2, 1, 1, 2, 1, 2, 2, 0, 0, 2, 1, 2, 2, 4, 1, 0, 2, 1, 4, 1, 1, 1, 1, 2, 0, 1, 1, 2, 2, 2, 0, 2], 'learning_rate': 4.761906463078393e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007248039591923761, 'train_segmentation_loss': 0.33330777530918027, 'val_foreground_miou_all22': 0.707513153108333, 'val_psnr_ref1': 38.40262985229492, 'elapsed_seconds': 321.89019989967346, 'peak_cuda_allocated_gib': 7.509288787841797}

Epoch 260/500 | Batch 10/202 | Rec 0.000622 | Seg 0.311141 | Elapsed 0.2m | ETA 3.9m
Epoch 260/500 | Batch 20/202 | Rec 0.000685 | Seg 0.301225 | Elapsed 0.4m | ETA 3.7m
Epoch 260/500 | Batch 30/202 | Rec 0.000758 | Seg 0.312213 | Elapsed 0.6m | ETA 3.5m
Epoch 260/500 | Batch 40/202 | Rec 0.000723 | Seg 0.296004 | Elapsed 0.8m | ETA 3.3m
Epoch 260/500 | Batch 50/202 | Rec 0.000711 | Seg 0.291241 | Elapsed 1.0m | ETA 3.1m
Epoch 260/500 | Batch 60/202 | Rec 0.000733 | Seg 0.313135 | Elapsed 1.2m | ETA 2.9m
Epoch 260/500 | Batch 70/202 | Rec 0.000725 | Seg 0.316108 | Elapsed 1.4m | ETA 2.7m
Epoch 260/500 | Batch 80/202 | Rec 0.000726 | Seg 0.316207 | Elapsed 1.6m | ETA 2.5m
Epoch 260/500 | Batch 90/202 | Rec 0.000711 | Seg 0.310116 | Elapsed 1.8m | ETA 2.3m
Epoch 260/500 | Batch 100/202 | Rec 0.000710 | Seg 0.302998 | Elapsed 2.0m | ETA 2.1m
Epoch 260/500 | Batch 110/202 | Rec 0.000705 | Seg 0.301791 | Elapsed 2.2m | ETA 1.9m
Epoch 260/500 | Batch 120/202 | Rec 0.000707 | Seg 0.305428 | Elapsed 2.4m | ETA 1.7m
Epoch 260/500 | Batch 130/202 | Rec 0.000708 | Seg 0.310502 | Elapsed 2.6m | ETA 1.5m
Epoch 260/500 | Batch 140/202 | Rec 0.000699 | Seg 0.307138 | Elapsed 2.8m | ETA 1.3m
Epoch 260/500 | Batch 150/202 | Rec 0.000699 | Seg 0.310842 | Elapsed 3.0m | ETA 1.1m
Epoch 260/500 | Batch 160/202 | Rec 0.000695 | Seg 0.311133 | Elapsed 3.2m | ETA 0.9m
Epoch 260/500 | Batch 170/202 | Rec 0.000695 | Seg 0.310505 | Elapsed 3.4m | ETA 0.6m
Epoch 260/500 | Batch 180/202 | Rec 0.000697 | Seg 0.309929 | Elapsed 3.6m | ETA 0.4m
Epoch 260/500 | Batch 190/202 | Rec 0.000696 | Seg 0.312404 | Elapsed 3.8m | ETA 0.2m
Epoch 260/500 | Batch 200/202 | Rec 0.000698 | Seg 0.312490 | Elapsed 4.1m | ETA 0.0m
Epoch 260/500 | Batch 202/202 | Rec 0.000702 | Seg 0.311680 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:36:44,987 - INFO: Rec loss: 0.0007023811248842267
2026-09-24 08:36:44,987 - INFO: Seg loss: 0.3116797334745084
2026-09-24 08:36:44,987 - INFO: λ_rec: 1
2026-09-24 08:36:44,987 - INFO: λ_seg: 0.0001
2026-09-24 08:37:58,127 - INFO: -------------------Epoch: 260------------------------
2026-09-24 08:37:58,131 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.399579  0.972711  0.00015
2026-09-24 08:37:58,138 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995336  0.997612  0.996485  0.998843  0.995544
real potato   0.856659  0.922747  0.981043  0.871079  0.999826
fake potato   0.850686  0.919270  0.958618  0.883117  0.999887
real apple    0.720266  0.837339  0.935378  0.757983  0.998984
fake apple    0.586046  0.738956  0.994531  0.587941  0.998432
real orange   0.684658  0.812767  0.988068  0.690366  0.999581
fake orange   0.843880  0.915281  0.865779  0.970899  0.999486
real grape    0.733790  0.846408  0.863177  0.830373  0.999371
fake grape    0.871644  0.931371  0.926743  0.936147  0.999490
real lemon    0.410924  0.582439  0.533225  0.641781  0.998919
fake lemon    0.838042  0.911836  0.999227  0.838586  0.999657
real avocado  0.806005  0.892534  0.836685  0.956486  0.999786
fake avocado  0.464559  0.634358  0.999451  0.464677  0.999359
real pepper   0.871650  0.931374  0.953311  0.910521  0.999510
fake pepper   0.881151  0.936771  0.967594  0.907944  0.999708
real plant    0.846428  0.916777  0.955608  0.881072  0.998401
fake plant    0.795167  0.885848  0.848001  0.927339  0.999810
real banana   0.616517  0.762724  0.915051  0.653945  0.999086
fake banana   0.645200  0.784292  0.724404  0.855093  0.999135
real onion    0.695134  0.820103  0.718440  0.955413  0.999621
fake onion    0.943306  0.970776  0.984340  0.957678  0.999964
real unknown  0.795269  0.885911  0.845620  0.930343  0.999962
fake unknown  0.212391  0.350331  0.229699  0.738138  0.997694
total         0.737596  0.834253  0.870456  0.832425  0.999183
total(-bg)    0.725881  0.826828  0.864727  0.824860  0.999349
2026-09-24 08:37:58,660 - INFO: Epoch accounting: {'epoch': 260, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11318985, 53030, 59741, 128950, 131984, 102753, 58114, 152093, 171744, 80025, 70150, 38272, 38304, 204718, 164875, 97833, 18995, 78498, 76585, 74240, 52755, 9131, 56497], 'crops_with_class': [202, 32, 28, 34, 35, 34, 22, 32, 32, 33, 27, 14, 14, 53, 39, 20, 14, 23, 31, 35, 24, 12, 21], 'targeted_crops_by_class': [0, 8, 9, 0, 6, 7, 2, 5, 6, 8, 1, 6, 6, 4, 2, 8, 1, 3, 4, 5, 3, 7, 3], 'sampled_scene_counts': [0, 1, 1, 1, 0, 1, 0, 0, 2, 2, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 2, 0, 0, 0, 3, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 2, 1, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 3, 1, 0, 0, 0, 0, 1, 1, 0, 3, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 2, 1, 1, 0, 1, 1, 0, 3, 1, 2, 2, 2, 0, 2, 1, 1, 0, 3, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1, 3, 6, 2, 2, 3, 1, 1, 1, 1, 1, 2, 0, 0, 1, 2, 4, 3, 0, 3, 2, 1, 1, 2, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 1, 0, 1, 0, 1, 2, 1, 1, 0, 1, 4, 1, 1, 4, 2, 3, 1, 1, 1, 1, 1, 1, 2, 0, 2], 'learning_rate': 4.7306138092708964e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0007023811248842267, 'train_segmentation_loss': 0.3116797334745084, 'val_foreground_miou_all22': 0.7258805372852856, 'val_psnr_ref1': 38.39957855224609, 'elapsed_seconds': 319.34801983833313, 'peak_cuda_allocated_gib': 7.511539459228516}

Epoch 261/500 | Batch 10/202 | Rec 0.000785 | Seg 0.388631 | Elapsed 0.2m | ETA 3.9m
Epoch 261/500 | Batch 20/202 | Rec 0.000752 | Seg 0.359237 | Elapsed 0.4m | ETA 3.7m
Epoch 261/500 | Batch 30/202 | Rec 0.000707 | Seg 0.328975 | Elapsed 0.6m | ETA 3.5m
Epoch 261/500 | Batch 40/202 | Rec 0.000695 | Seg 0.328911 | Elapsed 0.8m | ETA 3.3m
Epoch 261/500 | Batch 50/202 | Rec 0.000701 | Seg 0.326436 | Elapsed 1.0m | ETA 3.1m
Epoch 261/500 | Batch 60/202 | Rec 0.000681 | Seg 0.324028 | Elapsed 1.2m | ETA 2.9m
Epoch 261/500 | Batch 70/202 | Rec 0.000687 | Seg 0.324090 | Elapsed 1.4m | ETA 2.7m
Epoch 261/500 | Batch 80/202 | Rec 0.000712 | Seg 0.332733 | Elapsed 1.6m | ETA 2.5m
Epoch 261/500 | Batch 90/202 | Rec 0.000704 | Seg 0.324469 | Elapsed 1.8m | ETA 2.3m
Epoch 261/500 | Batch 100/202 | Rec 0.000696 | Seg 0.317832 | Elapsed 2.0m | ETA 2.1m
Epoch 261/500 | Batch 110/202 | Rec 0.000705 | Seg 0.319148 | Elapsed 2.2m | ETA 1.9m
Epoch 261/500 | Batch 120/202 | Rec 0.000706 | Seg 0.323734 | Elapsed 2.4m | ETA 1.7m
Epoch 261/500 | Batch 130/202 | Rec 0.000714 | Seg 0.322451 | Elapsed 2.6m | ETA 1.5m
Epoch 261/500 | Batch 140/202 | Rec 0.000715 | Seg 0.323728 | Elapsed 2.8m | ETA 1.3m
Epoch 261/500 | Batch 150/202 | Rec 0.000703 | Seg 0.319601 | Elapsed 3.0m | ETA 1.1m
Epoch 261/500 | Batch 160/202 | Rec 0.000693 | Seg 0.319393 | Elapsed 3.3m | ETA 0.9m
Epoch 261/500 | Batch 170/202 | Rec 0.000692 | Seg 0.318828 | Elapsed 3.5m | ETA 0.7m
Epoch 261/500 | Batch 180/202 | Rec 0.000696 | Seg 0.314422 | Elapsed 3.7m | ETA 0.4m
Epoch 261/500 | Batch 190/202 | Rec 0.000706 | Seg 0.317397 | Elapsed 3.9m | ETA 0.2m
Epoch 261/500 | Batch 200/202 | Rec 0.000704 | Seg 0.316779 | Elapsed 4.1m | ETA 0.0m
Epoch 261/500 | Batch 202/202 | Rec 0.000705 | Seg 0.316771 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:42:04,969 - INFO: Rec loss: 0.0007050300908412111
2026-09-24 08:42:04,969 - INFO: Seg loss: 0.31677074361555646
2026-09-24 08:42:04,969 - INFO: λ_rec: 1
2026-09-24 08:42:04,969 - INFO: λ_seg: 0.0001
2026-09-24 08:43:18,009 - INFO: -------------------Epoch: 261------------------------
2026-09-24 08:43:18,014 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.403739  0.972813  0.00015
2026-09-24 08:43:18,020 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995356  0.997623  0.996463  0.998886  0.995564
real potato   0.811939  0.896160  0.972824  0.830783  0.999770
fake potato   0.937285  0.967577  0.964806  0.970465  0.999953
real apple    0.747160  0.855236  0.930608  0.791243  0.999076
fake apple    0.706859  0.828208  0.957573  0.729712  0.998857
real orange   0.591018  0.742897  0.982292  0.597383  0.999455
fake orange   0.813944  0.897381  0.833082  0.972551  0.999364
real grape    0.680745  0.810002  0.907517  0.731492  0.999284
fake grape    0.876622  0.934205  0.929242  0.939323  0.999511
real lemon    0.386489  0.557460  0.454360  0.721241  0.998654
fake lemon    0.851671  0.919845  0.993557  0.856401  0.999684
real avocado  0.855360  0.921992  0.889992  0.956486  0.999850
fake avocado  0.688042  0.815147  0.999630  0.688217  0.999627
real pepper   0.873608  0.932491  0.932618  0.932463  0.999507
fake pepper   0.848030  0.917717  0.968171  0.872351  0.999627
real plant    0.845078  0.915985  0.930382  0.902124  0.998346
fake plant    0.828186  0.905969  0.917781  0.894555  0.999852
real banana   0.408917  0.580427  0.937320  0.420413  0.998634
fake banana   0.661065  0.795903  0.777146  0.815693  0.999231
real onion    0.666234  0.799639  0.689019  0.952711  0.999569
fake onion    0.937156  0.967509  0.987412  0.948488  0.999960
real unknown  0.624680  0.768940  0.654387  0.932252  0.999910
fake unknown  0.281118  0.438819  0.325730  0.672401  0.998551
total         0.735503  0.833354  0.866605  0.831636  0.999210
total(-bg)    0.723691  0.825887  0.860702  0.824034  0.999376
2026-09-24 08:43:18,564 - INFO: Epoch accounting: {'epoch': 261, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11334413, 62611, 61049, 102915, 107725, 75540, 87498, 123487, 153098, 75407, 46289, 30784, 39925, 232353, 107738, 200388, 23614, 82225, 74753, 97783, 75959, 10432, 32286], 'crops_with_class': [202, 38, 29, 27, 32, 25, 28, 25, 29, 33, 18, 12, 16, 56, 34, 20, 23, 23, 31, 42, 30, 13, 15], 'targeted_crops_by_class': [0, 8, 7, 2, 5, 3, 3, 3, 5, 6, 4, 4, 7, 3, 3, 9, 3, 2, 5, 5, 5, 5, 3], 'sampled_scene_counts': [1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 2, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 0, 2, 0, 2, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 0, 2, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1, 2, 0, 0, 0, 1, 2, 1, 1, 0, 0, 0, 2, 0, 2, 2, 1, 3, 6, 4, 0, 2, 0, 1, 2, 4, 0, 0, 3, 1, 2, 1, 2, 3, 1, 3, 0, 1, 2, 2, 1, 0, 1, 5, 0, 1, 1, 2, 2, 2, 1, 1, 2, 0, 0, 4, 2, 0, 4, 1, 0, 2, 2, 2, 0, 2, 0, 1, 0, 2, 2, 2, 2, 2, 4], 'learning_rate': 4.6993322838475444e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007050300908412111, 'train_segmentation_loss': 0.31677074361555646, 'val_foreground_miou_all22': 0.7236911404098327, 'val_psnr_ref1': 38.40373886108399, 'elapsed_seconds': 319.8967921733856, 'peak_cuda_allocated_gib': 7.517520904541016}

Epoch 262/500 | Batch 10/202 | Rec 0.000698 | Seg 0.383098 | Elapsed 0.2m | ETA 3.8m
Epoch 262/500 | Batch 20/202 | Rec 0.000658 | Seg 0.311527 | Elapsed 0.4m | ETA 3.7m
Epoch 262/500 | Batch 30/202 | Rec 0.000644 | Seg 0.288798 | Elapsed 0.6m | ETA 3.5m
Epoch 262/500 | Batch 40/202 | Rec 0.000645 | Seg 0.296783 | Elapsed 0.8m | ETA 3.3m
Epoch 262/500 | Batch 50/202 | Rec 0.000636 | Seg 0.300511 | Elapsed 1.0m | ETA 3.1m
Epoch 262/500 | Batch 60/202 | Rec 0.000651 | Seg 0.300839 | Elapsed 1.2m | ETA 2.9m
Epoch 262/500 | Batch 70/202 | Rec 0.000646 | Seg 0.297708 | Elapsed 1.4m | ETA 2.7m
Epoch 262/500 | Batch 80/202 | Rec 0.000666 | Seg 0.308117 | Elapsed 1.6m | ETA 2.5m
Epoch 262/500 | Batch 90/202 | Rec 0.000684 | Seg 0.321633 | Elapsed 1.8m | ETA 2.3m
Epoch 262/500 | Batch 100/202 | Rec 0.000685 | Seg 0.323719 | Elapsed 2.0m | ETA 2.1m
Epoch 262/500 | Batch 110/202 | Rec 0.000691 | Seg 0.321049 | Elapsed 2.2m | ETA 1.9m
Epoch 262/500 | Batch 120/202 | Rec 0.000676 | Seg 0.317051 | Elapsed 2.4m | ETA 1.7m
Epoch 262/500 | Batch 130/202 | Rec 0.000678 | Seg 0.316988 | Elapsed 2.6m | ETA 1.5m
Epoch 262/500 | Batch 140/202 | Rec 0.000680 | Seg 0.314295 | Elapsed 2.9m | ETA 1.3m
Epoch 262/500 | Batch 150/202 | Rec 0.000688 | Seg 0.313971 | Elapsed 3.1m | ETA 1.1m
Epoch 262/500 | Batch 160/202 | Rec 0.000690 | Seg 0.316426 | Elapsed 3.3m | ETA 0.9m
Epoch 262/500 | Batch 170/202 | Rec 0.000703 | Seg 0.321636 | Elapsed 3.5m | ETA 0.7m
Epoch 262/500 | Batch 180/202 | Rec 0.000700 | Seg 0.320113 | Elapsed 3.7m | ETA 0.4m
Epoch 262/500 | Batch 190/202 | Rec 0.000693 | Seg 0.318439 | Elapsed 3.9m | ETA 0.2m
Epoch 262/500 | Batch 200/202 | Rec 0.000696 | Seg 0.317939 | Elapsed 4.1m | ETA 0.0m
Epoch 262/500 | Batch 202/202 | Rec 0.000698 | Seg 0.319239 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:47:26,155 - INFO: Rec loss: 0.0006984489051985905
2026-09-24 08:47:26,156 - INFO: Seg loss: 0.3192386405524051
2026-09-24 08:47:26,156 - INFO: λ_rec: 1
2026-09-24 08:47:26,156 - INFO: λ_seg: 0.0001
2026-09-24 08:48:41,465 - INFO: -------------------Epoch: 262------------------------
2026-09-24 08:48:41,468 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.322269  0.97286  0.000153
2026-09-24 08:48:41,475 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995020  0.997454  0.996114  0.998898  0.995240
real potato   0.872475  0.931845  0.897297  0.969268  0.999830
fake potato   0.914827  0.955469  0.931384  0.980938  0.999933
real apple    0.648571  0.786780  0.995532  0.650464  0.998784
fake apple    0.548885  0.708703  0.995685  0.550194  0.998293
real orange   0.554344  0.713237  0.984308  0.559287  0.999408
fake orange   0.797805  0.887483  0.821668  0.964876  0.999300
real grape    0.648964  0.787067  0.821454  0.755536  0.999147
fake grape    0.869101  0.929917  0.920478  0.939653  0.999476
real lemon    0.490498  0.658117  0.705751  0.616593  0.999247
fake lemon    0.804370  0.891530  0.999731  0.804544  0.999586
real avocado  0.912908  0.954422  0.994659  0.917406  0.999919
fake avocado  0.097934  0.178381  1.000000  0.097934  0.998921
real pepper   0.901826  0.948329  0.951045  0.945728  0.999623
fake pepper   0.900540  0.947617  0.966955  0.929134  0.999755
real plant    0.833321  0.909034  0.944296  0.876403  0.998247
fake plant    0.846714  0.916945  0.970053  0.869440  0.999875
real banana   0.692288  0.818119  0.916596  0.738829  0.999262
fake banana   0.604358  0.753346  0.678657  0.846632  0.998980
real onion    0.633386  0.775501  0.653548  0.953555  0.999501
fake onion    0.928333  0.962785  0.983602  0.942926  0.999954
real unknown  0.631191  0.773853  0.678906  0.899809  0.999916
fake unknown  0.169312  0.289559  0.182210  0.705179  0.997085
total         0.708564  0.803282  0.869127  0.804923  0.999099
total(-bg)    0.695543  0.794456  0.863355  0.796106  0.999275
2026-09-24 08:48:42,005 - INFO: Epoch accounting: {'epoch': 262, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11321653, 53162, 44768, 123947, 129379, 71242, 53530, 117017, 219029, 73949, 50886, 44601, 35195, 223991, 132584, 166690, 30610, 104853, 65321, 63520, 56518, 10503, 45324], 'crops_with_class': [202, 27, 19, 30, 31, 19, 18, 22, 37, 31, 23, 15, 15, 59, 34, 22, 24, 30, 27, 33, 23, 12, 18], 'targeted_crops_by_class': [0, 4, 3, 7, 5, 2, 4, 5, 5, 8, 3, 4, 4, 5, 7, 3, 2, 7, 4, 4, 1, 6, 2], 'sampled_scene_counts': [1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 2, 0, 2, 0, 1, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 4, 0, 0, 1, 0, 1, 0, 0, 3, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 3, 2, 1, 2, 1, 2, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 2, 1, 1, 2, 2, 1, 2, 2, 0, 1, 1, 4, 1, 2, 1, 3, 3, 0, 0, 4, 2, 1, 1, 0, 0, 1, 1, 0, 0, 2, 3, 3, 2, 1, 3, 2, 3, 1, 1, 0, 2, 0, 2, 1, 0, 1, 1, 1, 6, 0, 0, 2, 1, 0, 0, 0, 1, 1, 2, 3, 3, 0], 'learning_rate': 4.668063121749396e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006984489051985905, 'train_segmentation_loss': 0.3192386405524051, 'val_foreground_miou_all22': 0.6955432605554913, 'val_psnr_ref1': 38.3222689819336, 'elapsed_seconds': 323.43268632888794, 'peak_cuda_allocated_gib': 7.510440826416016}

Epoch 263/500 | Batch 10/202 | Rec 0.000689 | Seg 0.321279 | Elapsed 0.2m | ETA 3.9m
Epoch 263/500 | Batch 20/202 | Rec 0.000726 | Seg 0.319612 | Elapsed 0.4m | ETA 3.7m
Epoch 263/500 | Batch 30/202 | Rec 0.000695 | Seg 0.322842 | Elapsed 0.6m | ETA 3.5m
Epoch 263/500 | Batch 40/202 | Rec 0.000712 | Seg 0.323061 | Elapsed 0.8m | ETA 3.3m
Epoch 263/500 | Batch 50/202 | Rec 0.000699 | Seg 0.325214 | Elapsed 1.0m | ETA 3.1m
Epoch 263/500 | Batch 60/202 | Rec 0.000706 | Seg 0.326458 | Elapsed 1.2m | ETA 2.9m
Epoch 263/500 | Batch 70/202 | Rec 0.000695 | Seg 0.319205 | Elapsed 1.4m | ETA 2.7m
Epoch 263/500 | Batch 80/202 | Rec 0.000698 | Seg 0.317768 | Elapsed 1.6m | ETA 2.5m
Epoch 263/500 | Batch 90/202 | Rec 0.000720 | Seg 0.326875 | Elapsed 1.8m | ETA 2.3m
Epoch 263/500 | Batch 100/202 | Rec 0.000734 | Seg 0.331277 | Elapsed 2.0m | ETA 2.1m
Epoch 263/500 | Batch 110/202 | Rec 0.000722 | Seg 0.324767 | Elapsed 2.2m | ETA 1.9m
Epoch 263/500 | Batch 120/202 | Rec 0.000710 | Seg 0.323405 | Elapsed 2.4m | ETA 1.7m
Epoch 263/500 | Batch 130/202 | Rec 0.000719 | Seg 0.326281 | Elapsed 2.6m | ETA 1.5m
Epoch 263/500 | Batch 140/202 | Rec 0.000714 | Seg 0.325023 | Elapsed 2.8m | ETA 1.2m
Epoch 263/500 | Batch 150/202 | Rec 0.000705 | Seg 0.321907 | Elapsed 3.0m | ETA 1.0m
Epoch 263/500 | Batch 160/202 | Rec 0.000704 | Seg 0.322502 | Elapsed 3.2m | ETA 0.8m
Epoch 263/500 | Batch 170/202 | Rec 0.000699 | Seg 0.318934 | Elapsed 3.4m | ETA 0.6m
Epoch 263/500 | Batch 180/202 | Rec 0.000694 | Seg 0.315984 | Elapsed 3.6m | ETA 0.4m
Epoch 263/500 | Batch 190/202 | Rec 0.000692 | Seg 0.314869 | Elapsed 3.9m | ETA 0.2m
Epoch 263/500 | Batch 200/202 | Rec 0.000700 | Seg 0.323130 | Elapsed 4.1m | ETA 0.0m
Epoch 263/500 | Batch 202/202 | Rec 0.000702 | Seg 0.324756 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:52:47,804 - INFO: Rec loss: 0.0007021536426457327
2026-09-24 08:52:47,804 - INFO: Seg loss: 0.32475607322141675
2026-09-24 08:52:47,804 - INFO: λ_rec: 1
2026-09-24 08:52:47,805 - INFO: λ_seg: 0.0001
2026-09-24 08:54:02,416 - INFO: -------------------Epoch: 263------------------------
2026-09-24 08:54:02,420 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.355953  0.97285  0.000152
2026-09-24 08:54:02,426 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995613  0.997752  0.996765  0.998840  0.995810
real potato   0.922269  0.959513  0.992236  0.928972  0.999906
fake potato   0.933055  0.965318  0.947549  0.983871  0.999949
real apple    0.815627  0.898402  0.958068  0.845820  0.999340
fake apple    0.604603  0.753539  0.995751  0.606167  0.998503
real orange   0.797380  0.887220  0.959973  0.824803  0.999724
fake orange   0.882529  0.937550  0.919326  0.956614  0.999635
real grape    0.734608  0.846953  0.968582  0.752540  0.999432
fake grape    0.877869  0.934913  0.929795  0.940189  0.999516
real lemon    0.489858  0.657541  0.569676  0.777590  0.999048
fake lemon    0.803910  0.891248  0.991345  0.809592  0.999582
real avocado  0.881187  0.936791  0.947139  0.926765  0.999884
fake avocado  0.537103  0.698805  0.993419  0.539021  0.999444
real pepper   0.867229  0.928844  0.910099  0.948482  0.999469
fake pepper   0.822864  0.902775  0.948664  0.861212  0.999558
real plant    0.856007  0.922368  0.948008  0.898172  0.998489
fake plant    0.810811  0.895472  0.866990  0.925997  0.999828
real banana   0.607801  0.756016  0.888196  0.658156  0.999046
fake banana   0.605691  0.754381  0.684410  0.840411  0.998994
real onion    0.663432  0.797617  0.715897  0.900524  0.999587
fake onion    0.820816  0.901542  0.840192  0.972672  0.999866
real unknown  0.843290  0.914933  0.901017  0.929389  0.999972
fake unknown  0.199066  0.331994  0.230391  0.594169  0.997986
total         0.755331  0.846586  0.874065  0.844347  0.999242
total(-bg)    0.744409  0.839715  0.868487  0.837324  0.999398
2026-09-24 08:54:02,965 - INFO: Epoch accounting: {'epoch': 263, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11278601, 57491, 74371, 105725, 126125, 75747, 69715, 160551, 176014, 74535, 68184, 23796, 19524, 234591, 111450, 175839, 21319, 94621, 91558, 62050, 86968, 10806, 38691], 'crops_with_class': [202, 29, 34, 30, 30, 27, 25, 30, 34, 31, 33, 9, 9, 60, 36, 21, 18, 24, 37, 35, 35, 14, 19], 'targeted_crops_by_class': [0, 5, 4, 3, 3, 3, 2, 4, 6, 9, 3, 2, 5, 4, 4, 10, 3, 5, 6, 4, 9, 7, 4], 'sampled_scene_counts': [0, 0, 2, 0, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 0, 1, 1, 2, 0, 0, 1, 3, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 2, 0, 1, 1, 3, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 4, 0, 1, 2, 0, 2, 1, 1, 0, 2, 2, 0, 0, 4, 2, 0, 0, 1, 1, 2, 2, 3, 2, 2, 2, 2, 1, 1, 3, 2, 1, 1, 1, 3, 2, 1, 1, 1, 1, 0, 1, 1, 2, 0, 2, 0, 1, 2, 1, 1, 2, 3, 2, 0, 3, 1, 1, 2, 2, 2, 2, 0, 2, 0, 2, 1, 2, 5, 1, 3], 'learning_rate': 4.6368075574294294e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007021536426457327, 'train_segmentation_loss': 0.32475607322141675, 'val_foreground_miou_all22': 0.7444092932636305, 'val_psnr_ref1': 38.35595260620117, 'elapsed_seconds': 320.95165491104126, 'peak_cuda_allocated_gib': 7.506381988525391}

Epoch 264/500 | Batch 10/202 | Rec 0.000797 | Seg 0.296206 | Elapsed 0.2m | ETA 3.9m
Epoch 264/500 | Batch 20/202 | Rec 0.000704 | Seg 0.305213 | Elapsed 0.4m | ETA 3.6m
Epoch 264/500 | Batch 30/202 | Rec 0.000663 | Seg 0.283337 | Elapsed 0.6m | ETA 3.5m
Epoch 264/500 | Batch 40/202 | Rec 0.000649 | Seg 0.290974 | Elapsed 0.8m | ETA 3.3m
Epoch 264/500 | Batch 50/202 | Rec 0.000665 | Seg 0.296276 | Elapsed 1.0m | ETA 3.1m
Epoch 264/500 | Batch 60/202 | Rec 0.000700 | Seg 0.316643 | Elapsed 1.2m | ETA 2.9m
Epoch 264/500 | Batch 70/202 | Rec 0.000717 | Seg 0.321328 | Elapsed 1.4m | ETA 2.7m
Epoch 264/500 | Batch 80/202 | Rec 0.000713 | Seg 0.317504 | Elapsed 1.6m | ETA 2.5m
Epoch 264/500 | Batch 90/202 | Rec 0.000723 | Seg 0.328787 | Elapsed 1.8m | ETA 2.3m
Epoch 264/500 | Batch 100/202 | Rec 0.000728 | Seg 0.333904 | Elapsed 2.0m | ETA 2.1m
Epoch 264/500 | Batch 110/202 | Rec 0.000714 | Seg 0.328057 | Elapsed 2.2m | ETA 1.9m
Epoch 264/500 | Batch 120/202 | Rec 0.000711 | Seg 0.323379 | Elapsed 2.4m | ETA 1.7m
Epoch 264/500 | Batch 130/202 | Rec 0.000697 | Seg 0.315571 | Elapsed 2.6m | ETA 1.5m
Epoch 264/500 | Batch 140/202 | Rec 0.000689 | Seg 0.314603 | Elapsed 2.8m | ETA 1.3m
Epoch 264/500 | Batch 150/202 | Rec 0.000690 | Seg 0.315727 | Elapsed 3.1m | ETA 1.1m
Epoch 264/500 | Batch 160/202 | Rec 0.000692 | Seg 0.313634 | Elapsed 3.3m | ETA 0.9m
Epoch 264/500 | Batch 170/202 | Rec 0.000688 | Seg 0.310601 | Elapsed 3.5m | ETA 0.7m
Epoch 264/500 | Batch 180/202 | Rec 0.000683 | Seg 0.307436 | Elapsed 3.7m | ETA 0.4m
Epoch 264/500 | Batch 190/202 | Rec 0.000682 | Seg 0.310992 | Elapsed 3.9m | ETA 0.2m
Epoch 264/500 | Batch 200/202 | Rec 0.000692 | Seg 0.310385 | Elapsed 4.1m | ETA 0.0m
Epoch 264/500 | Batch 202/202 | Rec 0.000692 | Seg 0.310127 | Elapsed 4.1m | ETA 0.0m

2026-09-24 08:58:10,715 - INFO: Rec loss: 0.0006920312770318452
2026-09-24 08:58:10,716 - INFO: Seg loss: 0.3101274658105161
2026-09-24 08:58:10,716 - INFO: λ_rec: 1
2026-09-24 08:58:10,716 - INFO: λ_seg: 0.0001
2026-09-24 08:59:26,063 - INFO: -------------------Epoch: 264------------------------
2026-09-24 08:59:26,067 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.43799  0.973201  0.000149
2026-09-24 08:59:26,074 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995495  0.997693  0.996897  0.998590  0.995698
real potato   0.840452  0.913261  0.982667  0.853099  0.999806
fake potato   0.891304  0.942479  0.967365  0.918936  0.999918
real apple    0.763576  0.865891  0.951096  0.794781  0.999151
fake apple    0.666627  0.799923  0.989809  0.671233  0.998733
real orange   0.906546  0.950933  0.998726  0.907596  0.999877
fake orange   0.930159  0.963766  0.957354  0.970366  0.999791
real grape    0.615622  0.762039  0.939387  0.641087  0.999164
fake grape    0.881811  0.937144  0.958831  0.916512  0.999546
real lemon    0.511855  0.677072  0.609002  0.762399  0.999146
fake lemon    0.833874  0.909363  0.999654  0.834115  0.999648
real avocado  0.921028  0.958841  0.964143  0.953695  0.999924
fake avocado  0.476603  0.645496  0.999733  0.476664  0.999374
real pepper   0.893342  0.943617  0.935371  0.952111  0.999584
fake pepper   0.909627  0.952625  0.990601  0.917547  0.999783
real plant    0.845232  0.916075  0.913499  0.918767  0.998317
fake plant    0.865019  0.927575  0.897758  0.959548  0.999881
real banana   0.577348  0.732000  0.890045  0.621690  0.998977
fake banana   0.669207  0.801776  0.762939  0.844891  0.999232
real onion    0.613733  0.760590  0.625354  0.970613  0.999448
fake onion    0.942400  0.970296  0.987725  0.953567  0.999963
real unknown  0.678474  0.808393  0.703390  0.950382  0.999928
fake unknown  0.240973  0.388326  0.253794  0.826693  0.997806
total         0.759579  0.848921  0.881528  0.852821  0.999248
total(-bg)    0.748855  0.842158  0.876284  0.846195  0.999409
2026-09-24 08:59:26,611 - INFO: Epoch accounting: {'epoch': 264, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11366137, 45684, 47996, 162192, 143298, 93588, 83170, 131158, 191255, 65401, 58017, 39302, 43148, 169170, 98297, 151882, 29080, 91167, 67626, 65013, 41322, 9993, 44376], 'crops_with_class': [202, 26, 24, 44, 34, 26, 26, 27, 36, 30, 24, 14, 17, 42, 26, 20, 24, 26, 29, 28, 20, 10, 19], 'targeted_crops_by_class': [0, 2, 4, 10, 5, 3, 7, 3, 5, 3, 0, 3, 9, 2, 2, 5, 7, 2, 3, 6, 7, 4, 4], 'sampled_scene_counts': [1, 3, 1, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 0, 2, 2, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 2, 2, 1, 0, 2, 2, 0, 0, 1, 0, 1, 2, 0, 0, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 0, 0, 2, 2, 2, 3, 1, 0, 2, 1, 1, 1, 0, 1, 2, 0, 0, 2, 1, 0, 2, 0, 1, 0, 2, 0, 2, 0, 3, 1, 1, 1, 2, 1, 2, 3, 1, 1, 2, 0, 3, 1, 3, 3, 1, 1, 0, 1, 2, 1, 1, 0, 1, 3, 1, 2, 1, 2, 1, 0, 1, 1, 1, 1, 3, 1, 0, 1, 1, 1, 2, 1, 3, 1, 1, 0, 1, 1, 0, 2, 0, 3, 1], 'learning_rate': 4.605566824803809e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006920312770318452, 'train_segmentation_loss': 0.3101274658105161, 'val_foreground_miou_all22': 0.7488551597907062, 'val_psnr_ref1': 38.437989959716795, 'elapsed_seconds': 323.63734436035156, 'peak_cuda_allocated_gib': 7.5111846923828125}

Epoch 265/500 | Batch 10/202 | Rec 0.000511 | Seg 0.269094 | Elapsed 0.2m | ETA 4.0m
Epoch 265/500 | Batch 20/202 | Rec 0.000574 | Seg 0.266240 | Elapsed 0.4m | ETA 3.8m
Epoch 265/500 | Batch 30/202 | Rec 0.000610 | Seg 0.289570 | Elapsed 0.6m | ETA 3.6m
Epoch 265/500 | Batch 40/202 | Rec 0.000672 | Seg 0.293293 | Elapsed 0.8m | ETA 3.3m
Epoch 265/500 | Batch 50/202 | Rec 0.000652 | Seg 0.284655 | Elapsed 1.0m | ETA 3.1m
Epoch 265/500 | Batch 60/202 | Rec 0.000695 | Seg 0.309080 | Elapsed 1.2m | ETA 2.9m
Epoch 265/500 | Batch 70/202 | Rec 0.000724 | Seg 0.310624 | Elapsed 1.4m | ETA 2.7m
Epoch 265/500 | Batch 80/202 | Rec 0.000715 | Seg 0.310760 | Elapsed 1.6m | ETA 2.5m
Epoch 265/500 | Batch 90/202 | Rec 0.000709 | Seg 0.306475 | Elapsed 1.8m | ETA 2.3m
Epoch 265/500 | Batch 100/202 | Rec 0.000708 | Seg 0.307512 | Elapsed 2.0m | ETA 2.1m
Epoch 265/500 | Batch 110/202 | Rec 0.000707 | Seg 0.310244 | Elapsed 2.2m | ETA 1.9m
Epoch 265/500 | Batch 120/202 | Rec 0.000713 | Seg 0.315355 | Elapsed 2.4m | ETA 1.7m
Epoch 265/500 | Batch 130/202 | Rec 0.000719 | Seg 0.319781 | Elapsed 2.6m | ETA 1.5m
Epoch 265/500 | Batch 140/202 | Rec 0.000716 | Seg 0.318894 | Elapsed 2.8m | ETA 1.3m
Epoch 265/500 | Batch 150/202 | Rec 0.000720 | Seg 0.320321 | Elapsed 3.0m | ETA 1.1m
Epoch 265/500 | Batch 160/202 | Rec 0.000721 | Seg 0.325326 | Elapsed 3.2m | ETA 0.8m
Epoch 265/500 | Batch 170/202 | Rec 0.000718 | Seg 0.325235 | Elapsed 3.4m | ETA 0.6m
Epoch 265/500 | Batch 180/202 | Rec 0.000711 | Seg 0.322579 | Elapsed 3.6m | ETA 0.4m
Epoch 265/500 | Batch 190/202 | Rec 0.000712 | Seg 0.325138 | Elapsed 3.8m | ETA 0.2m
Epoch 265/500 | Batch 200/202 | Rec 0.000724 | Seg 0.329726 | Elapsed 4.0m | ETA 0.0m
Epoch 265/500 | Batch 202/202 | Rec 0.000723 | Seg 0.329248 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:03:31,621 - INFO: Rec loss: 0.0007231822062317181
2026-09-24 09:03:31,621 - INFO: Seg loss: 0.32924779714776736
2026-09-24 09:03:31,621 - INFO: λ_rec: 1
2026-09-24 09:03:31,622 - INFO: λ_seg: 0.0001
2026-09-24 09:04:46,850 - INFO: -------------------Epoch: 265------------------------
2026-09-24 09:04:46,854 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.169222  0.97221  0.000159
2026-09-24 09:04:46,861 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995703  0.997797  0.996981  0.998715  0.995897
real potato   0.175465  0.298521  1.000000  0.175465  0.999013
fake potato   0.613056  0.760070  0.973194  0.623586  0.999713
real apple    0.615816  0.762185  0.726090  0.802167  0.998273
fake apple    0.692722  0.818422  0.953358  0.717022  0.998799
real orange   0.925810  0.961426  0.999500  0.926239  0.999902
fake orange   0.944065  0.971178  0.970014  0.972444  0.999835
real grape    0.652441  0.789621  0.949394  0.675948  0.999248
fake grape    0.860693  0.925082  0.914688  0.935817  0.999440
real lemon    0.324746  0.490234  0.356318  0.785640  0.998080
fake lemon    0.842884  0.914695  0.994830  0.846592  0.999666
real avocado  0.794696  0.885555  0.829699  0.949589  0.999772
fake avocado  0.288773  0.448101  0.997798  0.288957  0.999148
real pepper   0.846886  0.917046  0.906885  0.927540  0.999387
fake pepper   0.827663  0.905657  0.996465  0.830101  0.999588
real plant    0.854359  0.921410  0.919222  0.923709  0.998425
fake plant    0.847067  0.917152  0.932277  0.902607  0.999870
real banana   0.172577  0.294325  0.832174  0.178799  0.998074
fake banana   0.665358  0.799007  0.783545  0.815196  0.999246
real onion    0.620236  0.765562  0.831815  0.709171  0.999608
fake onion    0.906776  0.951059  0.992897  0.912696  0.999941
real unknown  0.923713  0.960294  0.961722  0.958969  0.999987
fake unknown  0.209458  0.346335  0.216160  0.871061  0.997230
total         0.678303  0.773945  0.871088  0.770784  0.999050
total(-bg)    0.663875  0.763770  0.865366  0.760424  0.999193
2026-09-24 09:04:47,408 - INFO: Epoch accounting: {'epoch': 265, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11234169, 49700, 69282, 115260, 152134, 91438, 87291, 160654, 186901, 84418, 58684, 40630, 34437, 227419, 129937, 142273, 26983, 81941, 61198, 79713, 41484, 17056, 65270], 'crops_with_class': [202, 30, 30, 32, 40, 25, 32, 30, 38, 34, 30, 14, 13, 53, 33, 18, 28, 23, 26, 34, 19, 17, 29], 'targeted_crops_by_class': [0, 6, 5, 3, 7, 9, 8, 5, 5, 4, 6, 4, 3, 6, 4, 6, 5, 1, 3, 2, 4, 6, 5], 'sampled_scene_counts': [1, 0, 2, 1, 1, 1, 0, 1, 2, 4, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 2, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 3, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 4, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 0, 0, 1, 3, 0, 2, 1, 2, 0, 0, 2, 1, 2, 1, 1, 3, 2, 0, 2, 2, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 2, 2, 1, 2, 2, 4, 1, 0, 2, 4, 3, 5, 2, 4, 4, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 2, 1, 2, 1, 1, 2, 1, 4, 1, 1, 2, 1, 1, 1, 2, 2, 3, 2, 0, 1, 0, 2, 0, 0, 0, 1, 2], 'learning_rate': 4.574342157203163e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007231822062317181, 'train_segmentation_loss': 0.32924779714776736, 'val_foreground_miou_all22': 0.6638754575125704, 'val_psnr_ref1': 38.169222106933596, 'elapsed_seconds': 320.7893269062042, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 266/500 | Batch 10/202 | Rec 0.000691 | Seg 0.352716 | Elapsed 0.2m | ETA 3.8m
Epoch 266/500 | Batch 20/202 | Rec 0.000677 | Seg 0.341574 | Elapsed 0.4m | ETA 3.7m
Epoch 266/500 | Batch 30/202 | Rec 0.000684 | Seg 0.357920 | Elapsed 0.6m | ETA 3.4m
Epoch 266/500 | Batch 40/202 | Rec 0.000712 | Seg 0.371238 | Elapsed 0.8m | ETA 3.3m
Epoch 266/500 | Batch 50/202 | Rec 0.000699 | Seg 0.356727 | Elapsed 1.0m | ETA 3.1m
Epoch 266/500 | Batch 60/202 | Rec 0.000682 | Seg 0.339856 | Elapsed 1.2m | ETA 2.9m
Epoch 266/500 | Batch 70/202 | Rec 0.000739 | Seg 0.340333 | Elapsed 1.4m | ETA 2.7m
Epoch 266/500 | Batch 80/202 | Rec 0.000729 | Seg 0.333903 | Elapsed 1.6m | ETA 2.5m
Epoch 266/500 | Batch 90/202 | Rec 0.000724 | Seg 0.331888 | Elapsed 1.8m | ETA 2.3m
Epoch 266/500 | Batch 100/202 | Rec 0.000723 | Seg 0.333567 | Elapsed 2.0m | ETA 2.1m
Epoch 266/500 | Batch 110/202 | Rec 0.000725 | Seg 0.331623 | Elapsed 2.2m | ETA 1.9m
Epoch 266/500 | Batch 120/202 | Rec 0.000716 | Seg 0.327119 | Elapsed 2.4m | ETA 1.7m
Epoch 266/500 | Batch 130/202 | Rec 0.000715 | Seg 0.325128 | Elapsed 2.6m | ETA 1.5m
Epoch 266/500 | Batch 140/202 | Rec 0.000706 | Seg 0.321890 | Elapsed 2.8m | ETA 1.3m
Epoch 266/500 | Batch 150/202 | Rec 0.000700 | Seg 0.316952 | Elapsed 3.0m | ETA 1.1m
Epoch 266/500 | Batch 160/202 | Rec 0.000699 | Seg 0.315907 | Elapsed 3.2m | ETA 0.9m
Epoch 266/500 | Batch 170/202 | Rec 0.000695 | Seg 0.312193 | Elapsed 3.5m | ETA 0.7m
Epoch 266/500 | Batch 180/202 | Rec 0.000699 | Seg 0.314038 | Elapsed 3.7m | ETA 0.4m
Epoch 266/500 | Batch 190/202 | Rec 0.000702 | Seg 0.313931 | Elapsed 3.9m | ETA 0.2m
Epoch 266/500 | Batch 200/202 | Rec 0.000706 | Seg 0.316311 | Elapsed 4.1m | ETA 0.0m
Epoch 266/500 | Batch 202/202 | Rec 0.000709 | Seg 0.315836 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:08:54,068 - INFO: Rec loss: 0.0007085053713837786
2026-09-24 09:08:54,068 - INFO: Seg loss: 0.31583624263063514
2026-09-24 09:08:54,068 - INFO: λ_rec: 1
2026-09-24 09:08:54,068 - INFO: λ_seg: 0.0001
2026-09-24 09:10:05,989 - INFO: -------------------Epoch: 266------------------------
2026-09-24 09:10:05,993 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.242678  0.972724  0.000156
2026-09-24 09:10:06,000 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995964  0.997928  0.997287  0.998670  0.996147
real potato   0.905723  0.950480  0.969500  0.932288  0.999884
fake potato   0.941578  0.969860  0.957729  0.982405  0.999956
real apple    0.825041  0.904085  0.978176  0.840513  0.999385
fake apple    0.540248  0.701462  0.989766  0.543283  0.998254
real orange   0.946694  0.972567  0.996236  0.950093  0.999930
fake orange   0.943453  0.970854  0.963716  0.978201  0.999832
real grape    0.771981  0.871270  0.956328  0.800190  0.999507
fake grape    0.905823  0.950534  0.941998  0.959328  0.999631
real lemon    0.631885  0.774375  0.662180  0.932485  0.999362
fake lemon    0.831832  0.908147  0.998789  0.832672  0.999644
real avocado  0.943483  0.970869  0.994490  0.948440  0.999947
fake avocado  0.216654  0.356118  1.000000  0.216654  0.999063
real pepper   0.880054  0.936151  0.915378  0.957993  0.999522
fake pepper   0.882812  0.937709  0.949892  0.925933  0.999707
real plant    0.870272  0.930587  0.935370  0.925952  0.998619
fake plant    0.723617  0.839600  0.755324  0.945169  0.999713
real banana   0.618461  0.764209  0.912449  0.657477  0.999089
fake banana   0.759011  0.862947  0.899065  0.829711  0.999515
real onion    0.660401  0.795423  0.678427  0.961324  0.999553
fake onion    0.944839  0.971587  0.978186  0.965175  0.999964
real unknown  0.898352  0.946404  0.957073  0.936069  0.999983
fake unknown  0.180477  0.305736  0.194753  0.711155  0.997279
total         0.774724  0.851691  0.894874  0.857877  0.999282
total(-bg)    0.764668  0.845044  0.890219  0.851478  0.999424
2026-09-24 09:10:06,540 - INFO: Epoch accounting: {'epoch': 266, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11306414, 48266, 48807, 124630, 140524, 76768, 62113, 106640, 217110, 83152, 63284, 42684, 28452, 247557, 134577, 153883, 25340, 86757, 79698, 62241, 53723, 7489, 38163], 'crops_with_class': [202, 27, 23, 36, 40, 22, 22, 26, 39, 39, 28, 16, 12, 56, 31, 26, 24, 26, 29, 33, 26, 8, 16], 'targeted_crops_by_class': [0, 4, 3, 5, 6, 1, 5, 5, 8, 12, 2, 2, 3, 4, 4, 4, 3, 6, 4, 4, 8, 7, 3], 'sampled_scene_counts': [1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 2, 0, 1, 0, 2, 0, 1, 1, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0, 2, 0, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 0, 0, 2, 1, 1, 0, 2, 2, 1, 0, 3, 1, 3, 3, 0, 1, 1, 4, 0, 0, 1, 1, 2, 1, 2, 1, 0, 2, 4, 0, 2, 4, 1, 0, 1, 1, 4, 1, 0, 0, 0, 2, 1, 2, 4, 0, 3, 1, 1, 1, 2, 1, 1, 1, 0, 4, 0, 0, 0, 2, 1, 1, 1, 0, 1, 1, 2, 1, 0, 2, 1, 3, 2, 2, 1, 0, 0, 1, 2, 2, 2, 4, 2], 'learning_rate': 4.5431347873239044e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007085053713837786, 'train_segmentation_loss': 0.31583624263063514, 'val_foreground_miou_all22': 0.7646677457162074, 'val_psnr_ref1': 38.24267791748047, 'elapsed_seconds': 319.1235017776489, 'peak_cuda_allocated_gib': 7.509342193603516}

Epoch 267/500 | Batch 10/202 | Rec 0.000690 | Seg 0.278128 | Elapsed 0.2m | ETA 4.0m
Epoch 267/500 | Batch 20/202 | Rec 0.000622 | Seg 0.291488 | Elapsed 0.4m | ETA 3.7m
Epoch 267/500 | Batch 30/202 | Rec 0.000668 | Seg 0.300944 | Elapsed 0.6m | ETA 3.5m
Epoch 267/500 | Batch 40/202 | Rec 0.000705 | Seg 0.305934 | Elapsed 0.8m | ETA 3.3m
Epoch 267/500 | Batch 50/202 | Rec 0.000697 | Seg 0.303231 | Elapsed 1.0m | ETA 3.1m
Epoch 267/500 | Batch 60/202 | Rec 0.000691 | Seg 0.303643 | Elapsed 1.2m | ETA 2.9m
Epoch 267/500 | Batch 70/202 | Rec 0.000697 | Seg 0.303024 | Elapsed 1.4m | ETA 2.7m
Epoch 267/500 | Batch 80/202 | Rec 0.000707 | Seg 0.307109 | Elapsed 1.6m | ETA 2.5m
Epoch 267/500 | Batch 90/202 | Rec 0.000698 | Seg 0.301938 | Elapsed 1.8m | ETA 2.3m
Epoch 267/500 | Batch 100/202 | Rec 0.000689 | Seg 0.299754 | Elapsed 2.0m | ETA 2.1m
Epoch 267/500 | Batch 110/202 | Rec 0.000682 | Seg 0.299302 | Elapsed 2.2m | ETA 1.9m
Epoch 267/500 | Batch 120/202 | Rec 0.000696 | Seg 0.301605 | Elapsed 2.4m | ETA 1.7m
Epoch 267/500 | Batch 130/202 | Rec 0.000699 | Seg 0.303994 | Elapsed 2.6m | ETA 1.5m
Epoch 267/500 | Batch 140/202 | Rec 0.000698 | Seg 0.304650 | Elapsed 2.8m | ETA 1.3m
Epoch 267/500 | Batch 150/202 | Rec 0.000703 | Seg 0.306015 | Elapsed 3.1m | ETA 1.1m
Epoch 267/500 | Batch 160/202 | Rec 0.000697 | Seg 0.303620 | Elapsed 3.3m | ETA 0.9m
Epoch 267/500 | Batch 170/202 | Rec 0.000690 | Seg 0.301827 | Elapsed 3.5m | ETA 0.7m
Epoch 267/500 | Batch 180/202 | Rec 0.000695 | Seg 0.303150 | Elapsed 3.7m | ETA 0.4m
Epoch 267/500 | Batch 190/202 | Rec 0.000691 | Seg 0.302769 | Elapsed 3.9m | ETA 0.2m
Epoch 267/500 | Batch 200/202 | Rec 0.000691 | Seg 0.304703 | Elapsed 4.1m | ETA 0.0m
Epoch 267/500 | Batch 202/202 | Rec 0.000693 | Seg 0.305518 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:14:12,832 - INFO: Rec loss: 0.0006928364976797953
2026-09-24 09:14:12,832 - INFO: Seg loss: 0.3055183064598258
2026-09-24 09:14:12,832 - INFO: λ_rec: 1
2026-09-24 09:14:12,833 - INFO: λ_seg: 0.0001
2026-09-24 09:15:26,389 - INFO: -------------------Epoch: 267------------------------
2026-09-24 09:15:26,393 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.513028  0.972914  0.000147
2026-09-24 09:15:26,399 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995868  0.997880  0.997397  0.998463  0.996056
real potato   0.398598  0.569956  0.999042  0.398750  0.999280
fake potato   0.834951  0.910003  0.960447  0.864684  0.999875
real apple    0.708436  0.829289  0.783065  0.881424  0.998748
fake apple    0.642275  0.782129  0.968722  0.655876  0.998621
real orange   0.926267  0.961673  0.994557  0.930987  0.999902
fake orange   0.929756  0.963550  0.945199  0.982731  0.999787
real grape    0.686156  0.813821  0.964078  0.704158  0.999328
fake grape    0.897089  0.945703  0.933221  0.958627  0.999593
real lemon    0.376329  0.546816  0.401079  0.859127  0.998327
fake lemon    0.843568  0.915098  0.995086  0.847097  0.999668
real avocado  0.777896  0.875025  0.805272  0.958128  0.999746
fake avocado  0.701437  0.824475  0.996566  0.703137  0.999642
real pepper   0.840579  0.913336  0.906592  0.920282  0.999362
fake pepper   0.768155  0.868828  0.974153  0.784137  0.999436
real plant    0.856358  0.922572  0.899601  0.946851  0.998411
fake plant    0.855143  0.921866  0.907201  0.937117  0.999874
real banana   0.197062  0.329213  0.902587  0.201345  0.998157
fake banana   0.684606  0.812729  0.795913  0.830375  0.999296
real onion    0.642947  0.782626  0.715545  0.863705  0.999567
fake onion    0.938815  0.968392  0.987679  0.949940  0.999961
real unknown  0.942777  0.970496  0.982405  0.958969  0.999991
fake unknown  0.254363  0.405527  0.275533  0.768019  0.998103
total         0.726062  0.818739  0.873519  0.821910  0.999162
total(-bg)    0.713798  0.810596  0.867888  0.813885  0.999303
2026-09-24 09:15:26,945 - INFO: Epoch accounting: {'epoch': 267, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11392600, 54077, 76035, 103902, 109885, 79708, 74387, 125285, 163114, 61621, 50292, 33871, 18327, 200663, 134276, 144299, 20668, 95517, 82248, 90131, 75682, 10892, 40792], 'crops_with_class': [202, 37, 34, 31, 30, 24, 27, 23, 30, 26, 19, 14, 9, 53, 34, 21, 22, 27, 35, 39, 35, 11, 19], 'targeted_crops_by_class': [0, 6, 3, 6, 0, 3, 2, 4, 9, 4, 2, 2, 1, 6, 5, 5, 6, 1, 5, 7, 11, 4, 6], 'sampled_scene_counts': [1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 2, 0, 1, 2, 1, 0, 2, 0, 1, 0, 1, 1, 2, 0, 1, 0, 2, 0, 1, 0, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 1, 1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 3, 1, 0, 0, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0, 4, 2, 1, 0, 1, 2, 3, 0, 1, 1, 2, 1, 2, 1, 3, 0, 1, 0, 2, 2, 0, 2, 3, 0, 2, 2, 2, 3, 3, 1, 0, 0, 2, 2, 2, 2, 1, 0, 1, 1, 1, 4, 1, 1, 0, 0, 2, 1, 2, 1, 2, 0, 0, 1, 2, 1, 1, 4, 2, 3, 1, 0, 1, 3, 2, 5, 2, 2, 2], 'learning_rate': 4.5119459471795605e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006928364976797953, 'train_segmentation_loss': 0.3055183064598258, 'val_foreground_miou_all22': 0.7137984617535703, 'val_psnr_ref1': 38.51302764892578, 'elapsed_seconds': 320.3975474834442, 'peak_cuda_allocated_gib': 7.514682769775391}

Epoch 268/500 | Batch 10/202 | Rec 0.000541 | Seg 0.266175 | Elapsed 0.2m | ETA 3.9m
Epoch 268/500 | Batch 20/202 | Rec 0.000585 | Seg 0.275910 | Elapsed 0.4m | ETA 3.7m
Epoch 268/500 | Batch 30/202 | Rec 0.000641 | Seg 0.306816 | Elapsed 0.6m | ETA 3.5m
Epoch 268/500 | Batch 40/202 | Rec 0.000610 | Seg 0.292761 | Elapsed 0.8m | ETA 3.3m
Epoch 268/500 | Batch 50/202 | Rec 0.000657 | Seg 0.319309 | Elapsed 1.0m | ETA 3.1m
Epoch 268/500 | Batch 60/202 | Rec 0.000669 | Seg 0.319741 | Elapsed 1.2m | ETA 2.9m
Epoch 268/500 | Batch 70/202 | Rec 0.000654 | Seg 0.313789 | Elapsed 1.4m | ETA 2.7m
Epoch 268/500 | Batch 80/202 | Rec 0.000708 | Seg 0.326834 | Elapsed 1.6m | ETA 2.5m
Epoch 268/500 | Batch 90/202 | Rec 0.000698 | Seg 0.319330 | Elapsed 1.8m | ETA 2.3m
Epoch 268/500 | Batch 100/202 | Rec 0.000722 | Seg 0.321690 | Elapsed 2.0m | ETA 2.1m
Epoch 268/500 | Batch 110/202 | Rec 0.000731 | Seg 0.327075 | Elapsed 2.2m | ETA 1.9m
Epoch 268/500 | Batch 120/202 | Rec 0.000719 | Seg 0.330738 | Elapsed 2.4m | ETA 1.7m
Epoch 268/500 | Batch 130/202 | Rec 0.000721 | Seg 0.333069 | Elapsed 2.6m | ETA 1.5m
Epoch 268/500 | Batch 140/202 | Rec 0.000703 | Seg 0.325172 | Elapsed 2.9m | ETA 1.3m
Epoch 268/500 | Batch 150/202 | Rec 0.000702 | Seg 0.326343 | Elapsed 3.1m | ETA 1.1m
Epoch 268/500 | Batch 160/202 | Rec 0.000699 | Seg 0.327268 | Elapsed 3.3m | ETA 0.9m
Epoch 268/500 | Batch 170/202 | Rec 0.000699 | Seg 0.326539 | Elapsed 3.5m | ETA 0.7m
Epoch 268/500 | Batch 180/202 | Rec 0.000692 | Seg 0.327180 | Elapsed 3.7m | ETA 0.4m
Epoch 268/500 | Batch 190/202 | Rec 0.000689 | Seg 0.324847 | Elapsed 3.9m | ETA 0.2m
Epoch 268/500 | Batch 200/202 | Rec 0.000692 | Seg 0.324341 | Elapsed 4.1m | ETA 0.0m
Epoch 268/500 | Batch 202/202 | Rec 0.000689 | Seg 0.323788 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:19:33,846 - INFO: Rec loss: 0.0006891523204319695
2026-09-24 09:19:33,846 - INFO: Seg loss: 0.32378832276652353
2026-09-24 09:19:33,846 - INFO: λ_rec: 1
2026-09-24 09:19:33,846 - INFO: λ_seg: 0.0001
2026-09-24 09:20:45,378 - INFO: -------------------Epoch: 268------------------------
2026-09-24 09:20:45,382 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.813365  0.974016  0.000139
2026-09-24 09:20:45,389 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995208  0.997548  0.996268  0.998933  0.995421
real potato   0.900799  0.947761  0.947268  0.948355  0.999875
fake potato   0.949634  0.974117  0.968918  0.979472  0.999962
real apple    0.726778  0.841725  0.989191  0.732596  0.999050
fake apple    0.751621  0.858151  0.995254  0.754324  0.999059
real orange   0.821986  0.902247  0.997895  0.823414  0.999765
fake orange   0.875833  0.933757  0.897351  0.973350  0.999605
real grape    0.704854  0.826829  0.843702  0.810714  0.999291
fake grape    0.884934  0.938905  0.947955  0.930124  0.999553
real lemon    0.696402  0.820984  0.790131  0.854453  0.999562
fake lemon    0.817697  0.899657  0.998856  0.818464  0.999614
real avocado  0.921821  0.959270  0.954486  0.964204  0.999924
fake avocado  0.571592  0.727359  0.999777  0.571665  0.999487
real pepper   0.806084  0.892582  0.850208  0.939513  0.999173
fake pepper   0.746442  0.854765  0.973187  0.762115  0.999383
real plant    0.851409  0.919692  0.942221  0.898310  0.998432
fake plant    0.718657  0.836251  0.798327  0.878067  0.999726
real banana   0.732714  0.845692  0.960300  0.755602  0.999381
fake banana   0.735197  0.847343  0.881657  0.815693  0.999460
real onion    0.685814  0.813581  0.707195  0.957777  0.999604
fake onion    0.945663  0.972023  0.984860  0.959613  0.999965
real unknown  0.563592  0.720846  0.604787  0.892175  0.999890
fake unknown  0.277179  0.434005  0.319760  0.675480  0.998516
total         0.768779  0.859352  0.884763  0.856279  0.999291
total(-bg)    0.758487  0.853070  0.879695  0.849795  0.999467
2026-09-24 09:20:46,130 - INFO: Epoch accounting: {'epoch': 268, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11281547, 56231, 65178, 109846, 150534, 81283, 74261, 107371, 181892, 62789, 57947, 37715, 43349, 247353, 105255, 148310, 21131, 97355, 100552, 87388, 67761, 10412, 42812], 'crops_with_class': [202, 36, 33, 30, 39, 28, 25, 22, 37, 30, 26, 12, 17, 62, 33, 17, 18, 29, 41, 35, 29, 14, 20], 'targeted_crops_by_class': [0, 5, 5, 5, 5, 7, 1, 0, 2, 3, 8, 1, 5, 9, 2, 3, 5, 4, 7, 5, 3, 3, 5], 'sampled_scene_counts': [3, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 0, 0, 1, 0, 2, 1, 0, 2, 1, 0, 2, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0, 2, 1, 1, 2, 2, 1, 3, 1, 1, 1, 1, 1, 0, 0, 0, 3, 3, 3, 2, 5, 4, 0, 1, 1, 0, 1, 0, 2, 2, 1, 0, 1, 3, 1, 1, 3, 2, 1, 1, 0, 4, 1, 1, 3, 0, 1, 1, 1, 1, 0, 2, 1, 0, 4, 2, 1, 1, 1, 2, 1, 2, 1, 2, 3, 4, 1, 3, 3, 1, 0, 2, 0, 1, 2, 3, 0], 'learning_rate': 4.4807768680521354e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006891523204319695, 'train_segmentation_loss': 0.32378832276652353, 'val_foreground_miou_all22': 0.7584866088801129, 'val_psnr_ref1': 38.81336471557617, 'elapsed_seconds': 319.17664766311646, 'peak_cuda_allocated_gib': 7.512729644775391}

Epoch 269/500 | Batch 10/202 | Rec 0.000586 | Seg 0.262756 | Elapsed 0.2m | ETA 4.0m
Epoch 269/500 | Batch 20/202 | Rec 0.000639 | Seg 0.300861 | Elapsed 0.4m | ETA 3.8m
Epoch 269/500 | Batch 30/202 | Rec 0.000631 | Seg 0.286781 | Elapsed 0.6m | ETA 3.5m
Epoch 269/500 | Batch 40/202 | Rec 0.000621 | Seg 0.292765 | Elapsed 0.8m | ETA 3.3m
Epoch 269/500 | Batch 50/202 | Rec 0.000619 | Seg 0.289894 | Elapsed 1.0m | ETA 3.1m
Epoch 269/500 | Batch 60/202 | Rec 0.000626 | Seg 0.292059 | Elapsed 1.2m | ETA 2.9m
Epoch 269/500 | Batch 70/202 | Rec 0.000625 | Seg 0.292654 | Elapsed 1.4m | ETA 2.7m
Epoch 269/500 | Batch 80/202 | Rec 0.000637 | Seg 0.294081 | Elapsed 1.6m | ETA 2.5m
Epoch 269/500 | Batch 90/202 | Rec 0.000646 | Seg 0.292345 | Elapsed 1.8m | ETA 2.3m
Epoch 269/500 | Batch 100/202 | Rec 0.000638 | Seg 0.289935 | Elapsed 2.0m | ETA 2.1m
Epoch 269/500 | Batch 110/202 | Rec 0.000638 | Seg 0.292386 | Elapsed 2.3m | ETA 1.9m
Epoch 269/500 | Batch 120/202 | Rec 0.000646 | Seg 0.298639 | Elapsed 2.5m | ETA 1.7m
Epoch 269/500 | Batch 130/202 | Rec 0.000662 | Seg 0.308210 | Elapsed 2.7m | ETA 1.5m
Epoch 269/500 | Batch 140/202 | Rec 0.000673 | Seg 0.312355 | Elapsed 2.9m | ETA 1.3m
Epoch 269/500 | Batch 150/202 | Rec 0.000670 | Seg 0.312306 | Elapsed 3.1m | ETA 1.1m
Epoch 269/500 | Batch 160/202 | Rec 0.000671 | Seg 0.316187 | Elapsed 3.3m | ETA 0.9m
Epoch 269/500 | Batch 170/202 | Rec 0.000676 | Seg 0.317740 | Elapsed 3.5m | ETA 0.7m
Epoch 269/500 | Batch 180/202 | Rec 0.000679 | Seg 0.314215 | Elapsed 3.7m | ETA 0.4m
Epoch 269/500 | Batch 190/202 | Rec 0.000680 | Seg 0.313434 | Elapsed 3.9m | ETA 0.2m
Epoch 269/500 | Batch 200/202 | Rec 0.000690 | Seg 0.314533 | Elapsed 4.1m | ETA 0.0m
Epoch 269/500 | Batch 202/202 | Rec 0.000690 | Seg 0.315422 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:24:53,177 - INFO: Rec loss: 0.0006896334805175441
2026-09-24 09:24:53,177 - INFO: Seg loss: 0.31542159233352923
2026-09-24 09:24:53,177 - INFO: λ_rec: 1
2026-09-24 09:24:53,177 - INFO: λ_seg: 0.0001
2026-09-24 09:26:06,176 - INFO: -------------------Epoch: 269------------------------
2026-09-24 09:26:06,180 - INFO:
Validation stats:
      PSNR      SSIM       MSE
0  37.9631  0.973016  0.000166
2026-09-24 09:26:06,187 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995666  0.997778  0.996956  0.998702  0.995862
real potato   0.918438  0.957435  0.967456  0.947717  0.999899
fake potato   0.938771  0.968369  0.960635  0.976330  0.999954
real apple    0.737957  0.849174  0.917145  0.790668  0.999031
fake apple    0.536433  0.698238  0.987802  0.540010  0.998238
real orange   0.922482  0.959628  0.997502  0.924618  0.999898
fake orange   0.939832  0.968933  0.958301  0.979906  0.999820
real grape    0.710698  0.830837  0.859060  0.804502  0.999316
fake grape    0.896398  0.945319  0.938282  0.952564  0.999593
real lemon    0.534930  0.696959  0.698098  0.695923  0.999289
fake lemon    0.852766  0.920483  0.996805  0.855103  0.999688
real avocado  0.897649  0.946014  0.933365  0.959113  0.999898
fake avocado  0.530852  0.693492  0.999520  0.530987  0.999438
real pepper   0.853849  0.921113  0.898181  0.945353  0.999408
fake pepper   0.873328  0.932332  0.973461  0.894629  0.999691
real plant    0.861917  0.925788  0.940466  0.911658  0.998539
fake plant    0.830265  0.907212  0.906741  0.907784  0.999852
real banana   0.693524  0.818982  0.938509  0.726538  0.999279
fake banana   0.613918  0.760730  0.694197  0.841490  0.999026
real onion    0.676195  0.806773  0.694312  0.962844  0.999583
fake onion    0.932368  0.964951  0.980289  0.950181  0.999957
real unknown  0.847844  0.917608  0.881371  0.957061  0.999973
fake unknown  0.213267  0.351520  0.237412  0.677110  0.997895
total         0.774319  0.858246  0.885038  0.857860  0.999266
total(-bg)    0.764258  0.851904  0.879951  0.851459  0.999421
2026-09-24 09:26:06,759 - INFO: Epoch accounting: {'epoch': 269, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11316632, 48739, 56153, 126140, 113446, 72837, 58708, 137259, 187740, 66403, 73503, 35180, 51895, 218072, 132096, 131691, 32297, 83527, 91618, 87759, 52094, 14361, 50122], 'crops_with_class': [202, 28, 24, 34, 31, 23, 18, 30, 35, 31, 30, 12, 21, 54, 35, 19, 28, 22, 37, 37, 25, 16, 22], 'targeted_crops_by_class': [0, 6, 3, 3, 2, 3, 5, 4, 8, 5, 7, 1, 11, 3, 4, 2, 1, 4, 3, 3, 6, 6, 3], 'sampled_scene_counts': [0, 1, 0, 2, 0, 2, 0, 1, 0, 0, 2, 0, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 3, 0, 1, 1, 0, 0, 0, 0, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 2, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 3, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 2, 2, 0, 0, 2, 1, 2, 3, 2, 0, 1, 1, 1, 3, 1, 0, 1, 1, 2, 1, 2, 2, 3, 1, 1, 0, 2, 2, 3, 1, 0, 1, 3, 2, 0, 1, 6, 3, 1, 3, 0, 2, 1, 1, 4, 0, 1, 1, 2, 2, 1, 3, 0, 1, 2, 0, 1, 2, 1, 1, 1, 2, 1, 3, 2, 1, 1, 1, 2, 3, 1, 1, 1, 1, 0, 0, 1, 1, 2], 'learning_rate': 4.4496287804435044e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006896334805175441, 'train_segmentation_loss': 0.31542159233352923, 'val_foreground_miou_all22': 0.7642581910018429, 'val_psnr_ref1': 37.96310028076172, 'elapsed_seconds': 320.62120246887207, 'peak_cuda_allocated_gib': 7.506870269775391}

Epoch 270/500 | Batch 10/202 | Rec 0.000832 | Seg 0.314262 | Elapsed 0.2m | ETA 3.9m
Epoch 270/500 | Batch 20/202 | Rec 0.000779 | Seg 0.303546 | Elapsed 0.4m | ETA 3.7m
Epoch 270/500 | Batch 30/202 | Rec 0.000743 | Seg 0.323075 | Elapsed 0.6m | ETA 3.5m
Epoch 270/500 | Batch 40/202 | Rec 0.000727 | Seg 0.320618 | Elapsed 0.8m | ETA 3.3m
Epoch 270/500 | Batch 50/202 | Rec 0.000700 | Seg 0.306497 | Elapsed 1.0m | ETA 3.1m
Epoch 270/500 | Batch 60/202 | Rec 0.000707 | Seg 0.309855 | Elapsed 1.2m | ETA 2.9m
Epoch 270/500 | Batch 70/202 | Rec 0.000705 | Seg 0.311614 | Elapsed 1.4m | ETA 2.7m
Epoch 270/500 | Batch 80/202 | Rec 0.000692 | Seg 0.308637 | Elapsed 1.6m | ETA 2.5m
Epoch 270/500 | Batch 90/202 | Rec 0.000709 | Seg 0.305649 | Elapsed 1.8m | ETA 2.3m
Epoch 270/500 | Batch 100/202 | Rec 0.000698 | Seg 0.301947 | Elapsed 2.0m | ETA 2.1m
Epoch 270/500 | Batch 110/202 | Rec 0.000685 | Seg 0.301071 | Elapsed 2.2m | ETA 1.9m
Epoch 270/500 | Batch 120/202 | Rec 0.000685 | Seg 0.303081 | Elapsed 2.4m | ETA 1.7m
Epoch 270/500 | Batch 130/202 | Rec 0.000685 | Seg 0.308372 | Elapsed 2.6m | ETA 1.5m
Epoch 270/500 | Batch 140/202 | Rec 0.000682 | Seg 0.307325 | Elapsed 2.8m | ETA 1.3m
Epoch 270/500 | Batch 150/202 | Rec 0.000673 | Seg 0.304258 | Elapsed 3.0m | ETA 1.1m
Epoch 270/500 | Batch 160/202 | Rec 0.000686 | Seg 0.311279 | Elapsed 3.2m | ETA 0.9m
Epoch 270/500 | Batch 170/202 | Rec 0.000681 | Seg 0.309795 | Elapsed 3.4m | ETA 0.6m
Epoch 270/500 | Batch 180/202 | Rec 0.000685 | Seg 0.311167 | Elapsed 3.6m | ETA 0.4m
Epoch 270/500 | Batch 190/202 | Rec 0.000679 | Seg 0.308220 | Elapsed 3.8m | ETA 0.2m
Epoch 270/500 | Batch 200/202 | Rec 0.000681 | Seg 0.308710 | Elapsed 4.1m | ETA 0.0m
Epoch 270/500 | Batch 202/202 | Rec 0.000699 | Seg 0.307832 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:30:12,734 - INFO: Rec loss: 0.0006990671606064719
2026-09-24 09:30:12,735 - INFO: Seg loss: 0.3078320048712563
2026-09-24 09:30:12,735 - INFO: λ_rec: 1
2026-09-24 09:30:12,735 - INFO: λ_seg: 0.0001
2026-09-24 09:31:25,505 - INFO: -------------------Epoch: 270------------------------
2026-09-24 09:31:25,509 - INFO:
Validation stats:
        PSNR     SSIM      MSE
0  38.421636  0.97315  0.00015
2026-09-24 09:31:25,516 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995474  0.997682  0.996590  0.998876  0.995676
real potato   0.915408  0.955786  0.945929  0.965953  0.999893
fake potato   0.920728  0.958678  0.933519  0.985337  0.999938
real apple    0.726076  0.841253  0.994151  0.729191  0.999051
fake apple    0.602291  0.751741  0.991332  0.605480  0.998490
real orange   0.934311  0.965990  0.996798  0.937124  0.999913
fake orange   0.941856  0.970007  0.962049  0.978201  0.999827
real grape    0.746390  0.854731  0.937151  0.785720  0.999443
fake grape    0.876837  0.934328  0.967987  0.903024  0.999531
real lemon    0.432057  0.603359  0.511464  0.735653  0.998864
fake lemon    0.849038  0.918307  0.995034  0.852651  0.999679
real avocado  0.928503  0.962876  0.975084  0.951067  0.999932
fake avocado  0.584268  0.737541  0.999564  0.584417  0.999502
real pepper   0.884355  0.938579  0.929981  0.947439  0.999547
fake pepper   0.894039  0.944005  0.961314  0.927405  0.999738
real plant    0.854474  0.921477  0.942616  0.901361  0.998465
fake plant    0.829196  0.906573  0.903945  0.909317  0.999851
real banana   0.510077  0.675518  0.917794  0.534497  0.998846
fake banana   0.657766  0.793507  0.755474  0.835683  0.999200
real onion    0.621838  0.766783  0.638839  0.958960  0.999473
fake onion    0.946488  0.972459  0.987291  0.958162  0.999966
real unknown  0.482943  0.651286  0.496742  0.945611  0.999838
fake unknown  0.201713  0.335671  0.223999  0.669685  0.997767
total         0.753745  0.841658  0.868028  0.852209  0.999236
total(-bg)    0.742757  0.834566  0.862184  0.845543  0.999398
2026-09-24 09:31:26,102 - INFO: Epoch accounting: {'epoch': 270, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11334075, 43125, 54490, 112656, 156829, 93679, 97627, 174612, 156850, 81031, 51074, 42968, 50440, 207456, 149131, 127505, 26034, 69076, 63412, 61255, 44716, 9013, 31218], 'crops_with_class': [202, 22, 29, 34, 37, 31, 31, 28, 28, 39, 25, 15, 18, 53, 33, 17, 22, 19, 25, 28, 19, 10, 15], 'targeted_crops_by_class': [0, 2, 4, 5, 3, 9, 12, 7, 4, 7, 4, 5, 4, 4, 9, 3, 3, 5, 5, 5, 3, 3, 1], 'sampled_scene_counts': [1, 3, 2, 0, 0, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 0, 0, 0, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1, 0, 2, 0, 0, 2, 1, 2, 0, 0, 2, 1, 0, 1, 1, 2, 2, 1, 0, 1, 1, 3, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 3, 0, 1, 1, 2, 1, 2, 0, 2, 2, 0, 0, 3, 2, 2, 1, 1, 0, 0, 2, 2, 1, 2, 0, 2, 3, 1, 1, 1, 5, 0, 1, 2, 1, 1, 2, 3, 2, 0, 2, 1, 2, 1, 1, 0, 0, 3, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 1, 2, 0, 1, 2, 0, 2, 1, 2, 1, 2, 1, 1, 3, 1, 2, 0, 1, 1, 2, 1, 2, 0, 2], 'learning_rate': 4.418502914026833e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0006990671606064719, 'train_segmentation_loss': 0.3078320048712563, 'val_foreground_miou_all22': 0.7427568476511552, 'val_psnr_ref1': 38.42163604736328, 'elapsed_seconds': 319.335412979126, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 271/500 | Batch 10/202 | Rec 0.000684 | Seg 0.290090 | Elapsed 0.2m | ETA 4.0m
Epoch 271/500 | Batch 20/202 | Rec 0.000695 | Seg 0.295460 | Elapsed 0.4m | ETA 3.7m
Epoch 271/500 | Batch 30/202 | Rec 0.000771 | Seg 0.314884 | Elapsed 0.6m | ETA 3.5m
Epoch 271/500 | Batch 40/202 | Rec 0.000774 | Seg 0.312584 | Elapsed 0.8m | ETA 3.3m
Epoch 271/500 | Batch 50/202 | Rec 0.000761 | Seg 0.328583 | Elapsed 1.0m | ETA 3.1m
Epoch 271/500 | Batch 60/202 | Rec 0.000746 | Seg 0.325232 | Elapsed 1.2m | ETA 2.9m
Epoch 271/500 | Batch 70/202 | Rec 0.000730 | Seg 0.320180 | Elapsed 1.4m | ETA 2.7m
Epoch 271/500 | Batch 80/202 | Rec 0.000715 | Seg 0.309572 | Elapsed 1.6m | ETA 2.5m
Epoch 271/500 | Batch 90/202 | Rec 0.000698 | Seg 0.298947 | Elapsed 1.9m | ETA 2.3m
Epoch 271/500 | Batch 100/202 | Rec 0.000696 | Seg 0.307178 | Elapsed 2.1m | ETA 2.1m
Epoch 271/500 | Batch 110/202 | Rec 0.000702 | Seg 0.312573 | Elapsed 2.3m | ETA 1.9m
Epoch 271/500 | Batch 120/202 | Rec 0.000727 | Seg 0.316107 | Elapsed 2.5m | ETA 1.7m
Epoch 271/500 | Batch 130/202 | Rec 0.000726 | Seg 0.317282 | Elapsed 2.7m | ETA 1.5m
Epoch 271/500 | Batch 140/202 | Rec 0.000716 | Seg 0.309394 | Elapsed 2.9m | ETA 1.3m
Epoch 271/500 | Batch 150/202 | Rec 0.000706 | Seg 0.304404 | Elapsed 3.1m | ETA 1.1m
Epoch 271/500 | Batch 160/202 | Rec 0.000707 | Seg 0.307757 | Elapsed 3.3m | ETA 0.9m
Epoch 271/500 | Batch 170/202 | Rec 0.000703 | Seg 0.306236 | Elapsed 3.5m | ETA 0.7m
Epoch 271/500 | Batch 180/202 | Rec 0.000703 | Seg 0.308893 | Elapsed 3.7m | ETA 0.5m
Epoch 271/500 | Batch 190/202 | Rec 0.000705 | Seg 0.310974 | Elapsed 3.9m | ETA 0.2m
Epoch 271/500 | Batch 200/202 | Rec 0.000708 | Seg 0.310041 | Elapsed 4.1m | ETA 0.0m
Epoch 271/500 | Batch 202/202 | Rec 0.000708 | Seg 0.309307 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:35:34,430 - INFO: Rec loss: 0.0007082017230522348
2026-09-24 09:35:34,430 - INFO: Seg loss: 0.3093073895330181
2026-09-24 09:35:34,430 - INFO: λ_rec: 1
2026-09-24 09:35:34,430 - INFO: λ_seg: 0.0001
2026-09-24 09:36:47,307 - INFO: -------------------Epoch: 271------------------------
2026-09-24 09:36:47,311 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.429498  0.973365  0.00015
2026-09-24 09:36:47,318 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995895  0.997894  0.997406  0.998482  0.996082
real potato   0.704482  0.826574  0.997836  0.705560  0.999646
fake potato   0.814437  0.897680  0.968477  0.836615  0.999861
real apple    0.751315  0.857951  0.863303  0.852764  0.999026
fake apple    0.609174  0.757079  0.990077  0.612916  0.998515
real orange   0.895192  0.944648  0.995257  0.899027  0.999861
fake orange   0.926220  0.961647  0.946339  0.977561  0.999777
real grape    0.764162  0.866267  0.887781  0.845867  0.999455
fake grape    0.893101  0.943482  0.941440  0.945634  0.999581
real lemon    0.419541  0.591047  0.471814  0.791093  0.998714
fake lemon    0.855465  0.922053  0.991944  0.861450  0.999692
real avocado  0.857101  0.923003  0.890313  0.958292  0.999852
fake avocado  0.491841  0.659330  0.999482  0.491966  0.999392
real pepper   0.833774  0.909303  0.886306  0.933631  0.999319
fake pepper   0.796434  0.886633  0.968314  0.817745  0.999502
real plant    0.865625  0.927923  0.936684  0.919423  0.998572
fake plant    0.842765  0.914625  0.878799  0.953604  0.999858
real banana   0.489114  0.656872  0.853468  0.533954  0.998747
fake banana   0.695907  0.820640  0.778845  0.867286  0.999303
real onion    0.651332  0.788807  0.751798  0.829758  0.999599
fake onion    0.939727  0.968877  0.988428  0.950181  0.999962
real unknown  0.950382  0.974510  1.000000  0.950382  0.999992
fake unknown  0.217490  0.357241  0.233508  0.760232  0.997695
total         0.750456  0.841482  0.879027  0.838845  0.999218
total(-bg)    0.739299  0.834372  0.873646  0.831588  0.999360
2026-09-24 09:36:47,855 - INFO: Epoch accounting: {'epoch': 271, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11323115, 60694, 76430, 134954, 147792, 62319, 64684, 108912, 204777, 73943, 79144, 47573, 27729, 190274, 158889, 126047, 19963, 74974, 77273, 77877, 49739, 9713, 41457], 'crops_with_class': [202, 34, 32, 36, 34, 19, 22, 23, 36, 33, 32, 18, 12, 51, 37, 22, 22, 26, 29, 36, 24, 9, 20], 'targeted_crops_by_class': [0, 4, 7, 3, 6, 3, 2, 2, 7, 3, 3, 5, 5, 8, 7, 5, 4, 3, 8, 3, 6, 4, 3], 'sampled_scene_counts': [1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 3, 0, 2, 2, 3, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 3, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 3, 2, 2, 1, 2, 1, 1, 2, 0, 3, 2, 3, 3, 1, 0, 1, 1, 0, 1, 1, 2, 0, 3, 2, 1, 1, 3, 3, 0, 1, 2, 3, 3, 2, 1, 0, 0, 2, 2, 0, 3, 3, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1], 'learning_rate': 4.387400497598028e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007082017230522348, 'train_segmentation_loss': 0.3093073895330181, 'val_foreground_miou_all22': 0.739299144166588, 'val_psnr_ref1': 38.42949813842773, 'elapsed_seconds': 321.74582600593567, 'peak_cuda_allocated_gib': 7.508335113525391}

Epoch 272/500 | Batch 10/202 | Rec 0.000772 | Seg 0.337566 | Elapsed 0.2m | ETA 3.9m
Epoch 272/500 | Batch 20/202 | Rec 0.000724 | Seg 0.333619 | Elapsed 0.4m | ETA 3.6m
Epoch 272/500 | Batch 30/202 | Rec 0.000693 | Seg 0.313818 | Elapsed 0.6m | ETA 3.5m
Epoch 272/500 | Batch 40/202 | Rec 0.000807 | Seg 0.299578 | Elapsed 0.8m | ETA 3.3m
Epoch 272/500 | Batch 50/202 | Rec 0.000815 | Seg 0.324187 | Elapsed 1.0m | ETA 3.1m
Epoch 272/500 | Batch 60/202 | Rec 0.000793 | Seg 0.331337 | Elapsed 1.2m | ETA 2.9m
Epoch 272/500 | Batch 70/202 | Rec 0.000786 | Seg 0.339797 | Elapsed 1.4m | ETA 2.7m
Epoch 272/500 | Batch 80/202 | Rec 0.000786 | Seg 0.339278 | Elapsed 1.6m | ETA 2.5m
Epoch 272/500 | Batch 90/202 | Rec 0.000773 | Seg 0.334761 | Elapsed 1.8m | ETA 2.3m
Epoch 272/500 | Batch 100/202 | Rec 0.000765 | Seg 0.332645 | Elapsed 2.0m | ETA 2.1m
Epoch 272/500 | Batch 110/202 | Rec 0.000752 | Seg 0.327289 | Elapsed 2.2m | ETA 1.9m
Epoch 272/500 | Batch 120/202 | Rec 0.000745 | Seg 0.327385 | Elapsed 2.4m | ETA 1.7m
Epoch 272/500 | Batch 130/202 | Rec 0.000751 | Seg 0.331184 | Elapsed 2.6m | ETA 1.5m
Epoch 272/500 | Batch 140/202 | Rec 0.000745 | Seg 0.328256 | Elapsed 2.8m | ETA 1.3m
Epoch 272/500 | Batch 150/202 | Rec 0.000737 | Seg 0.324851 | Elapsed 3.1m | ETA 1.1m
Epoch 272/500 | Batch 160/202 | Rec 0.000728 | Seg 0.321170 | Elapsed 3.3m | ETA 0.9m
Epoch 272/500 | Batch 170/202 | Rec 0.000730 | Seg 0.320513 | Elapsed 3.5m | ETA 0.7m
Epoch 272/500 | Batch 180/202 | Rec 0.000728 | Seg 0.320577 | Elapsed 3.7m | ETA 0.4m
Epoch 272/500 | Batch 190/202 | Rec 0.000735 | Seg 0.330030 | Elapsed 3.9m | ETA 0.2m
Epoch 272/500 | Batch 200/202 | Rec 0.000738 | Seg 0.330685 | Elapsed 4.1m | ETA 0.0m
Epoch 272/500 | Batch 202/202 | Rec 0.000737 | Seg 0.329365 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:40:55,258 - INFO: Rec loss: 0.0007369362434780336
2026-09-24 09:40:55,258 - INFO: Seg loss: 0.3293647580217607
2026-09-24 09:40:55,258 - INFO: λ_rec: 1
2026-09-24 09:40:55,258 - INFO: λ_seg: 0.0001
2026-09-24 09:42:08,323 - INFO: -------------------Epoch: 272------------------------
2026-09-24 09:42:08,326 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.271722  0.973068  0.000155
2026-09-24 09:42:08,333 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995752  0.997821  0.996932  0.998812  0.995943
real potato   0.400536  0.571934  1.000000  0.400536  0.999283
fake potato   0.639497  0.780065  0.952295  0.660662  0.999729
real apple    0.668079  0.800966  0.786686  0.815878  0.998602
fake apple    0.630042  0.772990  0.990651  0.633810  0.998595
real orange   0.850468  0.919143  0.998506  0.851552  0.999803
fake orange   0.908036  0.951752  0.940800  0.963064  0.999721
real grape    0.797820  0.887492  0.977161  0.812980  0.999570
fake grape    0.883741  0.938233  0.924114  0.952894  0.999536
real lemon    0.354442  0.523331  0.410119  0.723059  0.998452
fake lemon    0.847398  0.917347  0.991126  0.853877  0.999675
real avocado  0.849488  0.918570  0.898430  0.939737  0.999845
fake avocado  0.483172  0.651495  0.999473  0.483295  0.999381
real pepper   0.886285  0.939665  0.942435  0.937010  0.999560
fake pepper   0.845233  0.916076  0.938259  0.895013  0.999609
real plant    0.868075  0.929329  0.941714  0.917363  0.998605
fake plant    0.804647  0.891700  0.887265  0.896281  0.999827
real banana   0.355854  0.524874  0.881345  0.373761  0.998480
fake banana   0.613960  0.760762  0.700000  0.833195  0.999036
real onion    0.626234  0.770114  0.768674  0.771660  0.999584
fake onion    0.926442  0.961767  0.993555  0.932044  0.999953
real unknown  0.940840  0.969468  1.000000  0.940840  0.999991
fake unknown  0.193751  0.324574  0.209081  0.725462  0.997456
total         0.711730  0.809542  0.875157  0.796208  0.999141
total(-bg)    0.698820  0.800984  0.869622  0.786999  0.999286
2026-09-24 09:42:08,900 - INFO: Epoch accounting: {'epoch': 272, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11189679, 41793, 87814, 101775, 144223, 64218, 70878, 145655, 203721, 66778, 54711, 28615, 34370, 265843, 197006, 150020, 20771, 63470, 77207, 104427, 64364, 7146, 53788], 'crops_with_class': [202, 30, 36, 28, 38, 20, 22, 31, 33, 32, 24, 11, 14, 62, 46, 21, 18, 22, 32, 41, 29, 10, 22], 'targeted_crops_by_class': [0, 2, 9, 5, 2, 4, 3, 4, 5, 5, 3, 4, 3, 7, 9, 5, 4, 2, 6, 3, 6, 5, 6], 'sampled_scene_counts': [0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 2, 2, 1, 2, 0, 2, 0, 0, 0, 1, 1, 1, 2, 0, 0, 1, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 2, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 3, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 2, 1, 0, 0, 1, 2, 1, 1, 0, 1, 2, 2, 1, 0, 0, 1, 1, 1, 1, 1, 3, 3, 1, 2, 1, 2, 0, 3, 2, 1, 0, 4, 3, 0, 2, 1, 1, 1, 2, 1, 4, 2, 1, 0, 0, 3, 1, 0, 2, 4, 4, 3, 3, 3, 2, 1, 0, 2, 0, 2, 2, 1, 3, 2, 1, 2, 0, 2, 1, 1, 4, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 2, 1, 2, 0, 3, 1, 0], 'learning_rate': 4.356322759027236e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007369362434780336, 'train_segmentation_loss': 0.3293647580217607, 'val_foreground_miou_all22': 0.6988199800182175, 'val_psnr_ref1': 38.27172180175781, 'elapsed_seconds': 321.0366253852844, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 273/500 | Batch 10/202 | Rec 0.000733 | Seg 0.386649 | Elapsed 0.2m | ETA 3.7m
Epoch 273/500 | Batch 20/202 | Rec 0.000712 | Seg 0.316410 | Elapsed 0.4m | ETA 3.7m
Epoch 273/500 | Batch 30/202 | Rec 0.000731 | Seg 0.314782 | Elapsed 0.6m | ETA 3.5m
Epoch 273/500 | Batch 40/202 | Rec 0.000712 | Seg 0.321224 | Elapsed 0.8m | ETA 3.3m
Epoch 273/500 | Batch 50/202 | Rec 0.000713 | Seg 0.321943 | Elapsed 1.0m | ETA 3.1m
Epoch 273/500 | Batch 60/202 | Rec 0.000684 | Seg 0.314277 | Elapsed 1.2m | ETA 2.9m
Epoch 273/500 | Batch 70/202 | Rec 0.000666 | Seg 0.307143 | Elapsed 1.4m | ETA 2.7m
Epoch 273/500 | Batch 80/202 | Rec 0.000681 | Seg 0.305013 | Elapsed 1.6m | ETA 2.5m
Epoch 273/500 | Batch 90/202 | Rec 0.000691 | Seg 0.315033 | Elapsed 1.8m | ETA 2.3m
Epoch 273/500 | Batch 100/202 | Rec 0.000700 | Seg 0.320219 | Elapsed 2.0m | ETA 2.1m
Epoch 273/500 | Batch 110/202 | Rec 0.000694 | Seg 0.319062 | Elapsed 2.2m | ETA 1.9m
Epoch 273/500 | Batch 120/202 | Rec 0.000692 | Seg 0.319809 | Elapsed 2.4m | ETA 1.7m
Epoch 273/500 | Batch 130/202 | Rec 0.000693 | Seg 0.323547 | Elapsed 2.6m | ETA 1.5m
Epoch 273/500 | Batch 140/202 | Rec 0.000696 | Seg 0.323471 | Elapsed 2.8m | ETA 1.3m
Epoch 273/500 | Batch 150/202 | Rec 0.000689 | Seg 0.324453 | Elapsed 3.0m | ETA 1.1m
Epoch 273/500 | Batch 160/202 | Rec 0.000686 | Seg 0.321890 | Elapsed 3.2m | ETA 0.9m
Epoch 273/500 | Batch 170/202 | Rec 0.000685 | Seg 0.322025 | Elapsed 3.4m | ETA 0.6m
Epoch 273/500 | Batch 180/202 | Rec 0.000677 | Seg 0.319608 | Elapsed 3.6m | ETA 0.4m
Epoch 273/500 | Batch 190/202 | Rec 0.000666 | Seg 0.315448 | Elapsed 3.9m | ETA 0.2m
Epoch 273/500 | Batch 200/202 | Rec 0.000664 | Seg 0.314310 | Elapsed 4.1m | ETA 0.0m
Epoch 273/500 | Batch 202/202 | Rec 0.000666 | Seg 0.314673 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:46:14,462 - INFO: Rec loss: 0.0006655673069232789
2026-09-24 09:46:14,462 - INFO: Seg loss: 0.31467262126210305
2026-09-24 09:46:14,462 - INFO: λ_rec: 1
2026-09-24 09:46:14,462 - INFO: λ_seg: 0.0001
2026-09-24 09:47:27,470 - INFO: -------------------Epoch: 273------------------------
2026-09-24 09:47:27,474 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.444362  0.973264  0.000148
2026-09-24 09:47:27,481 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995397  0.997643  0.996759  0.998629  0.995604
real potato   0.923932  0.960412  0.956033  0.964932  0.999905
fake potato   0.953578  0.976187  0.967304  0.985337  0.999965
real apple    0.694356  0.819562  0.979406  0.704644  0.998930
fake apple    0.529598  0.692422  0.988308  0.532937  0.998213
real orange   0.826810  0.905146  0.996521  0.829203  0.999771
fake orange   0.893773  0.943858  0.911660  0.978520  0.999667
real grape    0.660210  0.795283  0.846801  0.749762  0.999194
fake grape    0.897890  0.946148  0.949717  0.942705  0.999603
real lemon    0.639434  0.780017  0.742951  0.821085  0.999456
fake lemon    0.826500  0.904960  0.998781  0.827335  0.999633
real avocado  0.952981  0.975875  0.983492  0.968473  0.999956
fake avocado  0.425931  0.597365  0.999402  0.426039  0.999313
real pepper   0.864890  0.927501  0.903138  0.953321  0.999455
fake pepper   0.849500  0.918577  0.979274  0.865053  0.999635
real plant    0.832135  0.908327  0.933694  0.884397  0.998215
fake plant    0.844674  0.915747  0.890580  0.942485  0.999862
real banana   0.710791  0.830901  0.919868  0.757707  0.999307
fake banana   0.715461  0.834083  0.824832  0.843646  0.999383
real onion    0.602258  0.751715  0.612570  0.972809  0.999420
fake onion    0.939799  0.968916  0.987202  0.951391  0.999962
real unknown  0.505066  0.671109  0.518461  0.951336  0.999851
fake unknown  0.186535  0.314387  0.198269  0.759145  0.997211
total         0.750935  0.840702  0.873262  0.852648  0.999196
total(-bg)    0.739823  0.833568  0.867648  0.846012  0.999359
2026-09-24 09:47:28,014 - INFO: Epoch accounting: {'epoch': 273, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11321353, 48959, 68354, 146544, 134909, 82511, 70984, 167806, 169069, 89517, 77125, 39614, 43375, 182812, 95857, 82809, 22829, 101938, 92787, 92515, 49668, 8333, 48604], 'crops_with_class': [202, 28, 31, 36, 39, 28, 28, 33, 34, 37, 31, 13, 14, 46, 29, 15, 21, 29, 36, 36, 25, 9, 18], 'targeted_crops_by_class': [0, 7, 2, 4, 5, 4, 3, 9, 5, 5, 10, 3, 5, 4, 2, 6, 2, 7, 6, 7, 4, 4, 6], 'sampled_scene_counts': [0, 1, 2, 0, 1, 2, 1, 0, 1, 3, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 1, 3, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 3, 2, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 2, 2, 1, 2, 1, 0, 2, 1, 2, 0, 2, 3, 2, 1, 3, 1, 0, 2, 1, 1, 0, 1, 1, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 1, 1, 0, 1, 3, 2, 1, 1, 4, 4, 1, 2, 2, 1, 2, 0, 1, 2, 3, 0, 1, 1, 3, 0, 0, 1, 1, 2, 1, 2, 1, 1, 3, 2, 3, 1, 1, 1, 0, 0, 1, 2, 1, 1, 1, 5, 1], 'learning_rate': 4.325270925210363e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006655673069232789, 'train_segmentation_loss': 0.31467262126210305, 'val_foreground_miou_all22': 0.7398228806162584, 'val_psnr_ref1': 38.444362030029296, 'elapsed_seconds': 319.1065459251404, 'peak_cuda_allocated_gib': 7.507358551025391}

Epoch 274/500 | Batch 10/202 | Rec 0.000722 | Seg 0.295968 | Elapsed 0.2m | ETA 4.1m
Epoch 274/500 | Batch 20/202 | Rec 0.000654 | Seg 0.299754 | Elapsed 0.4m | ETA 3.8m
Epoch 274/500 | Batch 30/202 | Rec 0.000690 | Seg 0.309042 | Elapsed 0.6m | ETA 3.5m
Epoch 274/500 | Batch 40/202 | Rec 0.000709 | Seg 0.325623 | Elapsed 0.8m | ETA 3.3m
Epoch 274/500 | Batch 50/202 | Rec 0.000709 | Seg 0.326962 | Elapsed 1.0m | ETA 3.1m
Epoch 274/500 | Batch 60/202 | Rec 0.000703 | Seg 0.321067 | Elapsed 1.2m | ETA 2.9m
Epoch 274/500 | Batch 70/202 | Rec 0.000709 | Seg 0.330745 | Elapsed 1.4m | ETA 2.7m
Epoch 274/500 | Batch 80/202 | Rec 0.000718 | Seg 0.335524 | Elapsed 1.6m | ETA 2.5m
Epoch 274/500 | Batch 90/202 | Rec 0.000711 | Seg 0.328514 | Elapsed 1.8m | ETA 2.3m
Epoch 274/500 | Batch 100/202 | Rec 0.000711 | Seg 0.328700 | Elapsed 2.0m | ETA 2.1m
Epoch 274/500 | Batch 110/202 | Rec 0.000713 | Seg 0.333627 | Elapsed 2.2m | ETA 1.9m
Epoch 274/500 | Batch 120/202 | Rec 0.000702 | Seg 0.327422 | Elapsed 2.5m | ETA 1.7m
Epoch 274/500 | Batch 130/202 | Rec 0.000702 | Seg 0.328457 | Elapsed 2.7m | ETA 1.5m
Epoch 274/500 | Batch 140/202 | Rec 0.000700 | Seg 0.325815 | Elapsed 2.8m | ETA 1.3m
Epoch 274/500 | Batch 150/202 | Rec 0.000693 | Seg 0.320706 | Elapsed 3.1m | ETA 1.1m
Epoch 274/500 | Batch 160/202 | Rec 0.000698 | Seg 0.320626 | Elapsed 3.3m | ETA 0.9m
Epoch 274/500 | Batch 170/202 | Rec 0.000694 | Seg 0.319337 | Elapsed 3.4m | ETA 0.6m
Epoch 274/500 | Batch 180/202 | Rec 0.000693 | Seg 0.320552 | Elapsed 3.7m | ETA 0.4m
Epoch 274/500 | Batch 190/202 | Rec 0.000689 | Seg 0.319796 | Elapsed 3.9m | ETA 0.2m
Epoch 274/500 | Batch 200/202 | Rec 0.000681 | Seg 0.315856 | Elapsed 4.1m | ETA 0.0m
Epoch 274/500 | Batch 202/202 | Rec 0.000681 | Seg 0.315772 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:51:34,046 - INFO: Rec loss: 0.0006811808358755719
2026-09-24 09:51:34,046 - INFO: Seg loss: 0.3157718824130474
2026-09-24 09:51:34,046 - INFO: λ_rec: 1
2026-09-24 09:51:34,046 - INFO: λ_seg: 0.0001
2026-09-24 09:52:47,613 - INFO: -------------------Epoch: 274------------------------
2026-09-24 09:52:47,617 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.679963  0.973312  0.000141
2026-09-24 09:52:47,623 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995700  0.997795  0.997160  0.998531  0.995895
real potato   0.614750  0.761371  0.992621  0.617572  0.999537
fake potato   0.914732  0.955417  0.979538  0.932551  0.999937
real apple    0.737580  0.848924  0.839898  0.858249  0.998947
fake apple    0.577443  0.732079  0.993078  0.579777  0.998398
real orange   0.872486  0.931851  0.998148  0.873900  0.999832
fake orange   0.919629  0.958082  0.938282  0.978840  0.999755
real grape    0.745177  0.853934  0.879551  0.829862  0.999408
fake grape    0.887480  0.940336  0.936653  0.944149  0.999557
real lemon    0.568679  0.724994  0.594792  0.928330  0.999173
fake lemon    0.825827  0.904557  0.996960  0.827912  0.999631
real avocado  0.878788  0.935434  0.914783  0.957143  0.999877
fake avocado  0.494773  0.661960  0.999485  0.494899  0.999395
real pepper   0.848816  0.918176  0.899912  0.937302  0.999389
fake pepper   0.817542  0.899563  0.967369  0.840727  0.999553
real plant    0.865494  0.927848  0.932949  0.922901  0.998565
fake plant    0.820824  0.901546  0.883511  0.920437  0.999840
real banana   0.540600  0.701757  0.883019  0.582303  0.998888
fake banana   0.741043  0.851213  0.843193  0.859489  0.999447
real onion    0.647305  0.785846  0.741718  0.835670  0.999589
fake onion    0.941515  0.969827  0.990668  0.949940  0.999963
real unknown  0.807692  0.893567  0.850129  0.941794  0.999964
fake unknown  0.217103  0.356717  0.232739  0.763673  0.997680
total         0.751347  0.844035  0.882007  0.842433  0.999227
total(-bg)    0.740240  0.837045  0.876773  0.835337  0.999378
2026-09-24 09:52:48,164 - INFO: Epoch accounting: {'epoch': 274, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11292419, 55712, 75587, 137877, 153706, 67941, 81939, 141203, 229403, 72479, 79592, 38890, 30719, 187372, 89564, 106111, 26301, 62405, 79331, 85170, 71956, 15740, 56855], 'crops_with_class': [202, 32, 34, 36, 41, 21, 28, 30, 38, 33, 31, 14, 12, 49, 25, 20, 23, 20, 33, 35, 32, 17, 26], 'targeted_crops_by_class': [0, 3, 7, 5, 7, 2, 5, 6, 5, 7, 9, 5, 2, 3, 3, 2, 3, 3, 6, 5, 3, 6, 8], 'sampled_scene_counts': [0, 1, 0, 1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 2, 2, 1, 0, 1, 1, 1, 4, 3, 1, 2, 1, 1, 0, 0, 1, 2, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 3, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 1, 2, 1, 1, 0, 0, 2, 0, 2, 1, 0, 1, 0, 1, 1, 0, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 2, 0, 2, 1, 2, 0, 2, 2, 2, 3, 0, 1, 3, 1, 1, 1, 1, 0, 3, 1, 2, 1, 1, 1, 1, 0, 0, 1, 2, 2, 2, 1, 1, 3, 0, 0, 0, 2, 2, 2, 1, 1, 4, 3, 5, 1, 3, 4, 1, 1, 1, 1, 0, 4, 1, 0, 0, 1, 0, 1, 2, 0, 2, 1, 1, 3, 2, 2, 0, 2, 2, 2, 1, 3, 0, 2, 1, 0, 0, 1, 1, 2, 2, 1, 2], 'learning_rate': 4.294246222020637e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0006811808358755719, 'train_segmentation_loss': 0.3157718824130474, 'val_foreground_miou_all22': 0.7402398778038498, 'val_psnr_ref1': 38.67996276855469, 'elapsed_seconds': 320.14258551597595, 'peak_cuda_allocated_gib': 7.505649566650391}

Epoch 275/500 | Batch 10/202 | Rec 0.000713 | Seg 0.369955 | Elapsed 0.2m | ETA 3.9m
Epoch 275/500 | Batch 20/202 | Rec 0.000789 | Seg 0.361631 | Elapsed 0.4m | ETA 3.7m
Epoch 275/500 | Batch 30/202 | Rec 0.000728 | Seg 0.343011 | Elapsed 0.6m | ETA 3.5m
Epoch 275/500 | Batch 40/202 | Rec 0.000730 | Seg 0.341095 | Elapsed 0.8m | ETA 3.3m
Epoch 275/500 | Batch 50/202 | Rec 0.000688 | Seg 0.318445 | Elapsed 1.0m | ETA 3.1m
Epoch 275/500 | Batch 60/202 | Rec 0.000681 | Seg 0.320024 | Elapsed 1.2m | ETA 2.9m
Epoch 275/500 | Batch 70/202 | Rec 0.000680 | Seg 0.317361 | Elapsed 1.4m | ETA 2.7m
Epoch 275/500 | Batch 80/202 | Rec 0.000692 | Seg 0.323496 | Elapsed 1.6m | ETA 2.5m
Epoch 275/500 | Batch 90/202 | Rec 0.000687 | Seg 0.319731 | Elapsed 1.8m | ETA 2.3m
Epoch 275/500 | Batch 100/202 | Rec 0.000675 | Seg 0.315156 | Elapsed 2.0m | ETA 2.1m
Epoch 275/500 | Batch 110/202 | Rec 0.000670 | Seg 0.311623 | Elapsed 2.2m | ETA 1.9m
Epoch 275/500 | Batch 120/202 | Rec 0.000668 | Seg 0.310560 | Elapsed 2.4m | ETA 1.7m
Epoch 275/500 | Batch 130/202 | Rec 0.000669 | Seg 0.312088 | Elapsed 2.6m | ETA 1.5m
Epoch 275/500 | Batch 140/202 | Rec 0.000668 | Seg 0.309915 | Elapsed 2.8m | ETA 1.3m
Epoch 275/500 | Batch 150/202 | Rec 0.000666 | Seg 0.306463 | Elapsed 3.1m | ETA 1.1m
Epoch 275/500 | Batch 160/202 | Rec 0.000670 | Seg 0.309863 | Elapsed 3.3m | ETA 0.9m
Epoch 275/500 | Batch 170/202 | Rec 0.000673 | Seg 0.311504 | Elapsed 3.5m | ETA 0.7m
Epoch 275/500 | Batch 180/202 | Rec 0.000661 | Seg 0.305864 | Elapsed 3.7m | ETA 0.4m
Epoch 275/500 | Batch 190/202 | Rec 0.000680 | Seg 0.314922 | Elapsed 3.9m | ETA 0.2m
Epoch 275/500 | Batch 200/202 | Rec 0.000681 | Seg 0.315400 | Elapsed 4.1m | ETA 0.0m
Epoch 275/500 | Batch 202/202 | Rec 0.000682 | Seg 0.317102 | Elapsed 4.1m | ETA 0.0m

2026-09-24 09:56:55,439 - INFO: Rec loss: 0.0006818901712165933
2026-09-24 09:56:55,439 - INFO: Seg loss: 0.3171017207389716
2026-09-24 09:56:55,440 - INFO: λ_rec: 1
2026-09-24 09:56:55,440 - INFO: λ_seg: 0.0001
2026-09-24 09:58:08,702 - INFO: -------------------Epoch: 275------------------------
2026-09-24 09:58:08,706 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.298367  0.97262  0.000154
2026-09-24 09:58:08,713 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995603  0.997746  0.996842  0.998753  0.995800
real potato   0.843404  0.915001  0.973400  0.863300  0.999808
fake potato   0.852456  0.920302  0.956198  0.887097  0.999888
real apple    0.732908  0.845821  0.886980  0.808403  0.998984
fake apple    0.522887  0.686660  0.992739  0.524895  0.998192
real orange   0.923077  0.959950  0.995646  0.926818  0.999898
fake orange   0.943518  0.970888  0.965236  0.976708  0.999833
real grape    0.646821  0.785490  0.891819  0.701893  0.999200
fake grape    0.885598  0.939279  0.951350  0.927608  0.999557
real lemon    0.559797  0.717733  0.616575  0.858738  0.999206
fake lemon    0.813950  0.897384  0.998850  0.814713  0.999606
real avocado  0.926646  0.961877  0.969793  0.954187  0.999930
fake avocado  0.462519  0.632453  0.999449  0.462637  0.999357
real pepper   0.914736  0.955419  0.971175  0.940264  0.999679
fake pepper   0.922715  0.959754  0.964270  0.955381  0.999809
real plant    0.846517  0.916830  0.911591  0.922230  0.998327
fake plant    0.861258  0.925408  0.979448  0.877109  0.999888
real banana   0.526333  0.689622  0.901271  0.558536  0.998871
fake banana   0.747784  0.855644  0.872436  0.839582  0.999479
real onion    0.652204  0.789447  0.671844  0.957102  0.999539
fake onion    0.935214  0.966473  0.987879  0.946070  0.999959
real unknown  0.889699  0.941580  0.952195  0.931298  0.999982
fake unknown  0.195053  0.326400  0.206937  0.772546  0.997314
total         0.765248  0.850311  0.896257  0.843733  0.999222
total(-bg)    0.754777  0.843610  0.891685  0.836687  0.999377
2026-09-24 09:58:09,274 - INFO: Epoch accounting: {'epoch': 275, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11294095, 59981, 59404, 117105, 90868, 96424, 63449, 167379, 152871, 66430, 54438, 55199, 36372, 252744, 151398, 170056, 24170, 92539, 62716, 64985, 34266, 9248, 62135], 'crops_with_class': [202, 34, 28, 34, 28, 29, 24, 32, 32, 31, 27, 18, 12, 59, 37, 22, 21, 25, 26, 34, 22, 11, 24], 'targeted_crops_by_class': [0, 3, 4, 4, 4, 3, 1, 5, 2, 10, 8, 7, 4, 2, 5, 4, 4, 5, 1, 2, 5, 2, 8], 'sampled_scene_counts': [1, 1, 1, 0, 1, 1, 1, 1, 0, 4, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 2, 1, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 3, 1, 3, 1, 0, 0, 2, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 2, 0, 4, 0, 2, 1, 0, 0, 1, 2, 1, 1, 1, 0, 3, 0, 2, 1, 2, 1, 3, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 3, 3, 2, 4, 0, 0, 2, 5, 1, 3, 1, 1, 1, 4, 1, 2, 1, 0, 1, 3, 1, 1, 2, 2, 1, 1, 0, 2, 3, 2, 1, 3, 0, 0, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2], 'learning_rate': 4.2632498742602184e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006818901712165933, 'train_segmentation_loss': 0.3171017207389716, 'val_foreground_miou_all22': 0.7547769556411213, 'val_psnr_ref1': 38.29836700439453, 'elapsed_seconds': 321.1023497581482, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 276/500 | Batch 10/202 | Rec 0.000644 | Seg 0.303037 | Elapsed 0.2m | ETA 4.0m
Epoch 276/500 | Batch 20/202 | Rec 0.000629 | Seg 0.304040 | Elapsed 0.4m | ETA 3.7m
Epoch 276/500 | Batch 30/202 | Rec 0.000618 | Seg 0.285266 | Elapsed 0.6m | ETA 3.6m
Epoch 276/500 | Batch 40/202 | Rec 0.000678 | Seg 0.292507 | Elapsed 0.8m | ETA 3.4m
Epoch 276/500 | Batch 50/202 | Rec 0.000644 | Seg 0.283736 | Elapsed 1.0m | ETA 3.2m
Epoch 276/500 | Batch 60/202 | Rec 0.000659 | Seg 0.292112 | Elapsed 1.2m | ETA 2.9m
Epoch 276/500 | Batch 70/202 | Rec 0.000655 | Seg 0.294472 | Elapsed 1.4m | ETA 2.7m
Epoch 276/500 | Batch 80/202 | Rec 0.000653 | Seg 0.296041 | Elapsed 1.6m | ETA 2.5m
Epoch 276/500 | Batch 90/202 | Rec 0.000663 | Seg 0.295111 | Elapsed 1.8m | ETA 2.3m
Epoch 276/500 | Batch 100/202 | Rec 0.000677 | Seg 0.298342 | Elapsed 2.1m | ETA 2.1m
Epoch 276/500 | Batch 110/202 | Rec 0.000679 | Seg 0.306421 | Elapsed 2.3m | ETA 1.9m
Epoch 276/500 | Batch 120/202 | Rec 0.000681 | Seg 0.306452 | Elapsed 2.5m | ETA 1.7m
Epoch 276/500 | Batch 130/202 | Rec 0.000675 | Seg 0.307993 | Elapsed 2.7m | ETA 1.5m
Epoch 276/500 | Batch 140/202 | Rec 0.000674 | Seg 0.309594 | Elapsed 2.9m | ETA 1.3m
Epoch 276/500 | Batch 150/202 | Rec 0.000679 | Seg 0.312767 | Elapsed 3.1m | ETA 1.1m
Epoch 276/500 | Batch 160/202 | Rec 0.000678 | Seg 0.313025 | Elapsed 3.3m | ETA 0.9m
Epoch 276/500 | Batch 170/202 | Rec 0.000686 | Seg 0.314296 | Elapsed 3.5m | ETA 0.7m
Epoch 276/500 | Batch 180/202 | Rec 0.000688 | Seg 0.313869 | Elapsed 3.7m | ETA 0.5m
Epoch 276/500 | Batch 190/202 | Rec 0.000696 | Seg 0.318714 | Elapsed 3.9m | ETA 0.2m
Epoch 276/500 | Batch 200/202 | Rec 0.000698 | Seg 0.320894 | Elapsed 4.1m | ETA 0.0m
Epoch 276/500 | Batch 202/202 | Rec 0.000702 | Seg 0.323230 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:02:17,447 - INFO: Rec loss: 0.00070177549643253
2026-09-24 10:02:17,447 - INFO: Seg loss: 0.32322962312857706
2026-09-24 10:02:17,447 - INFO: λ_rec: 1
2026-09-24 10:02:17,447 - INFO: λ_seg: 0.0001
2026-09-24 10:03:28,832 - INFO: -------------------Epoch: 276------------------------
2026-09-24 10:03:28,837 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.316355  0.972884  0.000153
2026-09-24 10:03:28,844 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995626  0.997758  0.997001  0.998616  0.995823
real potato   0.897160  0.945743  0.979377  0.914435  0.999875
fake potato   0.954620  0.976733  0.979768  0.973816  0.999966
real apple    0.811311  0.895778  0.975764  0.827996  0.999336
fake apple    0.676950  0.807310  0.989214  0.681984  0.998771
real orange   0.893323  0.943606  0.995502  0.896943  0.999859
fake orange   0.923792  0.960337  0.951790  0.969140  0.999771
real grape    0.705127  0.827018  0.932984  0.742746  0.999352
fake grape    0.893266  0.943574  0.930678  0.956936  0.999577
real lemon    0.593736  0.745037  0.669914  0.839263  0.999325
fake lemon    0.838141  0.911895  0.996920  0.840317  0.999657
real avocado  0.856723  0.922783  0.890756  0.957307  0.999851
fake avocado  0.641764  0.781751  0.999603  0.641928  0.999571
real pepper   0.852374  0.920254  0.902906  0.938386  0.999406
fake pepper   0.832233  0.908386  0.958757  0.863133  0.999585
real plant    0.860526  0.924985  0.923740  0.926333  0.998498
fake plant    0.862174  0.925936  0.927322  0.924655  0.999882
real banana   0.614283  0.761011  0.930774  0.643691  0.999092
fake banana   0.672959  0.804463  0.782350  0.827969  0.999260
real onion    0.655225  0.791656  0.678107  0.951022  0.999548
fake onion    0.922381  0.959573  0.983498  0.936880  0.999950
real unknown  0.841667  0.913977  0.869191  0.963740  0.999971
fake unknown  0.243102  0.391082  0.271305  0.700471  0.998162
total         0.784281  0.867854  0.892053  0.865987  0.999308
total(-bg)    0.774674  0.861950  0.887283  0.859959  0.999467
2026-09-24 10:03:29,547 - INFO: Epoch accounting: {'epoch': 276, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11245070, 48269, 66014, 140730, 127214, 63151, 60686, 183110, 257185, 78898, 46150, 48904, 47660, 210338, 96622, 189214, 24815, 64871, 68856, 72160, 50093, 8047, 40215], 'crops_with_class': [202, 29, 28, 36, 35, 19, 21, 34, 43, 35, 26, 18, 14, 54, 27, 28, 24, 20, 26, 32, 26, 7, 19], 'targeted_crops_by_class': [0, 1, 7, 5, 2, 2, 3, 4, 4, 9, 3, 7, 2, 2, 4, 5, 6, 3, 6, 4, 3, 2, 3], 'sampled_scene_counts': [0, 2, 1, 1, 0, 0, 0, 1, 1, 2, 2, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 3, 0, 0, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 3, 2, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 3, 1, 2, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 2, 1, 3, 1, 1, 1, 2, 2, 4, 2, 1, 1, 2, 0, 0, 1, 2, 1, 2, 0, 1, 1, 1, 3, 2, 0, 2, 0, 2, 3, 2, 1, 1, 2, 3, 1, 1, 1, 1, 1, 3, 2, 0, 3, 1, 5, 1, 1, 0, 2, 1, 1, 1, 0, 0, 0, 1, 3, 1, 1, 1, 3, 2, 2, 3, 1, 1, 1, 1, 1, 0, 5, 0, 2, 2, 0, 0, 1, 0, 2, 0, 2], 'learning_rate': 4.232283105611843e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.00070177549643253, 'train_segmentation_loss': 0.32322962312857706, 'val_foreground_miou_all22': 0.7746742979268647, 'val_psnr_ref1': 38.31635482788086, 'elapsed_seconds': 320.26545906066895, 'peak_cuda_allocated_gib': 7.508365631103516}

Epoch 277/500 | Batch 10/202 | Rec 0.000768 | Seg 0.349518 | Elapsed 0.2m | ETA 3.9m
Epoch 277/500 | Batch 20/202 | Rec 0.000679 | Seg 0.298102 | Elapsed 0.4m | ETA 3.8m
Epoch 277/500 | Batch 30/202 | Rec 0.000675 | Seg 0.304791 | Elapsed 0.6m | ETA 3.6m
Epoch 277/500 | Batch 40/202 | Rec 0.000697 | Seg 0.317891 | Elapsed 0.8m | ETA 3.3m
Epoch 277/500 | Batch 50/202 | Rec 0.000725 | Seg 0.331423 | Elapsed 1.0m | ETA 3.1m
Epoch 277/500 | Batch 60/202 | Rec 0.000728 | Seg 0.326501 | Elapsed 1.2m | ETA 2.9m
Epoch 277/500 | Batch 70/202 | Rec 0.000740 | Seg 0.334544 | Elapsed 1.4m | ETA 2.7m
Epoch 277/500 | Batch 80/202 | Rec 0.000736 | Seg 0.336022 | Elapsed 1.6m | ETA 2.5m
Epoch 277/500 | Batch 90/202 | Rec 0.000721 | Seg 0.331531 | Elapsed 1.8m | ETA 2.3m
Epoch 277/500 | Batch 100/202 | Rec 0.000744 | Seg 0.330448 | Elapsed 2.0m | ETA 2.1m
Epoch 277/500 | Batch 110/202 | Rec 0.000742 | Seg 0.337462 | Elapsed 2.2m | ETA 1.9m
Epoch 277/500 | Batch 120/202 | Rec 0.000733 | Seg 0.333171 | Elapsed 2.4m | ETA 1.7m
Epoch 277/500 | Batch 130/202 | Rec 0.000722 | Seg 0.332539 | Elapsed 2.6m | ETA 1.5m
Epoch 277/500 | Batch 140/202 | Rec 0.000713 | Seg 0.329228 | Elapsed 2.8m | ETA 1.3m
Epoch 277/500 | Batch 150/202 | Rec 0.000700 | Seg 0.324886 | Elapsed 3.0m | ETA 1.1m
Epoch 277/500 | Batch 160/202 | Rec 0.000695 | Seg 0.323954 | Elapsed 3.2m | ETA 0.8m
Epoch 277/500 | Batch 170/202 | Rec 0.000690 | Seg 0.321101 | Elapsed 3.4m | ETA 0.6m
Epoch 277/500 | Batch 180/202 | Rec 0.000699 | Seg 0.326389 | Elapsed 3.6m | ETA 0.4m
Epoch 277/500 | Batch 190/202 | Rec 0.000700 | Seg 0.324206 | Elapsed 3.8m | ETA 0.2m
Epoch 277/500 | Batch 200/202 | Rec 0.000702 | Seg 0.325346 | Elapsed 4.0m | ETA 0.0m
Epoch 277/500 | Batch 202/202 | Rec 0.000705 | Seg 0.327306 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:07:34,442 - INFO: Rec loss: 0.0007054572810429278
2026-09-24 10:07:34,442 - INFO: Seg loss: 0.32730606106100696
2026-09-24 10:07:34,442 - INFO: λ_rec: 1
2026-09-24 10:07:34,442 - INFO: λ_seg: 0.0001
2026-09-24 10:08:45,935 - INFO: -------------------Epoch: 277------------------------
2026-09-24 10:08:45,939 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.442908  0.972831  0.000149
2026-09-24 10:08:45,946 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995848  0.997870  0.997275  0.998566  0.996037
real potato   0.923281  0.960060  0.943275  0.977557  0.999903
fake potato   0.949749  0.974177  0.959196  0.989736  0.999962
real apple    0.818702  0.900265  0.993276  0.823264  0.999371
fake apple    0.575880  0.730821  0.993196  0.578160  0.998392
real orange   0.903078  0.949021  0.990927  0.910607  0.999871
fake orange   0.926903  0.962015  0.947303  0.977295  0.999779
real grape    0.795132  0.885826  0.955125  0.825988  0.999556
fake grape    0.895103  0.944598  0.943870  0.945428  0.999590
real lemon    0.616636  0.762813  0.753068  0.772916  0.999435
fake lemon    0.811757  0.896050  0.998582  0.812694  0.999601
real avocado  0.851197  0.919568  0.884925  0.957143  0.999845
fake avocado  0.587073  0.739772  0.999566  0.587223  0.999506
real pepper   0.864355  0.927193  0.916918  0.937802  0.999462
fake pepper   0.864733  0.927410  0.949443  0.906472  0.999662
real plant    0.877533  0.934722  0.942734  0.926943  0.998706
fake plant    0.842729  0.914604  0.890645  0.939992  0.999860
real banana   0.710454  0.830671  0.917214  0.759134  0.999305
fake banana   0.669739  0.802158  0.737010  0.880060  0.999202
real onion    0.608221  0.756342  0.620045  0.969600  0.999436
fake onion    0.800517  0.889158  0.817739  0.974365  0.999847
real unknown  0.886589  0.939835  0.939885  0.939885  0.999981
fake unknown  0.188171  0.316701  0.215566  0.596885  0.997830
total         0.781016  0.863550  0.882904  0.869031  0.999310
total(-bg)    0.771251  0.857445  0.877705  0.863143  0.999459
2026-09-24 10:08:46,480 - INFO: Epoch accounting: {'epoch': 277, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11218525, 43462, 73207, 151097, 170585, 72901, 80009, 120612, 212176, 53182, 38319, 40357, 25236, 230485, 119213, 153510, 29271, 80254, 83222, 93534, 58531, 16965, 73619], 'crops_with_class': [202, 27, 31, 35, 39, 25, 27, 27, 37, 29, 20, 12, 11, 56, 28, 21, 27, 23, 32, 34, 29, 18, 35], 'targeted_crops_by_class': [0, 2, 2, 3, 10, 6, 5, 6, 8, 3, 3, 4, 3, 10, 6, 4, 4, 1, 6, 4, 7, 6, 3], 'sampled_scene_counts': [1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 2, 1, 0, 3, 0, 0, 1, 0, 2, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2, 2, 1, 1, 0, 1, 1, 2, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 2, 2, 1, 3, 0, 0, 2, 1, 1, 1, 1, 0, 1, 3, 2, 1, 1, 3, 0, 3, 3, 1, 5, 3, 1, 3, 0, 2, 2, 1, 3, 1, 0, 1, 0, 0, 4, 7, 3, 2, 2, 0, 1, 2, 1, 1, 1, 2, 3, 1, 1, 1, 0, 1, 1, 0, 2, 3, 2, 1, 3, 2, 2, 1, 2, 0, 2, 1, 0, 2, 1, 0, 1, 2, 2, 2, 0, 0, 4], 'learning_rate': 4.201347138590513e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007054572810429278, 'train_segmentation_loss': 0.32730606106100696, 'val_foreground_miou_all22': 0.7712513011166003, 'val_psnr_ref1': 38.44290786743164, 'elapsed_seconds': 316.9242744445801, 'peak_cuda_allocated_gib': 7.510288238525391}

Epoch 278/500 | Batch 10/202 | Rec 0.000696 | Seg 0.274041 | Elapsed 0.2m | ETA 3.9m
Epoch 278/500 | Batch 20/202 | Rec 0.000652 | Seg 0.272752 | Elapsed 0.4m | ETA 3.7m
Epoch 278/500 | Batch 30/202 | Rec 0.000613 | Seg 0.270073 | Elapsed 0.6m | ETA 3.5m
Epoch 278/500 | Batch 40/202 | Rec 0.000631 | Seg 0.288889 | Elapsed 0.8m | ETA 3.3m
Epoch 278/500 | Batch 50/202 | Rec 0.000630 | Seg 0.274787 | Elapsed 1.0m | ETA 3.1m
Epoch 278/500 | Batch 60/202 | Rec 0.000632 | Seg 0.277953 | Elapsed 1.2m | ETA 2.9m
Epoch 278/500 | Batch 70/202 | Rec 0.000637 | Seg 0.282185 | Elapsed 1.4m | ETA 2.7m
Epoch 278/500 | Batch 80/202 | Rec 0.000674 | Seg 0.288582 | Elapsed 1.6m | ETA 2.5m
Epoch 278/500 | Batch 90/202 | Rec 0.000671 | Seg 0.288836 | Elapsed 1.8m | ETA 2.3m
Epoch 278/500 | Batch 100/202 | Rec 0.000680 | Seg 0.293809 | Elapsed 2.0m | ETA 2.1m
Epoch 278/500 | Batch 110/202 | Rec 0.000681 | Seg 0.293169 | Elapsed 2.2m | ETA 1.9m
Epoch 278/500 | Batch 120/202 | Rec 0.000683 | Seg 0.296432 | Elapsed 2.4m | ETA 1.7m
Epoch 278/500 | Batch 130/202 | Rec 0.000682 | Seg 0.297140 | Elapsed 2.6m | ETA 1.5m
Epoch 278/500 | Batch 140/202 | Rec 0.000678 | Seg 0.302291 | Elapsed 2.8m | ETA 1.2m
Epoch 278/500 | Batch 150/202 | Rec 0.000687 | Seg 0.306159 | Elapsed 3.0m | ETA 1.0m
Epoch 278/500 | Batch 160/202 | Rec 0.000684 | Seg 0.305000 | Elapsed 3.2m | ETA 0.8m
Epoch 278/500 | Batch 170/202 | Rec 0.000699 | Seg 0.311770 | Elapsed 3.4m | ETA 0.6m
Epoch 278/500 | Batch 180/202 | Rec 0.000697 | Seg 0.315070 | Elapsed 3.6m | ETA 0.4m
Epoch 278/500 | Batch 190/202 | Rec 0.000689 | Seg 0.310484 | Elapsed 3.8m | ETA 0.2m
Epoch 278/500 | Batch 200/202 | Rec 0.000686 | Seg 0.309227 | Elapsed 4.0m | ETA 0.0m
Epoch 278/500 | Batch 202/202 | Rec 0.000690 | Seg 0.311603 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:12:50,893 - INFO: Rec loss: 0.0006899012645734197
2026-09-24 10:12:50,893 - INFO: Seg loss: 0.3116034334617676
2026-09-24 10:12:50,893 - INFO: λ_rec: 1
2026-09-24 10:12:50,893 - INFO: λ_seg: 0.0001
2026-09-24 10:14:03,355 - INFO: -------------------Epoch: 278------------------------
2026-09-24 10:14:03,359 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.36916  0.973187  0.000152
2026-09-24 10:14:03,366 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995606  0.997748  0.996554  0.999045  0.995802
real potato   0.930912  0.964170  0.995653  0.934711  0.999917
fake potato   0.952234  0.975483  0.982370  0.968789  0.999965
real apple    0.766731  0.867917  0.990807  0.772225  0.999189
fake apple    0.604342  0.753335  0.939443  0.628839  0.998446
real orange   0.926272  0.961675  0.996153  0.929597  0.999902
fake orange   0.939575  0.968796  0.963131  0.974630  0.999821
real grape    0.633693  0.775732  0.984707  0.639991  0.999228
fake grape    0.903082  0.949023  0.953041  0.945139  0.999625
real lemon    0.569311  0.725507  0.611165  0.892625  0.999206
fake lemon    0.840714  0.913416  0.998119  0.842048  0.999662
real avocado  0.943729  0.971000  0.992964  0.950082  0.999947
fake avocado  0.688385  0.815387  0.999815  0.688472  0.999627
real pepper   0.903276  0.949130  0.931731  0.967295  0.999621
fake pepper   0.900210  0.947435  0.964025  0.931502  0.999754
real plant    0.823976  0.903444  0.923268  0.884550  0.998110
fake plant    0.861634  0.925625  0.979456  0.877492  0.999888
real banana   0.565676  0.722549  0.923776  0.593372  0.998976
fake banana   0.748535  0.856136  0.875987  0.837259  0.999483
real onion    0.718995  0.836480  0.751717  0.942915  0.999667
fake onion    0.935291  0.966514  0.986650  0.947279  0.999959
real unknown  0.912149  0.954007  0.977956  0.931298  0.999986
fake unknown  0.228611  0.372109  0.244035  0.783412  0.997773
total         0.795345  0.872722  0.911414  0.863590  0.999285
total(-bg)    0.786242  0.867040  0.907544  0.857433  0.999443
2026-09-24 10:14:04,061 - INFO: Epoch accounting: {'epoch': 278, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11283155, 47213, 47095, 129119, 174675, 62551, 38383, 151141, 165696, 89935, 71339, 60422, 33207, 227434, 153331, 175570, 27755, 65024, 51386, 79550, 56302, 8225, 39764], 'crops_with_class': [202, 29, 23, 37, 45, 20, 17, 27, 33, 36, 25, 22, 11, 55, 34, 24, 24, 18, 24, 34, 24, 11, 19], 'targeted_crops_by_class': [0, 3, 6, 6, 5, 3, 6, 4, 5, 4, 8, 7, 6, 2, 5, 5, 4, 5, 6, 4, 6, 4, 3], 'sampled_scene_counts': [1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 3, 0, 1, 1, 1, 0, 1, 3, 1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 2, 0, 2, 1, 3, 2, 2, 1, 1, 2, 4, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 3, 1, 1, 3, 0, 1, 0, 3, 0, 1, 3, 1, 1, 2, 3, 3, 1, 1, 0, 3, 1, 0, 1, 3, 1, 1, 0, 3, 4, 2, 0, 1, 2, 0, 1, 3, 2, 1, 0, 1, 0, 0, 0, 2, 1, 2, 0, 0, 3, 1, 0, 3, 1, 0, 0, 1, 2, 3, 1, 0, 0, 2, 0, 4, 2, 1], 'learning_rate': 4.1704431944952346e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006899012645734197, 'train_segmentation_loss': 0.3116034334617676, 'val_foreground_miou_all22': 0.7862424401936461, 'val_psnr_ref1': 38.36915969848633, 'elapsed_seconds': 317.5734043121338, 'peak_cuda_allocated_gib': 7.509799957275391}

Epoch 279/500 | Batch 10/202 | Rec 0.000720 | Seg 0.418389 | Elapsed 0.2m | ETA 3.8m
Epoch 279/500 | Batch 20/202 | Rec 0.000728 | Seg 0.400347 | Elapsed 0.4m | ETA 3.6m
Epoch 279/500 | Batch 30/202 | Rec 0.000690 | Seg 0.363332 | Elapsed 0.6m | ETA 3.5m
Epoch 279/500 | Batch 40/202 | Rec 0.000705 | Seg 0.357790 | Elapsed 0.8m | ETA 3.3m
Epoch 279/500 | Batch 50/202 | Rec 0.000680 | Seg 0.354015 | Elapsed 1.0m | ETA 3.1m
Epoch 279/500 | Batch 60/202 | Rec 0.000675 | Seg 0.333589 | Elapsed 1.2m | ETA 2.9m
Epoch 279/500 | Batch 70/202 | Rec 0.000667 | Seg 0.329495 | Elapsed 1.4m | ETA 2.7m
Epoch 279/500 | Batch 80/202 | Rec 0.000667 | Seg 0.329723 | Elapsed 1.6m | ETA 2.5m
Epoch 279/500 | Batch 90/202 | Rec 0.000680 | Seg 0.322724 | Elapsed 1.8m | ETA 2.3m
Epoch 279/500 | Batch 100/202 | Rec 0.000674 | Seg 0.320729 | Elapsed 2.0m | ETA 2.1m
Epoch 279/500 | Batch 110/202 | Rec 0.000692 | Seg 0.324781 | Elapsed 2.2m | ETA 1.9m
Epoch 279/500 | Batch 120/202 | Rec 0.000692 | Seg 0.324762 | Elapsed 2.4m | ETA 1.7m
Epoch 279/500 | Batch 130/202 | Rec 0.000699 | Seg 0.327355 | Elapsed 2.6m | ETA 1.5m
Epoch 279/500 | Batch 140/202 | Rec 0.000705 | Seg 0.326404 | Elapsed 2.8m | ETA 1.3m
Epoch 279/500 | Batch 150/202 | Rec 0.000696 | Seg 0.321418 | Elapsed 3.1m | ETA 1.1m
Epoch 279/500 | Batch 160/202 | Rec 0.000704 | Seg 0.323253 | Elapsed 3.3m | ETA 0.9m
Epoch 279/500 | Batch 170/202 | Rec 0.000701 | Seg 0.322532 | Elapsed 3.5m | ETA 0.7m
Epoch 279/500 | Batch 180/202 | Rec 0.000698 | Seg 0.319273 | Elapsed 3.7m | ETA 0.4m
Epoch 279/500 | Batch 190/202 | Rec 0.000700 | Seg 0.321525 | Elapsed 3.9m | ETA 0.2m
Epoch 279/500 | Batch 200/202 | Rec 0.000700 | Seg 0.319367 | Elapsed 4.1m | ETA 0.0m
Epoch 279/500 | Batch 202/202 | Rec 0.000700 | Seg 0.320076 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:18:10,149 - INFO: Rec loss: 0.000699793005887751
2026-09-24 10:18:10,149 - INFO: Seg loss: 0.32007639541631877
2026-09-24 10:18:10,149 - INFO: λ_rec: 1
2026-09-24 10:18:10,150 - INFO: λ_seg: 0.0001
2026-09-24 10:19:22,738 - INFO: -------------------Epoch: 279------------------------
2026-09-24 10:19:22,742 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.635042  0.973512  0.000143
2026-09-24 10:19:22,748 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995295  0.997592  0.996278  0.999009  0.995504
real potato   0.931056  0.964247  0.980240  0.948865  0.999916
fake potato   0.945595  0.971987  0.968399  0.975702  0.999959
real apple    0.743238  0.852661  0.994577  0.746263  0.999111
fake apple    0.666105  0.799547  0.989274  0.670951  0.998730
real orange   0.874121  0.932783  0.994883  0.878069  0.999833
fake orange   0.914898  0.955508  0.929370  0.983264  0.999738
real grape    0.746620  0.854882  0.893671  0.819411  0.999419
fake grape    0.892986  0.943418  0.951161  0.935899  0.999585
real lemon    0.508285  0.673944  0.540105  0.896131  0.998981
fake lemon    0.841579  0.913926  0.996509  0.844068  0.999664
real avocado  0.900327  0.947499  0.944381  0.950739  0.999902
fake avocado  0.555088  0.713853  1.000000  0.555088  0.999468
real pepper   0.894160  0.944073  0.941655  0.946604  0.999590
fake pepper   0.874618  0.933066  0.950046  0.916779  0.999687
real plant    0.843509  0.915063  0.956255  0.877365  0.998372
fake plant    0.793364  0.884727  0.903981  0.866373  0.999820
real banana   0.473698  0.642824  0.924115  0.492870  0.998770
fake banana   0.741926  0.851796  0.876118  0.828882  0.999470
real onion    0.650727  0.788364  0.676545  0.944604  0.999542
fake onion    0.943729  0.971000  0.985312  0.957195  0.999964
real unknown  0.638944  0.779653  0.674564  0.923664  0.999917
fake unknown  0.230861  0.375082  0.255978  0.701738  0.998030
total         0.765249  0.852500  0.883627  0.854762  0.999260
total(-bg)    0.754793  0.845905  0.878506  0.848206  0.999430
2026-09-24 10:19:23,315 - INFO: Epoch accounting: {'epoch': 279, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11269854, 57678, 80896, 144486, 159060, 81657, 85090, 114440, 137846, 93312, 73215, 29483, 29754, 195596, 123097, 163570, 34561, 68199, 69294, 88699, 88668, 12495, 37322], 'crops_with_class': [202, 34, 32, 35, 35, 26, 24, 27, 33, 38, 29, 8, 12, 47, 34, 26, 26, 23, 29, 42, 37, 11, 19], 'targeted_crops_by_class': [0, 6, 8, 5, 7, 5, 7, 3, 3, 5, 2, 3, 2, 3, 4, 3, 5, 6, 1, 7, 5, 6, 2], 'sampled_scene_counts': [0, 0, 2, 1, 0, 1, 0, 1, 2, 1, 0, 0, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 2, 0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 1, 1, 0, 1, 0, 2, 1, 2, 4, 0, 0, 1, 3, 0, 0, 1, 2, 3, 0, 1, 5, 1, 1, 0, 0, 0, 1, 1, 4, 1, 1, 1, 2, 1, 3, 0, 1, 1, 0, 1, 0, 0, 1, 1, 4, 4, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 1, 0, 4, 0, 2, 0, 1, 3, 1, 3, 3, 1, 1, 2, 2, 1, 0, 2, 3, 2, 1, 2, 1, 1, 2, 2, 1, 0, 4, 2], 'learning_rate': 4.139572493360806e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000699793005887751, 'train_segmentation_loss': 0.32007639541631877, 'val_foreground_miou_all22': 0.7547925077168679, 'val_psnr_ref1': 38.63504180908203, 'elapsed_seconds': 319.2454571723938, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 280/500 | Batch 10/202 | Rec 0.000763 | Seg 0.311297 | Elapsed 0.2m | ETA 3.7m
Epoch 280/500 | Batch 20/202 | Rec 0.000784 | Seg 0.292755 | Elapsed 0.4m | ETA 3.6m
Epoch 280/500 | Batch 30/202 | Rec 0.000746 | Seg 0.329305 | Elapsed 0.6m | ETA 3.4m
Epoch 280/500 | Batch 40/202 | Rec 0.000703 | Seg 0.316695 | Elapsed 0.8m | ETA 3.2m
Epoch 280/500 | Batch 50/202 | Rec 0.000680 | Seg 0.308246 | Elapsed 1.0m | ETA 3.0m
Epoch 280/500 | Batch 60/202 | Rec 0.000683 | Seg 0.305277 | Elapsed 1.2m | ETA 2.8m
Epoch 280/500 | Batch 70/202 | Rec 0.000695 | Seg 0.317750 | Elapsed 1.4m | ETA 2.6m
Epoch 280/500 | Batch 80/202 | Rec 0.000740 | Seg 0.332880 | Elapsed 1.6m | ETA 2.4m
Epoch 280/500 | Batch 90/202 | Rec 0.000741 | Seg 0.332839 | Elapsed 1.8m | ETA 2.2m
Epoch 280/500 | Batch 100/202 | Rec 0.000738 | Seg 0.335135 | Elapsed 2.0m | ETA 2.0m
Epoch 280/500 | Batch 110/202 | Rec 0.000727 | Seg 0.332154 | Elapsed 2.2m | ETA 1.8m
Epoch 280/500 | Batch 120/202 | Rec 0.000718 | Seg 0.328687 | Elapsed 2.4m | ETA 1.6m
Epoch 280/500 | Batch 130/202 | Rec 0.000713 | Seg 0.324796 | Elapsed 2.6m | ETA 1.4m
Epoch 280/500 | Batch 140/202 | Rec 0.000711 | Seg 0.324726 | Elapsed 2.8m | ETA 1.2m
Epoch 280/500 | Batch 150/202 | Rec 0.000713 | Seg 0.324961 | Elapsed 3.0m | ETA 1.0m
Epoch 280/500 | Batch 160/202 | Rec 0.000705 | Seg 0.322386 | Elapsed 3.2m | ETA 0.8m
Epoch 280/500 | Batch 170/202 | Rec 0.000715 | Seg 0.320830 | Elapsed 3.4m | ETA 0.6m
Epoch 280/500 | Batch 180/202 | Rec 0.000719 | Seg 0.318943 | Elapsed 3.6m | ETA 0.4m
Epoch 280/500 | Batch 190/202 | Rec 0.000720 | Seg 0.317573 | Elapsed 3.8m | ETA 0.2m
Epoch 280/500 | Batch 200/202 | Rec 0.000723 | Seg 0.317067 | Elapsed 4.0m | ETA 0.0m
Epoch 280/500 | Batch 202/202 | Rec 0.000723 | Seg 0.317944 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:23:26,779 - INFO: Rec loss: 0.0007228475497859198
2026-09-24 10:23:26,779 - INFO: Seg loss: 0.31794399720164807
2026-09-24 10:23:26,779 - INFO: λ_rec: 1
2026-09-24 10:23:26,779 - INFO: λ_seg: 0.0001
2026-09-24 10:24:40,489 - INFO: -------------------Epoch: 280------------------------
2026-09-24 10:24:40,493 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.335565  0.972838  0.000153
2026-09-24 10:24:40,499 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995450  0.997670  0.996537  0.998906  0.995654
real potato   0.905450  0.950329  0.983363  0.919536  0.999885
fake potato   0.942665  0.970436  0.973246  0.967742  0.999957
real apple    0.728993  0.843208  0.981046  0.739407  0.999052
fake apple    0.729020  0.843226  0.989977  0.734441  0.998969
real orange   0.651903  0.789227  0.994020  0.654470  0.999539
fake orange   0.835202  0.910152  0.858188  0.968927  0.999453
real grape    0.694892  0.819934  0.922922  0.737704  0.999324
fake grape    0.897552  0.945960  0.940915  0.951161  0.999598
real lemon    0.560760  0.718523  0.712880  0.724357  0.999333
fake lemon    0.830689  0.907466  0.999740  0.830869  0.999642
real avocado  0.922327  0.959544  0.971876  0.947619  0.999926
fake avocado  0.738432  0.849489  0.999482  0.738715  0.999687
real pepper   0.923168  0.959999  0.973132  0.947314  0.999712
fake pepper   0.904733  0.949934  0.957772  0.942321  0.999763
real plant    0.832461  0.908522  0.935009  0.883589  0.998221
fake plant    0.803349  0.890902  0.848180  0.938267  0.999817
real banana   0.737135  0.848629  0.938900  0.774277  0.999380
fake banana   0.660231  0.795299  0.748755  0.848125  0.999197
real onion    0.637113  0.778289  0.657919  0.952711  0.999510
fake onion    0.932584  0.965066  0.987845  0.943410  0.999957
real unknown  0.559293  0.717320  0.581506  0.936069  0.999882
fake unknown  0.284201  0.442569  0.319652  0.719305  0.998474
total         0.769896  0.859204  0.881429  0.860836  0.999301
total(-bg)    0.759643  0.852910  0.876197  0.854561  0.999467
2026-09-24 10:24:41,061 - INFO: Epoch accounting: {'epoch': 280, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11267644, 50958, 81595, 126973, 163729, 89751, 49004, 143631, 154274, 59019, 74296, 30748, 24540, 218144, 132807, 173317, 31645, 91135, 81863, 92828, 58576, 7776, 34019], 'crops_with_class': [202, 27, 38, 37, 39, 23, 18, 27, 33, 31, 26, 11, 10, 49, 32, 23, 26, 30, 35, 41, 27, 7, 18], 'targeted_crops_by_class': [0, 3, 13, 5, 6, 6, 4, 3, 4, 5, 8, 1, 3, 5, 11, 4, 8, 4, 3, 6, 6, 2, 6], 'sampled_scene_counts': [2, 1, 2, 0, 1, 0, 1, 0, 3, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 2, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 0, 0, 2, 0, 2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 2, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 3, 2, 0, 1, 2, 0, 0, 1, 4, 1, 0, 2, 1, 0, 0, 1, 3, 1, 2, 2, 2, 3, 1, 1, 1, 0, 1, 0, 1, 0, 1, 2, 2, 1, 2, 2, 1, 0, 2, 2, 0, 2, 2, 0, 0, 5, 1, 2, 1, 2, 1, 0, 2, 1, 1, 2, 3, 1, 0, 1, 1, 1, 0, 2, 5, 1, 2, 2, 3, 1, 1, 4, 1, 2, 3, 1, 2, 1, 1, 0, 1, 1, 0, 1, 2, 2], 'learning_rate': 4.1087362539096476e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007228475497859198, 'train_segmentation_loss': 0.31794399720164807, 'val_foreground_miou_all22': 0.7596432610235389, 'val_psnr_ref1': 38.335565185546876, 'elapsed_seconds': 317.73719906806946, 'peak_cuda_allocated_gib': 7.511783599853516}

Epoch 281/500 | Batch 10/202 | Rec 0.000625 | Seg 0.248423 | Elapsed 0.2m | ETA 4.1m
Epoch 281/500 | Batch 20/202 | Rec 0.000752 | Seg 0.323118 | Elapsed 0.4m | ETA 3.8m
Epoch 281/500 | Batch 30/202 | Rec 0.000793 | Seg 0.323425 | Elapsed 0.6m | ETA 3.5m
Epoch 281/500 | Batch 40/202 | Rec 0.000776 | Seg 0.331323 | Elapsed 0.8m | ETA 3.3m
Epoch 281/500 | Batch 50/202 | Rec 0.000763 | Seg 0.333117 | Elapsed 1.0m | ETA 3.1m
Epoch 281/500 | Batch 60/202 | Rec 0.000746 | Seg 0.346967 | Elapsed 1.2m | ETA 2.9m
Epoch 281/500 | Batch 70/202 | Rec 0.000723 | Seg 0.340881 | Elapsed 1.4m | ETA 2.7m
Epoch 281/500 | Batch 80/202 | Rec 0.000715 | Seg 0.335245 | Elapsed 1.6m | ETA 2.5m
Epoch 281/500 | Batch 90/202 | Rec 0.000705 | Seg 0.332197 | Elapsed 1.8m | ETA 2.3m
Epoch 281/500 | Batch 100/202 | Rec 0.000690 | Seg 0.322436 | Elapsed 2.0m | ETA 2.1m
Epoch 281/500 | Batch 110/202 | Rec 0.000687 | Seg 0.319472 | Elapsed 2.2m | ETA 1.9m
Epoch 281/500 | Batch 120/202 | Rec 0.000685 | Seg 0.320834 | Elapsed 2.4m | ETA 1.7m
Epoch 281/500 | Batch 130/202 | Rec 0.000686 | Seg 0.321518 | Elapsed 2.6m | ETA 1.5m
Epoch 281/500 | Batch 140/202 | Rec 0.000681 | Seg 0.317683 | Elapsed 2.8m | ETA 1.2m
Epoch 281/500 | Batch 150/202 | Rec 0.000682 | Seg 0.311872 | Elapsed 3.0m | ETA 1.0m
Epoch 281/500 | Batch 160/202 | Rec 0.000684 | Seg 0.311734 | Elapsed 3.2m | ETA 0.8m
Epoch 281/500 | Batch 170/202 | Rec 0.000686 | Seg 0.310249 | Elapsed 3.4m | ETA 0.6m
Epoch 281/500 | Batch 180/202 | Rec 0.000686 | Seg 0.309609 | Elapsed 3.6m | ETA 0.4m
Epoch 281/500 | Batch 190/202 | Rec 0.000678 | Seg 0.306015 | Elapsed 3.8m | ETA 0.2m
Epoch 281/500 | Batch 200/202 | Rec 0.000678 | Seg 0.309388 | Elapsed 4.0m | ETA 0.0m
Epoch 281/500 | Batch 202/202 | Rec 0.000677 | Seg 0.309020 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:28:45,806 - INFO: Rec loss: 0.0006769336189493758
2026-09-24 10:28:45,806 - INFO: Seg loss: 0.30902023875329754
2026-09-24 10:28:45,807 - INFO: λ_rec: 1
2026-09-24 10:28:45,807 - INFO: λ_seg: 0.0001
2026-09-24 10:29:57,130 - INFO: -------------------Epoch: 281------------------------
2026-09-24 10:29:57,134 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.456825  0.972689  0.000148
2026-09-24 10:29:57,141 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995563  0.997727  0.996809  0.998746  0.995762
real potato   0.911768  0.953798  0.956293  0.951415  0.999890
fake potato   0.941165  0.969641  0.961111  0.978425  0.999955
real apple    0.765446  0.867092  0.983561  0.775365  0.999180
fake apple    0.606973  0.755377  0.991982  0.609966  0.998509
real orange   0.939640  0.968831  0.988553  0.949977  0.999920
fake orange   0.944548  0.971433  0.972443  0.970526  0.999837
real grape    0.705894  0.827544  0.861173  0.796536  0.999307
fake grape    0.895816  0.944996  0.933800  0.956565  0.999588
real lemon    0.748578  0.856164  0.811824  0.905739  0.999642
fake lemon    0.818391  0.900077  0.999032  0.819041  0.999615
real avocado  0.852220  0.920165  0.885047  0.958292  0.999846
fake avocado  0.790158  0.882731  0.999677  0.790360  0.999749
real pepper   0.837672  0.911617  0.883029  0.942224  0.999332
fake pepper   0.769154  0.869467  0.965167  0.791115  0.999434
real plant    0.853366  0.920832  0.942218  0.900491  0.998452
fake plant    0.869686  0.930252  0.960400  0.902032  0.999892
real banana   0.735150  0.847312  0.937274  0.773190  0.999374
fake banana   0.751984  0.858387  0.876621  0.840992  0.999490
real onion    0.657512  0.793324  0.678923  0.954231  0.999551
fake onion    0.925323  0.961163  0.989000  0.934946  0.999952
real unknown  0.522280  0.686135  0.533333  0.961832  0.999859
fake unknown  0.246344  0.395269  0.267163  0.759689  0.998042
total         0.786288  0.869101  0.885845  0.879204  0.999312
total(-bg)    0.776776  0.863255  0.880801  0.873770  0.999474
2026-09-24 10:29:57,665 - INFO: Epoch accounting: {'epoch': 281, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11317426, 68470, 77629, 125325, 115278, 79110, 57710, 121522, 183337, 74533, 63703, 31767, 46645, 217191, 126521, 77441, 25178, 112647, 84954, 111223, 71913, 5366, 43383], 'crops_with_class': [202, 45, 37, 32, 30, 23, 17, 24, 33, 31, 24, 13, 16, 59, 42, 19, 21, 31, 33, 49, 35, 6, 16], 'targeted_crops_by_class': [0, 10, 5, 4, 4, 1, 3, 5, 8, 7, 2, 3, 6, 6, 5, 4, 2, 9, 8, 7, 5, 2, 3], 'sampled_scene_counts': [2, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 3, 0, 1, 0, 1, 0, 0, 3, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 1, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 3, 2, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 2, 2, 1, 0, 1, 2, 2, 0, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 3, 3, 0, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 3, 4, 3, 8, 3, 2, 2, 0, 3, 3, 2, 1, 3, 1, 1, 1, 0, 4, 2, 2, 1, 1, 2, 3, 3, 2, 0, 1, 1, 2, 3, 0, 0, 0, 3, 0, 1, 1, 3, 0], 'learning_rate': 4.077935693503693e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006769336189493758, 'train_segmentation_loss': 0.30902023875329754, 'val_foreground_miou_all22': 0.776775854252218, 'val_psnr_ref1': 38.456824951171875, 'elapsed_seconds': 316.59110593795776, 'peak_cuda_allocated_gib': 7.509342193603516}

Epoch 282/500 | Batch 10/202 | Rec 0.000475 | Seg 0.262456 | Elapsed 0.2m | ETA 4.1m
Epoch 282/500 | Batch 20/202 | Rec 0.000519 | Seg 0.291704 | Elapsed 0.4m | ETA 3.7m
Epoch 282/500 | Batch 30/202 | Rec 0.000627 | Seg 0.335107 | Elapsed 0.6m | ETA 3.5m
Epoch 282/500 | Batch 40/202 | Rec 0.000643 | Seg 0.326399 | Elapsed 0.8m | ETA 3.3m
Epoch 282/500 | Batch 50/202 | Rec 0.000697 | Seg 0.328471 | Elapsed 1.0m | ETA 3.1m
Epoch 282/500 | Batch 60/202 | Rec 0.000678 | Seg 0.307767 | Elapsed 1.2m | ETA 2.9m
Epoch 282/500 | Batch 70/202 | Rec 0.000679 | Seg 0.304498 | Elapsed 1.4m | ETA 2.7m
Epoch 282/500 | Batch 80/202 | Rec 0.000681 | Seg 0.306030 | Elapsed 1.6m | ETA 2.5m
Epoch 282/500 | Batch 90/202 | Rec 0.000687 | Seg 0.305225 | Elapsed 1.8m | ETA 2.3m
Epoch 282/500 | Batch 100/202 | Rec 0.000693 | Seg 0.303337 | Elapsed 2.0m | ETA 2.1m
Epoch 282/500 | Batch 110/202 | Rec 0.000686 | Seg 0.301389 | Elapsed 2.2m | ETA 1.9m
Epoch 282/500 | Batch 120/202 | Rec 0.000674 | Seg 0.300794 | Elapsed 2.4m | ETA 1.7m
Epoch 282/500 | Batch 130/202 | Rec 0.000671 | Seg 0.303435 | Elapsed 2.6m | ETA 1.5m
Epoch 282/500 | Batch 140/202 | Rec 0.000682 | Seg 0.307389 | Elapsed 2.8m | ETA 1.3m
Epoch 282/500 | Batch 150/202 | Rec 0.000681 | Seg 0.303000 | Elapsed 3.0m | ETA 1.0m
Epoch 282/500 | Batch 160/202 | Rec 0.000692 | Seg 0.308075 | Elapsed 3.2m | ETA 0.8m
Epoch 282/500 | Batch 170/202 | Rec 0.000697 | Seg 0.308034 | Elapsed 3.4m | ETA 0.6m
Epoch 282/500 | Batch 180/202 | Rec 0.000699 | Seg 0.305886 | Elapsed 3.6m | ETA 0.4m
Epoch 282/500 | Batch 190/202 | Rec 0.000706 | Seg 0.304141 | Elapsed 3.8m | ETA 0.2m
Epoch 282/500 | Batch 200/202 | Rec 0.000702 | Seg 0.306383 | Elapsed 4.0m | ETA 0.0m
Epoch 282/500 | Batch 202/202 | Rec 0.000708 | Seg 0.304969 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:34:02,364 - INFO: Rec loss: 0.0007079462669178899
2026-09-24 10:34:02,364 - INFO: Seg loss: 0.30496853440631144
2026-09-24 10:34:02,364 - INFO: λ_rec: 1
2026-09-24 10:34:02,364 - INFO: λ_seg: 0.0001
2026-09-24 10:35:15,374 - INFO: -------------------Epoch: 282------------------------
2026-09-24 10:35:15,378 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.232648  0.973084  0.000156
2026-09-24 10:35:15,385 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995572  0.997731  0.996659  0.998906  0.995771
real potato   0.922822  0.959812  0.960659  0.959067  0.999904
fake potato   0.959188  0.979119  0.978657  0.979682  0.999970
real apple    0.760198  0.863715  0.968148  0.779699  0.999151
fake apple    0.603973  0.753049  0.988442  0.608269  0.998494
real orange   0.544129  0.704725  0.970546  0.553265  0.999389
fake orange   0.794536  0.885456  0.816484  0.967274  0.999284
real grape    0.775473  0.873490  0.904840  0.844332  0.999490
fake grape    0.885185  0.939046  0.956574  0.922246  0.999557
real lemon    0.669384  0.801903  0.756651  0.853025  0.999505
fake lemon    0.843894  0.915289  0.998041  0.845294  0.999669
real avocado  0.908012  0.951738  0.948915  0.954680  0.999910
fake avocado  0.334311  0.501061  0.999619  0.334353  0.999203
real pepper   0.901540  0.948171  0.943870  0.952611  0.999619
fake pepper   0.881116  0.936752  0.975005  0.901479  0.999710
real plant    0.855033  0.921802  0.959995  0.886624  0.998496
fake plant    0.787296  0.880941  0.882772  0.879218  0.999811
real banana   0.718838  0.836374  0.925676  0.762868  0.999330
fake banana   0.735510  0.847551  0.848906  0.846301  0.999440
real onion    0.629451  0.772544  0.643090  0.967404  0.999485
fake onion    0.945598  0.971988  0.986066  0.958404  0.999965
real unknown  0.693380  0.818881  0.719971  0.949427  0.999933
fake unknown  0.208881  0.345542  0.222628  0.771822  0.997537
total         0.754492  0.843769  0.884879  0.846794  0.999245
total(-bg)    0.743534  0.836770  0.879798  0.839879  0.999402
2026-09-24 10:35:15,924 - INFO: Epoch accounting: {'epoch': 282, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11347594, 68625, 62190, 119131, 112713, 105609, 74092, 127248, 167385, 72287, 58936, 33810, 21510, 193451, 146357, 193770, 26179, 65674, 58114, 88780, 55421, 8571, 30825], 'crops_with_class': [202, 32, 25, 29, 32, 29, 27, 28, 29, 39, 24, 11, 10, 49, 37, 25, 24, 23, 25, 37, 27, 11, 16], 'targeted_crops_by_class': [0, 4, 6, 4, 5, 5, 3, 5, 8, 4, 5, 4, 4, 3, 8, 6, 7, 5, 4, 3, 7, 5, 1], 'sampled_scene_counts': [1, 2, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 2, 1, 2, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 3, 1, 1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 3, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 0, 1, 1, 1, 2, 0, 2, 1, 3, 1, 2, 1, 1, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 3, 1, 0, 1, 2, 1, 3, 0, 1, 4, 2, 1, 0, 1, 4, 1, 1, 3, 1, 3, 2, 0, 0, 2, 1, 2, 3, 3, 0, 1, 3, 2, 3, 1, 2, 3, 2, 0, 1, 1, 1, 3, 1, 0, 1, 0, 1, 1, 0, 1, 3, 1, 1, 1, 3, 0], 'learning_rate': 4.0471720280963304e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007079462669178899, 'train_segmentation_loss': 0.30496853440631144, 'val_foreground_miou_all22': 0.743533939447868, 'val_psnr_ref1': 38.23264785766602, 'elapsed_seconds': 318.2512903213501, 'peak_cuda_allocated_gib': 7.512760162353516}

Epoch 283/500 | Batch 10/202 | Rec 0.001068 | Seg 0.464224 | Elapsed 0.2m | ETA 3.8m
Epoch 283/500 | Batch 20/202 | Rec 0.000864 | Seg 0.412602 | Elapsed 0.4m | ETA 3.6m
Epoch 283/500 | Batch 30/202 | Rec 0.000794 | Seg 0.366119 | Elapsed 0.6m | ETA 3.5m
Epoch 283/500 | Batch 40/202 | Rec 0.000811 | Seg 0.358043 | Elapsed 0.8m | ETA 3.3m
Epoch 283/500 | Batch 50/202 | Rec 0.000761 | Seg 0.347378 | Elapsed 1.0m | ETA 3.0m
Epoch 283/500 | Batch 60/202 | Rec 0.000760 | Seg 0.348911 | Elapsed 1.2m | ETA 2.8m
Epoch 283/500 | Batch 70/202 | Rec 0.000735 | Seg 0.344048 | Elapsed 1.4m | ETA 2.6m
Epoch 283/500 | Batch 80/202 | Rec 0.000742 | Seg 0.344031 | Elapsed 1.6m | ETA 2.4m
Epoch 283/500 | Batch 90/202 | Rec 0.000729 | Seg 0.338380 | Elapsed 1.8m | ETA 2.2m
Epoch 283/500 | Batch 100/202 | Rec 0.000724 | Seg 0.331471 | Elapsed 2.0m | ETA 2.0m
Epoch 283/500 | Batch 110/202 | Rec 0.000735 | Seg 0.332140 | Elapsed 2.2m | ETA 1.8m
Epoch 283/500 | Batch 120/202 | Rec 0.000729 | Seg 0.333137 | Elapsed 2.4m | ETA 1.6m
Epoch 283/500 | Batch 130/202 | Rec 0.000737 | Seg 0.331867 | Elapsed 2.6m | ETA 1.4m
Epoch 283/500 | Batch 140/202 | Rec 0.000720 | Seg 0.327816 | Elapsed 2.8m | ETA 1.2m
Epoch 283/500 | Batch 150/202 | Rec 0.000724 | Seg 0.328406 | Elapsed 3.0m | ETA 1.0m
Epoch 283/500 | Batch 160/202 | Rec 0.000725 | Seg 0.332347 | Elapsed 3.2m | ETA 0.8m
Epoch 283/500 | Batch 170/202 | Rec 0.000720 | Seg 0.330809 | Elapsed 3.4m | ETA 0.6m
Epoch 283/500 | Batch 180/202 | Rec 0.000717 | Seg 0.329133 | Elapsed 3.6m | ETA 0.4m
Epoch 283/500 | Batch 190/202 | Rec 0.000718 | Seg 0.331215 | Elapsed 3.8m | ETA 0.2m
Epoch 283/500 | Batch 200/202 | Rec 0.000716 | Seg 0.332707 | Elapsed 4.0m | ETA 0.0m
Epoch 283/500 | Batch 202/202 | Rec 0.000716 | Seg 0.331604 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:39:19,272 - INFO: Rec loss: 0.0007163295053357102
2026-09-24 10:39:19,272 - INFO: Seg loss: 0.33160402706944114
2026-09-24 10:39:19,273 - INFO: λ_rec: 1
2026-09-24 10:39:19,273 - INFO: λ_seg: 0.0001
2026-09-24 10:40:31,290 - INFO: -------------------Epoch: 283------------------------
2026-09-24 10:40:31,294 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.700968  0.973793  0.000141
2026-09-24 10:40:31,301 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995637  0.997764  0.996867  0.998762  0.995833
real potato   0.328998  0.495069  1.000000  0.328998  0.999197
fake potato   0.648497  0.786726  0.983962  0.655425  0.999741
real apple    0.706901  0.828236  0.778534  0.884830  0.998734
fake apple    0.705394  0.827201  0.970406  0.720902  0.998863
real orange   0.908955  0.952257  0.989391  0.917902  0.999879
fake orange   0.937647  0.967770  0.958016  0.977828  0.999814
real grape    0.736641  0.848302  0.960540  0.759629  0.999433
fake grape    0.887385  0.940283  0.926461  0.954626  0.999552
real lemon    0.446146  0.616970  0.459717  0.937938  0.998632
fake lemon    0.829161  0.906553  0.996800  0.831374  0.999638
real avocado  0.790303  0.882821  0.814661  0.963547  0.999762
fake avocado  0.741874  0.851762  0.999485  0.742158  0.999691
real pepper   0.805085  0.891969  0.860482  0.925955  0.999180
fake pepper   0.738176  0.849319  0.996038  0.740350  0.999374
real plant    0.853573  0.920953  0.935196  0.907234  0.998443
fake plant    0.846300  0.916703  0.988037  0.855061  0.999876
real banana   0.276122  0.432717  0.967696  0.278691  0.998358
fake banana   0.734158  0.846653  0.851641  0.841821  0.999439
real onion    0.648992  0.787089  0.718489  0.870292  0.999575
fake onion    0.940431  0.969251  0.988682  0.950665  0.999962
real unknown  0.949427  0.974008  1.000000  0.949427  0.999992
fake unknown  0.278682  0.435851  0.294226  0.840637  0.998167
total         0.727586  0.822879  0.888492  0.818872  0.999180
total(-bg)    0.715402  0.814930  0.883566  0.810695  0.999332
2026-09-24 10:40:31,846 - INFO: Epoch accounting: {'epoch': 283, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11156897, 41558, 82759, 126973, 128643, 94236, 57040, 182229, 212520, 64916, 81460, 45150, 47391, 226651, 141044, 177595, 31249, 47444, 87258, 77964, 70573, 9023, 47699], 'crops_with_class': [202, 32, 36, 32, 37, 28, 20, 29, 38, 34, 29, 14, 17, 53, 38, 25, 22, 14, 33, 33, 31, 11, 18], 'targeted_crops_by_class': [0, 5, 7, 4, 5, 6, 5, 5, 5, 2, 8, 5, 8, 6, 4, 3, 9, 4, 3, 10, 4, 4, 6], 'sampled_scene_counts': [2, 1, 1, 2, 2, 2, 0, 0, 0, 0, 1, 0, 2, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 2, 2, 2, 0, 1, 1, 1, 1, 0, 2, 0, 0, 2, 1, 3, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 2, 0, 0, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 0, 1, 2, 2, 1, 2, 3, 1, 3, 0, 1, 0, 2, 2, 2, 1, 2, 1, 4, 2, 2, 1, 0, 1, 1, 1, 0, 1, 2, 1, 2, 1, 0, 1, 1, 0, 2, 1, 1, 0, 0, 1, 2, 4, 4, 0, 3, 1, 3, 1, 2, 1, 2, 0, 0, 0, 2, 0, 0, 0, 2, 1, 2, 3, 1, 2, 1, 0, 0, 1, 3, 4, 3, 2, 1, 1, 0, 0, 0, 0, 5, 2, 0, 2, 2, 3], 'learning_rate': 4.01644647218439e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007163295053357102, 'train_segmentation_loss': 0.33160402706944114, 'val_foreground_miou_all22': 0.7154021702683244, 'val_psnr_ref1': 38.700968170166014, 'elapsed_seconds': 315.91443037986755, 'peak_cuda_allocated_gib': 7.514682769775391}

Epoch 284/500 | Batch 10/202 | Rec 0.000760 | Seg 0.369134 | Elapsed 0.2m | ETA 3.7m
Epoch 284/500 | Batch 20/202 | Rec 0.000763 | Seg 0.343572 | Elapsed 0.4m | ETA 3.6m
Epoch 284/500 | Batch 30/202 | Rec 0.000757 | Seg 0.349520 | Elapsed 0.6m | ETA 3.4m
Epoch 284/500 | Batch 40/202 | Rec 0.000730 | Seg 0.343215 | Elapsed 0.8m | ETA 3.3m
Epoch 284/500 | Batch 50/202 | Rec 0.000703 | Seg 0.328373 | Elapsed 1.0m | ETA 3.1m
Epoch 284/500 | Batch 60/202 | Rec 0.000707 | Seg 0.337235 | Elapsed 1.2m | ETA 2.9m
Epoch 284/500 | Batch 70/202 | Rec 0.000707 | Seg 0.337333 | Elapsed 1.4m | ETA 2.7m
Epoch 284/500 | Batch 80/202 | Rec 0.000712 | Seg 0.332892 | Elapsed 1.6m | ETA 2.5m
Epoch 284/500 | Batch 90/202 | Rec 0.000707 | Seg 0.335884 | Elapsed 1.8m | ETA 2.3m
Epoch 284/500 | Batch 100/202 | Rec 0.000707 | Seg 0.333153 | Elapsed 2.0m | ETA 2.1m
Epoch 284/500 | Batch 110/202 | Rec 0.000715 | Seg 0.338540 | Elapsed 2.3m | ETA 1.9m
Epoch 284/500 | Batch 120/202 | Rec 0.000704 | Seg 0.331986 | Elapsed 2.5m | ETA 1.7m
Epoch 284/500 | Batch 130/202 | Rec 0.000708 | Seg 0.327609 | Elapsed 2.7m | ETA 1.5m
Epoch 284/500 | Batch 140/202 | Rec 0.000716 | Seg 0.334058 | Elapsed 2.9m | ETA 1.3m
Epoch 284/500 | Batch 150/202 | Rec 0.000716 | Seg 0.338471 | Elapsed 3.1m | ETA 1.1m
Epoch 284/500 | Batch 160/202 | Rec 0.000721 | Seg 0.338196 | Elapsed 3.3m | ETA 0.9m
Epoch 284/500 | Batch 170/202 | Rec 0.000724 | Seg 0.338266 | Elapsed 3.5m | ETA 0.7m
Epoch 284/500 | Batch 180/202 | Rec 0.000724 | Seg 0.340293 | Elapsed 3.7m | ETA 0.5m
Epoch 284/500 | Batch 190/202 | Rec 0.000721 | Seg 0.341902 | Elapsed 3.9m | ETA 0.2m
Epoch 284/500 | Batch 200/202 | Rec 0.000724 | Seg 0.343618 | Elapsed 4.1m | ETA 0.0m
Epoch 284/500 | Batch 202/202 | Rec 0.000725 | Seg 0.342296 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:44:39,050 - INFO: Rec loss: 0.0007252384094310472
2026-09-24 10:44:39,050 - INFO: Seg loss: 0.34229613420101673
2026-09-24 10:44:39,050 - INFO: λ_rec: 1
2026-09-24 10:44:39,051 - INFO: λ_seg: 0.0001
2026-09-24 10:45:52,007 - INFO: -------------------Epoch: 284------------------------
2026-09-24 10:45:52,011 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.639431  0.973208  0.000143
2026-09-24 10:45:52,018 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995552  0.997721  0.996846  0.998698  0.995753
real potato   0.893794  0.943869  0.973057  0.916475  0.999870
fake potato   0.850333  0.919064  0.959653  0.881860  0.999887
real apple    0.759068  0.862985  0.972709  0.775586  0.999151
fake apple    0.604381  0.753366  0.979437  0.612148  0.998487
real orange   0.823252  0.903009  0.994018  0.827351  0.999766
fake orange   0.890403  0.941974  0.926722  0.957840  0.999662
real grape    0.718506  0.836149  0.974332  0.732369  0.999401
fake grape    0.881203  0.936800  0.929584  0.944231  0.999529
real lemon    0.517274  0.681797  0.605914  0.779538  0.999145
fake lemon    0.839265  0.912560  0.998714  0.840173  0.999660
real avocado  0.896264  0.945245  0.937359  0.953366  0.999897
fake avocado  0.443227  0.614174  0.998564  0.443509  0.999333
real pepper   0.895938  0.945063  0.940661  0.949608  0.999597
fake pepper   0.901052  0.947901  0.976451  0.921068  0.999759
real plant    0.850913  0.919402  0.936440  0.903069  0.998417
fake plant    0.882118  0.937317  0.942270  0.932515  0.999901
real banana   0.605180  0.753985  0.902670  0.647426  0.999051
fake banana   0.677458  0.807670  0.770441  0.848789  0.999257
real onion    0.630919  0.773649  0.651711  0.951866  0.999497
fake onion    0.928215  0.962721  0.981896  0.944377  0.999954
real unknown  0.889792  0.941633  0.943486  0.939885  0.999981
fake unknown  0.208952  0.345640  0.220230  0.803151  0.997438
total         0.764481  0.851465  0.891877  0.848039  0.999234
total(-bg)    0.753978  0.844817  0.887106  0.841191  0.999393
2026-09-24 10:45:52,551 - INFO: Epoch accounting: {'epoch': 284, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11100004, 40735, 44907, 182301, 130765, 98446, 65077, 179613, 247413, 82473, 68770, 46124, 33041, 198553, 135137, 230288, 19838, 60521, 61912, 77650, 48867, 14404, 71433], 'crops_with_class': [202, 26, 22, 44, 38, 30, 22, 30, 39, 33, 28, 16, 12, 53, 32, 27, 18, 20, 27, 33, 21, 16, 26], 'targeted_crops_by_class': [0, 2, 1, 8, 3, 4, 2, 4, 2, 5, 8, 4, 1, 4, 4, 6, 2, 4, 5, 4, 6, 3, 11], 'sampled_scene_counts': [2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 2, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 2, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 2, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 3, 0, 4, 2, 3, 2, 3, 0, 0, 2, 2, 1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 4, 6, 1, 3, 1, 1, 2, 0, 0, 2, 1, 1, 0, 3, 0, 0, 0, 2, 2, 0, 2, 1, 0, 2, 1, 3, 2, 0, 2, 1, 0, 3, 1, 0, 1, 1, 2, 1, 0, 0, 1, 2, 0], 'learning_rate': 3.985760238760211e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0007252384094310472, 'train_segmentation_loss': 0.34229613420101673, 'val_foreground_miou_all22': 0.7539775703147018, 'val_psnr_ref1': 38.63943115234375, 'elapsed_seconds': 320.6979353427887, 'peak_cuda_allocated_gib': 7.515171051025391}

Epoch 285/500 | Batch 10/202 | Rec 0.000646 | Seg 0.271940 | Elapsed 0.2m | ETA 3.9m
Epoch 285/500 | Batch 20/202 | Rec 0.000719 | Seg 0.277877 | Elapsed 0.4m | ETA 3.7m
Epoch 285/500 | Batch 30/202 | Rec 0.000704 | Seg 0.285583 | Elapsed 0.6m | ETA 3.5m
Epoch 285/500 | Batch 40/202 | Rec 0.000704 | Seg 0.291709 | Elapsed 0.8m | ETA 3.3m
Epoch 285/500 | Batch 50/202 | Rec 0.000696 | Seg 0.300253 | Elapsed 1.0m | ETA 3.1m
Epoch 285/500 | Batch 60/202 | Rec 0.000690 | Seg 0.296922 | Elapsed 1.2m | ETA 2.9m
Epoch 285/500 | Batch 70/202 | Rec 0.000703 | Seg 0.299934 | Elapsed 1.4m | ETA 2.7m
Epoch 285/500 | Batch 80/202 | Rec 0.000706 | Seg 0.300053 | Elapsed 1.6m | ETA 2.5m
Epoch 285/500 | Batch 90/202 | Rec 0.000703 | Seg 0.304835 | Elapsed 1.8m | ETA 2.3m
Epoch 285/500 | Batch 100/202 | Rec 0.000697 | Seg 0.300248 | Elapsed 2.0m | ETA 2.1m
Epoch 285/500 | Batch 110/202 | Rec 0.000722 | Seg 0.304960 | Elapsed 2.2m | ETA 1.9m
Epoch 285/500 | Batch 120/202 | Rec 0.000706 | Seg 0.300935 | Elapsed 2.4m | ETA 1.7m
Epoch 285/500 | Batch 130/202 | Rec 0.000693 | Seg 0.303930 | Elapsed 2.6m | ETA 1.5m
Epoch 285/500 | Batch 140/202 | Rec 0.000684 | Seg 0.300241 | Elapsed 2.8m | ETA 1.3m
Epoch 285/500 | Batch 150/202 | Rec 0.000696 | Seg 0.304421 | Elapsed 3.0m | ETA 1.1m
Epoch 285/500 | Batch 160/202 | Rec 0.000694 | Seg 0.302503 | Elapsed 3.2m | ETA 0.9m
Epoch 285/500 | Batch 170/202 | Rec 0.000695 | Seg 0.306011 | Elapsed 3.4m | ETA 0.6m
Epoch 285/500 | Batch 180/202 | Rec 0.000696 | Seg 0.307962 | Elapsed 3.6m | ETA 0.4m
Epoch 285/500 | Batch 190/202 | Rec 0.000699 | Seg 0.315294 | Elapsed 3.8m | ETA 0.2m
Epoch 285/500 | Batch 200/202 | Rec 0.000696 | Seg 0.313118 | Elapsed 4.0m | ETA 0.0m
Epoch 285/500 | Batch 202/202 | Rec 0.000691 | Seg 0.310563 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:49:57,818 - INFO: Rec loss: 0.0006913771062725141
2026-09-24 10:49:57,818 - INFO: Seg loss: 0.310563082779103
2026-09-24 10:49:57,818 - INFO: λ_rec: 1
2026-09-24 10:49:57,819 - INFO: λ_seg: 0.0001
2026-09-24 10:51:09,936 - INFO: -------------------Epoch: 285------------------------
2026-09-24 10:51:09,940 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.942952  0.974266  0.000133
2026-09-24 10:51:09,947 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995619  0.997755  0.997118  0.998492  0.995817
real potato   0.916122  0.956175  0.965549  0.947080  0.999896
fake potato   0.946436  0.972431  0.982884  0.962296  0.999960
real apple    0.813878  0.897340  0.975243  0.831048  0.999344
fake apple    0.632890  0.775130  0.969078  0.645934  0.998585
real orange   0.785337  0.879714  0.988448  0.792612  0.999715
fake orange   0.876352  0.934052  0.899078  0.971965  0.999607
real grape    0.787241  0.880907  0.895695  0.866696  0.999511
fake grape    0.897196  0.945762  0.932633  0.959370  0.999593
real lemon    0.588293  0.740739  0.612010  0.938198  0.999228
fake lemon    0.832637  0.908627  0.997671  0.834259  0.999645
real avocado  0.876611  0.934199  0.919396  0.949589  0.999876
fake avocado  0.716931  0.835082  0.992451  0.720862  0.999659
real pepper   0.819994  0.901045  0.867976  0.936843  0.999248
fake pepper   0.736597  0.848273  0.978902  0.748480  0.999362
real plant    0.870211  0.930552  0.949589  0.912360  0.998639
fake plant    0.823957  0.903433  0.874014  0.935008  0.999841
real banana   0.561507  0.719138  0.892433  0.602268  0.998943
fake banana   0.719167  0.836596  0.820276  0.853683  0.999387
real onion    0.677115  0.807427  0.711163  0.933964  0.999598
fake onion    0.950828  0.974744  0.991496  0.958646  0.999969
real unknown  0.480058  0.648657  0.494737  0.941794  0.999837
fake unknown  0.247468  0.396712  0.274290  0.716769  0.998163
total         0.763150  0.853239  0.868788  0.867748  0.999279
total(-bg)    0.752583  0.846670  0.862955  0.861806  0.999437
2026-09-24 10:51:10,655 - INFO: Epoch accounting: {'epoch': 285, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11302699, 58578, 52760, 94077, 127663, 73484, 61745, 172740, 214443, 76666, 67375, 46128, 46568, 238141, 138770, 120358, 25851, 82804, 74829, 81346, 47289, 7755, 26203], 'crops_with_class': [202, 40, 24, 26, 30, 24, 22, 37, 38, 30, 24, 15, 18, 52, 37, 16, 23, 28, 28, 35, 24, 10, 14], 'targeted_crops_by_class': [0, 4, 3, 2, 1, 4, 4, 4, 5, 4, 5, 4, 10, 6, 7, 2, 9, 5, 4, 5, 3, 9, 2], 'sampled_scene_counts': [1, 1, 0, 1, 1, 2, 1, 1, 2, 0, 0, 0, 1, 1, 1, 2, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 2, 1, 2, 0, 1, 1, 0, 3, 0, 0, 0, 1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 0, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 2, 2, 0, 3, 2, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 2, 1, 2, 3, 2, 0, 1, 1, 1, 0, 3, 2, 1, 0, 0, 3, 2, 0, 1, 2, 2, 4, 1, 2, 0, 0, 2, 1, 1, 0, 3, 3, 2, 0, 0, 1, 1, 1, 2, 1, 2, 1, 3, 3, 2, 2, 1, 1, 2, 2, 0, 0, 1, 1, 0, 0, 2, 2, 4, 2, 2, 1, 1, 2, 2, 1, 0, 0, 1, 1, 0, 0, 3, 2, 1, 4, 2], 'learning_rate': 3.955114539263748e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0006913771062725141, 'train_segmentation_loss': 0.310563082779103, 'val_foreground_miou_all22': 0.7525829190541754, 'val_psnr_ref1': 38.94295196533203, 'elapsed_seconds': 318.0956823825836, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 286/500 | Batch 10/202 | Rec 0.000653 | Seg 0.362686 | Elapsed 0.2m | ETA 3.9m
Epoch 286/500 | Batch 20/202 | Rec 0.000587 | Seg 0.298206 | Elapsed 0.4m | ETA 3.6m
Epoch 286/500 | Batch 30/202 | Rec 0.000649 | Seg 0.314020 | Elapsed 0.6m | ETA 3.5m
Epoch 286/500 | Batch 40/202 | Rec 0.000628 | Seg 0.325293 | Elapsed 0.8m | ETA 3.3m
Epoch 286/500 | Batch 50/202 | Rec 0.000654 | Seg 0.336740 | Elapsed 1.0m | ETA 3.1m
Epoch 286/500 | Batch 60/202 | Rec 0.000639 | Seg 0.327341 | Elapsed 1.2m | ETA 2.9m
Epoch 286/500 | Batch 70/202 | Rec 0.000636 | Seg 0.322327 | Elapsed 1.4m | ETA 2.7m
Epoch 286/500 | Batch 80/202 | Rec 0.000652 | Seg 0.318110 | Elapsed 1.6m | ETA 2.5m
Epoch 286/500 | Batch 90/202 | Rec 0.000643 | Seg 0.315636 | Elapsed 1.8m | ETA 2.3m
Epoch 286/500 | Batch 100/202 | Rec 0.000649 | Seg 0.318155 | Elapsed 2.0m | ETA 2.1m
Epoch 286/500 | Batch 110/202 | Rec 0.000663 | Seg 0.321788 | Elapsed 2.2m | ETA 1.9m
Epoch 286/500 | Batch 120/202 | Rec 0.000668 | Seg 0.321105 | Elapsed 2.4m | ETA 1.7m
Epoch 286/500 | Batch 130/202 | Rec 0.000662 | Seg 0.315170 | Elapsed 2.7m | ETA 1.5m
Epoch 286/500 | Batch 140/202 | Rec 0.000667 | Seg 0.316358 | Elapsed 2.9m | ETA 1.3m
Epoch 286/500 | Batch 150/202 | Rec 0.000675 | Seg 0.321508 | Elapsed 3.0m | ETA 1.1m
Epoch 286/500 | Batch 160/202 | Rec 0.000667 | Seg 0.317379 | Elapsed 3.3m | ETA 0.9m
Epoch 286/500 | Batch 170/202 | Rec 0.000668 | Seg 0.318400 | Elapsed 3.5m | ETA 0.7m
Epoch 286/500 | Batch 180/202 | Rec 0.000662 | Seg 0.315969 | Elapsed 3.7m | ETA 0.4m
Epoch 286/500 | Batch 190/202 | Rec 0.000669 | Seg 0.318383 | Elapsed 3.9m | ETA 0.2m
Epoch 286/500 | Batch 200/202 | Rec 0.000669 | Seg 0.318437 | Elapsed 4.1m | ETA 0.0m
Epoch 286/500 | Batch 202/202 | Rec 0.000668 | Seg 0.318175 | Elapsed 4.1m | ETA 0.0m

2026-09-24 10:55:16,877 - INFO: Rec loss: 0.000668400831435263
2026-09-24 10:55:16,877 - INFO: Seg loss: 0.3181750761474123
2026-09-24 10:55:16,877 - INFO: λ_rec: 1
2026-09-24 10:55:16,877 - INFO: λ_seg: 0.0001
2026-09-24 10:56:31,962 - INFO: -------------------Epoch: 286------------------------
2026-09-24 10:56:31,965 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.225865  0.972898  0.000156
2026-09-24 10:56:31,972 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995007  0.997447  0.995825  0.999176  0.995227
real potato   0.564397  0.721506  1.000000  0.564397  0.999479
fake potato   0.687817  0.814988  0.955236  0.710725  0.999765
real apple    0.685258  0.813188  0.851639  0.778151  0.998767
fake apple    0.749420  0.856715  0.987241  0.756749  0.999045
real orange   0.525684  0.689067  0.994106  0.527327  0.999373
fake orange   0.797255  0.887142  0.809415  0.981505  0.999285
real grape    0.610291  0.757940  0.941138  0.634510  0.999154
fake grape    0.872795  0.932027  0.931597  0.932558  0.999497
real lemon    0.360514  0.529920  0.426704  0.699169  0.998542
fake lemon    0.854340  0.921400  0.995729  0.857483  0.999691
real avocado  0.820904  0.901595  0.861826  0.945320  0.999808
fake avocado  0.389569  0.560664  1.000000  0.389569  0.999270
real pepper   0.866982  0.928702  0.924415  0.933130  0.999476
fake pepper   0.829990  0.907048  0.975610  0.847577  0.999586
real plant    0.802243  0.890222  0.932990  0.851294  0.997901
fake plant    0.772537  0.871624  0.939119  0.813267  0.999809
real banana   0.354233  0.523110  0.946975  0.361402  0.998520
fake banana   0.630327  0.773202  0.748293  0.799934  0.999137
real onion    0.697375  0.821661  0.733962  0.933288  0.999634
fake onion    0.906198  0.950741  0.988515  0.915840  0.999940
real unknown  0.873723  0.932557  0.970103  0.897901  0.999979
fake unknown  0.217511  0.357268  0.233737  0.758059  0.997702
total         0.689755  0.797380  0.875834  0.777753  0.999069
total(-bg)    0.675880  0.788286  0.870380  0.767689  0.999244
2026-09-24 10:56:32,508 - INFO: Epoch accounting: {'epoch': 286, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11304145, 40754, 47538, 115378, 125776, 61405, 85216, 189570, 182086, 69460, 72020, 41799, 46273, 199309, 132662, 131635, 24896, 76444, 86183, 83552, 63437, 13522, 45212], 'crops_with_class': [202, 26, 21, 34, 27, 18, 31, 36, 36, 31, 30, 15, 16, 49, 36, 19, 25, 25, 32, 39, 29, 13, 25], 'targeted_crops_by_class': [0, 4, 4, 8, 2, 5, 2, 10, 2, 3, 5, 2, 6, 4, 6, 4, 5, 4, 5, 2, 5, 2, 5], 'sampled_scene_counts': [0, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 0, 1, 0, 1, 3, 1, 1, 1, 0, 2, 3, 2, 0, 1, 0, 3, 1, 2, 0, 2, 1, 2, 2, 1, 1, 0, 2, 1, 1, 0, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 4, 2, 5, 2, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 3, 2, 2, 1, 0, 0, 2, 2, 0, 2, 0, 2, 2, 3, 0, 0, 2, 2, 2, 0, 1, 1, 2, 4, 2, 0, 3, 1], 'learning_rate': 3.92451058353474e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000668400831435263, 'train_segmentation_loss': 0.3181750761474123, 'val_foreground_miou_all22': 0.6758800856466644, 'val_psnr_ref1': 38.22586517333984, 'elapsed_seconds': 321.84474182128906, 'peak_cuda_allocated_gib': 7.510318756103516}

Epoch 287/500 | Batch 10/202 | Rec 0.000669 | Seg 0.311642 | Elapsed 0.2m | ETA 3.9m
Epoch 287/500 | Batch 20/202 | Rec 0.000604 | Seg 0.286062 | Elapsed 0.4m | ETA 3.7m
Epoch 287/500 | Batch 30/202 | Rec 0.000648 | Seg 0.274140 | Elapsed 0.6m | ETA 3.5m
Epoch 287/500 | Batch 40/202 | Rec 0.000649 | Seg 0.290592 | Elapsed 0.8m | ETA 3.3m
Epoch 287/500 | Batch 50/202 | Rec 0.000631 | Seg 0.292363 | Elapsed 1.0m | ETA 3.1m
Epoch 287/500 | Batch 60/202 | Rec 0.000631 | Seg 0.292603 | Elapsed 1.2m | ETA 2.9m
Epoch 287/500 | Batch 70/202 | Rec 0.000629 | Seg 0.289106 | Elapsed 1.4m | ETA 2.7m
Epoch 287/500 | Batch 80/202 | Rec 0.000621 | Seg 0.291497 | Elapsed 1.6m | ETA 2.5m
Epoch 287/500 | Batch 90/202 | Rec 0.000628 | Seg 0.293876 | Elapsed 1.8m | ETA 2.3m
Epoch 287/500 | Batch 100/202 | Rec 0.000629 | Seg 0.295396 | Elapsed 2.0m | ETA 2.1m
Epoch 287/500 | Batch 110/202 | Rec 0.000638 | Seg 0.301762 | Elapsed 2.2m | ETA 1.9m
Epoch 287/500 | Batch 120/202 | Rec 0.000632 | Seg 0.298388 | Elapsed 2.4m | ETA 1.7m
Epoch 287/500 | Batch 130/202 | Rec 0.000635 | Seg 0.296164 | Elapsed 2.6m | ETA 1.5m
Epoch 287/500 | Batch 140/202 | Rec 0.000637 | Seg 0.295708 | Elapsed 2.8m | ETA 1.3m
Epoch 287/500 | Batch 150/202 | Rec 0.000640 | Seg 0.296481 | Elapsed 3.0m | ETA 1.1m
Epoch 287/500 | Batch 160/202 | Rec 0.000647 | Seg 0.301532 | Elapsed 3.2m | ETA 0.9m
Epoch 287/500 | Batch 170/202 | Rec 0.000644 | Seg 0.302335 | Elapsed 3.4m | ETA 0.6m
Epoch 287/500 | Batch 180/202 | Rec 0.000645 | Seg 0.305380 | Elapsed 3.7m | ETA 0.4m
Epoch 287/500 | Batch 190/202 | Rec 0.000650 | Seg 0.305710 | Elapsed 3.9m | ETA 0.2m
Epoch 287/500 | Batch 200/202 | Rec 0.000646 | Seg 0.304861 | Elapsed 4.1m | ETA 0.0m
Epoch 287/500 | Batch 202/202 | Rec 0.000645 | Seg 0.305093 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:00:38,336 - INFO: Rec loss: 0.0006452578693077356
2026-09-24 11:00:38,336 - INFO: Seg loss: 0.30509337082062615
2026-09-24 11:00:38,336 - INFO: λ_rec: 1
2026-09-24 11:00:38,336 - INFO: λ_seg: 0.0001
2026-09-24 11:01:50,927 - INFO: -------------------Epoch: 287------------------------
2026-09-24 11:01:50,931 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.369894  0.973151  0.000152
2026-09-24 11:01:50,938 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995485  0.997687  0.996818  0.998659  0.995688
real potato   0.278500  0.435633  1.000000  0.278500  0.999137
fake potato   0.643404  0.782966  0.982606  0.650817  0.999737
real apple    0.667519  0.800564  0.735999  0.877665  0.998492
fake apple    0.828078  0.905905  0.983757  0.839557  0.999342
real orange   0.580693  0.734686  0.985200  0.585804  0.999443
fake orange   0.810024  0.894993  0.827741  0.974256  0.999346
real grape    0.709576  0.830070  0.973547  0.723526  0.999382
fake grape    0.874475  0.932984  0.930717  0.935363  0.999503
real lemon    0.397246  0.568570  0.410450  0.925084  0.998350
fake lemon    0.845814  0.916418  0.984832  0.856978  0.999669
real avocado  0.723117  0.839263  0.746515  0.958456  0.999659
fake avocado  0.633350  0.775475  0.999598  0.633512  0.999561
real pepper   0.790326  0.882835  0.857396  0.909937  0.999117
fake pepper   0.674807  0.805784  0.994176  0.677485  0.999222
real plant    0.849916  0.918820  0.927270  0.910621  0.998392
fake plant    0.856104  0.922424  0.968579  0.880560  0.999882
real banana   0.215709  0.354837  0.851212  0.224161  0.998169
fake banana   0.675117  0.806004  0.812611  0.799602  0.999292
real onion    0.586080  0.738980  0.783028  0.699713  0.999554
fake onion    0.905347  0.950272  0.995498  0.909069  0.999940
real unknown  0.941794  0.969975  1.000000  0.941794  0.999991
fake unknown  0.287309  0.446332  0.307288  0.815465  0.998296
total         0.685643  0.791803  0.871949  0.782895  0.999094
total(-bg)    0.671559  0.782445  0.866274  0.773087  0.999249
2026-09-24 11:01:51,479 - INFO: Epoch accounting: {'epoch': 287, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11338598, 61533, 64460, 137644, 154435, 98968, 86813, 126225, 162864, 70523, 56118, 33830, 24483, 195079, 101079, 110180, 19878, 119284, 78375, 99334, 50123, 7833, 40613], 'crops_with_class': [202, 33, 29, 39, 35, 29, 29, 23, 30, 29, 26, 10, 8, 52, 30, 20, 18, 37, 29, 39, 27, 9, 18], 'targeted_crops_by_class': [0, 5, 7, 6, 3, 6, 8, 4, 3, 3, 7, 3, 3, 0, 4, 3, 3, 9, 2, 3, 9, 3, 5], 'sampled_scene_counts': [1, 1, 0, 1, 1, 1, 2, 1, 1, 3, 1, 0, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 2, 1, 2, 0, 2, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 2, 1, 2, 1, 2, 4, 0, 1, 0, 2, 1, 2, 1, 1, 2, 0, 0, 0, 1, 1, 2, 1, 1, 1, 0, 2, 0, 3, 2, 0, 1, 0, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 0, 2, 1, 3, 0, 1, 2, 0, 3, 1, 0, 2, 1, 1, 4, 2, 3, 1, 3, 1, 3, 1, 2, 0, 1, 5, 2, 2, 0, 1, 0, 0, 4, 0, 1, 0], 'learning_rate': 3.8939495797649566e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006452578693077356, 'train_segmentation_loss': 0.30509337082062615, 'val_foreground_miou_all22': 0.6715594083354065, 'val_psnr_ref1': 38.36989379882812, 'elapsed_seconds': 318.9635627269745, 'peak_cuda_allocated_gib': 7.509799957275391}

Epoch 288/500 | Batch 10/202 | Rec 0.000779 | Seg 0.422999 | Elapsed 0.2m | ETA 3.9m
Epoch 288/500 | Batch 20/202 | Rec 0.000646 | Seg 0.356644 | Elapsed 0.4m | ETA 3.7m
Epoch 288/500 | Batch 30/202 | Rec 0.000657 | Seg 0.366651 | Elapsed 0.6m | ETA 3.5m
Epoch 288/500 | Batch 40/202 | Rec 0.000660 | Seg 0.368059 | Elapsed 0.8m | ETA 3.3m
Epoch 288/500 | Batch 50/202 | Rec 0.000638 | Seg 0.355310 | Elapsed 1.0m | ETA 3.1m
Epoch 288/500 | Batch 60/202 | Rec 0.000616 | Seg 0.342340 | Elapsed 1.2m | ETA 2.9m
Epoch 288/500 | Batch 70/202 | Rec 0.000615 | Seg 0.336206 | Elapsed 1.4m | ETA 2.7m
Epoch 288/500 | Batch 80/202 | Rec 0.000615 | Seg 0.330078 | Elapsed 1.6m | ETA 2.5m
Epoch 288/500 | Batch 90/202 | Rec 0.000627 | Seg 0.327391 | Elapsed 1.8m | ETA 2.3m
Epoch 288/500 | Batch 100/202 | Rec 0.000624 | Seg 0.320613 | Elapsed 2.0m | ETA 2.1m
Epoch 288/500 | Batch 110/202 | Rec 0.000629 | Seg 0.324699 | Elapsed 2.2m | ETA 1.9m
Epoch 288/500 | Batch 120/202 | Rec 0.000628 | Seg 0.322962 | Elapsed 2.4m | ETA 1.7m
Epoch 288/500 | Batch 130/202 | Rec 0.000631 | Seg 0.322109 | Elapsed 2.6m | ETA 1.5m
Epoch 288/500 | Batch 140/202 | Rec 0.000641 | Seg 0.327468 | Elapsed 2.8m | ETA 1.3m
Epoch 288/500 | Batch 150/202 | Rec 0.000655 | Seg 0.335308 | Elapsed 3.0m | ETA 1.1m
Epoch 288/500 | Batch 160/202 | Rec 0.000653 | Seg 0.331524 | Elapsed 3.2m | ETA 0.8m
Epoch 288/500 | Batch 170/202 | Rec 0.000653 | Seg 0.329871 | Elapsed 3.4m | ETA 0.6m
Epoch 288/500 | Batch 180/202 | Rec 0.000660 | Seg 0.331020 | Elapsed 3.6m | ETA 0.4m
Epoch 288/500 | Batch 190/202 | Rec 0.000661 | Seg 0.327846 | Elapsed 3.8m | ETA 0.2m
Epoch 288/500 | Batch 200/202 | Rec 0.000661 | Seg 0.325160 | Elapsed 4.0m | ETA 0.0m
Epoch 288/500 | Batch 202/202 | Rec 0.000662 | Seg 0.325554 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:05:56,330 - INFO: Rec loss: 0.0006616156786567265
2026-09-24 11:05:56,331 - INFO: Seg loss: 0.325553955086092
2026-09-24 11:05:56,331 - INFO: λ_rec: 1
2026-09-24 11:05:56,331 - INFO: λ_seg: 0.0001
2026-09-24 11:07:09,979 - INFO: -------------------Epoch: 288------------------------
2026-09-24 11:07:09,983 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.707045  0.97417  0.000141
2026-09-24 11:07:09,989 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995208  0.997548  0.996424  0.998775  0.995422
real potato   0.191150  0.320924  1.000000  0.191150  0.999032
fake potato   0.545266  0.705679  0.980261  0.551320  0.999665
real apple    0.644206  0.783558  0.723838  0.854135  0.998372
fake apple    0.658929  0.794355  0.985514  0.665373  0.998700
real orange   0.918280  0.957350  0.995004  0.922534  0.999892
fake orange   0.936678  0.967254  0.981828  0.953203  0.999816
real grape    0.741189  0.851310  0.966394  0.760798  0.999445
fake grape    0.868494  0.929569  0.892631  0.969806  0.999457
real lemon    0.412453  0.583981  0.425015  0.933134  0.998438
fake lemon    0.851445  0.919713  0.993638  0.856113  0.999684
real avocado  0.733894  0.846477  0.765675  0.946470  0.999681
fake avocado  0.592427  0.744009  0.999570  0.592578  0.999512
real pepper   0.834223  0.909570  0.900601  0.918822  0.999332
fake pepper   0.745608  0.854218  0.997266  0.747135  0.999392
real plant    0.839285  0.912571  0.949169  0.878783  0.998317
fake plant    0.865027  0.927580  0.945451  0.910468  0.999887
real banana   0.266933  0.421348  0.882990  0.276721  0.998292
fake banana   0.724844  0.840425  0.841453  0.839499  0.999414
real onion    0.607632  0.755884  0.815321  0.704611  0.999589
fake onion    0.904992  0.950077  0.996813  0.907618  0.999940
real unknown  0.920952  0.958800  0.997936  0.922710  0.999987
fake unknown  0.229090  0.372746  0.239083  0.845708  0.997602
total         0.696879  0.795867  0.881386  0.789020  0.999081
total(-bg)    0.683318  0.786700  0.876157  0.779486  0.999248
2026-09-24 11:07:10,499 - INFO: Epoch accounting: {'epoch': 288, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11240475, 64329, 62894, 117834, 167118, 63590, 69946, 131420, 156620, 60851, 64177, 48556, 50477, 221993, 109270, 180054, 25629, 104424, 69900, 100664, 71992, 11549, 44510], 'crops_with_class': [202, 37, 27, 36, 30, 23, 27, 28, 33, 30, 28, 15, 15, 59, 26, 25, 24, 29, 28, 43, 30, 13, 20], 'targeted_crops_by_class': [0, 6, 8, 2, 3, 3, 4, 7, 4, 7, 2, 5, 6, 8, 2, 6, 1, 7, 2, 6, 6, 7, 4], 'sampled_scene_counts': [0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 2, 2, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 0, 1, 1, 3, 4, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 2, 3, 2, 1, 2, 0, 2, 1, 2, 0, 1, 3, 2, 0, 1, 1, 1, 0, 1, 0, 0, 1, 4, 4, 3, 2, 0, 1, 0, 1, 3, 2, 2, 0, 2, 0, 1, 1, 1, 5, 2, 1, 1, 1, 3, 1, 1, 1, 3, 4, 1, 1, 1, 3, 1, 2, 2, 0, 1, 1, 0, 2, 2, 3, 2, 2, 1, 3, 0, 1, 1, 2, 1, 1, 2, 3, 1, 3, 1, 0, 0], 'learning_rate': 3.863432734450501e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006616156786567265, 'train_segmentation_loss': 0.325553955086092, 'val_foreground_miou_all22': 0.6833181288288678, 'val_psnr_ref1': 38.70704513549805, 'elapsed_seconds': 319.01211810112, 'peak_cuda_allocated_gib': 7.512706756591797}

Epoch 289/500 | Batch 10/202 | Rec 0.000571 | Seg 0.273466 | Elapsed 0.2m | ETA 3.9m
Epoch 289/500 | Batch 20/202 | Rec 0.000754 | Seg 0.339685 | Elapsed 0.4m | ETA 3.7m
Epoch 289/500 | Batch 30/202 | Rec 0.000703 | Seg 0.346317 | Elapsed 0.6m | ETA 3.5m
Epoch 289/500 | Batch 40/202 | Rec 0.000698 | Seg 0.335472 | Elapsed 0.8m | ETA 3.3m
Epoch 289/500 | Batch 50/202 | Rec 0.000661 | Seg 0.326656 | Elapsed 1.0m | ETA 3.1m
Epoch 289/500 | Batch 60/202 | Rec 0.000667 | Seg 0.328339 | Elapsed 1.2m | ETA 2.9m
Epoch 289/500 | Batch 70/202 | Rec 0.000661 | Seg 0.329326 | Elapsed 1.4m | ETA 2.7m
Epoch 289/500 | Batch 80/202 | Rec 0.000665 | Seg 0.324024 | Elapsed 1.6m | ETA 2.5m
Epoch 289/500 | Batch 90/202 | Rec 0.000677 | Seg 0.321365 | Elapsed 1.8m | ETA 2.3m
Epoch 289/500 | Batch 100/202 | Rec 0.000676 | Seg 0.319612 | Elapsed 2.0m | ETA 2.1m
Epoch 289/500 | Batch 110/202 | Rec 0.000676 | Seg 0.322161 | Elapsed 2.2m | ETA 1.9m
Epoch 289/500 | Batch 120/202 | Rec 0.000669 | Seg 0.320678 | Elapsed 2.4m | ETA 1.7m
Epoch 289/500 | Batch 130/202 | Rec 0.000679 | Seg 0.328463 | Elapsed 2.6m | ETA 1.5m
Epoch 289/500 | Batch 140/202 | Rec 0.000683 | Seg 0.334175 | Elapsed 2.8m | ETA 1.3m
Epoch 289/500 | Batch 150/202 | Rec 0.000682 | Seg 0.334912 | Elapsed 3.0m | ETA 1.0m
Epoch 289/500 | Batch 160/202 | Rec 0.000677 | Seg 0.332793 | Elapsed 3.2m | ETA 0.8m
Epoch 289/500 | Batch 170/202 | Rec 0.000677 | Seg 0.331553 | Elapsed 3.4m | ETA 0.6m
Epoch 289/500 | Batch 180/202 | Rec 0.000675 | Seg 0.331140 | Elapsed 3.6m | ETA 0.4m
Epoch 289/500 | Batch 190/202 | Rec 0.000670 | Seg 0.328056 | Elapsed 3.8m | ETA 0.2m
Epoch 289/500 | Batch 200/202 | Rec 0.000669 | Seg 0.326146 | Elapsed 4.0m | ETA 0.0m
Epoch 289/500 | Batch 202/202 | Rec 0.000671 | Seg 0.326313 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:11:14,936 - INFO: Rec loss: 0.0006707279570775319
2026-09-24 11:11:14,936 - INFO: Seg loss: 0.32631322889044734
2026-09-24 11:11:14,936 - INFO: λ_rec: 1
2026-09-24 11:11:14,937 - INFO: λ_seg: 0.0001
2026-09-24 11:12:26,831 - INFO: -------------------Epoch: 289------------------------
2026-09-24 11:12:26,835 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.543564  0.973282  0.000146
2026-09-24 11:12:26,842 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995571  0.997731  0.997019  0.998543  0.995771
real potato   0.928111  0.962665  0.952678  0.972966  0.999910
fake potato   0.947347  0.972912  0.958910  0.987432  0.999960
real apple    0.748955  0.856411  0.993289  0.752764  0.999129
fake apple    0.587969  0.740482  0.988263  0.592103  0.998433
real orange   0.926037  0.961548  0.994556  0.930755  0.999902
fake orange   0.931546  0.964510  0.962283  0.966848  0.999797
real grape    0.638225  0.779118  0.968815  0.651611  0.999229
fake grape    0.902669  0.948795  0.940690  0.957142  0.999618
real lemon    0.746104  0.854543  0.839449  0.870293  0.999652
fake lemon    0.820311  0.901237  0.999210  0.820844  0.999620
real avocado  0.945538  0.971957  0.998960  0.946470  0.999949
fake avocado  0.417517  0.589040  0.999390  0.417623  0.999303
real pepper   0.864953  0.927537  0.889740  0.968797  0.999447
fake pepper   0.872069  0.931613  0.955025  0.909417  0.999682
real plant    0.829990  0.907048  0.927637  0.887448  0.998182
fake plant    0.832145  0.908334  0.878831  0.939992  0.999849
real banana   0.780063  0.876394  0.893190  0.860315  0.999455
fake banana   0.688186  0.815247  0.752509  0.889516  0.999259
real onion    0.619703  0.765158  0.630485  0.973146  0.999460
fake onion    0.937515  0.967700  0.977783  0.957920  0.999960
real unknown  0.643693  0.783179  0.668919  0.944656  0.999916
fake unknown  0.176149  0.299499  0.194370  0.652662  0.997428
total         0.773059  0.855768  0.885304  0.863012  0.999257
total(-bg)    0.762945  0.849315  0.880226  0.856851  0.999415
2026-09-24 11:12:27,357 - INFO: Epoch accounting: {'epoch': 289, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11191838, 43667, 59656, 105390, 143190, 89613, 71748, 154294, 208999, 86226, 65263, 36163, 40339, 241307, 127635, 152199, 18784, 78684, 88298, 93418, 61144, 15692, 64725], 'crops_with_class': [202, 26, 26, 36, 36, 28, 28, 29, 37, 39, 31, 13, 16, 63, 34, 24, 21, 26, 32, 38, 33, 16, 25], 'targeted_crops_by_class': [0, 4, 8, 4, 6, 4, 7, 5, 4, 7, 1, 1, 4, 8, 2, 6, 4, 5, 3, 7, 6, 7, 6], 'sampled_scene_counts': [1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 0, 1, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 1, 1, 2, 0, 0, 2, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 2, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 1, 0, 0, 0, 1, 2, 1, 1, 0, 1, 0, 3, 1, 0, 1, 2, 3, 2, 2, 2, 1, 0, 4, 1, 2, 0, 1, 1, 1, 1, 2, 0, 1, 1, 0, 2, 3, 0, 1, 2, 3, 1, 3, 1, 0, 3, 0, 1, 1, 4, 4, 3, 4, 0, 0, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 3, 2, 1, 2, 2, 3, 3, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 3, 3, 0], 'learning_rate': 3.832961252344169e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006707279570775319, 'train_segmentation_loss': 0.32631322889044734, 'val_foreground_miou_all22': 0.762945178483022, 'val_psnr_ref1': 38.543564300537106, 'elapsed_seconds': 316.8511667251587, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 290/500 | Batch 10/202 | Rec 0.000670 | Seg 0.315864 | Elapsed 0.2m | ETA 3.9m
Epoch 290/500 | Batch 20/202 | Rec 0.000613 | Seg 0.286281 | Elapsed 0.4m | ETA 3.8m
Epoch 290/500 | Batch 30/202 | Rec 0.000626 | Seg 0.289301 | Elapsed 0.6m | ETA 3.6m
Epoch 290/500 | Batch 40/202 | Rec 0.000597 | Seg 0.274937 | Elapsed 0.8m | ETA 3.4m
Epoch 290/500 | Batch 50/202 | Rec 0.000602 | Seg 0.289442 | Elapsed 1.0m | ETA 3.1m
Epoch 290/500 | Batch 60/202 | Rec 0.000591 | Seg 0.277971 | Elapsed 1.2m | ETA 2.9m
Epoch 290/500 | Batch 70/202 | Rec 0.000613 | Seg 0.288143 | Elapsed 1.4m | ETA 2.7m
Epoch 290/500 | Batch 80/202 | Rec 0.000623 | Seg 0.295658 | Elapsed 1.6m | ETA 2.5m
Epoch 290/500 | Batch 90/202 | Rec 0.000628 | Seg 0.297006 | Elapsed 1.8m | ETA 2.3m
Epoch 290/500 | Batch 100/202 | Rec 0.000646 | Seg 0.305920 | Elapsed 2.1m | ETA 2.1m
Epoch 290/500 | Batch 110/202 | Rec 0.000651 | Seg 0.301425 | Elapsed 2.3m | ETA 1.9m
Epoch 290/500 | Batch 120/202 | Rec 0.000653 | Seg 0.299826 | Elapsed 2.5m | ETA 1.7m
Epoch 290/500 | Batch 130/202 | Rec 0.000659 | Seg 0.302389 | Elapsed 2.7m | ETA 1.5m
Epoch 290/500 | Batch 140/202 | Rec 0.000652 | Seg 0.301089 | Elapsed 2.9m | ETA 1.3m
Epoch 290/500 | Batch 150/202 | Rec 0.000657 | Seg 0.304960 | Elapsed 3.1m | ETA 1.1m
Epoch 290/500 | Batch 160/202 | Rec 0.000666 | Seg 0.305013 | Elapsed 3.3m | ETA 0.9m
Epoch 290/500 | Batch 170/202 | Rec 0.000664 | Seg 0.305525 | Elapsed 3.5m | ETA 0.7m
Epoch 290/500 | Batch 180/202 | Rec 0.000665 | Seg 0.306794 | Elapsed 3.7m | ETA 0.4m
Epoch 290/500 | Batch 190/202 | Rec 0.000666 | Seg 0.306370 | Elapsed 3.9m | ETA 0.2m
Epoch 290/500 | Batch 200/202 | Rec 0.000679 | Seg 0.308274 | Elapsed 4.1m | ETA 0.0m
Epoch 290/500 | Batch 202/202 | Rec 0.000681 | Seg 0.308339 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:16:34,588 - INFO: Rec loss: 0.0006808523288386238
2026-09-24 11:16:34,588 - INFO: Seg loss: 0.30833948449701953
2026-09-24 11:16:34,588 - INFO: λ_rec: 1
2026-09-24 11:16:34,588 - INFO: λ_seg: 0.0001
2026-09-24 11:17:45,912 - INFO: -------------------Epoch: 290------------------------
2026-09-24 11:17:45,916 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.559233  0.973551  0.000144
2026-09-24 11:17:45,923 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995428  0.997659  0.996727  0.998692  0.995633
real potato   0.923372  0.960109  0.967746  0.952691  0.999905
fake potato   0.955606  0.977249  0.976176  0.978425  0.999967
real apple    0.721184  0.837960  0.976576  0.733879  0.999021
fake apple    0.582844  0.736405  0.993277  0.585152  0.998419
real orange   0.844887  0.915873  0.993500  0.849583  0.999794
fake orange   0.895775  0.944972  0.922753  0.968394  0.999677
real grape    0.737829  0.849089  0.874526  0.825185  0.999388
fake grape    0.882777  0.937689  0.925863  0.949924  0.999533
real lemon    0.793606  0.884878  0.865170  0.905609  0.999723
fake lemon    0.827713  0.905687  0.998870  0.828489  0.999635
real avocado  0.872093  0.931627  0.915649  0.948276  0.999871
fake avocado  0.461303  0.631315  0.999724  0.461362  0.999355
real pepper   0.816180  0.898738  0.845922  0.958702  0.999210
fake pepper   0.736923  0.848489  0.954258  0.763908  0.999350
real plant    0.853914  0.921152  0.954044  0.890545  0.998476
fake plant    0.775514  0.873515  0.850936  0.897431  0.999793
real banana   0.794819  0.885632  0.907749  0.864661  0.999498
fake banana   0.747036  0.855154  0.843140  0.867618  0.999460
real onion    0.625871  0.769842  0.644394  0.956088  0.999484
fake onion    0.939128  0.968559  0.978529  0.958888  0.999961
real unknown  0.505937  0.671877  0.524345  0.935114  0.999854
fake unknown  0.199550  0.332670  0.222569  0.658638  0.997774
total         0.760404  0.849397  0.875324  0.858141  0.999251
total(-bg)    0.749721  0.842658  0.869805  0.851753  0.999416
2026-09-24 11:17:46,437 - INFO: Epoch accounting: {'epoch': 290, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11296456, 69992, 62919, 132052, 129786, 72211, 61414, 133287, 182992, 85150, 67268, 51482, 45699, 244175, 142911, 131807, 34200, 88545, 58109, 69441, 46135, 5360, 26881], 'crops_with_class': [202, 34, 27, 35, 34, 24, 21, 30, 37, 37, 29, 18, 15, 63, 36, 22, 27, 26, 25, 32, 24, 5, 10], 'targeted_crops_by_class': [0, 2, 6, 6, 5, 3, 1, 3, 5, 4, 1, 7, 5, 6, 11, 6, 8, 2, 2, 5, 4, 2, 0], 'sampled_scene_counts': [1, 1, 2, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 0, 2, 3, 1, 2, 1, 0, 0, 2, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 0, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 0, 2, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 2, 2, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 0, 1, 1, 2, 2, 1, 1, 2, 0, 1, 5, 1, 0, 1, 3, 4, 2, 1, 1, 3, 1, 2, 2, 0, 1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 3, 2, 0, 4, 3, 0, 2, 1, 0, 1, 0, 0, 0, 3, 1, 0, 0, 2, 0, 3, 2, 0, 3, 3, 1, 1, 0, 2, 1, 0, 1, 3, 3], 'learning_rate': 3.802536336407901e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006808523288386238, 'train_segmentation_loss': 0.30833948449701953, 'val_foreground_miou_all22': 0.7497209020871267, 'val_psnr_ref1': 38.55923294067383, 'elapsed_seconds': 319.07150530815125, 'peak_cuda_allocated_gib': 7.510753631591797}

Epoch 291/500 | Batch 10/202 | Rec 0.000689 | Seg 0.329707 | Elapsed 0.2m | ETA 4.0m
Epoch 291/500 | Batch 20/202 | Rec 0.000661 | Seg 0.308901 | Elapsed 0.4m | ETA 3.7m
Epoch 291/500 | Batch 30/202 | Rec 0.000716 | Seg 0.300091 | Elapsed 0.6m | ETA 3.5m
Epoch 291/500 | Batch 40/202 | Rec 0.000712 | Seg 0.314217 | Elapsed 0.8m | ETA 3.3m
Epoch 291/500 | Batch 50/202 | Rec 0.000716 | Seg 0.326867 | Elapsed 1.0m | ETA 3.1m
Epoch 291/500 | Batch 60/202 | Rec 0.000686 | Seg 0.311449 | Elapsed 1.2m | ETA 2.9m
Epoch 291/500 | Batch 70/202 | Rec 0.000702 | Seg 0.317687 | Elapsed 1.4m | ETA 2.7m
Epoch 291/500 | Batch 80/202 | Rec 0.000686 | Seg 0.314724 | Elapsed 1.6m | ETA 2.5m
Epoch 291/500 | Batch 90/202 | Rec 0.000683 | Seg 0.313153 | Elapsed 1.8m | ETA 2.3m
Epoch 291/500 | Batch 100/202 | Rec 0.000676 | Seg 0.313067 | Elapsed 2.0m | ETA 2.1m
Epoch 291/500 | Batch 110/202 | Rec 0.000671 | Seg 0.320025 | Elapsed 2.2m | ETA 1.9m
Epoch 291/500 | Batch 120/202 | Rec 0.000670 | Seg 0.319971 | Elapsed 2.4m | ETA 1.7m
Epoch 291/500 | Batch 130/202 | Rec 0.000668 | Seg 0.321569 | Elapsed 2.6m | ETA 1.5m
Epoch 291/500 | Batch 140/202 | Rec 0.000666 | Seg 0.318953 | Elapsed 2.8m | ETA 1.3m
Epoch 291/500 | Batch 150/202 | Rec 0.000661 | Seg 0.317410 | Elapsed 3.0m | ETA 1.1m
Epoch 291/500 | Batch 160/202 | Rec 0.000660 | Seg 0.322167 | Elapsed 3.2m | ETA 0.8m
Epoch 291/500 | Batch 170/202 | Rec 0.000660 | Seg 0.325014 | Elapsed 3.4m | ETA 0.6m
Epoch 291/500 | Batch 180/202 | Rec 0.000666 | Seg 0.323643 | Elapsed 3.6m | ETA 0.4m
Epoch 291/500 | Batch 190/202 | Rec 0.000668 | Seg 0.323658 | Elapsed 3.8m | ETA 0.2m
Epoch 291/500 | Batch 200/202 | Rec 0.000670 | Seg 0.322988 | Elapsed 4.0m | ETA 0.0m
Epoch 291/500 | Batch 202/202 | Rec 0.000666 | Seg 0.321704 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:21:50,683 - INFO: Rec loss: 0.0006662913456779333
2026-09-24 11:21:50,684 - INFO: Seg loss: 0.3217038677470519
2026-09-24 11:21:50,684 - INFO: λ_rec: 1
2026-09-24 11:21:50,684 - INFO: λ_seg: 0.0001
2026-09-24 11:23:03,311 - INFO: -------------------Epoch: 291------------------------
2026-09-24 11:23:03,315 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.646898  0.973144  0.000143
2026-09-24 11:23:03,322 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995696  0.997793  0.996970  0.998718  0.995890
real potato   0.421777  0.593268  0.999698  0.421831  0.999308
fake potato   0.661870  0.796488  0.972516  0.674487  0.999749
real apple    0.699560  0.823175  0.791286  0.857851  0.998729
fake apple    0.719818  0.837037  0.983419  0.728661  0.998929
real orange   0.851647  0.919831  0.993817  0.856183  0.999803
fake orange   0.903768  0.949402  0.926024  0.974097  0.999703
real grape    0.757895  0.862227  0.976962  0.771687  0.999485
fake grape    0.877912  0.934937  0.938935  0.931073  0.999521
real lemon    0.442105  0.613095  0.451668  0.954298  0.998585
fake lemon    0.850158  0.918962  0.994708  0.854021  0.999682
real avocado  0.826186  0.904772  0.864493  0.949097  0.999814
fake avocado  0.813384  0.897040  0.999530  0.813695  0.999777
real pepper   0.834508  0.909740  0.878824  0.943017  0.999316
fake pepper   0.742062  0.851886  0.959657  0.765956  0.999365
real plant    0.866664  0.928520  0.936824  0.920460  0.998584
fake plant    0.850732  0.919297  0.976298  0.868673  0.999879
real banana   0.297837  0.458937  0.894861  0.308638  0.998365
fake banana   0.749228  0.856589  0.868018  0.845554  0.999479
real onion    0.681477  0.810520  0.745184  0.888532  0.999625
fake onion    0.948263  0.973395  0.989997  0.957436  0.999967
real unknown  0.933206  0.965399  1.000000  0.933206  0.999989
fake unknown  0.255377  0.406814  0.279378  0.748280  0.998162
total         0.738310  0.831701  0.887785  0.824585  0.999205
total(-bg)    0.726611  0.824151  0.882823  0.816670  0.999355
2026-09-24 11:23:03,836 - INFO: Epoch accounting: {'epoch': 291, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11197424, 70094, 61128, 98228, 149899, 103876, 75114, 153502, 199610, 65890, 74610, 36319, 53302, 205025, 169907, 88229, 9669, 111789, 84655, 97758, 74563, 9329, 48352], 'crops_with_class': [202, 37, 28, 28, 38, 28, 27, 28, 36, 24, 30, 11, 18, 54, 45, 12, 8, 32, 34, 49, 32, 12, 19], 'targeted_crops_by_class': [0, 3, 5, 1, 5, 2, 10, 6, 6, 1, 7, 1, 10, 1, 7, 4, 2, 9, 9, 8, 3, 5, 4], 'sampled_scene_counts': [2, 0, 1, 0, 0, 1, 0, 1, 2, 2, 1, 1, 0, 1, 1, 1, 3, 2, 0, 1, 0, 1, 0, 2, 1, 0, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 2, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 3, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 3, 2, 2, 2, 0, 1, 3, 2, 1, 3, 0, 1, 0, 1, 0, 0, 0, 3, 2, 1, 1, 1, 0, 0, 0, 1, 2, 1, 0, 1, 0, 5, 2, 1, 2, 1, 2, 4, 3, 2, 3, 4, 1, 1, 1, 1, 1, 2, 4, 3, 0, 2, 1, 0, 3, 0, 2, 2, 1, 1, 3, 1, 1, 3, 0, 2, 0, 1, 1, 1, 2, 1, 0, 2], 'learning_rate': 3.772159187765283e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006662913456779333, 'train_segmentation_loss': 0.3217038677470519, 'val_foreground_miou_all22': 0.7266107966359866, 'val_psnr_ref1': 38.6468977355957, 'elapsed_seconds': 317.3902666568756, 'peak_cuda_allocated_gib': 7.510288238525391}

Epoch 292/500 | Batch 10/202 | Rec 0.000656 | Seg 0.374274 | Elapsed 0.2m | ETA 4.0m
Epoch 292/500 | Batch 20/202 | Rec 0.000653 | Seg 0.341144 | Elapsed 0.4m | ETA 3.8m
Epoch 292/500 | Batch 30/202 | Rec 0.000666 | Seg 0.340282 | Elapsed 0.6m | ETA 3.5m
Epoch 292/500 | Batch 40/202 | Rec 0.000651 | Seg 0.328251 | Elapsed 0.8m | ETA 3.3m
Epoch 292/500 | Batch 50/202 | Rec 0.000636 | Seg 0.313414 | Elapsed 1.0m | ETA 3.1m
Epoch 292/500 | Batch 60/202 | Rec 0.000672 | Seg 0.306419 | Elapsed 1.2m | ETA 2.9m
Epoch 292/500 | Batch 70/202 | Rec 0.000651 | Seg 0.293201 | Elapsed 1.4m | ETA 2.7m
Epoch 292/500 | Batch 80/202 | Rec 0.000672 | Seg 0.303477 | Elapsed 1.6m | ETA 2.5m
Epoch 292/500 | Batch 90/202 | Rec 0.000677 | Seg 0.308896 | Elapsed 1.8m | ETA 2.3m
Epoch 292/500 | Batch 100/202 | Rec 0.000670 | Seg 0.310639 | Elapsed 2.0m | ETA 2.1m
Epoch 292/500 | Batch 110/202 | Rec 0.000661 | Seg 0.310340 | Elapsed 2.2m | ETA 1.9m
Epoch 292/500 | Batch 120/202 | Rec 0.000651 | Seg 0.310298 | Elapsed 2.4m | ETA 1.7m
Epoch 292/500 | Batch 130/202 | Rec 0.000670 | Seg 0.311463 | Elapsed 2.6m | ETA 1.5m
Epoch 292/500 | Batch 140/202 | Rec 0.000672 | Seg 0.313928 | Elapsed 2.8m | ETA 1.3m
Epoch 292/500 | Batch 150/202 | Rec 0.000676 | Seg 0.317459 | Elapsed 3.0m | ETA 1.1m
Epoch 292/500 | Batch 160/202 | Rec 0.000669 | Seg 0.314335 | Elapsed 3.3m | ETA 0.9m
Epoch 292/500 | Batch 170/202 | Rec 0.000672 | Seg 0.314465 | Elapsed 3.5m | ETA 0.7m
Epoch 292/500 | Batch 180/202 | Rec 0.000669 | Seg 0.311920 | Elapsed 3.7m | ETA 0.4m
Epoch 292/500 | Batch 190/202 | Rec 0.000673 | Seg 0.315598 | Elapsed 3.9m | ETA 0.2m
Epoch 292/500 | Batch 200/202 | Rec 0.000687 | Seg 0.317266 | Elapsed 4.1m | ETA 0.0m
Epoch 292/500 | Batch 202/202 | Rec 0.000689 | Seg 0.316799 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:27:10,554 - INFO: Rec loss: 0.0006891068063634863
2026-09-24 11:27:10,554 - INFO: Seg loss: 0.31679867016206875
2026-09-24 11:27:10,554 - INFO: λ_rec: 1
2026-09-24 11:27:10,554 - INFO: λ_seg: 0.0001
2026-09-24 11:28:21,880 - INFO: -------------------Epoch: 292------------------------
2026-09-24 11:28:21,883 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.757509  0.97349  0.000139
2026-09-24 11:28:21,890 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995544  0.997717  0.996761  0.998775  0.995744
real potato   0.597144  0.747718  0.999573  0.597297  0.999518
fake potato   0.753661  0.859480  0.963088  0.776079  0.999815
real apple    0.711258  0.831219  0.851733  0.811765  0.998863
fake apple    0.619873  0.765288  0.968097  0.632800  0.998535
real orange   0.940374  0.969221  0.997793  0.942334  0.999921
fake orange   0.944315  0.971310  0.970172  0.972551  0.999836
real grape    0.651074  0.788618  0.933900  0.682526  0.999236
fake grape    0.887131  0.940140  0.938875  0.941509  0.999557
real lemon    0.457681  0.627913  0.479015  0.911322  0.998731
fake lemon    0.843455  0.915031  0.998635  0.844428  0.999668
real avocado  0.831624  0.908023  0.862589  0.958621  0.999820
fake avocado  0.810683  0.895395  0.999686  0.810890  0.999773
real pepper   0.858532  0.923832  0.912621  0.935425  0.999436
fake pepper   0.841410  0.913826  0.950052  0.880353  0.999604
real plant    0.839675  0.912801  0.925121  0.900903  0.998279
fake plant    0.882690  0.937640  0.960402  0.916028  0.999903
real banana   0.385495  0.556429  0.887320  0.405337  0.998548
fake banana   0.720198  0.837293  0.831860  0.842900  0.999398
real onion    0.664554  0.798427  0.715605  0.903057  0.999588
fake onion    0.933173  0.965382  0.993601  0.938815  0.999958
real unknown  0.842195  0.914289  0.892727  0.937023  0.999972
fake unknown  0.228149  0.371494  0.251359  0.711880  0.997971
total         0.749560  0.841239  0.881765  0.837070  0.999203
total(-bg)    0.738379  0.834126  0.876537  0.829720  0.999360
2026-09-24 11:28:22,426 - INFO: Epoch accounting: {'epoch': 292, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11220871, 49723, 56133, 166884, 190105, 73610, 72388, 134811, 185270, 77694, 85317, 55688, 41746, 237917, 165889, 100266, 29872, 68068, 57215, 61231, 39642, 10198, 57734], 'crops_with_class': [202, 26, 23, 43, 46, 24, 26, 25, 37, 36, 31, 18, 19, 58, 36, 18, 21, 20, 22, 28, 20, 11, 24], 'targeted_crops_by_class': [0, 4, 2, 7, 6, 1, 6, 5, 6, 7, 4, 6, 3, 5, 5, 3, 4, 2, 4, 4, 1, 5, 4], 'sampled_scene_counts': [1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 3, 1, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 1, 1, 0, 1, 2, 3, 0, 1, 1, 0, 1, 1, 0, 1, 2, 2, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 3, 1, 1, 4, 2, 2, 1, 1, 0, 4, 4, 2, 0, 2, 2, 3, 0, 1, 1, 0, 1, 2, 1, 0, 3, 1, 1, 2, 3, 0, 1, 2, 1, 1, 0, 2, 0, 1, 6, 1, 2, 4, 3, 2, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 2, 0, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0, 1, 2, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1], 'learning_rate': 3.741831005654128e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006891068063634863, 'train_segmentation_loss': 0.31679867016206875, 'val_foreground_miou_all22': 0.7383793105408096, 'val_psnr_ref1': 38.757508544921876, 'elapsed_seconds': 318.58254384994507, 'peak_cuda_allocated_gib': 7.508823394775391}

Epoch 293/500 | Batch 10/202 | Rec 0.000782 | Seg 0.296298 | Elapsed 0.2m | ETA 4.0m
Epoch 293/500 | Batch 20/202 | Rec 0.000703 | Seg 0.296541 | Elapsed 0.4m | ETA 3.7m
Epoch 293/500 | Batch 30/202 | Rec 0.000674 | Seg 0.267602 | Elapsed 0.6m | ETA 3.5m
Epoch 293/500 | Batch 40/202 | Rec 0.000690 | Seg 0.281166 | Elapsed 0.8m | ETA 3.3m
Epoch 293/500 | Batch 50/202 | Rec 0.000665 | Seg 0.272324 | Elapsed 1.0m | ETA 3.1m
Epoch 293/500 | Batch 60/202 | Rec 0.000672 | Seg 0.287952 | Elapsed 1.2m | ETA 2.9m
Epoch 293/500 | Batch 70/202 | Rec 0.000652 | Seg 0.281748 | Elapsed 1.4m | ETA 2.7m
Epoch 293/500 | Batch 80/202 | Rec 0.000663 | Seg 0.283082 | Elapsed 1.7m | ETA 2.5m
Epoch 293/500 | Batch 90/202 | Rec 0.000669 | Seg 0.281872 | Elapsed 1.9m | ETA 2.3m
Epoch 293/500 | Batch 100/202 | Rec 0.000661 | Seg 0.281192 | Elapsed 2.1m | ETA 2.1m
Epoch 293/500 | Batch 110/202 | Rec 0.000661 | Seg 0.286245 | Elapsed 2.3m | ETA 1.9m
Epoch 293/500 | Batch 120/202 | Rec 0.000667 | Seg 0.292125 | Elapsed 2.5m | ETA 1.7m
Epoch 293/500 | Batch 130/202 | Rec 0.000657 | Seg 0.291452 | Elapsed 2.7m | ETA 1.5m
Epoch 293/500 | Batch 140/202 | Rec 0.000657 | Seg 0.292090 | Elapsed 2.9m | ETA 1.3m
Epoch 293/500 | Batch 150/202 | Rec 0.000659 | Seg 0.293333 | Elapsed 3.1m | ETA 1.1m
Epoch 293/500 | Batch 160/202 | Rec 0.000659 | Seg 0.294205 | Elapsed 3.3m | ETA 0.9m
Epoch 293/500 | Batch 170/202 | Rec 0.000659 | Seg 0.294791 | Elapsed 3.5m | ETA 0.7m
Epoch 293/500 | Batch 180/202 | Rec 0.000657 | Seg 0.293430 | Elapsed 3.7m | ETA 0.5m
Epoch 293/500 | Batch 190/202 | Rec 0.000659 | Seg 0.294817 | Elapsed 3.9m | ETA 0.2m
Epoch 293/500 | Batch 200/202 | Rec 0.000678 | Seg 0.295254 | Elapsed 4.1m | ETA 0.0m
Epoch 293/500 | Batch 202/202 | Rec 0.000680 | Seg 0.295036 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:32:30,537 - INFO: Rec loss: 0.0006797891713870173
2026-09-24 11:32:30,537 - INFO: Seg loss: 0.29503580251026273
2026-09-24 11:32:30,537 - INFO: λ_rec: 1
2026-09-24 11:32:30,537 - INFO: λ_seg: 0.0001
2026-09-24 11:33:47,141 - INFO: -------------------Epoch: 293------------------------
2026-09-24 11:33:47,145 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.448571  0.97301  0.000148
2026-09-24 11:33:47,152 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995621  0.997755  0.997064  0.998548  0.995818
real potato   0.929352  0.963332  0.950820  0.976282  0.999911
fake potato   0.947495  0.972990  0.959853  0.986594  0.999960
real apple    0.712270  0.831911  0.995624  0.714507  0.999004
fake apple    0.558586  0.716739  0.991645  0.561227  0.998326
real orange   0.928810  0.963041  0.994450  0.933650  0.999906
fake orange   0.935607  0.966682  0.963915  0.969566  0.999809
real grape    0.621389  0.766440  0.821372  0.718483  0.999086
fake grape    0.897201  0.945765  0.942311  0.949346  0.999598
real lemon    0.622293  0.767127  0.777141  0.757466  0.999460
fake lemon    0.818601  0.900204  0.997631  0.820195  0.999615
real avocado  0.923333  0.960089  0.965157  0.955172  0.999926
fake avocado  0.481448  0.649926  0.999735  0.481510  0.999379
real pepper   0.893791  0.943867  0.923697  0.965043  0.999581
fake pepper   0.862689  0.926233  0.950428  0.903335  0.999657
real plant    0.839657  0.912791  0.929220  0.897028  0.998287
fake plant    0.830508  0.907357  0.869466  0.948811  0.999846
real banana   0.772691  0.871722  0.892972  0.851555  0.999437
fake banana   0.656977  0.792933  0.731232  0.866125  0.999168
real onion    0.648332  0.786604  0.665614  0.961493  0.999529
fake onion    0.943968  0.971126  0.985316  0.957436  0.999964
real unknown  0.647449  0.785953  0.679416  0.932252  0.999919
fake unknown  0.192421  0.322705  0.208765  0.710793  0.997486
total         0.767847  0.853187  0.877950  0.861583  0.999247
total(-bg)    0.757494  0.846615  0.872536  0.855358  0.999402
2026-09-24 11:33:47,674 - INFO: Epoch accounting: {'epoch': 293, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11399014, 46988, 67380, 112024, 93089, 64954, 81269, 156537, 194433, 81353, 60644, 35571, 35870, 191067, 129532, 132686, 28239, 89667, 56894, 74071, 50518, 11889, 44583], 'crops_with_class': [202, 24, 31, 27, 27, 22, 27, 30, 40, 36, 29, 15, 15, 49, 34, 23, 28, 29, 26, 35, 21, 10, 22], 'targeted_crops_by_class': [0, 4, 5, 5, 2, 2, 8, 7, 6, 6, 4, 3, 3, 3, 6, 5, 3, 3, 5, 3, 4, 2, 4], 'sampled_scene_counts': [1, 0, 3, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 2, 2, 1, 0, 1, 1, 1, 3, 0, 2, 2, 1, 0, 0, 1, 1, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 3, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 0, 0, 1, 0, 2, 1, 1, 2, 0, 1, 2, 1, 0, 2, 1, 0, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 2, 0, 1, 0, 1, 1, 1, 0, 2, 3, 0, 2, 1, 1, 1, 2, 1, 3, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 0, 0, 1, 0, 1, 5, 2, 2, 1, 1, 0, 0, 1, 1, 0, 2, 1, 2, 2, 3, 1, 2, 1, 2, 1, 0, 3, 2, 3, 1, 0, 0, 2, 0, 0, 5, 1, 1, 1, 1, 2, 2, 1, 2, 3, 1], 'learning_rate': 3.711552987379135e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006797891713870173, 'train_segmentation_loss': 0.29503580251026273, 'val_foreground_miou_all22': 0.7574939970007065, 'val_psnr_ref1': 38.44857070922851, 'elapsed_seconds': 325.2399048805237, 'peak_cuda_allocated_gib': 7.504093170166016}

Epoch 294/500 | Batch 10/202 | Rec 0.000672 | Seg 0.314553 | Elapsed 0.2m | ETA 4.0m
Epoch 294/500 | Batch 20/202 | Rec 0.000653 | Seg 0.303087 | Elapsed 0.4m | ETA 3.8m
Epoch 294/500 | Batch 30/202 | Rec 0.000718 | Seg 0.310804 | Elapsed 0.6m | ETA 3.5m
Epoch 294/500 | Batch 40/202 | Rec 0.000665 | Seg 0.284594 | Elapsed 0.8m | ETA 3.3m
Epoch 294/500 | Batch 50/202 | Rec 0.000665 | Seg 0.283047 | Elapsed 1.0m | ETA 3.1m
Epoch 294/500 | Batch 60/202 | Rec 0.000656 | Seg 0.284321 | Elapsed 1.2m | ETA 2.9m
Epoch 294/500 | Batch 70/202 | Rec 0.000649 | Seg 0.284937 | Elapsed 1.5m | ETA 2.7m
Epoch 294/500 | Batch 80/202 | Rec 0.000651 | Seg 0.284639 | Elapsed 1.7m | ETA 2.5m
Epoch 294/500 | Batch 90/202 | Rec 0.000674 | Seg 0.280829 | Elapsed 1.9m | ETA 2.3m
Epoch 294/500 | Batch 100/202 | Rec 0.000673 | Seg 0.283550 | Elapsed 2.1m | ETA 2.1m
Epoch 294/500 | Batch 110/202 | Rec 0.000657 | Seg 0.278673 | Elapsed 2.3m | ETA 1.9m
Epoch 294/500 | Batch 120/202 | Rec 0.000651 | Seg 0.277538 | Elapsed 2.5m | ETA 1.7m
Epoch 294/500 | Batch 130/202 | Rec 0.000650 | Seg 0.282529 | Elapsed 2.7m | ETA 1.5m
Epoch 294/500 | Batch 140/202 | Rec 0.000662 | Seg 0.292438 | Elapsed 2.9m | ETA 1.3m
Epoch 294/500 | Batch 150/202 | Rec 0.000665 | Seg 0.295869 | Elapsed 3.1m | ETA 1.1m
Epoch 294/500 | Batch 160/202 | Rec 0.000660 | Seg 0.297568 | Elapsed 3.3m | ETA 0.9m
Epoch 294/500 | Batch 170/202 | Rec 0.000659 | Seg 0.300686 | Elapsed 3.5m | ETA 0.7m
Epoch 294/500 | Batch 180/202 | Rec 0.000656 | Seg 0.300073 | Elapsed 3.7m | ETA 0.5m
Epoch 294/500 | Batch 190/202 | Rec 0.000652 | Seg 0.298956 | Elapsed 3.9m | ETA 0.2m
Epoch 294/500 | Batch 200/202 | Rec 0.000650 | Seg 0.298534 | Elapsed 4.1m | ETA 0.0m
Epoch 294/500 | Batch 202/202 | Rec 0.000649 | Seg 0.299002 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:37:55,878 - INFO: Rec loss: 0.0006485506915256823
2026-09-24 11:37:55,878 - INFO: Seg loss: 0.2990024624263296
2026-09-24 11:37:55,878 - INFO: λ_rec: 1
2026-09-24 11:37:55,879 - INFO: λ_seg: 0.0001
2026-09-24 11:39:08,274 - INFO: -------------------Epoch: 294------------------------
2026-09-24 11:39:08,278 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.708347  0.973906  0.00014
2026-09-24 11:39:08,284 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995672  0.997781  0.997534  0.998129  0.995869
real potato   0.908037  0.951753  0.964641  0.939301  0.999886
fake potato   0.949702  0.974152  0.979462  0.968999  0.999963
real apple    0.796519  0.886687  0.979928  0.809730  0.999286
fake apple    0.647387  0.785908  0.987527  0.652724  0.998658
real orange   0.907312  0.951354  0.987176  0.918133  0.999876
fake orange   0.928720  0.962993  0.953361  0.972924  0.999786
real grape    0.690963  0.817192  0.896293  0.751005  0.999299
fake grape    0.888559  0.940941  0.909991  0.974178  0.999548
real lemon    0.696126  0.820793  0.764127  0.886653  0.999545
fake lemon    0.842109  0.914238  0.998463  0.843202  0.999666
real avocado  0.852742  0.920469  0.873617  0.972742  0.999844
fake avocado  0.691866  0.817825  0.999632  0.692043  0.999631
real pepper   0.839298  0.912578  0.882312  0.945103  0.999338
fake pepper   0.769684  0.869805  0.961553  0.794123  0.999434
real plant    0.863160  0.926505  0.923682  0.929445  0.998526
fake plant    0.834677  0.909840  0.870968  0.952454  0.999850
real banana   0.738006  0.849206  0.899461  0.804360  0.999358
fake banana   0.688089  0.815178  0.779535  0.854346  0.999288
real onion    0.647972  0.786339  0.663149  0.965884  0.999526
fake onion    0.923595  0.960230  0.958775  0.961790  0.999950
real unknown  0.639668  0.780193  0.658569  0.957061  0.999914
fake unknown  0.243960  0.392192  0.267963  0.731438  0.998090
total         0.781905  0.867137  0.876423  0.881555  0.999310
total(-bg)    0.772189  0.861199  0.870917  0.876256  0.999466
2026-09-24 11:39:08,836 - INFO: Epoch accounting: {'epoch': 294, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11339228, 63977, 60285, 146648, 142911, 60407, 59584, 156615, 161788, 70286, 55781, 47541, 41259, 225935, 129570, 128663, 21829, 67125, 63192, 81648, 59285, 10898, 43817], 'crops_with_class': [202, 33, 28, 39, 32, 20, 21, 28, 34, 29, 26, 18, 16, 58, 34, 17, 20, 20, 30, 34, 25, 11, 18], 'targeted_crops_by_class': [0, 6, 2, 8, 1, 2, 2, 3, 3, 5, 4, 7, 9, 6, 4, 1, 2, 2, 4, 8, 4, 4, 1], 'sampled_scene_counts': [0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 0, 1, 1, 0, 2, 1, 2, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 2, 2, 0, 1, 0, 1, 1, 1, 4, 1, 1, 0, 2, 1, 2, 1, 1, 0, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 2, 2, 1, 1, 2, 3, 0, 3, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 3, 0, 0, 0, 1, 1, 0, 2, 1, 2, 1, 2, 1, 2, 0, 1, 2, 0, 1, 2, 1, 3, 3, 3, 1, 1, 2, 1, 0, 0, 3, 1, 1, 3, 2, 2, 0, 1, 3, 2, 2, 1, 3, 3, 1, 1, 0, 0, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1], 'learning_rate': 3.6813263282646235e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006485506915256823, 'train_segmentation_loss': 0.2990024624263296, 'val_foreground_miou_all22': 0.7721887645933982, 'val_psnr_ref1': 38.70834701538086, 'elapsed_seconds': 321.1538918018341, 'peak_cuda_allocated_gib': 7.508609771728516}

Epoch 295/500 | Batch 10/202 | Rec 0.000570 | Seg 0.296743 | Elapsed 0.2m | ETA 3.8m
Epoch 295/500 | Batch 20/202 | Rec 0.000605 | Seg 0.315985 | Elapsed 0.4m | ETA 3.6m
Epoch 295/500 | Batch 30/202 | Rec 0.000680 | Seg 0.336621 | Elapsed 0.6m | ETA 3.4m
Epoch 295/500 | Batch 40/202 | Rec 0.000708 | Seg 0.334853 | Elapsed 0.8m | ETA 3.3m
Epoch 295/500 | Batch 50/202 | Rec 0.000689 | Seg 0.317884 | Elapsed 1.0m | ETA 3.1m
Epoch 295/500 | Batch 60/202 | Rec 0.000708 | Seg 0.336147 | Elapsed 1.2m | ETA 2.9m
Epoch 295/500 | Batch 70/202 | Rec 0.000699 | Seg 0.325150 | Elapsed 1.4m | ETA 2.7m
Epoch 295/500 | Batch 80/202 | Rec 0.000687 | Seg 0.319814 | Elapsed 1.6m | ETA 2.5m
Epoch 295/500 | Batch 90/202 | Rec 0.000679 | Seg 0.319032 | Elapsed 1.8m | ETA 2.3m
Epoch 295/500 | Batch 100/202 | Rec 0.000680 | Seg 0.321114 | Elapsed 2.0m | ETA 2.1m
Epoch 295/500 | Batch 110/202 | Rec 0.000673 | Seg 0.317323 | Elapsed 2.2m | ETA 1.9m
Epoch 295/500 | Batch 120/202 | Rec 0.000676 | Seg 0.315326 | Elapsed 2.4m | ETA 1.7m
Epoch 295/500 | Batch 130/202 | Rec 0.000671 | Seg 0.312360 | Elapsed 2.6m | ETA 1.5m
Epoch 295/500 | Batch 140/202 | Rec 0.000658 | Seg 0.308513 | Elapsed 2.9m | ETA 1.3m
Epoch 295/500 | Batch 150/202 | Rec 0.000650 | Seg 0.303351 | Elapsed 3.1m | ETA 1.1m
Epoch 295/500 | Batch 160/202 | Rec 0.000654 | Seg 0.301302 | Elapsed 3.3m | ETA 0.9m
Epoch 295/500 | Batch 170/202 | Rec 0.000664 | Seg 0.304221 | Elapsed 3.5m | ETA 0.7m
Epoch 295/500 | Batch 180/202 | Rec 0.000673 | Seg 0.309702 | Elapsed 3.7m | ETA 0.4m
Epoch 295/500 | Batch 190/202 | Rec 0.000664 | Seg 0.304970 | Elapsed 3.9m | ETA 0.2m
Epoch 295/500 | Batch 200/202 | Rec 0.000658 | Seg 0.302742 | Elapsed 4.1m | ETA 0.0m
Epoch 295/500 | Batch 202/202 | Rec 0.000659 | Seg 0.302717 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:43:16,252 - INFO: Rec loss: 0.0006589752064797668
2026-09-24 11:43:16,253 - INFO: Seg loss: 0.3027168497406315
2026-09-24 11:43:16,253 - INFO: λ_rec: 1
2026-09-24 11:43:16,253 - INFO: λ_seg: 0.0001
2026-09-24 11:44:28,899 - INFO: -------------------Epoch: 295------------------------
2026-09-24 11:44:28,903 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.635111  0.973853  0.000143
2026-09-24 11:44:28,910 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995483  0.997686  0.996758  0.998717  0.995686
real potato   0.430630  0.601972  1.000000  0.430630  0.999319
fake potato   0.674835  0.805804  0.975588  0.686426  0.999759
real apple    0.677057  0.807385  0.766431  0.853074  0.998596
fake apple    0.630335  0.773211  0.994158  0.632679  0.998599
real orange   0.939652  0.968837  0.994272  0.944766  0.999920
fake orange   0.933440  0.965525  0.970698  0.960505  0.999804
real grape    0.702679  0.825331  0.915346  0.751516  0.999336
fake grape    0.896129  0.945169  0.934810  0.955864  0.999590
real lemon    0.476582  0.645476  0.489566  0.947286  0.998777
fake lemon    0.847757  0.917557  0.980008  0.862676  0.999672
real avocado  0.825222  0.904193  0.854139  0.960591  0.999811
fake avocado  0.737506  0.848876  0.999654  0.737694  0.999686
real pepper   0.770673  0.870436  0.809638  0.941223  0.998976
fake pepper   0.618855  0.764511  0.954929  0.637475  0.999064
real plant    0.850449  0.919132  0.940194  0.899088  0.998419
fake plant    0.864211  0.927110  0.936962  0.917561  0.999885
real banana   0.388042  0.559079  0.913599  0.402825  0.998573
fake banana   0.720098  0.837226  0.822180  0.852936  0.999390
real onion    0.626668  0.770443  0.749282  0.792940  0.999573
fake onion    0.927365  0.962264  0.997664  0.929383  0.999954
real unknown  0.769960  0.869981  0.817800  0.929389  0.999956
fake unknown  0.220760  0.361638  0.244370  0.695581  0.997931
total         0.718452  0.819515  0.872089  0.813949  0.999142
total(-bg)    0.705859  0.811416  0.866422  0.805550  0.999300
2026-09-24 11:44:29,421 - INFO: Epoch accounting: {'epoch': 295, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11336738, 36360, 63949, 107889, 171086, 69580, 75771, 111510, 229011, 84613, 63586, 46996, 45827, 204722, 98437, 135563, 31904, 74519, 67327, 96030, 40690, 9636, 36528], 'crops_with_class': [202, 20, 25, 35, 36, 20, 27, 24, 38, 38, 28, 16, 15, 49, 27, 20, 27, 24, 30, 32, 22, 11, 18], 'targeted_crops_by_class': [0, 2, 4, 8, 6, 5, 5, 3, 5, 6, 4, 2, 2, 4, 4, 2, 4, 5, 6, 2, 4, 2, 4], 'sampled_scene_counts': [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 3, 1, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 1, 1, 0, 1, 3, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 1, 1, 0, 3, 0, 1, 1, 1, 3, 1, 2, 3, 4, 3, 2, 1, 0, 2, 3, 0, 0, 0, 2, 1, 0, 3, 2, 0, 2, 2, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 2, 3, 3, 2, 1, 2, 1, 3, 2, 2, 2, 1, 1, 1, 1, 3, 0, 0, 2, 1, 3, 1, 2, 2, 0, 0, 3, 1, 3, 1, 1, 1, 0, 2, 0, 2, 0, 1, 1, 1, 0, 2, 0, 0, 2, 0, 1, 1], 'learning_rate': 3.651152221607335e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006589752064797668, 'train_segmentation_loss': 0.3027168497406315, 'val_foreground_miou_all22': 0.7058594374403919, 'val_psnr_ref1': 38.63511138916016, 'elapsed_seconds': 320.5774116516113, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 296/500 | Batch 10/202 | Rec 0.000615 | Seg 0.282853 | Elapsed 0.2m | ETA 3.9m
Epoch 296/500 | Batch 20/202 | Rec 0.000681 | Seg 0.291866 | Elapsed 0.4m | ETA 3.7m
Epoch 296/500 | Batch 30/202 | Rec 0.000718 | Seg 0.309624 | Elapsed 0.6m | ETA 3.5m
Epoch 296/500 | Batch 40/202 | Rec 0.000703 | Seg 0.304688 | Elapsed 0.8m | ETA 3.3m
Epoch 296/500 | Batch 50/202 | Rec 0.000707 | Seg 0.313206 | Elapsed 1.0m | ETA 3.1m
Epoch 296/500 | Batch 60/202 | Rec 0.000686 | Seg 0.309815 | Elapsed 1.2m | ETA 2.9m
Epoch 296/500 | Batch 70/202 | Rec 0.000665 | Seg 0.299883 | Elapsed 1.4m | ETA 2.7m
Epoch 296/500 | Batch 80/202 | Rec 0.000648 | Seg 0.290661 | Elapsed 1.6m | ETA 2.5m
Epoch 296/500 | Batch 90/202 | Rec 0.000651 | Seg 0.302232 | Elapsed 1.8m | ETA 2.3m
Epoch 296/500 | Batch 100/202 | Rec 0.000646 | Seg 0.302234 | Elapsed 2.0m | ETA 2.1m
Epoch 296/500 | Batch 110/202 | Rec 0.000636 | Seg 0.299653 | Elapsed 2.2m | ETA 1.9m
Epoch 296/500 | Batch 120/202 | Rec 0.000639 | Seg 0.299670 | Elapsed 2.4m | ETA 1.7m
Epoch 296/500 | Batch 130/202 | Rec 0.000631 | Seg 0.295310 | Elapsed 2.6m | ETA 1.5m
Epoch 296/500 | Batch 140/202 | Rec 0.000633 | Seg 0.301291 | Elapsed 2.8m | ETA 1.3m
Epoch 296/500 | Batch 150/202 | Rec 0.000644 | Seg 0.303891 | Elapsed 3.0m | ETA 1.1m
Epoch 296/500 | Batch 160/202 | Rec 0.000642 | Seg 0.307079 | Elapsed 3.2m | ETA 0.9m
Epoch 296/500 | Batch 170/202 | Rec 0.000639 | Seg 0.308153 | Elapsed 3.4m | ETA 0.6m
Epoch 296/500 | Batch 180/202 | Rec 0.000635 | Seg 0.307081 | Elapsed 3.7m | ETA 0.4m
Epoch 296/500 | Batch 190/202 | Rec 0.000636 | Seg 0.310247 | Elapsed 3.9m | ETA 0.2m
Epoch 296/500 | Batch 200/202 | Rec 0.000635 | Seg 0.312044 | Elapsed 4.1m | ETA 0.0m
Epoch 296/500 | Batch 202/202 | Rec 0.000635 | Seg 0.311532 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:48:35,823 - INFO: Rec loss: 0.0006351857573643447
2026-09-24 11:48:35,823 - INFO: Seg loss: 0.3115323458493936
2026-09-24 11:48:35,823 - INFO: λ_rec: 1
2026-09-24 11:48:35,823 - INFO: λ_seg: 0.0001
2026-09-24 11:49:49,727 - INFO: -------------------Epoch: 296------------------------
2026-09-24 11:49:49,732 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.849473  0.974263  0.000136
2026-09-24 11:49:49,739 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995335  0.997612  0.996730  0.998596  0.995545
real potato   0.405967  0.577451  0.999686  0.406019  0.999289
fake potato   0.753360  0.859283  0.983005  0.763301  0.999818
real apple    0.724050  0.839891  0.801931  0.881734  0.998841
fake apple    0.668574  0.801324  0.985720  0.675113  0.998736
real orange   0.927970  0.962589  0.996653  0.930871  0.999905
fake orange   0.935115  0.966420  0.961297  0.971698  0.999807
real grape    0.823959  0.903434  0.935441  0.873639  0.999610
fake grape    0.880811  0.936579  0.926961  0.946500  0.999526
real lemon    0.513346  0.678379  0.536005  0.923916  0.998971
fake lemon    0.839038  0.912425  0.991454  0.845150  0.999657
real avocado  0.803335  0.890894  0.833309  0.957143  0.999782
fake avocado  0.777594  0.874834  0.999345  0.777990  0.999734
real pepper   0.804973  0.891900  0.853031  0.934590  0.999172
fake pepper   0.718330  0.836030  0.956924  0.742334  0.999306
real plant    0.860251  0.924826  0.961462  0.890972  0.998552
fake plant    0.809560  0.894709  0.982348  0.821511  0.999846
real banana   0.465312  0.635057  0.872729  0.499185  0.998711
fake banana   0.712517  0.832079  0.810813  0.854595  0.999366
real onion    0.689541  0.816197  0.760537  0.880763  0.999642
fake onion    0.932854  0.965211  0.991083  0.940750  0.999957
real unknown  0.922710  0.959751  1.000000  0.922710  0.999988
fake unknown  0.238147  0.384643  0.262885  0.716769  0.998068
total         0.747941  0.840936  0.886928  0.832863  0.999210
total(-bg)    0.736696  0.833814  0.881937  0.825330  0.999377
2026-09-24 11:49:50,257 - INFO: Epoch accounting: {'epoch': 296, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11244018, 54067, 48542, 135224, 145164, 97480, 82647, 174204, 207317, 84407, 58098, 52002, 39805, 232492, 111990, 98718, 15871, 110211, 69724, 71899, 51169, 9256, 43967], 'crops_with_class': [202, 30, 23, 34, 35, 26, 23, 32, 35, 36, 27, 18, 14, 61, 40, 17, 15, 31, 27, 36, 22, 10, 18], 'targeted_crops_by_class': [0, 3, 4, 4, 4, 6, 5, 6, 5, 3, 4, 5, 2, 8, 2, 5, 3, 7, 5, 3, 8, 4, 2], 'sampled_scene_counts': [0, 1, 4, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 2, 0, 2, 0, 0, 1, 0, 0, 0, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 3, 0, 2, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 3, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 1, 0, 1, 1, 1, 3, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 2, 1, 1, 1, 2, 4, 2, 3, 2, 0, 1, 1, 0, 1, 2, 1, 1, 2, 1, 1, 3, 0, 3, 2, 2, 0, 1, 1, 3, 3, 1, 2, 0, 2, 1, 3, 1, 0, 2, 0, 2, 3, 1, 3, 3, 3, 0, 0, 1, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0, 1, 4, 1, 0, 1, 0, 2, 2, 3, 1, 1, 1], 'learning_rate': 3.621031858629339e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006351857573643447, 'train_segmentation_loss': 0.3115323458493936, 'val_foreground_miou_all22': 0.7366959926178922, 'val_psnr_ref1': 38.84947280883789, 'elapsed_seconds': 320.82812786102295, 'peak_cuda_allocated_gib': 7.513736724853516}

Epoch 297/500 | Batch 10/202 | Rec 0.000575 | Seg 0.270801 | Elapsed 0.2m | ETA 3.7m
Epoch 297/500 | Batch 20/202 | Rec 0.000644 | Seg 0.321497 | Elapsed 0.4m | ETA 3.6m
Epoch 297/500 | Batch 30/202 | Rec 0.000651 | Seg 0.325334 | Elapsed 0.6m | ETA 3.4m
Epoch 297/500 | Batch 40/202 | Rec 0.000585 | Seg 0.295616 | Elapsed 0.8m | ETA 3.2m
Epoch 297/500 | Batch 50/202 | Rec 0.000607 | Seg 0.292706 | Elapsed 1.0m | ETA 3.1m
Epoch 297/500 | Batch 60/202 | Rec 0.000613 | Seg 0.295968 | Elapsed 1.2m | ETA 2.9m
Epoch 297/500 | Batch 70/202 | Rec 0.000615 | Seg 0.298233 | Elapsed 1.4m | ETA 2.7m
Epoch 297/500 | Batch 80/202 | Rec 0.000636 | Seg 0.308263 | Elapsed 1.6m | ETA 2.5m
Epoch 297/500 | Batch 90/202 | Rec 0.000640 | Seg 0.312609 | Elapsed 1.8m | ETA 2.3m
Epoch 297/500 | Batch 100/202 | Rec 0.000628 | Seg 0.312422 | Elapsed 2.0m | ETA 2.1m
Epoch 297/500 | Batch 110/202 | Rec 0.000624 | Seg 0.310045 | Elapsed 2.2m | ETA 1.9m
Epoch 297/500 | Batch 120/202 | Rec 0.000628 | Seg 0.315796 | Elapsed 2.4m | ETA 1.7m
Epoch 297/500 | Batch 130/202 | Rec 0.000628 | Seg 0.319204 | Elapsed 2.6m | ETA 1.5m
Epoch 297/500 | Batch 140/202 | Rec 0.000628 | Seg 0.316992 | Elapsed 2.8m | ETA 1.3m
Epoch 297/500 | Batch 150/202 | Rec 0.000627 | Seg 0.314483 | Elapsed 3.0m | ETA 1.1m
Epoch 297/500 | Batch 160/202 | Rec 0.000640 | Seg 0.319138 | Elapsed 3.2m | ETA 0.9m
Epoch 297/500 | Batch 170/202 | Rec 0.000639 | Seg 0.320038 | Elapsed 3.4m | ETA 0.6m
Epoch 297/500 | Batch 180/202 | Rec 0.000647 | Seg 0.326583 | Elapsed 3.6m | ETA 0.4m
Epoch 297/500 | Batch 190/202 | Rec 0.000650 | Seg 0.325087 | Elapsed 3.8m | ETA 0.2m
Epoch 297/500 | Batch 200/202 | Rec 0.000648 | Seg 0.323065 | Elapsed 4.1m | ETA 0.0m
Epoch 297/500 | Batch 202/202 | Rec 0.000647 | Seg 0.322230 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:53:55,781 - INFO: Rec loss: 0.0006469368535102031
2026-09-24 11:53:55,781 - INFO: Seg loss: 0.3222303328353285
2026-09-24 11:53:55,781 - INFO: λ_rec: 1
2026-09-24 11:53:55,781 - INFO: λ_seg: 0.0001
2026-09-24 11:55:08,880 - INFO: -------------------Epoch: 297------------------------
2026-09-24 11:55:08,884 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.751909  0.973605  0.000139
2026-09-24 11:55:08,892 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995748  0.997820  0.997404  0.998336  0.995942
real potato   0.271869  0.427478  1.000000  0.271869  0.999129
fake potato   0.647488  0.785983  0.992649  0.650607  0.999742
real apple    0.677139  0.807443  0.757449  0.864617  0.998578
fake apple    0.865924  0.928095  0.959329  0.898925  0.999474
real orange   0.936170  0.966983  0.998520  0.937471  0.999916
fake orange   0.957683  0.978334  0.982168  0.974630  0.999877
real grape    0.732114  0.845292  0.942154  0.766572  0.999414
fake grape    0.870000  0.930432  0.911591  0.950171  0.999475
real lemon    0.401003  0.572406  0.433842  0.841210  0.998523
fake lemon    0.851831  0.919938  0.992321  0.857483  0.999684
real avocado  0.698469  0.822420  0.711885  0.973727  0.999609
fake avocado  0.648649  0.786838  0.999607  0.648814  0.999579
real pepper   0.768235  0.868878  0.857236  0.880944  0.999028
fake pepper   0.652024  0.789316  0.991577  0.655656  0.999166
real plant    0.852234  0.920173  0.908819  0.931917  0.998384
fake plant    0.869758  0.930293  0.918692  0.942293  0.999888
real banana   0.331513  0.497909  0.886166  0.346258  0.998431
fake banana   0.684380  0.812569  0.779896  0.848208  0.999280
real onion    0.642656  0.782410  0.724968  0.849856  0.999573
fake onion    0.927743  0.962467  0.999219  0.928416  0.999954
real unknown  0.889982  0.941739  0.934272  0.949427  0.999981
fake unknown  0.352837  0.521583  0.373619  0.863817  0.998665
total         0.718498  0.817252  0.871886  0.818749  0.999187
total(-bg)    0.705895  0.809044  0.866181  0.810586  0.999334
2026-09-24 11:55:09,412 - INFO: Epoch accounting: {'epoch': 297, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11229683, 63301, 73008, 143079, 159110, 71479, 63276, 99592, 123872, 73717, 74236, 64125, 51701, 235363, 128707, 144845, 24035, 121152, 99437, 81152, 54333, 8522, 50547], 'crops_with_class': [202, 35, 32, 35, 38, 27, 21, 22, 25, 36, 27, 20, 21, 57, 41, 19, 20, 40, 34, 39, 25, 10, 18], 'targeted_crops_by_class': [0, 7, 6, 5, 4, 7, 6, 1, 3, 1, 10, 4, 6, 5, 2, 3, 5, 5, 10, 6, 3, 3, 4], 'sampled_scene_counts': [0, 0, 1, 0, 2, 2, 2, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 3, 1, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 2, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 2, 0, 1, 4, 3, 0, 1, 4, 0, 0, 1, 0, 2, 2, 3, 0, 1, 1, 1, 0, 2, 1, 0, 0, 1, 1, 4, 1, 1, 2, 2, 0, 0, 2, 0, 1, 2, 2, 1, 0, 0, 3, 2, 1, 3, 4, 0, 1, 3, 0, 0, 2, 1, 1, 1, 4, 3, 2, 2, 3, 2, 0, 2, 0, 3, 2, 4, 2, 1, 0, 1, 1, 0, 4, 1, 1, 2, 0, 2, 0, 4, 2, 3, 1], 'learning_rate': 3.5909664284309896e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006469368535102031, 'train_segmentation_loss': 0.3222303328353285, 'val_foreground_miou_all22': 0.7058954784309369, 'val_psnr_ref1': 38.75190902709961, 'elapsed_seconds': 319.1467571258545, 'peak_cuda_allocated_gib': 7.505069732666016}

Epoch 298/500 | Batch 10/202 | Rec 0.000489 | Seg 0.241823 | Elapsed 0.2m | ETA 3.8m
Epoch 298/500 | Batch 20/202 | Rec 0.000566 | Seg 0.286802 | Elapsed 0.4m | ETA 3.7m
Epoch 298/500 | Batch 30/202 | Rec 0.000563 | Seg 0.283143 | Elapsed 0.6m | ETA 3.5m
Epoch 298/500 | Batch 40/202 | Rec 0.000586 | Seg 0.285272 | Elapsed 0.8m | ETA 3.3m
Epoch 298/500 | Batch 50/202 | Rec 0.000618 | Seg 0.299990 | Elapsed 1.0m | ETA 3.1m
Epoch 298/500 | Batch 60/202 | Rec 0.000624 | Seg 0.296282 | Elapsed 1.2m | ETA 2.9m
Epoch 298/500 | Batch 70/202 | Rec 0.000613 | Seg 0.289154 | Elapsed 1.4m | ETA 2.6m
Epoch 298/500 | Batch 80/202 | Rec 0.000620 | Seg 0.296678 | Elapsed 1.6m | ETA 2.4m
Epoch 298/500 | Batch 90/202 | Rec 0.000621 | Seg 0.297255 | Elapsed 1.8m | ETA 2.2m
Epoch 298/500 | Batch 100/202 | Rec 0.000611 | Seg 0.289853 | Elapsed 2.0m | ETA 2.0m
Epoch 298/500 | Batch 110/202 | Rec 0.000616 | Seg 0.292974 | Elapsed 2.2m | ETA 1.9m
Epoch 298/500 | Batch 120/202 | Rec 0.000616 | Seg 0.296927 | Elapsed 2.4m | ETA 1.6m
Epoch 298/500 | Batch 130/202 | Rec 0.000622 | Seg 0.300520 | Elapsed 2.6m | ETA 1.5m
Epoch 298/500 | Batch 140/202 | Rec 0.000629 | Seg 0.302800 | Elapsed 2.8m | ETA 1.3m
Epoch 298/500 | Batch 150/202 | Rec 0.000628 | Seg 0.301175 | Elapsed 3.0m | ETA 1.0m
Epoch 298/500 | Batch 160/202 | Rec 0.000634 | Seg 0.305861 | Elapsed 3.2m | ETA 0.8m
Epoch 298/500 | Batch 170/202 | Rec 0.000629 | Seg 0.301803 | Elapsed 3.4m | ETA 0.6m
Epoch 298/500 | Batch 180/202 | Rec 0.000630 | Seg 0.303847 | Elapsed 3.6m | ETA 0.4m
Epoch 298/500 | Batch 190/202 | Rec 0.000636 | Seg 0.302361 | Elapsed 3.8m | ETA 0.2m
Epoch 298/500 | Batch 200/202 | Rec 0.000636 | Seg 0.302371 | Elapsed 4.0m | ETA 0.0m
Epoch 298/500 | Batch 202/202 | Rec 0.000632 | Seg 0.300876 | Elapsed 4.1m | ETA 0.0m

2026-09-24 11:59:14,147 - INFO: Rec loss: 0.0006322779489270789
2026-09-24 11:59:14,147 - INFO: Seg loss: 0.30087563685040075
2026-09-24 11:59:14,147 - INFO: λ_rec: 1
2026-09-24 11:59:14,147 - INFO: λ_seg: 0.0001
2026-09-24 12:00:26,768 - INFO: -------------------Epoch: 298------------------------
2026-09-24 12:00:26,772 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.599545  0.97376  0.000144
2026-09-24 12:00:26,780 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995778  0.997834  0.997165  0.998604  0.995969
real potato   0.708443  0.829295  0.977666  0.720097  0.999645
fake potato   0.962400  0.980790  0.980532  0.981148  0.999972
real apple    0.761616  0.864629  0.874096  0.855462  0.999076
fake apple    0.613863  0.760690  0.988880  0.618130  0.998532
real orange   0.941379  0.969754  0.990226  0.950208  0.999922
fake orange   0.931315  0.964386  0.947355  0.982145  0.999793
real grape    0.781535  0.877323  0.927095  0.832712  0.999514
fake grape    0.886725  0.939912  0.940933  0.938993  0.999556
real lemon    0.503994  0.670162  0.520146  0.941963  0.998911
fake lemon    0.850804  0.919339  0.994712  0.854670  0.999683
real avocado  0.784342  0.879089  0.802304  0.972250  0.999752
fake avocado  0.854867  0.921706  0.999106  0.855522  0.999826
real pepper   0.751822  0.858282  0.800505  0.925163  0.998883
fake pepper   0.595193  0.746186  0.963819  0.608796  0.999013
real plant    0.857702  0.923351  0.948862  0.899271  0.998508
fake plant    0.891980  0.942857  0.945451  0.940376  0.999909
real banana   0.464267  0.634083  0.884943  0.494092  0.998719
fake banana   0.756690  0.861445  0.864517  0.858494  0.999492
real onion    0.648170  0.786484  0.676646  0.939031  0.999539
fake onion    0.948268  0.973397  0.994700  0.953083  0.999967
real unknown  0.657087  0.793014  0.675621  0.959924  0.999920
fake unknown  0.253006  0.403799  0.278890  0.731619  0.998180
total         0.756576  0.847731  0.868442  0.861380  0.999230
total(-bg)    0.745703  0.840908  0.862591  0.855143  0.999378
2026-09-24 12:00:27,306 - INFO: Epoch accounting: {'epoch': 298, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11354957, 36106, 73392, 86894, 149733, 113771, 85523, 133705, 165120, 71769, 55943, 48690, 25312, 195297, 99618, 127692, 24287, 91358, 93239, 89959, 54025, 12388, 49494], 'crops_with_class': [202, 24, 29, 24, 38, 32, 32, 27, 34, 34, 25, 17, 11, 48, 32, 19, 23, 28, 36, 36, 26, 16, 21], 'targeted_crops_by_class': [0, 1, 4, 3, 8, 6, 5, 4, 1, 4, 7, 5, 4, 7, 6, 3, 3, 6, 3, 7, 6, 8, 9], 'sampled_scene_counts': [0, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 2, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 0, 1, 1, 2, 2, 1, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0, 1, 2, 1, 2, 2, 2, 1, 0, 1, 0, 3, 0, 1, 2, 0, 0, 3, 0, 2, 0, 2, 1, 3, 1, 0, 2, 2, 6, 2, 0, 0, 1, 0, 3, 2, 0, 1, 3, 1, 0, 1, 3, 3, 1, 1, 2, 2, 1, 2, 3, 1, 0, 1, 3, 2, 0, 0, 1, 2, 2, 0, 1, 2, 1, 3, 2, 2, 0, 3, 3, 2, 0, 1, 2, 1, 0, 1, 2, 3, 0, 1, 0, 2, 1], 'learning_rate': 3.56095711794399e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006322779489270789, 'train_segmentation_loss': 0.30087563685040075, 'val_foreground_miou_all22': 0.745703121316004, 'val_psnr_ref1': 38.59954467773437, 'elapsed_seconds': 317.8857510089874, 'peak_cuda_allocated_gib': 7.507755279541016}

Epoch 299/500 | Batch 10/202 | Rec 0.000628 | Seg 0.237262 | Elapsed 0.2m | ETA 4.0m
Epoch 299/500 | Batch 20/202 | Rec 0.000753 | Seg 0.301326 | Elapsed 0.4m | ETA 3.7m
Epoch 299/500 | Batch 30/202 | Rec 0.000733 | Seg 0.298368 | Elapsed 0.6m | ETA 3.5m
Epoch 299/500 | Batch 40/202 | Rec 0.000700 | Seg 0.286899 | Elapsed 0.8m | ETA 3.3m
Epoch 299/500 | Batch 50/202 | Rec 0.000679 | Seg 0.293832 | Elapsed 1.0m | ETA 3.1m
Epoch 299/500 | Batch 60/202 | Rec 0.000680 | Seg 0.294571 | Elapsed 1.2m | ETA 2.9m
Epoch 299/500 | Batch 70/202 | Rec 0.000674 | Seg 0.291049 | Elapsed 1.4m | ETA 2.7m
Epoch 299/500 | Batch 80/202 | Rec 0.000678 | Seg 0.302313 | Elapsed 1.6m | ETA 2.5m
Epoch 299/500 | Batch 90/202 | Rec 0.000680 | Seg 0.309802 | Elapsed 1.8m | ETA 2.3m
Epoch 299/500 | Batch 100/202 | Rec 0.000688 | Seg 0.318935 | Elapsed 2.0m | ETA 2.1m
Epoch 299/500 | Batch 110/202 | Rec 0.000698 | Seg 0.311392 | Elapsed 2.2m | ETA 1.9m
Epoch 299/500 | Batch 120/202 | Rec 0.000692 | Seg 0.317319 | Elapsed 2.4m | ETA 1.7m
Epoch 299/500 | Batch 130/202 | Rec 0.000695 | Seg 0.318970 | Elapsed 2.6m | ETA 1.5m
Epoch 299/500 | Batch 140/202 | Rec 0.000680 | Seg 0.314448 | Elapsed 2.8m | ETA 1.3m
Epoch 299/500 | Batch 150/202 | Rec 0.000679 | Seg 0.314707 | Elapsed 3.1m | ETA 1.1m
Epoch 299/500 | Batch 160/202 | Rec 0.000688 | Seg 0.316390 | Elapsed 3.3m | ETA 0.9m
Epoch 299/500 | Batch 170/202 | Rec 0.000692 | Seg 0.318382 | Elapsed 3.5m | ETA 0.7m
Epoch 299/500 | Batch 180/202 | Rec 0.000692 | Seg 0.313839 | Elapsed 3.7m | ETA 0.4m
Epoch 299/500 | Batch 190/202 | Rec 0.000685 | Seg 0.310668 | Elapsed 3.9m | ETA 0.2m
Epoch 299/500 | Batch 200/202 | Rec 0.000691 | Seg 0.309587 | Elapsed 4.1m | ETA 0.0m
Epoch 299/500 | Batch 202/202 | Rec 0.000696 | Seg 0.311614 | Elapsed 4.1m | ETA 0.0m

2026-09-24 12:04:34,221 - INFO: Rec loss: 0.0006961241951742495
2026-09-24 12:04:34,221 - INFO: Seg loss: 0.311614048031002
2026-09-24 12:04:34,221 - INFO: λ_rec: 1
2026-09-24 12:04:34,221 - INFO: λ_seg: 0.0001
2026-09-24 12:05:45,594 - INFO: -------------------Epoch: 299------------------------
2026-09-24 12:05:45,598 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.441661  0.973393  0.000148
2026-09-24 12:05:45,604 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995473  0.997681  0.997150  0.998314  0.995678
real potato   0.771290  0.870830  0.999670  0.771487  0.999726
fake potato   0.764788  0.866670  0.939564  0.804357  0.999820
real apple    0.714387  0.833352  0.862969  0.805794  0.998889
fake apple    0.609710  0.757493  0.992340  0.612593  0.998519
real orange   0.901864  0.948350  0.992907  0.907712  0.999870
fake orange   0.923618  0.960242  0.961575  0.959013  0.999773
real grape    0.811039  0.895612  0.956731  0.841921  0.999590
fake grape    0.852977  0.920606  0.881084  0.963948  0.999385
real lemon    0.369091  0.539132  0.406129  0.801870  0.998389
fake lemon    0.850330  0.919062  0.995042  0.853949  0.999682
real avocado  0.813128  0.896884  0.844748  0.955993  0.999796
fake avocado  0.642830  0.782541  0.999405  0.643076  0.999572
real pepper   0.840597  0.913346  0.890642  0.937344  0.999350
fake pepper   0.801591  0.889820  0.947635  0.838743  0.999505
real plant    0.864140  0.927069  0.951959  0.903542  0.998579
fake plant    0.796528  0.886691  0.838286  0.941143  0.999809
real banana   0.351459  0.520075  0.811402  0.382724  0.998413
fake banana   0.626952  0.770658  0.692374  0.869028  0.999049
real onion    0.630323  0.773199  0.779150  0.767438  0.999593
fake onion    0.926678  0.961894  0.986775  0.938331  0.999953
real unknown  0.911259  0.953520  1.000000  0.911259  0.999986
fake unknown  0.224823  0.367073  0.244568  0.735784  0.997862
total         0.738908  0.832687  0.868352  0.832407  0.999165
total(-bg)    0.727246  0.825187  0.862498  0.824866  0.999323
2026-09-24 12:05:46,121 - INFO: Epoch accounting: {'epoch': 299, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11272016, 36965, 57046, 143958, 142748, 92493, 73374, 165769, 194556, 74935, 63855, 39856, 29560, 186177, 142473, 205863, 19891, 84655, 63406, 52089, 45347, 11106, 40134], 'crops_with_class': [202, 19, 24, 32, 34, 25, 27, 32, 33, 34, 29, 13, 15, 43, 32, 24, 21, 22, 24, 28, 20, 12, 19], 'targeted_crops_by_class': [0, 3, 4, 5, 7, 2, 5, 2, 3, 2, 6, 2, 3, 4, 8, 9, 6, 4, 1, 5, 3, 5, 6], 'sampled_scene_counts': [1, 2, 4, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 2, 2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 0, 1, 0, 0, 1, 0, 4, 2, 2, 2, 1, 0, 2, 1, 1, 0, 1, 2, 0, 0, 3, 2, 1, 1, 2, 2, 3, 2, 2, 1, 1, 0, 3, 0, 3, 0, 0, 2, 2, 0, 2, 1, 0, 1, 0, 4, 2, 3, 1, 0, 1, 1, 2, 1, 3, 0, 0, 0, 1, 1, 2, 1, 5, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 1, 4, 1], 'learning_rate': 3.5310051118845335e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006961241951742495, 'train_segmentation_loss': 0.311614048031002, 'val_foreground_miou_all22': 0.7272455281246917, 'val_psnr_ref1': 38.44166061401367, 'elapsed_seconds': 318.8060884475708, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 300/500 | Batch 10/202 | Rec 0.000644 | Seg 0.317619 | Elapsed 0.2m | ETA 3.9m
Epoch 300/500 | Batch 20/202 | Rec 0.000718 | Seg 0.346424 | Elapsed 0.4m | ETA 3.8m
Epoch 300/500 | Batch 30/202 | Rec 0.000689 | Seg 0.322441 | Elapsed 0.6m | ETA 3.5m
Epoch 300/500 | Batch 40/202 | Rec 0.000692 | Seg 0.323020 | Elapsed 0.8m | ETA 3.3m
Epoch 300/500 | Batch 50/202 | Rec 0.000671 | Seg 0.315702 | Elapsed 1.0m | ETA 3.1m
Epoch 300/500 | Batch 60/202 | Rec 0.000667 | Seg 0.313326 | Elapsed 1.2m | ETA 2.9m
Epoch 300/500 | Batch 70/202 | Rec 0.000660 | Seg 0.315081 | Elapsed 1.4m | ETA 2.7m
Epoch 300/500 | Batch 80/202 | Rec 0.000654 | Seg 0.313135 | Elapsed 1.6m | ETA 2.5m
Epoch 300/500 | Batch 90/202 | Rec 0.000657 | Seg 0.313830 | Elapsed 1.8m | ETA 2.3m
Epoch 300/500 | Batch 100/202 | Rec 0.000658 | Seg 0.316928 | Elapsed 2.0m | ETA 2.1m
Epoch 300/500 | Batch 110/202 | Rec 0.000659 | Seg 0.316613 | Elapsed 2.2m | ETA 1.9m
Epoch 300/500 | Batch 120/202 | Rec 0.000652 | Seg 0.315314 | Elapsed 2.4m | ETA 1.7m
Epoch 300/500 | Batch 130/202 | Rec 0.000650 | Seg 0.320209 | Elapsed 2.6m | ETA 1.5m
Epoch 300/500 | Batch 140/202 | Rec 0.000649 | Seg 0.319602 | Elapsed 2.8m | ETA 1.3m
Epoch 300/500 | Batch 150/202 | Rec 0.000638 | Seg 0.313822 | Elapsed 3.1m | ETA 1.1m
Epoch 300/500 | Batch 160/202 | Rec 0.000638 | Seg 0.312504 | Elapsed 3.3m | ETA 0.9m
Epoch 300/500 | Batch 170/202 | Rec 0.000639 | Seg 0.310946 | Elapsed 3.5m | ETA 0.7m
Epoch 300/500 | Batch 180/202 | Rec 0.000636 | Seg 0.312653 | Elapsed 3.7m | ETA 0.4m
Epoch 300/500 | Batch 190/202 | Rec 0.000638 | Seg 0.314111 | Elapsed 3.9m | ETA 0.2m
Epoch 300/500 | Batch 200/202 | Rec 0.000641 | Seg 0.316837 | Elapsed 4.1m | ETA 0.0m
Epoch 300/500 | Batch 202/202 | Rec 0.000640 | Seg 0.316862 | Elapsed 4.1m | ETA 0.0m

2026-09-24 12:09:52,567 - INFO: Rec loss: 0.0006404533454373774
2026-09-24 12:09:52,567 - INFO: Seg loss: 0.31686242935386033
2026-09-24 12:09:52,567 - INFO: λ_rec: 1
2026-09-24 12:09:52,567 - INFO: λ_seg: 0.0001
2026-09-24 12:11:06,723 - INFO: -------------------Epoch: 300------------------------
2026-09-24 12:11:06,727 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.435641  0.973674  0.00015
2026-09-24 12:11:06,734 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995682  0.997786  0.996991  0.998683  0.995877
real potato   0.915037  0.955584  0.975432  0.936623  0.999896
fake potato   0.956602  0.977770  0.976798  0.978844  0.999968
real apple    0.797010  0.886991  0.982167  0.808713  0.999289
fake apple    0.640936  0.781136  0.984874  0.647308  0.998631
real orange   0.650035  0.787856  0.992610  0.653196  0.999537
fake orange   0.835066  0.910071  0.846041  0.984703  0.999443
real grape    0.707049  0.828338  0.928571  0.747716  0.999353
fake grape    0.892602  0.943204  0.914414  0.973972  0.999566
real lemon    0.719943  0.837121  0.769281  0.918203  0.999580
fake lemon    0.850007  0.918873  0.995874  0.853011  0.999682
real avocado  0.907685  0.951559  0.939651  0.963875  0.999909
fake avocado  0.714049  0.833124  0.999643  0.714231  0.999658
real pepper   0.874579  0.933044  0.914321  0.952653  0.999500
fake pepper   0.827544  0.905585  0.958137  0.858588  0.999574
real plant    0.838203  0.911931  0.943197  0.882765  0.998296
fake plant    0.820063  0.901087  0.905850  0.896472  0.999843
real banana   0.727698  0.842341  0.927440  0.771628  0.999351
fake banana   0.758830  0.862830  0.863202  0.862558  0.999496
real onion    0.649983  0.787818  0.664616  0.967235  0.999529
fake onion    0.946209  0.972311  0.979156  0.965659  0.999965
real unknown  0.691034  0.817243  0.713675  0.956107  0.999932
fake unknown  0.241760  0.389344  0.263546  0.745201  0.998031
total         0.780765  0.866650  0.888499  0.871215  0.999300
total(-bg)    0.770996  0.860689  0.883568  0.865421  0.999456
2026-09-24 12:11:07,247 - INFO: Epoch accounting: {'epoch': 300, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11251832, 64650, 66797, 107928, 111466, 38049, 91252, 155186, 187441, 83284, 79644, 44925, 55124, 253064, 112424, 142329, 27143, 95406, 69697, 92596, 49549, 8909, 49577], 'crops_with_class': [202, 33, 31, 29, 29, 20, 30, 30, 29, 35, 35, 15, 20, 60, 32, 20, 25, 26, 30, 37, 24, 11, 23], 'targeted_crops_by_class': [0, 7, 7, 4, 3, 3, 5, 2, 5, 3, 6, 1, 10, 5, 4, 3, 6, 5, 3, 3, 4, 2, 5], 'sampled_scene_counts': [1, 0, 1, 0, 1, 0, 0, 1, 2, 2, 1, 1, 1, 2, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 3, 0, 1, 0, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 2, 3, 1, 1, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 1, 2, 0, 2, 2, 3, 2, 1, 1, 1, 1, 0, 1, 2, 0, 2, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 1, 2, 1, 0, 0, 0, 3, 4, 4, 3, 1, 3, 0, 3, 1, 2, 2, 1, 1, 0, 2, 1, 2, 1, 1, 1, 2, 0, 1, 5, 1, 1, 0, 1, 1, 1, 0, 2, 3, 2, 1, 1, 3, 0, 2, 2, 2, 2], 'learning_rate': 3.501111592706536e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006404533454373774, 'train_segmentation_loss': 0.31686242935386033, 'val_foreground_miou_all22': 0.7709964628147666, 'val_psnr_ref1': 38.43564086914063, 'elapsed_seconds': 321.1188271045685, 'peak_cuda_allocated_gib': 7.511508941650391}

Stopped after epoch 300; scheduler horizon remains 500
Saved epoch: 300 | block target: 300 | Missing checkpoint files: []
Download: /kaggle/working/balanced250_to_epoch300_20260924_074129_epoch300.zip

/kaggle/working/balanced250_to_epoch300_20260924_074129_epoch300.zip

Epoch300 completed. Download the full backup before stopping the session.

In [4]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((CONT250_RUN / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(251,301)), 'Not all50 new epochs completed.'
for start,end in [(251,275),(276,300)]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] <= end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:', json.dumps(records[-1], indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

Epochs251-275: mean mIoU=73.08%, std=2.87 points
Epochs276-300: mean mIoU=74.08%, std=3.15 points
Final: {
  "epoch": 300,
  "scheduler_horizon": 500,
  "lambda_rec": 1,
  "lambda_seg": 0.0001,
  "sampling_policy": "balanced50_v1",
  "class_pixels_seen": [
    11251832,
    64650,
    66797,
    107928,
    111466,
    38049,
    91252,
    155186,
    187441,
    83284,
    79644,
    44925,
    55124,
    253064,
    112424,
    142329,
    27143,
    95406,
    69697,
    92596,
    49549,
    8909,
    49577
  ],
  "crops_with_class": [
    202,
    33,
    31,
    29,
    29,
    20,
    30,
    30,
    29,
    35,
    35,
    15,
    20,
    60,
    32,
    20,
    25,
    26,
    30,
    37,
    24,
    11,
    23
  ],
  "targeted_crops_by_class": [
    0,
    7,
    7,
    4,
    3,
    3,
    5,
    2,
    5,
    3,
    6,
    1,
    10,
    5,
    4,
    3,
    6,
    5,
    3,
    3,
    4,
    2,
    5
  ],
  "sampled_scene_counts": [
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    2,
    2,
    1,
    1,
    1,
    2,
    1,
    2,
    0,
    0,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    2,
    1,
    0,
    0,
    1,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    2,
    0,
    1,
    1,
    1,
    1,
    0,
    0,
    1,
    0,
    0,
    0,
    3,
    0,
    1,
    0,
    0,
    1,
    0,
    0,
    1,
    1,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    2,
    2,
    3,
    1,
    1,
    1,
    0,
    0,
    0,
    2,
    0,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    0,
    0,
    1,
    1,
    0,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    2,
    1,
    1,
    2,
    0,
    2,
    2,
    3,
    2,
    1,
    1,
    1,
    1,
    0,
    1,
    2,
    0,
    2,
    1,
    1,
    1,
    2,
    1,
    1,
    2,
    0,
    1,
    1,
    1,
    0,
    2,
    1,
    1,
    1,
    2,
    1,
    0,
    0,
    0,
    3,
    4,
    4,
    3,
    1,
    3,
    0,
    3,
    1,
    2,
    2,
    1,
    1,
    0,
    2,
    1,
    2,
    1,
    1,
    1,
    2,
    0,
    1,
    5,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    2,
    3,
    2,
    1,
    1,
    3,
    0,
    2,
    2,
    2,
    2
  ],
  "learning_rate": 3.501111592706536e-05,
  "attempted_updates": 202,
  "optimizer_updates": 202,
  "amp_skipped_updates": 0,
  "train_reconstruction_loss": 0.0006404533454373774,
  "train_segmentation_loss": 0.31686242935386033,
  "val_foreground_miou_all22": 0.7709964628147666,
  "val_psnr_ref1": 38.43564086914063,
  "elapsed_seconds": 321.1188271045685,
  "peak_cuda_allocated_gib": 7.511508941650391
}
New successful updates: 10096
New AMP skips: 4

In [1]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced250_to_epoch300_20260924_074129'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced300')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced250_to_epoch300_20260924_074129_epoch300.zip or its extracted folder.'
CHECKPOINT = refs[0]
assert hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest() == '3336458842278753855d7e0daabd329ffa0e9669ca8b21c4fc4c5126daa566da', 'Wrong epoch300 checkpoint.'
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch300 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 300
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 300
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch300 run.')

Balanced epoch300 reference: /kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129
PASS:22-class support, aligned crops/flips, deterministic replay, no RNG consumed by index building, baseline crop branch unchanged.
Saved next-epoch LR: 3.4712777405549456e-05
Preserved best metrics: {'iou': 0.7862424401936461, 'psnr': 38.94295196533203}
{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.
Training source hashes match the epoch300 run.

In [3]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT300_RUN' not in globals():
    CONT300_RUN = Path('/kaggle/working') / ('balanced300_to_epoch400_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT300_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT300_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 300, 'target_epoch': 400, 'backup_epochs': [350, 400],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Two sequential blocks from300 through400, with an intermediate backup at350.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT300_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT300_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT300_RUN.parent / (CONT300_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT300_RUN.parent, base_dir=CONT300_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT300_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT300_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target in (350, 400)
    last = CONT300_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT300_RUN.parent) + '/', '--name', CONT300_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT300_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT300_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print(f'Epoch{target} completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT300_RUN)

Continuation folder: /kaggle/working/balanced300_to_epoch400_20260925_173543

In [4]:
continue_to(350)
continue_to(400)

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced300_to_epoch400_20260925_173543', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=350, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-25 17:36:31,054 - INFO: Resuming after epoch 300

Epoch 301/500 | Batch 10/202 | Rec 0.000710 | Seg 0.266789 | Elapsed 0.6m | ETA 11.4m
Epoch 301/500 | Batch 20/202 | Rec 0.000641 | Seg 0.282812 | Elapsed 0.9m | ETA 8.2m
Epoch 301/500 | Batch 30/202 | Rec 0.000673 | Seg 0.293087 | Elapsed 1.2m | ETA 7.1m
Epoch 301/500 | Batch 40/202 | Rec 0.000637 | Seg 0.273699 | Elapsed 1.5m | ETA 6.2m
Epoch 301/500 | Batch 50/202 | Rec 0.000672 | Seg 0.283585 | Elapsed 1.8m | ETA 5.5m
Epoch 301/500 | Batch 60/202 | Rec 0.000662 | Seg 0.284398 | Elapsed 2.1m | ETA 5.0m
Epoch 301/500 | Batch 70/202 | Rec 0.000669 | Seg 0.301421 | Elapsed 2.4m | ETA 4.6m
Epoch 301/500 | Batch 80/202 | Rec 0.000647 | Seg 0.294825 | Elapsed 2.7m | ETA 4.2m
Epoch 301/500 | Batch 90/202 | Rec 0.000636 | Seg 0.289730 | Elapsed 3.1m | ETA 3.8m
Epoch 301/500 | Batch 100/202 | Rec 0.000634 | Seg 0.291227 | Elapsed 3.4m | ETA 3.4m
Epoch 301/500 | Batch 110/202 | Rec 0.000644 | Seg 0.294553 | Elapsed 3.7m | ETA 3.1m
Epoch 301/500 | Batch 120/202 | Rec 0.000645 | Seg 0.300453 | Elapsed 4.0m | ETA 2.7m
Epoch 301/500 | Batch 130/202 | Rec 0.000645 | Seg 0.298549 | Elapsed 4.3m | ETA 2.4m
Epoch 301/500 | Batch 140/202 | Rec 0.000641 | Seg 0.300931 | Elapsed 4.6m | ETA 2.0m
Epoch 301/500 | Batch 150/202 | Rec 0.000641 | Seg 0.303670 | Elapsed 4.8m | ETA 1.7m
Epoch 301/500 | Batch 160/202 | Rec 0.000651 | Seg 0.302661 | Elapsed 5.1m | ETA 1.3m
Epoch 301/500 | Batch 170/202 | Rec 0.000656 | Seg 0.304632 | Elapsed 5.4m | ETA 1.0m
Epoch 301/500 | Batch 180/202 | Rec 0.000661 | Seg 0.308983 | Elapsed 5.6m | ETA 0.7m
Epoch 301/500 | Batch 190/202 | Rec 0.000662 | Seg 0.309277 | Elapsed 5.9m | ETA 0.4m
Epoch 301/500 | Batch 200/202 | Rec 0.000659 | Seg 0.308232 | Elapsed 6.1m | ETA 0.1m
Epoch 301/500 | Batch 202/202 | Rec 0.000661 | Seg 0.308859 | Elapsed 6.1m | ETA 0.0m

2026-09-25 17:42:39,716 - INFO: Rec loss: 0.000661333457444043
2026-09-25 17:42:39,716 - INFO: Seg loss: 0.3088591570716978
2026-09-25 17:42:39,716 - INFO: λ_rec: 1
2026-09-25 17:42:39,716 - INFO: λ_seg: 0.0001
2026-09-25 17:44:09,452 - INFO: -------------------Epoch: 301------------------------
2026-09-25 17:44:09,465 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.341392  0.973263  0.000152
2026-09-25 17:44:09,472 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995773  0.997832  0.997104  0.998661  0.995964
real potato   0.690521  0.816884  0.978126  0.701352  0.999624
fake potato   0.853659  0.921003  0.966406  0.879765  0.999890
real apple    0.769005  0.869371  0.893144  0.846926  0.999122
fake apple    0.590545  0.742522  0.986998  0.595175  0.998442
real orange   0.959367  0.979212  0.996762  0.962367  0.999946
fake orange   0.958077  0.978540  0.977861  0.979320  0.999877
real grape    0.704262  0.826423  0.957547  0.726960  0.999363
fake grape    0.898868  0.946691  0.928186  0.966052  0.999598
real lemon    0.560417  0.718243  0.594122  0.908076  0.999163
fake lemon    0.849849  0.918781  0.998224  0.851136  0.999682
real avocado  0.883700  0.938210  0.920259  0.956979  0.999883
fake avocado  0.489671  0.657378  1.000000  0.489671  0.999389
real pepper   0.890087  0.941798  0.937180  0.946563  0.999572
fake pepper   0.878380  0.935203  0.970469  0.902503  0.999702
real plant    0.848893  0.918221  0.928160  0.908592  0.998382
fake plant    0.722744  0.839012  0.774712  0.915069  0.999721
real banana   0.543482  0.704182  0.916894  0.571642  0.998921
fake banana   0.740057  0.850562  0.863516  0.838089  0.999458
real onion    0.662702  0.797090  0.691401  0.941057  0.999567
fake onion    0.900216  0.947438  0.991022  0.907618  0.999937
real unknown  0.882353  0.937450  0.944767  0.930343  0.999980
fake unknown  0.218227  0.358235  0.230813  0.800072  0.997585
total         0.760472  0.849577  0.888855  0.848869  0.999251
total(-bg)    0.749776  0.842839  0.883935  0.842060  0.999400
2026-09-25 17:44:09,938 - INFO: Epoch accounting: {'epoch': 301, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11244366, 37107, 66609, 151959, 142802, 88852, 74268, 161375, 242138, 77803, 92843, 19413, 18921, 239670, 74869, 147304, 22912, 92214, 73820, 64013, 56592, 7326, 41096], 'crops_with_class': [202, 26, 28, 39, 37, 31, 23, 29, 43, 35, 37, 9, 7, 58, 22, 20, 22, 26, 27, 31, 24, 8, 21], 'targeted_crops_by_class': [0, 7, 4, 5, 4, 7, 5, 5, 6, 5, 7, 2, 0, 6, 2, 7, 2, 5, 5, 4, 2, 4, 4], 'sampled_scene_counts': [1, 2, 1, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 1, 0, 1, 1, 2, 2, 0, 1, 0, 0, 0, 0, 1, 2, 0, 3, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 2, 2, 1, 1, 0, 2, 4, 1, 1, 4, 2, 1, 3, 0, 0, 3, 1, 1, 2, 1, 2, 0, 0, 2, 2, 2, 1, 1, 3, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 3, 0, 0, 3, 0, 1, 1, 1, 0, 2, 0, 1, 2, 4, 0, 1, 0, 2, 2, 1, 2, 3, 2, 3, 2, 1, 2, 0, 0, 2, 1, 1, 0, 1, 2, 3, 1, 0, 0], 'learning_rate': 3.4712777405549456e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000661333457444043, 'train_segmentation_loss': 0.3088591570716978, 'val_foreground_miou_all22': 0.7497764091781793, 'val_psnr_ref1': 38.3413916015625, 'elapsed_seconds': 458.87647700309753, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 302/500 | Batch 10/202 | Rec 0.000668 | Seg 0.326140 | Elapsed 0.2m | ETA 4.2m
Epoch 302/500 | Batch 20/202 | Rec 0.000638 | Seg 0.298570 | Elapsed 0.5m | ETA 4.1m
Epoch 302/500 | Batch 30/202 | Rec 0.000644 | Seg 0.306833 | Elapsed 0.7m | ETA 3.9m
Epoch 302/500 | Batch 40/202 | Rec 0.000645 | Seg 0.313721 | Elapsed 0.9m | ETA 3.8m
Epoch 302/500 | Batch 50/202 | Rec 0.000621 | Seg 0.300659 | Elapsed 1.2m | ETA 3.5m
Epoch 302/500 | Batch 60/202 | Rec 0.000594 | Seg 0.294091 | Elapsed 1.4m | ETA 3.2m
Epoch 302/500 | Batch 70/202 | Rec 0.000582 | Seg 0.288184 | Elapsed 1.6m | ETA 3.0m
Epoch 302/500 | Batch 80/202 | Rec 0.000592 | Seg 0.291550 | Elapsed 1.8m | ETA 2.8m
Epoch 302/500 | Batch 90/202 | Rec 0.000587 | Seg 0.295114 | Elapsed 2.0m | ETA 2.5m
Epoch 302/500 | Batch 100/202 | Rec 0.000599 | Seg 0.290311 | Elapsed 2.3m | ETA 2.3m
Epoch 302/500 | Batch 110/202 | Rec 0.000613 | Seg 0.288315 | Elapsed 2.5m | ETA 2.1m
Epoch 302/500 | Batch 120/202 | Rec 0.000610 | Seg 0.290589 | Elapsed 2.7m | ETA 1.9m
Epoch 302/500 | Batch 130/202 | Rec 0.000609 | Seg 0.291710 | Elapsed 2.9m | ETA 1.6m
Epoch 302/500 | Batch 140/202 | Rec 0.000598 | Seg 0.290796 | Elapsed 3.2m | ETA 1.4m
Epoch 302/500 | Batch 150/202 | Rec 0.000608 | Seg 0.294771 | Elapsed 3.4m | ETA 1.2m
Epoch 302/500 | Batch 160/202 | Rec 0.000614 | Seg 0.299085 | Elapsed 3.6m | ETA 0.9m
Epoch 302/500 | Batch 170/202 | Rec 0.000615 | Seg 0.298985 | Elapsed 3.8m | ETA 0.7m
Epoch 302/500 | Batch 180/202 | Rec 0.000622 | Seg 0.300216 | Elapsed 4.0m | ETA 0.5m
Epoch 302/500 | Batch 190/202 | Rec 0.000622 | Seg 0.300012 | Elapsed 4.2m | ETA 0.3m
Epoch 302/500 | Batch 200/202 | Rec 0.000621 | Seg 0.301603 | Elapsed 4.4m | ETA 0.0m
Epoch 302/500 | Batch 202/202 | Rec 0.000624 | Seg 0.303904 | Elapsed 4.5m | ETA 0.0m

2026-09-25 17:48:39,222 - INFO: Rec loss: 0.0006241537019665731
2026-09-25 17:48:39,222 - INFO: Seg loss: 0.3039038558260049
2026-09-25 17:48:39,222 - INFO: λ_rec: 1
2026-09-25 17:48:39,222 - INFO: λ_seg: 0.0001
2026-09-25 17:49:56,788 - INFO: -------------------Epoch: 302------------------------
2026-09-25 17:49:56,791 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.580244  0.973684  0.000144
2026-09-25 17:49:56,798 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995202  0.997545  0.996292  0.998901  0.995415
real potato   0.560380  0.718214  0.987068  0.564524  0.999470
fake potato   0.767140  0.868178  0.960386  0.792208  0.999825
real apple    0.732972  0.845863  0.853802  0.838169  0.998947
fake apple    0.671818  0.803649  0.961502  0.690390  0.998727
real orange   0.844601  0.915705  0.995648  0.847730  0.999794
fake orange   0.905055  0.950112  0.922926  0.979053  0.999706
real grape    0.663562  0.797712  0.950571  0.687276  0.999272
fake grape    0.886930  0.940028  0.929762  0.950625  0.999552
real lemon    0.487403  0.655326  0.555636  0.798754  0.999013
fake lemon    0.845008  0.915944  0.991845  0.850920  0.999670
real avocado  0.839658  0.912791  0.864825  0.966502  0.999828
fake avocado  0.772055  0.871318  0.999670  0.772252  0.999727
real pepper   0.812459  0.896477  0.863687  0.931962  0.999213
fake pepper   0.718116  0.835885  0.950865  0.745791  0.999302
real plant    0.816711  0.899060  0.937084  0.864093  0.998060
fake plant    0.773266  0.872088  0.975569  0.788535  0.999816
real banana   0.511966  0.677173  0.915135  0.537485  0.998849
fake banana   0.662407  0.796875  0.745788  0.855591  0.999198
real onion    0.684767  0.812843  0.709235  0.952035  0.999604
fake onion    0.934808  0.966256  0.972100  0.960580  0.999958
real unknown  0.738346  0.849431  0.776899  0.937023  0.999947
fake unknown  0.246268  0.395167  0.278366  0.681094  0.998244
total         0.733517  0.834506  0.873681  0.825717  0.999180
total(-bg)    0.721623  0.827095  0.868108  0.817845  0.999351
2026-09-25 17:49:57,337 - INFO: Epoch accounting: {'epoch': 302, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11297882, 55033, 50666, 126573, 135341, 77694, 83038, 166932, 195303, 83722, 74063, 74934, 45227, 227600, 123314, 80959, 14225, 71221, 71403, 85648, 51085, 8759, 37650], 'crops_with_class': [202, 34, 26, 35, 35, 24, 28, 32, 36, 38, 27, 25, 19, 56, 35, 13, 15, 21, 29, 34, 24, 9, 18], 'targeted_crops_by_class': [0, 8, 3, 4, 5, 5, 4, 5, 5, 5, 7, 9, 5, 6, 6, 2, 1, 5, 2, 5, 4, 6, 2], 'sampled_scene_counts': [1, 1, 1, 0, 0, 0, 2, 0, 0, 2, 1, 2, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 0, 1, 1, 2, 0, 2, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 3, 0, 1, 0, 3, 1, 2, 2, 0, 1, 1, 2, 3, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 2, 0, 0, 5, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 0, 2, 3, 1, 2, 1, 1, 2, 0, 1, 1, 1, 1, 3, 1, 3, 1, 2, 1, 1, 2, 1, 2, 1, 3, 0, 3, 1, 4, 0, 1, 2, 2, 2, 1, 1, 0, 1, 2, 1, 1, 0, 2, 4, 1, 2, 0, 1, 0, 2, 2, 2, 0, 2, 0, 0], 'learning_rate': 3.441504733219163e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0006241537019665731, 'train_segmentation_loss': 0.3039038558260049, 'val_foreground_miou_all22': 0.7216225500955882, 'val_psnr_ref1': 38.580244140625, 'elapsed_seconds': 347.39115834236145, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 303/500 | Batch 10/202 | Rec 0.000632 | Seg 0.357842 | Elapsed 0.2m | ETA 3.9m
Epoch 303/500 | Batch 20/202 | Rec 0.000769 | Seg 0.361182 | Elapsed 0.4m | ETA 3.8m
Epoch 303/500 | Batch 30/202 | Rec 0.000726 | Seg 0.346449 | Elapsed 0.6m | ETA 3.6m
Epoch 303/500 | Batch 40/202 | Rec 0.000756 | Seg 0.359526 | Elapsed 0.8m | ETA 3.4m
Epoch 303/500 | Batch 50/202 | Rec 0.000729 | Seg 0.347383 | Elapsed 1.0m | ETA 3.2m
Epoch 303/500 | Batch 60/202 | Rec 0.000763 | Seg 0.333641 | Elapsed 1.3m | ETA 3.0m
Epoch 303/500 | Batch 70/202 | Rec 0.000756 | Seg 0.337411 | Elapsed 1.5m | ETA 2.8m
Epoch 303/500 | Batch 80/202 | Rec 0.000742 | Seg 0.329319 | Elapsed 1.7m | ETA 2.6m
Epoch 303/500 | Batch 90/202 | Rec 0.000733 | Seg 0.330484 | Elapsed 1.9m | ETA 2.3m
Epoch 303/500 | Batch 100/202 | Rec 0.000729 | Seg 0.323364 | Elapsed 2.1m | ETA 2.1m
Epoch 303/500 | Batch 110/202 | Rec 0.000731 | Seg 0.327089 | Elapsed 2.3m | ETA 1.9m
Epoch 303/500 | Batch 120/202 | Rec 0.000730 | Seg 0.332504 | Elapsed 2.5m | ETA 1.7m
Epoch 303/500 | Batch 130/202 | Rec 0.000728 | Seg 0.331284 | Elapsed 2.7m | ETA 1.5m
Epoch 303/500 | Batch 140/202 | Rec 0.000728 | Seg 0.332847 | Elapsed 3.0m | ETA 1.3m
Epoch 303/500 | Batch 150/202 | Rec 0.000719 | Seg 0.327146 | Elapsed 3.2m | ETA 1.1m
Epoch 303/500 | Batch 160/202 | Rec 0.000714 | Seg 0.327945 | Elapsed 3.4m | ETA 0.9m
Epoch 303/500 | Batch 170/202 | Rec 0.000723 | Seg 0.330520 | Elapsed 3.6m | ETA 0.7m
Epoch 303/500 | Batch 180/202 | Rec 0.000720 | Seg 0.329020 | Elapsed 3.8m | ETA 0.5m
Epoch 303/500 | Batch 190/202 | Rec 0.000725 | Seg 0.327159 | Elapsed 4.0m | ETA 0.3m
Epoch 303/500 | Batch 200/202 | Rec 0.000712 | Seg 0.323196 | Elapsed 4.2m | ETA 0.0m
Epoch 303/500 | Batch 202/202 | Rec 0.000709 | Seg 0.322457 | Elapsed 4.3m | ETA 0.0m

2026-09-25 17:54:13,221 - INFO: Rec loss: 0.0007085537547729725
2026-09-25 17:54:13,221 - INFO: Seg loss: 0.32245655416852176
2026-09-25 17:54:13,221 - INFO: λ_rec: 1
2026-09-25 17:54:13,221 - INFO: λ_seg: 0.0001
2026-09-25 17:55:30,623 - INFO: -------------------Epoch: 303------------------------
2026-09-25 17:55:30,628 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.821182  0.974155  0.000137
2026-09-25 17:55:30,635 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995871  0.997881  0.997437  0.998425  0.996059
real potato   0.930583  0.963993  0.967386  0.960724  0.999914
fake potato   0.940856  0.969477  0.962818  0.976330  0.999955
real apple    0.814791  0.897895  0.975517  0.831800  0.999348
fake apple    0.567686  0.724188  0.989980  0.570967  0.998358
real orange   0.939101  0.968544  0.991869  0.946387  0.999919
fake orange   0.932887  0.965228  0.965201  0.965356  0.999801
real grape    0.733978  0.846534  0.947588  0.765037  0.999421
fake grape    0.897495  0.945929  0.934444  0.957802  0.999595
real lemon    0.576500  0.731320  0.593371  0.952999  0.999177
fake lemon    0.834821  0.909926  0.997506  0.836567  0.999650
real avocado  0.923322  0.960083  0.969372  0.951067  0.999927
fake avocado  0.546277  0.706525  0.999533  0.546417  0.999457
real pepper   0.849623  0.918649  0.881829  0.958785  0.999379
fake pepper   0.796745  0.886826  0.955634  0.827348  0.999497
real plant    0.862334  0.926029  0.927262  0.924899  0.998523
fake plant    0.816347  0.898839  0.876069  0.922929  0.999835
real banana   0.551770  0.711101  0.886198  0.593848  0.998916
fake banana   0.749139  0.856530  0.847641  0.865710  0.999467
real onion    0.655873  0.792129  0.677091  0.954400  0.999548
fake onion    0.943696  0.970982  0.994674  0.948488  0.999964
real unknown  0.554515  0.713379  0.567324  0.960878  0.999877
fake unknown  0.215760  0.354903  0.230933  0.766570  0.997652
total         0.766520  0.852908  0.875508  0.868858  0.999271
total(-bg)    0.756095  0.846319  0.869965  0.862969  0.999417
2026-09-25 17:55:31,159 - INFO: Epoch accounting: {'epoch': 303, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11197273, 62405, 109948, 98810, 97876, 73315, 80171, 106527, 222318, 38801, 55336, 38308, 32770, 226172, 130267, 209582, 27530, 100988, 95470, 91742, 87529, 8716, 46418], 'crops_with_class': [202, 40, 45, 28, 26, 25, 27, 22, 39, 20, 20, 13, 14, 56, 36, 22, 22, 31, 33, 41, 38, 12, 21], 'targeted_crops_by_class': [0, 9, 11, 2, 5, 2, 7, 1, 4, 2, 2, 4, 2, 10, 4, 5, 2, 6, 4, 5, 6, 6, 5], 'sampled_scene_counts': [0, 1, 0, 1, 2, 1, 1, 0, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 2, 4, 0, 1, 0, 1, 2, 0, 1, 1, 1, 1, 4, 1, 1, 2, 1, 4, 1, 1, 1, 0, 4, 3, 0, 0, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 3, 0, 1, 3, 0, 2, 2, 0, 1, 2, 1, 2, 1, 1, 1, 5, 2, 4, 2, 2, 3, 0, 2, 3, 4, 1, 1, 4, 1, 1, 0, 0, 2, 2, 3, 0, 1, 2], 'learning_rate': 3.4117937460865384e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0007085537547729725, 'train_segmentation_loss': 0.32245655416852176, 'val_foreground_miou_all22': 0.7560954720834622, 'val_psnr_ref1': 38.821181640625, 'elapsed_seconds': 333.81423449516296, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 304/500 | Batch 10/202 | Rec 0.000598 | Seg 0.285887 | Elapsed 0.2m | ETA 4.0m
Epoch 304/500 | Batch 20/202 | Rec 0.000519 | Seg 0.268068 | Elapsed 0.4m | ETA 3.7m
Epoch 304/500 | Batch 30/202 | Rec 0.000542 | Seg 0.274568 | Elapsed 0.6m | ETA 3.6m
Epoch 304/500 | Batch 40/202 | Rec 0.000576 | Seg 0.297034 | Elapsed 0.8m | ETA 3.4m
Epoch 304/500 | Batch 50/202 | Rec 0.000649 | Seg 0.317275 | Elapsed 1.0m | ETA 3.1m
Epoch 304/500 | Batch 60/202 | Rec 0.000639 | Seg 0.306287 | Elapsed 1.2m | ETA 2.9m
Epoch 304/500 | Batch 70/202 | Rec 0.000643 | Seg 0.312073 | Elapsed 1.4m | ETA 2.7m
Epoch 304/500 | Batch 80/202 | Rec 0.000646 | Seg 0.308547 | Elapsed 1.6m | ETA 2.5m
Epoch 304/500 | Batch 90/202 | Rec 0.000647 | Seg 0.308882 | Elapsed 1.9m | ETA 2.3m
Epoch 304/500 | Batch 100/202 | Rec 0.000653 | Seg 0.308686 | Elapsed 2.1m | ETA 2.1m
Epoch 304/500 | Batch 110/202 | Rec 0.000660 | Seg 0.308114 | Elapsed 2.3m | ETA 1.9m
Epoch 304/500 | Batch 120/202 | Rec 0.000670 | Seg 0.306984 | Elapsed 2.5m | ETA 1.7m
Epoch 304/500 | Batch 130/202 | Rec 0.000674 | Seg 0.307382 | Elapsed 2.7m | ETA 1.5m
Epoch 304/500 | Batch 140/202 | Rec 0.000660 | Seg 0.304804 | Elapsed 2.9m | ETA 1.3m
Epoch 304/500 | Batch 150/202 | Rec 0.000670 | Seg 0.308748 | Elapsed 3.1m | ETA 1.1m
Epoch 304/500 | Batch 160/202 | Rec 0.000671 | Seg 0.311407 | Elapsed 3.3m | ETA 0.9m
Epoch 304/500 | Batch 170/202 | Rec 0.000667 | Seg 0.310503 | Elapsed 3.6m | ETA 0.7m
Epoch 304/500 | Batch 180/202 | Rec 0.000671 | Seg 0.314964 | Elapsed 3.8m | ETA 0.5m
Epoch 304/500 | Batch 190/202 | Rec 0.000681 | Seg 0.317055 | Elapsed 4.0m | ETA 0.2m
Epoch 304/500 | Batch 200/202 | Rec 0.000683 | Seg 0.318926 | Elapsed 4.2m | ETA 0.0m
Epoch 304/500 | Batch 202/202 | Rec 0.000683 | Seg 0.318433 | Elapsed 4.2m | ETA 0.0m

2026-09-25 17:59:43,230 - INFO: Rec loss: 0.0006826534778102171
2026-09-25 17:59:43,230 - INFO: Seg loss: 0.3184332614487941
2026-09-25 17:59:43,230 - INFO: λ_rec: 1
2026-09-25 17:59:43,230 - INFO: λ_seg: 0.0001
2026-09-25 18:01:02,451 - INFO: -------------------Epoch: 304------------------------
2026-09-25 18:01:02,455 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.551258  0.97383  0.000146
2026-09-25 18:01:02,462 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995841  0.997866  0.997131  0.998703  0.996029
real potato   0.839259  0.912556  0.986661  0.848891  0.999805
fake potato   0.889045  0.941214  0.954751  0.928152  0.999916
real apple    0.779482  0.876028  0.934309  0.824679  0.999195
fake apple    0.609024  0.756963  0.980648  0.616432  0.998506
real orange   0.944194  0.971246  0.997680  0.946271  0.999926
fake orange   0.948787  0.973670  0.967976  0.979533  0.999849
real grape    0.732421  0.845496  0.925974  0.777973  0.999407
fake grape    0.901119  0.947938  0.942366  0.953677  0.999613
real lemon    0.484141  0.652373  0.511113  0.901714  0.998871
fake lemon    0.847146  0.917199  0.991948  0.853011  0.999674
real avocado  0.874870  0.933209  0.903087  0.965517  0.999872
fake avocado  0.860329  0.924871  0.999260  0.860877  0.999833
real pepper   0.876558  0.934169  0.915945  0.953237  0.999509
fake pepper   0.830395  0.907290  0.946457  0.871327  0.999576
real plant    0.852159  0.920129  0.939685  0.901468  0.998436
fake plant    0.888746  0.941046  0.956083  0.926572  0.999908
real banana   0.452169  0.622704  0.901428  0.475689  0.998705
fake banana   0.714295  0.833290  0.803232  0.865793  0.999363
real onion    0.682645  0.811346  0.726496  0.918764  0.999614
fake onion    0.937261  0.967564  0.989633  0.946554  0.999960
real unknown  0.746125  0.854558  0.767071  0.964695  0.999948
fake unknown  0.245338  0.393971  0.269307  0.733792  0.998098
total         0.779624  0.862465  0.882967  0.870144  0.999287
total(-bg)    0.769796  0.856310  0.877778  0.864301  0.999436
2026-09-25 18:01:03,001 - INFO: Epoch accounting: {'epoch': 304, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11210841, 38825, 73536, 140954, 130146, 79911, 68449, 133663, 198611, 60426, 66823, 45356, 50178, 264935, 129296, 164666, 32154, 88186, 73081, 73181, 53327, 11917, 49810], 'crops_with_class': [202, 31, 36, 38, 35, 25, 27, 29, 32, 28, 25, 17, 19, 63, 36, 25, 28, 23, 32, 40, 21, 14, 19], 'targeted_crops_by_class': [0, 7, 7, 9, 5, 6, 7, 4, 3, 4, 3, 6, 5, 8, 6, 3, 7, 3, 8, 2, 4, 4, 5], 'sampled_scene_counts': [2, 1, 1, 0, 0, 3, 1, 2, 0, 2, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 2, 2, 2, 0, 2, 2, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 3, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 5, 0, 0, 0, 0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 2, 1, 3, 2, 1, 2, 1, 1, 2, 0, 2, 2, 0, 2, 3, 1, 0, 2, 0, 0, 2, 0, 3, 1, 2, 1, 1, 2, 0, 2, 0, 1, 0, 1, 3, 0, 2, 1, 3, 3, 2, 2, 3, 0, 1, 3, 3, 2, 2, 1, 0, 0, 0, 2, 3, 2, 0, 1, 3, 0, 0, 0, 1, 3, 1, 0, 4, 2, 1, 5, 3, 1, 0, 1, 0, 2, 2, 1, 0, 2, 0], 'learning_rate': 3.38214595209597e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006826534778102171, 'train_segmentation_loss': 0.3184332614487941, 'val_foreground_miou_all22': 0.7697957550815704, 'val_psnr_ref1': 38.551257934570316, 'elapsed_seconds': 331.8338272571564, 'peak_cuda_allocated_gib': 7.509067535400391}

Epoch 305/500 | Batch 10/202 | Rec 0.000576 | Seg 0.256726 | Elapsed 0.2m | ETA 4.3m
Epoch 305/500 | Batch 20/202 | Rec 0.000588 | Seg 0.274500 | Elapsed 0.4m | ETA 4.0m
Epoch 305/500 | Batch 30/202 | Rec 0.000597 | Seg 0.284462 | Elapsed 0.6m | ETA 3.7m
Epoch 305/500 | Batch 40/202 | Rec 0.000658 | Seg 0.320477 | Elapsed 0.9m | ETA 3.5m
Epoch 305/500 | Batch 50/202 | Rec 0.000623 | Seg 0.300689 | Elapsed 1.1m | ETA 3.2m
Epoch 305/500 | Batch 60/202 | Rec 0.000618 | Seg 0.293279 | Elapsed 1.3m | ETA 3.0m
Epoch 305/500 | Batch 70/202 | Rec 0.000614 | Seg 0.295954 | Elapsed 1.5m | ETA 2.8m
Epoch 305/500 | Batch 80/202 | Rec 0.000612 | Seg 0.289865 | Elapsed 1.7m | ETA 2.6m
Epoch 305/500 | Batch 90/202 | Rec 0.000609 | Seg 0.292074 | Elapsed 1.9m | ETA 2.4m
Epoch 305/500 | Batch 100/202 | Rec 0.000621 | Seg 0.291952 | Elapsed 2.1m | ETA 2.1m
Epoch 305/500 | Batch 110/202 | Rec 0.000623 | Seg 0.297703 | Elapsed 2.3m | ETA 2.0m
Epoch 305/500 | Batch 120/202 | Rec 0.000611 | Seg 0.291108 | Elapsed 2.6m | ETA 1.7m
Epoch 305/500 | Batch 130/202 | Rec 0.000628 | Seg 0.289248 | Elapsed 2.8m | ETA 1.5m
Epoch 305/500 | Batch 140/202 | Rec 0.000634 | Seg 0.291710 | Elapsed 3.0m | ETA 1.3m
Epoch 305/500 | Batch 150/202 | Rec 0.000629 | Seg 0.287434 | Elapsed 3.2m | ETA 1.1m
Epoch 305/500 | Batch 160/202 | Rec 0.000626 | Seg 0.289209 | Elapsed 3.4m | ETA 0.9m
Epoch 305/500 | Batch 170/202 | Rec 0.000624 | Seg 0.289536 | Elapsed 3.6m | ETA 0.7m
Epoch 305/500 | Batch 180/202 | Rec 0.000629 | Seg 0.291255 | Elapsed 3.8m | ETA 0.5m
Epoch 305/500 | Batch 190/202 | Rec 0.000625 | Seg 0.290635 | Elapsed 4.0m | ETA 0.3m
Epoch 305/500 | Batch 200/202 | Rec 0.000627 | Seg 0.292799 | Elapsed 4.2m | ETA 0.0m
Epoch 305/500 | Batch 202/202 | Rec 0.000625 | Seg 0.292078 | Elapsed 4.3m | ETA 0.0m

2026-09-25 18:05:19,818 - INFO: Rec loss: 0.0006246474864149217
2026-09-25 18:05:19,818 - INFO: Seg loss: 0.2920781522251592
2026-09-25 18:05:19,818 - INFO: λ_rec: 1
2026-09-25 18:05:19,818 - INFO: λ_seg: 0.0001
2026-09-25 18:06:44,047 - INFO: -------------------Epoch: 305------------------------
2026-09-25 18:06:44,050 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.203363  0.97317  0.000158
2026-09-25 18:06:44,057 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995537  0.997714  0.996845  0.998684  0.995738
real potato   0.438878  0.609986  0.999129  0.439046  0.999328
fake potato   0.650551  0.788235  0.961411  0.667993  0.999739
real apple    0.682519  0.811256  0.806397  0.816276  0.998690
fake apple    0.836961  0.911195  0.956219  0.870312  0.999360
real orange   0.875579  0.933613  0.999472  0.875984  0.999836
fake orange   0.924222  0.960569  0.939334  0.982891  0.999769
real grape    0.688764  0.815653  0.933333  0.724403  0.999317
fake grape    0.884084  0.938426  0.921213  0.956400  0.999536
real lemon    0.386710  0.557693  0.421035  0.825889  0.998461
fake lemon    0.846563  0.916857  0.996361  0.849189  0.999674
real avocado  0.798545  0.887940  0.816591  0.973071  0.999772
fake avocado  0.861748  0.925691  0.999114  0.862408  0.999834
real pepper   0.823666  0.903258  0.877028  0.931211  0.999271
fake pepper   0.747895  0.855717  0.975974  0.761923  0.999388
real plant    0.845428  0.916191  0.931963  0.901040  0.998352
fake plant    0.874193  0.932824  0.958536  0.908551  0.999896
real banana   0.282444  0.440441  0.900021  0.291593  0.998335
fake banana   0.660842  0.795742  0.779795  0.812459  0.999233
real onion    0.685935  0.813665  0.744017  0.897821  0.999629
fake onion    0.893340  0.943616  0.997575  0.895284  0.999933
real unknown  0.740658  0.850959  0.773614  0.945611  0.999947
fake unknown  0.345877  0.513936  0.380369  0.792285  0.998737
total         0.729171  0.827008  0.872406  0.825231  0.999208
total(-bg)    0.717064  0.819248  0.866750  0.817347  0.999365
2026-09-25 18:06:44,589 - INFO: Epoch accounting: {'epoch': 305, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11361385, 41043, 48756, 114495, 143050, 79849, 92863, 129889, 188485, 87980, 60425, 52319, 26986, 233986, 95847, 127410, 30600, 74712, 59668, 89803, 57237, 4645, 36839], 'crops_with_class': [202, 26, 23, 29, 34, 22, 31, 27, 31, 39, 29, 17, 12, 57, 24, 21, 29, 23, 32, 37, 27, 8, 17], 'targeted_crops_by_class': [0, 3, 6, 3, 8, 3, 6, 3, 7, 7, 6, 4, 3, 5, 4, 4, 4, 3, 5, 6, 5, 2, 3], 'sampled_scene_counts': [1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 2, 0, 1, 2, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 0, 0, 1, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 3, 2, 1, 0, 2, 1, 3, 2, 2, 1, 1, 0, 4, 0, 3, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 3, 0, 1, 0, 1, 3, 1, 1, 1, 1, 3, 2, 1, 1, 0, 2, 2, 1, 1, 2, 1, 1, 1, 0, 4, 1, 1, 1, 1, 0, 2, 1, 1, 0, 2, 2, 0, 1, 1, 3, 0, 0, 1, 0, 2, 2, 1, 2, 2, 1, 0, 2, 1, 1, 2, 3, 1], 'learning_rate': 3.3525625216915995e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006246474864149217, 'train_segmentation_loss': 0.2920781522251592, 'val_foreground_miou_all22': 0.7170637624822043, 'val_psnr_ref1': 38.20336334228516, 'elapsed_seconds': 341.57925629615784, 'peak_cuda_allocated_gib': 7.5095977783203125}

Epoch 306/500 | Batch 10/202 | Rec 0.000644 | Seg 0.305855 | Elapsed 0.2m | ETA 4.3m
Epoch 306/500 | Batch 20/202 | Rec 0.000654 | Seg 0.322950 | Elapsed 0.4m | ETA 3.9m
Epoch 306/500 | Batch 30/202 | Rec 0.000694 | Seg 0.351554 | Elapsed 0.6m | ETA 3.6m
Epoch 306/500 | Batch 40/202 | Rec 0.000644 | Seg 0.330012 | Elapsed 0.8m | ETA 3.4m
Epoch 306/500 | Batch 50/202 | Rec 0.000683 | Seg 0.333111 | Elapsed 1.0m | ETA 3.2m
Epoch 306/500 | Batch 60/202 | Rec 0.000692 | Seg 0.339662 | Elapsed 1.2m | ETA 3.0m
Epoch 306/500 | Batch 70/202 | Rec 0.000670 | Seg 0.327784 | Elapsed 1.5m | ETA 2.8m
Epoch 306/500 | Batch 80/202 | Rec 0.000655 | Seg 0.323910 | Elapsed 1.7m | ETA 2.5m
Epoch 306/500 | Batch 90/202 | Rec 0.000661 | Seg 0.322431 | Elapsed 1.9m | ETA 2.3m
Epoch 306/500 | Batch 100/202 | Rec 0.000633 | Seg 0.312091 | Elapsed 2.1m | ETA 2.1m
Epoch 306/500 | Batch 110/202 | Rec 0.000627 | Seg 0.308972 | Elapsed 2.3m | ETA 1.9m
Epoch 306/500 | Batch 120/202 | Rec 0.000631 | Seg 0.318494 | Elapsed 2.5m | ETA 1.7m
Epoch 306/500 | Batch 130/202 | Rec 0.000640 | Seg 0.318729 | Elapsed 2.7m | ETA 1.5m
Epoch 306/500 | Batch 140/202 | Rec 0.000647 | Seg 0.319071 | Elapsed 2.9m | ETA 1.3m
Epoch 306/500 | Batch 150/202 | Rec 0.000644 | Seg 0.322129 | Elapsed 3.1m | ETA 1.1m
Epoch 306/500 | Batch 160/202 | Rec 0.000646 | Seg 0.318841 | Elapsed 3.3m | ETA 0.9m
Epoch 306/500 | Batch 170/202 | Rec 0.000651 | Seg 0.316490 | Elapsed 3.5m | ETA 0.7m
Epoch 306/500 | Batch 180/202 | Rec 0.000651 | Seg 0.316486 | Elapsed 3.7m | ETA 0.5m
Epoch 306/500 | Batch 190/202 | Rec 0.000643 | Seg 0.315213 | Elapsed 3.9m | ETA 0.2m
Epoch 306/500 | Batch 200/202 | Rec 0.000644 | Seg 0.316922 | Elapsed 4.2m | ETA 0.0m
Epoch 306/500 | Batch 202/202 | Rec 0.000645 | Seg 0.315905 | Elapsed 4.2m | ETA 0.0m

2026-09-25 18:10:56,364 - INFO: Rec loss: 0.0006451020551797021
2026-09-25 18:10:56,364 - INFO: Seg loss: 0.31590528255051903
2026-09-25 18:10:56,364 - INFO: λ_rec: 1
2026-09-25 18:10:56,364 - INFO: λ_seg: 0.0001
2026-09-25 18:12:18,576 - INFO: -------------------Epoch: 306------------------------
2026-09-25 18:12:18,580 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.464586  0.973853  0.000148
2026-09-25 18:12:18,588 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995915  0.997903  0.997364  0.998543  0.996100
real potato   0.655177  0.791622  0.985191  0.661693  0.999583
fake potato   0.790171  0.882739  0.967541  0.811688  0.999843
real apple    0.767837  0.868624  0.876955  0.860548  0.999102
fake apple    0.622109  0.766989  0.956469  0.640236  0.998532
real orange   0.936556  0.967189  0.995952  0.940134  0.999916
fake orange   0.945957  0.972178  0.957846  0.987048  0.999839
real grape    0.792297  0.884064  0.955831  0.822407  0.999550
fake grape    0.902270  0.948575  0.940019  0.957390  0.999616
real lemon    0.519403  0.683646  0.558564  0.881070  0.999042
fake lemon    0.848795  0.918165  0.983364  0.861161  0.999675
real avocado  0.926705  0.961908  0.969010  0.955008  0.999930
fake avocado  0.797783  0.887469  0.999043  0.798393  0.999758
real pepper   0.863812  0.926881  0.889306  0.967879  0.999442
fake pepper   0.799335  0.888429  0.954081  0.831317  0.999503
real plant    0.872751  0.932002  0.946310  0.918218  0.998661
fake plant    0.843420  0.915010  0.911060  0.919095  0.999864
real banana   0.492713  0.660112  0.914303  0.516569  0.998805
fake banana   0.698896  0.822715  0.792364  0.855591  0.999322
real onion    0.663062  0.797350  0.691155  0.942239  0.999567
fake onion    0.941599  0.969871  0.989188  0.951391  0.999963
real unknown  0.862862  0.926333  0.889377  0.966603  0.999975
fake unknown  0.242031  0.389696  0.264027  0.743933  0.998037
total         0.773107  0.859107  0.886275  0.860355  0.999288
total(-bg)    0.762979  0.852798  0.881225  0.854073  0.999433
2026-09-25 18:12:19,114 - INFO: Epoch accounting: {'epoch': 306, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11231249, 49252, 49522, 120732, 138768, 108351, 71631, 196468, 123484, 51778, 61620, 45217, 41539, 233785, 151273, 187877, 17293, 87352, 93840, 79739, 45406, 13947, 38149], 'crops_with_class': [202, 28, 23, 31, 34, 36, 25, 32, 21, 28, 26, 15, 15, 55, 35, 30, 20, 25, 37, 33, 24, 15, 19], 'targeted_crops_by_class': [0, 6, 9, 3, 8, 6, 6, 5, 1, 4, 6, 3, 5, 5, 4, 9, 3, 4, 5, 1, 4, 3, 2], 'sampled_scene_counts': [0, 0, 1, 0, 0, 0, 2, 1, 1, 5, 1, 2, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 3, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 3, 2, 1, 1, 2, 1, 0, 2, 1, 1, 2, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 2, 1, 0, 0, 1, 0, 2, 0, 1, 2, 0, 1, 2, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 2, 2, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 4, 2, 1, 3, 0, 1, 3, 1, 0, 2, 1, 2, 2, 4, 7, 2, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 0, 1, 1, 2, 1, 2, 3, 0, 0, 1, 1, 0, 1, 2, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 3, 2], 'learning_rate': 3.323044622776604e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006451020551797021, 'train_segmentation_loss': 0.31590528255051903, 'val_foreground_miou_all22': 0.7629791456444548, 'val_psnr_ref1': 38.46458648681641, 'elapsed_seconds': 334.51621317863464, 'peak_cuda_allocated_gib': 7.510807037353516}

Epoch 307/500 | Batch 10/202 | Rec 0.000892 | Seg 0.295341 | Elapsed 0.2m | ETA 4.0m
Epoch 307/500 | Batch 20/202 | Rec 0.000842 | Seg 0.325353 | Elapsed 0.4m | ETA 3.7m
Epoch 307/500 | Batch 30/202 | Rec 0.000820 | Seg 0.353346 | Elapsed 0.6m | ETA 3.6m
Epoch 307/500 | Batch 40/202 | Rec 0.000779 | Seg 0.349043 | Elapsed 0.8m | ETA 3.4m
Epoch 307/500 | Batch 50/202 | Rec 0.000750 | Seg 0.339646 | Elapsed 1.0m | ETA 3.1m
Epoch 307/500 | Batch 60/202 | Rec 0.000752 | Seg 0.339786 | Elapsed 1.2m | ETA 2.9m
Epoch 307/500 | Batch 70/202 | Rec 0.000734 | Seg 0.333585 | Elapsed 1.4m | ETA 2.7m
Epoch 307/500 | Batch 80/202 | Rec 0.000718 | Seg 0.332626 | Elapsed 1.7m | ETA 2.5m
Epoch 307/500 | Batch 90/202 | Rec 0.000701 | Seg 0.331581 | Elapsed 1.9m | ETA 2.3m
Epoch 307/500 | Batch 100/202 | Rec 0.000676 | Seg 0.317208 | Elapsed 2.1m | ETA 2.1m
Epoch 307/500 | Batch 110/202 | Rec 0.000665 | Seg 0.313063 | Elapsed 2.3m | ETA 1.9m
Epoch 307/500 | Batch 120/202 | Rec 0.000662 | Seg 0.311109 | Elapsed 2.5m | ETA 1.7m
Epoch 307/500 | Batch 130/202 | Rec 0.000665 | Seg 0.311025 | Elapsed 2.7m | ETA 1.5m
Epoch 307/500 | Batch 140/202 | Rec 0.000658 | Seg 0.309824 | Elapsed 2.9m | ETA 1.3m
Epoch 307/500 | Batch 150/202 | Rec 0.000658 | Seg 0.308413 | Elapsed 3.1m | ETA 1.1m
Epoch 307/500 | Batch 160/202 | Rec 0.000658 | Seg 0.307022 | Elapsed 3.3m | ETA 0.9m
Epoch 307/500 | Batch 170/202 | Rec 0.000655 | Seg 0.306851 | Elapsed 3.5m | ETA 0.7m
Epoch 307/500 | Batch 180/202 | Rec 0.000655 | Seg 0.306065 | Elapsed 3.7m | ETA 0.5m
Epoch 307/500 | Batch 190/202 | Rec 0.000651 | Seg 0.307018 | Elapsed 3.9m | ETA 0.2m
Epoch 307/500 | Batch 200/202 | Rec 0.000656 | Seg 0.304813 | Elapsed 4.1m | ETA 0.0m
Epoch 307/500 | Batch 202/202 | Rec 0.000655 | Seg 0.303568 | Elapsed 4.2m | ETA 0.0m

2026-09-25 18:16:28,809 - INFO: Rec loss: 0.0006545158425843952
2026-09-25 18:16:28,809 - INFO: Seg loss: 0.30356769730327743
2026-09-25 18:16:28,809 - INFO: λ_rec: 1
2026-09-25 18:16:28,809 - INFO: λ_seg: 0.0001
2026-09-25 18:17:44,252 - INFO: -------------------Epoch: 307------------------------
2026-09-25 18:17:44,255 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.679517  0.973565  0.000142
2026-09-25 18:17:44,262 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995725  0.997808  0.997186  0.998530  0.995918
real potato   0.301581  0.463372  1.000000  0.301581  0.999164
fake potato   0.646045  0.784919  0.986371  0.651864  0.999740
real apple    0.683499  0.811948  0.768387  0.860858  0.998625
fake apple    0.678547  0.808445  0.968255  0.693986  0.998759
real orange   0.946030  0.972217  0.997928  0.947893  0.999929
fake orange   0.953191  0.975984  0.984072  0.968127  0.999864
real grape    0.767115  0.868162  0.947846  0.800921  0.999492
fake grape    0.891813  0.942763  0.920703  0.966011  0.999566
real lemon    0.479087  0.647769  0.494231  0.939886  0.998799
fake lemon    0.841836  0.914078  0.997272  0.843779  0.999665
real avocado  0.892585  0.943194  0.926512  0.960591  0.999893
fake avocado  0.863590  0.926753  0.999705  0.863810  0.999837
real pepper   0.808498  0.894060  0.840592  0.954906  0.999173
fake pepper   0.693802  0.819176  0.992890  0.697266  0.999267
real plant    0.867193  0.928823  0.937806  0.920109  0.998591
fake plant    0.898402  0.946432  0.955638  0.937500  0.999916
real banana   0.377574  0.548130  0.903070  0.393522  0.998542
fake banana   0.716931  0.835081  0.841817  0.828550  0.999398
real onion    0.670867  0.802967  0.719716  0.908124  0.999597
fake onion    0.914842  0.955478  0.994248  0.919710  0.999946
real unknown  0.798883  0.888149  0.830017  0.955153  0.999962
fake unknown  0.294298  0.454723  0.305762  0.886997  0.998208
total         0.738345  0.831758  0.883044  0.834768  0.999211
total(-bg)    0.726646  0.824210  0.877856  0.827325  0.999360
2026-09-25 18:17:44,780 - INFO: Epoch accounting: {'epoch': 307, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11251077, 58721, 69359, 153393, 134536, 108459, 84330, 132466, 219691, 88122, 78709, 20906, 15907, 232849, 97129, 129965, 26781, 65376, 77758, 88071, 59830, 9874, 34963], 'crops_with_class': [202, 32, 32, 38, 35, 30, 29, 27, 36, 40, 34, 7, 5, 55, 31, 18, 22, 23, 29, 36, 28, 11, 19], 'targeted_crops_by_class': [0, 6, 6, 8, 4, 6, 6, 6, 3, 4, 5, 3, 2, 3, 8, 5, 5, 6, 6, 4, 4, 4, 3], 'sampled_scene_counts': [0, 3, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 2, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1, 2, 0, 2, 2, 0, 1, 2, 0, 1, 1, 0, 2, 1, 0, 1, 0, 0, 2, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 2, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 2, 1, 3, 3, 1, 2, 2, 1, 2, 1, 2, 1, 2, 4, 1, 2, 1, 0, 2, 2, 0, 0, 0, 1, 2, 2, 1, 2, 4, 2, 0, 0, 1, 0, 3, 0, 0, 2, 1, 2, 3, 1, 1, 3, 3, 1, 2, 2, 1, 1, 0, 0, 3, 1, 0, 2, 2, 0, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 1, 1, 1, 2, 1, 0, 0, 3, 1, 3, 2], 'learning_rate': 3.293593420667091e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006545158425843952, 'train_segmentation_loss': 0.30356769730327743, 'val_foreground_miou_all22': 0.7266458147410357, 'val_psnr_ref1': 38.67951721191406, 'elapsed_seconds': 325.65721225738525, 'peak_cuda_allocated_gib': 7.515201568603516}

Epoch 308/500 | Batch 10/202 | Rec 0.000600 | Seg 0.244849 | Elapsed 0.2m | ETA 4.0m
Epoch 308/500 | Batch 20/202 | Rec 0.000637 | Seg 0.255226 | Elapsed 0.4m | ETA 3.8m
Epoch 308/500 | Batch 30/202 | Rec 0.000671 | Seg 0.282421 | Elapsed 0.6m | ETA 3.5m
Epoch 308/500 | Batch 40/202 | Rec 0.000623 | Seg 0.280538 | Elapsed 0.8m | ETA 3.3m
Epoch 308/500 | Batch 50/202 | Rec 0.000648 | Seg 0.300415 | Elapsed 1.0m | ETA 3.1m
Epoch 308/500 | Batch 60/202 | Rec 0.000646 | Seg 0.304062 | Elapsed 1.2m | ETA 2.9m
Epoch 308/500 | Batch 70/202 | Rec 0.000663 | Seg 0.299520 | Elapsed 1.4m | ETA 2.7m
Epoch 308/500 | Batch 80/202 | Rec 0.000687 | Seg 0.306135 | Elapsed 1.6m | ETA 2.5m
Epoch 308/500 | Batch 90/202 | Rec 0.000698 | Seg 0.316056 | Elapsed 1.8m | ETA 2.3m
Epoch 308/500 | Batch 100/202 | Rec 0.000688 | Seg 0.316029 | Elapsed 2.1m | ETA 2.1m
Epoch 308/500 | Batch 110/202 | Rec 0.000700 | Seg 0.318905 | Elapsed 2.3m | ETA 1.9m
Epoch 308/500 | Batch 120/202 | Rec 0.000693 | Seg 0.314801 | Elapsed 2.5m | ETA 1.7m
Epoch 308/500 | Batch 130/202 | Rec 0.000692 | Seg 0.318069 | Elapsed 2.7m | ETA 1.5m
Epoch 308/500 | Batch 140/202 | Rec 0.000683 | Seg 0.315285 | Elapsed 2.9m | ETA 1.3m
Epoch 308/500 | Batch 150/202 | Rec 0.000682 | Seg 0.312702 | Elapsed 3.1m | ETA 1.1m
Epoch 308/500 | Batch 160/202 | Rec 0.000687 | Seg 0.315010 | Elapsed 3.3m | ETA 0.9m
Epoch 308/500 | Batch 170/202 | Rec 0.000688 | Seg 0.320478 | Elapsed 3.5m | ETA 0.7m
Epoch 308/500 | Batch 180/202 | Rec 0.000686 | Seg 0.322734 | Elapsed 3.7m | ETA 0.5m
Epoch 308/500 | Batch 190/202 | Rec 0.000682 | Seg 0.321385 | Elapsed 3.9m | ETA 0.2m
Epoch 308/500 | Batch 200/202 | Rec 0.000674 | Seg 0.317937 | Elapsed 4.1m | ETA 0.0m
Epoch 308/500 | Batch 202/202 | Rec 0.000672 | Seg 0.316471 | Elapsed 4.1m | ETA 0.0m

2026-09-25 18:21:53,082 - INFO: Rec loss: 0.0006720620144238133
2026-09-25 18:21:53,082 - INFO: Seg loss: 0.3164705155361997
2026-09-25 18:21:53,082 - INFO: λ_rec: 1
2026-09-25 18:21:53,082 - INFO: λ_seg: 0.0001
2026-09-25 18:23:17,519 - INFO: -------------------Epoch: 308------------------------
2026-09-25 18:23:17,523 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.715499  0.974105  0.00014
2026-09-25 18:23:17,529 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995860  0.997876  0.997314  0.998538  0.996048
real potato   0.340347  0.507811  1.000000  0.340347  0.999211
fake potato   0.654774  0.791328  0.976923  0.665061  0.999745
real apple    0.672331  0.804014  0.768134  0.843521  0.998582
fake apple    0.697185  0.821529  0.948284  0.724741  0.998811
real orange   0.954635  0.976741  0.996746  0.957619  0.999940
fake orange   0.927060  0.962100  0.937899  0.987688  0.999778
real grape    0.743682  0.852953  0.959452  0.767814  0.999447
fake grape    0.890582  0.942075  0.927843  0.956854  0.999565
real lemon    0.436396  0.607582  0.454974  0.914438  0.998612
fake lemon    0.858357  0.923730  0.988327  0.867147  0.999697
real avocado  0.725507  0.840871  0.735689  0.981281  0.999655
fake avocado  0.854249  0.921346  0.998957  0.855011  0.999825
real pepper   0.812403  0.896443  0.894075  0.898924  0.999241
fake pepper   0.720265  0.837340  0.993323  0.723769  0.999330
real plant    0.868094  0.929340  0.930726  0.928057  0.998589
fake plant    0.897013  0.945661  0.953076  0.938459  0.999914
real banana   0.274165  0.430308  0.914185  0.281407  0.998326
fake banana   0.726271  0.841383  0.852353  0.830790  0.999424
real onion    0.637087  0.778270  0.667917  0.932444  0.999520
fake onion    0.904911  0.950032  0.994971  0.909069  0.999940
real unknown  0.765460  0.867101  0.784996  0.968511  0.999953
fake unknown  0.301977  0.463836  0.316442  0.868526  0.998308
total         0.724287  0.821290  0.869244  0.832175  0.999194
total(-bg)    0.711943  0.813263  0.863422  0.824613  0.999337
2026-09-25 18:23:18,046 - INFO: Epoch accounting: {'epoch': 308, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11208538, 46817, 52448, 115960, 152770, 102544, 83581, 132253, 212501, 77229, 74496, 45102, 36805, 234414, 110400, 132589, 20279, 101513, 66342, 105628, 60267, 12222, 53574], 'crops_with_class': [202, 31, 25, 33, 36, 29, 31, 26, 37, 35, 32, 16, 15, 60, 31, 19, 20, 31, 26, 40, 28, 11, 24], 'targeted_crops_by_class': [0, 5, 5, 7, 7, 7, 2, 5, 7, 6, 6, 5, 7, 3, 3, 3, 6, 9, 2, 4, 7, 6, 5], 'sampled_scene_counts': [2, 1, 3, 1, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 4, 2, 1, 2, 0, 4, 1, 1, 2, 3, 1, 1, 0, 1, 2, 2, 1, 0, 2, 0, 2, 3, 0, 1, 1, 2, 0, 2, 3, 0, 2, 1, 2, 4, 1, 0, 1, 1, 2, 2, 2, 5, 1, 0, 1, 1, 2, 2, 2, 4, 1, 0, 3, 1, 0, 2, 2, 1, 0, 2, 1, 0, 2, 0, 2, 1, 2, 1, 2, 1, 1, 2, 3, 2, 1, 2, 0, 0, 2, 1, 2, 2], 'learning_rate': 3.26421007804609e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006720620144238133, 'train_segmentation_loss': 0.3164705155361997, 'val_foreground_miou_all22': 0.711943208443943, 'val_psnr_ref1': 38.715499267578124, 'elapsed_seconds': 333.2569887638092, 'peak_cuda_allocated_gib': 7.510288238525391}

Epoch 309/500 | Batch 10/202 | Rec 0.000634 | Seg 0.297579 | Elapsed 0.2m | ETA 3.9m
Epoch 309/500 | Batch 20/202 | Rec 0.000706 | Seg 0.312130 | Elapsed 0.4m | ETA 3.8m
Epoch 309/500 | Batch 30/202 | Rec 0.000717 | Seg 0.331655 | Elapsed 0.6m | ETA 3.6m
Epoch 309/500 | Batch 40/202 | Rec 0.000700 | Seg 0.334173 | Elapsed 0.8m | ETA 3.3m
Epoch 309/500 | Batch 50/202 | Rec 0.000691 | Seg 0.342998 | Elapsed 1.0m | ETA 3.1m
Epoch 309/500 | Batch 60/202 | Rec 0.000688 | Seg 0.333700 | Elapsed 1.2m | ETA 2.9m
Epoch 309/500 | Batch 70/202 | Rec 0.000680 | Seg 0.327996 | Elapsed 1.4m | ETA 2.7m
Epoch 309/500 | Batch 80/202 | Rec 0.000663 | Seg 0.318180 | Elapsed 1.7m | ETA 2.5m
Epoch 309/500 | Batch 90/202 | Rec 0.000654 | Seg 0.311368 | Elapsed 1.9m | ETA 2.3m
Epoch 309/500 | Batch 100/202 | Rec 0.000637 | Seg 0.306966 | Elapsed 2.1m | ETA 2.1m
Epoch 309/500 | Batch 110/202 | Rec 0.000638 | Seg 0.302525 | Elapsed 2.3m | ETA 1.9m
Epoch 309/500 | Batch 120/202 | Rec 0.000633 | Seg 0.297219 | Elapsed 2.5m | ETA 1.7m
Epoch 309/500 | Batch 130/202 | Rec 0.000628 | Seg 0.294504 | Elapsed 2.7m | ETA 1.5m
Epoch 309/500 | Batch 140/202 | Rec 0.000641 | Seg 0.300899 | Elapsed 2.9m | ETA 1.3m
Epoch 309/500 | Batch 150/202 | Rec 0.000652 | Seg 0.307518 | Elapsed 3.1m | ETA 1.1m
Epoch 309/500 | Batch 160/202 | Rec 0.000650 | Seg 0.307142 | Elapsed 3.3m | ETA 0.9m
Epoch 309/500 | Batch 170/202 | Rec 0.000653 | Seg 0.306334 | Elapsed 3.5m | ETA 0.7m
Epoch 309/500 | Batch 180/202 | Rec 0.000656 | Seg 0.307833 | Elapsed 3.7m | ETA 0.5m
Epoch 309/500 | Batch 190/202 | Rec 0.000653 | Seg 0.308592 | Elapsed 3.9m | ETA 0.2m
Epoch 309/500 | Batch 200/202 | Rec 0.000647 | Seg 0.305746 | Elapsed 4.2m | ETA 0.0m
Epoch 309/500 | Batch 202/202 | Rec 0.000647 | Seg 0.306071 | Elapsed 4.2m | ETA 0.0m

2026-09-25 18:27:30,369 - INFO: Rec loss: 0.0006471968652584848
2026-09-25 18:27:30,369 - INFO: Seg loss: 0.30607122463164943
2026-09-25 18:27:30,370 - INFO: λ_rec: 1
2026-09-25 18:27:30,370 - INFO: λ_seg: 0.0001
2026-09-25 18:28:53,343 - INFO: -------------------Epoch: 309------------------------
2026-09-25 18:28:53,347 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.837018  0.974024  0.000137
2026-09-25 18:28:53,354 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995557  0.997724  0.996814  0.998736  0.995757
real potato   0.519823  0.684012  0.987250  0.523336  0.999422
fake potato   0.716146  0.834549  0.982138  0.725597  0.999790
real apple    0.718121  0.835888  0.845139  0.826935  0.998880
fake apple    0.664560  0.798433  0.975668  0.675760  0.998712
real orange   0.953961  0.976388  0.991173  0.962135  0.999939
fake orange   0.951018  0.974844  0.979140  0.970685  0.999857
real grape    0.771449  0.870931  0.950558  0.803698  0.999503
fake grape    0.890288  0.941910  0.917256  0.968032  0.999559
real lemon    0.493271  0.660613  0.510030  0.937549  0.998868
fake lemon    0.842613  0.914535  0.998464  0.843707  0.999667
real avocado  0.762820  0.865405  0.784617  0.964860  0.999721
fake avocado  0.803417  0.890945  0.999683  0.803622  0.999765
real pepper   0.776042  0.873851  0.837186  0.913983  0.999035
fake pepper   0.678436  0.808366  0.983219  0.686384  0.999225
real plant    0.849895  0.918808  0.944107  0.894923  0.998419
fake plant    0.805825  0.892423  0.863963  0.922929  0.999823
real banana   0.405221  0.576694  0.917481  0.420549  0.998613
fake banana   0.749058  0.856478  0.890870  0.824735  0.999492
real onion    0.656430  0.792536  0.674736  0.960311  0.999546
fake onion    0.942280  0.970232  0.994164  0.947521  0.999963
real unknown  0.553880  0.712853  0.571758  0.946565  0.999878
fake unknown  0.276723  0.433450  0.296610  0.804962  0.998227
total         0.729428  0.829646  0.864871  0.840327  0.999203
total(-bg)    0.717331  0.822006  0.858873  0.833126  0.999359
2026-09-25 18:28:53,940 - INFO: Epoch accounting: {'epoch': 309, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11272026, 37392, 56075, 148597, 151050, 102390, 74173, 153821, 215051, 74547, 69590, 23331, 48916, 186757, 121435, 139794, 25473, 81172, 54013, 94027, 39230, 14147, 55265], 'crops_with_class': [202, 23, 25, 36, 43, 34, 23, 31, 40, 38, 27, 8, 21, 48, 30, 18, 21, 24, 24, 33, 19, 19, 22], 'targeted_crops_by_class': [0, 3, 4, 6, 5, 8, 4, 4, 3, 6, 4, 1, 8, 6, 5, 1, 3, 3, 6, 5, 1, 8, 4], 'sampled_scene_counts': [0, 0, 1, 0, 1, 2, 0, 0, 0, 3, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 3, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 2, 3, 1, 1, 0, 0, 2, 2, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 2, 1, 2, 2, 1, 5, 2, 2, 0, 0, 1, 0, 1, 2, 3, 1, 1, 1, 1, 1, 0, 0, 0, 3, 2, 1, 0, 2, 4, 3, 2, 1, 3, 1, 0, 0, 0, 1, 4, 1, 1, 1, 6, 2, 0, 3, 2, 1, 2, 3, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 1, 3, 0, 0, 1, 2, 0, 4, 1, 0, 1, 1, 0, 1, 3, 2, 0, 1, 0, 1, 1, 0, 2, 2], 'learning_rate': 3.234895754917657e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006471968652584848, 'train_segmentation_loss': 0.30607122463164943, 'val_foreground_miou_all22': 0.7173308689981899, 'val_psnr_ref1': 38.837018127441404, 'elapsed_seconds': 335.886412858963, 'peak_cuda_allocated_gib': 7.509220123291016}

Epoch 310/500 | Batch 10/202 | Rec 0.000723 | Seg 0.407892 | Elapsed 0.2m | ETA 3.8m
Epoch 310/500 | Batch 20/202 | Rec 0.000709 | Seg 0.367000 | Elapsed 0.4m | ETA 3.7m
Epoch 310/500 | Batch 30/202 | Rec 0.000656 | Seg 0.342077 | Elapsed 0.6m | ETA 3.6m
Epoch 310/500 | Batch 40/202 | Rec 0.000623 | Seg 0.321242 | Elapsed 0.8m | ETA 3.4m
Epoch 310/500 | Batch 50/202 | Rec 0.000633 | Seg 0.321541 | Elapsed 1.0m | ETA 3.1m
Epoch 310/500 | Batch 60/202 | Rec 0.000660 | Seg 0.315115 | Elapsed 1.2m | ETA 2.9m
Epoch 310/500 | Batch 70/202 | Rec 0.000664 | Seg 0.315140 | Elapsed 1.4m | ETA 2.7m
Epoch 310/500 | Batch 80/202 | Rec 0.000677 | Seg 0.319218 | Elapsed 1.7m | ETA 2.5m
Epoch 310/500 | Batch 90/202 | Rec 0.000667 | Seg 0.309975 | Elapsed 1.9m | ETA 2.3m
Epoch 310/500 | Batch 100/202 | Rec 0.000671 | Seg 0.311368 | Elapsed 2.1m | ETA 2.1m
Epoch 310/500 | Batch 110/202 | Rec 0.000667 | Seg 0.309562 | Elapsed 2.3m | ETA 1.9m
Epoch 310/500 | Batch 120/202 | Rec 0.000649 | Seg 0.304970 | Elapsed 2.5m | ETA 1.7m
Epoch 310/500 | Batch 130/202 | Rec 0.000647 | Seg 0.299790 | Elapsed 2.7m | ETA 1.5m
Epoch 310/500 | Batch 140/202 | Rec 0.000642 | Seg 0.296619 | Elapsed 2.9m | ETA 1.3m
Epoch 310/500 | Batch 150/202 | Rec 0.000631 | Seg 0.289131 | Elapsed 3.1m | ETA 1.1m
Epoch 310/500 | Batch 160/202 | Rec 0.000634 | Seg 0.292355 | Elapsed 3.3m | ETA 0.9m
Epoch 310/500 | Batch 170/202 | Rec 0.000637 | Seg 0.294811 | Elapsed 3.5m | ETA 0.7m
Epoch 310/500 | Batch 180/202 | Rec 0.000630 | Seg 0.292563 | Elapsed 3.7m | ETA 0.5m
Epoch 310/500 | Batch 190/202 | Rec 0.000618 | Seg 0.286655 | Elapsed 3.9m | ETA 0.2m
Epoch 310/500 | Batch 200/202 | Rec 0.000612 | Seg 0.283307 | Elapsed 4.1m | ETA 0.0m
Epoch 310/500 | Batch 202/202 | Rec 0.000616 | Seg 0.285874 | Elapsed 4.2m | ETA 0.0m

2026-09-25 18:33:05,252 - INFO: Rec loss: 0.0006157224529623376
2026-09-25 18:33:05,252 - INFO: Seg loss: 0.2858743997530477
2026-09-25 18:33:05,252 - INFO: λ_rec: 1
2026-09-25 18:33:05,252 - INFO: λ_seg: 0.0001
2026-09-25 18:34:30,019 - INFO: -------------------Epoch: 310------------------------
2026-09-25 18:34:30,025 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.640119  0.973562  0.000143
2026-09-25 18:34:30,032 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995779  0.997835  0.997116  0.998656  0.995970
real potato   0.186815  0.314790  1.000000  0.186815  0.999027
fake potato   0.650156  0.787946  0.990174  0.654378  0.999743
real apple    0.644652  0.783888  0.707177  0.879390  0.998328
fake apple    0.722780  0.839036  0.946452  0.753597  0.998909
real orange   0.922366  0.959565  0.985004  0.935503  0.999896
fake orange   0.946976  0.972716  0.963360  0.982358  0.999843
real grape    0.790759  0.883105  0.964839  0.814222  0.999550
fake grape    0.886939  0.940032  0.916177  0.965268  0.999545
real lemon    0.380180  0.550871  0.399207  0.888600  0.998297
fake lemon    0.862886  0.926347  0.984654  0.874648  0.999706
real avocado  0.753623  0.859455  0.769470  0.973399  0.999704
fake avocado  0.864824  0.927463  0.998970  0.865596  0.999838
real pepper   0.777719  0.874913  0.834893  0.919072  0.999039
fake pepper   0.608432  0.756506  0.996443  0.609756  0.999065
real plant    0.864732  0.927410  0.947427  0.908317  0.998579
fake plant    0.860537  0.924991  0.940908  0.909701  0.999883
real banana   0.216276  0.355604  0.911715  0.220902  0.998201
fake banana   0.703558  0.825936  0.809509  0.843149  0.999346
real onion    0.519570  0.683788  0.718430  0.652424  0.999455
fake onion    0.905610  0.950418  0.995237  0.909553  0.999940
real unknown  0.863121  0.926482  0.909091  0.944656  0.999976
fake unknown  0.304360  0.466640  0.326065  0.820536  0.998420
total         0.705767  0.801554  0.870101  0.804804  0.999142
total(-bg)    0.692585  0.792632  0.864327  0.795993  0.999286
2026-09-25 18:34:30,633 - INFO: Epoch accounting: {'epoch': 310, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11420887, 38137, 74844, 117926, 115122, 64249, 73159, 125646, 197353, 90900, 68337, 49544, 37096, 212959, 91702, 162884, 28005, 70143, 50929, 64822, 34739, 5727, 43162], 'crops_with_class': [202, 25, 26, 29, 32, 25, 28, 29, 32, 36, 31, 19, 12, 57, 25, 20, 27, 21, 24, 26, 16, 9, 21], 'targeted_crops_by_class': [0, 3, 4, 4, 1, 2, 6, 5, 7, 5, 6, 6, 4, 5, 3, 7, 11, 7, 5, 3, 3, 3, 6], 'sampled_scene_counts': [0, 1, 4, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 2, 3, 0, 1, 0, 1, 0, 0, 2, 1, 5, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 2, 5, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 1, 0, 0, 3, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 2, 0, 0, 0, 1, 2, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 3, 1, 0, 3, 2, 2, 0, 0, 0, 2, 2, 1, 0, 1, 0, 2, 4, 2, 1, 0, 3, 3, 6, 0, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 0, 2, 1, 2, 2, 2, 2, 0, 2, 3, 0, 3, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 5, 0, 1, 1, 0, 1, 2, 2, 0, 0, 2, 2, 0, 0, 2, 1, 1, 1, 0, 0], 'learning_rate': 3.205651608561073e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006157224529623376, 'train_segmentation_loss': 0.2858743997530477, 'val_foreground_miou_all22': 0.6925849244107863, 'val_psnr_ref1': 38.6401188659668, 'elapsed_seconds': 336.6845052242279, 'peak_cuda_allocated_gib': 7.509342193603516}

Epoch 311/500 | Batch 10/202 | Rec 0.000514 | Seg 0.272790 | Elapsed 0.2m | ETA 4.1m
Epoch 311/500 | Batch 20/202 | Rec 0.000588 | Seg 0.321300 | Elapsed 0.4m | ETA 3.8m
Epoch 311/500 | Batch 30/202 | Rec 0.000568 | Seg 0.319031 | Elapsed 0.6m | ETA 3.6m
Epoch 311/500 | Batch 40/202 | Rec 0.000561 | Seg 0.306121 | Elapsed 0.8m | ETA 3.4m
Epoch 311/500 | Batch 50/202 | Rec 0.000645 | Seg 0.315613 | Elapsed 1.0m | ETA 3.2m
Epoch 311/500 | Batch 60/202 | Rec 0.000622 | Seg 0.299130 | Elapsed 1.2m | ETA 3.0m
Epoch 311/500 | Batch 70/202 | Rec 0.000639 | Seg 0.316583 | Elapsed 1.5m | ETA 2.7m
Epoch 311/500 | Batch 80/202 | Rec 0.000643 | Seg 0.315059 | Elapsed 1.7m | ETA 2.5m
Epoch 311/500 | Batch 90/202 | Rec 0.000648 | Seg 0.320878 | Elapsed 1.9m | ETA 2.3m
Epoch 311/500 | Batch 100/202 | Rec 0.000650 | Seg 0.321002 | Elapsed 2.1m | ETA 2.1m
Epoch 311/500 | Batch 110/202 | Rec 0.000647 | Seg 0.323872 | Elapsed 2.3m | ETA 1.9m
Epoch 311/500 | Batch 120/202 | Rec 0.000647 | Seg 0.325542 | Elapsed 2.5m | ETA 1.7m
Epoch 311/500 | Batch 130/202 | Rec 0.000639 | Seg 0.315757 | Elapsed 2.7m | ETA 1.5m
Epoch 311/500 | Batch 140/202 | Rec 0.000636 | Seg 0.314462 | Elapsed 2.9m | ETA 1.3m
Epoch 311/500 | Batch 150/202 | Rec 0.000642 | Seg 0.317251 | Elapsed 3.1m | ETA 1.1m
Epoch 311/500 | Batch 160/202 | Rec 0.000641 | Seg 0.314277 | Elapsed 3.3m | ETA 0.9m
Epoch 311/500 | Batch 170/202 | Rec 0.000638 | Seg 0.313939 | Elapsed 3.5m | ETA 0.7m
Epoch 311/500 | Batch 180/202 | Rec 0.000643 | Seg 0.314862 | Elapsed 3.7m | ETA 0.5m
Epoch 311/500 | Batch 190/202 | Rec 0.000644 | Seg 0.314690 | Elapsed 3.9m | ETA 0.2m
Epoch 311/500 | Batch 200/202 | Rec 0.000643 | Seg 0.314490 | Elapsed 4.1m | ETA 0.0m
Epoch 311/500 | Batch 202/202 | Rec 0.000642 | Seg 0.315560 | Elapsed 4.2m | ETA 0.0m

2026-09-25 18:38:41,729 - INFO: Rec loss: 0.0006423626316360908
2026-09-25 18:38:41,729 - INFO: Seg loss: 0.3155599175629639
2026-09-25 18:38:41,729 - INFO: λ_rec: 1
2026-09-25 18:38:41,730 - INFO: λ_seg: 0.0001
2026-09-25 18:40:04,474 - INFO: -------------------Epoch: 311------------------------
2026-09-25 18:40:04,479 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.548091  0.973808  0.000145
2026-09-25 18:40:04,487 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995855  0.997873  0.997394  0.998452  0.996043
real potato   0.618147  0.763971  0.992259  0.621143  0.999541
fake potato   0.838247  0.911957  0.973834  0.857562  0.999879
real apple    0.762405  0.865137  0.863947  0.866431  0.999068
fake apple    0.608305  0.756408  0.986736  0.613320  0.998509
real orange   0.816730  0.899071  0.990662  0.823066  0.999757
fake orange   0.899922  0.947275  0.910857  0.986835  0.999686
real grape    0.817823  0.899733  0.956923  0.849083  0.999605
fake grape    0.901104  0.947930  0.946946  0.949016  0.999615
real lemon    0.464813  0.634593  0.475783  0.952740  0.998711
fake lemon    0.855430  0.922033  0.994492  0.859502  0.999693
real avocado  0.789671  0.882427  0.811776  0.966667  0.999761
fake avocado  0.694161  0.819426  0.999633  0.694338  0.999634
real pepper   0.831492  0.907944  0.887574  0.929376  0.999311
fake pepper   0.764728  0.866631  0.971990  0.781960  0.999427
real plant    0.876372  0.934063  0.946210  0.922321  0.998699
fake plant    0.743220  0.852648  0.811429  0.898390  0.999753
real banana   0.367809  0.537765  0.860107  0.391213  0.998489
fake banana   0.715498  0.834108  0.815961  0.853185  0.999376
real onion    0.674124  0.805296  0.712393  0.926195  0.999595
fake onion    0.920192  0.958388  0.993512  0.925756  0.999949
real unknown  0.929389  0.963353  1.000000  0.929389  0.999989
fake unknown  0.240142  0.387245  0.254527  0.809489  0.997842
total         0.744591  0.838925  0.876302  0.843714  0.999214
total(-bg)    0.733169  0.831700  0.870798  0.836681  0.999359
2026-09-25 18:40:05,042 - INFO: Epoch accounting: {'epoch': 311, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11185912, 68149, 70283, 118355, 130576, 85898, 65845, 151201, 212122, 68775, 62279, 64447, 49809, 231446, 107512, 180517, 19005, 84344, 61859, 95551, 59686, 9059, 55642], 'crops_with_class': [202, 38, 28, 33, 36, 25, 24, 30, 31, 31, 25, 22, 16, 58, 27, 23, 17, 23, 30, 39, 27, 13, 25], 'targeted_crops_by_class': [0, 6, 5, 4, 5, 4, 8, 4, 2, 3, 5, 5, 7, 3, 4, 7, 3, 8, 3, 7, 7, 5, 6], 'sampled_scene_counts': [1, 1, 1, 0, 0, 0, 1, 1, 3, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 3, 0, 0, 0, 0, 0, 2, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 2, 1, 0, 0, 4, 0, 0, 3, 1, 2, 2, 1, 1, 0, 0, 0, 1, 1, 1, 0, 2, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 2, 1, 3, 2, 2, 1, 1, 3, 2, 1, 1, 0, 0, 0, 3, 1, 3, 1, 2, 1, 0, 3, 0, 1, 1, 4, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 0, 1, 1, 6, 0, 4, 0, 2, 1, 1, 1, 0, 1, 2, 1, 3, 2, 2, 2, 3, 0, 1, 0, 2, 3, 4, 2, 1, 0, 0, 2, 3, 2, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 0, 2], 'learning_rate': 3.176478793485163e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006423626316360908, 'train_segmentation_loss': 0.3155599175629639, 'val_foreground_miou_all22': 0.7331694065391943, 'val_psnr_ref1': 38.548091125488284, 'elapsed_seconds': 334.3996570110321, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 312/500 | Batch 10/202 | Rec 0.000516 | Seg 0.277023 | Elapsed 0.2m | ETA 4.0m
Epoch 312/500 | Batch 20/202 | Rec 0.000661 | Seg 0.316731 | Elapsed 0.4m | ETA 3.8m
Epoch 312/500 | Batch 30/202 | Rec 0.000636 | Seg 0.300517 | Elapsed 0.6m | ETA 3.6m
Epoch 312/500 | Batch 40/202 | Rec 0.000622 | Seg 0.308395 | Elapsed 0.8m | ETA 3.4m
Epoch 312/500 | Batch 50/202 | Rec 0.000611 | Seg 0.303857 | Elapsed 1.1m | ETA 3.2m
Epoch 312/500 | Batch 60/202 | Rec 0.000630 | Seg 0.300933 | Elapsed 1.3m | ETA 3.0m
Epoch 312/500 | Batch 70/202 | Rec 0.000628 | Seg 0.298555 | Elapsed 1.5m | ETA 2.8m
Epoch 312/500 | Batch 80/202 | Rec 0.000627 | Seg 0.299736 | Elapsed 1.7m | ETA 2.6m
Epoch 312/500 | Batch 90/202 | Rec 0.000642 | Seg 0.311330 | Elapsed 1.9m | ETA 2.4m
Epoch 312/500 | Batch 100/202 | Rec 0.000640 | Seg 0.308626 | Elapsed 2.1m | ETA 2.1m
Epoch 312/500 | Batch 110/202 | Rec 0.000637 | Seg 0.306876 | Elapsed 2.3m | ETA 1.9m
Epoch 312/500 | Batch 120/202 | Rec 0.000625 | Seg 0.302441 | Elapsed 2.5m | ETA 1.7m
Epoch 312/500 | Batch 130/202 | Rec 0.000618 | Seg 0.298190 | Elapsed 2.7m | ETA 1.5m
Epoch 312/500 | Batch 140/202 | Rec 0.000619 | Seg 0.299745 | Elapsed 2.9m | ETA 1.3m
Epoch 312/500 | Batch 150/202 | Rec 0.000626 | Seg 0.303207 | Elapsed 3.1m | ETA 1.1m
Epoch 312/500 | Batch 160/202 | Rec 0.000642 | Seg 0.301623 | Elapsed 3.4m | ETA 0.9m
Epoch 312/500 | Batch 170/202 | Rec 0.000643 | Seg 0.302713 | Elapsed 3.6m | ETA 0.7m
Epoch 312/500 | Batch 180/202 | Rec 0.000642 | Seg 0.303676 | Elapsed 3.8m | ETA 0.5m
Epoch 312/500 | Batch 190/202 | Rec 0.000641 | Seg 0.304087 | Elapsed 4.0m | ETA 0.3m
Epoch 312/500 | Batch 200/202 | Rec 0.000636 | Seg 0.302846 | Elapsed 4.2m | ETA 0.0m
Epoch 312/500 | Batch 202/202 | Rec 0.000633 | Seg 0.301001 | Elapsed 4.2m | ETA 0.0m

2026-09-25 18:44:19,116 - INFO: Rec loss: 0.0006328280281798803
2026-09-25 18:44:19,116 - INFO: Seg loss: 0.30100094040136527
2026-09-25 18:44:19,116 - INFO: λ_rec: 1
2026-09-25 18:44:19,116 - INFO: λ_seg: 0.0001
2026-09-25 18:45:39,275 - INFO: -------------------Epoch: 312------------------------
2026-09-25 18:45:39,279 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.53035  0.973708  0.000146
2026-09-25 18:45:39,286 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995610  0.997750  0.997148  0.998453  0.995809
real potato   0.813732  0.897251  0.966583  0.837286  0.999771
fake potato   0.933443  0.965526  0.982860  0.948890  0.999951
real apple    0.759741  0.863420  0.937513  0.800265  0.999127
fake apple    0.639611  0.780151  0.991096  0.643307  0.998631
real orange   0.872523  0.931873  0.987683  0.882121  0.999830
fake orange   0.911467  0.953633  0.932691  0.975642  0.999729
real grape    0.759260  0.863109  0.904533  0.825404  0.999454
fake grape    0.894731  0.944391  0.915737  0.975003  0.999576
real lemon    0.697093  0.821464  0.745216  0.915217  0.999533
fake lemon    0.841658  0.913973  0.997526  0.843419  0.999664
real avocado  0.835482  0.910318  0.859100  0.968144  0.999823
fake avocado  0.780597  0.876732  0.999673  0.780796  0.999737
real pepper   0.786378  0.880366  0.828574  0.939179  0.999067
fake pepper   0.656503  0.792589  0.959178  0.675373  0.999158
real plant    0.861461  0.925525  0.945402  0.906563  0.998542
fake plant    0.836769  0.911082  0.882638  0.941526  0.999854
real banana   0.695494  0.820353  0.903273  0.751460  0.999261
fake banana   0.741376  0.851433  0.842191  0.860982  0.999447
real onion    0.634872  0.776615  0.654733  0.954400  0.999504
fake onion    0.935492  0.966621  0.991108  0.943410  0.999959
real unknown  0.635838  0.777337  0.660440  0.944656  0.999913
fake unknown  0.251821  0.402287  0.277294  0.732706  0.998166
total         0.772650  0.861904  0.876617  0.871487  0.999283
total(-bg)    0.762516  0.855729  0.871138  0.865716  0.999441
2026-09-25 18:45:39,842 - INFO: Epoch accounting: {'epoch': 312, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11300868, 52521, 65344, 133441, 169735, 82395, 94585, 117535, 189034, 67038, 54346, 28400, 31155, 221579, 125692, 141094, 27199, 80041, 56212, 95877, 51415, 9125, 43641], 'crops_with_class': [202, 30, 27, 36, 43, 25, 33, 24, 33, 33, 23, 11, 10, 52, 29, 23, 23, 21, 24, 35, 23, 12, 23], 'targeted_crops_by_class': [0, 3, 9, 6, 4, 3, 6, 1, 3, 8, 2, 4, 3, 3, 4, 8, 3, 5, 9, 3, 3, 5, 7], 'sampled_scene_counts': [0, 0, 0, 1, 1, 1, 1, 0, 3, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 0, 0, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 1, 0, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 3, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 0, 1, 1, 1, 2, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 1, 2, 0, 1, 1, 1, 1, 2, 2, 0, 4, 0, 0, 2, 3, 1, 2, 1, 1, 5, 1, 1, 1, 2, 2, 0, 1, 1, 2, 1, 0, 2, 0, 1, 3, 2, 0, 3, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 0, 2, 0, 0, 1, 3, 2, 1, 1, 2, 0, 2, 0, 1, 2, 1, 0, 2, 3, 2, 1, 1, 2, 2, 1, 1, 2, 2], 'learning_rate': 3.147378461382715e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006328280281798803, 'train_segmentation_loss': 0.30100094040136527, 'val_foreground_miou_all22': 0.7625155362277717, 'val_psnr_ref1': 38.53035018920898, 'elapsed_seconds': 334.79088616371155, 'peak_cuda_allocated_gib': 7.513736724853516}

Epoch 313/500 | Batch 10/202 | Rec 0.000473 | Seg 0.207477 | Elapsed 0.2m | ETA 4.0m
Epoch 313/500 | Batch 20/202 | Rec 0.000495 | Seg 0.238795 | Elapsed 0.4m | ETA 3.7m
Epoch 313/500 | Batch 30/202 | Rec 0.000560 | Seg 0.280898 | Elapsed 0.6m | ETA 3.5m
Epoch 313/500 | Batch 40/202 | Rec 0.000559 | Seg 0.276809 | Elapsed 0.8m | ETA 3.3m
Epoch 313/500 | Batch 50/202 | Rec 0.000560 | Seg 0.274967 | Elapsed 1.0m | ETA 3.2m
Epoch 313/500 | Batch 60/202 | Rec 0.000568 | Seg 0.271004 | Elapsed 1.2m | ETA 3.0m
Epoch 313/500 | Batch 70/202 | Rec 0.000593 | Seg 0.277409 | Elapsed 1.5m | ETA 2.7m
Epoch 313/500 | Batch 80/202 | Rec 0.000585 | Seg 0.276008 | Elapsed 1.7m | ETA 2.5m
Epoch 313/500 | Batch 90/202 | Rec 0.000597 | Seg 0.286703 | Elapsed 1.9m | ETA 2.3m
Epoch 313/500 | Batch 100/202 | Rec 0.000604 | Seg 0.287917 | Elapsed 2.1m | ETA 2.1m
Epoch 313/500 | Batch 110/202 | Rec 0.000602 | Seg 0.290232 | Elapsed 2.3m | ETA 1.9m
Epoch 313/500 | Batch 120/202 | Rec 0.000620 | Seg 0.297034 | Elapsed 2.5m | ETA 1.7m
Epoch 313/500 | Batch 130/202 | Rec 0.000621 | Seg 0.299287 | Elapsed 2.7m | ETA 1.5m
Epoch 313/500 | Batch 140/202 | Rec 0.000615 | Seg 0.294925 | Elapsed 2.9m | ETA 1.3m
Epoch 313/500 | Batch 150/202 | Rec 0.000619 | Seg 0.297687 | Elapsed 3.1m | ETA 1.1m
Epoch 313/500 | Batch 160/202 | Rec 0.000619 | Seg 0.302158 | Elapsed 3.3m | ETA 0.9m
Epoch 313/500 | Batch 170/202 | Rec 0.000637 | Seg 0.312208 | Elapsed 3.5m | ETA 0.7m
Epoch 313/500 | Batch 180/202 | Rec 0.000632 | Seg 0.310752 | Elapsed 3.7m | ETA 0.5m
Epoch 313/500 | Batch 190/202 | Rec 0.000631 | Seg 0.309399 | Elapsed 3.9m | ETA 0.2m
Epoch 313/500 | Batch 200/202 | Rec 0.000636 | Seg 0.310618 | Elapsed 4.1m | ETA 0.0m
Epoch 313/500 | Batch 202/202 | Rec 0.000636 | Seg 0.310029 | Elapsed 4.2m | ETA 0.0m

2026-09-25 18:49:51,149 - INFO: Rec loss: 0.0006355209840723258
2026-09-25 18:49:51,149 - INFO: Seg loss: 0.31002870462097154
2026-09-25 18:49:51,149 - INFO: λ_rec: 1
2026-09-25 18:49:51,150 - INFO: λ_seg: 0.0001
2026-09-25 18:51:13,665 - INFO: -------------------Epoch: 313------------------------
2026-09-25 18:51:13,669 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.693611  0.973547  0.00014
2026-09-25 18:51:13,677 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995556  0.997723  0.997321  0.998225  0.995758
real potato   0.706712  0.828107  0.982665  0.715634  0.999645
fake potato   0.716406  0.834725  0.978053  0.728111  0.999790
real apple    0.747922  0.855734  0.895266  0.819637  0.999047
fake apple    0.623370  0.767948  0.978779  0.631911  0.998559
real orange   0.945668  0.972026  0.995991  0.949282  0.999928
fake orange   0.951546  0.975122  0.966593  0.983904  0.999857
real grape    0.690160  0.816631  0.948386  0.717094  0.999328
fake grape    0.856598  0.922711  0.878041  0.972281  0.999398
real lemon    0.554728  0.713554  0.575963  0.937679  0.999115
fake lemon    0.846547  0.916848  0.998132  0.847890  0.999675
real avocado  0.846837  0.917017  0.868467  0.971429  0.999837
fake avocado  0.795411  0.886000  0.999519  0.795715  0.999755
real pepper   0.845616  0.916301  0.886946  0.947772  0.999367
fake pepper   0.769710  0.869822  0.965851  0.791243  0.999436
real plant    0.839224  0.912535  0.926575  0.899011  0.998277
fake plant    0.879892  0.936059  0.936828  0.935391  0.999898
real banana   0.562837  0.720228  0.880333  0.609466  0.998936
fake banana   0.737045  0.848569  0.825555  0.873009  0.999427
real onion    0.662946  0.797267  0.680267  0.963013  0.999558
fake onion    0.945537  0.971956  0.991696  0.953083  0.999965
real unknown  0.685495  0.813356  0.718042  0.937977  0.999931
fake unknown  0.227413  0.370520  0.244834  0.761681  0.997820
total         0.757964  0.850468  0.874787  0.858280  0.999231
total(-bg)    0.747164  0.843774  0.869217  0.851919  0.999389
2026-09-25 18:51:14,270 - INFO: Epoch accounting: {'epoch': 313, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11245892, 45961, 56743, 137847, 164136, 50818, 47744, 173420, 193603, 72875, 77896, 43098, 55530, 245951, 88543, 173453, 26989, 73586, 75013, 75729, 53522, 8264, 51659], 'crops_with_class': [202, 31, 26, 37, 39, 17, 18, 34, 35, 29, 32, 17, 19, 63, 28, 23, 22, 25, 29, 32, 23, 10, 26], 'targeted_crops_by_class': [0, 2, 5, 5, 6, 4, 0, 6, 5, 2, 6, 8, 9, 7, 3, 5, 5, 4, 6, 3, 6, 4, 8], 'sampled_scene_counts': [2, 0, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 1, 3, 1, 2, 2, 1, 1, 1, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 2, 0, 1, 2, 3, 0, 1, 4, 2, 2, 2, 2, 3, 1, 1, 1, 1, 0, 2, 3, 3, 1, 1, 1, 1, 3, 0, 1, 1, 1, 3, 2, 1, 1, 3, 1, 1, 2, 2, 3, 2, 1, 1, 2, 0, 2, 0, 1, 2, 2, 0, 1, 0, 1, 1, 4, 1, 2, 1, 4, 1, 1, 3, 2, 1, 1, 1, 0, 4, 0, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 1, 1], 'learning_rate': 3.118351761085011e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006355209840723258, 'train_segmentation_loss': 0.31002870462097154, 'val_foreground_miou_all22': 0.7471644948835476, 'val_psnr_ref1': 38.693610992431644, 'elapsed_seconds': 334.4196546077728, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 314/500 | Batch 10/202 | Rec 0.001055 | Seg 0.391062 | Elapsed 0.2m | ETA 4.2m
Epoch 314/500 | Batch 20/202 | Rec 0.000895 | Seg 0.350442 | Elapsed 0.4m | ETA 3.9m
Epoch 314/500 | Batch 30/202 | Rec 0.000797 | Seg 0.326355 | Elapsed 0.6m | ETA 3.7m
Epoch 314/500 | Batch 40/202 | Rec 0.000834 | Seg 0.329074 | Elapsed 0.9m | ETA 3.5m
Epoch 314/500 | Batch 50/202 | Rec 0.000816 | Seg 0.318077 | Elapsed 1.1m | ETA 3.2m
Epoch 314/500 | Batch 60/202 | Rec 0.000802 | Seg 0.313342 | Elapsed 1.3m | ETA 3.0m
Epoch 314/500 | Batch 70/202 | Rec 0.000789 | Seg 0.308775 | Elapsed 1.5m | ETA 2.8m
Epoch 314/500 | Batch 80/202 | Rec 0.000767 | Seg 0.308687 | Elapsed 1.7m | ETA 2.6m
Epoch 314/500 | Batch 90/202 | Rec 0.000734 | Seg 0.303511 | Elapsed 1.9m | ETA 2.4m
Epoch 314/500 | Batch 100/202 | Rec 0.000726 | Seg 0.301230 | Elapsed 2.1m | ETA 2.2m
Epoch 314/500 | Batch 110/202 | Rec 0.000722 | Seg 0.306864 | Elapsed 2.3m | ETA 1.9m
Epoch 314/500 | Batch 120/202 | Rec 0.000710 | Seg 0.303172 | Elapsed 2.5m | ETA 1.7m
Epoch 314/500 | Batch 130/202 | Rec 0.000721 | Seg 0.305163 | Elapsed 2.7m | ETA 1.5m
Epoch 314/500 | Batch 140/202 | Rec 0.000710 | Seg 0.305976 | Elapsed 3.0m | ETA 1.3m
Epoch 314/500 | Batch 150/202 | Rec 0.000709 | Seg 0.306462 | Elapsed 3.2m | ETA 1.1m
Epoch 314/500 | Batch 160/202 | Rec 0.000703 | Seg 0.303019 | Elapsed 3.4m | ETA 0.9m
Epoch 314/500 | Batch 170/202 | Rec 0.000697 | Seg 0.302894 | Elapsed 3.6m | ETA 0.7m
Epoch 314/500 | Batch 180/202 | Rec 0.000688 | Seg 0.301581 | Elapsed 3.8m | ETA 0.5m
Epoch 314/500 | Batch 190/202 | Rec 0.000685 | Seg 0.299162 | Elapsed 4.0m | ETA 0.3m
Epoch 314/500 | Batch 200/202 | Rec 0.000684 | Seg 0.299161 | Elapsed 4.2m | ETA 0.0m
Epoch 314/500 | Batch 202/202 | Rec 0.000682 | Seg 0.298446 | Elapsed 4.3m | ETA 0.0m

2026-09-25 18:55:29,292 - INFO: Rec loss: 0.0006818079731385639
2026-09-25 18:55:29,293 - INFO: Seg loss: 0.2984455331127242
2026-09-25 18:55:29,293 - INFO: λ_rec: 1
2026-09-25 18:55:29,293 - INFO: λ_seg: 0.0001
2026-09-25 18:56:51,911 - INFO: -------------------Epoch: 314------------------------
2026-09-25 18:56:51,916 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.681474  0.974039  0.000141
2026-09-25 18:56:51,925 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995623  0.997757  0.997123  0.998491  0.995821
real potato   0.786721  0.880581  0.962778  0.811400  0.999737
fake potato   0.780363  0.876584  0.968338  0.800796  0.999836
real apple    0.769331  0.869579  0.906491  0.835648  0.999136
fake apple    0.578034  0.732554  0.992811  0.580464  0.998400
real orange   0.946183  0.972298  0.997201  0.948703  0.999929
fake orange   0.935185  0.966457  0.971004  0.962051  0.999809
real grape    0.794144  0.885212  0.935111  0.840459  0.999545
fake grape    0.888262  0.940775  0.933772  0.947985  0.999559
real lemon    0.594685  0.745786  0.617527  0.941444  0.999246
fake lemon    0.765105  0.866874  0.999529  0.765380  0.999503
real avocado  0.884062  0.938414  0.918685  0.959113  0.999883
fake avocado  0.745028  0.853838  0.999658  0.745218  0.999695
real pepper   0.752952  0.859018  0.777234  0.960162  0.998848
fake pepper   0.569224  0.725437  0.934875  0.592728  0.998931
real plant    0.876833  0.934325  0.941172  0.927676  0.998697
fake plant    0.804890  0.891849  0.858740  0.927722  0.999821
real banana   0.595670  0.746559  0.890646  0.642673  0.999020
fake banana   0.698690  0.822572  0.793814  0.853600  0.999323
real onion    0.618462  0.764209  0.695117  0.848674  0.999527
fake onion    0.942262  0.970223  0.990181  0.951149  0.999963
real unknown  0.777065  0.874499  0.829623  0.924618  0.999958
fake unknown  0.208417  0.344904  0.231523  0.676204  0.997836
total         0.752487  0.846100  0.875781  0.845320  0.999218
total(-bg)    0.741435  0.839207  0.870265  0.838358  0.999373
2026-09-25 18:56:52,516 - INFO: Epoch accounting: {'epoch': 314, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11311610, 63085, 65713, 115916, 124510, 99838, 60246, 136746, 143877, 61007, 47147, 31028, 39556, 238798, 125258, 183017, 18135, 78861, 68733, 103922, 68275, 11004, 41990], 'crops_with_class': [202, 35, 27, 28, 26, 24, 24, 29, 28, 28, 20, 12, 15, 59, 31, 22, 20, 27, 29, 42, 28, 11, 21], 'targeted_crops_by_class': [0, 4, 4, 5, 8, 4, 6, 6, 3, 4, 2, 2, 5, 7, 2, 4, 6, 5, 8, 8, 5, 2, 2], 'sampled_scene_counts': [1, 1, 0, 1, 0, 0, 0, 1, 2, 1, 0, 1, 0, 0, 2, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 2, 0, 2, 0, 3, 1, 0, 0, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 0, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2, 1, 0, 3, 1, 0, 0, 1, 1, 2, 0, 0, 3, 0, 1, 3, 1, 1, 2, 2, 1, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 2, 3, 1, 3, 5, 2, 1, 1, 2, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0, 0, 0, 1, 4, 3, 1, 2, 1, 1, 3, 0, 0, 3, 2, 3, 0, 2, 3, 0, 3, 2, 1, 1, 2, 3, 0], 'learning_rate': 3.089399838516479e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006818079731385639, 'train_segmentation_loss': 0.2984455331127242, 'val_foreground_miou_all22': 0.741434914438176, 'val_psnr_ref1': 38.68147354125976, 'elapsed_seconds': 338.23716378211975, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 315/500 | Batch 10/202 | Rec 0.000818 | Seg 0.340575 | Elapsed 0.2m | ETA 4.2m
Epoch 315/500 | Batch 20/202 | Rec 0.000697 | Seg 0.292679 | Elapsed 0.4m | ETA 4.0m
Epoch 315/500 | Batch 30/202 | Rec 0.000655 | Seg 0.290320 | Elapsed 0.6m | ETA 3.7m
Epoch 315/500 | Batch 40/202 | Rec 0.000642 | Seg 0.295431 | Elapsed 0.9m | ETA 3.5m
Epoch 315/500 | Batch 50/202 | Rec 0.000610 | Seg 0.281126 | Elapsed 1.1m | ETA 3.3m
Epoch 315/500 | Batch 60/202 | Rec 0.000613 | Seg 0.280139 | Elapsed 1.3m | ETA 3.0m
Epoch 315/500 | Batch 70/202 | Rec 0.000620 | Seg 0.288177 | Elapsed 1.5m | ETA 2.8m
Epoch 315/500 | Batch 80/202 | Rec 0.000607 | Seg 0.288739 | Elapsed 1.7m | ETA 2.6m
Epoch 315/500 | Batch 90/202 | Rec 0.000603 | Seg 0.287864 | Elapsed 1.9m | ETA 2.4m
Epoch 315/500 | Batch 100/202 | Rec 0.000612 | Seg 0.300984 | Elapsed 2.1m | ETA 2.2m
Epoch 315/500 | Batch 110/202 | Rec 0.000620 | Seg 0.301080 | Elapsed 2.3m | ETA 2.0m
Epoch 315/500 | Batch 120/202 | Rec 0.000625 | Seg 0.308051 | Elapsed 2.6m | ETA 1.7m
Epoch 315/500 | Batch 130/202 | Rec 0.000618 | Seg 0.305236 | Elapsed 2.8m | ETA 1.5m
Epoch 315/500 | Batch 140/202 | Rec 0.000623 | Seg 0.302012 | Elapsed 3.0m | ETA 1.3m
Epoch 315/500 | Batch 150/202 | Rec 0.000619 | Seg 0.302177 | Elapsed 3.2m | ETA 1.1m
Epoch 315/500 | Batch 160/202 | Rec 0.000614 | Seg 0.298887 | Elapsed 3.4m | ETA 0.9m
Epoch 315/500 | Batch 170/202 | Rec 0.000614 | Seg 0.298905 | Elapsed 3.6m | ETA 0.7m
Epoch 315/500 | Batch 180/202 | Rec 0.000614 | Seg 0.296345 | Elapsed 3.8m | ETA 0.5m
Epoch 315/500 | Batch 190/202 | Rec 0.000619 | Seg 0.296255 | Elapsed 4.0m | ETA 0.3m
Epoch 315/500 | Batch 200/202 | Rec 0.000621 | Seg 0.299295 | Elapsed 4.2m | ETA 0.0m
Epoch 315/500 | Batch 202/202 | Rec 0.000626 | Seg 0.301841 | Elapsed 4.3m | ETA 0.0m

2026-09-25 19:01:09,916 - INFO: Rec loss: 0.0006259875014737839
2026-09-25 19:01:09,916 - INFO: Seg loss: 0.3018411534773831
2026-09-25 19:01:09,916 - INFO: λ_rec: 1
2026-09-25 19:01:09,916 - INFO: λ_seg: 0.0001
2026-09-25 19:02:33,741 - INFO: -------------------Epoch: 315------------------------
2026-09-25 19:02:33,745 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.801663  0.973735  0.000138
2026-09-25 19:02:33,753 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995767  0.997829  0.997165  0.998594  0.995958
real potato   0.875127  0.933356  0.996813  0.877582  0.999850
fake potato   0.955212  0.977043  0.971429  0.982824  0.999966
real apple    0.790034  0.882653  0.938609  0.833083  0.999236
fake apple    0.623790  0.768266  0.984218  0.630092  0.998565
real orange   0.906236  0.950762  0.996951  0.908754  0.999876
fake orange   0.935427  0.966587  0.965045  0.968234  0.999809
real grape    0.819086  0.900497  0.975695  0.836147  0.999614
fake grape    0.883709  0.938215  0.925246  0.951656  0.999537
real lemon    0.478647  0.647364  0.532096  0.826539  0.998942
fake lemon    0.824166  0.903559  0.969427  0.846159  0.999618
real avocado  0.878380  0.935203  0.916601  0.954680  0.999877
fake avocado  0.795156  0.885841  0.999519  0.795460  0.999755
real pepper   0.856120  0.922433  0.890052  0.957367  0.999411
fake pepper   0.797043  0.887011  0.928711  0.848985  0.999485
real plant    0.878339  0.935180  0.954334  0.916875  0.998730
fake plant    0.821716  0.902084  0.885077  0.919862  0.999841
real banana   0.516183  0.680851  0.895956  0.549097  0.998844
fake banana   0.651877  0.789207  0.721299  0.871350  0.999144
real onion    0.646277  0.785088  0.704359  0.886843  0.999561
fake onion    0.912572  0.954238  0.951877  0.956711  0.999942
real unknown  0.941794  0.969975  1.000000  0.941794  0.999991
fake unknown  0.231971  0.376544  0.266346  0.642521  0.998208
total         0.783245  0.864773  0.885514  0.865270  0.999294
total(-bg)    0.773585  0.858725  0.880439  0.859210  0.999446
2026-09-25 19:02:34,389 - INFO: Epoch accounting: {'epoch': 315, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11241511, 46790, 67349, 162148, 102595, 85708, 74797, 164941, 253898, 84405, 55145, 33857, 24517, 217783, 118246, 135998, 23277, 73134, 79722, 92750, 62515, 8931, 28255], 'crops_with_class': [202, 26, 30, 36, 32, 23, 29, 28, 45, 35, 23, 11, 8, 52, 30, 17, 19, 22, 35, 41, 27, 10, 16], 'targeted_crops_by_class': [0, 2, 6, 4, 2, 4, 2, 6, 10, 2, 7, 6, 3, 7, 3, 3, 2, 10, 7, 5, 5, 2, 4], 'sampled_scene_counts': [0, 1, 1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 2, 0, 2, 0, 0, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 0, 2, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 3, 2, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 2, 1, 2, 2, 0, 2, 1, 4, 1, 0, 1, 1, 1, 3, 1, 3, 1, 1, 2, 1, 0, 0, 1, 1, 2, 2, 2, 3, 1, 1, 1, 1, 0, 2, 2, 0, 2, 0, 1, 2, 3, 2, 0, 0, 1, 2, 1, 0, 1, 2, 0, 3, 1, 0, 1, 0, 3, 1, 2, 1, 1, 1, 0, 2, 2, 2, 3, 2, 2, 2, 3, 3, 0, 1, 0, 3, 2, 1, 3, 0, 2], 'learning_rate': 3.060523836649448e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006259875014737839, 'train_segmentation_loss': 0.3018411534773831, 'val_foreground_miou_all22': 0.7735846564765244, 'val_psnr_ref1': 38.801663360595704, 'elapsed_seconds': 341.86304569244385, 'peak_cuda_allocated_gib': 7.509830474853516}

Epoch 316/500 | Batch 10/202 | Rec 0.000626 | Seg 0.263865 | Elapsed 0.2m | ETA 4.3m
Epoch 316/500 | Batch 20/202 | Rec 0.000593 | Seg 0.258125 | Elapsed 0.4m | ETA 4.0m
Epoch 316/500 | Batch 30/202 | Rec 0.000655 | Seg 0.292484 | Elapsed 0.6m | ETA 3.7m
Epoch 316/500 | Batch 40/202 | Rec 0.000641 | Seg 0.297550 | Elapsed 0.8m | ETA 3.4m
Epoch 316/500 | Batch 50/202 | Rec 0.000665 | Seg 0.315935 | Elapsed 1.1m | ETA 3.2m
Epoch 316/500 | Batch 60/202 | Rec 0.000641 | Seg 0.309181 | Elapsed 1.3m | ETA 3.0m
Epoch 316/500 | Batch 70/202 | Rec 0.000647 | Seg 0.303158 | Elapsed 1.5m | ETA 2.8m
Epoch 316/500 | Batch 80/202 | Rec 0.000632 | Seg 0.297907 | Elapsed 1.7m | ETA 2.6m
Epoch 316/500 | Batch 90/202 | Rec 0.000638 | Seg 0.298186 | Elapsed 1.9m | ETA 2.4m
Epoch 316/500 | Batch 100/202 | Rec 0.000643 | Seg 0.296867 | Elapsed 2.1m | ETA 2.2m
Epoch 316/500 | Batch 110/202 | Rec 0.000635 | Seg 0.296027 | Elapsed 2.3m | ETA 1.9m
Epoch 316/500 | Batch 120/202 | Rec 0.000638 | Seg 0.296589 | Elapsed 2.5m | ETA 1.7m
Epoch 316/500 | Batch 130/202 | Rec 0.000632 | Seg 0.295229 | Elapsed 2.8m | ETA 1.5m
Epoch 316/500 | Batch 140/202 | Rec 0.000632 | Seg 0.295251 | Elapsed 3.0m | ETA 1.3m
Epoch 316/500 | Batch 150/202 | Rec 0.000639 | Seg 0.299149 | Elapsed 3.2m | ETA 1.1m
Epoch 316/500 | Batch 160/202 | Rec 0.000653 | Seg 0.298106 | Elapsed 3.4m | ETA 0.9m
Epoch 316/500 | Batch 170/202 | Rec 0.000654 | Seg 0.299222 | Elapsed 3.6m | ETA 0.7m
Epoch 316/500 | Batch 180/202 | Rec 0.000649 | Seg 0.298151 | Elapsed 3.8m | ETA 0.5m
Epoch 316/500 | Batch 190/202 | Rec 0.000655 | Seg 0.304386 | Elapsed 4.0m | ETA 0.3m
Epoch 316/500 | Batch 200/202 | Rec 0.000653 | Seg 0.304981 | Elapsed 4.2m | ETA 0.0m
Epoch 316/500 | Batch 202/202 | Rec 0.000652 | Seg 0.304381 | Elapsed 4.3m | ETA 0.0m

2026-09-25 19:06:50,542 - INFO: Rec loss: 0.0006524280241245662
2026-09-25 19:06:50,543 - INFO: Seg loss: 0.3043808436187187
2026-09-25 19:06:50,543 - INFO: λ_rec: 1
2026-09-25 19:06:50,543 - INFO: λ_seg: 0.0001
2026-09-25 19:08:12,025 - INFO: -------------------Epoch: 316------------------------
2026-09-25 19:08:12,029 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.551889  0.97387  0.000146
2026-09-25 19:08:12,037 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995793  0.997842  0.997552  0.998232  0.995985
real potato   0.329635  0.495791  1.000000  0.329635  0.999198
fake potato   0.646400  0.785180  0.985759  0.652493  0.999740
real apple    0.685203  0.813149  0.763521  0.869792  0.998621
fake apple    0.658339  0.793926  0.959139  0.677336  0.998673
real orange   0.861166  0.925355  0.996129  0.864057  0.999816
fake orange   0.919966  0.958265  0.936778  0.980866  0.999756
real grape    0.790806  0.883134  0.953956  0.822188  0.999546
fake grape    0.862697  0.926238  0.888447  0.967496  0.999430
real lemon    0.399656  0.571036  0.410786  0.936510  0.998347
fake lemon    0.854103  0.921261  0.988593  0.862604  0.999688
real avocado  0.789823  0.882521  0.817940  0.958292  0.999763
fake avocado  0.646961  0.785595  0.998623  0.647539  0.999577
real pepper   0.846266  0.916682  0.911328  0.922201  0.999387
fake pepper   0.802289  0.890250  0.991437  0.807887  0.999525
real plant    0.874810  0.933175  0.935629  0.930834  0.998668
fake plant    0.806050  0.892561  0.867269  0.919479  0.999824
real banana   0.224256  0.366321  0.867987  0.232174  0.998195
fake banana   0.690811  0.817086  0.778420  0.859904  0.999292
real onion    0.587457  0.740073  0.710776  0.771998  0.999510
fake onion    0.884699  0.938772  0.992455  0.890689  0.999927
real unknown  0.924905  0.960938  0.995906  0.928435  0.999988
fake unknown  0.257534  0.409549  0.267570  0.872872  0.997880
total         0.710418  0.808900  0.870261  0.813196  0.999145
total(-bg)    0.697447  0.800312  0.864475  0.804785  0.999289
2026-09-25 19:08:12,674 - INFO: Epoch accounting: {'epoch': 316, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11243330, 44563, 58672, 177353, 114370, 77734, 49382, 151910, 124596, 69371, 77114, 33757, 21748, 271886, 146007, 163198, 33548, 96330, 73351, 83601, 61771, 11055, 53625], 'crops_with_class': [202, 30, 27, 43, 28, 29, 19, 31, 26, 37, 35, 12, 9, 62, 39, 21, 29, 26, 30, 38, 29, 11, 24], 'targeted_crops_by_class': [0, 5, 7, 11, 7, 7, 4, 5, 1, 2, 5, 2, 3, 2, 3, 2, 9, 4, 6, 6, 7, 6, 5], 'sampled_scene_counts': [1, 1, 2, 0, 1, 1, 1, 1, 1, 2, 0, 1, 0, 2, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 2, 0, 1, 2, 0, 3, 3, 1, 1, 0, 0, 1, 1, 1, 1, 3, 1, 1, 2, 0, 1, 2, 1, 2, 1, 0, 2, 2, 2, 1, 1, 3, 0, 0, 3, 0, 1, 1, 3, 1, 4, 1, 2, 3, 2, 4, 3, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 1, 5, 3, 0, 1, 1, 1, 0, 1, 0, 3, 0, 3, 1, 2, 1, 1, 4, 2, 0, 1, 2, 2, 2, 3, 2, 1, 1], 'learning_rate': 3.031724895459025e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006524280241245662, 'train_segmentation_loss': 0.3043808436187187, 'val_foreground_miou_all22': 0.6974467676023202, 'val_psnr_ref1': 38.55188873291016, 'elapsed_seconds': 338.27565264701843, 'peak_cuda_allocated_gib': 7.505405426025391}

Epoch 317/500 | Batch 10/202 | Rec 0.000701 | Seg 0.333746 | Elapsed 0.2m | ETA 4.2m
Epoch 317/500 | Batch 20/202 | Rec 0.000662 | Seg 0.320261 | Elapsed 0.4m | ETA 3.9m
Epoch 317/500 | Batch 30/202 | Rec 0.000650 | Seg 0.308044 | Elapsed 0.6m | ETA 3.7m
Epoch 317/500 | Batch 40/202 | Rec 0.000614 | Seg 0.298598 | Elapsed 0.9m | ETA 3.5m
Epoch 317/500 | Batch 50/202 | Rec 0.000645 | Seg 0.298585 | Elapsed 1.1m | ETA 3.2m
Epoch 317/500 | Batch 60/202 | Rec 0.000645 | Seg 0.299221 | Elapsed 1.3m | ETA 3.1m
Epoch 317/500 | Batch 70/202 | Rec 0.000658 | Seg 0.308551 | Elapsed 1.5m | ETA 2.8m
Epoch 317/500 | Batch 80/202 | Rec 0.000644 | Seg 0.300699 | Elapsed 1.7m | ETA 2.6m
Epoch 317/500 | Batch 90/202 | Rec 0.000673 | Seg 0.300594 | Elapsed 1.9m | ETA 2.4m
Epoch 317/500 | Batch 100/202 | Rec 0.000676 | Seg 0.302541 | Elapsed 2.1m | ETA 2.2m
Epoch 317/500 | Batch 110/202 | Rec 0.000664 | Seg 0.300483 | Elapsed 2.3m | ETA 2.0m
Epoch 317/500 | Batch 120/202 | Rec 0.000662 | Seg 0.295116 | Elapsed 2.6m | ETA 1.7m
Epoch 317/500 | Batch 130/202 | Rec 0.000662 | Seg 0.294297 | Elapsed 2.8m | ETA 1.5m
Epoch 317/500 | Batch 140/202 | Rec 0.000659 | Seg 0.294841 | Elapsed 3.0m | ETA 1.3m
Epoch 317/500 | Batch 150/202 | Rec 0.000655 | Seg 0.291859 | Elapsed 3.2m | ETA 1.1m
Epoch 317/500 | Batch 160/202 | Rec 0.000652 | Seg 0.292646 | Elapsed 3.4m | ETA 0.9m
Epoch 317/500 | Batch 170/202 | Rec 0.000657 | Seg 0.297855 | Elapsed 3.6m | ETA 0.7m
Epoch 317/500 | Batch 180/202 | Rec 0.000658 | Seg 0.294095 | Elapsed 3.8m | ETA 0.5m
Epoch 317/500 | Batch 190/202 | Rec 0.000657 | Seg 0.297478 | Elapsed 4.0m | ETA 0.3m
Epoch 317/500 | Batch 200/202 | Rec 0.000657 | Seg 0.298242 | Elapsed 4.2m | ETA 0.0m
Epoch 317/500 | Batch 202/202 | Rec 0.000656 | Seg 0.298721 | Elapsed 4.3m | ETA 0.0m

2026-09-25 19:12:29,219 - INFO: Rec loss: 0.0006563244973186007
2026-09-25 19:12:29,219 - INFO: Seg loss: 0.2987210449974726
2026-09-25 19:12:29,219 - INFO: λ_rec: 1
2026-09-25 19:12:29,219 - INFO: λ_seg: 0.0001
2026-09-25 19:13:47,913 - INFO: -------------------Epoch: 317------------------------
2026-09-25 19:13:47,917 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.682525  0.97374  0.000141
2026-09-25 19:13:47,925 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995501  0.997696  0.996521  0.998974  0.995702
real potato   0.716703  0.834927  0.996639  0.718439  0.999660
fake potato   0.850495  0.919158  0.939619  0.899665  0.999885
real apple    0.766974  0.868072  0.900090  0.838346  0.999121
fake apple    0.621846  0.766789  0.966679  0.635467  0.998541
real orange   0.868945  0.929828  0.992770  0.874479  0.999826
fake orange   0.912884  0.954408  0.942433  0.966795  0.999736
real grape    0.792531  0.884209  0.965320  0.815757  0.999554
fake grape    0.894140  0.944062  0.929525  0.959163  0.999580
real lemon    0.490036  0.657704  0.520290  0.893924  0.998907
fake lemon    0.840990  0.913578  0.968341  0.864767  0.999654
real avocado  0.887201  0.940179  0.931368  0.949261  0.999888
fake avocado  0.855704  0.922192  0.999553  0.856032  0.999827
real pepper   0.849501  0.918577  0.888145  0.951276  0.999384
fake pepper   0.755169  0.860459  0.944525  0.790218  0.999389
real plant    0.846804  0.916998  0.961884  0.876205  0.998414
fake plant    0.872791  0.932025  0.956425  0.908934  0.999895
real banana   0.460818  0.630859  0.927649  0.477998  0.998743
fake banana   0.717908  0.835744  0.837989  0.833610  0.999397
real onion    0.685899  0.813640  0.722273  0.931599  0.999615
fake onion    0.928774  0.963022  0.974029  0.952358  0.999954
real unknown  0.915799  0.955999  0.990788  0.923664  0.999986
fake unknown  0.234343  0.379665  0.264576  0.672220  0.998149
total         0.772250  0.858252  0.892062  0.851702  0.999253
total(-bg)    0.762102  0.851913  0.887314  0.845008  0.999414
2026-09-25 19:13:48,521 - INFO: Epoch accounting: {'epoch': 317, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11301584, 35947, 61116, 144668, 122067, 74731, 55437, 122522, 195773, 70899, 72059, 46030, 53108, 192197, 145758, 133160, 31529, 99074, 77524, 87947, 64481, 8016, 42645], 'crops_with_class': [202, 23, 32, 36, 34, 21, 20, 22, 37, 29, 29, 16, 17, 45, 40, 19, 27, 24, 31, 38, 31, 8, 18], 'targeted_crops_by_class': [0, 2, 2, 3, 5, 2, 3, 3, 5, 3, 5, 2, 10, 4, 8, 4, 6, 2, 5, 8, 5, 3, 6], 'sampled_scene_counts': [1, 0, 2, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 0, 0, 1, 1, 1, 2, 0, 1, 3, 2, 1, 0, 0, 1, 1, 2, 1, 1, 0, 0, 1, 0, 2, 0, 1, 1, 0, 0, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 4, 0, 2, 2, 1, 1, 0, 1, 2, 1, 0, 3, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 3, 0, 0, 2, 1, 1, 0, 1, 2, 1, 0, 3, 1, 1, 1, 0, 2, 1, 3, 5, 1, 2, 2, 1, 2, 2, 1, 0, 2, 0, 2, 4, 1, 0, 1, 0, 3, 1, 2, 0, 1, 0, 1, 2, 1, 2, 2, 4, 2, 2, 0, 1, 2, 2, 1, 0, 3, 2, 2], 'learning_rate': 3.0030041518781013e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006563244973186007, 'train_segmentation_loss': 0.2987210449974726, 'val_foreground_miou_all22': 0.7621024912010186, 'val_psnr_ref1': 38.68252532958984, 'elapsed_seconds': 335.837765455246, 'peak_cuda_allocated_gib': 7.512241363525391}

Epoch 318/500 | Batch 10/202 | Rec 0.000626 | Seg 0.318883 | Elapsed 0.2m | ETA 4.2m
Epoch 318/500 | Batch 20/202 | Rec 0.000576 | Seg 0.300291 | Elapsed 0.4m | ETA 3.9m
Epoch 318/500 | Batch 30/202 | Rec 0.000590 | Seg 0.297298 | Elapsed 0.6m | ETA 3.7m
Epoch 318/500 | Batch 40/202 | Rec 0.000598 | Seg 0.306749 | Elapsed 0.9m | ETA 3.5m
Epoch 318/500 | Batch 50/202 | Rec 0.000614 | Seg 0.316820 | Elapsed 1.1m | ETA 3.2m
Epoch 318/500 | Batch 60/202 | Rec 0.000597 | Seg 0.307199 | Elapsed 1.3m | ETA 3.0m
Epoch 318/500 | Batch 70/202 | Rec 0.000593 | Seg 0.312042 | Elapsed 1.5m | ETA 2.8m
Epoch 318/500 | Batch 80/202 | Rec 0.000588 | Seg 0.311538 | Elapsed 1.7m | ETA 2.6m
Epoch 318/500 | Batch 90/202 | Rec 0.000613 | Seg 0.320867 | Elapsed 1.9m | ETA 2.4m
Epoch 318/500 | Batch 100/202 | Rec 0.000621 | Seg 0.321156 | Elapsed 2.1m | ETA 2.2m
Epoch 318/500 | Batch 110/202 | Rec 0.000625 | Seg 0.317624 | Elapsed 2.3m | ETA 2.0m
Epoch 318/500 | Batch 120/202 | Rec 0.000630 | Seg 0.317115 | Elapsed 2.6m | ETA 1.7m
Epoch 318/500 | Batch 130/202 | Rec 0.000621 | Seg 0.308946 | Elapsed 2.8m | ETA 1.5m
Epoch 318/500 | Batch 140/202 | Rec 0.000616 | Seg 0.306522 | Elapsed 3.0m | ETA 1.3m
Epoch 318/500 | Batch 150/202 | Rec 0.000620 | Seg 0.308858 | Elapsed 3.2m | ETA 1.1m
Epoch 318/500 | Batch 160/202 | Rec 0.000620 | Seg 0.310371 | Elapsed 3.4m | ETA 0.9m
Epoch 318/500 | Batch 170/202 | Rec 0.000616 | Seg 0.308424 | Elapsed 3.6m | ETA 0.7m
Epoch 318/500 | Batch 180/202 | Rec 0.000628 | Seg 0.308483 | Elapsed 3.8m | ETA 0.5m
Epoch 318/500 | Batch 190/202 | Rec 0.000634 | Seg 0.310871 | Elapsed 4.0m | ETA 0.3m
Epoch 318/500 | Batch 200/202 | Rec 0.000626 | Seg 0.306091 | Elapsed 4.3m | ETA 0.0m
Epoch 318/500 | Batch 202/202 | Rec 0.000623 | Seg 0.304554 | Elapsed 4.3m | ETA 0.0m

2026-09-25 19:18:06,095 - INFO: Rec loss: 0.000623443870347611
2026-09-25 19:18:06,096 - INFO: Seg loss: 0.3045542461078356
2026-09-25 19:18:06,096 - INFO: λ_rec: 1
2026-09-25 19:18:06,096 - INFO: λ_seg: 0.0001
2026-09-25 19:19:31,153 - INFO: -------------------Epoch: 318------------------------
2026-09-25 19:19:31,157 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.780252  0.974456  0.000138
2026-09-25 19:19:31,166 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995793  0.997842  0.997686  0.998098  0.995986
real potato   0.892976  0.943412  0.961967  0.925657  0.999867
fake potato   0.785670  0.879923  0.982189  0.797026  0.999842
real apple    0.803609  0.891062  0.960298  0.831225  0.999299
fake apple    0.598784  0.749002  0.983570  0.604833  0.998470
real orange   0.886513  0.939793  0.997789  0.888258  0.999850
fake orange   0.922832  0.959818  0.946804  0.973297  0.999767
real grape    0.772033  0.871303  0.934410  0.816268  0.999497
fake grape    0.904521  0.949817  0.935376  0.964815  0.999623
real lemon    0.604480  0.753442  0.639009  0.917943  0.999294
fake lemon    0.835816  0.910516  0.997082  0.837865  0.999652
real avocado  0.930633  0.964020  0.998592  0.931855  0.999935
fake avocado  0.577617  0.732219  0.993445  0.579827  0.999493
real pepper   0.892124  0.942937  0.912779  0.975263  0.999569
fake pepper   0.844385  0.915578  0.947174  0.886115  0.999611
real plant    0.868202  0.929402  0.937750  0.921299  0.998601
fake plant    0.810110  0.895045  0.849131  0.946319  0.999823
real banana   0.620313  0.765622  0.884137  0.675200  0.999071
fake banana   0.691297  0.817426  0.758645  0.886198  0.999272
real onion    0.625974  0.769920  0.641395  0.963013  0.999480
fake onion    0.926460  0.961776  0.993301  0.932285  0.999953
real unknown  0.769762  0.869855  0.797297  0.957061  0.999954
fake unknown  0.222001  0.363306  0.234270  0.809127  0.997611
total         0.773126  0.859697  0.881917  0.870385  0.999284
total(-bg)    0.763005  0.853418  0.876655  0.864580  0.999433
2026-09-25 19:19:31,782 - INFO: Epoch accounting: {'epoch': 318, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11253617, 45174, 70519, 135092, 196222, 93748, 72336, 99271, 166360, 82463, 73343, 50168, 45747, 191764, 100019, 173328, 27035, 95141, 53290, 97124, 71912, 6223, 38376], 'crops_with_class': [202, 24, 33, 40, 38, 29, 25, 19, 37, 39, 31, 15, 17, 52, 32, 23, 20, 26, 24, 43, 29, 9, 18], 'targeted_crops_by_class': [0, 2, 8, 2, 6, 4, 5, 4, 1, 5, 4, 5, 6, 1, 2, 5, 3, 4, 6, 3, 7, 4, 6], 'sampled_scene_counts': [1, 1, 1, 0, 2, 1, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 3, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 2, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 1, 2, 0, 4, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0, 3, 2, 0, 2, 3, 1, 1, 6, 0, 3, 0, 3, 3, 2, 0, 2, 1, 1, 0, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 3, 0, 0, 2, 1, 1, 1, 3, 1, 1, 1, 0, 1, 4, 2, 1, 0, 1, 3, 1, 2, 3, 1, 0, 3, 1, 3, 1, 0, 3, 0, 0, 2, 2, 0, 1, 0, 4, 1, 1, 1, 0, 1, 2, 3, 2, 1], 'learning_rate': 2.9743627397524537e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000623443870347611, 'train_segmentation_loss': 0.3045542461078356, 'val_foreground_miou_all22': 0.763005073762049, 'val_psnr_ref1': 38.7802522277832, 'elapsed_seconds': 343.25282192230225, 'peak_cuda_allocated_gib': 7.511661529541016}

Epoch 319/500 | Batch 10/202 | Rec 0.000583 | Seg 0.247195 | Elapsed 0.2m | ETA 4.2m
Epoch 319/500 | Batch 20/202 | Rec 0.000661 | Seg 0.298163 | Elapsed 0.4m | ETA 3.9m
Epoch 319/500 | Batch 30/202 | Rec 0.000643 | Seg 0.314806 | Elapsed 0.6m | ETA 3.6m
Epoch 319/500 | Batch 40/202 | Rec 0.000668 | Seg 0.322784 | Elapsed 0.8m | ETA 3.4m
Epoch 319/500 | Batch 50/202 | Rec 0.000646 | Seg 0.316472 | Elapsed 1.1m | ETA 3.2m
Epoch 319/500 | Batch 60/202 | Rec 0.000684 | Seg 0.322612 | Elapsed 1.3m | ETA 3.0m
Epoch 319/500 | Batch 70/202 | Rec 0.000692 | Seg 0.328074 | Elapsed 1.5m | ETA 2.8m
Epoch 319/500 | Batch 80/202 | Rec 0.000679 | Seg 0.322757 | Elapsed 1.7m | ETA 2.6m
Epoch 319/500 | Batch 90/202 | Rec 0.000678 | Seg 0.321975 | Elapsed 1.9m | ETA 2.4m
Epoch 319/500 | Batch 100/202 | Rec 0.000679 | Seg 0.318372 | Elapsed 2.1m | ETA 2.2m
Epoch 319/500 | Batch 110/202 | Rec 0.000666 | Seg 0.314076 | Elapsed 2.3m | ETA 1.9m
Epoch 319/500 | Batch 120/202 | Rec 0.000656 | Seg 0.310465 | Elapsed 2.5m | ETA 1.7m
Epoch 319/500 | Batch 130/202 | Rec 0.000642 | Seg 0.307886 | Elapsed 2.8m | ETA 1.5m
Epoch 319/500 | Batch 140/202 | Rec 0.000640 | Seg 0.305324 | Elapsed 3.0m | ETA 1.3m
Epoch 319/500 | Batch 150/202 | Rec 0.000629 | Seg 0.301620 | Elapsed 3.2m | ETA 1.1m
Epoch 319/500 | Batch 160/202 | Rec 0.000632 | Seg 0.305441 | Elapsed 3.4m | ETA 0.9m
Epoch 319/500 | Batch 170/202 | Rec 0.000635 | Seg 0.304115 | Elapsed 3.6m | ETA 0.7m
Epoch 319/500 | Batch 180/202 | Rec 0.000634 | Seg 0.303220 | Elapsed 3.8m | ETA 0.5m
Epoch 319/500 | Batch 190/202 | Rec 0.000634 | Seg 0.305229 | Elapsed 4.0m | ETA 0.3m
Epoch 319/500 | Batch 200/202 | Rec 0.000633 | Seg 0.304050 | Elapsed 4.3m | ETA 0.0m
Epoch 319/500 | Batch 202/202 | Rec 0.000635 | Seg 0.304771 | Elapsed 4.3m | ETA 0.0m

2026-09-25 19:23:49,674 - INFO: Rec loss: 0.0006347321274132459
2026-09-25 19:23:49,674 - INFO: Seg loss: 0.3047710189061
2026-09-25 19:23:49,674 - INFO: λ_rec: 1
2026-09-25 19:23:49,674 - INFO: λ_seg: 0.0001
2026-09-25 19:25:10,781 - INFO: -------------------Epoch: 319------------------------
2026-09-25 19:25:10,786 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.725372  0.974084  0.00014
2026-09-25 19:25:10,793 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995490  0.997690  0.996674  0.998808  0.995692
real potato   0.877224  0.934547  0.980398  0.892884  0.999850
fake potato   0.930056  0.963710  0.981120  0.947005  0.999948
real apple    0.827388  0.905492  0.959234  0.857541  0.999383
fake apple    0.605768  0.754443  0.994446  0.607824  0.998506
real orange   0.739075  0.849915  0.994261  0.742242  0.999655
fake orange   0.845751  0.916380  0.881068  0.954749  0.999501
real grape    0.757477  0.861955  0.937479  0.797778  0.999467
fake grape    0.899969  0.947301  0.945774  0.948934  0.999610
real lemon    0.571656  0.727410  0.596871  0.931187  0.999180
fake lemon    0.822374  0.902481  0.996947  0.824450  0.999623
real avocado  0.903106  0.949036  0.938795  0.959606  0.999904
fake avocado  0.804204  0.891428  0.998734  0.805024  0.999765
real pepper   0.814449  0.897687  0.845751  0.956533  0.999203
fake pepper   0.700699  0.823964  0.966162  0.718328  0.999269
real plant    0.855011  0.921789  0.947296  0.897715  0.998477
fake plant    0.879230  0.935684  0.972498  0.901649  0.999901
real banana   0.555973  0.714582  0.897710  0.593576  0.998935
fake banana   0.739172  0.849977  0.856505  0.843646  0.999452
real onion    0.668386  0.801188  0.710166  0.919101  0.999588
fake onion    0.942721  0.970466  0.986267  0.955260  0.999963
real unknown  0.810000  0.894978  0.864769  0.927481  0.999965
fake unknown  0.229731  0.373589  0.254424  0.703006  0.998014
total         0.772822  0.860248  0.891450  0.855840  0.999255
total(-bg)    0.762701  0.854000  0.886667  0.849342  0.999416
2026-09-25 19:25:11,390 - INFO: Epoch accounting: {'epoch': 319, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11235016, 31375, 57183, 140617, 158315, 89852, 91478, 190920, 167580, 80733, 58488, 40806, 47199, 228517, 175063, 107470, 17565, 59402, 73471, 70107, 61480, 13851, 41784], 'crops_with_class': [202, 24, 25, 34, 42, 29, 29, 33, 32, 35, 26, 12, 18, 59, 39, 17, 18, 16, 33, 32, 26, 17, 17], 'targeted_crops_by_class': [0, 1, 2, 3, 5, 9, 4, 5, 4, 6, 3, 5, 4, 2, 7, 2, 6, 1, 8, 5, 4, 6, 2], 'sampled_scene_counts': [0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 2, 1, 2, 0, 1, 1, 1, 0, 0, 1, 0, 2, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 2, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 2, 0, 0, 2, 2, 1, 3, 1, 0, 1, 1, 1, 1, 1, 3, 2, 1, 2, 1, 0, 2, 1, 0, 1, 1, 2, 2, 1, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 3, 2, 2, 0, 6, 3, 2, 1, 2, 0, 2, 2, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 0, 2, 2, 3, 2, 1, 2, 0, 1, 2, 2, 1, 0, 1, 0, 2, 0, 1, 0, 4, 1, 1, 4, 0, 0], 'learning_rate': 2.9458017897959897e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006347321274132459, 'train_segmentation_loss': 0.3047710189061, 'val_foreground_miou_all22': 0.762700820284984, 'val_psnr_ref1': 38.725371856689456, 'elapsed_seconds': 339.5988337993622, 'peak_cuda_allocated_gib': 7.508823394775391}

Epoch 320/500 | Batch 10/202 | Rec 0.000614 | Seg 0.306948 | Elapsed 0.2m | ETA 4.1m
Epoch 320/500 | Batch 20/202 | Rec 0.000648 | Seg 0.324748 | Elapsed 0.4m | ETA 3.8m
Epoch 320/500 | Batch 30/202 | Rec 0.000647 | Seg 0.315326 | Elapsed 0.6m | ETA 3.6m
Epoch 320/500 | Batch 40/202 | Rec 0.000632 | Seg 0.313484 | Elapsed 0.8m | ETA 3.4m
Epoch 320/500 | Batch 50/202 | Rec 0.000632 | Seg 0.312746 | Elapsed 1.0m | ETA 3.2m
Epoch 320/500 | Batch 60/202 | Rec 0.000636 | Seg 0.317268 | Elapsed 1.3m | ETA 3.0m
Epoch 320/500 | Batch 70/202 | Rec 0.000646 | Seg 0.313084 | Elapsed 1.5m | ETA 2.8m
Epoch 320/500 | Batch 80/202 | Rec 0.000639 | Seg 0.309939 | Elapsed 1.7m | ETA 2.6m
Epoch 320/500 | Batch 90/202 | Rec 0.000637 | Seg 0.309797 | Elapsed 1.9m | ETA 2.3m
Epoch 320/500 | Batch 100/202 | Rec 0.000629 | Seg 0.306346 | Elapsed 2.1m | ETA 2.1m
Epoch 320/500 | Batch 110/202 | Rec 0.000640 | Seg 0.304176 | Elapsed 2.3m | ETA 1.9m
Epoch 320/500 | Batch 120/202 | Rec 0.000635 | Seg 0.301102 | Elapsed 2.5m | ETA 1.7m
Epoch 320/500 | Batch 130/202 | Rec 0.000641 | Seg 0.300224 | Elapsed 2.7m | ETA 1.5m
Epoch 320/500 | Batch 140/202 | Rec 0.000640 | Seg 0.300376 | Elapsed 2.9m | ETA 1.3m
Epoch 320/500 | Batch 150/202 | Rec 0.000636 | Seg 0.298383 | Elapsed 3.2m | ETA 1.1m
Epoch 320/500 | Batch 160/202 | Rec 0.000641 | Seg 0.302735 | Elapsed 3.4m | ETA 0.9m
Epoch 320/500 | Batch 170/202 | Rec 0.000635 | Seg 0.302898 | Elapsed 3.6m | ETA 0.7m
Epoch 320/500 | Batch 180/202 | Rec 0.000641 | Seg 0.303499 | Elapsed 3.8m | ETA 0.5m
Epoch 320/500 | Batch 190/202 | Rec 0.000640 | Seg 0.303450 | Elapsed 4.0m | ETA 0.3m
Epoch 320/500 | Batch 200/202 | Rec 0.000641 | Seg 0.304423 | Elapsed 4.2m | ETA 0.0m
Epoch 320/500 | Batch 202/202 | Rec 0.000639 | Seg 0.303911 | Elapsed 4.2m | ETA 0.0m

2026-09-25 19:29:25,951 - INFO: Rec loss: 0.0006392219489714647
2026-09-25 19:29:25,951 - INFO: Seg loss: 0.3039109294146004
2026-09-25 19:29:25,951 - INFO: λ_rec: 1
2026-09-25 19:29:25,951 - INFO: λ_seg: 0.0001
2026-09-25 19:30:48,928 - INFO: -------------------Epoch: 320------------------------
2026-09-25 19:30:48,932 - INFO:
Validation stats:
      PSNR      SSIM       MSE
0  38.9514  0.974213  0.000133
2026-09-25 19:30:48,940 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995589  0.997740  0.996711  0.998871  0.995787
real potato   0.929792  0.963569  0.976811  0.950778  0.999914
fake potato   0.803878  0.891228  0.957421  0.833682  0.999852
real apple    0.728614  0.842955  0.986252  0.736090  0.999054
fake apple    0.611096  0.758561  0.985721  0.616554  0.998519
real orange   0.912346  0.954114  0.997097  0.914775  0.999884
fake orange   0.941523  0.969831  0.959956  0.980013  0.999826
real grape    0.729984  0.843870  0.932137  0.770957  0.999405
fake grape    0.897031  0.945671  0.944205  0.947242  0.999598
real lemon    0.641286  0.781394  0.699119  0.885744  0.999418
fake lemon    0.847116  0.917181  0.996532  0.849621  0.999676
real avocado  0.943888  0.971084  0.999132  0.944663  0.999948
fake avocado  0.479791  0.648414  0.999734  0.479852  0.999377
real pepper   0.932058  0.964785  0.961974  0.967712  0.999742
fake pepper   0.902990  0.948972  0.948810  0.949235  0.999757
real plant    0.845725  0.916365  0.949729  0.885358  0.998385
fake plant    0.770641  0.870415  0.833509  0.910851  0.999784
real banana   0.656786  0.792795  0.933321  0.689121  0.999191
fake banana   0.716582  0.834844  0.837858  0.831951  0.999395
real onion    0.629221  0.772371  0.644804  0.963013  0.999487
fake onion    0.930655  0.964032  0.988068  0.941233  0.999956
real unknown  0.664861  0.798650  0.695960  0.937023  0.999924
fake unknown  0.199166  0.332140  0.213132  0.752445  0.997451
total         0.770027  0.855695  0.888608  0.858121  0.999275
total(-bg)    0.759774  0.849238  0.883695  0.851723  0.999434
2026-09-25 19:30:49,691 - INFO: Epoch accounting: {'epoch': 320, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11225416, 53303, 64048, 131639, 117667, 118646, 76433, 145522, 168941, 61740, 67363, 41533, 31058, 206628, 143297, 166095, 22060, 68655, 92175, 109365, 74791, 8884, 43013], 'crops_with_class': [202, 30, 26, 35, 32, 34, 28, 31, 30, 26, 23, 14, 12, 53, 37, 22, 22, 22, 35, 43, 33, 10, 21], 'targeted_crops_by_class': [0, 6, 4, 1, 3, 2, 6, 8, 5, 6, 4, 3, 4, 6, 8, 3, 3, 4, 10, 4, 5, 4, 3], 'sampled_scene_counts': [0, 1, 2, 1, 0, 2, 1, 1, 3, 2, 0, 2, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 2, 1, 3, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 0, 1, 1, 2, 1, 3, 0, 0, 1, 3, 3, 1, 1, 0, 2, 2, 1, 1, 1, 2, 3, 3, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 3, 2, 2, 2, 4, 1, 1, 4, 0, 0, 4, 1, 2, 1, 3, 2, 1, 3, 1, 1, 2, 1, 1, 2, 1, 1, 3, 2, 0, 0, 0, 1, 1, 1, 0, 0, 3, 3, 1, 1, 2, 1], 'learning_rate': 2.9173224295461104e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006392219489714647, 'train_segmentation_loss': 0.3039109294146004, 'val_foreground_miou_all22': 0.7597740647677536, 'val_psnr_ref1': 38.95139999389649, 'elapsed_seconds': 338.2910270690918, 'peak_cuda_allocated_gib': 7.512729644775391}

Epoch 321/500 | Batch 10/202 | Rec 0.000640 | Seg 0.297284 | Elapsed 0.2m | ETA 4.0m
Epoch 321/500 | Batch 20/202 | Rec 0.000525 | Seg 0.256014 | Elapsed 0.4m | ETA 3.9m
Epoch 321/500 | Batch 30/202 | Rec 0.000556 | Seg 0.249137 | Elapsed 0.6m | ETA 3.7m
Epoch 321/500 | Batch 40/202 | Rec 0.000643 | Seg 0.259915 | Elapsed 0.8m | ETA 3.4m
Epoch 321/500 | Batch 50/202 | Rec 0.000635 | Seg 0.269970 | Elapsed 1.1m | ETA 3.4m
Epoch 321/500 | Batch 60/202 | Rec 0.000661 | Seg 0.290508 | Elapsed 1.3m | ETA 3.1m
Epoch 321/500 | Batch 70/202 | Rec 0.000662 | Seg 0.292210 | Elapsed 1.5m | ETA 2.9m
Epoch 321/500 | Batch 80/202 | Rec 0.000659 | Seg 0.298607 | Elapsed 1.7m | ETA 2.7m
Epoch 321/500 | Batch 90/202 | Rec 0.000660 | Seg 0.303054 | Elapsed 2.0m | ETA 2.4m
Epoch 321/500 | Batch 100/202 | Rec 0.000660 | Seg 0.305164 | Elapsed 2.2m | ETA 2.2m
Epoch 321/500 | Batch 110/202 | Rec 0.000669 | Seg 0.309129 | Elapsed 2.4m | ETA 2.0m
Epoch 321/500 | Batch 120/202 | Rec 0.000656 | Seg 0.303272 | Elapsed 2.6m | ETA 1.8m
Epoch 321/500 | Batch 130/202 | Rec 0.000657 | Seg 0.304116 | Elapsed 2.8m | ETA 1.5m
Epoch 321/500 | Batch 140/202 | Rec 0.000667 | Seg 0.310805 | Elapsed 3.0m | ETA 1.3m
Epoch 321/500 | Batch 150/202 | Rec 0.000656 | Seg 0.308435 | Elapsed 3.2m | ETA 1.1m
Epoch 321/500 | Batch 160/202 | Rec 0.000663 | Seg 0.309542 | Elapsed 3.4m | ETA 0.9m
Epoch 321/500 | Batch 170/202 | Rec 0.000663 | Seg 0.309832 | Elapsed 3.6m | ETA 0.7m
Epoch 321/500 | Batch 180/202 | Rec 0.000659 | Seg 0.308418 | Elapsed 3.8m | ETA 0.5m
Epoch 321/500 | Batch 190/202 | Rec 0.000658 | Seg 0.309489 | Elapsed 4.0m | ETA 0.3m
Epoch 321/500 | Batch 200/202 | Rec 0.000653 | Seg 0.308746 | Elapsed 4.2m | ETA 0.0m
Epoch 321/500 | Batch 202/202 | Rec 0.000653 | Seg 0.308690 | Elapsed 4.3m | ETA 0.0m

2026-09-25 19:35:05,880 - INFO: Rec loss: 0.0006530325019664113
2026-09-25 19:35:05,880 - INFO: Seg loss: 0.30868978252505314
2026-09-25 19:35:05,880 - INFO: λ_rec: 1
2026-09-25 19:35:05,880 - INFO: λ_seg: 0.0001
2026-09-25 19:36:28,497 - INFO: -------------------Epoch: 321------------------------
2026-09-25 19:36:28,501 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.853873  0.974031  0.000136
2026-09-25 19:36:28,509 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995542  0.997716  0.996840  0.998694  0.995742
real potato   0.917426  0.956885  0.950554  0.963402  0.999896
fake potato   0.950071  0.974346  0.968349  0.980519  0.999962
real apple    0.689739  0.816337  0.994473  0.692393  0.998925
fake apple    0.688521  0.815483  0.990585  0.693057  0.998816
real orange   0.895010  0.944547  0.997169  0.897290  0.999861
fake orange   0.916654  0.956465  0.942702  0.970739  0.999747
real grape    0.697818  0.821968  0.895571  0.759629  0.999313
fake grape    0.897846  0.946124  0.923666  0.969806  0.999592
real lemon    0.534165  0.696309  0.662525  0.733835  0.999248
fake lemon    0.815031  0.898041  0.998852  0.815795  0.999608
real avocado  0.920687  0.958656  0.958627  0.958785  0.999923
fake avocado  0.613631  0.760512  0.998342  0.614257  0.999537
real pepper   0.825641  0.904445  0.868147  0.944018  0.999271
fake pepper   0.765377  0.867048  0.967739  0.785417  0.999426
real plant    0.848187  0.917808  0.931921  0.904213  0.998381
fake plant    0.821775  0.902120  0.895692  0.908742  0.999843
real banana   0.645340  0.784397  0.939543  0.673299  0.999169
fake banana   0.681143  0.810283  0.775696  0.848208  0.999270
real onion    0.588382  0.740809  0.603983  0.957946  0.999395
fake onion    0.920498  0.958554  0.989447  0.929625  0.999949
real unknown  0.443541  0.614474  0.457169  0.937023  0.999812
fake unknown  0.249358  0.399139  0.271151  0.756248  0.998082
total         0.753104  0.845325  0.868641  0.856215  0.999251
total(-bg)    0.742084  0.838398  0.862814  0.849738  0.999410
2026-09-25 19:36:29,094 - INFO: Epoch accounting: {'epoch': 321, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11233753, 53414, 54969, 119752, 188014, 72948, 59780, 144584, 193057, 88301, 99966, 45096, 23216, 188829, 124279, 132273, 21435, 92985, 123076, 61459, 67048, 8706, 41332], 'crops_with_class': [202, 31, 28, 33, 39, 22, 26, 29, 33, 35, 36, 15, 10, 49, 38, 17, 20, 31, 46, 35, 32, 9, 18], 'targeted_crops_by_class': [0, 6, 5, 6, 8, 4, 1, 5, 2, 5, 10, 5, 5, 4, 5, 5, 4, 6, 12, 3, 5, 4, 3], 'sampled_scene_counts': [2, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 3, 1, 0, 0, 1, 2, 0, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 3, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 2, 0, 0, 0, 1, 0, 2, 2, 2, 1, 2, 2, 3, 1, 2, 2, 4, 4, 1, 1, 3, 1, 0, 0, 1, 2, 2, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 3, 3, 3, 2, 0, 0, 2, 2, 1, 2, 0, 0, 1, 3, 6, 0, 3, 1, 0, 1, 1, 0, 0, 3, 2, 0, 3, 3, 3, 1, 2, 1, 1, 0, 2, 0, 0, 0, 2, 3, 4, 3], 'learning_rate': 2.888925783319194e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006530325019664113, 'train_segmentation_loss': 0.30868978252505314, 'val_foreground_miou_all22': 0.7420837253214514, 'val_psnr_ref1': 38.85387268066406, 'elapsed_seconds': 339.39461851119995, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 322/500 | Batch 10/202 | Rec 0.000678 | Seg 0.349156 | Elapsed 0.2m | ETA 4.0m
Epoch 322/500 | Batch 20/202 | Rec 0.000655 | Seg 0.327049 | Elapsed 0.4m | ETA 3.8m
Epoch 322/500 | Batch 30/202 | Rec 0.000604 | Seg 0.292215 | Elapsed 0.6m | ETA 3.6m
Epoch 322/500 | Batch 40/202 | Rec 0.000656 | Seg 0.321827 | Elapsed 0.8m | ETA 3.4m
Epoch 322/500 | Batch 50/202 | Rec 0.000634 | Seg 0.307897 | Elapsed 1.0m | ETA 3.2m
Epoch 322/500 | Batch 60/202 | Rec 0.000650 | Seg 0.303754 | Elapsed 1.3m | ETA 3.0m
Epoch 322/500 | Batch 70/202 | Rec 0.000636 | Seg 0.299216 | Elapsed 1.5m | ETA 2.7m
Epoch 322/500 | Batch 80/202 | Rec 0.000646 | Seg 0.301943 | Elapsed 1.7m | ETA 2.5m
Epoch 322/500 | Batch 90/202 | Rec 0.000634 | Seg 0.296098 | Elapsed 1.9m | ETA 2.3m
Epoch 322/500 | Batch 100/202 | Rec 0.000645 | Seg 0.304893 | Elapsed 2.1m | ETA 2.1m
Epoch 322/500 | Batch 110/202 | Rec 0.000632 | Seg 0.298949 | Elapsed 2.3m | ETA 1.9m
Epoch 322/500 | Batch 120/202 | Rec 0.000634 | Seg 0.297247 | Elapsed 2.5m | ETA 1.7m
Epoch 322/500 | Batch 130/202 | Rec 0.000636 | Seg 0.295973 | Elapsed 2.7m | ETA 1.5m
Epoch 322/500 | Batch 140/202 | Rec 0.000642 | Seg 0.292479 | Elapsed 2.9m | ETA 1.3m
Epoch 322/500 | Batch 150/202 | Rec 0.000649 | Seg 0.294759 | Elapsed 3.1m | ETA 1.1m
Epoch 322/500 | Batch 160/202 | Rec 0.000648 | Seg 0.294392 | Elapsed 3.3m | ETA 0.9m
Epoch 322/500 | Batch 170/202 | Rec 0.000642 | Seg 0.294644 | Elapsed 3.5m | ETA 0.7m
Epoch 322/500 | Batch 180/202 | Rec 0.000646 | Seg 0.296589 | Elapsed 3.7m | ETA 0.5m
Epoch 322/500 | Batch 190/202 | Rec 0.000642 | Seg 0.297460 | Elapsed 3.9m | ETA 0.2m
Epoch 322/500 | Batch 200/202 | Rec 0.000648 | Seg 0.299889 | Elapsed 4.1m | ETA 0.0m
Epoch 322/500 | Batch 202/202 | Rec 0.000647 | Seg 0.299802 | Elapsed 4.2m | ETA 0.0m

2026-09-25 19:40:40,600 - INFO: Rec loss: 0.0006471589156645488
2026-09-25 19:40:40,600 - INFO: Seg loss: 0.29980193495307816
2026-09-25 19:40:40,600 - INFO: λ_rec: 1
2026-09-25 19:40:40,600 - INFO: λ_seg: 0.0001
2026-09-25 19:41:59,045 - INFO: -------------------Epoch: 322------------------------
2026-09-25 19:41:59,049 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.868014  0.974223  0.000135
2026-09-25 19:41:59,057 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995594  0.997742  0.996886  0.998700  0.995792
real potato   0.940505  0.969290  0.983591  0.955496  0.999928
fake potato   0.934473  0.966077  0.970414  0.961877  0.999951
real apple    0.741362  0.851425  0.990207  0.746838  0.999101
fake apple    0.586919  0.739649  0.990038  0.590406  0.998431
real orange   0.941346  0.969737  0.996943  0.944071  0.999922
fake orange   0.944522  0.971420  0.971988  0.970952  0.999837
real grape    0.773335  0.872132  0.966824  0.794416  0.999514
fake grape    0.903899  0.949474  0.940156  0.959081  0.999623
real lemon    0.601655  0.751243  0.627998  0.934822  0.999273
fake lemon    0.836068  0.910666  0.977267  0.852651  0.999646
real avocado  0.947101  0.972782  0.997241  0.949589  0.999951
fake avocado  0.589518  0.741710  1.000000  0.589518  0.999509
real pepper   0.893216  0.943547  0.917616  0.971091  0.999575
fake pepper   0.861896  0.925776  0.936591  0.915306  0.999650
real plant    0.848685  0.918100  0.953128  0.885648  0.998421
fake plant    0.815546  0.898353  0.901699  0.895130  0.999839
real banana   0.599126  0.749268  0.898661  0.642537  0.999034
fake banana   0.699288  0.822987  0.786151  0.863553  0.999317
real onion    0.630469  0.773311  0.652502  0.949164  0.999497
fake onion    0.930738  0.964077  0.986832  0.942443  0.999956
real unknown  0.609365  0.757226  0.632353  0.943702  0.999903
fake unknown  0.191632  0.321593  0.211420  0.671858  0.997612
total         0.774620  0.858156  0.882022  0.866472  0.999273
total(-bg)    0.764576  0.851811  0.876801  0.860461  0.999431
2026-09-25 19:41:59,618 - INFO: Epoch accounting: {'epoch': 322, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11272680, 55494, 73599, 116333, 151956, 64991, 65193, 123170, 151749, 66275, 43092, 35628, 46865, 249335, 146861, 189850, 32499, 77358, 60994, 88955, 78351, 5453, 41591], 'crops_with_class': [202, 32, 33, 33, 36, 20, 18, 28, 29, 31, 22, 14, 17, 67, 39, 24, 27, 24, 24, 40, 32, 8, 17], 'targeted_crops_by_class': [0, 4, 8, 6, 9, 3, 2, 7, 3, 6, 5, 2, 7, 5, 6, 7, 7, 7, 4, 4, 3, 2, 4], 'sampled_scene_counts': [1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0, 0, 2, 0, 0, 2, 0, 0, 2, 1, 2, 0, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 2, 0, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 0, 2, 2, 3, 2, 1, 0, 2, 1, 3, 2, 0, 0, 0, 3, 0, 0, 1, 2, 2, 2, 2, 1, 2, 3, 1, 1, 1, 3, 0, 1, 0, 2, 4, 1, 2, 3, 1, 0, 2, 1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 1, 0, 2, 2, 0, 0, 3, 1, 0, 0, 2, 2, 2, 1, 2, 0, 0, 2, 4, 1, 1, 1, 1, 3, 2, 2, 2, 2, 0], 'learning_rate': 2.860612972166213e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006471589156645488, 'train_segmentation_loss': 0.29980193495307816, 'val_foreground_miou_all22': 0.7645756841092755, 'val_psnr_ref1': 38.86801376342773, 'elapsed_seconds': 330.51484990119934, 'peak_cuda_allocated_gib': 7.512241363525391}

Epoch 323/500 | Batch 10/202 | Rec 0.000717 | Seg 0.321302 | Elapsed 0.2m | ETA 4.0m
Epoch 323/500 | Batch 20/202 | Rec 0.000641 | Seg 0.292091 | Elapsed 0.4m | ETA 3.8m
Epoch 323/500 | Batch 30/202 | Rec 0.000622 | Seg 0.277655 | Elapsed 0.6m | ETA 3.7m
Epoch 323/500 | Batch 40/202 | Rec 0.000592 | Seg 0.274966 | Elapsed 0.9m | ETA 3.5m
Epoch 323/500 | Batch 50/202 | Rec 0.000609 | Seg 0.289741 | Elapsed 1.1m | ETA 3.2m
Epoch 323/500 | Batch 60/202 | Rec 0.000603 | Seg 0.289050 | Elapsed 1.3m | ETA 3.0m
Epoch 323/500 | Batch 70/202 | Rec 0.000593 | Seg 0.281417 | Elapsed 1.5m | ETA 2.8m
Epoch 323/500 | Batch 80/202 | Rec 0.000603 | Seg 0.280868 | Elapsed 1.7m | ETA 2.6m
Epoch 323/500 | Batch 90/202 | Rec 0.000607 | Seg 0.284899 | Elapsed 1.9m | ETA 2.3m
Epoch 323/500 | Batch 100/202 | Rec 0.000613 | Seg 0.291705 | Elapsed 2.1m | ETA 2.1m
Epoch 323/500 | Batch 110/202 | Rec 0.000616 | Seg 0.289067 | Elapsed 2.3m | ETA 1.9m
Epoch 323/500 | Batch 120/202 | Rec 0.000612 | Seg 0.290381 | Elapsed 2.5m | ETA 1.7m
Epoch 323/500 | Batch 130/202 | Rec 0.000607 | Seg 0.286779 | Elapsed 2.7m | ETA 1.5m
Epoch 323/500 | Batch 140/202 | Rec 0.000607 | Seg 0.286282 | Elapsed 2.9m | ETA 1.3m
Epoch 323/500 | Batch 150/202 | Rec 0.000598 | Seg 0.283620 | Elapsed 3.1m | ETA 1.1m
Epoch 323/500 | Batch 160/202 | Rec 0.000602 | Seg 0.287222 | Elapsed 3.3m | ETA 0.9m
Epoch 323/500 | Batch 170/202 | Rec 0.000614 | Seg 0.288056 | Elapsed 3.6m | ETA 0.7m
Epoch 323/500 | Batch 180/202 | Rec 0.000613 | Seg 0.287336 | Elapsed 3.8m | ETA 0.5m
Epoch 323/500 | Batch 190/202 | Rec 0.000612 | Seg 0.285021 | Elapsed 4.0m | ETA 0.3m
Epoch 323/500 | Batch 200/202 | Rec 0.000612 | Seg 0.285102 | Elapsed 4.2m | ETA 0.0m
Epoch 323/500 | Batch 202/202 | Rec 0.000609 | Seg 0.283878 | Elapsed 4.2m | ETA 0.0m

2026-09-25 19:46:13,719 - INFO: Rec loss: 0.0006090625591079317
2026-09-25 19:46:13,720 - INFO: Seg loss: 0.2838782667744868
2026-09-25 19:46:13,720 - INFO: λ_rec: 1
2026-09-25 19:46:13,720 - INFO: λ_seg: 0.0001
2026-09-25 19:47:35,159 - INFO: -------------------Epoch: 323------------------------
2026-09-25 19:47:35,163 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.957667  0.974658  0.000133
2026-09-25 19:47:35,170 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995435  0.997662  0.996607  0.998820  0.995639
real potato   0.644425  0.783721  0.975138  0.655190  0.999567
fake potato   0.718591  0.836207  0.962630  0.739212  0.999789
real apple    0.751816  0.858278  0.860675  0.855993  0.999025
fake apple    0.635755  0.777275  0.997027  0.636962  0.998622
real orange   0.769775  0.869864  0.981802  0.780917  0.999692
fake orange   0.873515  0.932438  0.902624  0.964396  0.999600
real grape    0.774482  0.872860  0.898114  0.849083  0.999484
fake grape    0.877698  0.934816  0.920821  0.949346  0.999511
real lemon    0.657936  0.793632  0.696142  0.923007  0.999436
fake lemon    0.844980  0.915927  0.992591  0.850343  0.999670
real avocado  0.812561  0.896539  0.845807  0.953859  0.999796
fake avocado  0.714268  0.833272  0.994868  0.716909  0.999657
real pepper   0.813296  0.896986  0.862099  0.934924  0.999215
fake pepper   0.658743  0.794219  0.942029  0.686576  0.999152
real plant    0.857285  0.923109  0.955112  0.893276  0.998513
fake plant    0.713300  0.832613  0.766023  0.912002  0.999708
real banana   0.654512  0.791135  0.920837  0.693535  0.999177
fake banana   0.753945  0.859664  0.875958  0.844061  0.999493
real onion    0.648958  0.787063  0.723947  0.862354  0.999579
fake onion    0.950493  0.974568  0.993469  0.956469  0.999969
real unknown  0.881614  0.937033  0.936190  0.937977  0.999980
fake unknown  0.227857  0.371106  0.257083  0.667150  0.998095
total         0.749184  0.846521  0.880765  0.837494  0.999233
total(-bg)    0.737991  0.839651  0.875499  0.830161  0.999397
2026-09-25 19:47:35,903 - INFO: Epoch accounting: {'epoch': 323, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11404588, 54483, 48169, 110167, 124755, 69939, 80442, 146354, 197613, 56005, 76525, 42630, 43862, 153027, 89036, 151298, 38516, 86703, 60919, 86212, 56683, 5587, 54759], 'crops_with_class': [202, 30, 24, 31, 28, 19, 22, 29, 32, 28, 26, 15, 14, 42, 24, 25, 31, 23, 28, 38, 27, 6, 23], 'targeted_crops_by_class': [0, 2, 1, 6, 3, 0, 2, 9, 9, 6, 6, 4, 8, 4, 4, 7, 6, 4, 3, 3, 7, 0, 7], 'sampled_scene_counts': [3, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 2, 2, 0, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 3, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 2, 3, 2, 2, 3, 0, 0, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 0, 2, 0, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0, 3, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 3, 1, 1, 0, 2, 2, 2, 1, 1, 1, 2, 3, 0, 1, 1, 2, 1, 1, 1, 0, 1, 2, 2, 1, 2, 1, 0, 2, 2, 1, 0, 3, 1, 3, 2, 3, 2, 2, 2, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 1, 2, 2, 2, 0, 1, 2, 0, 2, 2, 2, 2], 'learning_rate': 2.8323851138284675e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006090625591079317, 'train_segmentation_loss': 0.2838782667744868, 'val_foreground_miou_all22': 0.7379911647748059, 'val_psnr_ref1': 38.957667388916015, 'elapsed_seconds': 336.2773642539978, 'peak_cuda_allocated_gib': 7.510318756103516}

Epoch 324/500 | Batch 10/202 | Rec 0.000590 | Seg 0.264229 | Elapsed 0.2m | ETA 4.1m
Epoch 324/500 | Batch 20/202 | Rec 0.000582 | Seg 0.270349 | Elapsed 0.4m | ETA 3.9m
Epoch 324/500 | Batch 30/202 | Rec 0.000608 | Seg 0.290186 | Elapsed 0.6m | ETA 3.6m
Epoch 324/500 | Batch 40/202 | Rec 0.000655 | Seg 0.292451 | Elapsed 0.8m | ETA 3.4m
Epoch 324/500 | Batch 50/202 | Rec 0.000638 | Seg 0.300391 | Elapsed 1.0m | ETA 3.2m
Epoch 324/500 | Batch 60/202 | Rec 0.000638 | Seg 0.304693 | Elapsed 1.3m | ETA 3.0m
Epoch 324/500 | Batch 70/202 | Rec 0.000633 | Seg 0.310041 | Elapsed 1.5m | ETA 2.8m
Epoch 324/500 | Batch 80/202 | Rec 0.000613 | Seg 0.300492 | Elapsed 1.7m | ETA 2.6m
Epoch 324/500 | Batch 90/202 | Rec 0.000610 | Seg 0.299732 | Elapsed 1.9m | ETA 2.3m
Epoch 324/500 | Batch 100/202 | Rec 0.000605 | Seg 0.292379 | Elapsed 2.1m | ETA 2.1m
Epoch 324/500 | Batch 110/202 | Rec 0.000603 | Seg 0.292193 | Elapsed 2.3m | ETA 1.9m
Epoch 324/500 | Batch 120/202 | Rec 0.000603 | Seg 0.292219 | Elapsed 2.5m | ETA 1.7m
Epoch 324/500 | Batch 130/202 | Rec 0.000625 | Seg 0.297665 | Elapsed 2.7m | ETA 1.5m
Epoch 324/500 | Batch 140/202 | Rec 0.000632 | Seg 0.301219 | Elapsed 2.9m | ETA 1.3m
Epoch 324/500 | Batch 150/202 | Rec 0.000620 | Seg 0.296054 | Elapsed 3.1m | ETA 1.1m
Epoch 324/500 | Batch 160/202 | Rec 0.000629 | Seg 0.294190 | Elapsed 3.3m | ETA 0.9m
Epoch 324/500 | Batch 170/202 | Rec 0.000627 | Seg 0.293429 | Elapsed 3.6m | ETA 0.7m
Epoch 324/500 | Batch 180/202 | Rec 0.000623 | Seg 0.293300 | Elapsed 3.8m | ETA 0.5m
Epoch 324/500 | Batch 190/202 | Rec 0.000626 | Seg 0.295220 | Elapsed 4.0m | ETA 0.3m
Epoch 324/500 | Batch 200/202 | Rec 0.000631 | Seg 0.295227 | Elapsed 4.2m | ETA 0.0m
Epoch 324/500 | Batch 202/202 | Rec 0.000629 | Seg 0.294147 | Elapsed 4.2m | ETA 0.0m

2026-09-25 19:51:49,071 - INFO: Rec loss: 0.0006291708850767463
2026-09-25 19:51:49,072 - INFO: Seg loss: 0.2941471906839916
2026-09-25 19:51:49,072 - INFO: λ_rec: 1
2026-09-25 19:51:49,072 - INFO: λ_seg: 0.0001
2026-09-25 19:53:07,832 - INFO: -------------------Epoch: 324------------------------
2026-09-25 19:53:07,836 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.665173  0.974003  0.000142
2026-09-25 19:53:07,844 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995667  0.997779  0.996814  0.998845  0.995861
real potato   0.678990  0.808760  0.999625  0.679163  0.999616
fake potato   0.716363  0.834696  0.969781  0.732719  0.999789
real apple    0.751885  0.858323  0.852475  0.864352  0.999016
fake apple    0.601415  0.751058  0.991777  0.604429  0.998488
real orange   0.937615  0.967753  0.995592  0.941524  0.999917
fake orange   0.937031  0.967442  0.963427  0.971592  0.999813
real grape    0.820373  0.901274  0.937125  0.868158  0.999603
fake grape    0.874015  0.932723  0.956083  0.910572  0.999514
real lemon    0.529553  0.692380  0.579140  0.860815  0.999101
fake lemon    0.851044  0.919479  0.993966  0.855463  0.999683
real avocado  0.859973  0.924666  0.896286  0.955008  0.999855
fake avocado  0.576453  0.731282  0.998675  0.576894  0.999493
real pepper   0.866342  0.928335  0.900074  0.958535  0.999459
fake pepper   0.789705  0.882448  0.960594  0.816145  0.999482
real plant    0.869783  0.930307  0.964301  0.898722  0.998654
fake plant    0.839685  0.912807  0.926372  0.899732  0.999863
real banana   0.588178  0.740647  0.925041  0.617615  0.999028
fake banana   0.709885  0.830280  0.800925  0.861977  0.999352
real onion    0.630063  0.773004  0.740037  0.809154  0.999571
fake onion    0.940245  0.969152  0.991899  0.947521  0.999962
real unknown  0.932252  0.964888  1.000000  0.932252  0.999989
fake unknown  0.206543  0.342336  0.222318  0.744296  0.997591
total         0.761003  0.850514  0.894014  0.839369  0.999248
total(-bg)    0.750336  0.843820  0.889342  0.832120  0.999402
2026-09-25 19:53:08,400 - INFO: Epoch accounting: {'epoch': 324, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11330729, 32469, 44725, 117181, 145492, 95122, 61203, 164010, 201121, 62909, 69075, 48925, 45579, 196425, 131833, 135022, 27058, 91875, 57211, 61638, 49534, 15282, 53854], 'crops_with_class': [202, 20, 25, 32, 38, 28, 25, 32, 39, 29, 25, 16, 16, 48, 35, 16, 22, 24, 26, 27, 20, 15, 26], 'targeted_crops_by_class': [0, 3, 4, 6, 7, 5, 2, 7, 4, 3, 6, 8, 4, 2, 7, 2, 7, 4, 4, 1, 3, 8, 8], 'sampled_scene_counts': [3, 1, 0, 0, 2, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 0, 1, 2, 1, 0, 3, 0, 0, 1, 2, 0, 1, 0, 3, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 2, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 0, 2, 1, 1, 2, 1, 0, 1, 2, 3, 0, 3, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 2, 0, 0, 1, 0, 2, 0, 2, 1, 4, 0, 0, 1, 1, 2, 0, 1, 0, 0, 3, 3, 2, 1, 3, 1, 0, 1, 0, 1, 0, 1, 3, 1, 3, 2, 5, 4, 3, 0, 3, 1, 0, 3, 2, 1, 2, 0, 1, 0, 0, 2, 1, 0, 1, 2, 0, 2, 2, 0, 2, 1, 0, 1, 2, 1, 2, 2, 0, 0, 0, 1, 1, 1, 1, 1, 2], 'learning_rate': 2.8042433226934738e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006291708850767463, 'train_segmentation_loss': 0.2941471906839916, 'val_foreground_miou_all22': 0.7503359892781876, 'val_psnr_ref1': 38.66517318725586, 'elapsed_seconds': 332.4887840747833, 'peak_cuda_allocated_gib': 7.5077362060546875}

Epoch 325/500 | Batch 10/202 | Rec 0.000710 | Seg 0.401770 | Elapsed 0.2m | ETA 4.0m
Epoch 325/500 | Batch 20/202 | Rec 0.000619 | Seg 0.341046 | Elapsed 0.4m | ETA 3.8m
Epoch 325/500 | Batch 30/202 | Rec 0.000646 | Seg 0.359321 | Elapsed 0.6m | ETA 3.6m
Epoch 325/500 | Batch 40/202 | Rec 0.000684 | Seg 0.335833 | Elapsed 0.8m | ETA 3.4m
Epoch 325/500 | Batch 50/202 | Rec 0.000680 | Seg 0.331512 | Elapsed 1.0m | ETA 3.2m
Epoch 325/500 | Batch 60/202 | Rec 0.000665 | Seg 0.323415 | Elapsed 1.2m | ETA 2.9m
Epoch 325/500 | Batch 70/202 | Rec 0.000664 | Seg 0.319983 | Elapsed 1.5m | ETA 2.8m
Epoch 325/500 | Batch 80/202 | Rec 0.000685 | Seg 0.317472 | Elapsed 1.7m | ETA 2.5m
Epoch 325/500 | Batch 90/202 | Rec 0.000702 | Seg 0.310223 | Elapsed 1.9m | ETA 2.3m
Epoch 325/500 | Batch 100/202 | Rec 0.000688 | Seg 0.308207 | Elapsed 2.1m | ETA 2.1m
Epoch 325/500 | Batch 110/202 | Rec 0.000700 | Seg 0.308962 | Elapsed 2.3m | ETA 1.9m
Epoch 325/500 | Batch 120/202 | Rec 0.000694 | Seg 0.306564 | Elapsed 2.5m | ETA 1.7m
Epoch 325/500 | Batch 130/202 | Rec 0.000683 | Seg 0.302412 | Elapsed 2.7m | ETA 1.5m
Epoch 325/500 | Batch 140/202 | Rec 0.000690 | Seg 0.305344 | Elapsed 2.9m | ETA 1.3m
Epoch 325/500 | Batch 150/202 | Rec 0.000686 | Seg 0.305719 | Elapsed 3.1m | ETA 1.1m
Epoch 325/500 | Batch 160/202 | Rec 0.000680 | Seg 0.306150 | Elapsed 3.3m | ETA 0.9m
Epoch 325/500 | Batch 170/202 | Rec 0.000669 | Seg 0.302719 | Elapsed 3.6m | ETA 0.7m
Epoch 325/500 | Batch 180/202 | Rec 0.000667 | Seg 0.299493 | Elapsed 3.8m | ETA 0.5m
Epoch 325/500 | Batch 190/202 | Rec 0.000664 | Seg 0.300697 | Elapsed 4.0m | ETA 0.3m
Epoch 325/500 | Batch 200/202 | Rec 0.000664 | Seg 0.303241 | Elapsed 4.2m | ETA 0.0m
Epoch 325/500 | Batch 202/202 | Rec 0.000662 | Seg 0.303123 | Elapsed 4.2m | ETA 0.0m

2026-09-25 19:57:22,299 - INFO: Rec loss: 0.0006617524374119642
2026-09-25 19:57:22,299 - INFO: Seg loss: 0.3031226198862095
2026-09-25 19:57:22,299 - INFO: λ_rec: 1
2026-09-25 19:57:22,299 - INFO: λ_seg: 0.0001
2026-09-25 19:58:45,477 - INFO: -------------------Epoch: 325------------------------
2026-09-25 19:58:45,481 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.698309  0.974162  0.000141
2026-09-25 19:58:45,489 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.996026  0.997959  0.997802  0.998215  0.996208
real potato   0.861218  0.925385  0.973936  0.881535  0.999830
fake potato   0.956069  0.977491  0.974995  0.980101  0.999967
real apple    0.818081  0.899889  0.957543  0.848872  0.999349
fake apple    0.598153  0.748508  0.982402  0.604631  0.998466
real orange   0.914825  0.955468  0.993500  0.920333  0.999887
fake orange   0.927877  0.962539  0.949124  0.976442  0.999783
real grape    0.778083  0.875144  0.956816  0.806402  0.999520
fake grape    0.898545  0.946511  0.931022  0.962628  0.999598
real lemon    0.565228  0.722183  0.599588  0.907946  0.999179
fake lemon    0.844903  0.915883  0.996944  0.847097  0.999671
real avocado  0.800300  0.889024  0.825408  0.963383  0.999777
fake avocado  0.818680  0.900252  0.999067  0.819306  0.999783
real pepper   0.858524  0.923827  0.903928  0.944727  0.999431
fake pepper   0.777557  0.874811  0.962932  0.801549  0.999453
real plant    0.880554  0.936433  0.926822  0.946348  0.998716
fake plant    0.869816  0.930326  0.908775  0.953029  0.999886
real banana   0.563111  0.720452  0.871530  0.614084  0.998929
fake banana   0.681199  0.810323  0.751881  0.878733  0.999243
real onion    0.633443  0.775544  0.643605  0.975680  0.999490
fake onion    0.866911  0.928662  0.889159  0.971947  0.999906
real unknown  0.785998  0.880128  0.825397  0.942748  0.999959
fake unknown  0.226193  0.368896  0.255661  0.662441  0.998091
total         0.779187  0.863723  0.872950  0.878616  0.999310
total(-bg)    0.769330  0.857622  0.867274  0.873180  0.999451
2026-09-25 19:58:46,068 - INFO: Epoch accounting: {'epoch': 325, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11284800, 54703, 59010, 78675, 122639, 95628, 95075, 153471, 172261, 76329, 68711, 40915, 48878, 199369, 145564, 143395, 17776, 89642, 85960, 94472, 60588, 9695, 40716], 'crops_with_class': [202, 31, 27, 21, 32, 27, 30, 28, 27, 36, 28, 16, 20, 55, 40, 21, 17, 29, 36, 41, 30, 11, 18], 'targeted_crops_by_class': [0, 3, 6, 1, 5, 7, 5, 8, 3, 5, 3, 2, 7, 8, 7, 1, 6, 3, 8, 5, 4, 2, 3], 'sampled_scene_counts': [1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 2, 0, 2, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 2, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 1, 2, 2, 0, 0, 3, 0, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 2, 2, 1, 2, 0, 0, 1, 0, 2, 1, 1, 3, 1, 1, 2, 1, 0, 1, 3, 3, 0, 0, 3, 0, 3, 1, 3, 0, 1, 3, 0, 1, 3, 0, 1, 0, 0, 0, 1, 3, 4, 1, 3, 1, 2, 1, 2, 2, 1, 2, 0, 0, 2, 1, 4, 1, 1, 0, 1, 4, 4, 2, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 2, 2], 'learning_rate': 2.7761887097509593e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006617524374119642, 'train_segmentation_loss': 0.3031226198862095, 'val_foreground_miou_all22': 0.769330362524575, 'val_psnr_ref1': 38.698309173583986, 'elapsed_seconds': 337.66013050079346, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 326/500 | Batch 10/202 | Rec 0.000598 | Seg 0.354963 | Elapsed 0.2m | ETA 4.0m
Epoch 326/500 | Batch 20/202 | Rec 0.000624 | Seg 0.350675 | Elapsed 0.4m | ETA 3.8m
Epoch 326/500 | Batch 30/202 | Rec 0.000634 | Seg 0.320894 | Elapsed 0.6m | ETA 3.6m
Epoch 326/500 | Batch 40/202 | Rec 0.000621 | Seg 0.314041 | Elapsed 0.8m | ETA 3.4m
Epoch 326/500 | Batch 50/202 | Rec 0.000623 | Seg 0.313303 | Elapsed 1.0m | ETA 3.2m
Epoch 326/500 | Batch 60/202 | Rec 0.000612 | Seg 0.303724 | Elapsed 1.3m | ETA 3.0m
Epoch 326/500 | Batch 70/202 | Rec 0.000604 | Seg 0.292387 | Elapsed 1.5m | ETA 2.8m
Epoch 326/500 | Batch 80/202 | Rec 0.000604 | Seg 0.291893 | Elapsed 1.7m | ETA 2.6m
Epoch 326/500 | Batch 90/202 | Rec 0.000612 | Seg 0.296663 | Elapsed 1.9m | ETA 2.3m
Epoch 326/500 | Batch 100/202 | Rec 0.000616 | Seg 0.298031 | Elapsed 2.1m | ETA 2.1m
Epoch 326/500 | Batch 110/202 | Rec 0.000615 | Seg 0.294426 | Elapsed 2.3m | ETA 1.9m
Epoch 326/500 | Batch 120/202 | Rec 0.000619 | Seg 0.302497 | Elapsed 2.5m | ETA 1.7m
Epoch 326/500 | Batch 130/202 | Rec 0.000615 | Seg 0.302318 | Elapsed 2.7m | ETA 1.5m
Epoch 326/500 | Batch 140/202 | Rec 0.000619 | Seg 0.299504 | Elapsed 2.9m | ETA 1.3m
Epoch 326/500 | Batch 150/202 | Rec 0.000627 | Seg 0.299124 | Elapsed 3.1m | ETA 1.1m
Epoch 326/500 | Batch 160/202 | Rec 0.000636 | Seg 0.307534 | Elapsed 3.3m | ETA 0.9m
Epoch 326/500 | Batch 170/202 | Rec 0.000631 | Seg 0.306093 | Elapsed 3.6m | ETA 0.7m
Epoch 326/500 | Batch 180/202 | Rec 0.000655 | Seg 0.310997 | Elapsed 3.8m | ETA 0.5m
Epoch 326/500 | Batch 190/202 | Rec 0.000650 | Seg 0.309437 | Elapsed 4.0m | ETA 0.3m
Epoch 326/500 | Batch 200/202 | Rec 0.000654 | Seg 0.308862 | Elapsed 4.2m | ETA 0.0m
Epoch 326/500 | Batch 202/202 | Rec 0.000654 | Seg 0.308089 | Elapsed 4.2m | ETA 0.0m

2026-09-25 20:02:59,274 - INFO: Rec loss: 0.000654399511980649
2026-09-25 20:02:59,274 - INFO: Seg loss: 0.3080885711467207
2026-09-25 20:02:59,274 - INFO: λ_rec: 1
2026-09-25 20:02:59,274 - INFO: λ_seg: 0.0001
2026-09-25 20:04:23,245 - INFO: -------------------Epoch: 326------------------------
2026-09-25 20:04:23,249 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.675589  0.974027  0.000141
2026-09-25 20:04:23,256 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995540  0.997715  0.997126  0.998405  0.995742
real potato   0.929612  0.963472  0.958717  0.968375  0.999912
fake potato   0.947942  0.973225  0.962705  0.984080  0.999961
real apple    0.764072  0.866210  0.977915  0.777488  0.999172
fake apple    0.587120  0.739809  0.993124  0.589517  0.998435
real orange   0.940802  0.969448  0.998405  0.942219  0.999922
fake orange   0.937165  0.967513  0.966894  0.968234  0.999814
real grape    0.724867  0.840441  0.957749  0.748812  0.999407
fake grape    0.895293  0.944704  0.935639  0.954049  0.999587
real lemon    0.706226  0.827773  0.770824  0.893924  0.999563
fake lemon    0.804572  0.891655  0.999821  0.804688  0.999586
real avocado  0.940568  0.969324  0.999825  0.940722  0.999945
fake avocado  0.652429  0.789613  0.999805  0.652512  0.999584
real pepper   0.869323  0.930044  0.893195  0.970174  0.999467
fake pepper   0.822697  0.902675  0.968810  0.845080  0.999566
real plant    0.861514  0.925556  0.936126  0.915319  0.998528
fake plant    0.877693  0.934813  0.948323  0.921779  0.999898
real banana   0.718274  0.835991  0.875223  0.800217  0.999295
fake banana   0.673812  0.805073  0.760605  0.855176  0.999238
real onion    0.600186  0.750098  0.608253  0.978382  0.999411
fake onion    0.923202  0.960018  0.960765  0.959371  0.999950
real unknown  0.558100  0.716338  0.582437  0.930343  0.999882
fake unknown  0.208349  0.344812  0.229709  0.691416  0.997786
total         0.779972  0.862884  0.881826  0.873491  0.999289
total(-bg)    0.770174  0.856755  0.876585  0.867813  0.999450
2026-09-25 20:04:23,820 - INFO: Epoch accounting: {'epoch': 326, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11215267, 49505, 71283, 137964, 132297, 72769, 62204, 99905, 184558, 87698, 63534, 28317, 32215, 283086, 139821, 171398, 22286, 92575, 85772, 85526, 63779, 10667, 45846], 'crops_with_class': [202, 33, 31, 35, 32, 22, 26, 20, 30, 38, 28, 10, 13, 66, 36, 20, 21, 24, 31, 37, 27, 12, 25], 'targeted_crops_by_class': [0, 8, 6, 2, 4, 4, 7, 4, 1, 5, 3, 3, 5, 10, 3, 5, 7, 6, 2, 4, 6, 6, 4], 'sampled_scene_counts': [1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 2, 2, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 3, 2, 0, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 4, 1, 2, 1, 2, 3, 0, 0, 1, 3, 1, 3, 0, 0, 0, 1, 1, 1, 1, 1, 3, 3, 0, 2, 0, 4, 1, 0, 5, 1, 1, 1, 1, 1, 4, 4, 0, 1, 3, 2, 1, 2, 3, 1, 1, 3, 4, 2, 2, 1, 2, 1, 0, 1, 2, 3, 2, 2, 1, 2, 0, 2, 1, 1, 1, 2, 3, 3, 1, 1, 0, 2, 3, 1, 0, 1, 2, 0, 0, 1, 1, 1], 'learning_rate': 2.748222382549005e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000654399511980649, 'train_segmentation_loss': 0.3080885711467207, 'val_foreground_miou_all22': 0.7701735766147647, 'val_psnr_ref1': 38.675588836669924, 'elapsed_seconds': 337.7426471710205, 'peak_cuda_allocated_gib': 7.508335113525391}

Epoch 327/500 | Batch 10/202 | Rec 0.000574 | Seg 0.292542 | Elapsed 0.2m | ETA 3.9m
Epoch 327/500 | Batch 20/202 | Rec 0.000644 | Seg 0.298281 | Elapsed 0.4m | ETA 3.7m
Epoch 327/500 | Batch 30/202 | Rec 0.000643 | Seg 0.311985 | Elapsed 0.6m | ETA 3.6m
Epoch 327/500 | Batch 40/202 | Rec 0.000673 | Seg 0.299530 | Elapsed 0.8m | ETA 3.4m
Epoch 327/500 | Batch 50/202 | Rec 0.000659 | Seg 0.299056 | Elapsed 1.0m | ETA 3.2m
Epoch 327/500 | Batch 60/202 | Rec 0.000666 | Seg 0.303203 | Elapsed 1.3m | ETA 3.0m
Epoch 327/500 | Batch 70/202 | Rec 0.000647 | Seg 0.294851 | Elapsed 1.5m | ETA 2.8m
Epoch 327/500 | Batch 80/202 | Rec 0.000638 | Seg 0.290656 | Elapsed 1.7m | ETA 2.6m
Epoch 327/500 | Batch 90/202 | Rec 0.000639 | Seg 0.292888 | Elapsed 1.9m | ETA 2.4m
Epoch 327/500 | Batch 100/202 | Rec 0.000636 | Seg 0.289389 | Elapsed 2.1m | ETA 2.2m
Epoch 327/500 | Batch 110/202 | Rec 0.000635 | Seg 0.290565 | Elapsed 2.3m | ETA 1.9m
Epoch 327/500 | Batch 120/202 | Rec 0.000658 | Seg 0.292282 | Elapsed 2.5m | ETA 1.7m
Epoch 327/500 | Batch 130/202 | Rec 0.000659 | Seg 0.295088 | Elapsed 2.7m | ETA 1.5m
Epoch 327/500 | Batch 140/202 | Rec 0.000651 | Seg 0.293293 | Elapsed 3.0m | ETA 1.3m
Epoch 327/500 | Batch 150/202 | Rec 0.000651 | Seg 0.294193 | Elapsed 3.2m | ETA 1.1m
Epoch 327/500 | Batch 160/202 | Rec 0.000648 | Seg 0.299735 | Elapsed 3.4m | ETA 0.9m
Epoch 327/500 | Batch 170/202 | Rec 0.000642 | Seg 0.295048 | Elapsed 3.6m | ETA 0.7m
Epoch 327/500 | Batch 180/202 | Rec 0.000636 | Seg 0.291655 | Elapsed 3.8m | ETA 0.5m
Epoch 327/500 | Batch 190/202 | Rec 0.000639 | Seg 0.292996 | Elapsed 4.0m | ETA 0.3m
Epoch 327/500 | Batch 200/202 | Rec 0.000634 | Seg 0.289721 | Elapsed 4.2m | ETA 0.0m
Epoch 327/500 | Batch 202/202 | Rec 0.000635 | Seg 0.290382 | Elapsed 4.3m | ETA 0.0m

2026-09-25 20:08:39,779 - INFO: Rec loss: 0.0006349303095145058
2026-09-25 20:08:39,779 - INFO: Seg loss: 0.29038211806575853
2026-09-25 20:08:39,779 - INFO: λ_rec: 1
2026-09-25 20:08:39,779 - INFO: λ_seg: 0.0001
2026-09-25 20:09:58,603 - INFO: -------------------Epoch: 327------------------------
2026-09-25 20:09:58,607 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.640911  0.974436  0.000143
2026-09-25 20:09:58,615 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995726  0.997808  0.997349  0.998368  0.995920
real potato   0.908930  0.952242  0.926127  0.979980  0.999883
fake potato   0.959109  0.979078  0.966150  0.992459  0.999969
real apple    0.729132  0.843301  0.981220  0.739452  0.999052
fake apple    0.579948  0.734089  0.986964  0.584425  0.998402
real orange   0.916455  0.956357  0.994747  0.920912  0.999889
fake orange   0.931903  0.964701  0.948311  0.981772  0.999795
real grape    0.747938  0.855745  0.908755  0.808668  0.999431
fake grape    0.904458  0.949782  0.948056  0.951615  0.999628
real lemon    0.763461  0.865817  0.823247  0.913139  0.999668
fake lemon    0.845855  0.916442  0.997370  0.847746  0.999673
real avocado  0.939780  0.968905  0.969274  0.968637  0.999942
fake avocado  0.679373  0.809031  0.999625  0.679546  0.999616
real pepper   0.870265  0.930583  0.902682  0.960370  0.999476
fake pepper   0.827643  0.905645  0.951116  0.864413  0.999571
real plant    0.863417  0.926653  0.947409  0.906883  0.998565
fake plant    0.803082  0.890739  0.847258  0.939034  0.999817
real banana   0.764635  0.866571  0.874775  0.858617  0.999406
fake banana   0.715911  0.834388  0.795756  0.877074  0.999360
real onion    0.609926  0.757659  0.619410  0.975511  0.999436
fake onion    0.932848  0.965208  0.969734  0.960822  0.999956
real unknown  0.510671  0.676039  0.522078  0.958969  0.999853
fake unknown  0.221917  0.363190  0.243144  0.717675  0.997880
total         0.783582  0.865651  0.874807  0.886352  0.999313
total(-bg)    0.773939  0.859644  0.869237  0.881260  0.999467
2026-09-25 20:09:59,162 - INFO: Epoch accounting: {'epoch': 327, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11320617, 50281, 53076, 146507, 159015, 98152, 75760, 116993, 198592, 90163, 74557, 25644, 24485, 201649, 100021, 156233, 28181, 62673, 73290, 69919, 49917, 11123, 51424], 'crops_with_class': [202, 29, 26, 38, 43, 28, 24, 26, 35, 42, 31, 10, 11, 48, 28, 22, 23, 22, 29, 32, 23, 14, 22], 'targeted_crops_by_class': [0, 5, 5, 6, 5, 4, 7, 2, 0, 9, 10, 2, 3, 3, 4, 7, 3, 3, 2, 3, 2, 2, 7], 'sampled_scene_counts': [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 0, 1, 2, 1, 2, 2, 0, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 0, 0, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 2, 4, 1, 2, 1, 3, 1, 1, 2, 0, 1, 3, 1, 1, 0, 3, 0, 2, 2, 1, 2, 0, 3, 0, 0, 0, 1, 0, 2, 2, 2, 2, 3, 1, 1, 2, 1, 1, 2, 4, 1, 0, 1, 2, 3, 3, 1, 4, 1, 3, 1, 0, 0, 2, 0, 1, 4, 1, 3, 1, 0, 2, 0, 3, 1, 1, 0, 1, 1, 0, 1, 1, 3, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 3], 'learning_rate': 2.720345445150324e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006349303095145058, 'train_segmentation_loss': 0.29038211806575853, 'val_foreground_miou_all22': 0.7739389927738121, 'val_psnr_ref1': 38.640910949707035, 'elapsed_seconds': 335.3329658508301, 'peak_cuda_allocated_gib': 7.511997222900391}

Epoch 328/500 | Batch 10/202 | Rec 0.000644 | Seg 0.321478 | Elapsed 0.2m | ETA 4.0m
Epoch 328/500 | Batch 20/202 | Rec 0.000639 | Seg 0.315314 | Elapsed 0.4m | ETA 3.8m
Epoch 328/500 | Batch 30/202 | Rec 0.000646 | Seg 0.310084 | Elapsed 0.6m | ETA 3.6m
Epoch 328/500 | Batch 40/202 | Rec 0.000652 | Seg 0.311691 | Elapsed 0.8m | ETA 3.4m
Epoch 328/500 | Batch 50/202 | Rec 0.000649 | Seg 0.318152 | Elapsed 1.1m | ETA 3.2m
Epoch 328/500 | Batch 60/202 | Rec 0.000617 | Seg 0.302489 | Elapsed 1.3m | ETA 3.0m
Epoch 328/500 | Batch 70/202 | Rec 0.000627 | Seg 0.306144 | Elapsed 1.5m | ETA 2.8m
Epoch 328/500 | Batch 80/202 | Rec 0.000622 | Seg 0.295591 | Elapsed 1.7m | ETA 2.6m
Epoch 328/500 | Batch 90/202 | Rec 0.000640 | Seg 0.305665 | Elapsed 1.9m | ETA 2.3m
Epoch 328/500 | Batch 100/202 | Rec 0.000665 | Seg 0.325429 | Elapsed 2.1m | ETA 2.1m
Epoch 328/500 | Batch 110/202 | Rec 0.000654 | Seg 0.317594 | Elapsed 2.3m | ETA 1.9m
Epoch 328/500 | Batch 120/202 | Rec 0.000651 | Seg 0.313987 | Elapsed 2.5m | ETA 1.7m
Epoch 328/500 | Batch 130/202 | Rec 0.000641 | Seg 0.311031 | Elapsed 2.7m | ETA 1.5m
Epoch 328/500 | Batch 140/202 | Rec 0.000641 | Seg 0.313938 | Elapsed 2.9m | ETA 1.3m
Epoch 328/500 | Batch 150/202 | Rec 0.000639 | Seg 0.314557 | Elapsed 3.1m | ETA 1.1m
Epoch 328/500 | Batch 160/202 | Rec 0.000636 | Seg 0.311447 | Elapsed 3.3m | ETA 0.9m
Epoch 328/500 | Batch 170/202 | Rec 0.000640 | Seg 0.309580 | Elapsed 3.5m | ETA 0.7m
Epoch 328/500 | Batch 180/202 | Rec 0.000639 | Seg 0.308074 | Elapsed 3.7m | ETA 0.5m
Epoch 328/500 | Batch 190/202 | Rec 0.000641 | Seg 0.306514 | Elapsed 4.0m | ETA 0.3m
Epoch 328/500 | Batch 200/202 | Rec 0.000635 | Seg 0.304980 | Elapsed 4.2m | ETA 0.0m
Epoch 328/500 | Batch 202/202 | Rec 0.000634 | Seg 0.306412 | Elapsed 4.2m | ETA 0.0m

2026-09-25 20:14:12,108 - INFO: Rec loss: 0.0006337618004469579
2026-09-25 20:14:12,108 - INFO: Seg loss: 0.3064117461977766
2026-09-25 20:14:12,108 - INFO: λ_rec: 1
2026-09-25 20:14:12,108 - INFO: λ_seg: 0.0001
2026-09-25 20:15:31,580 - INFO: -------------------Epoch: 328------------------------
2026-09-25 20:15:31,584 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.875637  0.974202  0.000135
2026-09-25 20:15:31,592 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995728  0.997809  0.996914  0.998807  0.995920
real potato   0.269702  0.424793  1.000000  0.269702  0.999126
fake potato   0.668238  0.801082  0.968518  0.683075  0.999753
real apple    0.683357  0.811848  0.748712  0.886732  0.998582
fake apple    0.750738  0.857575  0.966218  0.770975  0.999034
real orange   0.832737  0.908686  0.996271  0.835340  0.999779
fake orange   0.899902  0.947264  0.918084  0.978467  0.999688
real grape    0.795382  0.885981  0.966169  0.818169  0.999561
fake grape    0.881859  0.937171  0.933825  0.940643  0.999534
real lemon    0.374675  0.545068  0.398726  0.861335  0.998311
fake lemon    0.845322  0.916128  0.962810  0.873855  0.999662
real avocado  0.747774  0.855638  0.768396  0.965353  0.999697
fake avocado  0.835585  0.910379  0.999390  0.836011  0.999803
real pepper   0.773776  0.872412  0.838235  0.909603  0.999027
fake pepper   0.635655  0.777200  0.949635  0.657832  0.999101
real plant    0.875178  0.933384  0.946860  0.920384  0.998687
fake plant    0.784968  0.879482  0.947136  0.820936  0.999821
real banana   0.218436  0.358520  0.916504  0.222871  0.998208
fake banana   0.696240  0.820871  0.834461  0.807814  0.999352
real onion    0.622234  0.767082  0.742803  0.793109  0.999565
fake onion    0.927557  0.962367  0.994837  0.932044  0.999954
real unknown  0.924386  0.960657  0.989878  0.933206  0.999988
fake unknown  0.258069  0.410220  0.295569  0.670409  0.998376
total         0.708587  0.806157  0.873041  0.799420  0.999153
total(-bg)    0.695535  0.797446  0.867411  0.790357  0.999300
2026-09-25 20:15:32,161 - INFO: Epoch accounting: {'epoch': 328, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11258412, 40662, 49824, 100822, 207966, 83717, 83197, 148756, 200611, 72041, 52789, 36583, 41577, 225369, 85812, 178174, 25923, 90475, 67384, 64631, 53742, 12354, 57451], 'crops_with_class': [202, 24, 23, 33, 48, 26, 29, 29, 35, 31, 23, 13, 14, 53, 26, 26, 24, 25, 31, 33, 24, 13, 26], 'targeted_crops_by_class': [0, 7, 5, 3, 8, 3, 6, 6, 3, 4, 5, 3, 5, 3, 3, 6, 4, 5, 3, 3, 5, 4, 6], 'sampled_scene_counts': [1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 3, 1, 2, 1, 2, 0, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 0, 1, 2, 0, 2, 1, 0, 1, 2, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 1, 2, 3, 0, 1, 1, 2, 0, 0, 1, 3, 1, 4, 1, 1, 2, 2, 1, 1, 0, 3, 1, 1, 0, 1, 2, 3, 1, 2, 0, 1, 1, 0, 2, 0, 3, 2, 1, 1, 4, 1, 4, 3, 1, 4, 0, 1, 0, 1, 1, 2, 0, 3, 2, 1, 2, 1, 1, 1, 1, 3, 2, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 2, 3, 4], 'learning_rate': 2.692558998088671e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006337618004469579, 'train_segmentation_loss': 0.3064117461977766, 'val_foreground_miou_all22': 0.695534900940863, 'val_psnr_ref1': 38.87563674926758, 'elapsed_seconds': 332.9886224269867, 'peak_cuda_allocated_gib': 7.512485504150391}

Epoch 329/500 | Batch 10/202 | Rec 0.000694 | Seg 0.328151 | Elapsed 0.2m | ETA 4.2m
Epoch 329/500 | Batch 20/202 | Rec 0.000633 | Seg 0.313939 | Elapsed 0.4m | ETA 3.9m
Epoch 329/500 | Batch 30/202 | Rec 0.000617 | Seg 0.303052 | Elapsed 0.6m | ETA 3.7m
Epoch 329/500 | Batch 40/202 | Rec 0.000630 | Seg 0.295135 | Elapsed 0.9m | ETA 3.5m
Epoch 329/500 | Batch 50/202 | Rec 0.000642 | Seg 0.296142 | Elapsed 1.1m | ETA 3.2m
Epoch 329/500 | Batch 60/202 | Rec 0.000648 | Seg 0.296703 | Elapsed 1.3m | ETA 3.0m
Epoch 329/500 | Batch 70/202 | Rec 0.000652 | Seg 0.299358 | Elapsed 1.5m | ETA 2.8m
Epoch 329/500 | Batch 80/202 | Rec 0.000634 | Seg 0.292106 | Elapsed 1.7m | ETA 2.6m
Epoch 329/500 | Batch 90/202 | Rec 0.000615 | Seg 0.286551 | Elapsed 1.9m | ETA 2.4m
Epoch 329/500 | Batch 100/202 | Rec 0.000641 | Seg 0.283960 | Elapsed 2.1m | ETA 2.2m
Epoch 329/500 | Batch 110/202 | Rec 0.000627 | Seg 0.282491 | Elapsed 2.3m | ETA 1.9m
Epoch 329/500 | Batch 120/202 | Rec 0.000626 | Seg 0.280659 | Elapsed 2.5m | ETA 1.7m
Epoch 329/500 | Batch 130/202 | Rec 0.000624 | Seg 0.286503 | Elapsed 2.8m | ETA 1.5m
Epoch 329/500 | Batch 140/202 | Rec 0.000624 | Seg 0.288234 | Elapsed 3.0m | ETA 1.3m
Epoch 329/500 | Batch 150/202 | Rec 0.000623 | Seg 0.291028 | Elapsed 3.2m | ETA 1.1m
Epoch 329/500 | Batch 160/202 | Rec 0.000622 | Seg 0.287013 | Elapsed 3.4m | ETA 0.9m
Epoch 329/500 | Batch 170/202 | Rec 0.000617 | Seg 0.282910 | Elapsed 3.6m | ETA 0.7m
Epoch 329/500 | Batch 180/202 | Rec 0.000633 | Seg 0.291591 | Elapsed 3.8m | ETA 0.5m
Epoch 329/500 | Batch 190/202 | Rec 0.000639 | Seg 0.295200 | Elapsed 4.0m | ETA 0.3m
Epoch 329/500 | Batch 200/202 | Rec 0.000642 | Seg 0.300977 | Elapsed 4.2m | ETA 0.0m
Epoch 329/500 | Batch 202/202 | Rec 0.000642 | Seg 0.301818 | Elapsed 4.3m | ETA 0.0m

2026-09-25 20:19:48,186 - INFO: Rec loss: 0.0006419659671742506
2026-09-25 20:19:48,187 - INFO: Seg loss: 0.3018183677945987
2026-09-25 20:19:48,187 - INFO: λ_rec: 1
2026-09-25 20:19:48,187 - INFO: λ_seg: 0.0001
2026-09-25 20:21:05,273 - INFO: -------------------Epoch: 329------------------------
2026-09-25 20:21:05,277 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.726892  0.973972  0.00014
2026-09-25 20:21:05,284 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995853  0.997872  0.997194  0.998652  0.996041
real potato   0.224178  0.366220  1.000000  0.224178  0.999072
fake potato   0.642813  0.782528  0.964121  0.658567  0.999733
real apple    0.643013  0.782675  0.719262  0.858470  0.998356
fake apple    0.687146  0.814517  0.927885  0.725913  0.998752
real orange   0.889557  0.941501  0.998572  0.890690  0.999854
fake orange   0.922448  0.959610  0.945344  0.974416  0.999765
real grape    0.774150  0.872650  0.964112  0.797121  0.999514
fake grape    0.867927  0.929245  0.909127  0.950377  0.999465
real lemon    0.322952  0.488188  0.345933  0.829395  0.997957
fake lemon    0.812835  0.896706  0.920489  0.874216  0.999574
real avocado  0.716591  0.834851  0.737233  0.962397  0.999646
fake avocado  0.805251  0.892071  0.999367  0.805662  0.999767
real pepper   0.863853  0.926904  0.948016  0.906808  0.999477
fake pepper   0.757395  0.861902  0.962793  0.780232  0.999404
real plant    0.878461  0.935249  0.918769  0.952435  0.998682
fake plant    0.824677  0.903866  0.974086  0.843175  0.999857
real banana   0.047358  0.090424  0.927152  0.047535  0.997851
fake banana   0.645168  0.784269  0.803708  0.765843  0.999225
real onion    0.488409  0.656234  0.761830  0.576423  0.999454
fake onion    0.665382  0.799026  0.994240  0.667956  0.999788
real unknown  0.937023  0.967438  1.000000  0.937023  0.999990
fake unknown  0.201579  0.335486  0.225912  0.651757  0.997825
total         0.678870  0.774758  0.867180  0.768663  0.999089
total(-bg)    0.664462  0.764616  0.861271  0.758209  0.999228
2026-09-25 20:21:05,844 - INFO: Epoch accounting: {'epoch': 329, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11267719, 47062, 65422, 135606, 170667, 80939, 76773, 104073, 178028, 78304, 76463, 50205, 32997, 182631, 122714, 184570, 26180, 83211, 66090, 86754, 65951, 8589, 47324], 'crops_with_class': [202, 29, 26, 40, 41, 26, 31, 24, 32, 35, 34, 17, 13, 52, 29, 21, 21, 24, 27, 34, 28, 9, 18], 'targeted_crops_by_class': [0, 1, 4, 6, 5, 3, 3, 2, 4, 3, 3, 6, 3, 4, 5, 3, 5, 6, 0, 7, 5, 6, 4], 'sampled_scene_counts': [0, 1, 2, 1, 1, 1, 0, 1, 2, 5, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 2, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 0, 3, 1, 0, 2, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 3, 1, 2, 1, 3, 4, 1, 0, 1, 2, 1, 1, 2, 1, 1, 2, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 3, 1, 1, 1, 1, 1, 2, 3, 0, 1, 2, 1, 2, 1, 1, 2, 2, 2, 3, 1, 2, 0, 1, 3, 1, 0, 1, 2, 2, 0, 1, 2, 1, 2, 1, 1, 3, 1, 4, 0, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 2, 2, 1, 1, 0, 3], 'learning_rate': 2.6648641383254002e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006419659671742506, 'train_segmentation_loss': 0.3018183677945987, 'val_foreground_miou_all22': 0.6644621744770174, 'val_psnr_ref1': 38.72689178466797, 'elapsed_seconds': 333.6758191585541, 'peak_cuda_allocated_gib': 7.510532379150391}

Epoch 330/500 | Batch 10/202 | Rec 0.000651 | Seg 0.280570 | Elapsed 0.2m | ETA 3.9m
Epoch 330/500 | Batch 20/202 | Rec 0.000666 | Seg 0.265226 | Elapsed 0.4m | ETA 3.7m
Epoch 330/500 | Batch 30/202 | Rec 0.000726 | Seg 0.264558 | Elapsed 0.6m | ETA 3.5m
Epoch 330/500 | Batch 40/202 | Rec 0.000711 | Seg 0.272780 | Elapsed 0.8m | ETA 3.4m
Epoch 330/500 | Batch 50/202 | Rec 0.000707 | Seg 0.288982 | Elapsed 1.0m | ETA 3.2m
Epoch 330/500 | Batch 60/202 | Rec 0.000671 | Seg 0.279517 | Elapsed 1.3m | ETA 3.0m
Epoch 330/500 | Batch 70/202 | Rec 0.000680 | Seg 0.290534 | Elapsed 1.5m | ETA 2.8m
Epoch 330/500 | Batch 80/202 | Rec 0.000669 | Seg 0.289774 | Elapsed 1.7m | ETA 2.5m
Epoch 330/500 | Batch 90/202 | Rec 0.000665 | Seg 0.295948 | Elapsed 1.9m | ETA 2.3m
Epoch 330/500 | Batch 100/202 | Rec 0.000661 | Seg 0.295335 | Elapsed 2.1m | ETA 2.1m
Epoch 330/500 | Batch 110/202 | Rec 0.000667 | Seg 0.296629 | Elapsed 2.3m | ETA 1.9m
Epoch 330/500 | Batch 120/202 | Rec 0.000661 | Seg 0.304137 | Elapsed 2.5m | ETA 1.7m
Epoch 330/500 | Batch 130/202 | Rec 0.000655 | Seg 0.304081 | Elapsed 2.7m | ETA 1.5m
Epoch 330/500 | Batch 140/202 | Rec 0.000660 | Seg 0.309038 | Elapsed 2.9m | ETA 1.3m
Epoch 330/500 | Batch 150/202 | Rec 0.000662 | Seg 0.313080 | Elapsed 3.1m | ETA 1.1m
Epoch 330/500 | Batch 160/202 | Rec 0.000659 | Seg 0.313652 | Elapsed 3.3m | ETA 0.9m
Epoch 330/500 | Batch 170/202 | Rec 0.000655 | Seg 0.311222 | Elapsed 3.5m | ETA 0.7m
Epoch 330/500 | Batch 180/202 | Rec 0.000672 | Seg 0.312238 | Elapsed 3.7m | ETA 0.5m
Epoch 330/500 | Batch 190/202 | Rec 0.000668 | Seg 0.307203 | Elapsed 3.9m | ETA 0.2m
Epoch 330/500 | Batch 200/202 | Rec 0.000680 | Seg 0.304996 | Elapsed 4.2m | ETA 0.0m
Epoch 330/500 | Batch 202/202 | Rec 0.000679 | Seg 0.304086 | Elapsed 4.2m | ETA 0.0m

2026-09-25 20:25:17,584 - INFO: Rec loss: 0.0006785030925697139
2026-09-25 20:25:17,584 - INFO: Seg loss: 0.30408636840189446
2026-09-25 20:25:17,584 - INFO: λ_rec: 1
2026-09-25 20:25:17,585 - INFO: λ_seg: 0.0001
2026-09-25 20:26:39,674 - INFO: -------------------Epoch: 330------------------------
2026-09-25 20:26:39,678 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.780408  0.974222  0.000138
2026-09-25 20:26:39,685 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995598  0.997744  0.996852  0.998738  0.995796
real potato   0.675338  0.806163  0.985806  0.681969  0.999608
fake potato   0.770468  0.870306  0.980320  0.782572  0.999830
real apple    0.755632  0.860759  0.865680  0.855993  0.999045
fake apple    0.646698  0.785400  0.987034  0.652239  0.998655
real orange   0.951754  0.975231  0.996616  0.954840  0.999936
fake orange   0.941284  0.969704  0.974899  0.964663  0.999828
real grape    0.774531  0.872891  0.921820  0.828985  0.999496
fake grape    0.890868  0.942235  0.933493  0.951244  0.999569
real lemon    0.657900  0.793605  0.718313  0.886653  0.999458
fake lemon    0.846425  0.916776  0.999064  0.847097  0.999675
real avocado  0.928391  0.962816  0.959257  0.966502  0.999931
fake avocado  0.691994  0.817914  0.999632  0.692170  0.999631
real pepper   0.765171  0.866916  0.787234  0.964667  0.998917
fake pepper   0.572363  0.727982  0.955288  0.588119  0.998953
real plant    0.855283  0.921948  0.955086  0.891125  0.998492
fake plant    0.886817  0.939964  0.950421  0.929831  0.999906
real banana   0.700013  0.823489  0.910512  0.751732  0.999276
fake banana   0.751030  0.857765  0.854182  0.861480  0.999475
real onion    0.675217  0.806075  0.725480  0.906941  0.999606
fake onion    0.939933  0.968986  0.993145  0.946070  0.999962
real unknown  0.791734  0.883713  0.840069  0.932252  0.999961
fake unknown  0.234823  0.380296  0.255558  0.743209  0.997959
total         0.769533  0.858638  0.893294  0.851265  0.999259
total(-bg)    0.759258  0.852315  0.888587  0.844561  0.999417
2026-09-25 20:26:40,336 - INFO: Epoch accounting: {'epoch': 330, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11249732, 54821, 84273, 105222, 132942, 77843, 59789, 150695, 178910, 86072, 63958, 34580, 20049, 197990, 129907, 202254, 32591, 78859, 84807, 89641, 68274, 14917, 40146], 'crops_with_class': [202, 39, 37, 29, 36, 25, 22, 30, 36, 35, 32, 12, 8, 57, 34, 29, 29, 27, 35, 43, 28, 16, 23], 'targeted_crops_by_class': [0, 10, 6, 5, 5, 6, 6, 2, 3, 5, 6, 3, 1, 7, 5, 6, 10, 4, 5, 8, 7, 7, 2], 'sampled_scene_counts': [2, 1, 2, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 2, 2, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 3, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 4, 1, 3, 2, 3, 1, 0, 0, 3, 0, 1, 1, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 0, 1, 0, 3, 2, 1, 0, 6, 3, 1, 0, 1, 2, 4, 2, 1, 1, 1, 4, 5, 0, 1, 2, 5, 0, 1, 3, 3, 0, 1, 1, 0, 4, 1, 1, 1, 0, 4, 0, 1, 4, 1, 3, 3, 2, 1, 1, 1, 3, 2, 0, 2, 1, 0, 3, 1, 0, 1, 1, 1], 'learning_rate': 2.637261959206148e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006785030925697139, 'train_segmentation_loss': 0.30408636840189446, 'val_foreground_miou_all22': 0.7592575569933178, 'val_psnr_ref1': 38.78040817260742, 'elapsed_seconds': 334.48272371292114, 'peak_cuda_allocated_gib': 7.513950347900391}

Epoch 331/500 | Batch 10/202 | Rec 0.000553 | Seg 0.234598 | Elapsed 0.2m | ETA 3.9m
Epoch 331/500 | Batch 20/202 | Rec 0.000594 | Seg 0.273250 | Elapsed 0.4m | ETA 3.8m
Epoch 331/500 | Batch 30/202 | Rec 0.000586 | Seg 0.268854 | Elapsed 0.6m | ETA 3.6m
Epoch 331/500 | Batch 40/202 | Rec 0.000549 | Seg 0.263092 | Elapsed 0.8m | ETA 3.4m
Epoch 331/500 | Batch 50/202 | Rec 0.000564 | Seg 0.272124 | Elapsed 1.0m | ETA 3.2m
Epoch 331/500 | Batch 60/202 | Rec 0.000562 | Seg 0.273547 | Elapsed 1.3m | ETA 3.0m
Epoch 331/500 | Batch 70/202 | Rec 0.000585 | Seg 0.282204 | Elapsed 1.5m | ETA 2.8m
Epoch 331/500 | Batch 80/202 | Rec 0.000590 | Seg 0.283721 | Elapsed 1.7m | ETA 2.6m
Epoch 331/500 | Batch 90/202 | Rec 0.000595 | Seg 0.287541 | Elapsed 1.9m | ETA 2.4m
Epoch 331/500 | Batch 100/202 | Rec 0.000605 | Seg 0.288576 | Elapsed 2.1m | ETA 2.1m
Epoch 331/500 | Batch 110/202 | Rec 0.000602 | Seg 0.288926 | Elapsed 2.3m | ETA 1.9m
Epoch 331/500 | Batch 120/202 | Rec 0.000605 | Seg 0.294264 | Elapsed 2.5m | ETA 1.7m
Epoch 331/500 | Batch 130/202 | Rec 0.000604 | Seg 0.289600 | Elapsed 2.7m | ETA 1.5m
Epoch 331/500 | Batch 140/202 | Rec 0.000607 | Seg 0.287161 | Elapsed 2.9m | ETA 1.3m
Epoch 331/500 | Batch 150/202 | Rec 0.000604 | Seg 0.288733 | Elapsed 3.2m | ETA 1.1m
Epoch 331/500 | Batch 160/202 | Rec 0.000607 | Seg 0.287592 | Elapsed 3.4m | ETA 0.9m
Epoch 331/500 | Batch 170/202 | Rec 0.000607 | Seg 0.289852 | Elapsed 3.6m | ETA 0.7m
Epoch 331/500 | Batch 180/202 | Rec 0.000600 | Seg 0.289783 | Elapsed 3.8m | ETA 0.5m
Epoch 331/500 | Batch 190/202 | Rec 0.000604 | Seg 0.289883 | Elapsed 4.0m | ETA 0.3m
Epoch 331/500 | Batch 200/202 | Rec 0.000607 | Seg 0.289810 | Elapsed 4.2m | ETA 0.0m
Epoch 331/500 | Batch 202/202 | Rec 0.000609 | Seg 0.289484 | Elapsed 4.3m | ETA 0.0m

2026-09-25 20:30:55,667 - INFO: Rec loss: 0.0006087243295906314
2026-09-25 20:30:55,667 - INFO: Seg loss: 0.28948412665931306
2026-09-25 20:30:55,667 - INFO: λ_rec: 1
2026-09-25 20:30:55,667 - INFO: λ_seg: 0.0001
2026-09-25 20:32:20,689 - INFO: -------------------Epoch: 331------------------------
2026-09-25 20:32:20,693 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.880805  0.97431  0.000135
2026-09-25 20:32:20,700 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995828  0.997860  0.997332  0.998488  0.996018
real potato   0.873683  0.932534  0.886743  0.983423  0.999830
fake potato   0.956680  0.977811  0.966067  0.989946  0.999967
real apple    0.684877  0.812921  0.981906  0.693631  0.998899
fake apple    0.536387  0.698199  0.987511  0.540050  0.998238
real orange   0.913480  0.954734  0.997351  0.915702  0.999886
fake orange   0.930483  0.963940  0.953682  0.974523  0.999792
real grape    0.725425  0.840816  0.930567  0.766937  0.999394
fake grape    0.909422  0.952513  0.948067  0.957101  0.999647
real lemon    0.756655  0.861423  0.917535  0.811867  0.999693
fake lemon    0.845098  0.915997  0.996018  0.847962  0.999671
real avocado  0.924024  0.960462  0.999290  0.924631  0.999929
fake avocado  0.599567  0.749614  0.999575  0.599719  0.999521
real pepper   0.922074  0.959407  0.943142  0.976347  0.999698
fake pepper   0.874063  0.932750  0.925135  0.940593  0.999677
real plant    0.857172  0.923044  0.941044  0.905815  0.998490
fake plant    0.830597  0.907411  0.876272  0.940951  0.999847
real banana   0.821627  0.902031  0.891668  0.912739  0.999555
fake banana   0.676526  0.807007  0.751970  0.870853  0.999234
real onion    0.577704  0.732288  0.586389  0.975004  0.999356
fake onion    0.939394  0.968700  0.978063  0.959613  0.999961
real unknown  0.414583  0.586113  0.423945  0.949427  0.999786
fake unknown  0.186929  0.314943  0.206504  0.663528  0.997568
total         0.771838  0.854457  0.873295  0.873863  0.999289
total(-bg)    0.761657  0.847939  0.867657  0.868198  0.999438
2026-09-25 20:32:21,250 - INFO: Epoch accounting: {'epoch': 331, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11339681, 38698, 59643, 115517, 144860, 67724, 67726, 121284, 243728, 64140, 81930, 39511, 41043, 204372, 127078, 104424, 25226, 99077, 66171, 74063, 53434, 11062, 47880], 'crops_with_class': [202, 27, 28, 30, 37, 22, 22, 23, 44, 28, 29, 12, 17, 51, 31, 19, 23, 24, 30, 36, 24, 13, 21], 'targeted_crops_by_class': [0, 6, 3, 3, 5, 3, 3, 1, 3, 3, 7, 2, 7, 2, 4, 5, 5, 3, 6, 4, 4, 6, 5], 'sampled_scene_counts': [0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1, 0, 2, 1, 0, 0, 0, 0, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 2, 2, 2, 0, 0, 2, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 1, 1, 1, 1, 2, 2, 1, 3, 1, 0, 1, 1, 3, 2, 2, 0, 2, 2, 0, 2, 1, 0, 1, 4, 0, 1, 1, 3, 0, 1, 2, 2, 3, 3, 1, 1, 1, 2, 3, 3, 1, 1, 3, 1, 4, 1, 2, 0, 2, 0, 1, 0, 1, 3, 1, 0, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 4, 1, 0, 1, 1, 1, 1, 1, 1, 2, 1], 'learning_rate': 2.6097535504176915e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006087243295906314, 'train_segmentation_loss': 0.28948412665931306, 'val_foreground_miou_all22': 0.7616568636848712, 'val_psnr_ref1': 38.88080520629883, 'elapsed_seconds': 340.9054877758026, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 332/500 | Batch 10/202 | Rec 0.000615 | Seg 0.268792 | Elapsed 0.2m | ETA 4.0m
Epoch 332/500 | Batch 20/202 | Rec 0.000623 | Seg 0.320262 | Elapsed 0.4m | ETA 3.8m
Epoch 332/500 | Batch 30/202 | Rec 0.000621 | Seg 0.323389 | Elapsed 0.6m | ETA 3.6m
Epoch 332/500 | Batch 40/202 | Rec 0.000633 | Seg 0.331575 | Elapsed 0.8m | ETA 3.4m
Epoch 332/500 | Batch 50/202 | Rec 0.000644 | Seg 0.322437 | Elapsed 1.1m | ETA 3.2m
Epoch 332/500 | Batch 60/202 | Rec 0.000656 | Seg 0.329012 | Elapsed 1.3m | ETA 3.0m
Epoch 332/500 | Batch 70/202 | Rec 0.000648 | Seg 0.319936 | Elapsed 1.5m | ETA 2.8m
Epoch 332/500 | Batch 80/202 | Rec 0.000639 | Seg 0.313430 | Elapsed 1.7m | ETA 2.6m
Epoch 332/500 | Batch 90/202 | Rec 0.000640 | Seg 0.307547 | Elapsed 1.9m | ETA 2.4m
Epoch 332/500 | Batch 100/202 | Rec 0.000651 | Seg 0.311238 | Elapsed 2.1m | ETA 2.1m
Epoch 332/500 | Batch 110/202 | Rec 0.000652 | Seg 0.310996 | Elapsed 2.3m | ETA 1.9m
Epoch 332/500 | Batch 120/202 | Rec 0.000654 | Seg 0.307822 | Elapsed 2.5m | ETA 1.7m
Epoch 332/500 | Batch 130/202 | Rec 0.000653 | Seg 0.309739 | Elapsed 2.7m | ETA 1.5m
Epoch 332/500 | Batch 140/202 | Rec 0.000651 | Seg 0.311338 | Elapsed 2.9m | ETA 1.3m
Epoch 332/500 | Batch 150/202 | Rec 0.000658 | Seg 0.317728 | Elapsed 3.1m | ETA 1.1m
Epoch 332/500 | Batch 160/202 | Rec 0.000653 | Seg 0.314058 | Elapsed 3.4m | ETA 0.9m
Epoch 332/500 | Batch 170/202 | Rec 0.000658 | Seg 0.311685 | Elapsed 3.6m | ETA 0.7m
Epoch 332/500 | Batch 180/202 | Rec 0.000661 | Seg 0.313709 | Elapsed 3.8m | ETA 0.5m
Epoch 332/500 | Batch 190/202 | Rec 0.000659 | Seg 0.313354 | Elapsed 4.0m | ETA 0.3m
Epoch 332/500 | Batch 200/202 | Rec 0.000661 | Seg 0.309324 | Elapsed 4.2m | ETA 0.0m
Epoch 332/500 | Batch 202/202 | Rec 0.000662 | Seg 0.310370 | Elapsed 4.2m | ETA 0.0m

2026-09-25 20:36:35,929 - INFO: Rec loss: 0.0006622066222808997
2026-09-25 20:36:35,929 - INFO: Seg loss: 0.3103697541547884
2026-09-25 20:36:35,929 - INFO: λ_rec: 1
2026-09-25 20:36:35,929 - INFO: λ_seg: 0.0001
2026-09-25 20:37:56,849 - INFO: -------------------Epoch: 332------------------------
2026-09-25 20:37:56,854 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.973324  0.974464  0.000132
2026-09-25 20:37:56,862 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995798  0.997844  0.997278  0.998511  0.995988
real potato   0.925841  0.961442  0.950530  0.972711  0.999907
fake potato   0.959779  0.979427  0.974300  0.984709  0.999970
real apple    0.755852  0.860902  0.972014  0.772667  0.999139
fake apple    0.566619  0.723319  0.987826  0.570603  0.998352
real orange   0.930423  0.963908  0.994459  0.935271  0.999908
fake orange   0.940128  0.969090  0.957692  0.980866  0.999821
real grape    0.744158  0.853265  0.910492  0.802894  0.999424
fake grape    0.901277  0.948026  0.927751  0.969311  0.999607
real lemon    0.715313  0.833982  0.764808  0.917035  0.999571
fake lemon    0.854273  0.921361  0.997981  0.855752  0.999691
real avocado  0.869982  0.930421  0.895761  0.967980  0.999866
fake avocado  0.715834  0.834337  0.999644  0.716016  0.999660
real pepper   0.886815  0.939962  0.936780  0.943267  0.999560
fake pepper   0.861215  0.925383  0.955295  0.897382  0.999655
real plant    0.865615  0.927917  0.944429  0.912070  0.998584
fake plant    0.798292  0.887783  0.847872  0.931748  0.999813
real banana   0.699610  0.823210  0.904127  0.755670  0.999271
fake banana   0.767112  0.868160  0.865419  0.871019  0.999514
real onion    0.600854  0.750619  0.610453  0.974498  0.999415
fake onion    0.937779  0.967840  0.969888  0.965901  0.999960
real unknown  0.527049  0.690238  0.545757  0.938931  0.999865
fake unknown  0.222077  0.363404  0.244394  0.708620  0.997908
total         0.784421  0.866167  0.876302  0.884497  0.999324
total(-bg)    0.774813  0.860182  0.870803  0.879315  0.999475
2026-09-25 20:37:57,644 - INFO: Epoch accounting: {'epoch': 332, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11212647, 59052, 91739, 113576, 126883, 83609, 76866, 134835, 236802, 66185, 56948, 46546, 29979, 230453, 111215, 153168, 25713, 91945, 86074, 80237, 63063, 11772, 48965], 'crops_with_class': [202, 35, 37, 30, 32, 22, 30, 28, 38, 32, 22, 15, 10, 56, 34, 24, 23, 25, 36, 41, 29, 11, 23], 'targeted_crops_by_class': [0, 1, 10, 5, 4, 5, 6, 5, 5, 3, 6, 4, 4, 5, 7, 5, 2, 3, 4, 2, 9, 6, 6], 'sampled_scene_counts': [0, 1, 2, 2, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 2, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 0, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 2, 1, 0, 3, 1, 0, 2, 1, 0, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 3, 1, 2, 4, 1, 1, 1, 2, 0, 1, 1, 3, 1, 3, 1, 0, 3, 0, 0, 0, 1, 3, 3, 0, 0, 3, 1, 2, 0, 2, 2, 3, 1, 2, 1, 1, 1, 2, 4, 2, 1, 2, 2, 2, 2, 2, 0, 1, 1, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 3, 0, 2, 1, 3, 2, 2, 1, 4, 2, 1, 1, 0, 0, 4, 1, 2, 0, 1, 1], 'learning_rate': 2.5823399979449013e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006622066222808997, 'train_segmentation_loss': 0.3103697541547884, 'val_foreground_miou_all22': 0.7748134022221655, 'val_psnr_ref1': 38.973324127197266, 'elapsed_seconds': 336.38650035858154, 'peak_cuda_allocated_gib': 7.508312225341797}

Epoch 333/500 | Batch 10/202 | Rec 0.000718 | Seg 0.335845 | Elapsed 0.2m | ETA 4.1m
Epoch 333/500 | Batch 20/202 | Rec 0.000671 | Seg 0.322430 | Elapsed 0.4m | ETA 3.9m
Epoch 333/500 | Batch 30/202 | Rec 0.000652 | Seg 0.318815 | Elapsed 0.6m | ETA 3.7m
Epoch 333/500 | Batch 40/202 | Rec 0.000649 | Seg 0.311859 | Elapsed 0.8m | ETA 3.4m
Epoch 333/500 | Batch 50/202 | Rec 0.000654 | Seg 0.306772 | Elapsed 1.1m | ETA 3.2m
Epoch 333/500 | Batch 60/202 | Rec 0.000648 | Seg 0.314022 | Elapsed 1.3m | ETA 3.0m
Epoch 333/500 | Batch 70/202 | Rec 0.000629 | Seg 0.310679 | Elapsed 1.5m | ETA 2.8m
Epoch 333/500 | Batch 80/202 | Rec 0.000625 | Seg 0.310948 | Elapsed 1.7m | ETA 2.6m
Epoch 333/500 | Batch 90/202 | Rec 0.000629 | Seg 0.316409 | Elapsed 1.9m | ETA 2.4m
Epoch 333/500 | Batch 100/202 | Rec 0.000626 | Seg 0.311784 | Elapsed 2.1m | ETA 2.2m
Epoch 333/500 | Batch 110/202 | Rec 0.000600 | Seg 0.299244 | Elapsed 2.3m | ETA 2.0m
Epoch 333/500 | Batch 120/202 | Rec 0.000594 | Seg 0.299863 | Elapsed 2.5m | ETA 1.7m
Epoch 333/500 | Batch 130/202 | Rec 0.000609 | Seg 0.300435 | Elapsed 2.8m | ETA 1.5m
Epoch 333/500 | Batch 140/202 | Rec 0.000613 | Seg 0.299515 | Elapsed 3.0m | ETA 1.3m
Epoch 333/500 | Batch 150/202 | Rec 0.000621 | Seg 0.302153 | Elapsed 3.2m | ETA 1.1m
Epoch 333/500 | Batch 160/202 | Rec 0.000616 | Seg 0.300397 | Elapsed 3.4m | ETA 0.9m
Epoch 333/500 | Batch 170/202 | Rec 0.000631 | Seg 0.301442 | Elapsed 3.6m | ETA 0.7m
Epoch 333/500 | Batch 180/202 | Rec 0.000625 | Seg 0.299117 | Elapsed 3.8m | ETA 0.5m
Epoch 333/500 | Batch 190/202 | Rec 0.000617 | Seg 0.296985 | Elapsed 4.0m | ETA 0.3m
Epoch 333/500 | Batch 200/202 | Rec 0.000616 | Seg 0.296823 | Elapsed 4.2m | ETA 0.0m
Epoch 333/500 | Batch 202/202 | Rec 0.000617 | Seg 0.297439 | Elapsed 4.3m | ETA 0.0m

2026-09-25 20:42:15,129 - INFO: Rec loss: 0.0006169378906597918
2026-09-25 20:42:15,129 - INFO: Seg loss: 0.29743924014049
2026-09-25 20:42:15,130 - INFO: λ_rec: 1
2026-09-25 20:42:15,130 - INFO: λ_seg: 0.0001
2026-09-25 20:43:35,200 - INFO: -------------------Epoch: 333------------------------
2026-09-25 20:43:35,205 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.717288  0.974458  0.00014
2026-09-25 20:43:35,213 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995606  0.997748  0.996786  0.998813  0.995803
real potato   0.413771  0.585302  0.995407  0.414563  0.999297
fake potato   0.646450  0.785217  0.982075  0.654168  0.999739
real apple    0.694146  0.819414  0.784219  0.858027  0.998696
fake apple    0.693905  0.819248  0.986068  0.700776  0.998833
real orange   0.826437  0.904922  0.991177  0.832561  0.999770
fake orange   0.900568  0.947633  0.917045  0.980439  0.999690
real grape    0.761174  0.864344  0.897224  0.833881  0.999454
fake grape    0.881917  0.937204  0.941703  0.932847  0.999538
real lemon    0.535819  0.697715  0.579394  0.876915  0.999107
fake lemon    0.853420  0.920864  0.997895  0.854959  0.999689
real avocado  0.790405  0.882885  0.811279  0.968473  0.999761
fake avocado  0.647374  0.785899  0.999606  0.647539  0.999578
real pepper   0.809326  0.894566  0.859615  0.932588  0.999196
fake pepper   0.628900  0.772129  0.969987  0.641380  0.999098
real plant    0.851047  0.919480  0.942971  0.897227  0.998429
fake plant    0.731794  0.845079  0.766256  0.942101  0.999725
real banana   0.555357  0.714073  0.905234  0.589637  0.998939
fake banana   0.736327  0.848093  0.840985  0.855425  0.999436
real onion    0.614439  0.761130  0.724264  0.802060  0.999545
fake onion    0.932692  0.965124  0.993598  0.938331  0.999957
real unknown  0.906667  0.950999  0.997903  0.908397  0.999985
fake unknown  0.260899  0.413791  0.284216  0.760775  0.998184
total         0.724715  0.827516  0.876735  0.818343  0.999194
total(-bg)    0.712402  0.819778  0.871278  0.810140  0.999348
2026-09-25 20:43:35,828 - INFO: Epoch accounting: {'epoch': 333, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11270506, 41234, 60263, 80839, 130780, 96841, 70061, 148505, 258335, 66660, 68083, 63324, 45529, 187944, 148958, 115157, 15865, 95855, 89756, 75478, 39133, 11945, 57221], 'crops_with_class': [202, 29, 30, 27, 36, 26, 23, 31, 40, 29, 26, 22, 19, 49, 38, 20, 14, 26, 34, 34, 24, 14, 22], 'targeted_crops_by_class': [0, 3, 6, 0, 3, 9, 1, 6, 7, 5, 3, 4, 6, 4, 2, 5, 4, 7, 7, 2, 2, 5, 4], 'sampled_scene_counts': [1, 1, 1, 0, 2, 1, 0, 1, 0, 0, 2, 1, 1, 0, 1, 1, 2, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 0, 1, 3, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 0, 1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 2, 0, 2, 0, 3, 1, 2, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 0, 5, 0, 0, 2, 3, 2, 3, 3, 0, 1, 2, 1, 0, 1, 0, 0, 2, 0, 1, 0, 2, 2, 3, 0, 1, 5, 3, 1, 2, 0, 5, 4, 0, 2, 1, 0, 1, 2, 0, 2, 0, 1, 1, 1, 1, 3, 0, 1, 0, 0, 1, 2, 0, 4, 0, 3, 1, 2, 2, 2, 2, 1, 2, 2, 1, 0, 1, 2, 1, 1, 0, 3, 2], 'learning_rate': 2.55502238402789e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0006169378906597918, 'train_segmentation_loss': 0.29743924014049, 'val_foreground_miou_all22': 0.7124015267866832, 'val_psnr_ref1': 38.7172883605957, 'elapsed_seconds': 338.1745617389679, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 334/500 | Batch 10/202 | Rec 0.000678 | Seg 0.323298 | Elapsed 0.2m | ETA 4.1m
Epoch 334/500 | Batch 20/202 | Rec 0.000577 | Seg 0.297396 | Elapsed 0.4m | ETA 3.9m
Epoch 334/500 | Batch 30/202 | Rec 0.000608 | Seg 0.301127 | Elapsed 0.6m | ETA 3.7m
Epoch 334/500 | Batch 40/202 | Rec 0.000633 | Seg 0.301932 | Elapsed 0.9m | ETA 3.4m
Epoch 334/500 | Batch 50/202 | Rec 0.000648 | Seg 0.288019 | Elapsed 1.1m | ETA 3.3m
Epoch 334/500 | Batch 60/202 | Rec 0.000643 | Seg 0.286398 | Elapsed 1.3m | ETA 3.0m
Epoch 334/500 | Batch 70/202 | Rec 0.000646 | Seg 0.286857 | Elapsed 1.5m | ETA 2.8m
Epoch 334/500 | Batch 80/202 | Rec 0.000647 | Seg 0.297177 | Elapsed 1.7m | ETA 2.6m
Epoch 334/500 | Batch 90/202 | Rec 0.000634 | Seg 0.291683 | Elapsed 1.9m | ETA 2.4m
Epoch 334/500 | Batch 100/202 | Rec 0.000623 | Seg 0.286737 | Elapsed 2.1m | ETA 2.2m
Epoch 334/500 | Batch 110/202 | Rec 0.000625 | Seg 0.284484 | Elapsed 2.3m | ETA 1.9m
Epoch 334/500 | Batch 120/202 | Rec 0.000628 | Seg 0.285466 | Elapsed 2.5m | ETA 1.7m
Epoch 334/500 | Batch 130/202 | Rec 0.000632 | Seg 0.290013 | Elapsed 2.8m | ETA 1.5m
Epoch 334/500 | Batch 140/202 | Rec 0.000638 | Seg 0.296520 | Elapsed 3.0m | ETA 1.3m
Epoch 334/500 | Batch 150/202 | Rec 0.000640 | Seg 0.299811 | Elapsed 3.2m | ETA 1.1m
Epoch 334/500 | Batch 160/202 | Rec 0.000637 | Seg 0.295555 | Elapsed 3.4m | ETA 0.9m
Epoch 334/500 | Batch 170/202 | Rec 0.000638 | Seg 0.299540 | Elapsed 3.6m | ETA 0.7m
Epoch 334/500 | Batch 180/202 | Rec 0.000637 | Seg 0.298484 | Elapsed 3.8m | ETA 0.5m
Epoch 334/500 | Batch 190/202 | Rec 0.000628 | Seg 0.294779 | Elapsed 4.0m | ETA 0.3m
Epoch 334/500 | Batch 200/202 | Rec 0.000627 | Seg 0.292698 | Elapsed 4.2m | ETA 0.0m
Epoch 334/500 | Batch 202/202 | Rec 0.000625 | Seg 0.291546 | Elapsed 4.3m | ETA 0.0m

2026-09-25 20:47:53,321 - INFO: Rec loss: 0.0006245357529917216
2026-09-25 20:47:53,321 - INFO: Seg loss: 0.2915462484159092
2026-09-25 20:47:53,321 - INFO: λ_rec: 1
2026-09-25 20:47:53,321 - INFO: λ_seg: 0.0001
2026-09-25 20:49:17,450 - INFO: -------------------Epoch: 334------------------------
2026-09-25 20:49:17,454 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.761232  0.974475  0.000139
2026-09-25 20:49:17,462 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995712  0.997801  0.997132  0.998572  0.995906
real potato   0.508389  0.674037  0.979344  0.513900  0.999405
fake potato   0.716821  0.835008  0.979966  0.727482  0.999791
real apple    0.737346  0.848769  0.814724  0.885891  0.998911
fake apple    0.615233  0.761741  0.994531  0.617321  0.998542
real orange   0.919478  0.958000  0.986865  0.930871  0.999893
fake orange   0.881336  0.936876  0.894714  0.983317  0.999621
real grape    0.849836  0.918773  0.928316  0.909523  0.999664
fake grape    0.902658  0.948789  0.937120  0.960855  0.999617
real lemon    0.638517  0.779336  0.674024  0.923786  0.999385
fake lemon    0.851769  0.919902  0.996718  0.854165  0.999686
real avocado  0.801114  0.889526  0.822684  0.968309  0.999777
fake avocado  0.670831  0.802943  0.999620  0.671002  0.999606
real pepper   0.733621  0.846296  0.776817  0.929543  0.998765
fake pepper   0.463679  0.633536  0.956803  0.473593  0.998694
real plant    0.876363  0.934058  0.965578  0.904625  0.998723
fake plant    0.721030  0.837855  0.782435  0.901840  0.999722
real banana   0.667291  0.800400  0.891612  0.726199  0.999186
fake banana   0.729992  0.843875  0.839767  0.848125  0.999423
real onion    0.647522  0.786006  0.733051  0.847323  0.999583
fake onion    0.943669  0.970968  0.995176  0.948005  0.999964
real unknown  0.849172  0.918385  0.907735  0.929389  0.999974
fake unknown  0.220472  0.361252  0.242304  0.709888  0.997885
total         0.736602  0.834962  0.873784  0.833197  0.999205
total(-bg)    0.724825  0.827561  0.868178  0.825680  0.999355
2026-09-25 20:49:18,067 - INFO: Epoch accounting: {'epoch': 334, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11324510, 56513, 37552, 126365, 134062, 94318, 91339, 142354, 215289, 65738, 51203, 41185, 43068, 189004, 98113, 186644, 18508, 52597, 61635, 79064, 63253, 12749, 53209], 'crops_with_class': [202, 27, 21, 35, 33, 31, 30, 28, 35, 31, 21, 14, 17, 45, 28, 25, 19, 16, 29, 33, 28, 16, 24], 'targeted_crops_by_class': [0, 6, 1, 3, 6, 6, 6, 9, 4, 2, 2, 6, 5, 6, 7, 3, 4, 4, 4, 3, 5, 8, 2], 'sampled_scene_counts': [0, 2, 2, 1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 2, 2, 2, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 1, 2, 1, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 3, 0, 2, 0, 1, 1, 0, 0, 2, 2, 1, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 2, 0, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 2, 0, 2, 2, 1, 1, 1, 0, 2, 1, 3, 2, 1, 2, 1, 1, 1, 2, 0, 2, 2, 1, 5, 1, 2, 1, 1, 1, 1, 2, 0, 2, 0, 0, 3, 0, 4, 4, 2, 3, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 2, 0, 4, 1, 1, 2, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 4, 1, 1, 2, 1, 3, 1, 1, 2, 2, 1, 3], 'learning_rate': 2.5278017871192852e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006245357529917216, 'train_segmentation_loss': 0.2915462484159092, 'val_foreground_miou_all22': 0.7248245639608059, 'val_psnr_ref1': 38.761232147216795, 'elapsed_seconds': 342.2303378582001, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 335/500 | Batch 10/202 | Rec 0.000626 | Seg 0.211188 | Elapsed 0.2m | ETA 4.3m
Epoch 335/500 | Batch 20/202 | Rec 0.000643 | Seg 0.248116 | Elapsed 0.4m | ETA 3.9m
Epoch 335/500 | Batch 30/202 | Rec 0.000592 | Seg 0.253050 | Elapsed 0.6m | ETA 3.7m
Epoch 335/500 | Batch 40/202 | Rec 0.000592 | Seg 0.265816 | Elapsed 0.8m | ETA 3.4m
Epoch 335/500 | Batch 50/202 | Rec 0.000593 | Seg 0.263416 | Elapsed 1.1m | ETA 3.2m
Epoch 335/500 | Batch 60/202 | Rec 0.000597 | Seg 0.267559 | Elapsed 1.3m | ETA 3.0m
Epoch 335/500 | Batch 70/202 | Rec 0.000581 | Seg 0.265439 | Elapsed 1.5m | ETA 2.8m
Epoch 335/500 | Batch 80/202 | Rec 0.000588 | Seg 0.271964 | Elapsed 1.7m | ETA 2.6m
Epoch 335/500 | Batch 90/202 | Rec 0.000592 | Seg 0.282282 | Elapsed 1.9m | ETA 2.4m
Epoch 335/500 | Batch 100/202 | Rec 0.000585 | Seg 0.277141 | Elapsed 2.1m | ETA 2.2m
Epoch 335/500 | Batch 110/202 | Rec 0.000594 | Seg 0.277638 | Elapsed 2.3m | ETA 1.9m
Epoch 335/500 | Batch 120/202 | Rec 0.000593 | Seg 0.276022 | Elapsed 2.5m | ETA 1.7m
Epoch 335/500 | Batch 130/202 | Rec 0.000594 | Seg 0.277374 | Elapsed 2.8m | ETA 1.5m
Epoch 335/500 | Batch 140/202 | Rec 0.000602 | Seg 0.284080 | Elapsed 3.0m | ETA 1.3m
Epoch 335/500 | Batch 150/202 | Rec 0.000605 | Seg 0.284399 | Elapsed 3.2m | ETA 1.1m
Epoch 335/500 | Batch 160/202 | Rec 0.000601 | Seg 0.280904 | Elapsed 3.4m | ETA 0.9m
Epoch 335/500 | Batch 170/202 | Rec 0.000598 | Seg 0.282150 | Elapsed 3.6m | ETA 0.7m
Epoch 335/500 | Batch 180/202 | Rec 0.000598 | Seg 0.281989 | Elapsed 3.8m | ETA 0.5m
Epoch 335/500 | Batch 190/202 | Rec 0.000597 | Seg 0.284379 | Elapsed 4.0m | ETA 0.3m
Epoch 335/500 | Batch 200/202 | Rec 0.000594 | Seg 0.286354 | Elapsed 4.2m | ETA 0.0m
Epoch 335/500 | Batch 202/202 | Rec 0.000593 | Seg 0.287229 | Elapsed 4.3m | ETA 0.0m

2026-09-25 20:53:34,829 - INFO: Rec loss: 0.0005931000231441323
2026-09-25 20:53:34,829 - INFO: Seg loss: 0.2872291195510638
2026-09-25 20:53:34,829 - INFO: λ_rec: 1
2026-09-25 20:53:34,829 - INFO: λ_seg: 0.0001
2026-09-25 20:54:58,083 - INFO: -------------------Epoch: 335------------------------
2026-09-25 20:54:58,087 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.843008  0.974574  0.000136
2026-09-25 20:54:58,095 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995808  0.997850  0.997296  0.998504  0.995998
real potato   0.791577  0.883616  0.993472  0.795715  0.999749
fake potato   0.857787  0.923400  0.975303  0.876833  0.999894
real apple    0.780742  0.876823  0.926451  0.832331  0.999194
fake apple    0.586252  0.739119  0.971186  0.596629  0.998410
real orange   0.918412  0.957421  0.999370  0.918944  0.999892
fake orange   0.936769  0.967302  0.953602  0.981505  0.999810
real grape    0.779989  0.876348  0.957637  0.807864  0.999524
fake grape    0.907196  0.951290  0.937380  0.965722  0.999635
real lemon    0.456592  0.626886  0.487898  0.876785  0.998774
fake lemon    0.858898  0.924044  0.995503  0.862243  0.999700
real avocado  0.939179  0.968586  0.979034  0.958456  0.999942
fake avocado  0.681882  0.810808  0.999813  0.681969  0.999619
real pepper   0.914917  0.955518  0.945998  0.965335  0.999672
fake pepper   0.882736  0.937666  0.956704  0.919467  0.999709
real plant    0.871073  0.931045  0.942474  0.919987  0.998638
fake plant    0.780260  0.876519  0.828469  0.930598  0.999791
real banana   0.407760  0.579259  0.886046  0.430327  0.998596
fake banana   0.669636  0.802084  0.756001  0.854263  0.999225
real onion    0.633762  0.775783  0.664778  0.931430  0.999514
fake onion    0.915210  0.955678  0.989640  0.924063  0.999946
real unknown  0.935176  0.966452  0.998982  0.936069  0.999990
fake unknown  0.228609  0.372106  0.247418  0.750453  0.997866
total         0.770879  0.854591  0.886541  0.857195  0.999265
total(-bg)    0.760655  0.848080  0.881507  0.850772  0.999413
2026-09-25 20:54:58,673 - INFO: Epoch accounting: {'epoch': 335, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11346949, 39908, 39460, 138071, 133537, 79212, 79886, 115866, 201249, 80303, 79340, 50175, 50504, 203442, 130222, 122112, 32543, 87839, 49667, 77013, 40331, 14733, 45910], 'crops_with_class': [202, 22, 21, 38, 33, 23, 30, 26, 30, 35, 32, 18, 18, 48, 32, 18, 29, 27, 23, 31, 19, 15, 21], 'targeted_crops_by_class': [0, 4, 3, 6, 4, 3, 4, 6, 4, 4, 4, 8, 4, 2, 4, 6, 5, 7, 2, 4, 5, 3, 5], 'sampled_scene_counts': [0, 0, 0, 0, 0, 3, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 2, 1, 1, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 2, 4, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 2, 0, 1, 0, 0, 2, 1, 0, 4, 2, 0, 2, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 2, 1, 1, 1, 1, 2, 3, 2, 2, 0, 1, 3, 1, 2, 3, 1, 0, 0, 2, 1, 2, 2, 0, 1, 3, 1, 1, 1, 0, 1, 1, 2, 1, 0, 5, 0, 2, 1, 4, 1, 4, 1, 2, 0, 1, 1, 1, 2, 1, 0, 1, 1, 4, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 3, 0, 2, 0, 1, 2, 1, 3, 1, 2, 2, 2, 0, 2, 3, 2, 1], 'learning_rate': 2.5006792818416384e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005931000231441323, 'train_segmentation_loss': 0.2872291195510638, 'val_foreground_miou_all22': 0.760655209157457, 'val_psnr_ref1': 38.84300765991211, 'elapsed_seconds': 340.5963201522827, 'peak_cuda_allocated_gib': 7.513713836669922}

Epoch 336/500 | Batch 10/202 | Rec 0.000801 | Seg 0.357076 | Elapsed 0.2m | ETA 4.1m
Epoch 336/500 | Batch 20/202 | Rec 0.000707 | Seg 0.306899 | Elapsed 0.4m | ETA 3.9m
Epoch 336/500 | Batch 30/202 | Rec 0.000677 | Seg 0.320363 | Elapsed 0.6m | ETA 3.7m
Epoch 336/500 | Batch 40/202 | Rec 0.000645 | Seg 0.304165 | Elapsed 0.8m | ETA 3.4m
Epoch 336/500 | Batch 50/202 | Rec 0.000618 | Seg 0.294845 | Elapsed 1.1m | ETA 3.2m
Epoch 336/500 | Batch 60/202 | Rec 0.000623 | Seg 0.294686 | Elapsed 1.3m | ETA 3.0m
Epoch 336/500 | Batch 70/202 | Rec 0.000607 | Seg 0.285418 | Elapsed 1.5m | ETA 2.8m
Epoch 336/500 | Batch 80/202 | Rec 0.000602 | Seg 0.283406 | Elapsed 1.7m | ETA 2.6m
Epoch 336/500 | Batch 90/202 | Rec 0.000599 | Seg 0.284372 | Elapsed 1.9m | ETA 2.4m
Epoch 336/500 | Batch 100/202 | Rec 0.000594 | Seg 0.279169 | Elapsed 2.1m | ETA 2.1m
Epoch 336/500 | Batch 110/202 | Rec 0.000592 | Seg 0.280486 | Elapsed 2.3m | ETA 1.9m
Epoch 336/500 | Batch 120/202 | Rec 0.000595 | Seg 0.286525 | Elapsed 2.5m | ETA 1.7m
Epoch 336/500 | Batch 130/202 | Rec 0.000595 | Seg 0.287047 | Elapsed 2.7m | ETA 1.5m
Epoch 336/500 | Batch 140/202 | Rec 0.000588 | Seg 0.284402 | Elapsed 2.9m | ETA 1.3m
Epoch 336/500 | Batch 150/202 | Rec 0.000589 | Seg 0.284361 | Elapsed 3.2m | ETA 1.1m
Epoch 336/500 | Batch 160/202 | Rec 0.000583 | Seg 0.280861 | Elapsed 3.4m | ETA 0.9m
Epoch 336/500 | Batch 170/202 | Rec 0.000584 | Seg 0.279582 | Elapsed 3.6m | ETA 0.7m
Epoch 336/500 | Batch 180/202 | Rec 0.000589 | Seg 0.278435 | Elapsed 3.8m | ETA 0.5m
Epoch 336/500 | Batch 190/202 | Rec 0.000599 | Seg 0.280556 | Elapsed 4.0m | ETA 0.3m
Epoch 336/500 | Batch 200/202 | Rec 0.000600 | Seg 0.281377 | Elapsed 4.2m | ETA 0.0m
Epoch 336/500 | Batch 202/202 | Rec 0.000600 | Seg 0.280743 | Elapsed 4.3m | ETA 0.0m

2026-09-25 20:59:13,848 - INFO: Rec loss: 0.0006000369740822952
2026-09-25 20:59:13,849 - INFO: Seg loss: 0.280742937532982
2026-09-25 20:59:13,849 - INFO: λ_rec: 1
2026-09-25 20:59:13,849 - INFO: λ_seg: 0.0001
2026-09-25 21:00:36,698 - INFO: -------------------Epoch: 336------------------------
2026-09-25 21:00:36,703 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.484746  0.973785  0.000148
2026-09-25 21:00:36,711 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995422  0.997656  0.996579  0.998835  0.995627
real potato   0.829690  0.906869  0.989006  0.837414  0.999794
fake potato   0.839224  0.912535  0.971388  0.860494  0.999880
real apple    0.761600  0.864618  0.927952  0.809465  0.999126
fake apple    0.634140  0.776067  0.987514  0.639266  0.998607
real orange   0.878658  0.935361  0.998817  0.879574  0.999840
fake orange   0.917013  0.956660  0.938253  0.975909  0.999747
real grape    0.791302  0.883444  0.949895  0.825769  0.999545
fake grape    0.900390  0.947535  0.943304  0.951904  0.999610
real lemon    0.533305  0.695579  0.610860  0.807712  0.999169
fake lemon    0.811249  0.895740  0.998139  0.812477  0.999600
real avocado  0.937974  0.967945  0.982905  0.953530  0.999941
fake avocado  0.721953  0.838479  0.999647  0.722137  0.999667
real pepper   0.871162  0.931095  0.908388  0.955073  0.999483
fake pepper   0.825854  0.904572  0.945612  0.867038  0.999564
real plant    0.849471  0.918560  0.956503  0.883604  0.998434
fake plant    0.778095  0.875150  0.861467  0.889379  0.999798
real banana   0.615717  0.762111  0.907267  0.657069  0.999079
fake banana   0.651373  0.788837  0.724703  0.865544  0.999148
real onion    0.650562  0.788242  0.707947  0.889208  0.999568
fake onion    0.931638  0.964559  0.991322  0.939299  0.999957
real unknown  0.733283  0.846071  0.775218  0.931298  0.999946
fake unknown  0.215437  0.354461  0.246364  0.631836  0.998061
total         0.768457  0.857050  0.883437  0.851471  0.999269
total(-bg)    0.758140  0.850659  0.878294  0.844773  0.999435
2026-09-25 21:00:37,298 - INFO: Epoch accounting: {'epoch': 336, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11398666, 46219, 62293, 100981, 147113, 91588, 99633, 90328, 199148, 71435, 66818, 45766, 43688, 193011, 132450, 150965, 21008, 65922, 79425, 47724, 39109, 10758, 34224], 'crops_with_class': [202, 25, 27, 28, 34, 31, 32, 21, 34, 32, 27, 17, 18, 49, 32, 24, 22, 20, 29, 23, 17, 11, 17], 'targeted_crops_by_class': [0, 6, 6, 3, 6, 6, 5, 3, 6, 3, 8, 5, 10, 5, 7, 6, 4, 3, 5, 2, 1, 5, 3], 'sampled_scene_counts': [1, 0, 1, 1, 0, 1, 1, 0, 3, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 2, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 2, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0, 2, 0, 2, 3, 1, 1, 2, 2, 1, 1, 3, 2, 2, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 2, 0, 0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 2, 3, 0, 1, 0, 1, 2, 0, 0, 1, 3, 0, 2, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 1, 1, 3, 3, 4, 0, 0, 1, 1, 2, 0, 1, 2, 1, 1, 2, 1, 1, 3, 4, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 0, 2, 1, 1, 0, 1, 0, 3, 2, 1, 2, 2, 3, 2, 2, 0, 1, 2, 0, 0, 1, 3, 1, 2, 2, 1, 1], 'learning_rate': 2.473655938945018e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006000369740822952, 'train_segmentation_loss': 0.280742937532982, 'val_foreground_miou_all22': 0.7581404671502078, 'val_psnr_ref1': 38.48474563598633, 'elapsed_seconds': 338.61498832702637, 'peak_cuda_allocated_gib': 7.511264801025391}

Epoch 337/500 | Batch 10/202 | Rec 0.000553 | Seg 0.253122 | Elapsed 0.2m | ETA 4.1m
Epoch 337/500 | Batch 20/202 | Rec 0.000641 | Seg 0.304933 | Elapsed 0.4m | ETA 3.8m
Epoch 337/500 | Batch 30/202 | Rec 0.000665 | Seg 0.315542 | Elapsed 0.6m | ETA 3.6m
Epoch 337/500 | Batch 40/202 | Rec 0.000648 | Seg 0.304968 | Elapsed 0.8m | ETA 3.4m
Epoch 337/500 | Batch 50/202 | Rec 0.000642 | Seg 0.318962 | Elapsed 1.0m | ETA 3.2m
Epoch 337/500 | Batch 60/202 | Rec 0.000630 | Seg 0.325553 | Elapsed 1.3m | ETA 3.0m
Epoch 337/500 | Batch 70/202 | Rec 0.000615 | Seg 0.314143 | Elapsed 1.5m | ETA 2.8m
Epoch 337/500 | Batch 80/202 | Rec 0.000615 | Seg 0.310550 | Elapsed 1.7m | ETA 2.6m
Epoch 337/500 | Batch 90/202 | Rec 0.000615 | Seg 0.307801 | Elapsed 1.9m | ETA 2.3m
Epoch 337/500 | Batch 100/202 | Rec 0.000617 | Seg 0.304509 | Elapsed 2.1m | ETA 2.1m
Epoch 337/500 | Batch 110/202 | Rec 0.000613 | Seg 0.301992 | Elapsed 2.3m | ETA 1.9m
Epoch 337/500 | Batch 120/202 | Rec 0.000613 | Seg 0.303678 | Elapsed 2.5m | ETA 1.7m
Epoch 337/500 | Batch 130/202 | Rec 0.000610 | Seg 0.299712 | Elapsed 2.7m | ETA 1.5m
Epoch 337/500 | Batch 140/202 | Rec 0.000614 | Seg 0.300308 | Elapsed 2.9m | ETA 1.3m
Epoch 337/500 | Batch 150/202 | Rec 0.000614 | Seg 0.298044 | Elapsed 3.2m | ETA 1.1m
Epoch 337/500 | Batch 160/202 | Rec 0.000621 | Seg 0.298570 | Elapsed 3.4m | ETA 0.9m
Epoch 337/500 | Batch 170/202 | Rec 0.000611 | Seg 0.296402 | Elapsed 3.6m | ETA 0.7m
Epoch 337/500 | Batch 180/202 | Rec 0.000609 | Seg 0.298116 | Elapsed 3.8m | ETA 0.5m
Epoch 337/500 | Batch 190/202 | Rec 0.000615 | Seg 0.295175 | Elapsed 4.0m | ETA 0.3m
Epoch 337/500 | Batch 200/202 | Rec 0.000618 | Seg 0.299379 | Elapsed 4.2m | ETA 0.0m
Epoch 337/500 | Batch 202/202 | Rec 0.000618 | Seg 0.299076 | Elapsed 4.3m | ETA 0.0m

2026-09-25 21:04:53,140 - INFO: Rec loss: 0.0006184235903449439
2026-09-25 21:04:53,140 - INFO: Seg loss: 0.2990757385545438
2026-09-25 21:04:53,140 - INFO: λ_rec: 1
2026-09-25 21:04:53,141 - INFO: λ_seg: 0.0001
2026-09-25 21:06:17,986 - INFO: -------------------Epoch: 337------------------------
2026-09-25 21:06:17,990 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.951702  0.974504  0.000133
2026-09-25 21:06:17,999 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995766  0.997829  0.996858  0.998901  0.995957
real potato   0.942872  0.970546  0.986181  0.955496  0.999931
fake potato   0.951898  0.975306  0.968408  0.982405  0.999964
real apple    0.790657  0.883042  0.965468  0.813667  0.999257
fake apple    0.577662  0.732255  0.991714  0.580464  0.998398
real orange   0.888774  0.941062  0.994839  0.892890  0.999853
fake orange   0.924719  0.960837  0.941216  0.981399  0.999771
real grape    0.817394  0.899474  0.966261  0.841409  0.999608
fake grape    0.889039  0.941211  0.934752  0.947861  0.999562
real lemon    0.463734  0.633584  0.523029  0.803558  0.998908
fake lemon    0.848905  0.918229  0.990567  0.855824  0.999678
real avocado  0.923381  0.960114  0.960559  0.959770  0.999926
fake avocado  0.712793  0.832268  0.998929  0.713338  0.999656
real pepper   0.877585  0.934752  0.905078  0.966544  0.999507
fake pepper   0.813804  0.897295  0.939307  0.858972  0.999532
real plant    0.858582  0.923861  0.967559  0.884031  0.998544
fake plant    0.736515  0.848218  0.778383  0.931940  0.999735
real banana   0.498426  0.665219  0.902408  0.526823  0.998809
fake banana   0.650862  0.788462  0.725002  0.864217  0.999147
real onion    0.633880  0.775872  0.651088  0.959973  0.999499
fake onion    0.889532  0.941487  0.918372  0.965901  0.999924
real unknown  0.896520  0.945387  0.956989  0.934160  0.999983
fake unknown  0.223753  0.365642  0.258211  0.626403  0.998169
total         0.774220  0.857911  0.879182  0.862867  0.999275
total(-bg)    0.764149  0.851551  0.873833  0.856684  0.999425
2026-09-25 21:06:18,603 - INFO: Epoch accounting: {'epoch': 337, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11251799, 51391, 58006, 130038, 142352, 66225, 66088, 136507, 217574, 84951, 59998, 40242, 45139, 205020, 118385, 141778, 36195, 72009, 88823, 89446, 56095, 11453, 68758], 'crops_with_class': [202, 28, 26, 37, 36, 22, 25, 26, 34, 36, 28, 13, 18, 54, 30, 21, 30, 19, 33, 36, 27, 13, 28], 'targeted_crops_by_class': [0, 7, 5, 4, 5, 4, 2, 5, 5, 8, 5, 2, 3, 4, 2, 5, 5, 6, 5, 2, 5, 3, 14], 'sampled_scene_counts': [0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1, 0, 2, 0, 0, 1, 2, 1, 0, 0, 3, 1, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 3, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 2, 2, 2, 3, 1, 0, 0, 2, 1, 1, 1, 3, 0, 1, 2, 3, 1, 0, 3, 2, 1, 1, 1, 2, 3, 1, 0, 1, 1, 4, 2, 0, 3, 2, 2, 4, 0, 0, 5, 1, 2, 2, 3, 3, 2, 1, 0, 1, 0, 1, 1, 2, 2, 1, 1, 1, 2, 0, 1, 0, 0, 1, 2, 1, 2, 4, 3, 1, 0, 2, 1, 2, 1, 0, 1, 2, 1, 2, 1, 0, 3], 'learning_rate': 2.4467328252647314e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006184235903449439, 'train_segmentation_loss': 0.2990757385545438, 'val_foreground_miou_all22': 0.7641494388881008, 'val_psnr_ref1': 38.95170227050781, 'elapsed_seconds': 341.2950222492218, 'peak_cuda_allocated_gib': 7.510807037353516}

Epoch 338/500 | Batch 10/202 | Rec 0.000695 | Seg 0.338685 | Elapsed 0.2m | ETA 4.0m
Epoch 338/500 | Batch 20/202 | Rec 0.000657 | Seg 0.328217 | Elapsed 0.4m | ETA 3.8m
Epoch 338/500 | Batch 30/202 | Rec 0.000677 | Seg 0.320398 | Elapsed 0.6m | ETA 3.7m
Epoch 338/500 | Batch 40/202 | Rec 0.000633 | Seg 0.318370 | Elapsed 0.8m | ETA 3.4m
Epoch 338/500 | Batch 50/202 | Rec 0.000614 | Seg 0.298252 | Elapsed 1.1m | ETA 3.2m
Epoch 338/500 | Batch 60/202 | Rec 0.000616 | Seg 0.294180 | Elapsed 1.3m | ETA 3.0m
Epoch 338/500 | Batch 70/202 | Rec 0.000619 | Seg 0.294476 | Elapsed 1.5m | ETA 2.8m
Epoch 338/500 | Batch 80/202 | Rec 0.000619 | Seg 0.288529 | Elapsed 1.7m | ETA 2.6m
Epoch 338/500 | Batch 90/202 | Rec 0.000626 | Seg 0.294627 | Elapsed 1.9m | ETA 2.4m
Epoch 338/500 | Batch 100/202 | Rec 0.000639 | Seg 0.299062 | Elapsed 2.1m | ETA 2.2m
Epoch 338/500 | Batch 110/202 | Rec 0.000635 | Seg 0.299872 | Elapsed 2.3m | ETA 2.0m
Epoch 338/500 | Batch 120/202 | Rec 0.000632 | Seg 0.302655 | Elapsed 2.6m | ETA 1.7m
Epoch 338/500 | Batch 130/202 | Rec 0.000633 | Seg 0.298276 | Elapsed 2.8m | ETA 1.5m
Epoch 338/500 | Batch 140/202 | Rec 0.000635 | Seg 0.299980 | Elapsed 3.0m | ETA 1.3m
Epoch 338/500 | Batch 150/202 | Rec 0.000635 | Seg 0.301231 | Elapsed 3.2m | ETA 1.1m
Epoch 338/500 | Batch 160/202 | Rec 0.000627 | Seg 0.295868 | Elapsed 3.4m | ETA 0.9m
Epoch 338/500 | Batch 170/202 | Rec 0.000624 | Seg 0.292236 | Elapsed 3.6m | ETA 0.7m
Epoch 338/500 | Batch 180/202 | Rec 0.000620 | Seg 0.291187 | Elapsed 3.8m | ETA 0.5m
Epoch 338/500 | Batch 190/202 | Rec 0.000627 | Seg 0.288678 | Elapsed 4.0m | ETA 0.3m
Epoch 338/500 | Batch 200/202 | Rec 0.000621 | Seg 0.287009 | Elapsed 4.2m | ETA 0.0m
Epoch 338/500 | Batch 202/202 | Rec 0.000622 | Seg 0.287774 | Elapsed 4.3m | ETA 0.0m

2026-09-25 21:10:34,965 - INFO: Rec loss: 0.0006222969286592151
2026-09-25 21:10:34,965 - INFO: Seg loss: 0.2877744740373132
2026-09-25 21:10:34,965 - INFO: λ_rec: 1
2026-09-25 21:10:34,965 - INFO: λ_seg: 0.0001
2026-09-25 21:11:57,073 - INFO: -------------------Epoch: 338------------------------
2026-09-25 21:11:57,077 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.945303  0.974711  0.000133
2026-09-25 21:11:57,085 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995738  0.997814  0.997276  0.998454  0.995931
real potato   0.901811  0.948321  0.920538  0.977939  0.999873
fake potato   0.959288  0.979171  0.976265  0.982195  0.999970
real apple    0.748532  0.856134  0.969250  0.766740  0.999111
fake apple    0.557184  0.715584  0.988741  0.560742  0.998317
real orange   0.959224  0.979138  0.997477  0.961556  0.999946
fake orange   0.945740  0.972064  0.976242  0.968020  0.999841
real grape    0.734597  0.846945  0.953955  0.761602  0.999426
fake grape    0.904461  0.949784  0.936673  0.963371  0.999624
real lemon    0.731591  0.844943  0.771533  0.933913  0.999597
fake lemon    0.764511  0.866492  0.999623  0.764731  0.999502
real avocado  0.958292  0.978652  0.995920  0.962069  0.999961
fake avocado  0.756247  0.861159  0.999663  0.756440  0.999708
real pepper   0.812349  0.896410  0.833065  0.970299  0.999180
fake pepper   0.706136  0.827712  0.950681  0.732988  0.999273
real plant    0.857311  0.923125  0.937843  0.908958  0.998487
fake plant    0.838918  0.912354  0.861646  0.969517  0.999852
real banana   0.721002  0.837836  0.902170  0.782154  0.999320
fake banana   0.672349  0.804028  0.744872  0.873507  0.999217
real onion    0.590006  0.742096  0.599771  0.973146  0.999389
fake onion    0.933381  0.965493  0.986623  0.945345  0.999957
real unknown  0.520691  0.684763  0.535849  0.948473  0.999860
fake unknown  0.207732  0.343965  0.231707  0.667512  0.997855
total         0.772917  0.857999  0.872495  0.875203  0.999269
total(-bg)    0.762789  0.851644  0.866823  0.869601  0.999421
2026-09-25 21:11:57,641 - INFO: Epoch accounting: {'epoch': 338, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11367230, 40274, 51943, 103989, 171573, 77258, 86023, 150957, 168399, 77708, 45285, 40198, 32519, 191243, 91958, 149412, 35487, 89063, 68966, 86780, 54235, 11037, 46735], 'crops_with_class': [202, 27, 23, 27, 41, 21, 25, 27, 36, 35, 22, 15, 17, 51, 25, 24, 28, 23, 29, 39, 26, 11, 22], 'targeted_crops_by_class': [0, 4, 4, 8, 7, 3, 7, 6, 1, 7, 8, 3, 5, 0, 4, 4, 7, 5, 6, 5, 7, 4, 2], 'sampled_scene_counts': [2, 2, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 3, 0, 1, 2, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 3, 0, 0, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2, 1, 0, 1, 1, 1, 0, 2, 2, 0, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 1, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 0, 0, 0, 2, 1, 2, 2, 0, 3, 3, 1, 3, 2, 1, 0, 0, 4, 1, 2, 3, 0, 0, 1, 1, 3, 2, 1, 3, 3, 2, 0, 2, 0, 0, 1, 1, 0, 1, 2, 1, 3, 0, 1, 2, 2, 4, 1, 3, 2, 2, 0, 2, 1, 2, 1, 0, 2, 0, 0, 1, 1, 2, 0, 0, 0, 5, 1, 2, 0, 1, 2, 1, 1, 1, 0, 3, 1, 3, 1, 0, 2, 4, 3, 1, 1, 0, 1], 'learning_rate': 2.419911003679208e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006222969286592151, 'train_segmentation_loss': 0.2877744740373132, 'val_foreground_miou_all22': 0.7627888836199468, 'val_psnr_ref1': 38.945303497314455, 'elapsed_seconds': 339.0294897556305, 'peak_cuda_allocated_gib': 7.509342193603516}

Epoch 339/500 | Batch 10/202 | Rec 0.000549 | Seg 0.294601 | Elapsed 0.2m | ETA 4.0m
Epoch 339/500 | Batch 20/202 | Rec 0.000502 | Seg 0.248483 | Elapsed 0.4m | ETA 3.7m
Epoch 339/500 | Batch 30/202 | Rec 0.000548 | Seg 0.277973 | Elapsed 0.6m | ETA 3.6m
Epoch 339/500 | Batch 40/202 | Rec 0.000550 | Seg 0.272458 | Elapsed 0.8m | ETA 3.4m
Epoch 339/500 | Batch 50/202 | Rec 0.000543 | Seg 0.274954 | Elapsed 1.0m | ETA 3.2m
Epoch 339/500 | Batch 60/202 | Rec 0.000565 | Seg 0.282520 | Elapsed 1.3m | ETA 3.0m
Epoch 339/500 | Batch 70/202 | Rec 0.000542 | Seg 0.272944 | Elapsed 1.5m | ETA 2.8m
Epoch 339/500 | Batch 80/202 | Rec 0.000562 | Seg 0.280111 | Elapsed 1.7m | ETA 2.6m
Epoch 339/500 | Batch 90/202 | Rec 0.000560 | Seg 0.280555 | Elapsed 1.9m | ETA 2.4m
Epoch 339/500 | Batch 100/202 | Rec 0.000572 | Seg 0.280003 | Elapsed 2.1m | ETA 2.1m
Epoch 339/500 | Batch 110/202 | Rec 0.000592 | Seg 0.284335 | Elapsed 2.3m | ETA 1.9m
Epoch 339/500 | Batch 120/202 | Rec 0.000583 | Seg 0.282684 | Elapsed 2.5m | ETA 1.7m
Epoch 339/500 | Batch 130/202 | Rec 0.000589 | Seg 0.280559 | Elapsed 2.7m | ETA 1.5m
Epoch 339/500 | Batch 140/202 | Rec 0.000589 | Seg 0.280725 | Elapsed 2.9m | ETA 1.3m
Epoch 339/500 | Batch 150/202 | Rec 0.000588 | Seg 0.278777 | Elapsed 3.2m | ETA 1.1m
Epoch 339/500 | Batch 160/202 | Rec 0.000589 | Seg 0.279655 | Elapsed 3.4m | ETA 0.9m
Epoch 339/500 | Batch 170/202 | Rec 0.000592 | Seg 0.281391 | Elapsed 3.6m | ETA 0.7m
Epoch 339/500 | Batch 180/202 | Rec 0.000588 | Seg 0.279914 | Elapsed 3.8m | ETA 0.5m
Epoch 339/500 | Batch 190/202 | Rec 0.000597 | Seg 0.280525 | Elapsed 4.0m | ETA 0.3m
Epoch 339/500 | Batch 200/202 | Rec 0.000603 | Seg 0.284066 | Elapsed 4.2m | ETA 0.0m
Epoch 339/500 | Batch 202/202 | Rec 0.000604 | Seg 0.284637 | Elapsed 4.2m | ETA 0.0m

2026-09-25 21:16:11,861 - INFO: Rec loss: 0.0006038223315170957
2026-09-25 21:16:11,861 - INFO: Seg loss: 0.28463657543358234
2026-09-25 21:16:11,861 - INFO: λ_rec: 1
2026-09-25 21:16:11,861 - INFO: λ_seg: 0.0001
2026-09-25 21:17:35,449 - INFO: -------------------Epoch: 339------------------------
2026-09-25 21:17:35,453 - INFO:
Validation stats:
        PSNR    SSIM      MSE
0  38.744013  0.9744  0.00014
2026-09-25 21:17:35,461 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995882  0.997887  0.997277  0.998597  0.996069
real potato   0.903024  0.948991  0.924537  0.974879  0.999875
fake potato   0.942714  0.970462  0.958904  0.982405  0.999957
real apple    0.752050  0.858431  0.962371  0.774834  0.999119
fake apple    0.565531  0.722432  0.992444  0.567976  0.998353
real orange   0.936146  0.966970  0.995099  0.940482  0.999915
fake orange   0.942810  0.970513  0.972850  0.968287  0.999832
real grape    0.723394  0.839450  0.942070  0.757071  0.999396
fake grape    0.894976  0.944528  0.922532  0.967702  0.999580
real lemon    0.667303  0.800408  0.831538  0.771618  0.999548
fake lemon    0.781102  0.877050  0.996240  0.783411  0.999536
real avocado  0.941645  0.969896  0.989411  0.951232  0.999945
fake avocado  0.744391  0.853419  0.999658  0.744580  0.999694
real pepper   0.840287  0.913163  0.860405  0.972927  0.999324
fake pepper   0.747641  0.855550  0.931354  0.791243  0.999363
real plant    0.857871  0.923449  0.936231  0.911109  0.998490
fake plant    0.803861  0.891217  0.839404  0.949962  0.999816
real banana   0.806813  0.893029  0.912012  0.874915  0.999529
fake banana   0.630298  0.773181  0.700067  0.863470  0.999068
real onion    0.623611  0.768130  0.637143  0.967066  0.999473
fake onion    0.911557  0.953682  0.940720  0.967110  0.999941
real unknown  0.718081  0.835861  0.760156  0.928435  0.999942
fake unknown  0.212901  0.351020  0.243866  0.626403  0.998049
total         0.780169  0.864292  0.880273  0.871118  0.999296
total(-bg)    0.770364  0.858220  0.874955  0.865323  0.999443
2026-09-25 21:17:36,026 - INFO: Epoch accounting: {'epoch': 339, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11342679, 57422, 59641, 96135, 127703, 94606, 63419, 123799, 153260, 78442, 57399, 33599, 54493, 207915, 136534, 123000, 16681, 88512, 85716, 104372, 74289, 7935, 50721], 'crops_with_class': [202, 34, 27, 24, 31, 27, 22, 26, 26, 33, 28, 13, 19, 54, 34, 18, 16, 30, 35, 43, 35, 8, 20], 'targeted_crops_by_class': [0, 2, 6, 3, 8, 4, 4, 6, 1, 5, 2, 3, 7, 4, 5, 5, 4, 12, 4, 5, 6, 2, 3], 'sampled_scene_counts': [0, 1, 3, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 4, 0, 2, 1, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 2, 0, 2, 0, 2, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 1, 0, 1, 2, 1, 3, 2, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 3, 0, 0, 1, 1, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 2, 2, 0, 0, 2, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 2, 2, 4, 3, 0, 1, 2, 1, 0, 3, 2, 2, 3, 1, 2, 2, 2, 2, 0, 1, 3, 1, 1, 0, 0, 0, 1, 2, 2, 2, 3, 2, 1, 1, 0, 1, 1, 2, 4, 1, 2, 5], 'learning_rate': 2.3931915330680322e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006038223315170957, 'train_segmentation_loss': 0.28463657543358234, 'val_foreground_miou_all22': 0.7703638355996602, 'val_psnr_ref1': 38.744012603759764, 'elapsed_seconds': 338.3757047653198, 'peak_cuda_allocated_gib': 7.506900787353516}

Epoch 340/500 | Batch 10/202 | Rec 0.000611 | Seg 0.278050 | Elapsed 0.2m | ETA 4.1m
Epoch 340/500 | Batch 20/202 | Rec 0.000564 | Seg 0.274159 | Elapsed 0.4m | ETA 3.8m
Epoch 340/500 | Batch 30/202 | Rec 0.000603 | Seg 0.294931 | Elapsed 0.6m | ETA 3.6m
Epoch 340/500 | Batch 40/202 | Rec 0.000626 | Seg 0.294669 | Elapsed 0.8m | ETA 3.4m
Epoch 340/500 | Batch 50/202 | Rec 0.000634 | Seg 0.313787 | Elapsed 1.0m | ETA 3.2m
Epoch 340/500 | Batch 60/202 | Rec 0.000644 | Seg 0.313145 | Elapsed 1.3m | ETA 3.0m
Epoch 340/500 | Batch 70/202 | Rec 0.000642 | Seg 0.312680 | Elapsed 1.5m | ETA 2.8m
Epoch 340/500 | Batch 80/202 | Rec 0.000631 | Seg 0.308897 | Elapsed 1.7m | ETA 2.6m
Epoch 340/500 | Batch 90/202 | Rec 0.000623 | Seg 0.299081 | Elapsed 1.9m | ETA 2.3m
Epoch 340/500 | Batch 100/202 | Rec 0.000618 | Seg 0.295912 | Elapsed 2.1m | ETA 2.1m
Epoch 340/500 | Batch 110/202 | Rec 0.000621 | Seg 0.295709 | Elapsed 2.3m | ETA 1.9m
Epoch 340/500 | Batch 120/202 | Rec 0.000631 | Seg 0.299172 | Elapsed 2.5m | ETA 1.7m
Epoch 340/500 | Batch 130/202 | Rec 0.000636 | Seg 0.305540 | Elapsed 2.7m | ETA 1.5m
Epoch 340/500 | Batch 140/202 | Rec 0.000636 | Seg 0.303297 | Elapsed 3.0m | ETA 1.3m
Epoch 340/500 | Batch 150/202 | Rec 0.000619 | Seg 0.295758 | Elapsed 3.2m | ETA 1.1m
Epoch 340/500 | Batch 160/202 | Rec 0.000610 | Seg 0.295153 | Elapsed 3.4m | ETA 0.9m
Epoch 340/500 | Batch 170/202 | Rec 0.000611 | Seg 0.297158 | Elapsed 3.6m | ETA 0.7m
Epoch 340/500 | Batch 180/202 | Rec 0.000618 | Seg 0.295232 | Elapsed 3.8m | ETA 0.5m
Epoch 340/500 | Batch 190/202 | Rec 0.000625 | Seg 0.302991 | Elapsed 4.0m | ETA 0.3m
Epoch 340/500 | Batch 200/202 | Rec 0.000621 | Seg 0.303763 | Elapsed 4.3m | ETA 0.0m
Epoch 340/500 | Batch 202/202 | Rec 0.000622 | Seg 0.304979 | Elapsed 4.3m | ETA 0.0m

2026-09-25 21:21:53,481 - INFO: Rec loss: 0.0006216399782679579
2026-09-25 21:21:53,481 - INFO: Seg loss: 0.3049789472750508
2026-09-25 21:21:53,481 - INFO: λ_rec: 1
2026-09-25 21:21:53,481 - INFO: λ_seg: 0.0001
2026-09-25 21:23:15,814 - INFO: -------------------Epoch: 340------------------------
2026-09-25 21:23:15,819 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.568019  0.974454  0.000144
2026-09-25 21:23:15,827 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995846  0.997869  0.997256  0.998582  0.996034
real potato   0.432543  0.603839  1.000000  0.432543  0.999321
fake potato   0.661671  0.796344  0.970783  0.675115  0.999749
real apple    0.710581  0.830757  0.799012  0.865237  0.998784
fake apple    0.603611  0.752767  0.967386  0.616149  0.998472
real orange   0.953978  0.976397  0.998548  0.955303  0.999939
fake orange   0.953106  0.975940  0.970588  0.981452  0.999862
real grape    0.778857  0.875633  0.971749  0.796901  0.999528
fake grape    0.897556  0.945963  0.930501  0.962051  0.999594
real lemon    0.392473  0.563661  0.434697  0.801610  0.998542
fake lemon    0.852969  0.920601  0.994642  0.856906  0.999687
real avocado  0.882887  0.937751  0.933605  0.942036  0.999884
fake avocado  0.668916  0.801570  0.997910  0.669855  0.999603
real pepper   0.896330  0.945282  0.935107  0.955782  0.999596
fake pepper   0.866957  0.928688  0.969762  0.891044  0.999674
real plant    0.874863  0.933206  0.938372  0.928194  0.998672
fake plant    0.857117  0.923012  0.950630  0.897048  0.999881
real banana   0.352532  0.521251  0.914636  0.364525  0.998496
fake banana   0.664488  0.798379  0.765050  0.834854  0.999225
real onion    0.638056  0.778991  0.731151  0.833643  0.999573
fake onion    0.855635  0.922152  0.990286  0.862878  0.999908
real unknown  0.894084  0.944031  1.000000  0.894084  0.999983
fake unknown  0.216688  0.356158  0.229063  0.800435  0.997562
total         0.734858  0.827402  0.886554  0.818097  0.999199
total(-bg)    0.722995  0.819653  0.881522  0.809893  0.999342
2026-09-25 21:23:16,387 - INFO: Epoch accounting: {'epoch': 340, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11236536, 47471, 56119, 143117, 128739, 86876, 100434, 102276, 185731, 84578, 59273, 46905, 39382, 214528, 113440, 218075, 32384, 93442, 68924, 85205, 49927, 10701, 34209], 'crops_with_class': [202, 30, 24, 39, 33, 28, 29, 19, 41, 34, 27, 17, 14, 52, 30, 25, 27, 25, 30, 37, 26, 11, 17], 'targeted_crops_by_class': [0, 5, 4, 9, 1, 8, 5, 1, 2, 4, 4, 5, 5, 3, 4, 7, 5, 4, 3, 5, 3, 4, 2], 'sampled_scene_counts': [1, 1, 1, 0, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 2, 3, 1, 1, 2, 1, 2, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 0, 1, 2, 1, 2, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1, 0, 3, 1, 1, 2, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 2, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 2, 4, 1, 1, 3, 1, 3, 1, 1, 2, 0, 2, 0, 2, 1, 1, 0, 1, 2, 4, 1, 0, 0, 1, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1, 5, 1, 2, 1, 4, 3, 0, 2, 2, 2, 1, 1, 0, 2, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 3, 3, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 4, 2], 'learning_rate': 2.3665754682701604e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006216399782679579, 'train_segmentation_loss': 0.3049789472750508, 'val_foreground_miou_all22': 0.722995375396925, 'val_psnr_ref1': 38.56801879882813, 'elapsed_seconds': 340.35159850120544, 'peak_cuda_allocated_gib': 7.503452301025391}

Epoch 341/500 | Batch 10/202 | Rec 0.000701 | Seg 0.332755 | Elapsed 0.2m | ETA 4.1m
Epoch 341/500 | Batch 20/202 | Rec 0.000624 | Seg 0.321341 | Elapsed 0.4m | ETA 3.9m
Epoch 341/500 | Batch 30/202 | Rec 0.000602 | Seg 0.307180 | Elapsed 0.6m | ETA 3.7m
Epoch 341/500 | Batch 40/202 | Rec 0.000593 | Seg 0.308129 | Elapsed 0.9m | ETA 3.5m
Epoch 341/500 | Batch 50/202 | Rec 0.000603 | Seg 0.301292 | Elapsed 1.1m | ETA 3.3m
Epoch 341/500 | Batch 60/202 | Rec 0.000614 | Seg 0.292452 | Elapsed 1.3m | ETA 3.0m
Epoch 341/500 | Batch 70/202 | Rec 0.000626 | Seg 0.300061 | Elapsed 1.5m | ETA 2.8m
Epoch 341/500 | Batch 80/202 | Rec 0.000616 | Seg 0.300363 | Elapsed 1.7m | ETA 2.6m
Epoch 341/500 | Batch 90/202 | Rec 0.000624 | Seg 0.303631 | Elapsed 1.9m | ETA 2.4m
Epoch 341/500 | Batch 100/202 | Rec 0.000615 | Seg 0.297563 | Elapsed 2.1m | ETA 2.2m
Epoch 341/500 | Batch 110/202 | Rec 0.000615 | Seg 0.297285 | Elapsed 2.3m | ETA 1.9m
Epoch 341/500 | Batch 120/202 | Rec 0.000609 | Seg 0.290108 | Elapsed 2.5m | ETA 1.7m
Epoch 341/500 | Batch 130/202 | Rec 0.000606 | Seg 0.286511 | Elapsed 2.7m | ETA 1.5m
Epoch 341/500 | Batch 140/202 | Rec 0.000620 | Seg 0.292613 | Elapsed 3.0m | ETA 1.3m
Epoch 341/500 | Batch 150/202 | Rec 0.000612 | Seg 0.288377 | Elapsed 3.2m | ETA 1.1m
Epoch 341/500 | Batch 160/202 | Rec 0.000604 | Seg 0.285667 | Elapsed 3.4m | ETA 0.9m
Epoch 341/500 | Batch 170/202 | Rec 0.000596 | Seg 0.280850 | Elapsed 3.6m | ETA 0.7m
Epoch 341/500 | Batch 180/202 | Rec 0.000598 | Seg 0.281539 | Elapsed 3.8m | ETA 0.5m
Epoch 341/500 | Batch 190/202 | Rec 0.000587 | Seg 0.280375 | Elapsed 4.0m | ETA 0.3m
Epoch 341/500 | Batch 200/202 | Rec 0.000591 | Seg 0.285269 | Elapsed 4.2m | ETA 0.0m
Epoch 341/500 | Batch 202/202 | Rec 0.000592 | Seg 0.284652 | Elapsed 4.3m | ETA 0.0m

2026-09-25 21:27:32,995 - INFO: Rec loss: 0.0005923258456214802
2026-09-25 21:27:32,995 - INFO: Seg loss: 0.28465154106811724
2026-09-25 21:27:32,996 - INFO: λ_rec: 1
2026-09-25 21:27:32,996 - INFO: λ_seg: 0.0001
2026-09-25 21:28:54,089 - INFO: -------------------Epoch: 341------------------------
2026-09-25 21:28:54,093 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  39.00477  0.974668  0.000132
2026-09-25 21:28:54,101 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995888  0.997890  0.997077  0.998804  0.996074
real potato   0.531704  0.694219  0.997135  0.532517  0.999439
fake potato   0.748822  0.856324  0.971558  0.765605  0.999813
real apple    0.731000  0.844548  0.807866  0.884830  0.998877
fake apple    0.612314  0.759500  0.984868  0.618130  0.998522
real orange   0.781445  0.877266  0.995590  0.784159  0.999711
fake orange   0.887008  0.940071  0.903079  0.980333  0.999642
real grape    0.839347  0.912608  0.957167  0.872104  0.999651
fake grape    0.893095  0.943479  0.942171  0.944891  0.999582
real lemon    0.455232  0.625603  0.484176  0.883926  0.998757
fake lemon    0.851699  0.919861  0.985657  0.862387  0.999682
real avocado  0.796735  0.886820  0.822934  0.961576  0.999772
fake avocado  0.837559  0.911550  0.998936  0.838307  0.999805
real pepper   0.872827  0.932046  0.925767  0.938512  0.999500
fake pepper   0.786587  0.880497  0.934277  0.832661  0.999462
real plant    0.878572  0.935312  0.955189  0.916341  0.998733
fake plant    0.812230  0.896337  0.891374  0.901457  0.999834
real banana   0.407540  0.579038  0.939902  0.418444  0.998633
fake banana   0.709192  0.829806  0.834872  0.824900  0.999378
real onion    0.600806  0.750580  0.723301  0.780105  0.999532
fake onion    0.931992  0.964749  0.989575  0.941233  0.999957
real unknown  0.948473  0.973505  1.000000  0.948473  0.999992
fake unknown  0.223664  0.365526  0.247888  0.695943  0.997965
total         0.744945  0.838136  0.882189  0.831550  0.999231
total(-bg)    0.733538  0.830875  0.876967  0.823947  0.999374
2026-09-25 21:28:54,871 - INFO: Epoch accounting: {'epoch': 341, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11330916, 48112, 61283, 143691, 149383, 76033, 72222, 107768, 189354, 79009, 51653, 39208, 56910, 219518, 120716, 140131, 29725, 62359, 60409, 92260, 56767, 9276, 41569], 'crops_with_class': [202, 29, 27, 37, 41, 24, 21, 23, 40, 35, 21, 15, 19, 55, 31, 24, 22, 20, 26, 39, 25, 12, 16], 'targeted_crops_by_class': [0, 5, 4, 2, 3, 5, 4, 3, 6, 1, 4, 5, 10, 4, 2, 6, 10, 2, 3, 7, 2, 5, 1], 'sampled_scene_counts': [0, 0, 1, 2, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 0, 2, 2, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 0, 2, 2, 0, 1, 3, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 2, 2, 0, 2, 1, 1, 3, 3, 2, 0, 1, 1, 2, 1, 3, 0, 7, 2, 2, 4, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 2, 2, 6, 1, 2, 2, 2, 2, 3, 5, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 3, 1, 1, 3, 2, 1, 1, 1, 1, 2, 2, 1, 1, 0, 2], 'learning_rate': 2.3400638600422508e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005923258456214802, 'train_segmentation_loss': 0.28465154106811724, 'val_foreground_miou_all22': 0.7335383848168436, 'val_psnr_ref1': 39.00476959228516, 'elapsed_seconds': 338.47466826438904, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 342/500 | Batch 10/202 | Rec 0.000458 | Seg 0.239182 | Elapsed 0.2m | ETA 4.1m
Epoch 342/500 | Batch 20/202 | Rec 0.000547 | Seg 0.276232 | Elapsed 0.4m | ETA 3.9m
Epoch 342/500 | Batch 30/202 | Rec 0.000582 | Seg 0.298280 | Elapsed 0.6m | ETA 3.6m
Epoch 342/500 | Batch 40/202 | Rec 0.000569 | Seg 0.278719 | Elapsed 0.8m | ETA 3.4m
Epoch 342/500 | Batch 50/202 | Rec 0.000580 | Seg 0.289923 | Elapsed 1.0m | ETA 3.2m
Epoch 342/500 | Batch 60/202 | Rec 0.000597 | Seg 0.290786 | Elapsed 1.3m | ETA 3.0m
Epoch 342/500 | Batch 70/202 | Rec 0.000610 | Seg 0.297640 | Elapsed 1.5m | ETA 2.8m
Epoch 342/500 | Batch 80/202 | Rec 0.000617 | Seg 0.303690 | Elapsed 1.7m | ETA 2.6m
Epoch 342/500 | Batch 90/202 | Rec 0.000612 | Seg 0.302169 | Elapsed 1.9m | ETA 2.4m
Epoch 342/500 | Batch 100/202 | Rec 0.000604 | Seg 0.302157 | Elapsed 2.1m | ETA 2.1m
Epoch 342/500 | Batch 110/202 | Rec 0.000608 | Seg 0.302728 | Elapsed 2.3m | ETA 1.9m
Epoch 342/500 | Batch 120/202 | Rec 0.000613 | Seg 0.302421 | Elapsed 2.5m | ETA 1.7m
Epoch 342/500 | Batch 130/202 | Rec 0.000625 | Seg 0.299052 | Elapsed 2.7m | ETA 1.5m
Epoch 342/500 | Batch 140/202 | Rec 0.000623 | Seg 0.301326 | Elapsed 2.9m | ETA 1.3m
Epoch 342/500 | Batch 150/202 | Rec 0.000621 | Seg 0.304048 | Elapsed 3.1m | ETA 1.1m
Epoch 342/500 | Batch 160/202 | Rec 0.000628 | Seg 0.306884 | Elapsed 3.3m | ETA 0.9m
Epoch 342/500 | Batch 170/202 | Rec 0.000645 | Seg 0.311426 | Elapsed 3.6m | ETA 0.7m
Epoch 342/500 | Batch 180/202 | Rec 0.000651 | Seg 0.314651 | Elapsed 3.8m | ETA 0.5m
Epoch 342/500 | Batch 190/202 | Rec 0.000652 | Seg 0.316823 | Elapsed 4.0m | ETA 0.3m
Epoch 342/500 | Batch 200/202 | Rec 0.000645 | Seg 0.314611 | Elapsed 4.2m | ETA 0.0m
Epoch 342/500 | Batch 202/202 | Rec 0.000647 | Seg 0.315191 | Elapsed 4.2m | ETA 0.0m

2026-09-25 21:33:09,404 - INFO: Rec loss: 0.000647079520487102
2026-09-25 21:33:09,404 - INFO: Seg loss: 0.315190631638069
2026-09-25 21:33:09,404 - INFO: λ_rec: 1
2026-09-25 21:33:09,404 - INFO: λ_seg: 0.0001
2026-09-25 21:34:29,548 - INFO: -------------------Epoch: 342------------------------
2026-09-25 21:34:29,553 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.895099  0.974597  0.000134
2026-09-25 21:34:29,561 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995530  0.997710  0.996708  0.998814  0.995730
real potato   0.544039  0.704650  0.986235  0.548202  0.999450
fake potato   0.653314  0.790260  0.978658  0.662757  0.999744
real apple    0.726367  0.841448  0.847749  0.835338  0.998914
fake apple    0.638018  0.778964  0.955378  0.657614  0.998591
real orange   0.735008  0.847219  0.999685  0.735178  0.999651
fake orange   0.863276  0.926572  0.892471  0.963490  0.999563
real grape    0.778471  0.875389  0.963236  0.802309  0.999523
fake grape    0.899166  0.946856  0.928963  0.965557  0.999599
real lemon    0.637917  0.778889  0.667346  0.935341  0.999376
fake lemon    0.850554  0.919193  0.997216  0.852578  0.999683
real avocado  0.901317  0.948047  0.940967  0.955337  0.999903
fake avocado  0.732883  0.845805  0.999826  0.732976  0.999680
real pepper   0.885799  0.939391  0.926670  0.952570  0.999551
fake pepper   0.826677  0.905066  0.963501  0.853402  0.999574
real plant    0.853983  0.921192  0.949412  0.894694  0.998470
fake plant    0.863885  0.926923  0.917230  0.936925  0.999883
real banana   0.617049  0.763130  0.926411  0.648852  0.999095
fake banana   0.724446  0.840158  0.861979  0.819509  0.999427
real onion    0.638167  0.779075  0.670854  0.929066  0.999524
fake onion    0.895733  0.944949  0.990196  0.903748  0.999934
real unknown  0.796875  0.886907  0.852243  0.924618  0.999962
fake unknown  0.238524  0.385136  0.258136  0.758421  0.997960
total         0.752043  0.847519  0.890046  0.837709  0.999252
total(-bg)    0.740976  0.840692  0.885198  0.830386  0.999412
2026-09-25 21:34:30,161 - INFO: Epoch accounting: {'epoch': 342, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11137678, 43169, 51518, 159025, 155785, 74701, 71710, 151032, 185091, 82676, 79969, 66809, 39950, 235774, 147244, 143925, 25566, 107658, 83042, 95268, 58379, 7095, 35208], 'crops_with_class': [202, 34, 28, 39, 36, 24, 24, 27, 37, 31, 29, 22, 14, 56, 36, 19, 20, 34, 33, 39, 27, 7, 15], 'targeted_crops_by_class': [0, 5, 5, 5, 4, 2, 7, 6, 1, 6, 5, 9, 6, 6, 6, 5, 1, 6, 8, 5, 8, 1, 4], 'sampled_scene_counts': [1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 3, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 1, 0, 0, 0, 1, 2, 1, 2, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 0, 1, 1, 1, 2, 1, 2, 0, 4, 2, 1, 1, 1, 2, 2, 3, 4, 2, 0, 1, 1, 1, 1, 2, 2, 0, 1, 2, 2, 0, 1, 3, 0, 0, 2, 0, 1, 0, 0, 2, 3, 2, 2, 1, 1, 1, 2, 2, 4, 2, 2, 2, 2, 1, 3, 1, 1, 3, 0, 0, 2, 2, 0, 1, 3, 3, 0, 0, 4, 1, 1, 1, 0, 0, 1, 0, 1, 2, 2, 3, 1, 2], 'learning_rate': 2.3136577550172028e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000647079520487102, 'train_segmentation_loss': 0.315190631638069, 'val_foreground_miou_all22': 0.7409758964661285, 'val_psnr_ref1': 38.89509918212891, 'elapsed_seconds': 335.2821729183197, 'peak_cuda_allocated_gib': 7.505161285400391}

Epoch 343/500 | Batch 10/202 | Rec 0.000699 | Seg 0.264428 | Elapsed 0.2m | ETA 4.1m
Epoch 343/500 | Batch 20/202 | Rec 0.000630 | Seg 0.261312 | Elapsed 0.4m | ETA 3.9m
Epoch 343/500 | Batch 30/202 | Rec 0.000673 | Seg 0.257847 | Elapsed 0.6m | ETA 3.7m
Epoch 343/500 | Batch 40/202 | Rec 0.000641 | Seg 0.264333 | Elapsed 0.8m | ETA 3.4m
Epoch 343/500 | Batch 50/202 | Rec 0.000655 | Seg 0.283622 | Elapsed 1.1m | ETA 3.2m
Epoch 343/500 | Batch 60/202 | Rec 0.000659 | Seg 0.298550 | Elapsed 1.3m | ETA 3.0m
Epoch 343/500 | Batch 70/202 | Rec 0.000647 | Seg 0.293288 | Elapsed 1.5m | ETA 2.8m
Epoch 343/500 | Batch 80/202 | Rec 0.000642 | Seg 0.298930 | Elapsed 1.7m | ETA 2.6m
Epoch 343/500 | Batch 90/202 | Rec 0.000645 | Seg 0.293122 | Elapsed 1.9m | ETA 2.4m
Epoch 343/500 | Batch 100/202 | Rec 0.000641 | Seg 0.292597 | Elapsed 2.1m | ETA 2.2m
Epoch 343/500 | Batch 110/202 | Rec 0.000625 | Seg 0.288218 | Elapsed 2.3m | ETA 2.0m
Epoch 343/500 | Batch 120/202 | Rec 0.000617 | Seg 0.291415 | Elapsed 2.6m | ETA 1.7m
Epoch 343/500 | Batch 130/202 | Rec 0.000618 | Seg 0.295147 | Elapsed 2.8m | ETA 1.5m
Epoch 343/500 | Batch 140/202 | Rec 0.000619 | Seg 0.294219 | Elapsed 3.0m | ETA 1.3m
Epoch 343/500 | Batch 150/202 | Rec 0.000623 | Seg 0.294928 | Elapsed 3.2m | ETA 1.1m
Epoch 343/500 | Batch 160/202 | Rec 0.000623 | Seg 0.292121 | Elapsed 3.4m | ETA 0.9m
Epoch 343/500 | Batch 170/202 | Rec 0.000623 | Seg 0.293495 | Elapsed 3.6m | ETA 0.7m
Epoch 343/500 | Batch 180/202 | Rec 0.000623 | Seg 0.294203 | Elapsed 3.8m | ETA 0.5m
Epoch 343/500 | Batch 190/202 | Rec 0.000626 | Seg 0.295993 | Elapsed 4.0m | ETA 0.3m
Epoch 343/500 | Batch 200/202 | Rec 0.000628 | Seg 0.293308 | Elapsed 4.3m | ETA 0.0m
Epoch 343/500 | Batch 202/202 | Rec 0.000629 | Seg 0.293547 | Elapsed 4.3m | ETA 0.0m

2026-09-25 21:38:48,122 - INFO: Rec loss: 0.0006293263455644241
2026-09-25 21:38:48,122 - INFO: Seg loss: 0.29354665183121026
2026-09-25 21:38:48,122 - INFO: λ_rec: 1
2026-09-25 21:38:48,122 - INFO: λ_seg: 0.0001
2026-09-25 21:40:08,596 - INFO: -------------------Epoch: 343------------------------
2026-09-25 21:40:08,601 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.861339  0.974675  0.000135
2026-09-25 21:40:08,609 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995952  0.997922  0.997413  0.998532  0.996137
real potato   0.722265  0.838690  0.996839  0.723922  0.999667
fake potato   0.752051  0.858431  0.972937  0.768119  0.999816
real apple    0.777194  0.874580  0.879342  0.869969  0.999140
fake apple    0.596318  0.747070  0.990851  0.599620  0.998467
real orange   0.879954  0.936094  0.987912  0.889532  0.999840
fake orange   0.909082  0.952326  0.937930  0.967274  0.999723
real grape    0.803848  0.891209  0.969744  0.824527  0.999580
fake grape    0.895569  0.944858  0.921443  0.969599  0.999582
real lemon    0.458379  0.628568  0.494132  0.863672  0.998801
fake lemon    0.857634  0.923312  0.991801  0.863758  0.999697
real avocado  0.762228  0.865023  0.787495  0.959606  0.999722
fake avocado  0.857034  0.922964  0.999109  0.857689  0.999829
real pepper   0.811631  0.895973  0.870287  0.923327  0.999216
fake pepper   0.726313  0.841412  0.960190  0.748864  0.999327
real plant    0.871822  0.931472  0.951507  0.912360  0.998658
fake plant    0.890222  0.941873  0.931073  0.953029  0.999906
real banana   0.503715  0.669913  0.862227  0.547807  0.998787
fake banana   0.692168  0.818035  0.783798  0.855508  0.999300
real onion    0.643292  0.782881  0.708157  0.875359  0.999561
fake onion    0.938491  0.968219  0.977334  0.959371  0.999960
real unknown  0.852137  0.920116  0.890974  0.951336  0.999974
fake unknown  0.222102  0.363437  0.244554  0.707533  0.997912
total         0.757365  0.848451  0.874220  0.851753  0.999244
total(-bg)    0.746520  0.841657  0.868620  0.845081  0.999385
2026-09-25 21:40:09,190 - INFO: Epoch accounting: {'epoch': 343, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11284593, 36885, 52512, 190743, 189425, 85197, 60014, 140918, 174062, 82116, 79908, 36876, 31482, 179008, 121534, 137799, 26306, 77742, 86560, 64432, 36458, 10815, 52887], 'crops_with_class': [202, 22, 24, 47, 44, 27, 22, 29, 32, 36, 33, 15, 12, 46, 30, 21, 22, 23, 33, 29, 22, 12, 23], 'targeted_crops_by_class': [0, 5, 5, 8, 5, 10, 1, 3, 3, 6, 7, 2, 4, 1, 4, 4, 1, 7, 2, 2, 8, 5, 5], 'sampled_scene_counts': [2, 2, 2, 1, 1, 0, 1, 1, 1, 2, 1, 2, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 2, 1, 0, 2, 0, 2, 1, 2, 1, 2, 0, 0, 2, 1, 5, 0, 5, 1, 0, 2, 2, 1, 0, 5, 1, 0, 0, 2, 1, 1, 4, 1, 2, 0, 2, 1, 2, 1, 1, 3, 1, 2, 1, 2, 4, 1, 4, 2, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 4, 1, 0, 1, 0, 2, 1, 4, 0, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 2, 2, 1], 'learning_rate': 2.287358195662829e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006293263455644241, 'train_segmentation_loss': 0.29354665183121026, 'val_foreground_miou_all22': 0.7465203752157756, 'val_psnr_ref1': 38.86133880615235, 'elapsed_seconds': 339.01683926582336, 'peak_cuda_allocated_gib': 7.512241363525391}

Epoch 344/500 | Batch 10/202 | Rec 0.000785 | Seg 0.336279 | Elapsed 0.2m | ETA 4.0m
Epoch 344/500 | Batch 20/202 | Rec 0.000744 | Seg 0.347153 | Elapsed 0.4m | ETA 3.9m
Epoch 344/500 | Batch 30/202 | Rec 0.000711 | Seg 0.352606 | Elapsed 0.6m | ETA 3.7m
Epoch 344/500 | Batch 40/202 | Rec 0.000685 | Seg 0.348165 | Elapsed 0.9m | ETA 3.5m
Epoch 344/500 | Batch 50/202 | Rec 0.000645 | Seg 0.320924 | Elapsed 1.1m | ETA 3.2m
Epoch 344/500 | Batch 60/202 | Rec 0.000628 | Seg 0.310880 | Elapsed 1.3m | ETA 3.0m
Epoch 344/500 | Batch 70/202 | Rec 0.000625 | Seg 0.304727 | Elapsed 1.5m | ETA 2.8m
Epoch 344/500 | Batch 80/202 | Rec 0.000615 | Seg 0.304946 | Elapsed 1.7m | ETA 2.6m
Epoch 344/500 | Batch 90/202 | Rec 0.000618 | Seg 0.304286 | Elapsed 1.9m | ETA 2.4m
Epoch 344/500 | Batch 100/202 | Rec 0.000618 | Seg 0.302134 | Elapsed 2.1m | ETA 2.1m
Epoch 344/500 | Batch 110/202 | Rec 0.000612 | Seg 0.300277 | Elapsed 2.3m | ETA 1.9m
Epoch 344/500 | Batch 120/202 | Rec 0.000616 | Seg 0.306649 | Elapsed 2.5m | ETA 1.7m
Epoch 344/500 | Batch 130/202 | Rec 0.000611 | Seg 0.303196 | Elapsed 2.7m | ETA 1.5m
Epoch 344/500 | Batch 140/202 | Rec 0.000612 | Seg 0.303489 | Elapsed 2.9m | ETA 1.3m
Epoch 344/500 | Batch 150/202 | Rec 0.000599 | Seg 0.296047 | Elapsed 3.1m | ETA 1.1m
Epoch 344/500 | Batch 160/202 | Rec 0.000600 | Seg 0.297855 | Elapsed 3.3m | ETA 0.9m
Epoch 344/500 | Batch 170/202 | Rec 0.000591 | Seg 0.295884 | Elapsed 3.6m | ETA 0.7m
Epoch 344/500 | Batch 180/202 | Rec 0.000593 | Seg 0.296950 | Elapsed 3.8m | ETA 0.5m
Epoch 344/500 | Batch 190/202 | Rec 0.000586 | Seg 0.291608 | Elapsed 4.0m | ETA 0.3m
Epoch 344/500 | Batch 200/202 | Rec 0.000592 | Seg 0.291166 | Elapsed 4.2m | ETA 0.0m
Epoch 344/500 | Batch 202/202 | Rec 0.000590 | Seg 0.290242 | Elapsed 4.2m | ETA 0.0m

2026-09-25 21:44:23,165 - INFO: Rec loss: 0.0005901839024655862
2026-09-25 21:44:23,165 - INFO: Seg loss: 0.29024169429915375
2026-09-25 21:44:23,165 - INFO: λ_rec: 1
2026-09-25 21:44:23,165 - INFO: λ_seg: 0.0001
2026-09-25 21:45:40,901 - INFO: -------------------Epoch: 344------------------------
2026-09-25 21:45:40,905 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.781708  0.974627  0.000138
2026-09-25 21:45:40,913 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995832  0.997862  0.997184  0.998641  0.996021
real potato   0.283984  0.442313  1.000000  0.283984  0.999143
fake potato   0.652865  0.789932  0.997444  0.653959  0.999747
real apple    0.665722  0.799270  0.723043  0.893587  0.998452
fake apple    0.684848  0.812900  0.961174  0.704332  0.998776
real orange   0.911755  0.953791  0.991627  0.918828  0.999883
fake orange   0.931181  0.964314  0.949809  0.979373  0.999793
real grape    0.773846  0.872457  0.953789  0.803990  0.999509
fake grape    0.897158  0.945741  0.929918  0.962216  0.999592
real lemon    0.444915  0.615792  0.454484  0.954817  0.998600
fake lemon    0.860073  0.924724  0.989476  0.868013  0.999701
real avocado  0.778671  0.875515  0.808795  0.954351  0.999748
fake avocado  0.784234  0.879021  0.996285  0.786534  0.999741
real pepper   0.755037  0.860373  0.805067  0.923953  0.998904
fake pepper   0.564051  0.721223  0.960196  0.577556  0.998936
real plant    0.867951  0.929258  0.945391  0.913763  0.998609
fake plant    0.809293  0.894546  0.926474  0.864839  0.999838
real banana   0.306043  0.468618  0.868886  0.320861  0.998365
fake banana   0.746129  0.854559  0.849947  0.859323  0.999462
real onion    0.495012  0.662168  0.689649  0.636886  0.999413
fake onion    0.873883  0.932647  0.998895  0.874728  0.999920
real unknown  0.794164  0.885225  0.820701  0.960878  0.999960
fake unknown  0.249970  0.399922  0.272417  0.752083  0.998099
total         0.701157  0.803573  0.864811  0.802065  0.999140
total(-bg)    0.687763  0.794741  0.858794  0.793130  0.999281
2026-09-25 21:45:41,480 - INFO: Epoch accounting: {'epoch': 344, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11288895, 52415, 39642, 151222, 176533, 84248, 83584, 117582, 183295, 86845, 74148, 51898, 39844, 193012, 104546, 187133, 27796, 64726, 42687, 71634, 51142, 15087, 50358], 'crops_with_class': [202, 26, 19, 42, 42, 26, 30, 23, 37, 39, 29, 18, 14, 46, 28, 28, 26, 20, 23, 32, 22, 16, 22], 'targeted_crops_by_class': [0, 4, 1, 8, 5, 6, 8, 4, 4, 5, 7, 6, 6, 4, 3, 7, 8, 6, 2, 2, 5, 5, 4], 'sampled_scene_counts': [1, 1, 1, 1, 1, 2, 1, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 2, 1, 1, 1, 0, 0, 0, 1, 3, 0, 0, 2, 1, 0, 3, 0, 0, 2, 0, 1, 1, 1, 0, 0, 0, 3, 1, 3, 1, 2, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 2, 0, 2, 2, 1, 1, 1, 1, 2, 2, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 1, 2, 0, 1, 0, 1, 1, 0, 0, 2, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 3, 1, 1, 2, 1, 2, 3, 1, 2, 1, 1, 2, 2, 0, 3, 0, 1, 1, 2, 0, 2, 5, 3, 3, 0, 2, 1, 0, 0, 1, 4, 1, 0, 2, 2, 2, 3, 4, 2, 1, 1, 1, 1, 0, 3, 2, 2, 3, 2, 1, 0, 3, 1, 1, 1, 0, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 1, 2, 2, 0, 1, 1, 0, 0, 1, 1, 1], 'learning_rate': 2.2611662202407e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005901839024655862, 'train_segmentation_loss': 0.29024169429915375, 'val_foreground_miou_all22': 0.6877628534612739, 'val_psnr_ref1': 38.781708221435544, 'elapsed_seconds': 332.2810950279236, 'peak_cuda_allocated_gib': 7.514438629150391}

Epoch 345/500 | Batch 10/202 | Rec 0.000766 | Seg 0.371090 | Elapsed 0.2m | ETA 4.2m
Epoch 345/500 | Batch 20/202 | Rec 0.000694 | Seg 0.313795 | Elapsed 0.4m | ETA 3.9m
Epoch 345/500 | Batch 30/202 | Rec 0.000684 | Seg 0.303628 | Elapsed 0.6m | ETA 3.7m
Epoch 345/500 | Batch 40/202 | Rec 0.000635 | Seg 0.300403 | Elapsed 0.9m | ETA 3.5m
Epoch 345/500 | Batch 50/202 | Rec 0.000622 | Seg 0.302706 | Elapsed 1.1m | ETA 3.2m
Epoch 345/500 | Batch 60/202 | Rec 0.000630 | Seg 0.308424 | Elapsed 1.3m | ETA 3.0m
Epoch 345/500 | Batch 70/202 | Rec 0.000612 | Seg 0.297118 | Elapsed 1.5m | ETA 2.8m
Epoch 345/500 | Batch 80/202 | Rec 0.000630 | Seg 0.300287 | Elapsed 1.7m | ETA 2.6m
Epoch 345/500 | Batch 90/202 | Rec 0.000627 | Seg 0.293213 | Elapsed 1.9m | ETA 2.4m
Epoch 345/500 | Batch 100/202 | Rec 0.000613 | Seg 0.288625 | Elapsed 2.1m | ETA 2.2m
Epoch 345/500 | Batch 110/202 | Rec 0.000605 | Seg 0.286545 | Elapsed 2.3m | ETA 2.0m
Epoch 345/500 | Batch 120/202 | Rec 0.000600 | Seg 0.286484 | Elapsed 2.6m | ETA 1.7m
Epoch 345/500 | Batch 130/202 | Rec 0.000600 | Seg 0.285726 | Elapsed 2.8m | ETA 1.5m
Epoch 345/500 | Batch 140/202 | Rec 0.000592 | Seg 0.279132 | Elapsed 3.0m | ETA 1.3m
Epoch 345/500 | Batch 150/202 | Rec 0.000593 | Seg 0.278559 | Elapsed 3.2m | ETA 1.1m
Epoch 345/500 | Batch 160/202 | Rec 0.000588 | Seg 0.278068 | Elapsed 3.4m | ETA 0.9m
Epoch 345/500 | Batch 170/202 | Rec 0.000596 | Seg 0.278554 | Elapsed 3.6m | ETA 0.7m
Epoch 345/500 | Batch 180/202 | Rec 0.000596 | Seg 0.280736 | Elapsed 3.8m | ETA 0.5m
Epoch 345/500 | Batch 190/202 | Rec 0.000589 | Seg 0.277523 | Elapsed 4.0m | ETA 0.3m
Epoch 345/500 | Batch 200/202 | Rec 0.000587 | Seg 0.281506 | Elapsed 4.3m | ETA 0.0m
Epoch 345/500 | Batch 202/202 | Rec 0.000590 | Seg 0.281998 | Elapsed 4.3m | ETA 0.0m

2026-09-25 21:49:59,611 - INFO: Rec loss: 0.0005904069408949576
2026-09-25 21:49:59,612 - INFO: Seg loss: 0.2819977889925537
2026-09-25 21:49:59,612 - INFO: λ_rec: 1
2026-09-25 21:49:59,612 - INFO: λ_seg: 0.0001
2026-09-25 21:51:18,252 - INFO: -------------------Epoch: 345------------------------
2026-09-25 21:51:18,257 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.927115  0.974706  0.000133
2026-09-25 21:51:18,265 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995899  0.997895  0.997271  0.998621  0.996086
real potato   0.731463  0.844858  0.994133  0.734634  0.999677
fake potato   0.840222  0.913125  0.978683  0.855886  0.999881
real apple    0.759167  0.863048  0.874943  0.851570  0.999068
fake apple    0.625920  0.769879  0.967815  0.639226  0.998558
real orange   0.812853  0.896717  0.995619  0.815771  0.999753
fake orange   0.894418  0.944217  0.914378  0.976175  0.999670
real grape    0.771992  0.871277  0.968197  0.792078  0.999512
fake grape    0.904379  0.949739  0.940437  0.959328  0.999625
real lemon    0.490008  0.657679  0.522214  0.888211  0.998914
fake lemon    0.846729  0.916954  0.996194  0.849477  0.999675
real avocado  0.861997  0.925835  0.899504  0.953859  0.999858
fake avocado  0.773869  0.872472  0.999506  0.774165  0.999729
real pepper   0.880140  0.936200  0.920401  0.952653  0.999525
fake pepper   0.820885  0.901583  0.951187  0.856987  0.999554
real plant    0.875224  0.933411  0.941581  0.925479  0.998680
fake plant    0.825820  0.904552  0.906605  0.902607  0.999848
real banana   0.462784  0.632699  0.909484  0.485128  0.998735
fake banana   0.666237  0.799641  0.749565  0.857001  0.999210
real onion    0.608411  0.756487  0.705093  0.816078  0.999525
fake onion    0.934195  0.965928  0.988855  0.944135  0.999958
real unknown  0.922710  0.959751  1.000000  0.922710  0.999988
fake unknown  0.247643  0.396939  0.269703  0.751720  0.998076
total         0.763172  0.852647  0.886581  0.847978  0.999265
total(-bg)    0.752594  0.846045  0.881550  0.841131  0.999410
2026-09-25 21:51:18,836 - INFO: Epoch accounting: {'epoch': 345, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11359494, 46578, 44716, 134791, 165599, 102704, 81398, 101492, 176500, 56541, 52577, 48324, 45290, 225327, 118113, 170517, 22967, 93559, 69326, 63380, 36574, 2047, 20458], 'crops_with_class': [202, 31, 22, 30, 39, 30, 27, 20, 35, 30, 22, 18, 17, 58, 29, 20, 19, 23, 29, 28, 17, 4, 12], 'targeted_crops_by_class': [0, 3, 3, 3, 8, 7, 2, 2, 4, 4, 6, 3, 7, 5, 2, 4, 4, 3, 6, 2, 3, 3, 2], 'sampled_scene_counts': [2, 2, 2, 2, 1, 1, 0, 0, 2, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 1, 2, 0, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 0, 2, 1, 1, 0, 0, 2, 1, 1, 1, 3, 0, 0, 3, 1, 2, 0, 1, 0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 2, 0, 1, 1, 1, 0, 0, 1, 2, 4, 3, 1, 1, 2, 1, 2, 3, 1, 2, 1, 0, 2, 2, 3, 1, 0, 3, 1, 2, 2, 0, 3, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 3, 4, 3, 0, 0, 2, 1, 0, 1, 1, 4, 0, 1, 2, 2, 2, 1, 1, 0, 2, 1, 1, 1, 3, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0], 'learning_rate': 2.235082862765158e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005904069408949576, 'train_segmentation_loss': 0.2819977889925537, 'val_foreground_miou_all22': 0.7525939392080931, 'val_psnr_ref1': 38.92711456298828, 'elapsed_seconds': 337.347939491272, 'peak_cuda_allocated_gib': 7.504428863525391}

Epoch 346/500 | Batch 10/202 | Rec 0.000495 | Seg 0.286938 | Elapsed 0.2m | ETA 4.1m
Epoch 346/500 | Batch 20/202 | Rec 0.000563 | Seg 0.310623 | Elapsed 0.4m | ETA 3.9m
Epoch 346/500 | Batch 30/202 | Rec 0.000611 | Seg 0.293344 | Elapsed 0.6m | ETA 3.7m
Epoch 346/500 | Batch 40/202 | Rec 0.000593 | Seg 0.294348 | Elapsed 0.9m | ETA 3.4m
Epoch 346/500 | Batch 50/202 | Rec 0.000601 | Seg 0.292559 | Elapsed 1.1m | ETA 3.2m
Epoch 346/500 | Batch 60/202 | Rec 0.000602 | Seg 0.288902 | Elapsed 1.3m | ETA 3.0m
Epoch 346/500 | Batch 70/202 | Rec 0.000589 | Seg 0.285720 | Elapsed 1.5m | ETA 2.8m
Epoch 346/500 | Batch 80/202 | Rec 0.000582 | Seg 0.279948 | Elapsed 1.7m | ETA 2.6m
Epoch 346/500 | Batch 90/202 | Rec 0.000587 | Seg 0.281375 | Elapsed 1.9m | ETA 2.3m
Epoch 346/500 | Batch 100/202 | Rec 0.000593 | Seg 0.280884 | Elapsed 2.1m | ETA 2.1m
Epoch 346/500 | Batch 110/202 | Rec 0.000594 | Seg 0.279161 | Elapsed 2.3m | ETA 1.9m
Epoch 346/500 | Batch 120/202 | Rec 0.000586 | Seg 0.275764 | Elapsed 2.5m | ETA 1.7m
Epoch 346/500 | Batch 130/202 | Rec 0.000589 | Seg 0.276726 | Elapsed 2.7m | ETA 1.5m
Epoch 346/500 | Batch 140/202 | Rec 0.000592 | Seg 0.279430 | Elapsed 2.9m | ETA 1.3m
Epoch 346/500 | Batch 150/202 | Rec 0.000585 | Seg 0.277672 | Elapsed 3.1m | ETA 1.1m
Epoch 346/500 | Batch 160/202 | Rec 0.000580 | Seg 0.277077 | Elapsed 3.3m | ETA 0.9m
Epoch 346/500 | Batch 170/202 | Rec 0.000584 | Seg 0.279466 | Elapsed 3.6m | ETA 0.7m
Epoch 346/500 | Batch 180/202 | Rec 0.000582 | Seg 0.280505 | Elapsed 3.8m | ETA 0.5m
Epoch 346/500 | Batch 190/202 | Rec 0.000585 | Seg 0.282896 | Elapsed 4.0m | ETA 0.3m
Epoch 346/500 | Batch 200/202 | Rec 0.000587 | Seg 0.284865 | Elapsed 4.2m | ETA 0.0m
Epoch 346/500 | Batch 202/202 | Rec 0.000586 | Seg 0.284765 | Elapsed 4.2m | ETA 0.0m

2026-09-25 21:55:32,079 - INFO: Rec loss: 0.0005862300742664236
2026-09-25 21:55:32,079 - INFO: Seg loss: 0.2847653594568814
2026-09-25 21:55:32,079 - INFO: λ_rec: 1
2026-09-25 21:55:32,079 - INFO: λ_seg: 0.0001
2026-09-25 21:56:53,003 - INFO: -------------------Epoch: 346------------------------
2026-09-25 21:56:53,008 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.878503  0.974304  0.000135
2026-09-25 21:56:53,015 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995599  0.997745  0.997007  0.998583  0.995798
real potato   0.256185  0.407845  1.000000  0.256185  0.999110
fake potato   0.636663  0.777954  0.974464  0.647465  0.999731
real apple    0.673486  0.804840  0.750516  0.867758  0.998549
fake apple    0.797983  0.887593  0.952055  0.831393  0.999205
real orange   0.944380  0.971345  0.996348  0.947661  0.999926
fake orange   0.949718  0.974161  0.968946  0.979533  0.999852
real grape    0.818015  0.899849  0.959987  0.846890  0.999607
fake grape    0.866647  0.928510  0.891516  0.968816  0.999449
real lemon    0.354713  0.523629  0.385778  0.814983  0.998258
fake lemon    0.855003  0.921785  0.992760  0.860368  0.999691
real avocado  0.760754  0.864074  0.781034  0.966995  0.999717
fake avocado  0.676527  0.807009  0.999812  0.676613  0.999613
real pepper   0.772463  0.871577  0.823024  0.926331  0.999002
fake pepper   0.607719  0.755954  0.976193  0.616862  0.999051
real plant    0.877010  0.934426  0.952025  0.917562  0.998713
fake plant    0.714524  0.833445  0.845835  0.821511  0.999739
real banana   0.210610  0.347910  0.909300  0.215130  0.998188
fake banana   0.675468  0.806254  0.782337  0.831785  0.999265
real onion    0.606303  0.754855  0.720491  0.792771  0.999535
fake onion    0.859349  0.924305  0.997200  0.861427  0.999911
real unknown  0.881495  0.936965  0.951772  0.922710  0.999980
fake unknown  0.316902  0.481242  0.346626  0.787034  0.998571
total         0.700327  0.800577  0.867610  0.798103  0.999150
total(-bg)    0.686905  0.791615  0.861728  0.788990  0.999303
2026-09-25 21:56:53,573 - INFO: Epoch accounting: {'epoch': 346, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11345726, 40483, 60903, 123887, 138740, 69867, 87499, 155826, 196471, 100548, 78356, 43404, 18136, 208891, 91871, 122379, 22763, 90009, 57023, 91463, 49984, 5008, 39035], 'crops_with_class': [202, 24, 26, 35, 37, 20, 27, 32, 34, 42, 33, 15, 7, 52, 26, 17, 23, 24, 26, 33, 24, 7, 18], 'targeted_crops_by_class': [0, 3, 4, 6, 4, 5, 6, 10, 6, 7, 7, 4, 5, 5, 1, 4, 4, 6, 4, 8, 2, 5, 4], 'sampled_scene_counts': [1, 0, 2, 0, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 3, 0, 2, 0, 0, 2, 0, 1, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 0, 0, 2, 2, 3, 2, 1, 2, 0, 2, 2, 2, 0, 1, 2, 1, 3, 1, 3, 1, 2, 2, 2, 1, 0, 2, 0, 0, 1, 1, 1, 1, 5, 1, 0, 1, 0, 1, 0, 0, 7, 2, 1, 2, 2, 1, 1, 1, 0, 1, 2, 0, 0, 1, 2, 1, 0, 3, 1, 4, 0, 2, 0, 0, 1, 1, 0, 2, 2, 4, 1, 0, 2, 1, 1, 1, 2, 1, 0], 'learning_rate': 2.209109152962494e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005862300742664236, 'train_segmentation_loss': 0.2847653594568814, 'val_foreground_miou_all22': 0.6869054188962658, 'val_psnr_ref1': 38.878502655029294, 'elapsed_seconds': 334.72809886932373, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 347/500 | Batch 10/202 | Rec 0.000863 | Seg 0.304283 | Elapsed 0.2m | ETA 4.2m
Epoch 347/500 | Batch 20/202 | Rec 0.000730 | Seg 0.303517 | Elapsed 0.4m | ETA 3.9m
Epoch 347/500 | Batch 30/202 | Rec 0.000667 | Seg 0.289016 | Elapsed 0.6m | ETA 3.7m
Epoch 347/500 | Batch 40/202 | Rec 0.000635 | Seg 0.284454 | Elapsed 0.9m | ETA 3.5m
Epoch 347/500 | Batch 50/202 | Rec 0.000612 | Seg 0.282096 | Elapsed 1.1m | ETA 3.2m
Epoch 347/500 | Batch 60/202 | Rec 0.000601 | Seg 0.281534 | Elapsed 1.3m | ETA 3.0m
Epoch 347/500 | Batch 70/202 | Rec 0.000569 | Seg 0.268890 | Elapsed 1.5m | ETA 2.8m
Epoch 347/500 | Batch 80/202 | Rec 0.000573 | Seg 0.272445 | Elapsed 1.7m | ETA 2.6m
Epoch 347/500 | Batch 90/202 | Rec 0.000574 | Seg 0.275326 | Elapsed 1.9m | ETA 2.4m
Epoch 347/500 | Batch 100/202 | Rec 0.000577 | Seg 0.277671 | Elapsed 2.1m | ETA 2.2m
Epoch 347/500 | Batch 110/202 | Rec 0.000568 | Seg 0.271237 | Elapsed 2.3m | ETA 2.0m
Epoch 347/500 | Batch 120/202 | Rec 0.000578 | Seg 0.272069 | Elapsed 2.5m | ETA 1.7m
Epoch 347/500 | Batch 130/202 | Rec 0.000579 | Seg 0.271476 | Elapsed 2.8m | ETA 1.5m
Epoch 347/500 | Batch 140/202 | Rec 0.000574 | Seg 0.268797 | Elapsed 3.0m | ETA 1.3m
Epoch 347/500 | Batch 150/202 | Rec 0.000586 | Seg 0.272306 | Elapsed 3.2m | ETA 1.1m
Epoch 347/500 | Batch 160/202 | Rec 0.000593 | Seg 0.274244 | Elapsed 3.4m | ETA 0.9m
Epoch 347/500 | Batch 170/202 | Rec 0.000595 | Seg 0.277207 | Elapsed 3.6m | ETA 0.7m
Epoch 347/500 | Batch 180/202 | Rec 0.000600 | Seg 0.281127 | Elapsed 3.8m | ETA 0.5m
Epoch 347/500 | Batch 190/202 | Rec 0.000594 | Seg 0.279742 | Elapsed 4.0m | ETA 0.3m
Epoch 347/500 | Batch 200/202 | Rec 0.000598 | Seg 0.281344 | Elapsed 4.2m | ETA 0.0m
Epoch 347/500 | Batch 202/202 | Rec 0.000599 | Seg 0.281300 | Elapsed 4.3m | ETA 0.0m

2026-09-25 22:01:09,240 - INFO: Rec loss: 0.0005987596089086072
2026-09-25 22:01:09,240 - INFO: Seg loss: 0.281299806873102
2026-09-25 22:01:09,240 - INFO: λ_rec: 1
2026-09-25 22:01:09,240 - INFO: λ_seg: 0.0001
2026-09-25 22:02:30,860 - INFO: -------------------Epoch: 347------------------------
2026-09-25 22:02:30,864 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.670882  0.974315  0.000141
2026-09-25 22:02:30,872 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995723  0.997807  0.997321  0.998393  0.995917
real potato   0.909057  0.952313  0.959012  0.945805  0.999887
fake potato   0.866884  0.928646  0.968395  0.892124  0.999900
real apple    0.826629  0.905037  0.975225  0.844361  0.999389
fake apple    0.600048  0.749991  0.995055  0.601843  0.998485
real orange   0.886738  0.939920  0.994444  0.891153  0.999850
fake orange   0.919453  0.957987  0.938001  0.978947  0.999754
real grape    0.759808  0.863463  0.909032  0.822334  0.999457
fake grape    0.889604  0.941527  0.915129  0.969599  0.999555
real lemon    0.747283  0.855316  0.793035  0.928330  0.999631
fake lemon    0.836273  0.910788  0.997938  0.837721  0.999653
real avocado  0.815273  0.898188  0.842098  0.962397  0.999797
fake avocado  0.400408  0.571804  1.000000  0.400408  0.999283
real pepper   0.810687  0.895397  0.853470  0.941765  0.999196
fake pepper   0.707081  0.828361  0.956423  0.730619  0.999279
real plant    0.872424  0.931816  0.945021  0.919072  0.998656
fake plant    0.670538  0.802732  0.719672  0.907592  0.999645
real banana   0.743166  0.852613  0.904048  0.806804  0.999373
fake banana   0.683474  0.811931  0.757615  0.874751  0.999255
real onion    0.660078  0.795188  0.703969  0.913697  0.999575
fake onion    0.910338  0.953015  0.943799  0.962515  0.999940
real unknown  0.876147  0.933935  0.957874  0.911259  0.999979
fake unknown  0.193761  0.324585  0.217070  0.643426  0.997744
total         0.764386  0.852276  0.880158  0.855866  0.999270
total(-bg)    0.753871  0.845661  0.874833  0.849387  0.999422
2026-09-25 22:02:31,423 - INFO: Epoch accounting: {'epoch': 347, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11404642, 44683, 49015, 101475, 125641, 91760, 84209, 159528, 130610, 51213, 46804, 54891, 38266, 236873, 100090, 140136, 23643, 85992, 80800, 81122, 48817, 11945, 46117], 'crops_with_class': [202, 25, 24, 25, 33, 27, 27, 29, 28, 25, 23, 19, 16, 54, 34, 24, 24, 24, 37, 33, 23, 15, 24], 'targeted_crops_by_class': [0, 7, 4, 8, 2, 2, 3, 8, 4, 4, 3, 7, 1, 5, 5, 5, 5, 4, 6, 2, 1, 9, 2], 'sampled_scene_counts': [1, 0, 3, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 3, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 2, 3, 1, 0, 0, 1, 0, 2, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 3, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 2, 3, 2, 1, 1, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 2, 0, 0, 2, 1, 2, 2, 0, 3, 0, 0, 2, 0, 1, 1, 1, 1, 0, 1, 4, 1, 1, 0, 3, 1, 4, 1, 1, 2, 1, 2, 1, 1, 4, 3, 2, 2, 0, 0, 0, 2, 2, 0, 1, 0, 1, 2, 2, 3, 2, 1, 1, 1, 2, 1, 1, 2, 0, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 4, 1, 1, 1, 3, 2], 'learning_rate': 2.183246116230299e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005987596089086072, 'train_segmentation_loss': 0.281299806873102, 'val_foreground_miou_all22': 0.7538706538531841, 'val_psnr_ref1': 38.67088150024414, 'elapsed_seconds': 337.84131026268005, 'peak_cuda_allocated_gib': 7.506137847900391}

Epoch 348/500 | Batch 10/202 | Rec 0.000532 | Seg 0.259276 | Elapsed 0.2m | ETA 4.0m
Epoch 348/500 | Batch 20/202 | Rec 0.000571 | Seg 0.289799 | Elapsed 0.4m | ETA 3.8m
Epoch 348/500 | Batch 30/202 | Rec 0.000552 | Seg 0.271385 | Elapsed 0.6m | ETA 3.6m
Epoch 348/500 | Batch 40/202 | Rec 0.000539 | Seg 0.269595 | Elapsed 0.8m | ETA 3.4m
Epoch 348/500 | Batch 50/202 | Rec 0.000539 | Seg 0.272430 | Elapsed 1.1m | ETA 3.2m
Epoch 348/500 | Batch 60/202 | Rec 0.000554 | Seg 0.276968 | Elapsed 1.3m | ETA 3.0m
Epoch 348/500 | Batch 70/202 | Rec 0.000564 | Seg 0.274247 | Elapsed 1.5m | ETA 2.8m
Epoch 348/500 | Batch 80/202 | Rec 0.000563 | Seg 0.268172 | Elapsed 1.7m | ETA 2.6m
Epoch 348/500 | Batch 90/202 | Rec 0.000558 | Seg 0.262950 | Elapsed 1.9m | ETA 2.3m
Epoch 348/500 | Batch 100/202 | Rec 0.000578 | Seg 0.275595 | Elapsed 2.1m | ETA 2.1m
Epoch 348/500 | Batch 110/202 | Rec 0.000578 | Seg 0.276520 | Elapsed 2.3m | ETA 1.9m
Epoch 348/500 | Batch 120/202 | Rec 0.000576 | Seg 0.276349 | Elapsed 2.5m | ETA 1.7m
Epoch 348/500 | Batch 130/202 | Rec 0.000574 | Seg 0.274116 | Elapsed 2.7m | ETA 1.5m
Epoch 348/500 | Batch 140/202 | Rec 0.000567 | Seg 0.270230 | Elapsed 2.9m | ETA 1.3m
Epoch 348/500 | Batch 150/202 | Rec 0.000572 | Seg 0.273946 | Elapsed 3.1m | ETA 1.1m
Epoch 348/500 | Batch 160/202 | Rec 0.000584 | Seg 0.276559 | Elapsed 3.4m | ETA 0.9m
Epoch 348/500 | Batch 170/202 | Rec 0.000588 | Seg 0.277716 | Elapsed 3.6m | ETA 0.7m
Epoch 348/500 | Batch 180/202 | Rec 0.000591 | Seg 0.278187 | Elapsed 3.8m | ETA 0.5m
Epoch 348/500 | Batch 190/202 | Rec 0.000601 | Seg 0.284318 | Elapsed 4.0m | ETA 0.3m
Epoch 348/500 | Batch 200/202 | Rec 0.000607 | Seg 0.286349 | Elapsed 4.2m | ETA 0.0m
Epoch 348/500 | Batch 202/202 | Rec 0.000608 | Seg 0.286880 | Elapsed 4.2m | ETA 0.0m

2026-09-25 22:06:46,394 - INFO: Rec loss: 0.0006083949229283498
2026-09-25 22:06:46,394 - INFO: Seg loss: 0.28687964630599067
2026-09-25 22:06:46,394 - INFO: λ_rec: 1
2026-09-25 22:06:46,394 - INFO: λ_seg: 0.0001
2026-09-25 22:08:03,706 - INFO: -------------------Epoch: 348------------------------
2026-09-25 22:08:03,710 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.542923  0.973883  0.000146
2026-09-25 22:08:03,718 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995857  0.997874  0.997369  0.998481  0.996046
real potato   0.931394  0.964429  0.961241  0.967738  0.999915
fake potato   0.933714  0.965671  0.972594  0.958944  0.999950
real apple    0.822593  0.902613  0.983015  0.834454  0.999379
fake apple    0.553945  0.712907  0.993715  0.555892  0.998310
real orange   0.675398  0.806206  0.994901  0.677744  0.999571
fake orange   0.836298  0.910802  0.858592  0.969886  0.999456
real grape    0.811021  0.895601  0.953611  0.844332  0.999589
fake grape    0.903238  0.949109  0.928202  0.971084  0.999615
real lemon    0.703937  0.826198  0.734039  0.944949  0.999533
fake lemon    0.847803  0.917584  0.996786  0.850126  0.999677
real avocado  0.940805  0.969450  0.984264  0.955172  0.999944
fake avocado  0.451613  0.622179  0.999718  0.451670  0.999344
real pepper   0.856955  0.922918  0.874286  0.977390  0.999403
fake pepper   0.765029  0.866824  0.941406  0.803278  0.999412
real plant    0.878169  0.935083  0.954050  0.916951  0.998728
fake plant    0.769781  0.869867  0.817998  0.928873  0.999779
real banana   0.713865  0.832997  0.903134  0.773054  0.999304
fake banana   0.723901  0.839790  0.816579  0.864466  0.999393
real onion    0.663569  0.797717  0.692528  0.940719  0.999569
fake onion    0.947845  0.973174  0.984174  0.962515  0.999967
real unknown  0.809244  0.894516  0.871493  0.918893  0.999965
fake unknown  0.194909  0.326198  0.211522  0.712785  0.997519
total         0.770908  0.856509  0.888053  0.859974  0.999277
total(-bg)    0.760683  0.850083  0.883084  0.853678  0.999424
2026-09-25 22:08:04,283 - INFO: Epoch accounting: {'epoch': 348, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11328411, 52940, 37339, 114961, 127185, 94109, 83756, 104126, 210613, 71814, 65600, 25811, 34055, 225104, 116496, 187325, 24121, 74829, 60218, 80516, 44830, 19615, 54498], 'crops_with_class': [202, 27, 19, 30, 34, 28, 31, 25, 35, 30, 30, 9, 13, 51, 32, 21, 24, 23, 28, 36, 21, 20, 26], 'targeted_crops_by_class': [0, 5, 4, 4, 4, 5, 7, 3, 6, 5, 6, 3, 2, 3, 5, 3, 3, 5, 7, 3, 1, 9, 1], 'sampled_scene_counts': [1, 0, 1, 0, 0, 2, 1, 0, 2, 1, 0, 0, 1, 2, 1, 1, 3, 0, 1, 0, 0, 2, 0, 1, 2, 1, 1, 0, 1, 0, 1, 0, 2, 0, 2, 1, 3, 0, 1, 1, 1, 0, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 3, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 2, 1, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 2, 1, 0, 1, 1, 2, 0, 2, 1, 0, 2, 1, 0, 1, 1, 3, 3, 3, 1, 0, 0, 3, 0, 0, 2, 0, 4, 1, 0, 2, 3, 4, 5, 2, 0, 1, 3, 0, 2, 0, 1, 0, 3, 2, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 2, 4, 1, 2, 2, 1, 2, 1, 1, 1, 3, 1, 2, 5, 0], 'learning_rate': 2.1574947735969734e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006083949229283498, 'train_segmentation_loss': 0.28687964630599067, 'val_foreground_miou_all22': 0.7606829102774003, 'val_psnr_ref1': 38.542922515869144, 'elapsed_seconds': 332.85066652297974, 'peak_cuda_allocated_gib': 7.507511138916016}

Epoch 349/500 | Batch 10/202 | Rec 0.000593 | Seg 0.290209 | Elapsed 0.2m | ETA 4.0m
Epoch 349/500 | Batch 20/202 | Rec 0.000565 | Seg 0.265859 | Elapsed 0.4m | ETA 3.8m
Epoch 349/500 | Batch 30/202 | Rec 0.000522 | Seg 0.257771 | Elapsed 0.6m | ETA 3.6m
Epoch 349/500 | Batch 40/202 | Rec 0.000526 | Seg 0.267386 | Elapsed 0.8m | ETA 3.4m
Epoch 349/500 | Batch 50/202 | Rec 0.000567 | Seg 0.278337 | Elapsed 1.0m | ETA 3.2m
Epoch 349/500 | Batch 60/202 | Rec 0.000582 | Seg 0.275297 | Elapsed 1.2m | ETA 2.9m
Epoch 349/500 | Batch 70/202 | Rec 0.000582 | Seg 0.276865 | Elapsed 1.5m | ETA 2.7m
Epoch 349/500 | Batch 80/202 | Rec 0.000573 | Seg 0.280758 | Elapsed 1.7m | ETA 2.5m
Epoch 349/500 | Batch 90/202 | Rec 0.000580 | Seg 0.287221 | Elapsed 1.9m | ETA 2.3m
Epoch 349/500 | Batch 100/202 | Rec 0.000575 | Seg 0.283669 | Elapsed 2.1m | ETA 2.1m
Epoch 349/500 | Batch 110/202 | Rec 0.000580 | Seg 0.280814 | Elapsed 2.3m | ETA 1.9m
Epoch 349/500 | Batch 120/202 | Rec 0.000581 | Seg 0.279769 | Elapsed 2.5m | ETA 1.7m
Epoch 349/500 | Batch 130/202 | Rec 0.000586 | Seg 0.279444 | Elapsed 2.7m | ETA 1.5m
Epoch 349/500 | Batch 140/202 | Rec 0.000580 | Seg 0.279206 | Elapsed 2.9m | ETA 1.3m
Epoch 349/500 | Batch 150/202 | Rec 0.000573 | Seg 0.274823 | Elapsed 3.1m | ETA 1.1m
Epoch 349/500 | Batch 160/202 | Rec 0.000588 | Seg 0.276196 | Elapsed 3.4m | ETA 0.9m
Epoch 349/500 | Batch 170/202 | Rec 0.000582 | Seg 0.273834 | Elapsed 3.6m | ETA 0.7m
Epoch 349/500 | Batch 180/202 | Rec 0.000580 | Seg 0.272546 | Elapsed 3.8m | ETA 0.5m
Epoch 349/500 | Batch 190/202 | Rec 0.000583 | Seg 0.273435 | Elapsed 4.0m | ETA 0.3m
Epoch 349/500 | Batch 200/202 | Rec 0.000591 | Seg 0.278350 | Elapsed 4.2m | ETA 0.0m
Epoch 349/500 | Batch 202/202 | Rec 0.000591 | Seg 0.278977 | Elapsed 4.2m | ETA 0.0m

2026-09-25 22:12:19,028 - INFO: Rec loss: 0.0005906302795116098
2026-09-25 22:12:19,028 - INFO: Seg loss: 0.27897691221372917
2026-09-25 22:12:19,029 - INFO: λ_rec: 1
2026-09-25 22:12:19,029 - INFO: λ_seg: 0.0001
2026-09-25 22:13:39,001 - INFO: -------------------Epoch: 349------------------------
2026-09-25 22:13:39,005 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.830738  0.974073  0.000137
2026-09-25 22:13:39,013 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995719  0.997805  0.997021  0.998691  0.995913
real potato   0.706980  0.828291  0.993225  0.710405  0.999648
fake potato   0.696015  0.820716  0.959630  0.717009  0.999772
real apple    0.756762  0.861492  0.895231  0.830296  0.999079
fake apple    0.673616  0.804934  0.961968  0.692047  0.998734
real orange   0.867938  0.929251  0.997477  0.869847  0.999826
fake orange   0.911431  0.953613  0.932556  0.975749  0.999729
real grape    0.770775  0.870502  0.971889  0.788351  0.999510
fake grape    0.887544  0.940372  0.922781  0.958751  0.999551
real lemon    0.456664  0.626953  0.513947  0.803817  0.998876
fake lemon    0.855212  0.921906  0.996231  0.857988  0.999693
real avocado  0.875261  0.933432  0.905526  0.963218  0.999872
fake avocado  0.776730  0.874287  0.999180  0.777225  0.999733
real pepper   0.838821  0.912297  0.874785  0.953279  0.999330
fake pepper   0.755332  0.860565  0.967023  0.775302  0.999401
real plant    0.866988  0.928706  0.947414  0.910819  0.998602
fake plant    0.860560  0.925005  0.963263  0.889762  0.999885
real banana   0.484148  0.652379  0.907858  0.509167  0.998781
fake banana   0.668610  0.801348  0.768762  0.836928  0.999237
real onion    0.649878  0.787741  0.675024  0.945786  0.999540
fake onion    0.930977  0.964205  0.979780  0.949214  0.999956
real unknown  0.887466  0.940328  0.955665  0.925572  0.999981
fake unknown  0.259763  0.412360  0.282296  0.764940  0.998163
total         0.757965  0.849934  0.885588  0.843659  0.999253
total(-bg)    0.747158  0.843213  0.880523  0.836612  0.999404
2026-09-25 22:13:39,552 - INFO: Epoch accounting: {'epoch': 349, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11358287, 39400, 52290, 134217, 151265, 92953, 75561, 165152, 208771, 89984, 57306, 46304, 35653, 167471, 93110, 149201, 23011, 64730, 41892, 88431, 53007, 13388, 36888], 'crops_with_class': [202, 22, 26, 36, 40, 29, 26, 35, 39, 38, 27, 14, 16, 44, 28, 24, 25, 25, 22, 34, 23, 14, 20], 'targeted_crops_by_class': [0, 5, 3, 7, 3, 6, 2, 3, 8, 7, 4, 3, 5, 4, 3, 8, 4, 4, 1, 11, 4, 8, 2], 'sampled_scene_counts': [0, 0, 0, 1, 0, 1, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 2, 0, 0, 1, 2, 0, 1, 1, 0, 0, 1, 1, 0, 1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 1, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 3, 1, 0, 1, 0, 0, 2, 1, 2, 1, 0, 1, 0, 1, 0, 1, 0, 2, 0, 2, 1, 1, 2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 4, 3, 4, 1, 1, 2, 0, 1, 2, 0, 0, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 3, 3, 0, 2, 2, 1, 1, 0, 4, 3, 1, 2, 0, 2, 3, 3, 1, 2, 1, 0, 0, 1, 2, 2, 1, 2, 2, 0, 0, 5, 2, 3, 1, 3, 1, 1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 3, 1, 0, 1, 1, 0, 1, 2, 2, 2, 0], 'learning_rate': 2.1318561416814376e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005906302795116098, 'train_segmentation_loss': 0.27897691221372917, 'val_foreground_miou_all22': 0.7471577922714331, 'val_psnr_ref1': 38.83073776245117, 'elapsed_seconds': 335.2613561153412, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 350/500 | Batch 10/202 | Rec 0.000635 | Seg 0.292377 | Elapsed 0.2m | ETA 4.1m
Epoch 350/500 | Batch 20/202 | Rec 0.000759 | Seg 0.325180 | Elapsed 0.4m | ETA 3.9m
Epoch 350/500 | Batch 30/202 | Rec 0.000735 | Seg 0.338802 | Elapsed 0.6m | ETA 3.7m
Epoch 350/500 | Batch 40/202 | Rec 0.000674 | Seg 0.312190 | Elapsed 0.8m | ETA 3.4m
Epoch 350/500 | Batch 50/202 | Rec 0.000657 | Seg 0.300369 | Elapsed 1.1m | ETA 3.2m
Epoch 350/500 | Batch 60/202 | Rec 0.000650 | Seg 0.305642 | Elapsed 1.3m | ETA 3.0m
Epoch 350/500 | Batch 70/202 | Rec 0.000628 | Seg 0.304124 | Elapsed 1.5m | ETA 2.8m
Epoch 350/500 | Batch 80/202 | Rec 0.000625 | Seg 0.303263 | Elapsed 1.7m | ETA 2.6m
Epoch 350/500 | Batch 90/202 | Rec 0.000622 | Seg 0.302100 | Elapsed 1.9m | ETA 2.4m
Epoch 350/500 | Batch 100/202 | Rec 0.000622 | Seg 0.303332 | Elapsed 2.1m | ETA 2.2m
Epoch 350/500 | Batch 110/202 | Rec 0.000619 | Seg 0.298558 | Elapsed 2.3m | ETA 2.0m
Epoch 350/500 | Batch 120/202 | Rec 0.000624 | Seg 0.296573 | Elapsed 2.5m | ETA 1.7m
Epoch 350/500 | Batch 130/202 | Rec 0.000613 | Seg 0.299580 | Elapsed 2.8m | ETA 1.5m
Epoch 350/500 | Batch 140/202 | Rec 0.000614 | Seg 0.298949 | Elapsed 3.0m | ETA 1.3m
Epoch 350/500 | Batch 150/202 | Rec 0.000618 | Seg 0.302044 | Elapsed 3.2m | ETA 1.1m
Epoch 350/500 | Batch 160/202 | Rec 0.000615 | Seg 0.299430 | Elapsed 3.4m | ETA 0.9m
Epoch 350/500 | Batch 170/202 | Rec 0.000613 | Seg 0.297865 | Elapsed 3.6m | ETA 0.7m
Epoch 350/500 | Batch 180/202 | Rec 0.000611 | Seg 0.300304 | Elapsed 3.8m | ETA 0.5m
Epoch 350/500 | Batch 190/202 | Rec 0.000607 | Seg 0.295768 | Elapsed 4.0m | ETA 0.3m
Epoch 350/500 | Batch 200/202 | Rec 0.000608 | Seg 0.296195 | Elapsed 4.2m | ETA 0.0m
Epoch 350/500 | Batch 202/202 | Rec 0.000607 | Seg 0.295803 | Elapsed 4.3m | ETA 0.0m

2026-09-25 22:17:55,399 - INFO: Rec loss: 0.0006074301774860221
2026-09-25 22:17:55,399 - INFO: Seg loss: 0.2958027869462967
2026-09-25 22:17:55,400 - INFO: λ_rec: 1
2026-09-25 22:17:55,400 - INFO: λ_seg: 0.0001
2026-09-25 22:19:16,922 - INFO: -------------------Epoch: 350------------------------
2026-09-25 22:19:16,926 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.757346  0.974435  0.000139
2026-09-25 22:19:16,933 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995771  0.997831  0.997366  0.998396  0.995963
real potato   0.413867  0.585398  0.985809  0.416348  0.999294
fake potato   0.655805  0.792080  0.976958  0.666108  0.999745
real apple    0.689468  0.816145  0.797426  0.835869  0.998701
fake apple    0.636426  0.777776  0.985554  0.642418  0.998614
real orange   0.921095  0.958877  0.997498  0.923228  0.999896
fake orange   0.932188  0.964854  0.952722  0.977401  0.999796
real grape    0.774539  0.872897  0.946923  0.809691  0.999508
fake grape    0.902997  0.948976  0.938706  0.959576  0.999619
real lemon    0.440390  0.611440  0.484968  0.827318  0.998764
fake lemon    0.858730  0.923947  0.992791  0.864118  0.999699
real avocado  0.901667  0.948241  0.929236  0.968144  0.999902
fake avocado  0.574270  0.729524  0.999778  0.574343  0.999491
real pepper   0.800462  0.889124  0.832829  0.953696  0.999130
fake pepper   0.694724  0.819818  0.965799  0.712246  0.999254
real plant    0.873360  0.932350  0.939629  0.925281  0.998658
fake plant    0.841450  0.913849  0.949195  0.881135  0.999868
real banana   0.429605  0.600967  0.868137  0.459595  0.998629
fake banana   0.672683  0.804266  0.765689  0.847047  0.999242
real onion    0.631338  0.773964  0.674229  0.908461  0.999521
fake onion    0.877738  0.934839  0.994546  0.881983  0.999922
real unknown  0.784750  0.879345  0.824020  0.942748  0.999959
fake unknown  0.208794  0.345425  0.221383  0.785947  0.997491
total         0.717918  0.818345  0.870487  0.815700  0.999159
total(-bg)    0.705288  0.810186  0.864719  0.807396  0.999305
2026-09-25 22:19:17,465 - INFO: Epoch accounting: {'epoch': 350, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11274437, 63192, 60862, 109099, 134831, 102496, 84348, 128520, 172069, 66016, 72213, 48828, 31079, 207739, 112841, 126718, 21710, 94954, 101362, 84850, 70241, 11072, 58795], 'crops_with_class': [202, 39, 32, 27, 33, 29, 30, 26, 31, 28, 26, 18, 11, 51, 37, 18, 19, 27, 38, 35, 35, 11, 26], 'targeted_crops_by_class': [0, 7, 3, 5, 3, 4, 6, 5, 2, 3, 4, 6, 2, 3, 6, 2, 2, 3, 5, 5, 9, 2, 8], 'sampled_scene_counts': [0, 1, 2, 1, 1, 1, 1, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 1, 0, 1, 1, 0, 0, 1, 2, 2, 0, 1, 0, 0, 1, 0, 1, 2, 1, 2, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 2, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 3, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 0, 2, 0, 0, 2, 2, 3, 2, 0, 2, 4, 0, 1, 1, 0, 1, 3, 0, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 0, 1, 3, 4, 3, 1, 2, 1, 3, 1, 1, 0, 2, 1, 2, 1, 4, 0, 4, 1, 0, 1, 2, 1, 1, 1, 1, 1, 3, 1, 2, 4, 2, 4, 3, 0, 0, 0, 0, 1, 1, 1, 1, 2], 'learning_rate': 2.106331232652974e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006074301774860221, 'train_segmentation_loss': 0.2958027869462967, 'val_foreground_miou_all22': 0.705288409443648, 'val_psnr_ref1': 38.75734634399414, 'elapsed_seconds': 337.90420174598694, 'peak_cuda_allocated_gib': 7.510776519775391}

Stopped after epoch 350; scheduler horizon remains 500
Saved epoch: 350 | block target: 350 | Missing checkpoint files: []
Download: /kaggle/working/balanced300_to_epoch400_20260925_173543_epoch350.zip

/kaggle/working/balanced300_to_epoch400_20260925_173543_epoch350.zip

Epoch350 completed. Download the full backup before stopping the session.
Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced300_to_epoch400_20260925_173543', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/working/balanced300_to_epoch400_20260925_173543/model/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=400, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-25 22:20:14,706 - INFO: Resuming after epoch 350

Epoch 351/500 | Batch 10/202 | Rec 0.000621 | Seg 0.309572 | Elapsed 0.4m | ETA 8.5m
Epoch 351/500 | Batch 20/202 | Rec 0.000609 | Seg 0.312349 | Elapsed 0.7m | ETA 6.0m
Epoch 351/500 | Batch 30/202 | Rec 0.000646 | Seg 0.307186 | Elapsed 0.9m | ETA 5.0m
Epoch 351/500 | Batch 40/202 | Rec 0.000614 | Seg 0.288856 | Elapsed 1.1m | ETA 4.4m
Epoch 351/500 | Batch 50/202 | Rec 0.000615 | Seg 0.288135 | Elapsed 1.3m | ETA 4.0m
Epoch 351/500 | Batch 60/202 | Rec 0.000630 | Seg 0.293952 | Elapsed 1.5m | ETA 3.6m
Epoch 351/500 | Batch 70/202 | Rec 0.000621 | Seg 0.290538 | Elapsed 1.7m | ETA 3.2m
Epoch 351/500 | Batch 80/202 | Rec 0.000622 | Seg 0.282183 | Elapsed 1.9m | ETA 2.9m
Epoch 351/500 | Batch 90/202 | Rec 0.000629 | Seg 0.278101 | Elapsed 2.1m | ETA 2.7m
Epoch 351/500 | Batch 100/202 | Rec 0.000624 | Seg 0.274659 | Elapsed 2.3m | ETA 2.4m
Epoch 351/500 | Batch 110/202 | Rec 0.000616 | Seg 0.272614 | Elapsed 2.6m | ETA 2.1m
Epoch 351/500 | Batch 120/202 | Rec 0.000622 | Seg 0.276074 | Elapsed 2.8m | ETA 1.9m
Epoch 351/500 | Batch 130/202 | Rec 0.000616 | Seg 0.279481 | Elapsed 3.0m | ETA 1.6m
Epoch 351/500 | Batch 140/202 | Rec 0.000615 | Seg 0.278472 | Elapsed 3.2m | ETA 1.4m
Epoch 351/500 | Batch 150/202 | Rec 0.000626 | Seg 0.282063 | Elapsed 3.4m | ETA 1.2m
Epoch 351/500 | Batch 160/202 | Rec 0.000625 | Seg 0.280408 | Elapsed 3.6m | ETA 0.9m
Epoch 351/500 | Batch 170/202 | Rec 0.000618 | Seg 0.276260 | Elapsed 3.8m | ETA 0.7m
Epoch 351/500 | Batch 180/202 | Rec 0.000616 | Seg 0.277083 | Elapsed 4.0m | ETA 0.5m
Epoch 351/500 | Batch 190/202 | Rec 0.000617 | Seg 0.278773 | Elapsed 4.2m | ETA 0.3m
Epoch 351/500 | Batch 200/202 | Rec 0.000613 | Seg 0.280968 | Elapsed 4.4m | ETA 0.0m
Epoch 351/500 | Batch 202/202 | Rec 0.000612 | Seg 0.280040 | Elapsed 4.5m | ETA 0.0m

2026-09-25 22:24:44,110 - INFO: Rec loss: 0.0006124865522177078
2026-09-25 22:24:44,111 - INFO: Seg loss: 0.2800397989662862
2026-09-25 22:24:44,111 - INFO: λ_rec: 1
2026-09-25 22:24:44,111 - INFO: λ_seg: 0.0001
2026-09-25 22:26:02,150 - INFO: -------------------Epoch: 351------------------------
2026-09-25 22:26:02,156 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.979192  0.974518  0.000132
2026-09-25 22:26:02,163 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995742  0.997817  0.997178  0.998556  0.995935
real potato   0.151747  0.263485  1.000000  0.151747  0.998985
fake potato   0.648473  0.786709  0.997427  0.649560  0.999743
real apple    0.675969  0.806611  0.728115  0.904202  0.998505
fake apple    0.714418  0.833374  0.937475  0.750162  0.998868
real orange   0.957292  0.978130  0.999517  0.957735  0.999944
fake orange   0.961367  0.980253  0.981771  0.978840  0.999887
real grape    0.828893  0.906393  0.964468  0.855003  0.999632
fake grape    0.880123  0.936190  0.916647  0.956689  0.999518
real lemon    0.384078  0.554953  0.394462  0.935861  0.998236
fake lemon    0.863459  0.926677  0.983484  0.876163  0.999707
real avocado  0.725335  0.840755  0.747382  0.960920  0.999662
fake avocado  0.782891  0.878177  0.999674  0.783091  0.999740
real pepper   0.751826  0.858284  0.818864  0.901802  0.998911
fake pepper   0.572158  0.727817  0.994895  0.573843  0.998977
real plant    0.873039  0.932167  0.948799  0.916204  0.998667
fake plant    0.835237  0.910172  0.938684  0.883436  0.999861
real banana   0.118338  0.211611  0.877228  0.120331  0.997986
fake banana   0.700253  0.823655  0.822513  0.824900  0.999350
real onion    0.593680  0.744993  0.726339  0.764736  0.999527
fake onion    0.628985  0.772195  0.998084  0.629746  0.999766
real unknown  0.834878  0.909959  0.876991  0.945611  0.999970
fake unknown  0.279204  0.436491  0.288966  0.892068  0.998060
total         0.685104  0.783342  0.866911  0.791791  0.999106
total(-bg)    0.670984  0.773593  0.860990  0.782393  0.999250
2026-09-25 22:26:02,696 - INFO: Epoch accounting: {'epoch': 351, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11378980, 38440, 45897, 114403, 161612, 32779, 56641, 117250, 192194, 66944, 57840, 52041, 42259, 237854, 122565, 177407, 26496, 86134, 59630, 69254, 43852, 7557, 50243], 'crops_with_class': [202, 21, 22, 32, 36, 14, 23, 26, 34, 28, 28, 16, 18, 57, 28, 21, 27, 26, 27, 29, 21, 8, 22], 'targeted_crops_by_class': [0, 0, 2, 4, 4, 3, 2, 5, 5, 2, 3, 4, 6, 7, 5, 6, 6, 7, 5, 3, 5, 5, 7], 'sampled_scene_counts': [2, 0, 1, 0, 1, 1, 0, 1, 1, 4, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 0, 2, 2, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 2, 1, 0, 1, 2, 2, 1, 3, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 2, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 0, 0, 0, 0, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 2, 2, 0, 1, 1, 1, 2, 1, 1, 2, 0, 0, 1, 1, 1, 0, 3, 0, 2, 2, 1, 0, 0, 1, 1, 1, 2, 3, 1, 1, 1, 3, 0, 1, 0, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1, 3, 3, 1, 3, 3, 2, 2, 0, 2, 0, 1, 2, 1, 2, 3, 0, 2, 0, 2, 1, 1, 1, 2, 0, 3, 2, 1, 1, 0, 2, 1, 1, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 1], 'learning_rate': 2.080921054191287e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006124865522177078, 'train_segmentation_loss': 0.2800397989662862, 'val_foreground_miou_all22': 0.6709838529388897, 'val_psnr_ref1': 38.97919219970703, 'elapsed_seconds': 347.9819965362549, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 352/500 | Batch 10/202 | Rec 0.000693 | Seg 0.313268 | Elapsed 0.2m | ETA 4.0m
Epoch 352/500 | Batch 20/202 | Rec 0.000611 | Seg 0.267907 | Elapsed 0.4m | ETA 3.8m
Epoch 352/500 | Batch 30/202 | Rec 0.000618 | Seg 0.294661 | Elapsed 0.6m | ETA 3.5m
Epoch 352/500 | Batch 40/202 | Rec 0.000611 | Seg 0.301210 | Elapsed 0.8m | ETA 3.3m
Epoch 352/500 | Batch 50/202 | Rec 0.000607 | Seg 0.294511 | Elapsed 1.0m | ETA 3.1m
Epoch 352/500 | Batch 60/202 | Rec 0.000602 | Seg 0.295339 | Elapsed 1.2m | ETA 2.9m
Epoch 352/500 | Batch 70/202 | Rec 0.000598 | Seg 0.297514 | Elapsed 1.4m | ETA 2.7m
Epoch 352/500 | Batch 80/202 | Rec 0.000598 | Seg 0.295462 | Elapsed 1.7m | ETA 2.5m
Epoch 352/500 | Batch 90/202 | Rec 0.000594 | Seg 0.290547 | Elapsed 1.9m | ETA 2.3m
Epoch 352/500 | Batch 100/202 | Rec 0.000587 | Seg 0.288729 | Elapsed 2.1m | ETA 2.1m
Epoch 352/500 | Batch 110/202 | Rec 0.000598 | Seg 0.286667 | Elapsed 2.3m | ETA 1.9m
Epoch 352/500 | Batch 120/202 | Rec 0.000590 | Seg 0.284231 | Elapsed 2.5m | ETA 1.7m
Epoch 352/500 | Batch 130/202 | Rec 0.000587 | Seg 0.280280 | Elapsed 2.7m | ETA 1.5m
Epoch 352/500 | Batch 140/202 | Rec 0.000580 | Seg 0.279974 | Elapsed 2.9m | ETA 1.3m
Epoch 352/500 | Batch 150/202 | Rec 0.000575 | Seg 0.280984 | Elapsed 3.1m | ETA 1.1m
Epoch 352/500 | Batch 160/202 | Rec 0.000589 | Seg 0.284068 | Elapsed 3.3m | ETA 0.9m
Epoch 352/500 | Batch 170/202 | Rec 0.000592 | Seg 0.285805 | Elapsed 3.5m | ETA 0.7m
Epoch 352/500 | Batch 180/202 | Rec 0.000584 | Seg 0.282500 | Elapsed 3.7m | ETA 0.5m
Epoch 352/500 | Batch 190/202 | Rec 0.000586 | Seg 0.284894 | Elapsed 3.9m | ETA 0.2m
Epoch 352/500 | Batch 200/202 | Rec 0.000584 | Seg 0.282999 | Elapsed 4.2m | ETA 0.0m
Epoch 352/500 | Batch 202/202 | Rec 0.000583 | Seg 0.282370 | Elapsed 4.2m | ETA 0.0m

2026-09-25 22:30:14,815 - INFO: Rec loss: 0.0005826080098516529
2026-09-25 22:30:14,816 - INFO: Seg loss: 0.2823700932140398
2026-09-25 22:30:14,816 - INFO: λ_rec: 1
2026-09-25 22:30:14,816 - INFO: λ_seg: 0.0001
2026-09-25 22:31:32,620 - INFO: -------------------Epoch: 352------------------------
2026-09-25 22:31:32,624 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.952658  0.97484  0.000133
2026-09-25 22:31:32,631 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995262  0.997575  0.996293  0.998961  0.995472
real potato   0.585633  0.738627  0.980380  0.592578  0.999498
fake potato   0.726895  0.841803  0.988421  0.733138  0.999799
real apple    0.703244  0.825720  0.854668  0.798762  0.998837
fake apple    0.718946  0.836448  0.993552  0.722317  0.998934
real orange   0.835704  0.910450  0.998205  0.836962  0.999783
fake orange   0.895215  0.944661  0.919564  0.971272  0.999675
real grape    0.803286  0.890864  0.899508  0.882482  0.999549
fake grape    0.893304  0.943595  0.959497  0.928309  0.999590
real lemon    0.675122  0.806008  0.719841  0.915736  0.999482
fake lemon    0.842329  0.914368  0.997359  0.844212  0.999666
real avocado  0.880186  0.936226  0.912420  0.961412  0.999878
fake avocado  0.594364  0.745534  1.000000  0.594364  0.999515
real pepper   0.789813  0.882515  0.831342  0.940514  0.999084
fake pepper   0.664411  0.798325  0.956394  0.685167  0.999175
real plant    0.867855  0.929203  0.967910  0.893565  0.998639
fake plant    0.750801  0.857616  0.862236  0.853144  0.999775
real banana   0.661704  0.796367  0.934028  0.694146  0.999203
fake banana   0.741841  0.851740  0.885942  0.820173  0.999475
real onion    0.663130  0.797399  0.704731  0.918257  0.999579
fake onion    0.918554  0.957498  0.996080  0.921886  0.999948
real unknown  0.591411  0.743205  0.623545  0.919847  0.999898
fake unknown  0.239439  0.386327  0.265639  0.708258  0.998104
total         0.740802  0.840525  0.880328  0.831977  0.999242
total(-bg)    0.729236  0.833386  0.875057  0.824386  0.999413
2026-09-25 22:31:33,182 - INFO: Epoch accounting: {'epoch': 352, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11348483, 65501, 53442, 125770, 151281, 97203, 58734, 152588, 182144, 97594, 44601, 55013, 32378, 178174, 97345, 107581, 20844, 87168, 62398, 98999, 57018, 10132, 53881], 'crops_with_class': [202, 38, 26, 36, 41, 25, 23, 25, 40, 37, 20, 16, 17, 47, 32, 16, 21, 25, 29, 42, 26, 10, 26], 'targeted_crops_by_class': [0, 4, 2, 8, 6, 5, 6, 6, 6, 6, 1, 4, 4, 2, 2, 4, 5, 10, 6, 5, 3, 4, 8], 'sampled_scene_counts': [0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 2, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 2, 2, 0, 3, 0, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 3, 2, 0, 2, 1, 2, 0, 2, 0, 2, 1, 2, 1, 4, 0, 0, 0, 1, 3, 1, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 3, 2, 2, 1, 2, 4, 1, 1, 0, 3, 2, 1, 1, 4, 3, 0, 3, 2, 2, 0, 1, 0, 2, 1, 2, 3, 0, 3, 1, 0, 1, 0, 1, 1, 3, 2, 1, 3, 1, 2, 1, 0, 0, 1, 0, 2, 3, 3, 3, 0, 0, 3, 2, 0, 1, 3, 1], 'learning_rate': 2.0556266094467134e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005826080098516529, 'train_segmentation_loss': 0.2823700932140398, 'val_foreground_miou_all22': 0.7292357734382766, 'val_psnr_ref1': 38.9526579284668, 'elapsed_seconds': 330.4782021045685, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 353/500 | Batch 10/202 | Rec 0.000600 | Seg 0.297474 | Elapsed 0.2m | ETA 4.0m
Epoch 353/500 | Batch 20/202 | Rec 0.000562 | Seg 0.279846 | Elapsed 0.4m | ETA 3.8m
Epoch 353/500 | Batch 30/202 | Rec 0.000519 | Seg 0.261529 | Elapsed 0.6m | ETA 3.7m
Epoch 353/500 | Batch 40/202 | Rec 0.000521 | Seg 0.261443 | Elapsed 0.8m | ETA 3.4m
Epoch 353/500 | Batch 50/202 | Rec 0.000547 | Seg 0.265194 | Elapsed 1.1m | ETA 3.2m
Epoch 353/500 | Batch 60/202 | Rec 0.000530 | Seg 0.261729 | Elapsed 1.3m | ETA 3.0m
Epoch 353/500 | Batch 70/202 | Rec 0.000532 | Seg 0.264350 | Elapsed 1.5m | ETA 2.8m
Epoch 353/500 | Batch 80/202 | Rec 0.000567 | Seg 0.270612 | Elapsed 1.7m | ETA 2.6m
Epoch 353/500 | Batch 90/202 | Rec 0.000576 | Seg 0.276797 | Elapsed 1.9m | ETA 2.4m
Epoch 353/500 | Batch 100/202 | Rec 0.000592 | Seg 0.291482 | Elapsed 2.1m | ETA 2.2m
Epoch 353/500 | Batch 110/202 | Rec 0.000590 | Seg 0.293331 | Elapsed 2.3m | ETA 1.9m
Epoch 353/500 | Batch 120/202 | Rec 0.000599 | Seg 0.296067 | Elapsed 2.5m | ETA 1.7m
Epoch 353/500 | Batch 130/202 | Rec 0.000590 | Seg 0.289703 | Elapsed 2.7m | ETA 1.5m
Epoch 353/500 | Batch 140/202 | Rec 0.000602 | Seg 0.295420 | Elapsed 2.9m | ETA 1.3m
Epoch 353/500 | Batch 150/202 | Rec 0.000607 | Seg 0.297615 | Elapsed 3.1m | ETA 1.1m
Epoch 353/500 | Batch 160/202 | Rec 0.000599 | Seg 0.293187 | Elapsed 3.4m | ETA 0.9m
Epoch 353/500 | Batch 170/202 | Rec 0.000598 | Seg 0.295283 | Elapsed 3.6m | ETA 0.7m
Epoch 353/500 | Batch 180/202 | Rec 0.000606 | Seg 0.297588 | Elapsed 3.8m | ETA 0.5m
Epoch 353/500 | Batch 190/202 | Rec 0.000605 | Seg 0.294958 | Elapsed 4.0m | ETA 0.3m
Epoch 353/500 | Batch 200/202 | Rec 0.000611 | Seg 0.292277 | Elapsed 4.2m | ETA 0.0m
Epoch 353/500 | Batch 202/202 | Rec 0.000612 | Seg 0.292947 | Elapsed 4.2m | ETA 0.0m

2026-09-25 22:35:48,183 - INFO: Rec loss: 0.0006124660605996948
2026-09-25 22:35:48,184 - INFO: Seg loss: 0.2929470466431415
2026-09-25 22:35:48,184 - INFO: λ_rec: 1
2026-09-25 22:35:48,184 - INFO: λ_seg: 0.0001
2026-09-25 22:37:08,584 - INFO: -------------------Epoch: 353------------------------
2026-09-25 22:37:08,588 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.917725  0.974575  0.000134
2026-09-25 22:37:08,596 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995700  0.997796  0.997267  0.998424  0.995896
real potato   0.921393  0.959039  0.946930  0.971563  0.999901
fake potato   0.967112  0.983231  0.981026  0.985547  0.999976
real apple    0.770831  0.870537  0.974314  0.786820  0.999193
fake apple    0.605877  0.754528  0.986939  0.610774  0.998500
real orange   0.958899  0.978969  0.994033  0.964451  0.999946
fake orange   0.950988  0.974828  0.974541  0.975216  0.999856
real grape    0.771746  0.871120  0.946043  0.807279  0.999501
fake grape    0.905408  0.950306  0.942226  0.958627  0.999630
real lemon    0.787335  0.880966  0.902615  0.860426  0.999727
fake lemon    0.752416  0.858669  0.999904  0.752470  0.999476
real avocado  0.961105  0.980117  0.995093  0.965681  0.999964
fake avocado  0.647374  0.785899  0.999606  0.647539  0.999578
real pepper   0.824472  0.903743  0.844334  0.972259  0.999243
fake pepper   0.719593  0.836885  0.952307  0.746495  0.999307
real plant    0.865244  0.927704  0.948175  0.908195  0.998585
fake plant    0.829426  0.906711  0.861956  0.956480  0.999843
real banana   0.815985  0.898619  0.887337  0.910295  0.999539
fake banana   0.638353  0.779212  0.713076  0.858991  0.999105
real onion    0.597670  0.748130  0.608751  0.970444  0.999410
fake onion    0.944484  0.971399  0.980300  0.962757  0.999964
real unknown  0.590442  0.742440  0.617331  0.931298  0.999897
fake unknown  0.223237  0.364955  0.247454  0.695219  0.997962
total         0.784569  0.866339  0.882676  0.878141  0.999304
total(-bg)    0.774972  0.860364  0.877468  0.872674  0.999459
2026-09-25 22:37:09,139 - INFO: Epoch accounting: {'epoch': 353, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11260657, 44269, 53204, 129405, 152060, 71062, 66478, 138166, 222174, 68917, 80626, 44592, 46688, 234087, 103313, 147435, 25355, 66168, 78428, 98905, 47985, 11594, 46704], 'crops_with_class': [202, 28, 21, 33, 36, 23, 23, 25, 41, 33, 30, 15, 18, 55, 26, 19, 26, 26, 34, 35, 23, 12, 22], 'targeted_crops_by_class': [0, 3, 6, 5, 4, 5, 2, 7, 7, 6, 5, 2, 4, 5, 3, 1, 4, 3, 4, 1, 3, 6, 3], 'sampled_scene_counts': [0, 0, 2, 1, 3, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 3, 1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 2, 2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 2, 0, 2, 0, 1, 3, 2, 1, 0, 0, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 4, 0, 1, 1, 2, 0, 2, 2, 1, 2, 2, 0, 2, 3, 0, 1, 2, 1, 0, 1, 2, 2, 3, 0, 1, 0, 1, 4, 0, 2, 1, 2, 3, 1, 1, 4, 3, 1, 3, 0, 1, 2, 1, 1, 2, 0, 1, 3, 1, 3, 0, 3, 1, 0, 3, 1, 0, 2, 0, 2, 1, 1, 1, 0, 1, 5, 1, 1, 1, 1, 0, 0, 2, 0, 1, 2, 2, 1, 0], 'learning_rate': 2.030448897000623e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006124660605996948, 'train_segmentation_loss': 0.2929470466431415, 'val_foreground_miou_all22': 0.7749722034262768, 'val_psnr_ref1': 38.91772476196289, 'elapsed_seconds': 335.94824028015137, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 354/500 | Batch 10/202 | Rec 0.000702 | Seg 0.297735 | Elapsed 0.2m | ETA 3.9m
Epoch 354/500 | Batch 20/202 | Rec 0.000680 | Seg 0.273276 | Elapsed 0.4m | ETA 3.8m
Epoch 354/500 | Batch 30/202 | Rec 0.000611 | Seg 0.269841 | Elapsed 0.6m | ETA 3.6m
Epoch 354/500 | Batch 40/202 | Rec 0.000647 | Seg 0.292320 | Elapsed 0.8m | ETA 3.4m
Epoch 354/500 | Batch 50/202 | Rec 0.000652 | Seg 0.293086 | Elapsed 1.0m | ETA 3.2m
Epoch 354/500 | Batch 60/202 | Rec 0.000626 | Seg 0.287104 | Elapsed 1.2m | ETA 3.0m
Epoch 354/500 | Batch 70/202 | Rec 0.000607 | Seg 0.284318 | Elapsed 1.5m | ETA 2.7m
Epoch 354/500 | Batch 80/202 | Rec 0.000609 | Seg 0.284602 | Elapsed 1.7m | ETA 2.5m
Epoch 354/500 | Batch 90/202 | Rec 0.000591 | Seg 0.282793 | Elapsed 1.9m | ETA 2.3m
Epoch 354/500 | Batch 100/202 | Rec 0.000588 | Seg 0.277304 | Elapsed 2.1m | ETA 2.1m
Epoch 354/500 | Batch 110/202 | Rec 0.000594 | Seg 0.279796 | Elapsed 2.3m | ETA 1.9m
Epoch 354/500 | Batch 120/202 | Rec 0.000591 | Seg 0.280364 | Elapsed 2.5m | ETA 1.7m
Epoch 354/500 | Batch 130/202 | Rec 0.000581 | Seg 0.275859 | Elapsed 2.7m | ETA 1.5m
Epoch 354/500 | Batch 140/202 | Rec 0.000575 | Seg 0.273886 | Elapsed 2.9m | ETA 1.3m
Epoch 354/500 | Batch 150/202 | Rec 0.000582 | Seg 0.275884 | Elapsed 3.1m | ETA 1.1m
Epoch 354/500 | Batch 160/202 | Rec 0.000594 | Seg 0.275444 | Elapsed 3.3m | ETA 0.9m
Epoch 354/500 | Batch 170/202 | Rec 0.000589 | Seg 0.273714 | Elapsed 3.6m | ETA 0.7m
Epoch 354/500 | Batch 180/202 | Rec 0.000590 | Seg 0.278259 | Elapsed 3.8m | ETA 0.5m
Epoch 354/500 | Batch 190/202 | Rec 0.000589 | Seg 0.277692 | Elapsed 4.0m | ETA 0.3m
Epoch 354/500 | Batch 200/202 | Rec 0.000592 | Seg 0.281038 | Elapsed 4.2m | ETA 0.0m
Epoch 354/500 | Batch 202/202 | Rec 0.000593 | Seg 0.281908 | Elapsed 4.2m | ETA 0.0m

2026-09-25 22:41:22,344 - INFO: Rec loss: 0.0005931072450723582
2026-09-25 22:41:22,344 - INFO: Seg loss: 0.28190808003712997
2026-09-25 22:41:22,344 - INFO: λ_rec: 1
2026-09-25 22:41:22,344 - INFO: λ_seg: 0.0001
2026-09-25 22:42:48,182 - INFO: -------------------Epoch: 354------------------------
2026-09-25 22:42:48,186 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.994669  0.974599  0.000132
2026-09-25 22:42:48,194 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995672  0.997781  0.997003  0.998660  0.995867
real potato   0.388549  0.559607  1.000000  0.388549  0.999268
fake potato   0.676059  0.806677  0.994779  0.678467  0.999763
real apple    0.708629  0.829421  0.779294  0.886555  0.998742
fake apple    0.635640  0.777189  0.968978  0.648844  0.998596
real orange   0.915211  0.955679  0.991536  0.922418  0.999887
fake orange   0.933268  0.965432  0.961958  0.969033  0.999802
real grape    0.858466  0.923794  0.955632  0.894102  0.999692
fake grape    0.863198  0.926527  0.885319  0.971868  0.999430
real lemon    0.400388  0.571781  0.416592  0.911452  0.998396
fake lemon    0.855538  0.922096  0.990802  0.862387  0.999692
real avocado  0.677378  0.807614  0.697694  0.958785  0.999576
fake avocado  0.710134  0.830452  0.999462  0.710405  0.999653
real pepper   0.803049  0.890718  0.896108  0.885491  0.999206
fake pepper   0.611664  0.758999  0.947500  0.633122  0.999042
real plant    0.873350  0.932344  0.939272  0.925616  0.998657
fake plant    0.708452  0.829300  0.765574  0.904716  0.999704
real banana   0.212789  0.350878  0.951351  0.215130  0.998212
fake banana   0.701609  0.824592  0.824882  0.824403  0.999355
real onion    0.605793  0.754460  0.733227  0.777065  0.999543
fake onion    0.906753  0.951047  0.993156  0.912455  0.999941
real unknown  0.812392  0.896436  0.892249  0.900763  0.999967
fake unknown  0.249863  0.399785  0.273570  0.742485  0.998122
total         0.700167  0.802722  0.863302  0.805338  0.999135
total(-bg)    0.686735  0.793856  0.857224  0.796550  0.999284
2026-09-25 22:42:48,766 - INFO: Epoch accounting: {'epoch': 354, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11342136, 51777, 54462, 123829, 151612, 80971, 76613, 140869, 163617, 92214, 61725, 53275, 52154, 208476, 120970, 124928, 25720, 67678, 64461, 74436, 54314, 9496, 42539], 'crops_with_class': [202, 28, 27, 33, 42, 24, 29, 26, 33, 37, 25, 20, 19, 50, 29, 19, 23, 17, 30, 29, 25, 9, 20], 'targeted_crops_by_class': [0, 3, 4, 4, 6, 3, 5, 3, 4, 7, 1, 4, 7, 6, 6, 2, 2, 4, 6, 8, 2, 4, 4], 'sampled_scene_counts': [1, 1, 0, 0, 1, 0, 3, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 2, 2, 0, 2, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 3, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0, 1, 1, 1, 3, 1, 2, 0, 1, 1, 1, 1, 2, 1, 2, 2, 1, 3, 3, 1, 2, 1, 0, 4, 2, 1, 1, 1, 0, 1, 1, 3, 0, 1, 2, 2, 2, 0, 1, 2, 2, 1, 1, 3, 2, 2, 2, 1, 0, 1, 1, 1, 3, 1, 4, 1, 1, 0, 0, 0, 2, 1, 1, 2, 1, 3, 1, 3, 0, 0, 1, 1, 1, 3, 1, 1, 2, 1, 0, 1, 1, 1, 2, 1, 1, 1], 'learning_rate': 2.0053889108259855e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005931072450723582, 'train_segmentation_loss': 0.28190808003712997, 'val_foreground_miou_all22': 0.6867352516948316, 'val_psnr_ref1': 38.994669342041014, 'elapsed_seconds': 339.61924743652344, 'peak_cuda_allocated_gib': 7.509555816650391}

Epoch 355/500 | Batch 10/202 | Rec 0.000679 | Seg 0.365114 | Elapsed 0.2m | ETA 3.9m
Epoch 355/500 | Batch 20/202 | Rec 0.000592 | Seg 0.289371 | Elapsed 0.4m | ETA 3.8m
Epoch 355/500 | Batch 30/202 | Rec 0.000566 | Seg 0.280236 | Elapsed 0.6m | ETA 3.6m
Epoch 355/500 | Batch 40/202 | Rec 0.000584 | Seg 0.291630 | Elapsed 0.8m | ETA 3.4m
Epoch 355/500 | Batch 50/202 | Rec 0.000588 | Seg 0.297541 | Elapsed 1.0m | ETA 3.1m
Epoch 355/500 | Batch 60/202 | Rec 0.000605 | Seg 0.308863 | Elapsed 1.2m | ETA 2.9m
Epoch 355/500 | Batch 70/202 | Rec 0.000599 | Seg 0.309601 | Elapsed 1.4m | ETA 2.7m
Epoch 355/500 | Batch 80/202 | Rec 0.000599 | Seg 0.309440 | Elapsed 1.6m | ETA 2.5m
Epoch 355/500 | Batch 90/202 | Rec 0.000604 | Seg 0.307120 | Elapsed 1.8m | ETA 2.3m
Epoch 355/500 | Batch 100/202 | Rec 0.000608 | Seg 0.305557 | Elapsed 2.1m | ETA 2.1m
Epoch 355/500 | Batch 110/202 | Rec 0.000606 | Seg 0.304251 | Elapsed 2.3m | ETA 1.9m
Epoch 355/500 | Batch 120/202 | Rec 0.000614 | Seg 0.305821 | Elapsed 2.5m | ETA 1.7m
Epoch 355/500 | Batch 130/202 | Rec 0.000610 | Seg 0.306281 | Elapsed 2.7m | ETA 1.5m
Epoch 355/500 | Batch 140/202 | Rec 0.000612 | Seg 0.302605 | Elapsed 2.9m | ETA 1.3m
Epoch 355/500 | Batch 150/202 | Rec 0.000607 | Seg 0.300749 | Elapsed 3.1m | ETA 1.1m
Epoch 355/500 | Batch 160/202 | Rec 0.000610 | Seg 0.299704 | Elapsed 3.3m | ETA 0.9m
Epoch 355/500 | Batch 170/202 | Rec 0.000602 | Seg 0.295861 | Elapsed 3.5m | ETA 0.7m
Epoch 355/500 | Batch 180/202 | Rec 0.000600 | Seg 0.295704 | Elapsed 3.7m | ETA 0.5m
Epoch 355/500 | Batch 190/202 | Rec 0.000604 | Seg 0.299822 | Elapsed 3.9m | ETA 0.2m
Epoch 355/500 | Batch 200/202 | Rec 0.000609 | Seg 0.303572 | Elapsed 4.1m | ETA 0.0m
Epoch 355/500 | Batch 202/202 | Rec 0.000614 | Seg 0.303639 | Elapsed 4.2m | ETA 0.0m

2026-09-25 22:46:59,947 - INFO: Rec loss: 0.000613794431244807
2026-09-25 22:46:59,947 - INFO: Seg loss: 0.30363910567789976
2026-09-25 22:46:59,947 - INFO: λ_rec: 1
2026-09-25 22:46:59,947 - INFO: λ_seg: 0.0001
2026-09-25 22:48:20,089 - INFO: -------------------Epoch: 355------------------------
2026-09-25 22:48:20,096 - INFO:
Validation stats:
      PSNR      SSIM       MSE
0  38.6197  0.974233  0.000143
2026-09-25 22:48:20,110 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995884  0.997888  0.997480  0.998396  0.996072
real potato   0.897018  0.945664  0.912106  0.981892  0.999865
fake potato   0.953282  0.976032  0.961023  0.991621  0.999965
real apple    0.697500  0.821748  0.978495  0.708359  0.998940
fake apple    0.588859  0.741188  0.977819  0.596832  0.998427
real orange   0.854191  0.921313  0.996498  0.856762  0.999807
fake orange   0.917395  0.956868  0.926227  0.989713  0.999745
real grape    0.735047  0.847244  0.908285  0.793978  0.999402
fake grape    0.894874  0.944471  0.913353  0.977891  0.999575
real lemon    0.726499  0.841536  0.864576  0.819787  0.999637
fake lemon    0.819079  0.900493  0.998770  0.819906  0.999617
real avocado  0.913550  0.954772  0.998924  0.914450  0.999920
fake avocado  0.663564  0.797714  0.999616  0.663734  0.999597
real pepper   0.877354  0.934621  0.893855  0.979393  0.999499
fake pepper   0.848595  0.918047  0.936306  0.900583  0.999617
real plant    0.867274  0.928870  0.946174  0.912283  0.998604
fake plant    0.759796  0.863455  0.817901  0.914494  0.999770
real banana   0.790701  0.883069  0.908451  0.859161  0.999489
fake banana   0.672150  0.803885  0.751515  0.864217  0.999225
real onion    0.545704  0.706045  0.553774  0.973991  0.999267
fake onion    0.896366  0.945301  0.925214  0.966384  0.999930
real unknown  0.586747  0.739512  0.614124  0.929389  0.999895
fake unknown  0.238212  0.384728  0.264662  0.704455  0.998102
total         0.771289  0.858890  0.871528  0.874681  0.999303
total(-bg)    0.761080  0.852572  0.865803  0.869058  0.999450
2026-09-25 22:48:20,675 - INFO: Epoch accounting: {'epoch': 355, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11212552, 66076, 73890, 127967, 140145, 68621, 75069, 103587, 196410, 85306, 73329, 33994, 31336, 212928, 116222, 143757, 29807, 112049, 97365, 127532, 56573, 5465, 48292], 'crops_with_class': [202, 36, 33, 35, 36, 21, 26, 21, 35, 37, 26, 12, 13, 51, 34, 24, 24, 35, 36, 48, 25, 6, 21], 'targeted_crops_by_class': [0, 6, 7, 5, 4, 3, 4, 3, 6, 5, 6, 5, 5, 5, 4, 10, 1, 8, 3, 8, 6, 2, 5], 'sampled_scene_counts': [0, 1, 0, 1, 0, 1, 0, 1, 3, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 2, 2, 0, 2, 2, 1, 0, 0, 0, 1, 2, 2, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 2, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 3, 2, 0, 1, 1, 1, 1, 3, 0, 3, 0, 2, 0, 0, 0, 2, 1, 1, 4, 2, 3, 1, 0, 1, 2, 1, 2, 1, 1, 3, 0, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 0, 1, 2, 1, 0, 3, 2, 2, 3, 1, 0, 2, 3, 3, 1, 2, 2, 1, 1, 3, 0, 4, 1, 2, 2, 1, 3, 2, 1, 0, 1, 1, 4, 0, 2, 0, 4, 3, 2, 1, 1, 1, 1, 1, 4, 1], 'learning_rate': 1.980447640248152e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000613794431244807, 'train_segmentation_loss': 0.30363910567789976, 'val_foreground_miou_all22': 0.7610798794493079, 'val_psnr_ref1': 38.6197004699707, 'elapsed_seconds': 331.9002537727356, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 356/500 | Batch 10/202 | Rec 0.000605 | Seg 0.231986 | Elapsed 0.2m | ETA 4.2m
Epoch 356/500 | Batch 20/202 | Rec 0.000625 | Seg 0.271995 | Elapsed 0.4m | ETA 3.8m
Epoch 356/500 | Batch 30/202 | Rec 0.000611 | Seg 0.252861 | Elapsed 0.6m | ETA 3.6m
Epoch 356/500 | Batch 40/202 | Rec 0.000609 | Seg 0.257553 | Elapsed 0.8m | ETA 3.4m
Epoch 356/500 | Batch 50/202 | Rec 0.000616 | Seg 0.260379 | Elapsed 1.1m | ETA 3.2m
Epoch 356/500 | Batch 60/202 | Rec 0.000583 | Seg 0.259796 | Elapsed 1.3m | ETA 3.0m
Epoch 356/500 | Batch 70/202 | Rec 0.000577 | Seg 0.258871 | Elapsed 1.5m | ETA 2.8m
Epoch 356/500 | Batch 80/202 | Rec 0.000576 | Seg 0.258066 | Elapsed 1.7m | ETA 2.6m
Epoch 356/500 | Batch 90/202 | Rec 0.000573 | Seg 0.260891 | Elapsed 1.9m | ETA 2.4m
Epoch 356/500 | Batch 100/202 | Rec 0.000567 | Seg 0.261864 | Elapsed 2.1m | ETA 2.2m
Epoch 356/500 | Batch 110/202 | Rec 0.000583 | Seg 0.268937 | Elapsed 2.3m | ETA 1.9m
Epoch 356/500 | Batch 120/202 | Rec 0.000587 | Seg 0.271560 | Elapsed 2.5m | ETA 1.7m
Epoch 356/500 | Batch 130/202 | Rec 0.000578 | Seg 0.270387 | Elapsed 2.7m | ETA 1.5m
Epoch 356/500 | Batch 140/202 | Rec 0.000580 | Seg 0.269499 | Elapsed 2.9m | ETA 1.3m
Epoch 356/500 | Batch 150/202 | Rec 0.000576 | Seg 0.269798 | Elapsed 3.2m | ETA 1.1m
Epoch 356/500 | Batch 160/202 | Rec 0.000585 | Seg 0.268189 | Elapsed 3.4m | ETA 0.9m
Epoch 356/500 | Batch 170/202 | Rec 0.000592 | Seg 0.269360 | Elapsed 3.6m | ETA 0.7m
Epoch 356/500 | Batch 180/202 | Rec 0.000595 | Seg 0.271089 | Elapsed 3.8m | ETA 0.5m
Epoch 356/500 | Batch 190/202 | Rec 0.000592 | Seg 0.269209 | Elapsed 4.0m | ETA 0.3m
Epoch 356/500 | Batch 200/202 | Rec 0.000589 | Seg 0.272497 | Elapsed 4.2m | ETA 0.0m
Epoch 356/500 | Batch 202/202 | Rec 0.000592 | Seg 0.273293 | Elapsed 4.3m | ETA 0.0m

2026-09-25 22:52:35,788 - INFO: Rec loss: 0.0005915849118771281
2026-09-25 22:52:35,788 - INFO: Seg loss: 0.2732925822976792
2026-09-25 22:52:35,788 - INFO: λ_rec: 1
2026-09-25 22:52:35,788 - INFO: λ_seg: 0.0001
2026-09-25 22:54:00,159 - INFO: -------------------Epoch: 356------------------------
2026-09-25 22:54:00,165 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.899798  0.974614  0.000134
2026-09-25 22:54:00,176 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995710  0.997800  0.996911  0.998791  0.995903
real potato   0.650454  0.788164  0.982116  0.658250  0.999577
fake potato   0.654833  0.791370  0.969909  0.668412  0.999743
real apple    0.730322  0.844096  0.875921  0.814595  0.998962
fake apple    0.650303  0.788053  0.968481  0.664363  0.998651
real orange   0.904040  0.949552  0.999616  0.904354  0.999874
fake orange   0.920364  0.958481  0.951905  0.965249  0.999761
real grape    0.762242  0.865033  0.972103  0.779288  0.999492
fake grape    0.887447  0.940318  0.941456  0.939281  0.999559
real lemon    0.436275  0.607460  0.515475  0.739548  0.998877
fake lemon    0.842272  0.914334  0.996174  0.845005  0.999665
real avocado  0.870126  0.930503  0.899601  0.963711  0.999866
fake avocado  0.580390  0.734443  0.999780  0.580464  0.999498
real pepper   0.851931  0.919996  0.895572  0.945895  0.999399
fake pepper   0.802266  0.890236  0.966557  0.825171  0.999515
real plant    0.865677  0.927953  0.937952  0.918263  0.998575
fake plant    0.871673  0.931387  0.946556  0.916794  0.999893
real banana   0.509740  0.675222  0.920929  0.533071  0.998848
fake banana   0.659316  0.794634  0.776836  0.813371  0.999227
real onion    0.661417  0.796160  0.692567  0.936328  0.999567
fake onion    0.906489  0.950901  0.985222  0.918984  0.999940
real unknown  0.834324  0.909630  0.883888  0.937023  0.999970
fake unknown  0.211268  0.348803  0.226869  0.754437  0.997627
total         0.741690  0.837153  0.882713  0.826985  0.999217
total(-bg)    0.730144  0.829851  0.877522  0.819175  0.999368
2026-09-25 22:54:00,745 - INFO: Epoch accounting: {'epoch': 356, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11398813, 51061, 69590, 98271, 120359, 76986, 48626, 132978, 124805, 46664, 43758, 42908, 23862, 244029, 165760, 108481, 31224, 85153, 80204, 99062, 60761, 15402, 69515], 'crops_with_class': [202, 35, 32, 31, 32, 24, 20, 29, 25, 23, 18, 16, 11, 64, 37, 20, 30, 25, 36, 40, 28, 17, 35], 'targeted_crops_by_class': [0, 4, 3, 3, 5, 4, 2, 4, 1, 5, 3, 6, 1, 4, 6, 2, 3, 6, 5, 7, 2, 8, 13], 'sampled_scene_counts': [0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 0, 1, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 5, 1, 1, 1, 1, 1, 5, 1, 4, 0, 2, 4, 3, 0, 2, 2, 3, 3, 4, 3, 3, 3, 4, 1, 2, 1, 1, 5, 3, 1, 2, 3, 2, 1, 0, 1, 2, 1, 1, 1, 2, 1, 2, 2, 0, 4, 1, 1, 3, 1, 1, 0, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2], 'learning_rate': 1.9556260699057777e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005915849118771281, 'train_segmentation_loss': 0.2732925822976792, 'val_foreground_miou_all22': 0.7301439888131669, 'val_psnr_ref1': 38.899798278808596, 'elapsed_seconds': 340.060898065567, 'peak_cuda_allocated_gib': 7.512271881103516}

Epoch 357/500 | Batch 10/202 | Rec 0.000546 | Seg 0.241336 | Elapsed 0.2m | ETA 3.9m
Epoch 357/500 | Batch 20/202 | Rec 0.000596 | Seg 0.253614 | Elapsed 0.4m | ETA 3.9m
Epoch 357/500 | Batch 30/202 | Rec 0.000588 | Seg 0.269408 | Elapsed 0.6m | ETA 3.6m
Epoch 357/500 | Batch 40/202 | Rec 0.000588 | Seg 0.272792 | Elapsed 0.8m | ETA 3.4m
Epoch 357/500 | Batch 50/202 | Rec 0.000604 | Seg 0.279932 | Elapsed 1.1m | ETA 3.2m
Epoch 357/500 | Batch 60/202 | Rec 0.000624 | Seg 0.279392 | Elapsed 1.3m | ETA 3.0m
Epoch 357/500 | Batch 70/202 | Rec 0.000625 | Seg 0.287083 | Elapsed 1.5m | ETA 2.8m
Epoch 357/500 | Batch 80/202 | Rec 0.000616 | Seg 0.282349 | Elapsed 1.7m | ETA 2.6m
Epoch 357/500 | Batch 90/202 | Rec 0.000628 | Seg 0.293732 | Elapsed 1.9m | ETA 2.3m
Epoch 357/500 | Batch 100/202 | Rec 0.000631 | Seg 0.301817 | Elapsed 2.1m | ETA 2.1m
Epoch 357/500 | Batch 110/202 | Rec 0.000615 | Seg 0.297539 | Elapsed 2.3m | ETA 1.9m
Epoch 357/500 | Batch 120/202 | Rec 0.000618 | Seg 0.294534 | Elapsed 2.5m | ETA 1.7m
Epoch 357/500 | Batch 130/202 | Rec 0.000610 | Seg 0.294935 | Elapsed 2.7m | ETA 1.5m
Epoch 357/500 | Batch 140/202 | Rec 0.000613 | Seg 0.294618 | Elapsed 2.9m | ETA 1.3m
Epoch 357/500 | Batch 150/202 | Rec 0.000621 | Seg 0.295732 | Elapsed 3.1m | ETA 1.1m
Epoch 357/500 | Batch 160/202 | Rec 0.000617 | Seg 0.290506 | Elapsed 3.4m | ETA 0.9m
Epoch 357/500 | Batch 170/202 | Rec 0.000614 | Seg 0.290064 | Elapsed 3.6m | ETA 0.7m
Epoch 357/500 | Batch 180/202 | Rec 0.000615 | Seg 0.288381 | Elapsed 3.8m | ETA 0.5m
Epoch 357/500 | Batch 190/202 | Rec 0.000613 | Seg 0.286276 | Elapsed 4.0m | ETA 0.3m
Epoch 357/500 | Batch 200/202 | Rec 0.000612 | Seg 0.285143 | Elapsed 4.2m | ETA 0.0m
Epoch 357/500 | Batch 202/202 | Rec 0.000615 | Seg 0.286109 | Elapsed 4.3m | ETA 0.0m

2026-09-25 22:58:16,096 - INFO: Rec loss: 0.0006152807513314142
2026-09-25 22:58:16,096 - INFO: Seg loss: 0.2861086796729429
2026-09-25 22:58:16,096 - INFO: λ_rec: 1
2026-09-25 22:58:16,096 - INFO: λ_seg: 0.0001
2026-09-25 22:59:36,620 - INFO: -------------------Epoch: 357------------------------
2026-09-25 22:59:36,625 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.760006  0.974547  0.000138
2026-09-25 22:59:36,632 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995370  0.997629  0.996715  0.998646  0.995577
real potato   0.844705  0.915766  0.856810  0.983550  0.999784
fake potato   0.949698  0.974150  0.960130  0.988689  0.999962
real apple    0.628600  0.771903  0.961363  0.644892  0.998685
fake apple    0.538492  0.699980  0.991263  0.541060  0.998249
real orange   0.932732  0.965146  0.998021  0.934460  0.999911
fake orange   0.944058  0.971174  0.972834  0.969619  0.999836
real grape    0.660386  0.795412  0.888899  0.719798  0.999227
fake grape    0.914276  0.955168  0.944586  0.966093  0.999665
real lemon    0.716142  0.834546  0.917380  0.765515  0.999643
fake lemon    0.693423  0.818912  0.999896  0.693473  0.999351
real avocado  0.907614  0.951520  0.999277  0.908210  0.999914
fake avocado  0.434200  0.605453  1.000000  0.434200  0.999323
real pepper   0.820813  0.901540  0.840216  0.972635  0.999223
fake pepper   0.724072  0.839907  0.945236  0.755777  0.999314
real plant    0.840888  0.913518  0.949261  0.880461  0.998334
fake plant    0.792116  0.883951  0.831307  0.943827  0.999803
real banana   0.796064  0.886404  0.908773  0.865204  0.999502
fake banana   0.573535  0.728928  0.630115  0.864632  0.998817
real onion    0.528561  0.691534  0.535771  0.975173  0.999214
fake onion    0.926118  0.961592  0.971612  0.951874  0.999952
real unknown  0.489827  0.657516  0.511962  0.918893  0.999847
fake unknown  0.178108  0.302327  0.197545  0.644151  0.997495
total         0.731730  0.827129  0.861260  0.840036  0.999158
total(-bg)    0.719747  0.819379  0.855103  0.832827  0.999321
2026-09-25 22:59:37,218 - INFO: Epoch accounting: {'epoch': 357, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11318438, 56098, 72888, 106865, 139375, 70688, 84829, 110386, 173561, 74324, 67343, 38675, 44314, 225236, 137370, 167494, 36949, 89861, 50782, 70546, 48514, 10464, 43272], 'crops_with_class': [202, 35, 32, 26, 37, 21, 27, 24, 34, 40, 28, 14, 18, 54, 38, 22, 33, 23, 22, 36, 23, 11, 19], 'targeted_crops_by_class': [0, 4, 5, 4, 7, 4, 1, 5, 6, 4, 3, 3, 5, 2, 6, 8, 3, 4, 2, 7, 4, 5, 5], 'sampled_scene_counts': [2, 1, 0, 0, 1, 0, 2, 0, 2, 2, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 3, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 0, 2, 1, 0, 2, 1, 3, 5, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 2, 1, 0, 1, 0, 1, 1, 4, 0, 2, 1, 2, 0, 1, 1, 2, 4, 1, 1, 1, 4, 0, 0, 1, 2, 0, 3, 2, 4, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 0, 2, 1, 1, 3, 3, 1, 3, 0, 2, 2, 1, 1, 1, 4, 1, 3, 4, 0, 0, 0, 0, 1, 3, 0, 1, 1, 0], 'learning_rate': 1.9309251797119533e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006152807513314142, 'train_segmentation_loss': 0.2861086796729429, 'val_foreground_miou_all22': 0.71974673097573, 'val_psnr_ref1': 38.76000579833985, 'elapsed_seconds': 336.46452927589417, 'peak_cuda_allocated_gib': 7.512271881103516}

Epoch 358/500 | Batch 10/202 | Rec 0.000911 | Seg 0.248581 | Elapsed 0.2m | ETA 4.1m
Epoch 358/500 | Batch 20/202 | Rec 0.000719 | Seg 0.252955 | Elapsed 0.4m | ETA 3.9m
Epoch 358/500 | Batch 30/202 | Rec 0.000689 | Seg 0.275735 | Elapsed 0.6m | ETA 3.7m
Epoch 358/500 | Batch 40/202 | Rec 0.000672 | Seg 0.292573 | Elapsed 0.8m | ETA 3.4m
Epoch 358/500 | Batch 50/202 | Rec 0.000653 | Seg 0.287811 | Elapsed 1.1m | ETA 3.2m
Epoch 358/500 | Batch 60/202 | Rec 0.000628 | Seg 0.288009 | Elapsed 1.3m | ETA 3.0m
Epoch 358/500 | Batch 70/202 | Rec 0.000621 | Seg 0.285539 | Elapsed 1.5m | ETA 2.8m
Epoch 358/500 | Batch 80/202 | Rec 0.000610 | Seg 0.282399 | Elapsed 1.7m | ETA 2.6m
Epoch 358/500 | Batch 90/202 | Rec 0.000607 | Seg 0.286322 | Elapsed 1.9m | ETA 2.4m
Epoch 358/500 | Batch 100/202 | Rec 0.000602 | Seg 0.283305 | Elapsed 2.1m | ETA 2.2m
Epoch 358/500 | Batch 110/202 | Rec 0.000596 | Seg 0.281146 | Elapsed 2.3m | ETA 2.0m
Epoch 358/500 | Batch 120/202 | Rec 0.000607 | Seg 0.284598 | Elapsed 2.5m | ETA 1.7m
Epoch 358/500 | Batch 130/202 | Rec 0.000612 | Seg 0.283515 | Elapsed 2.8m | ETA 1.5m
Epoch 358/500 | Batch 140/202 | Rec 0.000613 | Seg 0.281044 | Elapsed 3.0m | ETA 1.3m
Epoch 358/500 | Batch 150/202 | Rec 0.000614 | Seg 0.283910 | Elapsed 3.2m | ETA 1.1m
Epoch 358/500 | Batch 160/202 | Rec 0.000608 | Seg 0.282776 | Elapsed 3.4m | ETA 0.9m
Epoch 358/500 | Batch 170/202 | Rec 0.000604 | Seg 0.279665 | Elapsed 3.6m | ETA 0.7m
Epoch 358/500 | Batch 180/202 | Rec 0.000611 | Seg 0.276599 | Elapsed 3.8m | ETA 0.5m
Epoch 358/500 | Batch 190/202 | Rec 0.000609 | Seg 0.276409 | Elapsed 4.0m | ETA 0.3m
Epoch 358/500 | Batch 200/202 | Rec 0.000614 | Seg 0.279463 | Elapsed 4.2m | ETA 0.0m
Epoch 358/500 | Batch 202/202 | Rec 0.000613 | Seg 0.279385 | Elapsed 4.3m | ETA 0.0m

2026-09-25 23:03:53,843 - INFO: Rec loss: 0.0006132056781161106
2026-09-25 23:03:53,843 - INFO: Seg loss: 0.27938463953830817
2026-09-25 23:03:53,843 - INFO: λ_rec: 1
2026-09-25 23:03:53,843 - INFO: λ_seg: 0.0001
2026-09-25 23:05:16,833 - INFO: -------------------Epoch: 358------------------------
2026-09-25 23:05:16,837 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.865969  0.974642  0.000136
2026-09-25 23:05:16,844 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995642  0.997766  0.996914  0.998720  0.995838
real potato   0.927783  0.962489  0.982214  0.943637  0.999912
fake potato   0.859752  0.924538  0.965140  0.887306  0.999895
real apple    0.758705  0.862750  0.982595  0.769040  0.999156
fake apple    0.599704  0.749722  0.981684  0.606490  0.998472
real orange   0.868902  0.929803  0.998141  0.870310  0.999827
fake orange   0.914580  0.955334  0.936294  0.975269  0.999739
real grape    0.811124  0.895663  0.959506  0.839874  0.999592
fake grape    0.896845  0.945568  0.935708  0.955740  0.999593
real lemon    0.523097  0.686837  0.602725  0.798364  0.999145
fake lemon    0.854427  0.921450  0.993908  0.858925  0.999690
real avocado  0.945769  0.972079  0.994504  0.950739  0.999949
fake avocado  0.331676  0.498095  1.000000  0.331676  0.999200
real pepper   0.874586  0.933048  0.900260  0.968421  0.999492
fake pepper   0.801042  0.889482  0.949245  0.836886  0.999505
real plant    0.870901  0.930947  0.959690  0.903969  0.998660
fake plant    0.704929  0.826881  0.845830  0.808857  0.999731
real banana   0.574715  0.729881  0.926266  0.602268  0.998999
fake banana   0.655510  0.791863  0.736688  0.856088  0.999172
real onion    0.617049  0.763131  0.631882  0.963351  0.999460
fake onion    0.934559  0.966123  0.986885  0.946312  0.999958
real unknown  0.665289  0.798958  0.705109  0.921756  0.999926
fake unknown  0.192115  0.322275  0.206336  0.735965  0.997392
total         0.746900  0.837160  0.877284  0.840433  0.999231
total(-bg)    0.735594  0.829860  0.871846  0.833238  0.999385
2026-09-25 23:05:17,384 - INFO: Epoch accounting: {'epoch': 358, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11343979, 64890, 69805, 119384, 153526, 55681, 56424, 119949, 204511, 67852, 84995, 35464, 44924, 212099, 165502, 119972, 24569, 79366, 51613, 67449, 49173, 6418, 40727], 'crops_with_class': [202, 32, 29, 32, 37, 19, 19, 23, 42, 32, 30, 12, 15, 45, 39, 18, 19, 27, 23, 29, 24, 6, 16], 'targeted_crops_by_class': [0, 6, 7, 4, 4, 4, 2, 4, 6, 1, 5, 5, 2, 7, 3, 2, 4, 2, 7, 2, 5, 2, 4], 'sampled_scene_counts': [1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 3, 1, 2, 1, 2, 0, 0, 2, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 2, 1, 1, 3, 1, 1, 1, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 3, 1, 1, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 3, 1, 0, 3, 2, 2, 2, 1, 1, 2, 0, 1, 1, 1, 2, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 0, 0, 0, 2, 1, 1, 1, 2, 2, 1, 0, 0, 1, 3, 1, 2, 1, 1, 1, 1, 0, 0, 3, 2, 1, 2, 3, 3, 2, 2, 3, 0, 1, 1, 1, 4, 2, 2, 2, 1, 1, 0, 0, 1, 1, 1, 0, 2, 0, 2, 1, 0, 3, 0, 2, 0], 'learning_rate': 1.9063459448155364e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006132056781161106, 'train_segmentation_loss': 0.27938463953830817, 'val_foreground_miou_all22': 0.7355935604669047, 'val_psnr_ref1': 38.86596939086914, 'elapsed_seconds': 340.1581757068634, 'peak_cuda_allocated_gib': 7.511783599853516}

Epoch 359/500 | Batch 10/202 | Rec 0.000574 | Seg 0.312975 | Elapsed 0.2m | ETA 4.0m
Epoch 359/500 | Batch 20/202 | Rec 0.000541 | Seg 0.281786 | Elapsed 0.4m | ETA 3.9m
Epoch 359/500 | Batch 30/202 | Rec 0.000556 | Seg 0.287267 | Elapsed 0.6m | ETA 3.6m
Epoch 359/500 | Batch 40/202 | Rec 0.000549 | Seg 0.284505 | Elapsed 0.8m | ETA 3.4m
Epoch 359/500 | Batch 50/202 | Rec 0.000562 | Seg 0.287167 | Elapsed 1.1m | ETA 3.2m
Epoch 359/500 | Batch 60/202 | Rec 0.000573 | Seg 0.288389 | Elapsed 1.3m | ETA 3.0m
Epoch 359/500 | Batch 70/202 | Rec 0.000578 | Seg 0.284544 | Elapsed 1.5m | ETA 2.8m
Epoch 359/500 | Batch 80/202 | Rec 0.000581 | Seg 0.279617 | Elapsed 1.7m | ETA 2.6m
Epoch 359/500 | Batch 90/202 | Rec 0.000592 | Seg 0.281446 | Elapsed 1.9m | ETA 2.4m
Epoch 359/500 | Batch 100/202 | Rec 0.000582 | Seg 0.278702 | Elapsed 2.1m | ETA 2.2m
Epoch 359/500 | Batch 110/202 | Rec 0.000594 | Seg 0.283306 | Elapsed 2.3m | ETA 1.9m
Epoch 359/500 | Batch 120/202 | Rec 0.000591 | Seg 0.284489 | Elapsed 2.5m | ETA 1.7m
Epoch 359/500 | Batch 130/202 | Rec 0.000587 | Seg 0.283756 | Elapsed 2.7m | ETA 1.5m
Epoch 359/500 | Batch 140/202 | Rec 0.000594 | Seg 0.281882 | Elapsed 3.0m | ETA 1.3m
Epoch 359/500 | Batch 150/202 | Rec 0.000596 | Seg 0.283048 | Elapsed 3.2m | ETA 1.1m
Epoch 359/500 | Batch 160/202 | Rec 0.000604 | Seg 0.280813 | Elapsed 3.4m | ETA 0.9m
Epoch 359/500 | Batch 170/202 | Rec 0.000600 | Seg 0.282364 | Elapsed 3.6m | ETA 0.7m
Epoch 359/500 | Batch 180/202 | Rec 0.000597 | Seg 0.282081 | Elapsed 3.8m | ETA 0.5m
Epoch 359/500 | Batch 190/202 | Rec 0.000602 | Seg 0.284185 | Elapsed 4.0m | ETA 0.3m
Epoch 359/500 | Batch 200/202 | Rec 0.000603 | Seg 0.286861 | Elapsed 4.2m | ETA 0.0m
Epoch 359/500 | Batch 202/202 | Rec 0.000601 | Seg 0.285874 | Elapsed 4.3m | ETA 0.0m

2026-09-25 23:09:33,171 - INFO: Rec loss: 0.0006006372383522506
2026-09-25 23:09:33,171 - INFO: Seg loss: 0.2858736452711101
2026-09-25 23:09:33,171 - INFO: λ_rec: 1
2026-09-25 23:09:33,171 - INFO: λ_seg: 0.0001
2026-09-25 23:10:58,140 - INFO: -------------------Epoch: 359------------------------
2026-09-25 23:10:58,144 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.962608  0.974721  0.000133
2026-09-25 23:10:58,152 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995557  0.997724  0.996741  0.998808  0.995757
real potato   0.432226  0.603530  0.995602  0.433053  0.999319
fake potato   0.662951  0.797271  0.978373  0.672811  0.999751
real apple    0.711784  0.831578  0.797976  0.868244  0.998787
fake apple    0.663188  0.797442  0.984158  0.670344  0.998715
real orange   0.758176  0.862408  0.992762  0.762390  0.999680
fake orange   0.868603  0.929632  0.890521  0.972444  0.999579
real grape    0.853012  0.920626  0.968306  0.877512  0.999684
fake grape    0.891479  0.942576  0.928117  0.957596  0.999569
real lemon    0.532844  0.695188  0.568285  0.895222  0.999078
fake lemon    0.854649  0.921579  0.995564  0.857916  0.999691
real avocado  0.812144  0.896285  0.840765  0.959770  0.999794
fake avocado  0.600791  0.750570  0.999788  0.600867  0.999522
real pepper   0.769640  0.869777  0.813110  0.935049  0.998976
fake pepper   0.606806  0.755247  0.972088  0.617566  0.999046
real plant    0.867240  0.928851  0.968885  0.892086  0.998634
fake plant    0.759829  0.863476  0.842576  0.885544  0.999777
real banana   0.522366  0.686208  0.902758  0.553511  0.998863
fake banana   0.731702  0.845017  0.841867  0.848291  0.999428
real onion    0.657110  0.793030  0.725287  0.874852  0.999588
fake onion    0.935383  0.966563  0.992861  0.941717  0.999959
real unknown  0.907372  0.951387  0.989691  0.916030  0.999985
fake unknown  0.237253  0.383479  0.255328  0.770192  0.997914
total         0.723135  0.825628  0.880061  0.815731  0.999178
total(-bg)    0.710752  0.817805  0.874758  0.807409  0.999334
2026-09-25 23:10:58,764 - INFO: Epoch accounting: {'epoch': 359, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11284569, 55622, 54121, 116606, 151595, 89200, 76406, 189966, 189884, 74926, 50348, 30983, 37350, 237304, 129075, 134492, 23674, 67379, 67751, 73191, 61551, 9298, 32981], 'crops_with_class': [202, 28, 25, 31, 38, 24, 24, 29, 38, 36, 23, 11, 12, 54, 30, 19, 21, 22, 26, 29, 28, 10, 16], 'targeted_crops_by_class': [0, 3, 7, 5, 3, 4, 9, 6, 4, 3, 5, 3, 7, 5, 3, 1, 5, 5, 4, 5, 3, 7, 2], 'sampled_scene_counts': [1, 0, 2, 1, 1, 0, 1, 0, 2, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 2, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 0, 2, 0, 1, 0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 2, 1, 1, 2, 0, 2, 0, 4, 0, 1, 2, 1, 3, 2, 0, 2, 2, 0, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2, 1, 1, 1, 1, 4, 1, 2, 3, 1, 2, 2, 2, 0, 0, 1, 0, 0, 1, 2, 1, 2, 3, 1, 0, 3, 2, 2, 3, 1, 1, 1, 0, 1, 2, 0, 3, 1, 2, 0, 1, 2, 1, 1, 1, 1, 0, 1, 2, 3, 1, 3], 'learning_rate': 1.8818893355626286e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006006372383522506, 'train_segmentation_loss': 0.2858736452711101, 'val_foreground_miou_all22': 0.7107521942412212, 'val_psnr_ref1': 38.96260848999023, 'elapsed_seconds': 341.3711361885071, 'peak_cuda_allocated_gib': 7.509288787841797}

Epoch 360/500 | Batch 10/202 | Rec 0.000649 | Seg 0.307631 | Elapsed 0.2m | ETA 4.1m
Epoch 360/500 | Batch 20/202 | Rec 0.000604 | Seg 0.305799 | Elapsed 0.4m | ETA 3.8m
Epoch 360/500 | Batch 30/202 | Rec 0.000572 | Seg 0.283776 | Elapsed 0.6m | ETA 3.6m
Epoch 360/500 | Batch 40/202 | Rec 0.000574 | Seg 0.291038 | Elapsed 0.8m | ETA 3.4m
Epoch 360/500 | Batch 50/202 | Rec 0.000591 | Seg 0.286436 | Elapsed 1.0m | ETA 3.1m
Epoch 360/500 | Batch 60/202 | Rec 0.000606 | Seg 0.293786 | Elapsed 1.2m | ETA 2.9m
Epoch 360/500 | Batch 70/202 | Rec 0.000594 | Seg 0.287796 | Elapsed 1.5m | ETA 2.7m
Epoch 360/500 | Batch 80/202 | Rec 0.000573 | Seg 0.284051 | Elapsed 1.7m | ETA 2.5m
Epoch 360/500 | Batch 90/202 | Rec 0.000576 | Seg 0.291167 | Elapsed 1.9m | ETA 2.3m
Epoch 360/500 | Batch 100/202 | Rec 0.000576 | Seg 0.285615 | Elapsed 2.1m | ETA 2.1m
Epoch 360/500 | Batch 110/202 | Rec 0.000580 | Seg 0.290457 | Elapsed 2.3m | ETA 1.9m
Epoch 360/500 | Batch 120/202 | Rec 0.000584 | Seg 0.292741 | Elapsed 2.5m | ETA 1.7m
Epoch 360/500 | Batch 130/202 | Rec 0.000589 | Seg 0.291480 | Elapsed 2.7m | ETA 1.5m
Epoch 360/500 | Batch 140/202 | Rec 0.000589 | Seg 0.291737 | Elapsed 2.9m | ETA 1.3m
Epoch 360/500 | Batch 150/202 | Rec 0.000591 | Seg 0.289540 | Elapsed 3.1m | ETA 1.1m
Epoch 360/500 | Batch 160/202 | Rec 0.000592 | Seg 0.288609 | Elapsed 3.4m | ETA 0.9m
Epoch 360/500 | Batch 170/202 | Rec 0.000593 | Seg 0.285852 | Elapsed 3.6m | ETA 0.7m
Epoch 360/500 | Batch 180/202 | Rec 0.000594 | Seg 0.287506 | Elapsed 3.8m | ETA 0.5m
Epoch 360/500 | Batch 190/202 | Rec 0.000591 | Seg 0.287664 | Elapsed 4.0m | ETA 0.3m
Epoch 360/500 | Batch 200/202 | Rec 0.000586 | Seg 0.286354 | Elapsed 4.2m | ETA 0.0m
Epoch 360/500 | Batch 202/202 | Rec 0.000588 | Seg 0.286576 | Elapsed 4.2m | ETA 0.0m

2026-09-25 23:15:13,477 - INFO: Rec loss: 0.0005883210610816172
2026-09-25 23:15:13,477 - INFO: Seg loss: 0.2865764518443606
2026-09-25 23:15:13,478 - INFO: λ_rec: 1
2026-09-25 23:15:13,478 - INFO: λ_seg: 0.0001
2026-09-25 23:16:34,540 - INFO: -------------------Epoch: 360------------------------
2026-09-25 23:16:34,544 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.014158  0.974833  0.000131
2026-09-25 23:16:34,552 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995732  0.997812  0.997124  0.998600  0.995925
real potato   0.918792  0.957628  0.942025  0.973859  0.999897
fake potato   0.953055  0.975914  0.965560  0.986594  0.999965
real apple    0.770148  0.870102  0.993080  0.774303  0.999203
fake apple    0.631850  0.774349  0.991859  0.635144  0.998603
real orange   0.912396  0.954142  0.996470  0.915354  0.999884
fake orange   0.924865  0.960916  0.948639  0.973617  0.999774
real grape    0.794868  0.885662  0.957297  0.824088  0.999556
fake grape    0.905898  0.950576  0.947065  0.954214  0.999633
real lemon    0.659209  0.794556  0.765272  0.826279  0.999498
fake lemon    0.844664  0.915742  0.998213  0.845943  0.999671
real avocado  0.930734  0.964074  0.964045  0.964204  0.999933
fake avocado  0.707675  0.828768  0.999640  0.707855  0.999650
real pepper   0.812943  0.896772  0.833166  0.971008  0.999183
fake pepper   0.687114  0.814494  0.952757  0.711350  0.999228
real plant    0.864964  0.927543  0.952706  0.903771  0.998589
fake plant    0.892635  0.943222  0.952679  0.934049  0.999911
real banana   0.729777  0.843732  0.901049  0.793359  0.999340
fake banana   0.689844  0.816409  0.764817  0.875581  0.999276
real onion    0.622283  0.767121  0.637890  0.962169  0.999472
fake onion    0.917991  0.957192  0.950847  0.963724  0.999946
real unknown  0.536504  0.698297  0.560694  0.925572  0.999872
fake unknown  0.218098  0.358056  0.243885  0.673488  0.997966
total         0.779219  0.863177  0.878990  0.873658  0.999303
total(-bg)    0.769378  0.857058  0.873621  0.867978  0.999457
2026-09-25 23:16:35,314 - INFO: Epoch accounting: {'epoch': 360, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11288183, 59331, 78429, 134092, 95086, 96557, 81642, 95803, 145584, 67843, 58715, 55431, 61021, 244079, 130663, 136296, 28599, 62363, 91017, 86743, 66479, 18156, 56160], 'crops_with_class': [202, 31, 37, 34, 25, 27, 28, 21, 32, 31, 28, 19, 23, 58, 33, 20, 23, 19, 40, 39, 27, 18, 26], 'targeted_crops_by_class': [0, 4, 7, 2, 2, 6, 4, 2, 2, 8, 3, 6, 10, 6, 4, 3, 4, 2, 8, 5, 3, 10, 2], 'sampled_scene_counts': [1, 0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 0, 2, 2, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 1, 1, 3, 1, 1, 2, 3, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 3, 0, 1, 2, 3, 0, 3, 0, 0, 2, 1, 1, 2, 1, 0, 1, 0, 1, 2, 2, 1, 0, 0, 1, 2, 2, 1, 3, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 6, 3, 5, 2, 1, 1, 1, 1, 2, 0, 0, 3, 0, 1, 2, 2, 0, 2, 2, 1, 3, 1, 1, 2, 2, 0, 0, 0, 4, 3, 0, 4, 2, 1, 1, 0, 1, 1, 0, 0, 3, 2, 2], 'learning_rate': 1.8575563174582887e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005883210610816172, 'train_segmentation_loss': 0.2865764518443606, 'val_foreground_miou_all22': 0.769377520720694, 'val_psnr_ref1': 39.014158477783205, 'elapsed_seconds': 336.541610956192, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 361/500 | Batch 10/202 | Rec 0.000592 | Seg 0.264798 | Elapsed 0.2m | ETA 4.2m
Epoch 361/500 | Batch 20/202 | Rec 0.000613 | Seg 0.310243 | Elapsed 0.4m | ETA 3.9m
Epoch 361/500 | Batch 30/202 | Rec 0.000606 | Seg 0.299001 | Elapsed 0.6m | ETA 3.7m
Epoch 361/500 | Batch 40/202 | Rec 0.000579 | Seg 0.281653 | Elapsed 0.8m | ETA 3.4m
Epoch 361/500 | Batch 50/202 | Rec 0.000572 | Seg 0.284324 | Elapsed 1.1m | ETA 3.2m
Epoch 361/500 | Batch 60/202 | Rec 0.000562 | Seg 0.281684 | Elapsed 1.3m | ETA 3.0m
Epoch 361/500 | Batch 70/202 | Rec 0.000574 | Seg 0.285488 | Elapsed 1.5m | ETA 2.8m
Epoch 361/500 | Batch 80/202 | Rec 0.000568 | Seg 0.287132 | Elapsed 1.7m | ETA 2.6m
Epoch 361/500 | Batch 90/202 | Rec 0.000572 | Seg 0.285450 | Elapsed 1.9m | ETA 2.4m
Epoch 361/500 | Batch 100/202 | Rec 0.000576 | Seg 0.288784 | Elapsed 2.1m | ETA 2.1m
Epoch 361/500 | Batch 110/202 | Rec 0.000576 | Seg 0.282936 | Elapsed 2.3m | ETA 1.9m
Epoch 361/500 | Batch 120/202 | Rec 0.000585 | Seg 0.285787 | Elapsed 2.5m | ETA 1.7m
Epoch 361/500 | Batch 130/202 | Rec 0.000586 | Seg 0.287145 | Elapsed 2.7m | ETA 1.5m
Epoch 361/500 | Batch 140/202 | Rec 0.000587 | Seg 0.285301 | Elapsed 2.9m | ETA 1.3m
Epoch 361/500 | Batch 150/202 | Rec 0.000597 | Seg 0.287808 | Elapsed 3.2m | ETA 1.1m
Epoch 361/500 | Batch 160/202 | Rec 0.000597 | Seg 0.288880 | Elapsed 3.4m | ETA 0.9m
Epoch 361/500 | Batch 170/202 | Rec 0.000593 | Seg 0.286675 | Elapsed 3.6m | ETA 0.7m
Epoch 361/500 | Batch 180/202 | Rec 0.000595 | Seg 0.289725 | Elapsed 3.8m | ETA 0.5m
Epoch 361/500 | Batch 190/202 | Rec 0.000598 | Seg 0.291070 | Elapsed 4.0m | ETA 0.3m
Epoch 361/500 | Batch 200/202 | Rec 0.000599 | Seg 0.292864 | Elapsed 4.2m | ETA 0.0m
Epoch 361/500 | Batch 202/202 | Rec 0.000600 | Seg 0.292858 | Elapsed 4.2m | ETA 0.0m

2026-09-25 23:20:50,157 - INFO: Rec loss: 0.0006000968551414207
2026-09-25 23:20:50,157 - INFO: Seg loss: 0.29285837637979795
2026-09-25 23:20:50,157 - INFO: λ_rec: 1
2026-09-25 23:20:50,157 - INFO: λ_seg: 0.0001
2026-09-25 23:22:15,860 - INFO: -------------------Epoch: 361------------------------
2026-09-25 23:22:15,864 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.992313  0.974878  0.000131
2026-09-25 23:22:15,872 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995626  0.997758  0.997115  0.998502  0.995824
real potato   0.581081  0.734996  0.999561  0.581229  0.999499
fake potato   0.691278  0.817413  0.956229  0.713867  0.999768
real apple    0.719431  0.836775  0.850745  0.823352  0.998892
fake apple    0.627943  0.771407  0.955579  0.646823  0.998553
real orange   0.870893  0.930942  0.998938  0.871700  0.999830
fake orange   0.916967  0.956635  0.937123  0.977081  0.999747
real grape    0.775352  0.873413  0.966407  0.796828  0.999518
fake grape    0.867400  0.928942  0.905887  0.953306  0.999461
real lemon    0.330643  0.496922  0.381498  0.712672  0.998304
fake lemon    0.860740  0.925109  0.990453  0.867941  0.999703
real avocado  0.857101  0.923003  0.890313  0.958292  0.999852
fake avocado  0.593981  0.745233  1.000000  0.593981  0.999514
real pepper   0.876204  0.933968  0.923749  0.944519  0.999512
fake pepper   0.838105  0.911873  0.968009  0.861981  0.999603
real plant    0.877019  0.934431  0.942994  0.926120  0.998701
fake plant    0.778355  0.875315  0.889395  0.861771  0.999805
real banana   0.265235  0.419229  0.856813  0.277536  0.998272
fake banana   0.634981  0.776694  0.716327  0.848291  0.999103
real onion    0.696843  0.821291  0.756507  0.898328  0.999647
fake onion    0.878043  0.935012  0.985270  0.889722  0.999922
real unknown  0.867320  0.928896  0.928503  0.929389  0.999977
fake unknown  0.215186  0.354126  0.229171  0.779066  0.997606
total         0.722423  0.818669  0.870721  0.813578  0.999157
total(-bg)    0.710004  0.810528  0.864976  0.805173  0.999309
2026-09-25 23:22:16,428 - INFO: Epoch accounting: {'epoch': 361, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11275674, 41494, 50006, 104245, 138354, 52028, 77674, 144588, 175442, 59215, 60106, 51007, 57672, 257450, 138626, 128189, 24997, 101136, 75642, 102266, 61283, 9950, 51228], 'crops_with_class': [202, 25, 22, 31, 36, 16, 27, 27, 31, 30, 25, 15, 22, 62, 34, 18, 21, 29, 32, 42, 30, 12, 22], 'targeted_crops_by_class': [0, 2, 8, 1, 9, 3, 5, 6, 2, 2, 4, 8, 7, 7, 4, 3, 4, 3, 6, 7, 4, 4, 3], 'sampled_scene_counts': [1, 0, 0, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 0, 0, 1, 3, 1, 1, 0, 1, 0, 2, 0, 2, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 1, 2, 1, 2, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 2, 1, 1, 1, 2, 1, 0, 1, 3, 1, 1, 1, 2, 2, 3, 3, 0, 1, 1, 2, 0, 1, 0, 1, 1, 2, 0, 2, 3, 0, 2, 1, 3, 1, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 2, 1, 1, 5, 3, 2, 2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 0, 4, 2, 1, 2, 1, 0, 3, 1, 0, 2, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 2, 3, 1, 3, 2], 'learning_rate': 1.833347851128407e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006000968551414207, 'train_segmentation_loss': 0.29285837637979795, 'val_foreground_miou_all22': 0.710004492846056, 'val_psnr_ref1': 38.992313079833984, 'elapsed_seconds': 341.1050720214844, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 362/500 | Batch 10/202 | Rec 0.000604 | Seg 0.301737 | Elapsed 0.2m | ETA 4.1m
Epoch 362/500 | Batch 20/202 | Rec 0.000632 | Seg 0.325572 | Elapsed 0.4m | ETA 3.8m
Epoch 362/500 | Batch 30/202 | Rec 0.000636 | Seg 0.319045 | Elapsed 0.6m | ETA 3.6m
Epoch 362/500 | Batch 40/202 | Rec 0.000640 | Seg 0.318458 | Elapsed 0.8m | ETA 3.4m
Epoch 362/500 | Batch 50/202 | Rec 0.000647 | Seg 0.309830 | Elapsed 1.1m | ETA 3.2m
Epoch 362/500 | Batch 60/202 | Rec 0.000643 | Seg 0.312659 | Elapsed 1.3m | ETA 3.0m
Epoch 362/500 | Batch 70/202 | Rec 0.000668 | Seg 0.320069 | Elapsed 1.5m | ETA 2.8m
Epoch 362/500 | Batch 80/202 | Rec 0.000671 | Seg 0.317932 | Elapsed 1.7m | ETA 2.6m
Epoch 362/500 | Batch 90/202 | Rec 0.000655 | Seg 0.310827 | Elapsed 1.9m | ETA 2.3m
Epoch 362/500 | Batch 100/202 | Rec 0.000639 | Seg 0.303562 | Elapsed 2.1m | ETA 2.1m
Epoch 362/500 | Batch 110/202 | Rec 0.000624 | Seg 0.299499 | Elapsed 2.3m | ETA 1.9m
Epoch 362/500 | Batch 120/202 | Rec 0.000620 | Seg 0.297133 | Elapsed 2.5m | ETA 1.7m
Epoch 362/500 | Batch 130/202 | Rec 0.000620 | Seg 0.298288 | Elapsed 2.7m | ETA 1.5m
Epoch 362/500 | Batch 140/202 | Rec 0.000618 | Seg 0.298358 | Elapsed 2.9m | ETA 1.3m
Epoch 362/500 | Batch 150/202 | Rec 0.000609 | Seg 0.292402 | Elapsed 3.1m | ETA 1.1m
Epoch 362/500 | Batch 160/202 | Rec 0.000604 | Seg 0.291114 | Elapsed 3.4m | ETA 0.9m
Epoch 362/500 | Batch 170/202 | Rec 0.000623 | Seg 0.289733 | Elapsed 3.6m | ETA 0.7m
Epoch 362/500 | Batch 180/202 | Rec 0.000623 | Seg 0.291138 | Elapsed 3.8m | ETA 0.5m
Epoch 362/500 | Batch 190/202 | Rec 0.000618 | Seg 0.287135 | Elapsed 4.0m | ETA 0.3m
Epoch 362/500 | Batch 200/202 | Rec 0.000622 | Seg 0.287150 | Elapsed 4.2m | ETA 0.0m
Epoch 362/500 | Batch 202/202 | Rec 0.000620 | Seg 0.286759 | Elapsed 4.2m | ETA 0.0m

2026-09-25 23:26:30,263 - INFO: Rec loss: 0.0006200220128394534
2026-09-25 23:26:30,263 - INFO: Seg loss: 0.2867594341756684
2026-09-25 23:26:30,263 - INFO: λ_rec: 1
2026-09-25 23:26:30,263 - INFO: λ_seg: 0.0001
2026-09-25 23:27:51,743 - INFO: -------------------Epoch: 362------------------------
2026-09-25 23:27:51,747 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.030179  0.974907  0.000131
2026-09-25 23:27:51,755 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995553  0.997721  0.997363  0.998180  0.995755
real potato   0.504848  0.670917  0.975901  0.511222  0.999400
fake potato   0.678505  0.808415  0.987606  0.684332  0.999764
real apple    0.712064  0.831770  0.825266  0.838479  0.998830
fake apple    0.594744  0.745833  0.980767  0.601762  0.998452
real orange   0.952326  0.975531  0.996738  0.955303  0.999937
fake orange   0.958669  0.978849  0.988745  0.969246  0.999880
real grape    0.801834  0.889970  0.949992  0.837170  0.999568
fake grape    0.889513  0.941476  0.905964  0.979994  0.999550
real lemon    0.658839  0.794288  0.687892  0.939756  0.999428
fake lemon    0.857040  0.922968  0.995411  0.860440  0.999696
real avocado  0.933928  0.965785  0.968466  0.963218  0.999937
fake avocado  0.687492  0.814761  0.999815  0.687580  0.999626
real pepper   0.809945  0.894944  0.836086  0.962832  0.999174
fake pepper   0.684391  0.812579  0.964638  0.702004  0.999228
real plant    0.871667  0.931384  0.950561  0.913061  0.998655
fake plant    0.810421  0.895235  0.847934  0.948236  0.999823
real banana   0.648859  0.786990  0.846076  0.735706  0.999105
fake banana   0.705514  0.827283  0.796500  0.860650  0.999339
real onion    0.637604  0.778655  0.657478  0.954737  0.999510
fake onion    0.927751  0.962472  0.988529  0.937848  0.999954
real unknown  0.841105  0.913646  0.898524  0.929389  0.999972
fake unknown  0.237235  0.383456  0.251351  0.808584  0.997809
total         0.756515  0.848910  0.882504  0.851293  0.999234
total(-bg)    0.745650  0.842146  0.877284  0.844616  0.999393
2026-09-25 23:27:52,481 - INFO: Epoch accounting: {'epoch': 362, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11289270, 49738, 67824, 116546, 90532, 86656, 59281, 87804, 138538, 84369, 79611, 38647, 48165, 255246, 169210, 212565, 24002, 86503, 62243, 73342, 52738, 13869, 51573], 'crops_with_class': [202, 30, 28, 28, 29, 27, 22, 24, 29, 35, 29, 14, 18, 64, 34, 25, 26, 26, 27, 31, 23, 15, 22], 'targeted_crops_by_class': [0, 4, 6, 3, 3, 6, 2, 3, 1, 6, 5, 2, 6, 8, 6, 6, 4, 7, 3, 4, 4, 6, 5], 'sampled_scene_counts': [1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 2, 0, 1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2, 2, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 0, 0, 2, 0, 2, 2, 1, 3, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 0, 2, 1, 2, 1, 2, 0, 3, 3, 1, 2, 1, 4, 2, 3, 2, 1, 1, 0, 1, 2, 1, 1, 0, 2, 2, 1, 1, 3, 1, 1, 1, 3, 1, 2, 3, 2, 0, 1, 2, 1, 0, 1, 1, 1, 2, 1, 2, 1, 3, 1, 4, 1, 0, 1], 'learning_rate': 1.809264892281784e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0006200220128394534, 'train_segmentation_loss': 0.2867594341756684, 'val_foreground_miou_all22': 0.7456497574870865, 'val_psnr_ref1': 39.03017913818359, 'elapsed_seconds': 336.04491114616394, 'peak_cuda_allocated_gib': 7.512760162353516}

Epoch 363/500 | Batch 10/202 | Rec 0.000572 | Seg 0.280585 | Elapsed 0.2m | ETA 4.2m
Epoch 363/500 | Batch 20/202 | Rec 0.000565 | Seg 0.277893 | Elapsed 0.4m | ETA 3.9m
Epoch 363/500 | Batch 30/202 | Rec 0.000531 | Seg 0.253016 | Elapsed 0.6m | ETA 3.7m
Epoch 363/500 | Batch 40/202 | Rec 0.000592 | Seg 0.262803 | Elapsed 0.9m | ETA 3.5m
Epoch 363/500 | Batch 50/202 | Rec 0.000574 | Seg 0.262892 | Elapsed 1.1m | ETA 3.3m
Epoch 363/500 | Batch 60/202 | Rec 0.000551 | Seg 0.258322 | Elapsed 1.3m | ETA 3.0m
Epoch 363/500 | Batch 70/202 | Rec 0.000564 | Seg 0.269162 | Elapsed 1.5m | ETA 2.8m
Epoch 363/500 | Batch 80/202 | Rec 0.000565 | Seg 0.269576 | Elapsed 1.7m | ETA 2.6m
Epoch 363/500 | Batch 90/202 | Rec 0.000570 | Seg 0.269830 | Elapsed 1.9m | ETA 2.4m
Epoch 363/500 | Batch 100/202 | Rec 0.000572 | Seg 0.269016 | Elapsed 2.1m | ETA 2.2m
Epoch 363/500 | Batch 110/202 | Rec 0.000577 | Seg 0.273026 | Elapsed 2.3m | ETA 1.9m
Epoch 363/500 | Batch 120/202 | Rec 0.000586 | Seg 0.277923 | Elapsed 2.5m | ETA 1.7m
Epoch 363/500 | Batch 130/202 | Rec 0.000582 | Seg 0.279469 | Elapsed 2.7m | ETA 1.5m
Epoch 363/500 | Batch 140/202 | Rec 0.000575 | Seg 0.278358 | Elapsed 2.9m | ETA 1.3m
Epoch 363/500 | Batch 150/202 | Rec 0.000579 | Seg 0.281467 | Elapsed 3.1m | ETA 1.1m
Epoch 363/500 | Batch 160/202 | Rec 0.000581 | Seg 0.284241 | Elapsed 3.3m | ETA 0.9m
Epoch 363/500 | Batch 170/202 | Rec 0.000577 | Seg 0.282969 | Elapsed 3.5m | ETA 0.7m
Epoch 363/500 | Batch 180/202 | Rec 0.000579 | Seg 0.282775 | Elapsed 3.8m | ETA 0.5m
Epoch 363/500 | Batch 190/202 | Rec 0.000581 | Seg 0.282591 | Elapsed 4.0m | ETA 0.3m
Epoch 363/500 | Batch 200/202 | Rec 0.000579 | Seg 0.280521 | Elapsed 4.2m | ETA 0.0m
Epoch 363/500 | Batch 202/202 | Rec 0.000579 | Seg 0.279446 | Elapsed 4.2m | ETA 0.0m

2026-09-25 23:32:06,167 - INFO: Rec loss: 0.0005788876856463998
2026-09-25 23:32:06,167 - INFO: Seg loss: 0.2794456462938302
2026-09-25 23:32:06,167 - INFO: λ_rec: 1
2026-09-25 23:32:06,168 - INFO: λ_seg: 0.0001
2026-09-25 23:33:30,102 - INFO: -------------------Epoch: 363------------------------
2026-09-25 23:33:30,109 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.017244  0.974977  0.000131
2026-09-25 23:33:30,119 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995542  0.997716  0.997067  0.998465  0.995743
real potato   0.663225  0.797469  0.981188  0.671767  0.999592
fake potato   0.812886  0.896737  0.979172  0.827189  0.999861
real apple    0.745188  0.853942  0.867674  0.840734  0.999008
fake apple    0.604393  0.753375  0.989353  0.608349  0.998497
real orange   0.909468  0.952538  0.995581  0.913154  0.999880
fake orange   0.918273  0.957346  0.950134  0.964769  0.999754
real grape    0.774438  0.872833  0.949485  0.807718  0.999509
fake grape    0.879973  0.936105  0.913588  0.959865  0.999516
real lemon    0.533871  0.696061  0.584909  0.859517  0.999118
fake lemon    0.836494  0.910919  0.995299  0.839812  0.999653
real avocado  0.876774  0.934291  0.906564  0.963875  0.999874
fake avocado  0.716471  0.834770  0.999644  0.716654  0.999661
real pepper   0.779239  0.875874  0.809549  0.954155  0.999011
fake pepper   0.626969  0.770672  0.957957  0.644709  0.999086
real plant    0.862657  0.926215  0.949402  0.904229  0.998560
fake plant    0.844441  0.915610  0.908319  0.923121  0.999865
real banana   0.599877  0.749854  0.868299  0.659921  0.999011
fake banana   0.676871  0.807253  0.749449  0.874834  0.999232
real onion    0.651751  0.789114  0.713272  0.883128  0.999574
fake onion    0.951822  0.975266  0.990768  0.960339  0.999969
real unknown  0.833478  0.909127  0.901501  0.916985  0.999971
fake unknown  0.201434  0.335285  0.225817  0.651032  0.997825
total         0.751980  0.845581  0.877565  0.841057  0.999207
total(-bg)    0.740909  0.838666  0.872133  0.833903  0.999365
2026-09-25 23:33:30,730 - INFO: Epoch accounting: {'epoch': 363, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11370705, 52628, 62653, 108197, 143200, 63058, 94809, 140589, 179382, 60462, 52539, 50497, 30558, 243183, 85891, 127830, 33895, 68336, 92973, 91081, 48334, 11412, 26060], 'crops_with_class': [202, 28, 29, 27, 35, 20, 29, 28, 31, 28, 26, 19, 12, 62, 23, 24, 30, 20, 41, 35, 26, 10, 15], 'targeted_crops_by_class': [0, 4, 3, 6, 4, 3, 6, 4, 2, 4, 6, 6, 5, 5, 6, 5, 8, 5, 7, 3, 6, 1, 5], 'sampled_scene_counts': [1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 2, 1, 1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 2, 4, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 3, 0, 1, 2, 1, 0, 1, 1, 1, 2, 0, 1, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 2, 0, 1, 0, 1, 3, 1, 0, 1, 1, 1, 2, 1, 0, 2, 1, 2, 2, 1, 3, 0, 2, 1, 3, 3, 1, 2, 2, 2, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 3, 3, 3, 1, 1, 2, 4, 0, 1, 1, 0, 2, 1, 0, 0, 2, 1, 1, 1, 0, 2, 1, 2, 1, 0, 4, 1, 3, 2, 1, 0, 0, 2, 2, 2, 2, 1, 3, 1, 0, 2, 2, 2, 1, 4, 0, 2], 'learning_rate': 1.7853083916723932e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005788876856463998, 'train_segmentation_loss': 0.2794456462938302, 'val_foreground_miou_all22': 0.7409086879197112, 'val_psnr_ref1': 39.01724365234375, 'elapsed_seconds': 338.2407474517822, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 364/500 | Batch 10/202 | Rec 0.000690 | Seg 0.303235 | Elapsed 0.2m | ETA 4.0m
Epoch 364/500 | Batch 20/202 | Rec 0.000618 | Seg 0.289408 | Elapsed 0.4m | ETA 3.8m
Epoch 364/500 | Batch 30/202 | Rec 0.000641 | Seg 0.281206 | Elapsed 0.6m | ETA 3.6m
Epoch 364/500 | Batch 40/202 | Rec 0.000624 | Seg 0.276313 | Elapsed 0.8m | ETA 3.4m
Epoch 364/500 | Batch 50/202 | Rec 0.000613 | Seg 0.282774 | Elapsed 1.0m | ETA 3.2m
Epoch 364/500 | Batch 60/202 | Rec 0.000635 | Seg 0.295388 | Elapsed 1.3m | ETA 3.0m
Epoch 364/500 | Batch 70/202 | Rec 0.000613 | Seg 0.289777 | Elapsed 1.5m | ETA 2.8m
Epoch 364/500 | Batch 80/202 | Rec 0.000623 | Seg 0.290400 | Elapsed 1.7m | ETA 2.6m
Epoch 364/500 | Batch 90/202 | Rec 0.000627 | Seg 0.292164 | Elapsed 1.9m | ETA 2.3m
Epoch 364/500 | Batch 100/202 | Rec 0.000641 | Seg 0.301414 | Elapsed 2.1m | ETA 2.1m
Epoch 364/500 | Batch 110/202 | Rec 0.000623 | Seg 0.293766 | Elapsed 2.3m | ETA 1.9m
Epoch 364/500 | Batch 120/202 | Rec 0.000633 | Seg 0.301253 | Elapsed 2.5m | ETA 1.7m
Epoch 364/500 | Batch 130/202 | Rec 0.000634 | Seg 0.307020 | Elapsed 2.7m | ETA 1.5m
Epoch 364/500 | Batch 140/202 | Rec 0.000624 | Seg 0.302635 | Elapsed 2.9m | ETA 1.3m
Epoch 364/500 | Batch 150/202 | Rec 0.000619 | Seg 0.299402 | Elapsed 3.1m | ETA 1.1m
Epoch 364/500 | Batch 160/202 | Rec 0.000612 | Seg 0.298477 | Elapsed 3.3m | ETA 0.9m
Epoch 364/500 | Batch 170/202 | Rec 0.000620 | Seg 0.296555 | Elapsed 3.6m | ETA 0.7m
Epoch 364/500 | Batch 180/202 | Rec 0.000611 | Seg 0.294020 | Elapsed 3.8m | ETA 0.5m
Epoch 364/500 | Batch 190/202 | Rec 0.000615 | Seg 0.297894 | Elapsed 4.0m | ETA 0.3m
Epoch 364/500 | Batch 200/202 | Rec 0.000617 | Seg 0.297678 | Elapsed 4.2m | ETA 0.0m
Epoch 364/500 | Batch 202/202 | Rec 0.000621 | Seg 0.297189 | Elapsed 4.2m | ETA 0.0m

2026-09-25 23:37:44,988 - INFO: Rec loss: 0.0006207338004663476
2026-09-25 23:37:44,989 - INFO: Seg loss: 0.2971890788562227
2026-09-25 23:37:44,989 - INFO: λ_rec: 1
2026-09-25 23:37:44,989 - INFO: λ_seg: 0.0001
2026-09-25 23:39:10,437 - INFO: -------------------Epoch: 364------------------------
2026-09-25 23:39:10,441 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.706927  0.974293  0.00014
2026-09-25 23:39:10,449 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995584  0.997737  0.996986  0.998589  0.995784
real potato   0.931081  0.964261  0.962168  0.966463  0.999914
fake potato   0.949767  0.974186  0.966406  0.982195  0.999962
real apple    0.791751  0.883724  0.991420  0.797214  0.999277
fake apple    0.540847  0.701967  0.991374  0.543404  0.998258
real orange   0.717088  0.835188  0.995037  0.719662  0.999626
fake orange   0.851462  0.919723  0.878212  0.965462  0.999518
real grape    0.783494  0.878556  0.964279  0.806914  0.999534
fake grape    0.903563  0.949288  0.945647  0.953059  0.999624
real lemon    0.689434  0.816123  0.722929  0.937029  0.999504
fake lemon    0.846558  0.916854  0.998048  0.847962  0.999675
real avocado  0.910063  0.952864  0.955431  0.950410  0.999913
fake avocado  0.504973  0.671028  1.000000  0.504973  0.999408
real pepper   0.869851  0.930346  0.897754  0.965501  0.999472
fake pepper   0.795360  0.885967  0.950767  0.829524  0.999491
real plant    0.864363  0.927198  0.951182  0.904488  0.998580
fake plant    0.757485  0.861961  0.806005  0.926380  0.999764
real banana   0.696580  0.821108  0.907880  0.749559  0.999266
fake banana   0.676828  0.807222  0.754964  0.867369  0.999238
real onion    0.623587  0.768111  0.644666  0.950177  0.999482
fake onion    0.932039  0.964774  0.978131  0.951874  0.999956
real unknown  0.733741  0.846376  0.787356  0.915076  0.999947
fake unknown  0.178667  0.303132  0.198596  0.640348  0.997520
total         0.762790  0.851204  0.880228  0.855375  0.999248
total(-bg)    0.752208  0.844544  0.874920  0.848866  0.999406
2026-09-25 23:39:10,996 - INFO: Epoch accounting: {'epoch': 364, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11255639, 46654, 64889, 88680, 151491, 68106, 87897, 168301, 183965, 82179, 71302, 52502, 30800, 195814, 123264, 202133, 22450, 83792, 81708, 67549, 49291, 6704, 53162], 'crops_with_class': [202, 27, 29, 27, 34, 20, 28, 31, 26, 35, 29, 18, 14, 48, 31, 26, 20, 25, 31, 30, 26, 8, 20], 'targeted_crops_by_class': [0, 4, 5, 4, 5, 2, 9, 1, 2, 6, 6, 2, 4, 6, 2, 4, 5, 6, 5, 4, 4, 4, 7], 'sampled_scene_counts': [2, 0, 2, 1, 0, 1, 0, 2, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 2, 2, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 2, 2, 1, 0, 0, 0, 1, 2, 0, 1, 1, 0, 3, 1, 0, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 3, 1, 1, 0, 1, 1, 1, 2, 0, 3, 1, 1, 2, 0, 1, 1, 2, 0, 1, 1, 0, 2, 2, 3, 2, 2, 2, 1, 0, 2, 1, 1, 0, 2, 1, 1, 1, 2, 3, 3, 3, 1, 1, 2, 0, 1, 2, 3, 0, 2, 2, 0, 0, 4, 0, 0, 0, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 3, 0, 2, 1, 4, 0, 0, 3, 2, 0, 3, 2, 0, 2, 0, 1, 1, 1, 1, 1, 2, 2], 'learning_rate': 1.7614792950618637e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006207338004663476, 'train_segmentation_loss': 0.2971890788562227, 'val_foreground_miou_all22': 0.7522083160238224, 'val_psnr_ref1': 38.706927185058596, 'elapsed_seconds': 340.25728940963745, 'peak_cuda_allocated_gib': 7.508487701416016}

Epoch 365/500 | Batch 10/202 | Rec 0.000565 | Seg 0.335964 | Elapsed 0.2m | ETA 4.0m
Epoch 365/500 | Batch 20/202 | Rec 0.000591 | Seg 0.335336 | Elapsed 0.4m | ETA 3.9m
Epoch 365/500 | Batch 30/202 | Rec 0.000632 | Seg 0.308888 | Elapsed 0.6m | ETA 3.7m
Epoch 365/500 | Batch 40/202 | Rec 0.000620 | Seg 0.308050 | Elapsed 0.8m | ETA 3.4m
Epoch 365/500 | Batch 50/202 | Rec 0.000592 | Seg 0.296418 | Elapsed 1.1m | ETA 3.2m
Epoch 365/500 | Batch 60/202 | Rec 0.000587 | Seg 0.293551 | Elapsed 1.3m | ETA 3.0m
Epoch 365/500 | Batch 70/202 | Rec 0.000586 | Seg 0.294842 | Elapsed 1.5m | ETA 2.8m
Epoch 365/500 | Batch 80/202 | Rec 0.000584 | Seg 0.286482 | Elapsed 1.7m | ETA 2.6m
Epoch 365/500 | Batch 90/202 | Rec 0.000583 | Seg 0.287813 | Elapsed 1.9m | ETA 2.4m
Epoch 365/500 | Batch 100/202 | Rec 0.000579 | Seg 0.281280 | Elapsed 2.1m | ETA 2.1m
Epoch 365/500 | Batch 110/202 | Rec 0.000577 | Seg 0.274296 | Elapsed 2.3m | ETA 1.9m
Epoch 365/500 | Batch 120/202 | Rec 0.000579 | Seg 0.280517 | Elapsed 2.5m | ETA 1.7m
Epoch 365/500 | Batch 130/202 | Rec 0.000590 | Seg 0.284628 | Elapsed 2.7m | ETA 1.5m
Epoch 365/500 | Batch 140/202 | Rec 0.000589 | Seg 0.283253 | Elapsed 2.9m | ETA 1.3m
Epoch 365/500 | Batch 150/202 | Rec 0.000591 | Seg 0.287156 | Elapsed 3.1m | ETA 1.1m
Epoch 365/500 | Batch 160/202 | Rec 0.000592 | Seg 0.289235 | Elapsed 3.4m | ETA 0.9m
Epoch 365/500 | Batch 170/202 | Rec 0.000587 | Seg 0.287617 | Elapsed 3.6m | ETA 0.7m
Epoch 365/500 | Batch 180/202 | Rec 0.000596 | Seg 0.294282 | Elapsed 3.8m | ETA 0.5m
Epoch 365/500 | Batch 190/202 | Rec 0.000597 | Seg 0.292820 | Elapsed 4.0m | ETA 0.3m
Epoch 365/500 | Batch 200/202 | Rec 0.000597 | Seg 0.294991 | Elapsed 4.2m | ETA 0.0m
Epoch 365/500 | Batch 202/202 | Rec 0.000595 | Seg 0.293914 | Elapsed 4.2m | ETA 0.0m

2026-09-25 23:43:25,194 - INFO: Rec loss: 0.0005950365212082051
2026-09-25 23:43:25,195 - INFO: Seg loss: 0.29391368530174294
2026-09-25 23:43:25,195 - INFO: λ_rec: 1
2026-09-25 23:43:25,195 - INFO: λ_seg: 0.0001
2026-09-25 23:44:47,815 - INFO: -------------------Epoch: 365------------------------
2026-09-25 23:44:47,819 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.722111  0.974415  0.00014
2026-09-25 23:44:47,827 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995405  0.997647  0.996879  0.998516  0.995611
real potato   0.328360  0.494347  1.000000  0.328360  0.999196
fake potato   0.638574  0.779379  0.975142  0.649141  0.999732
real apple    0.670830  0.802940  0.766359  0.843299  0.998572
fake apple    0.635935  0.777410  0.983430  0.642822  0.998611
real orange   0.882101  0.937308  0.999083  0.882816  0.999845
fake orange   0.926545  0.961822  0.957680  0.966102  0.999781
real grape    0.793614  0.884884  0.974851  0.810202  0.999560
fake grape    0.887113  0.940130  0.911400  0.970837  0.999543
real lemon    0.427455  0.598861  0.446599  0.908855  0.998569
fake lemon    0.858394  0.923752  0.994923  0.862171  0.999699
real avocado  0.849404  0.918520  0.891395  0.947455  0.999844
fake avocado  0.561081  0.718791  1.000000  0.561081  0.999475
real pepper   0.833783  0.909308  0.879581  0.941223  0.999314
fake pepper   0.747963  0.855762  0.972541  0.764100  0.999386
real plant    0.864606  0.927337  0.952746  0.903344  0.998585
fake plant    0.827837  0.905760  0.916748  0.895130  0.999852
real banana   0.331180  0.497531  0.831425  0.355018  0.998389
fake banana   0.675909  0.806568  0.766410  0.851277  0.999249
real onion    0.596203  0.746977  0.708295  0.790238  0.999516
fake onion    0.862542  0.926149  0.994725  0.866505  0.999913
real unknown  0.911259  0.953520  1.000000  0.911259  0.999986
fake unknown  0.227250  0.370306  0.238468  0.828504  0.997626
total         0.710145  0.810218  0.876464  0.803403  0.999124
total(-bg)    0.697179  0.801698  0.870991  0.794534  0.999284
2026-09-25 23:44:48,372 - INFO: Epoch accounting: {'epoch': 365, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11215265, 34657, 45372, 153132, 139728, 87234, 79211, 209367, 187834, 102480, 96457, 35754, 53237, 234317, 137485, 90669, 23463, 99577, 62868, 63698, 29714, 10633, 46120], 'crops_with_class': [202, 24, 20, 38, 41, 28, 27, 36, 43, 38, 40, 11, 18, 51, 30, 14, 20, 26, 28, 30, 18, 12, 19], 'targeted_crops_by_class': [0, 5, 2, 3, 4, 7, 2, 8, 6, 3, 7, 4, 6, 5, 7, 3, 5, 6, 3, 4, 2, 5, 3], 'sampled_scene_counts': [1, 1, 0, 0, 1, 0, 1, 1, 2, 1, 1, 0, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 4, 0, 2, 0, 0, 2, 2, 2, 4, 2, 2, 3, 1, 2, 4, 2, 0, 2, 1, 1, 1, 0, 1, 0, 2, 1, 3, 1, 1, 1, 1, 0, 1, 1, 3, 2, 2, 5, 0, 4, 2, 1, 0, 1, 1, 1, 2, 0, 0, 1, 2, 2, 3, 2, 0, 1, 1, 0, 2, 2, 0, 1, 3, 2, 1, 1, 0, 2, 2, 3, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0], 'learning_rate': 1.7377785431821276e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0005950365212082051, 'train_segmentation_loss': 0.29391368530174294, 'val_foreground_miou_all22': 0.6971790469988476, 'val_psnr_ref1': 38.722111206054684, 'elapsed_seconds': 337.3674244880676, 'peak_cuda_allocated_gib': 7.505924224853516}

Epoch 366/500 | Batch 10/202 | Rec 0.000557 | Seg 0.222401 | Elapsed 0.2m | ETA 4.2m
Epoch 366/500 | Batch 20/202 | Rec 0.000585 | Seg 0.276576 | Elapsed 0.4m | ETA 3.9m
Epoch 366/500 | Batch 30/202 | Rec 0.000568 | Seg 0.269193 | Elapsed 0.6m | ETA 3.7m
Epoch 366/500 | Batch 40/202 | Rec 0.000564 | Seg 0.259696 | Elapsed 0.8m | ETA 3.4m
Epoch 366/500 | Batch 50/202 | Rec 0.000558 | Seg 0.257340 | Elapsed 1.1m | ETA 3.2m
Epoch 366/500 | Batch 60/202 | Rec 0.000570 | Seg 0.259050 | Elapsed 1.3m | ETA 3.0m
Epoch 366/500 | Batch 70/202 | Rec 0.000567 | Seg 0.266482 | Elapsed 1.5m | ETA 2.8m
Epoch 366/500 | Batch 80/202 | Rec 0.000569 | Seg 0.270186 | Elapsed 1.7m | ETA 2.6m
Epoch 366/500 | Batch 90/202 | Rec 0.000579 | Seg 0.275460 | Elapsed 1.9m | ETA 2.3m
Epoch 366/500 | Batch 100/202 | Rec 0.000572 | Seg 0.275290 | Elapsed 2.1m | ETA 2.1m
Epoch 366/500 | Batch 110/202 | Rec 0.000592 | Seg 0.277690 | Elapsed 2.3m | ETA 1.9m
Epoch 366/500 | Batch 120/202 | Rec 0.000590 | Seg 0.276286 | Elapsed 2.5m | ETA 1.7m
Epoch 366/500 | Batch 130/202 | Rec 0.000585 | Seg 0.279274 | Elapsed 2.7m | ETA 1.5m
Epoch 366/500 | Batch 140/202 | Rec 0.000595 | Seg 0.287508 | Elapsed 2.9m | ETA 1.3m
Epoch 366/500 | Batch 150/202 | Rec 0.000601 | Seg 0.287588 | Elapsed 3.1m | ETA 1.1m
Epoch 366/500 | Batch 160/202 | Rec 0.000603 | Seg 0.288807 | Elapsed 3.4m | ETA 0.9m
Epoch 366/500 | Batch 170/202 | Rec 0.000599 | Seg 0.288336 | Elapsed 3.6m | ETA 0.7m
Epoch 366/500 | Batch 180/202 | Rec 0.000605 | Seg 0.291587 | Elapsed 3.8m | ETA 0.5m
Epoch 366/500 | Batch 190/202 | Rec 0.000601 | Seg 0.290660 | Elapsed 4.0m | ETA 0.3m
Epoch 366/500 | Batch 200/202 | Rec 0.000598 | Seg 0.291361 | Elapsed 4.2m | ETA 0.0m
Epoch 366/500 | Batch 202/202 | Rec 0.000598 | Seg 0.292102 | Elapsed 4.2m | ETA 0.0m

2026-09-25 23:49:02,486 - INFO: Rec loss: 0.0005978904834528924
2026-09-25 23:49:02,486 - INFO: Seg loss: 0.29210236707314996
2026-09-25 23:49:02,486 - INFO: λ_rec: 1
2026-09-25 23:49:02,486 - INFO: λ_seg: 0.0001
2026-09-25 23:50:24,211 - INFO: -------------------Epoch: 366------------------------
2026-09-25 23:50:24,215 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.744377  0.97459  0.000139
2026-09-25 23:50:24,223 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995602  0.997746  0.997063  0.998530  0.995800
real potato   0.918792  0.957628  0.942025  0.973859  0.999897
fake potato   0.949888  0.974250  0.967955  0.980729  0.999962
real apple    0.737446  0.848836  0.980866  0.748209  0.999081
fake apple    0.614034  0.760822  0.982974  0.620635  0.998527
real orange   0.815273  0.898188  0.997174  0.817161  0.999756
fake orange   0.895885  0.945034  0.914089  0.978254  0.999675
real grape    0.716111  0.834525  0.934990  0.753636  0.999376
fake grape    0.904840  0.949993  0.940143  0.960153  0.999626
real lemon    0.685457  0.813328  0.797009  0.830434  0.999552
fake lemon    0.832168  0.908348  0.998962  0.832889  0.999645
real avocado  0.949870  0.974241  0.987519  0.961412  0.999953
fake avocado  0.548585  0.708452  1.000000  0.548585  0.999460
real pepper   0.862243  0.925977  0.887398  0.968171  0.999434
fake pepper   0.790867  0.883173  0.967164  0.812688  0.999488
real plant    0.855456  0.922048  0.938485  0.906273  0.998468
fake plant    0.784558  0.879225  0.834395  0.929256  0.999797
real banana   0.716271  0.834633  0.906148  0.773666  0.999311
fake banana   0.654383  0.791040  0.735510  0.855756  0.999169
real onion    0.559267  0.717300  0.571128  0.964195  0.999314
fake onion    0.922309  0.959535  0.981294  0.938815  0.999950
real unknown  0.614942  0.761517  0.650236  0.918893  0.999908
fake unknown  0.218847  0.359068  0.240054  0.712423  0.997857
total         0.762743  0.852387  0.876199  0.860201  0.999261
total(-bg)    0.752159  0.845780  0.870705  0.853913  0.999418
2026-09-25 23:50:24,766 - INFO: Epoch accounting: {'epoch': 366, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11233646, 53729, 60262, 145199, 136198, 93473, 79825, 167557, 235946, 65210, 64034, 44456, 26750, 215202, 135218, 134208, 31121, 70387, 82117, 62138, 50334, 9201, 42061], 'crops_with_class': [202, 29, 27, 42, 35, 28, 27, 27, 44, 29, 28, 14, 12, 55, 33, 20, 27, 23, 30, 31, 22, 11, 21], 'targeted_crops_by_class': [0, 3, 5, 5, 5, 3, 2, 9, 3, 5, 3, 3, 2, 5, 4, 5, 7, 5, 3, 4, 5, 5, 8], 'sampled_scene_counts': [1, 2, 0, 1, 1, 1, 1, 0, 1, 2, 2, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 3, 0, 2, 1, 2, 1, 0, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0, 1, 1, 1, 0, 1, 2, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 2, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 3, 1, 0, 0, 1, 2, 2, 1, 3, 1, 1, 3, 2, 2, 0, 1, 2, 3, 3, 1, 0, 2, 3, 1, 1, 2, 0, 4, 3, 1, 2, 2, 1, 0, 1, 1, 1, 3, 2, 0, 0, 2, 2, 1, 3, 1, 0, 0, 1, 1, 3, 2, 1, 1, 0, 1, 1, 1, 2, 2, 0, 1, 0, 1, 3, 0, 1, 1, 3, 1, 5, 0, 3, 0, 1, 1, 0, 0, 0, 1, 1, 2, 0, 4], 'learning_rate': 1.7142070716982827e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005978904834528924, 'train_segmentation_loss': 0.29210236707314996, 'val_foreground_miou_all22': 0.7521587917983994, 'val_psnr_ref1': 38.74437744140625, 'elapsed_seconds': 336.3859512805939, 'peak_cuda_allocated_gib': 7.5099334716796875}

Epoch 367/500 | Batch 10/202 | Rec 0.000534 | Seg 0.296678 | Elapsed 0.2m | ETA 3.8m
Epoch 367/500 | Batch 20/202 | Rec 0.000572 | Seg 0.291854 | Elapsed 0.4m | ETA 3.7m
Epoch 367/500 | Batch 30/202 | Rec 0.000599 | Seg 0.293078 | Elapsed 0.6m | ETA 3.5m
Epoch 367/500 | Batch 40/202 | Rec 0.000628 | Seg 0.304415 | Elapsed 0.8m | ETA 3.3m
Epoch 367/500 | Batch 50/202 | Rec 0.000631 | Seg 0.298437 | Elapsed 1.0m | ETA 3.1m
Epoch 367/500 | Batch 60/202 | Rec 0.000606 | Seg 0.288992 | Elapsed 1.2m | ETA 3.0m
Epoch 367/500 | Batch 70/202 | Rec 0.000604 | Seg 0.290862 | Elapsed 1.4m | ETA 2.7m
Epoch 367/500 | Batch 80/202 | Rec 0.000606 | Seg 0.286862 | Elapsed 1.7m | ETA 2.5m
Epoch 367/500 | Batch 90/202 | Rec 0.000610 | Seg 0.287293 | Elapsed 1.9m | ETA 2.3m
Epoch 367/500 | Batch 100/202 | Rec 0.000610 | Seg 0.289272 | Elapsed 2.1m | ETA 2.1m
Epoch 367/500 | Batch 110/202 | Rec 0.000607 | Seg 0.284156 | Elapsed 2.3m | ETA 1.9m
Epoch 367/500 | Batch 120/202 | Rec 0.000603 | Seg 0.284675 | Elapsed 2.5m | ETA 1.7m
Epoch 367/500 | Batch 130/202 | Rec 0.000605 | Seg 0.285290 | Elapsed 2.7m | ETA 1.5m
Epoch 367/500 | Batch 140/202 | Rec 0.000608 | Seg 0.287525 | Elapsed 2.9m | ETA 1.3m
Epoch 367/500 | Batch 150/202 | Rec 0.000607 | Seg 0.287097 | Elapsed 3.1m | ETA 1.1m
Epoch 367/500 | Batch 160/202 | Rec 0.000606 | Seg 0.289207 | Elapsed 3.3m | ETA 0.9m
Epoch 367/500 | Batch 170/202 | Rec 0.000601 | Seg 0.287899 | Elapsed 3.5m | ETA 0.7m
Epoch 367/500 | Batch 180/202 | Rec 0.000595 | Seg 0.285479 | Elapsed 3.8m | ETA 0.5m
Epoch 367/500 | Batch 190/202 | Rec 0.000595 | Seg 0.282791 | Elapsed 4.0m | ETA 0.3m
Epoch 367/500 | Batch 200/202 | Rec 0.000600 | Seg 0.283067 | Elapsed 4.2m | ETA 0.0m
Epoch 367/500 | Batch 202/202 | Rec 0.000606 | Seg 0.285886 | Elapsed 4.2m | ETA 0.0m

2026-09-25 23:54:38,226 - INFO: Rec loss: 0.0006055259326614652
2026-09-25 23:54:38,226 - INFO: Seg loss: 0.2858862721979028
2026-09-25 23:54:38,226 - INFO: λ_rec: 1
2026-09-25 23:54:38,226 - INFO: λ_seg: 0.0001
2026-09-25 23:55:58,294 - INFO: -------------------Epoch: 367------------------------
2026-09-25 23:55:58,298 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.863193  0.974707  0.000136
2026-09-25 23:55:58,306 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995668  0.997779  0.996887  0.998773  0.995863
real potato   0.847591  0.917459  0.864113  0.977939  0.999790
fake potato   0.940837  0.969467  0.950493  0.989317  0.999955
real apple    0.682901  0.811528  0.993657  0.685891  0.998901
fake apple    0.559672  0.717633  0.989908  0.562884  0.998328
real orange   0.793561  0.884851  0.995657  0.796318  0.999727
fake orange   0.885695  0.939333  0.903029  0.978787  0.999638
real grape    0.745199  0.853949  0.939556  0.782723  0.999441
fake grape    0.886382  0.939719  0.954832  0.925174  0.999561
real lemon    0.707317  0.828522  0.879557  0.783173  0.999619
fake lemon    0.826866  0.905180  0.997741  0.828417  0.999633
real avocado  0.931080  0.964260  0.999296  0.931691  0.999936
fake avocado  0.276333  0.432976  1.000000  0.276333  0.999134
real pepper   0.904441  0.949773  0.926430  0.974428  0.999623
fake pepper   0.869712  0.930267  0.955094  0.906792  0.999676
real plant    0.864566  0.927314  0.954673  0.901574  0.998587
fake plant    0.736489  0.848201  0.783371  0.924847  0.999737
real banana   0.774788  0.873055  0.899180  0.848499  0.999446
fake banana   0.656686  0.792721  0.733611  0.862309  0.999171
real onion    0.569272  0.725477  0.580162  0.968080  0.999338
fake onion    0.944681  0.971504  0.976778  0.966384  0.999964
real unknown  0.614341  0.761056  0.655410  0.907443  0.999909
fake unknown  0.185022  0.312234  0.200829  0.701557  0.997396
total         0.747787  0.837142  0.875229  0.846928  0.999234
total(-bg)    0.736520  0.829840  0.869699  0.840026  0.999387
2026-09-25 23:55:58,899 - INFO: Epoch accounting: {'epoch': 367, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11295289, 53942, 77073, 148633, 158816, 79402, 71624, 137782, 142520, 77237, 65395, 34386, 18651, 228251, 110055, 155407, 33452, 106368, 79474, 64319, 52635, 8982, 38579], 'crops_with_class': [202, 32, 35, 41, 38, 26, 29, 32, 30, 37, 28, 12, 7, 55, 30, 25, 27, 30, 33, 34, 24, 9, 20], 'targeted_crops_by_class': [0, 8, 5, 8, 3, 5, 3, 4, 6, 2, 7, 3, 4, 5, 5, 7, 9, 5, 5, 3, 1, 2, 4], 'sampled_scene_counts': [0, 1, 1, 0, 2, 1, 0, 2, 3, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 2, 1, 1, 2, 1, 1, 0, 1, 0, 3, 0, 1, 1, 0, 1, 3, 2, 0, 0, 1, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 0, 0, 2, 0, 0, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 2, 0, 3, 3, 1, 2, 1, 0, 1, 2, 2, 1, 2, 2, 2, 2, 0, 3, 0, 1, 0, 0, 1, 2, 0, 0, 2, 2, 1, 1, 1, 1, 2, 4, 2, 3, 1, 1, 2, 2, 1, 3, 1, 2, 2, 1, 2, 1, 0, 1, 0, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 4, 1, 2, 1, 2, 1, 1, 3, 3, 1, 1, 0, 2, 2, 1, 2, 0, 2], 'learning_rate': 1.6907658111716676e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006055259326614652, 'train_segmentation_loss': 0.2858862721979028, 'val_foreground_miou_all22': 0.736519568752362, 'val_psnr_ref1': 38.86319274902344, 'elapsed_seconds': 334.12477469444275, 'peak_cuda_allocated_gib': 7.509799957275391}

Epoch 368/500 | Batch 10/202 | Rec 0.000675 | Seg 0.264375 | Elapsed 0.2m | ETA 4.1m
Epoch 368/500 | Batch 20/202 | Rec 0.000573 | Seg 0.247252 | Elapsed 0.4m | ETA 3.9m
Epoch 368/500 | Batch 30/202 | Rec 0.000566 | Seg 0.265594 | Elapsed 0.6m | ETA 3.7m
Epoch 368/500 | Batch 40/202 | Rec 0.000586 | Seg 0.289673 | Elapsed 0.8m | ETA 3.4m
Epoch 368/500 | Batch 50/202 | Rec 0.000620 | Seg 0.287114 | Elapsed 1.0m | ETA 3.2m
Epoch 368/500 | Batch 60/202 | Rec 0.000612 | Seg 0.279792 | Elapsed 1.3m | ETA 3.0m
Epoch 368/500 | Batch 70/202 | Rec 0.000608 | Seg 0.285703 | Elapsed 1.5m | ETA 2.8m
Epoch 368/500 | Batch 80/202 | Rec 0.000613 | Seg 0.289736 | Elapsed 1.7m | ETA 2.6m
Epoch 368/500 | Batch 90/202 | Rec 0.000616 | Seg 0.290616 | Elapsed 1.9m | ETA 2.3m
Epoch 368/500 | Batch 100/202 | Rec 0.000622 | Seg 0.296508 | Elapsed 2.1m | ETA 2.1m
Epoch 368/500 | Batch 110/202 | Rec 0.000617 | Seg 0.298489 | Elapsed 2.3m | ETA 1.9m
Epoch 368/500 | Batch 120/202 | Rec 0.000616 | Seg 0.293809 | Elapsed 2.5m | ETA 1.7m
Epoch 368/500 | Batch 130/202 | Rec 0.000616 | Seg 0.291968 | Elapsed 2.7m | ETA 1.5m
Epoch 368/500 | Batch 140/202 | Rec 0.000610 | Seg 0.287500 | Elapsed 2.9m | ETA 1.3m
Epoch 368/500 | Batch 150/202 | Rec 0.000606 | Seg 0.286884 | Elapsed 3.1m | ETA 1.1m
Epoch 368/500 | Batch 160/202 | Rec 0.000613 | Seg 0.288093 | Elapsed 3.4m | ETA 0.9m
Epoch 368/500 | Batch 170/202 | Rec 0.000614 | Seg 0.287357 | Elapsed 3.6m | ETA 0.7m
Epoch 368/500 | Batch 180/202 | Rec 0.000619 | Seg 0.289922 | Elapsed 3.8m | ETA 0.5m
Epoch 368/500 | Batch 190/202 | Rec 0.000630 | Seg 0.290346 | Elapsed 4.0m | ETA 0.3m
Epoch 368/500 | Batch 200/202 | Rec 0.000626 | Seg 0.290563 | Elapsed 4.2m | ETA 0.0m
Epoch 368/500 | Batch 202/202 | Rec 0.000627 | Seg 0.291597 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:00:12,311 - INFO: Rec loss: 0.0006274237729134131
2026-09-26 00:00:12,311 - INFO: Seg loss: 0.29159692872204995
2026-09-26 00:00:12,311 - INFO: λ_rec: 1
2026-09-26 00:00:12,311 - INFO: λ_seg: 0.0001
2026-09-26 00:01:32,598 - INFO: -------------------Epoch: 368------------------------
2026-09-26 00:01:32,603 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.886259  0.974357  0.000135
2026-09-26 00:01:32,611 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995928  0.997910  0.997473  0.998448  0.996114
real potato   0.868979  0.929847  0.975897  0.888039  0.999840
fake potato   0.791317  0.883453  0.972565  0.809384  0.999845
real apple    0.788160  0.881482  0.945641  0.825564  0.999234
fake apple    0.588322  0.740763  0.984783  0.593720  0.998431
real orange   0.902839  0.948889  0.996180  0.905975  0.999872
fake orange   0.933560  0.965588  0.949279  0.982571  0.999800
real grape    0.809142  0.894454  0.955410  0.840897  0.999586
fake grape    0.895071  0.944580  0.918583  0.972198  0.999578
real lemon    0.628958  0.772172  0.666290  0.918203  0.999363
fake lemon    0.862508  0.926129  0.997172  0.864623  0.999708
real avocado  0.919887  0.958222  0.954990  0.961576  0.999922
fake avocado  0.561321  0.718987  0.999546  0.561464  0.999475
real pepper   0.889333  0.941375  0.917955  0.966127  0.999560
fake pepper   0.840355  0.913203  0.964672  0.867038  0.999607
real plant    0.877087  0.934469  0.952116  0.917562  0.998714
fake plant    0.870116  0.930497  0.939086  0.922163  0.999890
real banana   0.640475  0.780792  0.913324  0.681923  0.999140
fake banana   0.713858  0.832992  0.799497  0.869526  0.999359
real onion    0.648332  0.786604  0.678589  0.935653  0.999541
fake onion    0.905162  0.950171  0.992105  0.911729  0.999940
real unknown  0.756654  0.861422  0.788431  0.949427  0.999951
fake unknown  0.203874  0.338662  0.216936  0.772003  0.997460
total         0.777880  0.862290  0.890283  0.865905  0.999301
total(-bg)    0.767969  0.856125  0.885411  0.859880  0.999446
2026-09-26 00:01:33,238 - INFO: Epoch accounting: {'epoch': 368, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11228658, 53638, 63788, 115268, 98217, 65851, 78966, 145761, 177069, 90428, 67106, 37993, 35784, 305606, 151335, 143637, 20600, 66544, 82434, 104223, 52124, 7293, 45949], 'crops_with_class': [202, 31, 31, 36, 27, 20, 30, 24, 34, 40, 30, 17, 18, 73, 32, 20, 18, 21, 36, 40, 28, 7, 19], 'targeted_crops_by_class': [0, 5, 4, 5, 4, 4, 5, 4, 5, 5, 4, 9, 4, 5, 5, 3, 4, 8, 11, 2, 6, 4, 6], 'sampled_scene_counts': [2, 1, 2, 1, 1, 1, 1, 0, 0, 3, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 2, 0, 0, 0, 1, 1, 1, 0, 0, 3, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 3, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 1, 2, 0, 2, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 2, 0, 4, 2, 1, 2, 1, 0, 2, 1, 1, 0, 2, 3, 2, 3, 2, 0, 1, 0, 2, 1, 2, 2, 1, 1, 1, 3, 0, 3, 1, 1, 1, 3, 0, 2, 3, 2, 0, 1, 1, 0, 1, 2, 3, 0, 2, 0, 1, 3, 2, 0, 0, 0, 2, 1, 3, 1, 3, 2, 1, 2, 1, 2, 6, 0, 0, 2, 1, 1, 3, 1, 2, 0, 2, 2], 'learning_rate': 1.6674556870231063e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006274237729134131, 'train_segmentation_loss': 0.29159692872204995, 'val_foreground_miou_all22': 0.7679685300127965, 'val_psnr_ref1': 38.886258850097654, 'elapsed_seconds': 334.3307204246521, 'peak_cuda_allocated_gib': 7.509067535400391}

Epoch 369/500 | Batch 10/202 | Rec 0.000472 | Seg 0.264811 | Elapsed 0.2m | ETA 4.2m
Epoch 369/500 | Batch 20/202 | Rec 0.000546 | Seg 0.266683 | Elapsed 0.4m | ETA 4.0m
Epoch 369/500 | Batch 30/202 | Rec 0.000524 | Seg 0.259758 | Elapsed 0.6m | ETA 3.7m
Epoch 369/500 | Batch 40/202 | Rec 0.000522 | Seg 0.255627 | Elapsed 0.9m | ETA 3.5m
Epoch 369/500 | Batch 50/202 | Rec 0.000535 | Seg 0.266788 | Elapsed 1.1m | ETA 3.2m
Epoch 369/500 | Batch 60/202 | Rec 0.000545 | Seg 0.276698 | Elapsed 1.3m | ETA 3.0m
Epoch 369/500 | Batch 70/202 | Rec 0.000570 | Seg 0.277806 | Elapsed 1.5m | ETA 2.8m
Epoch 369/500 | Batch 80/202 | Rec 0.000585 | Seg 0.280343 | Elapsed 1.7m | ETA 2.6m
Epoch 369/500 | Batch 90/202 | Rec 0.000581 | Seg 0.282605 | Elapsed 1.9m | ETA 2.4m
Epoch 369/500 | Batch 100/202 | Rec 0.000580 | Seg 0.280938 | Elapsed 2.1m | ETA 2.1m
Epoch 369/500 | Batch 110/202 | Rec 0.000589 | Seg 0.282423 | Elapsed 2.3m | ETA 1.9m
Epoch 369/500 | Batch 120/202 | Rec 0.000584 | Seg 0.279060 | Elapsed 2.5m | ETA 1.7m
Epoch 369/500 | Batch 130/202 | Rec 0.000586 | Seg 0.278820 | Elapsed 2.7m | ETA 1.5m
Epoch 369/500 | Batch 140/202 | Rec 0.000587 | Seg 0.281257 | Elapsed 2.9m | ETA 1.3m
Epoch 369/500 | Batch 150/202 | Rec 0.000582 | Seg 0.281053 | Elapsed 3.1m | ETA 1.1m
Epoch 369/500 | Batch 160/202 | Rec 0.000590 | Seg 0.279868 | Elapsed 3.3m | ETA 0.9m
Epoch 369/500 | Batch 170/202 | Rec 0.000585 | Seg 0.278790 | Elapsed 3.5m | ETA 0.7m
Epoch 369/500 | Batch 180/202 | Rec 0.000599 | Seg 0.281136 | Elapsed 3.8m | ETA 0.5m
Epoch 369/500 | Batch 190/202 | Rec 0.000598 | Seg 0.281256 | Elapsed 4.0m | ETA 0.3m
Epoch 369/500 | Batch 200/202 | Rec 0.000602 | Seg 0.279670 | Elapsed 4.2m | ETA 0.0m
Epoch 369/500 | Batch 202/202 | Rec 0.000602 | Seg 0.279932 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:05:46,578 - INFO: Rec loss: 0.0006024020315248215
2026-09-26 00:05:46,578 - INFO: Seg loss: 0.27993225671424726
2026-09-26 00:05:46,578 - INFO: λ_rec: 1
2026-09-26 00:05:46,579 - INFO: λ_seg: 0.0001
2026-09-26 00:07:09,980 - INFO: -------------------Epoch: 369------------------------
2026-09-26 00:07:09,984 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.749492  0.974044  0.000139
2026-09-26 00:07:09,992 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995472  0.997681  0.996648  0.998816  0.995674
real potato   0.919450  0.957985  0.961232  0.954858  0.999900
fake potato   0.955010  0.976937  0.975763  0.978215  0.999966
real apple    0.732466  0.845527  0.978267  0.744582  0.999062
fake apple    0.607389  0.755699  0.987993  0.611906  0.998507
real orange   0.930644  0.964026  0.998140  0.932260  0.999908
fake orange   0.932888  0.965229  0.962975  0.967594  0.999801
real grape    0.763756  0.866007  0.936523  0.805452  0.999480
fake grape    0.909601  0.952611  0.949480  0.955864  0.999649
real lemon    0.675816  0.806503  0.713786  0.927032  0.999477
fake lemon    0.804857  0.891830  0.998927  0.805554  0.999587
real avocado  0.951056  0.974864  0.996740  0.954023  0.999954
fake avocado  0.770015  0.870017  0.999669  0.770212  0.999725
real pepper   0.892959  0.943403  0.918127  0.970215  0.999575
fake pepper   0.830037  0.907076  0.950102  0.867870  0.999576
real plant    0.850694  0.919274  0.954599  0.886563  0.998444
fake plant    0.811440  0.895856  0.859458  0.935583  0.999827
real banana   0.667406  0.800483  0.943922  0.694961  0.999222
fake banana   0.670517  0.802716  0.766486  0.842651  0.999238
real onion    0.604205  0.753228  0.623464  0.951360  0.999437
fake onion    0.916547  0.956407  0.987887  0.926965  0.999947
real unknown  0.508052  0.673740  0.527224  0.933206  0.999855
fake unknown  0.227204  0.370239  0.254658  0.678196  0.998056
total         0.779456  0.862928  0.880090  0.873649  0.999299
total(-bg)    0.769637  0.856803  0.874792  0.867960  0.999463
2026-09-26 00:07:10,639 - INFO: Epoch accounting: {'epoch': 369, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11283520, 52886, 58039, 113000, 159434, 105831, 76398, 115825, 193902, 68655, 77803, 40545, 48061, 230872, 124148, 88278, 26282, 82500, 75594, 112777, 63983, 8083, 31856], 'crops_with_class': [202, 35, 25, 33, 39, 34, 26, 26, 35, 29, 27, 14, 14, 54, 32, 11, 23, 27, 28, 43, 29, 9, 15], 'targeted_crops_by_class': [0, 6, 5, 6, 3, 4, 3, 4, 6, 7, 9, 5, 4, 2, 7, 3, 6, 1, 7, 12, 5, 3, 6], 'sampled_scene_counts': [0, 3, 1, 0, 2, 1, 1, 1, 3, 2, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 2, 3, 0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 2, 0, 0, 1, 2, 2, 0, 3, 0, 2, 1, 0, 2, 4, 2, 5, 2, 0, 3, 2, 2, 2, 1, 1, 2, 1, 3, 1, 1, 0, 3, 1, 1, 1, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 2, 2, 1, 2, 2, 0, 1, 1, 3, 0, 3, 0, 1, 0, 1, 3, 3, 2, 0, 2, 2, 0, 2, 0, 3, 0, 1, 1, 1, 3, 1, 5, 2], 'learning_rate': 1.644277619496388e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006024020315248215, 'train_segmentation_loss': 0.27993225671424726, 'val_foreground_miou_all22': 0.7696367567517531, 'val_psnr_ref1': 38.74949172973633, 'elapsed_seconds': 337.3923683166504, 'peak_cuda_allocated_gib': 7.512729644775391}

Epoch 370/500 | Batch 10/202 | Rec 0.000624 | Seg 0.216087 | Elapsed 0.2m | ETA 4.2m
Epoch 370/500 | Batch 20/202 | Rec 0.000661 | Seg 0.252637 | Elapsed 0.4m | ETA 3.9m
Epoch 370/500 | Batch 30/202 | Rec 0.000610 | Seg 0.254237 | Elapsed 0.6m | ETA 3.7m
Epoch 370/500 | Batch 40/202 | Rec 0.000596 | Seg 0.264788 | Elapsed 0.8m | ETA 3.4m
Epoch 370/500 | Batch 50/202 | Rec 0.000596 | Seg 0.273051 | Elapsed 1.0m | ETA 3.2m
Epoch 370/500 | Batch 60/202 | Rec 0.000599 | Seg 0.280025 | Elapsed 1.3m | ETA 3.0m
Epoch 370/500 | Batch 70/202 | Rec 0.000605 | Seg 0.275936 | Elapsed 1.5m | ETA 2.8m
Epoch 370/500 | Batch 80/202 | Rec 0.000590 | Seg 0.277412 | Elapsed 1.7m | ETA 2.6m
Epoch 370/500 | Batch 90/202 | Rec 0.000603 | Seg 0.285856 | Elapsed 1.9m | ETA 2.3m
Epoch 370/500 | Batch 100/202 | Rec 0.000598 | Seg 0.288250 | Elapsed 2.1m | ETA 2.1m
Epoch 370/500 | Batch 110/202 | Rec 0.000592 | Seg 0.284152 | Elapsed 2.3m | ETA 1.9m
Epoch 370/500 | Batch 120/202 | Rec 0.000585 | Seg 0.279155 | Elapsed 2.5m | ETA 1.7m
Epoch 370/500 | Batch 130/202 | Rec 0.000588 | Seg 0.281730 | Elapsed 2.7m | ETA 1.5m
Epoch 370/500 | Batch 140/202 | Rec 0.000585 | Seg 0.281848 | Elapsed 2.9m | ETA 1.3m
Epoch 370/500 | Batch 150/202 | Rec 0.000583 | Seg 0.279861 | Elapsed 3.1m | ETA 1.1m
Epoch 370/500 | Batch 160/202 | Rec 0.000589 | Seg 0.282625 | Elapsed 3.4m | ETA 0.9m
Epoch 370/500 | Batch 170/202 | Rec 0.000591 | Seg 0.280332 | Elapsed 3.6m | ETA 0.7m
Epoch 370/500 | Batch 180/202 | Rec 0.000596 | Seg 0.283105 | Elapsed 3.8m | ETA 0.5m
Epoch 370/500 | Batch 190/202 | Rec 0.000594 | Seg 0.282811 | Elapsed 4.0m | ETA 0.3m
Epoch 370/500 | Batch 200/202 | Rec 0.000591 | Seg 0.284613 | Elapsed 4.2m | ETA 0.0m
Epoch 370/500 | Batch 202/202 | Rec 0.000596 | Seg 0.283643 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:11:25,349 - INFO: Rec loss: 0.0005962920009497423
2026-09-26 00:11:25,349 - INFO: Seg loss: 0.28364310752932387
2026-09-26 00:11:25,349 - INFO: λ_rec: 1
2026-09-26 00:11:25,349 - INFO: λ_seg: 0.0001
2026-09-26 00:12:45,758 - INFO: -------------------Epoch: 370------------------------
2026-09-26 00:12:45,763 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.771251  0.974398  0.000138
2026-09-26 00:12:45,771 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995717  0.997804  0.997184  0.998524  0.995911
real potato   0.778223  0.875232  0.976751  0.792910  0.999730
fake potato   0.947250  0.972861  0.975368  0.970465  0.999961
real apple    0.796675  0.886783  0.917285  0.858337  0.999244
fake apple    0.619695  0.765152  0.988104  0.624353  0.998553
real orange   0.956261  0.977591  0.996512  0.959472  0.999942
fake orange   0.945328  0.971846  0.971508  0.972284  0.999839
real grape    0.837219  0.911348  0.971698  0.858145  0.999652
fake grape    0.896414  0.945328  0.930314  0.960937  0.999589
real lemon    0.560368  0.718203  0.586797  0.925604  0.999147
fake lemon    0.847632  0.917484  0.997544  0.849405  0.999677
real avocado  0.918863  0.957666  0.959611  0.955829  0.999922
fake avocado  0.791433  0.883526  0.999678  0.791635  0.999750
real pepper   0.806935  0.893104  0.835678  0.959119  0.999161
fake pepper   0.701580  0.824573  0.956566  0.724666  0.999265
real plant    0.874711  0.933119  0.955820  0.911566  0.998694
fake plant    0.870550  0.930746  0.933308  0.928298  0.999890
real banana   0.531762  0.694267  0.876813  0.574698  0.998863
fake banana   0.724781  0.840382  0.823956  0.857581  0.999401
real onion    0.663139  0.797406  0.697269  0.931262  0.999573
fake onion    0.940010  0.969027  0.987695  0.951149  0.999962
real unknown  0.829351  0.906666  0.886861  0.927481  0.999969
fake unknown  0.244840  0.393329  0.266359  0.751901  0.998046
total         0.786032  0.867976  0.890812  0.871114  0.999293
total(-bg)    0.776501  0.862075  0.885977  0.865323  0.999447
2026-09-26 00:12:46,348 - INFO: Epoch accounting: {'epoch': 370, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11315780, 53048, 63558, 136686, 124267, 63897, 47241, 103188, 197233, 62611, 47465, 49847, 38972, 229152, 144402, 138939, 32549, 117801, 65734, 77851, 75117, 13876, 39058], 'crops_with_class': [202, 33, 32, 30, 35, 16, 19, 24, 34, 27, 23, 17, 16, 57, 43, 17, 29, 32, 28, 35, 29, 13, 19], 'targeted_crops_by_class': [0, 6, 6, 4, 9, 5, 2, 3, 5, 5, 1, 4, 5, 7, 2, 2, 5, 7, 3, 8, 3, 4, 5], 'sampled_scene_counts': [1, 0, 0, 1, 2, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 3, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 1, 2, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 3, 1, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 2, 1, 1, 1, 2, 1, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 2, 0, 1, 1, 2, 1, 2, 0, 1, 0, 2, 1, 1, 1, 0, 1, 3, 0, 2, 0, 4, 1, 2, 1, 1, 2, 1, 1, 2, 0, 0, 0, 2, 1, 1, 3, 3, 2, 0, 2, 1, 4, 0, 4, 0, 1, 4, 0, 1, 0, 2, 1, 2, 5, 2, 2, 2, 0, 1, 5, 3, 1, 2, 0, 2, 2, 1, 1, 1, 3, 0, 2, 3, 0, 1, 0, 1, 0, 0, 3, 3, 1], 'learning_rate': 1.6212325236219317e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005962920009497423, 'train_segmentation_loss': 0.28364310752932387, 'val_foreground_miou_all22': 0.7765009623862125, 'val_psnr_ref1': 38.77125076293945, 'elapsed_seconds': 335.70033526420593, 'peak_cuda_allocated_gib': 7.512760162353516}

Epoch 371/500 | Batch 10/202 | Rec 0.000479 | Seg 0.224995 | Elapsed 0.2m | ETA 4.1m
Epoch 371/500 | Batch 20/202 | Rec 0.000522 | Seg 0.276783 | Elapsed 0.4m | ETA 3.8m
Epoch 371/500 | Batch 30/202 | Rec 0.000538 | Seg 0.261230 | Elapsed 0.6m | ETA 3.6m
Epoch 371/500 | Batch 40/202 | Rec 0.000533 | Seg 0.250751 | Elapsed 0.8m | ETA 3.4m
Epoch 371/500 | Batch 50/202 | Rec 0.000534 | Seg 0.255946 | Elapsed 1.0m | ETA 3.2m
Epoch 371/500 | Batch 60/202 | Rec 0.000552 | Seg 0.277340 | Elapsed 1.3m | ETA 3.0m
Epoch 371/500 | Batch 70/202 | Rec 0.000544 | Seg 0.270976 | Elapsed 1.5m | ETA 2.8m
Epoch 371/500 | Batch 80/202 | Rec 0.000541 | Seg 0.265350 | Elapsed 1.7m | ETA 2.6m
Epoch 371/500 | Batch 90/202 | Rec 0.000560 | Seg 0.273830 | Elapsed 1.9m | ETA 2.3m
Epoch 371/500 | Batch 100/202 | Rec 0.000562 | Seg 0.277034 | Elapsed 2.1m | ETA 2.1m
Epoch 371/500 | Batch 110/202 | Rec 0.000562 | Seg 0.273671 | Elapsed 2.3m | ETA 1.9m
Epoch 371/500 | Batch 120/202 | Rec 0.000572 | Seg 0.269422 | Elapsed 2.5m | ETA 1.7m
Epoch 371/500 | Batch 130/202 | Rec 0.000574 | Seg 0.270510 | Elapsed 2.7m | ETA 1.5m
Epoch 371/500 | Batch 140/202 | Rec 0.000569 | Seg 0.267368 | Elapsed 2.9m | ETA 1.3m
Epoch 371/500 | Batch 150/202 | Rec 0.000572 | Seg 0.272091 | Elapsed 3.1m | ETA 1.1m
Epoch 371/500 | Batch 160/202 | Rec 0.000571 | Seg 0.277443 | Elapsed 3.3m | ETA 0.9m
Epoch 371/500 | Batch 170/202 | Rec 0.000578 | Seg 0.278589 | Elapsed 3.6m | ETA 0.7m
Epoch 371/500 | Batch 180/202 | Rec 0.000578 | Seg 0.275901 | Elapsed 3.8m | ETA 0.5m
Epoch 371/500 | Batch 190/202 | Rec 0.000573 | Seg 0.272291 | Elapsed 4.0m | ETA 0.3m
Epoch 371/500 | Batch 200/202 | Rec 0.000575 | Seg 0.271884 | Elapsed 4.2m | ETA 0.0m
Epoch 371/500 | Batch 202/202 | Rec 0.000577 | Seg 0.274744 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:17:01,108 - INFO: Rec loss: 0.0005767666898283988
2026-09-26 00:17:01,108 - INFO: Seg loss: 0.27474407619326424
2026-09-26 00:17:01,108 - INFO: λ_rec: 1
2026-09-26 00:17:01,108 - INFO: λ_seg: 0.0001
2026-09-26 00:18:20,800 - INFO: -------------------Epoch: 371------------------------
2026-09-26 00:18:20,804 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.811627  0.974337  0.000137
2026-09-26 00:18:20,812 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995861  0.997876  0.997389  0.998463  0.996049
real potato   0.923172  0.960002  0.971906  0.948483  0.999906
fake potato   0.935750  0.966759  0.982274  0.951822  0.999952
real apple    0.781022  0.877000  0.979591  0.793941  0.999232
fake apple    0.597182  0.747748  0.984169  0.602974  0.998464
real orange   0.920494  0.958551  0.996253  0.923692  0.999895
fake orange   0.939170  0.968581  0.948967  0.989127  0.999817
real grape    0.762219  0.865017  0.938376  0.802383  0.999477
fake grape    0.899556  0.947072  0.925889  0.969352  0.999600
real lemon    0.535427  0.697382  0.637233  0.770190  0.999215
fake lemon    0.857709  0.923355  0.998156  0.859070  0.999698
real avocado  0.940913  0.969507  0.974299  0.964860  0.999944
fake avocado  0.515492  0.680251  0.999753  0.515557  0.999420
real pepper   0.902304  0.948593  0.933807  0.963958  0.999618
fake pepper   0.865758  0.927999  0.964510  0.894245  0.999669
real plant    0.872480  0.931848  0.940233  0.923709  0.998650
fake plant    0.747487  0.855450  0.805142  0.912577  0.999755
real banana   0.604690  0.753605  0.907439  0.644438  0.999053
fake banana   0.674219  0.805364  0.766053  0.849038  0.999245
real onion    0.615761  0.762145  0.633386  0.956764  0.999461
fake onion    0.927086  0.962114  0.987774  0.937848  0.999953
real unknown  0.646631  0.785350  0.677509  0.934160  0.999918
fake unknown  0.218342  0.358389  0.232867  0.777798  0.997654
total         0.768640  0.854346  0.877521  0.864541  0.999289
total(-bg)    0.758312  0.847822  0.872072  0.858454  0.999436
2026-09-26 00:18:21,405 - INFO: Epoch accounting: {'epoch': 371, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11360390, 47932, 60710, 111130, 140658, 86810, 88091, 138463, 164952, 76893, 55477, 21813, 24834, 208125, 102606, 143187, 24953, 94204, 50478, 103275, 61937, 13125, 58229], 'crops_with_class': [202, 27, 28, 40, 31, 27, 34, 26, 31, 30, 29, 9, 11, 53, 30, 20, 21, 24, 24, 36, 28, 13, 25], 'targeted_crops_by_class': [0, 5, 4, 4, 6, 7, 6, 1, 1, 3, 6, 1, 3, 4, 2, 5, 4, 2, 1, 8, 7, 7, 10], 'sampled_scene_counts': [0, 0, 0, 1, 1, 0, 0, 1, 2, 3, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 1, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 0, 1, 2, 1, 1, 2, 1, 0, 1, 0, 0, 2, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 0, 1, 0, 3, 0, 2, 1, 2, 2, 0, 0, 1, 2, 0, 1, 2, 2, 3, 0, 1, 1, 2, 2, 3, 0, 1, 0, 1, 4, 3, 2, 0, 1, 1, 0, 1, 4, 1, 2, 0, 1, 1, 1, 1, 4, 2, 1, 3, 0, 3, 1, 1, 3, 2, 0, 1, 4, 1, 1, 0, 1, 1, 2, 1, 1, 2, 1, 1, 2, 0, 1, 0, 0, 0, 1, 2, 0, 2, 0, 2, 1, 1, 5, 1, 4], 'learning_rate': 1.5983213091806644e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005767666898283988, 'train_segmentation_loss': 0.27474407619326424, 'val_foreground_miou_all22': 0.7583119409127701, 'val_psnr_ref1': 38.81162658691406, 'elapsed_seconds': 335.0493459701538, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 372/500 | Batch 10/202 | Rec 0.000735 | Seg 0.364639 | Elapsed 0.2m | ETA 3.9m
Epoch 372/500 | Batch 20/202 | Rec 0.000720 | Seg 0.310925 | Elapsed 0.4m | ETA 3.8m
Epoch 372/500 | Batch 30/202 | Rec 0.000633 | Seg 0.281498 | Elapsed 0.6m | ETA 3.6m
Epoch 372/500 | Batch 40/202 | Rec 0.000690 | Seg 0.304742 | Elapsed 0.8m | ETA 3.4m
Epoch 372/500 | Batch 50/202 | Rec 0.000661 | Seg 0.288873 | Elapsed 1.1m | ETA 3.2m
Epoch 372/500 | Batch 60/202 | Rec 0.000674 | Seg 0.292979 | Elapsed 1.3m | ETA 3.0m
Epoch 372/500 | Batch 70/202 | Rec 0.000681 | Seg 0.305243 | Elapsed 1.5m | ETA 2.8m
Epoch 372/500 | Batch 80/202 | Rec 0.000671 | Seg 0.306850 | Elapsed 1.7m | ETA 2.5m
Epoch 372/500 | Batch 90/202 | Rec 0.000687 | Seg 0.303672 | Elapsed 1.9m | ETA 2.3m
Epoch 372/500 | Batch 100/202 | Rec 0.000677 | Seg 0.299737 | Elapsed 2.1m | ETA 2.1m
Epoch 372/500 | Batch 110/202 | Rec 0.000667 | Seg 0.297454 | Elapsed 2.3m | ETA 1.9m
Epoch 372/500 | Batch 120/202 | Rec 0.000656 | Seg 0.290716 | Elapsed 2.5m | ETA 1.7m
Epoch 372/500 | Batch 130/202 | Rec 0.000645 | Seg 0.287355 | Elapsed 2.7m | ETA 1.5m
Epoch 372/500 | Batch 140/202 | Rec 0.000634 | Seg 0.283496 | Elapsed 2.9m | ETA 1.3m
Epoch 372/500 | Batch 150/202 | Rec 0.000625 | Seg 0.283534 | Elapsed 3.1m | ETA 1.1m
Epoch 372/500 | Batch 160/202 | Rec 0.000625 | Seg 0.285651 | Elapsed 3.3m | ETA 0.9m
Epoch 372/500 | Batch 170/202 | Rec 0.000626 | Seg 0.287889 | Elapsed 3.6m | ETA 0.7m
Epoch 372/500 | Batch 180/202 | Rec 0.000622 | Seg 0.285041 | Elapsed 3.8m | ETA 0.5m
Epoch 372/500 | Batch 190/202 | Rec 0.000619 | Seg 0.286427 | Elapsed 4.0m | ETA 0.3m
Epoch 372/500 | Batch 200/202 | Rec 0.000622 | Seg 0.287793 | Elapsed 4.2m | ETA 0.0m
Epoch 372/500 | Batch 202/202 | Rec 0.000621 | Seg 0.287710 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:22:34,265 - INFO: Rec loss: 0.0006210238820185083
2026-09-26 00:22:34,266 - INFO: Seg loss: 0.28770967694644883
2026-09-26 00:22:34,266 - INFO: λ_rec: 1
2026-09-26 00:22:34,266 - INFO: λ_seg: 0.0001
2026-09-26 00:23:58,088 - INFO: -------------------Epoch: 372------------------------
2026-09-26 00:23:58,092 - INFO:
Validation stats:
       PSNR      SSIM      MSE
0  38.70196  0.974151  0.00014
2026-09-26 00:23:58,099 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995430  0.997660  0.996716  0.998705  0.995635
real potato   0.921033  0.958844  0.954052  0.963785  0.999901
fake potato   0.950850  0.974756  0.977062  0.972560  0.999963
real apple    0.698706  0.822585  0.992995  0.702167  0.998955
fake apple    0.776626  0.874221  0.987732  0.784190  0.999148
real orange   0.747426  0.855410  0.998918  0.748031  0.999667
fake orange   0.866821  0.928610  0.885819  0.975855  0.999571
real grape    0.689559  0.816209  0.883199  0.758752  0.999287
fake grape    0.902006  0.948429  0.945485  0.951491  0.999618
real lemon    0.703498  0.825895  0.797582  0.856401  0.999576
fake lemon    0.799885  0.888768  0.999370  0.800288  0.999576
real avocado  0.958503  0.978762  0.994744  0.963383  0.999961
fake avocado  0.526906  0.690117  1.000000  0.526906  0.999434
real pepper   0.856349  0.922567  0.878956  0.970841  0.999404
fake pepper   0.764644  0.866577  0.957701  0.791371  0.999419
real plant    0.848326  0.917890  0.942899  0.894267  0.998401
fake plant    0.790780  0.883118  0.868992  0.897814  0.999811
real banana   0.713577  0.832801  0.918742  0.761646  0.999313
fake banana   0.667433  0.800501  0.762051  0.843149  0.999227
real onion    0.570742  0.726669  0.583658  0.962675  0.999346
fake onion    0.938473  0.968210  0.989399  0.948005  0.999961
real unknown  0.517666  0.682140  0.541130  0.922710  0.999863
fake unknown  0.261547  0.414603  0.294674  0.699384  0.998336
total         0.759425  0.851102  0.876169  0.856277  0.999277
total(-bg)    0.748698  0.844440  0.870689  0.849803  0.999443
2026-09-26 00:23:58,645 - INFO: Epoch accounting: {'epoch': 372, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11283264, 43213, 66428, 96369, 137337, 45023, 68935, 112994, 180987, 68748, 79618, 31742, 31986, 256229, 136715, 169990, 29583, 92037, 91370, 95851, 70008, 9294, 40551], 'crops_with_class': [202, 26, 33, 24, 34, 18, 22, 24, 37, 30, 28, 12, 14, 58, 32, 19, 27, 25, 36, 42, 29, 11, 18], 'targeted_crops_by_class': [0, 6, 13, 4, 5, 4, 4, 1, 2, 6, 5, 3, 5, 6, 6, 5, 8, 4, 6, 4, 5, 5, 3], 'sampled_scene_counts': [0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 2, 0, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 1, 1, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 3, 3, 0, 2, 0, 3, 1, 1, 1, 2, 2, 1, 1, 2, 5, 4, 2, 0, 0, 0, 2, 1, 0, 2, 2, 4, 2, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 3, 1, 0, 2, 3, 4, 1, 0, 1, 2, 2, 0, 0, 0, 2, 2, 4, 1, 1, 2, 0, 1, 4, 2, 2, 0, 3, 1, 2, 3, 1, 2], 'learning_rate': 1.5755448806680968e-05, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0006210238820185083, 'train_segmentation_loss': 0.28770967694644883, 'val_foreground_miou_all22': 0.7486979895165902, 'val_psnr_ref1': 38.70196029663086, 'elapsed_seconds': 337.230229139328, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 373/500 | Batch 10/202 | Rec 0.000660 | Seg 0.347140 | Elapsed 0.2m | ETA 4.0m
Epoch 373/500 | Batch 20/202 | Rec 0.000687 | Seg 0.334416 | Elapsed 0.4m | ETA 3.8m
Epoch 373/500 | Batch 30/202 | Rec 0.000711 | Seg 0.318311 | Elapsed 0.6m | ETA 3.6m
Epoch 373/500 | Batch 40/202 | Rec 0.000645 | Seg 0.294452 | Elapsed 0.8m | ETA 3.4m
Epoch 373/500 | Batch 50/202 | Rec 0.000650 | Seg 0.285623 | Elapsed 1.0m | ETA 3.2m
Epoch 373/500 | Batch 60/202 | Rec 0.000640 | Seg 0.288864 | Elapsed 1.3m | ETA 3.0m
Epoch 373/500 | Batch 70/202 | Rec 0.000656 | Seg 0.301340 | Elapsed 1.5m | ETA 2.8m
Epoch 373/500 | Batch 80/202 | Rec 0.000640 | Seg 0.294569 | Elapsed 1.7m | ETA 2.6m
Epoch 373/500 | Batch 90/202 | Rec 0.000639 | Seg 0.298596 | Elapsed 1.9m | ETA 2.4m
Epoch 373/500 | Batch 100/202 | Rec 0.000627 | Seg 0.292182 | Elapsed 2.1m | ETA 2.2m
Epoch 373/500 | Batch 110/202 | Rec 0.000631 | Seg 0.298097 | Elapsed 2.3m | ETA 1.9m
Epoch 373/500 | Batch 120/202 | Rec 0.000622 | Seg 0.292658 | Elapsed 2.5m | ETA 1.7m
Epoch 373/500 | Batch 130/202 | Rec 0.000625 | Seg 0.286535 | Elapsed 2.7m | ETA 1.5m
Epoch 373/500 | Batch 140/202 | Rec 0.000619 | Seg 0.280078 | Elapsed 2.9m | ETA 1.3m
Epoch 373/500 | Batch 150/202 | Rec 0.000614 | Seg 0.280095 | Elapsed 3.2m | ETA 1.1m
Epoch 373/500 | Batch 160/202 | Rec 0.000615 | Seg 0.282958 | Elapsed 3.4m | ETA 0.9m
Epoch 373/500 | Batch 170/202 | Rec 0.000626 | Seg 0.283794 | Elapsed 3.6m | ETA 0.7m
Epoch 373/500 | Batch 180/202 | Rec 0.000631 | Seg 0.283906 | Elapsed 3.8m | ETA 0.5m
Epoch 373/500 | Batch 190/202 | Rec 0.000630 | Seg 0.285036 | Elapsed 4.0m | ETA 0.3m
Epoch 373/500 | Batch 200/202 | Rec 0.000622 | Seg 0.282913 | Elapsed 4.2m | ETA 0.0m
Epoch 373/500 | Batch 202/202 | Rec 0.000622 | Seg 0.282542 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:28:12,831 - INFO: Rec loss: 0.0006219214170630606
2026-09-26 00:28:12,831 - INFO: Seg loss: 0.28254235211280315
2026-09-26 00:28:12,832 - INFO: λ_rec: 1
2026-09-26 00:28:12,832 - INFO: λ_seg: 0.0001
2026-09-26 00:29:32,338 - INFO: -------------------Epoch: 373------------------------
2026-09-26 00:29:32,342 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.92964  0.974643  0.000134
2026-09-26 00:29:32,349 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995771  0.997831  0.997079  0.998685  0.995963
real potato   0.908333  0.951915  0.944968  0.959067  0.999884
fake potato   0.960296  0.979696  0.981703  0.977796  0.999971
real apple    0.720566  0.837543  0.974585  0.734365  0.999017
fake apple    0.608622  0.756653  0.992003  0.611623  0.998515
real orange   0.879461  0.935815  0.993497  0.884553  0.999840
fake orange   0.903884  0.949466  0.923178  0.977401  0.999702
real grape    0.733386  0.846139  0.874776  0.819411  0.999378
fake grape    0.903555  0.949284  0.945720  0.952976  0.999624
real lemon    0.768395  0.868981  0.848294  0.890808  0.999684
fake lemon    0.844320  0.915540  0.998637  0.845294  0.999670
real avocado  0.895448  0.944790  0.921887  0.968966  0.999895
fake avocado  0.445422  0.616278  1.000000  0.445422  0.999336
real pepper   0.778294  0.875277  0.810607  0.951276  0.999009
fake pepper   0.628282  0.771664  0.974417  0.638820  0.999099
real plant    0.864316  0.927171  0.949813  0.905678  0.998578
fake plant    0.737343  0.848767  0.776911  0.935391  0.999735
real banana   0.780892  0.876917  0.914988  0.841980  0.999469
fake banana   0.745737  0.854302  0.845504  0.863388  0.999458
real onion    0.599832  0.749821  0.613771  0.963520  0.999419
fake onion    0.952746  0.975751  0.991513  0.960580  0.999970
real unknown  0.533333  0.695605  0.557925  0.923664  0.999871
fake unknown  0.223463  0.365259  0.242218  0.742666  0.997825
total         0.757030  0.847412  0.872782  0.860580  0.999257
total(-bg)    0.746178  0.840574  0.867132  0.854302  0.999407
2026-09-26 00:29:32,910 - INFO: Epoch accounting: {'epoch': 373, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11343583, 65756, 72316, 120494, 133760, 87921, 65631, 124768, 182314, 74265, 67869, 22760, 18205, 186222, 99451, 200564, 25762, 111029, 64189, 73092, 52067, 10531, 35723], 'crops_with_class': [202, 39, 31, 32, 34, 25, 25, 26, 31, 30, 28, 10, 9, 53, 25, 27, 21, 28, 27, 36, 23, 12, 15], 'targeted_crops_by_class': [0, 5, 6, 5, 1, 3, 6, 6, 4, 5, 5, 2, 3, 7, 4, 9, 3, 8, 6, 5, 2, 5, 0], 'sampled_scene_counts': [2, 0, 2, 1, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 2, 1, 0, 3, 2, 1, 1, 0, 3, 1, 2, 2, 2, 0, 0, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 2, 0, 4, 1, 2, 2, 1, 0, 3, 1, 1, 1, 1, 2, 1, 4, 0, 0, 0, 1, 0, 1, 2, 1, 2, 2, 2, 1, 0, 2, 3, 1, 1, 1, 2, 2, 1, 2, 0, 1, 2, 0, 1, 1, 1, 4, 1, 0, 1, 2, 0, 1, 1, 3, 2, 1, 2, 0, 4, 0, 3, 0, 4, 1, 0, 1, 1, 1, 4, 0, 1, 1], 'learning_rate': 1.552904137258634e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006219214170630606, 'train_segmentation_loss': 0.28254235211280315, 'val_foreground_miou_all22': 0.7461784734366933, 'val_psnr_ref1': 38.92963958740234, 'elapsed_seconds': 334.25643849372864, 'peak_cuda_allocated_gib': 7.511508941650391}

Epoch 374/500 | Batch 10/202 | Rec 0.000805 | Seg 0.277868 | Elapsed 0.2m | ETA 4.1m
Epoch 374/500 | Batch 20/202 | Rec 0.000651 | Seg 0.259633 | Elapsed 0.4m | ETA 3.8m
Epoch 374/500 | Batch 30/202 | Rec 0.000637 | Seg 0.278181 | Elapsed 0.6m | ETA 3.6m
Epoch 374/500 | Batch 40/202 | Rec 0.000628 | Seg 0.272006 | Elapsed 0.8m | ETA 3.4m
Epoch 374/500 | Batch 50/202 | Rec 0.000614 | Seg 0.273678 | Elapsed 1.1m | ETA 3.2m
Epoch 374/500 | Batch 60/202 | Rec 0.000582 | Seg 0.262519 | Elapsed 1.3m | ETA 3.0m
Epoch 374/500 | Batch 70/202 | Rec 0.000599 | Seg 0.270603 | Elapsed 1.5m | ETA 2.8m
Epoch 374/500 | Batch 80/202 | Rec 0.000591 | Seg 0.272325 | Elapsed 1.7m | ETA 2.6m
Epoch 374/500 | Batch 90/202 | Rec 0.000600 | Seg 0.277299 | Elapsed 1.9m | ETA 2.4m
Epoch 374/500 | Batch 100/202 | Rec 0.000595 | Seg 0.277426 | Elapsed 2.1m | ETA 2.2m
Epoch 374/500 | Batch 110/202 | Rec 0.000592 | Seg 0.281931 | Elapsed 2.3m | ETA 1.9m
Epoch 374/500 | Batch 120/202 | Rec 0.000598 | Seg 0.287890 | Elapsed 2.5m | ETA 1.7m
Epoch 374/500 | Batch 130/202 | Rec 0.000592 | Seg 0.285740 | Elapsed 2.7m | ETA 1.5m
Epoch 374/500 | Batch 140/202 | Rec 0.000588 | Seg 0.284069 | Elapsed 2.9m | ETA 1.3m
Epoch 374/500 | Batch 150/202 | Rec 0.000590 | Seg 0.288372 | Elapsed 3.2m | ETA 1.1m
Epoch 374/500 | Batch 160/202 | Rec 0.000597 | Seg 0.293346 | Elapsed 3.4m | ETA 0.9m
Epoch 374/500 | Batch 170/202 | Rec 0.000598 | Seg 0.293179 | Elapsed 3.6m | ETA 0.7m
Epoch 374/500 | Batch 180/202 | Rec 0.000598 | Seg 0.294885 | Elapsed 3.8m | ETA 0.5m
Epoch 374/500 | Batch 190/202 | Rec 0.000601 | Seg 0.294351 | Elapsed 4.0m | ETA 0.3m
Epoch 374/500 | Batch 200/202 | Rec 0.000601 | Seg 0.292308 | Elapsed 4.2m | ETA 0.0m
Epoch 374/500 | Batch 202/202 | Rec 0.000600 | Seg 0.292341 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:33:47,151 - INFO: Rec loss: 0.0005997485918624529
2026-09-26 00:33:47,152 - INFO: Seg loss: 0.2923408476728024
2026-09-26 00:33:47,152 - INFO: λ_rec: 1
2026-09-26 00:33:47,152 - INFO: λ_seg: 0.0001
2026-09-26 00:35:07,043 - INFO: -------------------Epoch: 374------------------------
2026-09-26 00:35:07,047 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.801251  0.97456  0.000138
2026-09-26 00:35:07,055 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995840  0.997866  0.997516  0.998315  0.996030
real potato   0.923560  0.960211  0.945715  0.975261  0.999903
fake potato   0.956950  0.977951  0.978206  0.977796  0.999968
real apple    0.757246  0.861806  0.981084  0.768465  0.999150
fake apple    0.575395  0.730430  0.985049  0.580464  0.998383
real orange   0.957125  0.978043  0.997952  0.959009  0.999943
fake orange   0.953226  0.976003  0.970244  0.981932  0.999862
real grape    0.703214  0.825700  0.930785  0.742016  0.999346
fake grape    0.903971  0.949514  0.924011  0.976571  0.999616
real lemon    0.679229  0.808928  0.727962  0.910283  0.999495
fake lemon    0.851257  0.919603  0.998479  0.852362  0.999685
real avocado  0.955765  0.977332  0.990061  0.965025  0.999958
fake avocado  0.557185  0.715585  0.999771  0.557256  0.999470
real pepper   0.833452  0.909112  0.853016  0.973219  0.999289
fake pepper   0.735957  0.847849  0.954939  0.762435  0.999348
real plant    0.856311  0.922544  0.932265  0.913122  0.998467
fake plant    0.854446  0.921461  0.914636  0.928489  0.999874
real banana   0.689102  0.815889  0.879018  0.761307  0.999228
fake banana   0.713251  0.832579  0.788319  0.882216  0.999348
real onion    0.607893  0.756089  0.622637  0.962506  0.999439
fake onion    0.927820  0.962509  0.987535  0.938815  0.999954
real unknown  0.596353  0.747096  0.621673  0.936069  0.999899
fake unknown  0.205037  0.340265  0.220686  0.743028  0.997573
total         0.773460  0.858016  0.878329  0.871564  0.999271
total(-bg)    0.763352  0.851659  0.872911  0.865802  0.999418
2026-09-26 00:35:07,597 - INFO: Epoch accounting: {'epoch': 374, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11270914, 44316, 61349, 100142, 153371, 86154, 80694, 122106, 233464, 75500, 61855, 43784, 38725, 218818, 124505, 142853, 18119, 112471, 87291, 59132, 44193, 12787, 45729], 'crops_with_class': [202, 30, 28, 31, 35, 29, 33, 23, 40, 32, 25, 13, 15, 51, 34, 18, 16, 30, 36, 29, 21, 13, 21], 'targeted_crops_by_class': [0, 2, 4, 6, 4, 4, 4, 6, 11, 4, 4, 1, 4, 5, 0, 4, 2, 9, 2, 5, 3, 8, 8], 'sampled_scene_counts': [0, 1, 4, 1, 1, 1, 1, 0, 2, 2, 0, 1, 1, 0, 1, 1, 1, 0, 0, 2, 1, 0, 2, 0, 1, 0, 1, 1, 0, 1, 3, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 0, 1, 0, 2, 1, 2, 0, 1, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 0, 3, 2, 1, 1, 1, 2, 0, 4, 1, 1, 1, 3, 1, 0, 1, 1, 0, 2, 2, 1, 0, 2, 1, 0, 2, 1, 1, 2, 1, 1, 3, 3, 2, 3, 1, 0, 0, 0, 1, 1, 3, 2, 1, 1, 0, 0, 2, 2, 1, 0, 1, 2, 0, 0, 2, 3, 1, 2, 2, 2, 4, 1, 2, 3, 1, 1, 1, 0, 1, 1, 1, 0, 2, 1], 'learning_rate': 1.530399972770054e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005997485918624529, 'train_segmentation_loss': 0.2923408476728024, 'val_foreground_miou_all22': 0.7633520053401566, 'val_psnr_ref1': 38.80125122070312, 'elapsed_seconds': 334.67959213256836, 'peak_cuda_allocated_gib': 7.508243560791016}

Epoch 375/500 | Batch 10/202 | Rec 0.000518 | Seg 0.238407 | Elapsed 0.2m | ETA 4.0m
Epoch 375/500 | Batch 20/202 | Rec 0.000510 | Seg 0.253075 | Elapsed 0.4m | ETA 3.8m
Epoch 375/500 | Batch 30/202 | Rec 0.000520 | Seg 0.252409 | Elapsed 0.6m | ETA 3.6m
Epoch 375/500 | Batch 40/202 | Rec 0.000502 | Seg 0.242277 | Elapsed 0.8m | ETA 3.4m
Epoch 375/500 | Batch 50/202 | Rec 0.000514 | Seg 0.239360 | Elapsed 1.0m | ETA 3.2m
Epoch 375/500 | Batch 60/202 | Rec 0.000530 | Seg 0.261143 | Elapsed 1.2m | ETA 2.9m
Epoch 375/500 | Batch 70/202 | Rec 0.000543 | Seg 0.264824 | Elapsed 1.5m | ETA 2.7m
Epoch 375/500 | Batch 80/202 | Rec 0.000531 | Seg 0.259816 | Elapsed 1.7m | ETA 2.5m
Epoch 375/500 | Batch 90/202 | Rec 0.000533 | Seg 0.258266 | Elapsed 1.9m | ETA 2.3m
Epoch 375/500 | Batch 100/202 | Rec 0.000528 | Seg 0.257308 | Elapsed 2.1m | ETA 2.1m
Epoch 375/500 | Batch 110/202 | Rec 0.000528 | Seg 0.256666 | Elapsed 2.3m | ETA 1.9m
Epoch 375/500 | Batch 120/202 | Rec 0.000534 | Seg 0.258941 | Elapsed 2.5m | ETA 1.7m
Epoch 375/500 | Batch 130/202 | Rec 0.000546 | Seg 0.262308 | Elapsed 2.7m | ETA 1.5m
Epoch 375/500 | Batch 140/202 | Rec 0.000548 | Seg 0.263331 | Elapsed 2.9m | ETA 1.3m
Epoch 375/500 | Batch 150/202 | Rec 0.000553 | Seg 0.267327 | Elapsed 3.1m | ETA 1.1m
Epoch 375/500 | Batch 160/202 | Rec 0.000550 | Seg 0.264581 | Elapsed 3.3m | ETA 0.9m
Epoch 375/500 | Batch 170/202 | Rec 0.000558 | Seg 0.266642 | Elapsed 3.6m | ETA 0.7m
Epoch 375/500 | Batch 180/202 | Rec 0.000565 | Seg 0.269951 | Elapsed 3.8m | ETA 0.5m
Epoch 375/500 | Batch 190/202 | Rec 0.000567 | Seg 0.269890 | Elapsed 4.0m | ETA 0.3m
Epoch 375/500 | Batch 200/202 | Rec 0.000574 | Seg 0.271873 | Elapsed 4.2m | ETA 0.0m
Epoch 375/500 | Batch 202/202 | Rec 0.000573 | Seg 0.271624 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:39:20,313 - INFO: Rec loss: 0.0005729263144116479
2026-09-26 00:39:20,314 - INFO: Seg loss: 0.27162402589796203
2026-09-26 00:39:20,314 - INFO: λ_rec: 1
2026-09-26 00:39:20,314 - INFO: λ_seg: 0.0001
2026-09-26 00:40:45,425 - INFO: -------------------Epoch: 375------------------------
2026-09-26 00:40:45,430 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  38.719942  0.974669  0.00014
2026-09-26 00:40:45,437 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995628  0.997759  0.997353  0.998265  0.995826
real potato   0.919500  0.958012  0.950546  0.965698  0.999899
fake potato   0.932471  0.965006  0.978884  0.951613  0.999950
real apple    0.722820  0.839064  0.990668  0.727775  0.999037
fake apple    0.602031  0.751538  0.988793  0.606167  0.998487
real orange   0.731298  0.844749  0.997949  0.732399  0.999645
fake orange   0.861741  0.925687  0.877970  0.979000  0.999550
real grape    0.729916  0.843825  0.888548  0.803479  0.999379
fake grape    0.899068  0.946802  0.927109  0.967455  0.999598
real lemon    0.673251  0.804672  0.837428  0.774474  0.999558
fake lemon    0.845816  0.916419  0.997116  0.847890  0.999673
real avocado  0.955134  0.977002  0.985956  0.968309  0.999958
fake avocado  0.502677  0.668998  0.999493  0.502805  0.999405
real pepper   0.817481  0.899526  0.835864  0.973803  0.999205
fake pepper   0.689878  0.816434  0.947489  0.717304  0.999231
real plant    0.868931  0.929820  0.946456  0.913855  0.998621
fake plant    0.805505  0.892227  0.856337  0.931365  0.999821
real banana   0.762174  0.864988  0.870300  0.859840  0.999397
fake banana   0.656706  0.792736  0.723446  0.876825  0.999157
real onion    0.606547  0.755046  0.620663  0.963857  0.999435
fake onion    0.937530  0.967708  0.981353  0.954534  0.999960
real unknown  0.518637  0.682983  0.539911  0.929389  0.999862
fake unknown  0.207050  0.343032  0.224757  0.724375  0.997663
total         0.749643  0.842784  0.868017  0.855238  0.999231
total(-bg)    0.738462  0.835740  0.862138  0.848737  0.999386
2026-09-26 00:40:45,992 - INFO: Epoch accounting: {'epoch': 375, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11379642, 65089, 70945, 158841, 118785, 81381, 50988, 124050, 169557, 54979, 57201, 46926, 40604, 224135, 105011, 84833, 25160, 95026, 55086, 121476, 53129, 9694, 45734], 'crops_with_class': [202, 35, 31, 39, 29, 25, 21, 23, 31, 26, 26, 16, 17, 55, 27, 15, 20, 25, 27, 48, 28, 11, 20], 'targeted_crops_by_class': [0, 6, 6, 11, 3, 5, 4, 2, 4, 4, 6, 7, 4, 2, 1, 2, 6, 8, 3, 10, 6, 3, 3], 'sampled_scene_counts': [0, 0, 1, 1, 1, 1, 0, 0, 2, 3, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 3, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 3, 3, 0, 2, 1, 0, 1, 0, 2, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 2, 1, 1, 1, 1, 0, 2, 2, 2, 1, 1, 1, 0, 3, 2, 1, 1, 2, 0, 0, 1, 2, 1, 2, 0, 1, 0, 2, 2, 1, 1, 1, 0, 2, 1, 0, 1, 0, 2, 0, 1, 1, 2, 3, 1, 2, 1, 0, 2, 1, 3, 1, 2, 2, 1, 2, 0, 2, 4, 1, 1, 2, 0, 2, 4, 2, 1, 3, 2, 0, 2, 0, 0, 3, 1, 1, 3, 0, 3, 1, 0, 0, 1, 1, 3], 'learning_rate': 1.5080332756282365e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005729263144116479, 'train_segmentation_loss': 0.27162402589796203, 'val_foreground_miou_all22': 0.7384619993120594, 'val_psnr_ref1': 38.71994186401367, 'elapsed_seconds': 338.38703083992004, 'peak_cuda_allocated_gib': 7.512729644775391}

Epoch 376/500 | Batch 10/202 | Rec 0.000754 | Seg 0.375372 | Elapsed 0.2m | ETA 3.9m
Epoch 376/500 | Batch 20/202 | Rec 0.000676 | Seg 0.335362 | Elapsed 0.4m | ETA 3.8m
Epoch 376/500 | Batch 30/202 | Rec 0.000657 | Seg 0.323970 | Elapsed 0.6m | ETA 3.6m
Epoch 376/500 | Batch 40/202 | Rec 0.000641 | Seg 0.316736 | Elapsed 0.8m | ETA 3.4m
Epoch 376/500 | Batch 50/202 | Rec 0.000622 | Seg 0.308540 | Elapsed 1.0m | ETA 3.2m
Epoch 376/500 | Batch 60/202 | Rec 0.000619 | Seg 0.309928 | Elapsed 1.3m | ETA 3.0m
Epoch 376/500 | Batch 70/202 | Rec 0.000609 | Seg 0.296873 | Elapsed 1.5m | ETA 2.7m
Epoch 376/500 | Batch 80/202 | Rec 0.000610 | Seg 0.301270 | Elapsed 1.7m | ETA 2.5m
Epoch 376/500 | Batch 90/202 | Rec 0.000614 | Seg 0.306053 | Elapsed 1.9m | ETA 2.3m
Epoch 376/500 | Batch 100/202 | Rec 0.000616 | Seg 0.299352 | Elapsed 2.1m | ETA 2.1m
Epoch 376/500 | Batch 110/202 | Rec 0.000602 | Seg 0.293021 | Elapsed 2.3m | ETA 1.9m
Epoch 376/500 | Batch 120/202 | Rec 0.000586 | Seg 0.285691 | Elapsed 2.5m | ETA 1.7m
Epoch 376/500 | Batch 130/202 | Rec 0.000595 | Seg 0.289851 | Elapsed 2.7m | ETA 1.5m
Epoch 376/500 | Batch 140/202 | Rec 0.000600 | Seg 0.292190 | Elapsed 2.9m | ETA 1.3m
Epoch 376/500 | Batch 150/202 | Rec 0.000592 | Seg 0.288988 | Elapsed 3.1m | ETA 1.1m
Epoch 376/500 | Batch 160/202 | Rec 0.000595 | Seg 0.289362 | Elapsed 3.3m | ETA 0.9m
Epoch 376/500 | Batch 170/202 | Rec 0.000598 | Seg 0.292133 | Elapsed 3.5m | ETA 0.7m
Epoch 376/500 | Batch 180/202 | Rec 0.000599 | Seg 0.292844 | Elapsed 3.8m | ETA 0.5m
Epoch 376/500 | Batch 190/202 | Rec 0.000589 | Seg 0.289574 | Elapsed 4.0m | ETA 0.3m
Epoch 376/500 | Batch 200/202 | Rec 0.000584 | Seg 0.288873 | Elapsed 4.2m | ETA 0.0m
Epoch 376/500 | Batch 202/202 | Rec 0.000583 | Seg 0.288423 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:44:59,117 - INFO: Rec loss: 0.0005832687633355278
2026-09-26 00:44:59,117 - INFO: Seg loss: 0.28842315048274425
2026-09-26 00:44:59,117 - INFO: λ_rec: 1
2026-09-26 00:44:59,118 - INFO: λ_seg: 0.0001
2026-09-26 00:46:20,748 - INFO: -------------------Epoch: 376------------------------
2026-09-26 00:46:20,752 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.053044  0.974937  0.00013
2026-09-26 00:46:20,760 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995686  0.997788  0.997284  0.998393  0.995882
real potato   0.815161  0.898119  0.971518  0.835119  0.999773
fake potato   0.958308  0.978660  0.984938  0.972560  0.999969
real apple    0.783827  0.878765  0.936506  0.827820  0.999212
fake apple    0.670527  0.802724  0.982505  0.678629  0.998741
real orange   0.956431  0.977681  0.997950  0.958314  0.999942
fake orange   0.952425  0.975583  0.969675  0.981665  0.999860
real grape    0.776882  0.874383  0.960385  0.802602  0.999519
fake grape    0.904276  0.949682  0.939179  0.960525  0.999624
real lemon    0.556804  0.715268  0.621138  0.843158  0.999211
fake lemon    0.851506  0.919749  0.993721  0.856113  0.999684
real avocado  0.912262  0.954068  0.942203  0.966338  0.999914
fake avocado  0.646864  0.785523  0.999606  0.647029  0.999577
real pepper   0.795918  0.886314  0.819758  0.964751  0.999095
fake pepper   0.642576  0.782352  0.963653  0.658537  0.999127
real plant    0.869017  0.929869  0.940896  0.919194  0.998614
fake plant    0.856026  0.922379  0.921546  0.923313  0.999876
real banana   0.586670  0.739450  0.868689  0.643759  0.998981
fake banana   0.683246  0.811769  0.776893  0.850033  0.999275
real onion    0.621313  0.766384  0.652504  0.928559  0.999489
fake onion    0.927578  0.962378  0.991033  0.935429  0.999954
real unknown  0.760031  0.863607  0.812447  0.921756  0.999953
fake unknown  0.251724  0.402165  0.270144  0.786853  0.998029
total         0.772828  0.859768  0.883225  0.863498  0.999274
total(-bg)    0.762699  0.853494  0.878040  0.857366  0.999428
2026-09-26 00:46:21,502 - INFO: Epoch accounting: {'epoch': 376, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11280466, 59591, 80247, 106327, 166915, 65842, 88814, 114948, 181737, 81356, 47546, 35881, 44484, 205901, 109949, 140590, 22082, 98930, 79013, 113016, 57376, 14530, 42731], 'crops_with_class': [202, 30, 33, 31, 40, 18, 30, 29, 32, 34, 26, 16, 14, 53, 31, 17, 21, 28, 34, 42, 31, 14, 20], 'targeted_crops_by_class': [0, 3, 5, 4, 6, 4, 7, 8, 6, 3, 2, 3, 3, 3, 5, 7, 4, 6, 6, 5, 8, 3, 4], 'sampled_scene_counts': [0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 3, 0, 2, 0, 0, 0, 3, 1, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 1, 1, 3, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 4, 1, 1, 0, 1, 3, 2, 3, 0, 1, 1, 1, 0, 2, 0, 1, 2, 1, 3, 2, 0, 2, 3, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 4, 5, 1, 2, 1, 2, 1, 2, 2, 2, 2, 0, 1, 3, 3, 1, 1, 3, 0, 0, 1, 1, 3, 1, 0, 1, 1, 1, 0, 1, 2, 5, 2, 1, 0, 3, 4, 1, 0, 1, 1, 3], 'learning_rate': 1.4858049288320925e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005832687633355278, 'train_segmentation_loss': 0.28842315048274425, 'val_foreground_miou_all22': 0.7626985874325819, 'val_psnr_ref1': 39.05304443359375, 'elapsed_seconds': 335.5010275840759, 'peak_cuda_allocated_gib': 7.513217926025391}

Epoch 377/500 | Batch 10/202 | Rec 0.000629 | Seg 0.353153 | Elapsed 0.2m | ETA 3.8m
Epoch 377/500 | Batch 20/202 | Rec 0.000621 | Seg 0.343447 | Elapsed 0.4m | ETA 3.7m
Epoch 377/500 | Batch 30/202 | Rec 0.000631 | Seg 0.329806 | Elapsed 0.6m | ETA 3.5m
Epoch 377/500 | Batch 40/202 | Rec 0.000606 | Seg 0.312944 | Elapsed 0.8m | ETA 3.3m
Epoch 377/500 | Batch 50/202 | Rec 0.000610 | Seg 0.307384 | Elapsed 1.0m | ETA 3.2m
Epoch 377/500 | Batch 60/202 | Rec 0.000589 | Seg 0.289748 | Elapsed 1.2m | ETA 2.9m
Epoch 377/500 | Batch 70/202 | Rec 0.000610 | Seg 0.289038 | Elapsed 1.4m | ETA 2.7m
Epoch 377/500 | Batch 80/202 | Rec 0.000605 | Seg 0.292804 | Elapsed 1.7m | ETA 2.5m
Epoch 377/500 | Batch 90/202 | Rec 0.000608 | Seg 0.293747 | Elapsed 1.9m | ETA 2.3m
Epoch 377/500 | Batch 100/202 | Rec 0.000607 | Seg 0.291337 | Elapsed 2.1m | ETA 2.1m
Epoch 377/500 | Batch 110/202 | Rec 0.000603 | Seg 0.290901 | Elapsed 2.3m | ETA 1.9m
Epoch 377/500 | Batch 120/202 | Rec 0.000593 | Seg 0.287507 | Elapsed 2.5m | ETA 1.7m
Epoch 377/500 | Batch 130/202 | Rec 0.000587 | Seg 0.284850 | Elapsed 2.7m | ETA 1.5m
Epoch 377/500 | Batch 140/202 | Rec 0.000580 | Seg 0.280962 | Elapsed 2.9m | ETA 1.3m
Epoch 377/500 | Batch 150/202 | Rec 0.000588 | Seg 0.287244 | Elapsed 3.1m | ETA 1.1m
Epoch 377/500 | Batch 160/202 | Rec 0.000583 | Seg 0.287222 | Elapsed 3.3m | ETA 0.9m
Epoch 377/500 | Batch 170/202 | Rec 0.000585 | Seg 0.291056 | Elapsed 3.5m | ETA 0.7m
Epoch 377/500 | Batch 180/202 | Rec 0.000584 | Seg 0.291281 | Elapsed 3.7m | ETA 0.5m
Epoch 377/500 | Batch 190/202 | Rec 0.000584 | Seg 0.288622 | Elapsed 3.9m | ETA 0.2m
Epoch 377/500 | Batch 200/202 | Rec 0.000593 | Seg 0.292227 | Elapsed 4.2m | ETA 0.0m
Epoch 377/500 | Batch 202/202 | Rec 0.000593 | Seg 0.291976 | Elapsed 4.2m | ETA 0.0m

2026-09-26 00:50:33,264 - INFO: Rec loss: 0.0005931520569028729
2026-09-26 00:50:33,264 - INFO: Seg loss: 0.2919755691090728
2026-09-26 00:50:33,264 - INFO: λ_rec: 1
2026-09-26 00:50:33,264 - INFO: λ_seg: 0.0001
2026-09-26 00:51:58,945 - INFO: -------------------Epoch: 377------------------------
2026-09-26 00:51:58,950 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.064572  0.974806  0.00013
2026-09-26 00:51:58,958 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995981  0.997937  0.997634  0.998340  0.996165
real potato   0.907346  0.951373  0.922000  0.982785  0.999880
fake potato   0.957835  0.978413  0.967445  0.989736  0.999968
real apple    0.753952  0.859668  0.963231  0.776294  0.999126
fake apple    0.519941  0.684114  0.984443  0.524248  0.998172
real orange   0.881765  0.937118  0.991345  0.888606  0.999843
fake orange   0.919847  0.958200  0.931465  0.986622  0.999754
real grape    0.791434  0.883527  0.958145  0.819776  0.999549
fake grape    0.891385  0.942524  0.925090  0.960731  0.999567
real lemon    0.723276  0.839370  0.809650  0.871462  0.999608
fake lemon    0.848812  0.918175  0.997884  0.850343  0.999680
real avocado  0.956663  0.977802  0.988097  0.967816  0.999959
fake avocado  0.298903  0.460204  1.000000  0.298903  0.999161
real pepper   0.839745  0.912843  0.854596  0.979726  0.999316
fake pepper   0.736140  0.847970  0.953844  0.763331  0.999348
real plant    0.874065  0.932751  0.949814  0.916387  0.998679
fake plant    0.789271  0.882177  0.827291  0.944977  0.999799
real banana   0.746406  0.854741  0.899303  0.814478  0.999378
fake banana   0.699189  0.822918  0.768097  0.886281  0.999299
real onion    0.574140  0.729418  0.580626  0.980915  0.999343
fake onion    0.844672  0.915747  0.862733  0.975816  0.999887
real unknown  0.577713  0.732294  0.599878  0.939885  0.999890
fake unknown  0.160663  0.276813  0.176960  0.635639  0.997202
total         0.751702  0.838961  0.865633  0.858830  0.999242
total(-bg)    0.740598  0.831735  0.859633  0.852489  0.999382
2026-09-26 00:51:59,727 - INFO: Epoch accounting: {'epoch': 377, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11236938, 49101, 70423, 99318, 164396, 103198, 75424, 137754, 195364, 65945, 79028, 47524, 38955, 256448, 116464, 161095, 19219, 62192, 61856, 76255, 56554, 12638, 52183], 'crops_with_class': [202, 29, 30, 32, 35, 31, 29, 29, 35, 30, 32, 18, 12, 64, 35, 22, 21, 20, 26, 30, 24, 14, 25], 'targeted_crops_by_class': [0, 3, 9, 8, 4, 3, 6, 3, 5, 6, 1, 6, 4, 5, 12, 7, 4, 1, 7, 5, 6, 5, 6], 'sampled_scene_counts': [1, 1, 1, 1, 0, 2, 2, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 3, 0, 1, 0, 2, 0, 2, 1, 1, 2, 1, 0, 3, 1, 0, 1, 0, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 0, 0, 0, 1, 2, 1, 1, 0, 3, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 3, 0, 1, 1, 1, 1, 5, 2, 2, 3, 1, 1, 2, 1, 2, 2, 1, 1, 0, 1, 0, 2, 1, 0, 1, 1, 0, 1, 1, 2, 2, 2, 1, 1, 5, 5, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 0, 0, 0, 3, 1, 0, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 4, 1, 1, 2, 0, 1, 1, 2, 2, 0, 1, 2, 1], 'learning_rate': 1.4637158099186873e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005931520569028729, 'train_segmentation_loss': 0.2919755691090728, 'val_foreground_miou_all22': 0.7405983615030344, 'val_psnr_ref1': 39.064572448730466, 'elapsed_seconds': 338.21715545654297, 'peak_cuda_allocated_gib': 7.513370513916016}

Epoch 378/500 | Batch 10/202 | Rec 0.000578 | Seg 0.310176 | Elapsed 0.2m | ETA 3.9m
Epoch 378/500 | Batch 20/202 | Rec 0.000604 | Seg 0.301179 | Elapsed 0.4m | ETA 3.8m
Epoch 378/500 | Batch 30/202 | Rec 0.000562 | Seg 0.289438 | Elapsed 0.6m | ETA 3.6m
Epoch 378/500 | Batch 40/202 | Rec 0.000561 | Seg 0.292925 | Elapsed 0.8m | ETA 3.4m
Epoch 378/500 | Batch 50/202 | Rec 0.000583 | Seg 0.290430 | Elapsed 1.1m | ETA 3.2m
Epoch 378/500 | Batch 60/202 | Rec 0.000563 | Seg 0.272415 | Elapsed 1.3m | ETA 3.0m
Epoch 378/500 | Batch 70/202 | Rec 0.000570 | Seg 0.277538 | Elapsed 1.5m | ETA 2.8m
Epoch 378/500 | Batch 80/202 | Rec 0.000573 | Seg 0.278058 | Elapsed 1.7m | ETA 2.6m
Epoch 378/500 | Batch 90/202 | Rec 0.000572 | Seg 0.276895 | Elapsed 1.9m | ETA 2.4m
Epoch 378/500 | Batch 100/202 | Rec 0.000566 | Seg 0.276748 | Elapsed 2.1m | ETA 2.2m
Epoch 378/500 | Batch 110/202 | Rec 0.000572 | Seg 0.275858 | Elapsed 2.3m | ETA 1.9m
Epoch 378/500 | Batch 120/202 | Rec 0.000592 | Seg 0.290032 | Elapsed 2.5m | ETA 1.7m
Epoch 378/500 | Batch 130/202 | Rec 0.000606 | Seg 0.293886 | Elapsed 2.8m | ETA 1.5m
Epoch 378/500 | Batch 140/202 | Rec 0.000594 | Seg 0.291761 | Elapsed 3.0m | ETA 1.3m
Epoch 378/500 | Batch 150/202 | Rec 0.000598 | Seg 0.292953 | Elapsed 3.2m | ETA 1.1m
Epoch 378/500 | Batch 160/202 | Rec 0.000610 | Seg 0.291956 | Elapsed 3.4m | ETA 0.9m
Epoch 378/500 | Batch 170/202 | Rec 0.000610 | Seg 0.291947 | Elapsed 3.6m | ETA 0.7m
Epoch 378/500 | Batch 180/202 | Rec 0.000608 | Seg 0.288829 | Elapsed 3.8m | ETA 0.5m
Epoch 378/500 | Batch 190/202 | Rec 0.000605 | Seg 0.287262 | Elapsed 4.0m | ETA 0.3m
Epoch 378/500 | Batch 200/202 | Rec 0.000614 | Seg 0.289998 | Elapsed 4.2m | ETA 0.0m
Epoch 378/500 | Batch 202/202 | Rec 0.000616 | Seg 0.291535 | Elapsed 4.3m | ETA 0.0m

2026-09-26 00:56:14,998 - INFO: Rec loss: 0.0006163610510111989
2026-09-26 00:56:14,998 - INFO: Seg loss: 0.29153490009358024
2026-09-26 00:56:14,998 - INFO: λ_rec: 1
2026-09-26 00:56:14,998 - INFO: λ_seg: 0.0001
2026-09-26 00:57:38,296 - INFO: -------------------Epoch: 378------------------------
2026-09-26 00:57:38,300 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.856674  0.97453  0.000136
2026-09-26 00:57:38,307 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995742  0.997816  0.996983  0.998752  0.995934
real potato   0.698763  0.822624  0.985407  0.706070  0.999636
fake potato   0.727068  0.841919  0.969954  0.743821  0.999797
real apple    0.758407  0.862557  0.865391  0.859841  0.999055
fake apple    0.620200  0.765537  0.980684  0.627869  0.998548
real orange   0.825695  0.904477  0.996240  0.828277  0.999770
fake orange   0.893906  0.943931  0.914920  0.974949  0.999669
real grape    0.823298  0.903037  0.973153  0.842432  0.999622
fake grape    0.888610  0.940970  0.919871  0.963165  0.999553
real lemon    0.473105  0.642276  0.532309  0.809660  0.998940
fake lemon    0.846847  0.917024  0.981969  0.860224  0.999671
real avocado  0.872689  0.931967  0.904512  0.961248  0.999870
fake avocado  0.627741  0.771256  0.999594  0.627901  0.999554
real pepper   0.867327  0.928901  0.902803  0.956658  0.999465
fake pepper   0.781215  0.877122  0.950056  0.814673  0.999456
real plant    0.868517  0.929583  0.962711  0.898752  0.998639
fake plant    0.814637  0.897801  0.886852  0.909126  0.999835
real banana   0.520137  0.684282  0.910547  0.548146  0.998864
fake banana   0.670117  0.802429  0.765690  0.842983  0.999237
real onion    0.605224  0.754018  0.696636  0.821821  0.999516
fake onion    0.923608  0.960237  0.983029  0.938573  0.999951
real unknown  0.902713  0.948819  0.978702  0.920801  0.999984
fake unknown  0.204275  0.339213  0.225230  0.687070  0.997745
total         0.748254  0.842078  0.881880  0.832296  0.999231
total(-bg)    0.737005  0.834999  0.876648  0.824730  0.999381
2026-09-26 00:57:38,867 - INFO: Epoch accounting: {'epoch': 378, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11210247, 50176, 60752, 130973, 157304, 77536, 61588, 131151, 196135, 86068, 64235, 39973, 35050, 236203, 170402, 167543, 20309, 72732, 64025, 93678, 67556, 7187, 37449], 'crops_with_class': [202, 35, 29, 39, 33, 23, 23, 29, 31, 35, 28, 13, 13, 56, 38, 23, 18, 22, 30, 42, 29, 8, 18], 'targeted_crops_by_class': [0, 4, 3, 5, 5, 3, 1, 6, 6, 6, 6, 2, 3, 8, 6, 3, 1, 3, 9, 7, 3, 4, 1], 'sampled_scene_counts': [1, 1, 1, 0, 0, 1, 0, 2, 2, 1, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 1, 0, 0, 0, 2, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 3, 1, 0, 1, 1, 2, 1, 3, 1, 2, 1, 1, 3, 2, 0, 2, 1, 1, 0, 1, 1, 2, 0, 0, 0, 1, 0, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 2, 4, 1, 0, 2, 0, 3, 4, 1, 2, 0, 3, 1, 1, 2, 1, 0, 1, 3, 1, 1, 1, 2, 1, 1, 0, 1, 1, 2, 4, 1, 1, 1, 0, 0, 1, 2, 3, 2, 2, 2], 'learning_rate': 1.4417667909286148e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006163610510111989, 'train_segmentation_loss': 0.29153490009358024, 'val_foreground_miou_all22': 0.7370045567415318, 'val_psnr_ref1': 38.856673583984374, 'elapsed_seconds': 339.1313679218292, 'peak_cuda_allocated_gib': 7.513683319091797}

Epoch 379/500 | Batch 10/202 | Rec 0.000582 | Seg 0.269678 | Elapsed 0.2m | ETA 4.0m
Epoch 379/500 | Batch 20/202 | Rec 0.000570 | Seg 0.286061 | Elapsed 0.4m | ETA 3.8m
Epoch 379/500 | Batch 30/202 | Rec 0.000552 | Seg 0.266171 | Elapsed 0.6m | ETA 3.6m
Epoch 379/500 | Batch 40/202 | Rec 0.000584 | Seg 0.278899 | Elapsed 0.8m | ETA 3.4m
Epoch 379/500 | Batch 50/202 | Rec 0.000587 | Seg 0.278941 | Elapsed 1.0m | ETA 3.1m
Epoch 379/500 | Batch 60/202 | Rec 0.000628 | Seg 0.271404 | Elapsed 1.2m | ETA 3.0m
Epoch 379/500 | Batch 70/202 | Rec 0.000636 | Seg 0.278703 | Elapsed 1.5m | ETA 2.7m
Epoch 379/500 | Batch 80/202 | Rec 0.000615 | Seg 0.270723 | Elapsed 1.7m | ETA 2.5m
Epoch 379/500 | Batch 90/202 | Rec 0.000619 | Seg 0.271300 | Elapsed 1.9m | ETA 2.3m
Epoch 379/500 | Batch 100/202 | Rec 0.000623 | Seg 0.276383 | Elapsed 2.1m | ETA 2.1m
Epoch 379/500 | Batch 110/202 | Rec 0.000620 | Seg 0.273149 | Elapsed 2.3m | ETA 1.9m
Epoch 379/500 | Batch 120/202 | Rec 0.000612 | Seg 0.271910 | Elapsed 2.5m | ETA 1.7m
Epoch 379/500 | Batch 130/202 | Rec 0.000609 | Seg 0.269372 | Elapsed 2.7m | ETA 1.5m
Epoch 379/500 | Batch 140/202 | Rec 0.000613 | Seg 0.270826 | Elapsed 2.9m | ETA 1.3m
Epoch 379/500 | Batch 150/202 | Rec 0.000606 | Seg 0.269016 | Elapsed 3.1m | ETA 1.1m
Epoch 379/500 | Batch 160/202 | Rec 0.000607 | Seg 0.269666 | Elapsed 3.4m | ETA 0.9m
Epoch 379/500 | Batch 170/202 | Rec 0.000598 | Seg 0.269342 | Elapsed 3.6m | ETA 0.7m
Epoch 379/500 | Batch 180/202 | Rec 0.000592 | Seg 0.268351 | Elapsed 3.8m | ETA 0.5m
Epoch 379/500 | Batch 190/202 | Rec 0.000597 | Seg 0.270107 | Elapsed 4.0m | ETA 0.3m
Epoch 379/500 | Batch 200/202 | Rec 0.000593 | Seg 0.268148 | Elapsed 4.2m | ETA 0.0m
Epoch 379/500 | Batch 202/202 | Rec 0.000595 | Seg 0.269729 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:01:52,862 - INFO: Rec loss: 0.0005948218949384628
2026-09-26 01:01:52,862 - INFO: Seg loss: 0.2697291094994191
2026-09-26 01:01:52,862 - INFO: λ_rec: 1
2026-09-26 01:01:52,862 - INFO: λ_seg: 0.0001
2026-09-26 01:03:17,282 - INFO: -------------------Epoch: 379------------------------
2026-09-26 01:03:17,286 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.058709  0.974874  0.00013
2026-09-26 01:03:17,294 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995792  0.997842  0.997310  0.998474  0.995983
real potato   0.925775  0.961407  0.963860  0.959067  0.999908
fake potato   0.933511  0.965562  0.975625  0.955802  0.999950
real apple    0.768929  0.869323  0.969063  0.788280  0.999183
fake apple    0.551608  0.710968  0.988134  0.555286  0.998296
real orange   0.926097  0.961581  0.997016  0.928671  0.999902
fake orange   0.937420  0.967650  0.953774  0.982038  0.999812
real grape    0.804840  0.891819  0.909450  0.874954  0.999557
fake grape    0.901318  0.948048  0.921938  0.975787  0.999605
real lemon    0.700777  0.824018  0.735891  0.936250  0.999530
fake lemon    0.853816  0.921095  0.995892  0.856834  0.999690
real avocado  0.894361  0.944185  0.923270  0.966174  0.999894
fake avocado  0.382330  0.553128  0.999334  0.382428  0.999261
real pepper   0.838363  0.912026  0.872993  0.954822  0.999327
fake pepper   0.742376  0.852092  0.954214  0.769797  0.999363
real plant    0.880408  0.936351  0.959264  0.914602  0.998757
fake plant    0.750748  0.857581  0.807725  0.914110  0.999758
real banana   0.666202  0.799616  0.908071  0.714383  0.999196
fake banana   0.739893  0.850454  0.840515  0.860733  0.999443
real onion    0.631307  0.773941  0.652602  0.950853  0.999498
fake onion    0.939459  0.968734  0.980912  0.956953  0.999961
real unknown  0.629703  0.772734  0.671358  0.910305  0.999914
fake unknown  0.195108  0.326477  0.208367  0.754075  0.997379
total         0.764789  0.850723  0.877677  0.863508  0.999268
total(-bg)    0.754289  0.844036  0.872239  0.857373  0.999418
2026-09-26 01:03:17,846 - INFO: Epoch accounting: {'epoch': 379, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11383277, 57962, 65468, 82576, 136385, 50429, 51120, 157801, 132641, 82605, 45438, 38993, 46523, 229840, 138495, 157717, 33805, 76399, 42016, 102051, 68640, 7107, 50984], 'crops_with_class': [202, 34, 26, 27, 38, 17, 16, 28, 26, 38, 22, 14, 17, 56, 34, 22, 30, 22, 18, 38, 28, 8, 21], 'targeted_crops_by_class': [0, 3, 4, 2, 7, 4, 3, 3, 6, 3, 6, 1, 9, 7, 8, 5, 6, 3, 3, 4, 5, 4, 6], 'sampled_scene_counts': [2, 1, 2, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 3, 0, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 0, 1, 3, 1, 2, 1, 0, 0, 0, 2, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 3, 1, 2, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 4, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 1, 0, 2, 0, 1, 1, 1, 1, 1, 2, 2, 1, 3, 2, 4, 1, 0, 1, 4, 2, 1, 0, 1, 2, 3, 0, 2, 1, 1, 1, 2, 4, 2, 2, 1, 2, 1, 1, 4, 0, 2, 4, 1, 2, 1, 1, 0, 2, 1, 1, 2, 0, 1, 4, 2, 1, 1, 1, 1, 2, 0, 1, 0, 2, 1, 3, 1, 2, 1, 0], 'learning_rate': 1.4199587383715622e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005948218949384628, 'train_segmentation_loss': 0.2697291094994191, 'val_foreground_miou_all22': 0.754288684490162, 'val_psnr_ref1': 39.058709411621095, 'elapsed_seconds': 338.97101879119873, 'peak_cuda_allocated_gib': 7.510532379150391}

Epoch 380/500 | Batch 10/202 | Rec 0.000588 | Seg 0.292397 | Elapsed 0.2m | ETA 4.0m
Epoch 380/500 | Batch 20/202 | Rec 0.000544 | Seg 0.283175 | Elapsed 0.4m | ETA 3.8m
Epoch 380/500 | Batch 30/202 | Rec 0.000549 | Seg 0.281675 | Elapsed 0.6m | ETA 3.5m
Epoch 380/500 | Batch 40/202 | Rec 0.000528 | Seg 0.276086 | Elapsed 0.8m | ETA 3.3m
Epoch 380/500 | Batch 50/202 | Rec 0.000550 | Seg 0.279467 | Elapsed 1.0m | ETA 3.1m
Epoch 380/500 | Batch 60/202 | Rec 0.000558 | Seg 0.278459 | Elapsed 1.2m | ETA 2.9m
Epoch 380/500 | Batch 70/202 | Rec 0.000561 | Seg 0.277839 | Elapsed 1.5m | ETA 2.8m
Epoch 380/500 | Batch 80/202 | Rec 0.000552 | Seg 0.270243 | Elapsed 1.7m | ETA 2.5m
Epoch 380/500 | Batch 90/202 | Rec 0.000582 | Seg 0.288192 | Elapsed 1.9m | ETA 2.3m
Epoch 380/500 | Batch 100/202 | Rec 0.000596 | Seg 0.287127 | Elapsed 2.1m | ETA 2.1m
Epoch 380/500 | Batch 110/202 | Rec 0.000596 | Seg 0.283396 | Elapsed 2.3m | ETA 1.9m
Epoch 380/500 | Batch 120/202 | Rec 0.000600 | Seg 0.285272 | Elapsed 2.5m | ETA 1.7m
Epoch 380/500 | Batch 130/202 | Rec 0.000604 | Seg 0.285884 | Elapsed 2.7m | ETA 1.5m
Epoch 380/500 | Batch 140/202 | Rec 0.000611 | Seg 0.289797 | Elapsed 2.9m | ETA 1.3m
Epoch 380/500 | Batch 150/202 | Rec 0.000612 | Seg 0.288657 | Elapsed 3.1m | ETA 1.1m
Epoch 380/500 | Batch 160/202 | Rec 0.000610 | Seg 0.289364 | Elapsed 3.3m | ETA 0.9m
Epoch 380/500 | Batch 170/202 | Rec 0.000605 | Seg 0.285945 | Elapsed 3.5m | ETA 0.7m
Epoch 380/500 | Batch 180/202 | Rec 0.000602 | Seg 0.286922 | Elapsed 3.7m | ETA 0.5m
Epoch 380/500 | Batch 190/202 | Rec 0.000610 | Seg 0.284353 | Elapsed 4.0m | ETA 0.3m
Epoch 380/500 | Batch 200/202 | Rec 0.000611 | Seg 0.286421 | Elapsed 4.2m | ETA 0.0m
Epoch 380/500 | Batch 202/202 | Rec 0.000611 | Seg 0.287797 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:07:29,666 - INFO: Rec loss: 0.0006112675025475922
2026-09-26 01:07:29,667 - INFO: Seg loss: 0.2877973601000734
2026-09-26 01:07:29,667 - INFO: λ_rec: 1
2026-09-26 01:07:29,667 - INFO: λ_seg: 0.0001
2026-09-26 01:08:52,913 - INFO: -------------------Epoch: 380------------------------
2026-09-26 01:08:52,917 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.977876  0.974601  0.000132
2026-09-26 01:08:52,925 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995604  0.997747  0.996909  0.998687  0.995802
real potato   0.923820  0.960352  0.957420  0.963402  0.999905
fake potato   0.940460  0.969266  0.953220  0.985966  0.999955
real apple    0.795937  0.886326  0.984864  0.805794  0.999287
fake apple    0.607102  0.755476  0.979341  0.614977  0.998497
real orange   0.950485  0.974564  0.996611  0.953566  0.999935
fake orange   0.946708  0.972575  0.968156  0.977135  0.999843
real grape    0.797450  0.887263  0.969018  0.818315  0.999566
fake grape    0.898018  0.946219  0.933952  0.958916  0.999597
real lemon    0.674511  0.805572  0.796473  0.814983  0.999538
fake lemon    0.839058  0.912437  0.990789  0.845655  0.999657
real avocado  0.931012  0.964224  0.971343  0.957307  0.999934
fake avocado  0.508289  0.673949  1.000000  0.508289  0.999412
real pepper   0.863055  0.926444  0.888187  0.968255  0.999438
fake pepper   0.796613  0.886745  0.950373  0.831189  0.999494
real plant    0.863126  0.926486  0.960007  0.895320  0.998580
fake plant    0.751867  0.858311  0.814350  0.907400  0.999762
real banana   0.710171  0.830476  0.889932  0.778555  0.999286
fake banana   0.669625  0.802076  0.758407  0.851194  0.999227
real onion    0.644276  0.783611  0.660227  0.963857  0.999519
fake onion    0.932267  0.964896  0.971331  0.958646  0.999956
real unknown  0.796928  0.886939  0.882798  0.891221  0.999964
fake unknown  0.215963  0.355175  0.237852  0.701195  0.997855
total         0.784885  0.866397  0.891807  0.867384  0.999305
total(-bg)    0.775306  0.860427  0.887030  0.861415  0.999464
2026-09-26 01:08:53,478 - INFO: Epoch accounting: {'epoch': 380, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11261057, 38783, 46976, 92343, 131367, 82296, 69456, 138481, 190354, 68821, 73689, 44537, 38203, 285216, 128553, 212674, 19219, 78223, 67212, 88234, 41411, 5091, 36076], 'crops_with_class': [202, 22, 23, 29, 29, 24, 27, 29, 35, 33, 28, 18, 16, 66, 30, 20, 20, 24, 27, 33, 22, 5, 15], 'targeted_crops_by_class': [0, 7, 5, 6, 3, 5, 3, 6, 9, 4, 7, 8, 4, 6, 7, 4, 5, 3, 4, 6, 3, 2, 3], 'sampled_scene_counts': [1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2, 1, 2, 1, 0, 2, 0, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 0, 2, 1, 1, 1, 0, 1, 0, 2, 2, 1, 0, 0, 1, 0, 1, 2, 0, 2, 1, 0, 1, 0, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 2, 3, 0, 1, 1, 2, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 3, 0, 0, 1, 3, 1, 1, 0, 1, 4, 0, 0, 4, 1, 0, 2, 2, 0, 0, 3, 1, 0, 2, 2, 1, 1, 2, 2, 0, 2, 1, 3, 2, 2, 2, 1, 2, 1, 0, 2, 3, 1, 2, 2, 1, 3, 0, 3, 0, 2, 2, 1, 0, 4, 1, 2, 0, 0, 0, 0, 1, 2, 1, 0, 1, 2, 2, 2, 2, 0, 4, 1, 1, 2, 0, 0, 1, 2, 2, 0], 'learning_rate': 1.3982925131921038e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006112675025475922, 'train_segmentation_loss': 0.2877973601000734, 'val_foreground_miou_all22': 0.7753064318974766, 'val_psnr_ref1': 38.97787643432617, 'elapsed_seconds': 335.62392830848694, 'peak_cuda_allocated_gib': 7.507846832275391}

Epoch 381/500 | Batch 10/202 | Rec 0.000751 | Seg 0.268457 | Elapsed 0.2m | ETA 4.0m
Epoch 381/500 | Batch 20/202 | Rec 0.000635 | Seg 0.259856 | Elapsed 0.4m | ETA 3.8m
Epoch 381/500 | Batch 30/202 | Rec 0.000610 | Seg 0.259565 | Elapsed 0.6m | ETA 3.6m
Epoch 381/500 | Batch 40/202 | Rec 0.000650 | Seg 0.290761 | Elapsed 0.8m | ETA 3.4m
Epoch 381/500 | Batch 50/202 | Rec 0.000617 | Seg 0.276291 | Elapsed 1.0m | ETA 3.2m
Epoch 381/500 | Batch 60/202 | Rec 0.000596 | Seg 0.268228 | Elapsed 1.3m | ETA 3.0m
Epoch 381/500 | Batch 70/202 | Rec 0.000588 | Seg 0.270181 | Elapsed 1.5m | ETA 2.7m
Epoch 381/500 | Batch 80/202 | Rec 0.000583 | Seg 0.270562 | Elapsed 1.7m | ETA 2.5m
Epoch 381/500 | Batch 90/202 | Rec 0.000567 | Seg 0.265509 | Elapsed 1.9m | ETA 2.3m
Epoch 381/500 | Batch 100/202 | Rec 0.000589 | Seg 0.276256 | Elapsed 2.1m | ETA 2.1m
Epoch 381/500 | Batch 110/202 | Rec 0.000586 | Seg 0.278578 | Elapsed 2.3m | ETA 1.9m
Epoch 381/500 | Batch 120/202 | Rec 0.000573 | Seg 0.272945 | Elapsed 2.5m | ETA 1.7m
Epoch 381/500 | Batch 130/202 | Rec 0.000575 | Seg 0.274758 | Elapsed 2.7m | ETA 1.5m
Epoch 381/500 | Batch 140/202 | Rec 0.000577 | Seg 0.275381 | Elapsed 2.9m | ETA 1.3m
Epoch 381/500 | Batch 150/202 | Rec 0.000579 | Seg 0.279734 | Elapsed 3.1m | ETA 1.1m
Epoch 381/500 | Batch 160/202 | Rec 0.000571 | Seg 0.275967 | Elapsed 3.3m | ETA 0.9m
Epoch 381/500 | Batch 170/202 | Rec 0.000576 | Seg 0.273518 | Elapsed 3.5m | ETA 0.7m
Epoch 381/500 | Batch 180/202 | Rec 0.000582 | Seg 0.277380 | Elapsed 3.7m | ETA 0.5m
Epoch 381/500 | Batch 190/202 | Rec 0.000581 | Seg 0.276411 | Elapsed 3.9m | ETA 0.2m
Epoch 381/500 | Batch 200/202 | Rec 0.000581 | Seg 0.277438 | Elapsed 4.1m | ETA 0.0m
Epoch 381/500 | Batch 202/202 | Rec 0.000581 | Seg 0.276586 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:13:04,007 - INFO: Rec loss: 0.0005806768676848151
2026-09-26 01:13:04,007 - INFO: Seg loss: 0.27658585453461304
2026-09-26 01:13:04,008 - INFO: λ_rec: 1
2026-09-26 01:13:04,008 - INFO: λ_seg: 0.0001
2026-09-26 01:14:21,209 - INFO: -------------------Epoch: 381------------------------
2026-09-26 01:14:21,213 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.976829  0.974703  0.000132
2026-09-26 01:14:21,221 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995785  0.997838  0.997206  0.998571  0.995976
real potato   0.899584  0.947088  0.957757  0.936751  0.999875
fake potato   0.950398  0.974518  0.973855  0.975283  0.999963
real apple    0.806770  0.893003  0.975831  0.823220  0.999320
fake apple    0.600056  0.749997  0.991890  0.603015  0.998483
real orange   0.919178  0.957837  0.996870  0.921839  0.999893
fake orange   0.925571  0.961297  0.949332  0.973670  0.999776
real grape    0.811347  0.895799  0.944719  0.851787  0.999586
fake grape    0.904871  0.950010  0.935750  0.964815  0.999625
real lemon    0.641458  0.781523  0.662603  0.952610  0.999374
fake lemon    0.847028  0.917130  0.997205  0.849044  0.999676
real avocado  0.927548  0.962362  0.957872  0.966995  0.999930
fake avocado  0.648394  0.786650  0.999607  0.648559  0.999579
real pepper   0.815987  0.898621  0.842526  0.962832  0.999206
fake pepper   0.694396  0.819590  0.953542  0.718712  0.999246
real plant    0.874494  0.932995  0.957665  0.909660  0.998694
fake plant    0.768190  0.868850  0.819185  0.925038  0.999778
real banana   0.620235  0.765562  0.903947  0.663996  0.999086
fake banana   0.736827  0.848425  0.824912  0.873424  0.999426
real onion    0.638261  0.779145  0.665431  0.939875  0.999519
fake onion    0.942864  0.970542  0.987976  0.953809  0.999964
real unknown  0.830060  0.907089  0.887671  0.927481  0.999970
fake unknown  0.222965  0.364593  0.243635  0.724375  0.997873
total         0.783577  0.866542  0.888130  0.872407  0.999296
total(-bg)    0.773931  0.860574  0.883172  0.866672  0.999447
2026-09-26 01:14:21,763 - INFO: Epoch accounting: {'epoch': 381, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11346805, 40361, 68249, 112817, 156009, 73059, 83749, 101960, 145662, 70363, 50037, 46687, 36567, 185440, 178038, 117300, 21233, 68144, 115103, 89611, 67738, 11431, 51909], 'crops_with_class': [202, 26, 30, 31, 37, 26, 30, 20, 29, 29, 24, 16, 15, 48, 40, 16, 21, 22, 44, 41, 31, 16, 25], 'targeted_crops_by_class': [0, 8, 3, 4, 5, 5, 7, 4, 6, 4, 7, 5, 2, 2, 8, 7, 4, 2, 5, 7, 10, 6, 6], 'sampled_scene_counts': [0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 2, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 2, 1, 0, 2, 0, 1, 2, 0, 1, 3, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 1, 2, 1, 2, 2, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 3, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 2, 2, 1, 0, 1, 1, 0, 3, 2, 0, 2, 0, 2, 2, 0, 1, 0, 1, 1, 1, 1, 4, 1, 0, 2, 0, 1, 5, 4, 1, 1, 0, 1, 3, 2, 0, 2, 4, 1, 1, 0, 2, 1, 1, 5, 1, 1, 0, 2, 4, 1, 3, 1, 0, 1, 1, 3, 0, 1, 2, 1, 2, 1, 2, 1, 0, 3, 0, 3, 4, 1, 1, 3, 0, 2, 2, 1, 0, 1, 1, 2, 1, 1, 2], 'learning_rate': 1.3767689707357074e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005806768676848151, 'train_segmentation_loss': 0.27658585453461304, 'val_foreground_miou_all22': 0.7739310151478551, 'val_psnr_ref1': 38.97682861328125, 'elapsed_seconds': 328.27669620513916, 'peak_cuda_allocated_gib': 7.5080108642578125}

Epoch 382/500 | Batch 10/202 | Rec 0.000463 | Seg 0.228541 | Elapsed 0.2m | ETA 4.1m
Epoch 382/500 | Batch 20/202 | Rec 0.000492 | Seg 0.263412 | Elapsed 0.4m | ETA 3.9m
Epoch 382/500 | Batch 30/202 | Rec 0.000495 | Seg 0.248427 | Elapsed 0.6m | ETA 3.7m
Epoch 382/500 | Batch 40/202 | Rec 0.000549 | Seg 0.272759 | Elapsed 0.9m | ETA 3.5m
Epoch 382/500 | Batch 50/202 | Rec 0.000535 | Seg 0.273921 | Elapsed 1.1m | ETA 3.2m
Epoch 382/500 | Batch 60/202 | Rec 0.000560 | Seg 0.274446 | Elapsed 1.3m | ETA 3.0m
Epoch 382/500 | Batch 70/202 | Rec 0.000558 | Seg 0.273746 | Elapsed 1.5m | ETA 2.8m
Epoch 382/500 | Batch 80/202 | Rec 0.000578 | Seg 0.282772 | Elapsed 1.7m | ETA 2.6m
Epoch 382/500 | Batch 90/202 | Rec 0.000576 | Seg 0.282718 | Elapsed 1.9m | ETA 2.4m
Epoch 382/500 | Batch 100/202 | Rec 0.000593 | Seg 0.280889 | Elapsed 2.1m | ETA 2.2m
Epoch 382/500 | Batch 110/202 | Rec 0.000592 | Seg 0.287078 | Elapsed 2.3m | ETA 1.9m
Epoch 382/500 | Batch 120/202 | Rec 0.000597 | Seg 0.286512 | Elapsed 2.5m | ETA 1.7m
Epoch 382/500 | Batch 130/202 | Rec 0.000592 | Seg 0.283223 | Elapsed 2.7m | ETA 1.5m
Epoch 382/500 | Batch 140/202 | Rec 0.000593 | Seg 0.283783 | Elapsed 3.0m | ETA 1.3m
Epoch 382/500 | Batch 150/202 | Rec 0.000597 | Seg 0.286647 | Elapsed 3.2m | ETA 1.1m
Epoch 382/500 | Batch 160/202 | Rec 0.000600 | Seg 0.286875 | Elapsed 3.4m | ETA 0.9m
Epoch 382/500 | Batch 170/202 | Rec 0.000596 | Seg 0.285914 | Elapsed 3.6m | ETA 0.7m
Epoch 382/500 | Batch 180/202 | Rec 0.000600 | Seg 0.289724 | Elapsed 3.8m | ETA 0.5m
Epoch 382/500 | Batch 190/202 | Rec 0.000595 | Seg 0.286449 | Elapsed 4.0m | ETA 0.3m
Epoch 382/500 | Batch 200/202 | Rec 0.000587 | Seg 0.282375 | Elapsed 4.2m | ETA 0.0m
Epoch 382/500 | Batch 202/202 | Rec 0.000589 | Seg 0.282740 | Elapsed 4.3m | ETA 0.0m

2026-09-26 01:18:37,337 - INFO: Rec loss: 0.0005887553119158261
2026-09-26 01:18:37,337 - INFO: Seg loss: 0.2827395835135243
2026-09-26 01:18:37,337 - INFO: λ_rec: 1
2026-09-26 01:18:37,337 - INFO: λ_seg: 0.0001
2026-09-26 01:19:56,071 - INFO: -------------------Epoch: 382------------------------
2026-09-26 01:19:56,075 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.649859  0.974328  0.000142
2026-09-26 01:19:56,082 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995797  0.997844  0.997526  0.998263  0.995989
real potato   0.773193  0.872042  0.961149  0.798138  0.999720
fake potato   0.958915  0.978977  0.980260  0.977796  0.999969
real apple    0.764708  0.866618  0.912837  0.824945  0.999124
fake apple    0.585912  0.738849  0.986500  0.590648  0.998424
real orange   0.929174  0.963237  0.997643  0.931218  0.999906
fake orange   0.933891  0.965766  0.950320  0.981825  0.999801
real grape    0.825907  0.904604  0.934689  0.876489  0.999614
fake grape    0.908007  0.951736  0.927707  0.977148  0.999634
real lemon    0.626964  0.770669  0.649324  0.947936  0.999337
fake lemon    0.839012  0.912410  0.998457  0.840101  0.999659
real avocado  0.916432  0.956344  0.949506  0.963383  0.999918
fake avocado  0.575290  0.730346  0.999778  0.575363  0.999492
real pepper   0.803751  0.891150  0.833019  0.958118  0.999144
fake pepper   0.676465  0.806965  0.967096  0.692401  0.999211
real plant    0.880693  0.936512  0.958849  0.915289  0.998760
fake plant    0.781521  0.877314  0.841670  0.916219  0.999796
real banana   0.626460  0.770286  0.868713  0.691973  0.999073
fake banana   0.698143  0.822193  0.776859  0.873258  0.999305
real onion    0.637652  0.778691  0.659709  0.950177  0.999512
fake onion    0.947129  0.972797  0.988761  0.957436  0.999966
real unknown  0.750000  0.857093  0.798846  0.924618  0.999951
fake unknown  0.221801  0.363036  0.237280  0.772727  0.997716
total         0.767688  0.855890  0.877239  0.866760  0.999262
total(-bg)    0.757319  0.849438  0.871771  0.860782  0.999411
2026-09-26 01:19:56,655 - INFO: Epoch accounting: {'epoch': 382, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11304044, 41710, 52087, 115412, 132658, 84097, 72014, 160657, 158832, 85947, 45942, 56129, 35129, 220560, 126270, 198426, 25540, 82962, 81451, 65950, 51127, 7729, 33599], 'crops_with_class': [202, 26, 25, 28, 35, 21, 26, 27, 32, 38, 23, 18, 14, 55, 38, 25, 26, 25, 31, 29, 21, 8, 15], 'targeted_crops_by_class': [0, 3, 3, 2, 5, 5, 4, 8, 3, 4, 2, 5, 3, 4, 4, 5, 3, 6, 4, 5, 4, 3, 4], 'sampled_scene_counts': [0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 1, 0, 3, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 2, 1, 2, 1, 2, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 5, 1, 4, 0, 2, 1, 1, 3, 2, 0, 1, 2, 3, 2, 0, 1, 1, 1, 2, 0, 3, 1, 0, 2, 2, 3, 1, 2, 0, 2, 1, 0, 1, 3, 3, 2, 3, 1, 0, 0, 1, 3, 1, 1, 1, 1, 1, 3, 0, 0, 2, 1, 2, 1, 2, 2, 3, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 3, 0], 'learning_rate': 1.355388960714981e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005887553119158261, 'train_segmentation_loss': 0.2827395835135243, 'val_foreground_miou_all22': 0.7573192095023376, 'val_psnr_ref1': 38.64985946655273, 'elapsed_seconds': 334.88416481018066, 'peak_cuda_allocated_gib': 7.505405426025391}

Epoch 383/500 | Batch 10/202 | Rec 0.000583 | Seg 0.299414 | Elapsed 0.2m | ETA 3.9m
Epoch 383/500 | Batch 20/202 | Rec 0.000593 | Seg 0.290375 | Elapsed 0.4m | ETA 3.8m
Epoch 383/500 | Batch 30/202 | Rec 0.000609 | Seg 0.287060 | Elapsed 0.6m | ETA 3.6m
Epoch 383/500 | Batch 40/202 | Rec 0.000573 | Seg 0.279290 | Elapsed 0.8m | ETA 3.4m
Epoch 383/500 | Batch 50/202 | Rec 0.000558 | Seg 0.269268 | Elapsed 1.1m | ETA 3.2m
Epoch 383/500 | Batch 60/202 | Rec 0.000561 | Seg 0.267073 | Elapsed 1.3m | ETA 3.0m
Epoch 383/500 | Batch 70/202 | Rec 0.000560 | Seg 0.271871 | Elapsed 1.5m | ETA 2.8m
Epoch 383/500 | Batch 80/202 | Rec 0.000553 | Seg 0.272669 | Elapsed 1.7m | ETA 2.6m
Epoch 383/500 | Batch 90/202 | Rec 0.000555 | Seg 0.276609 | Elapsed 1.9m | ETA 2.4m
Epoch 383/500 | Batch 100/202 | Rec 0.000575 | Seg 0.282229 | Elapsed 2.1m | ETA 2.2m
Epoch 383/500 | Batch 110/202 | Rec 0.000563 | Seg 0.279676 | Elapsed 2.3m | ETA 1.9m
Epoch 383/500 | Batch 120/202 | Rec 0.000566 | Seg 0.285570 | Elapsed 2.5m | ETA 1.7m
Epoch 383/500 | Batch 130/202 | Rec 0.000569 | Seg 0.284234 | Elapsed 2.8m | ETA 1.5m
Epoch 383/500 | Batch 140/202 | Rec 0.000573 | Seg 0.284622 | Elapsed 3.0m | ETA 1.3m
Epoch 383/500 | Batch 150/202 | Rec 0.000570 | Seg 0.280292 | Elapsed 3.2m | ETA 1.1m
Epoch 383/500 | Batch 160/202 | Rec 0.000571 | Seg 0.280579 | Elapsed 3.4m | ETA 0.9m
Epoch 383/500 | Batch 170/202 | Rec 0.000571 | Seg 0.281034 | Elapsed 3.6m | ETA 0.7m
Epoch 383/500 | Batch 180/202 | Rec 0.000568 | Seg 0.278251 | Elapsed 3.8m | ETA 0.5m
Epoch 383/500 | Batch 190/202 | Rec 0.000567 | Seg 0.278253 | Elapsed 4.0m | ETA 0.3m
Epoch 383/500 | Batch 200/202 | Rec 0.000562 | Seg 0.276856 | Elapsed 4.2m | ETA 0.0m
Epoch 383/500 | Batch 202/202 | Rec 0.000562 | Seg 0.277039 | Elapsed 4.3m | ETA 0.0m

2026-09-26 01:24:12,390 - INFO: Rec loss: 0.0005624906158784755
2026-09-26 01:24:12,390 - INFO: Seg loss: 0.2770391187197206
2026-09-26 01:24:12,391 - INFO: λ_rec: 1
2026-09-26 01:24:12,391 - INFO: λ_seg: 0.0001
2026-09-26 01:25:34,019 - INFO: -------------------Epoch: 383------------------------
2026-09-26 01:25:34,023 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.005993  0.974796  0.000132
2026-09-26 01:25:34,030 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995556  0.997723  0.997080  0.998467  0.995757
real potato   0.363717  0.533381  0.999299  0.363810  0.999238
fake potato   0.646754  0.785441  0.985150  0.653121  0.999740
real apple    0.692192  0.818051  0.782130  0.857541  0.998684
fake apple    0.669376  0.801899  0.986255  0.675679  0.998740
real orange   0.657212  0.793106  0.999648  0.657365  0.999548
fake orange   0.835678  0.910435  0.853975  0.975003  0.999451
real grape    0.812131  0.896277  0.931092  0.864065  0.999583
fake grape    0.895796  0.944984  0.917035  0.974797  0.999581
real lemon    0.564855  0.721879  0.582206  0.949883  0.999140
fake lemon    0.862861  0.926333  0.997835  0.864479  0.999709
real avocado  0.842362  0.914387  0.868756  0.965189  0.999832
fake avocado  0.633941  0.775918  0.999799  0.634022  0.999562
real pepper   0.797368  0.887212  0.837962  0.942725  0.999124
fake pepper   0.656242  0.792399  0.977552  0.666283  0.999168
real plant    0.871819  0.931470  0.958403  0.906105  0.998667
fake plant    0.854277  0.921362  0.946071  0.898006  0.999878
real banana   0.510978  0.676307  0.890528  0.545226  0.998828
fake banana   0.715205  0.833908  0.811602  0.857581  0.999372
real onion    0.648335  0.786605  0.719183  0.868097  0.999575
fake onion    0.837994  0.911808  0.996274  0.840629  0.999897
real unknown  0.755660  0.860777  0.805995  0.923664  0.999952
fake unknown  0.226636  0.369488  0.241120  0.790474  0.997727
total         0.710737  0.817007  0.873259  0.811835  0.999163
total(-bg)    0.697790  0.808792  0.867630  0.803352  0.999318
2026-09-26 01:25:34,569 - INFO: Epoch accounting: {'epoch': 383, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11355783, 49614, 67424, 153988, 154077, 84359, 65810, 138661, 133131, 59421, 49984, 45435, 22522, 195736, 82261, 165694, 23388, 110716, 92771, 85997, 54925, 9843, 36732], 'crops_with_class': [202, 36, 31, 40, 33, 24, 25, 28, 22, 28, 21, 15, 10, 51, 22, 23, 20, 31, 39, 36, 23, 12, 19], 'targeted_crops_by_class': [0, 9, 3, 2, 4, 5, 7, 5, 1, 4, 4, 3, 1, 1, 4, 7, 4, 5, 6, 4, 3, 3, 3], 'sampled_scene_counts': [1, 1, 1, 1, 0, 0, 0, 2, 3, 2, 1, 0, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 1, 0, 1, 2, 1, 0, 1, 2, 1, 1, 2, 1, 2, 0, 1, 0, 1, 1, 0, 1, 1, 2, 1, 2, 0, 0, 2, 0, 1, 0, 0, 1, 5, 0, 0, 2, 3, 1, 1, 1, 0, 2, 2, 3, 2, 0, 1, 2, 2, 2, 1, 1, 2, 2, 1, 3, 1, 2, 1, 1, 1, 0, 2, 2, 3, 0, 1, 1, 0, 3, 2, 3, 2, 2, 1, 1, 1, 2, 1, 4, 1, 1, 1, 2, 0, 2, 2, 0, 0], 'learning_rate': 1.3341533271761063e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005624906158784755, 'train_segmentation_loss': 0.2770391187197206, 'val_foreground_miou_all22': 0.6977903729537046, 'val_psnr_ref1': 39.005992584228515, 'elapsed_seconds': 337.90562772750854, 'peak_cuda_allocated_gib': 7.513217926025391}

Epoch 384/500 | Batch 10/202 | Rec 0.000521 | Seg 0.216438 | Elapsed 0.2m | ETA 4.0m
Epoch 384/500 | Batch 20/202 | Rec 0.000558 | Seg 0.278190 | Elapsed 0.4m | ETA 3.8m
Epoch 384/500 | Batch 30/202 | Rec 0.000547 | Seg 0.271675 | Elapsed 0.6m | ETA 3.6m
Epoch 384/500 | Batch 40/202 | Rec 0.000560 | Seg 0.269246 | Elapsed 0.8m | ETA 3.4m
Epoch 384/500 | Batch 50/202 | Rec 0.000575 | Seg 0.283579 | Elapsed 1.0m | ETA 3.2m
Epoch 384/500 | Batch 60/202 | Rec 0.000612 | Seg 0.290826 | Elapsed 1.3m | ETA 3.0m
Epoch 384/500 | Batch 70/202 | Rec 0.000602 | Seg 0.279474 | Elapsed 1.5m | ETA 2.7m
Epoch 384/500 | Batch 80/202 | Rec 0.000596 | Seg 0.265978 | Elapsed 1.7m | ETA 2.6m
Epoch 384/500 | Batch 90/202 | Rec 0.000588 | Seg 0.263829 | Elapsed 1.9m | ETA 2.3m
Epoch 384/500 | Batch 100/202 | Rec 0.000616 | Seg 0.268267 | Elapsed 2.1m | ETA 2.1m
Epoch 384/500 | Batch 110/202 | Rec 0.000606 | Seg 0.264956 | Elapsed 2.3m | ETA 1.9m
Epoch 384/500 | Batch 120/202 | Rec 0.000619 | Seg 0.272666 | Elapsed 2.5m | ETA 1.7m
Epoch 384/500 | Batch 130/202 | Rec 0.000617 | Seg 0.273714 | Elapsed 2.7m | ETA 1.5m
Epoch 384/500 | Batch 140/202 | Rec 0.000614 | Seg 0.275379 | Elapsed 2.9m | ETA 1.3m
Epoch 384/500 | Batch 150/202 | Rec 0.000607 | Seg 0.276018 | Elapsed 3.2m | ETA 1.1m
Epoch 384/500 | Batch 160/202 | Rec 0.000617 | Seg 0.284040 | Elapsed 3.4m | ETA 0.9m
Epoch 384/500 | Batch 170/202 | Rec 0.000618 | Seg 0.282592 | Elapsed 3.6m | ETA 0.7m
Epoch 384/500 | Batch 180/202 | Rec 0.000620 | Seg 0.283827 | Elapsed 3.8m | ETA 0.5m
Epoch 384/500 | Batch 190/202 | Rec 0.000620 | Seg 0.284379 | Elapsed 4.0m | ETA 0.3m
Epoch 384/500 | Batch 200/202 | Rec 0.000616 | Seg 0.285677 | Elapsed 4.2m | ETA 0.0m
Epoch 384/500 | Batch 202/202 | Rec 0.000619 | Seg 0.287101 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:29:49,328 - INFO: Rec loss: 0.0006193049412104301
2026-09-26 01:29:49,329 - INFO: Seg loss: 0.28710135623886446
2026-09-26 01:29:49,329 - INFO: λ_rec: 1
2026-09-26 01:29:49,329 - INFO: λ_seg: 0.0001
2026-09-26 01:31:10,157 - INFO: -------------------Epoch: 384------------------------
2026-09-26 01:31:10,164 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.93467  0.974622  0.000133
2026-09-26 01:31:10,172 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995724  0.997808  0.996975  0.998742  0.995917
real potato   0.919806  0.958178  0.951244  0.965315  0.999899
fake potato   0.959820  0.979448  0.978270  0.980729  0.999970
real apple    0.778226  0.875234  0.990008  0.784387  0.999229
fake apple    0.648857  0.786991  0.977567  0.658665  0.998654
real orange   0.876155  0.933940  0.997370  0.878184  0.999836
fake orange   0.913643  0.954823  0.936098  0.974416  0.999736
real grape    0.748330  0.856002  0.951551  0.777973  0.999454
fake grape    0.896989  0.945648  0.926373  0.965846  0.999590
real lemon    0.726245  0.841366  0.824181  0.859387  0.999619
fake lemon    0.801225  0.889595  0.999101  0.801803  0.999579
real avocado  0.935690  0.966727  0.973211  0.960427  0.999939
fake avocado  0.564707  0.721760  0.999774  0.564779  0.999479
real pepper   0.829965  0.907033  0.853537  0.967796  0.999275
fake pepper   0.715625  0.834195  0.959387  0.737981  0.999301
real plant    0.866541  0.928449  0.942274  0.915121  0.998590
fake plant    0.816526  0.898948  0.887085  0.911235  0.999837
real banana   0.747988  0.855778  0.934910  0.789081  0.999403
fake banana   0.659469  0.794745  0.757517  0.835932  0.999206
real onion    0.620720  0.765932  0.636618  0.961324  0.999469
fake onion    0.922477  0.959625  0.975994  0.943894  0.999950
real unknown  0.604153  0.753187  0.653792  0.888359  0.999907
fake unknown  0.213135  0.351340  0.241835  0.642340  0.998002
total         0.772262  0.858989  0.884551  0.859292  0.999297
total(-bg)    0.762104  0.852679  0.879441  0.852953  0.999451
2026-09-26 01:31:10,710 - INFO: Epoch accounting: {'epoch': 384, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11256988, 47147, 56122, 133826, 127618, 102971, 74281, 167872, 146070, 68599, 64249, 30659, 30368, 240953, 112408, 240808, 21780, 83008, 70699, 77193, 43286, 7292, 34075], 'crops_with_class': [202, 29, 26, 31, 33, 32, 25, 27, 26, 32, 25, 11, 13, 58, 28, 24, 22, 23, 30, 35, 21, 10, 15], 'targeted_crops_by_class': [0, 3, 6, 9, 2, 7, 3, 6, 1, 3, 5, 3, 2, 4, 4, 8, 2, 5, 3, 4, 2, 5, 2], 'sampled_scene_counts': [1, 1, 3, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 3, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 3, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 2, 0, 1, 0, 0, 2, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 3, 0, 1, 0, 0, 2, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 1, 2, 1, 0, 1, 0, 1, 2, 2, 2, 2, 1, 1, 1, 2, 0, 1, 0, 2, 1, 2, 2, 1, 1, 4, 2, 1, 3, 2, 2, 2, 1, 0, 1, 1, 3, 1, 1, 2, 1, 0, 1, 1, 2, 2, 0, 0, 0, 1, 1, 2, 4, 2, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 3, 1, 2, 1, 2, 2, 3, 2, 2, 1, 1, 0, 2, 1, 2, 1, 0, 0], 'learning_rate': 1.313062908465537e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006193049412104301, 'train_segmentation_loss': 0.28710135623886446, 'val_foreground_miou_all22': 0.7621042452205262, 'val_psnr_ref1': 38.934669952392575, 'elapsed_seconds': 336.13206601142883, 'peak_cuda_allocated_gib': 7.510074615478516}

Epoch 385/500 | Batch 10/202 | Rec 0.000664 | Seg 0.325534 | Elapsed 0.2m | ETA 3.9m
Epoch 385/500 | Batch 20/202 | Rec 0.000685 | Seg 0.298051 | Elapsed 0.4m | ETA 3.8m
Epoch 385/500 | Batch 30/202 | Rec 0.000670 | Seg 0.310377 | Elapsed 0.6m | ETA 3.6m
Epoch 385/500 | Batch 40/202 | Rec 0.000644 | Seg 0.292822 | Elapsed 0.8m | ETA 3.4m
Epoch 385/500 | Batch 50/202 | Rec 0.000621 | Seg 0.289829 | Elapsed 1.0m | ETA 3.2m
Epoch 385/500 | Batch 60/202 | Rec 0.000620 | Seg 0.294403 | Elapsed 1.3m | ETA 3.0m
Epoch 385/500 | Batch 70/202 | Rec 0.000618 | Seg 0.297317 | Elapsed 1.5m | ETA 2.8m
Epoch 385/500 | Batch 80/202 | Rec 0.000620 | Seg 0.297039 | Elapsed 1.7m | ETA 2.6m
Epoch 385/500 | Batch 90/202 | Rec 0.000606 | Seg 0.289476 | Elapsed 1.9m | ETA 2.3m
Epoch 385/500 | Batch 100/202 | Rec 0.000612 | Seg 0.283188 | Elapsed 2.1m | ETA 2.1m
Epoch 385/500 | Batch 110/202 | Rec 0.000610 | Seg 0.287051 | Elapsed 2.3m | ETA 1.9m
Epoch 385/500 | Batch 120/202 | Rec 0.000605 | Seg 0.286820 | Elapsed 2.5m | ETA 1.7m
Epoch 385/500 | Batch 130/202 | Rec 0.000594 | Seg 0.280714 | Elapsed 2.7m | ETA 1.5m
Epoch 385/500 | Batch 140/202 | Rec 0.000597 | Seg 0.280700 | Elapsed 2.9m | ETA 1.3m
Epoch 385/500 | Batch 150/202 | Rec 0.000589 | Seg 0.279903 | Elapsed 3.1m | ETA 1.1m
Epoch 385/500 | Batch 160/202 | Rec 0.000590 | Seg 0.282506 | Elapsed 3.3m | ETA 0.9m
Epoch 385/500 | Batch 170/202 | Rec 0.000600 | Seg 0.279592 | Elapsed 3.6m | ETA 0.7m
Epoch 385/500 | Batch 180/202 | Rec 0.000596 | Seg 0.278483 | Elapsed 3.8m | ETA 0.5m
Epoch 385/500 | Batch 190/202 | Rec 0.000598 | Seg 0.278645 | Elapsed 4.0m | ETA 0.3m
Epoch 385/500 | Batch 200/202 | Rec 0.000595 | Seg 0.276648 | Elapsed 4.2m | ETA 0.0m
Epoch 385/500 | Batch 202/202 | Rec 0.000598 | Seg 0.277120 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:35:23,680 - INFO: Rec loss: 0.0005979451676052626
2026-09-26 01:35:23,680 - INFO: Seg loss: 0.2771202867463379
2026-09-26 01:35:23,680 - INFO: λ_rec: 1
2026-09-26 01:35:23,680 - INFO: λ_seg: 0.0001
2026-09-26 01:36:43,774 - INFO: -------------------Epoch: 385------------------------
2026-09-26 01:36:43,778 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.857625  0.974419  0.000136
2026-09-26 01:36:43,785 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995491  0.997690  0.996712  0.998771  0.995693
real potato   0.789414  0.882266  0.802696  0.979470  0.999687
fake potato   0.963957  0.981598  0.977367  0.985966  0.999973
real apple    0.591428  0.743220  0.981492  0.598098  0.998575
fake apple    0.552700  0.711875  0.991130  0.555448  0.998303
real orange   0.855558  0.922107  0.997575  0.857341  0.999809
fake orange   0.896589  0.945425  0.922601  0.969513  0.999680
real grape    0.627811  0.771306  0.862134  0.697873  0.999136
fake grape    0.907791  0.951617  0.947427  0.955946  0.999641
real lemon    0.760065  0.863629  0.949992  0.791742  0.999706
fake lemon    0.670296  0.802559  0.999462  0.670537  0.999302
real avocado  0.962054  0.980610  0.995936  0.965846  0.999965
fake avocado  0.583652  0.737050  1.000000  0.583652  0.999502
real pepper   0.817764  0.899697  0.842919  0.964792  0.999214
fake pepper   0.707810  0.828861  0.954151  0.732732  0.999279
real plant    0.846011  0.916533  0.936460  0.897532  0.998366
fake plant    0.761494  0.864550  0.807488  0.930406  0.999768
real banana   0.814031  0.897433  0.918105  0.877767  0.999549
fake banana   0.595826  0.746681  0.673172  0.838338  0.998954
real onion    0.539122  0.700511  0.546253  0.976355  0.999246
fake onion    0.918353  0.957389  0.960117  0.954776  0.999946
real unknown  0.375298  0.545727  0.391304  0.901717  0.999760
fake unknown  0.178929  0.303507  0.203230  0.599420  0.997682
total         0.726584  0.823993  0.854684  0.838437  0.999162
total(-bg)    0.714361  0.816098  0.848228  0.831149  0.999320
2026-09-26 01:36:44,340 - INFO: Epoch accounting: {'epoch': 385, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11336092, 48475, 46808, 100145, 139353, 67543, 73339, 135568, 199927, 81877, 42708, 50317, 36236, 149775, 151245, 131719, 24520, 81596, 109576, 94249, 61588, 11511, 64105], 'crops_with_class': [202, 28, 26, 30, 38, 24, 25, 27, 34, 34, 21, 18, 16, 48, 37, 21, 21, 24, 42, 43, 32, 12, 25], 'targeted_crops_by_class': [0, 4, 2, 3, 5, 4, 6, 6, 4, 6, 3, 4, 5, 1, 5, 3, 1, 8, 7, 6, 7, 5, 3], 'sampled_scene_counts': [1, 1, 2, 0, 3, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 2, 2, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 0, 0, 0, 2, 1, 1, 2, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 3, 2, 1, 1, 1, 1, 0, 2, 1, 0, 0, 2, 3, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 1, 1, 1, 3, 2, 2, 0, 1, 3, 1, 0, 1, 1, 5, 2, 2, 2, 3, 2, 4, 3, 2, 1, 2, 0, 1, 0, 1, 2, 1, 1, 3, 0, 1, 1, 0, 1, 0, 3, 1, 3, 0, 0, 0, 1, 0, 3, 2, 1, 1, 4, 1, 1, 2, 3, 4], 'learning_rate': 1.29211853719689e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005979451676052626, 'train_segmentation_loss': 0.2771202867463379, 'val_foreground_miou_all22': 0.7143614712100288, 'val_psnr_ref1': 38.85762512207031, 'elapsed_seconds': 333.6229248046875, 'peak_cuda_allocated_gib': 7.509799957275391}

Epoch 386/500 | Batch 10/202 | Rec 0.000489 | Seg 0.270136 | Elapsed 0.2m | ETA 4.0m
Epoch 386/500 | Batch 20/202 | Rec 0.000609 | Seg 0.279042 | Elapsed 0.4m | ETA 3.7m
Epoch 386/500 | Batch 30/202 | Rec 0.000598 | Seg 0.253014 | Elapsed 0.6m | ETA 3.6m
Epoch 386/500 | Batch 40/202 | Rec 0.000626 | Seg 0.279839 | Elapsed 0.8m | ETA 3.4m
Epoch 386/500 | Batch 50/202 | Rec 0.000645 | Seg 0.275171 | Elapsed 1.0m | ETA 3.2m
Epoch 386/500 | Batch 60/202 | Rec 0.000612 | Seg 0.266918 | Elapsed 1.2m | ETA 2.9m
Epoch 386/500 | Batch 70/202 | Rec 0.000604 | Seg 0.261130 | Elapsed 1.5m | ETA 2.7m
Epoch 386/500 | Batch 80/202 | Rec 0.000633 | Seg 0.287710 | Elapsed 1.7m | ETA 2.5m
Epoch 386/500 | Batch 90/202 | Rec 0.000619 | Seg 0.283324 | Elapsed 1.9m | ETA 2.3m
Epoch 386/500 | Batch 100/202 | Rec 0.000613 | Seg 0.278491 | Elapsed 2.1m | ETA 2.1m
Epoch 386/500 | Batch 110/202 | Rec 0.000616 | Seg 0.280024 | Elapsed 2.3m | ETA 1.9m
Epoch 386/500 | Batch 120/202 | Rec 0.000631 | Seg 0.281634 | Elapsed 2.5m | ETA 1.7m
Epoch 386/500 | Batch 130/202 | Rec 0.000626 | Seg 0.280967 | Elapsed 2.7m | ETA 1.5m
Epoch 386/500 | Batch 140/202 | Rec 0.000618 | Seg 0.277162 | Elapsed 2.9m | ETA 1.3m
Epoch 386/500 | Batch 150/202 | Rec 0.000628 | Seg 0.278091 | Elapsed 3.1m | ETA 1.1m
Epoch 386/500 | Batch 160/202 | Rec 0.000625 | Seg 0.278399 | Elapsed 3.3m | ETA 0.9m
Epoch 386/500 | Batch 170/202 | Rec 0.000628 | Seg 0.281123 | Elapsed 3.5m | ETA 0.7m
Epoch 386/500 | Batch 180/202 | Rec 0.000625 | Seg 0.280800 | Elapsed 3.8m | ETA 0.5m
Epoch 386/500 | Batch 190/202 | Rec 0.000628 | Seg 0.282562 | Elapsed 4.0m | ETA 0.3m
Epoch 386/500 | Batch 200/202 | Rec 0.000628 | Seg 0.283475 | Elapsed 4.2m | ETA 0.0m
Epoch 386/500 | Batch 202/202 | Rec 0.000625 | Seg 0.281867 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:40:57,248 - INFO: Rec loss: 0.0006251908596120959
2026-09-26 01:40:57,248 - INFO: Seg loss: 0.2818666146238252
2026-09-26 01:40:57,248 - INFO: λ_rec: 1
2026-09-26 01:40:57,248 - INFO: λ_seg: 0.0001
2026-09-26 01:42:20,436 - INFO: -------------------Epoch: 386------------------------
2026-09-26 01:42:20,440 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.991721  0.974757  0.000132
2026-09-26 01:42:20,446 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995716  0.997803  0.997001  0.998707  0.995909
real potato   0.911983  0.953916  0.953966  0.953966  0.999890
fake potato   0.961373  0.980256  0.975327  0.985337  0.999971
real apple    0.787683  0.881184  0.975106  0.803848  0.999252
fake apple    0.564810  0.721843  0.993064  0.567047  0.998350
real orange   0.836960  0.911195  0.993304  0.841709  0.999784
fake orange   0.890807  0.942201  0.912889  0.973564  0.999658
real grape    0.780204  0.876483  0.944839  0.817438  0.999519
fake grape    0.904167  0.949622  0.935773  0.963990  0.999622
real lemon    0.673383  0.804768  0.697978  0.950273  0.999458
fake lemon    0.848794  0.918164  0.994699  0.852651  0.999679
real avocado  0.904004  0.949532  0.939136  0.960263  0.999905
fake avocado  0.696927  0.821351  0.999817  0.697016  0.999637
real pepper   0.774467  0.872851  0.799168  0.961622  0.998976
fake pepper   0.604896  0.753766  0.942810  0.627937  0.999022
real plant    0.863379  0.926631  0.958780  0.896662  0.998581
fake plant    0.765617  0.867202  0.836869  0.899923  0.999781
real banana   0.671589  0.803484  0.890606  0.731971  0.999196
fake banana   0.724815  0.840406  0.819084  0.862973  0.999397
real onion    0.632767  0.775037  0.660714  0.937342  0.999509
fake onion    0.947082  0.972772  0.976138  0.969528  0.999966
real unknown  0.635410  0.777016  0.670124  0.924618  0.999915
fake unknown  0.213936  0.352428  0.239710  0.665520  0.997940
total         0.764816  0.854344  0.874213  0.862778  0.999257
total(-bg)    0.754321  0.847823  0.868632  0.856600  0.999409
2026-09-26 01:42:20,996 - INFO: Epoch accounting: {'epoch': 386, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11272345, 60450, 74052, 91015, 114170, 93349, 52283, 128736, 201882, 75277, 72280, 41655, 48502, 237319, 130169, 186534, 24501, 66298, 49745, 98461, 61622, 12826, 44801], 'crops_with_class': [202, 35, 27, 26, 34, 27, 18, 29, 34, 33, 26, 12, 18, 55, 31, 21, 23, 20, 24, 37, 27, 14, 18], 'targeted_crops_by_class': [0, 5, 8, 2, 4, 4, 3, 8, 5, 2, 3, 4, 6, 4, 6, 2, 6, 7, 2, 4, 4, 6, 3], 'sampled_scene_counts': [1, 1, 1, 2, 2, 1, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 0, 1, 0, 1, 1, 1, 2, 2, 0, 0, 1, 3, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 2, 1, 2, 0, 1, 0, 1, 1, 1, 0, 2, 0, 1, 0, 0, 1, 1, 1, 1, 3, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 3, 1, 1, 2, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2, 1, 2, 1, 4, 2, 1, 1, 0, 1, 1, 0, 0, 1, 2, 1, 0, 2, 1, 2, 1, 2, 0, 1, 4, 1, 1, 1, 3, 4, 1, 2, 2, 3, 2, 0, 1, 1, 1, 3, 0, 1, 0, 1, 2, 0, 0, 1, 2, 1, 3, 3, 2, 1, 4, 1, 0, 2, 1, 2, 1, 1, 1, 0, 2, 0, 1, 1, 2, 1, 2], 'learning_rate': 1.271321040218081e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006251908596120959, 'train_segmentation_loss': 0.2818666146238252, 'val_foreground_miou_all22': 0.7543206644026209, 'val_psnr_ref1': 38.99172134399414, 'elapsed_seconds': 336.64803767204285, 'peak_cuda_allocated_gib': 7.512241363525391}

Epoch 387/500 | Batch 10/202 | Rec 0.000516 | Seg 0.250086 | Elapsed 0.2m | ETA 4.0m
Epoch 387/500 | Batch 20/202 | Rec 0.000513 | Seg 0.245124 | Elapsed 0.4m | ETA 3.7m
Epoch 387/500 | Batch 30/202 | Rec 0.000589 | Seg 0.263682 | Elapsed 0.6m | ETA 3.5m
Epoch 387/500 | Batch 40/202 | Rec 0.000577 | Seg 0.245156 | Elapsed 0.8m | ETA 3.3m
Epoch 387/500 | Batch 50/202 | Rec 0.000594 | Seg 0.264072 | Elapsed 1.0m | ETA 3.1m
Epoch 387/500 | Batch 60/202 | Rec 0.000584 | Seg 0.254274 | Elapsed 1.2m | ETA 2.9m
Epoch 387/500 | Batch 70/202 | Rec 0.000578 | Seg 0.255905 | Elapsed 1.4m | ETA 2.7m
Epoch 387/500 | Batch 80/202 | Rec 0.000573 | Seg 0.255616 | Elapsed 1.7m | ETA 2.5m
Epoch 387/500 | Batch 90/202 | Rec 0.000580 | Seg 0.265532 | Elapsed 1.9m | ETA 2.3m
Epoch 387/500 | Batch 100/202 | Rec 0.000575 | Seg 0.260550 | Elapsed 2.1m | ETA 2.1m
Epoch 387/500 | Batch 110/202 | Rec 0.000578 | Seg 0.263224 | Elapsed 2.3m | ETA 1.9m
Epoch 387/500 | Batch 120/202 | Rec 0.000582 | Seg 0.266016 | Elapsed 2.5m | ETA 1.7m
Epoch 387/500 | Batch 130/202 | Rec 0.000582 | Seg 0.268200 | Elapsed 2.7m | ETA 1.5m
Epoch 387/500 | Batch 140/202 | Rec 0.000587 | Seg 0.274488 | Elapsed 2.9m | ETA 1.3m
Epoch 387/500 | Batch 150/202 | Rec 0.000593 | Seg 0.272195 | Elapsed 3.1m | ETA 1.1m
Epoch 387/500 | Batch 160/202 | Rec 0.000596 | Seg 0.274571 | Elapsed 3.3m | ETA 0.9m
Epoch 387/500 | Batch 170/202 | Rec 0.000592 | Seg 0.271833 | Elapsed 3.5m | ETA 0.7m
Epoch 387/500 | Batch 180/202 | Rec 0.000597 | Seg 0.274638 | Elapsed 3.7m | ETA 0.5m
Epoch 387/500 | Batch 190/202 | Rec 0.000594 | Seg 0.272992 | Elapsed 3.9m | ETA 0.2m
Epoch 387/500 | Batch 200/202 | Rec 0.000592 | Seg 0.270962 | Elapsed 4.2m | ETA 0.0m
Epoch 387/500 | Batch 202/202 | Rec 0.000600 | Seg 0.272704 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:46:33,076 - INFO: Rec loss: 0.0005996502397897755
2026-09-26 01:46:33,076 - INFO: Seg loss: 0.27270399448968985
2026-09-26 01:46:33,076 - INFO: λ_rec: 1
2026-09-26 01:46:33,076 - INFO: λ_seg: 0.0001
2026-09-26 01:47:55,892 - INFO: -------------------Epoch: 387------------------------
2026-09-26 01:47:55,897 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.036086  0.974888  0.00013
2026-09-26 01:47:55,904 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995658  0.997774  0.997734  0.997915  0.995857
real potato   0.422925  0.594403  0.999699  0.422979  0.999309
fake potato   0.661020  0.795873  0.997476  0.662128  0.999753
real apple    0.671465  0.803395  0.727276  0.897435  0.998485
fake apple    0.575543  0.730550  0.989707  0.579009  0.998388
real orange   0.699461  0.823108  0.986257  0.706346  0.999600
fake orange   0.859260  0.924253  0.874756  0.979800  0.999541
real grape    0.781661  0.877402  0.887253  0.867865  0.999494
fake grape    0.843483  0.915047  0.853633  0.986099  0.999323
real lemon    0.482363  0.650758  0.489369  0.971176  0.998775
fake lemon    0.871332  0.931193  0.991127  0.878182  0.999726
real avocado  0.787109  0.880824  0.809183  0.966502  0.999757
fake avocado  0.803005  0.890691  0.998259  0.804132  0.999764
real pepper   0.764662  0.866589  0.804408  0.939304  0.998943
fake pepper   0.582129  0.735833  0.956290  0.598041  0.998977
real plant    0.880886  0.936621  0.951410  0.922382  0.998752
fake plant    0.882718  0.937656  0.922150  0.953796  0.999899
real banana   0.423143  0.594614  0.821951  0.465843  0.998573
fake banana   0.718554  0.836181  0.795138  0.881802  0.999365
real onion    0.509313  0.674845  0.812262  0.577267  0.999498
fake onion    0.921329  0.959004  0.987949  0.931802  0.999950
real unknown  0.920801  0.958718  1.000000  0.920801  0.999987
fake unknown  0.230765  0.374958  0.247272  0.775625  0.997822
total         0.708199  0.812621  0.865242  0.812445  0.999110
total(-bg)    0.695133  0.804205  0.859219  0.804014  0.999258
2026-09-26 01:47:56,484 - INFO: Epoch accounting: {'epoch': 387, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11391505, 53512, 48503, 104170, 165715, 91040, 80012, 84737, 196352, 66082, 64699, 40862, 26148, 142301, 120632, 199383, 34079, 81828, 71765, 67333, 43255, 12058, 52301], 'crops_with_class': [202, 25, 24, 31, 36, 25, 30, 23, 34, 30, 27, 12, 12, 36, 35, 29, 30, 24, 24, 32, 21, 13, 24], 'targeted_crops_by_class': [0, 4, 5, 6, 4, 3, 5, 3, 4, 5, 5, 3, 6, 5, 6, 7, 8, 4, 1, 3, 2, 6, 5], 'sampled_scene_counts': [3, 0, 2, 1, 2, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2, 1, 0, 0, 2, 1, 2, 1, 1, 1, 1, 0, 3, 0, 2, 0, 1, 1, 1, 0, 0, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2, 0, 2, 1, 0, 2, 1, 0, 1, 2, 0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 2, 1, 1, 0, 1, 2, 0, 2, 0, 1, 3, 2, 2, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 2, 0, 3, 2, 2, 1, 0, 0, 1, 1, 3, 0, 0, 0, 1, 2, 0, 1, 2, 1, 3, 2, 0, 1, 2, 3, 3, 3, 2, 0, 2, 0, 0, 2, 1, 1, 0, 1, 2, 2, 0, 1, 3, 3, 1, 1, 0, 2, 1, 4, 1, 2, 1, 2, 0, 2, 1, 2, 2, 0, 1, 0, 0, 0, 2, 3, 0], 'learning_rate': 1.2506712385786802e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005996502397897755, 'train_segmentation_loss': 0.27270399448968985, 'val_foreground_miou_all22': 0.6951331246648668, 'val_psnr_ref1': 39.036085510253905, 'elapsed_seconds': 335.4799282550812, 'peak_cuda_allocated_gib': 7.511974334716797}

Epoch 388/500 | Batch 10/202 | Rec 0.000422 | Seg 0.222550 | Elapsed 0.2m | ETA 4.0m
Epoch 388/500 | Batch 20/202 | Rec 0.000519 | Seg 0.260335 | Elapsed 0.4m | ETA 3.8m
Epoch 388/500 | Batch 30/202 | Rec 0.000541 | Seg 0.254777 | Elapsed 0.6m | ETA 3.6m
Epoch 388/500 | Batch 40/202 | Rec 0.000546 | Seg 0.258720 | Elapsed 0.8m | ETA 3.4m
Epoch 388/500 | Batch 50/202 | Rec 0.000554 | Seg 0.269127 | Elapsed 1.0m | ETA 3.2m
Epoch 388/500 | Batch 60/202 | Rec 0.000574 | Seg 0.281797 | Elapsed 1.2m | ETA 3.0m
Epoch 388/500 | Batch 70/202 | Rec 0.000576 | Seg 0.283612 | Elapsed 1.5m | ETA 2.7m
Epoch 388/500 | Batch 80/202 | Rec 0.000578 | Seg 0.282180 | Elapsed 1.7m | ETA 2.5m
Epoch 388/500 | Batch 90/202 | Rec 0.000585 | Seg 0.288596 | Elapsed 1.9m | ETA 2.3m
Epoch 388/500 | Batch 100/202 | Rec 0.000572 | Seg 0.284839 | Elapsed 2.1m | ETA 2.1m
Epoch 388/500 | Batch 110/202 | Rec 0.000586 | Seg 0.288340 | Elapsed 2.3m | ETA 1.9m
Epoch 388/500 | Batch 120/202 | Rec 0.000585 | Seg 0.279560 | Elapsed 2.5m | ETA 1.7m
Epoch 388/500 | Batch 130/202 | Rec 0.000595 | Seg 0.283340 | Elapsed 2.7m | ETA 1.5m
Epoch 388/500 | Batch 140/202 | Rec 0.000597 | Seg 0.283159 | Elapsed 2.9m | ETA 1.3m
Epoch 388/500 | Batch 150/202 | Rec 0.000592 | Seg 0.282150 | Elapsed 3.1m | ETA 1.1m
Epoch 388/500 | Batch 160/202 | Rec 0.000593 | Seg 0.284376 | Elapsed 3.3m | ETA 0.9m
Epoch 388/500 | Batch 170/202 | Rec 0.000592 | Seg 0.281548 | Elapsed 3.5m | ETA 0.7m
Epoch 388/500 | Batch 180/202 | Rec 0.000592 | Seg 0.279785 | Elapsed 3.8m | ETA 0.5m
Epoch 388/500 | Batch 190/202 | Rec 0.000589 | Seg 0.278590 | Elapsed 4.0m | ETA 0.3m
Epoch 388/500 | Batch 200/202 | Rec 0.000588 | Seg 0.278201 | Elapsed 4.2m | ETA 0.0m
Epoch 388/500 | Batch 202/202 | Rec 0.000588 | Seg 0.277472 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:52:09,593 - INFO: Rec loss: 0.0005876343252971805
2026-09-26 01:52:09,593 - INFO: Seg loss: 0.27747194207098225
2026-09-26 01:52:09,593 - INFO: λ_rec: 1
2026-09-26 01:52:09,594 - INFO: λ_seg: 0.0001
2026-09-26 01:53:30,348 - INFO: -------------------Epoch: 388------------------------
2026-09-26 01:53:30,352 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.082737  0.975099  0.000129
2026-09-26 01:53:30,359 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995759  0.997825  0.997019  0.998732  0.995951
real potato   0.539046  0.700448  0.986336  0.543101  0.999444
fake potato   0.697151  0.821506  0.979692  0.707373  0.999776
real apple    0.732573  0.845598  0.831006  0.860814  0.998916
fake apple    0.586149  0.739037  0.991833  0.588991  0.998430
real orange   0.914493  0.955287  0.996229  0.917670  0.999887
fake orange   0.927760  0.962477  0.958558  0.966528  0.999785
real grape    0.833357  0.909055  0.967428  0.857414  0.999642
fake grape    0.902174  0.948521  0.932250  0.965475  0.999613
real lemon    0.506194  0.672104  0.521773  0.944300  0.998917
fake lemon    0.847392  0.917343  0.985827  0.857843  0.999673
real avocado  0.905766  0.950503  0.941669  0.959606  0.999907
fake avocado  0.789876  0.882555  0.999839  0.789977  0.999749
real pepper   0.818334  0.900042  0.847486  0.959661  0.999221
fake pepper   0.706286  0.827815  0.933542  0.743678  0.999263
real plant    0.871926  0.931532  0.962231  0.902825  0.998674
fake plant    0.832642  0.908629  0.933482  0.885161  0.999858
real banana   0.447023  0.617806  0.879579  0.476165  0.998676
fake banana   0.727505  0.842211  0.833036  0.851692  0.999413
real onion    0.652462  0.789635  0.715010  0.881777  0.999576
fake onion    0.932646  0.965099  0.990580  0.940992  0.999957
real unknown  0.808848  0.894274  0.865952  0.924618  0.999965
fake unknown  0.200560  0.334074  0.222083  0.674212  0.997736
total         0.746779  0.839712  0.881410  0.834722  0.999219
total(-bg)    0.735462  0.832525  0.876155  0.827267  0.999367
2026-09-26 01:53:31,085 - INFO: Epoch accounting: {'epoch': 388, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11320810, 38237, 53501, 113187, 115455, 68787, 66274, 168573, 235725, 50484, 56695, 39257, 39555, 200183, 125278, 134492, 23509, 101158, 69013, 103444, 71290, 8241, 35124], 'crops_with_class': [202, 26, 24, 32, 32, 26, 21, 32, 37, 22, 25, 13, 13, 50, 34, 21, 21, 27, 33, 39, 28, 9, 14], 'targeted_crops_by_class': [0, 3, 5, 4, 6, 4, 7, 4, 5, 4, 4, 5, 4, 3, 3, 0, 7, 7, 4, 6, 5, 3, 3], 'sampled_scene_counts': [0, 1, 0, 1, 1, 2, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 3, 0, 0, 0, 0, 1, 0, 3, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 3, 0, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1, 0, 4, 1, 0, 1, 0, 1, 4, 0, 0, 1, 1, 1, 3, 0, 1, 1, 1, 0, 2, 0, 1, 0, 2, 3, 1, 1, 0, 2, 1, 1, 0, 2, 3, 0, 2, 1, 2, 1, 1, 1, 4, 1, 2, 1, 0, 1, 5, 1, 0, 0, 0, 3, 1, 1, 2, 1, 3, 3, 0, 2, 2, 0, 4, 2, 1, 2, 0, 2, 1, 0, 0, 0, 2, 2, 2, 1, 1, 2, 1], 'learning_rate': 1.2301699474974979e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005876343252971805, 'train_segmentation_loss': 0.27747194207098225, 'val_foreground_miou_all22': 0.7354619990532592, 'val_psnr_ref1': 39.08273696899414, 'elapsed_seconds': 334.5940341949463, 'peak_cuda_allocated_gib': 7.512393951416016}

Epoch 389/500 | Batch 10/202 | Rec 0.000643 | Seg 0.337833 | Elapsed 0.2m | ETA 4.0m
Epoch 389/500 | Batch 20/202 | Rec 0.000632 | Seg 0.289653 | Elapsed 0.4m | ETA 3.7m
Epoch 389/500 | Batch 30/202 | Rec 0.000596 | Seg 0.294959 | Elapsed 0.6m | ETA 3.5m
Epoch 389/500 | Batch 40/202 | Rec 0.000589 | Seg 0.299540 | Elapsed 0.8m | ETA 3.3m
Epoch 389/500 | Batch 50/202 | Rec 0.000587 | Seg 0.292495 | Elapsed 1.0m | ETA 3.1m
Epoch 389/500 | Batch 60/202 | Rec 0.000575 | Seg 0.280268 | Elapsed 1.2m | ETA 2.9m
Epoch 389/500 | Batch 70/202 | Rec 0.000573 | Seg 0.279457 | Elapsed 1.4m | ETA 2.7m
Epoch 389/500 | Batch 80/202 | Rec 0.000582 | Seg 0.285949 | Elapsed 1.6m | ETA 2.5m
Epoch 389/500 | Batch 90/202 | Rec 0.000596 | Seg 0.290508 | Elapsed 1.8m | ETA 2.3m
Epoch 389/500 | Batch 100/202 | Rec 0.000586 | Seg 0.285564 | Elapsed 2.1m | ETA 2.1m
Epoch 389/500 | Batch 110/202 | Rec 0.000585 | Seg 0.287073 | Elapsed 2.3m | ETA 1.9m
Epoch 389/500 | Batch 120/202 | Rec 0.000587 | Seg 0.289514 | Elapsed 2.5m | ETA 1.7m
Epoch 389/500 | Batch 130/202 | Rec 0.000583 | Seg 0.286119 | Elapsed 2.7m | ETA 1.5m
Epoch 389/500 | Batch 140/202 | Rec 0.000591 | Seg 0.290918 | Elapsed 2.9m | ETA 1.3m
Epoch 389/500 | Batch 150/202 | Rec 0.000590 | Seg 0.289035 | Elapsed 3.1m | ETA 1.1m
Epoch 389/500 | Batch 160/202 | Rec 0.000586 | Seg 0.284503 | Elapsed 3.3m | ETA 0.9m
Epoch 389/500 | Batch 170/202 | Rec 0.000583 | Seg 0.281868 | Elapsed 3.5m | ETA 0.7m
Epoch 389/500 | Batch 180/202 | Rec 0.000582 | Seg 0.282313 | Elapsed 3.7m | ETA 0.5m
Epoch 389/500 | Batch 190/202 | Rec 0.000580 | Seg 0.281331 | Elapsed 3.9m | ETA 0.2m
Epoch 389/500 | Batch 200/202 | Rec 0.000580 | Seg 0.280863 | Elapsed 4.1m | ETA 0.0m
Epoch 389/500 | Batch 202/202 | Rec 0.000580 | Seg 0.281283 | Elapsed 4.2m | ETA 0.0m

2026-09-26 01:57:42,090 - INFO: Rec loss: 0.0005796695798623956
2026-09-26 01:57:42,090 - INFO: Seg loss: 0.281282659269648
2026-09-26 01:57:42,090 - INFO: λ_rec: 1
2026-09-26 01:57:42,090 - INFO: λ_seg: 0.0001
2026-09-26 01:59:00,701 - INFO: -------------------Epoch: 389------------------------
2026-09-26 01:59:00,705 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.943562  0.974756  0.000133
2026-09-26 01:59:00,712 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995591  0.997741  0.996821  0.998762  0.995789
real potato   0.454453  0.624870  0.988956  0.456771  0.999344
fake potato   0.672199  0.803922  0.986001  0.678676  0.999759
real apple    0.725281  0.840718  0.812500  0.871075  0.998862
fake apple    0.602401  0.751826  0.983922  0.608390  0.998484
real orange   0.944843  0.971589  0.998534  0.946156  0.999927
fake orange   0.943390  0.970821  0.969143  0.972604  0.999833
real grape    0.792513  0.884199  0.970149  0.812322  0.999556
fake grape    0.897872  0.946138  0.927428  0.965722  0.999594
real lemon    0.528093  0.691133  0.545810  0.942093  0.999011
fake lemon    0.854875  0.921710  0.995482  0.858204  0.999692
real avocado  0.879172  0.935652  0.916404  0.955829  0.999878
fake avocado  0.720678  0.837619  0.999646  0.720862  0.999666
real pepper   0.856092  0.922417  0.895204  0.951443  0.999415
fake pepper   0.764510  0.866491  0.955622  0.792651  0.999418
real plant    0.864688  0.927384  0.949775  0.906120  0.998582
fake plant    0.754453  0.859994  0.894410  0.828221  0.999785
real banana   0.456175  0.626494  0.900790  0.480307  0.998713
fake banana   0.730980  0.844535  0.858403  0.831204  0.999437
real onion    0.632707  0.774992  0.691147  0.882114  0.999537
fake onion    0.882917  0.937769  0.991112  0.889964  0.999926
real unknown  0.910391  0.953044  0.998954  0.911259  0.999986
fake unknown  0.216261  0.355579  0.234104  0.739406  0.997742
total         0.742632  0.836810  0.889579  0.826094  0.999215
total(-bg)    0.731134  0.829495  0.884704  0.818245  0.999370
2026-09-26 01:59:01,273 - INFO: Epoch accounting: {'epoch': 389, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11285991, 42982, 55800, 117384, 172354, 79684, 78456, 146512, 218944, 86433, 49768, 43288, 40684, 262352, 108096, 115120, 28255, 67832, 63255, 75688, 42011, 16069, 41314], 'crops_with_class': [202, 27, 25, 33, 45, 24, 31, 31, 41, 37, 25, 13, 19, 59, 28, 17, 28, 22, 23, 30, 20, 15, 20], 'targeted_crops_by_class': [0, 4, 4, 4, 4, 4, 3, 3, 6, 8, 4, 7, 4, 7, 6, 3, 8, 7, 2, 4, 4, 9, 5], 'sampled_scene_counts': [1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 1, 2, 2, 2, 2, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0, 4, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 3, 1, 5, 2, 2, 2, 1, 4, 0, 0, 1, 0, 1, 1, 1, 2, 1, 3, 1, 3, 0, 3, 0, 3, 0, 1, 2, 0, 1, 2, 2, 3, 5, 0, 3, 2, 2, 1, 2, 1, 2, 1, 3, 2, 1, 1, 2, 1, 2, 0, 2, 1, 0, 3, 2, 0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 0, 1, 1, 2, 0, 0, 1, 3], 'learning_rate': 1.209817976330403e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005796695798623956, 'train_segmentation_loss': 0.281282659269648, 'val_foreground_miou_all22': 0.7311338405152636, 'val_psnr_ref1': 38.943561706542965, 'elapsed_seconds': 330.1795566082001, 'peak_cuda_allocated_gib': 7.512241363525391}

Epoch 390/500 | Batch 10/202 | Rec 0.000605 | Seg 0.284123 | Elapsed 0.2m | ETA 4.2m
Epoch 390/500 | Batch 20/202 | Rec 0.000633 | Seg 0.309598 | Elapsed 0.4m | ETA 3.9m
Epoch 390/500 | Batch 30/202 | Rec 0.000585 | Seg 0.280024 | Elapsed 0.6m | ETA 3.6m
Epoch 390/500 | Batch 40/202 | Rec 0.000584 | Seg 0.279959 | Elapsed 0.8m | ETA 3.4m
Epoch 390/500 | Batch 50/202 | Rec 0.000595 | Seg 0.296104 | Elapsed 1.0m | ETA 3.2m
Epoch 390/500 | Batch 60/202 | Rec 0.000581 | Seg 0.290237 | Elapsed 1.2m | ETA 2.9m
Epoch 390/500 | Batch 70/202 | Rec 0.000587 | Seg 0.291180 | Elapsed 1.5m | ETA 2.7m
Epoch 390/500 | Batch 80/202 | Rec 0.000590 | Seg 0.292757 | Elapsed 1.7m | ETA 2.5m
Epoch 390/500 | Batch 90/202 | Rec 0.000580 | Seg 0.287615 | Elapsed 1.9m | ETA 2.3m
Epoch 390/500 | Batch 100/202 | Rec 0.000573 | Seg 0.286308 | Elapsed 2.1m | ETA 2.1m
Epoch 390/500 | Batch 110/202 | Rec 0.000575 | Seg 0.285205 | Elapsed 2.3m | ETA 1.9m
Epoch 390/500 | Batch 120/202 | Rec 0.000569 | Seg 0.285172 | Elapsed 2.5m | ETA 1.7m
Epoch 390/500 | Batch 130/202 | Rec 0.000568 | Seg 0.286475 | Elapsed 2.7m | ETA 1.5m
Epoch 390/500 | Batch 140/202 | Rec 0.000567 | Seg 0.284767 | Elapsed 2.9m | ETA 1.3m
Epoch 390/500 | Batch 150/202 | Rec 0.000561 | Seg 0.282816 | Elapsed 3.1m | ETA 1.1m
Epoch 390/500 | Batch 160/202 | Rec 0.000555 | Seg 0.279594 | Elapsed 3.3m | ETA 0.9m
Epoch 390/500 | Batch 170/202 | Rec 0.000552 | Seg 0.278197 | Elapsed 3.5m | ETA 0.7m
Epoch 390/500 | Batch 180/202 | Rec 0.000560 | Seg 0.284380 | Elapsed 3.7m | ETA 0.5m
Epoch 390/500 | Batch 190/202 | Rec 0.000558 | Seg 0.284400 | Elapsed 3.9m | ETA 0.2m
Epoch 390/500 | Batch 200/202 | Rec 0.000557 | Seg 0.283609 | Elapsed 4.2m | ETA 0.0m
Epoch 390/500 | Batch 202/202 | Rec 0.000557 | Seg 0.284124 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:03:13,164 - INFO: Rec loss: 0.0005572533547892097
2026-09-26 02:03:13,164 - INFO: Seg loss: 0.284124413781827
2026-09-26 02:03:13,164 - INFO: λ_rec: 1
2026-09-26 02:03:13,164 - INFO: λ_seg: 0.0001
2026-09-26 02:04:33,846 - INFO: -------------------Epoch: 390------------------------
2026-09-26 02:04:33,850 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.060342  0.974928  0.00013
2026-09-26 02:04:33,857 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995500  0.997695  0.996716  0.998777  0.995702
real potato   0.281561  0.439369  1.000000  0.281561  0.999140
fake potato   0.656406  0.792519  0.989342  0.661081  0.999748
real apple    0.689066  0.815864  0.753021  0.890270  0.998614
fake apple    0.704476  0.826570  0.958920  0.726398  0.998849
real orange   0.855656  0.922164  0.998650  0.856647  0.999810
fake orange   0.905269  0.950230  0.928277  0.973350  0.999708
real grape    0.833583  0.909189  0.970635  0.855149  0.999644
fake grape    0.891114  0.942372  0.925411  0.960071  0.999566
real lemon    0.433846  0.605106  0.447647  0.933654  0.998568
fake lemon    0.841828  0.914072  0.970815  0.863686  0.999657
real avocado  0.853934  0.921163  0.879027  0.967652  0.999846
fake avocado  0.806756  0.892994  0.999526  0.807065  0.999769
real pepper   0.788974  0.881991  0.828761  0.942641  0.999078
fake pepper   0.647044  0.785655  0.944370  0.672684  0.999125
real plant    0.864988  0.927557  0.960922  0.896525  0.998600
fake plant    0.780353  0.876577  0.917610  0.839149  0.999812
real banana   0.284099  0.442449  0.854118  0.298588  0.998309
fake banana   0.716176  0.834568  0.857743  0.812707  0.999408
real onion    0.612865  0.759921  0.726656  0.796487  0.999545
fake onion    0.885088  0.938992  0.995664  0.888513  0.999927
real unknown  0.896946  0.945624  1.000000  0.896946  0.999984
fake unknown  0.242126  0.389816  0.277386  0.655741  0.998271
total         0.715985  0.813585  0.877444  0.803276  0.999160
total(-bg)    0.703280  0.805217  0.872023  0.794389  0.999317
2026-09-26 02:04:34,381 - INFO: Epoch accounting: {'epoch': 390, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11262915, 44856, 48714, 160109, 153078, 108679, 76055, 147022, 151647, 83735, 78553, 56237, 46682, 185388, 119888, 142330, 27716, 79182, 65209, 79154, 67932, 11886, 41305], 'crops_with_class': [202, 27, 24, 42, 38, 31, 28, 26, 31, 37, 31, 19, 18, 50, 34, 22, 25, 25, 25, 36, 26, 12, 19], 'targeted_crops_by_class': [0, 4, 6, 5, 5, 8, 7, 4, 4, 4, 5, 5, 4, 3, 3, 6, 2, 3, 5, 4, 4, 5, 4], 'sampled_scene_counts': [0, 0, 1, 0, 1, 1, 2, 2, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 2, 2, 1, 0, 1, 0, 0, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 3, 1, 0, 2, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 2, 1, 2, 3, 3, 0, 1, 3, 1, 0, 1, 0, 2, 1, 4, 1, 1, 2, 1, 0, 1, 2, 0, 1, 2, 2, 3, 4, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 5, 2, 2, 1, 1, 1, 0, 1, 0, 3, 1, 3, 3, 2, 0, 2, 2, 0, 2, 3, 0, 1, 0, 2, 1, 2, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 3, 1, 2, 1], 'learning_rate': 1.1896161285383653e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005572533547892097, 'train_segmentation_loss': 0.284124413781827, 'val_foreground_miou_all22': 0.7032797462953606, 'val_psnr_ref1': 39.06034225463867, 'elapsed_seconds': 333.0999894142151, 'peak_cuda_allocated_gib': 7.511508941650391}

Epoch 391/500 | Batch 10/202 | Rec 0.000542 | Seg 0.283563 | Elapsed 0.2m | ETA 4.0m
Epoch 391/500 | Batch 20/202 | Rec 0.000596 | Seg 0.280488 | Elapsed 0.4m | ETA 3.8m
Epoch 391/500 | Batch 30/202 | Rec 0.000552 | Seg 0.270948 | Elapsed 0.6m | ETA 3.6m
Epoch 391/500 | Batch 40/202 | Rec 0.000516 | Seg 0.258368 | Elapsed 0.8m | ETA 3.4m
Epoch 391/500 | Batch 50/202 | Rec 0.000523 | Seg 0.249929 | Elapsed 1.0m | ETA 3.2m
Epoch 391/500 | Batch 60/202 | Rec 0.000526 | Seg 0.250212 | Elapsed 1.2m | ETA 2.9m
Epoch 391/500 | Batch 70/202 | Rec 0.000563 | Seg 0.253650 | Elapsed 1.4m | ETA 2.7m
Epoch 391/500 | Batch 80/202 | Rec 0.000563 | Seg 0.255376 | Elapsed 1.7m | ETA 2.5m
Epoch 391/500 | Batch 90/202 | Rec 0.000551 | Seg 0.255323 | Elapsed 1.9m | ETA 2.3m
Epoch 391/500 | Batch 100/202 | Rec 0.000543 | Seg 0.249020 | Elapsed 2.1m | ETA 2.1m
Epoch 391/500 | Batch 110/202 | Rec 0.000538 | Seg 0.247852 | Elapsed 2.3m | ETA 1.9m
Epoch 391/500 | Batch 120/202 | Rec 0.000525 | Seg 0.246130 | Elapsed 2.5m | ETA 1.7m
Epoch 391/500 | Batch 130/202 | Rec 0.000551 | Seg 0.246849 | Elapsed 2.7m | ETA 1.5m
Epoch 391/500 | Batch 140/202 | Rec 0.000552 | Seg 0.248430 | Elapsed 2.9m | ETA 1.3m
Epoch 391/500 | Batch 150/202 | Rec 0.000559 | Seg 0.249822 | Elapsed 3.1m | ETA 1.1m
Epoch 391/500 | Batch 160/202 | Rec 0.000557 | Seg 0.247095 | Elapsed 3.3m | ETA 0.9m
Epoch 391/500 | Batch 170/202 | Rec 0.000563 | Seg 0.252231 | Elapsed 3.5m | ETA 0.7m
Epoch 391/500 | Batch 180/202 | Rec 0.000562 | Seg 0.252232 | Elapsed 3.7m | ETA 0.5m
Epoch 391/500 | Batch 190/202 | Rec 0.000561 | Seg 0.254942 | Elapsed 3.9m | ETA 0.2m
Epoch 391/500 | Batch 200/202 | Rec 0.000566 | Seg 0.256152 | Elapsed 4.1m | ETA 0.0m
Epoch 391/500 | Batch 202/202 | Rec 0.000565 | Seg 0.256623 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:08:45,627 - INFO: Rec loss: 0.0005648797580374101
2026-09-26 02:08:45,628 - INFO: Seg loss: 0.25662277192615046
2026-09-26 02:08:45,628 - INFO: λ_rec: 1
2026-09-26 02:08:45,628 - INFO: λ_seg: 0.0001
2026-09-26 02:10:08,117 - INFO: -------------------Epoch: 391------------------------
2026-09-26 02:10:08,122 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.945561  0.974734  0.000133
2026-09-26 02:10:08,129 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995864  0.997878  0.997169  0.998688  0.996052
real potato   0.897563  0.945966  0.967850  0.925147  0.999874
fake potato   0.944069  0.971180  0.977306  0.965228  0.999958
real apple    0.828829  0.906354  0.956438  0.861345  0.999386
fake apple    0.582338  0.736001  0.991578  0.585233  0.998415
real orange   0.895634  0.944894  0.994246  0.900301  0.999862
fake orange   0.922532  0.959655  0.947347  0.972391  0.999766
real grape    0.824431  0.903718  0.965603  0.849375  0.999622
fake grape    0.905430  0.950318  0.930480  0.971126  0.999625
real lemon    0.638990  0.779688  0.668056  0.936250  0.999378
fake lemon    0.846071  0.916568  0.993016  0.851136  0.999672
real avocado  0.918712  0.957584  0.950356  0.965025  0.999921
fake avocado  0.710479  0.830689  0.999641  0.710661  0.999653
real pepper   0.810975  0.895573  0.834739  0.966085  0.999176
fake pepper   0.683135  0.811692  0.927948  0.721401  0.999202
real plant    0.872101  0.931632  0.960957  0.904137  0.998674
fake plant    0.785369  0.879734  0.831173  0.934432  0.999797
real banana   0.644724  0.783942  0.904698  0.691702  0.999144
fake banana   0.730318  0.844093  0.841914  0.846384  0.999425
real onion    0.657777  0.793516  0.699768  0.916399  0.999569
fake onion    0.939100  0.968543  0.979002  0.958404  0.999961
real unknown  0.906191  0.950737  0.981707  0.921756  0.999985
fake unknown  0.221296  0.362357  0.246031  0.687613  0.997961
total         0.789649  0.870535  0.893349  0.871314  0.999308
total(-bg)    0.780276  0.864747  0.888630  0.865524  0.999456
2026-09-26 02:10:08,674 - INFO: Epoch accounting: {'epoch': 391, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11474816, 46111, 58022, 132432, 111167, 70526, 92804, 129046, 189790, 71923, 54014, 62739, 50841, 153620, 141616, 71664, 22317, 81325, 55829, 59278, 40364, 15409, 52619], 'crops_with_class': [202, 31, 29, 34, 30, 24, 32, 24, 31, 33, 21, 22, 19, 43, 31, 12, 24, 19, 24, 29, 20, 17, 25], 'targeted_crops_by_class': [0, 5, 4, 6, 5, 6, 7, 6, 5, 5, 3, 6, 6, 5, 2, 3, 4, 5, 7, 1, 6, 7, 6], 'sampled_scene_counts': [1, 2, 0, 0, 0, 1, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 0, 1, 0, 1, 1, 1, 1, 2, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 1, 2, 1, 1, 2, 1, 0, 1, 2, 1, 3, 1, 2, 3, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 3, 1, 0, 0, 1, 4, 0, 3, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 3, 1, 1, 1, 0, 2, 3, 3, 2, 2, 0, 0, 3, 1, 0, 2, 5, 2, 0, 4, 3, 1, 3, 3, 1, 1, 3, 1, 0, 1, 1, 1, 0, 1, 1, 2, 2, 0, 1, 0, 3, 0, 0, 1, 1, 1, 0, 0, 2, 2, 0, 4, 3, 2, 1, 1, 0, 1, 1, 1, 0, 1, 2], 'learning_rate': 1.16956520165575e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005648797580374101, 'train_segmentation_loss': 0.25662277192615046, 'val_foreground_miou_all22': 0.7802756539986432, 'val_psnr_ref1': 38.94556060791015, 'elapsed_seconds': 334.285368680954, 'peak_cuda_allocated_gib': 7.5089874267578125}

Epoch 392/500 | Batch 10/202 | Rec 0.000507 | Seg 0.243556 | Elapsed 0.2m | ETA 4.0m
Epoch 392/500 | Batch 20/202 | Rec 0.000534 | Seg 0.264733 | Elapsed 0.4m | ETA 3.8m
Epoch 392/500 | Batch 30/202 | Rec 0.000557 | Seg 0.275408 | Elapsed 0.6m | ETA 3.5m
Epoch 392/500 | Batch 40/202 | Rec 0.000554 | Seg 0.267215 | Elapsed 0.8m | ETA 3.4m
Epoch 392/500 | Batch 50/202 | Rec 0.000590 | Seg 0.287713 | Elapsed 1.0m | ETA 3.2m
Epoch 392/500 | Batch 60/202 | Rec 0.000582 | Seg 0.292485 | Elapsed 1.2m | ETA 2.9m
Epoch 392/500 | Batch 70/202 | Rec 0.000594 | Seg 0.292102 | Elapsed 1.5m | ETA 2.8m
Epoch 392/500 | Batch 80/202 | Rec 0.000583 | Seg 0.284047 | Elapsed 1.7m | ETA 2.5m
Epoch 392/500 | Batch 90/202 | Rec 0.000577 | Seg 0.283373 | Elapsed 1.9m | ETA 2.3m
Epoch 392/500 | Batch 100/202 | Rec 0.000563 | Seg 0.277399 | Elapsed 2.1m | ETA 2.1m
Epoch 392/500 | Batch 110/202 | Rec 0.000568 | Seg 0.279394 | Elapsed 2.3m | ETA 1.9m
Epoch 392/500 | Batch 120/202 | Rec 0.000573 | Seg 0.285225 | Elapsed 2.5m | ETA 1.7m
Epoch 392/500 | Batch 130/202 | Rec 0.000570 | Seg 0.287949 | Elapsed 2.7m | ETA 1.5m
Epoch 392/500 | Batch 140/202 | Rec 0.000573 | Seg 0.287633 | Elapsed 2.9m | ETA 1.3m
Epoch 392/500 | Batch 150/202 | Rec 0.000572 | Seg 0.286257 | Elapsed 3.1m | ETA 1.1m
Epoch 392/500 | Batch 160/202 | Rec 0.000574 | Seg 0.285043 | Elapsed 3.3m | ETA 0.9m
Epoch 392/500 | Batch 170/202 | Rec 0.000572 | Seg 0.282856 | Elapsed 3.5m | ETA 0.7m
Epoch 392/500 | Batch 180/202 | Rec 0.000568 | Seg 0.280626 | Elapsed 3.8m | ETA 0.5m
Epoch 392/500 | Batch 190/202 | Rec 0.000578 | Seg 0.280228 | Elapsed 4.0m | ETA 0.3m
Epoch 392/500 | Batch 200/202 | Rec 0.000575 | Seg 0.278664 | Elapsed 4.2m | ETA 0.0m
Epoch 392/500 | Batch 202/202 | Rec 0.000574 | Seg 0.277983 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:14:21,425 - INFO: Rec loss: 0.0005740659674635332
2026-09-26 02:14:21,425 - INFO: Seg loss: 0.27798253544929
2026-09-26 02:14:21,425 - INFO: λ_rec: 1
2026-09-26 02:14:21,425 - INFO: λ_seg: 0.0001
2026-09-26 02:15:41,819 - INFO: -------------------Epoch: 392------------------------
2026-09-26 02:15:41,824 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.992765  0.974857  0.000132
2026-09-26 02:15:41,831 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995665  0.997778  0.997067  0.998590  0.995861
real potato   0.481683  0.650139  0.942373  0.496302  0.999361
fake potato   0.794317  0.885320  0.978939  0.808127  0.999848
real apple    0.694754  0.819837  0.808981  0.831092  0.998740
fake apple    0.589382  0.741602  0.990678  0.592669  0.998441
real orange   0.936680  0.967255  0.993892  0.942103  0.999916
fake orange   0.942400  0.970296  0.962410  0.978414  0.999829
real grape    0.761018  0.864243  0.927751  0.808960  0.999470
fake grape    0.908828  0.952187  0.943693  0.960937  0.999643
real lemon    0.656519  0.792600  0.690853  0.929629  0.999428
fake lemon    0.826215  0.904789  0.998260  0.827407  0.999632
real avocado  0.887231  0.940196  0.915526  0.966338  0.999886
fake avocado  0.722973  0.839167  0.999647  0.723157  0.999668
real pepper   0.769197  0.869494  0.797667  0.955657  0.998951
fake pepper   0.567715  0.724210  0.930653  0.592792  0.998924
real plant    0.863832  0.926892  0.947160  0.907570  0.998569
fake plant    0.777230  0.874603  0.844520  0.907017  0.999793
real banana   0.643626  0.783129  0.890900  0.698696  0.999131
fake banana   0.722080  0.838564  0.810907  0.868281  0.999385
real onion    0.648812  0.786956  0.694294  0.908293  0.999556
fake onion    0.928640  0.962950  0.993063  0.934704  0.999955
real unknown  0.658177  0.793807  0.688640  0.937023  0.999922
fake unknown  0.213766  0.352198  0.235109  0.701920  0.997825
total         0.738728  0.836444  0.868825  0.838073  0.999206
total(-bg)    0.727049  0.829111  0.862996  0.830777  0.999358
2026-09-26 02:15:42,382 - INFO: Epoch accounting: {'epoch': 392, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11317393, 45190, 69993, 123190, 133374, 82846, 92662, 179385, 180846, 71774, 65710, 50295, 43880, 208222, 86472, 136493, 23269, 74855, 59302, 102546, 59608, 7454, 23513], 'crops_with_class': [202, 28, 31, 32, 34, 27, 29, 29, 39, 32, 27, 17, 16, 49, 25, 19, 19, 21, 24, 39, 27, 8, 11], 'targeted_crops_by_class': [0, 4, 3, 8, 4, 7, 3, 5, 6, 6, 4, 4, 5, 6, 4, 7, 4, 2, 4, 5, 3, 2, 3], 'sampled_scene_counts': [0, 0, 2, 1, 2, 2, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 2, 0, 0, 1, 1, 0, 1, 1, 2, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0, 2, 1, 3, 1, 1, 1, 3, 1, 1, 0, 2, 4, 1, 2, 2, 1, 1, 3, 1, 1, 2, 1, 2, 0, 1, 2, 0, 0, 0, 1, 0, 3, 0, 0, 0, 1, 1, 1, 0, 3, 1, 1, 0, 1, 1, 1, 2, 6, 0, 1, 1, 1, 0, 0, 0, 2, 3, 0, 2, 2, 1, 3, 0, 2, 1, 1, 1, 1, 2, 0, 1, 3, 2, 1, 0, 2, 0, 1, 1, 1, 2, 3], 'learning_rate': 1.1496659872588139e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005740659674635332, 'train_segmentation_loss': 0.27798253544929, 'val_foreground_miou_all22': 0.7270488456780868, 'val_psnr_ref1': 38.992764739990236, 'elapsed_seconds': 333.70002245903015, 'peak_cuda_allocated_gib': 7.5058135986328125}

Epoch 393/500 | Batch 10/202 | Rec 0.000566 | Seg 0.285864 | Elapsed 0.2m | ETA 4.0m
Epoch 393/500 | Batch 20/202 | Rec 0.000582 | Seg 0.305159 | Elapsed 0.4m | ETA 3.8m
Epoch 393/500 | Batch 30/202 | Rec 0.000574 | Seg 0.294521 | Elapsed 0.6m | ETA 3.6m
Epoch 393/500 | Batch 40/202 | Rec 0.000600 | Seg 0.304245 | Elapsed 0.8m | ETA 3.4m
Epoch 393/500 | Batch 50/202 | Rec 0.000591 | Seg 0.296293 | Elapsed 1.0m | ETA 3.2m
Epoch 393/500 | Batch 60/202 | Rec 0.000569 | Seg 0.284144 | Elapsed 1.3m | ETA 3.0m
Epoch 393/500 | Batch 70/202 | Rec 0.000568 | Seg 0.286705 | Elapsed 1.5m | ETA 2.7m
Epoch 393/500 | Batch 80/202 | Rec 0.000590 | Seg 0.290257 | Elapsed 1.7m | ETA 2.5m
Epoch 393/500 | Batch 90/202 | Rec 0.000597 | Seg 0.290482 | Elapsed 1.9m | ETA 2.3m
Epoch 393/500 | Batch 100/202 | Rec 0.000584 | Seg 0.285823 | Elapsed 2.1m | ETA 2.1m
Epoch 393/500 | Batch 110/202 | Rec 0.000595 | Seg 0.284221 | Elapsed 2.3m | ETA 1.9m
Epoch 393/500 | Batch 120/202 | Rec 0.000603 | Seg 0.284001 | Elapsed 2.5m | ETA 1.7m
Epoch 393/500 | Batch 130/202 | Rec 0.000604 | Seg 0.287981 | Elapsed 2.7m | ETA 1.5m
Epoch 393/500 | Batch 140/202 | Rec 0.000610 | Seg 0.287230 | Elapsed 2.9m | ETA 1.3m
Epoch 393/500 | Batch 150/202 | Rec 0.000612 | Seg 0.291266 | Elapsed 3.1m | ETA 1.1m
Epoch 393/500 | Batch 160/202 | Rec 0.000617 | Seg 0.293730 | Elapsed 3.4m | ETA 0.9m
Epoch 393/500 | Batch 170/202 | Rec 0.000612 | Seg 0.289204 | Elapsed 3.6m | ETA 0.7m
Epoch 393/500 | Batch 180/202 | Rec 0.000618 | Seg 0.290547 | Elapsed 3.8m | ETA 0.5m
Epoch 393/500 | Batch 190/202 | Rec 0.000616 | Seg 0.289667 | Elapsed 4.0m | ETA 0.3m
Epoch 393/500 | Batch 200/202 | Rec 0.000610 | Seg 0.287621 | Elapsed 4.2m | ETA 0.0m
Epoch 393/500 | Batch 202/202 | Rec 0.000611 | Seg 0.288705 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:19:55,897 - INFO: Rec loss: 0.0006109804065153463
2026-09-26 02:19:55,897 - INFO: Seg loss: 0.28870504825274546
2026-09-26 02:19:55,897 - INFO: λ_rec: 1
2026-09-26 02:19:55,897 - INFO: λ_seg: 0.0001
2026-09-26 02:21:15,114 - INFO: -------------------Epoch: 393------------------------
2026-09-26 02:21:15,118 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.920992  0.974831  0.000134
2026-09-26 02:21:15,126 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995819  0.997855  0.997521  0.998289  0.996010
real potato   0.845935  0.916488  0.964502  0.873119  0.999810
fake potato   0.901331  0.948055  0.975410  0.922287  0.999926
real apple    0.796006  0.886368  0.948196  0.832198  0.999264
fake apple    0.589481  0.741681  0.981501  0.596104  0.998433
real orange   0.929446  0.963383  0.997027  0.932029  0.999907
fake orange   0.943640  0.970953  0.958892  0.983424  0.999832
real grape    0.807315  0.893336  0.951367  0.842067  0.999580
fake grape    0.898064  0.946245  0.918569  0.975746  0.999590
real lemon    0.646716  0.785412  0.740570  0.836146  0.999463
fake lemon    0.849784  0.918743  0.997046  0.851929  0.999681
real avocado  0.952420  0.975580  0.988539  0.963054  0.999955
fake avocado  0.545582  0.705943  0.999766  0.545652  0.999456
real pepper   0.835174  0.910135  0.856176  0.971467  0.999299
fake pepper   0.720866  0.837745  0.948228  0.750400  0.999307
real plant    0.876692  0.934245  0.954456  0.914968  0.998713
fake plant    0.817511  0.899544  0.867260  0.934432  0.999834
real banana   0.703375  0.825811  0.876019  0.781135  0.999260
fake banana   0.677067  0.807392  0.751035  0.873009  0.999234
real onion    0.658671  0.794167  0.684339  0.946124  0.999557
fake onion    0.934360  0.966016  0.978898  0.953567  0.999958
real unknown  0.761159  0.864334  0.809325  0.927481  0.999953
fake unknown  0.209425  0.346287  0.224142  0.761318  0.997578
total         0.778080  0.862423  0.885599  0.868085  0.999287
total(-bg)    0.768183  0.856267  0.880512  0.862166  0.999436
2026-09-26 02:21:15,669 - INFO: Epoch accounting: {'epoch': 393, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11282139, 74151, 103026, 94072, 110873, 75456, 75962, 123237, 167858, 56232, 52515, 27543, 30244, 237091, 123488, 158499, 19152, 132201, 79756, 103029, 59401, 9321, 43026], 'crops_with_class': [202, 42, 42, 26, 28, 23, 25, 26, 26, 25, 23, 11, 13, 57, 38, 19, 20, 35, 33, 48, 32, 10, 20], 'targeted_crops_by_class': [0, 4, 11, 5, 2, 1, 8, 4, 1, 4, 0, 2, 7, 5, 8, 5, 3, 9, 2, 5, 3, 4, 3], 'sampled_scene_counts': [2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 2, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 3, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 2, 0, 0, 1, 2, 2, 0, 1, 2, 0, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 2, 0, 1, 0, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 0, 2, 1, 3, 2, 0, 1, 3, 1, 2, 1, 0, 2, 1, 1, 1, 0, 2, 1, 1, 1, 1, 2, 4, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 0, 2, 2, 4, 2, 4, 3, 2, 2, 0, 0, 2, 1, 2, 6, 3, 2, 2, 1, 3, 1, 1, 0, 2, 2], 'learning_rate': 1.1299192709344694e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006109804065153463, 'train_segmentation_loss': 0.28870504825274546, 'val_foreground_miou_all22': 0.7681827638675344, 'val_psnr_ref1': 38.920991821289064, 'elapsed_seconds': 333.2792797088623, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 394/500 | Batch 10/202 | Rec 0.000705 | Seg 0.352397 | Elapsed 0.2m | ETA 3.9m
Epoch 394/500 | Batch 20/202 | Rec 0.000644 | Seg 0.337081 | Elapsed 0.4m | ETA 3.7m
Epoch 394/500 | Batch 30/202 | Rec 0.000587 | Seg 0.293605 | Elapsed 0.6m | ETA 3.6m
Epoch 394/500 | Batch 40/202 | Rec 0.000567 | Seg 0.294291 | Elapsed 0.8m | ETA 3.3m
Epoch 394/500 | Batch 50/202 | Rec 0.000582 | Seg 0.304999 | Elapsed 1.0m | ETA 3.1m
Epoch 394/500 | Batch 60/202 | Rec 0.000596 | Seg 0.313275 | Elapsed 1.2m | ETA 2.9m
Epoch 394/500 | Batch 70/202 | Rec 0.000588 | Seg 0.303973 | Elapsed 1.4m | ETA 2.7m
Epoch 394/500 | Batch 80/202 | Rec 0.000595 | Seg 0.304073 | Elapsed 1.6m | ETA 2.5m
Epoch 394/500 | Batch 90/202 | Rec 0.000599 | Seg 0.302325 | Elapsed 1.8m | ETA 2.3m
Epoch 394/500 | Batch 100/202 | Rec 0.000614 | Seg 0.303337 | Elapsed 2.0m | ETA 2.1m
Epoch 394/500 | Batch 110/202 | Rec 0.000621 | Seg 0.305240 | Elapsed 2.3m | ETA 1.9m
Epoch 394/500 | Batch 120/202 | Rec 0.000620 | Seg 0.303639 | Elapsed 2.5m | ETA 1.7m
Epoch 394/500 | Batch 130/202 | Rec 0.000614 | Seg 0.301131 | Elapsed 2.7m | ETA 1.5m
Epoch 394/500 | Batch 140/202 | Rec 0.000602 | Seg 0.292419 | Elapsed 2.9m | ETA 1.3m
Epoch 394/500 | Batch 150/202 | Rec 0.000609 | Seg 0.290696 | Elapsed 3.1m | ETA 1.1m
Epoch 394/500 | Batch 160/202 | Rec 0.000603 | Seg 0.286457 | Elapsed 3.3m | ETA 0.9m
Epoch 394/500 | Batch 170/202 | Rec 0.000595 | Seg 0.285527 | Elapsed 3.5m | ETA 0.7m
Epoch 394/500 | Batch 180/202 | Rec 0.000597 | Seg 0.287326 | Elapsed 3.7m | ETA 0.5m
Epoch 394/500 | Batch 190/202 | Rec 0.000596 | Seg 0.288994 | Elapsed 3.9m | ETA 0.2m
Epoch 394/500 | Batch 200/202 | Rec 0.000597 | Seg 0.289428 | Elapsed 4.1m | ETA 0.0m
Epoch 394/500 | Batch 202/202 | Rec 0.000596 | Seg 0.290286 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:25:25,610 - INFO: Rec loss: 0.0005961689594637437
2026-09-26 02:25:25,610 - INFO: Seg loss: 0.29028613596121866
2026-09-26 02:25:25,610 - INFO: λ_rec: 1
2026-09-26 02:25:25,610 - INFO: λ_seg: 0.0001
2026-09-26 02:26:46,934 - INFO: -------------------Epoch: 394------------------------
2026-09-26 02:26:46,938 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.119715  0.975155  0.000128
2026-09-26 02:26:46,947 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995800  0.997846  0.997050  0.998743  0.995990
real potato   0.419918  0.591427  1.000000  0.419918  0.999306
fake potato   0.663720  0.797827  0.972590  0.676372  0.999750
real apple    0.700359  0.823728  0.795274  0.854401  0.998739
fake apple    0.617700  0.763629  0.961128  0.633527  0.998520
real orange   0.907914  0.951685  0.997588  0.909912  0.999878
fake orange   0.933724  0.965676  0.954073  0.977668  0.999801
real grape    0.812702  0.896625  0.976908  0.828619  0.999601
fake grape    0.878667  0.935365  0.904313  0.968733  0.999505
real lemon    0.386671  0.557651  0.427405  0.802259  0.998504
fake lemon    0.861352  0.925463  0.984943  0.872845  0.999703
real avocado  0.855411  0.922022  0.885546  0.961741  0.999849
fake avocado  0.691523  0.817585  0.999447  0.691788  0.999631
real pepper   0.882889  0.937753  0.926446  0.949441  0.999539
fake pepper   0.803397  0.890932  0.953968  0.835798  0.999512
real plant    0.874169  0.932811  0.958139  0.908881  0.998691
fake plant    0.808172  0.893860  0.892884  0.894939  0.999831
real banana   0.332657  0.499199  0.900797  0.345308  0.998443
fake banana   0.661237  0.796028  0.769201  0.824900  0.999223
real onion    0.656362  0.792485  0.729312  0.867759  0.999590
fake onion    0.909349  0.952473  0.977111  0.929141  0.999942
real unknown  0.912796  0.954360  0.992783  0.918893  0.999986
fake unknown  0.219510  0.359960  0.238104  0.737595  0.997790
total         0.729826  0.824191  0.878044  0.817791  0.999188
total(-bg)    0.717736  0.816297  0.872635  0.809565  0.999333
2026-09-26 02:26:47,660 - INFO: Epoch accounting: {'epoch': 394, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11252269, 58018, 71549, 153650, 134014, 101886, 82851, 143248, 163759, 49710, 71927, 41517, 34561, 217942, 92057, 181762, 25275, 97587, 67194, 82476, 65033, 10702, 39285], 'crops_with_class': [202, 32, 33, 35, 32, 32, 29, 26, 36, 27, 27, 18, 17, 54, 27, 25, 21, 26, 28, 36, 28, 10, 18], 'targeted_crops_by_class': [0, 8, 7, 5, 7, 4, 4, 5, 4, 10, 4, 5, 5, 8, 4, 4, 7, 5, 2, 4, 8, 3, 4], 'sampled_scene_counts': [2, 1, 3, 0, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 4, 0, 0, 0, 0, 0, 1, 1, 0, 0, 3, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 2, 0, 1, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 0, 1, 1, 3, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 2, 2, 1, 3, 1, 1, 0, 2, 2, 0, 0, 2, 1, 2, 2, 1, 2, 1, 1, 1, 3, 0, 2, 2, 2, 1, 1, 1, 4, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 3, 2, 2, 5, 0, 1, 1, 1, 2, 2, 2, 1, 0, 1, 1, 3, 0, 3, 5, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 3, 1, 2, 2, 1, 4, 0, 0, 1, 2, 0, 2, 3, 1, 4], 'learning_rate': 1.110325832249265e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005961689594637437, 'train_segmentation_loss': 0.29028613596121866, 'val_foreground_miou_all22': 0.7177363277982528, 'val_psnr_ref1': 39.11971542358398, 'elapsed_seconds': 331.98359847068787, 'peak_cuda_allocated_gib': 7.508579254150391}

Epoch 395/500 | Batch 10/202 | Rec 0.000568 | Seg 0.327826 | Elapsed 0.2m | ETA 3.9m
Epoch 395/500 | Batch 20/202 | Rec 0.000560 | Seg 0.287567 | Elapsed 0.4m | ETA 3.8m
Epoch 395/500 | Batch 30/202 | Rec 0.000579 | Seg 0.289380 | Elapsed 0.6m | ETA 3.5m
Epoch 395/500 | Batch 40/202 | Rec 0.000578 | Seg 0.294122 | Elapsed 0.8m | ETA 3.4m
Epoch 395/500 | Batch 50/202 | Rec 0.000585 | Seg 0.290250 | Elapsed 1.0m | ETA 3.2m
Epoch 395/500 | Batch 60/202 | Rec 0.000581 | Seg 0.290906 | Elapsed 1.2m | ETA 2.9m
Epoch 395/500 | Batch 70/202 | Rec 0.000577 | Seg 0.289001 | Elapsed 1.5m | ETA 2.7m
Epoch 395/500 | Batch 80/202 | Rec 0.000576 | Seg 0.286294 | Elapsed 1.7m | ETA 2.6m
Epoch 395/500 | Batch 90/202 | Rec 0.000600 | Seg 0.289986 | Elapsed 1.9m | ETA 2.3m
Epoch 395/500 | Batch 100/202 | Rec 0.000624 | Seg 0.284423 | Elapsed 2.1m | ETA 2.1m
Epoch 395/500 | Batch 110/202 | Rec 0.000631 | Seg 0.290810 | Elapsed 2.3m | ETA 1.9m
Epoch 395/500 | Batch 120/202 | Rec 0.000623 | Seg 0.290636 | Elapsed 2.5m | ETA 1.7m
Epoch 395/500 | Batch 130/202 | Rec 0.000631 | Seg 0.297352 | Elapsed 2.7m | ETA 1.5m
Epoch 395/500 | Batch 140/202 | Rec 0.000625 | Seg 0.299877 | Elapsed 2.9m | ETA 1.3m
Epoch 395/500 | Batch 150/202 | Rec 0.000624 | Seg 0.302167 | Elapsed 3.1m | ETA 1.1m
Epoch 395/500 | Batch 160/202 | Rec 0.000618 | Seg 0.299362 | Elapsed 3.3m | ETA 0.9m
Epoch 395/500 | Batch 170/202 | Rec 0.000612 | Seg 0.295725 | Elapsed 3.5m | ETA 0.7m
Epoch 395/500 | Batch 180/202 | Rec 0.000604 | Seg 0.291751 | Elapsed 3.7m | ETA 0.5m
Epoch 395/500 | Batch 190/202 | Rec 0.000599 | Seg 0.288771 | Elapsed 3.9m | ETA 0.2m
Epoch 395/500 | Batch 200/202 | Rec 0.000602 | Seg 0.289986 | Elapsed 4.1m | ETA 0.0m
Epoch 395/500 | Batch 202/202 | Rec 0.000604 | Seg 0.292397 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:30:58,853 - INFO: Rec loss: 0.0006040665607768028
2026-09-26 02:30:58,854 - INFO: Seg loss: 0.2923970152946687
2026-09-26 02:30:58,854 - INFO: λ_rec: 1
2026-09-26 02:30:58,854 - INFO: λ_seg: 0.0001
2026-09-26 02:32:18,165 - INFO: -------------------Epoch: 395------------------------
2026-09-26 02:32:18,169 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.880713  0.974556  0.000135
2026-09-26 02:32:18,177 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995768  0.997829  0.997248  0.998512  0.995960
real potato   0.913203  0.954583  0.990001  0.921704  0.999895
fake potato   0.869824  0.930331  0.976075  0.888772  0.999903
real apple    0.796438  0.886636  0.969454  0.816939  0.999280
fake apple    0.583663  0.737058  0.982038  0.589961  0.998411
real orange   0.939439  0.968724  0.995964  0.943029  0.999920
fake orange   0.947968  0.973239  0.965932  0.980759  0.999846
real grape    0.777280  0.874635  0.966820  0.798582  0.999522
fake grape    0.894353  0.944181  0.917864  0.972157  0.999575
real lemon    0.566522  0.723237  0.622495  0.863023  0.999224
fake lemon    0.862223  0.925965  0.995356  0.865705  0.999707
real avocado  0.941683  0.969916  0.988743  0.951888  0.999945
fake avocado  0.710187  0.830489  0.999820  0.710278  0.999653
real pepper   0.935308  0.966523  0.965146  0.968004  0.999755
fake pepper   0.901539  0.948170  0.955180  0.941361  0.999755
real plant    0.870549  0.930745  0.950025  0.912329  0.998643
fake plant    0.826969  0.905241  0.881840  0.930023  0.999845
real banana   0.583265  0.736739  0.885205  0.630993  0.998987
fake banana   0.660520  0.795508  0.743335  0.855674  0.999191
real onion    0.645902  0.784812  0.678058  0.931599  0.999539
fake onion    0.893441  0.943672  0.977208  0.912455  0.999931
real unknown  0.843996  0.915349  0.911932  0.918893  0.999973
fake unknown  0.208226  0.344644  0.227058  0.715139  0.997709
total         0.789925  0.869053  0.893165  0.870338  0.999312
total(-bg)    0.780568  0.863200  0.888434  0.864512  0.999464
2026-09-26 02:32:18,714 - INFO: Epoch accounting: {'epoch': 395, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11231841, 57523, 60989, 110625, 132518, 103064, 79869, 199039, 185035, 72511, 72563, 35537, 32886, 195690, 121369, 155646, 24378, 102601, 80718, 77975, 51528, 9107, 45260], 'crops_with_class': [202, 31, 28, 27, 33, 31, 29, 39, 38, 34, 28, 13, 12, 52, 33, 24, 23, 33, 30, 38, 26, 12, 19], 'targeted_crops_by_class': [0, 5, 3, 5, 1, 3, 8, 5, 9, 4, 5, 5, 3, 3, 6, 2, 6, 5, 7, 6, 6, 4, 8], 'sampled_scene_counts': [0, 1, 0, 1, 1, 1, 0, 0, 3, 1, 0, 2, 1, 0, 1, 0, 1, 2, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 2, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 1, 0, 2, 1, 2, 1, 0, 0, 1, 3, 0, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 2, 0, 4, 2, 1, 0, 1, 1, 1, 1, 0, 1, 2, 3, 2, 0, 3, 4, 1, 2, 1, 2, 0, 0, 1, 2, 1, 2, 0, 2, 2, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 5, 3, 0, 3, 1, 1, 1, 0, 1, 3, 1, 1, 4, 1, 3, 1, 3, 2, 1, 0, 1, 1, 3, 1, 4, 2, 2, 1, 2, 2, 0, 4, 0, 1, 0, 0, 2, 1, 1, 0, 1, 0], 'learning_rate': 1.0908864447186131e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006040665607768028, 'train_segmentation_loss': 0.2923970152946687, 'val_foreground_miou_all22': 0.7805680915413041, 'val_psnr_ref1': 38.88071273803711, 'elapsed_seconds': 331.04667687416077, 'peak_cuda_allocated_gib': 7.510265350341797}

Epoch 396/500 | Batch 10/202 | Rec 0.000508 | Seg 0.231121 | Elapsed 0.2m | ETA 4.1m
Epoch 396/500 | Batch 20/202 | Rec 0.000530 | Seg 0.268205 | Elapsed 0.4m | ETA 3.8m
Epoch 396/500 | Batch 30/202 | Rec 0.000519 | Seg 0.270949 | Elapsed 0.6m | ETA 3.6m
Epoch 396/500 | Batch 40/202 | Rec 0.000510 | Seg 0.272685 | Elapsed 0.8m | ETA 3.4m
Epoch 396/500 | Batch 50/202 | Rec 0.000535 | Seg 0.285117 | Elapsed 1.0m | ETA 3.2m
Epoch 396/500 | Batch 60/202 | Rec 0.000550 | Seg 0.292791 | Elapsed 1.3m | ETA 3.0m
Epoch 396/500 | Batch 70/202 | Rec 0.000558 | Seg 0.298257 | Elapsed 1.5m | ETA 2.7m
Epoch 396/500 | Batch 80/202 | Rec 0.000559 | Seg 0.297824 | Elapsed 1.7m | ETA 2.5m
Epoch 396/500 | Batch 90/202 | Rec 0.000560 | Seg 0.299194 | Elapsed 1.9m | ETA 2.3m
Epoch 396/500 | Batch 100/202 | Rec 0.000559 | Seg 0.296196 | Elapsed 2.1m | ETA 2.1m
Epoch 396/500 | Batch 110/202 | Rec 0.000569 | Seg 0.295252 | Elapsed 2.3m | ETA 1.9m
Epoch 396/500 | Batch 120/202 | Rec 0.000574 | Seg 0.297110 | Elapsed 2.5m | ETA 1.7m
Epoch 396/500 | Batch 130/202 | Rec 0.000576 | Seg 0.297287 | Elapsed 2.7m | ETA 1.5m
Epoch 396/500 | Batch 140/202 | Rec 0.000579 | Seg 0.297522 | Elapsed 2.9m | ETA 1.3m
Epoch 396/500 | Batch 150/202 | Rec 0.000575 | Seg 0.292223 | Elapsed 3.1m | ETA 1.1m
Epoch 396/500 | Batch 160/202 | Rec 0.000580 | Seg 0.289097 | Elapsed 3.3m | ETA 0.9m
Epoch 396/500 | Batch 170/202 | Rec 0.000580 | Seg 0.292316 | Elapsed 3.6m | ETA 0.7m
Epoch 396/500 | Batch 180/202 | Rec 0.000585 | Seg 0.293558 | Elapsed 3.8m | ETA 0.5m
Epoch 396/500 | Batch 190/202 | Rec 0.000585 | Seg 0.296349 | Elapsed 4.0m | ETA 0.3m
Epoch 396/500 | Batch 200/202 | Rec 0.000586 | Seg 0.294963 | Elapsed 4.2m | ETA 0.0m
Epoch 396/500 | Batch 202/202 | Rec 0.000585 | Seg 0.295447 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:36:31,313 - INFO: Rec loss: 0.0005847582474551486
2026-09-26 02:36:31,313 - INFO: Seg loss: 0.2954470839462068
2026-09-26 02:36:31,313 - INFO: λ_rec: 1
2026-09-26 02:36:31,313 - INFO: λ_seg: 0.0001
2026-09-26 02:37:52,906 - INFO: -------------------Epoch: 396------------------------
2026-09-26 02:37:52,910 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.944153  0.974783  0.000133
2026-09-26 02:37:52,917 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995704  0.997797  0.997471  0.998224  0.995900
real potato   0.415394  0.586925  0.994517  0.416348  0.999299
fake potato   0.697982  0.822083  0.962619  0.717428  0.999774
real apple    0.661976  0.796563  0.782345  0.811411  0.998571
fake apple    0.612836  0.759900  0.962399  0.627869  0.998502
real orange   0.951293  0.974988  0.996614  0.954377  0.999936
fake orange   0.949707  0.974155  0.971135  0.977295  0.999852
real grape    0.791664  0.883669  0.971278  0.810641  0.999555
fake grape    0.896407  0.945324  0.920546  0.971579  0.999585
real lemon    0.448751  0.619454  0.484642  0.858348  0.998761
fake lemon    0.860959  0.925236  0.995103  0.864623  0.999705
real avocado  0.896636  0.945451  0.928730  0.962890  0.999897
fake avocado  0.783146  0.878338  0.999675  0.783346  0.999740
real pepper   0.870279  0.930591  0.905329  0.957409  0.999478
fake pepper   0.856799  0.922828  0.959892  0.888611  0.999646
real plant    0.872647  0.931943  0.947438  0.917043  0.998661
fake plant    0.791242  0.883407  0.823637  0.952646  0.999800
real banana   0.439789  0.610862  0.854406  0.475418  0.998639
fake banana   0.665687  0.799245  0.743383  0.864300  0.999202
real onion    0.633188  0.775352  0.707909  0.857119  0.999551
fake onion    0.895000  0.944541  0.983002  0.909069  0.999933
real unknown  0.850694  0.919275  0.904059  0.935114  0.999974
fake unknown  0.226978  0.369942  0.243268  0.772184  0.997784
total         0.741946  0.834690  0.871278  0.838404  0.999206
total(-bg)    0.730412  0.827276  0.865542  0.831139  0.999357
2026-09-26 02:37:53,492 - INFO: Epoch accounting: {'epoch': 396, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11163761, 41850, 41465, 168794, 192582, 76590, 77329, 118960, 269360, 84911, 93746, 49500, 53530, 219672, 126822, 81455, 17883, 75048, 68968, 82847, 54886, 13422, 64891], 'crops_with_class': [202, 27, 18, 47, 48, 28, 30, 24, 42, 35, 39, 17, 19, 59, 32, 14, 17, 20, 28, 33, 24, 16, 27], 'targeted_crops_by_class': [0, 0, 2, 8, 5, 6, 8, 3, 5, 3, 7, 6, 7, 3, 3, 1, 3, 5, 3, 6, 4, 8, 6], 'sampled_scene_counts': [0, 1, 2, 2, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 3, 1, 0, 0, 1, 3, 2, 2, 1, 5, 2, 4, 1, 2, 3, 2, 2, 2, 3, 0, 2, 2, 1, 0, 2, 2, 1, 0, 3, 1, 1, 3, 4, 2, 1, 1, 3, 0, 0, 2, 0, 1, 0, 0, 2, 5, 3, 3, 2, 2, 1, 1, 1, 0, 0, 0, 2, 0, 0, 1, 3, 1, 2, 1, 0, 0, 4, 1, 2, 1, 1, 3, 1, 1, 2, 2, 2, 1, 0, 0, 1, 1, 0, 3, 1, 2, 1, 1], 'learning_rate': 1.0716018757762425e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005847582474551486, 'train_segmentation_loss': 0.2954470839462068, 'val_foreground_miou_all22': 0.7304115812681361, 'val_psnr_ref1': 38.94415267944336, 'elapsed_seconds': 334.76986169815063, 'peak_cuda_allocated_gib': 7.508853912353516}

Epoch 397/500 | Batch 10/202 | Rec 0.000638 | Seg 0.332564 | Elapsed 0.2m | ETA 4.0m
Epoch 397/500 | Batch 20/202 | Rec 0.000684 | Seg 0.319431 | Elapsed 0.4m | ETA 3.7m
Epoch 397/500 | Batch 30/202 | Rec 0.000660 | Seg 0.306455 | Elapsed 0.6m | ETA 3.6m
Epoch 397/500 | Batch 40/202 | Rec 0.000625 | Seg 0.301807 | Elapsed 0.8m | ETA 3.4m
Epoch 397/500 | Batch 50/202 | Rec 0.000603 | Seg 0.292120 | Elapsed 1.0m | ETA 3.2m
Epoch 397/500 | Batch 60/202 | Rec 0.000617 | Seg 0.287278 | Elapsed 1.3m | ETA 3.0m
Epoch 397/500 | Batch 70/202 | Rec 0.000599 | Seg 0.281938 | Elapsed 1.5m | ETA 2.8m
Epoch 397/500 | Batch 80/202 | Rec 0.000601 | Seg 0.276903 | Elapsed 1.7m | ETA 2.6m
Epoch 397/500 | Batch 90/202 | Rec 0.000604 | Seg 0.280277 | Elapsed 1.9m | ETA 2.3m
Epoch 397/500 | Batch 100/202 | Rec 0.000608 | Seg 0.286019 | Elapsed 2.1m | ETA 2.1m
Epoch 397/500 | Batch 110/202 | Rec 0.000602 | Seg 0.286325 | Elapsed 2.3m | ETA 1.9m
Epoch 397/500 | Batch 120/202 | Rec 0.000598 | Seg 0.285734 | Elapsed 2.5m | ETA 1.7m
Epoch 397/500 | Batch 130/202 | Rec 0.000590 | Seg 0.281505 | Elapsed 2.7m | ETA 1.5m
Epoch 397/500 | Batch 140/202 | Rec 0.000586 | Seg 0.279838 | Elapsed 2.9m | ETA 1.3m
Epoch 397/500 | Batch 150/202 | Rec 0.000590 | Seg 0.278486 | Elapsed 3.1m | ETA 1.1m
Epoch 397/500 | Batch 160/202 | Rec 0.000590 | Seg 0.277389 | Elapsed 3.3m | ETA 0.9m
Epoch 397/500 | Batch 170/202 | Rec 0.000579 | Seg 0.273869 | Elapsed 3.6m | ETA 0.7m
Epoch 397/500 | Batch 180/202 | Rec 0.000576 | Seg 0.272202 | Elapsed 3.8m | ETA 0.5m
Epoch 397/500 | Batch 190/202 | Rec 0.000571 | Seg 0.271098 | Elapsed 4.0m | ETA 0.3m
Epoch 397/500 | Batch 200/202 | Rec 0.000574 | Seg 0.271876 | Elapsed 4.2m | ETA 0.0m
Epoch 397/500 | Batch 202/202 | Rec 0.000574 | Seg 0.271504 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:42:06,389 - INFO: Rec loss: 0.0005737298267223817
2026-09-26 02:42:06,389 - INFO: Seg loss: 0.2715037950489781
2026-09-26 02:42:06,389 - INFO: λ_rec: 1
2026-09-26 02:42:06,389 - INFO: λ_seg: 0.0001
2026-09-26 02:43:28,195 - INFO: -------------------Epoch: 397------------------------
2026-09-26 02:43:28,200 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.770663  0.974399  0.000139
2026-09-26 02:43:28,206 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995654  0.997772  0.997285  0.998360  0.995851
real potato   0.917343  0.956840  0.962820  0.951033  0.999897
fake potato   0.925493  0.961255  0.978728  0.944491  0.999945
real apple    0.768523  0.869063  0.965167  0.790447  0.999179
fake apple    0.553741  0.712738  0.982533  0.559247  0.998298
real orange   0.952777  0.975767  0.996980  0.955535  0.999938
fake orange   0.953295  0.976039  0.967779  0.984543  0.999862
real grape    0.742873  0.852420  0.949816  0.773222  0.999441
fake grape    0.908055  0.951762  0.934321  0.969971  0.999637
real lemon    0.775016  0.873200  0.822100  0.931187  0.999682
fake lemon    0.845379  0.916162  0.996609  0.847818  0.999672
real avocado  0.927658  0.962421  0.960582  0.964368  0.999930
fake avocado  0.553105  0.712211  0.999770  0.553175  0.999465
real pepper   0.874555  0.933030  0.895486  0.973970  0.999489
fake pepper   0.796762  0.886837  0.953872  0.828692  0.999496
real plant    0.860709  0.925091  0.943093  0.907859  0.998530
fake plant    0.840237  0.913133  0.928472  0.898390  0.999864
real banana   0.731497  0.844880  0.881325  0.811422  0.999331
fake banana   0.692522  0.818282  0.775271  0.866457  0.999292
real onion    0.623964  0.768397  0.643598  0.953386  0.999481
fake onion    0.898426  0.946446  0.984583  0.911245  0.999935
real unknown  0.668501  0.801270  0.705370  0.927481  0.999926
fake unknown  0.202062  0.336157  0.215859  0.759689  0.997472
total         0.782963  0.864834  0.888757  0.872260  0.999288
total(-bg)    0.773295  0.858791  0.883824  0.866528  0.999444
2026-09-26 02:43:28,785 - INFO: Epoch accounting: {'epoch': 397, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11283264, 52713, 44475, 153615, 132712, 73906, 53734, 143117, 238529, 97746, 85438, 39080, 39542, 281637, 124730, 68394, 16407, 79255, 63695, 68582, 35015, 8764, 53922], 'crops_with_class': [202, 28, 26, 42, 33, 28, 22, 31, 44, 42, 36, 12, 13, 65, 28, 12, 14, 23, 26, 26, 18, 10, 23], 'targeted_crops_by_class': [0, 3, 1, 8, 4, 3, 3, 5, 7, 11, 3, 4, 1, 9, 6, 3, 4, 4, 3, 4, 3, 4, 7], 'sampled_scene_counts': [1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 2, 1, 1, 1, 1, 1, 1, 0, 2, 4, 2, 1, 0, 1, 0, 2, 1, 0, 0, 2, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 2, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 2, 1, 0, 0, 2, 1, 0, 1, 1, 4, 1, 1, 1, 2, 5, 0, 2, 2, 5, 1, 1, 1, 2, 1, 1, 0, 1, 2, 1, 1, 1, 1, 2, 0, 1, 3, 0, 1, 1, 2, 5, 1, 4, 2, 2, 0, 1, 1, 1, 2, 3, 2, 2, 1, 0, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 0, 0, 4, 1, 1, 1, 0, 0, 0, 0, 1, 0, 2, 0, 1, 2], 'learning_rate': 1.0524728867439195e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005737298267223817, 'train_segmentation_loss': 0.2715037950489781, 'val_foreground_miou_all22': 0.773295115066854, 'val_psnr_ref1': 38.770663299560546, 'elapsed_seconds': 335.2848994731903, 'peak_cuda_allocated_gib': 7.511508941650391}

Epoch 398/500 | Batch 10/202 | Rec 0.000677 | Seg 0.301923 | Elapsed 0.2m | ETA 4.0m
Epoch 398/500 | Batch 20/202 | Rec 0.000748 | Seg 0.321026 | Elapsed 0.4m | ETA 3.7m
Epoch 398/500 | Batch 30/202 | Rec 0.000700 | Seg 0.328921 | Elapsed 0.6m | ETA 3.5m
Epoch 398/500 | Batch 40/202 | Rec 0.000740 | Seg 0.317553 | Elapsed 0.8m | ETA 3.3m
Epoch 398/500 | Batch 50/202 | Rec 0.000684 | Seg 0.298826 | Elapsed 1.0m | ETA 3.1m
Epoch 398/500 | Batch 60/202 | Rec 0.000648 | Seg 0.290129 | Elapsed 1.2m | ETA 2.9m
Epoch 398/500 | Batch 70/202 | Rec 0.000624 | Seg 0.280906 | Elapsed 1.4m | ETA 2.7m
Epoch 398/500 | Batch 80/202 | Rec 0.000643 | Seg 0.290051 | Elapsed 1.7m | ETA 2.5m
Epoch 398/500 | Batch 90/202 | Rec 0.000635 | Seg 0.289134 | Elapsed 1.9m | ETA 2.3m
Epoch 398/500 | Batch 100/202 | Rec 0.000626 | Seg 0.290663 | Elapsed 2.1m | ETA 2.1m
Epoch 398/500 | Batch 110/202 | Rec 0.000619 | Seg 0.288247 | Elapsed 2.3m | ETA 1.9m
Epoch 398/500 | Batch 120/202 | Rec 0.000617 | Seg 0.287322 | Elapsed 2.5m | ETA 1.7m
Epoch 398/500 | Batch 130/202 | Rec 0.000606 | Seg 0.282201 | Elapsed 2.7m | ETA 1.5m
Epoch 398/500 | Batch 140/202 | Rec 0.000613 | Seg 0.289444 | Elapsed 2.9m | ETA 1.3m
Epoch 398/500 | Batch 150/202 | Rec 0.000607 | Seg 0.289816 | Elapsed 3.1m | ETA 1.1m
Epoch 398/500 | Batch 160/202 | Rec 0.000603 | Seg 0.289623 | Elapsed 3.3m | ETA 0.9m
Epoch 398/500 | Batch 170/202 | Rec 0.000596 | Seg 0.287038 | Elapsed 3.5m | ETA 0.7m
Epoch 398/500 | Batch 180/202 | Rec 0.000597 | Seg 0.284931 | Elapsed 3.7m | ETA 0.5m
Epoch 398/500 | Batch 190/202 | Rec 0.000590 | Seg 0.280403 | Elapsed 3.9m | ETA 0.2m
Epoch 398/500 | Batch 200/202 | Rec 0.000584 | Seg 0.280072 | Elapsed 4.1m | ETA 0.0m
Epoch 398/500 | Batch 202/202 | Rec 0.000587 | Seg 0.281194 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:47:40,080 - INFO: Rec loss: 0.0005872207170751148
2026-09-26 02:47:40,080 - INFO: Seg loss: 0.28119397727717266
2026-09-26 02:47:40,081 - INFO: λ_rec: 1
2026-09-26 02:47:40,081 - INFO: λ_seg: 0.0001
2026-09-26 02:49:00,038 - INFO: -------------------Epoch: 398------------------------
2026-09-26 02:49:00,042 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.166095  0.974956  0.000127
2026-09-26 02:49:00,049 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995631  0.997761  0.996916  0.998707  0.995828
real potato   0.153915  0.266747  1.000000  0.153915  0.998988
fake potato   0.640902  0.781111  0.995781  0.642648  0.999738
real apple    0.636049  0.777493  0.708273  0.861831  0.998299
fake apple    0.637498  0.778576  0.955834  0.656846  0.998590
real orange   0.927846  0.962523  0.996775  0.930639  0.999905
fake orange   0.936364  0.967086  0.964930  0.969353  0.999811
real grape    0.865314  0.927745  0.982357  0.878974  0.999714
fake grape    0.876729  0.934266  0.912966  0.956689  0.999502
real lemon    0.358558  0.527810  0.369157  0.925863  0.998053
fake lemon    0.849880  0.918799  0.979036  0.865633  0.999677
real avocado  0.750836  0.857639  0.776094  0.958456  0.999704
fake avocado  0.760326  0.863798  0.999665  0.760520  0.999713
real pepper   0.802153  0.890166  0.870416  0.910938  0.999178
fake pepper   0.711314  0.831259  0.970842  0.726842  0.999297
real plant    0.878854  0.935471  0.956502  0.915441  0.998738
fake plant    0.794052  0.885155  0.884866  0.885544  0.999817
real banana   0.079464  0.147213  0.856318  0.080538  0.997904
fake banana   0.682275  0.811084  0.828975  0.794044  0.999320
real onion    0.589951  0.742050  0.802593  0.690086  0.999567
fake onion    0.811898  0.896136  0.994982  0.815236  0.999881
real unknown  0.907578  0.951500  0.966535  0.937023  0.999985
fake unknown  0.231152  0.375468  0.246116  0.791742  0.997781
total         0.690371  0.783776  0.870258  0.787283  0.999086
total(-bg)    0.676496  0.774050  0.864501  0.777673  0.999235
2026-09-26 02:49:00,817 - INFO: Epoch accounting: {'epoch': 398, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11258028, 52003, 71103, 106599, 148359, 78870, 60312, 174631, 155758, 80633, 59873, 24017, 29595, 273997, 155726, 157205, 26182, 72694, 86353, 48206, 46898, 12224, 59006], 'crops_with_class': [202, 30, 30, 29, 40, 23, 21, 31, 41, 32, 25, 9, 15, 65, 39, 24, 24, 22, 35, 28, 20, 13, 27], 'targeted_crops_by_class': [0, 4, 5, 6, 6, 3, 5, 7, 2, 10, 5, 3, 2, 4, 6, 4, 5, 3, 9, 4, 5, 5, 4], 'sampled_scene_counts': [1, 0, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1, 0, 2, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 1, 2, 2, 3, 3, 0, 0, 1, 1, 3, 2, 1, 2, 1, 1, 3, 3, 1, 4, 2, 1, 0, 1, 4, 1, 3, 1, 1, 6, 2, 2, 1, 3, 0, 2, 1, 0, 1, 1, 1, 0, 1, 1, 3, 2, 1, 0, 0, 3, 1, 2, 3, 2, 2, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 0, 3, 0, 1, 0], 'learning_rate': 1.0335002328013762e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005872207170751148, 'train_segmentation_loss': 0.28119397727717266, 'val_foreground_miou_all22': 0.6764957873477285, 'val_psnr_ref1': 39.16609451293945, 'elapsed_seconds': 332.0243864059448, 'peak_cuda_allocated_gib': 7.511264801025391}

Epoch 399/500 | Batch 10/202 | Rec 0.000600 | Seg 0.264462 | Elapsed 0.2m | ETA 3.8m
Epoch 399/500 | Batch 20/202 | Rec 0.000569 | Seg 0.257474 | Elapsed 0.4m | ETA 3.7m
Epoch 399/500 | Batch 30/202 | Rec 0.000583 | Seg 0.267706 | Elapsed 0.6m | ETA 3.6m
Epoch 399/500 | Batch 40/202 | Rec 0.000586 | Seg 0.287394 | Elapsed 0.8m | ETA 3.3m
Epoch 399/500 | Batch 50/202 | Rec 0.000568 | Seg 0.280176 | Elapsed 1.0m | ETA 3.1m
Epoch 399/500 | Batch 60/202 | Rec 0.000550 | Seg 0.266297 | Elapsed 1.2m | ETA 3.0m
Epoch 399/500 | Batch 70/202 | Rec 0.000545 | Seg 0.269077 | Elapsed 1.5m | ETA 2.7m
Epoch 399/500 | Batch 80/202 | Rec 0.000575 | Seg 0.270866 | Elapsed 1.7m | ETA 2.5m
Epoch 399/500 | Batch 90/202 | Rec 0.000572 | Seg 0.280445 | Elapsed 1.9m | ETA 2.3m
Epoch 399/500 | Batch 100/202 | Rec 0.000565 | Seg 0.280078 | Elapsed 2.1m | ETA 2.1m
Epoch 399/500 | Batch 110/202 | Rec 0.000556 | Seg 0.274269 | Elapsed 2.3m | ETA 1.9m
Epoch 399/500 | Batch 120/202 | Rec 0.000546 | Seg 0.268245 | Elapsed 2.5m | ETA 1.7m
Epoch 399/500 | Batch 130/202 | Rec 0.000555 | Seg 0.273357 | Elapsed 2.7m | ETA 1.5m
Epoch 399/500 | Batch 140/202 | Rec 0.000567 | Seg 0.274273 | Elapsed 2.9m | ETA 1.3m
Epoch 399/500 | Batch 150/202 | Rec 0.000572 | Seg 0.277022 | Elapsed 3.1m | ETA 1.1m
Epoch 399/500 | Batch 160/202 | Rec 0.000574 | Seg 0.281943 | Elapsed 3.3m | ETA 0.9m
Epoch 399/500 | Batch 170/202 | Rec 0.000579 | Seg 0.284035 | Elapsed 3.5m | ETA 0.7m
Epoch 399/500 | Batch 180/202 | Rec 0.000576 | Seg 0.281116 | Elapsed 3.7m | ETA 0.5m
Epoch 399/500 | Batch 190/202 | Rec 0.000574 | Seg 0.278314 | Elapsed 3.9m | ETA 0.2m
Epoch 399/500 | Batch 200/202 | Rec 0.000572 | Seg 0.278940 | Elapsed 4.1m | ETA 0.0m
Epoch 399/500 | Batch 202/202 | Rec 0.000571 | Seg 0.278694 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:53:11,794 - INFO: Rec loss: 0.0005710207810222014
2026-09-26 02:53:11,794 - INFO: Seg loss: 0.27869448895649157
2026-09-26 02:53:11,794 - INFO: λ_rec: 1
2026-09-26 02:53:11,794 - INFO: λ_seg: 0.0001
2026-09-26 02:54:35,018 - INFO: -------------------Epoch: 399------------------------
2026-09-26 02:54:35,022 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  39.094406  0.97491  0.000129
2026-09-26 02:54:35,030 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995655  0.997773  0.997021  0.998626  0.995851
real potato   0.754998  0.860348  0.966460  0.775312  0.999699
fake potato   0.727777  0.842394  0.973366  0.742564  0.999798
real apple    0.753826  0.859586  0.896433  0.825741  0.999070
fake apple    0.601197  0.750887  0.989556  0.605036  0.998485
real orange   0.898489  0.946481  0.995781  0.901922  0.999866
fake orange   0.928104  0.962661  0.951437  0.974256  0.999784
real grape    0.807588  0.893503  0.922293  0.866550  0.999569
fake grape    0.900636  0.947671  0.932107  0.963866  0.999607
real lemon    0.659213  0.794561  0.681299  0.953129  0.999421
fake lemon    0.855769  0.922230  0.994660  0.859719  0.999693
real avocado  0.883384  0.938032  0.916902  0.960263  0.999882
fake avocado  0.769280  0.869547  0.999503  0.769574  0.999724
real pepper   0.802494  0.890377  0.835638  0.952903  0.999142
fake pepper   0.659980  0.795118  0.932707  0.692977  0.999149
real plant    0.866656  0.928515  0.962207  0.897196  0.998619
fake plant    0.776561  0.874180  0.828866  0.924847  0.999788
real banana   0.653697  0.790539  0.890581  0.710784  0.999154
fake banana   0.737642  0.848965  0.852673  0.845388  0.999447
real onion    0.642900  0.782591  0.683613  0.915217  0.999541
fake onion    0.940852  0.969475  0.989673  0.950181  0.999962
real unknown  0.752905  0.858987  0.800000  0.927481  0.999951
fake unknown  0.221108  0.362105  0.244395  0.698841  0.997926
total         0.764813  0.855936  0.879877  0.857060  0.999266
total(-bg)    0.754321  0.849489  0.874552  0.850625  0.999422
2026-09-26 02:54:35,575 - INFO: Epoch accounting: {'epoch': 399, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11308498, 63668, 74480, 121897, 116781, 70899, 86336, 128416, 180495, 77628, 52568, 50163, 49906, 200783, 136886, 114778, 15956, 105072, 76849, 81400, 63416, 8878, 52519], 'crops_with_class': [202, 34, 33, 32, 28, 23, 27, 23, 29, 31, 27, 18, 20, 53, 36, 16, 18, 30, 32, 37, 28, 10, 20], 'targeted_crops_by_class': [0, 6, 6, 5, 3, 7, 9, 4, 7, 4, 3, 7, 4, 4, 5, 1, 6, 7, 4, 8, 2, 1, 6], 'sampled_scene_counts': [1, 3, 3, 1, 1, 0, 1, 1, 0, 3, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 2, 1, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 0, 0, 1, 1, 3, 1, 3, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 3, 2, 2, 1, 0, 0, 0, 0, 1, 0, 1, 2, 2, 1, 1, 2, 0, 0, 0, 3, 1, 2, 3, 1, 1, 2, 2, 1, 1, 1, 0, 3, 1, 3, 0, 1, 0, 1, 1, 3, 1, 2, 3, 1, 1, 2, 3, 1, 1, 2, 2, 1, 3, 2, 3, 0, 4, 1, 0, 1, 1, 1, 3, 1, 3, 1, 2, 4, 2, 1, 1, 3, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1], 'learning_rate': 1.0146846629565007e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005710207810222014, 'train_segmentation_loss': 0.27869448895649157, 'val_foreground_miou_all22': 0.7543206578640685, 'val_psnr_ref1': 39.094406280517575, 'elapsed_seconds': 334.74988865852356, 'peak_cuda_allocated_gib': 7.506381988525391}

Epoch 400/500 | Batch 10/202 | Rec 0.000709 | Seg 0.288165 | Elapsed 0.2m | ETA 4.0m
Epoch 400/500 | Batch 20/202 | Rec 0.000631 | Seg 0.253470 | Elapsed 0.4m | ETA 3.8m
Epoch 400/500 | Batch 30/202 | Rec 0.000599 | Seg 0.251355 | Elapsed 0.6m | ETA 3.6m
Epoch 400/500 | Batch 40/202 | Rec 0.000577 | Seg 0.256482 | Elapsed 0.8m | ETA 3.4m
Epoch 400/500 | Batch 50/202 | Rec 0.000568 | Seg 0.260745 | Elapsed 1.0m | ETA 3.2m
Epoch 400/500 | Batch 60/202 | Rec 0.000565 | Seg 0.264173 | Elapsed 1.2m | ETA 2.9m
Epoch 400/500 | Batch 70/202 | Rec 0.000564 | Seg 0.268763 | Elapsed 1.5m | ETA 2.7m
Epoch 400/500 | Batch 80/202 | Rec 0.000558 | Seg 0.270950 | Elapsed 1.7m | ETA 2.5m
Epoch 400/500 | Batch 90/202 | Rec 0.000547 | Seg 0.271211 | Elapsed 1.9m | ETA 2.3m
Epoch 400/500 | Batch 100/202 | Rec 0.000558 | Seg 0.270701 | Elapsed 2.1m | ETA 2.1m
Epoch 400/500 | Batch 110/202 | Rec 0.000565 | Seg 0.270691 | Elapsed 2.3m | ETA 1.9m
Epoch 400/500 | Batch 120/202 | Rec 0.000573 | Seg 0.275362 | Elapsed 2.5m | ETA 1.7m
Epoch 400/500 | Batch 130/202 | Rec 0.000580 | Seg 0.280186 | Elapsed 2.7m | ETA 1.5m
Epoch 400/500 | Batch 140/202 | Rec 0.000580 | Seg 0.282956 | Elapsed 2.9m | ETA 1.3m
Epoch 400/500 | Batch 150/202 | Rec 0.000587 | Seg 0.285286 | Elapsed 3.1m | ETA 1.1m
Epoch 400/500 | Batch 160/202 | Rec 0.000583 | Seg 0.282831 | Elapsed 3.3m | ETA 0.9m
Epoch 400/500 | Batch 170/202 | Rec 0.000587 | Seg 0.286754 | Elapsed 3.5m | ETA 0.7m
Epoch 400/500 | Batch 180/202 | Rec 0.000591 | Seg 0.288671 | Elapsed 3.7m | ETA 0.5m
Epoch 400/500 | Batch 190/202 | Rec 0.000585 | Seg 0.286039 | Elapsed 3.9m | ETA 0.2m
Epoch 400/500 | Batch 200/202 | Rec 0.000595 | Seg 0.285532 | Elapsed 4.1m | ETA 0.0m
Epoch 400/500 | Batch 202/202 | Rec 0.000596 | Seg 0.286633 | Elapsed 4.2m | ETA 0.0m

2026-09-26 02:58:47,079 - INFO: Rec loss: 0.0005956125230410846
2026-09-26 02:58:47,079 - INFO: Seg loss: 0.28663293239061194
2026-09-26 02:58:47,080 - INFO: λ_rec: 1
2026-09-26 02:58:47,080 - INFO: λ_seg: 0.0001
2026-09-26 03:00:06,657 - INFO: -------------------Epoch: 400------------------------
2026-09-26 03:00:06,661 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.068676  0.974841  0.000129
2026-09-26 03:00:06,668 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995722  0.997806  0.997163  0.998551  0.995915
real potato   0.418316  0.589835  0.987425  0.420556  0.999300
fake potato   0.706242  0.827785  0.964345  0.725178  0.999780
real apple    0.668810  0.801491  0.793601  0.809642  0.998617
fake apple    0.611434  0.758822  0.974034  0.621565  0.998509
real orange   0.895771  0.944970  0.997683  0.897638  0.999862
fake orange   0.926560  0.961830  0.940919  0.983797  0.999777
real grape    0.845595  0.916289  0.970730  0.867719  0.999669
fake grape    0.898717  0.946607  0.921165  0.973601  0.999594
real lemon    0.463968  0.633805  0.481554  0.927032  0.998741
fake lemon    0.861218  0.925385  0.990054  0.868734  0.999704
real avocado  0.848733  0.918128  0.872983  0.968309  0.999840
fake avocado  0.741968  0.851825  0.999656  0.742158  0.999691
real pepper   0.841612  0.913945  0.888744  0.940723  0.999352
fake pepper   0.788697  0.881818  0.960966  0.814801  0.999480
real plant    0.874637  0.933077  0.961982  0.905953  0.998701
fake plant    0.794827  0.885637  0.893638  0.877876  0.999820
real banana   0.370224  0.540341  0.862459  0.393454  0.998496
fake banana   0.709946  0.830323  0.800431  0.862641  0.999352
real onion    0.668785  0.801474  0.718378  0.906435  0.999594
fake onion    0.925316  0.961160  0.985765  0.937848  0.999952
real unknown  0.640553  0.780850  0.673823  0.928435  0.999917
fake unknown  0.218737  0.358920  0.236952  0.739949  0.997773
total         0.726799  0.824440  0.864107  0.830982  0.999193
total(-bg)    0.714576  0.816560  0.858059  0.823365  0.999342
2026-09-26 03:00:07,198 - INFO: Epoch accounting: {'epoch': 400, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11234533, 61643, 56191, 96677, 144426, 93147, 83993, 185806, 197436, 77440, 62524, 30242, 29700, 253322, 105178, 158101, 26947, 73208, 69983, 90742, 59878, 10076, 37079], 'crops_with_class': [202, 38, 28, 30, 35, 29, 30, 34, 36, 32, 28, 14, 10, 61, 30, 24, 20, 22, 33, 41, 26, 14, 15], 'targeted_crops_by_class': [0, 9, 5, 3, 5, 8, 3, 5, 1, 7, 4, 3, 2, 2, 5, 6, 6, 5, 3, 12, 3, 4, 4], 'sampled_scene_counts': [1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 3, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 0, 2, 0, 1, 0, 2, 1, 2, 1, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 3, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 3, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 0, 3, 0, 2, 1, 0, 1, 2, 1, 2, 2, 5, 0, 1, 1, 0, 2, 1, 2, 2, 2, 1, 0, 0, 1, 5, 1, 1, 1, 2, 2, 1, 2, 1, 2, 0, 2, 1, 1, 4, 1, 3, 2, 1, 1, 1, 0, 1, 1, 2, 2, 0, 1, 2, 1, 5, 1, 0, 1, 0, 1, 2, 4, 2, 0, 1, 2], 'learning_rate': 9.96026920015778e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005956125230410846, 'train_segmentation_loss': 0.28663293239061194, 'val_foreground_miou_all22': 0.7145757598981378, 'val_psnr_ref1': 39.06867599487305, 'elapsed_seconds': 331.6140902042389, 'peak_cuda_allocated_gib': 7.508365631103516}

Stopped after epoch 400; scheduler horizon remains 500
Saved epoch: 400 | block target: 400 | Missing checkpoint files: []
Download: /kaggle/working/balanced300_to_epoch400_20260925_173543_epoch400.zip

/kaggle/working/balanced300_to_epoch400_20260925_173543_epoch400.zip

Epoch400 completed. Download the full backup before stopping the session.

In [1]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced300_to_epoch400_20260925_173543/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch278_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced300_to_epoch400_20260925_173543_epoch400.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch278 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch278 weights: /kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/best_iou.pth

In [2]:
NAME='epoch278_validation_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f')
RUN=WORK/NAME
subprocess.run([sys.executable,'test.py','--data_root',str(DATA),
    '--transpose_image','--eval_split','val','--pretrained_model_path',str(CHECKPOINT),
    '--outf',str(WORK),'--name',NAME,'--workers','0','--save_segmentation'],
    cwd=CODE,check=True)
OUT=RUN/'evaluation_val'
print('Evaluation complete:',OUT)

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

load model from /kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/best_iou.pth
Evaluated 1/25
Evaluated 2/25
Evaluated 3/25
Evaluated 4/25
Evaluated 5/25
Evaluated 6/25
Evaluated 7/25
Evaluated 8/25
Evaluated 9/25
Evaluated 10/25
Evaluated 11/25
Evaluated 12/25
Evaluated 13/25
Evaluated 14/25
Evaluated 15/25
Evaluated 16/25
Evaluated 17/25
Evaluated 18/25
Evaluated 19/25
Evaluated 20/25
Evaluated 21/25
Evaluated 22/25
Evaluated 23/25
Evaluated 24/25
Evaluated 25/25
Completed val: 25 scenes. Results: /kaggle/working/epoch278_validation_audit_20260927_164048_773155/evaluation_val
Evaluation complete: /kaggle/working/epoch278_validation_audit_20260927_164048_773155/evaluation_val

In [3]:
EXPECTED_MIOU=0.7862424401936461
EXPECTED_PSNR=38.36915969848633

import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['split']=='val' and meta['scene_count']==25
assert meta['checkpoint_sha256']==EXPECTED
assert len(set(meta['scenes']))==25
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(scene+'_confusion.npy')) for scene in meta['scenes']]
assert np.array_equal(sum(parts),cm), 'Per-scene confusion totals differ.'
assert len(list(OUT.glob('*_preview.png')))==25
assert not list(OUT.glob('*_hsi.npy'))
seg=pd.read_csv(OUT/'segmentation.csv',index_col=0)
rec=pd.read_csv(OUT/'reconstruction.csv')
miou=float(seg.loc['total(-bg)','IoU'])
psnr=float(rec.iloc[0]['PSNR'])
summary=dict(checkpoint_epoch=278,validation_scenes=25,foreground_miou=miou,
    psnr_ref1=psnr,logged_miou=EXPECTED_MIOU,logged_psnr=EXPECTED_PSNR,
    miou_difference=miou-EXPECTED_MIOU,psnr_difference=psnr-EXPECTED_PSNR,
    matches_logged_metrics=bool(abs(miou-EXPECTED_MIOU)<1e-5 and abs(psnr-EXPECTED_PSNR)<1e-3),
    scope='Independent full validation evaluation; no test performance or new training.')
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'evaluator_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in
    ['test.py','dataset.py','utils.py','public252-v1.json']},indent=2))
print(json.dumps(summary,indent=2))
display(seg)
display(rec)

import io
BASELINE_CSV=',IoU,F1,Prec,recall,Acc\n"bg,",0.9948839716665797,0.9973854282614268,0.9957255823734946,0.9991511511710756,0.995108642578125\nreal potato,0.8534077820356925,0.920856927078357,0.9945274220599405,0.8574343170436838,0.9998237609863281\nfake potato,0.831000609337777,0.9076514648699882,0.9967426460350126,0.8332634932286658,0.9998765563964844\nreal apple,0.7945355618563241,0.8854557035354464,0.9445140547114728,0.8334365288215987,0.9992564392089843\nfake apple,0.7085108064433383,0.8293412480663026,0.992010796714241,0.71257678341183,0.9988931274414062\nreal orange,0.8376294495094424,0.911591629208639,0.992636015373844,0.8428670583271531,0.9997846984863281\nfake orange,0.8940453126379823,0.9440090694529523,0.9276197287534351,0.961091562940563,0.9996739196777343\nreal grape,0.6859217982220894,0.8136558738019682,0.9059530132154114,0.7385076318167972,0.9992939758300782\nfake grape,0.8314671338620018,0.9079293241369685,0.9219746537886951,0.8944025042511137,0.9993293762207032\nreal lemon,0.6550680724747725,0.7915412072954824,0.7067945245175014,0.8995066099778419,0.999443359375\nfake lemon,0.8373679991568999,0.9114367831639925,0.9952189789531378,0.8407500840912364,0.999654541015625\nreal avocado,0.7732943884617149,0.8721060684390091,0.8013755047953851,0.9566502305968763,0.9997393798828125\nfake avocado,0.47198576455360475,0.6412474607286106,0.9922542470017561,0.4737311849817497,0.9993658447265625\nreal pepper,0.7932016753543454,0.8846265262467832,0.9113224196757079,0.8595444649610192,0.9991802978515625\nfake pepper,0.8931769397579965,0.9435247908004276,0.9835428026974321,0.9067281165947884,0.9997415161132812\nreal plant,0.8205660968577401,0.9013907089803945,0.9452655525412759,0.8614992664426725,0.9981156921386719\nfake plant,0.7669498456280217,0.8680559678767813,0.8540159366719359,0.8826686947341124,0.9997865295410157\nreal banana,0.6259002271166157,0.7698641578381138,0.9586116073809795,0.6432839831367378,0.9991360473632812\nfake banana,0.6914398484597389,0.8175254519708561,0.8218236605613171,0.8133709288871025,0.999332275390625\nreal onion,0.7376813392016554,0.8489915801630484,0.7653919071685393,0.9532173458331811,0.9996937561035156\nfake onion,0.9261036246136366,0.9615843040923314,0.9915232213839398,0.9334945360702651,0.9999530029296875\nreal unknown,0.8828193054784751,0.9377131527706012,0.9201101083461792,0.9561067789974448,0.9999797058105468\nfake unknown,0.21214896085379148,0.34999762141131746,0.24244749708750787,0.6293009665103049,0.9980308532714843\ntotal,0.7617002831974015,0.8529340195734696,0.8939739948612235,0.83837322707947,0.999225795579993\ntotal(-bg),0.7511010246306207,0.8463680464512897,0.8893489227015748,0.8310651396207608,0.9994129388982597\n'
BASELINE_META={'status': 'completed', 'split': 'val', 'scope': 'full split', 'checkpoint_sha256': '5ad004708dd6ce388708ad3627cf8206b184804b6202754204f7296bfc253c7b', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'reference_amplitude': 1.0, 'seed': 3407, 'torch': '2.10.0+cu128', 'gpu': 'Tesla T4', 'config': {'data_root': '/kaggle/input/datasets/arnavnigamd/btp-data/public252', 'pretrained_model_path': '/kaggle/input/datasets/arnavnigamd/checkpoint10/balanced150_to_epoch200_20260923_102523/model/best_iou.pth', 'eval_split': 'val', 'transpose_image': True, 'outf': '/kaggle/working', 'name': 'epoch188_validation_audit_20260923_152602_480885', 'workers': 0, 'mask_path': '/kaggle/input/datasets/arnavnigamd/btp-code-8/BTP/mask/mask512x512.mat', 'limit': None, 'save_predictions': False, 'save_segmentation': True, 'batch_size': 1}, 'scene_count': 25, 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050']}
assert set(meta['scenes'])==set(BASELINE_META['scenes']), 'Validation scene membership changed.'
for field in ['protocol_sha256','mask_sha256','reference_amplitude']:
    assert meta[field]==BASELINE_META[field], f'Evaluation protocol changed: {field}'
baseline=pd.read_csv(io.StringIO(BASELINE_CSV),index_col=0)
assert list(seg.index)==list(baseline.index), 'Class ordering changed.'
comparison=pd.DataFrame({'epoch188_IoU_percent':100*baseline['IoU'],
    'epoch278_IoU_percent':100*seg['IoU'],
    'change_points':100*(seg['IoU']-baseline['IoU']),
    'epoch278_precision_percent':100*seg['Prec'],
    'epoch278_recall_percent':100*seg['recall']})
comparison.to_csv(RUN/'comparison_with_epoch188.csv')
(RUN/'epoch188_segmentation_reference.csv').write_text(BASELINE_CSV)
print('Per-class comparison; percentage-point changes, not statistical significance:')
display(comparison)

# Save results even if the comparison differs, so the difference can be investigated.
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir(WORK)
print('Download this archive before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))
if not summary['matches_logged_metrics']:
    print('Metrics differ from the training record: share this ZIP before further training.')

{
  "checkpoint_epoch": 278,
  "validation_scenes": 25,
  "foreground_miou": 0.7862424401936461,
  "psnr_ref1": 38.36915969848633,
  "logged_miou": 0.7862424401936461,
  "logged_psnr": 38.36915969848633,
  "miou_difference": 0.0,
  "psnr_difference": 0.0,
  "matches_logged_metrics": true,
  "scope": "Independent full validation evaluation; no test performance or new training."
}

                   IoU        F1      Prec    recall       Acc
bg,           0.995606  0.997748  0.996554  0.999045  0.995802
real potato   0.930912  0.964170  0.995653  0.934711  0.999917
fake potato   0.952234  0.975483  0.982370  0.968789  0.999965
real apple    0.766731  0.867917  0.990807  0.772225  0.999189
fake apple    0.604342  0.753335  0.939443  0.628839  0.998446
real orange   0.926272  0.961675  0.996153  0.929597  0.999902
fake orange   0.939575  0.968796  0.963131  0.974630  0.999821
real grape    0.633693  0.775732  0.984707  0.639991  0.999228
fake grape    0.903082  0.949023  0.953041  0.945139  0.999625
real lemon    0.569311  0.725507  0.611165  0.892625  0.999206
fake lemon    0.840714  0.913416  0.998119  0.842048  0.999662
real avocado  0.943729  0.971000  0.992964  0.950082  0.999947
fake avocado  0.688385  0.815387  0.999815  0.688472  0.999627
real pepper   0.903276  0.949130  0.931731  0.967295  0.999621
fake pepper   0.900210  0.947435  0.964025  0.931502  0.999754
real plant    0.823976  0.903444  0.923268  0.884550  0.998110
fake plant    0.861634  0.925625  0.979456  0.877492  0.999888
real banana   0.565676  0.722549  0.923776  0.593372  0.998976
fake banana   0.748535  0.856136  0.875987  0.837259  0.999483
real onion    0.718995  0.836480  0.751717  0.942915  0.999667
fake onion    0.935291  0.966514  0.986650  0.947279  0.999959
real unknown  0.912149  0.954007  0.977956  0.931298  0.999986
fake unknown  0.228611  0.372109  0.244035  0.783412  0.997773
total         0.795345  0.872722  0.911414  0.863590  0.999285
total(-bg)    0.786242  0.867040  0.907544  0.857433  0.999443

       PSNR      SSIM       MSE
0  38.36916  0.973187  0.000152

Per-class comparison; percentage-point changes, not statistical significance:

,epoch188_IoU_percent,epoch278_IoU_percent,change_points,epoch278_precision_percent,epoch278_recall_percent
"bg,",99.488397,99.560569,0.072171,99.655423,99.904488
real potato,85.340778,93.091185,7.750407,99.565334,93.471052
fake potato,83.100061,95.223387,12.123326,98.237041,96.878925
real apple,79.453556,76.673107,-2.780449,99.080694,77.222468
fake apple,70.851081,60.434225,-10.416856,93.944333,62.883931
real orange,83.762945,92.627206,8.864261,99.615336,92.959702
fake orange,89.404531,93.957455,4.552924,96.313072,97.462957
real grape,68.592180,63.369274,-5.222906,98.470706,63.999123
fake grape,83.146713,90.308213,7.161500,95.304051,94.513880
real lemon,65.506807,56.931103,-8.575705,61.116543,89.262528
fake lemon,83.736800,84.071433,0.334633,99.811917,84.204832
real avocado,77.329439,94.372858,17.043419,99.296377,95.008209
fake avocado,47.198576,68.838454,21.639877,99.981480,68.847232
real pepper,79.320168,90.327607,11.007439,93.173142,96.729517
fake pepper,89.317694,90.021034,0.703340,96.402543,93.150246
real plant,82.056610,82.397578,0.340969,92.326800,88.454967
fake plant,76.694985,86.163402,9.468417,97.945643,87.749231
real banana,62.590023,56.567618,-6.022405,92.377629,59.337226
fake banana,69.143985,74.853540,5.709556,87.598715,83.725945
real onion,73.768134,71.899548,-1.868586,75.171670,94.291503
fake onion,92.610362,93.529129,0.918766,98.664985,94.727930
real unknown,88.281931,91.214945,2.933014,97.795581,93.129762
fake unknown,21.214896,22.861068,1.646172,24.403452,78.341179
total,76.170028,79.534519,3.364491,91.141412,86.358993
total(-bg),75.110102,78.624244,3.514142,90.754411,85.743288

Download this archive before stopping: epoch278_validation_audit_20260927_164048_773155.zip 7160567 bytes

/kaggle/working/epoch278_validation_audit_20260927_164048_773155.zip

In [1]:
from pathlib import Path
import json, hashlib, datetime, zipfile, shutil, os, io
import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
from scipy.ndimage import label as connected_components, find_objects
from IPython.display import display, FileLink
DATA=Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
RAW_ROOT=None  # Optional Path('/kaggle/input/.../raw_labels'); original H x W x2 arrays only.
RUN=Path('/kaggle/working')/('training_label_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
(RUN/'previews').mkdir()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()

SPEC={'protocol_id': 'public252-v1', 'date': '2026-09-16', 'scope': 'Controlled public-subset experiments, not an exact CRSDUN paper reproduction', 'dataset_files_sha256': {'train_data.csv': 'fc2a3c666d3344c7bcaedebe44c5af1a32b2f353c1f3a66c0b097d65d8839eff', 'val_data.csv': 'c1b81f6b272bffed303e3bfca099735c02cc3f536d4ef9a6b2335bbd73f5556e', 'test_data.csv': '38ea2fcea42a7cf767c3dce4029fa9055c0006633bdc497bd118365bdc9f8c16', 'all_data.csv': '96092c78659c3b83bbcde26f7f4597a51ba5959d18df6b8f85fc65ebdcb08c9c', 'split_manifest.json': '8fdffa621343cced4cd32a9da6553763cf6c2de0c04b0eb87c4e6945b4a43899', 'labels_crsdun_like_manifest.json': '68922836b85f84e2c27f625c0ce2515abd9d4a0f3f96033483b4526eeab7fb04', 'visible_28_candidate_bk7_manifest.json': '4de811f2f6e6742ed00ecb53b102ca68b3ffbdbfdc17e40bc4efe9d1e6f46df6'}, 'split_sizes': {'train': 202, 'val': 25, 'test': 25}, 'transpose_image': True, 'normalization': 'identity; retain distributed intensities', 'clipping': 'none', 'tensor_dtype': 'float32', 'labels_dtype': 'int64', 'reconstruction_metrics': {'reference_amplitude': 1.0, 'label': 'PSNR_ref1 / SSIM_ref1', 'meaning': 'Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range.'}, 'target_wavelengths_nm': [400.0, 405.26771217007314, 410.76554496731114, 416.5098328510006, 422.51851664943507, 428.81134334937263, 435.410095387312, 442.3388543250952, 449.6243046310128, 457.2960842506011, 465.3871897405087, 473.9344449415441, 482.97904344647924, 492.56717639500704, 502.75075825205676, 513.5882639304882, 525.1456904518687, 537.4976545526498, 550.7286330309245, 564.934343290246, 580.2232445419355, 596.7181110977776, 614.5575818318009, 633.8975157246186, 654.9118721117962, 677.7926758445392, 702.7484182706323, 730.0], 'wavelength_rule': 'linear interpolation from the original 10 nm FVgNET grid onto 28 wavelengths equally spaced in N-BK7 refractive-index dispersion coordinate', 'raw_fruit_id_mapping': {'1': {'real': 1, 'fake': 2}, '2': {'real': 19, 'fake': 20}, '3': {'real': 7, 'fake': 8}, '4': {'real': 15, 'fake': 16}, '5': {'real': 9, 'fake': 10}, '6': {'real': 5, 'fake': 6}, '7': {'real': 3, 'fake': 4}, '8': {'real': 13, 'fake': 14}, '9': {'real': 17, 'fake': 18}, '10': {'real': 21, 'fake': 22}, '11': {'real': 11, 'fake': 12}, '12': {'real': 21, 'fake': 22}}, 'starfruit_policy': 'Map raw ID 12 to other/unknown: real=21, fake=22; preserve real/fake distinction.', 'provenance': {'hyplex_commit': '187cd9394dae08beb883dbc6bab50a6d3f317c66'}, 'limitations': ['CRSDUN processed release could not be inspected; browser site-safety policy blocks Baidu share.', 'Exact author wavelength grid and raw-to-23-class conversion are not published in inspected source.', 'Distributed intensity radiometric calibration is not established; identity is a project convention supported by the active Hyplex loader.', 'Published paper scores are not directly comparable to public252-v1 scores.']}
HISTORICAL_TRAIN_RAW={'2021-11-03_007': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_008': {'raw_fruit_ids': [-1, 0, 6, 7], 'starfruit_pixels': 0}, '2021-11-03_010': {'raw_fruit_ids': [-1, 0, 5, 6], 'starfruit_pixels': 0}, '2021-11-03_015': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_017': {'raw_fruit_ids': [-1, 0, 3, 7], 'starfruit_pixels': 0}, '2021-11-03_018': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-03_020': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-03_021': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-03_023': {'raw_fruit_ids': [-1, 0, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-03_025': {'raw_fruit_ids': [-1, 0, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-03_032': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_033': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_034': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_035': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_036': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_037': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_040': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_041': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_042': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_043': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_045': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_048': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_049': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_051': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_052': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_053': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_054': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_055': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_056': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_058': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_080': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_081': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_082': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_084': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_086': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_087': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_088': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_089': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_091': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_092': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_094': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_099': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_101': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_102': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_103': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_104': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_001': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_006': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_007': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_008': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_009': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_011': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_016': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_018': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_019': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_020': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_021': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_022': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_023': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_025': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_026': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_027': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_028': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_030': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_031': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_032': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_033': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_034': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_035': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_036': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_037': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_038': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_039': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_041': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_044': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_045': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_046': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_048': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_050': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_051': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_052': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_053': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_054': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_056': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_057': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_058': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_059': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_062': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_063': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_064': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_065': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_066': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_067': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_068': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_069': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_070': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_071': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_072': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_073': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_074': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_075': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_076': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_077': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_079': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_080': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_081': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_082': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_083': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_084': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_085': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_086': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_089': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_090': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_091': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_092': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_094': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_095': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_096': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_097': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_102': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_103': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-04_105': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-04_106': {'raw_fruit_ids': [-1, 0, 3, 5, 6], 'starfruit_pixels': 0}, '2021-11-04_107': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7], 'starfruit_pixels': 0}, '2021-11-04_108': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7], 'starfruit_pixels': 0}, '2021-11-05_001': {'raw_fruit_ids': [-1, 0, 5, 6, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_002': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_004': {'raw_fruit_ids': [-1, 0, 3, 5, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_005': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_006': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_008': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_009': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_012': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_013': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_014': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_015': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 8], 'starfruit_pixels': 0}, '2021-11-05_016': {'raw_fruit_ids': [-1, 0, 3, 5, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_017': {'raw_fruit_ids': [-1, 0, 3, 4], 'starfruit_pixels': 0}, '2021-11-05_018': {'raw_fruit_ids': [-1, 0, 4, 8, 11], 'starfruit_pixels': 0}, '2021-11-05_019': {'raw_fruit_ids': [-1, 0, 6, 9, 11, 12], 'starfruit_pixels': 2013}, '2021-11-05_020': {'raw_fruit_ids': [-1, 0, 3, 4, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_021': {'raw_fruit_ids': [-1, 0, 7, 8, 11], 'starfruit_pixels': 0}, '2021-11-05_022': {'raw_fruit_ids': [-1, 0, 5, 6, 11], 'starfruit_pixels': 0}, '2021-11-05_025': {'raw_fruit_ids': [-1, 0, 3, 4, 8], 'starfruit_pixels': 0}, '2021-11-05_027': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 11], 'starfruit_pixels': 0}, '2021-11-05_028': {'raw_fruit_ids': [-1, 0, 6, 9, 10, 12], 'starfruit_pixels': 1807}, '2021-11-05_029': {'raw_fruit_ids': [-1, 0, 3, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_032': {'raw_fruit_ids': [-1, 0, 4, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_033': {'raw_fruit_ids': [-1, 0, 4, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_034': {'raw_fruit_ids': [-1, 0, 4, 5, 7, 8, 9], 'starfruit_pixels': 0}, '2021-11-05_042': {'raw_fruit_ids': [-1, 0, 4, 5, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_043': {'raw_fruit_ids': [-1, 0, 3, 4, 11, 12], 'starfruit_pixels': 1781}, '2021-11-05_047': {'raw_fruit_ids': [-1, 0, 4, 5, 6], 'starfruit_pixels': 0}, '2021-11-05_049': {'raw_fruit_ids': [-1, 0, 3, 7, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_050': {'raw_fruit_ids': [-1, 0, 3, 4, 7, 9, 10], 'starfruit_pixels': 0}, '2021-11-05_051': {'raw_fruit_ids': [-1, 0, 4, 5, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_052': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 8], 'starfruit_pixels': 0}, '2021-11-05_053': {'raw_fruit_ids': [-1, 0, 3, 6, 7, 8, 9], 'starfruit_pixels': 0}, '2021-11-05_055': {'raw_fruit_ids': [-1, 0, 3, 7, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_056': {'raw_fruit_ids': [-1, 0, 7, 8, 9, 10, 11], 'starfruit_pixels': 0}, '2021-11-05_057': {'raw_fruit_ids': [-1, 0, 3, 4, 6, 8, 9, 10], 'starfruit_pixels': 0}, '2021-11-05_058': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_059': {'raw_fruit_ids': [-1, 0, 5, 7, 8, 10, 11], 'starfruit_pixels': 0}, '2021-11-05_060': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7, 10, 12], 'starfruit_pixels': 3428}, '2021-11-10_001': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_002': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_003': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_005': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_006': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_007': {'raw_fruit_ids': [-1, 0, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_008': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_009': {'raw_fruit_ids': [-1, 0, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_011': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_012': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_013': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_016': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_017': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_018': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_019': {'raw_fruit_ids': [-1, 0, 1, 8], 'starfruit_pixels': 0}, '2021-11-10_020': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_021': {'raw_fruit_ids': [-1, 0, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_022': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_023': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_025': {'raw_fruit_ids': [-1, 0, 1, 9], 'starfruit_pixels': 0}, '2021-11-10_026': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_027': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_028': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_030': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_032': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_033': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_035': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_036': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_038': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_040': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_041': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-10_042': {'raw_fruit_ids': [-1, 0, 2], 'starfruit_pixels': 0}, '2021-11-10_043': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_044': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_045': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_046': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_048': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_049': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}}

assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
assert sha(DATA/'train_data.csv')==SPEC['dataset_files_sha256']['train_data.csv'], 'Training split changed.'
manifest_path=DATA/'labels_crsdun_like_manifest.json'
assert manifest_path.is_file(), 'Prepared label manifest missing.'
assert sha(manifest_path)==SPEC['dataset_files_sha256']['labels_crsdun_like_manifest.json'], 'Label manifest changed.'
manifest=json.loads(manifest_path.read_text())
assert manifest['mapping']==SPEC['raw_fruit_id_mapping']
train=pd.read_csv(DATA/'train_data.csv',index_col=0)
names=sorted(train['names'].astype(str).tolist())
assert len(names)==len(set(names))==202
assert set(names)==set(HISTORICAL_TRAIN_RAW)
if RAW_ROOT is not None:
    RAW_ROOT=Path(RAW_ROOT)
    assert RAW_ROOT.is_dir()
print('Training scenes:',len(names),'| GPU not needed')
print('Fresh original raw-label audit:', 'enabled' if RAW_ROOT else 'unavailable; prepared labels and historical provenance only')
print('Frozen mapping: raw apple7 -> fake apple4; raw avocado11 -> fake avocado12; raw unknown10 and starfruit12 -> fake unknown22.')

Training scenes: 202 | GPU not needed
Fresh original raw-label audit: unavailable; prepared labels and historical provenance only
Frozen mapping: raw apple7 -> fake apple4; raw avocado11 -> fake avocado12; raw unknown10 and starfruit12 -> fake unknown22.

In [2]:
from pathlib import Path
import json, hashlib, datetime, zipfile, shutil, os, io
import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
from scipy.ndimage import label as connected_components, find_objects
from IPython.display import display, FileLink
DATA=Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
RAW_ROOT=None  # Optional Path('/kaggle/input/.../raw_labels'); original H x W x2 arrays only.
RUN=Path('/kaggle/working')/('training_label_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
(RUN/'previews').mkdir()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()

SPEC={'protocol_id': 'public252-v1', 'date': '2026-09-16', 'scope': 'Controlled public-subset experiments, not an exact CRSDUN paper reproduction', 'dataset_files_sha256': {'train_data.csv': 'fc2a3c666d3344c7bcaedebe44c5af1a32b2f353c1f3a66c0b097d65d8839eff', 'val_data.csv': 'c1b81f6b272bffed303e3bfca099735c02cc3f536d4ef9a6b2335bbd73f5556e', 'test_data.csv': '38ea2fcea42a7cf767c3dce4029fa9055c0006633bdc497bd118365bdc9f8c16', 'all_data.csv': '96092c78659c3b83bbcde26f7f4597a51ba5959d18df6b8f85fc65ebdcb08c9c', 'split_manifest.json': '8fdffa621343cced4cd32a9da6553763cf6c2de0c04b0eb87c4e6945b4a43899', 'labels_crsdun_like_manifest.json': '68922836b85f84e2c27f625c0ce2515abd9d4a0f3f96033483b4526eeab7fb04', 'visible_28_candidate_bk7_manifest.json': '4de811f2f6e6742ed00ecb53b102ca68b3ffbdbfdc17e40bc4efe9d1e6f46df6'}, 'split_sizes': {'train': 202, 'val': 25, 'test': 25}, 'transpose_image': True, 'normalization': 'identity; retain distributed intensities', 'clipping': 'none', 'tensor_dtype': 'float32', 'labels_dtype': 'int64', 'reconstruction_metrics': {'reference_amplitude': 1.0, 'label': 'PSNR_ref1 / SSIM_ref1', 'meaning': 'Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range.'}, 'target_wavelengths_nm': [400.0, 405.26771217007314, 410.76554496731114, 416.5098328510006, 422.51851664943507, 428.81134334937263, 435.410095387312, 442.3388543250952, 449.6243046310128, 457.2960842506011, 465.3871897405087, 473.9344449415441, 482.97904344647924, 492.56717639500704, 502.75075825205676, 513.5882639304882, 525.1456904518687, 537.4976545526498, 550.7286330309245, 564.934343290246, 580.2232445419355, 596.7181110977776, 614.5575818318009, 633.8975157246186, 654.9118721117962, 677.7926758445392, 702.7484182706323, 730.0], 'wavelength_rule': 'linear interpolation from the original 10 nm FVgNET grid onto 28 wavelengths equally spaced in N-BK7 refractive-index dispersion coordinate', 'raw_fruit_id_mapping': {'1': {'real': 1, 'fake': 2}, '2': {'real': 19, 'fake': 20}, '3': {'real': 7, 'fake': 8}, '4': {'real': 15, 'fake': 16}, '5': {'real': 9, 'fake': 10}, '6': {'real': 5, 'fake': 6}, '7': {'real': 3, 'fake': 4}, '8': {'real': 13, 'fake': 14}, '9': {'real': 17, 'fake': 18}, '10': {'real': 21, 'fake': 22}, '11': {'real': 11, 'fake': 12}, '12': {'real': 21, 'fake': 22}}, 'starfruit_policy': 'Map raw ID 12 to other/unknown: real=21, fake=22; preserve real/fake distinction.', 'provenance': {'hyplex_commit': '187cd9394dae08beb883dbc6bab50a6d3f317c66'}, 'limitations': ['CRSDUN processed release could not be inspected; browser site-safety policy blocks Baidu share.', 'Exact author wavelength grid and raw-to-23-class conversion are not published in inspected source.', 'Distributed intensity radiometric calibration is not established; identity is a project convention supported by the active Hyplex loader.', 'Published paper scores are not directly comparable to public252-v1 scores.']}
HISTORICAL_TRAIN_RAW={'2021-11-03_007': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_008': {'raw_fruit_ids': [-1, 0, 6, 7], 'starfruit_pixels': 0}, '2021-11-03_010': {'raw_fruit_ids': [-1, 0, 5, 6], 'starfruit_pixels': 0}, '2021-11-03_015': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_017': {'raw_fruit_ids': [-1, 0, 3, 7], 'starfruit_pixels': 0}, '2021-11-03_018': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-03_020': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-03_021': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-03_023': {'raw_fruit_ids': [-1, 0, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-03_025': {'raw_fruit_ids': [-1, 0, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-03_032': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_033': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_034': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_035': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_036': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_037': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_040': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_041': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_042': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_043': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_045': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_048': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_049': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_051': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_052': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_053': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_054': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_055': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_056': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_058': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_080': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_081': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_082': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_084': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_086': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_087': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_088': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_089': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_091': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_092': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_094': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_099': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_101': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_102': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_103': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_104': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_001': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_006': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_007': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_008': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_009': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_011': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_016': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_018': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_019': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_020': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_021': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_022': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_023': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_025': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_026': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_027': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_028': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_030': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_031': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_032': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_033': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_034': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_035': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_036': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_037': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_038': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_039': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_041': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_044': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_045': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_046': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_048': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_050': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_051': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_052': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_053': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_054': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_056': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_057': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_058': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_059': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_062': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_063': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_064': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_065': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_066': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_067': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_068': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_069': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_070': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_071': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_072': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_073': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_074': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_075': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_076': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_077': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_079': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_080': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_081': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_082': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_083': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_084': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_085': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_086': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_089': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_090': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_091': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_092': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_094': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_095': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_096': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_097': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_102': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_103': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-04_105': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-04_106': {'raw_fruit_ids': [-1, 0, 3, 5, 6], 'starfruit_pixels': 0}, '2021-11-04_107': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7], 'starfruit_pixels': 0}, '2021-11-04_108': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7], 'starfruit_pixels': 0}, '2021-11-05_001': {'raw_fruit_ids': [-1, 0, 5, 6, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_002': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_004': {'raw_fruit_ids': [-1, 0, 3, 5, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_005': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_006': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_008': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_009': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_012': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_013': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_014': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_015': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 8], 'starfruit_pixels': 0}, '2021-11-05_016': {'raw_fruit_ids': [-1, 0, 3, 5, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_017': {'raw_fruit_ids': [-1, 0, 3, 4], 'starfruit_pixels': 0}, '2021-11-05_018': {'raw_fruit_ids': [-1, 0, 4, 8, 11], 'starfruit_pixels': 0}, '2021-11-05_019': {'raw_fruit_ids': [-1, 0, 6, 9, 11, 12], 'starfruit_pixels': 2013}, '2021-11-05_020': {'raw_fruit_ids': [-1, 0, 3, 4, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_021': {'raw_fruit_ids': [-1, 0, 7, 8, 11], 'starfruit_pixels': 0}, '2021-11-05_022': {'raw_fruit_ids': [-1, 0, 5, 6, 11], 'starfruit_pixels': 0}, '2021-11-05_025': {'raw_fruit_ids': [-1, 0, 3, 4, 8], 'starfruit_pixels': 0}, '2021-11-05_027': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 11], 'starfruit_pixels': 0}, '2021-11-05_028': {'raw_fruit_ids': [-1, 0, 6, 9, 10, 12], 'starfruit_pixels': 1807}, '2021-11-05_029': {'raw_fruit_ids': [-1, 0, 3, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_032': {'raw_fruit_ids': [-1, 0, 4, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_033': {'raw_fruit_ids': [-1, 0, 4, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_034': {'raw_fruit_ids': [-1, 0, 4, 5, 7, 8, 9], 'starfruit_pixels': 0}, '2021-11-05_042': {'raw_fruit_ids': [-1, 0, 4, 5, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_043': {'raw_fruit_ids': [-1, 0, 3, 4, 11, 12], 'starfruit_pixels': 1781}, '2021-11-05_047': {'raw_fruit_ids': [-1, 0, 4, 5, 6], 'starfruit_pixels': 0}, '2021-11-05_049': {'raw_fruit_ids': [-1, 0, 3, 7, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_050': {'raw_fruit_ids': [-1, 0, 3, 4, 7, 9, 10], 'starfruit_pixels': 0}, '2021-11-05_051': {'raw_fruit_ids': [-1, 0, 4, 5, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_052': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 8], 'starfruit_pixels': 0}, '2021-11-05_053': {'raw_fruit_ids': [-1, 0, 3, 6, 7, 8, 9], 'starfruit_pixels': 0}, '2021-11-05_055': {'raw_fruit_ids': [-1, 0, 3, 7, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_056': {'raw_fruit_ids': [-1, 0, 7, 8, 9, 10, 11], 'starfruit_pixels': 0}, '2021-11-05_057': {'raw_fruit_ids': [-1, 0, 3, 4, 6, 8, 9, 10], 'starfruit_pixels': 0}, '2021-11-05_058': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_059': {'raw_fruit_ids': [-1, 0, 5, 7, 8, 10, 11], 'starfruit_pixels': 0}, '2021-11-05_060': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7, 10, 12], 'starfruit_pixels': 3428}, '2021-11-10_001': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_002': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_003': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_005': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_006': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_007': {'raw_fruit_ids': [-1, 0, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_008': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_009': {'raw_fruit_ids': [-1, 0, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_011': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_012': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_013': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_016': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_017': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_018': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_019': {'raw_fruit_ids': [-1, 0, 1, 8], 'starfruit_pixels': 0}, '2021-11-10_020': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_021': {'raw_fruit_ids': [-1, 0, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_022': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_023': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_025': {'raw_fruit_ids': [-1, 0, 1, 9], 'starfruit_pixels': 0}, '2021-11-10_026': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_027': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_028': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_030': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_032': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_033': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_035': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_036': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_038': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_040': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_041': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-10_042': {'raw_fruit_ids': [-1, 0, 2], 'starfruit_pixels': 0}, '2021-11-10_043': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_044': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_045': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_046': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_048': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_049': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}}

assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
assert sha(DATA/'train_data.csv')==SPEC['dataset_files_sha256']['train_data.csv'], 'Training split changed.'
manifest_path=DATA/'labels_crsdun_like_manifest.json'
assert manifest_path.is_file(), 'Prepared label manifest missing.'
assert sha(manifest_path)==SPEC['dataset_files_sha256']['labels_crsdun_like_manifest.json'], 'Label manifest changed.'
manifest=json.loads(manifest_path.read_text())
assert manifest['mapping']==SPEC['raw_fruit_id_mapping']
train=pd.read_csv(DATA/'train_data.csv',index_col=0)
names=sorted(train['names'].astype(str).tolist())
assert len(names)==len(set(names))==202
assert set(names)==set(HISTORICAL_TRAIN_RAW)
if RAW_ROOT is not None:
    RAW_ROOT=Path(RAW_ROOT)
    assert RAW_ROOT.is_dir()
print('Training scenes:',len(names),'| GPU not needed')
print('Fresh original raw-label audit:', 'enabled' if RAW_ROOT else 'unavailable; prepared labels and historical provenance only')
print('Frozen mapping: raw apple7 -> fake apple4; raw avocado11 -> fake avocado12; raw unknown10 and starfruit12 -> fake unknown22.')

Training scenes: 202 | GPU not needed
Fresh original raw-label audit: unavailable; prepared labels and historical provenance only
Frozen mapping: raw apple7 -> fake apple4; raw avocado11 -> fake avocado12; raw unknown10 and starfruit12 -> fake unknown22.

In [3]:
PALETTE=np.array([[0,0,0],[128,0,0],[0,128,0],[128,128,0],[0,0,128],[128,0,128],[0,128,128],[128,128,128],[64,0,0],[192,0,0],[64,128,0],[192,128,0],[64,0,128],[192,0,128],[64,128,128],[192,128,128],[0,64,0],[128,64,0],[0,192,0],[128,192,0],[0,64,128],[128,64,128],[0,192,128]],dtype=np.uint8)
TARGETS={4:'fake apple',12:'fake avocado',22:'fake unknown'}
def decode(rgb):
    assert rgb.shape==(512,512,3), f'Unexpected label shape: {rgb.shape}'
    ids=np.full(rgb.shape[:2],255,dtype=np.uint8)
    for i,color in enumerate(PALETTE): ids[np.all(rgb==color,axis=-1)]=i
    assert not np.any(ids==255), 'Unexpected palette color; will not silently map it to background.'
    return ids

def raw_to_ids(raw):
    assert raw.shape==(512,512,2) and np.isfinite(raw).all()
    assert np.equal(raw,np.round(raw)).all()
    fruit,flag=raw[:,:,0],raw[:,:,1]
    assert set(np.unique(fruit))<=set([-1,0]+list(range(1,13)))
    assert set(np.unique(flag[fruit>0]))<={-1,1}
    ids=np.zeros((512,512),dtype=np.uint8)
    for fid,entry in SPEC['raw_fruit_id_mapping'].items():
        ids[(fruit==int(fid))&(flag==1)]=entry['real']
        ids[(fruit==int(fid))&(flag==-1)]=entry['fake']
    return ids
rows=[];spectra=[];components=[];file_hashes={};errors=[];raw_checks=[];selected=[]
for index,scene in enumerate(names):
    label_path=DATA/'labels'/(scene+'.png')
    rgb_label=np.array(Image.open(label_path))
    ids=decode(rgb_label)
    counts=np.bincount(ids.ravel(),minlength=23)
    file_hashes[scene]={'prepared_label_sha256':sha(label_path)}
    row={'scene':scene,**{f'class_{c}_pixels':int(counts[c]) for c in range(23)},
         'historical_raw_fruit_ids':HISTORICAL_TRAIN_RAW[scene]['raw_fruit_ids'],
         'historical_starfruit_pixels':HISTORICAL_TRAIN_RAW[scene]['starfruit_pixels']}
    rows.append(row)
    if RAW_ROOT is not None:
        rp=RAW_ROOT/(scene+'.npy')
        if rp.is_file():
            raw=np.load(rp,allow_pickle=False)
            mismatch=int(np.count_nonzero(raw_to_ids(raw)!=ids))
            raw_checks.append({'scene':scene,'mismatch_pixels':mismatch,
                'fake_unknown_raw10_pixels':int(np.sum((raw[:,:,0]==10)&(raw[:,:,1]==-1))),
                'fake_unknown_raw12_pixels':int(np.sum((raw[:,:,0]==12)&(raw[:,:,1]==-1)))})
            file_hashes[scene]['raw_sha256']=sha(rp)
            if mismatch: errors.append(scene+': raw conversion differs from prepared labels')
        else: raw_checks.append({'scene':scene,'status':'missing raw file'})
    present=[c for c in TARGETS if counts[c]>0]
    if present:
        selected.append(scene)
        xp=DATA/'visible_28'/(scene+'.npy')
        x=np.load(xp,mmap_mode='r',allow_pickle=False).transpose(1,0,2)
        assert x.shape==(512,512,28)
        rgb=np.asarray(x[:,:,[24,18,8]],dtype=np.float32)
        assert np.isfinite(rgb).all()
        rgb=(np.clip(rgb/max(float(np.quantile(rgb,.99)),1e-8),0,1)*255).astype(np.uint8)
        overlay=rgb.copy()
        for c in present:
            mask=ids==c
            overlay[mask]=(0.5*rgb[mask]+0.5*PALETTE[c]).astype(np.uint8)
            values=np.asarray(x[mask],dtype=np.float64)
            assert np.isfinite(values).all()
            spectra.append({'scene':scene,'class_id':c,'class_name':TARGETS[c],'pixels':int(mask.sum()),
                'mean_spectrum':values.mean(axis=0).tolist(),'std_spectrum':values.std(axis=0).tolist()})
            cc,n=connected_components(mask)
            for k,sl in enumerate(find_objects(cc),1):
                if sl is None:continue
                area=int(np.count_nonzero(cc[sl]==k))
                components.append({'scene':scene,'class_id':c,'component':k,'pixels':area,
                    'row_start':sl[0].start,'row_end_exclusive':sl[0].stop,'col_start':sl[1].start,'col_end_exclusive':sl[1].stop})
        canvas=Image.new('RGB',(1536,560),'white');draw=ImageDraw.Draw(canvas)
        for j,(panel,title) in enumerate([(rgb,'Pseudo-RGB'),(rgb_label,'Prepared ground truth'),(overlay,'Target-class overlay')]):
            canvas.paste(Image.fromarray(panel),(j*512,48));draw.text((j*512+5,5),scene+' | '+title,fill='black')
        draw.text((5,25),' | '.join(f'{c}: {TARGETS[c]} ({counts[c]} pixels)' for c in present),fill='black')
        canvas.save(RUN/'previews'/(scene+'.png'))
        del x
    if (index+1)%25==0 or index+1==len(names): print(f'Audited training labels: {index+1}/{len(names)}',flush=True)
summary={'scope':'Training-only label/provenance audit; no model inference, test data or label changes.',
    'train_scenes':len(names),'selected_scenes':len(selected),'selected_scene_ids':selected,
    'classes':{str(c):{'name':name,'scenes':sum(r[f'class_{c}_pixels']>0 for r in rows),
        'pixels':sum(r[f'class_{c}_pixels'] for r in rows)} for c,name in TARGETS.items()},
    'fresh_raw_files_checked':sum('mismatch_pixels' in r for r in raw_checks),
    'fresh_raw_status':'unavailable' if RAW_ROOT is None else 'complete' if len(raw_checks)==202 and all('mismatch_pixels' in r for r in raw_checks) else 'partial',
    'errors':errors,'historical_raw_source':'September16 audit; embedded train-only scene metadata, not a fresh raw-label verification',
    'limitations':['Prepared unknown labels cannot distinguish raw10 from raw12 without original raw labels.',
        'Conversion consistency does not establish semantic annotation correctness.',
        'Scene-level mean spectra can mix multiple objects; spectral similarity is descriptive, not a classification bound.']}
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'train_scene_counts.json').write_text(json.dumps(rows,indent=2))
(RUN/'target_spectra.json').write_text(json.dumps(spectra,indent=2))
(RUN/'components.json').write_text(json.dumps(components,indent=2))
(RUN/'raw_conversion_checks.json').write_text(json.dumps(raw_checks,indent=2))
(RUN/'label_hashes.json').write_text(json.dumps(file_hashes,indent=2))
(RUN/'frozen_label_manifest.json').write_text(json.dumps(manifest,indent=2))
print(json.dumps(summary,indent=2))

Audited training labels: 25/202
Audited training labels: 50/202
Audited training labels: 75/202
Audited training labels: 100/202
Audited training labels: 125/202
Audited training labels: 150/202
Audited training labels: 175/202
Audited training labels: 200/202
Audited training labels: 202/202
{
  "scope": "Training-only label/provenance audit; no model inference, test data or label changes.",
  "train_scenes": 202,
  "selected_scenes": 57,
  "selected_scene_ids": [
    "2021-11-03_017",
    "2021-11-03_020",
    "2021-11-03_021",
    "2021-11-03_023",
    "2021-11-03_025",
    "2021-11-04_056",
    "2021-11-04_057",
    "2021-11-04_058",
    "2021-11-04_059",
    "2021-11-04_062",
    "2021-11-04_063",
    "2021-11-04_064",
    "2021-11-04_065",
    "2021-11-04_066",
    "2021-11-04_082",
    "2021-11-04_083",
    "2021-11-04_084",
    "2021-11-04_085",
    "2021-11-04_086",
    "2021-11-04_089",
    "2021-11-04_090",
    "2021-11-04_091",
    "2021-11-04_092",
    "2021-11-04_094",
    "2021-11-04_095",
    "2021-11-04_096",
    "2021-11-04_097",
    "2021-11-04_102",
    "2021-11-04_103",
    "2021-11-04_105",
    "2021-11-04_108",
    "2021-11-05_001",
    "2021-11-05_002",
    "2021-11-05_008",
    "2021-11-05_009",
    "2021-11-05_012",
    "2021-11-05_013",
    "2021-11-05_014",
    "2021-11-05_016",
    "2021-11-05_019",
    "2021-11-05_020",
    "2021-11-05_021",
    "2021-11-05_022",
    "2021-11-05_027",
    "2021-11-05_028",
    "2021-11-05_029",
    "2021-11-05_034",
    "2021-11-05_042",
    "2021-11-05_043",
    "2021-11-05_049",
    "2021-11-05_050",
    "2021-11-05_055",
    "2021-11-05_056",
    "2021-11-05_057",
    "2021-11-05_058",
    "2021-11-05_059",
    "2021-11-05_060"
  ],
  "classes": {
    "4": {
      "name": "fake apple",
      "scenes": 38,
      "pixels": 237011
    },
    "12": {
      "name": "fake avocado",
      "scenes": 15,
      "pixels": 54898
    },
    "22": {
      "name": "fake unknown",
      "scenes": 14,
      "pixels": 40026
    }
  },
  "fresh_raw_files_checked": 0,
  "fresh_raw_status": "unavailable",
  "errors": [],
  "historical_raw_source": "September16 audit; embedded train-only scene metadata, not a fresh raw-label verification",
  "limitations": [
    "Prepared unknown labels cannot distinguish raw10 from raw12 without original raw labels.",
    "Conversion consistency does not establish semantic annotation correctness.",
    "Scene-level mean spectra can mix multiple objects; spectral similarity is descriptive, not a classification bound."
  ]
}

In [4]:
# Contact sheets retain every selected training scene, sorted by scene ID.
thumbs=[]
for scene in selected:
    with Image.open(RUN/'previews'/(scene+'.png')) as im:
        thumbs.append(im.resize((768,280)))
for page,start in enumerate(range(0,len(thumbs),8),1):
    items=thumbs[start:start+8]
    sheet=Image.new('RGB',(1536,280*((len(items)+1)//2)),'white')
    for j,im in enumerate(items): sheet.paste(im,((j%2)*768,(j//2)*280))
    sheet.save(RUN/f'contact_sheet_{page:02d}.jpg',quality=90)
# Plot per-scene mean target spectra without fitting or normalizing the data.
import matplotlib.pyplot as plt
fig,axes=plt.subplots(1,3,figsize=(15,4),sharex=True)
for ax,(c,name) in zip(axes,TARGETS.items()):
    for row in spectra:
        if row['class_id']==c: ax.plot(SPEC['target_wavelengths_nm'],row['mean_spectrum'],alpha=.35)
    ax.set_title(name);ax.set_xlabel('Candidate wavelength (nm)');ax.set_ylabel('Mean distributed intensity')
fig.tight_layout();fig.savefig(RUN/'training_mean_spectra.png',dpi=160);plt.close(fig)
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=RUN.parent,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir('/kaggle/working')
print('Download before stopping:',archive.name,'bytes:',archive.stat().st_size)
display(FileLink(archive.name))

Download before stopping: training_label_audit_20260927_165341_462108.zip bytes: 18633325

/kaggle/working/training_label_audit_20260927_165341_462108.zip

In [1]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced300_to_epoch400_20260925_173543/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch278_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced300_to_epoch400_20260925_173543_epoch400.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch278 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch278 weights: /kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/best_iou.pth

In [2]:
SCRIPT="\nimport argparse,json,hashlib,sys\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom PIL import Image\np=argparse.ArgumentParser()\np.add_argument('--code',type=Path,required=True);p.add_argument('--data',type=Path,required=True)\np.add_argument('--checkpoint',type=Path,required=True);p.add_argument('--out',type=Path,required=True)\np.add_argument('--selection',type=Path,required=True)\na=p.parse_args();sys.path.insert(0,str(a.code))\nfrom dataset import HySpecSegmentation,SegIdentityTransform,encode_segmap,get_labels\nfrom torch.utils.data import DataLoader\nfrom test import evaluate_batches,sha256\nfrom utils import init_mask,init_meas,set_seed\nfrom models import model_generator\nspec=json.loads((a.code/'public252-v1.json').read_text())\nassert sha256(a.data/'train_data.csv')==spec['dataset_files_sha256']['train_data.csv']\nselection=json.loads(a.selection.read_text())\nassert sha256(a.checkpoint)==selection['checkpoint_sha256']\nds=HySpecSegmentation(str(a.data),'train_data.csv',transform=SegIdentityTransform(),transpose_image=True)\nassert len(ds)==202\nchosen=[]\nfor scene in ds.names:\n    rgb=np.array(Image.open(a.data/'labels'/(str(scene)+'.png')))\n    ids=encode_segmap(rgb)\n    assert np.array_equal(get_labels()[ids],rgb), 'Unrecognized label color'\n    if np.isin(ids,[4,12,22]).any(): chosen.append(str(scene))\nassert sorted(chosen)==selection['scenes'], 'Selection differs from the verified training-label audit'\nds.data=ds.data[ds.data.names.astype(str).isin(chosen)].copy()\nds.names=np.array(sorted(chosen))\nassert len(ds)==len(ds.names)==57\nloader=DataLoader(ds,batch_size=1,shuffle=False,num_workers=0)\na.out.mkdir(exist_ok=False,parents=True)\nset_seed(3407)\nmodel=model_generator('CRSDUN',28,ds.num_classes,str(a.checkpoint))\nphi,mask=init_mask(str(a.code/'mask/mask512x512.mat'),'SSR',1,28)\nrecord={'status':'running','split':'selected_train','checkpoint_epoch':278,\n    'checkpoint_sha256':sha256(a.checkpoint),'protocol_sha256':sha256(a.code/'public252-v1.json'),\n    'mask_sha256':sha256(a.code/'mask/mask512x512.mat'),'torch':str(torch.__version__),\n    'gpu':torch.cuda.get_device_name(0),'selection_rule':'All training scenes containing class4,12 or22 in prepared labels',\n    'scope':'Full-frame evaluation on selected training scenes; no optimization or held-out image access',\n    'limitations':'Selection is conditioned on target ground truth. Precision and aggregate mIoU are not representative of the full train split; comparison with validation is descriptive.'}\n(a.out/'evaluation.json').write_text(json.dumps(record,indent=2))\nscenes=evaluate_batches(model,loader,lambda x:init_meas(x,phi,'Y'),mask,'cuda',a.out,save_segmentation=True)\nrecord.update(status='completed',scene_count=len(scenes),scenes=scenes)\n(a.out/'evaluation.json').write_text(json.dumps(record,indent=2))\n"
SELECTION={'scenes': ['2021-11-03_017', '2021-11-03_020', '2021-11-03_021', '2021-11-03_023', '2021-11-03_025', '2021-11-04_056', '2021-11-04_057', '2021-11-04_058', '2021-11-04_059', '2021-11-04_062', '2021-11-04_063', '2021-11-04_064', '2021-11-04_065', '2021-11-04_066', '2021-11-04_082', '2021-11-04_083', '2021-11-04_084', '2021-11-04_085', '2021-11-04_086', '2021-11-04_089', '2021-11-04_090', '2021-11-04_091', '2021-11-04_092', '2021-11-04_094', '2021-11-04_095', '2021-11-04_096', '2021-11-04_097', '2021-11-04_102', '2021-11-04_103', '2021-11-04_105', '2021-11-04_108', '2021-11-05_001', '2021-11-05_002', '2021-11-05_008', '2021-11-05_009', '2021-11-05_012', '2021-11-05_013', '2021-11-05_014', '2021-11-05_016', '2021-11-05_019', '2021-11-05_020', '2021-11-05_021', '2021-11-05_022', '2021-11-05_027', '2021-11-05_028', '2021-11-05_029', '2021-11-05_034', '2021-11-05_042', '2021-11-05_043', '2021-11-05_049', '2021-11-05_050', '2021-11-05_055', '2021-11-05_056', '2021-11-05_057', '2021-11-05_058', '2021-11-05_059', '2021-11-05_060'], 'checkpoint_sha256': '89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c'}

RUN=WORK/('epoch278_training_fit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
SCRIPT_PATH=RUN/'training_diagnostic.py'
SCRIPT_PATH.write_text(SCRIPT)
(RUN/'selection.json').write_text(json.dumps(SELECTION,indent=2))
subprocess.run([sys.executable,str(SCRIPT_PATH),'--code',str(CODE),'--data',str(DATA),
    '--checkpoint',str(CHECKPOINT),'--out',str(RUN/'evaluation_train'),
    '--selection',str(RUN/'selection.json')],cwd=CODE,check=True)
OUT=RUN/'evaluation_train'

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

load model from /kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/best_iou.pth
Evaluated 1/57
Evaluated 2/57
Evaluated 3/57
Evaluated 4/57
Evaluated 5/57
Evaluated 6/57
Evaluated 7/57
Evaluated 8/57
Evaluated 9/57
Evaluated 10/57
Evaluated 11/57
Evaluated 12/57
Evaluated 13/57
Evaluated 14/57
Evaluated 15/57
Evaluated 16/57
Evaluated 17/57
Evaluated 18/57
Evaluated 19/57
Evaluated 20/57
Evaluated 21/57
Evaluated 22/57
Evaluated 23/57
Evaluated 24/57
Evaluated 25/57
Evaluated 26/57
Evaluated 27/57
Evaluated 28/57
Evaluated 29/57
Evaluated 30/57
Evaluated 31/57
Evaluated 32/57
Evaluated 33/57
Evaluated 34/57
Evaluated 35/57
Evaluated 36/57
Evaluated 37/57
Evaluated 38/57
Evaluated 39/57
Evaluated 40/57
Evaluated 41/57
Evaluated 42/57
Evaluated 43/57
Evaluated 44/57
Evaluated 45/57
Evaluated 46/57
Evaluated 47/57
Evaluated 48/57
Evaluated 49/57
Evaluated 50/57
Evaluated 51/57
Evaluated 52/57
Evaluated 53/57
Evaluated 54/57
Evaluated 55/57
Evaluated 56/57
Evaluated 57/57

In [3]:
VALIDATION_CSV=',IoU,F1,Prec,recall,Acc\n"bg,",0.9956056857102029,0.9977480073007325,0.9965542331594534,0.9990448847883433,0.9958021545410156\nreal potato,0.9309118500011194,0.9641699818594597,0.9956533415423344,0.9347105211080015,0.9999169921875\nfake potato,0.9522338696266445,0.9754825724698661,0.9823704124390311,0.9687892549478581,0.999964599609375\nreal apple,0.7667310698808576,0.86791656541023,0.9908069402405689,0.7722246759300102,0.999189453125\nfake apple,0.6043422511191895,0.7533351644919333,0.9394433318876814,0.6288393120399316,0.9984455871582031\nreal orange,0.9262720557716387,0.9616751181814689,0.9961533565435742,0.9295970249004514,0.9999024963378906\nfake orange,0.9395745507163982,0.968796030785346,0.9631307228319249,0.9746295652135722,0.999820556640625\nreal grape,0.633692737291463,0.7757318358626515,0.9847070619059142,0.6399912253161498,0.9992276000976562\nfake grape,0.903082134230324,0.949023210711403,0.9530405084725043,0.9451387990548249,0.9996247863769532\nreal lemon,0.5693110254280307,0.725507126786873,0.6111654314946624,0.8926252805423879,0.9992063903808593\nfake lemon,0.840714331095886,0.9134156552707563,0.9981191673239364,0.8420483170425653,0.9996624755859375\nreal avocado,0.9437285770065472,0.9709997714735892,0.99296377221617,0.9500820862055487,0.9999473571777344\nfake avocado,0.6883845379525112,0.8153874257399899,0.9998147962997259,0.6884723197083357,0.9996270751953125\nreal pepper,0.9032760667551863,0.9491303105984753,0.9317314223018788,0.967295173672221,0.9996211242675781\nfake pepper,0.900210338405034,0.9474349533973953,0.9640254341856007,0.9315024586678032,0.9997538757324219\nreal plant,0.8239757843089116,0.9034442395536414,0.9232679952816458,0.8845496691412166,0.9981098937988281\nfake plant,0.8616340199240582,0.9256251271314639,0.9794564309981504,0.8774923144652547,0.9998878479003906\nreal banana,0.5656761794155748,0.7225490193781943,0.9237762879397793,0.5933722627096818,0.9989762878417969\nfake banana,0.7485354041636234,0.8561356100749404,0.8759871485204622,0.8372594489278414,0.9994825744628906\nreal onion,0.7189954833355378,0.8364804440637529,0.7517166991824868,0.9429150322088324,0.9996670532226563\nfake onion,0.9352912861678297,0.9665138489307946,0.9866498492027745,0.9472792999448778,0.9999586486816406\nreal unknown,0.9121494474626685,0.954006635209248,0.9779558138320829,0.9312976210593873,0.9999856567382812\nfake unknown,0.2286106842011801,0.3721088184324781,0.24403452223142932,0.7834117931290874,0.9977726745605469\ntotal,0.7953451899987137,0.8727224988310731,0.9114141165232076,0.8635899278575733,0.9992849200704824\ntotal(-bg),0.7862424401936461,0.8670395211733616,0.90754411122156,0.8574328843607201,0.9994432275945492\n'
VALIDATION_META={'status': 'completed', 'split': 'val', 'scope': 'full split', 'checkpoint_sha256': '89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'reference_amplitude': 1.0, 'seed': 3407, 'torch': '2.10.0+cu128', 'gpu': 'Tesla T4', 'config': {'data_root': '/kaggle/input/datasets/arnavnigamd/btp-data/public252', 'pretrained_model_path': '/kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/best_iou.pth', 'eval_split': 'val', 'transpose_image': True, 'outf': '/kaggle/working', 'name': 'epoch278_validation_audit_20260927_164048_773155', 'workers': 0, 'mask_path': '/kaggle/input/datasets/arnavnigamd/btp-code-8/BTP/mask/mask512x512.mat', 'limit': None, 'save_predictions': False, 'save_segmentation': True, 'batch_size': 1}, 'scene_count': 25, 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050']}

import io
import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['scene_count']==57
assert sorted(meta['scenes'])==SELECTION['scenes']
assert not (set(meta['scenes'])&set(VALIDATION_META['scenes']))
for f in ['checkpoint_sha256','mask_sha256','protocol_sha256']:
    assert meta[f]==VALIDATION_META[f], f'Mismatched evaluation: {f}'
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(s+'_confusion.npy')) for s in meta['scenes']]
assert np.array_equal(sum(parts),cm)
assert len(list(OUT.glob('*_preview.png')))==57
assert not list(OUT.glob('*_hsi.npy'))
train=pd.read_csv(OUT/'segmentation.csv',index_col=0)
val=pd.read_csv(io.StringIO(VALIDATION_CSV),index_col=0)
names=list(train.index[:23])
comparison=pd.DataFrame(index=['fake apple','fake avocado','fake unknown'])
for metric in ['IoU','Prec','recall']:
    comparison['selected_train_'+metric+'_percent']=100*train.loc[comparison.index,metric]
    comparison['validation_'+metric+'_percent']=100*val.loc[comparison.index,metric]
comparison.to_csv(RUN/'target_train_vs_validation.csv')
details={}
for c in [4,12,22]:
    row=cm[c];col=cm[:,c]
    details[names[c]]={'gt_pixels':int(row.sum()),'gt_predicted_as_percent':{
        names[int(i)]:float(row[i]/row.sum()*100) for i in np.argsort(row)[::-1][:5]},
        'prediction_sources_percent':{names[int(i)]:float(col[i]/col.sum()*100) for i in np.argsort(col)[::-1][:5]} if col.sum() else {}}
summary={'checkpoint_epoch':278,'train_scenes':57,'target_confusions':details,
    'scope':'Training-fit diagnostic; no new training. Selected-train versus validation comparison is descriptive, not a causal or statistically independent test.'}
(RUN/'diagnostic_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'validation_reference.csv').write_text(VALIDATION_CSV)
print(json.dumps(summary,indent=2))
display(comparison)
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z:assert z.testzip() is None
os.chdir(WORK)
print('Download before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))

{
  "checkpoint_epoch": 278,
  "train_scenes": 57,
  "target_confusions": {
    "fake apple": {
      "gt_pixels": 237011,
      "gt_predicted_as_percent": {
        "fake apple": 79.4967322191797,
        "fake unknown": 14.240267329364459,
        "fake orange": 2.159815367219243,
        "bg,": 1.8433743581521531,
        "fake pepper": 1.3568990468796807
      },
      "prediction_sources_percent": {
        "fake apple": 96.72130306001448,
        "real apple": 2.4399008228826045,
        "bg,": 0.7602552322089496,
        "fake banana": 0.04671385964281864,
        "fake unknown": 0.01642685174252963
      }
    },
    "fake avocado": {
      "gt_pixels": 54898,
      "gt_predicted_as_percent": {
        "fake avocado": 72.32503916353966,
        "fake unknown": 16.11169805821706,
        "bg,": 6.09858282633247,
        "real avocado": 3.7578782469306717,
        "fake plant": 1.2805566687311012
      },
      "prediction_sources_percent": {
        "fake avocado": 97.14949840959139,
        "real avocado": 2.752630291167115,
        "bg,": 0.09787129924149743,
        "real onion": 0.0,
        "fake unknown": 0.0
      }
    },
    "fake unknown": {
      "gt_pixels": 40026,
      "gt_predicted_as_percent": {
        "fake unknown": 89.59926048068755,
        "bg,": 4.9517813421276164,
        "fake banana": 3.6151501524009393,
        "fake pepper": 0.9993504222255534,
        "fake orange": 0.5621346125018738
      },
      "prediction_sources_percent": {
        "fake unknown": 39.10308131801033,
        "fake apple": 36.80027040582681,
        "fake avocado": 9.644111040844363,
        "real lemon": 5.187866628868003,
        "fake orange": 2.3148047190178165
      }
    }
  },
  "scope": "Training-fit diagnostic; no new training. Selected-train versus validation comparison is descriptive, not a causal or statistically independent test."
}

,selected_train_IoU_percent,validation_IoU_percent,selected_train_Prec_percent,validation_Prec_percent,selected_train_recall_percent,validation_recall_percent
fake apple,77.410661,60.434225,96.721303,93.944333,79.496732,62.883931
fake avocado,70.822111,68.838454,97.149498,99.981480,72.325039,68.847232
fake unknown,37.405217,22.861068,39.103081,24.403452,89.599260,78.341179

Download before stopping: epoch278_training_fit_20260927_170503_945447.zip 16612016 bytes

/kaggle/working/epoch278_training_fit_20260927_170503_945447.zip

In [1]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch

EXPECTED='0f81dc6ed10ab91f4f07d0c1df39b0faf6c84aebf519cbde837d803f53defa90'

relative='balanced300_to_epoch400_20260925_173543/model/last.pt'
def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
refs=[p for p in INPUTS.rglob(relative) if digest(p)==EXPECTED]
if not refs:
    dest=Path('/kaggle/working/restored_pair_epoch400')
    restored=dest/relative
    if restored.is_file() and digest(restored)==EXPECTED: refs=[restored]
    else:
        for archive in sorted(INPUTS.rglob('*.zip')):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist() and hashlib.sha256(z.read(relative)).hexdigest()==EXPECTED:
                    safe_extract(z,dest);refs=[dest/relative];break
assert refs, 'Attach balanced300_to_epoch400_20260925_173543_epoch400.zip (not only epoch350).'
CHECKPOINT=sorted(refs)[0]
REFERENCE=CHECKPOINT.parent.parent
DATA=Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable GPU.'
state=torch.load(CHECKPOINT,map_location='cpu',weights_only=True)
assert state['epoch']==state['scheduler']['last_epoch']==400
assert state['scheduler']['T_max']==500 and math.isclose(state['scheduler']['eta_min'],2.5e-7)
for k,v in dict(sampling_policy='balanced50_v1',lambda_seg=1e-4,learning_rate=1e-4,max_epoch=500,batch_size=1,workers=0,seed=3407,transpose_image=True,method='CRSDUN',input_setting='Y',input_mask='SSR').items():
    assert state['config'][k]==v,k
provenance=json.loads((REFERENCE/'continuation.json').read_text())
for f,h in provenance['source_sha256'].items(): assert digest(CODE/f)==h,f
sys.path.insert(0,str(CODE))
from training_state import identity,atomic_save
from types import SimpleNamespace
assert identity(SimpleNamespace(data_root=DATA,mask_path=CODE/'mask/mask512x512.mat'))==state['data_identity']
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
subprocess.run([sys.executable,'run_public252.py','--root',str(DATA)],cwd=CODE,check=True)
print('Verified epoch400. Next-epoch LR:',state['optimizer']['param_groups'][0]['lr'])

PASS:22-class support, aligned crops/flips, deterministic replay, no RNG consumed by index building, baseline crop branch unchanged.
{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Verified epoch400. Next-epoch LR: 9.775277405549487e-06

In [2]:
"""Derive explicit sampler-ablation seeds without altering training state."""
import copy
import torch

def equal(a,b):
    if isinstance(a,torch.Tensor): return isinstance(b,torch.Tensor) and a.dtype==b.dtype and a.shape==b.shape and torch.equal(a,b)
    if isinstance(a,dict): return isinstance(b,dict) and a.keys()==b.keys() and all(equal(a[k],b[k]) for k in a)
    if isinstance(a,(list,tuple)): return type(a)==type(b) and len(a)==len(b) and all(equal(x,y) for x,y in zip(a,b))
    return a==b

def derive(state,policy,initial_metrics):
    assert state['epoch']==400 and state['scheduler']['last_epoch']==400
    assert state['scheduler']['T_max']==500 and state['config']['sampling_policy']=='balanced50_v1'
    assert policy in ('balanced50_v1','baseline')
    seed=copy.deepcopy(state)
    seed['config']['sampling_policy']=policy
    seed['best']={'iou':initial_metrics['val_foreground_miou_all22'],'psnr':initial_metrics['val_psnr_ref1']}
    for key in state:
        if key not in ('config','best'): assert equal(state[key],seed[key]), key
    assert {k:v for k,v in seed['config'].items() if k!='sampling_policy'}=={k:v for k,v in state['config'].items() if k!='sampling_policy'}
    return seed

INITIAL={'val_foreground_miou_all22': 0.7145757598981378, 'val_psnr_ref1': 39.06867599487305}

from datetime import datetime
from IPython.display import display,FileLink
import os
if 'PAIR_RUN' not in globals():
    PAIR_RUN=Path('/kaggle/working')/('paired_sampling_epoch400_'+datetime.now().strftime('%Y%m%d_%H%M%S'))
    PAIR_RUN.mkdir(exist_ok=False)
ARMS={'balanced_control':'balanced50_v1','original_sampler':'baseline'}
seed_hashes={}
for name,policy in ARMS.items():
    dest=PAIR_RUN/'seeds'/name
    derived=derive(state,policy,INITIAL)
    if not dest.exists():
        dest.mkdir(parents=True)
        atomic_save(derived,dest/'last.pt')
        atomic_save(derived['model'],dest/'best_iou.pth')
        atomic_save(derived['model'],dest/'best_psnr.pth')
    assert equal(torch.load(dest/'last.pt',map_location='cpu',weights_only=True),derived)
    seed_hashes[name]=digest(dest/'last.pt')
    del derived
manifest={'reference_checkpoint_sha256':EXPECTED,'source_epoch':400,'end_epoch':410,
    'arms':ARMS,'seed_hashes':seed_hashes,'source_sha256':provenance['source_sha256'],
    'constants':'model, optimizer, scaler, scheduler horizon500, RNG starting state, loss1e-4, batch1,202 attempts per epoch',
    'best_weight_policy':'Both branches reset best tracking to common epoch400 weights and metrics; historical best preserved in source archive.',
    'primary_comparison':'Mean all22 foreground validation mIoU over406-410; report variability, target precision/recall and PSNR. Inspect all10 epochs; a higher best epoch alone is insufficient.',
    'scope':'Single-seed continuation sampler ablation, not a from-scratch comparison or test result.'}
(PAIR_RUN/'experiment.json').write_text(json.dumps(manifest,indent=2))
print('Experiment:',PAIR_RUN)
del state

def backup(label):
    archive=shutil.make_archive(str(PAIR_RUN)+'_'+label,'zip',root_dir=PAIR_RUN.parent,base_dir=PAIR_RUN.name)
    with zipfile.ZipFile(archive) as z:assert z.testzip() is None
    os.chdir('/kaggle/working')
    print('Download:',archive)
    display(FileLink(Path(archive).name))

def run_arm(name):
    policy=ARMS[name]
    last=PAIR_RUN/name/'model/last.pt'
    resume=last if last.is_file() else PAIR_RUN/'seeds'/name/'last.pt'
    saved=torch.load(resume,map_location='cpu',weights_only=True)
    start=int(saved['epoch']);assert 400<=start<=410
    assert saved['config']['sampling_policy']==policy
    del saved
    if start<410:
        try:
            subprocess.run([sys.executable,'-u','train.py','--data_root',str(DATA)+'/',
                '--transpose_image','--batch_size','1','--workers','0','--seed','3407',
                '--learning_rate','0.0001','--lambda_seg','0.0001','--sampling_policy',policy,
                '--max_epoch','500','--stop_after_epoch','410','--resume',str(resume),
                '--outf',str(PAIR_RUN)+'/', '--name',name],cwd=CODE,check=True)
        finally:
            backup(name)
    assert torch.load(last,map_location='cpu',weights_only=True)['epoch']==410

Experiment: /kaggle/working/paired_sampling_epoch400_20260928_170349

In [3]:
run_arm('balanced_control')
run_arm('original_sampler')

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/paired_sampling_epoch400_20260928_170349/', name='balanced_control', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/working/paired_sampling_epoch400_20260928_170349/seeds/balanced_control/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=410, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-09-28 17:05:12,992 - INFO: Resuming after epoch 400

Epoch 401/500 | Batch 10/202 | Rec 0.000614 | Seg 0.244062 | Elapsed 0.5m | ETA 9.3m
Epoch 401/500 | Batch 20/202 | Rec 0.000609 | Seg 0.250359 | Elapsed 0.7m | ETA 6.5m
Epoch 401/500 | Batch 30/202 | Rec 0.000628 | Seg 0.253616 | Elapsed 1.0m | ETA 5.5m
Epoch 401/500 | Batch 40/202 | Rec 0.000643 | Seg 0.269366 | Elapsed 1.2m | ETA 4.9m
Epoch 401/500 | Batch 50/202 | Rec 0.000627 | Seg 0.272698 | Elapsed 1.4m | ETA 4.4m
Epoch 401/500 | Batch 60/202 | Rec 0.000626 | Seg 0.279147 | Elapsed 1.7m | ETA 4.0m
Epoch 401/500 | Batch 70/202 | Rec 0.000610 | Seg 0.275896 | Elapsed 1.9m | ETA 3.6m
Epoch 401/500 | Batch 80/202 | Rec 0.000605 | Seg 0.275682 | Elapsed 2.1m | ETA 3.2m
Epoch 401/500 | Batch 90/202 | Rec 0.000641 | Seg 0.277075 | Elapsed 2.4m | ETA 2.9m
Epoch 401/500 | Batch 100/202 | Rec 0.000637 | Seg 0.276136 | Elapsed 2.6m | ETA 2.7m
Epoch 401/500 | Batch 110/202 | Rec 0.000630 | Seg 0.279288 | Elapsed 2.9m | ETA 2.4m
Epoch 401/500 | Batch 120/202 | Rec 0.000612 | Seg 0.272783 | Elapsed 3.1m | ETA 2.1m
Epoch 401/500 | Batch 130/202 | Rec 0.000605 | Seg 0.274560 | Elapsed 3.4m | ETA 1.9m
Epoch 401/500 | Batch 140/202 | Rec 0.000602 | Seg 0.274518 | Elapsed 3.6m | ETA 1.6m
Epoch 401/500 | Batch 150/202 | Rec 0.000598 | Seg 0.274621 | Elapsed 3.8m | ETA 1.3m
Epoch 401/500 | Batch 160/202 | Rec 0.000596 | Seg 0.275080 | Elapsed 4.0m | ETA 1.1m
Epoch 401/500 | Batch 170/202 | Rec 0.000593 | Seg 0.271104 | Elapsed 4.3m | ETA 0.8m
Epoch 401/500 | Batch 180/202 | Rec 0.000591 | Seg 0.273685 | Elapsed 4.5m | ETA 0.6m
Epoch 401/500 | Batch 190/202 | Rec 0.000602 | Seg 0.278695 | Elapsed 4.8m | ETA 0.3m
Epoch 401/500 | Batch 200/202 | Rec 0.000600 | Seg 0.277855 | Elapsed 5.0m | ETA 0.0m
Epoch 401/500 | Batch 202/202 | Rec 0.000600 | Seg 0.277049 | Elapsed 5.0m | ETA 0.0m

2026-09-28 17:10:14,274 - INFO: Rec loss: 0.0005998352441952868
2026-09-28 17:10:14,274 - INFO: Seg loss: 0.277048765654021
2026-09-28 17:10:14,274 - INFO: λ_rec: 1
2026-09-28 17:10:14,274 - INFO: λ_seg: 0.0001
2026-09-28 17:11:40,124 - INFO: -------------------Epoch: 401------------------------
2026-09-28 17:11:40,138 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.112274  0.974817  0.000128
2026-09-28 17:11:40,145 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995654  0.997772  0.996934  0.998712  0.995850
real potato   0.445216  0.616081  0.977821  0.449758  0.999329
fake potato   0.666460  0.799803  0.978485  0.676372  0.999753
real apple    0.710653  0.830806  0.806681  0.856524  0.998797
fake apple    0.636576  0.777889  0.993530  0.639226  0.998622
real orange   0.827968  0.905839  0.995699  0.830940  0.999772
fake orange   0.891032  0.942327  0.918488  0.967541  0.999661
real grape    0.820328  0.901247  0.958491  0.850544  0.999611
fake grape    0.896556  0.945407  0.926442  0.965268  0.999588
real lemon    0.520156  0.684299  0.539169  0.936510  0.998985
fake lemon    0.852990  0.920613  0.994477  0.857050  0.999687
real avocado  0.774427  0.872826  0.796344  0.965681  0.999739
fake avocado  0.555584  0.714263  0.999541  0.555726  0.999468
real pepper   0.761713  0.864691  0.813892  0.922368  0.998945
fake pepper   0.597012  0.747614  0.943604  0.619102  0.999004
real plant    0.871422  0.931244  0.949856  0.913443  0.998652
fake plant    0.699755  0.823310  0.776871  0.875767  0.999701
real banana   0.458169  0.628371  0.909325  0.480103  0.998724
fake banana   0.751150  0.857843  0.892083  0.826228  0.999496
real onion    0.640768  0.781010  0.692478  0.895626  0.999546
fake onion    0.926583  0.961843  0.991528  0.933978  0.999953
real unknown  0.790507  0.882948  0.847368  0.921756  0.999961
fake unknown  0.206748  0.342617  0.226366  0.704636  0.997722
total         0.708584  0.814377  0.866325  0.810559  0.999155
total(-bg)    0.695535  0.806040  0.860388  0.802007  0.999305
2026-09-28 17:11:40,778 - INFO: Epoch accounting: {'epoch': 401, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11310075, 51335, 55873, 137014, 142829, 66692, 55737, 217558, 174657, 84661, 45423, 34026, 42258, 217816, 106735, 148250, 21394, 55997, 65264, 89557, 57990, 9391, 47740], 'crops_with_class': [202, 28, 26, 38, 32, 19, 22, 36, 35, 34, 22, 11, 14, 51, 28, 19, 21, 17, 27, 32, 25, 10, 19], 'targeted_crops_by_class': [0, 2, 1, 9, 4, 6, 4, 8, 4, 5, 0, 4, 3, 6, 5, 1, 6, 4, 6, 4, 6, 1, 7], 'sampled_scene_counts': [1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 3, 1, 1, 1, 1, 0, 1, 0, 1, 2, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 2, 0, 1, 1, 1, 2, 1, 2, 0, 2, 1, 0, 0, 1, 2, 0, 1, 2, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 1, 3, 2, 1, 2, 1, 4, 2, 0, 2, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 2, 1, 0, 1, 1, 0, 0, 2, 0, 1, 0, 1, 1, 3, 2, 1, 3, 3, 1, 1, 3, 1, 0, 2, 4, 2, 1, 0, 3, 2, 0, 2, 1, 1, 1, 0, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 0, 1, 3, 1, 0, 3, 1, 1, 0, 1, 1, 2, 1, 0, 2, 1, 1, 1], 'learning_rate': 9.775277405549487e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005998352441952868, 'train_segmentation_loss': 0.277048765654021, 'val_foreground_miou_all22': 0.6955351552290234, 'val_psnr_ref1': 39.11227355957031, 'elapsed_seconds': 387.7784538269043, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 402/500 | Batch 10/202 | Rec 0.000608 | Seg 0.288321 | Elapsed 0.2m | ETA 4.2m
Epoch 402/500 | Batch 20/202 | Rec 0.000600 | Seg 0.285577 | Elapsed 0.4m | ETA 3.9m
Epoch 402/500 | Batch 30/202 | Rec 0.000602 | Seg 0.288216 | Elapsed 0.6m | ETA 3.7m
Epoch 402/500 | Batch 40/202 | Rec 0.000615 | Seg 0.300625 | Elapsed 0.9m | ETA 3.5m
Epoch 402/500 | Batch 50/202 | Rec 0.000605 | Seg 0.300487 | Elapsed 1.1m | ETA 3.3m
Epoch 402/500 | Batch 60/202 | Rec 0.000629 | Seg 0.308739 | Elapsed 1.3m | ETA 3.1m
Epoch 402/500 | Batch 70/202 | Rec 0.000636 | Seg 0.305080 | Elapsed 1.5m | ETA 2.9m
Epoch 402/500 | Batch 80/202 | Rec 0.000648 | Seg 0.310323 | Elapsed 1.7m | ETA 2.6m
Epoch 402/500 | Batch 90/202 | Rec 0.000635 | Seg 0.305045 | Elapsed 1.9m | ETA 2.4m
Epoch 402/500 | Batch 100/202 | Rec 0.000635 | Seg 0.310381 | Elapsed 2.1m | ETA 2.2m
Epoch 402/500 | Batch 110/202 | Rec 0.000631 | Seg 0.310962 | Elapsed 2.4m | ETA 2.0m
Epoch 402/500 | Batch 120/202 | Rec 0.000619 | Seg 0.301327 | Elapsed 2.6m | ETA 1.8m
Epoch 402/500 | Batch 130/202 | Rec 0.000613 | Seg 0.298719 | Elapsed 2.8m | ETA 1.5m
Epoch 402/500 | Batch 140/202 | Rec 0.000612 | Seg 0.299924 | Elapsed 3.0m | ETA 1.3m
Epoch 402/500 | Batch 150/202 | Rec 0.000616 | Seg 0.301447 | Elapsed 3.2m | ETA 1.1m
Epoch 402/500 | Batch 160/202 | Rec 0.000614 | Seg 0.298327 | Elapsed 3.5m | ETA 0.9m
Epoch 402/500 | Batch 170/202 | Rec 0.000611 | Seg 0.301382 | Elapsed 3.7m | ETA 0.7m
Epoch 402/500 | Batch 180/202 | Rec 0.000613 | Seg 0.297490 | Elapsed 3.9m | ETA 0.5m
Epoch 402/500 | Batch 190/202 | Rec 0.000610 | Seg 0.295424 | Elapsed 4.1m | ETA 0.3m
Epoch 402/500 | Batch 200/202 | Rec 0.000610 | Seg 0.295005 | Elapsed 4.3m | ETA 0.0m
Epoch 402/500 | Batch 202/202 | Rec 0.000608 | Seg 0.294165 | Elapsed 4.4m | ETA 0.0m

2026-09-28 17:16:03,044 - INFO: Rec loss: 0.0006077199852172432
2026-09-28 17:16:03,045 - INFO: Seg loss: 0.294165024035933
2026-09-28 17:16:03,045 - INFO: λ_rec: 1
2026-09-28 17:16:03,045 - INFO: λ_seg: 0.0001
2026-09-28 17:17:23,151 - INFO: -------------------Epoch: 402------------------------
2026-09-28 17:17:23,155 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.936169  0.974886  0.000134
2026-09-28 17:17:23,162 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995827  0.997859  0.997298  0.998522  0.996017
real potato   0.915337  0.955748  0.960350  0.951288  0.999895
fake potato   0.921596  0.959149  0.965612  0.952870  0.999941
real apple    0.768621  0.869126  0.960550  0.793675  0.999176
fake apple    0.555614  0.714288  0.991105  0.558398  0.998314
real orange   0.914975  0.955550  0.995981  0.918365  0.999888
fake orange   0.931348  0.964404  0.952351  0.976868  0.999794
real grape    0.812326  0.896396  0.943982  0.853468  0.999588
fake grape    0.903286  0.949136  0.935996  0.962752  0.999619
real lemon    0.613273  0.760235  0.668175  0.881849  0.999346
fake lemon    0.851961  0.920014  0.995217  0.855463  0.999686
real avocado  0.922243  0.959499  0.955100  0.964039  0.999924
fake avocado  0.451358  0.621937  0.999718  0.451415  0.999343
real pepper   0.849505  0.918580  0.877511  0.963791  0.999375
fake pepper   0.772852  0.871824  0.939246  0.813520  0.999430
real plant    0.874745  0.933138  0.958848  0.908866  0.998698
fake plant    0.746223  0.854621  0.792144  0.927914  0.999749
real banana   0.662369  0.796849  0.894145  0.718729  0.999177
fake banana   0.691364  0.817473  0.767450  0.874585  0.999282
real onion    0.648864  0.786995  0.695146  0.906941  0.999557
fake onion    0.934426  0.966052  0.981532  0.951149  0.999958
real unknown  0.573106  0.728582  0.598406  0.931298  0.999889
fake unknown  0.192101  0.322255  0.209310  0.700290  0.997518
total         0.761014  0.848683  0.871095  0.861568  0.999268
total(-bg)    0.750341  0.841902  0.865358  0.855342  0.999416
2026-09-28 17:17:23,872 - INFO: Epoch accounting: {'epoch': 402, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11205326, 40906, 43797, 102684, 140748, 70018, 76667, 187352, 234257, 59637, 63815, 40334, 21520, 229970, 134967, 177315, 27236, 109506, 96733, 78597, 38266, 9800, 48821], 'crops_with_class': [202, 24, 19, 33, 35, 24, 27, 38, 40, 29, 26, 15, 8, 56, 35, 24, 27, 31, 36, 31, 21, 11, 21], 'targeted_crops_by_class': [0, 3, 4, 3, 1, 6, 4, 8, 4, 4, 3, 3, 2, 3, 9, 6, 4, 4, 3, 3, 0, 5, 3], 'sampled_scene_counts': [1, 1, 1, 1, 1, 0, 1, 1, 3, 2, 0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 2, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 1, 1, 1, 0, 1, 0, 0, 0, 1, 2, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 1, 3, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 0, 3, 0, 3, 1, 1, 1, 0, 1, 1, 2, 2, 1, 2, 0, 3, 1, 2, 0, 0, 2, 2, 0, 4, 1, 2, 1, 4, 2, 3, 0, 2, 4, 2, 1, 2, 1, 2, 1, 3, 1, 1, 0, 3, 1, 0, 2, 2, 0, 1, 0, 2, 1, 1, 2, 0, 1, 1, 3, 0, 1, 0, 1, 2, 1, 1, 2, 2], 'learning_rate': 9.591878548899425e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006077199852172432, 'train_segmentation_loss': 0.294165024035933, 'val_foreground_miou_all22': 0.7503406736553724, 'val_psnr_ref1': 38.93616943359375, 'elapsed_seconds': 343.08640599250793, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 403/500 | Batch 10/202 | Rec 0.000442 | Seg 0.221355 | Elapsed 0.2m | ETA 4.3m
Epoch 403/500 | Batch 20/202 | Rec 0.000454 | Seg 0.221102 | Elapsed 0.4m | ETA 4.0m
Epoch 403/500 | Batch 30/202 | Rec 0.000506 | Seg 0.271619 | Elapsed 0.6m | ETA 3.6m
Epoch 403/500 | Batch 40/202 | Rec 0.000547 | Seg 0.283999 | Elapsed 0.8m | ETA 3.4m
Epoch 403/500 | Batch 50/202 | Rec 0.000557 | Seg 0.280665 | Elapsed 1.0m | ETA 3.2m
Epoch 403/500 | Batch 60/202 | Rec 0.000602 | Seg 0.301394 | Elapsed 1.3m | ETA 3.0m
Epoch 403/500 | Batch 70/202 | Rec 0.000598 | Seg 0.294738 | Elapsed 1.5m | ETA 2.8m
Epoch 403/500 | Batch 80/202 | Rec 0.000581 | Seg 0.288946 | Elapsed 1.7m | ETA 2.6m
Epoch 403/500 | Batch 90/202 | Rec 0.000577 | Seg 0.287132 | Elapsed 1.9m | ETA 2.4m
Epoch 403/500 | Batch 100/202 | Rec 0.000579 | Seg 0.288427 | Elapsed 2.1m | ETA 2.2m
Epoch 403/500 | Batch 110/202 | Rec 0.000575 | Seg 0.286687 | Elapsed 2.3m | ETA 1.9m
Epoch 403/500 | Batch 120/202 | Rec 0.000589 | Seg 0.293858 | Elapsed 2.5m | ETA 1.7m
Epoch 403/500 | Batch 130/202 | Rec 0.000591 | Seg 0.292340 | Elapsed 2.7m | ETA 1.5m
Epoch 403/500 | Batch 140/202 | Rec 0.000594 | Seg 0.291705 | Elapsed 2.9m | ETA 1.3m
Epoch 403/500 | Batch 150/202 | Rec 0.000590 | Seg 0.290316 | Elapsed 3.1m | ETA 1.1m
Epoch 403/500 | Batch 160/202 | Rec 0.000593 | Seg 0.292575 | Elapsed 3.4m | ETA 0.9m
Epoch 403/500 | Batch 170/202 | Rec 0.000599 | Seg 0.291951 | Elapsed 3.6m | ETA 0.7m
Epoch 403/500 | Batch 180/202 | Rec 0.000598 | Seg 0.292376 | Elapsed 3.8m | ETA 0.5m
Epoch 403/500 | Batch 190/202 | Rec 0.000591 | Seg 0.289104 | Elapsed 4.0m | ETA 0.3m
Epoch 403/500 | Batch 200/202 | Rec 0.000587 | Seg 0.287869 | Elapsed 4.2m | ETA 0.0m
Epoch 403/500 | Batch 202/202 | Rec 0.000588 | Seg 0.287480 | Elapsed 4.2m | ETA 0.0m

2026-09-28 17:21:38,397 - INFO: Rec loss: 0.000587563303306164
2026-09-28 17:21:38,397 - INFO: Seg loss: 0.2874801268819535
2026-09-28 17:21:38,397 - INFO: λ_rec: 1
2026-09-28 17:21:38,397 - INFO: λ_seg: 0.0001
2026-09-28 17:22:56,787 - INFO: -------------------Epoch: 403------------------------
2026-09-28 17:22:56,790 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.113148  0.975126  0.000128
2026-09-28 17:22:56,797 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995561  0.997725  0.996799  0.998754  0.995760
real potato   0.346468  0.514594  1.000000  0.346468  0.999218
fake potato   0.662776  0.797144  0.992509  0.666108  0.999753
real apple    0.665238  0.798921  0.732427  0.878815  0.998474
fake apple    0.645259  0.784338  0.983962  0.652118  0.998646
real orange   0.824334  0.903660  0.990612  0.830824  0.999767
fake orange   0.895112  0.944604  0.921230  0.969300  0.999675
real grape    0.826547  0.904988  0.965766  0.851495  0.999627
fake grape    0.883488  0.938090  0.910843  0.967125  0.999528
real lemon    0.455669  0.626017  0.473537  0.923526  0.998703
fake lemon    0.860640  0.925052  0.994772  0.864551  0.999704
real avocado  0.820039  0.901073  0.847311  0.962233  0.999804
fake avocado  0.606273  0.754835  0.999790  0.606350  0.999529
real pepper   0.791990  0.883873  0.834445  0.939638  0.999097
fake pepper   0.616974  0.763074  0.948189  0.638499  0.999055
real plant    0.866217  0.928263  0.960128  0.898539  0.998612
fake plant    0.736475  0.848192  0.845655  0.850844  0.999758
real banana   0.392970  0.564176  0.890092  0.413011  0.998566
fake banana   0.706780  0.828153  0.822947  0.833527  0.999364
real onion    0.496469  0.663471  0.752033  0.593650  0.999456
fake onion    0.886752  0.939927  0.993534  0.891898  0.999928
real unknown  0.909351  0.952474  1.000000  0.909351  0.999986
fake unknown  0.215947  0.355155  0.235800  0.719486  0.997799
total         0.700319  0.805122  0.873582  0.791570  0.999122
total(-bg)    0.686899  0.796367  0.867981  0.782152  0.999275
2026-09-28 17:22:57,483 - INFO: Epoch accounting: {'epoch': 403, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11245902, 41406, 46660, 139858, 174644, 69496, 62252, 155228, 183473, 77076, 61718, 53446, 37798, 231601, 123940, 116520, 23432, 90122, 82395, 94468, 61972, 10270, 54595], 'crops_with_class': [202, 29, 23, 35, 39, 21, 20, 30, 32, 35, 30, 17, 14, 57, 27, 19, 26, 26, 36, 43, 29, 11, 22], 'targeted_crops_by_class': [0, 4, 4, 3, 5, 5, 1, 4, 4, 2, 2, 4, 5, 4, 2, 4, 6, 4, 5, 4, 6, 7, 4], 'sampled_scene_counts': [3, 2, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 0, 1, 1, 3, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 0, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 0, 0, 1, 3, 4, 2, 1, 0, 2, 4, 2, 1, 1, 1, 3, 2, 3, 2, 1, 0, 1, 2, 2, 2, 1, 1, 1, 0, 3, 2, 2, 1, 1, 1, 2, 2, 0, 0, 3, 4, 1, 3, 1, 0, 4, 1, 1, 1, 0, 0, 1, 0, 2, 1, 1, 1], 'learning_rate': 9.410079870480438e-06, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000587563303306164, 'train_segmentation_loss': 0.2874801268819535, 'val_foreground_miou_all22': 0.6868986157915092, 'val_psnr_ref1': 39.1131477355957, 'elapsed_seconds': 333.6034519672394, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 404/500 | Batch 10/202 | Rec 0.000584 | Seg 0.294690 | Elapsed 0.2m | ETA 3.9m
Epoch 404/500 | Batch 20/202 | Rec 0.000652 | Seg 0.290461 | Elapsed 0.4m | ETA 3.7m
Epoch 404/500 | Batch 30/202 | Rec 0.000640 | Seg 0.305394 | Elapsed 0.6m | ETA 3.5m
Epoch 404/500 | Batch 40/202 | Rec 0.000654 | Seg 0.318561 | Elapsed 0.8m | ETA 3.3m
Epoch 404/500 | Batch 50/202 | Rec 0.000648 | Seg 0.312045 | Elapsed 1.0m | ETA 3.1m
Epoch 404/500 | Batch 60/202 | Rec 0.000617 | Seg 0.305489 | Elapsed 1.2m | ETA 2.9m
Epoch 404/500 | Batch 70/202 | Rec 0.000647 | Seg 0.322284 | Elapsed 1.4m | ETA 2.7m
Epoch 404/500 | Batch 80/202 | Rec 0.000636 | Seg 0.319195 | Elapsed 1.6m | ETA 2.5m
Epoch 404/500 | Batch 90/202 | Rec 0.000624 | Seg 0.309193 | Elapsed 1.8m | ETA 2.3m
Epoch 404/500 | Batch 100/202 | Rec 0.000655 | Seg 0.307922 | Elapsed 2.0m | ETA 2.1m
Epoch 404/500 | Batch 110/202 | Rec 0.000656 | Seg 0.309513 | Elapsed 2.2m | ETA 1.9m
Epoch 404/500 | Batch 120/202 | Rec 0.000647 | Seg 0.306360 | Elapsed 2.5m | ETA 1.7m
Epoch 404/500 | Batch 130/202 | Rec 0.000636 | Seg 0.302677 | Elapsed 2.7m | ETA 1.5m
Epoch 404/500 | Batch 140/202 | Rec 0.000622 | Seg 0.298282 | Elapsed 2.9m | ETA 1.3m
Epoch 404/500 | Batch 150/202 | Rec 0.000616 | Seg 0.292646 | Elapsed 3.1m | ETA 1.1m
Epoch 404/500 | Batch 160/202 | Rec 0.000619 | Seg 0.290430 | Elapsed 3.3m | ETA 0.9m
Epoch 404/500 | Batch 170/202 | Rec 0.000611 | Seg 0.288445 | Elapsed 3.5m | ETA 0.7m
Epoch 404/500 | Batch 180/202 | Rec 0.000607 | Seg 0.288415 | Elapsed 3.7m | ETA 0.5m
Epoch 404/500 | Batch 190/202 | Rec 0.000602 | Seg 0.286907 | Elapsed 3.9m | ETA 0.2m
Epoch 404/500 | Batch 200/202 | Rec 0.000596 | Seg 0.285448 | Elapsed 4.1m | ETA 0.0m
Epoch 404/500 | Batch 202/202 | Rec 0.000593 | Seg 0.284937 | Elapsed 4.2m | ETA 0.0m

2026-09-28 17:27:06,866 - INFO: Rec loss: 0.0005934817556840469
2026-09-28 17:27:06,866 - INFO: Seg loss: 0.2849373141543405
2026-09-28 17:27:06,866 - INFO: λ_rec: 1
2026-09-28 17:27:06,866 - INFO: λ_seg: 0.0001
2026-09-28 17:28:25,747 - INFO: -------------------Epoch: 404------------------------
2026-09-28 17:28:25,751 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  38.920008  0.97471  0.000134
2026-09-28 17:28:25,759 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995758  0.997824  0.997125  0.998624  0.995950
real potato   0.507756  0.673481  0.978848  0.513389  0.999404
fake potato   0.767390  0.868338  0.970505  0.785714  0.999827
real apple    0.726840  0.841765  0.827396  0.856745  0.998889
fake apple    0.658071  0.793731  0.966367  0.673497  0.998679
real orange   0.897649  0.946014  0.994890  0.901806  0.999865
fake orange   0.924252  0.960585  0.941369  0.980706  0.999770
real grape    0.793981  0.885112  0.970368  0.813710  0.999559
fake grape    0.902501  0.948702  0.930683  0.967537  0.999613
real lemon    0.515508  0.680264  0.537005  0.927941  0.998975
fake lemon    0.855543  0.922099  0.994741  0.859430  0.999693
real avocado  0.883076  0.937858  0.910229  0.967323  0.999881
fake avocado  0.791385  0.883496  0.999195  0.791890  0.999750
real pepper   0.825356  0.904273  0.862645  0.950234  0.999265
fake pepper   0.718756  0.836318  0.957254  0.742590  0.999307
real plant    0.862196  0.925949  0.950715  0.902535  0.998557
fake plant    0.862910  0.926361  0.930894  0.921971  0.999883
real banana   0.479046  0.647730  0.887602  0.509982  0.998754
fake banana   0.707162  0.828415  0.824114  0.832863  0.999366
real onion    0.645457  0.784483  0.692616  0.904577  0.999551
fake onion    0.922561  0.959671  0.990731  0.930592  0.999951
real unknown  0.813433  0.897069  0.861282  0.936069  0.999966
fake unknown  0.245537  0.394228  0.268750  0.739768  0.998085
total         0.752266  0.845381  0.880231  0.843891  0.999241
total(-bg)    0.741198  0.838452  0.874918  0.836858  0.999390
2026-09-28 17:28:26,293 - INFO: Epoch accounting: {'epoch': 404, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11245621, 38144, 50853, 113329, 152227, 83440, 87801, 160365, 205956, 74036, 60685, 52543, 46926, 243704, 141040, 152742, 17669, 70736, 68057, 62448, 49226, 6844, 53880], 'crops_with_class': [202, 21, 24, 32, 43, 29, 32, 33, 36, 35, 28, 15, 19, 56, 31, 20, 16, 20, 29, 27, 22, 10, 24], 'targeted_crops_by_class': [0, 2, 2, 4, 7, 5, 8, 6, 3, 1, 4, 5, 9, 5, 4, 8, 2, 3, 5, 1, 2, 5, 3], 'sampled_scene_counts': [0, 1, 2, 1, 0, 2, 2, 1, 2, 3, 0, 1, 2, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 2, 1, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 2, 1, 0, 2, 1, 2, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 2, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 1, 0, 1, 2, 1, 3, 3, 1, 0, 1, 0, 1, 3, 0, 2, 1, 1, 1, 0, 3, 0, 1, 1, 1, 3, 3, 0, 2, 5, 3, 0, 0, 4, 2, 1, 1, 2, 2, 0, 0, 1, 1, 1, 2, 1, 3, 3, 1, 0, 2, 0, 1, 0, 0, 2, 1, 1, 1, 1, 2, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 1, 1, 2, 1, 0, 1, 1, 3, 1, 3, 1, 1], 'learning_rate': 9.229888547393062e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005934817556840469, 'train_segmentation_loss': 0.2849373141543405, 'val_foreground_miou_all22': 0.7411983703087697, 'val_psnr_ref1': 38.920008239746096, 'elapsed_seconds': 328.8022608757019, 'peak_cuda_allocated_gib': 7.509555816650391}

Epoch 405/500 | Batch 10/202 | Rec 0.000560 | Seg 0.294316 | Elapsed 0.2m | ETA 3.9m
Epoch 405/500 | Batch 20/202 | Rec 0.000592 | Seg 0.307858 | Elapsed 0.4m | ETA 3.7m
Epoch 405/500 | Batch 30/202 | Rec 0.000610 | Seg 0.319006 | Elapsed 0.6m | ETA 3.4m
Epoch 405/500 | Batch 40/202 | Rec 0.000610 | Seg 0.322969 | Elapsed 0.8m | ETA 3.3m
Epoch 405/500 | Batch 50/202 | Rec 0.000634 | Seg 0.329651 | Elapsed 1.0m | ETA 3.1m
Epoch 405/500 | Batch 60/202 | Rec 0.000622 | Seg 0.321070 | Elapsed 1.2m | ETA 2.9m
Epoch 405/500 | Batch 70/202 | Rec 0.000638 | Seg 0.329881 | Elapsed 1.4m | ETA 2.7m
Epoch 405/500 | Batch 80/202 | Rec 0.000621 | Seg 0.322827 | Elapsed 1.6m | ETA 2.5m
Epoch 405/500 | Batch 90/202 | Rec 0.000618 | Seg 0.323106 | Elapsed 1.8m | ETA 2.3m
Epoch 405/500 | Batch 100/202 | Rec 0.000634 | Seg 0.313165 | Elapsed 2.0m | ETA 2.1m
Epoch 405/500 | Batch 110/202 | Rec 0.000625 | Seg 0.308104 | Elapsed 2.2m | ETA 1.9m
Epoch 405/500 | Batch 120/202 | Rec 0.000632 | Seg 0.314154 | Elapsed 2.4m | ETA 1.7m
Epoch 405/500 | Batch 130/202 | Rec 0.000623 | Seg 0.311875 | Elapsed 2.7m | ETA 1.5m
Epoch 405/500 | Batch 140/202 | Rec 0.000618 | Seg 0.308945 | Elapsed 2.9m | ETA 1.3m
Epoch 405/500 | Batch 150/202 | Rec 0.000616 | Seg 0.304519 | Elapsed 3.1m | ETA 1.1m
Epoch 405/500 | Batch 160/202 | Rec 0.000619 | Seg 0.307069 | Elapsed 3.3m | ETA 0.9m
Epoch 405/500 | Batch 170/202 | Rec 0.000621 | Seg 0.305484 | Elapsed 3.5m | ETA 0.7m
Epoch 405/500 | Batch 180/202 | Rec 0.000639 | Seg 0.309689 | Elapsed 3.7m | ETA 0.4m
Epoch 405/500 | Batch 190/202 | Rec 0.000640 | Seg 0.312079 | Elapsed 3.9m | ETA 0.2m
Epoch 405/500 | Batch 200/202 | Rec 0.000636 | Seg 0.311680 | Elapsed 4.1m | ETA 0.0m
Epoch 405/500 | Batch 202/202 | Rec 0.000634 | Seg 0.310370 | Elapsed 4.1m | ETA 0.0m

2026-09-28 17:32:33,992 - INFO: Rec loss: 0.0006344394816983592
2026-09-28 17:32:33,992 - INFO: Seg loss: 0.3103699014697335
2026-09-28 17:32:33,992 - INFO: λ_rec: 1
2026-09-28 17:32:33,992 - INFO: λ_seg: 0.0001
2026-09-28 17:33:52,203 - INFO: -------------------Epoch: 405------------------------
2026-09-28 17:33:52,207 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.780661  0.974456  0.000138
2026-09-28 17:33:52,214 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995808  0.997850  0.997765  0.998034  0.996001
real potato   0.391232  0.562385  0.998374  0.391482  0.999271
fake potato   0.658045  0.793711  0.959608  0.676791  0.999744
real apple    0.681023  0.810199  0.774876  0.849005  0.998628
fake apple    0.624692  0.768950  0.949030  0.646379  0.998534
real orange   0.937118  0.967488  0.996198  0.940482  0.999917
fake orange   0.946911  0.972682  0.959076  0.986782  0.999842
real grape    0.774607  0.872940  0.967295  0.795440  0.999517
fake grape    0.867425  0.928956  0.881560  0.981850  0.999445
real lemon    0.471591  0.640881  0.495117  0.908465  0.998804
fake lemon    0.858773  0.923972  0.994185  0.863109  0.999700
real avocado  0.893100  0.943482  0.917339  0.971264  0.999892
fake avocado  0.730019  0.843895  0.999476  0.730298  0.999677
real pepper   0.814993  0.898017  0.841817  0.962373  0.999201
fake pepper   0.703847  0.826137  0.966469  0.721465  0.999276
real plant    0.872456  0.931834  0.939873  0.924030  0.998649
fake plant    0.843353  0.914971  0.890138  0.941334  0.999861
real banana   0.446440  0.617248  0.850316  0.484517  0.998650
fake banana   0.680028  0.809494  0.755115  0.872429  0.999245
real onion    0.636294  0.777676  0.721636  0.843270  0.999565
fake onion    0.914463  0.955270  0.984103  0.928174  0.999945
real unknown  0.912558  0.954230  0.973214  0.936069  0.999986
fake unknown  0.233316  0.378319  0.248606  0.791380  0.997809
total         0.734265  0.830026  0.872225  0.832366  0.999181
total(-bg)    0.722376  0.822397  0.866519  0.824836  0.999325
2026-09-28 17:33:52,742 - INFO: Epoch accounting: {'epoch': 405, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11067077, 49322, 64634, 172481, 163370, 106306, 97295, 168004, 208017, 114362, 74471, 59942, 24698, 228626, 138724, 178873, 33024, 66795, 59102, 61170, 51076, 7828, 43075], 'crops_with_class': [202, 27, 27, 45, 40, 35, 38, 33, 40, 46, 31, 18, 11, 56, 31, 21, 21, 18, 26, 32, 22, 10, 18], 'targeted_crops_by_class': [0, 6, 4, 3, 3, 6, 5, 4, 8, 9, 5, 6, 3, 0, 7, 3, 7, 1, 6, 2, 3, 4, 5], 'sampled_scene_counts': [0, 1, 1, 1, 2, 1, 0, 0, 2, 2, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 3, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 0, 0, 3, 3, 4, 2, 4, 4, 3, 1, 2, 2, 1, 1, 2, 2, 2, 2, 3, 1, 2, 2, 0, 1, 0, 0, 0, 4, 0, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 0, 2, 4, 0, 2, 0, 1, 2, 1, 1, 2, 1, 1, 0, 1, 0, 2, 1, 0, 1, 2, 2, 0, 2, 3, 3, 0, 1, 1, 2, 1, 0, 3, 1, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1], 'learning_rate': 9.051311693282169e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006344394816983592, 'train_segmentation_loss': 0.3103699014697335, 'val_foreground_miou_all22': 0.722376498367968, 'val_psnr_ref1': 38.78066055297852, 'elapsed_seconds': 326.44093441963196, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 406/500 | Batch 10/202 | Rec 0.000626 | Seg 0.354140 | Elapsed 0.2m | ETA 3.9m
Epoch 406/500 | Batch 20/202 | Rec 0.000569 | Seg 0.312037 | Elapsed 0.4m | ETA 3.7m
Epoch 406/500 | Batch 30/202 | Rec 0.000569 | Seg 0.307904 | Elapsed 0.6m | ETA 3.5m
Epoch 406/500 | Batch 40/202 | Rec 0.000595 | Seg 0.303492 | Elapsed 0.8m | ETA 3.3m
Epoch 406/500 | Batch 50/202 | Rec 0.000568 | Seg 0.300498 | Elapsed 1.0m | ETA 3.1m
Epoch 406/500 | Batch 60/202 | Rec 0.000575 | Seg 0.290559 | Elapsed 1.2m | ETA 2.9m
Epoch 406/500 | Batch 70/202 | Rec 0.000562 | Seg 0.287606 | Elapsed 1.4m | ETA 2.7m
Epoch 406/500 | Batch 80/202 | Rec 0.000570 | Seg 0.278456 | Elapsed 1.6m | ETA 2.5m
Epoch 406/500 | Batch 90/202 | Rec 0.000577 | Seg 0.278507 | Elapsed 1.8m | ETA 2.3m
Epoch 406/500 | Batch 100/202 | Rec 0.000579 | Seg 0.280414 | Elapsed 2.0m | ETA 2.1m
Epoch 406/500 | Batch 110/202 | Rec 0.000582 | Seg 0.281332 | Elapsed 2.2m | ETA 1.9m
Epoch 406/500 | Batch 120/202 | Rec 0.000587 | Seg 0.288282 | Elapsed 2.4m | ETA 1.7m
Epoch 406/500 | Batch 130/202 | Rec 0.000585 | Seg 0.291555 | Elapsed 2.6m | ETA 1.5m
Epoch 406/500 | Batch 140/202 | Rec 0.000586 | Seg 0.290218 | Elapsed 2.8m | ETA 1.3m
Epoch 406/500 | Batch 150/202 | Rec 0.000585 | Seg 0.290915 | Elapsed 3.0m | ETA 1.1m
Epoch 406/500 | Batch 160/202 | Rec 0.000584 | Seg 0.291243 | Elapsed 3.3m | ETA 0.9m
Epoch 406/500 | Batch 170/202 | Rec 0.000582 | Seg 0.289503 | Elapsed 3.5m | ETA 0.7m
Epoch 406/500 | Batch 180/202 | Rec 0.000582 | Seg 0.291438 | Elapsed 3.7m | ETA 0.4m
Epoch 406/500 | Batch 190/202 | Rec 0.000583 | Seg 0.289633 | Elapsed 3.9m | ETA 0.2m
Epoch 406/500 | Batch 200/202 | Rec 0.000581 | Seg 0.286012 | Elapsed 4.1m | ETA 0.0m
Epoch 406/500 | Batch 202/202 | Rec 0.000584 | Seg 0.287838 | Elapsed 4.1m | ETA 0.0m

2026-09-28 17:37:58,935 - INFO: Rec loss: 0.0005837097590544842
2026-09-28 17:37:58,935 - INFO: Seg loss: 0.2878380931987621
2026-09-28 17:37:58,935 - INFO: λ_rec: 1
2026-09-28 17:37:58,936 - INFO: λ_seg: 0.0001
2026-09-28 17:39:17,189 - INFO: -------------------Epoch: 406------------------------
2026-09-28 17:39:17,192 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  39.08399  0.974982  0.000129
2026-09-28 17:39:17,199 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995926  0.997909  0.997675  0.998243  0.996113
real potato   0.924224  0.960570  0.942128  0.979852  0.999904
fake potato   0.960553  0.979830  0.970419  0.989527  0.999970
real apple    0.743187  0.852627  0.957821  0.768333  0.999084
fake apple    0.549100  0.708882  0.985960  0.553427  0.998284
real orange   0.949528  0.974060  0.994929  0.954145  0.999933
fake orange   0.948604  0.973574  0.955369  0.992591  0.999846
real grape    0.771096  0.870706  0.936790  0.813418  0.999496
fake grape    0.907614  0.951520  0.929237  0.975003  0.999633
real lemon    0.757794  0.862160  0.793710  0.943651  0.999646
fake lemon    0.862332  0.926028  0.996840  0.864695  0.999708
real avocado  0.948981  0.973773  0.976395  0.971264  0.999951
fake avocado  0.642912  0.782602  0.999604  0.643076  0.999573
real pepper   0.863427  0.926659  0.885582  0.971842  0.999438
fake pepper   0.786450  0.880412  0.949023  0.821138  0.999469
real plant    0.868219  0.929412  0.946856  0.912695  0.998614
fake plant    0.776938  0.874418  0.813325  0.945552  0.999784
real banana   0.730068  0.843926  0.883598  0.807755  0.999329
fake banana   0.730674  0.844331  0.810497  0.881221  0.999402
real onion    0.589517  0.741709  0.600943  0.968755  0.999391
fake onion    0.941651  0.969899  0.980005  0.960097  0.999962
real unknown  0.495318  0.662446  0.506042  0.958969  0.999844
fake unknown  0.220616  0.361446  0.238246  0.748823  0.997771
total         0.781075  0.862996  0.871782  0.888003  0.999311
total(-bg)    0.771309  0.856863  0.866060  0.882992  0.999456
2026-09-28 17:39:17,896 - INFO: Epoch accounting: {'epoch': 406, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11227678, 44484, 49283, 115909, 177626, 102955, 84722, 174554, 254959, 82047, 74853, 53003, 30970, 172527, 99774, 175751, 26190, 79702, 57568, 73896, 41416, 7520, 30885], 'crops_with_class': [202, 25, 22, 34, 39, 31, 33, 35, 44, 36, 33, 18, 12, 48, 26, 25, 26, 24, 27, 30, 21, 9, 15], 'targeted_crops_by_class': [0, 6, 1, 3, 3, 4, 5, 7, 10, 6, 10, 5, 1, 4, 6, 5, 9, 2, 6, 7, 5, 3, 2], 'sampled_scene_counts': [0, 0, 1, 0, 2, 2, 0, 1, 2, 2, 0, 0, 1, 3, 0, 1, 1, 1, 1, 0, 0, 3, 0, 1, 1, 0, 1, 0, 2, 2, 1, 3, 0, 0, 0, 1, 2, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 2, 2, 2, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 2, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 2, 1, 3, 3, 2, 3, 2, 3, 2, 2, 1, 2, 1, 2, 3, 1, 2, 0, 1, 1, 1, 1, 3, 2, 1, 2, 0, 2, 2, 2, 1, 3, 1, 0, 2, 0, 0, 2, 2, 2, 1, 1, 3, 2, 0, 0, 2, 1, 4, 0, 2, 1, 2, 0, 1, 1, 3, 1, 0, 1, 0, 1, 1, 0, 1, 4, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 3], 'learning_rate': 8.874356358056223e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005837097590544842, 'train_segmentation_loss': 0.2878380931987621, 'val_foreground_miou_all22': 0.7713092263421295, 'val_psnr_ref1': 39.083990478515624, 'elapsed_seconds': 325.1465721130371, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 407/500 | Batch 10/202 | Rec 0.000698 | Seg 0.311735 | Elapsed 0.2m | ETA 3.7m
Epoch 407/500 | Batch 20/202 | Rec 0.000622 | Seg 0.274832 | Elapsed 0.4m | ETA 3.7m
Epoch 407/500 | Batch 30/202 | Rec 0.000551 | Seg 0.253639 | Elapsed 0.6m | ETA 3.5m
Epoch 407/500 | Batch 40/202 | Rec 0.000545 | Seg 0.247615 | Elapsed 0.8m | ETA 3.3m
Epoch 407/500 | Batch 50/202 | Rec 0.000553 | Seg 0.256959 | Elapsed 1.0m | ETA 3.1m
Epoch 407/500 | Batch 60/202 | Rec 0.000541 | Seg 0.251085 | Elapsed 1.2m | ETA 2.9m
Epoch 407/500 | Batch 70/202 | Rec 0.000555 | Seg 0.256287 | Elapsed 1.4m | ETA 2.7m
Epoch 407/500 | Batch 80/202 | Rec 0.000544 | Seg 0.247419 | Elapsed 1.6m | ETA 2.5m
Epoch 407/500 | Batch 90/202 | Rec 0.000541 | Seg 0.250558 | Elapsed 1.8m | ETA 2.3m
Epoch 407/500 | Batch 100/202 | Rec 0.000550 | Seg 0.248962 | Elapsed 2.0m | ETA 2.1m
Epoch 407/500 | Batch 110/202 | Rec 0.000548 | Seg 0.249275 | Elapsed 2.2m | ETA 1.9m
Epoch 407/500 | Batch 120/202 | Rec 0.000549 | Seg 0.255709 | Elapsed 2.4m | ETA 1.7m
Epoch 407/500 | Batch 130/202 | Rec 0.000549 | Seg 0.261295 | Elapsed 2.7m | ETA 1.5m
Epoch 407/500 | Batch 140/202 | Rec 0.000559 | Seg 0.266203 | Elapsed 2.8m | ETA 1.3m
Epoch 407/500 | Batch 150/202 | Rec 0.000561 | Seg 0.265438 | Elapsed 3.1m | ETA 1.1m
Epoch 407/500 | Batch 160/202 | Rec 0.000568 | Seg 0.262964 | Elapsed 3.3m | ETA 0.9m
Epoch 407/500 | Batch 170/202 | Rec 0.000571 | Seg 0.263454 | Elapsed 3.5m | ETA 0.7m
Epoch 407/500 | Batch 180/202 | Rec 0.000577 | Seg 0.263498 | Elapsed 3.7m | ETA 0.4m
Epoch 407/500 | Batch 190/202 | Rec 0.000582 | Seg 0.265943 | Elapsed 3.9m | ETA 0.2m
Epoch 407/500 | Batch 200/202 | Rec 0.000578 | Seg 0.264662 | Elapsed 4.1m | ETA 0.0m
Epoch 407/500 | Batch 202/202 | Rec 0.000581 | Seg 0.265063 | Elapsed 4.1m | ETA 0.0m

2026-09-28 17:43:24,837 - INFO: Rec loss: 0.0005808909522198915
2026-09-28 17:43:24,837 - INFO: Seg loss: 0.26506279504830293
2026-09-28 17:43:24,837 - INFO: λ_rec: 1
2026-09-28 17:43:24,837 - INFO: λ_seg: 0.0001
2026-09-28 17:44:43,673 - INFO: -------------------Epoch: 407------------------------
2026-09-28 17:44:43,677 - INFO:
Validation stats:
       PSNR      SSIM      MSE
0  39.04545  0.974976  0.00013
2026-09-28 17:44:43,684 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995693  0.997792  0.997063  0.998622  0.995888
real potato   0.868382  0.929505  0.886677  0.976792  0.999823
fake potato   0.965496  0.982395  0.980192  0.984709  0.999974
real apple    0.696284  0.820903  0.969463  0.711897  0.998929
fake apple    0.533078  0.695390  0.994289  0.534715  0.998232
real orange   0.868203  0.929403  0.994195  0.872626  0.999825
fake orange   0.910829  0.953284  0.935059  0.972338  0.999727
real grape    0.704406  0.826521  0.879868  0.779361  0.999317
fake grape    0.909759  0.952698  0.931712  0.974756  0.999642
real lemon    0.841537  0.913901  0.939049  0.890158  0.999803
fake lemon    0.739315  0.850073  0.996799  0.741075  0.999447
real avocado  0.956864  0.977907  0.998802  0.957964  0.999960
fake avocado  0.624761  0.769002  0.999796  0.624841  0.999551
real pepper   0.821978  0.902242  0.841687  0.972301  0.999230
fake pepper   0.698104  0.822167  0.932241  0.735420  0.999242
real plant    0.855560  0.922108  0.948361  0.897364  0.998485
fake plant    0.757962  0.862269  0.799836  0.935391  0.999762
real banana   0.813672  0.897215  0.895716  0.898818  0.999538
fake banana   0.642434  0.782245  0.715583  0.862724  0.999117
real onion    0.608036  0.756200  0.620268  0.968586  0.999436
fake onion    0.937529  0.967707  0.966474  0.969045  0.999959
real unknown  0.517021  0.681580  0.538803  0.927481  0.999861
fake unknown  0.187663  0.315982  0.212928  0.612640  0.997766
total         0.758894  0.848195  0.868472  0.860853  0.999240
total(-bg)    0.748131  0.841395  0.862627  0.854591  0.999392
2026-09-28 17:44:44,206 - INFO: Epoch accounting: {'epoch': 407, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11387492, 38151, 57744, 83353, 95173, 75066, 60571, 162525, 215282, 72287, 64792, 36476, 41205, 210098, 115573, 155858, 29085, 70125, 66576, 86325, 66982, 11943, 35590], 'crops_with_class': [202, 30, 25, 25, 23, 24, 22, 27, 35, 29, 29, 13, 15, 50, 29, 23, 21, 22, 29, 37, 31, 16, 15], 'targeted_crops_by_class': [0, 4, 4, 3, 2, 6, 3, 6, 6, 8, 3, 5, 5, 6, 6, 4, 6, 4, 3, 8, 8, 2, 3], 'sampled_scene_counts': [2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 3, 1, 2, 1, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 2, 3, 2, 0, 2, 0, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 2, 1, 2, 1, 1, 0, 3, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 2, 1, 2, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1, 2, 0, 4, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 1, 3, 1, 1, 2, 4, 3, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 6, 1, 0, 1, 1, 1, 0, 0, 0, 0, 3, 1, 1, 1, 2, 3, 1, 1, 1, 0, 1, 1, 0, 1, 0, 3, 0, 2, 0, 3, 0, 2, 1, 1, 1, 1, 0, 3, 1, 4, 3, 1, 2, 0, 1, 1, 0, 2, 0, 0, 2, 2, 2, 1, 3, 2, 2], 'learning_rate': 8.699029527608837e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005808909522198915, 'train_segmentation_loss': 0.26506279504830293, 'val_foreground_miou_all22': 0.7481305867807477, 'val_psnr_ref1': 39.04544952392578, 'elapsed_seconds': 326.3017432689667, 'peak_cuda_allocated_gib': 7.511142730712891}

Epoch 408/500 | Batch 10/202 | Rec 0.000741 | Seg 0.334779 | Elapsed 0.2m | ETA 3.9m
Epoch 408/500 | Batch 20/202 | Rec 0.000657 | Seg 0.305652 | Elapsed 0.4m | ETA 3.7m
Epoch 408/500 | Batch 30/202 | Rec 0.000658 | Seg 0.306203 | Elapsed 0.6m | ETA 3.5m
Epoch 408/500 | Batch 40/202 | Rec 0.000652 | Seg 0.310538 | Elapsed 0.8m | ETA 3.3m
Epoch 408/500 | Batch 50/202 | Rec 0.000625 | Seg 0.302531 | Elapsed 1.0m | ETA 3.1m
Epoch 408/500 | Batch 60/202 | Rec 0.000622 | Seg 0.296283 | Elapsed 1.2m | ETA 2.9m
Epoch 408/500 | Batch 70/202 | Rec 0.000611 | Seg 0.292661 | Elapsed 1.4m | ETA 2.7m
Epoch 408/500 | Batch 80/202 | Rec 0.000615 | Seg 0.298324 | Elapsed 1.6m | ETA 2.5m
Epoch 408/500 | Batch 90/202 | Rec 0.000624 | Seg 0.293974 | Elapsed 1.8m | ETA 2.3m
Epoch 408/500 | Batch 100/202 | Rec 0.000618 | Seg 0.292186 | Elapsed 2.0m | ETA 2.1m
Epoch 408/500 | Batch 110/202 | Rec 0.000611 | Seg 0.289960 | Elapsed 2.3m | ETA 1.9m
Epoch 408/500 | Batch 120/202 | Rec 0.000599 | Seg 0.285456 | Elapsed 2.5m | ETA 1.7m
Epoch 408/500 | Batch 130/202 | Rec 0.000612 | Seg 0.282066 | Elapsed 2.7m | ETA 1.5m
Epoch 408/500 | Batch 140/202 | Rec 0.000607 | Seg 0.281261 | Elapsed 2.9m | ETA 1.3m
Epoch 408/500 | Batch 150/202 | Rec 0.000608 | Seg 0.283696 | Elapsed 3.1m | ETA 1.1m
Epoch 408/500 | Batch 160/202 | Rec 0.000608 | Seg 0.286179 | Elapsed 3.3m | ETA 0.9m
Epoch 408/500 | Batch 170/202 | Rec 0.000602 | Seg 0.281979 | Elapsed 3.5m | ETA 0.7m
Epoch 408/500 | Batch 180/202 | Rec 0.000594 | Seg 0.279623 | Elapsed 3.7m | ETA 0.5m
Epoch 408/500 | Batch 190/202 | Rec 0.000591 | Seg 0.280959 | Elapsed 3.9m | ETA 0.2m
Epoch 408/500 | Batch 200/202 | Rec 0.000589 | Seg 0.279666 | Elapsed 4.1m | ETA 0.0m
Epoch 408/500 | Batch 202/202 | Rec 0.000591 | Seg 0.280690 | Elapsed 4.1m | ETA 0.0m

2026-09-28 17:48:52,259 - INFO: Rec loss: 0.0005906119200373345
2026-09-28 17:48:52,259 - INFO: Seg loss: 0.2806895394800323
2026-09-28 17:48:52,260 - INFO: λ_rec: 1
2026-09-28 17:48:52,260 - INFO: λ_seg: 0.0001
2026-09-28 17:50:11,609 - INFO: -------------------Epoch: 408------------------------
2026-09-28 17:50:11,612 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.050432  0.974941  0.00013
2026-09-28 17:50:11,619 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995781  0.997836  0.997273  0.998499  0.995972
real potato   0.404744  0.576212  1.000000  0.404744  0.999288
fake potato   0.653918  0.790702  0.988376  0.658986  0.999746
real apple    0.706529  0.827981  0.792631  0.866740  0.998758
fake apple    0.616873  0.762997  0.967300  0.630011  0.998523
real orange   0.939760  0.968895  0.994394  0.944766  0.999920
fake orange   0.946973  0.972715  0.970854  0.974683  0.999844
real grape    0.814128  0.897492  0.975223  0.831324  0.999604
fake grape    0.886845  0.939980  0.908015  0.974384  0.999540
real lemon    0.463515  0.633382  0.479097  0.934433  0.998729
fake lemon    0.865281  0.927726  0.992602  0.870898  0.999713
real avocado  0.802606  0.890446  0.829811  0.960755  0.999780
fake avocado  0.731480  0.844870  0.999826  0.731574  0.999679
real pepper   0.851372  0.919670  0.902013  0.938136  0.999401
fake pepper   0.748709  0.856250  0.963500  0.770565  0.999384
real plant    0.872130  0.931648  0.946472  0.917379  0.998655
fake plant    0.827088  0.905312  0.870072  0.943635  0.999843
real banana   0.377591  0.548147  0.872868  0.399565  0.998520
fake banana   0.689390  0.816091  0.793899  0.839665  0.999304
real onion    0.635697  0.777230  0.706916  0.863199  0.999553
fake onion    0.909676  0.952652  0.984270  0.923096  0.999942
real unknown  0.929389  0.963353  1.000000  0.929389  0.999989
fake unknown  0.237269  0.383500  0.254775  0.775444  0.997900
total         0.735076  0.829786  0.877834  0.829646  0.999199
total(-bg)    0.723226  0.822148  0.872405  0.821971  0.999346
2026-09-28 17:50:12,137 - INFO: Epoch accounting: {'epoch': 408, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11287483, 52470, 59638, 109844, 139717, 99275, 97073, 80067, 183222, 72410, 85767, 65849, 40439, 212580, 121299, 140399, 31298, 78351, 82549, 77831, 76507, 12388, 31816], 'crops_with_class': [202, 33, 27, 27, 34, 32, 33, 18, 33, 38, 31, 21, 14, 53, 33, 21, 23, 23, 34, 42, 31, 14, 17], 'targeted_crops_by_class': [0, 7, 4, 1, 3, 4, 7, 1, 2, 3, 7, 9, 6, 4, 6, 5, 2, 3, 5, 5, 2, 7, 3], 'sampled_scene_counts': [0, 0, 3, 1, 2, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 3, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 0, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 3, 0, 0, 4, 2, 2, 1, 1, 2, 1, 1, 1, 1, 3, 2, 2, 0, 1, 1, 0, 0, 2, 1, 1, 4, 2, 1, 1, 1, 1, 3, 2, 0, 1, 2, 1, 0, 1, 2, 2, 4, 1, 1, 0, 3, 0, 1, 0, 1, 1, 0, 1, 1, 4, 4, 2, 2, 1, 4, 1, 1, 1, 1, 1, 0, 2, 1, 4, 1, 1, 0, 1, 1, 1, 0, 3, 1, 2, 2, 2, 2], 'learning_rate': 8.525338123543067e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005906119200373345, 'train_segmentation_loss': 0.2806895394800323, 'val_foreground_miou_all22': 0.7232256974254496, 'val_psnr_ref1': 39.05043197631836, 'elapsed_seconds': 327.92270851135254, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 409/500 | Batch 10/202 | Rec 0.000525 | Seg 0.264235 | Elapsed 0.2m | ETA 3.9m
Epoch 409/500 | Batch 20/202 | Rec 0.000632 | Seg 0.314210 | Elapsed 0.4m | ETA 3.7m
Epoch 409/500 | Batch 30/202 | Rec 0.000622 | Seg 0.302070 | Elapsed 0.6m | ETA 3.5m
Epoch 409/500 | Batch 40/202 | Rec 0.000581 | Seg 0.284030 | Elapsed 0.8m | ETA 3.3m
Epoch 409/500 | Batch 50/202 | Rec 0.000584 | Seg 0.286791 | Elapsed 1.0m | ETA 3.1m
Epoch 409/500 | Batch 60/202 | Rec 0.000580 | Seg 0.289140 | Elapsed 1.2m | ETA 2.9m
Epoch 409/500 | Batch 70/202 | Rec 0.000584 | Seg 0.284979 | Elapsed 1.4m | ETA 2.7m
Epoch 409/500 | Batch 80/202 | Rec 0.000596 | Seg 0.287807 | Elapsed 1.6m | ETA 2.5m
Epoch 409/500 | Batch 90/202 | Rec 0.000609 | Seg 0.286264 | Elapsed 1.8m | ETA 2.3m
Epoch 409/500 | Batch 100/202 | Rec 0.000605 | Seg 0.284877 | Elapsed 2.0m | ETA 2.1m
Epoch 409/500 | Batch 110/202 | Rec 0.000608 | Seg 0.288235 | Elapsed 2.2m | ETA 1.9m
Epoch 409/500 | Batch 120/202 | Rec 0.000607 | Seg 0.291099 | Elapsed 2.4m | ETA 1.7m
Epoch 409/500 | Batch 130/202 | Rec 0.000601 | Seg 0.291436 | Elapsed 2.6m | ETA 1.5m
Epoch 409/500 | Batch 140/202 | Rec 0.000598 | Seg 0.289801 | Elapsed 2.9m | ETA 1.3m
Epoch 409/500 | Batch 150/202 | Rec 0.000604 | Seg 0.288950 | Elapsed 3.1m | ETA 1.1m
Epoch 409/500 | Batch 160/202 | Rec 0.000604 | Seg 0.290630 | Elapsed 3.3m | ETA 0.9m
Epoch 409/500 | Batch 170/202 | Rec 0.000602 | Seg 0.291820 | Elapsed 3.5m | ETA 0.7m
Epoch 409/500 | Batch 180/202 | Rec 0.000605 | Seg 0.292931 | Elapsed 3.7m | ETA 0.5m
Epoch 409/500 | Batch 190/202 | Rec 0.000606 | Seg 0.293477 | Elapsed 3.9m | ETA 0.2m
Epoch 409/500 | Batch 200/202 | Rec 0.000602 | Seg 0.291641 | Elapsed 4.1m | ETA 0.0m
Epoch 409/500 | Batch 202/202 | Rec 0.000603 | Seg 0.292132 | Elapsed 4.1m | ETA 0.0m

2026-09-28 17:54:19,516 - INFO: Rec loss: 0.0006031675530352058
2026-09-28 17:54:19,516 - INFO: Seg loss: 0.292131615378479
2026-09-28 17:54:19,516 - INFO: λ_rec: 1
2026-09-28 17:54:19,516 - INFO: λ_seg: 0.0001
2026-09-28 17:55:38,005 - INFO: -------------------Epoch: 409------------------------
2026-09-28 17:55:38,009 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.166709  0.975082  0.000126
2026-09-28 17:55:38,017 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995925  0.997908  0.997653  0.998264  0.996111
real potato   0.850419  0.919114  0.961817  0.880133  0.999815
fake potato   0.934554  0.966120  0.981626  0.951194  0.999951
real apple    0.811314  0.895779  0.939128  0.856347  0.999313
fake apple    0.575140  0.730225  0.991473  0.577999  0.998388
real orange   0.952902  0.975833  0.994233  0.958198  0.999938
fake orange   0.947801  0.973151  0.964265  0.982305  0.999845
real grape    0.833506  0.909144  0.939644  0.880655  0.999633
fake grape    0.895672  0.944915  0.910928  0.981644  0.999577
real lemon    0.696610  0.821130  0.721692  0.952480  0.999512
fake lemon    0.850929  0.919412  0.994297  0.855103  0.999683
real avocado  0.848555  0.918024  0.872394  0.968801  0.999839
fake avocado  0.710862  0.830950  0.999641  0.711043  0.999654
real pepper   0.800947  0.889423  0.833832  0.953070  0.999134
fake pepper   0.666914  0.800129  0.950828  0.690737  0.999178
real plant    0.882772  0.937687  0.956614  0.919591  0.998779
fake plant    0.767149  0.868184  0.802604  0.945552  0.999772
real banana   0.681506  0.810540  0.876768  0.753701  0.999209
fake banana   0.737141  0.848633  0.816752  0.883212  0.999421
real onion    0.640765  0.781008  0.680547  0.916399  0.999536
fake onion    0.944616  0.971469  0.982205  0.961064  0.999964
real unknown  0.840813  0.913473  0.881883  0.947519  0.999971
fake unknown  0.231645  0.376117  0.251653  0.744477  0.997919
total         0.786889  0.869494  0.882716  0.881282  0.999310
total(-bg)    0.777388  0.863657  0.877492  0.875965  0.999456
2026-09-28 17:55:38,901 - INFO: Epoch accounting: {'epoch': 409, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11200446, 55257, 57407, 105022, 102799, 117577, 81207, 168348, 248637, 73430, 58671, 37161, 41726, 205583, 100730, 186428, 28560, 72300, 84020, 92775, 56937, 10783, 52468], 'crops_with_class': [202, 33, 28, 28, 33, 34, 28, 36, 42, 32, 26, 13, 13, 49, 30, 24, 25, 23, 30, 37, 29, 11, 23], 'targeted_crops_by_class': [0, 7, 3, 0, 2, 5, 2, 3, 5, 4, 6, 3, 4, 2, 6, 7, 6, 3, 5, 10, 7, 6, 6], 'sampled_scene_counts': [1, 0, 1, 1, 0, 2, 2, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 0, 1, 2, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 2, 2, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 1, 0, 2, 2, 0, 2, 2, 2, 0, 2, 3, 2, 3, 1, 1, 1, 1, 0, 0, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 1, 2, 1, 1, 4, 3, 4, 1, 1, 1, 2, 2, 0, 0, 1, 0, 3, 0, 0, 2, 0, 1, 0, 2, 2, 0, 2, 1, 2, 1, 2, 1, 1, 2, 0, 3, 1, 2, 0, 1, 2, 4, 4, 0, 2, 4], 'learning_rate': 8.353289002898174e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006031675530352058, 'train_segmentation_loss': 0.292131615378479, 'val_foreground_miou_all22': 0.7773877742924625, 'val_psnr_ref1': 39.16670852661133, 'elapsed_seconds': 326.75512957572937, 'peak_cuda_allocated_gib': 7.510318756103516}

Epoch 410/500 | Batch 10/202 | Rec 0.000531 | Seg 0.224195 | Elapsed 0.2m | ETA 4.0m
Epoch 410/500 | Batch 20/202 | Rec 0.000629 | Seg 0.272070 | Elapsed 0.4m | ETA 3.8m
Epoch 410/500 | Batch 30/202 | Rec 0.000580 | Seg 0.274611 | Elapsed 0.6m | ETA 3.6m
Epoch 410/500 | Batch 40/202 | Rec 0.000583 | Seg 0.279030 | Elapsed 0.8m | ETA 3.4m
Epoch 410/500 | Batch 50/202 | Rec 0.000592 | Seg 0.290252 | Elapsed 1.0m | ETA 3.1m
Epoch 410/500 | Batch 60/202 | Rec 0.000590 | Seg 0.295787 | Elapsed 1.2m | ETA 2.9m
Epoch 410/500 | Batch 70/202 | Rec 0.000571 | Seg 0.280167 | Elapsed 1.4m | ETA 2.7m
Epoch 410/500 | Batch 80/202 | Rec 0.000571 | Seg 0.283558 | Elapsed 1.6m | ETA 2.5m
Epoch 410/500 | Batch 90/202 | Rec 0.000588 | Seg 0.293674 | Elapsed 1.9m | ETA 2.3m
Epoch 410/500 | Batch 100/202 | Rec 0.000587 | Seg 0.294828 | Elapsed 2.1m | ETA 2.1m
Epoch 410/500 | Batch 110/202 | Rec 0.000600 | Seg 0.294260 | Elapsed 2.3m | ETA 1.9m
Epoch 410/500 | Batch 120/202 | Rec 0.000605 | Seg 0.295477 | Elapsed 2.5m | ETA 1.7m
Epoch 410/500 | Batch 130/202 | Rec 0.000607 | Seg 0.293530 | Elapsed 2.7m | ETA 1.5m
Epoch 410/500 | Batch 140/202 | Rec 0.000603 | Seg 0.291792 | Elapsed 2.9m | ETA 1.3m
Epoch 410/500 | Batch 150/202 | Rec 0.000595 | Seg 0.288061 | Elapsed 3.1m | ETA 1.1m
Epoch 410/500 | Batch 160/202 | Rec 0.000592 | Seg 0.284959 | Elapsed 3.3m | ETA 0.9m
Epoch 410/500 | Batch 170/202 | Rec 0.000585 | Seg 0.283541 | Elapsed 3.5m | ETA 0.7m
Epoch 410/500 | Batch 180/202 | Rec 0.000584 | Seg 0.282741 | Elapsed 3.7m | ETA 0.4m
Epoch 410/500 | Batch 190/202 | Rec 0.000582 | Seg 0.282860 | Elapsed 3.9m | ETA 0.2m
Epoch 410/500 | Batch 200/202 | Rec 0.000580 | Seg 0.278790 | Elapsed 4.1m | ETA 0.0m
Epoch 410/500 | Batch 202/202 | Rec 0.000577 | Seg 0.278046 | Elapsed 4.1m | ETA 0.0m

2026-09-28 17:59:46,585 - INFO: Rec loss: 0.000576575547612346
2026-09-28 17:59:46,585 - INFO: Seg loss: 0.2780458528437827
2026-09-28 17:59:46,585 - INFO: λ_rec: 1
2026-09-28 17:59:46,585 - INFO: λ_seg: 0.0001
2026-09-28 18:01:05,611 - INFO: -------------------Epoch: 410------------------------
2026-09-28 18:01:05,615 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.036791  0.974955  0.000131
2026-09-28 18:01:05,622 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995563  0.997727  0.996996  0.998558  0.995764
real potato   0.793637  0.884898  0.955769  0.823897  0.999744
fake potato   0.796645  0.886764  0.971557  0.815668  0.999848
real apple    0.722459  0.838819  0.916234  0.773552  0.998975
fake apple    0.586945  0.739670  0.992852  0.589436  0.998434
real orange   0.916224  0.956231  0.996236  0.919407  0.999889
fake orange   0.924536  0.960738  0.945229  0.976868  0.999772
real grape    0.828447  0.906126  0.956179  0.861142  0.999628
fake grape    0.906086  0.950680  0.938298  0.963495  0.999631
real lemon    0.493977  0.661246  0.507827  0.947676  0.998859
fake lemon    0.857409  0.923182  0.993600  0.862171  0.999697
real avocado  0.898375  0.946418  0.931056  0.962397  0.999899
fake avocado  0.701428  0.824468  0.999637  0.701607  0.999643
real pepper   0.781234  0.877133  0.816070  0.948190  0.999029
fake pepper   0.649055  0.787135  0.949295  0.672364  0.999133
real plant    0.864370  0.927201  0.962691  0.894328  0.998596
fake plant    0.753095  0.859110  0.844062  0.874808  0.999772
real banana   0.427950  0.599345  0.834383  0.467676  0.998595
fake banana   0.734945  0.847176  0.827845  0.867535  0.999424
real onion    0.640864  0.781081  0.685681  0.907448  0.999541
fake onion    0.929174  0.963237  0.995869  0.932769  0.999955
real unknown  0.387755  0.558782  0.397106  0.942748  0.999762
fake unknown  0.209000  0.345703  0.228518  0.709888  0.997736
total         0.730399  0.827081  0.854043  0.844071  0.999188
total(-bg)    0.718346  0.819325  0.847545  0.837049  0.999344
2026-09-28 18:01:06,179 - INFO: Epoch accounting: {'epoch': 410, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11286628, 60592, 74237, 105051, 122136, 86597, 63851, 188440, 198800, 79058, 46398, 46062, 44529, 210090, 131325, 123229, 25248, 74982, 70809, 79116, 50933, 13406, 56755], 'crops_with_class': [202, 36, 31, 28, 29, 24, 23, 33, 36, 33, 25, 16, 16, 53, 29, 19, 23, 23, 32, 35, 26, 13, 22], 'targeted_crops_by_class': [0, 3, 5, 2, 1, 4, 7, 10, 3, 3, 6, 5, 2, 7, 5, 7, 4, 3, 2, 4, 6, 6, 4], 'sampled_scene_counts': [1, 1, 1, 0, 1, 1, 0, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 2, 2, 1, 1, 0, 1, 0, 0, 2, 1, 1, 0, 1, 2, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 1, 0, 2, 0, 1, 0, 2, 3, 0, 0, 2, 2, 0, 1, 0, 0, 2, 3, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 2, 0, 2, 1, 1, 1, 2, 1, 4, 1, 0, 0, 2, 2, 0, 0, 1, 2, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 3, 1, 1, 1, 3, 2, 0, 1, 4, 2, 3, 2, 2, 0, 1, 2, 2, 0, 1, 2, 0, 0, 1, 3, 1, 2, 1, 1, 0, 1, 1, 1, 2, 2, 2, 1, 3, 3, 2, 2, 2, 0, 1, 0, 1, 3, 2, 4, 0, 0, 2], 'learning_rate': 8.182888957878807e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000576575547612346, 'train_segmentation_loss': 0.2780458528437827, 'val_foreground_miou_all22': 0.7183458007231032, 'val_psnr_ref1': 39.03679138183594, 'elapsed_seconds': 327.2691626548767, 'peak_cuda_allocated_gib': 7.510044097900391}

Stopped after epoch 410; scheduler horizon remains 500
Download: /kaggle/working/paired_sampling_epoch400_20260928_170349_balanced_control.zip

/kaggle/working/paired_sampling_epoch400_20260928_170349_balanced_control.zip

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/paired_sampling_epoch400_20260928_170349/', name='original_sampler', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/working/paired_sampling_epoch400_20260928_170349/seeds/original_sampler/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=410, lambda_seg=0.0001, sampling_policy='baseline')
Dataset size (num. batches) 202 25

2026-09-28 18:01:41,813 - INFO: Resuming after epoch 400

Epoch 401/500 | Batch 10/202 | Rec 0.000475 | Seg 0.210523 | Elapsed 0.4m | ETA 8.3m
Epoch 401/500 | Batch 20/202 | Rec 0.000554 | Seg 0.242832 | Elapsed 0.6m | ETA 5.8m
Epoch 401/500 | Batch 30/202 | Rec 0.000548 | Seg 0.241453 | Elapsed 0.9m | ETA 4.9m
Epoch 401/500 | Batch 40/202 | Rec 0.000609 | Seg 0.250702 | Elapsed 1.1m | ETA 4.3m
Epoch 401/500 | Batch 50/202 | Rec 0.000579 | Seg 0.240756 | Elapsed 1.3m | ETA 3.9m
Epoch 401/500 | Batch 60/202 | Rec 0.000562 | Seg 0.239049 | Elapsed 1.5m | ETA 3.5m
Epoch 401/500 | Batch 70/202 | Rec 0.000548 | Seg 0.239885 | Elapsed 1.7m | ETA 3.2m
Epoch 401/500 | Batch 80/202 | Rec 0.000550 | Seg 0.242808 | Elapsed 1.9m | ETA 2.9m
Epoch 401/500 | Batch 90/202 | Rec 0.000585 | Seg 0.245414 | Elapsed 2.1m | ETA 2.6m
Epoch 401/500 | Batch 100/202 | Rec 0.000572 | Seg 0.238893 | Elapsed 2.3m | ETA 2.4m
Epoch 401/500 | Batch 110/202 | Rec 0.000567 | Seg 0.242271 | Elapsed 2.6m | ETA 2.1m
Epoch 401/500 | Batch 120/202 | Rec 0.000560 | Seg 0.239211 | Elapsed 2.8m | ETA 1.9m
Epoch 401/500 | Batch 130/202 | Rec 0.000559 | Seg 0.242275 | Elapsed 3.0m | ETA 1.7m
Epoch 401/500 | Batch 140/202 | Rec 0.000557 | Seg 0.243928 | Elapsed 3.2m | ETA 1.4m
Epoch 401/500 | Batch 150/202 | Rec 0.000551 | Seg 0.242606 | Elapsed 3.4m | ETA 1.2m
Epoch 401/500 | Batch 160/202 | Rec 0.000548 | Seg 0.245263 | Elapsed 3.6m | ETA 1.0m
Epoch 401/500 | Batch 170/202 | Rec 0.000544 | Seg 0.242715 | Elapsed 3.8m | ETA 0.7m
Epoch 401/500 | Batch 180/202 | Rec 0.000540 | Seg 0.243407 | Elapsed 4.1m | ETA 0.5m
Epoch 401/500 | Batch 190/202 | Rec 0.000549 | Seg 0.248784 | Elapsed 4.3m | ETA 0.3m
Epoch 401/500 | Batch 200/202 | Rec 0.000550 | Seg 0.249760 | Elapsed 4.5m | ETA 0.0m
Epoch 401/500 | Batch 202/202 | Rec 0.000553 | Seg 0.250918 | Elapsed 4.5m | ETA 0.0m

2026-09-28 18:06:14,300 - INFO: Rec loss: 0.000553301333620946
2026-09-28 18:06:14,300 - INFO: Seg loss: 0.250918207247511
2026-09-28 18:06:14,300 - INFO: λ_rec: 1
2026-09-28 18:06:14,300 - INFO: λ_seg: 0.0001
2026-09-28 18:07:30,265 - INFO: -------------------Epoch: 401------------------------
2026-09-28 18:07:30,270 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.151093  0.975098  0.000127
2026-09-28 18:07:30,277 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995859  0.997875  0.997255  0.998596  0.996046
real potato   0.801459  0.889740  0.983632  0.812293  0.999759
fake potato   0.849403  0.918520  0.980966  0.863636  0.999888
real apple    0.790447  0.882911  0.896816  0.869527  0.999205
fake apple    0.566023  0.722833  0.993218  0.568219  0.998355
real orange   0.885014  0.938950  0.993283  0.890343  0.999848
fake orange   0.915989  0.956103  0.940597  0.972231  0.999745
real grape    0.829677  0.906861  0.970422  0.851202  0.999635
fake grape    0.891789  0.942750  0.927796  0.958297  0.999570
real lemon    0.524007  0.687624  0.538157  0.952220  0.998983
fake lemon    0.842468  0.914450  0.995248  0.845871  0.999665
real avocado  0.834100  0.909497  0.870126  0.952709  0.999824
fake avocado  0.603084  0.752357  0.998734  0.603545  0.999525
real pepper   0.812700  0.896624  0.845790  0.954071  0.999196
fake pepper   0.673513  0.804861  0.944790  0.701107  0.999190
real plant    0.878335  0.935177  0.951046  0.919926  0.998725
fake plant    0.732651  0.845650  0.773276  0.933090  0.999729
real banana   0.478943  0.647636  0.881150  0.512020  0.998748
fake banana   0.691295  0.817425  0.780333  0.858328  0.999295
real onion    0.615938  0.762279  0.709485  0.823678  0.999536
fake onion    0.917811  0.957095  0.960995  0.953325  0.999946
real unknown  0.900763  0.947741  1.000000  0.900763  0.999984
fake unknown  0.199101  0.332046  0.222134  0.657552  0.997771
total         0.749146  0.842044  0.876315  0.841415  0.999225
total(-bg)    0.737932  0.834960  0.870818  0.834271  0.999369
2026-09-28 18:07:31,070 - INFO: Epoch accounting: {'epoch': 401, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11475453, 40350, 41786, 150134, 157014, 68234, 68320, 134247, 194870, 63925, 52418, 46805, 28311, 198432, 110280, 169958, 18196, 44896, 49961, 65438, 29078, 4200, 25966], 'crops_with_class': [202, 22, 19, 40, 33, 21, 23, 27, 34, 27, 21, 14, 12, 46, 27, 20, 17, 15, 20, 26, 15, 5, 13], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 9.775277405549487e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000553301333620946, 'train_segmentation_loss': 0.250918207247511, 'val_foreground_miou_all22': 0.7379322866486517, 'val_psnr_ref1': 39.151093292236325, 'elapsed_seconds': 349.24926829338074, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 402/500 | Batch 10/202 | Rec 0.000554 | Seg 0.233701 | Elapsed 0.2m | ETA 4.1m
Epoch 402/500 | Batch 20/202 | Rec 0.000470 | Seg 0.217251 | Elapsed 0.4m | ETA 3.9m
Epoch 402/500 | Batch 30/202 | Rec 0.000508 | Seg 0.222101 | Elapsed 0.6m | ETA 3.7m
Epoch 402/500 | Batch 40/202 | Rec 0.000534 | Seg 0.242033 | Elapsed 0.9m | ETA 3.5m
Epoch 402/500 | Batch 50/202 | Rec 0.000543 | Seg 0.256381 | Elapsed 1.1m | ETA 3.3m
Epoch 402/500 | Batch 60/202 | Rec 0.000561 | Seg 0.261992 | Elapsed 1.3m | ETA 3.1m
Epoch 402/500 | Batch 70/202 | Rec 0.000590 | Seg 0.265415 | Elapsed 1.5m | ETA 2.9m
Epoch 402/500 | Batch 80/202 | Rec 0.000602 | Seg 0.267422 | Elapsed 1.7m | ETA 2.6m
Epoch 402/500 | Batch 90/202 | Rec 0.000592 | Seg 0.263195 | Elapsed 1.9m | ETA 2.4m
Epoch 402/500 | Batch 100/202 | Rec 0.000583 | Seg 0.259279 | Elapsed 2.2m | ETA 2.2m
Epoch 402/500 | Batch 110/202 | Rec 0.000583 | Seg 0.258980 | Elapsed 2.4m | ETA 2.0m
Epoch 402/500 | Batch 120/202 | Rec 0.000569 | Seg 0.254009 | Elapsed 2.6m | ETA 1.8m
Epoch 402/500 | Batch 130/202 | Rec 0.000568 | Seg 0.253214 | Elapsed 2.8m | ETA 1.6m
Epoch 402/500 | Batch 140/202 | Rec 0.000561 | Seg 0.250163 | Elapsed 3.0m | ETA 1.3m
Epoch 402/500 | Batch 150/202 | Rec 0.000569 | Seg 0.253046 | Elapsed 3.2m | ETA 1.1m
Epoch 402/500 | Batch 160/202 | Rec 0.000568 | Seg 0.253789 | Elapsed 3.5m | ETA 0.9m
Epoch 402/500 | Batch 170/202 | Rec 0.000559 | Seg 0.252602 | Elapsed 3.7m | ETA 0.7m
Epoch 402/500 | Batch 180/202 | Rec 0.000564 | Seg 0.254616 | Elapsed 3.9m | ETA 0.5m
Epoch 402/500 | Batch 190/202 | Rec 0.000568 | Seg 0.256450 | Elapsed 4.1m | ETA 0.3m
Epoch 402/500 | Batch 200/202 | Rec 0.000567 | Seg 0.255746 | Elapsed 4.3m | ETA 0.0m
Epoch 402/500 | Batch 202/202 | Rec 0.000564 | Seg 0.254200 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:11:53,905 - INFO: Rec loss: 0.0005640397913060105
2026-09-28 18:11:53,906 - INFO: Seg loss: 0.2541997845810239
2026-09-28 18:11:53,906 - INFO: λ_rec: 1
2026-09-28 18:11:53,906 - INFO: λ_seg: 0.0001
2026-09-28 18:13:11,652 - INFO: -------------------Epoch: 402------------------------
2026-09-28 18:13:11,656 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.067134  0.974932  0.00013
2026-09-28 18:13:11,663 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995732  0.997811  0.997516  0.998208  0.995927
real potato   0.649081  0.787155  0.960683  0.666794  0.999569
fake potato   0.726240  0.841363  0.981569  0.736280  0.999798
real apple    0.737937  0.849160  0.857813  0.840778  0.998970
fake apple    0.531823  0.694320  0.989238  0.534918  0.998222
real orange   0.933718  0.965673  0.995208  0.937934  0.999912
fake orange   0.943891  0.971086  0.957283  0.985396  0.999832
real grape    0.797185  0.887098  0.901471  0.873273  0.999536
fake grape    0.898623  0.946555  0.918059  0.976983  0.999592
real lemon    0.562123  0.719644  0.576727  0.956894  0.999124
fake lemon    0.855951  0.922336  0.996650  0.858420  0.999694
real avocado  0.855213  0.921907  0.880927  0.966995  0.999848
fake avocado  0.467296  0.636905  0.999727  0.467355  0.999362
real pepper   0.795123  0.885821  0.832331  0.946771  0.999108
fake pepper   0.648190  0.786499  0.967739  0.662506  0.999143
real plant    0.873435  0.932392  0.953929  0.911902  0.998678
fake plant    0.751218  0.857888  0.784919  0.945936  0.999751
real banana   0.530529  0.693214  0.829737  0.595342  0.998816
fake banana   0.705969  0.827596  0.784288  0.876078  0.999329
real onion    0.650511  0.788204  0.705443  0.893092  0.999566
fake onion    0.935368  0.966555  0.993112  0.941475  0.999959
real unknown  0.769841  0.869905  0.820643  0.925572  0.999956
fake unknown  0.183118  0.309518  0.196369  0.730713  0.997253
total         0.730353  0.828635  0.864408  0.836070  0.999172
total(-bg)    0.718290  0.820945  0.858358  0.828700  0.999319
2026-09-28 18:13:12,182 - INFO: Epoch accounting: {'epoch': 402, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11437973, 39377, 35623, 164292, 146537, 77588, 61210, 143207, 193470, 69876, 41005, 34904, 29512, 194553, 134411, 177742, 18836, 58528, 49532, 63937, 39395, 4486, 22278], 'crops_with_class': [202, 23, 17, 38, 34, 22, 21, 28, 34, 27, 20, 13, 12, 44, 29, 23, 17, 18, 18, 27, 18, 6, 11], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 9.591878548899425e-06, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0005640397913060105, 'train_segmentation_loss': 0.2541997845810239, 'val_foreground_miou_all22': 0.7182900961226376, 'val_psnr_ref1': 39.06713394165039, 'elapsed_seconds': 341.1025893688202, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 403/500 | Batch 10/202 | Rec 0.000451 | Seg 0.180930 | Elapsed 0.2m | ETA 4.1m
Epoch 403/500 | Batch 20/202 | Rec 0.000492 | Seg 0.223128 | Elapsed 0.4m | ETA 3.9m
Epoch 403/500 | Batch 30/202 | Rec 0.000516 | Seg 0.243124 | Elapsed 0.6m | ETA 3.7m
Epoch 403/500 | Batch 40/202 | Rec 0.000498 | Seg 0.237329 | Elapsed 0.9m | ETA 3.5m
Epoch 403/500 | Batch 50/202 | Rec 0.000541 | Seg 0.246554 | Elapsed 1.1m | ETA 3.3m
Epoch 403/500 | Batch 60/202 | Rec 0.000562 | Seg 0.264633 | Elapsed 1.3m | ETA 3.1m
Epoch 403/500 | Batch 70/202 | Rec 0.000567 | Seg 0.268320 | Elapsed 1.5m | ETA 2.9m
Epoch 403/500 | Batch 80/202 | Rec 0.000562 | Seg 0.262230 | Elapsed 1.7m | ETA 2.6m
Epoch 403/500 | Batch 90/202 | Rec 0.000577 | Seg 0.258821 | Elapsed 1.9m | ETA 2.4m
Epoch 403/500 | Batch 100/202 | Rec 0.000562 | Seg 0.254354 | Elapsed 2.2m | ETA 2.2m
Epoch 403/500 | Batch 110/202 | Rec 0.000547 | Seg 0.248782 | Elapsed 2.4m | ETA 2.0m
Epoch 403/500 | Batch 120/202 | Rec 0.000566 | Seg 0.250455 | Elapsed 2.6m | ETA 1.8m
Epoch 403/500 | Batch 130/202 | Rec 0.000571 | Seg 0.249867 | Elapsed 2.8m | ETA 1.6m
Epoch 403/500 | Batch 140/202 | Rec 0.000563 | Seg 0.245690 | Elapsed 3.0m | ETA 1.3m
Epoch 403/500 | Batch 150/202 | Rec 0.000558 | Seg 0.245093 | Elapsed 3.2m | ETA 1.1m
Epoch 403/500 | Batch 160/202 | Rec 0.000559 | Seg 0.244967 | Elapsed 3.5m | ETA 0.9m
Epoch 403/500 | Batch 170/202 | Rec 0.000569 | Seg 0.246542 | Elapsed 3.7m | ETA 0.7m
Epoch 403/500 | Batch 180/202 | Rec 0.000579 | Seg 0.251635 | Elapsed 3.9m | ETA 0.5m
Epoch 403/500 | Batch 190/202 | Rec 0.000575 | Seg 0.251189 | Elapsed 4.1m | ETA 0.3m
Epoch 403/500 | Batch 200/202 | Rec 0.000574 | Seg 0.252857 | Elapsed 4.3m | ETA 0.0m
Epoch 403/500 | Batch 202/202 | Rec 0.000574 | Seg 0.253059 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:17:34,893 - INFO: Rec loss: 0.0005739424916532923
2026-09-28 18:17:34,893 - INFO: Seg loss: 0.25305948904392744
2026-09-28 18:17:34,893 - INFO: λ_rec: 1
2026-09-28 18:17:34,893 - INFO: λ_seg: 0.0001
2026-09-28 18:18:51,916 - INFO: -------------------Epoch: 403------------------------
2026-09-28 18:18:51,920 - INFO:
Validation stats:
        PSNR     SSIM      MSE
0  39.039908  0.97485  0.00013
2026-09-28 18:18:51,927 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995615  0.997753  0.996792  0.998815  0.995812
real potato   0.398573  0.569930  0.998085  0.398878  0.999280
fake potato   0.678005  0.808060  0.994490  0.680561  0.999765
real apple    0.681013  0.810192  0.743970  0.889474  0.998563
fake apple    0.629634  0.772683  0.990334  0.633527  0.998593
real orange   0.880005  0.936123  0.992732  0.885711  0.999841
fake orange   0.919984  0.958275  0.948616  0.968234  0.999759
real grape    0.844771  0.915804  0.955965  0.878974  0.999663
fake grape    0.888927  0.941148  0.918597  0.964938  0.999554
real lemon    0.484721  0.652899  0.509039  0.910283  0.998863
fake lemon    0.854638  0.921573  0.991119  0.861233  0.999690
real avocado  0.814841  0.897925  0.842643  0.961084  0.999797
fake avocado  0.755768  0.860848  0.999494  0.756057  0.999708
real pepper   0.813618  0.897182  0.857273  0.941098  0.999211
fake pepper   0.652006  0.789302  0.937963  0.681390  0.999133
real plant    0.870912  0.930953  0.959720  0.903954  0.998660
fake plant    0.761623  0.864633  0.865680  0.863689  0.999785
real banana   0.458593  0.628770  0.909289  0.480579  0.998725
fake banana   0.724932  0.840484  0.862391  0.819758  0.999428
real onion    0.485398  0.653510  0.716559  0.600743  0.999425
fake onion    0.924221  0.960568  0.991000  0.932044  0.999952
real unknown  0.899809  0.947213  1.000000  0.899809  0.999984
fake unknown  0.222092  0.363424  0.246946  0.688156  0.997969
total         0.723465  0.822576  0.879509  0.808652  0.999181
total(-bg)    0.711095  0.814614  0.874178  0.800008  0.999334
2026-09-28 18:18:52,444 - INFO: Epoch accounting: {'epoch': 403, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11465494, 41755, 38783, 141248, 163366, 70475, 61476, 140707, 188470, 63650, 42149, 36785, 29921, 201641, 117275, 183709, 20054, 52642, 44456, 61550, 40593, 5079, 26994], 'crops_with_class': [202, 21, 19, 38, 35, 20, 21, 27, 31, 25, 18, 13, 11, 49, 29, 23, 19, 14, 18, 25, 18, 5, 10], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 9.410079870480438e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005739424916532923, 'train_segmentation_loss': 0.25305948904392744, 'val_foreground_miou_all22': 0.7110946680557768, 'val_psnr_ref1': 39.03990783691406, 'elapsed_seconds': 340.2533233165741, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 404/500 | Batch 10/202 | Rec 0.000484 | Seg 0.222497 | Elapsed 0.2m | ETA 4.2m
Epoch 404/500 | Batch 20/202 | Rec 0.000574 | Seg 0.271175 | Elapsed 0.4m | ETA 3.9m
Epoch 404/500 | Batch 30/202 | Rec 0.000571 | Seg 0.267422 | Elapsed 0.7m | ETA 3.7m
Epoch 404/500 | Batch 40/202 | Rec 0.000598 | Seg 0.256764 | Elapsed 0.9m | ETA 3.5m
Epoch 404/500 | Batch 50/202 | Rec 0.000599 | Seg 0.256393 | Elapsed 1.1m | ETA 3.3m
Epoch 404/500 | Batch 60/202 | Rec 0.000581 | Seg 0.253867 | Elapsed 1.3m | ETA 3.1m
Epoch 404/500 | Batch 70/202 | Rec 0.000558 | Seg 0.240796 | Elapsed 1.5m | ETA 2.9m
Epoch 404/500 | Batch 80/202 | Rec 0.000553 | Seg 0.242137 | Elapsed 1.7m | ETA 2.7m
Epoch 404/500 | Batch 90/202 | Rec 0.000559 | Seg 0.245743 | Elapsed 2.0m | ETA 2.4m
Epoch 404/500 | Batch 100/202 | Rec 0.000589 | Seg 0.245707 | Elapsed 2.2m | ETA 2.2m
Epoch 404/500 | Batch 110/202 | Rec 0.000590 | Seg 0.247448 | Elapsed 2.4m | ETA 2.0m
Epoch 404/500 | Batch 120/202 | Rec 0.000581 | Seg 0.247168 | Elapsed 2.6m | ETA 1.8m
Epoch 404/500 | Batch 130/202 | Rec 0.000578 | Seg 0.248466 | Elapsed 2.8m | ETA 1.6m
Epoch 404/500 | Batch 140/202 | Rec 0.000575 | Seg 0.251719 | Elapsed 3.0m | ETA 1.3m
Epoch 404/500 | Batch 150/202 | Rec 0.000571 | Seg 0.248887 | Elapsed 3.3m | ETA 1.1m
Epoch 404/500 | Batch 160/202 | Rec 0.000584 | Seg 0.255112 | Elapsed 3.5m | ETA 0.9m
Epoch 404/500 | Batch 170/202 | Rec 0.000583 | Seg 0.254111 | Elapsed 3.7m | ETA 0.7m
Epoch 404/500 | Batch 180/202 | Rec 0.000582 | Seg 0.254427 | Elapsed 3.9m | ETA 0.5m
Epoch 404/500 | Batch 190/202 | Rec 0.000574 | Seg 0.253024 | Elapsed 4.1m | ETA 0.3m
Epoch 404/500 | Batch 200/202 | Rec 0.000568 | Seg 0.253271 | Elapsed 4.3m | ETA 0.0m
Epoch 404/500 | Batch 202/202 | Rec 0.000568 | Seg 0.253278 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:23:16,025 - INFO: Rec loss: 0.0005679762823389622
2026-09-28 18:23:16,025 - INFO: Seg loss: 0.25327789846180687
2026-09-28 18:23:16,025 - INFO: λ_rec: 1
2026-09-28 18:23:16,025 - INFO: λ_seg: 0.0001
2026-09-28 18:24:36,786 - INFO: -------------------Epoch: 404------------------------
2026-09-28 18:24:36,790 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.960119  0.974683  0.000133
2026-09-28 18:24:36,798 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995632  0.997761  0.997018  0.998605  0.995829
real potato   0.450948  0.621548  0.981293  0.454858  0.999337
fake potato   0.665207  0.798900  0.992844  0.668412  0.999755
real apple    0.715605  0.834181  0.810024  0.859929  0.998821
fake apple    0.667306  0.800412  0.982365  0.675396  0.998729
real orange   0.952337  0.975537  0.993992  0.957851  0.999937
fake orange   0.958414  0.978715  0.978531  0.979000  0.999878
real grape    0.784075  0.878921  0.948455  0.818972  0.999529
fake grape    0.903303  0.949145  0.930087  0.969104  0.999616
real lemon    0.612118  0.759348  0.635576  0.943132  0.999298
fake lemon    0.845262  0.916093  0.998045  0.846664  0.999672
real avocado  0.850630  0.919237  0.877688  0.965025  0.999843
fake avocado  0.740788  0.851046  0.999828  0.740882  0.999690
real pepper   0.793404  0.884752  0.833912  0.942308  0.999102
fake pepper   0.652949  0.789993  0.981191  0.661225  0.999162
real plant    0.857398  0.923175  0.947711  0.899973  0.998503
fake plant    0.831768  0.908109  0.884008  0.933666  0.999850
real banana   0.594982  0.746019  0.898909  0.637648  0.999025
fake banana   0.719398  0.836752  0.825228  0.848706  0.999391
real onion    0.637361  0.778474  0.673701  0.921973  0.999526
fake onion    0.921677  0.959192  0.989712  0.930592  0.999950
real unknown  0.867502  0.929001  0.933526  0.924618  0.999977
fake unknown  0.254517  0.405723  0.274452  0.777979  0.998080
total         0.750982  0.845306  0.885569  0.841588  0.999239
total(-bg)    0.739861  0.838376  0.880503  0.834451  0.999394
2026-09-28 18:24:37,491 - INFO: Epoch accounting: {'epoch': 404, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11462265, 43526, 43417, 142973, 139191, 71639, 61504, 130390, 180850, 66479, 55179, 39832, 42091, 216271, 121513, 143882, 21181, 57254, 53541, 63884, 45823, 4445, 31142], 'crops_with_class': [202, 25, 19, 34, 34, 21, 18, 24, 34, 31, 22, 14, 15, 42, 27, 21, 19, 19, 22, 25, 19, 6, 13], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 9.229888547393062e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005679762823389622, 'train_segmentation_loss': 0.25327789846180687, 'val_foreground_miou_all22': 0.7398612938353661, 'val_psnr_ref1': 38.96011932373047, 'elapsed_seconds': 345.038941860199, 'peak_cuda_allocated_gib': 7.509067535400391}

Epoch 405/500 | Batch 10/202 | Rec 0.000495 | Seg 0.272210 | Elapsed 0.2m | ETA 4.1m
Epoch 405/500 | Batch 20/202 | Rec 0.000507 | Seg 0.247416 | Elapsed 0.4m | ETA 3.9m
Epoch 405/500 | Batch 30/202 | Rec 0.000525 | Seg 0.245305 | Elapsed 0.6m | ETA 3.7m
Epoch 405/500 | Batch 40/202 | Rec 0.000521 | Seg 0.242445 | Elapsed 0.9m | ETA 3.5m
Epoch 405/500 | Batch 50/202 | Rec 0.000542 | Seg 0.246796 | Elapsed 1.1m | ETA 3.3m
Epoch 405/500 | Batch 60/202 | Rec 0.000538 | Seg 0.251327 | Elapsed 1.3m | ETA 3.1m
Epoch 405/500 | Batch 70/202 | Rec 0.000559 | Seg 0.257650 | Elapsed 1.5m | ETA 2.8m
Epoch 405/500 | Batch 80/202 | Rec 0.000554 | Seg 0.258086 | Elapsed 1.7m | ETA 2.6m
Epoch 405/500 | Batch 90/202 | Rec 0.000552 | Seg 0.258044 | Elapsed 1.9m | ETA 2.4m
Epoch 405/500 | Batch 100/202 | Rec 0.000559 | Seg 0.251639 | Elapsed 2.2m | ETA 2.2m
Epoch 405/500 | Batch 110/202 | Rec 0.000547 | Seg 0.246763 | Elapsed 2.4m | ETA 2.0m
Epoch 405/500 | Batch 120/202 | Rec 0.000560 | Seg 0.250338 | Elapsed 2.6m | ETA 1.8m
Epoch 405/500 | Batch 130/202 | Rec 0.000557 | Seg 0.251544 | Elapsed 2.8m | ETA 1.6m
Epoch 405/500 | Batch 140/202 | Rec 0.000545 | Seg 0.248781 | Elapsed 3.0m | ETA 1.3m
Epoch 405/500 | Batch 150/202 | Rec 0.000550 | Seg 0.246664 | Elapsed 3.2m | ETA 1.1m
Epoch 405/500 | Batch 160/202 | Rec 0.000561 | Seg 0.251527 | Elapsed 3.5m | ETA 0.9m
Epoch 405/500 | Batch 170/202 | Rec 0.000577 | Seg 0.253457 | Elapsed 3.7m | ETA 0.7m
Epoch 405/500 | Batch 180/202 | Rec 0.000579 | Seg 0.256139 | Elapsed 3.9m | ETA 0.5m
Epoch 405/500 | Batch 190/202 | Rec 0.000578 | Seg 0.261066 | Elapsed 4.1m | ETA 0.3m
Epoch 405/500 | Batch 200/202 | Rec 0.000574 | Seg 0.258897 | Elapsed 4.3m | ETA 0.0m
Epoch 405/500 | Batch 202/202 | Rec 0.000573 | Seg 0.258570 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:28:59,069 - INFO: Rec loss: 0.0005728399018972586
2026-09-28 18:28:59,069 - INFO: Seg loss: 0.25857008279919036
2026-09-28 18:28:59,069 - INFO: λ_rec: 1
2026-09-28 18:28:59,069 - INFO: λ_seg: 0.0001
2026-09-28 18:30:20,543 - INFO: -------------------Epoch: 405------------------------
2026-09-28 18:30:20,547 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.904726  0.974693  0.000134
2026-09-28 18:30:20,554 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995594  0.997742  0.997455  0.998129  0.995794
real potato   0.357806  0.526997  0.993991  0.358582  0.999230
fake potato   0.654944  0.791452  0.981401  0.663176  0.999745
real apple    0.684313  0.812522  0.773452  0.855860  0.998638
fake apple    0.684622  0.812741  0.967735  0.700614  0.998781
real orange   0.949164  0.973869  0.995286  0.953451  0.999933
fake orange   0.945475  0.971923  0.960837  0.983371  0.999838
real grape    0.788932  0.881965  0.950059  0.823065  0.999540
fake grape    0.891597  0.942642  0.913904  0.973353  0.999562
real lemon    0.498871  0.665617  0.513268  0.946767  0.998882
fake lemon    0.857829  0.923425  0.993685  0.862532  0.999698
real avocado  0.868328  0.929474  0.894849  0.966995  0.999864
fake avocado  0.622004  0.766910  0.999590  0.622163  0.999548
real pepper   0.785865  0.880045  0.823613  0.944894  0.999058
fake pepper   0.654804  0.791350  0.988962  0.659625  0.999171
real plant    0.871537  0.931310  0.944448  0.918629  0.998646
fake plant    0.845331  0.916134  0.922957  0.909509  0.999868
real banana   0.436975  0.608140  0.818756  0.483770  0.998599
fake banana   0.677367  0.807605  0.759066  0.862890  0.999244
real onion    0.632683  0.774973  0.691533  0.881439  0.999538
fake onion    0.900289  0.947479  0.995473  0.903990  0.999937
real unknown  0.902033  0.948444  0.966337  0.931298  0.999984
fake unknown  0.253148  0.403982  0.267735  0.822890  0.997954
total         0.728674  0.826380  0.874539  0.827260  0.999176
total(-bg)    0.716542  0.818591  0.868952  0.819494  0.999330
2026-09-28 18:30:21,072 - INFO: Epoch accounting: {'epoch': 405, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11431416, 36563, 46572, 148033, 159036, 74875, 67800, 142528, 191695, 54046, 55156, 36886, 28961, 197586, 116086, 189797, 19718, 57823, 44437, 65027, 42210, 4270, 27751], 'crops_with_class': [202, 21, 19, 38, 34, 21, 20, 26, 31, 27, 25, 14, 11, 43, 28, 24, 18, 18, 21, 27, 19, 5, 12], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 9.051311693282169e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005728399018972586, 'train_segmentation_loss': 0.25857008279919036, 'val_foreground_miou_all22': 0.7165417450405986, 'val_psnr_ref1': 38.904726104736326, 'elapsed_seconds': 343.5729703903198, 'peak_cuda_allocated_gib': 7.5095977783203125}

Epoch 406/500 | Batch 10/202 | Rec 0.000640 | Seg 0.332521 | Elapsed 0.2m | ETA 4.1m
Epoch 406/500 | Batch 20/202 | Rec 0.000553 | Seg 0.270581 | Elapsed 0.4m | ETA 3.9m
Epoch 406/500 | Batch 30/202 | Rec 0.000577 | Seg 0.292874 | Elapsed 0.6m | ETA 3.7m
Epoch 406/500 | Batch 40/202 | Rec 0.000575 | Seg 0.285821 | Elapsed 0.9m | ETA 3.5m
Epoch 406/500 | Batch 50/202 | Rec 0.000552 | Seg 0.275216 | Elapsed 1.1m | ETA 3.3m
Epoch 406/500 | Batch 60/202 | Rec 0.000540 | Seg 0.265315 | Elapsed 1.3m | ETA 3.1m
Epoch 406/500 | Batch 70/202 | Rec 0.000545 | Seg 0.256944 | Elapsed 1.5m | ETA 2.8m
Epoch 406/500 | Batch 80/202 | Rec 0.000537 | Seg 0.248408 | Elapsed 1.7m | ETA 2.6m
Epoch 406/500 | Batch 90/202 | Rec 0.000539 | Seg 0.244385 | Elapsed 1.9m | ETA 2.4m
Epoch 406/500 | Batch 100/202 | Rec 0.000550 | Seg 0.244847 | Elapsed 2.2m | ETA 2.2m
Epoch 406/500 | Batch 110/202 | Rec 0.000548 | Seg 0.243403 | Elapsed 2.4m | ETA 2.0m
Epoch 406/500 | Batch 120/202 | Rec 0.000553 | Seg 0.250198 | Elapsed 2.6m | ETA 1.8m
Epoch 406/500 | Batch 130/202 | Rec 0.000550 | Seg 0.250712 | Elapsed 2.8m | ETA 1.5m
Epoch 406/500 | Batch 140/202 | Rec 0.000548 | Seg 0.248490 | Elapsed 3.0m | ETA 1.3m
Epoch 406/500 | Batch 150/202 | Rec 0.000544 | Seg 0.248578 | Elapsed 3.2m | ETA 1.1m
Epoch 406/500 | Batch 160/202 | Rec 0.000558 | Seg 0.250513 | Elapsed 3.4m | ETA 0.9m
Epoch 406/500 | Batch 170/202 | Rec 0.000556 | Seg 0.249100 | Elapsed 3.7m | ETA 0.7m
Epoch 406/500 | Batch 180/202 | Rec 0.000554 | Seg 0.250068 | Elapsed 3.9m | ETA 0.5m
Epoch 406/500 | Batch 190/202 | Rec 0.000553 | Seg 0.247848 | Elapsed 4.1m | ETA 0.3m
Epoch 406/500 | Batch 200/202 | Rec 0.000548 | Seg 0.244356 | Elapsed 4.3m | ETA 0.0m
Epoch 406/500 | Batch 202/202 | Rec 0.000551 | Seg 0.245209 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:34:42,432 - INFO: Rec loss: 0.0005511276963936847
2026-09-28 18:34:42,432 - INFO: Seg loss: 0.24520928329686717
2026-09-28 18:34:42,432 - INFO: λ_rec: 1
2026-09-28 18:34:42,432 - INFO: λ_seg: 0.0001
2026-09-28 18:36:04,480 - INFO: -------------------Epoch: 406------------------------
2026-09-28 18:36:04,485 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.043631  0.974851  0.00013
2026-09-28 18:36:04,491 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995613  0.997752  0.997212  0.998392  0.995812
real potato   0.408230  0.579736  0.975860  0.412395  0.999285
fake potato   0.666391  0.799753  0.981419  0.674906  0.999754
real apple    0.686055  0.813749  0.790217  0.838832  0.998676
fake apple    0.576335  0.731188  0.991695  0.579130  0.998393
real orange   0.955220  0.977047  0.993891  0.960861  0.999941
fake orange   0.949860  0.974235  0.973197  0.975376  0.999853
real grape    0.831370  0.907872  0.959622  0.861507  0.999635
fake grape    0.902511  0.948708  0.924667  0.974137  0.999611
real lemon    0.535343  0.697313  0.548615  0.956764  0.999024
fake lemon    0.858294  0.923695  0.997491  0.860151  0.999700
real avocado  0.842257  0.914325  0.872131  0.960920  0.999833
fake avocado  0.791943  0.883844  0.999678  0.792145  0.999751
real pepper   0.791337  0.883466  0.830689  0.943517  0.999090
fake pepper   0.656815  0.792817  0.967712  0.671532  0.999164
real plant    0.867891  0.929224  0.959420  0.900964  0.998628
fake plant    0.893026  0.943440  0.944306  0.942676  0.999910
real banana   0.499658  0.666315  0.853703  0.546448  0.998770
fake banana   0.700454  0.823794  0.782252  0.870106  0.999315
real onion    0.653823  0.790632  0.693267  0.919946  0.999560
fake onion    0.924447  0.960690  0.994564  0.929141  0.999952
real unknown  0.678969  0.808744  0.715334  0.930343  0.999930
fake unknown  0.204982  0.340188  0.222050  0.727273  0.997623
total         0.733514  0.829936  0.868217  0.835977  0.999183
total(-bg)    0.721601  0.822308  0.862354  0.828594  0.999336
2026-09-28 18:36:05,025 - INFO: Epoch accounting: {'epoch': 406, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11509123, 40195, 32541, 137134, 138501, 67474, 53620, 133584, 183252, 66161, 60645, 33909, 35760, 210116, 120556, 155467, 22669, 55371, 50010, 59527, 43282, 4024, 25351], 'crops_with_class': [202, 20, 16, 34, 33, 17, 20, 24, 31, 30, 21, 12, 14, 47, 28, 19, 20, 17, 21, 26, 19, 4, 12], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 8.874356358056223e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005511276963936847, 'train_segmentation_loss': 0.24520928329686717, 'val_foreground_miou_all22': 0.7216005989458018, 'val_psnr_ref1': 39.04363052368164, 'elapsed_seconds': 343.94419503211975, 'peak_cuda_allocated_gib': 7.510807037353516}

Epoch 407/500 | Batch 10/202 | Rec 0.000555 | Seg 0.293396 | Elapsed 0.2m | ETA 4.1m
Epoch 407/500 | Batch 20/202 | Rec 0.000544 | Seg 0.274017 | Elapsed 0.4m | ETA 3.9m
Epoch 407/500 | Batch 30/202 | Rec 0.000505 | Seg 0.249257 | Elapsed 0.6m | ETA 3.7m
Epoch 407/500 | Batch 40/202 | Rec 0.000521 | Seg 0.253129 | Elapsed 0.9m | ETA 3.5m
Epoch 407/500 | Batch 50/202 | Rec 0.000513 | Seg 0.255787 | Elapsed 1.1m | ETA 3.3m
Epoch 407/500 | Batch 60/202 | Rec 0.000505 | Seg 0.248313 | Elapsed 1.3m | ETA 3.1m
Epoch 407/500 | Batch 70/202 | Rec 0.000502 | Seg 0.239268 | Elapsed 1.5m | ETA 2.8m
Epoch 407/500 | Batch 80/202 | Rec 0.000507 | Seg 0.241207 | Elapsed 1.7m | ETA 2.6m
Epoch 407/500 | Batch 90/202 | Rec 0.000522 | Seg 0.249444 | Elapsed 1.9m | ETA 2.4m
Epoch 407/500 | Batch 100/202 | Rec 0.000542 | Seg 0.253441 | Elapsed 2.2m | ETA 2.2m
Epoch 407/500 | Batch 110/202 | Rec 0.000538 | Seg 0.252531 | Elapsed 2.4m | ETA 2.0m
Epoch 407/500 | Batch 120/202 | Rec 0.000537 | Seg 0.254820 | Elapsed 2.6m | ETA 1.8m
Epoch 407/500 | Batch 130/202 | Rec 0.000537 | Seg 0.253529 | Elapsed 2.8m | ETA 1.6m
Epoch 407/500 | Batch 140/202 | Rec 0.000531 | Seg 0.251602 | Elapsed 3.0m | ETA 1.3m
Epoch 407/500 | Batch 150/202 | Rec 0.000531 | Seg 0.249355 | Elapsed 3.2m | ETA 1.1m
Epoch 407/500 | Batch 160/202 | Rec 0.000546 | Seg 0.251617 | Elapsed 3.4m | ETA 0.9m
Epoch 407/500 | Batch 170/202 | Rec 0.000549 | Seg 0.253558 | Elapsed 3.7m | ETA 0.7m
Epoch 407/500 | Batch 180/202 | Rec 0.000560 | Seg 0.251868 | Elapsed 3.9m | ETA 0.5m
Epoch 407/500 | Batch 190/202 | Rec 0.000567 | Seg 0.254586 | Elapsed 4.1m | ETA 0.3m
Epoch 407/500 | Batch 200/202 | Rec 0.000565 | Seg 0.254180 | Elapsed 4.3m | ETA 0.0m
Epoch 407/500 | Batch 202/202 | Rec 0.000566 | Seg 0.254829 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:40:26,318 - INFO: Rec loss: 0.0005660859151428685
2026-09-28 18:40:26,318 - INFO: Seg loss: 0.25482889083168
2026-09-28 18:40:26,318 - INFO: λ_rec: 1
2026-09-28 18:40:26,318 - INFO: λ_seg: 0.0001
2026-09-28 18:41:44,070 - INFO: -------------------Epoch: 407------------------------
2026-09-28 18:41:44,074 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.168631  0.975244  0.000127
2026-09-28 18:41:44,080 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995708  0.997799  0.997109  0.998590  0.995902
real potato   0.901627  0.948219  0.957013  0.939684  0.999877
fake potato   0.961175  0.980153  0.980306  0.980101  0.999971
real apple    0.806983  0.893133  0.955868  0.838213  0.999308
fake apple    0.554379  0.713266  0.993434  0.556418  0.998311
real orange   0.873606  0.932490  0.992293  0.879574  0.999832
fake orange   0.914015  0.955026  0.934333  0.976762  0.999737
real grape    0.813780  0.897281  0.945677  0.853687  0.999592
fake grape    0.902962  0.948957  0.931786  0.966877  0.999616
real lemon    0.782576  0.877979  0.817530  0.948195  0.999690
fake lemon    0.847882  0.917630  0.994527  0.851857  0.999677
real avocado  0.896939  0.945620  0.934156  0.957471  0.999898
fake avocado  0.747450  0.855426  0.999659  0.747641  0.999698
real pepper   0.789551  0.882352  0.814044  0.963291  0.999061
fake pepper   0.617914  0.763792  0.934018  0.646117  0.999048
real plant    0.868084  0.929335  0.962967  0.898066  0.998635
fake plant    0.847784  0.917573  0.907557  0.927914  0.999867
real banana   0.760490  0.863903  0.891441  0.838109  0.999407
fake banana   0.723397  0.839451  0.812495  0.868364  0.999389
real onion    0.656937  0.792905  0.686296  0.938862  0.999557
fake onion    0.939451  0.968730  0.977122  0.960580  0.999961
real unknown  0.748638  0.856203  0.802335  0.917939  0.999951
fake unknown  0.216828  0.356344  0.240833  0.685078  0.997915
total         0.789920  0.871025  0.889687  0.875626  0.999300
total(-bg)    0.780566  0.865262  0.884804  0.870036  0.999454
2026-09-28 18:41:44,919 - INFO: Epoch accounting: {'epoch': 407, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11436893, 41230, 47347, 151514, 130380, 80748, 72968, 126729, 194621, 52934, 53980, 37606, 30173, 217565, 112953, 198227, 15450, 55355, 44446, 73489, 36797, 4951, 21916], 'crops_with_class': [202, 24, 21, 40, 32, 21, 22, 25, 32, 25, 22, 14, 10, 47, 26, 22, 12, 17, 21, 26, 17, 5, 10], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 8.699029527608837e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005660859151428685, 'train_segmentation_loss': 0.25482889083168, 'val_foreground_miou_all22': 0.7805658898746034, 'val_psnr_ref1': 39.168630828857424, 'elapsed_seconds': 339.8847622871399, 'peak_cuda_allocated_gib': 7.515201568603516}

Epoch 408/500 | Batch 10/202 | Rec 0.000583 | Seg 0.252736 | Elapsed 0.2m | ETA 4.2m
Epoch 408/500 | Batch 20/202 | Rec 0.000549 | Seg 0.250809 | Elapsed 0.4m | ETA 3.9m
Epoch 408/500 | Batch 30/202 | Rec 0.000544 | Seg 0.251650 | Elapsed 0.6m | ETA 3.7m
Epoch 408/500 | Batch 40/202 | Rec 0.000536 | Seg 0.243649 | Elapsed 0.9m | ETA 3.5m
Epoch 408/500 | Batch 50/202 | Rec 0.000524 | Seg 0.246660 | Elapsed 1.1m | ETA 3.3m
Epoch 408/500 | Batch 60/202 | Rec 0.000542 | Seg 0.256794 | Elapsed 1.3m | ETA 3.1m
Epoch 408/500 | Batch 70/202 | Rec 0.000536 | Seg 0.259682 | Elapsed 1.5m | ETA 2.8m
Epoch 408/500 | Batch 80/202 | Rec 0.000551 | Seg 0.268739 | Elapsed 1.7m | ETA 2.6m
Epoch 408/500 | Batch 90/202 | Rec 0.000546 | Seg 0.267187 | Elapsed 1.9m | ETA 2.4m
Epoch 408/500 | Batch 100/202 | Rec 0.000537 | Seg 0.261171 | Elapsed 2.2m | ETA 2.2m
Epoch 408/500 | Batch 110/202 | Rec 0.000535 | Seg 0.260862 | Elapsed 2.4m | ETA 2.0m
Epoch 408/500 | Batch 120/202 | Rec 0.000532 | Seg 0.258651 | Elapsed 2.6m | ETA 1.8m
Epoch 408/500 | Batch 130/202 | Rec 0.000543 | Seg 0.252719 | Elapsed 2.8m | ETA 1.6m
Epoch 408/500 | Batch 140/202 | Rec 0.000544 | Seg 0.249336 | Elapsed 3.0m | ETA 1.3m
Epoch 408/500 | Batch 150/202 | Rec 0.000554 | Seg 0.251852 | Elapsed 3.2m | ETA 1.1m
Epoch 408/500 | Batch 160/202 | Rec 0.000558 | Seg 0.251883 | Elapsed 3.5m | ETA 0.9m
Epoch 408/500 | Batch 170/202 | Rec 0.000560 | Seg 0.252924 | Elapsed 3.7m | ETA 0.7m
Epoch 408/500 | Batch 180/202 | Rec 0.000559 | Seg 0.251400 | Elapsed 3.9m | ETA 0.5m
Epoch 408/500 | Batch 190/202 | Rec 0.000564 | Seg 0.249824 | Elapsed 4.1m | ETA 0.3m
Epoch 408/500 | Batch 200/202 | Rec 0.000563 | Seg 0.248912 | Elapsed 4.3m | ETA 0.0m
Epoch 408/500 | Batch 202/202 | Rec 0.000562 | Seg 0.248717 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:46:06,766 - INFO: Rec loss: 0.0005616162978383565
2026-09-28 18:46:06,766 - INFO: Seg loss: 0.24871681165872234
2026-09-28 18:46:06,766 - INFO: λ_rec: 1
2026-09-28 18:46:06,766 - INFO: λ_seg: 0.0001
2026-09-28 18:47:22,086 - INFO: -------------------Epoch: 408------------------------
2026-09-28 18:47:22,089 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.078745  0.975058  0.00013
2026-09-28 18:47:22,096 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995516  0.997703  0.997055  0.998452  0.995718
real potato   0.351313  0.519920  1.000000  0.351313  0.999224
fake potato   0.649656  0.787578  0.991418  0.653331  0.999743
real apple    0.676216  0.806787  0.748647  0.874834  0.998555
fake apple    0.626777  0.770528  0.994694  0.628880  0.998586
real orange   0.934207  0.965935  0.992910  0.940482  0.999913
fake orange   0.936321  0.967063  0.963253  0.971005  0.999811
real grape    0.843765  0.915213  0.938013  0.893591  0.999655
fake grape    0.889910  0.941699  0.914536  0.970631  0.999556
real lemon    0.526786  0.690013  0.542270  0.948585  0.998999
fake lemon    0.850661  0.919256  0.996379  0.853300  0.999683
real avocado  0.809846  0.894884  0.834826  0.964368  0.999790
fake avocado  0.523907  0.687539  0.999757  0.523973  0.999430
real pepper   0.765210  0.866940  0.802428  0.942850  0.998942
fake pepper   0.583596  0.737004  0.946396  0.603547  0.998974
real plant    0.870444  0.930685  0.962593  0.900918  0.998659
fake plant    0.763817  0.866046  0.825061  0.911426  0.999776
real banana   0.500882  0.667402  0.827191  0.559419  0.998747
fake banana   0.731474  0.844865  0.826836  0.863802  0.999417
real onion    0.585580  0.738583  0.800197  0.685864  0.999561
fake onion    0.931731  0.964609  0.993591  0.937364  0.999957
real unknown  0.901717  0.948269  1.000000  0.901717  0.999984
fake unknown  0.194373  0.325445  0.213270  0.686889  0.997601
total         0.714944  0.815390  0.874405  0.807241  0.999143
total(-bg)    0.702191  0.807103  0.868830  0.798549  0.999298
2026-09-28 18:47:22,615 - INFO: Epoch accounting: {'epoch': 408, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11499175, 38719, 49557, 150106, 130787, 73626, 66605, 149862, 176725, 61181, 51054, 37916, 31771, 193705, 112823, 168384, 19400, 53470, 44838, 63408, 35583, 3750, 25827], 'crops_with_class': [202, 18, 20, 36, 32, 22, 22, 27, 33, 25, 23, 14, 11, 45, 25, 21, 18, 15, 18, 23, 17, 4, 11], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 8.525338123543067e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005616162978383565, 'train_segmentation_loss': 0.24871681165872234, 'val_foreground_miou_all22': 0.7021905532822942, 'val_psnr_ref1': 39.07874450683594, 'elapsed_seconds': 337.68725419044495, 'peak_cuda_allocated_gib': 7.510288238525391}

Epoch 409/500 | Batch 10/202 | Rec 0.000645 | Seg 0.271169 | Elapsed 0.2m | ETA 4.1m
Epoch 409/500 | Batch 20/202 | Rec 0.000649 | Seg 0.289780 | Elapsed 0.4m | ETA 3.9m
Epoch 409/500 | Batch 30/202 | Rec 0.000623 | Seg 0.269378 | Elapsed 0.6m | ETA 3.7m
Epoch 409/500 | Batch 40/202 | Rec 0.000563 | Seg 0.246786 | Elapsed 0.9m | ETA 3.5m
Epoch 409/500 | Batch 50/202 | Rec 0.000575 | Seg 0.253111 | Elapsed 1.1m | ETA 3.3m
Epoch 409/500 | Batch 60/202 | Rec 0.000559 | Seg 0.248329 | Elapsed 1.3m | ETA 3.1m
Epoch 409/500 | Batch 70/202 | Rec 0.000557 | Seg 0.247609 | Elapsed 1.5m | ETA 2.8m
Epoch 409/500 | Batch 80/202 | Rec 0.000559 | Seg 0.248630 | Elapsed 1.7m | ETA 2.6m
Epoch 409/500 | Batch 90/202 | Rec 0.000566 | Seg 0.246805 | Elapsed 1.9m | ETA 2.4m
Epoch 409/500 | Batch 100/202 | Rec 0.000553 | Seg 0.244921 | Elapsed 2.2m | ETA 2.2m
Epoch 409/500 | Batch 110/202 | Rec 0.000560 | Seg 0.249640 | Elapsed 2.4m | ETA 2.0m
Epoch 409/500 | Batch 120/202 | Rec 0.000553 | Seg 0.250101 | Elapsed 2.6m | ETA 1.8m
Epoch 409/500 | Batch 130/202 | Rec 0.000541 | Seg 0.245806 | Elapsed 2.8m | ETA 1.6m
Epoch 409/500 | Batch 140/202 | Rec 0.000536 | Seg 0.244698 | Elapsed 3.0m | ETA 1.3m
Epoch 409/500 | Batch 150/202 | Rec 0.000546 | Seg 0.248208 | Elapsed 3.2m | ETA 1.1m
Epoch 409/500 | Batch 160/202 | Rec 0.000545 | Seg 0.248265 | Elapsed 3.5m | ETA 0.9m
Epoch 409/500 | Batch 170/202 | Rec 0.000552 | Seg 0.249265 | Elapsed 3.7m | ETA 0.7m
Epoch 409/500 | Batch 180/202 | Rec 0.000552 | Seg 0.250282 | Elapsed 3.9m | ETA 0.5m
Epoch 409/500 | Batch 190/202 | Rec 0.000551 | Seg 0.250612 | Elapsed 4.1m | ETA 0.3m
Epoch 409/500 | Batch 200/202 | Rec 0.000564 | Seg 0.249739 | Elapsed 4.3m | ETA 0.0m
Epoch 409/500 | Batch 202/202 | Rec 0.000565 | Seg 0.250935 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:51:45,514 - INFO: Rec loss: 0.0005653020903487727
2026-09-28 18:51:45,514 - INFO: Seg loss: 0.2509350835318022
2026-09-28 18:51:45,514 - INFO: λ_rec: 1
2026-09-28 18:51:45,514 - INFO: λ_seg: 0.0001
2026-09-28 18:53:02,404 - INFO: -------------------Epoch: 409------------------------
2026-09-28 18:53:02,408 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.168376  0.974814  0.000126
2026-09-28 18:53:02,415 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995620  0.997755  0.996894  0.998718  0.995817
real potato   0.403025  0.574467  0.991867  0.404361  0.999283
fake potato   0.671210  0.803214  0.979506  0.680771  0.999757
real apple    0.691857  0.817817  0.773753  0.867315  0.998667
fake apple    0.619591  0.765073  0.984919  0.625525  0.998550
real orange   0.939751  0.968890  0.996573  0.942798  0.999920
fake orange   0.940114  0.969083  0.972723  0.965569  0.999824
real grape    0.829397  0.906694  0.972232  0.849521  0.999635
fake grape    0.891912  0.942818  0.931279  0.954750  0.999572
real lemon    0.450968  0.621566  0.464235  0.940405  0.998654
fake lemon    0.850246  0.919013  0.985311  0.861161  0.999679
real avocado  0.775689  0.873627  0.800273  0.961905  0.999742
fake avocado  0.748376  0.856032  0.998810  0.749044  0.999699
real pepper   0.797435  0.887254  0.849468  0.928667  0.999137
fake pepper   0.659721  0.794930  0.935453  0.691185  0.999150
real plant    0.868228  0.929417  0.959556  0.901208  0.998632
fake plant    0.741796  0.851710  0.818005  0.888420  0.999754
real banana   0.350783  0.519335  0.856563  0.372674  0.998450
fake banana   0.714375  0.833344  0.810311  0.857830  0.999369
real onion    0.626519  0.770330  0.741830  0.801216  0.999568
fake onion    0.922948  0.959880  0.988721  0.932769  0.999951
real unknown  0.901211  0.947989  0.974798  0.922710  0.999984
fake unknown  0.221644  0.362823  0.245612  0.694314  0.997946
total         0.722279  0.820568  0.870813  0.817080  0.999163
total(-bg)    0.709854  0.812514  0.865082  0.808824  0.999315
2026-09-28 18:53:02,939 - INFO: Epoch accounting: {'epoch': 409, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11448269, 41236, 40528, 161396, 133455, 78591, 67854, 121694, 191576, 68337, 62441, 42888, 37432, 212655, 120667, 158503, 22974, 50458, 51882, 63561, 35759, 4024, 22092], 'crops_with_class': [202, 23, 18, 37, 33, 21, 24, 26, 34, 29, 23, 14, 13, 48, 26, 18, 18, 18, 20, 26, 18, 4, 10], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 8.353289002898174e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005653020903487727, 'train_segmentation_loss': 0.2509350835318022, 'val_foreground_miou_all22': 0.7098543541381629, 'val_psnr_ref1': 39.16837646484375, 'elapsed_seconds': 340.31592178344727, 'peak_cuda_allocated_gib': 7.509220123291016}

Epoch 410/500 | Batch 10/202 | Rec 0.000469 | Seg 0.227707 | Elapsed 0.2m | ETA 4.2m
Epoch 410/500 | Batch 20/202 | Rec 0.000612 | Seg 0.249492 | Elapsed 0.4m | ETA 4.0m
Epoch 410/500 | Batch 30/202 | Rec 0.000600 | Seg 0.269740 | Elapsed 0.7m | ETA 3.8m
Epoch 410/500 | Batch 40/202 | Rec 0.000590 | Seg 0.253997 | Elapsed 0.9m | ETA 3.6m
Epoch 410/500 | Batch 50/202 | Rec 0.000574 | Seg 0.250596 | Elapsed 1.1m | ETA 3.3m
Epoch 410/500 | Batch 60/202 | Rec 0.000570 | Seg 0.251391 | Elapsed 1.3m | ETA 3.1m
Epoch 410/500 | Batch 70/202 | Rec 0.000556 | Seg 0.245942 | Elapsed 1.5m | ETA 2.9m
Epoch 410/500 | Batch 80/202 | Rec 0.000556 | Seg 0.251102 | Elapsed 1.8m | ETA 2.7m
Epoch 410/500 | Batch 90/202 | Rec 0.000562 | Seg 0.254305 | Elapsed 2.0m | ETA 2.5m
Epoch 410/500 | Batch 100/202 | Rec 0.000574 | Seg 0.264670 | Elapsed 2.2m | ETA 2.2m
Epoch 410/500 | Batch 110/202 | Rec 0.000572 | Seg 0.259989 | Elapsed 2.4m | ETA 2.0m
Epoch 410/500 | Batch 120/202 | Rec 0.000575 | Seg 0.263555 | Elapsed 2.6m | ETA 1.8m
Epoch 410/500 | Batch 130/202 | Rec 0.000584 | Seg 0.268037 | Elapsed 2.8m | ETA 1.6m
Epoch 410/500 | Batch 140/202 | Rec 0.000581 | Seg 0.268989 | Elapsed 3.1m | ETA 1.4m
Epoch 410/500 | Batch 150/202 | Rec 0.000577 | Seg 0.267019 | Elapsed 3.3m | ETA 1.1m
Epoch 410/500 | Batch 160/202 | Rec 0.000568 | Seg 0.260052 | Elapsed 3.5m | ETA 0.9m
Epoch 410/500 | Batch 170/202 | Rec 0.000562 | Seg 0.256915 | Elapsed 3.7m | ETA 0.7m
Epoch 410/500 | Batch 180/202 | Rec 0.000563 | Seg 0.258829 | Elapsed 3.9m | ETA 0.5m
Epoch 410/500 | Batch 190/202 | Rec 0.000555 | Seg 0.254526 | Elapsed 4.2m | ETA 0.3m
Epoch 410/500 | Batch 200/202 | Rec 0.000556 | Seg 0.253080 | Elapsed 4.4m | ETA 0.0m
Epoch 410/500 | Batch 202/202 | Rec 0.000554 | Seg 0.252666 | Elapsed 4.4m | ETA 0.0m

2026-09-28 18:57:28,382 - INFO: Rec loss: 0.0005538568676807825
2026-09-28 18:57:28,382 - INFO: Seg loss: 0.2526660769956537
2026-09-28 18:57:28,382 - INFO: λ_rec: 1
2026-09-28 18:57:28,382 - INFO: λ_seg: 0.0001
2026-09-28 18:58:46,356 - INFO: -------------------Epoch: 410------------------------
2026-09-28 18:58:46,360 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.100583  0.974863  0.000129
2026-09-28 18:58:46,366 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995632  0.997761  0.997073  0.998551  0.995830
real potato   0.408564  0.580073  0.970676  0.413670  0.999283
fake potato   0.665630  0.799205  0.984667  0.672602  0.999754
real apple    0.687482  0.814752  0.784343  0.847722  0.998671
fake apple    0.634792  0.776555  0.992206  0.637973  0.998614
real orange   0.948697  0.973623  0.995403  0.952872  0.999932
fake orange   0.945598  0.971988  0.970412  0.973670  0.999840
real grape    0.809003  0.894368  0.926730  0.864284  0.999574
fake grape    0.901346  0.948064  0.930256  0.966671  0.999609
real lemon    0.427829  0.599229  0.437407  0.951311  0.998505
fake lemon    0.849975  0.918855  0.996125  0.852795  0.999682
real avocado  0.839629  0.912775  0.864270  0.967159  0.999828
fake avocado  0.760800  0.864104  0.999163  0.761285  0.999714
real pepper   0.765984  0.867437  0.799178  0.948565  0.998940
fake pepper   0.568058  0.724490  0.941550  0.588823  0.998933
real plant    0.871515  0.931297  0.954784  0.909034  0.998660
fake plant    0.770222  0.870149  0.828423  0.916411  0.999782
real banana   0.283926  0.442237  0.794263  0.306465  0.998263
fake banana   0.738296  0.849398  0.856613  0.842402  0.999451
real onion    0.626075  0.769995  0.713606  0.836176  0.999549
fake onion    0.912319  0.954099  0.998678  0.913422  0.999945
real unknown  0.645097  0.784217  0.681946  0.922710  0.999919
fake unknown  0.224293  0.366366  0.247125  0.708258  0.997936
total         0.707859  0.809176  0.854995  0.815340  0.999140
total(-bg)    0.694779  0.800603  0.848537  0.807013  0.999290
2026-09-28 18:58:46,909 - INFO: Epoch accounting: {'epoch': 410, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'baseline', 'class_pixels_seen': [11467426, 38472, 41324, 141220, 150187, 84046, 57915, 136633, 167927, 56070, 59508, 41206, 29639, 209101, 101362, 176731, 21697, 69211, 48981, 65395, 42930, 5253, 26038], 'crops_with_class': [202, 22, 19, 36, 33, 21, 19, 26, 32, 27, 21, 15, 12, 46, 26, 21, 20, 18, 20, 26, 20, 6, 12], 'targeted_crops_by_class': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'sampled_scene_counts': None, 'learning_rate': 8.182888957878807e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005538568676807825, 'train_segmentation_loss': 0.2526660769956537, 'val_foreground_miou_all22': 0.694778666017799, 'val_psnr_ref1': 39.1005825805664, 'elapsed_seconds': 343.9612398147583, 'peak_cuda_allocated_gib': 7.509342193603516}

Stopped after epoch 410; scheduler horizon remains 500
Download: /kaggle/working/paired_sampling_epoch400_20260928_170349_original_sampler.zip

/kaggle/working/paired_sampling_epoch400_20260928_170349_original_sampler.zip

In [4]:
import statistics
import pandas as pd
results={};target_rows=[]
for name in ARMS:
    records=[json.loads((PAIR_RUN/name/'result'/f'epoch_{e:04d}_training.json').read_text()) for e in range(401,411)]
    assert all(r['attempted_updates']==202 for r in records)
    vals=[r['val_foreground_miou_all22'] for r in records]
    results[name]={'final':records[-1],'epochs':records,
        'best_logged_continuation_miou':max(vals),'mean_last5_miou':statistics.mean(vals[-5:]),
        'std_last5_miou':statistics.pstdev(vals[-5:]),
        'mean_last5_psnr':statistics.mean(r['val_psnr_ref1'] for r in records[-5:]),
        'actual_updates':sum(r['optimizer_updates'] for r in records),
        'amp_skips':sum(r['amp_skipped_updates'] for r in records)}
    for e in range(401,411):
        table=pd.read_csv(PAIR_RUN/name/'result'/f'epoch_{e:04d}_segmentation.csv',index_col=0)
        for cls in ['fake apple','fake avocado','fake unknown']:
            target_rows.append({'arm':name,'epoch':e,'class':cls,**{m:float(table.loc[cls,m]) for m in ['IoU','Prec','recall']}})
summary={'experiment':manifest,'arms':results}
(PAIR_RUN/'comparison_summary.json').write_text(json.dumps(summary,indent=2))
targets=pd.DataFrame(target_rows);targets.to_csv(PAIR_RUN/'target_class_metrics.csv',index=False)
for name,record in results.items():print(name,json.dumps({k:v for k,v in record.items() if k!='epochs'},indent=2))
display(targets[targets.epoch>=406].groupby(['arm','class'])[['IoU','Prec','recall']].mean()*100)
backup('complete')

balanced_control {
  "final": {
    "epoch": 410,
    "scheduler_horizon": 500,
    "lambda_rec": 1,
    "lambda_seg": 0.0001,
    "sampling_policy": "balanced50_v1",
    "class_pixels_seen": [
      11286628,
      60592,
      74237,
      105051,
      122136,
      86597,
      63851,
      188440,
      198800,
      79058,
      46398,
      46062,
      44529,
      210090,
      131325,
      123229,
      25248,
      74982,
      70809,
      79116,
      50933,
      13406,
      56755
    ],
    "crops_with_class": [
      202,
      36,
      31,
      28,
      29,
      24,
      23,
      33,
      36,
      33,
      25,
      16,
      16,
      53,
      29,
      19,
      23,
      23,
      32,
      35,
      26,
      13,
      22
    ],
    "targeted_crops_by_class": [
      0,
      3,
      5,
      2,
      1,
      4,
      7,
      10,
      3,
      3,
      6,
      5,
      2,
      7,
      5,
      7,
      4,
      3,
      2,
      4,
      6,
      6,
      4
    ],
    "sampled_scene_counts": [
      1,
      1,
      1,
      0,
      1,
      1,
      0,
      0,
      1,
      2,
      1,
      1,
      0,
      1,
      1,
      0,
      0,
      1,
      1,
      2,
      0,
      0,
      1,
      0,
      0,
      0,
      2,
      2,
      1,
      1,
      0,
      1,
      0,
      0,
      2,
      1,
      1,
      0,
      1,
      2,
      0,
      1,
      1,
      2,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      1,
      1,
      1,
      0,
      1,
      1,
      0,
      1,
      2,
      1,
      1,
      1,
      0,
      2,
      0,
      1,
      0,
      2,
      3,
      0,
      0,
      2,
      2,
      0,
      1,
      0,
      0,
      2,
      3,
      0,
      1,
      1,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      1,
      1,
      2,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0,
      2,
      0,
      2,
      1,
      1,
      1,
      2,
      1,
      4,
      1,
      0,
      0,
      2,
      2,
      0,
      0,
      1,
      2,
      1,
      1,
      2,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      2,
      0,
      3,
      1,
      1,
      1,
      3,
      2,
      0,
      1,
      4,
      2,
      3,
      2,
      2,
      0,
      1,
      2,
      2,
      0,
      1,
      2,
      0,
      0,
      1,
      3,
      1,
      2,
      1,
      1,
      0,
      1,
      1,
      1,
      2,
      2,
      2,
      1,
      3,
      3,
      2,
      2,
      2,
      0,
      1,
      0,
      1,
      3,
      2,
      4,
      0,
      0,
      2
    ],
    "learning_rate": 8.182888957878807e-06,
    "attempted_updates": 202,
    "optimizer_updates": 202,
    "amp_skipped_updates": 0,
    "train_reconstruction_loss": 0.000576575547612346,
    "train_segmentation_loss": 0.2780458528437827,
    "val_foreground_miou_all22": 0.7183458007231032,
    "val_psnr_ref1": 39.03679138183594,
    "elapsed_seconds": 327.2691626548767,
    "peak_cuda_allocated_gib": 7.510044097900391
  },
  "best_logged_continuation_miou": 0.7773877742924625,
  "mean_last5_miou": 0.7476798171127785,
  "std_last5_miou": 0.02408154222986388,
  "mean_last5_psnr": 39.07667437744141,
  "actual_updates": 2019,
  "amp_skips": 1
}
original_sampler {
  "final": {
    "epoch": 410,
    "scheduler_horizon": 500,
    "lambda_rec": 1,
    "lambda_seg": 0.0001,
    "sampling_policy": "baseline",
    "class_pixels_seen": [
      11467426,
      38472,
      41324,
      141220,
      150187,
      84046,
      57915,
      136633,
      167927,
      56070,
      59508,
      41206,
      29639,
      209101,
      101362,
      176731,
      21697,
      69211,
      48981,
      65395,
      42930,
      5253,
      26038
    ],
    "crops_with_class": [
      202,
      22,
      19,
      36,
      33,
      21,
      19,
      26,
      32,
      27,
      21,
      15,
      12,
      46,
      26,
      21,
      20,
      18,
      20,
      26,
      20,
      6,
      12
    ],
    "targeted_crops_by_class": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "sampled_scene_counts": null,
    "learning_rate": 8.182888957878807e-06,
    "attempted_updates": 202,
    "optimizer_updates": 202,
    "amp_skipped_updates": 0,
    "train_reconstruction_loss": 0.0005538568676807825,
    "train_segmentation_loss": 0.2526660769956537,
    "val_foreground_miou_all22": 0.694778666017799,
    "val_psnr_ref1": 39.1005825805664,
    "elapsed_seconds": 343.9612398147583,
    "peak_cuda_allocated_gib": 7.509342193603516
  },
  "best_logged_continuation_miou": 0.7805658898746034,
  "mean_last5_miou": 0.7217980124517323,
  "std_last5_miou": 0.030694790761923458,
  "mean_last5_psnr": 39.111992980957034,
  "actual_updates": 2019,
  "amp_skips": 1
}

                                     IoU       Prec     recall
arm              class
balanced_control fake apple    57.222719  98.637476  57.711768
                 fake avocado  68.228852  99.970065  68.242794
                 fake unknown  21.723851  23.722397  71.825424
original_sampler fake apple    60.237481  99.138976  60.558519
                 fake avocado  71.449514  99.941333  71.481764
                 fake unknown  21.242406  23.377785  70.036217

Download: /kaggle/working/paired_sampling_epoch400_20260928_170349_complete.zip

/kaggle/working/paired_sampling_epoch400_20260928_170349_complete.zip

In [1]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch

EXPECTED_410='d9cc528d220f7918989a643d8d57c1c2f4811a74fb9122cdff54569ef93bac8a'
HISTORY={'checkpoint_hashes': {'last.pt': '0f81dc6ed10ab91f4f07d0c1df39b0faf6c84aebf519cbde837d803f53defa90', 'best_iou.pth': '89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c', 'best_psnr.pth': '10a193a52834b1813fb856df6b3b5992f2f62cd19ad09414ae04447acedb9133'}, 'best_iou': {'epoch': 278, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11283155, 47213, 47095, 129119, 174675, 62551, 38383, 151141, 165696, 89935, 71339, 60422, 33207, 227434, 153331, 175570, 27755, 65024, 51386, 79550, 56302, 8225, 39764], 'crops_with_class': [202, 29, 23, 37, 45, 20, 17, 27, 33, 36, 25, 22, 11, 55, 34, 24, 24, 18, 24, 34, 24, 11, 19], 'targeted_crops_by_class': [0, 3, 6, 6, 5, 3, 6, 4, 5, 4, 8, 7, 6, 2, 5, 5, 4, 5, 6, 4, 6, 4, 3], 'sampled_scene_counts': [1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 3, 0, 1, 1, 1, 0, 1, 3, 1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 2, 0, 2, 1, 3, 2, 2, 1, 1, 2, 4, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 3, 1, 1, 3, 0, 1, 0, 3, 0, 1, 3, 1, 1, 2, 3, 3, 1, 1, 0, 3, 1, 0, 1, 3, 1, 1, 0, 3, 4, 2, 0, 1, 2, 0, 1, 3, 2, 1, 0, 1, 0, 0, 0, 2, 1, 2, 0, 0, 3, 1, 0, 3, 1, 0, 0, 1, 2, 3, 1, 0, 0, 2, 0, 4, 2, 1], 'learning_rate': 4.1704431944952346e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006899012645734197, 'train_segmentation_loss': 0.3116034334617676, 'val_foreground_miou_all22': 0.7862424401936461, 'val_psnr_ref1': 38.36915969848633, 'elapsed_seconds': 317.5734043121338, 'peak_cuda_allocated_gib': 7.509799957275391}, 'best_psnr': {'epoch': 398, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11258028, 52003, 71103, 106599, 148359, 78870, 60312, 174631, 155758, 80633, 59873, 24017, 29595, 273997, 155726, 157205, 26182, 72694, 86353, 48206, 46898, 12224, 59006], 'crops_with_class': [202, 30, 30, 29, 40, 23, 21, 31, 41, 32, 25, 9, 15, 65, 39, 24, 24, 22, 35, 28, 20, 13, 27], 'targeted_crops_by_class': [0, 4, 5, 6, 6, 3, 5, 7, 2, 10, 5, 3, 2, 4, 6, 4, 5, 3, 9, 4, 5, 5, 4], 'sampled_scene_counts': [1, 0, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1, 0, 2, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 1, 2, 2, 3, 3, 0, 0, 1, 1, 3, 2, 1, 2, 1, 1, 3, 3, 1, 4, 2, 1, 0, 1, 4, 1, 3, 1, 1, 6, 2, 2, 1, 3, 0, 2, 1, 0, 1, 1, 1, 0, 1, 1, 3, 2, 1, 0, 0, 3, 1, 2, 3, 2, 2, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 0, 3, 0, 1, 0], 'learning_rate': 1.0335002328013762e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005872207170751148, 'train_segmentation_loss': 0.28119397727717266, 'val_foreground_miou_all22': 0.6764957873477285, 'val_psnr_ref1': 39.16609451293945, 'elapsed_seconds': 332.0243864059448, 'peak_cuda_allocated_gib': 7.511264801025391}}

def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
# Match actual file hashes so multiple attached backups do not select the wrong state.
def locate(relative,expected_hash,label):
    for p in sorted(INPUTS.rglob(relative)):
        if digest(p)==expected_hash:return p
    dest=Path('/kaggle/working')/('restore_'+label)
    restored=dest/relative
    if restored.is_file() and digest(restored)==expected_hash:return restored
    for archive in sorted(INPUTS.rglob('*.zip')):
        if not zipfile.is_zipfile(archive):continue
        with zipfile.ZipFile(archive) as z:
            if relative in z.namelist() and hashlib.sha256(z.read(relative)).hexdigest()==expected_hash:
                safe_extract(z,dest)
                return dest/relative
    raise FileNotFoundError('Attach the required '+label+' backup ZIP.')
PARENT410=locate('paired_sampling_epoch400_20260928_170349/balanced_control/model/last.pt',EXPECTED_410,'paired_epoch410').parent
PARENT400=locate('balanced300_to_epoch400_20260925_173543/model/last.pt',HISTORY['checkpoint_hashes']['last.pt'],'historical_epoch400').parent
DATA=Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(),'Enable GPU.'
state=torch.load(PARENT410/'last.pt',map_location='cpu',weights_only=True)
assert state['epoch']==state['scheduler']['last_epoch']==410
assert state['scheduler']['T_max']==500 and math.isclose(state['scheduler']['eta_min'],2.5e-7)
for k,v in dict(sampling_policy='balanced50_v1',lambda_seg=1e-4,learning_rate=1e-4,max_epoch=500,batch_size=1,workers=0,seed=3407,transpose_image=True,method='CRSDUN',input_setting='Y',input_mask='SSR').items():assert state['config'][k]==v,k
provenance=json.loads((PARENT410.parents[1]/'experiment.json').read_text())
for f,h in provenance['source_sha256'].items():assert digest(CODE/f)==h,f
sys.path.insert(0,str(CODE))
from training_state import identity,atomic_save
from types import SimpleNamespace
assert identity(SimpleNamespace(data_root=DATA,mask_path=CODE/'mask/mask512x512.mat'))==state['data_identity']
subprocess.run([sys.executable,'run_public252.py','--root',str(DATA)],cwd=CODE,check=True)
print('Verified balanced-control epoch410. Saved next LR:',state['optimizer']['param_groups'][0]['lr'])

{
  "protocol": "public252-v1",
  "protocol_sha256": "77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318",
  "preflight": "passed",
  "splits": {
    "train": 202,
    "val": 25,
    "test": 25
  },
  "metrics": {
    "reference_amplitude": 1.0,
    "label": "PSNR_ref1 / SSIM_ref1",
    "meaning": "Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range."
  },
  "training_command": [
    "/usr/bin/python3",
    "train.py",
    "--data_root",
    "/kaggle/input/datasets/arnavnigamd/btp-data/public252/",
    "--transpose_image",
    "--batch_size",
    "1",
    "--max_epoch",
    "500",
    "--name",
    "public252_v1_baseline",
    "--workers",
    "0",
    "--outf",
    "/kaggle/working/BTP-sampling/exp/CRSDUN/"
  ],
  "note": "Header/membership checks plus one training-scene loader check; full pixel audit is recorded separately."
}
Verified balanced-control epoch410. Saved next LR: 8.014144715586987e-06

In [5]:
import torch

assert "PARENT410" in globals(), "Run the setup cell first."
assert digest(PARENT410 / "last.pt") == EXPECTED_410

state = torch.load(
    PARENT410 / "last.pt",
    map_location="cpu",
    weights_only=True,
)
assert state["epoch"] == 410
print("Epoch-410 state reloaded.")

Epoch-410 state reloaded.

In [6]:
import copy

def restore_historical_best(state,history):
    derived=copy.deepcopy(state)
    selected={}
    for metric,record,filename in [('iou','best_iou','best_iou.pth'),('psnr','best_psnr','best_psnr.pth')]:
        field='val_foreground_miou_all22' if metric=='iou' else 'val_psnr_ref1'
        historical_value=history[record][field]
        use_history=historical_value>state['best'][metric]
        selected[filename]='historical' if use_history else 'current'
        derived['best'][metric]=max(state['best'][metric],historical_value)
    return derived,selected

from datetime import datetime
from IPython.display import display,FileLink
import os
if 'CONT410_RUN' not in globals():
    CONT410_RUN=Path('/kaggle/working')/('balanced410_to_epoch500_'+datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT410_RUN.mkdir(exist_ok=False)
SEED=CONT410_RUN/'initial_state'
SEED.mkdir(exist_ok=True)
derived,selected=restore_historical_best(state,HISTORY)
for filename,source in selected.items():
    source_path=(PARENT400 if source=='historical' else PARENT410)/filename
    assert source_path.is_file()
    if source=='historical':assert digest(source_path)==HISTORY['checkpoint_hashes'][filename]
    dest=SEED/filename
    if dest.exists():assert digest(dest)==digest(source_path)
    else:shutil.copy2(source_path,dest)
if not (SEED/'last.pt').exists():atomic_save(derived,SEED/'last.pt')
CHECKPOINT=SEED/'last.pt'
assert torch.load(CHECKPOINT,map_location='cpu',weights_only=True)['best']==derived['best']
manifest={'reference_checkpoint_sha256':EXPECTED_410,'derived_checkpoint_sha256':digest(CHECKPOINT),
    'source_epoch':410,'target_epoch':500,'backup_epochs':[450,500],
    'sampling_policy':'balanced50_v1','lambda_seg':1e-4,
    'source_sha256':provenance['source_sha256'],
    'bookkeeping_change':'Restore the better historical/current best metrics and weights; all other state preserved.',
    'selected_best_sources':selected,'restored_best':derived['best'],
    'note':'Finish fixed500-epoch schedule; not a new method or test result.'}
(CONT410_RUN/'continuation.json').write_text(json.dumps(manifest,indent=2))
shutil.copy2(CODE/'public252-v1.json',CONT410_RUN/'dataset_protocol.json')
print('Restored best tracking:',derived['best'],selected)
del state,derived

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT410_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT410_RUN.parent / (CONT410_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT410_RUN.parent, base_dir=CONT410_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT410_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT410_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target in (450, 500)
    last = CONT410_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT410_RUN.parent) + '/', '--name', CONT410_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT410_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT410_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print(f'Epoch{target} completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT410_RUN)

Restored best tracking: {'iou': 0.7862424401936461, 'psnr': 39.16670852661133} {'best_iou.pth': 'historical', 'best_psnr.pth': 'current'}
Continuation folder: /kaggle/working/balanced410_to_epoch500_20261010_094143

In [7]:
continue_to(450)

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced410_to_epoch500_20261010_094143', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/working/balanced410_to_epoch500_20261010_094143/initial_state/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=450, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-10-10 09:43:46,846 - INFO: Resuming after epoch 410

Epoch 411/500 | Batch 10/202 | Rec 0.000551 | Seg 0.242155 | Elapsed 0.5m | ETA 9.3m
Epoch 411/500 | Batch 20/202 | Rec 0.000539 | Seg 0.258941 | Elapsed 0.7m | ETA 6.6m
Epoch 411/500 | Batch 30/202 | Rec 0.000536 | Seg 0.271960 | Elapsed 0.9m | ETA 5.4m
Epoch 411/500 | Batch 40/202 | Rec 0.000558 | Seg 0.262766 | Elapsed 1.2m | ETA 4.8m
Epoch 411/500 | Batch 50/202 | Rec 0.000547 | Seg 0.254669 | Elapsed 1.4m | ETA 4.3m
Epoch 411/500 | Batch 60/202 | Rec 0.000543 | Seg 0.259818 | Elapsed 1.7m | ETA 3.9m
Epoch 411/500 | Batch 70/202 | Rec 0.000534 | Seg 0.265592 | Elapsed 1.9m | ETA 3.6m
Epoch 411/500 | Batch 80/202 | Rec 0.000517 | Seg 0.253379 | Elapsed 2.1m | ETA 3.3m
Epoch 411/500 | Batch 90/202 | Rec 0.000524 | Seg 0.261083 | Elapsed 2.4m | ETA 3.0m
Epoch 411/500 | Batch 100/202 | Rec 0.000533 | Seg 0.259766 | Elapsed 2.6m | ETA 2.7m
Epoch 411/500 | Batch 110/202 | Rec 0.000531 | Seg 0.260281 | Elapsed 2.9m | ETA 2.4m
Epoch 411/500 | Batch 120/202 | Rec 0.000529 | Seg 0.260067 | Elapsed 3.1m | ETA 2.1m
Epoch 411/500 | Batch 130/202 | Rec 0.000533 | Seg 0.264878 | Elapsed 3.3m | ETA 1.8m
Epoch 411/500 | Batch 140/202 | Rec 0.000536 | Seg 0.269465 | Elapsed 3.5m | ETA 1.6m
Epoch 411/500 | Batch 150/202 | Rec 0.000538 | Seg 0.270211 | Elapsed 3.7m | ETA 1.3m
Epoch 411/500 | Batch 160/202 | Rec 0.000543 | Seg 0.274138 | Elapsed 4.0m | ETA 1.0m
Epoch 411/500 | Batch 170/202 | Rec 0.000549 | Seg 0.277756 | Elapsed 4.2m | ETA 0.8m
Epoch 411/500 | Batch 180/202 | Rec 0.000552 | Seg 0.279417 | Elapsed 4.4m | ETA 0.5m
Epoch 411/500 | Batch 190/202 | Rec 0.000553 | Seg 0.280887 | Elapsed 4.6m | ETA 0.3m
Epoch 411/500 | Batch 200/202 | Rec 0.000551 | Seg 0.279267 | Elapsed 4.9m | ETA 0.0m
Epoch 411/500 | Batch 202/202 | Rec 0.000553 | Seg 0.280258 | Elapsed 4.9m | ETA 0.0m

2026-10-10 09:48:40,570 - INFO: Rec loss: 0.0005531932053266849
2026-10-10 09:48:40,570 - INFO: Seg loss: 0.28025762096858853
2026-10-10 09:48:40,570 - INFO: λ_rec: 1
2026-10-10 09:48:40,570 - INFO: λ_seg: 0.0001
2026-10-10 09:50:04,082 - INFO: -------------------Epoch: 411------------------------
2026-10-10 09:50:04,090 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.995721  0.974909  0.000132
2026-10-10 09:50:04,098 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995807  0.997849  0.997298  0.998501  0.995998
real potato   0.419911  0.591419  0.987179  0.422214  0.999302
fake potato   0.685525  0.813378  0.979640  0.695434  0.999768
real apple    0.717004  0.835130  0.804466  0.868333  0.998818
fake apple    0.610756  0.758299  0.963738  0.625121  0.998496
real orange   0.950704  0.974679  0.996853  0.953566  0.999935
fake orange   0.946251  0.972333  0.966167  0.978680  0.999841
real grape    0.812142  0.896284  0.976810  0.828108  0.999600
fake grape    0.897697  0.946041  0.923621  0.969682  0.999591
real lemon    0.545059  0.705504  0.575743  0.910932  0.999106
fake lemon    0.854366  0.921415  0.989326  0.862315  0.999689
real avocado  0.894110  0.944045  0.926629  0.962233  0.999894
fake avocado  0.665307  0.798972  0.999808  0.665391  0.999599
real pepper   0.813820  0.897305  0.841651  0.960954  0.999196
fake pepper   0.699392  0.823059  0.958089  0.721465  0.999261
real plant    0.874610  0.933061  0.952435  0.914556  0.998689
fake plant    0.836288  0.910796  0.899439  0.922546  0.999856
real banana   0.525506  0.688912  0.880321  0.565938  0.998852
fake banana   0.691046  0.817250  0.790800  0.845637  0.999305
real onion    0.656501  0.792586  0.700596  0.912515  0.999569
fake onion    0.914435  0.955255  0.978691  0.933011  0.999945
real unknown  0.924618  0.960783  1.000000  0.924618  0.999988
fake unknown  0.218408  0.358477  0.236474  0.740855  0.997766
total         0.745620  0.838819  0.883729  0.834026  0.999220
total(-bg)    0.734248  0.831590  0.878567  0.826550  0.999367
2026-10-10 09:50:04,536 - INFO: Epoch accounting: {'epoch': 411, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11242821, 49426, 47840, 149035, 153035, 91336, 81546, 156386, 164632, 97386, 82770, 40336, 37579, 248111, 98757, 189383, 28816, 52061, 48376, 58604, 61476, 12486, 46074], 'crops_with_class': [202, 27, 21, 44, 34, 28, 26, 31, 39, 43, 31, 13, 16, 57, 24, 29, 24, 15, 23, 31, 24, 13, 18], 'targeted_crops_by_class': [0, 3, 4, 6, 3, 7, 3, 6, 4, 6, 6, 2, 9, 4, 4, 10, 5, 1, 4, 5, 3, 8, 3], 'sampled_scene_counts': [1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 2, 2, 2, 2, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 2, 1, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 0, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 1, 1, 2, 1, 0, 1, 0, 0, 0, 1, 3, 0, 0, 0, 0, 1, 1, 1, 1, 0, 3, 1, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 2, 5, 1, 3, 2, 0, 3, 1, 2, 2, 1, 3, 1, 1, 1, 2, 2, 1, 0, 2, 0, 3, 2, 1, 1, 2, 3, 3, 2, 1, 2, 1, 1, 0, 3, 0, 1, 1, 4, 3, 1, 2, 0, 1, 0, 0, 2, 1, 1, 2, 0, 2, 0, 1, 1, 2, 1, 2, 1, 0, 3, 0, 0, 1, 1, 2, 2, 2, 1, 1, 2, 0, 1, 0, 0, 2, 2, 3, 2, 0, 0], 'learning_rate': 8.014144715586987e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005531932053266849, 'train_segmentation_loss': 0.28025762096858853, 'val_foreground_miou_all22': 0.7342479941088054, 'val_psnr_ref1': 38.995721435546876, 'elapsed_seconds': 377.683064699173, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 412/500 | Batch 10/202 | Rec 0.000511 | Seg 0.273241 | Elapsed 0.2m | ETA 4.3m
Epoch 412/500 | Batch 20/202 | Rec 0.000505 | Seg 0.273781 | Elapsed 0.4m | ETA 3.9m
Epoch 412/500 | Batch 30/202 | Rec 0.000505 | Seg 0.255492 | Elapsed 0.6m | ETA 3.7m
Epoch 412/500 | Batch 40/202 | Rec 0.000537 | Seg 0.278229 | Elapsed 0.9m | ETA 3.5m
Epoch 412/500 | Batch 50/202 | Rec 0.000518 | Seg 0.265040 | Elapsed 1.1m | ETA 3.3m
Epoch 412/500 | Batch 60/202 | Rec 0.000519 | Seg 0.263137 | Elapsed 1.3m | ETA 3.1m
Epoch 412/500 | Batch 70/202 | Rec 0.000514 | Seg 0.266639 | Elapsed 1.5m | ETA 2.8m
Epoch 412/500 | Batch 80/202 | Rec 0.000518 | Seg 0.271173 | Elapsed 1.7m | ETA 2.6m
Epoch 412/500 | Batch 90/202 | Rec 0.000501 | Seg 0.260300 | Elapsed 1.9m | ETA 2.4m
Epoch 412/500 | Batch 100/202 | Rec 0.000514 | Seg 0.269820 | Elapsed 2.1m | ETA 2.2m
Epoch 412/500 | Batch 110/202 | Rec 0.000512 | Seg 0.268035 | Elapsed 2.4m | ETA 2.0m
Epoch 412/500 | Batch 120/202 | Rec 0.000530 | Seg 0.271789 | Elapsed 2.6m | ETA 1.8m
Epoch 412/500 | Batch 130/202 | Rec 0.000543 | Seg 0.272002 | Elapsed 2.8m | ETA 1.5m
Epoch 412/500 | Batch 140/202 | Rec 0.000546 | Seg 0.273159 | Elapsed 3.0m | ETA 1.3m
Epoch 412/500 | Batch 150/202 | Rec 0.000557 | Seg 0.280262 | Elapsed 3.2m | ETA 1.1m
Epoch 412/500 | Batch 160/202 | Rec 0.000555 | Seg 0.278627 | Elapsed 3.4m | ETA 0.9m
Epoch 412/500 | Batch 170/202 | Rec 0.000558 | Seg 0.278458 | Elapsed 3.6m | ETA 0.7m
Epoch 412/500 | Batch 180/202 | Rec 0.000571 | Seg 0.284192 | Elapsed 3.9m | ETA 0.5m
Epoch 412/500 | Batch 190/202 | Rec 0.000577 | Seg 0.288193 | Elapsed 4.1m | ETA 0.3m
Epoch 412/500 | Batch 200/202 | Rec 0.000572 | Seg 0.285747 | Elapsed 4.3m | ETA 0.0m
Epoch 412/500 | Batch 202/202 | Rec 0.000571 | Seg 0.285760 | Elapsed 4.3m | ETA 0.0m

2026-10-10 09:54:24,515 - INFO: Rec loss: 0.0005712926015056126
2026-10-10 09:54:24,515 - INFO: Seg loss: 0.28576048068923526
2026-10-10 09:54:24,515 - INFO: λ_rec: 1
2026-10-10 09:54:24,515 - INFO: λ_seg: 0.0001
2026-10-10 09:55:39,275 - INFO: -------------------Epoch: 412------------------------
2026-10-10 09:55:39,279 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.151278  0.975208  0.000127
2026-10-10 09:55:39,285 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995898  0.997895  0.997460  0.998429  0.996085
real potato   0.366998  0.536901  1.000000  0.366998  0.999243
fake potato   0.673708  0.805001  0.997831  0.674696  0.999762
real apple    0.688649  0.815572  0.744981  0.901061  0.998595
fake apple    0.621662  0.766649  0.983056  0.628395  0.998556
real orange   0.896429  0.945336  0.994377  0.900996  0.999863
fake orange   0.926614  0.961859  0.945853  0.978520  0.999778
real grape    0.846504  0.916822  0.953369  0.883067  0.999666
fake grape    0.879762  0.935986  0.893350  0.983005  0.999503
real lemon    0.417222  0.588746  0.426352  0.951181  0.998439
fake lemon    0.866872  0.928639  0.990680  0.873999  0.999716
real avocado  0.816834  0.899134  0.846176  0.959277  0.999800
fake avocado  0.788381  0.881621  0.998870  0.789084  0.999747
real pepper   0.827868  0.905779  0.868281  0.946771  0.999280
fake pepper   0.670280  0.802547  0.946590  0.696626  0.999183
real plant    0.880981  0.936675  0.952073  0.921864  0.998754
fake plant    0.771888  0.871211  0.868687  0.873850  0.999794
real banana   0.257187  0.409110  0.846908  0.269727  0.998250
fake banana   0.719791  0.837018  0.828432  0.845886  0.999394
real onion    0.543352  0.704069  0.751245  0.662557  0.999497
fake onion    0.903389  0.949193  0.993131  0.909069  0.999939
real unknown  0.928503  0.962876  0.998974  0.929389  0.999989
fake unknown  0.226209  0.368919  0.245132  0.745563  0.997851
total         0.718043  0.814242  0.872687  0.812609  0.999160
total(-bg)    0.705413  0.805894  0.867016  0.804163  0.999300
2026-10-10 09:55:39,742 - INFO: Epoch accounting: {'epoch': 412, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11240872, 51456, 65139, 150168, 143157, 113976, 102291, 127189, 158737, 66297, 65996, 39626, 41756, 221287, 108247, 139350, 17620, 95034, 93137, 89281, 52789, 11461, 43406], 'crops_with_class': [202, 26, 32, 43, 39, 32, 34, 26, 29, 38, 24, 16, 18, 57, 30, 19, 15, 27, 33, 37, 30, 14, 18], 'targeted_crops_by_class': [0, 3, 7, 14, 8, 6, 5, 4, 3, 4, 2, 2, 3, 5, 5, 2, 2, 6, 6, 4, 6, 5, 3], 'sampled_scene_counts': [1, 4, 1, 0, 0, 1, 2, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 4, 1, 1, 0, 2, 1, 2, 0, 1, 1, 3, 1, 1, 1, 2, 0, 3, 4, 2, 2, 0, 1, 4, 0, 1, 2, 0, 1, 3, 3, 1, 3, 3, 1, 0, 3, 2, 0, 2, 1, 1, 0, 5, 2, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 1, 1, 2, 3, 2, 2, 1, 2, 3, 3, 1, 1, 1, 0, 2, 1, 3, 1, 1, 3, 2, 2, 2, 2, 1, 0, 3, 0, 1, 1], 'learning_rate': 7.847062937756462e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005712926015056126, 'train_segmentation_loss': 0.28576048068923526, 'val_foreground_miou_all22': 0.7054128665234622, 'val_psnr_ref1': 39.15127838134766, 'elapsed_seconds': 335.1994252204895, 'peak_cuda_allocated_gib': 7.513462066650391}

Epoch 413/500 | Batch 10/202 | Rec 0.000519 | Seg 0.305594 | Elapsed 0.2m | ETA 4.2m
Epoch 413/500 | Batch 20/202 | Rec 0.000555 | Seg 0.310328 | Elapsed 0.4m | ETA 3.8m
Epoch 413/500 | Batch 30/202 | Rec 0.000561 | Seg 0.285545 | Elapsed 0.6m | ETA 3.6m
Epoch 413/500 | Batch 40/202 | Rec 0.000574 | Seg 0.285101 | Elapsed 0.8m | ETA 3.4m
Epoch 413/500 | Batch 50/202 | Rec 0.000592 | Seg 0.281752 | Elapsed 1.1m | ETA 3.2m
Epoch 413/500 | Batch 60/202 | Rec 0.000584 | Seg 0.281236 | Elapsed 1.3m | ETA 3.0m
Epoch 413/500 | Batch 70/202 | Rec 0.000589 | Seg 0.282024 | Elapsed 1.5m | ETA 2.8m
Epoch 413/500 | Batch 80/202 | Rec 0.000590 | Seg 0.280736 | Elapsed 1.7m | ETA 2.6m
Epoch 413/500 | Batch 90/202 | Rec 0.000583 | Seg 0.275857 | Elapsed 1.9m | ETA 2.3m
Epoch 413/500 | Batch 100/202 | Rec 0.000583 | Seg 0.280912 | Elapsed 2.1m | ETA 2.1m
Epoch 413/500 | Batch 110/202 | Rec 0.000576 | Seg 0.276114 | Elapsed 2.3m | ETA 1.9m
Epoch 413/500 | Batch 120/202 | Rec 0.000584 | Seg 0.274416 | Elapsed 2.5m | ETA 1.7m
Epoch 413/500 | Batch 130/202 | Rec 0.000592 | Seg 0.279063 | Elapsed 2.7m | ETA 1.5m
Epoch 413/500 | Batch 140/202 | Rec 0.000602 | Seg 0.286764 | Elapsed 2.9m | ETA 1.3m
Epoch 413/500 | Batch 150/202 | Rec 0.000602 | Seg 0.287155 | Elapsed 3.1m | ETA 1.1m
Epoch 413/500 | Batch 160/202 | Rec 0.000596 | Seg 0.286025 | Elapsed 3.3m | ETA 0.9m
Epoch 413/500 | Batch 170/202 | Rec 0.000589 | Seg 0.281155 | Elapsed 3.5m | ETA 0.7m
Epoch 413/500 | Batch 180/202 | Rec 0.000598 | Seg 0.284300 | Elapsed 3.7m | ETA 0.5m
Epoch 413/500 | Batch 190/202 | Rec 0.000596 | Seg 0.284431 | Elapsed 3.9m | ETA 0.2m
Epoch 413/500 | Batch 200/202 | Rec 0.000601 | Seg 0.286445 | Elapsed 4.1m | ETA 0.0m
Epoch 413/500 | Batch 202/202 | Rec 0.000601 | Seg 0.285951 | Elapsed 4.2m | ETA 0.0m

2026-10-10 09:59:50,441 - INFO: Rec loss: 0.000600584360726505
2026-10-10 09:59:50,441 - INFO: Seg loss: 0.2859512903165109
2026-10-10 09:59:50,441 - INFO: λ_rec: 1
2026-10-10 09:59:50,441 - INFO: λ_seg: 0.0001
2026-10-10 10:01:04,558 - INFO: -------------------Epoch: 413------------------------
2026-10-10 10:01:04,563 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.011099  0.975013  0.000131
2026-10-10 10:01:04,571 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995808  0.997850  0.997446  0.998353  0.995999
real potato   0.912264  0.954069  0.929704  0.979852  0.999887
fake potato   0.961609  0.980379  0.974545  0.986385  0.999971
real apple    0.777647  0.874868  0.977977  0.791508  0.999219
fake apple    0.559494  0.717487  0.988229  0.563248  0.998326
real orange   0.921916  0.959322  0.994163  0.926934  0.999897
fake orange   0.936158  0.966977  0.953573  0.980866  0.999809
real grape    0.779276  0.875898  0.946613  0.815099  0.999518
fake grape    0.905599  0.950411  0.922510  0.980159  0.999622
real lemon    0.829614  0.906823  0.901578  0.912231  0.999780
fake lemon    0.834148  0.909526  0.996137  0.836855  0.999648
real avocado  0.954339  0.976586  0.989220  0.964368  0.999957
fake avocado  0.735339  0.847439  0.999653  0.735527  0.999683
real pepper   0.871491  0.931283  0.893432  0.972593  0.999475
fake pepper   0.801259  0.889615  0.946112  0.839575  0.999504
real plant    0.869171  0.929957  0.949474  0.911322  0.998628
fake plant    0.805433  0.892183  0.846141  0.943635  0.999819
real banana   0.791574  0.883613  0.894861  0.872742  0.999484
fake banana   0.707574  0.828698  0.796922  0.863222  0.999344
real onion    0.594104  0.745330  0.603876  0.973484  0.999399
fake onion    0.920250  0.958419  0.954219  0.962757  0.999947
real unknown  0.642250  0.782110  0.671223  0.937023  0.999917
fake unknown  0.218051  0.357995  0.240580  0.699565  0.997886
total         0.796712  0.874645  0.885573  0.889013  0.999336
total(-bg)    0.787662  0.869045  0.880488  0.884043  0.999487
2026-10-10 10:01:05,200 - INFO: Epoch accounting: {'epoch': 413, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11204202, 55683, 69493, 125373, 130594, 88824, 72591, 163971, 233238, 69775, 74414, 45581, 24282, 224024, 97664, 135998, 33555, 81228, 85337, 103104, 66357, 11685, 41299], 'crops_with_class': [202, 32, 34, 35, 36, 29, 25, 31, 42, 30, 29, 14, 10, 54, 32, 18, 25, 28, 31, 41, 28, 12, 20], 'targeted_crops_by_class': [0, 1, 4, 6, 5, 4, 5, 7, 7, 3, 6, 8, 2, 8, 5, 3, 3, 5, 8, 6, 7, 4, 5], 'sampled_scene_counts': [0, 2, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 0, 2, 2, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 3, 2, 4, 1, 6, 1, 1, 3, 1, 1, 1, 2, 1, 1, 2, 2, 3, 1, 1, 1, 2, 0, 0, 1, 0, 3, 2, 0, 0, 2, 2, 1, 2, 2, 0, 1, 1, 2, 1, 3, 1, 3, 1, 1, 2, 3, 1, 2, 3, 1, 1, 0, 1, 2, 0, 1, 2, 3, 1, 4, 2, 1, 1, 1, 1, 1, 1, 0, 2, 2, 1, 5, 1, 1, 0, 2, 1, 1, 1, 2, 1, 1], 'learning_rate': 7.681650220489738e-06, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000600584360726505, 'train_segmentation_loss': 0.2859512903165109, 'val_foreground_miou_all22': 0.7876618585113756, 'val_psnr_ref1': 39.011099090576174, 'elapsed_seconds': 325.4496319293976, 'peak_cuda_allocated_gib': 7.509098052978516}

Epoch 414/500 | Batch 10/202 | Rec 0.000698 | Seg 0.326493 | Elapsed 0.2m | ETA 3.9m
Epoch 414/500 | Batch 20/202 | Rec 0.000661 | Seg 0.305591 | Elapsed 0.4m | ETA 3.7m
Epoch 414/500 | Batch 30/202 | Rec 0.000653 | Seg 0.313655 | Elapsed 0.6m | ETA 3.5m
Epoch 414/500 | Batch 40/202 | Rec 0.000655 | Seg 0.305887 | Elapsed 0.8m | ETA 3.3m
Epoch 414/500 | Batch 50/202 | Rec 0.000626 | Seg 0.297005 | Elapsed 1.0m | ETA 3.1m
Epoch 414/500 | Batch 60/202 | Rec 0.000618 | Seg 0.299233 | Elapsed 1.2m | ETA 2.9m
Epoch 414/500 | Batch 70/202 | Rec 0.000609 | Seg 0.297685 | Elapsed 1.4m | ETA 2.7m
Epoch 414/500 | Batch 80/202 | Rec 0.000622 | Seg 0.303406 | Elapsed 1.7m | ETA 2.5m
Epoch 414/500 | Batch 90/202 | Rec 0.000631 | Seg 0.303749 | Elapsed 1.9m | ETA 2.3m
Epoch 414/500 | Batch 100/202 | Rec 0.000636 | Seg 0.301036 | Elapsed 2.1m | ETA 2.1m
Epoch 414/500 | Batch 110/202 | Rec 0.000636 | Seg 0.299754 | Elapsed 2.3m | ETA 1.9m
Epoch 414/500 | Batch 120/202 | Rec 0.000625 | Seg 0.296436 | Elapsed 2.5m | ETA 1.7m
Epoch 414/500 | Batch 130/202 | Rec 0.000627 | Seg 0.301000 | Elapsed 2.7m | ETA 1.5m
Epoch 414/500 | Batch 140/202 | Rec 0.000618 | Seg 0.299104 | Elapsed 2.9m | ETA 1.3m
Epoch 414/500 | Batch 150/202 | Rec 0.000611 | Seg 0.298306 | Elapsed 3.1m | ETA 1.1m
Epoch 414/500 | Batch 160/202 | Rec 0.000608 | Seg 0.298362 | Elapsed 3.3m | ETA 0.9m
Epoch 414/500 | Batch 170/202 | Rec 0.000600 | Seg 0.295260 | Elapsed 3.5m | ETA 0.7m
Epoch 414/500 | Batch 180/202 | Rec 0.000597 | Seg 0.294175 | Elapsed 3.7m | ETA 0.5m
Epoch 414/500 | Batch 190/202 | Rec 0.000601 | Seg 0.294949 | Elapsed 3.9m | ETA 0.2m
Epoch 414/500 | Batch 200/202 | Rec 0.000588 | Seg 0.288719 | Elapsed 4.1m | ETA 0.0m
Epoch 414/500 | Batch 202/202 | Rec 0.000588 | Seg 0.289603 | Elapsed 4.2m | ETA 0.0m

2026-10-10 10:05:15,005 - INFO: Rec loss: 0.000587716277505474
2026-10-10 10:05:15,005 - INFO: Seg loss: 0.28960310743365547
2026-10-10 10:05:15,006 - INFO: λ_rec: 1
2026-10-10 10:05:15,006 - INFO: λ_seg: 0.0001
2026-10-10 10:06:33,536 - INFO: -------------------Epoch: 414------------------------
2026-10-10 10:06:33,539 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.982224  0.974952  0.000132
2026-10-10 10:06:33,546 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995856  0.997874  0.997298  0.998550  0.996044
real potato   0.830321  0.907246  0.958688  0.861132  0.999789
fake potato   0.958162  0.978584  0.983499  0.973816  0.999969
real apple    0.791042  0.883282  0.939525  0.833481  0.999240
fake apple    0.591536  0.743305  0.990778  0.594811  0.998449
real orange   0.900899  0.947816  0.994656  0.905280  0.999869
fake orange   0.921683  0.959196  0.940715  0.978520  0.999762
real grape    0.792553  0.884223  0.959784  0.819776  0.999552
fake grape    0.896513  0.945383  0.928458  0.963041  0.999589
real lemon    0.700992  0.824166  0.730916  0.944820  0.999526
fake lemon    0.849860  0.918787  0.996459  0.852434  0.999681
real avocado  0.938368  0.968154  0.971405  0.965025  0.999941
fake avocado  0.756564  0.861364  0.999327  0.756950  0.999709
real pepper   0.793119  0.884575  0.815596  0.966419  0.999078
fake pepper   0.656114  0.792305  0.940380  0.684591  0.999145
real plant    0.870852  0.930918  0.945647  0.916738  0.998640
fake plant    0.699490  0.823127  0.830730  0.815759  0.999721
real banana   0.690553  0.816905  0.905687  0.744058  0.999251
fake banana   0.749801  0.856963  0.855208  0.858825  0.999473
real onion    0.641207  0.781336  0.672183  0.932950  0.999528
fake onion    0.941205  0.969662  0.987710  0.952358  0.999962
real unknown  0.691771  0.817758  0.719884  0.946565  0.999933
fake unknown  0.222783  0.364349  0.245885  0.703368  0.997932
total         0.777445  0.863360  0.883062  0.868229  0.999295
total(-bg)    0.767518  0.857246  0.877869  0.862305  0.999443
2026-10-10 10:06:34,008 - INFO: Epoch accounting: {'epoch': 414, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11193258, 48961, 68761, 151850, 147236, 81066, 88824, 148367, 188610, 97613, 67447, 33897, 19343, 240021, 126148, 178854, 23442, 86781, 56356, 66067, 57100, 15036, 53234], 'crops_with_class': [202, 33, 29, 32, 37, 27, 29, 28, 38, 42, 34, 11, 11, 61, 31, 20, 26, 28, 24, 33, 22, 19, 23], 'targeted_crops_by_class': [0, 3, 10, 5, 5, 3, 5, 5, 7, 5, 6, 2, 3, 7, 2, 4, 7, 6, 5, 1, 6, 4, 4], 'sampled_scene_counts': [0, 1, 2, 1, 2, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 2, 0, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 4, 1, 0, 0, 1, 2, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 0, 2, 2, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 2, 0, 1, 0, 2, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 2, 3, 1, 1, 0, 1, 2, 0, 5, 0, 2, 2, 3, 0, 2, 1, 1, 1, 2, 0, 3, 0, 2, 2, 1, 3, 2, 0, 1, 0, 0, 0, 1, 0, 3, 4, 1, 1, 0, 3, 4, 4, 4, 2, 1, 2, 0, 1, 1, 3, 1, 0, 0, 0, 0, 5, 1, 1, 0, 3, 0, 0, 4, 2, 2, 1, 2, 0, 2, 2, 1, 3, 2, 0, 1, 0, 1, 2, 3, 1, 0, 1], 'learning_rate': 7.5179130939976375e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000587716277505474, 'train_segmentation_loss': 0.28960310743365547, 'val_foreground_miou_all22': 0.7675175744052993, 'val_psnr_ref1': 38.98222427368164, 'elapsed_seconds': 328.8011791706085, 'peak_cuda_allocated_gib': 7.509067535400391}

Epoch 415/500 | Batch 10/202 | Rec 0.000601 | Seg 0.303700 | Elapsed 0.2m | ETA 4.0m
Epoch 415/500 | Batch 20/202 | Rec 0.000655 | Seg 0.322396 | Elapsed 0.4m | ETA 3.8m
Epoch 415/500 | Batch 30/202 | Rec 0.000670 | Seg 0.322735 | Elapsed 0.6m | ETA 3.6m
Epoch 415/500 | Batch 40/202 | Rec 0.000631 | Seg 0.299334 | Elapsed 0.8m | ETA 3.4m
Epoch 415/500 | Batch 50/202 | Rec 0.000617 | Seg 0.288437 | Elapsed 1.0m | ETA 3.2m
Epoch 415/500 | Batch 60/202 | Rec 0.000620 | Seg 0.280736 | Elapsed 1.2m | ETA 3.0m
Epoch 415/500 | Batch 70/202 | Rec 0.000610 | Seg 0.280429 | Elapsed 1.5m | ETA 2.8m
Epoch 415/500 | Batch 80/202 | Rec 0.000617 | Seg 0.280170 | Elapsed 1.7m | ETA 2.5m
Epoch 415/500 | Batch 90/202 | Rec 0.000607 | Seg 0.276108 | Elapsed 1.9m | ETA 2.3m
Epoch 415/500 | Batch 100/202 | Rec 0.000596 | Seg 0.268579 | Elapsed 2.1m | ETA 2.1m
Epoch 415/500 | Batch 110/202 | Rec 0.000634 | Seg 0.275983 | Elapsed 2.3m | ETA 1.9m
Epoch 415/500 | Batch 120/202 | Rec 0.000629 | Seg 0.276898 | Elapsed 2.5m | ETA 1.7m
Epoch 415/500 | Batch 130/202 | Rec 0.000623 | Seg 0.273540 | Elapsed 2.7m | ETA 1.5m
Epoch 415/500 | Batch 140/202 | Rec 0.000614 | Seg 0.270112 | Elapsed 2.9m | ETA 1.3m
Epoch 415/500 | Batch 150/202 | Rec 0.000618 | Seg 0.271252 | Elapsed 3.1m | ETA 1.1m
Epoch 415/500 | Batch 160/202 | Rec 0.000622 | Seg 0.271118 | Elapsed 3.3m | ETA 0.9m
Epoch 415/500 | Batch 170/202 | Rec 0.000620 | Seg 0.270554 | Elapsed 3.5m | ETA 0.7m
Epoch 415/500 | Batch 180/202 | Rec 0.000614 | Seg 0.268462 | Elapsed 3.7m | ETA 0.5m
Epoch 415/500 | Batch 190/202 | Rec 0.000612 | Seg 0.268253 | Elapsed 3.9m | ETA 0.2m
Epoch 415/500 | Batch 200/202 | Rec 0.000617 | Seg 0.272908 | Elapsed 4.1m | ETA 0.0m
Epoch 415/500 | Batch 202/202 | Rec 0.000619 | Seg 0.273549 | Elapsed 4.2m | ETA 0.0m

2026-10-10 10:10:44,359 - INFO: Rec loss: 0.0006188457826841715
2026-10-10 10:10:44,360 - INFO: Seg loss: 0.27354924220333593
2026-10-10 10:10:44,360 - INFO: λ_rec: 1
2026-10-10 10:10:44,360 - INFO: λ_seg: 0.0001
2026-10-10 10:12:01,208 - INFO: -------------------Epoch: 415------------------------
2026-10-10 10:12:01,212 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.058349  0.974847  0.00013
2026-10-10 10:12:01,219 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995594  0.997742  0.997199  0.998386  0.995793
real potato   0.926970  0.962051  0.981302  0.943637  0.999911
fake potato   0.837205  0.911340  0.968419  0.860704  0.999878
real apple    0.811642  0.895980  0.982023  0.823883  0.999340
fake apple    0.592569  0.744120  0.989868  0.596185  0.998452
real orange   0.917715  0.957042  0.996366  0.920797  0.999891
fake orange   0.929426  0.963372  0.962398  0.964449  0.999790
real grape    0.762886  0.865447  0.968855  0.782065  0.999492
fake grape    0.888835  0.941096  0.905930  0.979210  0.999547
real lemon    0.575041  0.730143  0.663448  0.811867  0.999295
fake lemon    0.837526  0.911530  0.979450  0.852506  0.999650
real avocado  0.918348  0.957386  0.965753  0.949261  0.999922
fake avocado  0.711972  0.831708  0.999821  0.712063  0.999655
real pepper   0.878109  0.935049  0.904649  0.967671  0.999509
fake pepper   0.803699  0.891118  0.938465  0.848409  0.999506
real plant    0.866455  0.928400  0.948100  0.909598  0.998598
fake plant    0.816507  0.898936  0.880795  0.917945  0.999836
real banana   0.656239  0.792395  0.865519  0.730748  0.999140
fake banana   0.627249  0.770883  0.695609  0.864549  0.999055
real onion    0.661613  0.796301  0.685127  0.950684  0.999561
fake onion    0.921403  0.959044  0.965678  0.952600  0.999949
real unknown  0.813545  0.897138  0.867975  0.928435  0.999966
fake unknown  0.197477  0.329783  0.223818  0.626585  0.997854
total         0.780349  0.863826  0.884198  0.864880  0.999287
total(-bg)    0.770565  0.857739  0.879062  0.858811  0.999445
2026-10-10 10:12:01,680 - INFO: Epoch accounting: {'epoch': 415, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11318985, 70841, 73187, 107465, 104753, 76400, 60705, 125297, 160272, 53257, 73989, 25418, 18635, 254505, 134668, 164717, 30723, 101596, 49438, 103102, 82202, 7650, 40467], 'crops_with_class': [202, 41, 33, 27, 27, 25, 23, 22, 33, 27, 27, 9, 9, 61, 35, 25, 28, 29, 29, 44, 33, 9, 17], 'targeted_crops_by_class': [0, 6, 6, 4, 3, 3, 3, 4, 5, 1, 4, 2, 3, 6, 9, 2, 10, 3, 3, 9, 4, 3, 5], 'sampled_scene_counts': [2, 2, 3, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 2, 1, 1, 1, 1, 1, 2, 2, 0, 2, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2, 1, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 1, 1, 0, 0, 0, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 3, 2, 0, 1, 0, 2, 1, 1, 2, 1, 0, 1, 0, 2, 2, 2, 0, 1, 0, 0, 0, 1, 2, 2, 3, 2, 1, 0, 1, 2, 3, 2, 0, 2, 0, 1, 0, 1, 3, 3, 2, 1, 2, 0, 0, 1, 3, 2, 1, 3, 0, 2, 4, 1, 0, 3, 1, 2, 2, 1, 1, 3, 4, 1, 1, 1, 2, 1, 3, 2, 1, 3], 'learning_rate': 7.355858022341591e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006188457826841715, 'train_segmentation_loss': 0.27354924220333593, 'val_foreground_miou_all22': 0.7705650801908054, 'val_psnr_ref1': 39.05834884643555, 'elapsed_seconds': 327.66433477401733, 'peak_cuda_allocated_gib': 7.508365631103516}

Epoch 416/500 | Batch 10/202 | Rec 0.000726 | Seg 0.324210 | Elapsed 0.2m | ETA 3.9m
Epoch 416/500 | Batch 20/202 | Rec 0.000678 | Seg 0.319083 | Elapsed 0.4m | ETA 3.7m
Epoch 416/500 | Batch 30/202 | Rec 0.000619 | Seg 0.293871 | Elapsed 0.6m | ETA 3.5m
Epoch 416/500 | Batch 40/202 | Rec 0.000621 | Seg 0.303888 | Elapsed 0.8m | ETA 3.3m
Epoch 416/500 | Batch 50/202 | Rec 0.000599 | Seg 0.291201 | Elapsed 1.0m | ETA 3.1m
Epoch 416/500 | Batch 60/202 | Rec 0.000590 | Seg 0.292255 | Elapsed 1.2m | ETA 2.9m
Epoch 416/500 | Batch 70/202 | Rec 0.000591 | Seg 0.292396 | Elapsed 1.4m | ETA 2.7m
Epoch 416/500 | Batch 80/202 | Rec 0.000588 | Seg 0.286404 | Elapsed 1.6m | ETA 2.5m
Epoch 416/500 | Batch 90/202 | Rec 0.000600 | Seg 0.292376 | Elapsed 1.8m | ETA 2.3m
Epoch 416/500 | Batch 100/202 | Rec 0.000602 | Seg 0.288968 | Elapsed 2.1m | ETA 2.1m
Epoch 416/500 | Batch 110/202 | Rec 0.000594 | Seg 0.285964 | Elapsed 2.3m | ETA 1.9m
Epoch 416/500 | Batch 120/202 | Rec 0.000596 | Seg 0.286749 | Elapsed 2.5m | ETA 1.7m
Epoch 416/500 | Batch 130/202 | Rec 0.000592 | Seg 0.285428 | Elapsed 2.7m | ETA 1.5m
Epoch 416/500 | Batch 140/202 | Rec 0.000582 | Seg 0.280333 | Elapsed 2.9m | ETA 1.3m
Epoch 416/500 | Batch 150/202 | Rec 0.000584 | Seg 0.279547 | Elapsed 3.1m | ETA 1.1m
Epoch 416/500 | Batch 160/202 | Rec 0.000582 | Seg 0.276522 | Elapsed 3.3m | ETA 0.9m
Epoch 416/500 | Batch 170/202 | Rec 0.000576 | Seg 0.272874 | Elapsed 3.5m | ETA 0.7m
Epoch 416/500 | Batch 180/202 | Rec 0.000568 | Seg 0.268677 | Elapsed 3.7m | ETA 0.5m
Epoch 416/500 | Batch 190/202 | Rec 0.000567 | Seg 0.271769 | Elapsed 3.9m | ETA 0.2m
Epoch 416/500 | Batch 200/202 | Rec 0.000568 | Seg 0.272886 | Elapsed 4.1m | ETA 0.0m
Epoch 416/500 | Batch 202/202 | Rec 0.000565 | Seg 0.271482 | Elapsed 4.2m | ETA 0.0m

2026-10-10 10:16:10,986 - INFO: Rec loss: 0.0005649231904616238
2026-10-10 10:16:10,986 - INFO: Seg loss: 0.27148166276735836
2026-10-10 10:16:10,986 - INFO: λ_rec: 1
2026-10-10 10:16:10,986 - INFO: λ_seg: 0.0001
2026-10-10 10:17:29,311 - INFO: -------------------Epoch: 416------------------------
2026-10-10 10:17:29,315 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.229227  0.975229  0.000125
2026-10-10 10:17:29,321 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995873  0.997882  0.997227  0.998639  0.996061
real potato   0.391321  0.562477  0.994824  0.392119  0.999270
fake potato   0.657665  0.793436  0.987523  0.663176  0.999749
real apple    0.718672  0.836261  0.786895  0.892349  0.998795
fake apple    0.686661  0.814176  0.964219  0.704615  0.998786
real orange   0.903706  0.949368  0.996816  0.906322  0.999873
fake orange   0.926096  0.961580  0.945363  0.978467  0.999776
real grape    0.780193  0.876477  0.958048  0.807791  0.999525
fake grape    0.892169  0.942962  0.916628  0.970961  0.999566
real lemon    0.550825  0.710317  0.575689  0.927292  0.999111
fake lemon    0.859991  0.924676  0.981613  0.874071  0.999699
real avocado  0.824444  0.903726  0.842464  0.974713  0.999807
fake avocado  0.633733  0.775762  0.999598  0.633894  0.999562
real pepper   0.774102  0.872619  0.809966  0.945895  0.998990
fake pepper   0.560199  0.718065  0.949085  0.577556  0.998919
real plant    0.860785  0.925135  0.945733  0.905510  0.998535
fake plant    0.752774  0.858902  0.802833  0.923505  0.999759
real banana   0.528827  0.691760  0.914787  0.556227  0.998886
fake banana   0.751405  0.858010  0.862228  0.853932  0.999480
real onion    0.644642  0.783881  0.706824  0.879919  0.999562
fake onion    0.935127  0.966426  0.993110  0.941233  0.999959
real unknown  0.888187  0.940733  0.941683  0.939885  0.999981
fake unknown  0.236686  0.382736  0.262032  0.709888  0.998071
total         0.728439  0.828146  0.875443  0.824259  0.999205
total(-bg)    0.716282  0.820431  0.869907  0.816333  0.999348
2026-10-10 10:17:29,963 - INFO: Epoch accounting: {'epoch': 416, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11332886, 54519, 64444, 123183, 130991, 56529, 60963, 159858, 183656, 85454, 51687, 35530, 39138, 242584, 136450, 111169, 31334, 85795, 78790, 68410, 45767, 14533, 44602], 'crops_with_class': [202, 35, 30, 32, 33, 19, 19, 31, 39, 33, 26, 11, 16, 66, 37, 16, 26, 25, 33, 36, 20, 14, 21], 'targeted_crops_by_class': [0, 5, 3, 2, 5, 3, 4, 5, 8, 6, 4, 2, 4, 5, 5, 4, 6, 8, 6, 5, 4, 3, 1], 'sampled_scene_counts': [1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 3, 2, 1, 0, 2, 1, 0, 2, 0, 1, 0, 1, 1, 0, 2, 2, 0, 2, 1, 1, 0, 0, 0, 1, 3, 1, 2, 0, 1, 0, 0, 0, 0, 3, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 2, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 0, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 3, 1, 1, 2, 0, 1, 1, 1, 2, 2, 3, 0, 4, 5, 2, 3, 2, 1, 2, 2, 3, 3, 1, 2, 0, 2, 2, 1, 2, 2, 1, 1, 0, 3, 0, 0, 1, 1, 3, 1, 1, 1, 2, 0, 0, 4, 1, 1, 1, 0, 2, 2, 1, 0, 0, 1], 'learning_rate': 7.195491403178306e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005649231904616238, 'train_segmentation_loss': 0.27148166276735836, 'val_foreground_miou_all22': 0.7162824006702105, 'val_psnr_ref1': 39.229226684570314, 'elapsed_seconds': 328.2762839794159, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 417/500 | Batch 10/202 | Rec 0.000464 | Seg 0.265189 | Elapsed 0.2m | ETA 4.0m
Epoch 417/500 | Batch 20/202 | Rec 0.000512 | Seg 0.275522 | Elapsed 0.4m | ETA 3.8m
Epoch 417/500 | Batch 30/202 | Rec 0.000599 | Seg 0.261643 | Elapsed 0.6m | ETA 3.6m
Epoch 417/500 | Batch 40/202 | Rec 0.000578 | Seg 0.260917 | Elapsed 0.8m | ETA 3.4m
Epoch 417/500 | Batch 50/202 | Rec 0.000556 | Seg 0.256848 | Elapsed 1.0m | ETA 3.2m
Epoch 417/500 | Batch 60/202 | Rec 0.000541 | Seg 0.254667 | Elapsed 1.2m | ETA 2.9m
Epoch 417/500 | Batch 70/202 | Rec 0.000563 | Seg 0.253682 | Elapsed 1.4m | ETA 2.7m
Epoch 417/500 | Batch 80/202 | Rec 0.000546 | Seg 0.250477 | Elapsed 1.7m | ETA 2.5m
Epoch 417/500 | Batch 90/202 | Rec 0.000541 | Seg 0.247683 | Elapsed 1.9m | ETA 2.3m
Epoch 417/500 | Batch 100/202 | Rec 0.000547 | Seg 0.251356 | Elapsed 2.1m | ETA 2.1m
Epoch 417/500 | Batch 110/202 | Rec 0.000561 | Seg 0.256716 | Elapsed 2.3m | ETA 1.9m
Epoch 417/500 | Batch 120/202 | Rec 0.000564 | Seg 0.258172 | Elapsed 2.5m | ETA 1.7m
Epoch 417/500 | Batch 130/202 | Rec 0.000577 | Seg 0.263459 | Elapsed 2.7m | ETA 1.5m
Epoch 417/500 | Batch 140/202 | Rec 0.000575 | Seg 0.261867 | Elapsed 2.9m | ETA 1.3m
Epoch 417/500 | Batch 150/202 | Rec 0.000580 | Seg 0.263133 | Elapsed 3.1m | ETA 1.1m
Epoch 417/500 | Batch 160/202 | Rec 0.000580 | Seg 0.264173 | Elapsed 3.3m | ETA 0.9m
Epoch 417/500 | Batch 170/202 | Rec 0.000586 | Seg 0.268598 | Elapsed 3.5m | ETA 0.7m
Epoch 417/500 | Batch 180/202 | Rec 0.000585 | Seg 0.270794 | Elapsed 3.7m | ETA 0.5m
Epoch 417/500 | Batch 190/202 | Rec 0.000580 | Seg 0.268059 | Elapsed 3.9m | ETA 0.2m
Epoch 417/500 | Batch 200/202 | Rec 0.000573 | Seg 0.266615 | Elapsed 4.1m | ETA 0.0m
Epoch 417/500 | Batch 202/202 | Rec 0.000574 | Seg 0.267415 | Elapsed 4.2m | ETA 0.0m

2026-10-10 10:21:39,145 - INFO: Rec loss: 0.0005735097426919977
2026-10-10 10:21:39,145 - INFO: Seg loss: 0.2674153711978752
2026-10-10 10:21:39,145 - INFO: λ_rec: 1
2026-10-10 10:21:39,145 - INFO: λ_seg: 0.0001
2026-10-10 10:22:57,600 - INFO: -------------------Epoch: 417------------------------
2026-10-10 10:22:57,604 - INFO:
Validation stats:
       PSNR      SSIM      MSE
0  39.06862  0.975024  0.00013
2026-10-10 10:22:57,610 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995602  0.997746  0.997137  0.998457  0.995802
real potato   0.900532  0.947613  0.924448  0.972073  0.999872
fake potato   0.963357  0.981287  0.976957  0.985756  0.999973
real apple    0.743180  0.852622  0.972573  0.759089  0.999095
fake apple    0.548976  0.708779  0.991644  0.551528  0.998289
real orange   0.909551  0.952584  0.993214  0.915239  0.999880
fake orange   0.916871  0.956583  0.936533  0.977614  0.999746
real grape    0.777502  0.874775  0.905585  0.846086  0.999494
fake grape    0.907880  0.951666  0.931511  0.972817  0.999635
real lemon    0.745810  0.854350  0.781910  0.941703  0.999623
fake lemon    0.831474  0.907934  0.997754  0.833033  0.999643
real avocado  0.909795  0.952717  0.941913  0.963875  0.999911
fake avocado  0.588880  0.741205  1.000000  0.588880  0.999508
real pepper   0.764217  0.866303  0.789920  0.959161  0.998918
fake pepper   0.573647  0.729020  0.950978  0.591127  0.998953
real plant    0.866417  0.928378  0.955150  0.903161  0.998607
fake plant    0.737398  0.848804  0.785924  0.922738  0.999738
real banana   0.713348  0.832645  0.880651  0.789692  0.999287
fake banana   0.724545  0.840224  0.821975  0.859406  0.999399
real onion    0.607874  0.756074  0.620585  0.967404  0.999436
fake onion    0.942088  0.970130  0.984803  0.955985  0.999963
real unknown  0.536545  0.698331  0.561089  0.924618  0.999872
fake unknown  0.208618  0.345180  0.229421  0.697030  0.997772
total         0.757135  0.847607  0.866595  0.864194  0.999235
total(-bg)    0.746296  0.840782  0.860661  0.858092  0.999392
2026-10-10 10:22:58,069 - INFO: Epoch accounting: {'epoch': 417, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11360254, 57267, 66217, 108557, 141342, 51064, 72401, 135657, 198380, 53272, 57245, 53186, 16141, 200741, 82177, 178303, 22478, 84662, 67445, 108041, 77485, 6872, 39085], 'crops_with_class': [202, 35, 31, 30, 35, 18, 24, 25, 34, 25, 24, 18, 7, 47, 23, 20, 20, 27, 27, 44, 34, 8, 18], 'targeted_crops_by_class': [0, 3, 5, 8, 3, 5, 3, 4, 3, 3, 4, 5, 2, 6, 3, 5, 6, 9, 4, 6, 7, 2, 5], 'sampled_scene_counts': [1, 2, 1, 1, 1, 0, 0, 1, 2, 3, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 2, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 2, 0, 3, 1, 0, 2, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 2, 0, 2, 0, 1, 1, 1, 1, 2, 0, 1, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 2, 1, 1, 2, 0, 2, 2, 0, 1, 0, 2, 0, 0, 0, 1, 3, 2, 2, 2, 0, 0, 1, 0, 1, 2, 2, 0, 0, 1, 2, 3, 0, 2, 1, 1, 0, 1, 2, 2, 0, 2, 2, 1, 2, 0, 0, 3, 2, 2, 4, 1, 0, 2, 3, 4, 3, 2, 2, 4, 1, 3, 0, 2, 2, 1, 0, 1, 3, 0, 0, 0, 0, 1, 1, 1, 1, 0, 3, 2, 2, 1], 'learning_rate': 7.036819567507319e-06, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0005735097426919977, 'train_segmentation_loss': 0.2674153711978752, 'val_foreground_miou_all22': 0.7462957217840688, 'val_psnr_ref1': 39.06862045288086, 'elapsed_seconds': 328.09862875938416, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 418/500 | Batch 10/202 | Rec 0.000784 | Seg 0.266070 | Elapsed 0.2m | ETA 4.0m
Epoch 418/500 | Batch 20/202 | Rec 0.000699 | Seg 0.271346 | Elapsed 0.4m | ETA 3.8m
Epoch 418/500 | Batch 30/202 | Rec 0.000695 | Seg 0.289389 | Elapsed 0.6m | ETA 3.5m
Epoch 418/500 | Batch 40/202 | Rec 0.000724 | Seg 0.305712 | Elapsed 0.8m | ETA 3.4m
Epoch 418/500 | Batch 50/202 | Rec 0.000676 | Seg 0.288048 | Elapsed 1.0m | ETA 3.1m
Epoch 418/500 | Batch 60/202 | Rec 0.000650 | Seg 0.285239 | Elapsed 1.2m | ETA 2.9m
Epoch 418/500 | Batch 70/202 | Rec 0.000639 | Seg 0.281306 | Elapsed 1.4m | ETA 2.7m
Epoch 418/500 | Batch 80/202 | Rec 0.000627 | Seg 0.280622 | Elapsed 1.6m | ETA 2.5m
Epoch 418/500 | Batch 90/202 | Rec 0.000616 | Seg 0.277551 | Elapsed 1.8m | ETA 2.3m
Epoch 418/500 | Batch 100/202 | Rec 0.000604 | Seg 0.274677 | Elapsed 2.0m | ETA 2.1m
Epoch 418/500 | Batch 110/202 | Rec 0.000601 | Seg 0.275557 | Elapsed 2.3m | ETA 1.9m
Epoch 418/500 | Batch 120/202 | Rec 0.000594 | Seg 0.273757 | Elapsed 2.5m | ETA 1.7m
Epoch 418/500 | Batch 130/202 | Rec 0.000597 | Seg 0.273602 | Elapsed 2.7m | ETA 1.5m
Epoch 418/500 | Batch 140/202 | Rec 0.000597 | Seg 0.269862 | Elapsed 2.9m | ETA 1.3m
Epoch 418/500 | Batch 150/202 | Rec 0.000600 | Seg 0.270416 | Elapsed 3.1m | ETA 1.1m
Epoch 418/500 | Batch 160/202 | Rec 0.000598 | Seg 0.273149 | Elapsed 3.3m | ETA 0.9m
Epoch 418/500 | Batch 170/202 | Rec 0.000596 | Seg 0.270610 | Elapsed 3.5m | ETA 0.7m
Epoch 418/500 | Batch 180/202 | Rec 0.000590 | Seg 0.267887 | Elapsed 3.7m | ETA 0.4m
Epoch 418/500 | Batch 190/202 | Rec 0.000589 | Seg 0.267459 | Elapsed 3.9m | ETA 0.2m
Epoch 418/500 | Batch 200/202 | Rec 0.000589 | Seg 0.267414 | Elapsed 4.1m | ETA 0.0m
Epoch 418/500 | Batch 202/202 | Rec 0.000591 | Seg 0.268890 | Elapsed 4.1m | ETA 0.0m

2026-10-10 10:27:06,423 - INFO: Rec loss: 0.0005906287192869562
2026-10-10 10:27:06,423 - INFO: Seg loss: 0.26888971115545474
2026-10-10 10:27:06,423 - INFO: λ_rec: 1
2026-10-10 10:27:06,423 - INFO: λ_seg: 0.0001
2026-10-10 10:28:20,857 - INFO: -------------------Epoch: 418------------------------
2026-10-10 10:28:20,860 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.063902  0.974842  0.00013
2026-10-10 10:28:20,867 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995642  0.997766  0.997254  0.998379  0.995840
real potato   0.291380  0.451234  1.000000  0.291380  0.999152
fake potato   0.645838  0.784765  0.986366  0.651655  0.999740
real apple    0.689607  0.816243  0.754875  0.888589  0.998620
fake apple    0.649249  0.787278  0.949709  0.672365  0.998629
real orange   0.942454  0.970325  0.997798  0.944419  0.999924
fake orange   0.951047  0.974860  0.972325  0.977508  0.999856
real grape    0.831429  0.907907  0.973011  0.851056  0.999640
fake grape    0.860561  0.925006  0.877903  0.977561  0.999414
real lemon    0.403210  0.574654  0.415931  0.929499  0.998383
fake lemon    0.863711  0.926822  0.988399  0.872557  0.999709
real avocado  0.793522  0.884826  0.816667  0.965517  0.999767
fake avocado  0.745123  0.853900  0.999829  0.745218  0.999695
real pepper   0.816106  0.898693  0.870577  0.928792  0.999234
fake pepper   0.712230  0.831884  0.974966  0.725498  0.999301
real plant    0.873047  0.932171  0.956048  0.909553  0.998677
fake plant    0.855242  0.921924  0.907672  0.936733  0.999874
real banana   0.233574  0.378660  0.844653  0.244058  0.998201
fake banana   0.690583  0.816926  0.804081  0.830292  0.999316
real onion    0.600749  0.750535  0.718634  0.785509  0.999528
fake onion    0.875269  0.933437  0.988642  0.884160  0.999921
real unknown  0.903648  0.949336  0.978723  0.921756  0.999984
fake unknown  0.253335  0.404220  0.269157  0.811662  0.997984
total         0.716372  0.811886  0.871444  0.814944  0.999147
total(-bg)    0.703678  0.803437  0.865726  0.806606  0.999298
2026-10-10 10:28:21,325 - INFO: Epoch accounting: {'epoch': 418, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11322581, 44068, 64608, 124769, 110556, 94029, 70603, 168006, 267186, 65607, 53249, 31839, 54606, 184117, 119405, 138392, 27739, 35335, 73179, 72111, 50389, 10360, 55538], 'crops_with_class': [202, 25, 29, 35, 34, 28, 23, 32, 46, 30, 26, 13, 19, 48, 28, 24, 25, 14, 32, 34, 23, 12, 22], 'targeted_crops_by_class': [0, 9, 4, 6, 6, 6, 5, 10, 8, 2, 4, 4, 9, 1, 2, 5, 2, 0, 5, 11, 4, 2, 6], 'sampled_scene_counts': [1, 1, 2, 1, 2, 1, 0, 0, 0, 4, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 2, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 1, 1, 1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2, 1, 1, 2, 1, 0, 2, 1, 1, 1, 0, 0, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 1, 2, 2, 4, 3, 1, 0, 0, 1, 2, 1, 1, 3, 2, 1, 0, 1, 2, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 0, 2, 1, 3, 2, 2, 3, 2, 0, 2, 0, 6, 2, 1, 1, 2, 0, 1, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 2, 2, 2, 1, 0, 2, 2, 1, 4, 1, 1, 4, 0, 1, 1, 1, 0, 2, 1, 1, 1, 0, 4], 'learning_rate': 6.87984877942105e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005906287192869562, 'train_segmentation_loss': 0.26888971115545474, 'val_foreground_miou_all22': 0.7036779701044691, 'val_psnr_ref1': 39.06390243530274, 'elapsed_seconds': 323.24872970581055, 'peak_cuda_allocated_gib': 7.514713287353516}

Epoch 419/500 | Batch 10/202 | Rec 0.000611 | Seg 0.252893 | Elapsed 0.2m | ETA 4.0m
Epoch 419/500 | Batch 20/202 | Rec 0.000602 | Seg 0.246421 | Elapsed 0.4m | ETA 3.8m
Epoch 419/500 | Batch 30/202 | Rec 0.000590 | Seg 0.253982 | Elapsed 0.6m | ETA 3.6m
Epoch 419/500 | Batch 40/202 | Rec 0.000607 | Seg 0.277621 | Elapsed 0.8m | ETA 3.4m
Epoch 419/500 | Batch 50/202 | Rec 0.000597 | Seg 0.294170 | Elapsed 1.0m | ETA 3.1m
Epoch 419/500 | Batch 60/202 | Rec 0.000595 | Seg 0.286364 | Elapsed 1.2m | ETA 2.9m
Epoch 419/500 | Batch 70/202 | Rec 0.000609 | Seg 0.292853 | Elapsed 1.4m | ETA 2.7m
Epoch 419/500 | Batch 80/202 | Rec 0.000615 | Seg 0.300800 | Elapsed 1.6m | ETA 2.5m
Epoch 419/500 | Batch 90/202 | Rec 0.000626 | Seg 0.291939 | Elapsed 1.9m | ETA 2.3m
Epoch 419/500 | Batch 100/202 | Rec 0.000633 | Seg 0.293545 | Elapsed 2.1m | ETA 2.1m
Epoch 419/500 | Batch 110/202 | Rec 0.000630 | Seg 0.292292 | Elapsed 2.3m | ETA 1.9m
Epoch 419/500 | Batch 120/202 | Rec 0.000624 | Seg 0.286369 | Elapsed 2.5m | ETA 1.7m
Epoch 419/500 | Batch 130/202 | Rec 0.000624 | Seg 0.287695 | Elapsed 2.7m | ETA 1.5m
Epoch 419/500 | Batch 140/202 | Rec 0.000631 | Seg 0.286876 | Elapsed 2.9m | ETA 1.3m
Epoch 419/500 | Batch 150/202 | Rec 0.000638 | Seg 0.294517 | Elapsed 3.1m | ETA 1.1m
Epoch 419/500 | Batch 160/202 | Rec 0.000628 | Seg 0.292161 | Elapsed 3.3m | ETA 0.9m
Epoch 419/500 | Batch 170/202 | Rec 0.000617 | Seg 0.288546 | Elapsed 3.5m | ETA 0.7m
Epoch 419/500 | Batch 180/202 | Rec 0.000614 | Seg 0.290117 | Elapsed 3.7m | ETA 0.4m
Epoch 419/500 | Batch 190/202 | Rec 0.000618 | Seg 0.292198 | Elapsed 3.9m | ETA 0.2m
Epoch 419/500 | Batch 200/202 | Rec 0.000615 | Seg 0.292221 | Elapsed 4.1m | ETA 0.0m
Epoch 419/500 | Batch 202/202 | Rec 0.000616 | Seg 0.292910 | Elapsed 4.1m | ETA 0.0m

2026-10-10 10:32:28,366 - INFO: Rec loss: 0.0006158322182750228
2026-10-10 10:32:28,366 - INFO: Seg loss: 0.29291020208361124
2026-10-10 10:32:28,366 - INFO: λ_rec: 1
2026-10-10 10:32:28,366 - INFO: λ_seg: 0.0001
2026-10-10 10:33:47,301 - INFO: -------------------Epoch: 419------------------------
2026-10-10 10:33:47,305 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.013007  0.974724  0.000131
2026-10-10 10:33:47,312 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995788  0.997840  0.997176  0.998604  0.995979
real potato   0.526262  0.689564  0.994951  0.527672  0.999432
fake potato   0.692936  0.818571  0.964753  0.710934  0.999771
real apple    0.715834  0.834336  0.824602  0.844405  0.998844
fake apple    0.621090  0.766215  0.975866  0.630779  0.998547
real orange   0.939785  0.968908  0.995966  0.943377  0.999920
fake orange   0.945167  0.971760  0.967066  0.976602  0.999838
real grape    0.784153  0.878970  0.968011  0.805014  0.999537
fake grape    0.886690  0.939893  0.911426  0.970301  0.999541
real lemon    0.491397  0.658928  0.534010  0.860296  0.998954
fake lemon    0.840111  0.913059  0.953308  0.876163  0.999647
real avocado  0.820031  0.901068  0.843893  0.966667  0.999803
fake avocado  0.818460  0.900119  0.999689  0.818669  0.999783
real pepper   0.850752  0.919308  0.898106  0.941640  0.999396
fake pepper   0.749847  0.856993  0.947793  0.782152  0.999378
real plant    0.866381  0.928357  0.948110  0.909507  0.998597
fake plant    0.844444  0.915613  0.920721  0.910659  0.999866
real banana   0.498634  0.665404  0.885866  0.532867  0.998796
fake banana   0.693445  0.818926  0.795265  0.844144  0.999314
real onion    0.655369  0.791761  0.710092  0.894781  0.999575
fake onion    0.912557  0.954229  0.984070  0.926239  0.999944
real unknown  0.825866  0.904580  0.878597  0.932252  0.999969
fake unknown  0.200745  0.334329  0.225784  0.644151  0.997839
total         0.746771  0.840380  0.875005  0.836864  0.999229
total(-bg)    0.735452  0.833222  0.869452  0.829512  0.999377
2026-10-10 10:33:47,769 - INFO: Epoch accounting: {'epoch': 419, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11179281, 48407, 54153, 120568, 146807, 97516, 81269, 183960, 228199, 70165, 89265, 27052, 35161, 233774, 87011, 169523, 37928, 76029, 100225, 57830, 38309, 21101, 54739], 'crops_with_class': [202, 28, 23, 29, 30, 32, 30, 40, 36, 36, 36, 10, 15, 56, 32, 29, 34, 23, 37, 29, 19, 21, 28], 'targeted_crops_by_class': [0, 3, 2, 3, 7, 5, 6, 4, 5, 4, 7, 3, 4, 7, 2, 8, 8, 6, 5, 4, 1, 8, 6], 'sampled_scene_counts': [2, 1, 2, 1, 0, 1, 0, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 2, 0, 2, 3, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 3, 1, 2, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 2, 0, 1, 1, 0, 2, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 4, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 6, 3, 2, 1, 2, 0, 1, 1, 2, 1, 2, 0, 2, 3, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 0, 1, 2, 1, 2, 1, 0, 1, 3, 1, 1, 1, 4, 8, 4, 1, 1, 1, 0, 1, 3, 0, 1, 1, 0, 2, 0, 0, 1, 2, 3, 0, 0, 0, 1, 2, 2, 3, 2, 2, 0, 3, 2, 2, 2, 0, 1, 1, 0, 1, 1, 0, 2, 2, 1], 'learning_rate': 6.724585235857396e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006158322182750228, 'train_segmentation_loss': 0.29291020208361124, 'val_foreground_miou_all22': 0.7354524988771854, 'val_psnr_ref1': 39.01300735473633, 'elapsed_seconds': 326.4361581802368, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 420/500 | Batch 10/202 | Rec 0.000529 | Seg 0.272904 | Elapsed 0.2m | ETA 4.1m
Epoch 420/500 | Batch 20/202 | Rec 0.000542 | Seg 0.271818 | Elapsed 0.4m | ETA 3.8m
Epoch 420/500 | Batch 30/202 | Rec 0.000535 | Seg 0.269403 | Elapsed 0.6m | ETA 3.5m
Epoch 420/500 | Batch 40/202 | Rec 0.000551 | Seg 0.284356 | Elapsed 0.8m | ETA 3.3m
Epoch 420/500 | Batch 50/202 | Rec 0.000558 | Seg 0.281998 | Elapsed 1.0m | ETA 3.1m
Epoch 420/500 | Batch 60/202 | Rec 0.000570 | Seg 0.287520 | Elapsed 1.2m | ETA 2.9m
Epoch 420/500 | Batch 70/202 | Rec 0.000576 | Seg 0.287071 | Elapsed 1.4m | ETA 2.7m
Epoch 420/500 | Batch 80/202 | Rec 0.000565 | Seg 0.277150 | Elapsed 1.7m | ETA 2.5m
Epoch 420/500 | Batch 90/202 | Rec 0.000559 | Seg 0.279377 | Elapsed 1.9m | ETA 2.3m
Epoch 420/500 | Batch 100/202 | Rec 0.000553 | Seg 0.274893 | Elapsed 2.1m | ETA 2.1m
Epoch 420/500 | Batch 110/202 | Rec 0.000550 | Seg 0.274775 | Elapsed 2.3m | ETA 1.9m
Epoch 420/500 | Batch 120/202 | Rec 0.000550 | Seg 0.275743 | Elapsed 2.5m | ETA 1.7m
Epoch 420/500 | Batch 130/202 | Rec 0.000545 | Seg 0.275305 | Elapsed 2.7m | ETA 1.5m
Epoch 420/500 | Batch 140/202 | Rec 0.000549 | Seg 0.276962 | Elapsed 2.9m | ETA 1.3m
Epoch 420/500 | Batch 150/202 | Rec 0.000543 | Seg 0.270241 | Elapsed 3.1m | ETA 1.1m
Epoch 420/500 | Batch 160/202 | Rec 0.000542 | Seg 0.271403 | Elapsed 3.3m | ETA 0.9m
Epoch 420/500 | Batch 170/202 | Rec 0.000542 | Seg 0.268624 | Elapsed 3.5m | ETA 0.7m
Epoch 420/500 | Batch 180/202 | Rec 0.000548 | Seg 0.270020 | Elapsed 3.7m | ETA 0.5m
Epoch 420/500 | Batch 190/202 | Rec 0.000557 | Seg 0.274317 | Elapsed 3.9m | ETA 0.2m
Epoch 420/500 | Batch 200/202 | Rec 0.000554 | Seg 0.273776 | Elapsed 4.1m | ETA 0.0m
Epoch 420/500 | Batch 202/202 | Rec 0.000555 | Seg 0.275009 | Elapsed 4.2m | ETA 0.0m

2026-10-10 10:37:56,974 - INFO: Rec loss: 0.0005548181505597169
2026-10-10 10:37:56,974 - INFO: Seg loss: 0.2750093750655651
2026-10-10 10:37:56,974 - INFO: λ_rec: 1
2026-10-10 10:37:56,974 - INFO: λ_seg: 0.0001
2026-10-10 10:39:12,689 - INFO: -------------------Epoch: 420------------------------
2026-10-10 10:39:12,693 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.984766  0.974752  0.000132
2026-10-10 10:39:12,700 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995754  0.997822  0.997247  0.998498  0.995946
real potato   0.638826  0.779566  0.981421  0.646646  0.999563
fake potato   0.713815  0.832964  0.976620  0.726225  0.999788
real apple    0.762953  0.865490  0.863596  0.867492  0.999070
fake apple    0.611403  0.758798  0.986107  0.616715  0.998520
real orange   0.828123  0.905932  0.995424  0.831288  0.999773
fake orange   0.896325  0.945279  0.917360  0.975056  0.999677
real grape    0.804703  0.891734  0.946725  0.842871  0.999573
fake grape    0.887989  0.940622  0.911126  0.972198  0.999546
real lemon    0.533518  0.695762  0.567541  0.898987  0.999076
fake lemon    0.857757  0.923383  0.991966  0.863758  0.999697
real avocado  0.853099  0.920677  0.880318  0.965025  0.999846
fake avocado  0.640143  0.780546  1.000000  0.640143  0.999569
real pepper   0.816223  0.898764  0.853244  0.949524  0.999218
fake pepper   0.682637  0.811341  0.945642  0.710518  0.999213
real plant    0.872426  0.931817  0.952060  0.912512  0.998665
fake plant    0.734934  0.847169  0.792913  0.909509  0.999739
real banana   0.529472  0.692312  0.897297  0.563629  0.998875
fake banana   0.710156  0.830466  0.808499  0.853766  0.999359
real onion    0.660579  0.795551  0.714171  0.897990  0.999583
fake onion    0.923388  0.960118  0.982780  0.938573  0.999951
real unknown  0.912594  0.954250  0.983789  0.926527  0.999986
fake unknown  0.214405  0.353066  0.233657  0.722383  0.997770
total         0.742662  0.839714  0.877370  0.836080  0.999217
total(-bg)    0.731158  0.832528  0.871921  0.828697  0.999366
2026-10-10 10:39:13,176 - INFO: Epoch accounting: {'epoch': 420, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11280429, 57315, 54550, 110867, 179745, 112282, 40761, 137343, 212727, 69663, 70315, 49392, 42833, 190841, 123718, 142730, 17228, 78265, 63520, 92529, 50808, 15618, 44793], 'crops_with_class': [202, 28, 26, 31, 43, 30, 20, 30, 38, 29, 29, 18, 16, 51, 32, 20, 17, 23, 31, 38, 25, 18, 21], 'targeted_crops_by_class': [0, 3, 5, 4, 8, 6, 1, 4, 4, 8, 2, 5, 4, 5, 7, 5, 3, 6, 5, 6, 3, 5, 4], 'sampled_scene_counts': [0, 2, 2, 1, 2, 0, 1, 1, 2, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 0, 1, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 2, 0, 1, 1, 1, 0, 0, 1, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 0, 2, 0, 0, 1, 1, 0, 1, 0, 1, 2, 1, 1, 0, 1, 2, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0, 1, 0, 0, 3, 2, 1, 0, 0, 1, 0, 1, 0, 2, 1, 2, 2, 0, 1, 1, 3, 1, 2, 1, 3, 1, 2, 1, 2, 2, 1, 3, 0, 1, 1, 3, 3, 0, 0, 1, 0, 3, 0, 0, 0, 2, 0, 2, 1, 3, 5, 2, 3, 1, 0, 0, 1, 1, 2, 1, 3, 1, 1, 2, 2, 1, 1, 2, 0, 0, 0, 2, 1, 2, 1, 1, 0, 3, 2, 0, 1, 4, 0, 2, 1, 2, 1, 2, 0, 2, 1, 2], 'learning_rate': 6.571035066355223e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005548181505597169, 'train_segmentation_loss': 0.2750093750655651, 'val_foreground_miou_all22': 0.7311575947902049, 'val_psnr_ref1': 38.984765625, 'elapsed_seconds': 325.400269985199, 'peak_cuda_allocated_gib': 7.507335662841797}

Epoch 421/500 | Batch 10/202 | Rec 0.000467 | Seg 0.261272 | Elapsed 0.2m | ETA 3.9m
Epoch 421/500 | Batch 20/202 | Rec 0.000548 | Seg 0.274478 | Elapsed 0.4m | ETA 3.7m
Epoch 421/500 | Batch 30/202 | Rec 0.000523 | Seg 0.248113 | Elapsed 0.6m | ETA 3.5m
Epoch 421/500 | Batch 40/202 | Rec 0.000538 | Seg 0.250853 | Elapsed 0.8m | ETA 3.3m
Epoch 421/500 | Batch 50/202 | Rec 0.000541 | Seg 0.260631 | Elapsed 1.0m | ETA 3.1m
Epoch 421/500 | Batch 60/202 | Rec 0.000552 | Seg 0.264525 | Elapsed 1.2m | ETA 2.9m
Epoch 421/500 | Batch 70/202 | Rec 0.000553 | Seg 0.260402 | Elapsed 1.4m | ETA 2.7m
Epoch 421/500 | Batch 80/202 | Rec 0.000551 | Seg 0.264615 | Elapsed 1.6m | ETA 2.5m
Epoch 421/500 | Batch 90/202 | Rec 0.000554 | Seg 0.270566 | Elapsed 1.8m | ETA 2.3m
Epoch 421/500 | Batch 100/202 | Rec 0.000556 | Seg 0.270076 | Elapsed 2.1m | ETA 2.1m
Epoch 421/500 | Batch 110/202 | Rec 0.000558 | Seg 0.270665 | Elapsed 2.3m | ETA 1.9m
Epoch 421/500 | Batch 120/202 | Rec 0.000558 | Seg 0.271316 | Elapsed 2.5m | ETA 1.7m
Epoch 421/500 | Batch 130/202 | Rec 0.000558 | Seg 0.270440 | Elapsed 2.7m | ETA 1.5m
Epoch 421/500 | Batch 140/202 | Rec 0.000560 | Seg 0.276031 | Elapsed 2.9m | ETA 1.3m
Epoch 421/500 | Batch 150/202 | Rec 0.000559 | Seg 0.276770 | Elapsed 3.1m | ETA 1.1m
Epoch 421/500 | Batch 160/202 | Rec 0.000559 | Seg 0.277045 | Elapsed 3.3m | ETA 0.9m
Epoch 421/500 | Batch 170/202 | Rec 0.000558 | Seg 0.276247 | Elapsed 3.5m | ETA 0.7m
Epoch 421/500 | Batch 180/202 | Rec 0.000556 | Seg 0.273505 | Elapsed 3.7m | ETA 0.5m
Epoch 421/500 | Batch 190/202 | Rec 0.000559 | Seg 0.271863 | Elapsed 3.9m | ETA 0.2m
Epoch 421/500 | Batch 200/202 | Rec 0.000565 | Seg 0.276818 | Elapsed 4.1m | ETA 0.0m
Epoch 421/500 | Batch 202/202 | Rec 0.000566 | Seg 0.277484 | Elapsed 4.2m | ETA 0.0m

2026-10-10 10:43:22,678 - INFO: Rec loss: 0.0005657850166910679
2026-10-10 10:43:22,678 - INFO: Seg loss: 0.27748427379618185
2026-10-10 10:43:22,678 - INFO: λ_rec: 1
2026-10-10 10:43:22,678 - INFO: λ_seg: 0.0001
2026-10-10 10:44:40,426 - INFO: -------------------Epoch: 421------------------------
2026-10-10 10:44:40,429 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.106712  0.975009  0.000128
2026-10-10 10:44:40,436 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995788  0.997839  0.997326  0.998454  0.995979
real potato   0.365468  0.535261  1.000000  0.365468  0.999241
fake potato   0.648370  0.786632  0.977598  0.658148  0.999740
real apple    0.682914  0.811535  0.769734  0.858249  0.998625
fake apple    0.624109  0.768507  0.961114  0.640276  0.998544
real orange   0.915184  0.955664  0.997732  0.917091  0.999888
fake orange   0.929338  0.963325  0.958043  0.968767  0.999789
real grape    0.805001  0.891918  0.979456  0.818826  0.999586
fake grape    0.881569  0.937007  0.902591  0.974261  0.999516
real lemon    0.393107  0.564316  0.412868  0.891457  0.998383
fake lemon    0.856696  0.922768  0.983990  0.868806  0.999693
real avocado  0.865376  0.927780  0.896372  0.961576  0.999861
fake avocado  0.751084  0.857801  1.000000  0.751084  0.999702
real pepper   0.844747  0.915790  0.881018  0.953529  0.999359
fake pepper   0.756940  0.861607  0.951563  0.787274  0.999397
real plant    0.877871  0.934914  0.947396  0.922855  0.998716
fake plant    0.890906  0.942256  0.963349  0.922163  0.999910
real banana   0.253760  0.404762  0.825941  0.268097  0.998228
fake banana   0.679397  0.809046  0.783274  0.836679  0.999274
real onion    0.605774  0.754445  0.721845  0.790238  0.999535
fake onion    0.878947  0.935524  0.987900  0.888513  0.999923
real unknown  0.926527  0.961812  1.000000  0.926527  0.999988
fake unknown  0.218479  0.358573  0.236300  0.743390  0.997759
total         0.723798  0.817352  0.875453  0.813553  0.999158
total(-bg)    0.711435  0.809148  0.869913  0.805149  0.999303
2026-10-10 10:44:40,903 - INFO: Epoch accounting: {'epoch': 421, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11248663, 56235, 60734, 126579, 155194, 77831, 77665, 148387, 209735, 90865, 61230, 31331, 26396, 235074, 130320, 110028, 16605, 91238, 70792, 93107, 55240, 9448, 55575], 'crops_with_class': [202, 30, 25, 35, 37, 24, 24, 27, 34, 37, 28, 13, 15, 56, 34, 21, 15, 27, 32, 36, 27, 11, 23], 'targeted_crops_by_class': [0, 6, 5, 4, 4, 5, 4, 4, 4, 4, 4, 4, 2, 3, 3, 4, 2, 4, 7, 8, 8, 4, 6], 'sampled_scene_counts': [0, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 3, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 1, 0, 0, 0, 2, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 2, 1, 2, 1, 2, 1, 2, 2, 0, 1, 2, 1, 1, 3, 3, 2, 1, 3, 1, 0, 2, 2, 0, 1, 4, 1, 0, 1, 2, 0, 1, 1, 2, 1, 0, 1, 4, 1, 1, 0, 1, 3, 3, 2, 5, 1, 1, 2, 2, 0, 2, 1, 3, 1, 0, 1, 2, 4, 0, 1, 3, 0, 5, 0, 0, 1, 0, 0, 0, 3, 2, 0, 1, 4, 0, 2, 0, 1, 3, 2, 3, 3, 1, 0], 'learning_rate': 6.419204332812295e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005657850166910679, 'train_segmentation_loss': 0.27748427379618185, 'val_foreground_miou_all22': 0.7114346377734386, 'val_psnr_ref1': 39.10671157836914, 'elapsed_seconds': 327.71913480758667, 'peak_cuda_allocated_gib': 7.510997772216797}

Epoch 422/500 | Batch 10/202 | Rec 0.000572 | Seg 0.288201 | Elapsed 0.2m | ETA 3.9m
Epoch 422/500 | Batch 20/202 | Rec 0.000612 | Seg 0.298376 | Elapsed 0.4m | ETA 3.8m
Epoch 422/500 | Batch 30/202 | Rec 0.000597 | Seg 0.303540 | Elapsed 0.6m | ETA 3.5m
Epoch 422/500 | Batch 40/202 | Rec 0.000583 | Seg 0.301305 | Elapsed 0.8m | ETA 3.3m
Epoch 422/500 | Batch 50/202 | Rec 0.000552 | Seg 0.295714 | Elapsed 1.0m | ETA 3.1m
Epoch 422/500 | Batch 60/202 | Rec 0.000557 | Seg 0.302036 | Elapsed 1.2m | ETA 2.9m
Epoch 422/500 | Batch 70/202 | Rec 0.000563 | Seg 0.290344 | Elapsed 1.4m | ETA 2.7m
Epoch 422/500 | Batch 80/202 | Rec 0.000576 | Seg 0.290465 | Elapsed 1.6m | ETA 2.5m
Epoch 422/500 | Batch 90/202 | Rec 0.000576 | Seg 0.289561 | Elapsed 1.8m | ETA 2.3m
Epoch 422/500 | Batch 100/202 | Rec 0.000580 | Seg 0.284495 | Elapsed 2.0m | ETA 2.1m
Epoch 422/500 | Batch 110/202 | Rec 0.000589 | Seg 0.285774 | Elapsed 2.2m | ETA 1.9m
Epoch 422/500 | Batch 120/202 | Rec 0.000577 | Seg 0.282063 | Elapsed 2.4m | ETA 1.7m
Epoch 422/500 | Batch 130/202 | Rec 0.000579 | Seg 0.282993 | Elapsed 2.6m | ETA 1.5m
Epoch 422/500 | Batch 140/202 | Rec 0.000574 | Seg 0.285064 | Elapsed 2.9m | ETA 1.3m
Epoch 422/500 | Batch 150/202 | Rec 0.000575 | Seg 0.285373 | Elapsed 3.1m | ETA 1.1m
Epoch 422/500 | Batch 160/202 | Rec 0.000569 | Seg 0.284296 | Elapsed 3.3m | ETA 0.9m
Epoch 422/500 | Batch 170/202 | Rec 0.000570 | Seg 0.283752 | Elapsed 3.5m | ETA 0.7m
Epoch 422/500 | Batch 180/202 | Rec 0.000569 | Seg 0.280176 | Elapsed 3.7m | ETA 0.4m
Epoch 422/500 | Batch 190/202 | Rec 0.000568 | Seg 0.279043 | Elapsed 3.9m | ETA 0.2m
Epoch 422/500 | Batch 200/202 | Rec 0.000564 | Seg 0.282306 | Elapsed 4.1m | ETA 0.0m
Epoch 422/500 | Batch 202/202 | Rec 0.000563 | Seg 0.282807 | Elapsed 4.1m | ETA 0.0m

2026-10-10 10:48:49,215 - INFO: Rec loss: 0.0005634830196850269
2026-10-10 10:48:49,215 - INFO: Seg loss: 0.2828067570998527
2026-10-10 10:48:49,215 - INFO: λ_rec: 1
2026-10-10 10:48:49,215 - INFO: λ_seg: 0.0001
2026-10-10 10:50:06,036 - INFO: -------------------Epoch: 422------------------------
2026-10-10 10:50:06,041 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.950543  0.974778  0.000133
2026-10-10 10:50:06,048 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995712  0.997801  0.997061  0.998643  0.995906
real potato   0.259118  0.411553  1.000000  0.259118  0.999113
fake potato   0.650385  0.788113  0.988313  0.655425  0.999743
real apple    0.683399  0.811878  0.741056  0.897789  0.998565
fake apple    0.661537  0.796247  0.958480  0.681054  0.998684
real orange   0.901666  0.948241  0.998975  0.902501  0.999870
fake orange   0.927652  0.962418  0.950049  0.975216  0.999782
real grape    0.838001  0.911811  0.954891  0.872543  0.999648
fake grape    0.881342  0.936879  0.903381  0.973064  0.999515
real lemon    0.457866  0.628087  0.473532  0.932615  0.998702
fake lemon    0.865099  0.927621  0.992925  0.870465  0.999713
real avocado  0.771226  0.870789  0.792407  0.966502  0.999734
fake avocado  0.730750  0.844383  0.999651  0.730936  0.999678
real pepper   0.780370  0.876588  0.837672  0.919406  0.999053
fake pepper   0.591141  0.742993  0.956552  0.607452  0.998999
real plant    0.869079  0.929904  0.949066  0.911597  0.998626
fake plant    0.754834  0.860241  0.838674  0.883052  0.999772
real banana   0.329448  0.495577  0.915797  0.339739  0.998446
fake banana   0.723663  0.839631  0.851202  0.828467  0.999418
real onion    0.580755  0.734732  0.721851  0.748184  0.999512
fake onion    0.837344  0.911422  0.994002  0.841596  0.999897
real unknown  0.922930  0.959871  0.996917  0.925572  0.999988
fake unknown  0.245611  0.394324  0.265947  0.762586  0.998026
total         0.706910  0.807874  0.872974  0.803631  0.999147
total(-bg)    0.693783  0.799241  0.867334  0.794767  0.999295
2026-10-10 10:50:06,516 - INFO: Epoch accounting: {'epoch': 422, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11249036, 37246, 35757, 110460, 155948, 102721, 102914, 158907, 220521, 107481, 76608, 49894, 59847, 221164, 81074, 140443, 31967, 69717, 63379, 61820, 44683, 14948, 41737], 'crops_with_class': [202, 27, 20, 35, 41, 28, 39, 31, 39, 45, 34, 17, 22, 51, 26, 21, 27, 22, 27, 29, 20, 14, 20], 'targeted_crops_by_class': [0, 3, 2, 2, 7, 5, 8, 4, 4, 4, 7, 6, 12, 5, 2, 3, 7, 6, 4, 2, 4, 8, 0], 'sampled_scene_counts': [1, 1, 2, 1, 1, 0, 0, 0, 2, 2, 2, 0, 2, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 1, 1, 1, 1, 3, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 2, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2, 3, 3, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 3, 0, 1, 1, 1, 0, 0, 1, 3, 2, 3, 3, 1, 2, 2, 3, 1, 1, 2, 2, 4, 2, 1, 2, 1, 2, 0, 3, 1, 0, 1, 4, 0, 2, 0, 2, 2, 1, 2, 0, 1, 3, 2, 0, 2, 3, 1, 4, 2, 2, 0, 2, 3, 0, 0, 1, 1, 1, 0, 1, 3, 2, 2, 0, 1, 2, 2, 1, 0, 0, 4, 0, 0, 1, 2, 3, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], 'learning_rate': 6.269099029246004e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005634830196850269, 'train_segmentation_loss': 0.2828067570998527, 'val_foreground_miou_all22': 0.693782568569642, 'val_psnr_ref1': 38.95054275512695, 'elapsed_seconds': 325.60576343536377, 'peak_cuda_allocated_gib': 7.515201568603516}

Epoch 423/500 | Batch 10/202 | Rec 0.000587 | Seg 0.218344 | Elapsed 0.2m | ETA 4.0m
Epoch 423/500 | Batch 20/202 | Rec 0.000576 | Seg 0.229989 | Elapsed 0.4m | ETA 3.8m
Epoch 423/500 | Batch 30/202 | Rec 0.000574 | Seg 0.278542 | Elapsed 0.6m | ETA 3.6m
Epoch 423/500 | Batch 40/202 | Rec 0.000570 | Seg 0.279401 | Elapsed 0.8m | ETA 3.4m
Epoch 423/500 | Batch 50/202 | Rec 0.000591 | Seg 0.274721 | Elapsed 1.0m | ETA 3.1m
Epoch 423/500 | Batch 60/202 | Rec 0.000587 | Seg 0.274107 | Elapsed 1.2m | ETA 2.9m
Epoch 423/500 | Batch 70/202 | Rec 0.000603 | Seg 0.274095 | Elapsed 1.4m | ETA 2.7m
Epoch 423/500 | Batch 80/202 | Rec 0.000597 | Seg 0.279312 | Elapsed 1.6m | ETA 2.5m
Epoch 423/500 | Batch 90/202 | Rec 0.000591 | Seg 0.277145 | Elapsed 1.8m | ETA 2.3m
Epoch 423/500 | Batch 100/202 | Rec 0.000607 | Seg 0.284594 | Elapsed 2.1m | ETA 2.1m
Epoch 423/500 | Batch 110/202 | Rec 0.000591 | Seg 0.277750 | Elapsed 2.3m | ETA 1.9m
Epoch 423/500 | Batch 120/202 | Rec 0.000580 | Seg 0.274516 | Elapsed 2.5m | ETA 1.7m
Epoch 423/500 | Batch 130/202 | Rec 0.000581 | Seg 0.273825 | Elapsed 2.7m | ETA 1.5m
Epoch 423/500 | Batch 140/202 | Rec 0.000574 | Seg 0.270231 | Elapsed 2.9m | ETA 1.3m
Epoch 423/500 | Batch 150/202 | Rec 0.000569 | Seg 0.267397 | Elapsed 3.1m | ETA 1.1m
Epoch 423/500 | Batch 160/202 | Rec 0.000569 | Seg 0.265603 | Elapsed 3.3m | ETA 0.9m
Epoch 423/500 | Batch 170/202 | Rec 0.000570 | Seg 0.266853 | Elapsed 3.5m | ETA 0.7m
Epoch 423/500 | Batch 180/202 | Rec 0.000573 | Seg 0.266992 | Elapsed 3.7m | ETA 0.5m
Epoch 423/500 | Batch 190/202 | Rec 0.000575 | Seg 0.267898 | Elapsed 3.9m | ETA 0.2m
Epoch 423/500 | Batch 200/202 | Rec 0.000577 | Seg 0.270335 | Elapsed 4.1m | ETA 0.0m
Epoch 423/500 | Batch 202/202 | Rec 0.000577 | Seg 0.269977 | Elapsed 4.1m | ETA 0.0m

2026-10-10 10:54:15,515 - INFO: Rec loss: 0.0005767683821008772
2026-10-10 10:54:15,515 - INFO: Seg loss: 0.2699772610080124
2026-10-10 10:54:15,515 - INFO: λ_rec: 1
2026-10-10 10:54:15,515 - INFO: λ_seg: 0.0001
2026-10-10 10:55:28,747 - INFO: -------------------Epoch: 423------------------------
2026-10-10 10:55:28,751 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.006019  0.974897  0.000131
2026-10-10 10:55:28,757 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995704  0.997797  0.997315  0.998380  0.995899
real potato   0.466466  0.636133  0.968701  0.473604  0.999352
fake potato   0.778585  0.875461  0.988149  0.785924  0.999837
real apple    0.723727  0.839674  0.801754  0.881468  0.998839
fake apple    0.587014  0.739725  0.989174  0.590810  0.998431
real orange   0.935087  0.966405  0.991714  0.942450  0.999914
fake orange   0.934033  0.965841  0.954751  0.977295  0.999802
real grape    0.828080  0.905906  0.945203  0.869838  0.999623
fake grape    0.900099  0.947373  0.919855  0.976694  0.999599
real lemon    0.599217  0.749340  0.617247  0.953519  0.999250
fake lemon    0.857050  0.922974  0.995908  0.860079  0.999697
real avocado  0.828897  0.906395  0.853415  0.966502  0.999815
fake avocado  0.783694  0.878682  0.998701  0.784494  0.999741
real pepper   0.772701  0.871728  0.807824  0.946730  0.998981
fake pepper   0.592199  0.743828  0.954573  0.609372  0.999000
real plant    0.871891  0.931512  0.960048  0.904717  0.998670
fake plant    0.787694  0.881191  0.827470  0.942485  0.999798
real banana   0.575610  0.730602  0.861477  0.634320  0.998949
fake banana   0.715807  0.834318  0.806439  0.864300  0.999369
real onion    0.638140  0.779054  0.704437  0.871474  0.999554
fake onion    0.933207  0.965400  0.978396  0.952842  0.999957
real unknown  0.930343  0.963865  1.000000  0.930343  0.999989
fake unknown  0.235405  0.381060  0.255969  0.745563  0.997960
total         0.750898  0.844098  0.877327  0.846226  0.999218
total(-bg)    0.739770  0.837112  0.871873  0.839310  0.999369
2026-10-10 10:55:29,211 - INFO: Epoch accounting: {'epoch': 423, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11348002, 55430, 61108, 124512, 131660, 79178, 68019, 156308, 135504, 62964, 67859, 39081, 35262, 198069, 111908, 148626, 32399, 89965, 85942, 107537, 53075, 7632, 38232], 'crops_with_class': [202, 30, 25, 36, 30, 28, 25, 27, 28, 27, 31, 14, 12, 51, 33, 20, 25, 29, 31, 43, 26, 8, 19], 'targeted_crops_by_class': [0, 4, 7, 5, 4, 4, 4, 3, 5, 9, 2, 4, 5, 2, 3, 6, 3, 8, 4, 6, 8, 3, 3], 'sampled_scene_counts': [0, 1, 0, 1, 0, 0, 0, 1, 2, 3, 1, 1, 2, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 2, 0, 0, 2, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 2, 0, 0, 2, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 1, 2, 0, 0, 1, 1, 1, 0, 2, 1, 3, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 2, 1, 4, 1, 1, 0, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 2, 1, 3, 2, 0, 0, 1, 1, 1, 3, 0, 1, 0, 1, 2, 1, 1, 2, 3, 0, 1, 0, 2, 3, 2, 2, 0, 3, 2, 2, 0, 2, 1, 0, 4, 3, 3, 6, 0, 2, 0, 1, 1, 0, 3, 1, 1, 1, 3, 2, 1, 0, 2, 1, 2, 2, 0, 1, 1, 1, 2, 1, 2, 1], 'learning_rate': 6.120725081556691e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005767683821008772, 'train_segmentation_loss': 0.2699772610080124, 'val_foreground_miou_all22': 0.7397703096439007, 'val_psnr_ref1': 39.006019287109375, 'elapsed_seconds': 322.68804812431335, 'peak_cuda_allocated_gib': 7.511569976806641}

Epoch 424/500 | Batch 10/202 | Rec 0.000592 | Seg 0.319825 | Elapsed 0.2m | ETA 3.9m
Epoch 424/500 | Batch 20/202 | Rec 0.000555 | Seg 0.279027 | Elapsed 0.4m | ETA 3.8m
Epoch 424/500 | Batch 30/202 | Rec 0.000528 | Seg 0.263615 | Elapsed 0.6m | ETA 3.5m
Epoch 424/500 | Batch 40/202 | Rec 0.000536 | Seg 0.265427 | Elapsed 0.8m | ETA 3.3m
Epoch 424/500 | Batch 50/202 | Rec 0.000538 | Seg 0.257383 | Elapsed 1.0m | ETA 3.1m
Epoch 424/500 | Batch 60/202 | Rec 0.000542 | Seg 0.259841 | Elapsed 1.2m | ETA 2.9m
Epoch 424/500 | Batch 70/202 | Rec 0.000573 | Seg 0.269462 | Elapsed 1.4m | ETA 2.7m
Epoch 424/500 | Batch 80/202 | Rec 0.000571 | Seg 0.270384 | Elapsed 1.6m | ETA 2.5m
Epoch 424/500 | Batch 90/202 | Rec 0.000554 | Seg 0.267669 | Elapsed 1.8m | ETA 2.3m
Epoch 424/500 | Batch 100/202 | Rec 0.000573 | Seg 0.276418 | Elapsed 2.0m | ETA 2.1m
Epoch 424/500 | Batch 110/202 | Rec 0.000573 | Seg 0.283950 | Elapsed 2.2m | ETA 1.9m
Epoch 424/500 | Batch 120/202 | Rec 0.000577 | Seg 0.284997 | Elapsed 2.5m | ETA 1.7m
Epoch 424/500 | Batch 130/202 | Rec 0.000565 | Seg 0.281875 | Elapsed 2.7m | ETA 1.5m
Epoch 424/500 | Batch 140/202 | Rec 0.000561 | Seg 0.280279 | Elapsed 2.9m | ETA 1.3m
Epoch 424/500 | Batch 150/202 | Rec 0.000565 | Seg 0.281811 | Elapsed 3.1m | ETA 1.1m
Epoch 424/500 | Batch 160/202 | Rec 0.000559 | Seg 0.279974 | Elapsed 3.3m | ETA 0.9m
Epoch 424/500 | Batch 170/202 | Rec 0.000567 | Seg 0.280877 | Elapsed 3.5m | ETA 0.7m
Epoch 424/500 | Batch 180/202 | Rec 0.000569 | Seg 0.279269 | Elapsed 3.7m | ETA 0.5m
Epoch 424/500 | Batch 190/202 | Rec 0.000559 | Seg 0.275710 | Elapsed 3.9m | ETA 0.2m
Epoch 424/500 | Batch 200/202 | Rec 0.000558 | Seg 0.276266 | Elapsed 4.1m | ETA 0.0m
Epoch 424/500 | Batch 202/202 | Rec 0.000558 | Seg 0.276530 | Elapsed 4.1m | ETA 0.0m

2026-10-10 10:59:37,191 - INFO: Rec loss: 0.0005575240915871714
2026-10-10 10:59:37,191 - INFO: Seg loss: 0.2765298378423299
2026-10-10 10:59:37,191 - INFO: λ_rec: 1
2026-10-10 10:59:37,191 - INFO: λ_seg: 0.0001
2026-10-10 11:00:53,857 - INFO: -------------------Epoch: 424------------------------
2026-10-10 11:00:53,861 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.162133  0.975233  0.000127
2026-10-10 11:00:53,868 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995670  0.997780  0.997100  0.998561  0.995866
real potato   0.341961  0.509606  0.999627  0.342005  0.999212
fake potato   0.654285  0.790971  0.985929  0.660452  0.999746
real apple    0.709929  0.830311  0.776158  0.892702  0.998742
fake apple    0.751835  0.858291  0.969762  0.769884  0.999041
real orange   0.924983  0.960980  0.994795  0.929481  0.999901
fake orange   0.932138  0.964827  0.952013  0.978094  0.999796
real grape    0.821276  0.901819  0.969651  0.842944  0.999617
fake grape    0.892211  0.942986  0.922143  0.964897  0.999569
real lemon    0.448730  0.619436  0.461333  0.942612  0.998639
fake lemon    0.857912  0.923473  0.994755  0.861810  0.999698
real avocado  0.866569  0.928465  0.891863  0.968309  0.999861
fake avocado  0.782282  0.877794  0.999511  0.782581  0.999739
real pepper   0.770530  0.870345  0.808802  0.942141  0.998974
fake pepper   0.622066  0.766956  0.973601  0.632738  0.999084
real plant    0.873845  0.932626  0.953367  0.912863  0.998682
fake plant    0.779265  0.875891  0.881553  0.870399  0.999804
real banana   0.307211  0.469985  0.859592  0.323442  0.998361
fake banana   0.706653  0.828066  0.829011  0.827223  0.999368
real onion    0.618869  0.764520  0.704860  0.835332  0.999535
fake onion    0.915825  0.956013  0.993996  0.920919  0.999947
real unknown  0.929457  0.963389  0.998975  0.930343  0.999989
fake unknown  0.293422  0.453673  0.320391  0.777074  0.998423
total         0.730301  0.825574  0.879947  0.822035  0.999200
total(-bg)    0.718239  0.817746  0.874622  0.814011  0.999351
2026-10-10 11:00:54,343 - INFO: Epoch accounting: {'epoch': 424, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11327284, 55520, 74870, 96454, 134045, 74126, 82388, 161031, 161182, 59669, 43529, 64424, 25193, 235519, 70114, 185044, 23579, 82728, 86426, 90881, 55831, 5998, 42437], 'crops_with_class': [202, 30, 32, 30, 33, 24, 26, 34, 30, 29, 22, 22, 10, 55, 25, 26, 23, 25, 38, 36, 28, 6, 22], 'targeted_crops_by_class': [0, 5, 7, 2, 5, 5, 6, 6, 6, 2, 4, 9, 3, 4, 2, 11, 5, 3, 7, 3, 8, 2, 6], 'sampled_scene_counts': [3, 1, 0, 1, 0, 3, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 1, 1, 2, 1, 2, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 0, 0, 1, 2, 1, 1, 2, 0, 0, 2, 2, 2, 0, 0, 1, 0, 0, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 2, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2, 2, 1, 1, 0, 1, 2, 4, 3, 0, 1, 0, 1, 0, 1, 2, 0, 2, 2, 4, 2, 0, 2, 0, 2, 4, 1, 1, 3, 1, 3, 1, 1, 1, 2, 0, 0, 1, 3, 0, 1, 4, 1, 3, 2, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2, 3, 3, 2, 1, 2, 1, 0, 1, 2, 1, 0, 2, 2, 3, 2], 'learning_rate': 5.974088347293791e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005575240915871714, 'train_segmentation_loss': 0.2765298378423299, 'val_foreground_miou_all22': 0.7182387650120831, 'val_psnr_ref1': 39.162132568359375, 'elapsed_seconds': 325.1245586872101, 'peak_cuda_allocated_gib': 7.507114410400391}

Epoch 425/500 | Batch 10/202 | Rec 0.000703 | Seg 0.302113 | Elapsed 0.2m | ETA 4.1m
Epoch 425/500 | Batch 20/202 | Rec 0.000584 | Seg 0.289764 | Elapsed 0.4m | ETA 3.8m
Epoch 425/500 | Batch 30/202 | Rec 0.000517 | Seg 0.273539 | Elapsed 0.6m | ETA 3.7m
Epoch 425/500 | Batch 40/202 | Rec 0.000518 | Seg 0.275008 | Elapsed 0.8m | ETA 3.4m
Epoch 425/500 | Batch 50/202 | Rec 0.000520 | Seg 0.263538 | Elapsed 1.0m | ETA 3.2m
Epoch 425/500 | Batch 60/202 | Rec 0.000517 | Seg 0.265388 | Elapsed 1.3m | ETA 3.0m
Epoch 425/500 | Batch 70/202 | Rec 0.000536 | Seg 0.276023 | Elapsed 1.5m | ETA 2.8m
Epoch 425/500 | Batch 80/202 | Rec 0.000538 | Seg 0.274046 | Elapsed 1.7m | ETA 2.5m
Epoch 425/500 | Batch 90/202 | Rec 0.000558 | Seg 0.282809 | Elapsed 1.9m | ETA 2.3m
Epoch 425/500 | Batch 100/202 | Rec 0.000579 | Seg 0.285135 | Elapsed 2.1m | ETA 2.1m
Epoch 425/500 | Batch 110/202 | Rec 0.000570 | Seg 0.282286 | Elapsed 2.3m | ETA 1.9m
Epoch 425/500 | Batch 120/202 | Rec 0.000562 | Seg 0.273827 | Elapsed 2.5m | ETA 1.7m
Epoch 425/500 | Batch 130/202 | Rec 0.000571 | Seg 0.279752 | Elapsed 2.7m | ETA 1.5m
Epoch 425/500 | Batch 140/202 | Rec 0.000563 | Seg 0.279611 | Elapsed 2.9m | ETA 1.3m
Epoch 425/500 | Batch 150/202 | Rec 0.000567 | Seg 0.277134 | Elapsed 3.1m | ETA 1.1m
Epoch 425/500 | Batch 160/202 | Rec 0.000560 | Seg 0.274263 | Elapsed 3.3m | ETA 0.9m
Epoch 425/500 | Batch 170/202 | Rec 0.000559 | Seg 0.275142 | Elapsed 3.5m | ETA 0.7m
Epoch 425/500 | Batch 180/202 | Rec 0.000560 | Seg 0.276371 | Elapsed 3.7m | ETA 0.5m
Epoch 425/500 | Batch 190/202 | Rec 0.000562 | Seg 0.276692 | Elapsed 3.9m | ETA 0.2m
Epoch 425/500 | Batch 200/202 | Rec 0.000568 | Seg 0.278457 | Elapsed 4.1m | ETA 0.0m
Epoch 425/500 | Batch 202/202 | Rec 0.000567 | Seg 0.276927 | Elapsed 4.2m | ETA 0.0m

2026-10-10 11:05:04,227 - INFO: Rec loss: 0.0005667650925040494
2026-10-10 11:05:04,227 - INFO: Seg loss: 0.2769270408345331
2026-10-10 11:05:04,227 - INFO: λ_rec: 1
2026-10-10 11:05:04,228 - INFO: λ_seg: 0.0001
2026-10-10 11:06:23,716 - INFO: -------------------Epoch: 425------------------------
2026-10-10 11:06:23,720 - INFO:
Validation stats:
      PSNR      SSIM       MSE
0  39.0804  0.975053  0.000129
2026-10-10 11:06:23,728 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.996002  0.997947  0.997668  0.998326  0.996185
real potato   0.820072  0.901093  0.972103  0.839837  0.999780
fake potato   0.765606  0.867195  0.967019  0.786133  0.999825
real apple    0.769885  0.869933  0.916023  0.828350  0.999146
fake apple    0.576259  0.731126  0.985138  0.581313  0.998386
real orange   0.886914  0.940019  0.996112  0.889995  0.999850
fake orange   0.925919  0.961485  0.935917  0.988594  0.999774
real grape    0.815895  0.898565  0.937505  0.862822  0.999594
fake grape    0.899954  0.947293  0.920107  0.976241  0.999599
real lemon    0.558966  0.717050  0.604217  0.881849  0.999182
fake lemon    0.866838  0.928620  0.986773  0.877028  0.999715
real avocado  0.920361  0.958479  0.945812  0.971593  0.999922
fake avocado  0.585873  0.738818  0.999782  0.585947  0.999504
real pepper   0.875226  0.933412  0.901843  0.967379  0.999496
fake pepper   0.802942  0.890652  0.945375  0.842008  0.999507
real plant    0.880605  0.936462  0.955782  0.918004  0.998755
fake plant    0.786148  0.880222  0.845244  0.918328  0.999801
real banana   0.580783  0.734755  0.883756  0.628820  0.998980
fake banana   0.694265  0.819497  0.766443  0.880557  0.999287
real onion    0.650164  0.787950  0.699150  0.902719  0.999561
fake onion    0.907936  0.951697  0.990583  0.915840  0.999941
real unknown  0.709723  0.830171  0.734754  0.954198  0.999938
fake unknown  0.196555  0.328501  0.211829  0.731619  0.997480
total         0.759691  0.850041  0.873867  0.857717  0.999270
total(-bg)    0.748950  0.843318  0.868239  0.851326  0.999410
2026-10-10 11:06:24,190 - INFO: Epoch accounting: {'epoch': 425, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11325897, 50326, 37575, 110219, 139500, 81887, 90440, 168860, 262644, 81609, 54910, 35580, 35603, 177130, 68553, 161264, 26518, 92702, 67579, 68321, 32412, 12946, 55797], 'crops_with_class': [202, 26, 20, 35, 30, 22, 32, 28, 45, 33, 28, 14, 14, 46, 20, 22, 28, 24, 32, 29, 19, 12, 23], 'targeted_crops_by_class': [0, 4, 3, 3, 4, 4, 5, 6, 9, 7, 3, 2, 4, 4, 6, 9, 5, 6, 2, 2, 1, 7, 5], 'sampled_scene_counts': [3, 0, 1, 1, 0, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 2, 1, 1, 1, 2, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 2, 1, 2, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 4, 3, 0, 3, 0, 3, 1, 0, 1, 1, 1, 3, 1, 0, 1, 0, 2, 0, 4, 1, 1, 1, 4, 2, 2, 3, 0, 2, 1, 1, 3, 1, 2, 5, 2, 0, 1, 0, 0, 1, 2, 0, 0, 2, 3, 3, 2, 1, 1, 1, 0, 0, 3, 1, 0, 3, 2, 2, 0, 0, 1, 2, 3, 1, 0, 2, 0, 0, 1, 1, 0, 2, 2, 1], 'learning_rate': 5.8291946154244606e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005667650925040494, 'train_segmentation_loss': 0.2769270408345331, 'val_foreground_miou_all22': 0.7489495281697821, 'val_psnr_ref1': 39.08040008544922, 'elapsed_seconds': 329.8395960330963, 'peak_cuda_allocated_gib': 7.502719879150391}

Epoch 426/500 | Batch 10/202 | Rec 0.000616 | Seg 0.296520 | Elapsed 0.2m | ETA 4.0m
Epoch 426/500 | Batch 20/202 | Rec 0.000588 | Seg 0.309172 | Elapsed 0.4m | ETA 3.8m
Epoch 426/500 | Batch 30/202 | Rec 0.000565 | Seg 0.285453 | Elapsed 0.6m | ETA 3.6m
Epoch 426/500 | Batch 40/202 | Rec 0.000594 | Seg 0.309385 | Elapsed 0.8m | ETA 3.3m
Epoch 426/500 | Batch 50/202 | Rec 0.000606 | Seg 0.310180 | Elapsed 1.0m | ETA 3.1m
Epoch 426/500 | Batch 60/202 | Rec 0.000621 | Seg 0.315967 | Elapsed 1.2m | ETA 2.9m
Epoch 426/500 | Batch 70/202 | Rec 0.000626 | Seg 0.308615 | Elapsed 1.4m | ETA 2.7m
Epoch 426/500 | Batch 80/202 | Rec 0.000616 | Seg 0.306111 | Elapsed 1.6m | ETA 2.5m
Epoch 426/500 | Batch 90/202 | Rec 0.000608 | Seg 0.301101 | Elapsed 1.9m | ETA 2.3m
Epoch 426/500 | Batch 100/202 | Rec 0.000596 | Seg 0.299284 | Elapsed 2.1m | ETA 2.1m
Epoch 426/500 | Batch 110/202 | Rec 0.000599 | Seg 0.296406 | Elapsed 2.3m | ETA 1.9m
Epoch 426/500 | Batch 120/202 | Rec 0.000598 | Seg 0.294235 | Elapsed 2.5m | ETA 1.7m
Epoch 426/500 | Batch 130/202 | Rec 0.000611 | Seg 0.299943 | Elapsed 2.7m | ETA 1.5m
Epoch 426/500 | Batch 140/202 | Rec 0.000612 | Seg 0.299858 | Elapsed 2.9m | ETA 1.3m
Epoch 426/500 | Batch 150/202 | Rec 0.000614 | Seg 0.296701 | Elapsed 3.1m | ETA 1.1m
Epoch 426/500 | Batch 160/202 | Rec 0.000607 | Seg 0.292783 | Elapsed 3.3m | ETA 0.9m
Epoch 426/500 | Batch 170/202 | Rec 0.000608 | Seg 0.293460 | Elapsed 3.5m | ETA 0.7m
Epoch 426/500 | Batch 180/202 | Rec 0.000602 | Seg 0.289676 | Elapsed 3.7m | ETA 0.5m
Epoch 426/500 | Batch 190/202 | Rec 0.000593 | Seg 0.288572 | Elapsed 3.9m | ETA 0.2m
Epoch 426/500 | Batch 200/202 | Rec 0.000590 | Seg 0.287334 | Elapsed 4.1m | ETA 0.0m
Epoch 426/500 | Batch 202/202 | Rec 0.000591 | Seg 0.288567 | Elapsed 4.2m | ETA 0.0m

2026-10-10 11:10:34,714 - INFO: Rec loss: 0.0005914867017936829
2026-10-10 11:10:34,715 - INFO: Seg loss: 0.2885665052782486
2026-10-10 11:10:34,715 - INFO: λ_rec: 1
2026-10-10 11:10:34,715 - INFO: λ_seg: 0.0001
2026-10-10 11:11:54,113 - INFO: -------------------Epoch: 426------------------------
2026-10-10 11:11:54,116 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.270616  0.975401  0.000124
2026-10-10 11:11:54,123 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995943  0.997917  0.997443  0.998492  0.996127
real potato   0.778427  0.875361  0.968310  0.798776  0.999728
fake potato   0.959121  0.979084  0.980265  0.978006  0.999970
real apple    0.791564  0.883607  0.899675  0.868200  0.999211
fake apple    0.589855  0.741976  0.985737  0.594932  0.998438
real orange   0.902388  0.948640  0.996052  0.905628  0.999871
fake orange   0.923418  0.960134  0.942869  0.978147  0.999768
real grape    0.810863  0.895504  0.965998  0.834685  0.999594
fake grape    0.900335  0.947504  0.922125  0.974426  0.999601
real lemon    0.593996  0.745243  0.620690  0.932485  0.999251
fake lemon    0.840466  0.913269  0.963348  0.868229  0.999651
real avocado  0.906615  0.950971  0.934952  0.967652  0.999907
fake avocado  0.813503  0.897113  0.998749  0.814333  0.999777
real pepper   0.843414  0.915006  0.873308  0.960996  0.999347
fake pepper   0.748688  0.856236  0.941028  0.785545  0.999371
real plant    0.875799  0.933738  0.953249  0.915106  0.998702
fake plant    0.822959  0.902833  0.879339  0.927722  0.999841
real banana   0.587058  0.739758  0.880946  0.637648  0.998992
fake banana   0.719242  0.836647  0.811827  0.863139  0.999380
real onion    0.636331  0.777704  0.688296  0.893937  0.999538
fake onion    0.927026  0.962081  0.981873  0.943168  0.999953
real unknown  0.923005  0.959911  0.983000  0.937977  0.999987
fake unknown  0.217230  0.356885  0.246431  0.647048  0.998035
total         0.787272  0.868571  0.887631  0.870708  0.999306
total(-bg)    0.777787  0.862691  0.882639  0.864899  0.999451
2026-10-10 11:11:54,738 - INFO: Epoch accounting: {'epoch': 426, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11196437, 45151, 60780, 107776, 160951, 101839, 70592, 145907, 216479, 69177, 71934, 58113, 40474, 265627, 103382, 174111, 26222, 71642, 79775, 62534, 30553, 11915, 66901], 'crops_with_class': [202, 26, 27, 28, 39, 27, 26, 32, 39, 31, 29, 18, 15, 60, 24, 26, 25, 20, 26, 25, 14, 13, 25], 'targeted_crops_by_class': [0, 7, 3, 1, 6, 7, 2, 5, 2, 2, 5, 7, 2, 8, 4, 3, 5, 2, 9, 5, 2, 3, 5], 'sampled_scene_counts': [1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 2, 2, 1, 0, 1, 1, 0, 1, 2, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 2, 2, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 3, 1, 2, 1, 1, 0, 0, 0, 3, 2, 2, 3, 3, 3, 1, 2, 0, 1, 1, 1, 4, 0, 3, 2, 0, 2, 1, 1, 2, 1, 2, 3, 0, 2, 1, 1, 3, 4, 3, 2, 3, 0, 0, 1, 2, 1, 1, 1, 1, 1, 1, 0, 1, 2, 2, 1, 0, 0, 2, 1, 3, 2, 1, 2, 0, 4, 2, 1, 0, 2, 1, 1, 2, 1, 0, 0, 2, 0, 1], 'learning_rate': 5.686049606105148e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005914867017936829, 'train_segmentation_loss': 0.2885665052782486, 'val_foreground_miou_all22': 0.7777865319119104, 'val_psnr_ref1': 39.27061645507813, 'elapsed_seconds': 330.54102206230164, 'peak_cuda_allocated_gib': 7.509799957275391}

Epoch 427/500 | Batch 10/202 | Rec 0.000443 | Seg 0.215986 | Elapsed 0.2m | ETA 3.9m
Epoch 427/500 | Batch 20/202 | Rec 0.000443 | Seg 0.197502 | Elapsed 0.4m | ETA 3.8m
Epoch 427/500 | Batch 30/202 | Rec 0.000536 | Seg 0.261011 | Elapsed 0.6m | ETA 3.6m
Epoch 427/500 | Batch 40/202 | Rec 0.000509 | Seg 0.257092 | Elapsed 0.8m | ETA 3.3m
Epoch 427/500 | Batch 50/202 | Rec 0.000506 | Seg 0.259445 | Elapsed 1.0m | ETA 3.1m
Epoch 427/500 | Batch 60/202 | Rec 0.000539 | Seg 0.254240 | Elapsed 1.2m | ETA 2.9m
Epoch 427/500 | Batch 70/202 | Rec 0.000534 | Seg 0.255095 | Elapsed 1.4m | ETA 2.7m
Epoch 427/500 | Batch 80/202 | Rec 0.000542 | Seg 0.262172 | Elapsed 1.6m | ETA 2.5m
Epoch 427/500 | Batch 90/202 | Rec 0.000540 | Seg 0.259033 | Elapsed 1.8m | ETA 2.3m
Epoch 427/500 | Batch 100/202 | Rec 0.000537 | Seg 0.256362 | Elapsed 2.0m | ETA 2.1m
Epoch 427/500 | Batch 110/202 | Rec 0.000530 | Seg 0.254081 | Elapsed 2.3m | ETA 1.9m
Epoch 427/500 | Batch 120/202 | Rec 0.000536 | Seg 0.258794 | Elapsed 2.5m | ETA 1.7m
Epoch 427/500 | Batch 130/202 | Rec 0.000538 | Seg 0.259543 | Elapsed 2.7m | ETA 1.5m
Epoch 427/500 | Batch 140/202 | Rec 0.000534 | Seg 0.258477 | Elapsed 2.9m | ETA 1.3m
Epoch 427/500 | Batch 150/202 | Rec 0.000533 | Seg 0.261542 | Elapsed 3.1m | ETA 1.1m
Epoch 427/500 | Batch 160/202 | Rec 0.000526 | Seg 0.260918 | Elapsed 3.3m | ETA 0.9m
Epoch 427/500 | Batch 170/202 | Rec 0.000531 | Seg 0.264207 | Elapsed 3.5m | ETA 0.7m
Epoch 427/500 | Batch 180/202 | Rec 0.000526 | Seg 0.262126 | Elapsed 3.7m | ETA 0.5m
Epoch 427/500 | Batch 190/202 | Rec 0.000536 | Seg 0.265595 | Elapsed 3.9m | ETA 0.2m
Epoch 427/500 | Batch 200/202 | Rec 0.000545 | Seg 0.269314 | Elapsed 4.1m | ETA 0.0m
Epoch 427/500 | Batch 202/202 | Rec 0.000543 | Seg 0.267636 | Elapsed 4.2m | ETA 0.0m

2026-10-10 11:16:03,955 - INFO: Rec loss: 0.0005430848080385937
2026-10-10 11:16:03,955 - INFO: Seg loss: 0.2676360843758477
2026-10-10 11:16:03,955 - INFO: λ_rec: 1
2026-10-10 11:16:03,955 - INFO: λ_seg: 0.0001
2026-10-10 11:17:20,725 - INFO: -------------------Epoch: 427------------------------
2026-10-10 11:17:20,729 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.225526  0.975214  0.000125
2026-10-10 11:17:20,736 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995740  0.997816  0.997071  0.998661  0.995933
real potato   0.493531  0.660847  0.989321  0.496174  0.999391
fake potato   0.706964  0.828280  0.981354  0.716590  0.999784
real apple    0.708267  0.829173  0.783173  0.881026  0.998748
fake apple    0.576016  0.730931  0.994919  0.577716  0.998394
real orange   0.921888  0.959306  0.996135  0.925197  0.999897
fake orange   0.925801  0.961421  0.954751  0.968287  0.999778
real grape    0.845615  0.916301  0.932577  0.900680  0.999657
fake grape    0.897877  0.946141  0.923400  0.970136  0.999592
real lemon    0.557327  0.715701  0.569705  0.962477  0.999102
fake lemon    0.846869  0.917037  0.981811  0.860368  0.999671
real avocado  0.803908  0.891246  0.832312  0.959277  0.999783
fake avocado  0.753472  0.859357  0.998818  0.754144  0.999705
real pepper   0.775335  0.873402  0.817937  0.937052  0.999007
fake pepper   0.615248  0.761752  0.936252  0.642148  0.999043
real plant    0.875808  0.933743  0.969087  0.900979  0.998722
fake plant    0.751549  0.858104  0.796454  0.930215  0.999755
real banana   0.540871  0.701985  0.877559  0.585020  0.998884
fake banana   0.743769  0.853009  0.849724  0.856420  0.999457
real onion    0.586130  0.739020  0.766274  0.713731  0.999545
fake onion    0.928588  0.962922  0.986802  0.940266  0.999954
real unknown  0.920605  0.958611  0.989837  0.929389  0.999987
fake unknown  0.208064  0.344420  0.231923  0.669142  0.997854
total         0.738228  0.834805  0.876400  0.829352  0.999202
total(-bg)    0.726523  0.827396  0.870915  0.821656  0.999350
2026-10-10 11:17:21,200 - INFO: Epoch accounting: {'epoch': 427, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11350216, 31312, 46756, 127634, 147650, 103470, 82831, 150014, 154768, 76619, 64469, 49484, 30831, 200374, 118470, 200122, 22637, 70710, 61060, 61537, 34507, 9936, 42865], 'crops_with_class': [202, 20, 22, 37, 38, 36, 29, 31, 27, 31, 28, 16, 16, 44, 25, 25, 23, 21, 29, 30, 19, 12, 17], 'targeted_crops_by_class': [0, 8, 2, 3, 5, 5, 8, 8, 2, 5, 6, 6, 6, 6, 3, 5, 3, 2, 5, 3, 3, 4, 6], 'sampled_scene_counts': [0, 1, 2, 0, 1, 1, 0, 0, 1, 3, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 2, 1, 0, 0, 1, 2, 1, 1, 2, 1, 3, 1, 2, 0, 1, 2, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 0, 1, 2, 3, 0, 1, 0, 1, 0, 0, 1, 0, 3, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 3, 1, 1, 1, 1, 0, 0, 0, 1, 1, 4, 2, 2, 2, 0, 0, 2, 1, 1, 3, 6, 2, 2, 1, 1, 2, 0, 0, 0, 0, 2, 1, 2, 1, 3, 2, 1, 3, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 3, 2, 0, 1, 0, 0, 0, 2, 1, 1, 3, 1, 0, 3, 1, 0, 3, 0, 1, 1, 1, 0, 2, 1, 2, 2, 1, 1], 'learning_rate': 5.544658970455711e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005430848080385937, 'train_segmentation_loss': 0.2676360843758477, 'val_foreground_miou_all22': 0.7265228687174415, 'val_psnr_ref1': 39.2255256652832, 'elapsed_seconds': 326.45497822761536, 'peak_cuda_allocated_gib': 7.506137847900391}

Epoch 428/500 | Batch 10/202 | Rec 0.000537 | Seg 0.242001 | Elapsed 0.2m | ETA 4.1m
Epoch 428/500 | Batch 20/202 | Rec 0.000588 | Seg 0.272156 | Elapsed 0.4m | ETA 3.8m
Epoch 428/500 | Batch 30/202 | Rec 0.000569 | Seg 0.269501 | Elapsed 0.6m | ETA 3.6m
Epoch 428/500 | Batch 40/202 | Rec 0.000589 | Seg 0.281292 | Elapsed 0.8m | ETA 3.3m
Epoch 428/500 | Batch 50/202 | Rec 0.000587 | Seg 0.272360 | Elapsed 1.0m | ETA 3.1m
Epoch 428/500 | Batch 60/202 | Rec 0.000572 | Seg 0.282449 | Elapsed 1.2m | ETA 2.9m
Epoch 428/500 | Batch 70/202 | Rec 0.000574 | Seg 0.283988 | Elapsed 1.4m | ETA 2.7m
Epoch 428/500 | Batch 80/202 | Rec 0.000571 | Seg 0.281216 | Elapsed 1.6m | ETA 2.5m
Epoch 428/500 | Batch 90/202 | Rec 0.000564 | Seg 0.277805 | Elapsed 1.8m | ETA 2.3m
Epoch 428/500 | Batch 100/202 | Rec 0.000561 | Seg 0.277489 | Elapsed 2.0m | ETA 2.1m
Epoch 428/500 | Batch 110/202 | Rec 0.000553 | Seg 0.277799 | Elapsed 2.2m | ETA 1.9m
Epoch 428/500 | Batch 120/202 | Rec 0.000561 | Seg 0.283509 | Elapsed 2.5m | ETA 1.7m
Epoch 428/500 | Batch 130/202 | Rec 0.000570 | Seg 0.288167 | Elapsed 2.7m | ETA 1.5m
Epoch 428/500 | Batch 140/202 | Rec 0.000591 | Seg 0.286133 | Elapsed 2.9m | ETA 1.3m
Epoch 428/500 | Batch 150/202 | Rec 0.000586 | Seg 0.284753 | Elapsed 3.1m | ETA 1.1m
Epoch 428/500 | Batch 160/202 | Rec 0.000590 | Seg 0.286523 | Elapsed 3.3m | ETA 0.9m
Epoch 428/500 | Batch 170/202 | Rec 0.000594 | Seg 0.286724 | Elapsed 3.5m | ETA 0.7m
Epoch 428/500 | Batch 180/202 | Rec 0.000590 | Seg 0.286514 | Elapsed 3.7m | ETA 0.5m
Epoch 428/500 | Batch 190/202 | Rec 0.000586 | Seg 0.284871 | Elapsed 3.9m | ETA 0.2m
Epoch 428/500 | Batch 200/202 | Rec 0.000585 | Seg 0.282467 | Elapsed 4.1m | ETA 0.0m
Epoch 428/500 | Batch 202/202 | Rec 0.000587 | Seg 0.282709 | Elapsed 4.1m | ETA 0.0m

2026-10-10 11:21:29,996 - INFO: Rec loss: 0.0005868086551741402
2026-10-10 11:21:29,996 - INFO: Seg loss: 0.282709017285321
2026-10-10 11:21:29,996 - INFO: λ_rec: 1
2026-10-10 11:21:29,996 - INFO: λ_seg: 0.0001
2026-10-10 11:22:49,744 - INFO: -------------------Epoch: 428------------------------
2026-10-10 11:22:49,748 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.092368  0.975105  0.000129
2026-10-10 11:22:49,755 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995786  0.997839  0.997356  0.998422  0.995978
real potato   0.899703  0.947154  0.930708  0.964295  0.999871
fake potato   0.966550  0.982940  0.985474  0.980519  0.999975
real apple    0.747805  0.855658  0.977500  0.760902  0.999115
fake apple    0.624930  0.769130  0.987953  0.629728  0.998573
real orange   0.868800  0.929745  0.993028  0.874132  0.999826
fake orange   0.911721  0.953772  0.926708  0.982571  0.999728
real grape    0.763325  0.865729  0.920197  0.817438  0.999471
fake grape    0.905575  0.950398  0.930216  0.971579  0.999625
real lemon    0.721519  0.838186  0.771447  0.917684  0.999584
fake lemon    0.854820  0.921679  0.997063  0.856978  0.999692
real avocado  0.923330  0.960087  0.951467  0.968966  0.999925
fake avocado  0.761346  0.864456  0.999665  0.761540  0.999714
real pepper   0.807748  0.893601  0.836994  0.958535  0.999165
fake pepper   0.675415  0.806217  0.953263  0.698547  0.999200
real plant    0.866204  0.928256  0.948014  0.909400  0.998595
fake plant    0.787472  0.881052  0.825461  0.944785  0.999797
real banana   0.724961  0.840504  0.893116  0.793834  0.999323
fake banana   0.724740  0.840355  0.811366  0.871599  0.999391
real onion    0.593721  0.745028  0.606972  0.964533  0.999404
fake onion    0.939143  0.968566  0.978293  0.959129  0.999961
real unknown  0.546060  0.706342  0.566168  0.938931  0.999875
fake unknown  0.253330  0.404211  0.279495  0.730170  0.998187
total         0.776696  0.863083  0.872518  0.880618  0.999303
total(-bg)    0.766737  0.856957  0.866844  0.875263  0.999454
2026-10-10 11:22:50,208 - INFO: Epoch accounting: {'epoch': 428, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11232598, 52245, 55300, 108075, 134998, 77724, 64537, 173602, 203663, 92024, 63627, 68029, 49043, 188339, 125270, 210121, 26248, 55752, 69269, 77035, 45281, 12464, 53028], 'crops_with_class': [202, 28, 25, 30, 43, 23, 26, 28, 39, 39, 25, 24, 17, 51, 32, 24, 27, 18, 26, 35, 18, 14, 23], 'targeted_crops_by_class': [0, 3, 4, 4, 5, 3, 3, 3, 3, 7, 7, 8, 6, 4, 6, 8, 5, 4, 5, 4, 0, 8, 6], 'sampled_scene_counts': [2, 0, 0, 1, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 2, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 3, 0, 0, 0, 1, 0, 2, 1, 1, 0, 1, 0, 1, 2, 2, 0, 0, 1, 0, 1, 2, 3, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 5, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 3, 1, 0, 2, 1, 0, 4, 1, 1, 1, 2, 2, 3, 2, 3, 1, 3, 2, 2, 3, 1, 1, 0, 3, 3, 1, 0, 1, 1, 2, 0, 2, 0, 5, 1, 0, 4, 2, 0, 3, 0, 3, 1, 3, 1, 1, 2, 1, 1, 0, 2, 0, 4, 1, 2, 2, 1, 1, 0, 0, 1, 1, 2, 3, 1, 1, 1, 0, 0, 1, 1, 2, 0, 1, 2, 1, 0, 1, 1, 1], 'learning_rate': 5.405028290336352e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005868086551741402, 'train_segmentation_loss': 0.282709017285321, 'val_foreground_miou_all22': 0.7667370310304468, 'val_psnr_ref1': 39.092367553710936, 'elapsed_seconds': 329.000675201416, 'peak_cuda_allocated_gib': 7.508335113525391}

Epoch 429/500 | Batch 10/202 | Rec 0.000517 | Seg 0.198505 | Elapsed 0.2m | ETA 4.0m
Epoch 429/500 | Batch 20/202 | Rec 0.000584 | Seg 0.243666 | Elapsed 0.4m | ETA 3.8m
Epoch 429/500 | Batch 30/202 | Rec 0.000611 | Seg 0.252236 | Elapsed 0.6m | ETA 3.5m
Epoch 429/500 | Batch 40/202 | Rec 0.000621 | Seg 0.248354 | Elapsed 0.8m | ETA 3.3m
Epoch 429/500 | Batch 50/202 | Rec 0.000648 | Seg 0.247770 | Elapsed 1.0m | ETA 3.1m
Epoch 429/500 | Batch 60/202 | Rec 0.000646 | Seg 0.262679 | Elapsed 1.2m | ETA 2.9m
Epoch 429/500 | Batch 70/202 | Rec 0.000630 | Seg 0.264894 | Elapsed 1.4m | ETA 2.7m
Epoch 429/500 | Batch 80/202 | Rec 0.000608 | Seg 0.259485 | Elapsed 1.6m | ETA 2.5m
Epoch 429/500 | Batch 90/202 | Rec 0.000607 | Seg 0.261787 | Elapsed 1.8m | ETA 2.3m
Epoch 429/500 | Batch 100/202 | Rec 0.000606 | Seg 0.266571 | Elapsed 2.0m | ETA 2.1m
Epoch 429/500 | Batch 110/202 | Rec 0.000610 | Seg 0.271767 | Elapsed 2.2m | ETA 1.9m
Epoch 429/500 | Batch 120/202 | Rec 0.000606 | Seg 0.271620 | Elapsed 2.4m | ETA 1.7m
Epoch 429/500 | Batch 130/202 | Rec 0.000603 | Seg 0.273373 | Elapsed 2.6m | ETA 1.5m
Epoch 429/500 | Batch 140/202 | Rec 0.000601 | Seg 0.270094 | Elapsed 2.8m | ETA 1.3m
Epoch 429/500 | Batch 150/202 | Rec 0.000596 | Seg 0.270267 | Elapsed 3.1m | ETA 1.1m
Epoch 429/500 | Batch 160/202 | Rec 0.000595 | Seg 0.269122 | Elapsed 3.3m | ETA 0.9m
Epoch 429/500 | Batch 170/202 | Rec 0.000590 | Seg 0.270529 | Elapsed 3.5m | ETA 0.7m
Epoch 429/500 | Batch 180/202 | Rec 0.000590 | Seg 0.270126 | Elapsed 3.7m | ETA 0.4m
Epoch 429/500 | Batch 190/202 | Rec 0.000588 | Seg 0.271424 | Elapsed 3.9m | ETA 0.2m
Epoch 429/500 | Batch 200/202 | Rec 0.000585 | Seg 0.273007 | Elapsed 4.1m | ETA 0.0m
Epoch 429/500 | Batch 202/202 | Rec 0.000588 | Seg 0.273509 | Elapsed 4.1m | ETA 0.0m

2026-10-10 11:26:57,772 - INFO: Rec loss: 0.0005884553571053006
2026-10-10 11:26:57,772 - INFO: Seg loss: 0.27350942454863303
2026-10-10 11:26:57,772 - INFO: λ_rec: 1
2026-10-10 11:26:57,772 - INFO: λ_seg: 0.0001
2026-10-10 11:28:14,416 - INFO: -------------------Epoch: 429------------------------
2026-10-10 11:28:14,420 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.165305  0.974954  0.000127
2026-10-10 11:28:14,427 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995804  0.997848  0.997182  0.998615  0.995995
real potato   0.825262  0.904217  0.974934  0.843152  0.999786
fake potato   0.896117  0.945163  0.968153  0.923335  0.999922
real apple    0.794142  0.885211  0.927602  0.846617  0.999243
fake apple    0.606883  0.755307  0.980519  0.614290  0.998498
real orange   0.928826  0.963050  0.994206  0.933881  0.999906
fake orange   0.936768  0.967302  0.958122  0.976762  0.999811
real grape    0.806203  0.892655  0.973173  0.824527  0.999586
fake grape    0.891241  0.942444  0.922199  0.963701  0.999565
real lemon    0.501904  0.668310  0.529122  0.907037  0.998942
fake lemon    0.853957  0.921177  0.978822  0.870032  0.999685
real avocado  0.894729  0.944390  0.930518  0.958785  0.999895
fake avocado  0.696788  0.821254  0.999269  0.697144  0.999637
real pepper   0.856083  0.922412  0.885165  0.963040  0.999408
fake pepper   0.759885  0.863512  0.947127  0.793547  0.999402
real plant    0.872337  0.931766  0.954005  0.910636  0.998667
fake plant    0.798188  0.887719  0.864619  0.912193  0.999816
real banana   0.478555  0.647281  0.874870  0.513717  0.998742
fake banana   0.688954  0.815785  0.790600  0.842734  0.999300
real onion    0.655319  0.791725  0.700546  0.910319  0.999567
fake onion    0.917412  0.956877  0.971350  0.942926  0.999946
real unknown  0.895124  0.944610  0.961462  0.928435  0.999983
fake unknown  0.223618  0.365464  0.249047  0.686527  0.997992
total         0.772787  0.858064  0.884027  0.859215  0.999274
total(-bg)    0.762650  0.851711  0.878883  0.852879  0.999423
2026-10-10 11:28:14,893 - INFO: Epoch accounting: {'epoch': 429, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11281211, 27065, 33885, 125703, 141399, 74176, 70330, 174062, 222415, 65281, 86431, 64785, 45036, 224186, 118567, 119877, 45987, 66548, 49596, 81457, 61567, 12241, 46467], 'crops_with_class': [202, 18, 16, 37, 40, 24, 25, 39, 39, 33, 32, 22, 16, 52, 28, 19, 36, 18, 24, 32, 23, 15, 21], 'targeted_crops_by_class': [0, 6, 1, 2, 5, 5, 6, 9, 4, 3, 8, 10, 5, 4, 7, 1, 8, 3, 1, 6, 5, 9, 6], 'sampled_scene_counts': [1, 1, 0, 0, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 2, 3, 0, 2, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 0, 2, 1, 0, 2, 3, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 1, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 3, 5, 2, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 4, 3, 3, 2, 1, 0, 1, 1, 1, 1, 2, 4, 0, 1, 0, 1, 1, 0, 0, 0, 3, 1, 3, 1, 1, 2, 2, 3, 0, 0, 1, 4, 2, 2, 1, 1, 4, 3, 2, 3, 0, 2, 0, 1, 1, 1, 2, 1, 2, 0, 0, 1, 0, 0, 1, 2, 2, 0, 0, 0, 1, 2, 1, 3, 2, 1, 0, 2, 3, 0, 0, 1, 1, 4, 1, 1, 1, 0], 'learning_rate': 5.267163078127235e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005884553571053006, 'train_segmentation_loss': 0.27350942454863303, 'val_foreground_miou_all22': 0.7626498390326012, 'val_psnr_ref1': 39.16530548095703, 'elapsed_seconds': 324.6772859096527, 'peak_cuda_allocated_gib': 7.514225006103516}

Epoch 430/500 | Batch 10/202 | Rec 0.000531 | Seg 0.235959 | Elapsed 0.2m | ETA 3.9m
Epoch 430/500 | Batch 20/202 | Rec 0.000522 | Seg 0.248636 | Elapsed 0.4m | ETA 3.8m
Epoch 430/500 | Batch 30/202 | Rec 0.000552 | Seg 0.263544 | Elapsed 0.6m | ETA 3.5m
Epoch 430/500 | Batch 40/202 | Rec 0.000511 | Seg 0.242381 | Elapsed 0.8m | ETA 3.3m
Epoch 430/500 | Batch 50/202 | Rec 0.000549 | Seg 0.254602 | Elapsed 1.0m | ETA 3.1m
Epoch 430/500 | Batch 60/202 | Rec 0.000545 | Seg 0.248115 | Elapsed 1.2m | ETA 2.9m
Epoch 430/500 | Batch 70/202 | Rec 0.000548 | Seg 0.256658 | Elapsed 1.4m | ETA 2.7m
Epoch 430/500 | Batch 80/202 | Rec 0.000545 | Seg 0.257476 | Elapsed 1.7m | ETA 2.5m
Epoch 430/500 | Batch 90/202 | Rec 0.000546 | Seg 0.261299 | Elapsed 1.9m | ETA 2.3m
Epoch 430/500 | Batch 100/202 | Rec 0.000547 | Seg 0.257449 | Elapsed 2.1m | ETA 2.1m
Epoch 430/500 | Batch 110/202 | Rec 0.000546 | Seg 0.256172 | Elapsed 2.3m | ETA 1.9m
Epoch 430/500 | Batch 120/202 | Rec 0.000552 | Seg 0.257642 | Elapsed 2.5m | ETA 1.7m
Epoch 430/500 | Batch 130/202 | Rec 0.000555 | Seg 0.261384 | Elapsed 2.7m | ETA 1.5m
Epoch 430/500 | Batch 140/202 | Rec 0.000556 | Seg 0.263860 | Elapsed 2.9m | ETA 1.3m
Epoch 430/500 | Batch 150/202 | Rec 0.000550 | Seg 0.266361 | Elapsed 3.1m | ETA 1.1m
Epoch 430/500 | Batch 160/202 | Rec 0.000557 | Seg 0.267457 | Elapsed 3.3m | ETA 0.9m
Epoch 430/500 | Batch 170/202 | Rec 0.000553 | Seg 0.263081 | Elapsed 3.5m | ETA 0.7m
Epoch 430/500 | Batch 180/202 | Rec 0.000556 | Seg 0.264677 | Elapsed 3.7m | ETA 0.5m
Epoch 430/500 | Batch 190/202 | Rec 0.000560 | Seg 0.267095 | Elapsed 3.9m | ETA 0.2m
Epoch 430/500 | Batch 200/202 | Rec 0.000569 | Seg 0.269945 | Elapsed 4.1m | ETA 0.0m
Epoch 430/500 | Batch 202/202 | Rec 0.000568 | Seg 0.269560 | Elapsed 4.2m | ETA 0.0m

2026-10-10 11:32:23,926 - INFO: Rec loss: 0.0005682884773993311
2026-10-10 11:32:23,926 - INFO: Seg loss: 0.2695599944874792
2026-10-10 11:32:23,926 - INFO: λ_rec: 1
2026-10-10 11:32:23,926 - INFO: λ_seg: 0.0001
2026-10-10 11:33:38,894 - INFO: -------------------Epoch: 430------------------------
2026-10-10 11:33:38,898 - INFO:
Validation stats:
        PSNR     SSIM      MSE
0  39.060637  0.97502  0.00013
2026-10-10 11:33:38,905 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995818  0.997854  0.997273  0.998537  0.996008
real potato   0.832398  0.908484  0.974168  0.851186  0.999795
fake potato   0.877081  0.934466  0.979119  0.893800  0.999909
real apple    0.786756  0.880603  0.919523  0.844936  0.999210
fake apple    0.589135  0.741407  0.989080  0.592992  0.998439
real orange   0.944637  0.971480  0.995866  0.948356  0.999927
fake orange   0.948338  0.973434  0.970545  0.976442  0.999848
real grape    0.825866  0.904579  0.961573  0.854052  0.999624
fake grape    0.893682  0.943807  0.914638  0.975003  0.999571
real lemon    0.606479  0.754992  0.668200  0.867827  0.999338
fake lemon    0.836963  0.911197  0.959630  0.867508  0.999642
real avocado  0.867693  0.929110  0.897856  0.962726  0.999864
fake avocado  0.804129  0.891382  0.999208  0.804642  0.999765
real pepper   0.866475  0.928411  0.902846  0.955573  0.999461
fake pepper   0.778929  0.875679  0.942391  0.817873  0.999447
real plant    0.871844  0.931485  0.961006  0.903817  0.998671
fake plant    0.825152  0.904151  0.875696  0.934624  0.999842
real banana   0.667742  0.800724  0.885543  0.730816  0.999183
fake banana   0.689103  0.815890  0.767219  0.871267  0.999277
real onion    0.637336  0.778454  0.676771  0.916230  0.999529
fake onion    0.928790  0.963031  0.973795  0.952600  0.999954
real unknown  0.883847  0.938293  0.947471  0.929389  0.999980
fake unknown  0.215048  0.353935  0.245447  0.634553  0.998048
total         0.790141  0.870993  0.887168  0.873250  0.999319
total(-bg)    0.780792  0.865227  0.882163  0.867555  0.999469
2026-10-10 11:33:39,384 - INFO: Epoch accounting: {'epoch': 430, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11333536, 60580, 57948, 164215, 142657, 53307, 60033, 132078, 205769, 91573, 48915, 33785, 41148, 217852, 106429, 174482, 31332, 79165, 66110, 68681, 32399, 6902, 29376], 'crops_with_class': [202, 31, 27, 39, 36, 17, 20, 24, 31, 38, 24, 12, 15, 50, 32, 24, 26, 21, 27, 30, 17, 8, 11], 'targeted_crops_by_class': [0, 5, 6, 5, 6, 2, 5, 5, 5, 8, 3, 6, 4, 9, 2, 7, 6, 5, 4, 1, 2, 5, 1], 'sampled_scene_counts': [1, 0, 0, 2, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 3, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 3, 1, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2, 3, 1, 2, 2, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 0, 0, 2, 1, 3, 2, 2, 3, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 1, 1, 1, 2, 1, 2, 1, 1, 1, 0, 4, 3, 0, 0, 2, 1, 1, 3, 1, 2, 0, 1, 1, 1, 3, 2, 1, 2, 2, 1, 2, 0, 1, 1, 2, 3, 4, 1, 0, 0, 1, 0, 1, 2, 0, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 3, 3, 0, 1, 0, 1], 'learning_rate': 5.131068776510875e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005682884773993311, 'train_segmentation_loss': 0.2695599944874792, 'val_foreground_miou_all22': 0.7807919939683992, 'val_psnr_ref1': 39.06063705444336, 'elapsed_seconds': 324.4833188056946, 'peak_cuda_allocated_gib': 7.509799957275391}

Epoch 431/500 | Batch 10/202 | Rec 0.000596 | Seg 0.247799 | Elapsed 0.2m | ETA 4.0m
Epoch 431/500 | Batch 20/202 | Rec 0.000779 | Seg 0.287918 | Elapsed 0.4m | ETA 3.8m
Epoch 431/500 | Batch 30/202 | Rec 0.000732 | Seg 0.304840 | Elapsed 0.6m | ETA 3.6m
Epoch 431/500 | Batch 40/202 | Rec 0.000651 | Seg 0.278076 | Elapsed 0.8m | ETA 3.4m
Epoch 431/500 | Batch 50/202 | Rec 0.000660 | Seg 0.286841 | Elapsed 1.0m | ETA 3.1m
Epoch 431/500 | Batch 60/202 | Rec 0.000678 | Seg 0.307973 | Elapsed 1.2m | ETA 2.9m
Epoch 431/500 | Batch 70/202 | Rec 0.000645 | Seg 0.300353 | Elapsed 1.4m | ETA 2.7m
Epoch 431/500 | Batch 80/202 | Rec 0.000640 | Seg 0.303703 | Elapsed 1.6m | ETA 2.5m
Epoch 431/500 | Batch 90/202 | Rec 0.000628 | Seg 0.296046 | Elapsed 1.8m | ETA 2.3m
Epoch 431/500 | Batch 100/202 | Rec 0.000621 | Seg 0.297483 | Elapsed 2.0m | ETA 2.1m
Epoch 431/500 | Batch 110/202 | Rec 0.000620 | Seg 0.296155 | Elapsed 2.2m | ETA 1.9m
Epoch 431/500 | Batch 120/202 | Rec 0.000613 | Seg 0.293765 | Elapsed 2.5m | ETA 1.7m
Epoch 431/500 | Batch 130/202 | Rec 0.000606 | Seg 0.291597 | Elapsed 2.7m | ETA 1.5m
Epoch 431/500 | Batch 140/202 | Rec 0.000608 | Seg 0.294121 | Elapsed 2.9m | ETA 1.3m
Epoch 431/500 | Batch 150/202 | Rec 0.000603 | Seg 0.294793 | Elapsed 3.1m | ETA 1.1m
Epoch 431/500 | Batch 160/202 | Rec 0.000591 | Seg 0.293026 | Elapsed 3.3m | ETA 0.9m
Epoch 431/500 | Batch 170/202 | Rec 0.000584 | Seg 0.290374 | Elapsed 3.5m | ETA 0.7m
Epoch 431/500 | Batch 180/202 | Rec 0.000578 | Seg 0.288525 | Elapsed 3.7m | ETA 0.4m
Epoch 431/500 | Batch 190/202 | Rec 0.000579 | Seg 0.284757 | Elapsed 3.9m | ETA 0.2m
Epoch 431/500 | Batch 200/202 | Rec 0.000573 | Seg 0.282614 | Elapsed 4.1m | ETA 0.0m
Epoch 431/500 | Batch 202/202 | Rec 0.000570 | Seg 0.280663 | Elapsed 4.1m | ETA 0.0m

2026-10-10 11:37:46,616 - INFO: Rec loss: 0.0005702448200254637
2026-10-10 11:37:46,616 - INFO: Seg loss: 0.2806631330179401
2026-10-10 11:37:46,616 - INFO: λ_rec: 1
2026-10-10 11:37:46,616 - INFO: λ_seg: 0.0001
2026-10-10 11:39:05,988 - INFO: -------------------Epoch: 431------------------------
2026-10-10 11:39:05,992 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.100205  0.975175  0.000129
2026-10-10 11:39:05,999 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995536  0.997713  0.997079  0.998448  0.995738
real potato   0.351077  0.519661  0.982967  0.353226  0.999219
fake potato   0.653918  0.790702  0.988376  0.658986  0.999746
real apple    0.673729  0.805014  0.774436  0.838213  0.998600
fake apple    0.598529  0.748803  0.990557  0.601964  0.998475
real orange   0.921478  0.959085  0.997001  0.924039  0.999896
fake orange   0.933649  0.965636  0.952981  0.978734  0.999801
real grape    0.809448  0.894641  0.936401  0.856537  0.999579
fake grape    0.890058  0.941781  0.918162  0.966753  0.999558
real lemon    0.458259  0.628457  0.472228  0.939366  0.998695
fake lemon    0.855860  0.922283  0.995653  0.859070  0.999694
real avocado  0.825109  0.904125  0.851567  0.963711  0.999810
fake avocado  0.568477  0.724832  1.000000  0.568477  0.999484
real pepper   0.770317  0.870209  0.813802  0.935133  0.998980
fake pepper   0.599298  0.749404  0.966535  0.611997  0.999025
real plant    0.873407  0.932376  0.949807  0.915670  0.998672
fake plant    0.681684  0.810666  0.824124  0.797738  0.999704
real banana   0.330167  0.496387  0.817828  0.356376  0.998375
fake banana   0.723616  0.839598  0.839301  0.839997  0.999410
real onion    0.618404  0.764165  0.674906  0.880763  0.999509
fake onion    0.879431  0.935798  0.996720  0.881983  0.999924
real unknown  0.673720  0.805008  0.702991  0.941794  0.999927
fake unknown  0.206807  0.342700  0.219692  0.779066  0.997482
total         0.690956  0.797785  0.854918  0.802089  0.999100
total(-bg)    0.677111  0.788697  0.848456  0.793163  0.999253
2026-10-10 11:39:06,458 - INFO: Epoch accounting: {'epoch': 431, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11285351, 33966, 51873, 100834, 150140, 75691, 83599, 146050, 156258, 83307, 69978, 57335, 41993, 196118, 143126, 178141, 24129, 95234, 79306, 83176, 51068, 10992, 40607], 'crops_with_class': [202, 22, 21, 35, 38, 25, 31, 25, 27, 39, 31, 19, 15, 50, 39, 20, 23, 31, 27, 36, 26, 14, 18], 'targeted_crops_by_class': [0, 3, 5, 3, 9, 1, 6, 5, 3, 7, 5, 7, 7, 4, 4, 6, 3, 9, 6, 0, 9, 4, 6], 'sampled_scene_counts': [1, 1, 1, 0, 1, 2, 2, 1, 0, 3, 0, 1, 3, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2, 1, 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 3, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 3, 1, 0, 4, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 2, 4, 2, 3, 2, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 4, 3, 1, 0, 3, 1, 1, 3, 1, 1, 5, 1, 0, 1, 1, 2, 2, 3, 2, 0, 1, 1, 1, 3, 0, 0, 2, 2, 0, 3, 1, 2, 1, 1, 0, 4, 1, 4, 0, 2, 2, 2, 1, 1, 1, 1, 0, 2, 0, 0, 2, 1, 1, 1, 2, 3, 0], 'learning_rate': 4.9967507582572766e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005702448200254637, 'train_segmentation_loss': 0.2806631330179401, 'val_foreground_miou_all22': 0.6771109944810058, 'val_psnr_ref1': 39.100204925537106, 'elapsed_seconds': 327.06757950782776, 'peak_cuda_allocated_gib': 7.514591217041016}

Epoch 432/500 | Batch 10/202 | Rec 0.000514 | Seg 0.218311 | Elapsed 0.2m | ETA 3.9m
Epoch 432/500 | Batch 20/202 | Rec 0.000565 | Seg 0.264512 | Elapsed 0.4m | ETA 3.7m
Epoch 432/500 | Batch 30/202 | Rec 0.000568 | Seg 0.279558 | Elapsed 0.6m | ETA 3.5m
Epoch 432/500 | Batch 40/202 | Rec 0.000568 | Seg 0.287531 | Elapsed 0.8m | ETA 3.3m
Epoch 432/500 | Batch 50/202 | Rec 0.000606 | Seg 0.304188 | Elapsed 1.0m | ETA 3.1m
Epoch 432/500 | Batch 60/202 | Rec 0.000608 | Seg 0.308824 | Elapsed 1.2m | ETA 2.9m
Epoch 432/500 | Batch 70/202 | Rec 0.000610 | Seg 0.306214 | Elapsed 1.4m | ETA 2.7m
Epoch 432/500 | Batch 80/202 | Rec 0.000625 | Seg 0.303223 | Elapsed 1.6m | ETA 2.5m
Epoch 432/500 | Batch 90/202 | Rec 0.000628 | Seg 0.299005 | Elapsed 1.8m | ETA 2.3m
Epoch 432/500 | Batch 100/202 | Rec 0.000629 | Seg 0.293922 | Elapsed 2.1m | ETA 2.1m
Epoch 432/500 | Batch 110/202 | Rec 0.000624 | Seg 0.293827 | Elapsed 2.3m | ETA 1.9m
Epoch 432/500 | Batch 120/202 | Rec 0.000618 | Seg 0.287910 | Elapsed 2.5m | ETA 1.7m
Epoch 432/500 | Batch 130/202 | Rec 0.000616 | Seg 0.284482 | Elapsed 2.7m | ETA 1.5m
Epoch 432/500 | Batch 140/202 | Rec 0.000612 | Seg 0.284467 | Elapsed 2.9m | ETA 1.3m
Epoch 432/500 | Batch 150/202 | Rec 0.000619 | Seg 0.288482 | Elapsed 3.1m | ETA 1.1m
Epoch 432/500 | Batch 160/202 | Rec 0.000615 | Seg 0.287341 | Elapsed 3.3m | ETA 0.9m
Epoch 432/500 | Batch 170/202 | Rec 0.000618 | Seg 0.289234 | Elapsed 3.5m | ETA 0.7m
Epoch 432/500 | Batch 180/202 | Rec 0.000619 | Seg 0.292473 | Elapsed 3.7m | ETA 0.5m
Epoch 432/500 | Batch 190/202 | Rec 0.000618 | Seg 0.290855 | Elapsed 3.9m | ETA 0.2m
Epoch 432/500 | Batch 200/202 | Rec 0.000609 | Seg 0.285636 | Elapsed 4.1m | ETA 0.0m
Epoch 432/500 | Batch 202/202 | Rec 0.000607 | Seg 0.285187 | Elapsed 4.2m | ETA 0.0m

2026-10-10 11:43:17,088 - INFO: Rec loss: 0.0006066429708124194
2026-10-10 11:43:17,088 - INFO: Seg loss: 0.28518704055707056
2026-10-10 11:43:17,088 - INFO: λ_rec: 1
2026-10-10 11:43:17,088 - INFO: λ_seg: 0.0001
2026-10-10 11:44:37,282 - INFO: -------------------Epoch: 432------------------------
2026-10-10 11:44:37,285 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  39.111742  0.97521  0.000129
2026-10-10 11:44:37,292 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995584  0.997737  0.997171  0.998404  0.995784
real potato   0.539908  0.701175  0.948066  0.556363  0.999433
fake potato   0.756349  0.861225  0.981511  0.767281  0.999820
real apple    0.713332  0.832634  0.811087  0.855462  0.998814
fake apple    0.597447  0.747955  0.994303  0.599499  0.998475
real orange   0.871724  0.931417  0.991632  0.878184  0.999830
fake orange   0.891630  0.942661  0.911093  0.976602  0.999660
real grape    0.797852  0.887512  0.938707  0.841701  0.999555
fake grape    0.903435  0.949218  0.924671  0.975209  0.999614
real lemon    0.595003  0.746036  0.611975  0.955466  0.999236
fake lemon    0.859503  0.924394  0.995259  0.863036  0.999702
real avocado  0.862443  0.926092  0.889713  0.965681  0.999857
fake avocado  0.794800  0.885620  0.999359  0.795205  0.999754
real pepper   0.745244  0.853979  0.777132  0.947814  0.998815
fake pepper   0.527176  0.690347  0.954361  0.540810  0.998844
real plant    0.866285  0.928303  0.957475  0.900949  0.998609
fake plant    0.808039  0.893779  0.893487  0.894172  0.999831
real banana   0.559237  0.717273  0.844463  0.623455  0.998896
fake banana   0.731619  0.844961  0.822956  0.868281  0.999414
real onion    0.625850  0.769825  0.689807  0.870968  0.999530
fake onion    0.947255  0.972863  0.990971  0.955502  0.999966
real unknown  0.727811  0.842416  0.763975  0.938931  0.999944
fake unknown  0.223992  0.365964  0.246497  0.710431  0.997926
total         0.736588  0.835365  0.866768  0.838235  0.999187
total(-bg)    0.724815  0.827984  0.860841  0.830955  0.999342
2026-10-10 11:44:37,748 - INFO: Epoch accounting: {'epoch': 432, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11248714, 48120, 59368, 141530, 159528, 71121, 72536, 151914, 264993, 55111, 56602, 33155, 39706, 198575, 85236, 202522, 38711, 87517, 56736, 89998, 43666, 4619, 28294], 'crops_with_class': [202, 30, 28, 34, 38, 24, 27, 29, 45, 26, 22, 14, 15, 50, 27, 28, 26, 22, 23, 37, 22, 6, 12], 'targeted_crops_by_class': [0, 5, 3, 4, 7, 5, 2, 6, 7, 2, 3, 3, 2, 4, 1, 6, 8, 3, 0, 8, 6, 3, 2], 'sampled_scene_counts': [1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 2, 2, 1, 1, 0, 0, 2, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 0, 2, 1, 1, 1, 3, 2, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 2, 1, 1, 1, 0, 2, 2, 0, 1, 0, 0, 1, 1, 2, 2, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 2, 2, 3, 3, 3, 2, 3, 1, 1, 2, 2, 1, 1, 1, 0, 3, 2, 2, 1, 1, 1, 0, 1, 1, 2, 2, 2, 0, 1, 0, 1, 1, 2, 0, 3, 0, 2, 0, 2, 2, 1, 0, 0, 0, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1, 1, 3, 0, 0, 2, 1, 0, 2, 1, 1, 1, 3, 1, 1, 2, 1, 4, 1, 2, 1, 0, 2, 2, 2, 1, 1, 3, 0], 'learning_rate': 4.864214326011782e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006066429708124194, 'train_segmentation_loss': 0.28518704055707056, 'val_foreground_miou_all22': 0.7248152421055667, 'val_psnr_ref1': 39.11174179077148, 'elapsed_seconds': 331.28265619277954, 'peak_cuda_allocated_gib': 7.508823394775391}

Epoch 433/500 | Batch 10/202 | Rec 0.000484 | Seg 0.263081 | Elapsed 0.2m | ETA 3.9m
Epoch 433/500 | Batch 20/202 | Rec 0.000581 | Seg 0.277549 | Elapsed 0.4m | ETA 3.7m
Epoch 433/500 | Batch 30/202 | Rec 0.000566 | Seg 0.278488 | Elapsed 0.6m | ETA 3.6m
Epoch 433/500 | Batch 40/202 | Rec 0.000568 | Seg 0.287013 | Elapsed 0.8m | ETA 3.3m
Epoch 433/500 | Batch 50/202 | Rec 0.000555 | Seg 0.272527 | Elapsed 1.0m | ETA 3.1m
Epoch 433/500 | Batch 60/202 | Rec 0.000562 | Seg 0.270925 | Elapsed 1.2m | ETA 2.9m
Epoch 433/500 | Batch 70/202 | Rec 0.000555 | Seg 0.270242 | Elapsed 1.4m | ETA 2.7m
Epoch 433/500 | Batch 80/202 | Rec 0.000576 | Seg 0.280746 | Elapsed 1.7m | ETA 2.5m
Epoch 433/500 | Batch 90/202 | Rec 0.000595 | Seg 0.291933 | Elapsed 1.9m | ETA 2.3m
Epoch 433/500 | Batch 100/202 | Rec 0.000589 | Seg 0.283783 | Elapsed 2.1m | ETA 2.1m
Epoch 433/500 | Batch 110/202 | Rec 0.000592 | Seg 0.286640 | Elapsed 2.3m | ETA 1.9m
Epoch 433/500 | Batch 120/202 | Rec 0.000584 | Seg 0.284263 | Elapsed 2.5m | ETA 1.7m
Epoch 433/500 | Batch 130/202 | Rec 0.000575 | Seg 0.282103 | Elapsed 2.7m | ETA 1.5m
Epoch 433/500 | Batch 140/202 | Rec 0.000580 | Seg 0.284566 | Elapsed 2.9m | ETA 1.3m
Epoch 433/500 | Batch 150/202 | Rec 0.000576 | Seg 0.281379 | Elapsed 3.1m | ETA 1.1m
Epoch 433/500 | Batch 160/202 | Rec 0.000582 | Seg 0.285659 | Elapsed 3.3m | ETA 0.9m
Epoch 433/500 | Batch 170/202 | Rec 0.000578 | Seg 0.283514 | Elapsed 3.5m | ETA 0.7m
Epoch 433/500 | Batch 180/202 | Rec 0.000567 | Seg 0.279087 | Elapsed 3.7m | ETA 0.5m
Epoch 433/500 | Batch 190/202 | Rec 0.000572 | Seg 0.284505 | Elapsed 3.9m | ETA 0.2m
Epoch 433/500 | Batch 200/202 | Rec 0.000568 | Seg 0.282830 | Elapsed 4.1m | ETA 0.0m
Epoch 433/500 | Batch 202/202 | Rec 0.000566 | Seg 0.281628 | Elapsed 4.2m | ETA 0.0m

2026-10-10 11:48:47,846 - INFO: Rec loss: 0.0005659272843547682
2026-10-10 11:48:47,846 - INFO: Seg loss: 0.2816283211370211
2026-10-10 11:48:47,846 - INFO: λ_rec: 1
2026-10-10 11:48:47,846 - INFO: λ_seg: 0.0001
2026-10-10 11:50:07,482 - INFO: -------------------Epoch: 433------------------------
2026-10-10 11:50:07,486 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.148437  0.975216  0.000127
2026-10-10 11:50:07,492 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995814  0.997853  0.997250  0.998557  0.996004
real potato   0.459292  0.629429  0.981627  0.463275  0.999347
fake potato   0.768089  0.868786  0.979753  0.780478  0.999828
real apple    0.730663  0.844324  0.812682  0.878638  0.998883
fake apple    0.638406  0.779253  0.980393  0.646662  0.998617
real orange   0.902329  0.948607  0.995420  0.906091  0.999871
fake orange   0.928033  0.962623  0.942682  0.983531  0.999782
real grape    0.815717  0.898457  0.966036  0.839801  0.999604
fake grape    0.898038  0.946230  0.920083  0.974013  0.999591
real lemon    0.562983  0.720348  0.581730  0.945858  0.999137
fake lemon    0.857911  0.923472  0.993030  0.863109  0.999698
real avocado  0.892516  0.943156  0.922051  0.965353  0.999892
fake avocado  0.746655  0.854905  0.999147  0.747131  0.999697
real pepper   0.777402  0.874713  0.803576  0.959786  0.998995
fake pepper   0.606968  0.755372  0.947999  0.627873  0.999031
real plant    0.872027  0.931589  0.952649  0.911536  0.998662
fake plant    0.762547  0.865228  0.874339  0.856403  0.999788
real banana   0.518568  0.682922  0.890770  0.553782  0.998845
fake banana   0.725025  0.840546  0.832560  0.848789  0.999408
real onion    0.652153  0.789409  0.705898  0.895457  0.999568
fake onion    0.930043  0.963704  0.990054  0.938815  0.999955
real unknown  0.871171  0.931101  0.939747  0.922710  0.999978
fake unknown  0.235731  0.381487  0.258340  0.729265  0.998008
total         0.745569  0.840588  0.881209  0.836387  0.999226
total(-bg)    0.734194  0.833439  0.875935  0.829016  0.999372
2026-10-10 11:50:07,959 - INFO: Epoch accounting: {'epoch': 433, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11245428, 47120, 72691, 140595, 136194, 96315, 60579, 138432, 192233, 70020, 61755, 53813, 45527, 222701, 107774, 155046, 24225, 80563, 88666, 85123, 63069, 9600, 40803], 'crops_with_class': [202, 35, 30, 36, 33, 26, 24, 23, 35, 30, 24, 17, 17, 56, 36, 22, 20, 24, 35, 40, 29, 10, 17], 'targeted_crops_by_class': [0, 1, 3, 4, 2, 6, 3, 6, 7, 8, 4, 3, 5, 1, 4, 5, 3, 4, 6, 4, 9, 4, 6], 'sampled_scene_counts': [1, 0, 0, 0, 0, 1, 1, 0, 0, 2, 2, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 2, 2, 0, 1, 2, 0, 3, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 2, 2, 1, 0, 1, 2, 0, 0, 2, 0, 1, 0, 2, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 2, 1, 2, 1, 2, 3, 2, 3, 3, 1, 2, 0, 1, 2, 2, 0, 1, 1, 1, 2, 2, 0, 0, 1, 0, 1, 1, 1, 3, 0, 0, 0, 0, 0, 2, 3, 0, 0, 2, 4, 1, 2, 1, 0, 2, 0, 2, 3, 1, 1, 0, 0, 3, 3, 2, 1, 2, 1, 1, 0, 0, 1, 3, 2, 3, 1, 1, 1, 2, 2, 3, 2, 0, 0, 0, 2, 1, 3, 0, 4, 1, 2], 'learning_rate': 4.733464712085834e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005659272843547682, 'train_segmentation_loss': 0.2816283211370211, 'val_foreground_miou_all22': 0.7341938711673119, 'val_psnr_ref1': 39.14843704223633, 'elapsed_seconds': 330.20371079444885, 'peak_cuda_allocated_gib': 7.5057830810546875}

Epoch 434/500 | Batch 10/202 | Rec 0.000514 | Seg 0.265290 | Elapsed 0.2m | ETA 3.9m
Epoch 434/500 | Batch 20/202 | Rec 0.000507 | Seg 0.246291 | Elapsed 0.4m | ETA 3.8m
Epoch 434/500 | Batch 30/202 | Rec 0.000539 | Seg 0.260374 | Elapsed 0.6m | ETA 3.6m
Epoch 434/500 | Batch 40/202 | Rec 0.000548 | Seg 0.276507 | Elapsed 0.8m | ETA 3.4m
Epoch 434/500 | Batch 50/202 | Rec 0.000532 | Seg 0.268270 | Elapsed 1.0m | ETA 3.2m
Epoch 434/500 | Batch 60/202 | Rec 0.000521 | Seg 0.268327 | Elapsed 1.3m | ETA 3.0m
Epoch 434/500 | Batch 70/202 | Rec 0.000514 | Seg 0.262712 | Elapsed 1.5m | ETA 2.8m
Epoch 434/500 | Batch 80/202 | Rec 0.000527 | Seg 0.266091 | Elapsed 1.7m | ETA 2.5m
Epoch 434/500 | Batch 90/202 | Rec 0.000513 | Seg 0.255339 | Elapsed 1.9m | ETA 2.3m
Epoch 434/500 | Batch 100/202 | Rec 0.000519 | Seg 0.261268 | Elapsed 2.1m | ETA 2.1m
Epoch 434/500 | Batch 110/202 | Rec 0.000527 | Seg 0.260833 | Elapsed 2.3m | ETA 1.9m
Epoch 434/500 | Batch 120/202 | Rec 0.000538 | Seg 0.267307 | Elapsed 2.5m | ETA 1.7m
Epoch 434/500 | Batch 130/202 | Rec 0.000537 | Seg 0.267465 | Elapsed 2.7m | ETA 1.5m
Epoch 434/500 | Batch 140/202 | Rec 0.000537 | Seg 0.267125 | Elapsed 2.9m | ETA 1.3m
Epoch 434/500 | Batch 150/202 | Rec 0.000540 | Seg 0.265289 | Elapsed 3.1m | ETA 1.1m
Epoch 434/500 | Batch 160/202 | Rec 0.000541 | Seg 0.266250 | Elapsed 3.3m | ETA 0.9m
Epoch 434/500 | Batch 170/202 | Rec 0.000542 | Seg 0.267033 | Elapsed 3.5m | ETA 0.7m
Epoch 434/500 | Batch 180/202 | Rec 0.000539 | Seg 0.263032 | Elapsed 3.7m | ETA 0.5m
Epoch 434/500 | Batch 190/202 | Rec 0.000543 | Seg 0.266639 | Elapsed 3.9m | ETA 0.2m
Epoch 434/500 | Batch 200/202 | Rec 0.000540 | Seg 0.265051 | Elapsed 4.1m | ETA 0.0m
Epoch 434/500 | Batch 202/202 | Rec 0.000542 | Seg 0.265684 | Elapsed 4.2m | ETA 0.0m

2026-10-10 11:54:18,809 - INFO: Rec loss: 0.0005417256723394351
2026-10-10 11:54:18,809 - INFO: Seg loss: 0.26568413606964714
2026-10-10 11:54:18,809 - INFO: λ_rec: 1
2026-10-10 11:54:18,810 - INFO: λ_seg: 0.0001
2026-10-10 11:55:35,494 - INFO: -------------------Epoch: 434------------------------
2026-10-10 11:55:35,498 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.018786  0.975044  0.000131
2026-10-10 11:55:35,506 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995614  0.997752  0.997119  0.998486  0.995813
real potato   0.916697  0.956488  0.951888  0.961234  0.999895
fake potato   0.950759  0.974708  0.978876  0.970674  0.999963
real apple    0.796632  0.886756  0.980292  0.809598  0.999287
fake apple    0.575795  0.730753  0.987276  0.580100  0.998386
real orange   0.891661  0.942678  0.997158  0.893932  0.999857
fake orange   0.917968  0.957180  0.943286  0.971592  0.999751
real grape    0.768879  0.869291  0.953024  0.799167  0.999498
fake grape    0.903385  0.949190  0.925473  0.974261  0.999615
real lemon    0.716832  0.835014  0.780411  0.897949  0.999583
fake lemon    0.839187  0.912514  0.990376  0.846087  0.999657
real avocado  0.948593  0.973568  0.990319  0.957471  0.999952
fake avocado  0.680821  0.810057  1.000000  0.680821  0.999618
real pepper   0.813338  0.897012  0.833059  0.971717  0.999184
fake pepper   0.686789  0.814266  0.932881  0.722489  0.999215
real plant    0.859173  0.924203  0.951636  0.898401  0.998527
fake plant    0.815033  0.898042  0.868949  0.929256  0.999832
real banana   0.722586  0.838905  0.870139  0.809928  0.999301
fake banana   0.706201  0.827755  0.802351  0.854927  0.999346
real onion    0.649025  0.787114  0.663615  0.967235  0.999527
fake onion    0.928655  0.962958  0.965937  0.960097  0.999953
real unknown  0.678420  0.808354  0.722222  0.917939  0.999930
fake unknown  0.209509  0.346398  0.233000  0.675118  0.997854
total         0.781372  0.865259  0.883447  0.871673  0.999285
total(-bg)    0.771634  0.859237  0.878280  0.865909  0.999442
2026-10-10 11:55:36,011 - INFO: Epoch accounting: {'epoch': 434, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11337359, 52942, 69072, 135239, 130573, 88731, 61634, 162274, 209721, 67458, 56840, 52991, 38953, 177297, 123273, 131008, 17544, 57430, 70776, 83741, 54701, 10603, 48112], 'crops_with_class': [202, 32, 29, 35, 33, 27, 23, 26, 38, 32, 28, 17, 14, 50, 32, 19, 18, 20, 29, 34, 28, 11, 19], 'targeted_crops_by_class': [0, 8, 7, 2, 4, 9, 2, 3, 7, 2, 2, 7, 1, 3, 5, 5, 4, 3, 1, 4, 6, 4, 4], 'sampled_scene_counts': [0, 0, 2, 1, 0, 0, 1, 0, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 3, 0, 1, 0, 1, 2, 0, 0, 1, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 2, 0, 1, 3, 1, 1, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 1, 1, 2, 2, 1, 3, 2, 1, 0, 1, 2, 0, 1, 5, 0, 1, 2, 0, 1, 1, 2, 1, 3, 0, 2, 1, 3, 1, 2, 4, 1, 4, 3, 3, 1, 1, 1, 1, 1, 0, 1, 1, 3, 1, 1, 0, 0, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 4], 'learning_rate': 4.6045070782502925e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005417256723394351, 'train_segmentation_loss': 0.26568413606964714, 'val_foreground_miou_all22': 0.7716335300287187, 'val_psnr_ref1': 39.01878570556641, 'elapsed_seconds': 328.0441222190857, 'peak_cuda_allocated_gib': 7.508853912353516}

Epoch 435/500 | Batch 10/202 | Rec 0.000469 | Seg 0.232573 | Elapsed 0.2m | ETA 3.9m
Epoch 435/500 | Batch 20/202 | Rec 0.000480 | Seg 0.237975 | Elapsed 0.4m | ETA 3.7m
Epoch 435/500 | Batch 30/202 | Rec 0.000486 | Seg 0.243355 | Elapsed 0.6m | ETA 3.5m
Epoch 435/500 | Batch 40/202 | Rec 0.000498 | Seg 0.241062 | Elapsed 0.8m | ETA 3.3m
Epoch 435/500 | Batch 50/202 | Rec 0.000569 | Seg 0.256440 | Elapsed 1.0m | ETA 3.1m
Epoch 435/500 | Batch 60/202 | Rec 0.000589 | Seg 0.271962 | Elapsed 1.2m | ETA 2.9m
Epoch 435/500 | Batch 70/202 | Rec 0.000606 | Seg 0.274580 | Elapsed 1.4m | ETA 2.7m
Epoch 435/500 | Batch 80/202 | Rec 0.000601 | Seg 0.276786 | Elapsed 1.7m | ETA 2.5m
Epoch 435/500 | Batch 90/202 | Rec 0.000595 | Seg 0.277254 | Elapsed 1.9m | ETA 2.3m
Epoch 435/500 | Batch 100/202 | Rec 0.000587 | Seg 0.270859 | Elapsed 2.1m | ETA 2.1m
Epoch 435/500 | Batch 110/202 | Rec 0.000575 | Seg 0.267065 | Elapsed 2.3m | ETA 1.9m
Epoch 435/500 | Batch 120/202 | Rec 0.000569 | Seg 0.267076 | Elapsed 2.5m | ETA 1.7m
Epoch 435/500 | Batch 130/202 | Rec 0.000571 | Seg 0.268230 | Elapsed 2.7m | ETA 1.5m
Epoch 435/500 | Batch 140/202 | Rec 0.000559 | Seg 0.265443 | Elapsed 2.9m | ETA 1.3m
Epoch 435/500 | Batch 150/202 | Rec 0.000562 | Seg 0.263775 | Elapsed 3.1m | ETA 1.1m
Epoch 435/500 | Batch 160/202 | Rec 0.000572 | Seg 0.270475 | Elapsed 3.3m | ETA 0.9m
Epoch 435/500 | Batch 170/202 | Rec 0.000583 | Seg 0.270598 | Elapsed 3.5m | ETA 0.7m
Epoch 435/500 | Batch 180/202 | Rec 0.000582 | Seg 0.271858 | Elapsed 3.7m | ETA 0.5m
Epoch 435/500 | Batch 190/202 | Rec 0.000584 | Seg 0.273129 | Elapsed 3.9m | ETA 0.2m
Epoch 435/500 | Batch 200/202 | Rec 0.000587 | Seg 0.277261 | Elapsed 4.1m | ETA 0.0m
Epoch 435/500 | Batch 202/202 | Rec 0.000586 | Seg 0.277659 | Elapsed 4.2m | ETA 0.0m

2026-10-10 11:59:46,801 - INFO: Rec loss: 0.0005864404134843083
2026-10-10 11:59:46,802 - INFO: Seg loss: 0.2776592720926988
2026-10-10 11:59:46,802 - INFO: λ_rec: 1
2026-10-10 11:59:46,802 - INFO: λ_seg: 0.0001
2026-10-10 12:01:03,690 - INFO: -------------------Epoch: 435------------------------
2026-10-10 12:01:03,694 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  39.092559  0.97503  0.000129
2026-10-10 12:01:03,701 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995640  0.997765  0.997132  0.998500  0.995838
real potato   0.867670  0.929097  0.999706  0.867891  0.999842
fake potato   0.722222  0.838660  0.944401  0.754294  0.999789
real apple    0.747247  0.855293  0.929157  0.792393  0.999075
fake apple    0.606990  0.755390  0.986516  0.612068  0.998504
real orange   0.859174  0.924204  0.998254  0.860468  0.999814
fake orange   0.910281  0.952983  0.935517  0.971218  0.999726
real grape    0.766765  0.867938  0.978895  0.779654  0.999505
fake grape    0.878345  0.935183  0.898791  0.974756  0.999501
real lemon    0.458685  0.628853  0.567709  0.704882  0.999022
fake lemon    0.832257  0.908400  0.957046  0.864551  0.999631
real avocado  0.916640  0.956457  0.956037  0.956979  0.999919
fake avocado  0.654469  0.791105  0.999805  0.654552  0.999586
real pepper   0.873632  0.932505  0.904271  0.962665  0.999491
fake pepper   0.847880  0.917629  0.944444  0.892388  0.999618
real plant    0.866409  0.928374  0.949841  0.907951  0.998600
fake plant    0.857512  0.923241  0.957005  0.891871  0.999882
real banana   0.583936  0.737274  0.867138  0.641315  0.998973
fake banana   0.610443  0.758057  0.672992  0.867867  0.998981
real onion    0.686777  0.814257  0.780046  0.851714  0.999649
fake onion    0.891751  0.942729  0.975187  0.912455  0.999930
real unknown  0.897267  0.945802  0.986528  0.908397  0.999983
fake unknown  0.177098  0.300869  0.197177  0.634915  0.997514
total         0.761265  0.849655  0.886243  0.837554  0.999234
total(-bg)    0.750611  0.842923  0.881203  0.830238  0.999388
2026-10-10 12:01:04,163 - INFO: Epoch accounting: {'epoch': 435, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11289622, 43878, 53550, 103698, 151293, 58591, 64773, 122825, 203513, 59013, 45520, 39496, 36330, 240150, 132183, 175668, 22283, 80002, 90175, 93692, 61251, 11815, 58951], 'crops_with_class': [202, 25, 25, 29, 37, 20, 25, 25, 38, 26, 20, 13, 15, 55, 34, 23, 22, 25, 36, 34, 28, 15, 27], 'targeted_crops_by_class': [0, 3, 6, 4, 6, 4, 3, 2, 6, 7, 4, 6, 1, 4, 2, 6, 6, 2, 5, 5, 7, 4, 3], 'sampled_scene_counts': [1, 0, 0, 3, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 3, 1, 1, 0, 1, 0, 0, 0, 0, 1, 3, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 2, 0, 1, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 2, 1, 3, 1, 1, 1, 2, 2, 0, 1, 1, 2, 2, 1, 0, 0, 0, 3, 0, 2, 3, 0, 1, 3, 0, 5, 1, 1, 0, 3, 1, 2, 2, 1, 0, 1, 1, 0, 1, 6, 2, 3, 1, 1, 0, 0, 0, 2, 1, 2, 2, 1, 0, 1, 3, 1, 1, 2, 2, 2, 1, 2, 0, 3, 1, 0, 2, 1, 1, 3, 1, 2, 1, 0, 1, 2, 0, 0, 3, 1, 3, 2], 'learning_rate': 4.477346515531731e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005864404134843083, 'train_segmentation_loss': 0.2776592720926988, 'val_foreground_miou_all22': 0.750611419926522, 'val_psnr_ref1': 39.09255889892578, 'elapsed_seconds': 328.144987821579, 'peak_cuda_allocated_gib': 7.511264801025391}

Epoch 436/500 | Batch 10/202 | Rec 0.000502 | Seg 0.227151 | Elapsed 0.2m | ETA 3.9m
Epoch 436/500 | Batch 20/202 | Rec 0.000583 | Seg 0.267615 | Elapsed 0.4m | ETA 3.7m
Epoch 436/500 | Batch 30/202 | Rec 0.000584 | Seg 0.278282 | Elapsed 0.6m | ETA 3.5m
Epoch 436/500 | Batch 40/202 | Rec 0.000593 | Seg 0.281724 | Elapsed 0.8m | ETA 3.3m
Epoch 436/500 | Batch 50/202 | Rec 0.000583 | Seg 0.280208 | Elapsed 1.0m | ETA 3.1m
Epoch 436/500 | Batch 60/202 | Rec 0.000598 | Seg 0.292155 | Elapsed 1.2m | ETA 2.9m
Epoch 436/500 | Batch 70/202 | Rec 0.000588 | Seg 0.279558 | Elapsed 1.4m | ETA 2.7m
Epoch 436/500 | Batch 80/202 | Rec 0.000584 | Seg 0.281245 | Elapsed 1.6m | ETA 2.5m
Epoch 436/500 | Batch 90/202 | Rec 0.000587 | Seg 0.277121 | Elapsed 1.8m | ETA 2.3m
Epoch 436/500 | Batch 100/202 | Rec 0.000577 | Seg 0.278794 | Elapsed 2.1m | ETA 2.1m
Epoch 436/500 | Batch 110/202 | Rec 0.000576 | Seg 0.275946 | Elapsed 2.3m | ETA 1.9m
Epoch 436/500 | Batch 120/202 | Rec 0.000578 | Seg 0.280006 | Elapsed 2.5m | ETA 1.7m
Epoch 436/500 | Batch 130/202 | Rec 0.000582 | Seg 0.280654 | Elapsed 2.7m | ETA 1.5m
Epoch 436/500 | Batch 140/202 | Rec 0.000582 | Seg 0.285509 | Elapsed 2.9m | ETA 1.3m
Epoch 436/500 | Batch 150/202 | Rec 0.000578 | Seg 0.284707 | Elapsed 3.1m | ETA 1.1m
Epoch 436/500 | Batch 160/202 | Rec 0.000573 | Seg 0.283748 | Elapsed 3.3m | ETA 0.9m
Epoch 436/500 | Batch 170/202 | Rec 0.000568 | Seg 0.282771 | Elapsed 3.5m | ETA 0.7m
Epoch 436/500 | Batch 180/202 | Rec 0.000571 | Seg 0.283534 | Elapsed 3.7m | ETA 0.5m
Epoch 436/500 | Batch 190/202 | Rec 0.000568 | Seg 0.280653 | Elapsed 3.9m | ETA 0.2m
Epoch 436/500 | Batch 200/202 | Rec 0.000566 | Seg 0.280335 | Elapsed 4.1m | ETA 0.0m
Epoch 436/500 | Batch 202/202 | Rec 0.000567 | Seg 0.279223 | Elapsed 4.2m | ETA 0.0m

2026-10-10 12:05:13,918 - INFO: Rec loss: 0.000567181193353931
2026-10-10 12:05:13,918 - INFO: Seg loss: 0.2792227992068718
2026-10-10 12:05:13,918 - INFO: λ_rec: 1
2026-10-10 12:05:13,918 - INFO: λ_seg: 0.0001
2026-10-10 12:06:30,711 - INFO: -------------------Epoch: 436------------------------
2026-10-10 12:06:30,715 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  39.154435  0.97521  0.000127
2026-10-10 12:06:30,721 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995890  0.997891  0.997632  0.998250  0.996078
real potato   0.799527  0.888547  0.970690  0.819306  0.999754
fake potato   0.813580  0.897159  0.978713  0.828236  0.999862
real apple    0.792337  0.884088  0.921523  0.849668  0.999232
fake apple    0.566486  0.723210  0.992178  0.569027  0.998356
real orange   0.911229  0.953503  0.995215  0.915239  0.999883
fake orange   0.931568  0.964522  0.954209  0.975163  0.999795
real grape    0.826801  0.905140  0.962841  0.854052  0.999626
fake grape    0.901969  0.948408  0.921625  0.976901  0.999607
real lemon    0.584703  0.737886  0.616423  0.919112  0.999233
fake lemon    0.858323  0.923711  0.994923  0.862099  0.999699
real avocado  0.909867  0.952756  0.942774  0.963054  0.999911
fake avocado  0.615198  0.761715  0.999793  0.615277  0.999539
real pepper   0.862762  0.926276  0.895083  0.959828  0.999442
fake pepper   0.789538  0.882343  0.939420  0.831893  0.999471
real plant    0.882074  0.937293  0.950077  0.924945  0.998763
fake plant    0.779862  0.876268  0.808690  0.956288  0.999785
real banana   0.597630  0.748097  0.867586  0.657612  0.999005
fake banana   0.687520  0.814779  0.761647  0.875995  0.999268
real onion    0.638303  0.779176  0.673223  0.924844  0.999527
fake onion    0.930183  0.963779  0.980967  0.947279  0.999955
real unknown  0.889699  0.941580  0.952195  0.931298  0.999982
fake unknown  0.204171  0.339070  0.222141  0.716226  0.997648
total         0.772575  0.858574  0.882590  0.863982  0.999279
total(-bg)    0.762424  0.852241  0.877361  0.857879  0.999425
2026-10-10 12:06:31,192 - INFO: Epoch accounting: {'epoch': 436, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11252728, 62883, 65617, 117177, 155093, 65994, 70419, 152181, 171810, 89263, 48072, 35107, 34190, 232665, 104998, 176272, 22501, 75247, 85698, 96892, 73277, 11127, 39061], 'crops_with_class': [202, 39, 27, 30, 40, 22, 21, 28, 34, 36, 23, 11, 12, 56, 29, 22, 20, 27, 35, 39, 35, 14, 15], 'targeted_crops_by_class': [0, 5, 8, 6, 2, 2, 4, 4, 4, 11, 4, 2, 0, 6, 3, 4, 3, 5, 5, 5, 5, 7, 4], 'sampled_scene_counts': [1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, 1, 1, 1, 3, 1, 0, 0, 1, 1, 3, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 0, 1, 1, 2, 2, 3, 1, 1, 0, 1, 3, 1, 0, 2, 2, 2, 1, 0, 2, 0, 2, 1, 0, 0, 1, 1, 2, 4, 3, 1, 0, 3, 3, 1, 0, 0, 2, 4, 1, 1, 2, 3, 2, 1, 1, 1, 2, 1, 1, 1, 0, 2, 1, 0, 3, 2, 3, 1, 2, 0, 1, 1, 1, 2, 0, 3, 1, 1, 2, 3, 3, 0, 2, 1, 1, 1, 0, 1, 2, 2, 4, 1, 2, 2], 'learning_rate': 4.3519880440114335e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000567181193353931, 'train_segmentation_loss': 0.2792227992068718, 'val_foreground_miou_all22': 0.7624240708459269, 'val_psnr_ref1': 39.154434814453126, 'elapsed_seconds': 327.0217580795288, 'peak_cuda_allocated_gib': 7.509799957275391}

Epoch 437/500 | Batch 10/202 | Rec 0.000563 | Seg 0.244390 | Elapsed 0.2m | ETA 3.8m
Epoch 437/500 | Batch 20/202 | Rec 0.000566 | Seg 0.270156 | Elapsed 0.4m | ETA 3.7m
Epoch 437/500 | Batch 30/202 | Rec 0.000539 | Seg 0.267095 | Elapsed 0.6m | ETA 3.5m
Epoch 437/500 | Batch 40/202 | Rec 0.000537 | Seg 0.277730 | Elapsed 0.8m | ETA 3.3m
Epoch 437/500 | Batch 50/202 | Rec 0.000540 | Seg 0.276956 | Elapsed 1.0m | ETA 3.1m
Epoch 437/500 | Batch 60/202 | Rec 0.000584 | Seg 0.273146 | Elapsed 1.2m | ETA 2.9m
Epoch 437/500 | Batch 70/202 | Rec 0.000604 | Seg 0.285783 | Elapsed 1.4m | ETA 2.7m
Epoch 437/500 | Batch 80/202 | Rec 0.000600 | Seg 0.286009 | Elapsed 1.6m | ETA 2.5m
Epoch 437/500 | Batch 90/202 | Rec 0.000596 | Seg 0.285451 | Elapsed 1.8m | ETA 2.3m
Epoch 437/500 | Batch 100/202 | Rec 0.000599 | Seg 0.286694 | Elapsed 2.0m | ETA 2.1m
Epoch 437/500 | Batch 110/202 | Rec 0.000602 | Seg 0.288706 | Elapsed 2.3m | ETA 1.9m
Epoch 437/500 | Batch 120/202 | Rec 0.000605 | Seg 0.293118 | Elapsed 2.5m | ETA 1.7m
Epoch 437/500 | Batch 130/202 | Rec 0.000607 | Seg 0.294375 | Elapsed 2.7m | ETA 1.5m
Epoch 437/500 | Batch 140/202 | Rec 0.000629 | Seg 0.304994 | Elapsed 2.9m | ETA 1.3m
Epoch 437/500 | Batch 150/202 | Rec 0.000630 | Seg 0.301515 | Elapsed 3.1m | ETA 1.1m
Epoch 437/500 | Batch 160/202 | Rec 0.000626 | Seg 0.299790 | Elapsed 3.3m | ETA 0.9m
Epoch 437/500 | Batch 170/202 | Rec 0.000624 | Seg 0.301340 | Elapsed 3.5m | ETA 0.7m
Epoch 437/500 | Batch 180/202 | Rec 0.000618 | Seg 0.298418 | Elapsed 3.7m | ETA 0.5m
Epoch 437/500 | Batch 190/202 | Rec 0.000612 | Seg 0.297276 | Elapsed 3.9m | ETA 0.2m
Epoch 437/500 | Batch 200/202 | Rec 0.000616 | Seg 0.296212 | Elapsed 4.1m | ETA 0.0m
Epoch 437/500 | Batch 202/202 | Rec 0.000615 | Seg 0.295970 | Elapsed 4.1m | ETA 0.0m

2026-10-10 12:10:40,043 - INFO: Rec loss: 0.0006145815470049591
2026-10-10 12:10:40,043 - INFO: Seg loss: 0.2959695323969763
2026-10-10 12:10:40,043 - INFO: λ_rec: 1
2026-10-10 12:10:40,043 - INFO: λ_seg: 0.0001
2026-10-10 12:11:54,897 - INFO: -------------------Epoch: 437------------------------
2026-10-10 12:11:54,901 - INFO:
Validation stats:
       PSNR      SSIM      MSE
0  39.04295  0.975025  0.00013
2026-10-10 12:11:54,907 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995604  0.997747  0.996920  0.998676  0.995802
real potato   0.744759  0.853660  0.944067  0.779138  0.999680
fake potato   0.832820  0.908736  0.977108  0.849393  0.999876
real apple    0.761556  0.864590  0.898940  0.832862  0.999100
fake apple    0.604965  0.753820  0.990138  0.608632  0.998499
real orange   0.874525  0.933013  0.993332  0.879690  0.999834
fake orange   0.906075  0.950673  0.928688  0.973830  0.999711
real grape    0.792618  0.884264  0.950050  0.827085  0.999548
fake grape    0.904456  0.949782  0.929451  0.971126  0.999621
real lemon    0.626718  0.770482  0.649426  0.947157  0.999337
fake lemon    0.842589  0.914521  0.993822  0.847025  0.999665
real avocado  0.916628  0.956450  0.950836  0.962233  0.999919
fake avocado  0.772525  0.871617  0.999176  0.773017  0.999728
real pepper   0.762559  0.865237  0.788911  0.958034  0.998909
fake pepper   0.576983  0.731708  0.946001  0.596633  0.998957
real plant    0.858900  0.924045  0.959104  0.891552  0.998535
fake plant    0.751253  0.857910  0.827193  0.891104  0.999765
real banana   0.617019  0.763107  0.899373  0.662773  0.999076
fake banana   0.741479  0.851501  0.851410  0.851692  0.999454
real onion    0.653238  0.790204  0.687899  0.928390  0.999555
fake onion    0.948070  0.973293  0.984417  0.962515  0.999967
real unknown  0.618471  0.764218  0.650368  0.926527  0.999909
fake unknown  0.228672  0.372187  0.254687  0.691235  0.998035
total         0.753586  0.847946  0.871796  0.852623  0.999238
total(-bg)    0.742585  0.841137  0.866109  0.845984  0.999395
2026-10-10 12:11:55,357 - INFO: Epoch accounting: {'epoch': 437, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11209260, 43038, 60815, 104625, 113723, 45467, 93609, 149460, 213149, 64411, 69395, 44986, 40262, 179561, 121298, 274462, 33223, 98371, 81664, 87928, 61695, 12321, 35549], 'crops_with_class': [202, 29, 29, 27, 29, 12, 30, 24, 38, 33, 30, 14, 18, 46, 33, 28, 29, 26, 28, 39, 29, 13, 16], 'targeted_crops_by_class': [0, 4, 3, 4, 6, 3, 8, 8, 5, 2, 5, 2, 4, 4, 4, 9, 4, 5, 3, 5, 7, 2, 4], 'sampled_scene_counts': [2, 0, 2, 0, 1, 0, 1, 0, 2, 1, 3, 1, 1, 0, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 1, 0, 2, 0, 1, 0, 0, 2, 2, 1, 2, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 0, 2, 1, 2, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 1, 0, 1, 2, 1, 0, 0, 0, 1, 1, 0, 2, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 2, 1, 1, 4, 0, 1, 2, 1, 2, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 3, 5, 1, 1, 0, 0, 2, 3, 1, 1, 1, 1, 2, 3, 0, 0, 0, 3, 1, 5, 2, 0, 3, 3, 2, 0, 3, 1, 1, 0, 1, 1, 2, 2, 3, 2, 0, 1, 2, 1, 0, 1, 2, 1, 2, 3, 3, 0, 0, 3, 1, 0, 0, 0, 2, 0, 0, 1, 3, 1], 'learning_rate': 4.228436612627219e-06, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0006145815470049591, 'train_segmentation_loss': 0.2959695323969763, 'val_foreground_miou_all22': 0.7425853492675802, 'val_psnr_ref1': 39.04295043945312, 'elapsed_seconds': 324.1576256752014, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 438/500 | Batch 10/202 | Rec 0.000556 | Seg 0.227564 | Elapsed 0.2m | ETA 4.1m
Epoch 438/500 | Batch 20/202 | Rec 0.000531 | Seg 0.246348 | Elapsed 0.4m | ETA 3.9m
Epoch 438/500 | Batch 30/202 | Rec 0.000582 | Seg 0.270116 | Elapsed 0.6m | ETA 3.6m
Epoch 438/500 | Batch 40/202 | Rec 0.000559 | Seg 0.266815 | Elapsed 0.8m | ETA 3.4m
Epoch 438/500 | Batch 50/202 | Rec 0.000546 | Seg 0.274528 | Elapsed 1.0m | ETA 3.2m
Epoch 438/500 | Batch 60/202 | Rec 0.000535 | Seg 0.267039 | Elapsed 1.2m | ETA 3.0m
Epoch 438/500 | Batch 70/202 | Rec 0.000542 | Seg 0.260654 | Elapsed 1.4m | ETA 2.7m
Epoch 438/500 | Batch 80/202 | Rec 0.000539 | Seg 0.264321 | Elapsed 1.7m | ETA 2.5m
Epoch 438/500 | Batch 90/202 | Rec 0.000537 | Seg 0.266471 | Elapsed 1.9m | ETA 2.3m
Epoch 438/500 | Batch 100/202 | Rec 0.000527 | Seg 0.265261 | Elapsed 2.1m | ETA 2.1m
Epoch 438/500 | Batch 110/202 | Rec 0.000543 | Seg 0.271367 | Elapsed 2.3m | ETA 1.9m
Epoch 438/500 | Batch 120/202 | Rec 0.000544 | Seg 0.265634 | Elapsed 2.5m | ETA 1.7m
Epoch 438/500 | Batch 130/202 | Rec 0.000545 | Seg 0.263844 | Elapsed 2.7m | ETA 1.5m
Epoch 438/500 | Batch 140/202 | Rec 0.000559 | Seg 0.273828 | Elapsed 2.9m | ETA 1.3m
Epoch 438/500 | Batch 150/202 | Rec 0.000562 | Seg 0.270102 | Elapsed 3.1m | ETA 1.1m
Epoch 438/500 | Batch 160/202 | Rec 0.000562 | Seg 0.271210 | Elapsed 3.3m | ETA 0.9m
Epoch 438/500 | Batch 170/202 | Rec 0.000561 | Seg 0.271137 | Elapsed 3.5m | ETA 0.7m
Epoch 438/500 | Batch 180/202 | Rec 0.000575 | Seg 0.270675 | Elapsed 3.7m | ETA 0.5m
Epoch 438/500 | Batch 190/202 | Rec 0.000579 | Seg 0.273141 | Elapsed 3.9m | ETA 0.2m
Epoch 438/500 | Batch 200/202 | Rec 0.000583 | Seg 0.273602 | Elapsed 4.1m | ETA 0.0m
Epoch 438/500 | Batch 202/202 | Rec 0.000581 | Seg 0.273591 | Elapsed 4.2m | ETA 0.0m

2026-10-10 12:16:04,926 - INFO: Rec loss: 0.0005809397388844391
2026-10-10 12:16:04,926 - INFO: Seg loss: 0.2735907285299041
2026-10-10 12:16:04,926 - INFO: λ_rec: 1
2026-10-10 12:16:04,926 - INFO: λ_seg: 0.0001
2026-10-10 12:17:20,122 - INFO: -------------------Epoch: 438------------------------
2026-10-10 12:17:20,126 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.978401  0.974728  0.000132
2026-10-10 12:17:20,133 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995697  0.997794  0.997282  0.998407  0.995892
real potato   0.405073  0.576545  0.986716  0.407294  0.999284
fake potato   0.695102  0.820081  0.987032  0.701508  0.999776
real apple    0.712237  0.831887  0.791855  0.876294  0.998779
fake apple    0.624024  0.768443  0.977776  0.633002  0.998560
real orange   0.935443  0.966595  0.993401  0.941292  0.999914
fake orange   0.941228  0.969674  0.962219  0.977348  0.999825
real grape    0.815482  0.898314  0.951606  0.850764  0.999598
fake grape    0.887159  0.940156  0.903207  0.980365  0.999539
real lemon    0.531985  0.694458  0.548693  0.945858  0.999022
fake lemon    0.861435  0.925510  0.995929  0.864479  0.999706
real avocado  0.842498  0.914467  0.870236  0.963547  0.999833
fake avocado  0.775768  0.873677  0.998852  0.776460  0.999731
real pepper   0.793702  0.884938  0.831902  0.945311  0.999101
fake pepper   0.641431  0.781503  0.948807  0.664426  0.999115
real plant    0.873010  0.932150  0.953689  0.911658  0.998674
fake plant    0.786845  0.880659  0.833590  0.933474  0.999799
real banana   0.497245  0.664166  0.864562  0.539250  0.998775
fake banana   0.711001  0.831044  0.818753  0.843812  0.999369
real onion    0.640225  0.780605  0.710917  0.865563  0.999561
fake onion    0.925071  0.961027  0.982567  0.940508  0.999952
real unknown  0.924618  0.960783  1.000000  0.924618  0.999988
fake unknown  0.239703  0.386671  0.262301  0.735603  0.998034
total         0.741564  0.836572  0.877039  0.835689  0.999210
total(-bg)    0.730013  0.829243  0.871573  0.828292  0.999361
2026-10-10 12:17:20,606 - INFO: Epoch accounting: {'epoch': 438, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11325910, 64893, 72025, 104618, 130411, 85528, 54414, 110321, 149346, 77520, 67485, 39693, 48531, 197086, 128867, 201961, 21763, 82256, 78983, 92462, 51025, 14011, 39163], 'crops_with_class': [202, 37, 35, 26, 29, 25, 22, 25, 28, 32, 27, 13, 15, 54, 34, 27, 20, 22, 35, 38, 30, 16, 19], 'targeted_crops_by_class': [0, 3, 6, 4, 4, 5, 4, 1, 1, 10, 3, 1, 6, 4, 2, 6, 6, 5, 6, 7, 6, 3, 5], 'sampled_scene_counts': [2, 1, 2, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 3, 2, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 2, 1, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 4, 1, 2, 2, 0, 1, 1, 1, 1, 1, 1, 0, 1, 3, 1, 1, 2, 0, 1, 3, 1, 0, 1, 4, 6, 3, 0, 0, 3, 2, 2, 1, 0, 1, 3, 0, 2, 2, 1, 1, 0, 2, 1, 1, 1, 2, 3, 1, 2, 0, 1, 2, 0, 1, 2, 3, 1, 2, 0, 0, 3, 3, 0, 1, 2, 2], 'learning_rate': 4.106697098978013e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005809397388844391, 'train_segmentation_loss': 0.2735907285299041, 'val_foreground_miou_all22': 0.7300128953589945, 'val_psnr_ref1': 38.97840133666992, 'elapsed_seconds': 325.2419352531433, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 439/500 | Batch 10/202 | Rec 0.000655 | Seg 0.255428 | Elapsed 0.2m | ETA 4.0m
Epoch 439/500 | Batch 20/202 | Rec 0.000638 | Seg 0.285682 | Elapsed 0.4m | ETA 3.7m
Epoch 439/500 | Batch 30/202 | Rec 0.000588 | Seg 0.269122 | Elapsed 0.6m | ETA 3.5m
Epoch 439/500 | Batch 40/202 | Rec 0.000559 | Seg 0.261866 | Elapsed 0.8m | ETA 3.3m
Epoch 439/500 | Batch 50/202 | Rec 0.000545 | Seg 0.258911 | Elapsed 1.0m | ETA 3.1m
Epoch 439/500 | Batch 60/202 | Rec 0.000539 | Seg 0.266103 | Elapsed 1.2m | ETA 2.9m
Epoch 439/500 | Batch 70/202 | Rec 0.000544 | Seg 0.262938 | Elapsed 1.4m | ETA 2.7m
Epoch 439/500 | Batch 80/202 | Rec 0.000535 | Seg 0.264971 | Elapsed 1.6m | ETA 2.5m
Epoch 439/500 | Batch 90/202 | Rec 0.000549 | Seg 0.270359 | Elapsed 1.9m | ETA 2.3m
Epoch 439/500 | Batch 100/202 | Rec 0.000558 | Seg 0.278804 | Elapsed 2.1m | ETA 2.1m
Epoch 439/500 | Batch 110/202 | Rec 0.000553 | Seg 0.277661 | Elapsed 2.3m | ETA 1.9m
Epoch 439/500 | Batch 120/202 | Rec 0.000552 | Seg 0.279749 | Elapsed 2.5m | ETA 1.7m
Epoch 439/500 | Batch 130/202 | Rec 0.000572 | Seg 0.283132 | Elapsed 2.7m | ETA 1.5m
Epoch 439/500 | Batch 140/202 | Rec 0.000573 | Seg 0.281382 | Elapsed 2.9m | ETA 1.3m
Epoch 439/500 | Batch 150/202 | Rec 0.000567 | Seg 0.278030 | Elapsed 3.1m | ETA 1.1m
Epoch 439/500 | Batch 160/202 | Rec 0.000567 | Seg 0.276459 | Elapsed 3.3m | ETA 0.9m
Epoch 439/500 | Batch 170/202 | Rec 0.000560 | Seg 0.272579 | Elapsed 3.5m | ETA 0.7m
Epoch 439/500 | Batch 180/202 | Rec 0.000561 | Seg 0.273483 | Elapsed 3.7m | ETA 0.5m
Epoch 439/500 | Batch 190/202 | Rec 0.000557 | Seg 0.272075 | Elapsed 3.9m | ETA 0.2m
Epoch 439/500 | Batch 200/202 | Rec 0.000549 | Seg 0.270504 | Elapsed 4.1m | ETA 0.0m
Epoch 439/500 | Batch 202/202 | Rec 0.000549 | Seg 0.270360 | Elapsed 4.2m | ETA 0.0m

2026-10-10 12:21:29,994 - INFO: Rec loss: 0.0005485528891578796
2026-10-10 12:21:29,994 - INFO: Seg loss: 0.270360488582882
2026-10-10 12:21:29,994 - INFO: λ_rec: 1
2026-10-10 12:21:29,994 - INFO: λ_seg: 0.0001
2026-10-10 12:22:50,633 - INFO: -------------------Epoch: 439------------------------
2026-10-10 12:22:50,637 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.214515  0.975148  0.000125
2026-10-10 12:22:50,644 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995786  0.997839  0.997177  0.998601  0.995977
real potato   0.271104  0.426531  1.000000  0.271104  0.999128
fake potato   0.656685  0.792722  0.989038  0.661500  0.999748
real apple    0.687603  0.814838  0.742108  0.903494  0.998584
fake apple    0.718166  0.835919  0.970562  0.734158  0.998912
real orange   0.903944  0.949499  0.995429  0.907712  0.999873
fake orange   0.925313  0.961158  0.939536  0.983904  0.999773
real grape    0.845617  0.916302  0.959313  0.877074  0.999666
fake grape    0.893742  0.943840  0.924764  0.963825  0.999576
real lemon    0.408957  0.580468  0.419890  0.940145  0.998403
fake lemon    0.861942  0.925803  0.982514  0.875370  0.999703
real avocado  0.637409  0.778510  0.648344  0.974220  0.999485
fake avocado  0.799592  0.888588  0.998886  0.800306  0.999760
real pepper   0.714476  0.833413  0.817835  0.849700  0.998758
fake pepper   0.551913  0.711221  0.951319  0.567953  0.998901
real plant    0.869768  0.930299  0.939975  0.920918  0.998621
fake plant    0.762291  0.865064  0.848066  0.882860  0.999781
real banana   0.210248  0.347414  0.840281  0.219000  0.998152
fake banana   0.712139  0.831820  0.846735  0.817518  0.999392
real onion    0.571091  0.726949  0.720133  0.733998  0.999502
fake onion    0.890738  0.942162  0.997030  0.893108  0.999931
real unknown  0.923729  0.960302  0.985930  0.936069  0.999988
fake unknown  0.262489  0.415787  0.291969  0.722202  0.998290
total         0.698902  0.798976  0.861167  0.801510  0.999126
total(-bg)    0.685407  0.789937  0.854984  0.792552  0.999269
2026-10-10 12:22:51,126 - INFO: Epoch accounting: {'epoch': 439, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11338227, 48079, 65478, 135558, 115361, 97680, 101611, 130095, 173053, 68042, 57406, 47671, 46452, 201989, 135771, 116971, 22206, 79112, 63671, 74373, 61858, 12048, 45560], 'crops_with_class': [202, 27, 26, 36, 35, 30, 37, 27, 35, 30, 25, 17, 21, 50, 28, 15, 21, 23, 28, 32, 28, 13, 23], 'targeted_crops_by_class': [0, 3, 4, 7, 2, 7, 7, 6, 5, 3, 2, 4, 7, 5, 2, 4, 5, 6, 3, 5, 6, 5, 4], 'sampled_scene_counts': [1, 1, 1, 1, 0, 2, 0, 2, 0, 3, 2, 0, 2, 1, 0, 2, 0, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 2, 2, 2, 3, 1, 1, 2, 0, 1, 1, 1, 1, 1, 3, 0, 1, 1, 1, 0, 0, 1, 0, 1, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 2, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 1, 2, 4, 3, 2, 2, 0, 2, 1, 2, 2, 1, 4, 1, 0, 0, 0, 4, 0, 4, 1, 2, 2, 2, 1, 0, 3, 3, 0, 1, 0, 1, 0, 3, 3, 2, 2, 1, 0, 4, 0, 0, 2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 3, 2, 1], 'learning_rate': 3.986774309131393e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005485528891578796, 'train_segmentation_loss': 0.270360488582882, 'val_foreground_miou_all22': 0.6854071377534733, 'val_psnr_ref1': 39.21451477050781, 'elapsed_seconds': 330.5133843421936, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 440/500 | Batch 10/202 | Rec 0.000576 | Seg 0.322077 | Elapsed 0.2m | ETA 3.9m
Epoch 440/500 | Batch 20/202 | Rec 0.000548 | Seg 0.310047 | Elapsed 0.4m | ETA 3.8m
Epoch 440/500 | Batch 30/202 | Rec 0.000559 | Seg 0.293101 | Elapsed 0.6m | ETA 3.6m
Epoch 440/500 | Batch 40/202 | Rec 0.000562 | Seg 0.289361 | Elapsed 0.8m | ETA 3.3m
Epoch 440/500 | Batch 50/202 | Rec 0.000581 | Seg 0.296368 | Elapsed 1.0m | ETA 3.1m
Epoch 440/500 | Batch 60/202 | Rec 0.000551 | Seg 0.278691 | Elapsed 1.2m | ETA 2.9m
Epoch 440/500 | Batch 70/202 | Rec 0.000555 | Seg 0.280519 | Elapsed 1.4m | ETA 2.7m
Epoch 440/500 | Batch 80/202 | Rec 0.000536 | Seg 0.267363 | Elapsed 1.7m | ETA 2.5m
Epoch 440/500 | Batch 90/202 | Rec 0.000540 | Seg 0.272709 | Elapsed 1.9m | ETA 2.3m
Epoch 440/500 | Batch 100/202 | Rec 0.000533 | Seg 0.273630 | Elapsed 2.1m | ETA 2.1m
Epoch 440/500 | Batch 110/202 | Rec 0.000535 | Seg 0.267585 | Elapsed 2.3m | ETA 1.9m
Epoch 440/500 | Batch 120/202 | Rec 0.000527 | Seg 0.262902 | Elapsed 2.5m | ETA 1.7m
Epoch 440/500 | Batch 130/202 | Rec 0.000527 | Seg 0.260783 | Elapsed 2.7m | ETA 1.5m
Epoch 440/500 | Batch 140/202 | Rec 0.000536 | Seg 0.263964 | Elapsed 2.9m | ETA 1.3m
Epoch 440/500 | Batch 150/202 | Rec 0.000542 | Seg 0.270700 | Elapsed 3.1m | ETA 1.1m
Epoch 440/500 | Batch 160/202 | Rec 0.000564 | Seg 0.273795 | Elapsed 3.3m | ETA 0.9m
Epoch 440/500 | Batch 170/202 | Rec 0.000562 | Seg 0.271529 | Elapsed 3.5m | ETA 0.7m
Epoch 440/500 | Batch 180/202 | Rec 0.000564 | Seg 0.272658 | Elapsed 3.7m | ETA 0.5m
Epoch 440/500 | Batch 190/202 | Rec 0.000566 | Seg 0.273859 | Elapsed 3.9m | ETA 0.2m
Epoch 440/500 | Batch 200/202 | Rec 0.000563 | Seg 0.272964 | Elapsed 4.1m | ETA 0.0m
Epoch 440/500 | Batch 202/202 | Rec 0.000564 | Seg 0.272801 | Elapsed 4.2m | ETA 0.0m

2026-10-10 12:27:01,208 - INFO: Rec loss: 0.0005638320392313515
2026-10-10 12:27:01,208 - INFO: Seg loss: 0.2728005352033542
2026-10-10 12:27:01,209 - INFO: λ_rec: 1
2026-10-10 12:27:01,209 - INFO: λ_seg: 0.0001
2026-10-10 12:28:20,557 - INFO: -------------------Epoch: 440------------------------
2026-10-10 12:28:20,560 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.184584  0.975154  0.000126
2026-10-10 12:28:20,566 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995774  0.997832  0.997273  0.998492  0.995965
real potato   0.816365  0.898850  0.968764  0.838434  0.999774
fake potato   0.840989  0.913577  0.980548  0.855258  0.999882
real apple    0.784953  0.879472  0.926519  0.837063  0.999209
fake apple    0.618876  0.764527  0.986022  0.624353  0.998548
real orange   0.877060  0.934454  0.994383  0.881427  0.999837
fake orange   0.917371  0.956855  0.932258  0.982891  0.999747
real grape    0.771890  0.871212  0.957130  0.799532  0.999507
fake grape    0.903895  0.949472  0.931058  0.968733  0.999619
real lemon    0.683904  0.812235  0.712578  0.944430  0.999487
fake lemon    0.852284  0.920202  0.991586  0.858493  0.999685
real avocado  0.931674  0.964579  0.964233  0.965025  0.999934
fake avocado  0.782764  0.878097  0.999674  0.782964  0.999740
real pepper   0.794388  0.885364  0.814686  0.969590  0.999082
fake pepper   0.633524  0.775605  0.941343  0.659561  0.999091
real plant    0.864071  0.927029  0.947763  0.907280  0.998572
fake plant    0.800491  0.889142  0.903443  0.875383  0.999826
real banana   0.673641  0.804951  0.893612  0.732378  0.999203
fake banana   0.731717  0.845027  0.818076  0.873922  0.999411
real onion    0.654369  0.791031  0.685750  0.934639  0.999554
fake onion    0.942088  0.970130  0.984803  0.955985  0.999963
real unknown  0.677083  0.807404  0.713241  0.930343  0.999929
fake unknown  0.227125  0.370136  0.250319  0.710250  0.997964
total         0.772882  0.861182  0.882394  0.864627  0.999284
total(-bg)    0.762751  0.854971  0.877172  0.858542  0.999435
2026-10-10 12:28:21,057 - INFO: Epoch accounting: {'epoch': 440, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11326666, 52112, 56884, 94278, 159544, 79134, 80336, 137409, 218515, 71955, 59860, 44019, 33733, 243050, 106526, 85769, 19344, 92585, 87310, 90586, 48897, 8789, 40971], 'crops_with_class': [202, 29, 28, 26, 41, 23, 26, 26, 35, 30, 25, 17, 16, 56, 26, 14, 16, 25, 29, 38, 26, 10, 19], 'targeted_crops_by_class': [0, 4, 5, 5, 7, 4, 4, 3, 3, 2, 7, 6, 4, 5, 5, 4, 2, 6, 6, 2, 6, 5, 3], 'sampled_scene_counts': [1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 0, 0, 1, 2, 0, 1, 1, 0, 2, 0, 0, 0, 0, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 2, 0, 0, 1, 2, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 3, 1, 2, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 1, 0, 0, 0, 1, 3, 1, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 2, 3, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 2, 2, 2, 0, 2, 1, 4, 1, 1, 3, 1, 0, 0, 2, 2, 1, 1, 0, 2, 1, 1, 2, 1, 1, 1, 2, 2, 0, 1, 1, 0, 3, 1, 0, 0, 1, 1, 1, 1, 2, 2, 1, 4, 2, 1, 0, 1, 2, 2, 0, 3, 1, 1, 1, 2, 1, 4, 2, 1, 0, 1, 1, 1, 4, 4, 1, 0, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 1, 1], 'learning_rate': 3.868672977433763e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005638320392313515, 'train_segmentation_loss': 0.2728005352033542, 'val_foreground_miou_all22': 0.7627510054488358, 'val_psnr_ref1': 39.184584350585936, 'elapsed_seconds': 329.9199388027191, 'peak_cuda_allocated_gib': 7.509616851806641}

Epoch 441/500 | Batch 10/202 | Rec 0.000509 | Seg 0.239148 | Elapsed 0.2m | ETA 4.0m
Epoch 441/500 | Batch 20/202 | Rec 0.000480 | Seg 0.250852 | Elapsed 0.4m | ETA 3.7m
Epoch 441/500 | Batch 30/202 | Rec 0.000492 | Seg 0.255979 | Elapsed 0.6m | ETA 3.5m
Epoch 441/500 | Batch 40/202 | Rec 0.000531 | Seg 0.265251 | Elapsed 0.8m | ETA 3.3m
Epoch 441/500 | Batch 50/202 | Rec 0.000531 | Seg 0.269246 | Elapsed 1.0m | ETA 3.1m
Epoch 441/500 | Batch 60/202 | Rec 0.000538 | Seg 0.271016 | Elapsed 1.2m | ETA 2.9m
Epoch 441/500 | Batch 70/202 | Rec 0.000540 | Seg 0.264627 | Elapsed 1.4m | ETA 2.7m
Epoch 441/500 | Batch 80/202 | Rec 0.000540 | Seg 0.261912 | Elapsed 1.6m | ETA 2.5m
Epoch 441/500 | Batch 90/202 | Rec 0.000547 | Seg 0.267281 | Elapsed 1.9m | ETA 2.3m
Epoch 441/500 | Batch 100/202 | Rec 0.000553 | Seg 0.267968 | Elapsed 2.1m | ETA 2.1m
Epoch 441/500 | Batch 110/202 | Rec 0.000551 | Seg 0.268827 | Elapsed 2.3m | ETA 1.9m
Epoch 441/500 | Batch 120/202 | Rec 0.000548 | Seg 0.268857 | Elapsed 2.5m | ETA 1.7m
Epoch 441/500 | Batch 130/202 | Rec 0.000559 | Seg 0.273843 | Elapsed 2.7m | ETA 1.5m
Epoch 441/500 | Batch 140/202 | Rec 0.000556 | Seg 0.273418 | Elapsed 2.9m | ETA 1.3m
Epoch 441/500 | Batch 150/202 | Rec 0.000557 | Seg 0.275262 | Elapsed 3.1m | ETA 1.1m
Epoch 441/500 | Batch 160/202 | Rec 0.000557 | Seg 0.276072 | Elapsed 3.3m | ETA 0.9m
Epoch 441/500 | Batch 170/202 | Rec 0.000550 | Seg 0.272763 | Elapsed 3.5m | ETA 0.7m
Epoch 441/500 | Batch 180/202 | Rec 0.000555 | Seg 0.270377 | Elapsed 3.7m | ETA 0.5m
Epoch 441/500 | Batch 190/202 | Rec 0.000556 | Seg 0.270975 | Elapsed 3.9m | ETA 0.2m
Epoch 441/500 | Batch 200/202 | Rec 0.000559 | Seg 0.270889 | Elapsed 4.1m | ETA 0.0m
Epoch 441/500 | Batch 202/202 | Rec 0.000562 | Seg 0.271035 | Elapsed 4.2m | ETA 0.0m

2026-10-10 12:32:31,248 - INFO: Rec loss: 0.0005615957117049337
2026-10-10 12:32:31,248 - INFO: Seg loss: 0.27103499212477467
2026-10-10 12:32:31,248 - INFO: λ_rec: 1
2026-10-10 12:32:31,248 - INFO: λ_seg: 0.0001
2026-10-10 12:33:51,781 - INFO: -------------------Epoch: 441------------------------
2026-10-10 12:33:51,785 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.006846  0.974785  0.000131
2026-10-10 12:33:51,792 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995787  0.997839  0.997217  0.998562  0.995978
real potato   0.891879  0.942800  0.960693  0.925657  0.999866
fake potato   0.927040  0.962089  0.982955  0.942187  0.999946
real apple    0.814152  0.897507  0.959390  0.843211  0.999336
fake apple    0.599559  0.749608  0.988357  0.603823  0.998477
real orange   0.917723  0.957047  0.994754  0.922186  0.999891
fake orange   0.935366  0.966554  0.953960  0.979586  0.999806
real grape    0.815870  0.898550  0.943057  0.858145  0.999596
fake grape    0.895325  0.944722  0.915886  0.975539  0.999578
real lemon    0.731780  0.845069  0.780281  0.921709  0.999603
fake lemon    0.854995  0.921780  0.996813  0.857339  0.999692
real avocado  0.910046  0.952855  0.939375  0.966831  0.999911
fake avocado  0.711882  0.831646  0.999642  0.712063  0.999655
real pepper   0.845314  0.916124  0.871709  0.965418  0.999354
fake pepper   0.733120  0.845963  0.947891  0.763908  0.999337
real plant    0.866085  0.928187  0.961363  0.897318  0.998612
fake plant    0.788185  0.881498  0.841170  0.925997  0.999802
real banana   0.742898  0.852436  0.908818  0.802730  0.999376
fake banana   0.724092  0.839919  0.820787  0.860070  0.999397
real onion    0.653006  0.790034  0.681829  0.939199  0.999549
fake onion    0.938563  0.968258  0.976161  0.960580  0.999960
real unknown  0.801324  0.889656  0.858156  0.923664  0.999963
fake unknown  0.230837  0.375050  0.254165  0.715502  0.997991
total         0.796732  0.876313  0.892801  0.880923  0.999334
total(-bg)    0.787684  0.870789  0.888055  0.875576  0.999486
2026-10-10 12:33:52,401 - INFO: Epoch accounting: {'epoch': 441, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11314007, 48373, 61773, 118762, 156434, 84723, 83220, 155483, 209152, 69715, 61365, 27935, 51907, 206903, 90742, 153372, 29623, 75222, 61302, 73887, 51282, 9683, 43407], 'crops_with_class': [202, 27, 28, 33, 39, 25, 30, 33, 40, 26, 24, 12, 14, 48, 24, 22, 24, 22, 26, 34, 24, 11, 22], 'targeted_crops_by_class': [0, 2, 3, 5, 5, 4, 6, 7, 4, 0, 8, 0, 5, 4, 4, 4, 4, 5, 5, 4, 4, 4, 9], 'sampled_scene_counts': [1, 1, 1, 0, 2, 0, 2, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 3, 0, 1, 2, 1, 3, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 2, 0, 0, 2, 1, 1, 0, 0, 1, 0, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 0, 0, 1, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 1, 2, 1, 3, 1, 1, 0, 2, 3, 0, 1, 2, 1, 2, 3, 3, 1, 1, 0, 0, 1, 2, 0, 0, 1, 2, 1, 1, 0, 1, 0, 2, 2, 2, 0, 3, 5, 0, 3, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 0, 2, 0, 1, 2, 1, 0, 1, 2, 0, 4, 1, 2, 1, 1, 0, 3, 1, 1, 2, 2, 0, 1, 1, 1, 1, 1, 3], 'learning_rate': 3.752397766323452e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005615957117049337, 'train_segmentation_loss': 0.27103499212477467, 'val_foreground_miou_all22': 0.7876837070566084, 'val_psnr_ref1': 39.006845703125, 'elapsed_seconds': 331.33693742752075, 'peak_cuda_allocated_gib': 7.514194488525391}

Epoch 442/500 | Batch 10/202 | Rec 0.000701 | Seg 0.223747 | Elapsed 0.2m | ETA 4.0m
Epoch 442/500 | Batch 20/202 | Rec 0.000703 | Seg 0.275190 | Elapsed 0.4m | ETA 3.8m
Epoch 442/500 | Batch 30/202 | Rec 0.000695 | Seg 0.297795 | Elapsed 0.6m | ETA 3.6m
Epoch 442/500 | Batch 40/202 | Rec 0.000662 | Seg 0.284130 | Elapsed 0.8m | ETA 3.3m
Epoch 442/500 | Batch 50/202 | Rec 0.000629 | Seg 0.275168 | Elapsed 1.0m | ETA 3.1m
Epoch 442/500 | Batch 60/202 | Rec 0.000618 | Seg 0.278078 | Elapsed 1.2m | ETA 2.9m
Epoch 442/500 | Batch 70/202 | Rec 0.000603 | Seg 0.277618 | Elapsed 1.4m | ETA 2.7m
Epoch 442/500 | Batch 80/202 | Rec 0.000597 | Seg 0.277716 | Elapsed 1.6m | ETA 2.5m
Epoch 442/500 | Batch 90/202 | Rec 0.000597 | Seg 0.277428 | Elapsed 1.8m | ETA 2.3m
Epoch 442/500 | Batch 100/202 | Rec 0.000598 | Seg 0.277240 | Elapsed 2.0m | ETA 2.1m
Epoch 442/500 | Batch 110/202 | Rec 0.000601 | Seg 0.285342 | Elapsed 2.2m | ETA 1.9m
Epoch 442/500 | Batch 120/202 | Rec 0.000611 | Seg 0.290138 | Elapsed 2.5m | ETA 1.7m
Epoch 442/500 | Batch 130/202 | Rec 0.000598 | Seg 0.284266 | Elapsed 2.7m | ETA 1.5m
Epoch 442/500 | Batch 140/202 | Rec 0.000590 | Seg 0.278382 | Elapsed 2.9m | ETA 1.3m
Epoch 442/500 | Batch 150/202 | Rec 0.000584 | Seg 0.274547 | Elapsed 3.1m | ETA 1.1m
Epoch 442/500 | Batch 160/202 | Rec 0.000593 | Seg 0.279958 | Elapsed 3.3m | ETA 0.9m
Epoch 442/500 | Batch 170/202 | Rec 0.000591 | Seg 0.279662 | Elapsed 3.5m | ETA 0.7m
Epoch 442/500 | Batch 180/202 | Rec 0.000586 | Seg 0.280253 | Elapsed 3.7m | ETA 0.5m
Epoch 442/500 | Batch 190/202 | Rec 0.000585 | Seg 0.281782 | Elapsed 3.9m | ETA 0.2m
Epoch 442/500 | Batch 200/202 | Rec 0.000582 | Seg 0.280879 | Elapsed 4.1m | ETA 0.0m
Epoch 442/500 | Batch 202/202 | Rec 0.000580 | Seg 0.279606 | Elapsed 4.1m | ETA 0.0m

2026-10-10 12:38:01,248 - INFO: Rec loss: 0.0005799680951139014
2026-10-10 12:38:01,248 - INFO: Seg loss: 0.27960631070603237
2026-10-10 12:38:01,248 - INFO: λ_rec: 1
2026-10-10 12:38:01,248 - INFO: λ_seg: 0.0001
2026-10-10 12:39:19,895 - INFO: -------------------Epoch: 442------------------------
2026-10-10 12:39:19,898 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.164571  0.975175  0.000127
2026-10-10 12:39:19,904 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995801  0.997846  0.997297  0.998496  0.995992
real potato   0.370970  0.541139  0.977674  0.374139  0.999241
fake potato   0.670889  0.802984  0.987168  0.676791  0.999758
real apple    0.691973  0.817898  0.759262  0.886466  0.998639
fake apple    0.577333  0.731991  0.992871  0.579736  0.998398
real orange   0.937543  0.967715  0.992935  0.943840  0.999917
fake orange   0.934724  0.966211  0.951483  0.981505  0.999804
real grape    0.832076  0.908292  0.930884  0.886867  0.999626
fake grape    0.902495  0.948699  0.925843  0.972817  0.999611
real lemon    0.525141  0.688600  0.539021  0.953259  0.998987
fake lemon    0.868142  0.929368  0.992061  0.874216  0.999719
real avocado  0.802449  0.890349  0.823973  0.968473  0.999778
fake avocado  0.765426  0.867080  0.999667  0.765621  0.999719
real pepper   0.760118  0.863663  0.804529  0.932296  0.998924
fake pepper   0.563663  0.720905  0.948324  0.581525  0.998927
real plant    0.876312  0.934029  0.955736  0.913382  0.998710
fake plant    0.779382  0.875964  0.862505  0.889954  0.999799
real banana   0.468973  0.638459  0.872543  0.503463  0.998719
fake banana   0.750978  0.857731  0.856081  0.859489  0.999476
real onion    0.576883  0.731625  0.716343  0.747678  0.999505
fake onion    0.899904  0.947265  0.994416  0.904474  0.999937
real unknown  0.851757  0.919894  0.893082  0.948473  0.999974
fake unknown  0.208167  0.344564  0.225689  0.728359  0.997666
total         0.722222  0.821403  0.869538  0.820492  0.999166
total(-bg)    0.709786  0.813383  0.863731  0.812401  0.999311
2026-10-10 12:39:20,391 - INFO: Epoch accounting: {'epoch': 442, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11277510, 55305, 63168, 95753, 173264, 73346, 88056, 162918, 220532, 73238, 47628, 50579, 33683, 205887, 109814, 111239, 18350, 97764, 77725, 91024, 46314, 9880, 55295], 'crops_with_class': [202, 36, 28, 30, 44, 24, 28, 30, 35, 36, 23, 19, 14, 56, 35, 14, 18, 29, 30, 40, 23, 11, 24], 'targeted_crops_by_class': [0, 6, 4, 2, 2, 2, 7, 6, 7, 0, 2, 5, 7, 10, 6, 2, 3, 5, 3, 4, 2, 5, 7], 'sampled_scene_counts': [1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 2, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 0, 1, 3, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 4, 3, 2, 2, 0, 2, 3, 1, 2, 1, 1, 1, 1, 1, 2, 0, 1, 1, 0, 3, 2, 0, 2, 0, 1, 2, 2, 0, 1, 0, 2, 1, 0, 2, 1, 2, 1, 2, 3, 3, 2, 1, 3, 1, 1, 1, 2, 3, 3, 1, 0, 1, 1, 1, 3, 1, 1, 2, 1, 1, 1, 1, 3, 0, 1, 2, 1, 0, 4, 0, 3, 3, 3, 1, 0, 2, 1, 2, 1, 1, 0, 1], 'learning_rate': 3.6379532661467224e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005799680951139014, 'train_segmentation_loss': 0.27960631070603237, 'val_foreground_miou_all22': 0.7097863368726907, 'val_psnr_ref1': 39.16457077026367, 'elapsed_seconds': 327.98223900794983, 'peak_cuda_allocated_gib': 7.509952545166016}

Epoch 443/500 | Batch 10/202 | Rec 0.000539 | Seg 0.223654 | Elapsed 0.2m | ETA 3.8m
Epoch 443/500 | Batch 20/202 | Rec 0.000521 | Seg 0.231069 | Elapsed 0.4m | ETA 3.7m
Epoch 443/500 | Batch 30/202 | Rec 0.000509 | Seg 0.242965 | Elapsed 0.6m | ETA 3.5m
Epoch 443/500 | Batch 40/202 | Rec 0.000521 | Seg 0.261402 | Elapsed 0.8m | ETA 3.3m
Epoch 443/500 | Batch 50/202 | Rec 0.000541 | Seg 0.269881 | Elapsed 1.0m | ETA 3.1m
Epoch 443/500 | Batch 60/202 | Rec 0.000566 | Seg 0.277244 | Elapsed 1.2m | ETA 2.9m
Epoch 443/500 | Batch 70/202 | Rec 0.000568 | Seg 0.278171 | Elapsed 1.4m | ETA 2.7m
Epoch 443/500 | Batch 80/202 | Rec 0.000560 | Seg 0.273878 | Elapsed 1.6m | ETA 2.5m
Epoch 443/500 | Batch 90/202 | Rec 0.000555 | Seg 0.267966 | Elapsed 1.8m | ETA 2.3m
Epoch 443/500 | Batch 100/202 | Rec 0.000550 | Seg 0.265086 | Elapsed 2.1m | ETA 2.1m
Epoch 443/500 | Batch 110/202 | Rec 0.000552 | Seg 0.267272 | Elapsed 2.3m | ETA 1.9m
Epoch 443/500 | Batch 120/202 | Rec 0.000543 | Seg 0.264364 | Elapsed 2.5m | ETA 1.7m
Epoch 443/500 | Batch 130/202 | Rec 0.000537 | Seg 0.263162 | Elapsed 2.7m | ETA 1.5m
Epoch 443/500 | Batch 140/202 | Rec 0.000542 | Seg 0.267516 | Elapsed 2.9m | ETA 1.3m
Epoch 443/500 | Batch 150/202 | Rec 0.000552 | Seg 0.269597 | Elapsed 3.1m | ETA 1.1m
Epoch 443/500 | Batch 160/202 | Rec 0.000557 | Seg 0.272252 | Elapsed 3.3m | ETA 0.9m
Epoch 443/500 | Batch 170/202 | Rec 0.000554 | Seg 0.271512 | Elapsed 3.5m | ETA 0.7m
Epoch 443/500 | Batch 180/202 | Rec 0.000545 | Seg 0.266168 | Elapsed 3.7m | ETA 0.5m
Epoch 443/500 | Batch 190/202 | Rec 0.000545 | Seg 0.267532 | Elapsed 3.9m | ETA 0.2m
Epoch 443/500 | Batch 200/202 | Rec 0.000540 | Seg 0.265482 | Elapsed 4.1m | ETA 0.0m
Epoch 443/500 | Batch 202/202 | Rec 0.000540 | Seg 0.264670 | Elapsed 4.2m | ETA 0.0m

2026-10-10 12:43:29,539 - INFO: Rec loss: 0.0005395592995435184
2026-10-10 12:43:29,539 - INFO: Seg loss: 0.26467031161162524
2026-10-10 12:43:29,539 - INFO: λ_rec: 1
2026-10-10 12:43:29,539 - INFO: λ_seg: 0.0001
2026-10-10 12:44:46,402 - INFO: -------------------Epoch: 443------------------------
2026-10-10 12:44:46,406 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.932368  0.974799  0.000134
2026-10-10 12:44:46,412 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995664  0.997777  0.997415  0.998240  0.995862
real potato   0.388693  0.559756  0.963263  0.394542  0.999258
fake potato   0.696366  0.820960  0.987920  0.702346  0.999777
real apple    0.681472  0.810516  0.783641  0.839407  0.998646
fake apple    0.652881  0.789943  0.985913  0.659028  0.998677
real orange   0.955256  0.977066  0.993065  0.961672  0.999941
fake orange   0.939580  0.968799  0.951209  0.987155  0.999818
real grape    0.805468  0.892204  0.930561  0.856976  0.999568
fake grape    0.901564  0.948184  0.921129  0.976983  0.999605
real lemon    0.517840  0.682292  0.531250  0.953519  0.998957
fake lemon    0.857122  0.923015  0.997071  0.859286  0.999697
real avocado  0.879200  0.935667  0.906543  0.966831  0.999877
fake avocado  0.648731  0.786898  0.999803  0.648814  0.999580
real pepper   0.761794  0.864744  0.796620  0.945728  0.998918
fake pepper   0.586941  0.739667  0.969684  0.597913  0.998997
real plant    0.873553  0.932459  0.950605  0.915090  0.998675
fake plant    0.765483  0.867116  0.846730  0.888612  0.999783
real banana   0.447315  0.618084  0.832624  0.491512  0.998635
fake banana   0.719613  0.836898  0.811274  0.864300  0.999380
real onion    0.633432  0.775535  0.680031  0.902381  0.999528
fake onion    0.905405  0.950305  0.997607  0.907376  0.999940
real unknown  0.659289  0.794616  0.689341  0.937977  0.999922
fake unknown  0.235948  0.381772  0.251910  0.788301  0.997849
total         0.717766  0.819751  0.859792  0.828000  0.999169
total(-bg)    0.705134  0.811659  0.853536  0.820261  0.999320
2026-10-10 12:44:46,875 - INFO: Epoch accounting: {'epoch': 443, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11325736, 46917, 52427, 161329, 134618, 79105, 63064, 131100, 214745, 76859, 58785, 53152, 42460, 260000, 94282, 116070, 24008, 47224, 66190, 75595, 49522, 12546, 52538], 'crops_with_class': [202, 25, 24, 41, 35, 23, 21, 30, 38, 30, 25, 20, 17, 61, 27, 18, 22, 14, 31, 32, 23, 14, 27], 'targeted_crops_by_class': [0, 5, 3, 6, 7, 5, 5, 2, 7, 5, 4, 5, 7, 2, 7, 3, 3, 2, 4, 1, 9, 5, 5], 'sampled_scene_counts': [0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 0, 2, 0, 3, 0, 1, 1, 1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 3, 1, 1, 1, 1, 2, 1, 1, 2, 3, 1, 1, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 2, 0, 0, 2, 2, 4, 1, 0, 1, 2, 0, 0, 2, 1, 0, 4, 1, 1, 1, 2, 1, 3, 4, 2, 5, 3, 2, 2, 3, 0, 1, 3, 0, 0, 1, 0, 2, 0, 1, 2, 2, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 3, 3, 0, 1], 'learning_rate': 3.5253439949764694e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005395592995435184, 'train_segmentation_loss': 0.26467031161162524, 'val_foreground_miou_all22': 0.7051339664320961, 'val_psnr_ref1': 38.9323681640625, 'elapsed_seconds': 326.4770607948303, 'peak_cuda_allocated_gib': 7.510288238525391}

Epoch 444/500 | Batch 10/202 | Rec 0.000403 | Seg 0.221369 | Elapsed 0.2m | ETA 3.8m
Epoch 444/500 | Batch 20/202 | Rec 0.000444 | Seg 0.233400 | Elapsed 0.4m | ETA 3.6m
Epoch 444/500 | Batch 30/202 | Rec 0.000464 | Seg 0.239458 | Elapsed 0.6m | ETA 3.4m
Epoch 444/500 | Batch 40/202 | Rec 0.000513 | Seg 0.267898 | Elapsed 0.8m | ETA 3.2m
Epoch 444/500 | Batch 50/202 | Rec 0.000520 | Seg 0.266591 | Elapsed 1.0m | ETA 3.1m
Epoch 444/500 | Batch 60/202 | Rec 0.000523 | Seg 0.269284 | Elapsed 1.2m | ETA 2.9m
Epoch 444/500 | Batch 70/202 | Rec 0.000548 | Seg 0.285040 | Elapsed 1.4m | ETA 2.7m
Epoch 444/500 | Batch 80/202 | Rec 0.000551 | Seg 0.282412 | Elapsed 1.6m | ETA 2.5m
Epoch 444/500 | Batch 90/202 | Rec 0.000545 | Seg 0.280584 | Elapsed 1.8m | ETA 2.3m
Epoch 444/500 | Batch 100/202 | Rec 0.000550 | Seg 0.285613 | Elapsed 2.0m | ETA 2.1m
Epoch 444/500 | Batch 110/202 | Rec 0.000554 | Seg 0.288923 | Elapsed 2.3m | ETA 1.9m
Epoch 444/500 | Batch 120/202 | Rec 0.000561 | Seg 0.285363 | Elapsed 2.5m | ETA 1.7m
Epoch 444/500 | Batch 130/202 | Rec 0.000558 | Seg 0.277522 | Elapsed 2.7m | ETA 1.5m
Epoch 444/500 | Batch 140/202 | Rec 0.000555 | Seg 0.274037 | Elapsed 2.9m | ETA 1.3m
Epoch 444/500 | Batch 150/202 | Rec 0.000560 | Seg 0.272719 | Elapsed 3.1m | ETA 1.1m
Epoch 444/500 | Batch 160/202 | Rec 0.000563 | Seg 0.271356 | Elapsed 3.3m | ETA 0.9m
Epoch 444/500 | Batch 170/202 | Rec 0.000568 | Seg 0.274138 | Elapsed 3.5m | ETA 0.7m
Epoch 444/500 | Batch 180/202 | Rec 0.000569 | Seg 0.277451 | Elapsed 3.7m | ETA 0.5m
Epoch 444/500 | Batch 190/202 | Rec 0.000569 | Seg 0.277661 | Elapsed 3.9m | ETA 0.2m
Epoch 444/500 | Batch 200/202 | Rec 0.000569 | Seg 0.276674 | Elapsed 4.1m | ETA 0.0m
Epoch 444/500 | Batch 202/202 | Rec 0.000570 | Seg 0.276513 | Elapsed 4.1m | ETA 0.0m

2026-10-10 12:48:55,275 - INFO: Rec loss: 0.0005703065746796945
2026-10-10 12:48:55,275 - INFO: Seg loss: 0.276512980719309
2026-10-10 12:48:55,276 - INFO: λ_rec: 1
2026-10-10 12:48:55,276 - INFO: λ_seg: 0.0001
2026-10-10 12:50:11,285 - INFO: -------------------Epoch: 444------------------------
2026-10-10 12:50:11,289 - INFO:
Validation stats:
       PSNR      SSIM      MSE
0  39.05279  0.974944  0.00013
2026-10-10 12:50:11,296 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995668  0.997779  0.997196  0.998464  0.995864
real potato   0.892967  0.943408  0.928827  0.958556  0.999863
fake potato   0.962902  0.981051  0.978139  0.984080  0.999972
real apple    0.804885  0.891847  0.966785  0.827775  0.999308
fake apple    0.559631  0.717599  0.995198  0.561146  0.998333
real orange   0.904214  0.949648  0.993674  0.909449  0.999873
fake orange   0.924555  0.960749  0.952446  0.969300  0.999774
real grape    0.799699  0.888653  0.925255  0.854929  0.999553
fake grape    0.899668  0.947135  0.922238  0.973518  0.999598
real lemon    0.782167  0.877721  0.816698  0.948715  0.999689
fake lemon    0.826225  0.904795  0.996703  0.828489  0.999631
real avocado  0.900308  0.947489  0.935928  0.959442  0.999901
fake avocado  0.740599  0.850921  0.999484  0.740882  0.999689
real pepper   0.789217  0.882143  0.812178  0.965418  0.999057
fake pepper   0.629481  0.772567  0.927374  0.662121  0.999071
real plant    0.868655  0.929661  0.961065  0.900339  0.998638
fake plant    0.762286  0.865061  0.795115  0.948620  0.999765
real banana   0.754373  0.859942  0.867962  0.852166  0.999377
fake banana   0.703968  0.826219  0.780962  0.877157  0.999321
real onion    0.653767  0.790591  0.695524  0.915893  0.999562
fake onion    0.915297  0.955725  0.942407  0.969528  0.999943
real unknown  0.842568  0.914508  0.914995  0.914122  0.999973
fake unknown  0.219404  0.359814  0.249475  0.645418  0.998065
total         0.788370  0.870219  0.885027  0.876762  0.999297
total(-bg)    0.778947  0.864420  0.879929  0.871230  0.999453
2026-10-10 12:50:11,759 - INFO: Epoch accounting: {'epoch': 444, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11280355, 44693, 59030, 100487, 139396, 86495, 83031, 118601, 234255, 62380, 72733, 52501, 32258, 222055, 116827, 149591, 29753, 83177, 86942, 88819, 49554, 10303, 35036], 'crops_with_class': [202, 29, 26, 31, 37, 23, 28, 25, 38, 27, 28, 17, 14, 54, 29, 21, 22, 23, 35, 37, 28, 11, 15], 'targeted_crops_by_class': [0, 4, 4, 2, 8, 3, 4, 1, 8, 4, 7, 3, 3, 2, 4, 8, 7, 3, 7, 6, 3, 6, 2], 'sampled_scene_counts': [0, 1, 1, 1, 1, 0, 1, 1, 0, 3, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 2, 2, 0, 1, 0, 3, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 1, 3, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 0, 1, 2, 0, 1, 2, 0, 1, 1, 1, 0, 1, 2, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 2, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 1, 1, 1, 2, 0, 2, 4, 1, 3, 1, 0, 2, 2, 1, 0, 2, 1, 3, 3, 2, 1, 2, 1, 2, 2, 0, 1, 1, 1, 0, 0, 1, 1, 0, 4, 1, 3, 3, 0, 2, 3, 2, 2, 2, 1, 1, 3, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 0, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 4, 1, 1, 2, 2, 1], 'learning_rate': 3.414574398433904e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005703065746796945, 'train_segmentation_loss': 0.276512980719309, 'val_foreground_miou_all22': 0.7789471083694888, 'val_psnr_ref1': 39.05279006958008, 'elapsed_seconds': 324.87678480148315, 'peak_cuda_allocated_gib': 7.512241363525391}

Epoch 445/500 | Batch 10/202 | Rec 0.000696 | Seg 0.310382 | Elapsed 0.2m | ETA 4.0m
Epoch 445/500 | Batch 20/202 | Rec 0.000669 | Seg 0.293384 | Elapsed 0.4m | ETA 3.8m
Epoch 445/500 | Batch 30/202 | Rec 0.000605 | Seg 0.271137 | Elapsed 0.6m | ETA 3.5m
Epoch 445/500 | Batch 40/202 | Rec 0.000588 | Seg 0.283841 | Elapsed 0.8m | ETA 3.3m
Epoch 445/500 | Batch 50/202 | Rec 0.000608 | Seg 0.291812 | Elapsed 1.0m | ETA 3.1m
Epoch 445/500 | Batch 60/202 | Rec 0.000594 | Seg 0.287999 | Elapsed 1.2m | ETA 2.9m
Epoch 445/500 | Batch 70/202 | Rec 0.000594 | Seg 0.287187 | Elapsed 1.4m | ETA 2.7m
Epoch 445/500 | Batch 80/202 | Rec 0.000591 | Seg 0.285884 | Elapsed 1.6m | ETA 2.5m
Epoch 445/500 | Batch 90/202 | Rec 0.000599 | Seg 0.286890 | Elapsed 1.8m | ETA 2.3m
Epoch 445/500 | Batch 100/202 | Rec 0.000588 | Seg 0.279563 | Elapsed 2.1m | ETA 2.1m
Epoch 445/500 | Batch 110/202 | Rec 0.000580 | Seg 0.275010 | Elapsed 2.3m | ETA 1.9m
Epoch 445/500 | Batch 120/202 | Rec 0.000570 | Seg 0.272926 | Elapsed 2.5m | ETA 1.7m
Epoch 445/500 | Batch 130/202 | Rec 0.000577 | Seg 0.270438 | Elapsed 2.7m | ETA 1.5m
Epoch 445/500 | Batch 140/202 | Rec 0.000575 | Seg 0.274114 | Elapsed 2.9m | ETA 1.3m
Epoch 445/500 | Batch 150/202 | Rec 0.000575 | Seg 0.276553 | Elapsed 3.1m | ETA 1.1m
Epoch 445/500 | Batch 160/202 | Rec 0.000580 | Seg 0.278130 | Elapsed 3.3m | ETA 0.9m
Epoch 445/500 | Batch 170/202 | Rec 0.000583 | Seg 0.277733 | Elapsed 3.5m | ETA 0.7m
Epoch 445/500 | Batch 180/202 | Rec 0.000584 | Seg 0.274794 | Elapsed 3.7m | ETA 0.5m
Epoch 445/500 | Batch 190/202 | Rec 0.000581 | Seg 0.274094 | Elapsed 3.9m | ETA 0.2m
Epoch 445/500 | Batch 200/202 | Rec 0.000580 | Seg 0.276302 | Elapsed 4.1m | ETA 0.0m
Epoch 445/500 | Batch 202/202 | Rec 0.000579 | Seg 0.275656 | Elapsed 4.1m | ETA 0.0m

2026-10-10 12:54:19,972 - INFO: Rec loss: 0.0005792284112493968
2026-10-10 12:54:19,972 - INFO: Seg loss: 0.27565646509058994
2026-10-10 12:54:19,972 - INFO: λ_rec: 1
2026-10-10 12:54:19,972 - INFO: λ_seg: 0.0001
2026-10-10 12:55:33,222 - INFO: -------------------Epoch: 445------------------------
2026-10-10 12:55:33,226 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.119853  0.975082  0.000128
2026-10-10 12:55:33,233 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995431  0.997660  0.996763  0.998660  0.995636
real potato   0.521238  0.685235  0.947546  0.536725  0.999410
fake potato   0.772868  0.871835  0.981899  0.784039  0.999832
real apple    0.699453  0.823101  0.832211  0.814286  0.998793
fake apple    0.636524  0.777850  0.985980  0.642338  0.998615
real orange   0.934900  0.966305  0.994728  0.939555  0.999914
fake orange   0.931563  0.964519  0.957078  0.972178  0.999796
real grape    0.790539  0.882968  0.957231  0.819484  0.999547
fake grape    0.903910  0.949480  0.938195  0.961143  0.999622
real lemon    0.753955  0.859670  0.800650  0.928200  0.999644
fake lemon    0.855234  0.921919  0.995484  0.858565  0.999693
real avocado  0.887634  0.940422  0.914778  0.967652  0.999886
fake avocado  0.715579  0.834164  0.999644  0.715761  0.999660
real pepper   0.775191  0.873311  0.809144  0.948648  0.998994
fake pepper   0.606811  0.755250  0.951284  0.626272  0.999033
real plant    0.856488  0.922647  0.955012  0.892498  0.998504
fake plant    0.783378  0.878483  0.866493  0.890913  0.999804
real banana   0.725044  0.840559  0.896706  0.791118  0.999326
fake banana   0.738675  0.849649  0.851361  0.848042  0.999448
real onion    0.637533  0.778602  0.665827  0.937511  0.999518
fake onion    0.925138  0.961063  0.988247  0.935429  0.999952
real unknown  0.604492  0.753451  0.635827  0.924618  0.999903
fake unknown  0.226513  0.369323  0.249665  0.709526  0.997959
total         0.751221  0.845977  0.877033  0.845355  0.999239
total(-bg)    0.740121  0.839082  0.871590  0.838386  0.999402
2026-10-10 12:55:33,700 - INFO: Epoch accounting: {'epoch': 445, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11259447, 50009, 57602, 159515, 119744, 79887, 82414, 126421, 267512, 62245, 63534, 70972, 39040, 206564, 142052, 91957, 19662, 79789, 76682, 83268, 40967, 12239, 46750], 'crops_with_class': [202, 32, 24, 39, 33, 27, 28, 24, 35, 31, 26, 23, 18, 51, 36, 16, 17, 23, 30, 38, 21, 15, 19], 'targeted_crops_by_class': [0, 2, 7, 6, 3, 5, 3, 5, 3, 5, 2, 7, 6, 3, 3, 2, 3, 6, 7, 5, 4, 7, 4], 'sampled_scene_counts': [1, 0, 1, 1, 1, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 2, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 2, 1, 0, 2, 0, 1, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 2, 2, 1, 1, 0, 0, 0, 1, 2, 2, 3, 1, 1, 2, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2, 4, 1, 2, 3, 0, 1, 3, 3, 0, 1, 0, 1, 2, 2, 1, 0, 2, 0, 0, 2, 1, 0, 4, 2, 2, 2, 2, 0, 3, 2, 1, 1, 3, 0, 2, 2, 4, 3, 1, 2, 0, 0, 3, 1, 1, 2, 0, 0, 0, 2, 0, 4, 2, 1, 1, 0, 0, 1, 0, 2, 1, 2, 4, 0, 0, 1, 1, 2, 1, 2, 2, 0, 2, 1, 2, 1, 1, 1, 3], 'learning_rate': 3.3056488495130252e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005792284112493968, 'train_segmentation_loss': 0.27565646509058994, 'val_foreground_miou_all22': 0.7401208278922542, 'val_psnr_ref1': 39.11985305786133, 'elapsed_seconds': 321.9336688518524, 'peak_cuda_allocated_gib': 7.508365631103516}

Epoch 446/500 | Batch 10/202 | Rec 0.000525 | Seg 0.253878 | Elapsed 0.2m | ETA 4.1m
Epoch 446/500 | Batch 20/202 | Rec 0.000546 | Seg 0.270092 | Elapsed 0.4m | ETA 3.8m
Epoch 446/500 | Batch 30/202 | Rec 0.000539 | Seg 0.262034 | Elapsed 0.6m | ETA 3.6m
Epoch 446/500 | Batch 40/202 | Rec 0.000525 | Seg 0.253844 | Elapsed 0.8m | ETA 3.4m
Epoch 446/500 | Batch 50/202 | Rec 0.000492 | Seg 0.239461 | Elapsed 1.0m | ETA 3.2m
Epoch 446/500 | Batch 60/202 | Rec 0.000558 | Seg 0.255785 | Elapsed 1.2m | ETA 3.0m
Epoch 446/500 | Batch 70/202 | Rec 0.000541 | Seg 0.254578 | Elapsed 1.5m | ETA 2.7m
Epoch 446/500 | Batch 80/202 | Rec 0.000552 | Seg 0.269476 | Elapsed 1.7m | ETA 2.5m
Epoch 446/500 | Batch 90/202 | Rec 0.000544 | Seg 0.269842 | Elapsed 1.9m | ETA 2.3m
Epoch 446/500 | Batch 100/202 | Rec 0.000545 | Seg 0.268799 | Elapsed 2.1m | ETA 2.1m
Epoch 446/500 | Batch 110/202 | Rec 0.000550 | Seg 0.264346 | Elapsed 2.3m | ETA 1.9m
Epoch 446/500 | Batch 120/202 | Rec 0.000549 | Seg 0.264096 | Elapsed 2.5m | ETA 1.7m
Epoch 446/500 | Batch 130/202 | Rec 0.000545 | Seg 0.265001 | Elapsed 2.7m | ETA 1.5m
Epoch 446/500 | Batch 140/202 | Rec 0.000548 | Seg 0.271820 | Elapsed 2.9m | ETA 1.3m
Epoch 446/500 | Batch 150/202 | Rec 0.000544 | Seg 0.271019 | Elapsed 3.1m | ETA 1.1m
Epoch 446/500 | Batch 160/202 | Rec 0.000547 | Seg 0.272571 | Elapsed 3.3m | ETA 0.9m
Epoch 446/500 | Batch 170/202 | Rec 0.000549 | Seg 0.271545 | Elapsed 3.5m | ETA 0.7m
Epoch 446/500 | Batch 180/202 | Rec 0.000551 | Seg 0.272065 | Elapsed 3.7m | ETA 0.5m
Epoch 446/500 | Batch 190/202 | Rec 0.000553 | Seg 0.270750 | Elapsed 3.9m | ETA 0.2m
Epoch 446/500 | Batch 200/202 | Rec 0.000559 | Seg 0.273227 | Elapsed 4.1m | ETA 0.0m
Epoch 446/500 | Batch 202/202 | Rec 0.000557 | Seg 0.272603 | Elapsed 4.2m | ETA 0.0m

2026-10-10 12:59:43,624 - INFO: Rec loss: 0.0005568594057003433
2026-10-10 12:59:43,624 - INFO: Seg loss: 0.2726027894174994
2026-10-10 12:59:43,624 - INFO: λ_rec: 1
2026-10-10 12:59:43,624 - INFO: λ_seg: 0.0001
2026-10-10 13:01:04,245 - INFO: -------------------Epoch: 446------------------------
2026-10-10 13:01:04,248 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.192154  0.975154  0.000126
2026-10-10 13:01:04,254 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995724  0.997808  0.997680  0.998035  0.995920
real potato   0.516468  0.681101  0.966487  0.525886  0.999411
fake potato   0.689895  0.816446  0.969749  0.705069  0.999769
real apple    0.704322  0.826463  0.810423  0.843255  0.998779
fake apple    0.598143  0.748501  0.983873  0.604066  0.998468
real orange   0.905689  0.950461  0.993934  0.910723  0.999875
fake orange   0.930387  0.963888  0.941643  0.987315  0.999789
real grape    0.803157  0.890784  0.962263  0.829277  0.999576
fake grape    0.879056  0.935586  0.897820  0.976777  0.999503
real lemon    0.449349  0.620026  0.465628  0.927811  0.998664
fake lemon    0.872555  0.931891  0.992342  0.878471  0.999729
real avocado  0.891167  0.942402  0.915737  0.970772  0.999890
fake avocado  0.569480  0.725646  0.999552  0.569625  0.999485
real pepper   0.800577  0.889195  0.827278  0.961246  0.999124
fake pepper   0.666999  0.800191  0.961639  0.685231  0.999185
real plant    0.871979  0.931562  0.950866  0.913122  0.998659
fake plant    0.829605  0.906818  0.871224  0.945552  0.999845
real banana   0.366873  0.536761  0.777091  0.410023  0.998410
fake banana   0.701997  0.824860  0.780574  0.874585  0.999317
real onion    0.636180  0.777592  0.681945  0.904577  0.999533
fake onion    0.946603  0.972519  0.985115  0.960339  0.999966
real unknown  0.597583  0.748061  0.619674  0.943702  0.999898
fake unknown  0.206530  0.342319  0.220316  0.767476  0.997516
total         0.714362  0.815690  0.850994  0.830128  0.999144
total(-bg)    0.701572  0.807412  0.844326  0.822495  0.999290
2026-10-10 13:01:04,708 - INFO: Epoch accounting: {'epoch': 446, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11278584, 41158, 44590, 135740, 158684, 43283, 78360, 134848, 237796, 74188, 55635, 67371, 52119, 212943, 132477, 201714, 22657, 36487, 34153, 77155, 49014, 9516, 59800], 'crops_with_class': [202, 24, 20, 36, 43, 16, 26, 25, 35, 32, 25, 22, 22, 55, 31, 23, 21, 13, 19, 28, 24, 11, 25], 'targeted_crops_by_class': [0, 3, 0, 3, 5, 0, 4, 4, 6, 3, 2, 5, 6, 6, 2, 7, 3, 0, 1, 2, 9, 7, 7], 'sampled_scene_counts': [0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 2, 0, 0, 2, 0, 0, 0, 1, 2, 1, 1, 1, 0, 1, 0, 0, 1, 2, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 2, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 2, 2, 0, 2, 2, 3, 2, 0, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 2, 3, 2, 1, 3, 0, 1, 1, 2, 1, 1, 2, 5, 1, 1, 0, 1, 2, 1, 2, 3, 6, 1, 1, 2, 3, 3, 1, 0, 0, 3, 2, 2, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1, 2, 1, 0, 0, 1, 0, 0, 0, 1, 0, 2, 2, 1, 1, 1, 3, 2, 0, 2, 0, 0], 'learning_rate': 3.1985716484080054e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005568594057003433, 'train_segmentation_loss': 0.2726027894174994, 'val_foreground_miou_all22': 0.7015724736474808, 'val_psnr_ref1': 39.192154235839844, 'elapsed_seconds': 331.0005028247833, 'peak_cuda_allocated_gib': 7.511173248291016}

Epoch 447/500 | Batch 10/202 | Rec 0.000585 | Seg 0.265413 | Elapsed 0.2m | ETA 4.0m
Epoch 447/500 | Batch 20/202 | Rec 0.000601 | Seg 0.282609 | Elapsed 0.4m | ETA 3.8m
Epoch 447/500 | Batch 30/202 | Rec 0.000574 | Seg 0.276176 | Elapsed 0.6m | ETA 3.5m
Epoch 447/500 | Batch 40/202 | Rec 0.000575 | Seg 0.288938 | Elapsed 0.8m | ETA 3.3m
Epoch 447/500 | Batch 50/202 | Rec 0.000552 | Seg 0.273392 | Elapsed 1.0m | ETA 3.1m
Epoch 447/500 | Batch 60/202 | Rec 0.000558 | Seg 0.281174 | Elapsed 1.2m | ETA 2.9m
Epoch 447/500 | Batch 70/202 | Rec 0.000578 | Seg 0.274455 | Elapsed 1.4m | ETA 2.7m
Epoch 447/500 | Batch 80/202 | Rec 0.000590 | Seg 0.283178 | Elapsed 1.6m | ETA 2.5m
Epoch 447/500 | Batch 90/202 | Rec 0.000580 | Seg 0.280647 | Elapsed 1.8m | ETA 2.3m
Epoch 447/500 | Batch 100/202 | Rec 0.000579 | Seg 0.280298 | Elapsed 2.0m | ETA 2.1m
Epoch 447/500 | Batch 110/202 | Rec 0.000569 | Seg 0.275979 | Elapsed 2.3m | ETA 1.9m
Epoch 447/500 | Batch 120/202 | Rec 0.000567 | Seg 0.275683 | Elapsed 2.5m | ETA 1.7m
Epoch 447/500 | Batch 130/202 | Rec 0.000574 | Seg 0.276799 | Elapsed 2.7m | ETA 1.5m
Epoch 447/500 | Batch 140/202 | Rec 0.000577 | Seg 0.285040 | Elapsed 2.9m | ETA 1.3m
Epoch 447/500 | Batch 150/202 | Rec 0.000574 | Seg 0.284382 | Elapsed 3.1m | ETA 1.1m
Epoch 447/500 | Batch 160/202 | Rec 0.000572 | Seg 0.283152 | Elapsed 3.3m | ETA 0.9m
Epoch 447/500 | Batch 170/202 | Rec 0.000575 | Seg 0.287446 | Elapsed 3.5m | ETA 0.7m
Epoch 447/500 | Batch 180/202 | Rec 0.000574 | Seg 0.286824 | Elapsed 3.7m | ETA 0.5m
Epoch 447/500 | Batch 190/202 | Rec 0.000576 | Seg 0.286011 | Elapsed 3.9m | ETA 0.2m
Epoch 447/500 | Batch 200/202 | Rec 0.000570 | Seg 0.281978 | Elapsed 4.1m | ETA 0.0m
Epoch 447/500 | Batch 202/202 | Rec 0.000570 | Seg 0.280924 | Elapsed 4.1m | ETA 0.0m

2026-10-10 13:05:12,934 - INFO: Rec loss: 0.000569718899905548
2026-10-10 13:05:12,934 - INFO: Seg loss: 0.28092414981657915
2026-10-10 13:05:12,934 - INFO: λ_rec: 1
2026-10-10 13:05:12,934 - INFO: λ_seg: 0.0001
2026-10-10 13:06:30,172 - INFO: -------------------Epoch: 447------------------------
2026-10-10 13:06:30,176 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.958304  0.974883  0.000133
2026-10-10 13:06:30,183 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995771  0.997831  0.997557  0.998205  0.995964
real potato   0.394665  0.565922  0.946204  0.403724  0.999259
fake potato   0.673440  0.804809  0.985138  0.680352  0.999760
real apple    0.664542  0.798418  0.781462  0.816232  0.998578
fake apple    0.700723  0.823980  0.961516  0.720942  0.998837
real orange   0.894016  0.943993  0.993097  0.899606  0.999859
fake orange   0.913702  0.954855  0.922370  0.989820  0.999732
real grape    0.778779  0.875584  0.938414  0.820726  0.999513
fake grape    0.901830  0.948331  0.922510  0.975746  0.999607
real lemon    0.529726  0.692530  0.544233  0.952090  0.999007
fake lemon    0.870850  0.930917  0.993455  0.875874  0.999725
real avocado  0.879598  0.935893  0.897633  0.977668  0.999876
fake avocado  0.811441  0.895857  0.998902  0.812165  0.999774
real pepper   0.780245  0.876509  0.813670  0.949983  0.999021
fake pepper   0.612100  0.759335  0.967400  0.624992  0.999056
real plant    0.867464  0.928979  0.944993  0.913595  0.998604
fake plant    0.850669  0.919259  0.900220  0.939225  0.999869
real banana   0.463057  0.632952  0.839184  0.508149  0.998676
fake banana   0.714491  0.833423  0.801701  0.867867  0.999362
real onion    0.617305  0.763326  0.655093  0.914541  0.999488
fake onion    0.904969  0.950064  0.997077  0.907376  0.999940
real unknown  0.567324  0.723893  0.580738  0.960878  0.999883
fake unknown  0.271311  0.426781  0.293084  0.785042  0.998223
total         0.724262  0.825367  0.855463  0.838904  0.999201
total(-bg)    0.711920  0.817528  0.849004  0.831663  0.999348
2026-10-10 13:06:30,663 - INFO: Epoch accounting: {'epoch': 447, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11245752, 46376, 52836, 136003, 154816, 76651, 74168, 168807, 144801, 82158, 57105, 45012, 46744, 236245, 113965, 192515, 37006, 67598, 66278, 69583, 57535, 17039, 49279], 'crops_with_class': [202, 27, 22, 37, 35, 22, 28, 34, 30, 36, 29, 17, 15, 58, 28, 26, 34, 21, 30, 33, 26, 18, 21], 'targeted_crops_by_class': [0, 4, 5, 5, 3, 3, 6, 4, 3, 2, 6, 8, 4, 7, 5, 7, 5, 2, 4, 4, 2, 7, 2], 'sampled_scene_counts': [0, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 2, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 2, 3, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 1, 1, 2, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 0, 2, 2, 2, 2, 3, 2, 0, 2, 3, 1, 1, 1, 2, 1, 1, 0, 3, 0, 1, 2, 0, 0, 0, 2, 2, 2, 1, 1, 1, 2, 1, 3, 1, 2, 0, 6, 2, 2, 0, 4, 4, 4, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 2, 1, 2, 0, 0, 1, 3, 2, 1, 0, 3, 3, 1, 0, 2, 0, 2, 2, 1, 1, 1, 0, 1, 3, 2, 3, 1, 1], 'learning_rate': 3.0933470223433763e-06, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000569718899905548, 'train_segmentation_loss': 0.28092414981657915, 'val_foreground_miou_all22': 0.7119202556119076, 'val_psnr_ref1': 38.958303985595705, 'elapsed_seconds': 325.9485909938812, 'peak_cuda_allocated_gib': 7.510044097900391}

Epoch 448/500 | Batch 10/202 | Rec 0.000573 | Seg 0.307852 | Elapsed 0.2m | ETA 4.0m
Epoch 448/500 | Batch 20/202 | Rec 0.000530 | Seg 0.267946 | Elapsed 0.4m | ETA 3.8m
Epoch 448/500 | Batch 30/202 | Rec 0.000513 | Seg 0.257815 | Elapsed 0.6m | ETA 3.5m
Epoch 448/500 | Batch 40/202 | Rec 0.000536 | Seg 0.256093 | Elapsed 0.8m | ETA 3.3m
Epoch 448/500 | Batch 50/202 | Rec 0.000533 | Seg 0.265838 | Elapsed 1.0m | ETA 3.1m
Epoch 448/500 | Batch 60/202 | Rec 0.000560 | Seg 0.277335 | Elapsed 1.2m | ETA 2.9m
Epoch 448/500 | Batch 70/202 | Rec 0.000552 | Seg 0.269233 | Elapsed 1.4m | ETA 2.7m
Epoch 448/500 | Batch 80/202 | Rec 0.000563 | Seg 0.278848 | Elapsed 1.6m | ETA 2.5m
Epoch 448/500 | Batch 90/202 | Rec 0.000553 | Seg 0.273791 | Elapsed 1.8m | ETA 2.3m
Epoch 448/500 | Batch 100/202 | Rec 0.000544 | Seg 0.271147 | Elapsed 2.0m | ETA 2.1m
Epoch 448/500 | Batch 110/202 | Rec 0.000537 | Seg 0.271011 | Elapsed 2.3m | ETA 1.9m
Epoch 448/500 | Batch 120/202 | Rec 0.000534 | Seg 0.271501 | Elapsed 2.5m | ETA 1.7m
Epoch 448/500 | Batch 130/202 | Rec 0.000532 | Seg 0.269784 | Elapsed 2.7m | ETA 1.5m
Epoch 448/500 | Batch 140/202 | Rec 0.000556 | Seg 0.273832 | Elapsed 2.9m | ETA 1.3m
Epoch 448/500 | Batch 150/202 | Rec 0.000552 | Seg 0.269339 | Elapsed 3.1m | ETA 1.1m
Epoch 448/500 | Batch 160/202 | Rec 0.000552 | Seg 0.268151 | Elapsed 3.3m | ETA 0.9m
Epoch 448/500 | Batch 170/202 | Rec 0.000564 | Seg 0.274316 | Elapsed 3.5m | ETA 0.7m
Epoch 448/500 | Batch 180/202 | Rec 0.000564 | Seg 0.272017 | Elapsed 3.7m | ETA 0.5m
Epoch 448/500 | Batch 190/202 | Rec 0.000558 | Seg 0.271427 | Elapsed 3.9m | ETA 0.2m
Epoch 448/500 | Batch 200/202 | Rec 0.000566 | Seg 0.276268 | Elapsed 4.1m | ETA 0.0m
Epoch 448/500 | Batch 202/202 | Rec 0.000565 | Seg 0.276485 | Elapsed 4.1m | ETA 0.0m

2026-10-10 13:10:39,465 - INFO: Rec loss: 0.0005646817591317957
2026-10-10 13:10:39,465 - INFO: Seg loss: 0.27648529310775277
2026-10-10 13:10:39,465 - INFO: λ_rec: 1
2026-10-10 13:10:39,465 - INFO: λ_seg: 0.0001
2026-10-10 13:11:59,696 - INFO: -------------------Epoch: 448------------------------
2026-10-10 13:11:59,700 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.101977  0.974957  0.000129
2026-10-10 13:11:59,706 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995780  0.997835  0.997168  0.998604  0.995971
real potato   0.778840  0.875622  0.983010  0.789467  0.999732
fake potato   0.865762  0.928002  0.962846  0.895685  0.999899
real apple    0.781761  0.877465  0.893401  0.862185  0.999170
fake apple    0.606702  0.755167  0.986701  0.611704  0.998503
real orange   0.899631  0.947114  0.995913  0.902964  0.999867
fake orange   0.930652  0.964031  0.948060  0.980652  0.999791
real grape    0.814931  0.897980  0.972076  0.834466  0.999604
fake grape    0.894620  0.944329  0.923884  0.965805  0.999579
real lemon    0.491383  0.658916  0.534545  0.858868  0.998955
fake lemon    0.843489  0.915051  0.961918  0.872629  0.999657
real avocado  0.904924  0.950039  0.937780  0.962726  0.999906
fake avocado  0.755128  0.860433  0.998820  0.755802  0.999707
real pepper   0.848158  0.917791  0.876695  0.963040  0.999369
fake pepper   0.745285  0.854006  0.934028  0.786697  0.999359
real plant    0.868296  0.929456  0.957108  0.903451  0.998629
fake plant    0.745967  0.854453  0.832515  0.877684  0.999762
real banana   0.493081  0.660441  0.876362  0.529947  0.998776
fake banana   0.664355  0.798284  0.746178  0.858328  0.999202
real onion    0.645234  0.784318  0.717913  0.864381  0.999571
fake onion    0.925829  0.961436  0.985279  0.938815  0.999953
real unknown  0.916190  0.956212  0.997925  0.917939  0.999987
fake unknown  0.212081  0.349905  0.241405  0.635820  0.998010
total         0.766438  0.853839  0.880936  0.850768  0.999259
total(-bg)    0.756014  0.847293  0.875653  0.844048  0.999409
2026-10-10 13:12:00,166 - INFO: Epoch accounting: {'epoch': 448, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11304461, 50239, 64297, 132730, 125752, 79201, 82164, 141680, 122404, 70068, 51302, 38144, 28376, 245518, 121883, 181779, 27033, 93333, 85147, 83455, 65376, 8388, 35542], 'crops_with_class': [202, 26, 26, 33, 29, 26, 28, 27, 26, 34, 22, 14, 12, 60, 34, 23, 24, 25, 34, 38, 27, 9, 17], 'targeted_crops_by_class': [0, 3, 5, 8, 3, 3, 6, 4, 1, 7, 4, 6, 3, 6, 1, 7, 7, 3, 7, 8, 7, 2, 2], 'sampled_scene_counts': [1, 2, 0, 1, 0, 1, 0, 0, 2, 1, 0, 2, 1, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 2, 2, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 3, 1, 1, 2, 1, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 3, 1, 1, 1, 0, 2, 0, 0, 0, 2, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 2, 2, 1, 0, 2, 0, 0, 1, 1, 1, 3, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 2, 2, 2, 4, 0, 1, 2, 2, 2, 1, 3, 0, 0, 1, 1, 2, 1, 3, 2, 1, 1, 1, 0, 0, 2, 3, 0, 1, 2, 1, 0, 1, 2, 2, 3, 1, 0, 2, 2, 2, 2, 1, 1, 0, 2, 0, 3, 1, 2, 3, 2, 1, 0, 0, 3, 0, 3, 3, 1, 0], 'learning_rate': 2.989979125407235e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005646817591317957, 'train_segmentation_loss': 0.27648529310775277, 'val_foreground_miou_all22': 0.7560136534012881, 'val_psnr_ref1': 39.10197738647461, 'elapsed_seconds': 329.4956226348877, 'peak_cuda_allocated_gib': 7.512241363525391}

Epoch 449/500 | Batch 10/202 | Rec 0.000423 | Seg 0.203219 | Elapsed 0.2m | ETA 4.0m
Epoch 449/500 | Batch 20/202 | Rec 0.000500 | Seg 0.252508 | Elapsed 0.4m | ETA 3.7m
Epoch 449/500 | Batch 30/202 | Rec 0.000511 | Seg 0.256099 | Elapsed 0.6m | ETA 3.5m
Epoch 449/500 | Batch 40/202 | Rec 0.000521 | Seg 0.267021 | Elapsed 0.8m | ETA 3.3m
Epoch 449/500 | Batch 50/202 | Rec 0.000550 | Seg 0.279209 | Elapsed 1.0m | ETA 3.1m
Epoch 449/500 | Batch 60/202 | Rec 0.000576 | Seg 0.283249 | Elapsed 1.2m | ETA 2.9m
Epoch 449/500 | Batch 70/202 | Rec 0.000554 | Seg 0.272519 | Elapsed 1.4m | ETA 2.7m
Epoch 449/500 | Batch 80/202 | Rec 0.000552 | Seg 0.278385 | Elapsed 1.6m | ETA 2.5m
Epoch 449/500 | Batch 90/202 | Rec 0.000572 | Seg 0.290435 | Elapsed 1.8m | ETA 2.3m
Epoch 449/500 | Batch 100/202 | Rec 0.000566 | Seg 0.287099 | Elapsed 2.1m | ETA 2.1m
Epoch 449/500 | Batch 110/202 | Rec 0.000557 | Seg 0.287053 | Elapsed 2.3m | ETA 1.9m
Epoch 449/500 | Batch 120/202 | Rec 0.000575 | Seg 0.284525 | Elapsed 2.5m | ETA 1.7m
Epoch 449/500 | Batch 130/202 | Rec 0.000571 | Seg 0.283093 | Elapsed 2.7m | ETA 1.5m
Epoch 449/500 | Batch 140/202 | Rec 0.000574 | Seg 0.283307 | Elapsed 2.9m | ETA 1.3m
Epoch 449/500 | Batch 150/202 | Rec 0.000576 | Seg 0.286012 | Elapsed 3.1m | ETA 1.1m
Epoch 449/500 | Batch 160/202 | Rec 0.000584 | Seg 0.287730 | Elapsed 3.3m | ETA 0.9m
Epoch 449/500 | Batch 170/202 | Rec 0.000581 | Seg 0.287285 | Elapsed 3.5m | ETA 0.7m
Epoch 449/500 | Batch 180/202 | Rec 0.000579 | Seg 0.288761 | Elapsed 3.7m | ETA 0.5m
Epoch 449/500 | Batch 190/202 | Rec 0.000592 | Seg 0.294159 | Elapsed 3.9m | ETA 0.2m
Epoch 449/500 | Batch 200/202 | Rec 0.000584 | Seg 0.289221 | Elapsed 4.1m | ETA 0.0m
Epoch 449/500 | Batch 202/202 | Rec 0.000581 | Seg 0.287372 | Elapsed 4.1m | ETA 0.0m

2026-10-10 13:16:09,055 - INFO: Rec loss: 0.0005808151863765498
2026-10-10 13:16:09,055 - INFO: Seg loss: 0.28737206283108435
2026-10-10 13:16:09,055 - INFO: λ_rec: 1
2026-10-10 13:16:09,055 - INFO: λ_seg: 0.0001
2026-10-10 13:17:26,911 - INFO: -------------------Epoch: 449------------------------
2026-10-10 13:17:26,914 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.143644  0.975105  0.000127
2026-10-10 13:17:26,920 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995533  0.997712  0.997061  0.998463  0.995735
real potato   0.707186  0.828432  0.940395  0.740372  0.999633
fake potato   0.795868  0.886283  0.983155  0.806871  0.999849
real apple    0.725298  0.840730  0.880103  0.804821  0.998948
fake apple    0.621504  0.766530  0.990776  0.625121  0.998563
real orange   0.898839  0.946675  0.992007  0.905396  0.999866
fake orange   0.907201  0.951293  0.929385  0.974363  0.999715
real grape    0.814812  0.897908  0.943854  0.856318  0.999594
fake grape    0.904797  0.949969  0.932053  0.968692  0.999623
real lemon    0.623001  0.767667  0.645979  0.945988  0.999327
fake lemon    0.849065  0.918322  0.997043  0.851208  0.999680
real avocado  0.848319  0.917886  0.871348  0.969787  0.999839
fake avocado  0.809099  0.894428  0.999213  0.809615  0.999771
real pepper   0.752512  0.858732  0.790295  0.940264  0.998869
fake pepper   0.564959  0.721964  0.963363  0.577364  0.998940
real plant    0.863484  0.926691  0.958003  0.897455  0.998581
fake plant    0.806762  0.892998  0.872235  0.914877  0.999826
real banana   0.592435  0.744013  0.862631  0.654149  0.998989
fake banana   0.732689  0.845675  0.824535  0.868033  0.999417
real onion    0.621655  0.766644  0.652215  0.929910  0.999489
fake onion    0.939692  0.968859  0.993144  0.945828  0.999962
real unknown  0.477816  0.646606  0.494201  0.935114  0.999837
fake unknown  0.236275  0.382198  0.261405  0.710793  0.998064
total         0.742991  0.839922  0.859756  0.853513  0.999222
total(-bg)    0.731512  0.832750  0.853515  0.846925  0.999381
2026-10-10 13:17:27,371 - INFO: Epoch accounting: {'epoch': 449, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11219447, 52352, 67774, 129069, 150670, 106650, 86446, 142390, 154511, 67161, 69682, 48177, 47310, 254807, 110802, 146430, 21402, 77027, 110130, 70043, 51514, 10600, 43878], 'crops_with_class': [202, 34, 28, 31, 37, 29, 31, 27, 29, 38, 25, 18, 17, 60, 31, 18, 20, 25, 39, 34, 25, 11, 21], 'targeted_crops_by_class': [0, 4, 2, 3, 5, 6, 5, 4, 3, 7, 4, 9, 8, 6, 5, 2, 2, 5, 8, 4, 2, 3, 5], 'sampled_scene_counts': [2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 0, 1, 1, 2, 0, 1, 2, 1, 0, 1, 0, 1, 0, 1, 1, 1, 2, 0, 1, 3, 2, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 2, 1, 2, 2, 4, 1, 0, 2, 2, 2, 1, 1, 2, 1, 1, 1, 4, 0, 2, 0, 1, 1, 2, 1, 1, 0, 3, 1, 0, 0, 2, 2, 4, 2, 2, 1, 2, 2, 1, 1, 0, 1, 6, 2, 0, 0, 1, 2, 1, 2, 1, 0, 2, 1, 1, 1, 5, 0, 2, 2, 0, 1, 1, 0, 3, 1, 0, 1, 1, 3, 3, 2, 1, 0, 2, 1, 2, 0, 2, 1, 3, 1, 2, 2], 'learning_rate': 2.888472038387126e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005808151863765498, 'train_segmentation_loss': 0.28737206283108435, 'val_foreground_miou_all22': 0.7315122388240244, 'val_psnr_ref1': 39.14364379882812, 'elapsed_seconds': 327.19712829589844, 'peak_cuda_allocated_gib': 7.512729644775391}

Epoch 450/500 | Batch 10/202 | Rec 0.000502 | Seg 0.288825 | Elapsed 0.2m | ETA 4.0m
Epoch 450/500 | Batch 20/202 | Rec 0.000545 | Seg 0.290851 | Elapsed 0.4m | ETA 3.8m
Epoch 450/500 | Batch 30/202 | Rec 0.000578 | Seg 0.314879 | Elapsed 0.6m | ETA 3.5m
Epoch 450/500 | Batch 40/202 | Rec 0.000615 | Seg 0.319414 | Elapsed 0.8m | ETA 3.3m
Epoch 450/500 | Batch 50/202 | Rec 0.000614 | Seg 0.315356 | Elapsed 1.0m | ETA 3.1m
Epoch 450/500 | Batch 60/202 | Rec 0.000609 | Seg 0.304803 | Elapsed 1.2m | ETA 2.9m
Epoch 450/500 | Batch 70/202 | Rec 0.000601 | Seg 0.295373 | Elapsed 1.4m | ETA 2.7m
Epoch 450/500 | Batch 80/202 | Rec 0.000598 | Seg 0.291668 | Elapsed 1.6m | ETA 2.5m
Epoch 450/500 | Batch 90/202 | Rec 0.000593 | Seg 0.294092 | Elapsed 1.8m | ETA 2.3m
Epoch 450/500 | Batch 100/202 | Rec 0.000595 | Seg 0.290277 | Elapsed 2.0m | ETA 2.1m
Epoch 450/500 | Batch 110/202 | Rec 0.000596 | Seg 0.288552 | Elapsed 2.3m | ETA 1.9m
Epoch 450/500 | Batch 120/202 | Rec 0.000592 | Seg 0.289962 | Elapsed 2.5m | ETA 1.7m
Epoch 450/500 | Batch 130/202 | Rec 0.000585 | Seg 0.286570 | Elapsed 2.7m | ETA 1.5m
Epoch 450/500 | Batch 140/202 | Rec 0.000577 | Seg 0.285565 | Elapsed 2.9m | ETA 1.3m
Epoch 450/500 | Batch 150/202 | Rec 0.000584 | Seg 0.287574 | Elapsed 3.1m | ETA 1.1m
Epoch 450/500 | Batch 160/202 | Rec 0.000574 | Seg 0.284440 | Elapsed 3.3m | ETA 0.9m
Epoch 450/500 | Batch 170/202 | Rec 0.000578 | Seg 0.286734 | Elapsed 3.5m | ETA 0.7m
Epoch 450/500 | Batch 180/202 | Rec 0.000577 | Seg 0.288617 | Elapsed 3.7m | ETA 0.5m
Epoch 450/500 | Batch 190/202 | Rec 0.000576 | Seg 0.286453 | Elapsed 3.9m | ETA 0.2m
Epoch 450/500 | Batch 200/202 | Rec 0.000571 | Seg 0.285439 | Elapsed 4.1m | ETA 0.0m
Epoch 450/500 | Batch 202/202 | Rec 0.000570 | Seg 0.285048 | Elapsed 4.1m | ETA 0.0m

2026-10-10 13:21:36,204 - INFO: Rec loss: 0.0005703196121871905
2026-10-10 13:21:36,204 - INFO: Seg loss: 0.2850476900613544
2026-10-10 13:21:36,204 - INFO: λ_rec: 1
2026-10-10 13:21:36,204 - INFO: λ_seg: 0.0001
2026-10-10 13:22:52,823 - INFO: -------------------Epoch: 450------------------------
2026-10-10 13:22:52,826 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.263751  0.975263  0.000124
2026-10-10 13:22:52,833 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995838  0.997865  0.997347  0.998483  0.996027
real potato   0.432337  0.603638  0.975249  0.437133  0.999313
fake potato   0.741969  0.851825  0.977748  0.754713  0.999809
real apple    0.711550  0.831418  0.792780  0.874126  0.998777
fake apple    0.627380  0.770983  0.977534  0.636558  0.998573
real orange   0.952974  0.975871  0.995185  0.957388  0.999938
fake orange   0.947578  0.973034  0.959056  0.987528  0.999844
real grape    0.836222  0.910757  0.963168  0.863846  0.999647
fake grape    0.898972  0.946748  0.931365  0.962752  0.999600
real lemon    0.547733  0.707741  0.564861  0.947546  0.999081
fake lemon    0.864652  0.927364  0.991867  0.870826  0.999712
real avocado  0.885504  0.939226  0.911351  0.968966  0.999884
fake avocado  0.818043  0.899866  0.999066  0.818669  0.999782
real pepper   0.788168  0.881487  0.822010  0.950359  0.999066
fake pepper   0.649647  0.787571  0.951332  0.671980  0.999136
real plant    0.872690  0.931968  0.960158  0.905480  0.998679
fake plant    0.828371  0.906080  0.905436  0.906825  0.999850
real banana   0.505401  0.671403  0.870430  0.546516  0.998798
fake banana   0.725392  0.840793  0.816406  0.866788  0.999396
real onion    0.628400  0.771751  0.695929  0.866239  0.999537
fake onion    0.938550  0.968251  0.992134  0.945586  0.999961
real unknown  0.778039  0.875116  0.813782  0.946565  0.999957
fake unknown  0.232904  0.377775  0.254529  0.732706  0.997967
total         0.748188  0.841240  0.874727  0.844242  0.999232
total(-bg)    0.736931  0.834121  0.869154  0.837232  0.999377
2026-10-10 13:22:53,285 - INFO: Epoch accounting: {'epoch': 450, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11199905, 45723, 49001, 142535, 119196, 83634, 67259, 133636, 201332, 91518, 72893, 52195, 41911, 256021, 136168, 165173, 26859, 83055, 63132, 84084, 57887, 6386, 58769], 'crops_with_class': [202, 25, 23, 31, 33, 24, 19, 22, 40, 38, 28, 19, 18, 62, 33, 24, 25, 24, 25, 33, 25, 7, 24], 'targeted_crops_by_class': [0, 6, 1, 7, 2, 6, 2, 3, 4, 5, 3, 4, 5, 9, 5, 4, 5, 4, 6, 3, 8, 2, 8], 'sampled_scene_counts': [1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 1, 2, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 2, 1, 3, 1, 0, 2, 0, 0, 0, 1, 0, 1, 0, 3, 1, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 1, 1, 1, 2, 1, 1, 2, 0, 1, 2, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 1, 1, 1, 2, 2, 0, 2, 3, 2, 1, 2, 2, 1, 0, 1, 3, 2, 1, 1, 3, 1, 1, 1, 2, 5, 1, 2, 2, 0, 2, 4, 2, 1, 0, 2, 3, 0, 1, 2, 2, 1, 1, 0, 2, 3, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 3, 2, 2, 1, 1, 1, 3, 1, 0, 3, 1, 0, 2, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1], 'learning_rate': 2.7888297686090466e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005703196121871905, 'train_segmentation_loss': 0.2850476900613544, 'val_foreground_miou_all22': 0.7369306968491479, 'val_psnr_ref1': 39.26375106811523, 'elapsed_seconds': 325.9072251319885, 'peak_cuda_allocated_gib': 7.510807037353516}

Stopped after epoch 450; scheduler horizon remains 500
Saved epoch: 450 | block target: 450 | Missing checkpoint files: []
Download: /kaggle/working/balanced410_to_epoch500_20261010_094143_epoch450.zip

/kaggle/working/balanced410_to_epoch500_20261010_094143_epoch450.zip

Epoch450 completed. Download the full backup before stopping the session.

In [8]:
continue_to(500)

Namespace(gpu_id='0', data_root='/kaggle/input/datasets/arnavnigamd/btp-data/public252/', mask_path='mask/mask512x512.mat', transpose_image=True, outf='/kaggle/working/', name='balanced410_to_epoch500_20261010_094143', method='CRSDUN', pretrained_model_path=None, input_setting='Y', input_mask='SSR', batch_size=1, max_epoch=500, learning_rate=0.0001, resume='/kaggle/working/balanced410_to_epoch500_20261010_094143/model/last.pt', workers=0, seed=3407, eval_split='val', stop_after_epoch=500, lambda_seg=0.0001, sampling_policy='balanced50_v1')
Dataset size (num. batches) 202 25

2026-10-10 13:23:51,996 - INFO: Resuming after epoch 450

Epoch 451/500 | Batch 10/202 | Rec 0.000522 | Seg 0.202445 | Elapsed 0.4m | ETA 8.0m
Epoch 451/500 | Batch 20/202 | Rec 0.000585 | Seg 0.280585 | Elapsed 0.6m | ETA 5.6m
Epoch 451/500 | Batch 30/202 | Rec 0.000554 | Seg 0.284008 | Elapsed 0.8m | ETA 4.7m
Epoch 451/500 | Batch 40/202 | Rec 0.000543 | Seg 0.267094 | Elapsed 1.0m | ETA 4.2m
Epoch 451/500 | Batch 50/202 | Rec 0.000529 | Seg 0.262732 | Elapsed 1.2m | ETA 3.8m
Epoch 451/500 | Batch 60/202 | Rec 0.000545 | Seg 0.262918 | Elapsed 1.5m | ETA 3.4m
Epoch 451/500 | Batch 70/202 | Rec 0.000553 | Seg 0.278076 | Elapsed 1.6m | ETA 3.1m
Epoch 451/500 | Batch 80/202 | Rec 0.000558 | Seg 0.284277 | Elapsed 1.8m | ETA 2.8m
Epoch 451/500 | Batch 90/202 | Rec 0.000549 | Seg 0.274290 | Elapsed 2.1m | ETA 2.6m
Epoch 451/500 | Batch 100/202 | Rec 0.000565 | Seg 0.277392 | Elapsed 2.3m | ETA 2.3m
Epoch 451/500 | Batch 110/202 | Rec 0.000560 | Seg 0.278834 | Elapsed 2.5m | ETA 2.1m
Epoch 451/500 | Batch 120/202 | Rec 0.000553 | Seg 0.274254 | Elapsed 2.7m | ETA 1.8m
Epoch 451/500 | Batch 130/202 | Rec 0.000560 | Seg 0.277354 | Elapsed 2.9m | ETA 1.6m
Epoch 451/500 | Batch 140/202 | Rec 0.000557 | Seg 0.275563 | Elapsed 3.1m | ETA 1.4m
Epoch 451/500 | Batch 150/202 | Rec 0.000560 | Seg 0.281073 | Elapsed 3.3m | ETA 1.1m
Epoch 451/500 | Batch 160/202 | Rec 0.000569 | Seg 0.280270 | Elapsed 3.5m | ETA 0.9m
Epoch 451/500 | Batch 170/202 | Rec 0.000574 | Seg 0.279397 | Elapsed 3.7m | ETA 0.7m
Epoch 451/500 | Batch 180/202 | Rec 0.000578 | Seg 0.278683 | Elapsed 3.9m | ETA 0.5m
Epoch 451/500 | Batch 190/202 | Rec 0.000571 | Seg 0.276946 | Elapsed 4.1m | ETA 0.3m
Epoch 451/500 | Batch 200/202 | Rec 0.000572 | Seg 0.272449 | Elapsed 4.3m | ETA 0.0m
Epoch 451/500 | Batch 202/202 | Rec 0.000579 | Seg 0.276905 | Elapsed 4.4m | ETA 0.0m

2026-10-10 13:28:13,828 - INFO: Rec loss: 0.0005791865879644427
2026-10-10 13:28:13,828 - INFO: Seg loss: 0.2769045507959505
2026-10-10 13:28:13,828 - INFO: λ_rec: 1
2026-10-10 13:28:13,828 - INFO: λ_seg: 0.0001
2026-10-10 13:29:29,411 - INFO: -------------------Epoch: 451------------------------
2026-10-10 13:29:29,416 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.131934  0.975208  0.000128
2026-10-10 13:29:29,422 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995839  0.997865  0.997627  0.998204  0.996030
real potato   0.529174  0.692059  0.982185  0.534302  0.999431
fake potato   0.698709  0.822586  0.970119  0.714076  0.999776
real apple    0.735458  0.847517  0.817737  0.879655  0.998908
fake apple    0.565001  0.721999  0.989586  0.568380  0.998348
real orange   0.903649  0.949336  0.993545  0.908986  0.999872
fake orange   0.930329  0.963857  0.946979  0.981452  0.999790
real grape    0.841307  0.913765  0.960603  0.871373  0.999657
fake grape    0.886973  0.940052  0.908472  0.974013  0.999541
real lemon    0.455353  0.625719  0.471110  0.931576  0.998690
fake lemon    0.865003  0.927566  0.993737  0.869744  0.999713
real avocado  0.859001  0.924103  0.886326  0.965353  0.999853
fake avocado  0.625701  0.769714  0.999593  0.625861  0.999552
real pepper   0.804263  0.891464  0.839206  0.950776  0.999154
fake pepper   0.683900  0.812232  0.946588  0.711350  0.999216
real plant    0.881995  0.937248  0.955355  0.919911  0.998769
fake plant    0.775221  0.873330  0.813430  0.942868  0.999782
real banana   0.375000  0.545409  0.781040  0.419055  0.998431
fake banana   0.706053  0.827653  0.790268  0.868862  0.999335
real onion    0.630251  0.773145  0.713510  0.843776  0.999553
fake onion    0.925669  0.961350  0.987506  0.936638  0.999953
real unknown  0.932252  0.964888  1.000000  0.932252  0.999989
fake unknown  0.202041  0.336128  0.217281  0.742303  0.997530
total         0.730789  0.826912  0.867905  0.830033  0.999168
total(-bg)    0.718741  0.819142  0.862008  0.822389  0.999311
2026-10-10 13:29:29,888 - INFO: Epoch accounting: {'epoch': 451, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11264825, 47554, 59169, 115880, 143617, 93975, 52316, 143813, 166168, 52884, 60212, 58916, 38076, 231865, 143443, 170196, 28882, 78038, 79011, 82663, 68049, 13451, 45269], 'crops_with_class': [202, 27, 29, 31, 34, 28, 18, 29, 31, 25, 21, 18, 12, 57, 33, 21, 21, 21, 35, 36, 32, 15, 20], 'targeted_crops_by_class': [0, 5, 7, 6, 8, 3, 4, 4, 4, 3, 3, 6, 3, 4, 2, 3, 4, 5, 5, 2, 9, 9, 2], 'sampled_scene_counts': [1, 0, 3, 0, 1, 0, 1, 2, 0, 0, 1, 1, 0, 0, 2, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 0, 0, 2, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 2, 1, 2, 1, 0, 0, 1, 0, 2, 1, 0, 0, 0, 1, 1, 1, 1, 3, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 2, 1, 2, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 1, 3, 0, 0, 0, 2, 1, 2, 2, 1, 1, 1, 1, 0, 3, 1, 2, 1, 1, 1, 3, 0, 0, 0, 1, 2, 3, 2, 1, 0, 1, 1, 2, 0, 0, 2, 1, 1, 1, 0, 2, 5, 2, 1, 2, 0, 2, 2, 0, 1, 0, 3, 1, 1, 0, 2, 0, 1, 0, 1, 1, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 0, 3, 2, 1, 2, 3, 2, 5, 0, 2, 1], 'learning_rate': 2.691056249779213e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005791865879644427, 'train_segmentation_loss': 0.2769045507959505, 'val_foreground_miou_all22': 0.7187409424409027, 'val_psnr_ref1': 39.13193389892578, 'elapsed_seconds': 337.88466906547546, 'peak_cuda_allocated_gib': 7.331333160400391}

Epoch 452/500 | Batch 10/202 | Rec 0.000518 | Seg 0.217482 | Elapsed 0.2m | ETA 3.9m
Epoch 452/500 | Batch 20/202 | Rec 0.000580 | Seg 0.245031 | Elapsed 0.4m | ETA 3.7m
Epoch 452/500 | Batch 30/202 | Rec 0.000543 | Seg 0.235222 | Elapsed 0.6m | ETA 3.5m
Epoch 452/500 | Batch 40/202 | Rec 0.000591 | Seg 0.252433 | Elapsed 0.8m | ETA 3.3m
Epoch 452/500 | Batch 50/202 | Rec 0.000576 | Seg 0.253414 | Elapsed 1.0m | ETA 3.1m
Epoch 452/500 | Batch 60/202 | Rec 0.000569 | Seg 0.257163 | Elapsed 1.2m | ETA 2.9m
Epoch 452/500 | Batch 70/202 | Rec 0.000573 | Seg 0.261283 | Elapsed 1.4m | ETA 2.7m
Epoch 452/500 | Batch 80/202 | Rec 0.000580 | Seg 0.258711 | Elapsed 1.7m | ETA 2.5m
Epoch 452/500 | Batch 90/202 | Rec 0.000584 | Seg 0.265006 | Elapsed 1.9m | ETA 2.3m
Epoch 452/500 | Batch 100/202 | Rec 0.000577 | Seg 0.261713 | Elapsed 2.1m | ETA 2.1m
Epoch 452/500 | Batch 110/202 | Rec 0.000580 | Seg 0.267307 | Elapsed 2.3m | ETA 1.9m
Epoch 452/500 | Batch 120/202 | Rec 0.000576 | Seg 0.268811 | Elapsed 2.5m | ETA 1.7m
Epoch 452/500 | Batch 130/202 | Rec 0.000572 | Seg 0.271427 | Elapsed 2.7m | ETA 1.5m
Epoch 452/500 | Batch 140/202 | Rec 0.000586 | Seg 0.273629 | Elapsed 2.9m | ETA 1.3m
Epoch 452/500 | Batch 150/202 | Rec 0.000575 | Seg 0.268726 | Elapsed 3.1m | ETA 1.1m
Epoch 452/500 | Batch 160/202 | Rec 0.000570 | Seg 0.267054 | Elapsed 3.3m | ETA 0.9m
Epoch 452/500 | Batch 170/202 | Rec 0.000568 | Seg 0.267106 | Elapsed 3.5m | ETA 0.7m
Epoch 452/500 | Batch 180/202 | Rec 0.000570 | Seg 0.266672 | Elapsed 3.7m | ETA 0.5m
Epoch 452/500 | Batch 190/202 | Rec 0.000570 | Seg 0.267398 | Elapsed 3.9m | ETA 0.2m
Epoch 452/500 | Batch 200/202 | Rec 0.000567 | Seg 0.267285 | Elapsed 4.1m | ETA 0.0m
Epoch 452/500 | Batch 202/202 | Rec 0.000567 | Seg 0.267105 | Elapsed 4.2m | ETA 0.0m

2026-10-10 13:33:39,496 - INFO: Rec loss: 0.0005665047132118494
2026-10-10 13:33:39,496 - INFO: Seg loss: 0.2671048445350463
2026-10-10 13:33:39,496 - INFO: λ_rec: 1
2026-10-10 13:33:39,496 - INFO: λ_seg: 0.0001
2026-10-10 13:34:58,028 - INFO: -------------------Epoch: 452------------------------
2026-10-10 13:34:58,032 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.042514  0.974975  0.00013
2026-10-10 13:34:58,038 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995780  0.997835  0.997368  0.998403  0.995972
real potato   0.915329  0.955743  0.937676  0.974624  0.999892
fake potato   0.966653  0.982994  0.982427  0.983661  0.999975
real apple    0.772257  0.871446  0.974152  0.788412  0.999198
fake apple    0.588504  0.740906  0.982963  0.594568  0.998430
real orange   0.943209  0.970725  0.994534  0.948124  0.999925
fake orange   0.949172  0.973873  0.967545  0.980386  0.999850
real grape    0.763549  0.865873  0.943626  0.800044  0.999483
fake grape    0.904292  0.949691  0.924938  0.975911  0.999618
real lemon    0.776554  0.874175  0.815089  0.942612  0.999681
fake lemon    0.808896  0.894304  0.999377  0.809304  0.999595
real avocado  0.954634  0.976741  0.989884  0.964039  0.999957
fake avocado  0.678098  0.808126  0.999624  0.678271  0.999615
real pepper   0.840404  0.913232  0.860724  0.972676  0.999324
fake pepper   0.739462  0.850170  0.950186  0.769285  0.999354
real plant    0.864558  0.927310  0.946572  0.908912  0.998576
fake plant    0.822929  0.902815  0.879476  0.927531  0.999841
real banana   0.738838  0.849757  0.899000  0.805718  0.999360
fake banana   0.673758  0.805034  0.755491  0.861646  0.999232
real onion    0.595846  0.746699  0.605545  0.973822  0.999403
fake onion    0.932176  0.964847  0.969253  0.960580  0.999956
real unknown  0.622423  0.767227  0.657143  0.921756  0.999911
fake unknown  0.217679  0.357492  0.241014  0.692141  0.997904
total         0.785435  0.867262  0.881461  0.879671  0.999307
total(-bg)    0.775874  0.861326  0.876193  0.874274  0.999458
2026-10-10 13:34:58,510 - INFO: Epoch accounting: {'epoch': 452, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11332104, 50312, 74950, 112589, 127844, 74804, 53475, 185348, 168469, 71774, 72205, 32191, 30634, 213198, 122872, 100177, 24480, 76061, 78622, 95916, 69318, 9653, 61276], 'crops_with_class': [202, 28, 35, 26, 32, 22, 19, 34, 34, 30, 29, 12, 11, 52, 36, 15, 22, 21, 32, 41, 28, 11, 24], 'targeted_crops_by_class': [0, 2, 8, 3, 5, 7, 0, 5, 3, 3, 5, 3, 2, 4, 7, 8, 2, 1, 5, 7, 4, 6, 7], 'sampled_scene_counts': [0, 1, 1, 1, 0, 1, 0, 0, 3, 1, 1, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 2, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 2, 2, 1, 0, 0, 1, 1, 2, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 3, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 3, 2, 0, 1, 2, 0, 1, 0, 1, 1, 1, 3, 0, 0, 1, 3, 1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 1, 2, 0, 2, 0, 1, 0, 1, 1, 4, 1, 3, 3, 4, 1, 1, 2, 3, 1, 2, 1, 1, 2, 1, 0, 0, 1, 3, 0, 2, 0, 1, 3, 1, 3, 0, 0, 2, 2, 2, 2, 3, 1, 2, 0, 2, 1, 4, 1, 2, 2, 2], 'learning_rate': 2.5951553418287106e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005665047132118494, 'train_segmentation_loss': 0.2671048445350463, 'val_foreground_miou_all22': 0.7758735067839306, 'val_psnr_ref1': 39.04251373291016, 'elapsed_seconds': 328.6155278682709, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 453/500 | Batch 10/202 | Rec 0.000780 | Seg 0.268907 | Elapsed 0.2m | ETA 4.0m
Epoch 453/500 | Batch 20/202 | Rec 0.000690 | Seg 0.271210 | Elapsed 0.4m | ETA 3.8m
Epoch 453/500 | Batch 30/202 | Rec 0.000625 | Seg 0.254094 | Elapsed 0.6m | ETA 3.6m
Epoch 453/500 | Batch 40/202 | Rec 0.000625 | Seg 0.261729 | Elapsed 0.8m | ETA 3.3m
Epoch 453/500 | Batch 50/202 | Rec 0.000614 | Seg 0.256457 | Elapsed 1.0m | ETA 3.1m
Epoch 453/500 | Batch 60/202 | Rec 0.000582 | Seg 0.256301 | Elapsed 1.2m | ETA 2.9m
Epoch 453/500 | Batch 70/202 | Rec 0.000583 | Seg 0.262512 | Elapsed 1.4m | ETA 2.7m
Epoch 453/500 | Batch 80/202 | Rec 0.000583 | Seg 0.264152 | Elapsed 1.7m | ETA 2.5m
Epoch 453/500 | Batch 90/202 | Rec 0.000586 | Seg 0.268879 | Elapsed 1.9m | ETA 2.3m
Epoch 453/500 | Batch 100/202 | Rec 0.000587 | Seg 0.266661 | Elapsed 2.1m | ETA 2.1m
Epoch 453/500 | Batch 110/202 | Rec 0.000580 | Seg 0.267473 | Elapsed 2.3m | ETA 1.9m
Epoch 453/500 | Batch 120/202 | Rec 0.000589 | Seg 0.276607 | Elapsed 2.5m | ETA 1.7m
Epoch 453/500 | Batch 130/202 | Rec 0.000590 | Seg 0.280010 | Elapsed 2.7m | ETA 1.5m
Epoch 453/500 | Batch 140/202 | Rec 0.000578 | Seg 0.275106 | Elapsed 2.9m | ETA 1.3m
Epoch 453/500 | Batch 150/202 | Rec 0.000579 | Seg 0.277530 | Elapsed 3.1m | ETA 1.1m
Epoch 453/500 | Batch 160/202 | Rec 0.000589 | Seg 0.280501 | Elapsed 3.3m | ETA 0.9m
Epoch 453/500 | Batch 170/202 | Rec 0.000589 | Seg 0.280483 | Elapsed 3.5m | ETA 0.7m
Epoch 453/500 | Batch 180/202 | Rec 0.000594 | Seg 0.281513 | Elapsed 3.7m | ETA 0.5m
Epoch 453/500 | Batch 190/202 | Rec 0.000588 | Seg 0.278783 | Elapsed 3.9m | ETA 0.2m
Epoch 453/500 | Batch 200/202 | Rec 0.000588 | Seg 0.281750 | Elapsed 4.1m | ETA 0.0m
Epoch 453/500 | Batch 202/202 | Rec 0.000585 | Seg 0.280597 | Elapsed 4.2m | ETA 0.0m

2026-10-10 13:39:08,668 - INFO: Rec loss: 0.0005854480766021591
2026-10-10 13:39:08,668 - INFO: Seg loss: 0.28059718258088767
2026-10-10 13:39:08,668 - INFO: λ_rec: 1
2026-10-10 13:39:08,669 - INFO: λ_seg: 0.0001
2026-10-10 13:40:30,779 - INFO: -------------------Epoch: 453------------------------
2026-10-10 13:40:30,783 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.067113  0.975076  0.000129
2026-10-10 13:40:30,790 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995732  0.997811  0.997259  0.998465  0.995926
real potato   0.636489  0.777823  0.974467  0.647284  0.999558
fake potato   0.702586  0.825268  0.972167  0.717009  0.999779
real apple    0.738101  0.849269  0.859374  0.839496  0.998972
fake apple    0.600839  0.750608  0.982289  0.607420  0.998476
real orange   0.947787  0.973144  0.995159  0.952177  0.999931
fake orange   0.945903  0.972149  0.966844  0.977614  0.999840
real grape    0.811450  0.895863  0.973587  0.829716  0.999597
fake grape    0.897937  0.946174  0.924211  0.969311  0.999592
real lemon    0.575080  0.730176  0.591019  0.955206  0.999171
fake lemon    0.863066  0.926451  0.993723  0.867797  0.999709
real avocado  0.887424  0.940305  0.919899  0.961741  0.999887
fake avocado  0.719403  0.836757  0.999646  0.719587  0.999664
real pepper   0.842307  0.914355  0.877305  0.954781  0.999346
fake pepper   0.758459  0.862591  0.955284  0.786377  0.999403
real plant    0.867946  0.929255  0.955063  0.904900  0.998623
fake plant    0.880134  0.936196  0.966333  0.907975  0.999902
real banana   0.532771  0.695126  0.869570  0.579044  0.998859
fake banana   0.711727  0.831539  0.799067  0.866871  0.999354
real onion    0.646184  0.785020  0.699116  0.895119  0.999557
fake onion    0.915547  0.955862  0.991426  0.922854  0.999946
real unknown  0.654897  0.791417  0.684540  0.937977  0.999921
fake unknown  0.210601  0.347893  0.226460  0.750453  0.997630
total         0.754016  0.846567  0.877122  0.849964  0.999245
total(-bg)    0.743029  0.839693  0.871661  0.843214  0.999396
2026-10-10 13:40:31,262 - INFO: Epoch accounting: {'epoch': 453, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11237565, 55751, 79474, 128454, 144839, 119722, 77641, 141253, 225229, 50833, 65005, 22860, 27683, 233996, 113086, 145109, 24930, 86149, 79206, 73134, 47208, 14719, 44426], 'crops_with_class': [202, 33, 33, 33, 38, 37, 28, 28, 39, 29, 26, 7, 10, 52, 32, 22, 24, 26, 31, 32, 23, 18, 19], 'targeted_crops_by_class': [0, 5, 5, 5, 4, 7, 5, 2, 4, 3, 7, 1, 1, 4, 5, 2, 8, 5, 6, 4, 4, 6, 2], 'sampled_scene_counts': [2, 1, 3, 0, 1, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 2, 1, 1, 1, 1, 1, 0, 0, 1, 2, 0, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 3, 1, 0, 2, 1, 0, 0, 1, 2, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 3, 1, 2, 0, 1, 1, 1, 1, 1, 3, 2, 0, 2, 1, 1, 2, 2, 1, 0, 0, 0, 1, 1, 1, 4, 4, 1, 2, 0, 3, 1, 1, 0, 1, 2, 1, 0, 1, 3, 4, 3, 0, 1, 1, 1, 3, 1, 1, 3, 3, 1, 2, 3, 3, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 3, 2, 0, 4, 0, 1, 0, 4, 1, 0, 0, 1, 1], 'learning_rate': 2.5011308307611784e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005854480766021591, 'train_segmentation_loss': 0.28059718258088767, 'val_foreground_miou_all22': 0.7430289610160842, 'val_psnr_ref1': 39.06711349487305, 'elapsed_seconds': 332.74390983581543, 'peak_cuda_allocated_gib': 7.515689849853516}

Epoch 454/500 | Batch 10/202 | Rec 0.000511 | Seg 0.235126 | Elapsed 0.2m | ETA 3.8m
Epoch 454/500 | Batch 20/202 | Rec 0.000519 | Seg 0.248150 | Elapsed 0.4m | ETA 3.7m
Epoch 454/500 | Batch 30/202 | Rec 0.000527 | Seg 0.271265 | Elapsed 0.6m | ETA 3.5m
Epoch 454/500 | Batch 40/202 | Rec 0.000538 | Seg 0.262000 | Elapsed 0.8m | ETA 3.3m
Epoch 454/500 | Batch 50/202 | Rec 0.000548 | Seg 0.264544 | Elapsed 1.0m | ETA 3.1m
Epoch 454/500 | Batch 60/202 | Rec 0.000525 | Seg 0.260542 | Elapsed 1.2m | ETA 2.9m
Epoch 454/500 | Batch 70/202 | Rec 0.000548 | Seg 0.272984 | Elapsed 1.4m | ETA 2.7m
Epoch 454/500 | Batch 80/202 | Rec 0.000536 | Seg 0.264744 | Elapsed 1.6m | ETA 2.5m
Epoch 454/500 | Batch 90/202 | Rec 0.000541 | Seg 0.266260 | Elapsed 1.8m | ETA 2.3m
Epoch 454/500 | Batch 100/202 | Rec 0.000534 | Seg 0.262097 | Elapsed 2.0m | ETA 2.1m
Epoch 454/500 | Batch 110/202 | Rec 0.000532 | Seg 0.264168 | Elapsed 2.2m | ETA 1.9m
Epoch 454/500 | Batch 120/202 | Rec 0.000537 | Seg 0.262083 | Elapsed 2.5m | ETA 1.7m
Epoch 454/500 | Batch 130/202 | Rec 0.000543 | Seg 0.261987 | Elapsed 2.7m | ETA 1.5m
Epoch 454/500 | Batch 140/202 | Rec 0.000560 | Seg 0.264588 | Elapsed 2.9m | ETA 1.3m
Epoch 454/500 | Batch 150/202 | Rec 0.000562 | Seg 0.266034 | Elapsed 3.1m | ETA 1.1m
Epoch 454/500 | Batch 160/202 | Rec 0.000560 | Seg 0.264887 | Elapsed 3.3m | ETA 0.9m
Epoch 454/500 | Batch 170/202 | Rec 0.000558 | Seg 0.265746 | Elapsed 3.5m | ETA 0.7m
Epoch 454/500 | Batch 180/202 | Rec 0.000555 | Seg 0.266623 | Elapsed 3.7m | ETA 0.5m
Epoch 454/500 | Batch 190/202 | Rec 0.000564 | Seg 0.265099 | Elapsed 3.9m | ETA 0.2m
Epoch 454/500 | Batch 200/202 | Rec 0.000565 | Seg 0.268519 | Elapsed 4.1m | ETA 0.0m
Epoch 454/500 | Batch 202/202 | Rec 0.000563 | Seg 0.267826 | Elapsed 4.2m | ETA 0.0m

2026-10-10 13:44:41,169 - INFO: Rec loss: 0.0005626435487272937
2026-10-10 13:44:41,169 - INFO: Seg loss: 0.26782567700426474
2026-10-10 13:44:41,169 - INFO: λ_rec: 1
2026-10-10 13:44:41,169 - INFO: λ_seg: 0.0001
2026-10-10 13:45:59,120 - INFO: -------------------Epoch: 454------------------------
2026-10-10 13:45:59,124 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  39.15022  0.975066  0.000127
2026-10-10 13:45:59,132 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995706  0.997798  0.996997  0.998701  0.995900
real potato   0.355731  0.524743  0.999642  0.355777  0.999229
fake potato   0.663761  0.797856  0.986428  0.669878  0.999753
real apple    0.698925  0.822735  0.762025  0.894073  0.998671
fake apple    0.641925  0.781870  0.971381  0.654300  0.998622
real orange   0.910014  0.952837  0.995960  0.913386  0.999881
fake orange   0.933520  0.965567  0.952645  0.978947  0.999800
real grape    0.846656  0.916912  0.945432  0.890156  0.999663
fake grape    0.883517  0.938107  0.907605  0.970837  0.999527
real lemon    0.495421  0.662538  0.513342  0.934173  0.998882
fake lemon    0.862133  0.925913  0.989019  0.870465  0.999706
real avocado  0.779614  0.876111  0.800027  0.968309  0.999746
fake avocado  0.772299  0.871473  0.999011  0.772890  0.999727
real pepper   0.795294  0.885926  0.847872  0.927666  0.999127
fake pepper   0.616443  0.762667  0.937792  0.642725  0.999047
real plant    0.868375  0.929501  0.959112  0.901757  0.998633
fake plant    0.723671  0.839636  0.818878  0.861580  0.999738
real banana   0.417559  0.589080  0.892951  0.439563  0.998622
fake banana   0.733309  0.846088  0.855206  0.837259  0.999440
real onion    0.605477  0.754214  0.739808  0.769296  0.999547
fake onion    0.922929  0.959870  0.992256  0.929625  0.999951
real unknown  0.910985  0.953369  0.991752  0.917939  0.999986
fake unknown  0.235024  0.380558  0.260881  0.703368  0.998071
total         0.724708  0.823277  0.874610  0.817507  0.999186
total(-bg)    0.712390  0.815344  0.869047  0.809271  0.999335
2026-10-10 13:45:59,600 - INFO: Epoch accounting: {'epoch': 454, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11342855, 54985, 51956, 112902, 147531, 49710, 51844, 133502, 197624, 82944, 62275, 65996, 53773, 207122, 122204, 138389, 31436, 78065, 70265, 67148, 58097, 8569, 49080], 'crops_with_class': [202, 30, 26, 34, 37, 16, 20, 30, 33, 32, 29, 22, 23, 52, 35, 18, 23, 23, 31, 34, 27, 9, 20], 'targeted_crops_by_class': [0, 3, 4, 9, 5, 1, 4, 4, 1, 5, 3, 11, 7, 3, 4, 5, 5, 7, 4, 2, 6, 1, 3], 'sampled_scene_counts': [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 2, 1, 1, 1, 1, 2, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 2, 1, 4, 0, 1, 0, 1, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 0, 0, 0, 3, 0, 1, 2, 0, 1, 0, 4, 2, 3, 1, 2, 1, 1, 0, 1, 1, 0, 1, 3, 1, 1, 2, 1, 2, 1, 1, 4, 0, 0, 2, 0, 2, 1, 2, 0, 2, 3, 1, 0, 2, 0, 3, 3, 2, 2, 1, 1, 1, 0, 1, 1, 1, 2, 0, 3, 2, 3, 0, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 2, 1, 2, 1, 2, 3, 0, 1, 2, 1, 0, 1, 1, 4, 2, 1], 'learning_rate': 2.4089864285033223e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005626435487272937, 'train_segmentation_loss': 0.26782567700426474, 'val_foreground_miou_all22': 0.7123900001994286, 'val_psnr_ref1': 39.15022018432617, 'elapsed_seconds': 328.33040165901184, 'peak_cuda_allocated_gib': 7.510318756103516}

Epoch 455/500 | Batch 10/202 | Rec 0.000583 | Seg 0.305607 | Elapsed 0.2m | ETA 4.1m
Epoch 455/500 | Batch 20/202 | Rec 0.000528 | Seg 0.266540 | Elapsed 0.4m | ETA 3.8m
Epoch 455/500 | Batch 30/202 | Rec 0.000560 | Seg 0.276434 | Elapsed 0.6m | ETA 3.6m
Epoch 455/500 | Batch 40/202 | Rec 0.000561 | Seg 0.278504 | Elapsed 0.8m | ETA 3.3m
Epoch 455/500 | Batch 50/202 | Rec 0.000588 | Seg 0.282691 | Elapsed 1.0m | ETA 3.1m
Epoch 455/500 | Batch 60/202 | Rec 0.000566 | Seg 0.276934 | Elapsed 1.2m | ETA 2.9m
Epoch 455/500 | Batch 70/202 | Rec 0.000556 | Seg 0.273535 | Elapsed 1.4m | ETA 2.7m
Epoch 455/500 | Batch 80/202 | Rec 0.000574 | Seg 0.274084 | Elapsed 1.6m | ETA 2.5m
Epoch 455/500 | Batch 90/202 | Rec 0.000575 | Seg 0.273393 | Elapsed 1.9m | ETA 2.3m
Epoch 455/500 | Batch 100/202 | Rec 0.000565 | Seg 0.268989 | Elapsed 2.1m | ETA 2.1m
Epoch 455/500 | Batch 110/202 | Rec 0.000567 | Seg 0.271782 | Elapsed 2.3m | ETA 1.9m
Epoch 455/500 | Batch 120/202 | Rec 0.000575 | Seg 0.275083 | Elapsed 2.5m | ETA 1.7m
Epoch 455/500 | Batch 130/202 | Rec 0.000575 | Seg 0.275708 | Elapsed 2.7m | ETA 1.5m
Epoch 455/500 | Batch 140/202 | Rec 0.000570 | Seg 0.274802 | Elapsed 2.9m | ETA 1.3m
Epoch 455/500 | Batch 150/202 | Rec 0.000569 | Seg 0.272833 | Elapsed 3.1m | ETA 1.1m
Epoch 455/500 | Batch 160/202 | Rec 0.000563 | Seg 0.271417 | Elapsed 3.3m | ETA 0.9m
Epoch 455/500 | Batch 170/202 | Rec 0.000565 | Seg 0.270396 | Elapsed 3.5m | ETA 0.7m
Epoch 455/500 | Batch 180/202 | Rec 0.000571 | Seg 0.271540 | Elapsed 3.7m | ETA 0.5m
Epoch 455/500 | Batch 190/202 | Rec 0.000569 | Seg 0.271476 | Elapsed 3.9m | ETA 0.2m
Epoch 455/500 | Batch 200/202 | Rec 0.000568 | Seg 0.274012 | Elapsed 4.1m | ETA 0.0m
Epoch 455/500 | Batch 202/202 | Rec 0.000568 | Seg 0.273251 | Elapsed 4.2m | ETA 0.0m

2026-10-10 13:50:09,236 - INFO: Rec loss: 0.0005679675301543833
2026-10-10 13:50:09,236 - INFO: Seg loss: 0.27325076482599914
2026-10-10 13:50:09,236 - INFO: λ_rec: 1
2026-10-10 13:50:09,236 - INFO: λ_seg: 0.0001
2026-10-10 13:51:26,460 - INFO: -------------------Epoch: 455------------------------
2026-10-10 13:51:26,464 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.086608  0.974926  0.000129
2026-10-10 13:51:26,470 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995679  0.997785  0.997048  0.998623  0.995874
real potato   0.845081  0.915987  0.858753  0.981510  0.999785
fake potato   0.951146  0.974911  0.959440  0.990993  0.999963
real apple    0.697291  0.821603  0.982760  0.705927  0.998943
fake apple    0.546727  0.706901  0.990962  0.549467  0.998280
real orange   0.923911  0.960401  0.995281  0.927976  0.999899
fake orange   0.935619  0.966689  0.954730  0.979053  0.999807
real grape    0.763947  0.866129  0.920823  0.817657  0.999473
fake grape    0.908220  0.951853  0.941532  0.962505  0.999640
real lemon    0.812037  0.896220  0.925460  0.868865  0.999764
fake lemon    0.768485  0.869039  0.995161  0.771367  0.999508
real avocado  0.962137  0.980653  0.998130  0.963875  0.999965
fake avocado  0.626163  0.770064  0.999796  0.626243  0.999553
real pepper   0.819733  0.900888  0.837878  0.974262  0.999216
fake pepper   0.707268  0.828489  0.929254  0.747519  0.999263
real plant    0.860039  0.924704  0.956520  0.895030  0.998543
fake plant    0.728888  0.843137  0.772372  0.928298  0.999725
real banana   0.803871  0.891223  0.894136  0.888429  0.999513
fake banana   0.665896  0.799395  0.746742  0.860153  0.999206
real onion    0.580292  0.734364  0.589178  0.974666  0.999363
fake onion    0.907574  0.951498  0.930437  0.973640  0.999937
real unknown  0.525563  0.688962  0.553561  0.912214  0.999868
fake unknown  0.196963  0.329065  0.223388  0.624774  0.997854
total         0.762284  0.850868  0.867537  0.866219  0.999258
total(-bg)    0.751675  0.844190  0.861650  0.860201  0.999412
2026-10-10 13:51:26,939 - INFO: Epoch accounting: {'epoch': 455, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11278434, 44637, 55364, 113723, 142217, 79545, 72532, 116353, 151547, 80046, 80352, 33467, 35476, 273392, 145703, 150660, 17257, 70727, 100660, 92413, 56977, 9275, 37515], 'crops_with_class': [202, 27, 29, 34, 36, 27, 25, 24, 31, 37, 33, 12, 12, 60, 35, 19, 18, 23, 41, 41, 26, 11, 20], 'targeted_crops_by_class': [0, 3, 2, 7, 4, 4, 1, 2, 5, 8, 5, 2, 4, 8, 12, 4, 5, 5, 10, 3, 4, 5, 3], 'sampled_scene_counts': [0, 1, 0, 0, 0, 1, 0, 1, 1, 2, 0, 1, 0, 0, 0, 1, 0, 2, 0, 2, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 2, 0, 1, 1, 2, 0, 1, 0, 0, 2, 1, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 2, 2, 0, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 1, 1, 0, 0, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 0, 2, 2, 1, 1, 2, 1, 1, 1, 4, 2, 1, 2, 1, 3, 1, 1, 0, 2, 4, 1, 3, 1, 1, 2, 1, 2, 2, 1, 0, 2, 2, 2, 2, 0, 2, 1, 0, 2, 1, 3, 3, 2, 2, 1, 0, 0, 0, 3, 3, 1, 4, 2, 1, 2, 2, 0, 0, 2, 0, 1, 1, 0, 0, 1, 4], 'learning_rate': 2.318725772758376e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005679675301543833, 'train_segmentation_loss': 0.27325076482599914, 'val_foreground_miou_all22': 0.7516750452380543, 'val_psnr_ref1': 39.0866081237793, 'elapsed_seconds': 327.331707239151, 'peak_cuda_allocated_gib': 7.512638092041016}

Epoch 456/500 | Batch 10/202 | Rec 0.000523 | Seg 0.254235 | Elapsed 0.2m | ETA 4.0m
Epoch 456/500 | Batch 20/202 | Rec 0.000533 | Seg 0.238737 | Elapsed 0.4m | ETA 3.8m
Epoch 456/500 | Batch 30/202 | Rec 0.000536 | Seg 0.251093 | Elapsed 0.6m | ETA 3.6m
Epoch 456/500 | Batch 40/202 | Rec 0.000537 | Seg 0.251991 | Elapsed 0.8m | ETA 3.4m
Epoch 456/500 | Batch 50/202 | Rec 0.000542 | Seg 0.259310 | Elapsed 1.0m | ETA 3.2m
Epoch 456/500 | Batch 60/202 | Rec 0.000533 | Seg 0.264113 | Elapsed 1.2m | ETA 3.0m
Epoch 456/500 | Batch 70/202 | Rec 0.000536 | Seg 0.268932 | Elapsed 1.5m | ETA 2.7m
Epoch 456/500 | Batch 80/202 | Rec 0.000540 | Seg 0.270270 | Elapsed 1.7m | ETA 2.5m
Epoch 456/500 | Batch 90/202 | Rec 0.000544 | Seg 0.268723 | Elapsed 1.9m | ETA 2.3m
Epoch 456/500 | Batch 100/202 | Rec 0.000545 | Seg 0.269042 | Elapsed 2.1m | ETA 2.1m
Epoch 456/500 | Batch 110/202 | Rec 0.000552 | Seg 0.273160 | Elapsed 2.3m | ETA 1.9m
Epoch 456/500 | Batch 120/202 | Rec 0.000554 | Seg 0.276429 | Elapsed 2.5m | ETA 1.7m
Epoch 456/500 | Batch 130/202 | Rec 0.000552 | Seg 0.276504 | Elapsed 2.7m | ETA 1.5m
Epoch 456/500 | Batch 140/202 | Rec 0.000549 | Seg 0.275007 | Elapsed 2.9m | ETA 1.3m
Epoch 456/500 | Batch 150/202 | Rec 0.000549 | Seg 0.275922 | Elapsed 3.1m | ETA 1.1m
Epoch 456/500 | Batch 160/202 | Rec 0.000557 | Seg 0.277534 | Elapsed 3.3m | ETA 0.9m
Epoch 456/500 | Batch 170/202 | Rec 0.000555 | Seg 0.276008 | Elapsed 3.5m | ETA 0.7m
Epoch 456/500 | Batch 180/202 | Rec 0.000558 | Seg 0.279838 | Elapsed 3.7m | ETA 0.5m
Epoch 456/500 | Batch 190/202 | Rec 0.000568 | Seg 0.282468 | Elapsed 3.9m | ETA 0.2m
Epoch 456/500 | Batch 200/202 | Rec 0.000566 | Seg 0.279229 | Elapsed 4.1m | ETA 0.0m
Epoch 456/500 | Batch 202/202 | Rec 0.000566 | Seg 0.279460 | Elapsed 4.2m | ETA 0.0m

2026-10-10 13:55:37,008 - INFO: Rec loss: 0.000566087342455227
2026-10-10 13:55:37,009 - INFO: Seg loss: 0.2794600314285495
2026-10-10 13:55:37,009 - INFO: λ_rec: 1
2026-10-10 13:55:37,009 - INFO: λ_seg: 0.0001
2026-10-10 13:56:56,543 - INFO: -------------------Epoch: 456------------------------
2026-10-10 13:56:56,547 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.097626  0.975113  0.000129
2026-10-10 13:56:56,553 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995744  0.997818  0.997116  0.998621  0.995937
real potato   0.437643  0.608791  0.986290  0.440321  0.999323
fake potato   0.689363  0.816073  0.982886  0.697738  0.999771
real apple    0.700638  0.823921  0.783382  0.868996  0.998719
fake apple    0.613380  0.760319  0.986907  0.618413  0.998528
real orange   0.886054  0.939535  0.996624  0.888722  0.999849
fake orange   0.923030  0.959925  0.944453  0.976015  0.999767
real grape    0.814975  0.898006  0.928583  0.869473  0.999588
fake grape    0.895248  0.944679  0.923799  0.966630  0.999582
real lemon    0.539650  0.700957  0.554581  0.952480  0.999045
fake lemon    0.854073  0.921244  0.988269  0.862820  0.999688
real avocado  0.859508  0.924397  0.888536  0.963383  0.999854
fake avocado  0.796738  0.886822  0.999201  0.797246  0.999757
real pepper   0.813389  0.897043  0.848284  0.951860  0.999201
fake pepper   0.670002  0.802348  0.934479  0.703028  0.999175
real plant    0.869579  0.930190  0.961361  0.901071  0.998648
fake plant    0.771020  0.870657  0.852628  0.889571  0.999790
real banana   0.525663  0.689047  0.885407  0.564036  0.998856
fake banana   0.738540  0.849559  0.833866  0.865959  0.999436
real onion    0.606276  0.754834  0.734387  0.776558  0.999544
fake onion    0.937830  0.967868  0.992128  0.944861  0.999960
real unknown  0.914393  0.955233  0.984802  0.927481  0.999986
fake unknown  0.217710  0.357534  0.242125  0.683448  0.997931
total         0.742193  0.837252  0.879569  0.830814  0.999215
total(-bg)    0.730668  0.829954  0.874226  0.823187  0.999364
2026-10-10 13:56:57,029 - INFO: Epoch accounting: {'epoch': 456, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11210156, 49430, 54959, 122361, 115284, 77546, 85128, 145206, 247740, 78652, 75949, 48231, 34306, 264920, 164913, 113753, 31463, 64441, 59831, 77161, 54233, 10547, 52062], 'crops_with_class': [202, 31, 26, 35, 33, 22, 29, 29, 41, 30, 30, 18, 15, 62, 41, 21, 25, 18, 31, 34, 25, 11, 24], 'targeted_crops_by_class': [0, 1, 0, 5, 6, 2, 4, 5, 6, 3, 2, 5, 5, 8, 3, 4, 5, 3, 6, 10, 6, 3, 7], 'sampled_scene_counts': [0, 0, 0, 0, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 3, 2, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 4, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 2, 1, 3, 2, 4, 1, 2, 1, 1, 3, 1, 0, 1, 2, 1, 2, 1, 0, 2, 2, 0, 3, 1, 0, 2, 3, 2, 2, 1, 1, 0, 2, 1, 0, 3, 0, 3, 0, 1, 2, 3, 4, 5, 1, 1, 0, 0, 1, 3, 2, 3, 2, 1, 1, 3, 1, 2, 0, 2, 3, 2, 1, 1, 0, 1, 0, 0, 2, 0, 1, 4, 2, 2, 0, 1, 0, 2, 1, 0, 1, 2, 1], 'learning_rate': 2.2303524268624607e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000566087342455227, 'train_segmentation_loss': 0.2794600314285495, 'val_foreground_miou_all22': 0.7306682020859754, 'val_psnr_ref1': 39.09762588500976, 'elapsed_seconds': 330.08271765708923, 'peak_cuda_allocated_gib': 7.505870819091797}

Epoch 457/500 | Batch 10/202 | Rec 0.000557 | Seg 0.303465 | Elapsed 0.2m | ETA 3.9m
Epoch 457/500 | Batch 20/202 | Rec 0.000518 | Seg 0.271611 | Elapsed 0.4m | ETA 3.8m
Epoch 457/500 | Batch 30/202 | Rec 0.000529 | Seg 0.275909 | Elapsed 0.6m | ETA 3.6m
Epoch 457/500 | Batch 40/202 | Rec 0.000589 | Seg 0.267210 | Elapsed 0.8m | ETA 3.4m
Epoch 457/500 | Batch 50/202 | Rec 0.000595 | Seg 0.293865 | Elapsed 1.0m | ETA 3.1m
Epoch 457/500 | Batch 60/202 | Rec 0.000590 | Seg 0.283793 | Elapsed 1.2m | ETA 2.9m
Epoch 457/500 | Batch 70/202 | Rec 0.000624 | Seg 0.286639 | Elapsed 1.4m | ETA 2.7m
Epoch 457/500 | Batch 80/202 | Rec 0.000623 | Seg 0.282897 | Elapsed 1.6m | ETA 2.5m
Epoch 457/500 | Batch 90/202 | Rec 0.000613 | Seg 0.281976 | Elapsed 1.8m | ETA 2.3m
Epoch 457/500 | Batch 100/202 | Rec 0.000617 | Seg 0.284182 | Elapsed 2.1m | ETA 2.1m
Epoch 457/500 | Batch 110/202 | Rec 0.000617 | Seg 0.284503 | Elapsed 2.3m | ETA 1.9m
Epoch 457/500 | Batch 120/202 | Rec 0.000616 | Seg 0.283640 | Elapsed 2.5m | ETA 1.7m
Epoch 457/500 | Batch 130/202 | Rec 0.000610 | Seg 0.282587 | Elapsed 2.7m | ETA 1.5m
Epoch 457/500 | Batch 140/202 | Rec 0.000610 | Seg 0.282447 | Elapsed 2.9m | ETA 1.3m
Epoch 457/500 | Batch 150/202 | Rec 0.000606 | Seg 0.283911 | Elapsed 3.1m | ETA 1.1m
Epoch 457/500 | Batch 160/202 | Rec 0.000604 | Seg 0.285558 | Elapsed 3.3m | ETA 0.9m
Epoch 457/500 | Batch 170/202 | Rec 0.000602 | Seg 0.283874 | Elapsed 3.5m | ETA 0.7m
Epoch 457/500 | Batch 180/202 | Rec 0.000606 | Seg 0.288878 | Elapsed 3.7m | ETA 0.5m
Epoch 457/500 | Batch 190/202 | Rec 0.000602 | Seg 0.286285 | Elapsed 3.9m | ETA 0.2m
Epoch 457/500 | Batch 200/202 | Rec 0.000598 | Seg 0.283011 | Elapsed 4.1m | ETA 0.0m
Epoch 457/500 | Batch 202/202 | Rec 0.000599 | Seg 0.282887 | Elapsed 4.2m | ETA 0.0m

2026-10-10 14:01:07,441 - INFO: Rec loss: 0.0005985173431489073
2026-10-10 14:01:07,442 - INFO: Seg loss: 0.28288652923068786
2026-10-10 14:01:07,442 - INFO: λ_rec: 1
2026-10-10 14:01:07,442 - INFO: λ_seg: 0.0001
2026-10-10 14:02:24,546 - INFO: -------------------Epoch: 457------------------------
2026-10-10 14:02:24,549 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.988845  0.974945  0.000132
2026-10-10 14:02:24,555 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995520  0.997705  0.996859  0.998653  0.995721
real potato   0.575041  0.730145  0.968994  0.585820  0.999482
fake potato   0.709684  0.830144  0.980319  0.719941  0.999785
real apple    0.686168  0.813829  0.838643  0.790535  0.998753
fake apple    0.592483  0.744053  0.984110  0.598206  0.998447
real orange   0.928101  0.962660  0.998135  0.929713  0.999905
fake orange   0.937937  0.967925  0.962971  0.973031  0.999816
real grape    0.816689  0.899046  0.958161  0.846890  0.999603
fake grape    0.891287  0.942469  0.923384  0.962463  0.999566
real lemon    0.592672  0.744200  0.636062  0.896780  0.999276
fake lemon    0.834364  0.909654  0.957885  0.866138  0.999636
real avocado  0.945422  0.971896  0.982712  0.961412  0.999948
fake avocado  0.672447  0.804099  0.999810  0.672533  0.999608
real pepper   0.846477  0.916806  0.872265  0.966252  0.999359
fake pepper   0.745320  0.854029  0.940018  0.782536  0.999363
real plant    0.860185  0.924788  0.963377  0.889263  0.998554
fake plant    0.712734  0.832227  0.909339  0.767255  0.999754
real banana   0.608100  0.756247  0.891573  0.656662  0.999049
fake banana   0.702544  0.825237  0.782712  0.872760  0.999320
real onion    0.642074  0.781979  0.685718  0.909813  0.999542
fake onion    0.881702  0.937083  0.993498  0.886820  0.999925
real unknown  0.540867  0.701982  0.559909  0.940840  0.999872
fake unknown  0.176318  0.299744  0.196719  0.629663  0.997522
total         0.734528  0.832519  0.868834  0.830608  0.999209
total(-bg)    0.722664  0.825011  0.863014  0.822969  0.999367
2026-10-10 14:02:25,019 - INFO: Epoch accounting: {'epoch': 457, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11200000, 56141, 57106, 123063, 145657, 78490, 70262, 148560, 241850, 45694, 60810, 41419, 38592, 248071, 155090, 128913, 31703, 89091, 67385, 88263, 59604, 12386, 50122], 'crops_with_class': [202, 34, 26, 33, 37, 26, 24, 30, 40, 21, 23, 16, 13, 69, 36, 19, 28, 25, 31, 40, 26, 14, 25], 'targeted_crops_by_class': [0, 6, 3, 4, 4, 1, 4, 6, 6, 1, 7, 2, 7, 6, 3, 4, 5, 6, 3, 4, 4, 8, 4], 'sampled_scene_counts': [0, 0, 0, 1, 0, 1, 2, 0, 3, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 1, 1, 0, 0, 2, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2, 2, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 2, 0, 2, 1, 2, 3, 1, 1, 1, 1, 1, 3, 1, 1, 2, 0, 2, 3, 0, 2, 3, 4, 1, 1, 1, 4, 0, 3, 1, 1, 2, 0, 3, 0, 1, 2, 2, 2, 1, 2, 3, 4, 4, 1, 0, 2, 5, 2, 0, 1, 3, 0, 1, 3, 1, 2, 2, 3, 0, 0, 1, 1, 1, 1, 1, 0, 3, 1, 1, 2, 1, 1, 1, 1, 1, 0, 1, 3, 0, 2, 1, 1, 1], 'learning_rate': 2.143869879643966e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005985173431489073, 'train_segmentation_loss': 0.28288652923068786, 'val_foreground_miou_all22': 0.7226643255808253, 'val_psnr_ref1': 38.988844604492186, 'elapsed_seconds': 327.9820737838745, 'peak_cuda_allocated_gib': 7.509342193603516}

Epoch 458/500 | Batch 10/202 | Rec 0.000573 | Seg 0.293633 | Elapsed 0.2m | ETA 3.9m
Epoch 458/500 | Batch 20/202 | Rec 0.000525 | Seg 0.257366 | Elapsed 0.4m | ETA 3.7m
Epoch 458/500 | Batch 30/202 | Rec 0.000545 | Seg 0.264973 | Elapsed 0.6m | ETA 3.5m
Epoch 458/500 | Batch 40/202 | Rec 0.000552 | Seg 0.269073 | Elapsed 0.8m | ETA 3.3m
Epoch 458/500 | Batch 50/202 | Rec 0.000542 | Seg 0.265439 | Elapsed 1.0m | ETA 3.1m
Epoch 458/500 | Batch 60/202 | Rec 0.000550 | Seg 0.279109 | Elapsed 1.2m | ETA 2.9m
Epoch 458/500 | Batch 70/202 | Rec 0.000547 | Seg 0.276295 | Elapsed 1.4m | ETA 2.7m
Epoch 458/500 | Batch 80/202 | Rec 0.000532 | Seg 0.272603 | Elapsed 1.6m | ETA 2.5m
Epoch 458/500 | Batch 90/202 | Rec 0.000536 | Seg 0.271385 | Elapsed 1.8m | ETA 2.3m
Epoch 458/500 | Batch 100/202 | Rec 0.000545 | Seg 0.270251 | Elapsed 2.0m | ETA 2.1m
Epoch 458/500 | Batch 110/202 | Rec 0.000546 | Seg 0.271127 | Elapsed 2.3m | ETA 1.9m
Epoch 458/500 | Batch 120/202 | Rec 0.000544 | Seg 0.273565 | Elapsed 2.4m | ETA 1.7m
Epoch 458/500 | Batch 130/202 | Rec 0.000542 | Seg 0.271547 | Elapsed 2.7m | ETA 1.5m
Epoch 458/500 | Batch 140/202 | Rec 0.000546 | Seg 0.276364 | Elapsed 2.9m | ETA 1.3m
Epoch 458/500 | Batch 150/202 | Rec 0.000544 | Seg 0.273914 | Elapsed 3.1m | ETA 1.1m
Epoch 458/500 | Batch 160/202 | Rec 0.000542 | Seg 0.273348 | Elapsed 3.3m | ETA 0.9m
Epoch 458/500 | Batch 170/202 | Rec 0.000542 | Seg 0.270467 | Elapsed 3.5m | ETA 0.7m
Epoch 458/500 | Batch 180/202 | Rec 0.000541 | Seg 0.269382 | Elapsed 3.7m | ETA 0.5m
Epoch 458/500 | Batch 190/202 | Rec 0.000541 | Seg 0.268952 | Elapsed 3.9m | ETA 0.2m
Epoch 458/500 | Batch 200/202 | Rec 0.000539 | Seg 0.269650 | Elapsed 4.1m | ETA 0.0m
Epoch 458/500 | Batch 202/202 | Rec 0.000540 | Seg 0.270980 | Elapsed 4.2m | ETA 0.0m

2026-10-10 14:06:34,325 - INFO: Rec loss: 0.000539703941546694
2026-10-10 14:06:34,325 - INFO: Seg loss: 0.27098023441463415
2026-10-10 14:06:34,325 - INFO: λ_rec: 1
2026-10-10 14:06:34,325 - INFO: λ_seg: 0.0001
2026-10-10 14:07:54,465 - INFO: -------------------Epoch: 458------------------------
2026-10-10 14:07:54,469 - INFO:
Validation stats:
       PSNR     SSIM       MSE
0  39.10496  0.97507  0.000129
2026-10-10 14:07:54,475 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995700  0.997795  0.997066  0.998626  0.995894
real potato   0.461286  0.631299  0.976508  0.466463  0.999348
fake potato   0.732438  0.845508  0.981722  0.742564  0.999802
real apple    0.721267  0.838015  0.802143  0.877355  0.998830
fake apple    0.602930  0.752238  0.984381  0.608754  0.998486
real orange   0.933019  0.965299  0.993505  0.938745  0.999911
fake orange   0.942894  0.970558  0.961895  0.979480  0.999830
real grape    0.818977  0.900431  0.934796  0.868596  0.999599
fake grape    0.895334  0.944727  0.920524  0.970342  0.999580
real lemon    0.686107  0.813787  0.717900  0.939366  0.999495
fake lemon    0.857982  0.923514  0.992458  0.863613  0.999698
real avocado  0.825386  0.904291  0.849819  0.966338  0.999810
fake avocado  0.714814  0.833644  0.999643  0.714996  0.999659
real pepper   0.792747  0.884344  0.834889  0.940138  0.999101
fake pepper   0.621476  0.766507  0.935856  0.649126  0.999058
real plant    0.865967  0.928120  0.957759  0.900354  0.998606
fake plant    0.725225  0.840681  0.792565  0.895130  0.999730
real banana   0.682689  0.811377  0.911600  0.731088  0.999236
fake banana   0.739768  0.850372  0.843380  0.857581  0.999445
real onion    0.647853  0.786250  0.730713  0.851039  0.999582
fake onion    0.933445  0.965527  0.989343  0.942926  0.999958
real unknown  0.897412  0.945883  0.966169  0.926527  0.999983
fake unknown  0.220927  0.361862  0.243604  0.703549  0.997910
total         0.752854  0.846175  0.883402  0.840552  0.999241
total(-bg)    0.741816  0.839283  0.878235  0.833367  0.999394
2026-10-10 14:07:54,933 - INFO: Epoch accounting: {'epoch': 458, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11284294, 67193, 43904, 104839, 117857, 104187, 99774, 182325, 191565, 76480, 65825, 36343, 43645, 237313, 132006, 89303, 27146, 91101, 64628, 69908, 54161, 11552, 42923], 'crops_with_class': [202, 32, 25, 31, 31, 30, 31, 31, 35, 40, 27, 15, 18, 58, 35, 14, 25, 27, 29, 34, 23, 12, 21], 'targeted_crops_by_class': [0, 6, 3, 2, 0, 8, 7, 2, 5, 7, 3, 5, 6, 2, 7, 5, 5, 5, 4, 3, 6, 7, 6], 'sampled_scene_counts': [0, 1, 1, 2, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 3, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 3, 0, 1, 1, 1, 0, 1, 1, 1, 3, 1, 0, 1, 2, 0, 0, 0, 0, 2, 0, 1, 0, 2, 2, 0, 1, 2, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 3, 2, 3, 1, 2, 2, 1, 0, 0, 0, 1, 1, 3, 1, 3, 1, 2, 2, 1, 4, 3, 2, 2, 1, 2, 3, 3, 3, 0, 1, 1, 0, 0, 0, 0, 1, 3, 1, 1, 3, 1, 3, 1, 1, 0, 1, 1, 0, 1, 2, 2, 1, 2, 1, 3, 2, 2, 1, 4, 1, 1, 0, 2, 1, 3, 1, 1, 1, 1, 2, 1, 3, 3, 1, 2, 1, 0, 0, 2, 1, 0, 1], 'learning_rate': 2.0592815452857624e-06, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000539703941546694, 'train_segmentation_loss': 0.27098023441463415, 'val_foreground_miou_all22': 0.7418155738713111, 'val_psnr_ref1': 39.10496047973633, 'elapsed_seconds': 329.9071271419525, 'peak_cuda_allocated_gib': 7.511997222900391}

Epoch 459/500 | Batch 10/202 | Rec 0.000568 | Seg 0.241513 | Elapsed 0.2m | ETA 4.1m
Epoch 459/500 | Batch 20/202 | Rec 0.000527 | Seg 0.242358 | Elapsed 0.4m | ETA 3.8m
Epoch 459/500 | Batch 30/202 | Rec 0.000565 | Seg 0.270811 | Elapsed 0.6m | ETA 3.6m
Epoch 459/500 | Batch 40/202 | Rec 0.000563 | Seg 0.271345 | Elapsed 0.8m | ETA 3.4m
Epoch 459/500 | Batch 50/202 | Rec 0.000541 | Seg 0.257928 | Elapsed 1.0m | ETA 3.1m
Epoch 459/500 | Batch 60/202 | Rec 0.000551 | Seg 0.269976 | Elapsed 1.2m | ETA 2.9m
Epoch 459/500 | Batch 70/202 | Rec 0.000553 | Seg 0.272311 | Elapsed 1.4m | ETA 2.7m
Epoch 459/500 | Batch 80/202 | Rec 0.000553 | Seg 0.267057 | Elapsed 1.6m | ETA 2.5m
Epoch 459/500 | Batch 90/202 | Rec 0.000549 | Seg 0.262630 | Elapsed 1.8m | ETA 2.3m
Epoch 459/500 | Batch 100/202 | Rec 0.000551 | Seg 0.262343 | Elapsed 2.1m | ETA 2.1m
Epoch 459/500 | Batch 110/202 | Rec 0.000544 | Seg 0.263738 | Elapsed 2.3m | ETA 1.9m
Epoch 459/500 | Batch 120/202 | Rec 0.000531 | Seg 0.259074 | Elapsed 2.5m | ETA 1.7m
Epoch 459/500 | Batch 130/202 | Rec 0.000537 | Seg 0.259726 | Elapsed 2.7m | ETA 1.5m
Epoch 459/500 | Batch 140/202 | Rec 0.000538 | Seg 0.260237 | Elapsed 2.9m | ETA 1.3m
Epoch 459/500 | Batch 150/202 | Rec 0.000537 | Seg 0.261272 | Elapsed 3.1m | ETA 1.1m
Epoch 459/500 | Batch 160/202 | Rec 0.000533 | Seg 0.260135 | Elapsed 3.3m | ETA 0.9m
Epoch 459/500 | Batch 170/202 | Rec 0.000534 | Seg 0.259958 | Elapsed 3.5m | ETA 0.7m
Epoch 459/500 | Batch 180/202 | Rec 0.000535 | Seg 0.263540 | Elapsed 3.7m | ETA 0.5m
Epoch 459/500 | Batch 190/202 | Rec 0.000536 | Seg 0.264495 | Elapsed 3.9m | ETA 0.2m
Epoch 459/500 | Batch 200/202 | Rec 0.000541 | Seg 0.266647 | Elapsed 4.1m | ETA 0.0m
Epoch 459/500 | Batch 202/202 | Rec 0.000542 | Seg 0.266887 | Elapsed 4.2m | ETA 0.0m

2026-10-10 14:12:04,670 - INFO: Rec loss: 0.0005418572166823957
2026-10-10 14:12:04,670 - INFO: Seg loss: 0.26688739609452755
2026-10-10 14:12:04,670 - INFO: λ_rec: 1
2026-10-10 14:12:04,670 - INFO: λ_seg: 0.0001
2026-10-10 14:13:17,182 - INFO: -------------------Epoch: 459------------------------
2026-10-10 14:13:17,185 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.130514  0.975134  0.000128
2026-10-10 14:13:17,192 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995439  0.997664  0.996763  0.998668  0.995644
real potato   0.896439  0.945342  0.947025  0.943764  0.999870
fake potato   0.958000  0.978500  0.977629  0.979472  0.999969
real apple    0.802536  0.890403  0.977933  0.817337  0.999306
fake apple    0.571009  0.726886  0.994110  0.572947  0.998375
real orange   0.898927  0.946724  0.996037  0.902154  0.999866
fake orange   0.923053  0.959937  0.958992  0.960985  0.999771
real grape    0.823248  0.903007  0.956742  0.855076  0.999617
fake grape    0.901786  0.948307  0.929086  0.968444  0.999610
real lemon    0.761720  0.864696  0.864521  0.864970  0.999682
fake lemon    0.798350  0.887820  0.993306  0.802669  0.999571
real avocado  0.944859  0.971598  0.987123  0.956650  0.999948
fake avocado  0.678398  0.808340  1.000000  0.678398  0.999615
real pepper   0.804877  0.891842  0.824937  0.970674  0.999139
fake pepper   0.660931  0.795807  0.920767  0.700787  0.999143
real plant    0.859217  0.924228  0.967378  0.884855  0.998550
fake plant    0.779195  0.875846  0.841399  0.913344  0.999794
real banana   0.784993  0.879498  0.882433  0.876681  0.999460
fake banana   0.653887  0.790678  0.731673  0.860153  0.999162
real onion    0.651842  0.789182  0.681094  0.938186  0.999547
fake onion    0.927502  0.962338  0.965668  0.959129  0.999953
real unknown  0.763010  0.865527  0.825823  0.909351  0.999955
fake unknown  0.188986  0.317854  0.218712  0.581673  0.997897
total         0.783835  0.866175  0.888659  0.865059  0.999280
total(-bg)    0.774217  0.860198  0.883745  0.858986  0.999445
2026-10-10 14:13:17,653 - INFO: Epoch accounting: {'epoch': 459, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11343924, 41262, 57164, 112217, 135080, 94926, 61375, 132162, 190334, 78756, 63236, 62759, 42408, 155377, 129262, 154393, 26816, 87908, 74406, 88964, 49347, 15464, 40732], 'crops_with_class': [202, 25, 27, 29, 31, 24, 25, 31, 33, 34, 28, 21, 16, 44, 34, 20, 29, 26, 27, 34, 28, 17, 23], 'targeted_crops_by_class': [0, 3, 3, 5, 2, 5, 6, 3, 5, 9, 7, 8, 2, 2, 6, 4, 5, 7, 4, 4, 3, 5, 1], 'sampled_scene_counts': [0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 1, 1, 2, 2, 1, 1, 2, 2, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 1, 1, 2, 2, 0, 0, 1, 2, 1, 0, 0, 1, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 1, 2, 2, 1, 0, 1, 0, 1, 1, 3, 1, 4, 1, 1, 2, 2, 1, 1, 2, 3, 3, 3, 0, 2, 1, 3, 4, 1, 0, 0, 3, 0, 0, 1, 2, 1, 6, 1, 1, 1, 1, 3, 1, 2, 1, 1, 0, 2, 1, 1, 1, 1, 2, 0, 2, 1, 2, 0, 2, 2, 0, 1, 3, 2, 0, 1, 3, 1, 0, 1, 2, 0, 2, 1, 0, 2, 1], 'learning_rate': 1.976590763190462e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005418572166823957, 'train_segmentation_loss': 0.26688739609452755, 'val_foreground_miou_all22': 0.7742166655834327, 'val_psnr_ref1': 39.130513763427736, 'elapsed_seconds': 322.71252274513245, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 460/500 | Batch 10/202 | Rec 0.000437 | Seg 0.254237 | Elapsed 0.2m | ETA 3.9m
Epoch 460/500 | Batch 20/202 | Rec 0.000495 | Seg 0.270642 | Elapsed 0.4m | ETA 3.7m
Epoch 460/500 | Batch 30/202 | Rec 0.000491 | Seg 0.270698 | Elapsed 0.6m | ETA 3.5m
Epoch 460/500 | Batch 40/202 | Rec 0.000517 | Seg 0.281417 | Elapsed 0.8m | ETA 3.3m
Epoch 460/500 | Batch 50/202 | Rec 0.000518 | Seg 0.275905 | Elapsed 1.0m | ETA 3.1m
Epoch 460/500 | Batch 60/202 | Rec 0.000519 | Seg 0.270415 | Elapsed 1.2m | ETA 2.9m
Epoch 460/500 | Batch 70/202 | Rec 0.000536 | Seg 0.277906 | Elapsed 1.4m | ETA 2.7m
Epoch 460/500 | Batch 80/202 | Rec 0.000527 | Seg 0.270063 | Elapsed 1.6m | ETA 2.5m
Epoch 460/500 | Batch 90/202 | Rec 0.000546 | Seg 0.272947 | Elapsed 1.8m | ETA 2.3m
Epoch 460/500 | Batch 100/202 | Rec 0.000550 | Seg 0.278371 | Elapsed 2.0m | ETA 2.1m
Epoch 460/500 | Batch 110/202 | Rec 0.000536 | Seg 0.270376 | Elapsed 2.2m | ETA 1.9m
Epoch 460/500 | Batch 120/202 | Rec 0.000529 | Seg 0.272115 | Elapsed 2.4m | ETA 1.7m
Epoch 460/500 | Batch 130/202 | Rec 0.000531 | Seg 0.275837 | Elapsed 2.6m | ETA 1.5m
Epoch 460/500 | Batch 140/202 | Rec 0.000526 | Seg 0.276376 | Elapsed 2.9m | ETA 1.3m
Epoch 460/500 | Batch 150/202 | Rec 0.000534 | Seg 0.275120 | Elapsed 3.0m | ETA 1.1m
Epoch 460/500 | Batch 160/202 | Rec 0.000538 | Seg 0.274600 | Elapsed 3.3m | ETA 0.9m
Epoch 460/500 | Batch 170/202 | Rec 0.000542 | Seg 0.276570 | Elapsed 3.5m | ETA 0.7m
Epoch 460/500 | Batch 180/202 | Rec 0.000545 | Seg 0.274192 | Elapsed 3.7m | ETA 0.4m
Epoch 460/500 | Batch 190/202 | Rec 0.000550 | Seg 0.274955 | Elapsed 3.9m | ETA 0.2m
Epoch 460/500 | Batch 200/202 | Rec 0.000547 | Seg 0.272251 | Elapsed 4.1m | ETA 0.0m
Epoch 460/500 | Batch 202/202 | Rec 0.000546 | Seg 0.271114 | Elapsed 4.1m | ETA 0.0m

2026-10-10 14:17:23,823 - INFO: Rec loss: 0.0005460818393829066
2026-10-10 14:17:23,823 - INFO: Seg loss: 0.2711142581878322
2026-10-10 14:17:23,823 - INFO: λ_rec: 1
2026-10-10 14:17:23,823 - INFO: λ_seg: 0.0001
2026-10-10 14:18:43,496 - INFO: -------------------Epoch: 460------------------------
2026-10-10 14:18:43,499 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.180357  0.975216  0.000126
2026-10-10 14:18:43,505 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995570  0.997730  0.997055  0.998507  0.995771
real potato   0.417621  0.589144  0.969892  0.423106  0.999294
fake potato   0.659768  0.794964  0.982132  0.667784  0.999749
real apple    0.678214  0.808207  0.780367  0.838213  0.998628
fake apple    0.594433  0.745588  0.992278  0.597195  0.998462
real orange   0.921808  0.959264  0.995640  0.925544  0.999897
fake orange   0.941119  0.969616  0.968172  0.971165  0.999826
real grape    0.788124  0.881459  0.916936  0.848717  0.999524
fake grape    0.903200  0.949088  0.933538  0.965268  0.999617
real lemon    0.573810  0.729151  0.589233  0.956375  0.999165
fake lemon    0.857235  0.923081  0.996739  0.859647  0.999697
real avocado  0.901128  0.947943  0.938385  0.957800  0.999902
fake avocado  0.651409  0.788865  0.999804  0.651492  0.999583
real pepper   0.793705  0.884940  0.819730  0.961538  0.999086
fake pepper   0.618471  0.764218  0.924895  0.651175  0.999043
real plant    0.867759  0.929148  0.958964  0.901223  0.998626
fake plant    0.796916  0.886932  0.854882  0.921587  0.999813
real banana   0.559147  0.717199  0.854687  0.617887  0.998905
fake banana   0.727524  0.842224  0.813989  0.872595  0.999399
real onion    0.622138  0.767010  0.730229  0.807803  0.999557
fake onion    0.913179  0.954570  0.993979  0.918259  0.999945
real unknown  0.777331  0.874667  0.831470  0.922710  0.999958
fake unknown  0.200700  0.334268  0.218960  0.706447  0.997629
total         0.728709  0.827795  0.872259  0.823567  0.999177
total(-bg)    0.716579  0.820070  0.866587  0.815615  0.999332
2026-10-10 14:18:43,964 - INFO: Epoch accounting: {'epoch': 460, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11306786, 69031, 60138, 90218, 103201, 86437, 56200, 185573, 163946, 77279, 64251, 54164, 54604, 248025, 127945, 122169, 23514, 87800, 57328, 71814, 61904, 9339, 56606], 'crops_with_class': [202, 33, 26, 24, 35, 26, 19, 33, 31, 33, 27, 17, 22, 66, 37, 20, 21, 24, 30, 36, 29, 11, 20], 'targeted_crops_by_class': [0, 10, 6, 4, 1, 5, 3, 6, 8, 3, 8, 4, 8, 8, 4, 4, 4, 2, 2, 6, 4, 1, 8], 'sampled_scene_counts': [1, 0, 2, 0, 0, 2, 1, 1, 0, 2, 2, 1, 1, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 2, 0, 2, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 4, 1, 0, 0, 1, 0, 2, 3, 2, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 2, 2, 0, 2, 1, 1, 0, 3, 1, 0, 2, 0, 0, 0, 3, 2, 4, 2, 0, 0, 1, 2, 1, 0, 2, 2, 0, 0, 1, 0, 1, 2, 2, 2, 2, 3, 1, 1, 3, 4, 3, 1, 0, 2, 1, 0, 2, 0, 2, 0, 0, 0, 2, 1, 1, 2, 3, 1, 3, 2, 0, 2, 2, 0, 3, 1, 0, 0, 2, 0, 0, 1, 3, 3, 5, 0, 2, 1, 3, 4, 3, 2], 'learning_rate': 1.8958007978485514e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005460818393829066, 'train_segmentation_loss': 0.2711142581878322, 'val_foreground_miou_all22': 0.716579066520203, 'val_psnr_ref1': 39.180356903076174, 'elapsed_seconds': 326.30359864234924, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 461/500 | Batch 10/202 | Rec 0.000591 | Seg 0.312775 | Elapsed 0.2m | ETA 3.9m
Epoch 461/500 | Batch 20/202 | Rec 0.000578 | Seg 0.299737 | Elapsed 0.4m | ETA 3.7m
Epoch 461/500 | Batch 30/202 | Rec 0.000577 | Seg 0.305227 | Elapsed 0.6m | ETA 3.5m
Epoch 461/500 | Batch 40/202 | Rec 0.000565 | Seg 0.293190 | Elapsed 0.8m | ETA 3.3m
Epoch 461/500 | Batch 50/202 | Rec 0.000561 | Seg 0.290551 | Elapsed 1.0m | ETA 3.1m
Epoch 461/500 | Batch 60/202 | Rec 0.000569 | Seg 0.298251 | Elapsed 1.2m | ETA 2.9m
Epoch 461/500 | Batch 70/202 | Rec 0.000571 | Seg 0.289408 | Elapsed 1.4m | ETA 2.7m
Epoch 461/500 | Batch 80/202 | Rec 0.000574 | Seg 0.294400 | Elapsed 1.6m | ETA 2.5m
Epoch 461/500 | Batch 90/202 | Rec 0.000597 | Seg 0.296900 | Elapsed 1.8m | ETA 2.3m
Epoch 461/500 | Batch 100/202 | Rec 0.000600 | Seg 0.295009 | Elapsed 2.0m | ETA 2.1m
Epoch 461/500 | Batch 110/202 | Rec 0.000600 | Seg 0.295468 | Elapsed 2.2m | ETA 1.9m
Epoch 461/500 | Batch 120/202 | Rec 0.000603 | Seg 0.295816 | Elapsed 2.5m | ETA 1.7m
Epoch 461/500 | Batch 130/202 | Rec 0.000593 | Seg 0.292609 | Elapsed 2.7m | ETA 1.5m
Epoch 461/500 | Batch 140/202 | Rec 0.000588 | Seg 0.288439 | Elapsed 2.9m | ETA 1.3m
Epoch 461/500 | Batch 150/202 | Rec 0.000583 | Seg 0.285960 | Elapsed 3.1m | ETA 1.1m
Epoch 461/500 | Batch 160/202 | Rec 0.000587 | Seg 0.288588 | Elapsed 3.3m | ETA 0.9m
Epoch 461/500 | Batch 170/202 | Rec 0.000594 | Seg 0.291416 | Elapsed 3.5m | ETA 0.7m
Epoch 461/500 | Batch 180/202 | Rec 0.000590 | Seg 0.287548 | Elapsed 3.7m | ETA 0.5m
Epoch 461/500 | Batch 190/202 | Rec 0.000595 | Seg 0.288723 | Elapsed 3.9m | ETA 0.2m
Epoch 461/500 | Batch 200/202 | Rec 0.000601 | Seg 0.289700 | Elapsed 4.1m | ETA 0.0m
Epoch 461/500 | Batch 202/202 | Rec 0.000600 | Seg 0.289514 | Elapsed 4.1m | ETA 0.0m

2026-10-10 14:22:51,628 - INFO: Rec loss: 0.0005996014060116014
2026-10-10 14:22:51,628 - INFO: Seg loss: 0.2895135300805663
2026-10-10 14:22:51,628 - INFO: λ_rec: 1
2026-10-10 14:22:51,628 - INFO: λ_seg: 0.0001
2026-10-10 14:24:11,354 - INFO: -------------------Epoch: 461------------------------
2026-10-10 14:24:11,358 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.060762  0.974989  0.00013
2026-10-10 14:24:11,364 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995808  0.997849  0.997634  0.998165  0.995999
real potato   0.513431  0.678455  0.987811  0.516705  0.999414
fake potato   0.679241  0.808937  0.977165  0.690197  0.999763
real apple    0.740415  0.850799  0.823754  0.879788  0.998936
fake apple    0.625214  0.769345  0.975127  0.635346  0.998562
real orange   0.939883  0.968960  0.994274  0.944998  0.999920
fake orange   0.946563  0.972498  0.966128  0.979053  0.999842
real grape    0.806438  0.892799  0.966777  0.829423  0.999584
fake grape    0.875843  0.933763  0.891276  0.980613  0.999486
real lemon    0.498813  0.665564  0.519157  0.927162  0.998905
fake lemon    0.862507  0.926129  0.994783  0.866426  0.999708
real avocado  0.852314  0.920220  0.879754  0.964696  0.999845
fake avocado  0.768995  0.869366  0.999669  0.769192  0.999724
real pepper   0.814871  0.897944  0.845978  0.956825  0.999205
fake pepper   0.686482  0.814051  0.954538  0.709686  0.999227
real plant    0.876887  0.934356  0.946634  0.922489  0.998705
fake plant    0.884636  0.938737  0.947122  0.930598  0.999903
real banana   0.448618  0.619328  0.839726  0.490629  0.998645
fake banana   0.689575  0.816221  0.772967  0.864715  0.999284
real onion    0.645185  0.784282  0.701479  0.889377  0.999558
fake onion    0.911386  0.953589  0.983800  0.925272  0.999943
real unknown  0.922641  0.959714  0.987879  0.933206  0.999987
fake unknown  0.230962  0.375217  0.248188  0.768924  0.997843
total         0.748553  0.841223  0.878331  0.842325  0.999217
total(-bg)    0.737314  0.834103  0.872908  0.835242  0.999363
2026-10-10 14:24:11,821 - INFO: Epoch accounting: {'epoch': 461, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11169493, 42800, 50873, 143707, 190402, 75896, 59596, 118941, 233724, 48848, 59411, 51230, 28679, 248163, 129175, 179576, 31409, 84767, 72644, 93012, 61519, 14820, 49587], 'crops_with_class': [202, 25, 22, 41, 44, 26, 23, 26, 42, 24, 27, 19, 10, 61, 31, 27, 27, 25, 32, 37, 28, 16, 22], 'targeted_crops_by_class': [0, 2, 4, 6, 6, 5, 3, 3, 4, 5, 3, 2, 4, 4, 3, 6, 7, 4, 5, 4, 7, 8, 5], 'sampled_scene_counts': [1, 1, 0, 0, 0, 0, 0, 1, 0, 2, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 1, 0, 4, 2, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 2, 1, 2, 0, 2, 0, 3, 3, 3, 0, 1, 0, 3, 2, 6, 1, 0, 2, 1, 2, 0, 3, 2, 2, 1, 0, 1, 1, 3, 4, 1, 2, 1, 3, 2, 1, 2, 0, 2, 0, 1, 0, 2, 5, 3, 1, 1, 1, 1, 2, 1, 1, 3, 1, 1, 3, 1, 2, 0, 2, 1, 0, 0, 3, 1, 1, 2, 3, 0, 0, 0, 1, 1, 1, 1, 2, 2, 1, 1, 1, 0, 1, 4, 2, 2], 'learning_rate': 1.8169148387095222e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005996014060116014, 'train_segmentation_loss': 0.2895135300805663, 'val_foreground_miou_all22': 0.7373137276927676, 'val_psnr_ref1': 39.06076217651367, 'elapsed_seconds': 327.8504192829132, 'peak_cuda_allocated_gib': 7.513248443603516}

Epoch 462/500 | Batch 10/202 | Rec 0.000558 | Seg 0.275601 | Elapsed 0.2m | ETA 4.0m
Epoch 462/500 | Batch 20/202 | Rec 0.000516 | Seg 0.257921 | Elapsed 0.4m | ETA 3.7m
Epoch 462/500 | Batch 30/202 | Rec 0.000563 | Seg 0.271675 | Elapsed 0.6m | ETA 3.5m
Epoch 462/500 | Batch 40/202 | Rec 0.000535 | Seg 0.260829 | Elapsed 0.8m | ETA 3.3m
Epoch 462/500 | Batch 50/202 | Rec 0.000533 | Seg 0.256629 | Elapsed 1.0m | ETA 3.1m
Epoch 462/500 | Batch 60/202 | Rec 0.000535 | Seg 0.259447 | Elapsed 1.2m | ETA 2.9m
Epoch 462/500 | Batch 70/202 | Rec 0.000529 | Seg 0.258673 | Elapsed 1.4m | ETA 2.7m
Epoch 462/500 | Batch 80/202 | Rec 0.000535 | Seg 0.265731 | Elapsed 1.6m | ETA 2.5m
Epoch 462/500 | Batch 90/202 | Rec 0.000538 | Seg 0.265385 | Elapsed 1.8m | ETA 2.3m
Epoch 462/500 | Batch 100/202 | Rec 0.000549 | Seg 0.269793 | Elapsed 2.0m | ETA 2.1m
Epoch 462/500 | Batch 110/202 | Rec 0.000542 | Seg 0.265141 | Elapsed 2.2m | ETA 1.9m
Epoch 462/500 | Batch 120/202 | Rec 0.000542 | Seg 0.264288 | Elapsed 2.5m | ETA 1.7m
Epoch 462/500 | Batch 130/202 | Rec 0.000544 | Seg 0.266138 | Elapsed 2.7m | ETA 1.5m
Epoch 462/500 | Batch 140/202 | Rec 0.000555 | Seg 0.268855 | Elapsed 2.9m | ETA 1.3m
Epoch 462/500 | Batch 150/202 | Rec 0.000552 | Seg 0.268820 | Elapsed 3.1m | ETA 1.1m
Epoch 462/500 | Batch 160/202 | Rec 0.000550 | Seg 0.268873 | Elapsed 3.3m | ETA 0.9m
Epoch 462/500 | Batch 170/202 | Rec 0.000549 | Seg 0.264490 | Elapsed 3.5m | ETA 0.7m
Epoch 462/500 | Batch 180/202 | Rec 0.000551 | Seg 0.266559 | Elapsed 3.7m | ETA 0.4m
Epoch 462/500 | Batch 190/202 | Rec 0.000548 | Seg 0.267541 | Elapsed 3.9m | ETA 0.2m
Epoch 462/500 | Batch 200/202 | Rec 0.000546 | Seg 0.268413 | Elapsed 4.1m | ETA 0.0m
Epoch 462/500 | Batch 202/202 | Rec 0.000547 | Seg 0.269017 | Elapsed 4.1m | ETA 0.0m

2026-10-10 14:28:19,040 - INFO: Rec loss: 0.0005471149515239568
2026-10-10 14:28:19,040 - INFO: Seg loss: 0.26901656481446606
2026-10-10 14:28:19,040 - INFO: λ_rec: 1
2026-10-10 14:28:19,040 - INFO: λ_seg: 0.0001
2026-10-10 14:29:41,995 - INFO: -------------------Epoch: 462------------------------
2026-10-10 14:29:41,998 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  39.102366  0.97512  0.000129
2026-10-10 14:29:42,004 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995616  0.997753  0.996876  0.998732  0.995813
real potato   0.868567  0.929611  0.964242  0.897475  0.999837
fake potato   0.939568  0.968793  0.980480  0.957478  0.999955
real apple    0.818509  0.900148  0.949325  0.855904  0.999345
fake apple    0.648316  0.786592  0.984806  0.654866  0.998659
real orange   0.900876  0.947804  0.994908  0.905049  0.999869
fake orange   0.924035  0.960468  0.944556  0.977028  0.999770
real grape    0.801251  0.889611  0.942591  0.842359  0.999564
fake grape    0.902094  0.948477  0.936199  0.961185  0.999614
real lemon    0.701677  0.824639  0.744792  0.923786  0.999538
fake lemon    0.846364  0.916740  0.996781  0.848684  0.999674
real avocado  0.908278  0.951885  0.936874  0.967488  0.999909
fake avocado  0.648221  0.786523  0.999803  0.648304  0.999579
real pepper   0.776927  0.874412  0.805538  0.956282  0.998996
fake pepper   0.608977  0.756926  0.940925  0.633186  0.999031
real plant    0.861361  0.925468  0.961358  0.892253  0.998564
fake plant    0.749146  0.856535  0.831828  0.882860  0.999765
real banana   0.704333  0.826470  0.904912  0.760627  0.999283
fake banana   0.740003  0.850527  0.850788  0.850365  0.999450
real onion    0.659510  0.794776  0.703723  0.913021  0.999574
fake onion    0.946454  0.972441  0.983432  0.961790  0.999966
real unknown  0.825601  0.904421  0.892293  0.916985  0.999969
fake unknown  0.234081  0.379320  0.262120  0.686346  0.998108
total         0.783033  0.867406  0.891702  0.864872  0.999297
total(-bg)    0.773370  0.861481  0.886922  0.858787  0.999455
2026-10-10 14:29:42,473 - INFO: Epoch accounting: {'epoch': 462, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11296603, 48796, 56467, 111647, 97355, 96495, 59298, 130510, 179571, 92507, 66545, 55356, 55551, 256680, 147483, 138067, 24349, 73866, 78435, 58367, 61513, 10070, 42741], 'crops_with_class': [202, 27, 27, 30, 29, 25, 24, 29, 37, 40, 26, 19, 20, 52, 37, 24, 22, 23, 31, 33, 25, 11, 20], 'targeted_crops_by_class': [0, 4, 2, 4, 3, 3, 4, 10, 2, 5, 2, 6, 8, 5, 9, 7, 3, 8, 2, 9, 3, 4, 3], 'sampled_scene_counts': [0, 2, 1, 0, 1, 0, 0, 2, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 3, 0, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 1, 0, 1, 1, 1, 3, 0, 1, 0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 2, 0, 2, 2, 0, 1, 2, 2, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 2, 0, 1, 1, 0, 3, 2, 2, 0, 0, 1, 0, 3, 2, 2, 2, 1, 0, 4, 1, 1, 1, 2, 3, 1, 1, 2, 2, 1, 3, 1, 1, 0, 0, 1, 0, 0, 1, 3, 4, 2, 3, 0, 1, 0, 2, 1, 2, 1, 0, 3, 1, 1, 2, 3, 3, 0, 1, 3, 0, 1, 0, 1, 2, 0, 2, 1, 3, 1, 2, 1, 0, 2, 1, 1, 2, 2, 2, 1, 1, 1], 'learning_rate': 1.7399360000559707e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005471149515239568, 'train_segmentation_loss': 0.26901656481446606, 'val_foreground_miou_all22': 0.7733703405274786, 'val_psnr_ref1': 39.10236572265625, 'elapsed_seconds': 330.64447355270386, 'peak_cuda_allocated_gib': 7.507823944091797}

Epoch 463/500 | Batch 10/202 | Rec 0.000762 | Seg 0.327016 | Elapsed 0.2m | ETA 4.0m
Epoch 463/500 | Batch 20/202 | Rec 0.000665 | Seg 0.291381 | Elapsed 0.4m | ETA 3.8m
Epoch 463/500 | Batch 30/202 | Rec 0.000623 | Seg 0.283192 | Elapsed 0.6m | ETA 3.6m
Epoch 463/500 | Batch 40/202 | Rec 0.000605 | Seg 0.291660 | Elapsed 0.8m | ETA 3.3m
Epoch 463/500 | Batch 50/202 | Rec 0.000610 | Seg 0.296502 | Elapsed 1.0m | ETA 3.1m
Epoch 463/500 | Batch 60/202 | Rec 0.000603 | Seg 0.290944 | Elapsed 1.2m | ETA 2.9m
Epoch 463/500 | Batch 70/202 | Rec 0.000620 | Seg 0.298460 | Elapsed 1.4m | ETA 2.7m
Epoch 463/500 | Batch 80/202 | Rec 0.000600 | Seg 0.286747 | Elapsed 1.6m | ETA 2.5m
Epoch 463/500 | Batch 90/202 | Rec 0.000609 | Seg 0.287885 | Elapsed 1.8m | ETA 2.3m
Epoch 463/500 | Batch 100/202 | Rec 0.000601 | Seg 0.286103 | Elapsed 2.1m | ETA 2.1m
Epoch 463/500 | Batch 110/202 | Rec 0.000594 | Seg 0.281607 | Elapsed 2.3m | ETA 1.9m
Epoch 463/500 | Batch 120/202 | Rec 0.000584 | Seg 0.277501 | Elapsed 2.5m | ETA 1.7m
Epoch 463/500 | Batch 130/202 | Rec 0.000571 | Seg 0.272394 | Elapsed 2.7m | ETA 1.5m
Epoch 463/500 | Batch 140/202 | Rec 0.000580 | Seg 0.278431 | Elapsed 2.9m | ETA 1.3m
Epoch 463/500 | Batch 150/202 | Rec 0.000573 | Seg 0.275077 | Elapsed 3.1m | ETA 1.1m
Epoch 463/500 | Batch 160/202 | Rec 0.000580 | Seg 0.270107 | Elapsed 3.3m | ETA 0.9m
Epoch 463/500 | Batch 170/202 | Rec 0.000579 | Seg 0.268849 | Elapsed 3.5m | ETA 0.7m
Epoch 463/500 | Batch 180/202 | Rec 0.000588 | Seg 0.270279 | Elapsed 3.7m | ETA 0.5m
Epoch 463/500 | Batch 190/202 | Rec 0.000581 | Seg 0.265746 | Elapsed 3.9m | ETA 0.2m
Epoch 463/500 | Batch 200/202 | Rec 0.000584 | Seg 0.266150 | Elapsed 4.1m | ETA 0.0m
Epoch 463/500 | Batch 202/202 | Rec 0.000585 | Seg 0.266503 | Elapsed 4.2m | ETA 0.0m

2026-10-10 14:33:52,268 - INFO: Rec loss: 0.0005846646377219736
2026-10-10 14:33:52,268 - INFO: Seg loss: 0.2665028847237625
2026-10-10 14:33:52,268 - INFO: λ_rec: 1
2026-10-10 14:33:52,268 - INFO: λ_seg: 0.0001
2026-10-10 14:35:08,991 - INFO: -------------------Epoch: 463------------------------
2026-10-10 14:35:08,995 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.973403  0.974808  0.000132
2026-10-10 14:35:09,001 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995634  0.997762  0.997171  0.998454  0.995832
real potato   0.922600  0.959692  0.951385  0.968248  0.999903
fake potato   0.962341  0.980759  0.976735  0.984918  0.999972
real apple    0.782334  0.877827  0.988157  0.789739  0.999242
fake apple    0.536883  0.698619  0.992191  0.539161  0.998244
real orange   0.927252  0.962203  0.997020  0.929829  0.999904
fake orange   0.935248  0.966491  0.964642  0.968447  0.999808
real grape    0.820507  0.901355  0.955323  0.853249  0.999610
fake grape    0.903556  0.949285  0.925318  0.974632  0.999615
real lemon    0.768885  0.869294  0.814806  0.931706  0.999671
fake lemon    0.837683  0.911623  0.992946  0.842697  0.999655
real avocado  0.950073  0.974348  0.993347  0.956158  0.999953
fake avocado  0.569807  0.725912  0.999776  0.569880  0.999485
real pepper   0.861254  0.925405  0.881613  0.973886  0.999426
fake pepper   0.783570  0.878604  0.932835  0.830421  0.999453
real plant    0.869567  0.930184  0.960758  0.901590  0.998647
fake plant    0.805099  0.891978  0.882243  0.902032  0.999826
real banana   0.742508  0.852179  0.870643  0.834578  0.999350
fake banana   0.714305  0.833297  0.793636  0.877240  0.999355
real onion    0.657233  0.793120  0.681212  0.949164  0.999553
fake onion    0.928046  0.962630  0.980924  0.945103  0.999954
real unknown  0.619531  0.765026  0.648738  0.932252  0.999908
fake unknown  0.177263  0.301108  0.196121  0.648316  0.997465
total         0.785704  0.865596  0.885980  0.873987  0.999297
total(-bg)    0.776161  0.859588  0.880926  0.868329  0.999454
2026-10-10 14:35:09,458 - INFO: Epoch accounting: {'epoch': 463, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11351070, 42810, 60054, 102523, 154945, 75405, 74252, 128877, 141038, 71174, 67695, 39719, 41304, 209925, 117672, 162992, 25516, 60419, 84001, 100421, 65603, 12848, 48009], 'crops_with_class': [202, 29, 28, 28, 35, 25, 24, 27, 28, 30, 27, 15, 16, 50, 29, 18, 22, 20, 34, 38, 29, 12, 20], 'targeted_crops_by_class': [0, 1, 8, 0, 4, 6, 6, 4, 1, 4, 3, 4, 3, 4, 2, 7, 4, 2, 4, 5, 7, 3, 5], 'sampled_scene_counts': [2, 2, 3, 0, 0, 1, 0, 1, 4, 2, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 2, 0, 1, 1, 3, 1, 0, 1, 1, 1, 0, 2, 1, 0, 1, 0, 1, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 0, 1, 2, 1, 0, 0, 0, 2, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 2, 0, 0, 2, 0, 1, 1, 1, 1, 1, 0, 0, 3, 2, 0, 2, 1, 1, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 3, 0, 0, 1, 1, 1, 0, 0, 2, 1, 1, 1, 1, 2, 0, 2, 2, 1, 0, 2, 0, 1, 1, 4, 2, 3, 1, 1, 2, 1, 2, 1, 1, 2, 3, 1, 1, 1, 1, 0, 1, 2, 0, 1, 0, 0, 0, 2, 2, 3, 2, 2, 0, 1, 3, 2, 0, 0, 0, 1, 2, 2, 1, 2, 2, 2], 'learning_rate': 1.664867320880633e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005846646377219736, 'train_segmentation_loss': 0.2665028847237625, 'val_foreground_miou_all22': 0.7761611871266912, 'val_psnr_ref1': 38.9734033203125, 'elapsed_seconds': 326.9776303768158, 'peak_cuda_allocated_gib': 7.511020660400391}

Epoch 464/500 | Batch 10/202 | Rec 0.000469 | Seg 0.262872 | Elapsed 0.2m | ETA 3.9m
Epoch 464/500 | Batch 20/202 | Rec 0.000505 | Seg 0.266778 | Elapsed 0.4m | ETA 3.7m
Epoch 464/500 | Batch 30/202 | Rec 0.000522 | Seg 0.258515 | Elapsed 0.6m | ETA 3.6m
Epoch 464/500 | Batch 40/202 | Rec 0.000539 | Seg 0.271134 | Elapsed 0.8m | ETA 3.3m
Epoch 464/500 | Batch 50/202 | Rec 0.000562 | Seg 0.280216 | Elapsed 1.0m | ETA 3.1m
Epoch 464/500 | Batch 60/202 | Rec 0.000571 | Seg 0.285783 | Elapsed 1.2m | ETA 2.9m
Epoch 464/500 | Batch 70/202 | Rec 0.000565 | Seg 0.278947 | Elapsed 1.4m | ETA 2.7m
Epoch 464/500 | Batch 80/202 | Rec 0.000559 | Seg 0.281612 | Elapsed 1.6m | ETA 2.5m
Epoch 464/500 | Batch 90/202 | Rec 0.000565 | Seg 0.277031 | Elapsed 1.8m | ETA 2.3m
Epoch 464/500 | Batch 100/202 | Rec 0.000559 | Seg 0.274299 | Elapsed 2.0m | ETA 2.1m
Epoch 464/500 | Batch 110/202 | Rec 0.000564 | Seg 0.275833 | Elapsed 2.3m | ETA 1.9m
Epoch 464/500 | Batch 120/202 | Rec 0.000569 | Seg 0.280364 | Elapsed 2.5m | ETA 1.7m
Epoch 464/500 | Batch 130/202 | Rec 0.000565 | Seg 0.277528 | Elapsed 2.7m | ETA 1.5m
Epoch 464/500 | Batch 140/202 | Rec 0.000562 | Seg 0.274666 | Elapsed 2.9m | ETA 1.3m
Epoch 464/500 | Batch 150/202 | Rec 0.000573 | Seg 0.278635 | Elapsed 3.1m | ETA 1.1m
Epoch 464/500 | Batch 160/202 | Rec 0.000563 | Seg 0.274959 | Elapsed 3.3m | ETA 0.9m
Epoch 464/500 | Batch 170/202 | Rec 0.000558 | Seg 0.274134 | Elapsed 3.5m | ETA 0.7m
Epoch 464/500 | Batch 180/202 | Rec 0.000561 | Seg 0.276422 | Elapsed 3.7m | ETA 0.5m
Epoch 464/500 | Batch 190/202 | Rec 0.000561 | Seg 0.277258 | Elapsed 3.9m | ETA 0.2m
Epoch 464/500 | Batch 200/202 | Rec 0.000558 | Seg 0.275060 | Elapsed 4.1m | ETA 0.0m
Epoch 464/500 | Batch 202/202 | Rec 0.000555 | Seg 0.273394 | Elapsed 4.1m | ETA 0.0m

2026-10-10 14:39:17,808 - INFO: Rec loss: 0.0005553379044136134
2026-10-10 14:39:17,808 - INFO: Seg loss: 0.273394478355894
2026-10-10 14:39:17,808 - INFO: λ_rec: 1
2026-10-10 14:39:17,808 - INFO: λ_seg: 0.0001
2026-10-10 14:40:37,824 - INFO: -------------------Epoch: 464------------------------
2026-10-10 14:40:37,828 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.198067  0.975204  0.000126
2026-10-10 14:40:37,834 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995622  0.997756  0.997021  0.998592  0.995819
real potato   0.368273  0.538264  1.000000  0.368273  0.999244
fake potato   0.659261  0.794596  0.986944  0.665061  0.999750
real apple    0.695952  0.820671  0.768580  0.880451  0.998673
fake apple    0.774530  0.872891  0.979923  0.787019  0.999135
real orange   0.913960  0.954996  0.994236  0.918828  0.999886
fake orange   0.923348  0.960097  0.943690  0.977188  0.999768
real grape    0.780897  0.876920  0.945953  0.817365  0.999521
fake grape    0.897452  0.945905  0.926714  0.966011  0.999592
real lemon    0.487642  0.655546  0.500376  0.950402  0.998826
fake lemon    0.860271  0.924838  0.994852  0.864118  0.999703
real avocado  0.842465  0.914448  0.863351  0.972085  0.999831
fake avocado  0.836625  0.910997  0.999239  0.837159  0.999804
real pepper   0.750266  0.857267  0.787000  0.941432  0.998854
fake pepper   0.548597  0.708462  0.958711  0.561872  0.998898
real plant    0.860316  0.924864  0.950818  0.900384  0.998538
fake plant    0.847614  0.917473  0.956142  0.881902  0.999874
real banana   0.394020  0.565255  0.843758  0.425031  0.998531
fake banana   0.734251  0.846714  0.857532  0.836264  0.999443
real onion    0.628661  0.771948  0.708263  0.848336  0.999547
fake onion    0.939686  0.968855  0.997439  0.941959  0.999962
real unknown  0.800327  0.889041  0.848958  0.933206  0.999963
fake unknown  0.287156  0.446144  0.324021  0.716226  0.998502
total         0.731617  0.828867  0.875370  0.825616  0.999203
total(-bg)    0.719617  0.821191  0.869841  0.817753  0.999357
2026-10-10 14:40:38,293 - INFO: Epoch accounting: {'epoch': 464, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11323170, 73940, 66457, 130775, 131317, 70165, 79467, 130223, 199255, 76804, 39664, 42568, 47549, 191685, 101606, 140205, 26383, 85376, 70390, 90841, 61245, 9986, 49201], 'crops_with_class': [202, 38, 34, 35, 35, 21, 27, 24, 34, 30, 20, 17, 19, 49, 31, 18, 25, 26, 28, 40, 31, 11, 21], 'targeted_crops_by_class': [0, 4, 4, 4, 9, 4, 3, 6, 2, 2, 2, 3, 6, 4, 3, 4, 7, 3, 4, 9, 7, 6, 1], 'sampled_scene_counts': [1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 2, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 1, 2, 1, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 2, 0, 1, 1, 1, 0, 2, 1, 0, 1, 2, 1, 1, 1, 1, 1, 0, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 2, 0, 3, 2, 3, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 2, 2, 2, 1, 0, 3, 3, 3, 3, 0, 2, 1, 1, 0, 0, 3, 2, 2, 3, 1, 0, 1, 0, 2, 1, 3, 1, 0, 2, 2, 1, 0, 2, 0, 2, 1, 0, 2, 1, 2, 3, 2, 1, 0, 0, 0, 4, 5, 3, 1, 1, 1, 3, 2, 1, 1, 1, 3], 'learning_rate': 1.5917117647664374e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005553379044136134, 'train_segmentation_loss': 0.273394478355894, 'val_foreground_miou_all22': 0.7196167899577668, 'val_psnr_ref1': 39.19806716918945, 'elapsed_seconds': 328.8272578716278, 'peak_cuda_allocated_gib': 7.502964019775391}

Epoch 465/500 | Batch 10/202 | Rec 0.000548 | Seg 0.257340 | Elapsed 0.2m | ETA 4.0m
Epoch 465/500 | Batch 20/202 | Rec 0.000587 | Seg 0.275293 | Elapsed 0.4m | ETA 3.8m
Epoch 465/500 | Batch 30/202 | Rec 0.000562 | Seg 0.284056 | Elapsed 0.6m | ETA 3.6m
Epoch 465/500 | Batch 40/202 | Rec 0.000564 | Seg 0.286982 | Elapsed 0.8m | ETA 3.4m
Epoch 465/500 | Batch 50/202 | Rec 0.000545 | Seg 0.278685 | Elapsed 1.0m | ETA 3.1m
Epoch 465/500 | Batch 60/202 | Rec 0.000557 | Seg 0.282615 | Elapsed 1.2m | ETA 2.9m
Epoch 465/500 | Batch 70/202 | Rec 0.000564 | Seg 0.284794 | Elapsed 1.4m | ETA 2.7m
Epoch 465/500 | Batch 80/202 | Rec 0.000554 | Seg 0.278924 | Elapsed 1.6m | ETA 2.5m
Epoch 465/500 | Batch 90/202 | Rec 0.000560 | Seg 0.275574 | Elapsed 1.8m | ETA 2.3m
Epoch 465/500 | Batch 100/202 | Rec 0.000563 | Seg 0.278890 | Elapsed 2.1m | ETA 2.1m
Epoch 465/500 | Batch 110/202 | Rec 0.000587 | Seg 0.287189 | Elapsed 2.3m | ETA 1.9m
Epoch 465/500 | Batch 120/202 | Rec 0.000572 | Seg 0.282681 | Elapsed 2.5m | ETA 1.7m
Epoch 465/500 | Batch 130/202 | Rec 0.000583 | Seg 0.288127 | Elapsed 2.7m | ETA 1.5m
Epoch 465/500 | Batch 140/202 | Rec 0.000579 | Seg 0.283622 | Elapsed 2.9m | ETA 1.3m
Epoch 465/500 | Batch 150/202 | Rec 0.000586 | Seg 0.280144 | Elapsed 3.1m | ETA 1.1m
Epoch 465/500 | Batch 160/202 | Rec 0.000586 | Seg 0.282850 | Elapsed 3.3m | ETA 0.9m
Epoch 465/500 | Batch 170/202 | Rec 0.000579 | Seg 0.281085 | Elapsed 3.5m | ETA 0.7m
Epoch 465/500 | Batch 180/202 | Rec 0.000574 | Seg 0.281524 | Elapsed 3.7m | ETA 0.5m
Epoch 465/500 | Batch 190/202 | Rec 0.000581 | Seg 0.281651 | Elapsed 3.9m | ETA 0.2m
Epoch 465/500 | Batch 200/202 | Rec 0.000577 | Seg 0.279428 | Elapsed 4.1m | ETA 0.0m
Epoch 465/500 | Batch 202/202 | Rec 0.000576 | Seg 0.279033 | Elapsed 4.1m | ETA 0.0m

2026-10-10 14:44:46,712 - INFO: Rec loss: 0.0005759315283267094
2026-10-10 14:44:46,712 - INFO: Seg loss: 0.2790327047984494
2026-10-10 14:44:46,712 - INFO: λ_rec: 1
2026-10-10 14:44:46,712 - INFO: λ_seg: 0.0001
2026-10-10 14:46:03,220 - INFO: -------------------Epoch: 465------------------------
2026-10-10 14:46:03,224 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.237196  0.975219  0.000125
2026-10-10 14:46:03,231 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995543  0.997717  0.997106  0.998428  0.995745
real potato   0.402951  0.574392  0.973492  0.407422  0.999278
fake potato   0.662224  0.796745  0.991272  0.666108  0.999753
real apple    0.704792  0.826787  0.783832  0.874834  0.998736
fake apple    0.642725  0.782463  0.988162  0.647713  0.998641
real orange   0.907928  0.951693  0.994698  0.912344  0.999878
fake orange   0.927429  0.962298  0.951592  0.973350  0.999782
real grape    0.810564  0.895322  0.930898  0.862457  0.999579
fake grape    0.891137  0.942385  0.911540  0.975498  0.999559
real lemon    0.647330  0.785866  0.671389  0.947546  0.999393
fake lemon    0.860318  0.924865  0.996833  0.862676  0.999704
real avocado  0.849325  0.918474  0.871481  0.970936  0.999840
fake avocado  0.673212  0.804646  0.999811  0.673298  0.999609
real pepper   0.768978  0.869354  0.804177  0.946145  0.998960
fake pepper   0.572924  0.728436  0.956006  0.588439  0.998954
real plant    0.866987  0.928705  0.960917  0.898676  0.998621
fake plant    0.818273  0.900005  0.864021  0.939225  0.999834
real banana   0.624477  0.768785  0.854321  0.698900  0.999056
fake banana   0.730848  0.844447  0.833845  0.855425  0.999420
real onion    0.633620  0.775675  0.698499  0.872150  0.999544
fake onion    0.937140  0.967500  0.991622  0.944619  0.999960
real unknown  0.909348  0.952472  0.988706  0.918893  0.999985
fake unknown  0.227051  0.370039  0.248267  0.726548  0.997916
total         0.741962  0.837786  0.880978  0.833114  0.999206
total(-bg)    0.730436  0.830516  0.875699  0.825600  0.999364
2026-10-10 14:46:03,689 - INFO: Epoch accounting: {'epoch': 465, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11244821, 57489, 52267, 129929, 171606, 88738, 82048, 158232, 165659, 79605, 67136, 35197, 31248, 225781, 134294, 150049, 17620, 98792, 66495, 86502, 37262, 10401, 47101], 'crops_with_class': [202, 32, 26, 34, 44, 30, 27, 29, 34, 37, 28, 12, 13, 54, 33, 21, 20, 25, 26, 34, 20, 11, 19], 'targeted_crops_by_class': [0, 8, 4, 8, 9, 1, 1, 3, 6, 4, 6, 1, 3, 3, 3, 5, 5, 5, 2, 5, 5, 4, 4], 'sampled_scene_counts': [0, 1, 1, 1, 1, 1, 2, 2, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 3, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 1, 1, 1, 0, 1, 2, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0, 4, 4, 4, 1, 0, 2, 1, 1, 1, 0, 1, 3, 2, 1, 1, 1, 0, 1, 2, 1, 1, 3, 1, 0, 2, 3, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 4, 0, 2, 3, 2, 3, 1, 3, 2, 2, 1, 2, 1, 1, 3, 1, 1, 1, 1, 0, 0, 1, 0, 1, 2, 0, 2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 1, 0, 2], 'learning_rate': 1.5204722197694579e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005759315283267094, 'train_segmentation_loss': 0.2790327047984494, 'val_foreground_miou_all22': 0.7304355432093651, 'val_psnr_ref1': 39.237195892333986, 'elapsed_seconds': 325.3887882232666, 'peak_cuda_allocated_gib': 7.513217926025391}

Epoch 466/500 | Batch 10/202 | Rec 0.000488 | Seg 0.254846 | Elapsed 0.2m | ETA 4.1m
Epoch 466/500 | Batch 20/202 | Rec 0.000531 | Seg 0.275186 | Elapsed 0.4m | ETA 3.8m
Epoch 466/500 | Batch 30/202 | Rec 0.000541 | Seg 0.286289 | Elapsed 0.6m | ETA 3.5m
Epoch 466/500 | Batch 40/202 | Rec 0.000551 | Seg 0.275466 | Elapsed 0.8m | ETA 3.3m
Epoch 466/500 | Batch 50/202 | Rec 0.000544 | Seg 0.268872 | Elapsed 1.0m | ETA 3.1m
Epoch 466/500 | Batch 60/202 | Rec 0.000552 | Seg 0.265492 | Elapsed 1.2m | ETA 2.9m
Epoch 466/500 | Batch 70/202 | Rec 0.000545 | Seg 0.261319 | Elapsed 1.4m | ETA 2.7m
Epoch 466/500 | Batch 80/202 | Rec 0.000530 | Seg 0.253959 | Elapsed 1.6m | ETA 2.5m
Epoch 466/500 | Batch 90/202 | Rec 0.000533 | Seg 0.254420 | Elapsed 1.8m | ETA 2.3m
Epoch 466/500 | Batch 100/202 | Rec 0.000515 | Seg 0.250424 | Elapsed 2.1m | ETA 2.1m
Epoch 466/500 | Batch 110/202 | Rec 0.000520 | Seg 0.255847 | Elapsed 2.2m | ETA 1.9m
Epoch 466/500 | Batch 120/202 | Rec 0.000531 | Seg 0.261617 | Elapsed 2.5m | ETA 1.7m
Epoch 466/500 | Batch 130/202 | Rec 0.000533 | Seg 0.263657 | Elapsed 2.7m | ETA 1.5m
Epoch 466/500 | Batch 140/202 | Rec 0.000539 | Seg 0.268998 | Elapsed 2.9m | ETA 1.3m
Epoch 466/500 | Batch 150/202 | Rec 0.000535 | Seg 0.264829 | Elapsed 3.1m | ETA 1.1m
Epoch 466/500 | Batch 160/202 | Rec 0.000534 | Seg 0.262495 | Elapsed 3.3m | ETA 0.9m
Epoch 466/500 | Batch 170/202 | Rec 0.000532 | Seg 0.263456 | Elapsed 3.5m | ETA 0.7m
Epoch 466/500 | Batch 180/202 | Rec 0.000532 | Seg 0.263658 | Elapsed 3.7m | ETA 0.5m
Epoch 466/500 | Batch 190/202 | Rec 0.000536 | Seg 0.265082 | Elapsed 3.9m | ETA 0.2m
Epoch 466/500 | Batch 200/202 | Rec 0.000538 | Seg 0.267588 | Elapsed 4.1m | ETA 0.0m
Epoch 466/500 | Batch 202/202 | Rec 0.000539 | Seg 0.268065 | Elapsed 4.1m | ETA 0.0m

2026-10-10 14:50:12,141 - INFO: Rec loss: 0.0005389575709330637
2026-10-10 14:50:12,141 - INFO: Seg loss: 0.2680648805223184
2026-10-10 14:50:12,141 - INFO: λ_rec: 1
2026-10-10 14:50:12,141 - INFO: λ_seg: 0.0001
2026-10-10 14:51:31,804 - INFO: -------------------Epoch: 466------------------------
2026-10-10 14:51:31,808 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.025499  0.974917  0.000131
2026-10-10 14:51:31,814 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995655  0.997773  0.997344  0.998302  0.995853
real potato   0.880734  0.936535  0.897406  0.979342  0.999841
fake potato   0.948893  0.973727  0.960098  0.987851  0.999961
real apple    0.732508  0.845555  0.984832  0.740867  0.999067
fake apple    0.554624  0.713469  0.987706  0.558479  0.998307
real orange   0.913555  0.954775  0.994979  0.917786  0.999886
fake orange   0.929371  0.963343  0.949529  0.977668  0.999787
real grape    0.754545  0.860054  0.959176  0.779580  0.999471
fake grape    0.900381  0.947530  0.922728  0.973807  0.999601
real lemon    0.703042  0.825581  0.862088  0.792132  0.999607
fake lemon    0.825453  0.904332  0.995580  0.828489  0.999629
real avocado  0.958736  0.978883  0.997105  0.961412  0.999962
fake avocado  0.535323  0.697297  1.000000  0.535323  0.999444
real pepper   0.845906  0.916471  0.864421  0.975305  0.999350
fake pepper   0.765501  0.867127  0.944688  0.801421  0.999415
real plant    0.864907  0.927511  0.948069  0.907920  0.998582
fake plant    0.794492  0.885428  0.841242  0.934624  0.999808
real banana   0.762195  0.865002  0.857038  0.873217  0.999388
fake banana   0.629439  0.772534  0.693612  0.871848  0.999056
real onion    0.587251  0.739913  0.597179  0.972471  0.999382
fake onion    0.875055  0.933315  0.906357  0.962031  0.999913
real unknown  0.594645  0.745754  0.631196  0.911259  0.999901
fake unknown  0.181540  0.307256  0.203987  0.622600  0.997635
total         0.762337  0.850398  0.869407  0.863641  0.999254
total(-bg)    0.751732  0.843700  0.863592  0.857520  0.999409
2026-10-10 14:51:32,270 - INFO: Epoch accounting: {'epoch': 466, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11328532, 65700, 69853, 146158, 114962, 77972, 73257, 138641, 179400, 54956, 57438, 31870, 34367, 234350, 114791, 95804, 18125, 96169, 87088, 86787, 76678, 13083, 42291], 'crops_with_class': [202, 37, 31, 38, 29, 25, 23, 27, 35, 23, 22, 10, 11, 61, 27, 12, 17, 29, 40, 38, 35, 13, 22], 'targeted_crops_by_class': [0, 4, 7, 11, 4, 2, 4, 4, 3, 2, 4, 3, 6, 6, 3, 2, 3, 4, 5, 3, 8, 7, 5], 'sampled_scene_counts': [0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 2, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 4, 0, 1, 0, 1, 0, 0, 0, 1, 0, 3, 0, 0, 1, 2, 2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 2, 2, 0, 1, 1, 2, 0, 2, 1, 1, 0, 2, 1, 2, 1, 0, 0, 1, 3, 0, 1, 2, 1, 2, 1, 0, 2, 3, 2, 1, 3, 2, 5, 3, 0, 0, 2, 2, 1, 1, 3, 4, 1, 1, 3, 1, 2, 0, 4, 1, 0, 1, 1, 0, 2, 2, 2, 1, 2, 1, 0, 2, 1, 3, 2, 1, 1, 1, 2, 0, 3, 1, 0, 3], 'learning_rate': 1.4511514983049748e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005389575709330637, 'train_segmentation_loss': 0.2680648805223184, 'val_foreground_miou_all22': 0.751731626208005, 'val_psnr_ref1': 39.02549911499023, 'elapsed_seconds': 328.57329535484314, 'peak_cuda_allocated_gib': 7.509311676025391}

Epoch 467/500 | Batch 10/202 | Rec 0.000587 | Seg 0.299348 | Elapsed 0.2m | ETA 3.9m
Epoch 467/500 | Batch 20/202 | Rec 0.000610 | Seg 0.309506 | Elapsed 0.4m | ETA 3.7m
Epoch 467/500 | Batch 30/202 | Rec 0.000579 | Seg 0.311288 | Elapsed 0.6m | ETA 3.5m
Epoch 467/500 | Batch 40/202 | Rec 0.000583 | Seg 0.308036 | Elapsed 0.8m | ETA 3.3m
Epoch 467/500 | Batch 50/202 | Rec 0.000575 | Seg 0.298696 | Elapsed 1.0m | ETA 3.1m
Epoch 467/500 | Batch 60/202 | Rec 0.000565 | Seg 0.289898 | Elapsed 1.2m | ETA 2.9m
Epoch 467/500 | Batch 70/202 | Rec 0.000537 | Seg 0.271486 | Elapsed 1.4m | ETA 2.7m
Epoch 467/500 | Batch 80/202 | Rec 0.000566 | Seg 0.268393 | Elapsed 1.6m | ETA 2.5m
Epoch 467/500 | Batch 90/202 | Rec 0.000574 | Seg 0.272526 | Elapsed 1.8m | ETA 2.3m
Epoch 467/500 | Batch 100/202 | Rec 0.000589 | Seg 0.273520 | Elapsed 2.0m | ETA 2.1m
Epoch 467/500 | Batch 110/202 | Rec 0.000587 | Seg 0.274145 | Elapsed 2.2m | ETA 1.9m
Epoch 467/500 | Batch 120/202 | Rec 0.000585 | Seg 0.278061 | Elapsed 2.4m | ETA 1.7m
Epoch 467/500 | Batch 130/202 | Rec 0.000581 | Seg 0.276728 | Elapsed 2.6m | ETA 1.5m
Epoch 467/500 | Batch 140/202 | Rec 0.000583 | Seg 0.276188 | Elapsed 2.8m | ETA 1.3m
Epoch 467/500 | Batch 150/202 | Rec 0.000582 | Seg 0.277502 | Elapsed 3.1m | ETA 1.1m
Epoch 467/500 | Batch 160/202 | Rec 0.000580 | Seg 0.278612 | Elapsed 3.3m | ETA 0.9m
Epoch 467/500 | Batch 170/202 | Rec 0.000577 | Seg 0.278930 | Elapsed 3.5m | ETA 0.7m
Epoch 467/500 | Batch 180/202 | Rec 0.000575 | Seg 0.275793 | Elapsed 3.7m | ETA 0.4m
Epoch 467/500 | Batch 190/202 | Rec 0.000570 | Seg 0.275914 | Elapsed 3.9m | ETA 0.2m
Epoch 467/500 | Batch 200/202 | Rec 0.000575 | Seg 0.276193 | Elapsed 4.1m | ETA 0.0m
Epoch 467/500 | Batch 202/202 | Rec 0.000574 | Seg 0.275747 | Elapsed 4.1m | ETA 0.0m

2026-10-10 14:55:38,816 - INFO: Rec loss: 0.0005737270083333744
2026-10-10 14:55:38,816 - INFO: Seg loss: 0.2757466270929516
2026-10-10 14:55:38,816 - INFO: λ_rec: 1
2026-10-10 14:55:38,816 - INFO: λ_seg: 0.0001
2026-10-10 14:56:55,870 - INFO: -------------------Epoch: 467------------------------
2026-10-10 14:56:55,875 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.072386  0.975008  0.000129
2026-10-10 14:56:55,884 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995503  0.997697  0.997001  0.998494  0.995706
real potato   0.903755  0.949395  0.924387  0.975899  0.999876
fake potato   0.970128  0.984787  0.983295  0.986385  0.999978
real apple    0.745995  0.854472  0.975865  0.760018  0.999107
fake apple    0.575549  0.730555  0.989843  0.578969  0.998388
real orange   0.916532  0.956399  0.995243  0.920565  0.999890
fake orange   0.933483  0.965547  0.954583  0.976868  0.999801
real grape    0.723791  0.839717  0.934600  0.762406  0.999393
fake grape    0.903208  0.949093  0.928473  0.970754  0.999615
real lemon    0.799563  0.888569  0.925478  0.854583  0.999748
fake lemon    0.768427  0.869002  0.998689  0.769203  0.999510
real avocado  0.959568  0.979317  0.996769  0.962562  0.999962
fake avocado  0.515047  0.679864  1.000000  0.515047  0.999420
real pepper   0.815384  0.898255  0.833060  0.974637  0.999193
fake pepper   0.685651  0.813466  0.943183  0.715191  0.999218
real plant    0.847526  0.917421  0.945629  0.890942  0.998397
fake plant    0.769333  0.869580  0.849515  0.890721  0.999787
real banana   0.793139  0.884587  0.874627  0.894880  0.999476
fake banana   0.666539  0.799859  0.740673  0.869443  0.999200
real onion    0.603562  0.752729  0.613852  0.972978  0.999423
fake onion    0.932613  0.965082  0.969727  0.960580  0.999956
real unknown  0.551585  0.710948  0.582117  0.913168  0.999881
fake unknown  0.202658  0.336980  0.222623  0.693227  0.997702
total         0.764284  0.851884  0.877358  0.861196  0.999245
total(-bg)    0.753774  0.845256  0.871920  0.854956  0.999405
2026-10-10 14:56:56,386 - INFO: Epoch accounting: {'epoch': 467, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11254379, 58929, 48497, 119315, 144962, 83825, 68039, 156730, 199955, 58935, 57003, 47503, 49591, 249908, 155151, 134465, 20036, 64080, 66309, 74521, 56075, 11871, 58193], 'crops_with_class': [202, 33, 23, 31, 38, 24, 23, 26, 33, 28, 23, 15, 19, 60, 38, 14, 21, 18, 30, 34, 27, 14, 25], 'targeted_crops_by_class': [0, 4, 3, 6, 6, 5, 5, 8, 3, 2, 5, 3, 8, 3, 7, 6, 7, 2, 5, 6, 4, 7, 5], 'sampled_scene_counts': [0, 1, 1, 1, 1, 1, 2, 1, 2, 0, 2, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 2, 0, 2, 0, 0, 1, 0, 1, 1, 2, 1, 1, 1, 2, 0, 0, 1, 0, 1, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 3, 1, 1, 0, 2, 0, 1, 1, 2, 3, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 2, 2, 1, 3, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 0, 1, 2, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 3, 2, 1, 0, 3, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 0, 1, 1, 1, 3, 2, 1, 0, 1, 2, 0, 1, 7, 2, 1, 1, 2, 1, 3, 2, 0, 2, 1, 1, 1, 2, 0, 2, 0, 1, 0, 3, 2, 0, 1, 0, 2, 2, 0, 0, 2, 2, 1, 2, 1, 1, 0, 1, 1, 3, 1, 1, 1, 1, 3], 'learning_rate': 1.3837523370363479e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005737270083333744, 'train_segmentation_loss': 0.2757466270929516, 'val_foreground_miou_all22': 0.7537743665673783, 'val_psnr_ref1': 39.072386474609374, 'elapsed_seconds': 324.1093361377716, 'peak_cuda_allocated_gib': 7.516147613525391}

Epoch 468/500 | Batch 10/202 | Rec 0.000682 | Seg 0.302593 | Elapsed 0.2m | ETA 3.9m
Epoch 468/500 | Batch 20/202 | Rec 0.000627 | Seg 0.311002 | Elapsed 0.4m | ETA 3.7m
Epoch 468/500 | Batch 30/202 | Rec 0.000617 | Seg 0.307334 | Elapsed 0.6m | ETA 3.5m
Epoch 468/500 | Batch 40/202 | Rec 0.000640 | Seg 0.321902 | Elapsed 0.8m | ETA 3.3m
Epoch 468/500 | Batch 50/202 | Rec 0.000626 | Seg 0.312133 | Elapsed 1.0m | ETA 3.1m
Epoch 468/500 | Batch 60/202 | Rec 0.000624 | Seg 0.316899 | Elapsed 1.2m | ETA 2.9m
Epoch 468/500 | Batch 70/202 | Rec 0.000595 | Seg 0.302097 | Elapsed 1.4m | ETA 2.7m
Epoch 468/500 | Batch 80/202 | Rec 0.000583 | Seg 0.296742 | Elapsed 1.6m | ETA 2.5m
Epoch 468/500 | Batch 90/202 | Rec 0.000606 | Seg 0.297421 | Elapsed 1.8m | ETA 2.3m
Epoch 468/500 | Batch 100/202 | Rec 0.000590 | Seg 0.286200 | Elapsed 2.0m | ETA 2.1m
Epoch 468/500 | Batch 110/202 | Rec 0.000598 | Seg 0.282035 | Elapsed 2.3m | ETA 1.9m
Epoch 468/500 | Batch 120/202 | Rec 0.000601 | Seg 0.280440 | Elapsed 2.5m | ETA 1.7m
Epoch 468/500 | Batch 130/202 | Rec 0.000592 | Seg 0.277550 | Elapsed 2.7m | ETA 1.5m
Epoch 468/500 | Batch 140/202 | Rec 0.000588 | Seg 0.276235 | Elapsed 2.9m | ETA 1.3m
Epoch 468/500 | Batch 150/202 | Rec 0.000588 | Seg 0.273968 | Elapsed 3.1m | ETA 1.1m
Epoch 468/500 | Batch 160/202 | Rec 0.000587 | Seg 0.273496 | Elapsed 3.3m | ETA 0.9m
Epoch 468/500 | Batch 170/202 | Rec 0.000598 | Seg 0.277510 | Elapsed 3.5m | ETA 0.7m
Epoch 468/500 | Batch 180/202 | Rec 0.000594 | Seg 0.276623 | Elapsed 3.7m | ETA 0.5m
Epoch 468/500 | Batch 190/202 | Rec 0.000605 | Seg 0.278009 | Elapsed 3.9m | ETA 0.2m
Epoch 468/500 | Batch 200/202 | Rec 0.000598 | Seg 0.277928 | Elapsed 4.1m | ETA 0.0m
Epoch 468/500 | Batch 202/202 | Rec 0.000596 | Seg 0.276755 | Elapsed 4.1m | ETA 0.0m

2026-10-10 15:01:04,825 - INFO: Rec loss: 0.000596070046782134
2026-10-10 15:01:04,825 - INFO: Seg loss: 0.27675496071282
2026-10-10 15:01:04,826 - INFO: λ_rec: 1
2026-10-10 15:01:04,826 - INFO: λ_seg: 0.0001
2026-10-10 15:02:23,470 - INFO: -------------------Epoch: 468------------------------
2026-10-10 15:02:23,473 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.169646  0.975047  0.000127
2026-10-10 15:02:23,480 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995632  0.997761  0.996949  0.998676  0.995829
real potato   0.487378  0.655307  0.960591  0.497322  0.999374
fake potato   0.793923  0.885075  0.983611  0.804566  0.999848
real apple    0.728156  0.842647  0.824151  0.862096  0.998890
fake apple    0.582650  0.736250  0.990167  0.586041  0.998415
real orange   0.941536  0.969838  0.995610  0.945461  0.999923
fake orange   0.944104  0.971199  0.964033  0.978574  0.999834
real grape    0.821499  0.901953  0.921213  0.883578  0.999599
fake grape    0.905849  0.950549  0.934590  0.967166  0.999628
real lemon    0.564837  0.721864  0.583167  0.947286  0.999142
fake lemon    0.846325  0.916718  0.996528  0.848828  0.999674
real avocado  0.861746  0.925690  0.888553  0.966174  0.999856
fake avocado  0.754236  0.859854  0.998819  0.754909  0.999706
real pepper   0.790880  0.883181  0.831351  0.942016  0.999089
fake pepper   0.645618  0.784602  0.937228  0.674797  0.999117
real plant    0.869265  0.930011  0.962544  0.899698  0.998647
fake plant    0.750859  0.857654  0.801667  0.922163  0.999756
real banana   0.524949  0.688433  0.889618  0.561524  0.998858
fake banana   0.741317  0.851394  0.865940  0.837425  0.999462
real onion    0.670183  0.802477  0.723329  0.901199  0.999599
fake onion    0.928178  0.962701  0.989283  0.937606  0.999954
real unknown  0.880435  0.936366  0.945525  0.927481  0.999980
fake unknown  0.214194  0.352779  0.236517  0.694133  0.997854
total         0.749728  0.842796  0.879173  0.840814  0.999219
total(-bg)    0.738551  0.835752  0.873820  0.833638  0.999373
2026-10-10 15:02:23,937 - INFO: Epoch accounting: {'epoch': 468, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11245509, 56585, 57334, 106756, 136902, 92608, 67184, 157114, 234891, 61964, 64691, 54011, 40771, 217802, 150528, 123596, 24035, 77287, 64852, 75155, 66213, 12957, 49527], 'crops_with_class': [202, 33, 27, 32, 37, 27, 25, 33, 41, 27, 25, 18, 15, 56, 37, 13, 21, 22, 27, 33, 28, 14, 21], 'targeted_crops_by_class': [0, 3, 4, 3, 2, 1, 7, 3, 5, 6, 3, 4, 5, 4, 6, 3, 8, 8, 3, 5, 4, 7, 10], 'sampled_scene_counts': [1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 2, 1, 0, 1, 1, 2, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, 1, 0, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 2, 2, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 3, 1, 2, 2, 1, 4, 2, 1, 1, 2, 0, 0, 1, 3, 1, 1, 2, 3, 3, 0, 2, 1, 0, 0, 4, 1, 3, 1, 0, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 4, 3, 3, 1, 2, 1, 2, 1, 1, 0, 1, 2, 2, 3, 1, 2, 0, 3, 1, 0, 2, 1, 0, 1, 4, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 1, 1, 2, 2, 2, 4, 1, 2], 'learning_rate': 1.3182773967670786e-06, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000596070046782134, 'train_segmentation_loss': 0.27675496071282, 'val_foreground_miou_all22': 0.738550801949298, 'val_psnr_ref1': 39.16964569091797, 'elapsed_seconds': 327.5439808368683, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 469/500 | Batch 10/202 | Rec 0.000769 | Seg 0.340257 | Elapsed 0.2m | ETA 4.0m
Epoch 469/500 | Batch 20/202 | Rec 0.000637 | Seg 0.304590 | Elapsed 0.4m | ETA 3.7m
Epoch 469/500 | Batch 30/202 | Rec 0.000619 | Seg 0.305428 | Elapsed 0.6m | ETA 3.5m
Epoch 469/500 | Batch 40/202 | Rec 0.000587 | Seg 0.287327 | Elapsed 0.8m | ETA 3.3m
Epoch 469/500 | Batch 50/202 | Rec 0.000579 | Seg 0.286185 | Elapsed 1.0m | ETA 3.1m
Epoch 469/500 | Batch 60/202 | Rec 0.000579 | Seg 0.279136 | Elapsed 1.2m | ETA 2.9m
Epoch 469/500 | Batch 70/202 | Rec 0.000584 | Seg 0.279842 | Elapsed 1.4m | ETA 2.7m
Epoch 469/500 | Batch 80/202 | Rec 0.000579 | Seg 0.277908 | Elapsed 1.6m | ETA 2.5m
Epoch 469/500 | Batch 90/202 | Rec 0.000581 | Seg 0.281157 | Elapsed 1.8m | ETA 2.3m
Epoch 469/500 | Batch 100/202 | Rec 0.000563 | Seg 0.277824 | Elapsed 2.1m | ETA 2.1m
Epoch 469/500 | Batch 110/202 | Rec 0.000563 | Seg 0.279453 | Elapsed 2.3m | ETA 1.9m
Epoch 469/500 | Batch 120/202 | Rec 0.000566 | Seg 0.283024 | Elapsed 2.5m | ETA 1.7m
Epoch 469/500 | Batch 130/202 | Rec 0.000568 | Seg 0.284893 | Elapsed 2.7m | ETA 1.5m
Epoch 469/500 | Batch 140/202 | Rec 0.000585 | Seg 0.288983 | Elapsed 2.9m | ETA 1.3m
Epoch 469/500 | Batch 150/202 | Rec 0.000584 | Seg 0.287551 | Elapsed 3.1m | ETA 1.1m
Epoch 469/500 | Batch 160/202 | Rec 0.000597 | Seg 0.289923 | Elapsed 3.3m | ETA 0.9m
Epoch 469/500 | Batch 170/202 | Rec 0.000598 | Seg 0.286995 | Elapsed 3.5m | ETA 0.7m
Epoch 469/500 | Batch 180/202 | Rec 0.000597 | Seg 0.285577 | Elapsed 3.7m | ETA 0.5m
Epoch 469/500 | Batch 190/202 | Rec 0.000600 | Seg 0.288052 | Elapsed 3.9m | ETA 0.2m
Epoch 469/500 | Batch 200/202 | Rec 0.000598 | Seg 0.285879 | Elapsed 4.1m | ETA 0.0m
Epoch 469/500 | Batch 202/202 | Rec 0.000597 | Seg 0.285201 | Elapsed 4.2m | ETA 0.0m

2026-10-10 15:06:33,262 - INFO: Rec loss: 0.0005969006456100465
2026-10-10 15:06:33,262 - INFO: Seg loss: 0.28520071063891494
2026-10-10 15:06:33,262 - INFO: λ_rec: 1
2026-10-10 15:06:33,262 - INFO: λ_seg: 0.0001
2026-10-10 15:07:50,994 - INFO: -------------------Epoch: 469------------------------
2026-10-10 15:07:50,998 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.099151  0.975027  0.000129
2026-10-10 15:07:51,005 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995870  0.997881  0.997403  0.998459  0.996058
real potato   0.294568  0.455048  1.000000  0.294568  0.999156
fake potato   0.656152  0.792334  0.995878  0.657939  0.999749
real apple    0.690990  0.817212  0.751354  0.895843  0.998618
fake apple    0.632127  0.774557  0.979127  0.640761  0.998592
real orange   0.912432  0.954161  0.994599  0.916975  0.999884
fake orange   0.938786  0.968377  0.952430  0.984970  0.999816
real grape    0.853464  0.920889  0.944462  0.898560  0.999678
fake grape    0.886579  0.939830  0.907450  0.974714  0.999539
real lemon    0.411430  0.582955  0.420789  0.948715  0.998405
fake lemon    0.868291  0.929453  0.992627  0.873927  0.999720
real avocado  0.765507  0.867132  0.784963  0.968637  0.999724
fake avocado  0.820510  0.901357  0.998759  0.821347  0.999785
real pepper   0.798433  0.887871  0.855667  0.922701  0.999148
fake pepper   0.650940  0.788521  0.955531  0.671276  0.999142
real plant    0.880619  0.936470  0.954085  0.919591  0.998753
fake plant    0.820238  0.901193  0.878987  0.924655  0.999839
real banana   0.236697  0.382753  0.808940  0.250713  0.998183
fake banana   0.737441  0.848832  0.847898  0.849867  0.999443
real onion    0.592794  0.744295  0.733246  0.755784  0.999531
fake onion    0.915666  0.955926  0.992965  0.921644  0.999946
real unknown  0.921201  0.958934  0.982000  0.937023  0.999987
fake unknown  0.238228  0.384750  0.257560  0.760413  0.997951
total         0.718216  0.812640  0.868988  0.816917  0.999159
total(-bg)    0.705595  0.804220  0.863151  0.808665  0.999300
2026-10-10 15:07:51,471 - INFO: Epoch accounting: {'epoch': 469, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11213889, 64297, 67840, 61495, 143663, 90436, 76187, 149905, 201440, 72967, 56639, 49284, 45183, 226360, 122910, 222408, 32128, 75532, 79891, 67271, 68850, 8567, 41130], 'crops_with_class': [202, 34, 33, 20, 36, 24, 26, 24, 35, 27, 24, 17, 16, 53, 27, 31, 23, 20, 32, 31, 30, 8, 17], 'targeted_crops_by_class': [0, 6, 2, 2, 5, 4, 5, 3, 8, 3, 5, 4, 5, 6, 7, 10, 2, 2, 5, 1, 6, 4, 2], 'sampled_scene_counts': [1, 1, 1, 0, 1, 3, 1, 1, 1, 0, 2, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2, 1, 1, 0, 3, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 2, 3, 1, 1, 1, 1, 0, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 2, 0, 2, 0, 1, 1, 0, 1, 2, 1, 0, 2, 2, 2, 0, 1, 0, 1, 1, 2, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 2, 1, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 4, 1, 2, 0, 2, 1, 1, 1, 0, 2, 4, 1, 2, 1, 2, 1, 1, 3, 2, 0, 0, 0, 1, 0, 0, 1, 3, 0, 0, 1, 2, 0, 1, 1, 1, 1, 4, 2, 2, 2, 2, 1, 3, 1, 2, 1, 1, 1, 0, 0, 0, 1, 3, 0, 0, 1, 1, 2, 0, 2, 1, 1, 3, 2, 2, 3, 3, 2, 0, 1, 1, 1, 3, 2, 4, 1, 0, 1], 'learning_rate': 1.254729262335686e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005969006456100465, 'train_segmentation_loss': 0.28520071063891494, 'val_foreground_miou_all22': 0.7055950935268313, 'val_psnr_ref1': 39.09915100097656, 'elapsed_seconds': 327.5266623497009, 'peak_cuda_allocated_gib': 7.510318756103516}

Epoch 470/500 | Batch 10/202 | Rec 0.000600 | Seg 0.367422 | Elapsed 0.2m | ETA 3.9m
Epoch 470/500 | Batch 20/202 | Rec 0.000570 | Seg 0.300445 | Elapsed 0.4m | ETA 3.7m
Epoch 470/500 | Batch 30/202 | Rec 0.000569 | Seg 0.300873 | Elapsed 0.6m | ETA 3.5m
Epoch 470/500 | Batch 40/202 | Rec 0.000584 | Seg 0.299225 | Elapsed 0.8m | ETA 3.3m
Epoch 470/500 | Batch 50/202 | Rec 0.000551 | Seg 0.278814 | Elapsed 1.0m | ETA 3.1m
Epoch 470/500 | Batch 60/202 | Rec 0.000569 | Seg 0.275988 | Elapsed 1.2m | ETA 2.9m
Epoch 470/500 | Batch 70/202 | Rec 0.000570 | Seg 0.274546 | Elapsed 1.4m | ETA 2.7m
Epoch 470/500 | Batch 80/202 | Rec 0.000566 | Seg 0.280465 | Elapsed 1.6m | ETA 2.5m
Epoch 470/500 | Batch 90/202 | Rec 0.000561 | Seg 0.280790 | Elapsed 1.8m | ETA 2.3m
Epoch 470/500 | Batch 100/202 | Rec 0.000578 | Seg 0.285159 | Elapsed 2.0m | ETA 2.1m
Epoch 470/500 | Batch 110/202 | Rec 0.000573 | Seg 0.278236 | Elapsed 2.3m | ETA 1.9m
Epoch 470/500 | Batch 120/202 | Rec 0.000579 | Seg 0.279066 | Elapsed 2.5m | ETA 1.7m
Epoch 470/500 | Batch 130/202 | Rec 0.000580 | Seg 0.280735 | Elapsed 2.7m | ETA 1.5m
Epoch 470/500 | Batch 140/202 | Rec 0.000580 | Seg 0.282875 | Elapsed 2.9m | ETA 1.3m
Epoch 470/500 | Batch 150/202 | Rec 0.000572 | Seg 0.278396 | Elapsed 3.1m | ETA 1.1m
Epoch 470/500 | Batch 160/202 | Rec 0.000578 | Seg 0.281812 | Elapsed 3.3m | ETA 0.9m
Epoch 470/500 | Batch 170/202 | Rec 0.000583 | Seg 0.286279 | Elapsed 3.5m | ETA 0.7m
Epoch 470/500 | Batch 180/202 | Rec 0.000582 | Seg 0.286531 | Elapsed 3.7m | ETA 0.5m
Epoch 470/500 | Batch 190/202 | Rec 0.000583 | Seg 0.285466 | Elapsed 3.9m | ETA 0.2m
Epoch 470/500 | Batch 200/202 | Rec 0.000585 | Seg 0.284906 | Elapsed 4.1m | ETA 0.0m
Epoch 470/500 | Batch 202/202 | Rec 0.000582 | Seg 0.283366 | Elapsed 4.1m | ETA 0.0m

2026-10-10 15:11:59,881 - INFO: Rec loss: 0.0005817369105222884
2026-10-10 15:11:59,881 - INFO: Seg loss: 0.2833662692014829
2026-10-10 15:11:59,882 - INFO: λ_rec: 1
2026-10-10 15:11:59,882 - INFO: λ_seg: 0.0001
2026-10-10 15:13:18,229 - INFO: -------------------Epoch: 470------------------------
2026-10-10 15:13:18,232 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.996265  0.974887  0.000132
2026-10-10 15:13:18,238 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995736  0.997813  0.997295  0.998432  0.995929
real potato   0.470522  0.639894  0.962366  0.479342  0.999355
fake potato   0.690185  0.816649  0.986651  0.696690  0.999772
real apple    0.694768  0.819848  0.800270  0.840513  0.998726
fake apple    0.641151  0.781295  0.984819  0.647551  0.998632
real orange   0.931483  0.964476  0.994101  0.936660  0.999909
fake orange   0.941749  0.969951  0.955530  0.984916  0.999826
real grape    0.798855  0.888132  0.946655  0.836512  0.999560
fake grape    0.902447  0.948673  0.926616  0.971909  0.999611
real lemon    0.569781  0.725890  0.585228  0.955726  0.999152
fake lemon    0.864622  0.927347  0.995123  0.868301  0.999712
real avocado  0.905562  0.950391  0.936136  0.965189  0.999906
fake avocado  0.789648  0.882413  0.999677  0.789850  0.999748
real pepper   0.794972  0.885727  0.824861  0.956407  0.999098
fake pepper   0.636802  0.778057  0.948201  0.659753  0.999103
real plant    0.870175  0.930531  0.948869  0.912985  0.998638
fake plant    0.790375  0.882866  0.881061  0.884778  0.999813
real banana   0.516017  0.680706  0.854943  0.565530  0.998808
fake banana   0.742038  0.851870  0.853480  0.850365  0.999456
real onion    0.620464  0.765737  0.652401  0.926870  0.999488
fake onion    0.937305  0.967588  0.992875  0.943652  0.999960
real unknown  0.702722  0.825361  0.738149  0.936069  0.999937
fake unknown  0.238453  0.385043  0.260669  0.736690  0.998018
total         0.741123  0.837663  0.870695  0.841074  0.999224
total(-bg)    0.729550  0.830384  0.864940  0.833921  0.999374
2026-10-10 15:13:18,696 - INFO: Epoch accounting: {'epoch': 470, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11253814, 44662, 55947, 142057, 143582, 58667, 56406, 128952, 260360, 74035, 61570, 41374, 52099, 233175, 89607, 150539, 21700, 112716, 82302, 87580, 45458, 7599, 34071], 'crops_with_class': [202, 24, 26, 35, 37, 18, 21, 28, 44, 37, 29, 14, 15, 57, 25, 19, 20, 27, 32, 35, 22, 8, 14], 'targeted_crops_by_class': [0, 3, 5, 6, 6, 4, 2, 5, 6, 4, 5, 3, 5, 4, 5, 5, 3, 5, 3, 7, 4, 2, 5], 'sampled_scene_counts': [2, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 2, 2, 0, 2, 2, 3, 2, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 1, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 2, 0, 1, 0, 1, 1, 1, 3, 2, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 0, 1, 2, 1, 1, 2, 2, 1, 3, 2, 3, 1, 0, 0, 0, 4, 1, 0, 2, 0, 1, 0, 1, 2, 1, 2, 1, 1, 4, 0, 0, 2, 4, 2, 2, 0, 0, 1, 1, 3, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 3, 1, 3, 1, 5, 2, 0, 1, 0, 1, 1, 2, 3, 1], 'learning_rate': 1.1931104425137164e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005817369105222884, 'train_segmentation_loss': 0.2833662692014829, 'val_foreground_miou_all22': 0.729549799697833, 'val_psnr_ref1': 38.996265258789066, 'elapsed_seconds': 327.2177176475525, 'peak_cuda_allocated_gib': 7.511997222900391}

Epoch 471/500 | Batch 10/202 | Rec 0.000575 | Seg 0.245115 | Elapsed 0.2m | ETA 3.9m
Epoch 471/500 | Batch 20/202 | Rec 0.000548 | Seg 0.252757 | Elapsed 0.4m | ETA 3.7m
Epoch 471/500 | Batch 30/202 | Rec 0.000611 | Seg 0.246123 | Elapsed 0.6m | ETA 3.5m
Epoch 471/500 | Batch 40/202 | Rec 0.000604 | Seg 0.247250 | Elapsed 0.8m | ETA 3.3m
Epoch 471/500 | Batch 50/202 | Rec 0.000584 | Seg 0.249649 | Elapsed 1.0m | ETA 3.1m
Epoch 471/500 | Batch 60/202 | Rec 0.000586 | Seg 0.256118 | Elapsed 1.2m | ETA 2.9m
Epoch 471/500 | Batch 70/202 | Rec 0.000578 | Seg 0.254354 | Elapsed 1.4m | ETA 2.7m
Epoch 471/500 | Batch 80/202 | Rec 0.000559 | Seg 0.250910 | Elapsed 1.6m | ETA 2.5m
Epoch 471/500 | Batch 90/202 | Rec 0.000543 | Seg 0.241237 | Elapsed 1.8m | ETA 2.3m
Epoch 471/500 | Batch 100/202 | Rec 0.000564 | Seg 0.247153 | Elapsed 2.0m | ETA 2.1m
Epoch 471/500 | Batch 110/202 | Rec 0.000575 | Seg 0.249052 | Elapsed 2.2m | ETA 1.9m
Epoch 471/500 | Batch 120/202 | Rec 0.000572 | Seg 0.248433 | Elapsed 2.5m | ETA 1.7m
Epoch 471/500 | Batch 130/202 | Rec 0.000567 | Seg 0.246113 | Elapsed 2.7m | ETA 1.5m
Epoch 471/500 | Batch 140/202 | Rec 0.000561 | Seg 0.249091 | Elapsed 2.9m | ETA 1.3m
Epoch 471/500 | Batch 150/202 | Rec 0.000568 | Seg 0.255848 | Elapsed 3.1m | ETA 1.1m
Epoch 471/500 | Batch 160/202 | Rec 0.000573 | Seg 0.258682 | Elapsed 3.3m | ETA 0.9m
Epoch 471/500 | Batch 170/202 | Rec 0.000586 | Seg 0.262188 | Elapsed 3.5m | ETA 0.7m
Epoch 471/500 | Batch 180/202 | Rec 0.000593 | Seg 0.265428 | Elapsed 3.7m | ETA 0.4m
Epoch 471/500 | Batch 190/202 | Rec 0.000595 | Seg 0.267322 | Elapsed 3.9m | ETA 0.2m
Epoch 471/500 | Batch 200/202 | Rec 0.000599 | Seg 0.270401 | Elapsed 4.1m | ETA 0.0m
Epoch 471/500 | Batch 202/202 | Rec 0.000599 | Seg 0.271326 | Elapsed 4.1m | ETA 0.0m

2026-10-10 15:17:25,463 - INFO: Rec loss: 0.0005993675143028019
2026-10-10 15:17:25,463 - INFO: Seg loss: 0.2713256841802066
2026-10-10 15:17:25,463 - INFO: λ_rec: 1
2026-10-10 15:17:25,463 - INFO: λ_seg: 0.0001
2026-10-10 15:18:44,484 - INFO: -------------------Epoch: 471------------------------
2026-10-10 15:18:44,488 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.879795  0.974554  0.000135
2026-10-10 15:18:44,495 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995891  0.997892  0.997557  0.998326  0.996079
real potato   0.918994  0.957737  0.942476  0.973604  0.999897
fake potato   0.950575  0.974611  0.962615  0.987013  0.999963
real apple    0.815239  0.898167  0.981949  0.827643  0.999353
fake apple    0.566369  0.723115  0.990718  0.569391  0.998354
real orange   0.945287  0.971824  0.992278  0.952293  0.999927
fake orange   0.951297  0.974991  0.965413  0.984863  0.999856
real grape    0.804890  0.891849  0.951076  0.839655  0.999575
fake grape    0.884011  0.938385  0.904334  0.975209  0.999527
real lemon    0.615282  0.761776  0.748372  0.775773  0.999430
fake lemon    0.849739  0.918716  0.991315  0.856113  0.999680
real avocado  0.915130  0.955634  0.950024  0.961412  0.999917
fake avocado  0.505099  0.671140  0.999495  0.505228  0.999408
real pepper   0.881315  0.936864  0.906661  0.969256  0.999523
fake pepper   0.818182  0.899950  0.941604  0.861917  0.999543
real plant    0.877469  0.934686  0.956744  0.913717  0.998724
fake plant    0.714793  0.833629  0.757842  0.926380  0.999706
real banana   0.720172  0.837275  0.867108  0.809521  0.999293
fake banana   0.634183  0.776097  0.691978  0.883626  0.999062
real onion    0.662583  0.797004  0.691363  0.940888  0.999567
fake onion    0.922093  0.959418  0.960048  0.958888  0.999949
real unknown  0.872958  0.932120  0.946850  0.917939  0.999979
fake unknown  0.199662  0.332826  0.222155  0.663528  0.997759
total         0.783531  0.864161  0.883477  0.871834  0.999307
total(-bg)    0.773878  0.858083  0.878292  0.866084  0.999454
2026-10-10 15:18:44,952 - INFO: Epoch accounting: {'epoch': 471, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11342743, 56800, 61629, 103341, 123743, 55443, 56848, 112273, 143661, 72266, 45334, 48599, 38869, 219527, 138080, 193531, 27994, 80077, 112524, 92705, 63704, 8041, 40540], 'crops_with_class': [202, 36, 35, 27, 30, 20, 19, 21, 29, 33, 21, 16, 18, 57, 34, 27, 24, 22, 42, 42, 32, 9, 17], 'targeted_crops_by_class': [0, 11, 1, 5, 5, 2, 7, 5, 2, 4, 1, 4, 5, 9, 5, 10, 6, 4, 4, 6, 5, 5, 3], 'sampled_scene_counts': [2, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 3, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 0, 0, 1, 1, 1, 2, 0, 1, 1, 2, 2, 2, 1, 2, 1, 3, 1, 1, 1, 0, 0, 0, 2, 0, 1, 1, 2, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 2, 1, 2, 2, 0, 1, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 2, 3, 0, 0, 1, 1, 0, 0, 0, 3, 3, 0, 1, 0, 0, 1, 2, 2, 1, 2, 0, 1, 0, 3, 2, 2, 2, 1, 3, 0, 0, 0, 0, 2, 1, 0, 2, 0, 2, 2, 1, 4, 2, 0, 2, 2, 1, 0, 0, 2, 0, 0, 0, 3, 0, 1, 1, 1, 3, 1, 1, 1, 0, 7, 4, 3, 0, 2, 1, 4, 2, 1, 2, 2, 1, 3, 1, 0, 1, 2, 2], 'learning_rate': 1.1334233699066486e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005993675143028019, 'train_segmentation_loss': 0.2713256841802066, 'val_foreground_miou_all22': 0.7738782713571767, 'val_psnr_ref1': 38.87979461669922, 'elapsed_seconds': 326.2490801811218, 'peak_cuda_allocated_gib': 7.506626129150391}

Epoch 472/500 | Batch 10/202 | Rec 0.000459 | Seg 0.207870 | Elapsed 0.2m | ETA 4.0m
Epoch 472/500 | Batch 20/202 | Rec 0.000466 | Seg 0.223163 | Elapsed 0.4m | ETA 3.8m
Epoch 472/500 | Batch 30/202 | Rec 0.000458 | Seg 0.232761 | Elapsed 0.6m | ETA 3.5m
Epoch 472/500 | Batch 40/202 | Rec 0.000455 | Seg 0.236422 | Elapsed 0.8m | ETA 3.3m
Epoch 472/500 | Batch 50/202 | Rec 0.000488 | Seg 0.247344 | Elapsed 1.0m | ETA 3.1m
Epoch 472/500 | Batch 60/202 | Rec 0.000514 | Seg 0.250154 | Elapsed 1.2m | ETA 2.9m
Epoch 472/500 | Batch 70/202 | Rec 0.000547 | Seg 0.263495 | Elapsed 1.4m | ETA 2.7m
Epoch 472/500 | Batch 80/202 | Rec 0.000547 | Seg 0.262788 | Elapsed 1.6m | ETA 2.5m
Epoch 472/500 | Batch 90/202 | Rec 0.000541 | Seg 0.257381 | Elapsed 1.8m | ETA 2.3m
Epoch 472/500 | Batch 100/202 | Rec 0.000538 | Seg 0.255602 | Elapsed 2.0m | ETA 2.1m
Epoch 472/500 | Batch 110/202 | Rec 0.000540 | Seg 0.257162 | Elapsed 2.2m | ETA 1.9m
Epoch 472/500 | Batch 120/202 | Rec 0.000537 | Seg 0.257766 | Elapsed 2.4m | ETA 1.7m
Epoch 472/500 | Batch 130/202 | Rec 0.000543 | Seg 0.258458 | Elapsed 2.6m | ETA 1.5m
Epoch 472/500 | Batch 140/202 | Rec 0.000540 | Seg 0.257764 | Elapsed 2.9m | ETA 1.3m
Epoch 472/500 | Batch 150/202 | Rec 0.000540 | Seg 0.257153 | Elapsed 3.1m | ETA 1.1m
Epoch 472/500 | Batch 160/202 | Rec 0.000549 | Seg 0.256321 | Elapsed 3.3m | ETA 0.9m
Epoch 472/500 | Batch 170/202 | Rec 0.000558 | Seg 0.264282 | Elapsed 3.5m | ETA 0.7m
Epoch 472/500 | Batch 180/202 | Rec 0.000560 | Seg 0.264898 | Elapsed 3.7m | ETA 0.5m
Epoch 472/500 | Batch 190/202 | Rec 0.000553 | Seg 0.260949 | Elapsed 3.9m | ETA 0.2m
Epoch 472/500 | Batch 200/202 | Rec 0.000552 | Seg 0.260664 | Elapsed 4.1m | ETA 0.0m
Epoch 472/500 | Batch 202/202 | Rec 0.000550 | Seg 0.260604 | Elapsed 4.1m | ETA 0.0m

2026-10-10 15:22:53,689 - INFO: Rec loss: 0.0005503756166746987
2026-10-10 15:22:53,689 - INFO: Seg loss: 0.26060425438503226
2026-10-10 15:22:53,690 - INFO: λ_rec: 1
2026-10-10 15:22:53,690 - INFO: λ_seg: 0.0001
2026-10-10 15:24:09,568 - INFO: -------------------Epoch: 472------------------------
2026-10-10 15:24:09,572 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.054006  0.974935  0.00013
2026-10-10 15:24:09,578 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995733  0.997812  0.997292  0.998432  0.995927
real potato   0.852100  0.920095  0.967511  0.877200  0.999818
fake potato   0.900658  0.947683  0.980300  0.917260  0.999926
real apple    0.801166  0.889559  0.947379  0.838479  0.999282
fake apple    0.584232  0.737512  0.986926  0.588789  0.998418
real orange   0.926956  0.962044  0.996279  0.930176  0.999903
fake orange   0.938122  0.968023  0.956269  0.980173  0.999815
real grape    0.799703  0.888656  0.961234  0.826354  0.999568
fake grape    0.903928  0.949490  0.925447  0.974921  0.999617
real lemon    0.588183  0.740652  0.605389  0.953908  0.999215
fake lemon    0.858436  0.923776  0.995171  0.862027  0.999699
real avocado  0.923162  0.959996  0.957381  0.962726  0.999926
fake avocado  0.805761  0.892384  0.999368  0.806172  0.999767
real pepper   0.860093  0.924735  0.891491  0.960662  0.999428
fake pepper   0.783850  0.878780  0.948055  0.819026  0.999462
real plant    0.867305  0.928888  0.952243  0.906746  0.998612
fake plant    0.856130  0.922439  0.918631  0.926380  0.999876
real banana   0.553111  0.712214  0.860012  0.607836  0.998896
fake banana   0.724628  0.840279  0.814705  0.867618  0.999393
real onion    0.654515  0.791138  0.686275  0.933964  0.999555
fake onion    0.930255  0.963817  0.983392  0.945103  0.999955
real unknown  0.695035  0.820034  0.730253  0.935114  0.999934
fake unknown  0.222827  0.364408  0.244111  0.718761  0.997888
total         0.783734  0.866279  0.882831  0.875558  0.999299
total(-bg)    0.774098  0.860300  0.877628  0.869972  0.999452
2026-10-10 15:24:10,036 - INFO: Epoch accounting: {'epoch': 472, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11397671, 52422, 61075, 106934, 134421, 72254, 71404, 101048, 139677, 41810, 45177, 49870, 63629, 240868, 162999, 159388, 24949, 88201, 52922, 80760, 51055, 7372, 32366], 'crops_with_class': [202, 33, 27, 30, 34, 22, 23, 25, 30, 22, 18, 19, 20, 59, 39, 21, 27, 25, 25, 36, 23, 9, 15], 'targeted_crops_by_class': [0, 6, 6, 5, 4, 4, 4, 4, 2, 1, 3, 3, 9, 6, 9, 2, 4, 4, 1, 9, 3, 2, 2], 'sampled_scene_counts': [1, 2, 2, 0, 0, 2, 3, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 2, 0, 1, 1, 2, 2, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 2, 2, 0, 0, 1, 0, 3, 0, 3, 2, 3, 2, 3, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 2, 0, 1, 2, 0, 1, 0, 2, 1, 0, 0, 1, 1, 0, 1, 0, 2, 0, 3, 0, 0, 1, 0, 2, 2, 1, 1, 0, 0, 2, 2, 1, 3, 0, 1, 1, 4, 1, 1, 1, 1, 2, 2, 1, 1, 2, 1, 3, 1, 2, 1, 2, 3, 3, 3, 2, 0, 0, 0, 0, 1, 2, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 3, 1, 3, 1, 1, 1, 1, 2, 1, 4, 2, 2, 1], 'learning_rate': 1.0756704008579287e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005503756166746987, 'train_segmentation_loss': 0.26060425438503226, 'val_foreground_miou_all22': 0.7740980304671382, 'val_psnr_ref1': 39.0540055847168, 'elapsed_seconds': 325.0763156414032, 'peak_cuda_allocated_gib': 7.505649566650391}

Epoch 473/500 | Batch 10/202 | Rec 0.000549 | Seg 0.220589 | Elapsed 0.2m | ETA 4.2m
Epoch 473/500 | Batch 20/202 | Rec 0.000534 | Seg 0.240855 | Elapsed 0.4m | ETA 3.8m
Epoch 473/500 | Batch 30/202 | Rec 0.000534 | Seg 0.243412 | Elapsed 0.6m | ETA 3.6m
Epoch 473/500 | Batch 40/202 | Rec 0.000538 | Seg 0.256457 | Elapsed 0.8m | ETA 3.4m
Epoch 473/500 | Batch 50/202 | Rec 0.000543 | Seg 0.263600 | Elapsed 1.0m | ETA 3.1m
Epoch 473/500 | Batch 60/202 | Rec 0.000564 | Seg 0.282905 | Elapsed 1.2m | ETA 2.9m
Epoch 473/500 | Batch 70/202 | Rec 0.000565 | Seg 0.284100 | Elapsed 1.4m | ETA 2.7m
Epoch 473/500 | Batch 80/202 | Rec 0.000557 | Seg 0.278387 | Elapsed 1.6m | ETA 2.5m
Epoch 473/500 | Batch 90/202 | Rec 0.000544 | Seg 0.280351 | Elapsed 1.8m | ETA 2.3m
Epoch 473/500 | Batch 100/202 | Rec 0.000543 | Seg 0.280637 | Elapsed 2.0m | ETA 2.1m
Epoch 473/500 | Batch 110/202 | Rec 0.000546 | Seg 0.283671 | Elapsed 2.2m | ETA 1.9m
Epoch 473/500 | Batch 120/202 | Rec 0.000563 | Seg 0.293876 | Elapsed 2.4m | ETA 1.7m
Epoch 473/500 | Batch 130/202 | Rec 0.000571 | Seg 0.293292 | Elapsed 2.7m | ETA 1.5m
Epoch 473/500 | Batch 140/202 | Rec 0.000564 | Seg 0.287809 | Elapsed 2.9m | ETA 1.3m
Epoch 473/500 | Batch 150/202 | Rec 0.000560 | Seg 0.285515 | Elapsed 3.1m | ETA 1.1m
Epoch 473/500 | Batch 160/202 | Rec 0.000557 | Seg 0.284173 | Elapsed 3.3m | ETA 0.9m
Epoch 473/500 | Batch 170/202 | Rec 0.000553 | Seg 0.282370 | Elapsed 3.5m | ETA 0.7m
Epoch 473/500 | Batch 180/202 | Rec 0.000550 | Seg 0.281622 | Elapsed 3.7m | ETA 0.4m
Epoch 473/500 | Batch 190/202 | Rec 0.000557 | Seg 0.280656 | Elapsed 3.9m | ETA 0.2m
Epoch 473/500 | Batch 200/202 | Rec 0.000562 | Seg 0.282453 | Elapsed 4.1m | ETA 0.0m
Epoch 473/500 | Batch 202/202 | Rec 0.000561 | Seg 0.282826 | Elapsed 4.1m | ETA 0.0m

2026-10-10 15:28:17,540 - INFO: Rec loss: 0.0005605082390115292
2026-10-10 15:28:17,540 - INFO: Seg loss: 0.28282594870739053
2026-10-10 15:28:17,540 - INFO: λ_rec: 1
2026-10-10 15:28:17,540 - INFO: λ_seg: 0.0001
2026-10-10 15:29:39,992 - INFO: -------------------Epoch: 473------------------------
2026-10-10 15:29:39,997 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  38.89192  0.974705  0.000135
2026-10-10 15:29:40,005 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995704  0.997797  0.997356  0.998339  0.995899
real potato   0.408298  0.579805  0.995346  0.409079  0.999291
fake potato   0.663326  0.797541  0.965753  0.679305  0.999749
real apple    0.682579  0.811299  0.785842  0.838567  0.998655
fake apple    0.613425  0.760353  0.976302  0.622696  0.998518
real orange   0.919362  0.957937  0.997493  0.921491  0.999893
fake orange   0.936914  0.967380  0.950008  0.985503  0.999810
real grape    0.826771  0.905122  0.973904  0.845502  0.999630
fake grape    0.892218  0.942990  0.918377  0.969063  0.999567
real lemon    0.429320  0.600688  0.464230  0.850948  0.998671
fake lemon    0.849514  0.918585  0.964909  0.876596  0.999671
real avocado  0.930584  0.963994  0.968357  0.959770  0.999933
fake avocado  0.648693  0.786870  0.999411  0.648942  0.999579
real pepper   0.867731  0.929132  0.895030  0.966044  0.999461
fake pepper   0.800867  0.889374  0.945891  0.839319  0.999503
real plant    0.872782  0.932020  0.954890  0.910315  0.998673
fake plant    0.762482  0.865187  0.901851  0.831480  0.999794
real banana   0.392027  0.563201  0.830773  0.426049  0.998515
fake banana   0.658026  0.793696  0.724256  0.877986  0.999161
real onion    0.650448  0.788158  0.728942  0.857963  0.999583
fake onion    0.900791  0.947756  0.989992  0.909069  0.999937
real unknown  0.888486  0.940900  0.946860  0.935114  0.999981
fake unknown  0.187801  0.316180  0.206140  0.678558  0.997527
total         0.729485  0.824173  0.873127  0.819030  0.999174
total(-bg)    0.717384  0.816280  0.867480  0.810880  0.999323
2026-10-10 15:29:40,466 - INFO: Epoch accounting: {'epoch': 473, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11218939, 39589, 51834, 114374, 209415, 65554, 91056, 127171, 208436, 81955, 60140, 57593, 58072, 237810, 112389, 127871, 15857, 60412, 95684, 83118, 68002, 7792, 45209], 'crops_with_class': [202, 23, 25, 37, 51, 26, 30, 26, 36, 34, 28, 18, 22, 60, 25, 18, 14, 19, 37, 34, 28, 10, 20], 'targeted_crops_by_class': [0, 2, 2, 5, 7, 4, 5, 2, 3, 7, 6, 8, 7, 7, 2, 3, 2, 4, 10, 8, 5, 4, 6], 'sampled_scene_counts': [0, 1, 1, 1, 3, 1, 2, 2, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 2, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 2, 0, 2, 2, 2, 1, 3, 2, 2, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 2, 0, 1, 1, 3, 1, 2, 2, 1, 1, 0, 2, 2, 1, 2, 2, 2, 2, 2, 3, 0, 2, 4, 1, 2, 1, 1, 0, 3, 2, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 3, 1, 2, 1, 2, 1, 0, 1, 1, 1, 0, 4, 0, 0, 2, 0, 1, 1, 2, 2, 0, 3, 2, 1, 0, 1, 3, 1, 2, 4, 2, 2, 1, 1, 0, 1, 2, 1, 1, 0, 0, 3, 0, 1], 'learning_rate': 1.0198538153558828e-06, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005605082390115292, 'train_segmentation_loss': 0.28282594870739053, 'val_foreground_miou_all22': 0.7173839136294098, 'val_psnr_ref1': 38.89192031860352, 'elapsed_seconds': 330.42295718193054, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 474/500 | Batch 10/202 | Rec 0.000603 | Seg 0.263423 | Elapsed 0.2m | ETA 4.0m
Epoch 474/500 | Batch 20/202 | Rec 0.000602 | Seg 0.284147 | Elapsed 0.4m | ETA 3.7m
Epoch 474/500 | Batch 30/202 | Rec 0.000619 | Seg 0.295943 | Elapsed 0.6m | ETA 3.5m
Epoch 474/500 | Batch 40/202 | Rec 0.000591 | Seg 0.278333 | Elapsed 0.8m | ETA 3.4m
Epoch 474/500 | Batch 50/202 | Rec 0.000595 | Seg 0.283123 | Elapsed 1.0m | ETA 3.1m
Epoch 474/500 | Batch 60/202 | Rec 0.000584 | Seg 0.281805 | Elapsed 1.2m | ETA 2.9m
Epoch 474/500 | Batch 70/202 | Rec 0.000606 | Seg 0.279246 | Elapsed 1.4m | ETA 2.7m
Epoch 474/500 | Batch 80/202 | Rec 0.000605 | Seg 0.277464 | Elapsed 1.7m | ETA 2.5m
Epoch 474/500 | Batch 90/202 | Rec 0.000597 | Seg 0.272516 | Elapsed 1.9m | ETA 2.3m
Epoch 474/500 | Batch 100/202 | Rec 0.000594 | Seg 0.272182 | Elapsed 2.1m | ETA 2.1m
Epoch 474/500 | Batch 110/202 | Rec 0.000590 | Seg 0.272217 | Elapsed 2.3m | ETA 1.9m
Epoch 474/500 | Batch 120/202 | Rec 0.000596 | Seg 0.279458 | Elapsed 2.5m | ETA 1.7m
Epoch 474/500 | Batch 130/202 | Rec 0.000597 | Seg 0.280416 | Elapsed 2.7m | ETA 1.5m
Epoch 474/500 | Batch 140/202 | Rec 0.000588 | Seg 0.274143 | Elapsed 2.9m | ETA 1.3m
Epoch 474/500 | Batch 150/202 | Rec 0.000585 | Seg 0.271020 | Elapsed 3.1m | ETA 1.1m
Epoch 474/500 | Batch 160/202 | Rec 0.000591 | Seg 0.275845 | Elapsed 3.3m | ETA 0.9m
Epoch 474/500 | Batch 170/202 | Rec 0.000587 | Seg 0.276069 | Elapsed 3.5m | ETA 0.7m
Epoch 474/500 | Batch 180/202 | Rec 0.000583 | Seg 0.275820 | Elapsed 3.7m | ETA 0.5m
Epoch 474/500 | Batch 190/202 | Rec 0.000580 | Seg 0.276146 | Elapsed 3.9m | ETA 0.2m
Epoch 474/500 | Batch 200/202 | Rec 0.000581 | Seg 0.276160 | Elapsed 4.1m | ETA 0.0m
Epoch 474/500 | Batch 202/202 | Rec 0.000580 | Seg 0.276165 | Elapsed 4.2m | ETA 0.0m

2026-10-10 15:33:50,787 - INFO: Rec loss: 0.0005804024153218448
2026-10-10 15:33:50,787 - INFO: Seg loss: 0.2761652226200198
2026-10-10 15:33:50,787 - INFO: λ_rec: 1
2026-10-10 15:33:50,787 - INFO: λ_seg: 0.0001
2026-10-10 15:35:13,243 - INFO: -------------------Epoch: 474------------------------
2026-10-10 15:35:13,247 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.122218  0.975042  0.000128
2026-10-10 15:35:13,253 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995603  0.997747  0.997074  0.998520  0.995802
real potato   0.374984  0.545398  0.999660  0.375032  0.999252
fake potato   0.662246  0.796761  0.983990  0.669460  0.999751
real apple    0.687672  0.814886  0.757514  0.881778  0.998618
fake apple    0.578508  0.732935  0.994804  0.580262  0.998404
real orange   0.951931  0.975324  0.995299  0.956230  0.999936
fake orange   0.949259  0.973919  0.977762  0.970206  0.999852
real grape    0.871339  0.931197  0.962126  0.902288  0.999722
fake grape    0.890657  0.942117  0.909961  0.976736  0.999556
real lemon    0.472508  0.641729  0.482389  0.958452  0.998743
fake lemon    0.851567  0.919784  0.983417  0.863974  0.999681
real avocado  0.815089  0.898076  0.843921  0.959770  0.999798
fake avocado  0.779661  0.876141  0.999183  0.780158  0.999736
real pepper   0.810342  0.895187  0.854532  0.940013  0.999195
fake pepper   0.683617  0.812032  0.929155  0.721209  0.999204
real plant    0.875141  0.933364  0.968940  0.900400  0.998715
fake plant    0.779243  0.875876  0.868173  0.883819  0.999801
real banana   0.391264  0.562413  0.823791  0.427000  0.998507
fake banana   0.745933  0.854431  0.853209  0.855756  0.999464
real onion    0.594158  0.745369  0.745356  0.745482  0.999540
fake onion    0.916987  0.956646  0.994520  0.921644  0.999947
real unknown  0.923954  0.960424  0.995902  0.927481  0.999988
fake unknown  0.197047  0.329186  0.217765  0.674393  0.997684
total         0.730379  0.824823  0.875585  0.820437  0.999169
total(-bg)    0.718323  0.816963  0.870062  0.812343  0.999323
2026-10-10 15:35:13,774 - INFO: Epoch accounting: {'epoch': 474, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11272556, 57387, 58253, 113742, 117830, 96750, 75872, 183515, 202557, 88376, 51087, 41460, 37117, 201099, 122540, 130450, 20591, 87265, 81097, 81414, 55561, 15055, 46698], 'crops_with_class': [202, 31, 29, 27, 31, 26, 25, 41, 36, 37, 25, 16, 14, 53, 36, 21, 21, 24, 36, 36, 28, 17, 22], 'targeted_crops_by_class': [0, 5, 7, 5, 4, 6, 3, 3, 6, 5, 5, 3, 3, 3, 5, 5, 2, 3, 3, 8, 1, 5, 4], 'sampled_scene_counts': [1, 2, 2, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 3, 2, 0, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0, 0, 1, 2, 0, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 2, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 2, 1, 0, 0, 2, 1, 2, 0, 0, 1, 1, 1, 0, 1, 2, 1, 3, 3, 1, 5, 2, 3, 3, 1, 1, 0, 1, 1, 4, 1, 0, 1, 0, 0, 0, 1, 0, 1, 2, 2, 2, 1, 4, 4, 3, 2, 2, 1, 4, 3, 0, 3, 1, 2, 0, 1, 0, 2, 0, 0, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 1, 3, 1, 1, 2, 1, 2, 0, 1, 2, 1, 3, 3, 4, 1], 'learning_rate': 9.659758169437212e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005804024153218448, 'train_segmentation_loss': 0.2761652226200198, 'val_foreground_miou_all22': 0.718323132875327, 'val_psnr_ref1': 39.122218475341796, 'elapsed_seconds': 333.30113434791565, 'peak_cuda_allocated_gib': 7.510288238525391}

Epoch 475/500 | Batch 10/202 | Rec 0.000697 | Seg 0.337056 | Elapsed 0.2m | ETA 4.0m
Epoch 475/500 | Batch 20/202 | Rec 0.000625 | Seg 0.289696 | Elapsed 0.4m | ETA 3.8m
Epoch 475/500 | Batch 30/202 | Rec 0.000607 | Seg 0.287084 | Elapsed 0.6m | ETA 3.6m
Epoch 475/500 | Batch 40/202 | Rec 0.000595 | Seg 0.287779 | Elapsed 0.8m | ETA 3.3m
Epoch 475/500 | Batch 50/202 | Rec 0.000576 | Seg 0.285035 | Elapsed 1.0m | ETA 3.1m
Epoch 475/500 | Batch 60/202 | Rec 0.000578 | Seg 0.285166 | Elapsed 1.2m | ETA 2.9m
Epoch 475/500 | Batch 70/202 | Rec 0.000578 | Seg 0.277618 | Elapsed 1.4m | ETA 2.7m
Epoch 475/500 | Batch 80/202 | Rec 0.000582 | Seg 0.267400 | Elapsed 1.6m | ETA 2.5m
Epoch 475/500 | Batch 90/202 | Rec 0.000583 | Seg 0.275310 | Elapsed 1.8m | ETA 2.3m
Epoch 475/500 | Batch 100/202 | Rec 0.000584 | Seg 0.276927 | Elapsed 2.0m | ETA 2.1m
Epoch 475/500 | Batch 110/202 | Rec 0.000582 | Seg 0.276369 | Elapsed 2.2m | ETA 1.9m
Epoch 475/500 | Batch 120/202 | Rec 0.000574 | Seg 0.271693 | Elapsed 2.4m | ETA 1.7m
Epoch 475/500 | Batch 130/202 | Rec 0.000574 | Seg 0.275371 | Elapsed 2.7m | ETA 1.5m
Epoch 475/500 | Batch 140/202 | Rec 0.000574 | Seg 0.276270 | Elapsed 2.9m | ETA 1.3m
Epoch 475/500 | Batch 150/202 | Rec 0.000570 | Seg 0.278151 | Elapsed 3.1m | ETA 1.1m
Epoch 475/500 | Batch 160/202 | Rec 0.000572 | Seg 0.278897 | Elapsed 3.3m | ETA 0.9m
Epoch 475/500 | Batch 170/202 | Rec 0.000564 | Seg 0.274805 | Elapsed 3.5m | ETA 0.7m
Epoch 475/500 | Batch 180/202 | Rec 0.000558 | Seg 0.273538 | Elapsed 3.7m | ETA 0.4m
Epoch 475/500 | Batch 190/202 | Rec 0.000563 | Seg 0.278373 | Elapsed 3.9m | ETA 0.2m
Epoch 475/500 | Batch 200/202 | Rec 0.000567 | Seg 0.279909 | Elapsed 4.1m | ETA 0.0m
Epoch 475/500 | Batch 202/202 | Rec 0.000569 | Seg 0.280162 | Elapsed 4.1m | ETA 0.0m

2026-10-10 15:39:21,423 - INFO: Rec loss: 0.0005690201809791166
2026-10-10 15:39:21,423 - INFO: Seg loss: 0.2801619055358195
2026-10-10 15:39:21,423 - INFO: λ_rec: 1
2026-10-10 15:39:21,423 - INFO: λ_seg: 0.0001
2026-10-10 15:40:39,909 - INFO: -------------------Epoch: 475------------------------
2026-10-10 15:40:39,913 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.948652  0.974817  0.000133
2026-10-10 15:40:39,920 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995719  0.997805  0.997257  0.998453  0.995913
real potato   0.920587  0.958602  0.942241  0.975644  0.999899
fake potato   0.965035  0.982156  0.981590  0.982824  0.999974
real apple    0.765489  0.867120  0.975776  0.780318  0.999175
fake apple    0.577565  0.732177  0.983972  0.583050  0.998390
real orange   0.946464  0.972446  0.996235  0.949861  0.999929
fake orange   0.954895  0.976877  0.967831  0.986195  0.999867
real grape    0.762490  0.865192  0.937788  0.803113  0.999478
fake grape    0.892875  0.943356  0.907225  0.982593  0.999564
real lemon    0.748711  0.856251  0.863997  0.848741  0.999665
fake lemon    0.828803  0.906339  0.993296  0.833466  0.999636
real avocado  0.956280  0.977601  0.997097  0.958949  0.999959
fake avocado  0.621956  0.766874  0.999795  0.622035  0.999548
real pepper   0.897282  0.945811  0.919589  0.973678  0.999592
fake pepper   0.834157  0.909531  0.947186  0.874848  0.999585
real plant    0.864829  0.927466  0.950887  0.905266  0.998585
fake plant    0.776284  0.874004  0.873301  0.874808  0.999799
real banana   0.751772  0.858249  0.890674  0.828195  0.999386
fake banana   0.666559  0.799873  0.748518  0.858908  0.999210
real onion    0.607960  0.756140  0.621722  0.964871  0.999438
fake onion    0.917567  0.956962  0.969479  0.944861  0.999946
real unknown  0.679720  0.809276  0.717873  0.927481  0.999930
fake unknown  0.216651  0.356106  0.237193  0.714415  0.997823
total         0.789115  0.869401  0.887849  0.877068  0.999317
total(-bg)    0.779724  0.863564  0.882876  0.871551  0.999472
2026-10-10 15:40:40,392 - INFO: Epoch accounting: {'epoch': 475, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11224336, 48014, 73156, 141189, 173565, 87851, 74642, 129697, 202387, 80707, 75133, 33759, 28245, 265105, 76202, 115035, 26348, 86935, 88094, 91877, 69606, 10602, 35787], 'crops_with_class': [202, 37, 33, 42, 41, 25, 26, 26, 40, 36, 31, 12, 10, 65, 28, 18, 21, 23, 33, 38, 27, 10, 15], 'targeted_crops_by_class': [0, 6, 6, 3, 10, 5, 5, 2, 8, 5, 4, 6, 4, 2, 5, 5, 3, 7, 7, 3, 9, 5, 5], 'sampled_scene_counts': [0, 1, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 2, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0, 1, 1, 3, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 2, 2, 2, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 2, 0, 1, 0, 1, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 1, 0, 1, 0, 1, 1, 1, 3, 2, 2, 2, 3, 1, 2, 2, 2, 2, 1, 1, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0, 1, 2, 1, 3, 3, 2, 1, 1, 0, 1, 3, 2, 1, 3, 1, 2, 3, 0, 3, 2, 1, 4, 2, 1, 2, 1, 0, 3, 1, 0, 1, 0, 2, 0, 5, 3, 2, 2, 1, 0, 3, 1, 3, 2, 3, 1, 0, 3, 0, 1, 0, 2, 3, 0, 1, 0, 1], 'learning_rate': 9.140385326325806e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005690201809791166, 'train_segmentation_loss': 0.2801619055358195, 'val_foreground_miou_all22': 0.7797242028801804, 'val_psnr_ref1': 38.94865219116211, 'elapsed_seconds': 326.6100151538849, 'peak_cuda_allocated_gib': 7.514194488525391}

Epoch 476/500 | Batch 10/202 | Rec 0.000603 | Seg 0.300451 | Elapsed 0.2m | ETA 3.9m
Epoch 476/500 | Batch 20/202 | Rec 0.000748 | Seg 0.329730 | Elapsed 0.4m | ETA 3.7m
Epoch 476/500 | Batch 30/202 | Rec 0.000693 | Seg 0.326182 | Elapsed 0.6m | ETA 3.6m
Epoch 476/500 | Batch 40/202 | Rec 0.000700 | Seg 0.326145 | Elapsed 0.8m | ETA 3.4m
Epoch 476/500 | Batch 50/202 | Rec 0.000676 | Seg 0.317754 | Elapsed 1.0m | ETA 3.2m
Epoch 476/500 | Batch 60/202 | Rec 0.000643 | Seg 0.306203 | Elapsed 1.2m | ETA 2.9m
Epoch 476/500 | Batch 70/202 | Rec 0.000649 | Seg 0.310814 | Elapsed 1.5m | ETA 2.7m
Epoch 476/500 | Batch 80/202 | Rec 0.000640 | Seg 0.309966 | Elapsed 1.7m | ETA 2.5m
Epoch 476/500 | Batch 90/202 | Rec 0.000633 | Seg 0.301941 | Elapsed 1.9m | ETA 2.3m
Epoch 476/500 | Batch 100/202 | Rec 0.000631 | Seg 0.303208 | Elapsed 2.1m | ETA 2.1m
Epoch 476/500 | Batch 110/202 | Rec 0.000623 | Seg 0.297302 | Elapsed 2.3m | ETA 1.9m
Epoch 476/500 | Batch 120/202 | Rec 0.000616 | Seg 0.298554 | Elapsed 2.5m | ETA 1.7m
Epoch 476/500 | Batch 130/202 | Rec 0.000606 | Seg 0.297116 | Elapsed 2.7m | ETA 1.5m
Epoch 476/500 | Batch 140/202 | Rec 0.000598 | Seg 0.295065 | Elapsed 2.9m | ETA 1.3m
Epoch 476/500 | Batch 150/202 | Rec 0.000593 | Seg 0.291984 | Elapsed 3.1m | ETA 1.1m
Epoch 476/500 | Batch 160/202 | Rec 0.000595 | Seg 0.290331 | Elapsed 3.3m | ETA 0.9m
Epoch 476/500 | Batch 170/202 | Rec 0.000591 | Seg 0.288913 | Elapsed 3.5m | ETA 0.7m
Epoch 476/500 | Batch 180/202 | Rec 0.000584 | Seg 0.286612 | Elapsed 3.7m | ETA 0.5m
Epoch 476/500 | Batch 190/202 | Rec 0.000577 | Seg 0.281714 | Elapsed 3.9m | ETA 0.2m
Epoch 476/500 | Batch 200/202 | Rec 0.000573 | Seg 0.279101 | Elapsed 4.1m | ETA 0.0m
Epoch 476/500 | Batch 202/202 | Rec 0.000572 | Seg 0.278614 | Elapsed 4.2m | ETA 0.0m

2026-10-10 15:44:51,219 - INFO: Rec loss: 0.0005716744934682421
2026-10-10 15:44:51,220 - INFO: Seg loss: 0.2786139069807411
2026-10-10 15:44:51,220 - INFO: λ_rec: 1
2026-10-10 15:44:51,220 - INFO: λ_seg: 0.0001
2026-10-10 15:46:11,857 - INFO: -------------------Epoch: 476------------------------
2026-10-10 15:46:11,861 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.017765  0.974933  0.000131
2026-10-10 15:46:11,867 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995739  0.997815  0.997504  0.998227  0.995934
real potato   0.430498  0.601843  0.973497  0.435603  0.999310
fake potato   0.735767  0.847723  0.979676  0.747172  0.999805
real apple    0.705800  0.827480  0.785328  0.874525  0.998742
fake apple    0.573967  0.729279  0.987168  0.578282  0.998379
real orange   0.966306  0.982814  0.992910  0.973020  0.999955
fake orange   0.954588  0.976716  0.965625  0.988168  0.999865
real grape    0.858998  0.924102  0.955873  0.894468  0.999693
fake grape    0.894402  0.944208  0.910431  0.980695  0.999572
real lemon    0.524147  0.687745  0.535968  0.959621  0.998976
fake lemon    0.860437  0.924934  0.995264  0.863974  0.999704
real avocado  0.845627  0.916308  0.865761  0.973235  0.999835
fake avocado  0.658083  0.793740  0.999613  0.658250  0.999591
real pepper   0.763153  0.865619  0.805131  0.936050  0.998937
fake pepper   0.629729  0.772754  0.957340  0.647910  0.999092
real plant    0.879979  0.936108  0.962743  0.911002  0.998757
fake plant    0.749796  0.856960  0.835031  0.880176  0.999766
real banana   0.460009  0.630098  0.831404  0.507334  0.998662
fake banana   0.719783  0.837013  0.806224  0.870355  0.999377
real onion    0.630514  0.773343  0.711329  0.847323  0.999551
fake onion    0.917867  0.957125  0.992469  0.924305  0.999948
real unknown  0.750943  0.857709  0.782233  0.949427  0.999950
fake unknown  0.209526  0.346424  0.224509  0.758421  0.997589
total         0.726768  0.825559  0.863175  0.832937  0.999174
total(-bg)    0.714542  0.817729  0.857069  0.825423  0.999321
2026-10-10 15:46:12,351 - INFO: Epoch accounting: {'epoch': 476, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11242224, 51788, 75797, 130591, 135536, 93493, 61027, 179635, 216739, 61581, 52221, 42900, 24614, 246020, 107591, 167969, 14170, 73741, 68535, 77131, 64978, 9095, 40896], 'crops_with_class': [202, 29, 31, 34, 39, 28, 20, 32, 34, 27, 23, 15, 12, 63, 30, 20, 13, 21, 31, 33, 27, 11, 20], 'targeted_crops_by_class': [0, 1, 6, 3, 5, 4, 3, 9, 8, 2, 3, 3, 5, 9, 3, 2, 2, 7, 5, 5, 3, 5, 5], 'sampled_scene_counts': [1, 3, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 1, 0, 2, 1, 1, 1, 1, 0, 0, 1, 1, 0, 2, 0, 0, 2, 1, 1, 3, 1, 1, 0, 0, 1, 1, 0, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 1, 2, 2, 0, 0, 2, 0, 2, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 2, 3, 0, 2, 0, 2, 2, 0, 1, 1, 2, 0, 1, 1, 1, 1, 1, 1, 2, 1, 1, 3, 2, 0, 1, 2, 2, 1, 0, 1, 2, 2, 0, 1, 2, 1, 1, 4, 1, 2, 3, 1, 3, 1, 2, 0, 1, 1, 1, 2, 2, 0, 1, 1, 2, 4, 3, 1, 0, 2, 1, 2, 4, 1, 2, 0, 1, 1, 3, 2, 1, 0, 0, 1, 1, 0, 1, 2, 1, 4, 0, 1], 'learning_rate': 8.640440128175082e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005716744934682421, 'train_segmentation_loss': 0.2786139069807411, 'val_foreground_miou_all22': 0.7145417817544341, 'val_psnr_ref1': 39.017765045166016, 'elapsed_seconds': 331.9520676136017, 'peak_cuda_allocated_gib': 7.510288238525391}

Epoch 477/500 | Batch 10/202 | Rec 0.000593 | Seg 0.320469 | Elapsed 0.2m | ETA 3.9m
Epoch 477/500 | Batch 20/202 | Rec 0.000508 | Seg 0.272831 | Elapsed 0.4m | ETA 3.8m
Epoch 477/500 | Batch 30/202 | Rec 0.000562 | Seg 0.291268 | Elapsed 0.6m | ETA 3.5m
Epoch 477/500 | Batch 40/202 | Rec 0.000572 | Seg 0.299628 | Elapsed 0.8m | ETA 3.3m
Epoch 477/500 | Batch 50/202 | Rec 0.000569 | Seg 0.292727 | Elapsed 1.0m | ETA 3.1m
Epoch 477/500 | Batch 60/202 | Rec 0.000551 | Seg 0.275187 | Elapsed 1.2m | ETA 2.9m
Epoch 477/500 | Batch 70/202 | Rec 0.000550 | Seg 0.278317 | Elapsed 1.4m | ETA 2.7m
Epoch 477/500 | Batch 80/202 | Rec 0.000558 | Seg 0.279176 | Elapsed 1.7m | ETA 2.5m
Epoch 477/500 | Batch 90/202 | Rec 0.000559 | Seg 0.278125 | Elapsed 1.9m | ETA 2.3m
Epoch 477/500 | Batch 100/202 | Rec 0.000552 | Seg 0.277193 | Elapsed 2.1m | ETA 2.1m
Epoch 477/500 | Batch 110/202 | Rec 0.000564 | Seg 0.280400 | Elapsed 2.3m | ETA 1.9m
Epoch 477/500 | Batch 120/202 | Rec 0.000563 | Seg 0.279173 | Elapsed 2.5m | ETA 1.7m
Epoch 477/500 | Batch 130/202 | Rec 0.000566 | Seg 0.279463 | Elapsed 2.7m | ETA 1.5m
Epoch 477/500 | Batch 140/202 | Rec 0.000562 | Seg 0.275020 | Elapsed 2.9m | ETA 1.3m
Epoch 477/500 | Batch 150/202 | Rec 0.000560 | Seg 0.271588 | Elapsed 3.1m | ETA 1.1m
Epoch 477/500 | Batch 160/202 | Rec 0.000567 | Seg 0.276938 | Elapsed 3.3m | ETA 0.9m
Epoch 477/500 | Batch 170/202 | Rec 0.000572 | Seg 0.280163 | Elapsed 3.5m | ETA 0.7m
Epoch 477/500 | Batch 180/202 | Rec 0.000576 | Seg 0.282585 | Elapsed 3.7m | ETA 0.5m
Epoch 477/500 | Batch 190/202 | Rec 0.000577 | Seg 0.282818 | Elapsed 3.9m | ETA 0.2m
Epoch 477/500 | Batch 200/202 | Rec 0.000585 | Seg 0.284578 | Elapsed 4.1m | ETA 0.0m
Epoch 477/500 | Batch 202/202 | Rec 0.000585 | Seg 0.284070 | Elapsed 4.2m | ETA 0.0m

2026-10-10 15:50:22,451 - INFO: Rec loss: 0.000585021787970834
2026-10-10 15:50:22,451 - INFO: Seg loss: 0.2840697253215136
2026-10-10 15:50:22,451 - INFO: λ_rec: 1
2026-10-10 15:50:22,451 - INFO: λ_seg: 0.0001
2026-10-10 15:51:40,202 - INFO: -------------------Epoch: 477------------------------
2026-10-10 15:51:40,206 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.006431  0.974871  0.000131
2026-10-10 15:51:40,213 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995540  0.997715  0.997032  0.998499  0.995742
real potato   0.882299  0.937420  0.899461  0.978832  0.999844
fake potato   0.970364  0.984909  0.982292  0.987641  0.999978
real apple    0.702011  0.824871  0.966605  0.719460  0.998946
fake apple    0.536879  0.698616  0.993000  0.538919  0.998245
real orange   0.902970  0.948961  0.993415  0.908407  0.999871
fake orange   0.928575  0.962915  0.949956  0.976335  0.999785
real grape    0.732505  0.845553  0.864250  0.827742  0.999369
fake grape    0.896570  0.945415  0.914147  0.979004  0.999582
real lemon    0.662848  0.797195  0.956230  0.683589  0.999591
fake lemon    0.815326  0.898220  0.990353  0.821854  0.999606
real avocado  0.952926  0.975846  0.981242  0.970608  0.999955
fake avocado  0.598495  0.748777  0.999787  0.598572  0.999520
real pepper   0.802501  0.890381  0.821544  0.971926  0.999125
fake pepper   0.654659  0.791243  0.934053  0.686384  0.999137
real plant    0.856150  0.922451  0.961009  0.886960  0.998509
fake plant    0.734087  0.846606  0.774877  0.933090  0.999731
real banana   0.754358  0.859932  0.814451  0.910906  0.999333
fake banana   0.683679  0.812075  0.761452  0.870023  0.999259
real onion    0.608572  0.756614  0.617811  0.976018  0.999433
fake onion    0.904311  0.949701  0.931211  0.969045  0.999935
real unknown  0.554077  0.713015  0.584503  0.914122  0.999882
fake unknown  0.188149  0.316671  0.214222  0.607208  0.997792
total         0.752950  0.844570  0.865344  0.857180  0.999225
total(-bg)    0.741923  0.837608  0.859358  0.850756  0.999383
2026-10-10 15:51:40,679 - INFO: Epoch accounting: {'epoch': 477, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11206696, 46204, 67294, 110946, 124565, 92287, 80847, 120507, 247350, 100907, 59020, 44895, 33434, 177102, 104466, 208627, 32754, 65565, 77332, 110280, 68055, 6576, 52563], 'crops_with_class': [202, 28, 29, 30, 34, 25, 26, 31, 40, 45, 30, 17, 11, 51, 31, 27, 26, 21, 27, 44, 27, 7, 21], 'targeted_crops_by_class': [0, 9, 4, 5, 4, 1, 4, 4, 6, 7, 7, 2, 4, 4, 2, 4, 6, 5, 5, 4, 4, 4, 3], 'sampled_scene_counts': [1, 0, 1, 1, 2, 1, 1, 0, 0, 2, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 0, 0, 1, 2, 1, 0, 0, 1, 2, 0, 2, 2, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 3, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 2, 1, 0, 1, 1, 0, 1, 3, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 4, 3, 0, 4, 1, 1, 2, 0, 1, 1, 3, 3, 1, 2, 0, 0, 1, 1, 0, 2, 1, 0, 0, 0, 2, 1, 3, 1, 3, 3, 1, 1, 3, 1, 1, 0, 0, 5, 1, 4, 3, 2, 1, 1, 3, 0, 1, 2, 1, 1, 1, 1, 3, 0, 3, 0, 4, 1, 2, 1, 0, 2, 1, 0, 2, 1, 1, 0, 1, 2, 2, 0, 2, 2, 1, 2, 4, 2, 0], 'learning_rate': 8.159942311965409e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000585021787970834, 'train_segmentation_loss': 0.2840697253215136, 'val_foreground_miou_all22': 0.7419232442353497, 'val_psnr_ref1': 39.006431121826175, 'elapsed_seconds': 328.3204996585846, 'peak_cuda_allocated_gib': 7.513217926025391}

Epoch 478/500 | Batch 10/202 | Rec 0.000460 | Seg 0.235863 | Elapsed 0.2m | ETA 4.0m
Epoch 478/500 | Batch 20/202 | Rec 0.000460 | Seg 0.235254 | Elapsed 0.4m | ETA 3.8m
Epoch 478/500 | Batch 30/202 | Rec 0.000446 | Seg 0.239493 | Elapsed 0.6m | ETA 3.6m
Epoch 478/500 | Batch 40/202 | Rec 0.000470 | Seg 0.251778 | Elapsed 0.8m | ETA 3.3m
Epoch 478/500 | Batch 50/202 | Rec 0.000465 | Seg 0.249216 | Elapsed 1.0m | ETA 3.1m
Epoch 478/500 | Batch 60/202 | Rec 0.000488 | Seg 0.263216 | Elapsed 1.2m | ETA 2.9m
Epoch 478/500 | Batch 70/202 | Rec 0.000486 | Seg 0.263586 | Elapsed 1.4m | ETA 2.7m
Epoch 478/500 | Batch 80/202 | Rec 0.000482 | Seg 0.265446 | Elapsed 1.6m | ETA 2.5m
Epoch 478/500 | Batch 90/202 | Rec 0.000487 | Seg 0.260089 | Elapsed 1.8m | ETA 2.3m
Epoch 478/500 | Batch 100/202 | Rec 0.000507 | Seg 0.263777 | Elapsed 2.0m | ETA 2.1m
Epoch 478/500 | Batch 110/202 | Rec 0.000503 | Seg 0.259906 | Elapsed 2.3m | ETA 1.9m
Epoch 478/500 | Batch 120/202 | Rec 0.000500 | Seg 0.256375 | Elapsed 2.5m | ETA 1.7m
Epoch 478/500 | Batch 130/202 | Rec 0.000503 | Seg 0.255344 | Elapsed 2.7m | ETA 1.5m
Epoch 478/500 | Batch 140/202 | Rec 0.000513 | Seg 0.256670 | Elapsed 2.9m | ETA 1.3m
Epoch 478/500 | Batch 150/202 | Rec 0.000525 | Seg 0.258377 | Elapsed 3.1m | ETA 1.1m
Epoch 478/500 | Batch 160/202 | Rec 0.000537 | Seg 0.261586 | Elapsed 3.3m | ETA 0.9m
Epoch 478/500 | Batch 170/202 | Rec 0.000535 | Seg 0.263772 | Elapsed 3.5m | ETA 0.7m
Epoch 478/500 | Batch 180/202 | Rec 0.000551 | Seg 0.265173 | Elapsed 3.7m | ETA 0.5m
Epoch 478/500 | Batch 190/202 | Rec 0.000554 | Seg 0.265875 | Elapsed 3.9m | ETA 0.2m
Epoch 478/500 | Batch 200/202 | Rec 0.000553 | Seg 0.267440 | Elapsed 4.1m | ETA 0.0m
Epoch 478/500 | Batch 202/202 | Rec 0.000556 | Seg 0.269148 | Elapsed 4.1m | ETA 0.0m

2026-10-10 15:55:49,633 - INFO: Rec loss: 0.0005555465468925903
2026-10-10 15:55:49,634 - INFO: Seg loss: 0.2691475334438947
2026-10-10 15:55:49,634 - INFO: λ_rec: 1
2026-10-10 15:55:49,634 - INFO: λ_seg: 0.0001
2026-10-10 15:57:11,266 - INFO: -------------------Epoch: 478------------------------
2026-10-10 15:57:11,270 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.098177  0.974966  0.000128
2026-10-10 15:57:11,277 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995685  0.997788  0.996935  0.998742  0.995880
real potato   0.772414  0.871546  0.978865  0.785514  0.999723
fake potato   0.743616  0.852909  0.977796  0.756389  0.999810
real apple    0.769319  0.869572  0.917010  0.826891  0.999145
fake apple    0.633233  0.775387  0.966801  0.647308  0.998584
real orange   0.901558  0.948181  0.996301  0.904585  0.999870
fake orange   0.930875  0.964150  0.950495  0.978307  0.999792
real grape    0.780890  0.876916  0.951986  0.812907  0.999524
fake grape    0.889356  0.941388  0.914976  0.969476  0.999554
real lemon    0.540193  0.701413  0.601597  0.841080  0.999159
fake lemon    0.842558  0.914503  0.974079  0.861882  0.999659
real avocado  0.858231  0.923658  0.888148  0.962233  0.999852
fake avocado  0.734038  0.846574  0.999133  0.734506  0.999682
real pepper   0.831561  0.907985  0.875916  0.942600  0.999302
fake pepper   0.727473  0.842190  0.945623  0.759234  0.999322
real plant    0.863922  0.926944  0.950867  0.904290  0.998575
fake plant    0.734171  0.846661  0.821377  0.873658  0.999748
real banana   0.554635  0.713477  0.921432  0.582168  0.998950
fake banana   0.703825  0.826120  0.813258  0.839499  0.999350
real onion    0.650710  0.788351  0.680658  0.936666  0.999546
fake onion    0.927550  0.962363  0.984569  0.941233  0.999954
real unknown  0.713235  0.832568  0.756630  0.925572  0.999940
fake unknown  0.220632  0.361465  0.247156  0.672763  0.997998
total         0.753030  0.847483  0.874418  0.845978  0.999257
total(-bg)    0.742000  0.840651  0.868849  0.839035  0.999411
2026-10-10 15:57:11,778 - INFO: Epoch accounting: {'epoch': 478, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11334555, 52878, 54756, 117452, 166358, 69673, 69655, 144185, 183699, 64929, 46048, 53954, 32416, 189494, 107993, 140206, 24016, 81173, 92927, 93083, 60261, 8130, 50431], 'crops_with_class': [202, 31, 27, 33, 41, 24, 24, 31, 34, 31, 18, 18, 11, 48, 31, 19, 21, 23, 36, 40, 28, 9, 23], 'targeted_crops_by_class': [0, 3, 5, 4, 4, 5, 4, 6, 5, 0, 4, 4, 5, 2, 4, 4, 1, 5, 6, 8, 7, 2, 8], 'sampled_scene_counts': [0, 1, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 1, 0, 3, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 2, 2, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 2, 2, 1, 0, 0, 1, 2, 0, 1, 1, 1, 1, 2, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 1, 2, 2, 0, 1, 1, 0, 1, 1, 2, 2, 1, 1, 2, 0, 2, 2, 0, 1, 0, 1, 4, 2, 1, 1, 1, 1, 1, 2, 0, 4, 1, 2, 1, 2, 5, 3, 2, 2, 1, 0, 0, 2, 1, 1, 3, 2, 0, 3, 2, 2, 1, 1, 2, 0, 2, 0, 3, 2, 3, 0, 1, 2, 0, 1, 0, 0, 1, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 0, 1, 2, 3, 2, 0, 2, 2, 2], 'learning_rate': 7.698910846927841e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005555465468925903, 'train_segmentation_loss': 0.2691475334438947, 'val_foreground_miou_all22': 0.7419998483525853, 'val_psnr_ref1': 39.09817657470703, 'elapsed_seconds': 331.09213376045227, 'peak_cuda_allocated_gib': 7.507389068603516}

Epoch 479/500 | Batch 10/202 | Rec 0.000594 | Seg 0.253428 | Elapsed 0.2m | ETA 4.1m
Epoch 479/500 | Batch 20/202 | Rec 0.000512 | Seg 0.229867 | Elapsed 0.4m | ETA 3.8m
Epoch 479/500 | Batch 30/202 | Rec 0.000580 | Seg 0.227013 | Elapsed 0.6m | ETA 3.6m
Epoch 479/500 | Batch 40/202 | Rec 0.000579 | Seg 0.256236 | Elapsed 0.8m | ETA 3.4m
Epoch 479/500 | Batch 50/202 | Rec 0.000577 | Seg 0.262254 | Elapsed 1.0m | ETA 3.2m
Epoch 479/500 | Batch 60/202 | Rec 0.000567 | Seg 0.259826 | Elapsed 1.2m | ETA 3.0m
Epoch 479/500 | Batch 70/202 | Rec 0.000557 | Seg 0.257991 | Elapsed 1.5m | ETA 2.7m
Epoch 479/500 | Batch 80/202 | Rec 0.000563 | Seg 0.260457 | Elapsed 1.7m | ETA 2.5m
Epoch 479/500 | Batch 90/202 | Rec 0.000574 | Seg 0.267068 | Elapsed 1.9m | ETA 2.3m
Epoch 479/500 | Batch 100/202 | Rec 0.000577 | Seg 0.263154 | Elapsed 2.1m | ETA 2.1m
Epoch 479/500 | Batch 110/202 | Rec 0.000566 | Seg 0.257286 | Elapsed 2.3m | ETA 1.9m
Epoch 479/500 | Batch 120/202 | Rec 0.000563 | Seg 0.254630 | Elapsed 2.5m | ETA 1.7m
Epoch 479/500 | Batch 130/202 | Rec 0.000556 | Seg 0.252898 | Elapsed 2.7m | ETA 1.5m
Epoch 479/500 | Batch 140/202 | Rec 0.000568 | Seg 0.259773 | Elapsed 2.9m | ETA 1.3m
Epoch 479/500 | Batch 150/202 | Rec 0.000567 | Seg 0.257611 | Elapsed 3.1m | ETA 1.1m
Epoch 479/500 | Batch 160/202 | Rec 0.000568 | Seg 0.256731 | Elapsed 3.3m | ETA 0.9m
Epoch 479/500 | Batch 170/202 | Rec 0.000569 | Seg 0.257164 | Elapsed 3.5m | ETA 0.7m
Epoch 479/500 | Batch 180/202 | Rec 0.000565 | Seg 0.255699 | Elapsed 3.7m | ETA 0.5m
Epoch 479/500 | Batch 190/202 | Rec 0.000565 | Seg 0.258714 | Elapsed 3.9m | ETA 0.2m
Epoch 479/500 | Batch 200/202 | Rec 0.000572 | Seg 0.259759 | Elapsed 4.1m | ETA 0.0m
Epoch 479/500 | Batch 202/202 | Rec 0.000569 | Seg 0.258908 | Elapsed 4.2m | ETA 0.0m

2026-10-10 16:01:22,641 - INFO: Rec loss: 0.000569173414087255
2026-10-10 16:01:22,641 - INFO: Seg loss: 0.2589080522740536
2026-10-10 16:01:22,641 - INFO: λ_rec: 1
2026-10-10 16:01:22,641 - INFO: λ_seg: 0.0001
2026-10-10 16:02:40,586 - INFO: -------------------Epoch: 479------------------------
2026-10-10 16:02:40,590 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.121333  0.975082  0.000128
2026-10-10 16:02:40,596 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995785  0.997838  0.997254  0.998522  0.995976
real potato   0.516650  0.681259  0.979436  0.522316  0.999415
fake potato   0.707711  0.828793  0.985566  0.715124  0.999785
real apple    0.734525  0.846896  0.824475  0.870677  0.998914
fake apple    0.582827  0.736392  0.991720  0.585677  0.998417
real orange   0.919475  0.957999  0.992919  0.925544  0.999893
fake orange   0.939382  0.968693  0.959724  0.977934  0.999819
real grape    0.819346  0.900654  0.939724  0.864796  0.999602
fake grape    0.896244  0.945233  0.919671  0.972363  0.999584
real lemon    0.609284  0.757163  0.633637  0.940665  0.999291
fake lemon    0.859692  0.924503  0.997246  0.861738  0.999702
real avocado  0.857959  0.923500  0.887996  0.962069  0.999852
fake avocado  0.615708  0.762106  0.999793  0.615787  0.999540
real pepper   0.813721  0.897245  0.849743  0.950484  0.999204
fake pepper   0.657711  0.793468  0.937293  0.687984  0.999147
real plant    0.872027  0.931589  0.953668  0.910605  0.998663
fake plant    0.739768  0.850372  0.791866  0.918328  0.999743
real banana   0.591613  0.743365  0.890447  0.638055  0.999010
fake banana   0.724674  0.840311  0.819651  0.862143  0.999397
real onion    0.653889  0.790680  0.713084  0.887350  0.999576
fake onion    0.926555  0.961828  0.988515  0.936638  0.999953
real unknown  0.887971  0.940611  0.959325  0.922710  0.999981
fake unknown  0.208610  0.345170  0.226122  0.729265  0.997669
total         0.744832  0.840246  0.879951  0.837251  0.999223
total(-bg)    0.733425  0.833083  0.874619  0.829921  0.999371
2026-10-10 16:02:41,077 - INFO: Epoch accounting: {'epoch': 479, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11426296, 59449, 63670, 134934, 154343, 49371, 44460, 109603, 127574, 57700, 56914, 51020, 38310, 204366, 124162, 157861, 23698, 113288, 62347, 82098, 48706, 5899, 42203], 'crops_with_class': [202, 33, 33, 36, 39, 14, 14, 24, 24, 27, 24, 15, 13, 52, 34, 22, 22, 28, 24, 37, 26, 7, 16], 'targeted_crops_by_class': [0, 4, 5, 6, 3, 3, 0, 5, 2, 4, 1, 5, 5, 3, 6, 0, 8, 4, 9, 5, 3, 0, 5], 'sampled_scene_counts': [1, 1, 0, 0, 1, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 2, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 1, 1, 2, 3, 1, 1, 0, 2, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 2, 1, 0, 1, 2, 0, 1, 2, 2, 0, 0, 0, 2, 0, 2, 1, 2, 2, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 2, 0, 2, 0, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 2, 3, 0, 1, 1, 0, 2, 0, 1, 4, 1, 2, 3, 1, 3, 0, 1, 1, 2, 1, 1, 4, 1, 0, 1, 0, 2, 1, 1, 1, 0, 1, 2, 2, 1, 1, 2, 6, 2, 2, 0, 1, 1, 1, 1, 3, 1, 2], 'learning_rate': 7.257363933795215e-07, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.000569173414087255, 'train_segmentation_loss': 0.2589080522740536, 'val_foreground_miou_all22': 0.7334246679250644, 'val_psnr_ref1': 39.121333312988284, 'elapsed_seconds': 329.29135751724243, 'peak_cuda_allocated_gib': 7.511753082275391}

Epoch 480/500 | Batch 10/202 | Rec 0.000590 | Seg 0.298498 | Elapsed 0.2m | ETA 4.0m
Epoch 480/500 | Batch 20/202 | Rec 0.000567 | Seg 0.282231 | Elapsed 0.4m | ETA 3.8m
Epoch 480/500 | Batch 30/202 | Rec 0.000565 | Seg 0.253762 | Elapsed 0.6m | ETA 3.5m
Epoch 480/500 | Batch 40/202 | Rec 0.000580 | Seg 0.252184 | Elapsed 0.8m | ETA 3.3m
Epoch 480/500 | Batch 50/202 | Rec 0.000578 | Seg 0.270860 | Elapsed 1.0m | ETA 3.1m
Epoch 480/500 | Batch 60/202 | Rec 0.000582 | Seg 0.275884 | Elapsed 1.2m | ETA 2.9m
Epoch 480/500 | Batch 70/202 | Rec 0.000576 | Seg 0.268312 | Elapsed 1.4m | ETA 2.7m
Epoch 480/500 | Batch 80/202 | Rec 0.000579 | Seg 0.265812 | Elapsed 1.6m | ETA 2.5m
Epoch 480/500 | Batch 90/202 | Rec 0.000579 | Seg 0.264505 | Elapsed 1.8m | ETA 2.3m
Epoch 480/500 | Batch 100/202 | Rec 0.000566 | Seg 0.261312 | Elapsed 2.0m | ETA 2.1m
Epoch 480/500 | Batch 110/202 | Rec 0.000580 | Seg 0.266814 | Elapsed 2.2m | ETA 1.9m
Epoch 480/500 | Batch 120/202 | Rec 0.000587 | Seg 0.272359 | Elapsed 2.5m | ETA 1.7m
Epoch 480/500 | Batch 130/202 | Rec 0.000576 | Seg 0.269502 | Elapsed 2.7m | ETA 1.5m
Epoch 480/500 | Batch 140/202 | Rec 0.000580 | Seg 0.272087 | Elapsed 2.9m | ETA 1.3m
Epoch 480/500 | Batch 150/202 | Rec 0.000589 | Seg 0.270493 | Elapsed 3.1m | ETA 1.1m
Epoch 480/500 | Batch 160/202 | Rec 0.000586 | Seg 0.269618 | Elapsed 3.3m | ETA 0.9m
Epoch 480/500 | Batch 170/202 | Rec 0.000574 | Seg 0.266191 | Elapsed 3.5m | ETA 0.7m
Epoch 480/500 | Batch 180/202 | Rec 0.000569 | Seg 0.265473 | Elapsed 3.7m | ETA 0.5m
Epoch 480/500 | Batch 190/202 | Rec 0.000571 | Seg 0.266831 | Elapsed 3.9m | ETA 0.2m
Epoch 480/500 | Batch 200/202 | Rec 0.000572 | Seg 0.266506 | Elapsed 4.1m | ETA 0.0m
Epoch 480/500 | Batch 202/202 | Rec 0.000572 | Seg 0.266262 | Elapsed 4.1m | ETA 0.0m

2026-10-10 16:06:49,390 - INFO: Rec loss: 0.0005721970134827373
2026-10-10 16:06:49,390 - INFO: Seg loss: 0.26626170065143323
2026-10-10 16:06:49,391 - INFO: λ_rec: 1
2026-10-10 16:06:49,391 - INFO: λ_seg: 0.0001
2026-10-10 16:08:08,804 - INFO: -------------------Epoch: 480------------------------
2026-10-10 16:08:08,808 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.098278  0.974993  0.000129
2026-10-10 16:08:08,815 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995607  0.997749  0.996928  0.998671  0.995805
real potato   0.669627  0.802079  0.972389  0.682606  0.999597
fake potato   0.740474  0.850838  0.977965  0.753037  0.999808
real apple    0.727381  0.842128  0.876195  0.810703  0.998952
fake apple    0.606850  0.755281  0.978276  0.615139  0.998495
real orange   0.908325  0.951910  0.996832  0.910954  0.999879
fake orange   0.929022  0.963155  0.961594  0.964823  0.999789
real grape    0.785092  0.879560  0.962641  0.809764  0.999537
fake grape    0.899610  0.947102  0.925420  0.969929  0.999600
real lemon    0.578125  0.732625  0.623236  0.888730  0.999238
fake lemon    0.851296  0.919626  0.994798  0.855103  0.999684
real avocado  0.941063  0.969587  0.979879  0.959606  0.999944
fake avocado  0.737600  0.848939  0.999827  0.737694  0.999686
real pepper   0.860588  0.925021  0.887327  0.966169  0.999427
fake pepper   0.762441  0.865161  0.940209  0.801293  0.999405
real plant    0.859171  0.924202  0.953956  0.896342  0.998530
fake plant    0.828391  0.906092  0.907187  0.905100  0.999851
real banana   0.605044  0.753880  0.894315  0.651637  0.999044
fake banana   0.698283  0.822290  0.790586  0.856752  0.999319
real onion    0.650174  0.787957  0.691073  0.916568  0.999554
fake onion    0.921367  0.959025  0.987449  0.932285  0.999950
real unknown  0.623077  0.767724  0.654986  0.927481  0.999910
fake unknown  0.215396  0.354408  0.236692  0.705360  0.997835
total         0.756261  0.848971  0.877816  0.848511  0.999254
total(-bg)    0.745382  0.842209  0.872401  0.841685  0.999411
2026-10-10 16:08:09,295 - INFO: Epoch accounting: {'epoch': 480, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11316824, 64062, 56489, 93269, 143769, 49679, 72661, 93371, 234598, 79420, 45760, 66076, 43844, 203389, 156366, 102834, 27057, 74291, 69579, 101281, 72440, 13712, 57501], 'crops_with_class': [202, 36, 27, 31, 37, 18, 25, 21, 39, 30, 21, 23, 19, 52, 40, 19, 24, 22, 28, 39, 33, 13, 28], 'targeted_crops_by_class': [0, 5, 5, 5, 3, 3, 3, 0, 6, 2, 4, 5, 5, 4, 5, 7, 4, 5, 7, 7, 9, 5, 5], 'sampled_scene_counts': [0, 1, 1, 2, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 2, 0, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 3, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 0, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 2, 1, 1, 0, 1, 0, 1, 2, 1, 0, 3, 1, 2, 0, 0, 3, 0, 1, 1, 3, 1, 2, 3, 0, 1, 1, 2, 1, 2, 1, 0, 2, 2, 0, 0, 1, 1, 5, 0, 1, 3, 1, 1, 3, 2, 6, 1, 4, 3, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 3, 0, 1, 0, 1, 5, 2, 4, 0, 1, 2, 2, 2, 2, 1, 0, 1, 0, 1, 1, 1, 2, 2, 1, 2, 0, 1, 3], 'learning_rate': 6.835319004083584e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005721970134827373, 'train_segmentation_loss': 0.26626170065143323, 'val_foreground_miou_all22': 0.7453816265248694, 'val_psnr_ref1': 39.0982780456543, 'elapsed_seconds': 328.21014761924744, 'peak_cuda_allocated_gib': 7.507846832275391}

Epoch 481/500 | Batch 10/202 | Rec 0.000512 | Seg 0.291227 | Elapsed 0.2m | ETA 4.0m
Epoch 481/500 | Batch 20/202 | Rec 0.000542 | Seg 0.300441 | Elapsed 0.4m | ETA 3.8m
Epoch 481/500 | Batch 30/202 | Rec 0.000573 | Seg 0.304713 | Elapsed 0.6m | ETA 3.5m
Epoch 481/500 | Batch 40/202 | Rec 0.000574 | Seg 0.305859 | Elapsed 0.8m | ETA 3.3m
Epoch 481/500 | Batch 50/202 | Rec 0.000578 | Seg 0.301852 | Elapsed 1.0m | ETA 3.1m
Epoch 481/500 | Batch 60/202 | Rec 0.000571 | Seg 0.294020 | Elapsed 1.2m | ETA 2.9m
Epoch 481/500 | Batch 70/202 | Rec 0.000555 | Seg 0.284925 | Elapsed 1.4m | ETA 2.7m
Epoch 481/500 | Batch 80/202 | Rec 0.000557 | Seg 0.283523 | Elapsed 1.6m | ETA 2.5m
Epoch 481/500 | Batch 90/202 | Rec 0.000546 | Seg 0.274459 | Elapsed 1.8m | ETA 2.3m
Epoch 481/500 | Batch 100/202 | Rec 0.000556 | Seg 0.283311 | Elapsed 2.0m | ETA 2.1m
Epoch 481/500 | Batch 110/202 | Rec 0.000548 | Seg 0.282803 | Elapsed 2.2m | ETA 1.9m
Epoch 481/500 | Batch 120/202 | Rec 0.000549 | Seg 0.281803 | Elapsed 2.4m | ETA 1.7m
Epoch 481/500 | Batch 130/202 | Rec 0.000554 | Seg 0.280687 | Elapsed 2.7m | ETA 1.5m
Epoch 481/500 | Batch 140/202 | Rec 0.000550 | Seg 0.276985 | Elapsed 2.9m | ETA 1.3m
Epoch 481/500 | Batch 150/202 | Rec 0.000544 | Seg 0.273058 | Elapsed 3.1m | ETA 1.1m
Epoch 481/500 | Batch 160/202 | Rec 0.000550 | Seg 0.271901 | Elapsed 3.3m | ETA 0.9m
Epoch 481/500 | Batch 170/202 | Rec 0.000552 | Seg 0.272940 | Elapsed 3.5m | ETA 0.7m
Epoch 481/500 | Batch 180/202 | Rec 0.000553 | Seg 0.274216 | Elapsed 3.7m | ETA 0.5m
Epoch 481/500 | Batch 190/202 | Rec 0.000553 | Seg 0.273305 | Elapsed 3.9m | ETA 0.2m
Epoch 481/500 | Batch 200/202 | Rec 0.000558 | Seg 0.273099 | Elapsed 4.1m | ETA 0.0m
Epoch 481/500 | Batch 202/202 | Rec 0.000562 | Seg 0.275221 | Elapsed 4.1m | ETA 0.0m

2026-10-10 16:12:18,015 - INFO: Rec loss: 0.0005620544980767662
2026-10-10 16:12:18,015 - INFO: Seg loss: 0.2752213235391249
2026-10-10 16:12:18,015 - INFO: λ_rec: 1
2026-10-10 16:12:18,015 - INFO: λ_seg: 0.0001
2026-10-10 16:13:33,989 - INFO: -------------------Epoch: 481------------------------
2026-10-10 16:13:33,993 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.058387  0.974827  0.00013
2026-10-10 16:13:33,999 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995749  0.997820  0.997387  0.998353  0.995942
real potato   0.535314  0.697289  0.999524  0.535450  0.999444
fake potato   0.758910  0.862883  0.971676  0.776079  0.999820
real apple    0.710936  0.830999  0.812743  0.850199  0.998807
fake apple    0.621369  0.766427  0.973663  0.631992  0.998546
real orange   0.953775  0.976291  0.995309  0.958082  0.999939
fake orange   0.958139  0.978572  0.981297  0.975962  0.999878
real grape    0.823810  0.903345  0.969030  0.846086  0.999622
fake grape    0.870598  0.930773  0.888931  0.976859  0.999463
real lemon    0.468762  0.638261  0.531080  0.799792  0.998935
fake lemon    0.851586  0.919795  0.983815  0.863686  0.999682
real avocado  0.868519  0.929583  0.901187  0.959934  0.999865
fake avocado  0.637360  0.778474  0.998802  0.637847  0.999566
real pepper   0.892611  0.943209  0.934209  0.952486  0.999581
fake pepper   0.835031  0.910050  0.946364  0.876512  0.999587
real plant    0.879784  0.935998  0.955146  0.917699  0.998746
fake plant    0.738305  0.849405  0.770070  0.947086  0.999733
real banana   0.535857  0.697747  0.865474  0.584544  0.998862
fake banana   0.648610  0.786807  0.723021  0.863056  0.999140
real onion    0.632524  0.774853  0.728937  0.827056  0.999566
fake onion    0.902076  0.948468  0.973765  0.924547  0.999937
real unknown  0.908484  0.951998  0.998952  0.909351  0.999985
fake unknown  0.229114  0.372773  0.251876  0.717131  0.997967
total         0.750314  0.842688  0.876185  0.840426  0.999244
total(-bg)    0.739158  0.835636  0.870676  0.833247  0.999394
2026-10-10 16:13:34,469 - INFO: Epoch accounting: {'epoch': 481, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11253171, 43901, 41268, 119897, 107596, 100198, 70923, 184175, 182074, 99778, 88057, 27153, 20895, 235701, 147724, 161721, 19280, 64672, 75216, 75282, 58351, 12450, 48789], 'crops_with_class': [202, 29, 21, 33, 26, 32, 28, 29, 34, 42, 34, 9, 8, 53, 39, 24, 20, 21, 31, 31, 27, 18, 22], 'targeted_crops_by_class': [0, 7, 3, 0, 2, 5, 4, 3, 3, 5, 11, 6, 4, 5, 5, 5, 2, 4, 5, 3, 7, 7, 6], 'sampled_scene_counts': [0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 2, 0, 1, 1, 1, 1, 0, 2, 1, 3, 1, 0, 1, 1, 1, 1, 0, 0, 3, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 2, 1, 0, 1, 0, 1, 1, 1, 1, 2, 0, 0, 0, 1, 2, 2, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 3, 1, 4, 4, 3, 2, 1, 0, 0, 3, 1, 0, 0, 1, 2, 2, 0, 0, 0, 0, 6, 3, 1, 2, 2, 2, 2, 2, 1, 2, 4, 2, 1, 0, 1, 4, 0, 3, 1, 0, 2, 0, 3, 2, 1, 3, 0, 1, 3, 1, 1, 1, 0, 0, 3, 1, 1, 1, 1, 0, 0, 3, 0, 2, 0, 3, 0, 0, 1, 2, 0, 1, 1, 2, 2, 5, 1], 'learning_rate': 6.43279271940421e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005620544980767662, 'train_segmentation_loss': 0.2752213235391249, 'val_foreground_miou_all22': 0.7391578960148262, 'val_psnr_ref1': 39.05838653564453, 'elapsed_seconds': 325.1662435531616, 'peak_cuda_allocated_gib': 7.512241363525391}

Epoch 482/500 | Batch 10/202 | Rec 0.000590 | Seg 0.288076 | Elapsed 0.2m | ETA 4.1m
Epoch 482/500 | Batch 20/202 | Rec 0.000663 | Seg 0.317179 | Elapsed 0.4m | ETA 3.7m
Epoch 482/500 | Batch 30/202 | Rec 0.000620 | Seg 0.288856 | Elapsed 0.6m | ETA 3.6m
Epoch 482/500 | Batch 40/202 | Rec 0.000609 | Seg 0.289532 | Elapsed 0.8m | ETA 3.4m
Epoch 482/500 | Batch 50/202 | Rec 0.000609 | Seg 0.288074 | Elapsed 1.0m | ETA 3.1m
Epoch 482/500 | Batch 60/202 | Rec 0.000610 | Seg 0.278361 | Elapsed 1.2m | ETA 2.9m
Epoch 482/500 | Batch 70/202 | Rec 0.000613 | Seg 0.284986 | Elapsed 1.4m | ETA 2.7m
Epoch 482/500 | Batch 80/202 | Rec 0.000601 | Seg 0.286264 | Elapsed 1.6m | ETA 2.5m
Epoch 482/500 | Batch 90/202 | Rec 0.000600 | Seg 0.289047 | Elapsed 1.8m | ETA 2.3m
Epoch 482/500 | Batch 100/202 | Rec 0.000590 | Seg 0.281805 | Elapsed 2.0m | ETA 2.1m
Epoch 482/500 | Batch 110/202 | Rec 0.000589 | Seg 0.279827 | Elapsed 2.2m | ETA 1.9m
Epoch 482/500 | Batch 120/202 | Rec 0.000582 | Seg 0.277547 | Elapsed 2.4m | ETA 1.7m
Epoch 482/500 | Batch 130/202 | Rec 0.000568 | Seg 0.270882 | Elapsed 2.6m | ETA 1.5m
Epoch 482/500 | Batch 140/202 | Rec 0.000570 | Seg 0.272396 | Elapsed 2.8m | ETA 1.3m
Epoch 482/500 | Batch 150/202 | Rec 0.000576 | Seg 0.275527 | Elapsed 3.1m | ETA 1.1m
Epoch 482/500 | Batch 160/202 | Rec 0.000569 | Seg 0.273890 | Elapsed 3.3m | ETA 0.9m
Epoch 482/500 | Batch 170/202 | Rec 0.000569 | Seg 0.275633 | Elapsed 3.5m | ETA 0.7m
Epoch 482/500 | Batch 180/202 | Rec 0.000563 | Seg 0.270889 | Elapsed 3.7m | ETA 0.4m
Epoch 482/500 | Batch 190/202 | Rec 0.000567 | Seg 0.272037 | Elapsed 3.9m | ETA 0.2m
Epoch 482/500 | Batch 200/202 | Rec 0.000567 | Seg 0.272072 | Elapsed 4.1m | ETA 0.0m
Epoch 482/500 | Batch 202/202 | Rec 0.000566 | Seg 0.271827 | Elapsed 4.1m | ETA 0.0m

2026-10-10 16:17:42,371 - INFO: Rec loss: 0.0005662328049847119
2026-10-10 16:17:42,371 - INFO: Seg loss: 0.27182719987439047
2026-10-10 16:17:42,371 - INFO: λ_rec: 1
2026-10-10 16:17:42,371 - INFO: λ_seg: 0.0001
2026-10-10 16:19:05,275 - INFO: -------------------Epoch: 482------------------------
2026-10-10 16:19:05,279 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.008866  0.974903  0.000131
2026-10-10 16:19:05,285 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995371  0.997630  0.996669  0.998693  0.995578
real potato   0.905037  0.950102  0.961122  0.939429  0.999882
fake potato   0.867796  0.929169  0.984302  0.879975  0.999902
real apple    0.732777  0.845734  0.983524  0.741884  0.999067
fake apple    0.738277  0.849386  0.977892  0.750808  0.998995
real orange   0.881307  0.936859  0.996735  0.883858  0.999843
fake orange   0.916367  0.956308  0.937084  0.976442  0.999745
real grape    0.741830  0.851733  0.915553  0.796317  0.999421
fake grape    0.893061  0.943460  0.928167  0.959370  0.999575
real lemon    0.763606  0.865910  0.852453  0.879901  0.999680
fake lemon    0.838217  0.911940  0.986573  0.847890  0.999654
real avocado  0.936190  0.966994  0.965619  0.968473  0.999939
fake avocado  0.661566  0.796268  1.000000  0.661566  0.999595
real pepper   0.800438  0.889109  0.827006  0.961413  0.999123
fake pepper   0.662374  0.796853  0.946308  0.688240  0.999164
real plant    0.853960  0.921178  0.950072  0.894084  0.998471
fake plant    0.715481  0.834096  0.849225  0.819594  0.999741
real banana   0.750724  0.857565  0.910840  0.810268  0.999395
fake banana   0.719889  0.837084  0.833964  0.840328  0.999398
real onion    0.604493  0.753453  0.618722  0.963351  0.999431
fake onion    0.928333  0.962784  0.987046  0.939782  0.999954
real unknown  0.550750  0.710254  0.581962  0.911259  0.999881
fake unknown  0.258291  0.410500  0.295404  0.672763  0.998372
total         0.770267  0.859755  0.882011  0.860247  0.999296
total(-bg)    0.760035  0.853488  0.876799  0.853954  0.999465
2026-10-10 16:19:05,749 - INFO: Epoch accounting: {'epoch': 482, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11287590, 58459, 67169, 158723, 150739, 79091, 64489, 161844, 193609, 70852, 60935, 24101, 26556, 237849, 95952, 124509, 26731, 73647, 81601, 82252, 63038, 9080, 39456], 'crops_with_class': [202, 31, 28, 38, 39, 26, 23, 34, 31, 33, 26, 10, 10, 59, 31, 16, 23, 22, 33, 32, 30, 11, 21], 'targeted_crops_by_class': [0, 7, 7, 4, 8, 10, 2, 3, 7, 6, 2, 2, 3, 3, 6, 1, 9, 5, 4, 2, 6, 5, 4], 'sampled_scene_counts': [1, 0, 1, 0, 1, 0, 0, 1, 3, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 0, 0, 1, 2, 1, 0, 0, 1, 3, 1, 1, 0, 1, 0, 0, 1, 0, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 2, 1, 2, 0, 1, 0, 1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 2, 3, 2, 2, 1, 2, 0, 2, 2, 1, 0, 2, 1, 3, 0, 0, 2, 2, 2, 0, 2, 1, 1, 0, 0, 1, 2, 0, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 4, 0, 1, 4, 3, 0, 3, 1, 3, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 0, 1, 3, 1, 2, 4, 0, 1, 2, 3, 1, 1, 1, 1, 0, 1, 1, 1, 1, 2, 2, 2, 0, 1], 'learning_rate': 6.049800970805469e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005662328049847119, 'train_segmentation_loss': 0.27182719987439047, 'val_foreground_miou_all22': 0.7600347301338227, 'val_psnr_ref1': 39.0088655090332, 'elapsed_seconds': 331.27236247062683, 'peak_cuda_allocated_gib': 7.513706207275391}

Epoch 483/500 | Batch 10/202 | Rec 0.000507 | Seg 0.226298 | Elapsed 0.2m | ETA 4.0m
Epoch 483/500 | Batch 20/202 | Rec 0.000507 | Seg 0.242925 | Elapsed 0.4m | ETA 3.8m
Epoch 483/500 | Batch 30/202 | Rec 0.000520 | Seg 0.256927 | Elapsed 0.6m | ETA 3.6m
Epoch 483/500 | Batch 40/202 | Rec 0.000542 | Seg 0.261851 | Elapsed 0.8m | ETA 3.3m
Epoch 483/500 | Batch 50/202 | Rec 0.000536 | Seg 0.265719 | Elapsed 1.0m | ETA 3.1m
Epoch 483/500 | Batch 60/202 | Rec 0.000547 | Seg 0.277472 | Elapsed 1.2m | ETA 2.9m
Epoch 483/500 | Batch 70/202 | Rec 0.000575 | Seg 0.269392 | Elapsed 1.4m | ETA 2.7m
Epoch 483/500 | Batch 80/202 | Rec 0.000573 | Seg 0.268273 | Elapsed 1.6m | ETA 2.5m
Epoch 483/500 | Batch 90/202 | Rec 0.000564 | Seg 0.265431 | Elapsed 1.8m | ETA 2.3m
Epoch 483/500 | Batch 100/202 | Rec 0.000563 | Seg 0.269222 | Elapsed 2.0m | ETA 2.1m
Epoch 483/500 | Batch 110/202 | Rec 0.000553 | Seg 0.268786 | Elapsed 2.3m | ETA 1.9m
Epoch 483/500 | Batch 120/202 | Rec 0.000560 | Seg 0.269440 | Elapsed 2.5m | ETA 1.7m
Epoch 483/500 | Batch 130/202 | Rec 0.000559 | Seg 0.273915 | Elapsed 2.7m | ETA 1.5m
Epoch 483/500 | Batch 140/202 | Rec 0.000560 | Seg 0.277148 | Elapsed 2.9m | ETA 1.3m
Epoch 483/500 | Batch 150/202 | Rec 0.000557 | Seg 0.275218 | Elapsed 3.1m | ETA 1.1m
Epoch 483/500 | Batch 160/202 | Rec 0.000573 | Seg 0.274573 | Elapsed 3.3m | ETA 0.9m
Epoch 483/500 | Batch 170/202 | Rec 0.000573 | Seg 0.273906 | Elapsed 3.5m | ETA 0.7m
Epoch 483/500 | Batch 180/202 | Rec 0.000565 | Seg 0.269271 | Elapsed 3.7m | ETA 0.5m
Epoch 483/500 | Batch 190/202 | Rec 0.000557 | Seg 0.267237 | Elapsed 3.9m | ETA 0.2m
Epoch 483/500 | Batch 200/202 | Rec 0.000568 | Seg 0.269227 | Elapsed 4.1m | ETA 0.0m
Epoch 483/500 | Batch 202/202 | Rec 0.000567 | Seg 0.268502 | Elapsed 4.1m | ETA 0.0m

2026-10-10 16:23:14,507 - INFO: Rec loss: 0.0005668310789560835
2026-10-10 16:23:14,507 - INFO: Seg loss: 0.26850236151920687
2026-10-10 16:23:14,507 - INFO: λ_rec: 1
2026-10-10 16:23:14,507 - INFO: λ_seg: 0.0001
2026-10-10 16:24:34,252 - INFO: -------------------Epoch: 483------------------------
2026-10-10 16:24:34,256 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.082376  0.974959  0.000129
2026-10-10 16:24:34,262 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995787  0.997839  0.997533  0.998246  0.995979
real potato   0.909398  0.952500  0.945254  0.959959  0.999886
fake potato   0.956539  0.977737  0.973624  0.981986  0.999967
real apple    0.774776  0.873048  0.973507  0.791464  0.999206
fake apple    0.565863  0.722703  0.987467  0.569956  0.998349
real orange   0.932543  0.965044  0.993744  0.938050  0.999911
fake orange   0.941920  0.970041  0.959347  0.981079  0.999827
real grape    0.796362  0.886589  0.948983  0.831981  0.999556
fake grape    0.900221  0.947441  0.920129  0.976529  0.999600
real lemon    0.659941  0.795089  0.683077  0.951181  0.999424
fake lemon    0.848718  0.918120  0.998052  0.850126  0.999679
real avocado  0.918153  0.957280  0.951354  0.963383  0.999920
fake avocado  0.748757  0.856282  0.999490  0.749044  0.999699
real pepper   0.814220  0.897548  0.842656  0.960204  0.999199
fake pepper   0.703116  0.825633  0.951244  0.729403  0.999266
real plant    0.873691  0.932538  0.949307  0.916448  0.998675
fake plant    0.780427  0.876624  0.810952  0.953988  0.999786
real banana   0.640608  0.780890  0.867574  0.710037  0.999105
fake banana   0.716707  0.834929  0.797014  0.876742  0.999362
real onion    0.596932  0.747551  0.609655  0.966222  0.999411
fake onion    0.939151  0.968571  0.974309  0.962999  0.999961
real unknown  0.603587  0.752748  0.631715  0.931298  0.999902
fake unknown  0.230875  0.375101  0.252410  0.730170  0.997950
total         0.776013  0.861385  0.870365  0.881761  0.999288
total(-bg)    0.766023  0.855182  0.864585  0.876466  0.999438
2026-10-10 16:24:34,754 - INFO: Epoch accounting: {'epoch': 483, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11322369, 47448, 55402, 126153, 106857, 79061, 79463, 127409, 210220, 72857, 60583, 54803, 45973, 182597, 146136, 126701, 25729, 71446, 84851, 91775, 56337, 9879, 54223], 'crops_with_class': [202, 27, 23, 31, 31, 24, 26, 23, 39, 31, 28, 19, 16, 47, 34, 19, 25, 22, 31, 35, 25, 13, 24], 'targeted_crops_by_class': [0, 4, 6, 6, 3, 6, 3, 5, 5, 2, 5, 8, 4, 1, 5, 6, 5, 6, 6, 3, 5, 3, 5], 'sampled_scene_counts': [1, 0, 3, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 2, 0, 1, 0, 1, 1, 0, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0, 1, 1, 0, 2, 0, 1, 1, 0, 1, 3, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 3, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 2, 1, 1, 1, 2, 3, 2, 1, 2, 0, 2, 0, 2, 3, 2, 0, 2, 1, 1, 2, 0, 4, 3, 0, 1, 0, 1, 3, 1, 0, 6, 3, 1, 1, 1, 2, 1, 3, 3, 1, 2, 2, 1, 1, 1, 1, 1, 0, 3, 2, 2, 1, 2, 3, 0, 1, 2, 1, 1, 2, 0, 0, 3, 2, 1, 0, 2, 0, 2, 1, 0, 2, 1, 2, 0, 0, 2, 1], 'learning_rate': 5.68635887814581e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005668310789560835, 'train_segmentation_loss': 0.26850236151920687, 'val_foreground_miou_all22': 0.766022999102793, 'val_psnr_ref1': 39.08237594604492, 'elapsed_seconds': 328.9966745376587, 'peak_cuda_allocated_gib': 7.512485504150391}

Epoch 484/500 | Batch 10/202 | Rec 0.000446 | Seg 0.252048 | Elapsed 0.2m | ETA 4.0m
Epoch 484/500 | Batch 20/202 | Rec 0.000549 | Seg 0.270193 | Elapsed 0.4m | ETA 3.8m
Epoch 484/500 | Batch 30/202 | Rec 0.000577 | Seg 0.272615 | Elapsed 0.6m | ETA 3.5m
Epoch 484/500 | Batch 40/202 | Rec 0.000529 | Seg 0.250187 | Elapsed 0.8m | ETA 3.3m
Epoch 484/500 | Batch 50/202 | Rec 0.000519 | Seg 0.255428 | Elapsed 1.0m | ETA 3.1m
Epoch 484/500 | Batch 60/202 | Rec 0.000518 | Seg 0.251893 | Elapsed 1.2m | ETA 2.9m
Epoch 484/500 | Batch 70/202 | Rec 0.000527 | Seg 0.256641 | Elapsed 1.4m | ETA 2.7m
Epoch 484/500 | Batch 80/202 | Rec 0.000519 | Seg 0.253843 | Elapsed 1.6m | ETA 2.5m
Epoch 484/500 | Batch 90/202 | Rec 0.000524 | Seg 0.261975 | Elapsed 1.8m | ETA 2.3m
Epoch 484/500 | Batch 100/202 | Rec 0.000527 | Seg 0.261215 | Elapsed 2.0m | ETA 2.1m
Epoch 484/500 | Batch 110/202 | Rec 0.000529 | Seg 0.268434 | Elapsed 2.2m | ETA 1.9m
Epoch 484/500 | Batch 120/202 | Rec 0.000542 | Seg 0.270855 | Elapsed 2.5m | ETA 1.7m
Epoch 484/500 | Batch 130/202 | Rec 0.000546 | Seg 0.273075 | Elapsed 2.7m | ETA 1.5m
Epoch 484/500 | Batch 140/202 | Rec 0.000558 | Seg 0.271009 | Elapsed 2.9m | ETA 1.3m
Epoch 484/500 | Batch 150/202 | Rec 0.000555 | Seg 0.271391 | Elapsed 3.1m | ETA 1.1m
Epoch 484/500 | Batch 160/202 | Rec 0.000566 | Seg 0.275391 | Elapsed 3.3m | ETA 0.9m
Epoch 484/500 | Batch 170/202 | Rec 0.000565 | Seg 0.276142 | Elapsed 3.5m | ETA 0.7m
Epoch 484/500 | Batch 180/202 | Rec 0.000599 | Seg 0.284217 | Elapsed 3.7m | ETA 0.5m
Epoch 484/500 | Batch 190/202 | Rec 0.000598 | Seg 0.287164 | Elapsed 3.9m | ETA 0.2m
Epoch 484/500 | Batch 200/202 | Rec 0.000592 | Seg 0.282477 | Elapsed 4.1m | ETA 0.0m
Epoch 484/500 | Batch 202/202 | Rec 0.000592 | Seg 0.282897 | Elapsed 4.1m | ETA 0.0m

2026-10-10 16:28:42,894 - INFO: Rec loss: 0.0005924705412938481
2026-10-10 16:28:42,894 - INFO: Seg loss: 0.2828965091727453
2026-10-10 16:28:42,894 - INFO: λ_rec: 1
2026-10-10 16:28:42,895 - INFO: λ_seg: 0.0001
2026-10-10 16:30:01,768 - INFO: -------------------Epoch: 484------------------------
2026-10-10 16:30:01,772 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.990389  0.974847  0.000132
2026-10-10 16:30:01,778 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995614  0.997752  0.997212  0.998394  0.995813
real potato   0.898372  0.946416  0.910655  0.985208  0.999867
fake potato   0.959462  0.979262  0.972136  0.986594  0.999970
real apple    0.673147  0.804599  0.966625  0.689164  0.998846
fake apple    0.552177  0.711441  0.987019  0.556216  0.998297
real orange   0.935365  0.966553  0.996557  0.938397  0.999915
fake orange   0.943650  0.970958  0.960428  0.981825  0.999832
real grape    0.733239  0.846041  0.908009  0.792078  0.999398
fake grape    0.908912  0.952233  0.931652  0.973848  0.999639
real lemon    0.838407  0.912051  0.908751  0.915476  0.999793
fake lemon    0.788139  0.881469  0.998904  0.788821  0.999551
real avocado  0.961450  0.980296  0.994593  0.966502  0.999964
fake avocado  0.536912  0.698644  0.999763  0.536980  0.999446
real pepper   0.850576  0.919206  0.870862  0.973344  0.999375
fake pepper   0.752947  0.859015  0.948419  0.785097  0.999386
real plant    0.861101  0.925318  0.948778  0.903085  0.998543
fake plant    0.772345  0.871501  0.832461  0.914494  0.999785
real banana   0.775222  0.873330  0.886704  0.860451  0.999439
fake banana   0.676607  0.807065  0.760302  0.860070  0.999244
real onion    0.548637  0.708496  0.555098  0.979226  0.999272
fake onion    0.928217  0.962722  0.975192  0.950665  0.999954
real unknown  0.500000  0.666621  0.518558  0.933206  0.999851
fake unknown  0.199990  0.333284  0.217200  0.716226  0.997586
total         0.764804  0.851055  0.871560  0.868929  0.999251
total(-bg)    0.754312  0.844387  0.865848  0.863044  0.999407
2026-10-10 16:30:02,279 - INFO: Epoch accounting: {'epoch': 484, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11196361, 41704, 66602, 137228, 160416, 89893, 83189, 163462, 240317, 94540, 66674, 27564, 34376, 231381, 113038, 114352, 23818, 74660, 68056, 84885, 67373, 5736, 52647], 'crops_with_class': [202, 24, 30, 31, 37, 25, 28, 30, 44, 40, 31, 11, 12, 57, 30, 15, 21, 21, 28, 34, 28, 7, 23], 'targeted_crops_by_class': [0, 4, 6, 3, 5, 5, 5, 7, 9, 8, 4, 3, 3, 5, 3, 4, 6, 3, 6, 6, 3, 2, 4], 'sampled_scene_counts': [1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0, 0, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 0, 1, 0, 1, 2, 0, 0, 0, 0, 1, 2, 1, 0, 2, 0, 0, 0, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 4, 4, 1, 1, 1, 0, 0, 1, 1, 3, 3, 2, 3, 0, 1, 0, 1, 2, 3, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 2, 1, 2, 1, 0, 1, 1, 2, 1, 1, 2, 3, 2, 0, 1, 0, 1, 1, 2, 2, 1, 1, 1, 3, 0, 0, 1, 1, 2, 0, 1, 2, 2, 1, 1, 4, 3, 3, 0, 2, 2, 2, 1, 2, 1, 1, 1, 0, 2, 0, 2], 'learning_rate': 5.342480789496784e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005924705412938481, 'train_segmentation_loss': 0.2828965091727453, 'val_foreground_miou_all22': 0.7543124230504584, 'val_psnr_ref1': 38.99038925170898, 'elapsed_seconds': 327.51803970336914, 'peak_cuda_allocated_gib': 7.510021209716797}

Epoch 485/500 | Batch 10/202 | Rec 0.000494 | Seg 0.278940 | Elapsed 0.2m | ETA 3.9m
Epoch 485/500 | Batch 20/202 | Rec 0.000568 | Seg 0.333642 | Elapsed 0.4m | ETA 3.7m
Epoch 485/500 | Batch 30/202 | Rec 0.000604 | Seg 0.313433 | Elapsed 0.6m | ETA 3.5m
Epoch 485/500 | Batch 40/202 | Rec 0.000576 | Seg 0.301272 | Elapsed 0.8m | ETA 3.3m
Epoch 485/500 | Batch 50/202 | Rec 0.000556 | Seg 0.300481 | Elapsed 1.0m | ETA 3.1m
Epoch 485/500 | Batch 60/202 | Rec 0.000554 | Seg 0.296429 | Elapsed 1.2m | ETA 2.9m
Epoch 485/500 | Batch 70/202 | Rec 0.000568 | Seg 0.294467 | Elapsed 1.4m | ETA 2.7m
Epoch 485/500 | Batch 80/202 | Rec 0.000554 | Seg 0.288380 | Elapsed 1.6m | ETA 2.5m
Epoch 485/500 | Batch 90/202 | Rec 0.000548 | Seg 0.279458 | Elapsed 1.9m | ETA 2.3m
Epoch 485/500 | Batch 100/202 | Rec 0.000562 | Seg 0.279610 | Elapsed 2.1m | ETA 2.1m
Epoch 485/500 | Batch 110/202 | Rec 0.000591 | Seg 0.281033 | Elapsed 2.3m | ETA 1.9m
Epoch 485/500 | Batch 120/202 | Rec 0.000581 | Seg 0.277453 | Elapsed 2.5m | ETA 1.7m
Epoch 485/500 | Batch 130/202 | Rec 0.000580 | Seg 0.281929 | Elapsed 2.7m | ETA 1.5m
Epoch 485/500 | Batch 140/202 | Rec 0.000570 | Seg 0.276126 | Elapsed 2.9m | ETA 1.3m
Epoch 485/500 | Batch 150/202 | Rec 0.000590 | Seg 0.286272 | Elapsed 3.1m | ETA 1.1m
Epoch 485/500 | Batch 160/202 | Rec 0.000586 | Seg 0.282883 | Elapsed 3.3m | ETA 0.9m
Epoch 485/500 | Batch 170/202 | Rec 0.000588 | Seg 0.280776 | Elapsed 3.5m | ETA 0.7m
Epoch 485/500 | Batch 180/202 | Rec 0.000590 | Seg 0.281673 | Elapsed 3.7m | ETA 0.5m
Epoch 485/500 | Batch 190/202 | Rec 0.000581 | Seg 0.279090 | Elapsed 3.9m | ETA 0.2m
Epoch 485/500 | Batch 200/202 | Rec 0.000576 | Seg 0.278205 | Elapsed 4.1m | ETA 0.0m
Epoch 485/500 | Batch 202/202 | Rec 0.000575 | Seg 0.278727 | Elapsed 4.1m | ETA 0.0m

2026-10-10 16:34:10,723 - INFO: Rec loss: 0.000574579290235369
2026-10-10 16:34:10,723 - INFO: Seg loss: 0.2787269884997075
2026-10-10 16:34:10,723 - INFO: λ_rec: 1
2026-10-10 16:34:10,723 - INFO: λ_seg: 0.0001
2026-10-10 16:35:28,591 - INFO: -------------------Epoch: 485------------------------
2026-10-10 16:35:28,595 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.158923  0.975102  0.000127
2026-10-10 16:35:28,601 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995787  0.997839  0.997216  0.998564  0.995978
real potato   0.322749  0.487961  1.000000  0.322749  0.999190
fake potato   0.680688  0.809963  0.984417  0.688102  0.999765
real apple    0.675733  0.806443  0.732847  0.896594  0.998516
fake apple    0.661564  0.796267  0.976123  0.672446  0.998701
real orange   0.879862  0.936042  0.996211  0.882816  0.999841
fake orange   0.917795  0.957086  0.936324  0.978894  0.999749
real grape    0.840366  0.913210  0.958846  0.871812  0.999654
fake grape    0.891280  0.942465  0.914884  0.971868  0.999561
real lemon    0.436948  0.608118  0.447001  0.951052  0.998560
fake lemon    0.864925  0.927521  0.988415  0.873783  0.999711
real avocado  0.818764  0.900302  0.843177  0.965846  0.999801
fake avocado  0.812842  0.896711  0.998904  0.813568  0.999776
real pepper   0.768691  0.869170  0.807911  0.940597  0.998965
fake pepper   0.579485  0.733717  0.938104  0.602522  0.998958
real plant    0.877493  0.934699  0.959075  0.911627  0.998727
fake plant    0.739286  0.850053  0.867492  0.833397  0.999766
real banana   0.293671  0.453972  0.849981  0.309724  0.998326
fake banana   0.722979  0.839170  0.829231  0.849453  0.999401
real onion    0.513902  0.678860  0.707639  0.652424  0.999442
fake onion    0.912154  0.954009  0.994751  0.916566  0.999944
real unknown  0.923077  0.959950  0.994882  0.927481  0.999988
fake unknown  0.237687  0.384044  0.263409  0.708801  0.998085
total         0.711640  0.810329  0.868993  0.806117  0.999148
total(-bg)    0.698725  0.801806  0.863165  0.797369  0.999292
2026-10-10 16:35:29,075 - INFO: Epoch accounting: {'epoch': 485, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11265393, 32247, 44018, 151718, 132210, 96294, 94640, 186557, 162875, 81603, 79626, 48683, 23801, 218279, 109705, 147826, 29931, 88673, 78737, 74544, 42501, 10541, 37870], 'crops_with_class': [202, 20, 21, 38, 30, 27, 33, 31, 34, 35, 36, 16, 12, 56, 33, 19, 25, 28, 29, 34, 22, 12, 17], 'targeted_crops_by_class': [0, 4, 5, 6, 4, 7, 8, 3, 3, 3, 7, 5, 3, 6, 1, 6, 8, 5, 3, 4, 4, 4, 5], 'sampled_scene_counts': [2, 0, 1, 0, 1, 1, 2, 1, 0, 2, 1, 1, 2, 0, 0, 1, 0, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 2, 0, 0, 0, 1, 1, 2, 0, 0, 0, 1, 1, 3, 0, 3, 0, 1, 1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 0, 1, 0, 1, 1, 2, 1, 2, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 0, 2, 0, 1, 0, 1, 1, 0, 1, 1, 1, 2, 2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 3, 3, 1, 3, 2, 1, 4, 2, 1, 3, 2, 0, 2, 1, 1, 0, 0, 2, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 3, 1, 1, 4, 1, 2, 3, 3, 4, 2, 2, 1, 0, 3, 1, 0, 1, 2, 0, 2, 2, 1, 4, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 2, 0, 1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 1, 1, 3, 2], 'learning_rate': 5.018180280576536e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000574579290235369, 'train_segmentation_loss': 0.2787269884997075, 'val_foreground_miou_all22': 0.69872461739591, 'val_psnr_ref1': 39.15892349243164, 'elapsed_seconds': 326.7885277271271, 'peak_cuda_allocated_gib': 7.510776519775391}

Epoch 486/500 | Batch 10/202 | Rec 0.000489 | Seg 0.289130 | Elapsed 0.2m | ETA 4.0m
Epoch 486/500 | Batch 20/202 | Rec 0.000458 | Seg 0.230405 | Elapsed 0.4m | ETA 3.8m
Epoch 486/500 | Batch 30/202 | Rec 0.000479 | Seg 0.221403 | Elapsed 0.6m | ETA 3.6m
Epoch 486/500 | Batch 40/202 | Rec 0.000489 | Seg 0.233689 | Elapsed 0.8m | ETA 3.4m
Epoch 486/500 | Batch 50/202 | Rec 0.000499 | Seg 0.240818 | Elapsed 1.0m | ETA 3.1m
Epoch 486/500 | Batch 60/202 | Rec 0.000509 | Seg 0.247100 | Elapsed 1.2m | ETA 2.9m
Epoch 486/500 | Batch 70/202 | Rec 0.000519 | Seg 0.253466 | Elapsed 1.4m | ETA 2.7m
Epoch 486/500 | Batch 80/202 | Rec 0.000523 | Seg 0.261739 | Elapsed 1.6m | ETA 2.5m
Epoch 486/500 | Batch 90/202 | Rec 0.000516 | Seg 0.260510 | Elapsed 1.8m | ETA 2.3m
Epoch 486/500 | Batch 100/202 | Rec 0.000532 | Seg 0.260126 | Elapsed 2.1m | ETA 2.1m
Epoch 486/500 | Batch 110/202 | Rec 0.000547 | Seg 0.264115 | Elapsed 2.3m | ETA 1.9m
Epoch 486/500 | Batch 120/202 | Rec 0.000544 | Seg 0.262501 | Elapsed 2.5m | ETA 1.7m
Epoch 486/500 | Batch 130/202 | Rec 0.000537 | Seg 0.258404 | Elapsed 2.7m | ETA 1.5m
Epoch 486/500 | Batch 140/202 | Rec 0.000538 | Seg 0.258603 | Elapsed 2.9m | ETA 1.3m
Epoch 486/500 | Batch 150/202 | Rec 0.000540 | Seg 0.259824 | Elapsed 3.1m | ETA 1.1m
Epoch 486/500 | Batch 160/202 | Rec 0.000540 | Seg 0.260343 | Elapsed 3.3m | ETA 0.9m
Epoch 486/500 | Batch 170/202 | Rec 0.000538 | Seg 0.258029 | Elapsed 3.5m | ETA 0.7m
Epoch 486/500 | Batch 180/202 | Rec 0.000539 | Seg 0.260757 | Elapsed 3.7m | ETA 0.5m
Epoch 486/500 | Batch 190/202 | Rec 0.000533 | Seg 0.257287 | Elapsed 3.9m | ETA 0.2m
Epoch 486/500 | Batch 200/202 | Rec 0.000534 | Seg 0.260140 | Elapsed 4.1m | ETA 0.0m
Epoch 486/500 | Batch 202/202 | Rec 0.000533 | Seg 0.259786 | Elapsed 4.2m | ETA 0.0m

2026-10-10 16:39:38,622 - INFO: Rec loss: 0.000533388718449174
2026-10-10 16:39:38,622 - INFO: Seg loss: 0.2597858162025119
2026-10-10 16:39:38,622 - INFO: λ_rec: 1
2026-10-10 16:39:38,622 - INFO: λ_seg: 0.0001
2026-10-10 16:40:58,362 - INFO: -------------------Epoch: 486------------------------
2026-10-10 16:40:58,365 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.046831  0.975069  0.00013
2026-10-10 16:40:58,373 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995541  0.997715  0.997093  0.998438  0.995742
real potato   0.898244  0.946345  0.940554  0.952308  0.999871
fake potato   0.959462  0.979262  0.987021  0.971722  0.999970
real apple    0.767822  0.868615  0.964984  0.789828  0.999176
fake apple    0.541268  0.702322  0.989568  0.544374  0.998258
real orange   0.943085  0.970659  0.996827  0.945924  0.999925
fake orange   0.947202  0.972835  0.971412  0.974363  0.999845
real grape    0.752170  0.858509  0.912682  0.810495  0.999442
fake grape    0.901492  0.948144  0.921090  0.976942  0.999605
real lemon    0.840125  0.913067  0.885756  0.942223  0.999789
fake lemon    0.820264  0.901208  0.998072  0.821565  0.999619
real avocado  0.957262  0.978114  0.997100  0.959934  0.999960
fake avocado  0.676399  0.806919  0.999812  0.676486  0.999613
real pepper   0.851007  0.919457  0.871715  0.972843  0.999377
fake pepper   0.749453  0.856736  0.937671  0.788746  0.999371
real plant    0.858086  0.923574  0.953084  0.895930  0.998518
fake plant    0.742532  0.852195  0.842194  0.862538  0.999762
real banana   0.782804  0.878122  0.882143  0.874236  0.999455
fake banana   0.698857  0.822688  0.782475  0.867369  0.999312
real onion    0.655288  0.791703  0.675453  0.956426  0.999545
fake onion    0.920028  0.958299  0.980030  0.937606  0.999949
real unknown  0.620076  0.765442  0.649800  0.931298  0.999909
fake unknown  0.203333  0.337913  0.223608  0.691597  0.997717
total         0.786165  0.867384  0.885224  0.875791  0.999293
total(-bg)    0.776648  0.861460  0.880139  0.870216  0.999454
2026-10-10 16:40:58,846 - INFO: Epoch accounting: {'epoch': 486, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11389199, 43733, 47776, 138599, 140045, 80780, 66134, 121081, 173517, 74971, 54596, 53218, 41183, 188281, 133087, 101093, 24664, 90348, 83270, 74843, 47085, 12123, 58646], 'crops_with_class': [202, 29, 28, 34, 40, 27, 21, 25, 33, 31, 24, 18, 16, 52, 34, 15, 21, 27, 32, 29, 24, 15, 25], 'targeted_crops_by_class': [0, 2, 7, 8, 6, 1, 4, 5, 5, 7, 3, 5, 3, 4, 4, 1, 6, 4, 6, 4, 9, 8, 4], 'sampled_scene_counts': [0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 2, 2, 1, 0, 1, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 2, 2, 3, 1, 0, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 2, 1, 2, 2, 0, 2, 0, 3, 1, 1, 0, 2, 5, 3, 1, 2, 1, 1, 2, 0, 1, 2, 2, 0, 3, 1, 3, 1, 3, 1, 3, 1, 1, 5, 0, 2, 1, 0, 1, 2, 0, 3, 1, 2, 0, 0, 1, 1, 0, 0, 2, 2, 3, 3, 0, 0, 1, 3, 3, 2, 1, 1, 1, 2, 0, 1, 0, 1, 1], 'learning_rate': 4.7134701542138494e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000533388718449174, 'train_segmentation_loss': 0.2597858162025119, 'val_foreground_miou_all22': 0.7766482016046384, 'val_psnr_ref1': 39.04683135986328, 'elapsed_seconds': 329.7631678581238, 'peak_cuda_allocated_gib': 7.5077667236328125}

Epoch 487/500 | Batch 10/202 | Rec 0.000637 | Seg 0.277365 | Elapsed 0.2m | ETA 3.9m
Epoch 487/500 | Batch 20/202 | Rec 0.000593 | Seg 0.273087 | Elapsed 0.4m | ETA 3.7m
Epoch 487/500 | Batch 30/202 | Rec 0.000604 | Seg 0.283709 | Elapsed 0.6m | ETA 3.5m
Epoch 487/500 | Batch 40/202 | Rec 0.000646 | Seg 0.315123 | Elapsed 0.8m | ETA 3.3m
Epoch 487/500 | Batch 50/202 | Rec 0.000640 | Seg 0.316975 | Elapsed 1.0m | ETA 3.1m
Epoch 487/500 | Batch 60/202 | Rec 0.000615 | Seg 0.304946 | Elapsed 1.2m | ETA 2.9m
Epoch 487/500 | Batch 70/202 | Rec 0.000597 | Seg 0.293322 | Elapsed 1.4m | ETA 2.7m
Epoch 487/500 | Batch 80/202 | Rec 0.000592 | Seg 0.289603 | Elapsed 1.6m | ETA 2.5m
Epoch 487/500 | Batch 90/202 | Rec 0.000601 | Seg 0.293952 | Elapsed 1.8m | ETA 2.3m
Epoch 487/500 | Batch 100/202 | Rec 0.000611 | Seg 0.302423 | Elapsed 2.0m | ETA 2.1m
Epoch 487/500 | Batch 110/202 | Rec 0.000605 | Seg 0.298594 | Elapsed 2.2m | ETA 1.9m
Epoch 487/500 | Batch 120/202 | Rec 0.000603 | Seg 0.293298 | Elapsed 2.5m | ETA 1.7m
Epoch 487/500 | Batch 130/202 | Rec 0.000602 | Seg 0.292497 | Elapsed 2.6m | ETA 1.5m
Epoch 487/500 | Batch 140/202 | Rec 0.000600 | Seg 0.289522 | Elapsed 2.9m | ETA 1.3m
Epoch 487/500 | Batch 150/202 | Rec 0.000593 | Seg 0.285840 | Elapsed 3.1m | ETA 1.1m
Epoch 487/500 | Batch 160/202 | Rec 0.000587 | Seg 0.284736 | Elapsed 3.3m | ETA 0.9m
Epoch 487/500 | Batch 170/202 | Rec 0.000586 | Seg 0.284698 | Elapsed 3.5m | ETA 0.7m
Epoch 487/500 | Batch 180/202 | Rec 0.000585 | Seg 0.287793 | Elapsed 3.7m | ETA 0.5m
Epoch 487/500 | Batch 190/202 | Rec 0.000586 | Seg 0.287670 | Elapsed 3.9m | ETA 0.2m
Epoch 487/500 | Batch 200/202 | Rec 0.000588 | Seg 0.286102 | Elapsed 4.1m | ETA 0.0m
Epoch 487/500 | Batch 202/202 | Rec 0.000586 | Seg 0.284958 | Elapsed 4.1m | ETA 0.0m

2026-10-10 16:45:07,215 - INFO: Rec loss: 0.000585637095175098
2026-10-10 16:45:07,216 - INFO: Seg loss: 0.28495840014576324
2026-10-10 16:45:07,216 - INFO: λ_rec: 1
2026-10-10 16:45:07,216 - INFO: λ_seg: 0.0001
2026-10-10 16:46:28,704 - INFO: -------------------Epoch: 487------------------------
2026-10-10 16:46:28,708 - INFO:
Validation stats:
        PSNR    SSIM       MSE
0  38.880491  0.9747  0.000135
2026-10-10 16:46:28,715 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995679  0.997785  0.997048  0.998623  0.995874
real potato   0.905392  0.950297  0.941662  0.959194  0.999880
fake potato   0.961807  0.980482  0.979916  0.981148  0.999972
real apple    0.768317  0.868932  0.974915  0.783812  0.999185
fake apple    0.718613  0.836222  0.977821  0.730521  0.998920
real orange   0.863992  0.926984  0.991817  0.870195  0.999819
fake orange   0.911458  0.953628  0.925868  0.983211  0.999727
real grape    0.751906  0.858336  0.907071  0.814661  0.999439
fake grape    0.902151  0.948509  0.928941  0.969022  0.999611
real lemon    0.709616  0.830097  0.760982  0.913139  0.999561
fake lemon    0.848591  0.918045  0.992954  0.853732  0.999678
real avocado  0.934450  0.966064  0.960858  0.971429  0.999937
fake avocado  0.784331  0.879083  0.998702  0.785131  0.999742
real pepper   0.786718  0.880579  0.813264  0.960162  0.999048
fake pepper   0.631504  0.774089  0.944752  0.655720  0.999088
real plant    0.857706  0.923354  0.952753  0.895808  0.998513
fake plant    0.755814  0.860877  0.838329  0.884778  0.999772
real banana   0.711186  0.831170  0.912345  0.763344  0.999303
fake banana   0.728362  0.842785  0.828975  0.857167  0.999412
real onion    0.635161  0.776831  0.653931  0.956764  0.999503
fake onion    0.948858  0.973708  0.982997  0.964692  0.999967
real unknown  0.587022  0.739730  0.616953  0.923664  0.999896
fake unknown  0.293635  0.453925  0.337446  0.693408  0.998595
total         0.782273  0.868327  0.879144  0.876927  0.999324
total(-bg)    0.772572  0.862442  0.873784  0.871395  0.999480
2026-10-10 16:46:29,195 - INFO: Epoch accounting: {'epoch': 487, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11221474, 58409, 74021, 117287, 139516, 76161, 89791, 165224, 182698, 79140, 66158, 44296, 33521, 207436, 130888, 146285, 24708, 66974, 83905, 107325, 69555, 7762, 45738], 'crops_with_class': [202, 32, 33, 30, 33, 23, 28, 29, 37, 40, 29, 14, 13, 58, 35, 17, 21, 22, 37, 44, 35, 9, 16], 'targeted_crops_by_class': [0, 6, 2, 8, 2, 3, 9, 7, 5, 4, 7, 4, 5, 5, 6, 5, 4, 5, 8, 6, 6, 3, 5], 'sampled_scene_counts': [1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 2, 0, 1, 1, 0, 1, 2, 2, 0, 1, 1, 0, 0, 0, 1, 0, 3, 0, 0, 0, 1, 3, 0, 0, 0, 2, 0, 1, 1, 0, 1, 2, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 1, 0, 2, 2, 0, 1, 2, 1, 1, 2, 0, 1, 1, 2, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 4, 2, 2, 2, 2, 1, 1, 2, 1, 0, 3, 3, 2, 2, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0, 3, 0, 1, 1, 2, 2, 1, 2, 0, 1, 2, 2, 1, 1, 3, 0, 1, 3, 2, 2, 4, 1, 0, 0, 1, 1, 2, 2, 2, 3, 0, 2, 1, 0, 1, 2, 3, 1, 1, 2, 1, 1, 3, 0, 2, 2, 2, 1, 2, 0, 2, 3, 1, 1, 2, 1, 2], 'learning_rate': 4.428362439842711e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.000585637095175098, 'train_segmentation_loss': 0.28495840014576324, 'val_foreground_miou_all22': 0.7725722460955186, 'val_psnr_ref1': 38.88049072265625, 'elapsed_seconds': 330.3411900997162, 'peak_cuda_allocated_gib': 7.514469146728516}

Epoch 488/500 | Batch 10/202 | Rec 0.000650 | Seg 0.348276 | Elapsed 0.2m | ETA 3.9m
Epoch 488/500 | Batch 20/202 | Rec 0.000595 | Seg 0.302129 | Elapsed 0.4m | ETA 3.7m
Epoch 488/500 | Batch 30/202 | Rec 0.000611 | Seg 0.311610 | Elapsed 0.6m | ETA 3.5m
Epoch 488/500 | Batch 40/202 | Rec 0.000582 | Seg 0.300815 | Elapsed 0.8m | ETA 3.3m
Epoch 488/500 | Batch 50/202 | Rec 0.000580 | Seg 0.294376 | Elapsed 1.0m | ETA 3.1m
Epoch 488/500 | Batch 60/202 | Rec 0.000565 | Seg 0.282053 | Elapsed 1.2m | ETA 2.9m
Epoch 488/500 | Batch 70/202 | Rec 0.000568 | Seg 0.282186 | Elapsed 1.4m | ETA 2.7m
Epoch 488/500 | Batch 80/202 | Rec 0.000556 | Seg 0.275639 | Elapsed 1.6m | ETA 2.5m
Epoch 488/500 | Batch 90/202 | Rec 0.000560 | Seg 0.276361 | Elapsed 1.8m | ETA 2.3m
Epoch 488/500 | Batch 100/202 | Rec 0.000566 | Seg 0.282492 | Elapsed 2.0m | ETA 2.1m
Epoch 488/500 | Batch 110/202 | Rec 0.000563 | Seg 0.281042 | Elapsed 2.3m | ETA 1.9m
Epoch 488/500 | Batch 120/202 | Rec 0.000564 | Seg 0.279020 | Elapsed 2.5m | ETA 1.7m
Epoch 488/500 | Batch 130/202 | Rec 0.000563 | Seg 0.279896 | Elapsed 2.7m | ETA 1.5m
Epoch 488/500 | Batch 140/202 | Rec 0.000561 | Seg 0.278874 | Elapsed 2.9m | ETA 1.3m
Epoch 488/500 | Batch 150/202 | Rec 0.000559 | Seg 0.280675 | Elapsed 3.1m | ETA 1.1m
Epoch 488/500 | Batch 160/202 | Rec 0.000558 | Seg 0.280257 | Elapsed 3.3m | ETA 0.9m
Epoch 488/500 | Batch 170/202 | Rec 0.000552 | Seg 0.276234 | Elapsed 3.5m | ETA 0.7m
Epoch 488/500 | Batch 180/202 | Rec 0.000554 | Seg 0.274518 | Elapsed 3.7m | ETA 0.5m
Epoch 488/500 | Batch 190/202 | Rec 0.000555 | Seg 0.277787 | Elapsed 3.9m | ETA 0.2m
Epoch 488/500 | Batch 200/202 | Rec 0.000555 | Seg 0.277027 | Elapsed 4.1m | ETA 0.0m
Epoch 488/500 | Batch 202/202 | Rec 0.000553 | Seg 0.275947 | Elapsed 4.1m | ETA 0.0m

2026-10-10 16:50:37,951 - INFO: Rec loss: 0.0005529891667278981
2026-10-10 16:50:37,951 - INFO: Seg loss: 0.2759470086323448
2026-10-10 16:50:37,951 - INFO: λ_rec: 1
2026-10-10 16:50:37,951 - INFO: λ_seg: 0.0001
2026-10-10 16:51:59,172 - INFO: -------------------Epoch: 488------------------------
2026-10-10 16:51:59,177 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.149916  0.975205  0.000127
2026-10-10 16:51:59,183 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995694  0.997792  0.997069  0.998616  0.995888
real potato   0.767376  0.868329  0.962165  0.791252  0.999713
fake potato   0.782099  0.877678  0.977875  0.796188  0.999838
real apple    0.783110  0.878314  0.911765  0.847324  0.999190
fake apple    0.602327  0.751769  0.988410  0.606612  0.998488
real orange   0.889927  0.941708  0.995997  0.893122  0.999854
fake orange   0.918243  0.957329  0.942474  0.972764  0.999752
real grape    0.817965  0.899819  0.953612  0.851860  0.999604
fake grape    0.901416  0.948102  0.937785  0.958751  0.999612
real lemon    0.633074  0.775267  0.700629  0.867827  0.999409
fake lemon    0.854128  0.921276  0.986739  0.864046  0.999688
real avocado  0.914596  0.955343  0.943910  0.967159  0.999916
fake avocado  0.670066  0.802395  0.999620  0.670237  0.999605
real pepper   0.803925  0.891257  0.835395  0.955239  0.999148
fake pepper   0.680101  0.809546  0.942131  0.709750  0.999204
real plant    0.867419  0.928953  0.961466  0.898661  0.998626
fake plant    0.772408  0.871542  0.838830  0.907017  0.999787
real banana   0.682529  0.811263  0.887679  0.747046  0.999219
fake banana   0.699264  0.822970  0.783188  0.867120  0.999314
real onion    0.656553  0.792625  0.699961  0.913697  0.999568
fake onion    0.943719  0.970995  0.981235  0.961064  0.999964
real unknown  0.784330  0.879081  0.836348  0.926527  0.999959
fake unknown  0.210112  0.347222  0.232512  0.685621  0.997828
total         0.766538  0.856547  0.882469  0.854674  0.999269
total(-bg)    0.756122  0.850126  0.877260  0.848131  0.999422
2026-10-10 16:51:59,641 - INFO: Epoch accounting: {'epoch': 488, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11240626, 65238, 65943, 126824, 131817, 85464, 83488, 135955, 215013, 79775, 63942, 49117, 37035, 243902, 112524, 116273, 18628, 67001, 65603, 102030, 81291, 10050, 40733], 'crops_with_class': [202, 35, 30, 30, 37, 25, 28, 28, 32, 36, 31, 17, 15, 61, 33, 16, 20, 21, 24, 42, 37, 12, 21], 'targeted_crops_by_class': [0, 4, 4, 6, 4, 4, 3, 5, 1, 7, 3, 4, 5, 3, 8, 3, 8, 5, 4, 7, 6, 4, 5], 'sampled_scene_counts': [0, 0, 2, 0, 1, 1, 1, 0, 0, 2, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 2, 0, 2, 2, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 0, 2, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 0, 0, 2, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 3, 3, 0, 2, 2, 1, 2, 2, 2, 2, 3, 1, 3, 1, 3, 3, 2, 0, 2, 2, 2, 0, 3, 0, 1, 2, 0, 1, 0, 2, 2, 1, 2, 2, 3, 3, 0, 1, 1, 3, 1, 1, 0, 1, 2, 1, 2, 1, 0, 0, 3, 1, 0, 3, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 3, 1, 1, 0, 2, 1, 1, 2, 3, 1, 4], 'learning_rate': 4.162868393027601e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005529891667278981, 'train_segmentation_loss': 0.2759470086323448, 'val_foreground_miou_all22': 0.7561221053206623, 'val_psnr_ref1': 39.149916381835936, 'elapsed_seconds': 330.4388589859009, 'peak_cuda_allocated_gib': 7.510532379150391}

Epoch 489/500 | Batch 10/202 | Rec 0.000470 | Seg 0.265353 | Elapsed 0.2m | ETA 4.1m
Epoch 489/500 | Batch 20/202 | Rec 0.000462 | Seg 0.229942 | Elapsed 0.4m | ETA 3.8m
Epoch 489/500 | Batch 30/202 | Rec 0.000490 | Seg 0.249112 | Elapsed 0.6m | ETA 3.6m
Epoch 489/500 | Batch 40/202 | Rec 0.000533 | Seg 0.261049 | Elapsed 0.8m | ETA 3.4m
Epoch 489/500 | Batch 50/202 | Rec 0.000540 | Seg 0.281840 | Elapsed 1.0m | ETA 3.2m
Epoch 489/500 | Batch 60/202 | Rec 0.000540 | Seg 0.269594 | Elapsed 1.2m | ETA 2.9m
Epoch 489/500 | Batch 70/202 | Rec 0.000556 | Seg 0.272222 | Elapsed 1.4m | ETA 2.7m
Epoch 489/500 | Batch 80/202 | Rec 0.000549 | Seg 0.267198 | Elapsed 1.7m | ETA 2.5m
Epoch 489/500 | Batch 90/202 | Rec 0.000554 | Seg 0.271156 | Elapsed 1.9m | ETA 2.3m
Epoch 489/500 | Batch 100/202 | Rec 0.000553 | Seg 0.273724 | Elapsed 2.1m | ETA 2.1m
Epoch 489/500 | Batch 110/202 | Rec 0.000556 | Seg 0.275059 | Elapsed 2.3m | ETA 1.9m
Epoch 489/500 | Batch 120/202 | Rec 0.000553 | Seg 0.274855 | Elapsed 2.5m | ETA 1.7m
Epoch 489/500 | Batch 130/202 | Rec 0.000546 | Seg 0.273496 | Elapsed 2.7m | ETA 1.5m
Epoch 489/500 | Batch 140/202 | Rec 0.000543 | Seg 0.273419 | Elapsed 2.9m | ETA 1.3m
Epoch 489/500 | Batch 150/202 | Rec 0.000548 | Seg 0.275741 | Elapsed 3.1m | ETA 1.1m
Epoch 489/500 | Batch 160/202 | Rec 0.000555 | Seg 0.277247 | Elapsed 3.3m | ETA 0.9m
Epoch 489/500 | Batch 170/202 | Rec 0.000551 | Seg 0.272678 | Elapsed 3.5m | ETA 0.7m
Epoch 489/500 | Batch 180/202 | Rec 0.000550 | Seg 0.271459 | Elapsed 3.7m | ETA 0.5m
Epoch 489/500 | Batch 190/202 | Rec 0.000552 | Seg 0.273732 | Elapsed 3.9m | ETA 0.2m
Epoch 489/500 | Batch 200/202 | Rec 0.000560 | Seg 0.272685 | Elapsed 4.1m | ETA 0.0m
Epoch 489/500 | Batch 202/202 | Rec 0.000560 | Seg 0.273371 | Elapsed 4.2m | ETA 0.0m

2026-10-10 16:56:10,047 - INFO: Rec loss: 0.0005596703114933196
2026-10-10 16:56:10,047 - INFO: Seg loss: 0.2733712152458063
2026-10-10 16:56:10,047 - INFO: λ_rec: 1
2026-10-10 16:56:10,047 - INFO: λ_seg: 0.0001
2026-10-10 16:57:31,688 - INFO: -------------------Epoch: 489------------------------
2026-10-10 16:57:31,692 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.027809  0.974834  0.00013
2026-10-10 16:57:31,699 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995663  0.997777  0.997226  0.998428  0.995860
real potato   0.917460  0.956903  0.967301  0.946825  0.999898
fake potato   0.937820  0.967862  0.975532  0.960411  0.999954
real apple    0.786483  0.880433  0.981564  0.798275  0.999252
fake apple    0.605941  0.754577  0.976325  0.614977  0.998490
real orange   0.936909  0.967377  0.995832  0.940597  0.999917
fake orange   0.952700  0.975727  0.973577  0.977987  0.999861
real grape    0.763969  0.866144  0.953703  0.793393  0.999488
fake grape    0.896028  0.945113  0.914519  0.977932  0.999580
real lemon    0.581068  0.734984  0.631123  0.879901  0.999254
fake lemon    0.851071  0.919495  0.996548  0.853588  0.999684
real avocado  0.939968  0.969005  0.984743  0.953859  0.999943
fake avocado  0.606223  0.754796  1.000000  0.606223  0.999529
real pepper   0.918409  0.957420  0.947842  0.967295  0.999686
fake pepper   0.874810  0.933175  0.948081  0.918827  0.999687
real plant    0.864542  0.927300  0.947215  0.908302  0.998577
fake plant    0.751834  0.858290  0.787452  0.943252  0.999752
real banana   0.594273  0.745461  0.890261  0.641247  0.999016
fake banana   0.651295  0.788780  0.732036  0.855176  0.999158
real onion    0.636652  0.777945  0.659617  0.948151  0.999511
fake onion    0.917394  0.956868  0.974430  0.940024  0.999947
real unknown  0.719909  0.837098  0.776961  0.907443  0.999944
fake unknown  0.214770  0.353559  0.237839  0.688881  0.997878
total         0.778921  0.862004  0.880423  0.870478  0.999298
total(-bg)    0.769069  0.855832  0.875114  0.864662  0.999455
2026-10-10 16:57:32,157 - INFO: Epoch accounting: {'epoch': 489, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11319286, 54085, 76035, 124027, 117586, 72357, 79626, 150505, 186101, 70115, 47026, 47184, 30431, 219132, 127539, 125219, 21974, 104119, 95181, 69476, 51419, 7717, 42132], 'crops_with_class': [202, 35, 35, 29, 33, 23, 28, 26, 35, 31, 22, 19, 12, 50, 35, 17, 21, 33, 37, 34, 24, 9, 19], 'targeted_crops_by_class': [0, 4, 11, 5, 3, 4, 5, 4, 4, 3, 2, 4, 1, 0, 3, 0, 7, 9, 3, 9, 1, 5, 5], 'sampled_scene_counts': [0, 0, 1, 2, 1, 1, 0, 2, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 3, 0, 1, 0, 1, 1, 2, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 3, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 2, 0, 0, 1, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 0, 0, 1, 0, 1, 1, 2, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 2, 1, 1, 1, 1, 1, 1, 1, 0, 1, 3, 0, 0, 1, 2, 1, 2, 1, 1, 0, 2, 1, 2, 1, 1, 0, 1, 4, 1, 0, 0, 1, 5, 1, 1, 0, 1, 0, 1, 2, 1, 1, 3, 2, 0, 1, 2, 3, 0, 2, 2, 0, 0, 1, 3, 1, 3, 1, 2, 1, 2, 1, 1, 0, 1, 2, 1, 1, 0, 1, 2, 2, 2, 2, 2, 1, 3, 4, 1, 1, 4, 0, 1, 1, 1, 2, 2, 1, 1, 2], 'learning_rate': 3.916998495018799e-07, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0005596703114933196, 'train_segmentation_loss': 0.2733712152458063, 'val_foreground_miou_all22': 0.7690694224494369, 'val_psnr_ref1': 39.02780853271484, 'elapsed_seconds': 332.5086119174957, 'peak_cuda_allocated_gib': 7.506137847900391}

Epoch 490/500 | Batch 10/202 | Rec 0.000621 | Seg 0.248183 | Elapsed 0.2m | ETA 3.9m
Epoch 490/500 | Batch 20/202 | Rec 0.000538 | Seg 0.263790 | Elapsed 0.4m | ETA 3.7m
Epoch 490/500 | Batch 30/202 | Rec 0.000553 | Seg 0.298786 | Elapsed 0.6m | ETA 3.5m
Epoch 490/500 | Batch 40/202 | Rec 0.000544 | Seg 0.293720 | Elapsed 0.8m | ETA 3.3m
Epoch 490/500 | Batch 50/202 | Rec 0.000574 | Seg 0.299807 | Elapsed 1.0m | ETA 3.1m
Epoch 490/500 | Batch 60/202 | Rec 0.000573 | Seg 0.287011 | Elapsed 1.2m | ETA 2.9m
Epoch 490/500 | Batch 70/202 | Rec 0.000593 | Seg 0.294595 | Elapsed 1.4m | ETA 2.7m
Epoch 490/500 | Batch 80/202 | Rec 0.000577 | Seg 0.284572 | Elapsed 1.6m | ETA 2.5m
Epoch 490/500 | Batch 90/202 | Rec 0.000566 | Seg 0.280956 | Elapsed 1.8m | ETA 2.3m
Epoch 490/500 | Batch 100/202 | Rec 0.000572 | Seg 0.282528 | Elapsed 2.0m | ETA 2.1m
Epoch 490/500 | Batch 110/202 | Rec 0.000578 | Seg 0.289737 | Elapsed 2.2m | ETA 1.9m
Epoch 490/500 | Batch 120/202 | Rec 0.000568 | Seg 0.287145 | Elapsed 2.4m | ETA 1.7m
Epoch 490/500 | Batch 130/202 | Rec 0.000567 | Seg 0.283644 | Elapsed 2.6m | ETA 1.5m
Epoch 490/500 | Batch 140/202 | Rec 0.000565 | Seg 0.284485 | Elapsed 2.9m | ETA 1.3m
Epoch 490/500 | Batch 150/202 | Rec 0.000564 | Seg 0.282390 | Elapsed 3.1m | ETA 1.1m
Epoch 490/500 | Batch 160/202 | Rec 0.000568 | Seg 0.283147 | Elapsed 3.3m | ETA 0.9m
Epoch 490/500 | Batch 170/202 | Rec 0.000570 | Seg 0.283886 | Elapsed 3.5m | ETA 0.7m
Epoch 490/500 | Batch 180/202 | Rec 0.000568 | Seg 0.281771 | Elapsed 3.7m | ETA 0.4m
Epoch 490/500 | Batch 190/202 | Rec 0.000564 | Seg 0.281957 | Elapsed 3.9m | ETA 0.2m
Epoch 490/500 | Batch 200/202 | Rec 0.000564 | Seg 0.282930 | Elapsed 4.1m | ETA 0.0m
Epoch 490/500 | Batch 202/202 | Rec 0.000564 | Seg 0.282141 | Elapsed 4.1m | ETA 0.0m

2026-10-10 17:01:39,363 - INFO: Rec loss: 0.0005638549159947174
2026-10-10 17:01:39,363 - INFO: Seg loss: 0.2821414689763938
2026-10-10 17:01:39,364 - INFO: λ_rec: 1
2026-10-10 17:01:39,364 - INFO: λ_seg: 0.0001
2026-10-10 17:02:58,948 - INFO: -------------------Epoch: 490------------------------
2026-10-10 17:02:58,952 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  39.167581  0.97511  0.000126
2026-10-10 17:02:58,958 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995625  0.997758  0.997348  0.998268  0.995824
real potato   0.386156  0.557121  0.985123  0.388421  0.999261
fake potato   0.658091  0.793746  0.985705  0.664432  0.999749
real apple    0.705317  0.827148  0.785515  0.873552  0.998741
fake apple    0.619105  0.764702  0.985094  0.624960  0.998548
real orange   0.943124  0.970680  0.996101  0.946619  0.999925
fake orange   0.945865  0.972129  0.968426  0.975962  0.999840
real grape    0.798892  0.888155  0.965748  0.822188  0.999568
fake grape    0.891604  0.942646  0.907073  0.981232  0.999559
real lemon    0.519969  0.684138  0.532481  0.956764  0.998962
fake lemon    0.860410  0.924918  0.996668  0.862892  0.999704
real avocado  0.866913  0.928663  0.896167  0.963711  0.999863
fake avocado  0.738144  0.849298  0.999655  0.738332  0.999687
real pepper   0.791597  0.883628  0.823455  0.953404  0.999082
fake pepper   0.641509  0.781561  0.963860  0.657320  0.999124
real plant    0.867087  0.928763  0.949821  0.908714  0.998607
fake plant    0.882418  0.937487  0.954871  0.920821  0.999902
real banana   0.454360  0.624778  0.832900  0.499932  0.998651
fake banana   0.712457  0.832038  0.802978  0.863388  0.999359
real onion    0.646845  0.785508  0.695714  0.902044  0.999555
fake onion    0.927116  0.962130  0.990776  0.935187  0.999954
real unknown  0.796596  0.886734  0.840890  0.937977  0.999962
fake unknown  0.226105  0.368783  0.241701  0.777979  0.997756
total         0.733709  0.830109  0.873829  0.832787  0.999182
total(-bg)    0.721804  0.822489  0.868215  0.825265  0.999334
2026-10-10 17:02:59,419 - INFO: Epoch accounting: {'epoch': 490, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11238593, 67756, 71937, 110998, 165653, 84860, 93810, 180467, 176579, 71710, 60892, 34973, 29280, 219196, 124613, 107817, 23157, 101249, 73050, 87579, 57785, 11346, 44972], 'crops_with_class': [202, 38, 33, 31, 42, 34, 32, 30, 39, 33, 26, 13, 11, 57, 30, 13, 22, 27, 30, 33, 24, 15, 21], 'targeted_crops_by_class': [0, 2, 4, 6, 5, 8, 4, 1, 4, 2, 5, 5, 4, 6, 5, 4, 7, 7, 5, 6, 7, 8, 5], 'sampled_scene_counts': [0, 1, 0, 1, 1, 2, 2, 1, 2, 3, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 2, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 2, 2, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 2, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 2, 1, 3, 1, 1, 1, 1, 1, 2, 2, 0, 1, 2, 2, 2, 1, 4, 1, 1, 1, 2, 1, 0, 2, 0, 2, 5, 2, 1, 0, 0, 2, 1, 1, 1, 4, 1, 3, 2, 1, 2, 2, 1, 2, 2, 1, 3, 0, 2, 3, 0, 0, 4, 4, 0, 3, 3, 1, 0, 1, 1, 0, 1, 4, 1, 1, 2, 3, 1, 1, 3, 1, 1, 1, 1, 2, 1, 3, 2, 1, 0, 1], 'learning_rate': 3.6907624523389174e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005638549159947174, 'train_segmentation_loss': 0.2821414689763938, 'val_foreground_miou_all22': 0.7218037272010852, 'val_psnr_ref1': 39.1675813293457, 'elapsed_seconds': 327.2542712688446, 'peak_cuda_allocated_gib': 7.5103302001953125}

Epoch 491/500 | Batch 10/202 | Rec 0.000516 | Seg 0.240672 | Elapsed 0.2m | ETA 4.0m
Epoch 491/500 | Batch 20/202 | Rec 0.000538 | Seg 0.251056 | Elapsed 0.4m | ETA 3.8m
Epoch 491/500 | Batch 30/202 | Rec 0.000613 | Seg 0.263822 | Elapsed 0.6m | ETA 3.5m
Epoch 491/500 | Batch 40/202 | Rec 0.000583 | Seg 0.264689 | Elapsed 0.8m | ETA 3.3m
Epoch 491/500 | Batch 50/202 | Rec 0.000581 | Seg 0.261507 | Elapsed 1.0m | ETA 3.1m
Epoch 491/500 | Batch 60/202 | Rec 0.000553 | Seg 0.255946 | Elapsed 1.2m | ETA 2.9m
Epoch 491/500 | Batch 70/202 | Rec 0.000565 | Seg 0.254886 | Elapsed 1.4m | ETA 2.7m
Epoch 491/500 | Batch 80/202 | Rec 0.000558 | Seg 0.252439 | Elapsed 1.6m | ETA 2.5m
Epoch 491/500 | Batch 90/202 | Rec 0.000551 | Seg 0.253510 | Elapsed 1.9m | ETA 2.3m
Epoch 491/500 | Batch 100/202 | Rec 0.000549 | Seg 0.251228 | Elapsed 2.1m | ETA 2.1m
Epoch 491/500 | Batch 110/202 | Rec 0.000536 | Seg 0.249312 | Elapsed 2.3m | ETA 1.9m
Epoch 491/500 | Batch 120/202 | Rec 0.000537 | Seg 0.255934 | Elapsed 2.5m | ETA 1.7m
Epoch 491/500 | Batch 130/202 | Rec 0.000541 | Seg 0.259826 | Elapsed 2.7m | ETA 1.5m
Epoch 491/500 | Batch 140/202 | Rec 0.000544 | Seg 0.260182 | Elapsed 2.9m | ETA 1.3m
Epoch 491/500 | Batch 150/202 | Rec 0.000545 | Seg 0.261683 | Elapsed 3.1m | ETA 1.1m
Epoch 491/500 | Batch 160/202 | Rec 0.000543 | Seg 0.260783 | Elapsed 3.3m | ETA 0.9m
Epoch 491/500 | Batch 170/202 | Rec 0.000541 | Seg 0.262062 | Elapsed 3.5m | ETA 0.7m
Epoch 491/500 | Batch 180/202 | Rec 0.000546 | Seg 0.259621 | Elapsed 3.7m | ETA 0.5m
Epoch 491/500 | Batch 190/202 | Rec 0.000550 | Seg 0.258888 | Elapsed 3.9m | ETA 0.2m
Epoch 491/500 | Batch 200/202 | Rec 0.000552 | Seg 0.259971 | Elapsed 4.1m | ETA 0.0m
Epoch 491/500 | Batch 202/202 | Rec 0.000552 | Seg 0.260003 | Elapsed 4.2m | ETA 0.0m

2026-10-10 17:07:09,465 - INFO: Rec loss: 0.0005520216582226567
2026-10-10 17:07:09,465 - INFO: Seg loss: 0.2600027007410432
2026-10-10 17:07:09,465 - INFO: λ_rec: 1
2026-10-10 17:07:09,465 - INFO: λ_seg: 0.0001
2026-10-10 17:08:22,574 - INFO: -------------------Epoch: 491------------------------
2026-10-10 17:08:22,578 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.031857  0.974944  0.00013
2026-10-10 17:08:22,584 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995490  0.997690  0.996904  0.998577  0.995693
real potato   0.911600  0.953706  0.935172  0.973094  0.999887
fake potato   0.964455  0.981856  0.986264  0.977587  0.999974
real apple    0.749247  0.856602  0.982767  0.759222  0.999123
fake apple    0.610819  0.758348  0.989783  0.614694  0.998521
real orange   0.913104  0.954528  0.994852  0.917439  0.999885
fake orange   0.930130  0.963751  0.957739  0.969939  0.999791
real grape    0.756927  0.861599  0.922154  0.808595  0.999458
fake grape    0.900348  0.947511  0.924030  0.972322  0.999602
real lemon    0.764790  0.866671  0.907876  0.829135  0.999700
fake lemon    0.744412  0.853433  0.999516  0.744681  0.999459
real avocado  0.958960  0.979000  0.995586  0.963054  0.999962
fake avocado  0.512114  0.677304  1.000000  0.512114  0.999416
real pepper   0.812590  0.896557  0.834862  0.968213  0.999183
fake pepper   0.677523  0.807717  0.946504  0.704500  0.999201
real plant    0.854384  0.921425  0.953650  0.891399  0.998480
fake plant    0.765528  0.867145  0.834456  0.902607  0.999780
real banana   0.796497  0.886673  0.896571  0.877088  0.999496
fake banana   0.608814  0.756799  0.678278  0.856005  0.998988
real onion    0.600563  0.750393  0.611017  0.972302  0.999416
fake onion    0.933853  0.965745  0.975808  0.955985  0.999957
real unknown  0.569552  0.725703  0.603416  0.910305  0.999890
fake unknown  0.199500  0.332601  0.225170  0.636364  0.997849
total         0.762226  0.850555  0.876190  0.857184  0.999248
total(-bg)    0.751623  0.843867  0.870703  0.850757  0.999410
2026-10-10 17:08:23,045 - INFO: Epoch accounting: {'epoch': 491, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11361634, 64869, 72911, 106321, 121289, 103317, 54562, 168107, 155287, 70464, 56247, 47729, 40328, 222542, 127437, 105535, 23788, 50692, 62358, 94963, 67504, 9930, 50458], 'crops_with_class': [202, 32, 29, 29, 35, 30, 19, 29, 31, 36, 24, 17, 15, 55, 26, 15, 22, 17, 23, 36, 27, 13, 18], 'targeted_crops_by_class': [0, 5, 6, 3, 2, 4, 5, 8, 8, 5, 4, 4, 1, 2, 5, 2, 3, 4, 5, 1, 7, 5, 5], 'sampled_scene_counts': [0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 2, 2, 1, 3, 1, 2, 1, 2, 0, 1, 1, 0, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 1, 1, 0, 2, 0, 2, 1, 0, 1, 0, 1, 2, 1, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 2, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 4, 1, 1, 1, 2, 0, 1, 1, 2, 0, 2, 2, 4, 1, 3, 1, 2, 1, 2, 2, 0, 3, 1, 1, 2, 4, 1, 1, 2, 2, 1, 1, 1, 2, 0, 2, 2, 0, 1, 1, 0, 5, 3, 1, 1, 3, 1, 2, 1, 1, 2, 2, 3, 1, 0, 1, 0, 0, 0, 3, 0, 1, 3, 0, 1, 0, 1, 3], 'learning_rate': 3.4841691963995593e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005520216582226567, 'train_segmentation_loss': 0.2600027007410432, 'val_foreground_miou_all22': 0.7516232107175658, 'val_psnr_ref1': 39.0318569946289, 'elapsed_seconds': 323.6183466911316, 'peak_cuda_allocated_gib': 7.5126190185546875}

Epoch 492/500 | Batch 10/202 | Rec 0.000517 | Seg 0.245431 | Elapsed 0.2m | ETA 4.0m
Epoch 492/500 | Batch 20/202 | Rec 0.000520 | Seg 0.242979 | Elapsed 0.4m | ETA 3.8m
Epoch 492/500 | Batch 30/202 | Rec 0.000503 | Seg 0.236452 | Elapsed 0.6m | ETA 3.5m
Epoch 492/500 | Batch 40/202 | Rec 0.000542 | Seg 0.263639 | Elapsed 0.8m | ETA 3.3m
Epoch 492/500 | Batch 50/202 | Rec 0.000560 | Seg 0.276747 | Elapsed 1.0m | ETA 3.1m
Epoch 492/500 | Batch 60/202 | Rec 0.000558 | Seg 0.280882 | Elapsed 1.2m | ETA 2.9m
Epoch 492/500 | Batch 70/202 | Rec 0.000547 | Seg 0.272475 | Elapsed 1.4m | ETA 2.7m
Epoch 492/500 | Batch 80/202 | Rec 0.000557 | Seg 0.276233 | Elapsed 1.6m | ETA 2.5m
Epoch 492/500 | Batch 90/202 | Rec 0.000552 | Seg 0.272303 | Elapsed 1.8m | ETA 2.3m
Epoch 492/500 | Batch 100/202 | Rec 0.000553 | Seg 0.270339 | Elapsed 2.1m | ETA 2.1m
Epoch 492/500 | Batch 110/202 | Rec 0.000553 | Seg 0.268043 | Elapsed 2.3m | ETA 1.9m
Epoch 492/500 | Batch 120/202 | Rec 0.000560 | Seg 0.269311 | Elapsed 2.5m | ETA 1.7m
Epoch 492/500 | Batch 130/202 | Rec 0.000562 | Seg 0.272657 | Elapsed 2.7m | ETA 1.5m
Epoch 492/500 | Batch 140/202 | Rec 0.000563 | Seg 0.272810 | Elapsed 2.9m | ETA 1.3m
Epoch 492/500 | Batch 150/202 | Rec 0.000555 | Seg 0.270991 | Elapsed 3.1m | ETA 1.1m
Epoch 492/500 | Batch 160/202 | Rec 0.000563 | Seg 0.268370 | Elapsed 3.3m | ETA 0.9m
Epoch 492/500 | Batch 170/202 | Rec 0.000555 | Seg 0.266275 | Elapsed 3.5m | ETA 0.7m
Epoch 492/500 | Batch 180/202 | Rec 0.000553 | Seg 0.266663 | Elapsed 3.7m | ETA 0.5m
Epoch 492/500 | Batch 190/202 | Rec 0.000556 | Seg 0.267918 | Elapsed 3.9m | ETA 0.2m
Epoch 492/500 | Batch 200/202 | Rec 0.000552 | Seg 0.266302 | Elapsed 4.1m | ETA 0.0m
Epoch 492/500 | Batch 202/202 | Rec 0.000555 | Seg 0.268055 | Elapsed 4.2m | ETA 0.0m

2026-10-10 17:12:32,539 - INFO: Rec loss: 0.0005547496020340933
2026-10-10 17:12:32,539 - INFO: Seg loss: 0.26805532662806536
2026-10-10 17:12:32,539 - INFO: λ_rec: 1
2026-10-10 17:12:32,539 - INFO: λ_seg: 0.0001
2026-10-10 17:13:53,894 - INFO: -------------------Epoch: 492------------------------
2026-10-10 17:13:53,898 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.096214  0.974945  0.000129
2026-10-10 17:13:53,904 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995786  0.997839  0.997281  0.998498  0.995978
real potato   0.368582  0.538594  0.997586  0.368911  0.999244
fake potato   0.654987  0.791483  0.984726  0.661709  0.999746
real apple    0.710128  0.830447  0.789214  0.876338  0.998766
fake apple    0.656541  0.792616  0.957911  0.676043  0.998665
real orange   0.926981  0.962057  0.995910  0.930523  0.999903
fake orange   0.942351  0.970270  0.959846  0.981025  0.999828
real grape    0.815492  0.898320  0.968246  0.837901  0.999604
fake grape    0.886168  0.939599  0.910766  0.970424  0.999539
real lemon    0.411111  0.582634  0.421873  0.941574  0.998415
fake lemon    0.863030  0.926430  0.986954  0.872990  0.999707
real avocado  0.826154  0.904752  0.852681  0.963711  0.999812
fake avocado  0.827876  0.905784  0.998924  0.828615  0.999794
real pepper   0.847056  0.917146  0.900708  0.934298  0.999383
fake pepper   0.767925  0.868681  0.960025  0.793291  0.999429
real plant    0.875452  0.933540  0.947569  0.920018  0.998691
fake plant    0.842341  0.914374  0.926757  0.902416  0.999866
real banana   0.209783  0.346777  0.808304  0.220766  0.998131
fake banana   0.703789  0.826096  0.818975  0.833444  0.999355
real onion    0.645803  0.784738  0.702631  0.888701  0.999560
fake onion    0.903643  0.949333  0.990281  0.911729  0.999939
real unknown  0.918944  0.957710  0.986842  0.930343  0.999987
fake unknown  0.248347  0.397843  0.270095  0.755161  0.998074
total         0.732533  0.823351  0.875396  0.826019  0.999192
total(-bg)    0.720567  0.815419  0.869856  0.818179  0.999338
2026-10-10 17:13:54,366 - INFO: Epoch accounting: {'epoch': 492, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11351692, 52819, 71648, 113203, 169245, 80365, 58129, 134923, 155649, 71550, 44140, 29494, 53214, 191594, 99120, 177991, 31670, 90781, 73240, 80301, 58431, 12620, 36453], 'crops_with_class': [202, 26, 31, 32, 43, 25, 26, 27, 30, 31, 20, 11, 18, 49, 23, 22, 26, 25, 29, 35, 25, 13, 18], 'targeted_crops_by_class': [0, 5, 2, 5, 3, 7, 5, 1, 2, 3, 2, 0, 8, 4, 2, 4, 7, 5, 7, 3, 6, 5, 4], 'sampled_scene_counts': [1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 2, 0, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 2, 1, 1, 3, 2, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 3, 1, 2, 1, 0, 0, 0, 1, 1, 0, 2, 1, 1, 0, 2, 2, 1, 0, 0, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 3, 1, 1, 0, 2, 3, 1, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 0, 2, 3, 0, 0, 2, 2, 3, 1, 1, 2, 1, 1, 0, 1, 0, 1, 0, 1, 0, 4, 1, 3, 1, 3, 0, 1, 1, 0, 0, 2, 0, 0, 1, 3, 3, 3, 1, 2, 0, 2, 1, 3, 1, 1, 1, 1, 1, 2, 1, 2, 3, 2, 2, 4, 0, 0, 0, 2, 1, 3, 0, 1], 'learning_rate': 3.297226883148707e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005547496020340933, 'train_segmentation_loss': 0.26805532662806536, 'val_foreground_miou_all22': 0.7205674589417863, 'val_psnr_ref1': 39.09621398925781, 'elapsed_seconds': 331.31379890441895, 'peak_cuda_allocated_gib': 7.505313873291016}

Epoch 493/500 | Batch 10/202 | Rec 0.000575 | Seg 0.302214 | Elapsed 0.2m | ETA 3.9m
Epoch 493/500 | Batch 20/202 | Rec 0.000580 | Seg 0.261199 | Elapsed 0.4m | ETA 3.8m
Epoch 493/500 | Batch 30/202 | Rec 0.000531 | Seg 0.247058 | Elapsed 0.6m | ETA 3.5m
Epoch 493/500 | Batch 40/202 | Rec 0.000534 | Seg 0.241027 | Elapsed 0.8m | ETA 3.3m
Epoch 493/500 | Batch 50/202 | Rec 0.000549 | Seg 0.256694 | Elapsed 1.0m | ETA 3.1m
Epoch 493/500 | Batch 60/202 | Rec 0.000544 | Seg 0.259110 | Elapsed 1.2m | ETA 2.9m
Epoch 493/500 | Batch 70/202 | Rec 0.000551 | Seg 0.255352 | Elapsed 1.4m | ETA 2.7m
Epoch 493/500 | Batch 80/202 | Rec 0.000560 | Seg 0.260822 | Elapsed 1.6m | ETA 2.5m
Epoch 493/500 | Batch 90/202 | Rec 0.000566 | Seg 0.259725 | Elapsed 1.8m | ETA 2.3m
Epoch 493/500 | Batch 100/202 | Rec 0.000570 | Seg 0.265040 | Elapsed 2.0m | ETA 2.1m
Epoch 493/500 | Batch 110/202 | Rec 0.000560 | Seg 0.261942 | Elapsed 2.3m | ETA 1.9m
Epoch 493/500 | Batch 120/202 | Rec 0.000564 | Seg 0.261133 | Elapsed 2.5m | ETA 1.7m
Epoch 493/500 | Batch 130/202 | Rec 0.000559 | Seg 0.259600 | Elapsed 2.7m | ETA 1.5m
Epoch 493/500 | Batch 140/202 | Rec 0.000554 | Seg 0.259444 | Elapsed 2.9m | ETA 1.3m
Epoch 493/500 | Batch 150/202 | Rec 0.000550 | Seg 0.262165 | Elapsed 3.1m | ETA 1.1m
Epoch 493/500 | Batch 160/202 | Rec 0.000559 | Seg 0.267033 | Elapsed 3.3m | ETA 0.9m
Epoch 493/500 | Batch 170/202 | Rec 0.000558 | Seg 0.265224 | Elapsed 3.5m | ETA 0.7m
Epoch 493/500 | Batch 180/202 | Rec 0.000554 | Seg 0.265124 | Elapsed 3.7m | ETA 0.4m
Epoch 493/500 | Batch 190/202 | Rec 0.000554 | Seg 0.264691 | Elapsed 3.9m | ETA 0.2m
Epoch 493/500 | Batch 200/202 | Rec 0.000556 | Seg 0.265169 | Elapsed 4.1m | ETA 0.0m
Epoch 493/500 | Batch 202/202 | Rec 0.000559 | Seg 0.266521 | Elapsed 4.1m | ETA 0.0m

2026-10-10 17:18:02,419 - INFO: Rec loss: 0.0005593751397244356
2026-10-10 17:18:02,419 - INFO: Seg loss: 0.2665214105739747
2026-10-10 17:18:02,419 - INFO: λ_rec: 1
2026-10-10 17:18:02,419 - INFO: λ_seg: 0.0001
2026-10-10 17:19:19,483 - INFO: -------------------Epoch: 493------------------------
2026-10-10 17:19:19,487 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.172906  0.975109  0.000126
2026-10-10 17:19:19,493 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995787  0.997839  0.997355  0.998424  0.995978
real potato   0.904184  0.949632  0.930284  0.969906  0.999877
fake potato   0.962948  0.981074  0.976947  0.985337  0.999972
real apple    0.792454  0.884162  0.975967  0.808226  0.999270
fake apple    0.561391  0.719044  0.992529  0.563773  0.998337
real orange   0.885681  0.939326  0.992397  0.891732  0.999848
fake orange   0.918169  0.957289  0.940502  0.974789  0.999751
real grape    0.794608  0.885501  0.941622  0.835782  0.999549
fake grape    0.897631  0.946004  0.924188  0.968981  0.999591
real lemon    0.682493  0.811238  0.763071  0.866009  0.999527
fake lemon    0.841231  0.913721  0.996423  0.843779  0.999663
real avocado  0.899434  0.947005  0.929894  0.964860  0.999900
fake avocado  0.753187  0.859171  0.999662  0.753379  0.999705
real pepper   0.811531  0.895912  0.837682  0.962957  0.999182
fake pepper   0.680064  0.809520  0.942512  0.709494  0.999204
real plant    0.867730  0.929131  0.953025  0.906502  0.998618
fake plant    0.772344  0.871501  0.806757  0.947661  0.999778
real banana   0.728317  0.842755  0.879345  0.809181  0.999322
fake banana   0.693927  0.819262  0.768242  0.877654  0.999288
real onion    0.621681  0.766664  0.641323  0.953048  0.999476
fake onion    0.888448  0.940879  0.909501  0.974607  0.999923
real unknown  0.634941  0.776666  0.667123  0.929389  0.999915
fake unknown  0.213123  0.351322  0.241158  0.647048  0.997987
total         0.773970  0.860636  0.869892  0.875762  0.999290
total(-bg)    0.763887  0.854399  0.864098  0.870186  0.999440
2026-10-10 17:19:19,977 - INFO: Epoch accounting: {'epoch': 493, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11320235, 56883, 55191, 89216, 145874, 79263, 80804, 81617, 216150, 81735, 74674, 37632, 27128, 225092, 133980, 106183, 32751, 61682, 91321, 102236, 70198, 15873, 52554], 'crops_with_class': [202, 29, 28, 27, 33, 27, 32, 20, 42, 35, 34, 11, 11, 56, 29, 16, 26, 22, 38, 42, 32, 15, 26], 'targeted_crops_by_class': [0, 3, 3, 0, 1, 5, 5, 3, 9, 6, 5, 6, 1, 7, 3, 5, 6, 4, 8, 5, 8, 4, 6], 'sampled_scene_counts': [0, 1, 1, 0, 0, 1, 0, 0, 3, 2, 0, 1, 0, 0, 2, 0, 3, 1, 1, 1, 1, 1, 0, 1, 0, 0, 2, 1, 0, 1, 1, 2, 1, 1, 2, 1, 0, 1, 2, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 1, 1, 0, 2, 0, 1, 0, 1, 0, 0, 2, 1, 1, 1, 1, 2, 0, 1, 1, 2, 0, 0, 1, 1, 1, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 5, 3, 2, 1, 0, 1, 1, 1, 3, 1, 1, 2, 0, 1, 0, 1, 4, 1, 0, 1, 1, 3, 0, 2, 0, 0, 0, 0, 2, 1, 4, 4, 1, 0, 2, 2, 2, 5, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 3, 3, 3, 1, 0, 2, 1, 1, 1, 1, 2, 3, 1, 1, 3, 3, 1, 1, 1, 0, 1, 0, 0, 4, 2, 1, 5], 'learning_rate': 3.1299428927487875e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005593751397244356, 'train_segmentation_loss': 0.2665214105739747, 'val_foreground_miou_all22': 0.7638871167439091, 'val_psnr_ref1': 39.17290634155273, 'elapsed_seconds': 325.60354495048523, 'peak_cuda_allocated_gib': 7.514194488525391}

Epoch 494/500 | Batch 10/202 | Rec 0.000574 | Seg 0.268305 | Elapsed 0.2m | ETA 4.0m
Epoch 494/500 | Batch 20/202 | Rec 0.000609 | Seg 0.261670 | Elapsed 0.4m | ETA 3.8m
Epoch 494/500 | Batch 30/202 | Rec 0.000565 | Seg 0.261948 | Elapsed 0.6m | ETA 3.5m
Epoch 494/500 | Batch 40/202 | Rec 0.000580 | Seg 0.284321 | Elapsed 0.8m | ETA 3.3m
Epoch 494/500 | Batch 50/202 | Rec 0.000578 | Seg 0.288421 | Elapsed 1.0m | ETA 3.1m
Epoch 494/500 | Batch 60/202 | Rec 0.000582 | Seg 0.295325 | Elapsed 1.2m | ETA 2.9m
Epoch 494/500 | Batch 70/202 | Rec 0.000576 | Seg 0.291317 | Elapsed 1.4m | ETA 2.7m
Epoch 494/500 | Batch 80/202 | Rec 0.000572 | Seg 0.296178 | Elapsed 1.6m | ETA 2.5m
Epoch 494/500 | Batch 90/202 | Rec 0.000582 | Seg 0.300469 | Elapsed 1.8m | ETA 2.3m
Epoch 494/500 | Batch 100/202 | Rec 0.000570 | Seg 0.297560 | Elapsed 2.0m | ETA 2.1m
Epoch 494/500 | Batch 110/202 | Rec 0.000567 | Seg 0.300124 | Elapsed 2.2m | ETA 1.9m
Epoch 494/500 | Batch 120/202 | Rec 0.000567 | Seg 0.297410 | Elapsed 2.5m | ETA 1.7m
Epoch 494/500 | Batch 130/202 | Rec 0.000561 | Seg 0.292657 | Elapsed 2.7m | ETA 1.5m
Epoch 494/500 | Batch 140/202 | Rec 0.000565 | Seg 0.291671 | Elapsed 2.9m | ETA 1.3m
Epoch 494/500 | Batch 150/202 | Rec 0.000572 | Seg 0.292915 | Elapsed 3.1m | ETA 1.1m
Epoch 494/500 | Batch 160/202 | Rec 0.000585 | Seg 0.299825 | Elapsed 3.3m | ETA 0.9m
Epoch 494/500 | Batch 170/202 | Rec 0.000580 | Seg 0.296494 | Elapsed 3.5m | ETA 0.7m
Epoch 494/500 | Batch 180/202 | Rec 0.000579 | Seg 0.294924 | Elapsed 3.7m | ETA 0.5m
Epoch 494/500 | Batch 190/202 | Rec 0.000570 | Seg 0.289158 | Elapsed 3.9m | ETA 0.2m
Epoch 494/500 | Batch 200/202 | Rec 0.000571 | Seg 0.289668 | Elapsed 4.1m | ETA 0.0m
Epoch 494/500 | Batch 202/202 | Rec 0.000572 | Seg 0.289854 | Elapsed 4.2m | ETA 0.0m

2026-10-10 17:23:29,696 - INFO: Rec loss: 0.0005722470137193836
2026-10-10 17:23:29,696 - INFO: Seg loss: 0.28985351888407573
2026-10-10 17:23:29,696 - INFO: λ_rec: 1
2026-10-10 17:23:29,696 - INFO: λ_seg: 0.0001
2026-10-10 17:24:47,095 - INFO: -------------------Epoch: 494------------------------
2026-10-10 17:24:47,098 - INFO:
Validation stats:
        PSNR      SSIM      MSE
0  39.046199  0.974986  0.00013
2026-10-10 17:24:47,105 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995665  0.997778  0.996958  0.998699  0.995860
real potato   0.774585  0.872927  0.990452  0.780413  0.999728
fake potato   0.729214  0.843356  0.973417  0.744030  0.999799
real apple    0.759729  0.863412  0.912566  0.819372  0.999106
fake apple    0.606983  0.755384  0.972447  0.617604  0.998490
real orange   0.889967  0.941730  0.996767  0.892543  0.999855
fake orange   0.924584  0.960764  0.948344  0.973617  0.999773
real grape    0.768087  0.868784  0.966520  0.789081  0.999503
fake grape    0.898254  0.946350  0.927799  0.965763  0.999595
real lemon    0.573795  0.729138  0.621839  0.881330  0.999231
fake lemon    0.843978  0.915338  0.977554  0.860656  0.999663
real avocado  0.937470  0.967676  0.978031  0.957635  0.999941
fake avocado  0.710570  0.830750  0.999821  0.710661  0.999654
real pepper   0.901627  0.948219  0.930672  0.966544  0.999614
fake pepper   0.840887  0.913517  0.945544  0.883682  0.999601
real plant    0.862823  0.926311  0.952344  0.901757  0.998566
fake plant    0.781082  0.877037  0.863324  0.891296  0.999801
real banana   0.586947  0.739670  0.896452  0.629635  0.999004
fake banana   0.680204  0.809618  0.770510  0.853019  0.999262
real onion    0.663950  0.797992  0.703479  0.921973  0.999578
fake onion    0.921322  0.959000  0.981763  0.937364  0.999949
real unknown  0.739800  0.850393  0.792904  0.916985  0.999948
fake unknown  0.205037  0.340262  0.228148  0.669323  0.997813
total         0.765068  0.854583  0.883811  0.850564  0.999275
total(-bg)    0.754586  0.848074  0.878668  0.843831  0.999431
2026-10-10 17:24:47,564 - INFO: Epoch accounting: {'epoch': 494, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11163486, 62676, 57738, 134941, 179797, 97286, 102234, 110440, 188574, 105014, 67128, 46681, 32843, 229030, 141027, 164172, 16689, 86837, 76090, 59986, 53154, 11055, 51394], 'crops_with_class': [202, 33, 29, 39, 42, 30, 36, 23, 38, 41, 31, 16, 14, 53, 37, 21, 16, 24, 28, 27, 25, 14, 23], 'targeted_crops_by_class': [0, 3, 4, 6, 8, 3, 7, 4, 3, 5, 3, 3, 4, 7, 5, 4, 3, 6, 4, 1, 2, 6, 7], 'sampled_scene_counts': [0, 0, 3, 0, 0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 3, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 2, 0, 1, 0, 2, 0, 1, 1, 0, 0, 0, 1, 1, 2, 0, 1, 1, 2, 0, 1, 2, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 1, 0, 2, 1, 1, 1, 0, 0, 1, 2, 4, 2, 4, 0, 2, 1, 2, 5, 1, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 4, 3, 3, 1, 1, 0, 1, 1, 1, 3, 1, 1, 1, 0, 2, 3, 2, 4, 1, 0, 2, 1, 1, 0, 1, 2, 3, 0, 3, 1, 0, 2, 0, 1, 2, 1, 1, 1, 4, 2, 0, 2, 2, 3, 1, 1, 2, 1, 0, 1, 1, 0, 2, 0, 2, 1, 3], 'learning_rate': 2.982323829285302e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005722470137193836, 'train_segmentation_loss': 0.28985351888407573, 'val_foreground_miou_all22': 0.7545860680933978, 'val_psnr_ref1': 39.046199035644534, 'elapsed_seconds': 327.57939314842224, 'peak_cuda_allocated_gib': 7.513217926025391}

Epoch 495/500 | Batch 10/202 | Rec 0.000715 | Seg 0.354841 | Elapsed 0.2m | ETA 4.0m
Epoch 495/500 | Batch 20/202 | Rec 0.000725 | Seg 0.384113 | Elapsed 0.4m | ETA 3.7m
Epoch 495/500 | Batch 30/202 | Rec 0.000646 | Seg 0.323155 | Elapsed 0.6m | ETA 3.5m
Epoch 495/500 | Batch 40/202 | Rec 0.000635 | Seg 0.316238 | Elapsed 0.8m | ETA 3.3m
Epoch 495/500 | Batch 50/202 | Rec 0.000650 | Seg 0.312764 | Elapsed 1.0m | ETA 3.1m
Epoch 495/500 | Batch 60/202 | Rec 0.000667 | Seg 0.317824 | Elapsed 1.2m | ETA 2.9m
Epoch 495/500 | Batch 70/202 | Rec 0.000642 | Seg 0.305830 | Elapsed 1.4m | ETA 2.7m
Epoch 495/500 | Batch 80/202 | Rec 0.000640 | Seg 0.307001 | Elapsed 1.6m | ETA 2.5m
Epoch 495/500 | Batch 90/202 | Rec 0.000629 | Seg 0.307727 | Elapsed 1.8m | ETA 2.3m
Epoch 495/500 | Batch 100/202 | Rec 0.000626 | Seg 0.304933 | Elapsed 2.0m | ETA 2.1m
Epoch 495/500 | Batch 110/202 | Rec 0.000631 | Seg 0.304629 | Elapsed 2.2m | ETA 1.9m
Epoch 495/500 | Batch 120/202 | Rec 0.000619 | Seg 0.302254 | Elapsed 2.4m | ETA 1.7m
Epoch 495/500 | Batch 130/202 | Rec 0.000616 | Seg 0.298838 | Elapsed 2.6m | ETA 1.5m
Epoch 495/500 | Batch 140/202 | Rec 0.000621 | Seg 0.299267 | Elapsed 2.8m | ETA 1.3m
Epoch 495/500 | Batch 150/202 | Rec 0.000615 | Seg 0.298851 | Elapsed 3.0m | ETA 1.1m
Epoch 495/500 | Batch 160/202 | Rec 0.000613 | Seg 0.296263 | Elapsed 3.2m | ETA 0.9m
Epoch 495/500 | Batch 170/202 | Rec 0.000614 | Seg 0.293937 | Elapsed 3.5m | ETA 0.6m
Epoch 495/500 | Batch 180/202 | Rec 0.000617 | Seg 0.295466 | Elapsed 3.7m | ETA 0.4m
Epoch 495/500 | Batch 190/202 | Rec 0.000621 | Seg 0.294831 | Elapsed 3.9m | ETA 0.2m
Epoch 495/500 | Batch 200/202 | Rec 0.000615 | Seg 0.290269 | Elapsed 4.1m | ETA 0.0m
Epoch 495/500 | Batch 202/202 | Rec 0.000612 | Seg 0.288526 | Elapsed 4.1m | ETA 0.0m

2026-10-10 17:28:53,832 - INFO: Rec loss: 0.0006118442847809552
2026-10-10 17:28:53,832 - INFO: Seg loss: 0.28852582433362406
2026-10-10 17:28:53,833 - INFO: λ_rec: 1
2026-10-10 17:28:53,833 - INFO: λ_seg: 0.0001
2026-10-10 17:30:09,557 - INFO: -------------------Epoch: 495------------------------
2026-10-10 17:30:09,561 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.117245  0.975077  0.000128
2026-10-10 17:30:09,567 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995737  0.997814  0.997496  0.998232  0.995931
real potato   0.462497  0.632432  0.972479  0.468630  0.999348
fake potato   0.711065  0.831088  0.995324  0.713448  0.999789
real apple    0.699077  0.822840  0.799708  0.847457  0.998741
fake apple    0.587060  0.739761  0.984358  0.592588  0.998426
real orange   0.956547  0.977741  0.995203  0.960977  0.999942
fake orange   0.961173  0.980152  0.973554  0.986942  0.999886
real grape    0.789910  0.882576  0.918927  0.849083  0.999529
fake grape    0.903232  0.949106  0.922355  0.977561  0.999613
real lemon    0.574701  0.729870  0.593432  0.947936  0.999176
fake lemon    0.863072  0.926454  0.994868  0.866931  0.999709
real avocado  0.894194  0.944092  0.920855  0.968637  0.999893
fake avocado  0.547297  0.707378  0.999534  0.547437  0.999458
real pepper   0.812500  0.896502  0.844430  0.955531  0.999193
fake pepper   0.681116  0.810265  0.956124  0.703092  0.999215
real plant    0.872955  0.932119  0.947427  0.917394  0.998665
fake plant    0.757808  0.862169  0.803344  0.930406  0.999763
real banana   0.531935  0.694413  0.853550  0.585359  0.998843
fake banana   0.721764  0.838351  0.814745  0.863470  0.999388
real onion    0.634531  0.776358  0.680529  0.903732  0.999530
fake onion    0.901107  0.947931  0.994424  0.905683  0.999937
real unknown  0.801626  0.889842  0.844178  0.940840  0.999963
fake unknown  0.212139  0.349990  0.225028  0.787396  0.997536
total         0.733611  0.831272  0.870951  0.835598  0.999195
total(-bg)    0.721696  0.823701  0.865199  0.828206  0.999343
2026-10-10 17:30:10,030 - INFO: Epoch accounting: {'epoch': 495, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11211514, 41965, 61144, 145264, 148938, 75745, 78306, 115876, 193084, 70720, 76178, 29974, 53218, 201987, 130104, 225227, 36069, 94616, 75954, 71053, 46575, 7725, 47036], 'crops_with_class': [202, 29, 26, 37, 33, 25, 25, 24, 34, 33, 32, 12, 18, 54, 36, 26, 31, 27, 30, 36, 23, 9, 20], 'targeted_crops_by_class': [0, 6, 5, 6, 11, 3, 6, 6, 3, 5, 5, 3, 7, 1, 4, 5, 15, 2, 7, 6, 5, 6, 2], 'sampled_scene_counts': [3, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 3, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 2, 1, 1, 0, 0, 3, 2, 3, 1, 2, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 2, 1, 2, 1, 0, 0, 0, 0, 1, 0, 1, 1, 2, 1, 1, 2, 0, 2, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 2, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 2, 0, 0, 3, 1, 0, 1, 4, 1, 1, 2, 2, 2, 2, 1, 1, 4, 2, 1, 1, 1, 2, 0, 1, 0, 2, 3, 2, 1, 0, 1, 2, 3, 1, 1, 3, 1, 0, 0, 0, 2, 2, 4, 2, 0, 4, 0, 2, 3, 1, 0, 2, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 3, 1, 2, 1, 2, 2, 2, 2, 2, 3, 2, 0, 0, 1, 3, 1, 1, 3, 3, 1], 'learning_rate': 2.854375520506134e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006118442847809552, 'train_segmentation_loss': 0.28852582433362406, 'val_foreground_miou_all22': 0.7216956797942616, 'val_psnr_ref1': 39.11724517822265, 'elapsed_seconds': 322.4590883255005, 'peak_cuda_allocated_gib': 7.508090972900391}

Epoch 496/500 | Batch 10/202 | Rec 0.000548 | Seg 0.250968 | Elapsed 0.2m | ETA 4.0m
Epoch 496/500 | Batch 20/202 | Rec 0.000550 | Seg 0.270270 | Elapsed 0.4m | ETA 3.7m
Epoch 496/500 | Batch 30/202 | Rec 0.000550 | Seg 0.270007 | Elapsed 0.6m | ETA 3.5m
Epoch 496/500 | Batch 40/202 | Rec 0.000568 | Seg 0.282142 | Elapsed 0.8m | ETA 3.3m
Epoch 496/500 | Batch 50/202 | Rec 0.000595 | Seg 0.273121 | Elapsed 1.0m | ETA 3.1m
Epoch 496/500 | Batch 60/202 | Rec 0.000601 | Seg 0.284576 | Elapsed 1.2m | ETA 2.9m
Epoch 496/500 | Batch 70/202 | Rec 0.000589 | Seg 0.285066 | Elapsed 1.4m | ETA 2.7m
Epoch 496/500 | Batch 80/202 | Rec 0.000588 | Seg 0.288895 | Elapsed 1.6m | ETA 2.5m
Epoch 496/500 | Batch 90/202 | Rec 0.000590 | Seg 0.288597 | Elapsed 1.8m | ETA 2.3m
Epoch 496/500 | Batch 100/202 | Rec 0.000595 | Seg 0.293059 | Elapsed 2.0m | ETA 2.1m
Epoch 496/500 | Batch 110/202 | Rec 0.000585 | Seg 0.290018 | Elapsed 2.3m | ETA 1.9m
Epoch 496/500 | Batch 120/202 | Rec 0.000575 | Seg 0.285793 | Elapsed 2.5m | ETA 1.7m
Epoch 496/500 | Batch 130/202 | Rec 0.000569 | Seg 0.280837 | Elapsed 2.7m | ETA 1.5m
Epoch 496/500 | Batch 140/202 | Rec 0.000563 | Seg 0.276483 | Elapsed 2.9m | ETA 1.3m
Epoch 496/500 | Batch 150/202 | Rec 0.000567 | Seg 0.279183 | Elapsed 3.1m | ETA 1.1m
Epoch 496/500 | Batch 160/202 | Rec 0.000567 | Seg 0.280295 | Elapsed 3.3m | ETA 0.9m
Epoch 496/500 | Batch 170/202 | Rec 0.000580 | Seg 0.279599 | Elapsed 3.5m | ETA 0.7m
Epoch 496/500 | Batch 180/202 | Rec 0.000586 | Seg 0.277596 | Elapsed 3.7m | ETA 0.5m
Epoch 496/500 | Batch 190/202 | Rec 0.000584 | Seg 0.277589 | Elapsed 3.9m | ETA 0.2m
Epoch 496/500 | Batch 200/202 | Rec 0.000580 | Seg 0.274861 | Elapsed 4.1m | ETA 0.0m
Epoch 496/500 | Batch 202/202 | Rec 0.000578 | Seg 0.274634 | Elapsed 4.2m | ETA 0.0m

2026-10-10 17:34:19,814 - INFO: Rec loss: 0.0005783817996956767
2026-10-10 17:34:19,814 - INFO: Seg loss: 0.27463380387513947
2026-10-10 17:34:19,814 - INFO: λ_rec: 1
2026-10-10 17:34:19,814 - INFO: λ_seg: 0.0001
2026-10-10 17:35:32,485 - INFO: -------------------Epoch: 496------------------------
2026-10-10 17:35:32,488 - INFO:
Validation stats:
       PSNR      SSIM       MSE
0  39.01597  0.974886  0.000131
2026-10-10 17:35:32,495 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995502  0.997696  0.996882  0.998612  0.995705
real potato   0.904296  0.949693  0.933711  0.966335  0.999878
fake potato   0.962834  0.981015  0.979937  0.982195  0.999972
real apple    0.751824  0.858284  0.992110  0.756347  0.999139
fake apple    0.582269  0.735946  0.989758  0.585799  0.998413
real orange   0.907602  0.951513  0.995823  0.911070  0.999878
fake orange   0.925368  0.961187  0.953773  0.968820  0.999776
real grape    0.735588  0.847603  0.936759  0.774026  0.999419
fake grape    0.905902  0.950578  0.938570  0.963000  0.999630
real lemon    0.764529  0.866503  0.842887  0.891587  0.999677
fake lemon    0.771564  0.871005  0.998880  0.772232  0.999516
real avocado  0.953648  0.976224  0.993707  0.959442  0.999957
fake avocado  0.634324  0.776205  0.999799  0.634404  0.999562
real pepper   0.814751  0.897871  0.836490  0.969089  0.999194
fake pepper   0.688699  0.815607  0.937703  0.721721  0.999222
real plant    0.853869  0.921125  0.946794  0.896906  0.998465
fake plant    0.816904  0.899176  0.907299  0.891296  0.999841
real banana   0.763577  0.865891  0.893293  0.840215  0.999415
fake banana   0.660866  0.795759  0.740606  0.859904  0.999188
real onion    0.626346  0.770201  0.641860  0.962844  0.999481
fake onion    0.934608  0.966149  0.975123  0.957436  0.999958
real unknown  0.541808  0.702774  0.570494  0.915076  0.999876
fake unknown  0.200999  0.334682  0.223039  0.670409  0.997755
total         0.769464  0.856204  0.879361  0.862990  0.999257
total(-bg)    0.759190  0.849772  0.874019  0.856825  0.999419
2026-10-10 17:35:32,956 - INFO: Epoch accounting: {'epoch': 496, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11245886, 46565, 72530, 122988, 160769, 98327, 73006, 166708, 225868, 72978, 77992, 53498, 35625, 221565, 108417, 118981, 20600, 56681, 66385, 80967, 69383, 5396, 37157], 'crops_with_class': [202, 30, 33, 32, 39, 27, 26, 29, 40, 32, 31, 19, 13, 55, 32, 16, 18, 22, 27, 38, 30, 6, 17], 'targeted_crops_by_class': [0, 4, 4, 4, 5, 6, 4, 3, 4, 8, 8, 4, 4, 5, 2, 4, 6, 1, 6, 7, 2, 2, 3], 'sampled_scene_counts': [0, 1, 2, 1, 0, 0, 2, 2, 0, 3, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 2, 0, 2, 1, 0, 0, 0, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 2, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 4, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 2, 1, 0, 0, 2, 2, 1, 2, 1, 4, 3, 1, 2, 2, 4, 1, 1, 0, 3, 2, 3, 0, 0, 0, 3, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 2, 0, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 1, 1, 2, 0, 2, 2, 1, 1, 1, 5, 0, 2, 2, 1, 1, 1, 1, 3, 1, 2, 1, 1, 2, 0, 1, 0, 4, 1, 1, 1, 3, 2], 'learning_rate': 2.746103017591364e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005783817996956767, 'train_segmentation_loss': 0.27463380387513947, 'val_foreground_miou_all22': 0.7591897203929385, 'val_psnr_ref1': 39.01597045898438, 'elapsed_seconds': 322.9180796146393, 'peak_cuda_allocated_gib': 7.509342193603516}

Epoch 497/500 | Batch 10/202 | Rec 0.000470 | Seg 0.206461 | Elapsed 0.2m | ETA 4.1m
Epoch 497/500 | Batch 20/202 | Rec 0.000548 | Seg 0.233184 | Elapsed 0.4m | ETA 3.9m
Epoch 497/500 | Batch 30/202 | Rec 0.000566 | Seg 0.247169 | Elapsed 0.6m | ETA 3.6m
Epoch 497/500 | Batch 40/202 | Rec 0.000586 | Seg 0.269264 | Elapsed 0.8m | ETA 3.4m
Epoch 497/500 | Batch 50/202 | Rec 0.000586 | Seg 0.287037 | Elapsed 1.1m | ETA 3.2m
Epoch 497/500 | Batch 60/202 | Rec 0.000559 | Seg 0.274121 | Elapsed 1.3m | ETA 3.0m
Epoch 497/500 | Batch 70/202 | Rec 0.000546 | Seg 0.266642 | Elapsed 1.5m | ETA 2.8m
Epoch 497/500 | Batch 80/202 | Rec 0.000551 | Seg 0.268548 | Elapsed 1.7m | ETA 2.5m
Epoch 497/500 | Batch 90/202 | Rec 0.000545 | Seg 0.267160 | Elapsed 1.9m | ETA 2.3m
Epoch 497/500 | Batch 100/202 | Rec 0.000549 | Seg 0.265389 | Elapsed 2.1m | ETA 2.1m
Epoch 497/500 | Batch 110/202 | Rec 0.000545 | Seg 0.264274 | Elapsed 2.3m | ETA 1.9m
Epoch 497/500 | Batch 120/202 | Rec 0.000547 | Seg 0.263460 | Elapsed 2.5m | ETA 1.7m
Epoch 497/500 | Batch 130/202 | Rec 0.000548 | Seg 0.264420 | Elapsed 2.7m | ETA 1.5m
Epoch 497/500 | Batch 140/202 | Rec 0.000547 | Seg 0.269621 | Elapsed 2.9m | ETA 1.3m
Epoch 497/500 | Batch 150/202 | Rec 0.000544 | Seg 0.267975 | Elapsed 3.1m | ETA 1.1m
Epoch 497/500 | Batch 160/202 | Rec 0.000547 | Seg 0.267165 | Elapsed 3.3m | ETA 0.9m
Epoch 497/500 | Batch 170/202 | Rec 0.000549 | Seg 0.266979 | Elapsed 3.5m | ETA 0.7m
Epoch 497/500 | Batch 180/202 | Rec 0.000548 | Seg 0.265834 | Elapsed 3.7m | ETA 0.5m
Epoch 497/500 | Batch 190/202 | Rec 0.000550 | Seg 0.267248 | Elapsed 4.0m | ETA 0.2m
Epoch 497/500 | Batch 200/202 | Rec 0.000545 | Seg 0.265092 | Elapsed 4.2m | ETA 0.0m
Epoch 497/500 | Batch 202/202 | Rec 0.000546 | Seg 0.264098 | Elapsed 4.2m | ETA 0.0m

2026-10-10 17:39:44,855 - INFO: Rec loss: 0.0005460026008906857
2026-10-10 17:39:44,855 - INFO: Seg loss: 0.26409813798595183
2026-10-10 17:39:44,855 - INFO: λ_rec: 1
2026-10-10 17:39:44,855 - INFO: λ_seg: 0.0001
2026-10-10 17:41:07,097 - INFO: -------------------Epoch: 497------------------------
2026-10-10 17:41:07,101 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.110744  0.975113  0.000128
2026-10-10 17:41:07,108 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995716  0.997803  0.997335  0.998372  0.995911
real potato   0.609114  0.757032  0.966713  0.622163  0.999522
fake potato   0.701579  0.824573  0.988869  0.707164  0.999781
real apple    0.742713  0.852314  0.850469  0.854268  0.998979
fake apple    0.601814  0.751368  0.988530  0.606046  0.998486
real orange   0.929903  0.963629  0.993605  0.935503  0.999907
fake orange   0.942926  0.970575  0.961364  0.980066  0.999830
real grape    0.793016  0.884511  0.930323  0.843090  0.999541
fake grape    0.901283  0.948029  0.923601  0.973889  0.999605
real lemon    0.632104  0.774540  0.655834  0.945858  0.999353
fake lemon    0.845893  0.916464  0.998724  0.846809  0.999674
real avocado  0.885204  0.939057  0.911324  0.968637  0.999883
fake avocado  0.654895  0.791417  0.999611  0.655062  0.999587
real pepper   0.806657  0.892933  0.839763  0.953404  0.999164
fake pepper   0.675583  0.806337  0.956839  0.696818  0.999202
real plant    0.868771  0.929728  0.950939  0.909537  0.998626
fake plant    0.786468  0.880423  0.825970  0.942676  0.999796
real banana   0.613463  0.760381  0.867258  0.677034  0.999041
fake banana   0.734331  0.846768  0.827671  0.866871  0.999423
real onion    0.647560  0.786034  0.690714  0.912008  0.999552
fake onion    0.938829  0.968400  0.987434  0.950181  0.999961
real unknown  0.818029  0.899857  0.874775  0.926527  0.999967
fake unknown  0.217453  0.357190  0.234138  0.753169  0.997716
total         0.754057  0.847798  0.879209  0.848920  0.999239
total(-bg)    0.743072  0.840980  0.873839  0.842126  0.999391
2026-10-10 17:41:07,583 - INFO: Epoch accounting: {'epoch': 497, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11354242, 41612, 70384, 137044, 139287, 87142, 70774, 169055, 168939, 61698, 37117, 34632, 24891, 220511, 105799, 156935, 29428, 69858, 72983, 87489, 55048, 7987, 35417], 'crops_with_class': [202, 26, 27, 34, 36, 27, 22, 33, 32, 25, 21, 12, 10, 52, 23, 20, 26, 21, 30, 36, 28, 10, 17], 'targeted_crops_by_class': [0, 1, 5, 3, 6, 5, 3, 5, 4, 2, 2, 5, 1, 4, 2, 3, 3, 4, 12, 2, 4, 4, 4], 'sampled_scene_counts': [0, 2, 0, 0, 1, 2, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 1, 2, 1, 2, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 2, 0, 1, 1, 2, 0, 2, 1, 1, 0, 1, 0, 1, 3, 2, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 2, 2, 1, 0, 1, 1, 0, 2, 1, 0, 1, 0, 0, 2, 1, 1, 0, 0, 0, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1, 0, 0, 3, 3, 1, 1, 0, 1, 2, 1, 2, 3, 2, 0, 0, 0, 2, 1, 0, 1, 1, 0, 2, 1, 1, 0, 0, 1, 2, 1, 2, 2, 0, 2, 2, 1, 1, 1, 1, 3, 1, 0, 1, 2, 4, 1, 1, 2, 1, 1, 1, 2, 2, 1, 0, 1, 1, 3, 1, 1, 0, 1, 3, 1, 1, 2, 1, 0, 0, 1, 3, 1, 3, 0, 1, 2, 2, 3, 2, 1, 1, 1, 0, 2, 5, 1, 1, 1, 0, 1], 'learning_rate': 2.6575105949541547e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005460026008906857, 'train_segmentation_loss': 0.26409813798595183, 'val_foreground_miou_all22': 0.743072178306426, 'val_psnr_ref1': 39.11074371337891, 'elapsed_seconds': 334.61994433403015, 'peak_cuda_allocated_gib': 7.511264801025391}

Epoch 498/500 | Batch 10/202 | Rec 0.000742 | Seg 0.233198 | Elapsed 0.2m | ETA 4.0m
Epoch 498/500 | Batch 20/202 | Rec 0.000610 | Seg 0.250735 | Elapsed 0.4m | ETA 3.8m
Epoch 498/500 | Batch 30/202 | Rec 0.000558 | Seg 0.247315 | Elapsed 0.6m | ETA 3.6m
Epoch 498/500 | Batch 40/202 | Rec 0.000570 | Seg 0.253602 | Elapsed 0.8m | ETA 3.4m
Epoch 498/500 | Batch 50/202 | Rec 0.000584 | Seg 0.260829 | Elapsed 1.0m | ETA 3.2m
Epoch 498/500 | Batch 60/202 | Rec 0.000573 | Seg 0.254164 | Elapsed 1.2m | ETA 3.0m
Epoch 498/500 | Batch 70/202 | Rec 0.000590 | Seg 0.258773 | Elapsed 1.5m | ETA 2.7m
Epoch 498/500 | Batch 80/202 | Rec 0.000608 | Seg 0.262455 | Elapsed 1.7m | ETA 2.5m
Epoch 498/500 | Batch 90/202 | Rec 0.000606 | Seg 0.262933 | Elapsed 1.9m | ETA 2.3m
Epoch 498/500 | Batch 100/202 | Rec 0.000609 | Seg 0.267027 | Elapsed 2.1m | ETA 2.1m
Epoch 498/500 | Batch 110/202 | Rec 0.000599 | Seg 0.264264 | Elapsed 2.3m | ETA 1.9m
Epoch 498/500 | Batch 120/202 | Rec 0.000596 | Seg 0.264748 | Elapsed 2.5m | ETA 1.7m
Epoch 498/500 | Batch 130/202 | Rec 0.000586 | Seg 0.263936 | Elapsed 2.7m | ETA 1.5m
Epoch 498/500 | Batch 140/202 | Rec 0.000586 | Seg 0.266569 | Elapsed 2.9m | ETA 1.3m
Epoch 498/500 | Batch 150/202 | Rec 0.000585 | Seg 0.266509 | Elapsed 3.1m | ETA 1.1m
Epoch 498/500 | Batch 160/202 | Rec 0.000581 | Seg 0.266622 | Elapsed 3.3m | ETA 0.9m
Epoch 498/500 | Batch 170/202 | Rec 0.000582 | Seg 0.265976 | Elapsed 3.5m | ETA 0.7m
Epoch 498/500 | Batch 180/202 | Rec 0.000593 | Seg 0.272658 | Elapsed 3.7m | ETA 0.5m
Epoch 498/500 | Batch 190/202 | Rec 0.000593 | Seg 0.271301 | Elapsed 3.9m | ETA 0.2m
Epoch 498/500 | Batch 200/202 | Rec 0.000591 | Seg 0.272275 | Elapsed 4.1m | ETA 0.0m
Epoch 498/500 | Batch 202/202 | Rec 0.000588 | Seg 0.271280 | Elapsed 4.2m | ETA 0.0m

2026-10-10 17:45:17,970 - INFO: Rec loss: 0.0005876208933031112
2026-10-10 17:45:17,971 - INFO: Seg loss: 0.2712801021182596
2026-10-10 17:45:17,971 - INFO: λ_rec: 1
2026-10-10 17:45:17,971 - INFO: λ_seg: 0.0001
2026-10-10 17:46:39,668 - INFO: -------------------Epoch: 498------------------------
2026-10-10 17:46:39,672 - INFO:
Validation stats:
        PSNR     SSIM       MSE
0  39.131911  0.97508  0.000128
2026-10-10 17:46:39,679 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995623  0.997757  0.996948  0.998667  0.995821
real potato   0.357507  0.526672  0.998576  0.357689  0.999231
fake potato   0.654006  0.790766  0.986228  0.660034  0.999746
real apple    0.694254  0.819490  0.772544  0.872623  0.998674
fake apple    0.654234  0.790933  0.977576  0.664201  0.998675
real orange   0.913857  0.954940  0.996977  0.916396  0.999886
fake orange   0.934189  0.965925  0.958349  0.973723  0.999804
real grape    0.815696  0.898444  0.944418  0.856830  0.999596
fake grape    0.894490  0.944257  0.922091  0.967620  0.999578
real lemon    0.558676  0.716813  0.578348  0.942612  0.999125
fake lemon    0.859917  0.924634  0.988428  0.868662  0.999701
real avocado  0.839008  0.912408  0.863743  0.966995  0.999828
fake avocado  0.782099  0.877678  0.999837  0.782198  0.999739
real pepper   0.787163  0.880858  0.826988  0.942349  0.999068
fake pepper   0.618898  0.764544  0.939787  0.644453  0.999054
real plant    0.866256  0.928286  0.959829  0.898844  0.998612
fake plant    0.789538  0.882343  0.897167  0.868098  0.999816
real banana   0.523079  0.686823  0.893335  0.557925  0.998857
fake banana   0.733167  0.845993  0.838699  0.853517  0.999429
real onion    0.629892  0.772875  0.739097  0.809998  0.999570
fake onion    0.894990  0.944536  0.995446  0.898670  0.999933
real unknown  0.901382  0.948084  0.963547  0.933206  0.999984
fake unknown  0.224456  0.366583  0.247633  0.705723  0.997945
total         0.735756  0.832245  0.881982  0.823523  0.999203
total(-bg)    0.723943  0.824722  0.876756  0.815562  0.999357
2026-10-10 17:46:40,153 - INFO: Epoch accounting: {'epoch': 498, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11309263, 36568, 60922, 140862, 158325, 77929, 80218, 178272, 211988, 66985, 49852, 39590, 27854, 198028, 82336, 178584, 27558, 60610, 57611, 84751, 54684, 11221, 44261], 'crops_with_class': [202, 24, 27, 38, 40, 25, 25, 34, 38, 34, 21, 13, 10, 54, 26, 19, 24, 20, 26, 34, 23, 11, 21], 'targeted_crops_by_class': [0, 5, 3, 5, 3, 5, 4, 7, 4, 2, 7, 6, 2, 3, 2, 5, 4, 4, 4, 6, 6, 5, 3], 'sampled_scene_counts': [1, 1, 5, 1, 1, 1, 1, 1, 0, 1, 1, 2, 1, 2, 2, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 0, 1, 0, 1, 1, 0, 2, 1, 1, 1, 0, 0, 2, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 2, 2, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 2, 4, 1, 3, 3, 1, 0, 1, 2, 0, 1, 1, 1, 0, 1, 0, 3, 0, 0, 0, 2, 1, 2, 1, 2, 1, 2, 0, 1, 3, 2, 4, 0, 1, 2, 2, 2, 1, 2, 3, 2, 2, 0, 2, 0, 1, 3, 2, 2, 3, 1, 0, 1, 1, 0, 3, 1, 0, 1, 3, 2, 1, 1, 0, 0, 1, 1, 1, 0, 0, 3, 2, 0, 1, 1, 0, 3, 1, 1, 2, 2, 1], 'learning_rate': 2.5886017500715285e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005876208933031112, 'train_segmentation_loss': 0.2712801021182596, 'val_foreground_miou_all22': 0.7239433846607616, 'val_psnr_ref1': 39.131910705566405, 'elapsed_seconds': 332.56231474876404, 'peak_cuda_allocated_gib': 7.508335113525391}

Epoch 499/500 | Batch 10/202 | Rec 0.000607 | Seg 0.277984 | Elapsed 0.2m | ETA 3.9m
Epoch 499/500 | Batch 20/202 | Rec 0.000525 | Seg 0.270755 | Elapsed 0.4m | ETA 3.7m
Epoch 499/500 | Batch 30/202 | Rec 0.000557 | Seg 0.290009 | Elapsed 0.6m | ETA 3.5m
Epoch 499/500 | Batch 40/202 | Rec 0.000559 | Seg 0.293945 | Elapsed 0.8m | ETA 3.3m
Epoch 499/500 | Batch 50/202 | Rec 0.000556 | Seg 0.289071 | Elapsed 1.0m | ETA 3.1m
Epoch 499/500 | Batch 60/202 | Rec 0.000555 | Seg 0.289979 | Elapsed 1.2m | ETA 2.9m
Epoch 499/500 | Batch 70/202 | Rec 0.000544 | Seg 0.287876 | Elapsed 1.4m | ETA 2.7m
Epoch 499/500 | Batch 80/202 | Rec 0.000549 | Seg 0.289806 | Elapsed 1.6m | ETA 2.5m
Epoch 499/500 | Batch 90/202 | Rec 0.000544 | Seg 0.291796 | Elapsed 1.8m | ETA 2.3m
Epoch 499/500 | Batch 100/202 | Rec 0.000556 | Seg 0.298392 | Elapsed 2.0m | ETA 2.1m
Epoch 499/500 | Batch 110/202 | Rec 0.000550 | Seg 0.297374 | Elapsed 2.3m | ETA 1.9m
Epoch 499/500 | Batch 120/202 | Rec 0.000556 | Seg 0.303903 | Elapsed 2.5m | ETA 1.7m
Epoch 499/500 | Batch 130/202 | Rec 0.000551 | Seg 0.297928 | Elapsed 2.7m | ETA 1.5m
Epoch 499/500 | Batch 140/202 | Rec 0.000543 | Seg 0.294100 | Elapsed 2.9m | ETA 1.3m
Epoch 499/500 | Batch 150/202 | Rec 0.000545 | Seg 0.293287 | Elapsed 3.1m | ETA 1.1m
Epoch 499/500 | Batch 160/202 | Rec 0.000558 | Seg 0.297561 | Elapsed 3.3m | ETA 0.9m
Epoch 499/500 | Batch 170/202 | Rec 0.000559 | Seg 0.292800 | Elapsed 3.5m | ETA 0.7m
Epoch 499/500 | Batch 180/202 | Rec 0.000558 | Seg 0.291202 | Elapsed 3.7m | ETA 0.5m
Epoch 499/500 | Batch 190/202 | Rec 0.000555 | Seg 0.290339 | Elapsed 3.9m | ETA 0.2m
Epoch 499/500 | Batch 200/202 | Rec 0.000551 | Seg 0.287216 | Elapsed 4.1m | ETA 0.0m
Epoch 499/500 | Batch 202/202 | Rec 0.000552 | Seg 0.287567 | Elapsed 4.1m | ETA 0.0m

2026-10-10 17:50:48,000 - INFO: Rec loss: 0.0005515951345995124
2026-10-10 17:50:48,000 - INFO: Seg loss: 0.2875672964987778
2026-10-10 17:50:48,001 - INFO: λ_rec: 1
2026-10-10 17:50:48,001 - INFO: λ_seg: 0.0001
2026-10-10 17:52:07,015 - INFO: -------------------Epoch: 499------------------------
2026-10-10 17:52:07,019 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  38.940543  0.974855  0.000133
2026-10-10 17:52:07,026 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995442  0.997666  0.996895  0.998538  0.995647
real potato   0.908313  0.951904  0.930896  0.973986  0.999882
fake potato   0.969177  0.984297  0.987355  0.981357  0.999977
real apple    0.687893  0.815042  0.972824  0.701371  0.998902
fake apple    0.570682  0.726622  0.990100  0.573957  0.998370
real orange   0.903915  0.949483  0.997070  0.906322  0.999873
fake orange   0.924700  0.960827  0.948163  0.973937  0.999773
real grape    0.710186  0.830487  0.859983  0.803040  0.999316
fake grape    0.890958  0.942285  0.915312  0.971002  0.999560
real lemon    0.846504  0.916822  0.915803  0.917943  0.999804
fake lemon    0.819842  0.900954  0.991768  0.825460  0.999616
real avocado  0.959843  0.979460  0.993915  0.965517  0.999962
fake avocado  0.573633  0.729009  0.999778  0.573706  0.999490
real pepper   0.823196  0.902976  0.844729  0.969965  0.999238
fake pepper   0.698737  0.822605  0.943139  0.729467  0.999250
real plant    0.855584  0.922122  0.952671  0.893565  0.998491
fake plant    0.659867  0.795034  0.809212  0.781442  0.999679
real banana   0.789373  0.882240  0.895337  0.869618  0.999479
fake banana   0.723616  0.839599  0.819272  0.861065  0.999395
real onion    0.625899  0.769864  0.638355  0.969769  0.999476
fake onion    0.924380  0.960654  0.985504  0.937122  0.999952
real unknown  0.459700  0.629811  0.474601  0.936069  0.999824
fake unknown  0.200431  0.333896  0.220288  0.689786  0.997681
total         0.761821  0.849724  0.873173  0.861044  0.999245
total(-bg)    0.751201  0.843000  0.867549  0.854794  0.999409
2026-10-10 17:52:07,498 - INFO: Epoch accounting: {'epoch': 499, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11216885, 45069, 69890, 95658, 126254, 92120, 48173, 154395, 182360, 113109, 58984, 38877, 39885, 199138, 96268, 225432, 16852, 115138, 92824, 91451, 58273, 15986, 45251], 'crops_with_class': [202, 27, 31, 26, 31, 29, 20, 27, 32, 44, 30, 13, 16, 48, 31, 23, 18, 32, 36, 42, 31, 18, 19], 'targeted_crops_by_class': [0, 2, 6, 3, 3, 4, 3, 2, 5, 8, 4, 2, 4, 3, 5, 7, 4, 7, 6, 6, 11, 11, 4], 'sampled_scene_counts': [0, 1, 0, 2, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 2, 1, 1, 1, 0, 0, 0, 2, 1, 0, 1, 0, 0, 1, 1, 2, 1, 1, 2, 0, 2, 1, 0, 1, 1, 0, 0, 0, 2, 0, 0, 2, 1, 1, 1, 2, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 2, 1, 0, 2, 0, 1, 1, 4, 0, 0, 1, 1, 0, 0, 1, 1, 2, 1, 1, 1, 0, 1, 0, 1, 1, 0, 2, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 5, 2, 1, 0, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 3, 0, 1, 1, 2, 1, 1, 0, 0, 1, 1, 2, 4, 2, 1, 0, 1, 0, 3, 0, 0, 5, 1, 2, 1, 3, 4, 2, 2, 2, 1, 0, 1, 1, 4, 1, 1, 2, 1, 2, 3, 1, 2, 2, 0, 0, 1, 1, 2, 0, 3, 2, 2, 0, 1, 0, 2, 3, 0, 1, 1, 1, 4, 0, 2, 2, 4, 3], 'learning_rate': 2.5393792033467143e-07, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005515951345995124, 'train_segmentation_loss': 0.2875672964987778, 'val_foreground_miou_all22': 0.7512013745577168, 'val_psnr_ref1': 38.940543212890624, 'elapsed_seconds': 327.3375117778778, 'peak_cuda_allocated_gib': 7.511295318603516}

Epoch 500/500 | Batch 10/202 | Rec 0.000540 | Seg 0.256770 | Elapsed 0.2m | ETA 3.9m
Epoch 500/500 | Batch 20/202 | Rec 0.000660 | Seg 0.276191 | Elapsed 0.4m | ETA 3.7m
Epoch 500/500 | Batch 30/202 | Rec 0.000612 | Seg 0.280166 | Elapsed 0.6m | ETA 3.5m
Epoch 500/500 | Batch 40/202 | Rec 0.000621 | Seg 0.279285 | Elapsed 0.8m | ETA 3.3m
Epoch 500/500 | Batch 50/202 | Rec 0.000583 | Seg 0.270971 | Elapsed 1.0m | ETA 3.1m
Epoch 500/500 | Batch 60/202 | Rec 0.000586 | Seg 0.279501 | Elapsed 1.2m | ETA 2.9m
Epoch 500/500 | Batch 70/202 | Rec 0.000571 | Seg 0.275202 | Elapsed 1.4m | ETA 2.7m
Epoch 500/500 | Batch 80/202 | Rec 0.000586 | Seg 0.279711 | Elapsed 1.6m | ETA 2.5m
Epoch 500/500 | Batch 90/202 | Rec 0.000581 | Seg 0.276209 | Elapsed 1.9m | ETA 2.3m
Epoch 500/500 | Batch 100/202 | Rec 0.000579 | Seg 0.276963 | Elapsed 2.1m | ETA 2.1m
Epoch 500/500 | Batch 110/202 | Rec 0.000559 | Seg 0.268503 | Elapsed 2.3m | ETA 1.9m
Epoch 500/500 | Batch 120/202 | Rec 0.000560 | Seg 0.264161 | Elapsed 2.5m | ETA 1.7m
Epoch 500/500 | Batch 130/202 | Rec 0.000561 | Seg 0.262502 | Elapsed 2.7m | ETA 1.5m
Epoch 500/500 | Batch 140/202 | Rec 0.000561 | Seg 0.260730 | Elapsed 2.9m | ETA 1.3m
Epoch 500/500 | Batch 150/202 | Rec 0.000571 | Seg 0.264009 | Elapsed 3.1m | ETA 1.1m
Epoch 500/500 | Batch 160/202 | Rec 0.000582 | Seg 0.261514 | Elapsed 3.3m | ETA 0.9m
Epoch 500/500 | Batch 170/202 | Rec 0.000582 | Seg 0.265616 | Elapsed 3.5m | ETA 0.7m
Epoch 500/500 | Batch 180/202 | Rec 0.000582 | Seg 0.266655 | Elapsed 3.7m | ETA 0.5m
Epoch 500/500 | Batch 190/202 | Rec 0.000575 | Seg 0.265427 | Elapsed 3.9m | ETA 0.2m
Epoch 500/500 | Batch 200/202 | Rec 0.000576 | Seg 0.266247 | Elapsed 4.1m | ETA 0.0m
Epoch 500/500 | Batch 202/202 | Rec 0.000579 | Seg 0.267871 | Elapsed 4.2m | ETA 0.0m

2026-10-10 17:56:18,317 - INFO: Rec loss: 0.0005785898312823709
2026-10-10 17:56:18,317 - INFO: Seg loss: 0.26787092167847226
2026-10-10 17:56:18,317 - INFO: λ_rec: 1
2026-10-10 17:56:18,318 - INFO: λ_seg: 0.0001
2026-10-10 17:57:37,864 - INFO: -------------------Epoch: 500------------------------
2026-10-10 17:57:37,868 - INFO:
Validation stats:
        PSNR      SSIM       MSE
0  39.085745  0.975024  0.000129
2026-10-10 17:57:37,875 - INFO:
Validation stats:
                   IoU        F1      Prec    recall       Acc
bg,           0.995801  0.997846  0.997145  0.998648  0.995991
real potato   0.916594  0.956432  0.968742  0.944529  0.999897
fake potato   0.955075  0.976971  0.974375  0.979682  0.999966
real apple    0.773997  0.872553  0.985687  0.782795  0.999211
fake apple    0.589860  0.741980  0.974747  0.599014  0.998427
real orange   0.899457  0.947018  0.996547  0.902270  0.999867
fake orange   0.929188  0.963244  0.945995  0.981239  0.999786
real grape    0.766422  0.867718  0.955620  0.794709  0.999494
fake grape    0.898430  0.946448  0.926278  0.967620  0.999595
real lemon    0.541110  0.702185  0.619748  0.810049  0.999193
fake lemon    0.844383  0.915577  0.975687  0.862532  0.999664
real avocado  0.919436  0.957977  0.952891  0.963218  0.999922
fake avocado  0.666582  0.799891  0.999809  0.666667  0.999601
real pepper   0.867882  0.929219  0.897640  0.963207  0.999464
fake pepper   0.793298  0.884686  0.948575  0.828948  0.999485
real plant    0.871118  0.931071  0.946059  0.916646  0.998643
fake plant    0.768460  0.869023  0.830162  0.911810  0.999781
real banana   0.582937  0.736478  0.915271  0.616189  0.999009
fake banana   0.675877  0.806545  0.772313  0.844061  0.999255
real onion    0.626754  0.770509  0.644333  0.958284  0.999484
fake onion    0.914839  0.955476  0.962917  0.948247  0.999944
real unknown  0.665751  0.799292  0.703408  0.925572  0.999926
fake unknown  0.215713  0.354837  0.239084  0.688156  0.997892
total         0.768651  0.855782  0.875349  0.863221  0.999283
total(-bg)    0.758326  0.849324  0.869813  0.857066  0.999432
2026-10-10 17:57:38,343 - INFO: Epoch accounting: {'epoch': 500, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11310932, 27325, 60246, 122306, 144656, 67982, 59888, 188516, 211279, 68241, 71870, 48628, 31156, 208040, 137819, 134831, 18044, 67817, 73024, 92006, 48358, 8365, 36943], 'crops_with_class': [202, 16, 23, 36, 38, 20, 21, 32, 36, 34, 31, 16, 11, 50, 32, 21, 16, 21, 28, 34, 25, 10, 17], 'targeted_crops_by_class': [0, 1, 2, 4, 3, 1, 3, 10, 2, 4, 4, 8, 3, 2, 9, 3, 2, 5, 5, 3, 7, 4, 4], 'sampled_scene_counts': [0, 1, 3, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 0, 0, 3, 1, 1, 0, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 1, 0, 1, 2, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 2, 0, 1, 0, 0, 3, 1, 0, 1, 2, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 2, 1, 1, 1, 1, 3, 1, 1, 2, 1, 1, 0, 2, 1, 1, 3, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 3, 2, 0, 2, 4, 1, 2, 1, 2, 1, 1, 1, 1, 4, 1, 2, 0, 2, 0, 2, 2, 1, 0, 2, 0, 2, 0, 1, 0, 1, 1, 1, 1, 0, 3, 3, 1, 0, 1, 2, 1, 3, 1, 1, 3, 2, 1, 0, 2, 3, 1, 1, 1, 1, 2, 1], 'learning_rate': 2.5098448980016134e-07, 'attempted_updates': 202, 'optimizer_updates': 201, 'amp_skipped_updates': 1, 'train_reconstruction_loss': 0.0005785898312823709, 'train_segmentation_loss': 0.26787092167847226, 'val_foreground_miou_all22': 0.758325622631578, 'val_psnr_ref1': 39.085745086669924, 'elapsed_seconds': 330.83754444122314, 'peak_cuda_allocated_gib': 7.502231597900391}

Stopped after epoch 500; scheduler horizon remains 500
Saved epoch: 500 | block target: 500 | Missing checkpoint files: []
Download: /kaggle/working/balanced410_to_epoch500_20261010_094143_epoch500.zip

/kaggle/working/balanced410_to_epoch500_20261010_094143_epoch500.zip

Epoch500 completed. Download the full backup before stopping the session.

In [9]:
import statistics
records=[json.loads(p.read_text()) for p in sorted((CONT410_RUN/'result').glob('*_training.json'))]
assert [r['epoch'] for r in records]==list(range(411,501)),'The run has not completed90 new epochs.'
for start,end in [(411,425),(426,450),(451,475),(476,500)]:
    values=[100*r['val_foreground_miou_all22'] for r in records if start<=r['epoch']<=end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:',json.dumps(records[-1],indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))
print('The500-epoch reference schedule is complete. Download the final ZIP; do not run the test split yet.')

Epochs411-425: mean mIoU=73.40%, std=2.61 points
Epochs426-450: mean mIoU=74.06%, std=3.00 points
Epochs451-475: mean mIoU=74.27%, std=2.37 points
Epochs476-500: mean mIoU=74.56%, std=1.95 points
Final: {
  "epoch": 500,
  "scheduler_horizon": 500,
  "lambda_rec": 1,
  "lambda_seg": 0.0001,
  "sampling_policy": "balanced50_v1",
  "class_pixels_seen": [
    11310932,
    27325,
    60246,
    122306,
    144656,
    67982,
    59888,
    188516,
    211279,
    68241,
    71870,
    48628,
    31156,
    208040,
    137819,
    134831,
    18044,
    67817,
    73024,
    92006,
    48358,
    8365,
    36943
  ],
  "crops_with_class": [
    202,
    16,
    23,
    36,
    38,
    20,
    21,
    32,
    36,
    34,
    31,
    16,
    11,
    50,
    32,
    21,
    16,
    21,
    28,
    34,
    25,
    10,
    17
  ],
  "targeted_crops_by_class": [
    0,
    1,
    2,
    4,
    3,
    1,
    3,
    10,
    2,
    4,
    4,
    8,
    3,
    2,
    9,
    3,
    2,
    5,
    5,
    3,
    7,
    4,
    4
  ],
  "sampled_scene_counts": [
    0,
    1,
    3,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    1,
    1,
    2,
    0,
    0,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    2,
    1,
    0,
    0,
    3,
    1,
    1,
    0,
    2,
    1,
    1,
    1,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    0,
    1,
    1,
    1,
    0,
    1,
    1,
    0,
    1,
    2,
    1,
    1,
    0,
    1,
    2,
    0,
    0,
    0,
    0,
    1,
    1,
    1,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    2,
    1,
    1,
    1,
    1,
    0,
    1,
    1,
    2,
    0,
    1,
    0,
    0,
    3,
    1,
    0,
    1,
    2,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    0,
    0,
    1,
    0,
    1,
    0,
    0,
    1,
    1,
    0,
    1,
    1,
    1,
    0,
    1,
    2,
    1,
    1,
    1,
    1,
    3,
    1,
    1,
    2,
    1,
    1,
    0,
    2,
    1,
    1,
    3,
    1,
    1,
    1,
    0,
    1,
    1,
    0,
    0,
    0,
    1,
    3,
    2,
    0,
    2,
    4,
    1,
    2,
    1,
    2,
    1,
    1,
    1,
    1,
    4,
    1,
    2,
    0,
    2,
    0,
    2,
    2,
    1,
    0,
    2,
    0,
    2,
    0,
    1,
    0,
    1,
    1,
    1,
    1,
    0,
    3,
    3,
    1,
    0,
    1,
    2,
    1,
    3,
    1,
    1,
    3,
    2,
    1,
    0,
    2,
    3,
    1,
    1,
    1,
    1,
    2,
    1
  ],
  "learning_rate": 2.5098448980016134e-07,
  "attempted_updates": 202,
  "optimizer_updates": 201,
  "amp_skipped_updates": 1,
  "train_reconstruction_loss": 0.0005785898312823709,
  "train_segmentation_loss": 0.26787092167847226,
  "val_foreground_miou_all22": 0.758325622631578,
  "val_psnr_ref1": 39.085745086669924,
  "elapsed_seconds": 330.83754444122314,
  "peak_cuda_allocated_gib": 7.502231597900391
}
New successful updates: 18171
New AMP skips: 9
The500-epoch reference schedule is complete. Download the final ZIP; do not run the test split yet.

In [10]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch441 weights: /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth

In [11]:
NAME='epoch441_validation_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f')
RUN=WORK/NAME
subprocess.run([sys.executable,'test.py','--data_root',str(DATA),
    '--transpose_image','--eval_split','val','--pretrained_model_path',str(CHECKPOINT),
    '--outf',str(WORK),'--name',NAME,'--workers','0','--save_segmentation'],
    cwd=CODE,check=True)
OUT=RUN/'evaluation_val'
print('Evaluation complete:',OUT)

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
Evaluated 1/25
Evaluated 2/25
Evaluated 3/25
Evaluated 4/25
Evaluated 5/25
Evaluated 6/25
Evaluated 7/25
Evaluated 8/25
Evaluated 9/25
Evaluated 10/25
Evaluated 11/25
Evaluated 12/25
Evaluated 13/25
Evaluated 14/25
Evaluated 15/25
Evaluated 16/25
Evaluated 17/25
Evaluated 18/25
Evaluated 19/25
Evaluated 20/25
Evaluated 21/25
Evaluated 22/25
Evaluated 23/25
Evaluated 24/25
Evaluated 25/25
Completed val: 25 scenes. Results: /kaggle/working/epoch441_validation_audit_20261010_180454_292362/evaluation_val
Evaluation complete: /kaggle/working/epoch441_validation_audit_20261010_180454_292362/evaluation_val

In [12]:
EXPECTED_MIOU=0.7876837070566084
EXPECTED_PSNR=39.006845703125

import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['split']=='val' and meta['scene_count']==25
assert meta['checkpoint_sha256']==EXPECTED
assert len(set(meta['scenes']))==25
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(scene+'_confusion.npy')) for scene in meta['scenes']]
assert np.array_equal(sum(parts),cm), 'Per-scene confusion totals differ.'
assert len(list(OUT.glob('*_preview.png')))==25
assert not list(OUT.glob('*_hsi.npy'))
seg=pd.read_csv(OUT/'segmentation.csv',index_col=0)
rec=pd.read_csv(OUT/'reconstruction.csv')
miou=float(seg.loc['total(-bg)','IoU'])
psnr=float(rec.iloc[0]['PSNR'])
summary=dict(checkpoint_epoch=441,validation_scenes=25,foreground_miou=miou,
    psnr_ref1=psnr,logged_miou=EXPECTED_MIOU,logged_psnr=EXPECTED_PSNR,
    miou_difference=miou-EXPECTED_MIOU,psnr_difference=psnr-EXPECTED_PSNR,
    matches_logged_metrics=bool(abs(miou-EXPECTED_MIOU)<1e-5 and abs(psnr-EXPECTED_PSNR)<1e-3),
    scope='Independent full validation evaluation; no test performance or new training.')
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'evaluator_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in
    ['test.py','dataset.py','utils.py','public252-v1.json']},indent=2))
print(json.dumps(summary,indent=2))
display(seg)
display(rec)

import io
BASELINE_CSV=',IoU,F1,Prec,recall,Acc\n"bg,",0.9956056857102029,0.9977480073007325,0.9965542331594534,0.9990448847883433,0.9958021545410156\nreal potato,0.9309118500011194,0.9641699818594597,0.9956533415423344,0.9347105211080015,0.9999169921875\nfake potato,0.9522338696266445,0.9754825724698661,0.9823704124390311,0.9687892549478581,0.999964599609375\nreal apple,0.7667310698808576,0.86791656541023,0.9908069402405689,0.7722246759300102,0.999189453125\nfake apple,0.6043422511191895,0.7533351644919333,0.9394433318876814,0.6288393120399316,0.9984455871582031\nreal orange,0.9262720557716387,0.9616751181814689,0.9961533565435742,0.9295970249004514,0.9999024963378906\nfake orange,0.9395745507163982,0.968796030785346,0.9631307228319249,0.9746295652135722,0.999820556640625\nreal grape,0.633692737291463,0.7757318358626515,0.9847070619059142,0.6399912253161498,0.9992276000976562\nfake grape,0.903082134230324,0.949023210711403,0.9530405084725043,0.9451387990548249,0.9996247863769532\nreal lemon,0.5693110254280307,0.725507126786873,0.6111654314946624,0.8926252805423879,0.9992063903808593\nfake lemon,0.840714331095886,0.9134156552707563,0.9981191673239364,0.8420483170425653,0.9996624755859375\nreal avocado,0.9437285770065472,0.9709997714735892,0.99296377221617,0.9500820862055487,0.9999473571777344\nfake avocado,0.6883845379525112,0.8153874257399899,0.9998147962997259,0.6884723197083357,0.9996270751953125\nreal pepper,0.9032760667551863,0.9491303105984753,0.9317314223018788,0.967295173672221,0.9996211242675781\nfake pepper,0.900210338405034,0.9474349533973953,0.9640254341856007,0.9315024586678032,0.9997538757324219\nreal plant,0.8239757843089116,0.9034442395536414,0.9232679952816458,0.8845496691412166,0.9981098937988281\nfake plant,0.8616340199240582,0.9256251271314639,0.9794564309981504,0.8774923144652547,0.9998878479003906\nreal banana,0.5656761794155748,0.7225490193781943,0.9237762879397793,0.5933722627096818,0.9989762878417969\nfake banana,0.7485354041636234,0.8561356100749404,0.8759871485204622,0.8372594489278414,0.9994825744628906\nreal onion,0.7189954833355378,0.8364804440637529,0.7517166991824868,0.9429150322088324,0.9996670532226563\nfake onion,0.9352912861678297,0.9665138489307946,0.9866498492027745,0.9472792999448778,0.9999586486816406\nreal unknown,0.9121494474626685,0.954006635209248,0.9779558138320829,0.9312976210593873,0.9999856567382812\nfake unknown,0.2286106842011801,0.3721088184324781,0.24403452223142932,0.7834117931290874,0.9977726745605469\ntotal,0.7953451899987137,0.8727224988310731,0.9114141165232076,0.8635899278575733,0.9992849200704824\ntotal(-bg),0.7862424401936461,0.8670395211733616,0.90754411122156,0.8574328843607201,0.9994432275945492\n'
BASELINE_META={'status': 'completed', 'split': 'val', 'scope': 'full split', 'checkpoint_sha256': '89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'reference_amplitude': 1.0, 'seed': 3407, 'torch': '2.10.0+cu128', 'gpu': 'Tesla T4', 'config': {'data_root': '/kaggle/input/datasets/arnavnigamd/btp-data/public252', 'pretrained_model_path': '/kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/best_iou.pth', 'eval_split': 'val', 'transpose_image': True, 'outf': '/kaggle/working', 'name': 'epoch278_validation_audit_20260927_164048_773155', 'workers': 0, 'mask_path': '/kaggle/input/datasets/arnavnigamd/btp-code-8/BTP/mask/mask512x512.mat', 'limit': None, 'save_predictions': False, 'save_segmentation': True, 'batch_size': 1}, 'scene_count': 25, 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050']}
assert set(meta['scenes'])==set(BASELINE_META['scenes']), 'Validation scene membership changed.'
for field in ['protocol_sha256','mask_sha256','reference_amplitude']:
    assert meta[field]==BASELINE_META[field], f'Evaluation protocol changed: {field}'
baseline=pd.read_csv(io.StringIO(BASELINE_CSV),index_col=0)
assert list(seg.index)==list(baseline.index), 'Class ordering changed.'
comparison=pd.DataFrame({'epoch278_IoU_percent':100*baseline['IoU'],
    'epoch441_IoU_percent':100*seg['IoU'],
    'change_points':100*(seg['IoU']-baseline['IoU']),
    'epoch441_precision_percent':100*seg['Prec'],
    'epoch441_recall_percent':100*seg['recall']})
comparison.to_csv(RUN/'comparison_with_epoch278.csv')
(RUN/'epoch278_segmentation_reference.csv').write_text(BASELINE_CSV)
print('Per-class comparison; percentage-point changes, not statistical significance:')
display(comparison)

# Save results even if the comparison differs, so the difference can be investigated.
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir(WORK)
print('Download this archive before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))
if not summary['matches_logged_metrics']:
    print('Metrics differ from the training record: share this ZIP before further training.')

{
  "checkpoint_epoch": 441,
  "validation_scenes": 25,
  "foreground_miou": 0.7876837070566084,
  "psnr_ref1": 39.006845703125,
  "logged_miou": 0.7876837070566084,
  "logged_psnr": 39.006845703125,
  "miou_difference": 0.0,
  "psnr_difference": 0.0,
  "matches_logged_metrics": true,
  "scope": "Independent full validation evaluation; no test performance or new training."
}

                   IoU        F1      Prec    recall       Acc
bg,           0.995787  0.997839  0.997217  0.998562  0.995978
real potato   0.891879  0.942800  0.960693  0.925657  0.999866
fake potato   0.927040  0.962089  0.982955  0.942187  0.999946
real apple    0.814152  0.897507  0.959390  0.843211  0.999336
fake apple    0.599559  0.749608  0.988357  0.603823  0.998477
real orange   0.917723  0.957047  0.994754  0.922186  0.999891
fake orange   0.935366  0.966554  0.953960  0.979586  0.999806
real grape    0.815870  0.898550  0.943057  0.858145  0.999596
fake grape    0.895325  0.944722  0.915886  0.975539  0.999578
real lemon    0.731780  0.845069  0.780281  0.921709  0.999603
fake lemon    0.854995  0.921780  0.996813  0.857339  0.999692
real avocado  0.910046  0.952855  0.939375  0.966831  0.999911
fake avocado  0.711882  0.831646  0.999642  0.712063  0.999655
real pepper   0.845314  0.916124  0.871709  0.965418  0.999354
fake pepper   0.733120  0.845963  0.947891  0.763908  0.999337
real plant    0.866085  0.928187  0.961363  0.897318  0.998612
fake plant    0.788185  0.881498  0.841170  0.925997  0.999802
real banana   0.742898  0.852436  0.908818  0.802730  0.999376
fake banana   0.724092  0.839919  0.820787  0.860070  0.999397
real onion    0.653006  0.790034  0.681829  0.939199  0.999549
fake onion    0.938563  0.968258  0.976161  0.960580  0.999960
real unknown  0.801324  0.889656  0.858156  0.923664  0.999963
fake unknown  0.230837  0.375050  0.254165  0.715502  0.997991
total         0.796732  0.876313  0.892801  0.880923  0.999334
total(-bg)    0.787684  0.870789  0.888055  0.875576  0.999486

        PSNR      SSIM       MSE
0  39.006846  0.974785  0.000131

Per-class comparison; percentage-point changes, not statistical significance:

,epoch278_IoU_percent,epoch441_IoU_percent,change_points,epoch441_precision_percent,epoch441_recall_percent
"bg,",99.560569,99.578705,0.018137,99.721695,99.856212
real potato,93.091185,89.187860,-3.903325,96.069348,92.565671
fake potato,95.223387,92.704038,-2.519349,98.295452,94.218683
real apple,76.673107,81.415211,4.742104,95.939009,84.321096
fake apple,60.434225,59.955859,-0.478367,98.835747,60.382315
real orange,92.627206,91.772297,-0.854909,99.475392,92.218619
fake orange,93.957455,93.536566,-0.420889,95.396034,97.958639
real grape,63.369274,81.586992,18.217718,94.305678,85.814514
fake grape,90.308213,89.532462,-0.775751,91.588568,97.553933
real lemon,56.931103,73.178022,16.246920,78.028137,92.170864
fake lemon,84.071433,85.499532,1.428099,99.681341,85.733862
real avocado,94.372858,91.004635,-3.368222,93.937459,96.683085
fake avocado,68.838454,71.188168,2.349715,99.964194,71.206324
real pepper,90.327607,84.531375,-5.796231,87.170891,96.541798
fake pepper,90.021034,73.312035,-16.708999,94.789101,76.390756
real plant,82.397578,86.608457,4.210879,96.136308,89.731816
fake plant,86.163402,78.818537,-7.344865,84.117031,92.599691
real banana,56.567618,74.289844,17.722226,90.881832,80.272986
fake banana,74.853540,72.409217,-2.444323,82.078682,86.006967
real onion,71.899548,65.300610,-6.598938,68.182932,93.919944
fake onion,93.529129,93.856330,0.327202,97.616119,96.058039
real unknown,91.214945,80.132444,-11.082501,85.815595,92.366403
fake unknown,22.861068,23.083664,0.222596,25.416532,71.550162
total,79.534519,79.673168,0.138649,89.280134,88.092277
total(-bg),78.624244,78.768371,0.144127,88.805517,87.557553

Download this archive before stopping: epoch441_validation_audit_20261010_180454_292362.zip 7159885 bytes

/kaggle/working/epoch441_validation_audit_20261010_180454_292362.zip

**## Now new model**

In [13]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch441 weights: /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth

In [14]:
SCRIPT='"""Five-stage validation diagnostic; frozen model, no optimization."""\nfrom pathlib import Path\nimport argparse,hashlib,json,sys,math\nimport numpy as np\nimport torch\nfrom scipy.stats import rankdata\n\ndef translate_mask(mask,dx):\n    assert mask.ndim==2 and abs(dx)<mask.shape[1]\n    out=torch.zeros_like(mask)\n    if dx==0:return mask.clone()\n    if dx>0:out[:,dx:]=mask[:,:-dx]\n    else:out[:,:dx]=mask[:,-dx:]\n    return out\n\ndef build_phi(mask,bands=28,step=2):\n    h,w=mask.shape\n    phi=mask.new_zeros((1,bands,h,w+(bands-1)*step))\n    for c in range(bands):phi[0,c,:,step*c:step*c+w]=mask\n    return phi\n\ndef measure(x,phi,step=2):\n    b,c,h,w=x.shape\n    shifted=x.new_zeros((b,c,h,w+(c-1)*step))\n    for k in range(c):shifted[:,k,:,step*k:step*k+w]=x[:,k]\n    return (shifted*phi).sum(1)\n\ndef auc(score,event):\n    score=np.asarray(score);event=np.asarray(event,dtype=bool)\n    n1=int(event.sum());n0=int((~event).sum())\n    if not n1 or not n0:return None\n    ranks=rankdata(score,method=\'average\')\n    return float((ranks[event].sum()-n1*(n1+1)/2)/(n1*n0))\n\ndef transition_rows(prev,current,truth,signals,scene,condition,stage):\n    rows=[]\n    for group,region in [(\'foreground\',truth>0),(\'background\',truth==0)]+[(f\'class_{c}\',truth==c) for c in range(1,23)]:\n        pc=prev==truth;cc=current==truth;eligible=region&pc;event=~cc\n        row={\'scene\':scene,\'condition\':condition,\'to_stage\':stage,\'group\':group,\n             \'pixels\':int(region.sum()),\'previous_correct\':int(eligible.sum()),\n             \'correct_to_wrong\':int((eligible&event).sum()),\n             \'wrong_to_correct\':int((region&~pc&cc).sum())}\n        for name,score in signals.items():\n            if score is None:continue\n            vals=score[eligible];bad=event[eligible]\n            row[name+\'_auc_next_error_given_previous_correct\']=auc(vals,bad)\n            for tag,select in [(\'flipped\',bad),(\'retained\',~bad)]:\n                row[name+\'_mean_\'+tag]=float(vals[select].mean()) if select.any() else None\n        rows.append(row)\n    return rows\n\ndef sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()\n\ndef main():\n    p=argparse.ArgumentParser()\n    for arg in [\'code\',\'data\',\'checkpoint\',\'out\',\'reference\']:p.add_argument(\'--\'+arg,type=Path,required=True)\n    a=p.parse_args();sys.path.insert(0,str(a.code))\n    from dataset import evaluation_loader,get_class_names\n    from utils import init_mask,init_meas,Metrics_Rec,Metrics_Seg,set_seed\n    from models import model_generator\n    from run_public252 import validate\n    from scipy.io import loadmat\n    ref=json.loads(a.reference.read_text())\n    assert sha(a.checkpoint)==ref[\'checkpoint_sha256\']\n    spec_path=a.code/\'public252-v1.json\';mask_path=a.code/\'mask/mask512x512.mat\'\n    assert sha(spec_path)==ref[\'protocol_sha256\'] and sha(mask_path)==ref[\'mask_sha256\']\n    validate(a.data,json.loads(spec_path.read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(parents=True,exist_ok=False)\n    set_seed(3407)\n    loader=evaluation_loader(a.data,\'val\',0,True)\n    assert sorted(map(str,loader.dataset.names))==sorted(ref[\'scenes\']) and len(loader)==25\n    model=model_generator(\'CRSDUN\',28,23,str(a.checkpoint));model.eval()\n    phi,nominal=init_mask(str(mask_path),\'SSR\',1,28)\n    physical=torch.as_tensor(loadmat(mask_path)[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    assert torch.equal(build_phi(physical),phi)\n    assert torch.equal(translate_mask(physical,0),physical)\n    nominal_digest=hashlib.sha256(phi.cpu().numpy().tobytes()).hexdigest()\n    manifest={\'status\':\'running\',\'checkpoint_sha256\':sha(a.checkpoint),\'checkpoint_epoch\':441,\n        \'protocol_sha256\':sha(spec_path),\'mask_sha256\':sha(mask_path),\'scenes\':ref[\'scenes\'],\n        \'conditions\':{\'clean\':0,\'mask_plus1\':1,\'mask_minus1\':-1},\'torch\':str(torch.__version__),\n        \'gpu\':torch.cuda.get_device_name(0),\'script_sha256\':sha(__file__),\n        \'scope\':\'Frozen-model validation diagnostics, all five stages. Model always receives nominal SSR mask tuple.\',\n        \'residual_score\':\'Mean absolute nominal backprojected residual across28 bands, divided by RMS measurement plus1e-8.\',\n        \'stability_score\':\'Normalized Jensen-Shannon divergence between consecutive stage softmax distributions; unavailable at stage1.\',\n        \'auc_scope\':\'Per-scene descriptive next-stage error discrimination conditional on previous correctness; foreground/background and class separated. No independent-pixel significance claims.\',\n        \'caveat\':\'Synthetic zero-filled horizontal mask translation, not calibrated real hardware. Signals do not certify correctness; no causal feedback intervention.\'}\n    (a.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    import pandas as pd\n    overall=[]\n    with torch.inference_mode():\n      for condition,dx in manifest[\'conditions\'].items():\n        cond=a.out/condition;cond.mkdir()\n        acquisition=build_phi(translate_mask(physical,dx))\n        if dx:assert not torch.equal(acquisition,phi)\n        rec=[Metrics_Rec() for _ in range(5)];seg=[Metrics_Seg(23,get_class_names()) for _ in range(5)]\n        scene_records=[];transitions=[]\n        for index,sample in enumerate(loader):\n          scene=str(loader.dataset.names[index]);target=sample[\'image\'].float().cuda()\n          truth=sample[\'label\'].numpy()[0]\n          y=init_meas(target,acquisition,\'Y\')\n          if index==0:assert torch.allclose(measure(target,acquisition),y,rtol=1e-6,atol=1e-6)\n          xs,logits=model(y,nominal)\n          assert len(xs)==len(logits)==5\n          gt_cpu=target.cpu();previous_pred=None;previous_prob=None;previous_signals=None\n          rms=float(y.square().mean().sqrt())+1e-8\n          for k,(x,l) in enumerate(zip(xs,logits)):\n            assert x.shape==target.shape and l.shape==(1,23,*truth.shape)\n            assert torch.isfinite(x).all() and torch.isfinite(l).all()\n            x_cpu=x.float().cpu()\n            one=Metrics_Rec();one.add_batch(gt_cpu,x_cpu)\n            for field in [\'psnr\',\'ssim\',\'mse\',\'count\']:setattr(rec[k],field,getattr(rec[k],field)+getattr(one,field))\n            pred=l.argmax(1).cpu().numpy()[0]\n            seg[k].add_batch(truth[None],pred[None])\n            hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=23*23).reshape(23,23)\n            np.save(cond/f\'{scene}_stage{k+1}_confusion.npy\',hist)\n            prob=l.float().softmax(1).cpu().numpy()[0]\n            entropy=-(prob*np.log(np.maximum(prob,1e-12))).sum(0)/math.log(23)\n            instability=None\n            if previous_prob is not None:\n                mid=(prob+previous_prob)/2\n                instability=(.5*(prob*(np.log(np.maximum(prob,1e-12))-np.log(np.maximum(mid,1e-12)))).sum(0)+.5*(previous_prob*(np.log(np.maximum(previous_prob,1e-12))-np.log(np.maximum(mid,1e-12)))).sum(0))/math.log(2)\n            residual=y.unsqueeze(1)-model.mul_Phif(phi,x)\n            residual_map=model.mul_PhiTg(phi,residual).abs().mean(1)[0].cpu().numpy()/rms\n            signals={\'entropy\':entropy,\'nominal_residual\':residual_map,\'instability\':instability}\n            record={\'scene\':scene,\'condition\':condition,\'stage\':k+1,**one.get_table().iloc[0].to_dict(),\n                    \'normalized_measurement_residual_rms\':float(residual.square().mean().sqrt())/rms}\n            for region_name,region in [(\'foreground\',truth>0),(\'background\',truth==0)]:\n                for name,score in signals.items():\n                    if score is not None:record[name+\'_\'+region_name+\'_mean\']=float(score[region].mean()) if region.any() else None\n            scene_records.append(record)\n            if previous_pred is not None:transitions+=transition_rows(previous_pred,pred,truth,previous_signals,scene,condition,k+1)\n            previous_pred,previous_prob,previous_signals=pred,prob,signals\n          del xs,logits,target,gt_cpu,x,x_cpu,l,prob,previous_prob,previous_signals,residual\n          print(f\'{condition}: {index+1}/25 scenes, five stages\',flush=True)\n        assert hashlib.sha256(phi.cpu().numpy().tobytes()).hexdigest()==nominal_digest\n        pd.DataFrame(scene_records).to_csv(cond/\'per_scene_stage_metrics.csv\',index=False)\n        pd.DataFrame(transitions).to_csv(cond/\'stage_transitions_and_signals.csv\',index=False)\n        for k in range(5):\n            table=seg[k].get_table();table.to_csv(cond/f\'stage{k+1}_segmentation.csv\')\n            rec[k].get_table().to_csv(cond/f\'stage{k+1}_reconstruction.csv\',index=False)\n            np.save(cond/f\'stage{k+1}_aggregate_confusion.npy\',seg[k].confusion_matrix)\n            summed=sum(np.load(cond/f\'{s}_stage{k+1}_confusion.npy\') for s in ref[\'scenes\'])\n            assert np.array_equal(summed,seg[k].confusion_matrix)\n            overall.append({\'condition\':condition,\'stage\':k+1,\'foreground_miou_all22\':float(table.loc[\'total(-bg)\',\'IoU\']),**rec[k].get_table().iloc[0].to_dict()})\n        pd.DataFrame(overall).to_csv(a.out/\'stage_summary.csv\',index=False)\n        if condition==\'clean\':\n            final=overall[-1]\n            check={\'miou_difference\':final[\'foreground_miou_all22\']-ref[\'miou\'],\'psnr_difference\':final[\'PSNR\']-ref[\'psnr\']}\n            check[\'passed\']=abs(check[\'miou_difference\'])<1e-6 and abs(check[\'psnr_difference\'])<1e-4\n            (a.out/\'clean_equivalence.json\').write_text(json.dumps(check,indent=2))\n            assert check[\'passed\'], \'Clean final-stage reproduction failed; stopping before stresses.\'\n    manifest[\'status\']=\'completed\';(a.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    print(pd.DataFrame(overall).to_string(index=False),flush=True)\n\nif __name__==\'__main__\':main()\n'
TEST_SCRIPT="import numpy as np\nimport torch\nfrom stage_audit import translate_mask,build_phi,measure,transition_rows,auc\nmask=torch.tensor([[1.,2.,3.,4.],[5.,6.,7.,8.]])\noriginal=mask.clone()\nassert torch.equal(translate_mask(mask,1),torch.tensor([[0.,1.,2.,3.],[0.,5.,6.,7.]]))\nassert torch.equal(translate_mask(mask,-1),torch.tensor([[2.,3.,4.,0.],[6.,7.,8.,0.]]))\nassert torch.equal(translate_mask(mask,0),mask) and torch.equal(mask,original)\nx=torch.arange(24,dtype=torch.float32).reshape(1,3,2,4)\nfor dx in [0,1,-1]:\n shifted=translate_mask(mask,dx);phi=build_phi(shifted,bands=3)\n y=measure(x,phi);expected=torch.zeros(1,2,8)\n for c in range(3):expected[:,:,2*c:2*c+4]+=x[:,c]*shifted\n assert torch.equal(y,expected)\nassert auc([.1,.2,.8,.9],[0,0,1,1])==1\nassert auc([.5,.5],[0,1])==.5\nassert auc([.5,.7],[0,0]) is None\ntruth=np.array([[1,1],[0,0]]);prev=np.array([[1,1],[0,1]]);current=np.array([[2,1],[0,0]])\nrows=transition_rows(prev,current,truth,{'entropy':np.array([[.9,.1],[.2,.3]]),'instability':None},'s','clean',2)\nfg=next(r for r in rows if r['group']=='foreground');bg=next(r for r in rows if r['group']=='background')\nassert fg['correct_to_wrong']==1 and fg['previous_correct']==2\nassert fg['entropy_auc_next_error_given_previous_correct']==1\nassert bg['wrong_to_correct']==1\nassert 'instability_auc_next_error_given_previous_correct' not in fg\nprint('PASS: zero-filled mask shifts, physical-mask measurement construction, unchanged mask, AUROC ties/degenerate cases, and foreground/background transition accounting.')\n"
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}

RUN=WORK/('stage_reliability_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
(RUN/'stage_audit.py').write_text(SCRIPT)
(RUN/'verify_stage_audit.py').write_text(TEST_SCRIPT)
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'source_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in ['models/CRSDUN.py','dataset.py','utils.py','public252-v1.json']},indent=2))
subprocess.run([sys.executable,str(RUN/'verify_stage_audit.py')],cwd=RUN,check=True)
print('Output folder:',RUN)

PASS: zero-filled mask shifts, physical-mask measurement construction, unchanged mask, AUROC ties/degenerate cases, and foreground/background transition accounting.
Output folder: /kaggle/working/stage_reliability_epoch441_20261010_181504_618640

In [15]:
from IPython.display import display,FileLink
try:
    subprocess.run([sys.executable,'-u',str(RUN/'stage_audit.py'),
        '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
        '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json')],cwd=CODE,check=True)
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z:assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
clean: 1/25 scenes, five stages
clean: 2/25 scenes, five stages
clean: 3/25 scenes, five stages
clean: 4/25 scenes, five stages
clean: 5/25 scenes, five stages
clean: 6/25 scenes, five stages
clean: 7/25 scenes, five stages
clean: 8/25 scenes, five stages
clean: 9/25 scenes, five stages
clean: 10/25 scenes, five stages
clean: 11/25 scenes, five stages
clean: 12/25 scenes, five stages
clean: 13/25 scenes, five stages
clean: 14/25 scenes, five stages
clean: 15/25 scenes, five stages
clean: 16/25 scenes, five stages
clean: 17/25 scenes, five stages
clean: 18/25 scenes, five stages
clean: 19/25 scenes, five stages
clean: 20/25 scenes, five stages
clean: 21/25 scenes, five stages
clean: 22/25 scenes, five stages
clean: 23/25 scenes, five stages
clean: 24/25 scenes, five stages
clean: 25/25 scenes, five stages
mask_plus1: 1/25 scenes, five stages
mask_plus1: 2/25 scenes, five stages
mask_plus1: 3/25 scenes, five stages
mask_plus1: 4/25 scenes, five stages
mask_plus1: 5/25 scenes, five stages
mask_plus1: 6/25 scenes, five stages
mask_plus1: 7/25 scenes, five stages
mask_plus1: 8/25 scenes, five stages
mask_plus1: 9/25 scenes, five stages
mask_plus1: 10/25 scenes, five stages
mask_plus1: 11/25 scenes, five stages
mask_plus1: 12/25 scenes, five stages
mask_plus1: 13/25 scenes, five stages
mask_plus1: 14/25 scenes, five stages
mask_plus1: 15/25 scenes, five stages
mask_plus1: 16/25 scenes, five stages
mask_plus1: 17/25 scenes, five stages
mask_plus1: 18/25 scenes, five stages
mask_plus1: 19/25 scenes, five stages
mask_plus1: 20/25 scenes, five stages
mask_plus1: 21/25 scenes, five stages
mask_plus1: 22/25 scenes, five stages
mask_plus1: 23/25 scenes, five stages
mask_plus1: 24/25 scenes, five stages
mask_plus1: 25/25 scenes, five stages
mask_minus1: 1/25 scenes, five stages
mask_minus1: 2/25 scenes, five stages
mask_minus1: 3/25 scenes, five stages
mask_minus1: 4/25 scenes, five stages
mask_minus1: 5/25 scenes, five stages
mask_minus1: 6/25 scenes, five stages
mask_minus1: 7/25 scenes, five stages
mask_minus1: 8/25 scenes, five stages
mask_minus1: 9/25 scenes, five stages
mask_minus1: 10/25 scenes, five stages
mask_minus1: 11/25 scenes, five stages
mask_minus1: 12/25 scenes, five stages
mask_minus1: 13/25 scenes, five stages
mask_minus1: 14/25 scenes, five stages
mask_minus1: 15/25 scenes, five stages
mask_minus1: 16/25 scenes, five stages
mask_minus1: 17/25 scenes, five stages
mask_minus1: 18/25 scenes, five stages
mask_minus1: 19/25 scenes, five stages
mask_minus1: 20/25 scenes, five stages
mask_minus1: 21/25 scenes, five stages
mask_minus1: 22/25 scenes, five stages
mask_minus1: 23/25 scenes, five stages
mask_minus1: 24/25 scenes, five stages
mask_minus1: 25/25 scenes, five stages
  condition  stage  foreground_miou_all22      PSNR     SSIM      MSE
      clean      1               0.005484 31.244791 0.931951 0.000771
      clean      2               0.114054 35.856313 0.957340 0.000270
      clean      3               0.665539 37.108682 0.966230 0.000202
      clean      4               0.636575 38.603490 0.970424 0.000143
      clean      5               0.787684 39.006846 0.974785 0.000131
 mask_plus1      1               0.001045 19.689185 0.570635 0.010800
 mask_plus1      2               0.000736 16.695964 0.151602 0.021483
 mask_plus1      3               0.012277 15.577501 0.114122 0.027798
 mask_plus1      4               0.009099 10.649412 0.099360 0.310092
 mask_plus1      5               0.015743 10.009459 0.107820 0.373303
mask_minus1      1               0.001876 19.940973 0.579538 0.010180
mask_minus1      2               0.001138 16.837921 0.153019 0.020786
mask_minus1      3               0.015625 15.662102 0.114881 0.027258
mask_minus1      4               0.014110 11.038959 0.100340 0.100175
mask_minus1      5               0.018487 10.341741 0.108856 0.129025
Download this ZIP even if an error occurred: stage_reliability_epoch441_20261010_181504_618640.zip

/kaggle/working/stage_reliability_epoch441_20261010_181504_618640.zip

In [16]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed','Partial run: share the ZIP and error.'
assert json.loads((RUN/'results/clean_equivalence.json').read_text())['passed']
summary=pd.read_csv(RUN/'results/stage_summary.csv')
summary['foreground_miou_percent']=100*summary['foreground_miou_all22']
display(summary[['condition','stage','foreground_miou_percent','PSNR','SSIM','MSE']])
print('Completed. Share the ZIP. Stage changes are descriptive and do not alone establish harmful feedback or a causal mechanism.')

      condition  stage  foreground_miou_percent       PSNR      SSIM       MSE
0         clean      1                 0.548378  31.244791  0.931951  0.000771
1         clean      2                11.405355  35.856313  0.957340  0.000270
2         clean      3                66.553853  37.108682  0.966230  0.000202
3         clean      4                63.657516  38.603490  0.970424  0.000143
4         clean      5                78.768371  39.006846  0.974785  0.000131
5    mask_plus1      1                 0.104548  19.689185  0.570635  0.010800
6    mask_plus1      2                 0.073628  16.695964  0.151602  0.021483
7    mask_plus1      3                 1.227699  15.577501  0.114122  0.027798
8    mask_plus1      4                 0.909888  10.649412  0.099360  0.310092
9    mask_plus1      5                 1.574307  10.009459  0.107820  0.373303
10  mask_minus1      1                 0.187586  19.940973  0.579538  0.010180
11  mask_minus1      2                 0.113762  16.837921  0.153019  0.020786
12  mask_minus1      3                 1.562503  15.662102  0.114881  0.027258
13  mask_minus1      4                 1.411001  11.038959  0.100340  0.100175
14  mask_minus1      5                 1.848736  10.341741  0.108856  0.129025

Completed. Share the ZIP. Stage changes are descriptive and do not alone establish harmful feedback or a causal mechanism.

In [17]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch441 weights: /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth

In [18]:
SCRIPT='"""Frozen validation: paired nominal/matched operators under synthetic mask mixing."""\nfrom pathlib import Path\nimport argparse\nimport hashlib\nimport json\nimport time\nimport numpy as np\nimport torch\n\nALPHAS = (0.05, 0.10, 0.25, 1.0)\n\ndef sha(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\ndef tensor_sha(x):\n    return hashlib.sha256(x.detach().cpu().contiguous().numpy().tobytes()).hexdigest()\n\ndef mix_mask(mask, dx, alpha):\n    assert mask.ndim == 2 and dx in (-1, 1) and 0 <= alpha <= 1\n    shifted = torch.zeros_like(mask)\n    if dx == 1:\n        shifted[:, 1:] = mask[:, :-1]\n    else:\n        shifted[:, :-1] = mask[:, 1:]\n    return (1-alpha)*mask + alpha*shifted\n\ndef make_operator(mask, bands=28, step=2):\n    h, w = mask.shape\n    phi = mask.new_zeros((1, bands, h, w+(bands-1)*step))\n    for c in range(bands):\n        phi[0, c, :, step*c:step*c+w] = mask\n    back = torch.stack([phi[:, c, :, step*c:step*c+w] for c in range(bands)], dim=1)\n    energy = phi.square().sum(1, keepdim=True)\n    energy = torch.where(energy == 0, torch.ones_like(energy), energy)\n    return back, phi, energy\n\ndef measure(x, phi, step=2):\n    b, c, h, w = x.shape\n    y = x.new_zeros((b, h, phi.shape[-1]))\n    for k in range(c):\n        y[:, :, step*k:step*k+w] += x[:, k]*phi[:, k, :, step*k:step*k+w]\n    return y\n\ndef relative_error(a, b):\n    return float(torch.linalg.vector_norm(a-b)/torch.linalg.vector_norm(b).clamp_min(1e-12))\n\ndef main():\n    import sys\n    p = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\'):\n        p.add_argument(\'--\'+key, type=Path, required=True)\n    a = p.parse_args()\n    sys.path.insert(0, str(a.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, shift_back_mask, Metrics_Rec, Metrics_Seg, set_seed\n    from run_public252 import validate\n\n    ref = json.loads(a.reference.read_text())\n    mask_path = a.code/\'mask/mask512x512.mat\'\n    assert sha(a.checkpoint) == ref[\'checkpoint_sha256\']\n    assert sha(mask_path) == ref[\'mask_sha256\']\n    assert sha(a.code/\'public252-v1.json\') == ref[\'protocol_sha256\']\n    validate(a.data, json.loads((a.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(exist_ok=False, parents=True)\n    set_seed(3407)\n    loader = evaluation_loader(a.data, \'val\', 0, True)\n    scenes = list(map(str, loader.dataset.names))\n    assert sorted(scenes) == sorted(ref[\'scenes\']) and len(scenes) == 25\n    model = model_generator(\'CRSDUN\', 28, 23, str(a.checkpoint))\n    model.eval()\n    physical = torch.as_tensor(loadmat(mask_path)[\'mask\'], dtype=torch.float32, device=\'cuda\')\n    phi, nominal = init_mask(str(mask_path), \'SSR\', 1, 28)\n    built = make_operator(physical)\n    assert all(torch.equal(x, y) for x, y in zip(built, nominal)), \'Nominal SSR tuple differs\'\n    assert all(torch.equal(x, y) for x, y in zip(make_operator(mix_mask(physical, 1, 0)), nominal))\n    nominal_hashes = [tensor_sha(x) for x in nominal]\n    conditions = [(\'clean\', 0, 0.0)] + [(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\', dx, alpha) for alpha in ALPHAS for dx in (1, -1)]\n    manifest = dict(status=\'running\', checkpoint_epoch=441, checkpoint_sha256=sha(a.checkpoint),\n                    protocol_sha256=ref[\'protocol_sha256\'], mask_sha256=sha(mask_path),\n                    script_sha256=sha(__file__), scenes=scenes, alphas=list(ALPHAS),\n                    conditions=conditions, completed_conditions=[], torch=str(torch.__version__),\n                    gpu=torch.cuda.get_device_name(0), expected_model_forwards=425,\n                    test_evaluated=False, training=False,\n                    scope=\'25 validation scenes; frozen model; identical measurement reused for nominal and matched full SSR tuples.\',\n                    caveat=\'Linear mask mixing with a zero-filled +/-1px shift is synthetic, not calibrated hardware motion. Matched masks may still be outside the training distribution.\',\n                    metrics=\'Every-stage confusion/MSE/PSNR_ref1; SSIM_ref1 final stage only. Scene-averaged reconstruction metrics; aggregate confusion mIoU.\')\n    manifest_path = a.out/\'experiment.json\'\n    def save_manifest():\n        manifest_path.write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    summary, severity_rows = [], []\n    started = time.time()\n    try:\n      with torch.inference_mode():\n        for name, dx, alpha in conditions:\n            folder = a.out/name\n            folder.mkdir()\n            mixed = physical if name == \'clean\' else mix_mask(physical, dx, alpha)\n            matched = make_operator(mixed)\n            acquisition = matched[1]\n            assert torch.equal(matched[0], shift_back_mask(acquisition))\n            expected_energy = acquisition.square().sum(1, keepdim=True)\n            expected_energy[expected_energy == 0] = 1\n            assert torch.equal(matched[2], expected_energy)\n            paired_ops = [(\'nominal\', nominal)] if name == \'clean\' else [(\'nominal\', nominal), (\'matched\', matched)]\n            severity_rows.append(dict(condition=name, dx=dx, alpha=alpha,\n                                      mask_relative_error=relative_error(mixed, physical),\n                                      changed_fraction=float((mixed != physical).float().mean()),\n                                      mean_transmittance=float(mixed.mean())))\n            pd.DataFrame(severity_rows).to_csv(a.out/\'mask_severity.csv\', index=False)\n            seg = {mode: [Metrics_Seg(23, get_class_names()) for _ in range(5)] for mode, _ in paired_ops}\n            records = []\n            for index, sample in enumerate(loader):\n                scene = scenes[index]\n                target = sample[\'image\'].float().cuda()\n                gt_cpu = target.cpu()\n                truth = sample[\'label\'].numpy()[0]\n                y = init_meas(target, acquisition, \'Y\')\n                if index == 0:\n                    assert torch.allclose(measure(target, acquisition), y, atol=1e-6, rtol=1e-6)\n                y_nominal = init_meas(target, phi, \'Y\')\n                measurement_error = relative_error(y, y_nominal)\n                y_digest = tensor_sha(y)\n                for mode, operator in paired_ops:\n                    op_hashes = [tensor_sha(x) for x in operator]\n                    xs, logits = model(y, operator)\n                    assert len(xs) == len(logits) == 5\n                    for k, (x, logit) in enumerate(zip(xs, logits), 1):\n                        assert x.shape == target.shape and logit.shape == (1, 23, *truth.shape)\n                        assert torch.isfinite(x).all() and torch.isfinite(logit).all(), f\'Nonfinite: {name}/{mode}/{scene}/stage{k}\'\n                        x_cpu = x.float().cpu()\n                        pred = logit.argmax(1).cpu().numpy()[0]\n                        hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                        np.save(folder/f\'{mode}_{scene}_stage{k}_confusion.npy\', hist)\n                        seg[mode][k-1].add_batch(truth[None], pred[None])\n                        mse = float((x_cpu-gt_cpu).square().mean())\n                        metrics = {\'MSE\':mse, \'PSNR\':float(-10*torch.log10(torch.tensor(mse))), \'SSIM\':None}\n                        if k == 5:\n                            rec = Metrics_Rec()\n                            rec.add_batch(gt_cpu, x_cpu)\n                            metrics = rec.get_table().iloc[0].to_dict()\n                        records.append(dict(condition=name, mode=mode, scene=scene, stage=k,\n                                            dx=dx, alpha=alpha, measurement_sha256=y_digest,\n                                            measurement_relative_error=measurement_error, **metrics))\n                    assert tensor_sha(y) == y_digest, \'Measurement mutated during inference\'\n                    assert [tensor_sha(t) for t in operator] == op_hashes, \'SSR tuple mutated\'\n                    del xs, logits, x, logit, x_cpu\n                pd.DataFrame(records).to_csv(folder/\'per_scene_stage_metrics.csv\', index=False)\n                del target, gt_cpu, y, y_nominal\n                print(f\'{name}: {index+1}/25; modes={len(paired_ops)}; elapsed={(time.time()-started)/60:.1f}min\', flush=True)\n            assert [tensor_sha(t) for t in nominal] == nominal_hashes\n            for mode, _ in paired_ops:\n                for k in range(1,6):\n                    acc = seg[mode][k-1]\n                    assert np.array_equal(sum(np.load(folder/f\'{mode}_{s}_stage{k}_confusion.npy\') for s in scenes), acc.confusion_matrix)\n                    np.save(folder/f\'{mode}_stage{k}_aggregate_confusion.npy\', acc.confusion_matrix)\n                    table = acc.get_table()\n                    table.to_csv(folder/f\'{mode}_stage{k}_segmentation.csv\')\n                    items = [r for r in records if r[\'mode\'] == mode and r[\'stage\'] == k]\n                    summary.append(dict(condition=name, mode=mode, stage=k, alpha=alpha, dx=dx,\n                                        foreground_miou_all22=float(table.loc[\'total(-bg)\', \'IoU\']),\n                                        PSNR=float(np.mean([r[\'PSNR\'] for r in items])),\n                                        MSE=float(np.mean([r[\'MSE\'] for r in items])),\n                                        SSIM=float(np.mean([r[\'SSIM\'] for r in items])) if k == 5 else None))\n            pd.DataFrame(summary).to_csv(a.out/\'stage_summary.csv\', index=False)\n            if name == \'clean\':\n                final = summary[-1]\n                check = dict(miou_difference=final[\'foreground_miou_all22\']-ref[\'miou\'], psnr_difference=final[\'PSNR\']-ref[\'psnr\'])\n                check[\'passed\'] = abs(check[\'miou_difference\']) < 1e-6 and abs(check[\'psnr_difference\']) < 1e-4\n                (a.out/\'clean_equivalence.json\').write_text(json.dumps(check, indent=2))\n                assert check[\'passed\'], \'Clean check failed; stopping before stresses\'\n            manifest[\'completed_conditions\'].append(name)\n            save_manifest()\n        pairs = []\n        for name, dx, alpha in conditions[1:]:\n            n, m = [next(r for r in summary if r[\'condition\']==name and r[\'mode\']==mode and r[\'stage\']==5) for mode in (\'nominal\', \'matched\')]\n            pairs.append(dict(condition=name, dx=dx, alpha=alpha,\n                              nominal_miou_percent=100*n[\'foreground_miou_all22\'], matched_miou_percent=100*m[\'foreground_miou_all22\'],\n                              matched_minus_nominal_miou_points=100*(m[\'foreground_miou_all22\']-n[\'foreground_miou_all22\']),\n                              nominal_psnr=n[\'PSNR\'], matched_psnr=m[\'PSNR\'], matched_minus_nominal_psnr=m[\'PSNR\']-n[\'PSNR\']))\n        pd.DataFrame(pairs).to_csv(a.out/\'paired_final_summary.csv\', index=False)\n        manifest[\'status\'] = \'completed\'\n        print(pd.DataFrame(pairs).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest[\'status\'] = \'failed\'\n        manifest[\'error\'] = repr(exc)\n        raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started\n        save_manifest()\n\nif __name__ == \'__main__\':\n    main()\n'
TEST_SCRIPT='"""CPU operator tests, including comparisons to the production helpers."""\nimport argparse\nimport sys\nimport torch\nfrom operator_control import mix_mask, make_operator, measure, relative_error, tensor_sha\n\np = argparse.ArgumentParser()\np.add_argument(\'--code\', required=True)\na = p.parse_args()\nsys.path.insert(0, a.code)\nfrom utils import init_meas, shift_back_mask\n\nm = torch.tensor([[1.,0.,1.,0.],[0.,1.,0.,1.]])\nunchanged = m.clone()\nx = torch.arange(24, dtype=torch.float32).reshape(1,3,2,4)/24\nfor dx in (-1,1):\n    expected_shift = torch.tensor([[0.,1.,0.,0.],[1.,0.,1.,0.]]) if dx == -1 else torch.tensor([[0.,1.,0.,1.],[0.,0.,1.,0.]])\n    assert torch.equal(mix_mask(m,dx,1), expected_shift)\n    assert torch.equal(mix_mask(m,dx,0), m)\n    for alpha in (0.,.05,.1,.25,1.):\n        mixed = mix_mask(m, dx, alpha)\n        assert torch.equal(mixed, (1-alpha)*m+alpha*expected_shift)\n        back, phi, energy = make_operator(mixed, bands=3)\n        assert torch.equal(back, shift_back_mask(phi))\n        assert torch.equal(back, mixed[None,None].repeat(1,3,1,1))\n        e = phi.square().sum(1, keepdim=True)\n        e[e==0] = 1\n        assert torch.equal(energy, e)\n        if alpha == .25:\n            assert not torch.equal(energy, phi.sum(1, keepdim=True)), \'Fractional masks must use squared energy\'\n        independent = torch.zeros(1,2,8)\n        for c in range(3):\n            independent[:,:,2*c:2*c+4] += x[:,c]*mixed\n        y = measure(x, phi)\n        assert torch.allclose(y, independent)\n        # Production shift() allocates CUDA explicitly, even for CPU input.\n        if torch.cuda.is_available():\n            production = init_meas(x.cuda(), phi.cuda(), \'Y\').cpu()\n            assert torch.allclose(y, production)\n        assert relative_error(mixed,m) >= 0\n        assert tensor_sha(y) == tensor_sha(y.clone())\nassert torch.equal(m, unchanged)\nassert relative_error(m,m) == 0\nzero = make_operator(torch.zeros_like(m), bands=3)\nassert torch.equal(zero[2], torch.ones_like(zero[2]))\nassert torch.cuda.is_available(), \'Production measurement comparison requires CUDA; CPU-only checks finished.\'\nprint(\'PASS: both zero-filled shifts, mixing endpoints/interiors, all SSR components, squared fractional-mask energy, zero-energy guard, production measurement agreement on CUDA, no mask mutation.\')\n'
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}

RUN=WORK/('operator_control_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
(RUN/'operator_control.py').write_text(SCRIPT)
(RUN/'verify_operator_control.py').write_text(TEST_SCRIPT)
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'source_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in ['models/CRSDUN.py','dataset.py','utils.py','public252-v1.json']},indent=2))
subprocess.run([sys.executable,str(RUN/'verify_operator_control.py'),'--code',str(CODE)],cwd=RUN,check=True)
print('Output folder:',RUN)

PASS: both zero-filled shifts, mixing endpoints/interiors, all SSR components, squared fractional-mask energy, zero-energy guard, production measurement agreement on CUDA, no mask mutation.
Output folder: /kaggle/working/operator_control_epoch441_20261010_183309_608911

In [19]:
from IPython.display import display,FileLink
try:
    with (RUN/'console.log').open('w') as log:
        command=[sys.executable,'-u',str(RUN/'operator_control.py'),
                 '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
                 '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json')]
        proc=subprocess.Popen(command,cwd=CODE,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)
        try:
            for line in proc.stdout:
                print(line,end='',flush=True)
                log.write(line);log.flush()
            code=proc.wait()
            if code: raise subprocess.CalledProcessError(code,command)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try: proc.wait(timeout=10)
                except subprocess.TimeoutExpired: proc.kill();proc.wait()
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
clean: 1/25; modes=1; elapsed=0.1min
clean: 2/25; modes=1; elapsed=0.1min
clean: 3/25; modes=1; elapsed=0.2min
clean: 4/25; modes=1; elapsed=0.3min
clean: 5/25; modes=1; elapsed=0.3min
clean: 6/25; modes=1; elapsed=0.4min
clean: 7/25; modes=1; elapsed=0.4min
clean: 8/25; modes=1; elapsed=0.5min
clean: 9/25; modes=1; elapsed=0.5min
clean: 10/25; modes=1; elapsed=0.6min
clean: 11/25; modes=1; elapsed=0.7min
clean: 12/25; modes=1; elapsed=0.7min
clean: 13/25; modes=1; elapsed=0.8min
clean: 14/25; modes=1; elapsed=0.8min
clean: 15/25; modes=1; elapsed=0.9min
clean: 16/25; modes=1; elapsed=0.9min
clean: 17/25; modes=1; elapsed=1.0min
clean: 18/25; modes=1; elapsed=1.1min
clean: 19/25; modes=1; elapsed=1.1min
clean: 20/25; modes=1; elapsed=1.2min
clean: 21/25; modes=1; elapsed=1.2min
clean: 22/25; modes=1; elapsed=1.3min
clean: 23/25; modes=1; elapsed=1.3min
clean: 24/25; modes=1; elapsed=1.4min
clean: 25/25; modes=1; elapsed=1.5min
plus1_alpha0.05: 1/25; modes=2; elapsed=1.6min
plus1_alpha0.05: 2/25; modes=2; elapsed=1.7min
plus1_alpha0.05: 3/25; modes=2; elapsed=1.8min
plus1_alpha0.05: 4/25; modes=2; elapsed=1.9min
plus1_alpha0.05: 5/25; modes=2; elapsed=2.0min
plus1_alpha0.05: 6/25; modes=2; elapsed=2.2min
plus1_alpha0.05: 7/25; modes=2; elapsed=2.3min
plus1_alpha0.05: 8/25; modes=2; elapsed=2.4min
plus1_alpha0.05: 9/25; modes=2; elapsed=2.5min
plus1_alpha0.05: 10/25; modes=2; elapsed=2.6min
plus1_alpha0.05: 11/25; modes=2; elapsed=2.7min
plus1_alpha0.05: 12/25; modes=2; elapsed=2.8min
plus1_alpha0.05: 13/25; modes=2; elapsed=3.0min
plus1_alpha0.05: 14/25; modes=2; elapsed=3.1min
plus1_alpha0.05: 15/25; modes=2; elapsed=3.2min
plus1_alpha0.05: 16/25; modes=2; elapsed=3.3min
plus1_alpha0.05: 17/25; modes=2; elapsed=3.4min
plus1_alpha0.05: 18/25; modes=2; elapsed=3.5min
plus1_alpha0.05: 19/25; modes=2; elapsed=3.7min
plus1_alpha0.05: 20/25; modes=2; elapsed=3.8min
plus1_alpha0.05: 21/25; modes=2; elapsed=3.9min
plus1_alpha0.05: 22/25; modes=2; elapsed=4.0min
plus1_alpha0.05: 23/25; modes=2; elapsed=4.1min
plus1_alpha0.05: 24/25; modes=2; elapsed=4.2min
plus1_alpha0.05: 25/25; modes=2; elapsed=4.3min
minus1_alpha0.05: 1/25; modes=2; elapsed=4.5min
minus1_alpha0.05: 2/25; modes=2; elapsed=4.6min
minus1_alpha0.05: 3/25; modes=2; elapsed=4.7min
minus1_alpha0.05: 4/25; modes=2; elapsed=4.8min
minus1_alpha0.05: 5/25; modes=2; elapsed=4.9min
minus1_alpha0.05: 6/25; modes=2; elapsed=5.0min
minus1_alpha0.05: 7/25; modes=2; elapsed=5.2min
minus1_alpha0.05: 8/25; modes=2; elapsed=5.3min
minus1_alpha0.05: 9/25; modes=2; elapsed=5.4min
minus1_alpha0.05: 10/25; modes=2; elapsed=5.5min
minus1_alpha0.05: 11/25; modes=2; elapsed=5.6min
minus1_alpha0.05: 12/25; modes=2; elapsed=5.7min
minus1_alpha0.05: 13/25; modes=2; elapsed=5.8min
minus1_alpha0.05: 14/25; modes=2; elapsed=6.0min
minus1_alpha0.05: 15/25; modes=2; elapsed=6.1min
minus1_alpha0.05: 16/25; modes=2; elapsed=6.2min
minus1_alpha0.05: 17/25; modes=2; elapsed=6.3min
minus1_alpha0.05: 18/25; modes=2; elapsed=6.4min
minus1_alpha0.05: 19/25; modes=2; elapsed=6.5min
minus1_alpha0.05: 20/25; modes=2; elapsed=6.6min
minus1_alpha0.05: 21/25; modes=2; elapsed=6.8min
minus1_alpha0.05: 22/25; modes=2; elapsed=6.9min
minus1_alpha0.05: 23/25; modes=2; elapsed=7.0min
minus1_alpha0.05: 24/25; modes=2; elapsed=7.1min
minus1_alpha0.05: 25/25; modes=2; elapsed=7.2min
plus1_alpha0.1: 1/25; modes=2; elapsed=7.3min
plus1_alpha0.1: 2/25; modes=2; elapsed=7.5min
plus1_alpha0.1: 3/25; modes=2; elapsed=7.6min
plus1_alpha0.1: 4/25; modes=2; elapsed=7.7min
plus1_alpha0.1: 5/25; modes=2; elapsed=7.8min
plus1_alpha0.1: 6/25; modes=2; elapsed=7.9min
plus1_alpha0.1: 7/25; modes=2; elapsed=8.0min
plus1_alpha0.1: 8/25; modes=2; elapsed=8.1min
plus1_alpha0.1: 9/25; modes=2; elapsed=8.3min
plus1_alpha0.1: 10/25; modes=2; elapsed=8.4min
plus1_alpha0.1: 11/25; modes=2; elapsed=8.5min
plus1_alpha0.1: 12/25; modes=2; elapsed=8.6min
plus1_alpha0.1: 13/25; modes=2; elapsed=8.7min
plus1_alpha0.1: 14/25; modes=2; elapsed=8.8min
plus1_alpha0.1: 15/25; modes=2; elapsed=8.9min
plus1_alpha0.1: 16/25; modes=2; elapsed=9.1min
plus1_alpha0.1: 17/25; modes=2; elapsed=9.2min
plus1_alpha0.1: 18/25; modes=2; elapsed=9.3min
plus1_alpha0.1: 19/25; modes=2; elapsed=9.4min
plus1_alpha0.1: 20/25; modes=2; elapsed=9.5min
plus1_alpha0.1: 21/25; modes=2; elapsed=9.6min
plus1_alpha0.1: 22/25; modes=2; elapsed=9.7min
plus1_alpha0.1: 23/25; modes=2; elapsed=9.9min
plus1_alpha0.1: 24/25; modes=2; elapsed=10.0min
plus1_alpha0.1: 25/25; modes=2; elapsed=10.1min
minus1_alpha0.1: 1/25; modes=2; elapsed=10.2min
minus1_alpha0.1: 2/25; modes=2; elapsed=10.3min
minus1_alpha0.1: 3/25; modes=2; elapsed=10.4min
minus1_alpha0.1: 4/25; modes=2; elapsed=10.6min
minus1_alpha0.1: 5/25; modes=2; elapsed=10.7min
minus1_alpha0.1: 6/25; modes=2; elapsed=10.8min
minus1_alpha0.1: 7/25; modes=2; elapsed=10.9min
minus1_alpha0.1: 8/25; modes=2; elapsed=11.0min
minus1_alpha0.1: 9/25; modes=2; elapsed=11.1min
minus1_alpha0.1: 10/25; modes=2; elapsed=11.3min
minus1_alpha0.1: 11/25; modes=2; elapsed=11.4min
minus1_alpha0.1: 12/25; modes=2; elapsed=11.5min
minus1_alpha0.1: 13/25; modes=2; elapsed=11.6min
minus1_alpha0.1: 14/25; modes=2; elapsed=11.7min
minus1_alpha0.1: 15/25; modes=2; elapsed=11.8min
minus1_alpha0.1: 16/25; modes=2; elapsed=11.9min
minus1_alpha0.1: 17/25; modes=2; elapsed=12.1min
minus1_alpha0.1: 18/25; modes=2; elapsed=12.2min
minus1_alpha0.1: 19/25; modes=2; elapsed=12.3min
minus1_alpha0.1: 20/25; modes=2; elapsed=12.4min
minus1_alpha0.1: 21/25; modes=2; elapsed=12.5min
minus1_alpha0.1: 22/25; modes=2; elapsed=12.6min
minus1_alpha0.1: 23/25; modes=2; elapsed=12.8min
minus1_alpha0.1: 24/25; modes=2; elapsed=12.9min
minus1_alpha0.1: 25/25; modes=2; elapsed=13.0min
plus1_alpha0.25: 1/25; modes=2; elapsed=13.1min
plus1_alpha0.25: 2/25; modes=2; elapsed=13.2min
plus1_alpha0.25: 3/25; modes=2; elapsed=13.4min
plus1_alpha0.25: 4/25; modes=2; elapsed=13.5min
plus1_alpha0.25: 5/25; modes=2; elapsed=13.6min
plus1_alpha0.25: 6/25; modes=2; elapsed=13.7min
plus1_alpha0.25: 7/25; modes=2; elapsed=13.8min
plus1_alpha0.25: 8/25; modes=2; elapsed=13.9min
plus1_alpha0.25: 9/25; modes=2; elapsed=14.0min
plus1_alpha0.25: 10/25; modes=2; elapsed=14.2min
plus1_alpha0.25: 11/25; modes=2; elapsed=14.3min
plus1_alpha0.25: 12/25; modes=2; elapsed=14.4min
plus1_alpha0.25: 13/25; modes=2; elapsed=14.5min
plus1_alpha0.25: 14/25; modes=2; elapsed=14.6min
plus1_alpha0.25: 15/25; modes=2; elapsed=14.7min
plus1_alpha0.25: 16/25; modes=2; elapsed=14.9min
plus1_alpha0.25: 17/25; modes=2; elapsed=15.0min
plus1_alpha0.25: 18/25; modes=2; elapsed=15.1min
plus1_alpha0.25: 19/25; modes=2; elapsed=15.2min
plus1_alpha0.25: 20/25; modes=2; elapsed=15.3min
plus1_alpha0.25: 21/25; modes=2; elapsed=15.5min
plus1_alpha0.25: 22/25; modes=2; elapsed=15.6min
plus1_alpha0.25: 23/25; modes=2; elapsed=15.7min
plus1_alpha0.25: 24/25; modes=2; elapsed=15.8min
plus1_alpha0.25: 25/25; modes=2; elapsed=15.9min
minus1_alpha0.25: 1/25; modes=2; elapsed=16.0min
minus1_alpha0.25: 2/25; modes=2; elapsed=16.2min
minus1_alpha0.25: 3/25; modes=2; elapsed=16.3min
minus1_alpha0.25: 4/25; modes=2; elapsed=16.4min
minus1_alpha0.25: 5/25; modes=2; elapsed=16.5min
minus1_alpha0.25: 6/25; modes=2; elapsed=16.6min
minus1_alpha0.25: 7/25; modes=2; elapsed=16.7min
minus1_alpha0.25: 8/25; modes=2; elapsed=16.9min
minus1_alpha0.25: 9/25; modes=2; elapsed=17.0min
minus1_alpha0.25: 10/25; modes=2; elapsed=17.1min
minus1_alpha0.25: 11/25; modes=2; elapsed=17.2min
minus1_alpha0.25: 12/25; modes=2; elapsed=17.3min
minus1_alpha0.25: 13/25; modes=2; elapsed=17.4min
minus1_alpha0.25: 14/25; modes=2; elapsed=17.6min
minus1_alpha0.25: 15/25; modes=2; elapsed=17.7min
minus1_alpha0.25: 16/25; modes=2; elapsed=17.8min
minus1_alpha0.25: 17/25; modes=2; elapsed=17.9min
minus1_alpha0.25: 18/25; modes=2; elapsed=18.0min
minus1_alpha0.25: 19/25; modes=2; elapsed=18.1min
minus1_alpha0.25: 20/25; modes=2; elapsed=18.2min
minus1_alpha0.25: 21/25; modes=2; elapsed=18.4min
minus1_alpha0.25: 22/25; modes=2; elapsed=18.5min
minus1_alpha0.25: 23/25; modes=2; elapsed=18.6min
minus1_alpha0.25: 24/25; modes=2; elapsed=18.7min
minus1_alpha0.25: 25/25; modes=2; elapsed=18.8min
plus1_alpha1: 1/25; modes=2; elapsed=18.9min
plus1_alpha1: 2/25; modes=2; elapsed=19.1min
plus1_alpha1: 3/25; modes=2; elapsed=19.2min
plus1_alpha1: 4/25; modes=2; elapsed=19.3min
plus1_alpha1: 5/25; modes=2; elapsed=19.4min
plus1_alpha1: 6/25; modes=2; elapsed=19.5min
plus1_alpha1: 7/25; modes=2; elapsed=19.6min
plus1_alpha1: 8/25; modes=2; elapsed=19.8min
plus1_alpha1: 9/25; modes=2; elapsed=19.9min
plus1_alpha1: 10/25; modes=2; elapsed=20.0min
plus1_alpha1: 11/25; modes=2; elapsed=20.1min
plus1_alpha1: 12/25; modes=2; elapsed=20.2min
plus1_alpha1: 13/25; modes=2; elapsed=20.3min
plus1_alpha1: 14/25; modes=2; elapsed=20.5min
plus1_alpha1: 15/25; modes=2; elapsed=20.6min
plus1_alpha1: 16/25; modes=2; elapsed=20.7min
plus1_alpha1: 17/25; modes=2; elapsed=20.8min
plus1_alpha1: 18/25; modes=2; elapsed=20.9min
plus1_alpha1: 19/25; modes=2; elapsed=21.0min
plus1_alpha1: 20/25; modes=2; elapsed=21.2min
plus1_alpha1: 21/25; modes=2; elapsed=21.3min
plus1_alpha1: 22/25; modes=2; elapsed=21.4min
plus1_alpha1: 23/25; modes=2; elapsed=21.5min
plus1_alpha1: 24/25; modes=2; elapsed=21.6min
plus1_alpha1: 25/25; modes=2; elapsed=21.7min
minus1_alpha1: 1/25; modes=2; elapsed=21.9min
minus1_alpha1: 2/25; modes=2; elapsed=22.0min
minus1_alpha1: 3/25; modes=2; elapsed=22.1min
minus1_alpha1: 4/25; modes=2; elapsed=22.2min
minus1_alpha1: 5/25; modes=2; elapsed=22.3min
minus1_alpha1: 6/25; modes=2; elapsed=22.4min
minus1_alpha1: 7/25; modes=2; elapsed=22.6min
minus1_alpha1: 8/25; modes=2; elapsed=22.7min
minus1_alpha1: 9/25; modes=2; elapsed=22.8min
minus1_alpha1: 10/25; modes=2; elapsed=22.9min
minus1_alpha1: 11/25; modes=2; elapsed=23.0min
minus1_alpha1: 12/25; modes=2; elapsed=23.1min
minus1_alpha1: 13/25; modes=2; elapsed=23.3min
minus1_alpha1: 14/25; modes=2; elapsed=23.4min
minus1_alpha1: 15/25; modes=2; elapsed=23.5min
minus1_alpha1: 16/25; modes=2; elapsed=23.6min
minus1_alpha1: 17/25; modes=2; elapsed=23.7min
minus1_alpha1: 18/25; modes=2; elapsed=23.8min
minus1_alpha1: 19/25; modes=2; elapsed=24.0min
minus1_alpha1: 20/25; modes=2; elapsed=24.1min
minus1_alpha1: 21/25; modes=2; elapsed=24.2min
minus1_alpha1: 22/25; modes=2; elapsed=24.3min
minus1_alpha1: 23/25; modes=2; elapsed=24.4min
minus1_alpha1: 24/25; modes=2; elapsed=24.5min
minus1_alpha1: 25/25; modes=2; elapsed=24.7min
       condition  dx  alpha  nominal_miou_percent  matched_miou_percent  matched_minus_nominal_miou_points  nominal_psnr  matched_psnr  matched_minus_nominal_psnr
 plus1_alpha0.05   1   0.05             68.772347             78.435744                           9.663397     33.998472     38.857996                    4.859523
minus1_alpha0.05  -1   0.05             69.156736             78.445751                           9.289016     34.035714     38.851799                    4.816086
  plus1_alpha0.1   1   0.10             56.989315             78.040719                          21.051404     30.814781     38.480462                    7.665681
 minus1_alpha0.1  -1   0.10             57.975741             78.062349                          20.086608     30.851640     38.410596                    7.558956
 plus1_alpha0.25   1   0.25             31.223435             70.998186                          39.774751     25.694804     -5.109314                  -30.804118
minus1_alpha0.25  -1   0.25             32.167946             70.331652                          38.163707     25.743426     -5.086849                  -30.830274
    plus1_alpha1   1   1.00              1.574307             78.308001                          76.733694     10.009459     38.985379                   28.975920
   minus1_alpha1  -1   1.00              1.848736             78.207776                          76.359041     10.341741     38.889867                   28.548125
Download this ZIP even if an error occurred: operator_control_epoch441_20261010_183309_608911.zip

/kaggle/working/operator_control_epoch441_20261010_183309_608911.zip

In [20]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed','Partial run: share the ZIP and error.'
assert len(manifest['completed_conditions'])==9
assert json.loads((RUN/'results/clean_equivalence.json').read_text())['passed']
display(pd.read_csv(RUN/'results/paired_final_summary.csv'))
display(pd.read_csv(RUN/'results/mask_severity.csv'))
print('Completed. Download the operator_control_epoch441 ZIP and share its local path. No new model was trained.')

,condition,dx,alpha,nominal_miou_percent,matched_miou_percent,matched_minus_nominal_miou_points,nominal_psnr,matched_psnr,matched_minus_nominal_psnr
0,plus1_alpha0.05,1,0.05,68.772347,78.435744,9.663397,33.998472,38.857996,4.859523
1,minus1_alpha0.05,-1,0.05,69.156736,78.445751,9.289016,34.035714,38.851799,4.816086
2,plus1_alpha0.1,1,0.10,56.989315,78.040719,21.051404,30.814781,38.480462,7.665681
3,minus1_alpha0.1,-1,0.10,57.975741,78.062349,20.086608,30.851640,38.410596,7.558956
4,plus1_alpha0.25,1,0.25,31.223435,70.998186,39.774751,25.694804,-5.109314,-30.804118
5,minus1_alpha0.25,-1,0.25,32.167946,70.331652,38.163707,25.743426,-5.086849,-30.830274
6,plus1_alpha1,1,1.00,1.574307,78.308001,76.733694,10.009459,38.985379,28.975920
7,minus1_alpha1,-1,1.00,1.848736,78.207776,76.359041,10.341741,38.889867,28.548125

,condition,dx,alpha,mask_relative_error,changed_fraction,mean_transmittance
0,clean,0,0.00,0.000000,0.000000,0.500740
1,plus1_alpha0.05,1,0.05,0.049937,0.499485,0.500691
2,minus1_alpha0.05,-1,0.05,0.049935,0.499435,0.500689
3,plus1_alpha0.1,1,0.10,0.099875,0.499485,0.500643
4,minus1_alpha0.1,-1,0.10,0.099870,0.499435,0.500638
5,plus1_alpha0.25,1,0.25,0.249687,0.499485,0.500497
6,minus1_alpha0.25,-1,0.25,0.249674,0.499435,0.500484
7,plus1_alpha1,1,1.00,0.998746,0.499485,0.499767
8,minus1_alpha1,-1,1.00,0.998697,0.499435,0.499718

Completed. Download the operator_control_epoch441 ZIP and share its local path. No new model was trained.