In [ ]:
from pathlib import Path
import shutil
import zipfile
import os

inputs = Path("/kaggle/input")
destination = Path("/kaggle/working/BTP")

matches = list(inputs.rglob("run_public252.py"))

if matches:
    source = matches[0].parent
    shutil.copytree(source, destination, dirs_exist_ok=True)
else:
    archives = list(inputs.rglob("*.zip"))
    code_found = False

    for archive in archives:
        with zipfile.ZipFile(archive) as z:
            if "BTP/run_public252.py" in z.namelist():
                # Extract only our code archive.
                target = Path("/kaggle/working").resolve()
                for name in z.namelist():
                    if not (target / name).resolve().is_relative_to(target):
                        raise ValueError("Unsafe archive path")
                z.extractall(target)
                code_found = True
                break

    if not code_found:
        print("Attached input folders:", list(inputs.iterdir()))
        print("ZIP files found:", archives)
        raise RuntimeError(
            "BTP code is not attached. Add the dataset containing BTP-code.zip."
        )

assert (destination / "run_public252.py").is_file()
os.chdir(destination)
print("Code ready:", os.getcwd())

In [ ]:
import importlib
from pathlib import Path

for name in [
    "torch", "torchvision", "numpy", "pandas",
    "scipy", "skimage", "PIL", "einops", "torchmetrics", "tqdm"
]:
    try:
        module = importlib.import_module(name)
        print(f"{name}: OK ({getattr(module, '__version__', 'unknown')})")
    except Exception as error:
        print(f"{name}: FAILED — {error}")

import torch
print("\nCUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print("VRAM:", round(
        torch.cuda.get_device_properties(0).total_memory / 1024**3, 1
    ), "GB")

roots = [
    p.parent
    for p in Path("/kaggle/input").rglob("train_data.csv")
    if (p.parent / "visible_28").is_dir()
    and (p.parent / "labels").is_dir()
]

print("\nPrepared dataset folders:", roots)

In [ ]:
from pathlib import Path
import subprocess
import sys

DATA_ROOT = Path("/kaggle/input/datasets/arnavnigamd/btp-data/public252")

def run(script, *args):
    subprocess.run(
        [sys.executable, script, *map(str, args)],
        cwd="/kaggle/working/BTP",
        check=True,
    )

run("verify_evaluation.py")
run("run_public252.py", "--root", DATA_ROOT)
run("verify_portability.py", "--root", DATA_ROOT)
run("verify_public252_pipeline.py", "--root", DATA_ROOT)

In [ ]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

In [ ]:
import subprocess
import sys
from datetime import datetime

DATA_ROOT = "/kaggle/input/datasets/arnavnigamd/btp-data/public252"
OUT = "/kaggle/working/gpu_smoke_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "gpu_smoke.py",
        "--root", DATA_ROOT,
        "--out", OUT,
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

In [ ]:
import subprocess
import sys
from datetime import datetime

OUT = "/kaggle/working/fixed_crop_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "diagnostic_public252.py",
        "--root", "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--out", OUT,
        "--transpose-image",
        "--steps", "200",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Diagnostic results:", OUT)

In [ ]:
from IPython.display import display, Image

display(Image(
    filename="/kaggle/working/fixed_crop_20260917_144904/predictions.png"
))

In [ ]:
import subprocess
import sys
from datetime import datetime

OUT = "/kaggle/working/fixed_crop_1000_" + datetime.now().strftime("%Y%m%d_%H%M%S")

subprocess.run(
    [
        sys.executable, "diagnostic_public252.py",
        "--root", "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--out", OUT,
        "--transpose-image",
        "--steps", "1000",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Results:", OUT)

In [ ]:
from pathlib import Path
from IPython.display import display, Image
import json

run_dir = Path("/kaggle/working/fixed_crop_1000_20260917_145850")

metrics = json.loads((run_dir / "metrics.json").read_text())
print("Final step:", metrics[-1]["step"])
print("Final mIoU:", metrics[-1]["foreground_miou_present"])

display(Image(filename=str(run_dir / "predictions.png")))

In [ ]:
from pathlib import Path
import shutil
from IPython.display import FileLink, display

run_dir = Path("/kaggle/working/fixed_crop_1000_20260917_145850")
assert run_dir.is_dir(), "Run folder not found"

archive = shutil.make_archive(
    "/kaggle/working/fixed_crop_1000_backup",
    "zip",
    root_dir=run_dir.parent,
    base_dir=run_dir.name,
)

display(FileLink(archive))

##version 2

In [ ]:
from pathlib import Path
import shutil, zipfile, os

inputs = Path('/kaggle/input')
working = Path('/kaggle/working')

def safe_extract(archive, target):
    target.mkdir(parents=True, exist_ok=False)
    with zipfile.ZipFile(archive) as z:
        for name in z.namelist():
            if not (target / name).resolve().is_relative_to(target.resolve()):
                raise ValueError('Unsafe ZIP member')
        z.extractall(target)

code = list(inputs.rglob('compare_diagnostic_lr.py'))
if not code:
    for archive in inputs.rglob('*.zip'):
        with zipfile.ZipFile(archive) as z:
            is_code = 'BTP/compare_diagnostic_lr.py' in z.namelist()
        if is_code:
            target = working / 'lr_code_unpacked'
            safe_extract(archive, target)
            code.extend(target.rglob('compare_diagnostic_lr.py'))
assert len(code) == 1, f'Expected one updated code input: {code}'
shutil.copytree(code[0].parent, working/'BTP', dirs_exist_ok=True)
os.chdir(working/'BTP')

run_name = 'fixed_crop_1000_20260917_145850'
runs = [p.parent for p in inputs.rglob('diagnostic_checkpoint.pt')
        if p.parent.name == run_name]
if not runs:
    for archive in inputs.rglob('*.zip'):
        with zipfile.ZipFile(archive) as z:
            is_run = f'{run_name}/diagnostic_checkpoint.pt' in z.namelist()
        if is_run:
            target = working / 'reference_unpacked'
            safe_extract(archive, target)
            runs.append(target/run_name)
assert len(runs) == 1, f'Expected one saved 1,000-step run: {runs}'
REFERENCE_RUN = runs[0]
DATA_ROOT = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert (DATA_ROOT/'train_data.csv').is_file()
print('Code ready; reference:', REFERENCE_RUN)

In [ ]:
import subprocess
import sys
import torch
from pathlib import Path
from datetime import datetime

assert torch.cuda.is_available(), "Enable GPU T4 ×2 first"

DATA_ROOT = Path("/kaggle/input/datasets/arnavnigamd/btp-data/public252")
REFERENCE_RUN = Path(
    "/kaggle/input/datasets/arnavnigamd/checkpoint1/"
    "fixed_crop_1000_20260917_145850"
)
OUT = Path(
    "/kaggle/working/lr_comparison_"
    + datetime.now().strftime("%Y%m%d_%H%M%S")
)

subprocess.run(
    [sys.executable, "verify_diagnostic_comparison.py"],
    cwd="/kaggle/working/BTP",
    check=True,
)

subprocess.run(
    [
        sys.executable, "compare_diagnostic_lr.py",
        "--root", str(DATA_ROOT),
        "--from-run", str(REFERENCE_RUN),
        "--out", str(OUT),
        "--steps", "500",
        "--eval-every", "10",
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

print("Results:", OUT)
print((OUT / "comparison_summary.json").read_text())

In [ ]:
import subprocess
import sys
from datetime import datetime

checkpoint = (
    "/kaggle/working/lr_comparison_20260917_160952/"
    "control_4e-4/diagnostic_checkpoint.pt"
)

subprocess.run(
    [
        sys.executable, "test.py",
        "--data_root",
        "/kaggle/input/datasets/arnavnigamd/btp-data/public252",
        "--transpose_image",
        "--eval_split", "val",
        "--limit", "1",
        "--pretrained_model_path", checkpoint,
        "--outf", "/kaggle/working/evaluations",
        "--name", "full_frame_smoke_" + datetime.now().strftime("%H%M%S"),
    ],
    cwd="/kaggle/working/BTP",
    check=True,
)

In [ ]:
from pathlib import Path
from IPython.display import display, Image

comparison = Path("/kaggle/working/lr_comparison_20260917_160952")

for arm in ["control_4e-4", "low_4e-5"]:
    path = comparison / arm / "best_predictions.png"
    print(arm)
    if path.is_file():
        display(Image(filename=str(path)))
    else:
        print("Restore the saved comparison folder and update its path.")

In [ ]:
from pathlib import Path

for root in [Path("/kaggle/input"), Path("/kaggle/working")]:
    print(f"\nSearching {root}")
    for pattern in ["best_predictions.png", "comparison_summary.json", "*.zip"]:
        for path in root.rglob(pattern):
            print(path)

In [ ]:
from pathlib import Path
import shutil
import zipfile

inputs = Path("/kaggle/input")
target = Path("/kaggle/working/BTP")

# Find an already-extracted copy of the updated code.
sources = [
    p.parent for p in inputs.rglob("run_public252.py")
    if "--stop-after-epoch" in p.read_text()
]

if sources:
    shutil.copytree(sources[0], target, dirs_exist_ok=True)
else:
    candidates = []
    for archive in inputs.rglob("*.zip"):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            name = "BTP/run_public252.py"
            if name in z.namelist():
                if b"--stop-after-epoch" in z.read(name):
                    candidates.append(archive)

    if not candidates:
        raise FileNotFoundError(
            "Attach BTP-code-pilot.zip through Add Input, then rerun this cell."
        )

    with zipfile.ZipFile(candidates[0]) as z:
        destination = Path("/kaggle/working").resolve()
        for member in z.infolist():
            resolved = (destination / member.filename).resolve()
            if not resolved.is_relative_to(destination):
                raise ValueError("Unsafe archive path")
        z.extractall(destination)

assert (target / "run_public252.py").is_file()
assert "--stop-after-epoch" in (target / "run_public252.py").read_text()
print("Updated pilot code ready:", target)

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_pilot_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '3', '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-3 model folder.
import zipfile
expected = 'baseline_pilot_20260917_190720'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-3 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_to_epoch10_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '10', '--resume', str(REFERENCE), '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-10 model folder.
import zipfile
expected = 'baseline_to_epoch10_20260917_195856'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-10 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

from datetime import datetime
import shutil, zipfile
from IPython.display import display, FileLink
NAME = 'baseline_to_epoch50_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUTPUT = Path('/kaggle/working/baseline_runs')
RUN = OUTPUT / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_public252.py', '--root', str(DATA),
        '--train', '--epochs', '500', '--stop-after-epoch', '50', '--resume', str(REFERENCE), '--batch-size', '1',
        '--workers', '0', '--output', str(OUTPUT), '--name', NAME], cwd=CODE, check=True)
finally:
    if RUN.exists():
        archive = shutil.make_archive(str(Path('/kaggle/working') / NAME), 'zip', root_dir=OUTPUT, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None, 'Archive integrity check failed'
            required = [NAME + '/model/' + f for f in ['last.pt', 'best_iou.pth', 'best_psnr.pth']]
            missing = [f for f in required if f not in z.namelist()]
        print('Archive:', archive, 'bytes:', Path(archive).stat().st_size)
        print('Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download this archive before stopping the session. If checkpoint files are missing, report the training error.')

In [ ]:
import json
for path in sorted((RUN / 'result').glob('*_training.json')):
    print(json.dumps(json.loads(path.read_text()), indent=2))
print('Download the complete archive, then share these metrics and the per-class segmentation CSVs.')

In [ ]:
from pathlib import Path
import shutil
import zipfile

inputs = Path("/kaggle/input")
destination = Path("/kaggle/working").resolve()
code = destination / "BTP"

sources = [
    p.parent for p in inputs.rglob("run_public252.py")
    if "--stop-after-epoch" in p.read_text()
]

if sources:
    shutil.copytree(sources[0], code, dirs_exist_ok=True)
else:
    found = False
    for archive in inputs.rglob("*.zip"):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            entry = "BTP/run_public252.py"
            if entry not in z.namelist():
                continue
            if b"--stop-after-epoch" not in z.read(entry):
                continue
            for member in z.infolist():
                if not (destination / member.filename).resolve().is_relative_to(destination):
                    raise ValueError("Unsafe archive path")
            z.extractall(destination)
            found = True
            break

    assert found, "Attach BTP-code-pilot.zip through Add Input, then rerun."

assert (code / "test.py").is_file()
print("Code ready:", code)

In [ ]:
from pathlib import Path
import subprocess, sys, torch
CODE = Path('/kaggle/working/BTP')
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert CODE.joinpath('run_public252.py').is_file(), 'Extract the updated BTP-code-pilot.zip first.'
assert '--stop-after-epoch' in CODE.joinpath('run_public252.py').read_text(), 'Use the updated pilot code ZIP.'
assert torch.cuda.is_available(), 'Enable the GPU before starting.'
print(torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA), '--epochs', '500', '--stop-after-epoch', '3'], cwd=CODE, check=True)

In [ ]:
# Locate the complete saved epoch-50 model folder.
import zipfile
expected = 'baseline_to_epoch50_20260917_204827'
refs = list(Path('/kaggle/input').rglob(expected + '/model/last.pt'))
if not refs:
    for archive in Path('/kaggle/input').rglob('*.zip'):
        if not zipfile.is_zipfile(archive):
            continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' not in z.namelist():
                continue
            dest = Path('/kaggle/working/restored_pilot').resolve()
            for member in z.infolist():
                if not (dest / member.filename).resolve().is_relative_to(dest):
                    raise ValueError('Unsafe archive path')
            z.extractall(dest)
            refs = [dest / expected / 'model/last.pt']
            break
assert len(refs) == 1, f'Attach exactly one saved epoch-50 pilot. Found: {refs}'
REFERENCE = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert REFERENCE.with_name(name).is_file(), f'Missing {name}'
print('Resume checkpoint:', REFERENCE)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import shutil
OUT = Path('/kaggle/working') / ('checkpoint_audit_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
OUT.mkdir()
try:
    for name, weights in [('best_iou_a', 'best_iou.pth'), ('best_iou_b', 'best_iou.pth'), ('last_epoch50', 'last.pt')]:
        subprocess.run([sys.executable, '-u', 'test.py', '--data_root', str(DATA),
            '--transpose_image', '--eval_split', 'val', '--pretrained_model_path', str(REFERENCE.with_name(weights)),
            '--outf', str(OUT), '--name', name], cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
    display(FileLink(archive))
    print('Download this evaluation archive for comparison:', archive)

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-paired')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
if not CODE.exists():
    sources = list(INPUTS.rglob('paired_full_training.py'))
    if len(sources) == 1:
        shutil.copytree(sources[0].parent, CODE)
    else:
        found = []
        for archive in INPUTS.rglob('*.zip'):
            if zipfile.is_zipfile(archive):
                with zipfile.ZipFile(archive) as z:
                    if 'BTP/paired_full_training.py' in z.namelist(): found.append(archive)
        assert len(found) == 1, 'Attach exactly one BTP-code-paired-full.zip input.'
        staging = Path('/kaggle/working/paired_code_extract')
        staging.mkdir(exist_ok=False)
        with zipfile.ZipFile(found[0]) as z: safe_extract(z, staging)
        shutil.copytree(staging / 'BTP', CODE)
assert (CODE / 'paired_full_training.py').is_file()
expected = 'baseline_to_epoch50_20260917_204827'
refs = list(INPUTS.rglob(expected + '/model/last.pt'))
if not refs:
    for archive in INPUTS.rglob('*.zip'):
        if not zipfile.is_zipfile(archive): continue
        with zipfile.ZipFile(archive) as z:
            if expected + '/model/last.pt' in z.namelist():
                dest = Path('/kaggle/working/paired_reference')
                safe_extract(z, dest)
                refs = [dest / expected / 'model/last.pt']
                break
assert len(refs) == 1, 'Attach the complete epoch50 run ZIP or extracted folder.'
REFERENCE = refs[0].parent.parent
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
import torch
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Code:', CODE, 'Reference:', REFERENCE, 'GPU:', torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'verify_paired_full_training.py'], cwd=CODE, check=True)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
OUT = Path('/kaggle/working') / ('paired_full_lr_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
try:
    subprocess.run([sys.executable, '-u', 'paired_full_training.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{OUT.name}/{arm}/model/{name}' for arm in ['control','quarter_lr']
                for name in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{OUT.name}/{arm}/model/{name}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        display(FileLink(archive))
        print('Download the complete ZIP before closing the session. Check logs for successful epoch60 completion in BOTH arms.')

In [ ]:
import json
summary = json.loads((OUT / 'comparison_summary.json').read_text())
for arm, result in summary['arms'].items():
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))
assert set(summary['arms']) == {'control', 'quarter_lr'}, 'Comparison is incomplete.'

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-paired')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
if not CODE.exists():
    sources = list(INPUTS.rglob('paired_full_training.py'))
    if len(sources) == 1:
        shutil.copytree(sources[0].parent, CODE)
    else:
        found = []
        for archive in INPUTS.rglob('*.zip'):
            if zipfile.is_zipfile(archive):
                with zipfile.ZipFile(archive) as z:
                    if 'BTP/paired_full_training.py' in z.namelist(): found.append(archive)
        assert len(found) == 1, 'Attach exactly one BTP-code-paired-full.zip input.'
        staging = Path('/kaggle/working/paired_code_extract')
        staging.mkdir(exist_ok=False)
        with zipfile.ZipFile(found[0]) as z: safe_extract(z, staging)
        shutil.copytree(staging / 'BTP', CODE)
assert (CODE / 'paired_full_training.py').is_file()
import json, hashlib, math
import torch
expected = 'paired_full_lr_20260918_065140'
relative = expected + '/quarter_lr/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach paired_full_lr_20260918_065140.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 60
expected_config = dict(learning_rate=0.0001, max_epoch=500, batch_size=1,
                       workers=0, seed=3407, transpose_image=True,
                       method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Unexpected checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 60
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Resuming quarter-rate checkpoint:', CHECKPOINT)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Saved best metrics:', state['best'])
del state
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU before training.'
print('GPU:', torch.cuda.get_device_name(0))
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above; the next cell resumes the quarter schedule, not the printed default schedule.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'quarter_lr_to_epoch100_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
shutil.copy2(CODE / 'public252-v1.json', OUT / 'dataset_protocol.json')
provenance = {
    'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
    'source_epoch': 60, 'stop_after_epoch': 100, 'arm': 'quarter_lr',
    'note': 'Restore saved Adam/scaler/RNG and quarter-scaled500-epoch scheduler without rescaling again.',
    'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
                      for f in ['train.py', 'opt.py', 'training_state.py', 'dataset.py']}
}
(OUT / 'continuation.json').write_text(json.dumps(provenance, indent=2))
command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
    '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
    '--learning_rate', '0.0001', '--max_epoch', '500', '--stop_after_epoch', '100',
    '--resume', str(CHECKPOINT), '--outf', str(OUT.parent) + '/', '--name', NAME]
try:
    subprocess.run(command, cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=OUT.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{NAME}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
                   if f'{NAME}/model/{f}' not in z.namelist()]
    print('Archive:', archive, 'Missing checkpoint files:', missing)
    if (OUT / 'model/last.pt').is_file():
        saved = torch.load(OUT / 'model/last.pt', map_location='cpu', weights_only=True)
        print('Saved epoch:', saved['epoch'], 'Best metrics:', saved['best'])
        del saved
    display(FileLink(archive))
    print('Download the complete archive before stopping the session. Check saved epoch is100; a partial run also creates an archive.')

In [ ]:
records = [json.loads(p.read_text()) for p in sorted((OUT / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(61,101)), 'Training did not finish all40 epochs.'
print('Final epoch:', json.dumps(records[-1], indent=2))
print('Best mIoU among new epochs:', max(records, key=lambda r: r['val_foreground_miou_all22']))
print('AMP skips in new epochs:', sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import os
import shutil
import zipfile
from IPython.display import display, FileLink

working = Path("/kaggle/working")
runs = [
    p for p in working.glob("quarter_lr_to_epoch100_*")
    if p.is_dir() and (p / "model/last.pt").is_file()
]
assert runs, "No saved run found. Keep this session open and share the output."

run = max(runs, key=lambda p: (p / "model/last.pt").stat().st_mtime)
archive = run.with_suffix(".zip")

# Recreate the archive from the saved run.
shutil.make_archive(
    str(run), "zip", root_dir=run.parent, base_dir=run.name
)

with zipfile.ZipFile(archive) as z:
    assert z.testzip() is None, "Archive integrity check failed"

print("ZIP:", archive)
print(f"Size: {archive.stat().st_size / 1024**2:.1f} MiB")

os.chdir(working)
display(FileLink(archive.name))

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-weak-audit')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = "parser.add_argument('--save_segmentation'"
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'test.py'):
    sources = [p.parent for p in INPUTS.rglob('test.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/test.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-weak-audit.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'test.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
CHECKPOINT = CHECKPOINT.with_name('best_iou.pth')
assert '--save_segmentation' in (CODE / 'test.py').read_text(), 'Attach the updated BTP-code-weak-audit.zip.'
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Evaluating saved best segmentation checkpoint:', CHECKPOINT)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'weak_class_audit_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
try:
    subprocess.run([sys.executable, '-u', 'test.py', '--data_root', str(DATA),
        '--transpose_image', '--eval_split', 'val', '--save_segmentation',
        '--pretrained_model_path', str(CHECKPOINT), '--outf', str(OUT), '--name', 'best_epoch96'], cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    import os
    os.chdir('/kaggle/working')
    print('Download:', archive)
    display(FileLink(Path(archive).name))

In [ ]:
import numpy as np
import sys
sys.path.insert(0,str(CODE))
from dataset import get_class_names
folder = OUT / 'best_epoch96/evaluation_val'
meta = json.loads((folder / 'evaluation.json').read_text())
assert meta['status']=='completed' and meta['scene_count']==25
hist = np.load(folder / 'confusion_matrix.npy')
classes = get_class_names()
for k in [9,12,17,22]:
    total = hist[k].sum()
    print(classes[k], 'ground-truth pixels:', int(total))
    print([(classes[j], round(100*hist[k,j]/total,2)) for j in np.argsort(hist[k])[::-1][:5]])
print('Share the downloaded ZIP; it contains all25 previews and per-scene confusion matrices, without reconstructed HSI cubes.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-training-diagnostic')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Training-only inference diagnostic; fixed class-rich crops'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'diagnose_training_classes.py'):
    sources = [p.parent for p in INPUTS.rglob('diagnose_training_classes.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/diagnose_training_classes.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-training-diagnostic.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'diagnose_training_classes.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
CHECKPOINT = CHECKPOINT.with_name('best_iou.pth')
assert (CODE / 'diagnose_training_classes.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Evaluating saved best segmentation checkpoint:', CHECKPOINT)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'training_class_diagnostic_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'diagnose_training_classes.py', '--root', str(DATA),
        '--checkpoint', str(CHECKPOINT), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z: assert z.testzip() is None
        import os
        os.chdir('/kaggle/working')
        print('Download:', archive)
        display(FileLink(Path(archive).name))

In [ ]:
record = json.loads((OUT / 'diagnostic.json').read_text())
assert record.get('status') == 'completed', 'Diagnostic did not finish.'
for row in json.loads((OUT / 'summary.json').read_text()):
    print(row['class_id'],row['scene'],row['mode'],
          'IoU:',round(100*row['target_iou'],2),'recall:',round(100*row['target_recall'],2))
print('These are selected TRAINING-scene diagnostics, not validation or test scores.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-loss-pair')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Matched epoch101-110 segmentation-loss experiment'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'paired_loss_weight.py'):
    sources = [p.parent for p in INPUTS.rglob('paired_loss_weight.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/paired_loss_weight.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-loss-pair.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'paired_loss_weight.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'paired_loss_weight.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Epoch100 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_loss_pair.py'],cwd=CODE,check=True)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'paired_loss_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'paired_loss_weight.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{NAME}/{arm}/model/{file}' for arm in ['control_seg1e-4','higher_seg1e-3']
                for file in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{NAME}/{arm}/model/{file}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        import os
        os.chdir('/kaggle/working')
        display(FileLink(Path(archive).name))
        print('Download before ending the session. Confirm BOTH arms reached epoch110.')

In [ ]:
summary = json.loads((OUT / 'comparison_summary.json').read_text())
assert set(summary['arms']) == {'control_seg1e-4','higher_seg1e-3'}, 'Incomplete comparison'
for arm, result in summary['arms'].items():
    assert result['final']['epoch'] == 110
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))

/////////////////////////////////////////

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'quarter_lr_to_epoch100_20260918_094320'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach quarter_lr_to_epoch100_20260918_094320.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Epoch100 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'balanced_sampling_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
try:
    subprocess.run([sys.executable, '-u', 'run_sampling_experiment.py', '--root', str(DATA),
        '--reference', str(REFERENCE), '--out', str(OUT)], cwd=CODE, check=True)
finally:
    if OUT.exists():
        archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
        with zipfile.ZipFile(archive) as z:
            assert z.testzip() is None
            missing = [f'{NAME}/balanced50/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
                if f'{NAME}/balanced50/model/{f}' not in z.namelist()]
        print('Archive:', archive, 'Missing checkpoint files:', missing)
        import os
        os.chdir('/kaggle/working')
        display(FileLink(Path(archive).name))
        print('Download the complete ZIP before ending the session.')

In [ ]:
summary = json.loads((OUT / 'comparison_summary.json').read_text())
assert summary['arms']['balanced50']['final']['epoch']==110
for arm, result in summary['arms'].items():
    print(arm, json.dumps({k:v for k,v in result.items() if k != 'epochs'}, indent=2))
print('Historical control is reused from the completed loss experiment; only balanced50 was newly trained.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_sampling_20260922_131859'
relative = expected + '/balanced50/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_quarter60')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_sampling_20260922_131859.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch110 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 110
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 110
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
NAME = 'balanced_to_epoch130_' + datetime.now().strftime('%Y%m%d_%H%M%S')
OUT = Path('/kaggle/working') / NAME
OUT.mkdir(exist_ok=False)
shutil.copy2(CODE / 'public252-v1.json', OUT / 'dataset_protocol.json')
manifest = {
    'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
    'source_epoch': 110, 'stop_after_epoch': 130, 'sampling_policy': 'balanced50_v1',
    'note': 'Exact full-state continuation settings: lambda_seg1e-4; saved quarter-rate cosine schedule restored without additional scaling.',
    'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
        for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
}
(OUT / 'continuation.json').write_text(json.dumps(manifest, indent=2))
command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
    '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
    '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
    '--max_epoch', '500', '--stop_after_epoch', '130', '--resume', str(CHECKPOINT),
    '--outf', str(OUT.parent) + '/', '--name', NAME]
try:
    subprocess.run(command, cwd=CODE, check=True)
finally:
    archive = shutil.make_archive(str(OUT), 'zip', root_dir=OUT.parent, base_dir=NAME)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{NAME}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{NAME}/model/{f}' not in z.namelist()]
    print('Archive:', archive, 'Missing checkpoint files:', missing)
    if (OUT / 'model/last.pt').is_file():
        saved = torch.load(OUT / 'model/last.pt', map_location='cpu', weights_only=True)
        print('Saved epoch:', saved['epoch'], 'Best metrics:', saved['best'])
        del saved
    import os
    os.chdir('/kaggle/working')
    display(FileLink(Path(archive).name))
    print('Download the complete ZIP before ending the session. A partial run can also produce an archive.')

In [ ]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((OUT / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(111,131)), 'Not all20 epochs completed.'
print('Final:', json.dumps(records[-1], indent=2))
for start in [111,121]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] < start+10]
    print(f'Epochs{start}-{start+9}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('New optimizer updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_to_epoch130_20260922_143402'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced130')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_to_epoch130_20260922_143402.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch130 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 130
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 130
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch130 run.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT_RUN' not in globals():
    CONT_RUN = Path('/kaggle/working') / ('balanced_to_epoch200_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 130, 'target_epoch': 200, 'backup_epochs': [150,175,200],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Three subprocess blocks with epoch-boundary RNG restoration.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT_RUN.parent / (CONT_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT_RUN.parent, base_dir=CONT_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target in [150,175,200]
    last = CONT_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT_RUN.parent) + '/', '--name', CONT_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Block completed. Download the backup, then run the next block when ready.')
print('Continuation folder:', CONT_RUN)

In [ ]:
continue_to(150)

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced_to_epoch200_20260922_164019'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced150')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced_to_epoch200_20260922_164019_epoch150.zip or its extracted folder.'
CHECKPOINT = refs[0]
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch150 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 150
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 150
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch150 run.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT150_RUN' not in globals():
    CONT150_RUN = Path('/kaggle/working') / ('balanced150_to_epoch200_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT150_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT150_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 150, 'target_epoch': 200, 'backup_epochs': [200],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Single subprocess continuation from150 through200.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT150_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT150_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT150_RUN.parent / (CONT150_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT150_RUN.parent, base_dir=CONT150_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT150_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT150_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target == 200
    last = CONT150_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT150_RUN.parent) + '/', '--name', CONT150_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT150_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT150_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Epoch200 completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT150_RUN)

In [ ]:
continue_to(200)

In [ ]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((CONT150_RUN / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(151,201)), 'Not all50 new epochs completed.'
for start,end in [(151,175),(176,200)]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] <= end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:', json.dumps(records[-1], indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='5ad004708dd6ce388708ad3627cf8206b184804b6202754204f7296bfc253c7b'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced150_to_epoch200_20260923_102523/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch188_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced150_to_epoch200_20260923_102523_epoch200.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch188 weights:',CHECKPOINT)

In [ ]:
NAME='epoch188_validation_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f')
RUN=WORK/NAME
subprocess.run([sys.executable,'test.py','--data_root',str(DATA),
    '--transpose_image','--eval_split','val','--pretrained_model_path',str(CHECKPOINT),
    '--outf',str(WORK),'--name',NAME,'--workers','0','--save_segmentation'],
    cwd=CODE,check=True)
OUT=RUN/'evaluation_val'
print('Evaluation complete:',OUT)

In [ ]:
EXPECTED_MIOU=0.7511010246306207
EXPECTED_PSNR=37.20344635009766

import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['split']=='val' and meta['scene_count']==25
assert meta['checkpoint_sha256']==EXPECTED
assert len(set(meta['scenes']))==25
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(scene+'_confusion.npy')) for scene in meta['scenes']]
assert np.array_equal(sum(parts),cm), 'Per-scene confusion totals differ.'
assert len(list(OUT.glob('*_preview.png')))==25
assert not list(OUT.glob('*_hsi.npy'))
seg=pd.read_csv(OUT/'segmentation.csv',index_col=0)
rec=pd.read_csv(OUT/'reconstruction.csv')
miou=float(seg.loc['total(-bg)','IoU'])
psnr=float(rec.iloc[0]['PSNR'])
summary=dict(checkpoint_epoch=188,validation_scenes=25,foreground_miou=miou,
    psnr_ref1=psnr,logged_miou=EXPECTED_MIOU,logged_psnr=EXPECTED_PSNR,
    miou_difference=miou-EXPECTED_MIOU,psnr_difference=psnr-EXPECTED_PSNR,
    matches_logged_metrics=bool(abs(miou-EXPECTED_MIOU)<1e-5 and abs(psnr-EXPECTED_PSNR)<1e-3),
    scope='Independent full validation evaluation; no test performance or new training.')
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'evaluator_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in
    ['test.py','dataset.py','utils.py','public252-v1.json']},indent=2))
print(json.dumps(summary,indent=2))
display(seg)
display(rec)
# Save results even if the comparison differs, so the difference can be investigated.
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir(WORK)
print('Download this archive before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))
if not summary['matches_logged_metrics']:
    print('Metrics differ from the training record: share this ZIP before further training.')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced150_to_epoch200_20260923_102523'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced200')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced150_to_epoch200_20260923_102523_epoch200.zip or its extracted folder.'
CHECKPOINT = refs[0]
assert hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest() == 'e0c7e178b9c90178cc08d71136d3f5316ab985159b9ab1254bf26c5cf0325e9a', 'Wrong epoch200 checkpoint.'
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch200 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 200
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 200
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch200 run.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT200_RUN' not in globals():
    CONT200_RUN = Path('/kaggle/working') / ('balanced200_to_epoch250_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT200_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT200_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 200, 'target_epoch': 250, 'backup_epochs': [250],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Single subprocess continuation from200 through250.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT200_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT200_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT200_RUN.parent / (CONT200_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT200_RUN.parent, base_dir=CONT200_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT200_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT200_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target == 250
    last = CONT200_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT200_RUN.parent) + '/', '--name', CONT200_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT200_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT200_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Epoch250 completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT200_RUN)

In [ ]:
continue_to(250)

In [ ]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((CONT200_RUN / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(201,251)), 'Not all50 new epochs completed.'
for start,end in [(201,225),(226,250)]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] <= end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:', json.dumps(records[-1], indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced200_to_epoch250_20260923_155019'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced250')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced200_to_epoch250_20260923_155019_epoch250.zip or its extracted folder.'
CHECKPOINT = refs[0]
assert hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest() == '2ae6932257f8145195e62f2152ef43c14a61cec1de4e15d8c71b4e1aff8b1253', 'Wrong epoch250 checkpoint.'
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch250 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 250
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 250
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch250 run.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT250_RUN' not in globals():
    CONT250_RUN = Path('/kaggle/working') / ('balanced250_to_epoch300_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT250_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT250_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 250, 'target_epoch': 300, 'backup_epochs': [300],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Single subprocess continuation from250 through300.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT250_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT250_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT250_RUN.parent / (CONT250_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT250_RUN.parent, base_dir=CONT250_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT250_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT250_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target == 300
    last = CONT250_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT250_RUN.parent) + '/', '--name', CONT250_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT250_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT250_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print('Epoch300 completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT250_RUN)

In [ ]:
continue_to(300)

In [ ]:
import statistics
records = [json.loads(p.read_text()) for p in sorted((CONT250_RUN / 'result').glob('*_training.json'))]
assert [r['epoch'] for r in records] == list(range(251,301)), 'Not all50 new epochs completed.'
for start,end in [(251,275),(276,300)]:
    values = [100*r['val_foreground_miou_all22'] for r in records if start <= r['epoch'] <= end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:', json.dumps(records[-1], indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch
expected = 'balanced250_to_epoch300_20260924_074129'
relative = expected + '/model/last.pt'
refs = list(INPUTS.rglob(relative))
if not refs:
    working = Path('/kaggle/working') / relative
    if working.is_file(): refs = [working]
if not refs:
    dest = Path('/kaggle/working/restored_balanced300')
    restored = dest / relative
    if restored.is_file(): refs = [restored]
    else:
        for archive in INPUTS.rglob('*.zip'):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist():
                    safe_extract(z, dest)
                    refs = [dest / relative]
                    break
assert len(refs) == 1, 'Attach balanced250_to_epoch300_20260924_074129_epoch300.zip or its extracted folder.'
CHECKPOINT = refs[0]
assert hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest() == '3336458842278753855d7e0daabd329ffa0e9669ca8b21c4fc4c5126daa566da', 'Wrong epoch300 checkpoint.'
for name in ['last.pt', 'best_iou.pth', 'best_psnr.pth']:
    assert CHECKPOINT.with_name(name).is_file(), f'Missing {name}'
REFERENCE = CHECKPOINT.parent.parent
assert (CODE / 'run_sampling_experiment.py').is_file()
DATA = Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable the GPU.'
print('Balanced epoch300 reference:', REFERENCE)
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
state = torch.load(CHECKPOINT, map_location='cpu', weights_only=True)
assert state['epoch'] == 300
expected_config = dict(sampling_policy='balanced50_v1', lambda_seg=1e-4,
    learning_rate=1e-4, max_epoch=500, batch_size=1, workers=0, seed=3407,
    transpose_image=True, method='CRSDUN', input_setting='Y', input_mask='SSR')
for key, value in expected_config.items():
    assert state['config'][key] == value, f'Wrong checkpoint setting: {key}'
assert state['scheduler']['last_epoch'] == 300
assert state['scheduler']['T_max'] == 500
assert math.isclose(state['scheduler']['eta_min'], 2.5e-7)
print('Saved next-epoch LR:', state['optimizer']['param_groups'][0]['lr'])
print('Preserved best metrics:', state['best'])
del state
subprocess.run([sys.executable, 'run_public252.py', '--root', str(DATA)], cwd=CODE, check=True)
print('Preflight only above. The next cell restores balanced sampling and the saved quarter-rate schedule.')
# Check that the resume uses the same training implementation recorded by the prior run.
previous_provenance = json.loads((REFERENCE / 'continuation.json').read_text())
for filename, expected_hash in previous_provenance['source_sha256'].items():
    actual_hash = hashlib.sha256((CODE / filename).read_bytes()).hexdigest()
    assert actual_hash == expected_hash, f'Training code changed: {filename}. Use BTP-code-sampling.zip.'
print('Training source hashes match the epoch300 run.')

In [ ]:
from datetime import datetime
from IPython.display import display, FileLink
import os
if 'CONT300_RUN' not in globals():
    CONT300_RUN = Path('/kaggle/working') / ('balanced300_to_epoch400_' + datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT300_RUN.mkdir(exist_ok=False)
    shutil.copy2(CODE / 'public252-v1.json', CONT300_RUN / 'dataset_protocol.json')
    manifest = {
        'reference_checkpoint_sha256': hashlib.sha256(CHECKPOINT.read_bytes()).hexdigest(),
        'source_epoch': 300, 'target_epoch': 400, 'backup_epochs': [350, 400],
        'sampling_policy': 'balanced50_v1', 'lambda_seg': 1e-4,
        'note': 'Full-state continuation; unchanged500-epoch quarter-rate scheduler. Two sequential blocks from300 through400, with an intermediate backup at350.',
        'source_sha256': {f: hashlib.sha256((CODE / f).read_bytes()).hexdigest()
            for f in ['train.py','dataset.py','balanced_sampling.py','opt.py','training_state.py']}
    }
    (CONT300_RUN / 'continuation.json').write_text(json.dumps(manifest, indent=2))

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT300_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT300_RUN.parent / (CONT300_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT300_RUN.parent, base_dir=CONT300_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT300_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT300_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target in (350, 400)
    last = CONT300_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT300_RUN.parent) + '/', '--name', CONT300_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT300_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT300_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print(f'Epoch{target} completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT300_RUN)

In [ ]:
continue_to(350)
continue_to(400)

In [ ]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced300_to_epoch400_20260925_173543/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch278_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced300_to_epoch400_20260925_173543_epoch400.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch278 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

In [ ]:
NAME='epoch278_validation_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f')
RUN=WORK/NAME
subprocess.run([sys.executable,'test.py','--data_root',str(DATA),
    '--transpose_image','--eval_split','val','--pretrained_model_path',str(CHECKPOINT),
    '--outf',str(WORK),'--name',NAME,'--workers','0','--save_segmentation'],
    cwd=CODE,check=True)
OUT=RUN/'evaluation_val'
print('Evaluation complete:',OUT)

In [ ]:
EXPECTED_MIOU=0.7862424401936461
EXPECTED_PSNR=38.36915969848633

import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['split']=='val' and meta['scene_count']==25
assert meta['checkpoint_sha256']==EXPECTED
assert len(set(meta['scenes']))==25
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(scene+'_confusion.npy')) for scene in meta['scenes']]
assert np.array_equal(sum(parts),cm), 'Per-scene confusion totals differ.'
assert len(list(OUT.glob('*_preview.png')))==25
assert not list(OUT.glob('*_hsi.npy'))
seg=pd.read_csv(OUT/'segmentation.csv',index_col=0)
rec=pd.read_csv(OUT/'reconstruction.csv')
miou=float(seg.loc['total(-bg)','IoU'])
psnr=float(rec.iloc[0]['PSNR'])
summary=dict(checkpoint_epoch=278,validation_scenes=25,foreground_miou=miou,
    psnr_ref1=psnr,logged_miou=EXPECTED_MIOU,logged_psnr=EXPECTED_PSNR,
    miou_difference=miou-EXPECTED_MIOU,psnr_difference=psnr-EXPECTED_PSNR,
    matches_logged_metrics=bool(abs(miou-EXPECTED_MIOU)<1e-5 and abs(psnr-EXPECTED_PSNR)<1e-3),
    scope='Independent full validation evaluation; no test performance or new training.')
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'evaluator_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in
    ['test.py','dataset.py','utils.py','public252-v1.json']},indent=2))
print(json.dumps(summary,indent=2))
display(seg)
display(rec)

import io
BASELINE_CSV=',IoU,F1,Prec,recall,Acc\n"bg,",0.9948839716665797,0.9973854282614268,0.9957255823734946,0.9991511511710756,0.995108642578125\nreal potato,0.8534077820356925,0.920856927078357,0.9945274220599405,0.8574343170436838,0.9998237609863281\nfake potato,0.831000609337777,0.9076514648699882,0.9967426460350126,0.8332634932286658,0.9998765563964844\nreal apple,0.7945355618563241,0.8854557035354464,0.9445140547114728,0.8334365288215987,0.9992564392089843\nfake apple,0.7085108064433383,0.8293412480663026,0.992010796714241,0.71257678341183,0.9988931274414062\nreal orange,0.8376294495094424,0.911591629208639,0.992636015373844,0.8428670583271531,0.9997846984863281\nfake orange,0.8940453126379823,0.9440090694529523,0.9276197287534351,0.961091562940563,0.9996739196777343\nreal grape,0.6859217982220894,0.8136558738019682,0.9059530132154114,0.7385076318167972,0.9992939758300782\nfake grape,0.8314671338620018,0.9079293241369685,0.9219746537886951,0.8944025042511137,0.9993293762207032\nreal lemon,0.6550680724747725,0.7915412072954824,0.7067945245175014,0.8995066099778419,0.999443359375\nfake lemon,0.8373679991568999,0.9114367831639925,0.9952189789531378,0.8407500840912364,0.999654541015625\nreal avocado,0.7732943884617149,0.8721060684390091,0.8013755047953851,0.9566502305968763,0.9997393798828125\nfake avocado,0.47198576455360475,0.6412474607286106,0.9922542470017561,0.4737311849817497,0.9993658447265625\nreal pepper,0.7932016753543454,0.8846265262467832,0.9113224196757079,0.8595444649610192,0.9991802978515625\nfake pepper,0.8931769397579965,0.9435247908004276,0.9835428026974321,0.9067281165947884,0.9997415161132812\nreal plant,0.8205660968577401,0.9013907089803945,0.9452655525412759,0.8614992664426725,0.9981156921386719\nfake plant,0.7669498456280217,0.8680559678767813,0.8540159366719359,0.8826686947341124,0.9997865295410157\nreal banana,0.6259002271166157,0.7698641578381138,0.9586116073809795,0.6432839831367378,0.9991360473632812\nfake banana,0.6914398484597389,0.8175254519708561,0.8218236605613171,0.8133709288871025,0.999332275390625\nreal onion,0.7376813392016554,0.8489915801630484,0.7653919071685393,0.9532173458331811,0.9996937561035156\nfake onion,0.9261036246136366,0.9615843040923314,0.9915232213839398,0.9334945360702651,0.9999530029296875\nreal unknown,0.8828193054784751,0.9377131527706012,0.9201101083461792,0.9561067789974448,0.9999797058105468\nfake unknown,0.21214896085379148,0.34999762141131746,0.24244749708750787,0.6293009665103049,0.9980308532714843\ntotal,0.7617002831974015,0.8529340195734696,0.8939739948612235,0.83837322707947,0.999225795579993\ntotal(-bg),0.7511010246306207,0.8463680464512897,0.8893489227015748,0.8310651396207608,0.9994129388982597\n'
BASELINE_META={'status': 'completed', 'split': 'val', 'scope': 'full split', 'checkpoint_sha256': '5ad004708dd6ce388708ad3627cf8206b184804b6202754204f7296bfc253c7b', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'reference_amplitude': 1.0, 'seed': 3407, 'torch': '2.10.0+cu128', 'gpu': 'Tesla T4', 'config': {'data_root': '/kaggle/input/datasets/arnavnigamd/btp-data/public252', 'pretrained_model_path': '/kaggle/input/datasets/arnavnigamd/checkpoint10/balanced150_to_epoch200_20260923_102523/model/best_iou.pth', 'eval_split': 'val', 'transpose_image': True, 'outf': '/kaggle/working', 'name': 'epoch188_validation_audit_20260923_152602_480885', 'workers': 0, 'mask_path': '/kaggle/input/datasets/arnavnigamd/btp-code-8/BTP/mask/mask512x512.mat', 'limit': None, 'save_predictions': False, 'save_segmentation': True, 'batch_size': 1}, 'scene_count': 25, 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050']}
assert set(meta['scenes'])==set(BASELINE_META['scenes']), 'Validation scene membership changed.'
for field in ['protocol_sha256','mask_sha256','reference_amplitude']:
    assert meta[field]==BASELINE_META[field], f'Evaluation protocol changed: {field}'
baseline=pd.read_csv(io.StringIO(BASELINE_CSV),index_col=0)
assert list(seg.index)==list(baseline.index), 'Class ordering changed.'
comparison=pd.DataFrame({'epoch188_IoU_percent':100*baseline['IoU'],
    'epoch278_IoU_percent':100*seg['IoU'],
    'change_points':100*(seg['IoU']-baseline['IoU']),
    'epoch278_precision_percent':100*seg['Prec'],
    'epoch278_recall_percent':100*seg['recall']})
comparison.to_csv(RUN/'comparison_with_epoch188.csv')
(RUN/'epoch188_segmentation_reference.csv').write_text(BASELINE_CSV)
print('Per-class comparison; percentage-point changes, not statistical significance:')
display(comparison)

# Save results even if the comparison differs, so the difference can be investigated.
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir(WORK)
print('Download this archive before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))
if not summary['matches_logged_metrics']:
    print('Metrics differ from the training record: share this ZIP before further training.')

In [ ]:
from pathlib import Path
import json, hashlib, datetime, zipfile, shutil, os, io
import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
from scipy.ndimage import label as connected_components, find_objects
from IPython.display import display, FileLink
DATA=Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
RAW_ROOT=None  # Optional Path('/kaggle/input/.../raw_labels'); original H x W x2 arrays only.
RUN=Path('/kaggle/working')/('training_label_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
(RUN/'previews').mkdir()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()

SPEC={'protocol_id': 'public252-v1', 'date': '2026-09-16', 'scope': 'Controlled public-subset experiments, not an exact CRSDUN paper reproduction', 'dataset_files_sha256': {'train_data.csv': 'fc2a3c666d3344c7bcaedebe44c5af1a32b2f353c1f3a66c0b097d65d8839eff', 'val_data.csv': 'c1b81f6b272bffed303e3bfca099735c02cc3f536d4ef9a6b2335bbd73f5556e', 'test_data.csv': '38ea2fcea42a7cf767c3dce4029fa9055c0006633bdc497bd118365bdc9f8c16', 'all_data.csv': '96092c78659c3b83bbcde26f7f4597a51ba5959d18df6b8f85fc65ebdcb08c9c', 'split_manifest.json': '8fdffa621343cced4cd32a9da6553763cf6c2de0c04b0eb87c4e6945b4a43899', 'labels_crsdun_like_manifest.json': '68922836b85f84e2c27f625c0ce2515abd9d4a0f3f96033483b4526eeab7fb04', 'visible_28_candidate_bk7_manifest.json': '4de811f2f6e6742ed00ecb53b102ca68b3ffbdbfdc17e40bc4efe9d1e6f46df6'}, 'split_sizes': {'train': 202, 'val': 25, 'test': 25}, 'transpose_image': True, 'normalization': 'identity; retain distributed intensities', 'clipping': 'none', 'tensor_dtype': 'float32', 'labels_dtype': 'int64', 'reconstruction_metrics': {'reference_amplitude': 1.0, 'label': 'PSNR_ref1 / SSIM_ref1', 'meaning': 'Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range.'}, 'target_wavelengths_nm': [400.0, 405.26771217007314, 410.76554496731114, 416.5098328510006, 422.51851664943507, 428.81134334937263, 435.410095387312, 442.3388543250952, 449.6243046310128, 457.2960842506011, 465.3871897405087, 473.9344449415441, 482.97904344647924, 492.56717639500704, 502.75075825205676, 513.5882639304882, 525.1456904518687, 537.4976545526498, 550.7286330309245, 564.934343290246, 580.2232445419355, 596.7181110977776, 614.5575818318009, 633.8975157246186, 654.9118721117962, 677.7926758445392, 702.7484182706323, 730.0], 'wavelength_rule': 'linear interpolation from the original 10 nm FVgNET grid onto 28 wavelengths equally spaced in N-BK7 refractive-index dispersion coordinate', 'raw_fruit_id_mapping': {'1': {'real': 1, 'fake': 2}, '2': {'real': 19, 'fake': 20}, '3': {'real': 7, 'fake': 8}, '4': {'real': 15, 'fake': 16}, '5': {'real': 9, 'fake': 10}, '6': {'real': 5, 'fake': 6}, '7': {'real': 3, 'fake': 4}, '8': {'real': 13, 'fake': 14}, '9': {'real': 17, 'fake': 18}, '10': {'real': 21, 'fake': 22}, '11': {'real': 11, 'fake': 12}, '12': {'real': 21, 'fake': 22}}, 'starfruit_policy': 'Map raw ID 12 to other/unknown: real=21, fake=22; preserve real/fake distinction.', 'provenance': {'hyplex_commit': '187cd9394dae08beb883dbc6bab50a6d3f317c66'}, 'limitations': ['CRSDUN processed release could not be inspected; browser site-safety policy blocks Baidu share.', 'Exact author wavelength grid and raw-to-23-class conversion are not published in inspected source.', 'Distributed intensity radiometric calibration is not established; identity is a project convention supported by the active Hyplex loader.', 'Published paper scores are not directly comparable to public252-v1 scores.']}
HISTORICAL_TRAIN_RAW={'2021-11-03_007': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_008': {'raw_fruit_ids': [-1, 0, 6, 7], 'starfruit_pixels': 0}, '2021-11-03_010': {'raw_fruit_ids': [-1, 0, 5, 6], 'starfruit_pixels': 0}, '2021-11-03_015': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_017': {'raw_fruit_ids': [-1, 0, 3, 7], 'starfruit_pixels': 0}, '2021-11-03_018': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-03_020': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-03_021': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-03_023': {'raw_fruit_ids': [-1, 0, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-03_025': {'raw_fruit_ids': [-1, 0, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-03_032': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_033': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_034': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_035': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_036': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_037': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_040': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_041': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_042': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_043': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_045': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_048': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_049': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_051': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_052': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_053': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_054': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_055': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_056': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_058': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_080': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_081': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_082': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_084': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_086': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_087': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_088': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_089': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_091': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_092': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_094': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_099': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_101': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_102': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_103': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_104': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_001': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_006': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_007': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_008': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_009': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_011': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_016': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_018': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_019': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_020': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_021': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_022': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_023': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_025': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_026': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_027': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_028': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_030': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_031': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_032': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_033': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_034': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_035': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_036': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_037': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_038': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_039': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_041': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_044': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_045': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_046': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_048': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_050': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_051': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_052': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_053': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_054': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_056': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_057': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_058': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_059': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_062': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_063': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_064': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_065': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_066': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_067': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_068': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_069': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_070': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_071': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_072': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_073': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_074': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_075': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_076': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_077': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_079': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_080': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_081': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_082': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_083': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_084': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_085': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_086': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_089': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_090': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_091': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_092': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_094': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_095': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_096': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_097': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_102': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_103': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-04_105': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-04_106': {'raw_fruit_ids': [-1, 0, 3, 5, 6], 'starfruit_pixels': 0}, '2021-11-04_107': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7], 'starfruit_pixels': 0}, '2021-11-04_108': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7], 'starfruit_pixels': 0}, '2021-11-05_001': {'raw_fruit_ids': [-1, 0, 5, 6, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_002': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_004': {'raw_fruit_ids': [-1, 0, 3, 5, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_005': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_006': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_008': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_009': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_012': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_013': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_014': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_015': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 8], 'starfruit_pixels': 0}, '2021-11-05_016': {'raw_fruit_ids': [-1, 0, 3, 5, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_017': {'raw_fruit_ids': [-1, 0, 3, 4], 'starfruit_pixels': 0}, '2021-11-05_018': {'raw_fruit_ids': [-1, 0, 4, 8, 11], 'starfruit_pixels': 0}, '2021-11-05_019': {'raw_fruit_ids': [-1, 0, 6, 9, 11, 12], 'starfruit_pixels': 2013}, '2021-11-05_020': {'raw_fruit_ids': [-1, 0, 3, 4, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_021': {'raw_fruit_ids': [-1, 0, 7, 8, 11], 'starfruit_pixels': 0}, '2021-11-05_022': {'raw_fruit_ids': [-1, 0, 5, 6, 11], 'starfruit_pixels': 0}, '2021-11-05_025': {'raw_fruit_ids': [-1, 0, 3, 4, 8], 'starfruit_pixels': 0}, '2021-11-05_027': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 11], 'starfruit_pixels': 0}, '2021-11-05_028': {'raw_fruit_ids': [-1, 0, 6, 9, 10, 12], 'starfruit_pixels': 1807}, '2021-11-05_029': {'raw_fruit_ids': [-1, 0, 3, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_032': {'raw_fruit_ids': [-1, 0, 4, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_033': {'raw_fruit_ids': [-1, 0, 4, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_034': {'raw_fruit_ids': [-1, 0, 4, 5, 7, 8, 9], 'starfruit_pixels': 0}, '2021-11-05_042': {'raw_fruit_ids': [-1, 0, 4, 5, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_043': {'raw_fruit_ids': [-1, 0, 3, 4, 11, 12], 'starfruit_pixels': 1781}, '2021-11-05_047': {'raw_fruit_ids': [-1, 0, 4, 5, 6], 'starfruit_pixels': 0}, '2021-11-05_049': {'raw_fruit_ids': [-1, 0, 3, 7, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_050': {'raw_fruit_ids': [-1, 0, 3, 4, 7, 9, 10], 'starfruit_pixels': 0}, '2021-11-05_051': {'raw_fruit_ids': [-1, 0, 4, 5, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_052': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 8], 'starfruit_pixels': 0}, '2021-11-05_053': {'raw_fruit_ids': [-1, 0, 3, 6, 7, 8, 9], 'starfruit_pixels': 0}, '2021-11-05_055': {'raw_fruit_ids': [-1, 0, 3, 7, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_056': {'raw_fruit_ids': [-1, 0, 7, 8, 9, 10, 11], 'starfruit_pixels': 0}, '2021-11-05_057': {'raw_fruit_ids': [-1, 0, 3, 4, 6, 8, 9, 10], 'starfruit_pixels': 0}, '2021-11-05_058': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_059': {'raw_fruit_ids': [-1, 0, 5, 7, 8, 10, 11], 'starfruit_pixels': 0}, '2021-11-05_060': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7, 10, 12], 'starfruit_pixels': 3428}, '2021-11-10_001': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_002': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_003': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_005': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_006': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_007': {'raw_fruit_ids': [-1, 0, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_008': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_009': {'raw_fruit_ids': [-1, 0, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_011': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_012': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_013': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_016': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_017': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_018': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_019': {'raw_fruit_ids': [-1, 0, 1, 8], 'starfruit_pixels': 0}, '2021-11-10_020': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_021': {'raw_fruit_ids': [-1, 0, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_022': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_023': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_025': {'raw_fruit_ids': [-1, 0, 1, 9], 'starfruit_pixels': 0}, '2021-11-10_026': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_027': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_028': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_030': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_032': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_033': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_035': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_036': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_038': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_040': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_041': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-10_042': {'raw_fruit_ids': [-1, 0, 2], 'starfruit_pixels': 0}, '2021-11-10_043': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_044': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_045': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_046': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_048': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_049': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}}

assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
assert sha(DATA/'train_data.csv')==SPEC['dataset_files_sha256']['train_data.csv'], 'Training split changed.'
manifest_path=DATA/'labels_crsdun_like_manifest.json'
assert manifest_path.is_file(), 'Prepared label manifest missing.'
assert sha(manifest_path)==SPEC['dataset_files_sha256']['labels_crsdun_like_manifest.json'], 'Label manifest changed.'
manifest=json.loads(manifest_path.read_text())
assert manifest['mapping']==SPEC['raw_fruit_id_mapping']
train=pd.read_csv(DATA/'train_data.csv',index_col=0)
names=sorted(train['names'].astype(str).tolist())
assert len(names)==len(set(names))==202
assert set(names)==set(HISTORICAL_TRAIN_RAW)
if RAW_ROOT is not None:
    RAW_ROOT=Path(RAW_ROOT)
    assert RAW_ROOT.is_dir()
print('Training scenes:',len(names),'| GPU not needed')
print('Fresh original raw-label audit:', 'enabled' if RAW_ROOT else 'unavailable; prepared labels and historical provenance only')
print('Frozen mapping: raw apple7 -> fake apple4; raw avocado11 -> fake avocado12; raw unknown10 and starfruit12 -> fake unknown22.')

In [ ]:
from pathlib import Path
import json, hashlib, datetime, zipfile, shutil, os, io
import numpy as np
import pandas as pd
from PIL import Image, ImageDraw
from scipy.ndimage import label as connected_components, find_objects
from IPython.display import display, FileLink
DATA=Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
RAW_ROOT=None  # Optional Path('/kaggle/input/.../raw_labels'); original H x W x2 arrays only.
RUN=Path('/kaggle/working')/('training_label_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
(RUN/'previews').mkdir()
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()

SPEC={'protocol_id': 'public252-v1', 'date': '2026-09-16', 'scope': 'Controlled public-subset experiments, not an exact CRSDUN paper reproduction', 'dataset_files_sha256': {'train_data.csv': 'fc2a3c666d3344c7bcaedebe44c5af1a32b2f353c1f3a66c0b097d65d8839eff', 'val_data.csv': 'c1b81f6b272bffed303e3bfca099735c02cc3f536d4ef9a6b2335bbd73f5556e', 'test_data.csv': '38ea2fcea42a7cf767c3dce4029fa9055c0006633bdc497bd118365bdc9f8c16', 'all_data.csv': '96092c78659c3b83bbcde26f7f4597a51ba5959d18df6b8f85fc65ebdcb08c9c', 'split_manifest.json': '8fdffa621343cced4cd32a9da6553763cf6c2de0c04b0eb87c4e6945b4a43899', 'labels_crsdun_like_manifest.json': '68922836b85f84e2c27f625c0ce2515abd9d4a0f3f96033483b4526eeab7fb04', 'visible_28_candidate_bk7_manifest.json': '4de811f2f6e6742ed00ecb53b102ca68b3ffbdbfdc17e40bc4efe9d1e6f46df6'}, 'split_sizes': {'train': 202, 'val': 25, 'test': 25}, 'transpose_image': True, 'normalization': 'identity; retain distributed intensities', 'clipping': 'none', 'tensor_dtype': 'float32', 'labels_dtype': 'int64', 'reconstruction_metrics': {'reference_amplitude': 1.0, 'label': 'PSNR_ref1 / SSIM_ref1', 'meaning': 'Fixed reference scale, not an assertion that all target values lie in [0,1]. No per-image inferred range.'}, 'target_wavelengths_nm': [400.0, 405.26771217007314, 410.76554496731114, 416.5098328510006, 422.51851664943507, 428.81134334937263, 435.410095387312, 442.3388543250952, 449.6243046310128, 457.2960842506011, 465.3871897405087, 473.9344449415441, 482.97904344647924, 492.56717639500704, 502.75075825205676, 513.5882639304882, 525.1456904518687, 537.4976545526498, 550.7286330309245, 564.934343290246, 580.2232445419355, 596.7181110977776, 614.5575818318009, 633.8975157246186, 654.9118721117962, 677.7926758445392, 702.7484182706323, 730.0], 'wavelength_rule': 'linear interpolation from the original 10 nm FVgNET grid onto 28 wavelengths equally spaced in N-BK7 refractive-index dispersion coordinate', 'raw_fruit_id_mapping': {'1': {'real': 1, 'fake': 2}, '2': {'real': 19, 'fake': 20}, '3': {'real': 7, 'fake': 8}, '4': {'real': 15, 'fake': 16}, '5': {'real': 9, 'fake': 10}, '6': {'real': 5, 'fake': 6}, '7': {'real': 3, 'fake': 4}, '8': {'real': 13, 'fake': 14}, '9': {'real': 17, 'fake': 18}, '10': {'real': 21, 'fake': 22}, '11': {'real': 11, 'fake': 12}, '12': {'real': 21, 'fake': 22}}, 'starfruit_policy': 'Map raw ID 12 to other/unknown: real=21, fake=22; preserve real/fake distinction.', 'provenance': {'hyplex_commit': '187cd9394dae08beb883dbc6bab50a6d3f317c66'}, 'limitations': ['CRSDUN processed release could not be inspected; browser site-safety policy blocks Baidu share.', 'Exact author wavelength grid and raw-to-23-class conversion are not published in inspected source.', 'Distributed intensity radiometric calibration is not established; identity is a project convention supported by the active Hyplex loader.', 'Published paper scores are not directly comparable to public252-v1 scores.']}
HISTORICAL_TRAIN_RAW={'2021-11-03_007': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_008': {'raw_fruit_ids': [-1, 0, 6, 7], 'starfruit_pixels': 0}, '2021-11-03_010': {'raw_fruit_ids': [-1, 0, 5, 6], 'starfruit_pixels': 0}, '2021-11-03_015': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_017': {'raw_fruit_ids': [-1, 0, 3, 7], 'starfruit_pixels': 0}, '2021-11-03_018': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-03_020': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-03_021': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-03_023': {'raw_fruit_ids': [-1, 0, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-03_025': {'raw_fruit_ids': [-1, 0, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-03_032': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_033': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_034': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_035': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_036': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_037': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_040': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_041': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_042': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_043': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_045': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_048': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_049': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_051': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_052': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_053': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_054': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_055': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_056': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_058': {'raw_fruit_ids': [-1, 0, 3], 'starfruit_pixels': 0}, '2021-11-03_080': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_081': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_082': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_084': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_086': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_087': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_088': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_089': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_091': {'raw_fruit_ids': [-1, 0, 5], 'starfruit_pixels': 0}, '2021-11-03_092': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_094': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_099': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_101': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_102': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_103': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-03_104': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_001': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_006': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_007': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_008': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_009': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_011': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_016': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_018': {'raw_fruit_ids': [-1, 0, 4], 'starfruit_pixels': 0}, '2021-11-04_019': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_020': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_021': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_022': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_023': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_025': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_026': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_027': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_028': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_030': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_031': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_032': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_033': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_034': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-04_035': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_036': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_037': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_038': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_039': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_041': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_044': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_045': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_046': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_048': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_050': {'raw_fruit_ids': [-1, 0, 6], 'starfruit_pixels': 0}, '2021-11-04_051': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_052': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_053': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_054': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_056': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_057': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_058': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_059': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_062': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_063': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_064': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_065': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_066': {'raw_fruit_ids': [-1, 0, 11], 'starfruit_pixels': 0}, '2021-11-04_067': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_068': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_069': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_070': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_071': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_072': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_073': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_074': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_075': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_076': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_077': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_079': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_080': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_081': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_082': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_083': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_084': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_085': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_086': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_089': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_090': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_091': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_092': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_094': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_095': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_096': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_097': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_102': {'raw_fruit_ids': [-1, 0, 7], 'starfruit_pixels': 0}, '2021-11-04_103': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-04_105': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-04_106': {'raw_fruit_ids': [-1, 0, 3, 5, 6], 'starfruit_pixels': 0}, '2021-11-04_107': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7], 'starfruit_pixels': 0}, '2021-11-04_108': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7], 'starfruit_pixels': 0}, '2021-11-05_001': {'raw_fruit_ids': [-1, 0, 5, 6, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_002': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_004': {'raw_fruit_ids': [-1, 0, 3, 5, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_005': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_006': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_008': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_009': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_012': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_013': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_014': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_015': {'raw_fruit_ids': [-1, 0, 3, 5, 6, 8], 'starfruit_pixels': 0}, '2021-11-05_016': {'raw_fruit_ids': [-1, 0, 3, 5, 7, 11], 'starfruit_pixels': 0}, '2021-11-05_017': {'raw_fruit_ids': [-1, 0, 3, 4], 'starfruit_pixels': 0}, '2021-11-05_018': {'raw_fruit_ids': [-1, 0, 4, 8, 11], 'starfruit_pixels': 0}, '2021-11-05_019': {'raw_fruit_ids': [-1, 0, 6, 9, 11, 12], 'starfruit_pixels': 2013}, '2021-11-05_020': {'raw_fruit_ids': [-1, 0, 3, 4, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_021': {'raw_fruit_ids': [-1, 0, 7, 8, 11], 'starfruit_pixels': 0}, '2021-11-05_022': {'raw_fruit_ids': [-1, 0, 5, 6, 11], 'starfruit_pixels': 0}, '2021-11-05_025': {'raw_fruit_ids': [-1, 0, 3, 4, 8], 'starfruit_pixels': 0}, '2021-11-05_027': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 11], 'starfruit_pixels': 0}, '2021-11-05_028': {'raw_fruit_ids': [-1, 0, 6, 9, 10, 12], 'starfruit_pixels': 1807}, '2021-11-05_029': {'raw_fruit_ids': [-1, 0, 3, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_032': {'raw_fruit_ids': [-1, 0, 4, 5, 6, 7], 'starfruit_pixels': 0}, '2021-11-05_033': {'raw_fruit_ids': [-1, 0, 4, 5, 6, 7, 8], 'starfruit_pixels': 0}, '2021-11-05_034': {'raw_fruit_ids': [-1, 0, 4, 5, 7, 8, 9], 'starfruit_pixels': 0}, '2021-11-05_042': {'raw_fruit_ids': [-1, 0, 4, 5, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_043': {'raw_fruit_ids': [-1, 0, 3, 4, 11, 12], 'starfruit_pixels': 1781}, '2021-11-05_047': {'raw_fruit_ids': [-1, 0, 4, 5, 6], 'starfruit_pixels': 0}, '2021-11-05_049': {'raw_fruit_ids': [-1, 0, 3, 7, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_050': {'raw_fruit_ids': [-1, 0, 3, 4, 7, 9, 10], 'starfruit_pixels': 0}, '2021-11-05_051': {'raw_fruit_ids': [-1, 0, 4, 5, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_052': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 8], 'starfruit_pixels': 0}, '2021-11-05_053': {'raw_fruit_ids': [-1, 0, 3, 6, 7, 8, 9], 'starfruit_pixels': 0}, '2021-11-05_055': {'raw_fruit_ids': [-1, 0, 3, 7, 8, 10], 'starfruit_pixels': 0}, '2021-11-05_056': {'raw_fruit_ids': [-1, 0, 7, 8, 9, 10, 11], 'starfruit_pixels': 0}, '2021-11-05_057': {'raw_fruit_ids': [-1, 0, 3, 4, 6, 8, 9, 10], 'starfruit_pixels': 0}, '2021-11-05_058': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 6, 7, 10], 'starfruit_pixels': 0}, '2021-11-05_059': {'raw_fruit_ids': [-1, 0, 5, 7, 8, 10, 11], 'starfruit_pixels': 0}, '2021-11-05_060': {'raw_fruit_ids': [-1, 0, 3, 4, 5, 7, 10, 12], 'starfruit_pixels': 3428}, '2021-11-10_001': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_002': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_003': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_005': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_006': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_007': {'raw_fruit_ids': [-1, 0, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_008': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_009': {'raw_fruit_ids': [-1, 0, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_011': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_012': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_013': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_016': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_017': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_018': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_019': {'raw_fruit_ids': [-1, 0, 1, 8], 'starfruit_pixels': 0}, '2021-11-10_020': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_021': {'raw_fruit_ids': [-1, 0, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_022': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_023': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_025': {'raw_fruit_ids': [-1, 0, 1, 9], 'starfruit_pixels': 0}, '2021-11-10_026': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_027': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_028': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_030': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}, '2021-11-10_032': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_033': {'raw_fruit_ids': [-1, 0, 1, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_035': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_036': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_038': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_040': {'raw_fruit_ids': [-1, 0, 1, 2], 'starfruit_pixels': 0}, '2021-11-10_041': {'raw_fruit_ids': [-1, 0, 8], 'starfruit_pixels': 0}, '2021-11-10_042': {'raw_fruit_ids': [-1, 0, 2], 'starfruit_pixels': 0}, '2021-11-10_043': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_044': {'raw_fruit_ids': [-1, 0, 1, 2, 8], 'starfruit_pixels': 0}, '2021-11-10_045': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_046': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_048': {'raw_fruit_ids': [-1, 0, 1, 2, 8, 9], 'starfruit_pixels': 0}, '2021-11-10_049': {'raw_fruit_ids': [-1, 0, 1, 2, 9], 'starfruit_pixels': 0}}

assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
assert sha(DATA/'train_data.csv')==SPEC['dataset_files_sha256']['train_data.csv'], 'Training split changed.'
manifest_path=DATA/'labels_crsdun_like_manifest.json'
assert manifest_path.is_file(), 'Prepared label manifest missing.'
assert sha(manifest_path)==SPEC['dataset_files_sha256']['labels_crsdun_like_manifest.json'], 'Label manifest changed.'
manifest=json.loads(manifest_path.read_text())
assert manifest['mapping']==SPEC['raw_fruit_id_mapping']
train=pd.read_csv(DATA/'train_data.csv',index_col=0)
names=sorted(train['names'].astype(str).tolist())
assert len(names)==len(set(names))==202
assert set(names)==set(HISTORICAL_TRAIN_RAW)
if RAW_ROOT is not None:
    RAW_ROOT=Path(RAW_ROOT)
    assert RAW_ROOT.is_dir()
print('Training scenes:',len(names),'| GPU not needed')
print('Fresh original raw-label audit:', 'enabled' if RAW_ROOT else 'unavailable; prepared labels and historical provenance only')
print('Frozen mapping: raw apple7 -> fake apple4; raw avocado11 -> fake avocado12; raw unknown10 and starfruit12 -> fake unknown22.')

In [ ]:
PALETTE=np.array([[0,0,0],[128,0,0],[0,128,0],[128,128,0],[0,0,128],[128,0,128],[0,128,128],[128,128,128],[64,0,0],[192,0,0],[64,128,0],[192,128,0],[64,0,128],[192,0,128],[64,128,128],[192,128,128],[0,64,0],[128,64,0],[0,192,0],[128,192,0],[0,64,128],[128,64,128],[0,192,128]],dtype=np.uint8)
TARGETS={4:'fake apple',12:'fake avocado',22:'fake unknown'}
def decode(rgb):
    assert rgb.shape==(512,512,3), f'Unexpected label shape: {rgb.shape}'
    ids=np.full(rgb.shape[:2],255,dtype=np.uint8)
    for i,color in enumerate(PALETTE): ids[np.all(rgb==color,axis=-1)]=i
    assert not np.any(ids==255), 'Unexpected palette color; will not silently map it to background.'
    return ids

def raw_to_ids(raw):
    assert raw.shape==(512,512,2) and np.isfinite(raw).all()
    assert np.equal(raw,np.round(raw)).all()
    fruit,flag=raw[:,:,0],raw[:,:,1]
    assert set(np.unique(fruit))<=set([-1,0]+list(range(1,13)))
    assert set(np.unique(flag[fruit>0]))<={-1,1}
    ids=np.zeros((512,512),dtype=np.uint8)
    for fid,entry in SPEC['raw_fruit_id_mapping'].items():
        ids[(fruit==int(fid))&(flag==1)]=entry['real']
        ids[(fruit==int(fid))&(flag==-1)]=entry['fake']
    return ids
rows=[];spectra=[];components=[];file_hashes={};errors=[];raw_checks=[];selected=[]
for index,scene in enumerate(names):
    label_path=DATA/'labels'/(scene+'.png')
    rgb_label=np.array(Image.open(label_path))
    ids=decode(rgb_label)
    counts=np.bincount(ids.ravel(),minlength=23)
    file_hashes[scene]={'prepared_label_sha256':sha(label_path)}
    row={'scene':scene,**{f'class_{c}_pixels':int(counts[c]) for c in range(23)},
         'historical_raw_fruit_ids':HISTORICAL_TRAIN_RAW[scene]['raw_fruit_ids'],
         'historical_starfruit_pixels':HISTORICAL_TRAIN_RAW[scene]['starfruit_pixels']}
    rows.append(row)
    if RAW_ROOT is not None:
        rp=RAW_ROOT/(scene+'.npy')
        if rp.is_file():
            raw=np.load(rp,allow_pickle=False)
            mismatch=int(np.count_nonzero(raw_to_ids(raw)!=ids))
            raw_checks.append({'scene':scene,'mismatch_pixels':mismatch,
                'fake_unknown_raw10_pixels':int(np.sum((raw[:,:,0]==10)&(raw[:,:,1]==-1))),
                'fake_unknown_raw12_pixels':int(np.sum((raw[:,:,0]==12)&(raw[:,:,1]==-1)))})
            file_hashes[scene]['raw_sha256']=sha(rp)
            if mismatch: errors.append(scene+': raw conversion differs from prepared labels')
        else: raw_checks.append({'scene':scene,'status':'missing raw file'})
    present=[c for c in TARGETS if counts[c]>0]
    if present:
        selected.append(scene)
        xp=DATA/'visible_28'/(scene+'.npy')
        x=np.load(xp,mmap_mode='r',allow_pickle=False).transpose(1,0,2)
        assert x.shape==(512,512,28)
        rgb=np.asarray(x[:,:,[24,18,8]],dtype=np.float32)
        assert np.isfinite(rgb).all()
        rgb=(np.clip(rgb/max(float(np.quantile(rgb,.99)),1e-8),0,1)*255).astype(np.uint8)
        overlay=rgb.copy()
        for c in present:
            mask=ids==c
            overlay[mask]=(0.5*rgb[mask]+0.5*PALETTE[c]).astype(np.uint8)
            values=np.asarray(x[mask],dtype=np.float64)
            assert np.isfinite(values).all()
            spectra.append({'scene':scene,'class_id':c,'class_name':TARGETS[c],'pixels':int(mask.sum()),
                'mean_spectrum':values.mean(axis=0).tolist(),'std_spectrum':values.std(axis=0).tolist()})
            cc,n=connected_components(mask)
            for k,sl in enumerate(find_objects(cc),1):
                if sl is None:continue
                area=int(np.count_nonzero(cc[sl]==k))
                components.append({'scene':scene,'class_id':c,'component':k,'pixels':area,
                    'row_start':sl[0].start,'row_end_exclusive':sl[0].stop,'col_start':sl[1].start,'col_end_exclusive':sl[1].stop})
        canvas=Image.new('RGB',(1536,560),'white');draw=ImageDraw.Draw(canvas)
        for j,(panel,title) in enumerate([(rgb,'Pseudo-RGB'),(rgb_label,'Prepared ground truth'),(overlay,'Target-class overlay')]):
            canvas.paste(Image.fromarray(panel),(j*512,48));draw.text((j*512+5,5),scene+' | '+title,fill='black')
        draw.text((5,25),' | '.join(f'{c}: {TARGETS[c]} ({counts[c]} pixels)' for c in present),fill='black')
        canvas.save(RUN/'previews'/(scene+'.png'))
        del x
    if (index+1)%25==0 or index+1==len(names): print(f'Audited training labels: {index+1}/{len(names)}',flush=True)
summary={'scope':'Training-only label/provenance audit; no model inference, test data or label changes.',
    'train_scenes':len(names),'selected_scenes':len(selected),'selected_scene_ids':selected,
    'classes':{str(c):{'name':name,'scenes':sum(r[f'class_{c}_pixels']>0 for r in rows),
        'pixels':sum(r[f'class_{c}_pixels'] for r in rows)} for c,name in TARGETS.items()},
    'fresh_raw_files_checked':sum('mismatch_pixels' in r for r in raw_checks),
    'fresh_raw_status':'unavailable' if RAW_ROOT is None else 'complete' if len(raw_checks)==202 and all('mismatch_pixels' in r for r in raw_checks) else 'partial',
    'errors':errors,'historical_raw_source':'September16 audit; embedded train-only scene metadata, not a fresh raw-label verification',
    'limitations':['Prepared unknown labels cannot distinguish raw10 from raw12 without original raw labels.',
        'Conversion consistency does not establish semantic annotation correctness.',
        'Scene-level mean spectra can mix multiple objects; spectral similarity is descriptive, not a classification bound.']}
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'train_scene_counts.json').write_text(json.dumps(rows,indent=2))
(RUN/'target_spectra.json').write_text(json.dumps(spectra,indent=2))
(RUN/'components.json').write_text(json.dumps(components,indent=2))
(RUN/'raw_conversion_checks.json').write_text(json.dumps(raw_checks,indent=2))
(RUN/'label_hashes.json').write_text(json.dumps(file_hashes,indent=2))
(RUN/'frozen_label_manifest.json').write_text(json.dumps(manifest,indent=2))
print(json.dumps(summary,indent=2))

In [ ]:
# Contact sheets retain every selected training scene, sorted by scene ID.
thumbs=[]
for scene in selected:
    with Image.open(RUN/'previews'/(scene+'.png')) as im:
        thumbs.append(im.resize((768,280)))
for page,start in enumerate(range(0,len(thumbs),8),1):
    items=thumbs[start:start+8]
    sheet=Image.new('RGB',(1536,280*((len(items)+1)//2)),'white')
    for j,im in enumerate(items): sheet.paste(im,((j%2)*768,(j//2)*280))
    sheet.save(RUN/f'contact_sheet_{page:02d}.jpg',quality=90)
# Plot per-scene mean target spectra without fitting or normalizing the data.
import matplotlib.pyplot as plt
fig,axes=plt.subplots(1,3,figsize=(15,4),sharex=True)
for ax,(c,name) in zip(axes,TARGETS.items()):
    for row in spectra:
        if row['class_id']==c: ax.plot(SPEC['target_wavelengths_nm'],row['mean_spectrum'],alpha=.35)
    ax.set_title(name);ax.set_xlabel('Candidate wavelength (nm)');ax.set_ylabel('Mean distributed intensity')
fig.tight_layout();fig.savefig(RUN/'training_mean_spectra.png',dpi=160);plt.close(fig)
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=RUN.parent,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir('/kaggle/working')
print('Download before stopping:',archive.name,'bytes:',archive.stat().st_size)
display(FileLink(archive.name))

In [ ]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced300_to_epoch400_20260925_173543/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch278_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced300_to_epoch400_20260925_173543_epoch400.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch278 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

In [ ]:
SCRIPT="\nimport argparse,json,hashlib,sys\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom PIL import Image\np=argparse.ArgumentParser()\np.add_argument('--code',type=Path,required=True);p.add_argument('--data',type=Path,required=True)\np.add_argument('--checkpoint',type=Path,required=True);p.add_argument('--out',type=Path,required=True)\np.add_argument('--selection',type=Path,required=True)\na=p.parse_args();sys.path.insert(0,str(a.code))\nfrom dataset import HySpecSegmentation,SegIdentityTransform,encode_segmap,get_labels\nfrom torch.utils.data import DataLoader\nfrom test import evaluate_batches,sha256\nfrom utils import init_mask,init_meas,set_seed\nfrom models import model_generator\nspec=json.loads((a.code/'public252-v1.json').read_text())\nassert sha256(a.data/'train_data.csv')==spec['dataset_files_sha256']['train_data.csv']\nselection=json.loads(a.selection.read_text())\nassert sha256(a.checkpoint)==selection['checkpoint_sha256']\nds=HySpecSegmentation(str(a.data),'train_data.csv',transform=SegIdentityTransform(),transpose_image=True)\nassert len(ds)==202\nchosen=[]\nfor scene in ds.names:\n    rgb=np.array(Image.open(a.data/'labels'/(str(scene)+'.png')))\n    ids=encode_segmap(rgb)\n    assert np.array_equal(get_labels()[ids],rgb), 'Unrecognized label color'\n    if np.isin(ids,[4,12,22]).any(): chosen.append(str(scene))\nassert sorted(chosen)==selection['scenes'], 'Selection differs from the verified training-label audit'\nds.data=ds.data[ds.data.names.astype(str).isin(chosen)].copy()\nds.names=np.array(sorted(chosen))\nassert len(ds)==len(ds.names)==57\nloader=DataLoader(ds,batch_size=1,shuffle=False,num_workers=0)\na.out.mkdir(exist_ok=False,parents=True)\nset_seed(3407)\nmodel=model_generator('CRSDUN',28,ds.num_classes,str(a.checkpoint))\nphi,mask=init_mask(str(a.code/'mask/mask512x512.mat'),'SSR',1,28)\nrecord={'status':'running','split':'selected_train','checkpoint_epoch':278,\n    'checkpoint_sha256':sha256(a.checkpoint),'protocol_sha256':sha256(a.code/'public252-v1.json'),\n    'mask_sha256':sha256(a.code/'mask/mask512x512.mat'),'torch':str(torch.__version__),\n    'gpu':torch.cuda.get_device_name(0),'selection_rule':'All training scenes containing class4,12 or22 in prepared labels',\n    'scope':'Full-frame evaluation on selected training scenes; no optimization or held-out image access',\n    'limitations':'Selection is conditioned on target ground truth. Precision and aggregate mIoU are not representative of the full train split; comparison with validation is descriptive.'}\n(a.out/'evaluation.json').write_text(json.dumps(record,indent=2))\nscenes=evaluate_batches(model,loader,lambda x:init_meas(x,phi,'Y'),mask,'cuda',a.out,save_segmentation=True)\nrecord.update(status='completed',scene_count=len(scenes),scenes=scenes)\n(a.out/'evaluation.json').write_text(json.dumps(record,indent=2))\n"
SELECTION={'scenes': ['2021-11-03_017', '2021-11-03_020', '2021-11-03_021', '2021-11-03_023', '2021-11-03_025', '2021-11-04_056', '2021-11-04_057', '2021-11-04_058', '2021-11-04_059', '2021-11-04_062', '2021-11-04_063', '2021-11-04_064', '2021-11-04_065', '2021-11-04_066', '2021-11-04_082', '2021-11-04_083', '2021-11-04_084', '2021-11-04_085', '2021-11-04_086', '2021-11-04_089', '2021-11-04_090', '2021-11-04_091', '2021-11-04_092', '2021-11-04_094', '2021-11-04_095', '2021-11-04_096', '2021-11-04_097', '2021-11-04_102', '2021-11-04_103', '2021-11-04_105', '2021-11-04_108', '2021-11-05_001', '2021-11-05_002', '2021-11-05_008', '2021-11-05_009', '2021-11-05_012', '2021-11-05_013', '2021-11-05_014', '2021-11-05_016', '2021-11-05_019', '2021-11-05_020', '2021-11-05_021', '2021-11-05_022', '2021-11-05_027', '2021-11-05_028', '2021-11-05_029', '2021-11-05_034', '2021-11-05_042', '2021-11-05_043', '2021-11-05_049', '2021-11-05_050', '2021-11-05_055', '2021-11-05_056', '2021-11-05_057', '2021-11-05_058', '2021-11-05_059', '2021-11-05_060'], 'checkpoint_sha256': '89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c'}

RUN=WORK/('epoch278_training_fit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
SCRIPT_PATH=RUN/'training_diagnostic.py'
SCRIPT_PATH.write_text(SCRIPT)
(RUN/'selection.json').write_text(json.dumps(SELECTION,indent=2))
subprocess.run([sys.executable,str(SCRIPT_PATH),'--code',str(CODE),'--data',str(DATA),
    '--checkpoint',str(CHECKPOINT),'--out',str(RUN/'evaluation_train'),
    '--selection',str(RUN/'selection.json')],cwd=CODE,check=True)
OUT=RUN/'evaluation_train'

In [ ]:
VALIDATION_CSV=',IoU,F1,Prec,recall,Acc\n"bg,",0.9956056857102029,0.9977480073007325,0.9965542331594534,0.9990448847883433,0.9958021545410156\nreal potato,0.9309118500011194,0.9641699818594597,0.9956533415423344,0.9347105211080015,0.9999169921875\nfake potato,0.9522338696266445,0.9754825724698661,0.9823704124390311,0.9687892549478581,0.999964599609375\nreal apple,0.7667310698808576,0.86791656541023,0.9908069402405689,0.7722246759300102,0.999189453125\nfake apple,0.6043422511191895,0.7533351644919333,0.9394433318876814,0.6288393120399316,0.9984455871582031\nreal orange,0.9262720557716387,0.9616751181814689,0.9961533565435742,0.9295970249004514,0.9999024963378906\nfake orange,0.9395745507163982,0.968796030785346,0.9631307228319249,0.9746295652135722,0.999820556640625\nreal grape,0.633692737291463,0.7757318358626515,0.9847070619059142,0.6399912253161498,0.9992276000976562\nfake grape,0.903082134230324,0.949023210711403,0.9530405084725043,0.9451387990548249,0.9996247863769532\nreal lemon,0.5693110254280307,0.725507126786873,0.6111654314946624,0.8926252805423879,0.9992063903808593\nfake lemon,0.840714331095886,0.9134156552707563,0.9981191673239364,0.8420483170425653,0.9996624755859375\nreal avocado,0.9437285770065472,0.9709997714735892,0.99296377221617,0.9500820862055487,0.9999473571777344\nfake avocado,0.6883845379525112,0.8153874257399899,0.9998147962997259,0.6884723197083357,0.9996270751953125\nreal pepper,0.9032760667551863,0.9491303105984753,0.9317314223018788,0.967295173672221,0.9996211242675781\nfake pepper,0.900210338405034,0.9474349533973953,0.9640254341856007,0.9315024586678032,0.9997538757324219\nreal plant,0.8239757843089116,0.9034442395536414,0.9232679952816458,0.8845496691412166,0.9981098937988281\nfake plant,0.8616340199240582,0.9256251271314639,0.9794564309981504,0.8774923144652547,0.9998878479003906\nreal banana,0.5656761794155748,0.7225490193781943,0.9237762879397793,0.5933722627096818,0.9989762878417969\nfake banana,0.7485354041636234,0.8561356100749404,0.8759871485204622,0.8372594489278414,0.9994825744628906\nreal onion,0.7189954833355378,0.8364804440637529,0.7517166991824868,0.9429150322088324,0.9996670532226563\nfake onion,0.9352912861678297,0.9665138489307946,0.9866498492027745,0.9472792999448778,0.9999586486816406\nreal unknown,0.9121494474626685,0.954006635209248,0.9779558138320829,0.9312976210593873,0.9999856567382812\nfake unknown,0.2286106842011801,0.3721088184324781,0.24403452223142932,0.7834117931290874,0.9977726745605469\ntotal,0.7953451899987137,0.8727224988310731,0.9114141165232076,0.8635899278575733,0.9992849200704824\ntotal(-bg),0.7862424401936461,0.8670395211733616,0.90754411122156,0.8574328843607201,0.9994432275945492\n'
VALIDATION_META={'status': 'completed', 'split': 'val', 'scope': 'full split', 'checkpoint_sha256': '89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'reference_amplitude': 1.0, 'seed': 3407, 'torch': '2.10.0+cu128', 'gpu': 'Tesla T4', 'config': {'data_root': '/kaggle/input/datasets/arnavnigamd/btp-data/public252', 'pretrained_model_path': '/kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/best_iou.pth', 'eval_split': 'val', 'transpose_image': True, 'outf': '/kaggle/working', 'name': 'epoch278_validation_audit_20260927_164048_773155', 'workers': 0, 'mask_path': '/kaggle/input/datasets/arnavnigamd/btp-code-8/BTP/mask/mask512x512.mat', 'limit': None, 'save_predictions': False, 'save_segmentation': True, 'batch_size': 1}, 'scene_count': 25, 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050']}

import io
import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['scene_count']==57
assert sorted(meta['scenes'])==SELECTION['scenes']
assert not (set(meta['scenes'])&set(VALIDATION_META['scenes']))
for f in ['checkpoint_sha256','mask_sha256','protocol_sha256']:
    assert meta[f]==VALIDATION_META[f], f'Mismatched evaluation: {f}'
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(s+'_confusion.npy')) for s in meta['scenes']]
assert np.array_equal(sum(parts),cm)
assert len(list(OUT.glob('*_preview.png')))==57
assert not list(OUT.glob('*_hsi.npy'))
train=pd.read_csv(OUT/'segmentation.csv',index_col=0)
val=pd.read_csv(io.StringIO(VALIDATION_CSV),index_col=0)
names=list(train.index[:23])
comparison=pd.DataFrame(index=['fake apple','fake avocado','fake unknown'])
for metric in ['IoU','Prec','recall']:
    comparison['selected_train_'+metric+'_percent']=100*train.loc[comparison.index,metric]
    comparison['validation_'+metric+'_percent']=100*val.loc[comparison.index,metric]
comparison.to_csv(RUN/'target_train_vs_validation.csv')
details={}
for c in [4,12,22]:
    row=cm[c];col=cm[:,c]
    details[names[c]]={'gt_pixels':int(row.sum()),'gt_predicted_as_percent':{
        names[int(i)]:float(row[i]/row.sum()*100) for i in np.argsort(row)[::-1][:5]},
        'prediction_sources_percent':{names[int(i)]:float(col[i]/col.sum()*100) for i in np.argsort(col)[::-1][:5]} if col.sum() else {}}
summary={'checkpoint_epoch':278,'train_scenes':57,'target_confusions':details,
    'scope':'Training-fit diagnostic; no new training. Selected-train versus validation comparison is descriptive, not a causal or statistically independent test.'}
(RUN/'diagnostic_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'validation_reference.csv').write_text(VALIDATION_CSV)
print(json.dumps(summary,indent=2))
display(comparison)
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z:assert z.testzip() is None
os.chdir(WORK)
print('Download before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch

EXPECTED='0f81dc6ed10ab91f4f07d0c1df39b0faf6c84aebf519cbde837d803f53defa90'

relative='balanced300_to_epoch400_20260925_173543/model/last.pt'
def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
refs=[p for p in INPUTS.rglob(relative) if digest(p)==EXPECTED]
if not refs:
    dest=Path('/kaggle/working/restored_pair_epoch400')
    restored=dest/relative
    if restored.is_file() and digest(restored)==EXPECTED: refs=[restored]
    else:
        for archive in sorted(INPUTS.rglob('*.zip')):
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                if relative in z.namelist() and hashlib.sha256(z.read(relative)).hexdigest()==EXPECTED:
                    safe_extract(z,dest);refs=[dest/relative];break
assert refs, 'Attach balanced300_to_epoch400_20260925_173543_epoch400.zip (not only epoch350).'
CHECKPOINT=sorted(refs)[0]
REFERENCE=CHECKPOINT.parent.parent
DATA=Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(), 'Enable GPU.'
state=torch.load(CHECKPOINT,map_location='cpu',weights_only=True)
assert state['epoch']==state['scheduler']['last_epoch']==400
assert state['scheduler']['T_max']==500 and math.isclose(state['scheduler']['eta_min'],2.5e-7)
for k,v in dict(sampling_policy='balanced50_v1',lambda_seg=1e-4,learning_rate=1e-4,max_epoch=500,batch_size=1,workers=0,seed=3407,transpose_image=True,method='CRSDUN',input_setting='Y',input_mask='SSR').items():
    assert state['config'][k]==v,k
provenance=json.loads((REFERENCE/'continuation.json').read_text())
for f,h in provenance['source_sha256'].items(): assert digest(CODE/f)==h,f
sys.path.insert(0,str(CODE))
from training_state import identity,atomic_save
from types import SimpleNamespace
assert identity(SimpleNamespace(data_root=DATA,mask_path=CODE/'mask/mask512x512.mat'))==state['data_identity']
subprocess.run([sys.executable,'verify_balanced_sampling.py'],cwd=CODE,check=True)
subprocess.run([sys.executable,'run_public252.py','--root',str(DATA)],cwd=CODE,check=True)
print('Verified epoch400. Next-epoch LR:',state['optimizer']['param_groups'][0]['lr'])

In [ ]:
"""Derive explicit sampler-ablation seeds without altering training state."""
import copy
import torch

def equal(a,b):
    if isinstance(a,torch.Tensor): return isinstance(b,torch.Tensor) and a.dtype==b.dtype and a.shape==b.shape and torch.equal(a,b)
    if isinstance(a,dict): return isinstance(b,dict) and a.keys()==b.keys() and all(equal(a[k],b[k]) for k in a)
    if isinstance(a,(list,tuple)): return type(a)==type(b) and len(a)==len(b) and all(equal(x,y) for x,y in zip(a,b))
    return a==b

def derive(state,policy,initial_metrics):
    assert state['epoch']==400 and state['scheduler']['last_epoch']==400
    assert state['scheduler']['T_max']==500 and state['config']['sampling_policy']=='balanced50_v1'
    assert policy in ('balanced50_v1','baseline')
    seed=copy.deepcopy(state)
    seed['config']['sampling_policy']=policy
    seed['best']={'iou':initial_metrics['val_foreground_miou_all22'],'psnr':initial_metrics['val_psnr_ref1']}
    for key in state:
        if key not in ('config','best'): assert equal(state[key],seed[key]), key
    assert {k:v for k,v in seed['config'].items() if k!='sampling_policy'}=={k:v for k,v in state['config'].items() if k!='sampling_policy'}
    return seed

INITIAL={'val_foreground_miou_all22': 0.7145757598981378, 'val_psnr_ref1': 39.06867599487305}

from datetime import datetime
from IPython.display import display,FileLink
import os
if 'PAIR_RUN' not in globals():
    PAIR_RUN=Path('/kaggle/working')/('paired_sampling_epoch400_'+datetime.now().strftime('%Y%m%d_%H%M%S'))
    PAIR_RUN.mkdir(exist_ok=False)
ARMS={'balanced_control':'balanced50_v1','original_sampler':'baseline'}
seed_hashes={}
for name,policy in ARMS.items():
    dest=PAIR_RUN/'seeds'/name
    derived=derive(state,policy,INITIAL)
    if not dest.exists():
        dest.mkdir(parents=True)
        atomic_save(derived,dest/'last.pt')
        atomic_save(derived['model'],dest/'best_iou.pth')
        atomic_save(derived['model'],dest/'best_psnr.pth')
    assert equal(torch.load(dest/'last.pt',map_location='cpu',weights_only=True),derived)
    seed_hashes[name]=digest(dest/'last.pt')
    del derived
manifest={'reference_checkpoint_sha256':EXPECTED,'source_epoch':400,'end_epoch':410,
    'arms':ARMS,'seed_hashes':seed_hashes,'source_sha256':provenance['source_sha256'],
    'constants':'model, optimizer, scaler, scheduler horizon500, RNG starting state, loss1e-4, batch1,202 attempts per epoch',
    'best_weight_policy':'Both branches reset best tracking to common epoch400 weights and metrics; historical best preserved in source archive.',
    'primary_comparison':'Mean all22 foreground validation mIoU over406-410; report variability, target precision/recall and PSNR. Inspect all10 epochs; a higher best epoch alone is insufficient.',
    'scope':'Single-seed continuation sampler ablation, not a from-scratch comparison or test result.'}
(PAIR_RUN/'experiment.json').write_text(json.dumps(manifest,indent=2))
print('Experiment:',PAIR_RUN)
del state

def backup(label):
    archive=shutil.make_archive(str(PAIR_RUN)+'_'+label,'zip',root_dir=PAIR_RUN.parent,base_dir=PAIR_RUN.name)
    with zipfile.ZipFile(archive) as z:assert z.testzip() is None
    os.chdir('/kaggle/working')
    print('Download:',archive)
    display(FileLink(Path(archive).name))

def run_arm(name):
    policy=ARMS[name]
    last=PAIR_RUN/name/'model/last.pt'
    resume=last if last.is_file() else PAIR_RUN/'seeds'/name/'last.pt'
    saved=torch.load(resume,map_location='cpu',weights_only=True)
    start=int(saved['epoch']);assert 400<=start<=410
    assert saved['config']['sampling_policy']==policy
    del saved
    if start<410:
        try:
            subprocess.run([sys.executable,'-u','train.py','--data_root',str(DATA)+'/',
                '--transpose_image','--batch_size','1','--workers','0','--seed','3407',
                '--learning_rate','0.0001','--lambda_seg','0.0001','--sampling_policy',policy,
                '--max_epoch','500','--stop_after_epoch','410','--resume',str(resume),
                '--outf',str(PAIR_RUN)+'/', '--name',name],cwd=CODE,check=True)
        finally:
            backup(name)
    assert torch.load(last,map_location='cpu',weights_only=True)['epoch']==410

In [ ]:
run_arm('balanced_control')
run_arm('original_sampler')

In [ ]:
import statistics
import pandas as pd
results={};target_rows=[]
for name in ARMS:
    records=[json.loads((PAIR_RUN/name/'result'/f'epoch_{e:04d}_training.json').read_text()) for e in range(401,411)]
    assert all(r['attempted_updates']==202 for r in records)
    vals=[r['val_foreground_miou_all22'] for r in records]
    results[name]={'final':records[-1],'epochs':records,
        'best_logged_continuation_miou':max(vals),'mean_last5_miou':statistics.mean(vals[-5:]),
        'std_last5_miou':statistics.pstdev(vals[-5:]),
        'mean_last5_psnr':statistics.mean(r['val_psnr_ref1'] for r in records[-5:]),
        'actual_updates':sum(r['optimizer_updates'] for r in records),
        'amp_skips':sum(r['amp_skipped_updates'] for r in records)}
    for e in range(401,411):
        table=pd.read_csv(PAIR_RUN/name/'result'/f'epoch_{e:04d}_segmentation.csv',index_col=0)
        for cls in ['fake apple','fake avocado','fake unknown']:
            target_rows.append({'arm':name,'epoch':e,'class':cls,**{m:float(table.loc[cls,m]) for m in ['IoU','Prec','recall']}})
summary={'experiment':manifest,'arms':results}
(PAIR_RUN/'comparison_summary.json').write_text(json.dumps(summary,indent=2))
targets=pd.DataFrame(target_rows);targets.to_csv(PAIR_RUN/'target_class_metrics.csv',index=False)
for name,record in results.items():print(name,json.dumps({k:v for k,v in record.items() if k!='epochs'},indent=2))
display(targets[targets.epoch>=406].groupby(['arm','class'])[['IoU','Prec','recall']].mean()*100)
backup('complete')

In [ ]:
from pathlib import Path
import shutil, zipfile, subprocess, sys
INPUTS = Path('/kaggle/input')
CODE = Path('/kaggle/working/BTP-sampling')
def safe_extract(z, dest):
    dest = dest.resolve()
    for member in z.infolist():
        if not (dest / member.filename).resolve().is_relative_to(dest):
            raise ValueError('Unsafe ZIP member')
        if (member.external_attr >> 16) & 0o170000 == 0o120000:
            raise ValueError('ZIP symlinks are not allowed')
    z.extractall(dest)
# Identify this evaluator by its actual feature, not a shared filename.
import tempfile
marker = 'Single balanced-sampling arm against the archived epoch101-110 control'
def is_audit_source(path):
    return path.is_file() and marker in path.read_text()
if not is_audit_source(CODE / 'run_sampling_experiment.py'):
    sources = [p.parent for p in INPUTS.rglob('run_sampling_experiment.py') if is_audit_source(p)]
    if sources:
        shutil.copytree(sorted(sources)[0], CODE, dirs_exist_ok=True)
    else:
        matches = []
        archives = list(INPUTS.rglob('*.zip'))
        for archive in archives:
            if not zipfile.is_zipfile(archive): continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if member.endswith('/run_sampling_experiment.py') and marker.encode() in z.read(member):
                        matches.append((archive, member))
        if not matches:
            print('ZIP inputs found:', [str(p) for p in archives])
            raise FileNotFoundError('Updated audit code is not attached. Add BTP-code-sampling.zip, then rerun this cell.')
        archive, member = sorted(matches, key=lambda x: str(x[0]))[0]
        print('Using audit code:', archive)
        with tempfile.TemporaryDirectory(prefix='weak_audit_code_', dir='/kaggle/working') as tmp:
            staging = Path(tmp)
            with zipfile.ZipFile(archive) as z: safe_extract(z, staging)
            shutil.copytree((staging / member).parent, CODE, dirs_exist_ok=True)
assert is_audit_source(CODE / 'run_sampling_experiment.py'), 'Audit evaluator not found after extraction.'
import json, hashlib, math
import torch

EXPECTED_410='d9cc528d220f7918989a643d8d57c1c2f4811a74fb9122cdff54569ef93bac8a'
HISTORY={'checkpoint_hashes': {'last.pt': '0f81dc6ed10ab91f4f07d0c1df39b0faf6c84aebf519cbde837d803f53defa90', 'best_iou.pth': '89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c', 'best_psnr.pth': '10a193a52834b1813fb856df6b3b5992f2f62cd19ad09414ae04447acedb9133'}, 'best_iou': {'epoch': 278, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11283155, 47213, 47095, 129119, 174675, 62551, 38383, 151141, 165696, 89935, 71339, 60422, 33207, 227434, 153331, 175570, 27755, 65024, 51386, 79550, 56302, 8225, 39764], 'crops_with_class': [202, 29, 23, 37, 45, 20, 17, 27, 33, 36, 25, 22, 11, 55, 34, 24, 24, 18, 24, 34, 24, 11, 19], 'targeted_crops_by_class': [0, 3, 6, 6, 5, 3, 6, 4, 5, 4, 8, 7, 6, 2, 5, 5, 4, 5, 6, 4, 6, 4, 3], 'sampled_scene_counts': [1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 3, 0, 1, 1, 1, 0, 1, 3, 1, 1, 0, 0, 0, 2, 2, 0, 1, 1, 1, 1, 0, 0, 1, 2, 0, 1, 0, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 2, 1, 0, 2, 0, 1, 1, 2, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 2, 0, 2, 1, 3, 2, 2, 1, 1, 2, 4, 1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 3, 1, 1, 3, 0, 1, 0, 3, 0, 1, 3, 1, 1, 2, 3, 3, 1, 1, 0, 3, 1, 0, 1, 3, 1, 1, 0, 3, 4, 2, 0, 1, 2, 0, 1, 3, 2, 1, 0, 1, 0, 0, 0, 2, 1, 2, 0, 0, 3, 1, 0, 3, 1, 0, 0, 1, 2, 3, 1, 0, 0, 2, 0, 4, 2, 1], 'learning_rate': 4.1704431944952346e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0006899012645734197, 'train_segmentation_loss': 0.3116034334617676, 'val_foreground_miou_all22': 0.7862424401936461, 'val_psnr_ref1': 38.36915969848633, 'elapsed_seconds': 317.5734043121338, 'peak_cuda_allocated_gib': 7.509799957275391}, 'best_psnr': {'epoch': 398, 'scheduler_horizon': 500, 'lambda_rec': 1, 'lambda_seg': 0.0001, 'sampling_policy': 'balanced50_v1', 'class_pixels_seen': [11258028, 52003, 71103, 106599, 148359, 78870, 60312, 174631, 155758, 80633, 59873, 24017, 29595, 273997, 155726, 157205, 26182, 72694, 86353, 48206, 46898, 12224, 59006], 'crops_with_class': [202, 30, 30, 29, 40, 23, 21, 31, 41, 32, 25, 9, 15, 65, 39, 24, 24, 22, 35, 28, 20, 13, 27], 'targeted_crops_by_class': [0, 4, 5, 6, 6, 3, 5, 7, 2, 10, 5, 3, 2, 4, 6, 4, 5, 3, 9, 4, 5, 5, 4], 'sampled_scene_counts': [1, 0, 1, 0, 1, 2, 1, 2, 1, 1, 0, 1, 0, 2, 2, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, 0, 2, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 1, 2, 2, 3, 3, 0, 0, 1, 1, 3, 2, 1, 2, 1, 1, 3, 3, 1, 4, 2, 1, 0, 1, 4, 1, 3, 1, 1, 6, 2, 2, 1, 3, 0, 2, 1, 0, 1, 1, 1, 0, 1, 1, 3, 2, 1, 0, 0, 3, 1, 2, 3, 2, 2, 0, 2, 1, 2, 2, 2, 0, 1, 2, 1, 0, 2, 0, 3, 0, 1, 0], 'learning_rate': 1.0335002328013762e-05, 'attempted_updates': 202, 'optimizer_updates': 202, 'amp_skipped_updates': 0, 'train_reconstruction_loss': 0.0005872207170751148, 'train_segmentation_loss': 0.28119397727717266, 'val_foreground_miou_all22': 0.6764957873477285, 'val_psnr_ref1': 39.16609451293945, 'elapsed_seconds': 332.0243864059448, 'peak_cuda_allocated_gib': 7.511264801025391}}

def digest(p): return hashlib.sha256(p.read_bytes()).hexdigest()
# Match actual file hashes so multiple attached backups do not select the wrong state.
def locate(relative,expected_hash,label):
    for p in sorted(INPUTS.rglob(relative)):
        if digest(p)==expected_hash:return p
    dest=Path('/kaggle/working')/('restore_'+label)
    restored=dest/relative
    if restored.is_file() and digest(restored)==expected_hash:return restored
    for archive in sorted(INPUTS.rglob('*.zip')):
        if not zipfile.is_zipfile(archive):continue
        with zipfile.ZipFile(archive) as z:
            if relative in z.namelist() and hashlib.sha256(z.read(relative)).hexdigest()==expected_hash:
                safe_extract(z,dest)
                return dest/relative
    raise FileNotFoundError('Attach the required '+label+' backup ZIP.')
PARENT410=locate('paired_sampling_epoch400_20260928_170349/balanced_control/model/last.pt',EXPECTED_410,'paired_epoch410').parent
PARENT400=locate('balanced300_to_epoch400_20260925_173543/model/last.pt',HISTORY['checkpoint_hashes']['last.pt'],'historical_epoch400').parent
DATA=Path('/kaggle/input/datasets/arnavnigamd/btp-data/public252')
assert torch.cuda.is_available(),'Enable GPU.'
state=torch.load(PARENT410/'last.pt',map_location='cpu',weights_only=True)
assert state['epoch']==state['scheduler']['last_epoch']==410
assert state['scheduler']['T_max']==500 and math.isclose(state['scheduler']['eta_min'],2.5e-7)
for k,v in dict(sampling_policy='balanced50_v1',lambda_seg=1e-4,learning_rate=1e-4,max_epoch=500,batch_size=1,workers=0,seed=3407,transpose_image=True,method='CRSDUN',input_setting='Y',input_mask='SSR').items():assert state['config'][k]==v,k
provenance=json.loads((PARENT410.parents[1]/'experiment.json').read_text())
for f,h in provenance['source_sha256'].items():assert digest(CODE/f)==h,f
sys.path.insert(0,str(CODE))
from training_state import identity,atomic_save
from types import SimpleNamespace
assert identity(SimpleNamespace(data_root=DATA,mask_path=CODE/'mask/mask512x512.mat'))==state['data_identity']
subprocess.run([sys.executable,'run_public252.py','--root',str(DATA)],cwd=CODE,check=True)
print('Verified balanced-control epoch410. Saved next LR:',state['optimizer']['param_groups'][0]['lr'])

In [ ]:
import torch

assert "PARENT410" in globals(), "Run the setup cell first."
assert digest(PARENT410 / "last.pt") == EXPECTED_410

state = torch.load(
    PARENT410 / "last.pt",
    map_location="cpu",
    weights_only=True,
)
assert state["epoch"] == 410
print("Epoch-410 state reloaded.")

In [ ]:
import copy

def restore_historical_best(state,history):
    derived=copy.deepcopy(state)
    selected={}
    for metric,record,filename in [('iou','best_iou','best_iou.pth'),('psnr','best_psnr','best_psnr.pth')]:
        field='val_foreground_miou_all22' if metric=='iou' else 'val_psnr_ref1'
        historical_value=history[record][field]
        use_history=historical_value>state['best'][metric]
        selected[filename]='historical' if use_history else 'current'
        derived['best'][metric]=max(state['best'][metric],historical_value)
    return derived,selected

from datetime import datetime
from IPython.display import display,FileLink
import os
if 'CONT410_RUN' not in globals():
    CONT410_RUN=Path('/kaggle/working')/('balanced410_to_epoch500_'+datetime.now().strftime('%Y%m%d_%H%M%S'))
    CONT410_RUN.mkdir(exist_ok=False)
SEED=CONT410_RUN/'initial_state'
SEED.mkdir(exist_ok=True)
derived,selected=restore_historical_best(state,HISTORY)
for filename,source in selected.items():
    source_path=(PARENT400 if source=='historical' else PARENT410)/filename
    assert source_path.is_file()
    if source=='historical':assert digest(source_path)==HISTORY['checkpoint_hashes'][filename]
    dest=SEED/filename
    if dest.exists():assert digest(dest)==digest(source_path)
    else:shutil.copy2(source_path,dest)
if not (SEED/'last.pt').exists():atomic_save(derived,SEED/'last.pt')
CHECKPOINT=SEED/'last.pt'
assert torch.load(CHECKPOINT,map_location='cpu',weights_only=True)['best']==derived['best']
manifest={'reference_checkpoint_sha256':EXPECTED_410,'derived_checkpoint_sha256':digest(CHECKPOINT),
    'source_epoch':410,'target_epoch':500,'backup_epochs':[450,500],
    'sampling_policy':'balanced50_v1','lambda_seg':1e-4,
    'source_sha256':provenance['source_sha256'],
    'bookkeeping_change':'Restore the better historical/current best metrics and weights; all other state preserved.',
    'selected_best_sources':selected,'restored_best':derived['best'],
    'note':'Finish fixed500-epoch schedule; not a new method or test result.'}
(CONT410_RUN/'continuation.json').write_text(json.dumps(manifest,indent=2))
shutil.copy2(CODE/'public252-v1.json',CONT410_RUN/'dataset_protocol.json')
print('Restored best tracking:',derived['best'],selected)
del state,derived

def saved_epoch(path):
    state = torch.load(path, map_location='cpu', weights_only=True)
    epoch = int(state['epoch'])
    del state
    return epoch

def backup_run(target):
    last = CONT410_RUN / 'model/last.pt'
    epoch = saved_epoch(last) if last.is_file() else None
    label = f'epoch{epoch}' if epoch is not None else 'incomplete'
    base = CONT410_RUN.parent / (CONT410_RUN.name + '_' + label)
    archive = shutil.make_archive(str(base), 'zip', root_dir=CONT410_RUN.parent, base_dir=CONT410_RUN.name)
    with zipfile.ZipFile(archive) as z:
        assert z.testzip() is None, 'ZIP integrity check failed'
        missing = [f'{CONT410_RUN.name}/model/{f}' for f in ['last.pt','best_iou.pth','best_psnr.pth']
            if f'{CONT410_RUN.name}/model/{f}' not in z.namelist()]
    os.chdir('/kaggle/working')
    print('Saved epoch:', epoch, '| block target:', target, '| Missing checkpoint files:', missing)
    print('Download:', archive)
    display(FileLink(Path(archive).name))
    return epoch

def continue_to(target):
    assert target in (450, 500)
    last = CONT410_RUN / 'model/last.pt'
    resume = last if last.is_file() else CHECKPOINT
    start = saved_epoch(resume)
    if start >= target:
        print('This block is already complete; creating its current backup.')
        backup_run(target)
        return
    command = [sys.executable, '-u', 'train.py', '--data_root', str(DATA) + '/',
        '--transpose_image', '--batch_size', '1', '--workers', '0', '--seed', '3407',
        '--learning_rate', '0.0001', '--lambda_seg', '0.0001', '--sampling_policy', 'balanced50_v1',
        '--max_epoch', '500', '--stop_after_epoch', str(target), '--resume', str(resume),
        '--outf', str(CONT410_RUN.parent) + '/', '--name', CONT410_RUN.name]
    try:
        subprocess.run(command, cwd=CODE, check=True)
    finally:
        segments = CONT410_RUN / 'segments'
        segments.mkdir(exist_ok=True)
        for filename in ['run_resume.json','source_resume.diff']:
            source = CONT410_RUN / 'model' / filename
            if source.is_file():
                shutil.copy2(source, segments / (f'from{start}_to{target}_' + filename))
        backup_run(target)
    assert saved_epoch(last) == target, 'Block did not reach its target epoch.'
    print(f'Epoch{target} completed. Download the full backup before stopping the session.')
print('Continuation folder:', CONT410_RUN)

In [ ]:
continue_to(450)

In [ ]:
continue_to(500)

In [ ]:
import statistics
records=[json.loads(p.read_text()) for p in sorted((CONT410_RUN/'result').glob('*_training.json'))]
assert [r['epoch'] for r in records]==list(range(411,501)),'The run has not completed90 new epochs.'
for start,end in [(411,425),(426,450),(451,475),(476,500)]:
    values=[100*r['val_foreground_miou_all22'] for r in records if start<=r['epoch']<=end]
    print(f'Epochs{start}-{end}: mean mIoU={statistics.mean(values):.2f}%, std={statistics.pstdev(values):.2f} points')
print('Final:',json.dumps(records[-1],indent=2))
print('New successful updates:',sum(r['optimizer_updates'] for r in records))
print('New AMP skips:',sum(r['amp_skipped_updates'] for r in records))
print('The500-epoch reference schedule is complete. Download the final ZIP; do not run the test split yet.')

In [ ]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

In [ ]:
NAME='epoch441_validation_audit_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f')
RUN=WORK/NAME
subprocess.run([sys.executable,'test.py','--data_root',str(DATA),
    '--transpose_image','--eval_split','val','--pretrained_model_path',str(CHECKPOINT),
    '--outf',str(WORK),'--name',NAME,'--workers','0','--save_segmentation'],
    cwd=CODE,check=True)
OUT=RUN/'evaluation_val'
print('Evaluation complete:',OUT)

In [ ]:
EXPECTED_MIOU=0.7876837070566084
EXPECTED_PSNR=39.006845703125

import numpy as np
import pandas as pd
from IPython.display import display, FileLink
meta=json.loads((OUT/'evaluation.json').read_text())
assert meta['status']=='completed' and meta['split']=='val' and meta['scene_count']==25
assert meta['checkpoint_sha256']==EXPECTED
assert len(set(meta['scenes']))==25
cm=np.load(OUT/'confusion_matrix.npy')
parts=[np.load(OUT/(scene+'_confusion.npy')) for scene in meta['scenes']]
assert np.array_equal(sum(parts),cm), 'Per-scene confusion totals differ.'
assert len(list(OUT.glob('*_preview.png')))==25
assert not list(OUT.glob('*_hsi.npy'))
seg=pd.read_csv(OUT/'segmentation.csv',index_col=0)
rec=pd.read_csv(OUT/'reconstruction.csv')
miou=float(seg.loc['total(-bg)','IoU'])
psnr=float(rec.iloc[0]['PSNR'])
summary=dict(checkpoint_epoch=441,validation_scenes=25,foreground_miou=miou,
    psnr_ref1=psnr,logged_miou=EXPECTED_MIOU,logged_psnr=EXPECTED_PSNR,
    miou_difference=miou-EXPECTED_MIOU,psnr_difference=psnr-EXPECTED_PSNR,
    matches_logged_metrics=bool(abs(miou-EXPECTED_MIOU)<1e-5 and abs(psnr-EXPECTED_PSNR)<1e-3),
    scope='Independent full validation evaluation; no test performance or new training.')
(RUN/'audit_summary.json').write_text(json.dumps(summary,indent=2))
(RUN/'evaluator_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in
    ['test.py','dataset.py','utils.py','public252-v1.json']},indent=2))
print(json.dumps(summary,indent=2))
display(seg)
display(rec)

import io
BASELINE_CSV=',IoU,F1,Prec,recall,Acc\n"bg,",0.9956056857102029,0.9977480073007325,0.9965542331594534,0.9990448847883433,0.9958021545410156\nreal potato,0.9309118500011194,0.9641699818594597,0.9956533415423344,0.9347105211080015,0.9999169921875\nfake potato,0.9522338696266445,0.9754825724698661,0.9823704124390311,0.9687892549478581,0.999964599609375\nreal apple,0.7667310698808576,0.86791656541023,0.9908069402405689,0.7722246759300102,0.999189453125\nfake apple,0.6043422511191895,0.7533351644919333,0.9394433318876814,0.6288393120399316,0.9984455871582031\nreal orange,0.9262720557716387,0.9616751181814689,0.9961533565435742,0.9295970249004514,0.9999024963378906\nfake orange,0.9395745507163982,0.968796030785346,0.9631307228319249,0.9746295652135722,0.999820556640625\nreal grape,0.633692737291463,0.7757318358626515,0.9847070619059142,0.6399912253161498,0.9992276000976562\nfake grape,0.903082134230324,0.949023210711403,0.9530405084725043,0.9451387990548249,0.9996247863769532\nreal lemon,0.5693110254280307,0.725507126786873,0.6111654314946624,0.8926252805423879,0.9992063903808593\nfake lemon,0.840714331095886,0.9134156552707563,0.9981191673239364,0.8420483170425653,0.9996624755859375\nreal avocado,0.9437285770065472,0.9709997714735892,0.99296377221617,0.9500820862055487,0.9999473571777344\nfake avocado,0.6883845379525112,0.8153874257399899,0.9998147962997259,0.6884723197083357,0.9996270751953125\nreal pepper,0.9032760667551863,0.9491303105984753,0.9317314223018788,0.967295173672221,0.9996211242675781\nfake pepper,0.900210338405034,0.9474349533973953,0.9640254341856007,0.9315024586678032,0.9997538757324219\nreal plant,0.8239757843089116,0.9034442395536414,0.9232679952816458,0.8845496691412166,0.9981098937988281\nfake plant,0.8616340199240582,0.9256251271314639,0.9794564309981504,0.8774923144652547,0.9998878479003906\nreal banana,0.5656761794155748,0.7225490193781943,0.9237762879397793,0.5933722627096818,0.9989762878417969\nfake banana,0.7485354041636234,0.8561356100749404,0.8759871485204622,0.8372594489278414,0.9994825744628906\nreal onion,0.7189954833355378,0.8364804440637529,0.7517166991824868,0.9429150322088324,0.9996670532226563\nfake onion,0.9352912861678297,0.9665138489307946,0.9866498492027745,0.9472792999448778,0.9999586486816406\nreal unknown,0.9121494474626685,0.954006635209248,0.9779558138320829,0.9312976210593873,0.9999856567382812\nfake unknown,0.2286106842011801,0.3721088184324781,0.24403452223142932,0.7834117931290874,0.9977726745605469\ntotal,0.7953451899987137,0.8727224988310731,0.9114141165232076,0.8635899278575733,0.9992849200704824\ntotal(-bg),0.7862424401936461,0.8670395211733616,0.90754411122156,0.8574328843607201,0.9994432275945492\n'
BASELINE_META={'status': 'completed', 'split': 'val', 'scope': 'full split', 'checkpoint_sha256': '89daa7d800ec64648d591f03c64e5162c5bbe52714dc5e43a168e01fe37d7c5c', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'reference_amplitude': 1.0, 'seed': 3407, 'torch': '2.10.0+cu128', 'gpu': 'Tesla T4', 'config': {'data_root': '/kaggle/input/datasets/arnavnigamd/btp-data/public252', 'pretrained_model_path': '/kaggle/input/datasets/arnavnigamd/checkpoint12/balanced250_to_epoch300_20260924_074129/model/best_iou.pth', 'eval_split': 'val', 'transpose_image': True, 'outf': '/kaggle/working', 'name': 'epoch278_validation_audit_20260927_164048_773155', 'workers': 0, 'mask_path': '/kaggle/input/datasets/arnavnigamd/btp-code-8/BTP/mask/mask512x512.mat', 'limit': None, 'save_predictions': False, 'save_segmentation': True, 'batch_size': 1}, 'scene_count': 25, 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050']}
assert set(meta['scenes'])==set(BASELINE_META['scenes']), 'Validation scene membership changed.'
for field in ['protocol_sha256','mask_sha256','reference_amplitude']:
    assert meta[field]==BASELINE_META[field], f'Evaluation protocol changed: {field}'
baseline=pd.read_csv(io.StringIO(BASELINE_CSV),index_col=0)
assert list(seg.index)==list(baseline.index), 'Class ordering changed.'
comparison=pd.DataFrame({'epoch278_IoU_percent':100*baseline['IoU'],
    'epoch441_IoU_percent':100*seg['IoU'],
    'change_points':100*(seg['IoU']-baseline['IoU']),
    'epoch441_precision_percent':100*seg['Prec'],
    'epoch441_recall_percent':100*seg['recall']})
comparison.to_csv(RUN/'comparison_with_epoch278.csv')
(RUN/'epoch278_segmentation_reference.csv').write_text(BASELINE_CSV)
print('Per-class comparison; percentage-point changes, not statistical significance:')
display(comparison)

# Save results even if the comparison differs, so the difference can be investigated.
archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
with zipfile.ZipFile(archive) as z: assert z.testzip() is None
os.chdir(WORK)
print('Download this archive before stopping:',archive.name,archive.stat().st_size,'bytes')
display(FileLink(archive.name))
if not summary['matches_logged_metrics']:
    print('Metrics differ from the training record: share this ZIP before further training.')

**## Now new model**

In [ ]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

In [ ]:
SCRIPT='"""Five-stage validation diagnostic; frozen model, no optimization."""\nfrom pathlib import Path\nimport argparse,hashlib,json,sys,math\nimport numpy as np\nimport torch\nfrom scipy.stats import rankdata\n\ndef translate_mask(mask,dx):\n    assert mask.ndim==2 and abs(dx)<mask.shape[1]\n    out=torch.zeros_like(mask)\n    if dx==0:return mask.clone()\n    if dx>0:out[:,dx:]=mask[:,:-dx]\n    else:out[:,:dx]=mask[:,-dx:]\n    return out\n\ndef build_phi(mask,bands=28,step=2):\n    h,w=mask.shape\n    phi=mask.new_zeros((1,bands,h,w+(bands-1)*step))\n    for c in range(bands):phi[0,c,:,step*c:step*c+w]=mask\n    return phi\n\ndef measure(x,phi,step=2):\n    b,c,h,w=x.shape\n    shifted=x.new_zeros((b,c,h,w+(c-1)*step))\n    for k in range(c):shifted[:,k,:,step*k:step*k+w]=x[:,k]\n    return (shifted*phi).sum(1)\n\ndef auc(score,event):\n    score=np.asarray(score);event=np.asarray(event,dtype=bool)\n    n1=int(event.sum());n0=int((~event).sum())\n    if not n1 or not n0:return None\n    ranks=rankdata(score,method=\'average\')\n    return float((ranks[event].sum()-n1*(n1+1)/2)/(n1*n0))\n\ndef transition_rows(prev,current,truth,signals,scene,condition,stage):\n    rows=[]\n    for group,region in [(\'foreground\',truth>0),(\'background\',truth==0)]+[(f\'class_{c}\',truth==c) for c in range(1,23)]:\n        pc=prev==truth;cc=current==truth;eligible=region&pc;event=~cc\n        row={\'scene\':scene,\'condition\':condition,\'to_stage\':stage,\'group\':group,\n             \'pixels\':int(region.sum()),\'previous_correct\':int(eligible.sum()),\n             \'correct_to_wrong\':int((eligible&event).sum()),\n             \'wrong_to_correct\':int((region&~pc&cc).sum())}\n        for name,score in signals.items():\n            if score is None:continue\n            vals=score[eligible];bad=event[eligible]\n            row[name+\'_auc_next_error_given_previous_correct\']=auc(vals,bad)\n            for tag,select in [(\'flipped\',bad),(\'retained\',~bad)]:\n                row[name+\'_mean_\'+tag]=float(vals[select].mean()) if select.any() else None\n        rows.append(row)\n    return rows\n\ndef sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()\n\ndef main():\n    p=argparse.ArgumentParser()\n    for arg in [\'code\',\'data\',\'checkpoint\',\'out\',\'reference\']:p.add_argument(\'--\'+arg,type=Path,required=True)\n    a=p.parse_args();sys.path.insert(0,str(a.code))\n    from dataset import evaluation_loader,get_class_names\n    from utils import init_mask,init_meas,Metrics_Rec,Metrics_Seg,set_seed\n    from models import model_generator\n    from run_public252 import validate\n    from scipy.io import loadmat\n    ref=json.loads(a.reference.read_text())\n    assert sha(a.checkpoint)==ref[\'checkpoint_sha256\']\n    spec_path=a.code/\'public252-v1.json\';mask_path=a.code/\'mask/mask512x512.mat\'\n    assert sha(spec_path)==ref[\'protocol_sha256\'] and sha(mask_path)==ref[\'mask_sha256\']\n    validate(a.data,json.loads(spec_path.read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(parents=True,exist_ok=False)\n    set_seed(3407)\n    loader=evaluation_loader(a.data,\'val\',0,True)\n    assert sorted(map(str,loader.dataset.names))==sorted(ref[\'scenes\']) and len(loader)==25\n    model=model_generator(\'CRSDUN\',28,23,str(a.checkpoint));model.eval()\n    phi,nominal=init_mask(str(mask_path),\'SSR\',1,28)\n    physical=torch.as_tensor(loadmat(mask_path)[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    assert torch.equal(build_phi(physical),phi)\n    assert torch.equal(translate_mask(physical,0),physical)\n    nominal_digest=hashlib.sha256(phi.cpu().numpy().tobytes()).hexdigest()\n    manifest={\'status\':\'running\',\'checkpoint_sha256\':sha(a.checkpoint),\'checkpoint_epoch\':441,\n        \'protocol_sha256\':sha(spec_path),\'mask_sha256\':sha(mask_path),\'scenes\':ref[\'scenes\'],\n        \'conditions\':{\'clean\':0,\'mask_plus1\':1,\'mask_minus1\':-1},\'torch\':str(torch.__version__),\n        \'gpu\':torch.cuda.get_device_name(0),\'script_sha256\':sha(__file__),\n        \'scope\':\'Frozen-model validation diagnostics, all five stages. Model always receives nominal SSR mask tuple.\',\n        \'residual_score\':\'Mean absolute nominal backprojected residual across28 bands, divided by RMS measurement plus1e-8.\',\n        \'stability_score\':\'Normalized Jensen-Shannon divergence between consecutive stage softmax distributions; unavailable at stage1.\',\n        \'auc_scope\':\'Per-scene descriptive next-stage error discrimination conditional on previous correctness; foreground/background and class separated. No independent-pixel significance claims.\',\n        \'caveat\':\'Synthetic zero-filled horizontal mask translation, not calibrated real hardware. Signals do not certify correctness; no causal feedback intervention.\'}\n    (a.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    import pandas as pd\n    overall=[]\n    with torch.inference_mode():\n      for condition,dx in manifest[\'conditions\'].items():\n        cond=a.out/condition;cond.mkdir()\n        acquisition=build_phi(translate_mask(physical,dx))\n        if dx:assert not torch.equal(acquisition,phi)\n        rec=[Metrics_Rec() for _ in range(5)];seg=[Metrics_Seg(23,get_class_names()) for _ in range(5)]\n        scene_records=[];transitions=[]\n        for index,sample in enumerate(loader):\n          scene=str(loader.dataset.names[index]);target=sample[\'image\'].float().cuda()\n          truth=sample[\'label\'].numpy()[0]\n          y=init_meas(target,acquisition,\'Y\')\n          if index==0:assert torch.allclose(measure(target,acquisition),y,rtol=1e-6,atol=1e-6)\n          xs,logits=model(y,nominal)\n          assert len(xs)==len(logits)==5\n          gt_cpu=target.cpu();previous_pred=None;previous_prob=None;previous_signals=None\n          rms=float(y.square().mean().sqrt())+1e-8\n          for k,(x,l) in enumerate(zip(xs,logits)):\n            assert x.shape==target.shape and l.shape==(1,23,*truth.shape)\n            assert torch.isfinite(x).all() and torch.isfinite(l).all()\n            x_cpu=x.float().cpu()\n            one=Metrics_Rec();one.add_batch(gt_cpu,x_cpu)\n            for field in [\'psnr\',\'ssim\',\'mse\',\'count\']:setattr(rec[k],field,getattr(rec[k],field)+getattr(one,field))\n            pred=l.argmax(1).cpu().numpy()[0]\n            seg[k].add_batch(truth[None],pred[None])\n            hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=23*23).reshape(23,23)\n            np.save(cond/f\'{scene}_stage{k+1}_confusion.npy\',hist)\n            prob=l.float().softmax(1).cpu().numpy()[0]\n            entropy=-(prob*np.log(np.maximum(prob,1e-12))).sum(0)/math.log(23)\n            instability=None\n            if previous_prob is not None:\n                mid=(prob+previous_prob)/2\n                instability=(.5*(prob*(np.log(np.maximum(prob,1e-12))-np.log(np.maximum(mid,1e-12)))).sum(0)+.5*(previous_prob*(np.log(np.maximum(previous_prob,1e-12))-np.log(np.maximum(mid,1e-12)))).sum(0))/math.log(2)\n            residual=y.unsqueeze(1)-model.mul_Phif(phi,x)\n            residual_map=model.mul_PhiTg(phi,residual).abs().mean(1)[0].cpu().numpy()/rms\n            signals={\'entropy\':entropy,\'nominal_residual\':residual_map,\'instability\':instability}\n            record={\'scene\':scene,\'condition\':condition,\'stage\':k+1,**one.get_table().iloc[0].to_dict(),\n                    \'normalized_measurement_residual_rms\':float(residual.square().mean().sqrt())/rms}\n            for region_name,region in [(\'foreground\',truth>0),(\'background\',truth==0)]:\n                for name,score in signals.items():\n                    if score is not None:record[name+\'_\'+region_name+\'_mean\']=float(score[region].mean()) if region.any() else None\n            scene_records.append(record)\n            if previous_pred is not None:transitions+=transition_rows(previous_pred,pred,truth,previous_signals,scene,condition,k+1)\n            previous_pred,previous_prob,previous_signals=pred,prob,signals\n          del xs,logits,target,gt_cpu,x,x_cpu,l,prob,previous_prob,previous_signals,residual\n          print(f\'{condition}: {index+1}/25 scenes, five stages\',flush=True)\n        assert hashlib.sha256(phi.cpu().numpy().tobytes()).hexdigest()==nominal_digest\n        pd.DataFrame(scene_records).to_csv(cond/\'per_scene_stage_metrics.csv\',index=False)\n        pd.DataFrame(transitions).to_csv(cond/\'stage_transitions_and_signals.csv\',index=False)\n        for k in range(5):\n            table=seg[k].get_table();table.to_csv(cond/f\'stage{k+1}_segmentation.csv\')\n            rec[k].get_table().to_csv(cond/f\'stage{k+1}_reconstruction.csv\',index=False)\n            np.save(cond/f\'stage{k+1}_aggregate_confusion.npy\',seg[k].confusion_matrix)\n            summed=sum(np.load(cond/f\'{s}_stage{k+1}_confusion.npy\') for s in ref[\'scenes\'])\n            assert np.array_equal(summed,seg[k].confusion_matrix)\n            overall.append({\'condition\':condition,\'stage\':k+1,\'foreground_miou_all22\':float(table.loc[\'total(-bg)\',\'IoU\']),**rec[k].get_table().iloc[0].to_dict()})\n        pd.DataFrame(overall).to_csv(a.out/\'stage_summary.csv\',index=False)\n        if condition==\'clean\':\n            final=overall[-1]\n            check={\'miou_difference\':final[\'foreground_miou_all22\']-ref[\'miou\'],\'psnr_difference\':final[\'PSNR\']-ref[\'psnr\']}\n            check[\'passed\']=abs(check[\'miou_difference\'])<1e-6 and abs(check[\'psnr_difference\'])<1e-4\n            (a.out/\'clean_equivalence.json\').write_text(json.dumps(check,indent=2))\n            assert check[\'passed\'], \'Clean final-stage reproduction failed; stopping before stresses.\'\n    manifest[\'status\']=\'completed\';(a.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    print(pd.DataFrame(overall).to_string(index=False),flush=True)\n\nif __name__==\'__main__\':main()\n'
TEST_SCRIPT="import numpy as np\nimport torch\nfrom stage_audit import translate_mask,build_phi,measure,transition_rows,auc\nmask=torch.tensor([[1.,2.,3.,4.],[5.,6.,7.,8.]])\noriginal=mask.clone()\nassert torch.equal(translate_mask(mask,1),torch.tensor([[0.,1.,2.,3.],[0.,5.,6.,7.]]))\nassert torch.equal(translate_mask(mask,-1),torch.tensor([[2.,3.,4.,0.],[6.,7.,8.,0.]]))\nassert torch.equal(translate_mask(mask,0),mask) and torch.equal(mask,original)\nx=torch.arange(24,dtype=torch.float32).reshape(1,3,2,4)\nfor dx in [0,1,-1]:\n shifted=translate_mask(mask,dx);phi=build_phi(shifted,bands=3)\n y=measure(x,phi);expected=torch.zeros(1,2,8)\n for c in range(3):expected[:,:,2*c:2*c+4]+=x[:,c]*shifted\n assert torch.equal(y,expected)\nassert auc([.1,.2,.8,.9],[0,0,1,1])==1\nassert auc([.5,.5],[0,1])==.5\nassert auc([.5,.7],[0,0]) is None\ntruth=np.array([[1,1],[0,0]]);prev=np.array([[1,1],[0,1]]);current=np.array([[2,1],[0,0]])\nrows=transition_rows(prev,current,truth,{'entropy':np.array([[.9,.1],[.2,.3]]),'instability':None},'s','clean',2)\nfg=next(r for r in rows if r['group']=='foreground');bg=next(r for r in rows if r['group']=='background')\nassert fg['correct_to_wrong']==1 and fg['previous_correct']==2\nassert fg['entropy_auc_next_error_given_previous_correct']==1\nassert bg['wrong_to_correct']==1\nassert 'instability_auc_next_error_given_previous_correct' not in fg\nprint('PASS: zero-filled mask shifts, physical-mask measurement construction, unchanged mask, AUROC ties/degenerate cases, and foreground/background transition accounting.')\n"
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}

RUN=WORK/('stage_reliability_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
(RUN/'stage_audit.py').write_text(SCRIPT)
(RUN/'verify_stage_audit.py').write_text(TEST_SCRIPT)
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'source_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in ['models/CRSDUN.py','dataset.py','utils.py','public252-v1.json']},indent=2))
subprocess.run([sys.executable,str(RUN/'verify_stage_audit.py')],cwd=RUN,check=True)
print('Output folder:',RUN)

In [ ]:
from IPython.display import display,FileLink
try:
    subprocess.run([sys.executable,'-u',str(RUN/'stage_audit.py'),
        '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
        '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json')],cwd=CODE,check=True)
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z:assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

In [ ]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed','Partial run: share the ZIP and error.'
assert json.loads((RUN/'results/clean_equivalence.json').read_text())['passed']
summary=pd.read_csv(RUN/'results/stage_summary.csv')
summary['foreground_miou_percent']=100*summary['foreground_miou_all22']
display(summary[['condition','stage','foreground_miou_percent','PSNR','SSIM','MSE']])
print('Completed. Share the ZIP. Stage changes are descriptive and do not alone establish harmful feedback or a causal mechanism.')

In [ ]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

In [ ]:
SCRIPT='"""Frozen validation: paired nominal/matched operators under synthetic mask mixing."""\nfrom pathlib import Path\nimport argparse\nimport hashlib\nimport json\nimport time\nimport numpy as np\nimport torch\n\nALPHAS = (0.05, 0.10, 0.25, 1.0)\n\ndef sha(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\ndef tensor_sha(x):\n    return hashlib.sha256(x.detach().cpu().contiguous().numpy().tobytes()).hexdigest()\n\ndef mix_mask(mask, dx, alpha):\n    assert mask.ndim == 2 and dx in (-1, 1) and 0 <= alpha <= 1\n    shifted = torch.zeros_like(mask)\n    if dx == 1:\n        shifted[:, 1:] = mask[:, :-1]\n    else:\n        shifted[:, :-1] = mask[:, 1:]\n    return (1-alpha)*mask + alpha*shifted\n\ndef make_operator(mask, bands=28, step=2):\n    h, w = mask.shape\n    phi = mask.new_zeros((1, bands, h, w+(bands-1)*step))\n    for c in range(bands):\n        phi[0, c, :, step*c:step*c+w] = mask\n    back = torch.stack([phi[:, c, :, step*c:step*c+w] for c in range(bands)], dim=1)\n    energy = phi.square().sum(1, keepdim=True)\n    energy = torch.where(energy == 0, torch.ones_like(energy), energy)\n    return back, phi, energy\n\ndef measure(x, phi, step=2):\n    b, c, h, w = x.shape\n    y = x.new_zeros((b, h, phi.shape[-1]))\n    for k in range(c):\n        y[:, :, step*k:step*k+w] += x[:, k]*phi[:, k, :, step*k:step*k+w]\n    return y\n\ndef relative_error(a, b):\n    return float(torch.linalg.vector_norm(a-b)/torch.linalg.vector_norm(b).clamp_min(1e-12))\n\ndef main():\n    import sys\n    p = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\'):\n        p.add_argument(\'--\'+key, type=Path, required=True)\n    a = p.parse_args()\n    sys.path.insert(0, str(a.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, shift_back_mask, Metrics_Rec, Metrics_Seg, set_seed\n    from run_public252 import validate\n\n    ref = json.loads(a.reference.read_text())\n    mask_path = a.code/\'mask/mask512x512.mat\'\n    assert sha(a.checkpoint) == ref[\'checkpoint_sha256\']\n    assert sha(mask_path) == ref[\'mask_sha256\']\n    assert sha(a.code/\'public252-v1.json\') == ref[\'protocol_sha256\']\n    validate(a.data, json.loads((a.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(exist_ok=False, parents=True)\n    set_seed(3407)\n    loader = evaluation_loader(a.data, \'val\', 0, True)\n    scenes = list(map(str, loader.dataset.names))\n    assert sorted(scenes) == sorted(ref[\'scenes\']) and len(scenes) == 25\n    model = model_generator(\'CRSDUN\', 28, 23, str(a.checkpoint))\n    model.eval()\n    physical = torch.as_tensor(loadmat(mask_path)[\'mask\'], dtype=torch.float32, device=\'cuda\')\n    phi, nominal = init_mask(str(mask_path), \'SSR\', 1, 28)\n    built = make_operator(physical)\n    assert all(torch.equal(x, y) for x, y in zip(built, nominal)), \'Nominal SSR tuple differs\'\n    assert all(torch.equal(x, y) for x, y in zip(make_operator(mix_mask(physical, 1, 0)), nominal))\n    nominal_hashes = [tensor_sha(x) for x in nominal]\n    conditions = [(\'clean\', 0, 0.0)] + [(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\', dx, alpha) for alpha in ALPHAS for dx in (1, -1)]\n    manifest = dict(status=\'running\', checkpoint_epoch=441, checkpoint_sha256=sha(a.checkpoint),\n                    protocol_sha256=ref[\'protocol_sha256\'], mask_sha256=sha(mask_path),\n                    script_sha256=sha(__file__), scenes=scenes, alphas=list(ALPHAS),\n                    conditions=conditions, completed_conditions=[], torch=str(torch.__version__),\n                    gpu=torch.cuda.get_device_name(0), expected_model_forwards=425,\n                    test_evaluated=False, training=False,\n                    scope=\'25 validation scenes; frozen model; identical measurement reused for nominal and matched full SSR tuples.\',\n                    caveat=\'Linear mask mixing with a zero-filled +/-1px shift is synthetic, not calibrated hardware motion. Matched masks may still be outside the training distribution.\',\n                    metrics=\'Every-stage confusion/MSE/PSNR_ref1; SSIM_ref1 final stage only. Scene-averaged reconstruction metrics; aggregate confusion mIoU.\')\n    manifest_path = a.out/\'experiment.json\'\n    def save_manifest():\n        manifest_path.write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    summary, severity_rows = [], []\n    started = time.time()\n    try:\n      with torch.inference_mode():\n        for name, dx, alpha in conditions:\n            folder = a.out/name\n            folder.mkdir()\n            mixed = physical if name == \'clean\' else mix_mask(physical, dx, alpha)\n            matched = make_operator(mixed)\n            acquisition = matched[1]\n            assert torch.equal(matched[0], shift_back_mask(acquisition))\n            expected_energy = acquisition.square().sum(1, keepdim=True)\n            expected_energy[expected_energy == 0] = 1\n            assert torch.equal(matched[2], expected_energy)\n            paired_ops = [(\'nominal\', nominal)] if name == \'clean\' else [(\'nominal\', nominal), (\'matched\', matched)]\n            severity_rows.append(dict(condition=name, dx=dx, alpha=alpha,\n                                      mask_relative_error=relative_error(mixed, physical),\n                                      changed_fraction=float((mixed != physical).float().mean()),\n                                      mean_transmittance=float(mixed.mean())))\n            pd.DataFrame(severity_rows).to_csv(a.out/\'mask_severity.csv\', index=False)\n            seg = {mode: [Metrics_Seg(23, get_class_names()) for _ in range(5)] for mode, _ in paired_ops}\n            records = []\n            for index, sample in enumerate(loader):\n                scene = scenes[index]\n                target = sample[\'image\'].float().cuda()\n                gt_cpu = target.cpu()\n                truth = sample[\'label\'].numpy()[0]\n                y = init_meas(target, acquisition, \'Y\')\n                if index == 0:\n                    assert torch.allclose(measure(target, acquisition), y, atol=1e-6, rtol=1e-6)\n                y_nominal = init_meas(target, phi, \'Y\')\n                measurement_error = relative_error(y, y_nominal)\n                y_digest = tensor_sha(y)\n                for mode, operator in paired_ops:\n                    op_hashes = [tensor_sha(x) for x in operator]\n                    xs, logits = model(y, operator)\n                    assert len(xs) == len(logits) == 5\n                    for k, (x, logit) in enumerate(zip(xs, logits), 1):\n                        assert x.shape == target.shape and logit.shape == (1, 23, *truth.shape)\n                        assert torch.isfinite(x).all() and torch.isfinite(logit).all(), f\'Nonfinite: {name}/{mode}/{scene}/stage{k}\'\n                        x_cpu = x.float().cpu()\n                        pred = logit.argmax(1).cpu().numpy()[0]\n                        hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                        np.save(folder/f\'{mode}_{scene}_stage{k}_confusion.npy\', hist)\n                        seg[mode][k-1].add_batch(truth[None], pred[None])\n                        mse = float((x_cpu-gt_cpu).square().mean())\n                        metrics = {\'MSE\':mse, \'PSNR\':float(-10*torch.log10(torch.tensor(mse))), \'SSIM\':None}\n                        if k == 5:\n                            rec = Metrics_Rec()\n                            rec.add_batch(gt_cpu, x_cpu)\n                            metrics = rec.get_table().iloc[0].to_dict()\n                        records.append(dict(condition=name, mode=mode, scene=scene, stage=k,\n                                            dx=dx, alpha=alpha, measurement_sha256=y_digest,\n                                            measurement_relative_error=measurement_error, **metrics))\n                    assert tensor_sha(y) == y_digest, \'Measurement mutated during inference\'\n                    assert [tensor_sha(t) for t in operator] == op_hashes, \'SSR tuple mutated\'\n                    del xs, logits, x, logit, x_cpu\n                pd.DataFrame(records).to_csv(folder/\'per_scene_stage_metrics.csv\', index=False)\n                del target, gt_cpu, y, y_nominal\n                print(f\'{name}: {index+1}/25; modes={len(paired_ops)}; elapsed={(time.time()-started)/60:.1f}min\', flush=True)\n            assert [tensor_sha(t) for t in nominal] == nominal_hashes\n            for mode, _ in paired_ops:\n                for k in range(1,6):\n                    acc = seg[mode][k-1]\n                    assert np.array_equal(sum(np.load(folder/f\'{mode}_{s}_stage{k}_confusion.npy\') for s in scenes), acc.confusion_matrix)\n                    np.save(folder/f\'{mode}_stage{k}_aggregate_confusion.npy\', acc.confusion_matrix)\n                    table = acc.get_table()\n                    table.to_csv(folder/f\'{mode}_stage{k}_segmentation.csv\')\n                    items = [r for r in records if r[\'mode\'] == mode and r[\'stage\'] == k]\n                    summary.append(dict(condition=name, mode=mode, stage=k, alpha=alpha, dx=dx,\n                                        foreground_miou_all22=float(table.loc[\'total(-bg)\', \'IoU\']),\n                                        PSNR=float(np.mean([r[\'PSNR\'] for r in items])),\n                                        MSE=float(np.mean([r[\'MSE\'] for r in items])),\n                                        SSIM=float(np.mean([r[\'SSIM\'] for r in items])) if k == 5 else None))\n            pd.DataFrame(summary).to_csv(a.out/\'stage_summary.csv\', index=False)\n            if name == \'clean\':\n                final = summary[-1]\n                check = dict(miou_difference=final[\'foreground_miou_all22\']-ref[\'miou\'], psnr_difference=final[\'PSNR\']-ref[\'psnr\'])\n                check[\'passed\'] = abs(check[\'miou_difference\']) < 1e-6 and abs(check[\'psnr_difference\']) < 1e-4\n                (a.out/\'clean_equivalence.json\').write_text(json.dumps(check, indent=2))\n                assert check[\'passed\'], \'Clean check failed; stopping before stresses\'\n            manifest[\'completed_conditions\'].append(name)\n            save_manifest()\n        pairs = []\n        for name, dx, alpha in conditions[1:]:\n            n, m = [next(r for r in summary if r[\'condition\']==name and r[\'mode\']==mode and r[\'stage\']==5) for mode in (\'nominal\', \'matched\')]\n            pairs.append(dict(condition=name, dx=dx, alpha=alpha,\n                              nominal_miou_percent=100*n[\'foreground_miou_all22\'], matched_miou_percent=100*m[\'foreground_miou_all22\'],\n                              matched_minus_nominal_miou_points=100*(m[\'foreground_miou_all22\']-n[\'foreground_miou_all22\']),\n                              nominal_psnr=n[\'PSNR\'], matched_psnr=m[\'PSNR\'], matched_minus_nominal_psnr=m[\'PSNR\']-n[\'PSNR\']))\n        pd.DataFrame(pairs).to_csv(a.out/\'paired_final_summary.csv\', index=False)\n        manifest[\'status\'] = \'completed\'\n        print(pd.DataFrame(pairs).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest[\'status\'] = \'failed\'\n        manifest[\'error\'] = repr(exc)\n        raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started\n        save_manifest()\n\nif __name__ == \'__main__\':\n    main()\n'
TEST_SCRIPT='"""CPU operator tests, including comparisons to the production helpers."""\nimport argparse\nimport sys\nimport torch\nfrom operator_control import mix_mask, make_operator, measure, relative_error, tensor_sha\n\np = argparse.ArgumentParser()\np.add_argument(\'--code\', required=True)\na = p.parse_args()\nsys.path.insert(0, a.code)\nfrom utils import init_meas, shift_back_mask\n\nm = torch.tensor([[1.,0.,1.,0.],[0.,1.,0.,1.]])\nunchanged = m.clone()\nx = torch.arange(24, dtype=torch.float32).reshape(1,3,2,4)/24\nfor dx in (-1,1):\n    expected_shift = torch.tensor([[0.,1.,0.,0.],[1.,0.,1.,0.]]) if dx == -1 else torch.tensor([[0.,1.,0.,1.],[0.,0.,1.,0.]])\n    assert torch.equal(mix_mask(m,dx,1), expected_shift)\n    assert torch.equal(mix_mask(m,dx,0), m)\n    for alpha in (0.,.05,.1,.25,1.):\n        mixed = mix_mask(m, dx, alpha)\n        assert torch.equal(mixed, (1-alpha)*m+alpha*expected_shift)\n        back, phi, energy = make_operator(mixed, bands=3)\n        assert torch.equal(back, shift_back_mask(phi))\n        assert torch.equal(back, mixed[None,None].repeat(1,3,1,1))\n        e = phi.square().sum(1, keepdim=True)\n        e[e==0] = 1\n        assert torch.equal(energy, e)\n        if alpha == .25:\n            assert not torch.equal(energy, phi.sum(1, keepdim=True)), \'Fractional masks must use squared energy\'\n        independent = torch.zeros(1,2,8)\n        for c in range(3):\n            independent[:,:,2*c:2*c+4] += x[:,c]*mixed\n        y = measure(x, phi)\n        assert torch.allclose(y, independent)\n        # Production shift() allocates CUDA explicitly, even for CPU input.\n        if torch.cuda.is_available():\n            production = init_meas(x.cuda(), phi.cuda(), \'Y\').cpu()\n            assert torch.allclose(y, production)\n        assert relative_error(mixed,m) >= 0\n        assert tensor_sha(y) == tensor_sha(y.clone())\nassert torch.equal(m, unchanged)\nassert relative_error(m,m) == 0\nzero = make_operator(torch.zeros_like(m), bands=3)\nassert torch.equal(zero[2], torch.ones_like(zero[2]))\nassert torch.cuda.is_available(), \'Production measurement comparison requires CUDA; CPU-only checks finished.\'\nprint(\'PASS: both zero-filled shifts, mixing endpoints/interiors, all SSR components, squared fractional-mask energy, zero-energy guard, production measurement agreement on CUDA, no mask mutation.\')\n'
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}

RUN=WORK/('operator_control_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
(RUN/'operator_control.py').write_text(SCRIPT)
(RUN/'verify_operator_control.py').write_text(TEST_SCRIPT)
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'source_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in ['models/CRSDUN.py','dataset.py','utils.py','public252-v1.json']},indent=2))
subprocess.run([sys.executable,str(RUN/'verify_operator_control.py'),'--code',str(CODE)],cwd=RUN,check=True)
print('Output folder:',RUN)

In [ ]:
from IPython.display import display,FileLink
try:
    with (RUN/'console.log').open('w') as log:
        command=[sys.executable,'-u',str(RUN/'operator_control.py'),
                 '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
                 '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json')]
        proc=subprocess.Popen(command,cwd=CODE,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)
        try:
            for line in proc.stdout:
                print(line,end='',flush=True)
                log.write(line);log.flush()
            code=proc.wait()
            if code: raise subprocess.CalledProcessError(code,command)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try: proc.wait(timeout=10)
                except subprocess.TimeoutExpired: proc.kill();proc.wait()
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

In [ ]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed','Partial run: share the ZIP and error.'
assert len(manifest['completed_conditions'])==9
assert json.loads((RUN/'results/clean_equivalence.json').read_text())['passed']
display(pd.read_csv(RUN/'results/paired_final_summary.csv'))
display(pd.read_csv(RUN/'results/mask_severity.csv'))
print('Completed. Download the operator_control_epoch441 ZIP and share its local path. No new model was trained.')

In [1]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch441 weights: /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth

In [2]:
FILES={'operator_control.py': '"""Frozen validation: paired nominal/matched operators under synthetic mask mixing."""\nfrom pathlib import Path\nimport argparse\nimport hashlib\nimport json\nimport time\nimport numpy as np\nimport torch\n\nALPHAS = (0.05, 0.10, 0.25, 1.0)\n\ndef sha(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\ndef tensor_sha(x):\n    return hashlib.sha256(x.detach().cpu().contiguous().numpy().tobytes()).hexdigest()\n\ndef mix_mask(mask, dx, alpha):\n    assert mask.ndim == 2 and dx in (-1, 1) and 0 <= alpha <= 1\n    shifted = torch.zeros_like(mask)\n    if dx == 1:\n        shifted[:, 1:] = mask[:, :-1]\n    else:\n        shifted[:, :-1] = mask[:, 1:]\n    return (1-alpha)*mask + alpha*shifted\n\ndef make_operator(mask, bands=28, step=2):\n    h, w = mask.shape\n    phi = mask.new_zeros((1, bands, h, w+(bands-1)*step))\n    for c in range(bands):\n        phi[0, c, :, step*c:step*c+w] = mask\n    back = torch.stack([phi[:, c, :, step*c:step*c+w] for c in range(bands)], dim=1)\n    energy = phi.square().sum(1, keepdim=True)\n    energy = torch.where(energy == 0, torch.ones_like(energy), energy)\n    return back, phi, energy\n\ndef measure(x, phi, step=2):\n    b, c, h, w = x.shape\n    y = x.new_zeros((b, h, phi.shape[-1]))\n    for k in range(c):\n        y[:, :, step*k:step*k+w] += x[:, k]*phi[:, k, :, step*k:step*k+w]\n    return y\n\ndef relative_error(a, b):\n    return float(torch.linalg.vector_norm(a-b)/torch.linalg.vector_norm(b).clamp_min(1e-12))\n\ndef main():\n    import sys\n    p = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\'):\n        p.add_argument(\'--\'+key, type=Path, required=True)\n    a = p.parse_args()\n    sys.path.insert(0, str(a.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, shift_back_mask, Metrics_Rec, Metrics_Seg, set_seed\n    from run_public252 import validate\n\n    ref = json.loads(a.reference.read_text())\n    mask_path = a.code/\'mask/mask512x512.mat\'\n    assert sha(a.checkpoint) == ref[\'checkpoint_sha256\']\n    assert sha(mask_path) == ref[\'mask_sha256\']\n    assert sha(a.code/\'public252-v1.json\') == ref[\'protocol_sha256\']\n    validate(a.data, json.loads((a.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(exist_ok=False, parents=True)\n    set_seed(3407)\n    loader = evaluation_loader(a.data, \'val\', 0, True)\n    scenes = list(map(str, loader.dataset.names))\n    assert sorted(scenes) == sorted(ref[\'scenes\']) and len(scenes) == 25\n    model = model_generator(\'CRSDUN\', 28, 23, str(a.checkpoint))\n    model.eval()\n    physical = torch.as_tensor(loadmat(mask_path)[\'mask\'], dtype=torch.float32, device=\'cuda\')\n    phi, nominal = init_mask(str(mask_path), \'SSR\', 1, 28)\n    built = make_operator(physical)\n    assert all(torch.equal(x, y) for x, y in zip(built, nominal)), \'Nominal SSR tuple differs\'\n    assert all(torch.equal(x, y) for x, y in zip(make_operator(mix_mask(physical, 1, 0)), nominal))\n    nominal_hashes = [tensor_sha(x) for x in nominal]\n    conditions = [(\'clean\', 0, 0.0)] + [(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\', dx, alpha) for alpha in ALPHAS for dx in (1, -1)]\n    manifest = dict(status=\'running\', checkpoint_epoch=441, checkpoint_sha256=sha(a.checkpoint),\n                    protocol_sha256=ref[\'protocol_sha256\'], mask_sha256=sha(mask_path),\n                    script_sha256=sha(__file__), scenes=scenes, alphas=list(ALPHAS),\n                    conditions=conditions, completed_conditions=[], torch=str(torch.__version__),\n                    gpu=torch.cuda.get_device_name(0), expected_model_forwards=425,\n                    test_evaluated=False, training=False,\n                    scope=\'25 validation scenes; frozen model; identical measurement reused for nominal and matched full SSR tuples.\',\n                    caveat=\'Linear mask mixing with a zero-filled +/-1px shift is synthetic, not calibrated hardware motion. Matched masks may still be outside the training distribution.\',\n                    metrics=\'Every-stage confusion/MSE/PSNR_ref1; SSIM_ref1 final stage only. Scene-averaged reconstruction metrics; aggregate confusion mIoU.\')\n    manifest_path = a.out/\'experiment.json\'\n    def save_manifest():\n        manifest_path.write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    summary, severity_rows = [], []\n    started = time.time()\n    try:\n      with torch.inference_mode():\n        for name, dx, alpha in conditions:\n            folder = a.out/name\n            folder.mkdir()\n            mixed = physical if name == \'clean\' else mix_mask(physical, dx, alpha)\n            matched = make_operator(mixed)\n            acquisition = matched[1]\n            assert torch.equal(matched[0], shift_back_mask(acquisition))\n            expected_energy = acquisition.square().sum(1, keepdim=True)\n            expected_energy[expected_energy == 0] = 1\n            assert torch.equal(matched[2], expected_energy)\n            paired_ops = [(\'nominal\', nominal)] if name == \'clean\' else [(\'nominal\', nominal), (\'matched\', matched)]\n            severity_rows.append(dict(condition=name, dx=dx, alpha=alpha,\n                                      mask_relative_error=relative_error(mixed, physical),\n                                      changed_fraction=float((mixed != physical).float().mean()),\n                                      mean_transmittance=float(mixed.mean())))\n            pd.DataFrame(severity_rows).to_csv(a.out/\'mask_severity.csv\', index=False)\n            seg = {mode: [Metrics_Seg(23, get_class_names()) for _ in range(5)] for mode, _ in paired_ops}\n            records = []\n            for index, sample in enumerate(loader):\n                scene = scenes[index]\n                target = sample[\'image\'].float().cuda()\n                gt_cpu = target.cpu()\n                truth = sample[\'label\'].numpy()[0]\n                y = init_meas(target, acquisition, \'Y\')\n                if index == 0:\n                    assert torch.allclose(measure(target, acquisition), y, atol=1e-6, rtol=1e-6)\n                y_nominal = init_meas(target, phi, \'Y\')\n                measurement_error = relative_error(y, y_nominal)\n                y_digest = tensor_sha(y)\n                for mode, operator in paired_ops:\n                    op_hashes = [tensor_sha(x) for x in operator]\n                    xs, logits = model(y, operator)\n                    assert len(xs) == len(logits) == 5\n                    for k, (x, logit) in enumerate(zip(xs, logits), 1):\n                        assert x.shape == target.shape and logit.shape == (1, 23, *truth.shape)\n                        assert torch.isfinite(x).all() and torch.isfinite(logit).all(), f\'Nonfinite: {name}/{mode}/{scene}/stage{k}\'\n                        x_cpu = x.float().cpu()\n                        pred = logit.argmax(1).cpu().numpy()[0]\n                        hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                        np.save(folder/f\'{mode}_{scene}_stage{k}_confusion.npy\', hist)\n                        seg[mode][k-1].add_batch(truth[None], pred[None])\n                        mse = float((x_cpu-gt_cpu).square().mean())\n                        metrics = {\'MSE\':mse, \'PSNR\':float(-10*torch.log10(torch.tensor(mse))), \'SSIM\':None}\n                        if k == 5:\n                            rec = Metrics_Rec()\n                            rec.add_batch(gt_cpu, x_cpu)\n                            metrics = rec.get_table().iloc[0].to_dict()\n                        records.append(dict(condition=name, mode=mode, scene=scene, stage=k,\n                                            dx=dx, alpha=alpha, measurement_sha256=y_digest,\n                                            measurement_relative_error=measurement_error, **metrics))\n                    assert tensor_sha(y) == y_digest, \'Measurement mutated during inference\'\n                    assert [tensor_sha(t) for t in operator] == op_hashes, \'SSR tuple mutated\'\n                    del xs, logits, x, logit, x_cpu\n                pd.DataFrame(records).to_csv(folder/\'per_scene_stage_metrics.csv\', index=False)\n                del target, gt_cpu, y, y_nominal\n                print(f\'{name}: {index+1}/25; modes={len(paired_ops)}; elapsed={(time.time()-started)/60:.1f}min\', flush=True)\n            assert [tensor_sha(t) for t in nominal] == nominal_hashes\n            for mode, _ in paired_ops:\n                for k in range(1,6):\n                    acc = seg[mode][k-1]\n                    assert np.array_equal(sum(np.load(folder/f\'{mode}_{s}_stage{k}_confusion.npy\') for s in scenes), acc.confusion_matrix)\n                    np.save(folder/f\'{mode}_stage{k}_aggregate_confusion.npy\', acc.confusion_matrix)\n                    table = acc.get_table()\n                    table.to_csv(folder/f\'{mode}_stage{k}_segmentation.csv\')\n                    items = [r for r in records if r[\'mode\'] == mode and r[\'stage\'] == k]\n                    summary.append(dict(condition=name, mode=mode, stage=k, alpha=alpha, dx=dx,\n                                        foreground_miou_all22=float(table.loc[\'total(-bg)\', \'IoU\']),\n                                        PSNR=float(np.mean([r[\'PSNR\'] for r in items])),\n                                        MSE=float(np.mean([r[\'MSE\'] for r in items])),\n                                        SSIM=float(np.mean([r[\'SSIM\'] for r in items])) if k == 5 else None))\n            pd.DataFrame(summary).to_csv(a.out/\'stage_summary.csv\', index=False)\n            if name == \'clean\':\n                final = summary[-1]\n                check = dict(miou_difference=final[\'foreground_miou_all22\']-ref[\'miou\'], psnr_difference=final[\'PSNR\']-ref[\'psnr\'])\n                check[\'passed\'] = abs(check[\'miou_difference\']) < 1e-6 and abs(check[\'psnr_difference\']) < 1e-4\n                (a.out/\'clean_equivalence.json\').write_text(json.dumps(check, indent=2))\n                assert check[\'passed\'], \'Clean check failed; stopping before stresses\'\n            manifest[\'completed_conditions\'].append(name)\n            save_manifest()\n        pairs = []\n        for name, dx, alpha in conditions[1:]:\n            n, m = [next(r for r in summary if r[\'condition\']==name and r[\'mode\']==mode and r[\'stage\']==5) for mode in (\'nominal\', \'matched\')]\n            pairs.append(dict(condition=name, dx=dx, alpha=alpha,\n                              nominal_miou_percent=100*n[\'foreground_miou_all22\'], matched_miou_percent=100*m[\'foreground_miou_all22\'],\n                              matched_minus_nominal_miou_points=100*(m[\'foreground_miou_all22\']-n[\'foreground_miou_all22\']),\n                              nominal_psnr=n[\'PSNR\'], matched_psnr=m[\'PSNR\'], matched_minus_nominal_psnr=m[\'PSNR\']-n[\'PSNR\']))\n        pd.DataFrame(pairs).to_csv(a.out/\'paired_final_summary.csv\', index=False)\n        manifest[\'status\'] = \'completed\'\n        print(pd.DataFrame(pairs).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest[\'status\'] = \'failed\'\n        manifest[\'error\'] = repr(exc)\n        raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started\n        save_manifest()\n\nif __name__ == \'__main__\':\n    main()\n', 'numerical_trace.py': '"""Observe frozen CRSDUN through hooks; require exact traced/untraced outputs."""\nimport argparse, json, sys, time\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom operator_control import make_operator, mix_mask, sha, tensor_sha\n\ndef stats(x):\n    a=x.detach().cpu().double().numpy()\n    assert np.isfinite(a).all(), \'Nonfinite tensor in trace\'\n    return dict(min=float(a.min()),max=float(a.max()),rms=float(np.sqrt(np.mean(a*a))),max_abs=float(np.abs(a).max()))\n\ndef denominator_stats(d):\n    r=stats(d); a=d.detach().cpu().double().numpy()\n    r.update(min_abs=float(np.abs(a).min()),min_abs_index=[int(i) for i in np.unravel_index(np.abs(a).argmin(),a.shape)],nonpositive=int((a<=0).sum()),elements=int(a.size))\n    for limit in (1e-6,1e-4,1e-2,.1):r[f\'abs_below_{limit:g}\']=int((np.abs(a)<limit).sum())\n    return r\n\ndef spatial_error(x, target, aligned_energy):\n    delta=x.detach().cpu().double().numpy()-target\n    sq=delta[0]**2\n    h,w=sq.shape[-2:]\n    border=np.ones((h,w),dtype=bool)\n    border[16:-16,16:-16]=False\n    regions={\'image_border16\':np.broadcast_to(border,sq.shape),\'image_interior\':np.broadcast_to(~border,sq.shape)}\n    regions.update({\'energy_zero\':aligned_energy==0,\'energy_0_to_0.1\':(aligned_energy>0)&(aligned_energy<=.1),\n                    \'energy_0.1_to_1\':(aligned_energy>.1)&(aligned_energy<=1),\n                    \'energy_1_to_4\':(aligned_energy>1)&(aligned_energy<=4),\'energy_above4\':aligned_energy>4})\n    total=float(sq.sum()); result={}\n    for name,mask in regions.items():\n        n=int(mask.sum()); s=float(sq[mask].sum())\n        result[name]=dict(voxels=n,squared_error_sum=s,mse=s/n if n else None,fraction_total_error=s/total if total else 0.)\n    return dict(mse=float(sq.mean()),total_squared_error=total,regions=result)\n\nclass Observer:\n    def __init__(self,model,operator,target,emit,measurement=None):\n        self.model=model;self.operator=operator;self.target=target.detach().cpu().double().numpy();self.emit=emit\n        self.stage=0;self.handles=[];self.original_phif=model.mul_Phif;self.original_phit=model.mul_PhiTg\n        self.measurement=measurement\n        self.had_phif=\'mul_Phif\' in model.__dict__;self.had_phit=\'mul_PhiTg\' in model.__dict__\n        _,bands,h,w=target.shape\n        raw=operator[1].square().sum(1)[0]\n        self.aligned_energy=torch.stack([raw[:,2*c:2*c+w] for c in range(bands)]).cpu().numpy()\n\n    def record(self,event,x,error=False,**extra):\n        row=dict(stage=self.stage,event=event,values=stats(x),**extra)\n        if error:row[\'reconstruction_error\']=spatial_error(x,self.target,self.aligned_energy)\n        self.emit(row)\n\n    def __enter__(self):\n        def para_hook(module,args,out):\n            self.stage+=1\n            p=out.detach().cpu().flatten().tolist()\n            assert len(p)==4\n            self.emit(dict(stage=self.stage,event=\'parameters\',a=p[0],mu=p[1],b=p[2],gamma=p[3],\n                           denominator=denominator_stats(self.operator[2]+out[:,0:1])))\n        def phif(phi,x):\n            self.record(\'x_new_before_data_consistency\',x,error=True)\n            result=self.original_phif(phi,x)\n            self.record(\'predicted_measurement\',result)\n            if self.measurement is not None:self.record(\'measurement_residual\',self.measurement.unsqueeze(1)-result)\n            return result\n        def phit(phi,g):\n            self.record(\'residual_divided_by_denominator\',g)\n            result=self.original_phit(phi,g)\n            self.record(\'data_consistency_correction\',result)\n            return result\n        self.model.mul_Phif=phif;self.model.mul_PhiTg=phit\n        for module in self.model.para_est:self.handles.append(module.register_forward_hook(para_hook))\n        for k in range(self.model.stage):\n            self.handles.append(self.model.net_stage[3*k].register_forward_pre_hook(lambda m,args:self.record(\'z_before_reconstruction_attention\',args[0],error=True)))\n            self.handles.append(self.model.net_stage[3*k].register_forward_hook(lambda m,args,out:self.record(\'after_reconstruction_attention\',out,error=True)))\n            self.handles.append(self.model.net_stage[3*k+1].register_forward_hook(lambda m,args,out:self.record(\'after_refinement\',out,error=True)))\n        return self\n\n    def __exit__(self,*exc):\n        for h in self.handles:h.remove()\n        if self.had_phif:self.model.mul_Phif=self.original_phif\n        else:del self.model.mul_Phif\n        if self.had_phit:self.model.mul_PhiTg=self.original_phit\n        else:del self.model.mul_PhiTg\n\ndef main():\n    p=argparse.ArgumentParser()\n    for name in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+name,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    from scipy.io import loadmat\n    import pandas as pd\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    conditions=[(\'clean\',0,0.)]+[(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\',dx,alpha) for alpha in (.1,.25,1.) for dx in (1,-1)]\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],mask_sha256=ref[\'mask_sha256\'],script_sha256=sha(__file__),helper_sha256=sha(Path(__file__).with_name(\'operator_control.py\')),scenes=scenes,conditions=conditions,completed_conditions=[],completed_identity_pairs=0,training=False,test_evaluated=False,expected_forwards=350,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'Matched operators only. Every traced forward paired with an uninstrumented forward; all five reconstruction/logit tensors must hash identically. Regions are image-border16 and raw detector-energy bins aligned to each spectral voxel, not calibrated hardware regions.\')\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];scene_metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha in conditions:\n            operator=make_operator(mask if not dx else mix_mask(mask,dx,alpha))\n            op_hash=[tensor_sha(t) for t in operator]\n            accumulator=Metrics_Seg(23,get_class_names());rec=Metrics_Rec()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                y=init_meas(target,operator[1],\'Y\');yh=tensor_sha(y)\n                xs,ls=model(y,operator)\n                baseline=[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n                def emit(row):\n                    f.write(json.dumps(dict(condition=name,scene=scene,**row),allow_nan=False)+\'\\n\')\n                with Observer(model,operator,target,emit,measurement=y) as observer:xs,ls=model(y,operator)\n                f.flush()\n                assert observer.stage==5\n                equal=baseline==[tensor_sha(t) for t in [*xs,*ls]]\n                checks.append(dict(condition=name,scene=scene,all_stage_tensors_bitwise_identical=equal))\n                (args.out/\'identity_checks.json\').write_text(json.dumps(checks,indent=2))\n                assert equal,\'Instrumentation altered predictions\'\n                assert tensor_sha(y)==yh and [tensor_sha(t) for t in operator]==op_hash\n                one=Metrics_Rec();one.add_batch(target.cpu(),xs[-1].cpu())\n                metric=one.get_table().iloc[0].to_dict()\n                e=expected[\'scenes\'][name][scene]\n                assert abs(metric[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(metric[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Prior scene metrics not reproduced\'\n                for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec,field,getattr(rec,field)+getattr(one,field))\n                pred=ls[-1].argmax(1).cpu().numpy()[0];accumulator.add_batch(truth[None],pred[None])\n                hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                assert __import__(\'hashlib\').sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Prior scene confusion differs\'\n                scene_metrics.append(dict(condition=name,scene=scene,**metric));pd.DataFrame(scene_metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                manifest[\'completed_identity_pairs\']+=1;save()\n                del xs,ls,target,y\n                print(f\'{name}: {index+1}/25, traced/untraced identical, prior metrics reproduced; {(time.time()-started)/60:.1f}min\',flush=True)\n            table=accumulator.get_table();row=dict(condition=name,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec.get_table().iloc[0].to_dict())\n            e=expected[\'summary\'][name]\n            assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n            summaries.append(row);pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            table.to_csv(args.out/f\'{name}_segmentation.csv\');np.save(args.out/f\'{name}_confusion.npy\',accumulator.confusion_matrix)\n            manifest[\'completed_conditions\'].append(name);save()\n        manifest[\'status\']=\'completed\'\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'verify_numerical_trace.py': '"""Test observational instrumentation on the actual architecture at small resolution."""\nimport argparse,sys\nimport numpy as np\nimport torch\nfrom numerical_trace import Observer,denominator_stats,spatial_error\nfrom operator_control import make_operator,mix_mask,tensor_sha\np=argparse.ArgumentParser();p.add_argument(\'--code\',required=True);args=p.parse_args();sys.path.insert(0,args.code)\nfrom models.CRSDUN import CRSDUN\nfrom utils import init_meas,set_seed\nassert torch.cuda.is_available()\ntorch.set_num_threads(1);set_seed(3407)\nd=denominator_stats(torch.tensor([[-.001,0.,.05,2.]]))\nassert d[\'nonpositive\']==2 and d[\'min_abs\']==0 and d[\'abs_below_0.01\']==2\ntarget=torch.zeros(1,3,40,40);x=torch.ones_like(target);energy=np.ones((3,40,40))\nr=spatial_error(x,target.numpy(),energy)\nassert r[\'mse\']==1\nassert r[\'regions\'][\'image_border16\'][\'voxels\']+r[\'regions\'][\'image_interior\'][\'voxels\']==x.numel()\nassert sum(v[\'voxels\'] for k,v in r[\'regions\'].items() if k.startswith(\'energy_\'))==x.numel()\nassert r[\'regions\'][\'energy_0.1_to_1\'][\'fraction_total_error\']==1\nmodel=CRSDUN(stage=5,bands=28,n_class=23).cuda().eval()\nmask=(torch.rand(64,64,device=\'cuda\')>.5).float()\ntarget=torch.rand(1,28,64,64,device=\'cuda\')\nwith torch.inference_mode():\n for alpha in (0.,.25):\n    op=make_operator(mix_mask(mask,1,alpha));y=init_meas(target,op[1],\'Y\')\n    before=model(y,op);hashes=[tensor_sha(t) for outputs in before for t in outputs];del before\n    records=[]\n    with Observer(model,op,target,records.append,measurement=y) as observer:after=model(y,op)\n    assert hashes==[tensor_sha(t) for outputs in after for t in outputs]\n    assert observer.stage==5 and len([r for r in records if r[\'event\']==\'parameters\'])==5\n    assert len(records)==45\n    assert \'mul_Phif\' not in model.__dict__ and \'mul_PhiTg\' not in model.__dict__\n    assert all(not module._forward_hooks and not module._forward_pre_hooks for module in model.modules())\n    del after\n try:\n    with Observer(model,op,target,lambda r:None):raise RuntimeError(\'intentional cleanup check\')\n except RuntimeError:pass\n assert \'mul_Phif\' not in model.__dict__ and all(not m._forward_hooks and not m._forward_pre_hooks for m in model.modules())\nprint(\'PASS: real five-stage architecture, clean/fractional operators, bitwise unchanged outputs, hook cleanup including exceptions, denominator counts and spatial error partitions. Small random-input test; not trained full-frame evaluation.\')\n'}
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}
EXPECTED={'source_archive': 'operator_control_epoch441_20261010_183309_608911.zip', 'source_archive_sha256': 'b2f9bf0118804cfdfecc7e72f5aee9a3f36b975631bcb1c4ad1618cec7cb7743', 'summary': {'clean': {'foreground_miou_all22': 0.7876837070566084, 'PSNR': 39.00684616088867, 'MSE': 0.00013123682205332443, 'SSIM': 0.9747850704193115}, 'plus1_alpha0.1': {'foreground_miou_all22': 0.7804071879322305, 'PSNR': 38.480462341308595, 'MSE': 0.00014687360497191547, 'SSIM': 0.9726465129852295}, 'minus1_alpha0.1': {'foreground_miou_all22': 0.7806234925438672, 'PSNR': 38.41059600830078, 'MSE': 0.0001489559863694012, 'SSIM': 0.97251469373703}, 'plus1_alpha0.25': {'foreground_miou_all22': 0.7099818617488114, 'PSNR': -5.109313906431198, 'MSE': 83.81524314329027, 'SSIM': 0.9039690732955933}, 'minus1_alpha0.25': {'foreground_miou_all22': 0.7033165229414478, 'PSNR': -5.086848521232605, 'MSE': 65.10976030603051, 'SSIM': 0.8999737000465393}, 'plus1_alpha1': {'foreground_miou_all22': 0.7830800141043546, 'PSNR': 38.98537872314453, 'MSE': 0.00013183161034248768, 'SSIM': 0.974661271572113}, 'minus1_alpha1': {'foreground_miou_all22': 0.7820777620674779, 'PSNR': 38.88986663818359, 'MSE': 0.0001340003072982654, 'SSIM': 0.9741322302818298}}, 'scenes': {'clean': {'2021-11-03_046': {'PSNR': 39.89459228515625, 'MSE': 0.00010245677549391985, 'confusion_sha256': '9a717b84a51b72b2fba1c9060dfc8ad32d2508a3c8f0eb98494f1809757909ec'}, '2021-11-03_047': {'PSNR': 38.86285400390625, 'MSE': 0.00012993150448892266, 'confusion_sha256': '919915901d083e6ed85b8577721c7392ee968a7d23b41b7d6df5407226b34d16'}, '2021-11-03_057': {'PSNR': 37.99570083618164, 'MSE': 0.00015864624583628029, 'confusion_sha256': '711f63aea60da1ad3e5dd583c1ad6c185b62eb8ead7661faab625fefc9a93000'}, '2021-11-03_085': {'PSNR': 40.45058059692383, 'MSE': 9.01449893717654e-05, 'confusion_sha256': 'f26712d2687056e1f8812c93a119dc945e55a6c1c3a465d8c75b9e4e89c4cfdd'}, '2021-11-03_090': {'PSNR': 40.33523178100586, 'MSE': 9.257135388907045e-05, 'confusion_sha256': 'ce95968be99e39136bb3a54ba923ea41501fa0803c75a0bae08d8bd21e2de7ec'}, '2021-11-03_110': {'PSNR': 39.576499938964844, 'MSE': 0.00011024268314940855, 'confusion_sha256': '925537ac21544cbbed2767f15ad85fa1c7a52691dc70e7712568c6260f9b2c13'}, '2021-11-04_010': {'PSNR': 37.13905334472656, 'MSE': 0.00019323898595757782, 'confusion_sha256': 'c9099b0d0a570152439bb9708c16c6f9882d2b9d23632b94de45b23e5e2e145b'}, '2021-11-04_017': {'PSNR': 38.54598617553711, 'MSE': 0.00013976586342323571, 'confusion_sha256': 'dcdfe2f5a2ef36a30df2960ae7f34537645c5ef3070a89e09ec06fe7708f669c'}, '2021-11-04_024': {'PSNR': 38.70061111450195, 'MSE': 0.00013487727846950293, 'confusion_sha256': 'e3082e8a5aee905c21b646233bda5e8f37889d2ec740925842e5389426415656'}, '2021-11-04_042': {'PSNR': 40.50850296020508, 'MSE': 8.895069913705811e-05, 'confusion_sha256': '69745abc94ea2ee55b0aac789679b0353d08f391c931258e232dd465690d7f22'}, '2021-11-04_047': {'PSNR': 40.22039794921875, 'MSE': 9.505175694357604e-05, 'confusion_sha256': 'b6c73d3bec5395b68de7c48614e082e1c36f6330ee46719b20947da3f4c25bbc'}, '2021-11-04_049': {'PSNR': 40.83124542236328, 'MSE': 8.25801253085956e-05, 'confusion_sha256': 'b63f6d857eeb2b1870346a4ecb5c3594f5dea62fefe6262ece4344a65a2791c2'}, '2021-11-04_055': {'PSNR': 40.75486373901367, 'MSE': 8.404533582506701e-05, 'confusion_sha256': '995f147be920d56d9ba740f6ec33fd436afc5e1a8eaad452b5dcaa746edd9834'}, '2021-11-04_061': {'PSNR': 40.685176849365234, 'MSE': 8.540479029761627e-05, 'confusion_sha256': '59adfbe1bb34d1890af5029d8bd8281620d18396e9b876be0e4f6e4f6f5d2596'}, '2021-11-04_093': {'PSNR': 39.08949661254883, 'MSE': 0.0001233247312484309, 'confusion_sha256': '6366ce691015ac82a2669684a1c4d681bff89544f92fab6972d817ea7e7d7b2c'}, '2021-11-04_098': {'PSNR': 39.36787414550781, 'MSE': 0.00011566774628590792, 'confusion_sha256': '6d227838a684f6f312e50afa89da8c8623ad19564835045da03dc93a2bdabdea'}, '2021-11-05_010': {'PSNR': 37.41633987426758, 'MSE': 0.00018128668307326734, 'confusion_sha256': '13b3bae21986dd485dbe9125a904ee039a7d076c7e1aa9a2c19c4a8317eeee6f'}, '2021-11-05_024': {'PSNR': 39.7016716003418, 'MSE': 0.00010711060895118862, 'confusion_sha256': 'df5555f991ede7f38186ff4cbfe4dca368ad0ff0bfba94e2cb5e5ae992659d4f'}, '2021-11-05_035': {'PSNR': 38.786293029785156, 'MSE': 0.00013224223221186548, 'confusion_sha256': '7642e43435e57e4c293c5497b3ed47fdf0830fab3a34010f983d393ff6f79224'}, '2021-11-05_041': {'PSNR': 38.4978141784668, 'MSE': 0.00014132479554973543, 'confusion_sha256': 'cee79d0f10b1a368417af8ec32939e69ccfc5a1d5d4b70c9727535b9fe968e3b'}, '2021-11-05_046': {'PSNR': 36.10015869140625, 'MSE': 0.0002454617933835834, 'confusion_sha256': '99ceb435926731d4d7593346568ef795f28ff326dcb5a775f1f9fe1af0388e31'}, '2021-11-10_014': {'PSNR': 38.25468063354492, 'MSE': 0.00014946235751267523, 'confusion_sha256': '700d7bfb7ee77774c754fa984c10b556125d20f7eb11ce8f8fea4055a35c9fc2'}, '2021-11-10_024': {'PSNR': 37.73176193237305, 'MSE': 0.00016858673188835382, 'confusion_sha256': '32c9dfe5fd11c769fdd29d729a4cc2575d048096185fe33c83c76f035d77b383'}, '2021-11-10_029': {'PSNR': 38.25230407714844, 'MSE': 0.00014954424113966525, 'confusion_sha256': '55b866708c3de1af700fe8c596c4acee41e9c60fc89886eb282486f138541098'}, '2021-11-10_050': {'PSNR': 37.47146224975586, 'MSE': 0.00017900024249684066, 'confusion_sha256': 'ffff7a303633916099bc9025d29370aab79abad5f287f2f452f346467e5b0f9a'}}, 'plus1_alpha0.1': {'2021-11-03_046': {'PSNR': 39.53356170654297, 'MSE': 0.00011133799853269011, 'confusion_sha256': '74fc44022774fddc2d3a840197e046c73c5050626e157f802892e08a8ae3970a'}, '2021-11-03_047': {'PSNR': 38.42921829223633, 'MSE': 0.00014357476902659982, 'confusion_sha256': '2ce3d59f70510d4f27629c65ea1221c6b4fff5549368e6846e141f6bba354231'}, '2021-11-03_057': {'PSNR': 37.398101806640625, 'MSE': 0.0001820495817810297, 'confusion_sha256': 'babb40ea19ec33fbca3de7480d72b180d3866d0be78a8a68b66ba7a1eccf7165'}, '2021-11-03_085': {'PSNR': 39.71846389770508, 'MSE': 0.00010669727635104209, 'confusion_sha256': '54ef114eaba644b482e72defb86a4d5b911e24996811d862f6bb0a092aafd750'}, '2021-11-03_090': {'PSNR': 39.6631965637207, 'MSE': 0.0001080637812265195, 'confusion_sha256': 'd7b07e83629bb6d48a85433bfeeb9d99b21eb999ddf69b08cb96ac2b25a6fcc2'}, '2021-11-03_110': {'PSNR': 38.660606384277344, 'MSE': 0.00013612551265396178, 'confusion_sha256': '4d2d561e7a719337bf24cd74ecfd5cd6e8eed94b1a8a9fb3e71f4380fc87e583'}, '2021-11-04_010': {'PSNR': 36.83472442626953, 'MSE': 0.00020726557704620063, 'confusion_sha256': '543788170690efed986c186154b356d3f8b37ae5ae3d5c40f69a693b0ffb7667'}, '2021-11-04_017': {'PSNR': 38.19437026977539, 'MSE': 0.00015155240544117987, 'confusion_sha256': '4ecdb1d9c131545b6465cb2f6655cf57e58f4102b1d0f390fe04c259d8668765'}, '2021-11-04_024': {'PSNR': 38.337066650390625, 'MSE': 0.00014665376511402428, 'confusion_sha256': 'b2f7017b0135d8af9983fde8ac73650082fa5e34c6885c915d4e28f5c85f185a'}, '2021-11-04_042': {'PSNR': 39.93755340576172, 'MSE': 0.00010144825500901788, 'confusion_sha256': 'f76ec9713fff65f4d1aef2658e4a7bc4f98f77b342008b199ed4304d316954ed'}, '2021-11-04_047': {'PSNR': 39.63911056518555, 'MSE': 0.00010866473894566298, 'confusion_sha256': '4a0f2d6389539eb636b013b6816fbf617c6f7b4f045018981882104bc8345341'}, '2021-11-04_049': {'PSNR': 40.25779724121094, 'MSE': 9.423670417163521e-05, 'confusion_sha256': '0b49214fcd84d7922c192e60f21be8517bf86b8cff7aa9714ed8a51bcf89b108'}, '2021-11-04_055': {'PSNR': 39.86824417114258, 'MSE': 0.000103080237749964, 'confusion_sha256': '8cc5e7d7f0945238df53f2d9672225549251d60810a28e4e4aa565963f02ce73'}, '2021-11-04_061': {'PSNR': 39.8060417175293, 'MSE': 0.00010456730524310842, 'confusion_sha256': '60fe3ce021d34106b146016292b483da442d708c45db3bc2d42951d0feb031d0'}, '2021-11-04_093': {'PSNR': 38.563316345214844, 'MSE': 0.00013920932542532682, 'confusion_sha256': '555ac685515ef30d01a51135613607f7ec4c60ac53c28292e3d7f173ed36d617'}, '2021-11-04_098': {'PSNR': 38.90040588378906, 'MSE': 0.00012881297152489424, 'confusion_sha256': 'a6beda01a90aae13038df16fb931b4fdec8bf94d10e4027a9148bcb3756d070f'}, '2021-11-05_010': {'PSNR': 37.00151824951172, 'MSE': 0.0001994563644984737, 'confusion_sha256': 'bf0749f32bd5d80958f98e352fd7fd1131008676df80a3f46eb4f28b1ac25f72'}, '2021-11-05_024': {'PSNR': 38.845340728759766, 'MSE': 0.00013045647938270122, 'confusion_sha256': '1bd25ebf983cbd00fffc9cf8659e15393a561a6eace3e1b533ef944762731df3'}, '2021-11-05_035': {'PSNR': 38.225521087646484, 'MSE': 0.00015046920452732593, 'confusion_sha256': '23f7b9d374d780201f3077757527583beb1225381eb926082b57f3a4169d8efe'}, '2021-11-05_041': {'PSNR': 37.94324493408203, 'MSE': 0.00016057398170232773, 'confusion_sha256': 'e6375941a1fdea5e3321dee2238122ea334eea1c51beb4d9fd86ad68e6154b5e'}, '2021-11-05_046': {'PSNR': 35.822505950927734, 'MSE': 0.0002616672427393496, 'confusion_sha256': '37d8a2e9cdc0a84b7438fcb02912645900f27c501d1f824a3adede7dc38383f5'}, '2021-11-10_014': {'PSNR': 37.92229080200195, 'MSE': 0.00016135061741806567, 'confusion_sha256': 'e6510dad970ce41a35f9d809d214e3e9300e620010fdcc88dfcd73eac85d8ada'}, '2021-11-10_024': {'PSNR': 37.33868408203125, 'MSE': 0.00018455726967658848, 'confusion_sha256': 'd945f704aef8878db17ecf69be736bbdb13d93f4e5499f7c29a31bc42e81959b'}, '2021-11-10_029': {'PSNR': 37.95048522949219, 'MSE': 0.00016030656115617603, 'confusion_sha256': '76065de3abf7f309e3985213ad4785d89f595d58597cf79bde1b6e9a0f95f7cd'}, '2021-11-10_050': {'PSNR': 37.22018814086914, 'MSE': 0.0001896621979540214, 'confusion_sha256': 'b94d127de50692d41ba0666718afc1ac429a68f510931393d09d17e7b83f1af0'}}, 'minus1_alpha0.1': {'2021-11-03_046': {'PSNR': 39.504478454589844, 'MSE': 0.00011208618525415659, 'confusion_sha256': '12a79283c292e64e439aa3a508a48a4b79aad92aa66a919f06e4c1b505cf203b'}, '2021-11-03_047': {'PSNR': 38.409427642822266, 'MSE': 0.0001442304637748748, 'confusion_sha256': 'c872b12f217d64b7e7f97031757ce9cbb01fc394d5b8a44346040b749778ee85'}, '2021-11-03_057': {'PSNR': 37.30839157104492, 'MSE': 0.0001858491450548172, 'confusion_sha256': '9d164eeba19d0d1921c21ea102649cea84fec6c0bbb830e89f2a02c4764236d4'}, '2021-11-03_085': {'PSNR': 39.658958435058594, 'MSE': 0.00010816926078405231, 'confusion_sha256': 'ee617f071d4418738a87a45e9688a0b6295f84d04d8f2a71b282c2d92e1c51ba'}, '2021-11-03_090': {'PSNR': 39.579044342041016, 'MSE': 0.00011017820361303166, 'confusion_sha256': '55c32cb03f28c23eb3af7597cce6f559fa618bab9a6d73ad087a769c3bf43cb9'}, '2021-11-03_110': {'PSNR': 38.48360824584961, 'MSE': 0.0001417878520442173, 'confusion_sha256': '0fa7a52f5c25647b61412ad526ac22d40bdfcaf859cceae4d8c996b86dd7e6b0'}, '2021-11-04_010': {'PSNR': 36.857460021972656, 'MSE': 0.0002061835111817345, 'confusion_sha256': 'cca771642a02bf9b162821778d29d04adaf664b9d64f6a193bc751aa33510cdf'}, '2021-11-04_017': {'PSNR': 38.16506576538086, 'MSE': 0.00015257846098393202, 'confusion_sha256': '05610aafa0917bb5762013d6c88e68aae5c7dafad95e01914a0a9a93d18beb7e'}, '2021-11-04_024': {'PSNR': 38.302467346191406, 'MSE': 0.00014782676589675248, 'confusion_sha256': 'b753920aeb07ebbd5721e3c21c8d3a0632a64f1d55361ff128a0ba1f77534a5f'}, '2021-11-04_042': {'PSNR': 39.79904556274414, 'MSE': 0.00010473588190507144, 'confusion_sha256': 'a186add554b815e1981560085145a33acd0bee8132718d2e1a2d0cac0e087350'}, '2021-11-04_047': {'PSNR': 39.448638916015625, 'MSE': 0.0001135365673690103, 'confusion_sha256': '5a688bdb8d0a318edc5322a44e144542c9896dfa3ad749e2fe5f192905e823b0'}, '2021-11-04_049': {'PSNR': 40.15362548828125, 'MSE': 9.652441804064438e-05, 'confusion_sha256': '663e1e7398596f06fb12aca03ca1e9fa39e6be70197f32e3461b9226d70d61bd'}, '2021-11-04_055': {'PSNR': 39.721153259277344, 'MSE': 0.00010663115972420201, 'confusion_sha256': 'edc0f1d02e855da0cd6722af59b80cd0eb42561bdf9fc804e6d7925a503e05ed'}, '2021-11-04_061': {'PSNR': 39.71446990966797, 'MSE': 0.00010679545812308788, 'confusion_sha256': 'a79245940931ee2953d9ff06c8cb5b6aaa5cbff1306d56f52583dbf278bffebd'}, '2021-11-04_093': {'PSNR': 38.49284362792969, 'MSE': 0.00014148661284707487, 'confusion_sha256': '0c4750df4a807cfb5408514c2744551bcb7a11a738d4cb1d0464c2bbd72f4f6d'}, '2021-11-04_098': {'PSNR': 38.83191680908203, 'MSE': 0.00013086042599752545, 'confusion_sha256': '9bf1f5b28d2a656a05c37588b52102d54c674dad8090b12393ab112529d5f368'}, '2021-11-05_010': {'PSNR': 36.97058868408203, 'MSE': 0.00020088198652956635, 'confusion_sha256': '5fab299a74c84535834f00737c7838b63d790c970ba865e4806118f43b03e693'}, '2021-11-05_024': {'PSNR': 38.72041320800781, 'MSE': 0.00013426375517155975, 'confusion_sha256': '3bf862732ff99c2cff8860479505212d4d2048fdf1417d77dd56d009a1d8f3b7'}, '2021-11-05_035': {'PSNR': 38.15167999267578, 'MSE': 0.00015304956468753517, 'confusion_sha256': '01b3900646776fbbff267c32f504b380974ef87daed8bdae6ffd34b28f12e9e0'}, '2021-11-05_041': {'PSNR': 37.860992431640625, 'MSE': 0.00016364408656954765, 'confusion_sha256': '96e41c724be4aa0407ae092a8ce1023cd1ae87ec9ed39a1c0d06f6eb51b45c53'}, '2021-11-05_046': {'PSNR': 35.8121337890625, 'MSE': 0.0002622929750941694, 'confusion_sha256': '919c5c55e5be26195e513aac79cc0392d50425e19b7f9cc2fcd246d53ac943ba'}, '2021-11-10_014': {'PSNR': 37.8758544921875, 'MSE': 0.00016308513295371085, 'confusion_sha256': '02efc1b17df6a4dda23af082bc7a2d54e3a2ac41d7688621adfc1e65d694212c'}, '2021-11-10_024': {'PSNR': 37.33454513549805, 'MSE': 0.0001847333915065974, 'confusion_sha256': 'f60bb3abf0e51f4ce4f6036e3f39adb008075ccc280cb0c505fdbccf1cba6efb'}, '2021-11-10_029': {'PSNR': 37.91758346557617, 'MSE': 0.00016152569151017815, 'confusion_sha256': 'f23b5a6d0bf26bfb75b13384937693c9581804d1f7e1f207316ce642dd443ec7'}, '2021-11-10_050': {'PSNR': 37.190513610839844, 'MSE': 0.00019096270261798054, 'confusion_sha256': '8cd3ec56bd8bebe50e08eb9d21e2fac8ac749c1b13c97c2734bac2f0aca06c8d'}}, 'plus1_alpha0.25': {'2021-11-03_046': {'PSNR': 8.277036666870117, 'MSE': 0.1486949622631073, 'confusion_sha256': '65acef90a8030dca16eae33a2ccc7e1404ce7ba7d6d09a5d7c14b12df9e1c8a4'}, '2021-11-03_047': {'PSNR': -12.5802640914917, 'MSE': 18.114505767822266, 'confusion_sha256': '3d04f7a26a1bf259fa3734c9ed2e57bd34a59167ba32aad00c00962c96afe3e4'}, '2021-11-03_057': {'PSNR': -0.5277264714241028, 'MSE': 1.1292046308517456, 'confusion_sha256': '8f85aadc0b630d6e17553e566c7159263192edec6c86a565930f6c6be3f14948'}, '2021-11-03_085': {'PSNR': -8.534158706665039, 'MSE': 7.135361194610596, 'confusion_sha256': '365e74e2af6c468d1df8653f8cfef603cfa571228fba120bd2f2dff2bd39306b'}, '2021-11-03_090': {'PSNR': -7.22999382019043, 'MSE': 5.284445285797119, 'confusion_sha256': 'dfedf56ceb73a1e2ccb7ba8ad3637b73c72d3dab40fa108d5c26cb9533ce937b'}, '2021-11-03_110': {'PSNR': 12.149971008300781, 'MSE': 0.06095408275723457, 'confusion_sha256': 'fd6fc38362dea4862579ba7cfc6ef61bf796a00a10d1ea7c83101f034bc8c422'}, '2021-11-04_010': {'PSNR': -6.972059726715088, 'MSE': 4.979732036590576, 'confusion_sha256': '768bcb93e017a0890aaa9f8ba136b8b56b2bf5cab1372df8a21dd4d2e5ffb600'}, '2021-11-04_017': {'PSNR': -3.0808913707733154, 'MSE': 2.0327742099761963, 'confusion_sha256': 'fa0a264501321e5a175dd0bdfa6a656fa4cc1f7db5dfd7a1f37f7247958f09ca'}, '2021-11-04_024': {'PSNR': -2.196054220199585, 'MSE': 1.658079743385315, 'confusion_sha256': '984d6008696749b3462f01087b3140f5f18c83b873cc6c1c138ff3ae114bddeb'}, '2021-11-04_042': {'PSNR': -5.517134666442871, 'MSE': 3.5621604919433594, 'confusion_sha256': '03fdaf6ef0aa9233d17059cc32a28a9f827b6ef8fa9ab3186dd4c900264eecfb'}, '2021-11-04_047': {'PSNR': -10.676491737365723, 'MSE': 11.685553550720215, 'confusion_sha256': '198ee43b581c33226515a8ffd38a676870ba5bd1231349faafaccb7c6fe8be15'}, '2021-11-04_049': {'PSNR': -12.803421974182129, 'MSE': 19.069631576538086, 'confusion_sha256': '484d9c9d11a6e8d567548d3917ff7e38ad81a304bb87362b17831100e7c36144'}, '2021-11-04_055': {'PSNR': 3.5782041549682617, 'MSE': 0.43871206045150757, 'confusion_sha256': '3135c3b6cac4213f18ce2c168352d7f69c7c6c6c764ad468ee73338fb349e2d9'}, '2021-11-04_061': {'PSNR': -0.21835699677467346, 'MSE': 1.0515639781951904, 'confusion_sha256': '3d719225209b182810dfaac5a05398524d9018da717b153b995cbeb949091c43'}, '2021-11-04_093': {'PSNR': -0.7805860042572021, 'MSE': 1.1969020366668701, 'confusion_sha256': '59e39c80d583e00071cae25bb81f32b9d138219848fe8b5cb1a48476efb1c84e'}, '2021-11-04_098': {'PSNR': -7.466648578643799, 'MSE': 5.580394744873047, 'confusion_sha256': 'f8b05fc5a9adf39caa8436f23ef4b5f010abd26962fc154910eb066676b43029'}, '2021-11-05_010': {'PSNR': -4.319344997406006, 'MSE': 2.7035505771636963, 'confusion_sha256': '7a01f278b319d941c4fe548b746a9f99ec2b4e348ab953cd1e65e4051b509129'}, '2021-11-05_024': {'PSNR': 2.2303483486175537, 'MSE': 0.5983635783195496, 'confusion_sha256': 'afeb3f00632d036adaef01c1901e14f30098b8c48990343c5a29efb02e98456c'}, '2021-11-05_035': {'PSNR': 8.731414794921875, 'MSE': 0.13392402231693268, 'confusion_sha256': 'c7704dbb19830007798127ae5295984e6149965290f37e931c9d5a13aacc3058'}, '2021-11-05_041': {'PSNR': -1.4292829036712646, 'MSE': 1.3897231817245483, 'confusion_sha256': 'b8ccff5a7dfa4918a7a9812f93743d402f5a16905de6ba3163781479638303b6'}, '2021-11-05_046': {'PSNR': 9.312551498413086, 'MSE': 0.1171506717801094, 'confusion_sha256': '58ecfc75d2e41925458a71b520839ddb8570fbbb4e2a9446ccdc2409e9fee2eb'}, '2021-11-10_014': {'PSNR': -30.780231475830078, 'MSE': 1196.8046875, 'confusion_sha256': '6c5c3a2302df06978061318210a83cbc2eedfab24f384375af4b4c3a941e6303'}, '2021-11-10_024': {'PSNR': -27.06857681274414, 'MSE': 509.1642150878906, 'confusion_sha256': '68d64fc62f66eb3d725c098fa442f6bce07277635bb191f187e3951d7754232c'}, '2021-11-10_029': {'PSNR': -24.743825912475586, 'MSE': 298.1142883300781, 'confusion_sha256': '6a73b0063fad1dce5373cc13aec6127d6a84cde5abb791b283f843d1e2245264'}, '2021-11-10_050': {'PSNR': -5.0873236656188965, 'MSE': 3.2265052795410156, 'confusion_sha256': 'e4eb77276872c0426737fb89dd4bad0364589bc81b1c173c92c4e321f0cbe707'}}, 'minus1_alpha0.25': {'2021-11-03_046': {'PSNR': 7.803365707397461, 'MSE': 0.1658301204442978, 'confusion_sha256': 'f62fe7edcb36dce8e9569e42182b90e68c70a2eca54970d1df07a942b49bed50'}, '2021-11-03_047': {'PSNR': -14.702699661254883, 'MSE': 29.530447006225586, 'confusion_sha256': 'c6524665f3f4b49a2a63e4281689d77fc8172bb18f8f4c735516c38d653bbdf6'}, '2021-11-03_057': {'PSNR': -1.7272698879241943, 'MSE': 1.4884251356124878, 'confusion_sha256': '77f9329a014c58556af219a02debd7506b851e4136fe38f55b7160dcb0f03d3e'}, '2021-11-03_085': {'PSNR': -0.886996865272522, 'MSE': 1.2265907526016235, 'confusion_sha256': '9f4e08df0829bd23df769ca95dc781c5ba0221e7fddd7e97e792c0ee51b112a4'}, '2021-11-03_090': {'PSNR': -5.25463342666626, 'MSE': 3.3532299995422363, 'confusion_sha256': 'f829e11b9b26f2a568acfaec4dee7c85ded2eeded0403b05b7e60e78af5ef261'}, '2021-11-03_110': {'PSNR': 12.107354164123535, 'MSE': 0.061555165797472, 'confusion_sha256': '3bd0c6c14d19529ca464c9e9d018f370cf70edf3c5f576eb4813d89012b4ce80'}, '2021-11-04_010': {'PSNR': -11.525019645690918, 'MSE': 14.206987380981445, 'confusion_sha256': '5cc1e0457065f19fcd3784acba2edb3575dfed4ffbc4a237ef93f187d8d26bc4'}, '2021-11-04_017': {'PSNR': -16.70313835144043, 'MSE': 46.80733871459961, 'confusion_sha256': '6d5dff939641d5931183cf0ce0c5f01069808846deb9a36ce6938362a3a93cf5'}, '2021-11-04_024': {'PSNR': -3.812268018722534, 'MSE': 2.405618906021118, 'confusion_sha256': 'a8b78527c556e8551ddc88835976e688b1681a71f297b592801ae75ba8b110d7'}, '2021-11-04_042': {'PSNR': -5.1902174949646, 'MSE': 3.303861379623413, 'confusion_sha256': 'e1f5da754712f846b0b1d0f480986e1b55ff7955d543138551699f3905f2ae59'}, '2021-11-04_047': {'PSNR': -11.66427993774414, 'MSE': 14.669931411743164, 'confusion_sha256': '2c0acff73872e99170d9cf5b5a951a69d68762f0e9be522f04368a117ebc2211'}, '2021-11-04_049': {'PSNR': -15.672592163085938, 'MSE': 36.919795989990234, 'confusion_sha256': 'ed86060e37b1b4bdf0e0ba903ec0b396ec5fb7bed333a85f3bbcbf2fab5bbaa4'}, '2021-11-04_055': {'PSNR': 4.529160499572754, 'MSE': 0.3524389863014221, 'confusion_sha256': 'd1fdd99f09ffee5d8f85314f696f08b92b2775d670ee34eafa4c2c4e1fdf299d'}, '2021-11-04_061': {'PSNR': 0.5494163036346436, 'MSE': 0.8811672925949097, 'confusion_sha256': 'fcc297032a61e9dd0c93c84398cb0766b87a44b59950b22f1c53a20d8391c822'}, '2021-11-04_093': {'PSNR': 1.5230262279510498, 'MSE': 0.7042021751403809, 'confusion_sha256': '201ff6250ed202e11af64a04a933a4abefa26d3b7eec5e94bf1cf504f6c4e516'}, '2021-11-04_098': {'PSNR': -1.3938651084899902, 'MSE': 1.378435730934143, 'confusion_sha256': '7b6429241b13abd1a0db072fce898cc6e61eb3600af38093283fd1eb498fbcc2'}, '2021-11-05_010': {'PSNR': -4.2936272621154785, 'MSE': 2.6875884532928467, 'confusion_sha256': 'ccc2e21594932c2d84ae7f85e4f2b841b1ff2b8d18d9bb17489807d5449321d9'}, '2021-11-05_024': {'PSNR': 0.510915994644165, 'MSE': 0.8890135884284973, 'confusion_sha256': 'd0d86a855ead3fd164bb2a84237c955d3af545887db404b9276c02a499162aec'}, '2021-11-05_035': {'PSNR': 7.533391952514648, 'MSE': 0.17646588385105133, 'confusion_sha256': '82d345d93b7ba6970f2bcaa3c9288b7a519da0da6d4576f57efd17f5b46e32e6'}, '2021-11-05_041': {'PSNR': 1.2950642108917236, 'MSE': 0.7421532273292542, 'confusion_sha256': '3737be4f4b370c6ae02ab9dbb192ff2d250d5dbc48fa8f3cd4357dc27c25b860'}, '2021-11-05_046': {'PSNR': 8.538073539733887, 'MSE': 0.14002083241939545, 'confusion_sha256': 'da173b491f28cf66388db7c4ab2663d91cdc1283d4717da4d1f46018b9d239f9'}, '2021-11-10_014': {'PSNR': -30.209529876708984, 'MSE': 1049.4293212890625, 'confusion_sha256': 'bb6090713bece762a9c273606dd63e2afd2ed4d3e968206392c4fa9ceb59b44d'}, '2021-11-10_024': {'PSNR': -25.037992477416992, 'MSE': 319.0064392089844, 'confusion_sha256': 'dfea492ea7005f6b688487d4e6e39ee5073c03a686d3af80532535462d32b927'}, '2021-11-10_029': {'PSNR': -19.77103042602539, 'MSE': 94.86436462402344, 'confusion_sha256': '2840d205bb1e52c8a8d4568bac06a0b5fe2589b441421e8b84cafc2e50ab77f3'}, '2021-11-10_050': {'PSNR': -3.7158210277557373, 'MSE': 2.3527843952178955, 'confusion_sha256': '8dda4c1f03bd47e7ab1f633b9e405aac429b961b1286768604ef795c73beaa53'}}, 'plus1_alpha1': {'2021-11-03_046': {'PSNR': 39.93577194213867, 'MSE': 0.00010148985165869817, 'confusion_sha256': '14d73e1d988c3f12445ad7605030a4aae6d00bedfbcd0a2590e73ce6a51a9f86'}, '2021-11-03_047': {'PSNR': 38.74766540527344, 'MSE': 0.0001334237604169175, 'confusion_sha256': 'e33773f13e39c415c4a16615b47c307f9cb5a3f3a57527dbec2852c3949532c0'}, '2021-11-03_057': {'PSNR': 38.011871337890625, 'MSE': 0.00015805664588697255, 'confusion_sha256': 'f8d10f8c036a225b811d4c6163a0dacf823f541ced6875a3a73ee641e4de98d6'}, '2021-11-03_085': {'PSNR': 40.45233917236328, 'MSE': 9.010852227220312e-05, 'confusion_sha256': '29b10d98e58cd2f21f568b68b97469f820580e93f40ddf739b3d4dd72c5029f9'}, '2021-11-03_090': {'PSNR': 40.327449798583984, 'MSE': 9.273734031012282e-05, 'confusion_sha256': 'a30335633bde701a59bf9ab0ea2730a99f6ecf268b4ce149f5d12a23eaadb1a5'}, '2021-11-03_110': {'PSNR': 39.5364875793457, 'MSE': 0.00011126306344522163, 'confusion_sha256': '1ef25a4011bd2eb1aa8106f826fa5744da1540ee530ca2398a90e6bfaf120cc2'}, '2021-11-04_010': {'PSNR': 37.031429290771484, 'MSE': 0.0001980874949367717, 'confusion_sha256': '83ef051c01af9cc064d65b6bdb1a860ca41bfceac6c53e4ffa3d1f3899a43541'}, '2021-11-04_017': {'PSNR': 38.305030822753906, 'MSE': 0.00014773955626878887, 'confusion_sha256': '30fd19e55413ee336efde550a6d18744310dbac363ed0df36852443f0f7466fc'}, '2021-11-04_024': {'PSNR': 38.92214584350586, 'MSE': 0.00012816974776796997, 'confusion_sha256': '5117e1755188e0081172a6cabc50fe17f22ee83b1756e117a61eb18ab583899f'}, '2021-11-04_042': {'PSNR': 40.36432647705078, 'MSE': 9.195320308208466e-05, 'confusion_sha256': 'e811ffe794b72420cd8b4029771d035b29533fa1af2f3059be976693c1a27121'}, '2021-11-04_047': {'PSNR': 40.204830169677734, 'MSE': 9.5393079391215e-05, 'confusion_sha256': 'd9ce18ab865496e7b49ff3f44fc2baf2094b6ed47a63a9a7ba7becfa1da48aa7'}, '2021-11-04_049': {'PSNR': 40.76326370239258, 'MSE': 8.388292917516083e-05, 'confusion_sha256': '0739e78fdce2fd493a0ba10a70b17775e0f9e31c6c12f242f23f044dc02d053c'}, '2021-11-04_055': {'PSNR': 40.6777458190918, 'MSE': 8.555103704566136e-05, 'confusion_sha256': 'd114df89306eedf47535155128aa09f186d1af10d0311737d6c3df2b95f67762'}, '2021-11-04_061': {'PSNR': 40.669185638427734, 'MSE': 8.571981743443757e-05, 'confusion_sha256': '24a36c34d291e115447b406535a1dc828672e1b33910da5649dd8be417982bf6'}, '2021-11-04_093': {'PSNR': 39.108089447021484, 'MSE': 0.00012279787915758789, 'confusion_sha256': '7ffb0b314167f9997093033d1e058cc6b4eb1d7460017a7dd48134cbf9054f4c'}, '2021-11-04_098': {'PSNR': 39.419681549072266, 'MSE': 0.00011429621372371912, 'confusion_sha256': '7e4d06de321d1a215030015fb0901ec49f4ea36c1ab0e742961185696052e8d6'}, '2021-11-05_010': {'PSNR': 37.400718688964844, 'MSE': 0.00018193975847680122, 'confusion_sha256': '664274c7764a4ee9745f1e9512d3516202c6110b3b988d991867f67dcc3f9672'}, '2021-11-05_024': {'PSNR': 39.66768264770508, 'MSE': 0.0001079522626241669, 'confusion_sha256': '6d9b4a0bb4c0201e00b2e992f1c591ad95546b736c2cc170fd0e04f71b494331'}, '2021-11-05_035': {'PSNR': 38.80119323730469, 'MSE': 0.0001317894784733653, 'confusion_sha256': '7344af1615b33e4b2fc3dfe6aeb65a8356552888c70e5cb92ff02fbc59d35656'}, '2021-11-05_041': {'PSNR': 38.47829055786133, 'MSE': 0.00014196158736012876, 'confusion_sha256': '84e1cbc4065644afd3badaf58755d846956b9d3bc062694b9c274a35bc29b580'}, '2021-11-05_046': {'PSNR': 36.15117263793945, 'MSE': 0.0002425952407065779, 'confusion_sha256': 'f556d6048653f677f798897c43d20b1cf1ac1bf710d767c3889f12d3973c7a16'}, '2021-11-10_014': {'PSNR': 38.18336486816406, 'MSE': 0.00015193699800875038, 'confusion_sha256': '03c6ca79b8a384401a6f5295141949e807a064f09bbccbbbc75e960b5bb054ee'}, '2021-11-10_024': {'PSNR': 37.86553192138672, 'MSE': 0.00016347326163668185, 'confusion_sha256': 'fd4ff1567e9ea0800587d9a93417f44d2d3db92e93575c08e8ead678e01f902b'}, '2021-11-10_029': {'PSNR': 38.2700080871582, 'MSE': 0.00014893573825247586, 'confusion_sha256': '07c8908d21e62c73ba4b96e0ad6f2511bb20bc2b81df342f3278f649fdbd3911'}, '2021-11-10_050': {'PSNR': 37.33919143676758, 'MSE': 0.0001845357910497114, 'confusion_sha256': 'd60d3fcdb457c10e4e7f2a974e2ad732eb532cd422348f233bf2fe206b135c75'}}, 'minus1_alpha1': {'2021-11-03_046': {'PSNR': 39.77946090698242, 'MSE': 0.00010520912474021316, 'confusion_sha256': '001937a1365ad6cc97f4063edfc953d10e71ebb98931acdc77ea4a265c83e081'}, '2021-11-03_047': {'PSNR': 38.6917724609375, 'MSE': 0.00013515203318092972, 'confusion_sha256': '91462bb1d1c1b5cb20cde612023104ebef082c555a870907b728124682abf04f'}, '2021-11-03_057': {'PSNR': 38.02188491821289, 'MSE': 0.0001576926588313654, 'confusion_sha256': '03e698b21cdae41b5991210b5541e51fb417155991d248b5253f23154b751779'}, '2021-11-03_085': {'PSNR': 40.30281448364258, 'MSE': 9.326493454864249e-05, 'confusion_sha256': '14ac21f8bde27adfe23129111e8b9a0a9dbefb667fb1f8ec88996959689b3430'}, '2021-11-03_090': {'PSNR': 40.20442581176758, 'MSE': 9.540192695567384e-05, 'confusion_sha256': '4ab0686987aa4fe61cd6fe086733b30b50ffad78476190896b0b7e685be6794a'}, '2021-11-03_110': {'PSNR': 39.50486755371094, 'MSE': 0.0001120761371566914, 'confusion_sha256': 'd983700844c54998edbad82d50ff881a02f3fe4e649a801c94806f95288e3590'}, '2021-11-04_010': {'PSNR': 37.249549865722656, 'MSE': 0.00018838440882973373, 'confusion_sha256': '72125cc4e0945192590c0b6a6adf0ac0fa9d261db7638b41841182067083f089'}, '2021-11-04_017': {'PSNR': 38.4840087890625, 'MSE': 0.00014177474076859653, 'confusion_sha256': 'f54f0fbcd698b2e327094a26203cf96cc526816f804931dc45300714855664a1'}, '2021-11-04_024': {'PSNR': 38.65106201171875, 'MSE': 0.00013642494741361588, 'confusion_sha256': 'aaab1344b0b32c6579c30d2c1b9a2ab506e7070e64c095b01d067be589944cd2'}, '2021-11-04_042': {'PSNR': 40.1712532043457, 'MSE': 9.613343718228862e-05, 'confusion_sha256': 'ecf46b820c15b8fdbe7bc256638880c4da92226f62121ba3031b882c1cdbde0a'}, '2021-11-04_047': {'PSNR': 39.96493148803711, 'MSE': 0.00010081072832690552, 'confusion_sha256': '8c669512fa42a4202dc9a97013d6bbf57164d644455f868312baa26fb1700ffb'}, '2021-11-04_049': {'PSNR': 40.5753059387207, 'MSE': 8.759294723859057e-05, 'confusion_sha256': '2feaf15b7b4406276f7ea7f49196cc1351f5ce9903db5e60b1d61fc6289e6ce5'}, '2021-11-04_055': {'PSNR': 40.35194778442383, 'MSE': 9.221574146067724e-05, 'confusion_sha256': '8bb6db7eda58f13c124fae1ef3111040bf81bb235a3a2746542bd6a04ba19c08'}, '2021-11-04_061': {'PSNR': 40.27669143676758, 'MSE': 9.382760617882013e-05, 'confusion_sha256': '04a6dbca8d073ee68a2b42cfaf7fde08bde3585280818899137956d8a52ad4bf'}, '2021-11-04_093': {'PSNR': 39.054813385009766, 'MSE': 0.00012431357754394412, 'confusion_sha256': 'bc72c1334fe11b01342d256c1caeccbc0fa9acf89bdeab81108c33acb00ef82e'}, '2021-11-04_098': {'PSNR': 39.23973083496094, 'MSE': 0.000119131596875377, 'confusion_sha256': '971f9c205a4edd1e94411287906ea9dedc16bff36849a5036def85eee51a85d7'}, '2021-11-05_010': {'PSNR': 37.39585494995117, 'MSE': 0.00018214374722447246, 'confusion_sha256': 'ce54101d30622f3dae17ff86bf51e114a9c8e97ccdd966cb96e88e15f6832673'}, '2021-11-05_024': {'PSNR': 39.5966682434082, 'MSE': 0.00010973198368446901, 'confusion_sha256': 'b6ad1cf047c843b02bb6ec8a4fc7471e361ae6e60af873d187f7232aeaeec4fc'}, '2021-11-05_035': {'PSNR': 38.71174240112305, 'MSE': 0.00013453203428070992, 'confusion_sha256': 'fe0a70b0902d6cfe063291a591a75d5d512a1b3e5debec7640de6390e82d4bd9'}, '2021-11-05_041': {'PSNR': 38.43107223510742, 'MSE': 0.00014351338904816657, 'confusion_sha256': '8f64b2f835cd99af39a2c8ff765294f524561c63d7b1d7bff04cedfc0a8d40f5'}, '2021-11-05_046': {'PSNR': 36.058353424072266, 'MSE': 0.00024783617118373513, 'confusion_sha256': '19479ea65b8906b463fa586dd42da26cc470b62b521d767df06e822796e5f689'}, '2021-11-10_014': {'PSNR': 38.06553649902344, 'MSE': 0.00015611555136274546, 'confusion_sha256': '184a55cb0afb8576ba2905207ba66ac33681b36d14b5cef518e23359fe94faf7'}, '2021-11-10_024': {'PSNR': 37.631168365478516, 'MSE': 0.00017253738769795746, 'confusion_sha256': '25267115d55c6313a161747f9f83e562b8f251bfec0f28409bbf9720f3d28a71'}, '2021-11-10_029': {'PSNR': 38.259586334228516, 'MSE': 0.00014929348253645003, 'confusion_sha256': '8435416170e7932b77ebd421892a69ef0d8e9aeee4e601e17f00475e4b46a569'}, '2021-11-10_050': {'PSNR': 37.57216262817383, 'MSE': 0.00017489738820586354, 'confusion_sha256': '8b3b7203ff04ebcd9a8a43adfd841cd6fc614ba8b696ecd21361a0148e2f06a8'}}}}

RUN=WORK/('numerical_trace_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
for filename,source in FILES.items():(RUN/filename).write_text(source)
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'expected.json').write_text(json.dumps(EXPECTED,indent=2))
(RUN/'source_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in ['models/CRSDUN.py','dataset.py','utils.py','public252-v1.json']},indent=2))
with (RUN/'local_checks.log').open('w') as log:
    result=subprocess.run([sys.executable,str(RUN/'verify_numerical_trace.py'),'--code',str(CODE)],cwd=RUN,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    log.write(result.stdout);print(result.stdout)
    result.check_returncode()
print('Output folder:',RUN)

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
PASS: real five-stage architecture, clean/fractional operators, bitwise unchanged outputs, hook cleanup including exceptions, denominator counts and spatial error partitions. Small random-input test; not trained full-frame evaluation.

Output folder: /kaggle/working/numerical_trace_epoch441_20261011_070941_283789

In [3]:
from IPython.display import display,FileLink
try:
    with (RUN/'console.log').open('w') as log:
        command=[sys.executable,'-u',str(RUN/'numerical_trace.py'),
                 '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
                 '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json'),'--expected',str(RUN/'expected.json')]
        proc=subprocess.Popen(command,cwd=CODE,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)
        try:
            for line in proc.stdout:
                print(line,end='',flush=True)
                log.write(line);log.flush()
            code=proc.wait()
            if code: raise subprocess.CalledProcessError(code,command)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try: proc.wait(timeout=10)
                except subprocess.TimeoutExpired: proc.kill();proc.wait()
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
clean: 1/25, traced/untraced identical, prior metrics reproduced; 0.3min
clean: 2/25, traced/untraced identical, prior metrics reproduced; 0.5min
clean: 3/25, traced/untraced identical, prior metrics reproduced; 0.7min
clean: 4/25, traced/untraced identical, prior metrics reproduced; 0.9min
clean: 5/25, traced/untraced identical, prior metrics reproduced; 1.1min
clean: 6/25, traced/untraced identical, prior metrics reproduced; 1.3min
clean: 7/25, traced/untraced identical, prior metrics reproduced; 1.5min
clean: 8/25, traced/untraced identical, prior metrics reproduced; 1.7min
clean: 9/25, traced/untraced identical, prior metrics reproduced; 1.9min
clean: 10/25, traced/untraced identical, prior metrics reproduced; 2.1min
clean: 11/25, traced/untraced identical, prior metrics reproduced; 2.3min
clean: 12/25, traced/untraced identical, prior metrics reproduced; 2.5min
clean: 13/25, traced/untraced identical, prior metrics reproduced; 2.8min
clean: 14/25, traced/untraced identical, prior metrics reproduced; 3.0min
clean: 15/25, traced/untraced identical, prior metrics reproduced; 3.2min
clean: 16/25, traced/untraced identical, prior metrics reproduced; 3.4min
clean: 17/25, traced/untraced identical, prior metrics reproduced; 3.6min
clean: 18/25, traced/untraced identical, prior metrics reproduced; 3.8min
clean: 19/25, traced/untraced identical, prior metrics reproduced; 4.0min
clean: 20/25, traced/untraced identical, prior metrics reproduced; 4.2min
clean: 21/25, traced/untraced identical, prior metrics reproduced; 4.4min
clean: 22/25, traced/untraced identical, prior metrics reproduced; 4.6min
clean: 23/25, traced/untraced identical, prior metrics reproduced; 4.8min
clean: 24/25, traced/untraced identical, prior metrics reproduced; 5.0min
clean: 25/25, traced/untraced identical, prior metrics reproduced; 5.2min
plus1_alpha0.1: 1/25, traced/untraced identical, prior metrics reproduced; 5.4min
plus1_alpha0.1: 2/25, traced/untraced identical, prior metrics reproduced; 5.6min
plus1_alpha0.1: 3/25, traced/untraced identical, prior metrics reproduced; 5.8min
plus1_alpha0.1: 4/25, traced/untraced identical, prior metrics reproduced; 6.0min
plus1_alpha0.1: 5/25, traced/untraced identical, prior metrics reproduced; 6.2min
plus1_alpha0.1: 6/25, traced/untraced identical, prior metrics reproduced; 6.4min
plus1_alpha0.1: 7/25, traced/untraced identical, prior metrics reproduced; 6.6min
plus1_alpha0.1: 8/25, traced/untraced identical, prior metrics reproduced; 6.8min
plus1_alpha0.1: 9/25, traced/untraced identical, prior metrics reproduced; 7.0min
plus1_alpha0.1: 10/25, traced/untraced identical, prior metrics reproduced; 7.2min
plus1_alpha0.1: 11/25, traced/untraced identical, prior metrics reproduced; 7.4min
plus1_alpha0.1: 12/25, traced/untraced identical, prior metrics reproduced; 7.6min
plus1_alpha0.1: 13/25, traced/untraced identical, prior metrics reproduced; 7.8min
plus1_alpha0.1: 14/25, traced/untraced identical, prior metrics reproduced; 8.0min
plus1_alpha0.1: 15/25, traced/untraced identical, prior metrics reproduced; 8.2min
plus1_alpha0.1: 16/25, traced/untraced identical, prior metrics reproduced; 8.3min
plus1_alpha0.1: 17/25, traced/untraced identical, prior metrics reproduced; 8.5min
plus1_alpha0.1: 18/25, traced/untraced identical, prior metrics reproduced; 8.7min
plus1_alpha0.1: 19/25, traced/untraced identical, prior metrics reproduced; 8.9min
plus1_alpha0.1: 20/25, traced/untraced identical, prior metrics reproduced; 9.1min
plus1_alpha0.1: 21/25, traced/untraced identical, prior metrics reproduced; 9.3min
plus1_alpha0.1: 22/25, traced/untraced identical, prior metrics reproduced; 9.5min
plus1_alpha0.1: 23/25, traced/untraced identical, prior metrics reproduced; 9.7min
plus1_alpha0.1: 24/25, traced/untraced identical, prior metrics reproduced; 9.9min
plus1_alpha0.1: 25/25, traced/untraced identical, prior metrics reproduced; 10.1min
minus1_alpha0.1: 1/25, traced/untraced identical, prior metrics reproduced; 10.3min
minus1_alpha0.1: 2/25, traced/untraced identical, prior metrics reproduced; 10.5min
minus1_alpha0.1: 3/25, traced/untraced identical, prior metrics reproduced; 10.7min
minus1_alpha0.1: 4/25, traced/untraced identical, prior metrics reproduced; 10.9min
minus1_alpha0.1: 5/25, traced/untraced identical, prior metrics reproduced; 11.1min
minus1_alpha0.1: 6/25, traced/untraced identical, prior metrics reproduced; 11.3min
minus1_alpha0.1: 7/25, traced/untraced identical, prior metrics reproduced; 11.5min
minus1_alpha0.1: 8/25, traced/untraced identical, prior metrics reproduced; 11.7min
minus1_alpha0.1: 9/25, traced/untraced identical, prior metrics reproduced; 11.9min
minus1_alpha0.1: 10/25, traced/untraced identical, prior metrics reproduced; 12.1min
minus1_alpha0.1: 11/25, traced/untraced identical, prior metrics reproduced; 12.3min
minus1_alpha0.1: 12/25, traced/untraced identical, prior metrics reproduced; 12.5min
minus1_alpha0.1: 13/25, traced/untraced identical, prior metrics reproduced; 12.7min
minus1_alpha0.1: 14/25, traced/untraced identical, prior metrics reproduced; 12.9min
minus1_alpha0.1: 15/25, traced/untraced identical, prior metrics reproduced; 13.1min
minus1_alpha0.1: 16/25, traced/untraced identical, prior metrics reproduced; 13.3min
minus1_alpha0.1: 17/25, traced/untraced identical, prior metrics reproduced; 13.4min
minus1_alpha0.1: 18/25, traced/untraced identical, prior metrics reproduced; 13.6min
minus1_alpha0.1: 19/25, traced/untraced identical, prior metrics reproduced; 13.8min
minus1_alpha0.1: 20/25, traced/untraced identical, prior metrics reproduced; 14.0min
minus1_alpha0.1: 21/25, traced/untraced identical, prior metrics reproduced; 14.2min
minus1_alpha0.1: 22/25, traced/untraced identical, prior metrics reproduced; 14.4min
minus1_alpha0.1: 23/25, traced/untraced identical, prior metrics reproduced; 14.6min
minus1_alpha0.1: 24/25, traced/untraced identical, prior metrics reproduced; 14.8min
minus1_alpha0.1: 25/25, traced/untraced identical, prior metrics reproduced; 15.0min
plus1_alpha0.25: 1/25, traced/untraced identical, prior metrics reproduced; 15.2min
plus1_alpha0.25: 2/25, traced/untraced identical, prior metrics reproduced; 15.4min
plus1_alpha0.25: 3/25, traced/untraced identical, prior metrics reproduced; 15.6min
plus1_alpha0.25: 4/25, traced/untraced identical, prior metrics reproduced; 15.8min
plus1_alpha0.25: 5/25, traced/untraced identical, prior metrics reproduced; 16.0min
plus1_alpha0.25: 6/25, traced/untraced identical, prior metrics reproduced; 16.2min
plus1_alpha0.25: 7/25, traced/untraced identical, prior metrics reproduced; 16.4min
plus1_alpha0.25: 8/25, traced/untraced identical, prior metrics reproduced; 16.6min
plus1_alpha0.25: 9/25, traced/untraced identical, prior metrics reproduced; 16.8min
plus1_alpha0.25: 10/25, traced/untraced identical, prior metrics reproduced; 17.0min
plus1_alpha0.25: 11/25, traced/untraced identical, prior metrics reproduced; 17.2min
plus1_alpha0.25: 12/25, traced/untraced identical, prior metrics reproduced; 17.4min
plus1_alpha0.25: 13/25, traced/untraced identical, prior metrics reproduced; 17.6min
plus1_alpha0.25: 14/25, traced/untraced identical, prior metrics reproduced; 17.8min
plus1_alpha0.25: 15/25, traced/untraced identical, prior metrics reproduced; 18.0min
plus1_alpha0.25: 16/25, traced/untraced identical, prior metrics reproduced; 18.2min
plus1_alpha0.25: 17/25, traced/untraced identical, prior metrics reproduced; 18.4min
plus1_alpha0.25: 18/25, traced/untraced identical, prior metrics reproduced; 18.6min
plus1_alpha0.25: 19/25, traced/untraced identical, prior metrics reproduced; 18.7min
plus1_alpha0.25: 20/25, traced/untraced identical, prior metrics reproduced; 18.9min
plus1_alpha0.25: 21/25, traced/untraced identical, prior metrics reproduced; 19.1min
plus1_alpha0.25: 22/25, traced/untraced identical, prior metrics reproduced; 19.3min
plus1_alpha0.25: 23/25, traced/untraced identical, prior metrics reproduced; 19.5min
plus1_alpha0.25: 24/25, traced/untraced identical, prior metrics reproduced; 19.7min
plus1_alpha0.25: 25/25, traced/untraced identical, prior metrics reproduced; 19.9min
minus1_alpha0.25: 1/25, traced/untraced identical, prior metrics reproduced; 20.1min
minus1_alpha0.25: 2/25, traced/untraced identical, prior metrics reproduced; 20.3min
minus1_alpha0.25: 3/25, traced/untraced identical, prior metrics reproduced; 20.5min
minus1_alpha0.25: 4/25, traced/untraced identical, prior metrics reproduced; 20.7min
minus1_alpha0.25: 5/25, traced/untraced identical, prior metrics reproduced; 20.9min
minus1_alpha0.25: 6/25, traced/untraced identical, prior metrics reproduced; 21.1min
minus1_alpha0.25: 7/25, traced/untraced identical, prior metrics reproduced; 21.3min
minus1_alpha0.25: 8/25, traced/untraced identical, prior metrics reproduced; 21.5min
minus1_alpha0.25: 9/25, traced/untraced identical, prior metrics reproduced; 21.7min
minus1_alpha0.25: 10/25, traced/untraced identical, prior metrics reproduced; 21.9min
minus1_alpha0.25: 11/25, traced/untraced identical, prior metrics reproduced; 22.1min
minus1_alpha0.25: 12/25, traced/untraced identical, prior metrics reproduced; 22.3min
minus1_alpha0.25: 13/25, traced/untraced identical, prior metrics reproduced; 22.5min
minus1_alpha0.25: 14/25, traced/untraced identical, prior metrics reproduced; 22.7min
minus1_alpha0.25: 15/25, traced/untraced identical, prior metrics reproduced; 22.9min
minus1_alpha0.25: 16/25, traced/untraced identical, prior metrics reproduced; 23.1min
minus1_alpha0.25: 17/25, traced/untraced identical, prior metrics reproduced; 23.3min
minus1_alpha0.25: 18/25, traced/untraced identical, prior metrics reproduced; 23.5min
minus1_alpha0.25: 19/25, traced/untraced identical, prior metrics reproduced; 23.7min
minus1_alpha0.25: 20/25, traced/untraced identical, prior metrics reproduced; 23.9min
minus1_alpha0.25: 21/25, traced/untraced identical, prior metrics reproduced; 24.1min
minus1_alpha0.25: 22/25, traced/untraced identical, prior metrics reproduced; 24.3min
minus1_alpha0.25: 23/25, traced/untraced identical, prior metrics reproduced; 24.5min
minus1_alpha0.25: 24/25, traced/untraced identical, prior metrics reproduced; 24.7min
minus1_alpha0.25: 25/25, traced/untraced identical, prior metrics reproduced; 24.9min
plus1_alpha1: 1/25, traced/untraced identical, prior metrics reproduced; 25.1min
plus1_alpha1: 2/25, traced/untraced identical, prior metrics reproduced; 25.3min
plus1_alpha1: 3/25, traced/untraced identical, prior metrics reproduced; 25.5min
plus1_alpha1: 4/25, traced/untraced identical, prior metrics reproduced; 25.7min
plus1_alpha1: 5/25, traced/untraced identical, prior metrics reproduced; 25.9min
plus1_alpha1: 6/25, traced/untraced identical, prior metrics reproduced; 26.0min
plus1_alpha1: 7/25, traced/untraced identical, prior metrics reproduced; 26.2min
plus1_alpha1: 8/25, traced/untraced identical, prior metrics reproduced; 26.4min
plus1_alpha1: 9/25, traced/untraced identical, prior metrics reproduced; 26.6min
plus1_alpha1: 10/25, traced/untraced identical, prior metrics reproduced; 26.8min
plus1_alpha1: 11/25, traced/untraced identical, prior metrics reproduced; 27.0min
plus1_alpha1: 12/25, traced/untraced identical, prior metrics reproduced; 27.2min
plus1_alpha1: 13/25, traced/untraced identical, prior metrics reproduced; 27.4min
plus1_alpha1: 14/25, traced/untraced identical, prior metrics reproduced; 27.6min
plus1_alpha1: 15/25, traced/untraced identical, prior metrics reproduced; 27.8min
plus1_alpha1: 16/25, traced/untraced identical, prior metrics reproduced; 28.0min
plus1_alpha1: 17/25, traced/untraced identical, prior metrics reproduced; 28.2min
plus1_alpha1: 18/25, traced/untraced identical, prior metrics reproduced; 28.4min
plus1_alpha1: 19/25, traced/untraced identical, prior metrics reproduced; 28.6min
plus1_alpha1: 20/25, traced/untraced identical, prior metrics reproduced; 28.8min
plus1_alpha1: 21/25, traced/untraced identical, prior metrics reproduced; 29.0min
plus1_alpha1: 22/25, traced/untraced identical, prior metrics reproduced; 29.2min
plus1_alpha1: 23/25, traced/untraced identical, prior metrics reproduced; 29.4min
plus1_alpha1: 24/25, traced/untraced identical, prior metrics reproduced; 29.6min
plus1_alpha1: 25/25, traced/untraced identical, prior metrics reproduced; 29.8min
minus1_alpha1: 1/25, traced/untraced identical, prior metrics reproduced; 30.0min
minus1_alpha1: 2/25, traced/untraced identical, prior metrics reproduced; 30.2min
minus1_alpha1: 3/25, traced/untraced identical, prior metrics reproduced; 30.4min
minus1_alpha1: 4/25, traced/untraced identical, prior metrics reproduced; 30.6min
minus1_alpha1: 5/25, traced/untraced identical, prior metrics reproduced; 30.8min
minus1_alpha1: 6/25, traced/untraced identical, prior metrics reproduced; 31.0min
minus1_alpha1: 7/25, traced/untraced identical, prior metrics reproduced; 31.2min
minus1_alpha1: 8/25, traced/untraced identical, prior metrics reproduced; 31.4min
minus1_alpha1: 9/25, traced/untraced identical, prior metrics reproduced; 31.6min
minus1_alpha1: 10/25, traced/untraced identical, prior metrics reproduced; 31.8min
minus1_alpha1: 11/25, traced/untraced identical, prior metrics reproduced; 32.0min
minus1_alpha1: 12/25, traced/untraced identical, prior metrics reproduced; 32.2min
minus1_alpha1: 13/25, traced/untraced identical, prior metrics reproduced; 32.4min
minus1_alpha1: 14/25, traced/untraced identical, prior metrics reproduced; 32.6min
minus1_alpha1: 15/25, traced/untraced identical, prior metrics reproduced; 32.8min
minus1_alpha1: 16/25, traced/untraced identical, prior metrics reproduced; 33.0min
minus1_alpha1: 17/25, traced/untraced identical, prior metrics reproduced; 33.2min
minus1_alpha1: 18/25, traced/untraced identical, prior metrics reproduced; 33.4min
minus1_alpha1: 19/25, traced/untraced identical, prior metrics reproduced; 33.6min
minus1_alpha1: 20/25, traced/untraced identical, prior metrics reproduced; 33.8min
minus1_alpha1: 21/25, traced/untraced identical, prior metrics reproduced; 34.0min
minus1_alpha1: 22/25, traced/untraced identical, prior metrics reproduced; 34.2min
minus1_alpha1: 23/25, traced/untraced identical, prior metrics reproduced; 34.4min
minus1_alpha1: 24/25, traced/untraced identical, prior metrics reproduced; 34.6min
minus1_alpha1: 25/25, traced/untraced identical, prior metrics reproduced; 34.8min
Download this ZIP even if an error occurred: numerical_trace_epoch441_20261011_070941_283789.zip

/kaggle/working/numerical_trace_epoch441_20261011_070941_283789.zip

In [4]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed','Partial run: share the ZIP and error.'
assert len(manifest['completed_conditions'])==7 and manifest['completed_identity_pairs']==175
display(pd.read_csv(RUN/'results/summary.csv'))
trace=[json.loads(line) for line in (RUN/'results/trace.jsonl').read_text().splitlines()]
parameters=[dict(condition=r['condition'],scene=r['scene'],stage=r['stage'],a=r['a'],mu=r['mu'],
                 minimum_absolute_denominator=r['denominator']['min_abs'],nonpositive_denominators=r['denominator']['nonpositive'])
            for r in trace if r['event']=='parameters']
display(pd.DataFrame(parameters).groupby(['condition','stage']).agg(
    minimum_absolute_denominator=('minimum_absolute_denominator','min'),
    maximum_nonpositive_count=('nonpositive_denominators','max'),minimum_a=('a','min'),maximum_a=('a','max')))
print('Completed:175 exact traced/untraced comparisons, prior scene metrics/confusions reproduced. Download the numerical_trace_epoch441 ZIP and share its local path. A small denominator alone does not prove the failure mechanism.')

          condition  foreground_miou_all22       PSNR      SSIM        MSE
0             clean               0.787684  39.006846  0.974785   0.000131
1    plus1_alpha0.1               0.780407  38.480462  0.972647   0.000147
2   minus1_alpha0.1               0.780623  38.410596  0.972515   0.000149
3   plus1_alpha0.25               0.709982  -5.109314  0.903969  83.815243
4  minus1_alpha0.25               0.703317  -5.086849  0.899974  65.109760
5      plus1_alpha1               0.783080  38.985379  0.974661   0.000132
6     minus1_alpha1               0.782078  38.889867  0.974132   0.000134

                        minimum_absolute_denominator  \
condition        stage
clean            1                         10.853058
                 2                          0.738616
                 3                          0.313725
                 4                          0.462256
                 5                          0.411361
minus1_alpha0.1  1                          9.848619
                 2                          0.139756
                 3                          0.114221
                 4                          0.277858
                 5                          0.220863
minus1_alpha0.25 1                          9.882829
                 2                          0.000594
                 3                          0.000417
                 4                          0.004822
                 5                          0.003151
minus1_alpha1    1                         10.847350
                 2                          0.738904
                 3                          0.314052
                 4                          0.461959
                 5                          0.411000
plus1_alpha0.1   1                          9.848701
                 2                          0.149797
                 3                          0.114242
                 4                          0.277782
                 5                          0.220979
plus1_alpha0.25  1                          9.883036
                 2                          0.000464
                 3                          0.000908
                 4                          0.011621
                 5                          0.002629
plus1_alpha1     1                         10.848184
                 2                          0.738683
                 3                          0.315037
                 4                          0.461770
                 5                          0.411552

                        maximum_nonpositive_count  minimum_a  maximum_a
condition        stage
clean            1                              0   9.853058  10.482160
                 2                              0  -0.261384  -0.204884
                 3                              0  -0.686275  -0.510176
                 4                              0  -0.537744  -0.396481
                 5                              0  -0.588639  -0.534263
minus1_alpha0.1  1                              0   9.838619  10.465438
                 2                           1140  -0.266353  -0.209756
                 3                           1140  -0.695779  -0.515417
                 4                           1140  -0.532142  -0.392651
                 5                           1140  -0.589137  -0.534105
minus1_alpha0.25 1                              0   9.820329  10.445496
                 2                           1126  -0.279319  -0.222947
                 3                           3337  -0.718352  -0.541594
                 4                           1140  -0.552016  -0.393944
                 5                           2317  -0.594342  -0.524289
minus1_alpha1    1                              0   9.847350  10.476105
                 2                              0  -0.261096  -0.204731
                 3                              0  -0.685948  -0.510411
                 4                              0  -0.538041  -0.398691
                 5                              0  -0.589000  -0.534512
plus1_alpha0.1   1                              0   9.838700  10.465537
                 2                           1145  -0.266402  -0.209797
                 3                           1145  -0.695758  -0.515519
                 4                           1145  -0.532218  -0.392827
                 5                           1145  -0.589021  -0.534176
plus1_alpha0.25  1                              0   9.820536  10.445749
                 2                           1135  -0.279337  -0.222779
                 3                           3291  -0.718751  -0.543778
                 4                           1145  -0.550879  -0.392035
                 5                           2307  -0.594247  -0.526506
plus1_alpha1     1                              0   9.848184  10.477127
                 2                              0  -0.261317  -0.204510
                 3                              0  -0.684963  -0.509943
                 4                              0  -0.538230  -0.396343
                 5                              0  -0.588448  -0.534987

Completed:175 exact traced/untraced comparisons, prior scene metrics/confusions reproduced. Download the numerical_trace_epoch441 ZIP and share its local path. A small denominator alone does not prove the failure mechanism.

In [1]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch441 weights: /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth

In [2]:
FILES={'operator_control.py': '"""Frozen validation: paired nominal/matched operators under synthetic mask mixing."""\nfrom pathlib import Path\nimport argparse\nimport hashlib\nimport json\nimport time\nimport numpy as np\nimport torch\n\nALPHAS = (0.05, 0.10, 0.25, 1.0)\n\ndef sha(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\ndef tensor_sha(x):\n    return hashlib.sha256(x.detach().cpu().contiguous().numpy().tobytes()).hexdigest()\n\ndef mix_mask(mask, dx, alpha):\n    assert mask.ndim == 2 and dx in (-1, 1) and 0 <= alpha <= 1\n    shifted = torch.zeros_like(mask)\n    if dx == 1:\n        shifted[:, 1:] = mask[:, :-1]\n    else:\n        shifted[:, :-1] = mask[:, 1:]\n    return (1-alpha)*mask + alpha*shifted\n\ndef make_operator(mask, bands=28, step=2):\n    h, w = mask.shape\n    phi = mask.new_zeros((1, bands, h, w+(bands-1)*step))\n    for c in range(bands):\n        phi[0, c, :, step*c:step*c+w] = mask\n    back = torch.stack([phi[:, c, :, step*c:step*c+w] for c in range(bands)], dim=1)\n    energy = phi.square().sum(1, keepdim=True)\n    energy = torch.where(energy == 0, torch.ones_like(energy), energy)\n    return back, phi, energy\n\ndef measure(x, phi, step=2):\n    b, c, h, w = x.shape\n    y = x.new_zeros((b, h, phi.shape[-1]))\n    for k in range(c):\n        y[:, :, step*k:step*k+w] += x[:, k]*phi[:, k, :, step*k:step*k+w]\n    return y\n\ndef relative_error(a, b):\n    return float(torch.linalg.vector_norm(a-b)/torch.linalg.vector_norm(b).clamp_min(1e-12))\n\ndef main():\n    import sys\n    p = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\'):\n        p.add_argument(\'--\'+key, type=Path, required=True)\n    a = p.parse_args()\n    sys.path.insert(0, str(a.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, shift_back_mask, Metrics_Rec, Metrics_Seg, set_seed\n    from run_public252 import validate\n\n    ref = json.loads(a.reference.read_text())\n    mask_path = a.code/\'mask/mask512x512.mat\'\n    assert sha(a.checkpoint) == ref[\'checkpoint_sha256\']\n    assert sha(mask_path) == ref[\'mask_sha256\']\n    assert sha(a.code/\'public252-v1.json\') == ref[\'protocol_sha256\']\n    validate(a.data, json.loads((a.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(exist_ok=False, parents=True)\n    set_seed(3407)\n    loader = evaluation_loader(a.data, \'val\', 0, True)\n    scenes = list(map(str, loader.dataset.names))\n    assert sorted(scenes) == sorted(ref[\'scenes\']) and len(scenes) == 25\n    model = model_generator(\'CRSDUN\', 28, 23, str(a.checkpoint))\n    model.eval()\n    physical = torch.as_tensor(loadmat(mask_path)[\'mask\'], dtype=torch.float32, device=\'cuda\')\n    phi, nominal = init_mask(str(mask_path), \'SSR\', 1, 28)\n    built = make_operator(physical)\n    assert all(torch.equal(x, y) for x, y in zip(built, nominal)), \'Nominal SSR tuple differs\'\n    assert all(torch.equal(x, y) for x, y in zip(make_operator(mix_mask(physical, 1, 0)), nominal))\n    nominal_hashes = [tensor_sha(x) for x in nominal]\n    conditions = [(\'clean\', 0, 0.0)] + [(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\', dx, alpha) for alpha in ALPHAS for dx in (1, -1)]\n    manifest = dict(status=\'running\', checkpoint_epoch=441, checkpoint_sha256=sha(a.checkpoint),\n                    protocol_sha256=ref[\'protocol_sha256\'], mask_sha256=sha(mask_path),\n                    script_sha256=sha(__file__), scenes=scenes, alphas=list(ALPHAS),\n                    conditions=conditions, completed_conditions=[], torch=str(torch.__version__),\n                    gpu=torch.cuda.get_device_name(0), expected_model_forwards=425,\n                    test_evaluated=False, training=False,\n                    scope=\'25 validation scenes; frozen model; identical measurement reused for nominal and matched full SSR tuples.\',\n                    caveat=\'Linear mask mixing with a zero-filled +/-1px shift is synthetic, not calibrated hardware motion. Matched masks may still be outside the training distribution.\',\n                    metrics=\'Every-stage confusion/MSE/PSNR_ref1; SSIM_ref1 final stage only. Scene-averaged reconstruction metrics; aggregate confusion mIoU.\')\n    manifest_path = a.out/\'experiment.json\'\n    def save_manifest():\n        manifest_path.write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    summary, severity_rows = [], []\n    started = time.time()\n    try:\n      with torch.inference_mode():\n        for name, dx, alpha in conditions:\n            folder = a.out/name\n            folder.mkdir()\n            mixed = physical if name == \'clean\' else mix_mask(physical, dx, alpha)\n            matched = make_operator(mixed)\n            acquisition = matched[1]\n            assert torch.equal(matched[0], shift_back_mask(acquisition))\n            expected_energy = acquisition.square().sum(1, keepdim=True)\n            expected_energy[expected_energy == 0] = 1\n            assert torch.equal(matched[2], expected_energy)\n            paired_ops = [(\'nominal\', nominal)] if name == \'clean\' else [(\'nominal\', nominal), (\'matched\', matched)]\n            severity_rows.append(dict(condition=name, dx=dx, alpha=alpha,\n                                      mask_relative_error=relative_error(mixed, physical),\n                                      changed_fraction=float((mixed != physical).float().mean()),\n                                      mean_transmittance=float(mixed.mean())))\n            pd.DataFrame(severity_rows).to_csv(a.out/\'mask_severity.csv\', index=False)\n            seg = {mode: [Metrics_Seg(23, get_class_names()) for _ in range(5)] for mode, _ in paired_ops}\n            records = []\n            for index, sample in enumerate(loader):\n                scene = scenes[index]\n                target = sample[\'image\'].float().cuda()\n                gt_cpu = target.cpu()\n                truth = sample[\'label\'].numpy()[0]\n                y = init_meas(target, acquisition, \'Y\')\n                if index == 0:\n                    assert torch.allclose(measure(target, acquisition), y, atol=1e-6, rtol=1e-6)\n                y_nominal = init_meas(target, phi, \'Y\')\n                measurement_error = relative_error(y, y_nominal)\n                y_digest = tensor_sha(y)\n                for mode, operator in paired_ops:\n                    op_hashes = [tensor_sha(x) for x in operator]\n                    xs, logits = model(y, operator)\n                    assert len(xs) == len(logits) == 5\n                    for k, (x, logit) in enumerate(zip(xs, logits), 1):\n                        assert x.shape == target.shape and logit.shape == (1, 23, *truth.shape)\n                        assert torch.isfinite(x).all() and torch.isfinite(logit).all(), f\'Nonfinite: {name}/{mode}/{scene}/stage{k}\'\n                        x_cpu = x.float().cpu()\n                        pred = logit.argmax(1).cpu().numpy()[0]\n                        hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                        np.save(folder/f\'{mode}_{scene}_stage{k}_confusion.npy\', hist)\n                        seg[mode][k-1].add_batch(truth[None], pred[None])\n                        mse = float((x_cpu-gt_cpu).square().mean())\n                        metrics = {\'MSE\':mse, \'PSNR\':float(-10*torch.log10(torch.tensor(mse))), \'SSIM\':None}\n                        if k == 5:\n                            rec = Metrics_Rec()\n                            rec.add_batch(gt_cpu, x_cpu)\n                            metrics = rec.get_table().iloc[0].to_dict()\n                        records.append(dict(condition=name, mode=mode, scene=scene, stage=k,\n                                            dx=dx, alpha=alpha, measurement_sha256=y_digest,\n                                            measurement_relative_error=measurement_error, **metrics))\n                    assert tensor_sha(y) == y_digest, \'Measurement mutated during inference\'\n                    assert [tensor_sha(t) for t in operator] == op_hashes, \'SSR tuple mutated\'\n                    del xs, logits, x, logit, x_cpu\n                pd.DataFrame(records).to_csv(folder/\'per_scene_stage_metrics.csv\', index=False)\n                del target, gt_cpu, y, y_nominal\n                print(f\'{name}: {index+1}/25; modes={len(paired_ops)}; elapsed={(time.time()-started)/60:.1f}min\', flush=True)\n            assert [tensor_sha(t) for t in nominal] == nominal_hashes\n            for mode, _ in paired_ops:\n                for k in range(1,6):\n                    acc = seg[mode][k-1]\n                    assert np.array_equal(sum(np.load(folder/f\'{mode}_{s}_stage{k}_confusion.npy\') for s in scenes), acc.confusion_matrix)\n                    np.save(folder/f\'{mode}_stage{k}_aggregate_confusion.npy\', acc.confusion_matrix)\n                    table = acc.get_table()\n                    table.to_csv(folder/f\'{mode}_stage{k}_segmentation.csv\')\n                    items = [r for r in records if r[\'mode\'] == mode and r[\'stage\'] == k]\n                    summary.append(dict(condition=name, mode=mode, stage=k, alpha=alpha, dx=dx,\n                                        foreground_miou_all22=float(table.loc[\'total(-bg)\', \'IoU\']),\n                                        PSNR=float(np.mean([r[\'PSNR\'] for r in items])),\n                                        MSE=float(np.mean([r[\'MSE\'] for r in items])),\n                                        SSIM=float(np.mean([r[\'SSIM\'] for r in items])) if k == 5 else None))\n            pd.DataFrame(summary).to_csv(a.out/\'stage_summary.csv\', index=False)\n            if name == \'clean\':\n                final = summary[-1]\n                check = dict(miou_difference=final[\'foreground_miou_all22\']-ref[\'miou\'], psnr_difference=final[\'PSNR\']-ref[\'psnr\'])\n                check[\'passed\'] = abs(check[\'miou_difference\']) < 1e-6 and abs(check[\'psnr_difference\']) < 1e-4\n                (a.out/\'clean_equivalence.json\').write_text(json.dumps(check, indent=2))\n                assert check[\'passed\'], \'Clean check failed; stopping before stresses\'\n            manifest[\'completed_conditions\'].append(name)\n            save_manifest()\n        pairs = []\n        for name, dx, alpha in conditions[1:]:\n            n, m = [next(r for r in summary if r[\'condition\']==name and r[\'mode\']==mode and r[\'stage\']==5) for mode in (\'nominal\', \'matched\')]\n            pairs.append(dict(condition=name, dx=dx, alpha=alpha,\n                              nominal_miou_percent=100*n[\'foreground_miou_all22\'], matched_miou_percent=100*m[\'foreground_miou_all22\'],\n                              matched_minus_nominal_miou_points=100*(m[\'foreground_miou_all22\']-n[\'foreground_miou_all22\']),\n                              nominal_psnr=n[\'PSNR\'], matched_psnr=m[\'PSNR\'], matched_minus_nominal_psnr=m[\'PSNR\']-n[\'PSNR\']))\n        pd.DataFrame(pairs).to_csv(a.out/\'paired_final_summary.csv\', index=False)\n        manifest[\'status\'] = \'completed\'\n        print(pd.DataFrame(pairs).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest[\'status\'] = \'failed\'\n        manifest[\'error\'] = repr(exc)\n        raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started\n        save_manifest()\n\nif __name__ == \'__main__\':\n    main()\n', 'numerical_trace.py': '"""Observe frozen CRSDUN through hooks; require exact traced/untraced outputs."""\nimport argparse, json, sys, time\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom operator_control import make_operator, mix_mask, sha, tensor_sha\n\ndef stats(x):\n    a=x.detach().cpu().double().numpy()\n    assert np.isfinite(a).all(), \'Nonfinite tensor in trace\'\n    return dict(min=float(a.min()),max=float(a.max()),rms=float(np.sqrt(np.mean(a*a))),max_abs=float(np.abs(a).max()))\n\ndef denominator_stats(d):\n    r=stats(d); a=d.detach().cpu().double().numpy()\n    r.update(min_abs=float(np.abs(a).min()),min_abs_index=[int(i) for i in np.unravel_index(np.abs(a).argmin(),a.shape)],nonpositive=int((a<=0).sum()),elements=int(a.size))\n    for limit in (1e-6,1e-4,1e-2,.1):r[f\'abs_below_{limit:g}\']=int((np.abs(a)<limit).sum())\n    return r\n\ndef spatial_error(x, target, aligned_energy):\n    delta=x.detach().cpu().double().numpy()-target\n    sq=delta[0]**2\n    h,w=sq.shape[-2:]\n    border=np.ones((h,w),dtype=bool)\n    border[16:-16,16:-16]=False\n    regions={\'image_border16\':np.broadcast_to(border,sq.shape),\'image_interior\':np.broadcast_to(~border,sq.shape)}\n    regions.update({\'energy_zero\':aligned_energy==0,\'energy_0_to_0.1\':(aligned_energy>0)&(aligned_energy<=.1),\n                    \'energy_0.1_to_1\':(aligned_energy>.1)&(aligned_energy<=1),\n                    \'energy_1_to_4\':(aligned_energy>1)&(aligned_energy<=4),\'energy_above4\':aligned_energy>4})\n    total=float(sq.sum()); result={}\n    for name,mask in regions.items():\n        n=int(mask.sum()); s=float(sq[mask].sum())\n        result[name]=dict(voxels=n,squared_error_sum=s,mse=s/n if n else None,fraction_total_error=s/total if total else 0.)\n    return dict(mse=float(sq.mean()),total_squared_error=total,regions=result)\n\nclass Observer:\n    def __init__(self,model,operator,target,emit,measurement=None):\n        self.model=model;self.operator=operator;self.target=target.detach().cpu().double().numpy();self.emit=emit\n        self.stage=0;self.handles=[];self.original_phif=model.mul_Phif;self.original_phit=model.mul_PhiTg\n        self.measurement=measurement\n        self.had_phif=\'mul_Phif\' in model.__dict__;self.had_phit=\'mul_PhiTg\' in model.__dict__\n        _,bands,h,w=target.shape\n        raw=operator[1].square().sum(1)[0]\n        self.aligned_energy=torch.stack([raw[:,2*c:2*c+w] for c in range(bands)]).cpu().numpy()\n\n    def record(self,event,x,error=False,**extra):\n        row=dict(stage=self.stage,event=event,values=stats(x),**extra)\n        if error:row[\'reconstruction_error\']=spatial_error(x,self.target,self.aligned_energy)\n        self.emit(row)\n\n    def __enter__(self):\n        def para_hook(module,args,out):\n            self.stage+=1\n            p=out.detach().cpu().flatten().tolist()\n            assert len(p)==4\n            self.emit(dict(stage=self.stage,event=\'parameters\',a=p[0],mu=p[1],b=p[2],gamma=p[3],\n                           denominator=denominator_stats(self.operator[2]+out[:,0:1])))\n        def phif(phi,x):\n            self.record(\'x_new_before_data_consistency\',x,error=True)\n            result=self.original_phif(phi,x)\n            self.record(\'predicted_measurement\',result)\n            if self.measurement is not None:self.record(\'measurement_residual\',self.measurement.unsqueeze(1)-result)\n            return result\n        def phit(phi,g):\n            self.record(\'residual_divided_by_denominator\',g)\n            result=self.original_phit(phi,g)\n            self.record(\'data_consistency_correction\',result)\n            return result\n        self.model.mul_Phif=phif;self.model.mul_PhiTg=phit\n        for module in self.model.para_est:self.handles.append(module.register_forward_hook(para_hook))\n        for k in range(self.model.stage):\n            self.handles.append(self.model.net_stage[3*k].register_forward_pre_hook(lambda m,args:self.record(\'z_before_reconstruction_attention\',args[0],error=True)))\n            self.handles.append(self.model.net_stage[3*k].register_forward_hook(lambda m,args,out:self.record(\'after_reconstruction_attention\',out,error=True)))\n            self.handles.append(self.model.net_stage[3*k+1].register_forward_hook(lambda m,args,out:self.record(\'after_refinement\',out,error=True)))\n        return self\n\n    def __exit__(self,*exc):\n        for h in self.handles:h.remove()\n        if self.had_phif:self.model.mul_Phif=self.original_phif\n        else:del self.model.mul_Phif\n        if self.had_phit:self.model.mul_PhiTg=self.original_phit\n        else:del self.model.mul_PhiTg\n\ndef main():\n    p=argparse.ArgumentParser()\n    for name in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+name,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    from scipy.io import loadmat\n    import pandas as pd\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    conditions=[(\'clean\',0,0.)]+[(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\',dx,alpha) for alpha in (.1,.25,1.) for dx in (1,-1)]\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],mask_sha256=ref[\'mask_sha256\'],script_sha256=sha(__file__),helper_sha256=sha(Path(__file__).with_name(\'operator_control.py\')),scenes=scenes,conditions=conditions,completed_conditions=[],completed_identity_pairs=0,training=False,test_evaluated=False,expected_forwards=350,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'Matched operators only. Every traced forward paired with an uninstrumented forward; all five reconstruction/logit tensors must hash identically. Regions are image-border16 and raw detector-energy bins aligned to each spectral voxel, not calibrated hardware regions.\')\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];scene_metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha in conditions:\n            operator=make_operator(mask if not dx else mix_mask(mask,dx,alpha))\n            op_hash=[tensor_sha(t) for t in operator]\n            accumulator=Metrics_Seg(23,get_class_names());rec=Metrics_Rec()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                y=init_meas(target,operator[1],\'Y\');yh=tensor_sha(y)\n                xs,ls=model(y,operator)\n                baseline=[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n                def emit(row):\n                    f.write(json.dumps(dict(condition=name,scene=scene,**row),allow_nan=False)+\'\\n\')\n                with Observer(model,operator,target,emit,measurement=y) as observer:xs,ls=model(y,operator)\n                f.flush()\n                assert observer.stage==5\n                equal=baseline==[tensor_sha(t) for t in [*xs,*ls]]\n                checks.append(dict(condition=name,scene=scene,all_stage_tensors_bitwise_identical=equal))\n                (args.out/\'identity_checks.json\').write_text(json.dumps(checks,indent=2))\n                assert equal,\'Instrumentation altered predictions\'\n                assert tensor_sha(y)==yh and [tensor_sha(t) for t in operator]==op_hash\n                one=Metrics_Rec();one.add_batch(target.cpu(),xs[-1].cpu())\n                metric=one.get_table().iloc[0].to_dict()\n                e=expected[\'scenes\'][name][scene]\n                assert abs(metric[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(metric[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Prior scene metrics not reproduced\'\n                for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec,field,getattr(rec,field)+getattr(one,field))\n                pred=ls[-1].argmax(1).cpu().numpy()[0];accumulator.add_batch(truth[None],pred[None])\n                hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                assert __import__(\'hashlib\').sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Prior scene confusion differs\'\n                scene_metrics.append(dict(condition=name,scene=scene,**metric));pd.DataFrame(scene_metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                manifest[\'completed_identity_pairs\']+=1;save()\n                del xs,ls,target,y\n                print(f\'{name}: {index+1}/25, traced/untraced identical, prior metrics reproduced; {(time.time()-started)/60:.1f}min\',flush=True)\n            table=accumulator.get_table();row=dict(condition=name,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec.get_table().iloc[0].to_dict())\n            e=expected[\'summary\'][name]\n            assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n            summaries.append(row);pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            table.to_csv(args.out/f\'{name}_segmentation.csv\');np.save(args.out/f\'{name}_confusion.npy\',accumulator.confusion_matrix)\n            manifest[\'completed_conditions\'].append(name);save()\n        manifest[\'status\']=\'completed\'\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'denominator_guard.py': '"""One fixed pre-division denominator intervention on a source-pinned forward."""\nimport inspect, textwrap, types\nimport torch\nfrom numerical_trace import denominator_stats\n\nFACTOR = 0.1\n\ndef safe_denominator(d, energy):\n    return torch.maximum(d, FACTOR*energy)\n\nclass Guard:\n    def __init__(self, model, emit, enabled=True):\n        self.model=model;self.emit=emit;self.enabled=enabled;self.stage=0;self.total_activated=0\n        self.had_forward=\'forward\' in model.__dict__;self.original=model.forward\n        assert not hasattr(model,\'_guard_denominator\')\n        source=textwrap.dedent(inspect.getsource(self.original.__func__))\n        old=\'torch.div(y - A_x_phitheta, PhiPhiT + a)\'\n        assert source.count(old)==1, \'Unexpected forward source; do not patch\'\n        source=source.replace(old,\'torch.div(y - A_x_phitheta, self._guard_denominator(PhiPhiT + a, PhiPhiT))\')\n        namespace=dict(self.original.__func__.__globals__)\n        exec(compile(source,\'<source-pinned-denominator-guard>\',\'exec\'),namespace)\n        self.patched=types.MethodType(namespace[\'forward\'],model)\n\n    def __enter__(self):\n        def apply(d,energy):\n            self.stage+=1\n            used=safe_denominator(d,energy) if self.enabled else d\n            count=int((used!=d).sum());self.total_activated+=count\n            self.emit(dict(stage=self.stage,event=\'denominator_guard\',enabled=self.enabled,factor=FACTOR,\n                           activated=count,elements=d.numel(),original=denominator_stats(d),used=denominator_stats(used)))\n            return used\n        self.model._guard_denominator=apply;self.model.forward=self.patched\n        return self\n\n    def __exit__(self,*exc):\n        del self.model._guard_denominator\n        if self.had_forward:self.model.forward=self.original\n        else:del self.model.forward\n', 'guard_experiment.py': '"""Frozen paired evaluation of one prespecified denominator safeguard."""\nimport argparse,hashlib,json,sys,time\nfrom pathlib import Path\nfrom contextlib import nullcontext\nimport numpy as np\nimport torch\nfrom operator_control import make_operator,mix_mask,sha,tensor_sha\nfrom numerical_trace import Observer\nfrom denominator_guard import Guard,FACTOR\n\ndef main():\n    p=argparse.ArgumentParser()\n    for key in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+key,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    assert sha(args.code/\'models/CRSDUN.py\')==\'57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543\'\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    weight_hashes={k:tensor_sha(v) for k,v in model.state_dict().items()}\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    # Finish all intended inactive controls before fractional-mask interventions.\n    conditions=[(\'clean\',0,0.)]+[(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\',dx,alpha) for alpha in (1.,.1,.25) for dx in (1,-1)]\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],mask_sha256=ref[\'mask_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],factor=FACTOR,formula=\'d_safe=max(E+a,0.1*E); E is existing guarded squared-mask energy\',scenes=scenes,conditions=conditions,completed_conditions=[],completed_pairs=0,expected_forwards=350,training=False,test_evaluated=False,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'One prespecified frozen inference intervention; matched operators; full-frame metrics; no output clipping or border exclusion.\',script_hashes={n:sha(Path(__file__).with_name(n)) for n in (\'guard_experiment.py\',\'denominator_guard.py\',\'numerical_trace.py\',\'operator_control.py\')})\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha in conditions:\n            op=make_operator(mask if not dx else mix_mask(mask,dx,alpha));op_hash=[tensor_sha(t) for t in op]\n            seg={mode:Metrics_Seg(23,get_class_names()) for mode in (\'control\',\'guarded\')}\n            rec={mode:Metrics_Rec() for mode in seg}\n            folder=args.out/name;folder.mkdir()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                y=init_meas(target,op[1],\'Y\');yh=tensor_sha(y);baseline_hashes=None\n                for mode in (\'control\',\'guarded\'):\n                    def emit(row):f.write(json.dumps(dict(condition=name,scene=scene,mode=mode,**row),allow_nan=False)+\'\\n\')\n                    ctx=Guard(model,emit) if mode==\'guarded\' else nullcontext()\n                    with ctx as guard:\n                        with Observer(model,op,target,emit,measurement=y) as observer:xs,ls=model(y,op)\n                    f.flush();assert observer.stage==5\n                    assert all(torch.isfinite(t).all() for t in [*xs,*ls]),\'Nonfinite model output\'\n                    output_hashes=[tensor_sha(t) for t in [*xs,*ls]]\n                    if mode==\'control\':baseline_hashes=output_hashes\n                    else:\n                        assert guard.stage==5\n                        identical=baseline_hashes==output_hashes\n                        row=dict(condition=name,scene=scene,activated=guard.total_activated,all_stage_outputs_identical=identical,expected_inactive=alpha in (0.,1.))\n                        checks.append(row);(args.out/\'pair_checks.json\').write_text(json.dumps(checks,indent=2))\n                        if alpha in (0.,1.):assert guard.total_activated==0 and identical,\'Clean/binary control changed; stop\'\n                        if guard.total_activated==0:assert identical,\'Inactive guard changed outputs\'\n                    assert tensor_sha(y)==yh and [tensor_sha(t) for t in op]==op_hash\n                    assert not hasattr(model,\'_guard_denominator\') and \'forward\' not in model.__dict__\n                    one=Metrics_Rec();one.add_batch(target.cpu(),xs[-1].cpu());values=one.get_table().iloc[0].to_dict()\n                    pred=ls[-1].argmax(1).cpu().numpy()[0]\n                    hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                    if mode==\'control\':\n                        e=expected[\'scenes\'][name][scene]\n                        assert abs(values[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(values[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Control reconstruction differs from prior run\'\n                        assert hashlib.sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Control segmentation differs from prior run\'\n                    np.save(folder/f\'{mode}_{scene}_confusion.npy\',hist)\n                    seg[mode].add_batch(truth[None],pred[None])\n                    for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec[mode],field,getattr(rec[mode],field)+getattr(one,field))\n                    metrics.append(dict(condition=name,scene=scene,mode=mode,measurement_sha256=yh,**values))\n                    pd.DataFrame(metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                    del xs,ls\n                manifest[\'completed_pairs\']+=1;save();del target,y\n                print(f\'{name}: {index+1}/25 paired; {(time.time()-started)/60:.1f}min\',flush=True)\n            for mode in seg:\n                table=seg[mode].get_table()\n                summed=sum(np.load(folder/f\'{mode}_{s}_confusion.npy\') for s in scenes)\n                assert np.array_equal(summed,seg[mode].confusion_matrix)\n                np.save(folder/f\'{mode}_aggregate_confusion.npy\',summed);table.to_csv(folder/f\'{mode}_segmentation.csv\')\n                row=dict(condition=name,mode=mode,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec[mode].get_table().iloc[0].to_dict())\n                if mode==\'control\':\n                    e=expected[\'summary\'][name]\n                    assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n                summaries.append(row)\n            pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            manifest[\'completed_conditions\'].append(name);save()\n        pairs=[]\n        for name,_,_ in conditions:\n            a,b=[next(r for r in summaries if r[\'condition\']==name and r[\'mode\']==mode) for mode in (\'control\',\'guarded\')]\n            pairs.append(dict(condition=name,control_miou_percent=100*a[\'foreground_miou_all22\'],guarded_miou_percent=100*b[\'foreground_miou_all22\'],miou_change_points=100*(b[\'foreground_miou_all22\']-a[\'foreground_miou_all22\']),control_psnr=a[\'PSNR\'],guarded_psnr=b[\'PSNR\'],psnr_change=b[\'PSNR\']-a[\'PSNR\'],control_mse=a[\'MSE\'],guarded_mse=b[\'MSE\']))\n        pd.DataFrame(pairs).to_csv(args.out/\'paired_summary.csv\',index=False)\n        assert weight_hashes=={k:tensor_sha(v) for k,v in model.state_dict().items()},\'Model state mutated\'\n        manifest.update(status=\'completed\',model_state_unchanged=True)\n        print(pd.DataFrame(pairs).to_string(index=False),flush=True)\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'verify_denominator_guard.py': "import argparse,sys\nimport torch\nfrom denominator_guard import Guard,safe_denominator\nfrom numerical_trace import Observer\nfrom operator_control import make_operator,mix_mask,tensor_sha\np=argparse.ArgumentParser();p.add_argument('--code',required=True);args=p.parse_args();sys.path.insert(0,args.code)\nfrom models.CRSDUN import CRSDUN\nfrom utils import init_meas,set_seed\nassert torch.cuda.is_available();torch.set_num_threads(1);set_seed(3407)\nenergy=torch.tensor([1.,.25,.0625,2.]);d=torch.tensor([.4,0.,-.1,.2]);saved=d.clone()\nassert torch.equal(safe_denominator(d,energy),torch.tensor([.4,.025,.00625,.2])) and torch.equal(d,saved)\nassert torch.isfinite(torch.ones_like(d)/safe_denominator(d,energy)).all()\nmodel=CRSDUN(stage=5,bands=28,n_class=23).cuda().eval()\nmask=(torch.rand(64,64,device='cuda')>.5).float();target=torch.rand(1,28,64,64,device='cuda')\n# Force a known negative offset to exercise both inactive binary and active fractional paths.\ndef forced_a(module,args,out):\n    value=out.clone();value[:,0:1]=-.6;return value\nhandles=[m.register_forward_hook(forced_a) for m in model.para_est]\nwith torch.inference_mode():\n for alpha in (0.,.25,1.):\n    op=make_operator(mix_mask(mask,1,alpha));y=init_meas(target,op[1],'Y')\n    baseline=model(y,op);original=[tensor_sha(t) for xs in baseline for t in xs];del baseline\n    with Guard(model,lambda r:None,enabled=False):\n        output=model(y,op)\n    assert original==[tensor_sha(t) for xs in output for t in xs];del output\n    records=[]\n    with Guard(model,records.append) as guard:\n        with Observer(model,op,target,lambda r:None,measurement=y):output=model(y,op)\n    hashes=[tensor_sha(t) for xs in output for t in xs]\n    assert guard.stage==5 and len(records)==5\n    if alpha in (0.,1.):assert guard.total_activated==0 and original==hashes\n    else:\n        assert guard.total_activated>0 and original!=hashes\n        assert all(r['used']['min']>0 for r in records)\n    assert all(torch.isfinite(t).all() for xs in output for t in xs)\n    assert 'forward' not in model.__dict__ and not hasattr(model,'_guard_denominator')\n    del output\n try:\n    with Guard(model,lambda r:None):raise RuntimeError('cleanup')\n except RuntimeError:pass\n assert 'forward' not in model.__dict__ and not hasattr(model,'_guard_denominator')\nfor h in handles:h.remove()\nprint('PASS: pre-division zero/negative denominator handling; actual five-stage forward disabled-patch identity; binary inactive identity; fractional activation; Observer compatibility; exception cleanup. Synthetic64x64 test, not trained full-frame efficacy.')\n"}
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}
EXPECTED={'source_archive': 'operator_control_epoch441_20261010_183309_608911.zip', 'source_archive_sha256': 'b2f9bf0118804cfdfecc7e72f5aee9a3f36b975631bcb1c4ad1618cec7cb7743', 'summary': {'clean': {'foreground_miou_all22': 0.7876837070566084, 'PSNR': 39.00684616088867, 'MSE': 0.00013123682205332443, 'SSIM': 0.9747850704193115}, 'plus1_alpha0.1': {'foreground_miou_all22': 0.7804071879322305, 'PSNR': 38.480462341308595, 'MSE': 0.00014687360497191547, 'SSIM': 0.9726465129852295}, 'minus1_alpha0.1': {'foreground_miou_all22': 0.7806234925438672, 'PSNR': 38.41059600830078, 'MSE': 0.0001489559863694012, 'SSIM': 0.97251469373703}, 'plus1_alpha0.25': {'foreground_miou_all22': 0.7099818617488114, 'PSNR': -5.109313906431198, 'MSE': 83.81524314329027, 'SSIM': 0.9039690732955933}, 'minus1_alpha0.25': {'foreground_miou_all22': 0.7033165229414478, 'PSNR': -5.086848521232605, 'MSE': 65.10976030603051, 'SSIM': 0.8999737000465393}, 'plus1_alpha1': {'foreground_miou_all22': 0.7830800141043546, 'PSNR': 38.98537872314453, 'MSE': 0.00013183161034248768, 'SSIM': 0.974661271572113}, 'minus1_alpha1': {'foreground_miou_all22': 0.7820777620674779, 'PSNR': 38.88986663818359, 'MSE': 0.0001340003072982654, 'SSIM': 0.9741322302818298}}, 'scenes': {'clean': {'2021-11-03_046': {'PSNR': 39.89459228515625, 'MSE': 0.00010245677549391985, 'confusion_sha256': '9a717b84a51b72b2fba1c9060dfc8ad32d2508a3c8f0eb98494f1809757909ec'}, '2021-11-03_047': {'PSNR': 38.86285400390625, 'MSE': 0.00012993150448892266, 'confusion_sha256': '919915901d083e6ed85b8577721c7392ee968a7d23b41b7d6df5407226b34d16'}, '2021-11-03_057': {'PSNR': 37.99570083618164, 'MSE': 0.00015864624583628029, 'confusion_sha256': '711f63aea60da1ad3e5dd583c1ad6c185b62eb8ead7661faab625fefc9a93000'}, '2021-11-03_085': {'PSNR': 40.45058059692383, 'MSE': 9.01449893717654e-05, 'confusion_sha256': 'f26712d2687056e1f8812c93a119dc945e55a6c1c3a465d8c75b9e4e89c4cfdd'}, '2021-11-03_090': {'PSNR': 40.33523178100586, 'MSE': 9.257135388907045e-05, 'confusion_sha256': 'ce95968be99e39136bb3a54ba923ea41501fa0803c75a0bae08d8bd21e2de7ec'}, '2021-11-03_110': {'PSNR': 39.576499938964844, 'MSE': 0.00011024268314940855, 'confusion_sha256': '925537ac21544cbbed2767f15ad85fa1c7a52691dc70e7712568c6260f9b2c13'}, '2021-11-04_010': {'PSNR': 37.13905334472656, 'MSE': 0.00019323898595757782, 'confusion_sha256': 'c9099b0d0a570152439bb9708c16c6f9882d2b9d23632b94de45b23e5e2e145b'}, '2021-11-04_017': {'PSNR': 38.54598617553711, 'MSE': 0.00013976586342323571, 'confusion_sha256': 'dcdfe2f5a2ef36a30df2960ae7f34537645c5ef3070a89e09ec06fe7708f669c'}, '2021-11-04_024': {'PSNR': 38.70061111450195, 'MSE': 0.00013487727846950293, 'confusion_sha256': 'e3082e8a5aee905c21b646233bda5e8f37889d2ec740925842e5389426415656'}, '2021-11-04_042': {'PSNR': 40.50850296020508, 'MSE': 8.895069913705811e-05, 'confusion_sha256': '69745abc94ea2ee55b0aac789679b0353d08f391c931258e232dd465690d7f22'}, '2021-11-04_047': {'PSNR': 40.22039794921875, 'MSE': 9.505175694357604e-05, 'confusion_sha256': 'b6c73d3bec5395b68de7c48614e082e1c36f6330ee46719b20947da3f4c25bbc'}, '2021-11-04_049': {'PSNR': 40.83124542236328, 'MSE': 8.25801253085956e-05, 'confusion_sha256': 'b63f6d857eeb2b1870346a4ecb5c3594f5dea62fefe6262ece4344a65a2791c2'}, '2021-11-04_055': {'PSNR': 40.75486373901367, 'MSE': 8.404533582506701e-05, 'confusion_sha256': '995f147be920d56d9ba740f6ec33fd436afc5e1a8eaad452b5dcaa746edd9834'}, '2021-11-04_061': {'PSNR': 40.685176849365234, 'MSE': 8.540479029761627e-05, 'confusion_sha256': '59adfbe1bb34d1890af5029d8bd8281620d18396e9b876be0e4f6e4f6f5d2596'}, '2021-11-04_093': {'PSNR': 39.08949661254883, 'MSE': 0.0001233247312484309, 'confusion_sha256': '6366ce691015ac82a2669684a1c4d681bff89544f92fab6972d817ea7e7d7b2c'}, '2021-11-04_098': {'PSNR': 39.36787414550781, 'MSE': 0.00011566774628590792, 'confusion_sha256': '6d227838a684f6f312e50afa89da8c8623ad19564835045da03dc93a2bdabdea'}, '2021-11-05_010': {'PSNR': 37.41633987426758, 'MSE': 0.00018128668307326734, 'confusion_sha256': '13b3bae21986dd485dbe9125a904ee039a7d076c7e1aa9a2c19c4a8317eeee6f'}, '2021-11-05_024': {'PSNR': 39.7016716003418, 'MSE': 0.00010711060895118862, 'confusion_sha256': 'df5555f991ede7f38186ff4cbfe4dca368ad0ff0bfba94e2cb5e5ae992659d4f'}, '2021-11-05_035': {'PSNR': 38.786293029785156, 'MSE': 0.00013224223221186548, 'confusion_sha256': '7642e43435e57e4c293c5497b3ed47fdf0830fab3a34010f983d393ff6f79224'}, '2021-11-05_041': {'PSNR': 38.4978141784668, 'MSE': 0.00014132479554973543, 'confusion_sha256': 'cee79d0f10b1a368417af8ec32939e69ccfc5a1d5d4b70c9727535b9fe968e3b'}, '2021-11-05_046': {'PSNR': 36.10015869140625, 'MSE': 0.0002454617933835834, 'confusion_sha256': '99ceb435926731d4d7593346568ef795f28ff326dcb5a775f1f9fe1af0388e31'}, '2021-11-10_014': {'PSNR': 38.25468063354492, 'MSE': 0.00014946235751267523, 'confusion_sha256': '700d7bfb7ee77774c754fa984c10b556125d20f7eb11ce8f8fea4055a35c9fc2'}, '2021-11-10_024': {'PSNR': 37.73176193237305, 'MSE': 0.00016858673188835382, 'confusion_sha256': '32c9dfe5fd11c769fdd29d729a4cc2575d048096185fe33c83c76f035d77b383'}, '2021-11-10_029': {'PSNR': 38.25230407714844, 'MSE': 0.00014954424113966525, 'confusion_sha256': '55b866708c3de1af700fe8c596c4acee41e9c60fc89886eb282486f138541098'}, '2021-11-10_050': {'PSNR': 37.47146224975586, 'MSE': 0.00017900024249684066, 'confusion_sha256': 'ffff7a303633916099bc9025d29370aab79abad5f287f2f452f346467e5b0f9a'}}, 'plus1_alpha0.1': {'2021-11-03_046': {'PSNR': 39.53356170654297, 'MSE': 0.00011133799853269011, 'confusion_sha256': '74fc44022774fddc2d3a840197e046c73c5050626e157f802892e08a8ae3970a'}, '2021-11-03_047': {'PSNR': 38.42921829223633, 'MSE': 0.00014357476902659982, 'confusion_sha256': '2ce3d59f70510d4f27629c65ea1221c6b4fff5549368e6846e141f6bba354231'}, '2021-11-03_057': {'PSNR': 37.398101806640625, 'MSE': 0.0001820495817810297, 'confusion_sha256': 'babb40ea19ec33fbca3de7480d72b180d3866d0be78a8a68b66ba7a1eccf7165'}, '2021-11-03_085': {'PSNR': 39.71846389770508, 'MSE': 0.00010669727635104209, 'confusion_sha256': '54ef114eaba644b482e72defb86a4d5b911e24996811d862f6bb0a092aafd750'}, '2021-11-03_090': {'PSNR': 39.6631965637207, 'MSE': 0.0001080637812265195, 'confusion_sha256': 'd7b07e83629bb6d48a85433bfeeb9d99b21eb999ddf69b08cb96ac2b25a6fcc2'}, '2021-11-03_110': {'PSNR': 38.660606384277344, 'MSE': 0.00013612551265396178, 'confusion_sha256': '4d2d561e7a719337bf24cd74ecfd5cd6e8eed94b1a8a9fb3e71f4380fc87e583'}, '2021-11-04_010': {'PSNR': 36.83472442626953, 'MSE': 0.00020726557704620063, 'confusion_sha256': '543788170690efed986c186154b356d3f8b37ae5ae3d5c40f69a693b0ffb7667'}, '2021-11-04_017': {'PSNR': 38.19437026977539, 'MSE': 0.00015155240544117987, 'confusion_sha256': '4ecdb1d9c131545b6465cb2f6655cf57e58f4102b1d0f390fe04c259d8668765'}, '2021-11-04_024': {'PSNR': 38.337066650390625, 'MSE': 0.00014665376511402428, 'confusion_sha256': 'b2f7017b0135d8af9983fde8ac73650082fa5e34c6885c915d4e28f5c85f185a'}, '2021-11-04_042': {'PSNR': 39.93755340576172, 'MSE': 0.00010144825500901788, 'confusion_sha256': 'f76ec9713fff65f4d1aef2658e4a7bc4f98f77b342008b199ed4304d316954ed'}, '2021-11-04_047': {'PSNR': 39.63911056518555, 'MSE': 0.00010866473894566298, 'confusion_sha256': '4a0f2d6389539eb636b013b6816fbf617c6f7b4f045018981882104bc8345341'}, '2021-11-04_049': {'PSNR': 40.25779724121094, 'MSE': 9.423670417163521e-05, 'confusion_sha256': '0b49214fcd84d7922c192e60f21be8517bf86b8cff7aa9714ed8a51bcf89b108'}, '2021-11-04_055': {'PSNR': 39.86824417114258, 'MSE': 0.000103080237749964, 'confusion_sha256': '8cc5e7d7f0945238df53f2d9672225549251d60810a28e4e4aa565963f02ce73'}, '2021-11-04_061': {'PSNR': 39.8060417175293, 'MSE': 0.00010456730524310842, 'confusion_sha256': '60fe3ce021d34106b146016292b483da442d708c45db3bc2d42951d0feb031d0'}, '2021-11-04_093': {'PSNR': 38.563316345214844, 'MSE': 0.00013920932542532682, 'confusion_sha256': '555ac685515ef30d01a51135613607f7ec4c60ac53c28292e3d7f173ed36d617'}, '2021-11-04_098': {'PSNR': 38.90040588378906, 'MSE': 0.00012881297152489424, 'confusion_sha256': 'a6beda01a90aae13038df16fb931b4fdec8bf94d10e4027a9148bcb3756d070f'}, '2021-11-05_010': {'PSNR': 37.00151824951172, 'MSE': 0.0001994563644984737, 'confusion_sha256': 'bf0749f32bd5d80958f98e352fd7fd1131008676df80a3f46eb4f28b1ac25f72'}, '2021-11-05_024': {'PSNR': 38.845340728759766, 'MSE': 0.00013045647938270122, 'confusion_sha256': '1bd25ebf983cbd00fffc9cf8659e15393a561a6eace3e1b533ef944762731df3'}, '2021-11-05_035': {'PSNR': 38.225521087646484, 'MSE': 0.00015046920452732593, 'confusion_sha256': '23f7b9d374d780201f3077757527583beb1225381eb926082b57f3a4169d8efe'}, '2021-11-05_041': {'PSNR': 37.94324493408203, 'MSE': 0.00016057398170232773, 'confusion_sha256': 'e6375941a1fdea5e3321dee2238122ea334eea1c51beb4d9fd86ad68e6154b5e'}, '2021-11-05_046': {'PSNR': 35.822505950927734, 'MSE': 0.0002616672427393496, 'confusion_sha256': '37d8a2e9cdc0a84b7438fcb02912645900f27c501d1f824a3adede7dc38383f5'}, '2021-11-10_014': {'PSNR': 37.92229080200195, 'MSE': 0.00016135061741806567, 'confusion_sha256': 'e6510dad970ce41a35f9d809d214e3e9300e620010fdcc88dfcd73eac85d8ada'}, '2021-11-10_024': {'PSNR': 37.33868408203125, 'MSE': 0.00018455726967658848, 'confusion_sha256': 'd945f704aef8878db17ecf69be736bbdb13d93f4e5499f7c29a31bc42e81959b'}, '2021-11-10_029': {'PSNR': 37.95048522949219, 'MSE': 0.00016030656115617603, 'confusion_sha256': '76065de3abf7f309e3985213ad4785d89f595d58597cf79bde1b6e9a0f95f7cd'}, '2021-11-10_050': {'PSNR': 37.22018814086914, 'MSE': 0.0001896621979540214, 'confusion_sha256': 'b94d127de50692d41ba0666718afc1ac429a68f510931393d09d17e7b83f1af0'}}, 'minus1_alpha0.1': {'2021-11-03_046': {'PSNR': 39.504478454589844, 'MSE': 0.00011208618525415659, 'confusion_sha256': '12a79283c292e64e439aa3a508a48a4b79aad92aa66a919f06e4c1b505cf203b'}, '2021-11-03_047': {'PSNR': 38.409427642822266, 'MSE': 0.0001442304637748748, 'confusion_sha256': 'c872b12f217d64b7e7f97031757ce9cbb01fc394d5b8a44346040b749778ee85'}, '2021-11-03_057': {'PSNR': 37.30839157104492, 'MSE': 0.0001858491450548172, 'confusion_sha256': '9d164eeba19d0d1921c21ea102649cea84fec6c0bbb830e89f2a02c4764236d4'}, '2021-11-03_085': {'PSNR': 39.658958435058594, 'MSE': 0.00010816926078405231, 'confusion_sha256': 'ee617f071d4418738a87a45e9688a0b6295f84d04d8f2a71b282c2d92e1c51ba'}, '2021-11-03_090': {'PSNR': 39.579044342041016, 'MSE': 0.00011017820361303166, 'confusion_sha256': '55c32cb03f28c23eb3af7597cce6f559fa618bab9a6d73ad087a769c3bf43cb9'}, '2021-11-03_110': {'PSNR': 38.48360824584961, 'MSE': 0.0001417878520442173, 'confusion_sha256': '0fa7a52f5c25647b61412ad526ac22d40bdfcaf859cceae4d8c996b86dd7e6b0'}, '2021-11-04_010': {'PSNR': 36.857460021972656, 'MSE': 0.0002061835111817345, 'confusion_sha256': 'cca771642a02bf9b162821778d29d04adaf664b9d64f6a193bc751aa33510cdf'}, '2021-11-04_017': {'PSNR': 38.16506576538086, 'MSE': 0.00015257846098393202, 'confusion_sha256': '05610aafa0917bb5762013d6c88e68aae5c7dafad95e01914a0a9a93d18beb7e'}, '2021-11-04_024': {'PSNR': 38.302467346191406, 'MSE': 0.00014782676589675248, 'confusion_sha256': 'b753920aeb07ebbd5721e3c21c8d3a0632a64f1d55361ff128a0ba1f77534a5f'}, '2021-11-04_042': {'PSNR': 39.79904556274414, 'MSE': 0.00010473588190507144, 'confusion_sha256': 'a186add554b815e1981560085145a33acd0bee8132718d2e1a2d0cac0e087350'}, '2021-11-04_047': {'PSNR': 39.448638916015625, 'MSE': 0.0001135365673690103, 'confusion_sha256': '5a688bdb8d0a318edc5322a44e144542c9896dfa3ad749e2fe5f192905e823b0'}, '2021-11-04_049': {'PSNR': 40.15362548828125, 'MSE': 9.652441804064438e-05, 'confusion_sha256': '663e1e7398596f06fb12aca03ca1e9fa39e6be70197f32e3461b9226d70d61bd'}, '2021-11-04_055': {'PSNR': 39.721153259277344, 'MSE': 0.00010663115972420201, 'confusion_sha256': 'edc0f1d02e855da0cd6722af59b80cd0eb42561bdf9fc804e6d7925a503e05ed'}, '2021-11-04_061': {'PSNR': 39.71446990966797, 'MSE': 0.00010679545812308788, 'confusion_sha256': 'a79245940931ee2953d9ff06c8cb5b6aaa5cbff1306d56f52583dbf278bffebd'}, '2021-11-04_093': {'PSNR': 38.49284362792969, 'MSE': 0.00014148661284707487, 'confusion_sha256': '0c4750df4a807cfb5408514c2744551bcb7a11a738d4cb1d0464c2bbd72f4f6d'}, '2021-11-04_098': {'PSNR': 38.83191680908203, 'MSE': 0.00013086042599752545, 'confusion_sha256': '9bf1f5b28d2a656a05c37588b52102d54c674dad8090b12393ab112529d5f368'}, '2021-11-05_010': {'PSNR': 36.97058868408203, 'MSE': 0.00020088198652956635, 'confusion_sha256': '5fab299a74c84535834f00737c7838b63d790c970ba865e4806118f43b03e693'}, '2021-11-05_024': {'PSNR': 38.72041320800781, 'MSE': 0.00013426375517155975, 'confusion_sha256': '3bf862732ff99c2cff8860479505212d4d2048fdf1417d77dd56d009a1d8f3b7'}, '2021-11-05_035': {'PSNR': 38.15167999267578, 'MSE': 0.00015304956468753517, 'confusion_sha256': '01b3900646776fbbff267c32f504b380974ef87daed8bdae6ffd34b28f12e9e0'}, '2021-11-05_041': {'PSNR': 37.860992431640625, 'MSE': 0.00016364408656954765, 'confusion_sha256': '96e41c724be4aa0407ae092a8ce1023cd1ae87ec9ed39a1c0d06f6eb51b45c53'}, '2021-11-05_046': {'PSNR': 35.8121337890625, 'MSE': 0.0002622929750941694, 'confusion_sha256': '919c5c55e5be26195e513aac79cc0392d50425e19b7f9cc2fcd246d53ac943ba'}, '2021-11-10_014': {'PSNR': 37.8758544921875, 'MSE': 0.00016308513295371085, 'confusion_sha256': '02efc1b17df6a4dda23af082bc7a2d54e3a2ac41d7688621adfc1e65d694212c'}, '2021-11-10_024': {'PSNR': 37.33454513549805, 'MSE': 0.0001847333915065974, 'confusion_sha256': 'f60bb3abf0e51f4ce4f6036e3f39adb008075ccc280cb0c505fdbccf1cba6efb'}, '2021-11-10_029': {'PSNR': 37.91758346557617, 'MSE': 0.00016152569151017815, 'confusion_sha256': 'f23b5a6d0bf26bfb75b13384937693c9581804d1f7e1f207316ce642dd443ec7'}, '2021-11-10_050': {'PSNR': 37.190513610839844, 'MSE': 0.00019096270261798054, 'confusion_sha256': '8cd3ec56bd8bebe50e08eb9d21e2fac8ac749c1b13c97c2734bac2f0aca06c8d'}}, 'plus1_alpha0.25': {'2021-11-03_046': {'PSNR': 8.277036666870117, 'MSE': 0.1486949622631073, 'confusion_sha256': '65acef90a8030dca16eae33a2ccc7e1404ce7ba7d6d09a5d7c14b12df9e1c8a4'}, '2021-11-03_047': {'PSNR': -12.5802640914917, 'MSE': 18.114505767822266, 'confusion_sha256': '3d04f7a26a1bf259fa3734c9ed2e57bd34a59167ba32aad00c00962c96afe3e4'}, '2021-11-03_057': {'PSNR': -0.5277264714241028, 'MSE': 1.1292046308517456, 'confusion_sha256': '8f85aadc0b630d6e17553e566c7159263192edec6c86a565930f6c6be3f14948'}, '2021-11-03_085': {'PSNR': -8.534158706665039, 'MSE': 7.135361194610596, 'confusion_sha256': '365e74e2af6c468d1df8653f8cfef603cfa571228fba120bd2f2dff2bd39306b'}, '2021-11-03_090': {'PSNR': -7.22999382019043, 'MSE': 5.284445285797119, 'confusion_sha256': 'dfedf56ceb73a1e2ccb7ba8ad3637b73c72d3dab40fa108d5c26cb9533ce937b'}, '2021-11-03_110': {'PSNR': 12.149971008300781, 'MSE': 0.06095408275723457, 'confusion_sha256': 'fd6fc38362dea4862579ba7cfc6ef61bf796a00a10d1ea7c83101f034bc8c422'}, '2021-11-04_010': {'PSNR': -6.972059726715088, 'MSE': 4.979732036590576, 'confusion_sha256': '768bcb93e017a0890aaa9f8ba136b8b56b2bf5cab1372df8a21dd4d2e5ffb600'}, '2021-11-04_017': {'PSNR': -3.0808913707733154, 'MSE': 2.0327742099761963, 'confusion_sha256': 'fa0a264501321e5a175dd0bdfa6a656fa4cc1f7db5dfd7a1f37f7247958f09ca'}, '2021-11-04_024': {'PSNR': -2.196054220199585, 'MSE': 1.658079743385315, 'confusion_sha256': '984d6008696749b3462f01087b3140f5f18c83b873cc6c1c138ff3ae114bddeb'}, '2021-11-04_042': {'PSNR': -5.517134666442871, 'MSE': 3.5621604919433594, 'confusion_sha256': '03fdaf6ef0aa9233d17059cc32a28a9f827b6ef8fa9ab3186dd4c900264eecfb'}, '2021-11-04_047': {'PSNR': -10.676491737365723, 'MSE': 11.685553550720215, 'confusion_sha256': '198ee43b581c33226515a8ffd38a676870ba5bd1231349faafaccb7c6fe8be15'}, '2021-11-04_049': {'PSNR': -12.803421974182129, 'MSE': 19.069631576538086, 'confusion_sha256': '484d9c9d11a6e8d567548d3917ff7e38ad81a304bb87362b17831100e7c36144'}, '2021-11-04_055': {'PSNR': 3.5782041549682617, 'MSE': 0.43871206045150757, 'confusion_sha256': '3135c3b6cac4213f18ce2c168352d7f69c7c6c6c764ad468ee73338fb349e2d9'}, '2021-11-04_061': {'PSNR': -0.21835699677467346, 'MSE': 1.0515639781951904, 'confusion_sha256': '3d719225209b182810dfaac5a05398524d9018da717b153b995cbeb949091c43'}, '2021-11-04_093': {'PSNR': -0.7805860042572021, 'MSE': 1.1969020366668701, 'confusion_sha256': '59e39c80d583e00071cae25bb81f32b9d138219848fe8b5cb1a48476efb1c84e'}, '2021-11-04_098': {'PSNR': -7.466648578643799, 'MSE': 5.580394744873047, 'confusion_sha256': 'f8b05fc5a9adf39caa8436f23ef4b5f010abd26962fc154910eb066676b43029'}, '2021-11-05_010': {'PSNR': -4.319344997406006, 'MSE': 2.7035505771636963, 'confusion_sha256': '7a01f278b319d941c4fe548b746a9f99ec2b4e348ab953cd1e65e4051b509129'}, '2021-11-05_024': {'PSNR': 2.2303483486175537, 'MSE': 0.5983635783195496, 'confusion_sha256': 'afeb3f00632d036adaef01c1901e14f30098b8c48990343c5a29efb02e98456c'}, '2021-11-05_035': {'PSNR': 8.731414794921875, 'MSE': 0.13392402231693268, 'confusion_sha256': 'c7704dbb19830007798127ae5295984e6149965290f37e931c9d5a13aacc3058'}, '2021-11-05_041': {'PSNR': -1.4292829036712646, 'MSE': 1.3897231817245483, 'confusion_sha256': 'b8ccff5a7dfa4918a7a9812f93743d402f5a16905de6ba3163781479638303b6'}, '2021-11-05_046': {'PSNR': 9.312551498413086, 'MSE': 0.1171506717801094, 'confusion_sha256': '58ecfc75d2e41925458a71b520839ddb8570fbbb4e2a9446ccdc2409e9fee2eb'}, '2021-11-10_014': {'PSNR': -30.780231475830078, 'MSE': 1196.8046875, 'confusion_sha256': '6c5c3a2302df06978061318210a83cbc2eedfab24f384375af4b4c3a941e6303'}, '2021-11-10_024': {'PSNR': -27.06857681274414, 'MSE': 509.1642150878906, 'confusion_sha256': '68d64fc62f66eb3d725c098fa442f6bce07277635bb191f187e3951d7754232c'}, '2021-11-10_029': {'PSNR': -24.743825912475586, 'MSE': 298.1142883300781, 'confusion_sha256': '6a73b0063fad1dce5373cc13aec6127d6a84cde5abb791b283f843d1e2245264'}, '2021-11-10_050': {'PSNR': -5.0873236656188965, 'MSE': 3.2265052795410156, 'confusion_sha256': 'e4eb77276872c0426737fb89dd4bad0364589bc81b1c173c92c4e321f0cbe707'}}, 'minus1_alpha0.25': {'2021-11-03_046': {'PSNR': 7.803365707397461, 'MSE': 0.1658301204442978, 'confusion_sha256': 'f62fe7edcb36dce8e9569e42182b90e68c70a2eca54970d1df07a942b49bed50'}, '2021-11-03_047': {'PSNR': -14.702699661254883, 'MSE': 29.530447006225586, 'confusion_sha256': 'c6524665f3f4b49a2a63e4281689d77fc8172bb18f8f4c735516c38d653bbdf6'}, '2021-11-03_057': {'PSNR': -1.7272698879241943, 'MSE': 1.4884251356124878, 'confusion_sha256': '77f9329a014c58556af219a02debd7506b851e4136fe38f55b7160dcb0f03d3e'}, '2021-11-03_085': {'PSNR': -0.886996865272522, 'MSE': 1.2265907526016235, 'confusion_sha256': '9f4e08df0829bd23df769ca95dc781c5ba0221e7fddd7e97e792c0ee51b112a4'}, '2021-11-03_090': {'PSNR': -5.25463342666626, 'MSE': 3.3532299995422363, 'confusion_sha256': 'f829e11b9b26f2a568acfaec4dee7c85ded2eeded0403b05b7e60e78af5ef261'}, '2021-11-03_110': {'PSNR': 12.107354164123535, 'MSE': 0.061555165797472, 'confusion_sha256': '3bd0c6c14d19529ca464c9e9d018f370cf70edf3c5f576eb4813d89012b4ce80'}, '2021-11-04_010': {'PSNR': -11.525019645690918, 'MSE': 14.206987380981445, 'confusion_sha256': '5cc1e0457065f19fcd3784acba2edb3575dfed4ffbc4a237ef93f187d8d26bc4'}, '2021-11-04_017': {'PSNR': -16.70313835144043, 'MSE': 46.80733871459961, 'confusion_sha256': '6d5dff939641d5931183cf0ce0c5f01069808846deb9a36ce6938362a3a93cf5'}, '2021-11-04_024': {'PSNR': -3.812268018722534, 'MSE': 2.405618906021118, 'confusion_sha256': 'a8b78527c556e8551ddc88835976e688b1681a71f297b592801ae75ba8b110d7'}, '2021-11-04_042': {'PSNR': -5.1902174949646, 'MSE': 3.303861379623413, 'confusion_sha256': 'e1f5da754712f846b0b1d0f480986e1b55ff7955d543138551699f3905f2ae59'}, '2021-11-04_047': {'PSNR': -11.66427993774414, 'MSE': 14.669931411743164, 'confusion_sha256': '2c0acff73872e99170d9cf5b5a951a69d68762f0e9be522f04368a117ebc2211'}, '2021-11-04_049': {'PSNR': -15.672592163085938, 'MSE': 36.919795989990234, 'confusion_sha256': 'ed86060e37b1b4bdf0e0ba903ec0b396ec5fb7bed333a85f3bbcbf2fab5bbaa4'}, '2021-11-04_055': {'PSNR': 4.529160499572754, 'MSE': 0.3524389863014221, 'confusion_sha256': 'd1fdd99f09ffee5d8f85314f696f08b92b2775d670ee34eafa4c2c4e1fdf299d'}, '2021-11-04_061': {'PSNR': 0.5494163036346436, 'MSE': 0.8811672925949097, 'confusion_sha256': 'fcc297032a61e9dd0c93c84398cb0766b87a44b59950b22f1c53a20d8391c822'}, '2021-11-04_093': {'PSNR': 1.5230262279510498, 'MSE': 0.7042021751403809, 'confusion_sha256': '201ff6250ed202e11af64a04a933a4abefa26d3b7eec5e94bf1cf504f6c4e516'}, '2021-11-04_098': {'PSNR': -1.3938651084899902, 'MSE': 1.378435730934143, 'confusion_sha256': '7b6429241b13abd1a0db072fce898cc6e61eb3600af38093283fd1eb498fbcc2'}, '2021-11-05_010': {'PSNR': -4.2936272621154785, 'MSE': 2.6875884532928467, 'confusion_sha256': 'ccc2e21594932c2d84ae7f85e4f2b841b1ff2b8d18d9bb17489807d5449321d9'}, '2021-11-05_024': {'PSNR': 0.510915994644165, 'MSE': 0.8890135884284973, 'confusion_sha256': 'd0d86a855ead3fd164bb2a84237c955d3af545887db404b9276c02a499162aec'}, '2021-11-05_035': {'PSNR': 7.533391952514648, 'MSE': 0.17646588385105133, 'confusion_sha256': '82d345d93b7ba6970f2bcaa3c9288b7a519da0da6d4576f57efd17f5b46e32e6'}, '2021-11-05_041': {'PSNR': 1.2950642108917236, 'MSE': 0.7421532273292542, 'confusion_sha256': '3737be4f4b370c6ae02ab9dbb192ff2d250d5dbc48fa8f3cd4357dc27c25b860'}, '2021-11-05_046': {'PSNR': 8.538073539733887, 'MSE': 0.14002083241939545, 'confusion_sha256': 'da173b491f28cf66388db7c4ab2663d91cdc1283d4717da4d1f46018b9d239f9'}, '2021-11-10_014': {'PSNR': -30.209529876708984, 'MSE': 1049.4293212890625, 'confusion_sha256': 'bb6090713bece762a9c273606dd63e2afd2ed4d3e968206392c4fa9ceb59b44d'}, '2021-11-10_024': {'PSNR': -25.037992477416992, 'MSE': 319.0064392089844, 'confusion_sha256': 'dfea492ea7005f6b688487d4e6e39ee5073c03a686d3af80532535462d32b927'}, '2021-11-10_029': {'PSNR': -19.77103042602539, 'MSE': 94.86436462402344, 'confusion_sha256': '2840d205bb1e52c8a8d4568bac06a0b5fe2589b441421e8b84cafc2e50ab77f3'}, '2021-11-10_050': {'PSNR': -3.7158210277557373, 'MSE': 2.3527843952178955, 'confusion_sha256': '8dda4c1f03bd47e7ab1f633b9e405aac429b961b1286768604ef795c73beaa53'}}, 'plus1_alpha1': {'2021-11-03_046': {'PSNR': 39.93577194213867, 'MSE': 0.00010148985165869817, 'confusion_sha256': '14d73e1d988c3f12445ad7605030a4aae6d00bedfbcd0a2590e73ce6a51a9f86'}, '2021-11-03_047': {'PSNR': 38.74766540527344, 'MSE': 0.0001334237604169175, 'confusion_sha256': 'e33773f13e39c415c4a16615b47c307f9cb5a3f3a57527dbec2852c3949532c0'}, '2021-11-03_057': {'PSNR': 38.011871337890625, 'MSE': 0.00015805664588697255, 'confusion_sha256': 'f8d10f8c036a225b811d4c6163a0dacf823f541ced6875a3a73ee641e4de98d6'}, '2021-11-03_085': {'PSNR': 40.45233917236328, 'MSE': 9.010852227220312e-05, 'confusion_sha256': '29b10d98e58cd2f21f568b68b97469f820580e93f40ddf739b3d4dd72c5029f9'}, '2021-11-03_090': {'PSNR': 40.327449798583984, 'MSE': 9.273734031012282e-05, 'confusion_sha256': 'a30335633bde701a59bf9ab0ea2730a99f6ecf268b4ce149f5d12a23eaadb1a5'}, '2021-11-03_110': {'PSNR': 39.5364875793457, 'MSE': 0.00011126306344522163, 'confusion_sha256': '1ef25a4011bd2eb1aa8106f826fa5744da1540ee530ca2398a90e6bfaf120cc2'}, '2021-11-04_010': {'PSNR': 37.031429290771484, 'MSE': 0.0001980874949367717, 'confusion_sha256': '83ef051c01af9cc064d65b6bdb1a860ca41bfceac6c53e4ffa3d1f3899a43541'}, '2021-11-04_017': {'PSNR': 38.305030822753906, 'MSE': 0.00014773955626878887, 'confusion_sha256': '30fd19e55413ee336efde550a6d18744310dbac363ed0df36852443f0f7466fc'}, '2021-11-04_024': {'PSNR': 38.92214584350586, 'MSE': 0.00012816974776796997, 'confusion_sha256': '5117e1755188e0081172a6cabc50fe17f22ee83b1756e117a61eb18ab583899f'}, '2021-11-04_042': {'PSNR': 40.36432647705078, 'MSE': 9.195320308208466e-05, 'confusion_sha256': 'e811ffe794b72420cd8b4029771d035b29533fa1af2f3059be976693c1a27121'}, '2021-11-04_047': {'PSNR': 40.204830169677734, 'MSE': 9.5393079391215e-05, 'confusion_sha256': 'd9ce18ab865496e7b49ff3f44fc2baf2094b6ed47a63a9a7ba7becfa1da48aa7'}, '2021-11-04_049': {'PSNR': 40.76326370239258, 'MSE': 8.388292917516083e-05, 'confusion_sha256': '0739e78fdce2fd493a0ba10a70b17775e0f9e31c6c12f242f23f044dc02d053c'}, '2021-11-04_055': {'PSNR': 40.6777458190918, 'MSE': 8.555103704566136e-05, 'confusion_sha256': 'd114df89306eedf47535155128aa09f186d1af10d0311737d6c3df2b95f67762'}, '2021-11-04_061': {'PSNR': 40.669185638427734, 'MSE': 8.571981743443757e-05, 'confusion_sha256': '24a36c34d291e115447b406535a1dc828672e1b33910da5649dd8be417982bf6'}, '2021-11-04_093': {'PSNR': 39.108089447021484, 'MSE': 0.00012279787915758789, 'confusion_sha256': '7ffb0b314167f9997093033d1e058cc6b4eb1d7460017a7dd48134cbf9054f4c'}, '2021-11-04_098': {'PSNR': 39.419681549072266, 'MSE': 0.00011429621372371912, 'confusion_sha256': '7e4d06de321d1a215030015fb0901ec49f4ea36c1ab0e742961185696052e8d6'}, '2021-11-05_010': {'PSNR': 37.400718688964844, 'MSE': 0.00018193975847680122, 'confusion_sha256': '664274c7764a4ee9745f1e9512d3516202c6110b3b988d991867f67dcc3f9672'}, '2021-11-05_024': {'PSNR': 39.66768264770508, 'MSE': 0.0001079522626241669, 'confusion_sha256': '6d9b4a0bb4c0201e00b2e992f1c591ad95546b736c2cc170fd0e04f71b494331'}, '2021-11-05_035': {'PSNR': 38.80119323730469, 'MSE': 0.0001317894784733653, 'confusion_sha256': '7344af1615b33e4b2fc3dfe6aeb65a8356552888c70e5cb92ff02fbc59d35656'}, '2021-11-05_041': {'PSNR': 38.47829055786133, 'MSE': 0.00014196158736012876, 'confusion_sha256': '84e1cbc4065644afd3badaf58755d846956b9d3bc062694b9c274a35bc29b580'}, '2021-11-05_046': {'PSNR': 36.15117263793945, 'MSE': 0.0002425952407065779, 'confusion_sha256': 'f556d6048653f677f798897c43d20b1cf1ac1bf710d767c3889f12d3973c7a16'}, '2021-11-10_014': {'PSNR': 38.18336486816406, 'MSE': 0.00015193699800875038, 'confusion_sha256': '03c6ca79b8a384401a6f5295141949e807a064f09bbccbbbc75e960b5bb054ee'}, '2021-11-10_024': {'PSNR': 37.86553192138672, 'MSE': 0.00016347326163668185, 'confusion_sha256': 'fd4ff1567e9ea0800587d9a93417f44d2d3db92e93575c08e8ead678e01f902b'}, '2021-11-10_029': {'PSNR': 38.2700080871582, 'MSE': 0.00014893573825247586, 'confusion_sha256': '07c8908d21e62c73ba4b96e0ad6f2511bb20bc2b81df342f3278f649fdbd3911'}, '2021-11-10_050': {'PSNR': 37.33919143676758, 'MSE': 0.0001845357910497114, 'confusion_sha256': 'd60d3fcdb457c10e4e7f2a974e2ad732eb532cd422348f233bf2fe206b135c75'}}, 'minus1_alpha1': {'2021-11-03_046': {'PSNR': 39.77946090698242, 'MSE': 0.00010520912474021316, 'confusion_sha256': '001937a1365ad6cc97f4063edfc953d10e71ebb98931acdc77ea4a265c83e081'}, '2021-11-03_047': {'PSNR': 38.6917724609375, 'MSE': 0.00013515203318092972, 'confusion_sha256': '91462bb1d1c1b5cb20cde612023104ebef082c555a870907b728124682abf04f'}, '2021-11-03_057': {'PSNR': 38.02188491821289, 'MSE': 0.0001576926588313654, 'confusion_sha256': '03e698b21cdae41b5991210b5541e51fb417155991d248b5253f23154b751779'}, '2021-11-03_085': {'PSNR': 40.30281448364258, 'MSE': 9.326493454864249e-05, 'confusion_sha256': '14ac21f8bde27adfe23129111e8b9a0a9dbefb667fb1f8ec88996959689b3430'}, '2021-11-03_090': {'PSNR': 40.20442581176758, 'MSE': 9.540192695567384e-05, 'confusion_sha256': '4ab0686987aa4fe61cd6fe086733b30b50ffad78476190896b0b7e685be6794a'}, '2021-11-03_110': {'PSNR': 39.50486755371094, 'MSE': 0.0001120761371566914, 'confusion_sha256': 'd983700844c54998edbad82d50ff881a02f3fe4e649a801c94806f95288e3590'}, '2021-11-04_010': {'PSNR': 37.249549865722656, 'MSE': 0.00018838440882973373, 'confusion_sha256': '72125cc4e0945192590c0b6a6adf0ac0fa9d261db7638b41841182067083f089'}, '2021-11-04_017': {'PSNR': 38.4840087890625, 'MSE': 0.00014177474076859653, 'confusion_sha256': 'f54f0fbcd698b2e327094a26203cf96cc526816f804931dc45300714855664a1'}, '2021-11-04_024': {'PSNR': 38.65106201171875, 'MSE': 0.00013642494741361588, 'confusion_sha256': 'aaab1344b0b32c6579c30d2c1b9a2ab506e7070e64c095b01d067be589944cd2'}, '2021-11-04_042': {'PSNR': 40.1712532043457, 'MSE': 9.613343718228862e-05, 'confusion_sha256': 'ecf46b820c15b8fdbe7bc256638880c4da92226f62121ba3031b882c1cdbde0a'}, '2021-11-04_047': {'PSNR': 39.96493148803711, 'MSE': 0.00010081072832690552, 'confusion_sha256': '8c669512fa42a4202dc9a97013d6bbf57164d644455f868312baa26fb1700ffb'}, '2021-11-04_049': {'PSNR': 40.5753059387207, 'MSE': 8.759294723859057e-05, 'confusion_sha256': '2feaf15b7b4406276f7ea7f49196cc1351f5ce9903db5e60b1d61fc6289e6ce5'}, '2021-11-04_055': {'PSNR': 40.35194778442383, 'MSE': 9.221574146067724e-05, 'confusion_sha256': '8bb6db7eda58f13c124fae1ef3111040bf81bb235a3a2746542bd6a04ba19c08'}, '2021-11-04_061': {'PSNR': 40.27669143676758, 'MSE': 9.382760617882013e-05, 'confusion_sha256': '04a6dbca8d073ee68a2b42cfaf7fde08bde3585280818899137956d8a52ad4bf'}, '2021-11-04_093': {'PSNR': 39.054813385009766, 'MSE': 0.00012431357754394412, 'confusion_sha256': 'bc72c1334fe11b01342d256c1caeccbc0fa9acf89bdeab81108c33acb00ef82e'}, '2021-11-04_098': {'PSNR': 39.23973083496094, 'MSE': 0.000119131596875377, 'confusion_sha256': '971f9c205a4edd1e94411287906ea9dedc16bff36849a5036def85eee51a85d7'}, '2021-11-05_010': {'PSNR': 37.39585494995117, 'MSE': 0.00018214374722447246, 'confusion_sha256': 'ce54101d30622f3dae17ff86bf51e114a9c8e97ccdd966cb96e88e15f6832673'}, '2021-11-05_024': {'PSNR': 39.5966682434082, 'MSE': 0.00010973198368446901, 'confusion_sha256': 'b6ad1cf047c843b02bb6ec8a4fc7471e361ae6e60af873d187f7232aeaeec4fc'}, '2021-11-05_035': {'PSNR': 38.71174240112305, 'MSE': 0.00013453203428070992, 'confusion_sha256': 'fe0a70b0902d6cfe063291a591a75d5d512a1b3e5debec7640de6390e82d4bd9'}, '2021-11-05_041': {'PSNR': 38.43107223510742, 'MSE': 0.00014351338904816657, 'confusion_sha256': '8f64b2f835cd99af39a2c8ff765294f524561c63d7b1d7bff04cedfc0a8d40f5'}, '2021-11-05_046': {'PSNR': 36.058353424072266, 'MSE': 0.00024783617118373513, 'confusion_sha256': '19479ea65b8906b463fa586dd42da26cc470b62b521d767df06e822796e5f689'}, '2021-11-10_014': {'PSNR': 38.06553649902344, 'MSE': 0.00015611555136274546, 'confusion_sha256': '184a55cb0afb8576ba2905207ba66ac33681b36d14b5cef518e23359fe94faf7'}, '2021-11-10_024': {'PSNR': 37.631168365478516, 'MSE': 0.00017253738769795746, 'confusion_sha256': '25267115d55c6313a161747f9f83e562b8f251bfec0f28409bbf9720f3d28a71'}, '2021-11-10_029': {'PSNR': 38.259586334228516, 'MSE': 0.00014929348253645003, 'confusion_sha256': '8435416170e7932b77ebd421892a69ef0d8e9aeee4e601e17f00475e4b46a569'}, '2021-11-10_050': {'PSNR': 37.57216262817383, 'MSE': 0.00017489738820586354, 'confusion_sha256': '8b3b7203ff04ebcd9a8a43adfd841cd6fc614ba8b696ecd21361a0148e2f06a8'}}}}

RUN=WORK/('denominator_guard_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
for filename,source in FILES.items():(RUN/filename).write_text(source)
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'expected.json').write_text(json.dumps(EXPECTED,indent=2))
(RUN/'source_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in ['models/CRSDUN.py','dataset.py','utils.py','public252-v1.json']},indent=2))
with (RUN/'local_checks.log').open('w') as log:
    result=subprocess.run([sys.executable,str(RUN/'verify_denominator_guard.py'),'--code',str(CODE)],cwd=RUN,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    log.write(result.stdout);print(result.stdout)
    result.check_returncode()
print('Output folder:',RUN)

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
PASS: pre-division zero/negative denominator handling; actual five-stage forward disabled-patch identity; binary inactive identity; fractional activation; Observer compatibility; exception cleanup. Synthetic64x64 test, not trained full-frame efficacy.

Output folder: /kaggle/working/denominator_guard_epoch441_20261011_083129_702085

In [3]:
from IPython.display import display,FileLink
try:
    with (RUN/'console.log').open('w') as log:
        command=[sys.executable,'-u',str(RUN/'guard_experiment.py'),
                 '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
                 '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json'),'--expected',str(RUN/'expected.json')]
        proc=subprocess.Popen(command,cwd=CODE,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)
        try:
            for line in proc.stdout:
                print(line,end='',flush=True)
                log.write(line);log.flush()
            code=proc.wait()
            if code: raise subprocess.CalledProcessError(code,command)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try: proc.wait(timeout=10)
                except subprocess.TimeoutExpired: proc.kill();proc.wait()
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
clean: 1/25 paired; 0.4min
clean: 2/25 paired; 0.7min
clean: 3/25 paired; 1.0min
clean: 4/25 paired; 1.3min
clean: 5/25 paired; 1.6min
clean: 6/25 paired; 1.9min
clean: 7/25 paired; 2.2min
clean: 8/25 paired; 2.4min
clean: 9/25 paired; 2.7min
clean: 10/25 paired; 3.0min
clean: 11/25 paired; 3.3min
clean: 12/25 paired; 3.6min
clean: 13/25 paired; 3.9min
clean: 14/25 paired; 4.2min
clean: 15/25 paired; 4.5min
clean: 16/25 paired; 4.8min
clean: 17/25 paired; 5.1min
clean: 18/25 paired; 5.4min
clean: 19/25 paired; 5.7min
clean: 20/25 paired; 6.0min
clean: 21/25 paired; 6.3min
clean: 22/25 paired; 6.6min
clean: 23/25 paired; 6.9min
clean: 24/25 paired; 7.1min
clean: 25/25 paired; 7.4min
plus1_alpha1: 1/25 paired; 7.7min
plus1_alpha1: 2/25 paired; 8.0min
plus1_alpha1: 3/25 paired; 8.3min
plus1_alpha1: 4/25 paired; 8.6min
plus1_alpha1: 5/25 paired; 8.9min
plus1_alpha1: 6/25 paired; 9.2min
plus1_alpha1: 7/25 paired; 9.5min
plus1_alpha1: 8/25 paired; 9.8min
plus1_alpha1: 9/25 paired; 10.1min
plus1_alpha1: 10/25 paired; 10.3min
plus1_alpha1: 11/25 paired; 10.6min
plus1_alpha1: 12/25 paired; 10.9min
plus1_alpha1: 13/25 paired; 11.2min
plus1_alpha1: 14/25 paired; 11.5min
plus1_alpha1: 15/25 paired; 11.8min
plus1_alpha1: 16/25 paired; 12.1min
plus1_alpha1: 17/25 paired; 12.4min
plus1_alpha1: 18/25 paired; 12.7min
plus1_alpha1: 19/25 paired; 13.0min
plus1_alpha1: 20/25 paired; 13.3min
plus1_alpha1: 21/25 paired; 13.5min
plus1_alpha1: 22/25 paired; 13.8min
plus1_alpha1: 23/25 paired; 14.1min
plus1_alpha1: 24/25 paired; 14.4min
plus1_alpha1: 25/25 paired; 14.7min
minus1_alpha1: 1/25 paired; 15.0min
minus1_alpha1: 2/25 paired; 15.3min
minus1_alpha1: 3/25 paired; 15.6min
minus1_alpha1: 4/25 paired; 15.9min
minus1_alpha1: 5/25 paired; 16.2min
minus1_alpha1: 6/25 paired; 16.5min
minus1_alpha1: 7/25 paired; 16.9min
minus1_alpha1: 8/25 paired; 17.2min
minus1_alpha1: 9/25 paired; 17.5min
minus1_alpha1: 10/25 paired; 17.8min
minus1_alpha1: 11/25 paired; 18.1min
minus1_alpha1: 12/25 paired; 18.4min
minus1_alpha1: 13/25 paired; 18.7min
minus1_alpha1: 14/25 paired; 19.0min
minus1_alpha1: 15/25 paired; 19.3min
minus1_alpha1: 16/25 paired; 19.6min
minus1_alpha1: 17/25 paired; 19.8min
minus1_alpha1: 18/25 paired; 20.1min
minus1_alpha1: 19/25 paired; 20.4min
minus1_alpha1: 20/25 paired; 20.7min
minus1_alpha1: 21/25 paired; 21.0min
minus1_alpha1: 22/25 paired; 21.3min
minus1_alpha1: 23/25 paired; 21.6min
minus1_alpha1: 24/25 paired; 21.9min
minus1_alpha1: 25/25 paired; 22.2min
plus1_alpha0.1: 1/25 paired; 22.5min
plus1_alpha0.1: 2/25 paired; 22.8min
plus1_alpha0.1: 3/25 paired; 23.1min
plus1_alpha0.1: 4/25 paired; 23.4min
plus1_alpha0.1: 5/25 paired; 23.7min
plus1_alpha0.1: 6/25 paired; 24.0min
plus1_alpha0.1: 7/25 paired; 24.3min
plus1_alpha0.1: 8/25 paired; 24.6min
plus1_alpha0.1: 9/25 paired; 24.9min
plus1_alpha0.1: 10/25 paired; 25.2min
plus1_alpha0.1: 11/25 paired; 25.5min
plus1_alpha0.1: 12/25 paired; 25.8min
plus1_alpha0.1: 13/25 paired; 26.1min
plus1_alpha0.1: 14/25 paired; 26.4min
plus1_alpha0.1: 15/25 paired; 26.7min
plus1_alpha0.1: 16/25 paired; 27.0min
plus1_alpha0.1: 17/25 paired; 27.3min
plus1_alpha0.1: 18/25 paired; 27.6min
plus1_alpha0.1: 19/25 paired; 27.9min
plus1_alpha0.1: 20/25 paired; 28.2min
plus1_alpha0.1: 21/25 paired; 28.5min
plus1_alpha0.1: 22/25 paired; 28.8min
plus1_alpha0.1: 23/25 paired; 29.1min
plus1_alpha0.1: 24/25 paired; 29.4min
plus1_alpha0.1: 25/25 paired; 29.7min
minus1_alpha0.1: 1/25 paired; 30.0min
minus1_alpha0.1: 2/25 paired; 30.3min
minus1_alpha0.1: 3/25 paired; 30.6min
minus1_alpha0.1: 4/25 paired; 30.9min
minus1_alpha0.1: 5/25 paired; 31.2min
minus1_alpha0.1: 6/25 paired; 31.6min
minus1_alpha0.1: 7/25 paired; 31.9min
minus1_alpha0.1: 8/25 paired; 32.2min
minus1_alpha0.1: 9/25 paired; 32.5min
minus1_alpha0.1: 10/25 paired; 32.8min
minus1_alpha0.1: 11/25 paired; 33.2min
minus1_alpha0.1: 12/25 paired; 33.5min
minus1_alpha0.1: 13/25 paired; 33.8min
minus1_alpha0.1: 14/25 paired; 34.1min
minus1_alpha0.1: 15/25 paired; 34.4min
minus1_alpha0.1: 16/25 paired; 34.7min
minus1_alpha0.1: 17/25 paired; 35.0min
minus1_alpha0.1: 18/25 paired; 35.4min
minus1_alpha0.1: 19/25 paired; 35.7min
minus1_alpha0.1: 20/25 paired; 36.0min
minus1_alpha0.1: 21/25 paired; 36.3min
minus1_alpha0.1: 22/25 paired; 36.6min
minus1_alpha0.1: 23/25 paired; 36.9min
minus1_alpha0.1: 24/25 paired; 37.2min
minus1_alpha0.1: 25/25 paired; 37.5min
plus1_alpha0.25: 1/25 paired; 37.9min
plus1_alpha0.25: 2/25 paired; 38.2min
plus1_alpha0.25: 3/25 paired; 38.5min
plus1_alpha0.25: 4/25 paired; 38.8min
plus1_alpha0.25: 5/25 paired; 39.1min
plus1_alpha0.25: 6/25 paired; 39.5min
plus1_alpha0.25: 7/25 paired; 39.8min
plus1_alpha0.25: 8/25 paired; 40.1min
plus1_alpha0.25: 9/25 paired; 40.4min
plus1_alpha0.25: 10/25 paired; 40.7min
plus1_alpha0.25: 11/25 paired; 41.0min
plus1_alpha0.25: 12/25 paired; 41.3min
plus1_alpha0.25: 13/25 paired; 41.6min
plus1_alpha0.25: 14/25 paired; 41.9min
plus1_alpha0.25: 15/25 paired; 42.3min
plus1_alpha0.25: 16/25 paired; 42.6min
plus1_alpha0.25: 17/25 paired; 42.9min
plus1_alpha0.25: 18/25 paired; 43.2min
plus1_alpha0.25: 19/25 paired; 43.5min
plus1_alpha0.25: 20/25 paired; 43.8min
plus1_alpha0.25: 21/25 paired; 44.1min
plus1_alpha0.25: 22/25 paired; 44.5min
plus1_alpha0.25: 23/25 paired; 44.8min
plus1_alpha0.25: 24/25 paired; 45.1min
plus1_alpha0.25: 25/25 paired; 45.4min
minus1_alpha0.25: 1/25 paired; 45.7min
minus1_alpha0.25: 2/25 paired; 46.0min
minus1_alpha0.25: 3/25 paired; 46.3min
minus1_alpha0.25: 4/25 paired; 46.6min
minus1_alpha0.25: 5/25 paired; 46.9min
minus1_alpha0.25: 6/25 paired; 47.2min
minus1_alpha0.25: 7/25 paired; 47.5min
minus1_alpha0.25: 8/25 paired; 47.9min
minus1_alpha0.25: 9/25 paired; 48.2min
minus1_alpha0.25: 10/25 paired; 48.5min
minus1_alpha0.25: 11/25 paired; 48.8min
minus1_alpha0.25: 12/25 paired; 49.1min
minus1_alpha0.25: 13/25 paired; 49.4min
minus1_alpha0.25: 14/25 paired; 49.7min
minus1_alpha0.25: 15/25 paired; 50.0min
minus1_alpha0.25: 16/25 paired; 50.3min
minus1_alpha0.25: 17/25 paired; 50.7min
minus1_alpha0.25: 18/25 paired; 51.0min
minus1_alpha0.25: 19/25 paired; 51.3min
minus1_alpha0.25: 20/25 paired; 51.6min
minus1_alpha0.25: 21/25 paired; 52.0min
minus1_alpha0.25: 22/25 paired; 52.3min
minus1_alpha0.25: 23/25 paired; 52.6min
minus1_alpha0.25: 24/25 paired; 52.9min
minus1_alpha0.25: 25/25 paired; 53.2min
       condition  control_miou_percent  guarded_miou_percent  miou_change_points  control_psnr  guarded_psnr  psnr_change  control_mse  guarded_mse
           clean             78.768371             78.768371            0.000000     39.006846     39.006846     0.000000     0.000131     0.000131
    plus1_alpha1             78.308001             78.308001            0.000000     38.985379     38.985379     0.000000     0.000132     0.000132
   minus1_alpha1             78.207776             78.207776            0.000000     38.889867     38.889867     0.000000     0.000134     0.000134
  plus1_alpha0.1             78.040719             69.527508           -8.513211     38.480462     -1.924671   -40.405134     0.000147     1.579394
 minus1_alpha0.1             78.062349             71.347911           -6.714438     38.410596      1.677967   -36.732629     0.000149     0.690728
 plus1_alpha0.25             70.998186             68.843496           -2.154690     -5.109314     -2.196167     2.913147    83.815243     1.678608
minus1_alpha0.25             70.331652             69.892286           -0.439367     -5.086849     -0.808145     4.278703    65.109760     1.222929
Download this ZIP even if an error occurred: denominator_guard_epoch441_20261011_083129_702085.zip

/kaggle/working/denominator_guard_epoch441_20261011_083129_702085.zip

In [4]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed','Partial run: share the ZIP and error.'
assert manifest['completed_pairs']==175 and manifest['model_state_unchanged']
checks=pd.read_json(RUN/'results/pair_checks.json')
assert len(checks)==175
inactive=checks[checks['expected_inactive']]
assert len(inactive)==75 and inactive['all_stage_outputs_identical'].all() and (inactive['activated']==0).all()
display(pd.read_csv(RUN/'results/paired_summary.csv'))
display(checks.groupby('condition').agg(total_activated=('activated','sum'),identical_pairs=('all_stage_outputs_identical','sum')))
print('Completed. Download denominator_guard_epoch441 ZIP and share its local path. This is a frozen inference diagnostic, not a trained method or a journal-level claim.')

,condition,control_miou_percent,guarded_miou_percent,miou_change_points,control_psnr,guarded_psnr,psnr_change,control_mse,guarded_mse
0,clean,78.768371,78.768371,0.000000,39.006846,39.006846,0.000000,0.000131,0.000131
1,plus1_alpha1,78.308001,78.308001,0.000000,38.985379,38.985379,0.000000,0.000132,0.000132
2,minus1_alpha1,78.207776,78.207776,0.000000,38.889867,38.889867,0.000000,0.000134,0.000134
3,plus1_alpha0.1,78.040719,69.527508,-8.513211,38.480462,-1.924671,-40.405134,0.000147,1.579394
4,minus1_alpha0.1,78.062349,71.347911,-6.714438,38.410596,1.677967,-36.732629,0.000149,0.690728
5,plus1_alpha0.25,70.998186,68.843496,-2.154690,-5.109314,-2.196167,2.913147,83.815243,1.678608
6,minus1_alpha0.25,70.331652,69.892286,-0.439367,-5.086849,-0.808145,4.278703,65.109760,1.222929

                  total_activated  identical_pairs
condition
clean                           0               25
minus1_alpha0.1            114000                0
minus1_alpha0.25           201547                0
minus1_alpha1                   0               25
plus1_alpha0.1             114500                0
plus1_alpha0.25            200772                0
plus1_alpha1                    0               25

Completed. Download denominator_guard_epoch441 ZIP and share its local path. This is a frozen inference diagnostic, not a trained method or a journal-level claim.

In [5]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch441 weights: /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth

In [6]:
FILES={'operator_control.py': '"""Frozen validation: paired nominal/matched operators under synthetic mask mixing."""\nfrom pathlib import Path\nimport argparse\nimport hashlib\nimport json\nimport time\nimport numpy as np\nimport torch\n\nALPHAS = (0.05, 0.10, 0.25, 1.0)\n\ndef sha(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\ndef tensor_sha(x):\n    return hashlib.sha256(x.detach().cpu().contiguous().numpy().tobytes()).hexdigest()\n\ndef mix_mask(mask, dx, alpha):\n    assert mask.ndim == 2 and dx in (-1, 1) and 0 <= alpha <= 1\n    shifted = torch.zeros_like(mask)\n    if dx == 1:\n        shifted[:, 1:] = mask[:, :-1]\n    else:\n        shifted[:, :-1] = mask[:, 1:]\n    return (1-alpha)*mask + alpha*shifted\n\ndef make_operator(mask, bands=28, step=2):\n    h, w = mask.shape\n    phi = mask.new_zeros((1, bands, h, w+(bands-1)*step))\n    for c in range(bands):\n        phi[0, c, :, step*c:step*c+w] = mask\n    back = torch.stack([phi[:, c, :, step*c:step*c+w] for c in range(bands)], dim=1)\n    energy = phi.square().sum(1, keepdim=True)\n    energy = torch.where(energy == 0, torch.ones_like(energy), energy)\n    return back, phi, energy\n\ndef measure(x, phi, step=2):\n    b, c, h, w = x.shape\n    y = x.new_zeros((b, h, phi.shape[-1]))\n    for k in range(c):\n        y[:, :, step*k:step*k+w] += x[:, k]*phi[:, k, :, step*k:step*k+w]\n    return y\n\ndef relative_error(a, b):\n    return float(torch.linalg.vector_norm(a-b)/torch.linalg.vector_norm(b).clamp_min(1e-12))\n\ndef main():\n    import sys\n    p = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\'):\n        p.add_argument(\'--\'+key, type=Path, required=True)\n    a = p.parse_args()\n    sys.path.insert(0, str(a.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, shift_back_mask, Metrics_Rec, Metrics_Seg, set_seed\n    from run_public252 import validate\n\n    ref = json.loads(a.reference.read_text())\n    mask_path = a.code/\'mask/mask512x512.mat\'\n    assert sha(a.checkpoint) == ref[\'checkpoint_sha256\']\n    assert sha(mask_path) == ref[\'mask_sha256\']\n    assert sha(a.code/\'public252-v1.json\') == ref[\'protocol_sha256\']\n    validate(a.data, json.loads((a.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(exist_ok=False, parents=True)\n    set_seed(3407)\n    loader = evaluation_loader(a.data, \'val\', 0, True)\n    scenes = list(map(str, loader.dataset.names))\n    assert sorted(scenes) == sorted(ref[\'scenes\']) and len(scenes) == 25\n    model = model_generator(\'CRSDUN\', 28, 23, str(a.checkpoint))\n    model.eval()\n    physical = torch.as_tensor(loadmat(mask_path)[\'mask\'], dtype=torch.float32, device=\'cuda\')\n    phi, nominal = init_mask(str(mask_path), \'SSR\', 1, 28)\n    built = make_operator(physical)\n    assert all(torch.equal(x, y) for x, y in zip(built, nominal)), \'Nominal SSR tuple differs\'\n    assert all(torch.equal(x, y) for x, y in zip(make_operator(mix_mask(physical, 1, 0)), nominal))\n    nominal_hashes = [tensor_sha(x) for x in nominal]\n    conditions = [(\'clean\', 0, 0.0)] + [(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\', dx, alpha) for alpha in ALPHAS for dx in (1, -1)]\n    manifest = dict(status=\'running\', checkpoint_epoch=441, checkpoint_sha256=sha(a.checkpoint),\n                    protocol_sha256=ref[\'protocol_sha256\'], mask_sha256=sha(mask_path),\n                    script_sha256=sha(__file__), scenes=scenes, alphas=list(ALPHAS),\n                    conditions=conditions, completed_conditions=[], torch=str(torch.__version__),\n                    gpu=torch.cuda.get_device_name(0), expected_model_forwards=425,\n                    test_evaluated=False, training=False,\n                    scope=\'25 validation scenes; frozen model; identical measurement reused for nominal and matched full SSR tuples.\',\n                    caveat=\'Linear mask mixing with a zero-filled +/-1px shift is synthetic, not calibrated hardware motion. Matched masks may still be outside the training distribution.\',\n                    metrics=\'Every-stage confusion/MSE/PSNR_ref1; SSIM_ref1 final stage only. Scene-averaged reconstruction metrics; aggregate confusion mIoU.\')\n    manifest_path = a.out/\'experiment.json\'\n    def save_manifest():\n        manifest_path.write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    summary, severity_rows = [], []\n    started = time.time()\n    try:\n      with torch.inference_mode():\n        for name, dx, alpha in conditions:\n            folder = a.out/name\n            folder.mkdir()\n            mixed = physical if name == \'clean\' else mix_mask(physical, dx, alpha)\n            matched = make_operator(mixed)\n            acquisition = matched[1]\n            assert torch.equal(matched[0], shift_back_mask(acquisition))\n            expected_energy = acquisition.square().sum(1, keepdim=True)\n            expected_energy[expected_energy == 0] = 1\n            assert torch.equal(matched[2], expected_energy)\n            paired_ops = [(\'nominal\', nominal)] if name == \'clean\' else [(\'nominal\', nominal), (\'matched\', matched)]\n            severity_rows.append(dict(condition=name, dx=dx, alpha=alpha,\n                                      mask_relative_error=relative_error(mixed, physical),\n                                      changed_fraction=float((mixed != physical).float().mean()),\n                                      mean_transmittance=float(mixed.mean())))\n            pd.DataFrame(severity_rows).to_csv(a.out/\'mask_severity.csv\', index=False)\n            seg = {mode: [Metrics_Seg(23, get_class_names()) for _ in range(5)] for mode, _ in paired_ops}\n            records = []\n            for index, sample in enumerate(loader):\n                scene = scenes[index]\n                target = sample[\'image\'].float().cuda()\n                gt_cpu = target.cpu()\n                truth = sample[\'label\'].numpy()[0]\n                y = init_meas(target, acquisition, \'Y\')\n                if index == 0:\n                    assert torch.allclose(measure(target, acquisition), y, atol=1e-6, rtol=1e-6)\n                y_nominal = init_meas(target, phi, \'Y\')\n                measurement_error = relative_error(y, y_nominal)\n                y_digest = tensor_sha(y)\n                for mode, operator in paired_ops:\n                    op_hashes = [tensor_sha(x) for x in operator]\n                    xs, logits = model(y, operator)\n                    assert len(xs) == len(logits) == 5\n                    for k, (x, logit) in enumerate(zip(xs, logits), 1):\n                        assert x.shape == target.shape and logit.shape == (1, 23, *truth.shape)\n                        assert torch.isfinite(x).all() and torch.isfinite(logit).all(), f\'Nonfinite: {name}/{mode}/{scene}/stage{k}\'\n                        x_cpu = x.float().cpu()\n                        pred = logit.argmax(1).cpu().numpy()[0]\n                        hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                        np.save(folder/f\'{mode}_{scene}_stage{k}_confusion.npy\', hist)\n                        seg[mode][k-1].add_batch(truth[None], pred[None])\n                        mse = float((x_cpu-gt_cpu).square().mean())\n                        metrics = {\'MSE\':mse, \'PSNR\':float(-10*torch.log10(torch.tensor(mse))), \'SSIM\':None}\n                        if k == 5:\n                            rec = Metrics_Rec()\n                            rec.add_batch(gt_cpu, x_cpu)\n                            metrics = rec.get_table().iloc[0].to_dict()\n                        records.append(dict(condition=name, mode=mode, scene=scene, stage=k,\n                                            dx=dx, alpha=alpha, measurement_sha256=y_digest,\n                                            measurement_relative_error=measurement_error, **metrics))\n                    assert tensor_sha(y) == y_digest, \'Measurement mutated during inference\'\n                    assert [tensor_sha(t) for t in operator] == op_hashes, \'SSR tuple mutated\'\n                    del xs, logits, x, logit, x_cpu\n                pd.DataFrame(records).to_csv(folder/\'per_scene_stage_metrics.csv\', index=False)\n                del target, gt_cpu, y, y_nominal\n                print(f\'{name}: {index+1}/25; modes={len(paired_ops)}; elapsed={(time.time()-started)/60:.1f}min\', flush=True)\n            assert [tensor_sha(t) for t in nominal] == nominal_hashes\n            for mode, _ in paired_ops:\n                for k in range(1,6):\n                    acc = seg[mode][k-1]\n                    assert np.array_equal(sum(np.load(folder/f\'{mode}_{s}_stage{k}_confusion.npy\') for s in scenes), acc.confusion_matrix)\n                    np.save(folder/f\'{mode}_stage{k}_aggregate_confusion.npy\', acc.confusion_matrix)\n                    table = acc.get_table()\n                    table.to_csv(folder/f\'{mode}_stage{k}_segmentation.csv\')\n                    items = [r for r in records if r[\'mode\'] == mode and r[\'stage\'] == k]\n                    summary.append(dict(condition=name, mode=mode, stage=k, alpha=alpha, dx=dx,\n                                        foreground_miou_all22=float(table.loc[\'total(-bg)\', \'IoU\']),\n                                        PSNR=float(np.mean([r[\'PSNR\'] for r in items])),\n                                        MSE=float(np.mean([r[\'MSE\'] for r in items])),\n                                        SSIM=float(np.mean([r[\'SSIM\'] for r in items])) if k == 5 else None))\n            pd.DataFrame(summary).to_csv(a.out/\'stage_summary.csv\', index=False)\n            if name == \'clean\':\n                final = summary[-1]\n                check = dict(miou_difference=final[\'foreground_miou_all22\']-ref[\'miou\'], psnr_difference=final[\'PSNR\']-ref[\'psnr\'])\n                check[\'passed\'] = abs(check[\'miou_difference\']) < 1e-6 and abs(check[\'psnr_difference\']) < 1e-4\n                (a.out/\'clean_equivalence.json\').write_text(json.dumps(check, indent=2))\n                assert check[\'passed\'], \'Clean check failed; stopping before stresses\'\n            manifest[\'completed_conditions\'].append(name)\n            save_manifest()\n        pairs = []\n        for name, dx, alpha in conditions[1:]:\n            n, m = [next(r for r in summary if r[\'condition\']==name and r[\'mode\']==mode and r[\'stage\']==5) for mode in (\'nominal\', \'matched\')]\n            pairs.append(dict(condition=name, dx=dx, alpha=alpha,\n                              nominal_miou_percent=100*n[\'foreground_miou_all22\'], matched_miou_percent=100*m[\'foreground_miou_all22\'],\n                              matched_minus_nominal_miou_points=100*(m[\'foreground_miou_all22\']-n[\'foreground_miou_all22\']),\n                              nominal_psnr=n[\'PSNR\'], matched_psnr=m[\'PSNR\'], matched_minus_nominal_psnr=m[\'PSNR\']-n[\'PSNR\']))\n        pd.DataFrame(pairs).to_csv(a.out/\'paired_final_summary.csv\', index=False)\n        manifest[\'status\'] = \'completed\'\n        print(pd.DataFrame(pairs).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest[\'status\'] = \'failed\'\n        manifest[\'error\'] = repr(exc)\n        raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started\n        save_manifest()\n\nif __name__ == \'__main__\':\n    main()\n', 'numerical_trace.py': '"""Observe frozen CRSDUN through hooks; require exact traced/untraced outputs."""\nimport argparse, json, sys, time\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom operator_control import make_operator, mix_mask, sha, tensor_sha\n\ndef stats(x):\n    a=x.detach().cpu().double().numpy()\n    assert np.isfinite(a).all(), \'Nonfinite tensor in trace\'\n    return dict(min=float(a.min()),max=float(a.max()),rms=float(np.sqrt(np.mean(a*a))),max_abs=float(np.abs(a).max()))\n\ndef denominator_stats(d):\n    r=stats(d); a=d.detach().cpu().double().numpy()\n    r.update(min_abs=float(np.abs(a).min()),min_abs_index=[int(i) for i in np.unravel_index(np.abs(a).argmin(),a.shape)],nonpositive=int((a<=0).sum()),elements=int(a.size))\n    for limit in (1e-6,1e-4,1e-2,.1):r[f\'abs_below_{limit:g}\']=int((np.abs(a)<limit).sum())\n    return r\n\ndef spatial_error(x, target, aligned_energy):\n    delta=x.detach().cpu().double().numpy()-target\n    sq=delta[0]**2\n    h,w=sq.shape[-2:]\n    border=np.ones((h,w),dtype=bool)\n    border[16:-16,16:-16]=False\n    regions={\'image_border16\':np.broadcast_to(border,sq.shape),\'image_interior\':np.broadcast_to(~border,sq.shape)}\n    regions.update({\'energy_zero\':aligned_energy==0,\'energy_0_to_0.1\':(aligned_energy>0)&(aligned_energy<=.1),\n                    \'energy_0.1_to_1\':(aligned_energy>.1)&(aligned_energy<=1),\n                    \'energy_1_to_4\':(aligned_energy>1)&(aligned_energy<=4),\'energy_above4\':aligned_energy>4})\n    total=float(sq.sum()); result={}\n    for name,mask in regions.items():\n        n=int(mask.sum()); s=float(sq[mask].sum())\n        result[name]=dict(voxels=n,squared_error_sum=s,mse=s/n if n else None,fraction_total_error=s/total if total else 0.)\n    return dict(mse=float(sq.mean()),total_squared_error=total,regions=result)\n\nclass Observer:\n    def __init__(self,model,operator,target,emit,measurement=None):\n        self.model=model;self.operator=operator;self.target=target.detach().cpu().double().numpy();self.emit=emit\n        self.stage=0;self.handles=[];self.original_phif=model.mul_Phif;self.original_phit=model.mul_PhiTg\n        self.measurement=measurement\n        self.had_phif=\'mul_Phif\' in model.__dict__;self.had_phit=\'mul_PhiTg\' in model.__dict__\n        _,bands,h,w=target.shape\n        raw=operator[1].square().sum(1)[0]\n        self.aligned_energy=torch.stack([raw[:,2*c:2*c+w] for c in range(bands)]).cpu().numpy()\n\n    def record(self,event,x,error=False,**extra):\n        row=dict(stage=self.stage,event=event,values=stats(x),**extra)\n        if error:row[\'reconstruction_error\']=spatial_error(x,self.target,self.aligned_energy)\n        self.emit(row)\n\n    def __enter__(self):\n        def para_hook(module,args,out):\n            self.stage+=1\n            p=out.detach().cpu().flatten().tolist()\n            assert len(p)==4\n            self.emit(dict(stage=self.stage,event=\'parameters\',a=p[0],mu=p[1],b=p[2],gamma=p[3],\n                           denominator=denominator_stats(self.operator[2]+out[:,0:1])))\n        def phif(phi,x):\n            self.record(\'x_new_before_data_consistency\',x,error=True)\n            result=self.original_phif(phi,x)\n            self.record(\'predicted_measurement\',result)\n            if self.measurement is not None:self.record(\'measurement_residual\',self.measurement.unsqueeze(1)-result)\n            return result\n        def phit(phi,g):\n            self.record(\'residual_divided_by_denominator\',g)\n            result=self.original_phit(phi,g)\n            self.record(\'data_consistency_correction\',result)\n            return result\n        self.model.mul_Phif=phif;self.model.mul_PhiTg=phit\n        for module in self.model.para_est:self.handles.append(module.register_forward_hook(para_hook))\n        for k in range(self.model.stage):\n            self.handles.append(self.model.net_stage[3*k].register_forward_pre_hook(lambda m,args:self.record(\'z_before_reconstruction_attention\',args[0],error=True)))\n            self.handles.append(self.model.net_stage[3*k].register_forward_hook(lambda m,args,out:self.record(\'after_reconstruction_attention\',out,error=True)))\n            self.handles.append(self.model.net_stage[3*k+1].register_forward_hook(lambda m,args,out:self.record(\'after_refinement\',out,error=True)))\n        return self\n\n    def __exit__(self,*exc):\n        for h in self.handles:h.remove()\n        if self.had_phif:self.model.mul_Phif=self.original_phif\n        else:del self.model.mul_Phif\n        if self.had_phit:self.model.mul_PhiTg=self.original_phit\n        else:del self.model.mul_PhiTg\n\ndef main():\n    p=argparse.ArgumentParser()\n    for name in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+name,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    from scipy.io import loadmat\n    import pandas as pd\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    conditions=[(\'clean\',0,0.)]+[(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\',dx,alpha) for alpha in (.1,.25,1.) for dx in (1,-1)]\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],mask_sha256=ref[\'mask_sha256\'],script_sha256=sha(__file__),helper_sha256=sha(Path(__file__).with_name(\'operator_control.py\')),scenes=scenes,conditions=conditions,completed_conditions=[],completed_identity_pairs=0,training=False,test_evaluated=False,expected_forwards=350,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'Matched operators only. Every traced forward paired with an uninstrumented forward; all five reconstruction/logit tensors must hash identically. Regions are image-border16 and raw detector-energy bins aligned to each spectral voxel, not calibrated hardware regions.\')\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];scene_metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha in conditions:\n            operator=make_operator(mask if not dx else mix_mask(mask,dx,alpha))\n            op_hash=[tensor_sha(t) for t in operator]\n            accumulator=Metrics_Seg(23,get_class_names());rec=Metrics_Rec()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                y=init_meas(target,operator[1],\'Y\');yh=tensor_sha(y)\n                xs,ls=model(y,operator)\n                baseline=[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n                def emit(row):\n                    f.write(json.dumps(dict(condition=name,scene=scene,**row),allow_nan=False)+\'\\n\')\n                with Observer(model,operator,target,emit,measurement=y) as observer:xs,ls=model(y,operator)\n                f.flush()\n                assert observer.stage==5\n                equal=baseline==[tensor_sha(t) for t in [*xs,*ls]]\n                checks.append(dict(condition=name,scene=scene,all_stage_tensors_bitwise_identical=equal))\n                (args.out/\'identity_checks.json\').write_text(json.dumps(checks,indent=2))\n                assert equal,\'Instrumentation altered predictions\'\n                assert tensor_sha(y)==yh and [tensor_sha(t) for t in operator]==op_hash\n                one=Metrics_Rec();one.add_batch(target.cpu(),xs[-1].cpu())\n                metric=one.get_table().iloc[0].to_dict()\n                e=expected[\'scenes\'][name][scene]\n                assert abs(metric[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(metric[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Prior scene metrics not reproduced\'\n                for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec,field,getattr(rec,field)+getattr(one,field))\n                pred=ls[-1].argmax(1).cpu().numpy()[0];accumulator.add_batch(truth[None],pred[None])\n                hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                assert __import__(\'hashlib\').sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Prior scene confusion differs\'\n                scene_metrics.append(dict(condition=name,scene=scene,**metric));pd.DataFrame(scene_metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                manifest[\'completed_identity_pairs\']+=1;save()\n                del xs,ls,target,y\n                print(f\'{name}: {index+1}/25, traced/untraced identical, prior metrics reproduced; {(time.time()-started)/60:.1f}min\',flush=True)\n            table=accumulator.get_table();row=dict(condition=name,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec.get_table().iloc[0].to_dict())\n            e=expected[\'summary\'][name]\n            assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n            summaries.append(row);pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            table.to_csv(args.out/f\'{name}_segmentation.csv\');np.save(args.out/f\'{name}_confusion.npy\',accumulator.confusion_matrix)\n            manifest[\'completed_conditions\'].append(name);save()\n        manifest[\'status\']=\'completed\'\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'gain_guard.py': '"""Fixed energy floor for an isolated data-consistency gain bound; not whole-network stability."""\nimport inspect, textwrap, types\nimport torch\nfrom numerical_trace import denominator_stats\n\nFACTOR = 1.0\n\ndef safe_denominator(d, energy):\n    return torch.maximum(d, FACTOR*energy)\n\nclass Guard:\n    def __init__(self, model, emit, enabled=True):\n        self.model=model;self.emit=emit;self.enabled=enabled;self.stage=0;self.total_activated=0\n        self.had_forward=\'forward\' in model.__dict__;self.original=model.forward\n        assert not hasattr(model,\'_guard_denominator\')\n        source=textwrap.dedent(inspect.getsource(self.original.__func__))\n        old=\'torch.div(y - A_x_phitheta, PhiPhiT + a)\'\n        assert source.count(old)==1, \'Unexpected forward source; do not patch\'\n        source=source.replace(old,\'torch.div(y - A_x_phitheta, self._guard_denominator(PhiPhiT + a, PhiPhiT))\')\n        namespace=dict(self.original.__func__.__globals__)\n        exec(compile(source,\'<source-pinned-denominator-guard>\',\'exec\'),namespace)\n        self.patched=types.MethodType(namespace[\'forward\'],model)\n\n    def __enter__(self):\n        def apply(d,energy):\n            self.stage+=1\n            used=safe_denominator(d,energy) if self.enabled else d\n            count=int((used!=d).sum());self.total_activated+=count\n            gain=energy/used\n            if self.enabled:assert bool((gain>=0).all() and (gain<=1).all()), \'Gain bound violated\'\n            self.emit(dict(stage=self.stage,event=\'denominator_guard\',enabled=self.enabled,factor=FACTOR,\n                           activated=count,elements=d.numel(),guarded_energy_gain_min=float(gain.min()),guarded_energy_gain_max=float(gain.max()),original=denominator_stats(d),used=denominator_stats(used)))\n            return used\n        self.model._guard_denominator=apply;self.model.forward=self.patched\n        return self\n\n    def __exit__(self,*exc):\n        del self.model._guard_denominator\n        if self.had_forward:self.model.forward=self.original\n        else:del self.model.forward\n', 'gain_experiment.py': '"""Frozen paired evaluation of one prespecified denominator safeguard."""\nimport argparse,hashlib,json,sys,time\nfrom pathlib import Path\nfrom contextlib import nullcontext\nimport numpy as np\nimport torch\nfrom operator_control import make_operator,mix_mask,sha,tensor_sha\nfrom numerical_trace import Observer\nfrom gain_guard import Guard,FACTOR\n\ndef main():\n    p=argparse.ArgumentParser()\n    for key in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+key,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    assert sha(args.code/\'models/CRSDUN.py\')==\'57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543\'\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    weight_hashes={k:tensor_sha(v) for k,v in model.state_dict().items()}\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    # Include clean/binary tradeoffs first; their predictions may change with the energy floor.\n    conditions=[(\'clean\',0,0.)]+[(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\',dx,alpha) for alpha in (1.,.1,.25) for dx in (1,-1)]\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],mask_sha256=ref[\'mask_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],factor=FACTOR,formula=\'d_safe=max(E+a,E); E is existing guarded squared-mask energy\',scenes=scenes,conditions=conditions,completed_conditions=[],completed_pairs=0,expected_forwards=350,training=False,test_evaluated=False,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'Fixed energy floor, no sweep. Matched operators; fresh unchanged controls; guarded-arm tracing only. Clean/binary predictions may change. Full-frame metrics; no training, clipping or border exclusion.\',script_hashes={n:sha(Path(__file__).with_name(n)) for n in (\'gain_experiment.py\',\'gain_guard.py\',\'numerical_trace.py\',\'operator_control.py\')})\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha in conditions:\n            op=make_operator(mask if not dx else mix_mask(mask,dx,alpha));op_hash=[tensor_sha(t) for t in op]\n            seg={mode:Metrics_Seg(23,get_class_names()) for mode in (\'control\',\'guarded\')}\n            rec={mode:Metrics_Rec() for mode in seg}\n            folder=args.out/name;folder.mkdir()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                y=init_meas(target,op[1],\'Y\');yh=tensor_sha(y);baseline_hashes=None\n                for mode in (\'control\',\'guarded\'):\n                    def emit(row):f.write(json.dumps(dict(condition=name,scene=scene,mode=mode,**row),allow_nan=False)+\'\\n\')\n                    ctx=Guard(model,emit) if mode==\'guarded\' else nullcontext()\n                    with ctx as guard:\n                        observer_context=Observer(model,op,target,emit,measurement=y) if mode==\'guarded\' else nullcontext()\n                        with observer_context as observer:xs,ls=model(y,op)\n                    f.flush()\n                    if mode==\'guarded\':assert observer.stage==5\n                    assert all(torch.isfinite(t).all() for t in [*xs,*ls]),\'Nonfinite model output\'\n                    output_hashes=[tensor_sha(t) for t in [*xs,*ls]]\n                    if mode==\'control\':baseline_hashes=output_hashes\n                    else:\n                        assert guard.stage==5\n                        identical=baseline_hashes==output_hashes\n                        row=dict(condition=name,scene=scene,activated=guard.total_activated,all_stage_outputs_identical=identical,inactive=guard.total_activated==0)\n                        checks.append(row);(args.out/\'pair_checks.json\').write_text(json.dumps(checks,indent=2))\n                        if guard.total_activated==0:assert identical,\'Inactive guard changed outputs\'\n                    assert tensor_sha(y)==yh and [tensor_sha(t) for t in op]==op_hash\n                    assert not hasattr(model,\'_guard_denominator\') and \'forward\' not in model.__dict__\n                    one=Metrics_Rec();one.add_batch(target.cpu(),xs[-1].cpu());values=one.get_table().iloc[0].to_dict()\n                    pred=ls[-1].argmax(1).cpu().numpy()[0]\n                    hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                    if mode==\'control\':\n                        e=expected[\'scenes\'][name][scene]\n                        assert abs(values[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(values[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Control reconstruction differs from prior run\'\n                        assert hashlib.sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Control segmentation differs from prior run\'\n                    np.save(folder/f\'{mode}_{scene}_confusion.npy\',hist)\n                    seg[mode].add_batch(truth[None],pred[None])\n                    for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec[mode],field,getattr(rec[mode],field)+getattr(one,field))\n                    metrics.append(dict(condition=name,scene=scene,mode=mode,measurement_sha256=yh,**values))\n                    pd.DataFrame(metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                    del xs,ls\n                manifest[\'completed_pairs\']+=1;save();del target,y\n                print(f\'{name}: {index+1}/25 paired; {(time.time()-started)/60:.1f}min\',flush=True)\n            for mode in seg:\n                table=seg[mode].get_table()\n                summed=sum(np.load(folder/f\'{mode}_{s}_confusion.npy\') for s in scenes)\n                assert np.array_equal(summed,seg[mode].confusion_matrix)\n                np.save(folder/f\'{mode}_aggregate_confusion.npy\',summed);table.to_csv(folder/f\'{mode}_segmentation.csv\')\n                row=dict(condition=name,mode=mode,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec[mode].get_table().iloc[0].to_dict())\n                if mode==\'control\':\n                    e=expected[\'summary\'][name]\n                    assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n                summaries.append(row)\n            pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            manifest[\'completed_conditions\'].append(name);save()\n        pairs=[]\n        for name,_,_ in conditions:\n            a,b=[next(r for r in summaries if r[\'condition\']==name and r[\'mode\']==mode) for mode in (\'control\',\'guarded\')]\n            pairs.append(dict(condition=name,control_miou_percent=100*a[\'foreground_miou_all22\'],guarded_miou_percent=100*b[\'foreground_miou_all22\'],miou_change_points=100*(b[\'foreground_miou_all22\']-a[\'foreground_miou_all22\']),control_psnr=a[\'PSNR\'],guarded_psnr=b[\'PSNR\'],psnr_change=b[\'PSNR\']-a[\'PSNR\'],control_mse=a[\'MSE\'],guarded_mse=b[\'MSE\']))\n        pd.DataFrame(pairs).to_csv(args.out/\'paired_summary.csv\',index=False)\n        assert weight_hashes=={k:tensor_sha(v) for k,v in model.state_dict().items()},\'Model state mutated\'\n        manifest.update(status=\'completed\',model_state_unchanged=True)\n        print(pd.DataFrame(pairs).to_string(index=False),flush=True)\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'verify_gain_guard.py': '"""Algebraic gain bound plus real-architecture implementation tests."""\nimport argparse,sys\nimport torch\nfrom gain_guard import Guard,safe_denominator\nfrom numerical_trace import Observer\nfrom operator_control import make_operator,mix_mask,tensor_sha\np=argparse.ArgumentParser();p.add_argument(\'--code\',required=True);args=p.parse_args();sys.path.insert(0,args.code)\nfrom models.CRSDUN import CRSDUN\nfrom utils import init_meas,set_seed\n\n# Float64 check of the isolated update, including zero physical energy.\nphysical=torch.tensor([0.,.01,.0625,1.],dtype=torch.float64)\nA=torch.diag(physical.sqrt());E=torch.where(physical==0,1.,physical)\nx=torch.tensor([.2,.4,.6,.8],dtype=torch.float64);truth=torch.tensor([.8,.6,.4,.2],dtype=torch.float64)\ny=A@truth;r=y-A@x\nfor a in [-.6,0.,.4]:\n    d=E+a;saved=d.clone();used=safe_denominator(d,E)\n    assert torch.equal(d,saved) and torch.all(used>=E)\n    z=x+A.T@(r/used)\n    multiplier=1-physical/used\n    assert torch.all((multiplier>=0)&(multiplier<=1))\n    assert torch.allclose(y-A@z,multiplier*r,atol=1e-14,rtol=1e-14)\n    assert torch.linalg.vector_norm(y-A@z)<=torch.linalg.vector_norm(r)+1e-14\nassert torch.cuda.is_available();torch.set_num_threads(1);set_seed(3407)\nmodel=CRSDUN(stage=5,bands=28,n_class=23).cuda().eval()\nmask=(torch.rand(64,64,device=\'cuda\')>.5).float();target=torch.rand(1,28,64,64,device=\'cuda\')\nwith torch.inference_mode():\n for forced_offset in [.4,-.6]:\n    def forced_a(module,args,out):\n        result=out.clone();result[:,0:1]=forced_offset;return result\n    handles=[m.register_forward_hook(forced_a) for m in model.para_est]\n    for alpha in (0.,.25):\n        op=make_operator(mix_mask(mask,1,alpha));y=init_meas(target,op[1],\'Y\')\n        baseline=model(y,op);hashes=[tensor_sha(t) for xs in baseline for t in xs];del baseline\n        with Guard(model,lambda row:None,enabled=False):out=model(y,op)\n        assert hashes==[tensor_sha(t) for xs in out for t in xs];del out\n        records=[]\n        with Guard(model,records.append) as guard:\n            with Observer(model,op,target,lambda row:None,measurement=y):out=model(y,op)\n        same=hashes==[tensor_sha(t) for xs in out for t in xs]\n        assert guard.stage==5 and len(records)==5\n        if forced_offset>0:assert guard.total_activated==0 and same\n        else:assert guard.total_activated>0 and not same\n        assert all(0<=r[\'guarded_energy_gain_min\']<=r[\'guarded_energy_gain_max\']<=1 for r in records)\n        assert all(torch.isfinite(t).all() for xs in out for t in xs)\n        assert \'forward\' not in model.__dict__ and not hasattr(model,\'_guard_denominator\')\n        del out\n    for h in handles:h.remove()\n try:\n    with Guard(model,lambda row:None):raise RuntimeError(\'intentional cleanup test\')\n except RuntimeError:pass\n assert \'forward\' not in model.__dict__ and not hasattr(model,\'_guard_denominator\')\nprint(\'PASS: isolated residual multiplier in[0,1] including zero physical energy; actual five-stage disabled/inactive bitwise identity; negative-offset activation on binary and fractional masks; gain<=1; Observer compatibility and cleanup. No whole-network stability or trained-checkpoint efficacy claim.\')\n'}
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}
EXPECTED={'source_archive': 'operator_control_epoch441_20261010_183309_608911.zip', 'source_archive_sha256': 'b2f9bf0118804cfdfecc7e72f5aee9a3f36b975631bcb1c4ad1618cec7cb7743', 'summary': {'clean': {'foreground_miou_all22': 0.7876837070566084, 'PSNR': 39.00684616088867, 'MSE': 0.00013123682205332443, 'SSIM': 0.9747850704193115}, 'plus1_alpha0.1': {'foreground_miou_all22': 0.7804071879322305, 'PSNR': 38.480462341308595, 'MSE': 0.00014687360497191547, 'SSIM': 0.9726465129852295}, 'minus1_alpha0.1': {'foreground_miou_all22': 0.7806234925438672, 'PSNR': 38.41059600830078, 'MSE': 0.0001489559863694012, 'SSIM': 0.97251469373703}, 'plus1_alpha0.25': {'foreground_miou_all22': 0.7099818617488114, 'PSNR': -5.109313906431198, 'MSE': 83.81524314329027, 'SSIM': 0.9039690732955933}, 'minus1_alpha0.25': {'foreground_miou_all22': 0.7033165229414478, 'PSNR': -5.086848521232605, 'MSE': 65.10976030603051, 'SSIM': 0.8999737000465393}, 'plus1_alpha1': {'foreground_miou_all22': 0.7830800141043546, 'PSNR': 38.98537872314453, 'MSE': 0.00013183161034248768, 'SSIM': 0.974661271572113}, 'minus1_alpha1': {'foreground_miou_all22': 0.7820777620674779, 'PSNR': 38.88986663818359, 'MSE': 0.0001340003072982654, 'SSIM': 0.9741322302818298}}, 'scenes': {'clean': {'2021-11-03_046': {'PSNR': 39.89459228515625, 'MSE': 0.00010245677549391985, 'confusion_sha256': '9a717b84a51b72b2fba1c9060dfc8ad32d2508a3c8f0eb98494f1809757909ec'}, '2021-11-03_047': {'PSNR': 38.86285400390625, 'MSE': 0.00012993150448892266, 'confusion_sha256': '919915901d083e6ed85b8577721c7392ee968a7d23b41b7d6df5407226b34d16'}, '2021-11-03_057': {'PSNR': 37.99570083618164, 'MSE': 0.00015864624583628029, 'confusion_sha256': '711f63aea60da1ad3e5dd583c1ad6c185b62eb8ead7661faab625fefc9a93000'}, '2021-11-03_085': {'PSNR': 40.45058059692383, 'MSE': 9.01449893717654e-05, 'confusion_sha256': 'f26712d2687056e1f8812c93a119dc945e55a6c1c3a465d8c75b9e4e89c4cfdd'}, '2021-11-03_090': {'PSNR': 40.33523178100586, 'MSE': 9.257135388907045e-05, 'confusion_sha256': 'ce95968be99e39136bb3a54ba923ea41501fa0803c75a0bae08d8bd21e2de7ec'}, '2021-11-03_110': {'PSNR': 39.576499938964844, 'MSE': 0.00011024268314940855, 'confusion_sha256': '925537ac21544cbbed2767f15ad85fa1c7a52691dc70e7712568c6260f9b2c13'}, '2021-11-04_010': {'PSNR': 37.13905334472656, 'MSE': 0.00019323898595757782, 'confusion_sha256': 'c9099b0d0a570152439bb9708c16c6f9882d2b9d23632b94de45b23e5e2e145b'}, '2021-11-04_017': {'PSNR': 38.54598617553711, 'MSE': 0.00013976586342323571, 'confusion_sha256': 'dcdfe2f5a2ef36a30df2960ae7f34537645c5ef3070a89e09ec06fe7708f669c'}, '2021-11-04_024': {'PSNR': 38.70061111450195, 'MSE': 0.00013487727846950293, 'confusion_sha256': 'e3082e8a5aee905c21b646233bda5e8f37889d2ec740925842e5389426415656'}, '2021-11-04_042': {'PSNR': 40.50850296020508, 'MSE': 8.895069913705811e-05, 'confusion_sha256': '69745abc94ea2ee55b0aac789679b0353d08f391c931258e232dd465690d7f22'}, '2021-11-04_047': {'PSNR': 40.22039794921875, 'MSE': 9.505175694357604e-05, 'confusion_sha256': 'b6c73d3bec5395b68de7c48614e082e1c36f6330ee46719b20947da3f4c25bbc'}, '2021-11-04_049': {'PSNR': 40.83124542236328, 'MSE': 8.25801253085956e-05, 'confusion_sha256': 'b63f6d857eeb2b1870346a4ecb5c3594f5dea62fefe6262ece4344a65a2791c2'}, '2021-11-04_055': {'PSNR': 40.75486373901367, 'MSE': 8.404533582506701e-05, 'confusion_sha256': '995f147be920d56d9ba740f6ec33fd436afc5e1a8eaad452b5dcaa746edd9834'}, '2021-11-04_061': {'PSNR': 40.685176849365234, 'MSE': 8.540479029761627e-05, 'confusion_sha256': '59adfbe1bb34d1890af5029d8bd8281620d18396e9b876be0e4f6e4f6f5d2596'}, '2021-11-04_093': {'PSNR': 39.08949661254883, 'MSE': 0.0001233247312484309, 'confusion_sha256': '6366ce691015ac82a2669684a1c4d681bff89544f92fab6972d817ea7e7d7b2c'}, '2021-11-04_098': {'PSNR': 39.36787414550781, 'MSE': 0.00011566774628590792, 'confusion_sha256': '6d227838a684f6f312e50afa89da8c8623ad19564835045da03dc93a2bdabdea'}, '2021-11-05_010': {'PSNR': 37.41633987426758, 'MSE': 0.00018128668307326734, 'confusion_sha256': '13b3bae21986dd485dbe9125a904ee039a7d076c7e1aa9a2c19c4a8317eeee6f'}, '2021-11-05_024': {'PSNR': 39.7016716003418, 'MSE': 0.00010711060895118862, 'confusion_sha256': 'df5555f991ede7f38186ff4cbfe4dca368ad0ff0bfba94e2cb5e5ae992659d4f'}, '2021-11-05_035': {'PSNR': 38.786293029785156, 'MSE': 0.00013224223221186548, 'confusion_sha256': '7642e43435e57e4c293c5497b3ed47fdf0830fab3a34010f983d393ff6f79224'}, '2021-11-05_041': {'PSNR': 38.4978141784668, 'MSE': 0.00014132479554973543, 'confusion_sha256': 'cee79d0f10b1a368417af8ec32939e69ccfc5a1d5d4b70c9727535b9fe968e3b'}, '2021-11-05_046': {'PSNR': 36.10015869140625, 'MSE': 0.0002454617933835834, 'confusion_sha256': '99ceb435926731d4d7593346568ef795f28ff326dcb5a775f1f9fe1af0388e31'}, '2021-11-10_014': {'PSNR': 38.25468063354492, 'MSE': 0.00014946235751267523, 'confusion_sha256': '700d7bfb7ee77774c754fa984c10b556125d20f7eb11ce8f8fea4055a35c9fc2'}, '2021-11-10_024': {'PSNR': 37.73176193237305, 'MSE': 0.00016858673188835382, 'confusion_sha256': '32c9dfe5fd11c769fdd29d729a4cc2575d048096185fe33c83c76f035d77b383'}, '2021-11-10_029': {'PSNR': 38.25230407714844, 'MSE': 0.00014954424113966525, 'confusion_sha256': '55b866708c3de1af700fe8c596c4acee41e9c60fc89886eb282486f138541098'}, '2021-11-10_050': {'PSNR': 37.47146224975586, 'MSE': 0.00017900024249684066, 'confusion_sha256': 'ffff7a303633916099bc9025d29370aab79abad5f287f2f452f346467e5b0f9a'}}, 'plus1_alpha0.1': {'2021-11-03_046': {'PSNR': 39.53356170654297, 'MSE': 0.00011133799853269011, 'confusion_sha256': '74fc44022774fddc2d3a840197e046c73c5050626e157f802892e08a8ae3970a'}, '2021-11-03_047': {'PSNR': 38.42921829223633, 'MSE': 0.00014357476902659982, 'confusion_sha256': '2ce3d59f70510d4f27629c65ea1221c6b4fff5549368e6846e141f6bba354231'}, '2021-11-03_057': {'PSNR': 37.398101806640625, 'MSE': 0.0001820495817810297, 'confusion_sha256': 'babb40ea19ec33fbca3de7480d72b180d3866d0be78a8a68b66ba7a1eccf7165'}, '2021-11-03_085': {'PSNR': 39.71846389770508, 'MSE': 0.00010669727635104209, 'confusion_sha256': '54ef114eaba644b482e72defb86a4d5b911e24996811d862f6bb0a092aafd750'}, '2021-11-03_090': {'PSNR': 39.6631965637207, 'MSE': 0.0001080637812265195, 'confusion_sha256': 'd7b07e83629bb6d48a85433bfeeb9d99b21eb999ddf69b08cb96ac2b25a6fcc2'}, '2021-11-03_110': {'PSNR': 38.660606384277344, 'MSE': 0.00013612551265396178, 'confusion_sha256': '4d2d561e7a719337bf24cd74ecfd5cd6e8eed94b1a8a9fb3e71f4380fc87e583'}, '2021-11-04_010': {'PSNR': 36.83472442626953, 'MSE': 0.00020726557704620063, 'confusion_sha256': '543788170690efed986c186154b356d3f8b37ae5ae3d5c40f69a693b0ffb7667'}, '2021-11-04_017': {'PSNR': 38.19437026977539, 'MSE': 0.00015155240544117987, 'confusion_sha256': '4ecdb1d9c131545b6465cb2f6655cf57e58f4102b1d0f390fe04c259d8668765'}, '2021-11-04_024': {'PSNR': 38.337066650390625, 'MSE': 0.00014665376511402428, 'confusion_sha256': 'b2f7017b0135d8af9983fde8ac73650082fa5e34c6885c915d4e28f5c85f185a'}, '2021-11-04_042': {'PSNR': 39.93755340576172, 'MSE': 0.00010144825500901788, 'confusion_sha256': 'f76ec9713fff65f4d1aef2658e4a7bc4f98f77b342008b199ed4304d316954ed'}, '2021-11-04_047': {'PSNR': 39.63911056518555, 'MSE': 0.00010866473894566298, 'confusion_sha256': '4a0f2d6389539eb636b013b6816fbf617c6f7b4f045018981882104bc8345341'}, '2021-11-04_049': {'PSNR': 40.25779724121094, 'MSE': 9.423670417163521e-05, 'confusion_sha256': '0b49214fcd84d7922c192e60f21be8517bf86b8cff7aa9714ed8a51bcf89b108'}, '2021-11-04_055': {'PSNR': 39.86824417114258, 'MSE': 0.000103080237749964, 'confusion_sha256': '8cc5e7d7f0945238df53f2d9672225549251d60810a28e4e4aa565963f02ce73'}, '2021-11-04_061': {'PSNR': 39.8060417175293, 'MSE': 0.00010456730524310842, 'confusion_sha256': '60fe3ce021d34106b146016292b483da442d708c45db3bc2d42951d0feb031d0'}, '2021-11-04_093': {'PSNR': 38.563316345214844, 'MSE': 0.00013920932542532682, 'confusion_sha256': '555ac685515ef30d01a51135613607f7ec4c60ac53c28292e3d7f173ed36d617'}, '2021-11-04_098': {'PSNR': 38.90040588378906, 'MSE': 0.00012881297152489424, 'confusion_sha256': 'a6beda01a90aae13038df16fb931b4fdec8bf94d10e4027a9148bcb3756d070f'}, '2021-11-05_010': {'PSNR': 37.00151824951172, 'MSE': 0.0001994563644984737, 'confusion_sha256': 'bf0749f32bd5d80958f98e352fd7fd1131008676df80a3f46eb4f28b1ac25f72'}, '2021-11-05_024': {'PSNR': 38.845340728759766, 'MSE': 0.00013045647938270122, 'confusion_sha256': '1bd25ebf983cbd00fffc9cf8659e15393a561a6eace3e1b533ef944762731df3'}, '2021-11-05_035': {'PSNR': 38.225521087646484, 'MSE': 0.00015046920452732593, 'confusion_sha256': '23f7b9d374d780201f3077757527583beb1225381eb926082b57f3a4169d8efe'}, '2021-11-05_041': {'PSNR': 37.94324493408203, 'MSE': 0.00016057398170232773, 'confusion_sha256': 'e6375941a1fdea5e3321dee2238122ea334eea1c51beb4d9fd86ad68e6154b5e'}, '2021-11-05_046': {'PSNR': 35.822505950927734, 'MSE': 0.0002616672427393496, 'confusion_sha256': '37d8a2e9cdc0a84b7438fcb02912645900f27c501d1f824a3adede7dc38383f5'}, '2021-11-10_014': {'PSNR': 37.92229080200195, 'MSE': 0.00016135061741806567, 'confusion_sha256': 'e6510dad970ce41a35f9d809d214e3e9300e620010fdcc88dfcd73eac85d8ada'}, '2021-11-10_024': {'PSNR': 37.33868408203125, 'MSE': 0.00018455726967658848, 'confusion_sha256': 'd945f704aef8878db17ecf69be736bbdb13d93f4e5499f7c29a31bc42e81959b'}, '2021-11-10_029': {'PSNR': 37.95048522949219, 'MSE': 0.00016030656115617603, 'confusion_sha256': '76065de3abf7f309e3985213ad4785d89f595d58597cf79bde1b6e9a0f95f7cd'}, '2021-11-10_050': {'PSNR': 37.22018814086914, 'MSE': 0.0001896621979540214, 'confusion_sha256': 'b94d127de50692d41ba0666718afc1ac429a68f510931393d09d17e7b83f1af0'}}, 'minus1_alpha0.1': {'2021-11-03_046': {'PSNR': 39.504478454589844, 'MSE': 0.00011208618525415659, 'confusion_sha256': '12a79283c292e64e439aa3a508a48a4b79aad92aa66a919f06e4c1b505cf203b'}, '2021-11-03_047': {'PSNR': 38.409427642822266, 'MSE': 0.0001442304637748748, 'confusion_sha256': 'c872b12f217d64b7e7f97031757ce9cbb01fc394d5b8a44346040b749778ee85'}, '2021-11-03_057': {'PSNR': 37.30839157104492, 'MSE': 0.0001858491450548172, 'confusion_sha256': '9d164eeba19d0d1921c21ea102649cea84fec6c0bbb830e89f2a02c4764236d4'}, '2021-11-03_085': {'PSNR': 39.658958435058594, 'MSE': 0.00010816926078405231, 'confusion_sha256': 'ee617f071d4418738a87a45e9688a0b6295f84d04d8f2a71b282c2d92e1c51ba'}, '2021-11-03_090': {'PSNR': 39.579044342041016, 'MSE': 0.00011017820361303166, 'confusion_sha256': '55c32cb03f28c23eb3af7597cce6f559fa618bab9a6d73ad087a769c3bf43cb9'}, '2021-11-03_110': {'PSNR': 38.48360824584961, 'MSE': 0.0001417878520442173, 'confusion_sha256': '0fa7a52f5c25647b61412ad526ac22d40bdfcaf859cceae4d8c996b86dd7e6b0'}, '2021-11-04_010': {'PSNR': 36.857460021972656, 'MSE': 0.0002061835111817345, 'confusion_sha256': 'cca771642a02bf9b162821778d29d04adaf664b9d64f6a193bc751aa33510cdf'}, '2021-11-04_017': {'PSNR': 38.16506576538086, 'MSE': 0.00015257846098393202, 'confusion_sha256': '05610aafa0917bb5762013d6c88e68aae5c7dafad95e01914a0a9a93d18beb7e'}, '2021-11-04_024': {'PSNR': 38.302467346191406, 'MSE': 0.00014782676589675248, 'confusion_sha256': 'b753920aeb07ebbd5721e3c21c8d3a0632a64f1d55361ff128a0ba1f77534a5f'}, '2021-11-04_042': {'PSNR': 39.79904556274414, 'MSE': 0.00010473588190507144, 'confusion_sha256': 'a186add554b815e1981560085145a33acd0bee8132718d2e1a2d0cac0e087350'}, '2021-11-04_047': {'PSNR': 39.448638916015625, 'MSE': 0.0001135365673690103, 'confusion_sha256': '5a688bdb8d0a318edc5322a44e144542c9896dfa3ad749e2fe5f192905e823b0'}, '2021-11-04_049': {'PSNR': 40.15362548828125, 'MSE': 9.652441804064438e-05, 'confusion_sha256': '663e1e7398596f06fb12aca03ca1e9fa39e6be70197f32e3461b9226d70d61bd'}, '2021-11-04_055': {'PSNR': 39.721153259277344, 'MSE': 0.00010663115972420201, 'confusion_sha256': 'edc0f1d02e855da0cd6722af59b80cd0eb42561bdf9fc804e6d7925a503e05ed'}, '2021-11-04_061': {'PSNR': 39.71446990966797, 'MSE': 0.00010679545812308788, 'confusion_sha256': 'a79245940931ee2953d9ff06c8cb5b6aaa5cbff1306d56f52583dbf278bffebd'}, '2021-11-04_093': {'PSNR': 38.49284362792969, 'MSE': 0.00014148661284707487, 'confusion_sha256': '0c4750df4a807cfb5408514c2744551bcb7a11a738d4cb1d0464c2bbd72f4f6d'}, '2021-11-04_098': {'PSNR': 38.83191680908203, 'MSE': 0.00013086042599752545, 'confusion_sha256': '9bf1f5b28d2a656a05c37588b52102d54c674dad8090b12393ab112529d5f368'}, '2021-11-05_010': {'PSNR': 36.97058868408203, 'MSE': 0.00020088198652956635, 'confusion_sha256': '5fab299a74c84535834f00737c7838b63d790c970ba865e4806118f43b03e693'}, '2021-11-05_024': {'PSNR': 38.72041320800781, 'MSE': 0.00013426375517155975, 'confusion_sha256': '3bf862732ff99c2cff8860479505212d4d2048fdf1417d77dd56d009a1d8f3b7'}, '2021-11-05_035': {'PSNR': 38.15167999267578, 'MSE': 0.00015304956468753517, 'confusion_sha256': '01b3900646776fbbff267c32f504b380974ef87daed8bdae6ffd34b28f12e9e0'}, '2021-11-05_041': {'PSNR': 37.860992431640625, 'MSE': 0.00016364408656954765, 'confusion_sha256': '96e41c724be4aa0407ae092a8ce1023cd1ae87ec9ed39a1c0d06f6eb51b45c53'}, '2021-11-05_046': {'PSNR': 35.8121337890625, 'MSE': 0.0002622929750941694, 'confusion_sha256': '919c5c55e5be26195e513aac79cc0392d50425e19b7f9cc2fcd246d53ac943ba'}, '2021-11-10_014': {'PSNR': 37.8758544921875, 'MSE': 0.00016308513295371085, 'confusion_sha256': '02efc1b17df6a4dda23af082bc7a2d54e3a2ac41d7688621adfc1e65d694212c'}, '2021-11-10_024': {'PSNR': 37.33454513549805, 'MSE': 0.0001847333915065974, 'confusion_sha256': 'f60bb3abf0e51f4ce4f6036e3f39adb008075ccc280cb0c505fdbccf1cba6efb'}, '2021-11-10_029': {'PSNR': 37.91758346557617, 'MSE': 0.00016152569151017815, 'confusion_sha256': 'f23b5a6d0bf26bfb75b13384937693c9581804d1f7e1f207316ce642dd443ec7'}, '2021-11-10_050': {'PSNR': 37.190513610839844, 'MSE': 0.00019096270261798054, 'confusion_sha256': '8cd3ec56bd8bebe50e08eb9d21e2fac8ac749c1b13c97c2734bac2f0aca06c8d'}}, 'plus1_alpha0.25': {'2021-11-03_046': {'PSNR': 8.277036666870117, 'MSE': 0.1486949622631073, 'confusion_sha256': '65acef90a8030dca16eae33a2ccc7e1404ce7ba7d6d09a5d7c14b12df9e1c8a4'}, '2021-11-03_047': {'PSNR': -12.5802640914917, 'MSE': 18.114505767822266, 'confusion_sha256': '3d04f7a26a1bf259fa3734c9ed2e57bd34a59167ba32aad00c00962c96afe3e4'}, '2021-11-03_057': {'PSNR': -0.5277264714241028, 'MSE': 1.1292046308517456, 'confusion_sha256': '8f85aadc0b630d6e17553e566c7159263192edec6c86a565930f6c6be3f14948'}, '2021-11-03_085': {'PSNR': -8.534158706665039, 'MSE': 7.135361194610596, 'confusion_sha256': '365e74e2af6c468d1df8653f8cfef603cfa571228fba120bd2f2dff2bd39306b'}, '2021-11-03_090': {'PSNR': -7.22999382019043, 'MSE': 5.284445285797119, 'confusion_sha256': 'dfedf56ceb73a1e2ccb7ba8ad3637b73c72d3dab40fa108d5c26cb9533ce937b'}, '2021-11-03_110': {'PSNR': 12.149971008300781, 'MSE': 0.06095408275723457, 'confusion_sha256': 'fd6fc38362dea4862579ba7cfc6ef61bf796a00a10d1ea7c83101f034bc8c422'}, '2021-11-04_010': {'PSNR': -6.972059726715088, 'MSE': 4.979732036590576, 'confusion_sha256': '768bcb93e017a0890aaa9f8ba136b8b56b2bf5cab1372df8a21dd4d2e5ffb600'}, '2021-11-04_017': {'PSNR': -3.0808913707733154, 'MSE': 2.0327742099761963, 'confusion_sha256': 'fa0a264501321e5a175dd0bdfa6a656fa4cc1f7db5dfd7a1f37f7247958f09ca'}, '2021-11-04_024': {'PSNR': -2.196054220199585, 'MSE': 1.658079743385315, 'confusion_sha256': '984d6008696749b3462f01087b3140f5f18c83b873cc6c1c138ff3ae114bddeb'}, '2021-11-04_042': {'PSNR': -5.517134666442871, 'MSE': 3.5621604919433594, 'confusion_sha256': '03fdaf6ef0aa9233d17059cc32a28a9f827b6ef8fa9ab3186dd4c900264eecfb'}, '2021-11-04_047': {'PSNR': -10.676491737365723, 'MSE': 11.685553550720215, 'confusion_sha256': '198ee43b581c33226515a8ffd38a676870ba5bd1231349faafaccb7c6fe8be15'}, '2021-11-04_049': {'PSNR': -12.803421974182129, 'MSE': 19.069631576538086, 'confusion_sha256': '484d9c9d11a6e8d567548d3917ff7e38ad81a304bb87362b17831100e7c36144'}, '2021-11-04_055': {'PSNR': 3.5782041549682617, 'MSE': 0.43871206045150757, 'confusion_sha256': '3135c3b6cac4213f18ce2c168352d7f69c7c6c6c764ad468ee73338fb349e2d9'}, '2021-11-04_061': {'PSNR': -0.21835699677467346, 'MSE': 1.0515639781951904, 'confusion_sha256': '3d719225209b182810dfaac5a05398524d9018da717b153b995cbeb949091c43'}, '2021-11-04_093': {'PSNR': -0.7805860042572021, 'MSE': 1.1969020366668701, 'confusion_sha256': '59e39c80d583e00071cae25bb81f32b9d138219848fe8b5cb1a48476efb1c84e'}, '2021-11-04_098': {'PSNR': -7.466648578643799, 'MSE': 5.580394744873047, 'confusion_sha256': 'f8b05fc5a9adf39caa8436f23ef4b5f010abd26962fc154910eb066676b43029'}, '2021-11-05_010': {'PSNR': -4.319344997406006, 'MSE': 2.7035505771636963, 'confusion_sha256': '7a01f278b319d941c4fe548b746a9f99ec2b4e348ab953cd1e65e4051b509129'}, '2021-11-05_024': {'PSNR': 2.2303483486175537, 'MSE': 0.5983635783195496, 'confusion_sha256': 'afeb3f00632d036adaef01c1901e14f30098b8c48990343c5a29efb02e98456c'}, '2021-11-05_035': {'PSNR': 8.731414794921875, 'MSE': 0.13392402231693268, 'confusion_sha256': 'c7704dbb19830007798127ae5295984e6149965290f37e931c9d5a13aacc3058'}, '2021-11-05_041': {'PSNR': -1.4292829036712646, 'MSE': 1.3897231817245483, 'confusion_sha256': 'b8ccff5a7dfa4918a7a9812f93743d402f5a16905de6ba3163781479638303b6'}, '2021-11-05_046': {'PSNR': 9.312551498413086, 'MSE': 0.1171506717801094, 'confusion_sha256': '58ecfc75d2e41925458a71b520839ddb8570fbbb4e2a9446ccdc2409e9fee2eb'}, '2021-11-10_014': {'PSNR': -30.780231475830078, 'MSE': 1196.8046875, 'confusion_sha256': '6c5c3a2302df06978061318210a83cbc2eedfab24f384375af4b4c3a941e6303'}, '2021-11-10_024': {'PSNR': -27.06857681274414, 'MSE': 509.1642150878906, 'confusion_sha256': '68d64fc62f66eb3d725c098fa442f6bce07277635bb191f187e3951d7754232c'}, '2021-11-10_029': {'PSNR': -24.743825912475586, 'MSE': 298.1142883300781, 'confusion_sha256': '6a73b0063fad1dce5373cc13aec6127d6a84cde5abb791b283f843d1e2245264'}, '2021-11-10_050': {'PSNR': -5.0873236656188965, 'MSE': 3.2265052795410156, 'confusion_sha256': 'e4eb77276872c0426737fb89dd4bad0364589bc81b1c173c92c4e321f0cbe707'}}, 'minus1_alpha0.25': {'2021-11-03_046': {'PSNR': 7.803365707397461, 'MSE': 0.1658301204442978, 'confusion_sha256': 'f62fe7edcb36dce8e9569e42182b90e68c70a2eca54970d1df07a942b49bed50'}, '2021-11-03_047': {'PSNR': -14.702699661254883, 'MSE': 29.530447006225586, 'confusion_sha256': 'c6524665f3f4b49a2a63e4281689d77fc8172bb18f8f4c735516c38d653bbdf6'}, '2021-11-03_057': {'PSNR': -1.7272698879241943, 'MSE': 1.4884251356124878, 'confusion_sha256': '77f9329a014c58556af219a02debd7506b851e4136fe38f55b7160dcb0f03d3e'}, '2021-11-03_085': {'PSNR': -0.886996865272522, 'MSE': 1.2265907526016235, 'confusion_sha256': '9f4e08df0829bd23df769ca95dc781c5ba0221e7fddd7e97e792c0ee51b112a4'}, '2021-11-03_090': {'PSNR': -5.25463342666626, 'MSE': 3.3532299995422363, 'confusion_sha256': 'f829e11b9b26f2a568acfaec4dee7c85ded2eeded0403b05b7e60e78af5ef261'}, '2021-11-03_110': {'PSNR': 12.107354164123535, 'MSE': 0.061555165797472, 'confusion_sha256': '3bd0c6c14d19529ca464c9e9d018f370cf70edf3c5f576eb4813d89012b4ce80'}, '2021-11-04_010': {'PSNR': -11.525019645690918, 'MSE': 14.206987380981445, 'confusion_sha256': '5cc1e0457065f19fcd3784acba2edb3575dfed4ffbc4a237ef93f187d8d26bc4'}, '2021-11-04_017': {'PSNR': -16.70313835144043, 'MSE': 46.80733871459961, 'confusion_sha256': '6d5dff939641d5931183cf0ce0c5f01069808846deb9a36ce6938362a3a93cf5'}, '2021-11-04_024': {'PSNR': -3.812268018722534, 'MSE': 2.405618906021118, 'confusion_sha256': 'a8b78527c556e8551ddc88835976e688b1681a71f297b592801ae75ba8b110d7'}, '2021-11-04_042': {'PSNR': -5.1902174949646, 'MSE': 3.303861379623413, 'confusion_sha256': 'e1f5da754712f846b0b1d0f480986e1b55ff7955d543138551699f3905f2ae59'}, '2021-11-04_047': {'PSNR': -11.66427993774414, 'MSE': 14.669931411743164, 'confusion_sha256': '2c0acff73872e99170d9cf5b5a951a69d68762f0e9be522f04368a117ebc2211'}, '2021-11-04_049': {'PSNR': -15.672592163085938, 'MSE': 36.919795989990234, 'confusion_sha256': 'ed86060e37b1b4bdf0e0ba903ec0b396ec5fb7bed333a85f3bbcbf2fab5bbaa4'}, '2021-11-04_055': {'PSNR': 4.529160499572754, 'MSE': 0.3524389863014221, 'confusion_sha256': 'd1fdd99f09ffee5d8f85314f696f08b92b2775d670ee34eafa4c2c4e1fdf299d'}, '2021-11-04_061': {'PSNR': 0.5494163036346436, 'MSE': 0.8811672925949097, 'confusion_sha256': 'fcc297032a61e9dd0c93c84398cb0766b87a44b59950b22f1c53a20d8391c822'}, '2021-11-04_093': {'PSNR': 1.5230262279510498, 'MSE': 0.7042021751403809, 'confusion_sha256': '201ff6250ed202e11af64a04a933a4abefa26d3b7eec5e94bf1cf504f6c4e516'}, '2021-11-04_098': {'PSNR': -1.3938651084899902, 'MSE': 1.378435730934143, 'confusion_sha256': '7b6429241b13abd1a0db072fce898cc6e61eb3600af38093283fd1eb498fbcc2'}, '2021-11-05_010': {'PSNR': -4.2936272621154785, 'MSE': 2.6875884532928467, 'confusion_sha256': 'ccc2e21594932c2d84ae7f85e4f2b841b1ff2b8d18d9bb17489807d5449321d9'}, '2021-11-05_024': {'PSNR': 0.510915994644165, 'MSE': 0.8890135884284973, 'confusion_sha256': 'd0d86a855ead3fd164bb2a84237c955d3af545887db404b9276c02a499162aec'}, '2021-11-05_035': {'PSNR': 7.533391952514648, 'MSE': 0.17646588385105133, 'confusion_sha256': '82d345d93b7ba6970f2bcaa3c9288b7a519da0da6d4576f57efd17f5b46e32e6'}, '2021-11-05_041': {'PSNR': 1.2950642108917236, 'MSE': 0.7421532273292542, 'confusion_sha256': '3737be4f4b370c6ae02ab9dbb192ff2d250d5dbc48fa8f3cd4357dc27c25b860'}, '2021-11-05_046': {'PSNR': 8.538073539733887, 'MSE': 0.14002083241939545, 'confusion_sha256': 'da173b491f28cf66388db7c4ab2663d91cdc1283d4717da4d1f46018b9d239f9'}, '2021-11-10_014': {'PSNR': -30.209529876708984, 'MSE': 1049.4293212890625, 'confusion_sha256': 'bb6090713bece762a9c273606dd63e2afd2ed4d3e968206392c4fa9ceb59b44d'}, '2021-11-10_024': {'PSNR': -25.037992477416992, 'MSE': 319.0064392089844, 'confusion_sha256': 'dfea492ea7005f6b688487d4e6e39ee5073c03a686d3af80532535462d32b927'}, '2021-11-10_029': {'PSNR': -19.77103042602539, 'MSE': 94.86436462402344, 'confusion_sha256': '2840d205bb1e52c8a8d4568bac06a0b5fe2589b441421e8b84cafc2e50ab77f3'}, '2021-11-10_050': {'PSNR': -3.7158210277557373, 'MSE': 2.3527843952178955, 'confusion_sha256': '8dda4c1f03bd47e7ab1f633b9e405aac429b961b1286768604ef795c73beaa53'}}, 'plus1_alpha1': {'2021-11-03_046': {'PSNR': 39.93577194213867, 'MSE': 0.00010148985165869817, 'confusion_sha256': '14d73e1d988c3f12445ad7605030a4aae6d00bedfbcd0a2590e73ce6a51a9f86'}, '2021-11-03_047': {'PSNR': 38.74766540527344, 'MSE': 0.0001334237604169175, 'confusion_sha256': 'e33773f13e39c415c4a16615b47c307f9cb5a3f3a57527dbec2852c3949532c0'}, '2021-11-03_057': {'PSNR': 38.011871337890625, 'MSE': 0.00015805664588697255, 'confusion_sha256': 'f8d10f8c036a225b811d4c6163a0dacf823f541ced6875a3a73ee641e4de98d6'}, '2021-11-03_085': {'PSNR': 40.45233917236328, 'MSE': 9.010852227220312e-05, 'confusion_sha256': '29b10d98e58cd2f21f568b68b97469f820580e93f40ddf739b3d4dd72c5029f9'}, '2021-11-03_090': {'PSNR': 40.327449798583984, 'MSE': 9.273734031012282e-05, 'confusion_sha256': 'a30335633bde701a59bf9ab0ea2730a99f6ecf268b4ce149f5d12a23eaadb1a5'}, '2021-11-03_110': {'PSNR': 39.5364875793457, 'MSE': 0.00011126306344522163, 'confusion_sha256': '1ef25a4011bd2eb1aa8106f826fa5744da1540ee530ca2398a90e6bfaf120cc2'}, '2021-11-04_010': {'PSNR': 37.031429290771484, 'MSE': 0.0001980874949367717, 'confusion_sha256': '83ef051c01af9cc064d65b6bdb1a860ca41bfceac6c53e4ffa3d1f3899a43541'}, '2021-11-04_017': {'PSNR': 38.305030822753906, 'MSE': 0.00014773955626878887, 'confusion_sha256': '30fd19e55413ee336efde550a6d18744310dbac363ed0df36852443f0f7466fc'}, '2021-11-04_024': {'PSNR': 38.92214584350586, 'MSE': 0.00012816974776796997, 'confusion_sha256': '5117e1755188e0081172a6cabc50fe17f22ee83b1756e117a61eb18ab583899f'}, '2021-11-04_042': {'PSNR': 40.36432647705078, 'MSE': 9.195320308208466e-05, 'confusion_sha256': 'e811ffe794b72420cd8b4029771d035b29533fa1af2f3059be976693c1a27121'}, '2021-11-04_047': {'PSNR': 40.204830169677734, 'MSE': 9.5393079391215e-05, 'confusion_sha256': 'd9ce18ab865496e7b49ff3f44fc2baf2094b6ed47a63a9a7ba7becfa1da48aa7'}, '2021-11-04_049': {'PSNR': 40.76326370239258, 'MSE': 8.388292917516083e-05, 'confusion_sha256': '0739e78fdce2fd493a0ba10a70b17775e0f9e31c6c12f242f23f044dc02d053c'}, '2021-11-04_055': {'PSNR': 40.6777458190918, 'MSE': 8.555103704566136e-05, 'confusion_sha256': 'd114df89306eedf47535155128aa09f186d1af10d0311737d6c3df2b95f67762'}, '2021-11-04_061': {'PSNR': 40.669185638427734, 'MSE': 8.571981743443757e-05, 'confusion_sha256': '24a36c34d291e115447b406535a1dc828672e1b33910da5649dd8be417982bf6'}, '2021-11-04_093': {'PSNR': 39.108089447021484, 'MSE': 0.00012279787915758789, 'confusion_sha256': '7ffb0b314167f9997093033d1e058cc6b4eb1d7460017a7dd48134cbf9054f4c'}, '2021-11-04_098': {'PSNR': 39.419681549072266, 'MSE': 0.00011429621372371912, 'confusion_sha256': '7e4d06de321d1a215030015fb0901ec49f4ea36c1ab0e742961185696052e8d6'}, '2021-11-05_010': {'PSNR': 37.400718688964844, 'MSE': 0.00018193975847680122, 'confusion_sha256': '664274c7764a4ee9745f1e9512d3516202c6110b3b988d991867f67dcc3f9672'}, '2021-11-05_024': {'PSNR': 39.66768264770508, 'MSE': 0.0001079522626241669, 'confusion_sha256': '6d9b4a0bb4c0201e00b2e992f1c591ad95546b736c2cc170fd0e04f71b494331'}, '2021-11-05_035': {'PSNR': 38.80119323730469, 'MSE': 0.0001317894784733653, 'confusion_sha256': '7344af1615b33e4b2fc3dfe6aeb65a8356552888c70e5cb92ff02fbc59d35656'}, '2021-11-05_041': {'PSNR': 38.47829055786133, 'MSE': 0.00014196158736012876, 'confusion_sha256': '84e1cbc4065644afd3badaf58755d846956b9d3bc062694b9c274a35bc29b580'}, '2021-11-05_046': {'PSNR': 36.15117263793945, 'MSE': 0.0002425952407065779, 'confusion_sha256': 'f556d6048653f677f798897c43d20b1cf1ac1bf710d767c3889f12d3973c7a16'}, '2021-11-10_014': {'PSNR': 38.18336486816406, 'MSE': 0.00015193699800875038, 'confusion_sha256': '03c6ca79b8a384401a6f5295141949e807a064f09bbccbbbc75e960b5bb054ee'}, '2021-11-10_024': {'PSNR': 37.86553192138672, 'MSE': 0.00016347326163668185, 'confusion_sha256': 'fd4ff1567e9ea0800587d9a93417f44d2d3db92e93575c08e8ead678e01f902b'}, '2021-11-10_029': {'PSNR': 38.2700080871582, 'MSE': 0.00014893573825247586, 'confusion_sha256': '07c8908d21e62c73ba4b96e0ad6f2511bb20bc2b81df342f3278f649fdbd3911'}, '2021-11-10_050': {'PSNR': 37.33919143676758, 'MSE': 0.0001845357910497114, 'confusion_sha256': 'd60d3fcdb457c10e4e7f2a974e2ad732eb532cd422348f233bf2fe206b135c75'}}, 'minus1_alpha1': {'2021-11-03_046': {'PSNR': 39.77946090698242, 'MSE': 0.00010520912474021316, 'confusion_sha256': '001937a1365ad6cc97f4063edfc953d10e71ebb98931acdc77ea4a265c83e081'}, '2021-11-03_047': {'PSNR': 38.6917724609375, 'MSE': 0.00013515203318092972, 'confusion_sha256': '91462bb1d1c1b5cb20cde612023104ebef082c555a870907b728124682abf04f'}, '2021-11-03_057': {'PSNR': 38.02188491821289, 'MSE': 0.0001576926588313654, 'confusion_sha256': '03e698b21cdae41b5991210b5541e51fb417155991d248b5253f23154b751779'}, '2021-11-03_085': {'PSNR': 40.30281448364258, 'MSE': 9.326493454864249e-05, 'confusion_sha256': '14ac21f8bde27adfe23129111e8b9a0a9dbefb667fb1f8ec88996959689b3430'}, '2021-11-03_090': {'PSNR': 40.20442581176758, 'MSE': 9.540192695567384e-05, 'confusion_sha256': '4ab0686987aa4fe61cd6fe086733b30b50ffad78476190896b0b7e685be6794a'}, '2021-11-03_110': {'PSNR': 39.50486755371094, 'MSE': 0.0001120761371566914, 'confusion_sha256': 'd983700844c54998edbad82d50ff881a02f3fe4e649a801c94806f95288e3590'}, '2021-11-04_010': {'PSNR': 37.249549865722656, 'MSE': 0.00018838440882973373, 'confusion_sha256': '72125cc4e0945192590c0b6a6adf0ac0fa9d261db7638b41841182067083f089'}, '2021-11-04_017': {'PSNR': 38.4840087890625, 'MSE': 0.00014177474076859653, 'confusion_sha256': 'f54f0fbcd698b2e327094a26203cf96cc526816f804931dc45300714855664a1'}, '2021-11-04_024': {'PSNR': 38.65106201171875, 'MSE': 0.00013642494741361588, 'confusion_sha256': 'aaab1344b0b32c6579c30d2c1b9a2ab506e7070e64c095b01d067be589944cd2'}, '2021-11-04_042': {'PSNR': 40.1712532043457, 'MSE': 9.613343718228862e-05, 'confusion_sha256': 'ecf46b820c15b8fdbe7bc256638880c4da92226f62121ba3031b882c1cdbde0a'}, '2021-11-04_047': {'PSNR': 39.96493148803711, 'MSE': 0.00010081072832690552, 'confusion_sha256': '8c669512fa42a4202dc9a97013d6bbf57164d644455f868312baa26fb1700ffb'}, '2021-11-04_049': {'PSNR': 40.5753059387207, 'MSE': 8.759294723859057e-05, 'confusion_sha256': '2feaf15b7b4406276f7ea7f49196cc1351f5ce9903db5e60b1d61fc6289e6ce5'}, '2021-11-04_055': {'PSNR': 40.35194778442383, 'MSE': 9.221574146067724e-05, 'confusion_sha256': '8bb6db7eda58f13c124fae1ef3111040bf81bb235a3a2746542bd6a04ba19c08'}, '2021-11-04_061': {'PSNR': 40.27669143676758, 'MSE': 9.382760617882013e-05, 'confusion_sha256': '04a6dbca8d073ee68a2b42cfaf7fde08bde3585280818899137956d8a52ad4bf'}, '2021-11-04_093': {'PSNR': 39.054813385009766, 'MSE': 0.00012431357754394412, 'confusion_sha256': 'bc72c1334fe11b01342d256c1caeccbc0fa9acf89bdeab81108c33acb00ef82e'}, '2021-11-04_098': {'PSNR': 39.23973083496094, 'MSE': 0.000119131596875377, 'confusion_sha256': '971f9c205a4edd1e94411287906ea9dedc16bff36849a5036def85eee51a85d7'}, '2021-11-05_010': {'PSNR': 37.39585494995117, 'MSE': 0.00018214374722447246, 'confusion_sha256': 'ce54101d30622f3dae17ff86bf51e114a9c8e97ccdd966cb96e88e15f6832673'}, '2021-11-05_024': {'PSNR': 39.5966682434082, 'MSE': 0.00010973198368446901, 'confusion_sha256': 'b6ad1cf047c843b02bb6ec8a4fc7471e361ae6e60af873d187f7232aeaeec4fc'}, '2021-11-05_035': {'PSNR': 38.71174240112305, 'MSE': 0.00013453203428070992, 'confusion_sha256': 'fe0a70b0902d6cfe063291a591a75d5d512a1b3e5debec7640de6390e82d4bd9'}, '2021-11-05_041': {'PSNR': 38.43107223510742, 'MSE': 0.00014351338904816657, 'confusion_sha256': '8f64b2f835cd99af39a2c8ff765294f524561c63d7b1d7bff04cedfc0a8d40f5'}, '2021-11-05_046': {'PSNR': 36.058353424072266, 'MSE': 0.00024783617118373513, 'confusion_sha256': '19479ea65b8906b463fa586dd42da26cc470b62b521d767df06e822796e5f689'}, '2021-11-10_014': {'PSNR': 38.06553649902344, 'MSE': 0.00015611555136274546, 'confusion_sha256': '184a55cb0afb8576ba2905207ba66ac33681b36d14b5cef518e23359fe94faf7'}, '2021-11-10_024': {'PSNR': 37.631168365478516, 'MSE': 0.00017253738769795746, 'confusion_sha256': '25267115d55c6313a161747f9f83e562b8f251bfec0f28409bbf9720f3d28a71'}, '2021-11-10_029': {'PSNR': 38.259586334228516, 'MSE': 0.00014929348253645003, 'confusion_sha256': '8435416170e7932b77ebd421892a69ef0d8e9aeee4e601e17f00475e4b46a569'}, '2021-11-10_050': {'PSNR': 37.57216262817383, 'MSE': 0.00017489738820586354, 'confusion_sha256': '8b3b7203ff04ebcd9a8a43adfd841cd6fc614ba8b696ecd21361a0148e2f06a8'}}}}

RUN=WORK/('gain_bound_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
for filename,source in FILES.items():(RUN/filename).write_text(source)
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'expected.json').write_text(json.dumps(EXPECTED,indent=2))
(RUN/'source_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in ['models/CRSDUN.py','dataset.py','utils.py','public252-v1.json']},indent=2))
with (RUN/'local_checks.log').open('w') as log:
    result=subprocess.run([sys.executable,str(RUN/'verify_gain_guard.py'),'--code',str(CODE)],cwd=RUN,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    log.write(result.stdout);print(result.stdout)
    result.check_returncode()
print('Output folder:',RUN)

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
PASS: isolated residual multiplier in[0,1] including zero physical energy; actual five-stage disabled/inactive bitwise identity; negative-offset activation on binary and fractional masks; gain<=1; Observer compatibility and cleanup. No whole-network stability or trained-checkpoint efficacy claim.

Output folder: /kaggle/working/gain_bound_epoch441_20261011_093437_032153

In [7]:
from IPython.display import display,FileLink
try:
    with (RUN/'console.log').open('w') as log:
        command=[sys.executable,'-u',str(RUN/'gain_experiment.py'),
                 '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
                 '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json'),'--expected',str(RUN/'expected.json')]
        proc=subprocess.Popen(command,cwd=CODE,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)
        try:
            for line in proc.stdout:
                print(line,end='',flush=True)
                log.write(line);log.flush()
            code=proc.wait()
            if code: raise subprocess.CalledProcessError(code,command)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try: proc.wait(timeout=10)
                except subprocess.TimeoutExpired: proc.kill();proc.wait()
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
clean: 1/25 paired; 0.3min
clean: 2/25 paired; 0.5min
clean: 3/25 paired; 0.7min
clean: 4/25 paired; 0.9min
clean: 5/25 paired; 1.2min
clean: 6/25 paired; 1.4min
clean: 7/25 paired; 1.6min
clean: 8/25 paired; 1.8min
clean: 9/25 paired; 2.0min
clean: 10/25 paired; 2.2min
clean: 11/25 paired; 2.4min
clean: 12/25 paired; 2.7min
clean: 13/25 paired; 2.9min
clean: 14/25 paired; 3.1min
clean: 15/25 paired; 3.3min
clean: 16/25 paired; 3.5min
clean: 17/25 paired; 3.7min
clean: 18/25 paired; 4.0min
clean: 19/25 paired; 4.2min
clean: 20/25 paired; 4.4min
clean: 21/25 paired; 4.6min
clean: 22/25 paired; 4.8min
clean: 23/25 paired; 5.0min
clean: 24/25 paired; 5.3min
clean: 25/25 paired; 5.5min
plus1_alpha1: 1/25 paired; 5.7min
plus1_alpha1: 2/25 paired; 5.9min
plus1_alpha1: 3/25 paired; 6.1min
plus1_alpha1: 4/25 paired; 6.3min
plus1_alpha1: 5/25 paired; 6.6min
plus1_alpha1: 6/25 paired; 6.8min
plus1_alpha1: 7/25 paired; 7.0min
plus1_alpha1: 8/25 paired; 7.2min
plus1_alpha1: 9/25 paired; 7.4min
plus1_alpha1: 10/25 paired; 7.6min
plus1_alpha1: 11/25 paired; 7.9min
plus1_alpha1: 12/25 paired; 8.1min
plus1_alpha1: 13/25 paired; 8.3min
plus1_alpha1: 14/25 paired; 8.5min
plus1_alpha1: 15/25 paired; 8.7min
plus1_alpha1: 16/25 paired; 8.9min
plus1_alpha1: 17/25 paired; 9.2min
plus1_alpha1: 18/25 paired; 9.4min
plus1_alpha1: 19/25 paired; 9.6min
plus1_alpha1: 20/25 paired; 9.8min
plus1_alpha1: 21/25 paired; 10.0min
plus1_alpha1: 22/25 paired; 10.2min
plus1_alpha1: 23/25 paired; 10.5min
plus1_alpha1: 24/25 paired; 10.7min
plus1_alpha1: 25/25 paired; 10.9min
minus1_alpha1: 1/25 paired; 11.1min
minus1_alpha1: 2/25 paired; 11.3min
minus1_alpha1: 3/25 paired; 11.6min
minus1_alpha1: 4/25 paired; 11.8min
minus1_alpha1: 5/25 paired; 12.0min
minus1_alpha1: 6/25 paired; 12.2min
minus1_alpha1: 7/25 paired; 12.4min
minus1_alpha1: 8/25 paired; 12.6min
minus1_alpha1: 9/25 paired; 12.9min
minus1_alpha1: 10/25 paired; 13.1min
minus1_alpha1: 11/25 paired; 13.3min
minus1_alpha1: 12/25 paired; 13.5min
minus1_alpha1: 13/25 paired; 13.7min
minus1_alpha1: 14/25 paired; 14.0min
minus1_alpha1: 15/25 paired; 14.2min
minus1_alpha1: 16/25 paired; 14.4min
minus1_alpha1: 17/25 paired; 14.6min
minus1_alpha1: 18/25 paired; 14.8min
minus1_alpha1: 19/25 paired; 15.0min
minus1_alpha1: 20/25 paired; 15.3min
minus1_alpha1: 21/25 paired; 15.5min
minus1_alpha1: 22/25 paired; 15.7min
minus1_alpha1: 23/25 paired; 15.9min
minus1_alpha1: 24/25 paired; 16.1min
minus1_alpha1: 25/25 paired; 16.4min
plus1_alpha0.1: 1/25 paired; 16.6min
plus1_alpha0.1: 2/25 paired; 16.8min
plus1_alpha0.1: 3/25 paired; 17.0min
plus1_alpha0.1: 4/25 paired; 17.2min
plus1_alpha0.1: 5/25 paired; 17.4min
plus1_alpha0.1: 6/25 paired; 17.7min
plus1_alpha0.1: 7/25 paired; 17.9min
plus1_alpha0.1: 8/25 paired; 18.1min
plus1_alpha0.1: 9/25 paired; 18.3min
plus1_alpha0.1: 10/25 paired; 18.5min
plus1_alpha0.1: 11/25 paired; 18.7min
plus1_alpha0.1: 12/25 paired; 19.0min
plus1_alpha0.1: 13/25 paired; 19.2min
plus1_alpha0.1: 14/25 paired; 19.4min
plus1_alpha0.1: 15/25 paired; 19.6min
plus1_alpha0.1: 16/25 paired; 19.8min
plus1_alpha0.1: 17/25 paired; 20.1min
plus1_alpha0.1: 18/25 paired; 20.3min
plus1_alpha0.1: 19/25 paired; 20.5min
plus1_alpha0.1: 20/25 paired; 20.7min
plus1_alpha0.1: 21/25 paired; 20.9min
plus1_alpha0.1: 22/25 paired; 21.1min
plus1_alpha0.1: 23/25 paired; 21.4min
plus1_alpha0.1: 24/25 paired; 21.6min
plus1_alpha0.1: 25/25 paired; 21.8min
minus1_alpha0.1: 1/25 paired; 22.0min
minus1_alpha0.1: 2/25 paired; 22.2min
minus1_alpha0.1: 3/25 paired; 22.4min
minus1_alpha0.1: 4/25 paired; 22.7min
minus1_alpha0.1: 5/25 paired; 22.9min
minus1_alpha0.1: 6/25 paired; 23.1min
minus1_alpha0.1: 7/25 paired; 23.3min
minus1_alpha0.1: 8/25 paired; 23.5min
minus1_alpha0.1: 9/25 paired; 23.7min
minus1_alpha0.1: 10/25 paired; 24.0min
minus1_alpha0.1: 11/25 paired; 24.2min
minus1_alpha0.1: 12/25 paired; 24.4min
minus1_alpha0.1: 13/25 paired; 24.6min
minus1_alpha0.1: 14/25 paired; 24.8min
minus1_alpha0.1: 15/25 paired; 25.1min
minus1_alpha0.1: 16/25 paired; 25.3min
minus1_alpha0.1: 17/25 paired; 25.5min
minus1_alpha0.1: 18/25 paired; 25.7min
minus1_alpha0.1: 19/25 paired; 25.9min
minus1_alpha0.1: 20/25 paired; 26.1min
minus1_alpha0.1: 21/25 paired; 26.3min
minus1_alpha0.1: 22/25 paired; 26.6min
minus1_alpha0.1: 23/25 paired; 26.8min
minus1_alpha0.1: 24/25 paired; 27.0min
minus1_alpha0.1: 25/25 paired; 27.2min
plus1_alpha0.25: 1/25 paired; 27.4min
plus1_alpha0.25: 2/25 paired; 27.6min
plus1_alpha0.25: 3/25 paired; 27.9min
plus1_alpha0.25: 4/25 paired; 28.1min
plus1_alpha0.25: 5/25 paired; 28.3min
plus1_alpha0.25: 6/25 paired; 28.5min
plus1_alpha0.25: 7/25 paired; 28.7min
plus1_alpha0.25: 8/25 paired; 28.9min
plus1_alpha0.25: 9/25 paired; 29.2min
plus1_alpha0.25: 10/25 paired; 29.4min
plus1_alpha0.25: 11/25 paired; 29.6min
plus1_alpha0.25: 12/25 paired; 29.8min
plus1_alpha0.25: 13/25 paired; 30.0min
plus1_alpha0.25: 14/25 paired; 30.2min
plus1_alpha0.25: 15/25 paired; 30.5min
plus1_alpha0.25: 16/25 paired; 30.7min
plus1_alpha0.25: 17/25 paired; 30.9min
plus1_alpha0.25: 18/25 paired; 31.1min
plus1_alpha0.25: 19/25 paired; 31.3min
plus1_alpha0.25: 20/25 paired; 31.5min
plus1_alpha0.25: 21/25 paired; 31.8min
plus1_alpha0.25: 22/25 paired; 32.0min
plus1_alpha0.25: 23/25 paired; 32.2min
plus1_alpha0.25: 24/25 paired; 32.4min
plus1_alpha0.25: 25/25 paired; 32.6min
minus1_alpha0.25: 1/25 paired; 32.8min
minus1_alpha0.25: 2/25 paired; 33.0min
minus1_alpha0.25: 3/25 paired; 33.3min
minus1_alpha0.25: 4/25 paired; 33.5min
minus1_alpha0.25: 5/25 paired; 33.7min
minus1_alpha0.25: 6/25 paired; 33.9min
minus1_alpha0.25: 7/25 paired; 34.1min
minus1_alpha0.25: 8/25 paired; 34.3min
minus1_alpha0.25: 9/25 paired; 34.5min
minus1_alpha0.25: 10/25 paired; 34.8min
minus1_alpha0.25: 11/25 paired; 35.0min
minus1_alpha0.25: 12/25 paired; 35.2min
minus1_alpha0.25: 13/25 paired; 35.4min
minus1_alpha0.25: 14/25 paired; 35.6min
minus1_alpha0.25: 15/25 paired; 35.8min
minus1_alpha0.25: 16/25 paired; 36.0min
minus1_alpha0.25: 17/25 paired; 36.3min
minus1_alpha0.25: 18/25 paired; 36.5min
minus1_alpha0.25: 19/25 paired; 36.7min
minus1_alpha0.25: 20/25 paired; 36.9min
minus1_alpha0.25: 21/25 paired; 37.1min
minus1_alpha0.25: 22/25 paired; 37.3min
minus1_alpha0.25: 23/25 paired; 37.6min
minus1_alpha0.25: 24/25 paired; 37.8min
minus1_alpha0.25: 25/25 paired; 38.0min
       condition  control_miou_percent  guarded_miou_percent  miou_change_points  control_psnr  guarded_psnr  psnr_change  control_mse  guarded_mse
           clean             78.768371             78.874989            0.106619     39.006846     39.087124     0.080278     0.000131     0.000129
    plus1_alpha1             78.308001             78.391737            0.083736     38.985379     39.056940     0.071561     0.000132     0.000130
   minus1_alpha1             78.207776             78.356045            0.148269     38.889867     39.045544     0.155677     0.000134     0.000130
  plus1_alpha0.1             78.040719             78.039142           -0.001577     38.480462     38.827576     0.347113     0.000147     0.000137
 minus1_alpha0.1             78.062349             78.056459           -0.005890     38.410596     38.822663     0.412067     0.000149     0.000137
 plus1_alpha0.25             70.998186             76.049079            5.050893     -5.109314     37.931152    43.040466    83.815243     0.000169
minus1_alpha0.25             70.331652             76.055494            5.723842     -5.086849     37.903252    42.990100    65.109760     0.000170
Download this ZIP even if an error occurred: gain_bound_epoch441_20261011_093437_032153.zip

/kaggle/working/gain_bound_epoch441_20261011_093437_032153.zip

In [8]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed','Partial run: share the ZIP and error.'
assert manifest['completed_pairs']==175 and manifest['model_state_unchanged']
checks=pd.read_json(RUN/'results/pair_checks.json');assert len(checks)==175
assert checks[checks['inactive']]['all_stage_outputs_identical'].all()
display(pd.read_csv(RUN/'results/paired_summary.csv'))
display(checks.groupby('condition').agg(total_activated=('activated','sum'),identical_pairs=('all_stage_outputs_identical','sum')))
print('Completed. Download gain_bound_epoch441 ZIP and share its local path. Evaluate clean and segmentation tradeoffs alongside reconstruction recovery; completion does not establish that this method works.')

,condition,control_miou_percent,guarded_miou_percent,miou_change_points,control_psnr,guarded_psnr,psnr_change,control_mse,guarded_mse
0,clean,78.768371,78.874989,0.106619,39.006846,39.087124,0.080278,0.000131,0.000129
1,plus1_alpha1,78.308001,78.391737,0.083736,38.985379,39.056940,0.071561,0.000132,0.000130
2,minus1_alpha1,78.207776,78.356045,0.148269,38.889867,39.045544,0.155677,0.000134,0.000130
3,plus1_alpha0.1,78.040719,78.039142,-0.001577,38.480462,38.827576,0.347113,0.000147,0.000137
4,minus1_alpha0.1,78.062349,78.056459,-0.005890,38.410596,38.822663,0.412067,0.000149,0.000137
5,plus1_alpha0.25,70.998186,76.049079,5.050893,-5.109314,37.931152,43.040466,83.815243,0.000169
6,minus1_alpha0.25,70.331652,76.055494,5.723842,-5.086849,37.903252,42.990100,65.109760,0.000170

                  total_activated  identical_pairs
condition
clean                    28979200                0
minus1_alpha0.1          28979200                0
minus1_alpha0.25         28979200                0
minus1_alpha1            28979200                0
plus1_alpha0.1           28979200                0
plus1_alpha0.25          28979200                0
plus1_alpha1             28979200                0

Completed. Download gain_bound_epoch441 ZIP and share its local path. Evaluate clean and segmentation tradeoffs alongside reconstruction recovery; completion does not establish that this method works.

In [1]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch441 weights: /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth

In [2]:
FILES={'operator_control.py': '"""Frozen validation: paired nominal/matched operators under synthetic mask mixing."""\nfrom pathlib import Path\nimport argparse\nimport hashlib\nimport json\nimport time\nimport numpy as np\nimport torch\n\nALPHAS = (0.05, 0.10, 0.25, 1.0)\n\ndef sha(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\ndef tensor_sha(x):\n    return hashlib.sha256(x.detach().cpu().contiguous().numpy().tobytes()).hexdigest()\n\ndef mix_mask(mask, dx, alpha):\n    assert mask.ndim == 2 and dx in (-1, 1) and 0 <= alpha <= 1\n    shifted = torch.zeros_like(mask)\n    if dx == 1:\n        shifted[:, 1:] = mask[:, :-1]\n    else:\n        shifted[:, :-1] = mask[:, 1:]\n    return (1-alpha)*mask + alpha*shifted\n\ndef make_operator(mask, bands=28, step=2):\n    h, w = mask.shape\n    phi = mask.new_zeros((1, bands, h, w+(bands-1)*step))\n    for c in range(bands):\n        phi[0, c, :, step*c:step*c+w] = mask\n    back = torch.stack([phi[:, c, :, step*c:step*c+w] for c in range(bands)], dim=1)\n    energy = phi.square().sum(1, keepdim=True)\n    energy = torch.where(energy == 0, torch.ones_like(energy), energy)\n    return back, phi, energy\n\ndef measure(x, phi, step=2):\n    b, c, h, w = x.shape\n    y = x.new_zeros((b, h, phi.shape[-1]))\n    for k in range(c):\n        y[:, :, step*k:step*k+w] += x[:, k]*phi[:, k, :, step*k:step*k+w]\n    return y\n\ndef relative_error(a, b):\n    return float(torch.linalg.vector_norm(a-b)/torch.linalg.vector_norm(b).clamp_min(1e-12))\n\ndef main():\n    import sys\n    p = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\'):\n        p.add_argument(\'--\'+key, type=Path, required=True)\n    a = p.parse_args()\n    sys.path.insert(0, str(a.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, shift_back_mask, Metrics_Rec, Metrics_Seg, set_seed\n    from run_public252 import validate\n\n    ref = json.loads(a.reference.read_text())\n    mask_path = a.code/\'mask/mask512x512.mat\'\n    assert sha(a.checkpoint) == ref[\'checkpoint_sha256\']\n    assert sha(mask_path) == ref[\'mask_sha256\']\n    assert sha(a.code/\'public252-v1.json\') == ref[\'protocol_sha256\']\n    validate(a.data, json.loads((a.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(exist_ok=False, parents=True)\n    set_seed(3407)\n    loader = evaluation_loader(a.data, \'val\', 0, True)\n    scenes = list(map(str, loader.dataset.names))\n    assert sorted(scenes) == sorted(ref[\'scenes\']) and len(scenes) == 25\n    model = model_generator(\'CRSDUN\', 28, 23, str(a.checkpoint))\n    model.eval()\n    physical = torch.as_tensor(loadmat(mask_path)[\'mask\'], dtype=torch.float32, device=\'cuda\')\n    phi, nominal = init_mask(str(mask_path), \'SSR\', 1, 28)\n    built = make_operator(physical)\n    assert all(torch.equal(x, y) for x, y in zip(built, nominal)), \'Nominal SSR tuple differs\'\n    assert all(torch.equal(x, y) for x, y in zip(make_operator(mix_mask(physical, 1, 0)), nominal))\n    nominal_hashes = [tensor_sha(x) for x in nominal]\n    conditions = [(\'clean\', 0, 0.0)] + [(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\', dx, alpha) for alpha in ALPHAS for dx in (1, -1)]\n    manifest = dict(status=\'running\', checkpoint_epoch=441, checkpoint_sha256=sha(a.checkpoint),\n                    protocol_sha256=ref[\'protocol_sha256\'], mask_sha256=sha(mask_path),\n                    script_sha256=sha(__file__), scenes=scenes, alphas=list(ALPHAS),\n                    conditions=conditions, completed_conditions=[], torch=str(torch.__version__),\n                    gpu=torch.cuda.get_device_name(0), expected_model_forwards=425,\n                    test_evaluated=False, training=False,\n                    scope=\'25 validation scenes; frozen model; identical measurement reused for nominal and matched full SSR tuples.\',\n                    caveat=\'Linear mask mixing with a zero-filled +/-1px shift is synthetic, not calibrated hardware motion. Matched masks may still be outside the training distribution.\',\n                    metrics=\'Every-stage confusion/MSE/PSNR_ref1; SSIM_ref1 final stage only. Scene-averaged reconstruction metrics; aggregate confusion mIoU.\')\n    manifest_path = a.out/\'experiment.json\'\n    def save_manifest():\n        manifest_path.write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    summary, severity_rows = [], []\n    started = time.time()\n    try:\n      with torch.inference_mode():\n        for name, dx, alpha in conditions:\n            folder = a.out/name\n            folder.mkdir()\n            mixed = physical if name == \'clean\' else mix_mask(physical, dx, alpha)\n            matched = make_operator(mixed)\n            acquisition = matched[1]\n            assert torch.equal(matched[0], shift_back_mask(acquisition))\n            expected_energy = acquisition.square().sum(1, keepdim=True)\n            expected_energy[expected_energy == 0] = 1\n            assert torch.equal(matched[2], expected_energy)\n            paired_ops = [(\'nominal\', nominal)] if name == \'clean\' else [(\'nominal\', nominal), (\'matched\', matched)]\n            severity_rows.append(dict(condition=name, dx=dx, alpha=alpha,\n                                      mask_relative_error=relative_error(mixed, physical),\n                                      changed_fraction=float((mixed != physical).float().mean()),\n                                      mean_transmittance=float(mixed.mean())))\n            pd.DataFrame(severity_rows).to_csv(a.out/\'mask_severity.csv\', index=False)\n            seg = {mode: [Metrics_Seg(23, get_class_names()) for _ in range(5)] for mode, _ in paired_ops}\n            records = []\n            for index, sample in enumerate(loader):\n                scene = scenes[index]\n                target = sample[\'image\'].float().cuda()\n                gt_cpu = target.cpu()\n                truth = sample[\'label\'].numpy()[0]\n                y = init_meas(target, acquisition, \'Y\')\n                if index == 0:\n                    assert torch.allclose(measure(target, acquisition), y, atol=1e-6, rtol=1e-6)\n                y_nominal = init_meas(target, phi, \'Y\')\n                measurement_error = relative_error(y, y_nominal)\n                y_digest = tensor_sha(y)\n                for mode, operator in paired_ops:\n                    op_hashes = [tensor_sha(x) for x in operator]\n                    xs, logits = model(y, operator)\n                    assert len(xs) == len(logits) == 5\n                    for k, (x, logit) in enumerate(zip(xs, logits), 1):\n                        assert x.shape == target.shape and logit.shape == (1, 23, *truth.shape)\n                        assert torch.isfinite(x).all() and torch.isfinite(logit).all(), f\'Nonfinite: {name}/{mode}/{scene}/stage{k}\'\n                        x_cpu = x.float().cpu()\n                        pred = logit.argmax(1).cpu().numpy()[0]\n                        hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                        np.save(folder/f\'{mode}_{scene}_stage{k}_confusion.npy\', hist)\n                        seg[mode][k-1].add_batch(truth[None], pred[None])\n                        mse = float((x_cpu-gt_cpu).square().mean())\n                        metrics = {\'MSE\':mse, \'PSNR\':float(-10*torch.log10(torch.tensor(mse))), \'SSIM\':None}\n                        if k == 5:\n                            rec = Metrics_Rec()\n                            rec.add_batch(gt_cpu, x_cpu)\n                            metrics = rec.get_table().iloc[0].to_dict()\n                        records.append(dict(condition=name, mode=mode, scene=scene, stage=k,\n                                            dx=dx, alpha=alpha, measurement_sha256=y_digest,\n                                            measurement_relative_error=measurement_error, **metrics))\n                    assert tensor_sha(y) == y_digest, \'Measurement mutated during inference\'\n                    assert [tensor_sha(t) for t in operator] == op_hashes, \'SSR tuple mutated\'\n                    del xs, logits, x, logit, x_cpu\n                pd.DataFrame(records).to_csv(folder/\'per_scene_stage_metrics.csv\', index=False)\n                del target, gt_cpu, y, y_nominal\n                print(f\'{name}: {index+1}/25; modes={len(paired_ops)}; elapsed={(time.time()-started)/60:.1f}min\', flush=True)\n            assert [tensor_sha(t) for t in nominal] == nominal_hashes\n            for mode, _ in paired_ops:\n                for k in range(1,6):\n                    acc = seg[mode][k-1]\n                    assert np.array_equal(sum(np.load(folder/f\'{mode}_{s}_stage{k}_confusion.npy\') for s in scenes), acc.confusion_matrix)\n                    np.save(folder/f\'{mode}_stage{k}_aggregate_confusion.npy\', acc.confusion_matrix)\n                    table = acc.get_table()\n                    table.to_csv(folder/f\'{mode}_stage{k}_segmentation.csv\')\n                    items = [r for r in records if r[\'mode\'] == mode and r[\'stage\'] == k]\n                    summary.append(dict(condition=name, mode=mode, stage=k, alpha=alpha, dx=dx,\n                                        foreground_miou_all22=float(table.loc[\'total(-bg)\', \'IoU\']),\n                                        PSNR=float(np.mean([r[\'PSNR\'] for r in items])),\n                                        MSE=float(np.mean([r[\'MSE\'] for r in items])),\n                                        SSIM=float(np.mean([r[\'SSIM\'] for r in items])) if k == 5 else None))\n            pd.DataFrame(summary).to_csv(a.out/\'stage_summary.csv\', index=False)\n            if name == \'clean\':\n                final = summary[-1]\n                check = dict(miou_difference=final[\'foreground_miou_all22\']-ref[\'miou\'], psnr_difference=final[\'PSNR\']-ref[\'psnr\'])\n                check[\'passed\'] = abs(check[\'miou_difference\']) < 1e-6 and abs(check[\'psnr_difference\']) < 1e-4\n                (a.out/\'clean_equivalence.json\').write_text(json.dumps(check, indent=2))\n                assert check[\'passed\'], \'Clean check failed; stopping before stresses\'\n            manifest[\'completed_conditions\'].append(name)\n            save_manifest()\n        pairs = []\n        for name, dx, alpha in conditions[1:]:\n            n, m = [next(r for r in summary if r[\'condition\']==name and r[\'mode\']==mode and r[\'stage\']==5) for mode in (\'nominal\', \'matched\')]\n            pairs.append(dict(condition=name, dx=dx, alpha=alpha,\n                              nominal_miou_percent=100*n[\'foreground_miou_all22\'], matched_miou_percent=100*m[\'foreground_miou_all22\'],\n                              matched_minus_nominal_miou_points=100*(m[\'foreground_miou_all22\']-n[\'foreground_miou_all22\']),\n                              nominal_psnr=n[\'PSNR\'], matched_psnr=m[\'PSNR\'], matched_minus_nominal_psnr=m[\'PSNR\']-n[\'PSNR\']))\n        pd.DataFrame(pairs).to_csv(a.out/\'paired_final_summary.csv\', index=False)\n        manifest[\'status\'] = \'completed\'\n        print(pd.DataFrame(pairs).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest[\'status\'] = \'failed\'\n        manifest[\'error\'] = repr(exc)\n        raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started\n        save_manifest()\n\nif __name__ == \'__main__\':\n    main()\n', 'numerical_trace.py': '"""Observe frozen CRSDUN through hooks; require exact traced/untraced outputs."""\nimport argparse, json, sys, time\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom operator_control import make_operator, mix_mask, sha, tensor_sha\n\ndef stats(x):\n    a=x.detach().cpu().double().numpy()\n    assert np.isfinite(a).all(), \'Nonfinite tensor in trace\'\n    return dict(min=float(a.min()),max=float(a.max()),rms=float(np.sqrt(np.mean(a*a))),max_abs=float(np.abs(a).max()))\n\ndef denominator_stats(d):\n    r=stats(d); a=d.detach().cpu().double().numpy()\n    r.update(min_abs=float(np.abs(a).min()),min_abs_index=[int(i) for i in np.unravel_index(np.abs(a).argmin(),a.shape)],nonpositive=int((a<=0).sum()),elements=int(a.size))\n    for limit in (1e-6,1e-4,1e-2,.1):r[f\'abs_below_{limit:g}\']=int((np.abs(a)<limit).sum())\n    return r\n\ndef spatial_error(x, target, aligned_energy):\n    delta=x.detach().cpu().double().numpy()-target\n    sq=delta[0]**2\n    h,w=sq.shape[-2:]\n    border=np.ones((h,w),dtype=bool)\n    border[16:-16,16:-16]=False\n    regions={\'image_border16\':np.broadcast_to(border,sq.shape),\'image_interior\':np.broadcast_to(~border,sq.shape)}\n    regions.update({\'energy_zero\':aligned_energy==0,\'energy_0_to_0.1\':(aligned_energy>0)&(aligned_energy<=.1),\n                    \'energy_0.1_to_1\':(aligned_energy>.1)&(aligned_energy<=1),\n                    \'energy_1_to_4\':(aligned_energy>1)&(aligned_energy<=4),\'energy_above4\':aligned_energy>4})\n    total=float(sq.sum()); result={}\n    for name,mask in regions.items():\n        n=int(mask.sum()); s=float(sq[mask].sum())\n        result[name]=dict(voxels=n,squared_error_sum=s,mse=s/n if n else None,fraction_total_error=s/total if total else 0.)\n    return dict(mse=float(sq.mean()),total_squared_error=total,regions=result)\n\nclass Observer:\n    def __init__(self,model,operator,target,emit,measurement=None):\n        self.model=model;self.operator=operator;self.target=target.detach().cpu().double().numpy();self.emit=emit\n        self.stage=0;self.handles=[];self.original_phif=model.mul_Phif;self.original_phit=model.mul_PhiTg\n        self.measurement=measurement\n        self.had_phif=\'mul_Phif\' in model.__dict__;self.had_phit=\'mul_PhiTg\' in model.__dict__\n        _,bands,h,w=target.shape\n        raw=operator[1].square().sum(1)[0]\n        self.aligned_energy=torch.stack([raw[:,2*c:2*c+w] for c in range(bands)]).cpu().numpy()\n\n    def record(self,event,x,error=False,**extra):\n        row=dict(stage=self.stage,event=event,values=stats(x),**extra)\n        if error:row[\'reconstruction_error\']=spatial_error(x,self.target,self.aligned_energy)\n        self.emit(row)\n\n    def __enter__(self):\n        def para_hook(module,args,out):\n            self.stage+=1\n            p=out.detach().cpu().flatten().tolist()\n            assert len(p)==4\n            self.emit(dict(stage=self.stage,event=\'parameters\',a=p[0],mu=p[1],b=p[2],gamma=p[3],\n                           denominator=denominator_stats(self.operator[2]+out[:,0:1])))\n        def phif(phi,x):\n            self.record(\'x_new_before_data_consistency\',x,error=True)\n            result=self.original_phif(phi,x)\n            self.record(\'predicted_measurement\',result)\n            if self.measurement is not None:self.record(\'measurement_residual\',self.measurement.unsqueeze(1)-result)\n            return result\n        def phit(phi,g):\n            self.record(\'residual_divided_by_denominator\',g)\n            result=self.original_phit(phi,g)\n            self.record(\'data_consistency_correction\',result)\n            return result\n        self.model.mul_Phif=phif;self.model.mul_PhiTg=phit\n        for module in self.model.para_est:self.handles.append(module.register_forward_hook(para_hook))\n        for k in range(self.model.stage):\n            self.handles.append(self.model.net_stage[3*k].register_forward_pre_hook(lambda m,args:self.record(\'z_before_reconstruction_attention\',args[0],error=True)))\n            self.handles.append(self.model.net_stage[3*k].register_forward_hook(lambda m,args,out:self.record(\'after_reconstruction_attention\',out,error=True)))\n            self.handles.append(self.model.net_stage[3*k+1].register_forward_hook(lambda m,args,out:self.record(\'after_refinement\',out,error=True)))\n        return self\n\n    def __exit__(self,*exc):\n        for h in self.handles:h.remove()\n        if self.had_phif:self.model.mul_Phif=self.original_phif\n        else:del self.model.mul_Phif\n        if self.had_phit:self.model.mul_PhiTg=self.original_phit\n        else:del self.model.mul_PhiTg\n\ndef main():\n    p=argparse.ArgumentParser()\n    for name in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+name,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    from scipy.io import loadmat\n    import pandas as pd\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    conditions=[(\'clean\',0,0.)]+[(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\',dx,alpha) for alpha in (.1,.25,1.) for dx in (1,-1)]\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],mask_sha256=ref[\'mask_sha256\'],script_sha256=sha(__file__),helper_sha256=sha(Path(__file__).with_name(\'operator_control.py\')),scenes=scenes,conditions=conditions,completed_conditions=[],completed_identity_pairs=0,training=False,test_evaluated=False,expected_forwards=350,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'Matched operators only. Every traced forward paired with an uninstrumented forward; all five reconstruction/logit tensors must hash identically. Regions are image-border16 and raw detector-energy bins aligned to each spectral voxel, not calibrated hardware regions.\')\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];scene_metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha in conditions:\n            operator=make_operator(mask if not dx else mix_mask(mask,dx,alpha))\n            op_hash=[tensor_sha(t) for t in operator]\n            accumulator=Metrics_Seg(23,get_class_names());rec=Metrics_Rec()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                y=init_meas(target,operator[1],\'Y\');yh=tensor_sha(y)\n                xs,ls=model(y,operator)\n                baseline=[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n                def emit(row):\n                    f.write(json.dumps(dict(condition=name,scene=scene,**row),allow_nan=False)+\'\\n\')\n                with Observer(model,operator,target,emit,measurement=y) as observer:xs,ls=model(y,operator)\n                f.flush()\n                assert observer.stage==5\n                equal=baseline==[tensor_sha(t) for t in [*xs,*ls]]\n                checks.append(dict(condition=name,scene=scene,all_stage_tensors_bitwise_identical=equal))\n                (args.out/\'identity_checks.json\').write_text(json.dumps(checks,indent=2))\n                assert equal,\'Instrumentation altered predictions\'\n                assert tensor_sha(y)==yh and [tensor_sha(t) for t in operator]==op_hash\n                one=Metrics_Rec();one.add_batch(target.cpu(),xs[-1].cpu())\n                metric=one.get_table().iloc[0].to_dict()\n                e=expected[\'scenes\'][name][scene]\n                assert abs(metric[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(metric[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Prior scene metrics not reproduced\'\n                for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec,field,getattr(rec,field)+getattr(one,field))\n                pred=ls[-1].argmax(1).cpu().numpy()[0];accumulator.add_batch(truth[None],pred[None])\n                hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                assert __import__(\'hashlib\').sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Prior scene confusion differs\'\n                scene_metrics.append(dict(condition=name,scene=scene,**metric));pd.DataFrame(scene_metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                manifest[\'completed_identity_pairs\']+=1;save()\n                del xs,ls,target,y\n                print(f\'{name}: {index+1}/25, traced/untraced identical, prior metrics reproduced; {(time.time()-started)/60:.1f}min\',flush=True)\n            table=accumulator.get_table();row=dict(condition=name,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec.get_table().iloc[0].to_dict())\n            e=expected[\'summary\'][name]\n            assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n            summaries.append(row);pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            table.to_csv(args.out/f\'{name}_segmentation.csv\');np.save(args.out/f\'{name}_confusion.npy\',accumulator.confusion_matrix)\n            manifest[\'completed_conditions\'].append(name);save()\n        manifest[\'status\']=\'completed\'\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'gain_guard.py': '"""Fixed energy floor for an isolated data-consistency gain bound; not whole-network stability."""\nimport inspect, textwrap, types\nimport torch\nfrom numerical_trace import denominator_stats\n\nFACTOR = 1.0\n\ndef safe_denominator(d, energy):\n    return torch.maximum(d, FACTOR*energy)\n\nclass Guard:\n    def __init__(self, model, emit, enabled=True):\n        self.model=model;self.emit=emit;self.enabled=enabled;self.stage=0;self.total_activated=0\n        self.had_forward=\'forward\' in model.__dict__;self.original=model.forward\n        assert not hasattr(model,\'_guard_denominator\')\n        source=textwrap.dedent(inspect.getsource(self.original.__func__))\n        old=\'torch.div(y - A_x_phitheta, PhiPhiT + a)\'\n        assert source.count(old)==1, \'Unexpected forward source; do not patch\'\n        source=source.replace(old,\'torch.div(y - A_x_phitheta, self._guard_denominator(PhiPhiT + a, PhiPhiT))\')\n        namespace=dict(self.original.__func__.__globals__)\n        exec(compile(source,\'<source-pinned-denominator-guard>\',\'exec\'),namespace)\n        self.patched=types.MethodType(namespace[\'forward\'],model)\n\n    def __enter__(self):\n        def apply(d,energy):\n            self.stage+=1\n            used=safe_denominator(d,energy) if self.enabled else d\n            count=int((used!=d).sum());self.total_activated+=count\n            gain=energy/used\n            if self.enabled:assert bool((gain>=0).all() and (gain<=1).all()), \'Gain bound violated\'\n            self.emit(dict(stage=self.stage,event=\'denominator_guard\',enabled=self.enabled,factor=FACTOR,\n                           activated=count,elements=d.numel(),guarded_energy_gain_min=float(gain.min()),guarded_energy_gain_max=float(gain.max()),original=denominator_stats(d),used=denominator_stats(used)))\n            return used\n        self.model._guard_denominator=apply;self.model.forward=self.patched\n        return self\n\n    def __exit__(self,*exc):\n        del self.model._guard_denominator\n        if self.had_forward:self.model.forward=self.original\n        else:del self.model.forward\n', 'robustness_inputs.py': '"""Prespecified new perturbations; the inference rule is not tuned here."""\nimport hashlib, math\nimport torch\n\nCONDITIONS = [\n    (\'clean\', 0, 0., None),\n    (\'plus1_alpha0.5\', 1, .5, None),\n    (\'minus1_alpha0.5\', -1, .5, None),\n    (\'nominal_noise40\', 0, 0., 40.),\n    (\'nominal_noise30\', 0, 0., 30.),\n    (\'plus1_alpha0.25_noise40\', 1, .25, 40.),\n    (\'minus1_alpha0.25_noise40\', -1, .25, 40.),\n]\n\ndef add_noise(y, scene, dx, alpha, snr_db):\n    if snr_db is None:return y,dict(seed=None,requested_snr_db=None,actual_snr_db=None,noise_rms=0.)\n    # Omit SNR from the seed to use the same draw at two noise levels on the same acquisition.\n    key=f\'public252-noise-v1|3407|{scene}|{dx}|{alpha:g}\'\n    seed=int.from_bytes(hashlib.sha256(key.encode()).digest()[:8],\'little\')%(2**63)\n    generator=torch.Generator(device=\'cpu\').manual_seed(seed)\n    draw=torch.randn(y.shape,generator=generator,dtype=torch.float64,device=\'cpu\')\n    signal_rms=float(y.detach().cpu().double().square().mean().sqrt())\n    assert signal_rms>0 and math.isfinite(signal_rms)\n    sigma=signal_rms*10**(-snr_db/20)\n    noise=(draw/draw.square().mean().sqrt()*sigma).to(device=y.device,dtype=y.dtype)\n    noisy=y+noise\n    actual_rms=float((noisy.double()-y.double()).square().mean().sqrt())\n    actual_snr=20*math.log10(signal_rms/actual_rms)\n    assert abs(actual_snr-snr_db)<.001\n    # Decimal string preserves all seed bits when mixed with missing seeds in CSV columns.\n    return noisy,dict(seed=str(seed),requested_snr_db=snr_db,actual_snr_db=actual_snr,noise_rms=actual_rms,signal_rms=signal_rms)\n', 'robustness_experiment.py': '"""Frozen paired evaluation of one prespecified denominator safeguard."""\nimport argparse,hashlib,json,sys,time\nfrom pathlib import Path\nfrom contextlib import nullcontext\nimport numpy as np\nimport torch\nfrom operator_control import make_operator,mix_mask,sha,tensor_sha\nfrom numerical_trace import spatial_error\nfrom robustness_inputs import CONDITIONS,add_noise\nfrom gain_guard import Guard,FACTOR\n\ndef main():\n    p=argparse.ArgumentParser()\n    for key in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+key,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    assert sha(Path(__file__).with_name(\'gain_guard.py\'))==expected[\'guard_sha256\'],\'The validated guard changed\'\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    assert sha(args.code/\'models/CRSDUN.py\')==\'57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543\'\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    weight_hashes={k:tensor_sha(v) for k,v in model.state_dict().items()}\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    conditions=CONDITIONS\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],mask_sha256=ref[\'mask_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],factor=FACTOR,formula=\'d_safe=max(E+a,E); E is existing guarded squared-mask energy\',scenes=scenes,conditions=conditions,completed_conditions=[],completed_pairs=0,expected_forwards=350,training=False,test_evaluated=False,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'Fixed unit-gain floor, no tuning. New alpha0.5 mixtures and synthetic additive measurement noise on the same25 validation scenes. Matched operators and identical noisy measurements per pair. No training/test use/clipping. Gaussian draws globally scaled to exact scene RMS SNR, not a calibrated sensor model.\',script_hashes={n:sha(Path(__file__).with_name(n)) for n in (\'robustness_experiment.py\',\'gain_guard.py\',\'numerical_trace.py\',\'operator_control.py\',\'robustness_inputs.py\')})\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha,snr_db in conditions:\n            op=make_operator(mask if not dx else mix_mask(mask,dx,alpha));op_hash=[tensor_sha(t) for t in op]\n            raw_energy=op[1].square().sum(1)[0]\n            width=mask.shape[1]\n            aligned_energy=torch.stack([raw_energy[:,2*c:2*c+width] for c in range(28)]).cpu().numpy()\n            seg={mode:Metrics_Seg(23,get_class_names()) for mode in (\'control\',\'guarded\')}\n            rec={mode:Metrics_Rec() for mode in seg}\n            folder=args.out/name;folder.mkdir()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                noiseless=init_meas(target,op[1],\'Y\')\n                y,noise_info=add_noise(noiseless,scene,dx,alpha,snr_db);yh=tensor_sha(y);baseline_hashes=None\n                target_cpu=target.cpu();target_array=target_cpu.double().numpy()\n                for mode in (\'control\',\'guarded\'):\n                    def emit(row):f.write(json.dumps(dict(condition=name,scene=scene,mode=mode,**row),allow_nan=False)+\'\\n\')\n                    ctx=Guard(model,emit) if mode==\'guarded\' else nullcontext()\n                    with ctx as guard:\n                        xs,ls=model(y,op)\n                    f.flush()\n                    assert all(torch.isfinite(t).all() for t in [*xs,*ls]),\'Nonfinite model output\'\n                    output_hashes=[tensor_sha(t) for t in [*xs,*ls]]\n                    if mode==\'control\':baseline_hashes=output_hashes\n                    else:\n                        assert guard.stage==5\n                        identical=baseline_hashes==output_hashes\n                        row=dict(condition=name,scene=scene,activated=guard.total_activated,all_stage_outputs_identical=identical,inactive=guard.total_activated==0)\n                        checks.append(row);(args.out/\'pair_checks.json\').write_text(json.dumps(checks,indent=2))\n                        if guard.total_activated==0:assert identical,\'Inactive guard changed outputs\'\n                    assert tensor_sha(y)==yh and [tensor_sha(t) for t in op]==op_hash\n                    assert not hasattr(model,\'_guard_denominator\') and \'forward\' not in model.__dict__\n                    one=Metrics_Rec();one.add_batch(target_cpu,xs[-1].cpu());values=one.get_table().iloc[0].to_dict()\n                    pred=ls[-1].argmax(1).cpu().numpy()[0]\n                    hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                    if name==\'clean\':\n                        e=expected[\'scenes\'][mode][scene]\n                        assert abs(values[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(values[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Clean reconstruction differs from verified arm\'\n                        assert hashlib.sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Clean segmentation differs from verified arm\'\n                    np.save(folder/f\'{mode}_{scene}_confusion.npy\',hist)\n                    seg[mode].add_batch(truth[None],pred[None])\n                    for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec[mode],field,getattr(rec[mode],field)+getattr(one,field))\n                    region=spatial_error(xs[-1],target_array,aligned_energy)\n                    emit(dict(stage=5,event=\'final_spatial_error\',reconstruction_error=region))\n                    f.flush()\n                    metrics.append(dict(condition=name,scene=scene,mode=mode,measurement_sha256=yh,noiseless_sha256=tensor_sha(noiseless),**noise_info,**values))\n                    pd.DataFrame(metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                    del xs,ls\n                manifest[\'completed_pairs\']+=1;save();del target,y,noiseless,target_cpu,target_array\n                print(f\'{name}: {index+1}/25 paired; {(time.time()-started)/60:.1f}min\',flush=True)\n            for mode in seg:\n                table=seg[mode].get_table()\n                summed=sum(np.load(folder/f\'{mode}_{s}_confusion.npy\') for s in scenes)\n                assert np.array_equal(summed,seg[mode].confusion_matrix)\n                np.save(folder/f\'{mode}_aggregate_confusion.npy\',summed);table.to_csv(folder/f\'{mode}_segmentation.csv\')\n                row=dict(condition=name,mode=mode,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec[mode].get_table().iloc[0].to_dict())\n                if name==\'clean\':\n                    e=expected[\'summary\'][mode]\n                    assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n                summaries.append(row)\n            pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            manifest[\'completed_conditions\'].append(name);save()\n        pairs=[]\n        for name,_,_,_ in conditions:\n            a,b=[next(r for r in summaries if r[\'condition\']==name and r[\'mode\']==mode) for mode in (\'control\',\'guarded\')]\n            pairs.append(dict(condition=name,control_miou_percent=100*a[\'foreground_miou_all22\'],guarded_miou_percent=100*b[\'foreground_miou_all22\'],miou_change_points=100*(b[\'foreground_miou_all22\']-a[\'foreground_miou_all22\']),control_psnr=a[\'PSNR\'],guarded_psnr=b[\'PSNR\'],psnr_change=b[\'PSNR\']-a[\'PSNR\'],control_mse=a[\'MSE\'],guarded_mse=b[\'MSE\']))\n        pd.DataFrame(pairs).to_csv(args.out/\'paired_summary.csv\',index=False)\n        assert weight_hashes=={k:tensor_sha(v) for k,v in model.state_dict().items()},\'Model state mutated\'\n        manifest.update(status=\'completed\',model_state_unchanged=True)\n        print(pd.DataFrame(pairs).to_string(index=False),flush=True)\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'verify_robustness_inputs.py': "import torch\nfrom robustness_inputs import add_noise,CONDITIONS\ny=torch.linspace(.1,5,2048).reshape(1,32,64)\nsaved=y.clone();state=torch.random.get_rng_state().clone()\nclean,meta=add_noise(y,'scene_a',0,0.,None)\nassert clean is y and meta['noise_rms']==0\na,ma=add_noise(y,'scene_a',0,0.,40.)\nb,mb=add_noise(y,'scene_a',0,0.,40.)\nc,mc=add_noise(y,'scene_a',0,0.,30.)\nd,md=add_noise(y,'scene_b',0,0.,40.)\nassert torch.equal(a,b) and ma==mb and torch.equal(y,saved)\nassert torch.equal(state,torch.random.get_rng_state()),'Global RNG changed'\nassert ma['seed']==mc['seed'] and ma['seed']!=md['seed'] and not torch.equal(a,d)\nassert abs(mc['noise_rms']/ma['noise_rms']-10**.5)<1e-4\nassert torch.allclose((c-y)/(10**.5),a-y,rtol=1e-3,atol=1e-6)\nif torch.cuda.is_available():\n    g,mg=add_noise(y.cuda(),'scene_a',0,0.,40.)\n    assert torch.equal(a,g.cpu()) and abs(mg['actual_snr_db']-40)<.001\nassert len(CONDITIONS)==7 and len({c[0] for c in CONDITIONS})==7\nprint('PASS: deterministic scene/acquisition noise, exact requested RMS SNR, shared draws across levels, unchanged inputs/global RNG, seven fixed conditions.')\n"}
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}
EXPECTED={'source_archive': 'gain_bound_epoch441_20261011_093437_032153.zip', 'source_archive_sha256': '58bba27c6a9ed3d95bcf65ef1c3d1431bf788aaa52315837e7b558dee94c221e', 'summary': {'control': {'foreground_miou_all22': 0.7876837070566084, 'PSNR': 39.00684585571289, 'MSE': 0.0001312368325307034, 'SSIM': 0.9747850584983826}, 'guarded': {'foreground_miou_all22': 0.7887498949606914, 'PSNR': 39.08712356567383, 'MSE': 0.00012905740935821087, 'SSIM': 0.9754946565628052}}, 'scenes': {'control': {'2021-11-03_046': {'PSNR': 39.89459228515625, 'MSE': 0.00010245675366604701, 'confusion_sha256': '9a717b84a51b72b2fba1c9060dfc8ad32d2508a3c8f0eb98494f1809757909ec'}, '2021-11-03_047': {'PSNR': 38.86285400390625, 'MSE': 0.00012993150448892266, 'confusion_sha256': '919915901d083e6ed85b8577721c7392ee968a7d23b41b7d6df5407226b34d16'}, '2021-11-03_057': {'PSNR': 37.99570083618164, 'MSE': 0.00015864626038819551, 'confusion_sha256': '711f63aea60da1ad3e5dd583c1ad6c185b62eb8ead7661faab625fefc9a93000'}, '2021-11-03_085': {'PSNR': 40.45058059692383, 'MSE': 9.01449893717654e-05, 'confusion_sha256': 'f26712d2687056e1f8812c93a119dc945e55a6c1c3a465d8c75b9e4e89c4cfdd'}, '2021-11-03_090': {'PSNR': 40.33523178100586, 'MSE': 9.257133206119761e-05, 'confusion_sha256': 'ce95968be99e39136bb3a54ba923ea41501fa0803c75a0bae08d8bd21e2de7ec'}, '2021-11-03_110': {'PSNR': 39.576499938964844, 'MSE': 0.00011024273408111185, 'confusion_sha256': '925537ac21544cbbed2767f15ad85fa1c7a52691dc70e7712568c6260f9b2c13'}, '2021-11-04_010': {'PSNR': 37.1390495300293, 'MSE': 0.00019323908782098442, 'confusion_sha256': 'c9099b0d0a570152439bb9708c16c6f9882d2b9d23632b94de45b23e5e2e145b'}, '2021-11-04_017': {'PSNR': 38.54598617553711, 'MSE': 0.00013976586342323571, 'confusion_sha256': 'dcdfe2f5a2ef36a30df2960ae7f34537645c5ef3070a89e09ec06fe7708f669c'}, '2021-11-04_024': {'PSNR': 38.70061111450195, 'MSE': 0.00013487727846950293, 'confusion_sha256': 'e3082e8a5aee905c21b646233bda5e8f37889d2ec740925842e5389426415656'}, '2021-11-04_042': {'PSNR': 40.50850296020508, 'MSE': 8.89507427928038e-05, 'confusion_sha256': '69745abc94ea2ee55b0aac789679b0353d08f391c931258e232dd465690d7f22'}, '2021-11-04_047': {'PSNR': 40.220394134521484, 'MSE': 9.505181515123695e-05, 'confusion_sha256': 'b6c73d3bec5395b68de7c48614e082e1c36f6330ee46719b20947da3f4c25bbc'}, '2021-11-04_049': {'PSNR': 40.831241607666016, 'MSE': 8.258013986051083e-05, 'confusion_sha256': 'b63f6d857eeb2b1870346a4ecb5c3594f5dea62fefe6262ece4344a65a2791c2'}, '2021-11-04_055': {'PSNR': 40.75486373901367, 'MSE': 8.404529944527894e-05, 'confusion_sha256': '995f147be920d56d9ba740f6ec33fd436afc5e1a8eaad452b5dcaa746edd9834'}, '2021-11-04_061': {'PSNR': 40.68517303466797, 'MSE': 8.540487760910764e-05, 'confusion_sha256': '59adfbe1bb34d1890af5029d8bd8281620d18396e9b876be0e4f6e4f6f5d2596'}, '2021-11-04_093': {'PSNR': 39.08949661254883, 'MSE': 0.00012332471669651568, 'confusion_sha256': '6366ce691015ac82a2669684a1c4d681bff89544f92fab6972d817ea7e7d7b2c'}, '2021-11-04_098': {'PSNR': 39.36787414550781, 'MSE': 0.00011566773900995031, 'confusion_sha256': '6d227838a684f6f312e50afa89da8c8623ad19564835045da03dc93a2bdabdea'}, '2021-11-05_010': {'PSNR': 37.41633987426758, 'MSE': 0.0001812866685213521, 'confusion_sha256': '13b3bae21986dd485dbe9125a904ee039a7d076c7e1aa9a2c19c4a8317eeee6f'}, '2021-11-05_024': {'PSNR': 39.7016716003418, 'MSE': 0.00010711063077906147, 'confusion_sha256': 'df5555f991ede7f38186ff4cbfe4dca368ad0ff0bfba94e2cb5e5ae992659d4f'}, '2021-11-05_035': {'PSNR': 38.78630065917969, 'MSE': 0.00013224220310803503, 'confusion_sha256': '7642e43435e57e4c293c5497b3ed47fdf0830fab3a34010f983d393ff6f79224'}, '2021-11-05_041': {'PSNR': 38.4978141784668, 'MSE': 0.00014132481010165066, 'confusion_sha256': 'cee79d0f10b1a368417af8ec32939e69ccfc5a1d5d4b70c9727535b9fe968e3b'}, '2021-11-05_046': {'PSNR': 36.10015869140625, 'MSE': 0.0002454617933835834, 'confusion_sha256': '99ceb435926731d4d7593346568ef795f28ff326dcb5a775f1f9fe1af0388e31'}, '2021-11-10_014': {'PSNR': 38.25468063354492, 'MSE': 0.00014946238661650568, 'confusion_sha256': '700d7bfb7ee77774c754fa984c10b556125d20f7eb11ce8f8fea4055a35c9fc2'}, '2021-11-10_024': {'PSNR': 37.73176193237305, 'MSE': 0.00016858673188835382, 'confusion_sha256': '32c9dfe5fd11c769fdd29d729a4cc2575d048096185fe33c83c76f035d77b383'}, '2021-11-10_029': {'PSNR': 38.25230407714844, 'MSE': 0.00014954422658775002, 'confusion_sha256': '55b866708c3de1af700fe8c596c4acee41e9c60fc89886eb282486f138541098'}, '2021-11-10_050': {'PSNR': 37.47146224975586, 'MSE': 0.00017900022794492543, 'confusion_sha256': 'ffff7a303633916099bc9025d29370aab79abad5f287f2f452f346467e5b0f9a'}}, 'guarded': {'2021-11-03_046': {'PSNR': 39.962379455566406, 'MSE': 0.0001008699691738002, 'confusion_sha256': '374f3a7a88d8f8cda10ff9b6e33ece2beebedf7b8a18648e0fdd0fd9008b899a'}, '2021-11-03_047': {'PSNR': 38.931861877441406, 'MSE': 0.00012788323510903865, 'confusion_sha256': '0e5826e07647666e0a58af34c68eeee921f33213f9036e659f2bd74941113673'}, '2021-11-03_057': {'PSNR': 38.056732177734375, 'MSE': 0.00015643230290152133, 'confusion_sha256': 'e632f0ad7bff87592d55c39978b1bfb65d857589b277bf49757c151f6c358b43'}, '2021-11-03_085': {'PSNR': 40.56583023071289, 'MSE': 8.778433402767405e-05, 'confusion_sha256': '842c3e80b60a7b2ecac3e329e85798ddff4567c0fe1592e3d85545a722d58d0b'}, '2021-11-03_090': {'PSNR': 40.435272216796875, 'MSE': 9.046330524142832e-05, 'confusion_sha256': '209f23854013a461b5fb508754297bb853090446c24aecb2903be1ea92ec312c'}, '2021-11-03_110': {'PSNR': 39.70124053955078, 'MSE': 0.00010712122457334772, 'confusion_sha256': 'dc7429aad3c4721656de72d138f77f572bc00c6fe27173c34833c457553bc9d9'}, '2021-11-04_010': {'PSNR': 37.16178512573242, 'MSE': 0.00019223005801904947, 'confusion_sha256': '56558d4b7f070f234e77cf7ae52897b31f3525aff68940d220e84780e2e9f8a5'}, '2021-11-04_017': {'PSNR': 38.585121154785156, 'MSE': 0.00013851208495907485, 'confusion_sha256': 'b8e69792f730b257540b91a7ad9adfb81a5811ea2d90c530914cfa9368273fdb'}, '2021-11-04_024': {'PSNR': 38.73848342895508, 'MSE': 0.00013370622764341533, 'confusion_sha256': '844b89a123ad0d7705d9624d6d0cc914690124d0cb8171b1c650aa79d92dd40f'}, '2021-11-04_042': {'PSNR': 40.58415222167969, 'MSE': 8.741471538087353e-05, 'confusion_sha256': 'a186add554b815e1981560085145a33acd0bee8132718d2e1a2d0cac0e087350'}, '2021-11-04_047': {'PSNR': 40.28378677368164, 'MSE': 9.367440361529589e-05, 'confusion_sha256': 'cee7f430829b0199aad2d4a448ddf8de62da7c80450f995c696cc85cbd85f09a'}, '2021-11-04_049': {'PSNR': 40.924591064453125, 'MSE': 8.082403655862436e-05, 'confusion_sha256': '73e59e145e8b58c68ce1321b5fa6175893f9bb64936b74993bdc45e0c200b448'}, '2021-11-04_055': {'PSNR': 40.86586380004883, 'MSE': 8.192441600840539e-05, 'confusion_sha256': '191414b6176ae9302113fb5f58f097a6b477978f68e0498efbe6c7ec4a865786'}, '2021-11-04_061': {'PSNR': 40.808006286621094, 'MSE': 8.30231947475113e-05, 'confusion_sha256': 'c7507258d7b67089f8ee761269bad5bf81f59d0e558ad95dee2fe4056a96ba8a'}, '2021-11-04_093': {'PSNR': 39.19356155395508, 'MSE': 0.00012040480214636773, 'confusion_sha256': '8b95877e87ffa23382399a1533c2b2dd7061f2ffc4de90549a11a3b3571346e5'}, '2021-11-04_098': {'PSNR': 39.46736526489258, 'MSE': 0.00011304812505841255, 'confusion_sha256': '426e1afa1a1a82a2c29d95847fdd91c32de632db9dccc566aff8311d80bd8ca4'}, '2021-11-05_010': {'PSNR': 37.46293258666992, 'MSE': 0.00017935209325514734, 'confusion_sha256': '840649f0e14463f1d0b6c3625c81e383ad6898911be94352f7ceaa80fa230b46'}, '2021-11-05_024': {'PSNR': 39.879234313964844, 'MSE': 0.00010281968570780009, 'confusion_sha256': '6b7ece9425b74d81f3e0f5a8b7909df1ed16342fbebdda661a1b5c99ad5f577f'}, '2021-11-05_035': {'PSNR': 38.91636276245117, 'MSE': 0.00012834045628551394, 'confusion_sha256': 'b155132bec9234e755ccd24a5f4ffa35111ce197e9ad5de752accb9b8840364c'}, '2021-11-05_041': {'PSNR': 38.572322845458984, 'MSE': 0.0001389209064655006, 'confusion_sha256': '17f1334b21ebc9b8390c31c3cf725f349a95d21171e276ffc7c1e5bbefa2996b'}, '2021-11-05_046': {'PSNR': 36.126548767089844, 'MSE': 0.00024397484958171844, 'confusion_sha256': 'd5af010297e16ebde959393c4d76806a598cd7749dd54b674db23028ecea6b5f'}, '2021-11-10_014': {'PSNR': 38.300148010253906, 'MSE': 0.00014790569548495114, 'confusion_sha256': '3abc330e9e68de63e0ccaf5741f0e4356380395b9b2613e6c8bf243d274800d2'}, '2021-11-10_024': {'PSNR': 37.78757095336914, 'MSE': 0.00016643419803585857, 'confusion_sha256': 'd775cb05bc1c181c65a84bd9f72df3c8ee00fe213aee042c2f60fe6a501c378b'}, '2021-11-10_029': {'PSNR': 38.35245895385742, 'MSE': 0.0001461348874727264, 'confusion_sha256': '13f17289413e6b4657ca49719ab4e08f63a9b69da6bbb794f72d2b628cdad643'}, '2021-11-10_050': {'PSNR': 37.51447677612305, 'MSE': 0.00017723602650221437, 'confusion_sha256': '3e4aefe4db72b03ef825148e78b764f1aa720d6af1c3793b3e5fca94364e7fcf'}}}, 'guard_sha256': '48101cb5d2076a06fa80e8498eabf8e984968d4c325a12e21c057d43fac4b28d'}

RUN=WORK/('robustness_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
for filename,source in FILES.items():(RUN/filename).write_text(source)
assert digest(RUN/'gain_guard.py')==EXPECTED['guard_sha256']
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'expected.json').write_text(json.dumps(EXPECTED,indent=2))
(RUN/'source_hashes.json').write_text(json.dumps({f:digest(CODE/f) for f in ['models/CRSDUN.py','dataset.py','utils.py','public252-v1.json']},indent=2))
with (RUN/'local_checks.log').open('w') as log:
    result=subprocess.run([sys.executable,str(RUN/'verify_robustness_inputs.py')],cwd=RUN,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
    log.write(result.stdout);print(result.stdout)
    result.check_returncode()
print('Output folder:',RUN)

PASS: deterministic scene/acquisition noise, exact requested RMS SNR, shared draws across levels, unchanged inputs/global RNG, seven fixed conditions.

Output folder: /kaggle/working/robustness_epoch441_20261011_120732_586209

In [3]:
from IPython.display import display,FileLink
try:
    with (RUN/'console.log').open('w') as log:
        command=[sys.executable,'-u',str(RUN/'robustness_experiment.py'),
                 '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
                 '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json'),'--expected',str(RUN/'expected.json')]
        proc=subprocess.Popen(command,cwd=CODE,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)
        try:
            for line in proc.stdout:
                print(line,end='',flush=True)
                log.write(line);log.flush()
            code=proc.wait()
            if code: raise subprocess.CalledProcessError(code,command)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try: proc.wait(timeout=10)
                except subprocess.TimeoutExpired: proc.kill();proc.wait()
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
clean: 1/25 paired; 0.2min
clean: 2/25 paired; 0.3min
clean: 3/25 paired; 0.5min
clean: 4/25 paired; 0.6min
clean: 5/25 paired; 0.8min
clean: 6/25 paired; 0.9min
clean: 7/25 paired; 1.0min
clean: 8/25 paired; 1.2min
clean: 9/25 paired; 1.3min
clean: 10/25 paired; 1.5min
clean: 11/25 paired; 1.6min
clean: 12/25 paired; 1.7min
clean: 13/25 paired; 1.9min
clean: 14/25 paired; 2.0min
clean: 15/25 paired; 2.2min
clean: 16/25 paired; 2.3min
clean: 17/25 paired; 2.5min
clean: 18/25 paired; 2.6min
clean: 19/25 paired; 2.7min
clean: 20/25 paired; 2.9min
clean: 21/25 paired; 3.0min
clean: 22/25 paired; 3.2min
clean: 23/25 paired; 3.3min
clean: 24/25 paired; 3.5min
clean: 25/25 paired; 3.6min
plus1_alpha0.5: 1/25 paired; 3.7min
plus1_alpha0.5: 2/25 paired; 3.9min
plus1_alpha0.5: 3/25 paired; 4.0min
plus1_alpha0.5: 4/25 paired; 4.1min
plus1_alpha0.5: 5/25 paired; 4.3min
plus1_alpha0.5: 6/25 paired; 4.4min
plus1_alpha0.5: 7/25 paired; 4.6min
plus1_alpha0.5: 8/25 paired; 4.7min
plus1_alpha0.5: 9/25 paired; 4.8min
plus1_alpha0.5: 10/25 paired; 5.0min
plus1_alpha0.5: 11/25 paired; 5.1min
plus1_alpha0.5: 12/25 paired; 5.2min
plus1_alpha0.5: 13/25 paired; 5.4min
plus1_alpha0.5: 14/25 paired; 5.5min
plus1_alpha0.5: 15/25 paired; 5.6min
plus1_alpha0.5: 16/25 paired; 5.8min
plus1_alpha0.5: 17/25 paired; 5.9min
plus1_alpha0.5: 18/25 paired; 6.0min
plus1_alpha0.5: 19/25 paired; 6.2min
plus1_alpha0.5: 20/25 paired; 6.3min
plus1_alpha0.5: 21/25 paired; 6.4min
plus1_alpha0.5: 22/25 paired; 6.6min
plus1_alpha0.5: 23/25 paired; 6.7min
plus1_alpha0.5: 24/25 paired; 6.8min
plus1_alpha0.5: 25/25 paired; 7.0min
minus1_alpha0.5: 1/25 paired; 7.1min
minus1_alpha0.5: 2/25 paired; 7.3min
minus1_alpha0.5: 3/25 paired; 7.4min
minus1_alpha0.5: 4/25 paired; 7.5min
minus1_alpha0.5: 5/25 paired; 7.7min
minus1_alpha0.5: 6/25 paired; 7.8min
minus1_alpha0.5: 7/25 paired; 7.9min
minus1_alpha0.5: 8/25 paired; 8.1min
minus1_alpha0.5: 9/25 paired; 8.2min
minus1_alpha0.5: 10/25 paired; 8.3min
minus1_alpha0.5: 11/25 paired; 8.5min
minus1_alpha0.5: 12/25 paired; 8.6min
minus1_alpha0.5: 13/25 paired; 8.7min
minus1_alpha0.5: 14/25 paired; 8.9min
minus1_alpha0.5: 15/25 paired; 9.0min
minus1_alpha0.5: 16/25 paired; 9.2min
minus1_alpha0.5: 17/25 paired; 9.3min
minus1_alpha0.5: 18/25 paired; 9.4min
minus1_alpha0.5: 19/25 paired; 9.6min
minus1_alpha0.5: 20/25 paired; 9.7min
minus1_alpha0.5: 21/25 paired; 9.8min
minus1_alpha0.5: 22/25 paired; 10.0min
minus1_alpha0.5: 23/25 paired; 10.1min
minus1_alpha0.5: 24/25 paired; 10.2min
minus1_alpha0.5: 25/25 paired; 10.4min
nominal_noise40: 1/25 paired; 10.5min
nominal_noise40: 2/25 paired; 10.6min
nominal_noise40: 3/25 paired; 10.8min
nominal_noise40: 4/25 paired; 10.9min
nominal_noise40: 5/25 paired; 11.1min
nominal_noise40: 6/25 paired; 11.2min
nominal_noise40: 7/25 paired; 11.3min
nominal_noise40: 8/25 paired; 11.5min
nominal_noise40: 9/25 paired; 11.6min
nominal_noise40: 10/25 paired; 11.7min
nominal_noise40: 11/25 paired; 11.9min
nominal_noise40: 12/25 paired; 12.0min
nominal_noise40: 13/25 paired; 12.2min
nominal_noise40: 14/25 paired; 12.3min
nominal_noise40: 15/25 paired; 12.4min
nominal_noise40: 16/25 paired; 12.6min
nominal_noise40: 17/25 paired; 12.7min
nominal_noise40: 18/25 paired; 12.8min
nominal_noise40: 19/25 paired; 13.0min
nominal_noise40: 20/25 paired; 13.1min
nominal_noise40: 21/25 paired; 13.2min
nominal_noise40: 22/25 paired; 13.4min
nominal_noise40: 23/25 paired; 13.5min
nominal_noise40: 24/25 paired; 13.6min
nominal_noise40: 25/25 paired; 13.8min
nominal_noise30: 1/25 paired; 13.9min
nominal_noise30: 2/25 paired; 14.1min
nominal_noise30: 3/25 paired; 14.2min
nominal_noise30: 4/25 paired; 14.3min
nominal_noise30: 5/25 paired; 14.5min
nominal_noise30: 6/25 paired; 14.6min
nominal_noise30: 7/25 paired; 14.7min
nominal_noise30: 8/25 paired; 14.9min
nominal_noise30: 9/25 paired; 15.0min
nominal_noise30: 10/25 paired; 15.1min
nominal_noise30: 11/25 paired; 15.3min
nominal_noise30: 12/25 paired; 15.4min
nominal_noise30: 13/25 paired; 15.5min
nominal_noise30: 14/25 paired; 15.7min
nominal_noise30: 15/25 paired; 15.8min
nominal_noise30: 16/25 paired; 16.0min
nominal_noise30: 17/25 paired; 16.1min
nominal_noise30: 18/25 paired; 16.2min
nominal_noise30: 19/25 paired; 16.4min
nominal_noise30: 20/25 paired; 16.5min
nominal_noise30: 21/25 paired; 16.6min
nominal_noise30: 22/25 paired; 16.8min
nominal_noise30: 23/25 paired; 16.9min
nominal_noise30: 24/25 paired; 17.0min
nominal_noise30: 25/25 paired; 17.2min
plus1_alpha0.25_noise40: 1/25 paired; 17.3min
plus1_alpha0.25_noise40: 2/25 paired; 17.4min
plus1_alpha0.25_noise40: 3/25 paired; 17.6min
plus1_alpha0.25_noise40: 4/25 paired; 17.7min
plus1_alpha0.25_noise40: 5/25 paired; 17.9min
plus1_alpha0.25_noise40: 6/25 paired; 18.0min
plus1_alpha0.25_noise40: 7/25 paired; 18.1min
plus1_alpha0.25_noise40: 8/25 paired; 18.3min
plus1_alpha0.25_noise40: 9/25 paired; 18.4min
plus1_alpha0.25_noise40: 10/25 paired; 18.5min
plus1_alpha0.25_noise40: 11/25 paired; 18.7min
plus1_alpha0.25_noise40: 12/25 paired; 18.8min
plus1_alpha0.25_noise40: 13/25 paired; 18.9min
plus1_alpha0.25_noise40: 14/25 paired; 19.1min
plus1_alpha0.25_noise40: 15/25 paired; 19.2min
plus1_alpha0.25_noise40: 16/25 paired; 19.3min
plus1_alpha0.25_noise40: 17/25 paired; 19.5min
plus1_alpha0.25_noise40: 18/25 paired; 19.6min
plus1_alpha0.25_noise40: 19/25 paired; 19.8min
plus1_alpha0.25_noise40: 20/25 paired; 19.9min
plus1_alpha0.25_noise40: 21/25 paired; 20.0min
plus1_alpha0.25_noise40: 22/25 paired; 20.2min
plus1_alpha0.25_noise40: 23/25 paired; 20.3min
plus1_alpha0.25_noise40: 24/25 paired; 20.4min
plus1_alpha0.25_noise40: 25/25 paired; 20.6min
minus1_alpha0.25_noise40: 1/25 paired; 20.7min
minus1_alpha0.25_noise40: 2/25 paired; 20.8min
minus1_alpha0.25_noise40: 3/25 paired; 21.0min
minus1_alpha0.25_noise40: 4/25 paired; 21.1min
minus1_alpha0.25_noise40: 5/25 paired; 21.2min
minus1_alpha0.25_noise40: 6/25 paired; 21.4min
minus1_alpha0.25_noise40: 7/25 paired; 21.5min
minus1_alpha0.25_noise40: 8/25 paired; 21.7min
minus1_alpha0.25_noise40: 9/25 paired; 21.8min
minus1_alpha0.25_noise40: 10/25 paired; 21.9min
minus1_alpha0.25_noise40: 11/25 paired; 22.1min
minus1_alpha0.25_noise40: 12/25 paired; 22.2min
minus1_alpha0.25_noise40: 13/25 paired; 22.3min
minus1_alpha0.25_noise40: 14/25 paired; 22.5min
minus1_alpha0.25_noise40: 15/25 paired; 22.6min
minus1_alpha0.25_noise40: 16/25 paired; 22.7min
minus1_alpha0.25_noise40: 17/25 paired; 22.9min
minus1_alpha0.25_noise40: 18/25 paired; 23.0min
minus1_alpha0.25_noise40: 19/25 paired; 23.1min
minus1_alpha0.25_noise40: 20/25 paired; 23.3min
minus1_alpha0.25_noise40: 21/25 paired; 23.4min
minus1_alpha0.25_noise40: 22/25 paired; 23.5min
minus1_alpha0.25_noise40: 23/25 paired; 23.7min
minus1_alpha0.25_noise40: 24/25 paired; 23.8min
minus1_alpha0.25_noise40: 25/25 paired; 24.0min
               condition  control_miou_percent  guarded_miou_percent  miou_change_points  control_psnr  guarded_psnr  psnr_change  control_mse  guarded_mse
                   clean             78.768371             78.874989            0.106619     39.006846     39.087124     0.080278     0.000131     0.000129
          plus1_alpha0.5             56.472711             69.089544           12.616833      0.391656     34.085981    33.694325    58.459301     0.000402
         minus1_alpha0.5             55.635039             69.381944           13.746905     -0.805224     34.161295    34.966518   287.369370     0.000394
         nominal_noise40             73.252734             73.387606            0.134871     35.497581     35.977481     0.479900     0.000284     0.000256
         nominal_noise30             57.116704             56.656602           -0.460102     28.837772     29.583678     0.745906     0.001314     0.001109
 plus1_alpha0.25_noise40             65.243416             69.333182            4.089766    -10.211110     33.444063    43.655172  1084.954591     0.000457
minus1_alpha0.25_noise40             65.139403             68.693356            3.553953     -9.718108     33.432114    43.150222   174.948300     0.000458
Download this ZIP even if an error occurred: robustness_epoch441_20261011_120732_586209.zip

/kaggle/working/robustness_epoch441_20261011_120732_586209.zip

In [4]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed','Partial run: share the ZIP and error.'
assert manifest['completed_pairs']==175 and manifest['model_state_unchanged']
display(pd.read_csv(RUN/'results/paired_summary.csv'))
measurements=pd.read_csv(RUN/'results/per_scene_metrics.csv',dtype={'seed':'string'})
display(measurements[measurements['mode']=='control'].groupby('condition')['actual_snr_db'].agg(['min','max']))
print('Completed. Download robustness_epoch441 ZIP and share its local path. This assesses new synthetic stresses on existing validation scenes; no independent test or retraining was performed.')

,condition,control_miou_percent,guarded_miou_percent,miou_change_points,control_psnr,guarded_psnr,psnr_change,control_mse,guarded_mse
0,clean,78.768371,78.874989,0.106619,39.006846,39.087124,0.080278,0.000131,0.000129
1,plus1_alpha0.5,56.472711,69.089544,12.616833,0.391656,34.085981,33.694325,58.459301,0.000402
2,minus1_alpha0.5,55.635039,69.381944,13.746905,-0.805224,34.161295,34.966518,287.369370,0.000394
3,nominal_noise40,73.252734,73.387606,0.134871,35.497581,35.977481,0.479900,0.000284,0.000256
4,nominal_noise30,57.116704,56.656602,-0.460102,28.837772,29.583678,0.745906,0.001314,0.001109
5,plus1_alpha0.25_noise40,65.243416,69.333182,4.089766,-10.211110,33.444063,43.655172,1084.954591,0.000457
6,minus1_alpha0.25_noise40,65.139403,68.693356,3.553953,-9.718108,33.432114,43.150222,174.948300,0.000458

                           min   max
condition
clean                      NaN   NaN
minus1_alpha0.25_noise40  40.0  40.0
minus1_alpha0.5            NaN   NaN
nominal_noise30           30.0  30.0
nominal_noise40           40.0  40.0
plus1_alpha0.25_noise40   40.0  40.0
plus1_alpha0.5             NaN   NaN

Completed. Download robustness_epoch441 ZIP and share its local path. This assesses new synthetic stresses on existing validation scenes; no independent test or retraining was performed.

In [5]:
from pathlib import Path
import zipfile, shutil, hashlib, json, sys, subprocess, datetime, os
import torch
INPUT=Path('/kaggle/input')
WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(), 'Enable a GPU first.'
assert DATA.is_dir(), 'Attach the prepared public252 dataset.'
def digest(p):
    h=hashlib.sha256()
    with p.open('rb') as f:
        for b in iter(lambda:f.read(1024*1024), b''): h.update(b)
    return h.hexdigest()
def safe_extract(z,target):
    target=target.resolve()
    for m in z.infolist():
        dest=(target/m.filename).resolve()
        assert dest.is_relative_to(target), f'Unsafe archive path: {m.filename}'
        assert (m.external_attr >> 16) & 0o170000 != 0o120000, 'Symlinks not allowed'
    z.extractall(target)
# Locate the matching packaged evaluator, including automatically extracted inputs.
CODE=None
for p in sorted(INPUT.rglob('test.py')):
    if (p.parent/'run_sampling_experiment.py').is_file() and '--save_segmentation' in p.read_text():
        CODE=p.parent
        break
if CODE is None:
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if 'BTP/run_sampling_experiment.py' in z.namelist() and 'BTP/test.py' in z.namelist():
                if '--save_segmentation' in z.read('BTP/test.py').decode():
                    staging=WORK/('audit_code_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
                    safe_extract(z,staging)
                    CODE=staging/'BTP'
                    break
assert CODE is not None, 'Attach BTP-code-sampling.zip.'
EXPECTED='4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff'
CHECKPOINT=None
for p in sorted(INPUT.rglob('best_iou.pth')):
    if digest(p)==EXPECTED:
        CHECKPOINT=p
        break
if CHECKPOINT is None:
    member='balanced410_to_epoch500_20261010_094143/model/best_iou.pth'
    for archive in sorted(INPUT.rglob('*.zip')):
        with zipfile.ZipFile(archive) as z:
            if member in z.namelist():
                payload=z.read(member)
                if hashlib.sha256(payload).hexdigest()==EXPECTED:
                    target=WORK/'verified_epoch441_best'
                    target.mkdir(exist_ok=True)
                    CHECKPOINT=target/'best_iou.pth'
                    CHECKPOINT.write_bytes(payload)
                    break
assert CHECKPOINT is not None, 'Attach balanced410_to_epoch500_20261010_094143_epoch500.zip.'
assert digest(CHECKPOINT)==EXPECTED
print('GPU:',torch.cuda.get_device_name(0))
print('Code:',CODE,'\nVerified epoch441 weights:',CHECKPOINT)
BASELINE_EVALUATOR_HASHES={'test.py': '87dabe3e452640806fa213f555f2eeb7f2ac501bac4f805f16167e9989375423', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}
for filename, expected_hash in BASELINE_EVALUATOR_HASHES.items():
    assert digest(CODE/filename)==expected_hash, f"Evaluator changed: {filename}. Attach BTP-code-sampling.zip."

assert digest(CODE/"models/CRSDUN.py")=='57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', "Model source changed."

GPU: Tesla T4
Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified epoch441 weights: /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth

In [6]:
FILES={'pilot_support.py': '"""Fixed training rule, paired randomness and auditable optimizer accounting."""\nimport inspect\nimport random\nimport textwrap\nimport types\nimport numpy as np\nimport torch\n\n\nclass TrainingGuard:\n    """Same maximum as gain_guard.Guard, without synchronizing diagnostic statistics."""\n    def __init__(self, model):\n        self.model = model\n        self.original = model.forward\n        self.had_forward = \'forward\' in model.__dict__\n        source = textwrap.dedent(inspect.getsource(self.original.__func__))\n        old = \'torch.div(y - A_x_phitheta, PhiPhiT + a)\'\n        assert source.count(old) == 1\n        source = source.replace(old, \'torch.div(y - A_x_phitheta, torch.maximum(PhiPhiT + a, PhiPhiT))\')\n        namespace = dict(self.original.__func__.__globals__)\n        exec(compile(source, \'<fixed-unit-gain-training>\', \'exec\'), namespace)\n        self.patched = types.MethodType(namespace[\'forward\'], model)\n\n    def __enter__(self):\n        self.model.forward = self.patched\n        return self\n\n    def __exit__(self, *exc):\n        if self.had_forward:\n            self.model.forward = self.original\n        else:\n            del self.model.forward\n\n\ndef rng_state():\n    return dict(python=random.getstate(), numpy=np.random.get_state(),\n                torch=torch.get_rng_state(), cuda=torch.cuda.get_rng_state_all())\n\n\ndef restore_rng(state):\n    random.setstate(state[\'python\'])\n    np.random.set_state(state[\'numpy\'])\n    torch.set_rng_state(state[\'torch\'])\n    torch.cuda.set_rng_state_all(state[\'cuda\'])\n\n\ndef same_rng(a, b):\n    return (a[\'python\'] == b[\'python\'] and a[\'numpy\'][0] == b[\'numpy\'][0]\n            and np.array_equal(a[\'numpy\'][1], b[\'numpy\'][1])\n            and a[\'numpy\'][2:] == b[\'numpy\'][2:]\n            and torch.equal(a[\'torch\'], b[\'torch\'])\n            and len(a[\'cuda\']) == len(b[\'cuda\'])\n            and all(torch.equal(x, y) for x, y in zip(a[\'cuda\'], b[\'cuda\'])))\n\n\ndef noise_schedule(epoch):\n    # 101 clean, 51 at40dB, 50 at30dB, shuffled independently of training RNG.\n    values = np.array([-1] * 101 + [40] * 51 + [30] * 50)\n    np.random.default_rng(3407 + epoch).shuffle(values)\n    return values.tolist()\n\n\nclass UpdateCounter:\n    def __init__(self, optimizer):\n        self.count = 0\n        self.handle = optimizer.register_step_post_hook(self._increment)\n\n    def _increment(self, *args, **kwargs):\n        self.count += 1\n\n\ndef update(model, optimizer, scaler, counter, measurement, operator, target, labels):\n    optimizer.zero_grad(set_to_none=True)\n    before = counter.count\n    with torch.autocast(device_type=\'cuda\'):\n        images, logits = model(measurement, operator)\n        assert len(images) == len(logits) == 5\n        rec = sum(.7 ** (4-i) * torch.nn.functional.mse_loss(x, target)\n                  for i, x in enumerate(images))\n        seg = sum(.7 ** (4-i) * torch.nn.functional.cross_entropy(x, labels)\n                  for i, x in enumerate(logits))\n        loss = rec + 1e-4 * seg\n    if not bool(torch.isfinite(loss)):\n        raise FloatingPointError(\'Nonfinite training loss; paired run stopped\')\n    scaler.scale(loss).backward()\n    scaler.step(optimizer)\n    scaler.update()\n    result = dict(rec=float(rec.detach()), seg=float(seg.detach()),\n                  updated=counter.count-before, scale=float(scaler.get_scale()))\n    optimizer.zero_grad(set_to_none=True)\n    return result\n\n\ndef atomic_save(payload, path):\n    temporary = path.with_suffix(path.suffix + \'.tmp\')\n    torch.save(payload, temporary)\n    temporary.replace(path)\n', 'noise_training_pilot.py': '"""Prespecified paired five-epoch adaptation; never reads the test loader."""\nimport argparse\nimport hashlib\nimport json\nimport sys\nimport time\nfrom contextlib import nullcontext\nfrom pathlib import Path\nfrom types import SimpleNamespace\nimport numpy as np\nimport torch\nfrom operator_control import make_operator, mix_mask, sha, tensor_sha\nfrom robustness_inputs import CONDITIONS, add_noise\nfrom pilot_support import (TrainingGuard, UpdateCounter, update, noise_schedule,\n                           rng_state, restore_rng, same_rng, atomic_save)\n\nARMS = (\'control\', \'guarded\')\nPROTOCOL = dict(version=\'epoch441-paired-noise-pilot-v1\', seed=3407,\n                epochs=5, attempts_per_epoch=202, lr=1e-5, optimizer=\'Adam\',\n                betas=[.9, .999], eps=1e-8, weight_decay=0., scheduler=None,\n                batch_size=1, workers=0, sampling_policy=\'balanced50_v1\',\n                lambda_rec=1., lambda_seg=1e-4, stage_decay=.7,\n                crop_size=256, train_counts_per_epoch={\'clean\':101, \'noise40\':51, \'noise30\':50},\n                guard=\'maximum(E+a,E)\', training_mask=\'original crop_mask SSR\',\n                starting_epoch=441, optimizer_state=\'fresh for both arms\',\n                endpoint=\'fixed fifth pilot epoch; no best-epoch selection\',\n                evaluation_split=\'val\', test_evaluated=False)\n\n\ndef main():\n    parser = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\', \'expected\'):\n        parser.add_argument(\'--\'+key, type=Path, required=True)\n    args = parser.parse_args()\n    sys.path.insert(0, str(args.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import prep_loaders, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, crop_mask, set_seed, Metrics_Rec, Metrics_Seg\n    from run_public252 import validate\n\n    ref = json.loads(args.reference.read_text())\n    expected = json.loads(args.expected.read_text())\n    for path, key in [(args.checkpoint, \'checkpoint_sha256\'),\n                      (args.code/\'mask/mask512x512.mat\', \'mask_sha256\'),\n                      (args.code/\'public252-v1.json\', \'protocol_sha256\')]:\n        assert sha(path) == ref[key], str(path)\n    for name, digest in expected[\'code_hashes\'].items():\n        assert sha(args.code/name) == digest, \'Training source changed: \'+name\n    validate(args.data, json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    args.out.mkdir(parents=True, exist_ok=False)\n    manifest = dict(status=\'running\', protocol=PROTOCOL, reference=ref,\n                    torch=str(torch.__version__), gpu=torch.cuda.get_device_name(0),\n                    script_hashes={name:sha(Path(__file__).with_name(name)) for name in\n                                   (\'noise_training_pilot.py\',\'pilot_support.py\',\'robustness_inputs.py\',\'operator_control.py\')},\n                    code_hashes=expected[\'code_hashes\'], completed_epochs=0,\n                    scope=\'Paired noise adaptation on existing development split. Not from-scratch, not test performance. Both arms receive augmentation; no separate augmentation-only causal claim.\')\n    def save_manifest():\n        (args.out/\'experiment.json\').write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    started = time.time()\n    try:\n        set_seed(3407)\n        train, val = prep_loaders(str(args.data), batch_size=1, workers=0,\n                                 transpose_image=True, sampling_policy=\'balanced50_v1\')\n        assert len(train) == 202 and list(map(str, val.dataset.names)) == ref[\'scenes\']\n        assert set(train.dataset.names).isdisjoint(val.dataset.names)\n        models = {arm:model_generator(\'CRSDUN\',28,23,str(args.checkpoint)) for arm in ARMS}\n        assert all(torch.equal(v, models[\'guarded\'].state_dict()[k]) for k,v in models[\'control\'].state_dict().items())\n        optimizers = {arm:torch.optim.Adam(models[arm].parameters(), lr=1e-5) for arm in ARMS}\n        scalers = {arm:torch.amp.GradScaler(\'cuda\') for arm in ARMS}\n        counters = {arm:UpdateCounter(optimizers[arm]) for arm in ARMS}\n        assert all(not optimizer.state for optimizer in optimizers.values())\n        phi, nominal = init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n        mask = torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'], dtype=torch.float32, device=\'cuda\')\n        assert all(torch.equal(a,b) for a,b in zip(make_operator(mask), nominal))\n        summaries = []\n        scenes = list(map(str, val.dataset.names))\n\n        def evaluate(phase, conditions):\n            saved_rng = rng_state()\n            for model in models.values(): model.eval()\n            try:\n                with torch.inference_mode():\n                    for name, dx, alpha, snr in conditions:\n                        folder = args.out/phase/name\n                        folder.mkdir(parents=True)\n                        op = make_operator(mask if not dx else mix_mask(mask,dx,alpha))\n                        seg = {a:Metrics_Seg(23,get_class_names()) for a in ARMS}\n                        rec = {a:Metrics_Rec() for a in ARMS}\n                        rows = []\n                        for index, sample in enumerate(val):\n                            target = sample[\'image\'].float().cuda()\n                            truth = sample[\'label\'].numpy()[0]\n                            y, info = add_noise(init_meas(target,op[1],\'Y\'),scenes[index],dx,alpha,snr)\n                            yhash = tensor_sha(y)\n                            for arm in ARMS:\n                                with TrainingGuard(models[arm]) if arm == \'guarded\' else nullcontext():\n                                    images, logits = models[arm](y,op)\n                                assert all(bool(torch.isfinite(t).all()) for t in [*images,*logits])\n                                pred = logits[-1].argmax(1).cpu().numpy()[0]\n                                hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                                np.save(folder/f\'{arm}_{scenes[index]}_confusion.npy\', hist)\n                                one = Metrics_Rec();one.add_batch(target.cpu(),images[-1].cpu())\n                                values = one.get_table().iloc[0].to_dict()\n                                seg[arm].add_batch(truth[None],pred[None])\n                                for attr in (\'psnr\',\'ssim\',\'mse\',\'count\'):\n                                    setattr(rec[arm],attr,getattr(rec[arm],attr)+getattr(one,attr))\n                                if phase == \'initial\' and name == \'clean\':\n                                    prior = expected[\'scenes\'][arm][scenes[index]]\n                                    assert abs(values[\'PSNR\']-prior[\'PSNR\']) < 1e-4\n                                    assert hashlib.sha256(hist.astype(\'<i8\').tobytes()).hexdigest() == prior[\'confusion_sha256\']\n                                assert tensor_sha(y) == yhash\n                                rows.append(dict(scene=scenes[index], arm=arm, measurement_sha256=yhash, **info, **values))\n                                del images, logits\n                            del target, y\n                            if (index+1)%5 == 0: print(f\'{phase} {name}: {index+1}/25 pairs\',flush=True)\n                        pd.DataFrame(rows).to_csv(folder/\'scenes.csv\',index=False)\n                        for arm in ARMS:\n                            table = seg[arm].get_table()\n                            table.to_csv(folder/f\'{arm}_classes.csv\')\n                            np.save(folder/f\'{arm}_confusion.npy\',seg[arm].confusion_matrix)\n                            row = dict(phase=phase,condition=name,arm=arm,\n                                       miou=float(table.loc[\'total(-bg)\',\'IoU\']),**rec[arm].get_table().iloc[0].to_dict())\n                            # Same fixed scene/noise draws as the preceding frozen experiment.\n                            if phase == \'initial\':\n                                prior = expected[\'robustness\'][name][arm]\n                                assert abs(row[\'miou\']-prior[\'foreground_miou_all22\']) < 1e-8\n                                assert abs(row[\'PSNR\']-prior[\'PSNR\']) < 1e-4\n                            summaries.append(row)\n                            print(row,flush=True)\n                        pd.DataFrame(summaries).to_csv(args.out/\'evaluation_summary.csv\',index=False)\n            finally:\n                restore_rng(saved_rng)\n\n        evaluate(\'initial\',[c for c in CONDITIONS if c[0] in (\'clean\',\'nominal_noise30\')])\n        # Model construction and validation must not affect the training input sequence.\n        set_seed(3407)\n        epochs = []\n        with (args.out/\'training_inputs.jsonl\').open(\'w\') as audit:\n            for epoch in range(1,6):\n                epoch_start = time.time()\n                torch.cuda.reset_peak_memory_stats()\n                for model in models.values(): model.train()\n                schedule = noise_schedule(epoch)\n                totals = {a:dict(rec=0.,seg=0.,updates=0,skips=0) for a in ARMS}\n                seen_pixels = np.zeros(23,dtype=np.int64)\n                with TrainingGuard(models[\'guarded\']):\n                    for index,sample in enumerate(train):\n                        target=sample[\'image\'].float().cuda();labels=sample[\'label\'].long().cuda()\n                        seen_pixels += np.bincount(sample[\'label\'].numpy().ravel(),minlength=23)\n                        syn,op=crop_mask(phi,nominal,SimpleNamespace(input_mask=\'SSR\'),28)\n                        snr=None if schedule[index]<0 else float(schedule[index])\n                        scene_index=int(sample[\'sampling_scene_index\'].item())\n                        scene=str(train.dataset.names[scene_index])\n                        key=f\'train-pilot-v1|epoch={epoch}|batch={index}|{scene}\'\n                        y,info=add_noise(init_meas(target,syn,\'Y\'),key,0,0.,snr)\n                        fingerprint=dict(target=tensor_sha(target),label=tensor_sha(labels),\n                                         measurement=tensor_sha(y),operator=[tensor_sha(t) for t in op])\n                        before=rng_state();after_control=None;step={}\n                        for arm in ARMS:\n                            restore_rng(before)\n                            step[arm]=update(models[arm],optimizers[arm],scalers[arm],counters[arm],y,op,target,labels)\n                            after=rng_state()\n                            if arm==\'control\':after_control=after\n                            else:assert same_rng(after_control,after),\'Arms consumed different RNG streams\'\n                            assert fingerprint==dict(target=tensor_sha(target),label=tensor_sha(labels),\n                                                      measurement=tensor_sha(y),operator=[tensor_sha(t) for t in op]),\'Training inputs mutated\'\n                            totals[arm][\'rec\']+=step[arm][\'rec\'];totals[arm][\'seg\']+=step[arm][\'seg\']\n                            totals[arm][\'updates\']+=step[arm][\'updated\'];totals[arm][\'skips\']+=1-step[arm][\'updated\']\n                        audit.write(json.dumps(dict(epoch=epoch,batch=index,scene=scene,\n                                     targeted_class=int(sample[\'sampling_target\'].item()),\n                                     hashes=fingerprint,noise=info,arms=step),allow_nan=False)+\'\\n\')\n                        audit.flush()\n                        del target,labels,y,syn,op\n                        if (index+1)%25==0:print(f\'Pilot epoch{epoch}/5: {index+1}/202 paired updates\',flush=True)\n                assert index+1 == 202\n                for arm in ARMS:\n                    for param in models[arm].parameters():\n                        assert bool(torch.isfinite(param).all()),f\'Nonfinite weights: {arm}\'\n                    totals[arm][\'rec\']/=202;totals[arm][\'seg\']/=202\n                epochs.append(dict(epoch=epoch,arms=totals,class_pixels_seen=seen_pixels.tolist(),\n                                   elapsed_seconds=time.time()-epoch_start,\n                                   peak_cuda_allocated_gib=torch.cuda.max_memory_allocated()/2**30))\n                (args.out/\'training_epochs.json\').write_text(json.dumps(epochs,indent=2))\n                # Joint state saved at an epoch boundary, before any validation. Replaces only this run\'s own previous snapshot.\n                atomic_save(dict(protocol=PROTOCOL,reference=ref,epoch=epoch,rng=rng_state(),\n                                 arms={a:dict(model=models[a].state_dict(),optimizer=optimizers[a].state_dict(),\n                                              scaler=scalers[a].state_dict(),successful_updates=counters[a].count) for a in ARMS},\n                                 training_epochs=epochs),args.out/\'last_pair.pt\')\n                for arm in ARMS:\n                    atomic_save(dict(model=models[arm].state_dict(),pilot_epoch=epoch,arm=arm,\n                                     requires_unit_gain_guard=arm==\'guarded\',protocol=PROTOCOL),args.out/f\'{arm}_last.pth\')\n                manifest[\'completed_epochs\']=epoch;save_manifest()\n                print(epochs[-1],flush=True)\n                if any(totals[a][\'skips\'] > 20 for a in ARMS):\n                    raise RuntimeError(\'Over 20 AMP skips in one epoch: numerical failure; inspect archive before further training\')\n        evaluate(\'final\',CONDITIONS)\n        comparisons=[]\n        for name,_,_,_ in CONDITIONS:\n            for arm in ARMS:\n                final=next(r for r in summaries if r[\'phase\']==\'final\' and r[\'condition\']==name and r[\'arm\']==arm)\n                prior=expected[\'robustness\'][name][arm]\n                comparisons.append(dict(condition=name,arm=arm,final_miou_percent=100*final[\'miou\'],\n                                         change_from_frozen_miou_points=100*(final[\'miou\']-prior[\'foreground_miou_all22\']),\n                                         final_psnr=final[\'PSNR\'],change_from_frozen_psnr=final[\'PSNR\']-prior[\'PSNR\']))\n        pd.DataFrame(comparisons).to_csv(args.out/\'comparison.csv\',index=False)\n        manifest.update(status=\'completed\',successful_updates={a:counters[a].count for a in ARMS},\n                        attempted_updates_per_arm=1010,test_evaluated=False)\n        print(pd.DataFrame(comparisons).to_string(index=False),flush=True)\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save_manifest()\n\nif __name__==\'__main__\':main()\n', 'verify_noise_pilot.py': '"""Small real-model checks, including paired updates and full-state continuation."""\nimport argparse\nimport copy\nimport sys\nimport tempfile\nfrom pathlib import Path\nfrom contextlib import nullcontext\nimport numpy as np\nimport torch\nfrom pilot_support import (TrainingGuard,UpdateCounter,update,noise_schedule,\n                           rng_state,restore_rng,same_rng,atomic_save)\nfrom gain_guard import Guard\nfrom operator_control import make_operator,tensor_sha\nfrom robustness_inputs import add_noise\n\ndef main():\n    p=argparse.ArgumentParser();p.add_argument(\'--code\',required=True);args=p.parse_args()\n    sys.path.insert(0,args.code)\n    from models.CRSDUN import CRSDUN\n    from utils import init_meas,set_seed\n    torch.set_num_threads(1);set_seed(3407)\n    initial=rng_state()\n    for epoch in range(1,6):\n        schedule=noise_schedule(epoch)\n        assert len(schedule)==202 and schedule.count(-1)==101 and schedule.count(40)==51 and schedule.count(30)==50\n        assert schedule==noise_schedule(epoch)\n    assert same_rng(initial,rng_state())\n    d=torch.tensor([.2,2.],requires_grad=True);energy=torch.ones(2)\n    torch.maximum(d,energy).sum().backward()\n    assert torch.equal(d.grad,torch.tensor([0.,1.]))\n    assert torch.cuda.is_available()\n    model=CRSDUN(stage=5,bands=28,n_class=23).cuda()\n    mask=(torch.rand(64,64,device=\'cuda\')>.5).float()\n    op=make_operator(mask);target=torch.rand(1,28,64,64,device=\'cuda\')*.1\n    labels=torch.randint(23,(1,64,64),device=\'cuda\')\n    y,_=add_noise(init_meas(target,op[1],\'Y\'),\'train-pilot-local\',0,0.,30.)\n    fingerprint=[tensor_sha(t) for t in [target,labels,y,*op]]\n    # Force an active floor. The original learned a is tested separately via update below.\n    def force_a(module,args,out):\n        result=out.clone();result[:,0:1]=-.05;return result\n    handles=[m.register_forward_hook(force_a) for m in model.para_est]\n    model.train();state=rng_state();saved=copy.deepcopy(model.state_dict())\n    gradients=[];outputs=[]\n    for context in (Guard(model,lambda row:None),TrainingGuard(model)):\n        model.load_state_dict(saved);model.zero_grad(set_to_none=True);restore_rng(state)\n        with context:\n            xs,ls=model(y,op)\n            outputs.append([tensor_sha(t) for t in [*xs,*ls]])\n            loss=sum(x.square().mean() for x in [*xs,*ls]);loss.backward()\n        gradients.append({n:p.grad.detach().clone() for n,p in model.named_parameters() if p.grad is not None})\n        del xs,ls,loss\n    assert outputs[0]==outputs[1]\n    assert gradients[0].keys()==gradients[1].keys()\n    assert all(torch.equal(gradients[0][n],gradients[1][n]) for n in gradients[0])\n    assert all(bool(torch.isfinite(g).all()) for g in gradients[1].values())\n    del gradients,outputs\n    for handle in handles:handle.remove()\n    model.zero_grad(set_to_none=True)\n    try:\n        with TrainingGuard(model):raise RuntimeError(\'cleanup\')\n    except RuntimeError:pass\n    assert \'forward\' not in model.__dict__\n    # The production update helper and optimizer hook must count real steps.\n    optimizer=torch.optim.Adam(model.parameters(),lr=1e-5)\n    scaler=torch.amp.GradScaler(\'cuda\',init_scale=128.)\n    counter=UpdateCounter(optimizer)\n    with TrainingGuard(model):result=update(model,optimizer,scaler,counter,y,op,target,labels)\n    assert result[\'updated\']==1 and counter.count==1\n    assert fingerprint==[tensor_sha(t) for t in [target,labels,y,*op]]\n    # Save and reproduce the next stochastic training update, including Adam/AMP/RNG.\n    with tempfile.TemporaryDirectory() as folder:\n        path=Path(folder)/\'pair.pt\'\n        atomic_save(dict(model=model.state_dict(),optimizer=optimizer.state_dict(),scaler=scaler.state_dict(),rng=rng_state()),path)\n        with TrainingGuard(model):update(model,optimizer,scaler,counter,y,op,target,labels)\n        after={n:tensor_sha(t) for n,t in model.state_dict().items()};after_rng=rng_state()\n        payload=torch.load(path,weights_only=False,map_location=\'cpu\')\n        model.load_state_dict(payload[\'model\']);optimizer.load_state_dict(payload[\'optimizer\']);scaler.load_state_dict(payload[\'scaler\']);restore_rng(payload[\'rng\'])\n        with TrainingGuard(model):update(model,optimizer,scaler,counter,y,op,target,labels)\n        assert after=={n:tensor_sha(t) for n,t in model.state_dict().items()}\n        assert same_rng(after_rng,rng_state())\n    # AMP overflow must be recorded as a skipped optimizer step.\n    optimizer.zero_grad(set_to_none=True)\n    loss=next(model.parameters()).sum()*float(\'inf\')\n    before=counter.count;scaler.scale(loss).backward();scaler.step(optimizer);scaler.update()\n    assert counter.count==before\n    print(\'PASS: fixed augmentation counts/RNG isolation; active training guard exactly matches archived inference guard outputs AND gradients; floor gradient behavior; real five-stage CUDA Adam update; input immutability; exact model continuation with saved Adam/AMP/RNG; overflow accounting; guard cleanup. Small64x64 synthetic check, not full-frame pilot performance.\')\n\nif __name__==\'__main__\':main()\n', 'robustness_inputs.py': '"""Prespecified new perturbations; the inference rule is not tuned here."""\nimport hashlib, math\nimport torch\n\nCONDITIONS = [\n    (\'clean\', 0, 0., None),\n    (\'plus1_alpha0.5\', 1, .5, None),\n    (\'minus1_alpha0.5\', -1, .5, None),\n    (\'nominal_noise40\', 0, 0., 40.),\n    (\'nominal_noise30\', 0, 0., 30.),\n    (\'plus1_alpha0.25_noise40\', 1, .25, 40.),\n    (\'minus1_alpha0.25_noise40\', -1, .25, 40.),\n]\n\ndef add_noise(y, scene, dx, alpha, snr_db):\n    if snr_db is None:return y,dict(seed=None,requested_snr_db=None,actual_snr_db=None,noise_rms=0.)\n    # Omit SNR from the seed to use the same draw at two noise levels on the same acquisition.\n    key=f\'public252-noise-v1|3407|{scene}|{dx}|{alpha:g}\'\n    seed=int.from_bytes(hashlib.sha256(key.encode()).digest()[:8],\'little\')%(2**63)\n    generator=torch.Generator(device=\'cpu\').manual_seed(seed)\n    draw=torch.randn(y.shape,generator=generator,dtype=torch.float64,device=\'cpu\')\n    signal_rms=float(y.detach().cpu().double().square().mean().sqrt())\n    assert signal_rms>0 and math.isfinite(signal_rms)\n    sigma=signal_rms*10**(-snr_db/20)\n    noise=(draw/draw.square().mean().sqrt()*sigma).to(device=y.device,dtype=y.dtype)\n    noisy=y+noise\n    actual_rms=float((noisy.double()-y.double()).square().mean().sqrt())\n    actual_snr=20*math.log10(signal_rms/actual_rms)\n    assert abs(actual_snr-snr_db)<.001\n    # Decimal string preserves all seed bits when mixed with missing seeds in CSV columns.\n    return noisy,dict(seed=str(seed),requested_snr_db=snr_db,actual_snr_db=actual_snr,noise_rms=actual_rms,signal_rms=signal_rms)\n', 'operator_control.py': '"""Frozen validation: paired nominal/matched operators under synthetic mask mixing."""\nfrom pathlib import Path\nimport argparse\nimport hashlib\nimport json\nimport time\nimport numpy as np\nimport torch\n\nALPHAS = (0.05, 0.10, 0.25, 1.0)\n\ndef sha(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\ndef tensor_sha(x):\n    return hashlib.sha256(x.detach().cpu().contiguous().numpy().tobytes()).hexdigest()\n\ndef mix_mask(mask, dx, alpha):\n    assert mask.ndim == 2 and dx in (-1, 1) and 0 <= alpha <= 1\n    shifted = torch.zeros_like(mask)\n    if dx == 1:\n        shifted[:, 1:] = mask[:, :-1]\n    else:\n        shifted[:, :-1] = mask[:, 1:]\n    return (1-alpha)*mask + alpha*shifted\n\ndef make_operator(mask, bands=28, step=2):\n    h, w = mask.shape\n    phi = mask.new_zeros((1, bands, h, w+(bands-1)*step))\n    for c in range(bands):\n        phi[0, c, :, step*c:step*c+w] = mask\n    back = torch.stack([phi[:, c, :, step*c:step*c+w] for c in range(bands)], dim=1)\n    energy = phi.square().sum(1, keepdim=True)\n    energy = torch.where(energy == 0, torch.ones_like(energy), energy)\n    return back, phi, energy\n\ndef measure(x, phi, step=2):\n    b, c, h, w = x.shape\n    y = x.new_zeros((b, h, phi.shape[-1]))\n    for k in range(c):\n        y[:, :, step*k:step*k+w] += x[:, k]*phi[:, k, :, step*k:step*k+w]\n    return y\n\ndef relative_error(a, b):\n    return float(torch.linalg.vector_norm(a-b)/torch.linalg.vector_norm(b).clamp_min(1e-12))\n\ndef main():\n    import sys\n    p = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\'):\n        p.add_argument(\'--\'+key, type=Path, required=True)\n    a = p.parse_args()\n    sys.path.insert(0, str(a.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, shift_back_mask, Metrics_Rec, Metrics_Seg, set_seed\n    from run_public252 import validate\n\n    ref = json.loads(a.reference.read_text())\n    mask_path = a.code/\'mask/mask512x512.mat\'\n    assert sha(a.checkpoint) == ref[\'checkpoint_sha256\']\n    assert sha(mask_path) == ref[\'mask_sha256\']\n    assert sha(a.code/\'public252-v1.json\') == ref[\'protocol_sha256\']\n    validate(a.data, json.loads((a.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(exist_ok=False, parents=True)\n    set_seed(3407)\n    loader = evaluation_loader(a.data, \'val\', 0, True)\n    scenes = list(map(str, loader.dataset.names))\n    assert sorted(scenes) == sorted(ref[\'scenes\']) and len(scenes) == 25\n    model = model_generator(\'CRSDUN\', 28, 23, str(a.checkpoint))\n    model.eval()\n    physical = torch.as_tensor(loadmat(mask_path)[\'mask\'], dtype=torch.float32, device=\'cuda\')\n    phi, nominal = init_mask(str(mask_path), \'SSR\', 1, 28)\n    built = make_operator(physical)\n    assert all(torch.equal(x, y) for x, y in zip(built, nominal)), \'Nominal SSR tuple differs\'\n    assert all(torch.equal(x, y) for x, y in zip(make_operator(mix_mask(physical, 1, 0)), nominal))\n    nominal_hashes = [tensor_sha(x) for x in nominal]\n    conditions = [(\'clean\', 0, 0.0)] + [(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\', dx, alpha) for alpha in ALPHAS for dx in (1, -1)]\n    manifest = dict(status=\'running\', checkpoint_epoch=441, checkpoint_sha256=sha(a.checkpoint),\n                    protocol_sha256=ref[\'protocol_sha256\'], mask_sha256=sha(mask_path),\n                    script_sha256=sha(__file__), scenes=scenes, alphas=list(ALPHAS),\n                    conditions=conditions, completed_conditions=[], torch=str(torch.__version__),\n                    gpu=torch.cuda.get_device_name(0), expected_model_forwards=425,\n                    test_evaluated=False, training=False,\n                    scope=\'25 validation scenes; frozen model; identical measurement reused for nominal and matched full SSR tuples.\',\n                    caveat=\'Linear mask mixing with a zero-filled +/-1px shift is synthetic, not calibrated hardware motion. Matched masks may still be outside the training distribution.\',\n                    metrics=\'Every-stage confusion/MSE/PSNR_ref1; SSIM_ref1 final stage only. Scene-averaged reconstruction metrics; aggregate confusion mIoU.\')\n    manifest_path = a.out/\'experiment.json\'\n    def save_manifest():\n        manifest_path.write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    summary, severity_rows = [], []\n    started = time.time()\n    try:\n      with torch.inference_mode():\n        for name, dx, alpha in conditions:\n            folder = a.out/name\n            folder.mkdir()\n            mixed = physical if name == \'clean\' else mix_mask(physical, dx, alpha)\n            matched = make_operator(mixed)\n            acquisition = matched[1]\n            assert torch.equal(matched[0], shift_back_mask(acquisition))\n            expected_energy = acquisition.square().sum(1, keepdim=True)\n            expected_energy[expected_energy == 0] = 1\n            assert torch.equal(matched[2], expected_energy)\n            paired_ops = [(\'nominal\', nominal)] if name == \'clean\' else [(\'nominal\', nominal), (\'matched\', matched)]\n            severity_rows.append(dict(condition=name, dx=dx, alpha=alpha,\n                                      mask_relative_error=relative_error(mixed, physical),\n                                      changed_fraction=float((mixed != physical).float().mean()),\n                                      mean_transmittance=float(mixed.mean())))\n            pd.DataFrame(severity_rows).to_csv(a.out/\'mask_severity.csv\', index=False)\n            seg = {mode: [Metrics_Seg(23, get_class_names()) for _ in range(5)] for mode, _ in paired_ops}\n            records = []\n            for index, sample in enumerate(loader):\n                scene = scenes[index]\n                target = sample[\'image\'].float().cuda()\n                gt_cpu = target.cpu()\n                truth = sample[\'label\'].numpy()[0]\n                y = init_meas(target, acquisition, \'Y\')\n                if index == 0:\n                    assert torch.allclose(measure(target, acquisition), y, atol=1e-6, rtol=1e-6)\n                y_nominal = init_meas(target, phi, \'Y\')\n                measurement_error = relative_error(y, y_nominal)\n                y_digest = tensor_sha(y)\n                for mode, operator in paired_ops:\n                    op_hashes = [tensor_sha(x) for x in operator]\n                    xs, logits = model(y, operator)\n                    assert len(xs) == len(logits) == 5\n                    for k, (x, logit) in enumerate(zip(xs, logits), 1):\n                        assert x.shape == target.shape and logit.shape == (1, 23, *truth.shape)\n                        assert torch.isfinite(x).all() and torch.isfinite(logit).all(), f\'Nonfinite: {name}/{mode}/{scene}/stage{k}\'\n                        x_cpu = x.float().cpu()\n                        pred = logit.argmax(1).cpu().numpy()[0]\n                        hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                        np.save(folder/f\'{mode}_{scene}_stage{k}_confusion.npy\', hist)\n                        seg[mode][k-1].add_batch(truth[None], pred[None])\n                        mse = float((x_cpu-gt_cpu).square().mean())\n                        metrics = {\'MSE\':mse, \'PSNR\':float(-10*torch.log10(torch.tensor(mse))), \'SSIM\':None}\n                        if k == 5:\n                            rec = Metrics_Rec()\n                            rec.add_batch(gt_cpu, x_cpu)\n                            metrics = rec.get_table().iloc[0].to_dict()\n                        records.append(dict(condition=name, mode=mode, scene=scene, stage=k,\n                                            dx=dx, alpha=alpha, measurement_sha256=y_digest,\n                                            measurement_relative_error=measurement_error, **metrics))\n                    assert tensor_sha(y) == y_digest, \'Measurement mutated during inference\'\n                    assert [tensor_sha(t) for t in operator] == op_hashes, \'SSR tuple mutated\'\n                    del xs, logits, x, logit, x_cpu\n                pd.DataFrame(records).to_csv(folder/\'per_scene_stage_metrics.csv\', index=False)\n                del target, gt_cpu, y, y_nominal\n                print(f\'{name}: {index+1}/25; modes={len(paired_ops)}; elapsed={(time.time()-started)/60:.1f}min\', flush=True)\n            assert [tensor_sha(t) for t in nominal] == nominal_hashes\n            for mode, _ in paired_ops:\n                for k in range(1,6):\n                    acc = seg[mode][k-1]\n                    assert np.array_equal(sum(np.load(folder/f\'{mode}_{s}_stage{k}_confusion.npy\') for s in scenes), acc.confusion_matrix)\n                    np.save(folder/f\'{mode}_stage{k}_aggregate_confusion.npy\', acc.confusion_matrix)\n                    table = acc.get_table()\n                    table.to_csv(folder/f\'{mode}_stage{k}_segmentation.csv\')\n                    items = [r for r in records if r[\'mode\'] == mode and r[\'stage\'] == k]\n                    summary.append(dict(condition=name, mode=mode, stage=k, alpha=alpha, dx=dx,\n                                        foreground_miou_all22=float(table.loc[\'total(-bg)\', \'IoU\']),\n                                        PSNR=float(np.mean([r[\'PSNR\'] for r in items])),\n                                        MSE=float(np.mean([r[\'MSE\'] for r in items])),\n                                        SSIM=float(np.mean([r[\'SSIM\'] for r in items])) if k == 5 else None))\n            pd.DataFrame(summary).to_csv(a.out/\'stage_summary.csv\', index=False)\n            if name == \'clean\':\n                final = summary[-1]\n                check = dict(miou_difference=final[\'foreground_miou_all22\']-ref[\'miou\'], psnr_difference=final[\'PSNR\']-ref[\'psnr\'])\n                check[\'passed\'] = abs(check[\'miou_difference\']) < 1e-6 and abs(check[\'psnr_difference\']) < 1e-4\n                (a.out/\'clean_equivalence.json\').write_text(json.dumps(check, indent=2))\n                assert check[\'passed\'], \'Clean check failed; stopping before stresses\'\n            manifest[\'completed_conditions\'].append(name)\n            save_manifest()\n        pairs = []\n        for name, dx, alpha in conditions[1:]:\n            n, m = [next(r for r in summary if r[\'condition\']==name and r[\'mode\']==mode and r[\'stage\']==5) for mode in (\'nominal\', \'matched\')]\n            pairs.append(dict(condition=name, dx=dx, alpha=alpha,\n                              nominal_miou_percent=100*n[\'foreground_miou_all22\'], matched_miou_percent=100*m[\'foreground_miou_all22\'],\n                              matched_minus_nominal_miou_points=100*(m[\'foreground_miou_all22\']-n[\'foreground_miou_all22\']),\n                              nominal_psnr=n[\'PSNR\'], matched_psnr=m[\'PSNR\'], matched_minus_nominal_psnr=m[\'PSNR\']-n[\'PSNR\']))\n        pd.DataFrame(pairs).to_csv(a.out/\'paired_final_summary.csv\', index=False)\n        manifest[\'status\'] = \'completed\'\n        print(pd.DataFrame(pairs).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest[\'status\'] = \'failed\'\n        manifest[\'error\'] = repr(exc)\n        raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started\n        save_manifest()\n\nif __name__ == \'__main__\':\n    main()\n', 'numerical_trace.py': '"""Observe frozen CRSDUN through hooks; require exact traced/untraced outputs."""\nimport argparse, json, sys, time\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom operator_control import make_operator, mix_mask, sha, tensor_sha\n\ndef stats(x):\n    a=x.detach().cpu().double().numpy()\n    assert np.isfinite(a).all(), \'Nonfinite tensor in trace\'\n    return dict(min=float(a.min()),max=float(a.max()),rms=float(np.sqrt(np.mean(a*a))),max_abs=float(np.abs(a).max()))\n\ndef denominator_stats(d):\n    r=stats(d); a=d.detach().cpu().double().numpy()\n    r.update(min_abs=float(np.abs(a).min()),min_abs_index=[int(i) for i in np.unravel_index(np.abs(a).argmin(),a.shape)],nonpositive=int((a<=0).sum()),elements=int(a.size))\n    for limit in (1e-6,1e-4,1e-2,.1):r[f\'abs_below_{limit:g}\']=int((np.abs(a)<limit).sum())\n    return r\n\ndef spatial_error(x, target, aligned_energy):\n    delta=x.detach().cpu().double().numpy()-target\n    sq=delta[0]**2\n    h,w=sq.shape[-2:]\n    border=np.ones((h,w),dtype=bool)\n    border[16:-16,16:-16]=False\n    regions={\'image_border16\':np.broadcast_to(border,sq.shape),\'image_interior\':np.broadcast_to(~border,sq.shape)}\n    regions.update({\'energy_zero\':aligned_energy==0,\'energy_0_to_0.1\':(aligned_energy>0)&(aligned_energy<=.1),\n                    \'energy_0.1_to_1\':(aligned_energy>.1)&(aligned_energy<=1),\n                    \'energy_1_to_4\':(aligned_energy>1)&(aligned_energy<=4),\'energy_above4\':aligned_energy>4})\n    total=float(sq.sum()); result={}\n    for name,mask in regions.items():\n        n=int(mask.sum()); s=float(sq[mask].sum())\n        result[name]=dict(voxels=n,squared_error_sum=s,mse=s/n if n else None,fraction_total_error=s/total if total else 0.)\n    return dict(mse=float(sq.mean()),total_squared_error=total,regions=result)\n\nclass Observer:\n    def __init__(self,model,operator,target,emit,measurement=None):\n        self.model=model;self.operator=operator;self.target=target.detach().cpu().double().numpy();self.emit=emit\n        self.stage=0;self.handles=[];self.original_phif=model.mul_Phif;self.original_phit=model.mul_PhiTg\n        self.measurement=measurement\n        self.had_phif=\'mul_Phif\' in model.__dict__;self.had_phit=\'mul_PhiTg\' in model.__dict__\n        _,bands,h,w=target.shape\n        raw=operator[1].square().sum(1)[0]\n        self.aligned_energy=torch.stack([raw[:,2*c:2*c+w] for c in range(bands)]).cpu().numpy()\n\n    def record(self,event,x,error=False,**extra):\n        row=dict(stage=self.stage,event=event,values=stats(x),**extra)\n        if error:row[\'reconstruction_error\']=spatial_error(x,self.target,self.aligned_energy)\n        self.emit(row)\n\n    def __enter__(self):\n        def para_hook(module,args,out):\n            self.stage+=1\n            p=out.detach().cpu().flatten().tolist()\n            assert len(p)==4\n            self.emit(dict(stage=self.stage,event=\'parameters\',a=p[0],mu=p[1],b=p[2],gamma=p[3],\n                           denominator=denominator_stats(self.operator[2]+out[:,0:1])))\n        def phif(phi,x):\n            self.record(\'x_new_before_data_consistency\',x,error=True)\n            result=self.original_phif(phi,x)\n            self.record(\'predicted_measurement\',result)\n            if self.measurement is not None:self.record(\'measurement_residual\',self.measurement.unsqueeze(1)-result)\n            return result\n        def phit(phi,g):\n            self.record(\'residual_divided_by_denominator\',g)\n            result=self.original_phit(phi,g)\n            self.record(\'data_consistency_correction\',result)\n            return result\n        self.model.mul_Phif=phif;self.model.mul_PhiTg=phit\n        for module in self.model.para_est:self.handles.append(module.register_forward_hook(para_hook))\n        for k in range(self.model.stage):\n            self.handles.append(self.model.net_stage[3*k].register_forward_pre_hook(lambda m,args:self.record(\'z_before_reconstruction_attention\',args[0],error=True)))\n            self.handles.append(self.model.net_stage[3*k].register_forward_hook(lambda m,args,out:self.record(\'after_reconstruction_attention\',out,error=True)))\n            self.handles.append(self.model.net_stage[3*k+1].register_forward_hook(lambda m,args,out:self.record(\'after_refinement\',out,error=True)))\n        return self\n\n    def __exit__(self,*exc):\n        for h in self.handles:h.remove()\n        if self.had_phif:self.model.mul_Phif=self.original_phif\n        else:del self.model.mul_Phif\n        if self.had_phit:self.model.mul_PhiTg=self.original_phit\n        else:del self.model.mul_PhiTg\n\ndef main():\n    p=argparse.ArgumentParser()\n    for name in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+name,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    from scipy.io import loadmat\n    import pandas as pd\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    conditions=[(\'clean\',0,0.)]+[(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\',dx,alpha) for alpha in (.1,.25,1.) for dx in (1,-1)]\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],mask_sha256=ref[\'mask_sha256\'],script_sha256=sha(__file__),helper_sha256=sha(Path(__file__).with_name(\'operator_control.py\')),scenes=scenes,conditions=conditions,completed_conditions=[],completed_identity_pairs=0,training=False,test_evaluated=False,expected_forwards=350,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'Matched operators only. Every traced forward paired with an uninstrumented forward; all five reconstruction/logit tensors must hash identically. Regions are image-border16 and raw detector-energy bins aligned to each spectral voxel, not calibrated hardware regions.\')\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];scene_metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha in conditions:\n            operator=make_operator(mask if not dx else mix_mask(mask,dx,alpha))\n            op_hash=[tensor_sha(t) for t in operator]\n            accumulator=Metrics_Seg(23,get_class_names());rec=Metrics_Rec()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                y=init_meas(target,operator[1],\'Y\');yh=tensor_sha(y)\n                xs,ls=model(y,operator)\n                baseline=[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n                def emit(row):\n                    f.write(json.dumps(dict(condition=name,scene=scene,**row),allow_nan=False)+\'\\n\')\n                with Observer(model,operator,target,emit,measurement=y) as observer:xs,ls=model(y,operator)\n                f.flush()\n                assert observer.stage==5\n                equal=baseline==[tensor_sha(t) for t in [*xs,*ls]]\n                checks.append(dict(condition=name,scene=scene,all_stage_tensors_bitwise_identical=equal))\n                (args.out/\'identity_checks.json\').write_text(json.dumps(checks,indent=2))\n                assert equal,\'Instrumentation altered predictions\'\n                assert tensor_sha(y)==yh and [tensor_sha(t) for t in operator]==op_hash\n                one=Metrics_Rec();one.add_batch(target.cpu(),xs[-1].cpu())\n                metric=one.get_table().iloc[0].to_dict()\n                e=expected[\'scenes\'][name][scene]\n                assert abs(metric[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(metric[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Prior scene metrics not reproduced\'\n                for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec,field,getattr(rec,field)+getattr(one,field))\n                pred=ls[-1].argmax(1).cpu().numpy()[0];accumulator.add_batch(truth[None],pred[None])\n                hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                assert __import__(\'hashlib\').sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Prior scene confusion differs\'\n                scene_metrics.append(dict(condition=name,scene=scene,**metric));pd.DataFrame(scene_metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                manifest[\'completed_identity_pairs\']+=1;save()\n                del xs,ls,target,y\n                print(f\'{name}: {index+1}/25, traced/untraced identical, prior metrics reproduced; {(time.time()-started)/60:.1f}min\',flush=True)\n            table=accumulator.get_table();row=dict(condition=name,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec.get_table().iloc[0].to_dict())\n            e=expected[\'summary\'][name]\n            assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n            summaries.append(row);pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            table.to_csv(args.out/f\'{name}_segmentation.csv\');np.save(args.out/f\'{name}_confusion.npy\',accumulator.confusion_matrix)\n            manifest[\'completed_conditions\'].append(name);save()\n        manifest[\'status\']=\'completed\'\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'gain_guard.py': '"""Fixed energy floor for an isolated data-consistency gain bound; not whole-network stability."""\nimport inspect, textwrap, types\nimport torch\nfrom numerical_trace import denominator_stats\n\nFACTOR = 1.0\n\ndef safe_denominator(d, energy):\n    return torch.maximum(d, FACTOR*energy)\n\nclass Guard:\n    def __init__(self, model, emit, enabled=True):\n        self.model=model;self.emit=emit;self.enabled=enabled;self.stage=0;self.total_activated=0\n        self.had_forward=\'forward\' in model.__dict__;self.original=model.forward\n        assert not hasattr(model,\'_guard_denominator\')\n        source=textwrap.dedent(inspect.getsource(self.original.__func__))\n        old=\'torch.div(y - A_x_phitheta, PhiPhiT + a)\'\n        assert source.count(old)==1, \'Unexpected forward source; do not patch\'\n        source=source.replace(old,\'torch.div(y - A_x_phitheta, self._guard_denominator(PhiPhiT + a, PhiPhiT))\')\n        namespace=dict(self.original.__func__.__globals__)\n        exec(compile(source,\'<source-pinned-denominator-guard>\',\'exec\'),namespace)\n        self.patched=types.MethodType(namespace[\'forward\'],model)\n\n    def __enter__(self):\n        def apply(d,energy):\n            self.stage+=1\n            used=safe_denominator(d,energy) if self.enabled else d\n            count=int((used!=d).sum());self.total_activated+=count\n            gain=energy/used\n            if self.enabled:assert bool((gain>=0).all() and (gain<=1).all()), \'Gain bound violated\'\n            self.emit(dict(stage=self.stage,event=\'denominator_guard\',enabled=self.enabled,factor=FACTOR,\n                           activated=count,elements=d.numel(),guarded_energy_gain_min=float(gain.min()),guarded_energy_gain_max=float(gain.max()),original=denominator_stats(d),used=denominator_stats(used)))\n            return used\n        self.model._guard_denominator=apply;self.model.forward=self.patched\n        return self\n\n    def __exit__(self,*exc):\n        del self.model._guard_denominator\n        if self.had_forward:self.model.forward=self.original\n        else:del self.model.forward\n'}
REFERENCE={'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}
EXPECTED={'source_archive': 'gain_bound_epoch441_20261011_093437_032153.zip', 'source_archive_sha256': '58bba27c6a9ed3d95bcf65ef1c3d1431bf788aaa52315837e7b558dee94c221e', 'summary': {'control': {'foreground_miou_all22': 0.7876837070566084, 'PSNR': 39.00684585571289, 'MSE': 0.0001312368325307034, 'SSIM': 0.9747850584983826}, 'guarded': {'foreground_miou_all22': 0.7887498949606914, 'PSNR': 39.08712356567383, 'MSE': 0.00012905740935821087, 'SSIM': 0.9754946565628052}}, 'scenes': {'control': {'2021-11-03_046': {'PSNR': 39.89459228515625, 'MSE': 0.00010245675366604701, 'confusion_sha256': '9a717b84a51b72b2fba1c9060dfc8ad32d2508a3c8f0eb98494f1809757909ec'}, '2021-11-03_047': {'PSNR': 38.86285400390625, 'MSE': 0.00012993150448892266, 'confusion_sha256': '919915901d083e6ed85b8577721c7392ee968a7d23b41b7d6df5407226b34d16'}, '2021-11-03_057': {'PSNR': 37.99570083618164, 'MSE': 0.00015864626038819551, 'confusion_sha256': '711f63aea60da1ad3e5dd583c1ad6c185b62eb8ead7661faab625fefc9a93000'}, '2021-11-03_085': {'PSNR': 40.45058059692383, 'MSE': 9.01449893717654e-05, 'confusion_sha256': 'f26712d2687056e1f8812c93a119dc945e55a6c1c3a465d8c75b9e4e89c4cfdd'}, '2021-11-03_090': {'PSNR': 40.33523178100586, 'MSE': 9.257133206119761e-05, 'confusion_sha256': 'ce95968be99e39136bb3a54ba923ea41501fa0803c75a0bae08d8bd21e2de7ec'}, '2021-11-03_110': {'PSNR': 39.576499938964844, 'MSE': 0.00011024273408111185, 'confusion_sha256': '925537ac21544cbbed2767f15ad85fa1c7a52691dc70e7712568c6260f9b2c13'}, '2021-11-04_010': {'PSNR': 37.1390495300293, 'MSE': 0.00019323908782098442, 'confusion_sha256': 'c9099b0d0a570152439bb9708c16c6f9882d2b9d23632b94de45b23e5e2e145b'}, '2021-11-04_017': {'PSNR': 38.54598617553711, 'MSE': 0.00013976586342323571, 'confusion_sha256': 'dcdfe2f5a2ef36a30df2960ae7f34537645c5ef3070a89e09ec06fe7708f669c'}, '2021-11-04_024': {'PSNR': 38.70061111450195, 'MSE': 0.00013487727846950293, 'confusion_sha256': 'e3082e8a5aee905c21b646233bda5e8f37889d2ec740925842e5389426415656'}, '2021-11-04_042': {'PSNR': 40.50850296020508, 'MSE': 8.89507427928038e-05, 'confusion_sha256': '69745abc94ea2ee55b0aac789679b0353d08f391c931258e232dd465690d7f22'}, '2021-11-04_047': {'PSNR': 40.220394134521484, 'MSE': 9.505181515123695e-05, 'confusion_sha256': 'b6c73d3bec5395b68de7c48614e082e1c36f6330ee46719b20947da3f4c25bbc'}, '2021-11-04_049': {'PSNR': 40.831241607666016, 'MSE': 8.258013986051083e-05, 'confusion_sha256': 'b63f6d857eeb2b1870346a4ecb5c3594f5dea62fefe6262ece4344a65a2791c2'}, '2021-11-04_055': {'PSNR': 40.75486373901367, 'MSE': 8.404529944527894e-05, 'confusion_sha256': '995f147be920d56d9ba740f6ec33fd436afc5e1a8eaad452b5dcaa746edd9834'}, '2021-11-04_061': {'PSNR': 40.68517303466797, 'MSE': 8.540487760910764e-05, 'confusion_sha256': '59adfbe1bb34d1890af5029d8bd8281620d18396e9b876be0e4f6e4f6f5d2596'}, '2021-11-04_093': {'PSNR': 39.08949661254883, 'MSE': 0.00012332471669651568, 'confusion_sha256': '6366ce691015ac82a2669684a1c4d681bff89544f92fab6972d817ea7e7d7b2c'}, '2021-11-04_098': {'PSNR': 39.36787414550781, 'MSE': 0.00011566773900995031, 'confusion_sha256': '6d227838a684f6f312e50afa89da8c8623ad19564835045da03dc93a2bdabdea'}, '2021-11-05_010': {'PSNR': 37.41633987426758, 'MSE': 0.0001812866685213521, 'confusion_sha256': '13b3bae21986dd485dbe9125a904ee039a7d076c7e1aa9a2c19c4a8317eeee6f'}, '2021-11-05_024': {'PSNR': 39.7016716003418, 'MSE': 0.00010711063077906147, 'confusion_sha256': 'df5555f991ede7f38186ff4cbfe4dca368ad0ff0bfba94e2cb5e5ae992659d4f'}, '2021-11-05_035': {'PSNR': 38.78630065917969, 'MSE': 0.00013224220310803503, 'confusion_sha256': '7642e43435e57e4c293c5497b3ed47fdf0830fab3a34010f983d393ff6f79224'}, '2021-11-05_041': {'PSNR': 38.4978141784668, 'MSE': 0.00014132481010165066, 'confusion_sha256': 'cee79d0f10b1a368417af8ec32939e69ccfc5a1d5d4b70c9727535b9fe968e3b'}, '2021-11-05_046': {'PSNR': 36.10015869140625, 'MSE': 0.0002454617933835834, 'confusion_sha256': '99ceb435926731d4d7593346568ef795f28ff326dcb5a775f1f9fe1af0388e31'}, '2021-11-10_014': {'PSNR': 38.25468063354492, 'MSE': 0.00014946238661650568, 'confusion_sha256': '700d7bfb7ee77774c754fa984c10b556125d20f7eb11ce8f8fea4055a35c9fc2'}, '2021-11-10_024': {'PSNR': 37.73176193237305, 'MSE': 0.00016858673188835382, 'confusion_sha256': '32c9dfe5fd11c769fdd29d729a4cc2575d048096185fe33c83c76f035d77b383'}, '2021-11-10_029': {'PSNR': 38.25230407714844, 'MSE': 0.00014954422658775002, 'confusion_sha256': '55b866708c3de1af700fe8c596c4acee41e9c60fc89886eb282486f138541098'}, '2021-11-10_050': {'PSNR': 37.47146224975586, 'MSE': 0.00017900022794492543, 'confusion_sha256': 'ffff7a303633916099bc9025d29370aab79abad5f287f2f452f346467e5b0f9a'}}, 'guarded': {'2021-11-03_046': {'PSNR': 39.962379455566406, 'MSE': 0.0001008699691738002, 'confusion_sha256': '374f3a7a88d8f8cda10ff9b6e33ece2beebedf7b8a18648e0fdd0fd9008b899a'}, '2021-11-03_047': {'PSNR': 38.931861877441406, 'MSE': 0.00012788323510903865, 'confusion_sha256': '0e5826e07647666e0a58af34c68eeee921f33213f9036e659f2bd74941113673'}, '2021-11-03_057': {'PSNR': 38.056732177734375, 'MSE': 0.00015643230290152133, 'confusion_sha256': 'e632f0ad7bff87592d55c39978b1bfb65d857589b277bf49757c151f6c358b43'}, '2021-11-03_085': {'PSNR': 40.56583023071289, 'MSE': 8.778433402767405e-05, 'confusion_sha256': '842c3e80b60a7b2ecac3e329e85798ddff4567c0fe1592e3d85545a722d58d0b'}, '2021-11-03_090': {'PSNR': 40.435272216796875, 'MSE': 9.046330524142832e-05, 'confusion_sha256': '209f23854013a461b5fb508754297bb853090446c24aecb2903be1ea92ec312c'}, '2021-11-03_110': {'PSNR': 39.70124053955078, 'MSE': 0.00010712122457334772, 'confusion_sha256': 'dc7429aad3c4721656de72d138f77f572bc00c6fe27173c34833c457553bc9d9'}, '2021-11-04_010': {'PSNR': 37.16178512573242, 'MSE': 0.00019223005801904947, 'confusion_sha256': '56558d4b7f070f234e77cf7ae52897b31f3525aff68940d220e84780e2e9f8a5'}, '2021-11-04_017': {'PSNR': 38.585121154785156, 'MSE': 0.00013851208495907485, 'confusion_sha256': 'b8e69792f730b257540b91a7ad9adfb81a5811ea2d90c530914cfa9368273fdb'}, '2021-11-04_024': {'PSNR': 38.73848342895508, 'MSE': 0.00013370622764341533, 'confusion_sha256': '844b89a123ad0d7705d9624d6d0cc914690124d0cb8171b1c650aa79d92dd40f'}, '2021-11-04_042': {'PSNR': 40.58415222167969, 'MSE': 8.741471538087353e-05, 'confusion_sha256': 'a186add554b815e1981560085145a33acd0bee8132718d2e1a2d0cac0e087350'}, '2021-11-04_047': {'PSNR': 40.28378677368164, 'MSE': 9.367440361529589e-05, 'confusion_sha256': 'cee7f430829b0199aad2d4a448ddf8de62da7c80450f995c696cc85cbd85f09a'}, '2021-11-04_049': {'PSNR': 40.924591064453125, 'MSE': 8.082403655862436e-05, 'confusion_sha256': '73e59e145e8b58c68ce1321b5fa6175893f9bb64936b74993bdc45e0c200b448'}, '2021-11-04_055': {'PSNR': 40.86586380004883, 'MSE': 8.192441600840539e-05, 'confusion_sha256': '191414b6176ae9302113fb5f58f097a6b477978f68e0498efbe6c7ec4a865786'}, '2021-11-04_061': {'PSNR': 40.808006286621094, 'MSE': 8.30231947475113e-05, 'confusion_sha256': 'c7507258d7b67089f8ee761269bad5bf81f59d0e558ad95dee2fe4056a96ba8a'}, '2021-11-04_093': {'PSNR': 39.19356155395508, 'MSE': 0.00012040480214636773, 'confusion_sha256': '8b95877e87ffa23382399a1533c2b2dd7061f2ffc4de90549a11a3b3571346e5'}, '2021-11-04_098': {'PSNR': 39.46736526489258, 'MSE': 0.00011304812505841255, 'confusion_sha256': '426e1afa1a1a82a2c29d95847fdd91c32de632db9dccc566aff8311d80bd8ca4'}, '2021-11-05_010': {'PSNR': 37.46293258666992, 'MSE': 0.00017935209325514734, 'confusion_sha256': '840649f0e14463f1d0b6c3625c81e383ad6898911be94352f7ceaa80fa230b46'}, '2021-11-05_024': {'PSNR': 39.879234313964844, 'MSE': 0.00010281968570780009, 'confusion_sha256': '6b7ece9425b74d81f3e0f5a8b7909df1ed16342fbebdda661a1b5c99ad5f577f'}, '2021-11-05_035': {'PSNR': 38.91636276245117, 'MSE': 0.00012834045628551394, 'confusion_sha256': 'b155132bec9234e755ccd24a5f4ffa35111ce197e9ad5de752accb9b8840364c'}, '2021-11-05_041': {'PSNR': 38.572322845458984, 'MSE': 0.0001389209064655006, 'confusion_sha256': '17f1334b21ebc9b8390c31c3cf725f349a95d21171e276ffc7c1e5bbefa2996b'}, '2021-11-05_046': {'PSNR': 36.126548767089844, 'MSE': 0.00024397484958171844, 'confusion_sha256': 'd5af010297e16ebde959393c4d76806a598cd7749dd54b674db23028ecea6b5f'}, '2021-11-10_014': {'PSNR': 38.300148010253906, 'MSE': 0.00014790569548495114, 'confusion_sha256': '3abc330e9e68de63e0ccaf5741f0e4356380395b9b2613e6c8bf243d274800d2'}, '2021-11-10_024': {'PSNR': 37.78757095336914, 'MSE': 0.00016643419803585857, 'confusion_sha256': 'd775cb05bc1c181c65a84bd9f72df3c8ee00fe213aee042c2f60fe6a501c378b'}, '2021-11-10_029': {'PSNR': 38.35245895385742, 'MSE': 0.0001461348874727264, 'confusion_sha256': '13f17289413e6b4657ca49719ab4e08f63a9b69da6bbb794f72d2b628cdad643'}, '2021-11-10_050': {'PSNR': 37.51447677612305, 'MSE': 0.00017723602650221437, 'confusion_sha256': '3e4aefe4db72b03ef825148e78b764f1aa720d6af1c3793b3e5fca94364e7fcf'}}}, 'guard_sha256': '48101cb5d2076a06fa80e8498eabf8e984968d4c325a12e21c057d43fac4b28d', 'robustness': {'clean': {'control': {'foreground_miou_all22': 0.7876837070566084, 'PSNR': 39.00684585571289, 'SSIM': 0.9747850584983826, 'MSE': 0.0001312368325307034}, 'guarded': {'foreground_miou_all22': 0.7887498949606914, 'PSNR': 39.08712356567383, 'SSIM': 0.9754946565628052, 'MSE': 0.00012905740935821087}}, 'plus1_alpha0.5': {'control': {'foreground_miou_all22': 0.5647271088661402, 'PSNR': 0.3916556143760681, 'SSIM': 0.8857214736938477, 'MSE': 58.45930104374886}, 'guarded': {'foreground_miou_all22': 0.6908954386372597, 'PSNR': 34.08598068237305, 'SSIM': 0.9604343128204346, 'MSE': 0.00040174145251512525}}, 'minus1_alpha0.5': {'control': {'foreground_miou_all22': 0.5563503871713654, 'PSNR': -0.8052236938476562, 'SSIM': 0.8821101069450379, 'MSE': 287.36937010526657}, 'guarded': {'foreground_miou_all22': 0.6938194390069634, 'PSNR': 34.161294555664064, 'SSIM': 0.9607329630851745, 'MSE': 0.0003944522561505437}}, 'nominal_noise40': {'control': {'foreground_miou_all22': 0.7325273426760817, 'PSNR': 35.497581024169925, 'SSIM': 0.937585198879242, 'MSE': 0.0002844788134098053}, 'guarded': {'foreground_miou_all22': 0.7338760569452604, 'PSNR': 35.977481079101565, 'SSIM': 0.942121422290802, 'MSE': 0.0002560655836714432}}, 'nominal_noise30': {'control': {'foreground_miou_all22': 0.5711670433984805, 'PSNR': 28.837772216796875, 'SSIM': 0.8007261395454407, 'MSE': 0.0013138854666613043}, 'guarded': {'foreground_miou_all22': 0.5665660216839814, 'PSNR': 29.583678207397462, 'SSIM': 0.8047116923332215, 'MSE': 0.0011088608880527318}}, 'plus1_alpha0.25_noise40': {'control': {'foreground_miou_all22': 0.6524341609106942, 'PSNR': -10.211109795570373, 'SSIM': 0.8704821372032165, 'MSE': 1084.9545914059877}, 'guarded': {'foreground_miou_all22': 0.693331817932072, 'PSNR': 33.4440625, 'SSIM': 0.9302833604812623, 'MSE': 0.00045696881250478327}}, 'minus1_alpha0.25_noise40': {'control': {'foreground_miou_all22': 0.6513940262041529, 'PSNR': -9.71810763835907, 'SSIM': 0.8675760746002197, 'MSE': 174.94829990327358}, 'guarded': {'foreground_miou_all22': 0.68693355711001, 'PSNR': 33.4321142578125, 'SSIM': 0.9301380276679992, 'MSE': 0.0004576962871942669}}}, 'robustness_archive_sha256': 'ffdb99fff27fe697f7ff23b759599361710f9906852913b081ec17253e0709f0', 'code_hashes': {'models/CRSDUN.py': '57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', 'models/__init__.py': '84190199b5e4155ba534b9d6b5265b295153bec587ecfed3302daa59c0ee85da', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'balanced_sampling.py': 'd3ef24e45e8337a9b2bdbb0eacce532d3441b74f8565e771b36bc2c4e2d6dd19', 'run_public252.py': 'f77e5d5bdc7acc4b9137793cdefd6c04bbe50caf305f80ff65dbd18da531061e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}}

RUN=WORK/('paired_noise_pilot_epoch441_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
for filename,source in FILES.items():(RUN/filename).write_text(source)
(RUN/'reference.json').write_text(json.dumps(REFERENCE,indent=2))
(RUN/'expected.json').write_text(json.dumps(EXPECTED,indent=2))
for filename,expected_hash in EXPECTED['code_hashes'].items():
    assert digest(CODE/filename)==expected_hash, 'Attach the matching BTP-code-sampling.zip: '+filename
print('New paired pilot:',RUN)

New paired pilot: /kaggle/working/paired_noise_pilot_epoch441_20261011_125140_389258

In [7]:
from IPython.display import display,FileLink
try:
    with (RUN/'console.log').open('w') as log:
        check=subprocess.run([sys.executable,'-u',str(RUN/'verify_noise_pilot.py'),'--code',str(CODE)],
                             cwd=CODE,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
        print(check.stdout);log.write(check.stdout);log.flush();check.check_returncode()
        command=[sys.executable,'-u',str(RUN/'noise_training_pilot.py'),
                 '--code',str(CODE),'--data',str(DATA),'--checkpoint',str(CHECKPOINT),
                 '--out',str(RUN/'results'),'--reference',str(RUN/'reference.json'),'--expected',str(RUN/'expected.json')]
        proc=subprocess.Popen(command,cwd=CODE,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)
        try:
            for line in proc.stdout:
                print(line,end='',flush=True)
                log.write(line);log.flush()
            code=proc.wait()
            if code: raise subprocess.CalledProcessError(code,command)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try: proc.wait(timeout=10)
                except subprocess.TimeoutExpired: proc.kill();proc.wait()
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z: assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/kaggle/working/paired_noise_pilot_epoch441_20261011_125140_389258/gain_guard.py:32: UserWarning: Converting a tensor with requires_grad=True to a scalar may lead to unexpected behavior.
Consider using tensor.detach() first. (Triggered internally at /pytorch/torch/csrc/autograd/generated/python_variable_methods.cpp:836.)
  activated=count,elements=d.numel(),guarded_energy_gain_min=float(gain.min()),guarded_energy_gain_max=float(gain.max()),original=denominator_stats(d),used=denominator_stats(used)))
PASS: fixed augmentation counts/RNG isolation; active training guard exactly matches archived inference guard outputs AND gradients; floor gradient behavior; real five-stage CUDA Adam update; input immutability; exact model continuation with saved Adam/AMP/RNG; overflow accounting; guard cleanup. Small64x64 synthetic check, not full-frame pilot performance.

Dataset size (num. batches) 202 25
/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
load model from /kaggle/input/datasets/arnavnigamd/checkpoint18/balanced410_to_epoch500_20261010_094143/model/best_iou.pth
initial clean: 5/25 pairs
initial clean: 10/25 pairs
initial clean: 15/25 pairs
initial clean: 20/25 pairs
initial clean: 25/25 pairs
{'phase': 'initial', 'condition': 'clean', 'arm': 'control', 'miou': 0.7876837070566084, 'PSNR': 39.00684585571289, 'SSIM': 0.9747850584983826, 'MSE': 0.0001312368325307034}
{'phase': 'initial', 'condition': 'clean', 'arm': 'guarded', 'miou': 0.7887498949606914, 'PSNR': 39.08712356567383, 'SSIM': 0.9754946565628052, 'MSE': 0.00012905740935821087}
initial nominal_noise30: 5/25 pairs
initial nominal_noise30: 10/25 pairs
initial nominal_noise30: 15/25 pairs
initial nominal_noise30: 20/25 pairs
initial nominal_noise30: 25/25 pairs
{'phase': 'initial', 'condition': 'nominal_noise30', 'arm': 'control', 'miou': 0.5711670433984805, 'PSNR': 28.837772216796875, 'SSIM': 0.8007261395454407, 'MSE': 0.0013138854666613043}
{'phase': 'initial', 'condition': 'nominal_noise30', 'arm': 'guarded', 'miou': 0.5665660216839814, 'PSNR': 29.583678207397462, 'SSIM': 0.8047116923332215, 'MSE': 0.0011088608880527318}
Pilot epoch1/5: 25/202 paired updates
Pilot epoch1/5: 50/202 paired updates
Pilot epoch1/5: 75/202 paired updates
Pilot epoch1/5: 100/202 paired updates
Pilot epoch1/5: 125/202 paired updates
Pilot epoch1/5: 150/202 paired updates
Pilot epoch1/5: 175/202 paired updates
Pilot epoch1/5: 200/202 paired updates
{'epoch': 1, 'arms': {'control': {'rec': 0.0009457994542617148, 'seg': 0.27442725497012094, 'updates': 202, 'skips': 0}, 'guarded': {'rec': 0.0009399327304125487, 'seg': 0.27420533359935967, 'updates': 202, 'skips': 0}}, 'class_pixels_seen': [11349069, 41170, 50835, 115447, 159125, 101201, 78306, 129356, 148261, 70632, 58269, 57483, 50706, 198162, 105162, 144299, 26761, 81498, 73334, 86834, 50043, 16066, 46253], 'elapsed_seconds': 620.6127004623413, 'peak_cuda_allocated_gib': 7.3096842765808105}
Pilot epoch2/5: 25/202 paired updates
Pilot epoch2/5: 50/202 paired updates
Pilot epoch2/5: 75/202 paired updates
Pilot epoch2/5: 100/202 paired updates
Pilot epoch2/5: 125/202 paired updates
Pilot epoch2/5: 150/202 paired updates
Pilot epoch2/5: 175/202 paired updates
Pilot epoch2/5: 200/202 paired updates
{'epoch': 2, 'arms': {'control': {'rec': 0.0008793220664968134, 'seg': 0.28498980906413923, 'updates': 202, 'skips': 0}, 'guarded': {'rec': 0.0008754798586193315, 'seg': 0.28473204191737245, 'updates': 202, 'skips': 0}}, 'class_pixels_seen': [11275990, 54831, 76964, 114161, 98030, 80711, 81124, 188980, 171071, 90580, 66775, 49634, 67029, 222479, 138662, 90250, 12169, 88460, 74624, 67410, 54848, 15058, 58432], 'elapsed_seconds': 566.2894687652588, 'peak_cuda_allocated_gib': 7.3096842765808105}
Pilot epoch3/5: 25/202 paired updates
Pilot epoch3/5: 50/202 paired updates
Pilot epoch3/5: 75/202 paired updates
Pilot epoch3/5: 100/202 paired updates
Pilot epoch3/5: 125/202 paired updates
Pilot epoch3/5: 150/202 paired updates
Pilot epoch3/5: 175/202 paired updates
Pilot epoch3/5: 200/202 paired updates
{'epoch': 3, 'arms': {'control': {'rec': 0.0008719187796243817, 'seg': 0.2773239424747258, 'updates': 202, 'skips': 0}, 'guarded': {'rec': 0.000868567700758876, 'seg': 0.27706664578417445, 'updates': 202, 'skips': 0}}, 'class_pixels_seen': [11333518, 46476, 51803, 140019, 124957, 102994, 91795, 147034, 139235, 70329, 57425, 57565, 36150, 180304, 136559, 165788, 20246, 88584, 87955, 66213, 38167, 12296, 42860], 'elapsed_seconds': 546.6746065616608, 'peak_cuda_allocated_gib': 7.3096842765808105}
Pilot epoch4/5: 25/202 paired updates
Pilot epoch4/5: 50/202 paired updates
Pilot epoch4/5: 75/202 paired updates
Pilot epoch4/5: 100/202 paired updates
Pilot epoch4/5: 125/202 paired updates
Pilot epoch4/5: 150/202 paired updates
Pilot epoch4/5: 175/202 paired updates
Pilot epoch4/5: 200/202 paired updates
{'epoch': 4, 'arms': {'control': {'rec': 0.0008683369669597596, 'seg': 0.27996897544379873, 'updates': 202, 'skips': 0}, 'guarded': {'rec': 0.0008653554949266283, 'seg': 0.27970472915042743, 'updates': 202, 'skips': 0}}, 'class_pixels_seen': [11299257, 64297, 48786, 124420, 115064, 91475, 64271, 144704, 171065, 76022, 55314, 63839, 57241, 235440, 101705, 133027, 16077, 90279, 69044, 88583, 69492, 13476, 45394], 'elapsed_seconds': 533.574969291687, 'peak_cuda_allocated_gib': 7.3096842765808105}
Pilot epoch5/5: 25/202 paired updates
Pilot epoch5/5: 50/202 paired updates
Pilot epoch5/5: 75/202 paired updates
Pilot epoch5/5: 100/202 paired updates
Pilot epoch5/5: 125/202 paired updates
Pilot epoch5/5: 150/202 paired updates
Pilot epoch5/5: 175/202 paired updates
Pilot epoch5/5: 200/202 paired updates
{'epoch': 5, 'arms': {'control': {'rec': 0.0009095434815937533, 'seg': 0.28772748925603264, 'updates': 202, 'skips': 0}, 'guarded': {'rec': 0.0009051529120217022, 'seg': 0.28737472211665444, 'updates': 202, 'skips': 0}}, 'class_pixels_seen': [11227181, 62676, 54110, 110486, 139386, 90268, 69110, 133253, 207792, 79528, 53390, 28471, 26060, 241641, 161034, 156836, 21844, 101884, 86282, 80921, 52392, 8507, 45220], 'elapsed_seconds': 532.0643355846405, 'peak_cuda_allocated_gib': 7.3096842765808105}
final clean: 5/25 pairs
final clean: 10/25 pairs
final clean: 15/25 pairs
final clean: 20/25 pairs
final clean: 25/25 pairs
{'phase': 'final', 'condition': 'clean', 'arm': 'control', 'miou': 0.7519364625201984, 'PSNR': 39.10392791748047, 'SSIM': 0.9757934999465943, 'MSE': 0.00012969541974598543}
{'phase': 'final', 'condition': 'clean', 'arm': 'guarded', 'miou': 0.7608742886778193, 'PSNR': 39.13199493408203, 'SSIM': 0.9760174512863159, 'MSE': 0.000129022077890113}
final plus1_alpha0.5: 5/25 pairs
final plus1_alpha0.5: 10/25 pairs
final plus1_alpha0.5: 15/25 pairs
final plus1_alpha0.5: 20/25 pairs
final plus1_alpha0.5: 25/25 pairs
{'phase': 'final', 'condition': 'plus1_alpha0.5', 'arm': 'control', 'miou': 0.6108305433887987, 'PSNR': -8.360115586221218, 'SSIM': 0.898580641746521, 'MSE': 1297.8758979836107}
{'phase': 'final', 'condition': 'plus1_alpha0.5', 'arm': 'guarded', 'miou': 0.7079456389518013, 'PSNR': 35.89875946044922, 'SSIM': 0.9714169335365296, 'MSE': 0.0002733888104557991}
final minus1_alpha0.5: 5/25 pairs
final minus1_alpha0.5: 10/25 pairs
final minus1_alpha0.5: 15/25 pairs
final minus1_alpha0.5: 20/25 pairs
final minus1_alpha0.5: 25/25 pairs
{'phase': 'final', 'condition': 'minus1_alpha0.5', 'arm': 'control', 'miou': 0.6038555339521738, 'PSNR': -8.524602682590485, 'SSIM': 0.8977232646942138, 'MSE': 207.66724863171578}
{'phase': 'final', 'condition': 'minus1_alpha0.5', 'arm': 'guarded', 'miou': 0.707570929665001, 'PSNR': 35.93922210693359, 'SSIM': 0.9714727234840393, 'MSE': 0.00027030768687836827}
final nominal_noise40: 5/25 pairs
final nominal_noise40: 10/25 pairs
final nominal_noise40: 15/25 pairs
final nominal_noise40: 20/25 pairs
final nominal_noise40: 25/25 pairs
{'phase': 'final', 'condition': 'nominal_noise40', 'arm': 'control', 'miou': 0.7425885108765347, 'PSNR': 36.98492248535156, 'SSIM': 0.9572081995010376, 'MSE': 0.0002057978417724371}
{'phase': 'final', 'condition': 'nominal_noise40', 'arm': 'guarded', 'miou': 0.7492813688270814, 'PSNR': 37.21837371826172, 'SSIM': 0.9593847608566284, 'MSE': 0.00019602654909249396}
final nominal_noise30: 5/25 pairs
final nominal_noise30: 10/25 pairs
final nominal_noise30: 15/25 pairs
final nominal_noise30: 20/25 pairs
final nominal_noise30: 25/25 pairs
{'phase': 'final', 'condition': 'nominal_noise30', 'arm': 'control', 'miou': 0.6619986868943043, 'PSNR': 32.002398300170896, 'SSIM': 0.8623369836807251, 'MSE': 0.0006352627044543624}
{'phase': 'final', 'condition': 'nominal_noise30', 'arm': 'guarded', 'miou': 0.6653369061227624, 'PSNR': 32.47840354919433, 'SSIM': 0.8674454140663147, 'MSE': 0.0005716667848173529}
final plus1_alpha0.25_noise40: 5/25 pairs
final plus1_alpha0.25_noise40: 10/25 pairs
final plus1_alpha0.25_noise40: 15/25 pairs
final plus1_alpha0.25_noise40: 20/25 pairs
final plus1_alpha0.25_noise40: 25/25 pairs
{'phase': 'final', 'condition': 'plus1_alpha0.25_noise40', 'arm': 'control', 'miou': 0.65971162083755, 'PSNR': 8.18180344581604, 'SSIM': 0.908188099861145, 'MSE': 12.421373179126531}
{'phase': 'final', 'condition': 'plus1_alpha0.25_noise40', 'arm': 'guarded', 'miou': 0.736176400251842, 'PSNR': 34.69092376708984, 'SSIM': 0.948053457736969, 'MSE': 0.00034607998793944716}
final minus1_alpha0.25_noise40: 5/25 pairs
final minus1_alpha0.25_noise40: 10/25 pairs
final minus1_alpha0.25_noise40: 15/25 pairs
final minus1_alpha0.25_noise40: 20/25 pairs
final minus1_alpha0.25_noise40: 25/25 pairs
{'phase': 'final', 'condition': 'minus1_alpha0.25_noise40', 'arm': 'control', 'miou': 0.6698453405543302, 'PSNR': 6.858756275177002, 'SSIM': 0.9090690398216248, 'MSE': 7.831492779795081}
{'phase': 'final', 'condition': 'minus1_alpha0.25_noise40', 'arm': 'guarded', 'miou': 0.7420496756618177, 'PSNR': 34.6731527709961, 'SSIM': 0.9479894161224365, 'MSE': 0.00034700270276516676}
               condition     arm  final_miou_percent  change_from_frozen_miou_points  final_psnr  change_from_frozen_psnr
                   clean control           75.193646                       -3.574724   39.103928                 0.097082
                   clean guarded           76.087429                       -2.787561   39.131995                 0.044871
          plus1_alpha0.5 control           61.083054                        4.610343   -8.360116                -8.751771
          plus1_alpha0.5 guarded           70.794564                        1.705020   35.898759                 1.812779
         minus1_alpha0.5 control           60.385553                        4.750515   -8.524603                -7.719379
         minus1_alpha0.5 guarded           70.757093                        1.375149   35.939222                 1.777928
         nominal_noise40 control           74.258851                        1.006117   36.984922                 1.487341
         nominal_noise40 guarded           74.928137                        1.540531   37.218374                 1.240893
         nominal_noise30 control           66.199869                        9.083164   32.002398                 3.164626
         nominal_noise30 guarded           66.533691                        9.877088   32.478404                 2.894725
 plus1_alpha0.25_noise40 control           65.971162                        0.727746    8.181803                18.392913
 plus1_alpha0.25_noise40 guarded           73.617640                        4.284458   34.690924                 1.246861
minus1_alpha0.25_noise40 control           66.984534                        1.845131    6.858756                16.576864
minus1_alpha0.25_noise40 guarded           74.204968                        5.511612   34.673153                 1.241039
Download this ZIP even if an error occurred: paired_noise_pilot_epoch441_20261011_125140_389258.zip

/kaggle/working/paired_noise_pilot_epoch441_20261011_125140_389258.zip

In [8]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status']=='completed', 'Partial run: download and share the ZIP and error.'
assert manifest['completed_epochs']==5
display(pd.read_csv(RUN/'results/comparison.csv'))
print('Successful updates:',manifest['successful_updates'],'of1010 attempts per arm')
print('Download the paired_noise_pilot_epoch441 ZIP above and share its local path.')

,condition,arm,final_miou_percent,change_from_frozen_miou_points,final_psnr,change_from_frozen_psnr
0,clean,control,75.193646,-3.574724,39.103928,0.097082
1,clean,guarded,76.087429,-2.787561,39.131995,0.044871
2,plus1_alpha0.5,control,61.083054,4.610343,-8.360116,-8.751771
3,plus1_alpha0.5,guarded,70.794564,1.705020,35.898759,1.812779
4,minus1_alpha0.5,control,60.385553,4.750515,-8.524603,-7.719379
5,minus1_alpha0.5,guarded,70.757093,1.375149,35.939222,1.777928
6,nominal_noise40,control,74.258851,1.006117,36.984922,1.487341
7,nominal_noise40,guarded,74.928137,1.540531,37.218374,1.240893
8,nominal_noise30,control,66.199869,9.083164,32.002398,3.164626
9,nominal_noise30,guarded,66.533691,9.877088,32.478404,2.894725
10,plus1_alpha0.25_noise40,control,65.971162,0.727746,8.181803,18.392913
11,plus1_alpha0.25_noise40,guarded,73.617640,4.284458,34.690924,1.246861
12,minus1_alpha0.25_noise40,control,66.984534,1.845131,6.858756,16.576864
13,minus1_alpha0.25_noise40,guarded,74.204968,5.511612,34.673153,1.241039

Successful updates: {'control': 1010, 'guarded': 1010} of1010 attempts per arm
Download the paired_noise_pilot_epoch441 ZIP above and share its local path.

In [9]:
FILES={'pilot_support.py': '"""Fixed training rule, paired randomness and auditable optimizer accounting."""\nimport inspect\nimport random\nimport textwrap\nimport types\nimport numpy as np\nimport torch\n\n\nclass TrainingGuard:\n    """Same maximum as gain_guard.Guard, without synchronizing diagnostic statistics."""\n    def __init__(self, model):\n        self.model = model\n        self.original = model.forward\n        self.had_forward = \'forward\' in model.__dict__\n        source = textwrap.dedent(inspect.getsource(self.original.__func__))\n        old = \'torch.div(y - A_x_phitheta, PhiPhiT + a)\'\n        assert source.count(old) == 1\n        source = source.replace(old, \'torch.div(y - A_x_phitheta, torch.maximum(PhiPhiT + a, PhiPhiT))\')\n        namespace = dict(self.original.__func__.__globals__)\n        exec(compile(source, \'<fixed-unit-gain-training>\', \'exec\'), namespace)\n        self.patched = types.MethodType(namespace[\'forward\'], model)\n\n    def __enter__(self):\n        self.model.forward = self.patched\n        return self\n\n    def __exit__(self, *exc):\n        if self.had_forward:\n            self.model.forward = self.original\n        else:\n            del self.model.forward\n\n\ndef rng_state():\n    return dict(python=random.getstate(), numpy=np.random.get_state(),\n                torch=torch.get_rng_state(), cuda=torch.cuda.get_rng_state_all())\n\n\ndef restore_rng(state):\n    random.setstate(state[\'python\'])\n    np.random.set_state(state[\'numpy\'])\n    torch.set_rng_state(state[\'torch\'])\n    torch.cuda.set_rng_state_all(state[\'cuda\'])\n\n\ndef same_rng(a, b):\n    return (a[\'python\'] == b[\'python\'] and a[\'numpy\'][0] == b[\'numpy\'][0]\n            and np.array_equal(a[\'numpy\'][1], b[\'numpy\'][1])\n            and a[\'numpy\'][2:] == b[\'numpy\'][2:]\n            and torch.equal(a[\'torch\'], b[\'torch\'])\n            and len(a[\'cuda\']) == len(b[\'cuda\'])\n            and all(torch.equal(x, y) for x, y in zip(a[\'cuda\'], b[\'cuda\'])))\n\n\ndef noise_schedule(epoch):\n    # 101 clean, 51 at40dB, 50 at30dB, shuffled independently of training RNG.\n    values = np.array([-1] * 101 + [40] * 51 + [30] * 50)\n    np.random.default_rng(3407 + epoch).shuffle(values)\n    return values.tolist()\n\n\nclass UpdateCounter:\n    def __init__(self, optimizer):\n        self.count = 0\n        self.handle = optimizer.register_step_post_hook(self._increment)\n\n    def _increment(self, *args, **kwargs):\n        self.count += 1\n\n\ndef update(model, optimizer, scaler, counter, measurement, operator, target, labels):\n    optimizer.zero_grad(set_to_none=True)\n    before = counter.count\n    with torch.autocast(device_type=\'cuda\'):\n        images, logits = model(measurement, operator)\n        assert len(images) == len(logits) == 5\n        rec = sum(.7 ** (4-i) * torch.nn.functional.mse_loss(x, target)\n                  for i, x in enumerate(images))\n        seg = sum(.7 ** (4-i) * torch.nn.functional.cross_entropy(x, labels)\n                  for i, x in enumerate(logits))\n        loss = rec + 1e-4 * seg\n    if not bool(torch.isfinite(loss)):\n        raise FloatingPointError(\'Nonfinite training loss; paired run stopped\')\n    scaler.scale(loss).backward()\n    scaler.step(optimizer)\n    scaler.update()\n    result = dict(rec=float(rec.detach()), seg=float(seg.detach()),\n                  updated=counter.count-before, scale=float(scaler.get_scale()))\n    optimizer.zero_grad(set_to_none=True)\n    return result\n\n\ndef atomic_save(payload, path):\n    temporary = path.with_suffix(path.suffix + \'.tmp\')\n    torch.save(payload, temporary)\n    temporary.replace(path)\n', 'operator_control.py': '"""Frozen validation: paired nominal/matched operators under synthetic mask mixing."""\nfrom pathlib import Path\nimport argparse\nimport hashlib\nimport json\nimport time\nimport numpy as np\nimport torch\n\nALPHAS = (0.05, 0.10, 0.25, 1.0)\n\ndef sha(path):\n    return hashlib.sha256(Path(path).read_bytes()).hexdigest()\n\ndef tensor_sha(x):\n    return hashlib.sha256(x.detach().cpu().contiguous().numpy().tobytes()).hexdigest()\n\ndef mix_mask(mask, dx, alpha):\n    assert mask.ndim == 2 and dx in (-1, 1) and 0 <= alpha <= 1\n    shifted = torch.zeros_like(mask)\n    if dx == 1:\n        shifted[:, 1:] = mask[:, :-1]\n    else:\n        shifted[:, :-1] = mask[:, 1:]\n    return (1-alpha)*mask + alpha*shifted\n\ndef make_operator(mask, bands=28, step=2):\n    h, w = mask.shape\n    phi = mask.new_zeros((1, bands, h, w+(bands-1)*step))\n    for c in range(bands):\n        phi[0, c, :, step*c:step*c+w] = mask\n    back = torch.stack([phi[:, c, :, step*c:step*c+w] for c in range(bands)], dim=1)\n    energy = phi.square().sum(1, keepdim=True)\n    energy = torch.where(energy == 0, torch.ones_like(energy), energy)\n    return back, phi, energy\n\ndef measure(x, phi, step=2):\n    b, c, h, w = x.shape\n    y = x.new_zeros((b, h, phi.shape[-1]))\n    for k in range(c):\n        y[:, :, step*k:step*k+w] += x[:, k]*phi[:, k, :, step*k:step*k+w]\n    return y\n\ndef relative_error(a, b):\n    return float(torch.linalg.vector_norm(a-b)/torch.linalg.vector_norm(b).clamp_min(1e-12))\n\ndef main():\n    import sys\n    p = argparse.ArgumentParser()\n    for key in (\'code\', \'data\', \'checkpoint\', \'out\', \'reference\'):\n        p.add_argument(\'--\'+key, type=Path, required=True)\n    a = p.parse_args()\n    sys.path.insert(0, str(a.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, shift_back_mask, Metrics_Rec, Metrics_Seg, set_seed\n    from run_public252 import validate\n\n    ref = json.loads(a.reference.read_text())\n    mask_path = a.code/\'mask/mask512x512.mat\'\n    assert sha(a.checkpoint) == ref[\'checkpoint_sha256\']\n    assert sha(mask_path) == ref[\'mask_sha256\']\n    assert sha(a.code/\'public252-v1.json\') == ref[\'protocol_sha256\']\n    validate(a.data, json.loads((a.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    a.out.mkdir(exist_ok=False, parents=True)\n    set_seed(3407)\n    loader = evaluation_loader(a.data, \'val\', 0, True)\n    scenes = list(map(str, loader.dataset.names))\n    assert sorted(scenes) == sorted(ref[\'scenes\']) and len(scenes) == 25\n    model = model_generator(\'CRSDUN\', 28, 23, str(a.checkpoint))\n    model.eval()\n    physical = torch.as_tensor(loadmat(mask_path)[\'mask\'], dtype=torch.float32, device=\'cuda\')\n    phi, nominal = init_mask(str(mask_path), \'SSR\', 1, 28)\n    built = make_operator(physical)\n    assert all(torch.equal(x, y) for x, y in zip(built, nominal)), \'Nominal SSR tuple differs\'\n    assert all(torch.equal(x, y) for x, y in zip(make_operator(mix_mask(physical, 1, 0)), nominal))\n    nominal_hashes = [tensor_sha(x) for x in nominal]\n    conditions = [(\'clean\', 0, 0.0)] + [(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\', dx, alpha) for alpha in ALPHAS for dx in (1, -1)]\n    manifest = dict(status=\'running\', checkpoint_epoch=441, checkpoint_sha256=sha(a.checkpoint),\n                    protocol_sha256=ref[\'protocol_sha256\'], mask_sha256=sha(mask_path),\n                    script_sha256=sha(__file__), scenes=scenes, alphas=list(ALPHAS),\n                    conditions=conditions, completed_conditions=[], torch=str(torch.__version__),\n                    gpu=torch.cuda.get_device_name(0), expected_model_forwards=425,\n                    test_evaluated=False, training=False,\n                    scope=\'25 validation scenes; frozen model; identical measurement reused for nominal and matched full SSR tuples.\',\n                    caveat=\'Linear mask mixing with a zero-filled +/-1px shift is synthetic, not calibrated hardware motion. Matched masks may still be outside the training distribution.\',\n                    metrics=\'Every-stage confusion/MSE/PSNR_ref1; SSIM_ref1 final stage only. Scene-averaged reconstruction metrics; aggregate confusion mIoU.\')\n    manifest_path = a.out/\'experiment.json\'\n    def save_manifest():\n        manifest_path.write_text(json.dumps(manifest, indent=2))\n    save_manifest()\n    summary, severity_rows = [], []\n    started = time.time()\n    try:\n      with torch.inference_mode():\n        for name, dx, alpha in conditions:\n            folder = a.out/name\n            folder.mkdir()\n            mixed = physical if name == \'clean\' else mix_mask(physical, dx, alpha)\n            matched = make_operator(mixed)\n            acquisition = matched[1]\n            assert torch.equal(matched[0], shift_back_mask(acquisition))\n            expected_energy = acquisition.square().sum(1, keepdim=True)\n            expected_energy[expected_energy == 0] = 1\n            assert torch.equal(matched[2], expected_energy)\n            paired_ops = [(\'nominal\', nominal)] if name == \'clean\' else [(\'nominal\', nominal), (\'matched\', matched)]\n            severity_rows.append(dict(condition=name, dx=dx, alpha=alpha,\n                                      mask_relative_error=relative_error(mixed, physical),\n                                      changed_fraction=float((mixed != physical).float().mean()),\n                                      mean_transmittance=float(mixed.mean())))\n            pd.DataFrame(severity_rows).to_csv(a.out/\'mask_severity.csv\', index=False)\n            seg = {mode: [Metrics_Seg(23, get_class_names()) for _ in range(5)] for mode, _ in paired_ops}\n            records = []\n            for index, sample in enumerate(loader):\n                scene = scenes[index]\n                target = sample[\'image\'].float().cuda()\n                gt_cpu = target.cpu()\n                truth = sample[\'label\'].numpy()[0]\n                y = init_meas(target, acquisition, \'Y\')\n                if index == 0:\n                    assert torch.allclose(measure(target, acquisition), y, atol=1e-6, rtol=1e-6)\n                y_nominal = init_meas(target, phi, \'Y\')\n                measurement_error = relative_error(y, y_nominal)\n                y_digest = tensor_sha(y)\n                for mode, operator in paired_ops:\n                    op_hashes = [tensor_sha(x) for x in operator]\n                    xs, logits = model(y, operator)\n                    assert len(xs) == len(logits) == 5\n                    for k, (x, logit) in enumerate(zip(xs, logits), 1):\n                        assert x.shape == target.shape and logit.shape == (1, 23, *truth.shape)\n                        assert torch.isfinite(x).all() and torch.isfinite(logit).all(), f\'Nonfinite: {name}/{mode}/{scene}/stage{k}\'\n                        x_cpu = x.float().cpu()\n                        pred = logit.argmax(1).cpu().numpy()[0]\n                        hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                        np.save(folder/f\'{mode}_{scene}_stage{k}_confusion.npy\', hist)\n                        seg[mode][k-1].add_batch(truth[None], pred[None])\n                        mse = float((x_cpu-gt_cpu).square().mean())\n                        metrics = {\'MSE\':mse, \'PSNR\':float(-10*torch.log10(torch.tensor(mse))), \'SSIM\':None}\n                        if k == 5:\n                            rec = Metrics_Rec()\n                            rec.add_batch(gt_cpu, x_cpu)\n                            metrics = rec.get_table().iloc[0].to_dict()\n                        records.append(dict(condition=name, mode=mode, scene=scene, stage=k,\n                                            dx=dx, alpha=alpha, measurement_sha256=y_digest,\n                                            measurement_relative_error=measurement_error, **metrics))\n                    assert tensor_sha(y) == y_digest, \'Measurement mutated during inference\'\n                    assert [tensor_sha(t) for t in operator] == op_hashes, \'SSR tuple mutated\'\n                    del xs, logits, x, logit, x_cpu\n                pd.DataFrame(records).to_csv(folder/\'per_scene_stage_metrics.csv\', index=False)\n                del target, gt_cpu, y, y_nominal\n                print(f\'{name}: {index+1}/25; modes={len(paired_ops)}; elapsed={(time.time()-started)/60:.1f}min\', flush=True)\n            assert [tensor_sha(t) for t in nominal] == nominal_hashes\n            for mode, _ in paired_ops:\n                for k in range(1,6):\n                    acc = seg[mode][k-1]\n                    assert np.array_equal(sum(np.load(folder/f\'{mode}_{s}_stage{k}_confusion.npy\') for s in scenes), acc.confusion_matrix)\n                    np.save(folder/f\'{mode}_stage{k}_aggregate_confusion.npy\', acc.confusion_matrix)\n                    table = acc.get_table()\n                    table.to_csv(folder/f\'{mode}_stage{k}_segmentation.csv\')\n                    items = [r for r in records if r[\'mode\'] == mode and r[\'stage\'] == k]\n                    summary.append(dict(condition=name, mode=mode, stage=k, alpha=alpha, dx=dx,\n                                        foreground_miou_all22=float(table.loc[\'total(-bg)\', \'IoU\']),\n                                        PSNR=float(np.mean([r[\'PSNR\'] for r in items])),\n                                        MSE=float(np.mean([r[\'MSE\'] for r in items])),\n                                        SSIM=float(np.mean([r[\'SSIM\'] for r in items])) if k == 5 else None))\n            pd.DataFrame(summary).to_csv(a.out/\'stage_summary.csv\', index=False)\n            if name == \'clean\':\n                final = summary[-1]\n                check = dict(miou_difference=final[\'foreground_miou_all22\']-ref[\'miou\'], psnr_difference=final[\'PSNR\']-ref[\'psnr\'])\n                check[\'passed\'] = abs(check[\'miou_difference\']) < 1e-6 and abs(check[\'psnr_difference\']) < 1e-4\n                (a.out/\'clean_equivalence.json\').write_text(json.dumps(check, indent=2))\n                assert check[\'passed\'], \'Clean check failed; stopping before stresses\'\n            manifest[\'completed_conditions\'].append(name)\n            save_manifest()\n        pairs = []\n        for name, dx, alpha in conditions[1:]:\n            n, m = [next(r for r in summary if r[\'condition\']==name and r[\'mode\']==mode and r[\'stage\']==5) for mode in (\'nominal\', \'matched\')]\n            pairs.append(dict(condition=name, dx=dx, alpha=alpha,\n                              nominal_miou_percent=100*n[\'foreground_miou_all22\'], matched_miou_percent=100*m[\'foreground_miou_all22\'],\n                              matched_minus_nominal_miou_points=100*(m[\'foreground_miou_all22\']-n[\'foreground_miou_all22\']),\n                              nominal_psnr=n[\'PSNR\'], matched_psnr=m[\'PSNR\'], matched_minus_nominal_psnr=m[\'PSNR\']-n[\'PSNR\']))\n        pd.DataFrame(pairs).to_csv(a.out/\'paired_final_summary.csv\', index=False)\n        manifest[\'status\'] = \'completed\'\n        print(pd.DataFrame(pairs).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest[\'status\'] = \'failed\'\n        manifest[\'error\'] = repr(exc)\n        raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started\n        save_manifest()\n\nif __name__ == \'__main__\':\n    main()\n', 'robustness_inputs.py': '"""Prespecified new perturbations; the inference rule is not tuned here."""\nimport hashlib, math\nimport torch\n\nCONDITIONS = [\n    (\'clean\', 0, 0., None),\n    (\'plus1_alpha0.5\', 1, .5, None),\n    (\'minus1_alpha0.5\', -1, .5, None),\n    (\'nominal_noise40\', 0, 0., 40.),\n    (\'nominal_noise30\', 0, 0., 30.),\n    (\'plus1_alpha0.25_noise40\', 1, .25, 40.),\n    (\'minus1_alpha0.25_noise40\', -1, .25, 40.),\n]\n\ndef add_noise(y, scene, dx, alpha, snr_db):\n    if snr_db is None:return y,dict(seed=None,requested_snr_db=None,actual_snr_db=None,noise_rms=0.)\n    # Omit SNR from the seed to use the same draw at two noise levels on the same acquisition.\n    key=f\'public252-noise-v1|3407|{scene}|{dx}|{alpha:g}\'\n    seed=int.from_bytes(hashlib.sha256(key.encode()).digest()[:8],\'little\')%(2**63)\n    generator=torch.Generator(device=\'cpu\').manual_seed(seed)\n    draw=torch.randn(y.shape,generator=generator,dtype=torch.float64,device=\'cpu\')\n    signal_rms=float(y.detach().cpu().double().square().mean().sqrt())\n    assert signal_rms>0 and math.isfinite(signal_rms)\n    sigma=signal_rms*10**(-snr_db/20)\n    noise=(draw/draw.square().mean().sqrt()*sigma).to(device=y.device,dtype=y.dtype)\n    noisy=y+noise\n    actual_rms=float((noisy.double()-y.double()).square().mean().sqrt())\n    actual_snr=20*math.log10(signal_rms/actual_rms)\n    assert abs(actual_snr-snr_db)<.001\n    # Decimal string preserves all seed bits when mixed with missing seeds in CSV columns.\n    return noisy,dict(seed=str(seed),requested_snr_db=snr_db,actual_snr_db=actual_snr,noise_rms=actual_rms,signal_rms=signal_rms)\n', 'gain_guard.py': '"""Fixed energy floor for an isolated data-consistency gain bound; not whole-network stability."""\nimport inspect, textwrap, types\nimport torch\nfrom numerical_trace import denominator_stats\n\nFACTOR = 1.0\n\ndef safe_denominator(d, energy):\n    return torch.maximum(d, FACTOR*energy)\n\nclass Guard:\n    def __init__(self, model, emit, enabled=True):\n        self.model=model;self.emit=emit;self.enabled=enabled;self.stage=0;self.total_activated=0\n        self.had_forward=\'forward\' in model.__dict__;self.original=model.forward\n        assert not hasattr(model,\'_guard_denominator\')\n        source=textwrap.dedent(inspect.getsource(self.original.__func__))\n        old=\'torch.div(y - A_x_phitheta, PhiPhiT + a)\'\n        assert source.count(old)==1, \'Unexpected forward source; do not patch\'\n        source=source.replace(old,\'torch.div(y - A_x_phitheta, self._guard_denominator(PhiPhiT + a, PhiPhiT))\')\n        namespace=dict(self.original.__func__.__globals__)\n        exec(compile(source,\'<source-pinned-denominator-guard>\',\'exec\'),namespace)\n        self.patched=types.MethodType(namespace[\'forward\'],model)\n\n    def __enter__(self):\n        def apply(d,energy):\n            self.stage+=1\n            used=safe_denominator(d,energy) if self.enabled else d\n            count=int((used!=d).sum());self.total_activated+=count\n            gain=energy/used\n            if self.enabled:assert bool((gain>=0).all() and (gain<=1).all()), \'Gain bound violated\'\n            self.emit(dict(stage=self.stage,event=\'denominator_guard\',enabled=self.enabled,factor=FACTOR,\n                           activated=count,elements=d.numel(),guarded_energy_gain_min=float(gain.min()),guarded_energy_gain_max=float(gain.max()),original=denominator_stats(d),used=denominator_stats(used)))\n            return used\n        self.model._guard_denominator=apply;self.model.forward=self.patched\n        return self\n\n    def __exit__(self,*exc):\n        del self.model._guard_denominator\n        if self.had_forward:self.model.forward=self.original\n        else:del self.model.forward\n', 'numerical_trace.py': '"""Observe frozen CRSDUN through hooks; require exact traced/untraced outputs."""\nimport argparse, json, sys, time\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom operator_control import make_operator, mix_mask, sha, tensor_sha\n\ndef stats(x):\n    a=x.detach().cpu().double().numpy()\n    assert np.isfinite(a).all(), \'Nonfinite tensor in trace\'\n    return dict(min=float(a.min()),max=float(a.max()),rms=float(np.sqrt(np.mean(a*a))),max_abs=float(np.abs(a).max()))\n\ndef denominator_stats(d):\n    r=stats(d); a=d.detach().cpu().double().numpy()\n    r.update(min_abs=float(np.abs(a).min()),min_abs_index=[int(i) for i in np.unravel_index(np.abs(a).argmin(),a.shape)],nonpositive=int((a<=0).sum()),elements=int(a.size))\n    for limit in (1e-6,1e-4,1e-2,.1):r[f\'abs_below_{limit:g}\']=int((np.abs(a)<limit).sum())\n    return r\n\ndef spatial_error(x, target, aligned_energy):\n    delta=x.detach().cpu().double().numpy()-target\n    sq=delta[0]**2\n    h,w=sq.shape[-2:]\n    border=np.ones((h,w),dtype=bool)\n    border[16:-16,16:-16]=False\n    regions={\'image_border16\':np.broadcast_to(border,sq.shape),\'image_interior\':np.broadcast_to(~border,sq.shape)}\n    regions.update({\'energy_zero\':aligned_energy==0,\'energy_0_to_0.1\':(aligned_energy>0)&(aligned_energy<=.1),\n                    \'energy_0.1_to_1\':(aligned_energy>.1)&(aligned_energy<=1),\n                    \'energy_1_to_4\':(aligned_energy>1)&(aligned_energy<=4),\'energy_above4\':aligned_energy>4})\n    total=float(sq.sum()); result={}\n    for name,mask in regions.items():\n        n=int(mask.sum()); s=float(sq[mask].sum())\n        result[name]=dict(voxels=n,squared_error_sum=s,mse=s/n if n else None,fraction_total_error=s/total if total else 0.)\n    return dict(mse=float(sq.mean()),total_squared_error=total,regions=result)\n\nclass Observer:\n    def __init__(self,model,operator,target,emit,measurement=None):\n        self.model=model;self.operator=operator;self.target=target.detach().cpu().double().numpy();self.emit=emit\n        self.stage=0;self.handles=[];self.original_phif=model.mul_Phif;self.original_phit=model.mul_PhiTg\n        self.measurement=measurement\n        self.had_phif=\'mul_Phif\' in model.__dict__;self.had_phit=\'mul_PhiTg\' in model.__dict__\n        _,bands,h,w=target.shape\n        raw=operator[1].square().sum(1)[0]\n        self.aligned_energy=torch.stack([raw[:,2*c:2*c+w] for c in range(bands)]).cpu().numpy()\n\n    def record(self,event,x,error=False,**extra):\n        row=dict(stage=self.stage,event=event,values=stats(x),**extra)\n        if error:row[\'reconstruction_error\']=spatial_error(x,self.target,self.aligned_energy)\n        self.emit(row)\n\n    def __enter__(self):\n        def para_hook(module,args,out):\n            self.stage+=1\n            p=out.detach().cpu().flatten().tolist()\n            assert len(p)==4\n            self.emit(dict(stage=self.stage,event=\'parameters\',a=p[0],mu=p[1],b=p[2],gamma=p[3],\n                           denominator=denominator_stats(self.operator[2]+out[:,0:1])))\n        def phif(phi,x):\n            self.record(\'x_new_before_data_consistency\',x,error=True)\n            result=self.original_phif(phi,x)\n            self.record(\'predicted_measurement\',result)\n            if self.measurement is not None:self.record(\'measurement_residual\',self.measurement.unsqueeze(1)-result)\n            return result\n        def phit(phi,g):\n            self.record(\'residual_divided_by_denominator\',g)\n            result=self.original_phit(phi,g)\n            self.record(\'data_consistency_correction\',result)\n            return result\n        self.model.mul_Phif=phif;self.model.mul_PhiTg=phit\n        for module in self.model.para_est:self.handles.append(module.register_forward_hook(para_hook))\n        for k in range(self.model.stage):\n            self.handles.append(self.model.net_stage[3*k].register_forward_pre_hook(lambda m,args:self.record(\'z_before_reconstruction_attention\',args[0],error=True)))\n            self.handles.append(self.model.net_stage[3*k].register_forward_hook(lambda m,args,out:self.record(\'after_reconstruction_attention\',out,error=True)))\n            self.handles.append(self.model.net_stage[3*k+1].register_forward_hook(lambda m,args,out:self.record(\'after_refinement\',out,error=True)))\n        return self\n\n    def __exit__(self,*exc):\n        for h in self.handles:h.remove()\n        if self.had_phif:self.model.mul_Phif=self.original_phif\n        else:del self.model.mul_Phif\n        if self.had_phit:self.model.mul_PhiTg=self.original_phit\n        else:del self.model.mul_PhiTg\n\ndef main():\n    p=argparse.ArgumentParser()\n    for name in (\'code\',\'data\',\'checkpoint\',\'out\',\'reference\',\'expected\'):p.add_argument(\'--\'+name,type=Path,required=True)\n    args=p.parse_args();sys.path.insert(0,str(args.code))\n    from scipy.io import loadmat\n    import pandas as pd\n    from dataset import evaluation_loader,get_class_names\n    from models import model_generator\n    from utils import init_mask,init_meas,set_seed,Metrics_Rec,Metrics_Seg\n    from run_public252 import validate\n    ref=json.loads(args.reference.read_text());expected=json.loads(args.expected.read_text())\n    for path,key in [(args.checkpoint,\'checkpoint_sha256\'),(args.code/\'mask/mask512x512.mat\',\'mask_sha256\'),(args.code/\'public252-v1.json\',\'protocol_sha256\')]:assert sha(path)==ref[key]\n    validate(args.data,json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available();set_seed(3407)\n    loader=evaluation_loader(args.data,\'val\',0,True);scenes=list(map(str,loader.dataset.names))\n    assert scenes==ref[\'scenes\'] and len(scenes)==25\n    model=model_generator(\'CRSDUN\',28,23,str(args.checkpoint));model.eval()\n    mask=torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'],dtype=torch.float32,device=\'cuda\')\n    _,nominal=init_mask(str(args.code/\'mask/mask512x512.mat\'),\'SSR\',1,28)\n    assert all(torch.equal(a,b) for a,b in zip(make_operator(mask),nominal))\n    conditions=[(\'clean\',0,0.)]+[(f\'{"plus" if dx>0 else "minus"}1_alpha{alpha:g}\',dx,alpha) for alpha in (.1,.25,1.) for dx in (1,-1)]\n    args.out.mkdir(parents=True,exist_ok=False)\n    manifest=dict(status=\'running\',checkpoint_sha256=ref[\'checkpoint_sha256\'],protocol_sha256=ref[\'protocol_sha256\'],mask_sha256=ref[\'mask_sha256\'],script_sha256=sha(__file__),helper_sha256=sha(Path(__file__).with_name(\'operator_control.py\')),scenes=scenes,conditions=conditions,completed_conditions=[],completed_identity_pairs=0,training=False,test_evaluated=False,expected_forwards=350,torch=str(torch.__version__),gpu=torch.cuda.get_device_name(0),scope=\'Matched operators only. Every traced forward paired with an uninstrumented forward; all five reconstruction/logit tensors must hash identically. Regions are image-border16 and raw detector-energy bins aligned to each spectral voxel, not calibrated hardware regions.\')\n    def save(): (args.out/\'experiment.json\').write_text(json.dumps(manifest,indent=2))\n    save();started=time.time();summaries=[];checks=[];scene_metrics=[]\n    try:\n      with torch.inference_mode(),(args.out/\'trace.jsonl\').open(\'w\') as f:\n        for name,dx,alpha in conditions:\n            operator=make_operator(mask if not dx else mix_mask(mask,dx,alpha))\n            op_hash=[tensor_sha(t) for t in operator]\n            accumulator=Metrics_Seg(23,get_class_names());rec=Metrics_Rec()\n            for index,sample in enumerate(loader):\n                scene=scenes[index];target=sample[\'image\'].float().cuda();truth=sample[\'label\'].numpy()[0]\n                y=init_meas(target,operator[1],\'Y\');yh=tensor_sha(y)\n                xs,ls=model(y,operator)\n                baseline=[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n                def emit(row):\n                    f.write(json.dumps(dict(condition=name,scene=scene,**row),allow_nan=False)+\'\\n\')\n                with Observer(model,operator,target,emit,measurement=y) as observer:xs,ls=model(y,operator)\n                f.flush()\n                assert observer.stage==5\n                equal=baseline==[tensor_sha(t) for t in [*xs,*ls]]\n                checks.append(dict(condition=name,scene=scene,all_stage_tensors_bitwise_identical=equal))\n                (args.out/\'identity_checks.json\').write_text(json.dumps(checks,indent=2))\n                assert equal,\'Instrumentation altered predictions\'\n                assert tensor_sha(y)==yh and [tensor_sha(t) for t in operator]==op_hash\n                one=Metrics_Rec();one.add_batch(target.cpu(),xs[-1].cpu())\n                metric=one.get_table().iloc[0].to_dict()\n                e=expected[\'scenes\'][name][scene]\n                assert abs(metric[\'PSNR\']-e[\'PSNR\'])<1e-4 and np.isclose(metric[\'MSE\'],e[\'MSE\'],rtol=1e-5,atol=1e-9),\'Prior scene metrics not reproduced\'\n                for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):setattr(rec,field,getattr(rec,field)+getattr(one,field))\n                pred=ls[-1].argmax(1).cpu().numpy()[0];accumulator.add_batch(truth[None],pred[None])\n                hist=np.bincount((truth.astype(np.int64)*23+pred).ravel(),minlength=529).reshape(23,23)\n                assert __import__(\'hashlib\').sha256(hist.astype(\'<i8\').tobytes()).hexdigest()==e[\'confusion_sha256\'],\'Prior scene confusion differs\'\n                scene_metrics.append(dict(condition=name,scene=scene,**metric));pd.DataFrame(scene_metrics).to_csv(args.out/\'per_scene_metrics.csv\',index=False)\n                manifest[\'completed_identity_pairs\']+=1;save()\n                del xs,ls,target,y\n                print(f\'{name}: {index+1}/25, traced/untraced identical, prior metrics reproduced; {(time.time()-started)/60:.1f}min\',flush=True)\n            table=accumulator.get_table();row=dict(condition=name,foreground_miou_all22=float(table.loc[\'total(-bg)\',\'IoU\']),**rec.get_table().iloc[0].to_dict())\n            e=expected[\'summary\'][name]\n            assert abs(row[\'foreground_miou_all22\']-e[\'foreground_miou_all22\'])<1e-8 and abs(row[\'PSNR\']-e[\'PSNR\'])<1e-4\n            summaries.append(row);pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\',index=False)\n            table.to_csv(args.out/f\'{name}_segmentation.csv\');np.save(args.out/f\'{name}_confusion.npy\',accumulator.confusion_matrix)\n            manifest[\'completed_conditions\'].append(name);save()\n        manifest[\'status\']=\'completed\'\n    except BaseException as exc:\n        manifest.update(status=\'failed\',error=repr(exc));raise\n    finally:\n        manifest[\'elapsed_seconds\']=time.time()-started;save()\n\nif __name__==\'__main__\':main()\n', 'crossed_evaluation.py': '"""Frozen 2x2 evaluation: training arm crossed with inference guard."""\nimport argparse\nimport json\nimport math\nimport sys\nimport time\nfrom contextlib import nullcontext\nfrom pathlib import Path\nimport numpy as np\nimport torch\nfrom operator_control import make_operator, mix_mask, sha, tensor_sha\nfrom pilot_support import TrainingGuard\nfrom robustness_inputs import CONDITIONS, add_noise\n\nCOMBINATIONS = [(\'control\', False), (\'guarded\', True), (\'control\', True), (\'guarded\', False)]\n\n\ndef mode_name(arm, enabled):\n    return arm + (\'_on\' if enabled else \'_off\')\n\n\ndef forward(model, measurement, operator, enabled):\n    with TrainingGuard(model) if enabled else nullcontext():\n        result = model(measurement, operator)\n    assert \'forward\' not in model.__dict__, \'Guard was not removed\'\n    return result\n\n\ndef finite_outputs(images, logits):\n    return all(bool(torch.isfinite(t).all()) for t in [*images, *logits])\n\n\ndef contrasts(rows):\n    result = []\n    for condition, *_ in CONDITIONS:\n        group = {r[\'mode\']: r for r in rows if r[\'condition\'] == condition}\n        for label, base, changed in [\n            (\'inference_guard_on_control_weights\', \'control_off\', \'control_on\'),\n            (\'inference_guard_on_guarded_weights\', \'guarded_off\', \'guarded_on\'),\n            (\'training_arm_at_guard_off\', \'control_off\', \'guarded_off\'),\n            (\'training_arm_at_guard_on\', \'control_on\', \'guarded_on\')]:\n            if base not in group or changed not in group:\n                continue\n            a, b = group[base], group[changed]\n            complete = a[\'valid_scenes\'] == b[\'valid_scenes\'] == 25\n            result.append(dict(condition=condition, comparison=label, baseline=base, changed=changed,\n                               status=\'complete\' if complete else \'nonfinite_cases_no_full_metric\',\n                               miou_change_points=100*(b[\'miou\']-a[\'miou\']) if complete else None,\n                               psnr_change=b[\'PSNR\']-a[\'PSNR\'] if complete else None))\n    return result\n\n\ndef main():\n    parser = argparse.ArgumentParser()\n    for name in (\'code\', \'data\', \'control\', \'guarded\', \'out\', \'expected\'):\n        parser.add_argument(\'--\'+name, type=Path, required=True)\n    args = parser.parse_args()\n    sys.path.insert(0, str(args.code))\n    import pandas as pd\n    from scipy.io import loadmat\n    from dataset import evaluation_loader, get_class_names\n    from models import model_generator\n    from utils import init_mask, init_meas, set_seed, Metrics_Rec, Metrics_Seg\n    from run_public252 import validate\n\n    expected = json.loads(args.expected.read_text())\n    for name, digest in expected[\'code_hashes\'].items():\n        assert sha(args.code/name) == digest, name\n    for name, digest in expected[\'helper_hashes\'].items():\n        assert sha(Path(__file__).with_name(name)) == digest, name\n    assert sha(args.code/\'mask/mask512x512.mat\') == expected[\'reference\'][\'mask_sha256\']\n    for arm in (\'control\', \'guarded\'):\n        assert sha(getattr(args, arm)) == expected[\'checkpoints\'][arm+\'_last.pth\']\n    validate(args.data, json.loads((args.code/\'public252-v1.json\').read_text()))\n    assert torch.cuda.is_available()\n    args.out.mkdir(parents=True, exist_ok=False)\n    manifest = dict(status=\'running\', conditions=CONDITIONS, combinations=COMBINATIONS,\n                    checkpoint_hashes=expected[\'checkpoints\'], source_archive_sha256=expected[\'archive_sha256\'],\n                    code_hashes=expected[\'code_hashes\'], script_hashes={n:sha(Path(__file__).with_name(n)) for n in\n                    (\'crossed_evaluation.py\', \'pilot_support.py\', \'operator_control.py\', \'robustness_inputs.py\')},\n                    expected_forwards=700, completed_forwards=0, diagonal_checks=0,\n                    nonfinite_cases=[], completed_conditions=[], training=False, test_evaluated=False,\n                    torch=str(torch.__version__), gpu=torch.cuda.get_device_name(0),\n                    scope=\'Same25 development scenes and fixed measurements. Crossed inference at two adapted checkpoints; no further optimization, model selection or independent-test claim.\')\n    def save():\n        (args.out/\'experiment.json\').write_text(json.dumps(manifest, indent=2, allow_nan=False))\n    save(); started = time.time(); all_rows = []; summaries = []\n    try:\n        set_seed(3407)\n        loader = evaluation_loader(args.data, \'val\', 0, True)\n        scenes = list(map(str, loader.dataset.names))\n        assert scenes == expected[\'reference\'][\'scenes\'] and len(scenes) == 25\n        models = {arm:model_generator(\'CRSDUN\', 28, 23, str(getattr(args, arm))).eval() for arm in (\'control\', \'guarded\')}\n        original = {arm:{k:tensor_sha(t) for k,t in model.state_dict().items()} for arm,model in models.items()}\n        mask = torch.as_tensor(loadmat(args.code/\'mask/mask512x512.mat\')[\'mask\'], dtype=torch.float32, device=\'cuda\')\n        _, nominal = init_mask(str(args.code/\'mask/mask512x512.mat\'), \'SSR\', 1, 28)\n        assert all(torch.equal(a,b) for a,b in zip(make_operator(mask), nominal))\n        with torch.inference_mode():\n            for condition, dx, alpha, snr in CONDITIONS:\n                folder = args.out/condition; folder.mkdir()\n                op = make_operator(mask if not dx else mix_mask(mask, dx, alpha))\n                ophashes = [tensor_sha(t) for t in op]\n                seg = {mode_name(a,b):Metrics_Seg(23,get_class_names()) for a,b in COMBINATIONS}\n                rec = {name:Metrics_Rec() for name in seg}\n                valid = dict.fromkeys(seg, 0)\n                for index, sample in enumerate(loader):\n                    scene = scenes[index]; target = sample[\'image\'].float().cuda()\n                    truth = sample[\'label\'].numpy()[0]\n                    y, info = add_noise(init_meas(target, op[1], \'Y\'), scene, dx, alpha, snr)\n                    yh = tensor_sha(y)\n                    assert yh == expected[\'scenes\'][condition][\'control\'][scene][\'measurement_sha256\']\n                    for arm, enabled in COMBINATIONS:\n                        mode = mode_name(arm, enabled)\n                        diagonal = enabled == (arm == \'guarded\')\n                        images, logits = forward(models[arm], y, op, enabled)\n                        row = dict(condition=condition, scene=scene, mode=mode, training_arm=arm,\n                                   inference_guard=enabled, diagonal=diagonal, measurement_sha256=yh, **info)\n                        failure = None\n                        if not finite_outputs(images, logits):\n                            failure = \'nonfinite_model_output\'\n                        else:\n                            one = Metrics_Rec(); one.add_batch(target.cpu(), images[-1].cpu())\n                            values = one.get_table().iloc[0].to_dict()\n                            if not all(math.isfinite(float(v)) for v in values.values()):\n                                failure = \'nonfinite_reconstruction_metric\'\n                        if failure:\n                            row.update(status=failure, PSNR=None, SSIM=None, MSE=None)\n                            manifest[\'nonfinite_cases\'].append(dict(condition=condition, scene=scene, mode=mode, reason=failure))\n                            if diagonal:\n                                raise AssertionError(f\'Previously finite diagonal failed: {condition}/{scene}/{mode}\')\n                        else:\n                            pred = logits[-1].argmax(1).cpu().numpy()[0]\n                            hist = np.bincount((truth.astype(np.int64)*23+pred).ravel(), minlength=529).reshape(23,23)\n                            if diagonal:\n                                prior = expected[\'scenes\'][condition][arm][scene]\n                                import hashlib\n                                assert hashlib.sha256(hist.astype(\'<i8\').tobytes()).hexdigest() == prior[\'confusion_sha256\'], \'Diagonal segmentation changed\'\n                                assert abs(values[\'PSNR\']-prior[\'PSNR\']) < 1e-4, \'Diagonal reconstruction changed\'\n                                assert np.isclose(values[\'MSE\'], prior[\'MSE\'], rtol=1e-5, atol=1e-9)\n                                manifest[\'diagonal_checks\'] += 1\n                            np.save(folder/f\'{mode}_{scene}_confusion.npy\', hist)\n                            seg[mode].add_batch(truth[None], pred[None])\n                            for field in (\'psnr\',\'ssim\',\'mse\',\'count\'):\n                                setattr(rec[mode], field, getattr(rec[mode],field)+getattr(one,field))\n                            valid[mode] += 1; row.update(status=\'finite\', **values)\n                        all_rows.append(row)\n                        del images, logits\n                        assert tensor_sha(y) == yh and [tensor_sha(t) for t in op] == ophashes\n                        manifest[\'completed_forwards\'] += 1\n                    pd.DataFrame(all_rows).to_csv(args.out/\'per_scene_metrics.csv\', index=False)\n                    save(); del target, y\n                    if (index+1)%5 == 0:\n                        print(f\'{condition}: {index+1}/25 scenes, four combinations; {(time.time()-started)/60:.1f}min\', flush=True)\n                for arm, enabled in COMBINATIONS:\n                    mode = mode_name(arm, enabled)\n                    complete = valid[mode] == 25\n                    row = dict(condition=condition, mode=mode, training_arm=arm, inference_guard=enabled,\n                               valid_scenes=valid[mode], expected_scenes=25, status=\'complete\' if complete else \'nonfinite_cases_no_full_metric\',\n                               miou=None, PSNR=None, SSIM=None, MSE=None)\n                    if complete:\n                        table = seg[mode].get_table(); table.to_csv(folder/f\'{mode}_classes.csv\')\n                        np.save(folder/f\'{mode}_aggregate_confusion.npy\', seg[mode].confusion_matrix)\n                        row.update(miou=float(table.loc[\'total(-bg)\',\'IoU\']), **rec[mode].get_table().iloc[0].to_dict())\n                        if enabled == (arm == \'guarded\'):\n                            prior = expected[\'summary\'][condition][arm]\n                            assert abs(row[\'miou\']-prior[\'miou\']) < 1e-8 and abs(row[\'PSNR\']-prior[\'PSNR\']) < 1e-4\n                    summaries.append(row); print(row, flush=True)\n                pd.DataFrame(summaries).to_csv(args.out/\'summary.csv\', index=False)\n                pd.DataFrame(contrasts(summaries)).to_csv(args.out/\'contrasts.csv\', index=False)\n                manifest[\'completed_conditions\'].append(condition); save()\n        for arm, model in models.items():\n            assert original[arm] == {k:tensor_sha(t) for k,t in model.state_dict().items()}, \'Model state changed\'\n        assert manifest[\'completed_forwards\'] == 700 and manifest[\'diagonal_checks\'] == 350\n        manifest.update(status=\'completed\' if not manifest[\'nonfinite_cases\'] else \'completed_with_nonfinite_cases\', model_state_unchanged=True)\n        print(pd.DataFrame(contrasts(summaries)).to_string(index=False), flush=True)\n    except BaseException as exc:\n        manifest.update(status=\'failed\', error=repr(exc)); raise\n    finally:\n        manifest[\'elapsed_seconds\'] = time.time()-started; save()\n\nif __name__ == \'__main__\': main()\n', 'verify_crossed_evaluation.py': '"""Check switching, state preservation, and failure-aware summaries on small CUDA inputs."""\nimport argparse\nimport io\nimport sys\nimport zipfile\nfrom pathlib import Path\nimport torch\nfrom crossed_evaluation import COMBINATIONS, mode_name, forward, finite_outputs, contrasts\nfrom operator_control import make_operator, tensor_sha, mix_mask\nfrom robustness_inputs import add_noise\nfrom gain_guard import Guard\n\ndef main():\n    p=argparse.ArgumentParser();p.add_argument(\'--code\',required=True)\n    p.add_argument(\'--control\');p.add_argument(\'--guarded\');p.add_argument(\'--archive\')\n    args=p.parse_args();sys.path.insert(0,args.code)\n    from models.CRSDUN import CRSDUN\n    from utils import set_seed,init_meas\n    torch.set_num_threads(1);set_seed(3407)\n    models={}\n    for arm in (\'control\',\'guarded\'):\n        if args.archive:\n            with zipfile.ZipFile(args.archive) as z:\n                name=next(n for n in z.namelist() if n.endswith(\'/results/\'+arm+\'_last.pth\'))\n                saved=torch.load(io.BytesIO(z.read(name)),map_location=\'cpu\',weights_only=True)\n        else:saved=torch.load(getattr(args,arm),map_location=\'cpu\',weights_only=True)\n        assert saved[\'arm\']==arm and saved[\'pilot_epoch\']==5\n        models[arm]=CRSDUN(stage=5,bands=28,n_class=23).cuda().eval()\n        models[arm].load_state_dict(saved[\'model\'],strict=True)\n    original={a:{k:tensor_sha(t) for k,t in m.state_dict().items()} for a,m in models.items()}\n    x=torch.rand(1,28,64,64,device=\'cuda\')*.1\n    mask=(torch.rand(64,64,device=\'cuda\')>.5).float()\n    with torch.inference_mode():\n        for alpha in (0.,.5):\n            op=make_operator(mix_mask(mask,1,alpha))\n            y,_=add_noise(init_meas(x,op[1],\'Y\'),\'crossed-local-check\',1,alpha,30.)\n            yh=tensor_sha(y);record={}\n            for arm,enabled in COMBINATIONS:\n                xs,ls=forward(models[arm],y,op,enabled)\n                assert finite_outputs(xs,ls)\n                record[mode_name(arm,enabled)]=[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n            for arm,enabled in reversed(COMBINATIONS):\n                xs,ls=forward(models[arm],y,op,enabled)\n                assert record[mode_name(arm,enabled)]==[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n            for arm in models:\n                with Guard(models[arm],lambda row:None):xs,ls=models[arm](y,op)\n                assert record[mode_name(arm,True)]==[tensor_sha(t) for t in [*xs,*ls]]\n                del xs,ls\n            assert tensor_sha(y)==yh\n    assert all(original[a]=={k:tensor_sha(t) for k,t in m.state_dict().items()} for a,m in models.items())\n    assert not finite_outputs([torch.tensor([float(\'nan\')])],[torch.ones(1)])\n    rows=[dict(condition=\'clean\',mode=mode_name(a,b),valid_scenes=25,miou=.5+i*.1,PSNR=30+i) for i,(a,b) in enumerate(COMBINATIONS)]\n    result=contrasts(rows);assert len(result)==4\n    assert abs(result[0][\'miou_change_points\']-20)<1e-8 and result[0][\'psnr_change\']==2\n    rows[2].update(valid_scenes=24,miou=None,PSNR=None)\n    result=contrasts(rows)\n    assert result[0][\'miou_change_points\'] is None and result[0][\'psnr_change\'] is None\n    print(\'PASS: both actual pilot checkpoints, four configurations, binary/fractional noisy64x64 CUDA inputs; reverse-order bitwise repeatability; guard-on matches archived guard; unchanged model states/input; nonfinite detection and incomplete-metric contrasts. Full512x512 validation remains to run.\')\n\nif __name__==\'__main__\':main()\n'}
EXPECTED={'archive_sha256': '1ec598422f4407e876819d1a4b7790e4ed2bede4e4cd9fbfc3b22d2c67263454', 'checkpoints': {'last_pair.pt': 'eb057f12b13ae388a2862b034873ea165935698ac1a0c5384e2a298d91658358', 'control_last.pth': 'b6bcfbc372545058e207d14261344b7afc5e8d2d23673daa8b50d8a7a29fd90e', 'guarded_last.pth': '51e65fdddca4ff4826f132b73e040d6186cc15db504643e5d9c11c2c1304a846'}, 'reference': {'checkpoint_sha256': '4a10679ee5f685caa8815f2254a6c110f58f715ab3f73cb5a6c6bb535e10dcff', 'protocol_sha256': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318', 'mask_sha256': '1a278c3d4e9a90e1e6aa93b67ab716affd818abbbbfef8f6ea02f373740d3cd9', 'scenes': ['2021-11-03_046', '2021-11-03_047', '2021-11-03_057', '2021-11-03_085', '2021-11-03_090', '2021-11-03_110', '2021-11-04_010', '2021-11-04_017', '2021-11-04_024', '2021-11-04_042', '2021-11-04_047', '2021-11-04_049', '2021-11-04_055', '2021-11-04_061', '2021-11-04_093', '2021-11-04_098', '2021-11-05_010', '2021-11-05_024', '2021-11-05_035', '2021-11-05_041', '2021-11-05_046', '2021-11-10_014', '2021-11-10_024', '2021-11-10_029', '2021-11-10_050'], 'miou': 0.7876837070566084, 'psnr': 39.006845703125}, 'code_hashes': {'models/CRSDUN.py': '57bd3830958ddc0425ae8c170a840234e4683c8a94a105cb8a9c8a55859a0543', 'models/__init__.py': '84190199b5e4155ba534b9d6b5265b295153bec587ecfed3302daa59c0ee85da', 'dataset.py': 'b771e6d99eac9a946849388dc9b2d72408f85a9949886c1e818205ff054d2308', 'utils.py': 'afa791536c0726b65085a6d5c64d3e40d6e5f4c2f4fb6be9364cc0038c58b81e', 'balanced_sampling.py': 'd3ef24e45e8337a9b2bdbb0eacce532d3441b74f8565e771b36bc2c4e2d6dd19', 'run_public252.py': 'f77e5d5bdc7acc4b9137793cdefd6c04bbe50caf305f80ff65dbd18da531061e', 'public252-v1.json': '77e00da7d2ee3dc6509e840e1dd4139fd07d338fbecfab083ec28c48e36d7318'}, 'summary': {'clean': {'control': {'miou': 0.7519364625201984, 'PSNR': 39.10392791748047, 'SSIM': 0.9757934999465943, 'MSE': 0.00012969541974598543}, 'guarded': {'miou': 0.7608742886778193, 'PSNR': 39.13199493408203, 'SSIM': 0.9760174512863159, 'MSE': 0.000129022077890113}}, 'plus1_alpha0.5': {'control': {'miou': 0.6108305433887987, 'PSNR': -8.360115586221218, 'SSIM': 0.898580641746521, 'MSE': 1297.8758979836107}, 'guarded': {'miou': 0.7079456389518013, 'PSNR': 35.89875946044922, 'SSIM': 0.9714169335365296, 'MSE': 0.0002733888104557991}}, 'minus1_alpha0.5': {'control': {'miou': 0.6038555339521738, 'PSNR': -8.524602682590485, 'SSIM': 0.8977232646942138, 'MSE': 207.66724863171578}, 'guarded': {'miou': 0.707570929665001, 'PSNR': 35.93922210693359, 'SSIM': 0.9714727234840393, 'MSE': 0.00027030768687836827}}, 'nominal_noise40': {'control': {'miou': 0.7425885108765347, 'PSNR': 36.98492248535156, 'SSIM': 0.9572081995010376, 'MSE': 0.0002057978417724371}, 'guarded': {'miou': 0.7492813688270814, 'PSNR': 37.21837371826172, 'SSIM': 0.9593847608566284, 'MSE': 0.00019602654909249396}}, 'nominal_noise30': {'control': {'miou': 0.6619986868943043, 'PSNR': 32.002398300170896, 'SSIM': 0.8623369836807251, 'MSE': 0.0006352627044543624}, 'guarded': {'miou': 0.6653369061227624, 'PSNR': 32.47840354919433, 'SSIM': 0.8674454140663147, 'MSE': 0.0005716667848173529}}, 'plus1_alpha0.25_noise40': {'control': {'miou': 0.65971162083755, 'PSNR': 8.18180344581604, 'SSIM': 0.908188099861145, 'MSE': 12.421373179126531}, 'guarded': {'miou': 0.736176400251842, 'PSNR': 34.69092376708984, 'SSIM': 0.948053457736969, 'MSE': 0.00034607998793944716}}, 'minus1_alpha0.25_noise40': {'control': {'miou': 0.6698453405543302, 'PSNR': 6.858756275177002, 'SSIM': 0.9090690398216248, 'MSE': 7.831492779795081}, 'guarded': {'miou': 0.7420496756618177, 'PSNR': 34.6731527709961, 'SSIM': 0.9479894161224365, 'MSE': 0.00034700270276516676}}}, 'scenes': {'clean': {'control': {'2021-11-03_046': {'PSNR': 40.02615737915039, 'MSE': 9.939941082848236e-05, 'measurement_sha256': '5191111e68360ca27820d1afaad39e01c4025fd9e080b5bd43b4014924c2eaf8', 'confusion_sha256': '0dfafc082cdea3477fb1d8750eebb7ed95cbf3ea4c0158a6aa35cc63b9ce2a8d'}, '2021-11-03_047': {'PSNR': 38.85468673706055, 'MSE': 0.00013017599121667445, 'measurement_sha256': '7a6412fc0c1f42a41ed81c6443e75351eb9fea7c9b11393ffe639a85d04612fe', 'confusion_sha256': '4fb6976b4f31e53bb0f84414df8cce9e3d90489c82c042098a593497fadb6e91'}, '2021-11-03_057': {'PSNR': 38.09902572631836, 'MSE': 0.00015491632802877575, 'measurement_sha256': 'd2351df833a4b4a9424297a2658d694a6ef4b860548f7afbe88f571826a176da', 'confusion_sha256': '7724d1993081fdde0b1d534b4cd40d2ee69b19b309917d07913022f990f9f30a'}, '2021-11-03_085': {'PSNR': 40.81794738769531, 'MSE': 8.28333359095268e-05, 'measurement_sha256': 'c9e43b2281aa15ea374fea53621047c152b9d3bea4b49dea300b670648546c6e', 'confusion_sha256': 'c0505b87f38954d2e7fddfaaefeb5ca1f3f26d2a12ca3ef18035e6a365318a2b'}, '2021-11-03_090': {'PSNR': 40.634864807128906, 'MSE': 8.639990846859291e-05, 'measurement_sha256': '18b4c6dc7af3cde6e22733a096a4dfac787a7e59d02c62cdddf7acd47b4743a3', 'confusion_sha256': '624225e069130a100474e1bb3cec6ece65d967f0b4a2604dfd927420ace9f7ae'}, '2021-11-03_110': {'PSNR': 39.70047378540039, 'MSE': 0.00010714017844293267, 'measurement_sha256': '24e52021df1f97df92a857c79b65efb664079d4bcebdac7b77cc8295cc0b4359', 'confusion_sha256': '4a1ef2ecaa848864b20c36bd533e5b1f224c9c2c8894986421a641cf4b9f55d2'}, '2021-11-04_010': {'PSNR': 36.90199661254883, 'MSE': 0.0002040798863163218, 'measurement_sha256': '46cf4e1a53d55fbf79f34641b021da1ca1927d82a70cf058327fa4902e43793d', 'confusion_sha256': '888b0ec20e945708124ed512d6f43f80904319d8d1beacdf8a6a19475e97fc16'}, '2021-11-04_017': {'PSNR': 38.444095611572266, 'MSE': 0.0001430837291991338, 'measurement_sha256': 'cd41b9014db6172d44923f4989566995d1c7ce5588c25d591e589ceb31d81a34', 'confusion_sha256': '985856ede65d48d34b5e44ec78027e4207f04195803efc9c11f21d71e1f8f8d1'}, '2021-11-04_024': {'PSNR': 38.71913146972656, 'MSE': 0.0001343032345175743, 'measurement_sha256': '4b532914673e7f970c4cad27433d95f4023818e8e325a688d4119c5432b209e5', 'confusion_sha256': '11540454eb5142ead4f96ae2b7e1dbb0c1ac2bcee17f26802ffd35008a5779cd'}, '2021-11-04_042': {'PSNR': 40.715065002441406, 'MSE': 8.48190175020136e-05, 'measurement_sha256': 'ac460d346d881b5d954e309d39439bcf7e3f7fe7801192d523c746b1f8e0a56b', 'confusion_sha256': '484a834d3e4c9180737d3a194afc12956c0f73f07e928a016c9effdcf1bd96e5'}, '2021-11-04_047': {'PSNR': 40.50288772583008, 'MSE': 8.906584844226018e-05, 'measurement_sha256': '025f043649abfa9e1f5cbfbd07f472d6866bdf6916ee4f4088a9c8899e082683', 'confusion_sha256': '7c14e690870a199364e4529c3b7d433e024ae7401dcf127e094045aa5ee09315'}, '2021-11-04_049': {'PSNR': 40.916378021240234, 'MSE': 8.097706449916586e-05, 'measurement_sha256': '6b5fbc808927ab3def28d010fe0bff80d765342f1094e7c5dc0560a17e5be18b', 'confusion_sha256': 'f051061834c0359bf4d82f3fdc31413d6d2b160c2988cec492214d10cb83fd0e'}, '2021-11-04_055': {'PSNR': 40.996219635009766, 'MSE': 7.950194412842393e-05, 'measurement_sha256': 'cf74da7ef5193903d7b30586ffc2d4c6ddf6d07029ca1c566fc509f31a1022fe', 'confusion_sha256': '5d4811a040fb133bf706c9925d7479b1855f191356389533714c01fca3c0c063'}, '2021-11-04_061': {'PSNR': 40.983463287353516, 'MSE': 7.973582250997424e-05, 'measurement_sha256': '2ac2a9e2aee12e6740259103afe0d0f5a1e7ced6f75025e0f0fb910fca4d39d8', 'confusion_sha256': '933d8f0dd33a3fa9d7f05c6e774a047a0e5ef6a69f074059696405c2fc86f509'}, '2021-11-04_093': {'PSNR': 39.3204345703125, 'MSE': 0.00011693814303725958, 'measurement_sha256': 'a1fdcd1d86ad979b5585560f9de30646c6bf1ee8010bda943643b10f60f3cb77', 'confusion_sha256': '90bc2955568a907ae74f5ceb6b455b4cd17184b9fd9c815a7cda0c2f45384fd2'}, '2021-11-04_098': {'PSNR': 39.71792984008789, 'MSE': 0.00010671047493815422, 'measurement_sha256': '72b6223790ff9461b7d788d3c81b9ce3e34641fe9250bea030a3aa8efc52224e', 'confusion_sha256': 'f30a77bc36cf1c3f84607fefb4676a34225cb6dd7fd877fa67e5586b12b7cad4'}, '2021-11-05_010': {'PSNR': 37.17979431152344, 'MSE': 0.00019143450481351465, 'measurement_sha256': 'd39ffba0dc82719c254d478b2edd54568cbf2fbb9a683f7e95faf1c335821a33', 'confusion_sha256': '790752933372c456e571a45930e7790d90edb1ff2e7e05092e0eb2a2ee8f5550'}, '2021-11-05_024': {'PSNR': 39.89265823364258, 'MSE': 0.0001025024030241184, 'measurement_sha256': '7741dc02f1d6be8f57a28ea8481b78ebc8753f694382f612b6a09a4acc42ceda', 'confusion_sha256': '0f7f9ace0a7cc57a7a29a8fc3dffc99916c728937e594d281c0d3d2ab88428ed'}, '2021-11-05_035': {'PSNR': 38.92475509643555, 'MSE': 0.0001280926662730053, 'measurement_sha256': '59f204c967d2992fc5ab5facb9a3c1718f5a3853c13c095716ae5728bf79192a', 'confusion_sha256': '10265381fdb6743feb67b3b1868c43aeb5e69b979a116f53a8c225d235d94d8d'}, '2021-11-05_041': {'PSNR': 38.532447814941406, 'MSE': 0.0001402022608090192, 'measurement_sha256': 'd8beeb5b38f29b5cd0fc46ed1d56300fc319e409ab48e59f73faff5c82acfa34', 'confusion_sha256': '4349d165065bb20a0a423a0fb651de57795edcf68ea69f6bc4cf2e74cad4fe89'}, '2021-11-05_046': {'PSNR': 35.87843322753906, 'MSE': 0.00025831893435679376, 'measurement_sha256': '55e8f56e3636a5d68b0e02f63c1bff0083deacceb7915d9945f23d946360e3f0', 'confusion_sha256': 'd50ddcbdd8fc8a47f8c654aab1110df3cc3fbd96cf5e7cbd0666b1a232b2ddef'}, '2021-11-10_014': {'PSNR': 38.14520263671875, 'MSE': 0.00015327792789321393, 'measurement_sha256': 'e277db658c0fe737d2081b68ba266495cd36c2c756332fc8b657fb00efa653bb', 'confusion_sha256': '91f4f7f77b41154bdade44a01018d2aa3a58c9843fb69eb89272af62b3b83aef'}, '2021-11-10_024': {'PSNR': 37.95246887207031, 'MSE': 0.00016023337957449257, 'measurement_sha256': 'c8a63f51f8c53dbd8978961dfbfc8258a5042298b9dc3dc5bc2a3e02be29bfde', 'confusion_sha256': '5016df6d33d366e3fe7109f8df25fd0dbfd7784388dcfe5b16852a3fe401c176'}, '2021-11-10_029': {'PSNR': 38.31328582763672, 'MSE': 0.00014745898079127073, 'measurement_sha256': '7be966210bc7cf1f9f8579c909c00a151e44d1c8473d0b8183d9c9ad4d9f463d', 'confusion_sha256': '3d8b0cc926ddb2e5cca5cb41652721f9f6687de6e76e5ad422f91297e6f1fb3c'}, '2021-11-10_050': {'PSNR': 37.42839431762695, 'MSE': 0.00018078411812894046, 'measurement_sha256': '309aa876bd050bf484d3afc49b5b4debd2a407d26881fb47de2f6f387f7228a5', 'confusion_sha256': '56a6570bd4715f45ea18bf12b92cb63984212428f71f3e29642bad0f39ee4c43'}}, 'guarded': {'2021-11-03_046': {'PSNR': 40.10894775390625, 'MSE': 9.752257028594613e-05, 'measurement_sha256': '5191111e68360ca27820d1afaad39e01c4025fd9e080b5bd43b4014924c2eaf8', 'confusion_sha256': '782114b3e1c5eb3e244e4bc645383bf7dc1b55991018038956c5cea783161986'}, '2021-11-03_047': {'PSNR': 38.89791488647461, 'MSE': 0.00012888673518318683, 'measurement_sha256': '7a6412fc0c1f42a41ed81c6443e75351eb9fea7c9b11393ffe639a85d04612fe', 'confusion_sha256': 'd6f9a3006ff30db15e51c662100b9a97c2bceea7f1d760d81b0d7bc9d65d6a15'}, '2021-11-03_057': {'PSNR': 38.11849594116211, 'MSE': 0.00015422349679283798, 'measurement_sha256': 'd2351df833a4b4a9424297a2658d694a6ef4b860548f7afbe88f571826a176da', 'confusion_sha256': 'c8400afa8c8280849cd8cbe232579f5a2d68ff4f4788ae52fe3cf4cc6ddd64b4'}, '2021-11-03_085': {'PSNR': 40.8642463684082, 'MSE': 8.195495320251212e-05, 'measurement_sha256': 'c9e43b2281aa15ea374fea53621047c152b9d3bea4b49dea300b670648546c6e', 'confusion_sha256': '09c2a8ba7c522bb43cfb9d20447c90b1ce128319e573eddf37a6be1a56471050'}, '2021-11-03_090': {'PSNR': 40.66996765136719, 'MSE': 8.57043924042955e-05, 'measurement_sha256': '18b4c6dc7af3cde6e22733a096a4dfac787a7e59d02c62cdddf7acd47b4743a3', 'confusion_sha256': '967053e1ef3b81d9911a42f1a35c362c2074a4192c94d5d534fe3d8a1c21b5d9'}, '2021-11-03_110': {'PSNR': 39.72430419921875, 'MSE': 0.00010655393271008506, 'measurement_sha256': '24e52021df1f97df92a857c79b65efb664079d4bcebdac7b77cc8295cc0b4359', 'confusion_sha256': '58728b961101f056711d6cc50ba2ed576cec20a55e8767282d6048836764a8f7'}, '2021-11-04_010': {'PSNR': 36.94813919067383, 'MSE': 0.00020192310330457985, 'measurement_sha256': '46cf4e1a53d55fbf79f34641b021da1ca1927d82a70cf058327fa4902e43793d', 'confusion_sha256': 'a16f4f71f8cd126d245b52b7a5429fbc786df851f67cbceb522fcdadc311dd41'}, '2021-11-04_017': {'PSNR': 38.4373893737793, 'MSE': 0.00014330484555102885, 'measurement_sha256': 'cd41b9014db6172d44923f4989566995d1c7ce5588c25d591e589ceb31d81a34', 'confusion_sha256': 'e7e5bf14bffbf62f2baf215a3083af0ecb2f9333b53c21c47b3a1de6e577e40c'}, '2021-11-04_024': {'PSNR': 38.725624084472656, 'MSE': 0.00013410276733338833, 'measurement_sha256': '4b532914673e7f970c4cad27433d95f4023818e8e325a688d4119c5432b209e5', 'confusion_sha256': '76af67467cdf0277182a948641cd8fdf4973f6af93a11ce4f8201f85c0923a57'}, '2021-11-04_042': {'PSNR': 40.77299880981445, 'MSE': 8.369508577743545e-05, 'measurement_sha256': 'ac460d346d881b5d954e309d39439bcf7e3f7fe7801192d523c746b1f8e0a56b', 'confusion_sha256': 'd3ecafc0cd9d9450d334f88c4aac8186276ddc6090447e701a6eacafa1446e4e'}, '2021-11-04_047': {'PSNR': 40.52860641479492, 'MSE': 8.853992767399177e-05, 'measurement_sha256': '025f043649abfa9e1f5cbfbd07f472d6866bdf6916ee4f4088a9c8899e082683', 'confusion_sha256': 'e8be1ff276b3bd3f9b44cd599ea3315522e82225c1faeacc0c412f017cb52b5d'}, '2021-11-04_049': {'PSNR': 40.965576171875, 'MSE': 8.006492134882137e-05, 'measurement_sha256': '6b5fbc808927ab3def28d010fe0bff80d765342f1094e7c5dc0560a17e5be18b', 'confusion_sha256': '9a066097d65d0b20c99affeff509fcd7a0ad641fca2ad9cef5e82d991fcbd0eb'}, '2021-11-04_055': {'PSNR': 41.03412628173828, 'MSE': 7.881109195295721e-05, 'measurement_sha256': 'cf74da7ef5193903d7b30586ffc2d4c6ddf6d07029ca1c566fc509f31a1022fe', 'confusion_sha256': 'ad04b9ebb4989da11ebaf8e829947b55a88567f83f4af5acf91b5da00261c579'}, '2021-11-04_061': {'PSNR': 41.03514862060547, 'MSE': 7.87925673648715e-05, 'measurement_sha256': '2ac2a9e2aee12e6740259103afe0d0f5a1e7ced6f75025e0f0fb910fca4d39d8', 'confusion_sha256': 'e3c44de88ba15c424444299afb4514ad23951f21ebdd096018deee0e122f621a'}, '2021-11-04_093': {'PSNR': 39.32668685913086, 'MSE': 0.00011676997382892296, 'measurement_sha256': 'a1fdcd1d86ad979b5585560f9de30646c6bf1ee8010bda943643b10f60f3cb77', 'confusion_sha256': '6eb61e187dae2461d3bc0afb666abf420aeb78af21722ce0b0fcec34ab4fc459'}, '2021-11-04_098': {'PSNR': 39.74116897583008, 'MSE': 0.00010614100756356493, 'measurement_sha256': '72b6223790ff9461b7d788d3c81b9ce3e34641fe9250bea030a3aa8efc52224e', 'confusion_sha256': '006b5d6a1a6552c51118c671a1820b17f098a4731f5120c7d5a52e74b39fceb6'}, '2021-11-05_010': {'PSNR': 37.17367935180664, 'MSE': 0.00019170444284100085, 'measurement_sha256': 'd39ffba0dc82719c254d478b2edd54568cbf2fbb9a683f7e95faf1c335821a33', 'confusion_sha256': 'a9fac63905818d2d64e6f1a0801dccba5db6737e6268ba32b948f1b4341408fe'}, '2021-11-05_024': {'PSNR': 40.00386047363281, 'MSE': 9.99111871351488e-05, 'measurement_sha256': '7741dc02f1d6be8f57a28ea8481b78ebc8753f694382f612b6a09a4acc42ceda', 'confusion_sha256': '14ace487bc14781d4c76fa29cf21eb085521cdbaa5d3253d379ed4d896f70be3'}, '2021-11-05_035': {'PSNR': 38.94403839111328, 'MSE': 0.00012752521433867514, 'measurement_sha256': '59f204c967d2992fc5ab5facb9a3c1718f5a3853c13c095716ae5728bf79192a', 'confusion_sha256': '82df1d50233bdd5eecafb9ebf94d641a93a4da40a891559a1fa23a6bf6f9cfb9'}, '2021-11-05_041': {'PSNR': 38.557533264160156, 'MSE': 0.00013939481868874282, 'measurement_sha256': 'd8beeb5b38f29b5cd0fc46ed1d56300fc319e409ab48e59f73faff5c82acfa34', 'confusion_sha256': '761974a6109a0c9019f5a2698811a76310ec53b409b959538b43843908095a64'}, '2021-11-05_046': {'PSNR': 35.87215805053711, 'MSE': 0.00025869274395518005, 'measurement_sha256': '55e8f56e3636a5d68b0e02f63c1bff0083deacceb7915d9945f23d946360e3f0', 'confusion_sha256': '8c6b38429ba4d1a7ea375c0f633848200e6f6d58463a3dc308a7067f7d59eb8a'}, '2021-11-10_014': {'PSNR': 38.1336555480957, 'MSE': 0.00015368608001153916, 'measurement_sha256': 'e277db658c0fe737d2081b68ba266495cd36c2c756332fc8b657fb00efa653bb', 'confusion_sha256': '4915a4bef0a0546dcf2babdd1bb6e1ee9e88f4d281757acd2537710691977b1a'}, '2021-11-10_024': {'PSNR': 37.95493698120117, 'MSE': 0.0001601423427928239, 'measurement_sha256': 'c8a63f51f8c53dbd8978961dfbfc8258a5042298b9dc3dc5bc2a3e02be29bfde', 'confusion_sha256': '727f6ca2fc4724ecca7d575b2ef82634567857bd13951ea40b564c8cf8a89ae6'}, '2021-11-10_029': {'PSNR': 38.319820404052734, 'MSE': 0.00014723728236276656, 'measurement_sha256': '7be966210bc7cf1f9f8579c909c00a151e44d1c8473d0b8183d9c9ad4d9f463d', 'confusion_sha256': '3138e71774f351e9b58f3b95f099ce5e8ad31e86b37c0478134e8be93ec23bcf'}, '2021-11-10_050': {'PSNR': 37.44084930419922, 'MSE': 0.00018026646284852177, 'measurement_sha256': '309aa876bd050bf484d3afc49b5b4debd2a407d26881fb47de2f6f387f7228a5', 'confusion_sha256': 'd2016d80ad7fa0d6eb9fd54218c11fef36a1909fb4f7e6c5d44c70a47cd6d543'}}}, 'plus1_alpha0.5': {'control': {'2021-11-03_046': {'PSNR': -1.363975167274475, 'MSE': 1.3689813613891602, 'measurement_sha256': 'd1569fbd087bbfa0101197b8d70b739a99b5ecc2209b9c8b8b8524c6a0b44a3b', 'confusion_sha256': 'bf27cdfe7b4a5f21586e0659c0ed948e60bfa4aa1fbb4d4cb3001212ce7909de'}, '2021-11-03_047': {'PSNR': 5.316623687744141, 'MSE': 0.29399341344833374, 'measurement_sha256': 'ef9e3d48797b4deafa1e07d06711d78f053681ddb38a4f2f105d97d8f97c4f13', 'confusion_sha256': '88e1a82124c000646f5241e91f1af508e42e8b3b090c92f3b20972ff4f90e0f6'}, '2021-11-03_057': {'PSNR': 11.915732383728027, 'MSE': 0.06433195620775223, 'measurement_sha256': '2a92d484e835efbbe3a00be45386b7309a677ea82f24a39f290c92d732e97fcb', 'confusion_sha256': 'a4aa8e2240018278f2589aebba0ba36e0fb4ef9935824d5836868e1317bcd21c'}, '2021-11-03_085': {'PSNR': -0.6169565916061401, 'MSE': 1.152645230293274, 'measurement_sha256': 'd600cd8868afd32451b17d8f58a9bc7b53e7f1d520ddb3bb75bdd2758c497670', 'confusion_sha256': '9e291d35b81f5f0fa82e432823ce10d5236fc686379432ff3c5e70631bbcd1f4'}, '2021-11-03_090': {'PSNR': 0.24649420380592346, 'MSE': 0.9448232650756836, 'measurement_sha256': '0a69798b56158c2a53ae7ddc52c34a3b957c23d1ef01e36537eefc13d51c28ee', 'confusion_sha256': '1562218b685c7277b0b839f058fe7c3f26267204e578cd75029e69bd63518c99'}, '2021-11-03_110': {'PSNR': -0.8625420331954956, 'MSE': 1.2197033166885376, 'measurement_sha256': 'a7d18c410c16fabc111e43009c1930bdd615b7f55d6765ad7ad94130f1dad368', 'confusion_sha256': 'ad9b42436e32edffd0b0aca22d285f9809f76cc392aedb1fc152850ff0170470'}, '2021-11-04_010': {'PSNR': -1.8874379396438599, 'MSE': 1.544343113899231, 'measurement_sha256': '1f633eb3482c8a4c0595c018892a604c564d25f135756558b1bbf256449bc5ad', 'confusion_sha256': '57dbe7546be68f99ca8a0a60d21534258a3e2be889925aff5962cf0dc86e83d1'}, '2021-11-04_017': {'PSNR': 3.2026588916778564, 'MSE': 0.4783371388912201, 'measurement_sha256': 'f4134e54210103a66809f70fa0053fe12c7697700add845a070a642464dad732', 'confusion_sha256': 'b0728666b6ebfa38f1786a9fb13c1c70538ac70f203477870d55f1c0047a3160'}, '2021-11-04_024': {'PSNR': -10.712839126586914, 'MSE': 11.783761024475098, 'measurement_sha256': '59a56fac82f93a58e85e8c9f6e75de9dc113f728f65f12f66c5c809714bdcb15', 'confusion_sha256': '2e712d94105a0c8e91593c3ba7380da947e51dd01b7ce3dc7a034a7e9e9ef724'}, '2021-11-04_042': {'PSNR': -6.362588405609131, 'MSE': 4.327717304229736, 'measurement_sha256': 'aa33fc0412979b1d2c345020c610adbcaa69e79ff257af9f12bec2c0f665bb67', 'confusion_sha256': 'b7250f9135e3fd4323ed0ead9c67ef2c41b68bbc05be73c27de8836dfbb35dd7'}, '2021-11-04_047': {'PSNR': -21.918745040893555, 'MSE': 155.5516815185547, 'measurement_sha256': '1298a6775e31924c45d53dbebf0908aefdc00fbddfee0b3a5d0e5ec47fc36a94', 'confusion_sha256': '6fd43bdd1f5edd997e120f6b8678aaf6d61b438783db1e6a66e7748e772529cd'}, '2021-11-04_049': {'PSNR': -32.45771408081055, 'MSE': 1761.0489501953125, 'measurement_sha256': 'f7cde70867dc459f5e80ca7bb9c05baaae419e344f93e2319f64d38b4101a294', 'confusion_sha256': 'd49d0dee5d6eb969b09bf7f28e04c02e46debb5026fad516adec999425436b1e'}, '2021-11-04_055': {'PSNR': -8.492502212524414, 'MSE': 7.067246437072754, 'measurement_sha256': '7054c1a647bfa61ed3768e7aca72a9fc9a3c84ab96cec35c1aa2b85fcd703aaa', 'confusion_sha256': '98da3f9ab9569d2c0090ba01f66f898eda9323e6d5bce92d3e7daf6ac8dbb58a'}, '2021-11-04_061': {'PSNR': 2.7215030193328857, 'MSE': 0.5343793630599976, 'measurement_sha256': 'cb725348dbad6e9dc88f4e2d8bf2191b6f0e0c3df0707ab4a6e6cc1477286b7f', 'confusion_sha256': '957405da8e7bdfa5282da6864b0c168a3b170b6f5656610a4deb6a8f05f07eca'}, '2021-11-04_093': {'PSNR': 2.992377758026123, 'MSE': 0.5020676255226135, 'measurement_sha256': 'af550f8eda7cf71c5160c7e835cfd71c93ab24c226124e9d723069879e78b503', 'confusion_sha256': '30868ce6c9edcd81c2ea1974cfebae49696fba1f9d80d504bfc1af61c31be0a2'}, '2021-11-04_098': {'PSNR': -0.12061398476362228, 'MSE': 1.028161644935608, 'measurement_sha256': 'aceba9854c51f81bddc33620b7d558fea8db8ddd49209f4cb987b8c6810ce8d7', 'confusion_sha256': 'b860c669f3db6489ad59374ebf0abfed1376efd451beab5b51037f1fbe8ce643'}, '2021-11-05_010': {'PSNR': -43.247920989990234, 'MSE': 21124.791015625, 'measurement_sha256': '85b7f224eaef2e67e1744854fdae951978fdefc2c3a1786c53576c8172a371eb', 'confusion_sha256': '34b6f5cf66ada610bdb0fc6b922c7a17230affbd2d5c3ae08d89d4281c7ee16e'}, '2021-11-05_024': {'PSNR': 13.678030967712402, 'MSE': 0.042874276638031006, 'measurement_sha256': '83cc23f617484d0ed62113aaa9970521f71b95fa51e7a87161d5e520e70af137', 'confusion_sha256': '37b8f181ea65db0bbd7229c28481d74d787a92cdf71c08db19428bc9cad3dcde'}, '2021-11-05_035': {'PSNR': -39.56440353393555, 'MSE': 9045.6611328125, 'measurement_sha256': '9cc2c5d163454044450792cbbbffc5c8b288e8b62e05fbba92b8a701656194b2', 'confusion_sha256': '790cda229efd333174664502ead8eaeb4523fea6a275842dce699e6342ec0b0c'}, '2021-11-05_041': {'PSNR': -22.991605758666992, 'MSE': 199.14096069335938, 'measurement_sha256': '98fcc575bbf0c3c39ad6eb7bbd12bcc728a0b324867bff4edc7528cd18d1b68d', 'confusion_sha256': '90944709bf1674d8d9d1fbe66a0aa40e40b51a4fb04cbb2507f7f83fe0eeec33'}, '2021-11-05_046': {'PSNR': -7.5923638343811035, 'MSE': 5.744290828704834, 'measurement_sha256': '57ff027300f26f7537f68862e384ef14d11095d5db024355a22b711dac39c57d', 'confusion_sha256': '774c6cdc1bd1e69a447c0bdba68d63e6f98788c0647959d955e1728cf343de26'}, '2021-11-10_014': {'PSNR': -12.353215217590332, 'MSE': 17.191808700561523, 'measurement_sha256': 'd53013e94c7c3286a298ed3d412e00c0a308bd022f236663bb994e3388602cee', 'confusion_sha256': 'd2470eca013f35d370a69eb18b08ee3d9084ea9b0d48c22221b87cda72026c2b'}, '2021-11-10_024': {'PSNR': -8.723740577697754, 'MSE': 7.453738212585449, 'measurement_sha256': 'cb20fcb3203c3fa0809f73121f859102c71e3c6028298bced053e598b57251e5', 'confusion_sha256': '6c13b9189323cea5683b49f3da36df334cb3516ad79f211a9a3ea2a500c37a47'}, '2021-11-10_029': {'PSNR': -19.393218994140625, 'MSE': 86.96050262451172, 'measurement_sha256': 'e374149d2935d25d0743258f982c2abffaed0e7a97feda359e318dff06d1b897', 'confusion_sha256': '997d70d08e6197d6665e456859ef947819a2df3fcf8e82c19715987d8d1943b9'}, '2021-11-10_050': {'PSNR': -10.41392707824707, 'MSE': 11.000001907348633, 'measurement_sha256': 'c7dff76d75a9e427765188e43332608e2669c5300d5583d1a089a5bfc7c766bf', 'confusion_sha256': 'a77c51779d6a005154d577223ba76f6b7ddb36b658e8a716034097ecd1824acc'}}, 'guarded': {'2021-11-03_046': {'PSNR': 37.32080078125, 'MSE': 0.0001853189169196412, 'measurement_sha256': 'd1569fbd087bbfa0101197b8d70b739a99b5ecc2209b9c8b8b8524c6a0b44a3b', 'confusion_sha256': 'c8bc92a7d31874097f41144bac77e5675c5ea5bc274c8e812266bc496d79ed8d'}, '2021-11-03_047': {'PSNR': 35.75098419189453, 'MSE': 0.0002660120080690831, 'measurement_sha256': 'ef9e3d48797b4deafa1e07d06711d78f053681ddb38a4f2f105d97d8f97c4f13', 'confusion_sha256': 'aea8b86cb084683fe4cbb75825ab229bea78c97053fd7979e0605080bf2a8100'}, '2021-11-03_057': {'PSNR': 34.94248962402344, 'MSE': 0.0003204431268386543, 'measurement_sha256': '2a92d484e835efbbe3a00be45386b7309a677ea82f24a39f290c92d732e97fcb', 'confusion_sha256': '47c519acb77ec6661ccb7de64a8bc77e11a644d12b80ce71a89bcbc677b9fe4b'}, '2021-11-03_085': {'PSNR': 37.35795211791992, 'MSE': 0.00018374036881141365, 'measurement_sha256': 'd600cd8868afd32451b17d8f58a9bc7b53e7f1d520ddb3bb75bdd2758c497670', 'confusion_sha256': '88e8b14e8dd37a776b3139588a546a95e31f21574f268220abdffe147498ba29'}, '2021-11-03_090': {'PSNR': 36.49522399902344, 'MSE': 0.00022411838290281594, 'measurement_sha256': '0a69798b56158c2a53ae7ddc52c34a3b957c23d1ef01e36537eefc13d51c28ee', 'confusion_sha256': '3af291c446101546d781b852754dae26cbe0506ffc2b64b3cd61a7c933a9c265'}, '2021-11-03_110': {'PSNR': 37.236209869384766, 'MSE': 0.00018896395340561867, 'measurement_sha256': 'a7d18c410c16fabc111e43009c1930bdd615b7f55d6765ad7ad94130f1dad368', 'confusion_sha256': '785f3cd22e3cc6633e17db1b5205947124381addd54840f7ae5d65c284231f5d'}, '2021-11-04_010': {'PSNR': 34.012168884277344, 'MSE': 0.0003969928657170385, 'measurement_sha256': '1f633eb3482c8a4c0595c018892a604c564d25f135756558b1bbf256449bc5ad', 'confusion_sha256': '017a12f7c536ce4628a2bf8c4bedaee7bb60de899d03a63192fc594275a546cd'}, '2021-11-04_017': {'PSNR': 35.14459228515625, 'MSE': 0.0003058728761970997, 'measurement_sha256': 'f4134e54210103a66809f70fa0053fe12c7697700add845a070a642464dad732', 'confusion_sha256': 'fdf0d03f5218afc58b3a3db5c4dba763df7f53f8a1a13323cde5d6aab6726312'}, '2021-11-04_024': {'PSNR': 36.3045539855957, 'MSE': 0.0002341769722988829, 'measurement_sha256': '59a56fac82f93a58e85e8c9f6e75de9dc113f728f65f12f66c5c809714bdcb15', 'confusion_sha256': '72acf2724bd044f5c44d3e90adab31cc2208af5a4f231183aac09ecb97c27e1f'}, '2021-11-04_042': {'PSNR': 37.30693054199219, 'MSE': 0.00018591164553072304, 'measurement_sha256': 'aa33fc0412979b1d2c345020c610adbcaa69e79ff257af9f12bec2c0f665bb67', 'confusion_sha256': 'd2ff9c8b356bc5e67aa86b5433cfa9d49d09eb76af2d9f35856f9bdf99298de8'}, '2021-11-04_047': {'PSNR': 37.52788162231445, 'MSE': 0.00017668992222752422, 'measurement_sha256': '1298a6775e31924c45d53dbebf0908aefdc00fbddfee0b3a5d0e5ec47fc36a94', 'confusion_sha256': '481c946f13ac2c88b71e195b63b45c8fed9c4552543f53f07f400a398bf2228c'}, '2021-11-04_049': {'PSNR': 37.313629150390625, 'MSE': 0.00018562520563136786, 'measurement_sha256': 'f7cde70867dc459f5e80ca7bb9c05baaae419e344f93e2319f64d38b4101a294', 'confusion_sha256': '17848a8e0a686960a63d246e93a7610074afaf1a75776e425f68ee6ef66def41'}, '2021-11-04_055': {'PSNR': 37.94948959350586, 'MSE': 0.00016034334839787334, 'measurement_sha256': '7054c1a647bfa61ed3768e7aca72a9fc9a3c84ab96cec35c1aa2b85fcd703aaa', 'confusion_sha256': 'be0fb637c66f98f9091b73314b4f1c01a72ef91e31e2cd8c3883fe63f51656ca'}, '2021-11-04_061': {'PSNR': 37.78083419799805, 'MSE': 0.00016669262549839914, 'measurement_sha256': 'cb725348dbad6e9dc88f4e2d8bf2191b6f0e0c3df0707ab4a6e6cc1477286b7f', 'confusion_sha256': 'a018e750a0f8949c96962f73eafcf0549092eb7c3edbd32fc7b5419aea10ee23'}, '2021-11-04_093': {'PSNR': 36.983543395996094, 'MSE': 0.00020028368453495204, 'measurement_sha256': 'af550f8eda7cf71c5160c7e835cfd71c93ab24c226124e9d723069879e78b503', 'confusion_sha256': '12f8cf0bf7eea767f0cc482f26bf023defc8f35a7aa5c08f5fba51ba84906090'}, '2021-11-04_098': {'PSNR': 36.95447540283203, 'MSE': 0.00020162870350759476, 'measurement_sha256': 'aceba9854c51f81bddc33620b7d558fea8db8ddd49209f4cb987b8c6810ce8d7', 'confusion_sha256': 'd84316107927f5ba91ccfc85809194063cb10a955ddf26554fede99b94069376'}, '2021-11-05_010': {'PSNR': 33.9002685546875, 'MSE': 0.0004073549644090235, 'measurement_sha256': '85b7f224eaef2e67e1744854fdae951978fdefc2c3a1786c53576c8172a371eb', 'confusion_sha256': '8761f79507dfe0863a0bc07d9035c05ade7962bfc99c7dcd9dc7fe45e6c948be'}, '2021-11-05_024': {'PSNR': 36.98481369018555, 'MSE': 0.00020022505486849695, 'measurement_sha256': '83cc23f617484d0ed62113aaa9970521f71b95fa51e7a87161d5e520e70af137', 'confusion_sha256': '20bd6ceec1e2ac746ac1cc7faa0fddb179716ae168543cb4c02f044ffc7f1895'}, '2021-11-05_035': {'PSNR': 35.19392013549805, 'MSE': 0.0003024181060027331, 'measurement_sha256': '9cc2c5d163454044450792cbbbffc5c8b288e8b62e05fbba92b8a701656194b2', 'confusion_sha256': 'de64a7b6347f2b3c2c74fc0c921d87503ae2e3a8a8ce6126e52b1c6f8435fab1'}, '2021-11-05_041': {'PSNR': 35.10770034790039, 'MSE': 0.0003084818890783936, 'measurement_sha256': '98fcc575bbf0c3c39ad6eb7bbd12bcc728a0b324867bff4edc7528cd18d1b68d', 'confusion_sha256': 'acf5211b8cd0bfafabfdaea68e5531d702e0b3a4c0b7c3926888990a13da5421'}, '2021-11-05_046': {'PSNR': 33.01795196533203, 'MSE': 0.0004991195164620876, 'measurement_sha256': '57ff027300f26f7537f68862e384ef14d11095d5db024355a22b711dac39c57d', 'confusion_sha256': '840389b13ca2b023ce880616bcf0889b67bd79f865c2e491f49ff076d1a9225c'}, '2021-11-10_014': {'PSNR': 34.53233337402344, 'MSE': 0.0003521816397551447, 'measurement_sha256': 'd53013e94c7c3286a298ed3d412e00c0a308bd022f236663bb994e3388602cee', 'confusion_sha256': '75a32ffa5d159ccf954bb53af39b8326a399fa25c06db454bb4f5601cbdc817f'}, '2021-11-10_024': {'PSNR': 33.191524505615234, 'MSE': 0.0004795649438165128, 'measurement_sha256': 'cb20fcb3203c3fa0809f73121f859102c71e3c6028298bced053e598b57251e5', 'confusion_sha256': '3ab1b75c6a6982e4f39bc30d73e85e99e86409f57dfbac2deda901fd1be6d71c'}, '2021-11-10_029': {'PSNR': 35.13845443725586, 'MSE': 0.00030630530091002584, 'measurement_sha256': 'e374149d2935d25d0743258f982c2abffaed0e7a97feda359e318dff06d1b897', 'confusion_sha256': '56626506c8d15819392fd1f71291e52c9e80159d184462020cb3ec407b844167'}, '2021-11-10_050': {'PSNR': 34.020259857177734, 'MSE': 0.00039625423960387707, 'measurement_sha256': 'c7dff76d75a9e427765188e43332608e2669c5300d5583d1a089a5bfc7c766bf', 'confusion_sha256': 'e89d3acdc967f238040907e0c7d59d44ebfa10d77c02915a7bfbafc243673c86'}}}, 'minus1_alpha0.5': {'control': {'2021-11-03_046': {'PSNR': -2.620938301086426, 'MSE': 1.8284952640533447, 'measurement_sha256': '3c37205c88751c1b1fda3a2d81fe474f03ccdeb74d09d9fa8de73c095c65eae4', 'confusion_sha256': '2763099295bc483f143e66987dfd62f780d22812cecef6fda65b781041336d5e'}, '2021-11-03_047': {'PSNR': 4.0961127281188965, 'MSE': 0.38939350843429565, 'measurement_sha256': '91d5a5ca3605fca9d0adf6d65f0a3fe6f5272ed647aaa3c63e757c3a7a304330', 'confusion_sha256': '440467e21294c85e7b7a187d635ad15e33f4b1791299e9b0434fee35e9ff6bc4'}, '2021-11-03_057': {'PSNR': 10.862268447875977, 'MSE': 0.08199230581521988, 'measurement_sha256': 'd2cc0ec611a7d1e35783805537bbdff61b5f275fc2d8aafadc356f8512b2e9c0', 'confusion_sha256': 'eaab71c2b1c37745fe1800bb333e896973e916af8e0e5bbfc7f0d7a16bdbd6ae'}, '2021-11-03_085': {'PSNR': -1.3196297883987427, 'MSE': 1.3550739288330078, 'measurement_sha256': '43ce39c58fdcb6a43150b664d2f0122bc570e2eeae649f230ee3b162f185ac12', 'confusion_sha256': '24ff55b15e2c903084c690c77ef6c5ecfaae8a2afcef80057a043971c346bd52'}, '2021-11-03_090': {'PSNR': -0.9033111929893494, 'MSE': 1.2312071323394775, 'measurement_sha256': '13c9955940927509af2088c79891c505022d17a8007d3a5d2d3d8fe72bb99e82', 'confusion_sha256': 'c6dac58b559c73fd886e9f12c282df45faa1aff658573dee8ecfbb19be3cb897'}, '2021-11-03_110': {'PSNR': -1.6036540269851685, 'MSE': 1.4466564655303955, 'measurement_sha256': '8dcc03862fde90d214cdb745576890df5c64ae4c7cb0af628c106c910af90e58', 'confusion_sha256': 'ead8141bef3e59508f2824a039f6ba39ec24be800582dd2d9b60e78508472a2b'}, '2021-11-04_010': {'PSNR': -2.454202175140381, 'MSE': 1.7596254348754883, 'measurement_sha256': 'af9e96b426bcf3b9d046c0fecf2d4e4b19f64e6b2b0348571689465ea14b62a8', 'confusion_sha256': '7adb38510bc853ae04112a6ff3830d07eb978ff7bd33c10e47614dfad8e78e00'}, '2021-11-04_017': {'PSNR': 2.0616886615753174, 'MSE': 0.6220583319664001, 'measurement_sha256': 'f4216789c692c922f1e6cc76b1b86a8332ac8c5039b84b6181dadca0dde678e1', 'confusion_sha256': 'd05e2dc46558af01f27231a678a529c7ef34e6b6e275b8ec51a5296efc4c5b0e'}, '2021-11-04_024': {'PSNR': -12.273303985595703, 'MSE': 16.87837028503418, 'measurement_sha256': 'c8a0350510ac7d5c29ee61c78cc50b630bb120fb6f12ad08183bf7f91bd810c6', 'confusion_sha256': '045a9a4ec30be7dccf53fc1f2adb83861b58d145eccdc8c07f4d8c609f30ed16'}, '2021-11-04_042': {'PSNR': -7.9944167137146, 'MSE': 6.301467418670654, 'measurement_sha256': '1fb41e1e9ead692aaea703e69167d2cc38a23b2d58236568d8899ff010896289', 'confusion_sha256': 'a604e1fde67305a4f2d064f4020c29dff805950ae451a362bfb777051296c27b'}, '2021-11-04_047': {'PSNR': -23.439090728759766, 'MSE': 220.7542724609375, 'measurement_sha256': '69303fed14407b7dc8deb9f3542d9f9a043392e160f290e0a41ccb51ca139916', 'confusion_sha256': 'd578b904072d9816665edc124a71f6a6eb72128f14b0bc85f64d861798d43367'}, '2021-11-04_049': {'PSNR': -33.879486083984375, 'MSE': 2443.142822265625, 'measurement_sha256': 'f156816c2afde5ba38e7302ff534d620e3958cafc0546077c21f94c8fb0cf196', 'confusion_sha256': '7fca0f4e129378f8dc7c08eff5cb2389680eb7be031a92a51554ec7a6e61ef5b'}, '2021-11-04_055': {'PSNR': -8.898296356201172, 'MSE': 7.759427547454834, 'measurement_sha256': '3db4f2a51def332be797ae3deec230b067c353438fc8169c2595bbf60a49bdff', 'confusion_sha256': 'a04a6eb947b0500d559fb1b56705f20f57648105b7f1336395d4764b0c8d865f'}, '2021-11-04_061': {'PSNR': 1.5082430839538574, 'MSE': 0.7066033482551575, 'measurement_sha256': 'b626c34836fcad5bde18398be8cde1bb8ffbb2bd57db706a65e3686f345e85a3', 'confusion_sha256': '00fd890155099ff029d4e92b2b5bf4b8e4291c589da733e017ff0ec95d07343b'}, '2021-11-04_093': {'PSNR': 2.0571577548980713, 'MSE': 0.6227076649665833, 'measurement_sha256': '84d9bfbb7b7507601ae16b5d0277c23d184435da375cfc97e1b884d595bacc6b', 'confusion_sha256': 'f53e737285ded01c0606c94478b48eb40b2f650c8f6609ea915016e0b267cfd8'}, '2021-11-04_098': {'PSNR': -1.501569151878357, 'MSE': 1.4130480289459229, 'measurement_sha256': 'eacda5b7202611ace0f59e8fc8ec2984f0fd2478688f33a0b129cf58af2364c7', 'confusion_sha256': '736d12953d48c89d7cfc9589c8124ca771c7c4299e66937c5851442af400ea2c'}, '2021-11-05_010': {'PSNR': -27.195751190185547, 'MSE': 524.2943725585938, 'measurement_sha256': '27d07a23855778a431504c8f73fc6b71c7cd99754e7bed43493b34d1218098b2', 'confusion_sha256': '80d869a9c24a5eb81dea85d33e4b8e29a022c2a2397333a294fcc854ac23e197'}, '2021-11-05_024': {'PSNR': 12.03718376159668, 'MSE': 0.06255780905485153, 'measurement_sha256': '351df64428463fd8040aadb30ae2153e9348ecfb32b9c551e9d7b5507a3d45d4', 'confusion_sha256': 'ead809249b50ac223d15f694e47aebbd55b563d9aea01401815fc68ae63cdbce'}, '2021-11-05_035': {'PSNR': -30.965368270874023, 'MSE': 1248.926513671875, 'measurement_sha256': '9cec7803ca4988ccad8b6f38291c2ae245f66a7eaf371debef903227f03b414b', 'confusion_sha256': '8c0b7811c26795ab2de846d62d18c4d82587b8c80072df12b0365aa7660bf6be'}, '2021-11-05_041': {'PSNR': -27.137920379638672, 'MSE': 517.3590698242188, 'measurement_sha256': '0f6873d407cb09812f5953f206aa2babe83f201c16a82aecafeb838eb802b350', 'confusion_sha256': 'e04b5fd3a8e622e3118ece9596e071b120ac732cdc20528219365db2f2a22d55'}, '2021-11-05_046': {'PSNR': -7.835624694824219, 'MSE': 6.075226783752441, 'measurement_sha256': '96449e8d2ca0ad045f3f2d68c87e5ebdbd15edf9978244604a8a0fe531e8f6ed', 'confusion_sha256': 'c521611f822f3d7feab34aa82722f601bbcfb77b1357b0e643d59e8f08cb3259'}, '2021-11-10_014': {'PSNR': -12.90121078491211, 'MSE': 19.50388526916504, 'measurement_sha256': '6d592a181502db28ad76ac8c0707bcc4e5762795e7b058895be952dda5e7affc', 'confusion_sha256': '8b31545c9bc4724ffce31040ee7ccfa2fa51e7e54bfea1dbd1c585f2fc7972b6'}, '2021-11-10_024': {'PSNR': -8.90362548828125, 'MSE': 7.768955230712891, 'measurement_sha256': '0759ae65a45ec20862497dfa321a8d48c2133720bfa4980daa0563ced61a226b', 'confusion_sha256': 'e7234d17e99c2d52b83ffaeb466ecc329c6832913456bb091cf0cfc41523adf0'}, '2021-11-10_029': {'PSNR': -21.59422492980957, 'MSE': 144.35191345214844, 'measurement_sha256': '8d1db35b5184310713b9591d453375276c1e4d3e468deb96aa003346810111e4', 'confusion_sha256': 'f0e709989734a2d05d0655f71969a2b591dc038f43d5d3beac49bd33a4031622'}, '2021-11-10_050': {'PSNR': -12.316097259521484, 'MSE': 17.045499801635742, 'measurement_sha256': 'b9568579d78bd9bf9c03fdc07119645d029f6b01901c0eefcc9f48b7f8458adc', 'confusion_sha256': '8cadd3d6783ae8b96bba1c73d91b30e2f9d00e82f314cfd0ccf22f8822079d27'}}, 'guarded': {'2021-11-03_046': {'PSNR': 37.3604621887207, 'MSE': 0.00018363427079748362, 'measurement_sha256': '3c37205c88751c1b1fda3a2d81fe474f03ccdeb74d09d9fa8de73c095c65eae4', 'confusion_sha256': 'de17f867eaf5fbf451de04e5791edbf9d7bc222162406fbd9abd06d97bf19912'}, '2021-11-03_047': {'PSNR': 35.7398796081543, 'MSE': 0.0002666931541170925, 'measurement_sha256': '91d5a5ca3605fca9d0adf6d65f0a3fe6f5272ed647aaa3c63e757c3a7a304330', 'confusion_sha256': '4c506e20742c3f39eef7f42f61c57bef088226c580c15e489f8864c4d0fb0df4'}, '2021-11-03_057': {'PSNR': 34.89922332763672, 'MSE': 0.00032365130027756095, 'measurement_sha256': 'd2cc0ec611a7d1e35783805537bbdff61b5f275fc2d8aafadc356f8512b2e9c0', 'confusion_sha256': '30f471bfb0ef09beb34fb892fe0ff3abfb5f48ee6ab67c540d3c453b84013a03'}, '2021-11-03_085': {'PSNR': 37.351505279541016, 'MSE': 0.00018401343550067395, 'measurement_sha256': '43ce39c58fdcb6a43150b664d2f0122bc570e2eeae649f230ee3b162f185ac12', 'confusion_sha256': '8f0ef97ec95acf6b5faf6f16251ad389bad57d3194a063be6361e79039dff6a6'}, '2021-11-03_090': {'PSNR': 36.492210388183594, 'MSE': 0.0002242739574285224, 'measurement_sha256': '13c9955940927509af2088c79891c505022d17a8007d3a5d2d3d8fe72bb99e82', 'confusion_sha256': '3cded070f9e9f4f05de48b4f29e02ec5f7c224da606940a1726fcc0b420a364a'}, '2021-11-03_110': {'PSNR': 37.34746170043945, 'MSE': 0.00018418474064674228, 'measurement_sha256': '8dcc03862fde90d214cdb745576890df5c64ae4c7cb0af628c106c910af90e58', 'confusion_sha256': 'c1e1ce53ed93e1053948832fec6e2aacdfa9ca24888353eb300e707172f3380c'}, '2021-11-04_010': {'PSNR': 34.18732452392578, 'MSE': 0.0003813004295807332, 'measurement_sha256': 'af9e96b426bcf3b9d046c0fecf2d4e4b19f64e6b2b0348571689465ea14b62a8', 'confusion_sha256': '47d9d2db1054e89022a3986af28c3c6ae2ca922856f235c96d881817495fc8d3'}, '2021-11-04_017': {'PSNR': 35.33766555786133, 'MSE': 0.00029257236747071147, 'measurement_sha256': 'f4216789c692c922f1e6cc76b1b86a8332ac8c5039b84b6181dadca0dde678e1', 'confusion_sha256': 'da91aef8f711ca2914bdf52e461e9801febf65786b5d7532700139c394e5a4e5'}, '2021-11-04_024': {'PSNR': 36.325443267822266, 'MSE': 0.00023305344802793115, 'measurement_sha256': 'c8a0350510ac7d5c29ee61c78cc50b630bb120fb6f12ad08183bf7f91bd810c6', 'confusion_sha256': '639b10a17dd0552271affbd2f9a8e030d50e585dd282af392c73d114dcdc66bb'}, '2021-11-04_042': {'PSNR': 37.31441116333008, 'MSE': 0.00018559176533017308, 'measurement_sha256': '1fb41e1e9ead692aaea703e69167d2cc38a23b2d58236568d8899ff010896289', 'confusion_sha256': 'd5b9c276b62077ca0301eec879909f2619cb1ebed2d467341486fbdbaebca7a5'}, '2021-11-04_047': {'PSNR': 37.639808654785156, 'MSE': 0.000172194471815601, 'measurement_sha256': '69303fed14407b7dc8deb9f3542d9f9a043392e160f290e0a41ccb51ca139916', 'confusion_sha256': '91ffcaa5e8c2f476f1482d7a719d473497b7f32928468d6ee4787bf1b9ce6d83'}, '2021-11-04_049': {'PSNR': 37.25491714477539, 'MSE': 0.00018815157818607986, 'measurement_sha256': 'f156816c2afde5ba38e7302ff534d620e3958cafc0546077c21f94c8fb0cf196', 'confusion_sha256': '301ecf963e3e78b6c5595eb3b20f85b206de64707fd40bc87ba78d8191acd796'}, '2021-11-04_055': {'PSNR': 37.942935943603516, 'MSE': 0.00016058549226727337, 'measurement_sha256': '3db4f2a51def332be797ae3deec230b067c353438fc8169c2595bbf60a49bdff', 'confusion_sha256': 'e02017b1f74719b34d533dd584627ad52443c0b1a2fc686875481ebd68075a74'}, '2021-11-04_061': {'PSNR': 37.74317169189453, 'MSE': 0.00016814449918456376, 'measurement_sha256': 'b626c34836fcad5bde18398be8cde1bb8ffbb2bd57db706a65e3686f345e85a3', 'confusion_sha256': 'c9b9a0770085d03ff5f94370db64610b7de3b3237248a0220b7813cb0c9d9c8d'}, '2021-11-04_093': {'PSNR': 36.92219924926758, 'MSE': 0.00020313273125793785, 'measurement_sha256': '84d9bfbb7b7507601ae16b5d0277c23d184435da375cfc97e1b884d595bacc6b', 'confusion_sha256': '271e7b8be15c266529ea14c15634251ccd454d0d51ab49521cd996d697e75495'}, '2021-11-04_098': {'PSNR': 36.98240661621094, 'MSE': 0.00020033599867019802, 'measurement_sha256': 'eacda5b7202611ace0f59e8fc8ec2984f0fd2478688f33a0b129cf58af2364c7', 'confusion_sha256': '8197fa291244750e3fe101433700b2380450be206351f26b07e8eadea8e34c28'}, '2021-11-05_010': {'PSNR': 33.87629699707031, 'MSE': 0.0004096094344276935, 'measurement_sha256': '27d07a23855778a431504c8f73fc6b71c7cd99754e7bed43493b34d1218098b2', 'confusion_sha256': '8cf2efc76c9d863bf84f0fda3b22c4e2337508eeb9e61eb8882f5a323bcc10b6'}, '2021-11-05_024': {'PSNR': 37.0014533996582, 'MSE': 0.00019945930398534983, 'measurement_sha256': '351df64428463fd8040aadb30ae2153e9348ecfb32b9c551e9d7b5507a3d45d4', 'confusion_sha256': '82f7c28576495206f9f0f043aa1af84dcf26ec0ccc44dbb3dc056e98d29ff0eb'}, '2021-11-05_035': {'PSNR': 35.395851135253906, 'MSE': 0.00028867865330539644, 'measurement_sha256': '9cec7803ca4988ccad8b6f38291c2ae245f66a7eaf371debef903227f03b414b', 'confusion_sha256': '9bcc1863ca72f3e7c8150f6805e5d612c60349bfc903c655fbabe4ce00bf61bb'}, '2021-11-05_041': {'PSNR': 35.163612365722656, 'MSE': 0.0003045359335374087, 'measurement_sha256': '0f6873d407cb09812f5953f206aa2babe83f201c16a82aecafeb838eb802b350', 'confusion_sha256': '741781c195ede49dfaca4c344b21813dec59487c3c0d348756abfc7f102bd19f'}, '2021-11-05_046': {'PSNR': 33.12107849121094, 'MSE': 0.0004874072619713843, 'measurement_sha256': '96449e8d2ca0ad045f3f2d68c87e5ebdbd15edf9978244604a8a0fe531e8f6ed', 'confusion_sha256': 'e239c53ada3117ed47b6f4b670fea265ce3f74d970f7dccd0a4341ad1c952c90'}, '2021-11-10_014': {'PSNR': 34.57276153564453, 'MSE': 0.000348918343661353, 'measurement_sha256': '6d592a181502db28ad76ac8c0707bcc4e5762795e7b058895be952dda5e7affc', 'confusion_sha256': 'e8b6c4fc63fad9e149e8da7d9505f885aa3d10ec6c55f979bced28148f09a2f7'}, '2021-11-10_024': {'PSNR': 33.23871994018555, 'MSE': 0.00047438155161216855, 'measurement_sha256': '0759ae65a45ec20862497dfa321a8d48c2133720bfa4980daa0563ced61a226b', 'confusion_sha256': '163c9dd57306f569fec770e815894a574c4c46ace00bcfa275b94dab7fdbf151'}, '2021-11-10_029': {'PSNR': 35.17164611816406, 'MSE': 0.0003039733855985105, 'measurement_sha256': '8d1db35b5184310713b9591d453375276c1e4d3e468deb96aa003346810111e4', 'confusion_sha256': '6ce5b75fdcadd4d0d763317624a9e63d5d2dd45707ee130f0fa4c4a1224b0c81'}, '2021-11-10_050': {'PSNR': 34.098106384277344, 'MSE': 0.00038921466330066323, 'measurement_sha256': 'b9568579d78bd9bf9c03fdc07119645d029f6b01901c0eefcc9f48b7f8458adc', 'confusion_sha256': 'b2cd818fe97a357f2678bc7d07190a4e59c59ce1abe1c96c870eaca3f0dee503'}}}, 'nominal_noise40': {'control': {'2021-11-03_046': {'PSNR': 37.441551208496094, 'MSE': 0.00018023732991423458, 'measurement_sha256': '3e4dc5c4c27d7bacbb12289d34fb7a6840a63b8d2438103b9d63b6067513d371', 'confusion_sha256': '4259964e6204c7154172171ef51d5252c25f108ec83534bb836ea421be135dc8'}, '2021-11-03_047': {'PSNR': 36.64181900024414, 'MSE': 0.00021667961846105754, 'measurement_sha256': '498d201ef78ad9a90db5685ffa4c74687474aca1ecd3a2b9e6ec10e3f88b84b8', 'confusion_sha256': 'e82c9727a8f2943539ed5e19793de57944a1f5d827ccc72367901ad1771c8fdd'}, '2021-11-03_057': {'PSNR': 35.9923210144043, 'MSE': 0.00025163308600895107, 'measurement_sha256': '6994edb35bbfbb48fd86b16774c46c3ad0268d1c53a5ec75099cc3e1bff22321', 'confusion_sha256': '9fb19938f49a9ba7ce7b91ced3b4c2194440cdb501c3bea7a6e0ea00e592ede2'}, '2021-11-03_085': {'PSNR': 38.21639633178711, 'MSE': 0.000150785650475882, 'measurement_sha256': '7e420da1d171f49aa1eab75354a06172adaa90d0620f9f095f4ce81472dff0e0', 'confusion_sha256': '0f17cdf7e61e0aea983411d039953b34daad1a17e8fa3fc44e1b7a513d83a039'}, '2021-11-03_090': {'PSNR': 38.20994186401367, 'MSE': 0.00015100999735295773, 'measurement_sha256': '4c4094ce4134a9b1dbd30134e810d6ec83181c68dc406f919ea0562edd9d17de', 'confusion_sha256': '7cf5a06b9cb48359250585ea381159fd51fdbeee8455a897edbc442de1e7d927'}, '2021-11-03_110': {'PSNR': 37.237857818603516, 'MSE': 0.00018889213970396668, 'measurement_sha256': '3200116965a883a48c7a968038f6809637ccf88c17709fd30b198aed702b1904', 'confusion_sha256': '74df1e8dc0748df6f59e5d13bfb637b5b2ed788540ffacfe4eba531e63c9cf68'}, '2021-11-04_010': {'PSNR': 35.57490158081055, 'MSE': 0.0002770190767478198, 'measurement_sha256': '94e7fe26e1f1a77eeceb3f04007073b08ab23f7917d5579de068ec939bf85027', 'confusion_sha256': '7a9999ff339ebe551b1ad48b7739d4f925e6d4241b0822bb55de92f50996e9f1'}, '2021-11-04_017': {'PSNR': 36.52423858642578, 'MSE': 0.00022262598213274032, 'measurement_sha256': 'c00a6cbc325a0749c6e68a5f4d367231b8da4ffa1b57275bd9f3d1101a757b1e', 'confusion_sha256': 'c785b2174c02f22a19438294183f17821e59afb8c9ff9ca961f1c4d73fc652d5'}, '2021-11-04_024': {'PSNR': 37.19729995727539, 'MSE': 0.000190664577530697, 'measurement_sha256': '3bb7b37b49757dea7cb93c83f3c88208f5f998a8967b39b776cc42862dec7e85', 'confusion_sha256': 'dcd211e1f01c13321fb186a986232259d040a04fedebf074d46814d4e385b836'}, '2021-11-04_042': {'PSNR': 38.32109832763672, 'MSE': 0.00014719399041496217, 'measurement_sha256': '34da13a2d10f8967feaa0ef2c31fd81741971f174db3d02aa9dc5c05644a0e8f', 'confusion_sha256': '690dfa10cea362e04729806b74e82cd9bccff10717317dd42e2067829022f92b'}, '2021-11-04_047': {'PSNR': 38.119441986083984, 'MSE': 0.00015418969269376248, 'measurement_sha256': 'cf36d4c57fc4897fa8209cad382efd38246936fa26c02d581667f7c653a98b4c', 'confusion_sha256': '4944f6dfd4a6a09e39e4b1baede558d5d7a2b58ba0b0f4dcf033a594b1b3ea6f'}, '2021-11-04_049': {'PSNR': 38.42966079711914, 'MSE': 0.00014356010069604963, 'measurement_sha256': 'b46fea4ddd919dcb9ef846d02734a8f66e7f70428218b69f5415f23877cb8712', 'confusion_sha256': 'ad62c2761ab6ff045c102258f17c82fd017c70883fd90429c76d55650281216c'}, '2021-11-04_055': {'PSNR': 37.95415496826172, 'MSE': 0.000160171213792637, 'measurement_sha256': '23f66cf61af7dfd57016eb5edbeafa9886382b13efd95516645c947ae93be57e', 'confusion_sha256': '2b7738ca2cb2bc4c375184d9d99c5ac72c48898c8c53e1456f6aaa5e00e1c6c0'}, '2021-11-04_061': {'PSNR': 38.16327667236328, 'MSE': 0.00015264132525771856, 'measurement_sha256': 'e87f55bf3d2d88f12ac98b54a221df07eaa7bf49de5ed9fe1c87d0ba15f6c101', 'confusion_sha256': 'd69bed25be15adfc7637201c5b08eac2499f606c300f54916d3d749ef0e060d3'}, '2021-11-04_093': {'PSNR': 37.20384979248047, 'MSE': 0.00019037719175685197, 'measurement_sha256': 'dcd5254449a0d1f518ddaddc10e9821863d90645143b69ea95508520bb3e6861', 'confusion_sha256': 'e67041478aecd75200b057bfc6c42df474cac45772b81248b1f538f32a5fff49'}, '2021-11-04_098': {'PSNR': 37.51494216918945, 'MSE': 0.0001772170653566718, 'measurement_sha256': 'a062e650086309acdddb1dc177e8a8f0c3f1e413e4f486dcc2f9772e5a6aa3d5', 'confusion_sha256': 'daeca1136c514b16a54c4dbec3567d0ea6fcb88ba1520186c374c4f97a9f4189'}, '2021-11-05_010': {'PSNR': 35.629085540771484, 'MSE': 0.0002735844173002988, 'measurement_sha256': '85baa2f3a4cf2c9cbca614131aa26a429548f6718f218ab87778870b8684ff3c', 'confusion_sha256': '1dad75e8b6b482001417b350f3844f1abfd7d397d6e33cdb5ac7a993543cc8b7'}, '2021-11-05_024': {'PSNR': 37.48832321166992, 'MSE': 0.00017830661090556532, 'measurement_sha256': 'c65ca67d4a86b06af922d4126d977a863221843021c6be626769df3f8efce1c7', 'confusion_sha256': 'b9780f7cb5dacc0cd9d300b671205f9be502a050fe1f0353be03131bf3b85f54'}, '2021-11-05_035': {'PSNR': 37.00413513183594, 'MSE': 0.00019933625299017876, 'measurement_sha256': '4b7e8daff1ead546f9667ae2d331a4f803e94c8b1bd62900e580225f1c9e7c27', 'confusion_sha256': '38abf9435e25da668067ed94f8f26217b731e3ccf70aa68fe3e5e68a2025e3ca'}, '2021-11-05_041': {'PSNR': 36.60607147216797, 'MSE': 0.00021847047901246697, 'measurement_sha256': 'eb6d7f8b8f72ec35006bd721e2c115585ea5272c5e14f24fed14086ddd176a56', 'confusion_sha256': 'fba7f148217e4ceede8391d0d7cca21a005412b96d06e7889f197b891d6e52d2'}, '2021-11-05_046': {'PSNR': 34.62989044189453, 'MSE': 0.0003443585883360356, 'measurement_sha256': '278158520b781bceae27698a5bf396f42c15a6e394ebf2e81b29451151dcf8ef', 'confusion_sha256': '6ac80fa5e729e19673a14f57098ca5fe5aa59e4d5d2d47047000f1add6cf07be'}, '2021-11-10_014': {'PSNR': 36.294342041015625, 'MSE': 0.0002347283298149705, 'measurement_sha256': 'eb2a692b15bd8cdc1328bf27fc30fd7c661328f0c0b839aca554fe9d75f2cdb4', 'confusion_sha256': '1d145b05aea7192cec9ff3e3c27fa480e0871aac888caa2605ae25c50317f349'}, '2021-11-10_024': {'PSNR': 36.042484283447266, 'MSE': 0.00024874319205991924, 'measurement_sha256': 'bd305d8d9f63b9081f169b4acdc3b068df4362797224406ebc658cb9537398f7', 'confusion_sha256': '8ef2b3ac1a49765a1fb685dce2ebbfc20cb58d02d13c0c5d016c1b3c6fab90f2'}, '2021-11-10_029': {'PSNR': 36.33841323852539, 'MSE': 0.00023235849221237004, 'measurement_sha256': '04dc843ccc1386c24270b44109525eefd5e7424b6c3666e42fe26217c8604334', 'confusion_sha256': 'ef08b86d770ced9a74350a9030b7e5c842d5949687acb1590ca093d0f042d1d0'}, '2021-11-10_050': {'PSNR': 35.847564697265625, 'MSE': 0.00026016164338216186, 'measurement_sha256': '01fe60deefb30b194cc597611e17d1b2a0eb50e6662de15b5d0d2b7af13bd607', 'confusion_sha256': '15b4883a03355279108397da7586670412ec365326c8add872b28c23fffabf7f'}}, 'guarded': {'2021-11-03_046': {'PSNR': 37.7697868347168, 'MSE': 0.0001671172067290172, 'measurement_sha256': '3e4dc5c4c27d7bacbb12289d34fb7a6840a63b8d2438103b9d63b6067513d371', 'confusion_sha256': '0ae4ea319bfcded7068fe73e9f77fbe8889e565673d2bb573fdf50b011f845bd'}, '2021-11-03_047': {'PSNR': 36.9085693359375, 'MSE': 0.00020377125474624336, 'measurement_sha256': '498d201ef78ad9a90db5685ffa4c74687474aca1ecd3a2b9e6ec10e3f88b84b8', 'confusion_sha256': 'f82cc62fec1454314fd09ad9d00bcf791945750c507f163581a7bf11aa9bb34c'}, '2021-11-03_057': {'PSNR': 36.19538879394531, 'MSE': 0.00024013803340494633, 'measurement_sha256': '6994edb35bbfbb48fd86b16774c46c3ad0268d1c53a5ec75099cc3e1bff22321', 'confusion_sha256': '645b074e4fe0dd5bdc1b9d239fc27dd2cb463701ccedd08ed618af3a2460ad73'}, '2021-11-03_085': {'PSNR': 38.53007888793945, 'MSE': 0.00014027880388312042, 'measurement_sha256': '7e420da1d171f49aa1eab75354a06172adaa90d0620f9f095f4ce81472dff0e0', 'confusion_sha256': 'f067d1f17b7e09cf6299d03c5143bdb47070a008537029c91805cd0bacc69284'}, '2021-11-03_090': {'PSNR': 38.52151107788086, 'MSE': 0.00014055569772608578, 'measurement_sha256': '4c4094ce4134a9b1dbd30134e810d6ec83181c68dc406f919ea0562edd9d17de', 'confusion_sha256': '230ebb414ce6d8f97ef0f5911b21d88cf071078b38f6139d5452642e233119e3'}, '2021-11-03_110': {'PSNR': 37.52504348754883, 'MSE': 0.00017680540622677654, 'measurement_sha256': '3200116965a883a48c7a968038f6809637ccf88c17709fd30b198aed702b1904', 'confusion_sha256': 'efdb24755e5f4e605bbc5cecbdeed19da655b28781e8b7f026237c3361d33030'}, '2021-11-04_010': {'PSNR': 35.6777229309082, 'MSE': 0.00027053762460127473, 'measurement_sha256': '94e7fe26e1f1a77eeceb3f04007073b08ab23f7917d5579de068ec939bf85027', 'confusion_sha256': '0b5002f78d82178ca42ca74f25436ffa73ec613495a0c1723938bcd50f193c93'}, '2021-11-04_017': {'PSNR': 36.63553237915039, 'MSE': 0.00021699343051295727, 'measurement_sha256': 'c00a6cbc325a0749c6e68a5f4d367231b8da4ffa1b57275bd9f3d1101a757b1e', 'confusion_sha256': 'a23da8321b345f43debbad8eb4839e39d0cb629bb94a971bc0b1a4ed0401c42f'}, '2021-11-04_024': {'PSNR': 37.39862823486328, 'MSE': 0.00018202739011030644, 'measurement_sha256': '3bb7b37b49757dea7cb93c83f3c88208f5f998a8967b39b776cc42862dec7e85', 'confusion_sha256': '8af908f3c1d224a9f1d4e6846456263d0cf610f1d7932883cbdc78e2ee15e574'}, '2021-11-04_042': {'PSNR': 38.63909912109375, 'MSE': 0.0001368011871818453, 'measurement_sha256': '34da13a2d10f8967feaa0ef2c31fd81741971f174db3d02aa9dc5c05644a0e8f', 'confusion_sha256': 'f8aa9baf40605b9c48e2c41130542bbea1356bb549a0b083887771acc0d8a90e'}, '2021-11-04_047': {'PSNR': 38.45887756347656, 'MSE': 0.00014259752060752362, 'measurement_sha256': 'cf36d4c57fc4897fa8209cad382efd38246936fa26c02d581667f7c653a98b4c', 'confusion_sha256': '6dd39a6563763cadda73d36eec360ac0ac1d7e83883b96c9758661f627ac8bba'}, '2021-11-04_049': {'PSNR': 38.75672912597656, 'MSE': 0.00013314560055732727, 'measurement_sha256': 'b46fea4ddd919dcb9ef846d02734a8f66e7f70428218b69f5415f23877cb8712', 'confusion_sha256': 'd163ae987ab66df2ddf37a2c1682b25eba68ffb7a99d58c4f09ac1a79973e5fd'}, '2021-11-04_055': {'PSNR': 38.34196090698242, 'MSE': 0.0001464885863242671, 'measurement_sha256': '23f66cf61af7dfd57016eb5edbeafa9886382b13efd95516645c947ae93be57e', 'confusion_sha256': '4c9d54c43b5dd1f670e13007dc286a8406efc68e3333e243d9eb43ccad75162f'}, '2021-11-04_061': {'PSNR': 38.51255416870117, 'MSE': 0.0001408460084348917, 'measurement_sha256': 'e87f55bf3d2d88f12ac98b54a221df07eaa7bf49de5ed9fe1c87d0ba15f6c101', 'confusion_sha256': '7f65c39a3901761a50927f6f6cfc77cb78037cb5930f65594d720002cb82039b'}, '2021-11-04_093': {'PSNR': 37.45402908325195, 'MSE': 0.00017972027126234025, 'measurement_sha256': 'dcd5254449a0d1f518ddaddc10e9821863d90645143b69ea95508520bb3e6861', 'confusion_sha256': '81d9982cba87c2b0fd29bde37669b015135d758b95102f93ea6e6dcfc89f1d83'}, '2021-11-04_098': {'PSNR': 37.804656982421875, 'MSE': 0.00016578067152295262, 'measurement_sha256': 'a062e650086309acdddb1dc177e8a8f0c3f1e413e4f486dcc2f9772e5a6aa3d5', 'confusion_sha256': '121cb75cc6a53fd19a2b7cdbaf1eb09defccc357c31c7fa1713fe690755f250e'}, '2021-11-05_010': {'PSNR': 35.70376968383789, 'MSE': 0.00026891985908150673, 'measurement_sha256': '85baa2f3a4cf2c9cbca614131aa26a429548f6718f218ab87778870b8684ff3c', 'confusion_sha256': 'fb8c2b1d0e351cd9f3d30e6849f87ac94dcb61901db717e45a7cac459613f941'}, '2021-11-05_024': {'PSNR': 37.821502685546875, 'MSE': 0.0001651390630286187, 'measurement_sha256': 'c65ca67d4a86b06af922d4126d977a863221843021c6be626769df3f8efce1c7', 'confusion_sha256': 'fb8dcffad4ea1139301dbacde72c5f8f3a442ba856d7df44aab4ad31eee8b1d1'}, '2021-11-05_035': {'PSNR': 37.22248840332031, 'MSE': 0.0001895619643619284, 'measurement_sha256': '4b7e8daff1ead546f9667ae2d331a4f803e94c8b1bd62900e580225f1c9e7c27', 'confusion_sha256': '8e50b0495f8abda9c0a2b5f589e1dc492fb15ff242dc78adaba6c4a789d4f14c'}, '2021-11-05_041': {'PSNR': 36.80583953857422, 'MSE': 0.00020864872203674167, 'measurement_sha256': 'eb6d7f8b8f72ec35006bd721e2c115585ea5272c5e14f24fed14086ddd176a56', 'confusion_sha256': '867aa91f77d0d8ba24b5e362dd731ff60ef6b03e15eaf7c56d584db5e82d0cfc'}, '2021-11-05_046': {'PSNR': 34.679134368896484, 'MSE': 0.00034047593362629414, 'measurement_sha256': '278158520b781bceae27698a5bf396f42c15a6e394ebf2e81b29451151dcf8ef', 'confusion_sha256': '6cd9a2071e091e5a833b3c4647a04d5ad44ddef4309e477fdfa83cd4f31bfc00'}, '2021-11-10_014': {'PSNR': 36.424827575683594, 'MSE': 0.0002277808089274913, 'measurement_sha256': 'eb2a692b15bd8cdc1328bf27fc30fd7c661328f0c0b839aca554fe9d75f2cdb4', 'confusion_sha256': 'a3dac9d1dc20ee6cbd4371115f6b61b1eff18f4234cbeebe74b577079fba9138'}, '2021-11-10_024': {'PSNR': 36.19593811035156, 'MSE': 0.00024010769266169518, 'measurement_sha256': 'bd305d8d9f63b9081f169b4acdc3b068df4362797224406ebc658cb9537398f7', 'confusion_sha256': 'ce78ab8dc7604b0321b92fc169192d26a4d99f84a7b2b9c4802a8079473376ef'}, '2021-11-10_029': {'PSNR': 36.492881774902344, 'MSE': 0.0002242392220068723, 'measurement_sha256': '04dc843ccc1386c24270b44109525eefd5e7424b6c3666e42fe26217c8604334', 'confusion_sha256': '935e1da4120a81f7b6685d2e290e3206e16de1e5e01d1107f5c168cc8c8cc249'}, '2021-11-10_050': {'PSNR': 35.982791900634766, 'MSE': 0.00025218576774932444, 'measurement_sha256': '01fe60deefb30b194cc597611e17d1b2a0eb50e6662de15b5d0d2b7af13bd607', 'confusion_sha256': '8a81f3893566916fdae3c372023f4f0bf527163dca873e09894219cfbc3260ba'}}}, 'nominal_noise30': {'control': {'2021-11-03_046': {'PSNR': 32.019222259521484, 'MSE': 0.0006281708483584225, 'measurement_sha256': '6b116b7ac4297d89875c44773289a163bcf6323477a221d4c9b1020d5859b145', 'confusion_sha256': '09a349e96a5d27ceb7a7dfe58f0fa6818a67fa71a05d99c2e853eaabfc210c98'}, '2021-11-03_047': {'PSNR': 31.5387020111084, 'MSE': 0.000701664830558002, 'measurement_sha256': '4f5dca535357effbb6d5aeaba6b67c9c91a251bd64c5e5c0efd417e23e3ed6a8', 'confusion_sha256': 'b8e7f32e955b0956dc2e988979d72e9e2b8d02069ef4e94e91d3121360c7a2f4'}, '2021-11-03_057': {'PSNR': 31.381582260131836, 'MSE': 0.0007275143289007246, 'measurement_sha256': '421fbca6eb1d0322e7c41ae2ebb90ebfa10dbc49ef8d141f2ec2d2e2ec7da0f9', 'confusion_sha256': 'e30c4901660b8624439ba1d77ea70baae632fcc6a86b1fe258f2b70eb33b06bf'}, '2021-11-03_085': {'PSNR': 32.60420227050781, 'MSE': 0.0005490091280080378, 'measurement_sha256': '5792a5b856ebbafeb8839caadb92732599056eb67c755a4b37d93d409db211a1', 'confusion_sha256': '12de126e18bfe0dde5e5ef1ddd5e94f37b2575df0fb31cb58f16c803b6b81e0f'}, '2021-11-03_090': {'PSNR': 32.680755615234375, 'MSE': 0.000539416738320142, 'measurement_sha256': '37d3075c9bdb885a78d1adc3770f95242f9efe292f153d913681ec5e61c14b03', 'confusion_sha256': '17b99c8758ea7b0bbc16ffe739e378e687058910e462979941f203a68a75274a'}, '2021-11-03_110': {'PSNR': 31.85803985595703, 'MSE': 0.0006519222515635192, 'measurement_sha256': 'bb2787d626f6ebae2479b5b28d4ef44e4d271f89b918a460dced157695607d75', 'confusion_sha256': 'a6546b0d0169d768f7add5ff6dd579a6c8985006fdebacb848258208fc0be8d8'}, '2021-11-04_010': {'PSNR': 31.437833786010742, 'MSE': 0.0007181521505117416, 'measurement_sha256': '574348bfc78c5a4ef01e41d908e0f1246cd2ef2411a39025a26673beeed7cef8', 'confusion_sha256': '99b725c1e43c5d7ab033c6e113a07a24430f75da6df598b142ae33442e26dc64'}, '2021-11-04_017': {'PSNR': 31.719350814819336, 'MSE': 0.000673077127430588, 'measurement_sha256': 'f2c1fc3a1867a401a8830c7df106ff15363a644a4a6d2bb8f2c015ebfa5d95e5', 'confusion_sha256': 'c410683ea4e7a4e0eeeec334df8bed5e54ecea799f153a60acd463628ef873e7'}, '2021-11-04_024': {'PSNR': 32.28474426269531, 'MSE': 0.000590915500652045, 'measurement_sha256': '8fe1aa0e2ee3165140fd3870306a2f62fdf34a2db253eb83b862be708024cefa', 'confusion_sha256': '1841e030954d2029736480ebd343b231882db00057449ede86b381d22d7efd82'}, '2021-11-04_042': {'PSNR': 32.51279067993164, 'MSE': 0.0005606874474324286, 'measurement_sha256': 'c18213aa55da17b39d687a96b7dcaa0afca31bd03537eef0053bf2622dc08d17', 'confusion_sha256': '62dc2d81f99f2a731d7095e5a0619ba881e24db44559dad8523f592b056d3f19'}, '2021-11-04_047': {'PSNR': 32.574615478515625, 'MSE': 0.0005527620669454336, 'measurement_sha256': 'fa8542625141d7d0425d56302cae43bb4fe82c34438c2534766d48234fba093a', 'confusion_sha256': '2df65c2cda9090ab8e4358b3d9dd083c08a9050fc9310702a6f710d28d186895'}, '2021-11-04_049': {'PSNR': 32.72580337524414, 'MSE': 0.0005338502232916653, 'measurement_sha256': '3d1dc580085603aba03c6dea0c00f3f4f22585fe8e537b52822550ad4b0401bd', 'confusion_sha256': '6c35ebc35df20691bc9ff4924787566ad56d18d4ae7b52aa319dcf75b6b12236'}, '2021-11-04_055': {'PSNR': 32.316375732421875, 'MSE': 0.0005866270512342453, 'measurement_sha256': '8daf7c5eab29f12a14de4542185e4ce7c3701b1c7009efeeae8d054463ef9be6', 'confusion_sha256': 'c227ed06dc5a96bc4f0d719b88d4e55b928e279a6bc1197f0cd5c2b86fb9a4cc'}, '2021-11-04_061': {'PSNR': 32.458717346191406, 'MSE': 0.0005677118897438049, 'measurement_sha256': '76571d839fd815213a720028a0dea1e7c67a9771ecf41fa040116f41b88b197e', 'confusion_sha256': '648779fca4e3e028b233836449861ae432f2cc340dff6037aee4a4bec914fe65'}, '2021-11-04_093': {'PSNR': 32.3366584777832, 'MSE': 0.0005838939687237144, 'measurement_sha256': '3b87377460978cbf83282f69c8bc59e923bbee0091c1539d54d463e0e4faa286', 'confusion_sha256': '1a63283b0c5fe8fe461bbbf6d8fedf470bdd86b961639a9059d0864588c6c934'}, '2021-11-04_098': {'PSNR': 32.503196716308594, 'MSE': 0.0005619273870252073, 'measurement_sha256': 'f1b03e9f68c5819c19e2947f086b58d436a122d4903542062dca70ab4287db04', 'confusion_sha256': '42ccfa2d20739fe5c0f7ed16f4e6c59202aea5c057a1e634598d1817e2a07788'}, '2021-11-05_010': {'PSNR': 31.576108932495117, 'MSE': 0.000695647147949785, 'measurement_sha256': '82bfdf416b690183b07eac8ff7f95afc6080b1b0af3286cf749b20909ce1bda0', 'confusion_sha256': '054c131277cbd68f889cc734a4801d8efc36d76fb6cc7ce8212dbfdcae9e7a95'}, '2021-11-05_024': {'PSNR': 32.52799606323242, 'MSE': 0.0005587278865277767, 'measurement_sha256': '1590c87d257e7af56499f63bf35fd198e24fc655cceba3559efb1490d37048b7', 'confusion_sha256': 'e8fb2768e2329b62cfb297c53eaa08119e83a40d2665e92845b0248ea59fe430'}, '2021-11-05_035': {'PSNR': 32.341190338134766, 'MSE': 0.0005832848255522549, 'measurement_sha256': 'd24a53bfd9da196f8f3121cb81f98e1b9ba8d82afffd415ca99f23f4ef437081', 'confusion_sha256': '6a4c703938ad26c5dd6abeb7879952d39cb817000b0728f62e2d9435913215b4'}, '2021-11-05_041': {'PSNR': 32.016700744628906, 'MSE': 0.0006285353447310627, 'measurement_sha256': '64108b76e502b1b50cd5d408d7bf2e22650bfd382f33dd4db298eae54928f8ec', 'confusion_sha256': '82ec9ad10be2295604a77d173f957adf174da999fb59622f30695573ef832913'}, '2021-11-05_046': {'PSNR': 30.946348190307617, 'MSE': 0.0008042018162086606, 'measurement_sha256': '529822dac51afb5c5b5dd9679c9d66330839c81e965f0eb5555ff5a6186c2a5e', 'confusion_sha256': 'c6321ee1887a145ed2da53c81d0a9b52e8317a25950dca64c0c7e1b79d7aeea6'}, '2021-11-10_014': {'PSNR': 31.633211135864258, 'MSE': 0.0006865604664199054, 'measurement_sha256': '1b8d46279497f949832fc555b8f83b63a7dc362e951cefd5f8cccf9384ae77d3', 'confusion_sha256': '0fc480a4842e0b2a0ab07d93e4283eccd89071b6f2b9edf777cababd516ba8e3'}, '2021-11-10_024': {'PSNR': 31.193099975585938, 'MSE': 0.0007597836083732545, 'measurement_sha256': '3cd6daa626d7d626f725cd261e7c8b270e86a554ee30588dc1eb9fe61f1c4f07', 'confusion_sha256': 'cf752fe6df336a856cb87155a747fb031a69493c1bfb7239952afde701b9a2a7'}, '2021-11-10_029': {'PSNR': 31.574810028076172, 'MSE': 0.0006958552403375506, 'measurement_sha256': 'a76e550b9212038fc80b336730883483e737681692d749a06c44b1a92e0eda67', 'confusion_sha256': 'e7cf4a875faaa08eaa69518811239a81e6203b220213718d5b3eae062d4cea1f'}, '2021-11-10_050': {'PSNR': 31.297901153564453, 'MSE': 0.000741668336559087, 'measurement_sha256': '8b26ff6696703808ea783fdbda1524525d6be1e244b0eb10c151c9dc23e0eaa4', 'confusion_sha256': 'caabe42c9e00204a90bc63f2cb031547399fbbd8e26af9af2177af9a31d48da3'}}, 'guarded': {'2021-11-03_046': {'PSNR': 32.61248016357422, 'MSE': 0.000547963660210371, 'measurement_sha256': '6b116b7ac4297d89875c44773289a163bcf6323477a221d4c9b1020d5859b145', 'confusion_sha256': 'ab166d80a40656c17d1556bacf2af1ea5dca9273be8c87a29427554713ea91b8'}, '2021-11-03_047': {'PSNR': 32.07294464111328, 'MSE': 0.000620448321569711, 'measurement_sha256': '4f5dca535357effbb6d5aeaba6b67c9c91a251bd64c5e5c0efd417e23e3ed6a8', 'confusion_sha256': '62f75d68c87551af6d2298d1f3e5d171f09697e9d0444cd2c1bf3a4dadab0297'}, '2021-11-03_057': {'PSNR': 31.900053024291992, 'MSE': 0.0006456458941102028, 'measurement_sha256': '421fbca6eb1d0322e7c41ae2ebb90ebfa10dbc49ef8d141f2ec2d2e2ec7da0f9', 'confusion_sha256': 'b7571953dfaf1ee07d85ec101ae14725b9569daf860d7e9a09f08c35d42d54db'}, '2021-11-03_085': {'PSNR': 33.31599044799805, 'MSE': 0.00046601591748185456, 'measurement_sha256': '5792a5b856ebbafeb8839caadb92732599056eb67c755a4b37d93d409db211a1', 'confusion_sha256': 'e9fb21be25afcbb1eede8727e15f5a832e20c3791103f5e3ff60153fc79ed6e0'}, '2021-11-03_090': {'PSNR': 33.33252716064453, 'MSE': 0.00046424506581388414, 'measurement_sha256': '37d3075c9bdb885a78d1adc3770f95242f9efe292f153d913681ec5e61c14b03', 'confusion_sha256': 'b9a49a323ee722dcafc2875cce9e6187c21240e33ee03e924273c22513a8bee7'}, '2021-11-03_110': {'PSNR': 32.4525032043457, 'MSE': 0.0005685250507667661, 'measurement_sha256': 'bb2787d626f6ebae2479b5b28d4ef44e4d271f89b918a460dced157695607d75', 'confusion_sha256': '0944af0b95af443943287fde55daa5c8316f46354e872ace3bce9799e990b216'}, '2021-11-04_010': {'PSNR': 31.65911293029785, 'MSE': 0.000682477664668113, 'measurement_sha256': '574348bfc78c5a4ef01e41d908e0f1246cd2ef2411a39025a26673beeed7cef8', 'confusion_sha256': '0302d55190320ade8480a31d06fd0dc91653089317d6411faef73c82e5018397'}, '2021-11-04_017': {'PSNR': 32.068843841552734, 'MSE': 0.0006210344145074487, 'measurement_sha256': 'f2c1fc3a1867a401a8830c7df106ff15363a644a4a6d2bb8f2c015ebfa5d95e5', 'confusion_sha256': '0e409fc4d7661a42fb35c3bc6ebf1542b24a31903100c15853eee04f54191fba'}, '2021-11-04_024': {'PSNR': 32.81753158569336, 'MSE': 0.0005226928624324501, 'measurement_sha256': '8fe1aa0e2ee3165140fd3870306a2f62fdf34a2db253eb83b862be708024cefa', 'confusion_sha256': '15c73c79cb2661a51a4139cd9f09d98c9856d51ba58b7072b4f01e4c0733333f'}, '2021-11-04_042': {'PSNR': 33.13543701171875, 'MSE': 0.0004857984313275665, 'measurement_sha256': 'c18213aa55da17b39d687a96b7dcaa0afca31bd03537eef0053bf2622dc08d17', 'confusion_sha256': '4c9d19f4b04898dc94dbe7127eabf7249b60a795877f224a686d575af823d837'}, '2021-11-04_047': {'PSNR': 33.17755889892578, 'MSE': 0.0004811093967873603, 'measurement_sha256': 'fa8542625141d7d0425d56302cae43bb4fe82c34438c2534766d48234fba093a', 'confusion_sha256': '48301679879324b6abf5915acff8ff67182e6a0c086f4516c8d5943ef15e1cbb'}, '2021-11-04_049': {'PSNR': 33.28932189941406, 'MSE': 0.00046888639917597175, 'measurement_sha256': '3d1dc580085603aba03c6dea0c00f3f4f22585fe8e537b52822550ad4b0401bd', 'confusion_sha256': 'e0ea675ad85ea9537e4ebe6aae90f2c1d1b2777d833e190f1d73c17d65a906e8'}, '2021-11-04_055': {'PSNR': 32.98368835449219, 'MSE': 0.0005030730972066522, 'measurement_sha256': '8daf7c5eab29f12a14de4542185e4ce7c3701b1c7009efeeae8d054463ef9be6', 'confusion_sha256': '82bbda15946d4b19f58e16b8ebf1f07b9b957fcdd7b6ca066e8bb3aa83d7de5e'}, '2021-11-04_061': {'PSNR': 33.032325744628906, 'MSE': 0.0004974704352207482, 'measurement_sha256': '76571d839fd815213a720028a0dea1e7c67a9771ecf41fa040116f41b88b197e', 'confusion_sha256': 'd4ca5992761ffa0c8fa8829bbb8f9067c2be3d68f043a035f8423a60513ca52b'}, '2021-11-04_093': {'PSNR': 32.861488342285156, 'MSE': 0.0005174294929020107, 'measurement_sha256': '3b87377460978cbf83282f69c8bc59e923bbee0091c1539d54d463e0e4faa286', 'confusion_sha256': '11f4fbbfc72f44faca6ee21b8dacebeb80c935e29d44df90c04059446a5d2e74'}, '2021-11-04_098': {'PSNR': 33.13240051269531, 'MSE': 0.0004861380730289966, 'measurement_sha256': 'f1b03e9f68c5819c19e2947f086b58d436a122d4903542062dca70ab4287db04', 'confusion_sha256': '805703aa63d4d80c4dd96474ca88147d51322ca9649eddb87b455d6d6426c80f'}, '2021-11-05_010': {'PSNR': 31.729063034057617, 'MSE': 0.0006715732743032277, 'measurement_sha256': '82bfdf416b690183b07eac8ff7f95afc6080b1b0af3286cf749b20909ce1bda0', 'confusion_sha256': '121d1bddef98092237541002d6c6492daec3346f5a2453ad34391c0d2d1c6b2b'}, '2021-11-05_024': {'PSNR': 33.03628158569336, 'MSE': 0.0004970176960341632, 'measurement_sha256': '1590c87d257e7af56499f63bf35fd198e24fc655cceba3559efb1490d37048b7', 'confusion_sha256': '8422f76dde4824e860a5a4c6f4d5bcff27974073b02f7cc60fcd9cac6f812632'}, '2021-11-05_035': {'PSNR': 32.79540252685547, 'MSE': 0.0005253631388768554, 'measurement_sha256': 'd24a53bfd9da196f8f3121cb81f98e1b9ba8d82afffd415ca99f23f4ef437081', 'confusion_sha256': 'aad59211b196358031b8b216eadf37bf60fedbf526e453d637e73b29b6410926'}, '2021-11-05_041': {'PSNR': 32.420860290527344, 'MSE': 0.0005726827075704932, 'measurement_sha256': '64108b76e502b1b50cd5d408d7bf2e22650bfd382f33dd4db298eae54928f8ec', 'confusion_sha256': '64ca71526a2d1b19d957a4f0a624c631365a0f5744795b76f246b7e37abe07f0'}, '2021-11-05_046': {'PSNR': 31.126623153686523, 'MSE': 0.0007715028477832675, 'measurement_sha256': '529822dac51afb5c5b5dd9679c9d66330839c81e965f0eb5555ff5a6186c2a5e', 'confusion_sha256': 'a05ce07c33476b88f7a68a18ab8e717e8968334e1368e237fe18e59e1174db7f'}, '2021-11-10_014': {'PSNR': 31.955856323242188, 'MSE': 0.0006374032818712294, 'measurement_sha256': '1b8d46279497f949832fc555b8f83b63a7dc362e951cefd5f8cccf9384ae77d3', 'confusion_sha256': '2ce905fd9c48c0c911c94a5d6ae3d11f35cf286ebf81b2f281c3b2807291e72f'}, '2021-11-10_024': {'PSNR': 31.54131317138672, 'MSE': 0.000701243057847023, 'measurement_sha256': '3cd6daa626d7d626f725cd261e7c8b270e86a554ee30588dc1eb9fe61f1c4f07', 'confusion_sha256': 'd8a76058ccd324cf2d46b3d47a59fa5d89efeab4e8125b58d0401571496e410d'}, '2021-11-10_029': {'PSNR': 31.910573959350586, 'MSE': 0.0006440837751142681, 'measurement_sha256': 'a76e550b9212038fc80b336730883483e737681692d749a06c44b1a92e0eda67', 'confusion_sha256': '64aaa43d27efa9289d5d33c4c0e4190e469f0d7d97933c4d9ed6fa365c79b54b'}, '2021-11-10_050': {'PSNR': 31.59990692138672, 'MSE': 0.0006918456638231874, 'measurement_sha256': '8b26ff6696703808ea783fdbda1524525d6be1e244b0eb10c151c9dc23e0eaa4', 'confusion_sha256': '09695c61f969e5272ef57e8e86e34c17c103cea4c42a957bcf23ae67f4f167a4'}}}, 'plus1_alpha0.25_noise40': {'control': {'2021-11-03_046': {'PSNR': -2.9003567695617676, 'MSE': 1.9500048160552979, 'measurement_sha256': '48586d346d48d2958b1f5075af519ceae9bc1dcb49045ee3acfb1b5ab7bd9f84', 'confusion_sha256': '572ca12a8f1ebdd42412ed6feec276e141471e746ea8f2bba89afdc55905adf5'}, '2021-11-03_047': {'PSNR': -20.89003562927246, 'MSE': 122.74497985839844, 'measurement_sha256': '15e3ee815c6ed981b36d53963b731cbcc7e8bd776bf3827ff8ce86a11d997a72', 'confusion_sha256': 'e91dbec794ef3acfd005d8d3225080faaeacc494569b529e4d8eec3bf9af4f7f'}, '2021-11-03_057': {'PSNR': -10.045352935791016, 'MSE': 10.10497760772705, 'measurement_sha256': '28657b000064d5241f099b3589caf0e2795d493530f5ef2eddd3f2bd1ae32c44', 'confusion_sha256': 'f6b04d309dad0f6aac858966a6e3b38edaec61f9f462ac56e3c87096c49df519'}, '2021-11-03_085': {'PSNR': 6.336408615112305, 'MSE': 0.23246581852436066, 'measurement_sha256': '6b2c52a8a211ea5fdedad38461a29319f61cec173392df02bf9a02c03a083fd5', 'confusion_sha256': '6e130b794ebde88038c4aa39046cf7076ac4b77f485bbf27644720309e848703'}, '2021-11-03_090': {'PSNR': 5.479984283447266, 'MSE': 0.2831402122974396, 'measurement_sha256': '238c17fdc293ebea01c668806607e19db006a857a1d016212c77ab8c1f48bf4e', 'confusion_sha256': '5d66d2046fc782727a77cb95ab504c36fb1fa7b9c26d20e65bb4360c5c3418da'}, '2021-11-03_110': {'PSNR': 2.225416898727417, 'MSE': 0.5990434288978577, 'measurement_sha256': '73b70a206c808e8b19a5bc636c67e6f1fb38515db13df546dd485f0b7ef3fc66', 'confusion_sha256': 'f378140b7682795eca3299d94510cff57dca7660539efc3ad419cc256e2063fb'}, '2021-11-04_010': {'PSNR': 19.393129348754883, 'MSE': 0.011499715968966484, 'measurement_sha256': 'ab8e7dd80a8cc53087826fc9ad41ce35bb542b19be76eb6432b9f8d634f1f480', 'confusion_sha256': 'd03623523b66536d5592792220a2bb529f64cd02d8082885958ff1942d61b090'}, '2021-11-04_017': {'PSNR': 14.970934867858887, 'MSE': 0.03183511644601822, 'measurement_sha256': 'c1d21b153fc1bdcdabb666e4f05ce22010f37bc631f1c3c19daf67e8cb673b25', 'confusion_sha256': 'd6791abfbbf71630044fe5d6d07af83187d7773e12b1bd60e80a49e34ccafb40'}, '2021-11-04_024': {'PSNR': 17.27276039123535, 'MSE': 0.018738029524683952, 'measurement_sha256': '843735c8eb1e932eb74045825e36b9b092ec96682e8ca36f7f4d6eaa287890f9', 'confusion_sha256': '82aae9fa19a28ee43d0dc5ebf948975a0b1a212a1b4b20447f72b6c1ec4b0a51'}, '2021-11-04_042': {'PSNR': 15.721500396728516, 'MSE': 0.02678242325782776, 'measurement_sha256': '4a87bb9da17f844814eb438f2cd4f0c43965c9b0fd001f379badb0c22191e3bf', 'confusion_sha256': 'c6ba1e9db3ea10a6e8ef60654903704fe955314c40ab0d4bbbecfce220d9173e'}, '2021-11-04_047': {'PSNR': 14.871623992919922, 'MSE': 0.03257148712873459, 'measurement_sha256': '6603c9a10a6286ed165abb61e97271ab58937d0cdaf2d50dcaeb9dd446d1cd0b', 'confusion_sha256': '60330c7d07813cb56225e5d09fc625d9a2bb80b4332571f14db3556f0bae55ef'}, '2021-11-04_049': {'PSNR': 20.109027862548828, 'MSE': 0.009752077981829643, 'measurement_sha256': 'c40c9ef9104d29b791361f426cbbc6f49ba68a1ecab7901e25507e8f84d4631f', 'confusion_sha256': 'afd60a652de213174c4ff16f3db4adf08312cd0f26623b503dd4d771f818ff40'}, '2021-11-04_055': {'PSNR': -21.52325439453125, 'MSE': 142.0121612548828, 'measurement_sha256': 'f72ff20e5b4ac7e9b7ce6d9ec7b0a6ce47212bbd34ec0de542331a139fdcc96f', 'confusion_sha256': 'c2fd90e7b93e13be3743dc8e9261a3fe40c0eda1dbb20317dd1803ccc3a8ae8a'}, '2021-11-04_061': {'PSNR': -11.633523941040039, 'MSE': 14.566408157348633, 'measurement_sha256': '8751f0f9058d691b99542147c450cd727e2eda668c03008825286b933dbb7876', 'confusion_sha256': 'e79558786131ab74984e9f7bd66c574a223d62923aa1be041b4cd8b425e13538'}, '2021-11-04_093': {'PSNR': 9.732845306396484, 'MSE': 0.10634459555149078, 'measurement_sha256': '4cb2eb40f0eeae4437f2125ff66955ad6c1a0065ae9a4fc931c25bf72b8188ad', 'confusion_sha256': '300f656eaebe7735cddcc8ab2010af01195a8948b72b7f3b2f9afde368a8afa6'}, '2021-11-04_098': {'PSNR': 4.494118690490723, 'MSE': 0.35529419779777527, 'measurement_sha256': '131fab65f750e80993930a645ac086aed097e8d9fe00ca41db8e45ecb62abb1d', 'confusion_sha256': 'bae0bba41f758817a6ec493e99deec6df39557662494e1aad7aa76c96a946db7'}, '2021-11-05_010': {'PSNR': 15.928244590759277, 'MSE': 0.025537332519888878, 'measurement_sha256': 'c47732e50132455e12fbee0a93fab28bc75884a7efac61781b9ff54bddb7b66c', 'confusion_sha256': 'dedb5ede2ee7e28ab9d0eed0e277441913652035115592dd6d10f030c56cd6ef'}, '2021-11-05_024': {'PSNR': -12.382112503051758, 'MSE': 17.306583404541016, 'measurement_sha256': '47ae6f2788264a0dc36bb7841c079b80f46d5a957a4f6c7a997f7517e78f0f93', 'confusion_sha256': 'a0c9997eb7d6b2956a5fae11cdc7b2d29160dc84a3211e3edecbdc34c822920f'}, '2021-11-05_035': {'PSNR': 18.051925659179688, 'MSE': 0.015660563483834267, 'measurement_sha256': 'efc7cec23dd10f2bf229536f1d16f21902f93da1cf953116d4ccac8ccc563fa2', 'confusion_sha256': 'd7fe666fc5b3a77c833c71b58d6154bb6bf3cf2a125c0626d8889eb7d6feb343'}, '2021-11-05_041': {'PSNR': 18.149351119995117, 'MSE': 0.015313155017793179, 'measurement_sha256': '132059341d41ef4cbdd5952eb47ac4f579404306954986fb011c9636ab4cd10d', 'confusion_sha256': '31cecb6d48c10ace2dfc05d90cf4805b3db3f38805de22dc023c2c716329a092'}, '2021-11-05_046': {'PSNR': 19.525606155395508, 'MSE': 0.01115422137081623, 'measurement_sha256': '904dbca19af215cc872e173ec2eb1360047bb5a1d291b4d20ad0eb3e232ad52e', 'confusion_sha256': '639b65c4ab6648fc48d94a084b830f8319ec203a144c1ced25c5c5d3e35acee5'}, '2021-11-10_014': {'PSNR': 20.935026168823242, 'MSE': 0.008063011802732944, 'measurement_sha256': '5475b2e842fc6bbe12a15d4c9c472247802abf3123f07a0c22331d44af0ee64a', 'confusion_sha256': '3f7340d7284f51263388f47f6592fba801e2e19cf6142b834581f40da7a75c98'}, '2021-11-10_024': {'PSNR': 21.15890884399414, 'MSE': 0.0076578897424042225, 'measurement_sha256': 'a9aef1486890950d96c01fcc463370eb601baa80102df7df8a1c452737d4dc90', 'confusion_sha256': '5f0da7d9e90b108dde9094bd33bcef5a9c92984c75b5f94b37435f8f2801ea37'}, '2021-11-10_029': {'PSNR': 12.487183570861816, 'MSE': 0.05640032887458801, 'measurement_sha256': '526d34fa52be894e37699acda49f78aae2bb7efc264d4dbe443542d16e15d2c8', 'confusion_sha256': '166ef9c67e3ec0100bfc3f0115295d598d1eb01c708c632488112dc0fe15e2d3'}, '2021-11-10_050': {'PSNR': 27.075725555419922, 'MSE': 0.0019607730209827423, 'measurement_sha256': 'e63a66c469197e9c63c8d633df55ff8e3adfa61cf30083c0411257661d82ee7c', 'confusion_sha256': 'd1e48505ae1bfef046d5196396763ecb50d95dce3bce58b015ef6e52806e98b1'}}, 'guarded': {'2021-11-03_046': {'PSNR': 35.19025421142578, 'MSE': 0.00030267349211499095, 'measurement_sha256': '48586d346d48d2958b1f5075af519ceae9bc1dcb49045ee3acfb1b5ab7bd9f84', 'confusion_sha256': 'a1aecc683ae138299e4c0708e3aa3da169ea543e90a7c20ce014620b7bf9c98e'}, '2021-11-03_047': {'PSNR': 34.31640625, 'MSE': 0.00037013430846855044, 'measurement_sha256': '15e3ee815c6ed981b36d53963b731cbcc7e8bd776bf3827ff8ce86a11d997a72', 'confusion_sha256': '3e1b941ac2bfe6b322911445227e1a358715108577d75f0ca917acbb441b8d34'}, '2021-11-03_057': {'PSNR': 33.94091033935547, 'MSE': 0.00040356075624004006, 'measurement_sha256': '28657b000064d5241f099b3589caf0e2795d493530f5ef2eddd3f2bd1ae32c44', 'confusion_sha256': 'b3f47ffe7e7dbbf308f95867bf943350ef35e178dcb90401db44a06517120c14'}, '2021-11-03_085': {'PSNR': 35.75941467285156, 'MSE': 0.0002654964046087116, 'measurement_sha256': '6b2c52a8a211ea5fdedad38461a29319f61cec173392df02bf9a02c03a083fd5', 'confusion_sha256': '9b125bc2cc1ef3517ee87a6912058c932270c7093bd93192c0e453c84fc33c2f'}, '2021-11-03_090': {'PSNR': 35.51933288574219, 'MSE': 0.0002805863041430712, 'measurement_sha256': '238c17fdc293ebea01c668806607e19db006a857a1d016212c77ab8c1f48bf4e', 'confusion_sha256': '0318046719eb7c9b04177925a5320ef7ee95b6cc208e394f889780cd1f446487'}, '2021-11-03_110': {'PSNR': 35.19140625, 'MSE': 0.0003025932237505913, 'measurement_sha256': '73b70a206c808e8b19a5bc636c67e6f1fb38515db13df546dd485f0b7ef3fc66', 'confusion_sha256': 'f51d5f1fc69ea812b2ae515876c3890aa7a5f1df6001c151398c7d3be3375121'}, '2021-11-04_010': {'PSNR': 33.60725021362305, 'MSE': 0.00043578751501627266, 'measurement_sha256': 'ab8e7dd80a8cc53087826fc9ad41ce35bb542b19be76eb6432b9f8d634f1f480', 'confusion_sha256': 'ac23ab7d66505f676a05dd28137f844468770bcd3908aa01a4bfe793cbecedf8'}, '2021-11-04_017': {'PSNR': 34.25531768798828, 'MSE': 0.0003753773926291615, 'measurement_sha256': 'c1d21b153fc1bdcdabb666e4f05ce22010f37bc631f1c3c19daf67e8cb673b25', 'confusion_sha256': '0fc14ed483bce36b2c27b4c23affc81c7137fed2c5b25de206d5ecd8d1b60d2c'}, '2021-11-04_024': {'PSNR': 35.055564880371094, 'MSE': 0.00031220747041516006, 'measurement_sha256': '843735c8eb1e932eb74045825e36b9b092ec96682e8ca36f7f4d6eaa287890f9', 'confusion_sha256': '76bea4f10734c4918a3e4aa5e29a02347aff81f598f9661514b750cec12eb6ab'}, '2021-11-04_042': {'PSNR': 35.75208282470703, 'MSE': 0.00026594483642838895, 'measurement_sha256': '4a87bb9da17f844814eb438f2cd4f0c43965c9b0fd001f379badb0c22191e3bf', 'confusion_sha256': '94bc6a1e552cc16d271882db97e532fe0bfa9afe8cc88a3b53efec0e9e70678a'}, '2021-11-04_047': {'PSNR': 35.69123840332031, 'MSE': 0.0002696967567317188, 'measurement_sha256': '6603c9a10a6286ed165abb61e97271ab58937d0cdaf2d50dcaeb9dd446d1cd0b', 'confusion_sha256': '98f35b0efee462d6aca1af4c73ffe510ebaa41b654265af213a6a0c7047bfc60'}, '2021-11-04_049': {'PSNR': 35.60112380981445, 'MSE': 0.0002753513981588185, 'measurement_sha256': 'c40c9ef9104d29b791361f426cbbc6f49ba68a1ecab7901e25507e8f84d4631f', 'confusion_sha256': '29d94d592b314d2dcf0adc4c92d1a334dd2ed09a83cd26406b763fb2eebddce0'}, '2021-11-04_055': {'PSNR': 35.23705291748047, 'MSE': 0.0002994297246914357, 'measurement_sha256': 'f72ff20e5b4ac7e9b7ce6d9ec7b0a6ce47212bbd34ec0de542331a139fdcc96f', 'confusion_sha256': '02871f3cbd2440a976a445e449bd7a8a479903f9f31621f31e14d02ae614e85c'}, '2021-11-04_061': {'PSNR': 35.650978088378906, 'MSE': 0.0002722087665461004, 'measurement_sha256': '8751f0f9058d691b99542147c450cd727e2eda668c03008825286b933dbb7876', 'confusion_sha256': '08303baad468d9ba9e0e015370611878b6fc213da96bdabf648a614df84a5857'}, '2021-11-04_093': {'PSNR': 34.90760803222656, 'MSE': 0.00032302713952958584, 'measurement_sha256': '4cb2eb40f0eeae4437f2125ff66955ad6c1a0065ae9a4fc931c25bf72b8188ad', 'confusion_sha256': '8c0f534dc3b3b32619f9365227c79f0b54638fc6f8b041f0fd2721847d85fada'}, '2021-11-04_098': {'PSNR': 35.33294677734375, 'MSE': 0.0002928906469605863, 'measurement_sha256': '131fab65f750e80993930a645ac086aed097e8d9fe00ca41db8e45ecb62abb1d', 'confusion_sha256': 'e34c9cd00b210ddc8654e72e2b491509f887b5dcd86fe8539d6388d6d6d1053c'}, '2021-11-05_010': {'PSNR': 33.50735855102539, 'MSE': 0.0004459273477550596, 'measurement_sha256': 'c47732e50132455e12fbee0a93fab28bc75884a7efac61781b9ff54bddb7b66c', 'confusion_sha256': '886d034bf088b8638ae448cbe7d02f9ebb33c147ccc0f595c765dfee2cfde46a'}, '2021-11-05_024': {'PSNR': 35.306617736816406, 'MSE': 0.00029467165586538613, 'measurement_sha256': '47ae6f2788264a0dc36bb7841c079b80f46d5a957a4f6c7a997f7517e78f0f93', 'confusion_sha256': '6db6f354a45cf7ec2af3bcf7833b1240f2619544552ffea401caf4009694f491'}, '2021-11-05_035': {'PSNR': 34.58283996582031, 'MSE': 0.0003481096646282822, 'measurement_sha256': 'efc7cec23dd10f2bf229536f1d16f21902f93da1cf953116d4ccac8ccc563fa2', 'confusion_sha256': '296c3a0058ffc026c8f1fe28a854eeca408e3bc389f66f9a913a718a7a44e761'}, '2021-11-05_041': {'PSNR': 34.35743713378906, 'MSE': 0.0003666537522803992, 'measurement_sha256': '132059341d41ef4cbdd5952eb47ac4f579404306954986fb011c9636ab4cd10d', 'confusion_sha256': 'e9cea3e13493e5308e19056e911d300fe4ebb247f156a05d564a5274756b44cd'}, '2021-11-05_046': {'PSNR': 32.86766815185547, 'MSE': 0.0005166935734450817, 'measurement_sha256': '904dbca19af215cc872e173ec2eb1360047bb5a1d291b4d20ad0eb3e232ad52e', 'confusion_sha256': 'fa12f947941a2dd154d39ec5a4542b6d702c462ffb09a51e06879a30ed2a6cf9'}, '2021-11-10_014': {'PSNR': 34.108577728271484, 'MSE': 0.0003882773744408041, 'measurement_sha256': '5475b2e842fc6bbe12a15d4c9c472247802abf3123f07a0c22331d44af0ee64a', 'confusion_sha256': '8c3da389a7aeb4b6f7616d1acfae79747129c7c81643aba05baf6a4d05545f8d'}, '2021-11-10_024': {'PSNR': 33.24296951293945, 'MSE': 0.0004739177820738405, 'measurement_sha256': 'a9aef1486890950d96c01fcc463370eb601baa80102df7df8a1c452737d4dc90', 'confusion_sha256': 'da92c7d70b26c3f157248d5ac4a606f74ca7f4fb896689a8c813cef20648fb9a'}, '2021-11-10_029': {'PSNR': 34.34062576293945, 'MSE': 0.00036807573633268476, 'measurement_sha256': '526d34fa52be894e37699acda49f78aae2bb7efc264d4dbe443542d16e15d2c8', 'confusion_sha256': '0884e0d06b88974824693ef5e9f68c8ba8903e9e6bb081fc135c1dbcfd2ee004'}, '2021-11-10_050': {'PSNR': 33.950111389160156, 'MSE': 0.00040270667523145676, 'measurement_sha256': 'e63a66c469197e9c63c8d633df55ff8e3adfa61cf30083c0411257661d82ee7c', 'confusion_sha256': 'ebba57d70770634f450c36a6305519bcd3e1d20e145a2d3687b74e66b8a00cfa'}}}, 'minus1_alpha0.25_noise40': {'control': {'2021-11-03_046': {'PSNR': 1.8929266929626465, 'MSE': 0.6467066407203674, 'measurement_sha256': 'c77279b0f378722445456adbc2dff0518a3029071afc506236ce58f3017db98c', 'confusion_sha256': '5717fc872373eb198fb2c31db1421fbb73c649576a1f421e557e4bcb000701a6'}, '2021-11-03_047': {'PSNR': -18.10618782043457, 'MSE': 64.65750885009766, 'measurement_sha256': '65b56d35a14a9495b8874fa539fbdcdcdb9678b65d1c117a7accc2f1eddffcc2', 'confusion_sha256': '10c7a70329d254cbe5ca36efdad73e3513e4aaba200c42c453a3fe00914bf888'}, '2021-11-03_057': {'PSNR': -9.638367652893066, 'MSE': 9.201037406921387, 'measurement_sha256': '317aaa03c84199b89f5399fc562cd0f5cb33e43cfb7831d1bf1d85b4915b618f', 'confusion_sha256': '7e431307c0ff968d53c3637959a8d4afceeafbd2a3af74fc12e8c49793e77e7c'}, '2021-11-03_085': {'PSNR': 7.915778160095215, 'MSE': 0.16159285604953766, 'measurement_sha256': '918afe0a8da8e3b5198073f0edf8e698580fc6ee99dbdf514d264452f379e3e3', 'confusion_sha256': '5931124e77786aa00a29b17026684e0665fdad3a01c2ac7bcbbf94d51d078409'}, '2021-11-03_090': {'PSNR': 6.679916858673096, 'MSE': 0.21478715538978577, 'measurement_sha256': '52e0d3a346980ff8880bb713829ceaa8615b741bf31f3907cbe7f7681db70038', 'confusion_sha256': 'f39913782724db18cbe146933ed2a572939debc882c712f73dd912364c234f14'}, '2021-11-03_110': {'PSNR': 4.306404113769531, 'MSE': 0.37098774313926697, 'measurement_sha256': '05da66109304ac2fed0ca0fbb06aa4a713d5436658ffe9366a5755c7bf42ea52', 'confusion_sha256': '0cbfd61523aada0c9038d40de829342d3a05762f7075e00e8b1239087f48a4cf'}, '2021-11-04_010': {'PSNR': 21.06349754333496, 'MSE': 0.00782798696309328, 'measurement_sha256': '79b2798d0e08e8ee710f0a677e01dd90732e16c8e8bf7beaf66033aa0b464ae2', 'confusion_sha256': '67ae32d3d65c2a8866109dc4d4e9b776ee5f28807649a2a9f67de069a66c9e7d'}, '2021-11-04_017': {'PSNR': 16.104612350463867, 'MSE': 0.024521032348275185, 'measurement_sha256': '9656979e0fc4c7f75f10b3ee1c329ef4dc2a30597a67e8ed0588ec569da77523', 'confusion_sha256': 'a1371a3f4b08c1188211c0bfac31407fe24996f0ecf24a92e03775c67f2d15a4'}, '2021-11-04_024': {'PSNR': -7.123457431793213, 'MSE': 5.156390190124512, 'measurement_sha256': '60d594bc95211031ce58eea86e9f409033b9d9c2a98d6c6b8d04c694ae829c81', 'confusion_sha256': '34319be89f21f60d38acd607110534000d6de8adb2920bd7d93de4115bcaa6fc'}, '2021-11-04_042': {'PSNR': 16.19339370727539, 'MSE': 0.02402484603226185, 'measurement_sha256': '3cb73cdc28b7f97b3e1c7097db8ede55b57b1c258a7e3fd31398fe9baced7f27', 'confusion_sha256': '0ca0af3c255e36cb2a6b1ec468efecd5b1963527f72ee5bf185cb8ffb2b5d250'}, '2021-11-04_047': {'PSNR': 15.317720413208008, 'MSE': 0.02939191460609436, 'measurement_sha256': 'deba991cb8492fce8be060a828bae1e611532bc155fd36bd811932b1a41999dd', 'confusion_sha256': '7ddf03cf57c686d0a0ffa4d20a566c21cfd0717149abc5fe968b625c7efc3cee'}, '2021-11-04_049': {'PSNR': 19.85340118408203, 'MSE': 0.010343315079808235, 'measurement_sha256': '25b53fe50610d8cc2d83fdcdf08c759f5ec5cf9d5908ccdc0d8ee2be90cfdbf5', 'confusion_sha256': 'cd40f7ff0fced2e6ddd9092a1888f322273a158323dc5f737b9358231bb5abac'}, '2021-11-04_055': {'PSNR': -20.005207061767578, 'MSE': 100.12000274658203, 'measurement_sha256': '26840608eab51b3bd4ba18047a4ed2a6759d61d208665dc5916823dffe6aca3f', 'confusion_sha256': '9c18b8d34eca7b3bcc3fa84d536c4ca86590b6bc67fb02c47f4c4677e8da7e04'}, '2021-11-04_061': {'PSNR': -8.373223304748535, 'MSE': 6.875785827636719, 'measurement_sha256': '8b99ea86a3129902d1eeb50601df3e74dc49b6dcdd5d89eb21acf89ff798f253', 'confusion_sha256': 'b465af3d7f25ea47aabc9bf116451fe3163076221a9509cadecf49457e9e9734'}, '2021-11-04_093': {'PSNR': 10.816917419433594, 'MSE': 0.08285299688577652, 'measurement_sha256': 'c4710d9a5edd078271434e4fb4fba0fe34aaa16ab6c993fa2b3703cb97afb790', 'confusion_sha256': '2350bedfdcc4a72b1403801c9a81a1af48562f41f1144431e08ca0d2ceb49750'}, '2021-11-04_098': {'PSNR': 5.92501163482666, 'MSE': 0.25556349754333496, 'measurement_sha256': 'b629a0bb39fbed304f856674111484d7f27ab8314e42d7e98aa9ed79c874ea32', 'confusion_sha256': '1e7fbb63ed8244b60bd33223ebd275dd9a69e1915e7a6f872ad8d0289b95b3a8'}, '2021-11-05_010': {'PSNR': 8.508240699768066, 'MSE': 0.14098596572875977, 'measurement_sha256': '7d2bf476da2a155f112dc32674447c3843aed169677855c1e66c8e47128a08c5', 'confusion_sha256': '01490db53bb92e6a581f2c8a1470d7e78bdf950acf9f183fea9b9a32e7b50d39'}, '2021-11-05_024': {'PSNR': -6.3284807205200195, 'MSE': 4.2938618659973145, 'measurement_sha256': 'f933099dbd44110af1530174df997f19362f40751ff9641048887004652a6218', 'confusion_sha256': '33a39d531c72dc044113f344ebe29234b8401e3176c9a4d4a061741f2670f8c2'}, '2021-11-05_035': {'PSNR': 18.586042404174805, 'MSE': 0.013848276808857918, 'measurement_sha256': 'e2e23992bd5a3544feb9d3d9970e9f875f54569dca288f2a4c8d25d148e34681', 'confusion_sha256': 'bc0b4f7d77ac82a66f6495d84bbad0e4e55dbe720b9f27d005df06265aac3f32'}, '2021-11-05_041': {'PSNR': 20.009811401367188, 'MSE': 0.0099774319678545, 'measurement_sha256': '6718b79d17ee7bd25a27593256e5be9a241b30cacf909d2dc6f0d01432319f5c', 'confusion_sha256': 'cf2111f1e936d2e2156ba140233bf36e0b26588fa9994fd53ce7b524e3858a99'}, '2021-11-05_046': {'PSNR': 14.069116592407227, 'MSE': 0.0391821563243866, 'measurement_sha256': 'b1929e57229b46ae3cbed9e1d0e12867a17aa78238c0309249015bc768a8af47', 'confusion_sha256': '30e59605bdd6a555fef85198c24c43fc979da991095564912ad1ae8da2c7e540'}, '2021-11-10_014': {'PSNR': 12.575736045837402, 'MSE': 0.05526196211576462, 'measurement_sha256': 'e258c864280191fc937f94bdcbe7235938d839416d237b4622c6f48cafed9808', 'confusion_sha256': 'cd422f144e22c82f9cb79808a6d9ee447accc439df10a254f7285adcff67b6e5'}, '2021-11-10_024': {'PSNR': 19.88340950012207, 'MSE': 0.010272093117237091, 'measurement_sha256': '2c893a939eb4ebf5b31bda796518a206ae96c235f2c3cea437d5131c0fa1b854', 'confusion_sha256': 'f045bf152276f25d571202e9b08ffbc8e846190272ec218d265efb8b7ed5f53a'}, '2021-11-10_029': {'PSNR': -5.292293548583984, 'MSE': 3.382434129714966, 'measurement_sha256': '67e3dbcd927ba71dd3159846e6923b49044689c452a5365c1ae61c17cfcf1a65', 'confusion_sha256': '00b3702a067ce8f66275bf8751dcc390d83b47fe4a070627a459479e4d37caec'}, '2021-11-10_050': {'PSNR': 26.634187698364258, 'MSE': 0.0021706069819629192, 'measurement_sha256': '1004aaee5a0105b9bff4801ea83434b7b1fce1e65e2c135b0b063851e81ddd6a', 'confusion_sha256': '7040bedb7182490651db93aab8db67259fbd4967ed597b6cb1bfd8cc2b5be2b3'}}, 'guarded': {'2021-11-03_046': {'PSNR': 35.101463317871094, 'MSE': 0.0003089253150392324, 'measurement_sha256': 'c77279b0f378722445456adbc2dff0518a3029071afc506236ce58f3017db98c', 'confusion_sha256': 'be121acf7b38ebbd5922a3de01c08ab5e0307d17942d4e65e8d74cecfbb51ab1'}, '2021-11-03_047': {'PSNR': 34.4963264465332, 'MSE': 0.0003551136760506779, 'measurement_sha256': '65b56d35a14a9495b8874fa539fbdcdcdb9678b65d1c117a7accc2f1eddffcc2', 'confusion_sha256': '372205d484e741a72d213e3b43be938314b73ef5eadfb9be8da8d4d6d6b76254'}, '2021-11-03_057': {'PSNR': 33.85374069213867, 'MSE': 0.00041174268699251115, 'measurement_sha256': '317aaa03c84199b89f5399fc562cd0f5cb33e43cfb7831d1bf1d85b4915b618f', 'confusion_sha256': '674c2f7d756d9c4abeadc3651ff594e07a4ae24720107158047b324eec24a01d'}, '2021-11-03_085': {'PSNR': 35.68679428100586, 'MSE': 0.0002699729229789227, 'measurement_sha256': '918afe0a8da8e3b5198073f0edf8e698580fc6ee99dbdf514d264452f379e3e3', 'confusion_sha256': 'b4ce1bef75860a3ab89cbabd480bcdff7d5b35ec3c669f1c70c6db2ec01e29b1'}, '2021-11-03_090': {'PSNR': 35.45872116088867, 'MSE': 0.00028452984406612813, 'measurement_sha256': '52e0d3a346980ff8880bb713829ceaa8615b741bf31f3907cbe7f7681db70038', 'confusion_sha256': '0a1f15d71b750b05e51b55b33d36de6fd0fa770ca39802d0405c6e4864fe1469'}, '2021-11-03_110': {'PSNR': 34.96849060058594, 'MSE': 0.00031853021937422454, 'measurement_sha256': '05da66109304ac2fed0ca0fbb06aa4a713d5436658ffe9366a5755c7bf42ea52', 'confusion_sha256': '2501bf5efcdf80e71fe949b0f8667c48e38f454c45e8dfc430b22d70dd44e406'}, '2021-11-04_010': {'PSNR': 33.664737701416016, 'MSE': 0.0004300569707993418, 'measurement_sha256': '79b2798d0e08e8ee710f0a677e01dd90732e16c8e8bf7beaf66033aa0b464ae2', 'confusion_sha256': '6ecdd010a5d67236292b765f758ebe8bd948a50031837254d4cce53e683839f4'}, '2021-11-04_017': {'PSNR': 34.56328582763672, 'MSE': 0.00034968022373504937, 'measurement_sha256': '9656979e0fc4c7f75f10b3ee1c329ef4dc2a30597a67e8ed0588ec569da77523', 'confusion_sha256': '5e32435258f1e31eb23432dccfe3469d19ad45c278d40a3a9d5390dbdea6050f'}, '2021-11-04_024': {'PSNR': 34.97795867919922, 'MSE': 0.00031783670419827104, 'measurement_sha256': '60d594bc95211031ce58eea86e9f409033b9d9c2a98d6c6b8d04c694ae829c81', 'confusion_sha256': '9a654a498ac5646bf22672211d420407dc08c84ad21d3938dc25f200e4da354c'}, '2021-11-04_042': {'PSNR': 35.74744415283203, 'MSE': 0.0002662289480213076, 'measurement_sha256': '3cb73cdc28b7f97b3e1c7097db8ede55b57b1c258a7e3fd31398fe9baced7f27', 'confusion_sha256': '2dd73eab6613069565b8e573814ceb0fbf9fbf6a8740e76c73b97e6b55c311a1'}, '2021-11-04_047': {'PSNR': 35.602134704589844, 'MSE': 0.00027528745704330504, 'measurement_sha256': 'deba991cb8492fce8be060a828bae1e611532bc155fd36bd811932b1a41999dd', 'confusion_sha256': '3e458b7775a92263e8a0d63aab744d4d927a71c7e51c53667b0281a61f1cf32b'}, '2021-11-04_049': {'PSNR': 35.47181701660156, 'MSE': 0.0002836728817783296, 'measurement_sha256': '25b53fe50610d8cc2d83fdcdf08c759f5ec5cf9d5908ccdc0d8ee2be90cfdbf5', 'confusion_sha256': '8a77ea605b4f3f817470c10512b56b33dd7c796ec543b5579faf113e8722765f'}, '2021-11-04_055': {'PSNR': 35.32849884033203, 'MSE': 0.0002931905328296125, 'measurement_sha256': '26840608eab51b3bd4ba18047a4ed2a6759d61d208665dc5916823dffe6aca3f', 'confusion_sha256': '1688ffc9013c44b8a846fc388ef3c5c50408593f19685ed79ac98ceb67683fbd'}, '2021-11-04_061': {'PSNR': 35.4742546081543, 'MSE': 0.0002835139457602054, 'measurement_sha256': '8b99ea86a3129902d1eeb50601df3e74dc49b6dcdd5d89eb21acf89ff798f253', 'confusion_sha256': '5876b5192bf72a799b1748271ba29ae84153e9e2e293dcb1a6a2749b6bd20714'}, '2021-11-04_093': {'PSNR': 34.87086486816406, 'MSE': 0.00032577174715697765, 'measurement_sha256': 'c4710d9a5edd078271434e4fb4fba0fe34aaa16ab6c993fa2b3703cb97afb790', 'confusion_sha256': '5988059a1754a4ba2af4b6f7a802b3d5af0affe913b157ede65023d4775e6463'}, '2021-11-04_098': {'PSNR': 35.321353912353516, 'MSE': 0.00029367348179221153, 'measurement_sha256': 'b629a0bb39fbed304f856674111484d7f27ab8314e42d7e98aa9ed79c874ea32', 'confusion_sha256': '03dc19e3db95498d2787aec56238c2cfcc27d3c04c56129742acc9c5bf0eba22'}, '2021-11-05_010': {'PSNR': 33.49394226074219, 'MSE': 0.0004473067820072174, 'measurement_sha256': '7d2bf476da2a155f112dc32674447c3843aed169677855c1e66c8e47128a08c5', 'confusion_sha256': '619672b55af43da92563e2cb1b31ebac95d1ec39dba760f4d485396901c73f33'}, '2021-11-05_024': {'PSNR': 35.217594146728516, 'MSE': 0.00030077414703555405, 'measurement_sha256': 'f933099dbd44110af1530174df997f19362f40751ff9641048887004652a6218', 'confusion_sha256': '9a984a2e8f3c76cb70c0e45e803e84c87efba24b21afef583f0b72c75e097a70'}, '2021-11-05_035': {'PSNR': 34.674503326416016, 'MSE': 0.0003408393822610378, 'measurement_sha256': 'e2e23992bd5a3544feb9d3d9970e9f875f54569dca288f2a4c8d25d148e34681', 'confusion_sha256': '8dc91a05a7cd967de4dfcd07b0b7973841c8617888c41972d20a4378864cc2d5'}, '2021-11-05_041': {'PSNR': 34.194984436035156, 'MSE': 0.00038062859675846994, 'measurement_sha256': '6718b79d17ee7bd25a27593256e5be9a241b30cacf909d2dc6f0d01432319f5c', 'confusion_sha256': '0a94c4abbaab90a6f1a4b73e09cf94ac75b418107b38c2cee109231409ab732e'}, '2021-11-05_046': {'PSNR': 32.84754943847656, 'MSE': 0.0005190927186049521, 'measurement_sha256': 'b1929e57229b46ae3cbed9e1d0e12867a17aa78238c0309249015bc768a8af47', 'confusion_sha256': 'b1c9c8dc0ffa97d3ad97fafcc9153482c3707b146e98d68e475caf61ac1bb3e9'}, '2021-11-10_014': {'PSNR': 34.303077697753906, 'MSE': 0.0003712718898896128, 'measurement_sha256': 'e258c864280191fc937f94bdcbe7235938d839416d237b4622c6f48cafed9808', 'confusion_sha256': 'd4143dd43001ad46bdbfedcd68a73e52054735878357d3e2c58bd3ba90b72d96'}, '2021-11-10_024': {'PSNR': 33.2402229309082, 'MSE': 0.00047421734780073166, 'measurement_sha256': '2c893a939eb4ebf5b31bda796518a206ae96c235f2c3cea437d5131c0fa1b854', 'confusion_sha256': '90d38a7c26a5582e9fc75695589fc426d039860e931bad8e8a0845c145b33598'}, '2021-11-10_029': {'PSNR': 34.38471603393555, 'MSE': 0.0003643578093033284, 'measurement_sha256': '67e3dbcd927ba71dd3159846e6923b49044689c452a5365c1ae61c17cfcf1a65', 'confusion_sha256': '7610ae8786eadec0a907cdbc2d29fdc2a4e0ff7426b5f06dac20da3707cc27ff'}, '2021-11-10_050': {'PSNR': 33.884342193603516, 'MSE': 0.0004088513378519565, 'measurement_sha256': '1004aaee5a0105b9bff4801ea83434b7b1fce1e65e2c135b0b063851e81ddd6a', 'confusion_sha256': '164d052448d41bfb68d52614eba448e077ee04fd1e5e1f6b1adc5b7cabd0d61a'}}}}, 'helper_hashes': {'pilot_support.py': '5745eb5923602563e1be57cca987f577950f751fc059d2aa620c414293521b93', 'operator_control.py': '773a2ece4f755ec318a2bc9e3307d3d8e1d5f5a598772243ae6c8762ed890e81', 'robustness_inputs.py': 'c692a22cf9af62b06adc81125bb744b939956ad69b659c3a0a5905d8bbe2142e', 'gain_guard.py': '48101cb5d2076a06fa80e8498eabf8e984968d4c325a12e21c057d43fac4b28d', 'numerical_trace.py': 'afb24aabaad5b10060f973254f05233edbf7f137f091a0d048c63b941d2d4e33'}}

from pathlib import Path
import zipfile,hashlib,json,sys,subprocess,datetime,shutil,os
import torch
INPUT=Path('/kaggle/input');WORK=Path('/kaggle/working')
DATA=INPUT/'datasets/arnavnigamd/btp-data/public252'
assert torch.cuda.is_available(),'Enable GPU T4.'
assert DATA.is_dir(),'Attach the prepared public252 dataset.'
def digest(path):
    h=hashlib.sha256()
    with Path(path).open('rb') as f:
        for b in iter(lambda:f.read(1024*1024),b''):h.update(b)
    return h.hexdigest()
RUN=WORK/('crossed_noise_pilot_'+datetime.datetime.now().strftime('%Y%m%d_%H%M%S_%f'))
RUN.mkdir(exist_ok=False)
for name,source in FILES.items():(RUN/name).write_text(source)
(RUN/'expected.json').write_text(json.dumps(EXPECTED,indent=2))
for name,h in EXPECTED['helper_hashes'].items():assert digest(RUN/name)==h
print('Output:',RUN,'GPU:',torch.cuda.get_device_name(0))

Output: /kaggle/working/crossed_noise_pilot_20261011_141656_720753 GPU: Tesla T4

In [10]:
def matches_code(folder):
    return all((folder/name).is_file() and digest(folder/name)==h for name,h in EXPECTED['code_hashes'].items())
CODE=None
for surface in (INPUT,WORK):
    for p in sorted(surface.rglob('run_public252.py')):
        if matches_code(p.parent):CODE=p.parent;break
    if CODE is not None:break
archives=sorted(INPUT.rglob('*.zip'))+sorted(WORK.glob('*.zip'))
if CODE is None:
    for archive in archives:
        if not zipfile.is_zipfile(archive):continue
        with zipfile.ZipFile(archive) as z:
            if not all('BTP/'+name in z.namelist() and hashlib.sha256(z.read('BTP/'+name)).hexdigest()==h for name,h in EXPECTED['code_hashes'].items()):continue
            staging=WORK/(RUN.name+'_code');staging.mkdir(exist_ok=False)
            for entry in z.infolist():
                assert (staging/entry.filename).resolve().is_relative_to(staging.resolve()),'Unsafe ZIP path'
                assert (entry.external_attr>>16)&0o170000 != 0o120000,'ZIP symlinks unsupported'
            z.extractall(staging);CODE=staging/'BTP';break
assert CODE is not None,'Attach the matching BTP-code-sampling input.'
CHECKPOINTS={}
for arm in ('control','guarded'):
    filename=arm+'_last.pth';wanted=EXPECTED['checkpoints'][filename]
    for surface in (INPUT,WORK):
        for candidate in sorted(surface.rglob(filename)):
            if digest(candidate)==wanted:CHECKPOINTS[arm]=candidate;break
        if arm in CHECKPOINTS:break
    if arm not in CHECKPOINTS:
        for archive in archives:
            if not zipfile.is_zipfile(archive):continue
            with zipfile.ZipFile(archive) as z:
                for member in z.namelist():
                    if Path(member).name!=filename:continue
                    payload=z.read(member)
                    if hashlib.sha256(payload).hexdigest()!=wanted:continue
                    staging=WORK/(RUN.name+'_weights');staging.mkdir(exist_ok=True)
                    candidate=staging/filename;candidate.write_bytes(payload)
                    CHECKPOINTS[arm]=candidate;break
            if arm in CHECKPOINTS:break
    assert arm in CHECKPOINTS, 'Attach paired_noise_pilot_epoch441_20261011_125140_389258.zip; missing verified '+filename
(RUN/'input_paths.json').write_text(json.dumps(dict(code=str(CODE),data=str(DATA),checkpoints={k:str(v) for k,v in CHECKPOINTS.items()}),indent=2))
print('Code:',CODE)
print('Verified pilot checkpoints:',CHECKPOINTS)

Code: /kaggle/input/datasets/arnavnigamd/btp-code-8/BTP
Verified pilot checkpoints: {'control': PosixPath('/kaggle/input/datasets/arnavnigamd/checkpoint20/paired_noise_pilot_epoch441_20261011_125140_389258/results/control_last.pth'), 'guarded': PosixPath('/kaggle/input/datasets/arnavnigamd/checkpoint20/paired_noise_pilot_epoch441_20261011_125140_389258/results/guarded_last.pth')}

In [11]:
from IPython.display import display,FileLink
try:
    with (RUN/'console.log').open('w') as log:
        common=['--code',str(CODE),'--control',str(CHECKPOINTS['control']),'--guarded',str(CHECKPOINTS['guarded'])]
        check=subprocess.run([sys.executable,'-u',str(RUN/'verify_crossed_evaluation.py'),*common],cwd=CODE,text=True,stdout=subprocess.PIPE,stderr=subprocess.STDOUT)
        print(check.stdout);log.write(check.stdout);log.flush();check.check_returncode()
        command=[sys.executable,'-u',str(RUN/'crossed_evaluation.py'),*common,'--data',str(DATA),'--out',str(RUN/'results'),'--expected',str(RUN/'expected.json')]
        proc=subprocess.Popen(command,cwd=CODE,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True,bufsize=1)
        try:
            for line in proc.stdout:
                print(line,end='',flush=True);log.write(line);log.flush()
            code=proc.wait()
            if code:raise subprocess.CalledProcessError(code,command)
        finally:
            if proc.poll() is None:
                proc.terminate()
                try:proc.wait(timeout=10)
                except subprocess.TimeoutExpired:proc.kill();proc.wait()
finally:
    archive=Path(shutil.make_archive(str(RUN),'zip',root_dir=WORK,base_dir=RUN.name))
    with zipfile.ZipFile(archive) as z:assert z.testzip() is None
    os.chdir(WORK)
    print('Download this ZIP even if an error occurred:',archive.name)
    display(FileLink(archive.name))

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
PASS: both actual pilot checkpoints, four configurations, binary/fractional noisy64x64 CUDA inputs; reverse-order bitwise repeatability; guard-on matches archived guard; unchanged model states/input; nonfinite detection and incomplete-metric contrasts. Full512x512 validation remains to run.

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
load model from /kaggle/input/datasets/arnavnigamd/checkpoint20/paired_noise_pilot_epoch441_20261011_125140_389258/results/control_last.pth
load model from /kaggle/input/datasets/arnavnigamd/checkpoint20/paired_noise_pilot_epoch441_20261011_125140_389258/results/guarded_last.pth
clean: 5/25 scenes, four combinations; 1.0min
clean: 10/25 scenes, four combinations; 2.0min
clean: 15/25 scenes, four combinations; 3.0min
clean: 20/25 scenes, four combinations; 3.9min
clean: 25/25 scenes, four combinations; 4.9min
{'condition': 'clean', 'mode': 'control_off', 'training_arm': 'control', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7519364625201984, 'PSNR': 39.10392791748047, 'SSIM': 0.9757934999465943, 'MSE': 0.00012969541974598543}
{'condition': 'clean', 'mode': 'guarded_on', 'training_arm': 'guarded', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7608742886778193, 'PSNR': 39.13199493408203, 'SSIM': 0.9760174512863159, 'MSE': 0.000129022077890113}
{'condition': 'clean', 'mode': 'control_on', 'training_arm': 'control', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7520443999058419, 'PSNR': 39.15005599975586, 'SSIM': 0.9759534478187561, 'MSE': 0.00012848101177951322}
{'condition': 'clean', 'mode': 'guarded_off', 'training_arm': 'guarded', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7609522575112688, 'PSNR': 39.05684783935547, 'SSIM': 0.9756807446479797, 'MSE': 0.00013099975796649233}
plus1_alpha0.5: 5/25 scenes, four combinations; 5.9min
plus1_alpha0.5: 10/25 scenes, four combinations; 6.9min
plus1_alpha0.5: 15/25 scenes, four combinations; 7.9min
plus1_alpha0.5: 20/25 scenes, four combinations; 8.9min
plus1_alpha0.5: 25/25 scenes, four combinations; 9.9min
{'condition': 'plus1_alpha0.5', 'mode': 'control_off', 'training_arm': 'control', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6108305433887987, 'PSNR': -8.360115586221218, 'SSIM': 0.898580641746521, 'MSE': 1297.8758979836107}
{'condition': 'plus1_alpha0.5', 'mode': 'guarded_on', 'training_arm': 'guarded', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7079456389518013, 'PSNR': 35.89875946044922, 'SSIM': 0.9714169335365296, 'MSE': 0.0002733888104557991}
{'condition': 'plus1_alpha0.5', 'mode': 'control_on', 'training_arm': 'control', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6872974688487861, 'PSNR': 35.871127166748046, 'SSIM': 0.9713983559608459, 'MSE': 0.0002748928306391463}
{'condition': 'plus1_alpha0.5', 'mode': 'guarded_off', 'training_arm': 'guarded', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6069606565213574, 'PSNR': 1.7715907716751098, 'SSIM': 0.9043558621406556, 'MSE': 38.50637350341305}
minus1_alpha0.5: 5/25 scenes, four combinations; 10.9min
minus1_alpha0.5: 10/25 scenes, four combinations; 11.9min
minus1_alpha0.5: 15/25 scenes, four combinations; 12.9min
minus1_alpha0.5: 20/25 scenes, four combinations; 13.8min
minus1_alpha0.5: 25/25 scenes, four combinations; 14.8min
{'condition': 'minus1_alpha0.5', 'mode': 'control_off', 'training_arm': 'control', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6038555339521738, 'PSNR': -8.524602682590485, 'SSIM': 0.8977232646942138, 'MSE': 207.66724863171578}
{'condition': 'minus1_alpha0.5', 'mode': 'guarded_on', 'training_arm': 'guarded', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.707570929665001, 'PSNR': 35.93922210693359, 'SSIM': 0.9714727234840393, 'MSE': 0.00027030768687836827}
{'condition': 'minus1_alpha0.5', 'mode': 'control_on', 'training_arm': 'control', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6874815354967937, 'PSNR': 35.91125717163086, 'SSIM': 0.9714513492584228, 'MSE': 0.0002718254254432395}
{'condition': 'minus1_alpha0.5', 'mode': 'guarded_off', 'training_arm': 'guarded', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.60791488815314, 'PSNR': -0.12626004576683045, 'SSIM': 0.9010469293594361, 'MSE': 101.2669332800433}
nominal_noise40: 5/25 scenes, four combinations; 15.8min
nominal_noise40: 10/25 scenes, four combinations; 16.8min
nominal_noise40: 15/25 scenes, four combinations; 17.8min
nominal_noise40: 20/25 scenes, four combinations; 18.8min
nominal_noise40: 25/25 scenes, four combinations; 19.8min
{'condition': 'nominal_noise40', 'mode': 'control_off', 'training_arm': 'control', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7425885108765347, 'PSNR': 36.98492248535156, 'SSIM': 0.9572081995010376, 'MSE': 0.0002057978417724371}
{'condition': 'nominal_noise40', 'mode': 'guarded_on', 'training_arm': 'guarded', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7492813688270814, 'PSNR': 37.21837371826172, 'SSIM': 0.9593847608566284, 'MSE': 0.00019602654909249396}
{'condition': 'nominal_noise40', 'mode': 'control_on', 'training_arm': 'control', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7430171227974569, 'PSNR': 37.25979232788086, 'SSIM': 0.9597507572174072, 'MSE': 0.00019426888786256314}
{'condition': 'nominal_noise40', 'mode': 'guarded_off', 'training_arm': 'guarded', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7486897356923083, 'PSNR': 36.74979782104492, 'SSIM': 0.9554701018333435, 'MSE': 0.0002163093991111964}
nominal_noise30: 5/25 scenes, four combinations; 20.8min
nominal_noise30: 10/25 scenes, four combinations; 21.8min
nominal_noise30: 15/25 scenes, four combinations; 22.8min
nominal_noise30: 20/25 scenes, four combinations; 23.8min
nominal_noise30: 25/25 scenes, four combinations; 24.8min
{'condition': 'nominal_noise30', 'mode': 'control_off', 'training_arm': 'control', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6619986868943043, 'PSNR': 32.002398300170896, 'SSIM': 0.8623369836807251, 'MSE': 0.0006352627044543624}
{'condition': 'nominal_noise30', 'mode': 'guarded_on', 'training_arm': 'guarded', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6653369061227624, 'PSNR': 32.47840354919433, 'SSIM': 0.8674454140663147, 'MSE': 0.0005716667848173529}
{'condition': 'nominal_noise30', 'mode': 'control_on', 'training_arm': 'control', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6646666923701742, 'PSNR': 32.55696800231934, 'SSIM': 0.8687771224975586, 'MSE': 0.0005617223272565752}
{'condition': 'nominal_noise30', 'mode': 'guarded_off', 'training_arm': 'guarded', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6632852280308484, 'PSNR': 31.498658599853517, 'SSIM': 0.8588296890258789, 'MSE': 0.0007112307264469564}
plus1_alpha0.25_noise40: 5/25 scenes, four combinations; 25.7min
plus1_alpha0.25_noise40: 10/25 scenes, four combinations; 26.7min
plus1_alpha0.25_noise40: 15/25 scenes, four combinations; 27.7min
plus1_alpha0.25_noise40: 20/25 scenes, four combinations; 28.7min
plus1_alpha0.25_noise40: 25/25 scenes, four combinations; 29.7min
{'condition': 'plus1_alpha0.25_noise40', 'mode': 'control_off', 'training_arm': 'control', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.65971162083755, 'PSNR': 8.18180344581604, 'SSIM': 0.908188099861145, 'MSE': 12.421373179126531}
{'condition': 'plus1_alpha0.25_noise40', 'mode': 'guarded_on', 'training_arm': 'guarded', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.736176400251842, 'PSNR': 34.69092376708984, 'SSIM': 0.948053457736969, 'MSE': 0.00034607998793944716}
{'condition': 'plus1_alpha0.25_noise40', 'mode': 'control_on', 'training_arm': 'control', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7214137719931274, 'PSNR': 34.80653564453125, 'SSIM': 0.9489452433586121, 'MSE': 0.0003373728401493281}
{'condition': 'plus1_alpha0.25_noise40', 'mode': 'guarded_off', 'training_arm': 'guarded', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6629819042624253, 'PSNR': -14.572891203165055, 'SSIM': 0.8749603223800659, 'MSE': 1575.0092371976375}
minus1_alpha0.25_noise40: 5/25 scenes, four combinations; 30.7min
minus1_alpha0.25_noise40: 10/25 scenes, four combinations; 31.7min
minus1_alpha0.25_noise40: 15/25 scenes, four combinations; 32.7min
minus1_alpha0.25_noise40: 20/25 scenes, four combinations; 33.7min
minus1_alpha0.25_noise40: 25/25 scenes, four combinations; 34.7min
{'condition': 'minus1_alpha0.25_noise40', 'mode': 'control_off', 'training_arm': 'control', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6698453405543302, 'PSNR': 6.858756275177002, 'SSIM': 0.9090690398216248, 'MSE': 7.831492779795081}
{'condition': 'minus1_alpha0.25_noise40', 'mode': 'guarded_on', 'training_arm': 'guarded', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7420496756618177, 'PSNR': 34.6731527709961, 'SSIM': 0.9479894161224365, 'MSE': 0.00034700270276516676}
{'condition': 'minus1_alpha0.25_noise40', 'mode': 'control_on', 'training_arm': 'control', 'inference_guard': True, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.7266860726655003, 'PSNR': 34.800072479248044, 'SSIM': 0.9489065837860108, 'MSE': 0.0003374752611853182}
{'condition': 'minus1_alpha0.25_noise40', 'mode': 'guarded_off', 'training_arm': 'guarded', 'inference_guard': False, 'valid_scenes': 25, 'expected_scenes': 25, 'status': 'complete', 'miou': 0.6801749141461171, 'PSNR': -13.96185269832611, 'SSIM': 0.8775689554214477, 'MSE': 897.3069192838669}
               condition                         comparison    baseline     changed   status  miou_change_points  psnr_change
                   clean inference_guard_on_control_weights control_off  control_on complete            0.010794     0.046128
                   clean inference_guard_on_guarded_weights guarded_off  guarded_on complete           -0.007797     0.075147
                   clean          training_arm_at_guard_off control_off guarded_off complete            0.901579    -0.047080
                   clean           training_arm_at_guard_on  control_on  guarded_on complete            0.882989    -0.018061
          plus1_alpha0.5 inference_guard_on_control_weights control_off  control_on complete            7.646693    44.231243
          plus1_alpha0.5 inference_guard_on_guarded_weights guarded_off  guarded_on complete           10.098498    34.127169
          plus1_alpha0.5          training_arm_at_guard_off control_off guarded_off complete           -0.386989    10.131706
          plus1_alpha0.5           training_arm_at_guard_on  control_on  guarded_on complete            2.064817     0.027632
         minus1_alpha0.5 inference_guard_on_control_weights control_off  control_on complete            8.362600    44.435860
         minus1_alpha0.5 inference_guard_on_guarded_weights guarded_off  guarded_on complete            9.965604    36.065482
         minus1_alpha0.5          training_arm_at_guard_off control_off guarded_off complete            0.405935     8.398343
         minus1_alpha0.5           training_arm_at_guard_on  control_on  guarded_on complete            2.008939     0.027965
         nominal_noise40 inference_guard_on_control_weights control_off  control_on complete            0.042861     0.274870
         nominal_noise40 inference_guard_on_guarded_weights guarded_off  guarded_on complete            0.059163     0.468576
         nominal_noise40          training_arm_at_guard_off control_off guarded_off complete            0.610122    -0.235125
         nominal_noise40           training_arm_at_guard_on  control_on  guarded_on complete            0.626425    -0.041419
         nominal_noise30 inference_guard_on_control_weights control_off  control_on complete            0.266801     0.554570
         nominal_noise30 inference_guard_on_guarded_weights guarded_off  guarded_on complete            0.205168     0.979745
         nominal_noise30          training_arm_at_guard_off control_off guarded_off complete            0.128654    -0.503740
         nominal_noise30           training_arm_at_guard_on  control_on  guarded_on complete            0.067021    -0.078564
 plus1_alpha0.25_noise40 inference_guard_on_control_weights control_off  control_on complete            6.170215    26.624732
 plus1_alpha0.25_noise40 inference_guard_on_guarded_weights guarded_off  guarded_on complete            7.319450    49.263815
 plus1_alpha0.25_noise40          training_arm_at_guard_off control_off guarded_off complete            0.327028   -22.754695
 plus1_alpha0.25_noise40           training_arm_at_guard_on  control_on  guarded_on complete            1.476263    -0.115612
minus1_alpha0.25_noise40 inference_guard_on_control_weights control_off  control_on complete            5.684073    27.941316
minus1_alpha0.25_noise40 inference_guard_on_guarded_weights guarded_off  guarded_on complete            6.187476    48.635005
minus1_alpha0.25_noise40          training_arm_at_guard_off control_off guarded_off complete            1.032957   -20.820609
minus1_alpha0.25_noise40           training_arm_at_guard_on  control_on  guarded_on complete            1.536360    -0.126920
Download this ZIP even if an error occurred: crossed_noise_pilot_20261011_141656_720753.zip

/kaggle/working/crossed_noise_pilot_20261011_141656_720753.zip

In [12]:
import pandas as pd
manifest=json.loads((RUN/'results/experiment.json').read_text())
assert manifest['status'] in ('completed','completed_with_nonfinite_cases'),'Share the failure archive.'
assert manifest['completed_forwards']==700 and manifest['diagonal_checks']==350 and manifest['model_state_unchanged']
display(pd.read_csv(RUN/'results/summary.csv'))
display(pd.read_csv(RUN/'results/contrasts.csv'))
print('Nonfinite cases:',len(manifest['nonfinite_cases']))
print('Download crossed_noise_pilot ZIP above and share its local path.')

,condition,mode,training_arm,inference_guard,valid_scenes,expected_scenes,status,miou,PSNR,SSIM,MSE
0,clean,control_off,control,False,25,25,complete,0.751936,39.103928,0.975793,0.000130
1,clean,guarded_on,guarded,True,25,25,complete,0.760874,39.131995,0.976017,0.000129
2,clean,control_on,control,True,25,25,complete,0.752044,39.150056,0.975953,0.000128
3,clean,guarded_off,guarded,False,25,25,complete,0.760952,39.056848,0.975681,0.000131
4,plus1_alpha0.5,control_off,control,False,25,25,complete,0.610831,-8.360116,0.898581,1297.875898
5,plus1_alpha0.5,guarded_on,guarded,True,25,25,complete,0.707946,35.898759,0.971417,0.000273
6,plus1_alpha0.5,control_on,control,True,25,25,complete,0.687297,35.871127,0.971398,0.000275
7,plus1_alpha0.5,guarded_off,guarded,False,25,25,complete,0.606961,1.771591,0.904356,38.506374
8,minus1_alpha0.5,control_off,control,False,25,25,complete,0.603856,-8.524603,0.897723,207.667249
9,minus1_alpha0.5,guarded_on,guarded,True,25,25,complete,0.707571,35.939222,0.971473,0.000270
10,minus1_alpha0.5,control_on,control,True,25,25,complete,0.687482,35.911257,0.971451,0.000272
11,minus1_alpha0.5,guarded_off,guarded,False,25,25,complete,0.607915,-0.126260,0.901047,101.266933
12,nominal_noise40,control_off,control,False,25,25,complete,0.742589,36.984922,0.957208,0.000206
13,nominal_noise40,guarded_on,guarded,True,25,25,complete,0.749281,37.218374,0.959385,0.000196
14,nominal_noise40,control_on,control,True,25,25,complete,0.743017,37.259792,0.959751,0.000194
15,nominal_noise40,guarded_off,guarded,False,25,25,complete,0.748690,36.749798,0.955470,0.000216
16,nominal_noise30,control_off,control,False,25,25,complete,0.661999,32.002398,0.862337,0.000635
17,nominal_noise30,guarded_on,guarded,True,25,25,complete,0.665337,32.478404,0.867445,0.000572
18,nominal_noise30,control_on,control,True,25,25,complete,0.664667,32.556968,0.868777,0.000562
19,nominal_noise30,guarded_off,guarded,False,25,25,complete,0.663285,31.498659,0.858830,0.000711
20,plus1_alpha0.25_noise40,control_off,control,False,25,25,complete,0.659712,8.181803,0.908188,12.421373
21,plus1_alpha0.25_noise40,guarded_on,guarded,True,25,25,complete,0.736176,34.690924,0.948053,0.000346
22,plus1_alpha0.25_noise40,control_on,control,True,25,25,complete,0.721414,34.806536,0.948945,0.000337
23,plus1_alpha0.25_noise40,guarded_off,guarded,False,25,25,complete,0.662982,-14.572891,0.874960,1575.009237
24,minus1_alpha0.25_noise40,control_off,control,False,25,25,complete,0.669845,6.858756,0.909069,7.831493
25,minus1_alpha0.25_noise40,guarded_on,guarded,True,25,25,complete,0.742050,34.673153,0.947989,0.000347
26,minus1_alpha0.25_noise40,control_on,control,True,25,25,complete,0.726686,34.800072,0.948907,0.000337
27,minus1_alpha0.25_noise40,guarded_off,guarded,False,25,25,complete,0.680175,-13.961853,0.877569,897.306919

,condition,comparison,baseline,changed,status,miou_change_points,psnr_change
0,clean,inference_guard_on_control_weights,control_off,control_on,complete,0.010794,0.046128
1,clean,inference_guard_on_guarded_weights,guarded_off,guarded_on,complete,-0.007797,0.075147
2,clean,training_arm_at_guard_off,control_off,guarded_off,complete,0.901579,-0.047080
3,clean,training_arm_at_guard_on,control_on,guarded_on,complete,0.882989,-0.018061
4,plus1_alpha0.5,inference_guard_on_control_weights,control_off,control_on,complete,7.646693,44.231243
5,plus1_alpha0.5,inference_guard_on_guarded_weights,guarded_off,guarded_on,complete,10.098498,34.127169
6,plus1_alpha0.5,training_arm_at_guard_off,control_off,guarded_off,complete,-0.386989,10.131706
7,plus1_alpha0.5,training_arm_at_guard_on,control_on,guarded_on,complete,2.064817,0.027632
8,minus1_alpha0.5,inference_guard_on_control_weights,control_off,control_on,complete,8.362600,44.435860
9,minus1_alpha0.5,inference_guard_on_guarded_weights,guarded_off,guarded_on,complete,9.965604,36.065482
10,minus1_alpha0.5,training_arm_at_guard_off,control_off,guarded_off,complete,0.405935,8.398343
11,minus1_alpha0.5,training_arm_at_guard_on,control_on,guarded_on,complete,2.008939,0.027965
12,nominal_noise40,inference_guard_on_control_weights,control_off,control_on,complete,0.042861,0.274870
13,nominal_noise40,inference_guard_on_guarded_weights,guarded_off,guarded_on,complete,0.059163,0.468576
14,nominal_noise40,training_arm_at_guard_off,control_off,guarded_off,complete,0.610122,-0.235125
15,nominal_noise40,training_arm_at_guard_on,control_on,guarded_on,complete,0.626425,-0.041419
16,nominal_noise30,inference_guard_on_control_weights,control_off,control_on,complete,0.266801,0.554570
17,nominal_noise30,inference_guard_on_guarded_weights,guarded_off,guarded_on,complete,0.205168,0.979745
18,nominal_noise30,training_arm_at_guard_off,control_off,guarded_off,complete,0.128654,-0.503740
19,nominal_noise30,training_arm_at_guard_on,control_on,guarded_on,complete,0.067021,-0.078564
20,plus1_alpha0.25_noise40,inference_guard_on_control_weights,control_off,control_on,complete,6.170215,26.624732
21,plus1_alpha0.25_noise40,inference_guard_on_guarded_weights,guarded_off,guarded_on,complete,7.319450,49.263815
22,plus1_alpha0.25_noise40,training_arm_at_guard_off,control_off,guarded_off,complete,0.327028,-22.754695
23,plus1_alpha0.25_noise40,training_arm_at_guard_on,control_on,guarded_on,complete,1.476263,-0.115612
24,minus1_alpha0.25_noise40,inference_guard_on_control_weights,control_off,control_on,complete,5.684073,27.941316
25,minus1_alpha0.25_noise40,inference_guard_on_guarded_weights,guarded_off,guarded_on,complete,6.187476,48.635005
26,minus1_alpha0.25_noise40,training_arm_at_guard_off,control_off,guarded_off,complete,1.032957,-20.820609
27,minus1_alpha0.25_noise40,training_arm_at_guard_on,control_on,guarded_on,complete,1.536360,-0.126920

Nonfinite cases: 0
Download crossed_noise_pilot ZIP above and share its local path.